### ISSUE TITLE
Leveraging of Chrome's X server

### ISSUE THREAD

**Issue by davidradkowski** [dnschneid/crouton#1]
Hi

Not an issue, more a question/feature request:
Would it be possible to use Chorme's X server to run chroot-ed X/gtk apps?
Some quirky ssh tunneling?

Cheers

**Comment by Pocc** [comment]
I'm trying to follow this guide, but I'm getting some errors:

Gtk-WARNING **: cannot open display:

Invalid MIT-MAGIC-COOKIE-1 keyOpenbox-Message: 
Failed to open the display from the DISPLAY environment variable.

I'm working on a Toshiba Chromebook 2, and have set up cinnamon, lxde, and xfce chroots. I'm assuming it's something stupid simple if the DISPLAY environment variable is having issues.

**Comment by dnschneid** [comment]
This is mostly going the way of the dodo with the advent of xiwi (X in a window) and the migration to Freon (Chromium's new display server) fundamentally breaking host-x11.
