### ISSUE TITLE
How do I remove crouton? (I want to make a fresh install)

### ISSUE THREAD

**Issue by lrvaka** [dnschneid/crouton#10]
I just want to make a fresh install of crouton.

**Comment by Lvl50prod** [comment]
yo 2 years later it says sudo: delete-chroot: command not found what do I do?

**Comment by MrHallway0** [comment]
Check out #4378.

**Comment by Askofep-1** [comment]
@Lvl50prod
> yo 2 years later it says sudo: delete-chroot: command not found what do I do?

IDK
