### ISSUE TITLE
Bringing back the Cinnamon Target?

### ISSUE THREAD

**Issue by Lord-Buckles** [dnschneid/crouton#1000]
Would it be possible to bring back the Cinnamon Target now that there are stable PPAS for Ubuntu 12.04 and 14.04?

http://www.webupd8.org/2014/06/new-cinnamon-stable-ubuntu-ppas-ubuntu.html

I looked into adding a Cinnamon Target but I don't really know what I'm doing, so wondered if the PPA could just be replaced with Tsvetko's repository in the old Target.

Sorry if this issue has already been covered but I was unable to find any mention of it.

**Comment by JoshMcCullough** [comment]
:+1:  for Mint/Cinnamon support!
