### ISSUE TITLE
traditional/Australian scrolling in ubuntu opposite to chromeos

### ISSUE THREAD

**Issue by gibspaulding** [dnschneid/crouton#1012]
In the middle of installing crouton my trackpad's scrolling switched to "Australian" scrolling style, however once I started unity I found that Ubuntu still used traditional scrolling.  When I changed back to traditional scrolling in ChromeOS it switched Ubuntu to natural scrolling and vice versa.  Whatever direction I set ChromeOS to scroll, Unity will scroll in the opposite direction.

I have tried changing the scrolling style from Ubuntu, but there is not an option under settings.
I also tried changing the scroll direction in ChromeOS while logged out of Unity, but upon starting the chroot again it is switched just the same.
I even tried powerwashing and reinstalling my whole crouton set up this time changing the ChromeOS setting back before crouton was done installing, but again when starting unity the scrolling direction was opposite to ChromeOS

Sorry if I'm missing something, but I haven't been able to find anything about this so I figured I'd post it here.

Samsung Chromebook XE303C12 (arm)
~$ croutonversion
crouton: version 1-20140826230534~master:85cae7b9
release: precise
architecture: armhf
targets: unity
host: version 5841.98.0 (Official Build) stable-channel daisy

**Comment by dnschneid** [comment]
This may be the same root cause as [crbug.com/460548](http://crbug.com/460548)

**Comment by Dave89rr** [comment]
@drinkcat or @dnschneid Have you guys been able to make any progress? 😄 
I installed linux yesterday, and today I noticed that no matter what I tried, the scrolling was inverted from ChromeOS to Linux.


### Specs:
I realize I might be giving you more info than you need, but better safe than sorry.

Chromebook: Samsung Chromebook 3
Model: 500C13-K01
ChromeOS Version: 57.0.2987.146 (64-bit)
Platform: 9202.64.0 (Official Build)
ARC Version: 3880239
Firmware Google_Celes.7287.92.74
Crouton version 1-20170315143304~master:95589555
Linux is Xenial Xerus but when I run `uname -r` it gives me `3.18.0-13759-g98e7e0e` so I'm not sure on the version number for my linux install.
