### ISSUE TITLE
Target Practice: Adding Target flags via link 

### ISSUE THREAD

**Issue by moocow1452** [dnschneid/crouton#1027]
Rather than having to fork Crouton every single time one wants to add a target to customize their build, could a target be added to take a link from a pastebin or gist, write a new target curled from the raw text and allow the instructions to play out as an otherwise native target?

**Comment by dnschneid** [comment]
Split the bundle part into #2100

**Comment by dnschneid** [comment]
Multiple -T should be supported, and maybe some flag that says whether install should fail if the target is not fetchable.
