### ISSUE TITLE
"sudo startunity" not working

### ISSUE THREAD

**Issue by funkyfishy** [dnschneid/crouton#1031]
When I enter 'sudo startunity' in the crosh shell I get this output:

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Unknown username "whoopsie" in message bus configuration file

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri Aug 29 00:55:05 PDT 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=d3f24a78-c0bb-814d-a061-db9f68591db6/PARTNROFF=1 hashtree=PARTUUID=d3f24a78-c0bb-814d-a061-db9f68591db6/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=d1b86410b90395558333e0080eaad3d0c9bc65d0 salt=c0610a277b425d125455cae71d3eaf4a67bce8fe9207a1410cbbdd02275304f3" noinitrd vt.global_cursor_default=0 kern_guid=d3f24a78-c0bb-814d-a061-db9f68591db6 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3 
Build Date: 30 July 2014  12:21:54AM
xorg-server 2:1.15.1-0ubuntu2.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed Sep 10 07:30:28 2014
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $ 

I don't know what went wrong but after sending me to a blank screen for a few seconds it comes returns to crosh. Could someone please help me on how to fix this issue.

**Comment by Cool-N-boy** [comment]
Hey, I think you should try updating your chroot because that can sometimes fix anything not working 
if that doesnt work try restarting your chromebook

**Comment by Cool-N-boy** [comment]
I am also Cool N boy from the youtube channel Cool N boy Xbox 360 Gamer
