### ISSUE TITLE
Is it possible to use autofs with Crouton?

### ISSUE THREAD

**Issue by iainroyle** [dnschneid/crouton#1046]
[Crouton on Asus C200, trusty gnome installed]
When trying to install autofs I get the following error(s):

The following NEW packages will be installed:
  autofs
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/282 kB of archives.
After this operation, 1,671 kB of additional disk space will be used.
Selecting previously unselected package autofs.
(Reading database ... 67591 files and directories currently installed.)
Preparing to unpack .../autofs_5.0.7-3ubuntu3_amd64.deb ...
Unpacking autofs (5.0.7-3ubuntu3) ...
Processing triggers for man-db (2.6.7.1-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up autofs (5.0.7-3ubuntu3) ...
runlevel:/var/run/utmp: No such file or directory
initctl: Unknown job: autofs

Is it possible to use Crouton with autofs? Anything I can do to resolve these problems?

Incidentally, I'm trying to mount a drive over sshfs (which works temporarily without autofs) which is quite useful for space-limited Chromebooks.

Thanks!

**Comment by mark-hahn** [comment]
I know this is a year old but I'm trying to do the exact thing, which is to run autofs on my pixel2.

Thanks to @divx118's help on #2276 I was able to create and install autofs4.ko.  I now find I have the kernel module autofs4, which was available for my kernel version, but the ubuntu 12.0.4 I have in my chroot only has the autofs5 package.  I know this because of 

```
$  dpkg -l | grep autofs
ii  autofs                                      5.0.6-0ubuntu5.2                     dummy transitional package from autofs to autofs5
ii  autofs5                                     5.0.6-0ubuntu5.2                     kernel-based automounter for Linux, version 5
```

Should the autofs4 module and autofs5 package work together?  Now matter how I try to start autofs I get the error `Unknown job`.

When I run /etc/init.d/autofs status i get 

```
Rather than invoking init scripts through /etc/init.d, use the service(8)
utility, e.g. service autofs status
initctl: Unknown job: autofs

Since the script you are attempting to invoke has been converted to an
Upstart job, you may also use the status(8) utility, e.g. status autofs
status: Unknown job: autofs
```

After typing this in I realize this isn't really a crouton question but a linux newbie question.  I don't even know how to install an old autofs4 version.  But any help would be really appreciated.

**Comment by divx118** [comment]
@mark-hahn Did you try starting automountd by hand? You could put it in rc.local to automatically start it when entering the chroot.

**Comment by mark-hahn** [comment]
Hmmm.   I'm getting the same "Unknown job" error with `automountd`.  There is something fishy going on here and my linux-fu isn't strong enough.  I don't understand it.

BTW, the autofs article [here](https://wiki.archlinux.org/index.php/Autofs#Installation) says "Note: You no longer need to load autofs4 module."  This makes me think that autofs5 doesn't need a kernel module anymore although I could be misunderstanding the note.  If so then I've wasted much effort making `autofs4.ko`.  At least I've learned a lot about kernel modules.

So there is the possibility that I'm just back to the basic question, "How do I get autofs5 working on Crouton?".

**Comment by mark-hahn** [comment]
I just tried the `automount` command.  I did `automap -m` which lists the mappings and it showed my mappings as set up properly.  However, when I run`automount` I get the error 

```
automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.
```

This is exactly where I started a couple of days ago.  At the time I didn't understand the message.  Now I think it means I'm missing some autofs5 capability in the kernel.

I have gone in a big circle.  I'm about to give up and figure out a different workflow that doesn't use auto-mounting.

**Comment by mark-hahn** [comment]
I found this [here](http://apt-browse.org/browse/ubuntu/precise/main/i386/autofs5/5.0.6-0ubuntu5/file/usr/share/doc/autofs5/README.v5.release).

```
- `autofs' version 5.0.0 will refuse to run if it cannot find an
   autofs4 kernel module that supports protocol version 5.00 or above.
```

So it appears I need a newer `autofs4`.  I assume the autofs4 version that I get when I recompile my chromebook kernel 3.14 is fixed to this kernel version and I can't use autofs5 until I get a newer kernel.

I'll quit spamming this list now.  I give up.

**Comment by divx118** [comment]
Just a question, what is the purpose for you to use autofs? Convenience? You know you can mount networkdrives with sshfs, smb probably nfs also possible, but didn't try it yet myself. Just curious :)
BTW for smb drives there is now also a [chrome app](https://chrome.google.com/webstore/detail/file-system-for-windows/mfhnnfciefdpolbelmfkpmhhmlkehbdf?utm_source=chrome-app-launcher-search) For sftp also [see here](https://chrome.google.com/webstore/detail/sftp-file-system/gbheifiifcfekkamhepkeogobihicgmn?utm_source=chrome-app-launcher-search)

**Comment by mark-hahn** [comment]
It is pretty much for convenience.  I edit all source on the chromebook and
run on the server immediately.  I've been running sshfs for some time and
love it.  I close and open the chromebook many times during the day and it
would be nice if I could just forget about it instead of using my aliases
to fix things.

**Comment by divx118** [comment]
Yep, understandable. I am going to give it a try myself... lets see if I can get it working.

**Comment by divx118** [comment]
Update, just tried with sshfs and it seems to work for me. At least my sshfs mounts are mounted :)
Note that I am using trusty 14.04 which could be a difference.
```
(trusty)m@localhost:~$ sudo automount -V

Linux automount version 5.0.7

Directories:
        config dir:     /etc/default
        maps dir:       /etc
        modules dir:    /usr/lib/x86_64-linux-gnu/autofs

Compile options:
  ENABLE_FORCED_SHUTDOWN ENABLE_IGNORE_BUSY_MOUNTS WITH_HESIOD 
  WITH_LDAP WITH_SASL LIBXML2_WORKAROUND 

(trusty)m@localhost:~$ uname -a
Linux localhost 3.8.11 #1 SMP Wed Dec 2 23:51:17 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
(trusty)m@localhost:~$ lsmod |grep autofs4
autofs4                27612  3 
```

Also note that you need to start the automount daemon yourself you can do that in /etc/rc.local. With the following flags you will get some debug output also see [here](http://www.mccambridge.org/blog/2007/05/totally-seamless-sshfs-under-linux-using-fuse-and-autofs/) this is how I set autofs up now.
`$ sudo /usr/sbin/automount -d -f -v`

**Comment by divx118** [comment]
@mark-hahn I did a little write up on how to get autofs working https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc)#mounting-network-shares-with-autofs If you are still interested let me know if it works for you too.

**Comment by mark-hahn** [comment]
Thanks mucho.  I will test it in a day or two.

**Comment by divx118** [comment]
BTW I tried cifs mounts, they work, but  require the modules cifs.ko and md4.ko. nfs didn't work out of the box, but almost certain it only needs the nfs.ko module. Still have to build that and test.

**Comment by mark-hahn** [comment]
Is there any advantage of nfs over sshfs?  I really like the simplicity
of sshfs.

**Comment by divx118** [comment]
@mark-hahn Well performance is better with nfs, however if you don't have lots of data going back and forth sshfs works good enough. I have a synology NAS, which has support for nfs and cifs shares, so for me it is easier to use those instead of sshfs.

**Comment by mark-hahn** [comment]
Well, I do need performance.  I'm playing video from a file in the remote
directory.

Let me know how nfs goes.

**Comment by divx118** [comment]
@mark-hahn nfs mounts work too, with some additional modules. I updated https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc) with the info

**Comment by mark-hahn** [comment]
Thank you very much.  I can't wait to try this.

**Comment by mark-hahn** [comment]
I followed the instructions and ended up with the same error as always (see my earlier posts) ...

```
$ /usr/sbin/automount -d -f -v
/usr/sbin/automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.
```

Any idea what I'm doing wrong?

**Comment by divx118** [comment]
@mark-hahn Hmm strange, are you sure autofs4 is loaded `lsmod |grep autofs4`, because for me it also worked on precise. I tried on trusty and precise.

**Comment by mark-hahn** [comment]
Yes, I did everything in the instructions and I got no errors.

What kernel do you have on your chromebook?  Mine is 3.14.

**Comment by divx118** [comment]
I have 3.8.11 an older version kernel then yours. The autofs4 module has to be loaded before you start automount Just asking to be sure you have done that. 


What is your version of automount?
```
sudo automount -V

Linux automount version 5.0.7

Directories:
        config dir:     /etc/default
        maps dir:       /etc
        modules dir:    /usr/lib/x86_64-linux-gnu/autofs

Compile options:
  ENABLE_FORCED_SHUTDOWN ENABLE_IGNORE_BUSY_MOUNTS WITH_HESIOD 
  WITH_LDAP WITH_SASL LIBXML2_WORKAROUND 
```

**Comment by mark-hahn** [comment]
Linux automount version 5.0.6

Directories:
        config dir:     /etc/default
        maps dir:       /etc
        modules dir:    /usr/lib/autofs

Compile options:
  ENABLE_FORCED_SHUTDOWN ENABLE_IGNORE_BUSY_MOUNTS WITH_HESIOD 
  WITH_LDAP WITH_SASL LIBXML2_WORKAROUND

**Comment by mark-hahn** [comment]
and ...

```
oo(~). l /usr/lib/autofs
total 1.2M
4.0K drwxr-xr-x  2 root 4.0K Dec  4 22:25 .
 20K drwxr-xr-x 88 root  20K Dec 13 23:45 ..
116K -rw-r--r--  1 root 116K Jun  3  2014 lookup_file.so
   0 lrwxrwxrwx  1 root   14 Jun  3  2014 lookup_files.so -> lookup_file.so
116K -rw-r--r--  1 root 116K Jun  3  2014 lookup_hosts.so
120K -rw-r--r--  1 root 120K Jun  3  2014 lookup_multi.so
   0 lrwxrwxrwx  1 root   12 Jun  3  2014 lookup_nis.so -> lookup_yp.so
108K -rw-r--r--  1 root 108K Jun  3  2014 lookup_nisplus.so
104K -rw-r--r--  1 root 104K Jun  3  2014 lookup_program.so
100K -rw-r--r--  1 root 100K Jun  3  2014 lookup_userhome.so
108K -rw-r--r--  1 root 108K Jun  3  2014 lookup_yp.so
 12K -rw-r--r--  1 root  11K Jun  3  2014 mount_afs.so
104K -rw-r--r--  1 root 104K Jun  3  2014 mount_autofs.so
 16K -rw-r--r--  1 root  15K Jun  3  2014 mount_bind.so
 16K -rw-r--r--  1 root  15K Jun  3  2014 mount_changer.so
 16K -rw-r--r--  1 root  15K Jun  3  2014 mount_ext2.so
   0 lrwxrwxrwx  1 root   13 Jun  3  2014 mount_ext3.so -> mount_ext2.so
   0 lrwxrwxrwx  1 root   13 Jun  3  2014 mount_ext4.so -> mount_ext2.so
 20K -rw-r--r--  1 root  19K Jun  3  2014 mount_generic.so
 52K -rw-r--r--  1 root  51K Jun  3  2014 mount_nfs.so
   0 lrwxrwxrwx  1 root   12 Jun  3  2014 mount_nfs4.so -> mount_nfs.so
156K -rw-r--r--  1 root 153K Jun  3  2014 parse_sun.so
/root /usr/lib/autofs
```

**Comment by divx118** [comment]
Oh another question just to be sure you run `/usr/sbin/automount -d -f -v` as root? Putting sudo in front of it will also do.

**Comment by mark-hahn** [comment]
I always run as root user in all logins in all PCs.  Please don't lecture
me.   :-)  I've been doing this since 1970 and I haven't had a problem
yet.  When I mentioned this before my message was deleted.  So read this
quickly.  :-)

**Comment by mark-hahn** [comment]
I've found a solution that works well enough for me now.  I put the sshfs command in .bashrc and I use the reconnect option.  It seems to be working well so far.  I can close the lid on my chromebook without losing the mount.

Thanks for your help.  Any more ideas are welcome.

**Comment by divx118** [comment]
np, Just curious were that error comes from. I wish I had a pixel2 here, so I could reproduce it. Still happy you found a solution for now.

A bit off topic since you play videos over your network, there is now [VLC player for chromeos](https://chrome.google.com/webstore/detail/vlc/obpdeolnggmbekmklghapmfpnfhpcndf) No network support yet (not working), but it should be fixed in the near future.

**Comment by mark-hahn** [comment]
> there is now VLC player for chromeos
<https://chrome.google.com/webstore/detail/vlc/obpdeolnggmbekmklghapmfpnfhpcndf>


Thx.  Good to know.
