### ISSUE TITLE
Touchscreen events only work if application started with touch

### ISSUE THREAD

**Issue by ComputerLag** [dnschneid/crouton#1050]
Touchscreen works perfectly, sends all touch events ONLY if you start the application from the menu using the touchscreen.

if the application is launched with the command line or the mouse cursor, it will completely ignore all touch events.

I tested with Google Chrome and my own SDL example program. I confirmed in my own example program it can detect the device is touch enabled even if you start it command line, but the events only fire if you touch an application shortcut on unity or xfce application launchers.

**Comment by ComputerLag** [comment]
With the touch target installed it is still an issue. The touch target actually reduces touch functionality, because the previous workaround no longer will work starting programs using touch.

The touch target does scroll the window, but true touch events are not functioning. Also the scrolling by the touch target is unappealing as it is jerky compared to the smooth inertia scrolling provided by chrome when sending real touch events.

Below is an example page using canvas and javascript touch events. On multitouch devices you can paint one line per finger, it is also a simple way to test for touch events because mouse cursor clicks are ignored. So if you can paint on the test touch events are working properly.

http://www.paulirish.com/demo/multi
With the touch target, the touch events NEVER work.
Without the touch target, launching chrome using the touch screen to tap the icon touch events work.
Without the touch target, launching chrome using the touchpad to click on the icon touch events do not work.

**Comment by ComputerLag** [comment]
for chrome there is a workaround for getting touch working. get the ID of the touchscreen
```xinput list```

start chrome with the following parameters (replace 12 with your touch device ID)
```google-chrome --touch-devices=12```

Maybe this is all software having issues detecting touchscreen? Touch events are now working perfectly in chrome after adding the parameter, better than just launching with the touchscreen. Closing tabs and highlighting text with touch did not work previousley, it now does.

I don't have any other programs to test but i'm assuming a lot of software on linux simply does not readily detect touchscreens or support them. I will re-open this issue if I find any evidence otherwise.

**Comment by dnschneid** [comment]
Thanks.  Touch support on Linux is generally not very good.  Please let us know if this comes up with other applications or situations.
