### ISSUE TITLE
When switching back to Chrome OS crouton crashes and cannot switch back

### ISSUE THREAD

**Issue by DaBino** [dnschneid/crouton#1051]
After switch into linux on my Dell Chromebook 11 using the command sudo startxfce4 everything works fine but when I use CTRL + Shift + ALT + Back to switch into Chrome OS it doesn't allow me to switch back

This is what happens from the point of running the command to switching back to Chrome

Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri Aug 29 00:54:53 PDT 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=abee3104-2e02-1a42-9a42-82869515e73e/PARTNROFF=1 hashtree=PARTUUID=abee3104-2e02-1a42-9a42-82869515e73e/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=2de3a02d3b93d14d001d4d63b01caeb6cbb54751 salt=a1c5902bd1afa4423d5fa894efe20752e6869c18924a971f776cf69be3c790ab" noinitrd vt.global_cursor_default=0 kern_guid=abee3104-2e02-1a42-9a42-82869515e73e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic 
Build Date: 07 August 2014  11:49:36AM
xorg-server 2:1.15.1-0ubuntu2~precise2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.2.log", Time: Wed Sep 17 15:41:01 2014
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
xfce4-session: No gpg or ssh authentication agent found

(polkit-gnome-authentication-agent-1:20794): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:20794): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfce4-panel:20788): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(Thunar:20790): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfwm4:20784): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-session:20774): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfdesktop:20792): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:20792): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:20792): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:20792): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(wrapper:20828): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:20830): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfsettingsd:20805): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfdesktop:20792): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(II) AIGLX: Suspending AIGLX clients for VT switch

I've updated to the most recent version and this still happens.

after running sudo enter-chroot -n precise croutonversion this is the output

Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20140915182125~master:4f5c8f73
release: precise
architecture: amd64
targets: xfce
host: version 5978.80.0 (Official Build) stable-channel wolf 
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

**Comment by lucidry** [comment]
I know this comment thread is a bit old, but I wanted to post to thank you for that, the ctrl alt forward (dev console) then ctrl alt refresh allowed me to get back to my linux!
