### ISSUE TITLE
Keyboard mods lost after screensaver kicks in...

### ISSUE THREAD

**Issue by hkoster1** [dnschneid/crouton#109]
I've collected a few keyboard modifications on my Samsung ARM Chromebook (using xmodmap) in my script /usr/local/bin/keyboard, and have this file executed automatically when starting the LXDE chroot. Those modifications are then active, but are lost whenever I switch back-and-forth to ChromeOS or whenever the screensaver kicks in, requiring me to run my keyboard script again. Not a big issue, but more a puzzle...

**Comment by matttproud** [comment]
Hi, I know that this issue is old and marked as closed, but I see something similar on a Ubuntu Trusty install with any screensaver (using XScreenSaver at the moment).  Did anyone find a root cause for why the XServer (or whatever it is) is resetting the `setxkbmap` after the login?
