### ISSUE TITLE
external usb wifi device

### ISSUE THREAD

**Issue by NoPinky** [dnschneid/crouton#1090]
Hello,
is there a way to make kali detect an usb wifi dongle and actually use it as a networking device? I just want to be able to put that usb wifi dongle into monitor mode and do wifi penetration tests.
With lsusb I can see the usb wifi device (mine has an atheros chip) is listed correctly. dmesg tells me that it is connected and shows no errors.

**Comment by frafrichile** [comment]
Did you ever find a solution for this ?

**Comment by divx118** [comment]
@frafrichile if the wifi device is supported by chromeos it should be possible. This `Sweex LW313 802.11n Adapter [ralink rt2770 + rt2720]` works for me on chromeos. There should be other ones that are supported, just depends if the driver module is included in the chromeos kernel.

**Comment by NoPinky** [comment]
@divx118 and you are sure that it will show up when you type `airmon-ng` or only under `dmesg usb`?

**Comment by frafrichile** [comment]
It will not show under airmon-ng
it does show under dmesg and under lsusb
I believe the firmware needs to be installed but unsure to do this.

**Comment by divx118** [comment]
@NoPinky Yes  it will show under airmon-ng. The wifi device need to work under chromeos, else you will have to build your own driver module with firmware. The one I have works out of the box in chromeos on my HP chromebook 14 with the 3.8.11 kernel. In chromeos I can connect to 2 wifi networks simultaneously.
 
```
chronos@localhost / $ ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 580  bytes 36922 (36.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 580  bytes 36922 (36.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.215  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::3e77:e6ff:fe9f:3c7b  prefixlen 64  scopeid 0x20<link>
        ether 3c:77:e6:9f:3c:7b  txqueuelen 1000  (Ethernet)
        RX packets 27365  bytes 30406299 (28.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14534  bytes 2197521 (2.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1mon: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        unspec 00-16-0A-20-5F-D6-EA-1B-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 81  bytes 13583 (13.2 KiB)
        RX errors 0  dropped 81  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
(kali)m@localhost:~$ sudo airmon-ng start wlan1
Found 3 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to kill (some of) them!

  PID Name
  545 wpa_supplicant
22827 dhcpcd
25621 dhcpcd

PHY     Interface       Driver          Chipset

phy0    wlan0           ath9k           Atheros Communications Inc. AR9462 Wireless Network Adapter (rev 01)
phy2    wlan1           rt2800usb       Sweex LW313 802.11n Adapter [ralink rt2770 + rt2720]
                (mac80211 monitor mode vif enabled for [phy2]wlan1 on [phy2]wlan1mon)
                (mac80211 station mode vif disabled for [phy2]wlan1)
```

**Comment by NoPinky** [comment]
@divx118 
well... lucky you, I have an acer c710. It only has a 3.4 kernel and I from my 3 different dongles, none works out of the box. And I can't find any info about which would work for sure, like the chipset compatibility list. So I don't really know what I could buy.
I'm pretty much a script kiddie when it comes to linux internals, I only follow tuts and I'm only familiar to the most basic commands. :stuck_out_tongue_closed_eyes:
