### ISSUE TITLE
ld unable to find lgcc or lgcc_s

### ISSUE THREAD

**Issue by ofuangka** [dnschneid/crouton#1091]
I just recently started getting an issue trying to update crouton. It can't seem to find some dependencies.  Here's the relevant portion of the output:

Patching CRAS (volume control)...
patching file alsa_plugin/ctl_cras.c
Compiling CRAS (i386)...
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.7/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.7/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

Any suggestions?

**Comment by abliss** [comment]
FWIW I had the same problem with gcc-4.9 selected. Seems to work after using update-alternatives to revert to 4.8. Thanks!
