### ISSUE TITLE
Login incorrect when switching between ChromeOS and Ubuntu

### ISSUE THREAD

**Issue by rdoyle128** [dnschneid/crouton#1094]
To clarify, I've seen this issue before, but it wasn't resolved for me.

Here's a step-by-step on what I've run into:
1. Bring up Crosh, >shell, sudo startunity. I log into Ubuntu just fine.
2. Ctrl + Alt + Left, move to ChromeOS
3. Ctrl + Alt + Right, move back to Ubuntu. I arrive at the Developer Console
4. The console is requesting a localhost login. I enter my Ubuntu login information.
5. It tells me "Login incorrect" despite the fact that I entered the correct information

My question is, how do I get back into Ubuntu after switching to ChromeOS and then back again? I know it's still running, but I'm locked out. My only choice has been to cancel the process in Chronos on the ChromeOS side and boot Ubuntu back up, but of course this means I lose my Ubuntu session completely.

Shouldn't I be able to switch back and forth between Ubuntu and ChromeOS without restarting Ubuntu every time? Is there a way to stop it from locking me out/sending me to the developer console every time I switch between OSes? I've tried setting it to auto login, I've tried making a user account without a password, the result is the same, I'm locked out in the Developer Console when I use Ctrl + Alt + Left to get back into Ubuntu.

**Comment by Anish0000** [comment]
Again not working

**Comment by Anish0000** [comment]
what should i do

**Comment by Anish0000** [comment]
login incorrect!!!!!///?/////?/??////////////////////????//??/?
