### ISSUE TITLE
Switching back causes dual screen to become unstable

### ISSUE THREAD

**Issue by haarts** [dnschneid/crouton#1105]
First off, _great_ work on crouton. Love it.

I run trusty just fine with crouton. The external display is recognized and works well (start trusty, then plug in monitor). On ChromeOS it's all good too (start ChromeOS, then plug in monitor). Switching from ChromeOS to trusty again works nearly instantly and flawlessly. The issue arises when switching FROM trusty TO ChromeOS. All manner of weirdness. 
The primary screen is now ABOVE the secondary. Worse my mouse can't get there and 'teleports' from the left edge of the primary to the right edge of the primary. Also my open browser window is nowhere to be seen (which runs crouton, which might yield info). In short I can't do anything. 
Pressing shift-alt-crtl-BACK _again_ gets me in an other state. I have a browser window now. But secondary is not accessible by mouse. 
Also the switches back take a second or 2 in which both screens go blank, pop back to live, go blank again.

What's going on? How can I diagnose the issue?

I have a Toshiba Chromebook 2 with a Intel(R) Celeron(R) CPU N2840 @ 2.16GHz.
`$ sudo enter-chroot -n chrootname trusty` yields:
```
crouton: version 1-20141007225312~master:edac5e3d
release: trusty
architecture: amd64
targets: xfce
host: version 6158.49.0 (Official Build) stable-channel swanky 
```

**Comment by haarts** [comment]
I've just confirmed that this is still an issue. Crouton version: crouton: version 1-20150105184725~master:48712458. And running Trusty.

**Comment by rmkraus** [comment]
This one has become an issue for me. I've been trying to debug this one for a while now and I am officially stuck. This all is while having an external display connected and with a fresh install as of today. KDE is the window manager. Trusty is the distribution.

When using xorg: I can launch my chroot just fine, but when I go to cycle back to cros, my external display gets a black background and my internal display cycles back to cros correctly. The mouse gets locked on my external display and will not move over to the other display.

When using xiwi: This used to be my work-around. However, now when I launch xiwi, the same thing happens. If I unplug the external monitor, xiwi will launch and then I can plug the external monitor back in. This works but seems a bit hackey and will probably destroy my HDMI port in the long run.

Chromebook is an ASUS C300M. Below is the output of croutonversion:

crouton: version 1-20150414182244~master:da478a77
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,x11,kde,keyboard
host: version 6680.78.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Fri Mar 20 17:27:56 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

Any help would be appreciated. Thanks!

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
