### ISSUE TITLE
can't get into crouton-ubuntu-xfce4 since updating x.org, known x.org current update vs. xbmc issue

### ISSUE THREAD

**Issue by faddah** [dnschneid/crouton#1118]
hi @dnschneid (maybe also @divx118 & others?) -

i'm sorry to report, i'm afraid i have inadvertently [bork'd](http://www.urbandictionary.com/define.php?term=bork) myself up again, pretty good this time. 

**the set-up --**

i'm on an Acer C720P Chromebook, 2 GB RAM, 32 GB Drive, Motherboard is PEPPY-E6A-O7G-A3J, and here's the top info from my chrome://version -

```
Google Chrome   37.0.2062.120 (Official Build 6b29c9a) 
Platform    5978.98.1 (Official Build) stable-channel peppy
Blink   537.36 (@6894b21)
JavaScript  V8 3.27.34.17
Flash   15.0.0.152-r1
User Agent  Mozilla/5.0 (X11; CrOS x86_64 5978.98.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36
```

i am running crouton's install of chroots-ubuntu(trusty - 14.04)-linux-xfce4, and running it installed to an SD Card plugged into my chromebook, mounting it and using your `-p` option. here is my crouton install command i ran --

```
sudo sh -e ~/Downloads/crouton -r trusty -t core,cli-extra,audio,xorg,x11,gtk-extra,extension,keyboard,touch,xfce,chrome,chromium,xbmc -p /media/removable/linux/
```

**what happened --**

i was so thrilled to get the chroots-ubuntu-linux-xfce4 running, that i went and got the software update and ubuntun software manager (`sudo apt-get install software-center`), and also used `apt-get` to get `gparted` and `gedit`, as i like those tools. i ran the software update once it was installed, it found a bunch of stuff to update, and then wanted me to restart. i didn't know when it restarts, it restarts **_all_** of the chromebook, not just the virtual ubuntu linux running through crouton/chroots. anyway, when i came back in and tried to run ubuntu-linux-xfce4 again, i get the following -

``` bash
...
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /media/removable/linux/chroots/trusty...
chronos@localhost / $ 
```

... i looked up the `xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)` and it is discussed on this [arch linux forum thread, "XBMC Not starting from systemd service unit after latest Xorg update" here](https://bbs.archlinux.org/viewtopic.php?id=185017) and is a known issue since the last x.org update, [detailed in this bug, "FS#41391 - [xbmc] Since the new xorg update, xbmc.service does not start," here](https://bugs.archlinux.org/task/41391). i specified i wanted x.org, X11, and xbmc in my crouton install with ubuntu (see, again, my crouton install command line from above). so when i ran the software update, it probably updated me to the latest x.org, which conflicts with xbmc, which is why, after i restarted, i probably what i ran into this error and can't get the ubuntu-linux-xfce4 back up.

anyway, so i'm wondering what is to be done here, seeing how this is a known bug currently between the current update of x.org & xbmc? is there some way to do `edit-chroot` and take out just the xbmc so my ubuntu-linux-xfce4 will run again? or is it just an unfortunate whole re-install again with crouton (which would really bum me out)? i can't get back into linux to edit or update anything else that might fix it, as it halts at that line above ^^^^ while starting up.

thanx in advance and any and all help is all very much appreciated.

best,

--  faddah wolf
    portland, oregon, u.s.a.
    github.com/faddah

**Comment by gghezzo** [comment]
Faddah, 
How did this tale end? I am running into the same issue on my Acer with Crouton. Did you ever find a way out that was not re-install? Also, do you know the root cause? I am not sure what I did last except install idle for python . 
Thanks, 
Ginny

**Comment by solamour** [comment]
I have an Acer C720 and was greeted with the same "xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)" error message. For my case, updating crouton with "sudo sh ~/Downloads/crouton -u -t xfce -n trusty" fixed the problem.
__
sol

**Comment by timendez** [comment]
@solamour The exact command worked for me too, except I had to change trusty to precise due to a version thingy.

`sudo sh ~/Downloads/crouton -u -t xfce -n precise`

**Comment by TheBrockEllis** [comment]
@solamour and @timendez Thank God for both of you. I shut my chromebook down for the weekdn (Asus 13" 4gb) and when I booted it up Monday I got the same error everyone here has gotten. I thought I was toast.

Running `sudo sh ~/Downloads/crouton -u -t unity -n precise` fixed my issues. Huzzah!

**Comment by timendez** [comment]
@TheBrockEllis You got it buddy

**Comment by kellerscholl** [comment]
Note for posterity: the value after -n should be the name of your chroot, which may not be the same thing as your version.

**Comment by JCoderLi** [comment]
> Running sudo sh ~/Downloads/crouton -u -t unity -n precise fixed my issues. Huzzah!

Did it reset? I really would like to keep my files.
