### ISSUE TITLE
LXDE launch overwrites ChromeOS Terminal and Session

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#1141]
I found that my LXDE chroot (based on crouton -t lxde -r trusty) launches over the top of my ChromeOS terminal and graphics session (a specific TTY I would guess).

In other words after launching LXDE from the Developer shell, (sudo startlxde -b) the CTRL+ALT+=> navigation can only reach two sessions the Developer shell, or LXDE. The ChromeOS session becomes apparently overwritten by LXDE and otherwise invisible or inaccessible.

After logging out of LXDE the CTRL+ALT+=> navigation still shows two sessions, the Developer shell, or ChromeOS - the session has been preserved.

Perhaps related is an apparently static snapshot of ChromeOS taking over the screen when LXDE is launched for a minute or so, which hides all other sessions, before any of the navigation keys become responsive, and then either the LXDE desktop or Developer shell become visible depending on which navigation keys you're punching.

It's possible that I launched LXDE for the first time from CTRL+ALT+T to get chrosh then 'shell' but don't know what kind of permanent TTY association might have been made, then, or how to reverse it. The build is quite satisfactory if I could run it simultaneously with ChromeOS. Should I rebuild it and relaunch it from the Developer shell first time to make a permanent TTY association there?

**Comment by Dexterhill013** [comment]
ctrl alt shift backward not working and theres no ctrl alt shift forward

**Comment by Dexterhill013** [comment]
i had to delete it 😭😭😭😭😭😭😭😭😭😭
