### ISSUE TITLE
Route to samba client functionality not obvious from minimal lxde build

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#1142]
Where my other Lubuntu lapto (based on Trusty) can successfully browse Samba shares in PCManFM, the crouton LXDE build cannot by default. Because installing lubuntu-desktop is not advised, can anyone suggest how to get the LXDE build generated by crouton to acquire the minimal packages it needs for Samba client capabilities.

To demonstrate the failure, I navigate to Go=>Network and then try to browse the WIndows network, where it reports a problem like "Failed to retrieve share list from server". Using a direct smb:// path fails in a similar way. I have checked that gvfs-backends is installed, added cifs-utils and gvfs-bin, and experimented with installing fusesmb. So far, all these have the same result as above. Do I need to restart some service to make this work? What packages might I need to get so I can access media on the network.

**Comment by cefn** [comment]
Thanks for the suggestion, but it doesn't quite match with the feature request, so I should clarify. The wiki page you linked to helpfully describes how to use the command line to explicitly mount password-protected Samba shares. However, I would like to load Windows Shares by navigating with a graphical file navigation client, in particular the one built-in to the LXDE desktop; PCManFM. 

By default when trying to use the client from a LXDE crouton target, it appears not to have appropriate libraries or configuration to enable Windows shares to be accessed interactively. Incidentally, the shares I'm trying to reach are not password protected - just open network shares on my home network, so no auth configuration should be required.

I just recently got another chromebook (after my HP Chromebook 11 died - wifi hardware :( ) so I'm revisiting my original feature requests with a Toshiba Chromebook. Same setup, but amd64 instead of arm. Same problem accessing the Windows Network.

After installing a bunch of packages (not sure which are significant if any) I found that I can actually access Windows shares in PCManFM if I know the direct address of the share. So there must be some kind of lookup facility missing to allow PCManFM to discover 'broadcasted' shares.

If I know the IP address or DNS name of the server, then I can access it directly and successfully browse. For example...
    smb://192.168.1.36/
...works, as does...
    smb://192.168.1.36/public/
...or...
    smb://firefly/public/

However, the functionality to visit smb:/// and have it list available servers on the Samba network is non-functional.

The packages I installed were (I believe)...
gvfs-backends gvfs-bin samba system-config-samba smbnetfs fusesmb cifs-utils dnsutils

The dnsutils package simply allowed me to look up the IP address of the server, and may not be important. 

Perhaps others who have the same problem could verify that installing these packages makes accessing explicitly-addressed shares possible. The question then remains how to restore smb:/// browsing functionality at the network level.

**Comment by Watney** [comment]
Maybe [this guide](http://linuxg.net/how-to-install-pcmanfm-1-2-1-on-ubuntu-14-04-trusty-tahr-and-derivative-systems/) will help to replace Thunar with PCManFM. (I think that's what you want to do.)

However, without testing, I'm not sure you need to add another ppa. You may be able to install PCManFM as is. I'd try to install it, and if it fails, add the ppa.

**Comment by divx118** [comment]
Trusty with lxde minimum target allows for browsing the network in pcmanfm so no additional packages needed. It should work out of the box when creating a chroot with `sudo sh ~/Downloads/crouton -r trusty -t lxde`.  
The only problem is the iptables rules on chromeos. If you flush them, which is a bad idea browsing will work. Probably we only need to open the following:
```
Port      Protocol     
135       TCP and UDP
137       TCP and UDP
138       UDP        
139       TCP        
445       TCP and UDP
```
I never played around with iptables, so I need to do some reading on how to do this correctly. Or maybe someone beats me to it. :)

**Comment by divx118** [comment]
Ok, opening the high unpriviledged udp ports worked for me. That is kind of a big hole. For me it is not so much of a problem, because I only opened them on my local network. If you need more restriction, you could only define your smb server ip addresses (--source).  
More info http://terokarvinen.com/linux/doc/samba-quickstart.html bottom of the page.  
Below the iptables command I used. Note that you need to replace the ip address with the one from your local lan.  
```
sudo iptables -I INPUT 1 -p udp --source 10.0.0.1/255.255.255.0 --dport 1025:65535 -j ACCEPT
```
NOTE: On a reboot the iptables are reset to default, so you will need to reapply it when rebooted.

BTW I guess this will also work for other chroots to allow browsing of smb. I will test some and then add this info to the wiki.

**Comment by divx118** [comment]
I added the relevant info to the wiki https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc). So this can be closed now.

**Comment by DennisLfromGA** [comment]
@divx118 - Thanx for all your research and the solution on this.

I wonder if, after executing the `iptables ...` command, doing the `iptables-save > /etc/sysconfig/iptables` would save the current configuration and be implemented when entering the chroot each time.

If not, perhaps putting the `iptables ..` command in `/etc/rc.local` would work.
