### ISSUE TITLE
How to build and load kernel modules

### ISSUE THREAD

**Issue by ant6n** [dnschneid/crouton#1148]
I would like to compile and load a kernel module in Crouton, on a Samsung Chromebook: https://github.com/thoughtpolice/enable_arm_pmu. The module itself consists only of a single c-file, and the Makefile looks like this:

```
obj-m   := enable_arm_pmu.o
KDIR    := /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

all:
    $(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
```

After some googling, I understand that this is the usual way to compile a kernel module in Linux. However, in crouton, the `/lib/modules/3.8.1/build` file does not exist. So how does one go about compiling the module? Is there a way to create this build file? The only thing I found so far that is in any way related is a wiki-page for crouton: https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules. But I don't understand how downloading the kernel and building will help to be able to compile the kernel module that I have.
Thanks

**Comment by ashleygwilliams** [comment]
just gonna comment here that i had this same problem and this issue does a great job of solving it. would love to see it in the docs somewhere(or maybe it is and i just couldn't find it).

would be happy to contribute a write up on it if you could point me how and where to :)

**Comment by rafi16jan** [comment]
> For building a kernel module you will need atleast the kernel headers or the complete kernel source. You can build the kernel headers yourself by following https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)
> You could also try to get the kernel headers from https://github.com/divx118/crouton-packages/blob/master/README.md . This will give you the `/lib/modules/3.8.11/build` you need.
> Note that the arm kernel headers are untested. Loading the module is explained on the page you mentioned.
> Please report back if the kernel headers work or don't work for you if you use them.

Is the getting the headers only still relevant? I ran your script but still got no header in /lib/modules/3.18.0/build

**Comment by rafi16jan** [comment]
@divx118 well then I'll just compile the header from source...
