### ISSUE TITLE
Opening a remote desktop over ssh

### ISSUE THREAD

**Issue by davidgauch** [dnschneid/crouton#1152]
Is there a more elegant way to open a remote desktop than to do:
sudo enter-chroot xinit -e ssh -Y user@host gnome-session.

Also I am not a huge fan of these warnings: 

Warning: No xauth data; using fake authentication data for X11 forwarding.
gnome-session[23379]: WARNING: Unable to determine session: Unable to lookup session information for process '23379'
GNOME_KEYRING_SOCKET=/tmp/keyring-AZ8ohd/socket
SSH_AUTH_SOCK=/tmp/keyring-AZ8ohd/socket.ssh
GNOME_KEYRING_PID=23402
Unable to open desktop file thunderbird.desktop for panel launcher

(polkit-gnome-authentication-agent-1:23485): polkit-gnome-1-WARNING **: Unable to determine the session we are in: Remote Exception invoking org.freedesktop.ConsoleKit.Manager.GetSessionForUnixProcess() on /org/freedesktop/ConsoleKit/Manager at name org.freedesktop.ConsoleKit: org.freedesktop.ConsoleKit.Manager.GeneralError: Unable to lookup session information for process '23485' org.freedesktop.ConsoleKit.Manager.GeneralError Unable%20to%20lookup%20session%20information%20for%20process%20%2723485%27
system-config-printer-applet: failed to start NewPrinterNotification service
Failed to play sound: File or data not found
Initializing nautilus-gdu extension
Initializing nautilus-open-terminal extension

**Comment by mark-hahn** [comment]
I also want to run an X server in crouton and access a remote headless server acting as an X client.  I know this is a general unix question but I thought there might be some implications of doing this is crouton.  I have no idea how to do this inside or outside of crouton.

My specific use case is to edit files on the remote machine.  I've been using slap inside the terminal but I'd love to be able to just fire up gedit.

> The more elegant way is Chrome Remote Desktop

That requires a desktop with a display on the other end, right?
