### ISSUE TITLE
How to force umount a chroot?

### ISSUE THREAD

**Issue by martinffx** [dnschneid/crouton#117]
I'm not sure if this is the right place to ask this, but I can't seem to find a answer any where.

I'm having trouble `umount`ing my chroot env, whenever I log out I get the following error `Not unmounting /usr/local/chroots/precise as another instance is using it`

I know this is probably because I probably never logged out of the chroot and it is picking up my old session process. What I'm unsure of is how to _"reboot"_ the chroot (kill all process and umount), so that the next time I get a fresh session?

This is really bugging me because each time I boot it I have to close the old programs that are running but I no longer have a need for...

P.S. Thanks for the **awesome** project!!

**Comment by trusktr** [comment]
I haven't read the entire thread, but did you know when Chrome OS runs low on memory, it can kill crosh windows just like website tabs, and in my case this left the Xorg server running?

Notes on what I did, in case it helps anyone:

I didn't have any luck with `sudo unmount-chroot -fa`:

```
chronos@localhost / $ sudo unmount-chroot -fa
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Failed to unmount /mnt/stateful_partition/crouton/chroots/xenial. Kill processes? [a/k/y/p/N] n
Skipping unmounting of /mnt/stateful_partition/crouton/chroots/xenial
```

then I tried 

```
chronos@localhost / $ sudo unmount-chroot -pa
 1868 su - trusktr
 6933 su -s /bin/sh -c export SHELL='/usr/bin/zsh';'exec' 'startgnome'  - trusktr
28776 su - trusktr
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

then I tried SIGQUITing the dangling startgnome process, but no luck:

```
chronos@localhost / $ sudo unmount-chroot -pa
 1868 su - trusktr
 6933 su -s /bin/sh -c export SHELL='/usr/bin/zsh';'exec' 'startgnome'  - trusktr
28776 su - trusktr
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
chronos@localhost / $ sudo kill -SIGQUIT 6933
chronos@localhost / $ sudo unmount-chroot -pa
 1868 su - trusktr
 6933 su -s /bin/sh -c export SHELL='/usr/bin/zsh';'exec' 'startgnome'  - trusktr
28776 su - trusktr
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

Finally a `sudo kill -SIGKILL 6933` was able to stop `startgnome`, and I also killed the other processes, then I was able to unmount. I didn't try having the prompt kill all the processes, that may have worked too.
