### ISSUE TITLE
priortize targets

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1198]
Question/Enhancement: 

It seems the order in which we list targets on the command line is becoming more critical.

With the addition of some of the 'unique' targets like xephyr, xorg, xiwi and some that are mutually exclusive or incompatible, would it be worthwhile to have a 'priortizetargets' function or script segment, kind of like 'deduptargets' in main.sh or maybe something in targets/common, that would re-sort the targets to ensure that certain ones are listed first or at least before other less critical ones and remove unnecessary ones ?

**Comment by divx118** [comment]
Yes, sorry you are totally right. If I understand correctly it should be something like https://github.com/divx118/crouton/commit/71f27c18865ab7524326651aa29b0b3cc7636ade

**Comment by dnschneid** [comment]
That's looking quite good, thanks.  Could you open a PR for that and I'll post some feedback?

**Comment by dnschneid** [comment]
Fixed in master!  Thanks, @divx118

**Comment by DennisLfromGA** [comment]
Yes, thanx @divx118 :+1: 
I have lots of ideas but fewer & fewer solutions... ;-)
