### ISSUE TITLE
Wine on Crouton XFCE

### ISSUE THREAD

**Issue by vrodgers** [dnschneid/crouton#121]
Can someone help me to install wine on this Crouton XFCE?  I'm a beginner when it comes to linux as a PC.  Any help with terminal commands and pre-pakages that need to be installed would be appreciated.  I'm running into all sorts of issues trying to install from the basic instructions and anything I could find on forums.

**Comment by Inadequate-incubus** [comment]
will wine work on Acer c7 on crouton xfce... sorry im just poping up total newbie wannabe XD Ps.. i added on to my hard drive with a Xbox 360 60g... not that is relevant.


-Nathan
