### ISSUE TITLE
host resets on starting guest machine in virtualbox/crouton

### ISSUE THREAD

**Issue by MikRoscope** [dnschneid/crouton#1211]
I just changed the ssd on my Acer C720 and did a clean chromeos recovery all the way to virtualbox installation in crouton with trusty xfce. 
vitrualbox drivers are loaded as far as I can check with `sudo /etc/init.d/vboxdrv start` .
There is no OS installed on the guest machine, it's merely a predefined configurations for winxp. Simply trying to start the guest machine resets the chromebook. There is no log file in `~/VirtualBox VMs`. Is there somewhere a log file written by crouton?

**Comment by MikRoscope** [comment]
Sorry to open the issue. My virtualbox stopped working again. It's hard to know when since I only use it occasionally. I did a release upgrade from precise to trusty in between and there were several updates from google for chromeos. I did `sudo sh -e ~/Downloads/crouton -n <chroot_name> -u` after each of these updates.
My question is on which circumstances one needs to build the kernel headers again? perhaps with the [script](https://github.com/divx118/crouton-packages) from @divx118. After a chromeos update? after Ubuntu release upgrade? or never?

**Comment by divx118** [comment]
@MikRoscope See https://github.com/divx118/crouton-packages/issues/10 I just update the kernel headers last weekend. Normally they don't need to be updated often. Please post any issues regarding virtualbox on my github. We don't want to clutter up issues here, it is not crouton "related" in the meaning it is a bug in crouton.
