### ISSUE TITLE
Keyboard hot keys unresponsive in awesome

### ISSUE THREAD

**Issue by shakedlokits** [dnschneid/crouton#1223]
I installed trusty with e17 and awesome. when I enter awesome the keyboard search key wont 
respond (Mod4+Enter, etc..)

**Comment by 4nnn** [comment]
Hello, just installed e17 on a Acer CB3 131 chromebook.
Everything works like a charm except for the hotkeys (volume, brightness, etc.)
I can't seem to be able to get key binding to work.  Same thing, I cannot change Edge settings...

Any clue ?
