### ISSUE TITLE
Enter Chroot without login, (from VT2)

### ISSUE THREAD

**Issue by Timvrakas** [dnschneid/crouton#1225]
I want to be able (or think it would be cool) to be able to more easily enter the chroot from the chrome login screen. If you are adverse to google legal agreements, don't want a google account, etc., you can bypass the google interface and go straight to linux.

You can do it now but you have to run 'sudo startunity', then switch out of vt2 really quick, otherwise the start fails.

Just a thought!

**Comment by dnschneid** [comment]
Fixed in the latest crouton.
