### ISSUE TITLE
To allow easy output redirection, encryption key prompt should be sent to /dev/tty

### ISSUE THREAD

**Issue by fortran77** [dnschneid/crouton#1232]
The 'crouton -e' and related commands prompt the user to enter the encryption key apparently by writing to stderr.

If all script output is redirected to a file, no prompt reaches the user's screen. The user waits indefinitely for the prompt, while the script waits indefinitely for the input.

To prevent this problem, it would be better if possible to send the prompt to /dev/tty instead.

**Comment by dnschneid** [comment]
Fixed in the latest crouton.

**Comment by dnschneid** [comment]
I had reverted this because the implementation was broken.  I'm currently testing a simpler and more correct implementation in the tty branch.

**Comment by dnschneid** [comment]
Which I'm tracking in #1323, apparently.
