### ISSUE TITLE
No sound in xfce after ChromeOS update

### ISSUE THREAD

**Issue by JonathanFRU** [dnschneid/crouton#1238]
Sound stopped working in crouton after chromeOS update, tried to update crouton and got this:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libasound2:i386 is already the newest version.
libspeexdsp1:i386 is already the newest version.
alsa-utils is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libc6-dev:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libc6-dev-i386 linux-libc-dev libc-dev-bin

E: Package 'libc6-dev:i386' has no installation candidate
E: Unable to locate package libspeexdsp-dev
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
