### ISSUE TITLE
Can only see wallpaper when switching into Ubuntu

### ISSUE THREAD

**Issue by rileymd88** [dnschneid/crouton#1244]
Hi,

I recently installed Crouton with a unity build and everything was working fine but now suddenly when I switch to unity I see my wallpaper and that is it. I am able to see the mouse cursor and create new folders and open the terminal etc but I can't get back to the normal desktop screen. Can anyone help?

**Comment by rileymd88** [comment]
I tried to update but it did not work

**Comment by dnschneid** [comment]
You may need to update to trusty. saucy is long since EOL
