### ISSUE TITLE
CRAS is eating huge amounts of CPU. 

### ISSUE THREAD

**Issue by cwinnbari** [dnschneid/crouton#1252]
My has been working great until this week. My computer has been slowing down, my system monitor says CRAS is using 50-100% of my CPU

I'm running Ubuntu 14.04 Unity. 

The only thing can I think that I did was installing a 32bit file for a program.

-I'm using an ACER 720 2gb

**Comment by ComputerLag** [comment]
http://googlechromereleases.blogspot.com/2015/01/stable-update.html

Stable channel has been updated to version 40. This issue can now be closed. Anyone currently on beta channel can safely move back to stable.

**Comment by alaimacerc** [comment]
40 rolled out yesterday (Tuesday), it seems.  Have forced an update on the Stable channel, updated my chroot and...  crossing my fingers.

**Comment by helpdeskdan** [comment]
#*@& it!  Now the latest beta has high cpu on cras!  Powerwash it is.

**Comment by dnschneid** [comment]
erp what.  Is there a bug tracking that?  Probably a different bug from [crbug.com/424271](http://crbug.com/424271)?

**Comment by ComputerLag** [comment]
Honestly I'm on the latest beta and have had no problem with cras and CPU usage. I deal with a lot of media and use my chromebook daily. Make sure you are on version 40 or later, it should be out on the stable channel by now.

**Comment by helpdeskdan** [comment]
This acted entirely different - it was not at all intermittent, high CPU as soon as you startlxde.  I'm sorry, I can't help with the debug - I powerwashed.  Thanks for your hard work!

**Comment by dnschneid** [comment]
OK, I think we can close this for now.  If it appears again, we can re-open.
