### ISSUE TITLE
Include debootstrap in crouton bundle

### ISSUE THREAD

**Issue by tonyxue** [dnschneid/crouton#1257]
Hi,

From #1256 , I think of that crouton is using debian ftp as a secondary choice. 
But why not as the primary? So that we can add a parameter for users to assign the mirror they want to improve speed.

I understand that it is not a very big improvement on speed normally since the file is not large. But some people who have very bad international internet connection or some limitation on connection might want to use that.

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
