### ISSUE TITLE
Gnome target on jessie and sid is broken.

### ISSUE THREAD

**Issue by divx118** [dnschneid/crouton#1266]
When you use `sudo startgnome` you get the white gnome error screen on startup. To fix this I needed to install some extra packages.
First to let gnome start gdm3:

```
sudo apt-get --no-install-recommends install gdm3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  dconf-cli libelfg0 libglib2.0-bin
Suggested packages:
  gnome-orca
Recommended packages:
  xserver-xephyr desktop-base
The following NEW packages will be installed:
  dconf-cli gdm3 libelfg0 libglib2.0-bin
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 2047 kB of archives.
After this operation, 6931 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

Then to let the brightness slider work, else gnome crashes when used systemd-shim:

```
sudo apt-get install systemd-shim
The following extra packages will be installed:
  cgmanager libcgmanager0 libnih-dbus1 libnih1
Suggested packages:
  pm-utils
The following NEW packages will be installed:
  cgmanager libcgmanager0 libnih-dbus1 libnih1 systemd-shim
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 360 kB of archives.
After this operation, 1011 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

Still need to see if other distros are affected. Also there is no terminal present in the activity menu other then the root terminal. (xterm can't be found).

Edit added croutonversion:

```
(jessie)m@localhost:~$ croutonversion                   
crouton: version 1-20141208100324~master:7b8ffff0
release: jessie
architecture: amd64
targets: gnome,keyboard,extension
host: version 6592.0.0 (Official Build) dev-channel falco 
```

**Comment by berkough** [comment]
Tap to click doesn't work for me either... Here's output:

crouton: version 1-20150519153807~master:30cf02c9
release: jessie
architecture: amd64
xmethod: xorg
targets: gnome-desktop,gnome,audio,xorg,x11,extension
host: version 6812.88.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Fri May 8 14:01:46 PDT 2015 x86_64 GNU/Linux
freon: no

I'm on an Asus C300MA-EDU.

**Comment by dnschneid** [comment]
This is probably obsolete...
