### ISSUE TITLE
Need proper XMETHOD coexistence

### ISSUE THREAD

**Issue by divx118** [dnschneid/crouton#1274]
When xiwi target is not in front, xorg target will be installed and XMETHOD will be set to x11. This also happens when updating with a new WM target.
`sudo sh ~/Downloads/crouton -r trusty -t xiwi,lxde` updating and adding xfce should be done like this `sudo sh ~/Downloads/crouton -u -t xiwi,xfce` Normally it shouldn't be needed to add xiwi target on update.
This should be solved once https://github.com/dnschneid/crouton/issues/1198 is implemented.

On a side note, it would also be nice to be able to choose the xmethod on entering the chroot, so you can choose when accelerated gpu is needed.

**Comment by tedm** [comment]
that makes sense. Many will want a switching utility. I'm one of the few who doesn't game much and watch HD on a TV, so the xiwi (and the ARM cpu) is fine. The most intense graphics I do on the chromebook is Netflix SD, or borderline HD, and that is on the Chrome side. I really value the fanless design of the ARM, though I realize future Broadwell designs may be fanless, and Haswells can be quiet when not pushed.

**Comment by tedm** [comment]
@wenlock For my expectations with the chromebook, xiwi is fine, but almost any multimedia I do is on the Chrome side such as most browsing, all youtube, and netflix. (for audio I use a Pono) - so sound and video acceleration in the chroot for my uses are not great. I guess with the steam, and games and all that more people are installing apps in the chroot that need good video acceleration.

**Comment by DennisLfromGA** [comment]
@dnschneid, @drinkcat,

I've just updated crouton and my chroot (both xorg and xiwi are installed - xiwi is active) but I seem to be unable to invoke 'xorg' at will. I'm using:
```sudo enter-chroot -n utopic exec env XMETHOD=xorg startgnome```
but it just hangs at -
`...
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
`
Also, when I try to use `startkde` I get someting similar:
`
...
$DISPLAY is not set or cannot connect to the X server.
`

I've also changed `/etc/crouton/xmethod` to contain 'xorg' but it still hangs at the same point.

*Is there another trick to getting xorg to work that I'm missing?*

I can invoke 'xiwi' using:
```sudo enter-chroot -n utopic exec env XMETHOD=xiwi startgnome```
but that's to be expected since 'xiwi' is active (`/etc/crouton/xmethod` contains xiwi) and is listed first in `/etc/crouton/targets`.

The only way I've been able to switch between 'xorg' and 'xiwi' successfully is to change their order in `/etc/crouton/targets`. If I place 'xiwi' first:
```
xiwi,xorg,audio,cli-extra,gtk-extra,extension,gnome,kde,xbmc,chrome-beta
``` 
then 'xiwi' it works, 
If I place 'xorg' first: 
```
xorg,xiwi,audio,cli-extra,gtk-extra,extension,gnome,kde,xbmc,chrome-beta
```
then 'xorg' it works.

Stumped,
-DennisL

**Comment by merah-putih** [comment]
@DennisLfromGA 

Perhaps it works with the newest crouton:
crouton: version 1-20150107122507~master:3b348ad5
release: trusty
architecture: amd64
targets: chrome,xorg,xiwi,extension,keyboard,xfce
host: version 6310.68.0 (Official Build) stable-channel peppy

The XMETHOD option works in my case, that I can switch from xiwi to xorg (and vice versa) without any problem, using:

sudo enter-chroot -n trusty exec env XMETHOD=xiwi startxfce4
sudo enter-chroot -n trusty exec env XMETHOD=xorg startxfce4

The keyboard (UK layout here) still doesn't map correctly though ...

**Comment by DennisLfromGA** [comment]
The version I used was yesterdays and had the XMETHOD merged but maybe something has changed so I'll download an try again - just to be sure.

**Comment by hsharrison** [comment]
Just stumbled across this page and thought I would mention that this is working for me on an old chroot that's been updated through an iteration of targets, `xorg` --> `xephyr` --> `xiwi` --> `xorg` (accordingly `xorg` is listed first in `/etc/crouton/targets`).

`startgnome` launches `xorg` correctly; `XMETHOD=xiwi startgnome` launches `xiwi` correctly.

**Comment by dnschneid** [comment]
Oh, right.  Since #1305 got merged, this bug can be closed.  The only remaining issue is #1294.

**Comment by DennisLfromGA** [comment]
@dnschneid &  @drinkcat -

I cannot get my chroot to start with the desired XMETHOD using the example above (e.g.)

`sudo enter-chroot -n trusty exec env XMETHOD=xiwi startkde`
or
`sudo enter-chroot -n trusty exec env XMETHOD=xorg startkde`

I'm still getting: "$DISPLAY is not set or cannot connect to the X server."

Is there another, preferred way to do this?

----

In the interim, I've scripted another method that does it from both inside and outside the chroot.
It's based on an idea I found on this site but for the life of me I can't find it again the give the person credit, I think he named his script `setxwin`.

This seems to be an often requested feature already and I think the script might be an easy way around it. I just threw it together and it needs a lot of clean-up but it works with both the old `xserverrc-*` link and the new `/etc/crouton/xmethod` file. Please checkout '[setxm](https://github.com/DennisLfromGA/crouton/blob/master/host-bin/setxm)' and feel free to comment on improvements, if you like.

-DennisL

**Comment by dnschneid** [comment]
startkde inside the chroot actually needs to be wrapped by xinit.  Look at the startkde script outside of the chroot for details.

Your setxm script looks nice, but it doesn't reorder the targets, so updating the chroot will reset the method.  Instead, I perhaps it'd be useful to add an x11 method parameter to enter-chroot that would set the environment variable; i.e., `-X xiwi` or something.  Might be worth opening another bug for that though.

**Comment by DennisLfromGA** [comment]
@dnschneid,

Wow, that was easy, thanx!
I just added 'xinit' to the command and it worked:

`sudo enter-chroot -n trusty exec env XMETHOD=xorg xinit /usr/bin/startkde`

------

> ...add an x11 method parameter to enter-chroot that would set the environment variable...

I thought about that and, as an experiment, I hard-coded it to `enter-chroot (line 844)` -

`env -i TERM="$TERM" XMETHOD=xorg chroot "$CHROOT" "$@" || ret=$?`

but it still tried to use xiwi so I guess I don't fully understand what or where to add the x11 method.

-DennisL

**Comment by dnschneid** [comment]
`su` drops most of the environment variables.  So the place where it generates the export line in the "cmd" variable that gets passed to su, you'd want to add XMETHOD in there.  A real implementation would also need to filter the variable's contents to avoid misbehavior.

**Comment by DennisLfromGA** [comment]
@dnschneid,
> ...perhaps it'd be useful to add an x11 method parameter to enter-chroot that would set the environment variable; i.e., -X xiwi or something...

I've got a working [patch-3](https://github.com/DennisLfromGA/crouton/compare/patch-3?expand=1) that employs a '-X' option to temporarily set the XMETHOD for the session. 

> A real implementation would also need to filter the variable's contents to avoid misbehavior.

I hope I understood what you meant by the above, I check to ensure they only specify 'xiwi,xorg, or xephyr' but that's about it. I'd like to get your input and get it cleaned up a little before I submit a pr.

It's been working very well for me and hopefully it's something that would be valuable to others.
I can open a new issue/bug request if you like or we can continue here - up to you.

Thanx,
Dennis
