### ISSUE TITLE
How do I disable xiwi in a chroot?

### ISSUE THREAD

**Issue by air** [dnschneid/crouton#1276]
I installed the targets `extension` and `xiwi`. My chroot now runs in a tab through X - useful, but no good for watching video with VLC or gaming. How can I get my chroot behaving the old way?

Thanks.

**Comment by UncleSally** [comment]
![screenshot 2015-01-31 at 4 47 22 pm](https://cloud.githubusercontent.com/assets/10791082/5990142/e380cdbc-a968-11e4-8e1d-a96b69d17211.png)
Uh oh... Sh can't open crouton. What can I do?

**Comment by DennisLfromGA** [comment]
It's in ~/Downloads so try - sudo sh ~/Downloads/crouton -u -t x11

On Sat, Jan 31, 2015 at 5:48 PM, UncleSally <notifications@github.com>
wrote:

> [image: screenshot 2015-01-31 at 4 47 22 pm]
> <https://cloud.githubusercontent.com/assets/10791082/5990142/e380cdbc-a968-11e4-8e1d-a96b69d17211.png>
> Uh oh... Sh can't open crouton. What can I do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1276#issuecomment-72340864>.
>



-- 
*DennyL@GMail*

**Comment by Judecca** [comment]
Worked! Thank you

**Comment by Judecca** [comment]
Yeah, it worked apparently. Thanks!

**Comment by DennisLfromGA** [comment]
Your welcome :)

On Sat, Jan 31, 2015 at 5:53 PM, Judecca <notifications@github.com> wrote:

> Yeah, it worked apparently. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1276#issuecomment-72341061>.
>



-- 
*DennyL@GMail*

**Comment by aigh** [comment]
sudo sh -e ~/Downloads/crouton -t xorg -r trusty -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/trusty already exists; updating it...
Preparing chroot environment...
xorg target does not yet work with Freon.

Tried updating to run crouton in fullscreen after haphazardly updating to use with crouton extension. Any way I can update back to running crouton in fullscreen?

**Comment by DennisLfromGA** [comment]
@Judecca & @aigh - The syntax is a little off, once the chroot is installed, you no longer need to specify the release via '-r trusty', instead, specify the chroot name '-n trusty'.

@aigh - 

> xorg target does not yet work with Freon.

It looks like your Chromebook is using '*Freon*' so, the way I understand it, you have to use 'xiwi', not 'xorg'. I believe, @dnschneid & @drinkcat please correct me if I'm wrong, you could install xephyr and regain running crouton in full screen and switching via 'Ctrl+Alt+Shift+F1/F2'.

**Comment by dnschneid** [comment]
Try using the x11_freon branch (which will be merged soon).  See #1265

**Comment by rubanunes** [comment]
@DennisLfromGA You say one can specify the chroot name, but does is work on SdCard installations? Or do I need to specify the chroot path every time e want to do anything with it?

**Comment by DennisLfromGA** [comment]
@rubanunes,

If you're referring to updating the chroot on external media, then, yes, it needs a path.
You can do that with crouton's '-p' option:

`    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.`

Something like:

`    sudo sh ~/Downloads/crouton -p /path/to/external/media -t xorg -n trusty -u`

----

If you're talking about launching a target/DE, I believe if you don't specify the chrootname, it will launch the alphabetically first chroot it finds with the specified target. You can also use the '-c' option to help find it:

`    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots`

So for unity, for example, you would use:

`    sudo startunity -c /path/to/external/media/chroots`

Another way to start unity, for example, is to give it the full path:

`    sudo /path/to/external/media/bin/startunity`

Then it will find the chroot automagically.

----

BTW, the 'x11_freon' branch mentioned above is already merged so you're good to go.

**Comment by lzantal** [comment]
@rubanunes I created a simlink in /usr/local after turning on developer mode but before installed chroot that points to my sd card's chroots directory. Just create a directory on your sd card first.

sudo ln -s /media/removable/sdext/chroots/ chroots

After that everytime I run crouton commands it's just finds my chroots on my sd card.

**Comment by rubanunes** [comment]
@DennisLfromGA & @lzantal thanks for the help. Eventually I got there by reading some more and poking around.

**Comment by disport** [comment]
Hmm, so after I '''sudo sh -e crouton -u -t x11''' I get 
    list of releases for  not found
    Invalid target "x11".

**Comment by DennisLfromGA** [comment]
@disport, 
- You may have to specify the name of your chroot with the `-n ...` option.
- For a list of your chroot(s), enter `sudo edit-chroot -al`

**Comment by disport** [comment]
@DennisLfromGA , I just have the one, trusty, here's a selection of output from your command above:
```
name: trusty
crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
xmethod: xiwi
targets: xiwi,unity-desktop
```

**Comment by Anzii** [comment]
I'm having the same problem as @disport - saying x11 is an invalid target :(

**Comment by DennisLfromGA** [comment]
@disport (& @Anzii ) - Then see if this works for you: 

- `sudo sh ~/Downloads/crouton -t xorg -n trusty -u`

**Comment by disport** [comment]
@DennisLfromGA I literally just logged in to make this comment, but you beat me to it, `sudo sh ~/Downloads/crouton -t xorg -n trusty -u` works perfectly

**Comment by Anzii** [comment]
Just had to change **trusty** into **precise**. :+1:

**Comment by DennisLfromGA** [comment]
@disport  - *Perfectly* works for me... ;)
@Anzii - *Way to go*!

**Comment by 1kastner** [comment]
`chronos@localhost / $ sudo edit-chroot -al
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20160902144033~master:9f8e9a22
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xorg,x11,e17,xiwi
host: version 8350.68.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:08:34 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...`

I would like to turn back to the non-xiwi setup which I had with another chroot. Now I can't figure out how.

When I run 
`sudo enter-chroot XMETHOD=xorg kali`

It produces the following error:

`xorg is already the newest version (1:7.7+16).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-core : Conflicts: xserver-xorg-video-modesetting
 xserver-xorg-video-modesetting : Depends: xorg-video-abi-18
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
-su: 1: XMETHOD=xorg: not found`

**Comment by DennisLfromGA** [comment]
@1kastner,

You can switch xmethods when entering a chroot with the '-X' option -

`    -X XMETHOD  Override the auto-detected XMETHOD for this session.`

So this should work for you: `sudo enter-chroot -X xorg -n kali`

It looks like you might have some problems with some packages in your chroot too.
Updating your chroot via crouton, shown below, may fix it though.

-----
You can switch back to the 'xorg' xmethod permanently by updating your chroot like this:

`sudo sh ~/Downloads/crouton -t xorg -n kali -u`

Hope this helps,
-**DennisL**

**Comment by 1kastner** [comment]
Thanks a lot!
