### ISSUE TITLE
Can't disable module_locking in ChromeOS dev channel

### ISSUE THREAD

**Issue by dcroal** [dnschneid/crouton#1278]
Looks like v41 dev channel does not have /sys/module/lsm/parameters/module_locking present so the rc.local script provided to allow insertion of modules does not work for things like Virtualbox, etc. Does anyone know of a work-around?

Thanks,

**Comment by dnschneid** [comment]
OK, [module_locking may be returning](https://code.google.com/p/chromium/issues/detail?id=440990).  Feel free to star the bug to get updates, but there's no need to comment on it.

**Comment by divx118** [comment]
@dnschneid Thanks for taken the time for this. The ability to load your own kernel modules without disabling verified boot is something that really adds a nice fun factor and a very useful feature on dev mode. Hopefully this issue can be closed soon in a positive way.

**Comment by ComputerLag** [comment]
@dnschneid Thank you so much for this and everything you do for crouton. I really appreciate you going to bat for us. From your avid crouton fans.

I'm really hoping this feature can be preserved in dev mode.

**Comment by dnschneid** [comment]
Update: module_locking is not returning, so kernel flags are the only way forward.

**Comment by divx118** [comment]
I am working on a script to simplify changing kernel flags with also the possibility to revert any changes, so go back to a previously backed up signed kernel. Once this is done I will update the wiki pages.

**Comment by DennisLfromGA** [comment]
@divx118 - 
I updated my script '[enable-vmx.sh](https://gist.github.com/DennisLfromGA/cd3455530cec2a5a1ef4)' per your suggestion - thanx. Please feel free to use all or part of it for your new implementation. 
I was thinking of renaming the backup file generated (/mnt/stateful_partition/backups/kernel_A_`date +'%Y%m%d_'`*.bin) to something more memorable and distinct for restoral but didn't go that far - yet.

**Comment by Timvrakas** [comment]
Its official :) I just received a normal update from Google and no more module_locking.

**Comment by divx118** [comment]
Ok, I put my script online https://github.com/divx118/crouton-packages/blob/master/change-kernel-flags a short description is in https://github.com/divx118/crouton-packages/blob/master/change-kernel-flags
This script will look at which kernel is booted on a reboot and only adjust that kernel. It is also easy to revert and put a backup kernel back.  
I will update the virtualbox wiki pages soon.
