### ISSUE TITLE
Chromebook Utility “Crouton” Now Lets You Run Ubuntu on a Chrome Tab

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1279]
Read all about it!

Chromestory:**_[Chromebook Utility “Crouton” Now Lets You Run Ubuntu on a Chrome Tab](http://www.chromestory.com/2014/12/chromebook-utility-crouton-now-lets-run-ubuntu-chrome-tab/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+ChromeStory+%28Chrome+Story%29)**_

I think this at least deserves the 'enhancement' & 'partyinlinuxland' tags ;-)

**Comment by JimBuzbee** [comment]
After running for a while, my X session fails and I see continuous errors in the console that I used with startxfce4:

find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: Failed to create pipe. (Too many open files)

Looking at the /proc filesystem, I see that croutonfbserver has over 2000 file descriptors in use, with nearly all being used for pipes

**Comment by tedm** [comment]
@JimBuzbee You may want to open a new issue for this.

Are you using v2 of the Chrome Extension from the app store? You may want to try re-installing xiwi with -u and ensure you're using the latest version of crouton.

If you're on precise and Intel, you might want to create a trusty chroot with xiwi for now.

**Comment by dnschneid** [comment]
That's #1286
