### ISSUE TITLE
Target validity check still isn't right

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1280]
Just had to push 00179dae48ed72d4f4621fc169f1bbadb09f8b1a because the targets check was failing on upgrade, where DISTRO/RELEASE isn't detected yet.  Before I broke it with an earlier commit, targets checking wasn't working at all.

We need to properly fix the target validity check.  This is probably one step on the way to #647, but hopefully we can get it fixed as a testbed for modularization without requiring a complete refactor.

**Comment by dnschneid** [comment]
OK past me, could you be more specific about what the issue is?  Oh?  What's that?  Updates don't properly enforce validity because DISTRO and RELEASE aren't yet detected?  I see, that is indeed pretty bad.  Thanks for clarifying.

**Comment by DennisLfromGA** [comment]
[ Sometimes, talking to oneself is the only way to have an intelligent
conversation ;) ]

On Sat, Feb 21, 2015 at 4:31 AM, David Schneider <notifications@github.com>
wrote:

> OK past me, could you be more specific about what the issue is? Oh? What's
> that? Updates don't properly enforce validity because DISTRO and RELEASE
> aren't yet detected? I see, that is indeed pretty bad. Thanks for
> clarifying.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1280#issuecomment-75363809>.
>



-- 
*DennyL@GMail*
