### ISSUE TITLE
xiwi window crashes with popen2: Failed to create pipe.

### ISSUE THREAD

**Issue by divx118** [dnschneid/crouton#1286]
When leaving a chroot running for an extended period of time it crashes. This seems to happen coming out of standby at least it did for me 2 times.
Errors in the crosh window: http://pastebin.com/dfQ6VuvB
The `find_shm: Invalid signature, fetching new shm!` happens after I start the chroot and keeps popping up regularly. 
I have to ctr-C in the crosh window to exit and restart the chroot. Clicking in the crouton chromeos app on the chroot running fails with can't connect.

**Comment by monaka** [comment]
I got a similar issue. The difference is to stop with assertion failed.
Hope this bring some additional hints to fix it.

```
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: Failed to create pipe. (Too many open files)
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: Failed to create pipe. (Too many open files)
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: Failed to create pipe. (Too many open files)
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: Failed to create pipe. (Too many open files)
change_resolution: ASSERTION c > 0 FAILED (popen2)
```

**Comment by dnschneid** [comment]
Please update with the latest chroot.
