### ISSUE TITLE
screenshots/regions in a xiwi window

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1287]
In a xiwi chroot, mine is utopic, the normal screenshot function (Ctrl-F5/SwitchWindow) just seemingly minimizes the chroot window, I think it's just doing a window switch, and doesn't take a screenshot. Same thing happens when trying to capture a region (Ctrl-Shift-F5/SwitchWindow).

Here's my 'croutonversion' output:
```    
  crouton: version 1-20141224143251
  release: utopic
  architecture: amd64
  targets: xiwi,audio,cli-extra,gtk-extra,extension,gnome,kde,xbmc,chrome-beta
  host: version 6457.36.0 (Official Build) beta-channel falco
```

**NOTE**: I have a reply and explanation from @dnschneid concerning this below:
`@DennisLfromGA - that's because the extension captures the SwitchWindow key and specially processes it to unfocus the chroot. It might be possible to either toss the keypress up the stack or trigger a screenshot (not sure what the APIs are like), but either way, it's probably worth opening a new issue for.`

So, I guess it might be worth a look to see how difficult it might be, it could be useful.

**Comment by DennisLfromGA** [comment]
Seems to have been fixed so closing, please re-open if this issue is still a concern.

**Comment by eyqs** [comment]
I'm currently running into this issue, and the secret timing combinations aren't working. I'm not sure how to keep the xiwi window displayed without shifting focus to it either. I don't want to install a desktop environment. Were you able to find a fix, Dennis?

**Comment by eyqs** [comment]
I'm currently running into this issue, and the secret timing combinations aren't working. I'm not sure how to keep the xiwi window displayed without shifting focus to it either, and I don't want to install a desktop environment. Were you able to find a fix, Dennis?

> crouton:` version 1-20170901092920~master:0216f9d1
release: sid
architecture: amd64
xmethod: xiwi
targets: xiwi,core
host: version 9592.85.0 (Official Build) stable-channel cave
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Mon Aug 21 20:07:58 PDT 2017 x86_64 GNU/Linux
freon: yes`

**Comment by eyqs** [comment]
I'm currently running into this issue, and the secret timing combinations aren't working. I'm not sure how to keep the xiwi window displayed without shifting focus to it either, and I don't want to install a desktop environment. Were you able to find a fix, Dennis?

```
crouton: version 1-20170901092920~master:0216f9d1
release: sid
architecture: amd64
xmethod: xiwi
targets: xiwi,core
host: version 9592.85.0 (Official Build) stable-channel cave
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Mon Aug 21 20:07:58 PDT 2017 x86_64 GNU/Linux
freon: yes
```

**Comment by DennisLfromGA** [comment]
@eyqs,

- Are you opening a shell session via <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>t</kbd> or are you using the 'Crosh Window' / 'Secure Shell' extension combo?

- Are you using `enter-chroot` or launching an app in the chroot?

I always use the 'Crosh Window' / 'Secure Shell' extension combo -
- [ ] Crosh Window: [extension](https://chrome.google.com/webstore/detail/crosh-window/nhbmpbdladcchdhkemlojfjdknjadhmh?hl=en-US) / [page](https://chromium.googlesource.com/chromiumos/platform2/+/master/crosh/#Crosh-The-Chromium-OS-shell)
- [ ] Secure Shell: [extension](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?hl=en) / [page](https://chromium.googlesource.com/apps/libapps/)

I tried a fairly recent elementary chroot -
```
chronos@localhost ~ $ edit-chroot -l xen.elem
name: xen.elem
encrypted: no
Entering /var/crouton/chroots/xen.elem...
crouton: version 1-20170310141758
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,elementary,cli-extra,chrome-beta
host: version 9765.53.0 (Official Build) beta-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 5 12:32:03 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /var/crouton/chroots/xen.elem...
```

Using `enter-chroot` I was able to take screenshots in a region, window, and fullscreen - 
REGION:
![region_screenshot 2017-09-13 at 11 15 23 am](https://user-images.githubusercontent.com/3418772/30388895-357ef0a0-987f-11e7-84d1-dcf94c213611.png)
WINDOW:
![window_screenshot 2017-09-13 at 11 41 09 am](https://user-images.githubusercontent.com/3418772/30389535-193d39ea-9881-11e7-8dc6-375a251df126.png)
FULLSCREEN:
![fullscreen_screenshot 2017-09-13 at 11 42 10 am](https://user-images.githubusercontent.com/3418772/30389547-227e0da4-9881-11e7-962f-890126bb500a.png)

It seemed to work in any sequence but I think Ted's suggestion to "hold down ctrl first, then F5, let up F5 first, then ctrl" might work best???

-----
I could be misunderstanding your issue tho, if so, sorry, please give us a few more details.

*Hope this helps,*
-**DennisL**

**Comment by eyqs** [comment]
I can take screenshots fine of crosh, but not of a new xiwi window.

**Comment by eyqs** [comment]
I can't take a screenshot when I run an app in my chroot in a new xiwi window, i.e. with `xiwi xclock`. Apps in new tabs are fine, though.

**Comment by eyqs** [comment]
I can't take a screenshot when I run an app in my chroot in a new xiwi window, e.g. `xiwi xclock`. Apps in new tabs are fine, though.

**Comment by DennisLfromGA** [comment]
@eyqs,

Okay, that new info. helped.
I still have no problem launching 'xclock' and getting screenshots, see below -
WINDOW:
![screenshot 2017-09-14 at 9 03 21 am](https://user-images.githubusercontent.com/3418772/30434279-77313b22-992c-11e7-9aaf-04609bd92639.png)

SCREEN:
![screenshot 2017-09-14 at 9 05 00 am](https://user-images.githubusercontent.com/3418772/30434288-80a3db06-992c-11e7-971e-e3c1b3473d66.png)

You may have an extension that's interfering, other than that I'm out of ideas...

*Hope this helps,*
-**DennisL**

**Comment by eyqs** [comment]
Ah, got it. I said `xiwi xclock` but I didn't actually do that. Turns out the app I was actually running, QGIS, probably has a shortcut to minimize on F5 or something.

**Comment by DennisLfromGA** [comment]
@eyqs,

> Ah, got it. I said xiwi xclock but I didn't actually do that. 

Well, that doesn't help a lot, we assume we're getting accurate info. when we're trying to troubleshoot problems. 👎 

-**DennisL**

**Comment by Kakise** [comment]
I am running into the same problem. Chroot: kali, command used: `sudo startxiwi -n kali-rolling -b discord`. When pressing Ctrl + SwitchWindow or Ctrl + Shift + SwitchWindow, the window minimizes. I tried with and without focus

`(kali-rolling)kakise@localhost:~$ croutonversion
crouton: version 1-20180329190032~master:d287904a
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: keyboard,xorg,xiwi,xfce
host: version 10452.69.0 (Official Build) beta-channel lars 
kernel: Linux localhost 3.18.0-17025-g5eb931360066 #1 SMP PREEMPT Tue Apr 17 12:07:48 PDT 2018 x86_64 GNU/Linux
freon: yes
`

Acer Chromebook 14 For Work with intel core i3 skylake
