### ISSUE TITLE
summary of default crouton x servers by platform 

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1292]
Now that we have issues that are specific to platforms with the new Crouton Integration and xiwi, where are the best places to track, or create a table.

For example, upgrading an existing precise / xfce chroot with xiwi on ARM is great. On Intel xorg, not so great, on Tegra K1? (same as ARM?), trusty / xfce users are getting a lot of black screens, all seem to be xorg related, but not sure.

@dnschneid @drinkcat feel free to close this if there is an existing issue tracking these things.

**Comment by dnschneid** [comment]
Off the top of my head:

xiwi works everywhere, but upgrading from precise to trusty on Intel devices is currently broken.  Installing xiwi and xorg simultaneously on precise is broken without the xmethods branch, and switching between the two is onerous without that branch.  There is no GPU acceleration on any platform (and probably never will be).

xorg works on all Intel devices that are not on dev channel.  dev channel on some Intel platforms introduces Freon, which until @drinkcat's hack is in place prevents xorg from working properly.  There is some effort in getting it to work on Tegra K1, but nothing workable yet (unless you consider flipped R and B to be "workable").  I believe all platforms (except the K1) have GPU acceleration with xorg in Ubuntu.  With Debian, jessie/sid have issues with some of the older Intel devices.

xephyr works on all platforms that aren't Freon, so non-dev channel of everything and dev-channel of some.  There is no GPU acceleration in this mode, but it's faster (but less flexible) compared to xiwi.
