### ISSUE TITLE
crouton -u gives "Release doesn't match" errors for sid

### ISSUE THREAD

**Issue by janpmedlock** [dnschneid/crouton#1293]
Trying to add a target, I get "Release doesn't match" errors:

chronos@localhost ~ $ sudo sh ~/Downloads/crouton -u -t xiwi -n sid
/usr/local/chroots/sid already exists; updating it...
Enter encryption passphrase for sid: 
Unable to determine the release in /usr/local/chroots/sid. Please specify it with -r.
chronos@localhost ~ $ sudo sh ~/Downloads/crouton -u -t xiwi -n sid -r sid
/usr/local/chroots/sid already exists; updating it...
Enter encryption passphrase for sid: 
Release doesn't match! Please correct the -r option, or specify a second -u to
change the release, upgrading the chroot (dangerous).
chronos@localhost ~ $ sudo sh ~/Downloads/crouton -u -t xiwi -n sid -r sid -u
/usr/local/chroots/sid already exists; updating it...
Enter encryption passphrase for sid: 
WARNING: Changing the chroot release to sid.
Press Control-C to abort; upgrade will continue in 5 seconds.
chronos@localhost ~ $ sudo sh ~/Downloads/crouton -u -t xiwi -n sid -r sid
/usr/local/chroots/sid already exists; updating it...
Enter encryption passphrase for sid: 
Release doesn't match! Please correct the -r option, or specify a second -u to
change the release, upgrading the chroot (dangerous).

The chroot is encrypted and
$ croutonversion 
crouton: version 1-20141231011135~master:992afe3e
release: sid
architecture: amd64
targets: gnome
host: version 6310.68.0 (Official Build) stable-channel quawks 

I did a few tweaks inside the chroot after installing it, but I can't imagine how any of them would have broken then release detection...

Thanks,
JM

**Comment by janpmedlock** [comment]
Ah ha!  There seem to be 2 conditions that my changes did not satisfy:
1. There must be sources.list and instead of files in sources.list.d
2. There must be the version name 'sid' in sources.list rather than the alias 'unstable'.

Thanks for the help.

**Comment by dnschneid** [comment]
Yep!  crouton behaves well in the presence of lots of hacks, but some things do end up confusing it...

**Comment by dahveed** [comment]
I have the same issue ( https://github.com/dnschneid/crouton/issues/2174 ), so I tried your suggestion. I went into the chroot and edited the sources.list. It looks like this now:

deb http://mirrors.ustc.edu.cn/ubuntu/ trusty multiverse universe restricted main  
deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty multiverse universe restricted main  
deb http://mirrors.ustc.edu.cn/ubuntu/ trusty-updates multiverse universe restricted main 
deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty-updates multiverse universe restricted main     
deb http://mirrors.ustc.edu.cn/ubuntu/ trusty-security multiverse universe restricted main 
deb-src http://mirrors.ustc.edu.cn/ubuntu/ trusty-security multiverse universe restricted main 

(I live in China so I'm using Chinese mirrors)

I also deleted the sources.list.d (it didn't have any critical application sources).

However, attempting to update crouton in Crosh still gives the error "release not recognized." Forcing the update (/crouton -u -u) doesn't work either. My release is trusty, and it's clearly listed in each line of my sources list, so why is it still unrecognized by crouton?

Any help would be great! Thank you.
