### ISSUE TITLE
xiwi: page zoom results in black screen

### ISSUE THREAD

**Issue by vsukul** [dnschneid/crouton#1295]
installed a new chroot trusty.xiwi (via sudo sh ~/Downloads/crouton -t xiwi,xfce -r trusty -n trusty.xiwi)
on launching 'sudo startxfce4', I get a blank window. The extension says that a connection is established and that the chroot is running. 

This is the output in crosh below. I can't run crouton version b/c i'm not sure how to access the chroot...
-----------------------------------------------------
![screenshot 2015-01-01 at 1 49 58 am](https://cloud.githubusercontent.com/assets/6565484/5591774/86556f94-9158-11e4-8c4b-8ea33d9bee91.png)

sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty.xiwi...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-70-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Dec 17 22:03:20 PST 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashtree=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=761f1bd944a291de8466b50f99e2f5c9ec30105a salt=e9c9a882999db80f8d36f8ea5d1dc9a1a344438ce74ec141b93cff89e5422d7c" noinitrd vt.global_cursor_default=0 kern_guid=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic 
Build Date: 10 December 2014  06:15:52PM
xorg-server 2:1.15.1-0ubuntu2.6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jan  1 01:39:03 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a tab window.
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(xfwm4:22683): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed
Error: target STRING not available

(polkit-gnome-authentication-agent-1:22725): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:22725): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfsettingsd:22745): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfwm4:22683): xfwm4-WARNING **: The property '/general/double_click_distance' of type int is not supported
find_shm: Invalid signature, fetching new shm!
find_shm: Invalid signature, fetching new shm!
find_shm: Invalid signature, fetching new shm!
find_shm: Invalid signature, fetching new shm!
socket_client_read_frame_header: Connection close from WebSocket client.
find_shm: Invalid signature, fetching new shm!
find_shm: Invalid signature, fetching new shm!
socket_client_read_frame_header: Connection close from WebSocket client.
socket_client_read_frame_header: Connection close from WebSocket client.
find_shm: Invalid signature, fetching new shm!
socket_client_read_frame_header: Connection close from WebSocket client.
^C
Session terminated, terminating shell.../usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Running exit commands...
xscreensaver: 01:43:05: SIGHUP received: restarting...
xscreensaver: 01:43:05: running as vishad/vishad (1000/1000)

(xfsettingsd:22745): libxfce4ui-WARNING **: ICE I/O Error

(xfsettingsd:22745): libxfce4ui-WARNING **: Disconnected from session manager.

(xfwm4:22683): libxfce4ui-WARNING **: ICE I/O Error

(xfwm4:22683): libxfce4ui-WARNING **: Disconnected from session manager.

(xfce4-volumed:22777): xfce4-volumed-CRITICAL **: xvd_context_state_callback: The connection failed or was disconnected, is PulseAudio Daemon running?
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xscreensaver: 01:43:05: Can't open display: :1.0
xscreensaver: 01:43:05: running as vishad/vishad (1000/1000)

xscreensaver: 01:43:05: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html

(EE) Server terminated successfully (0). Closing log file.

/usr/bin/xinit: unexpected signal 2
 ...terminated.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty.xiwi...
chronos@localhost / $ sudo startxfce4
 
Entering /mnt/stateful_partition/crouton/chroots/trusty.xiwi...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-70-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Dec 17 22:03:20 PST 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashtree=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=761f1bd944a291de8466b50f99e2f5c9ec30105a salt=e9c9a882999db80f8d36f8ea5d1dc9a1a344438ce74ec141b93cff89e5422d7c" noinitrd vt.global_cursor_default=0 kern_guid=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic 
Build Date: 10 December 2014  06:15:52PM
xorg-server 2:1.15.1-0ubuntu2.6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jan  1 01:43:17 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a tab window.
xfce4-session: No gpg or ssh authentication agent found
Timeout waiting for extension to connect.
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:29506): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:29506): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
Error: target STRING not available

(xfsettingsd:29517): xfsettingsd-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
socket_client_read_frame_header: Connection close from WebSocket client.

**Comment by tedm** [comment]
before sudo startxfce4, go to a crosh / shell terminal and type:

sudo enter-chroot

cd /usr/local/bin

croutonversion

while in the chroot, may want to remove xscreensaver, perhaps that is what is blanking your screen?

**Comment by linux4kix** [comment]
The zoom to your window is set to non 100%.  You can right click on title bar and change it there.  That fixed it for me.

**Comment by vsukul** [comment]
that was the fix! thanks! i guess any type of zoom affects rendering?

**Comment by dylanPowers** [comment]
@linux4kix Thanks! Looks like a warning for the zoom level is necessary. On 1080p screens like the toshiba chromebook 2, having the default zoom != 100% is a bit of a necessity for daily browsing so I imagine this will be an ongoing problem.

**Comment by montauk** [comment]
@linux4kix I've spent hours trying to figure out why xiwi wasn't working for me! I imagine many users with 1080p screens will be running into this issue.

**Comment by vsukul** [comment]
so i've been able to install xiwi on my chromebox with xfce and it works like a charm. for some reason, i can't get the copy/paste (shared clipboard) to work despite installing the extension target several times. any thoughts?

**Comment by tcagle** [comment]
Did you install the crouton chrome browser integration extension to your
chromebook side ?

**Comment by tcagle** [comment]
Oh, forgot to mention you can find the browser extension here:
Check out "crouton integration":
https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom?utm_source=gmail

**Comment by linux4kix** [comment]
The performance of the new extension is much better, however I preferred the old behavior.  Now it fullscreens and sees the entire xrandr surface as a single desktop.  If you have an external monitor plugged in that can give a less than desirable output.  I preferred the old plugins behavior that would let me run my linux desktop on just one display.

**Comment by vsukul** [comment]
I do have the extension installed... Copy paste actually works fine on my chromebook,  bit I can't seem to get it working on my chromebox.

**Comment by dnschneid** [comment]
@linux4kix it sounds like you reverted back to native xorg...

So if I understand correctly, having page zoom results in xiwi not displaying anything?  System zoom should work fine.

**Comment by vsukul** [comment]
seems to be the case.

**Comment by YrrchSebor** [comment]
The main issue I have seen on my HP 14(2013) model, with Trusty XFCE,xiwi and the extension installed is I can never open Trusty with the extension on first boot, it constantly says 'Disconnected(retrying every 5 seconds)'. But once I open it with 'sudo startxfce4' thru the terminal, the extension works great.

**Comment by DennisLfromGA** [comment]
@YrrchSebor - For clarification, I'm just wondering how you are attempting to open Trusty on your first boot, what command(s) are you using?

**Comment by YrrchSebor** [comment]
@:DennisLfromGA: I'm just clicking on the Crouton extension and trying to open it like that. It works after I've already started Crouton thru the terminal with 'sudo startxfce4', but if i haven't done that yet, the extension will keep saying it's trying to connect but it never does. I wasn't sure if this was by design or if the extension is supposed to open Crouton straight away..

**Comment by DennisLfromGA** [comment]
@YrrchSebor - It's really by design; you have to open a cros shell and do your ```sudo startunity``` thing first, then the 'crouton integration' extension can '*see*' it and will switch to it. 
There's no way to start a chroot without first using one of the ```start*``` scripts in a cros shell.
That is, unless you're willing to go through some loops first, see '[Autostart crouton chroot at ChromeOS startup](https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup)'.

**Comment by montauk** [comment]
@YrrchSebor @DennisLfromGA Well one could also install a DE/WM, add it to `~/.xinitrc` and start the chroot with `sudo enter-chroot xinit`?

**Comment by dylanPowers** [comment]
@montauk Yep. That's what I'm doing since I'm using Awesome. It's been working without a hitch.

**Comment by DennisLfromGA** [comment]
@montauk - I was just explaining it using the conventional ```start*``` script syntax but, yep, you're right, there are other ways to start a DE/WM.

**Comment by YrrchSebor** [comment]
Thanks guys for the answers. I'm fine with using the terminal initially to open my chroot. I really like using the button above the number 6.... when my chroot is running, that button will show my Chromeos and Ubuntu desktops.

**Comment by murphycc** [comment]
I just read this thread and am sure it must be what I'm seeing with my blank screen with KDE as well. I think it's the zoom issue.

Question: Is there a way to remove the xiwi target after I have installed it? Or better yet, if I want to revert back to the non-tabbed version of chroot (where I switch back and forth to chromeos/kde using ctrl-alt-shift-forward/back arrow method again) -- is there a way to do this? Put another way, I just want to disable the tabbed version. It doesn't work if I just uninstall the crouton integration extension, as crouton still wants to connect with it.

-Chris

**Comment by dylanPowers** [comment]
@murphycc Run ```sudo sh -e ~/Downloads/crouton -u -t xorg -n your-chroot-name``` to go back.

**Comment by murphycc** [comment]
Great! Thanks, Dylan.

**Comment by rrolsbe** [comment]
Can BOTH crouton targets (extension AND xiwi)  be installed as the same time?  Or is it one or the other?  I performed a crouton update twice once to install the xiwi target and again to install the extension target.  After performing the second extension target update and launching crouton via the "sudo startxfce" command, my Chromebook rebooted to the recovery screen - lost all my configurations.  I believe crouton reset the dev_boot_signed_only to 1 which would not allow booting because I had previously executed the enable-vmx.sh script (which sets that variable to 0 and modifies kernel boot parameters).

Thanks Much for any Clarification!
Regards, Ron

**Comment by drinkcat** [comment]
@rrolsbe : xiwi depends on the extension (so it's either both, or just the extension).

See https://github.com/dnschneid/crouton/issues/765#issuecomment-69986327 for an answer to to second part.

**Comment by ubuntunoob** [comment]
In the past I have successfully installed precise with the xiwi,xfce extensions.

I want to run xbmc but other versions such as trusty and saucy do not  seem to work well, so I am stuck with precise.

Although I can successfully install precise, recently I cannot install the xiwi extension which is necessary for crouton integration.

sudo sh ~/Downloads/crouton -t xiwi -u

I receive the following message after an install, but only with a precise install

The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xorg-video-abi-11
                            Depends: xserver-xorg-core (>= 2:1.10.99.901)
E: Unable to correct problems, you have held broken packages.


Any assistance would be appreciated.

**Comment by dnschneid** [comment]
That's #1294

**Comment by ubuntunoob** [comment]
Thank you!
Regarding broken upgrade to xiwi (#1294), I was able to install the missing dependencies and get precise working with crouton integration.

After installing precise

sudo sh ~/Downloads/crouton -t xfce

I then installed the missing dependencies

sudo apt-get install xorg-video-abi-11 xserver-xorg-core

and updated

sudo sh ~/Downloads/crouton -t extension -u

**Comment by drinkcat** [comment]
Indeed, there is an issue when zooming the page (right click on title bar->zoom).

For now, we probably do not want to allow zooming (we could later on, possibly with another setting similar to "HiDPI" option we currently have).

We could force the page zoom to 100%. There is now an API (https://developer.chrome.com/extensions/tabs#method-setZoom), but unfortunately it is only available on dev channel...

The alternative is to compensate for page zoom (PR coming).
