### ISSUE TITLE
Unable to put chroot in window

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1297]
I have a trusty chroot with xiwi and extension and I can't find a button anywhere that says "Pop out chroot into window." Did I do something wrong? I installed the chroot today.

**Comment by tedm** [comment]
what DE target did you install (xfce? etc.) Did you install the Chrome Extension app from the app store?

**Comment by firestar115** [comment]
Sorry, I fixed it. I usually do stuff like -t core,audio,x11 and so
on, but I looked at a different issue and saw you only had to specify
-t xiwi,xfce4 and it worked.

On 1/1/15, tedm <notifications@github.com> wrote:
> what DE target did you install (xfce? etc.) Did you install the Chrome
> Extension app from the app store?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1297#issuecomment-68505026


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by tedm** [comment]
Good to see you got it working.
