### ISSUE TITLE
Error to launch ubuntu after rebooting of my chromebook

### ISSUE THREAD

**Issue by flo9Z** [dnschneid/crouton#1298]
Hi, After rebooting i have this error : 

/etc/X11/xinit/xserverrc: 19: exec: /usr/bin/X: not found
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I have tested : 

sudo sh ~/Downloads/crouton -n precise -u
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xserverrc-x11 into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startlxde into the host...
Installing startunity into the host...
Installing startunity into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing crouton-unity-autostart into the chroot...
Installing unity-autostart.desktop into the chroot...
Installing unity-profiled into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
E: The method driver /usr/lib/apt/methods/https could not be found.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Thanks for your help !

**Comment by flo9Z** [comment]
I have tested this command : sudo apt-get install apt-transport-https

now i have : 
sudo sh ~/Downloads/crouton -u -n precise
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xserverrc-x11 into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startlxde into the host...
Installing startunity into the host...
Installing startunity into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing crouton-unity-autostart into the chroot...
Installing unity-autostart.desktop into the chroot...
Installing unity-profiled into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://ppa.launchpad.net precise Release.gpg
Ign http://ppa.launchpad.net precise Release  
Get:1 http://archive.ubuntu.com precise Release.gpg [198 B]
Get:2 http://archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:3 http://archive.ubuntu.com precise-security Release.gpg [198 B]
Get:4 http://repo.steampowered.com precise Release.gpg [490 B]
Get:5 http://repo.steampowered.com precise Release [2303 B]
Hit http://archive.ubuntu.com precise Release                                
Hit http://archive.ubuntu.com precise-updates Release                        
Ign http://ppa.launchpad.net precise/main TranslationIndex                   
Hit http://archive.ubuntu.com precise-security Release                 
Hit http://archive.ubuntu.com precise/main Sources                                          
Hit http://archive.ubuntu.com precise/restricted Sources             
Hit http://archive.ubuntu.com precise/universe Sources               
Hit http://archive.ubuntu.com precise/multiverse Sources             
Hit http://archive.ubuntu.com precise/main amd64 Packages            
Hit http://archive.ubuntu.com precise/restricted amd64 Packages      
Hit http://archive.ubuntu.com precise/universe amd64 Packages        
Hit http://archive.ubuntu.com precise/multiverse amd64 Packages      
Hit http://archive.ubuntu.com precise/main i386 Packages             
Hit http://archive.ubuntu.com precise/restricted i386 Packages       
Get:6 http://repo.steampowered.com precise/steam Sources [549 B]     
Hit http://archive.ubuntu.com precise/universe i386 Packages                                                
Hit http://archive.ubuntu.com precise/multiverse i386 Packages                         
Hit http://archive.ubuntu.com precise/main TranslationIndex                            
Hit http://archive.ubuntu.com precise/multiverse TranslationIndex                      
Hit http://archive.ubuntu.com precise/restricted TranslationIndex                      
Hit http://archive.ubuntu.com precise/universe TranslationIndex                        
Hit http://archive.ubuntu.com precise-updates/main Sources                             
Hit http://archive.ubuntu.com precise-updates/restricted Sources                       
Hit http://archive.ubuntu.com precise-updates/universe Sources                         
Hit http://archive.ubuntu.com precise-updates/multiverse Sources                       
Hit http://archive.ubuntu.com precise-updates/main amd64 Packages                      
Get:7 http://repo.steampowered.com precise/steam amd64 Packages [604 B]                
Get:8 http://repo.steampowered.com precise/steam i386 Packages [804 B]                 
Ign http://repo.steampowered.com precise/steam TranslationIndex                                              
Hit http://archive.ubuntu.com precise-updates/restricted amd64 Packages                
Hit http://archive.ubuntu.com precise-updates/universe amd64 Packages
Hit http://archive.ubuntu.com precise-updates/multiverse amd64 Packages
Hit http://archive.ubuntu.com precise-updates/main i386 Packages 
Hit http://archive.ubuntu.com precise-updates/restricted i386 Packages
Hit http://archive.ubuntu.com precise-updates/universe i386 Packages                   
Hit http://archive.ubuntu.com precise-updates/multiverse i386 Packages                 
Hit http://archive.ubuntu.com precise-updates/main TranslationIndex                    
Hit http://archive.ubuntu.com precise-updates/multiverse TranslationIndex              
Hit http://archive.ubuntu.com precise-updates/restricted TranslationIndex
Hit http://archive.ubuntu.com precise-updates/universe TranslationIndex                 
Hit http://archive.ubuntu.com precise-security/main Sources                             
Hit http://archive.ubuntu.com precise-security/restricted Sources 
Hit http://archive.ubuntu.com precise-security/universe Sources   
Hit http://archive.ubuntu.com precise-security/multiverse Sources 
Err http://ppa.launchpad.net precise/main Sources                                       
  404  Not Found
Hit http://archive.ubuntu.com precise-security/main amd64 Packages                      
Hit http://archive.ubuntu.com precise-security/restricted amd64 Packages
Hit http://archive.ubuntu.com precise-security/universe amd64 Packages
Hit http://archive.ubuntu.com precise-security/multiverse amd64 Packages                
Hit http://archive.ubuntu.com precise-security/main i386 Packages                       
Err http://ppa.launchpad.net precise/main amd64 Packages                                
  404  Not Found
Err http://ppa.launchpad.net precise/main i386 Packages                                 
  404  Not Found
Hit http://archive.ubuntu.com precise-security/restricted i386 Packages                 
Hit http://archive.ubuntu.com precise-security/universe i386 Packages                   
Hit http://archive.ubuntu.com precise-security/multiverse i386 Packages
Hit http://archive.ubuntu.com precise-security/main TranslationIndex
Hit http://archive.ubuntu.com precise-security/multiverse TranslationIndex
Hit http://archive.ubuntu.com precise-security/restricted TranslationIndex
Hit http://archive.ubuntu.com precise-security/universe TranslationIndex
Hit http://archive.ubuntu.com precise/main Translation-en
Hit http://archive.ubuntu.com precise/main Translation-fr
Hit http://archive.ubuntu.com precise/multiverse Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en
Get:9 https://private-ppa.launchpad.net precise Release.gpg [316 B]
Hit http://archive.ubuntu.com precise/multiverse Translation-fr
Hit http://archive.ubuntu.com precise/restricted Translation-en
Hit http://archive.ubuntu.com precise/restricted Translation-fr                         
Hit http://archive.ubuntu.com precise/universe Translation-en                           
Hit http://archive.ubuntu.com precise/universe Translation-fr                           
Ign http://ppa.launchpad.net precise/main Translation-fr                                
Hit http://archive.ubuntu.com precise-updates/main Translation-en                       
Hit http://archive.ubuntu.com precise-updates/main Translation-fr 
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-fr
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en
Hit http://archive.ubuntu.com precise-updates/restricted Translation-fr
Hit http://archive.ubuntu.com precise-updates/universe Translation-en
Hit http://archive.ubuntu.com precise-updates/universe Translation-fr
Hit http://archive.ubuntu.com precise-security/main Translation-en
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en
Hit http://archive.ubuntu.com precise-security/restricted Translation-en
Hit http://archive.ubuntu.com precise-security/universe Translation-en
Get:10 https://private-ppa.launchpad.net precise Release [11.9 kB]
Get:11 https://private-ppa.launchpad.net precise/main amd64 Packages [879 B]
Get:12 https://private-ppa.launchpad.net precise/main i386 Packages [872 B]
Get:13 https://private-ppa.launchpad.net precise/main TranslationIndex [357 B]
Ign https://private-ppa.launchpad.net precise/main TranslationIndex
Ign http://repo.steampowered.com precise/steam Translation-en 
Ign https://private-ppa.launchpad.net precise/main Translation-en
Ign http://repo.steampowered.com precise/steam Translation-fr
Ign https://private-ppa.launchpad.net precise/main Translation-fr
Fetched 19.3 kB in 7s (2532 B/s)                                                                                                                    
W: Failed to fetch http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

**Comment by dnschneid** [comment]
Looks like you have some broken PPAs in there.  Remove them from /etc/apt/sources.list.d and try again.
