### ISSUE TITLE
chown /usr/bin  -->unable to restart system

### ISSUE THREAD

**Issue by roger77** [dnschneid/crouton#1300]
unfortunately I made a mistake and changed the ownership of /usr/bin now I cannot run the sudo command.  I restarted but now 'sudo startunity' gives:

    Enter encryption passphrase for trusty: 
    Entering /mnt/stateful_partition/crouton/chroots/trusty...
    (EE)  
    Fatal server error:
    (EE) Cannot move old log file "/var/log/Xorg.1.log" to "/var/log/Xorg.1.log.old"
    (EE) 
    (EE) 
    Please consult the The X.Org Foundation support 
            at http://wiki.x.org
    for help. 
    (EE) 

how can I fix this problem other than reinstalling the whole buntu? It seems to me the only login option left is with the chronos user, can this be used in any helpful way?

Thanks a lot!
Roger

PS:
     crouton: version 1-20141231011135~master:992afe3e
     release: trusty
     architecture: amd64
     targets: unity
     host: version 6310.68.0 (Official Build) stable-channel link

**Comment by DennisLfromGA** [comment]
You can log in to your chroot as 'root' and then fix your permissions -

    sudo enter-chroot -u root -n trusty

On Fri, Jan 2, 2015 at 5:18 PM, roger77 <notifications@github.com> wrote:

> unfortunately I made a mistake and changed the ownership of /usr/bin now I
> cannot run the sudo command. I restarted but now 'sudo startunity' gives:
>
> Enter encryption passphrase for trusty:
> Entering /mnt/stateful_partition/crouton/chroots/trusty...
> (EE)
> Fatal server error:
> (EE) Cannot move old log file "/var/log/Xorg.1.log" to "/var/log/Xorg.1.log.old"
> (EE)
> (EE)
> Please consult the The X.Org Foundation support
>         at http://wiki.x.org
> for help.
> (EE)
>
> Is there anyway I can fix this problem when I login as kronos?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1300>.
>



-- 
*DennyL@GMail*

**Comment by roger77** [comment]
Thanks. I was able to login and fix the permissions. I still get the same error when I start unity. Interestingly I can "sudo startunity" from enter-chroot. I think I just need to restart with a clean install

**Comment by DennisLfromGA** [comment]
You need 'sudo' in crosh to 'startunity' but inside the chroot you shouldn't use 'sudo' to startunity 'cause it'll mess up permissions. There's a fix coming soon that prevents starting unity and other DEs as root inside the chroot.
