### ISSUE TITLE
Always saying that no chroot found while i type in sudo startunity?    help pls i'm newbie at this! 

### ISSUE THREAD

**Issue by Jestin56** [dnschneid/crouton#1303]
This happened when i was trying to download crouton and after it did not let me set a user name or a password but when i type in shell it say that something is already in the file but when i type in sudo startunity it can't find any chroot. so if someone can help me with solving it or tell me how to delete it then it would be great

**Comment by tedm** [comment]
enter the chroot from a crosh / shell prompt with:

sudo enter-chroot

cd /usr/local/bin

and delete-chroot [precise]

withiout the brackets above, and if necessary, change name of chroot to the one you want to delete.

**Comment by Jestin56** [comment]
thanks for your help now i have it downloaded

**Comment by DennisLfromGA** [comment]
@tedm - 
Is that right? I don't believe you should enter the chroot to delete it.
I think the procedure is to open a crosh shell (press ```Ctrl-Alt-T``` and type ```shell```) 
then type ```sudo delete-chroot [chrootname]```.

**Comment by tedm** [comment]
@DennisLfromGA Dennis you are correct. The `delete-chroot` fortunately is not in the chroot /usr/local/bin dir, but is in crosh / shell, it's a sym link to edit-chroot. One should only delete a chroot before entering or after exiting cleanly. Thanks for the correction.
