### ISSUE TITLE
Question from a newbie..... Invalid target for "Precise" and "Trusty"

### ISSUE THREAD

**Issue by clifford1993** [dnschneid/crouton#1304]
Hi... I am really new to crouton :)

I installed crouton "Precise" before, and decided to powerwash when I saw "Trusty" is out. 

After powerwashing... both
chronos@localhost / $ sudo sh ~/Downloads/crouton -t trusty
AND
chronos@localhost / $ sudo sh ~/Downloads/crouton -t precise

output as
Invalid target "trusty". or Invalid target "precise".

xfce seems fine (thats the only other version I tried...)

here is the output of "cat /etc/lsb-release"
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={493FA09F-94EA-B829-46E0-48B12FD7264D}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={493FA09F-94EA-B829-46E0-48B12FD7264D}
CHROMEOS_RELEASE_BOARD=swanky-signed-mpkeys
CHROMEOS_RELEASE_DESCRIPTION=6310.68.0 (Official Build) stable-channel swanky 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6310.68.0
GOOGLE_RELEASE=6310.68.0

I checked around and don't seems to find someone asking about that.. I assumes its my problem?
Thanks a LOT!!

**Comment by tedm** [comment]
trusty and precise are releases not targets, xfce is a valid target.

**Comment by clifford1993** [comment]
Oh... sorry I have missed it
