### ISSUE TITLE
Crouton on every computer ?

### ISSUE THREAD

**Issue by nathan30** [dnschneid/crouton#1306]
Hi,

I want to knwo if it's possible to you to do the same works with crouton and crouton extension on all computer using chrome as browser ?

Thanks in advance

**Comment by DennisLfromGA** [comment]
No such luck, 'crouton' is a chroot that relies on Chromium/ChromeOS.

On Sun, Jan 4, 2015 at 1:10 PM, nathan30 <notifications@github.com> wrote:

> Hi,
>
> I want to knwo if it's possible to you to do the same works with crouton
> and crouton extension on all computer using chrome as browser ?
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1306>.
>



-- 
*DennyL@GMail*

**Comment by nathan30** [comment]
Too bad... 

Because it will be a great alternative on low storage pc based on windows...

**Comment by dnschneid** [comment]
Just install a minimal Debian install or an Ubuntu Server install and you'll get basically the same thing.
