### ISSUE TITLE
Question: Run i386 binary

### ISSUE THREAD

**Issue by sapstern** [dnschneid/crouton#1307]
Hi,

I am stuck in getting i386 binarys to run. (Ubuntu 14.04 Samsung 3 series chromebook)

I learned, that I have to install libc6-dev-armhf-cross / libc6-armel-cross in order to get the i386 stuff to run.

But package installer tells me "dependency not satisfiable".

Thanks for any hints

Matthias

**Comment by dnschneid** [comment]
You can't run i386 binaries on ARM-based devices.
