### ISSUE TITLE
New install errors

### ISSUE THREAD

**Issue by lecrouch** [dnschneid/crouton#1308]
Hey,
I have used chroot/crouton on my chromebook since August or so.  I was using it for school so I haven't touched it for about a month.  Turned it on the other day and no sauce.  Didn't seem to want to work.  No big deal, I pulled it out of devo mode, put it back in, and re-installed.  However, things don't seem to be working quite so well, software doesn't seem to install as cleanly as before.  So I looked at my terminal dump upon entering the xfce side, and found quite a few errors, so here it is.  What can I do?  I am a bit of a linux newb, but trying to become more proficient, so bare with me!

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-58-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Dec 10 15:53:53 PST 2014 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=adfcfdd3-09e4-b948-b4e5-e577d794574e/PARTNROFF=1 hashtree=PARTUUID=adfcfdd3-09e4-b948-b4e5-e577d794574e/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5aa7077b7464c281aacd2b0a77d97f8c3fc21050 salt=884031a1fca8d128eda8fc9dcb2554411cc0b33d72a3c8d1c83fab8dfacb538f" noinitrd vt.global_cursor_default=0 kern_guid=adfcfdd3-09e4-b948-b4e5-e577d794574e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3 
Build Date: 09 December 2014  11:03:52PM
xorg-server 2:1.15.1-0ubuntu2~precise4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Sun Jan  4 15:21:29 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
xfce4-session: No gpg or ssh authentication agent found

(polkit-gnome-authentication-agent-1:18685): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:18685): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfce4-session:18665): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(Thunar:18681): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-panel:18679): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfsettingsd:18695): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:18746): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfwm4:18675): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:18749): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfdesktop:18683): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:18683): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:18683): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:18683): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(II) AIGLX: Suspending AIGLX clients for VT switch
^C/usr/bin/xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 15:21:45: SIGHUP received: restarting...
xscreensaver: 15:21:45: running as lecrouch/lecrouch (1000/1000)

xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.

(xfsettingsd:18695): libxfce4ui-WARNING **: ICE I/O Error

(xfsettingsd:18695): libxfce4ui-WARNING **: Disconnected from session manager.
Hangup
Running exit commands...
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xscreensaver: 15:21:45: Can't open display: :1.0
xscreensaver: 15:21:45: running as lecrouch/lecrouch (1000/1000)

xscreensaver: 15:21:45: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html

(EE) Server terminated successfully (0). Closing log file.

/usr/bin/xinit: unexpected signal 2
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
chronos@localhost / $

**Comment by dnschneid** [comment]
Looks fine.  What is not working properly?
