### ISSUE TITLE
machine reboots on vagrant up using virtualbox.

### ISSUE THREAD

**Issue by komuW** [dnschneid/crouton#1309]
# background:
I have an acer c720 2gb RAM, 32gb SSD chromebook. I have been using crouton on it for almost a year now and its my main dev machine. I usually use vagrant and virtualbox for my dev machine and everything has been working fine.

Here's the output from the croutonversion command          
crouton: version 1-20141231011135~master:992afe3e
release: trusty
architecture: amd64
targets: xfce
host: version 6310.68.0 (Official Build) stable-channel peppy 

and the output from  cat /etc/lsb-release:     
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_RELEASE_BOARD=peppy-signed-mp-v2keys
CHROMEOS_RELEASE_DESCRIPTION=6310.68.0 (Official Build) stable-channel peppy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6310.68.0
GOOGLE_RELEASE=6310.68.0

# issue:
1. so the crouton on my chromebook crashed before christmas and come 1st of january I deleted all croutons(because I wanted a fresh install) using the command:      
$ sudo delete-chroot -ad 
2. I then downloaded crouton and installed as per usual       
$ sudo sh ~/Downloads/crouton -r trusty -t xfce 
3. Then I built linux headers and installed virtualbox as per usual (https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-%28x86%29)
4. I then enabled VT_x for virtualbox as per usual (https://github.com/dnschneid/crouton/wiki/Repack-kernel-to-Enable-VT_x-for-Virtualbox)

Now whenever I try to bring up a VM using vagrant up, the box gets imported but when it reaches the boot VM command, the machine 'crashes' and reboots.
And by machine, I mean the chromebook OS restarts and I have to login and sudo startxfce4.

I tried to start vagrant with debug option ie       
$ vagrant up --debug &> ~/Downloads/vagrant.log      
and here's the output of that log file: (https://gist.github.com/komuW/caeb33a164d0d6d6310a)

Anyone, know what could be the issue? I'm happy to provide any clarification needed.

Thanks,
Komu W.

**Comment by divx118** [comment]
Could you try the kernel headers from https://github.com/divx118/crouton-packages/blob/master/README.md These are build a while ago. I should build some new ones and see if I can replicate and if it is something they changed in the kernel config. There has been another report, who also build his own kernel headers recently and he had the same issue a reboot of the chromebook. Very likely a kernel panic. He then used the ones I build and they worked.  
PS: Note for the future https://github.com/dnschneid/crouton/issues/1278

**Comment by komuW** [comment]
@divx118  Thanks for the help. It worked. 
For anyone else who may encounter the same problem if it helps:
After buliding the headers using the method suggested by @divx118 , I downloaded and installed VirtualBox version 4.3.14 (released July 15th 2014) (http://download.virtualbox.org/virtualbox/4.3.14/virtualbox-4.3_4.3.14-95030~Ubuntu~raring_amd64.deb)

I didn't install the latest version of virtualbox.

Thanks @divx118 once again.

**Comment by divx118** [comment]
Ah ok nice it works for you. BTW I think the newest virtualbox version should also work.  
To avoid confusion you don't build the kernel headers, they were build by me. You just installed them by running the script setup-headers.sh.
This script will: 
 * add my signing key with which the packages are signed.
 * add the ppa to the sources.list.d (/etc/apt/sources.list.d/crouton-packages.list)
 * install linux-headers-
 * install linux-image-
 * add a rc.local script to load vboxdrv modules on entering the chroot if they are available.

Seems there is an issue then when building the kernel-headers with recent source. I will see if I can replicate and if something significant has changed in the kernel config.
