### ISSUE TITLE
Running Ubuntu in Crouton without xbindkeys installed

### ISSUE THREAD

**Issue by chrisofCCL** [dnschneid/crouton#1310]
Hi, I'm a newbie to this forum.  

I am recently up and running with Trusty in the Crouton environment and was experimenting with different ways of sorting my keybindings. As part of that I temporarily de-installed xbindkey but now I cannot launch trusty at all.  I obviously need to re-install it but can't do that until I can get back into it and install it via synaptic.

HELP!

**Comment by chrisofCCL** [comment]
Nothing like asking for help to stimulate the brain into finding an answer!  Of course, xbindkeys can be installed from the command-line before starting unity.  sudo apt-get install xbindkeys.

Now up and going again.

**Comment by dnschneid** [comment]
For the record, updating the chroot would also fix such issues.
