### ISSUE TITLE
No audio output - crouton precise - Unity

### ISSUE THREAD

**Issue by oryt** [dnschneid/crouton#1311]
No audio when running in Unity works in Chroome. No audio outputs in audio setting.
No issue when updating crouton.

crouton: version 1-20141231011135~master:992afe3e
release: precise
architecture: amd64
targets: unity
host: version 6310.68.0 (Official Build) stable-channel leon 

System Volume (0-100): 100 
Capture Gain (-17.25 - 30.00): 20.00dB 
Output Devices:
	ID	Name
	6	HDA Intel PCH: ALC283 Analog:1,0
	5	HDA Intel MID: HDMI 2:0,8
	4	HDA Intel MID: HDMI 1:0,7
	3	HDA Intel MID: HDMI 0:0,3
Output Nodes:
	 ID	 Vol   Plugged	L/R swapped	      Time	Type		 Name
	6:0	  100       no	            no	         0	HEADPHONE        Headphone
	6:1	   20      yes	            no	1420462112	INTERNAL_SPEAKER*Speaker
	5:0	  100       no	            no	         0	HDMI             HDMI/DP,pcm=8 Jack
	4:0	  100       no	            no	         0	HDMI             HDMI/DP,pcm=7 Jack
	3:0	  100       no	            no	         0	HDMI             HDMI/DP,pcm=3 Jack
	3:1	  100       no	            no	         0	HDMI             HDMI
Input Devices:
	ID	Name
	7	HDA Intel PCH: ALC283 Analog:1,0
Input Nodes:
	 ID	Gain   Plugged	L/R swapped	      Time	Type		 Name
	7:0	    0       no	            no	         0	MIC              Mic Jack
	7:1	    0      yes	            no	1420462112	INTERNAL_MIC    *Internal Mic
Selected Output Node: 6:1
Selected Input Node: 7:1
Attached clients:
	ID	pid	uid
	7	11184	1000
	18	11184	1000
	21	28703	1000
	22	28703	1000
Num active streams: 0
Last audio active time: 843, 776948125

**Comment by dnschneid** [comment]
What groups is your user in?

**Comment by oryt** [comment]
Its only me no specific groups set up

**Comment by dnschneid** [comment]
Could you please post the output of `groups` from inside the chroot?

**Comment by oryt** [comment]
myname, video, sudo, plugdev, audio

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
