### ISSUE TITLE
Alt + '-' not working

### ISSUE THREAD

**Issue by ClaudeJGreengrass** [dnschneid/crouton#1313]
You can minimize a browser window with Alt + '-'  (without the quotes)
It doesn't work for the Crouton window.

This was tested on a fresh install of Unity, Jan 4, 2015

**Comment by drinkcat** [comment]
I didn't know about that shortcut, but, generally, we want the crouton window to eat most keyboard shortcuts (after all you might need to type Alt+- in your crouton app).

Alt-tab is an exception (in full screen, crouton eats it; as window, it is passed to Chromium OS), but it's not something we did intentionally: it's Chromium OS' default behaviour. 

If you really want Alt+- to work, you can setup a shortcut in the chroot, that runs `croutoncycle cros` when that key combo is typed. That'll do just what you want.

**Comment by drinkcat** [comment]
Another keyboard-only option is Fullscreen followed by alt+tab. Or remap Alt+-.
