### ISSUE TITLE
xiwi and US international keyboard (ralt not working)

### ISSUE THREAD

**Issue by montauk** [dnschneid/crouton#1314]
**Commands with `ralt` have no effect**

My current set up is to start my chroot with `sudo enter-chroot xinit`, reading from the following `.xinitrc` file:
```
setxkbmap -rules evdev -model evdev -layout us -variant intl
exec i3
```
As you can see I've set it up to use the US international keyboard layout. Under ChromeOS having this layout works the following way: If I want the letter `ü` I type `Shift + '` followed by `u`. By replacing u with a or o I get ä or ö. Yet the letter ß works differently, I have to type `ralt + s`. So far so good.

Before using xiwi I remember it working just the same way under my chroot. Yet now, probably due to it being windowed, the behaviour has changed: in order to get ä, ö or ü I have to press `Shift + '` twice in order for it to work, which isn't too much of an inconvenience. But trying to get the letter ß has proven to be impossible. When I try the default command all I get is `s`. 

Any ideas?

**Comment by drinkcat** [comment]
Regarding `ü`: Same basic issue as #1275. There is a conflict between Chromium OS and crouton. Switching to Chromium OS US "normal" layout, and Intl in crouton, will fix it.

Regarding `ß`:
 - We are missing the mapping for Alt-Gr in kiwi (I think that could be fixed when both Chromium OS and crouton are using the same layout). That's an easy fix.
 - If we want Chromium OS US layout + intl in crouton, that's a similar issue to #1275, again (Alt R gets translated to Alt R, and not the key that is in the same position (Alt-Gr on a intl keyboard, I guess)).

Bottomline, I'm merging this into #1275: any non-US keyboard layout is basically broken.
