### ISSUE TITLE
Crouton privileges issue

### ISSUE THREAD

**Issue by chrisofCCL** [dnschneid/crouton#1315]
I'm running Trusty on Crouton, on an Asus C300 Chromebook.  Mostly all good but I have a few issues that I think might be related to privileges (or lack of). Symptoms are:
- I always get asked to unlock my keyring when I first login
- I cannot see shared folders on my local network
- I cannot set sharing permissions on a local folder
    -- Even if I try from a "sudo nautilus" window I get "'net usershare' returned error 255: net usershare add: cannot convert name "Everyone" to a SID. The connection was refused. Maybe smbd is not running."
- I am prompted for an admin password when I insert a USB drive (although I can ignore it - the drive still works)
- More annoyingly I can eject a USB drive only from a "sudo nautilus" window.
- Some menu bar applets do not display (eg the one installed by Copy.com cloud storage)

Are these  normal crouton artefacts or is there something I can do to improve things??

output from enter-chroots.. croutonversion is 

Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20141228012255~master:00179dae
release: trusty
architecture: amd64
targets: unity
host: version 6310.68.0 (Official Build) stable-channel quawks 
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

**Comment by dnschneid** [comment]
Most of these are normal, unfortunately.  You can try the `unity-desktop` target and see if the additional stuff resolves some of the issues, but for a mix of architectural reasons, I don't think we'll be fixing those issues.

**Comment by chrisofCCL** [comment]
No problem David. I have workarounds for them all now. The biggest issue
was having to re-mount my sd card (which I have mounted with exec
privileges) with a password every time I closed by Chromebook up, but I got
round that with the powerd fix.All now fine.  And Crouton really is a great
idea!

Thanks

Chris

On Saturday, February 21, 2015, David Schneider <notifications@github.com>
wrote:

> Closed #1315 <https://github.com/dnschneid/crouton/issues/1315>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1315#event-239576364>.
>


-- 
Chris Morris BSc C.Eng MIET
*Chardstock Consulting Ltd*
Bristol

email: chris.chardstockconsulting@gmail.com
mobile: +44 (0) 7976 123257



*Please consider the environment before printing a hard copy of this
e-mail. Chardstock Consulting Ltd. A company registered in England and
Wales.*
*Registered Number 8935506*
