### ISSUE TITLE
brain Freeze( We are sorry some thing  could not load),Activity Aborted

### ISSUE THREAD

**Issue by rameshmca2013** [dnschneid/crouton#1316]
i am developing chrome cast sample application using android , i registered the application  and  chrome cast device in Google developer console,i run the application it showing the error as "brain freeze ,we are sorry some thing could not load", i tried to see the log ,i put in to browser (CHROME CAST IP:9222 ),it showing "The Web Page not Available".,

**Comment by smibarber** [comment]
#262 should definitely help you with that.
