### ISSUE TITLE
Mouse can click but not move

### ISSUE THREAD

**Issue by frontalot** [dnschneid/crouton#1317]
Installed xfce,xiwi,extension,keyboard on an ASUS Chromebox with a Bluetooth keyboard and mouse. Inside the chroot, the mouse can click (both left and right) but not move. The keyboard works completely fine.

Any ideas on how to debug this problem? It makes the chroot basically unusable.

**Comment by plevesque** [comment]
Got the same problem with a Chromebook Asus C200 and a Logitech T630 bluetooth mouse.  Mouse running fine in ChromeOS and don't move in the chrrot.  Running the Dev channel on ChromeOS and installed the trusty chroot with crouton.

**Comment by frontalot** [comment]
Glad to know I'm not the only one. Seems like it's related to Bluetooth, obviously, but it's strange because my Bluetooth keyboard works fine even though the mouse doesn't.

**Comment by dnschneid** [comment]
What kind of mouse is it?  Have you updated recently, and could you post the full output of croutonversion?  If you're actually running xiwi, I don't see how a mouse couldn't work, since we're just using Chromium's mouse events.  If you haven't updated in a while and you're actually using xorg (not in a window), then it could be a touch mouse like in #713

**Comment by dnschneid** [comment]
Oops, reading comprehension.  Yes, you're probably on xorg (not xiwi), and updating will change that.  And yes, this is the same issue and I should re-open the other bug.

**Comment by plevesque** [comment]
I'm using a Logitech T630 and I'm running on Xorg.   Moving to xiwi fixed the mouse problem. My problem is xiwi disable hardware acceleration.   Is it possible to make the mouse work in xorg?  Or is it possible to have hardware acceleration in xiwi?   Thank for the support

**Comment by dnschneid** [comment]
See [the other bug](https://github.com/dnschneid/crouton/issues/713#issuecomment-72798960).

**Comment by kinkha3** [comment]
Watch This Fix!
Latest & Quick Method 2017

For Mouse Movements Not Happening But Clicks DOes!

https://www.youtube.com/watch?v=3u2rEFJ3MMU

**Comment by divx118** [comment]
Hmm didn't know we also supported windows chroots on crouton, must have missed something :)
