### ISSUE TITLE
promptNewPassphrase broken with stdout_to_tty

### ISSUE THREAD

**Issue by christopherschroeder** [dnschneid/crouton#1323]
I've tried to reinstall Ubuntu on my Acer C720 Chromebook, and I can see that it is generating keys but not installing Ubuntu as it has before (see screenshot) -- am I doing something wrong? I'm following the same process as I always have, and I have this same result even after powerwashing my Chromebook, as well as completely restoring the system. Thanks.

![screenshot 2015-01-07 at 11 58 46](https://cloud.githubusercontent.com/assets/10438741/5650609/8bce3854-9665-11e4-9c2c-1433d94e8eb9.png)

**Comment by christopherschroeder** [comment]
See also < https://plus.google.com/104469475353687423627/posts/Zs1CqK1aG9P >.

**Comment by drinkcat** [comment]
Not quite sure what's going on, but reverting `9df99a48bf570a7a66c281bcc48f0742c1f03ce1` fixes the issue. It looks like `stdout_to_tty` is confusing `ecryptfs-wrap-passphrase`.

**Comment by dnschneid** [comment]
Uh nope, the patch just drops the passphrase on the floor.  Reverting until I can fix it.

**Comment by dnschneid** [comment]
Reverted and released.  Tracking the real fix here.

**Comment by christopherschroeder** [comment]
Thanks. Although I'm in over my head, I'm happy to provide whatever
feedback you might find useful -- just let me know. Thanks again.

**Comment by dnschneid** [comment]
The tty branch has a fixed version of this.

**Comment by dnschneid** [comment]
Finally fixed this...

**Comment by christopherschroeder** [comment]
Thanks -- now the commands to toggle back and forth seem to be broken 
after the recent Chromebook update . . . am I missing something?

**Comment by christopherschroeder** [comment]
Thanks.
