### ISSUE TITLE
Super_L key combos not being passed to xiwi

### ISSUE THREAD

**Issue by dylanPowers** [dnschneid/crouton#1324]
Super_L key combos are only working with the standard alphabet keys in xiwi. They aren't working with the number keys, the arrow keys, the spacebar, tab, the enter key, and pretty much anything that isn't alphabetic. 
I did a little debugging with xev and I found that the super_L down event isn't being passed until either the up event occurs or an alphabetic key is pressed.

This is a bit of a show stopper for me and keeps me from using xiwi as my Awesome WM configuration depends a lot on those key combos. 
As mentioned in https://github.com/dnschneid/crouton/issues/1289#issuecomment-68762070 @drinkcat you seem to know a lot about what would be needed to fix this :) You're doing some amazing work!

**Comment by drinkcat** [comment]
Chromium OS under freon (e.g., peppy, dev-channel, `6592.2.0`) always reports "raw" keyboard events (no Search+Left -> Home translation). Which is awesome.

We need to disable the `Super_L` hack when running under freon. Then, we could just use the current xkb keyboard layout (`keyboard target`), or implement our own key translation in Kiwi (might be better as xkb is a bit quirky...).

And I don't think it is worth improving the current situation (under X11).
