### ISSUE TITLE
passwd doesn't work on xiwi,touch

### ISSUE THREAD

**Issue by appsforartists** [dnschneid/crouton#1325]
I tried updating my chroot to use xiwi, but it isn't working.  So, I tried making a new one (putting xiwi first):

```
sh -e /home/chronos/user/Downloads/crouton -f /home/chronos/user/Downloads/crouton_base.tar.bz2 -r raring -t xiwi,touch,extension -n dev
```

It seems to work, but when I tried to enter a password, it returned after the first character.  Any attempt at using `passwd` has the same problem:

```
passwd: Authentication token manipulation error
passwd: password unchanged
```

I can't `sudo`, because it thinks I have a password (even though I don't)

**Comment by hsharrison** [comment]
Happening to me too.

**Comment by drinkcat** [comment]
Is this related to #1323?

In any case, you can fix the password by entering the chroot as root:
`sudo enter-chroot -n chroot_name -u root`
Then modify (or, in this case, set) the user passwd with:
`passwd username`
(it won't ask for the previous password, since you're running as root)

**Comment by appsforartists** [comment]
It very well could be.

I was able to log in as `root` using your instructions.  After running `passwd me`, it doesn't ask me for a password to login as me though (only to `sudo`).
