### ISSUE TITLE
Crouton will not install

### ISSUE THREAD

**Issue by zoneco** [dnschneid/crouton#1326]
Ive been trying for about a day now to get Ubuntu on my chromebox.

Iv been typing in to the terminal:    sudo sh ~/Downloads/crouton -t xfce

Im returned with this prompt: 

 
Downloading latest crouton installer...
######################################################################## 100.0%
Installing precise-amd64 chroot to /usr/local/chroots/precise
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2015-01-08 01:03:52 URL:http://ftp.debian.org/debian/pool/main/d/debootstrap/ [5357/5357] -> "-" [1]
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.

Any ideas to move me forward would be wonderful!!

**Comment by dnschneid** [comment]
Are you behind a proxy?

**Comment by zoneco** [comment]
I am not behind a proxy, and my internet speed is around 70mbps.  Any ideas?

**Comment by drinkcat** [comment]
Can you access http://anonscm.debian.org/gitweb/ and http://ftp.debian.org/debian/pool/main/d/debootstrap/ from Chrome?

Can you post the output of `cat /etc/lsb-release`?

**Comment by zoneco** [comment]
I could not access a  http://anonscm.debian.org/gitweb/  I got a webpage not available.   I could access http://ftp.debian.org/debian/pool/main/d/debootstrap/ .    Output for cat /ect/lsb-release

CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C0E4276B-35C7-023D-BB4A-42D642B91E65}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C0E4276B-35C7-023D-BB4A-42D642B91E65}
CHROMEOS_RELEASE_BOARD=panther-signed-mpkeys
CHROMEOS_RELEASE_DESCRIPTION=6310.48.0 (Official Build) stable-channel panther 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6310.48.0
GOOGLE_RELEASE=6310.48.0

**Comment by dnschneid** [comment]
Hopefully it works by now...
