### ISSUE TITLE
No Volume Control or Audio Output in Debian/wheezy-lxde desktop.

### ISSUE THREAD

**Issue by LinuxJunkie** [dnschneid/crouton#1328]
Hello. I have recently installed Debian Wheezy using the following command, "sudo sh -e ~/Downloads/crouton -r wheezy -t lxde", and I have no volume control on my panel. I right clicked on the panel as well, and I tried to add the volume control feature under the add and remove items option, but it would not allow me to add it. I also went ahead and tested the music player that does have the volume control feature, and I still did not hear any audio coming from my speakers. Does anyone have a solution for this problem?

**Comment by Asuza** [comment]
I'm having a similar issue. I can't add the volume control panel, nor can I open "Alsamixergui" from the menu. If I try to launch "alsamixergui", it says:
```
Segmentation fault.
```
I can hear sound effects in Minecraft, and if I type `aplay -v /usr/share/sounds/alsa/Front_Center.wav`, I can hear "Front ce" from the speakers. However, Youtube has no audio and Hammerwatch says it can't initialize OpenAL. If I try to play FTL, I hear no sound at all.

I can adjust the volume via `alsamixer` and it does affect the loudness of the Front_Center sound file.

**Comment by Asuza** [comment]
@LinuxJunkie, most, if not all of my issues went away after installing `pulseaudio` (and rebooting). The volume doesn't behave entirely as I'd like, but at least it's working. It seems that the volume in Debian needs to be at 100%, then I can switch back to ChromeOS to turn it up and down.

I guess you could also turn ChromeOS volume to 100% then adjust it in Debian... I haven't tried that yet, though.

**Comment by Alfriadox** [comment]
Is this fixed with Cras now?

**Comment by dnschneid** [comment]
Try updating your chroot and using the `volume` command to adjust audio.  Installing pulseaudio may also help with some software that doesn't support alsa.
