### ISSUE TITLE
Kali Linux - Gnome Root Terminal Problem.

### ISSUE THREAD

**Issue by LinuxJunkie** [dnschneid/crouton#1329]
I have noticed in the gnome desktop that I need a root password to use the terminal. I had tried to use the password that I created when installing the chroot environment to my computer, but it did not work. I also tried to use the passwords "user", "toor", and "root". Nothing seemed to work. I even tried to install konsole from outside the environment through the enter-chroot command, and up on completion there was no konsole terminal under any sub-menus of the menu. Can anyone help me with this?

**Comment by divx118** [comment]
Yep, known problem. Issue is tracked here https://github.com/dnschneid/crouton/issues/1266 see second post for update on Kali.
You could try if lxterminal works for you. Use `sudo enter-chroot -n kali` If your chroot is named differently then replace "kali" with whatever your chroot is named.
Then to install lxterminal `sudo apt-get install lxterminal`.

**Comment by BharatAdhana** [comment]
Here Is the solution for this Problem 100% working

https://bharatadhana.blogspot.in/2016/08/kali-terminal-not-working-after.html

**Comment by TechnicalWorld001** [comment]
non of these solution worked for me
