### ISSUE TITLE
Starting Crouton in a tab

### ISSUE THREAD

**Issue by austinkregel** [dnschneid/crouton#1330]
Hey there guys, I have a brand new trusty chroot with xiwi and I didn't bother to install x11 or xorg when setting up the chroot. I try to start unity and it doesn't populate inside a tab. I was wondering if there was a special setting that I am suppose to have for crouton in a tab to work. If not what might I be doing wrong?

**Comment by LinuxJunkie** [comment]
To enter the chroot you will need to use the command, "sudo enter-chroot". That will allow you to work outside of the desktop environment. To enter the Desktop environment to have a GUI you will need to use the command, "sudo startunity". I hope that helps you.

**Comment by austinkregel** [comment]
Using `sudo startunity` from within the chroot will not work.

    Do not launch gnome-session-wrapper as root inside the chroot.

As an experiment I tried `startunity`, by itself, and that launches unity from a window with no problem. If anyone does have an issue I found this command `sudo enter-chroot -n trusty exec env XMETHOD=xiwi startunity` and then to go back to xorg there is this command `sudo enter-chroot -n trusty exec env XMETHOD=xorg startunity`

So to reiterate, I had to do `sudo enter-chroot` then I did `startunity`  from within the chroot.

**Comment by LinuxJunkie** [comment]
I apologize to you. I misunderstood the question. I had done a little research about this now though, and I have noticed that there is an extension that can be added to a persons chromebook to assist with the integration. The link for that is posted below:

https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom

I also have noticed that the x11 extension is needed if I am understanding this correctly. Here is an article posted below as well about running Ubuntu in a tab if you would like to read it. I hope this helps you out more.

http://liliputing.com/2014/12/crouton-chromebooks-run-ubuntu-browser-tab.html

**Comment by firestar115** [comment]
You have to specify `-t xiwi,unity` in that order.
