### ISSUE TITLE
Fails to unmount SD card (when running xfce4 and resuming the machine)?

### ISSUE THREAD

**Issue by monaka** [dnschneid/crouton#1332]
Reproduction (on my DELL Chromebook 11):
1. Insert SD card in your Chromebook.
2. Run startxfce4.
3. Close the lid of your Chromebook (to sleep)
4. Reopen it (to resume)
5. ChromeOS blames "SD card is removed without unmount."

I didn't get this issue when running enter-chroot.

**Comment by dnschneid** [comment]
See #288...
