### ISSUE TITLE
OpenGL in LWJGL unable to launch in xiwi window

### ISSUE THREAD

**Issue by TsundereBug** [dnschneid/crouton#1334]
When in an `xiwi` window, my program is not able to launch because there is no screen available:

``` java
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.otabi.firestar.portal.main.Portal.main(Portal.java:21)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at org.lwjgl.opengl.XRandR.findPrimary(XRandR.java:326)
    at org.lwjgl.opengl.XRandR.ScreentoDisplayMode(XRandR.java:315)
    at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
    at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
    at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
    ... 1 more
```

Which basically means this:

``` java
private static Screen findPrimary(Screen... screens) {
        for ( Screen screen : screens ) {
            if ( screen.name.equals(primaryScreenIdentifier) ) {
                return screen;
            }
        }
        // fallback
        return screens[0];
    }
```

And since `screens[0]` references the first screen, and it gives an `ArrayIndexOutOfBoundsException` that means that it is not there.
I know what you're thinking:
**"Oh... More work on that?"**
Find my code here: [firestar115/PortaJ](https://github.com/firestar115/PortaJ)

**Comment by dnschneid** [comment]
The xrandr code in the dummy driver isn't a complete implementation, iirc.

**Comment by firestar115** [comment]
I don't know what xrandr is or what iirc is...
I do java.

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by drinkcat** [comment]
In your code, I see `Display.setDisplayMode(new DisplayMode(800, 600));`. Are you trying to change resolution? That's probably a bad idea in `xiwi` context (we do not handle that). Can you start your application in a window?

I'm not sure why no screens are detected, though, as I see one in `xrandr` output. The only thing I can think about is that LWJGL might be using an older version of the xrandr protocol...

**Comment by firestar115** [comment]
`Display.setDisplayMode(DisplayMode mode)` sets the window size, not
linux's size.

On 1/15/15, drinkcat <notifications@github.com> wrote:
> In your code, I see `Display.setDisplayMode(new DisplayMode(800, 600));`.
> Are you trying to change resolution? That's probably a bad idea in `xiwi`
> context (we do not handle that). Can you start your application in a
> window?
>
> I'm not sure why no screens are detected, though, as I see one in `xrandr`
> output. The only thing I can think about is that LWJGL might be using an
> older version of the xrandr protocol...
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1334#issuecomment-70056683


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by drinkcat** [comment]
Could you look into LWJGL source (or file an issue on their github repo) to understand why it is trying to access screen information through xrandr? I don't see the point of doing that in windowed mode...

**Comment by TsundereBug** [comment]
Sorry I haven't been here in a while. I have heard this has been fixed and seen evidence that it has been fixed. Thanks for the interest though!

And oh boy my internet signature back then.
