### ISSUE TITLE
Corrupt packages -- couldn't download

### ISSUE THREAD

**Issue by tahirlanre** [dnschneid/crouton#1335]
I am trying to download crouton but it is failing due to error downloading binary-amd packages. The output is below 

chronos@localhost / $ sudo sh ~/Downloads/crouton -t unity
Downloading latest crouton installer...
######################################################################## 100.0%
Installing precise-amd64 chroot to /usr/local/chroots/precise
Downloading latest debootstrap...
2015-01-11 04:12:51 URL:http://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [61112/61112] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving Release 
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2
W: http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.bz2 was corrupt
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
I: Retrieving Packages 
I: Validating Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz
W: http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages.gz was corrupt
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages
W: http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/Packages was corrupt
E: Couldn't download dists/precise/main/binary-amd64/Packages

When I try to wget the package, i get the following output 

chronos@localhost / $: wget http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages
--2015-01-11 04:41:34--  http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages
Resolving archive.ubuntu.com... 91.189.88.149, 91.189.91.13, 91.189.91.15, ...
Connecting to archive.ubuntu.com|91.189.88.149|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-01-11 04:41:35 ERROR 404: Not Found.

**Comment by BiTinerary** [comment]
Meh, worked like a dream for me. Wish I has a solution for you but I don't. I can recommend StackOverflow.com though. Good luck

**Comment by tahirlanre** [comment]
I am gonna try it again. Thanks

**Comment by dnschneid** [comment]
You can also try a different mirror using -m.
