### ISSUE TITLE
Enhancements - free Chrome memory and virtual high resolutions

### ISSUE THREAD

**Issue by w-barath** [dnschneid/crouton#1336]
I'd like to share some enhancements I have been using for some time which work well and make my crouton / Ubuntu Trusty (xfce4 i386) experience much more productive.

There's two serious drawbacks to my C720-2420 vs other laptops I use:

1) very little RAM (2GB)
2) usable but low resolution (1366x768)

Here's my solutions to these two problems:

1) Lots of RAM is being used by Chrome.  About 600MB across 7 major instances plus a dozen minor instances.

I wrote a script which sleeps all chrome processes, then kills all but the topmost one (kill that and your chroot dies too!), then forces the new instances (which ChromeOS immediately spawns) to sleep before they load any significant resources.

```bash
#!/bin/bash
#
# mdk - murder death kill (to chrome)  ;-)
#

# make them sleep
killall -STOP chrome

# murder them in their sleep
pstree -p | grep chrome \
  | sed -e '/.*|.*|/!d' \
        -e "s/.*(//" \
        -e "s/[^0-9].*$//" \
  | xargs kill -s KILL; 

# prevent them from respawning
for (( i=0; i<200; i++ )) do killall -STOP chrome; done
```

A simple example of how effective 'mdk' is:

```
(trusty)sid@localhost:~$ free
             total       used       free     shared    buffers     cached
Mem:       1923092    1906816      16276     140332      32752     684600
-/+ buffers/cache:    1189464     733628
Swap:      2817028          0    2817028
(trusty)sid@localhost:~$ mdk
(trusty)sid@localhost:~$ free
             total       used       free     shared    buffers     cached
Mem:       1923092    1232928     690164      66220      32876     608952
-/+ buffers/cache:     591100    1331992
Swap:      2817028          0    2817028
```

That basically evicts everything other than X and various usability daemons, which is similar to having ldm, pulse, consolekit, network-manager etc hanging around, and provides free memory / performance which is ( at least IMHO) equivalent to a native Ubuntu install.

2) Low resolution.  I want to open Netbeans at the right and Firefox at the left, and 4 shells plus skype on the next virtual desktop. Configuring a fake low DPI was my first attempt.  I still had to CTRL-- in Firefox to shrink pages enough and that resulted in broken layouts a lot of the time.  Also this didn't scale down the browser chrome or any of the application toolbars/titlebars etc, so although I got more space I felt ripped off a lot of the time.  So I used xrandr scaling to provide virtual desktops with no panning.  :-)

add this to the end of your ~/.bash_aliases

```bash
res(){
echo 1536 1383 1280 1152 1080 1024 960 900 768 720
}
1536p(){
xrandr --output eDP1 --scale 2x2 --fb 2732x1536 --panning 2732x1536
}
1383p(){
xrandr --output eDP1 --scale 1.8x1.8 --fb 2459x1383 --panning 2459x1383
}
1280p(){
xrandr --output eDP1 --scale 1.667x1.666 --fb 2278x1280 --panning 2278x1280
}
1152p(){
xrandr --output eDP1 --scale 1.5x1.5 --fb 2049x1152 --panning 2049x1152
}
1080p(){
xrandr --output eDP1 --scale 1.405x1.406 --fb 1920x1080 --panning 1920x1080
}
1024p(){
xrandr --output eDP1 --scale 1.333x1.333 --fb 1821x1024 --panning 1821x1024
}
960p(){
xrandr --output eDP1 --scale 1.25x1.25 --fb 1708x960 --panning 1708x960
}
900p(){
xrandr --output eDP1 --scale 1.171x1.171 --fb 1600x900 --panning 1600x900
}
768p(){
xrandr --output eDP1 --scale 1x1 --fb 1366x768 --panning 1366x768
}
720p(){
xrandr --output eDP1 --scale 0.937x0.937 --fb 1280x720 --panning 0x0
}
```

Then close your terminal and open a new one, then try entering '960p' for a nice high resolution display, and use 'res' to remind yourself of the available resolutions.  

This is brilliant for working with apps like inkscape that require a larger desktop.  In particular, firefox with the developer tools open, inkscape, and remmina (you can access machines in their 'native' resolution with hardware scaling which is both lower CPU usage and higher visual quality.)

720p is there for youtube fullscreen and some games like Trine which run at 720p in 'fullscreen', leaving black borders.  With a 720p display the game is properly fullscreen. 

Enjoy!

P.S. - Darn, I missed 1337 by one LOL

**Comment by dnschneid** [comment]
Sweet tips.  If you're interested, it might be nice to extend the `setres` script with the ability to scale the display.

**Comment by idpnd** [comment]
Doesn't improve mem situation for me.. I launched this is entered chroot on chrome, is that correct approach? Many thanks
