### ISSUE TITLE
failure to install cinnamon - please delete*

### ISSUE THREAD

**Issue by daviday** [dnschneid/crouton#1337]
I'm back and forth on the mint and crouton page and can't keep track but am I missing something here. While this is an older build command it's kicking back invalid.

open shell: sudo sh -e ~/Downloads/crouton -r saucy -t cinnamon 

returns this: 
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Downloading latest crouton installer...
######################################################################## 100.0%
Invalid target "cinnamon".

KDE and XFCE install fine, apologies if I'm behind the curve. Caught on other issues with where I don't know to start.

edit::: quick list request showed working distros ****

**Comment by DennisLfromGA** [comment]
Check out these two issues:

- remove cinnamon target #832
<https://github.com/dnschneid/crouton/pull/832>
- Bringing back the Cinnamon Target? #1000
<https://github.com/dnschneid/crouton/issues/1000>

On Sun, Jan 11, 2015 at 11:59 AM, daviday <notifications@github.com> wrote:

> I'm back and forth on the mint and crouton page and can't keep track but
> am I missing something here. While this is an older build command it's
> kicking back invalid.
>
> open shell: sudo sh -e ~/Downloads/crouton -r saucy -t cinnamon
>
> returns this:
> We trust you have received the usual lecture from the local System
> Administrator. It usually boils down to these three things:
>
> #1) Respect the privacy of others.
> #2) Think before you type.
> #3) With great power comes great responsibility.
>
> Downloading latest crouton installer...
> ########################################################################
> 100.0%
> Invalid target "cinnamon".
>
> KDE and XFCE install fine, apologies if I'm behind the curve. Caught on
> other issues with where I don't know to start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1337>.
>



-- 
*DennyL@GMail*
