### ISSUE TITLE
Trouble getting [`¬] and [#~] keys working in xiwi based session on UK Pixel

### ISSUE THREAD

**Issue by stsquad** [dnschneid/crouton#1338]
I've tried all the various variants of gb layout and they all end up with [`¬] (top left) not generating anything and [~#] (next to @ and enter) only generates | and \.

    crouton: version git
    release: jessie
    architecture: amd64
    targets: xiwi,keyboard,cli-extra
    host: version 6310.68.0 (Official Build) stable-channel link

I've tried comparing with host-x11 setxkbmap with reports:

    rules:      evdev
    model:      pc
    layout:     gb(extd) 

Where as in my xiwi session I get:

    rules:      evdev
    model:      pc
    layout:     gb
    variant:    extd

Any ideas?

**Comment by stsquad** [comment]
Somehow I knocked out xiwi while testing without the keyboard target to find the key works fine on the normal X session. Once I'd restored xiwi,keyboard the behaviour was broken again.

**Comment by divx118** [comment]
There are indeed some keyboard issues with xiwi. see https://github.com/dnschneid/crouton/issues/1275
