### ISSUE TITLE
[Request] Linux notifications to ChromeOS

### ISSUE THREAD

**Issue by jorisvandijk** [dnschneid/crouton#1341]
This is the only thing I am seriously missing when using this extension. It'd be awesome if Crouton could see the notifications that pop up in Linux and push them to the notification system of ChromeOS. It might be beyond the scope of this extension, but it would be an incredible feature, which would make this extension perfect in my opinion. Also apologies if this isn't the place to post this, I didn't know where else to ask.

**Comment by drinkcat** [comment]
Yes, see #581. But I think what you suggest goes a bit further, so that "standard" X11 notifications are shown (I'm not sure what is actually standard, it looks like `libnotify` is commonly used).
