### ISSUE TITLE
Left and Down arrows don't auto-repeat in xiwi session. Up and Right do.

### ISSUE THREAD

**Issue by stsquad** [dnschneid/crouton#1344]
This is slightly weird but I've found scrolling down in my editor is very annoying as I have to keep tapping the key. However all the arrow keys auto-repeat when I use them within a crosh terminal.

    crouton: version git
    release: jessie
    architecture: amd64
    targets: xiwi,keyboard,cli-extra
    host: version 6310.68.0 (Official Build) stable-channel link

**Comment by drinkcat** [comment]
Confirmed, same problem here.

**Comment by drinkcat** [comment]
"Fix":
```
xset r 113
xset r 116
```

Need to dig a bit further to understand what is going on. I suspect it's because the keyboard starts in pc105 layout, and then is switched to evdev, breaking autorepeat settings in the process (see `xset q`, not all keys are on autorepeat)...
