### ISSUE TITLE
gnutls / github

### ISSUE THREAD

**Issue by Pobux** [dnschneid/crouton#1346]
I've been looking around to find a solution and I don't know if it's Crouton based, github base or my apache2 server. I'm taking a chance.

When trying to connect to github I have the following error : 
error: gnutls_handshake() failed: Error in the push function.

Is there some kind of OpenSSL / GnuTLS conflict?

----
git push -u origin master
error: gnutls_handshake() failed: Error in the push function. while accessing https://gitub.com/bleh/bleh.git/info/refs
fatal: HTTP request failed

**Comment by drinkcat** [comment]
Are you behind a proxy? (e.g. http://askubuntu.com/questions/186847/error-gnutls-handshake-falied-when-connecting-to-https-servers).

In any case, I doubt that this problem is directly related to crouton...
