### ISSUE TITLE
"sudo startunity" the chroot update dosen't work

### ISSUE THREAD

**Issue by daallgeier** [dnschneid/crouton#1348]
Hi, I just updated my ubuntu to 14.04. I think I made a little mistake at the work through.

This is the massage I get with "sudo startunity":

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Unknown username "whoopsie" in message bus configuration file

Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
[dix] Could not init font path element /usr/share/fonts/X11/misc, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down 
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

After that, I tried to run an update:

chronos@localhost / $ sudo sh ~/Downloads/crouton -n precise -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
unity target does not work in xephyr in trusty due to missing egl support.

And this is the log for the croutonversion

chronos@localhost / $ sudo enter-chroot -n precise croutonversion
Entering /mnt/stateful_partition/crouton/chroots/precise...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
However, it appears the setup script is invalid.
Removing the chroot setup script. You may want to update your chroot again.
Unknown username "whoopsie" in message bus configuration file
crouton: version 1-20141226162305~master:21db8947
release: precise
architecture: armhf
targets: unity
host: version 6457.68.0 (Official Build) beta-channel nyan_big 
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

what can I do to get around that problem?

**Comment by dnschneid** [comment]
Yeah, upgrading was a mistake if you want to keep using Unity.  Either make a new precise chroot if you want to go back to unity, or do the following to switch to another DE (such as xfce):

`sudo enter-chroot -u root sed -i 's/unity/xfce/' /etc/crouton/targets`
`sudo sh ~/Downloads/crouton -n precise -u`
