### ISSUE TITLE
Does Unity work in xiwi?

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1351]
Trusty Unity doesn't work in Xephyr due to missing EGL.  Does it work in xiwi?  If so, we may be able to change the Unity target on ARM to require xiwi instead of failing outright, and then potentially change the default release to trusty.

**Comment by dnschneid** [comment]
The answer is, unfortunately, [no, not yet](https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1251281).

**Comment by smibarber** [comment]
The answer appears to be yes now even without the proposed package, with the caveat that the screen is black at start. Exiting fullscreen redraws and then all is well.

**Comment by mark-hahn** [comment]
It works for me except the keyboard overlay doesn't work.  So I don't have
Home, End, etc.  Let me know if the keyboard works for you.

**Comment by dnschneid** [comment]
gnome fallback as well?

**Comment by smibarber** [comment]
gnome works with the same issue (black at startup). Home and end shortcuts from cros don't seem to work, @mark-hahn. alt-up and alt-down, correct?

**Comment by mark-hahn** [comment]
Home/end are supposed to be search-left and search-right, just as it is in
the rest of the chromebook.  The docs at
https://github.com/dnschneid/crouton/wiki/Keyboard say ..

"All Search+key bindings are supported, with the difference that the top
row (function keys) maps to F1->F10 by default. Search+function keys map to
actual functions (navigation, brightness, volume, etc.)".

"The other bindings (Ctrl+key, Alt+key, ...) are not supported, and will
probably never be, as they may interfere with useful key combinations in
some Linux applications".

Note the "All Search+key bindings are supported".

Anyway, please let me know if shift-left, shift-right, and shift-backspace
give you home, end, and delete.  Or actually if you can get them to work
with any key combination.

Thanks in advance.

**Comment by smibarber** [comment]
Ah whoops, I should've double checked those. I'm used to gg and G as home and end.

Anyway, none of those combination seems to work.

**Comment by mark-hahn** [comment]
> Anyway, none of those combination seems to work.

So you don't have any way to do home/end/delete?  This is a serious problem
for me.  I am trying to use a programming editor and those keys are
needed.  The weird part is that I've been asking this question for a week
and I couldn't get any answers.  It must be some dirty secret. (grin)

Anyway, I guess I'll have to learn how the keyboard layers work in X11.
That should be fun (not).

**Comment by vladimirvivien** [comment]
Unity works for me with xiwi, but only at the lower resolution.  When I hit HiDPI checkbox in crouton chrome extension, the screen rendering gets slow and unstable.  Is there a way (or which script in /etc/croutons to change) to avoid defaulting to the highest res when "hiDPI" is selected ?

**Comment by dnschneid** [comment]
Looks like the linked bug has been [fixed in trusty](https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1251281/comments/77).  Someone should try it and report back.

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
