### ISSUE TITLE
OpenGL on ARM Chromebooks  ?

### ISSUE THREAD

**Issue by jman6495** [dnschneid/crouton#1352]
Hey,

Sorry to be vague in my question title, basicly I need some clarification.
I understand that when using Xephyr (Which is what we use on ARM chromebooks); there can be no acceleration.

Say I get the lib's (libgl etc ...) bundled with the driver.
My questions are as follows : 
* If it were possible to run a second X Session, would that session be 3d accelerated ?
* If that is not possible, would it be possible to use a console (tty) to kill the main X server, then chroot and launch a replacement ?
* Could that have 3d acceleration ?

I really appreciate the efforts of the developers who put this together, currently my XFCE chroot is brilliant, but deep down I yearn for Gnome Shell ;)

Thanks to anyone who can respond :)

**Comment by lovedheart** [comment]
Which ARM chromebook do you use? It's shown that the Acer Tegra K1 don't support second X Session with hardware acceleration. However xorg can be installed rather than Xephyr. It shows a better graphic performance. I'd like to close main X server and start one for chroot.

**Comment by jman6495** [comment]
I've got the HP Chromebook 11 (daisy spring)
I was just curious as to if it was possible. so far i haven't worked out how to keep Xorg from restarting automatically on chromeos .. working on it :)

**Comment by dnschneid** [comment]
That would be #964.  Separate X11 is not an option yet.
