### ISSUE TITLE
Mouse Frozen When Switching Back to ChromeOS

### ISSUE THREAD

**Issue by hiswitness** [dnschneid/crouton#1354]
I have had a great time running Ubuntu Trusty on my Acer C7 with a couple of different chroots with Unity and Gnome desktop environments... but then after awhile (and some updates probably) for some reason my mouse started freezing whenever I would Shift-Ctrl-Alt-F2 swith back to ChromeOS. It's totaly stuck... and this is what I see in the the shell window....

<code>
Loading extension GLX<br />  
Error: target STRING not available<br />  
(II) AIGLX: Suspending AIGLX clients for VT switch<br />    
[dix] couldn't enable device 12 <br />   
</code>

Every time I switch back I see the same message printed again...

<code>
(II) AIGLX: Suspending AIGLX clients for VT switch<br />    
[dix] couldn't enable device 12 <br />   
</code>

Thanks!

**Comment by hiswitness** [comment]
oops! Just realized that's only happening when I use the USB mouse ...

But it was happening occasionally before without the USB mouse when I was running Unity on a different Trusty chroot...

**Comment by dnschneid** [comment]
X11 doesn't seem to be handing off the device properly.  Assuming you're still having the issue, could you post the output of `croutonversion`?

**Comment by hiswitness** [comment]
Thanks for checking in... I don't seem to be having too much of a problem with this anymore... it happened earlier after I updated my chroot I think... this re-install I have been afraid to do so. I do get occasional messages like 

(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available

and the trackpad tends to get jammed/messed up when I plug in a USB mouse

right now here is my output for croutonversion

(j)adam@localhost:~$ croutonversion
crouton: version 1-20150127081428~master:e1bcac2b
release: trusty
architecture: amd64
targets: core,gnome-desktop,extension,chrome,xorg,xephyr
host: version 6457.94.0 (Official Build) stable-channel parrot

**Comment by DennisLfromGA** [comment]
@hiswitness -
That's a fairly old version of crouton, there's been 15 updates since then and it's just 27 days old. ;)
If it were me, I would back up my chroot and then download a fresh installer and do a crouton update.

**Comment by yellow08** [comment]
I got this problem, too. When I change the system from Ubuntu Unitify back to Chrome OS, it prints: [dir] couldn't enable device 12. And the result is my touchpad can not work. My notebook is Toshiba CB2. The crouton version is 20150620.

Thanks!

**Comment by avernan** [comment]
Same problem here, on Toshiba CB2, too. It doesn't happen all the times, but seems somehow related to the time since the chroot start.

>(trusty)sg2514@localhost:~$ croutonversion 
>crouton: version 1-20150811114815~master:f6b810fe
>release: trusty
>architecture: amd64
>xmethod: xorg
>targets: chrome,keyboard,cli-extra,gnome,extension,xbmc
>host: version 7077.111.0 (Official Build) stable-channel swanky 
>kernel: Linux localhost 3.10.18 #1 SMP Tue Jul 28 16:15:02 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
>freon: yes

**Comment by dougfelt** [comment]
I have this only occasionally, using both precise and trusty.  When I'm in the chroot the mouse is ok, but when I switch to Chrome OS the mouse position is frozen.  Two-finger scrolling sometimes works (shows title when in fullscreen mode).  Very occasionally the mouse pointer will jump.  When I return to the chroot the mouse is fine again.  This is on an acer c720

$ croutonversion
crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,cli-extra,core,extension,keyboard,xfce
host: version 7390.68.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Nov 5 10:53:38 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
