### ISSUE TITLE
'shares' file usage

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1355]
Since ```/etc/crouton/shares``` has recently been implemented, could an explanation of it's use be added to the [README](https://github.com/dnschneid/crouton/blob/master/README.md) so those interested can take advantage?

Maybe something short and concise like the examples in the ```enter-chroot``` file might be enough(???)
```
# Examples:
#  Share a home directory encrypted by the current user's unsynced profile
#   encrypted/home ~
#  Share an unencrypted directory between chroots.
#   shared/home ~/Share
#  Absolute directories on the chroot side work too
#   shared/bin /usr/local/bin exec,suid
#  Share a noexec path that has spaces, and a specific user home directory
#   "encrypted/stupid example" "~omg/Why are you even doing this?" noexec
```

**Comment by DennisLfromGA** [comment]
As an afterthought, maybe just make a small reference to setting up shares in the [README](https://github.com/dnschneid/crouton/blob/master/README.md) and link it to a wiki page that does a more complete job of explaining what they are, where they can be used, etc., and list some examples.

**Comment by dnschneid** [comment]
Sure, an entry in the tips section pointing to the /etc/crouton/shares file would be reasonable.
