### ISSUE TITLE
Error when launching minecraft in Xorg.

### ISSUE THREAD

**Issue by gjgfuj** [dnschneid/crouton#1357]
When I try to launch minecraft under the Xorg display, I get this error:

/usr/bin/java: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_get_reply_fds

I do not get this under xiwi, and instead it launches fine.

I would like to ask how I could fix this, keeping both xiwi and xorg available within the same chroot.

EDIT:
My croutonversion is:
crouton: version 1-20150119115413~master:d11daa2b
release: utopic
architecture: amd64
targets: xiwi,xorg,xfce
host: version 6310.68.0 (Official Build) stable-channel leon

**Comment by drinkcat** [comment]
Are you using MultiMC? See https://github.com/MultiMC/MultiMC5/issues/576.

**Comment by gjgfuj** [comment]
Yep, that's MultiMC's issue and has nothing to do with crouton. Sorry for bothering you.

**Comment by drinkcat** [comment]
No worries.
