### ISSUE TITLE
Transfer of crouton install between computers

### ISSUE THREAD

**Issue by raj-kesavan** [dnschneid/crouton#1358]
I have a Chromebook running Crouton (Ubuntu trusty) with various installed packages and configs. Can I transfer this to another Chromebook?

**Comment by dnschneid** [comment]
Certainly.  Look into the `edit-chroot` command, specifically the -b option.  You can use it to back up your chroot to external media.  You can then use the -f option in the crouton installer to install the generated tarball onto the new system.
