### ISSUE TITLE
Ubuntu not starting after crouton update

### ISSUE THREAD

**Issue by telebuss** [dnschneid/crouton#1360]
Hi, I tried to update my chroot unsuccessfully today. Now Ubuntu won't start and I can't access my data, which I need kinda urgently. Here's what I did:

chronos@localhost / $ sudo sh -e ~/Downloads/crouton -n trusty -u
/usr/local/chroots/trusty already exists; updating it...
Enter encryption passphrase for trusty: 
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startunity into the host...
Installing crouton-noroot into the chroot...
Installing startunity into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing crouton-unity-autostart into the chroot...
Installing unity-autostart.desktop into the chroot...
Installing unity-profiled into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://archive.canonical.com trusty InRelease
Ign http://ppa.launchpad.net trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease 
Ign http://dl.google.com stable InRelease      
Hit http://archive.canonical.com trusty Release.gpg
Ign http://ppa.launchpad.net trusty InRelease
Hit http://dl.google.com stable Release.gpg
Ign http://archive.ubuntu.com trusty-updates InRelease
Hit http://archive.canonical.com trusty Release
Ign http://archive.ubuntu.com trusty-security InRelease              
Ign http://ppa.launchpad.net trusty Release.gpg                      
Hit http://dl.google.com stable Release                              
Ign http://archive.ubuntu.com trusty-proposed InRelease              
Hit http://archive.ubuntu.com trusty Release.gpg                               
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://archive.canonical.com trusty/partner Sources                        
Hit http://archive.ubuntu.com trusty-updates Release.gpg             
Ign http://ppa.launchpad.net trusty Release                          
Hit http://dl.google.com stable/main amd64 Packages                  
Hit http://archive.ubuntu.com trusty-security Release.gpg                      
Hit http://archive.canonical.com trusty/partner amd64 Packages                 
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://dl.google.com stable/main i386 Packages                             
Hit http://archive.ubuntu.com trusty-proposed Release.gpg                      
Hit http://archive.canonical.com trusty/partner i386 Packages                  
Hit http://archive.ubuntu.com trusty Release                                   
Hit http://archive.canonical.com trusty/partner Translation-en                 
Hit http://archive.ubuntu.com trusty-updates Release                           
Hit http://archive.ubuntu.com trusty-security Release                          
Hit http://archive.ubuntu.com trusty-proposed Release                          
Hit http://ppa.launchpad.net trusty/main Sources                               
Hit http://archive.ubuntu.com trusty/main Sources                              
Ign http://dl.google.com stable/main Translation-en                            
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://archive.ubuntu.com trusty/restricted Sources           
Hit http://ppa.launchpad.net trusty/main i386 Packages            
Hit http://archive.ubuntu.com trusty/universe Sources             
Hit http://archive.ubuntu.com trusty/multiverse Sources           
Hit http://archive.ubuntu.com trusty/main amd64 Packages          
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages    
Hit http://archive.ubuntu.com trusty/universe amd64 Packages      
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages    
Hit http://archive.ubuntu.com trusty/main i386 Packages           
Hit http://archive.ubuntu.com trusty/restricted i386 Packages     
Hit http://archive.ubuntu.com trusty/universe i386 Packages       
Hit http://archive.ubuntu.com trusty/multiverse i386 Packages     
Hit http://archive.ubuntu.com trusty/main Translation-en          
Hit http://archive.ubuntu.com trusty/multiverse Translation-en    
Hit http://archive.ubuntu.com trusty/restricted Translation-en    
Hit http://archive.ubuntu.com trusty/universe Translation-en      
Hit http://archive.ubuntu.com trusty-updates/main Sources         
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://archive.ubuntu.com trusty-updates/universe Sources     
Err http://ppa.launchpad.net trusty/main Sources                  
  404  Not Found
Hit http://archive.ubuntu.com trusty-updates/multiverse Sources   
Err http://ppa.launchpad.net trusty/main amd64 Packages           
  404  Not Found
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages  
Err http://ppa.launchpad.net trusty/main i386 Packages            
  404  Not Found
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Ign http://ppa.launchpad.net trusty/main Translation-en           
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Ign http://ppa.launchpad.net trusty/main Translation-en           
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://archive.ubuntu.com trusty-updates/main Translation-en
Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://archive.ubuntu.com trusty-security/main Sources
Hit http://archive.ubuntu.com trusty-security/restricted Sources
Hit http://archive.ubuntu.com trusty-security/universe Sources
Hit http://archive.ubuntu.com trusty-security/multiverse Sources
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-security/main i386 Packages
Hit http://archive.ubuntu.com trusty-security/restricted i386 Packages
Hit http://archive.ubuntu.com trusty-security/universe i386 Packages
Hit http://archive.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://archive.ubuntu.com trusty-security/main Translation-en
Hit http://archive.ubuntu.com trusty-security/multiverse Translation-en
Hit http://archive.ubuntu.com trusty-security/restricted Translation-en
Hit http://archive.ubuntu.com trusty-security/universe Translation-en
Hit http://archive.ubuntu.com trusty-proposed/main amd64 Packages
Hit http://archive.ubuntu.com trusty-proposed/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-proposed/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-proposed/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-proposed/main i386 Packages
Hit http://archive.ubuntu.com trusty-proposed/universe i386 Packages
Hit http://archive.ubuntu.com trusty-proposed/restricted i386 Packages
Hit http://archive.ubuntu.com trusty-proposed/multiverse i386 Packages
Hit http://archive.ubuntu.com trusty-proposed/main Translation-en
Hit http://archive.ubuntu.com trusty-proposed/multiverse Translation-en
Hit http://archive.ubuntu.com trusty-proposed/restricted Translation-en
Hit http://archive.ubuntu.com trusty-proposed/universe Translation-en
W: Failed to fetch http://ppa.launchpad.net/cardapio-team/cardapio-ppa/ubuntu/dists/trusty/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/cardapio-team/cardapio-ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/cardapio-team/cardapio-ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

chronos@localhost / $ sudo edit-chroot -a
trusty
chronos@localhost / $ sudo enter-chroot -n trusty
Enter encryption passphrase for trusty: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://archive.canonical.com trusty InRelease
Ign http://ppa.launchpad.net trusty InRelease                                  
Ign http://dl.google.com stable InRelease                                      
Hit http://archive.canonical.com trusty Release.gpg                            
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://dl.google.com stable Release.gpg                                    
Hit http://archive.canonical.com trusty Release                                
Ign http://ppa.launchpad.net trusty Release.gpg                                
Hit http://dl.google.com stable Release                                        
Hit http://ppa.launchpad.net trusty Release.gpg                                
Ign http://ppa.launchpad.net trusty Release                          
Hit http://archive.canonical.com trusty/partner Sources                        
Hit http://ppa.launchpad.net trusty Release                                    
Ign http://archive.ubuntu.com trusty InRelease                                 
Hit http://archive.canonical.com trusty/partner amd64 Packages                 
Hit http://dl.google.com stable/main amd64 Packages                            
Hit http://archive.canonical.com trusty/partner i386 Packages                  
Hit http://dl.google.com stable/main i386 Packages                             
Hit http://archive.canonical.com trusty/partner Translation-en                 
Ign http://archive.ubuntu.com trusty-updates InRelease                         
Hit http://ppa.launchpad.net trusty/main Sources                      
Hit http://ppa.launchpad.net trusty/main amd64 Packages               
Hit http://ppa.launchpad.net trusty/main i386 Packages                
Ign http://dl.google.com stable/main Translation-en                   
Ign http://archive.ubuntu.com trusty-security InRelease               
Ign http://archive.ubuntu.com trusty-proposed InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty-updates Release.gpg
Err http://ppa.launchpad.net trusty/main Sources
  404  Not Found
Hit http://archive.ubuntu.com trusty-security Release.gpg
Err http://ppa.launchpad.net trusty/main amd64 Packages
  404  Not Found
Err http://ppa.launchpad.net trusty/main i386 Packages
  404  Not Found
Ign http://ppa.launchpad.net trusty/main Translation-en
Ign http://ppa.launchpad.net trusty/main Translation-en
Hit http://archive.ubuntu.com trusty-proposed Release.gpg
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty-updates Release
Hit http://archive.ubuntu.com trusty-security Release
Hit http://archive.ubuntu.com trusty-proposed Release
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/multiverse Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty/main i386 Packages
Hit http://archive.ubuntu.com trusty/restricted i386 Packages
Hit http://archive.ubuntu.com trusty/universe i386 Packages
Hit http://archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://archive.ubuntu.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/multiverse Translation-en
Hit http://archive.ubuntu.com trusty/restricted Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://archive.ubuntu.com trusty-updates/universe Sources
Hit http://archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse i386 Packages          
Hit http://archive.ubuntu.com trusty-updates/main Translation-en               
Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en         
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en         
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en           
Hit http://archive.ubuntu.com trusty-security/main Sources                     
Hit http://archive.ubuntu.com trusty-security/restricted Sources               
Hit http://archive.ubuntu.com trusty-security/universe Sources                 
Hit http://archive.ubuntu.com trusty-security/multiverse Sources               
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages              
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages        
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages          
Hit http://archive.ubuntu.com trusty-security/multiverse amd64 Packages        
Hit http://archive.ubuntu.com trusty-security/main i386 Packages               
Hit http://archive.ubuntu.com trusty-security/restricted i386 Packages         
Hit http://archive.ubuntu.com trusty-security/universe i386 Packages           
Hit http://archive.ubuntu.com trusty-security/multiverse i386 Packages         
Hit http://archive.ubuntu.com trusty-security/main Translation-en              
Hit http://archive.ubuntu.com trusty-security/multiverse Translation-en        
Hit http://archive.ubuntu.com trusty-security/restricted Translation-en        
Hit http://archive.ubuntu.com trusty-security/universe Translation-en          
Hit http://archive.ubuntu.com trusty-proposed/main amd64 Packages              
Hit http://archive.ubuntu.com trusty-proposed/universe amd64 Packages          
Hit http://archive.ubuntu.com trusty-proposed/restricted amd64 Packages        
Hit http://archive.ubuntu.com trusty-proposed/multiverse amd64 Packages        
Hit http://archive.ubuntu.com trusty-proposed/main i386 Packages               
Hit http://archive.ubuntu.com trusty-proposed/universe i386 Packages           
Hit http://archive.ubuntu.com trusty-proposed/restricted i386 Packages         
Hit http://archive.ubuntu.com trusty-proposed/multiverse i386 Packages         
Hit http://archive.ubuntu.com trusty-proposed/main Translation-en              
Hit http://archive.ubuntu.com trusty-proposed/multiverse Translation-en        
Hit http://archive.ubuntu.com trusty-proposed/restricted Translation-en        
Hit http://archive.ubuntu.com trusty-proposed/universe Translation-en          
W: Failed to fetch http://ppa.launchpad.net/cardapio-team/cardapio-ppa/ubuntu/dists/trusty/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/cardapio-team/cardapio-ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/cardapio-team/cardapio-ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.

Here's the crouton version 

chronos@localhost / $ sudo enter-chroot -n trusty
Enter encryption passphrase for trusty: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)hamperfait@localhost:~$ croutonversion
crouton: version 1-20150119115413~master:d11daa2b
release: trusty
architecture: amd64
targets: keyboard,unity
host: version 6680.1.0 (Official Build) dev-channel squawks 

I don't know what else do you need. Please let me know and I'll upload it as soon as possible.

Thank you really much in advance

**Comment by drinkcat** [comment]
Enter the chroot (`sudo enter-chroot -n trusty`, then press `n`), remove `cardapio-ppa` PPA and try updating again.

Then figure out if you really needed that PPA, or if there is a new URL...

**Comment by telebuss** [comment]
It worked! I was going crazy. Thank you very much for your fast help
