### ISSUE TITLE
Two KDE environments running?

### ISSUE THREAD

**Issue by connorjolley** [dnschneid/crouton#1361]
I'm not a competent Linux user - so bear with me.

I seem to have two KDE environments running. When I startkde from ChromeOS it loads into KDE fine. But I have Transmission running which says the active torrents are idle, everything else seems to be working fine. When I switch back to ChromeOS using ctrl+shift+alt+back it takes me to another KDE login for an environment that seems to already be running, Transmission is running and the torrents are downloading. When I do the command again to get back to ChromeOS it seems to end the session - i.e. I can't type commands in the crosh shell, I have to close the window and load it up again and go into shell. When I startkde the whole process just repeats itself.

I've tried the instructions in the Wiki before reporting the issue - i.e. downloading and running crouton again.

I've tried to force an unmount-chroot because I thought that might solve it after searching the site for things that sound similar to what I am experiencing.

Can anyone help?

I hope my explanation is clear enough - I'm not a Linux person.

**Comment by connorjolley** [comment]
![screenshot 2015-01-22 at 12 14 27 am](https://cloud.githubusercontent.com/assets/10630742/5836596/beef56b6-a1cb-11e4-8bbb-30a0265ea09e.png)

This is what crosh says immediately after exiting KDE - normally the 'suspending aiglx clients for vt switch' message is the last thing it says

**Comment by dnschneid** [comment]
I don't really understand the issue.  The crosh shell is running startkde, so you won't be able to type any commands into it.

**Comment by connorjolley** [comment]
I believe I had two chroots mounted concurrently, the issue resolved itself - apologies for the confusion

**Comment by dnschneid** [comment]
OK, awesome.
