### ISSUE TITLE
Problems installing? gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by robbie0630** [dnschneid/crouton#1363]
So, I was installing crouton, just like the guide said. Then suddenly, I was interrupted by an odd error. `gzip: stdin: not in gzip format`. Why is this happening?

**Comment by DennisLfromGA** [comment]
More details please, like - 

- crouton command line parameters used to install the chroot: sudo sh ~/Downloads/crouton ...
- output showing what happenned and any errors encountered, you can use [paste.bin](http://pastebin.com/) for this.
- anything else you might deem  pertinent.

**Comment by robbie0630** [comment]
I am extremely sorry. I am fairly good in Linux, considering myself an intermediate user, but I am very forgetful. Here is the [console output](http://pastebin.com/YQ5FzwJF). The command is `sudo sh ~/Downloads/crouton -r trusty -t lxde,xiwi`. If anything else is needed, let me know.

**Comment by drinkcat** [comment]
@robbie0630 :

> Location: http://swocawireless.swoca.net/swocablock/drestricted.html?fn=SC-Default&fp=321&ip=10.138.220.43&ibip=10.194.25.12&ldu=1&re=0&bu=xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz&bc=Website contains prohibited Forums content. [following]

It looks like xorg.freedesktop.org is blocked from your location (not sure why, I don't see any forums on that domain)... Can you retry from another location?

**Comment by robbie0630** [comment]
@drinkcat I could, but that would be another three hours from now. The only way I could bypass this would be Tor, but I need this to use Tor. I could just do cli-extra, but then I couldn't use Tor due to the need for a graphic interface. I could get a graphic interface, but I would need Tor. As long as I am stuck here, I'm stuck in a paradox. This place is a paradox.

**Comment by DennisLfromGA** [comment]
This has nothing to do with the error but the command specified '... -t lxde,xiwi...'.
It used to be a requirement that 'xiwi' be specified as the first target '... -t xiwi,lxde...' for 'crouton in a window' to work but maybe it's no longer necessary with https://github.com/dnschneid/crouton/commit/640db455a8b031569934c6e0d0c85c748a2744d3 getting merged - just wondering...

**Comment by robbie0630** [comment]
@DennisLfromGA No, my school is blocking [xorg.freedesktop.org](xorg.freedesktop.org). My school blocks almost EVERYTHING.

**Comment by dnschneid** [comment]
It's probably best to just wait the three hours and have a sane network to install things on...
