### ISSUE TITLE
32 bit

### ISSUE THREAD

**Issue by midgitary** [dnschneid/crouton#1364]
I am a relatively new player with linux and all its many forms. As my IT guy says "I know just enough to screw myself and send his kid to college."

Anyway, i do not know how o load the 32 bit libraries (if that is what they are called) and most of the programs i run through wine are 32 bit so i figure i could just go with a 32 bit system instead of the 64. 

What are your thoughts? What is the easiest way to go about doing whatever you suggest? And please remember i am a ludite when it comes to this stuff but i have the willingness and the heart to learn.

SO thanks in advance,
midge

**Comment by tedm** [comment]
Community college, or private college??

**Comment by dnschneid** [comment]
You can install a 32-bit chroot directly by using `-a i386` when you create the chroot, but be aware that it's apparently quite difficult to get 64-bit applications running in a 32-bit chroot (#1248).  If you're sure 32-bit is all you need (it's probably fine unless you're trying to do something really strange), go the -a route.
