### ISSUE TITLE
Gracefully handle when apt-get update fails

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1365]
People love to put broken PPAs in their apt sources.  Not really sure why, but to each his or her own, I guess.

Anyway, when that happens, crouton should do something other than fall flat on its face.  Some options (in order of increasing difficulty:

1. Simply print out some helpful tips about how to correct
2. Blindly ask if the user wants to disable all of their PPAs, then flood the sources.list/sources.list.d with #'s
3. Monitor apt-get update output, grep for the failing PPA, then (ask?) comment out the PPA in sources and try again.

The third is clearly the best, and I don't think it would be particularly hard to do, but there may not be enough people hitting these kinds of issues to make it really worthwhile.

**Comment by tedm** [comment]
4. Package up Crouton with a minimal stateful distro. Update it every year or so. If the user needs a specific update of something, they can apt-get install it and be responsible for new PPAs that they've added from the base complete crouton distribution. I never understood why the Crouton versions of xfce target (for ARM) are missing dozens of utilities that are on the minimal x86 cd or usb mini live distros, other than oversight for the arm (this is with precise)

**Comment by dnschneid** [comment]
I don't really understand what you're suggesting.  The *-desktop targets will pull in all the crap that distros bundle on their live CDs.  Not everyone wants to burn through their limited storage that way, though...

**Comment by tedm** [comment]
Since creating a new chroot with https:// and wget script commands takes a good hour or so, and I see the benefits of this - small crouton and latest everything when their chroot finishes, but it depends on increasingly unreliable connections, people being in the right places at the right time, proxies not blocking, PPA servers synced and running, etc.

If Crouton included the base image files in a big one time download, then creating chroots could be done without a connection, [or optional download upgrades, if online with fast connection] and faster (disk to disk) transfers.

About the missing utilities, they are minor, but I'm willing to document them if you like, I'll load a barebones 3 or 4 year old 12.04 ubuntu 32-bit x86 release on a pc, then, an xfce chroot on the chromebook, and things like nano, vim, gcc, and basically the core of bash and linux are just not there, they have to be installed with apt-get install <package>.

**Comment by DennisLfromGA** [comment]
'crouton' gives you the option '-d -f' to download a bootstrap file for your release which saves installation time and it doesn't need to be updated.

**Comment by dnschneid** [comment]
Yeah, exchanging one period of download for another, higher maintenance one doesn't really seem like a win to me.  Dennis' trick is probably what you want.  You can maintain a repo of generated bootstraps and download them on demand.

This is all OT though.

**Comment by tedm** [comment]
OK, thanks @DennisLfromGA I am creating a chroot now with -t xfce,xfce-desktop when done, I will use the -d -f to save a local bootstrap file, and see how much time that saves for new chroot installs.

@dnschneid yeah, sorry for going OT, but I think a Crouton `distro` could be useful in instances where connectivity is less than optimal. Am going to d/l the bootstrap files shortly though.

**Comment by divx118** [comment]
IMO I would go for number 1, just let people correct their own mistakes to learn from them. Also, I didn't look at it deeply, but wouldn't number 3 give "problems" if their are other distros added to crouton which will use different package managers?

**Comment by drinkcat** [comment]
> 1. Simply print out some helpful tips about how to correct

This is how I handle this kind of issues on Arch: some (rare) Arch updates require manual intervention. I think most people who manually add PPA are also able to remove it without much help.

**Comment by DennisLfromGA** [comment]
@divx118 > IMO I would go for number 1, just let people correct their own mistakes to learn from them.
@drinkcat > I think most people who manually add PPA are also able to remove it without much help.

I also think #1 is the best way to go for both of those reasons.

**Comment by dnschneid** [comment]
1. wins.

**Comment by DennisLfromGA** [comment]
Here's part of a routine I picked up off the internet.
I think the idea is worthy, maybe some of it could be used.
If we want to be more aggressive, just remove the comment.
( I don't know if it's "easy-as-pie" though... ;)

```
sudo rm /tmp/update.txt
sudo apt-get update | tee /tmp/update.txt 2>&1
awk '( /W:/ && /launchpad/ && /404/ ) { print substr($5,26) }' /tmp/update.txt > /tmp/awk.txt
awk -F '/' '{ print $1"/"$2 }' /tmp/awk.txt > /tmp/awk1.txt
sort -u /tmp/awk1.txt > /tmp/awk2.txt; tput sgr0
if [ -s /tmp/awk2.txt ]; then
  printf "PPA's that need to be removed\n%s\n" "$(cat /tmp/awk2.txt)"
  while read -r line
  do
    echo "sudo add-apt-repository -r ppa:$line"
  done < /tmp/awk2.txt > /tmp/out
# sudo bash /tmp/out
fi
```

**Comment by tedm** [comment]
@DennisLfromGA What about keeping a known good backup copy of /etc/apt/sources.list and if something is broken, prompt the user to revert to the default, but that they will have to add their package back again after they restore to a known good install?

http://askubuntu.com/questions/496495/can-a-ppa-repository-be-added-to-etc-apt-source-list

**Comment by DennisLfromGA** [comment]
I'm really not too well versed on ppa's and such, someone else might be a
better source.

On Sun, Apr 26, 2015 at 6:56 PM, tedm <notifications@github.com> wrote:

> @DennisLfromGA <https://github.com/DennisLfromGA> What about keeping a
> known good backup copy of /etc/apt/sources.list and if something is broken,
> prompt the user to revert to the default, but that they will have to add
> their package back again after they restore to a known good install?
>
>
> http://askubuntu.com/questions/496495/can-a-ppa-repository-be-added-to-etc-apt-source-list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1365#issuecomment-96443972>.
>



-- 
*DennyL@GMail*

**Comment by dnschneid** [comment]
Soooo, I ended up just ignoring apt-get update failures.  We could print out a helpful message, but I don't think anybody would see it.
