### ISSUE TITLE
android SMS alarming system 

### ISSUE THREAD

**Issue by Vaji005** [dnschneid/crouton#1371]
I'm developing an android application in which it monitors a sound parameter and sends an alarm (SMS) to a predefined mobile number if the sound parameter does not conform to a predefined limit. The mobile number is saved in a SQLite database table. 

The pseudo code for the relevant case is as follows,

IF soundParameter = A; then send no message
else if soundParameter != A; then send a message "Warning! Parameter has been exceeded" 

Hope some one can lend some expertise here.
Thanks in advance.

Asela

**Comment by dnschneid** [comment]
No expertise here; just #262
