### ISSUE TITLE
Always Disable ChromeOS power management 

### ISSUE THREAD

**Issue by flo9Z** [dnschneid/crouton#1372]
Hi, How to disable ChromeOS power management at every start ?

**Comment by flo9Z** [comment]
I have enter croutonpowerd -i but à think it's not permanent ?

**Comment by dnschneid** [comment]
You could add it to your chroot's `/etc/rc.local`, or you could use one of the many Chrome extensions that disables power management.

**Comment by flo9Z** [comment]
Ok I'll test to add this. 
I tested Chrome extension but if i watch à moitié with vlc on Ubuntu my screen turn off after à few minutes. 
Thanks for your prompt Reply

**Comment by flo9Z** [comment]
Movie* not moitié
