### ISSUE TITLE
Ubuntu Light ? 

### ISSUE THREAD

**Issue by flo9Z** [dnschneid/crouton#1373]
After installing Ubuntu via Crouton i noticed he was missing several packages (Ubuntu software manager, language selector, synaptic etc...) I have reinstall it manually but Do you have à command to install the full directly ? Thanks.

**Comment by dnschneid** [comment]
Either install the stuff manually, or use the *-desktop targets with crouton to install a lot more stuff.

**Comment by flo9Z** [comment]
Thanks !

**Comment by DennisLfromGA** [comment]
By default, crouton installs the necessities but you can add more with the
'desktop' targets. Run 'sudo sh ~/Downloads/crouton -t list' for a full
list.

Here's a descripton of the desktop targets:

gnome
        Installs the GNOME desktop environment. (Approx. 400MB)

gnome-desktop
    Installs GNOME along with common applications. (Approx. 1100MB)
     Requires: gnome

kde-desktop
        Installs KDE along with common applications. (Approx. 1000MB)
        Requires: kde
lxde
        Installs the LXDE desktop environment. (Approx. 200MB)
        Requires: gtk-extra
lxde-desktop
        Installs LXDE along with common applications. (Approx. 800MB)
        Requires: lxde
unity
        Installs the Unity desktop environment. (Approx. 700MB)
        Requires: gtk-extra
unity-desktop
        Installs Unity along with common applications. (Approx. 1100MB)
        Requires: unity
xfce
        Installs the Xfce desktop environment. (Approx. 250MB)
        Requires: gtk-extra
xfce-desktop
        Installs Xfce along with common applications. (Approx. 1200MB)
        Requires: xfce


On Thu, Jan 22, 2015 at 5:16 PM, flo9Z <notifications@github.com> wrote:

> After installing Ubuntu via Crouton i noticed he was missing several
> packages (Ubuntu software manager, language selector, synaptic etc...) I
> have reinstall it manually but Do you have à command to install the full
> directly ? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1373>.
>



-- 
*DennyL@GMail*

**Comment by flo9Z** [comment]
Ok i have installed with this command : sudo sh ~/Downloads/crouton -t unity it's different with the desktop target ?

**Comment by flo9Z** [comment]
Ok i have understand if i want packages directly the correct command it's unity-desktop and not only unity !
