### ISSUE TITLE
How do i unmount it without powerwashing?

### ISSUE THREAD

**Issue by CreepahUbuntu** [dnschneid/crouton#1374]
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r trusty -t unity -e
/usr/local/chroots/trusty already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

**Comment by divx118** [comment]
You already have a chroot with trusty.
Probably you want to delete it. Just use:
```
$ sudo delete-chroot trusty
```
