### ISSUE TITLE
Start chroot with xiwi w/o extension?

### ISSUE THREAD

**Issue by robbie0630** [dnschneid/crouton#1375]
I made a chroot with lxde and xiwi targets. Can I start it without the extension?

**Comment by DennisLfromGA** [comment]
The 'xiwi' target installs the 'extension' (*Clipboard synchronization and URL handling with Chromium OS*) target automagically but you also need to have the '[Crouton Integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension installed to make it work. The newer version of the '[Crouton Integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension has the added benefit of supporting 'xiwi'.

> I made a chroot with lxde and xiwi targets. Can I start it without the extension?

I'm not sure which 'extension' you're speaking of but I'll assume you mean the '[Crouton Integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension in which case you *can* start it without the extension if you first click on it and select 'Disable'.
I'm not sure why you would want to do this though, if you've only installed 'xiwi' without 'xorg' or 'xephyr' then, without the '[Crouton Integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension, it won't open a window.
