### ISSUE TITLE
Cannot load xiwi

### ISSUE THREAD

**Issue by jewnersey** [dnschneid/crouton#1376]
Toshiba Chromebook 2. 

popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...

continues until i close the window.
targets were xiwi,extension,kde. 

happens with unity as well, on both trusty and utopic

**Comment by dnschneid** [comment]
Can you post the complete output of `sudo enter-chroot croutonversion`?  Have you tried updating the chroots?  Does the update complete successfully?

**Comment by jewnersey** [comment]
[code]
chronos@localhost / $ sudo startkde
Entering /mnt/stateful_partition/crouton/chroots/utopic...


X.Org X Server 1.16.0
Release Date: 2014-07-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-54-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Sat Jan 24 23:51:58 AEST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=17fca4ea-20d4-aa48-b5a1-0518f264d04b/PARTNROFF=1 hashtree=PARTUUID=17fca4ea-20d4-aa48-b5a1-0518f264d04b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=1b40800e98615e347dc2cfc77be4e2762a587483 salt=4c7df17695fd2dd90378eb2d4204639db776204c50f98d5cb6dc7a64662648b2" noinitrd cros_debug vt.global_cursor_default=0 kern_guid=17fca4ea-20d4-aa48-b5a1-0518f264d04b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic 
Build Date: 09 December 2014  11:01:03PM
xorg-server 2:1.16.0-1ubuntu1.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.32.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jan 26 19:19:10 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a tab window.
startkde: Starting up...
Error: target STRING not available
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
kbuildsycoca4 running...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
This backend is only for XRandR 1.1, your version is:  1 . 4 
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
kded(7357) LayoutMemoryPersister::restoreFromFile: Failed to open layout memory xml file for reading "/home/mtp/.kde/share/apps/kded/session/keyboard/layout_memory.xml" error: 5 
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
kded(7357)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
QDBusConnection: name 'org.kde.kglobalaccel' had owner '' but we thought it was ':1.5'
QDBusConnection: name 'org.freedesktop.UDisks2' had owner '' but we thought it was ':1.9'
klauncher(7353)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "kactivitymanagerd.desktop" not found
No outputs have backlight property
kded(7357) XRandRConfig::applyKScreenConfig: Current mode is null: ModeId: "433" Mode:  QObject(0x0)  Output:  64 
socket_client_read_frame_header: Connection close from WebSocket client.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
klauncher(7353)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "kactivitymanagerd.desktop" not found
kded(7357) PowerDevil::Core::loadProfile: The profile  "Battery" tried to activate "DimDisplay" a non existent action. This is usually due to an installation problem or to a configuration problem. or simlpy the action is not supported 
kded(7357) PowerDevil::Core::loadProfile: The profile  "Battery" tried to activate "DPMSControl" a non existent action. This is usually due to an installation problem or to a configuration problem. or simlpy the action is not supported 
kded(7357) PowerDevil::Core::loadProfile: The profile  "Battery" tried to activate "BrightnessControl" a non existent action. This is usually due to an installation problem or to a configuration problem. or simlpy the action is not supported 
kwin(7611) KWin::EffectsHandlerImpl::loadEffect: EffectsHandler::loadEffect : Effect  "kwin4_effect_startupfeedback"  is not supported 
kwin(7611) KWin::EffectsHandlerImpl::loadEffect: EffectsHandler::loadEffect : Effect  "kwin4_effect_blur"  is not supported 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusObjectPath: invalid path ""
QDBusObjectPath: invalid path ""
klauncher(7353)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "kactivitymanagerd.desktop" not found
plasma-desktop(7628): ""geometry" - conversion of "58,2,0,25" to QRectF failed" 
plasma-desktop(7628): ""geometry" - conversion of "58,2,0,25" to QRectF failed" 
plasma-desktop(7628): ""geometry" - conversion of "58,2,0,25" to QRectF failed" 
plasma-desktop(7628): ""geometry" - conversion of "58,2,0,25" to QRectF failed" 
plasma-desktop(7628)/libplasma Plasma::isPluginVersionCompatible: unversioned plugin detected, may result in instability 
plasma-desktop(7628): ""geometry" - conversion of "58,2,0,25" to QRectF failed" 
plasma-desktop(7628)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "kde4-kmenuedit.desktop" not found
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
plasma-desktop(7628)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "systemsettings" not found
========================>  7 0
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
static bool QDeclarativeMetaType::isModule(const QByteArray&, int, int) Qt 4.7 import detected; please note that Qt 4.7 is directly reusable as QtQuick 1.x with no code changes. Continuing, but startup time will be slower. 
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
plasma-desktop(7628)/libakonadi Akonadi::AgentManagerPrivate::createDBusInterface: AgentManager failed to get a valid AgentManager DBus interface. Error is: 1 "org.freedesktop.DBus.Error.NameHasNoOwner" "Could not get owner of name 'org.freedesktop.Akonadi.Control': no such name" 
plasma-desktop(7628)/libakonadi Akonadi::SessionPrivate::socketError: Socket error occurred: "QLocalSocket::connectToServer: Invalid name" 
plasma-desktop(7628)/libakonadi Akonadi::SessionPrivate::socketError: Socket error occurred: "QLocalSocket::connectToServer: Invalid name" 
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
search paths:  ("/usr/local/bin", "/usr/bin", "/bin", "/usr/local/games", "/usr/games", "/usr/sbin", "/usr/local/sbin", "/usr/local/libexec", "/usr/libexec", "/opt/mysql/libexec", "/opt/local/lib/mysql5/bin", "/opt/mysql/sbin") 
Found mysql_install_db:  "/usr/bin/mysql_install_db" 
Found mysqlcheck:  "/usr/bin/mysqlcheck" 
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
file:///usr/share/kde4/apps/plasma/plasmoids/battery/contents/ui/CompactRepresentation.qml:73:9: QML Column: Cannot specify top, bottom, verticalCenter, fill or centerIn anchors for items inside Column
file:///usr/lib/kde4/imports/org/kde/plasma/components/SectionScroller.qml:103: TypeError: Result of expression 'listView' [null] is not an object.
file:///usr/lib/kde4/imports/org/kde/plasma/components/SectionScroller.qml:175: ReferenceError: Can't find variable: sectionsRepeater
file:///usr/lib/kde4/imports/org/kde/plasma/extras/ScrollArea.qml:162:9: QML ScrollArea: Cannot anchor to an item that isn't a parent or sibling.
file:///usr/lib/kde4/imports/org/kde/plasma/extras/ScrollArea.qml:162:9: QML ScrollArea: Cannot anchor to an item that isn't a parent or sibling.
file:///usr/lib/kde4/imports/org/kde/plasma/extras/ScrollArea.qml:162:9: QML ScrollArea: Cannot anchor to an item that isn't a parent or sibling.
file:///usr/lib/kde4/imports/org/kde/plasma/components/SectionScroller.qml:103: Error: Cannot assign [undefined] to QString
file:///usr/share/kde4/apps/plasma/plasmoids/notifier/contents/ui/devicenotifier.qml:224:13: QML QDeclarativeListView_QML_92: Possible anchor loop detected on fill.
file:///usr/share/kde4/apps/plasma/plasmoids/notifier/contents/ui/devicenotifier.qml:224:13: QML QDeclarativeListView_QML_92: Possible anchor loop detected on fill.
file:///usr/share/kde4/apps/plasma/plasmoids/notifier/contents/ui/devicenotifier.qml:224:13: QML QDeclarativeListView_QML_92: Possible anchor loop detected on fill.
file:///usr/share/kde4/apps/plasma/plasmoids/notifier/contents/ui/devicenotifier.qml:224:13: QML QDeclarativeListView_QML_92: Possible anchor loop detected on fill.
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
file:///usr/share/kde4/apps/plasma/packages/org.kde.systemtray/contents/ui/IconsList.qml:53:9: QML MouseRedirectArea: Binding loop detected for property "width"
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
akonadi.collectionattributetable                   OK
akonadi.collectionmimetyperelation                 OK
akonadi.collectionpimitemrelation                  OK
akonadi.collectiontable                            OK
akonadi.flagtable                                  OK
akonadi.mimetypetable                              OK
akonadi.parttable                                  OK
akonadi.parttypetable                              OK
akonadi.pimitemflagrelation                        OK
akonadi.pimitemtable                               OK
akonadi.pimitemtagrelation                         OK
akonadi.resourcetable                              OK
akonadi.schemaversiontable                         OK
akonadi.tagattributetable                          OK
akonadi.tagremoteidresourcerelationtable           OK
akonadi.tagtable                                   OK
akonadi.tagtypetable                               OK
mysql.columns_priv                                 OK
mysql.db                                           OK
mysql.event                                        OK
mysql.func                                         OK
mysql.general_log                                  OK
mysql.help_category                                OK
mysql.help_keyword                                 OK
mysql.help_relation                                OK
mysql.help_topic                                   OK
mysql.host                                         OK
mysql.ndb_binlog_index                             OK
mysql.plugin                                       OK
mysql.proc                                         OK
mysql.procs_priv                                   OK
mysql.proxies_priv                                 OK
mysql.servers                                      OK
mysql.slow_log                                     OK
mysql.tables_priv                                  OK
mysql.time_zone                                    OK
mysql.time_zone_leap_second                        OK
mysql.time_zone_name                               OK
mysql.time_zone_transition                         OK
mysql.time_zone_transition_type                    OK
mysql.user                                         OK
MySQL version OK (required "5.1" , available "5.5" ) 
Object::connect: No such signal QDBusAbstractInterface::StateChanged(uint)
Database "akonadi" opened using driver "QMYSQL" 
DbInitializer::run() 
checking table  "SchemaVersionTable" 
checking table  "ResourceTable" 
checking table  "CollectionTable" 
checking table  "MimeTypeTable" 
checking table  "PimItemTable" 
checking table  "FlagTable" 
checking table  "PartTypeTable" 
checking table  "PartTable" 
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
checking table  "CollectionAttributeTable" 
checking table  "TagTypeTable" 
checking table  "TagTable" 
checking table  "TagAttributeTable" 
checking table  "TagRemoteIdResourceRelationTable" 
checking table  "PimItemFlagRelation" 
checking table  "PimItemTagRelation" 
checking table  "CollectionMimeTypeRelation" 
checking table  "CollectionPimItemRelation" 
DbInitializer::run() done 
skipping update 2 
skipping update 3 
skipping update 4 
skipping update 8 
skipping update 10 
skipping update 12 
skipping update 13 
skipping update 14 
skipping update 15 
skipping update 16 
skipping update 17 
skipping update 18 
skipping update 19 
skipping update 20 
skipping update 21 
skipping update 22 
skipping update 23 
skipping update 24 
skipping update 25 
skipping update 26 
skipping update 28 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Indexes successfully created 
DataStore::unhideAllPimItems() 
Search loop is waiting, will wake again in -1 ms 
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
Database "akonadi" opened using driver "QMYSQL" 
PLUGINS:  "/usr/share/akonadi/agents" 
PLUGINS:  ("akonadinepomukfeederagent.desktop", "akonotesresource.desktop", "birthdaysresource.desktop", "contactsresource.desktop", "davgroupwareresource.desktop", "facebookresource.desktop", "googlecalendarresource.desktop", "googlecontactsresource.desktop", "icaldirresource.desktop", "icalresource.desktop", "imapresource.desktop", "invitationsagent.desktop", "kabcresource.desktop", "kalarmdirresource.desktop", "kalarmresource.desktop", "kcalresource.desktop", "kdeaccountsresource.desktop", "kolabproxyresource.desktop", "kolabresource.desktop", "localbookmarksresource.desktop", "maildirresource.desktop", "maildispatcheragent.desktop", "mboxresource.desktop", "migrationagent.desktop", "mixedmaildirresource.desktop", "mtdummyresource.desktop", "newmailnotifieragent.desktop", "nntpresource.desktop", "notesresource.desktop", "openxchangeresource.desktop", "pop3resource.desktop", "vcarddirresource.desktop", "vcardresource.desktop") 
search paths:  ("/usr/local/bin", "/usr/bin", "/bin", "/usr/local/games", "/usr/games") 
Executable "akonadi_nepomuk_feeder" for agent "akonadi_nepomuk_feeder" could not be found!
PLUGINS inserting:  "akonadi_akonotes_resource" 1 ("Resource", "Notes") 
PLUGINS inserting:  "akonadi_birthdays_resource" 0 ("Resource", "Unique") 
PLUGINS inserting:  "akonadi_contacts_resource" 1 ("Resource") 
PLUGINS inserting:  "akonadi_davgroupware_resource" 0 ("Resource", "FreeBusyProvider") 
PLUGINS inserting:  "akonadi_facebook_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_googlecalendar_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_googlecontacts_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_icaldir_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_ical_resource" 1 ("Resource") 
PLUGINS inserting:  "akonadi_imap_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_invitations_agent" 0 ("NoConfig") 
PLUGINS inserting:  "akonadi_kabc_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kalarm_dir_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kalarm_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kcal_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kdeaccounts_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kolabproxy_resource" 0 ("Resource", "Unique") 
PLUGINS inserting:  "akonadi_kolab_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_localbookmarks_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_maildir_resource" 1 ("Resource") 
PLUGINS inserting:  "akonadi_maildispatcher_agent" 0 ("Unique", "Autostart") 
PLUGINS inserting:  "akonadi_mbox_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_migration_agent" 0 ("Unique", "Autostart") 
PLUGINS inserting:  "akonadi_mixedmaildir_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_mailtransport_dummy_resource" 0 ("Resource", "MailTransport") 
PLUGINS inserting:  "akonadi_newmailnotifier_agent" 0 ("Unique", "Autostart") 
PLUGINS inserting:  "akonadi_nntp_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_notes_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_openxchange_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_pop3_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_vcarddir_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_vcard_resource" 0 ("Resource") 
search paths:  ("/home/mtp/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/mtp/.kde/lib/kde4/", "/usr/lib/kde4/") 
SEARCH MANAGER: searching in  "/home/mtp/.kde/lib/kde4/plugins//akonadi" : () 
SEARCH MANAGER: searching in  "/usr/lib/kde4/plugins//akonadi" : () 
SEARCH MANAGER: searching in  "/usr/lib/x86_64-linux-gnu/qt4/plugins/akonadi" : () 
SEARCH MANAGER: searching in  "/usr/bin/akonadi" : () 
SEARCH MANAGER: searching in  "/usr/lib/kde4/plugins/akonadi" : () 
SEARCH MANAGER: searching in  "/home/mtp/.kde/lib/kde4//akonadi" : () 
SEARCH MANAGER: searching in  "/usr/lib/kde4//akonadi" : () 
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
plasma-desktop(7628)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
Akonadi server is now operational. 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "plasma-desktop_7628_xzAfli" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "plasma-desktop_7628_xzAfli" true false 
Database "akonadi" opened using driver "QMYSQL" 
Database "akonadi" opened using driver "QMYSQL" 
klipper(7683) Klipper::loadHistory: Failed to load history resource. Clipboard history cannot be read. :  History file does not exist 
search paths:  ("/home/mtp/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/mtp/.kde/lib/kde4/", "/usr/lib/kde4/") 
search paths:  ("/home/mtp/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/mtp/.kde/lib/kde4/", "/usr/lib/kde4/") 
search paths:  ("/home/mtp/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/mtp/.kde/lib/kde4/", "/usr/lib/kde4/") 
search paths:  ("/home/mtp/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/mtp/.kde/lib/kde4/", "/usr/lib/kde4/") 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7699_7pzclR" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7699_7pzclR" true false 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7702_K6iKiI" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7702_K6iKiI" true false 
Database "akonadi" opened using driver "QMYSQL" 
Database "akonadi" opened using driver "QMYSQL" 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7700_o21i60" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7700_o21i60" true false 
Database "akonadi" opened using driver "QMYSQL" 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7701_PBWn5q" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "AkonadiAgentServer_7701_PBWn5q" true false 
Database "akonadi" opened using driver "QMYSQL" 
Database "akonadi" opened using driver "QMYSQL" 
New PolkitAgentListener  0x116a020 
Adding new listener  PolkitQt1::Agent::Listener(0x12d1690) for  0x116a020 
"Cannot create unix session: No session for pid 7681" 

** (process:7681): CRITICAL **: polkit_agent_listener_register_with_options: assertion 'POLKIT_IS_SUBJECT (subject)' failed
"Cannot register authentication agent!" 

(process:7681): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Database "akonadi" opened using driver "QMYSQL" 
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
Agent instance created in separate process. 
Agent instance created in separate process. 
Agent instance created in separate process. 
Agent instance created in separate process. 
plasma-desktop(7628)/plasma StatusNotifierItemSource::refreshCallback: DBusMenu disabled for this application 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_maildispatcher_agent_7703_p5k0lA" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_maildispatcher_agent_7703_p5k0lA" true false 
Database "akonadi" opened using driver "QMYSQL" 
Database "akonadi" opened using driver "QMYSQL" 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_migration_agent_7704_G3j1q3" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_migration_agent_7704_G3j1q3" true false 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_newmailnotifier_agent_7705_Rm4WLM" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_newmailnotifier_agent_7705_Rm4WLM" true false 
Database "akonadi" opened using driver "QMYSQL" 
Database "akonadi" opened using driver "QMYSQL" 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_maildispatcher_agent_7703_7ODlGL" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_maildispatcher_agent_7703_7ODlGL" true false 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV2(const QString&, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_maildispatcher_agent_7703_llhH3v" true 
QDBusObjectPath Akonadi::Server::NotificationManager::subscribeV3(const QString&, bool, bool) Akonadi::Server::NotificationManager(0x21a2100) "akonadi_maildispatcher_agent_7703_llhH3v" true false 
krunner(7685)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "searchproviders/wikit.desktop" not found
Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
I/O warning : failed to load external entity "/home/mtp/.qalculate/eurofxref-daily.xml"
I/O warning : failed to load external entity "/home/mtp/.qalculate/eurofxref-daily.xml"
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)
[/code]

**Comment by dnschneid** [comment]
Sorry, but the command I was asking for was `sudo enter-chroot croutonversion`...

**Comment by jewnersey** [comment]
sudo enter-chroot croutonversion
Entering /mnt/stateful_partition/crouton/chroots/kde...
crouton: version 1-20150122115021~master:0ad2d48f
release: precise
architecture: amd64
targets: xorg
host: version 6721.0.2015_01_25_0039 (Developer Build - mtp) developer-build swanky
Unmounting /mnt/stateful_partition/crouton/chroots/kde...

**Comment by dnschneid** [comment]
Is that image built from ToT?

**Comment by jewnersey** [comment]
sorry,  ToT?

**Comment by dnschneid** [comment]
What Chromium OS image are you using?  Did you build it yourself?

**Comment by jewnersey** [comment]
yes built it myself using the defaults for Toshiba Chromebook 2 (swanky)

**Comment by drinkcat** [comment]
@jewnersey : Can you provide the output of this, while `startkde` is running, and the crouton in tab window is open? (that is, from another terminal)
```
for pid in `pgrep nacl_helper`; do echo $pid; grep shm "/proc/$pid/maps"; done
```

**Comment by jewnersey** [comment]
chronos@localhost / $ for pid in `pgrep nacl_helper`; do echo $pid; grep shm "/proc/$pid/maps"; done
1626
24831
142300090000-14230fd80000 ---s 00000000 00:0f 105353                     /dev/shm/.org.chromium.Chromium.II0Ge0 (deleted)
14230fd80000-14230fff0000 r-xs 0fcf0000 00:0f 105353                     /dev/shm/.org.chromium.Chromium.II0Ge0 (deleted)
14230fff0000-142310020000 ---s 0ff60000 00:0f 105353                     /dev/shm/.org.chromium.Chromium.II0Ge0 (deleted)
1423fe7b0000-1423fea82000 rw-s 00000000 00:0f 105509                     /dev/shm/.org.chromium.Chromium.MHjHfy (deleted)
1423fea90000-1423fed62000 rw-s 00000000 00:0f 105377                     /dev/shm/.org.chromium.Chromium.eAr9KE (deleted)
7f7490dd1000-7f7490dd2000 rw-s 00000000 00:0f 105312                     /dev/shm/.org.chromium.Chromium.Sk66u4 (deleted).

**Comment by drinkcat** [comment]
Ok thanks, that's an easy fix.

**Comment by jewnersey** [comment]
oh great! thank you!
