### ISSUE TITLE
[Pixel] 3D/GPU Acceleration not working with wheezy target

### ISSUE THREAD

**Issue by Reyncor** [dnschneid/crouton#1377]
I installed with the following
`sudo sh crouton -r wheezy -t gnome,extension,xiwi,keyboard`

glxinfo returns VMWare as the OpenGL vendor.

Funnily enough, the wiki's instructions for the pixel are
"Should work fine on all releases"
https://github.com/dnschneid/crouton/wiki/3D-Hardware-acceleration

What should I run to fix it? I'm fairly experienced with linux, but not chroots.

**Comment by drinkcat** [comment]
Well, as it stands, there is no hardware acceleration in crouton in a tab (`xiwi`)...

I'm not sure what's the status of freon on different pixel channels (e.g. if it has landed on stable-channel yet), but we do not have any way to get acceleration when freon is enabled (see #1265).

If freon is _not_ enabled on your channel (i.e. `/dev/tty0` exists), then you can get 3D acceleration with the `xorg` target.
