### ISSUE TITLE
mands

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1378]

**Comment by dnschneid** [comment]
I guess in the case of [extended mands](https://en.wikipedia.org/wiki/Mand_%28psychology%29#Extended_mands), "unmount!" or "download faster!" would be reasonable for crouton, but I think if we supported them they would no longer be mands.

**Comment by DennisLfromGA** [comment]
Or a *superstitious mand*, as in "come on crouton, work would you!"

On Mon, Jan 26, 2015 at 6:47 PM, David Schneider <notifications@github.com>
wrote:

> I guess in the case of extended mands
> <https://en.wikipedia.org/wiki/Mand_%28psychology%29#Extended_mands>,
> "unmount!" or "download faster!" would be reasonable for crouton, but I
> think if we supported them they would no longer be mands.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1378#issuecomment-71563096>.
>



-- 
*DennyL@GMail*
