### ISSUE TITLE
Change in chromeos <-> crouton switching behavior

### ISSUE THREAD

**Issue by yisheng-on-linux** [dnschneid/crouton#1380]
I mentioned in another issue a while back that the 4 finger method of switching between sessions had changed and was now ctrl-alt-F1 to get to chrome, ctrl-alt-F2 to get to VT2 then ctrl-alt-F3 to get to the chroot (mandatory VT2 first). I couldn't just cycle thorugh everything with ctrl-alt-shift-F1/F2 as before.

This is ok, but it limits me to 1 chroot, since I can't cycle through them. Any ideas why this changed? Is something broken (this had been the way it is for a month+) or did I miss the memo on it? ;)

Thanks.

**Comment by DennisLfromGA** [comment]
Additonal chroots should be assigned to the next available VT, like F4(Full
Screen), F5(Switch Window), etc.

So to get to the 2nd chroot hit Ctrl-Alt-F2 then Ctrl-Alt-F4, you get back
to ChromeOS the same way as before Ctrl-Alt-F2 then Ctrl-Alt=F1.

I don't have/use xephyr, I use xorg but that's the way it works for me.

On Mon, Jan 26, 2015 at 10:37 PM, yisheng-on-linux <notifications@github.com
> wrote:

> I mentioned in another issue a while back that the 4 finger method of
> switching between sessions had changed and was now ctrl-alt-F1 to get to
> chrome, ctrl-alt-F2 to get to VT2 then ctrl-alt-F3 to get to the chroot
> (mandatory VT2 first). I couldn't just cycle thorugh everything with
> ctrl-alt-shift-F1/F2 as before.
>
> This is ok, but it limits me to 1 chroot, since I can't cycle through
> them. Any ideas why this changed? Is something broken (this had been the
> way it is for a month+) or did I miss the memo on it? ;)
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1380>.
>



-- 
*DennyL@GMail*

**Comment by dnschneid** [comment]
Ctrl+Alt+Shift+F1/F2 should still work.  Have you updated your chroot recently?  Could you post the output of croutonversion?

**Comment by yisheng-on-linux** [comment]
I have updated multiple times since this happened, and it occured after an update a month+ ago.  
My current croutonversion is:

crouton: version 1-20150122115021~master:0ad2d48f
release: trusty
architecture: amd64
targets: audio,cli-extra,extension,gtk-extra,x11,xephyr,xfce,xorg,chromium
host: version 6310.68.0 (Official Build) stable-channel quawks

**Comment by dnschneid** [comment]
Can you try updating with the x11_freon branch?  The technique for handling the keys is drastically different.  See #1265 and let me know if that fixes things for you.

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
