### ISSUE TITLE
REQ: re-add cinnamon target

### ISSUE THREAD

**Issue by splllllitz** [dnschneid/crouton#1381]
is this possible re:

drinkcat commented on Nov 20, 2014
cinnamon support in crouton was removed in #832.

Now, utopic has packages for cinnamon: https://launchpad.net/ubuntu/+source/cinnamon . If anyone feel like reviving it...

**Comment by dnschneid** [comment]
It's a possibility.  Let's keep this bug open as a reminder.  First we really need to get Utopic fully supported, but that's a separate bug.

**Comment by MrHallway0** [comment]
Just wondering will it ever be re-added?
