### ISSUE TITLE
I am an idiot, hello!

### ISSUE THREAD

**Issue by kmages** [dnschneid/crouton#1383]
I am nearly 59 years old and JUST learning LINUX so please excuse my ignorance.  My profile is at www.linkedin.com/in/kmages.  I'm a hardcore PIXEL user and the fact that it has been my only computer for two years and I still haven't learned LINUX says great things about the OS, ChromeOS and Google.  But suddenly I have a need to add Skype to my Chromebook.  I've managed for two years with Hangouts and other IM systems but I have a client that needs me to use Skype.  So I began a journey to add Ubuntu to my Chromebook.  I do have a desktop Mac with VMware running Ubuntu so I am not a stranger to it.  

What I simply want to know, is what is the best distro of Ubuntu to run on my PIXEL?  I like the Unity interface much better than XFCE.  Also, why can't I load a distro from my hard drive (SSD) instead of downloading through a sudo command targeting a URL?  All I want is a sudo command that allows me to load a robust version of Linux (I don't care about the file size and I can manage the power consumption) and instructions on installing Skype.  I will buy dinner for the simplest answer at the restaurant of your choice as long as it starts with McD.

Kind thanks,

kgm

**Comment by dnschneid** [comment]
You probably want `-r trusty` and `-t unity-desktop`.  A crouton chroot could *probably* be made from a some random installation on a hard drive with a little effort, but I don't think you gain anything from the process.  Once you have unity-desktop installed you can launch the chroot and install skype from the Ubuntu software center application.

TIL: [there](http://www.sunriver-resort.com/dining/oregon-restaurant-mcdivots) [are](http://www.yelp.com/biz/mcds-diner-blanchester) a [few](http://www.mcdaidsirishpub.com/) [restaurants](https://www.here.com/south-africa/cape-town/restaurant/mcds-pizzas-take-aways--710k3vq4-0448246b1f26477fb572518e5605e69e?x=ep&map=-34.06206,18.76182,16,normal) starting with McD, but they're kinda hard to get to.

**Comment by kmages** [comment]
Sorry David, and thanks.  What is the exact sudo statement that I ought to
use?  Any McD is OK with me, I just love the Golden Arches :-)

kgm
[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/941c8a8c844b068f6bf5ef4281cd8436/d6850bc81b82cde1e0296d02fd99752a?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by dnschneid** [comment]
`sudo sh ~/Downloads/crouton -r trusty -t unity-desktop` and then later `sudo startunity` should work, but in general I recommend reading through the README, help text (`sh ~/Downloads/crouton`), and tips printed out at the very end of the install process and building up the command lines yourself.

**Comment by kmages** [comment]
Most kind thanks!  I will heed your advice.  I yearn to learn.
[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/3f5d997bcdd54a283e63af78c0f94895/66c4f8228fb794b45b37ed650aa19abf?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by kmages** [comment]
Just so you know, it works perfectly!  You and this team are really brilliant!  Now, when will Microsoft just make a nice version of Skype for ChromeOS!!  Still glad to have Ubuntu running.

kgm
