### ISSUE TITLE
cras cpu usage 100%

### ISSUE THREAD

**Issue by buluba89** [dnschneid/crouton#1384]
Hello 
I am using ubuntu trusty with a toshiba chromebook 2
The problem that i have is that almost every time when there is sound both cras processes are using 100 % cpu and the sound is crackling
Also when the sound is playing for too long, the sound stops completely for both ubuntu and chromeos and i have to reboot to work again
Plz tell me if you want any extra data that can help you
Thank you

**Comment by DennisLfromGA** [comment]
Take a look at https://github.com/dnschneid/crouton/issues/1252#issuecomment-66974296, I believe it's the same. It looks like it's fixed in Version 40.

**Comment by buluba89** [comment]
Yes thank you this solved it
