### ISSUE TITLE
FVWM freezing in xiwi

### ISSUE THREAD

**Issue by hectorchu** [dnschneid/crouton#1389]
Trying to drag or resize a window in FVWM causes the window manager to freeze under the xiwi server.

**Comment by dnschneid** [comment]
Possibly same root cause as #1334

**Comment by drinkcat** [comment]
Indeed, there is a problem with both twm and fvwm. A common point between the 2 is that they display a wireframe when the window is moved/resized.

In any case, it appears that the X server itself was freezing. I'm not sure if it's an issue with my patch on xorg-dummy...

**Comment by drinkcat** [comment]
It also fails with a non-patched xorg-dummy.

**Comment by dnschneid** [comment]
File a bug upstream then?  We can always pull in the patch if it's small.

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
