### ISSUE TITLE
Precise: Keyboard input not working. 

### ISSUE THREAD

**Issue by nahberry** [dnschneid/crouton#1390]
Been running crouton for over a year now. Issues for me have only started with the updated crouton extension and running unity in a window, but this is an amazing new way of using a separate Linux distro, and I must say I'm very excited to see what can be done with it in the future. Now, onto the issues...

I've included screenshots of the output of sudo enter-chroot -n chrootname croutonversion, and some of the errors I've been getting. Crouton seems to have crashed though and I could not supply the output from the failed keystrokes. 

1. Installed crouton step by step, (unity/precise) ran 'sudo enter unity' as usual. Everything ran fine except the input from the keyboard (excluding the space bar, it worked). Tried typing everywhere from xterm to a notepad. 

2. Not sure why crouton will not connect, I don't believe this is a bug, I believe this is an issue on my end, but including screenshots just in case I'm wrong. 

![screenshot 2015-01-29 at 9 45 24 pm](https://cloud.githubusercontent.com/assets/8603542/5970525/8b850d60-a802-11e4-8b20-9b422e3ce2ec.png)
![screenshot 2015-01-29 at 9 45 07 pm](https://cloud.githubusercontent.com/assets/8603542/5970524/8b843142-a802-11e4-843b-c4cf582e3671.png)
![screenshot 2015-01-29 at 9 44 56 pm](https://cloud.githubusercontent.com/assets/8603542/5970526/8b86455e-a802-11e4-9ee2-72f4d6f354b9.png)
![screenshot 2015-01-29 at 9 18 06 pm](https://cloud.githubusercontent.com/assets/8603542/5970527/8b87877a-a802-11e4-8045-60ab098cafe9.png)

**Comment by drinkcat** [comment]
Have you tried updating your chroot?

**Comment by nahberry** [comment]
I have updated the chroot. Still getting same issue.

**Comment by nahberry** [comment]
UPDATE: Keyboard input is working again. Not sure what the issue was. Still having some connection issues with the extension though.

**Comment by dnschneid** [comment]
It'll try a few times to connect; that's normal.  Glad the other issue is fixed.

**Comment by nahberry** [comment]
thanks man!
