### ISSUE TITLE
Horizontal scrolling? Mouse acting funny.

### ISSUE THREAD

**Issue by thetrex** [dnschneid/crouton#1392]
My crouton (xfce4 trusty) doesn't have a working horizontal scroll, is there a way to reconfigure this?

Also when I am coding in sublime the cursor will often random click where it is pointing. I have had this problem with previous installations on a different chromebook as well. At first I though I was accidentally touching the touch pad or something, but it sometimes happens when my hands aren't even near it. Any idea what is happening?

**Comment by drinkcat** [comment]
Can you provide the output of `croutonversion`, in the chroot?

**Comment by thetrex** [comment]
crouton: version 1-20150127081428~master:e1bcac2b
release: trusty
architecture: amd64
targets: xfce
host: version 6680.17.0 (Official Build) beta-channel swanky

**Comment by DennisLfromGA** [comment]
@drinkcat, 
Can the target be simply 'xfce'? I thought xfce would pull in xorg, xiwi, or xephyr and gkt-extra at least - seems unusual to me.

**Comment by drinkcat** [comment]
@DennisLfromGA : `targets` only shows the one that we specified explicitly.

@thetrex : Just to confirm, you are not using crouton in a tab, right? (i.e. you are using Ctrl-Alt-Shift-Back/Forward to switch to crouton?)

**Comment by thetrex** [comment]
@drinkcat : That is correct, I am not using crouton in a tab.

**Comment by drinkcat** [comment]
@thetrex : Sorry for the delay. X11 touchpad drivers sometimes have issues... You can play with `synclient`, first to enable horizontal scrolling, and then try to fix sensitivity. crouton modifies `FingerLow` and `FingerHigh`, but it might be that the values we use are not optimal.

#1302 will provide better drivers eventually.

**Comment by brendenyule** [comment]
Thanks, I got the touchpad working properly now.

**Comment by thetrex** [comment]
Thank you, I got the touch pad working correctly now.

**Comment by dnschneid** [comment]
Could you let us know what parameters you used?
