### ISSUE TITLE
Having problem with installing

### ISSUE THREAD

**Issue by whispz** [dnschneid/crouton#1393]
Sorry/ for the trouble but I am stuck. Look like I was almost done with the installation then I hit this.

Cp: Cannot create regular file'/usr/Local/chroots/precise/ .crouton-targets': no such file or directory

Is there something I did wrong and what can I do to fix this and get this going?

**Comment by davidlowryduda** [comment]
Would you mind saying exactly what steps you took to get to this point?

**Comment by whispz** [comment]
That I got sorted out. Now I am getting thisVVV

Entering /usr/local/chroots/precise...
[dix] Could not init font path element /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType, removing from list!
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
xfdesktop[11362]: starting up
xfce4-settings-helper: Another instance is already running. Leaving...
(polkit-gnome-authentication-agent-1:11373): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed
(polkit-gnome-authentication-agent-1:11373): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnkn
own: The name org.gnome.SessionManager was not provided by any .service files
(xfce4-settings-helper:11378): xfce4-settings-helper-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.
running 'ssh-agent -s -k'
/etc/xdg/xfce4/xinitrc: 1: eval: ssh-agent: not found
Running exit commands...
/usr/bin/xinit: connection to X server lost
waiting for X server to shut down xscreensaver: 23:32:19: SIGHUP received: restarting...
xscreensaver: 23:32:19: running as johns/johns (1000/1000)
xscreensaver: 23:32:19: Can't open display: :1
xscreensaver: 23:32:19: running as johns/johns (1000/1000)
xscreensaver: 23:32:19: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?
              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html
Unmounting /usr/local/chroots/precise...


So I enter by doing the sudo startxfce4 was looking around cause I just got it set up. And I decided to go and try the whole switch back and forth method [ctrl+alt+ < or > 
well it didnt do anything when I did ctrl+alt back. but if I was to do ctrl+alt forward then it takes me to a terminal page. I am going to try to load a image of it.

**Comment by whispz** [comment]
![20150201_234849](https://cloud.githubusercontent.com/assets/10784868/5997229/53176c12-aa6d-11e4-8225-b7d84be89090.jpg)

**Comment by whispz** [comment]
truly sorry I did not know how to rotate the image. But that is what I get when I do ctrl+alt forward and to exit that ctrl+alt back. then so I logged out and that is when I came across the the other error.

**Comment by whispz** [comment]
Thank you for your time to by the way I appreciate it.

**Comment by davidlowryduda** [comment]
I notice the line 

>xfce4-settings-helper: Another instance is already running. Leaving...

This makes me wonder if perhaps you should turn off and restart your machine. This might also be a good time to try the often-easy-solution of updating with

>sudo sh ~/Downloads/crouton -u -n chrootname

and pay careful attention to whether or not you get any errors. 

Supposing that doesn't do anything. What happens if you do ctrl+alt+shift forward/back?

Further, can you do ctrl+alt forward followed by ctrl+alt+refresh and see if that behaves differently? I've had incomplete installs/updates in the past where I used this temporary workaround before resolving my problems.

**Comment by whispz** [comment]
I tried to do an update and it said there was no updates for it. No nothing happens if I do any of those. Just if I do ctrl+alt forward then it takes me to that terminal like screen. I tried to power wash and reload it and it just did the same thing all over so I am at a loss.

**Comment by dnschneid** [comment]
Could you describe the steps you take, starting from power wash?

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
