### ISSUE TITLE
Screen stays on...

### ISSUE THREAD

**Issue by kmages** [dnschneid/crouton#1394]
Not sure which is causing my screen on a Chromebook Pixel to stay on (no time-out to black) as long as I leave my computer open.  Is it crouton with my new "trusty" install or is it the new Chrome version?

Version 40.0.2214.93 (64-bit)
Platform 6457.83.0 (Official Build) stable-channel link
Firmware Google_Link.2695.1.155

Just curious if anyone else has this issue...

kgm

**Comment by dnschneid** [comment]
Are you in crouton or in Chromium OS when this happens?  Is there a lot of motion on the screen?

**Comment by kmages** [comment]
I am in crouton and there is no motion at all.

[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<http://about.me/KenMages>

**Comment by dnschneid** [comment]
You may want to check the screensaver settings in Unity, or try installing xscreensaver `sudo apt-get install xscreensaver` if there's no screensaver.

**Comment by kmages** [comment]
Already did that thanks David!
[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/c880972c87487c595b750b923ca0def1/a509eca0873b8be8377416d0e0403ae2?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by dnschneid** [comment]
Did it fix things?

**Comment by kmages** [comment]
Fixed!
