### ISSUE TITLE
VirtualBox doesn't recompile kernel modules?

### ISSUE THREAD

**Issue by robbie0630** [dnschneid/crouton#1395]
I installed kernel headers using [this script](https://github.com/divx118/crouton-packages/blob/master/setup-headers.sh). I ran `/etc/init.d/vboxdrv VirtualBox gives this output:

    Stopping VirtualBox kernel modules ...done.
    Recompiling VirtualBox kernel modules ...failed!
    (Look at /var/log/vbox-install.log to find out what went wrong)
The `/var/log/vbox-install.log` says `Makefile:183: *** Error: unable to find the sources of your current Linux kernel. Specify KERN_DIR=<directory> and run Make again.  Stop.`. If anyone could identify the problem, because this is most likely crouton-related, this would be most helpful. Thanks in advance.

**Comment by divx118** [comment]
Please open a new issue on https://github.com/divx118/crouton-packages/issues then put in that issue your kernel version `uname -r` and the output of the script setup-headers.sh.  
Please don't post issues about this on crouton github. It has nothing to do with the crouton scripts and will only clutter things here. Thanks in advance.
