### ISSUE TITLE
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1

### ISSUE THREAD

**Issue by bertnic** [dnschneid/crouton#1398]
this error occurrs whenever I try to install unity, it used to work before though.
my dumb, I tried to upgrade release within a previous working installation. Since then no more chances to get a working chroot environment. Not even powerwashing my Hp chromebox or deleting previous installation folders.

**Comment by dnschneid** [comment]
Did you update crouton after you updated the release?

**Comment by bertnic** [comment]
Sure. I say again what I did.
Downloaded Crouton. installed pangolin basic without extensions.
Everithing worked properly. Installed a lot of missing pieces like apt and software center
Upgraded pangolin to trusty using apt.
Answered to a couple of scary questions during the upgrade phase. Proved I gave the wrong answers, the fact that ubuntu cannot start anymore.
Tried to reinstall deletnig previous folder installation: Same error
Tried to install directly trusty together with extensions: Same error
Powerwashed Chromebox, downloaded crouton from github, reinstalled trusty and extensions: Same error
The error occurs when I do a "sudo startunity"
Chrome OS works flawlessly.

**Comment by dnschneid** [comment]
Some ambiguities in there: did you update crouton (using the crouton installer's -u flag) after upgrading to Trusty inside the chroot?  When you say "reinstalled trusty", did you install trusty directly via crouton's -r, or did you go through the same upgrade steps as you went through the first time?

**Comment by bertnic** [comment]
No. I wasn't aware of -u flag. I simply downloaed again crouton after powerwashing the chromebox.
Yes. I reinstalled ubuntu-desktop from scratch with audio, chrome, x11, cli-extra, core, extension, gtk-extra, unity, unity-desktop using the -r flag to force trusty
I tried to reinstall twice, with and without powerwashing the cromebox.

**Comment by dnschneid** [comment]
Okay, cool.  Could you please post the output of both `sudo enter-chroot croutonversion` and `sudo startunity`?

**Comment by bertnic** [comment]
chronos@localhost / $ sudo enter-chroot croutonversion
Entering /usr/local/chroots/nikilist...
crouton: version 1-20150127081428~master:e1bcac2b
release: trusty
architecture: amd64
targets: audio,chrome-dev,x11,cli-extra,core,extension,gtk-extra,unity,unity-desktop,xbmc
host: version 6680.17.0 (Official Build) dev-channel zako_freon 
Unmounting /usr/local/chroots/nikilist...
===================================================================
chronos@localhost / $ sudo startunity
Entering /usr/local/chroots/nikilist...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-70-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Jan 26 21:49:09 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=49fb7972-09bd-8a46-a845-d85e2b427d90/PARTNROFF=1 hashtree=PARTUUID=49fb7972-09bd-8a46-a845-d85e2b427d90/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=966bbb8b36b7ecf000951fa85a08afa1370e1e5a salt=af179d09f2a42ad37ffafedcdb65ded75b805b976c566267b5c9bb8f5d2c2242" noinitrd vt.global_cursor_default=0 kern_guid=49fb7972-09bd-8a46-a845-d85e2b427d90 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic 
Build Date: 10 December 2014  06:15:52PM
xorg-server 2:1.15.1-0ubuntu2.6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Feb 10 08:46:19 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup
Hangup

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Unmounting /usr/local/chroots/nikilist...

**Comment by dnschneid** [comment]
Oh.  You're on dev channel, which converted to freon instead of X for display, so crouton is falling back on X-in-a-window (xiwi).  You need to do one of three things:
1. Install the extension so xiwi will work (as linked to in the log you just posted). This gives you a nice crouton-in-a-window integration with Chromium OS, but it doesn't have GPU acceleration so Unity will perform poorly.
2. Switch away from dev channel.  You'll have to power-wash, so back up your chroots first.
3. Try out my [experimental freon branch](https://github.com/dnschneid/crouton/archive/x11_freon.tar.gz) (see #1265).  Extract it with `cd ~/Downloads; tar xf x11_freon.tar.gz`, then update your chroot using `sudo sh ~/Downloads/*/installer/main.sh -u -n trusty` and see if it works.  Post back to #1265 if it works for you...

**Comment by bertnic** [comment]
Great, will let you know how it goes.
I'll try nr. 3 before then 1 and lastly 2 if nothing else works
Only one thing puzzles me, how did it work before upgrading to trusty within ubuntu through apt ugrade, I'd sear I was still on dev channel then...
BTW thanks you're awesome.

**Comment by dnschneid** [comment]
If you rebooted or power-washed, you would have upgraded to the latest dev channel.  Probably just bad timing :)

**Comment by bertnic** [comment]
Sounds reasonable.
just to let you know that nr. 3 worked for me.
So thankful !!!!
I'll post back as soon as I'm able to figure out how to do this.

**Comment by olec04** [comment]
won't work for me i used my beta channel for along time and worked now i still have the same error and just moved to dev channel to see if it fixed but it did not it was still the same.Here is the output of sudo enter-chroot chrootversion.
Entering /mnt/stateful_partition/crouton/chroots/precise...
Unknown username "dnsmasq" in message bus configuration file
-su: 1: chrootversion: not found
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
here is ubuntu precise starting from sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Unknown username "dnsmasq" in message bus configuration file

ERROR: ld.so: object '/usr/local/lib/croutonfreon.so' from LD_PRELOAD cannot be preloaded: ignored.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Mon Mar 16 21:07:15 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9a544ab9-217b-a047-90d7-dacba19c4a5d/PARTNROFF=1 hashtree=PARTUUID=9a544ab9-217b-a047-90d7-dacba19c4a5d/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=60f5286ee95ad4e4fed66bf0b836747473dcf4ff salt=a646819f56d366dfac00ce180e080bc5a079913065a6845b60b1fff787123f4b" noinitrd vt.global_cursor_default=0 kern_guid=9a544ab9-217b-a047-90d7-dacba19c4a5d add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Mar 27 09:22:41 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...!

**Comment by xeoron** [comment]
Have you considered using xiwi, instead of Xorg?

I was having rendering problems on the new Acer C910, until I switched to
it to using that. Plus there is a Google Chrome Browser extension that can
link into it. Chrome Store extension link here called: crouton integration
<https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom>
It was created by a Google intern in 2014.

*Example usage of xiwi*:

   - *sudo sh ~/Downloads/crouton xiwi,unity -u*
   - option *-u* updates your target
   - replace *unity* with whatever desktop environment name you have


Does this help?

-Jason

**Comment by DennisLfromGA** [comment]
@xeoron,

That example is close but won't work as is, try this:

  `sudo sh ~/Downloads/crouton -t xiwi -u`
  \- option *-u* updates your target

The *unity* target, once installed, is not required, all installed targets will be updated with *-u*.

**Comment by olec04** [comment]
@DennisLfromGA THANK YOU!
