### ISSUE TITLE
Advanced Encryption Options

### ISSUE THREAD

**Issue by Timvrakas** [dnschneid/crouton#1399]
Firstly, i'm absolutely loving my new Linux net book :) Thanks people!

I have an idea for a new method of encryption.
I think it seems rather silly to have to type in my extraneously long password no less than 3 times to get into the chroot, and then a 4th if I need sudo. The machine takes a few seconds to boot, but logging in takes almost a minute (Perhaps I'm spoiled by chrome :) ).
Ok, so I have a new system (or a plan at least)
1. Encrypted chroot files on external partition (yay thanks drinkcat!)
2. Un-encrypted private key for chroot in user statefull partition (encrypted by TPM/Google Login)
3. Autostart on Login script (possibly a program that listens for a key-press to start crouton)

In addition, if you are super crazy you could not include the encrypted key on encrypted, only backed up, but then you lose the developer-mode-wipe-protection.

I'm going to look into it but I expect to have trouble at some point.
Thanks

**Comment by dnschneid** [comment]
I think the key here (no pun intended) is to allow for no passphrase if -k is specified, and for a way to remove the passphrase with edit-chroot if the keyfile is separate.  Definitely worth implementing; feel free to ask questions here or on #crouton-devel as you start digging into it.

**Comment by Timvrakas** [comment]
Thanks. As soon as I back up Ill get to work. 
Do you have any kind of timeframe on merging drinkcat's seperate-partition with the latest version? even in an experimental branch would be nice. I'm running that now but its severely out of date.

**Comment by dnschneid** [comment]
It'll be a while.  separate-partition is really invasive and requires a lot of testing, and there are a lot of other things to get working (like GPU acceleration on Freon)...
If you post on the PR asking for a rebase he might find the chance to do it for you, but I doubt it'll get much testing.

**Comment by Timvrakas** [comment]
I just rebased it, it wasn't too hard. As soon as I test it I'll ask him to
pull it into his repo. Then I'll start on the keys.

**Comment by Timvrakas** [comment]
I'm confused about what this block of code in mount-chroot does

    if [ -z "$KEYFILE" ]; then
            KEYFILE="$CHROOTSRC/.ecryptfs"
            if [ -f "$KEYFILE" ]; then
                header="`head -n1 "$KEYFILE"`"
                if [ -n "$header" ]; then
                    KEYFILE="$header"
                fi
            fi
        elif [ "${KEYFILE#/}" = "$KEYFILE" ]; then
            KEYFILE="$PWD/$KEYFILE"
        fi
        if [ -d "$KEYFILE" -o ! "${KEYFILE%/}" = "$KEYFILE" ]; then
            KEYFILE="${KEYFILE%/}/$NAME"
        fi
        if ! mkdir -p "`dirname "$KEYFILE"`"; then
            error 1 "Unable to create directory for $KEYFILE"
        fi

Specificaly why in line 6 the KEYFILE variable, (which holds the path of the keyfile?) is filled with the header variable, (which holds the contents of the file?). Then later the KEYFILE is again the path of the file.

Also, are the 2 conditionals doing with the #/}  and %/} stuff? I have never seen that before. (in my limited experience.

Thanks

**Comment by DennisLfromGA** [comment]
@Timvrakas,

Sorry, I don't use encryption on my chroots nor do I know anything about it but...
@dnschneid pointed me to a very good explanation of  the parameter manipulaiton methods here - https://github.com/dnschneid/crouton/commit/3401dc491560e113052c888f220475936b6c452f#commitcomment-9636085.

**Comment by dnschneid** [comment]
When you relocate the keyfile, the .ecryptfs file in the chroot points to the keyfile's location.

**Comment by Timvrakas** [comment]
OK thanks!

**Comment by Timvrakas** [comment]
OK I have a first draft done, but I have not yet tested it and I am leaving for vacation so who knows if I will get around to testing it this week. It is in https://github.com/Timvrakas/crouton/tree/encryption 
I will get around to testing eventually.

FYI I still need the edit-chroot part, all I have done is the mount-chroot so far.

**Comment by Timvrakas** [comment]
OK there is a problem. The output of `hexdump -v -n32 -e'"%02x"' /dev/urandom` is not always the same length. Usually it is 64 hex characters but sometimes it is 63 or even 62 (and less I would guess).
`openssl rand -hex 32` would have been a better alternative I guess. But now it is too late for all the people (like me) who already have the wrong length keys. Instead of the `head` and `tail` business I will try separating them by line or in separate files.

**Comment by dnschneid** [comment]
Whoa, that's a significant bug.  I'll fix that immediately.  It looks like `hexdump -v -n32 -e'32/1 "%02x"' /dev/urandom` does the right thing.

**Comment by Timvrakas** [comment]
Ok I ended up just splitting the fnek and key into 2 separate lines. It is working for me and I will start on the edit-chroot part.
By the way I just noticed a weird quirk I cannot explain. For the normal encryption system when you input an incorrect paraphrase the unwrap command fails. But if you enter no password it does not fail, but instead adds invalid keys, and the chroot fails to start.

**Comment by Timvrakas** [comment]
OK here it is! (cf2aacba07e65d75c5b1c5484eae235588db1965)
I think edit-chroot and mount-chroot are good to go. I tested them on my C720
I am unsure if (or how) I should edit main.sh and add an option to set this up on creation of a chroot, for now you have to run `edit-chroot -u` or `mount-chroot -u` to create the keys.

I'm still new to all this (crouton, git, bash, life) so feel free to offer comments, questions, concerns, criticisms, critiques, complaints.

**Comment by DennisLfromGA** [comment]
@Timvrakas,

OT - but...

> I just rebased it, it wasn't too hard. As soon as I test it I'll ask him to
> pull it into his repo.

If you don't mind, I'd like to try your branch of 'crispy crouton' since you've recently rebased it.
I, just today, installed a 128GB ssd in my HP Chromebook 14 (whew!) and am anxious to get going.

Thanx,
-DennisL

**Comment by Timvrakas** [comment]
@DennisLfromGA feel free, I just rebased it again. It is here https://github.com/Timvrakas/crouton/tree/drinkcat-separate_partition
It went smoothly, but I have not had a chance to test it so beware!
Thanks

**Comment by DennisLfromGA** [comment]
Thanx, I'm on it...

On Tue, Apr 7, 2015 at 9:50 AM, Tim Vrakas <notifications@github.com> wrote:

> @DennisLfromGA <https://github.com/DennisLfromGA> feel free, I just
> rebased it again. It is here
> https://github.com/Timvrakas/crouton/tree/drinkcat-separate_partition
> It went smoothly, but I have not had a chance to test it so beware!
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1399#issuecomment-90559849>.
>



-- 
*DennyL@GMail*

**Comment by DennisLfromGA** [comment]
@Timvrakas - Maybe we should take tis off-line.

I ran - 
`sudo sh ~/Downloads/crouton-drinkcat-separate_partition/installer/main.sh -S -s 10000`
a couple of times and it bombed out and rebooted.

I then ran -
`sudo sh -x ~/Downloads/crouton-drinkcat-separate_partition/installer/main.sh -S -s 10000 2>&1 | tee -a ~/Downloads/crispy.log`
another couple of times and it did the same.

The last, pertinent part of the logs were -
```
+ [ 2 -gt 0 ]
+ printf \rYou have %2d seconds to press Ctrl-C to abort... 2
You have  2 seconds to press Ctrl-C to abort...+ sleep 1
+ time=1
+ [ 1 -gt 0 ]
+ printf \rYou have %2d seconds to press Ctrl-C to abort... 1
You have  1 seconds to press Ctrl-C to abort...+ sleep 1
+ time=0
+ [ 0 -gt 0 ]
+ echo

+ set -x
+ [ -n  -o -n  ]
+ wait
+ error 1 Cannot start subshell.
+ local ecode=1
+ shift
+ echo Cannot start subshell.
Cannot start subshell.
+ exit 1
```
I even added a `set -x` but still can't figure out where it's failing.

Have you run it successfully?

My Chromebook is:
```
Version 42.0.2311.67 beta (64-bit)
Platform 6812.59.0 (Official Build) beta-channel falco
Firmware Google_Falco.4389.92.0
```

Thanx,
-DennisL

**Comment by Timvrakas** [comment]
Huh. Well I do agree we should move this to an issue on that branch. I won't have a chance to test it for a few days, but have you tried running it without the command line options for size, just using the prompts?

**Comment by DennisLfromGA** [comment]
@Timvrakas - I'm moving this conversation to https://github.com/dnschneid/crouton/pull/706, see you there ;)

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
