### ISSUE TITLE
Cannot install Crouton on SD card (read only)

### ISSUE THREAD

**Issue by letheasce** [dnschneid/crouton#1400]
This isn't a new issue but none of the solutions that I've found here and elsewhere have worked for me. I am trying to install to an SD card but I get errors during clean up due to the SD card being a read-only file system. 
I used chown and chmod to get here: 
drwxrwxrwx 5 chronos chronos 4096 Feb  5 13:52 SD Card
so I think the problem is here:
/dev/sdb1 on /media/removable/SD Card type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)
I tried remounting it like this:
sudo mount -t ext4 -o remount,rw /dev/sdb1 /var/host/media/removable/SD\ Card
but I got an error saying the device could not be remounted because it was write-protected. The card is not locked. Can you advise me? Or is there a tutorial somewhere for this?

**Comment by dnschneid** [comment]
This is probably #288
