### ISSUE TITLE
Xorg dependency error when trying to install Utopic

### ISSUE THREAD

**Issue by snowball7275** [dnschneid/crouton#1401]
When running the command
 sudo sh ~/Downloads/crouton -t unity -r utopic -e 
after a while, it gives me an rsyslog error. There was already a thread about this and I got that solved. However, shortly after I get this error:

Unpacking libwayland-egl1-dummy (8.0.4) ...
dpkg: libwayland-egl1-dummy: dependency problems, but configuring anyway as you requested:
 libwayland-egl1-dummy depends on libegl1-mesa-drivers; however:
  Package libegl1-mesa-drivers is not installed.

Setting up libwayland-egl1-dummy (8.0.4) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  libwayland-egl1-dummy
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 3072 B disk space will be freed.
(Reading database ... 17109 files and directories currently installed.)
Removing libwayland-egl1-dummy (8.0.4) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xorg : Depends: xserver-xorg (>= 1:7.7+7ubuntu2)
 xserver-xorg-video-fbdev : Depends: xorg-video-abi-18
                            Depends: xserver-xorg-core (>= 2:1.15.99.903)
 xserver-xorg-video-intel : Depends: xorg-video-abi-18
                            Depends: xserver-xorg-core (>= 2:1.15.99.903)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in utopic
Not unmounting /mnt/stateful_partition/crouton/chroots/utopic as another instance is using it.

The output of sudo enter-chroot -n utopic croutonversion is

Entering /mnt/stateful_partition/crouton/chroots/utopic...
UID 1000 not found in utopic
Not unmounting /mnt/stateful_partition/crouton/chroots/utopic as another instance is using it.

Here is croutonversion when I get in to the chroot using root user

chronos@localhost / $ sudo enter-chroot -u root
Password: 
Entering /mnt/stateful_partition/crouton/chroots/utopic...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] n
Skipping setup. You will be prompted again next time.
croot@localhost:~# croutonversion
crouton: version 1-20150127081428~master:e1bcac2b
release: utopic
architecture: amd64
targets: unity
host: version 6457.83.0 (Official Build) stable-channel lumpy 

Here is the output of cat /etc/lsb-release from the chroot

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"

And here is the output of cat /etc/lsb-release from crosh

CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={A854E62E-9CB3-4DBE-8BBE-88C48FD65787}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={A854E62E-9CB3-4DBE-8BBE-88C48FD65787}
CHROMEOS_RELEASE_BOARD=lumpy-signed-mp-v3keys
CHROMEOS_RELEASE_DESCRIPTION=6457.83.0 (Official Build) stable-channel lumpy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6457.83.0

I've tried installing the packages manually but some of the packages can't be installed with apt-get.. Can someone help? I've even tried reinstalling the installer and updating the chroot, but these things seem not to help.

NOTE: I've tested this with xfce, KDE, and Unity. From what I can tell, it doesn't matter what DE you use, but I haven't tried with other supported DEs.

**Comment by dnschneid** [comment]
This is #1182
