### ISSUE TITLE
crouton slow switching / black screen pause.

### ISSUE THREAD

**Issue by ComputerLag** [dnschneid/crouton#1403]
I have an issue, I needed to update my ```xserver-xorg-video-intel``` package to support GTK 3.14. the old driver was producing bugs with shadows that is fixed in the later version.

Now when I Ctrl+Alt+Shift+Back / Forward from that chroot it changes to a black screen and pauses for about 3 seconds. With the old stock intel driver it switches instantly.

Is there any log files I can check to see why it's pausing between switches? I want to run the latest drivers, but I also want to be able to switch quickly.

What I Did:
```
sudo apt-add-repository ppa:oibaf/graphics-drivers
sudo apt-get update
sudo apt-get install xserver-xorg-video-intel
```

**Comment by divx118** [comment]
I don't think there are any special log messages for the intel driver at least I didn't notice any, except the obvious ones. `dmesg` xorg log in /var/log and maybe /var/log/messages.  
However I could be wrong, maybe someone else noticed another one.  
Just interested which release do you run on which chromebook?
Also what hardware acceleration do you use in xorg sna, uxa, glamor?  
FYI an interesting read about the intel driver could be https://wiki.archlinux.org/index.php/Intel_graphics.

**Comment by dnschneid** [comment]
Please try updating with the x11_freon branch: see #1265

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
