### ISSUE TITLE
man, rpm, yum commands not found

### ISSUE THREAD

**Issue by cyrxk** [dnschneid/crouton#1404]
I just installed xfce on my chromebook using these instructions http://lifehacker.com/how-to-install-linux-on-a-chromebook-and-unlock-its-ful-509039343 and anytime I try to use certain commands, they aren't found. 
"man ls", for example, gives the error "bash: man: command not found". Analogous error messages result from using rpm and yum.

**Comment by DennisLfromGA** [comment]
That article installs the xfce4 desktop environment which is a minimal
package to conserve space on a Chromebook which usually just has a 16GB
SSD.

You can install the equivalent of the Xubuntu desktop to your existing
chroot with:

    sudo sh ~/Downloads/crouton -t xfce-desktop -u

That'll get you a whole lot more software to play with.

On Tue, Feb 10, 2015 at 12:21 AM, cyrxk <notifications@github.com> wrote:

> I just installed xfce on my chromebook using these instructions
> http://lifehacker.com/how-to-install-linux-on-a-chromebook-and-unlock-its-ful-509039343
> and anytime I try to use certain commands, they aren't found.
> "man ls", for example, gives the error "bash: man: command not found".
> Analogous error messages result from using rpm and yum.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1404>.
>



-- 
*DennyL@GMail*
