### ISSUE TITLE
scanning

### ISSUE THREAD

**Issue by roubao** [dnschneid/crouton#1407]
Thanks David for your nice job. my CR-48 can print docs/pdfs with crouton+cups.
Now I wonder whether we can scan docs with crouton+sane using local usb scanners.

**Comment by dnschneid** [comment]
It should work fine.  Have you tried it?

**Comment by roubao** [comment]
since there is only 16G harddisk, I installed crouton 'core' only, no X. the scanner I'm using is Epson Perfection 2480. Epson provides a package to config/compile/install. But it requires X. so no luck. I am not sure how to skip that requirement.

**Comment by dnschneid** [comment]
X11 (without a desktop environment) isn't *that* big; try just the x11 target.  If that's a prereq for what you're trying to do there's not a lot I can help you with there.

**Comment by roubao** [comment]
It's working now. found George Smart's blog + sane website.

1) sudo apt-get install xsane sane libsane-extras sane-utils netpbm libusb
2) download the firmware:'Esfw41.bin'
3) sudo cp -v Esfw41.bin /lib/firmware/esfw41.bin 
4) add 'firmware /lib/firmware/esfw41.bin' to '/etc/sane.d/snapscan.conf' 
5) find the scanner:
   lsusb
   sane-find-scanner
6) find the device:
    scanimage -L
    In my case, it's 'snapscan:libusb:001:005'
7) test it:
    scanimage -d snapscan:libusb:001:005 --format pnm > out.pnm
8) convert it to jpg:
    pnmtojpeg out.pnm > out.jpg
9) done.  Epson package(iscan) looks not a must, neither does X. maybe xsane either.

Thanks for your Crouton making a cheap chromebook a full-functional linux box.

**Comment by dnschneid** [comment]
Sweet!  Maybe add that to the wiki?
