### ISSUE TITLE
Conflicts and issues with -desktop targets

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1408]
The -desktop targets aren't cleanly installing in many simple cases.  Need to fix the following:

* xfce-desktop: /etc/skel/.xscreensaver modifications conflict with xubuntu-default-settings
and xubuntu-desktop.  Maybe an apt override would fix this?  FWIW the two packages are both trying to do the same default-blank modification that we do.
* gnome-desktop, unity-desktop: requires network-manager.
* lxde-desktop: requires network-manager-gnome

We of course don't want NM running because it's extremely misleading/conflicting, so perhaps a fake package (via equivs) would do the trick and hopefully not break everything...

**Comment by DennisLfromGA** [comment]
- I hadn't run in to issue 1, or it hasn't affected me as far as I could tell.
- I've run in to issues 2 & 3, I got around it by installing the vanilla target 1st, then going in to the chroot and installing the network-manager, then exiting the chroot and installing the desktop target. 
  Having the network-manager installed poses no problem in the chroots I've done this on, it shows up in the task bar with a red X through it and when you hover over it, it says it's not running.

**Comment by dnschneid** [comment]
Yeah, but red X's on very standard utilities scare people.  I'm brewing something in the fixdesktop branch.

**Comment by DennisLfromGA** [comment]
They don't scare me none ;)

**Comment by tedm** [comment]
I've always run into conflicts in the top bullet, on ARM with xfce, with the .xscreensaver conflicting with the default settings of the host's screen settings. I think an "apt-get remove xscreensaver" would prevent a lot of folks with dead or black screens, and the folks who do want xscreensaver can still add it, and those users should be aware that Chromium OS owns init process 1, so unless you manipulate powerd and other Chromium OS screen / power settings, there will be conflict with chroot unique settings, just like with network settings.

**Comment by cefn** [comment]
I have encountered this issue with sudo sh ~/Downloads/crouton -r trusty -t lxde-desktop,extension

How do I workaround without installing an extra desktop (and utilities, configuration) that might confuse or conflict with lxde-desktop?

A command which enables the install of a desktop ignoring one of its dependencies would be useful to enable a manual intervention and then resume the build.

It reports...
The following packages have unmet dependencies:
 lubuntu-desktop : Depends: network-manager-gnome but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in trusty
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by cefn** [comment]
By the way, the workaround at https://github.com/dnschneid/crouton/issues/1366 is not functional for me, as it's impossible to enter the chroot with the UID 1000 error, preventing the negotiation of a user shell. I'll try without any desktop, entering the chroot, installing network-manager, then upgrading to add the desktop.

**Comment by tedm** [comment]
@cefn just use lxde for your target.

**Comment by cefn** [comment]
I updated my comment above with a detailed walkthrough of the steps which worked, thanks.

**Comment by dnschneid** [comment]
For reference, if you get the uid 1000 error, you can always log in as root via `sudo enter-chroot -u root`.  And if even THAT doesn't work, you can get a non-login shell via `sudo enter-chroot -x`, which is a lot like setting `init=/bin/sh` on a broken system.

**Comment by dnschneid** [comment]
xubuntu-desktop doesn't work with xephyr, as it requires xorg.  I don't think I'll fix this, as xephyr will be dead soon.

**Comment by dnschneid** [comment]
OK, stuff should be working now (sans xephyr-induced issues).
