### ISSUE TITLE
URLs not opening from other apps

### ISSUE THREAD

**Issue by nashtag** [dnschneid/crouton#1409]
So I'm trying to setup various apps (like Grive) and they need to be able to open a URL up in a browser, but it seems to be broken. My guess is that it has something to do with the crouton chrome extension that I have installed. That tries to open URLs in Chrome OS, right? If so, then that's not working either. I've tried disabling that extension and rebooting, but that didn't help either. Googling doesn't seem to return anything, so I'm turning to this forum. Any help would be much appreciated.

**Comment by nashtag** [comment]
Sorry.. just re-read the readme and realized I need to provide this info:

crouton: version 1-20150206191439~master:3401dc49
release: trusty
architecture: amd64
targets: extension,core,cli-extra,chrome,keyboard,unity
host: version 6457.94.0 (Official Build) stable-channel swanky

**Comment by nashtag** [comment]
Ok, so I was playing around with it some more and I got this error message:

"please start google chrome as a normal user. to run as root, you must specify an alternate --user-data-dir for storage of profile information"

So I figured I needed to change to exec of chrome.. but how? I can't seem to figure that part out. Also, I've noticed this error message quite a bit: "Gtk-Message: Failed to load module "canberra-gtk-module"". From Googling, I think that has something to do with the 64bit version vs x86, but every solution I've tried doesn't get rid of the error.

**Comment by dnschneid** [comment]
It sounds like you have Chrome installed (which takes priority over the crouton URL passing stuff), but it also sounds like you're somehow running your desktop environment as root (which is bad).  What do you get for the output of `ls -l ~/.ICEauthority`?

**Comment by nashtag** [comment]
-rw------- 1 rdnashjr rdnashjr 998 Feb 14 20:41 /home/rdnashjr/.ICEauthority

**Comment by nashtag** [comment]
I followed the guide in the readme.. didn't do anything to explicitly run the desktop as root. How do I not do that?

**Comment by dnschneid** [comment]
No, it seems like you're OK on that front.  Can you launch chrome from the applications menu?

**Comment by nashtag** [comment]
Yes, and it opens with my preferences remembered (gmail account, extensions installed, etc). After Googling a bit, I tried gedit-ing /usr/bin/google-chrome and added --user-data-dir to the end of it. That seemed to at least allow a link to be opened, however it's in a separate, new window that doesn't seem to have any "knowledge" of my preferences.

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
