### ISSUE TITLE
xiwi fails because M42's /proc/pid is now root-only

### ISSUE THREAD

**Issue by sgosnell** [dnschneid/crouton#1411]
Updated ChromeOS to 42.0.2302.4 (Official Build) dev (64-bit) today.  Now running "sudo startxfce4" hangs at a blank black screen.  The following goes on ad infinitum:
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
awk: read error (Permission denied)
popen2: child exited with status 2
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
awk: read error (Permission denied)
popen2: child exited with status 2
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
awk: read error (Permission denied)
popen2: child exited with status 2

I have to exit with Ctrl-c.  I've downloaded the latest crouton script and updated three times, with no change.  Looks like a permissions issue somewhere.  It was running fine until the ChromeOS update, and then this.  I'm running Debian Jessie, btw, NOT Ubuntu.

**Comment by dwploc** [comment]
Ditto, same setup plus xiwi. Black screen presented.

Dave Ploch

Voice: 636-336-6289

**Comment by bf5man** [comment]
Similar problem for me, a black screen after updating chrome os to 42:
    write_image:  

    Cannot find shm, moving on...
    awk: fatal: error reading input file `/proc/2349/maps': Permission denied
    popen2: child exited with status 2
    find_shm: Error running helper.

**Comment by pdbennett** [comment]
Same Issue

Ubuntu trusty/xfce/xiwi chroot

Version 42.0.2302.4 dev (64-bit)
Platform 6783.1.0 (Official Build) dev-channel peppy
Firmware Google_Peppy.4389.89.0

**Comment by denzeljiang** [comment]
Same here.

```
awk: read error (Permission denied)
popen2: child exited with status 2
find_shm: Error running helper.
```
ubuntu trusty -t xiwi  `with awesome wm`
Version 42.0.2302.4 dev (64-bit)
Platform 6783.1.0 (Official Build) dev-channel peppy
Firmware Google_Peppy.4389.89.0

**Comment by dnschneid** [comment]
I'm looking into it now.

**Comment by dnschneid** [comment]
Yeah, the maps file and the fd directory in /proc/$PID are now owned by root instead of chronos.  This is, of course, a totally reasonable change, but crouton will have to accommodate.

**Comment by dnschneid** [comment]
OK, the short-term super-insecure solution is to make croutonfbserver setuid root:
`sudo chmod +s /usr/local/bin/croutonfbserver`
That should get xiwi working again.

A proper solution would be to either rearchitect how we find the framebuffer shm, or make croutonfindnacl a very carefully-implemented setuid binary that returns an open fd via sockets.

**Comment by dnschneid** [comment]
The latest crouton has the workaround.

**Comment by bf5man** [comment]
I can confirm the fix, everything went back to normal, thanks David.

**Comment by drinkcat** [comment]
Instead of bind mounting /proc, could we mount another instance of /proc in the chroot, with relaxed permissions?

**Comment by dnschneid** [comment]
I think the restrictions are in the kernel, not in the mount options.  Unless you have something in particular in mind?

**Comment by drinkcat** [comment]
Ah, I was hoping it would be some kind of mount option...

**Comment by drinkcat** [comment]
Took me a while to find the culprit: https://codereview.chromium.org/901683003/ ... Now that doesn't really help, I don't think we can reset PR_SET_DUMPABLE from another process...

Will dig further, but it appears a setuid daemon is probably the only solution...

**Comment by DennisLfromGA** [comment]
Closing, please re-open if this issue is still a concern.
