### ISSUE TITLE
-su: 1: kde: not found ???

### ISSUE THREAD

**Issue by Polv89** [dnschneid/crouton#1412]
Why i have this message?
i've used the right instructions, step by step
Thanks a lot

ps. is possible to install ubuntu or linux mint in cinnamon edition?

**Comment by DennisLfromGA** [comment]
What instructions; do you have a link to them?
What are you entering on the command line?
----
Yes to Ubuntu (... -t unity ...) or (...-t unity-desktop ...)
No to Linux Mint or Cinnamon ( at the moment ).

**Comment by Polv89** [comment]
Now it works.. I have installed cinnamon DE on distro (14.04) through PPA, is not possible to use it?

**Comment by dnschneid** [comment]
It requires some hacks that have long since been removed from crouton.  See #832
