### ISSUE TITLE
Is it possible to disable xiwi for a while?

### ISSUE THREAD

**Issue by AlexSane** [dnschneid/crouton#1414]
I have a chroot with xiwi and xfce installed. Is it possible to start xfce without xiwi support without uninstalling it from the chroot?

**Comment by DennisLfromGA** [comment]
If you already have 'xorg' or 'xephyr' installed, then *yes*, just kick it off with the '-X' option, something like this:

`sudo startxfce -X [xorg or xephyr]`

If neither of those work, then you may have to install them - 'xephyr' on an ARM machine, 'xorg' on others, using:

`sudo ~/Downloads/crouton -t [xorg or xephyr] -n [chrootname] -u`

**Comment by AlexSane** [comment]
Trying to update to install xorg, but get the following error:
```
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
```

**Comment by DennisLfromGA** [comment]
@AlexSane - That looks like 'apt-get' was having problems with a package.
Do you have more details? You could try 'sudo enter-chroot' and try to finish the install and see what's failing...

**Comment by midnightradio** [comment]
Have a look at a question #1276 , updating x11 would take effect.

```sudo sh -e crouton -r your_crouton_name -u -t x11```

**Comment by AlexSane** [comment]
It seems `precise` could not be updated (even just `crouton -u -n precise` failed with error mentioned above). I have to recreate a chroot using `trusty` release and now all works like a charm: `sudo startxfce4` runs in xiwi, `sudo startxfce -X xorg` runs in full screen.

**Comment by DennisLfromGA** [comment]
Cool, glad it's working. 
I've had to move on from my 'precise' chroot(s) too...

**Comment by tedm** [comment]
updating precise / xfce on the arm is working for me on the stable channel with current crouton, xephyr is in the xmethods file. I'm installing a trusty / xfce chroot now.

Dennis, what issues are you having with precise on the intel platform? Is it switch xmethod target related?

**Comment by tedm** [comment]
new xfce trusty chroot on arm works fine as well (/etc/crouton/xmethod is xephyr), will update it tomorrow or so.

**Comment by DennisLfromGA** [comment]
> Dennis, what issues are you having with precise on the intel platform? Is it switch xmethod target related?

@ted, 
I fibbed a little when I said "I've *had* to move on from my 'precise' chroot(s) too..."
Actually, I just wanted to try the newer releases, I live on the *edge* ;)

**Comment by tedm** [comment]
@DennisLfromGA I figured that ;) I don't see the big allure to the newest release of the month, the work I do, and teach to my students is 99% at the bash command prompt. Our linux boxes in the home are running on low power cpus, one with fedora 17, the other mint 10.x. I used to use arch on a 3W pogo device, but the arch developers stopped supporting the device and it's low memory. So is there anything in 14.04 worth looking at before deleting it? I don't game or torrent, so if that's where the features are, I'm not really missing anything. I realize I'll have to move to it someday, but I want to check out elementary and some others when I get time. But I think, even if elementary gets stable on the arm with Crouton, the arm is possibly underpowered for its graphics, plus it has that weird browser that would need replacing immediately.

**Comment by joerosato** [comment]
Is there a way to save my precise without just installing a new trusty chroot? I headed here to disable xiwi but ran into the same issues as @AlexSane. I'm OK with dropping xiwi, I would rather my redshift was working again and xiwi upgrade made it stop working. On acer c720.

**Comment by AlexSane** [comment]
@joerosato BTW, I tried to update my precise chroot to trusty using `crouton -u -r trusty` but had no luck. But I didn't check whether my precise chroot works after this unlucky update.

**Comment by joerosato** [comment]
@AlexSane what targets did you install trusty with? I can assume from what you said but figured I'd ask.. if I'm going the same route would like to mirror your situation.

**Comment by AlexSane** [comment]
xiwi, touch, xfce

**Comment by Watney** [comment]
@alexsane if you didn't have any luck with your upgrade to trusty, you might see if [the Wiki](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release) is any help.
