### ISSUE TITLE
Standby Issues

### ISSUE THREAD

**Issue by spillz** [dnschneid/crouton#1416]
I am running crouton on a Acer 720p Chromebook using the Ubuntu 14.04 unity target runnign in fullscreen mode (i.e. no xiwi). When I go into standby mode from Ubuntu, then open the laptop up again it:

1. Usually shows no lockscreen
2. Defaults back to a very bright brightness setting
3. Loses keyboard settings set with xmodmap

Are these known limitations or am I just doing something wrong? Related to 3, what is the best way to modify the chroot config so that the xmodmap settigns gets set automatically at startup?

**Comment by dnschneid** [comment]
1. You probably need to install a screensaver or configure the unity power manager settings
2. Likely #407 
3. Likely #953, which has a workaround.
