### ISSUE TITLE
reboot on opening lid.

### ISSUE THREAD

**Issue by midnightradio** [dnschneid/crouton#1417]
Hi, 
I can read some are experiencing the same problem as I do but there's no issue only for the problem in spite of the severity. 

My pixel sometimes reboots on opening the lid and it only happens when I was running enter-chroot or startxfce4 before I close the lid. It's too risky for loosing all sessions and data that I have been working on and also tricky to reproduce though I had try to avoid several things I suspected not to experience it again but it continues to happen once or twice a week.

Here's what I have tried to avoid with no specific ground but I felt like the issue have been repeated under those circumstances,  
* closing the lid while I'm working on linux desktop environment (xfce)   
* not leaving a tab running enter-chroot (just for shell environment) or startxfce4 focused before closing the lid.
* opening the lid when the battery is almost running out.
* closing the lid with leaving Files app opened and Downloads focused

So I always tried to
* move focus to one of other tabs of chrome native browser except the crosh tab before closing the lid
* connect a charger before opening the lid
* close Files app before closing the lid

I'm not sure about xscreensaver does matter as some have been mentioning even though I move focus to chrome native browser before closing the lid. Anyway I have no screen saver installed and I'm still meeting the problem.

I think we need to gather some experiments to find out under what circumstance it happens.

crouton: version 1-20150127081428~master:e1bcac2b
release: trusty
architecture: amd64
targets: x11,keyboard,audio,cli-extra,xiwi,extension,touch,xfce
host: version 6457.83.0 (Official Build) stable-channel link

Any other information needed, just ask.

**Comment by dnschneid** [comment]
I wonder if this is similar to #1429.  Likewise, (and sorry for the blatant copy-paste), could you please repro the issue, then on reboot, run `generate_logs` in the crosh shell and file a (separate) bug on crbug.com, and link it here? It's probably a kernel panic that we need to make the Chromium OS team aware of.

**Comment by midnightradio** [comment]
Good to know I'm one of a few. Fortunately(?) I just met the problem again the log is ready to be filed.

**Comment by midnightradio** [comment]
Never happened the issue again for two weeks. I guess it was not related to crouton itself but to others like chrome os or some extensions of it.
