### ISSUE TITLE
VirtualBox completely reboots computer when using "Bridged" mode

### ISSUE THREAD

**Issue by robbie0630** [dnschneid/crouton#1420]
I like to use the VirtualBox networking feature in Bridged mode because a) it's the fastest, and b) it reduces hassle when transferring files, and allows sshing without the hassle of opening ports. (DO NOT: tell me to just use NAT, because I only have to forward two ports. I specifically want bridged mode.)

**Comment by dnschneid** [comment]
I won't tell you to just use NAT, but I will suggest that you not use a known buggy feature: #985

**Comment by robbie0630** [comment]
@dnschneid I saw this, and I would think someone would have made a fix for it. It was at the bottom, and nobody seemed to have acknowledged that.

**Comment by dnschneid** [comment]
There aren't any fixes at the moment, but if you want to dig into it and report back, I'm sure it'd be much appreciated.

**Comment by netdata** [comment]
@dnschneid I would like to give it a go to troubleshoot this issue.
DO you have any direction where to look, Really would like to use briding on my machines
