### ISSUE TITLE
Feature request: run X windows in separate chrome tabs

### ISSUE THREAD

**Issue by portaloffreedom** [dnschneid/crouton#1422]
I want to know if, through the extension, is possible to run a single window as a chrome tab instead of a full environment.

Something similar to what happens using the "host-x11" command, but instead of using the X11 protocol, create a chrome tab (xiwi) with only that window inside. Is it already there or is it possible to implement?

**Comment by dnschneid** [comment]
Actually, almost here.  It's in the xiwi-app branch.  Once #1415 is merged, I'll be merging the xiwi-app stuff as well.
