### ISSUE TITLE
crouton xfce lockscreen

### ISSUE THREAD

**Issue by william555** [dnschneid/crouton#1423]
I have a Asus chromebox and added sudo sh ~/Downloads/crouton -r trusty -t xfce.  My problem is when logged into crouton, if I step away and come back I have a lockscreen that I can't get out of.  I already removed xscreensaver and disable power manager on auto start list in Xubuntu with no effect.  Also in power manager settings, extended, I'm not able to uncheck "lock screen when going for suspend/hibernate"

**Comment by tedm** [comment]
try:

apt-get purge xscreensaver or apt-get remove --purge xscreensaver

and then apt-get autoremove

With trusty, check if any other screensavers are active or installed such as: gnome-screensaver 3.6.1-0ubuntu13 and either keep one, or let Chrome handle your screen management.

**Comment by william555** [comment]
Thanks, all better now.
