### ISSUE TITLE
what to do now that ChromeOS no longer supports ext2/3/4 ?

### ISSUE THREAD

**Issue by faddah** [dnschneid/crouton#1424]
hi all (& @dnschneid ),

there have now been several articles talking about how [ChromeOS/Chromebooks no longer support ext2/3/4 drive formats](http://www.reddit.com/r/chromeos/comments/2izce2/chromeos_will_no_longer_support_ext234_on) (why google made this bonehead decision on a linux based system is beyond me).

my question — my SD Card i was using to switch boot into Ubuntu Linux on the Acer C720P Chromebook gave up the ghost and won't work anymore. i broke down and bought a more stable 32 GB usb 3.0 stick for this purpose. what, if anything, do i use to format my usb 3.0 stick into ext4?? i keep finding articles just saying ext2/3/4 isn't supported on ChromeOS anymore or telling me to use gparted to do it, but if i'm not in vanilla linux (not ChromeOS), i can't run gparted. gak! what do i use to format my usb 3.0 stick and then run the crouton install again? please advise.  thank you.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by dnschneid** [comment]
That's a very old article.  The decision has been [reversed](https://code.google.com/p/chromium/issues/detail?id=315401#c124) and everything's fine.

**Comment by faddah** [comment]
sorry, didn't know. thanx, @dnschneid .
