### ISSUE TITLE
Xiwi connection was shutdown suddenly.

### ISSUE THREAD

**Issue by monaka** [dnschneid/crouton#1425]
Hello,

My crouton extension was suddenly closed.

Log messages are like this.
```
find_shm: Invalid signature, fetching new shm!
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
popen2: child exited with status 1
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
```

There seems X is still running but I can't reconnect.
Chrome extension shows this error message.
```
ERROR: Connection failed (code: -2).
Disconnected, please close the window.
```

The result of croutonversion on my machine is:
```
crouton: version 1-20150214193521~master:fe8e6dee
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,keyboard,extension,xfce
host: version 6457.94.0 (Official Build) stable-channel wolf 
```

It's a first time I met this issue.
Xiwi was running fine for an hour before unexpected window close.
After closing Crouton by Ctrl-C and restarting, The X session starts up fine.

**Comment by DennisLfromGA** [comment]
I've had that happen occasionally, don't know what causes it.
Even though it won't connect, I've still been able to access the chroot via
the 'switch window / F5' key.

On Fri, Feb 20, 2015 at 12:02 AM, Masaki Muranaka <notifications@github.com>
wrote:

> Hello,
>
> My crouton extension was suddenly closed.
>
> Log messages are like this.
>
> find_shm: Invalid signature, fetching new shm!
> popen2: child exited with status 1
> find_shm: Error running helper.
> write_image: Cannot find shm, moving on...
> popen2: child exited with status 1
> find_shm: Error running helper.
> write_image: Cannot find shm, moving on...
>
> There seems X is still running but I can't reconnect.
> Chrome extension shows this error message.
>
> ERROR: Connection failed (code: -2).
> Disconnected, please close the window.
>
> The result of croutonversion on my machine is:
>
> crouton: version 1-20150214193521~master:fe8e6dee
> release: trusty
> architecture: amd64
> xmethod: xiwi
> targets: xiwi,xorg,keyboard,extension,xfce
> host: version 6457.94.0 (Official Build) stable-channel wolf
>
> It's a first time I met this issue.
> Xiwi was running fine for an hour before unexpected window close.
> After closing Crouton by Ctrl-C and restarting, The X session starts up
> fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1425>.
>



-- 
*DennyL@GMail*

**Comment by dnschneid** [comment]
When you hit the issue, try opening up another crosh tab and running `sudo enter-chroot env DISPLAY=:1 croutonfbserver :1` and see if you can bring up the window again via the extension.

It's possible you're hitting 5d8c035e8c9c5c9157fea821715c444e6d331778 or some other thing that's causing croutonfbserver to segfault.  If the above works but the thing dies again, try making it `croutonfbserver -v2 :1`, reproduce, and provide us the logs.

**Comment by DennisLfromGA** [comment]
Closing, please re-open if this issue is still a concern.
