### ISSUE TITLE
Screen goes black after starting KDE

### ISSUE THREAD

**Issue by ajshell1** [dnschneid/crouton#1426]
The title says most of it.
After I type in "Shell" and then "sudo startkde", the KDE boot-up screen appears, the hard drive icon appears in that sequence that plays when KDE boots up, but then the screen goes black.  Ctrl-alt-shift-back/forward do nothing. I know that my Toshiba Chromebook 2 is still working alongside the dark KDe, because I started a Youtube video before typing in "sudo startkde",  and the video continued to play normally after starting KDE and getting the black screen (well, I know the audio played ok). 
How do I fix this? I would be glad to provide more anymore information that would help you help me.
Thank you in advance for helping me uphold my belief that random people on the internet are the best tech support.

**Comment by dnschneid** [comment]
Did you intend to close the bug?
