### ISSUE TITLE
possible to update the ubuntu linux kernel (unity ui) within crouton? yes? never?

### ISSUE THREAD

**Issue by faddah** [dnschneid/crouton#1427]
hi @dnschneid @DennisLfromGA, et al.,

i want to run vagrant/virtual box vms within my crouton ubuntu linux 14.04 lts (unity ui). however... ```unanme -a``` tells me i'm on linux kernel 3.8.11 (very old kernel). 

vagrant, the first time you edit the vagrant file and attempt to boot the VM, requires to run the vbox setup, which runs a Make, which needs the kernel source files somewhere in ```/usr/src``` and point to them using ```export KERN_DIR=...``` etc.. i can't find for the life of me source/header files for linux kernel 3.8.11 that work. i tried the instruction i found for updating the linux kernel in ubuntu using *.deb packages, ran those instructions and restarted twice. still no love, still comes up with linux kernel 3.8.11 and vbox setup will not compile.

so is there any way to update the kernel within my ubuntu linux install (it's on an external USB 3.0 stick on my Acer C720P Chromebook). everything else in ubuntu linux 14.04 lts unity runs great. does the crouton kernel share the same kernel with chromeos and that's why it can never change? can anything be done here to get vagrant/virtualbox running for web developement i want to do within linux?

please advise.

thank you.

best,

—  faddah 
     portland, oregon, u.s.a.

**Comment by dnschneid** [comment]
There's no virtualization involved, so crouton uses whatever kernel is active on the system.  The kernel you have installed in crouton just eats disk space.  Not a lot you can do about updating it other than booting Linux directly (e.g. chrubuntu or seabios).

Vagrant won't work: #1194 
Virtualbox: https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)
