### ISSUE TITLE
xiwi: Setting a keyboard layout in Chromium OS with dead keys (e.g. US Intl) leads to lost key events

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1428]
> I think it's fixable, as the key code appears when the key is lifted

From #1339

**Comment by drinkcat** [comment]
Actually I think this is a crosbug, only on Chromium OS on X11. Last time I checked, Chromium OS on freon behaved correctly, see https://code.google.com/p/chromium/issues/detail?id=425156#c16 .
