### ISSUE TITLE
Chrome keeps randomly rebooting when Crouton is mounted

### ISSUE THREAD

**Issue by connorjolley** [dnschneid/crouton#1429]
It seems to be a random occurrence that started over the last few days. I will mount crouton and have it running while I watch video in the Chrome environment and the Chrome system will randomly reboot. I use crouton to run torrents, so Transmission will be running in xfce. I'm not sure if the issue is related to the video player in Chrome. It happened once when I adjusted the volume on my keyboard but that may have just been coincidence. I'm not sure how to go about troubleshooting the issue or providing relevant logs to look for bugs.

Can any one advise how I might find information to provide here to see if there is a bug? Obviously I never get a chance to see what is happening in crosh because the system reboots and the previous shell information is gone when it reboots.

crouton: version 1-20150214193521~master:fe8e6dee
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6457.94.0 (Official Build) stable-channel swanky

**Comment by dnschneid** [comment]
Could you please repro the issue, then on reboot, run `generate_logs` in the crosh shell and file a bug on crbug.com, and link it here?  It's probably a kernel panic that we need to make the Chromium OS team aware of.

**Comment by midnightradio** [comment]
#1417 never happened while running something with a lid opened .

**Comment by connorjolley** [comment]
I updated the chroot as per the wiki after reporting this issue - I think the issue occurred one more time after that then it was fine for days. However, it just happened again so I followed the instructions above as requested.

Bug report: https://code.google.com/p/chromium/issues/detail?id=461745

**Comment by dnschneid** [comment]
Is your chroot mounted on external media?

**Comment by connorjolley** [comment]
No. Mounted internally. I just did a very standard install.

**Comment by DennisLfromGA** [comment]
Closed. Please re-open if this issue is still a concern.
