### ISSUE TITLE
No Volume bar on LXDE (or Brightness bars)

### ISSUE THREAD

**Issue by pepper311** [dnschneid/crouton#1431]
Hi THere,

I have trusty LXDE installed on Acer CB3-111

Afrer running the

 sudo sh -e ~/Downloads/crouton -r trusty t keyboard -u

I now have the brightness and volume buttons working but there is no visual progress bar on the GUI.

I mean that the brightness goes up and down but there is not a visual percentage indicator while this is happening.  

When I use my XFCE chroot I do not have this problem.  What can I do to fix this?  Its a shame because I really enjoy LXDE

**Comment by pepper311** [comment]
Disregard and close the ticket.  I just went back to XFCE and deleted the chroot with LXDE.

LXDE runs just fine on this machine so no need to get anymore lightweight (and dont want to miss out on any extra features)

**Comment by pepper311** [comment]
I am really happy with Crouton.  Else I could not play my wmv and certain other video formats that ChromeOS will not support.  (But now I can with VLC) 

Also it will be nice to just hook up a printer to the USB cable without all this cloud print nonsense.  

5 thumbs up for Crouton (and Ubuntu Trusty with XFCE)

**Comment by dnschneid** [comment]
Glad it's working for you.
