### ISSUE TITLE
Using JACK for recording

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1434]
I want to record my game with my headset mic, and the first method (using PulseAudio) nearly blew my ears out. I want to uninstall PulseAudio to get JACK, but I'm not sure if it is safe. Here: http://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/#recording-game-audio-and-microphone-at-the-same-time

**Comment by dnschneid** [comment]
That should be fine, although you may have to manually start JACK after installation.

**Comment by firestar115** [comment]
Do I look at the documentation for that? QJackCtl didn't work because of
ALSA whatever.

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by firestar115** [comment]
Get this log:
```
15:56:42.653 Patchbay deactivated.
15:56:42.655 Statistics reset.
15:56:42.683 Could not open ALSA sequencer as a client. ALSA MIDI patchbay will be not available.
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied
15:56:50.090 D-BUS: Service is available (org.jackaudio.service aka jackdbus).
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
15:57:54.863 D-BUS: JACK server could not be started. Sorry
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Mon Feb 23 15:57:54 2015: Starting jack server...
Mon Feb 23 15:57:54 2015: JACK server starting in realtime mode with priority 10
Mon Feb 23 15:57:54 2015: ERROR: Cannot lock down 82274202 byte memory area (Cannot allocate memory)
Mon Feb 23 15:57:54 2015: ERROR: control open "hw:0" (No such file or directory)
Mon Feb 23 15:57:54 2015: ERROR: control open "hw:0" (No such file or directory)
Mon Feb 23 15:57:54 2015: creating alsa driver ... hw:0|hw:0|1024|2|44100|0|0|nomon|swmeter|-|32bit
Mon Feb 23 15:57:54 2015: ERROR: control open "hw:0" (No such file or directory)
Mon Feb 23 15:57:54 2015: ERROR: ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
Mon Feb 23 15:57:54 2015: ERROR: Cannot initialize driver
Mon Feb 23 15:57:54 2015: ERROR: JackServer::Open failed with -1
Mon Feb 23 15:57:54 2015: ERROR: Failed to open server
Mon Feb 23 15:57:56 2015: Saving settings to "/home/firestar115/.config/jack/conf.xml" ...
15:58:00.551 Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```
Returns error.

**Comment by firestar115** [comment]
Running:
```
$ aplay -D pcm.jack ~/Downloads/Black\ Mesa\ EBS.mp3 
jack_client_new: deprecated
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
aplay: main:722: audio open error: No such file or directory
```

**Comment by dnschneid** [comment]
Try killing of cras (`sudo stop cras` in the crosh shell), then add yourself to the audio-hw group in crouton (sudo adduser $USER audio-hw), exit the chroot, enter the chroot, and try again.

**Comment by firestar115** [comment]
adduser: The group `audio-hw' does not exist.

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by dnschneid** [comment]
Argh, hwaudio, sorry.

**Comment by firestar115** [comment]
It kind of worked...
https://www.youtube.com/watch?v=OMOlU5ajP9E

**Comment by firestar115** [comment]
WAIT! I CAN'T HEAR ANY SOUNDS ON MY CHROMEBOOK! :anguished:

**Comment by dnschneid** [comment]
Yes, when you tell crouton to take over the hardware audio device, Chromium OS audio will stop working.  You need to stop JACK and then do a `sudo start cras` in Chromium OS to get it back.

**Comment by firestar115** [comment]
Worked!
