### ISSUE TITLE
Precise or Trusty?  better choice for Crouton

### ISSUE THREAD

**Issue by pepper311** [dnschneid/crouton#1435]
Is precise more stable?  I use it for my desktop and was wondering if anyone could comment on how it will run via Crouton on an HP Chromebook 14 (2ng gen with Celeron and 4GB Ram)

with XFCE

**Comment by tedm** [comment]
both should be fine. It's easy to just create 2 xfce chroots, one with each release, then delete the one you don't want to keep. By default, without specifying '-r trusty' , the default chroot release is precise, as is the chroot name, unless a name is specified with '-n mychrootname'

**Comment by divx118** [comment]
I would go for the trusty release, certainly on the HP chromebook 14. It will be just as stable as precise.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
