### ISSUE TITLE
Unusable space on Toshiba Chromebook 2

### ISSUE THREAD

**Issue by ajshell1** [dnschneid/crouton#1436]
When I bought my Toshiba Chromebook 2, I saw that it had a 16 GB SSD. When I used chrome://quota-internals in the ChromeOS (which is supposed to tell you how much space is left), it says that I only have 9.73 or so Gigabytes. I realize that I wasn't going to get exactly 16 GB when I got it, but that's quite a bit of space. So after trying to copy a 400 MB file from a flash drive onto the drive without realizing that I had less than 400 MB left (according chrome://quota-internals), I poked around a little. Here are some screenshots I took of gparted and dolphin. I want to maximize the amount of space I have for Kubuntu. 
http://imgur.com/tRPZvKU
I'm not an expert on partitoning, but I think that this is fairly screwed up.
http://imgur.com/aE6FEfW
http://imgur.com/802i7Uk
As you can see, only 4 KB of 3 GiB is used there. When I normally only have 9.73 GB, 3 GB is a lot for me. To me, every byte counts.

I'd like to thank you all for your help, and to thank the developers for making chromebooks useful.

**Comment by dnschneid** [comment]
Root-A/Root-B is key to how Chromium OS's auto-updates work (it loads a new system image on the other and then switches which one it boots from, falling back to the previous if it fails).  So you're not getting that back.

The 3GB partition you see is actually a tmpfs partition that should probably be smaller, but it's memory-backed and doesn't actually touch the SSD.

So there's really no space to be recovered from the SSD, unfortunately.  You'll need to use external storage to make up the difference.

**Comment by ajshell1** [comment]
Okay. Thank you. I'll be getting a 1 TB hard drive soon, so I have a feeling that my storage problem will be not be a problem for much longer.
Once again, thank you for making chromebooks useful.
