### ISSUE TITLE
Trouble Installing Ubuntu(Trusty Tahr):  'utmp' no such file or directory

### ISSUE THREAD

**Issue by horrigan97** [dnschneid/crouton#1438]
I have tried twice to install ubuntu in the last couple of days, and both times while installing I have received errors relating to the existance of 'var/run/utmp/'

Command Used: <code>sudo sh ~/Downloads/crouton -r trusty -t audio,core,chrome,cli-extra,extension,gtk-extra,keyboard,unity,unity-desktop,x11,xephyr,xiwi,xorg</code>

Here is the first error I received:

<code>Preparing to unpack .../libprocps3_1%3a3.3.9-1ubuntu2.2_amd64.deb ...</code>
<code>Unpacking libprocps3:amd64 (1:3.3.9-1ubuntu2.2) over (1:3.3.9-1ubuntu2) ...</code>
<code>Preparing to unpack .../procps_1%3a3.3.9-1ubuntu2.2_amd64.deb ...</code>
<code>runlevel:/var/run/utmp: No such file or directory</code>
<code>initctl: Unknown job: procps</code>

Another Example:

<code>Installing new version of config file /etc/init/udev-fallback-graphics.conf ...</code>
<code>runlevel:/var/run/utmp: No such file or directory</code>
<code>udev stop/waiting</code>
<code>udev start/running, process 2025</code>
<code>Removing 'diversion of /bin/udevadm to /bin/udevadm.upgrade by fake-udev'</code>
(Many more occur, all of them mention no file/directory: /var/run/utmp)
Possibly an issue with the install script?

<code>cat /etc/lsb-release</code>:
<code>CHROMEOS_AUSERVER=https://tools.google.com/service/update2</code>
<code>CHROMEOS_BOARD_APPID={9D137383-EB72-4BA9-A523-91AC0853F8AD}</code>
<code>CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}</code>
<code>CHROMEOS_DEVSERVER=</code>
<code>CHROMEOS_RELEASE_APPID={9D137383-EB72-4BA9-A523-91AC0853F8AD}</code>
<code>CHROMEOS_RELEASE_BOARD=parrot-signed-mp-v3keys</code>
<code>CHROMEOS_RELEASE_BRANCH_NUMBER=43</code>
<code>CHROMEOS_RELEASE_BUILD_NUMBER=6680</code>
<code>CHROMEOS_RELEASE_BUILD_TYPE=Official Build</code>
<code>CHROMEOS_RELEASE_CHROME_MILESTONE=41</code>
<code>CHROMEOS_RELEASE_DESCRIPTION=6680.43.0 (Official Build) beta-channel parrot </code>
<code>CHROMEOS_RELEASE_NAME=Chrome OS</code>
<code>CHROMEOS_RELEASE_PATCH_NUMBER=0</code>
<code>CHROMEOS_RELEASE_TRACK=beta-channel</code>
<code>CHROMEOS_RELEASE_VERSION=6680.43.0</code>
<code>GOOGLE_RELEASE=6680.43.0</code>

I update the crouton file, still no change. Also if I use the chroot(which i deleted), i encounter many errors with configuring mysql and phpmyadmin

**Comment by horrigan97** [comment]
I forgot to add, the final, and most prominent error is this:
<code>Processing triggers for libc-bin (2.19-0ubuntu6.5) ...</code>
<code>Processing triggers for initramfs-tools (0.103ubuntu4.2) ...</code>
<code>Installing target unity-desktop...</code>
<code>Reading package lists... Done</code>
<code>Building dependency tree       </code>
<code>Reading state information... Done</code>
<code>Package 'network-manager' is not installed, so not removed</code>
<code>Package 'xorg' is not installed, so not removed</code>
<code>Some packages could not be installed. This may mean that you have</code>
<code>requested an impossible situation or if you are using the unstable</code>
<code>distribution that some required packages have not yet been created</code>
<code>or been moved out of Incoming.</code>
<code>The following information may help to resolve the situation:</code>

<code>The following packages have unmet dependencies:</code>
<code> ubuntu-desktop : Depends: xorg but it is not going to be installed</code>
<code>                  Recommends: network-manager-gnome but it is not going to be installed</code>
<code>E: Unable to correct problems, you have held broken packages.</code>
<code>Failed to complete chroot setup.</code>
<code>Unmounting /mnt/stateful_partition/crouton/chroots/ladon...</code>

**Comment by dnschneid** [comment]
The udev errors are usually harmless, although in general you'll need to manually start mysqld and whatnot if you want to use them.

That last error is being tracked in #1408
