### ISSUE TITLE
screensaver and touchpad not working

### ISSUE THREAD

**Issue by BleakleyMcD** [dnschneid/crouton#1440]
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Feb 5 20:49:40 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4a144ca5-d25a-b44e-9a39-7c2f0e2b431b/PARTNROFF=1 hashtree=PARTUUID=4a144ca5-d25a-b44e-9a39-7c2f0e2b431b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b5dabdcb9ca428c18101c9531cd1de0e32a3491a salt=cbe45381f36c3151e158fb1796fd449db2d93a12221f9047422ba85d00f4fe14" noinitrd vt.global_cursor_default=0 kern_guid=4a144ca5-d25a-b44e-9a39-7c2f0e2b431b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed Feb 25 17:24:25 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
vesa: Ignoring device with a bound kernel driver

(Thunar:31725): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-panel:31727): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-session:31712): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfwm4:31723): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfsettingsd:31729): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfdesktop:31728): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-terminal:31730): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:31739): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:31743): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(polkit-gnome-authentication-agent-1:31752): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:31752): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfdesktop:31728): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:31728): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:31728): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(firefox:31760): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.

**Comment by dnschneid** [comment]
What do you mean by "not working"?  What's the output of `croutonversion`?

**Comment by intelligencer** [comment]
chronos@localhost / $ croutonversion
bash: croutonversion: command not found
chronos@localhost / $ 

the touchpad isn't responding in xfce to clicks or moving the cursor.

screen save just isn't showing up.

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Feb 5 20:49:40 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4a144ca5-d25a-b44e-9a39-7c2f0e2b431b/PARTNROFF=1 hashtree=PARTUUID=4a144ca5-d25a-b44e-9a39-7c2f0e2b431b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b5dabdcb9ca428c18101c9531cd1de0e32a3491a salt=cbe45381f36c3151e158fb1796fd449db2d93a12221f9047422ba85d00f4fe14" noinitrd vt.global_cursor_default=0 kern_guid=4a144ca5-d25a-b44e-9a39-7c2f0e2b431b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.2.log", Time: Wed Feb 25 17:28:20 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
vesa: Ignoring device with a bound kernel driver
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0

(xfwm4:2033): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(Thunar:2035): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
[dix] Elan Touchpad: unable to find touch point 0

(xfce4-panel:2037): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0

(xfce4-session:2021): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfdesktop:2041): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfsettingsd:2042): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:2048): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:2050): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(polkit-gnome-authentication-agent-1:2063): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:2063): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfdesktop:2041): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:2041): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:2041): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
[dix] Elan Touchpad: unable to find touch point 0
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.

(firefox:4086): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-terminal:4376): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-terminal:4376): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion `GDK_IS_WINDOW (window)' failed

**Comment by intelligencer** [comment]
Also now I'm not able to switch in and out of xfce with shift+ctrl+alt+--> 
I'm having to start a new shell each time I switch out.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
