### ISSUE TITLE
X on ARM fails after update

### ISSUE THREAD

**Issue by yisheng-on-linux** [dnschneid/crouton#1444]
Last night I did a crouton update to my Samsung ARM chromebook. I also noticed that chromeos said it had updated and rebooted, hoping for a nice new shiny experience.

Instead, I got the dreaded X not wanting to start failure. So, I went into /etc/crouton/xmethod and made sure xorg was there. I even tried various other possible entries. No luck.

I noticed that one of the errors was bin/X wasn't found. So, I updated again, specifically updating X11, xorg, and even tried xephyr. Each time, the updater said "X isn't available for ARM devices"!

It worked great till this update. What happened? And is it true X is not on ARM chromebooks any longer?

Running trusty...

**Comment by dnschneid** [comment]
The Samsung ARM chromebooks are supposed to be excluded from xorg.  Definitely a bug.

**Comment by dnschneid** [comment]
(In the meantime, update with `-t xephyr` and everything should be back to normal)

**Comment by yisheng-on-linux** [comment]
Thanks! Back in business! It works.

Off topic, but I have a request that might help self-debugging in cases like this and/or reduce the question load. Maybe I'm looking wrongly, but I can't find much on these 2 topics which would be immensely useful:

- besides the limited dependency info in the target help list, what or why would I want or not want some of these - like xorg/xephyr/etc... Some sound like they are required for X functionality but aren't. Since 'targets' are kinda unique to crouton, maybe some more detailed decisionmaking help would be good -wiki, post, whatever.

- and how does one remove a target? Like xephyr in one of the other posts of mine. You replied it didn't needed to be installed in the first place, but I didn't 'get' that from the help, so can it be removed with edit-chroot or crouton installer?

(I run rather 'full' Ubuntu installations in crouton, so making another chroot takes a long time, so anything to manipulate the install without re-installing is good, (including tips on the parameters for mounting an encrypted chroot with ecryptfs from outside...))

Thanks again.

**Comment by DennisLfromGA** [comment]
Along those lines, maybe some of the targets (e.g.) core, x11, audio, gtk-extra, etc., that are required by certain others (e.g.) xfce, unity, xiwi, etc., could be excluded from the '-t list/help' output so not to confuse people when trying to choose targets/DEs.

Also, the removal of targets is a request that is being considered (https://github.com/dnschneid/crouton/issues/717) but is just a lower priority right now - I believe.

**Comment by dnschneid** [comment]
Wait, if the updater was telling you that "xorg doesn't work on Samsung ARM devices", then everything's working fine.  The xorg target never worked on Samsung ARM, so I'm not sure why you were going down that path.

**Comment by dnschneid** [comment]
BTW, this was totally a bug.  Fixed it in 230a1afa6b27d13f35764974822f27f3558a7438 before I realized you had uncovered it here :)

**Comment by tedm** [comment]
I think that just:

sudo crouton

should just bring up a generic trusty xfce xiwi chroot.

Advanced users could then use -t for specific targets and whatever dependencies are needed. But if we keep the -t, how about categorizing them into DEs, and then "Other"

Normal users will get the DEs, and Advanced users can play with the Others ?
