### ISSUE TITLE
Xiwi with Sublime

### ISSUE THREAD

**Issue by jbaum98** [dnschneid/crouton#1445]
Running `xiwi subl` does not work even after installing `libgtk2.0-0`. If you run `xiwi xterm` and then `subl` from that, it works fine.

**Comment by dnschneid** [comment]
Stuff that immediately forks on launch confuses xiwi.  It appears that `subl` has a `-w` command that avoids forking, so try `xiwi subl -w` and see if that works better.

**Comment by dnschneid** [comment]
Another example is gvim, which requires the "foreground" flag: `xiwi gvim -f`

**Comment by jbaum98** [comment]
That worked great thank you! Light Table, backed by Node-Webkit also forks on launch. Is there a command line flag for that one?

**Comment by dnschneid** [comment]
I just searched the interwebs for subl parameters.  Try adding `-h` or `--help` to whatever command you use to launch light table and see if it prints out a list of valid parameters.  Hopefully in there is something that stops it from forking/running in background.
