### ISSUE TITLE
Incorrect Permissions

### ISSUE THREAD

**Issue by keithalanfisher** [dnschneid/crouton#1446]
The only thing my administrator account can do after install is unlock the screen. It's been a long time since I installed and used Precise but I seem to recall a an Ubuntu package installer was available. 
The -r trusty parameter does not change the installed package. Installing Trusty using CLI apt-get update and apt-get software-center works but again, administrator account can't install any software. (A dialogue box pops up here. Administrator account can't create another user, can't unlock tool! I'm appalled and confounded by all the weird complaints here. I have no idea where to begin. Another clue, the Dash icon changes to a Question Mark after upgrade to Trusty. Maybe you should scrap this POS and start over.

**Comment by DennisLfromGA** [comment]
You might want to check out this wiki for doing  upgrades - if it's not too late:
https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release

The problems with the Software Center permissons has been fixed in later releases, you may indeed just want to delete it and start over - with 'trusty'.

**Comment by keithalanfisher** [comment]
Too late. I just bought a Windows laptop to blow away with Ubuntu. Dual
boot is so passe. So 90s, don't you think? Anyone working on a Linux build
for Chromebooks? Torvolds? Ubuntu will soon be history with that
Shuttlecock in charge. I'll do it, but I'm not sharing with anybody.

Keith Alan Fisher
492 Taunton Ave
Seekonk, MA 02771

508-557-1756 Home
401-659-5229 Mobile

**Comment by DennisLfromGA** [comment]
See ya, have fun ;)

**Comment by dnschneid** [comment]
Edited your address and phone number out of your comment for your own sake :\
