### ISSUE TITLE
Should I upgrade?

### ISSUE THREAD

**Issue by Altohombre** [dnschneid/crouton#1447]
I am new to Linux. I installed crouton and see that it installs Precise 12.04.5 LTS. Should I leave it as is or should I be trying to upgrade to 14.10 or whatever the latest version of Ubuntu is? I am not sure if crouton can only handle the release it came with or if it is out dated. Thanks

**Comment by DennisLfromGA** [comment]
'precise' should be fine for most things, 'trusty' is the latest supported release though.
You can see all the releases crouton can install using: `sudo sh ~/Downloads/crouton -r list`

You can upgrade an existing chroot, see this wiki page for instructions:
https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release

If you do decide to upgrade, I would make a backup first (sudo edit-chroot -b precise).

**Comment by Altohombre** [comment]
I just got my laptop yesterday so I have nothing to backup yet. When I use the command to see the releases I get: "Failed to download crouton installer: Check your internet connection or proxy settings" but when I try "-P" it says command not found.

**Comment by Altohombre** [comment]
I am most interested in upgrading because I would like to utilize the latest version of MacBuntu which mimics Yosemite. The version I have now would make it look like Lion which is less appealing to me. Is it possible to upgrade to 14.10 somehow from 12.04.5 LTS?

**Comment by DennisLfromGA** [comment]
@Altohombre -

> I just got my laptop yesterday so I have nothing to backup yet.

I meant backup your 'precise' chroot, note the command I gave above (sudo edit-chroot -b precise).

> When I use the command to see the releases I get: "Failed to download crouton installer: Check your internet connection or proxy settings" but when I try "-P" it says command not found.

Are you connected to the internet? Are you behind a proxy?

> Is it possible to upgrade to 14.10 somehow from 12.04.5 LTS?

Please refer to the wiki page I listed above for upgrade procedures:
https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release

**Comment by Altohombre** [comment]
I am connected to the internet. I have no idea if I am behind a Proxy.

**Comment by Altohombre** [comment]
When I do this part it says command not found
sudo enter-chroot -n <chroot_name> (replace <chroot_name> by the name of your chroot, e.g. raring)

**Comment by DennisLfromGA** [comment]
@Altohombre -

> Even the backup says command not found.

Are you saying that `sudo edit-chroot -b precise` fails?
Are you sure you still have a crouton chroot installed?

> I am connected to the internet. I have no idea if I am behind a Proxy.

If so, then `sudo sh ~/Downloads/crouton -r list` should work, try again.
If that fails, you have bigger problems than obtaining the list I'm afraid, you won't be able to install a new chroot until you can get past `"Failed to download crouton installer...`.

Here's the current list of releases crouton can install -
```
Recognized debian releases:
    potato* woody* sarge* etch* lenny* squeeze* wheezy jessie sid
Recognized kali releases:
    kali
Recognized ubuntu releases:
    warty* hoary* breezy* dapper* edgy* feisty* gutsy* hardy* intrepid* jaunty*
    karmic* lucid* maverick* natty* oneiric* precise quantal* raring* saucy*
    trusty utopic*
Releases marked with * are unsupported, but may work with some effort.
```

**Comment by DennisLfromGA** [comment]
@Altohombre -

> When I do this part it says command not found
> sudo enter-chroot -n (replace by the name of your chroot, e.g. raring)

Try entering it without the chrootname: `sudo edit-chroot -b` and see if that works.
If not, then you've given your 'precise' chroot a name other than 'precise', enter:
`sudo edit-chroot -a` and it will list the chroot name(s).

**Comment by Altohombre** [comment]
is there a way to delete everything and install crouton again?

**Comment by DennisLfromGA** [comment]
@Altohombre -

> is there a way to delete everything ...?

You can delete your chroot using: `sudo delete-chroot precise`, if 'precise' is not the name, try: `sudo delete-chroot -a`.

> ...and install crouton again?

Like I said above, you won't be able to install a new chroot until you can get past "Failed to download crouton installer...". Once past that, just install another release with the '-r [release]' option.

**Comment by Altohombre** [comment]
I reinstalled the software updater and ran it and it said I didn't have privileges to do this. 

They make it seem so easy to setup Ubuntu, but this is rough =)

**Comment by DennisLfromGA** [comment]
@Altohombre -

What were the steps you took and the commands you gave?
Did you use 'sudo' for the command line stuff or 'gksu' for the gui stuff?

**Comment by Altohombre** [comment]
i did sudo apt-get install update-manager synaptic

I

**Comment by DennisLfromGA** [comment]
@Altohombre - Those aren't the instructions given on the wiki - just sayin'.

**Comment by Altohombre** [comment]
I couldn't find the update manager and none of the commands worked. I did a search and learned how to install it. It worked, but won't let me use

**Comment by DennisLfromGA** [comment]
What can't you 'use'?

**Comment by Altohombre** [comment]
When I run software updater it says that I don't have privileges to use it.

**Comment by DennisLfromGA** [comment]
Using 'Software Updater' is not the way shown on the wiki page :(

**Comment by Altohombre** [comment]
the link u gave me says u can use the ubuntu software manager or use those commands. I do not have software manager and those commands don't work....

**Comment by DennisLfromGA** [comment]
My bad, I overlooked the link to 'Ubuntu's update manager'. ;(
I don't know why the commands don't work for you, I guess this is a mystery I can't solve... :((

If you can get 'crouton' to respond, then I would do a fresh install of 'trusty'.

**Comment by Altohombre** [comment]
Do u suggest I delete crouton and start from scratch? maybe I screwed something up along the way. The problem is that when I tried those commands to delete you mentioned it did not recognize them

**Comment by DennisLfromGA** [comment]
> Do u suggest I delete crouton and start from scratch?

If you can't upgrade the existing chroot and it doesn't work for you, then I don't see any other alternative than to start over, if you still want one.

> The problem is that when I tried those commands to delete you mentioned it did not recognize them

That is also a mystery to me...
What happens when you enter: `sudo delete-chroot -a` ?

**Comment by Altohombre** [comment]
command not found

**Comment by Altohombre** [comment]
Ok i deleted the chroot via the chrome os terminal. What do i need to do next in order to do a fresh install of trusty. last time it automatically gave me precise 12.04.

Thank you, I really appreciate your patience and help.

**Comment by DennisLfromGA** [comment]
Okay, try: `sudo /usr/local/bin/delete-chroot -a`

**Comment by Altohombre** [comment]
not sure if that comment from you was after my last comment. 

It said No chroot found in /mnt/stateful_partition/crouton/chroots

**Comment by DennisLfromGA** [comment]
It depends what target(s) / Desktop Environment(s) you wnat to use, but in general, to install trusty with xfce enter: 

  `sudo ~/Downloads/crouton -r trusty -t xfce,extension`

**Comment by DennisLfromGA** [comment]
> It said No chroot found in /mnt/stateful_partition/crouton/chroots

That must have been after you attempted to delete it manually.

**Comment by Altohombre** [comment]
I tried this and I got command not found:

sudo ~/Downloads/crouton -r trusty -t unity,extension

**Comment by tedm** [comment]
try this:

sudo sh ~/Downloads/crouton -r trusty -t unity,extension

**Comment by Altohombre** [comment]
seems to be working!!!

**Comment by Altohombre** [comment]
thank you so much!

**Comment by tedm** [comment]
Enjoy and thank @DennisLfromGA as he got you running. It's ironic that I saw the typo, as 9 out of 10 times, Dennis is correcting my typos or command syntax!

**Comment by DennisLfromGA** [comment]
Glad to hear it and you're welcome!

@tedm - You're right, I have my home folder re-mounted as executable so I never need to use the 'sh' prefix.

**Comment by tedm** [comment]
@DennisLfromGA OK, my scripts never need sh either, after chmod 'ing to executable, but a quick look shows both Chrome OS and precise and trusty user directories are executable, with the exception of ~/Downloads. Did you hack croutonversion to put the newest crouton outside of ~/Downloads?

**Comment by DennisLfromGA** [comment]
@tedm,

> Did you hack croutonversion to put the newest crouton outside of ~/Downloads?

No, it's in ~/Downloads. I remount some things in my `.bashrc` script -
```
sudo mount -i -o remount,exec /home
sudo mount -i -o remount,exec /home/chronos/user
```
My HOME & Downloads permissions are -
```
drwx--x--- 34 chronos chronos-access 20K Feb 27 17:40 /home/chronos/user/
drwx--x---  4 chronos chronos-access 12K Feb 27 11:57 /home/chronos/user/Downloads/
```

**Comment by tedm** [comment]
You must be on the beta or dev channel, these are the stable channel defaults for the arm:

drwxr-xr-x 9 chronos chronos 4096 Feb 27 17:38 chronos
drwxrwx--t 3 root    root    4096 Dec 30  2013 root
drwxr-xr-x 2 root    root    4096 Apr 21  2014 ted
drwxr-xr-x 3 root    root    4096 Dec 30  2013 user
chronos@localhost /home $

**Comment by tedm** [comment]
in /home/chronos/user there is this ...

chronos@localhost ~ $ ls -la
total 42036
drwx--x--- 32 chronos chronos-access    16384 Feb 27 17:44 .
drwxr-xr-x  9 chronos chronos            4096 Feb 27 17:45 ..
-rw-------  1 chronos chronos             175 Feb  5 20:55 App Launcher Search
drwx------  3 chronos chronos            4096 Jan  8  2014 Application Cache
-rw-------  1 chronos chronos            6661 Feb 27 17:34 .bash_history
-rw-r--r--  1 chronos chronos             127 Dec 30  2013 .bash_logout
-rw-r--r--  1 chronos chronos             193 Dec 30  2013 .bash_profile
-rw-r--r--  1 chronos chronos             551 Dec 30  2013 .bashrc
-rw-------  1 chronos chronos          235726 Feb 26 11:43 Bookmarks
-rw-r--r--  1 chronos chronos          235726 Feb 26 19:24 Bookmarks.bak
drwx------  2 chronos chronos          483328 Feb 27 17:39 Cache
-rw-r-----  1 chronos chronos          203595 Feb 27 13:37 Certificate Revocation Lists
drwxr-xr-x  2 chronos chronos            4096 Sep 28 07:58 cmt
-rw-------  1 chronos chronos             313 Feb 17  2014 .com.google.Chrome.AJToNb
drwx------  3 chronos chronos            4096 Dec 30  2013 .config
-rw-r--r--  1 chronos chronos         2359296 Feb 27 17:44 Cookies
-rw-r--r--  1 chronos chronos           16384 Feb 27 17:44 Cookies-journal
-rw-------  1 chronos chronos            1051 Feb 27 14:05 .crosh_history
drwxr-xr-x  8 root    root               4096 Feb 22 15:07 crouton.unbundled
-rw-r--r--  1 chronos chronos         1190645 Feb 27 17:42 Current Session
-rw-r--r--  1 chronos chronos         1320463 Feb 27 14:19 Current Tabs
drwx------ 30 chronos chronos            4096 Jan  9 08:25 databases
drwx--x---  3 chronos chronos-access    24576 Feb 27 13:33 Downloads
-rw-r--r--  1 chronos chronos            8192 Feb 27 17:32 Extension Cookies
-rw-r--r--  1 chronos chronos            6704 Feb 27 17:32 Extension Cookies-journal
drwx------  2 chronos chronos            4096 Feb 26 19:24 Extension Rules
drwx------ 61 chronos chronos           16384 Feb 27 11:21 Extensions
drwx------  2 chronos chronos            4096 Feb 27 14:15 Extension State
-rw-r--r--  1 chronos chronos        10428416 Feb 27 17:39 Favicons
-rw-r--r--  1 chronos chronos           16384 Feb 27 17:39 Favicons-journal
drwx------ 12 chronos chronos            4096 Feb 27 11:23 File System
drwx--x---  3 chronos chronos-access     4096 Dec 30  2013 GCache
drwx------  2 chronos chronos            4096 Feb 26 19:24 GCM Store
drwx------  2 chronos chronos            4096 Dec 30  2013 GPUCache
-rw-r--r--  1 chronos chronos        13025280 Feb 27 17:39 History
-rw-r--r--  1 chronos chronos           16384 Feb 27 17:43 History-journal
drwx------ 13 chronos chronos            4096 Dec 31 13:08 IndexedDB
-rw-r--r--  1 chronos chronos           49052 Feb 26 19:23 Last Session
-rw-r--r--  1 chronos chronos          180960 Feb 26 19:23 Last Tabs
drwx------ 11 chronos chronos            4096 Feb 26 19:24 Local App Settings
drwx------  8 chronos chronos            4096 Jan 31 02:04 Local Extension Settings
drwx------  2 chronos chronos          458752 Feb 27 12:10 Local Storage
drwx------  2 chronos chronos            4096 Feb 26 19:24 log
-rw-------  1 chronos chronos          274432 Feb 27 17:38 Login Data
-rw-------  1 chronos chronos           16384 Feb 27 17:38 Login Data-journal
-rw-r--r--  1 chronos chronos             519 Feb 26 19:24 login-times
-rw-r--r--  1 chronos chronos             207 Feb 26 19:23 logout-times
drwx------  3 chronos chronos            4096 Mar 10  2014 Managed Extension Settings
drwx------  2 chronos chronos           40960 Feb 25 10:15 Media Cache
-rw-r--r--  1 chronos chronos               2 Jan 26  2014 mouse_sensitivity
-rw-r--r--  1 chronos chronos         7444480 Feb 27 17:31 Network Action Predictor
-rw-r--r--  1 chronos chronos           16384 Feb 27 17:31 Network Action Predictor-journal
-rw-r--r--  1 chronos chronos           65536 Dec 31 12:56 Origin Bound Certs
-rw-r--r--  1 chronos chronos            3608 Dec 31 12:56 Origin Bound Certs-journal
drwx------  3 chronos chronos            4096 Dec 30  2013 Pepper Data
drwx------  3 chronos chronos            4096 Dec 30  2013 .pki
-rw-------  1 chronos chronos          356667 Feb 27 17:44 Preferences
-rw-r--r--  1 chronos chronos           20480 Feb 27 17:33 QuotaManager
-rw-r--r--  1 chronos chronos            8768 Feb 27 17:33 QuotaManager-journal
-rw-r--r--  1 chronos chronos             180 Dec 30  2013 README
-rw-------  1 chronos chronos             399 Feb 27 10:33 RLZ Data
-rw-r--r--  1 chronos chronos               0 Dec 30  2013 RLZ Data.lock
drwx------  2 chronos chronos            4096 Feb 27 13:31 Session Storage
-rw-r--r--  1 chronos chronos         1105920 Feb 27 17:31 Shortcuts
-rw-r--r--  1 chronos chronos           16384 Feb 27 17:31 Shortcuts-journal
drwx------  2 chronos chronos            4096 Jul 28  2014 .ssh
drwx------  3 chronos chronos            4096 Dec 30  2013 Storage
drwx------  6 chronos chronos            4096 Feb 26 21:02 Sync App Settings
drwx------  2 chronos chronos            4096 Feb 17  2014 Sync Data
drwx------  3 chronos chronos            4096 Feb 26 13:21 Sync Extension Settings
-rw-r--r--  1 chronos chronos         1626112 Feb 27 11:11 Top Sites
-rw-r--r--  1 chronos chronos           16384 Feb 27 11:11 Top Sites-journal
-rw-r--r--  1 chronos chronos               2 Jun 20  2014 touchpad_sensitivity
-rw-r--r--  1 chronos chronos               2 Jun 20  2014 touchpad_t5r2_3f_click_enable
-rw-r--r--  1 chronos chronos               2 Jun 20  2014 touchpad_tap_drag_enable
-rw-------  1 chronos chronos           34349 Feb 27 17:40 TransportSecurity
drwx------  2 chronos chronos            4096 Dec 30  2013 User StyleSheets
-rw-r--r--  1 chronos chronos          524192 Feb 27 17:39 Visited Links
-rw-r--r--  1 chronos chronos          466944 Feb 27 17:38 Web Data
-rw-r--r--  1 chronos chronos           16384 Feb 27 17:38 Web Data-journal
-rw-r--r--  1 chronos chronos            4096 Feb  6 16:06 WebRTCIdentityStore
-rw-r--r--  1 chronos chronos            4640 Feb  6 16:06 WebRTCIdentityStore-journal
-rw-------  1 chronos chronos            8592 Jun  1  2014 Webservice Search Cache
chronos@localhost ~ $

**Comment by Altohombre** [comment]
Everything installed to 14.4 great and then I installed to 14.10. Now I am unable to boot from my ChromeOS side via the terminal and sudo start unity. It starts to work and then the terminal reappears with the script message. 

waiting for X server to shut down Hangup
.(EE) Server terminated successfully (0). Closing log file

**Comment by DennisLfromGA** [comment]
'trusty' (Ubuntu 14.4) is a fully supported lts version, 'utopic' (Utopic 14.10) is not.

**Comment by RyM21** [comment]
@Altohombre @DennisLfromGA I got the same message, then I realized I was trying to install crouton from inside the Chroot:

> /home/ryan/Downloads/crouton: 62: /home/ryan/Downloads/crouton: curl: not found
> Failed to download crouton installer.
> Check your internet connection or proxy settings (-P) and try again.
> (trusty)ryan@localhost:~$ sudo edit-chroot                        
> sudo: edit-chroot: command not found
> (trusty)ryan@localhost:~$
