### ISSUE TITLE
croutonversion not working in crosh / shell as chronos user

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1452]
pretty sure I used to be able to run this outside of the chroot fine:

chronos@localhost / $ sudo croutonversion -d -u
crouton: version 1-20140301024303~master:06549cb2
Retreiving latest version of crouton
latest: version 
Saving latest version to /root/Downloads/crouton
mv: cannot move ‘/tmp/crouton.jLD/crouton’ to ‘/root/Downloads/crouton’: No such file or directory

huh?

chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)ted@localhost:~$ sudo croutonversion -d -u
[sudo] password for ted: 
crouton: version 1-20150226113948~master:060367f9
Retrieving latest version of crouton
latest: version 1-20150226194717~master:841ff620
Saving latest version to /home/ted/Downloads/crouton
(precise)ted@localhost:~$

**Comment by dnschneid** [comment]
~/Downloads isn't mounted for the root user anymore.  That croutonversion script is custom, so you'll need to update it to not use `-u root`.

**Comment by tedm** [comment]
OK, thanks.

**Comment by tedm** [comment]
@DennisLfromGA going through old scripts, I think you wrote this one called crv.sh - it still works well, if crouton gets moved to the right places, on my precise / arm the 'which' command seems to be failing, even though it is in /bin, not sure if you're still updating it, but it seems useful - in the example below, all chroots are unmounted, but if any were, it would show it.

chronos@localhost / $ cd /usr/local/bin
chronos@localhost /usr/local/bin $ ./crv.sh
host: /home/chronos/user/Downloads/crouton: version 1-20150226194717~master:841ff620
-------------------------------------------------------------
chroot name: precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150226113948~master:060367f9
release: precise
architecture: armhf
xmethod: xiwi
targets: xiwi,xfce
host: version 6457.107.0 (Official Build) stable-channel daisy 
-------------------------------------------------------------
chroot name: trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150226183401~master:24fa73b3
release: trusty
architecture: armhf
xmethod: xiwi
targets: xiwi,extension,xfce
host: version 6457.107.0 (Official Build) stable-channel daisy 
-------------------------------------------------------------

**Comment by DennisLfromGA** [comment]
Yeah, I believe that was a *custom* croutonversion that would run outside the chroot.
Inside the chroot, you needn't (read shouldn't) use sudo when executing 'croutonversion'.

The script '[crv[.sh]](https://gist.github.com/DennisLfromGA/9654604)' was one I played with a while back but I haven't kept up with it, I'm a little surprised it still works.

**Comment by tedm** [comment]
@DennisLfromGA your crv.sh works well, and even unmodified if you cp crouton to where it wants to find it, but just like the custom old croutonversion, at some point it wants to root/Downloads and that's jut not there anymore. I'll try to find the newest standard /bin utilities.

**Comment by Watney** [comment]
@tedm Please excuse me for hijacking this thread, but what's this icon? It looks like the Crouton-Integration icon, but I thought it was only a browser extension. Seems like it might be cool to have integration in the dock for easier window switches, etc. Thanks!!

![screenshot 2015-02-27 at 6 06 00 pm](https://cloud.githubusercontent.com/assets/5377590/6424313/ac54aa7c-beab-11e4-9a27-b1d35e3cb91e.png)

**Comment by tedm** [comment]
@Watney I believe it is part of the Crouton Integration app. I haven't used it before, as I use alt tab to switch windows, but upon clicking on it, it shows all xiwi windows and lets you go directly to any from the dock. It's probably meant for mac users ;)

**Comment by Watney** [comment]
@tedm thanks! Interesting. I installed ``-t extension,xiwi`` and I'm not seeing the desktop app, only the toolbar icon. Seems like it would be nice to actuate with the keyboard ``Alt+8`` for example. 

Is anyone else (who randomly stumbles onto this dead thread) seeing the desktop icon? Thanks!!

**Comment by DennisLfromGA** [comment]
I think it's activated when the xiwi window is *not* in full screen mode.
Try exiting full screen in your chroot window and see if it appears.

On Fri, Feb 27, 2015 at 10:52 PM, Watney <notifications@github.com> wrote:

> @tedm <https://github.com/tedm> thanks! Interesting. I installed -t
> extension,xiwi and I'm not seeing the desktop app, only the toolbar icon.
> Seems like it would be nice to actuate with the keyboard Alt+8 for
> example.
>
> Is anyone else (who randomly stumbles onto this dead thread) seeing the
> desktop icon? Thanks!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1452#issuecomment-76508795>.
>



-- 
*DennyL@GMail*

**Comment by Watney** [comment]
@tedm @DennisLfromGA I feel like a total fool! The symbol appears in the dock, just as you suggested, when an `xiwi` window is *not* in the full screen. I have one myself!
