### ISSUE TITLE
Launch xiwi app in a small window

### ISSUE THREAD

**Issue by tonyxue** [dnschneid/crouton#1453]
As implemented in PR #1442 , the xiwi app windows are launched into full-screen mode, just like the launching the DEs. It would be better if the xiwi apps can be launched in the "default" resolution as they would do inside a normal desktop environment to provide better experience.

**Comment by tedm** [comment]
I'd like this too, as I mostly click the minimize at the top, I don't know what default size is, but just windowed would be a start.

Also noticed that when starting a bunch of xiwi chroots up, that sometimes if you don't click fast enough, they go away (could be a resource issue).

However, I have run full screen once or twice, and it is very nice, you can't easily alt-tab to the host OS, and it feels very native linux, so please don't remove the ability to do full screen, not just full window, if that makes sense?

**Comment by tonyxue** [comment]
>  I don't know what default size is, but just windowed would be a start.
The "default" I mentioned means the size an app would have in a normal DE, for example, Pidgin should start as a thin and vertical bar on the screen to show the buddy list while a terminal is a preset size window and apps like chrome would go into full screen *in the tab*.

**Comment by dnschneid** [comment]
That's probably doable...the script could hold off on launching ratpoison until a window has appeared, grab that window size and then proceed from there.  It would trip up on splash screens though.

I'm not sure the pidgin buddy list is a good example though, as when you open a chat it will take up the exact same space.

I think stage one is avoiding full-screen and having a reasonable default window size.

**Comment by tedm** [comment]
OK, I haven't used xiwi for apps yet, but that makes sense. It sounds like xiwi-app is behaving like Xming on windows. I'll try xiwi-app this weekend. Do apps have their independent size and position data independent of the DE?

I was indicating that I would prefer my whole xfce xiwi DE session come up windowed by default, but with the ability to come up as full screen as optional.

**Comment by DennisLfromGA** [comment]
Perhaps an option would be in order, '-w' for windowed, otherwise full
screen.

On Fri, Feb 27, 2015 at 9:37 PM, tedm <notifications@github.com> wrote:

> OK, I haven't used xiwi for apps yet, but that makes sense. It sounds like
> xiwi-app is behaving like Xming on windows. I'll try xiwi-app this weekend.
> Do apps have their independent size and position data independent of the DE?
>
> I was indicating that I would prefer my whole xfce xiwi DE session come up
> windowed by default, but with the ability to come up as full screen as
> optional.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1453#issuecomment-76505950>.
>



-- 
*DennyL@GMail*

**Comment by fczuardi** [comment]
or --width and --height parameters for the ```xiwi``` command (from xiwi-app) inside the chroot, so the user becomes responsible for setting the x session window dimensions, if not passed defaults to fullscreen

**Comment by tonyxue** [comment]
> or --width and --height parameters for the xiwi command (from xiwi-app) inside the chroot, so the user becomes responsible for setting the x session window dimensions, if not passed defaults to fullscreen

But manually setting a size at every launch is simply painful.
And it is a bit hard for everyone to build up a concept in mind about the resolution on each particular screen they use.

> I'm not sure the pidgin buddy list is a good example though, as when you open a chat it will take up the exact same space.

> I think stage one is avoiding full-screen and having a reasonable default window size.

Well,yea, it is not a very good common example. Those "regular" size window app should be first.

**Comment by dnschneid** [comment]
I'm inclined to leave DEs launching full-screen, because otherwise alt-tab doesn't work.  Stuff launched by `xiwi` will be windowed.  You can actually launch DEs via the xiwi command as well, so that's a nice compromise...

**Comment by DennisLfromGA** [comment]
Sounds like a perfect solution to me.

On Sun, Mar 1, 2015 at 2:11 AM, David Schneider <notifications@github.com>
wrote:

> I'm inclined to leave DEs launching full-screen, because otherwise alt-tab
> doesn't work. Stuff launched by xiwi will be windowed. You can actually
> launch DEs via the xiwi command as well, so that's a nice compromise...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1453#issuecomment-76585973>.
>



-- 
*DennyL@GMail*

**Comment by tonyxue** [comment]
Sounds good. People can get either way as they like.

**Comment by dnschneid** [comment]
The xiwiwindow branch implements both windowed- and tab launching of chroots. `xiwi` will default to windowed, `xiwi -F` will go full-screen, and `xiwi -T` will go tabbed (using uppercase to avoid conflicts with enter-chroot when we make a startxiwi script down the road).

It's a bit hard to test as you have to run the extension unpacked, but if you so desire, the branch seems to be working overall.

TODO: I need to change the order of the info in the title when you're in a tab (chroot+application AFTER titlebar instead of before), because the tab is too small to give useful information.

**Comment by DennisLfromGA** [comment]
> when we make a startxiwi script down the road

Don't know if this is far enough down the road but I've started one - [startxiwi](https://github.com/DennisLfromGA/crouton/blob/master/host-bin/startxiwi)

RE: https://github.com/dnschneid/crouton/pull/1568#issuecomment-89862497

**Comment by dnschneid** [comment]
If you open a PR for that (not necessarily being ready to merge), we can comment and discuss as you work on it.
