### ISSUE TITLE
show user status of running chroots / windows

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1454]
enhancment request - have a user terminal or command that shows the status of running crouton chroots and xiwi windows, perhaps a user version of the extension debug which shows chroot names running, but addl. details like addl targets, crouton versions, etc. this window with my startup script chroots.sh is simply launching a precise startxfce4 -b, and a trusty startxfce4 -b, then below it is @DennisLfromGA old crv.sh script:

![screenshot 2015-02-27 at 6 05 23 pm](https://cloud.githubusercontent.com/assets/3884283/6424370/a57cb234-beac-11e4-9855-54e45313f687.png)

there is added functionality in Dennis's crv.sh script, I think as time goes by, things will show up in color as needing updating. Not sure if that part works yet.

**Comment by dnschneid** [comment]
`sudo edit-chroot -al` and `sudo enter-chroot croutoncycle l`?

**Comment by tedm** [comment]
yes, that's it. For the latter script, my # was 0. that works. crv.sh is easier to remember, but edit-chroot shows encryption status which is good.

**Comment by dnschneid** [comment]
That's a lowercase L, not a 1.

**Comment by tedm** [comment]
OK, I added those two scripts to my script, and now launch two xfces, and get good info. Sometimes the windows disconnect, give the tv screen, and I have to run again. Perhaps there needs to be a delay between the first startxfce4 and the 2nd one, or perhaps it's just a stable channel issue for now. 

I also just realized that clicking the upper right x of a windowed xfce chroot doesn't "close and unmount" it, it just closes the window and can only be brought back with the mac dock icon (or the debug window selector), but not by keyboard? (alt tab would be great).

Closing the window by clicking on upper right X, and also unmounting the chroot (if it were the only/last window for the chroot) would be nice. Logging out, which is just a bit more effort does close down the window, and chroot, and probably in a safer way.

So maybe I'm not experiencing as many failed unmounts as I thought I was ...

**Comment by DennisLfromGA** [comment]
Yes, crv.sh was a predecessor to 'sudo edit-chroot -al'.
I hadn't thought of 'sudo enter-chroot croutoncycle list', great idea.


On Fri, Feb 27, 2015 at 10:08 PM, tedm <notifications@github.com> wrote:

> OK, I added those two scripts to my script, and now launch two xfces, and
> get good info. Sometimes the windows disconnect, give the tv screen, and I
> have to run again. Perhaps there needs to be a delay between the first
> startxfce4 and the 2nd one, or perhaps it's just a stable channel issue for
> now.
>
> I also just realized that clicking the upper right x of a windowed xfce
> chroot doesn't "close and unmount" it, it just closes the window and can
> only be brought back with the mac dock icon (or the debug window selector),
> but not by keyboard? (alt tab would be great).
>
> Closing the window by clicking on upper right X, and also unmounting the
> chroot (if it were the only/last window for the chroot) would be nice.
> Logging out, which is just a bit more effort does close down the window,
> and chroot, and probably in a safer way.
>
> So maybe I'm not experiencing as many failed unmounts as I thought I was
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1454#issuecomment-76507253>.
>



-- 
*DennyL@GMail*
