### ISSUE TITLE
Inverted Screen Color After Latest ChromeOS Update

### ISSUE THREAD

**Issue by mobius1484** [dnschneid/crouton#1455]
I received the ChromeOS update that was pushed the other day, and after rebooting and update my chroot, I noticed that the screen colors were inverted.  I remember reading somewhere in another thread about trying to get hardware acceleration on the Tegra K1 in the chroot environment, that there was an issue with the numerical RGB representation in ChromeOS kernel being in a different order than the standard RGB.  I'm wondering if the latest update changed the order, and is the reason I'm experiencing the color inversion in the GUI.

Chromebook: Acer 13 CB5-311-T1UU
Crouton: latest
Distro: Kali, latest
Desktop Environment: Xfce
Note: chroot was updated using the latest crouton, with -u flag just before posting this to see if the issue had already been fixed.

**Comment by dnschneid** [comment]
Could you please provide the full output of `croutonversion`?

**Comment by mobius1484** [comment]
crouton: version 1-20150226194717~master:841ff620
release: kali
architecture: armhf
xmethod: xorg
targets: xfce,x11,cli-extra,xorg,keyboard,audio
host: version 6457.107.0 (Official Build) stable-channel nyan_big

**Comment by dnschneid** [comment]
xorg prior to release 6689 has flipped colors on the K1 (see #1089).  Normally x11 would select xephyr, but since you installed xorg explicitly, crouton politely obliged.

Stick with xephyr for another couple months on stable...

**Comment by SwaginWagon101** [comment]
I don't know if this problem is fixed yet,  or if the problem is only to specific to xfce,  but I just installed trusty,  kde,  and xorg, on the tk1 Chromebook and there isn't any color inversion.

**Comment by dnschneid** [comment]
Yes, stable is on 6812 now, so the patch has long since landed.  There shouldn't be any issues with fbdev on K1.
