### ISSUE TITLE
xiwi pass-through IME

### ISSUE THREAD

**Issue by tonyxue** [dnschneid/crouton#1457]
Currently users cannot input non-latin characters languages into the apps as there is no input method working.

ibus works under the DEs and there is obviously no DE atm.
And the tab does not pass the result from Chromium OS system input method.

@dnschneid Is there a way to pass the output from system input tools to the tabs? That would be the best way I guess. In this way it would make the tabs look more integrated with the system.

**Comment by dnschneid** [comment]
There's two options here.  One is to get the input method working inside of X11; I think this should be possible if you open the same chroot using a simple xinit and configure the default X11 IME (xim, I think?) appropriately (via non-DE-specific methods).  But you're right, it's not very good integration.

Option 2 is to handle IME events from the extension and pass them in, but that would require making an X11 IME (either ibus or xim or whatever) that reads the input from the extension and passes the location of the edit box back.  That'll make for very good integration, but will, of course, require implementing an IME.

**Comment by tonyxue** [comment]
I think option one is more realistic and faster for now as I discovered another issue with option 2.

The location of the input option box should be placed right under the cursor on the screen. But while in a tab, there is no cursor available for the system. So it is placed on the lower left corner when full screen and under (outside of and align with) the window when in other size. It makes the input experience weird.
And when you move the  window around on the desktop, the input option box remains at the original position. To fix that, I had to maximize and minimize the window again.

It's a bit hard to understand since I can't take a screenshot. The tab minimizes after pressing the shortcut and seems the input option box would not stay when taking the screenshot. So any way I can take one successfully? It would be easier to show the situation.

**Comment by dnschneid** [comment]
That's what I was referring to with "passes the location of the edit box back".  It would come pretty naturally from making an X11 IME.

**Comment by dnschneid** [comment]
Note that the new autocorrect feature in Chromium also triggers this issue.

**Comment by junfx** [comment]
What happened on my ASUS C201P:

$ xiwi emacs

At first, key-bindings for emacs are not working, after pressing fullscreen button, switching to another app/page,  switching back, or maybe just leave it alone several seconds, the emacs keys work, C-f, C-n, M-x, ... even Ctrl-Space, which switch between input methods for chromeos. That's what I expect.

But Chinese pinyin does work. Sometimes, in pinyin input mode, uppercase English letters presented instead of lowercase letter and Chinese characters. Also, switching to another app and back makes lowercase letters back.

**Comment by jackyko1991** [comment]
I am a Chinese user and have same issue on crouton.

Chinese IME (Quick in specific) works fine in chromeos native environment, and this is the place where I typing Chinese word most of the time. But in rare cases, such as latex typing, would work better in IDEs with syntax highlighting.

Hopefully this issue can be fixed soon.

**Comment by liuxiawei** [comment]
I have the same problem too. Hope solve this problem!

**Comment by VictorSu000** [comment]
@tonyxue How do you solve IME issues with option one? How to "open the same chroot using a simple xinit and configure the default X11 IME"? I am using sogou-pinyin with fcitx on ubuntu, xfce. Can you offer some help please? Thanks.
