### ISSUE TITLE
target $TIPS in start* scripts

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1458]
Is there currently a way to see the $USAGE messages in the start\* scripts?

I may be missing something but, for example, `sudo startgnome -h` gives you the $USAGE message for `enter-chroot` not the `startgnome` script.

I think it might be helpful to have a way to output the $USAGE message in the start\* scripts and maybe even have the associated target's $TIPS display too for those (me:) that forget these blurbs at the tail end of a crouton install or update.

No biggey, just something to ponder in your _free time_ - ha, ha

**Comment by dnschneid** [comment]
We could probably make the start* scripts react to -h by providing their own usage, and then also calling enter-chroot -h to output that as well.  The USAGE could have similar text to TIPS (I don't think the effort to try to dedupe that text is worth it).

I'd consider this a pie for someone to grab...

**Comment by DennisLfromGA** [comment]
A pie it is then - but maybe on the back burner / stove...

**Comment by DennisLfromGA** [comment]
Okay, just noticed this again, sorry.
Maybe something like what's done in `startxiwi` would work for the other `start*` scripts too.
Here's one example -
```
--- /var/crouton/bin/startlxde
+++ /usr/local/bin/startlxde
@@ -6,13 +6,28 @@
 set -e
 
 APPLICATION="${0##*/}"
+ENTERCHROOT="$(dirname "$(readlink -f "$0")")/enter-chroot"
 
 USAGE="$APPLICATION [options]
 
 Wraps enter-chroot to start an LXDE session.
 By default, it will log into the primary user on the first chroot found.
 
-Options are directly passed to enter-chroot; run enter-chroot to list them."
+Options:
+$("$ENTERCHROOT" -h 2>&1 | grep -e ' -[bckntuX]')
+"
+
+if [ "$#" = "0" ]; then 
+    echo "$USAGE" 1>&2
+    exit 2
+fi
+
+while getopts 'bc:k:n:t:u:X:' OPT; do
+    case "$OPT" in
+      \?) echo "$USAGE" 1>&2
+          exit 2;;
+    esac
+done
 
 exec sh -e "`dirname "\`readlink -f "$0"\`"`/enter-chroot" -t lxde "$@" "" \
     exec xinit /usr/bin/startlxde
```

The output looks like this -
```
chronos@localhost ~/Downloads $ /usr/local/bin/startlxde -h
Illegal option -h
startlxde [options]

Wraps enter-chroot to start an LXDE session.
By default, it will log into the primary user on the first chroot found.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /usr/local/chroots
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -X XMETHOD  Override the auto-detected XMETHOD for this session.
```

I'll do a PR if this looks like something worth doing.

-**DennisL**
