### ISSUE TITLE
gnome-session-check-accelerated

### ISSUE THREAD

**Issue by gonzalezb** [dnschneid/crouton#1459]
tried install elementary freya 0.3 desktop on Ubuntu trusty using this guide https://www.reddit.com/r/elementaryos/comments/2mci9i/freya_on_acer_chromebook_11_with_crouton/

but when i launch startelem it fails but when i do sudo enter-chroot and try and start the xinitrc file manually i get this message

(gnome-session-check-accelerated:19767): Gtk-WARNING **: cannot open display: 

(gnome-session-check-accelerated:19777): Gtk-WARNING **: cannot open display: 

*\* (process:19762): WARNING **: software acceleration check failed: Child process exited with code 1

*\* (gnome-session:19762): WARNING **: Cannot open display: 

any idea on how to fix??

I am on Toshiba Chromebook 2

**Comment by DennisLfromGA** [comment]
On Sun, Mar 1, 2015 at 1:44 PM, Brenden Gonzalez <notifications@github.com>
wrote:

> gnome-session-check-accelerated
>

​It might be:
https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1274013
​



-- 
*DennyL@GMail*

**Comment by dnschneid** [comment]
Or the deduped [https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1251281].  Gotta love >1-year-old "critical" bugs.

**Comment by divx118** [comment]
Should be fixed by now according to https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1251281
