### ISSUE TITLE
No Sound [Trinity DE]

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#1461]
I have tried Googling my problem but nothing seems to bring anything up. How do I setup crouton to work with the default sound system that Trinity comes with? Sound dosn't seem to be working for some reason. The only application I have that can play audio is the Amarok Audio player.

Thanks!

**Comment by compaq98** [comment]
I have found out why the audio isn't working. The trinity desktop uses ALSA by default. Is there a way to install and configure alsa to tunnel requests PulseAudio instead, then make pulseaudio the default program and let it talk to CRAS?
