### ISSUE TITLE
Boots a black screen after update

### ISSUE THREAD

**Issue by Altohombre** [dnschneid/crouton#1462]
I currently had 14.10 and an update appeared so I clicked it. My chromebook restarted into ChromeOs and when I try to boot into Ubuntu I get a black/blank screen. I tried a couple things but nothing has worked yet. Thanks in advance for any help.

**Comment by Altohombre** [comment]
Nevermind. I got it to work doing it this way.

Remove everything to do with the Nvidia proprietary drivers.
sudo apt-get remove --purge nvidia-*
Start from scratch.
sudo apt-get remove --purge xserver-xorg-video-nouveau xserver-xorg-video-nv
Reinstall all the things!
sudo apt-get install nvidia-common
sudo apt-get install xserver-xorg-video-nouveau
sudo apt-get install --reinstall libgl1-mesa-glx libgl1-mesa-dri xserver-xorg-core
Reconfigure the X server.
sudo dpkg-reconfigure xserver-xorg

**Comment by dnschneid** [comment]
Glad you got it fixed, but could you provide the full output of `croutonversion` for our reference?
