### ISSUE TITLE
when xiwi and xfce targets are specified on a precise chroot, extension target is not brought in

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1464]
On Samsung ARM, creating a new precise chroot on stable channel with:

sudo sh ~/Downloads/crouton -t xiwi,xfce

the `extension` target is not automatically added as a target, but can be added manually after the install completes. With trusty, it does install extension with just xiwi,xfce -r trusty -n trusty

chronos@localhost ~ $ crv.sh
host: /home/chronos/user/Downloads/Insufficient permissions to refresh crouton installer.
crouton: version 1-20150301132939~master:80da699e
-------------------------------------------------------------
chroot name: precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150301132939~master:80da699e
release: precise
architecture: armhf
xmethod: xiwi
targets: xiwi,xfce
host: version 6457.107.0 (Official Build) stable-channel daisy 
-------------------------------------------------------------
chroot name: trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150226194717~master:841ff620
release: trusty
architecture: armhf
xmethod: xiwi
targets: xiwi,extension,xfce
host: version 6457.107.0 (Official Build) stable-channel daisy 
-------------------------------------------------------------
chronos@localhost ~ $ sudo find / -name targets
/home/user/a8db6489ef3e81899f90920a27a0661654371a2c/crouton.unbundled/targets
/home/user/a8db6489ef3e81899f90920a27a0661654371a2c/Downloads/crouton.unbundled/targets
/home/.shadow/a8db6489ef3e81899f90920a27a0661654371a2c/mount/user/crouton.unbundled/targets
/home/.shadow/a8db6489ef3e81899f90920a27a0661654371a2c/mount/user/Downloads/crouton.unbundled/targets
/home/chronos/u-a8db6489ef3e81899f90920a27a0661654371a2c/crouton.unbundled/targets
/home/chronos/u-a8db6489ef3e81899f90920a27a0661654371a2c/Downloads/crouton.unbundled/targets
/home/chronos/user/crouton.unbundled/targets
/home/chronos/user/Downloads/crouton.unbundled/targets
/mnt/stateful_partition/crouton/chroots/trusty/etc/crouton/targets
^Cchronos@localhost ~ $ cat /mnt/stateful_partition/crouton/chroots/precise/etc/crouton/targets
xiwi,xfce
chronos@localhost ~ $

**Comment by divx118** [comment]
Only targets specified on the command line will be visible in `/etc/crouton/targets` This doesn't mean extension is not installed. So if you specify only - t xiwi,xfce those will only visible in `/etc/crouton/targets` this will be the same for all releases.  
Does the precise chroot work without adding the extension target afterwards?

BTW I just checked to be sure myself and for me it works, but of course like explained above only xiwi and xfce in the tagets file. Tested on precise and trusty.

**Comment by dnschneid** [comment]
While /etc/crouton/targets only has explicitly-selected targets, the /.crouton-targets file has a dump of all of the installed targets, including those installed as dependencies.  If your chroot is encrypted, the .crouton-targets file is only accessible from *outside* the chroot, and is used to figure out what chroot to launch, for example, when using startxfce4.

**Comment by tedm** [comment]
Yes, it does run, mine is not encrypted, so should we fix edit-chroot ? How will extension and other targets be updated if they're not in the targets file? Or is extension not really a target, but rather a dependency on xiwi, so whenever xiwi is updated, extension will be updated?

I'm re-installing trusty with xiwi,xfce to see if it adds extension to the targets file as I thought it did automatically.

edit-chroot -al output:

crosh> shell
chronos@localhost / $ sudo edit-chroot -al
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150301132939~master:80da699e
release: precise
architecture: armhf
xmethod: xephyr
targets: xephyr,xiwi,xfce
host: version 6457.107.0 (Official Build) stable-channel daisy 
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
name: trusty
encrypted: no

**Comment by tedm** [comment]
yep, it's there:

chronos@localhost /mnt/stateful_partition/crouton/chroots/precise $ sudo cat .crouton-targets
xephyr
x11
audio
core
xiwi
x11
extension
xfce
gtk-extra
post-common

Is there a reason why we don't copy these to /etc/crouton/targets?

**Comment by dnschneid** [comment]
Mainly because dependencies in the past shouldn't result in required targets in the future.  The stuff in /etc/crouton/targets reflects user intent.

**Comment by tedm** [comment]
Since the user can't remove a target, I guess the purpose of /etc/crouton/targets is to show what they explicitly installed as a reminder? It seems counter-intuitive since the user sees things like audio being compiled and updated, even though the user never added audio as a target. Is there a list showing which user selected targets will bring in which dependencies?

**Comment by tedm** [comment]
@divx118 You're correct, trusty, like precise, is pulling in extension (shows in the . (dot) file), and is not putting it in /etc/crouton/targets. So it is behaving like precise.

**Comment by DennisLfromGA** [comment]
@tedm,

> Is there a list showing which user selected targets will bring in which dependencies?

Yes, when you run crouton with the '-t list' option, it shows the targets/DEs and their prerequisites (Requires:).

**Comment by tedm** [comment]
@DennisLfromGA yes it is there, but I'm not sure pre-requisite or Requires is the clearest wording, since a higher level DE target will automatically bring them in.

For example, by specifying -t xfce I get a lot of other targets, which is good, but if I didn't know to look in the dot file, I wouldn't know that xfce brought them in by the current wording.

By specifying -t help, I can see that xfce requies gtk-extra, and then that gtk-extra requires x11, then x11 requires xephyr, then xephyr requires audio and audio requires core but Crouton is smart enough to install all of these automatically, and put what I specified in /etc/crouton/targets, and all targets in the dot file, sometimes duplicated (in the dot file), not sure if in the actual chroot, but seems to resolve itself, in the case of x11.

I would suggest that the -t help or usage syntax were expanded to clarify that if for example, xfce or another DE target is specified, that it will automatically bring in it's dependencies, which on a new crouton -t xfce chroot would be these targets: x11, xephyr, audio, core, and gtk-extra, otherwise it seems like I would need to specify them individually as -t parameters.

And then after installation is successful, perhaps just before the text providing your start* script usage, a note that your specified targets can be seen at /etc/crouton/targets and your full list of targets installed at [path of dot file].

**Comment by yisheng-on-linux** [comment]
*that it will automatically bring in it's dependencies, which on a new crouton -t xfce chroot would be these targets: x11, xephyr, audio, core, and gtk-extra, otherwise it seems like I would need to specify them individually as -t parameters.*

I agree. I just did an install for a friend and from the target descriptions it sounds as if the user is responsible and advised to select the prereqs. ALSO, I keep hearing xephyr isn't required except on ARM, but it looks like it gets installed if one chooses xfce you get xephyr...

I've scratched my head everytime I've installed and I avoid other's questions about what they need to install whenever I'm called to help... ;)

**Comment by tedm** [comment]
@yisheng-on-linux I appreciate the abstraction in that the users' intended targets are tracked (in /etc/crouton/targets) independently of what the current required prerequisites are pulled down in .crouton-targets, so theoretically future upgrades could be more efficient while providing the same intended functionality.

However, observing usage, is that many users read the terse -t help list of targets top down and end up with a longer list of targets than they need, eliminating the potential future benefit of the abstraction.

I think xephyr shouldn't be installed automatically if your platform supports xorg or a faster xmethod. Perhaps it's a channel or platform specific issue at this time.

**Comment by divx118** [comment]
@tedm Xephyr isn't installed on devices that support xorg or you must
specify it with -t.

**Comment by tedm** [comment]
@divx118 Thanks, that's what I thought. I only have an ARM system, so no xorg support, so @yisheng-on-linux must have specified xephyr with -t at some point if we're sure that the xfce target is not pulling it in on xorg supported platforms?
