### ISSUE TITLE
How to use go into Unity Desktop using enter-chroot command

### ISSUE THREAD

**Issue by qAp** [dnschneid/crouton#1466]
Hi,
My chroot is called trusty1.
```sudo startunity``` takes me to a Unity session.  How do I do the same thing using the ```enter-chroot``` command?

```sudo enter-chroot -n trusty1``` just takes me to a terminal inside the browser and does not take me to a normal Unity session.

Thanks

**Comment by divx118** [comment]
sudo enter-chroot -n trusty1 startunity However you can also pass the -n to
the startscript like sudo startunity -n trusty1 So why do you want to use
enter-chroot?

**Comment by qAp** [comment]
Ok, thanks.  I was just a little bit confused because ```sudo startunity``` makes no reference to a particular chroot, but I guess a chroot can have an unity and/or xfce desktop, so that also has to be specified.

**Comment by tedm** [comment]
@qAp sudo start* scripts will use the first alphabetical chroot that you have if -n [optionalchrootname where default name is releasename] is not specified. If you have other chroots that start with letters or numbers ahead of "trusty1" then that chroot will start.

**Comment by DennisLfromGA** [comment]
Yup, that's why I sometimes name or rename my chroots with a number prefix,
like '1-trusty' so I know it'll get launched if I'm too lazy to use the '-n
chrootname' each time.

On Wed, Mar 4, 2015 at 1:15 PM, tedm <notifications@github.com> wrote:

> @qAp <https://github.com/qAp> sudo start* scripts will use the first
> alphabetical chroot that you have if -n [optionalchrootname where default
> name is releasename] is not specified. If you have other chroots that start
> with letters or numbers ahead of "trusty1" then that chroot will start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1466#issuecomment-77213381>.
>



-- 
*DennyL@GMail*

**Comment by dnschneid** [comment]
It's the alphabetically first chroot *that has the requisite target installed*.  So if you have 1-trusty (with xfce installed) and 2-unity (with unity installed) and run `startunity`, 2-unity will launch.

**Comment by DennisLfromGA** [comment]
Okay, sorry to confuse things.
If both 1-trusty & 2-unity have 'unity' installed, for example, then would 1-trusty/unity get launched when you run `sudo startunity` ?

**Comment by dnschneid** [comment]
Yep!

**Comment by jakman** [comment]
I have gotten to the point where I am trying to load my first chroot. Command is:
schroot -c precise_i386 -u root
I keep getting authentication errors. I am using my user password when prompted...still doesnt work. Any advice?

Jeff

**Comment by MeneerJansen** [comment]
Start your chroot with the sudo command. Something like:
`sudo enter-chroot startxfce4`
Or even better:
`sudo startxfce4`
You are starting your chroot as a regular user in ChromeOS.

**Comment by jakman** [comment]
Meneer,

So just to be clear, I was open shell and launching my session with sudo startunity. Are you saying use the sudo enter command above from the shell or from a terminal window? In your example what is startxfce4? For me that would be startunity correct? There is no need to specify my chroot name? How do I verify that the chroot is loaded.

Thanks for your assistance...

Jeff K

**Comment by MeneerJansen** [comment]
If I understand your English correctly then: 
1. Open a crosh terminal in ChromeOS (Ctrl Alt T)
2. Type "shell" to go into a shell
3. And then type the following in the shell:
`sudo startunity`
You do not have to specify the chroot name (if you have only one chroot).

**Comment by jakman** [comment]
I know this is gonna sound crazy Meneer but once installed...what do I do with a chroot??

**Comment by DennisLfromGA** [comment]
@jakman - That does sound a little crazy ;) Try this link: http://goo.gl/D9F2Vo
