### ISSUE TITLE
Changing passwords for encrypted chroot

### ISSUE THREAD

**Issue by iowamv** [dnschneid/crouton#1467]
I recently encrypted my chroot. Now when I enter the chroot, I am prompted for two passwords, one right after the other. I'd like to change them both, if possible (or even better, get rid of the first one and keep the encryption passphrase). 

I read the comments re: this issue: https://github.com/dnschneid/crouton/issues/344. Is the first password I'm prompted for the "dev password"? If so, sounds like it cannot be removed. Can it be changed?

Dennis' solution to change the encryption passphrase seems easy enough-- is that the way to go?
He wrote 

> I think you can change the encryption password by using the '-e' option on
> your existing chroot like this -

>   sudo sh -e ~/Downloads/crouton -e -u*

Thanks.

Mark

**Comment by dnschneid** [comment]
You can change the password using `sudo edit-chroot -e chrootname`, but you'll still have to type in two passwords.  #1399 is probably what you want to monitor.

**Comment by iowamv** [comment]
Thanks! And thanks for giving us crouton-- can't begin to tell you how much I value it.
