### ISSUE TITLE
Feature Request for the Crouton Integration App

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1468]
I just learned a few days ago, that the App put a context windowed docked icon at the bottom of the screen, and for those of us users who enter-chroot a lot, if a chroot terminal (for simplicity, let's say the default chroot, first alphabetical by name, etc.), an enter-chroot option were there, or since the lower icon isn't always there, perhaps on the block "C" browser icon drop down, have an enter-chroot selection, in addition to any current running chroot xiwi windows?

This 1-gesture feature could save these keystrokes ctrl alt t, shell, sudo enter-chroot, and then mouse/thumb window resizing (assuming it used a `standard` window size, as mentioned in the xiwi-app threads).

**Comment by DennisLfromGA** [comment]
Just to clarify - are you talking about the 'crouton integration' app figuring out what chroot(s) you have installed and putting a 'enter-chroot' option in a menu for that non-running chroot?

**Comment by tedm** [comment]
@DennisLfromGA yeah. One way would be when the browser is opened, the app runs an edit-chroot -al in the background to find info about the installed chroots, then either in the dock, or the extension bar icon, it has text or an icon for an enter-chroot terminal window. For an encrypted chroot, maybe it shows a lock icon indicating that it can't open it, or will require a password to enter.

**Comment by DennisLfromGA** [comment]
If this is doable, then why stop at just adding 'enter-chroot' to the menu, find the 'start*' scripts in `/usr/local/bin` and add them to the list also :)

**Comment by tedm** [comment]
well, we don't want to make things *too* easy ;)

**Comment by dnschneid** [comment]
#66 #369 #847 #972 and guess what, it's still not possible because it still runs afoul of Chromium OS's core security model.

**Comment by DennisLfromGA** [comment]
Uh, oh - guess we got told :(

**Comment by tedm** [comment]
@DennisLfromGA Yeah, Zilog8 defined it pretty well in #369 only a year and a half ago ;) @dnschneid you mentioned commands can be on wallpaper in #369, how is this done?

**Comment by dnschneid** [comment]
You literally make a wallpaper with the commands listed on it, so when it comes time to open a shell, you can remember what they are...

**Comment by tedm** [comment]
@dnschneid lol, I don't get it. What if the shell is covering the wallpaper? ;)

**Comment by dnschneid** [comment]
Foiled!  Or you can use the []|| key to take a peek :)

**Comment by yisheng-on-linux** [comment]
I package everything up in simple scripts and put in /usr/local/bin in ChromeOS and then it's very quick and easy....

And there are a few nice tools that don't require add'l libs that can be borrowed from the chroot, put in /usr/local/bin and run on the Chrome side. Makes the Chrome side *almost* fun. ;)

**Comment by DennisLfromGA** [comment]
@yisheng-on-linux - I stick '[busybox](http://www.busybox.net/downloads/binaries/latest/)' in /usr/local/bin and make links to the commands I need/use.

Here's just a glimpse of some I have:
```
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 unzip -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 usleep -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 vconfig -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 vlock -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 volname -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 wall -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 watchdog -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 whois -> /usr/local/bin/busybox*
lrwxrwxrwx 1 root    root   22 Dec 10 09:55 zcip -> /usr/local/bin/busybox*
```

**Comment by yisheng-on-linux** [comment]
Cool. I will look into that! Thanks.

**Comment by tedm** [comment]
@DennisLfromGA Thanks for this Pro Tip!!

**Comment by Xenataur** [comment]
Care to share the scripts @yisheng-on-linux? Sorry, I'm a total linux noob. Ideally I'd like to have an icon that lives in my dock that runs the shell script for me (I'm lazy and will be running `start xfce4` several times per day when school starts again).

**Comment by Venryx** [comment]
Having an icon in the dock that auto-starts crouton is in fact possible, if you're fine with locally/manually installing a modified version of the Secure Shell app: https://github.com/dnschneid/crouton/issues/369#issuecomment-349793600
