### ISSUE TITLE
Trusty chroot, now want to add keyboard extension

### ISSUE THREAD

**Issue by certen** [dnschneid/crouton#1469]
I saw that it is an option to create chroots with -t xfce,keyboard, extension

I only used -t xfce when I created my chroot, and now I see the reason they exist and I want to use them to my existing chroot. 

Would it be possible to add other targets (keyboard,extension in that case) to existing chroot ?

Or is it possible to execute the commands directly instead?

**Comment by divx118** [comment]
I assume you already noticed adding additional targets can be done with updating the chroot and specifying the targets you want to add. `sudo sh ~/Downloads/crouton -t keyboard,extension -u -n <chrootname>`
