### ISSUE TITLE
Chrome OS not responding when back from Ubuntu

### ISSUE THREAD

**Issue by viki53** [dnschneid/crouton#1473]
Hi,

First I wanna say good job to make this work so smoothly in general. Unfortunately I'm getting some weird behavious right now...

Since this morning when I get back on Chrome OS from crouton (without quitting it) I find that I can't type anymore except to enter my password (as it came back from sleep both times). But the key combination to switch to Ubuntu works fine and I can still type in it (which I'm doing right now, as the bug appeared for the second time -- this morning I just rebooted the laptop without thinking any further).

As I'm writing this message I tried different and I thought was a bug linked to the keyboard seems more like a global Chrome lag. I can open the application drawer and the notifications but that's pretty much all. The tabs in Chrome become unresponsive and I get an alert asking me if I want to close them or wait.

I trie closing all the tabs (leaving the browser totally closed -- even the shell, as Ubuntu is running in the background) and all the Chrome OS apps but it didn't change anything: only Ubuntu works properly.

The only thing that changed recently is that I tried grive yesterday (but removed it just after) and installed Insync yesterday night, which is running right now and syncing some of my Google Drive folders (as that's the only way I found to access these files from Ubuntu, even though Chrome OS allows direct access to them).

Any idea what might be causing this?

**Comment by smibarber** [comment]
Can you post the output of `croutonversion` from your chroot?

**Comment by viki53** [comment]
> crouton: version 1-20141208100324~master:7b8ffff0   
> release: trusty   
> architecture: amd64  
> targets: audio,chrome,xfce,keyboard,touch  
> host: version 6680.58.0 (Official Build) stable-channel peppy

**Comment by Watney** [comment]
You might try removing the ``touch`` target. I tried it and found it messed with everything. 

I can't tell you how to *remove* the target. I deleted the chroot and started over.

**Comment by DennisLfromGA** [comment]
It looks like the '*touch*' target installs the 'touchegg' package and
creates a file named '/etc/touchegg.conf'.

On Thu, Mar 5, 2015 at 4:13 PM, Watney <notifications@github.com> wrote:

> You might try removing the touch target. I tried it and found it messed
> with everything.
>
> I can't tell you how to *remove* the target. I deleted the chroot and
> started over.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1473#issuecomment-77452774>.
>



-- 
*DennyL@GMail*

**Comment by rmkraus** [comment]
I'm having this same issue with no touch installed. I have an Asus C300. croutonversion output is below:

```bash
crouton: version 1-20150423153254~master:2f55723c
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,x11,kde,keyboard
host: version 6812.75.2 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Tue Apr 14 20:45:15 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
```

**Comment by divx118** [comment]
@rmkraus I think you are experiencing #1475 please respond to that issue if you can confirm it is the same so we can reopen it.

**Comment by rmkraus** [comment]
I believe I am experiencing that issue. Thanks.
