### ISSUE TITLE
crouton prints out a LOT of "croutonwebsocket error:" (image attached)

### ISSUE THREAD

**Issue by dragonloverlord** [dnschneid/crouton#1476]
I have highlighted the rather annoying mass print out of error messages. Whether or not they mean something I can not say. But they are printed out rather rapidly and at random intervals.

The other stuff is just printed out every time I minimize the chroot window.

crouton is fully updated as of this posting so I don't think this is caused by an outdated crouton install.

![screenshot 2015-03-05 at 5 14 53 pm](https://cloud.githubusercontent.com/assets/2529736/6515848/75fdcc4c-c35b-11e4-8b6a-e4fc3c79f086.png)

**Comment by Watney** [comment]
This might be the same as #1475

**Comment by dragonloverlord** [comment]
The image I originally attached did not show the full error messages.

This is more like what I am seeing:

![screenshot 2015-03-06 at 7 49 06 pm](https://cloud.githubusercontent.com/assets/2529736/6539088/0a228a82-c43a-11e4-8f37-18410e1bf641.png)

**Comment by dnschneid** [comment]
Please post the output of `croutonversion`...I don't think your crouton is fully up-to-date.  It looks like you have a pre-xiwi-app build.
