### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by tonyxue** [dnschneid/crouton#1477]
The new xiwi window app is working with most of the apps but not with Atom(The one made by Github) as I discovered.

I failed to launch Atom and in the log

``` WebSocket connection to 'ws://localhost:30012/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED ```

appeared several times.

This only happened with Atom so far. It weird that I could still launch Chrome, which Atom is based on.

Anyone has any idea?

**Comment by DennisLfromGA** [comment]
I'm not familiar with Atom, is it the text editor? There seems to be a number of them on github.
I've had trouble with xiwi and apps that want to run in the background. If the app has a foreground option, you might try using that - it worked for me with conky.
The atom text editor looks to have a -f or foreground option, that might work.

**Comment by tonyxue** [comment]
Yes it is the text editor. Made officially by Github @ atom/atom or atom.io.
That worked, thanks! @DennisLfromGA

**Comment by tonyxue** [comment]
@DennisLfromGA And maybe you can put this little notice somewhere in the wiki? That might be helpful for others.

**Comment by Watney** [comment]
@DennisLfromGA maybe we should create a Wiki entry about the new xiwi app-in-a-window. It's such a cool feature and is easy to miss. @tonyxue observation would be right at home in the entry

**Comment by DennisLfromGA** [comment]
I added a little footnote [1] to the page to, hopefully, explain the need to run 'xiwi-apps' in the foreground. Please feel free to embellish if you like, it doesn't sound really clear to me.
