### ISSUE TITLE
-e encryption and mounting chroots/name on a different system

### ISSUE THREAD

**Issue by yisheng-on-linux** [dnschneid/crouton#1478]
Pardon my ignorance if this is obvious. I want to take the usb drive with the encrypted (-e option) chroot and mount it opened on another system to work on the files within.

I looked at the crouton scripts and tried the same options as I found. I am familiar with ecryptfs to a degree and do a lot of mounting of my own ecryptfs drives.
However, nothing works. I have tried every variation when prompted and the best I get is it mounted with encrypted filenames listed (obviously it isn't decrypted). I've tried aes with all bit lengths, passthrough or not, filename encryption (or not just to see), etc.

What am I missing and is there a special consideration I need to know about to do this?

TIA

**Comment by dnschneid** [comment]
See #1482 for tips.  You're probably not extracting the sig from the .ecryptfs file in the unencrypted chroot directory.
