### ISSUE TITLE
Window preview size becomes actual size

### ISSUE THREAD

**Issue by tonyxue** [dnschneid/crouton#1479]
![screenshot 2015-03-06 at 19 17 50](https://cloud.githubusercontent.com/assets/2350816/6524709/972edfe6-c437-11e4-868d-1817555c9508.png)

This sometimes happens when I try to use 'three-finger scrolling' to switch out of a crouton tab, even not in full screen mode. And seems it started to happen after the `xiwi-app` branch is installed. But I'm not sure whether it is a crouton bug or an upstream bug.

Any idea?

**Comment by smibarber** [comment]
Did you do a three finger swipe up? That triggers the window switching overview mode, same as hitting the switch window key next to brightness down.

**Comment by divx118** [comment]
@smibarber I think you mean three finger swipe down. At least on my chromebook.

**Comment by smibarber** [comment]
Perhaps, I use Australian scrolling :)

**Comment by divx118** [comment]
Ah didn't know it inverted the three finger swipe too.

**Comment by tonyxue** [comment]
> Did you do a three finger swipe up? That triggers the window switching overview mode, same as hitting the switch window key next to brightness down.

Yes I did. But every time this happened I actually had already swiped again to swipe all the windows back to the normal size, out of preview mode. And sometimes some window was "forgotten" to set back to the normal mode.

The window in the screenshot is in the normal mode. I could actually click on the tiny tiny 'maximize' button to bring this window back.

I closed other windows for taking the screenshot so it might not be that obvious.

Is this what supposed to happen? I don't really think so.

**Comment by smibarber** [comment]
Definitely not intentional behavior, but also probably not caused by crouton, even with xiwi-app. Mind filing a bug at https://crbug.com/new ?

**Comment by tonyxue** [comment]
No problem. And I'll try to produce it intentionally.

**Comment by tonyxue** [comment]
![screenshot 2015-03-10 at 11 38 22](https://cloud.githubusercontent.com/assets/2350816/6568861/295b3d30-c71a-11e4-826e-bd5e6bd24dba.png)
![screenshot 2015-03-10 at 11 38 04](https://cloud.githubusercontent.com/assets/2350816/6568860/29543bde-c71a-11e4-9ee3-85f0be265c68.png)
Em... It happened again.
This time I was in full-screen mode of xfce. I swiped and then put the pointer onto the Chrome window and touch the touchpad(Didn't push down).

**Comment by divx118** [comment]
And it happened just now for me with no chroot running. However I was using vnc viewer app.  
My chromeos version:
```
Version 43.0.2334.0 dev (64-bit)
Platform 6885.0.0 (Official Build) dev-channel falco
Firmware Google_Falco.4389.92.0
```
I will report to the google bug.
