### ISSUE TITLE
SD Card doesn't mount after sleep/waking up under KDE

### ISSUE THREAD

**Issue by me-lina** [dnschneid/crouton#1480]
Hi,

I've got a Problem with  mounting my SD Card.
FIrst: I've got a Toshiba Chromebook 2 and a SD Card which I formatted to ext4. I've set up KDE (trusty) via Crouton.

When I close the lid of the chromebook under Chrome OS and open it a little bit later again, the SD Card is mounted again.
But when I am working under KDE (I've also tried Unity before, it doesn't matter), and close the lid, the SD card can't become mounted after waking up the Chromebook again. In KDE I get an Error, when I try to mount it and in Chrome OS the SD card just disappeared. I can only mount the SD card again if if put it out (I don't do that anymore, I don't want to damage the card) or reboot the whole Chromebook. :(

Can you help me fixing this?

Regards
Melina

**Comment by Watney** [comment]
this appears to be a dup of #288

**Comment by smibarber** [comment]
Yep, problems with SD card on resume are being tracked in that issue.
