### ISSUE TITLE
Updated chroot with extension and now it doesn't even start!

### ISSUE THREAD

**Issue by rubanunes** [dnschneid/crouton#1481]
I've installed a trusty, xfce an xiwi chroot and worked fine except it wasn't integrating with the Chrome extension. It was giving me some errors upon entering the chroot and on the extension too.
![extension error image]
(https://lh6.googleusercontent.com/nkTMO8JBIRiqMfUj5kIXLwpz0ae66P3as3b5WkbFVLOgNX-Z-5hrRko8XOStDU5XyVYJKKLoayc=w1342-h557)

But after running `sudo sh ~/Downloads/crouton -t extension -u -p /media/removable/USB\ Drive/ -n trusty`, it did some installing and uninstalling and never worked again.

```
sudo sh /media/removable/USB\ Drive/bin/startxfce4 
Entering /media/removable/USB Drive/chroots/trusty...
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Mar 2 08:12:04 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=f13fe4dc-058d-ff4e-b597-e7ed53fe9aa0/PARTNROFF=1 hashtree=PARTUUID=f13fe4dc-058d-ff4e-b597-e7ed53fe9aa0/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=d699dbcb9436363d156f673d2974e9135446f31a salt=407d7eecf7f90be22e8a935e73e6064eebbc500bb76a9e4a1f47178f61629f4f" noinitrd vt.global_cursor_default=0 kern_guid=f13fe4dc-058d-ff4e-b597-e7ed53fe9aa0 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Mar  6 15:51:01 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /media/removable/USB Drive/chroots/trusty...
```

Did I messed up upon updating the chroot? Thanks.

**Comment by DennisLfromGA** [comment]
Have you installed the 'crouton integration' extension from the Chrome Web
store pointed to in the error output (http://goo.gl/OVQOEt)? That's what it
seems to be complaining about.

On Fri, Mar 6, 2015 at 11:12 AM, Ruben Nunes <notifications@github.com>
wrote:

> I've installed a trusty, xfce an xiwi chroot and worked fine except it
> wasn't integrating with the Chrome extension. It was giving me some errors
> upon entering the chroot and on the extension too.
> [image: extension error image]
> <https://camo.githubusercontent.com/39864edb1e3df8bc72daeaf9d6474304a971c877/68747470733a2f2f6c68362e676f6f676c6575736572636f6e74656e742e636f6d2f6e6b544d4f384a42495269714d66556a356b49584c77707a306165363650336173336235576b6246564c4f674e582d5a2d356872526b6f38584f5374445535587956594a4b4b4c6f6179633d77313334322d68353537>
>
> But after running sudo sh ~/Downloads/crouton -t extension -u -p
> /media/removable/USB\ Drive/ -n trusty, it did some installing and
> uninstalling and never worked again.
>
> sudo sh /media/removable/USB\ Drive/bin/startxfce4
> Entering /media/removable/USB Drive/chroots/trusty...
> /usr/bin/startxfce4: Starting X server
>
>
> X.Org X Server 1.15.1
> Release Date: 2014-04-13
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Mar 2 08:12:04 PST 2015 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=f13fe4dc-058d-ff4e-b597-e7ed53fe9aa0/PARTNROFF=1 hashtree=PARTUUID=f13fe4dc-058d-ff4e-b597-e7ed53fe9aa0/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=d699dbcb9436363d156f673d2974e9135446f31a salt=407d7eecf7f90be22e8a935e73e6064eebbc500bb76a9e4a1f47178f61629f4f" noinitrd vt.global_cursor_default=0 kern_guid=f13fe4dc-058d-ff4e-b597-e7ed53fe9aa0 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3
> Build Date: 12 February 2015  02:49:29PM
> xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support)
> Current version of pixman: 0.30.2
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Mar  6 15:51:01 2015
> (++) Using config file: "/etc/X11/xorg-dummy.conf"
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Initializing built-in extension Generic Event Extension
> Initializing built-in extension SHAPE
> Initializing built-in extension MIT-SHM
> Initializing built-in extension XInputExtension
> Initializing built-in extension XTEST
> Initializing built-in extension BIG-REQUESTS
> Initializing built-in extension SYNC
> Initializing built-in extension XKEYBOARD
> Initializing built-in extension XC-MISC
> Initializing built-in extension SECURITY
> Initializing built-in extension XINERAMA
> Initializing built-in extension XFIXES
> Initializing built-in extension RENDER
> Initializing built-in extension RANDR
> Initializing built-in extension COMPOSITE
> Initializing built-in extension DAMAGE
> Initializing built-in extension MIT-SCREEN-SAVER
> Initializing built-in extension DOUBLE-BUFFER
> Initializing built-in extension RECORD
> Initializing built-in extension DPMS
> Initializing built-in extension Present
> Initializing built-in extension DRI3
> Initializing built-in extension X-Resource
> Initializing built-in extension XVideo
> Initializing built-in extension XVideo-MotionCompensation
> Initializing built-in extension SELinux
> Initializing built-in extension XFree86-VidModeExtension
> Initializing built-in extension XFree86-DGA
> Initializing built-in extension XFree86-DRI
> Initializing built-in extension DRI2
> Loading extension GLX
> xf86: found device 0
> /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Unable to start display, make sure the crouton extension is installed
> and enabled, and up to date. (download from http://goo.gl/OVQOEt)
> Running exit commands...
> /usr/bin/xinit: connection to X server lost
> Hangup
>
> waiting for X server to shut down Hangup
> Hangup
> (EE) Server terminated successfully (0). Closing log file.
>
> Unmounting /media/removable/USB Drive/chroots/trusty...
>
> Did I messed up upon updating the chroot? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1481>.
>



-- 
*DennyL@GMail*

**Comment by rubanunes** [comment]
Yes I have, otherwise I couldn't take that SS.

**Comment by DennisLfromGA** [comment]
I have had this happen occasionally, it would make several attempts to
connect and give up. The next time, or the time after, it would work -
don't know why exactly.

On external media, I sometimes have better luck if I 'cd' to the media
first and then try to start it - cd /media/removable/USB\ Drive/;
sudo ./bin/startxfce4

On Sat, Mar 7, 2015 at 12:47 AM, Ruben Nunes <notifications@github.com>
wrote:

> Yes I have, otherwise I couldn't take that SS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1481#issuecomment-77675117>.
>



-- 
*DennyL@GMail*

**Comment by rubanunes** [comment]
Yeah... I reinstalled everything again. Forgot to make the tarball but either way.

Now everything runs again but it keeps failing to connect to the extension sometimes...
```
Loading extension GLX
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Error: target STRING not available
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
```
Don't know even why is this happening. Does anyone have an idea?

**Comment by divx118** [comment]
That is normal, it needs a few times to try and connect. At least I never seen it otherwise.

**Comment by rubanunes** [comment]
Ok. Solved then. Thanks.
