### ISSUE TITLE
Manually mounting encrypted chroot

### ISSUE THREAD

**Issue by pooralfie** [dnschneid/crouton#1482]
I have an encrypted chroot I'd like to mount from another chroot manually but I'm not sure what parameters (cipher, key bytes etc) are used when crouton encrypts the chroot. What do I need to add to
```mount -t ecryptfs /path/of/encrypted/chroot/ /path/of/mount/point/```
in order to be able to access the contents of the folder?

**Comment by DennisLfromGA** [comment]
Have you seen 'mount-chroot'?
```
mount-chroot [options] name [...]

Mounts one or more chroots into a root-only subdirectory of /run/crouton

Options:
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -e          If the chroot is not encrypted, encrypt it.
                If specified twice, prompt to change the encryption passphrase.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -n          Create the chroot if it doesn't exist.
    -p          Prints out the path to the mounted directory on stdout.
```

**Comment by DennisLfromGA** [comment]
If you haven't taken a look at '[mount-chroot](https://github.com/dnschneid/crouton/blob/master/host-bin/mount-chroot)' you might want to for some tips. The actual execution is done with this:

```
        mnt="ecryptfs_sig=$keysig,ecryptfs_fnek_sig=$fneksig"
        mnt="$mnt,ecryptfs_cipher=aes,ecryptfs_key_bytes=16"
        mnt="$mnt,ecryptfs_unlink_sigs,$MOUNTOPTS"

        if ! mount -i -t ecryptfs -o "$mnt" "$CHROOTSRC" "$CHROOT"; then
            error 1 "Failed to mount $NAME."
        fi
```

**Comment by pooralfie** [comment]
Thanks for the pointer, I did look through the scripts but somehow missed that. I'll see if I can figure it out, though I'm no shell script wiz and have no other experience with ecryptfs

**Comment by DennisLfromGA** [comment]
Unfortunately, me neither.

**Comment by yisheng-on-linux** [comment]
I will pick this up here vs my posting...
I've been through that script and as I said, tried manually using those parameters, but it didn't mount. I tried until I tired out. I will try again soon. I do a lot with ecryptfs on my things, so I'm not a noob with it, so hopefully I'll get it to work.

I am curious why the decision to do 16b instead of 32b....

**Comment by pooralfie** [comment]
I think I have an idea of the parameters that need to be used from the script but haven't had time to try it yet. Out of curiosity, what parameters do you believe it to be?

**Comment by pooralfie** [comment]
To me the parameters look like

`mount -i -t ecryptfs -o ecryptfs_sig=<sig>,ecryptfs_fnek_sig=<sig>,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs,rw,dev,exec,suid /path/of/encrypted/chroot/ /path/of/mount/point/`

Both sigs have been extracted from .ecryptfs and added to the session keyring. However whatever I try as the mountpoint, I either get the error `mount: No such file or directory` or `mount: Too many levels of symbolic links`

**Comment by drinkcat** [comment]
@yisheng-on-linux : 
> I am curious why the decision to do 16b instead of 32b....

AES 128 is good enough, and faster. Also, AES 256 appears to have a [potential weakness](https://www.schneier.com/blog/archives/2009/07/another_new_aes.html). Disclaimer: not a crypto expert...

@pooralfie: Can you provide the exact command you are trying to run (I mean, without the keys, but with the mount points...)?

**Comment by pooralfie** [comment]
as above with `/media/removable/sd_crouton/chroots/trusty.old/` as src and any mount point within `/media/removable/` as target gives the `Too many levels of symbolic links` error. Trying any mountpoint inside the chroot I'm trying to mount within eg `/home/<user>/enc_chroot/` `/mnt/enc_chroot/` and `/home/<user>/Downloads/enc_chroot/` etc gives the `No such file or directory`

**Comment by dnschneid** [comment]
Could you try mounting into a subfolder of /tmp instead?

**Comment by pooralfie** [comment]
attempting to mount in a subfolder of /tmp still gives
`mount: No such file or directory`

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
