### ISSUE TITLE
Xiwi and Java GUI applications

### ISSUE THREAD

**Issue by AlexSane** [dnschneid/crouton#1483]
Neither Eclipse, nor JetBrains IDEA are working in xiwi window (launched as `xiwi idea` inside chroot). The window is blank, but when I click on some hidden controls, some popups or drop downs are working.

I'm using trusty release.

**Comment by DennisLfromGA** [comment]
Does it work in the standard 'start*' launcher via xmethod:xiwi but not the in the 'xiwi-app'?

**Comment by AlexSane** [comment]
Not sure what you are talking about. It works perfectly in xfce working in xiwi.

**Comment by tmagara** [comment]
Same problem here. 
I suspect this bug is in Java side.
http://awesome.naquadah.org/wiki/Problems_with_Java

**Comment by tmagara** [comment]
I just found a workaround for this.
`$ sudo enter-chroot xiwi xterm -e "wmname LG3D;your-idea-directory/bin/idea.sh"`
 `wmname` can be installed with `suckless-tools` package in Ubuntu.

BTW,  this one did not work. I don't know why.
`$ sudo enter-chroot xiwi sh -c "wmname LG3D;your-idea-directory/bin/idea.sh"`

**Comment by DennisLfromGA** [comment]
I think it has to be a gui app.

On Wed, Mar 11, 2015 at 10:03 PM, Takafumi Magara <notifications@github.com>
wrote:

> I just found a workaround for this.
> $ sudo enter-chroot xiwi xterm -e "wmname
> LG3D;your-idea-directory/bin/idea.sh"
> wmname can be installed with suckless-tools package in Ubuntu.
>
> BTW, this one did not work. I don't know why.
> $ sudo enter-chroot xiwi sh -c "wmname
> LG3D;your-idea-directory/bin/idea.sh"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1483#issuecomment-78411071>.
>



-- 
*DennyL@GMail*

**Comment by AlexSane** [comment]
@tmagara Idea works perfectly, but after that I can't start xfce or any xiwi application

**Comment by drinkcat** [comment]
@tmagara : Does setting `_JAVA_AWT_WM_NONREPARENTING=1` fix the problem as well ? e.g.:
```
sudo enter-chroot xiwi sh -c "_JAVA_AWT_WM_NONREPARENTING=1 your-idea-directory/bin/idea.sh"
```

We probably do not want to run `wmname LG3D` by default (so if that's the only option, a wiki entry would be nice), but setting that environment variable is something we could do by default in crouton.

**Comment by AlexSane** [comment]
`_JAVA_AWT_WM_NONREPARENTING=1` does not work.
`wmname LG3D` works fine with `xterm`

**Comment by tmagara** [comment]
`_JAVA_AWT_WM_NONREPARENTING=1` works on Oracle JDK 8, but not on OpenJDK 7 unfortunately.
This bug is not crouton specific, anyway.

**Comment by dnschneid** [comment]
Yeah, ratpoison is showing its limitations in being a non-reparenting window manager.  I've seen issues with other software as well that waits for the ReparentWindow event notification before doing anything :\

I'm looking into switching to using i3 as the window manager for xiwi.

**Comment by dnschneid** [comment]
Please try the i3xiwi branch and see if you prefer this over the ratpoison solution.

**Comment by dnschneid** [comment]
Update with the latest crouton!  It's amazing!
