### ISSUE TITLE
[15894:15894:0309/205047:ERROR:browser_main_loop.cc(216)] Gtk: cannot open display: 

### ISSUE THREAD

**Issue by othode** [dnschneid/crouton#1485]
I did exactly as instructed
1) Format SD card as ext4
2) Open crosh
3) Type: "shell"
4) Type: "sudo sh -e ~/Downloads/crouton -t xfce -r trusty -p /media/removable/Crouton/" to install xfce trusty on the SD Card*
6) wait for installation to complete
7) Enter username and password
8) Type: "sudo sh -e '/media/removable/Crouton/bin/enter-chroot'" to enter the chroot
however, rather than entering into ubuntu, It remains in crosh

*Crouton is the name of the SD Card

**Comment by DennisLfromGA** [comment]
And what were those instructions?

**Comment by othode** [comment]
Nevermind, I figured it out.
I typed "sudo sh -e '/media/removable/Crouton/bin/startxfce4'" and it worked

**Comment by rubanunes** [comment]
After the enter-chroot you need to enter startxfce4.

**Comment by DennisLfromGA** [comment]
@rubanunes - That's one way to do it but @othode's remedy is the most direct.
