### ISSUE TITLE
Switching from crouton back to chromeos with external monitor causes crash

### ISSUE THREAD

**Issue by phreshbeatz** [dnschneid/crouton#1487]
On Version 41.0.2272.76 (64-bit) now.  I believe the problems only started after I allowed chromeos to update a few days ago.  When I switch from crouton to chromeos (using ctrl+alt+shift+back) it will cause a crash if my chromebook is plugged in to an external monitor.  By crash I mean chromeos will show a black screen for several minutes, then present a login screen.  All tabs will have closed, so it is like it has just rebooted.
If the chromebook is plugged into an external monitor but the native screen is also active, then switching from chromeos to crouton scrambles the display resolution, making chromeos nearly unusable but not causing a crash.
If the chromebook is not plugged into an external monitor, the behavior has been normal, so far.

So it seems like something wrong with the way it's handling the monitor.  I've updated the chroot (multiple times), powerwashed the chromebook, and updated xorg from the ppa.  I'm not sure what else to try.

**Comment by drinkcat** [comment]
Can you provide the output of `croutonversion`?

Is your Chromebook using freon yet? (what the output of `ls /dev/tty0`?)

**Comment by phreshbeatz** [comment]
ls /dev/tty0 finds tty0

croutonversion output:
crouton: version 1-20150304145447~master:550afdb3
release: precise
architecture: amd64
xmethod: xiwi
targets: gnome,extension,xiwi
host: version 6680.64.0 (Official Build) stable-channel falco

FYI the bug happens when i install without the xiwi or extension targets, too.

**Comment by phreshbeatz** [comment]
So unfortunately I"m not a Linux pro, so I can only list more descriptors of symptoms in the hopes that it means something to someone.  For example, when the chromebook has an external monitor and both are active, I mentioned that switching from crouton to chromeos scrambles the display resolution.  What I think is happening is that, instead of displaying the monitors side by side (Native monitor: native resolution, and External monitor: external resolution) it stacks the monitors instead (Native: top part of external and External: bottom part of external).  Closing the lid resets this (External monitor: external resolution).

**Comment by dnschneid** [comment]
Are you using the exact same resolution inside and outside the chroot?  It's quite likely that Chromium OS is getting confused when crouton changes the mode.

**Comment by phreshbeatz** [comment]
I certainly intend for the resolutions to be the same, but there is a mixup when chrome os takes back control.  Specifically it seems like chrome os tries to stack the monitors, and when it hands that back over to crouton, crouton gets confused, throws a "could not set monitor configuration" error, and ignores the bad resolution.

**Comment by dnschneid** [comment]
Filed [crbug/471078](https://code.google.com/p/chromium/issues/detail?id=471078).  Star it if you're interested.

**Comment by chromeuser** [comment]
The only way to switch back and forth between crouton and chromeOS while using an external monitor is to keep the chromebook screen open the entire time . 

If you close the chromebook screen you wont be able to switch back and forth using only an external monitor, you will get a black screen instead when you switch back to chromeOS. The way to deal with the black screen is to open your built in screen on the chromebook once you switch which will then either crash crouton or allow you to continue as usual. Occasionally the entire thing freezes up and you have to hard reset. This is why currently you should only run crouton on an external monitor if keep your chromebook built in screen on.
