### ISSUE TITLE
Popcorn Time Target

### ISSUE THREAD

**Issue by dortzur** [dnschneid/crouton#1488]
I would like to add Popcorn Time as a target.
I have a Chromebox in my living room and would like to access Popcorn Time the same way I do XBMC.
I tried to customize the XBMC target but to no avail.
It would also be nice if there was an easy way to add any program as launch target, couldn't quite figure it via just copying an existing target, as most of them are more complicated then just "run this program in full screen"

Crouton is really awesome by the way, and the only reason I have both a Chromebook and a Chromebox.

**Comment by DennisLfromGA** [comment]
@dortzur,

With the recent addition of the 'xiwi-app' branch, you should be able to launch nearly any gui linux app/program very easily from the crosh shell command line - as long as it doesn't want to kick-off in a background process. I don't know what the 'Popcorn Time' executable is but I run a 'conky' app using this: `sudo enter-chroot -b xiwi conky`

**Comment by reeved** [comment]
Thats quite cool :) 

But will the apps have GPU Acceleration?

**Comment by Watney** [comment]
@reeved the "xiwi-app" branch does not have GPU Acceleration.

**Comment by dortzur** [comment]
I think no GPU support is a major deal breaker  when trying to watch
movies, any alternatives?

**Comment by Watney** [comment]
@dortzur if your Chromebox has an Intel processor, as opposed to ARM, you can achieve GPU acceleration with the ``-t xorg``. This will put you into a Ubuntu chroot, where you can install Popcorn (see [this guide](http://www.webupd8.org/2014/05/install-popcorn-time-in-ubuntu-or.html)).

**Comment by jbaum98** [comment]
When I try to start Popcorn Time, it crashes with the error
```
[20841:0315/211629:ERROR:sandbox_linux.cc(142)] InitializeSandbox() called with multiple threads in process gpu-process
[20483:0315/211630:ERROR:breakpad_linux.cc(1225)] crash dump file written to /tmp/chromium-renderer-minidump-24d1074f7df0d1d7.dmp
Running exit commands...
/usr/bin/xinit: connection to X server lost
```
I think the issue comes from the multiple threads. A problem like that was solved for Sublime Text in #1445 but I'm not sure how to stop Node Webkit, which is powering Popcorn Time, from forking.

**Comment by dortzur** [comment]
@Watney  @DennisLfromGA I can run Popcorn Time easily from my unity target chroot. 
However what I'm looking for is a solution that would suit my girlfriend (non-technical user) similar to "startunity / startxbmc".
I would like ideally to be able to write "startpopcorn" and have a GPU enabled Popcorn Time instance run in full screen. I don't mind if it's simply a glorified launcher to my unity target chroot.
Any suggestions?

**Comment by Watney** [comment]
@dortzur this is a little cheesy, but Unity (along with most Linux distros) allow you to choose applications that launch on start-up. (See [this guide](http://askubuntu.com/questions/452661/where-is-start-up-applications-in-14-04-unity) at Ubuntu.)

Though admittedly, not the most elegant solution, you could put your "target" in the startup list, so it boots into the application automatically on ``sudo startunity``.

**Comment by DennisLfromGA** [comment]
@dortzur -

I successfully Popcorn-Time via modified 'xbmc' target.
My 'startpct' file is essentially this:
```
## ( the first part of the file doesn't change, just the last 2 lines ) ##
exec sh -e "`dirname "\`readlink -f "$0"\`"`/enter-chroot" -t xorg "$@" "" \
    exec xinit /usr/local/bin/Popcorn-Time
```
I've added the '-t xorg' argument to it since I think it'll probably run best in xorg but I have also run it using 'xiwi'. If you want to use a certain xmethod, you can hardcode it in the start file or enter it on the command line each time with the '-X' option.

My installation may be a bit different than yours though, I put the Popcorn-Time executable and db files in `/usr/local/src/popcorn-time/`, then made a softlink to it via `sudo ln -s /usr/local/src/pop-corn-time/Popcorn-Time /usr/local/bin/`.

Hope this works for you - and you score points your girlfriend ;)

**Comment by dnschneid** [comment]
Note: the `-t` with `enter-chroot` helps select which chroot to run based on their target list; it doesn't install any targets.

A target that automates the install akin to xbmc would be interesting, although I'm undecided whether I would add it to crouton or just keep it external (which you could use with -T...see #1027).

**Comment by DennisLfromGA** [comment]
@dortzur,

Sorry if I confused things, I didn't mean to infer that the `-t xorg` accompanying `enter-chroot` would install the 'xorg' target/xmethod. I just meant that using it there would ensure that it was already present in the chroot.

@dnschneid,

I also think it would be best to keep it external and use a target file with '-T'.
I think trying to incorporate it in crouton and accommodate each and every condition might be too complex and unnecessary.
