### ISSUE TITLE
Encrypted chroot takes up more space than original?

### ISSUE THREAD

**Issue by dragonloverlord** [dnschneid/crouton#1489]
I have recently encrypted my chroot and I am unsure if it is supposed to be bigger than the original non-encrypted chroot or not. So if this is natural then is it a crouton thing or just linux in general?

**Comment by yisheng-on-linux** [comment]
If I may answer... encryption can/will expand the original content. For instance, one can't take a filename which is at or near the filesystem limit for length and encrypt the filename - it will become longer and not usable. The man pgs for encfs and info on ecryptfs both specify a shorter limit for filenames then what the underlying fs has so when they are encrypted they don't exceed the fs limit.

Content should follow likewise.

**Comment by drinkcat** [comment]
Do you have hard data on this? Something like the output of `du` of the encrypted vs non-encrypted chroot...

On top of what @yisheng-on-linux said, another thing is that ecryptfs does not support sparse files. Depending on the content of your chroot, it may matter.
