### ISSUE TITLE
Chroot moved to SD, how to start it again

### ISSUE THREAD

**Issue by grosdod** [dnschneid/crouton#1492]
Dear All, 
I had a trusty xfce chroot working like a charm on my asus c200. I tried to move it to my sd card to save diskspace using 
sudo edit-chroot -m "/media/removable/SD Card/chroots" trusty
all seemed to be ok but i fail starting again my chroot using
sudo bash startxfce4 -c /media/removable/SD\ Card/chroots/
returns a "sh: Can't open //enter-chroot"
and typing "sudo sh /media/removable/SD\ Card/chroots/bin/startxfce4"
returns a "sh: Can't open /media/removable/SD Card/chroots/bin/startxfce4"

Thanks in Advance for heping.
Regards,

**Comment by plevesque** [comment]
Try doing mount /media/removable/SD\ Card/ -o,remount,exec.  by default Chrome OS does not allow binary to be execute on the SD card

**Comment by grosdod** [comment]
Thanks for helping.
No I got a 
"shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
bash: startxfce4: Transport endpoint is not connected"

Maybe an issue due to FAT32 format of my sd card instead of EXT ?

**Comment by DennisLfromGA** [comment]
>
> and typing "sudo sh /media/removable/SD\ Card/chroots/bin/startxfce4"
> returns a "sh: Can't open /media/removable/SD Card/chroots/bin/startxfce4"


'startxfce4' isn't a sub-directory of chroots, it's a sub-directory of
.../SD Card/

Try changing directories to the external media first -

    cd  /media/removable/SD\ Card/; sudo sh ./bin/startxfce4

-- 
*DennyL@GMail*
