### ISSUE TITLE
Feature Request: auto-start chroot with no window

### ISSUE THREAD

**Issue by stuartlynne** [dnschneid/crouton#1493]
I have a core, cli-extra chroot with a python server in it, that is working with auto-start using startcli and xorg.

It does not seem possible to get the auto-start to not open a window (which is easy to exit, but just one more thing to explain to my users.)

I may be missing something. But if not this would be a nice feature.

Thanks!

**Comment by DennisLfromGA** [comment]
I'm not sure I follow, when I auto-start my chroot DE, I don't have an extra window open.
If you can by-pass the cli shell and run a gui app directly, then you might try the new 'xiwi-app' approach with something like: `sudo enter-chroot xiwi [gui app]`.

**Comment by stuartlynne** [comment]
What I'm hoping to avoid is any window opening at all. The purpose of the
chroot is to have apache and an application specific python web server
running and available. All use of those is through the normal Chrome
browser in Chrome OS.

Currently I get the full screen terminal shortly after booting, and use
Control, Alt and <- to get out of it. Then login into Chrome OS in the
normal manner.

Failing that xiwi-app would appear to be a reasonable alternative. But that
presumably also means using start-user-session instead of
login-prompt-visible? I can try that as well.

Suggestions welcome.

Thanks!

On Thu, Mar 12, 2015 at 3:43 PM, DennisL <notifications@github.com> wrote:

> I'm not sure I follow, when I auto-start my chroot DE, I don't have an
> extra window open.
> If you can by-pass the cli shell and run a gui app directly, then you
> might try the new 'xiwi-app' approach with something like: sudo
> enter-chroot xiwi [gui app].
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1493#issuecomment-78668614>.
>



-- 
__________O___________
_______-\<,____________
_____(_)/_(_)___________
_________________________
Stuart_Lynne____<stuart.lynne@gmail.com>____604-518-1749(m)__604-461-7532(h)

**Comment by DennisLfromGA** [comment]
@stuartlynne,

 1. Do you have to manually issue commands in the cli session or does your web server start automagically?
 2. Do you just close down the cli session or leave it open and just switch back to chrome?

Either way, there is a crouton command you can use while in the chroot that will switch you back to Chrome OS via the command line - or in a script. The syntax & options are:

```
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
```

So, in your cli session or in your .bashrc script, you could run `croutoncycle cros` to switch back to Chrome OS.

**Comment by stuartlynne** [comment]
On Thu, Mar 12, 2015 at 8:32 PM, DennisL <notifications@github.com> wrote:

> @stuartlynne <https://github.com/stuartlynne>,
>
>    1. Do you have to manually issue commands in the cli session or does
>    your web server start automagically?
>
> Everything starts out of /etc/rc.local.


>
>    1. Do you just close down the cli session or leave it open and just
>    switch back to chrome?
>
> I just switch away with Control - Alt - <-


>
>
> Either way, there is a crouton command you can use while in the chroot
> that will switch you back to Chrome OS via the command line - or in a
> script. The syntax & options are:
>

I don't see that anywhere (standard crouton downloaded yesterday.)

Thanks!

> croutoncycle next|prev|cros|list|#
> Cycles through running graphical chroots.
>     next: switch to the next display
>     prev: switch to the previous display
>     cros: switch directly to Chromium OS
>     list: list all of the active displays and the associated chroot name
>     #: switch to the nth item in the list, zero-indexed
>     :#: switch directly to the chroot owning the specified display number
>
> So, in your cli session or in your .bashrc script, you could run croutoncycle
> cros to switch back to Chrome OS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1493#issuecomment-78775411>.
>



-- 
__________O___________
_______-\<,____________
_____(_)/_(_)___________
_________________________
Stuart_Lynne____<stuart.lynne@gmail.com>____604-518-1749(m)__604-461-7532(h)

**Comment by smibarber** [comment]
Why not use `enter-chroot <your python server command string here>`? That'd probably work even better since you could get Chrome OS's upstart to respawn it automatically if it dies.

**Comment by stuartlynne** [comment]
I tried enter-chroot but that failed to get the chroot started.

As an alternative... has anyone tried to adapt croshwindow to allow a crouton chroot to be started as an app?

My main goal is to make this painless to some end users who simply won't know what to do if they have to start the crouton chroot with the python application server manually in crosh. 

Either by automatically starting at boot or clicking on a menu icon. The latter would eliminate some additional setup (r/w root) as well.

**Comment by DennisLfromGA** [comment]
@stuartlynne -

> I don't see that anywhere (standard crouton downloaded yesterday.)

It's in your chroot: `/usr/local/bin/croutoncycle`, which is in your PATH; try it, you'll like it...

You may even be able to use it in your `/etc/rc.local` script to automagically switch back to Chrome OS after your server is started. Stick it at the end of the script something like this:
`sleep 30 && /usr/local/bin/croutoncycle cros`
I used the full path just in case...

> As an alternative... has anyone tried to adapt croshwindow to allow a crouton chroot to be started as an app?

Yes, instead of using the normal start script, like `sudo startunity`, instead use the new 'xiwi-app' to start it, like `sudo enter-chroot xiwi startunity`.

> Either by automatically starting at boot or clicking on a menu icon. The latter would eliminate some additional setup (r/w root) as well.

That's been 'invented' also but it *does* require 'r/w root' -
https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup

Also, forget about "clicking on a menu icon" - https://github.com/dnschneid/crouton/issues/847

**Comment by dnschneid** [comment]
@stuartlynne for your type of use-case, assuming you set up rc.local inside the chroot to launch your servers, `sudo enter-chroot -b sleep infinity` should launch and keep the servers running, after which you can safely close the window.

startcli is for starting an interactive session in a new VT environment.

@DennisLfromGA he's doing non-graphical stuff, so xiwi/startunity/croutoncycle/etc doesn't make a lot of sense here.

**Comment by DennisLfromGA** [comment]
Okay, I thought he was intent on using the cli gui so I advised on that assumption.
That's why they say that thing about `ass` `u` `me` I guess.

**Comment by stuartlynne** [comment]
enter-chroot -b sleep infinity works!

Thanks!

On Wed, Mar 25, 2015 at 7:16 PM, David Schneider <notifications@github.com>
wrote:

> @stuartlynne <https://github.com/stuartlynne> for your type of use-case,
> assuming you set up rc.local inside the chroot to launch your servers, sudo
> enter-chroot -b sleep infinity should launch and keep the servers
> running, after which you can safely close the window.
>
> startcli is for starting an interactive session in a new VT environment.
>
> @DennisLfromGA <https://github.com/DennisLfromGA> he's doing
> non-graphical stuff, so xiwi/startunity/croutoncycle/etc doesn't make a lot
> of sense here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1493#issuecomment-86295638>.
>



-- 
__________O___________
_______-\<,____________
_____(_)/_(_)___________
_________________________
Stuart_Lynne____<stuart.lynne@gmail.com>____604-518-1749(m)__604-461-7532(h)

**Comment by Venryx** [comment]
> Also, forget about "clicking on a menu icon" - #847

But this does in fact work!

You just have to modify the Secure Shell app source code, install your custom version over the original (using extensions page "Load unpacked extension"), then launch the "Crosh Window" app/icon to have your custom shell code run. Then when you press the "Crosh Window" icon, it will auto-run your custom shell code. (you can also add buttons or whatever else to the Secure Shell UI, if you want)

More info here: https://github.com/dnschneid/crouton/issues/369#issuecomment-349793600
