### ISSUE TITLE
switching between xfce chroot back to chromeOS creates intermediate developer console, sudo startxfce & doesn't switch to the chroot

### ISSUE THREAD

**Issue by gryftir** [dnschneid/crouton#1494]
These bugs both occurred in the beta channel as well as dev.  Tried moving to dev channel to see if there was a fix but no luck. new asus chromebook

So I can use sudo startxfce4 and that works fine.  So does switching back to Chromeos with ctrl alt f1/back button but switching back to xfce with ctrl alt f2/forward button gets me to a developer console, and I can only go back to chromeOS.  from chromeos ctrl-shift-alt f2 does gets me into the xfce, but I'd like to be able to toggle back with just ctrl-alt-f2.

crouton: version 1-20150226183401~master:24fa73b3
release: trusty
architecture: amd64
xmethod: xorg
targets: extension,keyboard,xfce
host: version 6797.0.0 (Official Build) dev-channel quawks

I also have been getting these errors in the chromeOS shell which may be related.

polkit-gnome-authentication-agent-1:17164): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:17164): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
^[[25;2~Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
(polkit-gnome-authentication-agent-1:17164): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

**Comment by DennisLfromGA** [comment]
@gryftir,

With the 'xorg' xmethod, the newer preferred way to switch between Chrome OS and your chroot(s) is to use:
 `Ctrl+Alt+Shift+f1/Back` and `Ctrl+Alt+Shift+f2/Forward`. 

This will get you to any of your running chroots and also back to Chrome OS.

The older way using `Ctrl+Alt+f1/Back` and `Ctrl+Alt+f2/Forward` still works.

Pressing `Ctrl+Alt+f2/Forward` drops you into the Developer Console, this is *not* a bug, it's intended. 

So, when using the older way of switching -
To get back to Chrome OS from any running chroot, press:
 `Ctrl+Alt+f2/Forward` then `Ctrl+Alt+f1/Back`

To get to your first running chroot from Chrome OS, press:
 `Ctrl+Alt+f2/Forward` then `Ctrl+Alt+f3/Reload`

To get to your second running chroot from Chrome OS, press:
 `Ctrl+Alt+f2/Forward` then `Ctrl+Alt+f4/Fullscreen`

Anytime you press ``Ctrl+Alt+f2/Forward`, it will drop you in the Developer Console.
