### ISSUE TITLE
Cannot open display

### ISSUE THREAD

**Issue by leto** [dnschneid/crouton#1495]
Firstly, I have been using crouton for a few months now and it is great software. Currently using 
it on a HP Chromebook 11:

```
crouton: version 1-20150206191439~master:3401dc49
release: trusty
architecture: armhf
targets: xfce,cli-extra,chrome-dev
host: version 6457.107.0 (Official Build) stable-channel daisy_spring 
```

Things have been working fine, then all of a sudden I am having serious X problems:

```
$ evince pres.pdf 
No protocol specified

** (evince:11688): WARNING **: Could not open X display
No protocol specified
```

At first this showed up as Vim spamming my display with "No protocol specified", so I uninstalled gvim (since I don't use the GUI). But the problem seems pervasive now.

Thanks for any help you can provide!

Rebooting did not change anything.

**Comment by drinkcat** [comment]
> `$ evince pres.pdf`

Where are you running this command? In crosh? The display environment will only be set properly in a xfce terminal (i.e. after you run `startxfce4`).

**Comment by leto** [comment]
No, this is all in the Ubuntu Trusty chroot. Everything has been working fine and I think I installed some packages recently via apt-get that made X windows :hankey: the bed

**Comment by drinkcat** [comment]
Sorry for the delay, have you tried updating your chroot?

**Comment by hoosierEE** [comment]
Quick question: How does one open a PDF from crosh (crouton installed with target: `cli-extra`)?  Ideally I could just pipe the output to Chrome, it would open a tab, and display the pdf.
