### ISSUE TITLE
Clipboard integration broken on ARM chromebook with xfce4 / extension target (xephyr)

### ISSUE THREAD

**Issue by DirtyHairy** [dnschneid/crouton#1498]
Hi there!

I don't know exactly when it happened, but clipboard sync is currently broken for me in my xfce4 chroot using the extension target. It works if I switch to xiwi, but I prefer the old-fashioned x11 mode :) The extension is installed (version 2.3.0), and croutonclip is running.

**Comment by keyneom** [comment]
I have the same issue and the same setup.

**Comment by drinkcat** [comment]
Can either of you provide the output of croutonversion?

**Comment by DirtyHairy** [comment]
Here you go ;)

crouton: version 1-20150304145447~master:550afdb3
release: trusty
architecture: armhf
xmethod: xephyr
targets: x11,xiwi,xfce,extension,cli-extra,audio,keyboard
host: version 6680.64.0 (Official Build) stable-channel daisy

**Comment by DirtyHairy** [comment]
On a side note, in case this helps anyone in the same issue, I have hacked up [this](https://github.com/DirtyHairy/aperture) as a poor man's solution for sharing text between Chrome and the chroot.

**Comment by tedm** [comment]
the clipboard works fine for me, with xmethod = xiwi

my explicit targets were only xiwi and xfce. I think that by specifying a bunch of things that automatically get brought in (check /.crouton-targets) is messing things up, for example, not doubled up x11 targets, etc.

**Comment by DirtyHairy** [comment]
@tedm: I don't think so, I added xiwi only after the clipboard stopped working, to check whether it works with xiwi --- there was only the x11 target before. As a sidenote, xiwi indeed works, but I prefer plain x11, so I switched back.

**Comment by tedm** [comment]
@DirtyHairy Right, are you on an ARM? there is no xorg, so xephyr is used. If xephyr xmethod, and croutonclip with extension are supposed to work, then I guess it is a bug, but I don't think xephyr support is long term at this point.

**Comment by dnschneid** [comment]
Should be fixed in the latest crouton.
