### ISSUE TITLE
cannot get ext. usb stick with ubuntu 14.04 LTS/unity on it to boot anymore

### ISSUE THREAD

**Issue by faddah** [dnschneid/crouton#1499]
hello,

i used crouton to put ubuntu linux 14.04 LTS with Unity on it and boot it on my chromebook. it had been working fine. only now, after a restart, i am getting this whenever i try and mount and go into my chroot (called 'trusty') —

```bash

$ sudo /media/removable/USB\ Drive/bin/startunity 
Entering /media/removable/USB Drive/chroots/trusty...


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sat Mar 7 07:02:28 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=afa08c2c-dfe6-1143-a2b0-36d61788c864/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 2506752 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2506752 alg=sha1 root_hexdigest=946ad2b10242b2d5d1d4832519a283e718557320 salt=4f5a557de57b1bff68e71288963ec10a3adb8869f98170f2d98d3d32d9da5d58" noinitrd vt.global_cursor_default=0 kern_guid=afa08c2c-dfe6-1143-a2b0-36d61788c864 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Fri Mar 13 13:10:54 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Not unmounting /media/removable/USB Drive/chroots/trusty as another instance is using it.

```

this happens now each and every time i want to get back into my crouton ubuntu linux on the external thumb drive, including if i remove the thumb drive, restart the chromebook, and re-insert the thumb drive and attempt to start unity again from the command line. i have repeatedly tried —

1. umounting the USB thumb drive ( ```$ sudo umount /dev/sdb1 ``` ) (the chroot on the USB thumb drive is usually at /dev/sdb1 )
2. ran ``` $ sudo fsck.ext4 -f /dev/sdb1 ``` - that always completes ok, no errors.
3. remounting the USB thumb drive with ``` $ sudo mount /dev/sdb1 /media/removable/USB\ Drive/ ```.
4. attempting to enter the chroot again with ```$ sudo /media/removable/USB\ Drive/bin/startunity ```

i have cycled through the above steps several times, and also shut the chromebook down, restarted and tried all this again. i keep getting the same thing over and over, that something is missing (```/dev/tty0```) and it cannot mount and there is another instance of the chroot "trusty" running, somewhere. 

any help with this, please?

best,

—  faddah 
     portland, oregon, u.s.a.

**Comment by divx118** [comment]
Try updating your chroot, see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting .

**Comment by faddah** [comment]
hi @divx118,

thank you for replying.

i tried the suggested steps at that page and had problems.

first, i don't have a ```/usr/local/chroots``` directory on my main Chromebook drive. i believe this is because i have linux installed, as i say above, not on the Chromebook drive it self, but to a usb stick/thumb drive. so my chroots are in ```/media/removable/USB\ Drive/chroots```.

so i pointed the ```-p``` option of ```PREFIX``` to ```/media/removable/USB\ Drive/chroots```, so my command to update looked like this —

```bash

$ sudo ~/Downloads/crouton -p /media/removable/USB\ Drive/chroots/ -n trusty -u

```

when i do that, i get —

```bash

sudo: /home/chronos/user/Downloads/crouton: command not found

```

??? <= this is rather disconcerting, as i just downloaded the latest crouton to my Downloads directory and made sure it was in there, but for some reason, using sudo, it doesn't see it.

any other suggestions, please?

i appreciate any help offered.

best

—  faddah
     portland, oregon, u.s.a.

**Comment by Watney** [comment]
@faddah try `` sudo sh ~/Downloads/crouton -p /media/removable/USB\ Drive/chroots/ -n trusty -u``

**Comment by smibarber** [comment]
Are you signed in [with multiple profiles at once](https://support.google.com/chromebook/answer/6088201?hl=en&source=genius-rts)? The first user signed in "claims" `/home/chronos/` - you can try downloading it onto that profile's Downloads folder.

**Comment by faddah** [comment]
hi @Watney, @smibarber & @divx118 —

@Watney's command line suggestion is what did it for me, though i needed to make an adjustment, it should actually be:

```sudo sh ~/Downloads/crouton -p /media/removable/USB\ Drive -n trusty -u```

it does not need ```.../chroots/``` to show where the chroot directory is, because it adds that on to the script itself, it just needs the path to the directory one level above that.

@smibarber — i am the only one on my Chromebook, no other profiles.

thanks for the help, all. it's o.k. to close this one out, i got my ubuntu linux install on my USB stick recovered and working again. thank you very much!

best,

—  faddah
     portland, oregon, u.s.a.
