### ISSUE TITLE
Unable to switch between chroot and ChromeOS on new Intel i3 Dell Chromebook 11

### ISSUE THREAD

**Issue by donkeyshark** [dnschneid/crouton#1501]
I have the new Dell Chromebook 11 with the Intel i3 processor in it. I have loaded Ubuntu via Crouton and am having issues switching between Ubuntu to ChromeOS. First off, I should start by stating that I've tried the solution for #834 which appears to be a similar issue. However, it does not work for me. I was able to successfully load the Intel drivers using the following, but they do not resolve my issue. 

sudo apt-get install --no-install-recommends xserver-xorg-lts-saucy libgl1-mesa-glx-lts-saucy
sudo apt-get install xserver-xorg-input-synaptics-lts-saucy

Previously, when I loaded my chroot installation of Ubuntu, I was stuck in there and had to either log out or shutdown to return to ChromeOS. Now, after running the code for updating the drivers per the code in #834  I am now able to exit Ubuntu, but then I get stuck in ChromeOS and can't get back to Ubuntu using the combo key shortcut (which I remapped as follows per another thread I found).

sudo sh -c "echo \"(xbindkey '(control Escape) \\\"croutoncycle next\\\")\" >> /etc/crouton/xbindkeysrc.scm"

I am able to exit Ubuntu, but then the terminal window in ChromeOS reads:
(II) AIGLX: Suspending AIGLX clients for VT switch

It appears to be waiting for more input... it's just sitting there and I have to ctrl+c to get out which closes my Ubuntu session. If anyone knows what I'm doing wrong or has a fix for this issue, I'd greatly appreciate the help. I'm a noob to Ubuntu and Chromebooks, so I apologize for any egregious oversights on my part.

Thanks in advance!

**Comment by drinkcat** [comment]
Can you provide the output of `croutonversion`? Thanks.

**Comment by donkeyshark** [comment]
I apologize for the lack of knowledge necessary here, like I said, I'm pretty new to linux and am guessing I need to enter some commands and a path with this, but I'm just not sure what those are. I tried the following with their respective results:

chronos@localhost / $ croutonversion
bash: croutonversion: command not found
chronos@localhost / $ sh ~/Downloads/croutonversion
sh: Can't open /home/chronos/user/Downloads/croutonversion
chronos@localhost / $ sudo ~/Downloads/croutonversion
sudo: /home/chronos/user/Downloads/croutonversion: command not found
chronos@localhost / $ ~/Downloads/crouton --version
bash: /home/chronos/user/Downloads/crouton: Permission denied
chronos@localhost / $ sudo ~/Downloads/crouton --version
sudo: /home/chronos/user/Downloads/crouton: command not found
chronos@localhost / $ ~/Downloads/croutonversion
bash: /home/chronos/user/Downloads/croutonversion: No such file or directory

**Comment by DennisLfromGA** [comment]
In a Chrome OS shell, enter 'sudo edit-chroot -al'
That will list the 'croutonversion' of all of your installed chroots.

**Comment by donkeyshark** [comment]
Thank you, this is what I get...

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150304145447~master:550afdb3
release: precise
architecture: amd64
xmethod: xorg
targets: extension,unity
host: version 6680.64.0 (Official Build) stable-channel wolf 
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by DennisLfromGA** [comment]
@donkeyshark - Maybe this comment will help you with your switching issue - https://github.com/dnschneid/crouton/issues/1494#issuecomment-78782600

**Comment by donkeyshark** [comment]
Thanks Dennis, I believe that fixes it for me! It's strange though. For some reason, I have to press Ctrl+Shift+Alt+Fwd(F2) going both directions (to and from ChromeOS/Linux). But it's working now! Thanks.

I wish I could get this remapping of keys to work though :) That's a rather inconvenient way to switch between the two... I'm hoping to remap it to Ctrl+Esc...

**Comment by DennisLfromGA** [comment]
Wish I had experience with key mapping but I don't, unfortunately.
If you haven't checked it out yet, there's a wiki page devoted to the keyboard that discusses key bindings and such here - https://github.com/dnschneid/crouton/wiki/Keyboard
