### ISSUE TITLE
Input/Output error when starting unity?

### ISSUE THREAD

**Issue by CyndaQuillian** [dnschneid/crouton#1502]
After the recent update to chromeos, I proceeded to update the chroot by running the command:

sudo sh ~/Downloads/crouton -n trusty -u

Afterwards, when I tried to enter the chroot, my Acer C720p just rebooted itself. After some searching, I found this thread and followed the instructions:
https://github.com/dnschneid/crouton/issues/1474

When I ran startunity again, this pops up:

Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/local/bin/enter-chroot: 490: cannot create /run/crouton/mnt/stateful_partition/crouton/chroots/trusty/etc/timezone: Input/output error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

Can anyone help? I couldn't find this anywhere. Thanks :D

**Comment by dnschneid** [comment]
Could you please update with the latest version of crouton and try again?

**Comment by CyndaQuillian** [comment]
No luck.

I decided to make a backup and try a fresh install of Ubuntu. While it seems to work perfectly fine, I  am unable to retrieve any of my old files. Luckily, I didn't have anything of importance stored there.
