### ISSUE TITLE
Errors when booting into XFCE

### ISSUE THREAD

**Issue by Haxzen** [dnschneid/crouton#1503]
Below is the log I am getting in terminal in chromiumos:

Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Mar 15 02:49:18 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
xf86: found device 0
No Chromium OS X server is available.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No GPG agent found
xfce4-session: No SSH authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:15442): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:15442): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

** (wrapper-1.0:15450): WARNING **: Binding 'XF86AudioLowerVolume' failed!

** (wrapper-1.0:15450): WARNING **: Binding 'XF86AudioRaiseVolume' failed!

** (wrapper-1.0:15450): WARNING **: Binding 'XF86AudioMute' failed!
(II) AIGLX: Suspending AIGLX clients for VT switch

Any help to fix these would be greatly appreciated I am a noob to linux so please keep it simple, and if you require any more info to help me out let me know. Thanks

**Comment by Haxzen** [comment]
Also this (polkit-gnome-authentication-agent-1:22945): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:22945): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

**Comment by drinkcat** [comment]
Can you provide the output of `sudo enter-chroot croutonversion`?

Have you tried updating your chroot?

**Comment by DavidMcLaughlin29** [comment]
I have this same problem.I tried updating and deleting and reinstalling. The release is trusty. It is encrypted. 2016 Acer CB3-431.

**Comment by DennisLfromGA** [comment]
@DavidMcLaughlin29,

This issue was closed nearly two years ago.
Please open a [new issue](https://github.com/dnschneid/crouton/issues/new) and give us all the details that you can.

*Hope this helps,*
-**DennisL**
