### ISSUE TITLE
armv7l architecture issue

### ISSUE THREAD

**Issue by SuvroB** [dnschneid/crouton#1504]
Hi,

I am using HP Chromebook 14 and have turned by chromebook to the developer mode using crouton, installing Ubuntu xfce4. The chip architecture of my chromebook is armv7l and it's not allowing me to install a host of open source softwares like R-studio, Anaconda Python and other tools like Virtual Box etc. It's incompatible with both 32 and 64 bits architecture.  How do I fix this issue ?

Thanks
Suvro

**Comment by DennisLfromGA** [comment]
@SuvroB,

Your HP Chromebook 14 has an Intel Haswell Celeron 64 bit processor not an ARM, but that's good.
Check out some of the specs and other info. here - [HP Chromebook 14](http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/hp-chromebook-14)

**Comment by divx118** [comment]
To be sure what architecture your have, maybe you mixed up some names. Post your `uname -a` If it is really arm then nothing you can do about it, except finding alternatives for the programs you want for arm. I know for virtualbox there will be no alternative on arm.

**Comment by tedm** [comment]
@DennisLfromGA I think there's also an HP Chromebook 14" with Nvidia K1 which started shipping in Q4 of last year. Would be interesting to see what croutonversion or edit-chroot show the platform as for those.

**Comment by DennisLfromGA** [comment]
@tedm,

I believe that's the [HP Chromebook 11](http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/hp-chromebook-11) you're thinking of.  
Also, the [Nvidia K1](http://prodct.info/chromebooks/#f&tegra&ram&us)'s are of the Acer variety.

**Comment by tedm** [comment]
@DennisLfromGA Here's an HP 14" K1: http://www.amazon.com/HP-Chromebook-14-Version-White/dp/B00N3ODBBA

**Comment by DennisLfromGA** [comment]
@SuvroB, 
Sorry for the misinformation, I can't keep up with these things.
The '[Developer Information for Chrome OS Devices](http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices)' can't keep up with'em either so I don't feel so bad. ;)

**Comment by tedm** [comment]
@DennisLfromGA No problem, I can't either. I want a new Chromebook, and all I know is that it must not have a fan ;)

**Comment by smibarber** [comment]
Updated that page with `nyan_blaze`, the Tegra K1-based HP Chromebook 14.

@SuvroB, you might be able to find ARM builds for R studio and other developer-oriented tools, but Virtualbox is a definite no-go since it's dependent on kernel modules that will only build and run on x86 or x86_64 processors. If you _really_ need to run some x86 stuff then slower qemu emulation might be an option.

**Comment by DennisLfromGA** [comment]
Thanx Stephen :) Didn't know you could do that.

**Comment by divx118** [comment]
Sorry for being off topic here, but keeping the same model names with other hardware inside is very confusing IMO. Same goes also for the Acer C720 I wish they update the names so you know what it is and which CPU it has...

BTW there is even wine on arm http://wiki.winehq.org/ARM . It will not be comparable with wine on a x86 machine, but was surprised it even exists.

**Comment by SuvroB** [comment]
HI Dennis, I can confirm it's the Nvidia processor with armv7l architecture. 
As you also confirmed that it wouldn't support a host of softwares, what if I install Debian instead of Ubuntu xfce4, will that support the armv7l arvchitecture? Can this be done using crouton ?
In future will there be a fix for this issue ?

@Stephen : I could install R on Ubuntu xfce4 but as soon as I try to install R-studio it throws the error of incompatibility with Arm architecture. Are you able to locate R-studio which runs on the Arm architecture?

Thanks
Suvro

**Comment by DennisLfromGA** [comment]
@SuvroB,

I'm sorry but I have no knowledge or experience with ARM Chromebooks.
There are lots of people on this site that do though so hopefully they'll chime in ;)

**Comment by SuvroB** [comment]
OK no problem. Thanks.
