### ISSUE TITLE
Unable to boot kali Toshiba Chromebook 2

### ISSUE THREAD

**Issue by nixg360** [dnschneid/crouton#1505]
Hello,

First I'd like to say that I read through just about every thread regarding the "no screens found" error and applied (or tried to apply) every fix that was mentioned, but to no avail. I just bought a new Toshiba Chromebook 2 today and am trying to install kali using crouton, but I keep getting the no screens found error message. I made sure I have the latest crouton installer, and have tried all the troubleshooting steps. I seriously have no other ideas of what to do. I've tried editing the xorg.conf file and running `X -configure`, neither of which worked because it says there is already an X server running. 
Here is the information required for the ticket:

The output of `croutonversion`: 
chronos@localhost / $ sudo enter-chroot -n kali croutonversion
Entering /usr/local/chroots/kali...
crout: version 1-20150304145447~master:550afdb3
release: kali
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6680.64.0 (OfficlBuild) stable-channel swanky 
Unmounting /usr/local/chroots/kali...

The command I run to install is: `sudo sh -e ~/Downloads/crouton -r kali -t xfce`
The command I run to start kali is: `sudo enter-chroot startxfce4`

The output of running the start command: 

chronos@localhost / $ sudo enter-chroot startxfce4
Entering /usr/local/chroots/kali...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.10.18 #1 SMP Sat Mar 7 08:57:35 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashtree=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=89f6e232389b7e19c3d020d05c81fbfef1b567a0 salt=90cc7538bb3f6f4df10159911fac834b58da92f2ccb2995eabed9c4bce6db0f8" noinitrd vt.global_cursor_default=0 kern_guid=53f1dd78-d512-d54e-ab32-e6551aaac164 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 09 February 2015  09:46:52AM
xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau <jcristau@debian.org>) 
Current version of pixman: 0.26.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Mon Mar 16 23:52:32 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/var/log/Xorg.1.log" for additional information.

Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /usr/local/chroots/kali...

Please let me know if there is any other information I can provide to help get this solved. I know crouton is an awesome project, and that's why I really want to get this to work.

Thanks in advance.

**Comment by Scott-Jones** [comment]
I'm having the same issue on the same hardware. 

I noticed that if you start the chroot from the dev console (ctrl-tab-forward), it switches back to the chrome window manager then X in the chroot crashes. 

Kali does actually boot however, and you can add packages using apt. You just can't start X

**Comment by nixg360** [comment]
I was actually able to use Kali by running it with xiwi. However, it's far from smooth. The chrome shell throws errors the whole time while running Kali/xiwi, especially after switching back and forth between operating systems. Also, several features do not seem to work in Kali (yes, I know tools have to be installed manually). I was having difficulty with iptables, specifically. Any thoughts? I'm seriously considering returning my Toshiba for a non-bay trail Chromebook just so I can boot to Kali for full functionality.

**Comment by nixg360** [comment]
It's a shame too, because the Toshiba Chromebook 2 is one of the nicest deals out there right now. But I definitely need full (within the limits of storage space) Kali functionality.

**Comment by Scott-Jones** [comment]
Sorry, I don't have any idea. I also tried booting a live x64 image from a high speed SD card without any luck. 

Interestingly enough I just finished boxing mine up to return tomorrow, lol.

**Comment by drinkcat** [comment]
`/var/log/Xorg.1.log`, inside the chroot, might provide some insight in the problem, if someone wants to upload it to a [gist](http://gist.github.com). Can you also confirm if you are running freon or not (`ls /dev/tty0`)?

**Comment by SeinGlobal** [comment]
I am having the same issue, thought its with an hp chrombook 14, I was about to start a new issue, but figured I could piggyback.

this is output for crouton version http://pastebin.com/kRcQ4RTK

this is output for my xorg log http://pastebin.com/6A65vu1n

**Comment by platonisation** [comment]
Exactly the same problem as SeinGlobal, on the hp 14 chromebook.

**Comment by rpweisman** [comment]
I'm having the same issue on the Acer C720. The default crouton (ubuntu/xfce) works with no issue. I also tried the Kali install with GNOME and KDE, but to no avail. 

Here are the results of my log: https://gist.github.com/rpweisman/9c5361b787c303878b68

Unfortunately I can't seem to find the xorg.conf file to attempt to edit it. From the research I've done, that's what is likely causing the issue: http://www.x.org/wiki/FAQErrorMessages/#index8h2

I should also note that I am able to boot Kali off a flashdrive, so in theory it should work over this medium.

**Comment by nixg360** [comment]
Unfortunately I already returned my chromebook. Like rpweisman said, the default crouton worked. Glad to see I wasn't the only one with this issue. It'd be great if crouton could become a legitimate option for using kali for pentesting, etc.

**Comment by dnschneid** [comment]
Kali is based on wheezy, which has a very old Intel driver.  Can you run `sudo enter-chroot dpkg --get-selections | grep video` and post the output here?

**Comment by SeinGlobal** [comment]
http://pastebin.com/0M9CCp1q This is the requested output, I would not that I got it to work with xiwi with the crouton extension, though I would much prefer the traditional crouton experience.

**Comment by dnschneid** [comment]
@SeinGlobal could you try running `sudo enter-chroot -u root apt-get remove xserver-xorg-video-intel` then trying again to launch xfce4 or whatever?

**Comment by SeinGlobal** [comment]
http://pastebin.com/VFG7csKJ is my results, as far as i can tell nothing changed.

**Comment by divx118** [comment]
@dnschneid fbdev doesn't take over, because we force the intel driver. Remember https://github.com/dnschneid/crouton/blob/master/chroot-etc/xorg-intel-sna.conf ;)

**Comment by divx118** [comment]
A little update. Here is the xorg log when using fbdev http://pastebin.com/G1zUSi0f which btw also fails. It doesn't switch vt. I did some googling, however the xorg server and indeed intel driver are quite old. AFAIK there is also not an easy way to update them.

**Comment by divx118** [comment]
Another update, I just remembered we did in the past a little hack to solve the issue of switching vt with the fbdev driver see https://github.com/dnschneid/crouton/issues/1164 This however will not work now with freon I guess. Also https://github.com/dnschneid/crouton/blob/master/targets/xorg#L114 needs to check if intel is supported on the release. Like mentioned before kali(wheezy) drivers are too old for this. Also see https://github.com/dnschneid/crouton/wiki/3D-Hardware-acceleration

**Comment by dnschneid** [comment]
@divx118 right...ok, so it seems to me like we need two things:

1. I need to finish and merge the freonarm branch, which brings in the modeswitching driver instead of fbdev when freon is present.
2. It sounds like we need to not install the intel driver and the conf file if your chip has fbc AND you're on wheezy or kali.  Does this sound right?

**Comment by divx118** [comment]
1. I tried the modesetting driver in the past, but it wouldn't work for me. Let me try that again and give some relevant debug info. BTW on my trusty chroot (where fbdev also doesn't work) modesetting worked.
2. That is correct.

**Comment by dnschneid** [comment]
Awesome.  Try out the freonarm branch if you get the chance (and let me know if there are issues).  No guarantees it's in a working state though (installing a chroot to test the latest commit at the moment, but I have to go...)

**Comment by divx118** [comment]
I did create a new chroot kali with the freonarm branch. There is no forcing of the intel driver, so that is good. However when trying to use modesetting with `sudo apt-get install xserver-xorg-video-modesetting` and then creating a conf file forcing modesetting gives me following xorg log http://pastebin.com/Je8VbAPG  
The same I tried with my trusty chroot and there it works. xorg log http://pastebin.com/h1feZ5iP  
Anyone any ideas on this X-server on kali crash?

**Comment by dnschneid** [comment]
It looks like kali/wheezy's modesetting driver are really old and may not support rootless operation.  You might be able to come up with some addition to croutonfreon.so that avoids the bad calls; try running  `strace -f xinit` and see which sequence of calls are failing.

On newer distros the modesetting driver gets automatically selected and applied.

**Comment by divx118** [comment]
Here is the strace from xinit in kali. http://www.timara.nl/crouton/strace_xinit.txt Going to take a look if I can find the bad calls and see if I can do something about it. I am not experienced in this, so if someone is more familiar with it...

**Comment by dnschneid** [comment]
It looks like the Xorg server is missing [this patch](http://cgit.freedesktop.org/~ajax/xserver/commit/?id=d01921ec18c21f21d377b60626cc2d3418b84a7c).

I'd try modifying src/freon.c to override ioperm.  First try having it fail (return -1) with ERRNO=ENODEV, and if that doesn't fix it, see what breaks if you just return success :\

**Comment by divx118** [comment]
Tested some things on the freonarm branch: I needed to set the modesetting driver in a xorg.conf, else it wouldn't get selected. Also tested the fbdev driver one more time which doesn't fail, but you can't get to the screen. It only switches away the keyboard and mouse. You can however get control again by using the hotkeys to switch back to chromeos.  
Strace results:  
fbdev: [strace_kali_fbdev.txt](http://www.timara.nl/crouton/strace_kali_fbdev.txt) Only thing I did here was return 0 on ioctl call FBIOPUTCMAP this doesn't make a difference, the call also produced an error on working fbdev drivers setup. Just to explain the many ioctl GRAB lines I put it beside the EVIOCGRAB in freon.c which also return 0.
ioperm returns -1 with errno = ENODEV: [strace_kali_ioperm_ENODEV.txt](http://www.timara.nl/crouton/strace_kali_ioperm_ENODEV.txt) 
ioperm and iopl returns 0: [strace_kali_ioperm_iopl_true.txt](http://www.timara.nl/crouton/strace_kali_ioperm_iopl_true.txt) 

So still no luck yet. Going to take another look at the missing xorg patch to see if I can find something else ...

BTW freonarm branch seems to work good. xiwi was installed as default on kali intel and fdev driver removed. Also on an update my manual installed fbdev driver was removed.

**Comment by dnschneid** [comment]
fbdev won't work on Freon because there's no framebuffer.  straces with modesetting are more interesting.

**Comment by dnschneid** [comment]
@divx118 if you have any breakthroughs we can re-open this and look at getting xorg support on freon+wheezy.  Otherwise, it's xiwi for that combo.

**Comment by nixg360** [comment]
@dnschneid I've been monitoring this issue since I opened it and noticed it was closed. I'm not as technically literate with crouton as you guys, so I was just wondering if Kali will actually work with full (or most) functionality on the Toshiba now? If so, what kind of setup/execution is required? Thanks for all your work on this.

**Comment by divx118** [comment]
@dnschneid No breakthroughs yet. I play with it another time during upcoming weekend, but I don't expect it to be easy to fix with LD_PRELOAD at least not for me.
@nixg360 You can update your kali chroot with `-t xiwi` this will then run kali in a chromeos window which should work with no problems. It will be a bit slower then the fbdev driver. For running graphic stuff I would use a trusty ubuntu chroot.

**Comment by rubsalma** [comment]
como puedo instalar kali linux con kde en mi thosiba chromebook 1 usando crouton??? 
Me dice error al iniciar . Puede que sea un error de grafica o prcesador no compatibles?????
