### ISSUE TITLE
user accounts, locale etc locked and uneditable in multiple new chroots

### ISSUE THREAD

**Issue by fraserYT** [dnschneid/crouton#1506]
I've been running Ubuntu through Crouton on my Acer C720 with no issues for about 6 months, until a Chrome update a few weeks ago meant it was crashing every time I tried to enter Chroot. 

I decided to take the opportunity to do a full factory reset and start fresh, but every time I set up a new Chroot now, user account settings, locale settings and several other crucial core settings are locked and greyed out, so I'm unable to edit or unlock. I've created and deleted five chroots in the last week and they've all had this same issue. Is there anything obvious I might be doing wrong, or is this an issue since the last Chrome update?

**Comment by Watney** [comment]
Is this the same as #1497?

**Comment by fraserYT** [comment]
Sounds the same. I'd searched but hadn't found that prior to posting. I'll close this. Thanks
