### ISSUE TITLE
Disabling web security in Chromebooks

### ISSUE THREAD

**Issue by gulfpearl** [dnschneid/crouton#1508]
Hello, just wondering how you can pass the --disable-web-security argument to the browser on a chromebook.

**Comment by drinkcat** [comment]
Not technically a crouton question...

However I'm pretty sure changing browser flags will need at the very least that you remount your root partition r/w, or maybe that you build a custom Chromium OS image.

A better alternative may be to run another instance of Chrome/Chromium in your crouton chroot, then you can easily use whatever flags you want.
