### ISSUE TITLE
The crouton integration extension is occasionally failing.

### ISSUE THREAD

**Issue by dragonloverlord** [dnschneid/crouton#1510]
The crouton integration extension seems to occasionally fail with this in its log:

    19:22:22	Uncaught JS error: Uncaught TypeError: Cannot set property 'onclick' of null
    15:24:20	Extension started (2.3.0)

There is also this present in background.js:

    WebSocket connection to 'ws://localhost:30001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
    background.js:655 19:22:02: Connection closed
    background.js:309 websocketConnect: null
    background.js:655 19:22:07: Opening a web socket
    background.js:314 WebSocket connection to 'ws://localhost:30001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
    background.js:655 19:22:07: Connection closed
    background.js:309 websocketConnect: null
    background.js:655 19:22:12: Opening a web socket
    background.js:314 WebSocket connection to 'ws://localhost:30001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
    background.js:655 19:22:12: Connection closed
    background.js:309 websocketConnect: null
    background.js:655 19:22:17: Opening a web socket
    background.js:314 WebSocket connection to 'ws://localhost:30001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
    background.js:655 19:22:17: Connection closed
    background.js:309 websocketConnect: null
    background.js:655 19:22:22: Opening a web socket
    background.js:655 19:22:22: Uncaught JS error: Uncaught TypeError: Cannot set property 'onclick' of null
    (2)background.js:152 Uncaught TypeError: Cannot set property 'onclick' of null

I do not think this is natural and I can prove that a lxde install will not launch with this error until the extension is reset(disabled then re-enabled).

This is the output from five consecutive attempts to run lxde it's all identical to this:

    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Error: not connected.
    Cannot connect to extension, retrying...
    Timeout waiting for extension to connect.
    Error: not connected.
    Cannot connect to extension, retrying...
    Unable to start display, make sure the crouton extension is installed
    and enabled, and up to date. (download from http://goo.gl/OVQOEt)
    Running exit commands...
    /usr/bin/xinit: connection to X server lost
    
    waiting for X server to shut down Hangup
    Hangup
    (EE) Server terminated successfully (0). Closing log file.
    
    Unmounting /media/removable/chroots/trusty...

The extension is updated and so is crouton so outdated scripts/extensions are not to blame.

**Comment by dnschneid** [comment]
Extension updated.  Please re-open if you hit this again.

**Comment by Puyodead1** [comment]
I'm experiencing this issue. i closed my chromebook and the extension crashed and says it may be corrupted
croutonwebsocket error: Error: not connected.
