### ISSUE TITLE
since restoring ubuntu trusty unity chroot, cannot do installs.

### ISSUE THREAD

**Issue by faddah** [dnschneid/crouton#1512]
hello,

this somewhat related to my previous issue i had on here, #1499. 

that issue was fixed by running the reinstall of the chroot on my ailing usb stick install of Ubuntu Linux 14.04 LTS. i can now launch back into that chroot ok.

however, since doing that update to fix it, i cannot install anything or remove anything with ```apt-get``` from the command line and the Ubuntu Software center will not launch and gets errors each and everytime.

also, my ```/usr/bin/classicmenu-indicator``` will no longer launch at start-up, nor will it launch when i invoke it from the command line. i get lines of errors whenever i attempt that.

also, as stated previously, when i try and ```sudo apt-get install classicmenu-indicator``` or ```sudo apt-get install gnome-session-flashback``` or ```sudo apt-get install python-pip```, or try a ```sudo apt-get remove...``` on any of those first, to uninstall then reinstall, i get multiple errors. here's an example of errors i get on one of the installs (all the errors on each of these that keeps them from installing look about the same) —

```bash

$ sudo apt-get install python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-colorama python-distlib python-html5lib python-setuptools
Suggested packages:
  python-genshi
Recommended packages:
  python-dev-all
The following NEW packages will be installed:
  python-colorama python-distlib python-html5lib python-pip python-setuptools
0 upgraded, 5 newly installed, 0 to remove and 9 not upgraded.
8 not fully installed or removed.
Need to get 542 kB of archives.
After this operation, 2513 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe python-colorama all 0.2.5-0.1ubuntu1 [18.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/universe python-distlib all 0.1.8-1 [113 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main python-html5lib all 0.999-2 [83.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main python-setuptools all 3.3-1ubuntu1 [230 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty/universe python-pip all 1.5.4-1 [97.7 kB]
Fetched 542 kB in 1s (491 kB/s)     
Selecting previously unselected package python-colorama.
(Reading database ... 256904 files and directories currently installed.)
Preparing to unpack .../python-colorama_0.2.5-0.1ubuntu1_all.deb ...
Unpacking python-colorama (0.2.5-0.1ubuntu1) ...
Selecting previously unselected package python-distlib.
Preparing to unpack .../python-distlib_0.1.8-1_all.deb ...
Unpacking python-distlib (0.1.8-1) ...
Selecting previously unselected package python-html5lib.
Preparing to unpack .../python-html5lib_0.999-2_all.deb ...
Unpacking python-html5lib (0.999-2) ...
Selecting previously unselected package python-setuptools.
Preparing to unpack .../python-setuptools_3.3-1ubuntu1_all.deb ...
Unpacking python-setuptools (3.3-1ubuntu1) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../python-pip_1.5.4-1_all.deb ...
Unpacking python-pip (1.5.4-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up alacarte (3.10.0-1ubuntu2) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package alacarte (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up classicmenu-indicator (0.09-1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package classicmenu-indicator (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up gconf2 (3.2.6-0ubuntu2) ...
Traceback (most recent call last):
  File "/usr/sbin/gconf-schemas", line 121, in <module>
    trim(os.path.join(defaults_dest,"%gconf-tree.xml"), get_valid_languages())
  File "/usr/sbin/gconf-schemas", line 18, in get_valid_languages
    langs.add(l.split('_')[0])
TypeError: Type str doesn't support the buffer API
dpkg: error processing package gconf2 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of gnome-applets-data:
 gnome-applets-data depends on gconf2 (>= 2.28.1-2); however:
  Package gconf2 is not configured yet.

dpkg: error processing package gnome-applets-data (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gnome-applets:
 gnome-applets depends on gconf2 (>= 2.28.1-2); however:
  Package gconf2 is not configured yet.
 gnome-applets depends on gnome-applets-data (>= 3.5); however:
  Package gnome-applets-data is not configured yet.
 gnome-applets depends on gnome-applets-data (<< 3.6); however:
  Package gnome-applets-data is not configured yet.

dpkg: error processing package gnome-applets (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgnome-media-profiles-3.0-0:
 libgnome-media-profiles-3.0-0 depends on gconf2 (>= 2.28.1-2); however:
  Package gconf2 is not configured yet.

dpkg: error processing paNo apport report written because MaxReports is reached already
                                                                                       No apport report written because MaxReports is reached already
                                        No apport report written because MaxReports is reached already
                                                                                                      No apport report written because MaxReports is reached already
                                                       No apport report written because MaxReports is reached already
        ckage libgnome-media-profiles-3.0-0 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gstreamer0.10-gconf:amd64:
 gstreamer0.10-gconf:amd64 depends on gconf2 (>= 2.28.1-2); however:
  Package gconf2 is not configured yet.

dpkg: error processing package gstreamer0.10-gconf:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gnome-media:
 gnome-media depends on libgnome-media-profiles-3.0-0 (>= 2.91.2); however:
  Package libgnome-media-profiles-3.0-0 is not configured yet.
 gnome-media depends on gconf2 (>= 2.28.1-2); however:
  Package gconf2 is not configured yet.
 gnome-media depends on gstreamer0.10-gconf; however:
  Package gstreamer0.10-gconf:amd64 is not configured yet.

dpkg: error processing package gnome-media (--configure):
 dependency problems - leaving unconfigured
Setting up python-colorama (0.2.5-0.1ubuntu1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-colorama (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up python-distlib (0.1.8-1) ...
No apport report written because MaxReports is reached already
                                                              Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-distlib (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up python-html5lib (0.999-2) ...
No apport report written because MaxReports is reached already
                                                              Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-html5lib (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up python-setuptools (3.3-1ubuntu1) ...
No apport report written because MaxReports is reached already
                                                              Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-setuptools (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of python-pip:
 python-pip depends on python-colorama; however:
  Package python-colorama is not configured yet.
 python-pip depends on python-distlib; however:
  Package python-distlib is not configured yet.
 python-pip depends on python-html5lib; however:
  Package python-html5lib is not configured yet.
 python-pip depends on python-setuptools (>= 0.6c1); however:
  Package python-setuptools is not configured yet.

dpkg: error processing package python-pip (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              No apport report written because MaxReports is reached already
               Errors were encountered while processing:
 alacarte
 classicmenu-indicator
 gconf2
 gnome-applets-data
 gnome-applets
 libgnome-media-profiles-3.0-0
 gstreamer0.10-gconf:amd64
 gnome-media
 python-colorama
 python-distlib
 python-html5lib
 python-setuptools
 python-pip
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

so can anyone suggest what needs to be done here? am i just out of luck and need an entire new re-install of my whole config. of the Ubuntu install on the USB stick for crouton? any diagnostics or repair or other install that can be run to fix this, please? please advise.

thank you in advance.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by DennisLfromGA** [comment]
Have you tried `sudo apt-get -install -f` or `sudo dpkg --configure -a`?

On Wed, Mar 18, 2015 at 4:19 PM, Faddah Wolf <notifications@github.com>
wrote:

> hello,
>
> this somewhat related to my previous issue i had on here, #1499
> <https://github.com/dnschneid/crouton/issues/1499>.
>
> that issue was fixed by running the reinstall of the chroot on my ailing
> usb stick install of Ubuntu Linux 14.04 LTS. i can now launch back into
> that chroot ok.
>
> however, since doing that update to fix it, i cannot install anything or
> remove anything with apt-get from the command line and the Ubuntu
> Software center will not launch and gets errors each and everytime.
>
> also, my /usr/bin/classicmenu-indicator will no longer launch at
> start-up, nor will it launch when i invoke it from the command line. i get
> lines of errors whenever i attempt that.
>
> also, as stated previously, when i try and sudo apt-get install
> classicmenu-indicator or sudo apt-get install gnome-session-flashback or sudo
> apt-get install python-pip, or try a sudo apt-get remove... on any of
> those first, to uninstall then reinstall, i get multiple errors. here's an
> example of errors i get on one of the installs (all the errors on each of
> these that keeps them from installing look about the same) —
>
> $ sudo apt-get install python-pip
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following extra packages will be installed:
>   python-colorama python-distlib python-html5lib python-setuptools
> Suggested packages:
>   python-genshi
> Recommended packages:
>   python-dev-all
> The following NEW packages will be installed:
>   python-colorama python-distlib python-html5lib python-pip python-setuptools
> 0 upgraded, 5 newly installed, 0 to remove and 9 not upgraded.
> 8 not fully installed or removed.
> Need to get 542 kB of archives.
> After this operation, 2513 kB of additional disk space will be used.
> Do you want to continue? [Y/n]
> Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe python-colorama all 0.2.5-0.1ubuntu1 [18.3 kB]
> Get:2 http://archive.ubuntu.com/ubuntu/ trusty/universe python-distlib all 0.1.8-1 [113 kB]
> Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main python-html5lib all 0.999-2 [83.2 kB]
> Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main python-setuptools all 3.3-1ubuntu1 [230 kB]
> Get:5 http://archive.ubuntu.com/ubuntu/ trusty/universe python-pip all 1.5.4-1 [97.7 kB]
> Fetched 542 kB in 1s (491 kB/s)
> Selecting previously unselected package python-colorama.
> (Reading database ... 256904 files and directories currently installed.)
> Preparing to unpack .../python-colorama_0.2.5-0.1ubuntu1_all.deb ...
> Unpacking python-colorama (0.2.5-0.1ubuntu1) ...
> Selecting previously unselected package python-distlib.
> Preparing to unpack .../python-distlib_0.1.8-1_all.deb ...
> Unpacking python-distlib (0.1.8-1) ...
> Selecting previously unselected package python-html5lib.
> Preparing to unpack .../python-html5lib_0.999-2_all.deb ...
> Unpacking python-html5lib (0.999-2) ...
> Selecting previously unselected package python-setuptools.
> Preparing to unpack .../python-setuptools_3.3-1ubuntu1_all.deb ...
> Unpacking python-setuptools (3.3-1ubuntu1) ...
> Selecting previously unselected package python-pip.
> Preparing to unpack .../python-pip_1.5.4-1_all.deb ...
> Unpacking python-pip (1.5.4-1) ...
> Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
> Setting up alacarte (3.10.0-1ubuntu2) ...
> Traceback (most recent call last):
>   File "/usr/bin/pycompile", line 35, in <module>
>     from debpython.version import SUPPORTED, debsorted, vrepr, \
>   File "/usr/share/python/debpython/version.py", line 24, in <module>
>     from ConfigParser import SafeConfigParser
> ImportError: No module named 'ConfigParser'
> dpkg: error processing package alacarte (--configure):
>  subprocess installed post-installation script returned error exit status 1
> Setting up classicmenu-indicator (0.09-1) ...
> Traceback (most recent call last):
>   File "/usr/bin/pycompile", line 35, in <module>
>     from debpython.version import SUPPORTED, debsorted, vrepr, \
>   File "/usr/share/python/debpython/version.py", line 24, in <module>
>     from ConfigParser import SafeConfigParser
> ImportError: No module named 'ConfigParser'
> dpkg: error processing package classicmenu-indicator (--configure):
>  subprocess installed post-installation script returned error exit status 1
> Setting up gconf2 (3.2.6-0ubuntu2) ...
> Traceback (most recent call last):
>   File "/usr/sbin/gconf-schemas", line 121, in <module>
>     trim(os.path.join(defaults_dest,"%gconf-tree.xml"), get_valid_languages())
>   File "/usr/sbin/gconf-schemas", line 18, in get_valid_languages
>     langs.add(l.split('_')[0])
> TypeError: Type str doesn't support the buffer APIdpkg: error processing package gconf2 (--configure): subprocess installed post-installation script returned error exit status 1dpkg: dependency problems prevent configuration of gnome-applets-data: gnome-applets-data depends on gconf2 (>= 2.28.1-2); however:  Package gconf2 is not configured yet.dpkg: error processing package gnome-applets-data (--configure): dependency problems - leaving unconfigureddpkg: dependency problems prevent configuration of gnome-applets: gnome-applets depends on gconf2 (>= 2.28.1-2); however:  Package gconf2 is not configured yet. gnome-applets depends on gnome-applets-data (>= 3.5); however:  Package gnome-applets-data is not configured yet. gnome-applets depends on gnome-applets-data (<< 3.6); however:  Package gnome-applets-data is not configured yet.dpkg: error processing package gnome-applets (--configure): dependency problems - leaving unconfigureddpkg: dependency problems prevent configuration of libgnome-media-profiles-3.0-0: libgnome-media-profiles-3.0-0 depends on gconf2 (>= 2.28.1-2); however:  Package gconf2 is not configured yet.dpkg: error processing paNo apport report written because MaxReports is reached already                                                                                       No apport report written because MaxReports is reached already                                        No apport report written because MaxReports is reached already                                                                                                      No apport report written because MaxReports is reached already                                                       No apport report written because MaxReports is reached already        ckage libgnome-media-profiles-3.0-0 (--configure): dependency problems - leaving unconfigureddpkg: dependency problems prevent configuration of gstreamer0.10-gconf:amd64: gstreamer0.10-gconf:amd64 depends on gconf2 (>= 2.28.1-2); however:  Package gconf2 is not configured yet.dpkg: error processing package gstreamer0.10-gconf:amd64 (--configure): dependency problems - leaving unconfigureddpkg: dependency problems prevent configuration of gnome-media: gnome-media depends on libgnome-media-profiles-3.0-0 (>= 2.91.2); however:  Package libgnome-media-profiles-3.0-0 is not configured yet. gnome-media depends on gconf2 (>= 2.28.1-2); however:  Package gconf2 is not configured yet. gnome-media depends on gstreamer0.10-gconf; however:  Package gstreamer0.10-gconf:amd64 is not configured yet.dpkg: error processing package gnome-media (--configure): dependency problems - leaving unconfiguredSetting up python-colorama (0.2.5-0.1ubuntu1) ...Traceback (most recent call last):  File "/usr/bin/pycompile", line 35, in <module>    from debpython.version import SUPPORTED, debsorted, vrepr, \  File "/usr/share/python/debpython/version.py", line 24, in <module>    from ConfigParser import SafeConfigParserImportError: No module named 'ConfigParser'dpkg: error processing package python-colorama (--configure): subprocess installed post-installation script returned error exit status 1Setting up python-distlib (0.1.8-1) ...No apport report written because MaxReports is reached already                                                              Traceback (most recent call last):  File "/usr/bin/pycompile", line 35, in <module>    from debpython.version import SUPPORTED, debsorted, vrepr, \  File "/usr/share/python/debpython/version.py", line 24, in <module>    from ConfigParser import SafeConfigParserImportError: No module named 'ConfigParser'dpkg: error processing package python-distlib (--configure): subprocess installed post-installation script returned error exit status 1Setting up python-html5lib (0.999-2) ...No apport report written because MaxReports is reached already                                                              Traceback (most recent call last):  File "/usr/bin/pycompile", line 35, in <module>    from debpython.version import SUPPORTED, debsorted, vrepr, \  File "/usr/share/python/debpython/version.py", line 24, in <module>    from ConfigParser import SafeConfigParserImportError: No module named 'ConfigParser'dpkg: error processing package python-html5lib (--configure): subprocess installed post-installation script returned error exit status 1Setting up python-setuptools (3.3-1ubuntu1) ...No apport report written because MaxReports is reached already                                                              Traceback (most recent call last):  File "/usr/bin/pycompile", line 35, in <module>    from debpython.version import SUPPORTED, debsorted, vrepr, \  File "/usr/share/python/debpython/version.py", line 24, in <module>    from ConfigParser import SafeConfigParserImportError: No module named 'ConfigParser'dpkg: error processing package python-setuptools (--configure): subprocess installed post-installation script returned error exit status 1dpkg: dependency problems prevent configuration of python-pip: python-pip depends on python-colorama; however:  Package python-colorama is not configured yet. python-pip depends on python-distlib; however:  Package python-distlib is not configured yet. python-pip depends on python-html5lib; however:  Package python-html5lib is not configured yet. python-pip depends on python-setuptools (>= 0.6c1); however:  Package python-setuptools is not configured yet.dpkg: error processing package python-pip (--configure): dependency problems - leaving unconfiguredNo apport report written because MaxReports is reached already                                                              No apport report written because MaxReports is reached already               Errors were encountered while processing: alacarte classicmenu-indicator gconf2 gnome-applets-data gnome-applets libgnome-media-profiles-3.0-0 gstreamer0.10-gconf:amd64 gnome-media python-colorama python-distlib python-html5lib python-setuptools python-pipE: Sub-process /usr/bin/dpkg returned an error code (1)
>
> so can anyone suggest what needs to be done here? am i just out of luck
> and need an entire new re-install of my whole config. of the Ubuntu install
> on the USB stick for crouton? any diagnostics or repair or other install
> that can be run to fix this, please? please advise.
>
> thank you in advance.
>
> best,
>
> — faddah
> portland, oregon, u.s.a.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1512>.
>



-- 
*DennyL@GMail*

**Comment by faddah** [comment]
@DennisLfromGA ,

thank you for responding to me.

tried ```sudo apt-get install -f gnome-session-flashback``` (there is no ```-install``` in apt-get, btw, just ```install```), and with the other installs (```classicmenu-indicator``` & ```python-pip```), get the same errors throughout.

```sudo dpkg --configure -a``` produces same errors as listed in bash readout example in my original post above.

so still at square one on this.

any other help here? is my ubuntu 14.04 just munged and i should just reinstall, or is there a way to fix this. and yes, i have a perfectly good internet connection on the ubuntu install, i am writing from it now in the Opera browser for Ubuntu.

please advise. thank you.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by theblacklion** [comment]
Hi Faddah,

ConfigParser is Python 2.x. In Python 3 it has been renamed to
configparser. So it looks like it is trying to use the wrong version
of Python. Which version pops up if you just execute "python" in a
shell? I'm getting 2.7.6 on elementary OS Freya (which is based on
Ubuntu 14.04).


Cheers,

Oktay.


Faddah Wolf <notifications@github.com> schrieb am Do., 19. März 2015 um
00:39 Uhr:

**Comment by faddah** [comment]
hi @theblacklion ,

_**d'oh!!**_  you are correct. i had switched to using Python 3.4 for something else that required it for install. i switched back (via a symlink) to Python 2.7.6 (i have both installed in the same ```/usr/bin``` directory), and suddenly, everything is working. wow. thanks. o.k. to close this one out.

i do appreciate the help. thank you agian for the timely direct response and help.

best,

—  faddah 
     portland, oregon, u.s.a.

**Comment by theblacklion** [comment]
Nice :). How was the solar eclipse? :)

**Comment by faddah** [comment]
can't tell, been too rainy in portland, @theblacklion. thank you for asking, though.

—  faddah
     portland, oregon, u.s.a.
