### ISSUE TITLE
Control + ["spc","backspace",";"] Behave Oddly

### ISSUE THREAD

**Issue by tychoish** [dnschneid/crouton#1514]
I've got a working crouton (crough, and arch) but I think my problem is general. (Hardware: Pixel 2) 

I've remapped search to control in both chromeos and within the chroot, and I have a host of weird and inconsistent behavior with the control key that feels resolvable. I should backup and say that things _mostly_ work the way we'd expect them to; however: 
- Control+Space always seems to trigger the "previous input" option in chromeos, and is never passed to the chroot. This is maddening. However, it seems to _only_ affect C+SPC when it's the remapped search key.
- C-; doesn't work, again only with the remapped search key. I just get ; characters. 
- C-backspace does backwards delete character when it's the remapped search key, and backward-delete-word when it's an other control key. 

I had some problems with the left-control behavior, so I made everything right controls, but it doesn't help the remapped search key as much as I'd like 

Here's the current set up, which is pretty good, but obviously, it'd be nice to have it work all the way.

```
shift       Shift_L (0x32),  Shift_R (0x3e)
lock      
control     Control_R (0x25),  Control_R (0x69),  Control_R (0x85)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_R (0x86),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

```
clear lock
remove control = Super_L 
remove mod4 = Super_L
remove mod4 = Control_R
keycode 133 = Control_R
keycode 37 = Control_R
add Control = Control_R
add mod4 = Hyper_R
```

**Comment by drinkcat** [comment]
Can you provide the output of croutonversion? I guess this only happens in xiwi, right?

**Comment by tychoish** [comment]
```
crouton: version git
release: arch
architecture: x86_64
xmethod: xiwi
targets: x11
host: version 6680.57.0 (Official Build) stable-channel samus 
```

I believe the answer to the xiwi question is "yes," though I must confess a bit of obliviousness wrt X11 environment. I'm willing to try different ways of running X, as long as I can run my own window manager/etc.

**Comment by rpdillon** [comment]
I'm seeing this as well in xiwi.  I ugraded ChromeOS to beta channel on my C720 and my Emacs bindings for set-mark (C-space) and undo (C-/) stopped being sent to xiwi.  It appears C-space is changing my keybord layout, as @tychoish pointed out, and C-/ is bringing up Chromebook Help.

**Comment by drinkcat** [comment]
That really should not happen if you are in a window (i.e. not in a tab). Fullscreen will help kiwi grab other key presses, but those should be passed to the app even when not in fullscreen.

**Comment by dnschneid** [comment]
It looks like all of the issues are with the remapped search key?  If you disable the remapping inside X11 (keep it enabled in Chromium OS), what does `xev` report when you hit the search key?

**Comment by liuxiawei** [comment]
I have the same problem. My ctrl+space will cause input many space untill I press down any key,or it will keep input space.
