### ISSUE TITLE
storage filled 

### ISSUE THREAD

**Issue by brw31415** [dnschneid/crouton#1515]
I have a toshiba c35 a3120 with v 14.02 chrome, 16gig storage. I installed with crouton the trusty ubuntu version. After using apt-get a few times to get various libraries, including add-apt-repository,and dependencies, the software center , and some other things, eventually the system said the storage was full, and the computer was rebooting itself and other ways of registering complaints after switching back to chrome os. Is there an easy way to keep tract of  storge,how do you purge files to free up storage, etc , and does crouton dynamical allocate space, and if not where is this set?

**Comment by midnightradio** [comment]
In my case, I have 64Gb storage but always check space left because ChromeOS exhaustively consumes the storage with storing offline data and never be considerate about the other side which actually living together with.

Actually, I can sense chromebook's performance degrading due to lack of free space so I can naturally try to free up some spaces and let the two systems live along in peace. I think you will meet the situation more often for the limited storage, and I would recommend you to move your chroot to removable storage such as SD card or USB thumb drive. 

And here's a tip for removing all offline meta data in chromeos at once. Go to chrome://drive-internals and click the button "clear local data". By this, you can remove all offline caches except some files related to google docs.

**Comment by brw31415** [comment]
I'd love to do rhat, but I haven't found a totally coherent description of how to use crouton to install to a usb drive
but this is what I found and tried:

sudo mkdir /media/removable/NAME-OF-SD-CARD-OR-FLASH-DRIVE/chroots
sudo ln -s /media/removable/NAME-OF-SD-CARD-OR-FLASH-DRIVE/chroots/   /usr/local/chroots

at this point, according to this particular article, "now that the directory has been created and linked to the correct location, the Crouton installer will place all your chroots to a USB stick or SD card."

then, according to article,
run:

sudo sh ~/Downloads/crouton -r trusty -t xfce

but doesn't work ,

/usr/local/chroots/trusty is not an ext filesystem. 

also tried this:

sudo sh -e ~/Downloads/crouton -r trusty -t xfce -p /media/removable/your-flashdrive-name/chroots

returns:
/media/removable/USB Drive/chroots/chroots/trusty is not an ext filesystem.



/usr/local/chroots/trusty is not an ext filesystem.

**Comment by DennisLfromGA** [comment]
> I'd love to do rhat, but I haven't found a totally coherent description of how to use crouton to install to a usb drive

Make a backup of your chroot: 
   `sudo edit-chroot -b trusty`
Then restore it to your external media: 
   `sudo sh ~/Downloads/crouton -f ~/Downloads/trusty-2015*.tar.gz -p /path/to/external/media`

**Comment by brw31415** [comment]
Thanks much, but i seem to still have a problem:

sudo sh ~/Downloads/crouton -f ~/Downloads/trusty-2015*.tar.gz -p /media/removable/'USB Drive 1'

/media/removable/USB Drive 1/chroots/trusty is not an ext filesystem

**Comment by DennisLfromGA** [comment]
Sorry, I thought you were just having trouble with the 'restore' part.
I found this method in issue https://github.com/dnschneid/crouton/issues/1103#issuecomment-58766746 
```
sudo umount /dev/sdb2
sudo fdisk /dev/sdb2  [with the -d to delete partition, -n to create partition, and -w & -q to write it and quit]
sudo mkfs.ext4 /dev/sdb2
sudo mkdir /media/removable/linux
sudo mount /dev/sdb2 /media/removable/linux
```
Maybe something like that will work for you - substituting 'ext4' for 'ext2', etc.

**Comment by brw31415** [comment]
I followed your intstructions, and I think it worked (see below) . Now what do I do? Do I wipe the trusty I installed internally? How do I run the linux xfce from the flash drive?

sudo sh ~/Downloads/crouton -f ~/Downloads/trusty-2015*.tar.gz -p /media/removable/'USB Drive'
Downloading latest crouton installer...
######################################################################## 100.0%
Finished restoring /home/chronos/user/Downloads/trusty-20150320-2015.tar.gz to /media/removable/USB Drive/chroots/trusty
Installing startxfce4 into the host...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Done! You can enter the chroot using enter-chroot.

**Comment by DennisLfromGA** [comment]
@brw31415 

To launch it, you can either 'cd' into the external media directory and run it there:
`cd /media/removable/USB Drive; sudo bin/startxfce4 -n trusty`
or use the '-c' option when specifying the command:
`sudo startxfce4 -c /media/removable/USB Drive/chroots -n trusty`

After a reboot, I believe you can just plug it in and it should mount.
Be sure to check /media/removable to see what the folder name is that's mounted.
 
You may/should be able to eject it via the Files app.

**Comment by brw31415** [comment]
Thanks so much for your help, as this great project evolves, hopefully things will become easier for the common user

**Comment by DennisLfromGA** [comment]
No problem, we've all been there...

**Comment by brw31415** [comment]
I guess I have one last question. I keep hearing about (but not convincingly how) that you can boot native linux from a flash drive. Why use this (or Chrubuntu) if thats true. Or is that just a recent development?

**Comment by midnightradio** [comment]
@brw31415 Presumably because they still want to keep ChromeOS and don't want to transform their chromebook into linux netbook I guess.

**Comment by brw31415** [comment]
I guess I spoke too soon. When I reboot, and plug flash drive back in , when I try this:

cd /media/removable/USB Drive; sudo bin/startxfce4 -n trusty

i get permission denied for both super user and not super user.


ditto for
cd /media/removable/USB Drive; sudo bin/startxfce4 -n trusty

however ls -l bin shows them all to be executable:

-rwxr-xr-x 1 root root  7304 Mar 20 20:39 crash_reporter_wrapper
lrwxrwxrwx 1 root root    11 Mar 20 20:39 delete-chroot -> edit-chroot
-rwxr-xr-x 1 root root 29039 Mar 20 20:39 edit-chroot
-rwxr-xr-x 1 root root 31729 Mar 20 20:39 enter-chroot
-rwxr-xr-x 1 root root 18372 Mar 20 20:39 mount-chroot
-rwxr-xr-x 1 root root   536 Mar 20 20:39 startxfce4
-rwxr-xr-x 1 root root 17047 Mar 20 20:39 unmount-chroot

**Comment by DennisLfromGA** [comment]
@brw31415 - See if this issue helps - https://github.com/dnschneid/crouton/issues/928

**Comment by brw31415** [comment]
OK, yea I just needed to umount and mount again, and (knock on wood!) works fine
