### ISSUE TITLE
chrome os (probably) updated, crouton 14.04 gnome, now virtualbox won't start

### ISSUE THREAD

**Issue by wb0gaz** [dnschneid/crouton#1516]
I've been using crouton (for the last few months with Ubuntu 14.04 Gnome) on an Acer C720 for about a year, includng Virtualbox. Somewhere in the last few weeks, Virtualbox no longer starts, instead advising me to run /etc/init.d/vboxdrv setup (I had installed virtualbox a year ago along with my first Crouton install - Ubuntu 12.04 - and it has worked well until this.) This script does not run (ends with an error condition.) I imagine google forced an update of chrome OS (I *really* wish I could control that behavior; updates via a metered tethering account is an expensive process!)

As my C720+Crouton+Ubuntu is a daily-use ("daily driver") laptop, I have little time for tinkering and experimentation, so I'm looking for a time-efficient way to recover virtualbox to operational. I recall when I first installed Virtualbox (a year ago) that I was able to find .deb file(s) that contained pre-built kernel headers and such needed to allow Virtualbox to properly operate, instead of going through the whole rebuild-the-kernel cycle.

It seems that going through kernel rebuild would be unnecessary if someone archived the needed kernel header files (as I found a year ago), as it seems generating the files once and making them available would be straightforward.

Any pointer/advice (short of rebuilding kernel and all that?)

Very tks!

**Comment by DennisLfromGA** [comment]
@wb0gaz - You might want to run this by @divx118 since he most likely created the headers and rc.local file you're speaking of. You can copy-n-paste this issue here - https://github.com/divx118/crouton-packages/issues/new

**Comment by wb0gaz** [comment]
Following a link provided by @divx118 easily fixed the problem - thanks for the pointer!
