### ISSUE TITLE
Jack not working

### ISSUE THREAD

**Issue by ozyrinis** [dnschneid/crouton#1517]
I have as USB audio interface,, namely Focusrite Scarlett Solo, and i use lubuntu on a fresh installation.

i m trying to get JACK to work, because without it Audacity hangs every 4 minutes but when i try to start it this is what i get:

13:27:46.207 Patchbay deactivated.
13:27:46.210 Statistics reset.
13:27:46.216 ALSA connection change.
13:27:46.227 D-BUS: Service is available (org.jackaudio.service aka jackdbus).
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
13:27:46.235 ALSA connection graph change.

And then when i press start i get this
D-BUS: JACK server could be started.

Sorry

and after a while i get this message
Could not connect to JACK server as client.
- Overall operation failed.
- Unable to connect to server.
Please check the messages window for more info.

the messages wiindow at this point says
13:27:46.207 Patchbay deactivated.
13:27:46.210 Statistics reset.
13:27:46.216 ALSA connection change.
13:27:46.227 D-BUS: Service is available (org.jackaudio.service aka jackdbus).
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
13:27:46.235 ALSA connection graph change.
13:31:41.602 D-BUS: JACK server could not be started. Sorry
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Wed Mar 18 13:31:41 2015: Starting jack server...
Wed Mar 18 13:31:41 2015: JACK server starting in realtime mode with priority 10
Wed Mar 18 13:31:41 2015: ERROR: Cannot lock down 82274202 byte memory area (Cannot allocate memory)
Wed Mar 18 13:31:41 2015: Acquired audio card Audio0
Wed Mar 18 13:31:41 2015: creating alsa driver ... hw:0|hw:0|128|3|44100|0|0|nomon|swmeter|-|32bit
Wed Mar 18 13:31:41 2015: ERROR: ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
Wed Mar 18 13:31:41 2015: ERROR: Cannot initialize driver
Wed Mar 18 13:31:41 2015: ERROR: JackServer::Open failed with -1
Wed Mar 18 13:31:41 2015: ERROR: Failed to open server
Wed Mar 18 13:31:43 2015: Saving settings to "/home/woodpecker/.config/jack/conf.xml" ...
13:32:10.259 Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

I couldn't find any solution on the internet
Any suggestions?
thanx!

**Comment by drinkcat** [comment]
Have you looked at #1434? Adding yourself to hwaudio and stoping cras should do the trick.

**Comment by ozyrinis** [comment]
Thanx for the reply :)
that's what i get: 
stop: Unknown job: cras

**Comment by dnschneid** [comment]
You need to do that in a crosh shell, not inside the chroot.

**Comment by firestar115** [comment]
See [Using JACK for SimpleScreenRecorder](https://github.com/dnschneid/crouton/wiki/Using-JACK-for-SimpleScreenRecorder)
