### ISSUE TITLE
download angular-material.js

### ISSUE THREAD

**Issue by zoplex** [dnschneid/crouton#1518]
Is it possible to download angular-material.js like it could be done with angular.js - for cases where browser app is on local network with no internet access?

**Comment by smibarber** [comment]
Certainly, see #262.

**Comment by zoplex** [comment]
Hm - I could not find anything about where to download from in that issue .. 

Could you be more specific - provide a link if you have it?

Much appreciated

**Comment by DennisLfromGA** [comment]
@zoplex - This doesn't pertain to 'crouton' as such (hence the irrelevant link), you might want to try this  - http://goo.gl/gyo85g
