### ISSUE TITLE
How to add a DE after install?

### ISSUE THREAD

**Issue by AsHperson** [dnschneid/crouton#1521]
I installed Ubuntu Trusty with Unity Desktop and now I want to try out Gnome Desktop on here to see how it will do. I know I can install it within Ubuntu but what about the startgnome command, how do I get that? I was thinking there should be an easy way to add a target to the install now such as -t gnomedesktop.

**Comment by DennisLfromGA** [comment]
Just update your chroot adding the desktop at the same time, like this:
`sudo sh ~/Downloads/crouton -n trusty -t [gnome or gnome-desktop] -u`
Once that's installed, you'll have the `startgnome` command available to you.

**Comment by AsHperson** [comment]
Thank you Dennis!

**Comment by DennisLfromGA** [comment]
Your most welcome ;)
