### ISSUE TITLE
My cursor in Ubuntu is glitching out.

### ISSUE THREAD

**Issue by AsHperson** [dnschneid/crouton#1522]
When I move a file or anything that I use my trackpad for(super annoying in Minecraft making it near unusable). For example when I have a file window and I am moving a file over to another window, it skips about 1/3 of the screen over to a random direction(up/down/left/right). This makes it nearly unusable and such. Here is my version info:

CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={F67500C1-C6D8-5287-E4EC-F9BBB4AEE5C5}
CHROMEOS_RELEASE_BOARD=samus-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=0
CHROMEOS_RELEASE_BUILD_NUMBER=6885
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=43
CHROMEOS_RELEASE_DESCRIPTION=6885.0.0 (Official Build) dev-channel samus 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=dev-channel
CHROMEOS_RELEASE_VERSION=6885.0.0
GOOGLE_RELEASE=6885.0.0

**Comment by drinkcat** [comment]
Can you provide the output of `croutonversion` (in the chroot)?

**Comment by AsHperson** [comment]
(trusty)ash@localhost:~$ croutonversion
crouton: version 1-20150317110704~master:be252afb
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome-desktop,gnome,audio,chrome-dev,cli-extra,core,extension,unity-desktop,gtk-extra,keyboard,touch
host: version 6885.0.0 (Official Build) dev-channel samus

**Comment by dennisranalli** [comment]
I am having the same issue.

**Comment by Watney** [comment]
maybe take a look at #1519

**Comment by dennisranalli** [comment]
Thanks.  This fixes the issue of the ghosting cursor when I switch from ChromOS to Ubuntu.  In Ubuntu, the cursor still jumps around erratically.

**Comment by Watney** [comment]
@dennisranalli Do you have the ``touch`` target installed? Looks like ``touch`` installs ``touchégg`` and sets parameters in ``/etc/touchegg.conf`` — [see the script](https://github.com/dnschneid/crouton/blob/fc5da1382e70525c857f68bd92a27013fe09dcd0/targets/touch). 

I don't use the ``touch`` target, and haven't experienced your problems. I wonder if ``touchégg`` is causing the cursor to jump?

**Comment by dennisranalli** [comment]
No -t touch enabled. Thanks

**Comment by dnschneid** [comment]
@dennisranalli could you also post the output of `croutonversion`?

**Comment by dennisranalli** [comment]
Thanks...

crouton: version 1-20150404180843~master:66d0393b
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 6680.78.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Fri Mar 20 15:41:09 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by dennisranalli** [comment]
This solution fixes most of the cursor issues.

https://plus.google.com/+ClayCaldovino/posts/beM8HnKMQ64

**Comment by Watney** [comment]
@dennisranalli links to a Google+ post that uses HughGreenBug's [CrOS trackpad drivers](https://launchpad.net/~hugegreenbug/+archive/ubuntu/cmt2) repackaged for Ubuntu. Have others tried using these drivers on various Chromebooks? I am testing the replacement driver in a trusty chroot, and it appears to be much better. 

If others share this experience, I'm glad to add a Wiki entry explaining how to use the replacement drivers, with @dnschneid's permission.

**Comment by matneyx** [comment]
I am trying this on an Acer C910 -- my mouse seems to be a lot less bouncy, especially when I click with one finger while scrolling with the other.

**Comment by bdshaffer73** [comment]
A simple workaround I found for the corrupt mouse after switching back to the chroot is to touch the touchscreen. Granted this requires a touchscreen device and enabled chroot, but it seems resetting the cursor after switching temporarily fixes the problem.

**Comment by bdshaffer73** [comment]
@dennisranalli That fixed mine jumping, thanks! Now on to editing the rest of the settings.
