### ISSUE TITLE
Solutions to the high ppi on the Chromebook Pixel

### ISSUE THREAD

**Issue by AsHperson** [dnschneid/crouton#1523]
I have the chromebook pixel and I think the dpi settings on Ubuntu are way off since the ui is eye-squinting level. Is there any way to fix this? I've already done some research although I can't find anything worthwhile.

**Comment by drinkcat** [comment]
Have you tried some of the solutions indicated here: https://github.com/dnschneid/crouton/wiki/Chromebook-Pixel ?

Also, if you are using xiwi, you could just untick the HiDPI checkbox...

**Comment by AsHperson** [comment]
Help! I used option 1 and now it wont startup.
here's the small log it gave when tring to startup:
X: /tmp/.X11-unix has suspicious ownership (not root:root), aborting.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

**Comment by MAkerboom** [comment]
try removing the tmp file and check the permissions of /etc/X11/xinit/xserverrc, should be root:root 0755 (-rwxr-xr-x)

**Comment by Watney** [comment]
@AsHperson If you're using Xfce, a simple hack, though not very elegant, is to add the built-in script ``setres 1440 960`` as a startup command. See [this blog](http://xubuntugeek.blogspot.com/2011/12/add-application-to-xfcexubuntu-session.html) for a nice guide to add a startup command. 

Of course, use the resolution that you prefer. Option #3 in [the Wiki Pixel entry](https://github.com/dnschneid/crouton/wiki/Chromebook-Pixel) suggests 4 resolutions that play nicely.

**Comment by dnschneid** [comment]
@AsHperson update your chroot to reset the file; the instructions on that page were out-of-date.  I've replaced them with terse, more correct ones, but someone can elaborate on it.
