### ISSUE TITLE
Can more than one chroot be safely mounted at the same time?

### ISSUE THREAD

**Issue by dragonloverlord** [dnschneid/crouton#1526]
What I am wondering is if I mount two chroots at the sametime will anything bad happen? or is mounting two or more chroots at the same time perfectly ok?

I am only asking this as I could not find any definitive answer in the wiki about mounting multiple chroots at the same time so if you could add info on this to the wiki it would be much appreciated.

Finally, thanks for all the wonderful work that you do to make all this stuff work! :smile:

**Comment by drinkcat** [comment]
It's perfectly ok, we do that all the time ,-)
