### ISSUE TITLE
Java Swing Element | Xiwi

### ISSUE THREAD

**Issue by horrigan97** [dnschneid/crouton#1527]
Does anyone have any idea how i might open a swing app window in a xiwi window? Or is this is even possible?

I have tried in a crosh shell
<code>$sudo enter-chroot -b -n [chrootname] xiwi 'java [java swing class]'</code>
and from within chroot terminal (through crosh window) 
<code>$enter-chroot xiwi 'java [java swing class]'</code>  <-- also tried this with sudo
(I was always in the correct directory)

error returned was something about being an unrecognized app, my guess it's just not an app name, ergo xiwi doesn't recognize etc etc.

Is there a possible workaround for this? Or possible that we can add an enhancement to the target? And if somebody on the Crouton group can give me a couple leads I can crash test and trouble shoot and give back what i found, but to do that I'd need a couple leads. Other wise does anyone know if this kindof thing could be done through NaCl? I read some stuff on it but it didn't look like it currently supports java.

Thoughts?
(ps thanks for input and help in advance)

**Comment by DennisLfromGA** [comment]
My thoughts:

Try giving it the full path or write a small script to start it and then use:
`$sudo enter-chroot -b -n [chrootname] xiwi [path/to/script]`

Also, the 'xiwi-app' has trouble with apps that run in the background.

**Comment by dnschneid** [comment]
See #1483
