### ISSUE TITLE
1th one works but failed to switch between chromeos and chroot. Second one: No display (still a black screen) however xfce still works. C710-2490

### ISSUE THREAD

**Issue by emini** [dnschneid/crouton#1531]
chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)acer@localhost:~$ croutonversion
crouton: version 1-20150323010735~master:4348d5f1
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,chrome,xfce,keyboard,touch,extension
host: version 6812.42.0 (Official Build) beta-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Wed Mar 18 14:16:08 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
(trusty)acer@localhost:~$ startxfce4
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Wed Mar 18 14:16:08 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-1 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="2 vboot none ro 1,0 2545920 bootcache PARTUUID=c86c538b-15ec-6b45-9cad-c16b48c6a750/PARTNROFF=1 2545920 3525a3ae8cfdef84575e630756c82520c17f7a71 512 20000 100000, vroot none ro 1,0 2506752 verity payload=254:0 hashtree=254:0 hashstart=2506752 alg=sha1 root_hexdigest=eec6f3ed903a03a4df15aef54a9c08fd7341f5a9 salt=d7baf609f8bfdb71a6b9207037c3273a59b35134557a6192f57e51ff007f43f0" noinitrd vt.global_cursor_default=0 kern_guid=c86c538b-15ec-6b45-9cad-c16b48c6a750 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.4.log", Time: Tue Mar 24 14:06:57 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 1
xf86: found device 1
7 XSELINUXs still allocated at reset
SCREEN: 0 objects of 352 bytes = 0 total bytes 0 private allocs
DEVICE: 0 objects of 104 bytes = 0 total bytes 0 private allocs
CLIENT: 0 objects of 200 bytes = 0 total bytes 0 private allocs
WINDOW: 0 objects of 80 bytes = 0 total bytes 0 private allocs
PIXMAP: 2 objects of 48 bytes = 96 total bytes 0 private allocs
GC: 4 objects of 88 bytes = 352 total bytes 0 private allocs
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
GLYPH: 0 objects of 24 bytes = 0 total bytes 0 private allocs
TOTAL: 7 objects, 456 bytes, 0 allocs
2 PIXMAPs still allocated at reset
PIXMAP: 2 objects of 48 bytes = 96 total bytes 0 private allocs
GC: 4 objects of 88 bytes = 352 total bytes 0 private allocs
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
GLYPH: 0 objects of 24 bytes = 0 total bytes 0 private allocs
TOTAL: 7 objects, 456 bytes, 0 allocs
4 GCs still allocated at reset
GC: 4 objects of 88 bytes = 352 total bytes 0 private allocs
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
GLYPH: 0 objects of 24 bytes = 0 total bytes 0 private allocs
TOTAL: 5 objects, 360 bytes, 0 allocs
1 CURSORs still allocated at reset
CURSOR: 1 objects of 8 bytes = 8 total bytes 0 private allocs
GLYPH: 0 objects of 24 bytes = 0 total bytes 0 private allocs
TOTAL: 1 objects, 8 bytes, 0 allocs
1 CURSOR_BITSs still allocated at reset
GLYPH: 0 objects of 24 bytes = 0 total bytes 0 private allocs
TOTAL: 0 objects, 0 bytes, 0 allocs
xf86: found device 1
Another instance of croutonclip running, waiting...
Another instance of croutontriggerd running, waiting...
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:31965): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:31965): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
Failure: Module initialization failed

(xfce4-panel:31950): Gtk-CRITICAL **: IA__gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(xfce4-panel:31950): Gtk-CRITICAL **: IA__gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(Thunar:31952): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
err:xrandr:xrandr12_get_current_mode Unknown mode, returning default.

(mousepad:629): Gtk-WARNING **: Attempting to read the recently used resources file at `/home/acer/.local/share/recently-used.xbel', but the parser failed: Failed to open file '/home/acer/.local/share/recently-used.xbel': Permission denied.
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
fixme:dwmapi:DwmIsCompositionEnabled 0x6c210b68
fixme:iphlpapi:NotifyAddrChange (Handle 0x184e118, overlapped 0x184e130): stub
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
fixme:dwmapi:DwmIsCompositionEnabled 0x6bccfb14
fixme:iphlpapi:NotifyAddrChange (Handle 0x166e790, overlapped 0x166e79c): stub
wine: configuration in '/home/acer/.wine' has been updated.
fixme:exec:SHELL_execute flags ignored: 0x00000100
(II) AIGLX: Suspending AIGLX clients for VT switch

---

Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)acer@localhost:~$ startxfce4
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Wed Mar 18 14:16:08 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-1 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="2 vboot none ro 1,0 2545920 bootcache PARTUUID=c86c538b-15ec-6b45-9cad-c16b48c6a750/PARTNROFF=1 2545920 3525a3ae8cfdef84575e630756c82520c17f7a71 512 20000 100000, vroot none ro 1,0 2506752 verity payload=254:0 hashtree=254:0 hashstart=2506752 alg=sha1 root_hexdigest=eec6f3ed903a03a4df15aef54a9c08fd7341f5a9 salt=d7baf609f8bfdb71a6b9207037c3273a59b35134557a6192f57e51ff007f43f0" noinitrd vt.global_cursor_default=0 kern_guid=c86c538b-15ec-6b45-9cad-c16b48c6a750 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.5.log", Time: Tue Mar 24 14:18:39 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 1
xf86: found device 1
Another instance of croutonclip running, waiting...
Another instance of croutontriggerd running, waiting...
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
Failure: Module initialization failed

(polkit-gnome-authentication-agent-1:5399): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:5399): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(II) AIGLX: Suspending AIGLX clients for VT switch

**Comment by emini** [comment]
Loading extension GLX
xf86: found device 1
xf86: found device 1
xfce4-session: No gpg or ssh authentication agent found
Error: target STRING not available
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
The program 'wrapper-1.0' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 277 error_code 3 request_code 138 minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
(II) AIGLX: Suspending AIGLX clients for VT switch
xfce4-panel-Message: Plugin systray-6 has been automatically restarted after crash.
Error: target STRING not available

(wrapper-1.0:15159): GLib-CRITICAL **: Source ID 316 was not found when attempting to remove it

**Comment by dnschneid** [comment]
What's the XSELINUX stuff?  Running anything special?
