### ISSUE TITLE
Updated ChromeOS receiving screen not found error when starting chroot

### ISSUE THREAD

**Issue by Tribblized** [dnschneid/crouton#1532]
chronos@localhost /usr/local/chroots $ sudo startkde
Entering /mnt/stateful_partition/crouton/chroots/kali...

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.10.18 #1 SMP Fri Mar 20 17:27:55 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=b7366d1a-8c09-1d4b-a0ba-517722476961/PARTNROFF=1 hashtree=PARTUUID=b7366d1a-8c09-1d4b-a0ba-517722476961/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5a0a8320ceaef1cf2fdbcb5368f94263062aab85 salt=c76c61a1338d5ac17df76df9958b7f1a5c442f002c1ec1fe678116d14d83cc26" noinitrd vt.global_cursor_default=0 kern_guid=b7366d1a-8c09-1d4b-a0ba-517722476961 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 09 February 2015  09:46:52AM
xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau <jcristau@debian.org>) 
Current version of pixman: 0.26.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed Mar 25 08:24:01 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/var/log/Xorg.1.log" for additional information.

Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/kali as another instance is using it.

**Comment by Anxionos** [comment]
See if you can try the command 'sudo unmount-chroot'.  I've had the same issue, I'm just going to see if I can help with this issue as well as possible.

**Comment by DennisLfromGA** [comment]
@Anxionos , If you just want to know what processes are stopping it from unmounting, use the '-p' option.

**Comment by Anxionos** [comment]
@DennisLfromGA Didn't know about that one, thanks.  The person who posted the thread hasn't replied yet, I'm only waiting to see if I can help.  *Thanks for taking the problem from a sorta newbie*

I fixed my own issue, I just don't remember how I did so.  Couple forums and reboots later, I don't remember, but it's fixed [yay!]

**Comment by Anxionos** [comment]
@Tribblized  As @DennisLfromGA  had said, see what processes are stopping the unmount by using the -p option.  Once you've figured out what's stopping it, tell us.  If you've fixed it, it'd be helpful if you posted how you fixed it for future people with issues.

**Comment by dnschneid** [comment]
Same as #1505.  His primary issue is the "no screens found" part...
