### ISSUE TITLE
No apt-get on install

### ISSUE THREAD

**Issue by johndj1** [dnschneid/crouton#1533]
Hi

Apologies, complete newbie, but having installed the latest version of crouton onto my chromebook I cannot get apt-get to work and looking into the usr/bin directory it does not appear to be there.

Probably doing something wrong if you could advise?

Thanks

Dan

**Comment by DennisLfromGA** [comment]
In a chroot shell, use: sudo apt-get ...

-DennyL

**Comment by johndj1** [comment]
When I try that I get 

sudo: apt-get: command not found

**Comment by DennisLfromGA** [comment]
I think I would try updating the chroot to see if that fixes it:
  `sudo sh ~/Downloads/crouton -u [-n chrootname]`

**Comment by johndj1** [comment]
Done and still the same.  

Sorry.

I've installed it a couple of times and each time is the same.  I get the feeling I should give up and just stick with my ChromeOS unless you have any other ideas?  Be a shame to.

**Comment by DennisLfromGA** [comment]
@johndj1 - In a cros shell, enter: `sudo edit-chroot -al` and let us know what it displays.
Just checking to be sure but are you in the chroot shell command line when trying to use `apt-get`?

**Comment by johndj1** [comment]
name: precise
encrypted: no
Entering /usr/local/chroots/precise...
crouton: version 1-20150323010735~master:4348d5f1
release: precise
architecture: amd64
xmethod: xorg
targets: kde
host: version 6812.42.0 (Official Build) beta-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Wed Mar 18 15:37:23 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /usr/local/chroots/precise...

**Comment by DennisLfromGA** [comment]
Everything looks good there, try this: `sudo enter-chroot -x sudo apt-get update`

**Comment by johndj1** [comment]
Ta, did that and it installed some stuff.  But still no apt-get.  command not found.

Sorry, I know this is a pain.

**Comment by DennisLfromGA** [comment]
Can you explain '...did that and it installed some stuff.' a little more?
Did it enter the chroot successfully, and not complain about a 'A chroot setup script still exists inside the chroot.'?

**Comment by johndj1** [comment]
Sorry, of course.  This was the output:
Entering /usr/local/chroots/precise...
Hit http://archive.ubuntu.com precise Release.gpg
Get:1 http://archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:2 http://archive.ubuntu.com precise-security Release.gpg [198 B]
Hit http://archive.ubuntu.com precise Release
Get:3 http://archive.ubuntu.com precise-updates Release [196 kB]
Get:4 http://archive.ubuntu.com precise-security Release [54.3 kB]
Hit http://archive.ubuntu.com precise/main Sources    
Hit http://archive.ubuntu.com precise/restricted Sources
Hit http://archive.ubuntu.com precise/universe Sources
Hit http://archive.ubuntu.com precise/multiverse Sources
Hit http://archive.ubuntu.com precise/main amd64 Packages
Hit http://archive.ubuntu.com precise/restricted amd64 Packages
Hit http://archive.ubuntu.com precise/universe amd64 Packages
Hit http://archive.ubuntu.com precise/multiverse amd64 Packages
Hit http://archive.ubuntu.com precise/main i386 Packages
Hit http://archive.ubuntu.com precise/restricted i386 Packages
Hit http://archive.ubuntu.com precise/universe i386 Packages
Hit http://archive.ubuntu.com precise/multiverse i386 Packages
Hit http://archive.ubuntu.com precise/main TranslationIndex
Hit http://archive.ubuntu.com precise/multiverse TranslationIndex
Hit http://archive.ubuntu.com precise/restricted TranslationIndex
Hit http://archive.ubuntu.com precise/universe TranslationIndex
Get:5 http://archive.ubuntu.com precise-updates/main Sources [487 kB]
Get:6 http://archive.ubuntu.com precise-updates/restricted Sources [7981 B]
Get:7 http://archive.ubuntu.com precise-updates/universe Sources [112 kB]
Get:8 http://archive.ubuntu.com precise-updates/multiverse Sources [9417 B]
Get:9 http://archive.ubuntu.com precise-updates/main amd64 Packages [884 kB]
Get:10 http://archive.ubuntu.com precise-updates/restricted amd64 Packages [13.6 kB]
Get:11 http://archive.ubuntu.com precise-updates/universe amd64 Packages [255 kB]
Get:12 http://archive.ubuntu.com precise-updates/multiverse amd64 Packages [16.4 kB]
Get:13 http://archive.ubuntu.com precise-updates/main i386 Packages [922 kB]   
Get:14 http://archive.ubuntu.com precise-updates/restricted i386 Packages [13.6 kB]
Get:15 http://archive.ubuntu.com precise-updates/universe i386 Packages [264 kB]
Get:16 http://archive.ubuntu.com precise-updates/multiverse i386 Packages [16.6 kB]
Get:17 http://archive.ubuntu.com precise-updates/main TranslationIndex [10.6 kB]
Get:18 http://archive.ubuntu.com precise-updates/multiverse TranslationIndex [7613 B]
Get:19 http://archive.ubuntu.com precise-updates/restricted TranslationIndex [7297 B]  
Get:20 http://archive.ubuntu.com precise-updates/universe TranslationIndex [8333 B]    
Get:21 http://archive.ubuntu.com precise-security/main Sources [125 kB]                
Get:22 http://archive.ubuntu.com precise-security/restricted Sources [3759 B]          
Get:23 http://archive.ubuntu.com precise-security/universe Sources [34.2 kB]  
Get:24 http://archive.ubuntu.com precise-security/multiverse Sources [1815 B]    
Get:25 http://archive.ubuntu.com precise-security/main amd64 Packages [492 kB]
Get:26 http://archive.ubuntu.com precise-security/restricted amd64 Packages [8943 B]
Get:27 http://archive.ubuntu.com precise-security/universe amd64 Packages [108 kB]
Get:28 http://archive.ubuntu.com precise-security/multiverse amd64 Packages [2463 B]
Get:29 http://archive.ubuntu.com precise-security/main i386 Packages [531 kB]   
Get:30 http://archive.ubuntu.com precise-security/restricted i386 Packages [8939 B]
Get:31 http://archive.ubuntu.com precise-security/universe i386 Packages [116 kB]
Get:32 http://archive.ubuntu.com precise-security/multiverse i386 Packages [2652 B]
Get:33 http://archive.ubuntu.com precise-security/main TranslationIndex [208 B]
Get:34 http://archive.ubuntu.com precise-security/multiverse TranslationIndex [199 B]
Get:35 http://archive.ubuntu.com precise-security/restricted TranslationIndex [202 B]
Get:36 http://archive.ubuntu.com precise-security/universe TranslationIndex [205 B]
Hit http://archive.ubuntu.com precise/main Translation-en                         
Hit http://archive.ubuntu.com precise/multiverse Translation-en
Hit http://archive.ubuntu.com precise/restricted Translation-en
Hit http://archive.ubuntu.com precise/universe Translation-en
Get:37 http://archive.ubuntu.com precise-updates/main Translation-en [389 kB]
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en             
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en             
Get:38 http://archive.ubuntu.com precise-updates/universe Translation-en [149 kB]   
Get:39 http://archive.ubuntu.com precise-security/main Translation-en [218 kB]       
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en        
Hit http://archive.ubuntu.com precise-security/restricted Translation-en        
Get:40 http://archive.ubuntu.com precise-security/universe Translation-en [66.6 kB]
Fetched 5545 kB in 7s (699 kB/s)                                                                                                                    
Reading package lists... Done
Unmounting /usr/local/chroots/precise...

**Comment by divx118** [comment]
@johndj1 First enter the chroot. You can do that with `sudo enter-chroot -n precise` Then your apt-get should be available. When you want to start your kde desktop, use `sudo startkde -n precise` You can not use apt-get in the cros shell.

**Comment by DennisLfromGA** [comment]
Thanx @divx118, I though I was going crazy. I *did* ask if he was in a chroot shell ;)

**Comment by johndj1** [comment]
Thanks both. As per my first comment, I am a newbie.  Bet you just didn't realise how much of a newbie I was. 

Sorted now,  ta. 

Dan

**Comment by DennisLfromGA** [comment]
@johndj1 - No problem, I'm an oldie - I think I'd rather be a newbie ;)

**Comment by Anxionos** [comment]
@johndj1 I'm here if you've got any questions, I've got Ubuntu 12.04 (precise) on mine, and I've had some of the problems you're gonna come across I'm sure.. (I'm kinda a newbie too, but forums browsing is my forte). =3

**Comment by Anxionos** [comment]
@johndj1  In response to your almost giving up on linux, don't lose hope! It's way faster, and if you'd like to show off, just run the update command.  People who don't know linux will have their minds blown.  

If you haven't done so already, I suggest installing firefox and maybe some sort of photo editor, or skype.  Thank goodness it was easier to install skype on Ubuntu through crouton than on fedora 21...

**Comment by tedm** [comment]
a "project" I give my college linux students is to go to the local apple store, bring up a terminal, and start typing and running every bash shell command they know. It's pretty much the most exciting field trip/project they've done in their lives.

**Comment by Anxionos** [comment]
@tedm The results should  be fun and exciting [hoping for a crash, did they do so?]

**Comment by divx118** [comment]
@DennisLfromGA Yes I know, but it was the only logical thing left...Hope I saved you some time this way :)

**Comment by tedm** [comment]
@Anxionos no, but some got dates with Geniuses

**Comment by DennisLfromGA** [comment]
@divx118 - You did, plus, your explanation of what to use and when was much better and clearer.
