### ISSUE TITLE
Unable to start Kali Linux: No screens found

### ISSUE THREAD

**Issue by PlasmacometX** [dnschneid/crouton#1534]
I'm only very novice at using command line and linux in general. So in September, I had managed to install Kali Linux on my Acer C720, using xfce. However, in about late November, my chromebook would crash at startup, and this was after a solid 2-1/2 months of full functionality with Kali and Chromeos. So I turned off developer mode to reset everything, and then went back to it in an attempt to reinstall it. However, now when I attempt to start it, I get an error saying "Fatal Error: No Screens Found."
Can anyone guide me through on how to fix this step by step?
Here is what I see:
chronos@localhost / $ sudo enter-chroot startxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Sat Mar 7 06:52:13 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=15ef924a-c1b5-0a4b-925b-2bf87aa27eb4/PARTNROFF=1 hashtree=PARTUUID=15ef924a-c1b5-0a4b-925b-2bf87aa27eb4/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=1a6a71bfdffaa1dc35dd4df3c7a4e296004bfb4b salt=c790964fb35f7cee08a4c63b94893a53ffae700e2dae6558271c8970e22f1af2" noinitrd vt.global_cursor_default=0 kern_guid=15ef924a-c1b5-0a4b-925b-2bf87aa27eb4 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 09 February 2015  09:46:52AM
xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau <jcristau@debian.org>) 
Current version of pixman: 0.26.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed Mar 25 14:25:25 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/var/log/Xorg.1.log" for additional information.

Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali...

**Comment by Anxionos** [comment]
If you were in developer mode, it shouldn't have updated itself .... now this si an interesting problem.  Had you edited anything or made a file [that you remember] that could have done this? These don't just pop up out of nowhere, it must have a cause.

(And I'm determined to help you find it.)

**Comment by PlasmacometX** [comment]
Thank you for your determination ^_^. Now, I haven't done anything other than the usually download crouton, and then install Kali Linux as normal, using XFCE. I believe Kali has installed, but I can't seem to start it, as I get the No Screens found error.

**Comment by dnschneid** [comment]
Please follow [these steps](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting) when reporting issues.
