### ISSUE TITLE
quick way to get into chroot?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1535]
(If there is a forum or better place to post this newbie question let me know.)

I open a new chroot terminal and ssh into a remote every 10 to 15 minutes.  I have to because whenever I close my lid my remote session ends and I can't get back to chroot so the terminal window locks up (this is normal, right?).

To get back in I have to ...

- ctrl-alt-t
- shell
- sudo enter-chroot
- ssh me@remote.com

I think I can change `sudo enter-chroot` into a single key by making my fs read-write but I'm nervous and afraid of bricking my chromebook pixel.

Any ideas on how to make this process easier?  I'm pretty lazy.

**Comment by smibarber** [comment]
Luckily this can be solved without fixing crouton :)

If your ssh session gets wedged/unresponsive, use the following incantation to kill it and be dropped back into your chroot's shell.
```(enter) ~ .```

From there you can run ssh again.

**Comment by DennisLfromGA** [comment]
Would using `screen`, `tmux` or others be useful, I believe they'll leave the ssh session up.

**Comment by tedm** [comment]
If all you want to do is ssh, you can do it from a crosh shell, and use Chrome's power settings for lid:

sudo stop powerm or sudo initctl stop powerm – to disable sleep when lid is closed. 

or to keep the system fully from sleeping or powering down: sudo stop powerd 

or in the chroot, croutonpowerd with options here:

https://github.com/dnschneid/crouton/blob/master/chroot-bin/croutonpowerd

**Comment by mark-hahn** [comment]
Thanks to all.  Lot's of good stuff here.

**Comment by mark-hahn** [comment]
> If all you want to do is ssh, you can do it from a crosh shell,

I can't use a key or scp from the chroot using a crosh shell, can I?

**Comment by tedm** [comment]
I think you can, unless it was removed very recently.

**Comment by tedm** [comment]
@mark-hahn just tried it, works fine from crosh / shell, uses keys in /home/chronos/user/.ssh/known_hosts

**Comment by mark-hahn** [comment]
Thanks. For some reason I assumed I had no write access to anything outside
of the chroot.

**Comment by mark-hahn** [comment]
Is chronos another chroot?  If so why do I need crouton?  (I know I'm
wading into stupid newbie territory.)

**Comment by tedm** [comment]
@mark-hahn chronos is a default user in Chrome OS crosh / shell. If all you want to do is ssh / scp, you don't need crouton.
