### ISSUE TITLE
It's not an issue, but where does KXSrudio fit into crouton ?

### ISSUE THREAD

**Issue by 3rdwiki** [dnschneid/crouton#1536]
I was reading this thread: https://lists.ubuntu.com/archives/ubuntu-studio-users/2015-March/thread.html#10319

And wondered where KXStudio fitted into crouton ?

I'know I'm gonna be slated, bt your gonna have to cut me some slack for this.

Of course I googled it and found it was a huge source of plug-ins
http://kxstudio.sourceforge.net/

Any chance this could be accesssed in future ?

**Comment by dnschneid** [comment]
See the [wiki](https://github.com/dnschneid/crouton/wiki/Full-Blown-Audio-Video-Workstation-using-KDE-chroot-and-KXStudio).
