### ISSUE TITLE
Late-failing target results in bad sources.list

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1537]
If you try to install xorg on a Samsung ARM chromebook (for instance), the installer will fail fairly late in the game, and leave behind a bad /etc/apt/sources.list that doesn't get fixed.  Usually this means the install fails strangely later if you update with the correct targets.

**Comment by tedm** [comment]
so should -u updates start by creating a new /etc/apt/sources.list after maybe backing up the original? Is this pie?

**Comment by dnschneid** [comment]
Nope, I think the check to see if /etc/apt/sources.list should consider a one-line sources.list to be invalid.  I don't think this is necessarily pie though, because the conditions for when to update the sources.list are pretty specific...

**Comment by tedm** [comment]
OK, thanks.
