### ISSUE TITLE
Add a -f command for xiwi to handle forking processes

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1538]
`xiwi -f` should make xiwi show a dialog when all windows are gone asking to quit instead of actually quitting, and the dialog should auto-disappear when an additional window is created.

This means forking applications will never have the X11 server ripped out from under them, but well-behaved applications will close xiwi promptly.

**Comment by dnschneid** [comment]
Just pushed xiwif which does a naive implementation (you have to ctrl-c xiwi to quit if you specify -f).  This isn't really ideal, and won't work well if you launch it in the background.

Another possibility is having xiwi automatically quit if you close the xiwi window when there are no windows open inside.

A third option is having xiwi create a window that asks if you want to quit, whenever there are no other windows.

I think the second option is best (quit when the window is closed if there are no windows open)...thoughts?

**Comment by dnschneid** [comment]
OK, just pushed an implementation of the second option.  This behaves really well, as far as I can tell.

**Comment by DennisLfromGA** [comment]
Question: Do we specify this new option as: `sudo enter-chroot xiwi -f [gui-app]` ?
I ask because I thought that `enter-chroot` might eat the '-f' opton - maybe not.
( I suppose I should try it first before I start asking unnecessary questions :)

**Comment by dnschneid** [comment]
enter-chroot stops parsing parameters once it hits a non-option parameter.  So `sudo enter-chroot xiwi -f ...` will work fine.

**Comment by DennisLfromGA** [comment]
K, thankx again.

On Tue, Mar 31, 2015 at 2:07 PM, David Schneider <notifications@github.com>
wrote:

> enter-chroot stops parsing parameters once it hits a non-option parameter.
> So sudo enter-chroot xiwi -f ... will work fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1538#issuecomment-88192409>.
>



-- 
*DennyL@GMail*
