### ISSUE TITLE
xinit: run croutonversion?

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1539]
Seeing as 97.6% of bugs on the tracker go something like this:

User:
> uh oh xorg crashes!
>
> `startxfce4/xinit output log`

Dev:
> croutonversion plox

User:
> here you go
> `croutonversion croutonversion croutonversion`

Dev:
> magic fix-everything answer omg genius

...perhaps it would be prudent to have xinit call croutonversion, either right at the start (easy), or if xorg exits non-zero (harder), so that we can get to the omg genius step faster.

Thoughts?

**Comment by DennisLfromGA** [comment]
My 2 cents - right at the start would be easy-peasy, what's another 10 lines in the grand scheme of things...

**Comment by drinkcat** [comment]
Well we could easily print on error only in `croutonxinitrc-wrapper`, but I guess that does not necessarily cover all cases...

So, yeah, just print it all the time...

**Comment by dnschneid** [comment]
pieee

**Comment by DennisLfromGA** [comment]
Just a guess: https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:patch-1

**Comment by dnschneid** [comment]
Yep!

**Comment by DennisLfromGA** [comment]
Here 'tis - PR https://github.com/dnschneid/crouton/pull/1542
