### ISSUE TITLE
permission denied loading extension GLX

### ISSUE THREAD

**Issue by willow9886** [dnschneid/crouton#1543]
I'm having some trouble getting ubuntu working properly on my Acer Chromebook 11 CB3-111.

When I run the command `sudo startunity`

It takes me to my ubuntu desktop. However, when I switch back to ChromeOS, I'm seeing the following error in my crosh:

Entering /mnt/stateful_partition/crouton/chroots/precise...

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Fri Mar 20 17:27:55 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4a211cb5-0d20-1e46-aca5-11a9bf67f6a3/PARTNROFF=1 hashtree=PARTUUID=4a211cb5-0d20-1e46-aca5-11a9bf67f6a3/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5a0a8320ceaef1cf2fdbcb5368f94263062aab85 salt=c76c61a1338d5ac17df76df9958b7f1a5c442f002c1ec1fe678116d14d83cc26" noinitrd vt.global_cursor_default=0 kern_guid=4a211cb5-0d20-1e46-aca5-11a9bf67f6a3 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Thu Mar 26 23:01:01 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
(II) AIGLX: Suspending AIGLX clients for VT switch

Any guidance is appreciated!!

**Comment by dnschneid** [comment]
You can disregard that; it's harmless.
