### ISSUE TITLE
Having trouble starting  xfce

### ISSUE THREAD

**Issue by Icesquid28** [dnschneid/crouton#1547]
When I try to start my chroot I get this and it doesn't start up:

Entering /mnt/stateful_partition/crouton/chroots/precise...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] Y
Preparing chroot environment...
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://ppa.launchpad.net trusty InRelease                                  
Ign http://archive.ubuntu.com trusty InRelease                                 
Ign http://ppa.launchpad.net trusty InRelease  
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://ppa.launchpad.net trusty InRelease  
Ign http://archive.ubuntu.com trusty-security InRelease
Ign http://ppa.launchpad.net trusty Release.gpg
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://ppa.launchpad.net trusty Release.gpg
Hit http://archive.ubuntu.com trusty-updates Release.gpg
Hit http://ppa.launchpad.net trusty Release.gpg
Hit http://archive.ubuntu.com trusty-security Release.gpg
Ign http://ppa.launchpad.net trusty Release
Hit http://archive.ubuntu.com trusty Release
Hit http://ppa.launchpad.net trusty Release                           
Hit http://archive.ubuntu.com trusty-updates Release                  
Hit http://ppa.launchpad.net trusty Release                           
Hit http://archive.ubuntu.com trusty-security Release                 
Hit http://archive.ubuntu.com trusty/main Sources                     
Hit http://archive.ubuntu.com trusty/restricted Sources          
Hit http://archive.ubuntu.com trusty/universe Sources             
Hit http://ppa.launchpad.net trusty/main amd64 Packages           
Hit http://archive.ubuntu.com trusty/multiverse Sources           
Hit http://ppa.launchpad.net trusty/main i386 Packages            
Hit http://archive.ubuntu.com trusty/main amd64 Packages          
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages    
Hit http://ppa.launchpad.net trusty/main amd64 Packages           
Hit http://archive.ubuntu.com trusty/universe amd64 Packages      
Hit http://ppa.launchpad.net trusty/main i386 Packages            
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages    
Hit http://ppa.launchpad.net trusty/main Translation-en           
Hit http://archive.ubuntu.com trusty/main i386 Packages            
Hit http://archive.ubuntu.com trusty/restricted i386 Packages      
Hit http://archive.ubuntu.com trusty/universe i386 Packages        
Hit http://archive.ubuntu.com trusty/multiverse i386 Packages      
Hit http://archive.ubuntu.com trusty/main Translation-en           
Hit http://archive.ubuntu.com trusty/multiverse Translation-en     
Hit http://archive.ubuntu.com trusty/restricted Translation-en     
Hit http://archive.ubuntu.com trusty/universe Translation-en            
Hit http://archive.ubuntu.com trusty-updates/main Sources          
Hit http://archive.ubuntu.com trusty-updates/restricted Sources    
Hit http://archive.ubuntu.com trusty-updates/universe Sources      
Hit http://archive.ubuntu.com trusty-updates/multiverse Sources    
Err http://ppa.launchpad.net trusty/main amd64 Packages            
  404  Not Found
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages   
Err http://ppa.launchpad.net trusty/main i386 Packages             
  404  Not Found
Ign http://ppa.launchpad.net trusty/main Translation-en            
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Ign http://ppa.launchpad.net trusty/main Translation-en            
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages           
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages         
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages                
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages          
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages            
Hit http://archive.ubuntu.com trusty-updates/multiverse i386 Packages          
Hit http://archive.ubuntu.com trusty-updates/main Translation-en               
Hit http://archive.ubuntu.com trusty-updates/multiverse Translation-en         
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en         
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en           
Hit http://archive.ubuntu.com trusty-security/main Sources                     
Hit http://archive.ubuntu.com trusty-security/restricted Sources               
Hit http://archive.ubuntu.com trusty-security/universe Sources                 
Hit http://archive.ubuntu.com trusty-security/multiverse Sources               
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages              
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages        
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages          
Hit http://archive.ubuntu.com trusty-security/multiverse amd64 Packages        
Hit http://archive.ubuntu.com trusty-security/main i386 Packages               
Hit http://archive.ubuntu.com trusty-security/restricted i386 Packages         
Hit http://archive.ubuntu.com trusty-security/universe i386 Packages           
Hit http://archive.ubuntu.com trusty-security/multiverse i386 Packages         
Hit http://archive.ubuntu.com trusty-security/main Translation-en              
Hit http://archive.ubuntu.com trusty-security/multiverse Translation-en        
Hit http://archive.ubuntu.com trusty-security/restricted Translation-en        
Hit http://archive.ubuntu.com trusty-security/universe Translation-en          
W: Failed to fetch http://ppa.launchpad.net/glasen/intel-driver/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/glasen/intel-driver/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Mar 24 20:51:28 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=8ade2547-341e-f34a-a935-a9ba3d1c5d6a/PARTNROFF=1 hashtree=PARTUUID=8ade2547-341e-f34a-a935-a9ba3d1c5d6a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=03747f1e18ba73c9fa7b01d261e5b051ac8e22e8 salt=49d8904998e71fbcac7fc20203fba95a89b2dec2874e5aafd8a545bdc5efcc84" noinitrd vt.global_cursor_default=0 kern_guid=8ade2547-341e-f34a-a935-a9ba3d1c5d6a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Mar 27 21:27:10 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x48) [0x7f50f68b0848]
(EE) 1: /usr/bin/Xorg (0x7f50f6707000+0x1ad539) [0x7f50f68b4539]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f50f5804000+0x10340) [0x7f50f5814340]
(EE) 3: /usr/bin/Xorg (0x7f50f6707000+0xb57a6) [0x7f50f67bc7a6]
(EE) 4: /usr/bin/Xorg (xf86BusProbe+0x9) [0x7f50f6790099]
(EE) 5: /usr/bin/Xorg (InitOutput+0x74d) [0x7f50f679e6fd]
(EE) 6: /usr/bin/Xorg (0x7f50f6707000+0x59bab) [0x7f50f6760bab]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7f50f4244ec5]
(EE) 8: /usr/bin/Xorg (0x7f50f6707000+0x451ee) [0x7f50f674c1ee]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
