### ISSUE TITLE
Deadkeys in xiwi : work only when used twice

### ISSUE THREAD

**Issue by SnarkBoojum** [dnschneid/crouton#1548]
I gave xiwi a try : if I don't do anything, I get a qwerty keyboard ; and if I do "setxkbmap -layout fr" (like I do with the usual X11 crouton), then I do get an azerty keyboard, but the dead keys don't work (like they do with the usual X11 crouton). The accentuated letters which are directly accessible with the keyboard do work.

**Comment by SnarkBoojum** [comment]
I made more tests (was forced to : since I updated to the devel channel, xiwi was the only way to get my chroot up), and found out that when switching to the fr layout, deadkeys actually do work!

You just have to type the dead key twice before the letter you want to accentuate!

**Comment by dnschneid** [comment]
Can you please post the output of `croutonversion`?

**Comment by SnarkBoojum** [comment]
Uh... the result is pretty interesting! The version is unknown, the release is unknown and the architecture is unknown... For the host, things look better: version 68865.0.0 (Official Build) dev-channel daisy-freon.

I can add it's an ARM samsung chromebook.

**Comment by drinkcat** [comment]
Ok, so that's freon. I was under the impression that this problem was fixed with freon (see https://code.google.com/p/chromium/issues/detail?id=425156#c16 , #1428 for the same issue on X11).

I'll have a look.

**Comment by drinkcat** [comment]
Confirmed on peppy/6885.0.0. Filed a crbug here: https://code.google.com/p/chromium/issues/detail?id=472071 (feel free to star the issue).

**Comment by tedm** [comment]
croutonversion is working on the stable channel with Samsung ARM, but the -u toggles between two different versions or hashes of crouton (by design?), and croutonversion appears to just read /etc/crouton/xmethod and will display the contents there, even if the user is using xiwi with `-X xiwi` and vice versa.

(precise)ted@localhost:~$ croutonversion -u
crouton: version 1-20150325193646~master:f7b2a0af
Retrieving latest version of crouton
latest: version 1-20150330191406~master:6b1fd1ef
(precise)ted@localhost:~$ croutonversion -u
crouton: version 1-20150325193646~master:f7b2a0af
Retrieving latest version of crouton
latest: version 1-20150330191406~master:6b1fd1ef
(precise)ted@localhost:~$ croutonversion
crouton: version 1-20150325193646~master:f7b2a0af
release: precise
architecture: armhf
xmethod: xephyr
targets: xfce,xiwi,xephyr
host: version 6680.78.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Mar 20 15:38:03 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
(precise)ted@localhost:~$

**Comment by dnschneid** [comment]
Not really relevant to this issue, but `croutonversion -u` doesn't actually update the chroot; it just reports what the latest upstream version is.  So the first version printed is your current version, and the second is what's available on the internets.

**Comment by DennisLfromGA** [comment]
Also not that pertinent but I have an alias defined to update 'crouton':

  'alias cru='sudo enter-chroot croutonversion -du'

And similar ones for 'croutoncycle':

  alias 0='sudo enter-chroot croutoncycle cros'
  alias 1='sudo enter-chroot croutoncycle 1'
  alias 2='sudo enter-chroot croutoncycle 2'
  alias 3='sudo enter-chroot croutoncycle 3'
  alias cros='sudo enter-chroot croutoncycle cros'
  alias list='sudo enter-chroot croutoncycle list 2>&1 | grep -iv -e mount
-e entering'
  alias next='sudo enter-chroot croutoncycle next'
  alias prev='sudo enter-chroot croutoncycle prev'

I find'em pretty handy.

On Tue, Mar 31, 2015 at 2:17 PM, David Schneider <notifications@github.com>
wrote:

> Not really relevant to this issue, but croutonversion -u doesn't actually
> update the chroot; it just reports what the latest upstream version is. So
> the first version printed is your current version, and the second is what's
> available on the internets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1548#issuecomment-88195753>.
>



-- 
*DennyL@GMail*

**Comment by tedm** [comment]
@dnschneid OK, then the wording should be something like: "Retrieving version info. of latest Crouton, but not downloading it"

Unless -d is used to download it, then it could use the current text string.

@DennisLfromGA I'm a pretty fast typer, so croutonversion -d is quite fast. I did find your chroots.sh script a lot faster than croutonversion -al though, but I think it needs to be updated to show encryption and platform status.

I'm not sure what the 0 - 3 and cros, list, next and prev do. I only have 2 chroots, a precise and a kali, and can get into them pretty fast by typing. I do have a script that brings up both in xiwi windows, but it doesnt use croutoncycle, just:

startxfce4 -n precise -b -X xiwi
startxfce4 -n kali -b -X xiwi

or something close to the above.

**Comment by dnschneid** [comment]
Still not relevant to the bug.

**Comment by tedm** [comment]
@dnschneid agree, and when `-d` is used, the text is fine:

chronos@localhost / $ croutonversion -d -u
crouton: version 1-20140301024303~master:06549cb2
Retreiving latest version of crouton
latest: version 
Saving latest version to /home/chronos/user/Downloads/crouton
chronos@localhost / $ which croutonversion
/usr/local/bin/croutonversion
chronos@localhost / $ 

if anyone else is confused by just `-u` I can enter a new issue, and possibly even fix it as it appears to be a `pie` issue, but if no one else is confused by it, there is no need to fix it.

**Comment by tedm** [comment]
@SnarkBoojum Are you still having the keyboard issues in your original post? If not, feel free to close this open issue.

**Comment by SnarkBoojum** [comment]
I downgraded to the beta channel, as I couldn't stand having a broken french keyboard in addition to the broken wifi -- chromeOS has been a pain since months now...

So I can't tell you if the issue is still there unfortunately :-(

**Comment by ByrialJensen** [comment]
I have the same issue on my Asus C300 chromebook with Danish keyboard layout.

(wily)byrial@localhost:~$ croutonversion 
crouton: version 1-20151104200003~master:2a1fc9da
release: wily
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,xfce-desktop
host: version 7520.63.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Fri Dec 11 19:13:33 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

When I select Danish keyboard in ChromeOS there are two dead keys (with key codes 21 and 35). If I then go to a xiwi window these two keys have to be used twice before anything happens. But that is independent on the selected keyboard layout in the xiwi window. If I use "setxkbmap -layout dk" they work as dead keys, but have to be used twice to work. If I switch to "setxkbmap -layout us" they are not dead keys (they are = and ]), but they still have to be used twice to work.

However if I select US keyboard in ChromeOS, when all keys works fine in xiwi, again independent on the selected keyboard layout in the xiwi window.

So as a workaround: If I use a keyboard layout without dead keys in ChromeOS, then dead keys works fine in xiwi. (But if use a keyboard layout with dead keys in ChromeOS, then they have to be used twice in xiwi even if they are not dead keys in xiwi).

**Comment by ByrialJensen** [comment]
Isn't this issue not really a duplicate of #1428 (xiwi: Setting a keyboard layout in Chromium OS with dead keys (e.g. US Intl) leads to lost key events)?

**Comment by SnarkBoojum** [comment]
Yes, it looks like it! Let me close.
