### ISSUE TITLE
REQUEST: Fedora support

### ISSUE THREAD

**Issue by matt-pfefferman** [dnschneid/crouton#1549]
Would it be possible to support Fedora? If so, Ill try to help as much as I can, but I have no programming experience......

**Comment by divx118** [comment]
It would be possible, but someone needs to spend some serious time on it. Also after that it needs to be maintained. I had it running in the past, but decided it isn't worth the effort for me. I now boot it with legacy boot which runs pretty good.

**Comment by DennisLfromGA** [comment]
Maurice,

(OT)
I run Linux Mint 14 via legacy boot on mine but, even though the RAM and
CPU show fairly low numbers, it sometimes really slow to respond. I'm using
a Transcend SDHC Class 10 32GB SD Card which I thought would be pretty fast.

Is yours pretty responsive and, if so, what are you using?

Thanx,
-DennisL

On Sat, Mar 28, 2015 at 3:54 PM, Maurice van Kruchten <
notifications@github.com> wrote:

> It would be possible, but someone needs to spend some serious time on it.
> Also after that it needs to be maintained. I had it running in the past,
> but decided it isn't worth the effort for me. I now boot it with legacy
> boot which runs pretty good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1549#issuecomment-87291885>.
>



-- 
*DennyL@GMail*

**Comment by divx118** [comment]
@DennisLfromGA I have fedora 21 with lxde on a class 10 16Gb sd card. IIRC same specs as you. HP chromebook 14 with 2Gb ram and the intel 2955U @ 1.40GHz
It boots up in 20 seconds and is pretty responsive. I only noticed that the chrome browser can cause some slow down. Still need to see what cause it has and if also other programs are affected.

**Comment by DennisLfromGA** [comment]
@divx118 - Yeah, pretty similar except I opted for the 4GB model. I may try some usb sticks, I would expect them to be slower but we'll see. I might put Fedora on one of 'em.

**Comment by DennisLfromGA** [comment]
@divx118,

> It would be possible, but someone needs to spend some serious time on it.

I know @drinkcat has some arch distros too. 
I guess it's not as simple as getting a url and downloading and installing the OS in a chroot.
I'll try to find some online guidance and, if it's not too difficult, I may try one with Linux Mint and Cinnamon.

**Comment by DennisLfromGA** [comment]
I just happened to remember that Jay Lee's ChrUbuntu scripts might be worth taking a look at.
His [latest one](http://goo.gl/FeTFxF) for the Haswell Chromebooks with legacy booting will let you install just about all the flavors of Ubuntu.

**Comment by divx118** [comment]
@DennisLfromGA Hmm with legacy boot I would just use the live cd, Here is what I did for fedora 21 https://github.com/divx118/Usb-boot-chromebook/wiki fedora 21 live cd's has currently a bug that doesn't let you boot it on chromebooks. So you must first install fedora 20 and then update or stick with 20.
BTW the newer the kernel the better support there is for the chromebooks. I also tried ubuntu trusty, but needed to update to a more upstream kernel to get the touchpad working properly.  

On Topic:
For the serious work adding another distro support. It is not that difficult, but you will need to put a lot of time in it. For example for fedora I only found one major issue, it will need a lot of changes in the mega script enter-chroot. That is where I stopped. At that time I couldn't see a clean way to add those changes there so it could be approved to let into crouton. For the rest it is sorting out the packages you need for the targets. At least on fedora they are named differently or other packages are availabe then debian/ubuntu. Also the package manager yum behaves different then apt-get, but that is doable. It would be almost something similar how drinkcat integrated pacman.  
Note that a distro must also support arm to be let into crouton.

**Comment by DennisLfromGA** [comment]
Thanx @divx118,

It doesn't look like Linux Mint has an ARM distro, bummer.

At this point, I'd just like to get it installed and working as a chroot.
I don't know what I need to do to load it in a chroot. Do I try to add it as a release in `installer/debian/releases` and install it via `installer/main.sh` ?
I may have to strip down the *mega script 'enter-chroot'* to launch it???

All unknowns to me at this time I'm afraid...

**Comment by divx118** [comment]
@DennisLfromGA I would make a new release folder, `installer/mint/releases` copy the files from debian in it and adjust to your needs. mint is debian based, so I guess it should be pretty straight forward. Also make a new branch on your git, so you can keep it up to date with crouton master. Best way is if it is possible to keep your changes to the main scripts in crouton to a minimum, that way you can easily rebase.  
Even if it has no arm, and you can keep it up to date with crouton master it can be useful to other people wanting to install mint.

**Comment by DennisLfromGA** [comment]
I'll try that, thanx.

**Comment by matt-pfefferman** [comment]
Mint is Ubuntu based.....

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by mdeguzis** [comment]
There is this, but not actively worked on it seems, I use it: https://github.com/nmilosev/crouton-fedora
