### ISSUE TITLE
gnome target requires pulseaudio for sound to work

### ISSUE THREAD

**Issue by thomie** [dnschneid/crouton#1550]
Using a fresh download of crouton, I created a new chroot with release `trusty` and target `gnome`. Although playing sounds via `aplay some.wav` works, the sound in any gui application doesn't (skype/firefox). Also, in the sound settings 'Output' menu, where it says 'Choose a device for sound output', there aren't any devices listed. After installing pulseaudio, everything works, and `cras` is listed as a sound device.

This problem seems similar to the one reported in #1328 for the `lxde` target. I also tried `xfce`, and there the sounds works out of the box. The `xfce` target comes with pulseaudio preinstalled though.

I suggest installing `pulseaudio` for the `gnome` and `lxde` targets, or perhaps even for the `audio` target.

My machine is an ASUS C300M. Here's the output of `croutonversion`:

```
chronos@localhost / $ sudo enter-chroot -n trusty-gnome-basic croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty-gnome-basic...
crouton: version 1-20150327195116~master:cf2aacba
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome
host: version 6680.78.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Fri Mar 20 17:27:56 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
```

Thank you for crouton! It's a lifesaver.

**Comment by jamesjnadeau** [comment]
Just encountered this when installing gnome as well, I think gnome should install pulse audio.

**Comment by thomie** [comment]
To make the sound work in Skype (which I installed using instructions from https://help.ubuntu.com/community/Skype#Installing_Skype), I had to also install `libpulse0:i386`. Installing the package `pulseaudio:i386` should also work, since it pulls in `libpulse0:i386`.

**Comment by smibarber** [comment]
Many, many targets now have pulseaudio now.
