### ISSUE TITLE
Is there a crouton forum?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1552]
Or should I use this repo's issues.  In general issues is not meant to be a discussion group and it isn't very good for that purpose.

**Comment by DennisLfromGA** [comment]
You can *Hang out in the #crouton IRC channel on freenode.net!*
If you're a Reddit fan try tis - http://www.reddit.com/r/Crouton
Also join the Google+ Community - https://plus.google.com/communities/109120069102230291151

**Comment by mark-hahn** [comment]
Thanks.  

FWIW: I refuse to join Google+ (or Facebook) so that is a shame.

**Comment by DennisLfromGA** [comment]
I understand, there's lots of other places luckily.

On Sat, Mar 28, 2015 at 7:12 PM, mark-hahn <notifications@github.com> wrote:

> Closed #1552 <https://github.com/dnschneid/crouton/issues/1552>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1552#event-267744781>.
>



-- 
*DennyL@GMail*

**Comment by tedm** [comment]
Rumor is that the mods on the reddit.com/r/crouton forum are super smart geniuses ;)

**Comment by mark-hahn** [comment]
I detect a gratuitous self-reference.  (grin)

**Comment by nlaney** [comment]
There's this also, http://stackoverflow.com/questions/tagged/crouton-os

Adding social media links to wiki

**Comment by DennisLfromGA** [comment]
Thanx @nlaney. That's a good start, we can all add to that as we find more...

**Comment by DennisLfromGA** [comment]
Good news! *[James Welbes](https://plus.google.com/u/2/+JamesWelbes/posts)* just started a new **'[Crouton Central](https://groups.google.com/forum/#!forum/crouton-central)'** Google group.

It'll be a great place to ask questions, share experiences and lots more - for all levels of 'crouton' users.
I think an added benefit may be that it will help to keep the 'issue's on this site for issues. ;-)

( I'll add this to the '[Community Links](https://github.com/dnschneid/crouton/wiki/Community-Links)' wiki when I get a chance. )
