### ISSUE TITLE
Dropbox problems

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1554]
I used Dropbox with no problem on Unity.  I had to quit using Unity because the Atom Editor has serious problems there (text cursor disappears, key bindings don't work, etc.).

The Atom Editor works great on xfce but the dropbox install never finishes.  I need help.

I don't care at all what desktop I'm using as long as the Atom Editor works and Dropbox works.  I'd even not use a desktop at all and just run Atom in it's own window with xiwi but that doesn't work.  It gives `Error: Connection failed (code 2).`

Can someone suggest an environment for me?  The actual crouton target would give you extra karma points.  (grin).

Or should I post details of the Dropbox install problem here or on some Dropbox forum?

Version 41.0.2272.102 (64-bit) 
Platform 6680.78.0 (Official Build) stable-channel samus 
Firmware Google_Samus.6300.102.0
Chromebook Pixel 2015

**Comment by DennisLfromGA** [comment]
I don't use it but @tonyxue does ( https://github.com/dnschneid/crouton/issues/1477#issuecomment-77531495 ), you could run it by him.

**Comment by mark-hahn** [comment]
Thank you very much @DennisLfromGA .  After many questions and your referrals to other threads I was able to find a combination of options to get exactly what I wanted.  I can now bring up the Atom  Editor in its own window with no desktop and run other ssh sessions in crosh shells.  And all of this running in ChromeOS.

I had nearly passed the two-week trial period for my chromebook pixel and I was starting to get nervous that I made a mistake.

**Comment by Watney** [comment]
@mark-hahn did you get Dropbox working? If you could briefly describe your installation and setup, others may benefit, like me. Thanks!!

**Comment by mark-hahn** [comment]
### How I use dropbox in crouton, by me, Mark Hahn (ahem) ..

These are very conservative instructions.  Some things I do from superstition.  

This only works with the Unity Desktop, although I start unity for this and then don't use it

### install the Unity desktop target

### install dropbox in chroot (from dropbox.com)

Close any chroots running, especially Unity.

```
# from crosh shell
sudo enter-chroot -n mychroot
cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
mkdir -p ~/bin
wget -O ~/bin/dropbox.py "https://www.dropbox.com/download?dl=packages/dropbox.py"
chmod +x ~/bin/dropbox.py
~/bin/dropbox.py status
.dropbox-dist/dropboxd
```

At this point you will probably get a message with a URL telling you to link your dropbox account.  Do this if needed and then enter `ctrl-c` to stop the daemon `dropboxd`.

### run dropbox

Do a `startunity` to open the desktop.  Start the dropbox daemon in a desktop terminal with ...

```
nohup ~/.dropbox-dist/dropboxd &
```

At this point a dropbox icon will appear at top of the desktop like it does in Windows and I presume the Mac.  You can click on this to see the status or open the dropbox folder.  Whenever you see this icon the dropbox daemon is running.  If it ever disappears start the daemon again using the above command.

At this point I shrink the desktop window down and minimize it.  I don't use the desktop.  From then on I use apps in their own windows with `xiwi` and/or crosh shells that have entered into the chroot.  Dropbox will continue to run when anything is running in that chroot, even in different windows, and won't stop until the last process in the chroot ends. 

I keep the desktop around for two reasons.  It keeps dropbox running when all other windows are closed.  And I go into it when I want to see the dropbox status from the icon.

Enjoy ...

*P.S. I hope everyone got the reference in the title*

**Comment by mark-hahn** [comment]
After more playing around I've discovered that I can run the dropbox daemon without starting Unity.  I check status etc. using the cli tool `~/bin/dropbox.py`.  So instead of keeping a unity desktop running I now keep a crosh shell running and minimized to do the same thing.  There is no pretty icon but the cli tool can tell the same info.

I don't know how much of the installation stuff in the last post is actually needed.  Maybe even Unity isn't needed.  I do know that dropbox doesn't work in an xfce chroot.  When I tried gnome it was too screwed up to try anything.

**Comment by tedm** [comment]
@mark-hahn you know that you can use dropbox from a browser, right? I'm assuming you want to sync and keep things local when offline?

**Comment by mark-hahn** [comment]
>  I'm assuming you want to sync and keep things local when offline?

No, this is all online usage.  I'm using dropbox for the live syncing, not storage.

I have my project's source files in dropbox and I edit them directly in there.  I also have a ssh shell open to my server which has the same dropbox folder synced.  My edits appear in the server with no noticeable delay.  So it is a form of deployment for my debug cycle.

This also means I can close my chromebook at any time and switch to my desktop with the same setup.  I can immediately continue working there with the latest files.

It is also a form of backup.

**Comment by ourlord** [comment]
Hey Mark, just reach here. Why not trying add `dropbox start` at a `.bash_profile` if you're only gonna use `xiwi`? I got my chrome book yesterday and so far it works well with adding that line in my `.bash_profile`.

**Comment by mark-hahn** [comment]
I've given up on dropbox.  I used it for fast syncing from my chromebook to the server so I could edit on my chromebook and run the app on the server right away.  I used it this way happily for months and then I started having reliability problems.  I would make an edit and some files wouldn't change on the server.  Stopping and restarting dropbox didn't help.

So now I'm using `unison` and I'm very happy.  It does 2-way syncing directly between my chromebook and server.  It makes sense to do this instead of sending the changes to the cloud and back.  Unison is supported well and has a lot of features.  I highly recommend it.  Unison is shipped with the Ubuntu standard package.  Just `apt-get install unison`.

**Comment by goodmanproject** [comment]
I also set up xiwi with crouton on a chromebook in order to use LibreOffice to create documents needing more complex layouts than can be currently provided by Google Docs. I like the low overhead of running a single application in a window from "within" ChromeOS and not needing to run a chroot with a full blown desktop environment. That being said I am uncomfortable not having an automatic synced backup of my work. I was going to try dropbox until I read your entire thread. I'm grateful for the effort you invested so that the rest of us can benefit from your experience.

That being said, I have a suggestion for a different approach, and I'd appreciate your opinion. I'm not running a local server and want to continue using cloud centric storage with Google Drive. Here's what I'm doing:

 I create my documents locally in the downloads folder, then move them into a folder on Google Drive. I then select "Available Offline" via the local context menu. It then automagically creates a synced copy locally in my Offline folder on the Chromebook. Changes I make locally from that point forward are synchronized and updated  online on Google Drive. 

How does that sound?
