### ISSUE TITLE
Trouble accessing xorg.freedesktop.org (was Crouton script can't handle a 302?)

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1555]
(Sorry about all these posts.  I'm a newbie to crouton).

I've run into a problem using ...
```
sudo sh ~/Downloads/crouton -t gnome,chrome,xiwi,keyboard -r trusty -n trusty 
```
I got this error... 

```
Download Xorg dummy driver...
--2015-03-28 16:12:30--  http://xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
Resolving xorg.freedesktop.org (xorg.freedesktop.org)... failed: Name or service not known.
wget: unable to resolve host address 'xorg.freedesktop.org'
Failed to complete chroot setup.
```
I get this this when I do `curl xorg.freedesktop.org` in the crosh shell .

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://www.x.org/wiki/">here</a>.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at xorg.freedesktop.org Port 80</address>
</body></html>
```

I assume some script can't handle a 302?

**Comment by mark-hahn** [comment]
when I did `wget http://xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz` in my chros shelll everything worked fine and I got the small file.  So it has nothing to do with a 302.

**Comment by DennisLfromGA** [comment]
The link works so maybe it was a glitch, did you try it again?

On Sat, Mar 28, 2015 at 7:28 PM, mark-hahn <notifications@github.com> wrote:

> (Sorry about all these posts. I'm a newbie to crouton).
>
> I've run into a problem using ...
>
> sudo sh ~/Downloads/crouton -t gnome,chrome,xiwi,keyboard -r trusty -n trusty
>
> I got this error...
>
> Download Xorg dummy driver...
> --2015-03-28 16:12:30--  http://xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
> Resolving xorg.freedesktop.org (xorg.freedesktop.org)... failed: Name or service not known.
> wget: unable to resolve host address 'xorg.freedesktop.org'
> Failed to complete chroot setup.
>
> I get this this when I do curl xorg.freedesktop.org in the crosh shell .
>
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>302 Found</title>
> </head><body>
> <h1>Found</h1>
> <p>The document has moved <a href="http://www.x.org/wiki/">here</a>.</p>
> <hr>
> <address>Apache/2.2.22 (Debian) Server at xorg.freedesktop.org Port 80</address>
> </body></html>
>
> I assume some script can't handle a 302?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1555>.
>



-- 
*DennyL@GMail*
