### ISSUE TITLE
Switching to ChromeOS from Ubuntu not working

### ISSUE THREAD

**Issue by flo9Z** [dnschneid/crouton#1556]
Switching to chromeos from ubuntu not working after update ChromeOS 42.0.2311.60. I have updated my crouton but this is the same problem.

If i press on "ctrl+alt and one of the two arrows" it nothing happens.

**Comment by jojo416** [comment]
I have the same issue as well.

**Comment by divx118** [comment]
And what happens with "ctr-alt-shift + arrow", which should be the correct way to switch between chroots and chromeos?

**Comment by jojo416** [comment]
Divx118, that works. 

Previously though, Ctrl + Alt + Back or Ctrl + Alt + Forward and then also press Ctrl + Alt + Refresh was the method on x86-based Chromebooks; your method was only for ARM-based.

**Comment by divx118** [comment]
@jojo416 It is since some time now the method to work for all architectures. Ctrl + Alt + Back or Ctrl + Alt + Forward and then Ctrl + Alt + Refresh was more of a workaround when the standard method didn't work.

**Comment by flo9Z** [comment]
Thanks, that works !
