### ISSUE TITLE
Problem with unity resolution

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1559]
**Edit:** This post used to be a link to the thread "Default screen resolution" #299.  Now I've moved my comment from there to this post.

---

I have been using Unity for a few days with no problem and I just started getting a `Could not apply the stored configuration for monitors` error when loading it.  

I followed the instructions (Option 3: change resolution) at the pixel wiki page https://github.com/dnschneid/crouton/wiki/Chromebook-Pixel.  The only thing that seemed odd was that the `10-monitor.conf` file didn't exist.  I created it with the contents from the wiki page.  My `cvt 1920 1280 60` output was the same as shown.

After doing this and restarting Unity the message changed to the one below.  (I don't know the details from the old error message).  Note that the message sits there for about a minute then the desktop appears as usual.

```
Could not apply the stored configuration for monitors

none of the selected modes were compatible with the possible modes:
Trying modes for CRTC 63
CRTC 63: trying mode 1920x1280@60Hz with output at 1291x920@60Hz (pass 0)
CRTC 63: trying mode 1360x768@60Hz with output at 1291x920@60Hz (pass 0)
CRTC 63: trying mode 1152x864@60Hz with output at 1291x920@60Hz (pass 0)
CRTC 63: trying mode 1024x768@60Hz with output at 1291x920@60Hz (pass 0)
CRTC 63: trying mode 800x600@60Hz with output at 1291x920@60Hz (pass 0)
CRTC 63: trying mode 640x480@60Hz with output at 1291x920@60Hz (pass 0)
CRTC 63: trying mode 1440x956@60Hz with output at 1291x920@60Hz (pass 0)
CRTC 63: trying mode 1920x1280@60Hz with output at 1291x920@60Hz (pass 1)
CRTC 63: trying mode 1360x768@60Hz with output at 1291x920@60Hz (pass 1)
CRTC 63: trying mode 1152x864@60Hz with output at 1291x920@60Hz (pass 1)
CRTC 63: trying mode 1024x768@60Hz with output at 1291x920@60Hz (pass 1)
CRTC 63: trying mode 800x600@60Hz with output at 1291x920@60Hz (pass 1)
CRTC 63: trying mode 640x480@60Hz with output at 1291x920@60Hz (pass 1)
CRTC 63: trying mode 1440x956@60Hz with output at 1291x920@60Hz (pass 1)
```

My resolution has been fine since the unity install.  I'm only asking this to get rid of the error message and not have to wait the minute.

My install command and system details follow ..

```
sudo sh -e ~/Downloads/crouton -t unity,xiwi,keyboard -r trusty -n mychroot
```
Chromebook Pixel 2015
Version 41.0.2272.102 (64-bit)
Platform 6680.78.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.102.0

**Comment by divx118** [comment]
Closed threads still sends notification, so there isn't really a need to open a new issue so you get noticed.  Also closed threads can be reopened.

**Comment by mark-hahn** [comment]
> there isn't really a need to open a new issue so you get noticed. 

Notifications only go to people who have participated in the thread, correct?  So only a few people involved in a conversation two years ago will see it.  A new issue appears in front of everyone following the issues.  That is a giant difference.  I want anyone who can help to see it.

> closed threads can be reopened.

I tried to do that but couldn't figure out how. 

I realize now that I shouldn't have added the comment just because the subject material was related.  My issue was different than that of the original and so it should have been a new thread.

Sorry for the bother.

**Comment by divx118** [comment]
Sorry, forgot to mention only people that have the rights to reopen/close issues can do that.  
I get notifications, also of old closed threads, because I watch this git. Like also a lot of other people. I don't need to have replied. So no, notifications don't only go to people who participated.  
However like you said, if it is a different issue, it deserves a new thread.  
Maybe it is best to edit your first post and add the relevant info about your issue.

**Comment by mark-hahn** [comment]
I just edited the original post above to be a normal issue instead of a link to a zombie thread.

**Comment by drinkcat** [comment]
@mark-hahn : Since you are using xiwi, I believe the best option for you is to tick/untick the HiDPI checkbox in the extension popup. You'll get full/half resolution that way. Unfortunately we do not support other resolutions (we potentially could, see #1370).

**Comment by mark-hahn** [comment]
> the best option for you is to tick/untick the HiDPI checkbox in the extension popup

That option does what it is supposed to do.  Clicking it immediately changes the resolution of xiwi windows.  

Unfortunately it doesn't affect the problem I'm facing with the  `Could not apply the stored configuration for monitors` error.  It is something wrong with my unity desktop setup.

I'll install a new fresh chroot and see if that fixes it.  I don't know why I didn't think to try this before.

**Comment by mark-hahn** [comment]
A fresh chroot does not show the problem.  So I somehow managed to clobber my setup.  I will now go through the painful process of setting up everything over again.

Sorry for all the trouble.  I should have checked this first thing.  For future issues like this I'll ask the question "have you tried a fresh chroot?".
