### ISSUE TITLE
Chrooot / ChromeOS switching stopped working after update

### ISSUE THREAD

**Issue by chrisofCCL** [dnschneid/crouton#1560]
Just updated my chroot (Trusty, Unity) and now I can no longer switch back to Chromeos.  Any ideas?

Not yet using the Extension pack and Xiwi but will probably give that a try shortly.  Can I update an existing chroot (-u) with -t xiwi?

**Comment by DennisLfromGA** [comment]
Yes, that's the way to do it.

-DennyL

**Comment by chrisofCCL** [comment]
Thanks Dennis - I'll give it a go tonight.  Does anyone have answer to the basic switching question though??

**Comment by divx118** [comment]
Just to be sure you do use ctr-shift-alt left/right arrow, so not only ctr-alt to switch?

**Comment by chrisofCCL** [comment]
Normally just ctrl-alt but I did try ctrl-shift-alt in desperation today 
and that didn't work either.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by divx118** [comment]
@chrisofCCL Well you should use ctrl-shift-alt. The other ctrl-alt was used in the passed a lot when ctrl-shift-alt failed, but that was more of a workaround.
Could you post the output of `croutonversion` in a chroot and your xorg log? (BTW the xorg log preferably on something like gist or pastebin and the link here.)

**Comment by DennisLfromGA** [comment]
On the latest version of 'crouton', 'croutonversion' is now part of the display output - yippee!

**Comment by chrisofCCL** [comment]
xorg.1.log is in here
https://www.dropbox.com/sh/v6xjsxdely6k7a5/AACidkwK6waCIdT40nPyOcn3a?dl=0

I have shared that folder so you should be able to see it.

Croutonversion output is as follows.

crouton: version 1-20150327195116~master:cf2aacba
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xiwi,unity
host: version 6812.52.0 (Official Build) beta-channel quawks_freon 
kernel: Linux localhost 3.10.18 #1 SMP Tue Mar 24 22:15:42 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

I had a go with xiwi and the crouton extension, which I liked but it overloaded my processor - something to do with Unity maybe, so have returned to x11 but I still have the problem I'm afraid.

**Comment by ElSpecialisto** [comment]
I have run into this same issue after the upgrade, even after I upgraded the chroot.  A temporary but unsatisfactory workaround is to press alt+ctrl+shift and then forward/backward TWICE, not once like it used to work.  Pressing once while in chroot results in a frozen / locked up version of Chrome OS.  Pressing the combo a second time gets back to a working Chrome Os.  

I'm a bit of a novice so would love to hear if anyone has been able to figure out how to restore one button combo press switching functionality.

**Comment by chrisofCCL** [comment]
I just changed to the enhanced integration option (xiwi target), which 
seems to work much better. It's then easy to use chromeos for web-based 
stuff and Ubuntu for everything else, and you can copy and paste between 
the two.


Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by divx118** [comment]
@chrisofCCL FYI xiwi is indeed a nice target, but has no gpu acceleration. With xorg you can also copy/paste between chromeos and the chroot, if you install the "extension" target.

**Comment by chrisofCCL** [comment]
ok, I've decided to go back to XORG because of the gpu acceleration issue. Now using xfce Trusty and ChromeOS 43.0.2357.32 beta (64-bit).

However, switching has now got even worse.  ctrl-alt-shift-left just takes me to a blank screen. Now, when I log out of Crouton it again goes to the blank screen. That never used to happen. The symptoms of both seem to be very similar.  Is there any way round this or do we need to wait for a Crouton upgrade?

**Comment by divx118** [comment]
@chrisofCCL This will probably resolve on the next chromeos update see #1475

**Comment by chrisofCCL** [comment]
ok, thanks. I await with bated breath!  Is this about when my version of ChromeOS starts to use freon?

**Comment by divx118** [comment]
@chrisofCCL Yes

**Comment by giliammc** [comment]
how do you go back to xorg

**Comment by divx118** [comment]
@giliammc If you updated your xorg chroot with the xiwi target, you can still start it with XMETHOD xorg by adding `-X xorg` to the startscript. So for example `sudo startxfce4 -X xorg` or update your chroot again with the `-t xorg` target. So it will be using xorg again by default instead of xiwi.

**Comment by giliammc** [comment]
i tried that and got 


chronos@localhost / $ sudo startxfce4 -X xorg
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

ERROR: ld.so: object '/usr/local/lib/croutonfreon.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:37:50 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=b8c42016-e762-9147-9241-79d63d80a629/PARTNROFF=1 hashtree=PARTUUID=b8c42016-e762-9147-9241-79d63d80a629/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=19983e99694f43f58c9b7fe794a36276d6631a9b salt=c1f66bbcb95439a8ee2d0617298166203029c4b74e1da8c2eb976c10a5fbe491" noinitrd vt.global_cursor_default=0 kern_guid=b8c42016-e762-9147-9241-79d63d80a629 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat May  2 16:22:46 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x48) [0x7f96c5b3c848]
(EE) 1: /usr/bin/Xorg (0x7f96c5993000+0x1ad539) [0x7f96c5b40539]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f96c4a8f000+0x10340) [0x7f96c4a9f340]
(EE) 3: /usr/bin/Xorg (0x7f96c5993000+0xb57a6) [0x7f96c5a487a6]
(EE) 4: /usr/bin/Xorg (xf86BusProbe+0x9) [0x7f96c5a1c099]
(EE) 5: /usr/bin/Xorg (InitOutput+0x74d) [0x7f96c5a2a6fd]
(EE) 6: /usr/bin/Xorg (0x7f96c5993000+0x59bab) [0x7f96c59ecbab]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7f96c34cfec5]
(EE) 8: /usr/bin/Xorg (0x7f96c5993000+0x451ee) [0x7f96c59d81ee]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
^[[A/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $

**Comment by divx118** [comment]
@giliammc I don't think you updated your chroot without errors. Is this the same chroot as in #1690 ?

**Comment by giliammc** [comment]
yes

**Comment by divx118** [comment]
@giliammc Then please don't post all over the place until we find a way to update your chroot successfully, so solve #1690 first. Thanks.
