### ISSUE TITLE
Java/Firefox install on HP11 Chromebook.

### ISSUE THREAD

**Issue by misterbreen** [dnschneid/crouton#1561]
Hi there. I'd like Java/Firefox installed on my chromebook/crouton, so I can run Java code in my browser (perhaps like webex apps).

This was answered here for for an Intel chip:
https://github.com/dnschneid/crouton/issues/886

The solution being to run this code:
sudo apt-get install firefox icedtea-plugin libxmu6:i386 libgcj14-awt:i386 libxv1:i386 libpangoxft-1.0-0:i386 libpangox-1.0-0:i386 libstdc++6:i386 && sudo ln -s /usr/lib/i386-linux-gnu/gcj-*/libjawt.so /usr/lib/i386-linux-gnu/

Could someone suggest the command for my HP11 AMD Chromebook?

Thanks.

**Comment by dnschneid** [comment]
Do you mean ARM?

**Comment by misterbreen** [comment]
Yes. I did mean ARM. Thanks. 
Any thoughts?

**Comment by dnschneid** [comment]
firefox + icedtea-plugin should make Java work, but I don't believe I've ever gotten webex to work on ARM.

**Comment by misterbreen** [comment]
Should I just use the same command for my ARM machine? So the i386 syntax still applies?

**Comment by dnschneid** [comment]
Drop the :i386; that's the architecture, and doesn't apply here.
