### ISSUE TITLE
ChromeOS breaks after chromebook sleeps in chroot

### ISSUE THREAD

**Issue by Kareeeeem** [dnschneid/crouton#1563]
If my chromebook sleeps (closing the lid or just letting it sit) while I'm in a chroot, ChromeOS is completely unresponsive after returning to it. I can press on menu items and a browser window will pop up but it will remain empty and nothing will happen. Same goes for clicking on settings for example. Anything that will louch a browser window.

The chroot itself is still functional after the issue occurs. 

I didn't pre install any desktop environments via a  target but I have X installed to run i3. However it doesnt matter if the chromebook sleeps while in a TTY or in the desktop environment. 

````
crouton: version 1-20150327195116~master:cf2aacba
release: jessie
architecture: amd64
xmethod: xorg targets: cli-extra,keyboard,audio,x11,xorg
host: version 6680.78.0 (Official Build) stable-channel peppy kernel:
Linux localhost 3.8.11 #1 SMP Fri Mar 20 15:40:08 PDT 2015 x86_64 GNU/Linux
freon: no
````

**Comment by mojo6911** [comment]
I have the same issue.

**Comment by MAkerboom** [comment]
seems to me like this is the same as: https://github.com/dnschneid/crouton/issues/1513

**Comment by Kareeeeem** [comment]
You're right, seems I did not look properly.

**Comment by drinkcat** [comment]
Apparently fixed. See #1513.
