### ISSUE TITLE
Black screen when using screen recording software.

### ISSUE THREAD

**Issue by mojo6911** [dnschneid/crouton#1566]
I have tried both Kazam and SimpleScreenRecorder. Both cause the screen to go black when it starts recording. You can switch back to ChromeOS and switch right back, and you will still see the screen temporarily. The chroot still responds to keyboard commands, so I can stop the recording with a keyboard shortcut, switch to ChromeOS, then switch back, and everything will be fine.

Same issues here: http://askubuntu.com/questions/600417/trying-to-screen-record-on-ubuntu-trusty-14-04-while-using-chromebook

I have tried it with elementaryOS, Ubuntu Precise, and Trusty running unity.

**Comment by DennisLfromGA** [comment]
Since you're already using crouton, you could try '[screencast](https://gist.github.com/DennisLfromGA/8441689)' originally created by Googler Francois Beaufort, this version has some slight modifications for command-line options, etc.
I like it because it's always recording, even when switching in and out of chroots.

**Comment by mojo6911** [comment]
I would prefer just to record what is going on in the chroot, rather than in ChromeOS. I will check out the script and see if I can get it going to help troubleshoot this issue,

**Comment by mojo6911** [comment]
OK, I tried screencast, and it doesn't record anything inside of the chroot, which is really what I need to do. Thanks for the suggestion, though.

**Comment by DennisLfromGA** [comment]
Very strange indeed, I have a video recorded here https://www.youtube.com/watch?v=KPezVrWsf_I
It's an older one when we were first testing 'Crouton In A Tab', it's been greatly improb ed since then.

Just wondering what 'xmethod' you're using - xorg, xephyr, or xiwi ?

**Comment by mojo6911** [comment]
xorg

**Comment by DennisLfromGA** [comment]
Okay, I'll fire mine up in 'xorg' and see if 'screencast' still works for me - be back soon...

**Comment by DennisLfromGA** [comment]
Bummer, looks like with the new  (friggin') 'frecon', 'screencast' refuses to run - I'' file an issue.

**Comment by mojo6911** [comment]
I installed the xiwi target to mess with it. It worked pretty well, but it was VERY clunky and slow. It is probably because I am running elementary. I bet if I installed xfce, then I could get it to work.

Still, the ideal solution, for me, is to run it as xorg and just start the recorder in the chroot.

**Comment by mojo6911** [comment]
So, after some further testing, I get the same results with avconv and trying to record the screen. I think it has something to do with the xserver running on display 1.0.

**Comment by mojo6911** [comment]
I still have made no progress with this. Any help?

**Comment by DennisLfromGA** [comment]
@mojo6911 - Still no, it's being tracked on https://github.com/dnschneid/crouton/issues/1567#issuecomment-90980225 if you'd like to follow.

**Comment by mojo6911** [comment]
OK, so I have found a viable work around for me. For some reason, it doesn't seem to work with precise, so you need a trusty ubuntu install. With Trusty and Simple Screen Recorder or Kazam, record a selection instead of the whole screen. When you do this, it will allow you to draw a rectangle around what you want to record, so I draw the rectangle around the entire screen, and it works great.

**Comment by drinkcat** [comment]
See #1567.

**Comment by brmbrmcar** [comment]
You cando window screen records inthe chroot as normal on Ubuntu.https://www.youtube.com/watch?v=o0A8BdMdyLk
