### ISSUE TITLE
'screencast' using host-x11 no longer works

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#1567]
My HP Chromebook 14 just updated to using Freon and my 'screencast' script is now broken - and it won't get up. I get the error:

  **No Chromium OS X server is available.**

The pertinent command is:
```
sudo enter-chroot -c /usr/local/chroots -n screencast host-x11 avconv -f alsa -ac 2 -ab 128k -i pulse -f x11grab -r 30 -s 1366x768 -i :0.0 -vcodec libx264 -preset ultrafast -crf 0 Downloads/movie1.mkv
```

It's using the `chroot-bin/host-x11` script and the error stems from this logic, I believe:
```
if [ ! -f "/sys/class/tty/tty0/active" ]; then
    err="No Chromium OS X server is available."
```

I tried adding the 'xorg' xmethod to no avail.

Shall I try to add xmethod 'xiwi' to see if that fixes it?
Is there another, better way to run this or am I now out of luck?

[croutonversion]
```
crouton: version 1-20150331105333~master:589ee11d
release: precise
architecture: amd64
xmethod: xorg
targets: xorg,audio
host: version 6812.52.0 (Official Build) beta-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 24 20:56:57 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by dnschneid** [comment]
There's no X server in Chromium OS with freon, so abusing host-x11 won't work anymore.  You'll either need to make avconv directly access the display data (not sure if possible), or use some Chromium OS native mechanism for screencasting.

**Comment by DennisLfromGA** [comment]
Well those *options* are out of my wheelhouse so I guess 'screencast' is dead :(
Maybe Francois Beaufort will have some ideas, I may try to run it by him.

**Comment by theblacklion** [comment]
@DennisLfromGA Anything new, yet?

**Comment by DennisLfromGA** [comment]
@theblacklion - Nope, I'm afraid not - as yet...
I tried a few things with the 'xiwi' app but haven't yet found anything that works.
The combination of options possible with '[avconv](http://manpages.ubuntu.com/manpages/precise/man1/avconv.1.html)' are extensive, to say the least, so there are many more to try. I'm just not sure I'll have the patience or knowledge to fix it. ;(

**Comment by VenomousSteam81** [comment]
Wait... if you use xiwi or Sommelier, and use ChromiumOS built-in screencasting feature, isn't that still a kind of screencasting via Crouton, or am I misunderstanding?

**Comment by DennisLfromGA** [comment]
@VenomousSteam81,

If you didn't notice this was an issue from 2015 before freon was introduced and it's closed, there may be ways to do it now with the advent of screencasting and other newer ChromeOS features.

-**DennisLfromGA**
