### ISSUE TITLE
Add ElementaryOS support

### ISSUE THREAD

**Issue by matt-pfefferman** [dnschneid/crouton#1571]
Came across this.. Would it be possible to include in mainstream crouton? https://github.com/AldousP/MyDearWatson

**Comment by MarkGavalda** [comment]
Yep, this would be great! Even more so now that Freya stable is coming out in a couple of days! :)

**Comment by dnschneid** [comment]
Actually, it looks like elementary-os/stable now provides packages on ARM, so yes, it seems like it would (finally) make for a good target.

**Comment by MarkGavalda** [comment]
That would be great! I believe the new stable version is coming out in 20hrs or so :) And it's a perfect fit for the less-capable ChromeOS devices. Thanks for your great work @dnschneid

**Comment by tedm** [comment]
I'll try it when it's available. Can you just leave the Midori browser out please?

**Comment by dnschneid** [comment]
@tedm: we'd probably have elementary and elementary-desktop targets (unless "pantheon" is the right term here?), where the first doesn't have a browser other than the classic netsurf-gtk, and the latter has whatever the packages request (in this case, midori).

**Comment by tedm** [comment]
@dnschneid sounds good. Should be very popular. Do a lot of folks use the *-desktop versions? I would think that if they know the difference between the DE [basic] and DE-desktop, then they're likely to know how to use apt-get, aptitude, or the gui package managers? If there's a list of differences, that would be interesting to review.

**Comment by dnschneid** [comment]
"A lot of folks" mostly just copy-paste tutorials, so as long as we release the elementary and -desktop versions at the same time, hopefully the various tutorials will pick up the existence of both.

Realistically speaking, even several months after releasing the target people will STILL be installing it manually via xfce+ppa or whatever the sites currently suggest.  So I think we should just provide the correct tools (in this case, separate basic and desktop targets) and hope people eventually use them properly.

**Comment by tedm** [comment]
Right, even after several years! I just always thought of xfce as a "desktop" of it's own, and Xubuntu as the xfce desktop with a half dozen additional utilities like multimedia players, email, office, and IM utils.

Is xfce-desktop like a French kind of translation for that? :)

**Comment by MarkGavalda** [comment]
The stable version of Freya just came out an hour ago.

**Comment by tedm** [comment]
waiting for the crouton target ...

**Comment by dnschneid** [comment]
Any volunteers to make it?

**Comment by hanslowinc** [comment]
Is there something I could do in the meantime, to update from Freya to Luna?

**Comment by MAkerboom** [comment]
You can follow this also: https://github.com/w /MyDearWatson/issues/4#issuecomment-92354162

**Comment by MAkerboom** [comment]
But there seems tot be an issue with freya support: https://github.com/AldousP/MyDearWatson/issues/4#issuecomment-92354162
?

**Comment by GloverDonovan** [comment]
+1 Elementary OS is amazing alongside Chrome OS. Two simplistic platforms both serving similar yet unique needs. (:

**Comment by Alfriadox** [comment]
I would be glad to transfer some stuff over from https://github.com/AldousP/MyDearWatson but I am new to programming so I might need some help. I will fork it add some things then create a pull request. (I use this tool.)

--Alfriadox

**Comment by Alfriadox** [comment]
NeverMind. Just use the link and folow the instructions there.

**Comment by leejinhuey** [comment]
[MyDearFreya](https://drive.google.com/folderview?id=0B5m4MQHPNKZjc1FfWldnWnZyM2M&usp=sharing), which appears to be [a fork of MyDearWatson](https://www.reddit.com/r/Crouton/comments/32akho/any_guides_to_getting_the_new_elementary_freya/) by [Skitals](https://www.reddit.com/user/Skitals) could be useful.

**Comment by dnschneid** [comment]
And yet nobody seems to want to put in the effort to get it pulled into crouton proper :(

**Comment by DokterVintij** [comment]
dnschield, If I wanted to put the effort to make elementary work on crouton what will I have to do and how can i do so. Does MyDearFreya work and if so what are the steps to get it installed on my chromebook.

**Comment by DennisLfromGA** [comment]
@DokterVintij,

> Does MyDearFreya work...

Yes, I have installed it on my HP Chromebook 14 (Falco) and it works.
I had to make some minor modifications to it since I have a CROUTON partition but it installed and worked just fine.

>  ...and if so what are the steps to get it installed on my chromebook.

Download [it](https://drive.google.com/folderview?id=0B5m4MQHPNKZjc1FfWldnWnZyM2M&usp=sharing), unzip it, and read the README for instructions, it's pretty simple.

Once that's done, you might get closer to be able to figure out what's needed to make a crouton freya target.

**Comment by DokterVintij** [comment]
@DennisLfromGA 

Thank you for your response. I tried MyDearFreya and slightly edited to crouton partition and i have it working perfectly on my Toshiba Chromebook 2. It took me about 3 tries to get it working the way I wanted.

**Comment by DennisLfromGA** [comment]
@DokterVintij - That's great and hopefully brings us closer to having a freya/elementary target.

**Comment by odysseusjak** [comment]
@DokterVintij 

Can you tell me how you set this up? I'm completely new to using this but I, too, have a Toshiba Chromebook 2 and would like to use Freya. Step by step would be great! Thanks.

**Comment by FlyKoBo** [comment]
Hi I was just wondering if Freya would work on the XE303C12? Or does it only work on intel?

**Comment by seijinshu** [comment]
If I had the spare time, I might try working on this target. I already will be working on 2 target, so it would be nice to kill 2 birds with one stone.

**Comment by Alfriadox** [comment]
I might be able to integrate this somehow. I will try.

**Comment by Alfriadox** [comment]
You may assign this issue to me.

**Comment by Alfriadox** [comment]
I will get elementary Luna working. Hopefully by the end of this week.

**Comment by Alfriadox** [comment]
This will mostly entail copying over files from [My fork of MyDearWatson](https://github.com/Alfriadox/MyDearWatson) (My fork)(pull requested to the original.)

**Comment by Asuza** [comment]
@Alfriadox, did you ever happen to finish this? I'm looking forward to trying Elementary OS but wasn't able to find any good information on getting it running with crouton. This would be perfect!
