### ISSUE TITLE
sd cards

### ISSUE THREAD

**Issue by brw31415** [dnschneid/crouton#1573]
I have crouton/trusty installed internally , how does adding an external sd card help, storage, memory, or both, as I noticed much of my file system is used up. Would it be better to just move the chroot to the sd drive completely. This is related to possibly another, similar question I asked here.

**Comment by Timvrakas** [comment]
The SD card is used to increase storage space. You would either move the chroot to you SD card, or just keep large files on the SD card to free up internal space.

**Comment by dnschneid** [comment]
But beware of #288
