### ISSUE TITLE
Starting CLI chroot issues

### ISSUE THREAD

**Issue by leogaggl** [dnschneid/crouton#1575]
I am using a trusty chroot in the browser extension and things are working as expected (thanks for the great work !) on a Toshiba Chromebook2 (Firmware Google_Swanky.5216.238.5).

However for most tasks a simple CLI instance would be more efficient and I just added another chroot with cli-extra (tried both trusty and precise). But I seem to be unable to start them. 

Entering /mnt/stateful_partition/crouton/chroots/precise...
Couldn't get a file descriptor referring to the console
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Not sure if this is an interaction with the crouton chrome browser extension. Any pointers appreciated.

**Comment by dnschneid** [comment]
This is likely due to freon; startcli won't work.  But you can enter the chroot without a graphical session by just running `sudo enter-chroot`.
