### ISSUE TITLE
Receive notification of errors in my i3 config file on loading xiwi the first time

### ISSUE THREAD

**Issue by ticviking** [dnschneid/crouton#1576]
On a new precise chroot on my toshiba chromebook 2, I get a big red bar notifying me of an error.

The contents of the error file 
```
ERROR:
ERROR: CONFIG: syntax error, unexpected $undefined
ERROR: CONFIG: in file "/etc/crouton/xiwi.conf", line 13:
ERROR: CONFIG:   client.focused          #8E8E8F #EAEAEB #000000 #8E8E8F
ERROR: CONFIG:                                                   ^
ERROR:
ERROR:
ERROR: CONFIG: syntax error, unexpected $undefined
ERROR: CONFIG: in file "/etc/crouton/xiwi.conf", line 14:
ERROR: CONFIG:   client.focused_inactive #8E8E8F #CACACB #525252 #8E8E8F
ERROR: CONFIG:                                                   ^
ERROR:
ERROR:
ERROR: CONFIG: syntax error, unexpected $undefined
ERROR: CONFIG: in file "/etc/crouton/xiwi.conf", line 15:
ERROR: CONFIG:   client.unfocused        #8E8E8F #CACACB #525252 #8E8E8F
ERROR: CONFIG:                                                   ^
ERROR:
ERROR:
ERROR: CONFIG: syntax error, unexpected $undefined
ERROR: CONFIG: in file "/etc/crouton/xiwi.conf", line 16:
ERROR: CONFIG:   client.urgent           #FF8E8E #FFCACB #520000 #FF8E8E
ERROR: CONFIG:                                                   ^
ERROR:
ERROR:
ERROR: CONFIG: syntax error, unexpected $undefined, expecting <number> or <word> or '+'
ERROR: CONFIG: in file "/etc/crouton/xiwi.conf", line 27:
ERROR: CONFIG:   bindsym --release button2 kill
ERROR: CONFIG:           ^
ERROR:
ERROR: FYI: You are using i3 version 4.1.2 (2012-01-27, branch "release-4.1.2")
```

output of croutonversion
```
crouton: version 1-20150404180843~master:66d0393b
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,cli-extra
host: version 6812.59.0 (Official Build) beta-channel swanky_freon 
kernel: Linux localhost 3.10.18 #1 SMP Wed Apr 1 00:22:20 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by dnschneid** [comment]
Hmm, looks like we may need to use [the i3 ppa](https://i3wm.org/docs/repositories.html).

**Comment by ipstone** [comment]
Hello, I noticed that *i3 is installed in the xiwi target by default* - is somehow i3 being used by xiwi?

I am also trying to start i3 by using "xiwi xinit i3", which has the same error as starting "xinit i3" with xorg. If it's just due to i3 startup script, we can just fix by patching the startup script ... will continue to investigate.

**Comment by divx118** [comment]
@ipstone Try `xinit /usr/bin/i3` If there are no `/` then xinit will tread it as an argument to pass it through to the standard script  ~/.xinitrc So use the full path which IIRC is /usr/bin, but you will have to check that where i3.

**Comment by ipstone** [comment]
Thanks @divx118 , it works! I got a fully functional i3 within xiwi.  

The only remaining issue is that somehow another blank/black window launched while executing "xiwi xinit /usr/bin/i3" - what might be the cause of that additional window? Once I can figure this out, will write down the instructions to run i3 with xiwi in the Wiki section.

Thanks

**Comment by divx118** [comment]
@ipstone that is because you start it with xiwi. If you have also xorg installed and that is the default then use `XMETHOD=xiwi xinit /usr/bin/i3` else if you don't have xorg then you can just use `xinit /usr/bin/i3`

**Comment by dnschneid** [comment]
Actually, that sounds like a bug.  `xiwi xinit` should really transform itself into `XMETHOD=xiwi xinit`.  Could you file a separate bug for that, please?

**Comment by ipstone** [comment]
Just for the completeness on using i3 on crouton xiki, I updated the following wiki page: https://github.com/dnschneid/crouton/wiki/i3

**Comment by jonchurch** [comment]
I'm receiving the same error when using xiwi to launch sublime text 3 on a toshiba 2 chromebook as well. 

I'm not running the command with sudo.

croutonversion outputs as such
`crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xiwi
targets: core,xiwi,keyboard,x11,cli-extra,extension
host: version 7647.84.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Feb 18 00:27:11 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
(precise)duarte@localhost:~$ croutonversion
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xiwi
targets: core,xiwi,keyboard,x11,cli-extra,extension
host: version 7647.84.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Feb 18 00:27:11 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes`

Sublime launches, but with the error bar. Sublime seems to be working fine, but I want to fix the error. Any help would be greatly appreciated =]

**Comment by mikefedyk** [comment]
I get this error as well with precise while running: xiwi keepassx

**Comment by dnschneid** [comment]
Finally fixed this!  Yay!

**Comment by tbloedel** [comment]
@dnschneid 

New to Crouton (installed today), trying to get single app mode working... having this problem with the Error Bar, indicating the same errors as in https://github.com/dnschneid/crouton/issues/1601

What was the fix, or any clues what I should be looking at?

**Comment by dnschneid** [comment]
You shouldn't be hitting the issue...what command did you run to create the chroot?  Could you post the output of `sudo edit-chroot -all`?

**Comment by tbloedel** [comment]
Installed per the xiwi wiki page, using:
`crouton -t xiwi
`
edit-chroot output:
```

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161012155921~master:68e8a354
release: precise
architecture: armhf
xmethod: xiwi
targets: xiwi
host: version 8530.96.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Oct 4 16:01:18 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

**Comment by dnschneid** [comment]
Okay, that was stupid.  Try it again the messages should go away.

**Comment by RobertGoulding** [comment]
I recently updated crouton after the latest ChromeOS update.  The error banner has suddenly reappeared.  edit-chroot -all:

name: precise
encrypted: no
Entering /media/removable/USB Drive/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce
host: version 9000.66.0 (Official Build) beta-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jan 17 21:51:58 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
