### ISSUE TITLE
Fresh crouton + new trusty chroot with -t xiwi = no keyboard 

### ISSUE THREAD

**Issue by Watney** [dnschneid/crouton#1578]
Just downloaded a fresh crouton and set up a new chroot to checkout the new xiwi coolness. To my surprise, only a few keys on the keyboard work. The alphanumeric are dead. The modifiers seem to work. 

For extra measure, I updated the chroot, but still no keyboard. The same behavior persists whether I run LXDE in a window or an app in a window or tab. :( 

crouton: version 1-20150404180843~master:66d0393b
release: trusty
architecture: amd64
xmethod: xiwi
targets: lxde,keyboard,extension,xiwi,cli-extra
host: version 6931.0.0 (Official Build) dev-channel glimmer_freon 
kernel: Linux localhost 3.10.18 #1 SMP Tue Mar 31 03:42:27 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

[Edit] I've discovered that a few keys work, including numbers (1,2,3...) the CrOS keys (e.g., Search), and Modifier+Key combos (e.g., Alt+F opens the File menu in LibreOffice Writer, but "f" in the document body is unregistered. 

[Edit] I uninstalled the ``-t keyboard`` following [the keyboard guide](https://github.com/dnschneid/crouton/wiki/Keyboard) in the Wiki. The keyboard worked correctly on the first launch of LibreOffice Writer in a Tab. But, on the second launch, No Keyboard. 

So, I undated the chroot and reinstalled ``-t keyboard`` but the keyboard still behaves as described above. No alpha keys. She's dead Jim.

**Comment by Aln-Bdx** [comment]
I had the same issue. I resolved it by disabling the parameter "automatic correction in web field" in my google account. I think  for automatic correction it needs to listen the keyboard, xiwi doesn't appreciate this listening so keyboard becomes very slow (if you keep your finger on a letter after 10 seconds the letter come on the screen)

**Comment by Watney** [comment]
@Aln-Bdx Thank you. I also had automatic spelling correction enabled in the CrOS settings: *Languages and input*-> *Input Method* -> *Configure* (along with a flag, though this may no longer be necessary). After disabling spelling correction, the keyboard works as expected. 

(I'm going to leave this open to make sure that @dnschneid is aware of the issue.)

**Comment by DennisLfromGA** [comment]
@Aln-Bdx, 
> I had the same issue. I resolved it by disabling the parameter "automatic correction in web field" in my google account.

Are you referring to this Chrome flag ?
- "[How to enable auto correct feature in Chrome \[Tip\]](http://dottech.org/166090/how-to-enable-auto-correct-feature-in-chrome-tip/)"

**Comment by Watney** [comment]
@DennisLfromGA I left the Chrome enabled, but disabled in the settings 
Step 1
![1](https://cloud.githubusercontent.com/assets/5377590/7006791/b9fb721e-dc38-11e4-9452-937275c2ba1b.png)

Step 2
![2](https://cloud.githubusercontent.com/assets/5377590/7006792/ba83081e-dc38-11e4-9721-89650f27f83f.png)

**Comment by DennisLfromGA** [comment]
Thanx all, I'll tweak those settings.

**Comment by dnschneid** [comment]
Looks like another manifestation of #1457
