### ISSUE TITLE
Question: do you need to manually delete+re-download crouton to update a chroot?

### ISSUE THREAD

**Issue by Watney** [dnschneid/crouton#1579]
The Wiki explains when updating, you need to download a fresh ``crouton`` before updating. Somewhere I thought I read that ``-u`` auto-updates ``crouton``. Hence, my lame question: 

Do I need to delete and then re-download a fresh ``crouton`` before updating a chroot?

**Comment by DennisLfromGA** [comment]
Probably not, since the creation of the ['crouton' installer](https://github.com/dnschneid/crouton/blob/master/installer/crouton).
```
# This is an indirect script. The actual installer will be downloaded, cached,
# and run with any parameters provided. Cached installer will be retained for
# 30 minutes unless this downloader is newer than the timestamp of the cache.
# Set CROUTON_BRANCH to change the branch downloaded.
```
It does, however, get updated but not nearly as often as the main program.

**Comment by Watney** [comment]
Thanks @DennisLfromGA When looking at the output of ``croutonversion`` I should focus on ``master:66d0393b`` not the date ``20150404180843``

**Comment by DennisLfromGA** [comment]
Correctomondo ;)
