### ISSUE TITLE
Cant enter ChromeOS username or non security textboxes

### ISSUE THREAD

**Issue by lucasheer** [dnschneid/crouton#1580]
I have wiped my chromebook 7 or 8 times because of this issue. When I download KDE, XFCE, or Unity, I start my chromebook up and am not able to enter ChromeOS. I can type my email password or wifi password, but not anything that doesn't have hidden text. The on-screen keyboard doesn't even work. However, to enter Ubuntu, I open up the developer console from log in screen and start crouton. I wouldn't need to be posting this cause i prefer Ubuntu or Linux, but recently I installed Trusty Tahr Unity, and I get some random server error:
No screens found(EE)

IDK if worth mentioning, but If i kept restarting my chromebook when I had XFCE I would eventually be able to log in. After installing Ubuntu I haven't been able to log in once.

Sorry about all my problems, hoping some other people went through trouble too. When I start my chromebook up I get OS verification screen and I just press CTRL + D, sometimes this just takes me to a screen trying to put OS verification on. I have to restart my chromebook until it doesn't show this screen.

Please help me, Thanks in advanced :D

**Comment by lucasheer** [comment]
After lots of reboots and endless tries at Sudo startunity, I finally got it to get in unity from developer console though. Restarted chromebook and now im presented with the same problem. Cant login and cant start Ubuntu.

**Comment by DennisLfromGA** [comment]
@lucasheer,

Your dilemma of not being able to log in to your Google account is pretty serious.
When you say :

> I have wiped my chromebook 7 or 8 times because of this issue.

Do you mean *'powerwashed'* it or actually did a *'usb restore'*?
I imagine you mean 'powerwash', I think you need to do a 'usb restore'.
Then you need to download a fresh version of 'crouton' and update your chroot.

If you decide to do a 'usb restore', please backup your chroot to external media first, then you won't need to start from scratch.

Hope this helps,
-DennisL

**Comment by lucasheer** [comment]
OK OK, I found out a way i can get back into Ubuntu.
First from login (cause i cant get in) I go to developer console and type start unity
After I get the error I go CTRL + ALT + F3
Then back CTRL + ALT + F2
And finally back to ChromeOS CTRL + ALT + F1
And now I CTRL + ALT + F2 and type Sudo startunity and it enters Ubuntu :)

**Comment by lucasheer** [comment]
@dennisLfromGA sorry about my new comment i didn't refresh the page lol

I meant I deleted all local data by exiting developer mode and then re-entering develoepr mode.

**Comment by lucasheer** [comment]
@DennisLfromGA Edit: I redid my chromebook just to try to be able to login.
