### ISSUE TITLE
Unexpected Password Request

### ISSUE THREAD

**Issue by kmages** [dnschneid/crouton#1582]
Hi.  I followed your instructions, and was able to get trusty downloaded,
now I need to know how to launch it in a tab.  Do I go from the terminal or from the
crouton integration app?  What is the launch command?  I tried sudo
startunity from chroot with no success, I also tried from the integration
app which shows that trusty is available.

**Comment by kmages** [comment]
I fixed the password issue, now I get a different problem:

Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n trusty -t xorg,xiwi
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots not found.
/usr/local/chroots/trusty does not exist; cannot update.
Valid chroots:
chronos@localhost / $

**Comment by divx118** [comment]
`sudo sh ~/Downloads/crouton -u -n trusty -t xorg,xiwi` is for updating a chroot. notice `-u` The correct way is `sudo sh ~/Downloads/crouton -r trusty -t xorg,xiwi` BTW `-n` defines the name of the chroot.

**Comment by kmages** [comment]
​Most kind thanks!​
[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/a809b529510ae94d73b08388db42da5a/0f1c04a313b3dbcee37dc6dac5f2827f?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by kmages** [comment]
OK, I got trusty to download, how do I launch her?  I am accustomed to running in separate sessions, not as a tab.  Thanks in advance!

**Comment by kmages** [comment]
​​
Hi.  I followed your instructions, and was able to get trusty downloaded,
now I need to know how to launch it.  Do I go from the terminal or from the
crouton integration app?  What is the launch command?  I tried sudo
startunity from chroot with no success, I also tried from the integration
app which shows that trusty is available.
[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/e853c151ca6071486df6fff290c516e4/0ed9487128e481572db899cbcd3c3ace?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by DennisLfromGA** [comment]
@kmages,

When you installed your chroot, you just installed two 'xmethods', namely `xorg` and `xiwi`.
Those are used for the graphical / windowing environment that's employed in the chroot.

You now need to install some desktop targets, there's a bunch to choose from, enter -
  `sudo sh ~/Downloads/crouton -t list` to get a complete list. 

Once you've decided on one or more, update your chroot with something like this -
  `sudo sh ~/Downloads/crouton -t xfce,unity -u`
That will install both 'xfce' and 'unity' desktops with a small footprint so they won't take up too much space.

You can run them using -
  `sudo startxfce4` or `sudo startunity`

These are just two examples, when you install a target, at the end of the installation, it will show you some tips about how to start them and how to switch from your chroot back to Chrome OS.

**Comment by kmages** [comment]
Thanks again.  I'll let you know how it goes.  Sorry for the dumb questions.
[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/d508c36403c4e847117b8c3e6c454e82/01d7248a4c670e30f3e9ca10114ae1c9?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by kmages** [comment]
Here is what I get:

chronos@localhost / $ sudo sh ~/Downloads/crouton -t,unity -u
Migrating data from legacy chroots directory /usr/local/chroots to
/mnt/stateful_partition/crouton/chroots...
/usr/local/chroots/precise does not exist; cannot update.
Valid chroots:
trusty

[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/29a38e2159a0d031b9a2794178e927be/c5cadeca8d6bba5c0a7997a2d322f7da?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by DennisLfromGA** [comment]
Try `sudo sh ~/Downloads/crouton -t,unity -u -n trusty`

**Comment by kmages** [comment]
So, Ubuntu opened, but in a separate session, not in a tab:

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Done! You can enter the chroot using enter-chroot.
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Mar 20
15:41:09 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init
cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro
dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1
dm="1 vroot none ro 1,0 2506752 verity
payload=PARTUUID=fd004e85-7a71-fa4a-9f3d-341596d5ce75/PARTNROFF=1
hashtree=PARTUUID=fd004e85-7a71-fa4a-9f3d-341596d5ce75/PARTNROFF=1
hashstart=2506752 alg=sha1
root_hexdigest=5d5557b5b04108e7ce8162c9f15eb3149ec4163a
salt=a9343ded2666b5870d2398f860f7ef9c75986bb11576ba379b0941335289303f"
noinitrd vt.global_cursor_default=0
kern_guid=fd004e85-7a71-fa4a-9f3d-341596d5ce75 add_efi_memmap
boot=local noresume noswap i915.modeset=1 tpm_tis.force=1
tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see
http://www.ubuntu.com/support)
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Apr  6 20:10:38 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20150404180843~master:66d0393b
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,xorg,xiwi
host: version 6680.78.0 (Official Build) stable-channel samus
kernel: Linux localhost 3.14.0 #1 SMP Fri Mar 20 15:41:09 PDT 2015
x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Compat map for group 2 redefined
>                   Using new definition
> Warning:          Compat map for group 3 redefined
>                   Using new definition
> Warning:          Compat map for group 4 redefined
>                   Using new definition
Errors from xkbcomp are not fatal to the X server
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup
Hangup

waiting for X server to shut down (EE) Server terminated successfully
(0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under
/mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $


[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<http://about.me/KenMages>

**Comment by DennisLfromGA** [comment]
> xmethod: xorg
> targets: unity,xorg,xiwi

To start unity in a tab, use: `sudo enter-chroot xiwi -T startunity`

There's lots of good info. in the [README](https://github.com/dnschneid/crouton/blob/master/README.md) and the [wiki pages](https://github.com/dnschneid/crouton/wiki), check'em out...

**Comment by kmages** [comment]
I will.  Thanks again.

kgm

**Comment by kmages** [comment]
Got this in the chroot window but a "trusty window" did open, just nothing
in it.

compiz (core) - Warn: Attempted to restack relative to 0x2600007 which
is not a child of the root window or a window compiz owns
Gtk-Message: Failed to load module "canberra-gtk-module"

(unity-settings-daemon:1350): AccountsService-WARNING **:
SetInputSources call failed:
GDBus.Error:org.freedesktop.Accounts.Error.PermissionDenied: Not
authorized
Error preparing AM: The name org.freedesktop.Telepathy.AccountManager
was not provided by any .service files

(zeitgeist-datahub:1928): GLib-GObject-WARNING **: invalid (NULL)
pointer instance

(zeitgeist-datahub:1928): GLib-GObject-CRITICAL **:
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)'
failed

**Comment by kmages** [comment]
I think what happens is that Ubuntu tries to open itself and is spread
across several tabs, when I look at the crouton integration I see trusty in
three windows.  Does this make sense?

**Comment by DennisLfromGA** [comment]
It makes sense if you've tried it several times.

Why don't you just try starting unity full-screen first -

  `sudo startunity -X xiwi`

Once you know that works, then get *fancy*. ;)

**Comment by kmages** [comment]
You are such a decent helpful guy, really appreciate you spoon feeding all
of this to me.

OK, that works great but the version of Ubuntu I have is very incomplete,
no browser or software.  Should I have installed a different build?  It is
definitely 14.04 but it is bare compared to the version I had on my
previous Pixel which had Firefox and a software updater, etc.

**Comment by DennisLfromGA** [comment]
You can install software in the chroot or you can update your chroot with the full unity-desktop meta-package. If you decide to install the unity-desktop via the crouton method, you'll first need to install 'network-manager' while in your chroot:

  `sudo apt-get install network-manager`

Then exit the chroot and install the unity-desktop:

  `sudo sh ~/Downloads/crouton -t unity-desktop -n trusty -u`

See https://github.com/dnschneid/crouton/issues/1408 for more info.

**Comment by kmages** [comment]
You can close this ticket.  You really are a genius.  Works perfectly!

Kind thanks.

kgm
[image: Ken Mages on about.me]

Ken Mages
about.me/KenMages
<https://t.yesware.com/tl/9b0ff9b8918d86354a71928f56afa01c3ee7c09a/5a8ec4400b8220f093a05474cc82b3d8/1fc09646bb19ad4903a9d11ed80d6355?ytl=http%3A%2F%2Fabout.me%2FKenMages>

**Comment by DennisLfromGA** [comment]
Cool, glad it's working...
