### ISSUE TITLE
Crouton Extension displays loading, instead of list running chroots.

### ISSUE THREAD

**Issue by divx118** [dnschneid/crouton#1584]
crouton integration 2.4.0

```
(trusty)maurice@localhost:~$ croutonversion
crouton: version 1-20150404180843~master:66d0393b
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce,keyboard,extension,chrome
host: version 6931.0.0 (Official Build) dev-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 31 05:07:46 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
When clicking the extension icon it will display `loading...` instead of the list of chroots. You will need to click it away and then click again on the icon to display the list. If it still displays `loading...` you will need to repeat the former. It is a bit of hit and miss. It seems the code to display the list isn't triggered  every time or hangs in an endless loop sometimes.  
If nothing is in the list, so no chroot or xiwi app running then it just displays `loading...` for a second or  two and will continue (display log, debugging if you enabled it and the status disconnected). This looks normal to me.

**Comment by Timvrakas** [comment]
Happens to me too with Unity/Trusty on C720.
Obviously not a serious issue but I definitely noticed.
