### ISSUE TITLE
Can't stop Kali

### ISSUE THREAD

**Issue by leto** [dnschneid/crouton#1588]
My initial experience with Kali via crouton is very positive. First bug-like thing I ran into is this:

```
(kali)root@localhost:~# halt
WARNING: could not determine runlevel - doing soft halt
  (it's better to use shutdown instead of halt from the command line)
shutdown: /run/initctl: No such file or directory
init: /run/initctl: No such file or directory
(kali)root@localhost:~# 
```

and then nothing happens. Is this because the crouton version of Kali has been stripped down, perhaps a bit too much?

The ```halt``` command works in my Ubuntu chroot, so this seems Kali-specific.

```
crouton: version 1-20150404180843~master:66d0393b
release: kali
architecture: armhf
xmethod: xephyr
targets: xfce
host: version 6680.78.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Fri Mar 20 17:02:35 PDT 2015 armv7l GNU/Linux
freon: no
```

**Comment by MAkerboom** [comment]
can't you just type `exit` ?

**Comment by leto** [comment]
```exit``` closes the current shell or a Terminal window if there is only one tab. It is not the command to shutdown a system.

**Comment by MAkerboom** [comment]
Because you try it from the console (not the GUI) maybe you did an enter-chroot and it would exit the only shell availeble.

**Comment by drinkcat** [comment]
halt, if it worked, would probably shut down the whole system.
