### ISSUE TITLE
crouton bluetooth networking?

### ISSUE THREAD

**Issue by williamsgray** [dnschneid/crouton#1589]
I'm trying to make a network of Chromebooks (via debian crouton) talk to each other over bluetooth (for use in an environment where 802.11 / wifi is not allowed).  I'm prototyping with an ASUS C200 because of the long battery life.  I'm using kde and debian jessie crouton.  I've built and loaded bnep.ko and rfcomm.ko kernel modules, but I can't seem to even get past bluetooth pairing...

I can make complete bluetooth networking function fine between two old thinkpads running native debian, but when I try to do bluetooth pairing from the crouton debian Chromebook it looks like a cancel message happens immediately after the pairing request.

Ideas / Suggestions??   Thanks!

l2ping works great:

# l2ping 00:1E:4C:FC:0D:0E
Ping: 00:1E:4C:FC:0D:0E from 00:02:72:C9:51:C4 (data size 44) ...
44 bytes from 00:1E:4C:FC:0D:0E id 0 time 6.46ms
44 bytes from 00:1E:4C:FC:0D:0E id 1 time 8.58ms
44 bytes from 00:1E:4C:FC:0D:0E id 2 time 9.16ms
44 bytes from 00:1E:4C:FC:0D:0E id 3 time 9.58ms
44 bytes from 00:1E:4C:FC:0D:0E id 4 time 9.49ms
^C5 sent, 5 received, 0% loss

But attempted pairing doesn't even wait for pin code to be entered on target:

# ./simple-agent -i hci2 00:1E:4C:FC:0D:0E
Agent registered
RequestPinCode (/org/bluez/hci2/dev_00_1E_4C_FC_0D_0E)
org.bluez.Error.AuthenticationFailed: Authentication Failed
Creating device failed: org.bluez.Error.AuthenticationFailed: Authentication Failed

hcidump output for pairing attempt:

< HCI Command: Create Connection (0x01|0x0005) plen 13
    bdaddr 00:1E:4C:FC:0D:0E ptype 0xcc18 rswitch 0x00 clkoffset 0x0000
    Packet type: DM1 DM3 DM5 DH1 DH3 DH5
> HCI Event: Command Status (0x0f) plen 4
    Create Connection (0x01|0x0005) status 0x00 ncmd 1
> HCI Event: Connect Complete (0x03) plen 11
    status 0x00 handle 12 bdaddr 00:1E:4C:FC:0D:0E type ACL encrypt 0x00
< HCI Command: Read Remote Supported Features (0x01|0x001b) plen 2
    handle 12
> HCI Event: Command Status (0x0f) plen 4
    Read Remote Supported Features (0x01|0x001b) status 0x00 ncmd 1
> HCI Event: Max Slots Change (0x1b) plen 3
    handle 12 slots 5
> HCI Event: Read Remote Supported Features (0x0b) plen 11
    status 0x00 handle 12
    Features: 0xff 0xff 0x8f 0xfe 0x9b 0xf9 0x00 0x80
< HCI Command: Remote Name Request (0x01|0x0019) plen 10
    bdaddr 00:1E:4C:FC:0D:0E mode 2 clkoffset 0x0000
> HCI Event: Command Status (0x0f) plen 4
    Remote Name Request (0x01|0x0019) status 0x00 ncmd 1
> HCI Event: Remote Name Req Complete (0x07) plen 255
    status 0x00 bdaddr 00:1E:4C:FC:0D:0E name 'debian1'
< HCI Command: Authentication Requested (0x01|0x0011) plen 2
    handle 12
> HCI Event: Command Status (0x0f) plen 4
    Authentication Requested (0x01|0x0011) status 0x00 ncmd 1
> HCI Event: Link Key Request (0x17) plen 6
    bdaddr 00:1E:4C:FC:0D:0E
< HCI Command: Link Key Request Negative Reply (0x01|0x000c) plen 6
    bdaddr 00:1E:4C:FC:0D:0E
> HCI Event: Command Complete (0x0e) plen 10
    Link Key Request Negative Reply (0x01|0x000c) ncmd 1
    status 0x00 bdaddr 00:1E:4C:FC:0D:0E
> HCI Event: PIN Code Request (0x16) plen 6
    bdaddr 00:1E:4C:FC:0D:0E
< HCI Command: PIN Code Request Reply (0x01|0x000d) plen 23
    bdaddr 00:1E:4C:FC:0D:0E len 4 pin '0000'
> HCI Event: Command Complete (0x0e) plen 10
    PIN Code Request Reply (0x01|0x000d) ncmd 1
    status 0x00 bdaddr 00:1E:4C:FC:0D:0E
< HCI Command: PIN Code Request Negative Reply (0x01|0x000e) plen 6
    bdaddr 00:1E:4C:FC:0D:0E
> HCI Event: Command Complete (0x0e) plen 10
    PIN Code Request Negative Reply (0x01|0x000e) ncmd 1
    status 0x00 bdaddr 00:1E:4C:FC:0D:0E
> HCI Event: Auth Complete (0x06) plen 3
    status 0x06 handle 12
    Error: PIN or Key Missing
< HCI Command: Read Clock Offset (0x01|0x001f) plen 2
    handle 12
> HCI Event: Command Status (0x0f) plen 4
    Read Clock Offset (0x01|0x001f) status 0x00 ncmd 1
< HCI Command: Disconnect (0x01|0x0006) plen 3
    handle 12 reason 0x13
    Reason: Remote User Terminated Connection
> HCI Event: Command Status (0x0f) plen 4
    Disconnect (0x01|0x0006) status 0x00 ncmd 1
> HCI Event: Disconn Complete (0x05) plen 4
    status 0x00 handle 12 reason 0x16
    Reason: Connection Terminated by Local Host

**Comment by drinkcat** [comment]
Sorry for the delay, I hope you found a solution... If not, it might be that some Chromium OS daemons are conflicting with your Bluetooth hacks. You could try `sudo stop bluetoothd` in crosh.
