### ISSUE TITLE
How to get Youtube History in android programmatically

### ISSUE THREAD

**Issue by anagham** [dnschneid/crouton#1593]
I am developing an android application to get youtube history in android app. I read about Youtube Player API but it is only to play videos. Also I referred Youtube Data API V3 but I am not getting how to utilize it. Guide me regarding the same.

**Comment by MAkerboom** [comment]
How is this crouton related?

**Comment by smibarber** [comment]
Dupe of #262.

**Comment by mohitkha** [comment]
I am developing an android application to get youtube history in android app.  how it possible
