### ISSUE TITLE
Cannot enter chroot anymore after beta channel update

### ISSUE THREAD

**Issue by thewes** [dnschneid/crouton#1594]
It goes like this:

sudo startunity

Entering /mnt/stateful_partition/crouton/chroots/unity...

X.Org X Server 1.14.6
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-37-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Feb 25 20:53:37 PST 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=ded7be36-296d-f64e-9d32-a2df35565d08/PARTNROFF=1 hashtree=PARTUUID=ded7be36-296d-f64e-9d32-a2df35565d08/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b899a45abe80a8499b88719cc15af525c904f751 salt=98803c68e2e05e875631b247eb1e2454b4954396437c69e53dc3b4b40b1025a4" noinitrd vt.global_cursor_default=0 kern_guid=ded7be36-296d-f64e-9d32-a2df35565d08 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  gpt 
Build Date: 01 May 2014  09:47:30PM
xorg-server 2:1.14.6-0ubuntu1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Wed Apr  8 21:24:47 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

My first thought is to try to update my crouton install. So I do an update, and it fails. Says the following every time:

The following NEW packages will be installed:
  libdrm-nouveau2 libegl1-mesa-lts-trusty libgbm1-lts-trusty libgl1-mesa-dri-lts-trusty libgl1-mesa-glx-lts-trusty libglamor-ltst0 libglapi-mesa-lts-trusty
  libllvm3.4 libwayland-ltst-client0 libwayland-ltst-server0 libxatracker2-lts-trusty libxcb-dri2-0 libxcb-util0 libxcb-xfixes0 libxvmc1
  xserver-common-lts-trusty xserver-xorg-core-lts-trusty xserver-xorg-input-evdev-lts-trusty xserver-xorg-lts-trusty xserver-xorg-video-all-lts-trusty
  xserver-xorg-video-ati-lts-trusty xserver-xorg-video-cirrus-lts-trusty xserver-xorg-video-fbdev-lts-trusty xserver-xorg-video-glamoregl-lts-trusty
  xserver-xorg-video-intel-lts-trusty xserver-xorg-video-mach64-lts-trusty xserver-xorg-video-mga-lts-trusty xserver-xorg-video-modesetting-lts-trusty
  xserver-xorg-video-neomagic-lts-trusty xserver-xorg-video-nouveau-lts-trusty xserver-xorg-video-openchrome-lts-trusty xserver-xorg-video-r128-lts-trusty
  xserver-xorg-video-radeon-lts-trusty xserver-xorg-video-s3-lts-trusty xserver-xorg-video-savage-lts-trusty xserver-xorg-video-siliconmotion-lts-trusty
  xserver-xorg-video-sis-lts-trusty xserver-xorg-video-sisusb-lts-trusty xserver-xorg-video-tdfx-lts-trusty xserver-xorg-video-trident-lts-trusty
  xserver-xorg-video-vesa-lts-trusty xserver-xorg-video-vmware-lts-trusty
The following held packages will be changed:
  xserver-xorg-video-dummy
0 upgraded, 42 newly installed, 13 to remove and 0 not upgraded.
Need to get 19.1 MB of archives.
After this operation, 55.3 MB of additional disk space will be used.
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Kind of at a loss for what to do. I think my install (precise unity) is severely outdated, but I am not sure how to "upgrade" it exactly. Thanks for any help

**Comment by thewes** [comment]
This is the other info:

E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
crouton: version 1-20150404180843~master:66d0393b
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi
host: version 6680.52.0 (Official Build) beta-channel link_freon 
kernel: Linux localhost 3.8.11 #1 SMP Wed Feb 25 20:53:37 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by Watney** [comment]
Please excuse the question, but did you update your chroot with ``sudo sh ~/Downloads/crouton -u -n chrootname`` per [the Wiki](https://github.com/dnschneid/crouton/wiki/Crouton-Command-Cheat-Sheet)?

**Comment by thewes** [comment]
Yes of course, this was the error that kept occurring after running the
command

**Comment by Lightsockie** [comment]
Also having this problem after updating from beta channel. Tried updating crouton, but the apt-get update part of the process crawls/times out. Likely a problem on my end, I'll try to resolve it and see if a crouton update fixes the issue

**Comment by MAkerboom** [comment]
can you `sudo enter-chroot` to load your chroot without a GUI. Then do a `sudo apt-get update && sudo apt-get upgrade` ?

**Comment by Lightsockie** [comment]
Oh, sorry should've said "updated Debian". Yeah I can enter-chroot and do all that. Everything seems to works fine, just can't seem to get X running. 

Here's my Xorg.0.log, with a similar error to OP
http://paste.debian.net/166122

**Comment by MAkerboom** [comment]
@lightsocky the OP has a diff problem after doing a crouton update ... Did you do the same?

**Comment by Lightsockie** [comment]
Oh, that's my bad. Sorry, I saw the title and saw we had similar errors with x. Assumed we had the same problems at the core, but I guess he's having an issue with updating. 

I'm having the error that caused him to try updating, and still having it after updating.

**Comment by ecollins** [comment]
@Lightsockie Just curious, did you ever find a solution to your particular problem? It sounds like I'm having the same issue.

**Comment by Lightsockie** [comment]
@ecollins Nope, but I haven't had the time to sit down and really address it either. I grabbed xiwi and can get most of what I need to run under chromos via it.

**Comment by drinkcat** [comment]
If you encounter the exact same error, you could try `apt-get remove xserver-xorg-video-dummy` in the chroot.

**Comment by dnschneid** [comment]
Please try with the latest crouton and re-open if you still have the same issue.
