### ISSUE TITLE
Can't Get To Trusty

### ISSUE THREAD

**Issue by kmages** [dnschneid/crouton#1595]
I successfully installed trusty (for the third time) as I am trying to maximize use of the tab functions (running Ubuntu in a tab) and I get this message:

Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo startunity
sudo: startunity: command not found
chronos@localhost / $

**Comment by kmages** [comment]
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Done! You can enter the chroot using enter-chroot.
chronos@localhost ~ $ sudo startunity
sudo: startunity: command not found

**Comment by kmages** [comment]
chronos@localhost ~ $ sudo sh -e ~/Downloads/crouton -t unity -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise does not exist; cannot update.
Valid chroots:
trusty

**Comment by kmages** [comment]
chronos@localhost / $ sudo sh ~/Downloads/crouton -t,unity -u -n trusty
Migrating data from legacy chroots directory /usr/local/chroots to /mnt/stateful_partition/crouton/chroots...
Not unmounting /usr/local/chroots/trusty as another instance is using it.
The above chroots appear to be running from the legacy chroots directory.
Log out of all running chroots and the install will automatically continue.
Press Ctrl-C at any time to abort the installation.

**Comment by mark-hahn** [comment]
FWIW, I would: Delete the chroot.  Reboot.  Do a new install.

**Comment by DennisLfromGA** [comment]
Also, don't use VT2, login to your Google account the normal way from the
login screen and then use Ctrl+Alt+t to get to cros, then enter shell per
normal, then start your chroot...

On Wed, Apr 8, 2015 at 10:47 PM, mark-hahn <notifications@github.com> wrote:

> FWIW, I would: Delete the chroot. Reboot. Do a new install.
>
> On Wed, Apr 8, 2015 at 7:44 PM, Kenneth Mages <notifications@github.com>
> wrote:
>
> > chronos@localhost / $ sudo sh ~/Downloads/crouton -t,unity -u -n trusty
> > Migrating data from legacy chroots directory /usr/local/chroots to
> > /mnt/stateful_partition/crouton/chroots...
> > Not unmounting /usr/local/chroots/trusty as another instance is using it.
> > The above chroots appear to be running from the legacy chroots directory.
> > Log out of all running chroots and the install will automatically
> continue.
> > Press Ctrl-C at any time to abort the installation.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dnschneid/crouton/issues/1595#issuecomment-91100138
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1595#issuecomment-91100331>.
>



-- 
*DennyL@GMail*
