### ISSUE TITLE
Clipboard problem in a xiwi browser tab

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1598]
I have a problem with the xiwi/extension clipboard integration when loaded in a browser tab, `sudo xiwi -T konqueror`.  It doesn't happen in a full screen, `sudo xiwi -F konqueror`.  

If I reboot and load an app in an xiwi tab, the first time I do a cut/copy in that app it goes in the clipboard properly. I can paste it in a  web page.  But then copy/paste doesn't work any more.  The clipboard doesn't change.  I have the problem in the other direction but I didn't test whether it works the first time or not.  I've verified the problem on my editor app, xterm, and konqueror. 

Any idea how I can chase this?

crouton: version 1-20150404180843~master:66d0393b
release: trusty
architecture: amd64
xmethod: xiwi
targets: unity,xiwi,keyboard
host: version 6680.78.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Fri Mar 20 15:41:09 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by dnschneid** [comment]
It's a known issue (that I forgot to document) that copy-paste between a xiwi tab and its url bar won't actively sync.  Are you switching tabs or windows and still not seeing the clipboard sync?

**Comment by mark-hahn** [comment]
> copy-paste between a xiwi tab and its url bar won't actively sync

If I understand what you are saying then I think I'm seeing the opposite.

After the first copy/paste that works, the following xiwi tab copies will
only paste correctly if I immediately paste in the url bar of the window
containing the xiwi tab.  Then the clipboard is correct and pastes that
value everywhere.

In other words, no matter how long it is broken, if I do a xiwi tab copy
and then paste in that window's url bar it is fixed and the clipboard is
correct.  If I paste anywhere else first then it doesn't work, even in that
window's url bar.

So I have a workaround.  I can paste into that bar after each copy.  Of
course the easier workaround is to not use the tab feature for now. (grin)

I'm sorry if this is confusing.  I can try saying it again in different
words if you wish.

**Comment by mark-hahn** [comment]
I've updated to latest version (don't know how to find version number) and now copy/paste doesn't work from either full screen or in a tab.  It works without any options.

**Comment by mark-hahn** [comment]
Now it seems to work everywhere.  Either the problem is intermittent or happens on the first testing.

**Comment by KFriedCode** [comment]
This seems to be an issue again. Several new chroot variations resulting in the same behavior. Clipboard functions when an app is opened units own xiwi window. Using xiwi -T <app> results in losing clipboard sync. Relevant targets installed: xiwi, cli-tools, extension, gnome/xfce/etc

**Comment by mark-hahn** [comment]
I get that problem often.  If you look at the chrome extension you will see
it trying over and over to connect.  I have to kill the chroot and re-enter
it.  My only target is xiwi.

**Comment by jpcookie** [comment]
I have the same issue happening 04242017. xiwi with xterm and trying to copy/paste into Chrome tab

**Comment by azet** [comment]
same problem with the signal-desktop app started with `sudo startxiwi -bfTn stretch signal-desktop` (`stretch` being the name of the debian stretch chroot, obviously).
