### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by chrisjamesberg** [dnschneid/crouton#1599]
I'm pretty new to crouton/chromebooks but...

My chromebook died while watching netflix tonight (I wasn't in crouton but had it running). Now when I "sudo startunity", it runs, but I just get a black screen.
Here's what happens when I start:

chronos@localhost / $ sudo startunity
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Mar 20 15:41:09 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cdff06a0-ad87-f246-8505-4b0b37336cdf/PARTNROFF=1 hashtree=PARTUUID=cdff06a0-ad87-f246-8505-4b0b37336cdf/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5d5557b5b04108e7ce8162c9f15eb3149ec4163a salt=a9343ded2666b5870d2398f860f7ef9c75986bb11576ba379b0941335289303f" noinitrd vt.global_cursor_default=0 kern_guid=cdff06a0-ad87-f246-8505-4b0b37336cdf add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Apr 10 00:40:44 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20150404180843~master:66d0393b
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,touch
host: version 6680.78.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Fri Mar 20 15:41:09 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.

**Comment by chrisjamesberg** [comment]
I should mention that I've done the common sense thing of updating crouton.

**Comment by MAkerboom** [comment]
Did you also update your chroot?

Run an update: `sudo sh ~/Downloads/crouton -n chrootname -u`, where `chrootname` is the name of your chroot.

**Comment by chrisjamesberg** [comment]
Yes I did.

**Comment by bvlaanderen** [comment]
Thanks MAkerboom, that worked for me!
