### ISSUE TITLE
how to use xiwi single-app mode without desktop?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1601]
*I posted this problem on the crouton google group a couple of days ago since it might be a problem of user error.  Until the group gets more active I think I need to ask about it here.*

The xiwi wiki page says "If you only intend to use the single-app mode, you can avoid installing a desktop environment entirely (-t xiwi)".  I have tried this and I cannot get past this error.

--- from google group post ---

 I pretty much put in everything I felt I wanted but left out any desktop.  

`sudo sh -e ~/Downloads/crouton -t cli-extra,core,extension,gtk-extra,keyboard,touch,x11,xiwi, -n min`

The first problem I had was that `sudo startcli` didn't work.  With a little googling I found that `sudo enter-chroot -n min` worked.

Then I tried `sudo xiwi -T xterm`.  It gave me a tab with the rust colored band at the top with a message saying I have an error in my i3 file.  I clicked on the "show error" button and saw the config errors. The first 4 errors each looked roughly like this ...

```
ERROR: CONFIG: syntax error, unexpected $undefined
ERROR: CONFIG: in file "/etc/crouton/xiwi.conf", line 13
ERROR: CONFIG:   client focused       #8E8E8F #EAEAEB #000000 #8E8E8F
                                                              ^
```

The last of the five looked like ...

```
ERROR: CONFIG:   syntax error, unexpected $undefined, expecting <number> or <word> or '+'
ERROR: CONFIG:   in file "/etc/crouton/xiwi.conf", line 27: 
ERROR: CONFIG:     bindsym --release button2 kill
                           ^
```

Can someone tell me the correct way to run xiwi with no desktop?  I don't care about the errors above as long as I can do it.  I also don't care if I have to delete the chroot and start over.

**Comment by dnschneid** [comment]
Once you're in the chroot, run xiwi *without* sudo.

`startcli` doesn't work with freon, and probably needs to be removed.

The errors you're seeing are #1576, but should be harmless.

So you seem to be doing the right thing; does it work?

**Comment by tedm** [comment]
xiwi -T xterm after sudo enter-chroot works fine on the ARM, but also get the brown/rust colored "You have an error in your i3 config file!"

and terminal output errors same as mark's output. - bindsym -- error

**Comment by mark-hahn** [comment]
Removing sudo fixed it.  Thanks.  I should have tried that.  I never know when to use sudo so I usually just try without and then with.
