### ISSUE TITLE
Chroots not found..

### ISSUE THREAD

**Issue by JanNegron** [dnschneid/crouton#1602]
Hi, when I try to update my chroot doesn't let me. I installed it in my SD card, and everything is fine. In my SD Card are three folders, and one of them is named "chroots", inside are the "trusty" folder, so yeah what to do now? :(

Here is the error that the shell tells me when I run this command, sudo sh ~/Downloads/crouton -n trusty -u...

/usr/local/chroots not found.
/usr/local/chroots/trusty does not exist; cannot update.
Valid chroots:

**Comment by DennisLfromGA** [comment]
`sudo sh ~/Downloads/crouton -p path/to/external/media/rootdirectory_of_chroots -n trusty -u`

**Comment by JanNegron** [comment]
the root directory is the folder "root" inside the folder of chroots?

**Comment by DennisLfromGA** [comment]
Nope.

The 'crouton' options note says this:
```
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local
```
Most likely, you've put your chroots in the parent directory of the SD Card so it would be something like this:

  `sudo sh ~/Downloads/crouton -p /media/removable/SD\ Card -n trusty -u`

**Comment by JanNegron** [comment]
Yayyyy! Thanks, men! I literally figure it out what to do for 3 hours and my only issue was that I don't put the prefix, lol!

**Comment by JanNegron** [comment]
ouh ouh... 

cd/media/removable/SD Card/bin: No such file or directory

:( an now what? never expected this...

**Comment by DennisLfromGA** [comment]
I've banged my head on that one too!

**Comment by Alfriadox** [comment]
Cool,
Can This issue be closed yet?
