### ISSUE TITLE
Gnome Doesn't Play Nice w/ setres (xrandr)

### ISSUE THREAD

**Issue by sprc** [dnschneid/crouton#1603]
Gnome doesn't want to play nice with the setres script when trying to switch to a custom resolution (such as 1280x850 on a Chromebook Pixel). Similar results when attempting to pick a custom resolution using xrandr --output eDP1 --mode <custom mode>. It flickers to the specified resolution but immediately switches back. You can then manually go select the resolution from the Display activity, but that's not ideal - I'm trying to script this for a remote desktop scenario.

Interestingly, after setting the custom mode of 1280x850, the same thing happens when trying to switch back to a standard resolution.

As a side note, xrandr --output eDP1 --auto --scale 0.5x0.5 works without needing to add a custom mode for 1280x850, but is tangibly fuzzier due to what I'm guessing is a software filter vs hardware filter.

**Comment by dnschneid** [comment]
What if you just do the --addmode part of the setres script, and then issue whatever gnome-settings command is necessary to switch the resolution "the gnome way"?

**Comment by sprc** [comment]
I haven't had any luck finding a command to switch the resolution "the gnome way", unfortunately.

**Comment by sprc** [comment]
Hmm So I've discovered that if you deactivate the xrandr gnome-settings-daemon plugin:

gsettings set org.gnome.settings-daemon.plugins.xrandr active false

...then do your xrandr command, the custom resolution sticks.

I'm guessing this has other ramifications but I don't know what they are. Also, using gsettings to reactivating the xrandr daemon plugin will instantly punt you back out of the custom resolution.

**Comment by dnschneid** [comment]
Well, that probably makes the GUI not work for changing display settings.  If you're happy with setres, then that's probably fine...

**Comment by sprc** [comment]
A Gnome dev mentioned taking a look at fixing this someday, and mentioned we could do a couple of things to work around it in the meantime without disabling the xrandr daemon plugin:

1) Explicitly tell mutter directly that we want a new configuration by using the org.gnome.Mutter.DisplayConfig D-Bus interface, via gdbus or dbus-send. This is theoretically the most 'correct' way to accomplish this, but it looks pretty complex and my google-fu tells me no one's actually managed to do this yet via shell script.

2) Modify ~/.config/monitors.xml to show our new resolution and then make the xrandr change.

This file is apparently Gnome's source-of-truth for monitor resolutions, so it's what gets loaded upon login and when things like monitor hot-plugging happens. If we trust users not to do anything too horrible with setres, we could just permanently modify the file. If we want setres changes to be temporary, we could modify the file, call xrandr, and revert the file from a backup a few seconds later so if anything goes horribly wrong, a logout/login would restore the old resolution. This is a double-edge sword though because plugging in an external monitor would also trigger a reversion.

I have a working prototype of option 2 that I could polish up a bit and submit a pull request for if you're interested.

**Comment by dnschneid** [comment]
I think people would find option 2 very useful, but that behavior should be behind a flag for setres.  Maybe `-w` to write the config to monitors.xml?

**Comment by sprc** [comment]
That sounds reasonable, but I think if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ]; then modify xml + xrandr + restore xml backup should be the default behavior without the -w flag; otherwise the script just won't work at all for Gnome unless users go out of their way to do something about it.

I guess we could just try to tell Gnome users when they run the script why it's not working and that they need to use the -w flag, but that's not going to win any UX awards... and we'd probably need to do it with a desktop notification via dbus in case people are relying on the script echoing an xrandr mode and nothing else.

**Comment by dnschneid** [comment]
That would make sense short-term.  Long-term it may make more sense if the script detects that the mode setting was immediately reverted, and then tries again with -w set.  I imagine Gnome isn't/won't be the only platform with that kind of behavior.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
