### ISSUE TITLE
Is "lxde-desktop" target broken?

### ISSUE THREAD

**Issue by haojiezhu** [dnschneid/crouton#1609]
Hi,

I failed to add "lxde-desktop" target to an existing chroot. Then I tried creating a new chroot with the following command using the latest crouton (version 1-20150404180843~master:66d0393b):

<i>sudo sh ~/Downloads/crouton -n lubuntu -r trusty -t lxde-desktop,chrome</i>

After a few minutes, installation failed with the same error message:

<i>Package 'network-manager' is not installed, so not removed
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lubuntu-desktop : Depends: network-manager-gnome but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.</i>

Did I missing anything or just run into a bug?

**Comment by tedm** [comment]
@haojiezhu if your existing target was lxde, just apt-get install the missing package that desktop would provide. I wouldn't run network manager in a chroot, since most of the functions won't work well with chrome which owns the network processes. What is it that you want to do in network manager that you can't configure in the Chromium OS host?

**Comment by haojiezhu** [comment]
@tedm I didn't try to install network manager. Crouton script did it automatically. I'll try to make a new chroot without "chrome" target and see if that helps.

**Comment by haojiezhu** [comment]
I tried installing "lxde-desktop" target only and still failed with the same "network-manager-gnome" error. It basically says "lxde-desktop" depends on "network-manager-gnome" package, which can't be installed for some reason.

**Comment by dnschneid** [comment]
See #1408. Fix is coming soon.

**Comment by tedm** [comment]
@haojiezhu what you may want to do until the #1408 fix arrives is to just install -t lxde and then apt-get the packages you need.

**Comment by DennisLfromGA** [comment]
Fix is in... Just update your chroot.

On Sat, Apr 11, 2015 at 8:09 PM, tedm <notifications@github.com> wrote:

> @haojiezhu <https://github.com/haojiezhu> what you may want to do until
> the #1408 <https://github.com/dnschneid/crouton/issues/1408> fix arrives
> is to just install -t lxde and then apt-get the packages you need.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1609#issuecomment-91949652>.
>



-- 
*DennyL@GMail*
