### ISSUE TITLE
SD Card Ext4..

### ISSUE THREAD

**Issue by JanNegron** [dnschneid/crouton#1610]
Someone knows how to delete files from an SD Card EXT4? Because I do the backup there, my fault obviously, and now I can't delete :(

**Comment by dnschneid** [comment]
You can do it from the crosh shell.  `sudo -i` to get a root shell, then `cd /media/removable/*`, `ls` to list files, and `rm` to delete them.

**Comment by JanNegron** [comment]
localhost SD Card # ls rm bin trusty-20150411-2256.tar.gz
ls: cannot access rm: No such file or directory
ls: cannot access trusty-20150411-2256.tar.gz: No such file or directory

what am doing wrong? the file is in the folder calls "bin"...

**Comment by mark-hahn** [comment]
ls (list) and rm (remove) are two different commands.  You should google
for linux command tutorials. There are a million of them on the web.
