### ISSUE TITLE
terminal gives never ending stream of error messages

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1611]
updated crouton, updated precise xfce chroot

then from crosh / shell:

sudo enter-chroot
xiwi -T startx

gives black screen, and terminal has stream of errors below.

from crosh / shell, sudo startxfce4 works properly.

(precise)ted@localhost:~$ c
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key..
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key..
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key..
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key..
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key..
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key.

**Comment by dnschneid** [comment]
Don't use startx...it's never worked reliably.  Use xinit instead.

**Comment by tedm** [comment]
Thanks xiwi -T xinit works well when in the chroot.
