### ISSUE TITLE
How to reset proxy when updating chroot?

### ISSUE THREAD

**Issue by BRFNGRNBWS** [dnschneid/crouton#1612]
I need to know how to disable the proxy when I update my chroot. I saw that under help, by -P it said to specify an empty string to reset, but I don't know what that means. When I run 
"sudo sh ~/Downloads/crouton -u -n precise -P"
, and leave -P blank, it says 
"no argument for target -P".
 So what do I put in front of it to reset the proxy? Thanks.

**Comment by JanNegron** [comment]
sudo sh ~/Downloads/crouton -p path/to/external/media/rootdirectory_of_chroots -n trusty -u

**Comment by DennisLfromGA** [comment]
Try using either two single-quote or two double-quotes with no space between them:
     `sudo sh ~/Downloads/crouton -u -n precise -P ''`

**Comment by DennisLfromGA** [comment]
@BRFNGRNBWS - Did that work?

**Comment by BRFNGRNBWS** [comment]
Yeah, it did, thanks!
