### ISSUE TITLE
Permission Denied on trying to use crouton chroot commands on first mount

### ISSUE THREAD

**Issue by tomwardill** [dnschneid/crouton#1613]
I have a newly created chroot on an ext4 formatted USB stick.

If I insert the USB stick and shell to the right directory:
```bash
chronos@localhost /media/removable/USB $ sudo ./bin/startxfce4 
Password: 
sudo: unable to execute ./bin/startxfce4: Permission denied
```

If I unmount the USB from it's auto mount and remount it manually, everything works:
```bash
chronos@localhost /media/removable/USB $ cd ..
chronos@localhost /media/removable $ sudo umount /media/removable/USB
chronos@localhost /media/removable $ sudo mount /dev/sda1 /media/removable/USB
chronos@localhost /media/removable $ cd USB
chronos@localhost /media/removable/USB $ sudo ./bin/startxfce4 
Entering /media/removable/USB/chroots/normal...
```

This is a new Dell Chromebook (2015), running latest stable.

**Comment by DennisLfromGA** [comment]
@tomwardill,

It sounds like it's getting mounted 'noexec' the first time and 'exec' the second time.
You can try this in the shell: `sudo mount    -o remount,exec /media/removable/USB`
but it's probably easier and quicker to unplug and plug it in again.

**Comment by divx118** [comment]
@DennisLfromGA  Default mount options of the file app are noexec. So reinserting has no effect.
@tomwardill Remounting is the best option I think. However you could try `sudo sh ./bin/startxfce4`

**Comment by dnschneid** [comment]
It's better to explicitly use sh (as @divx118 suggested) than to remount the external disk exec.
