### ISSUE TITLE
Blank screen when switching back to Chrome OS from Trusty

### ISSUE THREAD

**Issue by chrisjamesberg** [dnschneid/crouton#1614]
I was able to log what was happening after I start xfce. When I go back into chrome OS, it's a black screen but the buttons still work so it's clearly running (I can raise or lower my volume on the black screen).

I can easily switch back into xfce and I can also restart the machine to get back to chrome OS, but I effectively can't switch screens without restarting.

chronos@localhost / $ sudo startxfce4
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Mar 20 15:41:09 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cdff06a0-ad87-f246-8505-4b0b37336cdf/PARTNROFF=1 hashtree=PARTUUID=cdff06a0-ad87-f246-8505-4b0b37336cdf/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5d5557b5b04108e7ce8162c9f15eb3149ec4163a salt=a9343ded2666b5870d2398f860f7ef9c75986bb11576ba379b0941335289303f" noinitrd vt.global_cursor_default=0 kern_guid=cdff06a0-ad87-f246-8505-4b0b37336cdf add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Apr 12 23:04:46 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20150411190710~master:7adac7a1
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6680.78.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Fri Mar 20 15:41:09 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:16033): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:16033): polkit-gnome-1-WARNING **: Failed to register client:

**Comment by MAkerboom** [comment]
I think I got the same issue with utopic (trusty works fine), see: https://github.com/dnschneid/crouton/issues/1519

**Comment by chrisjamesberg** [comment]
I should mention, I was having problems with a video game crashing in Trusty (Civilization 5). After a lot of searching for fixes, I was able to solve it by doing this:
# add-apt-repository ppa:ubuntu-x-swat/x-updates
# add-apt-repository ppa:oibaf/graphics-drivers
# apt-get update && apt-get dist-upgrade

After this, Civilization 5 worked well, but then the next time I switched over to Chrome OS, it was just a black screen.

**Comment by haojiezhu** [comment]
Does the fan on your machine run crazy when you play games? If it does, it's probably related to overheating and something at the backend crashes. I had used the exact same PPA to test some games like Half-Life 2 and Hotline Miami and the frame-rate was decent with less jitters than drivers from other PPAs . After about 10 minutes, fan starts spinning like helicopter. If I continue playing, system becomes unstable after another 5-10 minutes. One time I also got the black screen when switching back to ChromeOS. Another time system just froze and rebooted.

Playing WebGL-based game in ChomeOS like "Save the Day" also causes fan to spin really fast, but no reboot so far. In my case, I think ASUS Chromebox's cooling is just not good enough for such graphics-intensive job, or maybe ChromeOS is really sensitive to overheating. Just my guess.

**Comment by valkenburgh** [comment]
@chrisjamesberg I have also had the same problem. Running Trusty with Gnome, CIV5 would crash. I updated intel video drivers and civ5 worked but switching back to chromeos resulted in black screen. @haojiezhu I don't believe it has to do with overheating. I've updated the video drivers on many chroots with pixel 2, sometimes playing civ 5 and sometimes never installing steam in the first place — always screen goes black. This is a bug in chromeos. If you bring your linux chroot's video driver up to date, chromeos display fails (goes black).  dnschneid is aware of bug and it is being addressed: https://github.com/dnschneid/crouton/issues/1519

**Comment by VhatAmI** [comment]
Same issue, also get blank screen after logging off of trusty. 
No games or high intensive apps ran in my trusty session, tried logging in and immediately swapping back to chromeos, and it is a blank screen. 

Only way to fix blank screen for me so far is to hard reset the device.

**Comment by tomulet** [comment]
Make sure Chrome OS is in Stable channel.

**Comment by Windexi** [comment]
Did you install  drivers to make Civ 5 not crash on startup? I too had the same problem with the crashing, and it seems that a side affect of installing the drivers breaks switching back to chrome os.

Instead, uninstall these
