### ISSUE TITLE
Insert crouton icon in start menu

### ISSUE THREAD

**Issue by aleroot** [dnschneid/crouton#1615]
I would want to have a new feature to the crouton script that if the user want will add an icon in the start menu (as if it was an application), that will launch the command to start the Linux in the chroot.

For example an icon named : wheezy-xfce4 
will launch the command : sudo startxfce4

Is it possible to implement, I think it will be useful shortcut to avoid going to the Terminal tab .

**Comment by smibarber** [comment]
See previous discussion at #1468. Still not possible to do this AFAIK.
