### ISSUE TITLE
Issues with mouse movement with Synergy on XFCE

### ISSUE THREAD

**Issue by r3ll1sh** [dnschneid/crouton#1618]
Sorry if this is in the wrong place.

I crouton'd my Samsung chromebook to install [synergy](http://synergy-project.org/), which shares my keyboard and mouse from my windows machine to my chromebook. I can share the keyboard fine but the mouse is having issues. The chromebook is registering that the (windows) mouse is moving, because it shows hover animations on the icons, but the cursor itself isn't moving. I think it has something to do with the way the mouse is configured. XFCE says it's using "Xephyr Virtual Mouse". I've tried restarting and reconfiguring synergy, but it hasn't helped. Any help would be appreciated.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
