### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by Scp-049** [dnschneid/crouton#1620]
I have been getting this error repeatedly when I try  install. It causes the installation tl stop and cancel out. 

zip:unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to complete chroot setup
Unmounting /usr/local/chroots/precise

**Comment by DimitriDokuchaev** [comment]
well the file that is being downloaded is corrupted (most likely not complete), more info would be needed to figure out which file.

**Comment by drinkcat** [comment]
zip? I can't think where crouton would try to extract a zip file...
