### ISSUE TITLE
Kali fails to build chroot - libxreder1 404 not found

### ISSUE THREAD

**Issue by aa0na** [dnschneid/crouton#1622]
this is the command i used to build the chroot
sudo sh crouton -r kali -t xiwi

Get:44 http://http.kali.org/ kali/main x11-utils amd64 7.7~1 [233 kB]                                                                      
Get:45 http://http.kali.org/ kali/main xclip amd64 0.12+svn84-2 [22.6 kB]                                                                  
Fetched 29.0 MB in 22s (1281 kB/s)                                                                                                         
Failed to fetch http://security.kali.org/kali-security/pool/main/libx/libxrender/libxrender1_0.9.7-1+deb7u1+b1_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali...

**Comment by dnschneid** [comment]
Possible a transient error.  Try again?

**Comment by aa0na** [comment]
rebuild worked.  thanks
