### ISSUE TITLE
Having a weird bug starting Ubutnu from my Chromebook. May be error with Crouton Update.

### ISSUE THREAD

**Issue by nateers** [dnschneid/crouton#1623]
I casually switched from ubutnu using Alt+Ctrl+Back Arrow and when I later tried to login I was met with some scary code (as I am not familiar with code). I have been troubleshooting for a while and im still stuck. This is what I do when I try to get back into ubutnu.

chronos@localhost / $ sudo startunity
Entering /usr/local/chroots/precise...

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri Mar 20 15:40:08 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=68f3be2f-dfcc-654c-b34d-c08c3f69ec07/PARTNROFF=1 hashtree=PARTUUID=68f3be2f-dfcc-654c-b34d-c08c3f69ec07/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b54ceb1092dc8e50b51915d5558e05f17ed5ab6f salt=0aad4d303c357509674753fb8541a709c812485ac286beed56a785ad7ba7c3b1" noinitrd vt.global_cursor_default=0 kern_guid=68f3be2f-dfcc-654c-b34d-c08c3f69ec07 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Tue Apr 14 21:07:49 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Not unmounting /usr/local/chroots/precise as another instance is using 

------------------------------------------------------------------------------------------------
Bam. Thats it. I am using an acer C720 if its any help. I am thoroughly confused and need help ASAP. Thank you :) I think it may be something with my crouton being out of date but im also getting weird errors when I attempt to update it.

**Comment by EsSai2** [comment]
Where you ever able to find what the issue was and fix it as I am having the exact same issue on my acer C720 and elementary OS.

Thanks.

**Comment by divx118** [comment]
@nateers If you would mention the errors you are getting when trying to update, it may be possible to help. However without I need to polish my crystal ball.
@EsSai2 Try updating your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by EsSai2** [comment]
@divx118 When I tried updating my chroot it said, sh: Can't open /home/chronos/user/Downloads/crouton.  Today is the first day I have encountered this problem.

**Comment by EsSai2** [comment]
chronos@localhost / $ sudo startelementary
Entering /mnt/stateful_partition/crouton/chroots/elementary...
/usr/bin/startelementary: Starting X server


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Apr 14 18:57:27 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=70e368e4-9955-9641-b0ed-a873194d0510/PARTNROFF=1 hashtree=PARTUUID=70e368e4-9955-9641-b0ed-a873194d0510/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=a066bff2dc004585fe2b5c44be0c33ce6314a3a4 salt=d9d62c9699d89416b72843e002fe7a0e273b0d9678a826be2a1517e0e06658ae" noinitrd vt.global_cursor_default=0 kern_guid=70e368e4-9955-9641-b0ed-a873194d0510 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Apr 18 15:38:46 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/elementary as another instance is using it.
chronos@localhost / $ sudo sh ~/Downloads/crouton -n elementary -u
sh: Can't open /home/chronos/user/Downloads/crouton

Above is everything that happens when I try to start elementary or update my chroot.  Any help would be appreciated.

**Comment by divx118** [comment]
@EsSai2 Be sure you have downloaded the crouton script from https://github.com/dnschneid/crouton the [goo.gl](https://goo.gl/fd3zc) link and it is in your download directory. Also before updating, reboot your chromebook so no chroot is running, just to be sure.

**Comment by EsSai2** [comment]
@divx118 I did as you suggested and I still get the same error, where it says "sh: Can't open /home/chronos/user/Downloads/crouton."

**Comment by divx118** [comment]
Can you post the output of `ls -al /home/chronos/user/Downloads/crouton`?

**Comment by EsSai2** [comment]
chronos@localhost / $ 1s -al /home/chronos/user/Downloads/crouton
bash: 1s: command not found

I am not sure I did this right, still learning this stuff.

**Comment by divx118** [comment]
@EsSai2 No problem, l not 1. so small letter L. `ls -al /home/chronos/user/Downloads/crouton`

**Comment by EsSai2** [comment]
chronos@localhost / $ ls -al /home/chronos/user/Downloads/crouton
ls: cannot access /home/chronos/user/Downloads/crouton: No such file or directory

**Comment by divx118** [comment]
@EsSai2 As I said in my first post download crouton  from https://goo.gl/fd3zc There is no crouton script in your directory downloads right now, so it cannot find the command when you try to update your chroot.

**Comment by EsSai2** [comment]
Sorry about that I had a Downloads folder under the primary Downloads folder and that was where crouton was located but changed it.  However, I still can't access Elementary OS when I type "sudo startelementary."  Get this info.

chronos@localhost / $ sudo sh ~/Downloads/crouton -n elementary -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/elementary already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Unknown username "dnsmasq" in message bus configuration file
Installing target core...
Preparing environment...
Preparing software sources...
Hit http://archive.ubuntu.com precise Release.gpg
Hit http://archive.ubuntu.com precise-updates Release.gpg                                                                         
Hit http://archive.ubuntu.com precise-security Release.gpg                                                                        
Hit http://repo.steampowered.com precise Release.gpg                                                                              
Hit http://archive.ubuntu.com precise Release                                                               
Hit http://archive.ubuntu.com precise-updates Release                     
Hit http://repo.steampowered.com precise Release                          
Hit http://archive.ubuntu.com precise-security Release                                           
Hit http://archive.ubuntu.com precise/main Sources                                          
Hit http://archive.ubuntu.com precise/restricted Sources             
Hit http://archive.ubuntu.com precise/universe Sources               
Hit http://archive.ubuntu.com precise/multiverse Sources             
Hit http://archive.ubuntu.com precise/main amd64 Packages            
Hit http://archive.ubuntu.com precise/restricted amd64 Packages      
Hit http://archive.ubuntu.com precise/universe amd64 Packages        
Hit http://archive.ubuntu.com precise/multiverse amd64 Packages      
Hit http://archive.ubuntu.com precise/main i386 Packages             
Hit http://archive.ubuntu.com precise/restricted i386 Packages       
Hit http://archive.ubuntu.com precise/universe i386 Packages                           
Hit http://archive.ubuntu.com precise/multiverse i386 Packages                         
Hit http://archive.ubuntu.com precise/main TranslationIndex                            
Hit http://archive.ubuntu.com precise/multiverse TranslationIndex                      
Hit http://archive.ubuntu.com precise/restricted TranslationIndex                      
Hit http://archive.ubuntu.com precise/universe TranslationIndex                        
Hit http://archive.ubuntu.com precise-updates/main Sources                             
Hit http://archive.ubuntu.com precise-updates/restricted Sources                       
Hit http://archive.ubuntu.com precise-updates/universe Sources                         
Hit http://archive.ubuntu.com precise-updates/multiverse Sources                       
Hit http://ppa.launchpad.net precise Release.gpg                                       
Ign http://ppa.launchpad.net precise Release.gpg                                       
Hit http://ppa.launchpad.net precise Release.gpg                                       
Hit http://ppa.launchpad.net precise Release.gpg                                       
Hit http://archive.ubuntu.com precise-updates/main amd64 Packages                      
Hit http://archive.ubuntu.com precise-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com precise-updates/universe amd64 Packages
Hit http://archive.ubuntu.com precise-updates/multiverse amd64 Packages
Hit http://archive.ubuntu.com precise-updates/main i386 Packages 
Hit http://archive.ubuntu.com precise-updates/restricted i386 Packages                 
Hit http://archive.ubuntu.com precise-updates/universe i386 Packages                   
Hit http://archive.ubuntu.com precise-updates/multiverse i386 Packages                 
Hit http://archive.ubuntu.com precise-updates/main TranslationIndex                    
Hit http://archive.ubuntu.com precise-updates/multiverse TranslationIndex              
Hit http://archive.ubuntu.com precise-updates/restricted TranslationIndex              
Hit http://archive.ubuntu.com precise-updates/universe TranslationIndex                
Hit http://archive.ubuntu.com precise-security/main Sources                            
Hit http://archive.ubuntu.com precise-security/restricted Sources                      
Hit http://archive.ubuntu.com precise-security/universe Sources                        
Hit http://archive.ubuntu.com precise-security/multiverse Sources                      
Hit http://archive.ubuntu.com precise-security/main amd64 Packages                     
Hit http://archive.ubuntu.com precise-security/restricted amd64 Packages               
Hit http://archive.ubuntu.com precise-security/universe amd64 Packages                 
Hit http://archive.ubuntu.com precise-security/multiverse amd64 Packages               
Hit http://ppa.launchpad.net precise Release                                            
Ign http://ppa.launchpad.net precise Release                                                                   
Hit http://ppa.launchpad.net precise Release                                                                   
Hit http://archive.ubuntu.com precise-security/main i386 Packages                                              
Hit http://archive.ubuntu.com precise-security/restricted i386 Packages                                        
Hit http://archive.ubuntu.com precise-security/universe i386 Packages                                          
Hit http://archive.ubuntu.com precise-security/multiverse i386 Packages                                        
Hit http://archive.ubuntu.com precise-security/main TranslationIndex                                           
Hit http://archive.ubuntu.com precise-security/multiverse TranslationIndex                                     
Hit http://archive.ubuntu.com precise-security/restricted TranslationIndex              
Hit http://archive.ubuntu.com precise-security/universe TranslationIndex                
Hit http://archive.ubuntu.com precise/main Translation-en                               
Hit http://archive.ubuntu.com precise/multiverse Translation-en                         
Hit http://archive.ubuntu.com precise/restricted Translation-en                         
Hit http://archive.ubuntu.com precise/universe Translation-en                           
Hit http://archive.ubuntu.com precise-updates/main Translation-en                       
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en                 
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en                 
Hit http://archive.ubuntu.com precise-updates/universe Translation-en                   
Hit http://archive.ubuntu.com precise-security/main Translation-en                      
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en                
Hit http://archive.ubuntu.com precise-security/restricted Translation-en                
Hit http://archive.ubuntu.com precise-security/universe Translation-en                  
Hit http://repo.steampowered.com precise/steam Sources                                  
Hit http://ppa.launchpad.net precise Release                      
Ign http://ppa.launchpad.net precise/main TranslationIndex                                                                 
Hit http://ppa.launchpad.net precise/main Sources                 
Hit http://ppa.launchpad.net precise/main amd64 Packages          
Hit http://ppa.launchpad.net precise/main i386 Packages           
Hit http://ppa.launchpad.net precise/main TranslationIndex        
Hit http://ppa.launchpad.net precise/main Sources                 
Hit http://ppa.launchpad.net precise/main amd64 Packages          
Hit http://ppa.launchpad.net precise/main i386 Packages           
Hit http://ppa.launchpad.net precise/main TranslationIndex        
Hit http://ppa.launchpad.net precise/main Sources                 
Hit http://ppa.launchpad.net precise/main amd64 Packages          
Hit http://ppa.launchpad.net precise/main i386 Packages           
Hit http://repo.steampowered.com precise/steam amd64 Packages     
Ign http://ppa.launchpad.net precise/main TranslationIndex                                          
Hit http://repo.steampowered.com precise/steam i386 Packages                                        
Hit http://ppa.launchpad.net precise/main Translation-en                                            
Hit http://ppa.launchpad.net precise/main Translation-en                                            
Ign http://repo.steampowered.com precise/steam TranslationIndex                                     
Err http://ppa.launchpad.net precise/main Sources                                                   
  404  Not Found
Err http://ppa.launchpad.net precise/main amd64 Packages           
  404  Not Found
Err http://ppa.launchpad.net precise/main i386 Packages            
  404  Not Found
Ign http://ppa.launchpad.net precise/main Translation-en           
Ign http://ppa.launchpad.net precise/main Translation-en           
Ign http://repo.steampowered.com precise/steam Translation-en
W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/elementary...
chronos@localhost / $ sudo startelementary
Entering /mnt/stateful_partition/crouton/chroots/elementary...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] Y
Preparing chroot environment...
Unknown username "dnsmasq" in message bus configuration file
Installing target core...
Preparing environment...
Preparing software sources...
Hit http://archive.ubuntu.com precise Release.gpg
Hit http://archive.ubuntu.com precise-updates Release.gpg                                       
Hit http://archive.ubuntu.com precise-security Release.gpg                                      
Hit http://archive.ubuntu.com precise Release                             
Hit http://archive.ubuntu.com precise-updates Release                                           
Hit http://archive.ubuntu.com precise-security Release                                          
Hit http://archive.ubuntu.com precise/main Sources                                          
Hit http://archive.ubuntu.com precise/restricted Sources             
Hit http://archive.ubuntu.com precise/universe Sources               
Hit http://archive.ubuntu.com precise/multiverse Sources             
Hit http://archive.ubuntu.com precise/main amd64 Packages            
Hit http://archive.ubuntu.com precise/restricted amd64 Packages      
Hit http://archive.ubuntu.com precise/universe amd64 Packages        
Hit http://archive.ubuntu.com precise/multiverse amd64 Packages      
Hit http://archive.ubuntu.com precise/main i386 Packages             
Hit http://archive.ubuntu.com precise/restricted i386 Packages       
Hit http://archive.ubuntu.com precise/universe i386 Packages         
Hit http://archive.ubuntu.com precise/multiverse i386 Packages   
Hit http://archive.ubuntu.com precise/main TranslationIndex      
Hit http://archive.ubuntu.com precise/multiverse TranslationIndex
Hit http://ppa.launchpad.net precise Release.gpg                 
Ign http://ppa.launchpad.net precise Release.gpg                 
Hit http://ppa.launchpad.net precise Release.gpg                 
Hit http://ppa.launchpad.net precise Release.gpg                 
Hit http://archive.ubuntu.com precise/restricted TranslationIndex
Hit http://archive.ubuntu.com precise/universe TranslationIndex                        
Hit http://archive.ubuntu.com precise-updates/main Sources                             
Hit http://archive.ubuntu.com precise-updates/restricted Sources                       
Hit http://archive.ubuntu.com precise-updates/universe Sources                         
Hit http://archive.ubuntu.com precise-updates/multiverse Sources                       
Hit http://archive.ubuntu.com precise-updates/main amd64 Packages                      
Hit http://archive.ubuntu.com precise-updates/restricted amd64 Packages                
Hit http://archive.ubuntu.com precise-updates/universe amd64 Packages                  
Hit http://archive.ubuntu.com precise-updates/multiverse amd64 Packages                
Hit http://archive.ubuntu.com precise-updates/main i386 Packages                       
Hit http://archive.ubuntu.com precise-updates/restricted i386 Packages                 
Hit http://archive.ubuntu.com precise-updates/universe i386 Packages                   
Hit http://archive.ubuntu.com precise-updates/multiverse i386 Packages                 
Hit http://archive.ubuntu.com precise-updates/main TranslationIndex                    
Hit http://archive.ubuntu.com precise-updates/multiverse TranslationIndex              
Hit http://repo.steampowered.com precise Release.gpg                                   
Hit http://archive.ubuntu.com precise-updates/restricted TranslationIndex              
Hit http://archive.ubuntu.com precise-updates/universe TranslationIndex                
Hit http://archive.ubuntu.com precise-security/main Sources                            
Hit http://archive.ubuntu.com precise-security/restricted Sources                      
Hit http://archive.ubuntu.com precise-security/universe Sources                        
Hit http://ppa.launchpad.net precise Release                                           
Ign http://ppa.launchpad.net precise Release                                           
Hit http://ppa.launchpad.net precise Release                     
Hit http://archive.ubuntu.com precise-security/multiverse Sources                                             
Hit http://archive.ubuntu.com precise-security/main amd64 Packages                     
Hit http://archive.ubuntu.com precise-security/restricted amd64 Packages               
Hit http://archive.ubuntu.com precise-security/universe amd64 Packages                 
Hit http://archive.ubuntu.com precise-security/multiverse amd64 Packages               
Hit http://archive.ubuntu.com precise-security/main i386 Packages                       
Hit http://archive.ubuntu.com precise-security/restricted i386 Packages                 
Hit http://archive.ubuntu.com precise-security/universe i386 Packages                   
Hit http://archive.ubuntu.com precise-security/multiverse i386 Packages                 
Hit http://archive.ubuntu.com precise-security/main TranslationIndex                    
Hit http://repo.steampowered.com precise Release                                        
Hit http://archive.ubuntu.com precise-security/multiverse TranslationIndex              
Hit http://archive.ubuntu.com precise-security/restricted TranslationIndex              
Hit http://archive.ubuntu.com precise-security/universe TranslationIndex                
Hit http://archive.ubuntu.com precise/main Translation-en                               
Hit http://archive.ubuntu.com precise/multiverse Translation-en                         
Hit http://archive.ubuntu.com precise/restricted Translation-en                         
Hit http://archive.ubuntu.com precise/universe Translation-en                           
Hit http://archive.ubuntu.com precise-updates/main Translation-en                       
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en                 
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en                 
Hit http://ppa.launchpad.net precise Release                                            
Ign http://ppa.launchpad.net precise/main TranslationIndex                                                     
Hit http://archive.ubuntu.com precise-updates/universe Translation-en                                          
Hit http://archive.ubuntu.com precise-security/main Translation-en                      
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en                
Hit http://archive.ubuntu.com precise-security/restricted Translation-en
Hit http://archive.ubuntu.com precise-security/universe Translation-en                  
Hit http://ppa.launchpad.net precise/main Sources                                       
Hit http://ppa.launchpad.net precise/main amd64 Packages          
Hit http://ppa.launchpad.net precise/main i386 Packages           
Hit http://ppa.launchpad.net precise/main TranslationIndex        
Hit http://ppa.launchpad.net precise/main Sources                 
Hit http://ppa.launchpad.net precise/main amd64 Packages          
Hit http://ppa.launchpad.net precise/main i386 Packages           
Hit http://ppa.launchpad.net precise/main TranslationIndex        
Hit http://ppa.launchpad.net precise/main Sources                 
Hit http://ppa.launchpad.net precise/main amd64 Packages          
Hit http://ppa.launchpad.net precise/main i386 Packages           
Hit http://repo.steampowered.com precise/steam Sources            
Ign http://ppa.launchpad.net precise/main TranslationIndex        
Hit http://ppa.launchpad.net precise/main Translation-en                                            
Hit http://ppa.launchpad.net precise/main Translation-en                                            
Hit http://repo.steampowered.com precise/steam amd64 Packages                 
Hit http://repo.steampowered.com precise/steam i386 Packages                                        
Err http://ppa.launchpad.net precise/main Sources                                                    
  404  Not Found
Err http://ppa.launchpad.net precise/main amd64 Packages                                             
  404  Not Found
Ign http://repo.steampowered.com precise/steam TranslationIndex                                      
Err http://ppa.launchpad.net precise/main i386 Packages            
  404  Not Found
Ign http://ppa.launchpad.net precise/main Translation-en           
Ign http://ppa.launchpad.net precise/main Translation-en           
Ign http://repo.steampowered.com precise/steam Translation-en      
W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
/usr/bin/startelementary: Starting X server


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Apr 14 18:57:27 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=70e368e4-9955-9641-b0ed-a873194d0510/PARTNROFF=1 hashtree=PARTUUID=70e368e4-9955-9641-b0ed-a873194d0510/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=a066bff2dc004585fe2b5c44be0c33ce6314a3a4 salt=d9d62c9699d89416b72843e002fe7a0e273b0d9678a826be2a1517e0e06658ae" noinitrd vt.global_cursor_default=0 kern_guid=70e368e4-9955-9641-b0ed-a873194d0510 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Sat Apr 18 16:39:19 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory

**Comment by divx118** [comment]
@EsSai2 You have a broken ppa in your sources in the chroot, remove that and you can update.

```
W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/source/Sources 404 Not Found

W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/binary-amd64/Packages 404 Not Found

W: Failed to fetch http://ppa.launchpad.net/ubunta-x-swat/x-updates/ubuntu/dists/precise/main/binary-i386/Packages 404 Not Found
```
You can do the following:

```
$ sudo enter-chroot -n elementary
```
then
```
$ cd /etc/apt
$ grep -r "http://ppa.launchpad.net/ubunta-x-swat" *
```
Now you see the file listed which contains that ppa. You can use `vi` to edit it. Some info on howto use vi is for example here http://www.cs.colostate.edu/helpdocs/vi.html
```
$ sudo vi <your filename path>
```
Remove the lines that contains `http://ppa.launchpad.net/ubunta-x-swat....` save the file and type `exit` to exit the chroot. Now try to update the chroot again.

**Comment by EsSai2** [comment]
@divx118 I just have one ?, I am not sure what you are referring to when you say "your filename path."  Can you please clarify this for a noob?  Otherwise been able to follow everything.

THanks.

**Comment by divx118** [comment]
When you run `grep -r "http://ppa.launchpad.net/ubunta-x-swat" *` it should present you with the filename paths where that line is present. That will be `<your filename path>`. BTW I think there are a few other ppa's broken, but first try removing this and update again. If the update still errors out try to do the same for the other ppa's that are failing.

**Comment by EsSai2** [comment]
It worked!!!  Thanks for all your help.

**Comment by divx118** [comment]
Nice, if @nateers can confirm he has a similar issue, this can be closed then.

**Comment by dnschneid** [comment]
@nateers, please update your chroot and re-open the bug if you still have issues.
