### ISSUE TITLE
Managing and using Desktop/GUI sessions with lightdm etc

### ISSUE THREAD

**Issue by Ali3n0id** [dnschneid/crouton#1625]
I really want to try a few desktop environments or window managers out often depending on my needs, for example - most of the time I will use the 'lubuntu-desktop' (not plain LXDE), openbox with extras as well as xmonad.

It'd be really handy if I could logout of a session using lightdm (or slim, gdm - currently if I log out of a session in LXDE it will exit Xorg/X11) and then change session to something else...

I haven't been able to figure out how to boot into the full lubuntu-desktop mode, openbox etc. and I've have played around with .Xsession and .xinitrc files but encountered errors.

How can this be done using crouton?

Many thanks in advance.

**Comment by DennisLfromGA** [comment]
> It'd be really handy if I could logout of a session using lightdm (or slim, gdm - currently if I log out of a session in LXDE it will exit Xorg/X11) and then change session to something else...

The session/window managers are *pretty tricky* in crouton. I've tried some myself once upon a time but gave up 'cause they *break* things. See these issues for more details - https://github.com/dnschneid/crouton/issues/1113#issuecomment-58712421 and https://github.com/dnschneid/crouton/issues/61#issuecomment-15979869.

Also, you can add any number of targets/DEs to a chroot and run them separately by specifying a different 'start*' script. For example, if you've installed targets 'lxde-desktop,gnome-desktop,unity-desktop' in a chroot named trusty, just run/start them like:

`sudo startlxde -n trusty` and/or `sudo startgnome -n trusty` and/or `sudo startunity -n trusty`

> I haven't been able to figure out how to boot into the full lubuntu-desktop mode, openbox etc. and I've have played around with .Xsession and .xinitrc files but encountered errors.

If you have the 'lxde-desktop' target installed, you start it the same way you would the plain vanilla 'lxde' desktop, with `sudo startlxde ...`. It will open in the full DE with all your installed bells & whistles.
