### ISSUE TITLE
PYWINRM : winrm.exceptions.WinRMTransportError: 500 WinRMTransport. [Errno 111] Connection refused

### ISSUE THREAD

**Issue by bhupal1reddy** [dnschneid/crouton#1626]
Hello,

Could anyone please help me with this error message?

I get the following error when I am using pywinrm to get info from a Windows host.

I am running the below script in RHEL 6 with Python 2.6.6 on it.

>>> import winrm
>>> s = winrm.Session('windowshost', auth=('username', 'password'))
>>> r = s.run_cmd('ipconfig', ['/all'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "winrm/__init__.py", line 28, in run_cmd
    shell_id = self.protocol.open_shell()
  File "winrm/protocol.py", line 103, in open_shell
    rs = self.send_message(xmltodict.unparse(rq))
  File "winrm/protocol.py", line 173, in send_message
    return self.transport.send_message(message)
  File "winrm/transport.py", line 103, in send_message
    raise WinRMTransportError('http', ex.reason)
winrm.exceptions.WinRMTransportError: 500 WinRMTransport. [Errno 111] Connection refused
>>>

**Comment by smibarber** [comment]
#262 might help

**Comment by bhupal1reddy** [comment]
I dont see answer to the issue I posted in the reference link you posted.
