### ISSUE TITLE
crouton install, quits right after "Extracting adduser..."

### ISSUE THREAD

**Issue by faddah** [dnschneid/crouton#1628]
hi all,

i broke my other USB stick i had my ubuntu install with crouton on it, so i bought a pny usb 3.0 32 GB stick and am trying to reinstall crouton ubuntu to it.

here is the command line i use with crouton for the install — 

```
sudo sh -e ~/Downloads/crouton -r trusty -t core,cli-extra,x11,gtk-extra,extension,keyboard,touch,unity,chrome,chromium -p /media/removable/USB30FD/
```

i've made sure the usb 3.0 stick is formatted with ext4 and checked it with ```sudo fsck.ext4 -f /dev/sdd``` etc.

i have tried this several times, and each time, it goes through all the retrieving and extracting all the files for ubuntu, the does, finally...

```
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting adduser...
```

and it stops there.

i've re-run this, several times, and it stops on ```I: Extracting adduser...```, every time.

i've re-downloaded the latest crouton installer from this github repository, tried again, same issue.

any help here? can't figure out what is halting this and not letting the crouton install all the way through. thanks in advance.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by dnschneid** [comment]
Do you have free space on your external disk?

**Comment by faddah** [comment]
@dnschneid,

thanks for responding back.

yes, plenty. as i said, it's a totally empty, formatted with ext4 32 GB USB 3.0 thumb drive. any other suggestions here?

best,

—  faddah
      portland, oregon

**Comment by DennisLfromGA** [comment]
@faddah - 
If you have room on your Chromebook, try installing it there first, get it all setup and updated, then back it up and restore it to your new usb stick. 
I've been using this method successfully for a while now, it seems to work best for me.

**Comment by faddah** [comment]
@dnschneid & @DennisLfromGA ,

thank you again for responding.

i understand just about all of that, except for the part about backing it up and restoring to the stick. how do i go about doing that. i ask because i have only ever installed to an external usb stick drive, not on the chromebook drive. does it install as just a folder on my chromebook and i can copy it over from there? if not, then how do i do it? i especially want to know this because, once copied to the usb stick drive and verifying it runs correctly, i want to wipe off my hard drive for space considerations. pardon the newbie question, but i've only ever done the back up of general system to an SD card in case of failure, not back up entire sections to another external usb stick.

please let me know, and thank you again.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by DennisLfromGA** [comment]
@faddah,

Once your chroot is installed on the internal SSD and your satisfied with it, exit the chroot to a cros shell.

To back it up, do:

  `sudo edit-chroot -b trusty`

It'll be saved in your ~/Downloads directory with a filename like `trusty-2015.....tar.gz`.

To restore it to your usb stick (formatted as ext2/3/4), do: 
 
 `sudo sh ~/Downloads/crouton -f ~/Downloads/trusty-2015*.tar.gz -p /media/removable/USB30FD/`

That should uncompress and untar your chroot on the external drive.

Then, you can run it by:

```
cd  /media/removable/USB30FD/
sudo sh ./bin/startunity
```

Once it successfully opens and runs, you can delete the backup file.

**Comment by faddah** [comment]
@DennisLfromGA & @dnschneid ,

thanks! i am trying all that. one last question: i understand deleting the back-up file, but once i make sure everything is great on the usb stick, where do i go on the chromebook SSD to delete the crouton install i did, please?

thanks again.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by DennisLfromGA** [comment]
@faddah - `sudo delete-chroot trusty`

**Comment by faddah** [comment]
*** *UPDATE* ***

@DennisLfromGA & @dnschneid,

thanks for writing back on how to delete the ```chroot``` on the chromebook ssd. much appreciated.

so, i tried what you suggested, using just this:  

```

sudo sh -e ~/Downloads/crouton -r trusty -t core,cli-extra,x11,gtk-extra,extension,keyboard,touch,unity,chrome,chromium

```

... so it would install to the chromebook SSD, not the usb stick drive partition. it still stops right on ...

```

...
I: Retrieving zlib1g 1:1.2.8.dfsg-1ubuntu1
I: Validating zlib1g 1:1.2.8.dfsg-1ubuntu1
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting adduser...
$ 

```

here's one other thing, when i first run the script above for the crouton install, it says:

```

...
WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
If this is a surprise to you, you should do a full system recovery via USB.
Installing trusty-amd64 chroot to /usr/local/chroots/trusty
...

```

...etc.

because i'm in dev mode on the chromebook, i made rootfs writable for other dev stuff i am doing. do i need to re-do that to do the install? i wouldn't think so, but i want to make sure that isn't what is going wrong here. please let me know.

thank you again for all the help.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by DennisLfromGA** [comment]
@faddah,

No, having the rootfs read-writeable is okay.
Run this in a cros shell: 

`df -h /home` 

and let us know how much available space you have.
If you've got enough space then, to keep it simple, try removing some of the targets on the initial install, you can add them later. Try it like this: 

`sudo sh -e ~/Downloads/crouton -r trusty -t extension,keyboard,touch,unity`

If it still fails at that same point, we'll have to get more info. from you.

**Comment by faddah** [comment]
@DennisLfromGA ,

thanks again for following up on this.

result is:

```

$ df -h /home
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        26G   16G  8.3G  66% /home

```

that should be plenty of space, yes?

if i run the crouton install script with just the packages you define above, it still fails right on ...

```

...
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting adduser...
$

```

so it still fails on that same point. what other info may i get for you and how, please?

and thank you again for all the follow up and help.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by DennisLfromGA** [comment]
Are you using a proxy or behind a firewall?

**Comment by faddah** [comment]
hello @DennisLfromGA ,

no proxies, no firewalls. and i've tried this from several different locations, different wifi connections each place. in any case, it seems the downloading (retrieving, verifying) each file package needed goes just fine. it's when it then takes the downloaded and verified packages, starting with "adduser...," and just quits, no explanation.

is there a switch in crouton for a verbose mode that would maybe give some clue as to what the heck is going on?

thanks again for the help.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by faddah** [comment]
hey @DennisLfromGA & @dnschneid ,

is there a Freenode IRC channel for this, perhaps, to move the communication along a little quicker? #crouton , perhaps? please let me know.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by DennisLfromGA** [comment]
Yup - README:"Hang out in the #crouton IRC channel on freenode.net!"

I wish I knew what to tell you but I'm out of answers for now, maybe some of the *big guns* will see this and step in ;-)

**Comment by faddah** [comment]
@DennisLfromGA ,

jumping on IRC now, thanks. ugh. kicking myself because i broke the old USB stick ubuntu install and cannot create a new one.  very sad.  ��😭��😢😪😭😢😪😭😢😪😭😢😪😭:::::😢😪😭😢😪😭😢😪😭😢 😪 😭

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by faddah** [comment]
hey all (including @DennisLfromGA & @dnschneid ),

so over at the Freenode IRC #crouton channel, @DennisLfromGA suggested i try these to things and post the logs so people could look at them and try and figure out why it's quitting every time at ```Extracting adduser...```.  —

```
$ sudo sh -x ~/Downloads/crouton -r trusty -t extension,keyboard,touch,unity 2>&1 | tee -a ~/Downloads/trusty-error.log

$ sudo sh -x ~/Downloads/crouton -r trusty -d -f ~/Downloads/trusty-bootstrap.tar.gz 2>&1 | tee -a trusty-bootstrap.log
```

I ran both of these and they kept quitting in the same place, when starting the ```Extracting adduser...```, only now there's more verbose info. 

i created a gist to show these error logs, here it is — https://gist.github.com/faddah/6687d4207b299af06c1a .

If folks could please look over that gist and give me any help with it, I would greatly appreciate it.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by DennisLfromGA** [comment]
@faddah, 

Since it seems we're kind'a on our own here ;), and since we've kind'a narrowed it down to grabbing the bootstrap file, I thought we could eliminate that step if I provided you one so here 'tis - [bootstrap-trusty-amd64.tgz](http://goo.gl/T0Q7n8).

After you download it, do this: 

`sudo sh ~/Downloads/crouton -f ~/Downloads/bootstrap-trusty-amd64.tgz -t extension,keyboard,touch,unity`

I think this should work...

**Comment by faddah** [comment]
@DennisLfromGA & @dnschneid ,

thank you for the compressed file. i will try that later tonight and let you know how it works.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by drinkcat** [comment]
Any update on this?

**Comment by DennisLfromGA** [comment]
@drinkcat  - No news is good news I guess. 
I suppose he either got it to work or he abandoned the effort - either way, I've heard nada...
