### ISSUE TITLE
crouton -d -f should confirm directory is writable *before* downloading everything

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1629]
If you try to create a bootstrap file in a read-only directory, crouton will fail at the final step.  It should check ahead of time that the directory is writable.

e.g., `sudo crouton -f /fail` should fail at the start on a Chromebook (where rootfs is read-only), not at the end.

**Comment by tonyxue** [comment]
what is 'pie'? :p

**Comment by tedm** [comment]
I'd like to try to fix this. I need to know which installer file -f uses, how to get that file, fix it, with disk space check, re-upload it, and then do a pull request. \

**Comment by tedm** [comment]
so to get available space, we can use this:

df -k /home | tail -1 | awk '{print $4}'

or this:

df -k /home | tail -1 | tr -s ' ' | cut -d' ' -f4

and to store in a variable, this:

$available=$(df -k /home | tail -1 | awk '{print $4}')
$echo "$available"

What file do I insert this in?

**Comment by dnschneid** [comment]
@tonyxue I'm labeling modifications that should be relatively simple as "pie" so that people who want to start contributing can do so :)

@tedm the issue is to check for read-only, not available disk space.

**Comment by tedm** [comment]
how about this:

 touch rotestfile && { rm rotestfile; echo "read-write";
 } || echo "read-only filesystem"

**Comment by DennisLfromGA** [comment]
@Ted, The file is: `installer/main.sh`

**Comment by dnschneid** [comment]
@tedm you can do it more simply, without creating test files.

**Comment by tedm** [comment]
@DennisLfromGA Thanks used the -x trick to update.

@dnschneid how about this:

grep "\sro[\s,]" /proc/mounts

**Comment by tedm** [comment]
@DennisLfromGA 

how about this:

if test ! -w "$1"
 then
   echo $1 filesystem is read only
 fi

**Comment by DennisLfromGA** [comment]
@Ted, Don't ask me, I'm just a peon ;-)

**Comment by tedm** [comment]
@dnschneid What about reusing this snippet from installer/main.sh from 2/14:

# We check by attempting to mount / read-write. We do so in a bind mount to a
# temporary directory to avoid changing its state permanently if it is
# successful.
vboot_is_safe() {
    local tmp="`mktemp -d --tmpdir=/tmp 'crouton-rwtest.XXX'`"
    local unmount="umount -l '$tmp' 2>/dev/null; rmdir '$tmp'"
    addtrap "$unmount"
    mount --bind / "$tmp" >/dev/null
    local ret=1
    mount -o remount,rw "$tmp" 2>/dev/null || ret=0 
    undotrap
    eval "$unmount"
    return "$ret" 

does -x work to get the latest crouton.unbundled still? I seem to have some old files in there.

**Comment by tedm** [comment]
why is the font so huge?

**Comment by dnschneid** [comment]
That code in installer/main.sh is checking to see whether rootfs can be made writable, and doesn't apply here.  Your `test ! -w "$1"` approach is much better, although you'll need to test the directory and do so in a style consistent with the rest of crouton.

**Comment by tedm** [comment]
How about changing this:

# Prefix must exist
if [ ! -d "$PREFIX" ]; then
    error 2 "$PREFIX is not a valid prefix"
fi

to this:

# Prefix must exist, and directory must be writable
if [ ! -d "$PREFIX" && ! -w "$PREFIX" ]; then
    error 2 "$PREFIX is not a valid prefix or the target directory is read-only"
fi

in main.sh ?

**Comment by dnschneid** [comment]
That's actually worth checking (please do it in a separate check so that you can report precisely which issue it is)...but it's not what this bug is talking about.

**Comment by tedm** [comment]
@dnschneid OK, I think I have found the right location, but need to test and fix brackets and ` marks:

from here:

    - Tar it up if we're only downloading
    if [ -n "$DOWNLOADONLY" ]; then
        echo 'Compressing bootstrap files...' 1>&2
            
to something like this, that I'll have to test tonight or tomorrow, and error msg.

 - Tar it up if we're only downloading
    if ( [ -n "$DOWNLOADONLY" ] && [ ! -w "$subdir" ] ); then ( tick marks here, or keep brackets?)
        echo 'Compressing bootstrap files...' 1>&2 (some kind of error message if read only detected)
    
right location for check?

**Comment by dnschneid** [comment]
Nope, that's really late in the process.  It should be towards the beginning, amidst the other various sanity checks.

**Comment by tedm** [comment]
below? The reason I don't think it's below is that appears to be using a previously created tarball.

The tricky part is the user command line arg is -d (and -f), but with bash types [ [ ] -d has it's own meaning. So in our hash comments, perhaps we should indicate when the user argument -x is utilized ?

- If we specified a tarball, we need to detect the tarball type
if [ -z "$DOWNLOADONLY" -a -n "$TARBALL" ]; then
    if [ ! -f "$TARBALL" ]; then
        error 2 "$TARBALL not found."
    fi

**Comment by tedm** [comment]
I see that the user arguments are parsed and translated to $f, so probably the earliest place for a filesystem check would be in here, but we only want to apply this to the downloaded bootstrap tarball, and we don't care if a user is restoring a previous tarball from a read only dir/fs.

Alternatively, we could put the test up when reading/parsing the users arguments, but that would mess up the nice table of arguments at the top.

- Either a tarball, update, target, or restore binaries must be specified.

if [ -z "$TARBALL$UPDATE$TARGETS$TARGETFILE$RESTOREBIN" ]; then
    error 2 "$USAGE"
fi

**Comment by smibarber** [comment]
When copying fragments of code you should quote them with backticks to prevent Markdown from formatting them. See the Github [guide](https://help.github.com/articles/github-flavored-markdown/).

How about around https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L228 ?

**Comment by smibarber** [comment]
To clarify with your other questions, the tarball may or may not already exist. If it exists, then downloading a new tarball to replace it with `-d -f` [won't work](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L262)

The other options there should be irrelevant for this bug. `$RESTOREBIN` is just a flag for reinstalling crouton scripts in the host, useful for when you're restoring a backup.

**Comment by tedm** [comment]
@smibarber Thanks for these tips, so how about this at 228:

```# check to see if the download directory for the bootstrap tarball is on a writable directory
if [ -z "$DOWNLOADONLY" -a -n "$TARBALL" ]; then
    if [ ! -w "$TARBALL"  ]; then
        error 2 "$TARBALL directory appears to be read-only; try again to a writable directory."
    fi
```

**Comment by tedm** [comment]
can I combine those two lines to this:

` if [ -z "$DOWNLOADONLY" ] && [ -n "$TARBALL" -a ! -w "$TARBALL" ]; then `

**Comment by smibarber** [comment]
The big if block (L230-260) should only be triggered if the tarball already exists, so that's not of any concern (e.g. you run `sudo crouton -f tarball_that_exists.tar.bz2`).

It probably makes more sense to put this off on its own, actually after the big if block (L264-ish). You'd also want to check `[ -n "$DOWNLOADONLY" -a ! -w "$TARPATH" ]` since the bootstrap tarball is only created if the `-d` flag is set.

Also note that you want to come up with a value for `"$TARPATH"` since `"$TARBALL"` doesn't exist yet. Stripping off the filename from the path isn't too difficult, I know it's done in a few places in the crouton codebase :)

**Comment by tedm** [comment]
@smibarber 

What about these new variables, if $TARBALL is the file only and no path:

`$FULLTARPATHANDFILE= // full path and full filename of tarball file as entered by user, or ~/Downloads/ if not ?? something like /dir1/dir2/croutonbootstrap.tar.gz or ~/Downloads/croutonbootstrap.bz2`

`$TARPATH=$(dirname "${FULLTARPATHANDFILE}")` 

`$TARBALL=$basename "${FULLTARPATHANDFILE}'

This will assume that the user has dirname and basename as they're not internal bash commands

and then above about line 262, this:

`[ -n "$DOWNLOADONLY" -a ! -w "$TARPATH" ]`

Thanks for correcting the -z with -n

**Comment by tedm** [comment]
@smibarber @dnschneid Where are we on this? I'm thinking that the immediate fix is erring out immediately if the -d destination isn't writable, so is $TARPATH necessary now, or will testing the writability of $TARBALL as whatever the user defines, work for now?

**Comment by tedm** [comment]
@dnschneid how about this either before or after the 230-260 block ?

Or do we really want to separate path and filename out now?

````#  check if path and file used with -d is writable
if [ -n "$DOWNLOADONLY" -a -z "$TARBALL" ]; then
    if [ -f "$DOWNLOADONLY" -a -w "$DOWNLOADONLY" ]; then
        echo "target bootstrap file directory appears to be valid and writable"
    fi
else
echo "WARNING - the path and file you specified does not appear to be writeable" 1>&2
fi
`# do the tar process of the bootstrap file ...

**Comment by tedm** [comment]
@dnschneid @smibarber any updates on this? I did an edit-chroot -b last night, and was thinking that whatever is used there could probably be used for the bootstrap file, or vice versa. But also was thinking that tar's own messages and error handling are good??

**Comment by smibarber** [comment]
Sorry for the delay. I think we should still separate out the base path and validate it. Probably don't need to explicitly print that the target path is writable.

**Comment by tedm** [comment]
OK, I'll keep working on the base path validation.

Question, In the lines of installer/main.sh , the big block starting at 377 down, is there a write access test that is not using `-w` that I am missing here?

`# Confirm we have write access to the directory before starting.`
`if [ -z "$RESTOREBIN$DOWNLOADONLY" ]; then`
` ... `
