### ISSUE TITLE
ROS commands (or any alias) using zsh and startxiwi do not function

### ISSUE THREAD

**Issue by usfbrian** [dnschneid/crouton#1630]
On an Asus C300 with Ubuntu 14.04 with xiwi and xfce4 targets (among others), attempting to open ROS (Indigo) terminals in a Chrome OS tab does not work. I am using zsh---specifically, prezto.

This is the command I'm running: `sudo startxiwi -b roscore`
If I run without the background flag, I receive the error, *xiwi: roscore: not found*.

I've since tried a workaround using an alias in my **.zshrc** to `xfce4-terminal` (an awkward command to type). The alias _also_ does not load; same error type.

(There might be two separate issues or one common issue with zsh.)
When I try the absolute path to roscore, I get several error messages after the extension connects, particularly:
*Cannot open /sys/class/tty/tty0/active: No such file or directory*
*Traceback (most recent call last):*
*File "/opt/ros/indigo/bin/roscore", line 62, in <module>*
*import roslaunch*
*ImportError: No module named roslaunch*

If I start xterm from xiwi, I can run the `roscore` service, but I'd prefer a different terminal for some of the simulators (or the ability to directly call the `ros*` commands, ideally).

Thanks in advance for your guidance.

**Comment by dnschneid** [comment]
`startxiwi` doesn't read in any rc files when launching commands, so you're stuck with default PATH variables.  Launching xfce4-terminal via startxiwi should work.  You can create an alias in Chromium OS's .bashrc if you want to shorten the command.

Alternatively, you can make fancier aliases in Chromium OS's .bashrc that wraps the commands in env to set various environment variables; stuff like: `sudo startxiwi -b env PATH=/opt/ros/indigo/bin roscore` (you can add more environment variables to set as necessary).  It's not pretty though.

Option three is you create wrapper scripts in your chroot's /usr/local/bin that do the equivalent of your aliases.

**Comment by usfbrian** [comment]
Cool. My workaround was to put an alias in Chrome's **.bashrc** to `sudo startxiwi -b xfce4-terminal`. I'll add the environmental variables to these. I've also noticed the prompt in the Xfce terminal is different than the prompt when using `enter-chroot`, presumably due to not loading the rc files. I'll slay that beast later.

**Comment by usfbrian** [comment]
It took some effort, but I added all of the environmental variables to make a single, generic alias: `ros="sudo startxiwi -b env PATH=...:$PATH ROS_DISTRO=... PACKAGE_PATH... CMAKE_PREFIX... etc`

Now if I type `ros roscore` or `ros roslaunch` or any of the other relevant commands, it opens in a new tab with the Crouton extension as expected. The only downside I have: I can't close `roscore` in the background without `ps aux | grep roscore` followed by `kill [pid]`.

Again, thanks for the help.

**Comment by dnschneid** [comment]
Glad you found a solution you like.

How about `pkill roscore`?

**Comment by usfbrian** [comment]
Made two separate aliases instead... One for background ROS commands and one which runs the command in the ChromeOS terminal. Now I can Ctrl+C out of `roscore`. It's still a lot of typing having to Ctrl+Alt+T, `shell`, type command, and input password multiple times. If I'm doing heavy duty work, I think I'll just `startxfce4` and work from there.

**Comment by mark-hahn** [comment]
> Made two separate aliases instead...

You can put in a conditional instead.

>  type command, and input password multiple times.

You shouldn't have to ever enter your password.  At least I never do.  One
thing that helps is this ...

```
sudo visudo
<your username> ALL=(ALL) NOPASSWD: ALL
```

**Comment by usfbrian** [comment]
`sudo visudo`
*visudo: /etc/sudoers: Read-only file system*

**Comment by mark-hahn** [comment]
Hmmm.  I guess I don't understand the scenario.  I type shell and
immediately run aliases that go or do anything in chroots without ever
entering a password.  I made them conditional to work in any environment.
I didn't make my system read-write.

I admit I didn't understand the earlier part of this thread.  I don't know
what ROS means but I do use a ton of aliases to run xiwi in different ways.

If you want to take the trouble, maybe you could explain the exact steps
you take and where you end up when `sudo visudo` doesn't work?

**Comment by usfbrian** [comment]
I think there might be a developer console command to remove password. Will
check in an hour.

**Comment by DennisLfromGA** [comment]
@usfbrian - In addition to Chrome OS aliases, you can wirite functions too which more easily handle more elaborate commands. I have both and source them in my `.bashrc` -
  `[ -f ~/.bash_aliases ] && . ~/.bash_aliases`
  `[ -f ~/.bash_funcs ] && . ~/.bash_funcs`

**Comment by DennisLfromGA** [comment]
@usfbrian,

> I think there might be a developer console command to remove password.

I don't know if `chromeos_setdevpasswd` will also remove a password, I know it's can be used to set one. ( It is stored in `/mnt/stateful_partition/etc/devmode.passwd` ;-)

**Comment by usfbrian** [comment]
`chromeos_setdevpasswd` will let you change the password to blank. Then, using `sudo` in the shell prompts for a password and hitting ENTER makes the command run. I guess it's more of a feature than a bug, since at least it provides the illusion of security. Thanks for the advice on the aliases and functions. I'm not a CS major---still new to everything and waiting for the day octave becomes a shell.

**Comment by usfbrian** [comment]
Renamed that file **devmode.passwd.bak**. That worked to remove the password.

Just curious: Is there any particular reason `enter-chroot` or `startxfce4` loads the various configuration scripts and `startxiwi` does not?

**Comment by DennisLfromGA** [comment]
@usfbrian - 'octave', I remember Fortran :/
