### ISSUE TITLE
Hi-DPI and Scale Factor

### ISSUE THREAD

**Issue by seanhig** [dnschneid/crouton#1631]
Apologies if this is mentioned somewhere I have not been able to find.

New Chromebook Pixel 2015.

The extension supports HiDPI mode, but seems to prevent ubuntu scale factor, or 'gsettings set org.gnome.desktop.interface scaling-factor 2' (or anything that is generally used for HiDPI linux).

Much as is described elsewhere with respect to the extension, none of the settings for resolution or scaling in System Settings > Displays do anything.

These things all worked when I replaced xiwi with xorg, but of course you lose the ability to run in a window... which is tragic.

Is there a way to apply scale factor in HiDPI mode that works with the extension?

**Comment by kellevan** [comment]
seanhig, just letting you know you aren't crazy.

Ran into the same thing, settled with Gnome... you can get it "workable" in xiwi, but the x11 session maintains proper dpi and looks crisp.

However, in X11, I get a weird graphical glitch with my mouse cursor after switching back into the session.

The mouse also feels "jumping" in x11.

Same for you?

**Comment by seanhig** [comment]
Hey kellevan,

Thanks.... assume you have the new Pixel too?

I had that cursor problem as well... there is a fix:

https://github.com/dnschneid/crouton/issues/1519

(2nd post)

I still have a few issues:

- Scaling of course - sure would be nice, my title bars are too damn thin.
- For some reason the unity launcher transparency doesn't work
- It hangs up completely if I close the lid and re-open (which is somehow
different then just sleep on this pixel, which is new to me)

But I just can't do non-Hi-DPI.  That world is like green screen.

Compared to the specs of this pixel LS, and how fast everything else, the
X11 server in Ubuntu sure feels laggy.  Using Sublime and some of the
workspace features, and it is noticeable.  Scrolling in sublime-text is
choppy on big files.  I assume that is the custom X implementation for the
xiwi... but this is all new to me.

**Comment by kellevan** [comment]
@seanhig Thanks for the fix! That solved that... it was a bugger.

You mentioned you are using Unity? Give 'gnome' a try - 3.14 seems to handle HiDPI quite well. Some of the window edges still small, but the resolution is sharp -- as long as you are in X11 and not xiwi.

That's enough thread de-railment for me, hoping the HiDPI "issues" are acknowledged by the dev team - they'll have to fix it sooner or later... wave of the fuuuutuuure ~ ~ ~ ~

**Comment by jamiecollinson** [comment]
In case it's helpful to anyone some users appear to be having success setting the scaling on individual apps and running them with xiwi, e.g. this report of Atom running in xiwi:

http://www.reddit.com/r/Crouton/comments/2zfo1e/

Screenshot looks like it's working well, and though I normally only use Atom on Windows I'm tempted to have a go on my Pixel 2.

**Comment by mark-hahn** [comment]
> and though I normally only use Atom on Windows I'm tempted to have a go on my Pixel 2.

FWIW, I use Atom on my pixel 2015 all day every day.  It is the only thing I run in an xiwi gui window.  I run no desktop other than the native chromeos.  I'm proud to say I changed all my windows machines to Linux 3 or 4 months ago and I am in heaven.

**Comment by jamiecollinson** [comment]
@mark-hahn I just tried this and it's beautiful! Might even tempt me away from my current setup (which is basically like yours, except using vim in a crosh shell instead of Atom).

Out of curiosity are you setting `require('web-frame').setZoomFactor(2)` in your `.atom/init.coffee` file? For me it's a big visual improvement and now the only minor annoyance is the mouse cursor in the xiwi window looks fuzzy in comparison to the crisp text!

**Comment by gryfxx** [comment]
@jamiecollinson There is a HiDPI plugin that works like magic within Atom.

Looks oh so good.

**Comment by jamiecollinson** [comment]
@gryfxx - I guess you mean https://atom.io/packages/hidpi? Just tried it and it's great - thanks for the tip!

**Comment by dnschneid** [comment]
crouton currently doesn't deal with DPI when adjusting for various xiwi resolutions/hi-dpi mode.  Not sure what it'd take, but it'd be a reasonable thing to look into...

**Comment by tarcieri** [comment]
Well I have Crouton running in HiDPI mode on a 2400x1600 Chromebook Pro, and yeah, it'd sure be nice if xiwi let me set the DPI.

**Comment by benben233** [comment]
5 years past, same problem. Now more and more device use high DPI, the issue should be considered
