### ISSUE TITLE
Downloaded compton, ubuntu no longer works through crouton.

### ISSUE THREAD

**Issue by Jimzyboi** [dnschneid/crouton#1634]
Please help, I tried to install compton to remove video tearing in xfce. However after doing this and restarting I only get a black screen in ubuntu, then if i go back to chrome os and try and go back into ubuntu i get stuck in a developer console. Here is a screenshot of the errors i get in the chrome terminal. Any help will be much appreciated, thanks.
![screenshot 2015-04-17 at 18 55 32](https://cloud.githubusercontent.com/assets/11875732/7208080/01d4ff32-e536-11e4-98e5-4ab53add84c3.png)

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
