### ISSUE TITLE
startcli failing due to openvt being unable to open console

### ISSUE THREAD

**Issue by unlikelylass** [dnschneid/crouton#1635]
I've noticed that, on the beta channel with my Acer C720, that startcli has ceased working.  This appears to be due to openvt inside the chroot failing, as I get the same error if I try running the openvt command from the startcli script after running enter-chroot.

To be clear:  everything else continues to work fine.

Visible error:
chronos@localhost ~ $ sudo startcli
Entering /mnt/stateful_partition/crouton/chroots/work...
Couldn't get a file descriptor referring to the console
Not unmounting /mnt/stateful_partition/crouton/chroots/work as another instance is using it.
chronos@localhost ~ $

Crouton version:
crouton: version 1-20150414182244~master:da478a77

ChromeOS version:
Version 42.0.2311.87 beta (64-bit)
Platform 6812.75.2 (Official Build) beta-channel peppy
Firmware Google_Peppy.4389.89.0

**Comment by DennisLfromGA** [comment]
Without the full `croutonversion` output we can't tell what 'xmethod' you're using or if you're using 'freon' or not but, to the best of my knowlege, `startcli` won't work on 'freon' systems.

**Comment by unlikelylass** [comment]
Sorry about that!

crouton: version 1-20150414182244~master:da478a77
release: jessie
architecture: amd64
xmethod: xiwi
targets: cli-extra,e17,lxde,extension,xiwi,chrome,keyboard
host: version 6812.75.2 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 18:57:27 PDT 2015 x86_64 GNU/Linux
freon: yes

And yes, it's on freon.  D'oh.  Well, that explains that.

Thanks!
