### ISSUE TITLE
Cron on Crouton won't work

### ISSUE THREAD

**Issue by sveisa** [dnschneid/crouton#1636]
Hi,

I can't get cron jobs to run properly on my ASUS Chromebox, which is running Crouton.

I have followed these instructions: https://github.com/dnschneid/crouton/wiki/Setting-Up-Cron-Job

1. I've edited /etc/rc.local
2. I've added the cron job to /etc/crontab
3. When I run crontab -l as root, I see the cron job

The cron job is this: 30 2 * * * /home/name/daily.py

The script works when I run it from the terminal.

**Comment by mark-hahn** [comment]
Did you use `crontab -e`?

**Comment by tcagle** [comment]
You might try rebooting your chromebook. It sounds as though the crond is
not running.

**Comment by sveisa** [comment]
Thanks to both of you! I tried rebooting and it didn't help. The cron job was added to /etc/crontab, not crontab -e, per the instructions I link to in the original post.

**Comment by vi-s** [comment]
I used crontab -e, and have tried restarting my computer.. no luck. I have the same issue as OP, crontab just doesnt run.

**Comment by tedm** [comment]
it's working here on precise / ARM. the daemon isn't cron.d though, just cron.

see if /etc/init.d/cron is running with:

`#ps ax | grep cron`

**Comment by vi-s** [comment]
I am on an Intel processor with Trusty... no idea if that would have any effect.

I have checked and cron is indeed not running unfortunately :(

**Comment by tedm** [comment]
you need to start it, it doesn't autostart

/etc/init.d/cron start

there is no upstart, so service cron start won't work, but you can put /etc/init.d/cron start in your 

/etc/rc.local file to start when your chroot starts.

**Comment by vi-s** [comment]
No good on the `/etc/init.d/cron start`. Cron unfortunatley still does not start up and does not show up in ps aux output... Here is the output I get when I try to run that command:
```
Rather than invoking init scripts through /etc/init.d, use the service(8)
utility, e.g. service cron start
initctl: Name "com.ubuntu.Upstart" does not exist

Since the script you are attempting to invoke has been converted to an
Upstart job, you may also use the start(8) utility, e.g. start cron
start: Name "com.ubuntu.Upstart" does not exist
```

**Comment by tedm** [comment]
@vi-s do you have cron? 

`sudo find / -name cron`

if not, apt-get install cron

if you have it should run, use:

`/etc/init.d/cron start`

then check for this link:

lrwxrwxrwx 1 root root 21 Jun 19  2012 cron -> /lib/init/upstart-job

then run /etc/init.d/cron again

and check for process with ps ax | grep cron

**Comment by sveisa** [comment]
Cron is installed and I get this output (from ps ax | grep cron):
8109 pts/1    S+     0:00 grep --color=auto cron
14205 ?        Ss     0:00 cron

Does this mean that Cron is indeed running?

**Comment by tedm** [comment]
@sveisa yes. test it with a simple:

`* * * * * dmesg > /home/dmesg.txt`

with crontab -e after adding the user to the crontab group

put /usr/sbin/cron or another line in /etc/rc.local or whatever you did to enable will need to run every session.

**Comment by sveisa** [comment]
Ah, it works after adding /etc/init.d/cron to rc.local!

But the output is also in root. How can I direct all outputs to a specific directory, not just a specific file?

**Comment by tedm** [comment]
just change the command with crontab -e, perhaps:

`* * * * * dmesg > /home/username/dmesg.txt`

be sure to run crontab -e as root or as user, depending on what you're doing.

**Comment by sveisa** [comment]
Ah, yes, but in the python file I'm trying to execute the output is five individual txt files. So how can I direct all output from the py file to something like /home/username/daily?

**Comment by tedm** [comment]
To me, a python is a deadly snake. This is the cryptic shell and linux basics forum ;)

**Comment by sveisa** [comment]
Haha, I see. But in general, is there a way to tell cron to direct output to a directory, not a file?

E.g. 
* * * * * dmesg > /home/username/folder
instead of 
* * * * * dmesg > /home/username/dmesg.txt

**Comment by tedm** [comment]
everything in linux is a file, even a directory. The > is a redirector of stdout (default is screen) to a file, if you don't give it a name, where is it supposed to reside in the folder, which is just a file? If you aren't careful, you could overwrite a directory (file) with the dmesg output.

**Comment by sveisa** [comment]
Thanks for the warning! And all the help!

**Comment by dnschneid** [comment]
You can't overwrite a directory with `>` redirection.  I suspect your tool is outputting to the current directory, which is the home directory by default.  Try either passing it a flag that changes the output directory (if it has one), or wrapping it in a shell command that cd's before calling python.
