### ISSUE TITLE
xiwi does not work when mirroring to tv screen via hdmi

### ISSUE THREAD

**Issue by dragonloverlord** [dnschneid/crouton#1637]
When I start a xiwi chroot well mirroring my chromebook to a tv screen via hdmi the chromebook will have very strange display issues and the taskbar will disappear which forces me to have to shutdown the chromebook by force.

**Comment by dnschneid** [comment]
Could you please post the output of `sudo edit-chroot -al`?

**Comment by dragonloverlord** [comment]
output is:

name: utopic
encrypted: yes, unlocked
Entering /media/removable/chroots/utopic...
crouton: version 1-20150414182244~master:da478a77
release: utopic
architecture: armhf
xmethod: xiwi
targets: xiwi,audio,keyboard,extension,lxde,gtk-extra,x11,xephyr,core
host: version 6812.75.2 (Official Build) beta-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 18:49:32 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no

This issue also occurs on a trusty chroot.

**Comment by dragonloverlord** [comment]
I have tested this issue with both xiwi and xephyr and the issue occurred in both of them. The issue also occurs regardless of the display settings (mirrored screen or extended screen). The chroot does work just fine well not being mirrored to a external display. Switching to VT2 and typing "sudo restart ui" will fix the problem but it also closes all open programs/apps and logs out the current user.
