### ISSUE TITLE
cannot create regular file ‘/usr/local/chroots/trusty/.crouton-targets’: No such file or directory

### ISSUE THREAD

**Issue by PickleJuice** [dnschneid/crouton#1638]
ChromeOS trying to install Crouton and it stops with the following:

cp: cannot create regular file ‘/usr/local/chroots/trusty/.crouton-targets’: No such file or directory

Any ideas how to proceed?

**Comment by dnschneid** [comment]
What command are you running?  Could you please post the full logs?

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by aghasemi** [comment]
Can you re-open this please? I got the same error on CloudReady ChromiumOS 52:
Installation command `sudo sh crouton -r trusty -t xiwi,core`

It ended with

```
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
cp: cannot create regular file ‘/usr/local/chroots/trusty/.crouton-targets’: No such file or directory
```

Any idea?

**Comment by DennisLfromGA** [comment]
Re-opened, please provide some more details if you can -
- Is this the first time you've used Cloudready and you ran into this problem?
- Have you run into this problem on any other versions or using Chrome OS?

Or anything else that you can think of that might be relevant.

**Comment by aghasemi** [comment]
Thanks.

- Yes. A standalone installation of CloudReady, with crouton tried right after installation
- No idea about ChromeOS. I've tried the unofficial VirtualBox image as well, where I received another error, issue #2850 .

**Comment by DennisLfromGA** [comment]
**_@crouton-devs_**

It's evident that I don't understand how all this works but it looks to me like the condition statement on [main.sh#L688](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L688) only executes if we are *restoring* the host-bin files. 

And [main.sh#L726](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L726) doesn't check to see if `.crouton-targets` exists first.

*Curious,*
-**DennisL**

**Comment by aghasemi** [comment]
I re-downloaded the script now and it successfully installed xenial. Unless you've fixed it yourself, it's not a good sign :-/

**Comment by DennisLfromGA** [comment]
The crouton installer script should get a fresh copy of crouton when it's run so I don't think re-downloading it was the solution, unless yours was very old.

I didn't fix it but if you if you updated your chroot instead of installing a new one that may be all it needed.

If you installed a new one then I agree, we may not know what the original problem was/is.

**Comment by aghasemi** [comment]
Maybe `touch`ing the file before using it is a good on-intrusive solution. No?
