### ISSUE TITLE
Switching between Chrome OS and Xfce key combo

### ISSUE THREAD

**Issue by GMTurbo** [dnschneid/crouton#164]
I'm using the Samsung Chromebook Series 5 with the intel celeron.

I'm having problems switching between the two OS's. 

I've using Ctrl-Alt-back and I can successfully switch from Xfce to chrome OS, but I can't go the other way. Also, there is a full terminal screen that appears during the switch from Xfce to Chrome OS.

Ctrl-Alt-Shift-Forward and back don't seem to do anything.

This project rocks by the way.  You all kick ass.

**Comment by ImaginaryDevelopment** [comment]
does this still work? I've followed the link to #48 and still no luck. I'm on an Acer c720p with ubuntu 12.04 via crouton.

**Comment by Pobux** [comment]
Same here, the controls to switch do not work anymore.

chronos@localhost / $ cat /etc/*-release 
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={E6710DFC-3EC0-42AE-8095-733FDEA6AF18}
CHROMEOS_RELEASE_BOARD=peppy-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=83
CHROMEOS_RELEASE_BUILD_NUMBER=6812
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=42
CHROMEOS_RELEASE_DESCRIPTION=6812.83.0 (Official Build) stable-channel peppy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6812.83.0
GOOGLE_RELEASE=6812.83.0

**Comment by divx118** [comment]
@Pobux ctr-alt-shift forward/backward Notice the shift.

**Comment by Pobux** [comment]
Here's the correct way to do it : 

From Crouton to ChromeOS : 
Ctrl + Alt + Shift + Back

From ChromeOS to Crouton : 
Ctrl + Alt + Back (x2)

**Comment by apgodshall** [comment]
Thanks!  Yes ctrl-alt-shift-back toggles between crouton chroot xfce4 and cromeos host, as does ctrl-alt-shift-forward, on my Asus Flip C101PA updated to latest beta channel chromeos 63.0.3239.140.

Let me add that on an external keyboard, ctrl-alt-shift-F1 does the toggle as well, as does ctrl-alt-shift-F2.

**Comment by cechmanek** [comment]
This is not working for me at all. I am trapped in my *nix environment and cannot return to chromeOS. I've tried every combination of control, alt, shift, forward, backward, refresh. 

I'm on an Asus Chromebook running crouton.

**Comment by DennisLfromGA** [comment]
@cechmanek,

Please show us the output of: `sudo edit-chroot -all`
Then we can try to narrow down the root cause.

-**DennisLfromGA**

**Comment by theTECHIEflyer** [comment]
Hi,

I am having the same problem. I've tried everything. Here is an output of `sudo edit-chroot -all`
`


```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11021.81.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-18546-g285bb8d836e6 #1 SMP PREEMPT Thu Nov 15 22:53:25 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

**Comment by DennisLfromGA** [comment]
The key combos <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>F1/F2</kbd> should work on all devices with crouton chroots using the 'xorg' xmethod.  
If they don't work for you one workaround might be to use the below terminal command in your chroot:

- `croutoncycle cros`

That should put you back in your Chrome OS session.

Here is the `croutoncycle` usage message that shows 'cros' and other options:
```
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by luka1231123** [comment]
please help me nothing work's i tried everything am locked on chrome os after i restarted my chromebook and can't get into xfce linux i also tried ctrl+alt+shift+f1/f2 nothing, this is my output
`name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190710132432~master:7e345389
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11895.118.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-19095-g86596f58eadf #1 SMP PREEMPT Tue May 14 23:29:06 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`
(sorry for my bad english).

**Comment by luka1231123** [comment]
please help

**Comment by luka1231123** [comment]
please

**Comment by DennisLfromGA** [comment]
@luka1231123,

> i tried everything am locked on chrome os after i restarted my chromebook and can't get into xfce linux

That doesn't sound like this issue: 'Switching between Chrome OS and Xfce key combo'
It sounds like your desktop isn't launching. If that's the case then please do the following:
- Update your chroot, your using a *very* old version
- See '[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)'
- Open a new issue and give us more details about what errors or warnings are displayed when you try to get into your chroot.

*Hope this helps,*
-**DennisLfromGA**
