### ISSUE TITLE
Cras running, but no sound.

### ISSUE THREAD

**Issue by DGO143** [dnschneid/crouton#1640]
![screenshot - 041915 - 11 39 20](https://cloud.githubusercontent.com/assets/6561144/7218961/d2d06474-e689-11e4-938b-d1f700ebd0a2.png)
I have mpd playing through PulseAudio on Xubuntu precise, but i don't hear anything.

Pulseaudio is running:
`(foobar)luukw@localhost:~$ pulseaudio`
`E: [pulseaudio] pid.c: Daemon already running.`
I get an error though, not sure if it's because pulseaudio was already running or something's wrong:
`E: [pulseaudio] main.c: pa_pid_file_create() failed.`

`cras` is running:
![image](https://cloud.githubusercontent.com/assets/6561144/7219689/38c52392-e6ac-11e4-90e9-7d8f0cee841a.png)

I turned up both my Chrome OS and Xubuntu sound, also tried plugging in headphones and updating crouton and the chroot.

UPDATE: I'm getting sound from youtube! Looks like it's an mpd problem.

**Comment by dnschneid** [comment]
mpd has issues with pulseaudio unless you're running it as the same user that is running pulseaudio.  One workaround is to enable the pulseaudio TCP interface and tell mpd to use localhost ([see tutorial](https://wiki.archlinux.org/index.php/Music_Player_Daemon/Tips_and_tricks#PulseAudio)).
