### ISSUE TITLE
New ChromeOS update breaks Crouton

### ISSUE THREAD

**Issue by vi-s** [dnschneid/crouton#1641]
So I installed the new ChromeOS update on my Acer C720 this morning and bam, my chroot using xfce and trusty ubuntu became broken. Upon trying to start the chroot environment with `sudo startxfce4` I get a X window server crash, and nothing else happens. I power-washed and reverted my chromebook to the prior version of ChromeOS and things started working again after I re-installed the chroot once again using xfce and trusty ubuntu. Not sure what the issue was, but kind of a pain in the ass with the data loss and all.

**Comment by divx118** [comment]
@vi-s Updating your chroot should have fixed the problem. See https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by vi-s** [comment]
ahhhh, i feel silly now :P
