### ISSUE TITLE
Crouton closes immediately

### ISSUE THREAD

**Issue by toad1359** [dnschneid/crouton#1643]
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xiwi
targets: touch,unity,xiwi
host: version 6680.78.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Mar 20 15:40:08 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Error: not connected.
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
Connected to extension, launched crouton in a window.
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost

Output^^ As soon as crouton launches, it closes.

**Comment by dnschneid** [comment]
Your chroot is way old.  [Please update it](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting).
