### ISSUE TITLE
Black screen Trusty and KDE

### ISSUE THREAD

**Issue by Tuxerito** [dnschneid/crouton#1644]
Hi.

I can use ChromeOS and Crouton(Trusty/KDE) at the same time but with one issue.

When I start Trusty using "sudo startkde -n trusty" the screen turns black. I can press Ctrl + Alt + Back to return to ChromeOS. Trusty always loads and I can use it but to change to Trusty I must to close the lid and open it again every time I want to use Trusty. If I am using ChromeOS and I want to use Trustry I must press Ctrl + Alt + Forward  then Ctrl + Alt + Refresh and then close the lid wait some seconds and open the lid. To return to ChromeOS I can do it as normally using Ctrl + Alt + Back and I see the Login screen because the lid was closed.

This issue appears around two months ago after ChromeOS was updated, before no problems.

Crouton and Trusty are up to date

-----Device ---
Acer C710

-----ChromeOS version ------
Version 42.0.2311.87 beta (64-bit)
Platform 6812.75.2 (Official Build) beta-channel parrot
Firmware Google_Parrot.2685.37.0

-----Crouton version ------
$ croutonversion 
crouton: version 1-20150414182244~master:da478a77
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xiwi,kde,keyboard
host: version 6812.75.2 (Official Build) beta-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Tue Apr 14 19:01:35 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

Thanks

**Comment by dnschneid** [comment]
Does it work better if you use <kbd>Ctrl+Alt+*Shift*+Forward</kbd>?

**Comment by Tuxerito** [comment]
Hi. No. If I use (Ctrl + Alt + Forward, Ctrl + Alt + Refresh) or Ctrl+Alt+Shift+Forward I always see KDE but just  for milliseconds and then the screen turns black.

With other chroot(Debian) no problem.

**Comment by Tuxerito** [comment]
Yesterday ChromeOS(Beta) was updated and the problem disappers and now my Kubuntu runs normally :D

**Comment by divx118** [comment]
@Tuxerito Could you post your croutonversion output (`sudo enter-chroot -n trusty croutonversion`), so we can see approximately how long it will take to stable. Still have a few people with the same problem in #1632

**Comment by Tuxerito** [comment]
Hummm The problem apperars today again.

Yestarday ChromeOS was updated and after the update I noticed that the problem was "fixed" then I restart my ChromeBook and I tested again and no problem I rebooted several times and each time I started Kubuntu 2 or 3 times without problem and switching each time between ChromeOS and Kubuntu also closing the lid and all test worked.

Today again I tested and no problem so I closed this issue. Later at noon I updated crouton(Checking for the new Ubuntu) but now the problem appears :(
------------------------------
crouton: version 1-20150423153254~master:2f55723c
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,kde,unity,xiwi,keyboard
host: version 6946.20.0 (Official Build) beta-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Mon Apr 20 21:40:50 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
-------------

Testing with Unity same problem.

Before I created this thread I found the others threads with similar problems but with different desktops or versions, also they don't mentioned if they can use their systems like me(closing/opening the lid) or if they can see the desktop at least for less than a sec so i decided create this.

Reopened again.

**Comment by Tuxerito** [comment]
Ok more test.

If I start KDE/Unity the screen turns off(Turns off because you can notice difference with a black screen or screen off) and nothing appends if I press Ctrl+Alt+Shift+Forward(@dnschneid suggested) 2-3 times  I can see the desktop and after that I can switch normally using Ctrl+Alt+Forward/Back between OS. When they suggested that I tried it all days and not worked but today that works. When I tested yesterday and today at morning all works without using Ctrl+Alt+Shift+Forward.

Maybe the new ChromeOS version fixed partially this problem?

I have this issue around two months a now I am closer to the solution.

**Comment by divx118** [comment]
I guess it all has to do with the transition to freon. When transitioned to freon, ctr-alt Forward/back will not work anymore see #1646. The keys to use are ctr-alt-shift forward/back. I also think when the transition to freon is complete the problem will be solved. I already hoped it was on freon when you said it started working yesterday, but looking at the croutonversion output it is not yet.

**Comment by Tuxerito** [comment]
Ok now is working.

When I start KDE screen turns black and some seconds later I can see the desktop and I can switch between OS normally.

**Comment by Tuxerito** [comment]
After some days testing mostly time all worked "normally"(black screen but just for 20-30 seconds and no close lid needed) but since yesterday KDE didn't load normally and I needed again  close/open the lid after the black screen, but if I start Unity no problem. All days I updated Crouton and Jaunty when updates available


Today I decided update my ChromeOS to Dev Channel(before was in Beta channel)

After the update I couldn't start KDE some errors. I fixed running
sudo sh ~/Downloads/crouton -u -n trusty

Now all is working normally and with normally I means without the 20-30 seconds of black screen. When I start KDE I can see the splash screen in less than 5 seconds like 3 moths ago.

Now to change between OS I use Ctrl + Alt + Shit +(Back/Forward) without Refresh key( you told me something about Freon and new keys.)

-----------------------------------------------
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150503215233~master:75fb08cb
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,kde,unity,xiwi,keyboard
host: version 7019.0.0 (Official Build) dev-channel parrot_freon 
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 29 03:43:42 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
-----------------------------------------------

**Comment by divx118** [comment]
@Tuxerito Thanks for the update. I see dev-channel also has now the newer kernel 3.8.11 instead of 3.4.0 for your device.

**Comment by Tuxerito** [comment]
The problem seems to be solved and now I close this issue after some days without the black screen.

Thanks for your help and thanks to all how make Crouton possible :D

**Comment by tomulet** [comment]
Make sure Chrome OS is in Stable channel.
