### ISSUE TITLE
problem with using proxy to get ubuntu

### ISSUE THREAD

**Issue by pojoker** [dnschneid/crouton#1645]
I'm in china, and I have bought the pixel 2015.
but I can't install the crouton on it. So i use the proxy.
problem one is solved.
But, now there is another problem that each time I try to finish the set up of chroot
"Cannot initiate the connection to" shows up.
Err http://archive.ubuntu.com trusty Release.gpg
  Cannot initiate the connection to 15838:80 (0.0.61.222). - connect (22: Invalid argument)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Cannot initiate the connection to 15838:80 (0.0.61.222). - connect (22: Invalid argument)
Really don't know how to fix those problems above.
SO SOMEBODY HELP ME！

**Comment by tonyxue** [comment]
It's not the case with proxy but the bad connection to the Ubuntu apt server.
Try to solve it by editing ```/etc/apt/sources.list``` in side the chroot or use ```-m``` option at the setup to switch to other mirrors.

**Comment by pojoker** [comment]
upadates: Here comes the problems. If I use the mirrors in china the problem above can be solved. But without proxy. I can't download anything from chromium........

**Comment by dnschneid** [comment]
Looks like the tips in #1150 are what you want.
