### ISSUE TITLE
Is this normal behavior for a xiwi tab startup or am I doing something wrong...

### ISSUE THREAD

**Issue by tcagle** [dnschneid/crouton#1647]
My tab opens and works fine but
Here is what I see in the launching console...

chronos@localhost / $  sudo enter-chroot -b xiwi -T startxfce4
Password: 
Enter encryption passphrase for precise.pws: 
Entering /mnt/stateful_partition/crouton/chroots/precise.pws...
WARNING: /etc/rc.local failed with code 1
chronos@localhost / $

**Comment by dnschneid** [comment]
It means that you have added something to /etc/rc.local that isn't running properly.  It won't impact crouton unless you actually depend on whatever program you're trying to launch in there.
