### ISSUE TITLE
Unable to start Trusty xfce croot

### ISSUE THREAD

**Issue by JasoonS** [dnschneid/crouton#1648]
So here is what my terminal looks like. I am not sure what to do here. I have seen other people with issues with xorg and trusty. Is there a solution here, or is it something to re-install over?

Thank you!

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue Apr 14 20:45:15 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=6faabe60-477d-ad40-8ad2-10421c2c4aec/PARTNROFF=1 hashtree=PARTUUID=6faabe60-477d-ad40-8ad2-10421c2c4aec/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=aac0e693463297b9837b1124407a20239526c662 salt=5297b1718ac0c43cf0b33f87f1381466523bdd75b202e8f223cba36aed74badc" noinitrd vt.global_cursor_default=0 kern_guid=6faabe60-477d-ad40-8ad2-10421c2c4aec add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Apr 20 09:36:40 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x48) [0x7f2175454848]
(EE) 1: /usr/bin/Xorg (0x7f21752ab000+0x1ad539) [0x7f2175458539]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f21743a7000+0x10340) [0x7f21743b7340]
(EE) 3: /usr/bin/Xorg (0x7f21752ab000+0xb57a6) [0x7f21753607a6]
(EE) 4: /usr/bin/Xorg (xf86BusProbe+0x9) [0x7f2175334099]
(EE) 5: /usr/bin/Xorg (InitOutput+0x74d) [0x7f21753426fd]
(EE) 6: /usr/bin/Xorg (0x7f21752ab000+0x59bab) [0x7f2175304bab]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7f2172de7ec5]
(EE) 8: /usr/bin/Xorg (0x7f21752ab000+0x451ee) [0x7f21752f01ee]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
^C
Session terminated, terminating shell.../usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: unexpected signal 2
 ...terminated.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by divx118** [comment]
Update your chroot and it should work again. See https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting 
Don't forget to close this issue when the above is working for you. Thanks.

**Comment by JasoonS** [comment]
Thanks, that worked.
