### ISSUE TITLE
VPN and browser

### ISSUE THREAD

**Issue by gonsolo** [dnschneid/crouton#1649]
If I vpn into my company's network via openconnect in the chroot and want to look at the intranet html pages I currently have to use the browser within the chroot. Is there a way to use the Chrome browser?
(The company is using Anyconnect so Chrome's VPN doesn't work)

**Comment by cheat117** [comment]
which flavor is your chroot? (Ubuntu, Kubuntu, Backtrack, Debian)

Depending on your flavor, you could just re-install chrome...although i know that takes unneeded space. Details on that found (http://askubuntu.com/a/510186)[here (askubuntu.com)] OR you could go to their install page and install chrome that way.

**Comment by gonsolo** [comment]
> which flavor is your chroot? (Ubuntu, Kubuntu, Backtrack, Debian)
> 

Ubuntu. Vivid. :)

> Depending on your flavor, you could just re-install chrome...although i know that takes unneeded space. Details on that found (http://askubuntu.com/a/510186)[here (askubuntu.com)] OR you could go to their install page and install chrome that way.
> 

I have Firefox installed. I was just interested if there was a way of sharing the routing to access the webpage of the Intranet in the existing browser. 

Thanks

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
