### ISSUE TITLE
Cannot switch back to ChromOS from chroot

### ISSUE THREAD

**Issue by Paumanok** [dnschneid/crouton#1651]
I changed my acer c720 to the developer channel and afterwords, I wasn't able to get into my chroot. I ran 'sudo sh ~/Downloads/crouton -u -n trusty'  to update crouton and I was able to get back into my chroot. This time gnome3 was incredibly unstable, XFCE4 was mostly okay, and neither could re-enter chromeOS via [ctrl][alt][<=]. 

I then clobbered and restored the updated version and now i'm back go getting the errors I had originally. Those errors are pretty much the same issue as here https://github.com/dnschneid/crouton/issues/1450.

Just to be sure I updated crouton again and I'm back at square one, unable to exit the chroot unless I log out or shut down the machine.

It should also be noted I have both xfce4 and gnome3 installed on this chroot, which may have caused some keyboard mapping errors when everything was updated.

**Comment by divx118** [comment]
@Paumanok See https://github.com/dnschneid/crouton/issues/1646 Keyboard combination is Ctr-Alt-Shift Forward/Backward Using only Ctr-Alt may have worked in the past, but was not the recommended way to switch between chroots.  
Don't forget to close this issue when this solves it for you. Thanks.

**Comment by Paumanok** [comment]
Wow I feel silly now. I didn't think to doubt my muscle memory. Thanks!
