### ISSUE TITLE
Running from SD Card, closing lid crashes Ubuntu

### ISSUE THREAD

**Issue by Jimzyboi** [dnschneid/crouton#1653]
I'm running crouton from my SD Card, however whenever I close the lid in Ubuntu and leave it down for longer than a minute or so, when I open it back up I am either stuck on a black screen or on the desktop where I cannot click anything. In either situation I cannot return to Chrome OS without rebooting my chromebook. Is there any way to fix this?

Thanks

**Comment by DennisLfromGA** [comment]
https://github.com/dnschneid/crouton/issues/288#issuecomment-39415458

**Comment by Jimzyboi** [comment]
I dont have a file named powerd_suspend in either /usr/bin or /usr/local/bin, closest I could find was croutonpowerd in /usr/local/bin. Is there anyway I can get powerd_suspend?

**Comment by DennisLfromGA** [comment]
`powerd_suspend` is found in Chroms OS, not in your chroot. Those changes need to be performed in a cros shell.

**Comment by Jimzyboi** [comment]
Tha
