### ISSUE TITLE
feature request: estimating size of backup

### ISSUE THREAD

**Issue by midnightradio** [dnschneid/crouton#1655]
It's strange to fail in backup chroot due to insufficient space with 32GB USB thumb drive. Even if the backup packs up Download folder (other than this, I cannot think of any other possibility) it cannot be such amount of size as I don't keep any large files in there. Eventually failing after waiting backup procedure to take almost two hours with filling up 32GB, would make anyone feel futility.

Anyway, Is there specific way to estimate the size of backup? Would be better to have such feature in order to prepare sufficient storage beforehand.

**Comment by DennisLfromGA** [comment]
@midnightradio - 

Try: `du -sh /usr/local/chroots/[CHROOTNAME]` to get the total size of your chroot.

I just did a backup of my wheezy chroot and this is what I got:
- 4.5G    /var/crouton/chroots/wheezy/
- 1.9G    ~/downloads/wheezy.tar.gz

That compressed size looks to be about 42% when using `tar` and `gunzip`
The backup time and rate were:
- 81MiB [2.81MiB/s] [>                                         ]  0% ETA 0:25:18

----

*The crouton author is looking at providing more feedback when doing backups, restorals, and encryption using a program called `pv` for 'pipeview', this will display the info. similar to what I got above.
It will provide realtime estimates of rate and completion time - very helpful for most of us I think.*

----
I'm not recommending this right now but, if you're sure your chroot is unmounted and not in use, you can try the following to do a backup with estimated rate and completion times:

NOTE: substitue [CHROOTNAME] with your actual chroot name in the 3 locations below!
```
tar cf - /usr/local/chroots/[CHROOTNAME] -P |\
    pv -i 5 -w 80 -berps $(du -sb /usr/local/chroots/[CHROOTNAME] |\
    awk '{print $1}') | gzip > [CHROOTNAME]-`date '+%Y%m%d-%H%M'`.tar.gz
```

**Comment by midnightradio** [comment]
@DennisLfromGA Thank you very much for your answer in detail. I thought it supposed be more complicated than just checking disk usage (du) somehow...
