### ISSUE TITLE
Having a weird bug starting Ubutnu from my Chromebook. (crouton installed on SD card)

### ISSUE THREAD

**Issue by aquisenberry** [dnschneid/crouton#1656]
tried to start crouton, which is installed on my SD card, using the following command. 

"sudo sh /media/removable/SD/bin/startxfce4"
it used to work then it randomly started giving me this output:

Entering /media/removable/SD/chroots/trusty...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue Apr 14 20:43:12 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=657cf66d-dd22-5e4b-814a-2a6b38a5d7c6/PARTNROFF=1 hashtree=PARTUUID=657cf66d-dd22-5e4b-814a-2a6b38a5d7c6/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=45e6c45d7f91005eb3265c86cdf50fb85b6449c4 salt=d14d293f1aa4206fae2fe4284ac3a5e3de528f53b75f6b378b55c5ce1c9ddfc5" noinitrd vt.global_cursor_default=0 kern_guid=657cf66d-dd22-5e4b-814a-2a6b38a5d7c6 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed Apr 22 17:25:41 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/X (xorg_backtrace+0x48) [0x7fee28cc6848]
(EE) 1: /usr/bin/X (0x7fee28b1d000+0x1ad539) [0x7fee28cca539]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7fee27c19000+0x10340) [0x7fee27c29340]
(EE) 3: /usr/bin/X (0x7fee28b1d000+0xb57a6) [0x7fee28bd27a6]
(EE) 4: /usr/bin/X (xf86BusProbe+0x9) [0x7fee28ba6099]
(EE) 5: /usr/bin/X (InitOutput+0x74d) [0x7fee28bb46fd]
(EE) 6: /usr/bin/X (0x7fee28b1d000+0x59bab) [0x7fee28b76bab]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7fee26659ec5]
(EE) 8: /usr/bin/X (0x7fee28b1d000+0x451ee) [0x7fee28b621ee]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /media/removable/SD/chroots/trusty...

I don't even know where to begin to try to fix this, as I am very new to anything that is not windows

**Comment by divx118** [comment]
Try updating your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting
