### ISSUE TITLE
Stop compiling freon & cras  for every crouton update 

### ISSUE THREAD

**Issue by ccaapton** [dnschneid/crouton#1657]
It appears that everytime I update the crouton, it will download a bunch of dev packages and compile freon+cras, and remove these pkgs after. Why not add some version information for these two so there is no need to recompile if they are already most updated?

**Comment by tonyxue** [comment]
+1 I'm inside the Great Firewall and download from googlesource.com is just painful.

**Comment by tonyxue** [comment]
@dnschneid 
For the audio target, I am thinking about simply adding a check on whether the local commit id stored in ```/var/host/cras_version``` is identical to the one from ```heads.txt``` downloaded.
But I didn't get why the thing now in ```targets/audio``` is written in this way:

Check the local id, if we do have one, download and compile
If we don't have one, get one from git, download and compile

I noticed in the comment there is a line: ``` ADHD_HEAD is normally autodetected```. Does this mean the latest ```ADHD_HEAD``` is normally updated from somewhere else and those two if clauses are just checking in case?

**Comment by gdm85** [comment]
Noticed this as well, was rather surprised by it too

**Comment by dnschneid** [comment]
Sort of in-line with #1049; crouton needs to update audio whenever and only whenever needed.
