### ISSUE TITLE
Kali Wifi USB adapter!

### ISSUE THREAD

**Issue by flowabuse** [dnschneid/crouton#1658]
How do i use a usb external wifi adapter with kali crouton. When i use ifconfig i only get mlan0, so i don't think the device is being detected.

**Comment by DennisLfromGA** [comment]
Configure it in Chrome OS and it should *show up* in your chroot.

**Comment by smibarber** [comment]
If the device doesn't show up with ifconfig, it's probably not supported by the kernel. There's support for certain WiFi USB dongles (RT2800 is supported in 3.14 at least) and a lot of USB Ethernet dongles.

If it's not in the kernel then you're out of luck unless you want to try compiling the appropriate modules yourself.
