### ISSUE TITLE
Gnome desktop not starting

### ISSUE THREAD

**Issue by nakulbende** [dnschneid/crouton#1660]
I installed trusty with gnome-desktop target, and it actually worked fine for once. I shut down my chromebook, try to start it again and get a black screen for 10 seconds, after which crouton shuts down. The error message is 

# **chronos@localhost / $ cat /etc/lsb-release**
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={FA5D6766-6B3C-47C8-84DD-6A322C311569}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={FA5D6766-6B3C-47C8-84DD-6A322C311569}
CHROMEOS_RELEASE_BOARD=falco-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=75
CHROMEOS_RELEASE_BUILD_NUMBER=6812
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=42
CHROMEOS_RELEASE_DESCRIPTION=6812.75.2 (Official Build) beta-channel falco 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=2
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=6812.75.2
GOOGLE_RELEASE=6812.75.2

# **(gnome)dexter@localhost:~$ croutonversion**
crouton: version 1-20150414182244~master:da478a77
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,chrome-beta,xorg,gnome-desktop,keyboard,chrome
host: version 6812.75.2 (Official Build) beta-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 19:00:14 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

# **chronos@localhost / $ sudo startgnome**
Entering /mnt/stateful_partition/crouton/chroots/gnome...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Apr 14 19:00:14 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=83f9ecad-5b56-0e42-8640-ea6363c8ac90/PARTNROFF=1 hashtree=PARTUUID=83f9ecad-5b56-0e42-8640-ea6363c8ac90/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=03b4c2c6d02fdbae790fbc9e900e9f807f609967 salt=3b6f2e86371794d43d071f1ab82e2d680ef138dab6a770102cfa3c7505c65fe7" noinitrd vt.global_cursor_default=0 kern_guid=83f9ecad-5b56-0e42-8640-ea6363c8ac90 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Apr 22 23:04:56 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
xf86: found device 0
xf86: found device 0
crouton: version 1-20150414182244~master:da478a77
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,chrome-beta,xorg,gnome-desktop,keyboard,chrome
host: version 6812.75.2 (Official Build) beta-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 19:00:14 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
(II) AIGLX: Suspending AIGLX clients for VT switch
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/gnome...

**Comment by fleminra** [comment]
I saw something like this, except I had been doing "enter-chroot -n trusty startx", and my black screen lasts for a couple minutes, and my error message is:

> /usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> 
waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.
> .
> /usr/bin/xinit: server error

What does work for me is invoking "xinit" but being sure to use "/usr/local/bin/xinit" instead of "/usr/bin/xinit". Also I use zsh as my default shell for user and root, so I might not be picking up any settings that crouton puts in "bash" startup files.

**Comment by nakulbende** [comment]
So is there no way I can run gnome on crouton?

**Comment by sprc** [comment]
Possibly related to #1680? I'd try the fix described therein and see if that does the trick.

**Comment by nakulbende** [comment]
Yes!! You guys are great! Thanks a lot!
