### ISSUE TITLE
Xiwi: clicking link crashes both OS

### ISSUE THREAD

**Issue by Dacit** [dnschneid/crouton#1661]
First of all, thanks for all the awesomeness in crouton and xiwi. But when I try to click a link in my xiwi window and the url is opened in a new chromeOs chrome tab (as supposed), both systems freeze. The only option is to force shutdown.
My machine is a Toshiba Chromebook 2, if this helps.
EDIT: Problem only occurs when using xfce as desktop environment.

**Comment by Skender** [comment]
I have the same issue on my HP Chromebook 11 with xfce.

**Comment by drinkcat** [comment]
Most likely obsolete.
