### ISSUE TITLE
Add Ubuntu 15.04 'Vivid Vervet' to ubuntu/releases

### ISSUE THREAD

**Issue by smibarber** [dnschneid/crouton#1662]
We need `vivid` in ubuntu/releases so we can start ~~testing~~breaking stuff.

**Comment by 1rocketdude** [comment]
pretty please. Looks to be some significant benefits over 14.04 (which has been rock solid for my Samsung 550C)

**Comment by DennisLfromGA** [comment]
I can't even get utopic to run right but maybe that's just me...

**Comment by jgw96** [comment]
Agreed, 15.04 has a ton of backend enhancements that bring Ubuntu up to a new level. Also i dont think this issue should have the bug badge, it deserves an enhancement badge.

**Comment by DennisLfromGA** [comment]
But it might be a buggy enhancement :)

On Sun, Apr 26, 2015 at 4:10 PM, Justin Willis <notifications@github.com>
wrote:

> Agreed, 15.04 has a ton of backend enhancements that bring Ubuntu up to a
> new level. Also i dont think this issue should have the bug badge, it
> deserves an enhancement badge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1662#issuecomment-96429580>.
>



-- 
*DennyL@GMail*

**Comment by jgw96** [comment]
Haha. I've heard 15.04 is actually pretty stable

**Comment by DennisLfromGA** [comment]
I hope it's better than utopic, I've had troubles with it.

On Sun, Apr 26, 2015 at 5:34 PM, Justin Willis <notifications@github.com>
wrote:

> Haha. I've heard 15.04 is actually pretty stable
>
> On Sun, Apr 26, 2015, 4:33 PM DennisL <notifications@github.com> wrote:
>
> > But it might be a buggy enhancement :)
> >
> > On Sun, Apr 26, 2015 at 4:10 PM, Justin Willis <notifications@github.com
> >
> > wrote:
> >
> > > Agreed, 15.04 has a ton of backend enhancements that bring Ubuntu up
> to a
> > > new level. Also i dont think this issue should have the bug badge, it
> > > deserves an enhancement badge.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/dnschneid/crouton/issues/1662#issuecomment-96429580
> > >.
> > >
> >
> >
> >
> > --
> > *DennyL@GMail*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dnschneid/crouton/issues/1662#issuecomment-96437082
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1662#issuecomment-96437130>.
>



-- 
*DennyL@GMail*

**Comment by tedm** [comment]
so what's involved in making a target? can one rename an existing target to vivid and point the ppas there?

**Comment by DennisLfromGA** [comment]
It's not a target, it's a release; they have to add it to `releases`.

On Sun, Apr 26, 2015 at 5:44 PM, tedm <notifications@github.com> wrote:

> so what's involved in making a target? can one rename an existing target
> to vivid and point the ppas there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1662#issuecomment-96438356>.
>



-- 
*DennyL@GMail*

**Comment by smibarber** [comment]
I hesitate to call adding a non-LTS Ubuntu release to crouton an "enhancement" because a lot of stuff will be broken, but I concede your point :)

This isn't a target; it's a release that just needs to be added to `installer/ubuntu/releases` at first. It'll need to be marked with a `*` since we haven't made any efforts to test crouton on `vivid` yet. That can probably be put into a one-line PR, hence the `pie` label.

After that's done, we need testing on `vivid` to see where things broke and need fixes, if workarounds from former releases (see the abhorrent workarounds for the `unity` target) still work, etc. Those should be tracked in separate issues, with names like `vivid: unity target needs X fixed`.

**Comment by tedm** [comment]
Thanks Dennis, so can one copy a release from say trusty to vivid and change some stuff? Or if it's harder than that, should the pie flag be attached to this issue?

**Comment by tedm** [comment]
@smibarber gotcha, so to do a PR for this, do I need to fork the branch here:

https://github.com/dnschneid/crouton/blob/b0a8c8d61e1d367ef9c625835c2e7067ee8e747f/installer/ubuntu/releases

(which would be a first for me)

and then add vivid* ??

**Comment by DennisLfromGA** [comment]
Ted, Take a look at [installer/ubuntu/releases](https://github.com/dnschneid/crouton/blob/master/installer/ubuntu/releases) that Stephen pointed out, it's simply a matter of adding the name 'vivid' to the end of the file with an asterisk and maybe a '| test' label.

**Comment by tedm** [comment]
@DennisLfromGA I did, I added vivid* |test below utopic, forked a branch, then clicked on Pull Request, but after that, it said I could just merge, so I did that too. I'm guessing anything that is green should be clicked on???

**Comment by DennisLfromGA** [comment]
@tedm - Oh wow, you did it now! :/ ( just kidding... ;)

**Comment by tedm** [comment]
@smibarber Did I do this right? If so, this can be closed.

**Comment by tedm** [comment]
@DennisLfromGA lol ;) ok, so what else needs fixing 'round here :+1:

**Comment by DennisLfromGA** [comment]
Good one ;-)
Take your pick - https://github.com/dnschneid/crouton/issues

On Sun, Apr 26, 2015 at 6:19 PM, tedm <notifications@github.com> wrote:

> @DennisLfromGA <https://github.com/DennisLfromGA> lol ;) ok, so what else
> needs fixing 'round here [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1662#issuecomment-96440110>.
>



-- 
*DennyL@GMail*

**Comment by DennisLfromGA** [comment]
@ted - Or start here -
> vivid: unity target needs widgetmaker5000 fixed

;-)

**Comment by tedm** [comment]
@DennisLfromGA lol, I ran this query: https://github.com/dnschneid/crouton/issues?utf8=%E2%9C%93&q=pie and most I've either fixed or am waiting for feedback, or they seem to be Intel cpu problems ;)

**Comment by DennisLfromGA** [comment]
You're the man!

On Sun, Apr 26, 2015 at 6:27 PM, tedm <notifications@github.com> wrote:

> @DennisLfromGA <https://github.com/DennisLfromGA> lol, I ran this query:
> https://github.com/dnschneid/crouton/issues?utf8=%E2%9C%93&q=pie and most
> I've either fixed or am waiting for feedback, or they seem to be Intel cpu
> problems ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1662#issuecomment-96440377>.
>



-- 
*DennyL@GMail*

**Comment by tedm** [comment]
@DennisLfromGA no seriously, I need to comprehend what these issues are first, and I'm sure most can probably be seen on the ARM. I think you explained the open issue for xfce in a window, which I just tested, so hopefully the OP will find that as a solution and close.
