### ISSUE TITLE
Colors in console output

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#1664]
I think we need to add colors to the console output.  Not because they're fancy, and pretty, and ooooooooh shiny...

...where was I?  Right, colors.  Really, we need colors so that the super-helpful crouton messages stand out from all the junk that's usually ignored.  Once you get past 3 or 4 lines of text everyone's eyes just glaze over and nobody notices crouton's error messages or whatever.

Color might help, or at least look nicer when being ignored.

In particular, we need red when installs or updates fail, so people don't think their chroots are up-to-date.

Tips might be nice in blue or green or whatever's visible but not too distracting.

**Comment by DennisLfromGA** [comment]
Yup, that'd be really helpful.
In this same vane (maybe), it would be handy to have a debug option that would `set -x` or something so you wouldn't have to instruct them on the use of `2>&1 | tee ~/Downloads/trusty-debug.log`

**Comment by DennisLfromGA** [comment]
And for extra bling:
```
    bold=$(     tput bold   || tput md      ) # Start bold
    stout=$(    tput smso   || tput so      ) # Start stand-out
    estout=$(   tput rmso   || tput se      ) # End stand-out
    under=$(    tput smul   || tput us      ) # Start underline
    eunder=$(   tput rmul   || tput ue      ) # End   underline
    italic=$(   tput sitm   || tput ZH      ) # Start italic
    eitalic=$(  tput ritm   || tput ZR      ) # End   italic
```

**Comment by tedm** [comment]
is this a pie?

**Comment by tonyxue** [comment]
@tedm Well, I'd rather say this is many pies :P

**Comment by DennisLfromGA** [comment]
@ted - Add red for cherry pie, green for apple pie, etc. ;)

**Comment by tedm** [comment]
@DennisLfromGA Thanks, but I looked at the related two issues, and I think there is some kind of color defined table in the works. Classic case of Rube Goldberg-ness ;)

**Comment by DennisLfromGA** [comment]
@tedm - Sorry, I was only attempting humor and failed I suppose - I wasn't being serious... ;)

**Comment by tedm** [comment]
@DennisLfromGA I get it! lol ;) Seeing all these colors coming, and being used to only black and white bash terminals, I've ordered a Toshiba FHD 13" Intel 4GB/16GB refurb from Groupon. Should be here mid-week.

**Comment by DennisLfromGA** [comment]
On Sun, May 31, 2015 at 5:04 PM, tedm <notifications@github.com> wrote:

> Toshiba FHD 13


​That looks like a really nice machine.​



-- 
*DennyL@GMail*

**Comment by tedm** [comment]
@DennisLfromGA We'll see. I had initially ruled it out because of the low cpu performance, but the groupon refurb deal is making it worth a try.
