### ISSUE TITLE
Pixel:lost Hotkey swap between Ubuntu and ChromeOS

### ISSUE THREAD

**Issue by roger77** [dnschneid/crouton#1668]
Since latest update I lost the ability to switch from/to Ubuntu from/to ChromeOS. Any idea what I should do? Thanks!

<code>
crouton: version 1-20150423153254~master:2f55723c
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,extension,unity,unity-desktop,xiwi,touch
host: version 6812.75.2 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 21:10:03 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
</code>

**Comment by DennisLfromGA** [comment]
I know this may seem obvious but have you tried to switch using Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward ?

**Comment by roger77** [comment]
Thanks a lot Dennis. I probably was using the old method without the shift key. The new config works.
