### ISSUE TITLE
Screen not responsive

### ISSUE THREAD

**Issue by szczys** [dnschneid/crouton#1670]
Hi all,

I just updated Crouton today and am experiencing the following issues:
* Open into Crouton and Trusty 
* Try to launch Guake -- part of window shows but not fully rendered
* Try to open xterm - window shows but typing doens't display, minimize and restore shows what was typed
* Similar problems with other windows (Chrome, etc.)

Could this be related to #477?

Note: I did follow this guide earlier to get Virtualbox working but have reverted that and associate this problem with the upgrade to crouton I performed while working through that process: https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-%28x86%29

Acer C720

Google Chrome	41.0.2272.102 (Official Build) 
Revision	00f0f7211cf494489f5046f4510733d61fe95663
Platform	6680.78.0 (Official Build) stable-channel peppy

crouton: version 1-20150423153254~master:2f55723c
release: trusty
architecture: amd64
targets: audio
host: version 6680.78.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Mar 20 15:40:08 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

**Comment by DennisLfromGA** [comment]
This doesn't sound exactly like your problem but I thought I'd mention -
I also use 'guake' and, sometimes when I first open it, it's not rendered correctly on the screen so I just exit and hit the launch key again and all is well.

**Comment by szczys** [comment]
Thanks @DennisLfromGA for that tidbit. This is definitely a bigger problem than just guake.

I had one other thought. I'm running Cinnamon desktop and perhaps this is causing the problem? Here's version information for that:

(cinnamon)mike@localhost ~ $ sudo apt-cache policy cinnamon
cinnamon:
  Installed: 2.4.5ubuntu2
  Candidate: 2.4.5ubuntu2
  Version table:
 *** 2.4.5ubuntu2 0
        500 http://ppa.launchpad.net/lestcape/cinnamon/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by DennisLfromGA** [comment]
I haven't run cinnamon since the target dried up and went away. I haven't tried any of the newer ppa's yet either so I can't be of much help I'm afraid.
[ I've got Linux Mint 17.1 loaded on /dev/sda7 so I'm good to go when I need a cinnamon fix. ;) ]

**Comment by szczys** [comment]
I'm going to assume this is my own fault and close the issue.
