### ISSUE TITLE
The default release should be xenial

### ISSUE THREAD

**Issue by frederic-parrenin** [dnschneid/crouton#1671]
I made several times the mistake to think that the default release was trusty, but it is actually still precise.
Is there a good reason for that? I do not see any reason to promote precise over trusty. There are both LTS releases but trusty is more up to date.

**Comment by weiHelloWorld** [comment]
Same here, I want to modify some default settings but I do not know where to start.

**Comment by DennisLfromGA** [comment]
It's easy to choose 'trusty' over 'precise', just enter '-r trusty' when
installing your chroot(s).

On Fri, May 1, 2015 at 6:34 PM, weiHelloWorld <notifications@github.com>
wrote:

> Same here, I want to modify some default settings but I do not know where
> to start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1671#issuecomment-98255991>.
>



-- 
*DennyL@GMail*

**Comment by sprc** [comment]
I'm guessing [this is the line](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L34) you'd want to change.

**Comment by dnschneid** [comment]
I'd like to do this, except #1351 prevents a good experience with Unity on ARM, which unfortunately seems to be a fairly large userbase.

**Comment by dnschneid** [comment]
Now that Gnome and Unity work on most platforms, I think the last bit will be to disable Unity on ARM on anything other than precise so people don't get caught in a hole.  #2833 implements the actual switch to xenial.

@drinkcat does anything else need to be done before flipping the switch?
