### ISSUE TITLE
Option to start xfce in a window

### ISSUE THREAD

**Issue by adamlofts** [dnschneid/crouton#1672]
The startxfce command starts xiwi in fullscreen mode. I would like an option to be able to start in a window.

The main reason for this is that going fullscreen causes problems when I have an external monitor plugged in. I would like to have linux in a window on the external monitor and chromeos on the pixel screen which I think would work fine if no attempt to go fullscreen is made.

**Comment by DennisLfromGA** [comment]
@adamlofts - Use `startxiwi` instead - `sudo startxiwi -b startxfce4`

**Comment by tedm** [comment]
@adamlofts @DennisLfromGA Dennis's suggestion works for me to start xfce in a window (I'm on ARM / precise / stable). If it works for you, feel free to close.

**Comment by adamlofts** [comment]
@DennisLfromGA @tedm Yes this command works for me. I was aware of the startwiwi command but did not realize it could be used like this to run a full desktop. Closing the issue. Thanks for the help.

**Comment by tedm** [comment]
@adamlofts Thanks for closing.

**Comment by dnschneid** [comment]
You can also use `sudo startxfce4 -X xiwi-window`, or even `sudo startxfce4 -X xiwi-tab` (with or without `-b`), although @DennisLfromGA's way is good too.

**Comment by DennisLfromGA** [comment]
@dnschneid - Wow, you sneaked in those other 'xmethods' ( https://github.com/dnschneid/crouton/commit/82d1ed1ef67353c238e3bf835a5984e91c9629f6 ) without me noticing them ;)
