### ISSUE TITLE
Screen flickering on Acer C910-54M1 after closing chroot

### ISSUE THREAD

**Issue by matneyx** [dnschneid/crouton#1676]
I'm running the most recent crouton on Trusty on an Acer C910-54M1 (Chromebook 15 with the i5) on the Stable channel.  Sometimes, but not always, when I log out of Trusty, my screen will start flickering any time I move the cursor. This happens any time I run a game from Steam (tried CaveStory+, Super Meat Boy, and Superbrothers: Sword and Sorcery).

I can't get the screen to stop flickering with the screen on -- it always returns to off -- and the only way I've been able to fix this has been to restart the laptop.

**Comment by ERR11CC** [comment]
I have this same problem.

**Comment by matneyx** [comment]
This just happened without me running games (or anything) -- at first, I could cycle between my chroot and Chrome OS and the flickering would go away, but eventually it took over.

Another interesting thing is what happens to my cursor -- it duplicates itself into 4 tiny arrows, and sometimes a large square of static (like an old TV) is below all 4.  Without Keyboard working (it's in /etc/crouton/targets, but doesn't actually work) I'm not sure I can take a screenshot of the cursor.

**Comment by rockybulwinkle** [comment]
I've been experiencing the same thing on an Acer Chromebook 15 CB5-571-C09S.  After switching between chromeos and ubuntu 14.04 trusty with gnome a few times (seemingly randomly), my cursor will turn to a static block, and after switching back and forth again it behaves as if it lost vsync and hsync on old monitors and flashes rapidly.  The whole system can be affected by it, including chromeos, ubuntu, login screen, etc, until a reboot.

**Comment by rockybulwinkle** [comment]
matneyx:  why did you close this issue?  Did you find a solution?

**Comment by rockybulwinkle** [comment]
Ok, I guess this is related to this issue: https://github.com/dnschneid/crouton/issues/1519

**Comment by matneyx** [comment]
@rockybulwinkle, I have not found a solution, but a few bandaids -- 1) if I use Ctrl+Alt+Shift+Forward to switch and it happens, I use Ctrl+Alt+Shift+Back to go back to Chrome OS and then Ctrl+Alt+Shift+Back to go to Trusty. (Like I move opposite whatever direction seemed to cause the problem).  2) If -that- doesn't work, I close the lid and log back into everything.  3) Finally, Power+Refresh will reboot your machine, if you can't get your screen to hold still long enough to log out.

**Comment by rockybulwinkle** [comment]
Did you check out the second post from issue #1519? As far as I can tell so far, it fixed it for me.

**Comment by ERR11CC** [comment]
It fixed it for me too. Wow! Thanks so much!

Date: Tue, 5 May 2015 09:37:13 -0700

**Comment by matneyx** [comment]
I have done what the second post says -- if you don't hear back from me, consider it fixed!
