### ISSUE TITLE
Have to press Ctrl+Alt+Shift+Back/Forward twice

### ISSUE THREAD

**Issue by Asuza** [dnschneid/crouton#1678]
After the latest Chrome OS update, crouton hasn't been working quite right.

Here is my current version info:
```
Version 42.0.2311.87 (64-bit)
Platform 6812.75.2 (Official Build) stable-channel swanky
Firmware Google_Swanky.5216.238.5
```
When switching between Chrome OS and my LXDE Debian (Jessie) install, I have to push the button combination twice.

If I'm in Linux and press Ctrl+Alt+Shift+Back, Chrome OS shows up but is completely unresponsive. If I press it again, the keyboard/mouse come back and everything is fine.

If I'm in Chrome OS and try to switch to Linux, the first time I push the buttons it "locks up" Chrome OS, then the second time it switches to Linux.

However, I've had a few times where I can no longer reliably switch between systems. Earlier today while trying to switch, the screen just went black and I rebooted in order to get back to what I was doing.

I updated crouton to see if it would fix the problem, but it didn't.

**Comment by Asuza** [comment]
I've been switching back and forth, and now it takes more button combination presses to switch between environments, and instead of Chrome OS appearing to be locked up, it goes straight to a black screen.

**Comment by penntaylor** [comment]
Same issue here, but I have other info: I like to re-map the chroot switching key combo to ctrl+esc since that's much easier to do with one hand. The line in /etc/crouton/xbindkeysrc.scm is `(xbindkey '(control Escape) "croutoncycle next")`. This used to work as expected to switch back and forth. Now it will only switch in one direction: from chroot back to Chrome OS. Once in Chrome OS, that key combo no longer does anything.
```
crouton: version 1-20150423153254~master:2f55723c
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,extension,gnome
host: version 6812.75.2 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Apr 14 20:43:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
```

**Comment by penntaylor** [comment]
The `mawk` process below, which seems to be started with the chroot, appears to be related to this issue. If I kill that process, I can no longer cycle into the chroot's desktop with ctrl+alt+shift+forward. 

It's a very long command. Much scrolling involved.
```
 mawk -W Interactive      function output(s) {         print s         fflush()     }          function update() {         c = lc || rc; s = ls || rs; a = la || ra         if (!cmd && c && s && a && p) {             cmd = "p"         } else if (!cmd && c && s && a && n) {             cmd = "n"         } else if (cmd && !c && !s && !a && !p && !n) {             system("/usr/local/bin/croutoncycle " cmd)             cmd = ""         }     }     $5 == 1 && $6 == 29   { lc = $7; update() }     $5 == 1 && $6 == 42  { ls = $7; update() }     $5 == 1 && $6 == 56    { la = $7; update() }     $5 == 1 && $6 == 97  { rc = $7; update() }     $5 == 1 && $6 == 54 { rs = $7; update() }     $5 == 1 && $6 == 100   { ra = $7; update() }     $5 == 1 && $6 == 59         {  p = $7; update() }     $5 == 1 && $6 == 60         {  n = $7; update() }
```

**Comment by ElSpecialisto** [comment]
Am having the exact same problem...now must hit the button combo twice to cycle between Chrome OS and the chroot desktop.  There seems to be a middle environment w/ a frozen Chrome OS screen between the two. 

I'm a bit of a novice and would love to hear any suggestions on how to get the button sequence back to normal / one press effectiveness.

**Comment by divx118** [comment]
I think you both experiencing #1475 I had this just before my device switched to freon. It is also a problem on "beta-channel parrot" see #1644

**Comment by 1rocketdude** [comment]
same problem here. Isn't a consistent thing. Sometimes multiple key combinations required. Sometimes I can't switch at all to Linux and have to clobber the running chroot

**Comment by penntaylor** [comment]
1rocketdude, head over to issue #1475 and try out my proposed solution towards the bottom of that thread. Post on that issue whether the change to croutoncycle works for your case.

**Comment by 1rocketdude** [comment]
I appreciate the heads up. I updated using crouton -r trusty -u and the problem appears fixed. Lots of magic going on that I'm not aware of.

crouton: version 1-20150430123324~master:90ad47ff
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde,audio,xorg,chrome
host: version 6812.83.0 (Official Build) stable-channel lumpy 
kernel: Linux localhost 3.4.0 #1 SMP Mon Apr 27 10:29:31 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

**Comment by Asuza** [comment]
I've updated again and continue to have the problem. However, a workaround that seems to be stable for me (so far) is...

To Linux: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F2</kbd> then <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F3</kbd>
To ChromeOS: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F1</kbd>

Hopefully it works as well for someone else.

**Comment by Asuza** [comment]
@dnschneid, would you please update this issue with a link to the issue it is a duplicate of?

**Comment by dnschneid** [comment]
Sorry, it's #1475

**Comment by gdm85** [comment]
@Asuza I have exact same problem, I think I got it with last ChromeOS update. The "middle" VT that I see with Ctrl+Alt+F2 is the one from where I entered the chroot & started xfce4. It would be best to switch directly to the chroot display, also because brightness gets messed up

**Comment by victorel-petrovich** [comment]
Same here, arm samsung chromebook, not freon

debian jessie + lxde or + xfce, both without or with crouton integration extension installed (i.e, before, and after adding target `xiwi`).

Before updating with `-t xiwi`, it showed `xmethod xephyr`

Will try 1475.
