### ISSUE TITLE
gnome-control-center crashes when clicking on "region and languages"

### ISSUE THREAD

**Issue by frederic-parrenin** [dnschneid/crouton#1679]
I installed crouton on my acer C720P.(upgraded with a 128 Gb SSD).
However, when I go to gnome-control-center and click on "region and languages", I got a crash with the following error message:

(gnome-control-center.real:3113): common-cc-panel-CRITICAL **: gdm_get_language_from_name: assertion '*name != '\0'' failed
Segmentation fault (core dumped)

**Comment by DennisLfromGA** [comment]
Looks to me like a problem with gnome similar to this one ( https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1245140 ), not crouton.

**Comment by frederic-parrenin** [comment]
Hmm, not sure it is the same.
My error message refers to gdm.

**Comment by DennisLfromGA** [comment]
No, it's not the same - but similar, and probably nothing to do with crouton.

**Comment by jasonjwells** [comment]
On C720p running crouton Trusty using GNOME Shell 
 
gnome-control-center

(gnome-control-center.real:15699): common-cc-panel-CRITICAL **: gdm_get_language_from_name: assertion '*name != '\0'' failed
Segmentation fault (core dumped)

Any suggestions>

**Comment by yhlam** [comment]
I have the same issue after I reinstall the trusty chroot today. Looks like it is because LANG is not set. It is fixed after I run "localectl set-locale LANG=en_US.utf8" and re-login.

**Comment by dnschneid** [comment]
Looks like another vote for #1680 then.
