### ISSUE TITLE
Xinit errors when starting KDE.

### ISSUE THREAD

**Issue by ajshell1** [dnschneid/crouton#1681]
I currently have my chroot on a 1TB external hard drive. In the past, I was able to start it with "sudo sh /media/removable/wd/bin/enter-chroot" followed by "xinit /usr/bin/startkde".  However, today, I tried that and it didn't work. First off, when I entered the first line, it returned with 

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

```
#1) Respect the privacy of others.
#2) Think before you type.
#3) With great power comes great responsibility.
```

Entering /media/removable/wd/chroots/trusty...
Unknown username "whoopsie" in message bus configuration file

I see the "entering /media/... configuration file" part when I enter the command normally, but the first part definitely hasn't appeared before.
Then, when I enter the second command, I get a really long message. You can find it [here](http://pastebin.com/TthsEetS. Following this, I don't enter the chroot. I just stay on the command line.
Also, my Chrome OS desktop looks slightly different. Instead of nine squares on the bottom left, there's a magnifying glass.
I have a lot of steam games downloaded onto this hard drive, so I really don't want to have to re-download anything.

**Comment by Tuxerito** [comment]
Maybe this help https://github.com/dnschneid/crouton/issues/845

If you have access to your Chroot in console mode you can copy Steam folder to another partition.

**Comment by divx118** [comment]
@ajshell1 You should update your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting
