### ISSUE TITLE
Sid lxde install fails, missing libc6:i386

### ISSUE THREAD

**Issue by TechnicalFox** [dnschneid/crouton#1682]
The following packages have unmet dependencies:
 libasound2:i386 : Depends: libc6:i386 (>= 2.16) but it is not going to be installed
 libspeexdsp1:i386 : Depends: libc6:i386 (>= 2.3.4) but it is not going to be installed

I have performed a powerwash and a recent download of the crouton installer. This is on an Acer c720.

**Comment by TechnicalFox** [comment]
Jessie lxde install completed sucessfully and is working...

**Comment by TechnicalFox** [comment]
Now I get this when installing sid:

Setting up python-minimal (2.7.9-1) ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
dpkg: error processing package python-minimal (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 python-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.

**Comment by TechnicalFox** [comment]
Changing sources.list in jessie to sid repo and running update, upgrade, then dist-upgrade worked... Still no idea why the installer can no longer directly install sid on my machine.

**Comment by jdfight** [comment]
I can confirm the same issue here...  Installing/Updating sid no longer seems to work through the crouton script:

Error:

```
The following packages have unmet dependencies:
 libc6-dev:i386 : Depends: linux-libc-dev:i386 but it is not going to be installed
```

My chromebook is 64bit - shouldn't it be installing linux-libc-dev:amd64 instead?  Is this some sort of multiarch issue?

Installing Jessie and changing apt source to Sid does seem to work.   Will this cause any issues with my chroot if I need to run any future crouton updates?

**Comment by Asdas91** [comment]
I have got exactly the same issue. Another problem is that I updated ChromeOS and now I need to update Sid, otherwise it won't run.

**Comment by jdfight** [comment]
Looks like the issue is explained in greater detail here:

https://github.com/dnschneid/crouton/issues/1843

I am currently running Jessie without any hitches - So i will probably just stick with it!
