### ISSUE TITLE
cannot update chroot after updating ChromeOS

### ISSUE THREAD

**Issue by yaup** [dnschneid/crouton#1683]
I updated to chrome os version 42.0.2311.87 yesterday, and was not able to run `sudo startunity`. I downloaded a fresh copy of crouton and followed the update instructions, but got these errors:

```
Compiling CRAS (i386)...
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

upon trying to launch unity again, it tells me the chroot may not be fully setup, and asks me if I want to finish the setup. I say yes, and end up with this error AFTER the previous error is repeated.

```
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

I am, able to run `sudo enter-chroot` and see all my stuff inside a terminal interface, but cannot connect to an X server from there. 

my chroot version output is this:

```
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150423153254~master:2f55723c
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 6812.75.2 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 18:57:27 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
```

Should I just wait for an update sometime to fix this (in response to the chrome os update) or is there something I can do now?

**Comment by giliammc** [comment]
i have the same issue something needs to be done

**Comment by yaup** [comment]
I did some googling around for a few days, and it seems like that same error shows up when people try to compile 32 bit code using a 64 bit compiler, or it's some sort of linking issue? Suggestions I found were either relink the files (which i think is the cannot find -lgcc) or install a 32 bit compiler(which is the incompatibility issue), which I have NO idea how to do in crosh shell. 

Of course maybe it's something completely different, but those are what I've found.

**Comment by yaup** [comment]
@giliammc  I figured it out. 

I had updated my gcc version to 4.8.3 but the default in precise is 4.6.4. Not sure exactly how the crouton script works, but the after I downgraded gcc back to 4.6.4, everything compiles and I am able to launch unity again.

**Comment by tedm** [comment]
@yaup that is interesting.
