### ISSUE TITLE
Fatal server error after ChromeOS update?

### ISSUE THREAD

**Issue by limestorm** [dnschneid/crouton#1684]
I have been running Trusty alongside Chrome OS for a few months now, and it was working fine until today. However, I updated Chrome OS last night before I went to sleep, and today I get this error message:

```
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
```

Any help would be greatly appreciated, as I have very important files on that Chroot that I really need for school. A screenshot of the error is available here: https://drive.google.com/file/d/0Byd1ooX4kAo1YnFsa3E1YWhCT3M/view?usp=sharing

Thanks sooooo much!

**Comment by DennisLfromGA** [comment]
It's a good idea to update crouton and your chroot after a Chrome OS update.
Follow this guide: https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by limestorm** [comment]
@DennisLfromGA Thank you! Can't believe I didn't think of doing that...

**Comment by DennisLfromGA** [comment]
No problem, I've been there too many times.
I think [this post](http://goo.gl/pl9YeG) should be written in stone ;o)

**Comment by giliammc** [comment]
i updated it and i still have the same issue

**Comment by v1j4y** [comment]
reporting same issue, updating doesn't resolve the issue.
