### ISSUE TITLE
Edit / partition

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1685]
I would like to edit the size of the root partition but cannot inside of the chroot because it is mounted. I need at least 8 GB to complete LFS (linux from scratch) and `/dev/sda`'s biggest unallowacated space is 64 MB. How would I go about resizing the partition?

**Comment by DennisLfromGA** [comment]
Very carefully ;)

If you have a Chromebook with SeaBIOS and can boot via <kbd>Ctrl+L</kbd>, then you could boot an alternate OS and fire-up `gparted` or something similar. Be forewarned that just about any time you touch the stateful_partiton (/dev/sda1) it's gon'na do a 'powerwash'.

**Comment by DennisLfromGA** [comment]
@drinkcat has a '[separate partition branch](https://github.com/dnschneid/crouton/pull/706)' that we used in the past to create a CROUTON partiton (/dev/sda13) that was a savior but it hasn't been updated in a while and I believe it's currently 'broken' with the advent of freon and the removal of vt's. If your Chromebook hasn't move to 'freon' yet, it may still work for you but *please be careful* and have backups - to include a 'usb restore' stick.
