### ISSUE TITLE
"xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)"

### ISSUE THREAD

**Issue by jcharris** [dnschneid/crouton#1686]
I apologize if this is a duplicate issue, but I have not seen this particular error in the list yet.  After a recent reboot, at which point ChromeOS updated itself, it was not possible to startup as normal.  After following the update process at <https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting>, I obtain seemingly good news:

...
> You can start Xfce via the startxfce4 host command: sudo startxfce4
> 
> Unmounting /mnt/stateful_partition/crouton/chroots/debian...
> Done! You can enter the chroot using enter-chroot.

At which point, if I start like normal with "sudo startxfce4", I get bad news, which ends with:

...
> Build Date: 09 February 2015  09:46:52AM
> xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau <jcristau@debian.org>) 
> Current version of pixman: 0.26.0
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Apr 29 11:23:52 2015
> (==) Using config directory: "/etc/X11/xorg.conf.d"
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> 
> Fatal server error:
> xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
> 
> 
> Please consult the The X.Org Foundation support 
>          at http://wiki.x.org
>  for help. 
> Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
> 
> Server terminated with error (1). Closing log file.
> /usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> /usr/bin/xinit: server error
> Unmounting /mnt/stateful_partition/crouton/chroots/debian...

I can, however, start things on the command-line, via "sudo enter-chroot" -- and then if I want to do anything on the command line, I can.  However I cannot run startxfce or startx from there -- I either get the same error as before, or if I think to run with sudo, I get "Do not launch startxfce4 as root inside the chroot."

Finally, the beginning of the error before, I see the message "_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root", but if I make this change, it changes nothing.

As per instructions, the output of version number is:

> chronos@localhost / $ sudo enter-chroot -n debian croutonversion
> Entering /mnt/stateful_partition/crouton/chroots/debian...
> crouton: version 1-20150428153647~master:6ae56c3d
> release: wheezy
> architecture: amd64
> xmethod: xorg
> targets: xfce
> host: version 6812.75.2 (Official Build) stable-channel peppy 
> kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 18:57:27 PDT 2015 x86_64 GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/debian...

**Comment by DennisLfromGA** [comment]
It's a good idea to update crouton and your chroot after a Chrome OS update.
Follow this guide: https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by griley4** [comment]
Hi @jcharris 

I have the exact same issue as you.  I am using debian wheezy and lxde.
i prefer to use the x11 setup of crouton for working, i tried out the new xiwi and extension, it worked as intended as far as integration with chromeOS is concerned, but some X forwarding issues, similar to the ones mentioned here #1276 made it non-ideal. i updated crouton and the chroot with by following the instructions  https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting with no obvious errors, then followed @dnschneid's instructions from #1276.

    sudo sh -e Downloads/crouton -u -n wheezy -t x11

and discovered this problem after trying to run

    sudo startlxde

i didn't see any obvious errors in the x11 target update.
I tried all the same things you did and got the same outputs, with the additional test of starting the chroot in command line and running sudo startx. the output of which is at the bottom.

Here's my croutonversion output

    chronos@localhost ~ $ sudo enter-chroot -n wheezy croutonversion
    Entering /mnt/stateful_partition/crouton/chroots/wheezy...
    -su: 1: [: -ne: unexpected operator
    -su: 1: [: -ne: unexpected operator 
    -su: 1: [: -ne: unexpected operator
    -su: 1: [: -ne: unexpected operator
    crouton: version 1-20150428153647~master:6ae56c3d
    release: wheezy
    architecture: amd64
    xmethod: xorg
    targets: x11,xiwi,extension,lxde,keyboard
    host: version 6812.83.0 (Official Build) stable-channel peppy  
    kernel: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:37:50 PDT 2015 x86_64 GNU/Linux
    freon: yes
    Unmounting /mnt/stateful_partition/crouton/chroots/wheezy...
    Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/wheezy...

output from running sudo startx inside the chroot
    
    sudo startx



    X.Org X Server 1.12.4
    Release Date: 2012-08-27
    X Protocol Version 11, Revision 0 
    Build Operating System: Linux 3.16-2-amd64 x86_64 Debian
    Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:37:50 PDT 2015 x86_64
    Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=deb49c04-b750 1245-8f74-7cf90461f255/PARTNROFF=1 hashtree=PARTUUID=deb49c04-b750-1245-8f74 7cf90461f255/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=19983e99694f43f58c9b7fe794a36276d6631a9b salt=c1f66bbcb95439a8ee2d0617298166203029c4b74e1da8c2eb976c10a5fbe491" noinitrd vt.global_cursor_default=0 kern_guid=deb49c04-b750-1245-8f74-7cf90461f255 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
    Build Date: 09 December 2014  09:12:48PM
    xorg-server 2:1.12.4-6+deb7u5 (Moritz Muehlenhoff <jmm@debian.org>) 
    Current version of pixman: 0.26.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
    Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Apr 29 15:12:57 2015
    (==) Using system config directory "/usr/share/X11/xorg.conf.d"

    Fatal server error:
    no screens found

    Please consult the The X.Org Foundation support 
         at http://wiki.x.org
     for help. 
     Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

    Server terminated with error (1). Closing log file.

**Comment by divx118** [comment]
@griley4 You will be experiencing https://github.com/dnschneid/crouton/issues/1505 xiwi is the only option for you at the moment. AFAIK kali and wheezy have this problem. jessie I still need to test.

**Comment by griley4** [comment]
Thank you for the prompt reply, i will stick with xiwi for now and keep my eyes on this issue and #1505 for updates

**Comment by jcharris** [comment]
@DennisLfromGA If you re-read, you'll see that following the update procedure was the first thing that I did (and how I knew to post here).  In fact, I ran the update procedure multiple times just to be sure.

@divx118 If I understand you correctly, one option might be to upgrade from wheezy to jessie?  At this point I'm open to anything; if I can't resolve it in a few days, I'll probably just copy my home directory off, scrap the whole thing and start over.  If I can get X windows back without doing this, though, I'd be happy, since it took a little while to tweak all of the settings for how I like it.

**Comment by DennisLfromGA** [comment]
@jcharris - You're right, I guess I just glossed over that part.
I'll butt out and let the heavies in here help you out - sorry :/

**Comment by divx118** [comment]
@jcharris Yes, upgrading it to jessie should work.

**Comment by jcharris** [comment]
I am not sure that it is a good solution, but I can verify that it "works".  I first had to delete over a GB of files to avoid running out of memory to perform the upgrade, and afterwards the error messages remain (in fact, more are created... see below).

I would recommend that if no better solution can be found, that for someone in a similar position to simply save their files, delete the chroot, and start over.

> chronos@localhost / $ sudo startxfce4 
Entering /mnt/stateful_partition/crouton/chroots/debian...
/usr/bin/startxfce4: Starting X server

> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

> X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:37:50 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=1b6e61fc-e530-0e4a-8580-ad5f0b741d23/PARTNROFF=1 hashtree=PARTUUID=1b6e61fc-e530-0e4a-8580-ad5f0b741d23/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=19983e99694f43f58c9b7fe794a36276d6631a9b salt=c1f66bbcb95439a8ee2d0617298166203029c4b74e1da8c2eb976c10a5fbe491" noinitrd vt.global_cursor_default=0 kern_guid=1b6e61fc-e530-0e4a-8580-ad5f0b741d23 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 11 February 2015  12:32:02AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon May 11 13:15:49 2015
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
xf86: found device 0
crouton: version 1-20150503215233~master:75fb08cb
release: jessie
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6812.83.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:37:50 PDT 2015 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root

> (xfce4-session:24369): xfce4-session-WARNING **: Unable to launch "xfce4-settings-helper": Failed to execute child process "xfce4-settings-helper" (No such file or directory)

> (xfce4-session:24369): xfce4-session-WARNING **: Unable to launch "xfce4-settings-helper": Failed to execute child process "xfce4-settings-helper" (No such file or directory)
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

> (xfdesktop:24385): GLib-GIO-CRITICAL **: g_file_get_path: assertion 'G_IS_FILE (file)' failed

> (xfdesktop:24385): GLib-GIO-CRITICAL **: g_file_get_path: assertion 'G_IS_FILE (file)' failed

> (xfdesktop:24385): GLib-GIO-CRITICAL **: g_file_get_path: assertion 'G_IS_FILE (file)' failed

> (xfdesktop:24385): GLib-GIO-CRITICAL **: g_file_get_path: assertion 'G_IS_FILE (file)' failed
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch

**Comment by divx118** [comment]
@jcharris Those errors can be ignored. However I agree, I would prefer creating a new chroot instead of upgrading a distro.
