### ISSUE TITLE
cant restore

### ISSUE THREAD

**Issue by giliammc** [dnschneid/crouton#1688]
i updated my acer c720 and tried to relaunch my chroot (i am using the xiwi target) and it didnt work so i tried to restore it to a backup file and got this error mesage
![screenshot 2015-04-29 at 2 39 11 pm](https://cloud.githubusercontent.com/assets/10850574/7399759/94cef9f0-ee7d-11e4-82d1-e9ea2a0c9173.png)

so i deleted the chroot updated crouton and tried again and got the same mesage

**Comment by DennisLfromGA** [comment]
That doesn't look good. :/ 

Did your backup complete without errors?
Did you possibly copy the backup file back to the Chromebook and the copy had errors?

BTW, you don't need the `-r trusty` option, crouton figures that out from the tar file.

**Comment by giliammc** [comment]
i have restored to this backup before with no errors

**Comment by DennisLfromGA** [comment]
> i have restored to this backup before with no errors

Do you mean you have restored *from* that backup before?
If that's the case, just try: `tar -tvaf ~/Downloads/trusty-20150324-1242.tar.gz` and see if you get any errors. If no errors, I'd try it again.
You could also try to uncompress it first using: `gzip -d ~/Downloads/trusty-20150324-1242.tar.gz` and see if that completes without error, then just untar it.

**Comment by giliammc** [comment]
i was able to get it to restore but now when i try to run sudo startxfce4
i get 
![screenshot 2015-04-29 at 6 24 02 pm](https://cloud.githubusercontent.com/assets/10850574/7403622/fcf88310-ee9c-11e4-9a1b-a969b5279d52.png)

**Comment by DennisLfromGA** [comment]
Now you just need to update [crouton](https://goo.gl/fd3zc) and your [chroot](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting).

**Comment by giliammc** [comment]
I tried that and got the same error

**Comment by DennisLfromGA** [comment]
@giliammc - What does `sudo edit-chroot -al` show?

**Comment by giliammc** [comment]
![screenshot 2015-05-01 at 2 27 31 pm](https://cloud.githubusercontent.com/assets/10850574/7435958/3e2b3ba8-f00e-11e4-945a-4adc8f6330b5.png)

**Comment by DennisLfromGA** [comment]
@giliammc - 
> I tried that and got the same error

So you updated crouton and your chroot and 'got the same error' as when you attempted the restore??? That's strange indeed.

Both the 'trusty' and 'utopic' chroots appear to have problems. Maybe the backup files are partially corrupt or the restore process didn't complete successfully. You could try to fix them again with a crouton update, other than that I don't know...

**Comment by tedm** [comment]
@giliammc since you have multiple chroots, you may want to use sudo startxfce with the -n parameter, it looks like you have two trusty chroots, one named trusty, and one named trustyer, probably a good ideal to name them with unique letters.

**Comment by giliammc** [comment]
the trustyer and the utopic chroots are just ones that i created to try to find out what the problem was 
the trustyer is trusty with xfce and no xiwi and it works fine 
the utopic one didn't even finish the install

**Comment by tedm** [comment]
OK, that's fine, then you must already be using -n, because by default sudo startxfce4 would try to start the one named trusty (comes earlier in the alphabet).

**Comment by giliammc** [comment]
yup the one i am trying to fix is the "trusty" one

**Comment by giliammc** [comment]
sorry for the bad grammar i started typing that and had to leave the room came back finished typing it and didn't read through it

**Comment by giliammc** [comment]
i got it working by removing the packages that could not be verified
