### ISSUE TITLE
Not able to switch Between ChromeOS and Ubuntu

### ISSUE THREAD

**Issue by Koalaman1** [dnschneid/crouton#1691]
So i installed Ubuntu Trusty with sudo CROUTON_BRANCH=x11_freon sh ~/Downloads/crouton -r trusty-t untiy and it installed fine but then when i run it it will run but ctrl+alt+[<-] (F1) will not switch me back the only way to get back to chrome is to restart it

**Comment by natevw** [comment]
I'm seeing something like this now too, on an older Crouton install which used to allow switching. You should be able to get back to Chrome by logging out of any window manager though.

**Comment by natevw** [comment]
I tried updating via `sudo sh ~/Downloads/crouton -n trusty -u` and still same thing: `sudo startxfce4` takes over the "Chrome" side of the virtual terminal switch until I log out.

**Comment by 1rocketdude** [comment]
I began seeing the same problem after last ChromeOS update. Switching to ChromeOS worked, but switching back to ubuntu was problematic - it worked after some seemingly random combination of shift, ctrl, right arrow.

**Comment by epilnivek** [comment]
Also seeing the same issue after the ChromeOS update. X wouldn't start until I updated via `sudo sh ~/Downloads/crouton -n trusty -t unity,extension,chrome -u`  and then I could get Unity to launch again. 

Now when I run `sudo startunity` I'm automatically switched to Unity and the old keyboard shortcut to take me back and forth doesn't work. I have to log out to get back to the ChromeOS shell.

**Comment by Koalaman1** [comment]
when you say logout do you mean shutdown

**Comment by unix1** [comment]
I also experienced similar symptoms after the latest ChromeOS update - i.e. I had to update crouton per readme instructions and the old keyboard combinations to switch between ChromeOS and Ubuntu didn't work.

But, for me `[ctrl]-[alt]-[shift]-[left-arrow/F1]` and `[ctrl]-[alt]-[shift]-[right-arrow/F2]` work fine instead. One thing I noticed is that after switching to ChromeOS, the mouse pointer will not work until I hit another key or touch the screen, but that's not a big deal at all.

**Comment by Koalaman1** [comment]
unix1 thanks that worked for me

**Comment by epilnivek** [comment]
@unix1 That worked for me, too. Thanks. Seems like this most recent ChromeOS update was a pretty major one if it broke this many peoples' crouton installations.

**Comment by darcyparker** [comment]
This issue isn't just ubuntu. 

I am having the same issue with my crouton `stretch` (debian - testing) crouton chroot.   I tried the key strokes suggested by @unix1, but unfortunately they don't work either.  I have my ctrl and search keys swapped... so I tried different combinations... and I also tried putting my keys back (ctrl==ctrl and search==search).  but this didn't help either.

I downloaded the latest crouton.sh, deleted and built a new chroot from scratch... and that didn't help either.

It seems the only workaround is to restart my chromebook.

Has a bug been filed with ChromeOS?

**Comment by darcyparker** [comment]
I read some other tickets like this one... and given it is so common, I tried changing from `stable` to `beta` channel for ChromeOS.  After updating to beta, things are working now.  The key stroke behavior is different.... but I figured it out.  `ctrl-alt-shift-forward` switches you into chroot after you press and release.  It used to be `ctrl-alt-forward` to get into VT-2, then `ctrl-alt-refresh` to get into VT-3.  I like the new behaviour because it cuts one key stroke...) 

I now wonder how to get to VT-8 and VT-2 if needed....

**Comment by chrism2671** [comment]
Any idea what it's supposed to be with an Apple wired keyboard plugged in?

**Comment by darcyparker** [comment]
@chrism2671 - I am not sure... but you might be able to work out what keystrokes your apple keyboard is sending to Chromebook by using the keyboard overlay app. <kbd>ctrl</kbd><kbd>alt</kbd><kbd>/</kbd>.  Once you get this up, you can press keys and see visually what is being triggered in ChromeOS.  Just a thought...

**Comment by dnschneid** [comment]
I think it's ctrl+alt+shift+function+f1/f2...anyway, looks like this bug should be closed.

**Comment by raj321321** [comment]
I am in Asus CN60 chromebox.
While in Chrome OS , press CTRL+ALT+T  
in the prompt, type 'shell' [without inverted commas]
type 'sudo startxfce4'

**Comment by DennisLfromGA** [comment]
@raj321321,

If you are trying to describe an issue, this is the wrong place.
Please open a **[New issue](https://github.com/dnschneid/crouton/issues/new)** and complete the form.

-**DennisL**

**Comment by abc123me** [comment]
I found a fix to switch between (for me at least) in your chroot's terminal type "croutoncycle cros" to get to crome os and to get back just use ctrl+alt+shift+f1

**Comment by kanner** [comment]
@abc123me: For me this is also the only way that works (dell chromebook 11)

**Comment by k1ypp** [comment]
I posted the following on another topic in this forum, but haven't seen any responses in a couple of days. I thought I would try again:

I too am suffering this problem with switching the OS from Chrome to Linux KDE and back. Yes, I am including the shift key. It was working and then just stopped. Being a newbie I'm not certain I know how to "test M58." How does one try that?

chronos@localhost / $ sudo edit-chroot -all
Password:
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20170315143304~master:95589555
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,unity,kde
host: version 9334.58.0 (Official Build) stable-channel winky
kernel: Linux localhost 4.4.44-07356-g3b524e9 #1 SMP PREEMPT Wed Apr 26 12:20:16 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Update: I should add that I'm using a Chromebook 2, Samsung, XE500C12-K01US. Up until recently this function, changing OS systems, did work without problems.

Additional information: If I start a Linux KDE session in Crouton and don't do anything (for example, start an app, such as notebook or something) I AM able to use the Alt-CTRL-Shift---> function to switch back to Chrome. Once I do anything, such as change the panel size at the bottom of the screen, then the function fails.

**Comment by julianoleary** [comment]
I'm running chrome OS currently, and I'm trying to get into ubuntu which I installed through crouton. Today I noticed that ctrl+alt+shift+foreward/backward wasn't working to get into Ubuntu. What is happening here? Did ubuntu or crouton uninstall or need an update after a few weeks of non-use? Are there any other ways to switch between operating systems other than a keyboard shortcut? Thanks

**Comment by DennisLfromGA** [comment]
@julianoleary,

This issue was opened when 'freon' was being introduced (`CROUTON_BRANCH=x11_freon`), it was merged a few years ago and is now used on all devices.

You didn't show us the output of `sudo edit-chroot -all` so we don't have all the details we need to properly troubleshoot your issue but I'll try anyway.

> Today I noticed that ctrl+alt+shift+foreward/backward wasn't working to get into Ubuntu.  
What is happening here? 

If you installed just the 'xorg' xmethod then 'ctrl+alt+shift+foreward/backward' should still work for you.
If you installed the 'xiwi' xmethod along with the ['crouton integration']() extension then you should *also* be able to switch into your chroot by using the extensions's drop-down menu on the address bar, see below -

![screenshot 2018-02-17 at 12 37 07 pm](https://user-images.githubusercontent.com/3418772/36343851-57c3d596-13df-11e8-8a7d-0b863275c955.png)

> Did ubuntu or crouton uninstall or need an update after a few weeks of non-use?

It's possible that Ubuntu, crouton, and CrOS all updated in that time, that's why it's a good idea to do a crouton update to help keep everything in sync.

> Are there any other ways to switch between operating systems other than a keyboard shortcut?

Yes, from inside your chroot(s) you can use the command-line along with `croutoncycle` to switch to CrOS and/or other chroots. See the usage below -
```
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by Coolgithubuser9** [comment]
09i
