### ISSUE TITLE
Can't start xfce from VT2 after Chrome OS update

### ISSUE THREAD

**Issue by alaimacerc** [dnschneid/crouton#1692]
After the latest Chrome OS (Stable channel) update, and updating my chroot (LTS precise) in a crosh tab, which still works fine, I don't see to be able to run xfce from VT2.  Specifically, when I switch from Chrome OS with the arrow keys I get a banner saying:

"Welcome to frecon!
[...]
Developer Console
[...]
To use this console, the developer mode switch must be engaged."

And on logging in, and running "sudo startxfce4", I get a:

"Xorg X11 servers cannot be launched from Frecon."

So...  has the update somehow switched VT2 from another console to frecon?  And how would I switch that back?  (In which case perhaps this isn't a crouton issue at all, but all pointers gratefully received!)  Or am I entirely confused as to what's going on?

**Comment by DennisLfromGA** [comment]
You'll have to get the details from the experts but 'frecon' doesn't use vt's but the crouton authors have done some slick manipulation to keep xorg alive all the while adding another very cool alternative called xiwi. 
Using vt2 was never really promoted, instead they encouraged everyone to login with their Google credentials and open a cros shell.

**Comment by alaimacerc** [comment]
Thanks for the reply, Dennis!  I thought running X through a console/switch of VTs _was_ the recommended method?  Maybe that's changed since I started using it!  What's the suggested method now?  I can't simply do "startxfce4" from a tabbed chrosh, can I?

Looking at xiwi, the idea is that instead of "desktop" switching, it all happens inside a browser tab?  Will have to look at this more closely when I'm more awake.

**Comment by DennisLfromGA** [comment]
@alaimacerc - 
The suggested method is to login to your Google account, open a cros shell using a tab <kbd>Ctrl+Alt+T</kbd> or via the [Crosh Window](https://chrome.google.com/webstore/detail/crosh-window/nhbmpbdladcchdhkemlojfjdknjadhmh?utm_source=chrome-app-launcher-info-dialog) extension (which also requires [Secure Shell](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?utm_source=chrome-app-launcher-info-dialog)), entering `shell` and then starting your chroot via `enter-chroot` or one of the `start*` scripts.
The crouton scripts have to be run as root *outside* of your chroot(s) so a typical session would start like this: `sudo enter-chroot -n trusty` or `sudo startxfce4 -n trusty`.
Again, this is just an example, there are more targets/desktops, xmethods, and options available that allow you to customize your experience.

**Comment by alaimacerc** [comment]
Thanks again Dennis;  the key part of that I was missing last night was that while I could indeed run xfce from a tabbed chrosh, I didn't get that it was still possible to "switch"...  just now needing a different four-fingered death-strike key combo.  Will have to keep more on top of the crouton update news to try to avoid such nasty surprises in future...

**Comment by tedm** [comment]
@alaimacerc try alt tab to switch, or alternatively, you can launch the chroots in their own windows non tabbed, but you should still be able to cycle through them with alt tab
