### ISSUE TITLE
Can't update chroot

### ISSUE THREAD

**Issue by andrewmoise** [dnschneid/crouton#1695]
I'm trying to deal with the "can't start X after ChromeOS update", and I'm hampered because it seems I can't update my chroot:

    chronos@localhost ~/src $ sudo sh -e ~/Downloads/crouton -n jessie -u
    /usr/local/chroots/jessie already exists; updating it...
    Enter encryption passphrase for jessie: 
    Unable to determine the release in /usr/local/chroots/jessie. Please specify it with -r.
    chronos@localhost ~/Downloads $ sudo sh -e ~/Downloads/crouton -n jessie -r jessie -u
    /usr/local/chroots/jessie already exists; updating it...
    Enter encryption passphrase for jessie: 
    Release doesn't match! Please correct the -r option, or specify a second -u to change the release, upgrading the chroot (dangerous).

This is and always has been a jessie chroot; I'm not sure why the installer wouldn't see that (maybe because jessie is released now and is no longer "testing"?):

    chronos@localhost ~/Downloads $ sudo edit-chroot -l jessie
    name: jessie
    encrypted: yes, unlocked
    Enter encryption passphrase for jessie: 
    Entering /mnt/stateful_partition/crouton/chroots/jessie...
    crouton: version 1-20141208100324~master:7b8ffff0
    release: jessie
    architecture: amd64
    targets: x11
    host: version 6812.75.2 (Official Build) stable-channel wolf 
    Unmounting /mnt/stateful_partition/crouton/chroots/jessie...
    chronos@localhost ~/Downloads $ sudo sh -e ~/Downloads/crouton -V
    crouton: version 1-20150428153647~master:6ae56c3d

Thanks in advance for your help.

**Comment by andrewmoise** [comment]
Now I tried again using the master git revision, and this particular problem is fixed. A bug report on the new problem is forthcoming. :-)

**Comment by dahveed** [comment]
What do you mean by "master git revision?" I have this same problem of trying to update crouton but can't. I've posted here ( https://github.com/dnschneid/crouton/issues/2174 ) but haven't gotten a reply yet.
