### ISSUE TITLE
removable media permission wrong in chroot; duplicate mount points?

### ISSUE THREAD

**Issue by MarcSabatella** [dnschneid/crouton#1697]
Hello!  I have been using crouton very happily since fall - thanks so much for this wonderful tool.

I have the chroot itself on my local SSD (Toshiba Chromebook 2), and even have my home folder there to be safe (?), but I use an SD card for most of my actual work.

The one thing that has not been as smooth as I would like has been the fact that, upon waking up from a sleep, my SD card would be mounted as noexec.  I read various threads about this but didn't see any solution better than just remounting (sudo -o remount,exec /var/host/media/removable/MSCORE, where MSCORE is the name of my SD card) every time I wake the machine, so that's what I've been doing.

Ever since my last ChromeOS update last week - and subsequent update of my chroot - this has not been working any more.  More often than not, even after remounting the SD card - or even umounting and mounting anew - it either shows as belonging to root, or belong to me but with permissions 700 which don't work for what I need to do.

After a whole lot of trial and error, I _think_ I have figured out that the system is trying to mount the same SD card both to /var/host/media/removable/MSCORE and to /media/marc/MSCORE, and the latter has a dmask of 0077, which I guess explains my permissions problem.  There is also a /media/marc/removable that is a symbolic link to /var/host/media/removable, but that has been there as long as I've been using crouton, so I assume that is how it supposed to be.  The problem mount doesn't have the "removable" in the pathname If I umount my SD card from /media/marc/MSCORE, I can then remount it at /var/host/media/removable and permissions are good (and it can also be accessed via the symbolic link at /media/marc/removable/MSCORE, although I'm not sure why I would want to).

I'm hoping this provides enough information to allow someone to give me a suggestion for how I can avoid all this silliness and get my SD to mount correctly on wake automatically.  For starters, I don't particularly understand why there is both a /var/host/media/removable and a /media/marc/removable (symbolic link) in the first place or if there is a reason to prefer one of these pathnames over the other.  But when this problem shows up after waking from a sleep, there is also /media/marc/MSCORE and that is the version with the wrong permissions that seems to be messing things up.

Here is output of croutonversion:

crouton: version 1-20150323010735~master:4348d5f1
release: trusty
architecture: amd64
xmethod: xorg
targets: core,audio,chrome,keyboard,xfce
host: version 6812.75.2 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Apr 14 20:43:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

**Comment by DennisLfromGA** [comment]
I've had similar problems with a running chroot and external media.
I think the */media/marc/MSCORE* is auto-mounted in the chroot, if you could turn off auto-mounting external media, that might help.

**Comment by chrisofCCL** [comment]
Don't know if this helps but I unmount and then remount an SD card that needs exec privs. The only other thing you need to do is prevent the Chromebook from sleeping because that results in the SD card being remounted in its default configuration when it wakes up. You can do that by stopping powerd. So my startup script (run as sudo) is:

stop powerd
umount /media/removable/<mountname>
mount -t ext4 -o defaults,nosuid,nodev /dev/<drivename>  /media/removable/<mountname>
startxfce4 [ or startunity ]
# restart powerd after leaving chroot
	start powerd

Hope that helps

**Comment by MarcSabatella** [comment]
Thanks, but disabling sleep is specifically what I *don't* want to do - I spend a signficant amount of time away from power.  And yes, umount followed mount usually works, but when I get into this situation, it doesn't.

If there is a way to disable automounting of /media/marc/MSCORE, that sounds great, but I don't know how to do that.  What I don't get is why it would be automounting both that *and* /var/host/media/removable/MSCORE.  I don't really care where it gets mounted - I'm not trying to take control here.  I just want it to work.

**Comment by chrisofCCL** [comment]
I agree that preventing automount would a much more elegant solution but I've no idea how to do that I'm afraid.

**Comment by divx118** [comment]
@MarcSabatella You could create a udev rule see https://github.com/dnschneid/crouton/wiki/udev:-manage-inserted-devices You will have to do it again on a reboot.

**Comment by MeneerJansen** [comment]
See [this issue/topic] (https://github.com/dnschneid/crouton/issues/1920) by me. You might try to **stop** your Linux chroot to (auto)mount removable devices by: 

1. sudo dconf-editor

2. Browse to org.gnome.desktop.media-handling and disable automount (and automount-open)

3. Do that both as root and "yourself".

Worked for getting write accress to the SD card for me. :)
