### ISSUE TITLE
Crouton on Restored Chromebook after install Chrubuntu wont start xfce4

### ISSUE THREAD

**Issue by gregnwosu** [dnschneid/crouton#17]
Followed the instruction and can enter-chroot and apt-get etc from there

but if i call startx from inside entered chroot 

or sudo startxfce4

then the screen goes dark after which i am booted back out into ChromeOS

**Comment by mentalhavoc** [comment]
hey guys sorry to add to thread new to playing with linux and new to chrome os was playing with ubuntu install had it running and was enjoying the fact that i got it to work but i loaded warzone 2100 and the samsung chromebook took a long time to load/ crashed so i restarted the device then when trying to get back in it gives me ---

Xephyr cannot open host display. Is DISPLAY set?
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /usr/local/chroots/precise...
chronos@localhost / $ 

can someone kinda give me an idiots def of whats going on havent been able to find intel relevent to what i am experiencing and dont understand the x11 server?     xfce4  i believe

**Comment by mentalhavoc** [comment]
then again i got so excited about reading this i just realize this post is years old

**Comment by finiteuniverse** [comment]
hey mentalhavoc im having the same issue with my crouton arch, trying to find a solution atm ill keep you updated
