### ISSUE TITLE
Screen Not Found

### ISSUE THREAD

**Issue by YoshiDudeRox** [dnschneid/crouton#1702]
So im having this issue
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo startunity
Entering /usr/local/chroots/precise...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:37:50 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=df69371e-2d5c-474a-b725-6ad16ca26b47/PARTNROFF=1 hashtree=PARTUUID=df69371e-2d5c-474a-b725-6ad16ca26b47/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=19983e99694f43f58c9b7fe794a36276d6631a9b salt=c1f66bbcb95439a8ee2d0617298166203029c4b74e1da8c2eb976c10a5fbe491" noinitrd vt.global_cursor_default=0 kern_guid=df69371e-2d5c-474a-b725-6ad16ca26b47 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri May  1 18:25:30 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /usr/local/chroots/precise...
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
> Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

...and provide `croutonversion` ...

**Comment by monster1612** [comment]
I'm having a similar issue with trusty. I tried starting a chroot that had the extension and unity targets installed, and it failed to start as well. This chroot I'm starting does _not_ have the extension target installed, just unity. It had no trouble installing, and I am able to do sudo enter-chroot to enter the trusty chroot via command line. The following is the terminal output. I ran 'croutonversion' on the chroot as well, so I believe I followed all guidelines in https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting. :smile: 

'Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo startunity
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.19.3 #1 SMP Wed May 6 19:36:08 BST 2015 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz root=/dev/sda5 quiet loglevel=1 rw cros_debug
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Thu May 21 14:20:42 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)chris@localhost:~$ exit
logout
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ sudo enter-chroot -n trusty croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 7015.0.2015_05_06_2115 (Developer Build - tonyd) developer-build amd64-atb
kernel: Linux localhost 3.19.3 #1 SMP Wed May 6 19:36:08 BST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ `
