### ISSUE TITLE
can you switch back to xorg in an existing chroot

### ISSUE THREAD

**Issue by giliammc** [dnschneid/crouton#1704]
is thier a way to switch back to the old way of launching xfce4

**Comment by tedm** [comment]
try doing an update with the -txorg target and -n [name of your chroot] -u

**Comment by giliammc** [comment]
i tried that and it dint do anything

**Comment by DennisLfromGA** [comment]
@giliammc - If that 'dint' work, then it didn't complete successfully or was entered incorrectly.

**Comment by dnschneid** [comment]
Please post the output of the failing commands if you want people to help you without just guessing what your problem is.

**Comment by giliammc** [comment]
it turns out that it was just an issue with my chroot, i fixed it and now it works fine, is there a way to switch between the two methods with out having to update every time

**Comment by divx118** [comment]
@giliammc If you mean switch between xiwi and xorg you can add the -X xiwi or  -X xorg to your command. So for example `sudo startxfce4 -X xorg`

**Comment by giliammc** [comment]
that worked great thanks

**Comment by giliammc** [comment]
one more question i have both xfce and unity can i set xfce to open by default in xiwi but unity start by default in xorg

**Comment by DennisLfromGA** [comment]
@giliammc - Sure, you could with aliases, like:
`alias startxfce4='sudo startxfce4 -X xiwi'`
`alias startunity='sudo startunity -X xorg'`
and then add those two commands to your `.bashrc` or `.bash_aliases` file.

**Comment by giliammc** [comment]
thanks that worked great
