### ISSUE TITLE
Cannot autostart crouton chroot when bootup

### ISSUE THREAD

**Issue by initguru** [dnschneid/crouton#1707]
Hi there,

I have been following this autostart crouton guide but failed to get it working.
https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup

I did not put crouton.init in ~/Downloads directory, just modified `/etc/init.d/crouton.conf` file like this:
>...
>env DELAY=10
>env CHROOT=trusty <- I installed trusty.
>env START_DE=startxfce4 <- Installed target was xfce
>env XMETHOD=xorg <- I'm not using xiwi
>env RUN_STATE=y
>...

I think the guide is quite simple but I do not know what I missed...

Thanks in advance.

**Comment by DennisLfromGA** [comment]
- Those changes in `crouton.conf` look alright to me, I don't think that's the problem.
- Did the first step running `rw-rootfs` complete without error and you rebooted?
- If you left DEBUGging on, then you may want look at the file in `/tmp/crouton-$PID.log` to see what might have failed and where.

Also, you don't have to put `crouton.init` in your ~/Downloads folder, that's okay.
You can also put it in `/usr/local/` too, it's just a little easier to tweak the `crouton.init` file than editing `/etc/init/crouton.conf` each time - for me at least.

**Comment by initguru** [comment]
Hi DennisLfromGA,

Thanks for the reply.

I remember there was one error when running rw-root-fs, which was something about brackets with -gt, but simply I have my root filesystem writable. Could that error be a problem? I think I can reproduce the error by reinstalling chroot environment.

I will look into /tmp/crouton*.log files when I get back home.

**Comment by DennisLfromGA** [comment]
No, that error won't affect anything, it's a bug in my script that I haven't fixed yet.
The DEBUG log file should show us where it's failing and we can go from there, hopefully.

**Comment by initguru** [comment]
Very strange, I checked that DEBUG was on in `/etc/init.d/crouton.conf` but no crouton log files under /tmp.
Can you guess what I am missing?

**Comment by initguru** [comment]
I got where I made a mistake...
I put crouton.conf file under `/etc/init.d`, not `/etc/init`. What a shame...
Problem solved. Thanks!

**Comment by DennisLfromGA** [comment]
That is very good news!
Glad it worked out, I've made one or two mistakes myself... ;)
You might want to tryout the `crouton.init` script option, I think it's pretty handy.

**Comment by DennisLfromGA** [comment]
@initguru - If you don't mind, please close this issue if all is well - Thanx.
