### ISSUE TITLE
Upgraded Trusty Crouton reboots on startunity (enter-chroot runs fine) while newly installed Trusty crouton works fine

### ISSUE THREAD

**Issue by enrogue** [dnschneid/crouton#1708]
I've upgraded this trusty crouton many times with a few issues - the last time this happened it was fixed by running 'sudo apt-get install --reinstall xserver-xorg-core' but this time it' not working:

(trusty)brendanb@corundum:~$ croutonversion 
crouton: version 1-20150430123324~master:90ad47ff
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xiwi,extension,unity
host: version 6812.83.0 (Official Build) stable-channel parrot_ivb 
kernel: Linux corundum 3.8.11 #1 SMP Mon Apr 27 10:12:25 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

from the Xorg.1.log if a reinstall is done:

[   871.333] (II) xfree86: Adding drm device (/dev/dri/card0)
[   871.335] (II) xfree86: Adding drm device (/dev/dri/card1)
[   871.337] (EE) 
[   871.337] (EE) Backtrace:
[   871.339] (EE) 0: /usr/bin/X (xorg_backtrace+0x48) [0x7ff8ec965848]
[   871.339] (EE) 1: /usr/bin/X (0x7ff8ec7bc000+0x1ad539) [0x7ff8ec969539]
[   871.340] (EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7ff8eb8b8000+0x10340) [0x7ff8eb8c8340]
[   871.341] (EE) 3: /usr/bin/X (0x7ff8ec7bc000+0xb57a6) [0x7ff8ec8717a6]
[   871.341] (EE) 4: /usr/bin/X (xf86BusProbe+0x9) [0x7ff8ec845099]
[   871.342] (EE) 5: /usr/bin/X (InitOutput+0x74d) [0x7ff8ec8536fd]
[   871.343] (EE) 6: /usr/bin/X (0x7ff8ec7bc000+0x59bab) [0x7ff8ec815bab]
[   871.344] (EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7ff8ea2f8ec5]
[   871.344] (EE) 8: /usr/bin/X (0x7ff8ec7bc000+0x451ee) [0x7ff8ec8011ee]
[   871.345] (EE) 
[   871.346] (EE) Segmentation fault at address 0x0
[   871.346] (EE) 
Fatal server error:
[   871.347] (EE) Caught signal 11 (Segmentation fault). Server aborting
[   871.348] (EE) 
[   871.348] (EE) 
Please consult the The X.Org Foundation support 

As I said in the subject, if \I don't run the apt-get reinstall, it reboots on running startunity - here is the relevant output of /dev/pstore/console-ramoops

[  495.884158] BUG: unable to handle kernel NULL pointer dereference at 0000000000000074
[  495.884179] IP: [<ffffffff868c86cf>] intel_crtc_page_flip+0x33/0x315
[  495.884198] PGD 0 
[  495.884207] Oops: 0000 [#1] SMP 
[  495.889369] gsmi: Log Shutdown Reason 0x03
[  495.889377] Modules linked in: i2c_dev uinput snd_hda_codec_hdmi memconsole ath3k btusb snd_hda_codec_realtek bluetooth snd_hda_intel snd_hda_codec snd_hwdep snd_pcm snd_page_alloc sdhci_pci sdhci mmc_core nm10_gpio snd_timer zram(C) lzo_compress zsmalloc(C) fuse nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_filter ip6_tables tg3 ptp pps_core ath9k_btcoex ath9k_common_btcoex ath9k_hw_btcoex ath mac80211 cfg80211 uvcvideo videobuf2_vmalloc joydev ppp_async ppp_generic slhc tun
[  495.889538] CPU 0 
[  495.889545] Pid: 27235, comm: Xorg Tainted: G         C   3.8.11 #1
[  495.889557] RIP: 0010:[<ffffffff868c86cf>]  [<ffffffff868c86cf>] intel_crtc_page_flip+0x33/0x315
[  495.889573] RSP: 0018:ffff880096cc7cb8  EFLAGS: 00010286
[  495.889582] RAX: ffff8800a628e200 RBX: ffff88013a1d5c00 RCX: 0000000000000201
[  495.889591] RDX: ffff880146c84900 RSI: ffff88013b653cc0 RDI: ffff88014a943000
[  495.889601] RBP: ffff880096cc7d00 R08: ffff88013b653cc0 R09: 0000000000000031
[  495.889610] R10: 0000000000000000 R11: ffffffff86891123 R12: ffff88014a942000
[  495.889620] R13: ffff88014a943000 R14: 0000000000000000 R15: ffff880149dc4000
[  495.889631] FS:  00007f1fad91b9c0(0000) GS:ffff88014f200000(0000) knlGS:0000000000000000
[  495.889641] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  495.889650] CR2: 0000000000000074 CR3: 00000000a6394000 CR4: 00000000001407f0
[  495.889659] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  495.889669] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
[  495.889679] Process Xorg (pid: 27235, threadinfo ffff880096cc6000, task ffff880096f9b480)
[  495.889689] Stack:
[  495.889694]  ffffffff8689dbf6 ffff88013b653cc0 0000000000000031 ffff88013b653cc0
[  495.889715]  ffff88013a1d5c00 ffff880149e39200 ffff88014a943000 ffff88013a1d5400
[  495.889736]  ffff88013a1d5800 ffff880096cc7d48 ffffffff8689e16f 0000000000000000
[  495.889756] Call Trace:
[  495.889766]  [<ffffffff8689dbf6>] ? commit_crtc_state+0x3e/0x21c
[  495.889777]  [<ffffffff8689e16f>] commit_plane_state+0x215/0x280
[  495.889787]  [<ffffffff8689d902>] atomic_commit.isra.3+0x93/0xb4
[  495.889797]  [<ffffffff8689d934>] drm_atomic_commit+0x11/0x13
[  495.889809]  [<ffffffff86896862>] drm_mode_page_flip_ioctl+0x1bd/0x230
[  495.889820]  [<ffffffff86886370>] drm_ioctl+0x30f/0x3ec
[  495.889831]  [<ffffffff868966a5>] ? drm_mode_gamma_get_ioctl+0xc7/0xc7
[  495.889844]  [<ffffffff867de8af>] ? timerqueue_del+0x52/0x5a
[  495.889856]  [<ffffffff86653181>] ? __remove_hrtimer+0x34/0x8d
[  495.889867]  [<ffffffff8665370e>] ? hrtimer_try_to_cancel+0x95/0xb5
[  495.889879]  [<ffffffff866f815f>] do_vfs_ioctl+0x362/0x425
[  495.889888]  [<ffffffff866f8b5b>] ? poll_select_copy_remaining+0xf5/0x120
[  495.889899]  [<ffffffff866f828f>] sys_ioctl+0x6d/0xa5
[  495.889910]  [<ffffffff86ad3902>] system_call_fastpath+0x16/0x1b
[  495.889919] Code: e5 41 57 41 56 41 55 41 54 53 48 83 ec 20 48 8b 87 b8 00 00 00 4c 8b 27 4c 8b 70 50 48 8b 86 90 00 00 00 4d 8b bc 24 f0 03 00 00 <41> 8b 5e 74 39 5e 74 48 89 45 d0 b8 ea ff ff ff 0f 85 bd 02 00 
[  495.890116] RIP  [<ffffffff868c86cf>] intel_crtc_page_flip+0x33/0x315
[  495.890131]  RSP <ffff880096cc7cb8>
[  495.890138] CR2: 0000000000000074
[  495.890166] ---[ end trace d23ef8223a331536 ]---
[  495.898099] Kernel panic - not syncing: Fatal exception
[  495.898118] Kernel Offset: 0x5600000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[  495.898270] gsmi: Log Shutdown Reason 0x02
[  495.909967] ACPI MEMORY or I/O RESET_REG.

Apologies if it's not enough of the logs - I can post more if necessary. Newly installed trusty & precise croutons work fine, but I have a lot of data & packages installed in that one so I'd rather not have to recreate it from scratch & transfer all of the data over

**Comment by dnschneid** [comment]
@smibarber this is what you expected might happen...

**Comment by enrogue** [comment]
Sooo, my chromebook has now been updated to Freon/frecon & the old crouton now works again - I guess this one can be closed - I couldn't test any fixes now in any case
