### ISSUE TITLE
startcli command has stopped working after chromeos update

### ISSUE THREAD

**Issue by Kareeeeem** [dnschneid/crouton#1709]
Tried updating my chroots and tried installing a new one named test. Output on running `sudo startcli -n test`. (Same as for the other chroots)
```
Entering /mnt/stateful_partition/crouton/chroots/test...
Couldn't get a file descriptor referring to the console
Unmounting /mnt/stateful_partition/crouton/chroots/test...
```

Output of croutonversion

```
crouton: version 1-20150430123324~master:90ad47ff
release: stretch
architecture: amd64
targets: cli-extra
host: version 6812.75.2 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 14 18:57:27 PDT 2015 x86_64 GNU/Linux
freon: yes
```
.

**Comment by DennisLfromGA** [comment]
`startcli` no longer works with 'freon', you can use `enter-chroot`.

**Comment by dnschneid** [comment]
`startcli` needs to be modified to spit out an error and suggest `enter-chroot` when launched on Freon.

**Comment by Kareeeeem** [comment]
What is freon exactly? I prefer startcli so I'm not dependent on any chromeos windows, but from the replies I gather that's history now.

Perhaps I'll just hop into a TTY with ctrl-alt -> to start a chroot there with enter-chroot.

**Comment by DennisLfromGA** [comment]
@Kareeeeem - You could also add the 'xiwi' target and then run your terminal in a window, full-screen, or in a tab - `sudo startxiwi -n test [xterm|guake|...]`

**Comment by DennisLfromGA** [comment]
> startcli needs to be modified to spit out an error and suggest enter-chroot when launched on Freon.

pie https://github.com/dnschneid/crouton/pull/1712

**Comment by tedm** [comment]
@DennisLfromGA Are you going to fix this? I looked at startcli and all I can think of is really echo something like:

`"startcli has been deprecated, please use `enter-chroot` instead"`

**Comment by dnschneid** [comment]
Thanks for the quick fix :)
