### ISSUE TITLE
question about mono in chroot

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1713]
Can I run mono in an ubuntu chroot without a desktop?  I'm trying out Microsoft's new Visual Studio Code and it requires mono to do debugging.  The Code editor itself runs great in a xiwi window.

I know this isn't a ubuntu forum but here is my problem trying it so far.  When I run `apt-get install mono-complete` I get this error ...

```
The following packages have unmet dependencies:
 mono-complete : Depends: mono-devel (= 4.0.1-0xamarin4) but it is not going to be installed
                 Depends: mono-4.0-service (= 4.0.1-0xamarin4) but it is not going to be installed
                 Depends: libmono-cil-dev (= 4.0.1-0xamarin4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I have tried apt-get update etc.

**Edit:** I'm running trusty chroot with no desktop, just xiwi.  I'm on a chromebook pixel 2015.

**Comment by tedm** [comment]
did you try:

`sudo apt-get -f install`

`sudo dpkg --configure -a`

then again:

`sudo dpkg --configure -a` ?

**Comment by mark-hahn** [comment]
That didn't help.

Newbie questions: I dpkg related to apt-get?  And what does the `-a` do?

**Comment by tedm** [comment]
@mark-hahn -a when used with `dpkg --configure` will configure all unpacked and unconfigured packages.

dpkg is a lower level installer than apt-get, where aptitude is a text front end for dpkg. learn dpkg and it's parameters if you're going to work with .deb packages as it has specific parameters for configuring package states and actions.

Here's a link that may help: http://askubuntu.com/questions/309113/what-is-the-difference-between-dpkg-and-aptitude-apt-get

**Comment by mark-hahn** [comment]
Thanks.

> I have a new chroot with Jaunty

I'll try that.  Luckily it's easy to try new chroots.

I've been wondering.  What is the advantage of using VMs over chroots?  I
find chroots much easier to work with.

**Comment by Tuxerito** [comment]
Sorry i n my last message I means Trusty no Jaunty

**Comment by mark-hahn** [comment]
Hmm.  I'm using trusty.  I'll try a fresh chroot anyway.

**Comment by Tuxerito** [comment]
Normally when that errors appears is because exists external repositories(same libs but different versions in each repository  and installed libs).

Do you have your repositories up to date?
try
sudo aptitude update
sudo aptitude safe-upgrade
sudo aptitude install mono-complete

**Comment by mark-hahn** [comment]
Thanks.  I tried that.  I got the same missing dependencies but then a
strange message asking me if the solution was acceptable.  I said yes and
then nothing happened.  "which mono" returned nothing so I think it is
still not installed.

I'm downloading a fresh trusty now.  I will try those three commands again.

**Comment by Tuxerito** [comment]
If you saw a message suggesting things like uninstall packages or similar then is probably what I told you, you have unofficial repositories and the package manager can't resolve the dependencies(conflict with lib versions).

When you see a message asking you for a solution be careful some people don't read and answer "Yes" and after that some times they break the system. I saw users choosing "Yes" and after that bye bye to all user interface(The suggested solution was delete lot of libs including Gnome libs) That can be fixed but a normal user don't know how. Users normally scare because they only have access to a console nothing graphic.

**Comment by mark-hahn** [comment]
Your three commands on a fresh trusty worked.  Now I have to decide if it is worth the trouble of reinstalling my entire environment for one feature.

Thanks mucho.
