### ISSUE TITLE
LXDE Crouton; Increase Brightness broken

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#1714]
When I switch to my LXDE Trusty chroot, I find that the Search+'increase brightness' key combination is non-responsive. 

However, weirdly if I hit the Search+'decrease brightness' key combination once, then all the SearchKey+X brightness control combinations become reactivated and brightness is back in my control even from the Chroot.

The underlying problem, (the reason why I'm trying to control brightness in the Chroot), is that during the switch from ChromeOS to the Chroot, for some reason the brightness goes from 100% to the lowest setting and needs at least a 'decrease brightness' event to be sent in order for the brightness to approximate to what it was before.

So this is really a feature request and a bug...

* Feature: Brightness config between VTs should be preserved, explicitly if necessary (e.g. store it before the switch and restore afterward).
* Bug: Increase brightness key combination is broken until decrease brightness is hit

**Comment by dnschneid** [comment]
Yep!  See #407
