### ISSUE TITLE
Using build/release.sh

### ISSUE THREAD

**Issue by gurupras** [dnschneid/crouton#1718]
Hi,

I forked the project to update the boot scripts so it installs an extended set of packages (texlive-full, nginx, etc). I added these to `installer/ubuntu/bootstrap`, however, I found that these lines were never executed.

I then proceeded to add echo statements which also never showed up. It seemed that despite changing the URLs in `installer/crouton`, the files being procured were older versions.

Looking at `/tmp/crouton-installer-cache`, I noticed that this script is being generated from `build/wrapper.sh` and that there is a specific git revision that it is using. My guess is that this is the revision from which the remaining files are checked out.

I tracked this down to `build/release.sh` which is supposed to create the releases. Unfortunately, I'm not quite sure how to use this script works. It expects me to provide it a bundle (`git bundle`? Which I tried BTW) which I'm not sure how to create/generate. Some help on how to use this would be greatly appreciated.

Thanks for your excellent work on crouton :)

**Comment by dnschneid** [comment]
You don't need to fork crouton to do that.  If you create a file like so:

```
REQUIRES=''
. "${TARGETSDIR:="$PWD"}/common"
### Append to prepare.sh:
install texlive-full nginx ...etc
```

Then pass `-T path_to_above_file` to the crouton installer, it will install those extra packages.  You can put arbitrary root commands in there as well to customize your chroot as you create it.  You can also add targets to the REQUIRES line to bring in a default set of targets.

**Comment by DennisLfromGA** [comment]
@dnschneid - Thanx for that tip; I never knew how to format a targets file for use with the `-T` option. I think that'll come in very handy for testing 'vivid' and others that still need various packages added to work.
