### ISSUE TITLE
Can't enter chroot (garbage in crouton-pulseaudio-cras.sh)

### ISSUE THREAD

**Issue by andrewmoise** [dnschneid/crouton#1719]
I can't enter my chroot any more:

    chronos@localhost ~/Downloads/crouton-master $ sudo enter-chroot
    Enter encryption passphrase for jessie: 
    Entering /mnt/stateful_partition/crouton/chroots/jessie...
    -su: 1: /etc/profile.d/crouton-pulseaudio-cras.sh: Syntax error: EOF in backquote substitution
    WARNING: starting chroot system dbus daemon failed with code 2
    -su: 1: /etc/profile.d/crouton-pulseaudio-cras.sh: Syntax error: EOF in backquote substitution
    Unmounting /mnt/stateful_partition/crouton/chroots/jessie...

Some investigation reveals a clue at the problem:

    chronos@localhost ~ $ sudo more /run/crouton/mnt/stateful_partition/crouton/chroots/jessie/etc/profile.d/crouton-pulseaudio-cras.sh
    ���Ɉ�/�c�:5���Ɉ��`#���
    chronos@localhost ~ $ 

... which doesn't seem right.

This is with crouton from git, commit 75fb08cb47626fced2f56ad995053c9944066baa.

Thanks in advance for your help.

**Comment by dnschneid** [comment]
It looks like you did an unclean shutdown (did your system suddenly reboot or run out of power?) so some of the files corrupted.  You can try updating crouton again to rewrite the crouton files, but it's possible other critical files in your chroot are broken as well, in which case you're better off making a new chroot and copying over your data as needed.

**Comment by andrewmoise** [comment]
Makes sense. I tried starting X and it froze on a black screen, so I did a hard shutdown. I'll try making a fresh chroot and see how that works.
