### ISSUE TITLE
Can't start X in updated jessie chroot

### ISSUE THREAD

**Issue by andrewmoise** [dnschneid/crouton#1720]
After working around issue #1719, I can now enter the chroot, but I still can't start X:

    (jessie)moise@localhost:~$ startx
    
    Invalid X11 backend ''
    /usr/bin/xinit: giving up
    /usr/bin/xinit: unable to connect to X server: Connection refused
    /usr/bin/xinit: server error
    Couldn't get a file descriptor referring to the console
    (jessie)moise@localhost:~$ 

This is with a freshly updated jessie chroot, using crouton from git (commit 75fb08cb47626fced2f56ad995053c9944066baa).

Thanks in advance for your help.

**Comment by dnschneid** [comment]
`startx` has never worked reliably, although you may be running into corrupted files as in #1719.  Use `xinit`.

**Comment by andrewmoise** [comment]
Hm, on a fresh stretch chroot, it seems like startx still doesn't work, xinit does work, and I can't switch VTs with the Ctrl-alt-F1 set of keys anymore (i.e. once I start X I'm stuck in X until I exit from X, then it switches back to ChromeOS). If startx isn't expected to work then I can switch to xinit. Is the non-working VT switching worth creating a separate issue for?

**Comment by dnschneid** [comment]
No, VT switching is dead, and hasn't been the appropriate way of switching to chroots for quite some time now.  Use Ctrl-Alt-Shift-F1/F2.

**Comment by andrewmoise** [comment]
Okay, I reinstalled a fresh stretch chroot to make sure, and no way of launching gnome that I can see works.

* The tips at the end of the installer tell me to use "sudo startgnome", but when I do it says, "Do not launch gnome-session-wrapper as root inside the chroot."

* Just using "startgnome" yields the following:

    X.Org X Server 1.16.4
    Release Date: 2014-12-20
    X Protocol Version 11, Revision 0
    Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
    Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 10:25:56 PDT 2015 x86_64
    Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=34ae123f-59e8-d643-80f3-6a46d20718c8/PARTNROFF=1 hashtree=PARTUUID=34ae123f-59e8-d643-80f3-6a46d20718c8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=28db8d39abe580e8d825c0c6e773936da352c3cb salt=3f6c3e57215764ae513116afda7f46da4034d74a40d4a51781ed278fa37ff57b" noinitrd vt.global_cursor_default=0 kern_guid=34ae123f-59e8-d643-80f3-6a46d20718c8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
    Build Date: 11 February 2015  12:32:02AM
    xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
    Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
    Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu May  7 00:26:58 2015
    (==) Using system config directory "/usr/share/X11/xorg.conf.d"
    xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
    (EE) 
    Fatal server error:
    (EE) no screens found(EE) 
    (EE) 
    Please consult the The X.Org Foundation support 
         at http://wiki.x.org
     for help. 
    (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
    (EE) 
    (EE) Server terminated with error (1). Closing log file.
    /usr/bin/xinit: giving up
    /usr/bin/xinit: unable to connect to X server: Connection refused
    /usr/bin/xinit: server error

* Running xinit and then gnome-session yields a whole slew of errors followed by a full screen "Oh no! Something has gone wrong." message. I don't know that gnome-session the right way to do it (I've always used startgnome), just that's what I tried.

  I'm not trying to be a pain in the neck, I just want my X environment to work. I can get work done by running xinit and then blackbox, but it's not preferred. If there is a recommended way to get gnome to work, let me know and I can make a patch for the docs. If you want me to file a separate bug for the gnome brokenness let me know and I can.

**Comment by andrewmoise** [comment]
Update: I just now figured out that I'm meant to run "sudo startgnome" from outside the chroot. That doesn't work either (I get the "Oh no! Something has gone wrong" message). Here's the output from that:

X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 10:25:56 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=34ae123f-59e8-d643-80f3-6a46d20718c8/PARTNROFF=1 hashtree=PARTUUID=34ae123f-59e8-d643-80f3-6a46d20718c8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=28db8d39abe580e8d825c0c6e773936da352c3cb salt=3f6c3e57215764ae513116afda7f46da4034d74a40d4a51781ed278fa37ff57b" noinitrd vt.global_cursor_default=0 kern_guid=34ae123f-59e8-d643-80f3-6a46d20718c8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 11 February 2015  12:32:02AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu May  7 00:41:46 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
xf86: found device 0
crouton: version git
release: stretch
architecture: amd64
xmethod: xorg
targets: gnome
host: version 6812.83.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Mon Apr 27 10:25:56 PDT 2015 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.
.
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/stretch...

**Comment by j0h** [comment]
I am just having the same problem. I could not figure what the cause of it is. Just in general applications are working nicely started with "xiwi " as a prefix. Therefor I am able to work with my chroot env. It would be still great to have this fixed. It is kind of annoying.

Calling xinit opens a bash shell. Then typing startx gives me a "waiting for xserver to accept connections..". Too bad this seems to be looping infinitely. I did not have the time to inspect this problem further. I hope you were more successful.

Best,
j0h

**Comment by andrewmoise** [comment]
Hm, it does work for me now ("sudo startxfce4" from outside the chroot). I get a crouton-extension window, like with xiwi, instead of switching to a different VT, but it works and I seem to be able to interact with xfce as I'd like to.

-Andrew

**Comment by j0h** [comment]
Indeed, xfce or even kde won't make any problems. They work like a charm. I would just love to have gnome running. :-) I get all the error stuff that was posted before (connection to xserver failed...). Next month I will hopefully have more time to figure out what the problem really is.



On 27 Jul 2015, at 15:16, andrewmoise <notifications@github.com<mailto:notifications@github.com>> wrote:


Hm, it does work for me now ("sudo startxfce4" from outside the chroot). I get a crouton-extension window, like with xiwi, instead of switching to a different VT, but it works and I seem to be able to interact with xfce as I'd like to.

-Andrew

**Comment by webhandler** [comment]
Having the exact same issue, getting into KDE fine. Gnome, not so much, same grey screen, fresh install with xiwi also.
