### ISSUE TITLE
Backing up to a network drive using an ES File Explorer

### ISSUE THREAD

**Issue by reeved** [dnschneid/crouton#1722]
I'm running the latest Dev Channel version and crouton version on my C720.

So, using ARC Welder, I was able to run the Android File Manager app, ES File Explorer.
Using this app, I was able to mount my network drive and access its files.
I was wondering if there was a way for crouton to connect to this network drive maybe through ES? 
That would make backing up my chroot a lot easier as it can be a pain to backup a large chroot on my 16GB SSD.
Of course, the alternative would be to just pop in an SD Card or USB and direct the backup location there but it would be cool if I also had the option of the network drive :P

**Comment by dnschneid** [comment]
That seems convoluted.  There's a [couple](https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-using-smbnetfs) wiki [entries](https://github.com/dnschneid/crouton/wiki/SME-Storage-Made-Easy-package-installation-for-local-access) on accessing cloud/network storage that may be of use.
