### ISSUE TITLE
feature request - support XAMPP or other all-in-one LAMP stack in crouton

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1723]
The individual modules can be installed currently, but it takes a lot of config time. On a standard linux system, the XAMPP package installs about 10 modules, mostly unattended and from a single package. I think it's a binary script. Here are errors I get when trying to install on precise / ARM:

XAMPP itself may never run because of upstart, but can some kind of single package install mysql, phpmyadmin, apache2, php5 in one go? leaving config and passwords for later?

-rwxrwxrwx 1 ted    ted     125180584 May  5 10:50 xampp-linux-5.6.8-0-installer.run
(0xampp)root@localhost:/home/ted/Downloads# whoami
root
(0xampp)root@localhost:/home/ted/Downloads# chown root:root xampp-linux-5.6.8-0-installer.run 
(0xampp)root@localhost:/home/ted/Downloads# ./run xampp-linux-5.6.8-0-installer.run 
bash: ./run: No such file or directory
(0xampp)root@localhost:/home/ted/Downloads# vi xampp-linux-5.6.8-0-installer.run 
(0xampp)root@localhost:/home/ted/Downloads# ./run xampp-linux-5.6.8-0-installer.run 
bash: ./run: No such file or directory
(0xampp)root@localhost:/home/ted/Downloads# ./xampp-linux-5.6.8-0-installer.run 
bash: ./xampp-linux-5.6.8-0-installer.run: cannot execute binary file
(0xampp)root@localhost:/home/ted/Downloads# sh xampp-linux-5.6.8-0-installer.run 
xampp-linux-5.6.8-0-installer.run: 1: xampp-linux-5.6.8-0-installer.run: Syntax error: "(" unexpected
(0xampp)root@localhost:/home/ted/Downloads#

**Comment by dnschneid** [comment]
You could make a target that automates stuff, but this probably wouldn't be integrated into crouton proper.
