### ISSUE TITLE
Implement Elementary OS

### ISSUE THREAD

**Issue by Alfriadox** [dnschneid/crouton#1725]
I was wondering how easy it would be to implement Elementary OS in crouton. Any thoughts, I would be happy to help.

**Comment by Alfriadox** [comment]
I found http://jeanlouisnguyen.blogspot.com/2014/01/guide-how-to-install-elementary-os-on.html and i was wondering if all you need to implement this would be to put some of the commands into .sh files and add elementary to the list of targets or something. This is based off of xfce which this already supports.

**Comment by DennisLfromGA** [comment]
@Alfriadox, 

'jeanlouisnguyen's [site](http://jeanlouisnguyen.blogspot.com/2014/01/guide-how-to-install-elementary-os-on.html) is very popular and definitely one way of installing Elementary on a Chromebook.

Another way, that I just recently did, is to use [MyDearWatson](https://github.com/AldousP/MyDearWatson). It has all the commands and scripts bundled together very nicely, like you were alluding to above. If you're interested in this approach, there's a discussion of it at [Crouton Central](https://groups.google.com/forum/#!topic/crouton-central/zi1qTAS4DRc).

-DennisL

**Comment by Alfriadox** [comment]
Thank you.

**Comment by tedm** [comment]
@DennisLfromGA What would be the differences between installing via MyDearWatson vs the #1725 open enhancement request of having elementary and elementary-desktop as crouton targets?
