### ISSUE TITLE
running as root

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1726]
Would there be any problems if I logged in and ran as root all the time?  I know all the yadda yadda about why I shouldn't but this is a technical question.  I know about sudo -i but I wonder if I can allow root login and if there would be any software that chokes when running as root.

I've used nothing but single-user servers as root for 25 years and I really hate typing sudo.

**Comment by dnschneid** [comment]
For others following along at home:

1. Don't do it.
2. Don't do it.
3. This is a terrible idea and it's highly likely you'll break your chroot even during routine usage, and/or get smashed with malicious code if you're touching the internet inside your chroot.
4. "I don't like typing sudo" is pretty much the worst justification you could use for taking this route.
5. Really, don't do it.

For @mark-hahn: join #crouton on IRC if you really want to do that.
