### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by ohnoplus** [dnschneid/crouton#1730]
Hello. I have a similar problem to the other black screen issues that I've seen recently, so maybe related. I wasn't able to start my Ubuntu 14.04 system through crouton so I updated to the newist version of crouton. Now crouton does seem to start, but when it does I get a solid black screen. <ctrl> + <alt> + <F1> does get me back to Crome OS. The output from the shell at that stace is attached below. Interestingly if I go back to Ubuntu with <ctrl> + <alt> + <F2> and then <ctrl> + <alt> + <F3> sometimes, but not always and not last time I tried it, I see the desktop flash up for maybe a fifth of a second before the screen goes black again.

Output below:
chronos@localhost / $ sudo startxfce4
Enter encryption passphrase for ogog: 
Entering /mnt/stateful_partition/crouton/chroots/ogog...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Mon Apr 27 08:43:45 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-1 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="2 vboot none ro 1,0 2545920 bootcache PARTUUID=77a8d32c-6ae5-4744-a9c9-d38c6eb2a3fc/PARTNROFF=1 2545920 1e8c00478ff05a911b5e4259be0a666475ffc9f2 512 20000 100000, vroot none ro 1,0 2506752 verity payload=254:0 hashtree=254:0 hashstart=2506752 alg=sha1 root_hexdigest=740a5bd822ea22b024dcc580e7f21f179ca653e1 salt=fa98b29a09fde12851119d11379e8ef74a4487202d5c8e29ac229196214f54e7" noinitrd vt.global_cursor_default=0 kern_guid=77a8d32c-6ae5-4744-a9c9-d38c6eb2a3fc add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Fri May  8 13:20:26 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 1
xf86: found device 1
crouton: version 1-20150503215233~master:75fb08cb
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6812.83.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Mon Apr 27 08:43:45 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:461): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:461): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

** (wrapper-1.0:478): WARNING **: Binding 'XF86AudioLowerVolume' failed!

** (wrapper-1.0:478): WARNING **: Binding 'XF86AudioRaiseVolume' failed!

** (wrapper-1.0:478): WARNING **: Binding 'XF86AudioMute' failed!

(process:485): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
(II) AIGLX: Suspending AIGLX clients for VT switch

**Comment by Tuxerito** [comment]
What happen If you close/open the lid when you see the desktop and the black screen?

**Comment by henningspruth** [comment]
I have the same symptoms as ohnoplus. Closing/opening the list brings the screen back to life until the next VT switch.

**Comment by Tuxerito** [comment]
I had that problem for 2 months. Partially solved in ChromeOS(Beta channel) and solved in  ChromeOS(Dev Channel)

You can see my thread here
https://github.com/dnschneid/crouton/issues/1644

**Comment by ohnoplus** [comment]
Yes, I have the same findings as henningspurth. Closing and opening does seem to make things work.

**Comment by astrodud** [comment]
I am now having the same problem, but closing and opening does not seem to end the black screen. I have to do a hard reboot.

I just set up a basic x11-enabled chroot, and am having the same issue there.
Here is my info:

$ croutonversion 
crouton: version 1-20150519153807~master:30cf02c9
release: jessie
architecture: amd64
xmethod: xorg
targets: xorg,keyboard,cli-extra
host: version 6812.88.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 12:21:21 PDT 2015 x86_64 GNU/Linux
freon: yes

**Comment by ohnoplus** [comment]
I seem to get the same behaviour in the Beta channel. Crouton doesn't start at all in the Dev channel. Instead I get the following

**Comment by Tuxerito** [comment]
Try updating your chroot after update ChromeOS(Beta/Dev)

**Comment by ohnoplus** [comment]
Yep, that works. Does this mean things will start working in the Beta or Stable channels soon/eventually?

**Comment by ohnoplus** [comment]
Also, Ctrl + Alt + F1 and Ctrl + Alt + F2 seem not to work in dev mode? Does anyone know if this is a bug I should suspect or is there some workaround?

**Comment by Tuxerito** [comment]
Yes. Changes in Dev channel will be implemented in the Beta version and changes in Beta will be implemented in the Stable version. 

I am using Dev channel and not problems

About Ctrl + Alt + F1

Now is Ctrl + Alt + Shift + F1 and Ctrl + Alt + Shift + F1
