### ISSUE TITLE
Not Able To Start Unity from ChromeOS

### ISSUE THREAD

**Issue by 13MattR** [dnschneid/crouton#1732]
So I open up Crosh with Cntrl+Alt+t, and then I type "shell" and I get "chronos@localhost / $ " like normal right? The I type "sudo startunity" which has been working till just a few minutes ago, and now all that happens is this: "Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:41:08 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cdc4bb3c-81ec-ba4f-9aca-bab048199b8d/PARTNROFF=1 hashtree=PARTUUID=cdc4bb3c-81ec-ba4f-9aca-bab048199b8d/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=de48652780ec47a8c663cbd70dad5784b727ad65 salt=1f18cb43e2ac2532c75275f05941bbe821951c1417d42c9470b1a50a7a86c94c" noinitrd vt.global_cursor_default=0 kern_guid=cdc4bb3c-81ec-ba4f-9aca-bab048199b8d add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat May  9 17:32:45 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file."

And this comes up every single time! Please shead your knowledge, because I have working applications on it and I don't want to go through the whole installation process my WiFi is slow.

**Comment by divx118** [comment]
Update your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by 13MattR** [comment]
Thanks, I updated my chroot and it seems to have worked like a charm!

**Comment by divx118** [comment]
@13MattR Nice, please close this issue then.Thanks
