### ISSUE TITLE
KVM and udev on Chromebook

### ISSUE THREAD

**Issue by maxenglander** [dnschneid/crouton#1733]
Hello,

I've gotten KVM installed onto Chromium thanks to [this fantastic guide](https://docs.google.com/document/d/1WQnfloMbcR798Lk-iYPbvZt-wplW83IYyCf7SYyXTvs/edit) I found listed in [another issue here](https://github.com/dnschneid/crouton/issues/707). I'm happily running an Android Emulator with KVM support.

One annoyance I'm having trouble with is getting udev to apply the right permissions to `/dev/kvm`.

I've followed the [Wiki directions](https://github.com/dnschneid/crouton/wiki/udev:-manage-inserted-devices) on managing inserted devices as far as I can tell, by
- updated `/etc/rc.local` to copy chroot rules files
- creating a rule file to set perms and mode on `/dev/kvm`
- added my user to the `devbroker-access` group
- rebooted the chroot (and Chrome itself, to be safe)

but it doesn't seem to apply the changes to `/dev/kvm` - I still end up having to manually apply the right permissions with `chgrp` and such.

Here are all the relevant files, in case it's helpful.

**Outside chroot**

```
chronos@localhost / $ ls -la /dev/kvm
crw-rw---- 1 root 50 10, 232 May 10 19:10 /dev/kvm

cronos$ cat /etc/group | grep devbroker-access
devbroker-access:!:403:chronos
```

**Inside chroot**

```
chroot$ grep udev /etc/rc.local
mkdir -p /run/udev/rules.d
cp /etc/udev/rules.d/*.rules /run/udev/rules.d
udevadm control --reload

chroot$ cat /etc/udev/rules.d/999-kvm
KERNEL=="kvm", GROUP="devbroker-access", MODE="0660"

chroot$ cat /etc/group | grep devbroker
devbroker-access:x:403:myuser
```

Thanks very much for your time, and for all the amazing work on this project.

**Comment by srinathh** [comment]
+1 I'm having the same problem and manually applying perms

**Comment by dkovach** [comment]
With this perms issue, were you guys still able to run the Android emulator successfully with KVM?

**Comment by DennisLfromGA** [comment]
@maxenglander,

> chroot$ cat /etc/udev/rules.d/999-kvm
> KERNEL=="kvm", GROUP="devbroker-access", MODE="0660"

I don't know if your file actually has two equal signs in it or not but the above shows it contains:

`KERNEL=="kvm"` not `KERNEL="kvm"`

If it does, then 'KERNEL' may not be getting assigned correctly.

**Comment by srinathh** [comment]
hmm.. I don't remember what i was trying in rules.d but i'll try this. Currently for Android emulator, the "fix" I'm using is to start my chroot with a script and before the startxfce command, to set the mode for /dev/kvm to 0666 (which isn't ideal).
