### ISSUE TITLE
Issue regarding changing a chroot's IP.

### ISSUE THREAD

**Issue by Skurp** [dnschneid/crouton#1734]
Is it possible to change my chroot's IP?

**Comment by tonyxue** [comment]
Your chroot shares the internet connection with your CrOS.

**Comment by Skurp** [comment]
Incorrect. My chromebook IP and ubuntu IP are not the same.

Can you stay on the right relevancy and actually help me instead of telling me a incorrect statement?

**Comment by DennisLfromGA** [comment]
@Skurp - I can't :/ :-1:

**Comment by dnschneid** [comment]
Except @tonyxue is right.  How are you determining the IP addresses of the two environments?  Could you post the output of `ifconfig` inside and outside the chroot?

**Comment by mark-hahn** [comment]
> actually help me instead of telling me a incorrect statement?

Are you aware how rude that was?  Not a good way to make friends and get
help on forums.

**Comment by tonyxue** [comment]
### A few things interesting from @Skurp here:
> My chromebook IP and ubuntu IP are not the same.

So are your CrOS and chroot using the same network card and did you modified crouton by yourself? Would need to have a look at your `ifconfig` output as @dnschneid suggested.

>Incorrect.

Nope, it's correct.

>Can you stay on the right relevancy and actually help me

That's what I am doing

>a incorrect statement

English grammar mistake here.

**Comment by Skurp** [comment]
ThaNKS!
