### ISSUE TITLE
Run script automatically when chroot starts (precise)

### ISSUE THREAD

**Issue by wb0gaz** [dnschneid/crouton#1735]
I wish to have a small script run when chroot starts, however, it does not appear to be doing as expected.

These two scripts (in the chroot directory structure) seem like where I'd put the commands I want executed.

/etc/rc.local
/etc/init.d/rc.local

The command I wish to execute is

stop powerd

yet if I place that near the end of both scripts above, powerd remains running when the chroot starts. I can stop powerd manually with sudo stop powerd, but I'd like to avoid this step if I can during start-up of the chroot.

Thanks!

**Comment by divx118** [comment]
You should add it to /etc/rc.local , maybe add some debug info that writes
it to a file. Maybe obvious, but just to be sure you need to add the
command before `exit 0`

**Comment by DennisLfromGA** [comment]
You may also need to specify the full path to 'powerd'.

On Mon, May 11, 2015 at 11:42 AM, Maurice van Kruchten <
notifications@github.com> wrote:

> You should add it to /etc/rc.local , maybe add some debug info that writes
> it to a file. Maybe obvious, but just to be sure you need to add the
> command before `exit 0`
>
>
> On Mon, May 11, 2015 at 2:53 PM, wb0gaz <notifications@github.com> wrote:
>
> > I wish to have a small script run when chroot starts, however, it does
> not
> > appear to be doing as expected.
> >
> > These two scripts (in the chroot directory structure) seem like where I'd
> > put the commands I want executed.
> >
> > /etc/rc.local
> > /etc/init.d/rc.local
> >
> > The command I wish to execute is
> >
> > stop powerd
> >
> > yet if I place that near the end of both scripts above, powerd remains
> > running when the chroot starts. I can stop powerd manually with sudo stop
> > powerd, but I'd like to avoid this step if I can during start-up of the
> > chroot.
> >
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dnschneid/crouton/issues/1735>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/1735#issuecomment-100950160>.
>



-- 
*DennyL@GMail*

**Comment by mark-hahn** [comment]
FWIW, I use .bashrc which meets my needs.

**Comment by wb0gaz** [comment]
Path sounds most likely - I doubt that individual user account PATH is valid at the time /etc/rc.local is executing. I'll check that, include some debug statements if necessary, and advise if any further difficulty.

Thanks for the several very helpful replies!


------------------------------

**Comment by wb0gaz** [comment]
Path was part of the problem - I replaced

stop powerd

with

/sbin/initctl stop powerd

and that works.

###

I also am trying to execute "brightness" command, which needs to be executed prior to stopping powerd. In a nutshell, I'm seeking to set brightness to a fixed level, then stop powerd, so I can leave the machine run unattended all day. I can do this manually once the chroot is running, but I would like this done automatically when the chroot starts.

I added to /etc/rc.local

/usr/local/bin/brightness 40

The /etc/rc.local script terminates /etc/rc.local itself when the command above is called - I don't think the command itself is executing, because logging output (/usr/local/bin/brightness 40 >>/tmp/log 2>&1)  produces nothing, and no further commands in /etg/rc.local are executing.

If I can fix this problem, I'll have crouton configured the way I want.

Thanks!

**Comment by wb0gaz** [comment]
I dug around /usr/local/bin/brightness and extracted the underlying host-dbus command. The command below (all in one long line) runs fine when executed manually once the chroot is running, but it appears to be ignored when executed in /etc/rc.local.

/usr/local/bin/host-dbus dbus-send --system --dest=org.chromium.PowerManager           --type=method_call  /org/chromium/PowerManager           org.chromium.PowerManager.SetScreenBrightnessPercent double:40 int32:1 >>/tmp/log 2&1

Thanks for any suggestions!

Dave

**Comment by wb0gaz** [comment]
Another approach - what's the correct way to launch a script on start of X11 (xinit?) - I'm on 12.04 (Precise) running gnome-fallback session. It's working really well as a "daily driver" machine (save for the forced Chrome OS updates which I hope to supress with stop update-engine), so I'm just trying tame some individual preferences with this.
