### ISSUE TITLE
X.Org issue

### ISSUE THREAD

**Issue by zalami12** [dnschneid/crouton#1737]
After recently updating my ChromeOS, I am unable to open Ubuntu with XFCE running the command below. We updated Ubuntu via the CLI, but to no avail. I also attempted to unmount  /mnt/stateful_partition/crouton/chroots/precise, but umount said it was not mounted.

Does anybody have any idea what the issue could be? Any help would be greatly appreciated...

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Apr 27 08:37:50 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=043bcab0-1025-3e40-b108-a02541d36d19/PARTNROFF=1 hashtree=PARTUUID=043bcab0-1025-3e40-b108-a02541d36d19/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=19983e99694f43f58c9b7fe794a36276d6631a9b salt=c1f66bbcb95439a8ee2d0617298166203029c4b74e1da8c2eb976c10a5fbe491" noinitrd vt.global_cursor_default=0 kern_guid=043bcab0-1025-3e40-b108-a02541d36d19 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Mon May 11 21:51:57 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

**Comment by zalami12** [comment]
I'm running on the Acer C720 

Version 42.0.2311.134 (64-bit)
Platform 6812.83.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.89.0

Channel
Currently on stable channel.

Change channel...
WebKit

537.36 (@194203)
V8

4.2.77.18

User Agent
Mozilla/5.0 (X11; CrOS x86_64 6812.83.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.134 Safari/537.36

Command Line
/opt/google/chrome/chrome --ppapi-flash-path=/opt/google/chrome/pepper/libpepflashplayer.so --ppapi-flash-version=17.0.0.169-r1 --ppapi-flash-args=enable_hw_video_decode=1 --enable-fixed-position-compositing --enable-impl-side-painting --max-tiles-for-interest-area=512 --ui-enable-per-tile-painting --ui-prioritize-in-gpu-process --use-gl=egl --gpu-sandbox-failures-fatal=yes --ozone-platform=gbm --ozone-use-surfaceless --enable-logging --log-level=1 --use-cras --user-data-dir=/home/chronos --max-unused-resource-memory-usage-percentage=5 --system-developer-mode --login-profile=user --has-chromeos-keyboard --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/oem_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/oem_small.jpg --default-wallpaper-is-oem --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --enterprise-enable-forced-re-enrollment --enterprise-enrollment-initial-modulus=13 --enterprise-enrollment-modulus-limit=17 --vmodule=screen_locker=1,webui_screen_locker=1,*ui/display/chromeos*=1,*ash/display*=1,*ui/ozone*=1,*zygote*=1,*plugin*=2 --login-manager --first-exec-after-boot --ozone-use-surfaceless

Build Date
Monday, April 27, 2015

**Comment by falafflepotatoe** [comment]
yea getting an error now myself also

xf86EnableIOPorts: failed to set IOPL for I/O
cannot startx

gonna try updating brb

**Comment by falafflepotatoe** [comment]
updating crouton fixed my issue

to op: crouton -n CHROOTNAME -u 

dsch, really nice software, thanks a bunch

**Comment by kellevan** [comment]
This issue exists for me, even after rebooting:

crouton: version 1-20150511154233~master:392b84e4
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,gnome,xiwi,x11,core,chrome,touch,cli-extra
host: version 6812.88.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Fri May 8 12:28:46 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Cannot open /sys/class/tty/tty0/active: No such file or directory

**Comment by kellevan** [comment]
Fixed this via:

https://github.com/dnschneid/crouton/issues/1680

Odd.

**Comment by rogue417** [comment]
Folks I'm having the same issue.  However I'm not running Gnome, but XFCE, so the solution gryfxx discovered in #1680 would seem to cut it.  Falafflepotatoe might have it with his crouton update suggestion, but my shell cannot find his command of crouton -n CHROOTNAME -u.  What am I missing?

**Comment by falafflepotatoe** [comment]
a lot of times crouton gets deleted by updates, just DL crouton again and try updating

**Comment by rogue417** [comment]
Wouldn't this eliminate the XFCE distro currently loaded?  Besides I still think Crouton is installed, at least the last time I looked.

**Comment by divx118** [comment]
@rogue417 CHROOTNAME should be replaced with your chroot name. Also don't forget `sudo sh` So an example of the complete command could be `sudo sh ~/Downloads/crouton -n precise -u` See https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting on how to retrieve your chroot name and other usefull tips on updating.

**Comment by rogue417** [comment]
divx thanks for your reply!  As you can see however it seems Crouton isn't a shell command for this chroot.

crosh> shell
chronos@localhost / $ sudo edit-chroot -a
Password: 
precise
chronos@localhost / $ crouton -n precise -u
bash: crouton: command not found
chronos@localhost / $ sudo crouton -n precise -u
sudo: crouton: command not found
chronos@localhost / $ 

Did I enter this incorrectly?  Like I said I'm pretty sure crouton is still loaded.. :-/

**Comment by falafflepotatoe** [comment]
ooh, you can try this, i had the same problem last time i ran crouton, i got crouton not found (wtf its there), i tried chmod +x crouton, still not enough. i ended up doing something like: `sudo sh crouton.sh -n precise -u`   and it worked perfect (not sure if it was ./crouton.sh or crouton.sh)

cheers n gl

**Comment by divx118** [comment]
@rogue417 Don't forget to specify the path to crouton. Default location after you download [crouton](https://goo.gl/fd3zc) is in ~/Downloads. So your command should be `sudo sh ~/Downloads/crouton -n precise -u`

**Comment by rogue417** [comment]
chronos@localhost / $ sudo sh ~/Downloads/crouton -n -u
Downloading latest crouton installer...
######################################################################## 100.0%
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: precise,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.
chronos@localhost / $ sudo startxfce4
Enter encryption passphrase for precise: 
Entering /usr/local/chroots/precise...
/usr/bin/startxfce4: Starting X server

ERROR: ld.so: object '/usr/local/lib/croutonfreon.so' from LD_PRELOAD cannot be preloaded: ignored.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Sun Jun 21 16:17:37 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=39e24f94-f193-814c-8d36-c487fcc5d6d9/PARTNROFF=1 hashtree=PARTUUID=39e24f94-f193-814c-8d36-c487fcc5d6d9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=a6ceb271ecf23d07601ba57a7124aa0802c8eec8 salt=57104ade9438a20fdeecb4b344f56aa43494671b8f3cacc573bdd243d1a10168" noinitrd vt.global_cursor_default=0 kern_guid=39e24f94-f193-814c-8d36-c487fcc5d6d9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jun 29 19:56:32 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /usr/local/chroots/precise...

Perhaps I'm missing something.  Have I actually installed Crouton, or did I just download the installer?  Thanks for your patience!

**Comment by falafflepotatoe** [comment]
thats the installer again
-n CHROOTNAME -u
is what you want

**Comment by rogue417** [comment]
Oh yeah!  And wouldn't you know it worked like a charm!  Obviously the 'invisible' chromeOS upgrade disabled an important part of my crouton.  Thankfully your assistance helped to me re-install it.  And everything - including my daughter's Minecraft, is right where we left it!  Given all this wouldn't it have been simpler to simply copy and paste the TTY0 that was missing into the right spot, or am I exercising ignorance here?

**Comment by divx118** [comment]
When your device has switched to freon TTY0 will be not there anymore. You needed another way to start your x-server after the chromeos update, the crouton update did that transition for you. It is best practice to perform a crouton update after every chromeos update.
