### ISSUE TITLE
Trusty Unity  install freezing Chomebook when logging out

### ISSUE THREAD

**Issue by mojo6911** [dnschneid/crouton#1739]
I have installed trusty with unity and chrome targets. When I logout of unity, it freezes my entire chromebook. Also, when using ctrl shift alt F1, it takes two key presses to switch back to the chroot from chrome os. Not sure if that has anything to do with it.

Is there a log or something I can see to try to troubleshoot?

**Comment by tedm** [comment]
@mojo6911 are you sure you are logging out as in exit from the chroot shell? Some DEs lets you "power off" and will shut down the whole chromebook from the chroot.

**Comment by mojo6911** [comment]
Yes, I am hitting "log out" and then confirming logout. It exits back to ChromeOS, but it is completely frozen. No mouse or keyboard response, whatsoever.

**Comment by tedm** [comment]
@mojo6911 is the chromebook on or off? any lights or signs that it is on?

**Comment by mojo6911** [comment]
Yes, the screen is powered on. I see the ChromeOS, just as I left it, but it is completely frozen. I have to hold down the power button and turn it back on.

**Comment by tedm** [comment]
@mojo6911 try making a chroot with xfce, if xfce logs out ok, and leaves ChromeOS up and usable, then unity could be broken.

**Comment by divx118** [comment]
@mojo6911 Please give the output of `croutonversion` This sounds like #1475 if so then please close this issue it is tracked there.

**Comment by mojo6911** [comment]
chronos@localhost / $ sudo enter-chroot -n trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)b0b@localhost:~$ croutonversion
crouton: version 1-20150511154233~master:392b84e4
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,unity,chrome
host: version 6812.83.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Mon Apr 27 10:22:23 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

**Comment by divx118** [comment]
@mojo6911 Yep same issue as #1475 . Best solution if you want to exit the chroot, is to switch to chromeos and press ctrl-c in the shell window where you started the chroot. Just don't use the logout.  Please close this issue since it is already tracked in #1475. Thanks.

**Comment by giliammc** [comment]
i had the same issue and closing the laptop and opening it backup usually fixed the problem and if it didn't i plugged in an external mouse
