### ISSUE TITLE
charles proxy doesn't work in trusty chroot

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1740]
This isn't a big deal but I'm curious.  The charles proxy didn't work in my trusty chroot.  It didn't show any traffic and the proxy client couldn't talk to anything.  I had to drag out an old windows laptop (shudder). This is the first time I've had to run windows since I switched to crouton two months ago.

Anyway, this is surprising to me.  I thought the crouton networking was full-featured, and a proxy is not rocket science.  Any ideas why this wouldn't work?

**Comment by Tuxerito** [comment]
Maybe need root privileges or need open ports.

I am user in some forums and we always ask to the users to give all possible info, for example if they have problems using an app then give us logs, app version, how the app was installed, how they are running the app, error messages, config files, what thing they tried to solve the problem, system config,  hardware info, network settings ,etc.

Probably I can't help but other users can help you more easy if you give more info. Just as advice.

**Comment by mark-hahn** [comment]
> other users can help you more easy if you give more info

Yeah, sorry about that.  I was just curious if anyone knew of an architectural problem in how crouton or chromeos does networking.  I wasn't really looking for a "fix".  Just curious.

I don't need this anymore but if anyone if lurking here is my setup.

Chromebook pixel 2015
trusty chroot, no desktop
