### ISSUE TITLE
Corrupted mouse Unity 2015 Pixel

### ISSUE THREAD

**Issue by fortinj1354** [dnschneid/crouton#1741]
So I've been having the same corrupted mouse cursor issue that it seems a lot of other people are having (using Trusty Unity on the new Pixel). Every time when switching back to unity I have the issue, but I have found that for some reason, with a 100% reproduction rate on my end, if I type a single character into xterm at any point after switching back to unity, it fixes the mouse issue and stays fixed until I switch to chromeos and back again. I have not updated my graphics drivers as seen here #1519 and actually discovered this behavior while I was getting ready to do this.

**Comment by kellevan** [comment]
Update the drivers, and then report back if it is is still an issue.

I suggest restarting your chroot after adjusting your drivers.

**Comment by hotpocket** [comment]
issue exists for me as well on a recent install

**Comment by dnschneid** [comment]
Yeah, hasn't been fixed yet.  Your experience seems to match my workaround: https://github.com/dnschneid/crouton/issues/1519#issuecomment-97631206
