### ISSUE TITLE
Cannot add Crouton Integration Extension to 43.0.2357.52 (Official Build) beta (64-bit)

### ISSUE THREAD

**Issue by imbigfella** [dnschneid/crouton#1742]
I have been using Crouton In A Tab (criat) for a few months now.  I really love it.  Today, I booted up my Chromebook and couldn't get to my chroot.  It seems that the chroot boots in the background (as intended) but the extension is broken.

![screenshot 2015-05-13 at 09 09 01](https://cloud.githubusercontent.com/assets/11049985/7616851/e2239ade-f964-11e4-9d0c-b31789743c50.png)

I attempted to remove and reinstall the extension, but I get the following error

![screenshot 2015-05-13 at 11 41 36](https://cloud.githubusercontent.com/assets/11049985/7616890/12e22b40-f965-11e4-9b77-41b7205ec8c7.png)

I powerwashed the device, but still am unable to install the Extension.  The link refrence I am using to attempt to install the Extension is https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom 

My Chrome Version is 43.0.2357.52 (Official Build) beta (64-bit)

**Comment by dnschneid** [comment]
You might be out of disk space...
