### ISSUE TITLE
Hisense Chromebook won't start X

### ISSUE THREAD

**Issue by unrulycow** [dnschneid/crouton#1743]
I have one of the $150 Hisense Chromebooks from Walmart and the crouton install appears to go smoothly, but X won't start.   It's likely an issue with drivers for the new Rockchip RK3288 CPU.  I tried with Jessie and Sid and have the same problem.  Does anyone know if there are working drivers for this chip?  

(sid)paul@localhost:~$ croutonversion
crouton: version 1-20150511154233~master:392b84e4
release: sid
architecture: armhf
xmethod: xorg
targets: gnome-desktop
host: version 6812.83.1 (Official Build) stable-channel veyron_jerry
kernel: Linux localhost 3.14.0 #1 SMP Tue Apr 28 20:31:59 PDT 2015
armv7l GNU/Linux
freon: no
(sid)paul@localhost:~$ startgnome

X.Org X Server 1.17.1
Release Date: 2015-02-10
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.14.0 #1 SMP Tue Apr 28 20:31:59 PDT 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=4f12a684-d69e-0e4e-8226-c50452ecf563/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 2506752 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2506752 alg=sha1 root_hexdigest=fd2a8037d67e2854cb023b20f579789605ae8acc salt=0c69e901d064e73b82a891fe5ef838ab12c88dbeeed74ff707a0cf55a4a62eb9" noinitrd vt.global_cursor_default=0 kern_guid=4f12a684-d69e-0e4e-8226-c50452ecf563  
Build Date: 05 May 2015  02:47:54AM
xorg-server 2:1.17.1-2 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed May 13 13:58:58 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
MESA-LOADER: malformed or no PCI ID
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/rockchip_dri.so: cannot open shared object file: No such file or directory
failed to load driver: rockchip
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory
failed to load driver: kms_swrast
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

**Comment by divx118** [comment]
XMETHOD xorg doesn't work for arm devices you need to use XMETHOD xiwi. I would try first with a xfce DE. `sudo sh ~/Downloads/crouton -r jessie -t xfce,xiwi` You can try updating your current chroot with `sudo sh ~/Downloads/crouton -u -t xiwi -n jessie` to see if gnome will work fast enough for you, but I think it will be to heavy. BTW you could also update your current chroot with -t xfce,xiwi or some other DE to test different desktop environments.

BTW I am wondering if it should have give you a warning ... that xorg is not supported.

**Comment by dnschneid** [comment]
It really shouldn't be selecting xorg to begin with.  What really needs to happen is #1721, but I need to dig through a bunch of test failures...

**Comment by FlashnRom** [comment]
Any fix for this yet?
