### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by brw31415** [dnschneid/crouton#1745]
chronos@localhost /media/removable/USB Drive $ sudo sh bin/startxfce4 -n trusty4
Entering /media/removable/USB Drive/chroots/trusty4...
-su: 26: [[: not found
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Mon Apr 27 10:23:37 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4a211cb5-0d20-1e46-aca5-11a9bf67f6a3/PARTNROFF=1 hashtree=PARTUUID=4a211cb5-0d20-1e46-aca5-11a9bf67f6a3/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=6181af1357991b3b9bdc63c62200c9c8f43ed73c salt=3122153d7cd99fa26e7db14046aeb06c369dfc94b7095714eb0ffcdb337de7ab" noinitrd vt.global_cursor_default=0 kern_guid=4a211cb5-0d20-1e46-aca5-11a9bf67f6a3 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed May 13 16:49:07 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/X (xorg_backtrace+0x48) [0x7ffa22c1a848](EE) 1: /usr/bin/X (0x7ffa22a71000+0x1ad539) [0x7ffa22c1e539](EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7ffa21b6d000+0x10340) [0x7ffa21b7d340](EE) 3: /usr/bin/X (0x7ffa22a71000+0xb57a6) [0x7ffa22b267a6](EE) 4: /usr/bin/X (xf86BusProbe+0x9) [0x7ffa22afa099](EE) 5: /usr/bin/X (InitOutput+0x74d) [0x7ffa22b086fd](EE) 6: /usr/bin/X (0x7ffa22a71000+0x59bab) [0x7ffa22acabab](EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7ffa205adec5](EE) 8: /usr/bin/X (0x7ffa22a71000+0x451ee) [0x7ffa22ab61ee](EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

**Comment by wlalele** [comment]
You should try updating crouton
Use : *crouton -n CHROOTNAME -u*
