### ISSUE TITLE
ChromeOs Freezes when using shift-ctrl-alt-back

### ISSUE THREAD

**Issue by ScriptMonkey00** [dnschneid/crouton#1746]
I'm still new at using crouton, so I am sorry if this is a known/fixable issue on my side, but I couldn't find any reference to it.

I've tried using an encrypted chroot running trusty with xfce, then when I saw the problem I tried a more generic setup, using standard crouton setup (using default precise) with lxde and no encryption.  The issue repeats itself in both.

I've figured out that if I use ctrl-alt-next to go to the cli, then ctrl-alt-back or ctrl-alt-refresh to hop through chroots it works fine.  From the chroot I can use ctrl-alt-shift-next to get back to the ChromeOs, but if in the chromeos I hit shift-ctrl-alt-back it instantly freezes the OS.  The mouse cursor vanishes and I can't seem to do anything,  Alt-tab does nothing, but ctrl-alt-next still works, so I can still hop to cli or to my ubuntu chroot.

Did I do something wrong in my setup, is this a bug, or is this a new gotcha from a ChromeOS update?

Thanks for the time.

**Comment by divx118** [comment]
See #1475 if it is the same then you can close this one. Thanks

**Comment by ScriptMonkey00** [comment]
I don't believe that is the same issue. This one I still have control of my keyboard, just not the chromeOS.

What I mean is after the "Freeze" I can hit ctrl-alt-next and get to the chromium login screen, then ctrl-alt-next from there to get back to my ubuntu chroot.

**Comment by divx118** [comment]
Can you post the output of `croutonversion` in the chroot?

**Comment by ScriptMonkey00** [comment]
Sure:

crouton: version 1-20150511154233~master:392b84e4
release: trusty
architecture: armhf
xmethod: xorg
targets: lxde-desktop,extension
host: version 6812.88.0 (Official Build) stable-channel veyron_speedy
kernel: Linux localhost 3.14.0 #1 SMP Fri May 8 13:57:03 PDT 2015 armv71 armv71 armv71 GNU/Linux
freon: no

I typed those in, hope I got it all correct. 

Side note,  I'm actually returning this chromebook because the ARM architecture doesn't mesh with the programs I need to run in Ubuntu, and will be getting an i3 which may actually solve both problems.  (it's a 2 week delivery or so, though)

**Comment by divx118** [comment]
I still think it could be related to #1475. Probably will be resolved when the device is fully transitioned to freon. You can take a look at the extension and see if there is an unknown display running. Normally it should only list chromeos and your chroot.

**Comment by ScriptMonkey00** [comment]
I was actually typing it because I was logged in on a different machine, not because I couldn't copy/paste :)  Side note, the device has already been sent back to the vendor so I can't check displays, or wait for the freon upgrade to happen.  Since I can't reproduce the error without that device, I'll close this, but thank you @divx118 for all the help and troubleshooting :)
