### ISSUE TITLE
chrome os screen colour became negative 

### ISSUE THREAD

**Issue by Whoopywhoop** [dnschneid/crouton#1747]
so after I installed crouton, a few days later suddenly the chrome os screen comes out negative coloured. Thankfully the xfce part is fine.
I tired to search about this issue but it's kind of hard cuz when I type negative it's never about the screen being negative.
Help please!

**Comment by DennisLfromGA** [comment]
Just recently saw this and was wondering if it's still a problem?

**Comment by dnschneid** [comment]
Output of `croutonversion` please.

**Comment by Whoopywhoop** [comment]
I don't know why but it's now all back to normal haha
