### ISSUE TITLE
question: how to reset the keyboard overlay

### ISSUE THREAD

**Issue by stsquad** [dnschneid/crouton#1749]
I've lost the ability to hist search+arrows for page up and down and AltGr+2 seems to have mysteriously stopped working as well. I've tried re-installing the keyboard extension as well as manually tweaking the keyboard /etc/default/keyboard. Could we add some instructions to the wiki on how to restore the default keyboard extension functionality?

**Comment by mark-hahn** [comment]
This may help:  https://github.com/dnschneid/crouton/issues/1558

**Comment by stsquad** [comment]
As far as I can tell everything is set however one interesting thing seems to be I only see Overlay_1 events when I lift the key up (I see both up and down events together). I wonder if this helps with the diagnosis?

**Comment by stsquad** [comment]
This is what xkbtool reports:

    Setting verbose level to 10
    locale is C
    Trying to load rules file ./rules/evdev...
    Trying to load rules file /usr/share/X11/xkb/rules/evdev...
    Success.
    Applied rules from evdev:
    rules:      evdev
    model:      chromebook
    layout:     gb
    Trying to build keymap using the following components:
    keycodes:   evdev+aliases(qwerty)
    types:      complete
    compat:     complete+chromebook
    symbols:    pc+gb+inet(evdev)+chromebook(overlay)
    geometry:   pc(pc104)
    xkb_keymap {
            xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            xkb_types     { include "complete"	};
            xkb_compat    { include "complete+chromebook"	};
            xkb_symbols   { include "pc+gb+inet(evdev)+chromebook(overlay)"	};
            xkb_geometry  { include "pc(pc104)"	};
    };
