### ISSUE TITLE
edit-chroot -m breaks on.... meteorjs..?

### ISSUE THREAD

**Issue by j6k4m8** [dnschneid/crouton#1752]
The machine had Meteor.js installed on it. And the move (`edit-chroot -m NEW_LOCATION`) failed horribly (after probably ten hours of waiting). This is the only output I've got. Lenovo Chromebook, Ubuntu (Trusty). After the move, sudo enter-chrooting fails; `no chroots found in /mnt/stateful_partition/crouton/chroots`. Bummer. The new location was on an ext4-formatted 64GB usb drive.

Suggestions and help welcome, but I'm hoping to help others avoid this problem. Happy to give any other info you'd like.

![screenshot 2015-05-15 at 11 49 39 pm](https://cloud.githubusercontent.com/assets/693511/7664587/37f3115c-fb5d-11e4-84b4-6112ad5833a4.png)

**Comment by dnschneid** [comment]
Could you please describe the steps you took and the exact commands you put in?

**Comment by j6k4m8** [comment]
Unmounted (just to be sure) and then moved:
```
sudo unmount-chroot -a
sudo edit-chroot -am /media/removable/U/.chroots/trusty-migratory
```

Afterward, `sudo enter-chroot -c /media/removable/U/.chroots/` results in:

```
Entering /media/removable/U/.chroots/trusty-migratory...
chroot: failed to run command 'su': No such file or directory
WARNING: starting chroot system dbus daemon failed with code 127
chroot: failed to run command 'su': No such file or directory
WARNING: /etc/rc.local failed with code 127
chroot: failed to run command 'su': No such file or directory
Unmounting /media/removable/U/.chroots/trusty-migratory...
```

**Comment by j6k4m8** [comment]
closing this as I've been unable to reproduce it a second time
