### ISSUE TITLE
Can't get into chroot; dependency problems

### ISSUE THREAD

**Issue by leeko** [dnschneid/crouton#1755]
Hi,

I restarted my lenovo yoga II chromebook, and after restart was unable to get into my xfce4 ubuntu chroot. The error message was for X, and after googling I understood it had happened after an update. To fix it, I ran the command:

sudo sh ~/Downloads/crouton -u -n precise

But it also returns an error message:

dpkg: dependency problems prevent configuration of openjdk-7-jre:amd64:
 openjdk-7-jre:amd64 depends on openjdk-7-jre-headless (= 7u79-2.5.5-0ubuntu0.14.04.2); however:
  Version of openjdk-7-jre-headless:amd64 on system is 7u75-2.5.4-1~trusty1.

dpkg: error processing package openjdk-7-jre:amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openjdk-7-jre:amd64
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I haven't been able to figure out how to fix dependency problems in dpkg without being able to enter the chroot. Please help! 

Thanks in advance for any help you can offer!

Lee

**Comment by divx118** [comment]
Use `sudo enter-chroot -n precise` to get to the command line of your chroot, resolve your error and try to update again.

**Comment by leeko** [comment]
That worked great, thanks.

Lee
