### ISSUE TITLE
Error in npm install -g generator- angular

### ISSUE THREAD

**Issue by vijayaragavan123** [dnschneid/crouton#1756]
i got this error pls any one help me 

npm WARN excluding symbolic link test/symlinks/dir1/dangling-symlink -> does-not-exist
/usr/bin/generate -> /usr/lib/node_modules/generator/bin/index.js
/usr/bin/generator -> /usr/lib/node_modules/generator/bin/index.js
npm WARN unmet dependency /usr/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/file-utils requires lodash@'~2.1.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.2
npm WARN unmet dependency /usr/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/file-utils requires isbinaryfile@'~0.1.9' but will load
npm WARN unmet dependency /usr/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/isbinaryfile,
npm WARN unmet dependency which is version 2.0.4
generator@1.0.1 /usr/lib/node_modules/generator
├── colors@0.6.2
├── async@0.2.10
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── fs-extra@0.6.4 (jsonfile@1.0.1, rimraf@2.2.8, ncp@0.4.2, mkdirp@0.3.5)
├── findit@0.1.2 (seq@0.3.5)
├── replace@0.2.10 (colors@0.5.1, minimatch@0.2.14, nomnom@1.6.2)
└── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, winston@0.8.3,

**Comment by tonyxue** [comment]
Those are warnings and seems your installation succeed, didn't it?

Is that a Crouton related issue?

**Comment by vijayaragavan123** [comment]
thank you iam new to yeoman 
how to check is it installed or not

**Comment by dnschneid** [comment]
Not crouton related...see #262

**Comment by tonyxue** [comment]
@vijayaragavan123 it did not return any error and node showed you the structure of modules.

Please navigate to the nodejs community for more specific questions.
