### ISSUE TITLE
touch on xiwi

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1757]
I have a chromebook pixel 2015 and I was hoping to use the touch target.  I am trying to get it to work in the atom editor with no luck.  The Atom package to add touch support is new and may be the culprit.  

I'd like to figure out whether the touch events get to the x-window.  Is there an app that is known to work with touch in a xiwi window?

What is the touch target supposed to do?  I couldn't find anything in the wiki or this forum.

**Comment by mark-hahn** [comment]
Also see https://github.com/russlescai/atom-touch-events/issues/10#issuecomment-102736550

**Comment by dnschneid** [comment]
Currently, touch events aren't passed through xiwi.  The touch target is only effective with xorg, and even then, it just adds standard gestures like 1-finger scrolling.

I'll keep this open as an enhancement request to support passing through touch events with xiwi.

**Comment by mark-hahn** [comment]
Thanks.

I found out from the author that he uses the native browser touchstart and touchmove events.  So these would be my personal enhancement request.
