### ISSUE TITLE
Can't switch back to ChromeOS after starting up

### ISSUE THREAD

**Issue by StannisZhou** [dnschneid/crouton#1758]
The chroot was installed using the command _sudo sh ~/Downloads/crouton -r trusty -t audio,keyboard,extension,xfce_. Works fine when first installed, but the issue started to appear after I installed some softwares (haven't quite figured out what exactly caused the problem). Can start xfce normally, but when I try to switch back to ChromeOS by pressing Ctrl-Alt-Shitf-Back/Forward, nothing happens. Have tried updating the crouton using _sudo sh ~/Downloads/crouton -n trusty -u_. No errors in the update, but the update didn't solve anything.
## When I run _sudo startxfce4_, the output is as follows:

Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri May 8 12:34:25 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=190c0267-2f09-cf47-bf15-c322ca4428a6/PARTNROFF=1 hashtree=PARTUUID=190c0267-2f09-cf47-bf15-c322ca4428a6/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=3d9974ce8fbae72f24274140b43ab50ba92031cf salt=08d221945b21db934b54af812711bbba821103d08b68de4a4786417d8be7c700" noinitrd vt.global_cursor_default=0 kern_guid=190c0267-2f09-cf47-bf15-c322ca4428a6 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.0.log", Time: Sun May 17 02:43:42 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
xf86: found device 0
xf86: found device 0
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:21552): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:21552): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[06:43:45][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:46][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:47][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:48][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:49][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:50][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:51][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:52][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:53][warn] QT Warning: QFile::open: File (/home/zhouguangyao/.local/share/data/Mega Limited/MEGAsync/megasync.lock) already open
[06:43:54][warn] MEGAsync is already started

(xfce4-terminal:21502): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 2 (X_ChangeWindowAttributes)
  Resource id:  0x280002c

(xfce4-session:21450): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 02:45:07: SIGHUP received: restarting...
xscreensaver: 02:45:07: running as zhouguangyao/zhouguangyao (1000/1000)

xfce4-volumed: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
xscreensaver: 02:45:07: Can't open display: :0.0
xscreensaver: 02:45:07: running as zhouguangyao/zhouguangyao (1000/1000)

xscreensaver: 02:45:07: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

```
          http://www.jwz.org/xscreensaver/faq.html
          http://www.jwz.org/xscreensaver/man.html
```

(EE) Server terminated successfully (0). Closing log file.
.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
## The output of _sudo enter-chroot -n trusty croutonversion_

Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150516123952~master:8f7245cc
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,keyboard,extension,xfce
host: version 6812.88.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 12:34:25 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by snowlarbear** [comment]
an extra psuedo-data point, i have similar issue. pretty sure it started after i updated the MESA drivers, as was suggested to fix a battle.net/hearthstone problem i was seeing.

**Comment by Snowflake6** [comment]
I haven't used my Crouton in a month or so, so I ran an update and now i'm seeing very similar behaviour.  Unity starts fine, runs fine, but I can't get out without a forced reboot.  Logout returns me to a black screen, CAS-Left and -Right do switch me to a black screen and back to Unity (at least a couple of times), but ChromeOS seems to disappear once i've started the crouton session.

Shutdown from inside the crouton does seem to shut down the laptop, so at least I have a semi-controlled way to get out... Shutdown, then power up the laptop again and re-login.

Oh, laptop is an ACER C720P with 4GB RAM and upgraded with 128GB SSD.  Here's the croutonversion output:

---
chronos@localhost / $ sudo enter-chroot -n utopic croutonversion
Entering /mnt/stateful_partition/crouton/chroots/utopic...
crouton: version 1-20150604154515~master:91b3e350
release: utopic
architecture: amd64
xmethod: xorg
targets: cli-extra,audio,chrome,core,keyboard,touch,unity
host: version 6812.88.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 12:21:21 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/utopic...
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
I know this is not an elegant way to handle this problem but, in your chroot, jump to a shell and enter `croutoncycle cros`, that should put you back in Chrome OS. You can then use the 'crouton integration' extension and 'click' on your chroot to get back to it.
