### ISSUE TITLE
Using '-X' option to uninstall xiwi when entering chroot not working

### ISSUE THREAD

**Issue by ssyyddii** [dnschneid/crouton#1759]
Xiwi is working fine. initially installed it using sudo sh ~/Downloads/crouton -t xiwi -u

when I want to start xfce4 without the xiwi I am using the command:
sudo startxfce4 -X xorg

I get the following error:
chronos@localhost / $ sudo startxfce4 -X xorg
/mnt/stateful_partition/crouton/chroots/precise does not contain XMETHOD 'xorg'

Any suggestions? What am I doing wrong?
Do I need to remove my chroot and reinstall it normally then run:
sh ~/Downloads/crouton -u -t xorg -n precise  
to change the "target" from 't-xiwi'  which was the original install command to 't-xorg'?

I am a nubie nubie. Expert newbie. please help

**Comment by divx118** [comment]
You should update your chroot first with `-t xorg` to add xorg then you can switch with -X between xiwi and xorg.  
So `sudo ~/Downloads/crouton -u -t xorg -n precise` This will make xorg the default. Now you can use `sudo startxfce4 -X xiwi` to start chromeos in a window. `sudo startxfce4` or `sudo startxfce4 -X xorg` will both run your chroot with XMETHOD xorg.

**Comment by ssyyddii** [comment]
Not working
I reinstalled the chroot, updated it and ran your script. I don't know what the problem is this is what I get:

chronos@localhost / $ sudo ~/Downloads/crouton -u -t xorg -n precise
sudo: /home/chronos/user/Downloads/crouton: command not found
chronos@localhost / $

**Comment by tedm** [comment]
@ssyyddii try 

`sudo sh ~/Downloads/crouton -u -t xorg -n precise`

**Comment by ssyyddii** [comment]
wow. it worked.
what does the 'sh' command do?
I'm trying to get my head around the very simple commands in crouton and understand the language.  I'm just a user and not a coder at all. but trying. I hate windows.

**Comment by tedm** [comment]
@ssyyddii it tells the kernel you are running a shell script, and to just run it with the default shell.

Some scripts contain this in the first line, such as:

`#!/bin/bash` for the common bash shell, but the sh way doesn't require that in case someone is running a different shell such as zsh, tcsh, csh, etc.

**Comment by divx118** [comment]
@tedm, @ssyyddii  my mistake a typo corrected it above.

**Comment by tedm** [comment]
@ssyyddii I might have been wrong about sh - though I doubt it will affect your running crouton, you just need it.

I think sh at one time meant to use the bourne shell, and at one time sh --version would tell you that or more about it.

Now I think sh may be used to imply POSIX compliance. This is very important, since when time traveling, we can use crouton with irix, solaris, aix, dos, and other POSIX compliant OS's.

Someone please correct me if I am wrong ;)

**Comment by ssyyddii** [comment]
"You should update your chroot first with -t xorg to add xorg then you can switch with -X between xiwi and xorg."
I finally figured it out. 

The instructions aren't  very clear . Really. Not clear.
this is how it works:
Once 't-org' target is installed then xiwi runs by default and you enter the chroot using only
'sudo startxfce4' , not :  'sudo startxfce4 -X xiwi' (doesn't work although is stated as so)
to switch back to xorg or said in another way running the chroot without xiwi use:
sudo startxfce4 -X xorg

Crouton is Super cool.

thanks to everyone for their input

**Comment by tedm** [comment]
@ssyyddii do you mean once `xiwi` target is installed? If so, then I agree.

I think the latter part that doesn't work for you would work, if you installed xorg last, but wanted to revert to xiwi (e.g. xorg just gives a black screen of death...)

**Comment by dnschneid** [comment]
Explicitly using `sh` allows you to avoid issues with the noexec flag that's on most filesystem mounts in Chromium OS.

Glad you got things working.

**Comment by tedm** [comment]
Thanks for this clarification.

**Comment by T55189** [comment]
I'd love to be able to switch between xiwi and xorg but using the above method is not working. I installed with xiwi and 'sudo startunity' opens in a new window just fine. So I tried installing xorg with 'sudo sh ~/Downloads/crouton -u -t xorg -n precise' and I get 'E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.'

What now?
