### ISSUE TITLE
GPU acceleration in Xiwi

### ISSUE THREAD

**Issue by ssyyddii** [dnschneid/crouton#1760]
Would it be possible for someone to add GPU acceleration to Xiwi?
It would be almost perfect.  Then  could run games and vlc

**Comment by dnschneid** [comment]
That'd be awesome, but it's very difficult to implement.  I'll keep this open but don't expect anything anytime soon.

**Comment by ssyyddii** [comment]
Thanks. Well, if you don't ask you don't get.
Crouton is a trip. Thanks for all your hard work.
Syd
