### ISSUE TITLE
does google chrome work in xiwi?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1761]
I created a new chroot with

```
sudo sh ~/Downloads/crouton -t chrome,xiwi,cli-extra,extension,keyboard,touch -n test
```

When I execute `xiwi google-chrome` I get the black screen of death.  Is this supposed to work?

**Comment by dnschneid** [comment]
That should work, if you launched it inside the correct chroot.  What do you mean "black screen of death"?

**Comment by mark-hahn** [comment]
>  if you launched it inside the correct chroot.

It was a brand-new chroot that used that set of targets I showed.  Maybe I
should try it in a desktop.

>  What do you mean "black screen of death"?

Sorry, I used a little poetic license.  Whenever I have a problem with xiwi
it manifests as the window appearing with black contents that never
finishes loading.  I'm talking about problems like stuck lock files and
apps missing some gui thing they need.  The main app I use will often stop
loading until I leave and re-enter the chroot.  So I see the black screen a
lot.

I'm not referring to a Crouton problem.  I'm sure it is usually the app.

**Comment by dnschneid** [comment]
Usually you'll see that black screen if the command fails to load.  xiwi says "well, the command existed, so maybe it forked" and then waits forever (until you close the window, at which point it gives up).

If you run google-chrome in a way that causes it to immediately exit, you'll hit that situation.  Possible causes include another instance of Chrome running in a different X server but with the same user profile (chrome will launch a new tab in the running instance), running Chrome as root (which it rejects), or some other issue that hopefully Chrome spat out a message complaining about.

**Comment by mark-hahn** [comment]
> or some other issue that hopefully Chrome spat out a message complaining
about.

I hadn't really spent any effort chasing it down.  I'll do that when I get
some time.

BTW, the term "black screen of death" was coined here by @alicein1derland a
few weeks ago.  Don't blame me.  (grin)    @tedm used it a few hours ago so
I fear we are stuck with it.

I've never used a linux desktop.  What happens when apps hang while opening
in that environment?  In Windows usually no window appears at all.

**Comment by mark-hahn** [comment]
Here is the console output when I try to start chrome with `xiwi google-chrome`.  Maybe someone here can interpret it?

```
05/17/15 20:46:37 - ERROR: FYI: You are using i3 version 4.1.2 (2012-01-27, branch "release-4.1.2")
Starting i3-nagbar due to configuration errors
button with label *edit config* and action *i3-sensible-terminal -e sh -c "i3-sensible-editor \"/etc/crouton/xiwi.conf\" && i3-msg reload"*
now 1 buttons
button with label *show errors* and action *i3-sensible-terminal -e i3-sensible-pager "/tmp/i3-root.mE5O0W/errorlog.20616"*
now 2 buttons
[1:1:0517/204637:ERROR:image_metadata_extractor.cc(111)] Couldn't load libexif.
[1:1:0517/204637:ERROR:nacl_fork_delegate_linux.cc(314)] Bad NaCl helper startup ack (0 bytes)
awk: cannot open /proc/20749/maps (No such file or directory)
popen2: child exited with status 2
find_shm: Error running helper.
write_image: Cannot find shm, moving on...
socket_client_read_frame_header: Connection close from WebSocket client.
```

**Comment by tedm** [comment]
@mark-hahn I can't try it on my arm, but try running it as a user ($) and do a 

`sudo google-chrome-stable &` 

btw, does it work with xorg?

**Comment by mark-hahn** [comment]
- `xiwi google-chrome`  --> shows the black window
- `xiwi google-chrome-stable` --> shows the black window
- `sudo google-chrome &` --> starts a process and nothing happens
- `sudo google-chrome-stable &` --> starts a process and nothing happens
- `sudo xiwi google-chrome &` --> starts a process and nothing happens
- `sudo xiwi google-chrome-stable &` --> starts a process and nothing happens

> btw, does it work with xorg?

I haven't tried xorg.  I'm embarrassed to say, but I don't know what the xorg target does.  I couldn't find it in the wiki.  Can you point me to some docs?

**Comment by tedm** [comment]
@mark-hahn after returning to a prompt, try typing jobs at the $ prompt and if google-chrome-stable is running, then type fg x where x is the job related to the process like fg 1 [enter] at the $ prompt.

by just running crouton and updating your chroot with the xorg target, you will lose xiwi's windowing functionality by default, but you'll still have xiwi, will just have to always specify it and you'll have to hot-key between chromeos and chroot with xorg and no windowing.

But if you want to try, just type:

sudo sh ~/Downloads/crouton -u -t xorg -n [name of chroot]

You also might find fonts and screen resolution is different than xiwi, so backup your chroot, or be prepared to create a new one, with xiwi, if you're used to xiwi. I can't help but wonder if there is a conflict with running chrome in the chroot, since it is running on the host, perhaps you can login to your host as guest, and have minimal windows open, like just a ctrl alt t crosh shell and try.

**Comment by tedm** [comment]
also try `nice google-chrome-stable` which will start and run the process at a reduced priority, but that might enable it to run.

If you're at a $ prompt you probably don't need to use sudo

**Comment by mark-hahn** [comment]
I will look more into this tomorrow.

Can someone point me to a description of what the xorg target is?  I know
xorg is an implementation of X-windows, but isn't every gui app, xiwi or
desktop, run on X-windows?

**Comment by tedm** [comment]
xorg is one of many X servers in linux, and is usually the name of the config file, like /etc/X11/xorg.conf.

Before X11, there was XFree86, which used different config files. As monitors, gpus, and the OS's change, there are new X11 type X11 drivers, but I think xorg was and is the default for x86 chromebooks, but the ARM systems always needed Xephyr. Now, we have freon and frecon in ChromeOS, so soon Xephyr won't work on arm, and will just have freon/frecon in ChromeOS, and xiwi, and I think there is work in progress for an xorg or freon variant or native non-windowed xorg type driver for ARM devices. Xorg in crouton has typically been reported as faster than xiwi, with some hw acceleration on x86 devices, but xiwi has the windowing capability, for the whole DE, or just apps (except for your google chrome issue, so far). 

There is probably a better answer out there than mine above.

**Comment by mark-hahn** [comment]
Thanks for the trouble for your response.  I am really enjoying the xiwi
windows but I'll try xorg as part of researching the chrome problem.
