### ISSUE TITLE
Unsure what to put in for 'Enter encryptsion paraphrase for presice'

### ISSUE THREAD

**Issue by pianoboy8** [dnschneid/crouton#1762]
Sorry, i'm new to this. I was using http://www.howtogeek.com/162120/how-to-install-ubuntu-linux-on-your-chromebook-with-crouton/ guide on how to install Ubuntu to my chromebook (intel), and it didn't mention something about a password nor an enter encryptsion paraphrase for presice message.
Before this it required a password, which I had to reset (which then worked), but I don't know how this portion works.
If someone could clear something up for me on how to do this I would be glad.
Log:
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ start-chroot xcfe4
bash: start-chroot: command not found
chronos@localhost / $ startxcfe4
bash: startxcfe4: command not found
chronos@localhost / $ startxfce4
enter-chroot must be run as root.
chronos@localhost / $ enter-chroot startxfce4
enter-chroot must be run as root.
chronos@localhost / $ sudo startxfce4
Password: 
Enter encryption passphrase for precise:

**Comment by pianoboy8** [comment]
Sorry I was trying to get the command by memory so ignore the first 3 messages.

**Comment by dnschneid** [comment]
When you created the chroot, you must have added `-e` and specified a passphrase at the very start.  If you can't remember the passphrase you set, you'll need to delete the chroot and start over.

**Comment by pianoboy8** [comment]
ty that was the the issue
I don't think I put anything in it so that's where the issues were,
