### ISSUE TITLE
Java does not work, ARM, Firefox.

### ISSUE THREAD

**Issue by goodroot** [dnschneid/crouton#1763]
My goal is to install Java for use in the browser, to operate a workplace VPN system.

The Chrmebook is an Acer with an ARM processor.

Have tired to install Java mnually, by syncing a .so file to the /plugins directory within Mozilla, no success.

Have tried all the openjdk6/7/8 packages, icedtea-X-plugins.

I can get it to where Firefox sees Java, via IcedTea, but attempting to verify or use Java causes the element to 'gray' out and the browser to become unresponsive.

Anyone able to  get Java operational on an Acer CB5-311 with ARM?

**Comment by YoshiDudeRox** [comment]
Alot of programs dont support ARM hope this helps 

Cheers

**Comment by asonawalla** [comment]
Same problem on the Asus c201 with precise and unity.  Will post back if I find a workaround.
