### ISSUE TITLE
Cannot enter chroot after setup, latest version, kali distro

### ISSUE THREAD

**Issue by whotooktwarden** [dnschneid/crouton#1764]
Attempted to install kali with targets xfce,core,audio,extension,chrome

chronos@localhost / $ sudo enter-chroot kali
Password: 
Entering /mnt/stateful_partition/crouton/chroots/kali...
-su: 1: kali: not found
Unmounting /mnt/stateful_partition/crouton/chroots/kali...

**Comment by divx118** [comment]
Use `sudo enter-chroot -n kali` Notice -n to specify that what follows is the chrootname.

**Comment by whotooktwarden** [comment]
This worked.
