### ISSUE TITLE
Error : target STRING not available

### ISSUE THREAD

**Issue by Hamerun** [dnschneid/crouton#1765]
Hello everyone,

First of all, I 'm sorry for my English because I'm French . This is a copy of my screen problem. 
I have an Acer Chromebook CB5-311 . 

![screenshot 2015-05-18 at 02 14 24](https://cloud.githubusercontent.com/assets/12488346/7672874/f8769d34-fd03-11e4-94cc-00661a61f55a.png)

I have a black page that opens in full screen for a second and then closes.
Can anyone help me please ?

thank you

**Comment by tedm** [comment]
@Hamerun just poweroff and on. It appears you have another instance of the chroot running.

**Comment by dnschneid** [comment]
What command are you running?

**Comment by Hamerun** [comment]
@tedm : after a restart, i have the same problem :(
@dnschneid : i running this command : "shell" then "sudo startgnome"

**Comment by troymz** [comment]
i have this same problem.  ive been slowly installing stuff. steam, google chrome, kodi. then i did the update that popped up, rebooted and get same error. it loads, connects then target string error and closes.

**Comment by odococo** [comment]
Same problem here. After an update of Chrome OS and reboot, xiwi wasn't working anymore. I downloaded the latest crouton and crouton extension. Nothing changed. I managed to get it started with xephyr but i preferred a window to use crouton(and it was terribly slow with xephyr, i don't why).

I also tried to install another release. Xiwi isn't working with that either. This is the output of the terminal

/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: armhf
xmethod: xiwi
targets: xiwi,xephyr,xfce
host: version 7077.95.0 (Official Build) stable-channel nyan_big 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jul 14 23:44:39 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Error: target STRING not available
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

 The crouton integration is installed and enabled but somehow it's not working. Its log

:1	trusty
23:38:34	Connection established
23:33:20	Connection closed

Sometimes the output of the terminal is this

/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: armhf
xmethod: xiwi
targets: xiwi,xephyr,xfce
host: version 7077.95.0 (Official Build) stable-channel nyan_big 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jul 14 23:44:39 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
croutonwebsocket error: Error timeout
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
 Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...


"Error: target STRING not available" became "croutonwebsocket error: Error timeout".

Last thing. At the beginning i couldn't unmounting either so i forced it.

**Comment by dewood** [comment]
Similar to odococo, my chroot broke yesterday after lxde said I needed to restart after an update. The crouton extension will get a connection and say `:1 trusty`, then disconnect 4-8 seconds later, roughly coinciding with the appearance of `Error: target STRING not available` in the output.

 ```$ sudo enter-chroot croutonversion
Enter encryption passphrase for trusty: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,lxde-desktop,keyboard,extension,core,cli-extra,audio,chrome
host: version 7077.95.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Tue Jul 14 21:44:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...```

```$ sudo startlxde
Enter encryption passphrase for trusty: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Tue Jul 14 21:44:12 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-1 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="2 vboot none ro 1,0 2545920 bootcache noinitrd vt.global_cursor_default=0 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jul 24 10:20:32 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,lxde-desktop,keyboard,extension,core,cli-extra,audio,chrome
host: version 7077.95.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Tue Jul 14 21:44:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Error: target STRING not available
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...```

(I deleted a couple parameters from the kernel command line that appeared cryptographic in nature, guid/uuid/salt stuff)

I can post /tmp/Xorg.crouton.1.log output if need be as well, though it is lengthy.

**Comment by dewood** [comment]
I've been able to get back in using `$ sudo startlxde -X xorg`, but this obviously doesn't have the xiwi/extension integration.

**Comment by DennisLfromGA** [comment]
Having the webstore 'crouton integration' extension installed allows me to switch from Chrome OS into both 'xiwi' and 'xorg' chroots. In an 'xorg' chroot, you'll need to use the key combo <kbd>Ctrl+Alt+Shift+F1/F2</kbd> to get back to Chrome OS or `croutoncycle ...` of course.

Also, with the 'extension' target installed, even when using xmethod 'xorg', I still get cut-n-paste between the chroot and Chrome OS and vice versa.

**Comment by jhartzler** [comment]
I also have an Acer CB5-311 and have not been able to run through xiwi. I have been experiencing the same behavior of failing to connect, getting :1 trusty in the extension, then disconnecting, sometimes with Error: Target STRING not available

**Comment by moderatic-john** [comment]
I have an Acer CB5-311-T9XM and I have not been able to run through xiwi either. It can run through xorg no problem, just xiwi is not working.

Here is a list of things I have tried

 1. First I uninstalled and reinstalled my crouton extension in Chrome on my Chrome OS.
 2. I then made sure crouton the script was up to date
 3. I then just added the target xiwi to my existing installed crouton linux.
 4. Afterwards it still carried on to work with xorg but not with xiwi.
 5. So I thought, lets create a new target with xiwi in case my existing
    target was not working, that gave the same problem.

Here is the output of the crouton chrome extension:

    18:06:40	Connection closed
    18:06:38	Message received (R)
    18:06:38	Message received (PING191552)
    18:06:37	Message received (C4194308* Unknown :1 Default )
    18:06:37	Message received (C)
    18:06:37	Message received (C4194308* Unknown :1 Default )
    18:06:37	Message received (C)
    18:06:37	Sending window list request
    18:06:37	Sending window list request
    18:06:37	Message received (V2)
    18:06:37	Connection established

and here is the output from running the start "/usr/bin/startxfce4":

    Release Date: 2014-04-13
    X Protocol Version 11, Revision 0
    Build Operating System: Linux 3.2.0-67-highbank armv7l Ubuntu
    Current Operating System: Linux localhost 3.10.18 #1 SMP Tue Jul 28 16:51:23 PDT 2015 armv7l
    Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4fd09475-ac17-2a4e-ad37-0ca84e2e88d8/PARTNROFF=1 hashtree=PARTUUID=4fd09475-ac17-2a4e-ad37-0ca84e2e88d8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=8902b759cc79feede05b6f61d3da7f2d55336b64 salt=7b896b4877251713c9420118839b81e28cb16f7964e7223a4246ecfe5b216f3e" noinitrd vt.global_cursor_default=0 kern_guid=4fd09475-ac17-2a4e-ad37-0ca84e2e88d8  
    Build Date: 12 February 2015  02:55:07PM
    xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
    Current version of pixman: 0.30.2
            Before reporting problems, check http://wiki.x.org
            to make sure that you have the latest version.
    Markers: (--) probed, (**) from config file, (==) default setting,
            (++) from command line, (!!) notice, (II) informational,
            (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jul 31 18:06:30 2015
    (++) Using config file: "/etc/X11/xorg-dummy.conf"
    (==) Using system config directory "/usr/share/X11/xorg.conf.d"
    Initializing built-in extension Generic Event Extension
    Initializing built-in extension SHAPE
    Initializing built-in extension MIT-SHM
    Initializing built-in extension XInputExtension
    Initializing built-in extension XTEST
    Initializing built-in extension BIG-REQUESTS
    Initializing built-in extension SYNC
    Initializing built-in extension XKEYBOARD
    Initializing built-in extension XC-MISC
    Initializing built-in extension SECURITY
    Initializing built-in extension XINERAMA
    Initializing built-in extension XFIXES
    Initializing built-in extension RENDER
    Initializing built-in extension RANDR
    Initializing built-in extension COMPOSITE
    Initializing built-in extension DAMAGE
    Initializing built-in extension MIT-SCREEN-SAVER
    Initializing built-in extension DOUBLE-BUFFER
    Initializing built-in extension RECORD
    Initializing built-in extension DPMS
    Initializing built-in extension Present
    Initializing built-in extension DRI3
    Initializing built-in extension X-Resource
    Initializing built-in extension XVideo
    Initializing built-in extension XVideo-MotionCompensation
    Initializing built-in extension SELinux
    Initializing built-in extension XFree86-VidModeExtension
    Initializing built-in extension XFree86-DGA
    Initializing built-in extension XFree86-DRI
    Initializing built-in extension DRI2
    Loading extension GLX
    /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
    crouton: version 1-20150730171703~master:f8fdfb0c
    release: trusty
    architecture: armhf
    xmethod: xiwi
    targets: xiwi,xfce,audio,keyboard,core,cli-extra,touch
    host: version 7077.111.0 (Official Build) stable-channel nyan_big 
    kernel: Linux localhost 3.10.18 #1 SMP Tue Jul 28 16:51:23 PDT 2015 armv7l armv7l armv7l GNU/Linux
    freon: no
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Error: target STRING not available
    Cannot connect to extension, retrying...
    Cannot connect to extension, retrying...
    Unable to start display, make sure the crouton extension is installed
    and enabled, and up to date. (download from http://goo.gl/OVQOEt)
    Running exit commands...
    /usr/bin/xinit: connection to X server lost
    
    waiting for X server to shut down  Server terminated successfully (0). Closing log file.
    Hangup
    Hangup
    
    Unmounting /media/removable/Storage/Linux_ARM/Default...
My chrome is version:
 
Version 44.0.2403.125
Platform 7077.111.0 (Official Build) stable-channel nyan_big
Firmware Google_Nyan_Big.5771.63.0

The architecture is ARM.

Hope this helps.

**Comment by grandrew** [comment]
This is an old ticket and it is likely unrelated to what is happening now after update. 
Same symptoms as above on nyan_big, need further investigating.

Also the `Error: target STRING not available` message is unrelated to the fact that the crouton intergration is no longer working as it seems to be coming from clipboard integraion: https://www.mail-archive.com/password-store@lists.zx2c4.com/msg00238.html

here is what comes from the crouton log:

```
00:56:53	Connection closed
00:56:53	Opening a web socket
00:56:48	Connection closed
00:56:39	Message received (R)
00:56:39	Message received (PING94328)
00:56:39	Message received (C6291460* Unknown :1 xiwi )
00:56:39	Message received (C)
00:56:39	Message received (C6291460* Unknown :1 xiwi )
00:56:39	Message received (C)
00:56:39	Sending window list request
00:56:39	Sending window list request
00:56:39	Message received (V2)
00:56:39	Connection established
```

this seems to be the same issue as #1940
