### ISSUE TITLE
Unable to boot into developer mode.

### ISSUE THREAD

**Issue by MrToshiaki** [dnschneid/crouton#1766]
Hello, I've recently removed developer mode from my chromebook, now I wish to re-enable it.
When I try ESC + REFRESH + POWER I am presented with no screen, so I opened a issue.

Thanks!

**Comment by dnschneid** [comment]
What model Chromebook?

**Comment by MrToshiaki** [comment]
Acer Chromebook C720.

**Comment by dnschneid** [comment]
And what do you see when you hold down ESC when pressing refresh/power?

**Comment by MrToshiaki** [comment]
Literally nothing.

**Comment by dnschneid** [comment]
You should probably e-mail the chromebook support forums...

**Comment by MrToshiaki** [comment]
.I've tried. They couldn't help.
