### ISSUE TITLE
My Downloads folder is wiped and my keyfile is gone. 

### ISSUE THREAD

**Issue by lucidbee** [dnschneid/crouton#1767]
I tried to get back into my ubuntu and the developer mode was gone. Not sure what had happened. Someone else was using my chromebook for awhile. 
So I reenabled developer mode and I found that my Downloads folder was missing. When I put in my sd card with ubuntu and tried to do a startUnity as I did before I got a message:
      Unable to find encryption key file /home/chronos/user/keyfile/trusty
That file is missing. 
(I had encrypted my ubuntu install.)
Can I get the ubuntu install back without the keyfile? Any help here? Thanks

**Comment by dnschneid** [comment]
No, sorry...the whole point of the keyfile is to keep your chroot inaccessible to those without it.  It's best to keep it backed up somewhere secure for these unfortunate kinds of events.  Google Drive is a reasonable place...
