### ISSUE TITLE
Chromebook 11 HP: "xorg target does not work on Samsung ARM devices"

### ISSUE THREAD

**Issue by WColt** [dnschneid/crouton#1769]
So yeah, i recently powerwashed my chromebook accidentally when i cleaned it. when i installed crouton again and downloaded xfce4, it refused to start because of the extension, then i got it and linux started but as a new window, which does not matter, but when i get to the top of the screen i get this notification box and that annoys me. so i tried to install xorg but i get this error.

**Comment by dnschneid** [comment]
#1415 is what you want to track
