### ISSUE TITLE
Desktop launch: clarify chroot being entered.

### ISSUE THREAD

**Issue by Hashmael** [dnschneid/crouton#1771]
So this is more of a UI thing, but perhaps when launching a desktop environment, there could be some sort of check to identify if that environment is installed on multiple chroots.
If it is, a prompt could indicate to the user that multiple chroots contain that desktop, and ask if they want to set a default chroot for that desktop. They could also choose between "ask every time", "ask every time the chroot/desktop situation changes", and "never ask again".
That might make it a bit simpler to get into the desktop of the desired chroot.
Hopefully this isn't too difficult or time-intensive.
Thanks.

**Comment by mark-hahn** [comment]
I always use `sudo enter-chroot -n chroot-name`.  I have an alias for each
one so I only have to type `chroot-name`.

**Comment by dnschneid** [comment]
Maybe `enter-chroot -t` could warn when multiple chroots meet the specified criteria?  I'd rather not have a prompt, though.

**Comment by Hashmael** [comment]
My concern is wrt the startkde/startxfce4/etc commands launched as sudo from the crosh shell; it would seem entering the chroot first (and then launching desktop as user) is the best way to avoid ambiguity. I didn't mean to overstep, I'll close and leave the matter at your discretion as to how to handle.

**Comment by dnschneid** [comment]
To clarify, I was talking about `enter-chroot -t` solely because the `start*` scripts simply wrap that command and specify `-t` to choose the first compatible chroot.  But yes, using `enter-chroot` yourself will guarantee you know what you're getting into.
