### ISSUE TITLE
cannot update chroot or use xorg (startxfce4 defaults to xiwi)

### ISSUE THREAD

**Issue by aus-tex** [dnschneid/crouton#1775]
I'm currently using arch/chroagh and it hasn't worked correctly since a recent chrome update.
https://github.com/drinkcat/chroagh

Any help on this would be greatly appreciated. I don't think chroagh is being updated so I wanted to see if you have any input. 

Here's what I'm seeing from the update command:

/usr/local/chroots/arch already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
xorg target does not yet work with Freon.

croutonversion output:

crouton: version unknown
release: unknown
architecture: unknown
xmethod: xiwi
xorg
x11
targets: x11,xorg,extension,xiwi,xfce,keyboard,cli-extra
host: version 6812.88.0 (Official Build) stable-channel peppy

**Comment by divx118** [comment]
@drinkcat is a bit busy at the moment, but chroagh is still alive. See #1201
