### ISSUE TITLE
intel(0): [drm] failed to set drm interface version: Permission denied [13].

### ISSUE THREAD

**Issue by gdm85** [dnschneid/crouton#1777]
I am using a trusty chroot, if I try to run ``startxfce4`` it fails:
```
[    46.582] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].
[    46.582] (EE) intel(0): Failed to claim DRM device.
[    46.582] (II) UnloadModule: "intel"
[    46.582] (EE) Screen(s) found, but none have a usable configuration.
```

If I do Ctrl+Alt+F1 after this error, and switch back with Ctrl+Alt+F2, then running same command will be successful.

[See full Xorg.1.log here](https://gist.github.com/gdm85/fc5a16668f3e0d4719e5)

I have checked the permissions of ``/dev/dri`` but they don't change with a login/logout, so obviously it's not that.

Is this is a known issue?

For the records: yes, I updated crouton after last ChromeOS update.

**Comment by gdm85** [comment]
Possibly related? https://github.com/Bumblebee-Project/Bumblebee/issues/580

**Comment by dnschneid** [comment]
Don't launch graphical chroots from VT2.  Launch them from crosh shells (ctrl+alt+t).

**Comment by gdm85** [comment]
@dnschneid that means I need to login first, it's something I wanted to avoid.

**Comment by dnschneid** [comment]
You can go into guest mode as well.
