### ISSUE TITLE
RT5370 driver on Samsung Chromebook 2 (intel)

### ISSUE THREAD

**Issue by shaddyang** [dnschneid/crouton#1778]
I have been trying to get the USB WiFi adapter(RT5370 chipset Panda adapter) to work on my Chromebook with crouton for some time. 
I tried both the kernel module(which I built according to the guide [here](https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules). I selected m for the RT2800USB and I enabled the support for RT53xx) and the driver provided on the Panda's website, but they seemed to be having the same problem which caused the system to reboot after I inserted the module and plugged in the USB adapter(I tried both modprobe and insmod). I also tried different release (Ubuntu trusty and Kali), but they gave the same result. 

I was going to post some logs here but I see there is nothing in `dmesg` or any other log, so it'd also be helpful if someone could tell me where to look for the log.

Also, [here](https://gist.github.com/shaddyang/10c0b902acb64a5dd6a4#file-versionoutput) is the output of `sudo enter-chroot -n trusty croutonversion` on my machine.

Please help me with this issue! Thanks!

**Comment by divx118** [comment]
Probably a kernel panic. You can take a look at `/dev/pstore/console-ramoops` or post it on gist or pastebin and the link here, maybe someone might know more...

**Comment by shaddyang** [comment]
Thanks! I looked in '/dev/pstore/' but there is nothing there. What other logs can I try?

**Comment by shaddyang** [comment]
OK. so I ran a `depmod -a` and this is the result
`ERROR: failed to load symbols from /lib/modules/3.10.18/kernel/drivers/net/wireless/rt2x00/rt2x00lib.ko: Invalid argument
ERROR: failed to load symbols from /lib/modules/3.10.18/kernel/drivers/net/wireless/rt2x00/rt2x00usb.ko: Invalid argument
ERROR: failed to load symbols from /lib/modules/3.10.18/kernel/drivers/net/wireless/rt2x00/rt2800lib.ko: Invalid argument
ERROR: failed to load symbols from /lib/modules/3.10.18/kernel/drivers/net/wireless/rt2x00/rt2800usb.ko: Invalid argument
ERROR: failed to load symbols from /lib/modules/3.10.18/kernel/net/wireless/rt5370sta.ko: Invalid argument`
Also, I did a `readelf` on the RT5370.ko file and [here](https://gist.github.com/anonymous/80f8bbf0384583aecfda#file-rt5370-readelf-symbols) is the symbols read from the file.

**Comment by shaddyang** [comment]
Since there is really no logs that I can find to post here, I did a `readelf -Ws` on the RT5370sta.ko and the result is [here](https://gist.github.com/shaddyang/aefed31f83d13f638bab#file-symbols).
If there is someone familiar with this, please help me! Thanks!

**Comment by divx118** [comment]
Did you try to insmod it in a crosh shell or in a chroot. Just a long shot. If you tried it in a chroot then try doing it in a crosh shell first, maybe it depends on something in chromeos. The module doesn't need to be in /lib/modules. Just specify the full path to it with insmod.
Just strange that your chromebook reboots when loading the module and nothing shows up in `/dev/pstore/console-ramoops`

**Comment by shaddyang** [comment]
I tried it with the RT5370sta but it still caused a crash. Also, as I can see from the `modinfo`, there is no dependencies required.
However, I actually got the `console-ramoops`, and [here](https://gist.github.com/shaddyang/7dc65c198da074c578db#file-console-ramoops) it is. If anyone can take a look, I would really appreciate it. I think the first time I forgot that I actually rebooted once after the crash.

**Comment by shaddyang** [comment]
I have been trying to read the `ramoops` myself, but as my kernel debug experience is close to nothing, all I got was that the initialization of the drive crashed at calling `RtmpOSNetDevAttach` which is in *rt_linux.c*. I would really appreciate it if someone could help! Thanks!

**Comment by shaddyang** [comment]
[Here](https://gist.github.com/shaddyang/f71b427e271d250299ba#file-driver-log) is the compilation log that I got when I was compiling the driver, which I got from the Panda Wireless website. If anyone has time, please take a look and tell me anything you think might've gone wrong. Thanks!

**Comment by tonyxue** [comment]
I thinkbit's really an upstream issue as chroots don't really handle network interfaces directly. They just simply use the connection from CrOS

**Comment by shaddyang** [comment]
I suppose it is. Does it mean that there is nothing I can do here? Not even if someone finds out what is missing?

**Comment by tonyxue** [comment]
Does the WiFi adapter work in the CrOS though? If it does, it worth taking a look from the crouton side.

But talking about hardware driver issues, mostly kernel issues I would say.

**Comment by shaddyang** [comment]
Nope. I am not experienced with this, but from what I understand, installing the driver should be the first step in cracking this, right? The original kernel module in CrOS is not supporting RT5370, for which I had to compile the custom kernel module according to the guide [here](https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules) while enabling the support for RT53xx, which I had to do inside one of the chroots. Now I am just stuck here since that although I have followed all guides strictly for multiple times, the result is the same -- system crash and reboot, due to a Null pointer as shown in the ramoops.

**Comment by divx118** [comment]
@shaddyang One thing, that won't be your issue, but why are you building as root? IMO it is always best to build as a normal user.

Did you build the kernel headers yourself? If so, you could try the kernel headers on my [github repo](https://github.com/divx118/crouton-packages) and build the module source with that. Be sure to uninstall your old kernel headers.

It is a good chance that it is an upstream bug. You could try https://groups.google.com/a/chromium.org/forum/#!forum/chromium-os-dev .

**Comment by shaddyang** [comment]
@divx118 I should've mentioned that the SD card that I mount is using ext4 filesystem that I find it is easier to just mount as root, have not got time to deal with that yet. Sure, I will try your kernel headers and take a look at Chromium OS dev. Thanks!

**Comment by shaddyang** [comment]
@divx118 I tried the kernel headers on your repo but unfortunately the result is still the same. I also posted the question onto Chromium OS dev. Hopefully someone would figure it out.
For anyone interested, [here](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/ijNUazl0Fzo) is the link to that page.
