### ISSUE TITLE
error generating xkmfile?

### ISSUE THREAD

**Issue by astrodud** [dnschneid/crouton#1779]
I have been very happily using crouton with my trusty Ubuntu chroot for a while. 
Suddenly after the latest chrome-os update,  when I try to start my window manager within the chroot (via "startx"), the screen blanks and then returns back to the chrome-os, reporting the following error in the terminal (copied from /tmp/Xorg.crouton.log.1):

(I should note that I did do a "crouton -u" after the chrome-os update.)

It seems to be a permissions problem, but I cannot figure it out. Any help would be appreciated.

[  2147.840] (II) XKB: generating xkmfile /var/lib/xkb/server-B20D7FC79C7F597315E3E501AEF10E0D866E8E92.xkm
[  2147.873] [xkb] Can't rename /tmp/fileJJodNq to /var/lib/xkb/server-B20D7FC79C7F597315E3E501AEF10E0D866E8E92.xkm, error: Invalid cross-device link
[  2147.873] (EE) XKB: Couldn't compile keymap
[  2147.873] (EE) XKB: Failed to load keymap. Loading default keymap instead.
[  2147.877] (II) XKB: generating xkmfile /var/lib/xkb/server-B20D7FC79C7F597315E3E501AEF10E0D866E8E92.xkm
[  2147.897] [xkb] Can't rename /tmp/fileNF1px9 to /var/lib/xkb/server-B20D7FC79C7F597315E3E501AEF10E0D866E8E92.xkm, error: Invalid cross-device link
[  2147.897] (EE) XKB: Couldn't compile keymap
[  2147.897] XKB: Failed to compile keymap
[  2147.897] Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
[  2147.897] (EE) 
Fatal server error:
[  2147.897] (EE) Failed to activate core devices.(EE) 
[  2147.897] (EE)

**Comment by astrodud** [comment]
Update: seems related to [this](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/972324) . 

If I set TMPDIR to $HOME/tmp and then startx, the screen goes blank and stays that way (rather than returning to chrome-os). The only way to return to chrome-os now is to reboot.

**Comment by dnschneid** [comment]
Try updating your chroot, and then try using `xinit`, because `startx` has never worked reliably in crouton (due to various coexistence hacks).
