### ISSUE TITLE
Arduino IDE problem

### ISSUE THREAD

**Issue by Alfriadox** [dnschneid/crouton#1780]
Hi,

I tried to install the ardunio IDE, and was able to get it, but I was not able to change serial ports through the IDE, I can through a config file, but is there a way to just do it through the app?

**Comment by Alfriadox** [comment]
I am asking because the serial ports are grayed out in the IDE itself.

**Comment by dnschneid** [comment]
Is this in crouton?

**Comment by Alfriadox** [comment]
yes.

**Comment by Alfriadox** [comment]
also I can't tell whic serial port is which through the ~/.arduino/prefrences.txt file
