### ISSUE TITLE
Remove target.

### ISSUE THREAD

**Issue by Alfriadox** [dnschneid/crouton#1781]
How would I remove xiwi from a chroot? 
(I installed it accidentily, but I like running the chroot in a sparate enviorment more.)

**Comment by Alfriadox** [comment]
Or perhaps I could somehow change the Xmethod.

**Comment by Alfriadox** [comment]
The other thing I could do would be to completely delete the chroot, but I don't realy want to.

**Comment by divx118** [comment]
Easy way is to update your chroot with `sudo sh ~/Downloads/crouton -t xorg -u -n <chrootname>` then it will automatically set your XMETHOD to xorg again. You can still use xiwi with your start script and then extend it with `-X xiwi` So for example `sudo startunity -X xiwi` FYI `-X` will override the default XMETHOD.

**Comment by Alfriadox** [comment]
Thank you!
