### ISSUE TITLE
Broken pre-freon chroot - won't boot into xiwi

### ISSUE THREAD

**Issue by westphae** [dnschneid/crouton#1784]
For many months, pretty much daily until yesterday morning, I have been happily running a Ubuntu chroot alongside a Pixel on ChromeOS beta channel using xiwi.  (Aside: awesome work on this project--I absolutely love working on my Pixel thanks to crouton!)  I have been able to handle the inoccasional glitch on an update by updating the chroot with crouton.  Yesterday I did two things, one of which seems to have broken my setup.

1. I added the keyboard target to my chroot.
2. I tried starting with -X xorg instead of xiwi.

Both changes worked, but now when I try to `sudo startxfce4 -X xiwi`, I get an error message

`(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)`

Looking in /tmp/Xorg.crouton.1.log, I see the following two errors:

```
[  3017.443] (II) LoadModule: "kbd"
[  3017.444] (WW) Warning, couldn't open module kbd
[  3017.444] (II) UnloadModule: "kbd"
[  3017.444] (II) Unloading kbd
[  3017.444] (EE) Failed to load module "kbd" (module does not exist, 0)
```
and
```
[  3017.445] (EE) 
Fatal server error:
[  3017.445] (EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
```

I can still `sudo startxfce4 -X xorg` with no problem, and I can also `sudo enter-chroot`.  When I enter-chroot or start with xorg and `ls /dev/tty*`, I see only /dev/tty, /dev/tty1, and /dev/tty8 (as well as ttyUSB?).  There is indeed no tty0.  Also, `/sbin/modprobe kbd` returns `modprobe: FATAL: Module kbd not found.`

I have tried downloading the latest crouton and updating.  I also found some possibly related issues here, and tried `sudo apt-get install --reinstall xserver-xorg-core` within the chroot.  This causes a segfault when xinit starts, but then updating the chroot with `sudo sh ~/Downloads/crouton -n threepio -u` fixes this and gives me again the above two problems.  I am on freon.  Here is the output of `sudo edit-chroot -al`:

```
name: threepio
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/threepio...
crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,xorg,keyboard,extension,cli-extra,touch
host: version 6946.52.0 (Official Build) beta-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 20 12:05:51 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/threepio...
```

For grins, I tried making a new chroot to test: `sudo sh ~/Downloads/crouton -t xfce,xiwi -n test`.  The new chroot works fine with xiwi.  The /tmp/Xorg.crouton.1.log still shows the error for the non-existing kbd kernel module, but does not complain about /dev/tty0 missing, and indeed /dev/tty0 is there.

I can use my old chroot with xorg for now, or could spend a few hours setting up the new chroot, but would prefer to repair my old one so it can work with xiwi again.  Any advice for figuring out what happened to my /dev/tty0?

Thanks!

**Comment by westphae** [comment]
I figured this one out after a few hours tracing through the X startup sequence.  One of the updates had mysteriously introduced a 10-monitor.conf file into /usr/share/X11/xorg.conf.d, and this file didn't have a Device section, so the Card0 "dummy" device as specified in /etc/X11/xorg-dummy.conf was being overridden by "Intel Graphics SNA+TearFree" which seemed to cause the problems.

I don't know where this 10-monitor.conf file came from.  It had a timestamp of Dec 10.  Somehow, booting with the xorg XMETHOD introduced it.

**Comment by DennisLfromGA** [comment]
@westphae - 
That's *very* interesting; great troubleshooting! 
I'm not a lot of help though since I don't know, nor looked to see where, `10-monitor.conf` comes from - sorry. If I get some time I'll try to find out but this is good info. :)

**Comment by divx118** [comment]
@westphae @DennisLfromGA 10-monitor.conf is not created by crouton, that file should be named [20-crouton-intel-sna.conf](https://github.com/dnschneid/crouton/blob/master/targets/xorg#L199) however that file can't interfere with xiwi, because the config file is passed by [a parameter](https://github.com/dnschneid/crouton/blob/master/chroot-etc/xserverrc-xiwi#L17) when using XMETHOD xiwi.

**Comment by westphae** [comment]
Thanks for having a look at this, @DennisLfromGA & @divx118.  My chroot has been working perfectly since this fix.  I'm happy to do any further troubleshooting that you think might help if the issue was due to something in the crouton install, or if it helps others who run across a similar issue.

My recollection is that I converted this chroot from xorg to xiwi shortly after xiwi became available and never used another XMETHOD until 2 weeks ago when the problem occurred.  The only other thing I can think of that could possibly have introduced this 10-monitor.conf file is that in February (still on xiwi) I used an external monitor through the DisplayPort for some presentations.  I never chrooted into xorg between then and when the problem occurred a few weeks ago.  I can't think of anything else unusual that I did that might have introduced this file.

@divx118 , there is indeed a 20-crouton-intel-sna.conf file in the xorg.conf.d directory, which is actually a link to /etc/crouton/20-xorg-intel-sna.conf.  But there was the additional 10-monitor.conf file causing the problems.  I also never passed a separate config file when starting the chroot.

**Comment by divx118** [comment]
@westphae Not sure what went wrong in your case. 10-monitor.conf shouldn't be in there with a normal install. Maybe some installed package put it there. Do you still have the content from 10-monitor.conf?

**Comment by westphae** [comment]
Yes, I saved it.  Here you go:
```
Section "Monitor"
  Identifier "Monitor0"
  Modeline "1440x960_60.00"  113.75  1440 1528 1672 1904  960 963 973 996 -hsync +vsync
EndSection
Section "Screen"
  Identifier "Screen0"
  Device "eDP1"
  Monitor "Monitor0"
  DefaultDepth 24
  SubSection "Display"
    Depth 24
    Modes "1440x960_60" "1280x960"
  EndSubSection
EndSection
```
