### ISSUE TITLE
Unable to Stream to Youtube Live via ScreenStudio

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1786]
I am using ScreenStudio to stream to Youtube Live and this happened:
```
Last log output...
-----------------------
avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[video4linux2 @ 0x1e53ee0] Estimating duration from bitrate, this may be inaccurate
Input #0, video4linux2, from '/dev/video0':
  Duration: N/A, start: 4709.401100, bitrate: 36864 kb/s
    Stream #0.0: Video: rawvideo, yuyv422, 320x240, 36864 kb/s, 1000k tbn, 30 tbc
Input #1, image2, from '/tmp/screenstudio9081289138134273368.png':
  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A
    Stream #1.0: Video: png, bgra, 1366x768, 25 tbn
[x11grab @ 0x1e565a0] device: :0.0+0,0 -> display: :0.0 x: 0 y: 0 width: 1366 height: 768
[x11grab @ 0x1e565a0] Could not open X display.
:0.0+0,0: Input/output error
```

**Comment by firestar115** [comment]
This is CodeDay 2015 and I really want my viewers to see...

**Comment by dnschneid** [comment]
What command are you using?  Where are you running it from?

**Comment by firestar115** [comment]
```shell
#!/bin/bash
INRES="1366x768" # input resolution
OUTRES="1366x768"
OFFSET="0,0"
FPS="30" # target FPS
QUAL="ultrafast"  # one of the many FFMPEG preset
STREAM_KEY="Insert stream key here"
URL="rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY"
avconv -f x11grab -s "$INRES" -r "$FPS" -i :0.0+$OFFSET -ab 192k \
-f alsa -ac 2 -i pulse -vcodec libx264 -crf 30 -preset "$QUAL" -s
"1366x768" \
-vol 11200 -acodec libmp3lame -ar 44100 -threads 0 \
-f flv "$URL"
```

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by dnschneid** [comment]
Where are you running it from?

**Comment by firestar115** [comment]
My trusty chroot on an Acer C7 switched to dev channel.

**Comment by dnschneid** [comment]
Are you running inside crosh attempting to screenshare Chromium OS, or is this inside the chroot's X server?

**Comment by firestar115** [comment]
Inside the xfce desktop (X Server). I am actually using ScreenStudio
so I don't know if that's the exact command it runs.

On 5/30/15, David Schneider <notifications@github.com> wrote:
> Are you running inside crosh attempting to screenshare Chromium OS, or is
> this inside the chroot's X server?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1786#issuecomment-107129444


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by dnschneid** [comment]
Oh, that's just because the display in crouton isn't necessarily `:0.0`.  Replace the `:0.0+$OFFSET` part with  `"${DISPLAY%%.*}.0+$OFFSET"`.

**Comment by firestar115** [comment]
But... what about ScreenStudio?

**Comment by dnschneid** [comment]
If that log is from ScreenStudio, they're making the same mistake.  If they don't have a way to edit what display they record (and don't do the sane thing and use `$DISPLAY`), you should file a bug on their site.
