### ISSUE TITLE
Elementary OS Implementation.

### ISSUE THREAD

**Issue by Alfriadox** [dnschneid/crouton#1788]
I am working on implementing Elementary OS in a fork I have of crouton.
It is based somewhat off of  https://github.com/AldousP/MyDearWatson , and should be ready soon.

This answers the following issues:

#1725
#994 
#1571
#314
#123

And several others I think.

-- Hope this works :smile: --Alfriadox

P.S. -- I am not currently listed under official contributors but I am pretty sure I signed https://cla.developers.google.com/clas/new?kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE
for another project a while ago. Do I need to be an official contributor some how before my pull request can be accepted?

**Comment by Alfriadox** [comment]
If anyone would like to help, though, it would be much appreciated.

**Comment by Alfriadox** [comment]
This is actually really difficult. If some one who has creared targets before could help, that would be really helpful.

**Comment by divx118** [comment]
@Alfriadox If you signed the cla you should be good to create the pull request.
Second, best way is to fork crouton and then create your own branch in it where you make the changes. It will be easier to keep things clean and stay synced with your crouton fork.
Specific questions about where you are stuck or how to do certain things would give you more change in getting help on this. Also you can join the crouton(-devel) irc channel on freenode, but again being specific will help you also there.

**Comment by Alfriadox** [comment]
Alright, thanks.

**Comment by dnschneid** [comment]
Yep, create a pull-request when you'd like feedback, and feel free to swing by \#crouton-devel for pointers.
