### ISSUE TITLE
stuck at shell, ctrl alt refresh not working

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#179]
forgot I still had crouton running when I rebooted to shell from the help screen (switching channels), not sure if that had to do with anything

pressing ctrl alt bkwd either drops me in the same/new tty, ctrl alt refresh appears to do nothing...

loging into chronos and running startxfce works though

**Comment by jmccoy** [comment]
I'm having the same problem as forresthopkinsa.  I boot ChromeOS, enter crouton (ctrl/alt/t, shell, sudo startxfce4), and all is good.  When I return to ChromeOS (ctrl/alt/F1), still good.  But then when I try to return to crouton (ctrl/alt/F2, ctrl/alt/F3), I get black screen.  (Actually, there seems to be a flash of something, but it's gone before I can see what's showing.)

This started last week after I updated Chrome.  Since then I've updated to the latest crouton, but the problem persists.

As a workaround, I had been going back to the crosh shell, hitting ctrl/C, and restarting crouton, but now I'm using the forresthopkinsa solution (close and open the lid).  It works, but something must be amiss?

**Comment by divx118** [comment]
@jmccoy See https://github.com/dnschneid/crouton/issues/1646 use ctr-alt-shift forward/backward

**Comment by jmccoy** [comment]
Thank you, divx118.  Before I comment, perhaps I should note that I'm on an Acer C710, and that almost all my computer work is done in crouton.  (Hooray for crouton!)

Unfortunately, ctrl/alt/SHIFT/forward or backward doesn't do it for me.

First, ctrl/alt/forward still brings me to the Developer Console, but then ctrl/alt/refresh now brings up a black screen.  Ctrl/alt/SHIFT/forward just replicates those steps, only faster (as does ctrl/alt/SHIFT/backward).

At the black screen, closing the lid, waiting for suspend, and opening the lid then brings up crouton as if nothing bad had happened.

Ctrl/alt/backward still returns me to Chrome, even from the black screen.

Should I move these comments to #1646?

**Comment by divx118** [comment]
@jmccoy I thinks you have the same issue as kikohernandez92 on issue https://github.com/dnschneid/crouton/issues/1632 Can you post the output of `sudo enter-chroot -n <chrootname> croutonversion` as a comment on that issue. BTW if you didn't specify a chrootname, then the chrootname will be the release you are using "precise" or "trusty" etc. So if you created a chroot with release trusty the command will be `sudo enter-chroot -n trusty croutonversion`

**Comment by jmccoy** [comment]
Thank you again.

Here is my screen copy:

chronos@localhost / $ sudo enter-chroot -n trusty croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150414182244~master:da478a77
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6812.75.2 (Official Build) stable-channel parrot
kernel: Linux localhost 3.4.0 #1 SMP Tue Apr 14 19:01:35 PDT 2015 x86_64
x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under
/mnt/stateful_partition/crouton/chroots/trusty…

After this I performed (as per #1632):

$ sudo enter-chroot -n trusty
$ sudo apt-get update && sudo apt-get upgrade
$ exit
$ sudo sh ~/Downloads/crouton -n trusty -u

And then found:

chronos@localhost / $ sudo enter-chroot -n trusty croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150423153254~master:2f55723c
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6812.75.2 (Official Build) stable-channel parrot
kernel: Linux localhost 3.4.0 #1 SMP Tue Apr 14 19:01:35 PDT 2015 x86_64
x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under
/mnt/stateful_partition/crouton/chroots/trusty…

But the the behavior of ctrl/alt/whatever is the same as I reported in #179.

(Sorry)

**Comment by divx118** [comment]
@jmccoy Those commands were not meant for you. Those were for realgt. What I meant is you have the same issue as kikohernandez92 which has the same device looking at your croutonversion output and also has the same issue "a black screen". Best is to move the discussion further to #1632   

I will post your croutonversion output there and add some comment.

**Comment by jmccoy** [comment]
Sorry - I hope I didn't mess anything up.  Those commands just seemed to be
good things even if there were no problems.

**Comment by divx118** [comment]
@jmccoy No the commands can't mess up your chroot, they just don't fix your issue.
