### ISSUE TITLE
GNOME opens to black, then closes out autmatically

### ISSUE THREAD

**Issue by kevvurs** [dnschneid/crouton#1791]
:(

I have a Samsung series chromebook with an xfce4 chroot. Trying to pivot into GNOME and scrap XFCE. XFCE is currently working. But after installing GNOME (-r trusty), I can't get a successful run when I try to start it.

Crashes and burns after Lines +30.

Like I said, display starts to open, pauses on blank screen, then runs away.

Log:
1  Enter encryption passphrase for trusty: 
2  Entering /mnt/stateful_partition/crouton/chroots/trusty...
3  Initializing built-in extension Generic Event Extension
4  Initializing built-in extension SHAPE
5  Initializing built-in extension MIT-SHM
6  Initializing built-in extension XInputExtension
7  Initializing built-in extension XTEST
8  Initializing built-in extension BIG-REQUESTS
9  Initializing built-in extension SYNC
10 Initializing built-in extension XKEYBOARD
11 Initializing built-in extension XC-MISC
12 Initializing built-in extension SECURITY
13 Initializing built-in extension XINERAMA
14 Initializing built-in extension XFIXES
15 Initializing built-in extension RENDER
16 Initializing built-in extension RANDR
17 Initializing built-in extension COMPOSITE
18 Initializing built-in extension DAMAGE
19 Initializing built-in extension MIT-SCREEN-SAVER
20 Initializing built-in extension DOUBLE-BUFFER
21 Initializing built-in extension RECORD
22 Initializing built-in extension DPMS
23 Initializing built-in extension Present
24 Initializing built-in extension DRI3
25 Initializing built-in extension X-Resource
26 Initializing built-in extension XVideo
27 Initializing built-in extension XVideo-MotionCompensation
28 Initializing built-in extension SELinux
29 Initializing built-in extension GLX
30 [dix] Could not init font path element /usr/share/fonts/X11/misc, removing from list!
31 [dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
32 [dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
33 [dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
34 [dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!
35 [dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
36 [dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
37 /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
38 crouton: version 1-20150519153807~master:30cf02c9
39 release: trusty
40 architecture: armhf
41 xmethod: xephyr
42 targets: gnome
43 host: version 6812.88.0 (Official Build) stable-channel daisy 
44 kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 12:23:49 PDT 2015 armv7l armv7l armv7l 
45 GNU/Linux
46 freon: no
47 Running exit commands...
48 /usr/bin/xinit: connection to X server lost Hangup
49 waiting for X server to shut down 
50 Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by dnschneid** [comment]
I would suggest waiting to try gnome until freon rolls down to your Chromebook (or switch to dev channel, but expect other random issues).
