### ISSUE TITLE
Policykit Issue

### ISSUE THREAD

**Issue by aahenn** [dnschneid/crouton#1792]
I’m on a fresh install of Trusty, and when I go to install anything through the Software Centre I get this: "Software can't be installed or removed because the authentication service is not available. (org.freedesktop.PolicyKit.Error.Failed: ('system-bus-name', {'name':  ':1.49'}): org.debian.apt.install-or-remove-packages".

From googling around it looks like there was an update on May 10th (https://github.com/dnschneid/crouton/pull/699) that was meant to address this. So I guess I’m just trying to let you guys knows it’s still an issue.

Here’s my output from croutonversion:
crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: amd64
xmethod: xorg
targets: unity-desktop,keyboard,extension
host: version 6812.88.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Fri May 8 12:28:58 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

Let me know if you need anything else.

**Comment by dnschneid** [comment]
@smibarber any thoughts?

**Comment by fignuts** [comment]
I am having this issue on xenial with xfce

**Comment by WanuelM** [comment]
Still an issue on xenial (unity and gnome). Is there any known workaround yet?
