### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Alexiplier777** [dnschneid/crouton#1795]
Hi, I am setting up Linux and Ubuntu onto my Chromebook Acer. Whenever I try to type the final command (sudo startxfce4) I receive the following:
chronos@localhost / $ sudo startxfce4
Entering /usr/local/chroots/precise...
UID 1000 not found in precise
Not unmounting /usr/local/chroots/precise as another instance is using it.

Does this mean that I have to do something to make it to where it is not being used in another instance? How would I have to fix that?

**Comment by divx118** [comment]
Just reboot your chromebook is the easiest way. However it seems you didn't complete your chroot setup   correctly according to `UID 1000 not found in precise` Try updating your chroot after the reboot with `sudo sh ~/Downloads/crouton -u -n precise` and be sure to enter a username and password when you are asked for it on the command line.

**Comment by Alexiplier777** [comment]
That worked! I had to restart it like you said, used the command given,then preceded to retype the original command to open XFCE

**Comment by divx118** [comment]
Nice, if it is solved for you then please close issue. Thanks

**Comment by Alfriadox** [comment]
Perhaps try restarting the computer.
