### ISSUE TITLE
nested arrays in swagger 2.0

### ISSUE THREAD

**Issue by Say123** [dnschneid/crouton#1799]
Hi ,
I would like to know whether  swagger 2.0  supports  nested array. For example,
{
	"details":"abc",
         "xyz":[[
            {"name":"F",
             "stream":"VBNBMNB"
             },
              {"name":"b",
             "stream":"VBNBMNB"
             }
             ]]
} 

Could you please provide a similar model schema.

Thanks in advance

**Comment by dnschneid** [comment]
#262 details it pretty well.
