### ISSUE TITLE
Xephyr cannot open host display

### ISSUE THREAD

**Issue by cdmurph32** [dnschneid/crouton#18]
I'm having the same issue as described in issue #17.  I've reinstalled the chroot 3 times over the past few weeks with fresh crouton scripts, with no success.

sudo startxfce4 2>&1 | tee startxfce4.log

startxfce4.log:
_/usr/bin/startxfce4: Starting X server_

_XIO: fatal IO error 2 (No such file or directory) on Xserver ":0" after 39 requests (39 known processed) with 0 events remaining._

Starting Xephyr manually results in the following:
export DISPLAY=:0 
Xephyr :0 -fullscreen -ac
_Fatal server error:_
_Server is already active for display 0_
_If this server is no longer running, remove /tmp/.XO-lock and start again._

export DISPLAY=:1
Xephyr :1 -fullscreen -ac
Xephyr cannot open host display. Is DISPLAY set?

Googling this error makes it seem to be a .Xauthority issue.  
I tried the solution on the Debian wiki http://wiki.debian.org/XStrikeForce/FAQ#howtoxnest
with no preliminary success.

**Comment by Firestarthirty** [comment]
Im having the same problem but on crosh (i have some problem almost every other time my chromebook updates usually I can fix it though)

**Comment by ant6n** [comment]
I have the same problem ("Xephyr cannot open host display. Is DISPLAY set?") on a Samsung Chromebook arm, using a trusty crouton with lxde. I can log into the chroot but not start up lxde. From inside the chroot, I can still not start lxde, but there it gives a different error

```chronos@localhost / $ sudo enter-chroot -n trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)adubra@localhost:~$ startlxde
Agent pid 22782
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE

(lxsession:22774): Gtk-WARNING **: cannot open display: ```

I created another crouton (precise-lxde). This one works, I can log in and the GUI will start. I tried to update the trusty chroot, which seems to fail (I dunno whether that's what causes this issue):

```...
E: Some index files failed to download. They have been ignored, or old ones used instead.
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-tools-3.13.0-37 linux-tools-3.13.0-37-generic
Use 'apt-get autoremove' to remove them.
The following packages will be upgraded:
  linux-image-3.8.11
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5513 kB of archives.
After this operation, 332 kB disk space will be freed.
Preconfiguring packages ...
(Reading database ... 78832 files and directories currently installed.)
Preparing to unpack .../linux-image-3.8.11_20150314_armhf.deb ...
Ok, aborting, since modules for this image already exist.
dpkg: error processing archive /var/cache/apt/archives/linux-image-3.8.11_20150314_armhf.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.8.11 /boot/vmlinuz-3.8.11
Errors were encountered while processing:
 /var/cache/apt/archives/linux-image-3.8.11_20150314_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...```

**Comment by ant6n** [comment]
(just coming back to note that the problem was that the updating kept crashing, because of issues with dependencies, and libraries pulled from non-standard sources. Once I resolved/removed those issues, the update went through and the GUI desktop works again.)
