### ISSUE TITLE
Removing a weird XFCE partition on Chromebook (installed with crouton)???

### ISSUE THREAD

**Issue by TheFlyingPig13** [dnschneid/crouton#1800]
my Chromebook had an XFCE partition installed in it using crouton, and whenever I open it up using the CTRL ALT Forward command, it goes to the developer console! I just want to remove the partition now, bur after power washing, switching developer mode on and off, multiple usb recoveries, and yet every time I turn developer mode back on and use the ctrl Alt Forward command its still there. What commands in crosh can I use to remove it? Or any other solution.

**Comment by tonyxue** [comment]
The console you saw is the console for Chromium OS. It will show up when dev mode is enabled. So if you don't want to see it, just turn off the dev mode.


You should use CTRL+SHIFT+ALT+Forward to switch to the desktop installed by crouton.





-Tony

**Comment by TheFlyingPig13** [comment]
Thanks, that helps a lot. But I'm just done with Linux partitions now so how can I remove it?

**Comment by tonyxue** [comment]
You can remove your chroot if you are sure that you don't want it anymore.
