### ISSUE TITLE
Can't enter chroot on Toshiba Chromebook 2

### ISSUE THREAD

**Issue by frontalot** [dnschneid/crouton#1803]
I have installed the Trusty Tahr release of xfce4, xiwi, keyboard, extension, core, and audio (no xorg because my Chromebook is running freon). When I try to enter a newly created chroot using "sudo startxfce4", I receive the following errors:

/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashtree=PARTUUID=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=eb247b54b3924eebc7fabcaa2526706546617882 salt=6c257451ffdb07295f3b1da1552915a8a174bdda04ee7f1063cb2b62a58da169" noinitrd vt.global_cursor_default=0 kern_guid=e4e36f0d-ca2b-5940-a7fe-a61287b5a2d8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat May 30 08:13:53 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x48) [0x7f5b59250848]
(EE) 1: /usr/bin/Xorg (0x7f5b590a7000+0x1ad539) [0x7f5b59254539]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f5b581a3000+0x10340) [0x7f5b581b3340]
(EE) 3: /usr/bin/Xorg (0x7f5b590a7000+0xb57a6) [0x7f5b5915c7a6]
(EE) 4: /usr/bin/Xorg (xf86BusProbe+0x9) [0x7f5b59130099]
(EE) 5: /usr/bin/Xorg (InitOutput+0x74d) [0x7f5b5913e6fd]
(EE) 6: /usr/bin/Xorg (0x7f5b590a7000+0x59bab) [0x7f5b59100bab]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7f5b56be3ec5]
(EE) 8: /usr/bin/Xorg (0x7f5b590a7000+0x451ee) [0x7f5b590ec1ee]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/xubuntu as another instance is using it.

Any idea on what's going on or how to fix it?

**Comment by efngn** [comment]
try using unity, rather than xfce. 

did you try using "enter-chroot"?

**Comment by divx118** [comment]
@frontalot Update your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting this should solve your problem. Using unity target or enter-chroot first will not make a difference.
