### ISSUE TITLE
cruoton asking for password

### ISSUE THREAD

**Issue by EvanDawesome** [dnschneid/crouton#1804]
So my friend has a chromebook and she is trying to run the following command in crosh.
sudo sh ~/Downloads/crouton -e -t xfce
after she types it it asks for a password but what password? Also whenever I see other people type it it does not ask for a password. Thanks

**Comment by divx118** [comment]
`-e` will set encryption on a chroot see https://github.com/dnschneid/crouton#with-encryption Also she should specify a release. Use the following for a trusty chroot with xfce desktop and no encryption. `sudo sh ~/Downloads/crouton -r trusty -t xfce,extension` The extension target will make clipboard sync possible between chromeos and the chroot. You get a link to the chrome extension in the Web store once your chroot is succesfully created. You need to install that too to make the clipboard sync work. See also https://github.com/dnschneid/crouton#prerequisites where there is the link to the extension also mentioned.

**Comment by EvanDawesome** [comment]
ok thanks ill have her try "sudo sh ~/Downloads/crouton -r trusty -t xfce,extension"

**Comment by EvanDawesome** [comment]
ok she has linux but when she trys to use the internet on her linux desktop it gives her a pop-up saying "failure to connect to default web browser (or input/output error)". What does this mean? Thanks

**Comment by EvanDawesome** [comment]
in the console it says needs crouton extension but she already has crouton right?

**Comment by tonyxue** [comment]
@EvanDawesome

Hi! Please see [this section](https://github.com/dnschneid/crouton#wasteful-rendundancies-are-wasteful-one-clipboard-one-browser-one-window) of the ```Readme.md```

**Comment by EvanDawesome** [comment]
@tonyxue 

she has the extension installed already. Is this "Add the extension or xiwi version to your chroot"  part of this command "sudo sh ~/Downloads/crouton -r trusty -t xfce,extension" or is it separate?

**Comment by divx118** [comment]
@EvanDawesome You have the extension target installed in the chroot, however you need [chromeos crouton extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) from the webstore to make it work. You need to install it in chromeos.

**Comment by EvanDawesome** [comment]
OK so we pushed add to chrome yesterday. Is that what we were supposed to do?

**Comment by divx118** [comment]
@EvanDawesome Yes

**Comment by EvanDawesome** [comment]
why would it be giving an error then? I had her enter developer mode by esc refresh and power then at recover screen pushed ctrl d.  she download the latest version of crouton from http://goo.gl/fd3zc then use ctrl alt t to open crouton and used the command shell followed by sudo sh ~/Downloads/crouton -r trusty -t xfce,extension. Then we added the crouton extension for her chrome. Then used sudo startfxce4 to start using linux.

**Comment by divx118** [comment]
@EvanDawesome You mean the "failure to connect to default web browser (or input/output error)" error. That is not related to the extension. I guess that the default web browser isn't set. You can try  "Application Menu --> Internet --> Netsurf webbrowser" instead of just clicking the web browser icon.

**Comment by EvanDawesome** [comment]
ok in linux or chrome os?

**Comment by divx118** [comment]
In linux. Just take it step by step. If this works for you then we see how to set the default browser.

**Comment by EvanDawesome** [comment]
@divx118 
ok thanks. she is busy right now so we can do it over skype later. I will tell you how it works out tomorrow and ask any other questions.

**Comment by EvanDawesome** [comment]
thanks for your support so far

**Comment by divx118** [comment]
I am sure "Application Menu --> Internet --> Netsurf Web Browser" will work for you.

I just setup a new chroot and the default web browser is not set correctly on xfce trusty. I will open a bug report for it. You can solve it by doing the following in linux: "Application Menu -> Settings -> Preferred Applications" You will get a screen where you can set the default webbrowser by default it is set to "Debian sensible browser" click on that and choose "other" then type in the input field "netsurf" without the quotes. Close the window by clicking the close button. Now the web browser icons should work and open the browser.

**Comment by EvanDawesome** [comment]
thanks it worked! I don't know how you knew all this but I am glad you did. See ya later.

**Comment by Alfriadox** [comment]
Can this issue be closed?

**Comment by EvanDawesome** [comment]
yes
