### ISSUE TITLE
Tabbing over into Chrome OS sets the mouse acceleration super high

### ISSUE THREAD

**Issue by efngn** [dnschneid/crouton#1805]
I have the default set to -1, and every time I tab over and back the mouse acceleration gets set really high. I have to manually set it back to -1 every time I come back.

**Comment by dnschneid** [comment]
What desktop environment are you using?  Please post the output of `croutonversion` as well.

**Comment by efngn** [comment]
unity.

crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 6946.55.0 (Official Build) stable-channel peppy
kernel: Linux localhost 3.8.11 #1 SMP Tue May 26 16:21:19 PDT 2015
x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by dnschneid** [comment]
Are you changing mouse acceleration in the unity UI, or via xset?

**Comment by efngn** [comment]
for some reason it doesn't give me the option to use the unity ui, so I use
xset.

interesting enough, using d-conf editor to set it back to default (-1)
results in it getting changed again when I tab out and back in

**Comment by dnschneid** [comment]
Yeah, that's just ubuntu's settings manager doing the right thing and restoring your settings whenever you switch VTs.

**Comment by efngn** [comment]
do you know how I can fix this? sorry.

**Comment by dnschneid** [comment]
Whoops, I thought you meant dconf-editor did it for you.

**Comment by dnschneid** [comment]
One of the solutions here might do it for you: http://askubuntu.com/questions/26176/how-do-i-turn-off-mouse-acceleration

**Comment by efngn** [comment]
I've tried all of them -- nothing works. do you know if I can execute a
script everytime I tab over?
