### ISSUE TITLE
Linux not starting up

### ISSUE THREAD

**Issue by ShadowIceStorm** [dnschneid/crouton#1806]
I need help, today I tried to start up Linux using crouton which I've had installed for about a month now.  It was working perfectly yesterday but today I tried to load it and the normal transition started but after the normal few seconds of black screen, instead of Unity Linux it brought me back to crosh.  This is the full feed
"
crosh> shell
chronos@localhost / $ sudo startunity
Entering /usr/local/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri May 8 12:21:21 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=043bcab0-1025-3e40-b108-a02541d36d19/PARTNROFF=1 hashtree=PARTUUID=043bcab0-1025-3e40-b108-a02541d36d19/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=9c34243a267c1af24486c5915d23642a322eebf7 salt=354cef49d2003d8b6815c8a5bb4c371c5f9f79569645357355f37b8be8d67824" noinitrd vt.global_cursor_default=0 kern_guid=043bcab0-1025-3e40-b108-a02541d36d19 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat May 30 13:17:47 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
setversion 1.4 failed: Permission denied
xf86: found device 0
crouton: version 1-20150511154233~master:392b84e4
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 6812.88.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 12:21:21 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.
.
Unmounting /usr/local/chroots/precise...
chronos@localhost / $ 
"
Please tell me if I can fix this and if so how.

**Comment by divx118** [comment]
@ShadowIceStorm Try updating your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by ShadowIceStorm** [comment]
Following the directions from that link you gave me I still am unable to run Linux. There was also an error somewhere but I don't know how to read crosh
"
crosh> shell
chronos@localhost / $ sudo edit-chroot -a
precise
chronos@localhost / $ sudo sh ~/Downloads/crouton -n precise -u
Downloading latest crouton installer...
######################################################################## 100.0%
Migrating data from legacy chroots directory /usr/local/chroots to /mnt/stateful_partition/crouton/chroots...
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startunity into the host...
Installing crouton-noroot into the chroot...
Installing startunity into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing crouton-unity-autostart into the chroot...
Installing unity-autostart.desktop into the chroot...
Installing unity-profiled into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
dpkg: dependency problems prevent configuration of libatspi2.0-0:amd64:
 libatspi2.0-0:amd64 depends on libc6 (>= 2.7); however:
  Package libc6:amd64 is not installed.
 libatspi2.0-0:amd64 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package libatspi2.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up libgtk-3-common (3.10.8-0ubuntu1.4) ...
dpkg: dependency problems prevent configuration of libcairo2:amd64:
 libcairo2:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libcairo2:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpython3.4-minimal:amd64:
 libpython3.4-minimal:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libpython3.4-minimal:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgraphite2-3:amd64:
 libgraphite2-3:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libgraphite2-3:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgdk-pixbuf2.0-0:amd64:
 libgdk-pixbuf2.0-0:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 libgdk-pixbuf2.0-0:amd64 depends on libglib2.0-0 (>= 2.37.6); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package libgdk-pixbuf2.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libjson-c2:amd64:
 libjson-c2:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libjson-c2:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of glib-networking:amd64:
 glib-networking:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 glib-networking:amd64 depends on libglib2.0-0 (>= 2.39.4); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package glib-networking:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libudev1:amd64:
 libudev1:amd64 depends on libc6 (>= 2.17); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libudev1:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libapt-inst1.5:amd64:
 libapt-inst1.5:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libapt-inst1.5:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gtk3-engines-unico:amd64:
 gtk3-engines-unico:amd64 depends on libc6 (>= 2.2.5); however:
  Package libc6:amd64 is not installed.
 gtk3-engines-unico:amd64 depends on libcairo2 (>= 1.10); however:
  Package libcairo2:amd64 is not configured yet.
 gtk3-engines-unico:amd64 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package gtk3-engines-unico:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgirepository-1.0-1:
 libgirepository-1.0-1 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 libgirepository-1.0-1 depends on libglib2.0-0 (>= 2.39.0); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package libgirepository-1.0-1 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libcgmanager0:amd64:
 libcgmanager0:amd64 depends on libc6 (>= 2.2.5); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libcgmanager0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpangocairo-1.0-0:amd64:
 libpangocairo-1.0-0:amd64 depends on libc6 (>= 2.4); however:
  Package libc6:amd64 is not installed.
 libpangocairo-1.0-0:amd64 depends on libcairo2 (>= 1.12.10); however:
  Package libcairo2:amd64 is not configured yet.
 libpangocairo-1.0-0:amd64 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.
 libpangocairo-1.0-0:amd64 depends on libpango-1.0-0 (>= 1.32.4); however:
  Package libpango-1.0-0 is not installed.

dpkg: error processing package libpangocairo-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgtk-3-0:amd64:
 libgtk-3-0:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 libgtk-3-0:amd64 depends on libcairo2 (>= 1.13.0~20140204); however:
  Package libcairo2:amd64 is not configured yet.
 libgtk-3-0:amd64 depends on libgdk-pixbuf2.0-0 (>= 2.27.1); however:
  Package libgdk-pixbuf2.0-0:amd64 is not configured yet.
 libgtk-3-0:amd64 depends on libglib2.0-0 (>= 2.39.4); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.
 libgtk-3-0:amd64 depends on libpango-1.0-0 (>= 1.32.4); however:
  Package libpango-1.0-0 is not installed.
 libgtk-3-0:amd64 depends on libpangocairo-1.0-0 (>= 1.32.4); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.

dpkg: error processing package libgtk-3-0:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up gsettings-desktop-schemas (3.10.1-0ubuntu1) ...
dpkg: dependency problems prevent configuration of libpango1.0-0:amd64:
 libpango1.0-0:amd64 depends on libpango-1.0-0 (= 1.36.3-1ubuntu1.1); however:
  Package libpango-1.0-0 is not installed.
 libpango1.0-0:amd64 depends on libpangocairo-1.0-0 (= 1.36.3-1ubuntu1.1); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.
 libpango1.0-0:amd64 depends on libpangoxft-1.0-0 (= 1.36.3-1ubuntu1.1); however:
  Package libpangoxft-1.0-0 is not installed.
 libpango1.0-0:amd64 depends on libpangox-1.0-0 (>= 0.0.2-2~); however:
  Package libpangox-1.0-0 is not installed.

dpkg: error processing package libpango1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libjbig0:amd64:
 libjbig0:amd64 depends on libc6 (>= 2.4); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libjbig0:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up ttf-freefont (20120503-4) ...
dpkg: dependency problems prevent configuration of libtiff5:amd64:
 libtiff5:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 libtiff5:amd64 depends on libjbig0 (>= 2.0); however:
  Package libjbig0:amd64 is not configured yet.

dpkg: error processing package libtiff5:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libharfbuzz0b:amd64:
 libharfbuzz0b:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 libharfbuzz0b:amd64 depends on libgraphite2-3 (>= 1.2.2); however:
  Package libgraphite2-3:amd64 is not configured yet.

dpkg: error processing package libharfbuzz0b:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of librsvg2-2:amd64:
 librsvg2-2:amd64 depends on libc6 (>= 2.4); however:
  Package libc6:amd64 is not installed.
 librsvg2-2:amd64 depends on libcairo2 (>= 1.2.4); however:
  Package libcairo2:amd64 is not configured yet.
 librsvg2-2:amd64 depends on libgdk-pixbuf2.0-0 (>= 2.22.0); however:
  Package libgdk-pixbuf2.0-0:amd64 is not configured yet.
 librsvg2-2:amd64 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.
 librsvg2-2:amd64 depends on libpango-1.0-0 (>= 1.36.0); however:
  Package libpango-1.0-0 is not installed.
 librsvg2-2:amd64 depends on libpangocairo-1.0-0 (>= 1.36.0); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.

dpkg: error processing package librsvg2-2:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of glib-networking-services:
 glib-networking-services depends on libc6 (>= 2.2.5); however:
  Package libc6:amd64 is not installed.
 glib-networking-services depends on libglib2.0-0 (>= 2.39.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package glib-networking-services (--configure):
 dependency problems - leaving unconfigured
Setting up libgdk-pixbuf2.0-common (2.30.7-0ubuntu1) ...
dpkg: dependency problems prevent configuration of librsvg2-common:amd64:
 librsvg2-common:amd64 depends on libc6 (>= 2.2.5); however:
  Package libc6:amd64 is not installed.
 librsvg2-common:amd64 depends on libgdk-pixbuf2.0-0 (>= 2.22.0); however:
  Package libgdk-pixbuf2.0-0:amd64 is not configured yet.
 librsvg2-common:amd64 depends on librsvg2-2 (= 2.40.2-1); however:
  Package librsvg2-2:amd64 is not configured yet.

dpkg: error processing package librsvg2-common:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgtk-3-bin:
 libgtk-3-bin depends on libc6 (>= 2.2.5); however:
  Package libc6:amd64 is not installed.
 libgtk-3-bin depends on libglib2.0-0 (>= 2.37.5); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.
 libgtk-3-bin depends on libgtk-3-0 (>= 3.10.8-0ubuntu1.4); however:
  Package libgtk-3-0:amd64 is not configured yet.

dpkg: error processing package libgtk-3-bin (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libatk1.0-0:amd64:
 libatk1.0-0:amd64 depends on libc6 (>= 2.2.5); however:
  Package libc6:amd64 is not installed.
 libatk1.0-0:amd64 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package libatk1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up glib-networking-common (2.40.0-1) ...
dpkg: dependency problems prevent configuration of libwayland-client0:amd64:
 libwayland-client0:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libwayland-client0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gir1.2-glib-2.0:
 gir1.2-glib-2.0 depends on libgirepository-1.0-1 (>= 1.40.0-1ubuntu0.2); however:
  Package libgirepository-1.0-1 is not configured yet.
 gir1.2-glib-2.0 depends on libglib2.0-0 (>= 2.39.91); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package gir1.2-glib-2.0 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libwayland-cursor0:amd64:
 libwayland-cursor0:amd64 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 libwayland-cursor0:amd64 depends on libwayland-client0 (>= 1.3.92); however:
  Package libwayland-client0:amd64 is not configured yet.

dpkg: error processing package libwayland-cursor0:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up ttf-dejavu-core (2.34-1ubuntu1) ...
dpkg: dependency problems prevent configuration of libxkbcommon0:amd64:
 libxkbcommon0:amd64 depends on libc6 (>= 2.17); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package libxkbcommon0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpangoft2-1.0-0:amd64:
 libpangoft2-1.0-0:amd64 depends on libc6 (>= 2.2.5); however:
  Package libc6:amd64 is not installed.
 libpangoft2-1.0-0:amd64 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.
 libpangoft2-1.0-0:amd64 depends on libharfbuzz0b (>= 0.9.9); however:
  Package libharfbuzz0b:amd64 is not configured yet.
 libpangoft2-1.0-0:amd64 depends on libpango-1.0-0 (>= 1.36.0); however:
  Package libpango-1.0-0 is not installed.

dpkg: error processing package libpangoft2-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up gnome-desktop3-data (3.8.4-0ubuntu3.1) ...
dpkg: dependency problems prevent configuration of cron:
 cron depends on libc6 (>= 2.7); however:
  Package libc6:amd64 is not installed.

dpkg: error processing package cron (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libjson0:amd64:
 libjson0:amd64 depends on libjson-c2; however:
  Package libjson-c2:amd64 is not configured yet.

dpkg: error processing package libjson0:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up libatk1.0-data (2.10.0-2ubuntu2) ...
dpkg: error processing package libc6:i386 (--configure):
 package libc6:i386 cannot be configured because libc6:amd64 is not ready (current status 'half-installed')
dpkg: dependency problems prevent configuration of libatk-bridge2.0-0:amd64:
 libatk-bridge2.0-0:amd64 depends on libatk1.0-0 (>= 2.10.0); however:
  Package libatk1.0-0:amd64 is not configured yet.
 libatk-bridge2.0-0:amd64 depends on libatspi2.0-0 (>= 2.9.90); however:
  Package libatspi2.0-0:amd64 is not configured yet.
 libatk-bridge2.0-0:amd64 depends on libc6 (>= 2.4); however:
  Package libc6:amd64 is not installed.
 libatk-bridge2.0-0:amd64 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.

dpkg: error processing package libatk-bridge2.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgnome-desktop-3-7:
 libgnome-desktop-3-7 depends on libc6 (>= 2.14); however:
  Package libc6:amd64 is not installed.
 libgnome-desktop-3-7 depends on libcairo2 (>= 1.2.4); however:
  Package libcairo2:amd64 is not configured yet.
 libgnome-desktop-3-7 depends on libgdk-pixbuf2.0-0 (>= 2.22.0); however:
  Package libgdk-pixbuf2.0-0:amd64 is not configured yet.
 libgnome-desktop-3-7 depends on libglib2.0-0 (>= 2.37.3); however:
  Version of libglib2.0-0:amd64 on system is 2.32.4-0ubuntu1.
 libgnome-desktop-3-7 depends on libgtk-3-0 (>= 3.3.6); however:
  Package libgtk-3-0:amd64 is not configured yet.

dpkg: error processing package libgnome-desktop-3-7 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gir1.2-freedesktop:
 gir1.2-freedesktop depends on gir1.2-glib-2.0 (= 1.40.0-1ubuntu0.2); however:
  Package gir1.2-glib-2.0 is not configured yet.

dpkg: error processing package gir1.2-freedesktop (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libatspi2.0-0:amd64
 libcairo2:amd64
 libpython3.4-minimal:amd64
 libgraphite2-3:amd64
 libgdk-pixbuf2.0-0:amd64
 libjson-c2:amd64
 glib-networking:amd64
 libudev1:amd64
 libapt-inst1.5:amd64
 gtk3-engines-unico:amd64
 libgirepository-1.0-1
 libcgmanager0:amd64
 libpangocairo-1.0-0:amd64
 libgtk-3-0:amd64
 libpango1.0-0:amd64
 libjbig0:amd64
 libtiff5:amd64
 libharfbuzz0b:amd64
 librsvg2-2:amd64
 glib-networking-services
 librsvg2-common:amd64
 libgtk-3-bin
 libatk1.0-0:amd64
 libwayland-client0:amd64
 gir1.2-glib-2.0
 libwayland-cursor0:amd64
 libxkbcommon0:amd64
 libpangoft2-1.0-0:amd64
 cron
 libjson0:amd64
 libc6:i386
 libatk-bridge2.0-0:amd64
 libgnome-desktop-3-7
 gir1.2-freedesktop
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
"

**Comment by divx118** [comment]
You have update problems you need to solve. Use `sudo enter-chroot -n precise` then resolve your problems on the chroot command line, until you can successfully run the following command there. `sudo apt-get update && sudo apt-get upgrade` Then try updating your chroot again with the command `sudo sh ~/Downloads/crouton -n precise -u` in a crosh shell like you did above. I don't know what you installed or maybe added other apt sources that would get you those dpkg errors. However googling them will most likely give you an answer to solve those.

**Comment by ShadowIceStorm** [comment]
Alright thanks

**Comment by Alfriadox** [comment]
Why is this open now?

**Comment by Alfriadox** [comment]
Can this be shut yet?
