### ISSUE TITLE
Unity -Facebook SDK - Error building Player: Win32Exception

### ISSUE THREAD

**Issue by StarWardo** [dnschneid/crouton#1807]
After installing the Facebook SDK to my project I get this error trying to build my game (android device):

Error building Player: Win32Exception: ApplicationName='javac.exe', CommandLine='-bootclasspath "D:/Documents/androidSDK/platforms/android-22\android.jar" -d "D:\Documents\multec\3D real time\Pinball2\Temp\StagingArea\bin\classes" -source 1.6 -target 1.6 -encoding UTF-8 "com\facebook\android\R.java" "com\StarWardo\Pinball\R.java"', CurrentDirectory='D:\Documents\multec\3D real time\Pinball2\Temp\StagingArea\gen'

(This is my first time posting on github, I hope this is the right place to post this question)

**Comment by dnschneid** [comment]
I think you discovered the answer to your parenthetical :) (#262)
