### ISSUE TITLE
[trusty] [stretch] xclip -o fails with "Error: target STRING not available"

### ISSUE THREAD

**Issue by savostyanov** [dnschneid/crouton#1812]
Just installed a fresh and minimal trusty chroot:

<pre>chronos@localhost ~/Downloads/crouton $ sudo enter-chroot -n trusty croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version git
release: trusty
architecture: armhf
xmethod: xephyr
targets: cli-extra,extension,x11
host: version 6812.88.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 13:52:51 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...</pre>

I've entered the chroot, run xinit, and in the xterm window typed

<pre> $ xclip -selection clipboard -o
Error: target STRING not available</pre>

The crouton integration Chrome browser extension was up and running and happily connected to trusty. 

The xinit output is below.

<pre>Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)draug@localhost:~$ xinit

Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
[dix] Could not init font path element /usr/share/fonts/X11/misc, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version git
release: trusty
architecture: armhf
xmethod: xephyr
targets: cli-extra,extension,x11
host: version 6812.88.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 13:52:51 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup</pre>

The same problem observed in stretch, but not in jessie.

**Comment by dnschneid** [comment]
If you switch away from the chroot and return to it, does it still fail?  It seems to not populate the clipboard on initial startup with xiwi, which is a bug.

**Comment by savostyanov** [comment]
If I Ctrl-Alt-Shift--> from the chroot and Ctrl-Alt-Shift--> back to it, the problem disappears!

**Comment by falematte** [comment]
Do we have a solution to this bug?
