### ISSUE TITLE
como puedo instalar kali linux con kde en mi thosiba chromebook 1 usando crouton???  Me dice error al iniciar . Puede que sea un error de grafica o prcesador no compatibles?????

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#1813]
How can I install Linux with KDE kali in my thosiba Chromebook 1 Using croutons ???
Start given to me error . You can sea Than A graphical error or unsupported prcesador ?????

**Comment by rubsalma** [comment]
sorry for my English , I have to use a translator

**Comment by rubsalma** [comment]
procesador = processor

**Comment by tonyxue** [comment]
Hola! Se puede publicar la salida?

> sorry for my English , I have to use a translator
No problem. I used translator too, except the first word :P
