### ISSUE TITLE
HP G3 Tegra K1 Hardware Acceleration or improvements.

### ISSUE THREAD

**Issue by asaggynoodle** [dnschneid/crouton#1814]
Good day fellow Gitters.

I've been using Crouton on my Chromebooks for a very long time, since the very first revision was made. Everything had always worked great, until I broke things.. Anyways, I just bought a new addition to the family, the HP G3 Tegra K1 powered Chromebook. I chose this over the Intel variants for more native ARC support for android applications. Which works great.

Then comes crouton; not very good. It's not crouton itself obviously, it's the lack of hardware acceleration from the GPU. I'm aware it's all down to the drivers, but has their been any improvements or even alternatives if native support is not possible. I mean, maybe some kind of faster alternative to iwix... I've tried all the major DE's, my hopes lie dying that XFCE or LXDE would have some kind of speed boost without direct acceleration. But, sheesh, moving windows around reminds me of running windows 98 on a 25Mhz 80486. It's just aweful. I thought that maybe I set something wrong, so I tried all the major desktops in both Xephyr and iwix. Latter is quicker, but very buggy when switching windows. Xephyr is too slow. 

Does anyone have any hacks or improvements on getting atleast some basic acceptable speed out of this? CPU hangs around ~20% and the 4GB of RAM is more than plenty. 

I tried Chrubuntu, but all of the setup scripts i've ran across are broken on the HP G3 (No Wifi driver, and they cannot detect the display so I get stuck with a TTy window.)

Any help is greatly appreciated in getting either Crouton working quicker, or pointing me in the direction of a Chrubuntu script that is not garbage.

Thank you for taking the time to at least make it this far. 
-Sam

**Comment by tonyxue** [comment]
See https://github.com/dnschneid/crouton/issues/1089
It has been noticed for a while and tried to solve.

**Comment by asaggynoodle** [comment]
@tonyxue 
"The armxorg stuff will be merged alongside the x11_freon branch (#1415), but that only provides access the the T1's framebuffer device, not real acceleration."

Hmm, I've not tried fbdev.. Is that supported out of the box by a install flag? Or in a config?

**Comment by tonyxue** [comment]
https://github.com/dnschneid/crouton/commit/0fafa652779f96aff7ce432643b02b0b4898054f

It helps you take care of it already. Is this something you are looking for?

If you are on the latest Crouton, that's the best solution so far.

**Comment by asaggynoodle** [comment]
Ahh, yes I see. I just re-installed Crouton this morning, So I'd assume I was using the latest as it was retrieved from GitHub.. I'm installing via the x11_Freon, as we speak. I'll keep this updated until I find the best available solution.
