### ISSUE TITLE
como puedo instalar kali linux con kde en mi thosiba chromebook 1 usando crouton???  Me dice error al iniciar . Puede que sea un error de grafica o prcesador no compatibles?????

### ISSUE THREAD

**Issue by rubsalma** [dnschneid/crouton#1816]
como puedo instalar kali linux con kde en mi thosiba chromebook 1 usando crouton??? 
Me dice error al iniciar . Puede que sea un error de grafica o prcesador no compatibles?????

**Comment by dnschneid** [comment]
See #1505.  It should work with the latest version of crouton; just don't force `xorg` (use `xiwi` or the auto-detecting `x11` instead).

**Comment by rubsalma** [comment]
thanks

2015-06-10 22:58 GMT+02:00 David Schneider <notifications@github.com>:
