### ISSUE TITLE
Insanely outdated packages

### ISSUE THREAD

**Issue by zwhitchcox** [dnschneid/crouton#1818]
I tried cli-extra and xcde, and I used apt-get update and apt-get install nodejs, and it installed version 6 of node. They're on 12 now. It did something similar with npm.

I don't know if these distros are being maintained any more, but if not, are there some that are and update their package managers?

**Comment by zwhitchcox** [comment]
So, unity is the best package for anyone else who can't get this to work. It takes up about 7GB though

**Comment by divx118** [comment]
unity, xfce, cli-extra are targets. They don't have any influence on package versions released with a distro. A distro release has influence on that, for example ubuntu releases precise, trusty etc and debian releases wheezy, jessie etc You probably used in a previous install release precise and now with unity release trusty.
