### ISSUE TITLE
Can't exit X or (apparently) switch back to ChromeOS

### ISSUE THREAD

**Issue by andrewmoise** [dnschneid/crouton#1822]
With the current crouton master, on a freshly installed stretch chroot, I can enter X using xinit, but then if I quit (by pressing Ctrl-D in the xterm), I get a black screen which Ctrl-Alt-Shift-Left doesn't seem to take me out of. I have to hold down the power button to force a shutdown.

After I did the hard shutdown, I tried again on the same chroot. After I started X and saw the xterm, I tried to switch back to ChromeOS using Ctrl-Alt-Shift-Left, but I only saw a black screen. If I hit it enough times I would get back to X, but I wasn't able to get back to ChromeOS.

I'm filing this specific bug report because I want to do everything from freshly-installed chroots and describe specific behavior so as to be filing useful bug reports as opposed to something caused by FS corruption from previous lockups (or old versions). But, the overall behavior on my machine is that I currently don't know of any way to install a crouton chroot within which X is usable.

Thanks in advance for any help, take care.

**Comment by idpnd** [comment]
yes, same here, acer c85-571, utopic, beta branch

**Comment by divx118** [comment]
@andrewmoise Can you post the output of `sudo enter-chroot croutonversion`

**Comment by andrewmoise** [comment]
```
chronos@localhost / $ sudo enter-chroot -n stretch croutonversion
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20150519153807~master:30cf02c9
release: stretch
architecture: amd64
xmethod: xorg
targets: xorg
host: version 6812.88.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 14:15:23 PDT 2015 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
chronos@localhost / $ 
```

This is a Dell Chromebook 11.

**Comment by divx118** [comment]
@andrewmoise Is there any reason you don't have a Desktop environment installed? If not then update your chroot with for example xfce target.
```
sudo sh ~/Downloads/crouton -n stretch -u -t xfce
```
Then use `sudo startxfce4 -n stretch` to start the xfce desktop.

**Comment by andrewmoise** [comment]
I used to have gnome, but it stopped working. I filed a bug and was told to start using xinit instead, so I switched to xinit+blackbox, which isn't ideal but at least was working. Now that's stopped working. I'm happy to try anything you think might work, although I think this is pretty obviously a case of crouton breaking, as opposed to anything that I'm doing wrong.

I tried to install the xfce target as requested, but that didn't work:

```
Selecting previously unselected package crouton-network-manager.
(Reading database ... 18647 files and directories currently installed.)
Preparing to unpack .../crouton-network-manager.deb ...
Unpacking crouton-network-manager (0) ...
Setting up crouton-network-manager (0) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 libxext-dev libxfixes-dev libxi-dev linux-libc-dev:i386
  x11proto-fixes-dev x11proto-xext-dev
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
chronos@localhost ~/Downloads $ 
```

Sounds like I should file a separate bug about stretch xfce not installing, no?

Thanks again.

**Comment by divx118** [comment]
Yep, looks like netsurf-gtk is not available on stretch.

**Comment by andrewmoise** [comment]
Okay, I'll file a separate bug for that then.

Getting back to the main point -- the reason this chroot is stripped down is that I'm trying to have a very simple environment, so that I can identify and report specific problems that are preventing my desktop environment from working. I'm not looking for user support ("Why don't you try doing X instead, that might work") so much as I am looking for "Yes, you're right, what you're doing should work, sounds like there's a bug and someone should fix it."

**Comment by divx118** [comment]
@andrewmoise Understandable, that is why I asked if you had a specific reason to not have a DE installed. The xfce example was mentioned if you hadn't a specific reason. I will take a look and see if I can replicate.

**Comment by andrewmoise** [comment]
Sure, no worries. I have a jessie chroot that I use as my main system, and I can easily delete and remake the stretch chroot to try out in a fresh environment any other things that you want me to check.

**Comment by macavity45** [comment]
I have the same problem but I have XFCE as my target:
crouton: version 1-20150617163120~master:5c73c9fd
release: stretch
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6946.55.0 (Official Build) stable-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP Tue May 26 18:05:38 PDT 2015 x86_64 GNU/Linux
freon: yes


I start my chroot with this:
sudo startxfce4 -n <myname>

But when I switch back to ChromeOS or log out of XFCE, I get a black screen.

**Comment by dnschneid** [comment]
I believe #2003 fixed this; please update with the latest crouton and re-open if it's still broken.

**Comment by jrowen** [comment]
I'm running into this issue with an Acer CB5-311
```
E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
```
using
```
sudo sh ~/Downloads/crouton -n stretch2 -t xfce -r stretch
```
I didn't run into this issue when I created the same chroot a few months back.
