### ISSUE TITLE
start lxde in separate tab

### ISSUE THREAD

**Issue by hashJuice** [dnschneid/crouton#1823]
Hello guys, I have installed trusty along with lxde and xiwi and xorg  on a fresh new crouton.
I can make xterm start in a separate window but whenever I try to get the lxde desktop running in a separate window it just switches to the lxde desktop and I still have to use CTRL+ALT+Arrows so switch back... Any ideas on how to make this work?

**Comment by DennisLfromGA** [comment]
I noticed this issue is closed so I hope that means you found an answer/method.
If not, you can start your lxde desktop in a window by using this:

  `sudo startlxde -X xiwi-window`

or by using this:

  `sudo startxiwi startlxde`

**Comment by hashJuice** [comment]
@DennisLfromGA Thank you that worked out! i tried it with sudo startxiwi  -T startlxde, now I have lxde running in a tab =)

**Comment by DennisLfromGA** [comment]
Great!
