### ISSUE TITLE
xfce target on stretch doesn't work

### ISSUE THREAD

**Issue by andrewmoise** [dnschneid/crouton#1824]
When I install a stretch chroot (with just the xorg target), and then attempt to add an xfce target to it, I get a failure to complete chroot setup:

```
chronos@localhost ~/Downloads $ sudo sh crouton -n stretch -u -t xfce
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/stretch already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
```

(snip)

```
Selecting previously unselected package crouton-network-manager.
(Reading database ... 18647 files and directories currently installed.)
Preparing to unpack .../crouton-network-manager.deb ...
Unpacking crouton-network-manager (0) ...
Setting up crouton-network-manager (0) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 libxext-dev libxfixes-dev libxi-dev linux-libc-dev:i386
  x11proto-fixes-dev x11proto-xext-dev
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
chronos@localhost ~/Downloads $ 
```

This is with the master crouton scripts:

```
chronos@localhost ~/Downloads $ sudo enter-chroot -n stretch croutonversion
Password: 
Entering /mnt/stateful_partition/crouton/chroots/stretch...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] n
Skipping setup. You will be prompted again next time.
crouton: version 1-20150519153807~master:30cf02c9
release: stretch
architecture: amd64
xmethod: xorg
targets: xfce,xorg
host: version 6812.88.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 14:15:23 PDT 2015 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
chronos@localhost ~/Downloads $ 
```

The error message is because of the xfce setup not completing properly.

Thanks in advance for your help.

**Comment by dereckson** [comment]
The  issue is the lack of the netsurf-gtk package on Debian Stretch.

This package is required by the gtk-extra target (a xfce target's dependency).

**Comment by dnschneid** [comment]
It appears to have (hopefully temporarily) disappeared from stretch.  A search on Google shows that the disappearance is even too recent for the search index (result shows up but page 404's).  Since it's still in sid, I suspect it will return soon.

**Comment by andrewmoise** [comment]
Right, looks to me like it's set to return in a few days if no RC bugs
are discovered. I'll keep an eye on it; thanks for the followup.
  -Andrew

**Comment by sopwerdna** [comment]
I realize that the cause of this problem is known and it looks like it will be resolved soon, but I think I should at least mention here that the problem appears to apply to enlightenment through the e17 target as well.

**Comment by dnschneid** [comment]
Yeah, any target that directly or indirectly includes `gtk-extra` will not work until stretch is fixed.

Someone might want to file a debian bug in case they haven't noticed the breakage.  Post back here with the bug number once you have.

**Comment by andrewmoise** [comment]
It looks to me like netsurf-gtk is back in testing; I can now install it with no issues from within the chroot. I still can't fully update my chroot (see issue #1850) but my guess is this bug can be closed now.
