### ISSUE TITLE
Have chroot on one screeen, ChromeOS on another.

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1826]
I would like to be running my chroot on my big screen and ChromeOS on my laptop screen. Is there a way to do this?

**Comment by tonyxue** [comment]
You can do it using the xiwi target. Simply drag the window to the screen.That's how I do it.





-Tony

**Comment by firestar115** [comment]
Yeah... I was thinking "No xiwi! It has title bars!" but now it makes
perfect sense because you can fullscreen it. I wish I could close the issue
from my email.

     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by Alfriadox** [comment]
close it from your browser.
