### ISSUE TITLE
run a script on every xiwi window open?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1828]
I have to run the command `setxkbmap -model chromebook` every time a xiwi window opens to fix the keyboard (#1558).  Is there any way xiwi could run a script of mine on every window open?  It needs to run in the new process but it doesn't have to run before the app that xiwi is opening.

This might have other use cases also.

**Comment by dnschneid** [comment]
Yep, just add your commands to `~/.xiwirc` in your chroot.
