### ISSUE TITLE
modesetting no longer a separate package in vivid

### ISSUE THREAD

**Issue by elbac** [dnschneid/crouton#1829]
Hey all, I've been scouring the internet trying to fix this issue and just can't seem to find it.

I just updated Ubuntu from 14.10 to the new version and when I tried to update the crouton, this happens:

sudo sh ~/Downloads/crouton -n precise -u

Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise already exists; updating it...
Unable to determine the release in /usr/local/chroots/precise. Please specify it with -r.

**Comment by leejinhuey** [comment]
New version meaning Vivid Veret? (15.04)

**Comment by elbac** [comment]
Ya know what, when I upgraded, it took me straight to wily werewolf.  So I reinstalled and made sure I had vivid vervet.  When the upgrade finished, it wouldn't let me reboot, so I forced it.  Now when I try to update the crouton, it goes through the entire update, and then at the end it gives me this:

E: Package 'xserver-xorg-video-modesetting' has no installation candidate
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/precise...

**Comment by dnschneid** [comment]
Wow, wily isn't even in alpha yet.

Yeah, it looks like vivid did the same thing as sid and integrated modesetting into core.  [This](https://github.com/dnschneid/crouton/blob/master/targets/xorg#L75) needs to be modified to blank out the package name if the release is sid or at least vivid.

**Comment by dnschneid** [comment]
Merged!  Should work better.
