### ISSUE TITLE
Can't update crouton kernel

### ISSUE THREAD

**Issue by llevene** [dnschneid/crouton#1830]
I have an Acer C710 Chromebook which I installed Ubuntu 14.04 (with LXDE desktop environment) to via crouton. By default, it comes with kernel version 3.14, and I need to get it to 3.19 for there to be support for my trackpad. I run the command sudo apt-get install linux-generic-lts-vivid, and it all goes normally, (when it asks I install grub to /dev/sda instead of /dev/sda1) but when i do sudo reboot and come back into ubuntu it is still on 3.14 i have tried installing 4.1 manually and i get the same result

any help much appreciated!

**Comment by divx118** [comment]
Not possible see #1427 at least not the way you want it.

**Comment by gryfxx** [comment]
Is the context that you want to run vagrant?
