### ISSUE TITLE
[solved] Can't connect to extension via xiwi or lxde or xfce4

### ISSUE THREAD

**Issue by hvdwolf** [dnschneid/crouton#1833]
Toshiba Chromebook 2
I installed crouton using the following command:
sudo sh ~/Downloads/crouton -r trusty -t xfce,extension,audio,gtk-extra,keyboard,xiwi

I also installed vlc and few other things to support that.

I tried "sudo startxiwi vlc" and got below mentioned error
I tried "sudo startxiwi xterm" and got below mentioned error
I tried "sudo startxfce4" and "sudo enter-chroot startxfce4" and got below mentioned error
I did the update step: "sudo sh ~/Downloads/crouton -u -n trusty" and that didn't help either.

I removed everything and reinstalled but now with lxde.
I got the exact same issues.
 =====
sudo enter-chroot startxfce4

Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashtree=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=e8d5eb56c862e952264ec4717e8398a1d7fa7aa9 salt=6c257451ffdb07295f3b1da1552915a8a174bdda04ee7f1063cb2b62a58da169" noinitrd vt.global_cursor_default=0 kern_guid=53f1dd78-d512-d54e-ab32-e6551aaac164 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jun  5 19:44:57 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,extension,audio,gtk-extra,keyboard,xiwi
host: version 6946.55.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by divx118** [comment]
@hvdwolf See `Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)` Follow the link and install the extension in chromeos and try again.

**Comment by hvdwolf** [comment]
Hi, thanks but it is installed. That's also what it mentions in the log (targets: xfce,extension,audio,gtk-extra,keyboard,xiwi). I did an update, both after the install of lxde and xfce4. Next to that I did a "sudo apt-get update; sudo apt-get upgrade". 

But just to be sure I did a "sudo sh -e ~/Downloads/crouton -r trusty -t extension -u"

Unfortunately it didn't change anything. Still the same error.

Just for completeness:
sudo enter-chroot croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xiwi
targets: extension,xfce,audio,gtk-extra,keyboard,xiwi
host: version 6946.55.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by divx118** [comment]
No it is not, follow the link and install it on chromeos. It is a chromeos extension and not the target extension in crouton.

**Comment by hvdwolf** [comment]
Thank you. That solved indeed the issue with "no connection".
I obviously did not read the instructuctions well enough. I did think it was a repetition of actions and I almost had reacted on the article for "this error", but it's definitely two separate actions: installation in Chrome and installation inside crouton.

Currently xiwi does not work properly yet as I only get black screens. Maybe the same as this issue: https://github.com/dnschneid/crouton/issues/1768

As it is a separate issue I close this one.

Thanks.

**Comment by KDCForum** [comment]
Hello,  I am having this same issue.  But as far as I can tell, the Crouton Integration Extension is installed by following goo.gl/OVQOEt.  I looked in Chrome and the Extension is there and enabled.
divx118 was very stern is saying that it was not, hvdwolf replied that now it is working and did not read the instructions.  As far as I can tell, I have installed the extension in the ChromeOS by going to Chrome and typing in the above URL link and then select add.
I know I am missing something.  But not sure what.  I would greatly appreciate some guidance.
Thanks
Keith.

**Comment by DennisLfromGA** [comment]
@KDCForum - There is an `extension` target that needs to be installed via crouton:

`sudo sh ~/Downloads/crouton -t extension -u [-n ...]`

And there is a Chrome Web Store app named 'Crouton Integration' extension that can be installed by following the link: http://goo.gl/OVQOEt

For 'xiwi' apps to work, they are both required.

**Comment by KDCForum** [comment]
Thanks DennisLfromGA.  Both was done, but still no positive results.  I decided to try a different procedure  at the below url link.  And that worked.
https://www.linux.com/learn/tutorials/795730-how-to-easily-install-ubuntu-on-chromebook-with-crouton

**Comment by DennisLfromGA** [comment]
@KDCForum - That's great but I think those instructions install xmethod 'xorg', I thought you were trying to use xmethod 'xiwi'. As long as it works and your happy then all is well.

**Comment by zig-fiedorowicz** [comment]
I have the same problem.  I found the following (apparent) solution.

I installed two chroots: one with xiwi running unity and another one without xiwi running kde.  If I boot my acer c720 and immediately try starting the xiwi chroot then crouton fails to connect to the extension and quits.  However if I first start the non-xiwi chroot and reboot the chromebox, then start the xiwi chroot, it does connect.  I first get a blank dark screen with  a single instruction to press F11 to exit fullscreen.  I then hold down the power button (corresponding to F11) and get a Chrome-OS login prompt.  After logging in to Chrome-OS I get the xiwi unity desktop and everything seems to work normally.

This is kind of weird, but so far it has been working for me.

**Comment by etavenn** [comment]
Had the same problem almost a year into using xfce4 successfully.  Had a quick fix. Crouton was disabled for some reason. Re-enabled, closed then opened up chrome and it worked.

Process:
1) Go to Chrome>settings (the three dots on the far right hand side)>more tools>extensions
2) Scroll down and find crouton. Its probably disabled. Click on "enable"
![screenshot 2016-10-25 at 6 03 35 pm](https://cloud.githubusercontent.com/assets/16109106/19709747/cc01ce62-9add-11e6-9341-df778fa5bd94.png)
3) Close all chrome browsers. Open up chrome.
4) Run shell and try again. Once you're in, you might see a black screen for 3-5 minutes. Grab a cup of coffee/tea while you wait.

Should work now!

I have a C720 and run xfce4 (Ubuntu 14.04)

**Comment by DennisLfromGA** [comment]
@etavenn,

*Thanx for that tip.* : )

Sometimes extensions do get disabled for one reason or another so this is a good step in troubleshooting the '`Cannot connect to extension, retrying...`' problem.

-**DennisL**
