### ISSUE TITLE
Mouse and Keyboard Failure in Ubuntu after Chromebook Update

### ISSUE THREAD

**Issue by lucashen** [dnschneid/crouton#1835]
I get this message when I am running the crouton update in the Chrome terminal on my chromebook. This happened right after a new chromebook update was installed. When I open Ubuntu everything freezes, can't use the keyboard or mouse, so have to shut down the computer using the powerbutton.

Err http://ppa.launchpad.net precise/main Sources  
  404  Not Found
Hit http://archive.ubuntu.com precise-updates/universe Translation-en
Err http://ppa.launchpad.net precise/main amd64 Packages  
  404  Not Found
Hit http://archive.ubuntu.com precise-security/main Translation-en
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en
Hit http://archive.ubuntu.com precise-security/restricted Translation-en
Hit http://archive.ubuntu.com precise-security/universe Translation-en
Err http://ppa.launchpad.net precise/main i386 Packages  
  404  Not Found
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en
Ign https://private-ppa.launchpad.net precise/main Translation-en
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/source/Sources  404  Not Found                          

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: The following packages cannot be authenticated!
  orage xfce4
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Any help really appreciated!

Thank You!

**Comment by Alfriadox** [comment]
How are you connected to the internet?

**Comment by lucashen** [comment]
Wifi

**Comment by Alfriadox** [comment]
are you able to run `sudo enter-chroot` in chrome shell without encountering any errors?
