### ISSUE TITLE
backup documentation should mention ~/Downloads

### ISSUE THREAD

**Issue by recri** [dnschneid/crouton#1838]
Specifically, if you powerwash and restore a crouton backup, your ~/Downloads/ directory will not be restored.  So if you stored anything there so it could go back and forth between ChromeOS and Crouton, it's gone.  It's not backed up by crouton and not backed up by ChromeOS.

**Comment by dnschneid** [comment]
That's a good point.  Documentation should be updated for that (pie).

Taken a step further, there should be an option for edit-chroot to backup and restore the /etc/crouton/shares directories as well, probably as a separate tarball (not necessarily pie).

**Comment by tedm** [comment]
If no one writes this up by the weekend, I'll give it a stab. The things to cover are that ~/Downloads may not always be persistent, or even available if you use certain autostart functions.

But yeah, if you backup your chroot, your chroot /home/Downloads content needs to be backed up in addition to chroot and/or system state.

**Comment by DennisLfromGA** [comment]
@tedm,

> The things to cover are that ~/Downloads may not always be persistent,...

True. 

> ...or even available if you use certain autostart functions.

Not True.
This doesn't have anything to do with 'autostart functions', it's about what happens after a 'powerwash'.

**Comment by tedm** [comment]
@DennisLfromGA You are correct. You could probably write this up more accurately. Here is something I specifically don't tknow, and don't expect to test by weekend:

What happens to the user who enables autostart, and it works, then does a system restore to usb drive, AND a Crouton chroot backup AND separately downloads their ~/Downloads directory, then for whatever reason does a Powerwash, and then restores from all 3 backups?

Are they fully restored? In all 4 autostart modes? (assuming no nasty auto-upgrades between powerwash and restore period).

**Comment by DennisLfromGA** [comment]
@tedm - Let's not hijack this thread, we can continue to discuss this at https://github.com/dnschneid/crouton/issues/1846, thanx.

**Comment by tedm** [comment]
@recri I have edited the backup section of the wiki to include the importance of backing up ~/Downloads in addition to your chroot. Please review, and close if you feel it addresses the situation for future use. Thanks for noticing this issue.

**Comment by recri** [comment]
That looks great on the wiki, but the impatient people who learn to do
backups from the README.md will remain at risk.

In a sense, the problem is that the architecture of chroot is intrinsically
messy and there's nothing to be done about that.  It's a leaky sandbox
inside another sandbox, things that it appears to contain are actually
outside (~/Downloads), a description of what's really in it gets hopelessly
long and complicated, it's hard to write such complicated descriptions
because you can feel your readers falling asleep.

Thanks,

-- rec --

**Comment by tedm** [comment]
@recri Thanks for closing, but is your recommendation to put the warning of backing up ~/Downloads also in this README.md? I wonder if the -b backup feature of edit-chroot can just be modified to backup ~/Downloads and add it to the tarball??

**Comment by recri** [comment]
No, adding ~/Downloads to the chroot backup would introduce a loop, since
the backup is being written to ~/Downloads by default.

But yes, the README.md should address the problem and link to the more
detailed discussion in the wiki.

The basic issue for me is that once you decide you like using crouton, now
you have to decide how to keep it running as you powerwash and change the
channels on your Chromebook.  I was backing up my home directory with rsync
onto an sdcard, and I almost lost ~/Downloads/ when I switched to using
edit-chroot -b.  A section in README.md and the wiki discussing how to
preserve your crouton chroot through powerwash cycles would be good.

-- rec --

**Comment by tedm** [comment]
@recri Thanks, I see the issue with backing up Downloads, and the only work arounds (a counter) would have to assume more space than may be available.

I am not sure I should just copy and paste the detailed backup procedures in README.md, but perhaps a note in README.md to fully read the WIKI on BACKUPS should be good @dnschneid
