### ISSUE TITLE
Error with KDE: Dolphin won't run properly as root.

### ISSUE THREAD

**Issue by ajshell1** [dnschneid/crouton#1840]
Before a recent crouton update, I was able to use Dolphin just fine. But after this update, none of the graphical user interface parts of Dolphin show up. I just see a grey window. While this is happening, this is being spammed in the terminal:
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x6a0007a
How do I fix this?

**Comment by Alfriadox** [comment]
What linux release / flavour do you have?

**Comment by ajshell1** [comment]
Ubuntu 14.04.

**Comment by dnschneid** [comment]
What's the output of `croutonversion`?  Why are you running dolphin as root?

**Comment by ajshell1** [comment]
The output is:
(trusty)aj@localhost:~$ croutonversion
crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xorg
targets: kde
host: version 6946.55.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes


Also, I need to run Dolphin as root because I decided the best place to put some of my games was in a ~/games/ that I created and I need to run Dolphin as root in order to transfer files from my ~/Downloads/ folder to ~/games/. Yes, I realize the risk of running stuff as root.

Also, my chroot is located on an external hard drive, in case that helps.

**Comment by DennisLfromGA** [comment]
@ajshell1,

> I need to run Dolphin as root in order to transfer files from my ~/Downloads/ folder to ~/games/. 

If they are both owned by your user id, I don't see why you have to have root perms to copy/move them while in the chroot, are you sure it's necessary?

**Comment by ajshell1** [comment]
It turns out that the ~/games/ folder was owned by "root" rather than by me. I fixed this with sudo chown -R, but I still can't run dolphin as root correctly. I just don't like the idea that there is a bug in my system, so I'd really appreciate somebody telling me how to fix this.

**Comment by tedm** [comment]
@ajshell1 Here is your answer:

http://www.iwillfolo.com/quick-fix-one-kdes-common-xorg-errors-x-error-baddrawable/

Please donate the computer or games to your local cat shelter. Thanks!

**Comment by drinkcat** [comment]
> Please donate the computer or games to your local cat shelter. Thanks!

I don't what this is about, but I approve.
