### ISSUE TITLE
Problem updating crouton with Debian sid

### ISSUE THREAD

**Issue by Asdas91** [dnschneid/crouton#1843]
And that is a problem because I recently updated ChromeOS and I need to update to start debian.

command and output:

chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n sid
/usr/local/chroots/sid already exists; updating it...
Enter encryption passphrase for sid: 
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startlxde into the host...
Installing crouton-noroot into the chroot...
Installing startlxde into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://ppa.launchpad.net trusty InRelease
Ign http://dl.google.com stable InRelease                                                                               
Hit http://ftp.debian.org sid InRelease                                                                                  
Hit http://download.mono-project.com wheezy InRelease                                                                    
Hit http://ppa.launchpad.net trusty Release.gpg                                                                            
Hit http://dl.google.com stable Release.gpg                                                                                
Hit http://ppa.launchpad.net trusty Release                                                          
Get:1 http://ftp.debian.org sid/main Sources/DiffIndex [7876 B]                                                   
Ign http://linux.dropbox.com jessie InRelease                                                                            
Hit http://dl.google.com stable Release                                                     
Hit http://download.mono-project.com wheezy/main amd64 Packages                             
Hit http://ppa.launchpad.net trusty/main Sources                                            
Get:2 http://ftp.debian.org sid/non-free Sources/DiffIndex [7819 B]                                                              
Hit http://download.mono-project.com wheezy/main i386 Packages                                                                             
Hit http://ppa.launchpad.net trusty/main amd64 Packages                                                           
Hit http://dl.google.com stable/main amd64 Packages                                                                              
Get:3 http://ftp.debian.org sid/contrib Sources/DiffIndex [7819 B]                                                               
Hit http://ppa.launchpad.net trusty/main i386 Packages                                                                                      
Hit http://dl.google.com stable/main i386 Packages                                                                
Get:4 http://ftp.debian.org sid/main amd64 Packages/DiffIndex [7876 B]                                            
Hit http://ppa.launchpad.net trusty/main Translation-en                                                                   
Get:5 http://ftp.debian.org sid/non-free amd64 Packages/DiffIndex [7819 B]                                                
Get:6 http://ftp.debian.org sid/contrib amd64 Packages/DiffIndex [7819 B]                   
Get:7 http://ftp.debian.org sid/main i386 Packages/DiffIndex [7876 B]                       
Get:8 http://ftp.debian.org sid/non-free i386 Packages/DiffIndex [7819 B]                   
Get:9 http://ftp.debian.org sid/contrib i386 Packages/DiffIndex [7819 B]                    
Get:10 http://ftp.debian.org sid/contrib Translation-en/DiffIndex [7819 B]                  
Get:11 http://ftp.debian.org sid/main Translation-en/DiffIndex [7876 B]                     
Get:12 http://ftp.debian.org sid/non-free Translation-en/DiffIndex [7819 B]                 
Hit http://linux.dropbox.com jessie Release.gpg                                             
Ign http://download.mono-project.com wheezy/main Translation-en                             
Hit http://linux.dropbox.com jessie Release     
Ign http://dl.google.com stable/main Translation-en
Hit http://linux.dropbox.com jessie/main amd64 Packages                                                                                             
Hit http://linux.dropbox.com jessie/main i386 Packages                                                                                              
Ign http://linux.dropbox.com jessie/main Translation-en                                                                                             
Fetched 94.1 kB in 7s (12.9 kB/s)                                                                                                                   
Reading package lists... Done
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... linux-libc-devThe following packages were automatically installed and are no longer required:
  libhogweed2:i386 libjim0.75 libnettle4:i386 liboath0 libopenconnect3 libplist2 libvncclient0 libx264-142 libx264-142:i386 libx265-51:i386
  libx265-51
Use 'apt-get autoremove' to remove them.
Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version.
ca-certificates is already the newest version.
sudo is already the newest version.
wget is already the newest version.
The following packages were automatically installed and are no longer required:
  libhogweed2:i386 libjim0.75 libnettle4:i386 liboath0 libopenconnect3 libplist2 libvncclient0 libx264-142 libx264-142:i386 libx265-51:i386
  libx265-51
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 103c37a8bf17ea65d590acd56f5d1a1778d27b1e)...
--2015-06-09 09:26:23--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/103c37a8bf17ea65d590acd56f5d1a1778d27b1e.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 173.194.67.82
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.67.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.eDFJl6/adhd.tar.gz'

     0K .......... .......... .......... .......... ..........  362K
    50K .......... .......... .......... .......... ..........  583K
   100K .......... .......... .......... .......... ..........  640K
   150K .......... .......... .......... .......... ..........  613K
   200K .......... .......... .......... .......... ..........  630K
   250K .......... .......... .......... .......... ..........  610K
   300K .......... .......... .......... .......... ..........  618K
   350K .......... .......... .......... .......... ..........  610K
   400K .......... .......... .......... .......... .....       624K=0.8s

2015-06-09 09:26:24 (571 KB/s) - '/tmp/crouton-cras.eDFJl6/adhd.tar.gz' saved [456003]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version.
libasound2:i386 is already the newest version.
libspeexdsp1:i386 is already the newest version.
The following packages were automatically installed and are no longer required:
  libhogweed2:i386 libjim0.75 libnettle4:i386 liboath0 libopenconnect3 libplist2 libvncclient0 libx264-142 libx264-142:i386 libx265-51:i386
  libx265-51
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version.
gcc-multilib is already the newest version.
gcc-multilib set to manually installed.
pkg-config is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev:i386 : Depends: linux-libc-dev:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

**Comment by mkasick** [comment]
The linux-libc-dev package is currently broken in sid.  The immediate problem is that crouton needs to install the i386 version to compile CRAS, and the current i386 version (4.0.4-1) is incompatible with the highest-available amd64 version (4.0.2-1).

As a workaround, you can install the 4.0.2-1 linux-libc-dev:i386 package from snapshots and re-run the crouton upgrade.  To install the older package, enter the chroot and run:
```
wget 'http://snapshot.debian.org/archive/debian/20150512T034855Z/pool/main/l/linux/linux-libc-dev_4.0.2-1_i386.deb'
sudo dpkg -i linux-libc-dev_4.0.2-1_i386.deb
```

You may also consider switching to testing in the future, if possible, as sid does have broken package problems like this one from time to time.
