### ISSUE TITLE
keyboard: problems with mappings on UK Pixel keyboard via xiwi

### ISSUE THREAD

**Issue by stsquad** [dnschneid/crouton#1844]
I have a UK spec pixel and have installed both the keyboard and xiwi targets. However a number of the mappings don't work, most annoyingly the Search+arrow keys for page-up/down, home/end. The info I have so far, xmodmap:

    !
    ! executing work queue
    !
    xmodmap:  up to 3 keys per modifier, (keycodes in parentheses):

    shift       Shift_L (0x32),  Shift_R (0x3e)
    lock        Caps_Lock (0x42)
    control     Control_L (0x25),  Control_R (0x69)
    mod1        Alt_L (0x40),  Meta_L (0xcd)
    mod2        Num_Lock (0x4d)
    mod3      
    mod4        Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
    mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)

setxkbmap report:

    Setting verbose level to 10
    locale is C
    Trying to load rules file ./rules/evdev...
    Trying to load rules file /usr/share/X11/xkb/rules/evdev...
    Success.
    Applied rules from evdev:
    rules:      evdev
    model:      chromebook
    layout:     gb
    Trying to build keymap using the following components:
    keycodes:   evdev+aliases(qwerty)
    types:      complete
    compat:     complete+chromebook
    symbols:    pc+gb+inet(evdev)+chromebook(overlay)
    geometry:   pc(pc104)
    xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)"	};
        xkb_types     { include "complete"	};
        xkb_compat    { include "complete+chromebook"	};
        xkb_symbols   { include "pc+gb+inet(evdev)+chromebook(overlay)"	};
        xkb_geometry  { include "pc(pc104)"	};
    };

xev grabbing the events as I did Super + Up, Down, Left and Right:

    KeyRelease event, serial 18, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 492925, (609,463), root:(611,481),
        state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
        XLookupString gives 1 bytes: (0d) ""
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 495460, (609,463), root:(611,481),
        state 0x0, keycode 111 (keysym 0xff52, Up), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 495460, (609,463), root:(611,481),
        state 0x0, keycode 111 (keysym 0xff52, Up), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 495615, (609,463), root:(611,481),
        state 0x0, keycode 111 (keysym 0xff52, Up), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 496674, (609,463), root:(611,481),
        state 0x0, keycode 116 (keysym 0xff54, Down), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 496674, (609,463), root:(611,481),
        state 0x0, keycode 116 (keysym 0xff54, Down), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 496791, (609,463), root:(611,481),
        state 0x0, keycode 116 (keysym 0xff54, Down), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 497911, (609,463), root:(611,481),
        state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 497911, (609,463), root:(611,481),
        state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 498055, (609,463), root:(611,481),
        state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 498980, (609,463), root:(611,481),
        state 0x0, keycode 114 (keysym 0xff53, Right), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 498980, (609,463), root:(611,481),
        state 0x0, keycode 114 (keysym 0xff53, Right), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 499132, (609,463), root:(611,481),
        state 0x0, keycode 114 (keysym 0xff53, Right), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyRelease event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 499951, (609,463), root:(611,481),
        state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 21, synthetic NO, window 0xe00009,
        root 0x1a6, subw 0xe0000e, time 499951, (609,463), root:(611,481),
        state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

Any ideas? Where does the translation get done?

**Comment by Alfriadox** [comment]
Can you run `xmodmap -pke` please and tell us the out put.

**Comment by Alfriadox** [comment]
Wait what are you trying to, because if you want to set key commands for page up / down , home, end, then that has nothing to do with `xmodmap` or `xev` as they are tools for key board mapping as in changing the search key to the super key like I did in #1845 .

**Comment by stsquad** [comment]
@Alfriadox will do when I get home. I'm a little confused, I thought the whole purpose of the overlay was to provide Chrome-like keyboard shortcuts to the crouton session.

**Comment by dnschneid** [comment]
The keyboard target isn't currently fully working in xiwi.  See #1558.  There's a pull request up that I haven't tested yet that apparently fixes the situation.

**Comment by stsquad** [comment]
@dnschneid ahh that's confusing because it used to work. Does this mean my Pixel has switched to Freon in the meantime?

**Comment by cribalik** [comment]
@stsquad ChromeOS has been moving to Freon on more machines with later releases, so it is very plausible that your Pixel recently switched to Freon.
