### ISSUE TITLE
croutonversion and autostart

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#1846]
With autostart enabled in the 4th mode (enable ~/Downloads), croutonversion -d -u in the chroot doesn't save or download the latest crouton.

The folder is shared though, and a manual download of crouton puts it in ~/Downloads. I think croutonversion needs to know the new place to place crouton.

**Comment by DennisLfromGA** [comment]
@tedm - I'm not sure how 'autostart' is involved here. Are you trying to 'autostart' a chroot and run `enter-chroot croutonversion -d -u` as the 'START_DE' and/or 'CHROOT_APP'?

**Comment by DennisLfromGA** [comment]
Are you saying that after a chroot is started via 'autostart' that, when in the chroot, `croutonversion -d -u` doesn't download crouton to ~/Downloads? I'll test it but I don't believe I've ever encountered any problems with ~/Downloads not shared/common between the cgriit and Chrome OS.
 
> croutonversion -d -u in the chroot doesn't save or download the latest crouton.

Does it throw an error or put it in another location?

**Comment by tedm** [comment]
@DennisLfromGA I can't remember if it exited, but after running it like I usually do, there was no crouton in ~/Downloads so I had to go get it. It's possible that it put it in another location or checked in another location. I'll test for it next time I run it.

I also installed a new chroot, a unity one on precise. I might want to autostart that one instead of my trusty at some point, but I know there are 3 more parameters somewhere for crouton.init so I kind of wish I had the big 52 line commented out file so I can see if any missing parameters should be used when I toggle unity to start. But I can manually compare the 5-6 options and see what is needed, then keep the trusty/xfce chroot backed up as crouton.init.trustyxfce so I can change back easily.

Do you have a better way of managing different autostart chroots?

**Comment by DennisLfromGA** [comment]
@tedm - I just tested it on my HP Chromebook 14 and `croutonversion -d -u` d/l and installed a fresh version of crouton in ~/Downloads. However, it was the original 'crouton' installer script, not the newer 'crouton' indirect installer script since `croutonversion` uses a different link/location.

----
> I might want to autostart that one instead of my trusty at some point

The six parameters possible in the 'crouton.init' script are as follows:
```
DELAY=10            # delay desired number of seconds before starting ##
CHROOT=precise      # enter desired chroot to start                   ##
START_DE=startxfce4 # enter desired Desktop Envirnoment to use        ##
CHROOT_APP=none     # enter desired chroot application to run         ##
XMETHOD=default     # enter temporary X-Window Envirnoment to use     ##
RUN_STATE=y         # change to 'n' to disable running $CHROOT        ##
```
The above values are set in `/etc/init/crouton.conf` by default so, if you your chroot needs any different values, just place them in `~/Downloads/crouton.init`.
So, for example, if you want to run unity instead of xfce, your `crouton.init` file would consist of:
`START_DE=startunity`
nothing more is needed.

**Comment by DennisLfromGA** [comment]
@tedm,

> But I can manually compare the 5-6 options and see what is needed, then keep the trusty/xfce chroot backed up as crouton.init.trustyxfce so I can change back easily.

Yes, do just as you noted above and rename the `crouton.init` file with all the parameters needed for your 'trusty' chroot to `crouton.init.trustyxfce` if you like, make another with all the parameters needed for your 'precise' chroot and rename it `crouton.init.preciseunity`. Continue this method for any other chroots or the same chroots with different START_DE's for instance.

> Do you have a better way of managing different autostart chroots?

Yes, kind'a.
Once you have a number of unique crouton.init files as above, just 'link' the one you want to use next to `crouton.init`. Similar to:
`ln -s ~/Downloads/crouton.init.preciseunity ~/Downloads/crouton.init`

**Comment by dnschneid** [comment]
croutonversion downloads the true installer, not the indirect one.  I don't think that needs to change, since people doing so fundamentally know to get the latest version.

If your chroot is autostarting before you log in, the Downloads folder won't be available for sharing when the chroot starts.  Perhaps that's what you're running into?

**Comment by DennisLfromGA** [comment]
@tedm - wrote:
> What happens to the user who enables autostart, and it works, then does a system restore to usb drive, AND a Crouton chroot backup AND separately downloads their ~/Downloads directory, then for whatever reason does a Powerwash, and then restores from all 3 backups?

What do you mean "what happens to the user"?
1. They'll have a system restore on a usb
2. They'll have a chroot backup - where is up to the user.
3. They'll have a backup of their ~/Downloads folder
4. After the powerwash and restore of all 3 backups they'll should be back in business.

> Are they fully restored? In all 4 autostart modes? (assuming no nasty auto-upgrades between powerwash and restore period).

1. They are fully restored if they completed without error(s).
2. Autostart modes should work if the `crouton.init` file(s) in the ~/Downloads folder(s) were restored.

However, if a system update has been performed, then `rw-rootfs` will need to be re-run and `/etc/init/crouton.conf` will have to be downloaded and reinstalled.

**Comment by tedm** [comment]
@dnschneid yes, that is what happened, on Sat or so. . I installed autostart of a trusty chroot (start mode 4, that is suppsed to keep Downloads contents?), and prior to autostart, I had a the trusty chroot installed, with crouton in Downloads, but just not autostarting. then I wanted to install a unity chroot, but whoa, no crouton in ~/Downloads. as root did a find / -name crouton, and nowhere to be found. I know I would not rm a crouton, so I thought croutonversion -d -u would just download one, but it didn't, so I went to github to get it. So somewhere it got lost or renamed.

@DennisLfromGA OK, I agree that this issue is all about the downloads folder when it exists, and to make note to back it up and restore it, and I've always had it except the autostart seems to maybe move it or take some files out??

**Comment by tedm** [comment]
oh, and a note to preserve state /boot /use - just stay off the network between backup / powerwash and restore system from usb, chroot and downloads from usb or wherever, when you absolutely need to restore to known previous working condition.

**Comment by tedm** [comment]
a nice feature would be a grub like screen: default chromeos, but other options would be chromeos with chroot a, chromeos with chroot b, chromeos with chroot a and b, etc.

**Comment by DennisLfromGA** [comment]
@tedm,

> @dnschneid yes, that is what happened, on Sat or so.
>> If your chroot is autostarting before you log in, the Downloads folder won't be available for sharing when the chroot starts.

That's another reason to add a short delay before starting your chroot after logging in.
The `crouton.conf` file includes a 10 second delay but you can change it in your `crouton.init` file.

> ...and I've always had it except the autostart seems to maybe move it or take some files out??

I guarantee you that 'autostart' didn't move or take any files out.
Look at the `crouton.conf` script and tell me where that happens?

**Comment by DennisLfromGA** [comment]
@tedm - 

> a nice feature would be a grub like screen: default chromeos, but other options would be chromeos with chroot a, chromeos with chroot b, chromeos with chroot a and b, etc.

Refer to https://github.com/dnschneid/crouton/issues/1468#issuecomment-77066112

**Comment by tedm** [comment]
@DennisLfromGA I am sure that it was some typo of mine or something, but if I see it again, I'll try to reproduce the steps. I haven't yet tried a different chroot to startup (Can I start up more than one?), but I did add some info. to the wiki about being sure to backup ~/Downloads, since the regular chroot backup does not back that dir up. If it's OK, @dnschneid or the OP can close it.

**Comment by tedm** [comment]
@DennisLfromGA I tried replacing precise with trusty in my crouton.init file but precise / unity did not come up. I did revert back to trusty and trusty comes up. I also changed the 0 to 10 seconds and it does wait.
