### ISSUE TITLE
Custom xkbcomp copy and paste misfire only under Chrome browser

### ISSUE THREAD

**Issue by popham** [dnschneid/crouton#1847]
I get some quirky behavior under `google-chrome-stable`.

I've got a custom `xkbcomp` configuration that binds `C-C` and `C-V` to copy and paste.  Under my `xkbcomp` configuration I've got a type for `Shift+Control`-based hotkeys:

```
type "HOT_KEYABLE_ALPHABETIC" {
    modifiers= Shift+Control;
    map[Shift]= Level2;
    map[Control+Shift]= Level3;
    preserve[Control]= Control;
};
```

For `'c'` and `'v'`, I've got bindings:

```
key <COPY> {         [        XF86Copy ] };
key <PAST> {         [       XF86Paste ] };
key <AB03> {
    type= "HOT_KEYABLE_ALPHABETIC",
    symbols[Group1]= [               c,               C ],
    actions[Group1]= [      NoAction(),      NoAction(), RedirectKey(key=<COPY>, clearmods=Shift+Control) ]
};
key <AB04> {
    type= "HOT_KEYABLE_ALPHABETIC",
    symbols[Group1]= [               v,               V ],
    actions[Group1]= [      NoAction(),      NoAction(), RedirectKey(key=<PAST>, clearmods=Shift+Control) ]
};
```

When I
- enter Chrome,
- highlight some text, `'asdf'`, in the address bar,
- press `'c'`,
- move my cursor to unhighlight,
- and finally press `'v'`,

I get `'c'` in place of the original `'asdf'`, and I get `'asdfv'` inserted at the cursor position.  If I perform the same sequence of operations in a new Firefox session, then everything behaves as expected.  That is, the original `'asdf'` maps to `'c'`, the final cursor position gets a `'v'` inserted, and `C-V` is independent of `'asdf'`.  If I poke at the configuration under `xev`, then I get my expected bindings.

I've just recently coped with the migration to Freon, so I suspect that Chrome is detecting its Freon environment and circumventing/incorporating my bindings in some goofball fashion.

`croutonversion`:

```
crouton: version git
release: precise
architecture: amd64
xmethod: xorg
targets: x11
host: version 6946.55.0 (Official Build) stable-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:06 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by xrmedge** [comment]
Hello @Popham,

I am a coder, but this message is not related to this issue. I am a friend of one of your former employers. 

He has a matter of pressing importance to discuss with you. Since he is unfamiliar with GitHub he asked me to see if I could reach you on here. It is nothing bad - in fact, the situation is in your favor. 

For further details, please contact me as soon as you can at ehp724-jc@yahoo.com.

Thanks,
Aron
