### ISSUE TITLE
Can't finish update

### ISSUE THREAD

**Issue by Magyktime** [dnschneid/crouton#1848]
When I tried to start crouton today it was telling me that the "startxfce4" command is not found. I figured that maybe updating crouton would fix it, but when I try to update crouton it attempts to go through and update all of my packages, and gets stuck here:
28% [3 openjdk-6-jre-headless 32.6 MB/32.7 MB 100%]

Since I can't get into the chroot, here is the output from cat /etc/lsb-release
Thanks in advance.

CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={A772AA64-E906-A01E-1DFD-1856870D39EC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={A772AA64-E906-A01E-1DFD-1856870D39EC}
CHROMEOS_RELEASE_BOARD=quawks-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=55
CHROMEOS_RELEASE_BUILD_NUMBER=6946
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=43
CHROMEOS_RELEASE_DESCRIPTION=6946.55.0 (Official Build) stable-channel quawks 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6946.55.0
GOOGLE_RELEASE=6946.55.0

**Comment by DennisLfromGA** [comment]
You may still be able to get into your chroot shell with `sudo enter-chroot`.
If that works, then try `sudo apt-get update; sudo apt-get upgrade` and see if that finishes without any errors.

**Comment by Magyktime** [comment]
Hey, that worked. Thanks so much.
