### ISSUE TITLE
xfce4 not launching?

### ISSUE THREAD

**Issue by Lucas502** [dnschneid/crouton#1849]
Here are the details: http://pastebin.com/iJRL3vim

Thank you in advance.

Edit: I'm trying to run Arch Linux.

**Comment by tonyxue** [comment]
Did you installled the Chrome extension as the output stated?

**Comment by Lucas502** [comment]
I did that, worked, thanks.

**Comment by giliammc** [comment]
pleas close the issue

**Comment by Lucas502** [comment]
ISSUE SOLVED

**Comment by giliammc** [comment]
the issue is still open you need to hit the close button

**Comment by Lucas502** [comment]
Where
