### ISSUE TITLE
Can't enter KDE desktop from Chrome OS.

### ISSUE THREAD

**Issue by FightOwensFight** [dnschneid/crouton#1851]
(I'm a noob at this so excuse me) Whenever I open crouton I type in 'shell' then hit enter and type in 'sudo startkde' as usual and it usually takes me to the KDE desktop. But now when I do this I get this error:

Entering /mnt/stateful_partition/crouton/chroots/saucy...

X.Org X Server 1.14.6
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-37-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=d29dfd99-1252-5f49-98fa-73224f08a523/PARTNROFF=1 hashtree=PARTUUID=d29dfd99-1252-5f49-98fa-73224f08a523/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=e8d5eb56c862e952264ec4717e8398a1d7fa7aa9 salt=6c257451ffdb07295f3b1da1552915a8a174bdda04ee7f1063cb2b62a58da169" noinitrd vt.global_cursor_default=0 kern_guid=d29dfd99-1252-5f49-98fa-73224f08a523 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 01 May 2014  09:47:30PM
xorg-server 2:1.14.6-0ubuntu1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Thu Jun 11 09:40:18 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/saucy...

Can someone tell me what's wrong and how I can fix this?

**Comment by divx118** [comment]
Did you update your chroot? If not do it see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by Alfriadox** [comment]
Updating the chroot should fix it.

**Comment by FightOwensFight** [comment]
When I update it, it says:
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: precise,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.
chronos@localhost / $ sudo sh ~/Downloads/crouton -n precise -u
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Get:1 http://archive.ubuntu.com precise Release.gpg [198 B]
Get:2 http://archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:3 http://archive.ubuntu.com precise-security Release.gpg [198 B]
Hit http://archive.ubuntu.com precise Release
Ign http://archive.ubuntu.com precise Release    
Get:4 http://archive.ubuntu.com precise-updates Release [196 kB]
Get:5 http://archive.ubuntu.com precise-security Release [54.3 kB]
Ign http://archive.ubuntu.com precise-updates Release    
Ign http://archive.ubuntu.com precise/main Sources/DiffIndex
Ign http://archive.ubuntu.com precise/restricted Sources/DiffIndex
Ign http://archive.ubuntu.com precise/universe Sources/DiffIndex
Ign http://archive.ubuntu.com precise/multiverse Sources/DiffIndex
Ign http://archive.ubuntu.com precise/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise/multiverse amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise/main i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security Release
Ign http://archive.ubuntu.com precise/restricted i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise/universe i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise/multiverse i386 Packages/DiffIndex
Hit http://archive.ubuntu.com precise/main TranslationIndex
Hit http://archive.ubuntu.com precise/multiverse TranslationIndex
Hit http://archive.ubuntu.com precise/restricted TranslationIndex
Hit http://archive.ubuntu.com precise/universe TranslationIndex
Ign http://archive.ubuntu.com precise-updates/main Sources/DiffIndex
Ign http://archive.ubuntu.com precise-updates/restricted Sources/DiffIndex
Ign http://archive.ubuntu.com precise-updates/universe Sources/DiffIndex
Ign http://archive.ubuntu.com precise-updates/multiverse Sources/DiffIndex
Ign http://archive.ubuntu.com precise-updates/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-updates/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-updates/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-updates/multiverse amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-updates/main i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-updates/restricted i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-updates/universe i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-updates/multiverse i386 Packages/DiffIndex
Get:6 http://archive.ubuntu.com precise-updates/main TranslationIndex [10.6 kB]
Get:7 http://archive.ubuntu.com precise-updates/multiverse TranslationIndex [7613 B]
Get:8 http://archive.ubuntu.com precise-updates/restricted TranslationIndex [7297 B]
Get:9 http://archive.ubuntu.com precise-updates/universe TranslationIndex [8333 B]
Hit http://archive.ubuntu.com precise/main Sources
Hit http://archive.ubuntu.com precise/restricted Sources
Hit http://archive.ubuntu.com precise/universe Sources
Hit http://archive.ubuntu.com precise/multiverse Sources
Hit http://archive.ubuntu.com precise/main amd64 Packages
Hit http://archive.ubuntu.com precise/restricted amd64 Packages
Hit http://archive.ubuntu.com precise/universe amd64 Packages
Hit http://archive.ubuntu.com precise/multiverse amd64 Packages
Hit http://archive.ubuntu.com precise/main i386 Packages
Ign http://archive.ubuntu.com precise-security/main Sources/DiffIndex
Ign http://archive.ubuntu.com precise-security/restricted Sources/DiffIndex
Ign http://archive.ubuntu.com precise-security/universe Sources/DiffIndex
Ign http://archive.ubuntu.com precise-security/multiverse Sources/DiffIndex
Ign http://archive.ubuntu.com precise-security/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security/multiverse amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security/main i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security/restricted i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security/universe i386 Packages/DiffIndex
Ign http://archive.ubuntu.com precise-security/multiverse i386 Packages/DiffIndex
Get:10 http://archive.ubuntu.com precise-security/main TranslationIndex [208 B]
Get:11 http://archive.ubuntu.com precise-security/multiverse TranslationIndex [199 B]
Get:12 http://archive.ubuntu.com precise-security/restricted TranslationIndex [202 B]
Get:13 http://archive.ubuntu.com precise-security/universe TranslationIndex [205 B]
Hit http://archive.ubuntu.com precise/restricted i386 Packages
Hit http://archive.ubuntu.com precise/universe i386 Packages
Hit http://archive.ubuntu.com precise/multiverse i386 Packages
Hit http://archive.ubuntu.com precise/main Translation-en
Hit http://archive.ubuntu.com precise/multiverse Translation-en
Hit http://archive.ubuntu.com precise/restricted Translation-en
Hit http://archive.ubuntu.com precise/universe Translation-en
Get:14 http://archive.ubuntu.com precise-updates/main Sources [490 kB]
Get:15 http://archive.ubuntu.com precise-updates/restricted Sources [7981 B]                                                                                           
Get:16 http://archive.ubuntu.com precise-updates/universe Sources [120 kB]                                                                                             
Get:17 http://archive.ubuntu.com precise-updates/multiverse Sources [9723 B]                                                                                           
Get:18 http://archive.ubuntu.com precise-updates/main amd64 Packages [902 kB]                                                                                          
Get:19 http://archive.ubuntu.com precise-updates/restricted amd64 Packages [13.6 kB]                                                                                   
Get:20 http://archive.ubuntu.com precise-updates/universe amd64 Packages [266 kB]                                                                                      
Get:21 http://archive.ubuntu.com precise-updates/multiverse amd64 Packages [16.5 kB]                                                                                   
Get:22 http://archive.ubuntu.com precise-updates/main i386 Packages [953 kB]                                                                                           
Get:23 http://archive.ubuntu.com precise-updates/restricted i386 Packages [13.6 kB]                                                                                    
Get:24 http://archive.ubuntu.com precise-updates/universe i386 Packages [276 kB]                                                                                       
Get:25 http://archive.ubuntu.com precise-updates/multiverse i386 Packages [16.7 kB]                                                                                    
Hit http://archive.ubuntu.com precise-updates/main Translation-en                                                                                                      
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en                                                                                                
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en                                                                                                
Hit http://archive.ubuntu.com precise-updates/universe Translation-en                                                                                                  
Get:26 http://archive.ubuntu.com precise-security/main Sources [130 kB]                                                                                                
Get:27 http://archive.ubuntu.com precise-security/restricted Sources [3759 B]                                                                                          
Get:28 http://archive.ubuntu.com precise-security/universe Sources [42.7 kB]                                                                                           
Get:29 http://archive.ubuntu.com precise-security/multiverse Sources [2203 B]                                                                                          
Get:30 http://archive.ubuntu.com precise-security/main amd64 Packages [520 kB]                                                                                         
Get:31 http://archive.ubuntu.com precise-security/restricted amd64 Packages [8943 B]                                                                                   
Get:32 http://archive.ubuntu.com precise-security/universe amd64 Packages [122 kB]                                                                                     
Get:33 http://archive.ubuntu.com precise-security/multiverse amd64 Packages [2693 B]                                                                                   
Get:34 http://archive.ubuntu.com precise-security/main i386 Packages [560 kB]                                                                                          
Get:35 http://archive.ubuntu.com precise-security/restricted i386 Packages [8939 B]                                                                                    
Get:36 http://archive.ubuntu.com precise-security/universe i386 Packages [130 kB]                                                                                      
Get:37 http://archive.ubuntu.com precise-security/multiverse i386 Packages [2874 B]                                                                                    
Hit http://archive.ubuntu.com precise-security/main Translation-en                                                                                                     
Hit http://archive.ubuntu.com precise-security/multiverse Translation-en                                                                                               
Hit http://archive.ubuntu.com precise-security/restricted Translation-en                                                                                               
Hit http://archive.ubuntu.com precise-security/universe Translation-en                                                                                                 
Fetched 4904 kB in 18s (264 kB/s)                                                                                                                                      
Reading package lists... Done
W: GPG error: http://archive.ubuntu.com precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5
W: GPG error: http://archive.ubuntu.com precise-updates Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5
W: GPG error: http://archive.ubuntu.com precise-security Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libcups2 libssl1.0.0 linux-libc-dev openssl
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 2604 kB of archives.
After this operation, 6144 B of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libssl1.0.0 libcups2 openssl linux-libc-dev
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by divx118** [comment]
Something like http://askubuntu.com/questions/235880/how-to-fix-gpg-in-updater should solve your GPG errors. Use `sudo enter-chroot -n precise` to get a command line in your chroot. Then add the key like described in the link. See if it all worked, by running `sudo apt-get update && sudo apt-get upgrade` When that finishes with no errors type `exit` to exit the chroot and try updating your chroot again with `sudo sh ~/Downloads/crouton -n precise -u`
