### ISSUE TITLE
Linux ubuntu: /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1

### ISSUE THREAD

**Issue by SpafinDoople** [dnschneid/crouton#1852]
When I run `sudo startunity` I get the following log:

`Initializing built-in extension Generic Event Extension`
`Initializing built-in extension SHAPE`
`Initializing built-in extension MIT-SHM`
`Initializing built-in extension XInputExtension`
`Initializing built-in extension XTEST`
`Initializing built-in extension BIG-REQUESTS`
`Initializing built-in extension SYNC`
`Initializing built-in extension XKEYBOARD`
`Initializing built-in extension XC-MISC`
`Initializing built-in extension SECURITY`
`Initializing built-in extension XINERAMA`
`Initializing built-in extension XFIXES`
`Initializing built-in extension RENDER`
`Initializing built-in extension RANDR`
`Initializing built-in extension COMPOSITE`
`Initializing built-in extension DAMAGE`
`Initializing built-in extension MIT-SCREEN-SAVER`
`Initializing built-in extension DOUBLE-BUFFER`
`Initializing built-in extension RECORD`
`Initializing built-in extension DPMS`
`Initializing built-in extension X-Resource`
`Initializing built-in extension XVideo`
`Initializing built-in extension XVideo-MotionCompensation`
`Initializing built-in extension XFree86-VidModeExtension`
`Initializing built-in extension XFree86-DGA`
`Initializing built-in extension XFree86-DRI`
`Initializing built-in extension DRI2`
`Loading extension GLX`
`setversion 1.4 failed: Permission denied`
`xf86: found device 0`
`/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1`
`crouton: version 1-20150604154515~master:91b3e350`
`release: precise`
`architecture: amd64`
`xmethod: xiwi`
`targets: xiwi,unity`
`host: version 6946.55.0 (Official Build) stable-channel link `
`kernel: Linux localhost 3.8.11 #1 SMP Tue May 26 18:41:21 PDT 2015 x86_64 x86_64 x86_64 ``GNU/Linux`
`freon: yes`
`Error: not connected.`
`Cannot connect to extension, retrying...`
`Error: not connected.`
`Cannot connect to extension, retrying...`
`Error: not connected.`
`Cannot connect to extension, retrying...`
`Connected to extension, launched crouton in a window.`

The line I'm concerned about is this: `/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1`. I never seen that happen before. Now whenever I load the crouton extension My chroot window is just a grey or black screen. Help! :open_mouth: 

`sudo enter-chroot -n precise croutonversion` returns the following:

`crouton: version 1-20150604154515~master:91b3e350
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,unity
host: version 6946.55.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Tue May 26 18:41:21 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes`

A bit of info: 
I'm using a Chromebook Pixel running v43.0.2357.8.
The error unexpectedly occurred when I restarted Linux.
I'm using Linux Ubuntu 14.04 (I think)

**Comment by SpafinDoople** [comment]
Also a question: Can I revert my chroot to disable xiwi?

**Comment by SpafinDoople** [comment]
Um... Help? I've been waiting for a day.. :stuck_out_tongue:

**Comment by divx118** [comment]
Easiest way is to update your chroot again with target xorg `sudo sh ~/Downloads/crouton -n precise -t xorg -u`

**Comment by SpafinDoople** [comment]
Will that fix my  issue, and disable xiwi, or will it just put my chroot back into X.org?

**Comment by divx118** [comment]
@SpafinDoople If xorg works for you then yes you can use your chroot again. It will not solve your issue with xiwi.

 >Also a question: Can I revert my chroot to disable xiwi?

I was answering this.

**Comment by SpafinDoople** [comment]
Okay, thanks for the help.
