### ISSUE TITLE
Does the target Chrome-dev have a graphical interface?

### ISSUE THREAD

**Issue by Alfriadox** [dnschneid/crouton#1853]
If it does, how do I start it?

**Comment by datruck** [comment]
No, you need to install one of the desktop environment targets.

**Comment by dnschneid** [comment]
Not necessarily.  If you install the xiwi target, you can launch chrome-dev via `sudo startxiwi chrome-browser`.  If you didn't install the xiwi target, you can try `sudo enter-chroot xinit /usr/bin/chrome-browser`, but you won't have a window manager and it may not behave nicely.

**Comment by datruck** [comment]
Wow, great tips David! I stand corrected. Sounds like your xinit suggestion might be a great way to increase available RAM and performance for certain apps or games especially for folks with slower CPUs or 2GB of ram.

**Comment by Alfriadox** [comment]
Thanks.

**Comment by DennisLfromGA** [comment]
I suppose there's something I'm missing here but why would one install crouton in order to start a Chrome-dev browser standalone?
