### ISSUE TITLE
unmount-chroot executable file

### ISSUE THREAD

**Issue by mnager** [dnschneid/crouton#1854]
I believe I have the same problem as Issue 1456. The output is below.

chronos@localhost / $ sudo unmount-chroot trusty
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

chronos@localhost / $ sudo unmount-chroot -p trusty
24815 su - mnager
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

chronos@localhost / $ mount|grep crouton|wc -l 
22

I found the unmount-chroot file(https://github.com/dnschneid/crouton/blob/master/host-bin/unmount-chroot). I believe from 1456 that this will solve my problem. My one question is, pardon my ignorance and inexperience, how would I go about executing the file in the Chrome Developer's Shell?

**Comment by dnschneid** [comment]
Try updating your chroot and rebooting.  If things are still broken, comment on #1456.
