### ISSUE TITLE
Q: How to build the extension for development?

### ISSUE THREAD

**Issue by stsquad** [dnschneid/crouton#1855]
I'm having a look at the various pull requests for fixing the Freon/Keyboard issues. However they require a new build of the extension to test. There don't seem to be any instructions for how to build a development version of the extension. I tried running the gencrx.sh shell script but that fails pretty quick even with the nacl_tools installed.

**Comment by stsquad** [comment]
Of course now I realise it's just:

    make extension

**Comment by dnschneid** [comment]
And now it's documented in the issue tracker.  Thanks! :)
