### ISSUE TITLE
Cant Delete

### ISSUE THREAD

**Issue by Mishiki01** [dnschneid/crouton#1856]
so i decided about a week ago to test it and now i cant delete it. but i dont want to powerwash my device. any suggestion?

**Comment by SpafinDoople** [comment]
If you are trying to delete the chroot, run `sudo delete-chroot chrootname`, where `chrootname` is the name of your chroot. If you don't know what your chrootname is, run `sudo edit-chroot -a` or `ls /usr/local/chroots`.

Hope I helped.

~**SpafinDoople**

**Comment by DennisLfromGA** [comment]
@Mishiki01 - 
Follow @SpafinDoople's suggestions, 
If you still have problems, it's possible that your chroot still has open/running processes so -
Reboot and instead of logging in, just press <kbd>Ctrl+Alt+->/F2</kbd> and follow @SpafinDoople's suggestions one more time.
