### ISSUE TITLE
sudo startunity: Xorg X11 servers cannot be launched from Frecon

### ISSUE THREAD

**Issue by 1MatthewHarris1** [dnschneid/crouton#1857]
Okay, here is the data from when I run sudo enter-chroot -n precise croutonversion:

Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150604154515~master:91b3e350
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 6946.55.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Tue May 26 18:21:47 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I ran crouton for a long time (about 6 month) without any issues, but last night when I tried using sudo startunity I got a server error. I didn't copy down the exact error code because I read online that such server errors are common and simply required the user to update crouton. So I downloaded the latest installer and typed in the following:
sudo sh ~/Downloads/crouton -n precise -u

It took some time to update, but it seemed to do so without any errors. So after it had finished I tried again but then when I typed sudo startunity, I got this: 

Xorg X11 servers cannot be launched from Frecon
Return to Chromium OS and use crosh to launch X
user/bin/xinit: giving up
user/bin/xinit: unable to connect to X server: no such file or directory
user/bin/xinit: server error
unmounting /mnt/stateful_partition/crouton/chroots/precise...

So after trying:
sudo sh ~/Downloads/crouton -n precise -u -t xiwi
Everything installed okay, but when I tried running sudo startunity, I got this:

setversion 1.4 failed: Permission denied
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150604154515~master:91b3e350
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,unity
host: version 6946.55.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Tue May 26 18:21:47 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...

So it's still a server problem I guess, but I'm not terribly familiar with this system, its supporting programs, or how any of it runs. If there is a simple fix, I would appreciate some educational explanation about what is broken and how it works. Of course, I appreciate any and all help and thank you for your time.

**Comment by DennisLfromGA** [comment]
@1MatthewHarris1 - 

> -su: 1: croutonvesion: not found

Don't panic, you didn't spell 'croutonversion' correctly, try again with:

`sudo enter-chroot -n precise croutonversion`

**Comment by DennisLfromGA** [comment]
@1MatthewHarris1 - 

> -su: 1: croutonvesion: not found

It was just a spelling error, for your croutonversion, try:

`sudo enter-chroot -n precise croutonversion`

> Xorg X11 servers cannot be launched from Frecon

You may have to update your chroot using 'xiwi' on your system, do an update again but this time add the 'xiwi' target:

`sudo sh ~/Downloads/crouton -n precise -u -t xiwi`

Once that completes successfully, try `sudo startunity` again, it should work but it'll be using 'xiwi' this time - with no hardware accelaration.

**Comment by dnschneid** [comment]
You don't need xiwi.  What the error message is saying is that you have to use a ctrl-alt-T shell to launch crouton, not ctrl+alt+F2.

**Comment by DennisLfromGA** [comment]
Sorry 'bout that, I just noticed it already had xiwi. I need to pay more attention :)

**Comment by 1MatthewHarris1** [comment]
That's great... But it won't launch crouton from the ctrl-alt-T shell or from ctrl+alt+F2

**Comment by divx118** [comment]
@1MatthewHarris1 Did you try a reboot, then login and open a ctr-alt-T shell?

**Comment by PixelXII** [comment]
@1MatthewHarris1 did you type "shell" into the crosh (ctrl+alt+t) shell before trying to launch crouton?

**Comment by Dae-Hang-Sook** [comment]
> You don't need xiwi.  What the error message is saying is that you have to use a ctrl-alt-T shell to launch crouton, not ctrl+alt+F2.
> 

This is a problem. I can not sudo inside of crosh nor can I set the flags to do so

**Comment by jkoudys** [comment]
I can't use the ctrl-alt-T shell because I cannot sudo from it, and I can't run frecon from the ctrl-alt-rightarrow terminal.

**Comment by DennisLfromGA** [comment]
@jkoudys,

This is an ancient topic that was closed in 2015.
See the below discussion for:

- #5013

-**DennisLfromGA**
