### ISSUE TITLE
Performance decreases with xiwi

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1859]
Now that the default is xiwi, I've noticed performance has gone way down (like 15fps in Minecraft). Can you add a mode so that we can have it the old way? (like a `-x11` option or something when doing `sudo startxfce4`...)

**Comment by hsharrison** [comment]
This already exists. Check `enter-chroot --help` to see the `-X` argument XMETHOD. I'm not sure if it's `sudo enter-chroot -X xorg startxfce4` or `sudo enter-chroot -X x11 startxfce4` but try both. You might have to update the chroot with the xorg/x11 targets, which may have the side effect of setting that XMETHOD to default.

**Comment by SpafinDoople** [comment]
Firestar115:

To switch back to using X.org, run: `sudo sh ~/Downloads/crouton -n chrootname -t xorg -u`. If you don't know what your chrootname is, run `sudo edit-chroot -a` or `ls /usr/local/chroots`.

Hope I helped.

~**SpafinDoople**

**Comment by firestar115** [comment]
Thank you! But why (after my chroot was `xorg`) did it change to xiwi?

**Comment by SpafinDoople** [comment]
You must have installed the crouton extension and updated the chroot with the xiwi target.

**Comment by firestar115** [comment]
I created the chroot with xorg and xiwi. It was xorg for weeks until
BOOM I updated it with only -u and it became xiwi.

On 6/13/15, SpafinDoople <notifications@github.com> wrote:
> You must have installed the crouton extension and updated the chroot with
> the xiwi target.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1859#issuecomment-111719278


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by SpafinDoople** [comment]
Hm... I don't quite know what must have happened... I'm not a crouton expert. I'm not quite sure. :disappointed:
