### ISSUE TITLE
Black screen on startxfce4 after Chrome updated and updating trusty

### ISSUE THREAD

**Issue by wytcld** [dnschneid/crouton#1861]
$ sudo enter-chroot croutonversion
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: i386
xmethod: xorg
targets: xfce
host: version 6946.55.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Tue May 26 16:18:27 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

After Chrome updated itself there was a segfault trying to startxfce4. Did the crouton update (2x) and the result is the screen goes black. Using ctrl-alt-right arrow twice a brief XFCE screen will flash, but just for the briefest moment than black again. This is on an Acer Chromebook. 

(With a similar segfault situation on an Asus, I did things backwards and ran do-release-upgrade until it was up to 15.04 - kept segfaulting of course - and _then_ did the crouton upgrade - which reported that 15.04 wasn't supported, but when finished it worked fine. But was never at a black-screen stage with that one, so probably no lesson from that for this system.)

**Comment by yisheng-on-linux** [comment]
Not sure if this belongs here but it's the closest I could find. Chrome updated on Asus a few days ago. Went back into crouton after reboot and it failed to start with many errors. That's history by now. As has become the norm, I then updated crouton. After that the error changed, but all new and old croutons were useless.

I then took a new drive and did a fresh install, leaving the updated and historical croutons on the old drive for forensic purposes. All day long today, starting the new crouton would give me a commandline, any attempt to start x on the commandline (or via startxfce4 in the shell) got me a "waiting to start x" followed by repeated
..
..
..
ad infinitum.

After several reboots, it now starts in commandline mode and startx gives me a few flashes like there is a video sync problem, then the screen goes blank, keyboard is dead, and I can't even get to power down without holding the power button for a very long time. The symptoms changed, so I assume another chrome os version got installed in the middle of this...

I've worked around various problems before but this one has me dead. 

System info:
Version 43.0.2357.81 (64-bit)
Platform 6946.55.0 (Official Build) stable-channel quawks
Firmware Google_Quawks.5216.204.6

crouton: version 1-20150604154515~master:91b3e350
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,cli-extra,core,extension,gtk-extra,touch,x11,xfce,xfce-desktop,xorg
host: version 6946.55.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Tue May 26 18:02:11 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by yisheng-on-linux** [comment]
Once in a crouton cli, I get this in the crouton log:
(this one is from the updated one, all acting similar now)
using: 
sudo enter-chroot -c /path/to/chroots -n trustyname
then at commandline:
startx

chromebook:~$ startx

ERROR: ld.so: object '/usr/local/lib/croutonfreon.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux chromebook 3.10.18 #1 SMP Tue May 26 18:02:11 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=2576c1c1-f6b0-d446-9ac5-5f8760f61592/PARTNROFF=1 hashtree=PARTUUID=2576c1c1-f6b0-d446-9ac5-5f8760f61592/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b11d145126c8261424685884426c06721cadf260 salt=798a2fe48498c404a404683967eb35e694276e5c76ff58d65cdadd343ede3c79" noinitrd vt.global_cursor_default=0 kern_guid=2576c1c1-f6b0-d446-9ac5-5f8760f61592 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jun 15 18:44:19 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
(trustyprod1)skip@chromebook:~$ cat /tmp/Xorg.crouton.1.log
[   958.657] 
X.Org X Server 1.15.1
Release Date: 2014-04-13
[   958.657] X Protocol Version 11, Revision 0
[   958.657] Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
[   958.657] Current Operating System: Linux chromebook 3.10.18 #1 SMP Tue May 26 18:02:11 PDT 2015 x86_64
[   958.658] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=2576c1c1-f6b0-d446-9ac5-5f8760f61592/PARTNROFF=1 hashtree=PARTUUID=2576c1c1-f6b0-d446-9ac5-5f8760f61592/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b11d145126c8261424685884426c06721cadf260 salt=798a2fe48498c404a404683967eb35e694276e5c76ff58d65cdadd343ede3c79" noinitrd vt.global_cursor_default=0 kern_guid=2576c1c1-f6b0-d446-9ac5-5f8760f61592 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
[   958.659] Build Date: 12 February 2015  02:49:29PM
[   958.659] xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
[   958.659] Current version of pixman: 0.30.2
[   958.659]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[   958.659] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   958.661] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jun 15 18:44:19 2015
[   958.666] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   958.676] (==) No Layout section.  Using the first Screen section.
[   958.676] (==) No screen section available. Using defaults.
[   958.676] (**) |-->Screen "Default Screen Section" (0)
[   958.676] (**) |   |-->Monitor "<default monitor>"
[   958.678] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[   958.679] (==) Automatically adding devices
[   958.679] (==) Automatically enabling devices
[   958.679] (==) Automatically adding GPU devices
[   958.696] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   958.696]    Entry deleted from font path.
[   958.696] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   958.696]    Entry deleted from font path.
[   958.696] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   958.696]    Entry deleted from font path.
[   958.699] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   958.699]    Entry deleted from font path.
[   958.699] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   958.699]    Entry deleted from font path.
[   958.699] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/Type1,
        built-ins
[   958.699] (==) ModulePath set to "/usr/lib/x86_64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[   958.699] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[   958.699] (II) Loader magic: 0x7fecffb42d40
[   958.699] (II) Module ABI versions:
[   958.699]    X.Org ANSI C Emulation: 0.4
[   958.699]    X.Org Video Driver: 15.0
[   958.699]    X.Org XInput driver : 20.0
[   958.699]    X.Org Server Extension : 8.0
[   958.701] (--) PCI:x(0:0:2:0) 8086:0f31:8086:0f31 rev 14, Mem @ 0xd0000000/4194304, 0xc0000000/268435456, I/O @ 0x00001000/8
[   958.703] Initializing built-in extension Generic Event Extension
[   958.703] Initializing built-in extension SHAPE
[   958.703] Initializing built-in extension MIT-SHM
[   958.703] Initializing built-in extension XInputExtension
[   958.703] Initializing built-in extension XTEST
[   958.703] Initializing built-in extension BIG-REQUESTS
[   958.703] Initializing built-in extension SYNC
[   958.703] Initializing built-in extension XKEYBOARD
[   958.704] Initializing built-in extension XC-MISC
[   958.704] Initializing built-in extension SECURITY
[   958.704] Initializing built-in extension XINERAMA
[   958.704] Initializing built-in extension XFIXES
[   958.704] Initializing built-in extension RENDER
[   958.704] Initializing built-in extension RANDR
[   958.704] Initializing built-in extension COMPOSITE
[   958.704] Initializing built-in extension DAMAGE
[   958.705] Initializing built-in extension MIT-SCREEN-SAVER
[   958.705] Initializing built-in extension DOUBLE-BUFFER
[   958.705] Initializing built-in extension RECORD
[   958.705] Initializing built-in extension DPMS
[   958.705] Initializing built-in extension Present
[   958.705] Initializing built-in extension DRI3
[   958.705] Initializing built-in extension X-Resource
[   958.705] Initializing built-in extension XVideo
[   958.706] Initializing built-in extension XVideo-MotionCompensation
[   958.706] Initializing built-in extension SELinux
[   958.706] Initializing built-in extension XFree86-VidModeExtension
[   958.706] Initializing built-in extension XFree86-DGA
[   958.706] Initializing built-in extension XFree86-DRI
[   958.706] Initializing built-in extension DRI2
[   958.706] (II) LoadModule: "glx"
[   958.747] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   958.794] (II) Module glx: vendor="X.Org Foundation"
[   958.794]    compiled for 1.15.1, module version = 1.0.0
[   958.794]    ABI class: X.Org Server Extension, version 8.0
[   958.794] (==) AIGLX enabled
[   958.794] Loading extension GLX
[   958.794] (==) Matched intel as autoconfigured driver 0
[   958.794] (==) Matched modesetting as autoconfigured driver 1
[   958.794] (==) Matched fbdev as autoconfigured driver 2
[   958.794] (==) Matched vesa as autoconfigured driver 3
[   958.794] (==) Assigned the driver to the xf86ConfigLayout
[   958.794] (II) LoadModule: "intel"
[   958.797] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[   958.812] (II) Module intel: vendor="X.Org Foundation"
[   958.812]    compiled for 1.15.1, module version = 2.99.910
[   958.812]    Module class: X.Org Video Driver
[   958.812]    ABI class: X.Org Video Driver, version 15.0
[   958.812] (II) LoadModule: "modesetting"
[   958.813] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   958.817] (II) Module modesetting: vendor="X.Org Foundation"
[   958.817]    compiled for 1.15.0, module version = 0.8.1
[   958.817]    Module class: X.Org Video Driver
[   958.817]    ABI class: X.Org Video Driver, version 15.0
[   958.817] (II) LoadModule: "fbdev"
[   958.817] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[   958.819] (II) Module fbdev: vendor="X.Org Foundation"
[   958.819]    compiled for 1.15.0, module version = 0.4.4
[   958.819]    Module class: X.Org Video Driver
[   958.819]    ABI class: X.Org Video Driver, version 15.0
[   958.819] (II) LoadModule: "vesa"
[   958.820] (II) Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
[   958.823] (II) Module vesa: vendor="X.Org Foundation"
[   958.823]    compiled for 1.15.0, module version = 2.3.3
[   958.823]    Module class: X.Org Video Driver
[   958.823]    ABI class: X.Org Video Driver, version 15.0
[   958.823] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
        i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
        915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
        Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
        GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
[   958.825] (II) intel: Driver for Intel(R) HD Graphics: 2000-6000
[   958.825] (II) intel: Driver for Intel(R) Iris(TM) Graphics: 5100, 6100
[   958.825] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics: 5200, 6200, P6300
[   958.825] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   958.825] (II) FBDEV: driver for framebuffer: fbdev
[   958.825] (II) VESA: driver for VESA chipsets: vesa
[   958.825] (EE) 
Fatal server error:
[   958.825] (EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
[   958.825] (EE) 
[   958.825] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[   958.826] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[   958.826] (EE)

**Comment by DennisLfromGA** [comment]
@wytcld - You could try this fix - https://github.com/dnschneid/crouton/issues/1680#issue-71383695, I think it's worked for some - might be worth a shot.

**Comment by yisheng-on-linux** [comment]
Tried and didn't make a difference. I'm running xfce and it #1680 is gnome. Still dead but thanks. I wonder why there aren't more folks reporting this problem. Seems pretty major, new fresh crouton and all...

**Comment by divx118** [comment]
@yisheng-on-linux You shouldn't use `startx` use `xinit` instead. Also you can just do in a crosh shell `sudo startxfce4`
`startx` has never worked reliable on crouton chroots and is recommended not to use. What is strange is that fbdev driver seems to be  installed. I thought it was removed for devices with freon and modesetting should be used. Need to check that.

**Comment by yisheng-on-linux** [comment]
Sorry if this is intuitively obvious, but I'm beginning to doubt what I know about getting crouton to run. If I have installed in /path/to/crouton and named it my_crouton what cmdline params do I use with startxfce4? Does it take the -c and -n ones?

I ask, since they also fail so far and I'm not sure if it's from the current problem or I'm not doing the cmdline right...

Thanks.

**Comment by yisheng-on-linux** [comment]
Tried xinit inside the cli crouton and get the following:

~$ xinit

ERROR: ld.so: object '/usr/local/lib/croutonfreon.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux chromebook 3.10.18 #1 SMP Tue May 26 18:02:11 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=2576c1c1-f6b0-d446-9ac5-5f8760f61592/PARTNROFF=1 hashtree=PARTUUID=2576c1c1-f6b0-d446-9ac5-5f8760f61592/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b11d145126c8261424685884426c06721cadf260 salt=798a2fe48498c404a404683967eb35e694276e5c76ff58d65cdadd343ede3c79" noinitrd vt.global_cursor_default=0 kern_guid=2576c1c1-f6b0-d446-9ac5-5f8760f61592 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jun 16 23:37:40 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

**Comment by Tuxerito** [comment]
You need to update you chroot after update ChromeOS

sudo enter-chroot -n chrootname
croutonversion -u -d
exit
sudo sh ~/Downloads/crouton -u -n chrootname



If you have multiple Chroots(Trusty, Jessie, Sid, customname etc) and you want to use for example Trusty run
sudo startxfce4 -n trusty

-n param is the name of the chroot

**Comment by wytcld** [comment]
Tuxerito,

Can't speak for the other issues in this thread, but my initial report was about the problem which has appeared after doing exactly what you're suggesting. So: Anyone who hasn't done that should. But there is at least one problem being discussed here which that does not cure. Not even after running it several times.

Whit

**Comment by tomulet** [comment]
Make sure Chrome OS is in Stable channel.
