### ISSUE TITLE
Calabash Android - I'm struggling to fix - undefined method `embed' for "447590087100":String (NoMethodError) 

### ISSUE THREAD

**Issue by americapires1** [dnschneid/crouton#1862]
Hi, my name is America Pires and I'm new to Calabash android.
I have the fallowing on my feature, step definitions and on my EnterNumberScreen class as shown below. This was working before (it would populate the phone number text filed with the number on the feature, however, now i keep getting the error as shown further down below).
I have tried so many things but I'm stuck on this error. 
Any advice would be much appreciated. 

Thank you.

Feature 

 @1.01
  Scenario Outline: Enter valid phone number      
    When I enter <valid_phone_number>   # this is line 9
  Examples:Valid phone numbers
    | valid_phone_number |
    | 07590087100        |

Step Definition 

When(/^I enter (.*)$/) do |valid_phone_number| 
  valid_number = EnterNumberScreen.new(valid_phone_number) 
  valid_number.enter_phone_number(valid_phone_number)       # this is line 8
end

Method on my EnterNumberScreen Class

    def enter_phone_number_field
         "* id:'register_enternumber_edittext'"
       end

  def enter_phone_number(phone_number) 
    wait_for_elements_exist(enter_phone_number_field,timeout:2)      # this is line 36
    keyboard_enter_text(phone_number)
  end

ERROR

Examples: Valid phone numbers
      | valid_phone_number |
      | 447590087100       |
      undefined method `embed' for "447590087100":String (NoMethodError)
      ./features/Classes/enter_number_class.rb:36:in `enter_phone_number'
      ./features/Step_definitions/enter_number_steps.rb:8:in `/^I enter (.*)$/'
      features/Features/enter_number.feature:9:in `When I enter <valid_phone_number>'

**Comment by Hashmael** [comment]
I think you might be in the wrong git.
https://github.com/calabash/calabash-android

**Comment by tonyxue** [comment]
@americapires1 Are you running the thing inside a chroot created by crouton on Chrome OS? Do you think there is anything related to Crouton?

**Comment by americapires1** [comment]
Hi Tonyxue, 

Thank you.
No. I don't think Im running this inside a chroot created by crouton on Chrome OS. I just downloaded calabash feature folder from the Github to my mac and used my own project APK file that I stored on platform tools folder that is inside a android-skd-macosx folder.

**Comment by tonyxue** [comment]
@americapires1 So here's not the right place for the question. As @Hashmael suggested, you can ask it at https://github.com/calabash/calabash-android

**Comment by americapires1** [comment]
Ok. Thank you.
