### ISSUE TITLE
Can't update stretch chroot "release does not match"

### ISSUE THREAD

**Issue by dragonloverlord** [dnschneid/crouton#1863]
I can't update my debian stretch chroot as crouton will not recognize my chroots release and specifying -uu on crouton results in a five second wait followed by nothing.

"edit-chroot -l" gives me this:

name: stretch
encrypted: no
Entering /media/removable/chroots/stretch...
crouton: version 1-20150519153807~master:30cf02c9
release: stretch
architecture: armhf
xmethod: xiwi
targets: xfce,gtk-extra,xiwi,extension,x11,xorg,audio,core
host: version 7077.34.0 (Official Build) beta-channel daisy_freon 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jun 10 21:40:30 PDT 2015 armv7l GNU/Linux
freon: yes
Unmounting /media/removable/chroots/stretch...

My update script looks like this but it fails:

sudo sh /home/chronos/user/Downloads/crouton -p /media/removable/ -r stretch -n stretch -u

I am using crouton version:

crouton: version 1-20150604154515~master:91b3e350

My chroot does launch and work fine in xiwi but I would like to update it so any help would be appreciated.

**Comment by SpafinDoople** [comment]
dragonloverlord:

Try force updating the chroot with `sudo sh /home/chronos/user/Downloads/crouton -p /media/removable/ -r stretch -n stretch -u -u`

**Comment by dragonloverlord** [comment]
As I have stated forcing the chroot to update does nothing but wait five seconds then put me back at the command line.

**Comment by dnschneid** [comment]
What does your /etc/apt/sources.list look like?

**Comment by dragonloverlord** [comment]
@dnschneid this is what it looks like:

# deb http://ftp.debian.org/debian/ stretch main non-free contrib
deb http://http.us.debian.org/debian stretch-updates main non-free contrib
# deb-src http://http.us.debian.org/debian stretch-updates main non-free contrib
deb http://http.us.debian.org/debian/ stretch main non-free contrib
# deb-src http://http.us.debian.org/debian/ stretch main non-free contrib
deb http://security.debian.org/ stretch/updates main non-free contrib
# deb-src http://security.debian.org/ stretch/updates main non-free contrib
# deb-src http://ftp.debian.org/debian/ stretch main non-free contrib

**Comment by dragonloverlord** [comment]
I fixed the issue by myself as I had some how managed to commend out the first line of my sources.list which when I uncommented it everything now works as intended! Thanks everyone for the help :)
