### ISSUE TITLE
crouton installation script failed installing x64 gnome-desktop: Unable to locate package xbindkeys and xautomation

### ISSUE THREAD

**Issue by kngharv** [dnschneid/crouton#1865]
Toward close to the end of installation, the installation script yield the following error message:

E: Unable to locate package xbindkeys
E: Unable to locate package xautomation
Failed to complete chroot setup

I am on a Dell Chromebook 11 i3 version.   

Please spoonfeed me on how to file bugs properly.  thanks in advance

**Comment by dnschneid** [comment]
Could you post the command you used to install crouton?

**Comment by bharath1097** [comment]
The same issue happened with me. This is the command i used
sudo sh crouton -r trusty -t cli-extra,extension,xorg,xiwi,lxde,audio -p /media/removable/SD\ Card/
