### ISSUE TITLE
support mouse outside of xiwi window?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#1866]
I run the atom editor in a xiwi window.  Atom is actually running in a chrome browser so this request also applies to browsers in general.

When a mouse goes outside of a browser window in a desktop, then browser somehow still tracks the mouse.  This means javascript code can tell the mouse has left the window.  This is important when the code is waiting for a mouseleave or mouseout event on a div next to the edge of the window.  Right now when the mouse leaves the xiwi window things stay popped open in the page which is a problem.  I'm don't know for sure this description is accurate but those are the symptoms.

I assume the mouse position stays at zero or max value when it leaves the xiwi window.  Could it be possible to give a value of -1 to the mouse position in the xwindow when this happens?  That would fix the problem.

**Comment by dnschneid** [comment]
I wonder if it's possible to explicitly send a LeaveNotify event to the window under the mouse?
