### ISSUE TITLE
Kali Linux not downloading

### ISSUE THREAD

**Issue by movieboy711** [dnschneid/crouton#1868]
So I followed the instructions for trying to install Kali Linux and unfortunately I only get this:

Installing kali-amd64 chroot to /usr/local/chroots/kali
Downloading latest debootstrap...
2015-06-15 19:24:29 URL:http://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [61841] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/stable/Release
W: http://http.kali.org/dists/stable/Release was corrupt
E: Failed getting release file http://http.kali.org/dists/stable/Release

**Comment by tf7534** [comment]
I have the same problem bro i thinks it because the download link for kali got changed. If you open http.kali.org/dists/ there is no stable "option" the link in crouton needs to be changed to to http.kali.org/dists/kali i think

**Comment by tonyxue** [comment]
Seems like the directory structure of http.kali.org has changed.

I've submitted a pull request to fix this. See #1870

**Comment by dnschneid** [comment]
Should be fixed now.

**Comment by Xxhackingxx** [comment]
i am having the same issue but it says 

Downloading latest crouton installer...
######################################################################## 100.0%
Installing kali-amd64 chroot to /usr/local/chroots/kali
Downloading latest debootstrap...
2015-11-01 17:41:37 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [62231] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
I: Retrieving Release 
W: Retrying failed download of http://http.kali.org/dists/kali/Release
W: http://http.kali.org/dists/kali/Release was corrupt
E: Failed getting release file http://http.kali.org/dists/kali/Release

and i am a noob so it to be simple

**Comment by DennisLfromGA** [comment]
@tonyxue,
> Seems like the directory structure of http.kali.org has changed.

It seems to have changed again...  https://github.com/dnschneid/crouton/issues/2220

**Comment by tonyxue** [comment]
@DennisLfromGA 
Yes it did. I really have no idea why they change that.

**Comment by divx118** [comment]
kali-current is sana at the moment, it is the current stable release see for more info http://docs.kali.org/general-use/kali-linux-sources-list-repositories It doesn't seem they have old releases in there, but maybe I overlooked something.

**Comment by tonyxue** [comment]
@divx118 
So in that case we wouldn't need ```kali``` & ```sana``` anymore. We only need ```sana``` now.

**Comment by luisschubert** [comment]
I just tried downloading it and I'm getting the same error again.

**Comment by suzainkhan** [comment]
jus visit here once
for knowing everything abt kali linux
www.junaidmugloo.blogspot.com
