### ISSUE TITLE
Error when execute sudo /etc/rc.local 

### ISSUE THREAD

**Issue by cvalentefilho** [dnschneid/crouton#1869]
Hi guys,

I long time a have trying install virtual box in crouton.

but don't have sucess.

Every time   sudo /etc/init.d/vboxdrv setup, return failed.

Now when a try execute the comand  sudo /etc/rc.local

 Return this /etc/rc.local: 1: /etc/rc.local: Syntax error: Unterminated quoted string

Someone can help me.

My chromebook is Asus C300.

Tks guys.

**Comment by Tuxerito** [comment]
Open the /etc/rc.local file and check line number 1(Discard comments #) and look for an unclosed quote.

Put here the content of that file.
