### ISSUE TITLE
Error updating crouton target

### ISSUE THREAD

**Issue by Ali3n0id** [dnschneid/crouton#1871]
Hi all,

Got an issue trying to update my trusty install:

>sudo sh ~/Downloads/crouton -u -n trusty

/usr/local/chroots/trusty already exists; updating it...
Enter encryption passphrase for trusty: 
WARNING: USB booting is enabled; consider disabling it.
WARNING: Legacy booting is enabled; consider disabling it.
WARNING: Signed boot verification is disabled; consider enabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_legacy=0 dev_boot_signed_only=1
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startcli into the host...
Installing croutonpowerd into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxbmc into the host...
Installing xbmc-keyboard.xml into the chroot...
Installing xbmc-cycle.py into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Unknown username "whoopsie" in message bus configuration file
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://ppa.launchpad.net trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease                             
Ign http://ppa.launchpad.net trusty InRelease                              
Get:1 http://archive.ubuntu.com trusty Release.gpg [933 B]                 
Ign http://ppa.launchpad.net trusty InRelease                                  
Ign http://security.ubuntu.com trusty-security InRelease             
Hit http://archive.ubuntu.com trusty Release                         
Ign http://ppa.launchpad.net trusty InRelease                         
Ign http://ppa.launchpad.net trusty InRelease                         
Ign http://ppa.launchpad.net trusty InRelease   
Ign http://archive.ubuntu.com trusty Release                          
Get:2 http://security.ubuntu.com trusty-security Release.gpg [933 B]  
Hit http://ppa.launchpad.net trusty Release.gpg                       
Ign http://archive.ubuntu.com trusty/main amd64 Packages/DiffIndex   
Get:3 http://ppa.launchpad.net trusty Release.gpg [836 B]            
Get:4 http://security.ubuntu.com trusty-security Release [63.5 kB]          
Ign http://archive.ubuntu.com trusty/universe amd64 Packages/DiffIndex   
Hit http://ppa.launchpad.net trusty Release.gpg                          
Ign http://archive.ubuntu.com trusty/main i386 Packages/DiffIndex              
Hit http://ppa.launchpad.net trusty Release.gpg                                
Ign http://archive.ubuntu.com trusty/universe i386 Packages/DiffIndex          
Hit http://ppa.launchpad.net trusty Release.gpg          
Hit http://archive.ubuntu.com trusty/main Translation-en                       
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://archive.ubuntu.com trusty/universe Translation-en                   
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://archive.ubuntu.com trusty/main amd64 Packages                       
Ign http://security.ubuntu.com trusty-security Release                   
Hit http://archive.ubuntu.com trusty/universe amd64 Packages             
Ign https://private-ppa.launchpad.net trusty InRelease                   
Hit http://ppa.launchpad.net trusty Release                              
Hit http://archive.ubuntu.com trusty/main i386 Packages                        
Hit http://ppa.launchpad.net trusty Release                                    
Ign http://ppa.launchpad.net trusty Release                                    
Ign http://security.ubuntu.com trusty-security/main amd64 Packages/DiffIndex   
Ign https://private-ppa.launchpad.net trusty Release.gpg                       
Hit http://archive.ubuntu.com trusty/universe i386 Packages                    
Hit http://ppa.launchpad.net trusty Release                              
Ign http://security.ubuntu.com trusty-security/universe amd64 Packages/DiffIndex
Hit http://ppa.launchpad.net trusty Release                              
Ign https://private-ppa.launchpad.net trusty Release                           
Hit http://ppa.launchpad.net trusty Release                                    
Ign http://security.ubuntu.com trusty-security/main i386 Packages/DiffIndex    
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Ign http://security.ubuntu.com trusty-security/universe i386 Packages/DiffIndex
Hit http://ppa.launchpad.net trusty/main i386 Packages                   
Hit http://ppa.launchpad.net trusty/main Translation-en                  
Get:5 http://security.ubuntu.com trusty-security/main Translation-en [156 kB]
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Get:6 http://security.ubuntu.com trusty-security/universe Translation-en [61.1 kB]
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Get:7 http://security.ubuntu.com trusty-security/main amd64 Packages [299 kB]  
Hit http://ppa.launchpad.net trusty/main amd64 Packages                   
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://ppa.launchpad.net trusty/main amd64 Packages                     
Hit http://ppa.launchpad.net trusty/main i386 Packages                      
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://ppa.launchpad.net trusty/main amd64 Packages                      
Get:8 http://security.ubuntu.com trusty-security/universe amd64 Packages [108 kB]
Get:9 http://security.ubuntu.com trusty-security/main i386 Packages [285 kB]   
Get:10 http://ppa.launchpad.net trusty/main amd64 Packages [12.2 kB]           
Err https://private-ppa.launchpad.net trusty/main amd64 Packages               
  HttpError401
Get:11 http://ppa.launchpad.net trusty/main i386 Packages [12.2 kB] 
Err https://private-ppa.launchpad.net trusty/main i386 Packages                
  HttpError401
Get:12 http://ppa.launchpad.net trusty/main i386 Packages [38.2 kB]            
Get:13 http://security.ubuntu.com trusty-security/universe i386 Packages [108 kB]
Ign https://private-ppa.launchpad.net trusty/main Translation-en               
Get:14 http://ppa.launchpad.net trusty/main Translation-en [19.2 kB]           
Fetched 1166 kB in 11s (102 kB/s)                                              
W: GPG error: http://archive.ubuntu.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
W: GPG error: http://security.ubuntu.com trusty-security Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FE56EB12FA2AF90A
W: Failed to fetch https://private-ppa.launchpad.net/commercial-ppa-uploaders/plexmediaserver/ubuntu/dists/trusty/main/binary-amd64/Packages  HttpError401

W: Failed to fetch https://private-ppa.launchpad.net/commercial-ppa-uploaders/plexmediaserver/ubuntu/dists/trusty/main/binary-i386/Packages  HttpError401

E: Some index files failed to download. They have been ignored, or old ones used instead.
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package libedata-cal-1.2-23 needs to be reinstalled, but I can't find an archive for it.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

Any ideas? I think my sources.list is broken...

**Comment by DennisLfromGA** [comment]
It looks like the errors stem from your PPAs and NO_PUBKEYs.
You may have to remove the PPAs or fix the NO_PUBKEY issues.
Here's a link with some info. about [HOWTO: Fix GPG errors for bad/deleted keys](http://ubuntuforums.org/showthread.php?t=1221323).
