### ISSUE TITLE
Can't start KDE (Toshiba Chromebook 2)

### ISSUE THREAD

**Issue by mfvaughan** [dnschneid/crouton#1872]
Everything was running fine in KDE on my Chromebook, until it randomly would not let me enter KDE after logging out recently. I have no idea what could have caused this to happen, and I also kept running into the "Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it." My issue is similar to #1051. Please help. Thanks.

Upon fresh restart and entering the Chromebook shell, I input sudo startkde and get the following:

chronos@localhost / $ sudo startkde
Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cea1402c-c324-4f4f-b5f1-35e5bea81837/PARTNROFF=1 hashtree=PARTUUID=cea1402c-c324-4f4f-b5f1-35e5bea81837/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=e8d5eb56c862e952264ec4717e8398a1d7fa7aa9 salt=6c257451ffdb07295f3b1da1552915a8a174bdda04ee7f1063cb2b62a58da169" noinitrd vt.global_cursor_default=0 kern_guid=cea1402c-c324-4f4f-b5f1-35e5bea81837 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jun 16 14:42:43 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

The log file that it stores in "/tmp/Xorg.crouton.1.log" is the following:

chronos@localhost / $ sudo enter-chroot -n precise cat /tmp/Xorg.crouton.1.log
Entering /mnt/stateful_partition/crouton/chroots/precise...
[   171.905] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[   171.908] 
X.Org X Server 1.11.3
Release Date: 2011-12-16
[   171.908] X Protocol Version 11, Revision 0
[   171.908] Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
[   171.908] Current Operating System: Linux localhost 3.10.18 #1 SMP Tue May 26 18:03:35 PDT 2015 x86_64
[   171.908] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cea1402c-c324-4f4f-b5f1-35e5bea81837/PARTNROFF=1 hashtree=PARTUUID=cea1402c-c324-4f4f-b5f1-35e5bea81837/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=e8d5eb56c862e952264ec4717e8398a1d7fa7aa9 salt=6c257451ffdb07295f3b1da1552915a8a174bdda04ee7f1063cb2b62a58da169" noinitrd vt.global_cursor_default=0 kern_guid=cea1402c-c324-4f4f-b5f1-35e5bea81837 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
[   171.908] Build Date: 12 February 2015  02:49:01PM
[   171.909] xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
[   171.909] Current version of pixman: 0.30.2
[   171.909]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[   171.910] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   171.911] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jun 16 14:42:43 2015
[   171.912] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   171.912] (==) No Layout section.  Using the first Screen section.
[   171.912] (==) No screen section available. Using defaults.
[   171.912] (**) |-->Screen "Default Screen Section" (0)
[   171.912] (**) |   |-->Monitor "<default monitor>"
[   171.912] (==) No device specified for screen "Default Screen Section".
        Using the first device section listed.
[   171.912] (**) |   |-->Device "Intel Graphics SNA+TearFree"
[   171.912] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[   171.912] (==) Automatically adding devices
[   171.912] (==) Automatically enabling devices
[   171.913] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   171.913]    Entry deleted from font path.
[   171.913] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   171.913]    Entry deleted from font path.
[   171.913] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   171.913]    Entry deleted from font path.
[   171.913] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   171.913]    Entry deleted from font path.
[   171.913] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   171.913]    Entry deleted from font path.
[   171.913] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[   171.913]    Entry deleted from font path.
[   171.913] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/Type1,
        built-ins
[   171.913] (==) ModulePath set to "/usr/lib/x86_64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[   171.913] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[   171.913] (II) Loader magic: 0x7f355847cb00
[   171.913] (II) Module ABI versions:
[   171.913]    X.Org ANSI C Emulation: 0.4
[   171.913]    X.Org Video Driver: 11.0
[   171.913]    X.Org XInput driver : 16.0
[   171.913]    X.Org Server Extension : 6.0
[   171.913] (--) PCI:*(0:0:2:0) 8086:0f31:8086:0f31 rev 14, Mem @ 0xd0000000/4194304, 0xc0000000/268435456, I/O @ 0x00001000/8
[   171.913] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
[   171.913] (II) LoadModule: "extmod"
[   171.914] (II) Loading /usr/lib/xorg/modules/extensions/libextmod.so
[   171.914] (II) Module extmod: vendor="X.Org Foundation"
[   171.914]    compiled for 1.11.3, module version = 1.0.0
[   171.914]    Module class: X.Org Server Extension
[   171.914]    ABI class: X.Org Server Extension, version 6.0
[   171.914] (II) Loading extension MIT-SCREEN-SAVER
[   171.914] (II) Loading extension XFree86-VidModeExtension
[   171.914] (II) Loading extension XFree86-DGA
[   171.914] (II) Loading extension DPMS
[   171.914] (II) Loading extension XVideo
[   171.914] (II) Loading extension XVideo-MotionCompensation
[   171.914] (II) Loading extension X-Resource
[   171.914] (II) LoadModule: "dbe"
[   171.915] (II) Loading /usr/lib/xorg/modules/extensions/libdbe.so
[   171.915] (II) Module dbe: vendor="X.Org Foundation"
[   171.915]    compiled for 1.11.3, module version = 1.0.0
[   171.915]    Module class: X.Org Server Extension
[   171.915]    ABI class: X.Org Server Extension, version 6.0
[   171.915] (II) Loading extension DOUBLE-BUFFER
[   171.915] (II) LoadModule: "glx"
[   171.915] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   171.915] (II) Module glx: vendor="X.Org Foundation"
[   171.915]    compiled for 1.11.3, module version = 1.0.0
[   171.915]    ABI class: X.Org Server Extension, version 6.0
[   171.915] (==) AIGLX enabled
[   171.915] (II) Loading extension GLX
[   171.915] (II) LoadModule: "record"
[   171.916] (II) Loading /usr/lib/xorg/modules/extensions/librecord.so
[   171.916] (II) Module record: vendor="X.Org Foundation"
[   171.916]    compiled for 1.11.3, module version = 1.13.0
[   171.916]    Module class: X.Org Server Extension
[   171.916]    ABI class: X.Org Server Extension, version 6.0
[   171.916] (II) Loading extension RECORD
[   171.916] (II) LoadModule: "dri"
[   171.916] (II) Loading /usr/lib/xorg/modules/extensions/libdri.so
[   171.916] (II) Module dri: vendor="X.Org Foundation"
[   171.916]    compiled for 1.11.3, module version = 1.0.0
[   171.916]    ABI class: X.Org Server Extension, version 6.0
[   171.916] (II) Loading extension XFree86-DRI
[   171.916] (II) LoadModule: "dri2"
[   171.917] (II) Loading /usr/lib/xorg/modules/extensions/libdri2.so
[   171.917] (II) Module dri2: vendor="X.Org Foundation"
[   171.917]    compiled for 1.11.3, module version = 1.2.0
[   171.917]    ABI class: X.Org Server Extension, version 6.0
[   171.917] (II) Loading extension DRI2
[   171.917] (II) LoadModule: "intel"
[   171.917] (WW) Warning, couldn't open module intel
[   171.917] (II) UnloadModule: "intel"
[   171.917] (II) Unloading intel
[   171.917] (EE) Failed to load module "intel" (module does not exist, 0)
[   171.917] (==) Matched intel as autoconfigured driver 0
[   171.917] (==) Matched vesa as autoconfigured driver 1
[   171.917] (==) Matched fbdev as autoconfigured driver 2
[   171.917] (==) Assigned the driver to the xf86ConfigLayout
[   171.917] (II) LoadModule: "intel"
[   171.918] (WW) Warning, couldn't open module intel
[   171.918] (II) UnloadModule: "intel"
[   171.918] (II) Unloading intel
[   171.918] (EE) Failed to load module "intel" (module does not exist, 0)
[   171.918] (II) LoadModule: "vesa"
[   171.918] (WW) Warning, couldn't open module vesa
[   171.918] (II) UnloadModule: "vesa"
[   171.918] (II) Unloading vesa
[   171.918] (EE) Failed to load module "vesa" (module does not exist, 0)
[   171.918] (II) LoadModule: "fbdev"
[   171.919] (WW) Warning, couldn't open module fbdev
[   171.919] (II) UnloadModule: "fbdev"
[   171.919] (II) Unloading fbdev
[   171.919] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   171.919] (EE) No drivers available.
[   171.919] 
Fatal server error:
[   171.919] no screens found
[   171.920] 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[   171.920] Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[   171.920] 
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by divx118** [comment]
You should update your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting for a howto.

**Comment by mfvaughan** [comment]
I have followed that guide multiple times with no luck - the update stops in the middle and I end up with the following:

chronos@localhost / $ sudo sh ~/Downloads/crouton -n precise -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startkde into the host...
Installing crouton-noroot into the chroot...
Installing startkde into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Setting up gpm (1.20.4-4) ...
open: No such file or directory
ioctl: Bad file descriptor
runlevel:/var/run/utmp: No such file or directory
 * Stopping mouse interface server gpm                                                                                                                                                                [ OK ] 
 * Starting mouse interface server gpm                                                                                                                                                                       /etc/init.d/gpm: 66: /etc/init.d/gpm: cannot open /dev/psaux: No such file
invoke-rc.d: initscript gpm, action "restart" failed.
dpkg: error processing gpm (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 gpm
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by divx118** [comment]
Well you could try `sudo enter-chroot -n precise` then in your chroot shell `sudo apt-get update && sudo apt-get upgrade` If that finishes without errors try updating your chroot again. If `sudo apt-get update && sudo apt-get upgrade` gives an error you need to resolve that first.

**Comment by mfvaughan** [comment]
After entering precise and running sudo apt-get update && sudo apt-get upgrade, I still hit an error, which seems to lie with "gpm". Here is what I get for the error:

Setting up gpm (1.20.4-4) ...
open: No such file or directory
ioctl: Bad file descriptor
runlevel:/var/run/utmp: No such file or directory
 * Stopping mouse interface server gpm                                                                                                                                                                [ OK ] 
 * Starting mouse interface server gpm                                                                                                                                                                       /etc/init.d/gpm: 66: /etc/init.d/gpm: cannot open /dev/psaux: No such file
invoke-rc.d: initscript gpm, action "restart" failed.
dpkg: error processing gpm (--configure):
 subprocess installed post-installation script returned error exit status 2
Setting up google-chrome-stable (43.0.2357.125-1) ...
Setting up openssl (1.0.1-4ubuntu5.31) ...
Setting up fonts-opensymbol (2:102.6+LibO4.4.4~rc2-0ubuntu1~precise1) ...
Setting up libreoffice-java-common (1:4.4.4~rc2-0ubuntu1~precise1) ...
Setting up libreoffice-style-human (1:4.4.4~rc2-0ubuntu1~precise1) ...
Setting up linux-libc-dev (3.2.0-86.123) ...
Setting up aptdaemon-data (0.43+bzr805-0ubuntu10) ...
Setting up python-aptdaemon (0.43+bzr805-0ubuntu10) ...
Setting up python-aptdaemon.gtk3widgets (0.43+bzr805-0ubuntu10) ...
Setting up aptdaemon (0.43+bzr805-0ubuntu10) ...
Errors were encountered while processing:
 gpm
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by divx118** [comment]
Why do you have gpm installed? If you don't know, then `sudo apt-get remove gpm` and then `sudo apt-get update && sudo apt-get upgrade` see if it now finishes without errors.

**Comment by mfvaughan** [comment]
Thanks @divx118 !! Removing gpm and following the same steps got me back into KDE. Thanks again for the help!!
