### ISSUE TITLE
chromeOS does not handle the URL links 

### ISSUE THREAD

**Issue by victorel-petrovich** [dnschneid/crouton#1873]
```
crouton: version 1-20150604154515~master:91b3e350
release: jessie
architecture: armhf
xmethod: xiwi
targets: extension,xiwi,core,audio,xephyr,x11,gtk-extra,lxde
host: version 6946.55.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue May 26 16:14:24 PDT 2015 armv7l GNU/Linux
freon: no
```
I have uninstalled the default netsurf browser in debian, and I have set in `preferences/ Default applications for LXSession` , chrome as webbrowser (I have simply clicked on the `more` button at the right, then in the `Manual Setting` text field I have written: "chrome").    
When I open a pdf with URLs in debian and click, the chromeOS browser does not open it, while the pdf application (evince viewer) tells me "Unable to open external link. No application is registered as handling this file."  The URLs are valid, tested with netsurf before removing it.  
I have also updated then the chroot with target `extension`, and still no help (I guess as expected).

When I run `croutonurlhandler https://www.google.com` in a terminal there in debian, chromeOS's browser opens it. But, by the way, once open, the chrome page is frozen completlely (even the clock stops running): the only way I found to "de-frost" it is to `ctrl-alt-shift-forward` once.

When I am in Synaptic, and click on a package, in the text with info in the lower half of the window, there is  `Visit Homepage` button / link: when click on it, it opens with chromeOS's browser, no matter whether in `Default applications for LXSession` it is set or not as default browser. 
And again, once it opens the URL, the chrome page is frozen completlely and I have to `ctrl-alt-shift-forward`.

In rest, the crouton integration extension seems to do what's supposed to (copy-paste, open in window..)

Am I missing something? How to make common chrome default browser? I am new to linux.

**Comment by dnschneid** [comment]
"chrome" is not valid.  Use `croutonurlhandler` in that text field.

Chrome frozen is probably #1475.

**Comment by victorel-petrovich** [comment]
@dnschneid  
Thanks for help!   
But who would know that it should be `croutonurlhandler , it does not say this at https://github.com/dnschneid/crouton/blob/master/README.md , and I did not find it in the wiki either
