### ISSUE TITLE
Playing game "Dustforce" in Xorg environment causes a crash, turns off display.  

### ISSUE THREAD

**Issue by JordanField** [dnschneid/crouton#1874]
I know this is a bit of an edge case but I was wondering if someone with a bit more knowledge of the underlying systems of Crouton could help me with this.

`croutonversion` output:

    Entering /mnt/stateful_partition/crouton/chroots/trusty...
    crouton: version 1-20150604154515~master:91b3e350
    release: trusty
    architecture: amd64
    xmethod: xorg
    targets: xorg,xiwi,xfce
    host: version 6812.88.0 (Official Build) stable-channel squawks 
    kernel: Linux localhost 3.10.18 #1 SMP Fri May 8 14:24:14 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
    freon: no
    Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

In a nutshell, My ASUS Chromebook will boot into XFCE4 fine and dandy, however loading the "Dustforce" game from steam will cause the game to boot up fine, then crash the entire system after about 20 seconds. While the game is playing there is a smooth framerate, but the audio will cut out and the display will switch off entirely. I know that the computer is still running, because I can switch back into ChromeOS and lock the computer, then unlock it using Smart Lock and my phone vibrates and tells me the Chromebook has been unlocked.

What would help me is if there were logs of the command line kept somewhere while I am in the XFCE enviroment, as I'm not able to look at them while the computers screen is off. Does anyone know where they might be kept?

**Comment by drinkcat** [comment]
Possibly a Chrome OS bug... If this still happens, please reopen.
