### ISSUE TITLE
Setting Up a Development Server / Local Dev Environment

### ISSUE THREAD

**Issue by JessBoctor** [dnschneid/crouton#1875]
Hey Everyone, 

Just looking for a little guidance here. I'm a new developer, so I don't have any particular favorite programs or items I have to have. That being said, I am trying to set up a local developer environment in Ubuntu so that I can build WordPress sites, which until now I have been doing via sub-domains and ftp and is becoming cumbersome. 

Does anyone have any tips on which programs are best, how to get started (especially with setting up an Apache server locally) or know of any really great tutorials to recommend? I love crouton and using my Toshiba Chromebook 2, but piece milling the information together myself is just taking a little too long at this point. A few signposts on where to go would be a great help.

Thanks so much for your help! It is greatly appreciated.

**Comment by mark-hahn** [comment]
Since this is a general question for wordpress/linux, you should google for
somewhere else on this question.  I'm sure you'll get a zillion results.

**Comment by Tuxerito** [comment]
You can install all common software for development from repositories (Apache, PHP, MySQL, FTP, Wordpress etc)

If you have a problem installing or configuring that software you can ask here if the problem is related with Crouton but normally on Google you can find answers for mostly problems.

**Comment by tedm** [comment]
@JessBoctor The crouton specific things you will need to setup are in the wiki, specifically startup services up in /etc/rc.local, and opening up ports with iptables.

That said, there is a great book out there with step by step instructions and pictures. But it might be considered shameless self promotion, so you'll have to search a bit ... also look for wamp, xampp, and lamp stacks on crouton in your searches.
