### ISSUE TITLE
fullscreen inconsistency...

### ISSUE THREAD

**Issue by tuberwassaly** [dnschneid/crouton#1876]
Running unity-desktop, xiwi, and trusty.
Crouton extension installed.
Using sudo startunity to launch.
Here is the issue: 
Sometimes using the fullscreen button in crouton allows an 'immersive' fullscreen window in which the chromeOS taskbar and 'menu' bar can still be accessed by mouseover. Sometimes the button triggers a complete fullscreen without such access. Why the discrepancy? Is there a possibility of controlling the fullscreen mode? Is this really more of a chrome problem?

**Comment by firestar115** [comment]
Pressing F4 should get you out of fullscreen if that's what you are looking for. If you want a "fullscreen fullscreen" then update your chroot like so: `sudo sh ~/Downloads/crouton -u -t xorg -n trusty`.

**Comment by tuberwassaly** [comment]
Maybe I didn't explain this well. I am not talking about reverting to a xorg boot, and I am not stuck in fullscreen. When the X11 window which is porting my Linux desktop environment to my chromeOS desktop environment is full-screened, one of two things happens: 

 -The full X11 screen is accompanied by mouse-over access to the chromeOS taskbar.

 -The full X11 screen stands alone, and access to chromeOS is restriced to F4 or ctrl+alt+forward.

It is unclear to me as to what causes one or the other result.

**Comment by JoshMcCullough** [comment]
I agree with this, similar issues here. Also sometimes Unity is launched in full screen mode but doesn't show up, I just get a black screen and Chrome's "you are in full screen mode" warning/message.
