### ISSUE TITLE
Creating a swap partition

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1878]
I don't have a 100% idea on what a swap does, but I know it speeds up your computer. I was trying to speed up my chroot by doing a swap partition (I also used the `mdk` script from #1336) but here's what I get:
```
(trusty)firestar115@localhost:~$ sudo swapon -v -f /swapfile 
[sudo] password for firestar115: 
swapon on /swapfile
swapon: /swapfile: found swap signature: version 1, page-size 4, same byte order
swapon: /swapfile: pagesize=4096, swapsize=2147483648, devsize=2147483648
swapon: /swapfile: swapon failed: Invalid argument
```
In chrome I have done this:
```
crosh> swap on
```
so I think it is already using that swapfile. What do I do to make that swapfile to work?

**Comment by dnschneid** [comment]
See http://www.omgchrome.com/how-to-add-swap-memory-to-your-chromebook/

**Comment by firestar115** [comment]
I have already done `swap enable` but I was looking for a way to get a swap on my chroot. I think it will really help performance-wise.
Off-Topic: Can I have 2 (n)GB swaps and swap between them as if I had (n)GB where n > 2?

**Comment by dnschneid** [comment]
Swap in Chromium OS applies to the chroot as well.  You can have multiple swap partitions, but you're generally wasting your time.  It won't give you the magical performance improvement you somehow think it does.
