### ISSUE TITLE
"WARNING: Outdated server version (VF2), expecting VF3. Please update your chroot."

### ISSUE THREAD

**Issue by brownieboy** [dnschneid/crouton#1879]
Running Ubuntu Trusty with XFCE on my Samsung ARM Chromebook.

Since updating to the latest ChromeOS version, I get the warning "WARNING: Outdated server version (VF2), expecting VF3. Please update your chroot." every time I start my Ubuntu Crouton.

What does it mean and what do I need to do to update my chroot?

Chrome version is:
Version 43.0.2357.125
Platform 6946.58.0 (Official Build) stable-channel daisy

**Comment by morphyhsieh** [comment]
I got the same issue on Pixel after I update it to DEV channel Chrome as follow:

Version 45.0.2431.0 dev (64-bit)
Platform 7173.2.0 (Official Build) dev-channel samus
Firmware Google_Samus.6300.128.0

**Comment by tonyxue** [comment]
Fetch a new ```crouton``` installer, run ```sudo sh ~/Downloads/crouton -u``` to upgrade your chroot.

**Comment by morphyhsieh** [comment]
Thx for tonyxue

It works but you need to specify your chroot_name if it is not "precise"

<code>sudo sh ~/Downloads/crouton -n chroot_name -u </code>

**Comment by brownieboy** [comment]
You also need to specify your chroot name when doing the upgrade.  So for Trusty, this would be:

sudo sh ~/Downloads/crouton -u -n trusty
