### ISSUE TITLE
How do irrelephants find this repo?

### ISSUE THREAD

**Issue by s3w47m88** [dnschneid/crouton#188]
[archived by @dnschneid: This bug plus Google, apparently.]

**Comment by rahulmodi1** [comment]
I am very new to Elastic Search. I want to index MySql data into it. I have studied few links but i am not able to get through it. Actually, i am using Windows system. Here i am not able to run below command:

./bin/plugin --install jdbc --url http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-river-jdbc/1.4.0.6/elasticsearch-river-jdbc-1.4.0.6-plugin.zip

Alternatively, i downloaded a zip having "elasticsearch-river-jdbc-1.0.0.RC1.2.jar". Then i put this jar in lib folder of Elastic Search so while running "elasticsearch.bat" file it is giving me an exception saying : "plugin river-jdbc, failed to invoke custom onModule method". 

Can anyone tell me how to solve this issue OR is there any alternate approach to index MySql data.

**Comment by jiaqiuwang123** [comment]
@dnschneid Thanks. I am learning it.

**Comment by ruhanijeb** [comment]
Is there any equivalent thing of "this.Resources.GetIdentifier("",packagename)" android in xamarin ios.

**Comment by DennisLfromGA** [comment]
@ruhanijeb,

> Is there any equivalent thing of "this.Resources.GetIdentifier("",packagename)" android in xamarin ios.

Does this pertain to 'crouton' in some way?

**Comment by varadha85** [comment]
I am encountering the following error when running unfactor.py kindly help.....

C:\>python "c:\python27\TeslaCrack-master\unfactor_ecdsa.py" AADHAARCARDAKG.pdf.
vvv 31 2927 57367 162256275048121520521753 204677407159300655087255717
Traceback (most recent call last):
  File "c:\python27\TeslaCrack-master\unfactor_ecdsa.py", line 69, in <module>
    print(main(sys.argv[1], sys.argv[2:]))
  File "c:\python27\TeslaCrack-master\unfactor_ecdsa.py", line 16, in main
    with open(file, "rb") as f:
IOError: [Errno 2] No such file or directory: 'AADHAARCARDAKG.pdf.vvv'

**Comment by tedm** [comment]
pip import crouton

**Comment by rugano** [comment]
how exactly do i submit my question to coders after writing?

**Comment by DennisLfromGA** [comment]
@rugano,

1. [Sign-in](https://github.com/login) to github
2. Navigate to ['crouton' issues](https://github.com/dnschneid/crouton/issues)
3. Click on the button to open a [New issue](https://github.com/dnschneid/crouton/issues/new)
4. Write or copy-paste your question to the coders.
5. Click the 'Submit new issue' button.

*Hope this helps,*
-**DennisL**

**Comment by smu86** [comment]
This question is w.r.t Koogra Excel. I need to know what is the method equivalent of Excel worksheets "xlWorkSheet.get_Range"  in KoograExcel. In case, if it is not defined, how to work with koogra in getting such methods defined in "Microsoft.Office.Interop.Excel". Any help is deeply appreciated. Thanks.

**Comment by DennisLfromGA** [comment]
**All**,

Please refer to https://github.com/dnschneid/crouton/issues/188#issuecomment-275215409 for crouton related questions.
You'll have to go elsewhere for questions unrelated to crouton.

*Hope this helps,*
-**DennisL**

**Comment by dnschneid** [comment]
Archive of this issue:

![screenshot 2017-03-14 at 15 35 48](https://cloud.githubusercontent.com/assets/522200/23919149/19942704-08cc-11e7-96a3-f9983a6f4f79.png)
