### ISSUE TITLE
getrelease.sh fails if extra fields are in sources.list

### ISSUE THREAD

**Issue by swarren** [dnschneid/crouton#1880]
installer/ubuntu/getrelease.sh prints $3 of the matching line in /etc/apt/sources.list. However, this isn't always the release name. For example, consider the following entry:

deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ trusty main restricted universe multiverse

$4 is required not $3.

(Serves me right for hacking the file in an attempt to run x86 binaries under qemu I suppose...)

**Comment by dnschneid** [comment]
Yeah, that's true.  From [the man page](http://manpages.debian.org/cgi-bin/man.cgi?sektion=5&query=sources.list&apropos=0&manpath=sid&locale=en) it looks like we need to use the field following the URI (wherever it is).

**Comment by tonyxue** [comment]
Fix is in PR #1903
