### ISSUE TITLE
Wishlist: Package as .deb

### ISSUE THREAD

**Issue by andrewmoise** [dnschneid/crouton#1882]
I don't know if this is feasible, but have you considered packaging up the crouton modifications as a .deb that can be installed into the chroot environment? It'd make it easier to track changes, know when things need updates, and so on, and it seems that it'd be simpler from the end user's perspective. I'm potentially interested in giving a hand with the packaging if you think it's a feasible approach.

**Comment by aaronhalford** [comment]
This is an interesting idea. This would also allow an official PPA to be created with automatic ( `sudo apt-get update && sudo apt-get upgrade` ) updating for the end user. I too wonder if the core architecture of crouton is feasible for deb packaging.

**Comment by tonyxue** [comment]
That would only work for updates inside the chroot. Sometimes, things outside the chroot (in the Chromium OS) also need to be updated, e.g. files in ```host-bin```

**Comment by drinkcat** [comment]
`.deb` are harder to maintain that the set of script crouton provides... It's held up pretty well considering the little effort we have put in it.
