### ISSUE TITLE
REQUEST - Any plans for Kali on Crouton to be Intel friendly? 

### ISSUE THREAD

**Issue by clening** [dnschneid/crouton#1886]
I love every single thing about Crouton. It's fabulous and makes me like Linux again -- notably finding the cli bonus add-on makes me really, really happy. 

I did have one small request --

I've tried to install Kali via Crouton for my Chromebook Pixel 2, but unfortunately, I think Kali at this point is AMD-only. Any chance of rerolling this to be intel-friendly as well? I'd do it myself, but I'm not particularly helpful when it comes to programming and I'd probably break things. 

Danke! 

--Carey

**Comment by NoPinky** [comment]
I don't think crouton kali is intel-unfriendly. I got a crouton kali install on my Acer C710 with Intel Celleron running for 3 months now. I don't use it very often, but when I do, it seems to run fine.
If there are no major changes in the last 3 months I don't see any reason why crouton kali is intel-unfriendly.... or did I miss something?

**Comment by dnschneid** [comment]
I suspect you're misinterpreting "[amd64](https://en.wikipedia.org/wiki/X86-64)".  Kali works fine on all platforms.

**Comment by clening** [comment]
Got it. It managed to work on the second go. Sorry I didn't close it.
