### ISSUE TITLE
Gnome automatically shutsdown

### ISSUE THREAD

**Issue by aurey2244** [dnschneid/crouton#1888]
I've tried installing gnome on the debian based distsros and couldn't get it to work, but got it to somewhat work for drinkcats arch linux.

Is there any tips as to how I can have trusty with the gnome desktop env or is there nothing I can do about it.

**Comment by Tuxerito** [comment]
sudo sh ~/Downloads/crouton -r trusty -t gnome

or
sudo sh ~/Downloads/crouton -r trusty -t gnome-desktop

**Comment by aurey2244** [comment]
Ok I'll try this and tell ya results afterwards, thanks

**Comment by aurey2244** [comment]
ok I tried and it stopped and terminated, this is what I got...chronos@localhost ~/Downloads $ sudo startgnome
Entering /mnt/stateful_partition/crouton/chroots/trusty...


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-67-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sat Jun 13 02:38:26 PDT 2015 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=a4561b01-851f-1145-8e1a-69a761a1ec80/PARTNROFF=1 hashtree=PARTUUID=a4561b01-851f-1145-8e1a-69a761a1ec80/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=cacb2fc085bb0a7c9d4673c969ad52047cdf6228 salt=f2e4b7520afa98f0c1430dec89cd936fc7c4081c802338908a02f6eb2c415f84" noinitrd vt.global_cursor_default=0 kern_guid=a4561b01-851f-1145-8e1a-69a761a1ec80  
Build Date: 12 February 2015  02:55:07PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jun 25 03:49:29 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
crouton: version 1-20150620222151~master:89796a99
release: trusty
architecture: armhf
xmethod: xorg
targets: gnome
host: version 6946.58.0 (Official Build) stable-channel daisy_freon 
kernel: Linux localhost 3.8.11 #1 SMP Sat Jun 13 02:38:26 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost ~/Downloads $ 

Perhaps maybe if I'd upgraded to unstable build channel of chrome os, do you think that would work?

**Comment by hitecherik** [comment]
I've got the same problem, but in both Debian (Jessie) and Ubuntu (Trusty).

**Comment by aurey2244** [comment]
@hitecherik have you ever installed gnome on anything!? I think debian wheezy and kali should work because they're the only ones that worked when I installed them as a chroot environment in my android but I don't really want those, anything for you tho?
