### ISSUE TITLE
Fatal server error: (EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)

### ISSUE THREAD

**Issue by kelpshake** [dnschneid/crouton#1889]
Crouton was working fine on my computer until a week or so ago.  Now whenever I try to open it (sudo startxfce4) or update (sudo sh -e ~/Downloads/crouton -n precise -u) it starts to update various things and then I get this:

Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

What can I do to fix this?

Thank You

**Comment by divx118** [comment]
Please post the output of `sudo sh  ~/Downloads/crouton -n precise -u` probably your update is failing for some reason.

**Comment by kelpshake** [comment]
Here is the output:

Downloading latest crouton installer...
######################################################################## #######################                                                  ###############################################                          ######################################################################## 100.0%
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startunity into the host...
Installing crouton-noroot into the chroot...
Installing startunity into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing crouton-unity-autostart into the chroot...
Installing unity-autostart.desktop into the chroot...
Installing unity-profiled into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://archive.ubuntu.com precise InRelease
Ign http://archive.ubuntu.com precise-updates InRelease
Ign http://archive.ubuntu.com precise-security InRelease
Hit http://archive.ubuntu.com precise Release.gpg
Get:1 http://archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:2 http://archive.ubuntu.com precise-security Release.gpg [198 B]
Hit http://archive.ubuntu.com precise Release
Get:3 http://archive.ubuntu.com precise-updates Release [196 kB]
Ign https://private-ppa.launchpad.net trusty InRelease
Hit https://private-ppa.launchpad.net trusty Release.gpg
Hit https://private-ppa.launchpad.net trusty Release
Hit https://private-ppa.launchpad.net trusty/main amd64 Packages
Get:4 http://archive.ubuntu.com precise-security Release [54.3 kB]
Hit https://private-ppa.launchpad.net trusty/main i386 Packages
Hit http://archive.ubuntu.com precise/main Sources 
Hit http://archive.ubuntu.com precise/restricted Sources
Hit http://archive.ubuntu.com precise/universe Sources
Hit http://archive.ubuntu.com precise/multiverse Sources
Hit http://archive.ubuntu.com precise/main amd64 Packages
Hit http://archive.ubuntu.com precise/restricted amd64 Packages
Hit http://archive.ubuntu.com precise/universe amd64 Packages
Hit http://archive.ubuntu.com precise/multiverse amd64 Packages
Hit http://archive.ubuntu.com precise/main i386 Packages
Ign https://private-ppa.launchpad.net trusty/main Translation-en
Hit http://archive.ubuntu.com precise/restricted i386 Packages
Hit http://archive.ubuntu.com precise/universe i386 Packages
Hit http://archive.ubuntu.com precise/multiverse i386 Packages
Hit http://archive.ubuntu.com precise/main Translation-en
Hit http://archive.ubuntu.com precise/multiverse Translation-en
Hit http://archive.ubuntu.com precise/restricted Translation-en
Hit http://archive.ubuntu.com precise/universe Translation-en
Get:5 http://archive.ubuntu.com precise-updates/main Sources [490 kB]
Get:6 http://archive.ubuntu.com precise-updates/restricted Sources [7981 B]
100% [5 Sources bzip2 0 B] [Packages 25.5 MB] [6 Sources 2568 B/7981 B 32                                                                         Get:7 http://archive.ubuntu.com precise-updates/universe Sources [120 kB]
100% [5 Sources bzip2 0 B] [Packages 25.5 MB] [7 Sources 2565 B/120 kB 2%                                                                         Get:8 http://archive.ubuntu.com precise-updates/multiverse Sources [9730 B]
100% [5 Sources bzip2 0 B] [Packages 25.5 MB] [8 Sources 2568 B/9730 B 26                                                                         Get:9 http://archive.ubuntu.com precise-updates/main amd64 Packages [909 kB]
97% [5 Sources bzip2 0 B] [Packages 25.5 MB] [9 Packages 2565 B/909 kB 0%                                                                         98% [6 Sources bzip2 0 B] [Packages 25.5 MB] [9 Packages 96.7 kB/909 kB 1                                                                         98% [7 Sources bzip2 0 B] [Packages 25.5 MB] [9 Packages 96.7 kB/909 kB 1                                                                         98% [8 Sources bzip2 0 B] [Packages 25.5 MB] [9 Packages 199 kB/909 kB 22                                                                         Get:10 http://archive.ubuntu.com precise-updates/restricted amd64 Packages [13.6 kB]
100% [9 Packages bzip2 0 B] [Packages 7816 kB] [10 Packages 2567 B/13.6 k                                                                         Get:11 http://archive.ubuntu.com precise-updates/universe amd64 Packages [267 kB]
100% [9 Packages bzip2 0 B] [Packages 7816 kB] [11 Packages 21.4 kB/267 k                                                                         Get:12 http://archive.ubuntu.com precise-updates/multiverse amd64 Packages [16.5 kB]
100% [9 Packages bzip2 0 B] [Packages 7816 kB] [12 Packages 2567 B/16.5 k                                                                         Get:13 http://archive.ubuntu.com precise-updates/main i386 Packages [959 kB]
99% [9 Packages bzip2 0 B] [Packages 7816 kB] [13 Packages 43.1 kB/959 kB                                                                         99% [9 Packages bzip2 0 B] [Packages 135 kB] [13 Packages 175 kB/959 kB 1                                                                         99% [9 Packages bzip2 0 B] [Packages 25.6 MB] [13 Packages 175 kB/959 kB                                                                          Get:14 http://archive.ubuntu.com precise-updates/restricted i386 Packages [13.6 kB]
100% [9 Packages bzip2 0 B] [Packages 25.6 MB] [14 Packages 8192 B/13.6 k                                                                         Get:15 http://archive.ubuntu.com precise-updates/universe i386 Packages [276 kB]
100% [9 Packages bzip2 0 B] [Packages 25.6 MB] [15 Packages 21.4 kB/276 k                                                                         Get:16 http://archive.ubuntu.com precise-updates/multiverse i386 Packages [16.7 kB]
100% [11 Packages bzip2 0 B] [Packages 25.6 MB] [16 Packages 0 B/16.7 kB                                                                          Hit http://archive.ubuntu.com precise-updates/main Translation-en    
Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en
Hit http://archive.ubuntu.com precise-updates/restricted Translation-en
Hit http://archive.ubuntu.com precise-updates/universe Translation-en
Get:17 http://archive.ubuntu.com precise-security/main Sources [130 kB]
100% [13 Packages bzip2 0 B] [Packages 25.6 MB] [17 Sources 21.4 kB/130 k                                                                         Get:18 http://archive.ubuntu.com precise-security/restricted Sources [3759 B]
100% [13 Packages bzip2 0 B] [Packages 25.6 MB] [18 Sources 2569 B/3759 B                                                                         Get:19 http://archive.ubuntu.com precise-security/universe Sources [43.0 kB]
100% [13 Packages bzip2 0 B] [Packages 25.6 MB] [19 Sources 9807 B/43.0 k                                                                         Get:20 http://archive.ubuntu.com precise-security/multiverse Sources [2186 B]
100% [13 Packages bzip2 0 B] [Packages 25.6 MB] [20 Sources 2186 B/2186 B                                                                         Get:21 http://archive.ubuntu.com precise-security/main amd64 Packages [525 kB]
99% [13 Packages bzip2 0 B] [Packages 25.6 MB] [21 Packages 2565 B/525 kB                                                                         100% [13 Packages bzip2 0 B] [21 Packages 236 kB/525 kB 45%]       11.9 M                                                                         100% [13 Packages bzip2 0 B] [Packages 592 kB] [21 Packages 236 kB/525 kB                                                                         100% [13 Packages bzip2 0 B] [21 Packages 428 kB/525 kB 82%]       11.9 M100% [13 Packages bzip2 0 B] [Translation-en 3862 kB] [21 Packages 428 kB                                                                         100% [13 Packages bzip2 0 B] [Translation-en 3862 kB] [Waiting for header                                                                         Get:22 http://archive.ubuntu.com precise-security/restricted amd64 Packages [8943 B]
                                                                         100% [13 Packages bzip2 0 B] [Translation-en 3862 kB] [22 Packages 8943 B                                                                         100% [13 Packages bzip2 0 B] [Translation-en 3862 kB] [Waiting for header                                                                         Get:23 http://archive.ubuntu.com precise-security/universe amd64 Packages [123 kB]
                                                                         100% [13 Packages bzip2 0 B] [Translation-en 3862 kB] [23 Packages 2565 B100% [13 Packages bzip2 0 B] [Translation-en 3862 kB]              11.9 M100% [13 Packages bzip2 0 B] [Waiting for headers]                 11.9 M                                                                         100% [13 Packages bzip2 0 B] [Translation-en 367 kB] [Waiting for headers                                                                         Get:24 http://archive.ubuntu.com precise-security/multiverse amd64 Packages [2689 B]
                                                                         100% [13 Packages bzip2 0 B] [Translation-en 367 kB] [24 Packages 2569 B/                                                                         100% [13 Packages bzip2 0 B] [Translation-en 367 kB] [Waiting for headers                                                                         100% [13 Packages bzip2 0 B] [Waiting for headers]                 11.9 M                                                                         100% [13 Packages bzip2 0 B] [Translation-en 10.2 kB] [Waiting for header                                                                         100% [13 Packages bzip2 0 B] [Waiting for headers]                 11.9 M                                                                         100% [13 Packages bzip2 0 B] [Translation-en 15.0 MB] [Waiting for header                                                                         Get:25 http://archive.ubuntu.com precise-security/main i386 Packages [566 kB]
                                                                         99% [13 Packages bzip2 0 B] [Translation-en 15.0 MB] [25 Packages 12.3 kB100% [Translation-en 15.0 MB] [25 Packages 511 kB/566 kB 90%]      11.9 M100% [14 Packages bzip2 0 B] [Translation-en 15.0 MB] [25 Packages 511 kB100% [Translation-en 15.0 MB] [25 Packages 518 kB/566 kB 92%]      11.9 M100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB] [25 Packages 518 kB100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB]              11.9 M                                                                         Get:26 http://archive.ubuntu.com precise-security/restricted i386 Packages [8939 B]
100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB] [26 Packages 2568 B                                                                         100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB] [Waiting for header                                                                         Get:27 http://archive.ubuntu.com precise-security/universe i386 Packages [131 kB]
                                                                         100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB] [27 Packages 21.4 k100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB]              11.9 M                                                                         Get:28 http://archive.ubuntu.com precise-security/multiverse i386 Packages [2876 B]
100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB] [28 Packages 2876 B                                                                         100% [15 Packages bzip2 0 B] [Translation-en 15.0 MB] [Waiting for header                                                                         100% [Translation-en 15.0 MB] [Waiting for headers]                11.9 M                                                                         100% [16 Packages bzip2 0 B] [Translation-en 15.0 MB] [Waiting for header                                                                         100% [Translation-en 15.0 MB] [Waiting for headers]                11.9 M                                                                         100% [17 Sources bzip2 0 B] [Translation-en 15.0 MB] [Waiting for headers                                                                         Hit http://archive.ubuntu.com precise-security/main Translation-en
100% [17 Sources bzip2 0 B] [Translation-en 15.0 MB] [Waiting for headers                                                                         100% [Translation-en 15.0 MB] [Waiting for headers]                11.9 M                                                                         100% [18 Sources bzip2 0 B] [Translation-en 15.0 MB] [Waiting for headers                                                                         100% [Translation-en 15.0 MB] [Waiting for headers]                11.9 M                                                                         100% [19 Sources bzip2 0 B] [Translation-en 15.0 MB] [Waiting for headers                                                                         Hit http://archive.ubuntu.com precise-security/multiverse Translation-en
100% [19 Sources bzip2 0 B] [Translation-en 15.0 MB] [Waiting for headers                                                                         100% [Translation-en 15.0 MB] [Waiting for headers]                11.9 M                                                                         100% [20 Sources bzip2 0 B] [Translation-en 15.0 MB] [Waiting for headers                                                                         100% [Translation-en 15.0 MB] [Waiting for headers]                11.9 M                                                                         100% [21 Packages bzip2 0 B] [Translation-en 15.0 MB] [Waiting for header                                                                         Hit http://archive.ubuntu.com precise-security/restricted Translation-en
100% [21 Packages bzip2 0 B] [Translation-en 15.0 MB] [Waiting for header                                                                         Hit http://archive.ubuntu.com precise-security/universe Translation-en
                                                                         100% [21 Packages bzip2 0 B] [Translation-en 15.0 MB]              11.9 M100% [21 Packages bzip2 0 B]                                       11.9 M100% [21 Packages bzip2 0 B] [Translation-en 4331 kB]              11.9 M100% [Translation-en 4331 kB]                                      11.9 M100% [22 Packages bzip2 0 B] [Translation-en 4331 kB]              11.9 M100% [Translation-en 4331 kB]                                      11.9 M100% [23 Packages bzip2 0 B] [Translation-en 4331 kB]              11.9 M100% [23 Packages bzip2 0 B]                                       11.9 M100% [23 Packages bzip2 0 B] [Translation-en 36.4 kB]              11.9 M100% [23 Packages bzip2 0 B]                                       11.9 M100% [23 Packages bzip2 0 B] [Translation-en 18.6 kB]              11.9 M100% [23 Packages bzip2 0 B]                                       11.9 M100% [23 Packages bzip2 0 B] [Translation-en 858 kB]               11.9 M100% [23 Packages bzip2 0 B]                                       11.9 M100% [23 Packages bzip2 0 B] [Translation-en 3110 kB]              11.9 M100% [Translation-en 3110 kB]                                      11.9 M100% [24 Packages bzip2 0 B] [Translation-en 3110 kB]              11.9 M100% [Translation-en 3110 kB]                                      11.9 M100% [25 Packages bzip2 0 B] [Translation-en 3110 kB]              11.9 M100% [25 Packages bzip2 0 B]                                       11.9 M100% [25 Packages bzip2 0 B] [Translation-en 3115 B]               11.9 M100% [25 Packages bzip2 0 B]                                       11.9 M100% [25 Packages bzip2 0 B] [Translation-en 12.6 kB]              11.9 M100% [25 Packages bzip2 0 B]                                       11.9 M100% [25 Packages bzip2 0 B] [Translation-en 443 kB]               11.9 M100% [25 Packages bzip2 0 B]                                       11.9 M100% [Working]                                                     11.9 M100% [26 Packages bzip2 0 B]                                       11.9 M100% [Working]                                                     11.9 M100% [27 Packages bzip2 0 B]                                       11.9 M100% [Working]                                                     11.9 M100% [28 Packages bzip2 0 B]                                       11.9 M100% [Working]                                                     11.9 M                                                                         Fetched 4896 kB in 8s (578 kB/s)
Reading package lists... Done
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  keyutils
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sudo is already the newest version.
apt-transport-https is already the newest version.
wget is already the newest version.
ca-certificates is already the newest version.
The following package was automatically installed and is no longer required:
  keyutils
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 103c37a8bf17ea65d590acd56f5d1a1778d27b1e)...
--2015-06-23 12:50:33--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/103c37a8bf17ea65d590acd56f5d1a1778d27b1e.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 74.125.70.82, 2607:f8b0:4001:c02::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.70.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.Yxt8Jl/adhd.tar.gz'

     0K .......... .......... .......... .......... ..........  933K
    50K .......... .......... .......... .......... .......... 1.63M
   100K .......... .......... .......... .......... .......... 2.17M
   150K .......... .......... .......... .......... .......... 3.19M
   200K .......... .......... .......... .......... .......... 2.84M
   250K .......... .......... .......... .......... .......... 6.72M
   300K .......... .......... .......... .......... .......... 2.01M
   350K .......... .......... .......... .......... .......... 3.65M
   400K .......... .......... .......... .......... .....      2.08M=0.2s

2015-06-23 12:50:34 (2.12 MB/s) - '/tmp/crouton-cras.Yxt8Jl/adhd.tar.gz' saved [456009]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libasound2:i386 is already the newest version.
libspeexdsp1:i386 is already the newest version.
alsa-utils is already the newest version.
The following package was automatically installed and is no longer required:
  keyutils
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc-multilib is already the newest version.
pkg-config is already the newest version.
gcc is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Breaks: libc6-dev:i386 (!= 2.19-0ubuntu6.6) but 2.15-0ubuntu10.12 is to be installed
 libc6-dev:i386 : Depends: libc6:i386 (= 2.15-0ubuntu10.12) but 2.19-0ubuntu6.6 is to be installed
                  Depends: libc-dev-bin:i386 (= 2.15-0ubuntu10.12)
                  Depends: linux-libc-dev:i386 but it is not going to be installed
                  Breaks: libc6-dev (!= 2.15-0ubuntu10.12) but 2.19-0ubuntu6.6 is to be installed
 libspeexdsp-dev:i386 : Depends: libspeexdsp1:i386 (= 1.2~rc1-3ubuntu2) but 1.2~rc1.1-1ubuntu1 is to be installed
                        Depends: libspeex-dev:i386 (= 1.2~rc1-3ubuntu2) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by divx118** [comment]
Before doing anything, [backup your chroot](https://github.com/dnschneid/crouton#a-backup-a-day-keeps-the-price-gouging-data-restoration-services-away)
Then use `sudo enter-chroot -n precise` to enter the command line of your chroot so you can resolve your issue with `libc6-dev : Breaks: libc6-dev:i386` which looks the same like https://github.com/dnschneid/crouton/issues/1694 Maybe following could help. https://bugs.launchpad.net/ubuntu/+source/eglibc/+bug/1365375 ...
