### ISSUE TITLE
failed to install vivid: missing dependencies

### ISSUE THREAD

**Issue by frederic-parrenin** [dnschneid/crouton#1890]
Today I tried to install vivid with the following command:

sudo sh -e ~/Downloads/crouton -r vivid -t gnome,touch,keyboard

However, it failed with the following error message:

dpkg: dependency problems prevent configuration of lsb-release:
 lsb-release depends on python3; however:
  Package python3 is not installed.
 lsb-release depends on python3:any (>= 3.3.2-2~); however:

dpkg: error processing package lsb-release (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of ubuntu-minimal:
 ubuntu-minimal depends on lsb-release; however:
  Package lsb-release is not configured yet.
 ubuntu-minimal depends on python3; however:
  Package python3 is not installed.
 ubuntu-minimal depends on resolvconf; however:
  Package resolvconf is not installed.

dpkg: error processing package ubuntu-minimal (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dh-python:
 dh-python depends on python3:any (>= 3.3.2-2~).

dpkg: error processing package dh-python (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 lsb-release
 ubuntu-minimal
 dh-python
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/vivid...

**Comment by dnschneid** [comment]
See #1706
