### ISSUE TITLE
Debian Jessie: Cannot install .deb packages via the GUI

### ISSUE THREAD

**Issue by ralmidani** [dnschneid/crouton#1891]
I'm using a Samsung Chromebook 2 (Peach Pi). 

After installing Debian Jessie, I try downloading .deb packages and installing them via the GUI. I am told I need administator priveleges, but when I enter my password, I keep getting the same screen.

This issue comes up with both xephyr and xiwi.

Edit: installing packages via apt-get works fine. The same password I supply when using sudo does not work when trying to install packages via the GUI.

**Comment by drinkcat** [comment]
Closing. But, unless proven otherwise, this looks like a Debian bug, maybe?
