### ISSUE TITLE
Stretch Ctl+Shift+Alt+Backspace

### ISSUE THREAD

**Issue by wmadan** [dnschneid/crouton#1896]
Hello,

I have a Chromebook Pixel 2 and installed Debian stretch in crouton successfully. The problem is that I can't get back to Chrome OS with Ctl+Shift+Alt+Backspace. All I get is a black screen and can't get out of it. So, I have to power off and reboot to get the system working again. This was the same result whether I was in KDE or Gnome.

**Comment by SpafinDoople** [comment]
Hello wmadan,

Are you doing Ctrl+Shift+Alt+Backspace, of Ctrl+Shift+Alt+F1?

Thanks.

~**SpafinDoople*

**Comment by wmadan** [comment]
Hi SpafinDoople,

Ctrl+Shift+Alt+Backspace

**Comment by SpafinDoople** [comment]
I think the proper shortcut is Ctrl+Shift+Alt+F1.

**Comment by wmadan** [comment]
Actually, since I have a Chromebook Pixel, I have no F1 key. It's the back arrow in the top left that I use, not backspace. My correction.

**Comment by Lucas502** [comment]
Use Ctrl+Alt+Shift+F1/<---

**Comment by wmadan** [comment]
Lucas 502, I don't have an F1 key, but the key I have, the <--, which is the second key from the left, is the one I have been using. It doesn't work.

**Comment by Lucas502** [comment]
Exactly F1 is the <-- but did you make sure you held down all the buttons, including shift

**Comment by wmadan** [comment]
Yes, I did.

I ended up installing sid and xiwi and that is working.

**Comment by SpafinDoople** [comment]
I have a chromebook pixel too. For future references, The keys on the top row are F1/F2/F3 etc. keys in linux.

**Comment by darcyparker** [comment]
Is this same as #1935  ?

**Comment by darcyparker** [comment]
Going back through other issues... This seems to be the same as #1699
