### ISSUE TITLE
Cannot create backup - error with tar and trusty/etc/init/dbus.conf

### ISSUE THREAD

**Issue by compumetrika** [dnschneid/crouton#1897]
I'm running trusty under crouton on an Acer c720-3404. I've been successfully backing up to a thumb drive in the past using a command [from the readme](https://github.com/dnschneid/crouton#a-backup-a-day-keeps-the-price-gouging-data-restoration-services-away) (plus file location):
    sudo edit-chroot -b -f /media/removable/USB\ Drive/ trusty

However this recently stopped working. There appears to be a missing file or something similar which throws an error under tar (see below). I've searched through both open and closer issues and haven't seen something which looks applicable (but of course may have missed something -- if there is something applicable I'm happily corrected...)

I've confirmed that the file system is correct (have tried this with ext4 and ntfs) and that the thumbdrive is writeable for the OS. 

Here is the current error I am getting:

> chronos@localhost ~ $ sudo edit-chroot -b -f '/media/removable/USB Drive/trusty-20150627-1530.bz' trusty
> Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
> tar: trusty/etc/init/dbus.conf: Read error at byte 0, while reading 489 bytes: Input/output error20150627-1530.bz...
> tar: trusty/etc/default/dbus: Read error at byte 0, while reading 297 bytes: Input/output error
> tar: trusty/home/npalmer/.cache/keyring-eqBjZV/control: socket ignored
> tar: trusty/home/npalmer/.cache/keyring-8YoqWk/control: socket ignored
> tar: trusty/home/npalmer/.config/chromium/Default/Cookies: File shrank by 1121280 bytes; padding with zeros
> tar: Exiting with failure status due to previous errors
> Unable to backup /mnt/stateful_partition/crouton/chroots/trusty.
> Deleting partial archive.

I get this error regardless of the file system I use on the thumb drive. The drive itself is SanDisk Ultra USB 3.0 128GB, and there is nothing else on the drive -- I've formatted it to whichever filesystem I wanted to try out (ntfs and ext4 and even fat32, the default filesystem to which ChromeOS formats the thumbdrive if you right-click and select "format" in ChromeOS file browser). 

I tried cat-ing the first two files which appear to have the issue, and am getting an i/o error:

> chronos@localhost / $ cat /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf
> cat: /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf: Input/output error
> chronos@localhost / $ ls /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf
> /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf
> chronos@localhost / $ ls -l /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf
> -rw-r--r-- 1 root root 489 Nov 11  2013 /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf
> chronos@localhost / $ sudo cat /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf
> cat: /mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf: Input/output error
> chronos@localhost / $ sudo cat /mnt/stateful_partition/crouton/chroots/trusty/etc/default/dbus
> cat: /mnt/stateful_partition/crouton/chroots/trusty/etc/default/dbus: Input/output error
> chronos@localhost / $ ls -l /mnt/stateful_partition/crouton/chroots/trusty/etc/default/dbus
> -rw-r--r-- 1 root root 297 Nov 11  2013 /mnt/stateful_partition/crouton/chroots/trusty/etc/default/dbus

Unfortunately I don't know much about these files in question -- and thus don't know if this is a particular-to-chroot issue or some broader issue for my xfce ubuntu install. 

Any insight is greatly appreciated.

**Comment by npalmer** [comment]
An update: I just used a plain "cp" command to copy the chroot to my backup thumbdrive. I'm hoping the output of that can help determine what is causing the edit-chroot -b to fail:

> chronos@localhost / $ sudo cp -r /mnt/stateful_partition/crouton/chroots/trusty /media/removable/USB\ Drive/backups/
> cp: error reading ‘/mnt/stateful_partition/crouton/chroots/trusty/etc/default/dbus’: Input/output error
> cp: failed to extend ‘/media/removable/USB Drive/backups/trusty/etc/default/dbus’: Input/output error
> cp: error reading ‘/mnt/stateful_partition/crouton/chroots/trusty/etc/init/dbus.conf’: Input/output error
> cp: failed to extend ‘/media/removable/USB Drive/backups/trusty/etc/init/dbus.conf’: Input/output error
> cp: error reading ‘/mnt/stateful_partition/crouton/chroots/trusty/home/npalmer/.config/chromium/Default/Cookies’: Input/output error
> cp: failed to extend ‘/media/removable/USB Drive/backups/trusty/home/npalmer/.config/chromium/Default/Cookies’: Input/output error

Of course I would still very much like to use edit-chroot -b. Advice on how to get that working correctly is still appreciated!

**Comment by divx118** [comment]
You could try a reboot of your chromebook and then start your backup. So
you are sure the chroot is unmounted. If that doesn't work, it could also
be that those files are damaged. If that is the case you should also get an
error when you enter the chroot and try to cat the files in the chroot.

**Comment by npalmer** [comment]
> You could try a reboot of your chromebook and then start your backup. So you
are sure the chroot is unmounted.

Yes, unfortunately I tried the reboot (to ensure unmounting) already and
got the same result.

> it could also be that those files are damaged. If that is the case you
should also get an error when you enter the chroot and try to cat the files
in the chroot.

Ah, so, from inside the chroot I also get an error when I try to cat those
files:

> (trusty)[username]@localhost:~$ cat /etc/default/dbus
> cat: /etc/default/dbus: Input/output error
> (trusty)[username]@localhost:~$ cat /etc/init/dbus.conf
> cat: /etc/init/dbus.conf: Input/output error

So it appears the files are damaged.

I'm afraid I don't immediately know how to go about fixing these. What do I
need to think about doing?

Is it as simple as running a crouton update, or do I need to manually
change these files?



​

**Comment by dnschneid** [comment]
You'd have to manually repair those files.

It might be interesting to run `sudo e2fsck -vfn "$(awk '/mnt\/stateful_partition /{print $1}' /proc/mounts)"` and see what it thinks are broken (have your chroot unmounted or the results will be weird).

**Comment by Timvrakas** [comment]
This just happened to me too.... (Same device, same time-frame; coincidence?) Here is the result of e2fsck:

    e2fsck 1.42.12 (29-Aug-2014)
    Warning!  /dev/sda1 is mounted.
    Warning: skipping journal recovery because doing a read-only filesystem check.
    Pass 1: Checking inodes, blocks, and sizes
    Pass 2: Checking directory structure
    Pass 3: Checking directory connectivity
    Pass 4: Checking reference counts
    Pass 5: Checking group summary information
    Free blocks count wrong (1261612, counted=1958170).
    Fix? no

    Free inodes count wrong (1393191, counted=1393441).
    Fix? no


      291065 inodes used (17.28%, out of 1684256)
        3493 non-contiguous files (1.2%)
         976 non-contiguous directories (0.3%)
             # of inodes with ind/dind/tind blocks: 0/0/0
             Extent depth histogram: 290054/529/1
     5466580 blocks used (81.25%, out of 6728192)
           0 bad blocks
           2 large files

      227068 regular files
       31685 directories
           0 character device files
           0 block device files
           0 fifos
         137 links
       32048 symbolic links (218 fast symbolic links)
           5 sockets
    ------------
      290943 files


I'm no expert on Filesystems, but it looks like at least some things are messed up.
How to fix this? can I boot into a USB stick to recover?

**Comment by Timvrakas** [comment]
I tried booting from a 15.04 USB I had lying around, but e2fsck does not report any issues, nor make changes. When I boot back to chrome OS the issues are still there.

**Comment by npalmer** [comment]
So, honestly, I just had to powerwash and reinstall everything. Now things
seem to be mostly working fine.

Fortunately I'd used the machine almost entirely for programming, with
everying save to git repos, wo not much was lost. It *was* a pain to
reinstall all my programs, but such is life...

*Nathan M. Palmer*
PhD Candidate
Department of Computational Social Sciences
George Mason University
npalmer4@gmu.edu
http://npalmer.github.io/
