### ISSUE TITLE
black screen (with maybe one flash) in Crouton

### ISSUE THREAD

**Issue by emanuensis** [dnschneid/crouton#1898]
i get a black screen (with maybe a flash of the true screen) whenever i switch to the crouton.

i am in a HP Chromebook 14 with an HDMI connected second screen. Trusty failed (presumably updated) before i got the new HDMI screen. After that i did

Fetch a fresh installer:
https://goo.gl/fd3zc
then
sudo enter-chroot -n trusty
croutonversion -u -d
exit
sudo sh ~/Downloads/crouton -u -n trusty
sudo startxfce4 -n trusty

and some (many) variations on that.

i was able to confirm trusty is running fine as (blindly) i installed a server therein and was able to run fom it on the Chrome side.

It sometimes flashes once when i disconnect the HDMI screen ... reconnecting before i go  into ChromeOS it can be difficult to get both screens running. Sometimes a cold reboot is necessary.

---supplements

 i think it is a monitor - as it does not have sound. a
Samsung SynchMaster B2430

In ChromeOS the HDMI screen is an Extension of the main screen. No configuration work has been done (is possible?) in trusty

**Comment by Lucas502** [comment]
Are you attempting to mirror your screen to a monitor or television?

**Comment by emanuensis** [comment]
Have not done anything in trusty, but in ChromeOS the HDMI screen is an Extension of the main screen.

**Comment by Lucas502** [comment]
You didn't answer my question...

**Comment by emanuensis** [comment]
Oh sorry. i think it is a monitor - as it does not have sound. a
Samsung SynchMaster B2430

**Comment by Lucas502** [comment]
So you are attempting to mirror your screen?

**Comment by emanuensis** [comment]
No, in ChromeOS the HDMI screen is an Extension of the main screen. No configuration work has been (is possible?) in trusty

**Comment by Lucas502** [comment]
Hmmm... This isn't much of my expertise. I'm going to delete my comments so this can be noticed maybe be dnschneid.

**Comment by emanuensis** [comment]
i get the message

AIGLX: Suspending AIGLX clients for VT switch

at the ctrl-alt-f2 screen before the ctrl-alt-f3 (flashed) screen

**Comment by emanuensis** [comment]
Thought i'd found it, so i executed the 7 lines at
https://github.com/dnschneid/crouton/issues/704#issuecomment-46393045
but no jo:(

i did find that entering
sudo enter-chroot -n trusty
at the developers terminal (ctrl-alt-F1) throws you into trusty with a CLI interface. So i am able to do fg, bg ctrl-z, and jobs to run multiple servers etc.

Unfortunately i cannot run any GUI/X apps. Eg i was usin Kate and enjoying multiscreens and paste buffers:)

i also found that if i
sudo startxfce4
in the developers terminal ... every time i switch trom the DT to the trusty installation it flashes trusty as it is. So i can make changes and see their effcts ... if my vision is real quick:).

**Comment by DennisLfromGA** [comment]
@emanuensis,

> i am in a HP Chromebook 14 with an HDMI connected second screen.

I haven't had any problems and I'm using an HP Chromebook 14 also but it's the older Haswell (Falco) model, not ARM. I use the 'xiwi' xmethod and no second screen though.

> So i am able to do fg, bg ctrl-z, and jobs to run multiple servers etc.

You could also use [screen, tmux, or byobu](http://superuser.com/questions/423310/byobu-versus-gnu-screen-versus-tmux). I personally use 'screen' since I've got it configured just the way I want but I may switch to tmux in the near future.

**Comment by emanuensis** [comment]
i did try xiwi, to not very good success:( i did get a display i could interact with so that is a plus. However the extension (that display is far bigger at 1080p) and only displays (as non black) the upper 3-400 pixels. The cursor is only on that display in the beginning: once it leaves it is stuck in the main display.

Perhaps this is fixable? i do not know how to access display controls in trusty or ChromeOS. Some whole windows of my ChromeOS installation were gone and all were rearranged.

i also do not seem to have effective access to apps. Eg i did
xiwi kate
which showed up on a jobs list but garnered no display window...

**Comment by wytcld** [comment]
Similar problem on an Acer. It's been this way for over a month now, through several updates. Going with ctrl-alt-right arrow shows a brief flash of the trusty screen, but it then immediately goes black. Doesn't matter if it's from sudo startxfce4 outside of the chroot, or using enter-chroot first and then startxfce4.

Strangely, on an Asus, it's for as long been the opposite problem. Once it starts XFCE in Linux there's no way back to anything but a black screen on Crome until the system's rebooted. In that case enter-chroot also works.

**Comment by emanuensis** [comment]
Doing
sudo sh ~/Downloads/crouton -r name -t lxde,xiwi -n name
for all names including
jessie stretch trusty precise
and then eg
sudo startxiwi -n jessie startlxde
with the same second monitor (1080p) i get an LXDE window that uses 100% of the main display and the top 25% of the second one to disply a LXDE desktop. The cursor is in the second window but as soon as move it into the first it cannot go back

The only way out is a cold boot (logging out of LXDE still leaves one with the windows messed up)

Perhaps there is some routine in Linux which can configure these monitors to match the Chrome set up?

It is a problem with monitor configuration however. If the second monitor is disconnected then it is quite normal, just with one screen.

**Comment by dnschneid** [comment]
Do you still have the issue if you use <kbd>ctrl</kbd> <kbd>alt</kbd> <kbd>shift</kbd> <kbd>forward</kbd> instead of the two-step switch?  Could you also post the output of `sudo edit-chroot -al`?

**Comment by emanuensis** [comment]
@dnschneid
No. i am currently working with Debian and LXDE, see

`https://github.com/dnschneid/crouton/issues/1955`

Now i still get (in debs, a pure LXDE stretch) a mirrored interface using the larger of the two displays. Ie not the screen extension seen in chrome.

Differing from what i said in the above problem report however i cannot get xiwi to work at all in either jessie or stretch with eg

`sudo sh ~/Downloads/crouton -r jessie -t xiwi,lxde -n jesx`

It fails

`sudo startxiwi -n jesx startlxde`

with

>Cannot connect to extension, retrying...

**Comment by emanuensis** [comment]
Nothing new or different occurs if i check the `enable debugging` box in the "crouton" extension.

So the XiWi is unavailable, and the regular is crippled to a single screen as of now.

**Comment by emanuensis** [comment]
emanuensis commented: 150801.1508

Nothing new or different occurs if i check the `enable debugging` box
in the "crouton" extension.

So the XiWi is unavailable in jessie and stretch, and the regular is
crippled to a single screen as of now.

---

emanuensis commented: 150801.1823


@dnschneid
No. i am currently working with Debian and LXDE, see

`https://github.com/dnschneid/crouton/issues/1955`

Now i still get (in debs, a pure LXDE stretch) a mirrored interface
using the larger of the two displays. Ie not the screen extension seen
in chrome.

Differing from what i said in the above problem report however i
cannot get  to work at all in either jessie or stretch with eg

`sudo sh ~/Downloads/crouton -r jessie -t ,lxde -n jesx`

It fails

`sudo startxiwi -n jesx startlxde`

with

>...
>Cannot connect to extension, retrying...
>Cannot connect to extension, retrying...
>Unable to start display, make sure the crouton extension is installed
>and enabled, and up to date. (download from http://goo.gl/OVQOEt)
>Running exit commands...
>/usr/bin/xinit: connection to X server lost
>
>waiting for X server to shut down Hangup
Hangup
>(EE) Server terminated successfully (0). Closing log file.
>
>Unmounting /mnt/stateful_partition/crouton/chroots/jesx...
>Sending SIGTERM to processes under >/mnt/stateful_partition/crouton/chroots/jesx...
>Sending SIGKILL to processes under >/mnt/stateful_partition/crouton/chroots/jesx...

---

from: David Schneider <notifications@github.com>
reply-to: dnschneid/crouton
<reply@reply.github.com>
to: dnschneid/crouton <crouton@noreply.github.com>
cc: emanuensis <emanuensis@gmail.com>
date: 1 August 2015 at 14:03
subject: Re: [crouton] black screen (with maybe one flash) in Crouton (#1898)

dnschneid commented 150801.1403

>Do you still have the issue if you use ctrl alt shift forward instead of the two-step switch? Could you also post the output of sudo edit-chroot -al?
