### ISSUE TITLE
Debian Stretch and Sid: Cannot Install Packages in GDebi, Synaptic

### ISSUE THREAD

**Issue by wmadan** [dnschneid/crouton#1900]
On my Chromebook Pixel 2 running both Stretch and Sid, I cannot install packages with GDebi. Gdebi launches and asks for my password. The password I set up with the chroot does not work. I am running Gnome.

Also, in both Stretch and Sid, Synaptic does not run from Activities > Show Applications.

**Comment by logicrime** [comment]
I'm having the same issue on Jessie. Can't seem to figure it out.

**Comment by logicrime** [comment]
sudo passwd root

solved it for me, will report back if something shitty happens as a result.

I didn't know Gdebi used the root password, but w/e

**Comment by dnschneid** [comment]
Does `gconftool -s -t b /apps/gksu/sudo-mode t` fix things for you (assuming you haven't done what @logicrime suggested yet)?
