### ISSUE TITLE
Debian Stretch and Sid: Gnome Terminal Does Not Launch

### ISSUE THREAD

**Issue by wmadan** [dnschneid/crouton#1901]
On both Stretch and Sid, I cannot launch the Gnome Terminal from Activities > Show Applications. Clicking the icon does nothing.

**Comment by yebyen** [comment]
Gnome Terminal depends on dbus (I think?), which you can see in the error messages it spews out if you launch it from a terminal.  (I'm using rxvt-unicode because it does not have such a dependency.)
The issue here is that dbus is not launched when systemd is not used, I think.

**Comment by drinkcat** [comment]
Please re-open if this is still an issue.
