### ISSUE TITLE
How to properly reference crouton scripts from removable media?

### ISSUE THREAD

**Issue by JoshMcCullough** [dnschneid/crouton#1902]
Hi - first, I'm amazed at how awesome crouton is! Great work, thank you!

I install crouton first to my built-in storage, but then I decided to install it on an SD card instead. That is all working great, and I've removed the built-in chroot. Now, as far I know, there are no remaining remnants of crouton in built-in storage. I then added `/media/removable/SD128GB/crouton/bin` to my `PATH` in `~/.profile` and I confirmed that it finds things there, by running `which enter-chroot`. However, when I actually try to enter the chroot, here's what happens:

    > sudo sh enter-chroot
    sh: Can't open enter-chroot

If I use the full path, it works:

    > sudo sh /media/removable/SD128GB/crouton/bin/enter-chroot
    Entering /media/removable/SD128GB/crouton/chroots/trusty... <<success>>

I'm not sure why it's not working, any ideas?

**Comment by tonyxue** [comment]
> sudo sh enter-chroot

You've put ```enter-chroot``` in the PATH, so just run ```sudo enter-chroot```.
By running ```sh enter-chroot```, you're looking for a file called ```enter-chroot``` in your current directory.

**Comment by JoshMcCullough** [comment]
Sorry, I tried that:

    > sudo enter-chroot
    sudo: enter-chroot: command not found
    > which enter-chroot
    /media/removable/SD128GB/crouton/bin/enter-chroot

Note that I had to source my `.profile` as I'm not sure how to get the shell to auto-source it. I have this in my `~/.profile`:

    PATH=$PATH:/media/removable/SD128GB/crouton/bin

And I source it by doing this:

    > . ~/.profile

Then `which enter-chroot` works, but executing `enter-chroot` does not.

**Comment by divx118** [comment]
By default chromeos mounts the external media with noexec rights. So you either need to remount on the  commandline or use `sh` with the full path.

**Comment by dnschneid** [comment]
...which you can make easier either by throwing a script in /usr/local/bin/ that calls the right thing, or adding an alias to your .profile.
