### ISSUE TITLE
Debian jessie minimal (without the bloatware)

### ISSUE THREAD

**Issue by flexjoly** [dnschneid/crouton#1904]
Hi,

First, thanks this great script! Although I still wonder why we just cant upgrade the gentoo kernel to full linux without chroot or dualboot. ;)

After succesfully trying ubuntu+lxde+xiwi+chrome, i wanted to try debian. I works fine, but it has a lot of bloatware like games, bittorrent, unwanted media tools. 
I will try to uninstall them. But it would be nice if there would be an option to select the minimal install.

Debian has an option ' --variant=minbase' in debootstrap. I guess this would do the job?

Thanks in advance, flexjoly

**Comment by drinkcat** [comment]
I don't think crouton installs much bloatware by default?
