### ISSUE TITLE
DVD Cannot playback in VLC

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#1906]
Thanks again for crouton. I've attached an external DVD drive to watch movies which identifies itself as 

    Bus 001 Device 002: ID 059f:0643 LaCie, Ltd 

...and which I've proven spins up and can decrypt DVDs when attached to my Lubuntu Vivid Vervet machine. However, the same drive with the same disc fails to read when running on Crouton and VLC reports...

    libdvdnav: Using dvdnav version 5.0.3
    libdvdread: Attempting to use device /dev/sr0 mounted on /var/host/media/removable/PROPOSITION_DVD for CSS authentication
    libdvdread: Could not open /dev/sr0 with libdvdcss.
    libdvdread: Can't open /dev/sr0 for reading
    libdvdread: Device /dev/sr0 inaccessible, CSS authentication not available.
    libdvdnav: Can't read name block. Probably not a DVD-ROM device.
    libdvdnav: vm: dvd_read_name failed
    libdvdnav: DVD disk reports itself with Region mask 0x00fd0000. Regions: 2
    [00007f2f40005db8] core input error: ES_OUT_RESET_PCR called
    [00007f2f40005db8] core input error: ES_OUT_RESET_PCR called
    [00007f2f40005db8] core input error: ES_OUT_RESET_PCR called
    [00007f2f40005db8] core input error: ES_OUT_RESET_PCR called
    libdvdnav: Using dvdnav version 5.0.3
    libdvdread: Could not open /dev/sr0 with libdvdcss.
    libdvdread: Can't open /dev/sr0 for reading
    libdvdnav: vm: failed to open/read the DVD
    libdvdread: Could not open /dev/sr0 with libdvdcss.
    libdvdread: Can't open /dev/sr0 for reading 
    [00007f2f4800ae98] dvdread demux error: DVDRead cannot open source: /dev/sr0
    [00007f2f40006198] core input error: open of `dvd:///dev/sr0' failed

I have installed libdvdcss2 within my LXDE crouton build by running the standard libdvdread4 install-css script exactly as I did on Vivid Vervet. I've added my user account to the ```disk``` group in the hope that would unravel permissions problems and rebooted, but still no joy.

It is a promising test case for attaching an external DVD drive as the identical USB setup on a regular Lubuntu install works fine.

**Comment by cefn** [comment]
Here is the contrasting case in Vivid Vervet with the same device and disc...

    libdvdnav: Using dvdnav version 5.0.1
    libdvdread: Attempting to use device /dev/sr1 mounted on /media/cefn/PROPOSITION_DVD for CSS authentication
    libdvdnav: DVD disk reports itself with Region mask 0x00fd0000. Regions: 2
    libdvdread: Attempting to retrieve all CSS keys
    libdvdread: This can take a _long_ time, please be patient
    libdvdread: Get key for /VIDEO_TS/VIDEO_TS.VOB at 0x00000138
    libdvdread: Elapsed time 0
    libdvdread: Get key for /VIDEO_TS/VTS_01_0.VOB at 0x0000019c
    libdvdread: Elapsed time 0
    libdvdread: Get key for /VIDEO_TS/VTS_01_1.VOB at 0x0000027b
    libdvdread: Elapsed time 0
    libdvdread: Get key for /VIDEO_TS/VTS_02_0.VOB at 0x00026a13
    libdvdread: Elapsed time 0
    libdvdread: Get key for /VIDEO_TS/VTS_02_1.VOB at 0x00026a60
    libdvdread: Elapsed time 0
    libdvdread: Get key for /VIDEO_TS/VTS_03_0.VOB at 0x000286ca
    libdvdread: Elapsed time 0
    libdvdread: Get key for /VIDEO_TS/VTS_03_1.VOB at 0x00028717
    libdvdread: Elapsed time 0
    libdvdread: Found 3 VTS's
    libdvdread: Elapsed time 0

...although I doubt there are any significant clues there.

**Comment by tmagara** [comment]
I see this on my chroot.
```
$ ls -l /dev/sr0
brw-rw---- 1 root cdrom 11, 0 Jun 30 14:27 /dev/sr0
```
So, try this in your chroot
```
$ sudo usermod -a -G cdrom your_user_name
```
and log in to crouton again.
You should be able to play DVDs with this.

**Comment by cefn** [comment]
Hey thanks for the suggestion and it should have been obvious if I'd actually inspected the device node under ```/dev```

I succeeded at playing a DVD by adding myself to the cdrom group, then forcing a reload of my group memberships and launching VLC in a terminal as follows...

    sudo usermod -a -G cdrom myuser
    exec su -l myuser
    vlc

...where myuser is my user name. After that, I removed and reinserted the DVD. My LXDE desktop session prompted for password and asked how to load the DVD. I chose VLC and it used the already-running instance with the renegotiated permissions and played successfully, without even a reboot. Obviously after a reboot the group membership of ```cdrom``` will be there without fancy terminal stuff. 

I'll raise the issue of how to auto-mount drives without a password popup every time as a separate question.

**Comment by alangumer** [comment]
play DVD crouton - Ubuntu 14-04
sudo apt-get update
sudo apt-get install vlc

run install libdvd -- https://github.com/dnschneid/crouton/issues/1367
sudo apt-get install libdvdread4
sudo /usr/share/doc/libdvdread4/install-css.sh

give permission to your user to play DVD -- @cefn 
sudo usermod -a -G cdrom myuser
reload your user group
exec su -l myuser
run VLC
vlc
