### ISSUE TITLE
Basic commands missing from Crouton Terminal

### ISSUE THREAD

**Issue by JessBoctor** [dnschneid/crouton#1909]
Hi Everyone, 

Here is my setup: 
I am running a crouton chroot (trusty xfce) off a USB stick with my Toshiba Chromebook 2 set in Dev mode.

Update - here is my crouton version:

(trusty)root@localhost:~# croutonversion
crouton: version 1-20150617163120~master:5c73c9fd
release: trusty
architecture: amd64
xmethod: xiwi
targets: chrome,xiwi,xfce
host: version 7204.0.0 (Official Build) dev-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jun 24 05:17:42 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

I have been trying to set up my chroot to use with Vagrant and Virtualbox for a development environment. One of the problems I keep running into is that when I Google around for instructions, many of the commands don't seem to work. 

For example, when trying to install VVV from the github instructions here: https://github.com/Varying-Vagrant-Vagrants/VVV I can get as far as step 6. 
    git clone git://github.com/Varying-Vagrant-Vagrants/VVV.git vagrant-local
 when I try to run this command, I receive this error
    (trusty)phantomblonde@localhost:~$ git clone git://github.com/Varying-Vagrant-Vagrants/VVV.git vagrant-local
bash: git: command not found

I tried using sudo with this as well, and receive the same error. I have tried to log into the chroot as a root user, but when I do, I receive this error:

chronos@localhost / $ sudo sh /media/removable/vDev/bin/enter-chroot -u root
Password: 
Enter encryption passphrase for trusty: 
Entering /media/removable/vDev/chroots/trusty...
(trusty)root@localhost:~# startxfce4
Do not launch startxfce4 as root inside the chroot.

I have run into this problem with commands not being found in other instances too, for example -mv would not work when I tried to install files into my fonts folder. wget has also had issues. Those are just the two off the top of my head, and I have had this issue whether using a chroot found locally on my hd or on the USB. 

Is there a package I am missing or some permissions issue I need to resolve? 

Any help with this would be greatly appreciated.

Thanks!

Jess

**Comment by Tuxerito** [comment]
Git is not a basic command and you can install it from repositories
sudo apt-get install git

**Comment by JessBoctor** [comment]
Thanks @Tuxerito for the response. I will try again and post any errors I receive.
