### ISSUE TITLE
Closing apps - Xiwi

### ISSUE THREAD

**Issue by mikecsmith** [dnschneid/crouton#1910]
Hi,

I adore Crouton, thanks for all the work you've put into it.

I've played around with about 20 different chroots trying to find the setup which best suits me. I've settled on Xiwi running on Debian Jessie since this gives me everything I need, I run Jessie on my servers and the only graphical linux apps I need run well using Xiwi (Skype, Mudlet and Sublime Text). 

My only issue so far is closing the Mudlet app. With Skype and Sublime text there's a menu option to exit. For Mudlet unfortunately there's no menu option or shortcut key - which is a particular problem for mudlet since it saves its setting files on a graceful close. Checking the i3 docs it looks like you can close a window with $mod+Shift+q - but I'm unable to figure out how to execute this from within Chrome OS. 

I'm currently running Debian Jessie (although I've also tested this in Ubuntu Precise) - was wondering if any options are available for me?

Thanks,

Mike

**Comment by dnschneid** [comment]
The key you want is Ctrl+Alt+Shift+Escape.  It's unfortunately unintuitive...
