### ISSUE TITLE
depmod not found

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#1911]
I was building an Android kernel for the Nexus 4 so I am able to understand how to put `ubuntu-touch` on my Galaxy Nexus. While `make`ing the kernel, make responds with `depmod not found`. What do I need to do to install depmod/find it on my system?

**Comment by divx118** [comment]
Are you trying to build the kernel in a chroot made with crouton? If not you are asking it in the wrong place.  BTW depmod should live in /sbin `/sbin/depmod` 
General tip: Try to give some more details when asking questions for example exact error messages, what did you exactly do before the error occurs etc.

**Comment by firestar115** [comment]
Yes, building in a chroot.

On 7/1/15, Maurice van Kruchten <notifications@github.com> wrote:
> Are you trying to build the kernel in a chroot made with crouton? If not you
> are asking it in the wrong place.  BTW depmod should live in /sbin
> `/sbin/depmod`
> General tip: Try to give some more details when asking questions for example
> exact error messages, what did you exactly do before the error occurs etc.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/1911#issuecomment-117796346


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by tista500** [comment]
@firestar115 

To search the package what you want from files to be installed:
``$ dpkg -S depmod``
```
kmod: /sbin/depmod
kmod: /usr/share/man/man8/depmod.8.gz
kmod: /etc/depmod.d/ubuntu.conf
kmod: /etc/depmod.d
kmod: /usr/share/man/man5/depmod.d.5.gz
```

So all you need is to apt-get install **kmod**...

Regards.

**Comment by firestar115** [comment]
Temporarily closed, not working on project anymore.
