### ISSUE TITLE
Intel Driver issues with Broadwell 3205U Processor (C740/C910/CB15)

### ISSUE THREAD

**Issue by Voltron00x** [dnschneid/crouton#1912]
Some time ago when the Pixel 2015 was released an issue was logged noting numerous performance issues in 14.04 including but not limited to graphical glitches on the mouse cursor when swapping between Chrome OS and Ubuntu, and a variety of other problems. I personally experienced poor performance, constant crashes in XFCE, games with sound errors and poor performance not present in 13.04 and 14.04 on 2995U-powered Chromebooks, hanging and crashing when logged out/rebooting/powering off via Ubuntu, and more.

In that issue (see link below) a solution was posted referencing the updating of the Intel graphics drivers. The good news is that for the Intel HD5500 and up (Broadwell i3, i5 and i7) this solves the issues. In fact on my Pixel after using this, Unity 14.04 is ridiculously great and everything I've tried has worked incredibly well.

Sadly, it looks like this driver update does NOT update the 3205U "Intel HD Graphics" for the Broadwell Celeron. These systems are still not working well at all in Crouton. 

Those of us who are mere mortals over on Reddit have not been able to figure out a solution to this and I found it odd that it didn't seem to be covered here, thus I figured I'd post it in the event that a) this wasn't a known problem, or b) it was a known problem with a solution (fingers crossed).

Referenced issue, which is open but not quite in reference to what I've described, above:
https://github.com/dnschneid/crouton/issues/1519

**Comment by Fishwithadeagle** [comment]
Just came here to second this. I cannot get better performance out of the 3205u with updated mesa and graphics drivers. For example. Team Fortress 2 should run completely playable on this chipset as shown by similar windows computers, whereas in crouton, I am only able to pull around 20 fps w/freezing on low settings.  With these updated drivers, I am no longer able to switch to chromeos (black screen), but everything runs fine within crouton, requiring a completely shutdown and restart to get back to chromeos. I attached a pastebin link of what glxinfo states.

http://pastebin.com/nkAxXrmT

**Comment by raidencup** [comment]
https://github.com/dnschneid/crouton/issues/1915
