### ISSUE TITLE
Unable to launch chroot in Xorg

### ISSUE THREAD

**Issue by liapman** [dnschneid/crouton#1913]
Greetings!

I've recently reinstalled my chroot to add the xiwi functionality (I'm late to the party, I know).
Having Xubuntu applications running in windowed mode on Chrome OS is amazing! However, since there's no GPU acceleration on xiwi, and I do want to be able to play Warcraft 3 (:D), I need to be able to run my chroot the old way with Xorg.
I tried running "Sudo startxfce4 -X xorg", but that didn't work, I got:
      /mnt/stateful_partition/crouton/chroots/Mycroft does not contain XMETHOD 'xorg'
(Mycroft is the name I chose for my chroot)
Any advice would be much appreciated.

Daniel

**Comment by DennisLfromGA** [comment]
You can add 'xorg' to your chroot with an update, using something like:

`sudo sh ~/Downloads/crouton -t xorg -u [-n Mycroft]`

This method will also make 'xorg' your default xmethod so to use 'xiwi' you'll have to use the '-X xiwi' method when starting your DE, using something like:

`sudo startxfce4 -X xiwi [-n Mycroft]`

**Comment by liapman** [comment]
It worked! Thanks a bunch :).

**Comment by DennisLfromGA** [comment]
Cool, cool, cool! 
( You can close this issue now if you like... )
