### ISSUE TITLE
Change screen resolution

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#1916]
First of all, thank you David Schneider for making Crouton! :smile: I wouldn't have bought a Chromebook if it weren't for Crouton. I've been using Linux per default for about 10 years and no way I'm gonna use a crippled little OS like ChromeOS.

Now for my problem. I've been trying to get my [Toshiba Chromebook CB30] (http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/toshiba-cb30-chromebook) to display a higher resolution than 1366x786. It won't work w/ the `cvt` and the creation of a `10-monitor.conf` file in */usr/share/X11/xorg.conf.d/* like in [this Github Crouton Wiki entry] (https://github.com/dnschneid/crouton/wiki/Chromebook-Pixel). 

In ChromeOS I can set a "virtual" resolution of 1536x864. But in Linux Ubuntu 14.04 "Trusty Tahr" with Gnome 3 I cant seem to change the resolution. When I've edited the `10-monitor.conf` file then nothing seems to happen. Ubuntu starts up as usual in the 1366x768 mode. When I switch to ChromeOS to see if there are errors logged by the X-server then I see nothing special, i.e. no errors marked w/ (EE) or warnings marked w/ (WW). The X server seems not to care about my settings in `10-monitor.conf`.

Any ideas or suggestions?

Again thanks for making Crouton. I now have a fully fledged Linux machine w/ a battery life of ~10 hours! Try to beat that that for under 800 Dollars (i.e. Macbook or one of the more expensive Lenovo's).

**Comment by tista500** [comment]
@MeneerJansen How about removing `$HOME/.config/monitors.xml` (it's used as Gnome3's display config) ?

Regards.

**Comment by MeneerJansen** [comment]
Holy cow Batman! The `randr` tricks in #1336 did it for me! Thanks y'all for the tips! :smile:

**Comment by MeneerJansen** [comment]
Wait. After closing the lid of my Chromebook it awakes in the old resolution. Anybody got a tip on how to automatically run a command after suspend?

**Comment by tista500** [comment]
@MeneerJansen pm-utils still works for me (Vivid Gnome, systemd 204, Asus C200).

So how about this?

#### Install pm-utils
If you didn't have, install it.
    `sudo apt-get install pm-utils`

#### Create a file as `/etc/pm/sleep.d/90_chr_xrandr`

Don't forget to set **YOUR_NAME** in `username=`

```
#!/bin/sh
#
# 90_chr_xrandr: resume scaling on hibernate or suspend

# DBus method
dbus=$(ps aux | grep 'dbus-daemon' | grep 'session')
if [ ! -z $dbus ]; then
    username=$(echo $dbus | awk '{print $1}')
    userhome=$(getent passwd $username | cut -d: -f6)
    export XAUTHORITY="$userhome/.Xauthority"
    for x in /tmp/.X11-unix/*; do
        displaynum=$(echo $x | sed s#/tmp/.X11-unix/X##)
        if [ -f "$XAUTHORITY" ]; then
            export DISPLAY=":$displaynum"
        fi
    done
else
# Fallback method
    username= # add username here; i.e.: username=foobar
    userhome=/home/$username                                                      
    export XAUTHORITY="$userhome/.Xauthority"
    export DISPLAY=":1" # set as '1' instead of '0'
fi

# Actions
case "$1" in
    suspend|suspend_hybrid)
        # nothing to do
    ;;
    resume)
        # sample 1080p scaling for internal display of Intel graphics
        su $username -c "dbus-launch xrandr --output eDP1 \
            --scale 1.405x1.406 --fb 1920x1080 --panning 1920x1080"
    ;;
    *) exit $NA
    ;;
esac
```

And then add executable:
    `sudo chmod +x /etc/pm/sleep.d/90_chr_xrandr`

#### Reboot and test
After rebooting, unplug AC and close/open the lid, could it keep your scaling?

Regards.

**Comment by MeneerJansen** [comment]
On my machine it does not work. When Ubuntu puts my Chr.book to sleep there's no problem. But when I close and open the lid then my desktop small part of the screen (i.e. not zoomed in). I've made a shell script the execute the screen resolution command and I've set a shortcut key. When I open the lid I log in and press "CTRL + R" .

**Comment by tista500** [comment]
Ah I've found this error on gnome-settings-daemon 3.16:
```
power-plugin-WARNING **: Unable to inhibit lid switch: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Operation not permitted
```
If you've got same, chroot's pm-utils might not work properly. For me, I don't go suspend with closing lid but budgie-desktop session-dialog... Yes, lid actions may hook ChromeOS's power-management earlier than chroot's one.

So ChromeOS's *powerd* may be potentially related to this issue, I would check `croutonpowerd -i` out to track this issue down...

Regards.
