### ISSUE TITLE
I can't start Ubuntu from my Chromebook.

### ISSUE THREAD

**Issue by TheGlamourGroup** [dnschneid/crouton#1917]
I put in sudo startunity in the crosh shell. I get some weird error with a bunch of (EE) though. I'm not sure how to right click or copy from the crosh shell, as it won't let me, but if you can tell me i'll be able to post exactly what it says. Thanks.

**Comment by SteveAdams86** [comment]
you could try to update it if you have recently updated chrome os

sudo sh -e ~/Downloads/crouton -u -n trusty

**Comment by giliammc** [comment]
pleas post the output of the commands

**Comment by giliammc** [comment]
instead of using the crosh shell do this

(ctrl+alt+t) type shell then enter sudo startunity 
highlight the output then use keyboard shortcut (ctrl+shift+c)

**Comment by TheGlamourGroup** [comment]
its ok i fixed it. it turns out i accidentally got out of developer mode.

**Comment by giliammc** [comment]
great!
you should close the issue

**Comment by TheGlamourGroup** [comment]
how do i do that?

**Comment by giliammc** [comment]
Push the comment and close button
