### ISSUE TITLE
Concise way to fix Meta and Alt keys in Trusty?

### ISSUE THREAD

**Issue by JoshMcCullough** [dnschneid/crouton#1919]
I've read #953 and the related documentation but still don't quite get how to fix the key mapping. I'm using Trusty/Unity.

Running unity in Xiwi, it appears that `Alt` is mapped to `Super` as it opens the launcher when pressed.

Running an app in Xiwi, it appears that `Alt` is mapped to ... `Alt` as it highlights the menu keys when pressed.

Search appears to not be mapped to anything, ever, nor does it show anything when pressed in `xev`.

**So...**

How do I make `Alt` behave like normal, and have the Search buttton be the Super button?

**Comment by MeneerJansen** [comment]
You might have accidentally set an shortcut key wrong. In Gnome 3 I can set these via the 'All Settings' window. Then I choose "Keyboard => Shortscuts". Your problem might be in the category 'System' where you can set shortcut keys for the 'Overview' etc.

Good luck! :)

**Comment by JoshMcCullough** [comment]
The only shortcuts I have in the System category are "Log Out" and "Lock Screen". And the search key is definitely not mapped to anything, certainly not Super. I haven't changed the keyboard shortcuts.

**Comment by MeneerJansen** [comment]
I have no experiende w/ Xiwi (is that running Linux inside a window in ChromeOS?). However the following quote from you speaks volumens to me:

> Search appears to not be mapped to anything, ever, nor does it show anything when pressed in xev.

If it doesn't show up in `xev`then I do not know of any tricks to (re)map said key. I'm sorry.

[edit] I run Ubunty w/ Gnome 3 in "full screen" in a chroot. And on my machine the Search key from the Chr.book doesn't show up in `xev` either. It does open the "open applications" show though. I might post my `xmodmap` shell script here, if somebody wants me to, which maps Ctrl + Alt to the context menu, Alt_R to the compose key, Alt_R + Up to page up, etc., etc.

**Comment by dnschneid** [comment]
It's definitely something configured wrong in Unity...check the keyboard layout configuration screen (not the shortcut screen).  Are you running xiwi full-screen?  Does search get passed when you're in full-screen?

**Comment by JoshMcCullough** [comment]
@dnschneid Not sure where the other keyboard layout screen you're referring to is, or how to get to it. All I can seem to find is the Keyboard settings applet. Also, the search button appears to do nothing, in full-screen mode or otherwise. Thanks!
