### ISSUE TITLE
SD Card

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#1920]
I'm having a hard time getting write access to my EXT2 formatted SD card. Wanted to move my home dir to it w/ this tutorial: https://help.ubuntu.com/community/Partitioning/Home/Moving

But every time I re-insert my SD card the ownership gets all messed up. Might that be ChromeOS demanding to "do" something w/ MY sd-card (eg. mount it as root or something...)? only want Linux to do things with it...

I'd like to use the internal 16 GB for my system (speed!) and the SD card for my home dir.

**Comment by MeneerJansen** [comment]
Something is very, very wrong w/ external media and (my) chroot. After suspend (i.e. closing the lid)  I cannot delete my own files and folders! Neither in ChromeOS nor Linux.

Will investigate some more. Would appreciate it very much if somebody could clarify...

**Comment by MeneerJansen** [comment]
I've set my Linux chroot to NOT auto-mount media: ChromeOS already does that. I've done it this way:

1. sudo dconf-editor

2. Browse to org.gnome.desktop.media-handling and disable automount (and automount-open)

3. Do that both as root and "yourself".

Seems read/write to the SD card works now.

**Comment by MeneerJansen** [comment]
There's no recycle bin on the SD card. Might be possible to create one...

**Comment by dnschneid** [comment]
What ownership changes are you seeing?  If you cd into the directory and `touch test` is there an error output?

**Comment by MeneerJansen** [comment]
@DNSchneid: thank you for the reply. By disabling automount in my Chroot and adding a directory on the SD card for my documents the problems disappeared. The "problem" w/ the disappearing mouse pointer in ChromeOS might not be a bug but a feature. After pressing Esc a few times and rubbing the mouse pad the mouse appeared again.
