### ISSUE TITLE
Update & Backup fail; chrootlink broken

### ISSUE THREAD

**Issue by ecollins** [dnschneid/crouton#1921]
I've got a trusty chroot that's been updated a few times in the past. No doubt I broke something to cause the following, but help would be appreciated.  
**tl;dr: /usr/local/chroots is gone. What do I do now?**

I typed: 

sudo sh -e ~/Downloads/crouton -n trusty -u

And get the message:

Migrating data from legacy chroots directory /usr/local/chroots to /mnt/stateful_partition/crouton/chroots...
There is data in both /usr/local/chroots and /mnt/stateful_partition/crouton/chroots.
Make sure all chroots are unmounted, then manually move the contents of
/mnt/stateful_partition/dev_image/chroots to /mnt/stateful_partition/crouton/chroots.

I wanted to back up my chroot to an external drive first, but: 
sudo edit-chroot -b trusty instantly reported it was finished after writing an empty (182 byte) .tar.bz file. So forging ahead with my faith in Dropbox, I did what I thought I was being told to do:

sudo mv /mnt/stateful_partition/dev_image/chroots /mnt/stateful_partition/crouton/chroots

crouton/chroots still has my chroot, but /usr/local/chroots is gone, so naturally:

sudo sh -e ~/Downloads/crouton -n trusty -u
/usr/local/chroots not found.
/usr/local/chroots/trusty does not exist; cannot update.
Valid chroots:

What do I do to get my chroot back and update?

**Comment by dnschneid** [comment]
Try `sudo ln -s /mnt/stateful_partition/crouton/chroots /usr/local/`

**Comment by ecollins** [comment]
Should've responded earlier. This worked. Thanks!

**Comment by dnschneid** [comment]
Also, I think this is fixed in the latest crouton (it shouldn't get into this state anymore).
