### ISSUE TITLE
When tried to download the audio driver, failed to do so.

### ISSUE THREAD

**Issue by JonahWong** [dnschneid/crouton#1922]
Below is the log I get from crosh terminal window.

Installing target audio...
Fetching CRAS (branch 67bd57ff79c7c7fab538612654ab8070675d35ff)...
--2015-07-05 16:56:57--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 74.125.200.82
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

--2015-07-05 16:59:06--  (try: 2)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

--2015-07-05 17:01:15--  (try: 3)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

--2015-07-05 17:03:25--  (try: 4)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

--2015-07-05 17:05:36--  (try: 5)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

--2015-07-05 17:07:49--  (try: 6)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

--2015-07-05 17:10:02--  (try: 7)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

--2015-07-05 17:12:16--  (try: 8)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/67bd57ff79c7c7fab538612654ab8070675d35ff.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... failed: Connection timed out.
Retrying.

I have tried all sorts of methods, changed many IP for chromium.googlesource.com, still the problem remains.

Any ideas?

**Comment by tista500** [comment]
@JonahWong Google products have blocked 443 port via http but https would be OK to connect...:( If you could, please try some accesses via "proxy" since your network might cause this issue.

Regards.

**Comment by tonyxue** [comment]
@JonahWong From looking at your username, I guess you're living in a mysterious place where Google is blocked, am I right?

There are two solutions:

1. Get yourself a VPN setup in Chrome OS
2. Find a IP here https://github.com/racaljk/hosts. Or you can try other repos but this one is the most actively updated one.
