### ISSUE TITLE
Black screen freeze on startx after update

### ISSUE THREAD

**Issue by JohnAllanSmith** [dnschneid/crouton#1923]
Hello, after I did my update sh crouton -u -n jessie, I can no longer startx. The upgrade itself seemed to have gone well, and my original arch was xorg.   Now I get a black screen freeze when I enter my chroot and do startx. Switching back doesn't work, and I need to do a hard power off.

Is there any way to get this fixed??

Chrombook: Toshiba Chromebook2

**Comment by SpafinDoople** [comment]
I have had this problem too. I tried all I could do, and in the end, I reinstalled Linux. :(

**Comment by JohnAllanSmith** [comment]
I tried to delete my chrooted environment and reinstall everything, still the same. Black screen. After waiting for 10mins or so, I get this prompt. Can anyone please advice how to get this working?


(jessie)john@localhost:~$ startx 

X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.10.18 #1 SMP Sun Jun 21 18:01:01 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashtree=PARTUUID=53f1dd78-d512-d54e-ab32-e6551aaac164/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=ff1ce997c6e143f695e40de3219616aac22b951e salt=0d0c94b94596e196ff469af0ff0fb0118b3075ba88e35eed80ab5d03cb20b234" noinitrd vt.global_cursor_default=0 kern_guid=53f1dd78-d512-d54e-ab32-e6551aaac164 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 11 February 2015  12:32:02AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Jul  8 12:17:39 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
xf86: found device 0

waiting for X server to begin accepting connections .
..
..

..
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

/usr/bin/xinit: server error
Couldn't get a file descriptor referring to the console
(jessie)john@localhost:~$

**Comment by MeneerJansen** [comment]
I start the graphical user interface (GUI), xorg, in Ubuntu w/ the Gnome3 desktop via the special command for Crouton:
`
sudo startgnome
`
You start it w/ the command `startx`. Is that the recommended way for Debian (Jessie) in the chroot on your Chromebook? Could you try `sudo startxfc4` or `sudo startgnome`?

**Comment by fuzetsu** [comment]
I'm having the same problem, neither xiwi nor xorg will work. It "waits for X server to begin accepting connections" and eventually gives up. 

Reinstalling hasn't helped, I even tried going back to the stable channel from the beta. 

Right now I'm testing with only the keyboard and xiwi targets on trusty. I'm not using `sudo startxfce4` or `sudo startgnome` because I didn't install a desktop environment, only i3 as the window mangager.

**Comment by cosine** [comment]
Hi, I have this issue as well with an Acer CB3-111-C8UB using a Debian Sid flavor chroot. My window manager is i3, so I also use "startx" normally to enter the chroot.

I have not tried waiting as long as 10 minutes to see if startx/xinit will give up, as @JohnAllanSmith did. I'm going to try that.

I'm also game to try startxfce4 when I have a chance to install it later, but I am skeptical that it does anything significantly different other than also starting xfce.

**Comment by fuzetsu** [comment]
@cosine have you tried using the `xinit` command. I was only able reproduce the issue using `startx`, `xinit` works fine.

**Comment by dnschneid** [comment]
I've never gotten `startx` to work reliably in crouton.  Use `xinit` instead.

**Comment by cosine** [comment]
Yeah, `xinit` did work for me. I did have some debugging information to report last week, but I misplaced it and it's not worth pursuing with the available workaround. I do not know which update broke `startx` anyway, which did work when I initially created this chroot 3-4 months ago.
