### ISSUE TITLE
Computer Crashes when using Wine

### ISSUE THREAD

**Issue by Judecca** [dnschneid/crouton#1925]
Right so here's the deal... I currently have an Acer Chromebook 11 (CB3-111) running Ubuntu Trusty via the latest version of crouton.

I downloaded Wine in order to use the VBA emulator (the Windows version because the Linux one is so outdated) from here: http://www.emulator-zone.com/doc.php/gba/vboyadvance.html

I read all the information regarding the use of the program via Wine located here: https://appdb.winehq.org/objectManager.php?sClass=version&iId=3730&iTestingId=86154

These are my symptoms:
When playing games (just double clicking the .exe), it would run fabulously fine until after 10 minutes where computer's audio would stutter, image would freeze (mouse wouldn't move, keyboard was unresponsive) *then* the screen would just turn off, sound would sometimes continue to stutter or sometimes it would just turn off all together (yet the lights on the laptop would indicate it's still on). Simply put, the computer would crash. 

The only way to get out was via hard reboot (esc + refresh then power button) The computer would boot up and sometimes work as normal. 

Notes: 
-Running dual screens via HDMI to VGA Adapter
-No other apps were running at the time of the crash. 
-Audio Jack was being used. 
-Crashes would still occur even if my laptop wasn't connected to anything.

**Also,** enfasis on *computer would boot up and sometimes work as normal*. What would happen (And its starting to become frequent) is that the computer would crash, I would reboot it but the time it takes to reboot is faster than usual. The Chrome animation would just zip and my login screen would show, where I would put in my password and then the screen would go black, the backlight of the screen seems to flash and then show up to the login screen again; it can't login and loops back into the login screen. Guest mode is alright though. This second issue also worries me and I'm not sure if it's related to Wine crashing my laptop or not. I cannot (or just simply don't know how to from guest mode) access my files at all therefore making them unrecoverable. I would have to tap spacebar at the boot in order to wipe my laptop and start anew. 

What can I do? 

**PS.** Output of sudo enter-chroot -n chrootname croutonversion

chronos@localhost / $ sudo enter-chroot -n trusty croutonversion
Password: 
Enter encryption passphrase for trusty: 
Entering /usr/local/chroots/trusty...
crouton: version 1-20150620222151~master:89796a99
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 6946.63.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Sun Jun 21 17:59:52 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /usr/local/chroots/trusty...

**Comment by tista500** [comment]
@Judecca I'm not sure what's the reason for crashing (seems like overload) though, but if you had pulseaudio as default sound server, please check your settings:

Open the file with some editers:
`sudo nano /etc/pulse/default.pa`
Then see around line no.54 to 56, A section of "autoloading via udev":

```
 ### Automatically load driver modules depending on the hardware available
.ifexists module-udev-detect.so
load-module module-udev-detect
.else
### Use the static hardware detection module (for systems that lack udev suppor$
load-module module-detect
.endif
```
So add `tsched=0` (means *disable timing scheduling*) like this:
```
load-module module-udev-detect tsched=0
```
If the timing scheduler was set as "disabled", pulseaudio's load-averaging would be reduced dramatically. After save and exit, do rebooting your machine to reload pulseaudio properly.

Anyway I don't know whether pulseaudio might cause the CPU load or not, with further say, CPU load might do crash or not...

Regards.

**Comment by Judecca** [comment]
Done. Still crashing. It doesn't seem to be PulseAudio

**Comment by tista500** [comment]
OK. So I now think this issue might not be related to crouton, but there's something to do.

By the way, gnawty is Acer CB3-111? Oh it has same BayTrail-M what I have. Then I've found that our BayTrail-M has ETC support by default on OpenGL already: http://cgit.freedesktop.org/mesa/mesa/commit/?id=8618407d15ead94358ccd691f598ca1c76c46385&utm_source=anzwix

ETC is famous as *S3 Texture Compression* of open-source. It would be useful for games, videos, and some visual works. If so, this S3TC may solve the heavy graphics loading issue, maybe...

I've created config file to force enabling S3TC on DRI:
```
<driconf>
    <device screen="0" driver="i965">
        <application name="Default">
            <option name="force_s3tc_enable" value="true" />
        </application>
    </device>
</driconf>
```
Copy & paste this as `$HOME/.drirc`, then reboot. Please give it a try.

Regards.

**Comment by tista500** [comment]
Forgot to mention. If you haven't tried, you'd better to run `croutonpowerd -i` to inhibit ChromeOS's powerd (power-management daemon). The powerd sometimes interrupt us.

Regards.

**Comment by Judecca** [comment]
Done and done. 
![screenshot - 071015 - 23 28 37](https://cloud.githubusercontent.com/assets/10791082/8632352/32f3f754-275c-11e5-9ed8-8838404dd642.png)


I played for about 15 mins then crashed again..... Also, it seems to work for a random amount of time but in general, after this, it seemed to take longer to crash.

**Comment by Judecca** [comment]
So I got " locked out" (AGAIN), can't log into my chromebook and I'm only in a login loop. (exactly what I mentioned above) 

https://goo.gl/WMweqU says just a powerwash but how could I recover my data before powerwashing? I really want to recover my documents in my downloads folder.... 

Also, I'm in guest mode and this is what popped up in my screen 
![screenshot 2015-07-21 at 10 30 33 am](https://cloud.githubusercontent.com/assets/10791082/8805333/4fa63dc0-2f96-11e5-840d-2affc5007202.png)

**Comment by drinkcat** [comment]
Looks like a kernel bug? Old bug though, please reopen if this is still an issue.
