### ISSUE TITLE
entered chroot fine, but no graphics screen?

### ISSUE THREAD

**Issue by nguyenlau** [dnschneid/crouton#1927]
I googled around but couldn't find an answer. Let me know if this is not the right place to ask.

I've been using elementary OS via crouton for several months on my Acer C720P CB.  Today, after I updated updated, I couldn't get to the eOS screen anymore.  I updated crouton, but it didn't help.  I entered as normal, and it comes back with normal message that it has entered, but I don't get the normal eOS graphics window.

chronos@localhost / $ sudo enter-chroot -n precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)lau@localhost:~$ 

and nothing happens, control-shift-alt-left/right doesn't get me to any other screens.  I've used eOS on crouton for several months now and this has never happened before.  Any suggestions would be greatly appreciated.  Thanks!

**Comment by DennisLfromGA** [comment]
Tell us what `sudo edit-chroot -l precise` displays.
Also, are you using the `startelementary` scripts outside and inside the chroot like the guide creates?

**Comment by nguyenlau** [comment]
@DennisLfromGA , thanks for the reply. Yes, I'm using the scripts as specified, but I'll reread the guide. Here is the output from the edit-chroot:

crosh> shell
chronos@localhost / $ sudo edit-chroot -l precise
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150620222151~master:89796a99
release: precise
architecture: amd64
xmethod: xorg
targets: xfce,keyboard,extension
host: version 6946.63.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jun 21 16:19:28 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
@nguyenlau - Thanx for the croutonversion output.
> I entered as normal...

So by that you mean - `sudo startelementary` is no longer working?
You could try it inside the chroot using something like this - `sudo enter-chroot startelementary` and see if that helps.

**Comment by nguyenlau** [comment]
@DennisLfromGA - Thanks for your help. Based on your suggestions, I experimented more with different combinations and I got my old desktop and state back.  If I enter the chroot first, then 'sudo startelementary', I get a different eOS desktop and state, like the original one before I installed packages.  If I startlementary straight from the chronos shell, without entering chroot first, then I get my desktop and state back.  If you have time to explain why, I'd appreciate it, as I'm not familiar with chroots. But for now, I'm OK and glad to have my desktop and x-window back.  Thanks again!

**Comment by DennisLfromGA** [comment]
Outside the chroot in crosh, the command should be: `sudo startelementary ...`
Inside the chroot, the command should just be: `startelementary` - no 'sudo' is needed nor wanted.

> I get a different eOS desktop and state

That's because prefixing 'startelementary' inside the chroot with sudo causes it to open up a 'root' desktop session, not the user you logged in as. It's a totally different environment and won't have or know about your user settings.

If it's working for you, I would just use `sudo startelementary` from crosh, outside the chroot per normal.

**Comment by DennisLfromGA** [comment]
One other thing, if you did use 'sudo' inside the chroot, your permissions maybe a little messed up in your HOME directory. If some things are failing to open or you're getting 'permissions' errors, you may need to do this:

1. `sudo enter-chroot`
2. `sudo chown -R 1000:1000 "$HOME"`

That'll reset the permissions back to normal for the logged in user.

**Comment by nguyenlau** [comment]
Thank you so much.  It makes sense.  I will close this now.  Really appreciate your assistance!

**Comment by DennisLfromGA** [comment]
No problem, glad it's working again. :+1:
