### ISSUE TITLE
Xiwi

### ISSUE THREAD

**Issue by jakman** [dnschneid/crouton#1928]
dnscheind or other,

I want to be able to integrate my linux environment with chrome.
I have installed Ubuntu using Crouton and have created a Chroot. I think I messed up because I didn't add xiwi to the list of targets. Do I need to completely reinstall or is there a way to add after install?  I am using Unity.

Thank you,

Jeff K

**Comment by DennisLfromGA** [comment]
@jakman - 

> Do I need to completely reinstall or is there a way to add after install?

Nope, just update your chroot and add the 'xiwi' target at the same time using something like this -

`sudo sh ~/Downloads/crouton -t xiwi -u [-n chrootname]`

This will also make 'xiwi' the default xmethod.

Now you can start your DE with -

[In a window] `sudo startunity`
[Full screen] `sudo startunity -X xiwi-fullscreen`
[In a tab] `sudo startunity -X xiwi-tab`

or, to go back to an 'xorg' chroot, use -

[XORG] `sudo startunity -X xorg`

**Comment by jakman** [comment]
Thanks Dennis...I'll give it a try!!

Jeff

**Comment by jakman** [comment]
Tried updating xiwi but got this error:

(precise)jakman@localhost:~$ sudo sh ~/Downloads/crouton -t xiwi -u -n precise_amd64
Downloading latest crouton installer...
/home/jakman/Downloads/crouton: 62: /home/jakman/Downloads/crouton: curl: not found
Failed to download crouton installer.
Check your internet connection or proxy settings (-P) and try again.

My internet connection from the linux desktop is fine in a browser.

Jeff

**Comment by DennisLfromGA** [comment]
@jakman - Exit your chroot and try again, it needs to be run in crosh.

**Comment by jakman** [comment]
Someone else helped me get curl and xiwi installed...I think...because this was at the bottom:

mount: Too many levels of symbolic links
WARNING: Unable to register core dump handler.
mount: special device /var/run/shill does not exist
Unmounting /usr/local/chroots/precise_amd64...

Also, I tried this command as recommended and got this error:

chronos@localhost / $ sudo mount -o bind /proc /var/chroot/proc
mount: mount point /var/chroot/proc does not exist

**Comment by DennisLfromGA** [comment]
@jakman - If you know what you're doing then, by all means experiment. If not, then I'd suggest sticking to the tried and true methods documented in the [README](https://github.com/dnschneid/crouton/blob/master/README.md) and elsewhere on this site.

At this point, I would recommend that you reboot your Chromebook, log in with your Google credentials, press <kbd>Ctrl+Alt+t</kbd>, enter 'shell', then do:
`sudo sh ~/Downloads/crouton -t xiwi -u -n precise_amd64`

**Comment by giliammc** [comment]
@DennisLfromGA  using xiwi in a tab is so useful i had no idea you could do that

**Comment by mark-hahn** [comment]
> using xiwi in a tab is so useful

I loved it until I found out it couldn't cut/paste to the rest of the
system.  I have an issue posted for this.

**Comment by giliammc** [comment]
it works fine for me

**Comment by mark-hahn** [comment]
I'll try it again,  It worked only once for each new tab for me.  There was
a work-around to paste into the url bar and then copy from there.

**Comment by mark-hahn** [comment]
I downloaded the latest and it doesn't work at all.  See #1598

**Comment by tedm** [comment]
@mark-hahn working for me with vim in trusty to/from gmail and other non-chroot windows, but I haven't updated for a week or two.

**Comment by tedm** [comment]
try installing a de, even if you don't use it, xfce only uses a few bits...

**Comment by mark-hahn** [comment]
I closed #1598.  Spoiler alert, the last comment is ...

"Now it seems to work everywhere.  Either the problem is intermittent or happens on the first testing".

So ignore my comments here.

**Comment by tedm** [comment]
So who's going to the #CroutonLinuxCon breakout session in Seattle next month?

**Comment by tedm** [comment]
It's in the #AARP wing of the Sheraton.

**Comment by mark-hahn** [comment]
What conference is that?

**Comment by tedm** [comment]
Possibly a part of this one: http://linuxplumbersconf.org/2015/ Don't let the filled up thing bother you, just flash your AARP card ...

**Comment by mark-hahn** [comment]
>  just flash your AARP card ...

How dare you assume I'm old.  Well, actually I'm very old, but still ...
 :-)

**Comment by dnschneid** [comment]
was not invited D:
