### ISSUE TITLE
error: target string not available

### ISSUE THREAD

**Issue by troymz** [dnschneid/crouton#1931]
hello. ive installed crouton on my chromebook pixel 2 i7
sudo sh -e ~/Downloads/crouton -r trusty -t unity,touch,xiwi

it works at first, i update intel drivers, install software center, install google chrome, install kodi. still works after reboots. then an update came up in ubuntu, i updated and now i get this:

Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150620222151~master:89796a99
release: trusty
architecture: amd64
xmethod: xiwi
targets: unity,touch,xiwi
host: version 6946.70.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Tue Jul 7 18:14:48 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.
Hangup

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

i have no idea what causes this.  im still learning ubuntu so im not a pro. very much a beginner.

**Comment by tista500** [comment]
@troymz Did you already try to update crouton on crosh window? `sudo sh ~/Downloads/crouton -u -n trusty`

Regards.

**Comment by troymz** [comment]
Yes I did. It's showing the latest croutob

**Comment by tista500** [comment]
OK. so https://github.com/dnschneid/crouton/issues/1490#issuecomment-80147622 could help? (I don't know how xiwi runs though...)

Regards.

**Comment by ironmanwaring** [comment]
I've been getting the same issue lately.  After searching in vain through the other issues, I ended up powerwashing and starting from scratch.  It worked the first couple of times yesterday, this morning I turned on the computer and it stopped working again, same issue :(

**Comment by troymz** [comment]
@tista500 i tried that command, it broke my chroot. i just reinstalled my chroot and it is still giving same error. i dont understand. ive tried powerwashing. same errors

**Comment by tista500** [comment]
Greetings,

It might be better to follow this issue: https://github.com/dnschneid/crouton/issues/1519 Because they're talking about new Pixel and intel driver, however, I don't know they're talking about xiwi or freon...

If you don't mind, how about using freon?

Regards.

**Comment by troymz** [comment]
i dont know what freon is. i followed a guide about xiwi to get it in its own window to avoid having to do alt+shift+ctrl+back.  but i will take a look at that issue

**Comment by troymz** [comment]
i dont have an issues with a black screen.  i have tried updating my intel drivers from download.01.org.  nothing seems to work.

**Comment by dnschneid** [comment]
You don't need updated intel drivers for xiwi.  Does updating your chroot complete successfully?  What's the output of `sudo edit-chroot -al`?
