### ISSUE TITLE
Mouse on top edge of screen triggers Chrome "full screen message" in crouton window

### ISSUE THREAD

**Issue by chilldude** [dnschneid/crouton#1933]
I understand this is a security feature in chrome, but I was wondering if this feature could be disabled when running a fullscreen crouton window via the chrome extension.

**Comment by giliammc** [comment]
i have the same issue and would like to disable it

**Comment by dnschneid** [comment]
Can't be disabled, sorry.  If you usually run full-screen, you may want to consider switching to the `xorg` target for X11.
