### ISSUE TITLE
USB stick keeps being remounted by Chrome OS?

### ISSUE THREAD

**Issue by promanczuk** [dnschneid/crouton#1936]
Hi,

I do not know whether that's the right forum, but I am kind of desperate after not finding any solution for my problem.

I have a running crouton/trust install on my Acer C720 and try to use PlayOnLinux to install some Blizzard games using the battle.net client from which different games can be installed. I did it many times on different linux systems. A first test on the chromebook/crouton/trusty combo with installing on the internal SSD worked fine. However due to space limitations, I decided to reinstall them on an external USB drive (ext4 parition), by moving the default wineprefix folder, where all the data is saved, and creating a symbolic link to the new location, e.g. /media/removable/USB\ Drive/wineprefix.

After setting the rights and remounting the stick with  exec option it seems to work at first. However, during installation of a game from the battlenet client, which involves typically several GB of download,  the installation/download stalls at some point. Apparently for some reason the device gets remounted. This causes a corruption of the virtual drive and the whole installation is broken. 

It also appears that the device of the drive changes from sdb1 to sdc1. It seems that for some reason the drive briefly disconnects at least I see the corresponding notification in Chrome OS, that I removed the drive without un-mounting, followed by new drive connected . Editing the fstab within trusty to try to mount the drive by the UUID does not work. Well, I know thet Chrome uses udev but I never looked into that... :)

I certainly do not seem to understand the management of the drives in Chrome OS and the relation to the chroot but is there a simple way for a "permanent" mount of the drive to point in the filesystem accessible by the chroot, which could fix this issue? 

Thanks a lot in advance.

**Comment by promanczuk** [comment]
Here the output of dmesg at the time when USB disconnects for unknown reason, to me could it be related to power managment?

203.432351] EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: (null)
[  231.353475] EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: (null)
[  673.191557] usb 2-1: USB disconnect, device number 2
[  677.853838] usb 2-1: Disable of device-initiated U1 failed.
[  678.357079] usb 2-1: device not accepting address 2, error -22
[  679.915242] hub 2-0:1.0: Could not enable port 1 after 1500 ms
[  680.772176] usb 2-1: device not accepting address 2, error -22
[  682.330248] hub 2-0:1.0: Could not enable port 1 after 1500 ms
[  683.187138] usb 2-1: device not accepting address 2, error -22
[  684.745253] hub 2-0:1.0: Could not enable port 1 after 1500 ms
[  685.602119] usb 2-1: device not accepting address 2, error -22
[  687.160196] hub 2-0:1.0: Could not enable port 1 after 1500 ms
[  689.072836] hub 2-0:1.0: Could not enable port 1 after 1500 ms
[  689.432393] sd 2:0:0:0: [sdb] Unhandled error code
[  689.432404] sd 2:0:0:0: [sdb]  
[  689.432410] Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK
[  689.432419] sd 2:0:0:0: [sdb] CDB: 
[  689.432425] Write(10): 2a 00 02 84 4a 58 00 00 08 00
[  689.432463] end_request: I/O error, dev sdb, sector 42224216
[  689.432473] Buffer I/O error on device sdb1, logical block 5277771
[  689.432488] EXT4-fs warning (device sdb1): ext4_end_bio:317: I/O error writing to inode 1305677 (offset 0 size 4096 starting block 5278028)
[  689.432546] Aborting journal on device sdb1-8.

and then a lot ext4 errors...However, I see nothing which would point to the reason.

**Comment by promanczuk** [comment]
Well after a lot of trying, I found a reason completely unrelated to Chrome OS/Crouton. It appears to have been caused by a loose power contact, which apparently lead to brief disruptions in the power supply switching between plug and battery power. So in a widest sense it was a "power managment" problem. However after fixing it no remounts so far. Finger crossed.....

**Comment by promanczuk** [comment]
Hi, although I closed this particular issue. It was actually experiencing the problem with the random remounts by Chrome OS also without a loose power contact. See my comment in [Issue #575](https://github.com/dnschneid/crouton/issues/575#issuecomment-123130458)

So it seems to be an issue within Chrome OS.  I will try to figure out what exactly is happening, if it happens again.

**Comment by gregnwosu** [comment]
I see this when the chromebook goes into suspend, on remount the exec bit isnt set so i have to manually remount

**Comment by Oliver84** [comment]
Have you tried running this? 
echo 1 | sudo tee /sys/bus/usb/devices/power/persist

You may need to specify the device number before the /power/persist
