### ISSUE TITLE
sudo startxfce4 fails on Tegra K1 HP G3

### ISSUE THREAD

**Issue by ChillingSilence** [dnschneid/crouton#1937]
Hi there,

Have tried setting up two new chroots, neither of them worked. Started with jessie, then tried trusty.
Grabbed the latest crouton installer as of ~6 hours ago, and installed the Chrome Plugin from the market / store whatever

Here's a pastie output of the error when trying to launch it:
http://pastie.org/10289174

Searching through some other issues here mention reinstalling xorg, that didn't work either.
Any suggestions on where-to from here? When I click on the Crouton extension in Chrome it'll show it connects for a split second then stops.

Cheers

**Comment by Doub1e-D** [comment]
If you install the crouton intergration extension ( https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom ) from the chrome webstore it will open the desktop envirement in a chromeOS browser window. And you should be good!

**Comment by ChillingSilence** [comment]
Thanks, that's the extension that I already have. As mentioned when I click on that, it shows that it's connected for a split second but then reverts back to "Disconnected".

Any other suggestions ?

**Comment by giliammc** [comment]
try running "sudo startxfce4 -X xorg
and see what happens

**Comment by DennisLfromGA** [comment]
@giliammc - Just looking at his [pastie](http://pastie.org/10289174) link, it doesn't appear that he has 'xorg' installed.

**Comment by giliammc** [comment]
@DennisLfromGA  @ChillingSilence  sorry what i meant was you could try installing xiwi and see if that works

**Comment by DennisLfromGA** [comment]
@giliammc - He *already* has 'xiwi' installed, that's what he's using.

**Comment by giliammc** [comment]
sorry not xiwi xorg

**Comment by DennisLfromGA** [comment]
Well, this back and forth may be all in vain since there seems to be a 'chilling silence' from the OP here... ;-)

**Comment by giliammc** [comment]
Teehee!

**Comment by partyewok** [comment]
He might be but I haven't found any solution in my case (same problem). Some advice by the OP?

**Comment by dnschneid** [comment]
@drinkcat more xiwi connection issues?

**Comment by alfieoriginal** [comment]
Hello, same issue here with nvidia k1. Nyan_blaze build.
http://pastie.org/10446381

**Comment by alfieoriginal** [comment]
Hello, Is this still considered as a bug? any progress made?

**Comment by alfieoriginal** [comment]
Xiwi connection issue is still present in ARM.
http://pastebin.com/WaNRc5qd

**Comment by alfieoriginal** [comment]
Is there any progress with this bug??

**Comment by partyewok** [comment]
@alfieoriginal there is a suggested "hotfix" there: https://github.com/dnschneid/crouton/issues/1976
