### ISSUE TITLE
X11 Fails to Start (Chromebook Flip C100, 45.0.2439.4 dev)

### ISSUE THREAD

**Issue by aarossig** [dnschneid/crouton#1938]
I am unable to run ```sudo startxfce4``` on an Asus Chromebook Flip C100 (Minnie). X11 will fail to start and complain that it cannot find any screens.
```
[    77.186] (II) LoadModule: "modesetting"
[    77.187] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[    77.187] (II) Module modesetting: vendor="X.Org Foundation"
[    77.187]    compiled for 1.15.0, module version = 0.8.1
[    77.187]    Module class: X.Org Video Driver
[    77.187]    ABI class: X.Org Video Driver, version 15.0
[    77.187] (II) UnloadModule: "modesetting"
[    77.187] (II) Unloading modesetting
[    77.187] (II) Failed to load module "modesetting" (already loaded, -1209214808)
[    77.187] (II) LoadModule: "fbdev"
[    77.187] (WW) Warning, couldn't open module fbdev
[    77.187] (II) UnloadModule: "fbdev"
[    77.187] (II) Unloading fbdev
[    77.187] (EE) Failed to load module "fbdev" (module does not exist, 0)
[    77.187] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[    77.187] (--) using VT number 7

[    77.198] (WW) Falling back to old probe method for modesetting
[    77.199] (EE) No devices detected.
[    77.199] (EE)
Fatal server error:
[    77.199] (EE) no screens found(EE)
```

I have a simple workaround:
```
sudo enter-chroot
sudo rm /dev/dri/card0
sudo mv /dev/dri/card1 /dev/dri/card0
```

This allows everything to startup correctly. I suspect this regression was introduced by:

https://code.google.com/p/chromium/issues/detail?id=477792
https://chromium.googlesource.com/chromiumos/third_party/kernel/+/d4ec95d83b3a3209f35b0c8d645aa51fcc9924e5%5E%21/#F0

--------

On a side note, I compiled xf86-video-armsoc. I managed to get es2gears running with hardware acceleration. This bug affects starting with ```fbdev``` and ```armsoc```. The logs from above occur when starting with ```fbdev``` (aka, the default Crouton setup).

https://github.com/mmind/xf86-video-armsoc

**Comment by amstan** [comment]
We're having similar problems with [Arch Linux ARM when using the armsoc X11 driver](https://github.com/archlinuxarm/PKGBUILDs/blob/e605cd2d3c07bd3b34e80dbbc84a48da4a27ee29/alarm/xf86-video-armsoc-rockchip/PKGBUILD). I suspend the fix is the same in both cases.

Another workaround I have is to just disable VGEM in the kernel config, but I guess that's harder with crouton.

**Comment by dnschneid** [comment]
Looks like the [terrible hack](https://github.com/dnschneid/crouton/blob/master/targets/x11-common#L15) crouton uses to get around vgem incompatibilities will need to be adjusted depending on whether card0 or card1 is active...

**Comment by amstan** [comment]
> Looks like the [terrible hack](https://github.com/dnschneid/crouton/blob/master/targets/x11-common#L15) crouton uses ....

    dd seek="${offset%:*}" bs=1 of=/usr/bin/Xorg

Alright, you made my day.

**Comment by smithno** [comment]
FYI, the "simple workaround" by aarossig above causes both USB slots and the MicroSD slot to stop working.  I get the error message "Sorry your external storage device not recognized." when either is inserted. I turned off Developer Mode and the external slots started working again.

**Comment by aarossig** [comment]
I don't believe that my workaround is the cause of USB and MicroSD to stop working. A simple reboot restores the /dev/dri/card0 and /dev/dri/card1 to their normal state.

I just tested on a C100 and my USB is working fine.

**Comment by smithno** [comment]
Thank you for checking! I'll dig some more...

Norm

**Comment by smithno** [comment]
I just tested it again on my end and it works fine. Sorry for the false alarm!! I have no clue what I did differently this time than before. Thank you for responding!!

Norm

**Comment by dnschneid** [comment]
1. make a directory somewhere (i.e., /var/run/drm)
2. copy contents of /sys/class/drm to that directory
3. remove any vgem symlinks from /var/run/drm
4. bind-mount /var/run/drm over /sys/class/drm inside the chroot
5. remove the terrible xorg binary hack because things behave well now

**Comment by dnschneid** [comment]
Okay, not-so-bad hack merged!  Give it a whirl...

**Comment by magjistari** [comment]
Hi, sorry but im new to this. Basically followed a step by step and got kde on asus c100. Is there a permanent fix to the no screen or should i keep doing this every time?
sudo enter-chroot
sudo rm /dev/dri/card0
sudo mv /dev/dri/card1 /dev/dri/card0... ?

dnschneid, does this work for me? Im new to the linux so i dont know how to do any of these. Is there a step by step somewhere?

make a directory somewhere (i.e., /var/run/drm)
cp -a contents of /sys/class/drm to that directory
remove any vgem symlinks from /var/run/drm
bind-mount /var/run/drm over /sys/class/drm inside the chroot
remove the terrible xorg binary hack because things behave well now

Thank you in advance.

**Comment by dnschneid** [comment]
You don't need to do any of that anymore.  Update your chroot and it should just work.

**Comment by magjistari** [comment]
David, thank you for your prompt reply sir but how do i update chroot? I thought i installed the latest yesterday. Excuse my ignorance but im so new to this im not even able to install chrome browser on this os. Im a quick learner though.any simple advice will be deeply appreciated. Thank you Luke.

**Comment by dnschneid** [comment]
If you installed it yesterday, then you don't need to do anything.

**Comment by magjistari** [comment]
I actually did have to do this yesterday and today too after i restarted my laptop. Otherwise i couldnt get past the error of no screen. 

sudo enter-chroot
sudo rm /dev/dri/card0
sudo mv /dev/dri/card1 /dev/dri/card0

**Comment by DennisLfromGA** [comment]
@magjistari,
> I thought i installed the latest yesterday.

After you install the latest version of crouton, you need to update your chroot.

**Comment by magjistari** [comment]
Thank you Dennis, i did sudo sh ~/Downloads/crouton -u [-n chrootkde] and it did download the crouton  installer so i guess it installed it, or do i have to install it? 
I installed this on asus c100 which is arm and i dont see any ways of installing deb packages. Couldnt even manage to install google chrome. Is there some step by step somewhere? For basic programs like some office or paint or etc...?
Thank you again, luke.

**Comment by DennisLfromGA** [comment]
@magjistari,
> i did sudo sh ~/Downloads/crouton -u [-n chrootkde] and it did download the crouton installer so i guess it installed it, or do i have to install it?

Nope, you don't have to do anything else to install it and that command should update the chroot at the sam time.

> I installed this on asus c100 which is arm and i dont see any ways of installing deb packages. 
You should be able to install linux packages using: `sudo apt-get install [package name ...]`

> Couldnt even manage to install google chrome.

Sorry, I'm not familiar with the Chromebook Flip but there is a chrome target in crouton so you may be able to install it that way. In fact, you can install chrome stable or beta or dev and even chromium -
```
chrome
        Google Chrome browser, stable channel.
        Requires: x11
chrome-beta
        Google Chrome browser, beta channel.
        Requires: x11
chrome-dev
        Google Chrome browser, dev channel.
        Requires: x11
chromium
        Chromium browser. Uses the distro's version, which may be old.
        Requires: x11
```
You can 'add' targets to an existing chroot installation using the update '-u' option, something like:

`sudo sh ~/Downloads/crouton -u -t chrome-beta [-n chrootname]`

**Comment by smithno** [comment]
See http://www.webupd8.org/2013/12/things-to-do-after-installing-ubuntu-on.html for a convenient way to tweak the Crouton installation. I use it as to remind me the things to install after Crouton.

**Comment by magjistari** [comment]
Thank you, thank you very much guys. This is the kind of instructions that i needed. People like you make this community wonderful and raise interest from noobs like me to start working on these platforms.

**Comment by magjistari** [comment]
Well i might just be doing something wrong cause once i restart my laptop i still get the no screen error.

**Comment by magjistari** [comment]
chronos@localhost / $ sudo sh ~/Downloads/crouton -u [-n chrootkde]
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: precise,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
@magjistari - Sorry but I just now saw your last post and noticed you used my suggestion literally with the brackets [] and all. I should have pointed out that the '`[-n chrootkde]`' part needs to be replaced with your actual chroot's name. 
You can find the name(s) of the chroot(s) you have installed by entering the following:

`sudo edit-chroot -al`

So, far example, if your chroot's name is 'trusty', then to update it you'd enter:

`sudo sh ~/Downloads/crouton -u -n trusty`

Hope this helps,
-DennisL

**Comment by laitanner** [comment]
I'm also on a chromebook flip (minnie) and this issue doesn't seem to have been fixed for me. I've included the log for reference. I've updated crouton twice and `croutonversion -u -d -c` tells me I have : `crouton: version 1-20151104200003~master:2a1fc9da`
```
[   721.965] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[   721.966] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[   721.967] X Protocol Version 11, Revision 0
[   721.967] Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
[   721.967] Current Operating System: Linux localhost 3.14.0 #1 SMP Mon Nov 30 22:00:10 PST 2015 armv7l
[   721.967] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=bd287ed9-9e61-2145-adad-fec8799881fe/PARTNROFF=1 hashtree=PARTUUID=bd287ed9-9e61-2145-adad-fec8799881fe/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=c754bbedaa661997af7b02f2ec812c42be8965e1 salt=f137c514be42bd0586d1583e68517c47c6c9cf74f7f5eebfa6375392c514fe9e" noinitrd vt.global_cursor_default=0 kern_guid=bd287ed9-9e61-2145-adad-fec8799881fe  
[   721.967] Build Date: 05 November 2013  03:23:26PM
[   721.967] xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
[   721.967] Current version of pixman: 0.30.2
[   721.967]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[   721.967] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   721.967] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Dec  3 23:20:15 2015
[   721.968] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   721.968] (==) No Layout section.  Using the first Screen section.
[   721.968] (==) No screen section available. Using defaults.
[   721.968] (**) |-->Screen "Default Screen Section" (0)
[   721.968] (**) |   |-->Monitor "<default monitor>"
[   721.969] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[   721.969] (==) Automatically adding devices
[   721.969] (==) Automatically enabling devices
[   721.969] (==) Automatically adding GPU devices
[   721.969] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   721.969]    Entry deleted from font path.
[   721.969] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   721.969]    Entry deleted from font path.
[   721.969] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   721.969]    Entry deleted from font path.
[   721.969] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[   721.969]    Entry deleted from font path.
[   721.969] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   721.969]    Entry deleted from font path.
[   721.969] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   721.969]    Entry deleted from font path.
[   721.969] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[   721.969]    Entry deleted from font path.
[   721.969] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[   721.969] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[   721.969] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[   721.969] (II) Loader magic: 0xb6f36e58
[   721.969] (II) Module ABI versions:
[   721.969]    X.Org ANSI C Emulation: 0.4
[   721.969]    X.Org Video Driver: 13.0
[   721.969]    X.Org XInput driver : 18.0
[   721.969]    X.Org Server Extension : 7.0
[   721.970] (II) config/udev: Adding drm device (/dev/dri/card1)
[   721.970] setversion 1.4 failed
[   721.970] Initializing built-in extension Generic Event Extension
[   721.970] Initializing built-in extension SHAPE
[   721.970] Initializing built-in extension MIT-SHM
[   721.970] Initializing built-in extension XInputExtension
[   721.971] Initializing built-in extension XTEST
[   721.971] Initializing built-in extension BIG-REQUESTS
[   721.971] Initializing built-in extension SYNC
[   721.971] Initializing built-in extension XKEYBOARD
[   721.971] Initializing built-in extension XC-MISC
[   721.971] Initializing built-in extension SECURITY
[   721.971] Initializing built-in extension XINERAMA
[   721.971] Initializing built-in extension XFIXES
[   721.971] Initializing built-in extension RENDER
[   721.971] Initializing built-in extension RANDR
[   721.971] Initializing built-in extension COMPOSITE
[   721.971] Initializing built-in extension DAMAGE
[   721.971] Initializing built-in extension MIT-SCREEN-SAVER
[   721.971] Initializing built-in extension DOUBLE-BUFFER
[   721.971] Initializing built-in extension RECORD
[   721.971] Initializing built-in extension DPMS
[   721.971] Initializing built-in extension X-Resource
[   721.971] Initializing built-in extension XVideo
[   721.971] Initializing built-in extension XVideo-MotionCompensation
[   721.971] Initializing built-in extension XFree86-VidModeExtension
[   721.975] Initializing built-in extension XFree86-DGA
[   721.975] Initializing built-in extension XFree86-DRI
[   721.975] Initializing built-in extension DRI2
[   721.975] (II) LoadModule: "glx"
[   721.975] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   721.976] (II) Module glx: vendor="X.Org Foundation"
[   721.976]    compiled for 1.13.0, module version = 1.0.0
[   721.976]    ABI class: X.Org Server Extension, version 7.0
[   721.976] (==) AIGLX enabled
[   721.976] Loading extension GLX
[   721.976] (==) Matched modesetting as autoconfigured driver 0
[   721.976] (==) Matched fbdev as autoconfigured driver 1
[   721.976] (==) Assigned the driver to the xf86ConfigLayout
[   721.976] (II) LoadModule: "modesetting"
[   721.977] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   721.977] (II) Module modesetting: vendor="X.Org Foundation"
[   721.977]    compiled for 1.13.0, module version = 0.5.0
[   721.977]    Module class: X.Org Video Driver
[   721.977]    ABI class: X.Org Video Driver, version 13.0
[   721.977] (II) LoadModule: "fbdev"
[   721.978] (WW) Warning, couldn't open module fbdev
[   721.978] (II) UnloadModule: "fbdev"
[   721.978] (II) Unloading fbdev
[   721.978] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   721.978] (==) Matched modesetting as autoconfigured driver 0
[   721.978] (==) Matched fbdev as autoconfigured driver 1
[   721.978] (==) Assigned the driver to the xf86ConfigLayout
[   721.978] (II) LoadModule: "modesetting"
[   721.978] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   721.978] (II) Module modesetting: vendor="X.Org Foundation"
[   721.978]    compiled for 1.13.0, module version = 0.5.0
[   721.978]    Module class: X.Org Video Driver
[   721.978]    ABI class: X.Org Video Driver, version 13.0
[   721.978] (II) UnloadModule: "modesetting"
[   721.978] (II) Unloading modesetting
[   721.978] (II) Failed to load module "modesetting" (already loaded, -1202464536)
[   721.978] (II) LoadModule: "fbdev"
[   721.979] (WW) Warning, couldn't open module fbdev
[   721.979] (II) UnloadModule: "fbdev"
[   721.979] (II) Unloading fbdev
[   721.979] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   721.979] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   721.979] (--) using VT number 7

[   721.992] (WW) Falling back to old probe method for modesetting
[   721.992] (II) modesetting(0): using default device
[   721.992] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[   721.993] (II) modesetting(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 24/32
[   721.993] (==) modesetting(0): Depth 24, (--) framebuffer bpp 32
[   721.993] (==) modesetting(0): RGB weight 888
[   721.993] (==) modesetting(0): Default visual is TrueColor
[   721.993] (II) modesetting(0): ShadowFB: preferred NO, enabled NO
[   721.993] (EE) modesetting(0): KMS setup failed
[   721.993] (II) UnloadModule: "modesetting"
[   721.993] (EE) Screen(s) found, but none have a usable configuration.
[   721.993] 
Fatal server error:
[   721.993] no screens found
[   721.993] (EE) 
```

**Comment by shoerob** [comment]
I just installed the latest version to my Chromebook flip, and I'm seeing the same "no screens found" problem.

**Comment by irothste** [comment]
I loaded it with xiwi and it seems to be working for me.

**Comment by andysam151** [comment]
can someone tell me what im doing wrong its not working
sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)andysam151@localhost:~$ sudo rm /dev/dri/card0
[sudo] password for andysam151: 
rm: cannot remove `/dev/dri/card0': No such file or directory
(precise)andysam151@localhost:~$ sudo mv /dev/dri/card1 /dev/dri/card0
mv: cannot stat `/dev/dri/card1': No such file or directory

**Comment by andysam151** [comment]
i have a chromebook flip

**Comment by andysam151** [comment]
im trying to download minecraft with xfce

**Comment by asonawalla** [comment]
@andysam151 skip the `enter-chroot` step- you need to do the card0/card1 trick from the chronos shell.

**Comment by andysam151** [comment]
i tried and this is what i got
crosh> shell
chronos@localhost / $ sudo rm /dev/dti/card0
rm: cannot remove ‘/dev/dti/card0’: No such file or directory
chronos@localhost / $ sudo mv /dev/dri/card0 /dev/dri/card1
mv: cannot stat ‘/dev/dri/card0’: No such file or directory
thanks for trying to help asonawalla

**Comment by divx118** [comment]
@andysam151 First reboot your chomebook, then before doing anything do:

```
crosh> shell
chronos@localhost / $ ls -al /dev/dri
```
Post the output here.
Then try again 
```
chronos@localhost / $ sudo rm /dev/dri/card0
chronos@localhost / $ sudo mv /dev/dri/card1 /dev/dri/card0
```
Look careful at the commands above, because you had some typos in yours.

**Comment by andysam151** [comment]
thanks this is the output
crosh> shell
chronos@localhost / $ ls -al /dev/dri
total 0
drwxr-xr-x  2 root root       140 Dec 31  1969 .
drwxr-xr-x 16 root root      2080 Dec 27 13:18 ..
crw-rw----  1 root video 226,   0 Dec 27 13:18 card0
crw-rw----  1 root video 226,   1 Dec 27 13:18 card1
crw-rw----  1 root video 226,  64 Dec 27 13:18 controlD64
crw-rw----  1 root video 226, 128 Dec 27 13:18 renderD128
crw-rw----  1 root video 226, 129 Dec 27 13:18 renderD129

**Comment by andysam151** [comment]
THANK YOU SO MUCH divx118 it worked

**Comment by andysam151** [comment]
so i am trying to open minecraft and i am opening it with the java7 that i was told to install but when i try to open it with java7 nothing happens
please help me

**Comment by Ph9214** [comment]
@andysam151 Make sure to have the arm version of Java, and you still might not be able to run it, try starting it in the terminal and post the output here

PS. The flip is arm and will not play steam games

**Comment by rustystrauss** [comment]
so I tried everything above, but I'm _still_ getting no screens found error. please help.

**Comment by DennisLfromGA** [comment]
@rustystrauss,

Have you updated your chroot?
The [fix for this](https://github.com/dnschneid/crouton/pull/2823) was merged on Oct. 12th.

*Hope this helps,*
-**DennisL**

**Comment by rustystrauss** [comment]
@DennisLfromGA thanks dennis, I should have tried something so obvious imediatly, but I still got an error on initialization, albeit a different one.
```
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
```
anyway thanks.

**Comment by Ders2212** [comment]
Hey folks, 



I have tried everything above and STILL cannot open xfce, can anyone help?

Error Message:
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:34:05 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=5ba313cf-1e37-7740-a314-e067d126a92e/PARTNROFF=1 hashtree=PARTUUID=5ba313cf-1e37-7740-a314-e067d126a92e/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=bc4b56db04ab647e24cc83c4e9c1d3ab23befe07 salt=f0f132479996b812e136d7a405b0692f126d03facd2e995f2e26b59818376e1e" noinitrd vt.global_cursor_default=0 kern_guid=5ba313cf-1e37-7740-a314-e067d126a92e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Mar  8 21:09:56 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.

**Comment by DennisLfromGA** [comment]
@Ders2212,

Please follow this guide: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

Once that's done if you are still having this issue please come back here and post the output of:

`sudo edit-chroot -all`

And provide us with more details.

*Hope this helps,*
-**DennisL**

**Comment by wcbrown11** [comment]
![Uploading image.jpg…]()
