### ISSUE TITLE
31.8 gb encstateful partition

### ISSUE THREAD

**Issue by giliammc** [dnschneid/crouton#1939]
i am running out of space and i thought that was odd since i have a 128 gb ssd so i deleted a few things so that i could use my computer without it crashing. i ran lsblk to check my partitons and this is what i found
chronos@localhost / $ lsblk
lsblk: dm-0: failed to get device path
lsblk: dm-0: failed to get device path
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    0 111.8G  0 disk 
├─sda1          8:1    0 107.7G  0 part /mnt/stateful_partition
├─sda2          8:2    0    16M  0 part 
├─sda3          8:3    0     2G  0 part 
├─sda4          8:4    0    16M  0 part 
├─sda5          8:5    0     2G  0 part 
├─sda6          8:6    0   512B  0 part 
├─sda7          8:7    0   512B  0 part 
├─sda8          8:8    0    16M  0 part /usr/share/oem
├─sda9          8:9    0   512B  0 part 
├─sda10         8:10   0   512B  0 part 
├─sda11         8:11   0     8M  0 part 
└─sda12         8:12   0    16M  0 part 
loop0           7:0    0  31.8G  0 loop 
└─encstateful 254:1    0  31.8G  0 dm   /mnt/stateful_partition/encrypted
zram0         253:0    0   5.7G  0 disk [SWAP]
chronos@localhost / $ 

thanks in advance

**Comment by DennisLfromGA** [comment]
@giliammc,

Try running: `df -h | grep -e /sda -e Avail`
That should show you what's 'Used' and 'Avail' to help you narrow down where the problem might be.

I have a 128gb ssd on my HP Chromebook 14 (Falco) and here's what mine shows -

`sudo lsblk`:
```
lsblk: dm-0: failed to get device path
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    0 111.8G  0 disk 
├─sda1    8:1    0   9.8G  0 part /mnt/stateful_partition
├─sda2    8:2    0    16M  0 part 
├─sda3    8:3    0     2G  0 part /run/crouton/var/crouton/chroots/trusty/lib/mo
├─sda4    8:4    0    16M  0 part 
├─sda5    8:5    0     2G  0 part 
├─sda6    8:6    0    16M  0 part 
├─sda7    8:7    0    15G  0 part /mnt/ChrUbuntu-sda7
├─sda8    8:8    0    16M  0 part /usr/share/oem
├─sda9    8:9    0   512B  0 part 
├─sda10   8:10   0   512B  0 part 
├─sda11   8:11   0     8M  0 part 
├─sda12   8:12   0    16M  0 part 
└─sda13   8:13   0  82.9G  0 part /var/crouton
loop0     7:0    0   2.9G  0 loop 
└─encstateful
        254:1    0   2.9G  0 dm   /mnt/stateful_partition/encrypted
zram0   253:0    0   5.6G  0 disk [SWAP]
```

`df -h | grep -e /sda -e Avail`:
```
Filesystem                                                    Size  Used Avail Use% Mounted on
/dev/sda1                                                     9.5G  2.4G  6.7G  26% /home
/dev/sda8                                                      12M   24K   12M   1% /usr/share/oem
/dev/sda7                                                      15G  7.8G  6.2G  56% /mnt/ChrUbuntu-sda7
/dev/sda13                                                     82G   27G   51G  35% /var/crouton
```

I have ChrUbuntu (sda7) and CROUTON (sda13) partitions setup on mine to protect them from powerwashes, etc.

**Comment by giliammc** [comment]
crosh> shell
chronos@localhost / $ df -h | grep -e /sda -e Avail
Filesystem                                                    Size  Used Avail Use% Mounted on
/dev/sda1                                                     106G   94G  7.2G  93% /home
/dev/sda8                                                      12M   24K   12M   1% /usr/share/oem
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
@giliammc - 
Somehow you're using 94gb of your 106gb stateful_partition but you still have 7.2gb left.
It could be you have one or more very large chroots installed.
Try running: `sudo du -cmhsx /usr/local/*` and see what you get.

**Comment by giliammc** [comment]
crosh> shell
chronos@localhost / $ sudo du -cmhsx /usr/local/*
128K    /usr/local/bin
0       /usr/local/chroots
128K    total
chronos@localhost / $

**Comment by giliammc** [comment]
to my knowledge on this computer i only have one chroot

**Comment by DennisLfromGA** [comment]
@giliammc -
You're also using 31.8gb as opposed to my 2.9gb in `/mnt/stateful_partition/encrypted/` for some reason. You may have some large file(s) in ~/Downloads perhaps???

Just for kicks, try running -
`sudo du -cmhsx /mnt/stateful_partition/encrypted/chronos/* | sort -h`
and
`sudo du -cmhsx $HOME/* | sort -h`
and show what you get.

TIP: enclose your output with three ticks ``` before and after to make it more readable - like:
```
output
```

**Comment by giliammc** [comment]
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo du -cmhsx /mnt/stateful_partition/encrypted/chronos/* | sort -h
0       /mnt/stateful_partition/encrypted/chronos/First Run
0       /mnt/stateful_partition/encrypted/chronos/SingletonCookie
0       /mnt/stateful_partition/encrypted/chronos/SingletonLock
0       /mnt/stateful_partition/encrypted/chronos/SingletonSocket
4.0K    /mnt/stateful_partition/encrypted/chronos/Consent To Send Stats
4.0K    /mnt/stateful_partition/encrypted/chronos/crash
4.0K    /mnt/stateful_partition/encrypted/chronos/nacl_validation_cache.bin
4.0K    /mnt/stateful_partition/encrypted/chronos/Safe Browsing IP Blacklist
4.0K    /mnt/stateful_partition/encrypted/chronos/u-0ab953a9fbb2d86711c27f2fefe874069353bdaa
4.0K    /mnt/stateful_partition/encrypted/chronos/u-4752f59f3f9d410d9349777ef243ec20c0f3758f
4.0K    /mnt/stateful_partition/encrypted/chronos/Webstore Downloads
8.0K    /mnt/stateful_partition/encrypted/chronos/Safe Browsing Cookies
8.0K    /mnt/stateful_partition/encrypted/chronos/Safe Browsing Cookies-journal
16K     /mnt/stateful_partition/encrypted/chronos/Safe Browsing Download Whitelist
24K     /mnt/stateful_partition/encrypted/chronos/user
28K     /mnt/stateful_partition/encrypted/chronos/Local State
40K     /mnt/stateful_partition/encrypted/chronos/custom_wallpapers
48K     /mnt/stateful_partition/encrypted/chronos/Safe Browsing Extension Blacklist
112K    /mnt/stateful_partition/encrypted/chronos/Safe Browsing Csd Whitelist
356K    /mnt/stateful_partition/encrypted/chronos/Safe Browsing UwS List Prefix Set
904K    /mnt/stateful_partition/encrypted/chronos/wallpaper_thumbnails
1.1M    /mnt/stateful_partition/encrypted/chronos/EVWhitelist
1.1M    /mnt/stateful_partition/encrypted/chronos/Safe Browsing UwS List
1.2M    /mnt/stateful_partition/encrypted/chronos/Safe Browsing Inclusion Whitelist
1.3M    /mnt/stateful_partition/encrypted/chronos/Dictionaries
1.8M    /mnt/stateful_partition/encrypted/chronos/Safe Browsing Bloom Prefix Set
2.7M    /mnt/stateful_partition/encrypted/chronos/Default
2.7M    /mnt/stateful_partition/encrypted/chronos/wallpapers
3.8M    /mnt/stateful_partition/encrypted/chronos/Safe Browsing Download
5.9M    /mnt/stateful_partition/encrypted/chronos/PnaclTranslationCache
8.2M    /mnt/stateful_partition/encrypted/chronos/Safe Browsing Bloom
31M     total
chronos@localhost / $

**Comment by giliammc** [comment]
here is the second one 
``` Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.
chronos@localhost / $ sudo du -cmhsx $HOME/* | sort -h
4.0K    /home/chronos/user/crash
8.0K    /home/chronos/user/local
8.0K    /home/chronos/user/RLZ Data.lock
12K     /home/chronos/user/Affiliation Database-journal
12K     /home/chronos/user/Current Tabs
12K     /home/chronos/user/login-times
12K     /home/chronos/user/logout-times
12K     /home/chronos/user/Origin Bound Certs-journal
12K     /home/chronos/user/README
12K     /home/chronos/user/RLZ Data
16K     /home/chronos/user/Affiliation Database
16K     /home/chronos/user/Extension Cookies-journal
16K     /home/chronos/user/WebRTCIdentityStore
20K     /home/chronos/user/Extension Cookies
20K     /home/chronos/user/QuotaManager-journal
20K     /home/chronos/user/WebRTCIdentityStore-journal
24K     /home/chronos/user/App Launcher Search
24K     /home/chronos/user/Cookies-journal
24K     /home/chronos/user/Favicons-journal
24K     /home/chronos/user/History-journal
24K     /home/chronos/user/Login Data-journal
24K     /home/chronos/user/Shortcuts-journal
24K     /home/chronos/user/Top Sites-journal
24K     /home/chronos/user/Web Data-journal
28K     /home/chronos/user/Network Action Predictor-journal
28K     /home/chronos/user/QuotaManager
44K     /home/chronos/user/TransportSecurity
48K     /home/chronos/user/Last Tabs
60K     /home/chronos/user/Extension Rules
60K     /home/chronos/user/Origin Bound Certs
76K     /home/chronos/user/Login Data
84K     /home/chronos/user/Bookmarks
84K     /home/chronos/user/Bookmarks.bak
88K     /home/chronos/user/cmt
96K     /home/chronos/user/databases
100K    /home/chronos/user/Sync FileSystem
132K    /home/chronos/user/Sync Extension Settings
136K    /home/chronos/user/Visited Links
144K    /home/chronos/user/Web Data
156K    /home/chronos/user/Shortcuts
196K    /home/chronos/user/Certificate Revocation Lists
228K    /home/chronos/user/Network Action Predictor
304K    /home/chronos/user/Last Session
304K    /home/chronos/user/Preferences
328K    /home/chronos/user/Local Extension Settings
364K    /home/chronos/user/History Provider Cache
388K    /home/chronos/user/GCM Store
592K    /home/chronos/user/GPUCache
644K    /home/chronos/user/Top Sites
660K    /home/chronos/user/Sync App Settings
1.1M    /home/chronos/user/ev_hashes_whitelist.bin
1.5M    /home/chronos/user/Current Session
1.6M    /home/chronos/user/Cookies
1.6M    /home/chronos/user/GCache
2.1M    /home/chronos/user/Local App Settings
2.5M    /home/chronos/user/Webservice Search Cache
3.6M    /home/chronos/user/log
3.9M    /home/chronos/user/Favicons
4.4M    /home/chronos/user/Sync Data
4.9M    /home/chronos/user/History
5.4M    /home/chronos/user/Media Cache
5.9M    /home/chronos/user/Pepper Data
6.1M    /home/chronos/user/Extension State
6.2M    /home/chronos/user/Service Worker
12M     /home/chronos/user/File System
12M     /home/chronos/user/Session Storage
29M     /home/chronos/user/Local Storage
31M     /home/chronos/user/IndexedDB
125M    /home/chronos/user/Application Cache
193M    /home/chronos/user/Cache
276M    /home/chronos/user/Extensions
417M    /home/chronos/user/Storage
74G     /home/chronos/user/Downloads
75G     total
chronos@localhost / $  
```

**Comment by giliammc** [comment]
the three ticks didnt work

**Comment by DennisLfromGA** [comment]
@giliammc,
> 74G /home/chronos/user/Downloads
> 75G total

That's where most of your space is being eaten up.
Now enter: `sudo sudo du -cmhsx ~/Downolads/* | sort -h`
and let us drill down a little.

----
> the three ticks didnt work

They work if they're on a line by themselves starting in column one, both before and after you're output.
Check out '[GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/)' and in particular '[Fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks)'.

**Comment by giliammc** [comment]
```
chronos@localhost / $ sudo sudo du -cmhsx ~/Downolads/* | sort -h
du: cannot access ‘/home/chronos/user/Downolads/*’: No such file or directory
0       total
```

**Comment by DennisLfromGA** [comment]
@giliammc,

You need to log in using your Google account credentials first in order to make ~/Downloads available.

**Comment by giliammc** [comment]
how do you do that

**Comment by DennisLfromGA** [comment]
Have you setup a user account on your Chromebook and logged in as someone other than 'guest'?
If not, I suggest you do that so that you become the 'owner' and have some control over who uses it.

Once you login with your Google account, you can gain access to your own ~/Downloads folder and configure/customize your Chromebook to your liking. You can then also use <kbd>Ctrl+Alt+t</kbd> to get a crosh shell and install crouton, etc.

**Comment by giliammc** [comment]
I am logged in to my account

**Comment by DennisLfromGA** [comment]
Okay, good start.

- press <kbd>Ctrl+Alt+t</kbd>
- enter: shell
- enter: sudo du -cmhsx ~/Downolads/* | sort -h

and let us know what it displays.

**Comment by giliammc** [comment]
Tat is the exact process I used

**Comment by DennisLfromGA** [comment]
Good, then what does is the output?

**Comment by giliammc** [comment]
```
du: cannot access ‘/home/chronos/user/Downolads/*’: No such file or directory
0       total
```

**Comment by giliammc** [comment]
same as before

**Comment by DennisLfromGA** [comment]
Could we see the command you're executing please?
It looks like you're using single quotes ->'<- surrounding the path, that's a no-no.

Again, just enter: sudo du -cmhsx ~/Downolads/* | sort -h
( the stuff after the colon above is what you need )

**Comment by giliammc** [comment]
i didn't put the quotes there

**Comment by giliammc** [comment]
```
chronos@localhost / $ sudo du -cmhsx ~/Downolads/* | sort -h
du: cannot access ‘/home/chronos/user/Downolads/*’: No such file or directory
0       total
chronos@localhost / $ 
```

**Comment by tmagara** [comment]
You are typing "Downolads". It should be "Downloads".

**Comment by DennisLfromGA** [comment]
My bad, sorry. Cut-N-Paste isn't always the best way to approach a problem... :/

**Comment by giliammc** [comment]
no wonder i was going crazy!

anyway here is the long awaited output

```
chronos@localhost / $ sudo du -cmhsx ~/Downloads/* | sort -h
Password: 
4.0K    /home/chronos/user/Downloads/trail life
12K     /home/chronos/user/Downloads/output.pdf
16K     /home/chronos/user/Downloads/crouton
20K     /home/chronos/user/Downloads/bat.png
24K     /home/chronos/user/Downloads/madsci1016-Arduino-PS2X-5d2be70.zip
32K     /home/chronos/user/Downloads/lsm303-arduino-master.zip
52K     /home/chronos/user/Downloads/2015-05-05-raspbian-wheezy.zip.torrent
96K     /home/chronos/user/Downloads/g face.png
140K    /home/chronos/user/Downloads/StripBoard.PNG
176K    /home/chronos/user/Downloads/Duty_Mode_GIR.png
192K    /home/chronos/user/Downloads/milk_carton_wallet_template.pdf
352K    /home/chronos/user/Downloads/Adafruit_Arduino_Boards-master.zip
376K    /home/chronos/user/Downloads/photo 1.JPG
512K    /home/chronos/user/Downloads/IMG_20150408_193119.jpg
824K    /home/chronos/user/Downloads/kayak
968K    /home/chronos/user/Downloads/Pro_Trinket_USB_Mouse-master.zip
1.5M    /home/chronos/user/Downloads/Adafruit_Arduino_Boards-master
1.6M    /home/chronos/user/Downloads/joystick mouse
1.7M    /home/chronos/user/Downloads/3D-printable_whistle_whistle_and_pea.gcode
1.9M    /home/chronos/user/Downloads/nano-2.4.2.tar.gz
1.9M    /home/chronos/user/Downloads/nano.tar.gz
3.3M    /home/chronos/user/Downloads/Pro_Trinket_USB_Keyboard_Library-master.zip
8.5M    /home/chronos/user/Downloads/nano-2.4.1
13M     /home/chronos/user/Downloads/3973368_Tinkerplay05191507
16M     /home/chronos/user/Downloads/arduino-0023
18M     /home/chronos/user/Downloads/hp
33M     /home/chronos/user/Downloads/berryboot-20150401-pi2-only.zip
43M     /home/chronos/user/Downloads/adafruit-arduino-1.6.4-linux64.tar.xz
196M    /home/chronos/user/Downloads/simulink
6.6G    /home/chronos/user/Downloads/trusty-20150705-1513.tar.gz
63G     /home/chronos/user/Downloads/sda1
70G     total
chronos@localhost / $ 
```

**Comment by DennisLfromGA** [comment]
> 6.6G    /home/chronos/user/Downloads/trusty-20150705-1513.tar.gz

I would move the trusty backup to external media.
> 63G     /home/chronos/user/Downloads/sda1

I don't know what the 63G 'sda1' is, possibly you 'dd'ed the partition to a file?
At any rate, that's where most of your space is being consumed.

**Comment by giliammc** [comment]
that still doesn't account for 31.8gb

**Comment by DennisLfromGA** [comment]
@giliammc - If I had your Chromebook, I could probably find it, but I don't; I suppose you'll have to look for. If it were me, I'd use the `df` and `du` commands and try to narrow down where the space is being used.

**Comment by giliammc** [comment]
ok what does the encstateful partition do

**Comment by DennisLfromGA** [comment]
> ok what does the encstateful partition do

It's an encrypted, loop mounted stateful partition that only the current user has access to - I'm guessing.
I don't pretend to know how Google does it's thing with Chromebooks but that seems to make the most sense to me.

I'm sure there are others here that could explain it a whole lot better...

**Comment by giliammc** [comment]
if i restart the computer and login as guest i still have a 31.8gb  encstateful partition

**Comment by DennisLfromGA** [comment]
@giliammc - If you don't know how or where your disk space is disappearing to and can't find out, I would suggest backing up the files you need in ~/Downloads ( did I spell it right ;), to include your trusty backup, and doing a usb restore.

**Comment by giliammc** [comment]
ok i was trying to ovoid that. but i guess that is the only option

**Comment by DennisLfromGA** [comment]
Well, it's not the only option, I probably should have recommended you do a 'powerwash' first, after backing up your important files first of course. Then, if that doesn't free up the space, do a usb restore as a last resort.

**Comment by giliammc** [comment]
ok

**Comment by giliammc** [comment]
as i was backing up my downloads folder i found a 62gb file named sda2
![screenshot 2015-07-18 at 10 42 31 am](https://cloud.githubusercontent.com/assets/10850574/8762271/dd0cde58-2d39-11e5-9b2e-ccdb674a618e.png)

**Comment by giliammc** [comment]
i just finished power washing and the 31.8gb partition is still there

**Comment by giliammc** [comment]
i restored from usb and it is still there

**Comment by DennisLfromGA** [comment]
> as i was backing up my downloads folder i found a 62gb file named sda2

It's actually 'sda1' and I referred to it here https://github.com/dnschneid/crouton/issues/1939#issuecomment-122390945.

> i just finished power washing and the 31.8gb partition is still there

What partition number is it?

**Comment by giliammc** [comment]
```
chronos@localhost ~ $ lsblk
lsblk: dm-0: failed to get device path
lsblk: dm-0: failed to get device path
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    0 111.8G  0 disk 
├─sda1          8:1    0 107.7G  0 part /mnt/stateful_partition
├─sda2          8:2    0    16M  0 part 
├─sda3          8:3    0     2G  0 part 
├─sda4          8:4    0    16M  0 part 
├─sda5          8:5    0     2G  0 part 
├─sda6          8:6    0   512B  0 part 
├─sda7          8:7    0   512B  0 part 
├─sda8          8:8    0    16M  0 part /usr/share/oem
├─sda9          8:9    0   512B  0 part 
├─sda10         8:10   0   512B  0 part 
├─sda11         8:11   0     8M  0 part 
└─sda12         8:12   0    16M  0 part 
sdb             8:16   1   988M  0 disk /media/removable/Internal
sdc             8:32   1   1.9G  0 disk 
└─sdc1          8:33   1   1.9G  0 part /media/removable/External
sr0            11:0    1   7.9M  0 rom  /media/removable/Mobile Partner
loop0           7:0    0  31.8G  0 loop 
└─encstateful 254:1    0  31.8G  0 dm   /mnt/stateful_partition/encrypted
zram0         253:0    0   2.7G  0 disk [SWAP]
chronos@localhost ~ $ 
```

**Comment by giliammc** [comment]
google lost my backup file

**Comment by DennisLfromGA** [comment]
@giliammc - It might give us a clearer picture of exactly what's on your Chromebook, and only your Chromebook, if you'd unplug all of your external media before running 'lsblk`.

I'm really curious though, exactly what model of Chromebook do you have?

-----

> i restored from usb and it is still there
```
loop0           7:0    0  31.8G  0 loop 
└─encstateful 254:1    0  31.8G  0 dm   /mnt/stateful_partition/encrypted
```

Does anyone know why @giliammc has a 31.8G encstateful partition, apparently after doing a usb restore?

Mine is only 2.9G - 
```
loop0     7:0    0   2.9G  0 loop 
└─encstateful
        254:1    0   2.9G  0 dm   /mnt/stateful_partition/encrypted
```

**Comment by tcagle** [comment]
I googled encstateful partition and found this thread...

https://github.com/dnschneid/crouton/issues/403

I am wondering if this is due to some prior experimentation  with chrubuntu on this machine as was apparently the case in that thread.

**Comment by DennisLfromGA** [comment]
> I am wondering if this is due to some prior experimentation with chrubuntu on this machine as was apparently the case in that thread.

That's possible but your ChrUbuntu partition (sda7) is minimal so I don't think so.

I've just come to the conclusion that, due to the extremely large size of your stateful_partition (sda1), it's creating a very large proportionate loop mounted encstateful partition when you log in, I don't think it'll hurt anything though. You took care of most of the problem, your 75G ~/Downloads, when you did the powerwash. 

I'm afraid that's the best I can come up with, maybe some others will have a more definite idea.

**Comment by giliammc** [comment]
i have never used chrbuntu and i am on a acer c720
here is lsblk with no external devices connected

```
chronos@localhost ~ $ lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    0 111.8G  0 disk 
├─sda1          8:1    0 107.7G  0 part /mnt/stateful_partition
├─sda2          8:2    0    16M  0 part 
├─sda3          8:3    0     2G  0 part 
│ └─vroot     254:0    0   1.2G  1 dm   /
├─sda4          8:4    0    16M  0 part 
├─sda5          8:5    0     2G  0 part 
├─sda6          8:6    0   512B  0 part 
├─sda7          8:7    0   512B  0 part 
├─sda8          8:8    0    16M  0 part /usr/share/oem
├─sda9          8:9    0   512B  0 part 
├─sda10         8:10   0   512B  0 part 
├─sda11         8:11   0     8M  0 part 
└─sda12         8:12   0    16M  0 part 
loop0           7:0    0  31.8G  0 loop 
└─encstateful 254:1    0  31.8G  0 dm   /mnt/stateful_partition/encrypted
zram0         253:0    0   2.7G  0 disk [SWAP]
chronos@localhost ~ $ 

```

**Comment by DennisLfromGA** [comment]
@giliammc - 
I see no problem whatsoever with that output, everything looks perfectly normal to me, except for the fact that you have a ginormous stateful_partition.

Do you still think that something is awry or are you now satisfied with the numbers?

If satisfied, please close this issue.
If not satisfied, you'll have to wait for others to weigh in...

Thanx,
-DennisL

P.S. I like my setup -
```
Filesystem                                                    Size  Used Avail Use% Mounted on
/dev/sda1                                                     9.5G  2.4G  6.7G  26% /home
/dev/sda8                                                      12M   24K   12M   1% /usr/share/oem
/dev/sda7                                                      15G  7.8G  6.2G  56% /mnt/ChrUbuntu-sda7
/dev/sda13                                                     82G   27G   51G  35% /var/crouton
```
It gives me an option to boot Linux Mint 17.1 via <kbd>Ctrl-l</kbd> and it saves my crouton chroots and other things I've stored on a separate and safe CROUTON partiton - pretty slick I think.

**Comment by drinkcat** [comment]
@giliammc : You could try doing an fstrim: `fstrim /mnt/stateful_partition/encrypted`, that may shrink the encrypted part of the stateful partition.

I'd also like to see the full output of `df -h`

**Comment by giliammc** [comment]
here is the output you asked for
```
chronos@localhost / $ df -h
Filesystem                                                    Size  Used Avail Use% Mounted on
/dev/root                                                     1.2G  1.1G  174M  86% /
devtmpfs                                                      938M  804M  135M  86% /dev
tmp                                                           939M   33M  907M   4% /tmp
run                                                           939M  396K  939M   1% /run
shmfs                                                         939M  154M  786M  17% /dev/shm
/dev/sda1                                                     106G   13G   88G  13% /home
/dev/sda8                                                      12M   24K   12M   1% /usr/share/oem
/dev/mapper/encstateful                                        32G  6.4G   25G  21% /var
media                                                         939M     0  939M   0% /media
none                                                          939M   40K  939M   1% /sys/fs/cgroup
/home/.shadow/d3b8202a50151c61c7d9a39bbed2881126ac4782/vault  106G   13G   88G  13% /home/chronos/user
tmpfs                                                         128K   12K  116K  10% /run/crw
chronos@localhost / $ 
```

**Comment by giliammc** [comment]
fstrim didn't work 
```
chronos@localhost / $ fstrim /mnt/stateful_partition/encrypted
bash: fstrim: command not found
chronos@localhost / $ 
```

**Comment by DennisLfromGA** [comment]
@giliammc - 'fstrim' needs root permissions, try: `sudo fstrim /mnt/stateful_partition/encrypted`

**Comment by giliammc** [comment]
ok

**Comment by giliammc** [comment]
```
sudo fstrim ``` doesnt apear to have done anything
```
chronos@localhost / $ sudo fstrim /mnt/stateful_partition/encrypted
chronos@localhost / $ lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    0 111.8G  0 disk 
├─sda1          8:1    0 107.7G  0 part /mnt/stateful_partition
├─sda2          8:2    0    16M  0 part 
├─sda3          8:3    0     2G  0 part 
│ └─vroot     254:0    0   1.2G  1 dm   /
├─sda4          8:4    0    16M  0 part 
├─sda5          8:5    0     2G  0 part 
├─sda6          8:6    0   512B  0 part 
├─sda7          8:7    0   512B  0 part 
├─sda8          8:8    0    16M  0 part /usr/share/oem
├─sda9          8:9    0   512B  0 part 
├─sda10         8:10   0   512B  0 part 
├─sda11         8:11   0     8M  0 part 
└─sda12         8:12   0    16M  0 part 
loop0           7:0    0  31.8G  0 loop 
└─encstateful 254:1    0  31.8G  0 dm   /mnt/stateful_partition/encrypted
zram0         253:0    0   2.7G  0 disk [SWAP]
chronos@localhost / $ 
```

**Comment by drinkcat** [comment]
IIRC encstateful size grows dynamically?
