### ISSUE TITLE
croutonversion: "unknown"

### ISSUE THREAD

**Issue by mosquito710** [dnschneid/crouton#1941]
I received an update to Cromeos, and tried to update my chroot after installing it. But it failed because it was trying to fetch urls with "unknown" where the version should be. This seems to be because my crountonversion just says "unknown." 

Here's the exact output: 
```
(trusty)[redacted]@localhost:~$ croutonversion
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xiwi
targets: xiwi,xephyr,xfce,audio,core,extension,keyboard
host: version 6946.70.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jul 7 19:37:29 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

I tried searching and didn't see this exact issue.

**Comment by dnschneid** [comment]
What's the output when you try to update the chroot?
