### ISSUE TITLE
Implement power manager overrides per default if chroot is stored on a removable device

### ISSUE THREAD

**Issue by lyxell** [dnschneid/crouton#1942]
Would it be possible to implement the power manager overrides defined in https://github.com/dnschneid/crouton/wiki/Power-manager-overrides per default if the chroot is stored on a removable device by adding the overrides to the enter-chroot shell script?

As far as I know everyone who is using a removable device encounters problems if they dont use the overrides.

**Comment by dnschneid** [comment]
It seems to be highly platform-specific; for some, removable devices work fine.  The overrides listed there really break power management as a workaround and can't be added as defaults.
