### ISSUE TITLE
Starting Ubuntu Results in Sleep Mode-ish Screen?

### ISSUE THREAD

**Issue by etpof** [dnschneid/crouton#1943]
Hello. I've been running Crouton on my HP Chromebook for about a week now and haven't had any problems (But obviously I am a Linux noob). Now, however, during a normal boot, I accidentally pressed the down key and my computer beeps. Now Ubuntu won't start and only lead me to a blank screen as if in sleep mode, and I have to hard restart to get out of it. I've tried other keys to see if pressing the down key was the problem, and maybe this would undo the effect, but had no luck. I restarted a couple of times but have had no luck either. I would try updating Crouton, but like a noob, I didn't save the file. When I try to redownload it, I'm notified that I don't have enough space. Unfortunately, I store nothing on Chrome OS and all my files are on Ubuntu, so I can't delete anything to free up space. I wouldn't like to have to completely reinstall it, but if there is a command to delete files on Ubuntu while using Chrome, that would help, but I doubt one exists. Or I could update it from a USB containing the Crouton file, as updating seems to fix most problems, but I'm not sure what the path to the file would be or if this is possible altogether. Any ideas to fixing this?﻿

EDIT:
So by exploring the files app to try to free up some space, I've been able to use "Show Hidden Files" delete some items in the .Trash-1000 folder and free up an entire 2.7 GB of space. I recognized the files in the folder as files I deleted in the past, so hopefully I just deleted those and not anything else on Ubuntu. I'm updating it at the moment so I'll see if it starts after.

SOLVED!
Updating Crouton solved this problem and I am now able to start normally again. It did delete my wallpaper but my files are just as they were. I'm still stumped as to what happened so if anyone could explain why this happened that would help.

**Comment by dnschneid** [comment]
You probably got a Chromium OS update that broke crouton, which updating crouton fixed.  Purely coincidental with the down key beep...

**Comment by etpof** [comment]
@dnshneid
I'm not sure. I usually never update Chrome because I never actually leave Ubuntu that often (yeah I know that's not good for device power :P). 
It very well could have been, and I was wondering if the beep had anything to do with it. Why does that beep exist during load?

**Comment by DennisLfromGA** [comment]
> I usually never update Chrome because I never actually leave Ubuntu that often

Chrome OS updates on it's own in the backgrond unless you manually stop the update engine each and every time you log in.

**Comment by tedm** [comment]
@DennisLfromGA Dennis, I'm sure you're correct here, but then what part does the up arrow indicating a restart do if the background updates are automatic? This is a controversial method of updating, eliminating ChromeOS from several specific server and security deployments that I am aware of.

**Comment by DennisLfromGA** [comment]
> ...but then what part does the up arrow indicating a restart do if the background updates are automatic?

The 'up arrow' only indicates that an update has **already** been downloaded and installed to the alternate boot pair (ROOT-A/B,KERN-A/B) and your Chromebook is ready to reboot.

> This is a controversial method of updating, eliminating ChromeOS from several specific server and security deployments that I am aware of.

Sorry, I don't follow, what is a controversial method of updating?

**Comment by etpof** [comment]
@DennisLfromGA
You are probably correct in what you've said in the first post. And it probably was a Chrome update. However, Chrome instructs me to "Restart to Update" when I do update. Because of Ubuntu, my Chromebook never actually restarts correctly. This doesn't interfere with updating according to this I guess right? Then again I may have just installed a Chrome update without remembering.

**Comment by tedm** [comment]
@DennisLfromGA Dennis, imagine that your car or truck firmware updated randomly overnight because some programmer thought they had optimized something. But your car was running fine for months. You're planning a long trip through the desert and there was a corner case where the programmer (and QA) didn't account for, say temp. or humidity or something, and you got stuck in the desert with no easy way to revert to the working firmware. Not fun.

**Comment by DennisLfromGA** [comment]
> Chrome instructs me to "Restart to Update" when I do update.

Yep, I think that wording is a little misleading but I suppose if you never restarted the Chromebook, you wouldn't *get* the update so I guess in that sense it's correct.

> Because of Ubuntu, my Chromebook never actually restarts correctly. This doesn't interfere with updating according to this I guess right?

I usually shutdown/logoff any running chroots *and* exit any active crosh shell sessions before I hit the restart up arrow, that way I know I've left things in a *'clean'* state. Leaving a chroot running when you hit the restart up arrow should not interfere with updating Chrome OS but it may leave your chroot in a bad way, and possibly Chrome OS too. Chrome OS isn't *aware* of any running chroots so it doesn't send any 'shutdown' signal to them - I don't believe.

> Then again I may have just installed a Chrome update without remembering.

That happens to me too, I've shutdown my Chromebook without noticing the 'up arrow' and when I start up again I find I'm running a new version of Chrome OS.

**Comment by DennisLfromGA** [comment]
@tedm,

>> Sorry, I don't follow, what is a controversial method of updating?

> Dennis, imagine that your car or truck firmware updated randomly overnight because some programmer thought they had optimized something. But your car was running fine for months...

Okay, I see what you were alluding to earlier now. 
Google's update method of Chrome OS has been around since it's inception and, I for one, welcome it and I think a lot of other Chromebook users/owners do too. I suppose it's *controversial* to some but I think they're in the minority.

We're getting a little off track here so I think we should stop. This *philosophical* discussion about Google's update scheme could be carried on ad nauseam I believe...

**Comment by etpof** [comment]
@DennisLfromGA
We should probably stop but I just have one more question. When I try to choose shut-down or restart from the Ubuntu menu, my computer never does anything but continue running. I used to be able to choose log-off and get back into Chrome. Now, however, logging off takes me to this same screen and I hard-restart to get back on. Is this not supposed to happen? Or is this bad for the chroot?

**Comment by DennisLfromGA** [comment]
@etpof - Sorry, I wasn't meaning you should stop, you have a legitimate question/problem, I was referring to our *rant* about the Chrome OS update mechanasm.

> When I try to choose shut-down or restart from the Ubuntu menu, my computer never does anything but continue running.

I don't think it's a good idea to choose shutdown or restart from the Ubuntu menu, logging off is sufficient to shut down the chroot - if it's working.

> Now, however, logging off takes me to this same screen and I hard-restart to get back on.

If by the same screen you are referring to the 'Sleep Mode-ish Screen', then that's a real problem and we should try to find out why it's happening.

If you could show us the output of `sudo edit-chroot -al`, we can find out what release, platform, and xmethod you're using and get closer to a resolution.

**Comment by etpof** [comment]
Here's the copied text and screenshot:

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150620222151~master:89796a99
release: utopic
architecture: amd64
xmethod: xorg
targets: xiwi,unity
host: version 7077.111.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jul 28 16:55:35 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

![screenshot 2015-08-12 at 10 05 08 am](https://cloud.githubusercontent.com/assets/13365820/9225857/b4999458-40d9-11e5-8454-334f0bf83b87.png)

I am aware I am running Utopic, an unsupported version, and its a long story explaining why I upgraded. I would downgrade, but most recommend I don't. Hopefully I can still be helped? I'm running an HP Chromebook 11 if that is important and or helps. Thanks.

>I don't think it's a good idea to choose shutdown or restart from the Ubuntu menu, logging off is sufficient to shut down the chroot - if it's working.

I'm aware of this, and I don't usually use these, however, when I first downloaded Ubuntu, I used to be able to shut-down and restart after granting access when it prompted me for my password. Now, however, it does nothing, if this at all is important.

> If by the same screen you are referring to the 'Sleep Mode-ish Screen'...

Yes, I am. Should've been more specific. My bad. There may be a better term to use for this situation that I'm not sure of. The computer hums and continues to run, but there is no display on the screen.

**Comment by DennisLfromGA** [comment]
@etpof,

>>host: version 7077.111.0 (Official Build) stable-channel falco 

> I'm running an HP Chromebook 11 if that is important and/or helps.

I think that's an HP Chromebook 14 (Falco) like one of mine.
I currently have three chroots installed with xiwi - mdwatson(precise), trusty, and wheezy and I haven't experienced anything like you're describing so maybe it's 'utopic' specific.

- Do you have any screensavers running in your chroot?

- Do you always run your chroot full-screen (-X xiwi-fullscreen) or have you tried running it in a tab (-X xiwi-tab) or window(-X xiwi) ?

In any of the three xiwi modes, I have always been able to get back to Chrome OS via the <kbd>F5/switch window</kbd> key. Is that not working for you?

**Comment by etpof** [comment]
>>>host: version 7077.111.0 (Official Build) stable-channel 

>>I'm running an HP Chromebook 11 if that is important and/or helps.

>I think that's an HP Chromebook 14 (Falco) like one of mine.

Whoops! My bad. Forgot that was listed there and forgot my own Chromebook model as well! Anyway, I only have 1 chroot installed (as I only need 1).

>Do you have any screensavers running in your chroot?

>Do you always run your chroot full-screen (-X xiwi-fullscreen) or have you tried running it in a tab (-X xiwi-tab) or window(-X xiwi) ?

I never run screensaver a in my chroot, and I run it in fullscreen. I've tried the crouton extension to run it in a tab, (not xiwi-tab) but I never really liked it so I switched back. Is the extension similar to xiwi-tab?

>In any of the three xiwi modes, I have always been able to get back to Chrome OS via the F5/switch window key. Is that not working for you?

This does not work for me, no. I have wondered why these shortcuts have been like this. Come to think of it however, when I was able to log-off, restart, and shut-down correctly from Ubuntu, this was with trusty. Maybe this is a utopic specific problem like you said? And maybe there is a safe way to downgrade back to trusty? Though I'm doubtful.
