### ISSUE TITLE
Help running Lubuntu after installing from Ubuntu (Unity)

### ISSUE THREAD

**Issue by monsterrex** [dnschneid/crouton#1946]
Sorry if this is a simple or stupid question but being decently new to Crouton I'm in the dark on how to boot into Lubuntu after installing it through the Ubuntu command "sudo apt-get install lubuntu-desktop". I must be doing something wrong since I know Lubuntu would not be started with the "sudo startunity" command and when I do use that I still boot into Ubuntu. How would I go about using Lubuntu instead of Ubuntu and how would I remove Ubuntu once I am switched? Thanks in advance!

**Comment by DennisLfromGA** [comment]
It would be started with the `sudo startlxde` command if either or both 'lxde' or 'lxde-desktop' was specified as a crouton target during installation or an update. 

If you added it yourself in the chroot using `apt-get ...`, then you wouldn't have the 'startlxde' script in your `/usr/local/bin` on the Chrome OS side.

However, the 'startlxde' script basically does this: `exec xinit /usr/bin/startlxde` in the chroot so you could  probably run it using something like this from a crosh shell:
 `sudo enter-chroot xinit /usr/bin/startlxde`.

**Comment by monsterrex** [comment]
Thank you but I decided with the space I had available I removed Ubuntu, installed lxde, then installed Lubuntu from there.

**Comment by DennisLfromGA** [comment]
That'll work. 
I just used 'lxde-desktop' as a crouton target, I think it does about the same thing.
The 'lxde-desktop' target says: 
`install ubuntu=lubuntu-desktop,task-lxde-desktop -- network-manager`
When I look at the packages installed, it shows lubuntu-desktop along with a slew of other lubuntu-* stuff.

**Comment by KurtWAndrews** [comment]
@dnschneid,

Does the 

install ubuntu=lubuntu-desktop,task-lxde-desktop -- network-manager
Install the lubuntu os,  or just the desktop over full Ubuntu?

**Comment by DennisLfromGA** [comment]
@KurtWAndrews,

Not to speak out of turn and certainly not to speak for @dnschneid but the [lubuntu-desktop](https://packages.ubuntu.com/xenial/lubuntu-desktop) *just* installs the desktop, not the full Ubuntu distro.

*Hope this helps,*
-**DennisLfromGA**
