### ISSUE TITLE
Named pipe not creating network connection

### ISSUE THREAD

**Issue by keithfarvis** [dnschneid/crouton#1947]
I am experimenting with snapcast https://github.com/badaix/snapcast whose snapserver process broadcasts audio streams to remote clients running snapclient processes through the mechanism of named pipes. This works well from my Ubuntu desktop but on my Acer 720 Chromebook running crouton (Unbuntu 14.04) while I can successfully loopback output from the snapserver to a local snapclient using a named pipe, nothing gets sent to remote snapclients on the network.  Is this because network socket creation is handled by Chrome OS rather than by crouton and if so, is there some workround I can do for it?

**Comment by DennisLfromGA** [comment]
> nothing gets sent to remote snapclients on the network

Maybe you just need to open up the firewall a little. See [Running servers in crouton](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton) for more info.
You may need to adjust outbound traffic rules, just guessing...
