### ISSUE TITLE
How to start KDE Authorization Service?

### ISSUE THREAD

**Issue by Windoze98** [dnschneid/crouton#1948]
I need help starting a service. Applications such as Muon Package manager use the polkit-kde-1 service for authorization. I think I need to manually start this service using the rc.local script. But I don't know what command to put in the file for it to start the service.

Any help would be appreciated!

**Comment by tista500** [comment]
@Windoze98 Please see: http://packages.ubuntu.com/trusty/amd64/polkit-kde-1/filelist

The binary is `/usr/lib/kde4/libexec/polkit-kde-authentication-agent-1`.

Regards.

**Comment by Windoze98** [comment]
Unfortunatly, inputting that into rc.local still didn't fix my authorization errors. Whenever I use Muon Updater or Muon Package Manager, I keep getting the error:

The operation cannot continue since proper authorization was not provided.

**Comment by tista500** [comment]
@Windoze98 Although I really don't know K desktop, let us know the 2 outputs of:
 `ps aux | grep dbus` and `ps aux | grep polkit`.

In Gnome, polkit-agent should be launched as "User's process" instead of "Root's process".

Regards.

**Comment by dkovach** [comment]
For mere mortals using Crouton -- which is amazing -- but, if I wanted to start with a less striped down Kubuntu version - is that possible w/ another target that is out there?

So things like authorization and Java would be able to be installed easier (vs. turning on the level of software apt-get has access to...)

For hours I have been trying to get Muon (installed separately) to have proper authorizations, or just installing GEDIT or NANO, again hassle without authorizations...

**Comment by dkovach** [comment]
My original chroot was via... 

~/Downloads/crouton -t kde

Did that install Trusty or Precise? is there a version that comes a little more ready to roll? but isn't full blown Kubuntu Desktop...

**Comment by mkvf** [comment]
I'm having the same problem.  I've tried launching muon using kdesudo


>kdesudo muon-installer


A graphical window opens and requests my root password.  In Konsole, the following appears:


>Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.cannot open shared object file: No such file or directory)" 
>kdesudo(29997) KDESu::KDESuPrivate::KCookie::getXCookie: No X authenticationo set for display  ":1" 

>QDBusConnection: session D-Bus connection created before QCoreApplication. Acation may misbehave.
>Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.cannot open shared object file: No such file or directory)" 
>QDBusConnection: session D-Bus connection created before QCoreApplication. Acation may misbehave.


The same happens when trying to launch the package manager, kdesudo muon.

Any ideas? I've been googling around for ways to install the library refered to in the Terminal message, but not really getting anywhere.

**Comment by bedfelllow** [comment]
Did anyone find a fix to this? I'm really enjoying the KDE experience in Chromebook, but this authorisation issue is a real pain.
