### ISSUE TITLE
Crouton Install Utopic Fails

### ISSUE THREAD

**Issue by promanczuk** [dnschneid/crouton#1957]
Hi, 

just tried to install crouton ubuntu utopic on my Acer C720 (i3, Intel HD, 4 GB RAM,32 GB). The installation fails with the following error:

``` 
Setting up rsyslog (7.4.4-1ubuntu11.2) ...
The user `syslog' is already a member of `adm'.
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: initscript rsyslog, action "restart" failed.
dpkg: error processing package rsyslog (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up sudo (1.8.9p5-1ubuntu2.1) ...
Setting up cpio (2.11+dfsg-2ubuntu1.1) ...
Setting up libcgmanager0:amd64 (0.32-4ubuntu1.4) ...
Processing triggers for libc-bin (2.19-10ubuntu2.3) ...
Processing triggers for initramfs-tools (0.103ubuntu8) ...
Errors were encountered while processing:
 rsyslog
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.
```

Any help would be appreciated...

best

**Comment by tista500** [comment]
@promanczuk You should search the precious issues to find solutions before filing the report... See https://github.com/dnschneid/crouton/issues/1391#issuecomment-72538256

This is the `invoke-rc.d` problem to be caused that rsyslog's post.install script had tried to start itself via upstart init system at the final stage of installation. You should see: `/var/lib/dpkg/info/rsyslog.postinst`

Then an alternate method:

1.  Open crosh shell and do `sudo enter-chroot` (decline to run the preparation script)

2. Edit `/var/lib/dpkg/info/rsyslog.postinst` like this:
```
--- rsyslog.postinst	2015-07-22 06:51:57.838053672 +0900
+++ rsyslog.postinst.new	2015-07-22 06:33:48.459031739 +0900
@@ -110,7 +110,7 @@
 	else
 		_dh_action=start
 	fi
-	invoke-rc.d rsyslog $_dh_action || exit $?
+	invoke-rc.d rsyslog $_dh_action || exit 0
 fi
 # End automatically added section
 # Automatically added by dh_installinit
```

3. Do `sudo dpkg --configure rsyslog` to force finishing dpkg.

4. Do `sudo exec /prepare.sh`

Finally the crouton installation process would finish normally...

Regards.

**Comment by promanczuk** [comment]
Sorry, I actually searched the issues, but probably got the keywords wrong.

But Thanks a lot for your help!

best
