### ISSUE TITLE
Add dock window left/right actions to xiwi windows in Crouton Integration Extension 

### ISSUE THREAD

**Issue by darcyparker** [dnschneid/crouton#1958]
In ChromeOS, <kbd>alt</kbd> + <kbd>[</kbd> and <kbd>alt</kbd> + <kbd>]</kbd> docks the window left and right respectively.  I understand when in a xiwi window, these keystrokes are passed through into the xiwi application because the xiwi application may have some purpose for these keystrokes.

Is it possible to have some action/button in the xiwi window title bar for docking the window left and right? (It could go next to the existing minimize and maximize buttons.)  I find these actions so helpful to layout a browser and my terminal (with text editor) at the same time.

Or is there some kind of tiling feature in ChromeOS that I don't know about?

**Comment by shippy** [comment]
@darcyparker: xiwi windows are standard ChromeOS window. This means that if you long-click the "maximize" button (middle), the adjacent buttons will switch to "<" and ">", which have the left- and right-docking functionality.

No idea how to stop the xiwi-launched application from capturing keystrokes.

**Comment by dnschneid** [comment]
We could have the crouton extension pass through certain shortcuts (if you request), but remember that any combos it lets Chromium OS handle are combos that will never make it to the chroot in any circumstance.
