### ISSUE TITLE
Crouton doesn't work after upgrade

### ISSUE THREAD

**Issue by vladimirvivien** [dnschneid/crouton#1961]
This is my third time I end up with a broken crouton after an update.  It seems no matter what I do and which directions i follow to upgrade chroot, I end up with the same result (see below).  Thankfully, I keep a backup of an old version (circa May) that I revert to keep working.

System
* Chromebook Pixel 2
* Ubuntu trusty
* Gnome 3
* Xiwi
* Chrome Extension

What I have tried
* I have update crouton with `sudo sh ~/Downloads/crouton -u -n <chroot>`
* I have downloaded directly from the provided link on project page
* I also have done the `sudo enter-chroot` then update from that within the chroot as documented on homepage.

Result
None of these approach work or fix my issue.  After I successfully update my chroot, when I start it using `sudo startgnome`, I always get disconnected from the X server immediately as shown in the output below.

Output
The xiwi window launches black goes away after a few seconds with result

```
$ sudo startgnome -n gnome-trusty
Entering /mnt/stateful_partition/crouton/chroots/gnome-trusty...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Mon Jul 13 22:32:37 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=8f7f09fd-3fa9-c04b-8582-dd9473131ef9/PARTNROFF=1 hashtree=PARTUUID=8f7f09fd-3fa9-c04b-8582-dd9473131ef9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=0a61dc61b59537ad616e7cae0d7c72fb9fcfcd0c salt=94f7d0efb4a4b2249fefb8384a4bdef37ba4a09908efaa9068f7d03a32a0fe23" noinitrd vt.global_cursor_default=0 kern_guid=8f7f09fd-3fa9-c04b-8582-dd9473131ef9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jul 23 17:04:02 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: amd64
xmethod: xiwi
targets: gnome,xiwi,touch,gnome-desktop
host: version 6946.86.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Mon Jul 13 22:32:37 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/gnome-trusty as another instance is using it.
```

**Comment by DennisLfromGA** [comment]
@vladimirvivien, 

I don't have a Pixel2 (I wish, I wish) to experiment on but I have had similar problems with Chrome OS updates causing problems and, like you, I would do a crouton update to try to *fix* it.
In all but a few cases, it worked and I was back in business. 
Being on the stable channel like you are, I would think this problem would be rare, I haven't heard of that many others running into this constantly.

This is the place to seek help though, from others and the experts.

The one thing I would recommend you to try is using xmethod 'xorg' instead of 'xiwi', you wouldn't have the convenience of your chroot in a tab/window/full-screen and you would have to revert to the <kbd>Ctrl+Alt+Shift+<-/-></kbd> key combo to get back and forth but it might cause less problems and give you the added advantage of hardware acceleration.

You can add it to your existing chroot using:

  `sudo sh ~/Downloads/crouton -t xorg -n gnome-trusty -u`

Doing this, however, will make 'xorg' your *default* xmethod so to use 'xiwi' instead when launcing yu'd use: 

  `sudo startgnome -n gnome-trusty -X xiwi`.

If 'xorg' just doesn't work or isn't for you, you can change the xmethod back to 'xiwi' using:

 `sudo sh ~/Downloads/crouton -t xiwi -n gnome-trusty -u`

-DennisL

**Comment by vladimirvivien** [comment]
@DennisLfromGA 
Thank you for taking your time and help with this.  (sidenote: the pixel 2 is a great machine, if you ever get a chance to update).

I use xiwi because of the convenience of windowed environment. Luckily, my last chroot install still works though i get a warning of it being out of date.  So I will continue to use an old chroot for now until I get this figured out.  If all fails maybe I will go full xorg.

Thanks again for the help.

**Comment by vladimirvivien** [comment]
Anyone else who may be able to help is welcome to chime in. 

Thanks.

**Comment by vladimirvivien** [comment]
@DennisLfromGA 
Thanks again.  I think Xorg will ok for me with Gnome.
My first stint was with Ubuntu-desktop unity and was slow, but Gnome feels more responsive.
Thanks for the help.

**Comment by DennisLfromGA** [comment]
@vladimirvivien - You're welcome, sorry there's no real solution for 'xiwi' yet...

> My first stint was with Ubuntu-desktop unity and was slow, but Gnome feels more responsive.

I like gnome better than unity also but, lately, I've been stuck on the lxde-desktop since it's light and quick.
