### ISSUE TITLE
Ubuntu can't recognize more than 1 core on the tegra k1

### ISSUE THREAD

**Issue by SimplySerenity** [dnschneid/crouton#1962]
I noticed something a little weird after installing trusty, with lxde. My cpu would max out and then still take longer than expected while doing something simple like just loading chromium. So I checked my cpu info and it's only recognizing and using 1 core. I'm not sure if it's a driver issue or a limitation of crouton? This goes a bit over my head.

**Comment by tista500** [comment]
You mean `cat /proc/cpuinfo | grep 'cpu cores' | cut -d: -f2` answered "1" ?

**Comment by SimplySerenity** [comment]
@tista500 Well that command doesn't return anything, neither does grep 'core id', it doesn't have any information on other cores, it just has information on the first one as processor '0'.

**Comment by tista500** [comment]
OK. let me see the output of `ls /sys/devices/system/cpu/`.

**Comment by SimplySerenity** [comment]
@tista500 okay, that list shows cpu 0-3. So all four cores show up there.

**Comment by tista500** [comment]
Nice. so please give it a try: `sudo sh -c "echo '1' > /sys/devices/system/cpu/cpu1/online"`. (this could enable the 2nd core).

**Comment by SimplySerenity** [comment]
@tista500 Okay, how will I know if it worked?

**Comment by tista500** [comment]
/proc/cpuinfo would be updated automatically. Or easily you can some tests by running apps with seeing `top`.

**Comment by SimplySerenity** [comment]
/proc/cpuinfo still only shows processor 0, What do you mean seeing top?

**Comment by SimplySerenity** [comment]
Okay so further confirmation. If I run the command lscpu it finds all 4 cpu cores, but it says that only cpu 0 is online and cpu 1-3 are offline.

**Comment by tista500** [comment]
Well, how about `cat /sys/devices/system/cpu/cpu[0-3]/online`? Said "0"?

**Comment by SimplySerenity** [comment]
1
0
0
0

**Comment by smibarber** [comment]
This is intentional, it's called cpuquiet.
http://www.linuxplumbersconf.org/2012/wp-content/uploads/2012/08/cpuquiet.pdf

**Comment by tista500** [comment]
@smibarber Ah thanks! I don't know why K1 has an "online" flag on first core0 though...

**Comment by SimplySerenity** [comment]
@smibarber so it does this use less power and make less heat essentially? Which would mean that right now it's "LP cluster" But what if I'd rather be in G cluster? What makes the change?

**Comment by tista500** [comment]
OK. give it a try:
```
echo 0 > /sys/devices/system/cpu/cpuquiet/tegra_cpuquiet/enable
echo 1 > /sys/devices/system/cpu/cpu0/online
echo 1 > /sys/devices/system/cpu/cpu1/online
echo 1 > /sys/devices/system/cpu/cpu2/online
echo 1 > /sys/devices/system/cpu/cpu3/online
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
```
Those could change all governor to "Max Performance".

**Comment by SimplySerenity** [comment]
Okay, in my cpuquiet folder there isn't a tegra_cpuquiet but instead available_governors, current_governor, hotplug_timeout, and runnable_threads. The available governors are userspace, and runnable. The current governor is runnable. 

But the good news is that after switching the scaling_governor to performance and writing the cpu_online state for cores 1-3 to online. They are seemingly awake! I opened up three tabs of youtube and had three videos running at once without maxing the cpu.

Thanks for all the help guys.

**Comment by tista500** [comment]
Sounds nice, and yep the story has both bad news and good news. :-P

Then you can set them permanently by adding such `echo 1 > ...` into `/etc/rc.local` so that your chroot will applied them at startup automatically (But be careful. You should insert your custom lines **above** `exit 0`).

Regards.
