### ISSUE TITLE
OpenSSH startup: could not load host keys error

### ISSUE THREAD

**Issue by aafrey** [dnschneid/crouton#1963]
apologies if this is old new, but i;ve spent the better part of two days trying to get ssh started in crouton. I've followed the setup instructions found here: https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton

but to no avail... my /etc/rc.local file looks like this:
`/sbin/iptables -I INPUT -p tcp --dport 22 -j ACCEPT`
`mkdir -p -m0755 /var/run/sshd`
`/usr/sbin/sshd`
`exit 0`

when i run
`$service ssh start`

i get this error
`* Starting OpenBSD Secure Shell server sshd`
`Could not load host key: /etc/ssh/ssh_host_rsa_key`
`Could not load host key: /etc/ssh/ssh_host_dsa_key`
`Could not load host key: /etc/ssh/ssh_host_ecdsa_key`
`Could not load host key: /etc/ssh/ssh_host_ed25519_key`
                                                                    `[ OK ]`

i've regenerated and reconfigured everything multiple times to no avail. any help appreciated. thanks

**Comment by tista500** [comment]
@aafrey, I haven't such issue in my OpenSSH-server. It would work well out of the box, maybe. :(

So did you try re-install openssh-server and re-create ssh-key? Seahorse (a Gtk frontend for managing personal keys) would be useful if you had graphical desktop. Then if I remembered well, `/etc/ssh/` directory and contents were generated automatically when we install a `openssh-server` properly.

Regards.

**Comment by drinkcat** [comment]
Which release is this on? IIRC these keys should be generated either at install time, or when the service is first started...

**Comment by drinkcat** [comment]
This page is old but probably still relevant: https://www.digitalocean.com/company/blog/avoid-duplicate-ssh-host-keys/ . Try to run:
`/usr/sbin/dpkg-reconfigure openssh-server`
