### ISSUE TITLE
Restore won't work.

### ISSUE THREAD

**Issue by taserman21** [dnschneid/crouton#1964]
I recently backed up one of my Chroots but now when I try to restore it, it prints:
/home/chronos/user/Downloads/Android_Dev-20150720.tar.gz doesn't appear to be a valid tarball.

**Comment by BlnKgl** [comment]
I got the same error message - and found that it was just a typo in the file name, nothing wrong with the tarball once I typed the name correctly, but the error message was misleading.

**Comment by dnschneid** [comment]
Is that the case for you too, @taserman21?  That message should be fixed.

**Comment by taserman21** [comment]
I already have made another chroot with the same aspects and features as
the old one but I am almost positive that I typed it correctly as I typed
it at least 5 times.
