### ISSUE TITLE
Cannot read or display Chinese and Japanese 

### ISSUE THREAD

**Issue by qAp** [dnschneid/crouton#1965]
Hi,
I cannot get Languages to work by following the steps at
https://github.com/dnschneid/crouton/wiki/Languages

For example, reading a csv file with Japanese in it in IPython:

![cantread_japanese](https://cloud.githubusercontent.com/assets/2902346/8888349/8620f32e-32dc-11e5-8ef2-c79bd70cc3b0.png)

I can, however, read it on a linux machine:
![japanese](https://cloud.githubusercontent.com/assets/2902346/8888353/96077006-32dc-11e5-87ef-e8cd2f3565b5.png)

But I cannot display it in Crouton:
![questionmark](https://cloud.githubusercontent.com/assets/2902346/8888352/8e4ce27e-32dc-11e5-95c3-f49c86ec351e.png)

I have also tried to set up Chinese input using Pinyin, which normally works on linux machine, but does not work in Crouton.

Is it a package that is missing?  I have installed locales and encodings for the languages I'm interested in, as well as the package ttf-ancient-fonts.

**Comment by tonyxue** [comment]
Is it in Crosh or X11/Xiwi?

**Comment by qAp** [comment]
@tonyxue So, in my chromebook I open a crosh, type `shell`, then `sudo startunity` to get into the Crouton mentioned above.  The top image is when I use IPython that is installed in Crouton; file does not even load.  For the second image, the same file is loaded on some linux server, and I connect to it via my other computer that is not a chromebook, but has a pure Ubuntu installation on it; file is loaded fine, and Japanese is displayed fine.  For the third image, I connect the same server from my chromebook's crouton; file is loaded (from before), but the Japanese is not displayed correctly.

**Comment by qAp** [comment]
In brief, what I am finding is that

Under a normal Ubuntu installation, a CSV file containing Japanese can be loaded with the Japanese displayed fine.

In Crouton, Japanese is not displayed correctly, and a CSV file containing Japanese cannot be loaded.

In both cases, the loading of the file is done using the same Anaconda Pandas.

**Comment by tista500** [comment]
@qAp Did you install `language-pack-ja` already? From your attached images, I don't think it seems to be missing fonts but a locale for Japanese...

In general, we can apply to change locales with `sudo update-locale` in terminal.
For example (add Japanese locale to default US):
```
sudo update-locale LANGUAGE=en_US:en:ja
```
Or GUI in Gnome, use `language-selector-gnome`.

Regards.

**Comment by qAp** [comment]
@tista500 Yes, `language-pack-ja` is installed, and `sudo update-locale LANGUAGE=en_US:en:ja` did not make a difference.  

I have made the file available at https://drive.google.com/file/d/0B34629crp1uGc0ZiMUVMaXBySFE/view?usp=sharing
if anyone wants to have a go.

**Comment by tista500** [comment]
@qAp On my Vivid Gnome, I could read that file via `less` in gnome-terminal even if `LANGUAGE=en_US:en` was set... :(

![screenshot from 2015-08-08 13-43-51](https://cloud.githubusercontent.com/assets/6073622/9149106/f68847dc-3dd3-11e5-829a-38cdfd4f9e25.png)

Though I didn't know about Python at all, I don't think this issue might not be related to crouton environment anyway.

Regards.

**Comment by qAp** [comment]
@tista500 Thanks for the screenshot.  In locale's output, I noticed that except for LANGUAGE being the same as yours, my LANG was empty while the rest were POSIX.  After making these the same, I can now read the .csv file with no problems.   I must have used `update-locale` in a wrong way before.
