### ISSUE TITLE
Unity "Cannot Connect"

### ISSUE THREAD

**Issue by etpof** [dnschneid/crouton#1968]
I recently updated to Ubuntu 15.04 and was running fine until I shutdown for the day. When I tried to reboot Unity I updated Crouton and then tried to start with "sudo startunity" as I would normally. However I get this error report:

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.17.1
Release Date: 2015-02-10
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Jul 14 00:18:51 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=d03ab519-05b9-3444-a989-bc1701b2c0fe/PARTNROFF=1 hashtree=PARTUUID=d03ab519-05b9-3444-a989-bc1701b2c0fe/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=ac631d7057709155cc343dadbc4c436390cd7c5a salt=ece2d11ed0bee603ed305a767fa0ff120ea11e3f08413850589e2a6d4860bd06" noinitrd vt.global_cursor_default=0 kern_guid=d03ab519-05b9-3444-a989-bc1701b2c0fe add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 19 March 2015  09:26:59AM
xorg-server 2:1.17.1-0ubuntu3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Jul 26 07:44:08 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
get chip id failed: -1 [13]
param: 4, val: 0
[intel_init_bufmgr:1063] Error initializing buffer manager.
EGL_MESA_drm_image required.
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150716185530~master:aba2c948
release: vivid
architecture: amd64
xmethod: xiwi
targets: xiwi,unity
host: version 6946.86.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jul 14 00:18:51 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

I'm not sure what much of this means, but here are the lines that I think may be part of the error:

[intel_init_bufmgr:1063] Error initializing buffer manager.

/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1

Error: not connected.
Cannot connect to extension, retrying...

The final lines are probably what is causing this, as I believe it is trying to connect to the Crouton extension. I've tried this extension, but it only opens a tab with my desktop files and wallpaper, and nothing else, I'd really like to go back to using everything normally, not in another tab, but instead with a task bar, settings, files, etc. (basically without the extension), without reinstalling Crouton if possible. If there is any way I can continue to do this and keep Ubuntu 15.04, that would be great. Otherwise I'd be fine with downgrading back to 14.10 if possible.

**Comment by tista500** [comment]
@etpof See this thread: Ubuntu 15.04 (Vivid) fails to install #1706.

1st, Vivid can't be installed properly (and devs said it's unsupported yet) via fresh-install. And to make matters worse, even if we could get passed crouton installation process, we will see the brick wall that "Oh Unity won't work at all, why?". 

2nd, Ubuntu Utopic (14.10) had got outdated in 23 Jul, 2015 already. So you should NOT use it anymore.

3rd, Downgrading release is too much risky and never be recommended ever. If you have done backup with crouton, you'd better to restore it from the previous snapshot to go back to.

Regards.

**Comment by etpof** [comment]
@tista500

I was able to fix the issue by deleting the chroot and loading a backup. I was not installing 15.04 via a fresh install however, as my taskbar was constantly notifying me that 14.10 was in fact out of date. I'll make sure not to downgrade I. The future as well. However, if 14.10 is out of date and 15.04 is unsupported, then which version should I use? Should I just go with another distro?

**Comment by tista500** [comment]
@etpof Try Trusty (14.04-LTS). it has 5 years support as LTS.

Regards.

**Comment by etpof** [comment]
Never mind. Just saw your comment as I was editing. I'll go ahead and use that then

**Comment by dnschneid** [comment]
It's going to be a while before vivid/wily is fully supported due to the systemd integration...

**Comment by etpof** [comment]
@dnschneid
Ok. Thank you
