### ISSUE TITLE
startx fails with repeated Invalid MIT-MAGIC-COOKIE-1

### ISSUE THREAD

**Issue by parkerlreed** [dnschneid/crouton#197]
Steps I took:
1. created a base x11 chroot
    sudo sh -e ~/Downloads/crouton -t x11
2. entered the chroot
    sudo enter-chroot
3. installed mate-desktop from
    http://wiki.mate-desktop.org/download
4. Created a .xinitrc file in the chroot user home folder with the command to launch mate
    echo "exec mate-session" > ~/.xinitrc
5. tried to launch x
    startx

It tries to launch, switches to the third tty to run X but nothing shows up. After switching back to ChromeOS there is a repeating line in the X server output.
    Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key..

Not sure if I am missing anything or is something just isn't working.

**Comment by JoshMcCullough** [comment]
I'm also trying to run Mate, and it works if I start it with `sudo xinit` but then, of course, I'm logged in as `root` - which is not what I want. When I try to run `xinit` without `sudo`, I get this: https://gist.github.com/JoshMcCullough/b04f321a5ecc8bc28994

Any ideas?

**Comment by dnschneid** [comment]
Reboot and try again without sudo.

**Comment by DennisLfromGA** [comment]
I believe `startx` has been working for a while now so closing this issue, please reopen if it's still an issue.

**Comment by parkerlreed** [comment]
@DennisLfromGA Wow I had completely forgotten about this. Haven't even had my Chromebook for a year or two. Glad it's closed!

**Comment by DennisLfromGA** [comment]
I know, there seems to be a bunch of these that have been fixed and are still hanging around. :)
