### ISSUE TITLE
Screen always eventually turns black with mouse pointer. Only occurs in crouton. Updated crouton and chrome OS.

### ISSUE THREAD

**Issue by philcastro** [dnschneid/crouton#1970]
The screen will always turn black with a mouse pointer but it happens either in a few hours or a matter of minutes. Not sure what's going on.

**Comment by cjp** [comment]
Similar issue. Runs normally for some time, then begins to cause blank screen with mouse pointer still visible. Then display re-appears. Problem seems to get progressively worse until such time I just need to restart.

Problem is most prevalent when running Citrix's `icaclient`.

`croutonversion` returns:

```
crouton: version 1-20150620222151~master:89796a99
release: precise
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi
host: version 7077.95.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux bishkek 3.14.0 #1 SMP Tue Jul 14 22:43:19 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
```

**Comment by drinkcat** [comment]
Does this still happen? Please reopen if that's the case.
