### ISSUE TITLE
ubuntu won't run since last chromeOS update (on chromebook hp11)

### ISSUE THREAD

**Issue by maxosteo** [dnschneid/crouton#1971]
Hello, 

I use ubuntu on my chrombook hp11, and since the last update, impossible to run ubuntu... This is what's in the terminal : 

chronos@localhost / $ sudo startunity
Password: 
Entering /mnt/stateful_partition/crouton/chroots/precise...

Xephyr cannot open host display. Is DISPLAY set?
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

If someone can help me... thanks !

**Comment by MeneerJansen** [comment]
Maybe ChromeOS updated itself and now you might need to update crouton and your chroot. I disable ChromeOS updates w/ `sudo  initctl stop update-engine` so I never updated crouton or my chroot. You might find [this topic] (https://github.com/dnschneid/crouton#a-new-version-of-crouton-came-out-my-chroot-is-therefore-obsolete-and-sad) on croutons "homepage" useful.

Good luck... :smile:

**Comment by maxosteo** [comment]
Thx, i hope there will be à good update soon ! And thank you for the tip to
stop chromeOS update !

**Comment by drinkcat** [comment]
Generally updating the chroot fixes these issues.
