### ISSUE TITLE
lost Super_L + numkey shortcuts in xiwi after last Chrome OS update

### ISSUE THREAD

**Issue by jowalski** [dnschneid/crouton#1972]
A few days ago, after the last Chrome OS stable upgrade (I think) on my Toshiba II chromebook, the Super_L + numkey shortcuts stopped working and are now getting interpreted as function keys (F1, F2, ... etc) according to `xev`.

Nothing else changed in my config and they were working before. Other shortcuts work fine (Super_L + letterkey, Super_L + enter, space, ...). I have `XKBMODEL="chromebook"` set in `/etc/default/keyboard`, and `xmodmap -e "keycode 133 = Super_L"` in `.xinitrc`.

I upgraded crouton also but no luck there. Also, I'm using `vivid` (which hasn't given me any problems so far!). Any suggestions on debugging this issue? as it seems to crop up in some form every once in a while and my knowledge doesn't go very deep on xiwi or Chrome OS/freon. I use awesome wm with Emacs and the Super_L + numkey shortcuts are very useful to me and seemingly the only viable ones.

This is the result from `xev` when typing Super_L + "1" (I don't know what the result was before):

````
KeyPress event, serial 33, synthetic NO, window 0x1000001,
    root 0x1a6, subw 0x0, time 34091067, (725,146), root:(727,170),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x1000001,
    root 0x1a6, subw 0x0, time 34091367, (725,146), root:(727,170),
    state 0x40, keycode 67 (keysym 0xffbe, F1), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x1000001,
    root 0x1a6, subw 0x0, time 34091540, (725,146), root:(727,170),
    state 0x40, keycode 67 (keysym 0xffbe, F1), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x1000001,
    root 0x1a6, subw 0x0, time 34091574, (725,146), root:(727,170),
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
````

This is from `croutonversion`:

````
crouton: version 1-20150716185530~master:aba2c948
release: vivid
architecture: amd64
xmethod: xiwi
targets: xiwi,core,x11,xorg,extension,keyboard,chrome-beta,audio
host: version 7077.95.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jul 14 23:13:38 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
````

**Comment by dnschneid** [comment]
It's possible that #1801 or #1832 *fixed* things for you.  With the keyboard target, super+numkeys are supposed to be function keys, but weren't due to bugs.

@drinkcat what's the current recommended way to undo the keyboard target?

**Comment by jowalski** [comment]
Thanks for clarifying. I figured out an alternative solution within awesome wm for my purposes. And thanks for all your great work on this project.
