### ISSUE TITLE
Xephyr Down 

### ISSUE THREAD

**Issue by gazampa** [dnschneid/crouton#1974]
crouton: version 0-20130809005455~master:1caf89f6
release: precise
host: version : ( samsung arm, 2013, most recent snow chromos )

I last installed crouton about a year ago, working fine,  chromeOS recently updates, now Xephyr, which I was unaware was running back there, is down.

Here is what my console tells me :

chronos@localhost ~ $ sudo startxfce4 -c /media/removable/SD\ Card/chroots/
Entering /media/removable/SD Card/chroots/precise...
/usr/bin/startxfce4: Starting X server

Can't open display

Xephyr cannot open host display. Is DISPLAY set?
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /media/removable/SD Card/chroots/precise...
Sending SIGTERM to processes under /media/removable/SD Card/chroots/precise... 

I am probably a bit behind, looked around the boards, updated crouton, /usr/bin/local, ran the above croutonversion from inside the fallen chroot.

Whats going on ? What happened my chroot !

**Comment by DennisLfromGA** [comment]
You most likely need to do a crouton update, for full details, see -https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by gazampa** [comment]
Is there a way pass path to crouton.

My chroot, precise, is on my sd card : /media/removable/SD Card/chroots precise

The installer goes looking under /usr/local/bin.

**Comment by DennisLfromGA** [comment]
Use crouton's '-p' option to specify the chroot's parent directory:
`sudo sh ~/Downloads/crouton -p /media/removable/SD Card/ -n precise -u`

**Comment by gazampa** [comment]
Thanks, that path flag does the trick.

( My chroot was kind of old and it hit some incompatibility stuff
upgrading. I deleted the old and ported over the old home directory to a
new install )

**Comment by DennisLfromGA** [comment]
Can this issue be closed now?

**Comment by gazampa** [comment]
Sure, Sorry, did not realise it was still open.
