### ISSUE TITLE
Crouton problems

### ISSUE THREAD

**Issue by redrobin53** [dnschneid/crouton#1975]
I try to enter crouton usin sudo startunity, but it replies with this 
Entering /mnt/stateful_partition/crouton/chroots/precise...
enter-chroot must be run as root.
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

i have tried everything, any ideas on how to fix?

**Comment by DennisLfromGA** [comment]
`sudo startunity` should work, reboot and try again.

**Comment by redrobin53** [comment]
ok thnx

**Comment by redrobin53** [comment]
changed to KDE build an have had no problems since

**Comment by Alfriadox** [comment]
good. This issue can be closed
