### ISSUE TITLE
Cannot connect to extension, unable to start display - apparently after chrome os update

### ISSUE THREAD

**Issue by ukgda** [dnschneid/crouton#1976]
Hello

Samsung chromebook intel XE550. OS Version 44.0.2403.90 (64-bit)

Have been connecting via X for some months. Suddenly has stopped working. (after system update?). Have updated integration app and crouton.  Still failing to open saying check crouton extension.  The most recent extension is installed and enabled.

Any help appreciated.  Thank you.

croutonversion:
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,chrome-beta,keyboard,gtk-extra,cli-extra,audio,core,extension
host: version 7077.95.0 (Official Build) stable-channel lumpy 
kernel: Linux localhost 3.4.0 #1 SMP Tue Jul 14 23:13:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

Terminal output after startxfce4 command:

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Tue Jul 14 23:13:12 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=8d6ab8b2-bc59-dd45-9c23-355bd4190bd4/PARTNROFF=1 hashtree=PARTUUID=8d6ab8b2-bc59-dd45-9c23-355bd4190bd4/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=7dd377974793808a85371170b765030a528a0b03 salt=4432640abda878e0f9fd6478b59171cc00b36d3871913022ce05ded87d7216f6" noinitrd vt.global_cursor_default=0 kern_guid=8d6ab8b2-bc59-dd45-9c23-355bd4190bd4 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jul 28 12:34:08 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Unable to set master
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,chrome-beta,keyboard,gtk-extra,cli-extra,audio,core,extension
host: version 7077.95.0 (Official Build) stable-channel lumpy 
kernel: Linux localhost 3.4.0 #1 SMP Tue Jul 14 23:13:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Cannot connect to extension, retrying...
Error: target STRING not available
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by fvant** [comment]
I have the same issue, creating a new chroot got me the same result.
The extension debugging shows it gets connected to and sees the window...

![screenshot 2015-07-29 at 09 46 14](https://cloud.githubusercontent.com/assets/5323587/8952566/5d8faf50-35d8-11e5-8c59-5b1961cef3f3.png)

**Comment by ukgda** [comment]
@fvant those are the same debug messages that I get. Not sure what to try next....

**Comment by Xodiced** [comment]
I'm having the same issue with the same debugging output from the extension on an Acer CB5 (Tegra ARM based), whereas my Haswell based Chromebox has no issues with xiwi and the extension.

https://github.com/dnschneid/crouton/issues/1940

**Comment by fvant** [comment]
OK, looked at the sourcecode and found something going wrong, a start of a fix I think.

In the debug window there is only a "C" command received, not an "X" that actually creates the window (see croutoncycle code).
I see that the code that sends the X never gets triggered (tested by increasing the timeout to 1000 in the startxfce4 script and then adding echo lines to croutoncycle)

Manually sending the X command, like the code would have, works fine, it created a window like before (but then empty)

echo 'X:1 xiwi' >/tmp/crouton-ext/in

**Comment by ukgda** [comment]
@fvant Thank you for investigating further.  I'm afraid I know too little to help you!

One thing I have done is to add xorg to my chroot (sudo sh ~/Downloads/crouton -u -t xorg -n trusty) so I can use it without the extension i.e. not in a tab.

But when I launch the chroot - sudo startxfce4 - and do the refresh trick to view the desktop I see the desktop for a second and then it goes to black and refresh no longer does anything. Before I installed xiwi and extension the window method worked without a problem now not even that appears to work?

**Comment by fvant** [comment]
I commented out this call and all seems to work again ! :)  perhaps dnschneid knows why..

/usr/local/bin/croutoncycle, line 520 (in the chroot).  Commented out and added : to have something in the if statement;   you can also remove the whole if.

       if [ -z "$freonowner" ]; then
             :
        #    host-x11 croutonwmtools raise "$aurawin"
        fi
        STATUS="`echo -n "X${destdisp} ${xmethod#*-}" | websocketcommand `"

**Comment by Xodiced** [comment]
That seemed to allow the command "sudo startxiwi xterm" to properly work on my Chromebook.  Thanks.  So it seems possibly freon related as it works fine without that "hack" on a freon enabled Chromebox, but the Chromebook affected does not use freon.

**Comment by jmccoy** [comment]
I have the same problem on my Acer C710. I've updated my chroot and installed the latest crouton extension.

Version 44.0.2403.90 (64-bit)
Platform 7077.95.0 (Official Build) stable-channel parrot
Firmware Google_Parrot.2685.37.0

crouton: version 1-20150730171703~master:f8fdfb0c
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 7077.95.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Tue Jul 14 21:44:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

I'd like to try fvant's suggestion, but am unable to edit the file - mousepad says "Cannot open display".
How should I proceed?

Thanks!

**Comment by Ranctifier** [comment]
I was able to replicate fvant's suggestions and get my crouton to run even though its a bit tedious.

Here's the steps if you've already done the edits fvant suggested:
1. Launch two terminals, and enter your chroot in both of them
2. In one terminal have your startxfce4 or whatever command ready
3. In the other terminal have `echo 'X:1 xiwi' >/tmp/crouton-ext/in` ready
4. Switch to your first terminal and enter your start command
5. Switch to your second terminal and enter the echo command

This should launch a blank screen, if your chroot boots into it, success!

Here's the steps for everything:
1. Start a terminal, enter your chroot, and change directory to `/usr/local/bin`
2. You should see a file named croutoncycle, thats the file fvant edits
3. Use `sudo chmod 777 croutoncycle` so we can write to the file
4. Use `vi croutoncycle` which is an editor should be installed by default, I have basic instructions later but vi isn't the easiest editor to learn so you may want to read about it
5. Scroll using pagedown to the code fvant suggested to comment out, its relatively close to the end of the file, it was 1-2 pageups from the end for me
6. Move the cursor with the arrow keys to these lines:
`if [ -z "$freonowner" ]; then`
`    host-x11 croutonwmtools raise "$aurawin"`
`fi`
7. The simplest way to comment the lines is, for each line:
  7a. Move the cursor before the line and press i to start insert mode
  7b. Enter a # character, then press Esc to end insert mode
  7c. Repeat 7a-b until the three lines in 6 are commented
8. Make sure Esc was pressed so vi isn't in insert mode
9. Type `:wq` and then press enter, this should save the file and exit vi
10. Use `sudo chmod 755 croutoncycle` to revert the file's original permissions
11. Now make sure two at least terminals are open, in one terminal have your startxfce4 command or whatever ready, in the other terminal have `echo 'X:1 xiwi' >/tmp/crouton-ext/in` ready
12. Enter your start command in the first terminal then switch to the other terminal and enter the echo command, if everything works out your chroot should boot into a window.

**Comment by moderatic-john** [comment]
The above worked for me. I had this issue and now at least I can get it running again. Thanks everyone.

**Comment by ukgda** [comment]
@Ranctifier thank you so much for setting out what to do so clearly.  Works for me!

**Comment by jmccoy** [comment]
I followed @Ranctifier and am now running Crouton.  Thanks much!  Also, thanks for making me recall the time when I knew how to use vi!

**Comment by ukgda** [comment]
Ok - so my os has just updated:

Version 44.0.2403.155 (64-bit)
Platform 7077.123.0 (Official Build) stable-channel lumpy_freon
Firmware Google_Lumpy.2.111.0

and now has freon. I've reinstated the commented out lines of code outlined by @Ranctifier and my chroot launches in a tab once again without using two terminals.

**Comment by jmccoy** [comment]
Just updated my os -

********
Version 44.0.2403.155 (64-bit)
Platform 7077.123.0 (Official Build) stable-channel parrot
Firmware Google_Parrot.2685.37.0
********
Which, I note, is not yhe same as @ukgda .

In any event, if I try to simply "sudo startxfce4", I get (as before)

********
freon: no
Cannot connect to extension, retrying...
Error: target STRING not available
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup
Hangup

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
********

The two terminal from @Ranctifier still works.

**Comment by rob6502** [comment]
Thanks @fvant, for explaining how you found it too.

I edited the file and it worked immediately (no second terminal with extra-command required).

**Comment by partyewok** [comment]
Dito. (@rob6502)

Fresh installation with *-t xiwi,xfce -r trusty* on
```
Version 44.0.2403.156
Plattform 7077.134.0 (Official Build) stable-channel nyan_big
Firmware Google_Nyan_Big.5771.63.0
```

**Comment by oleid** [comment]
The work-around by @fvant works for me on my Asus Chromebook 13 (nyan-big), too. Thanks a lot! What about including the fix by default?

**Comment by toussa** [comment]
The workaround works also for me :) Thank you !

**Comment by DennisLfromGA** [comment]
@dnschneid - Is this [issue/fix](https://github.com/dnschneid/crouton/issues/1976#issuecomment-126783866) just an issue on ARM Chromebooks or can other platforms benefit from it too ?

**Comment by fvant** [comment]
I have an Intel Samsung Chromebook.

**Comment by partyewok** [comment]
Crouton (or at least the arm part) does not seem to get a lot of love these days. Certainly, reapplying the fix after every update is not a reasonable solution to this problem. 

I would also consider switching to a different desktop and/or distro, but most things do not work extension-wise or not at all (like GNOME with a recent distro version, I assume there is a arm-related problem with GNOME3?). 

@dnschneid Any suggestions to make life easier (except for buying a x86 chromebook)?

**Comment by dnschneid** [comment]
I think crouton needs to drop xephyr support, and the subsequent cleanup and simplification will make this a lot more reliable and easier to debug.

**Comment by gnidorah** [comment]
Confirm this issue on vanilla self-built freon-less (!) Chromium OS. @fvant fix https://github.com/dnschneid/crouton/issues/1976#issuecomment-126783866 is needed, and indeed it helps! Thank you!
@dnschneid so the question arises: Is non-freon compatibility still maintained for crouton xiwi and xorg?

Just for the info: third-party pre-ready builds like CloudReady and ArnoldTheBat special are currently not compliant with crouton for graphics. This is the problem of these builds, not crouton. See: https://github.com/dnschneid/crouton/issues/2431 This is not issue for sure if you use Chrome OS or self build Chromium OS.

**Comment by gnidorah** [comment]
@DennisLfromGA @dnschneid 
> I'm just wondering what changed that host-x11 croutonwmtools raise "$aurawin" is failing ???
Got broken in non freon Chromium OS builds by this old commit https://chromium.googlesource.com/chromium/src/+/1c007d5de979461ae400c95c4309e2955de094c6
It also brakes clipboard sync between host and other displays.

**Comment by kgingeri** [comment]
(I know this is an older thread, but...) 
I had what seemed like the same issue and found this thread.  In fact what my issues was (ASUS Flip) was that I had the Crouton extension loaded in both profiles I had two open.  I had a black window with "connecting..." showing.  However, when I switched to the other profile I noticed the Trusty desktop had opened there!  

I disabled the extension so it is active in only the one profile and all is well.  :v)

**Comment by drinkcat** [comment]
We dropped xephyr support, hopefully this is fixed in the process?

**Comment by solofortitude** [comment]
I am also having an issue with crouton integration extension.  
"connecting...
Disconnected (retrying every 5 minutes) extension started 2.5.2

I was following Ranctifier) commented on Aug 3, 2015) adivce but I couldn't locate step 6....

Move the cursor with the arrow keys to these lines:
if [ -z "$freonowner" ]; then
host-x11 croutonwmtools raise "$aurawin"
fi

since he posted in 2015... the files have probably changed since then?

I'm running CB35 Toshiba Chrome book 2.  Any of you guys have suggestions?

**Comment by ramses0** [comment]
Happened again w/ latest update:


```Google Chrome	57.0.2987.146 (Official Build) (64-bit)
Revision	0
Platform	9202.64.0 (Official Build) stable-channel chell
ARC	3880239```

...this is terrible and basically kills chromebook as a stable developer machine.  I dread reboots b/c 20% of the time there's an update that kills crouton support and then I'm in a 1-hour to 1-month struggle to get things back running, migrating, etc.

**Comment by solamour** [comment]
As @solofortitude mentioned, I'm not able to find the relevant lines to comment out in `croutoncycle`. Perhaps it went through a few revisions in the last couple of years. Are there any other suggestions that I should try?
