### ISSUE TITLE
Brightness only goes up or down one level using keyboard shortcut after update

### ISSUE THREAD

**Issue by morsedl** [dnschneid/crouton#1977]
Hi Daniel!

Apologies I've not updated the keyboard wiki entry back in Jan. / Feb. as promised --- dissertation work has and will continue to have me swamped for a bit. :)  But I will get to revising the entire page at some point, perhaps if we're lucky before 2015's end. :)

Google updates to Chrome OS broke my Crouton, so I had to update.  This messed up my keyboard configuration, as I think you have incorporated some of the changes I made and described in another Crouton issue report a while ago into Crouton itself (yay!).  It took me a bit to figure this out, but once I turned off all my xmodmap calls in my startup script, things started to pretty much work just as they had before (except Search is the Win key again, which is fine [I had had it mapped to R-Alt]).

The one lingering issue I cannot seem to fix is that, after the updated, R-CTRL+Brightness Up and RCTL+Brightness Down do work, but they will not advance the present brightness up or down more than one level, no matter how many times pressed, nor the timing of them (e.g., even if I wait for the onscreen display of the brightness meter to disappear, I am still "locked in" to just two brightness level).

Oddly, from the command line, running "brightness up" and "brightness down" work fine and allow the full range of brightness levels available.  I have no custom keyboard shortcuts set up within Unity for this, so I'm not sure how the call to /usr/local/bin/brightness is being made once the appropriate key is pressed.

A minor issue, but one I'd like to fix if possible.  Any thoughts or insights?

Thanks!
Doug

**Comment by morsedl** [comment]
BTW, I learned that running "sudo initctl stop update-engine" within Crosh -> shell (i.e., the Chrome OS bash shell) will stop Google from updating Chrome OS.  This seems like useful information that ought might on the wiki somewhere if not already.  My setup was just fine, and Google breaking my Crouton and keyboard setup took quite some time to resolve (hours), time that I really did not have.

I'm very tired of the "update rat race" on nearly all the platforms I use (i.e., primarily Ubuntu, iOS, Android, and ChromeOS [only in service of Crouton]).  I suspect others are, too, so knowing how to stop Google from forcing ChromeOS updates that might break their Crouton is something other users may well want to know how to do.

**Comment by drinkcat** [comment]
Sorry, I know this is a super old issue, but... output of `sudo edit-chroot -all` would be useful, please reopen if this is still an issue.
