### ISSUE TITLE
Cannot return to lxde after returning to ChromeOS in Xorg

### ISSUE THREAD

**Issue by jhartzler** [dnschneid/crouton#1981]
I have a trusty chroot installed with lxde, xorg, and xiwi. Running with xiwi fails, another issue, but running with xorg lets me use lxde in its own screen until I page back to ChromeOS, when attempting to page back will drop me into the developer console. The following is the output that the crosh window I ran it from gave before I terminated it:

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-67-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue Jul 14 23:44:39 PDT 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=a47bac0c-0d25-064d-aab7-12d0e61b30bb/PARTNROFF=1 hashtree=PARTUUID=a47bac0c-0d25-064d-aab7-12d0e61b30bb/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5b555294b7e577d41c7de4fc52a0910623ba3769 salt=cadb7c2b91f1de700dbccb20c599894313edf982ca48c597bf7226c320694daf" noinitrd vt.global_cursor_default=0 kern_guid=a47bac0c-0d25-064d-aab7-12d0e61b30bb  
Build Date: 12 February 2015  02:55:07PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed Jul 29 20:32:47 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: armhf
xmethod: xorg
targets: xorg,lxde,xiwi
host: version 7077.95.0 (Official Build) stable-channel nyan_big 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jul 14 23:44:39 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Agent pid 27163
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE
** Message: main.vala:131: log directory: /home/jack/.cache/lxsession/LXDE
** Message: main.vala:132: log path: /home/jack/.cache/lxsession/LXDE/run.log
croutonwebsocket error: Error timeout
Error: target STRING not available
Error: target STRING not available

The following is the output from running sudo enter-chroot -n trusty croutonversion

Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: armhf
xmethod: xorg
targets: xorg,lxde,xiwi
host: version 7077.95.0 (Official Build) stable-channel nyan_big 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jul 14 23:44:39 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: no
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

**Comment by DennisLfromGA** [comment]
Make sure to use <kbd>Ctrl+Alt+SHIFT+F1/F2</kbd> to switch.

**Comment by jhartzler** [comment]
And that seems to do it. Thanks!

**Comment by DennisLfromGA** [comment]
Cool; if your satisfied you can close this issue...
