### ISSUE TITLE
USB stick, moving between machines, dbus daemon failure

### ISSUE THREAD

**Issue by ncc1701v** [dnschneid/crouton#1982]
I have chroots and bin on a USB stick. It works well on an Acer Chromebox. When I unmount-chroot and stick it in my old HP11 chromebook, then startxfce, I get "dbus daemon failed with code 126". The chroot should be hardware-independent, yes? Thanks.

**Comment by drinkcat** [comment]
Provided it's the same architecture, yes. Please reopen if this happens again.
