### ISSUE TITLE
Debian Sid no longer has gnome-session-fallback

### ISSUE THREAD

**Issue by tsmock** [dnschneid/crouton#1983]
Sid has replaced gnome-session-fallback with gnome-session-flashback.

I don't know if there is a way to have distro-specific packages with crouton.

Workaround:
$ sudo vim /mnt/stateful_partition/crouton/chroots/sid/prepare.sh

Replace gnome-session-fallback with gnome-session-flashback. When exiting, use w! (file marked as readonly). This must be done every time the chroot is updated with crouton.

EDIT:
I used enter-chroot when "fixing" the problem.

**Comment by voidplayer** [comment]
same problem. Your work around didnt worked for me... Im doing a first boostrap... and i have to either update or remove it...

$ sudo sh crouton -r stretch -t gnome -u
/usr/local/chroots/stretch already exists; updating it...
sed: can't read /run/crouton/mnt/stateful_partition/crouton/chroots/stretch/etc/apt/sources.list.d/*.list: No such file or directory
sed: can't read /run/crouton/mnt/stateful_partition/crouton/chroots/stretch/etc/apt/sources.list.d/*.list: No such file or directory
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startgnome into the host...
Installing crouton-noroot into the chroot...
Installing startgnome into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
mesg: ttyname failed: Inappropriate ioctl for device
mesg: ttyname failed: Inappropriate ioctl for device
Installing target core...
Preparing environment...
Preparing software sources...
Hit http://httpredir.debian.org stretch InRelease
Get:1 http://httpredir.debian.org stretch/main Sources/DiffIndex [7876 B]
Get:2 http://httpredir.debian.org stretch/contrib Sources/DiffIndex [5335 B]
Get:3 http://httpredir.debian.org stretch/non-free amd64 Packages/DiffIndex [6301 B]
Get:4 http://httpredir.debian.org stretch/main amd64 Packages/DiffIndex [7876 B]
Get:5 http://httpredir.debian.org stretch/non-free Sources/DiffIndex [6439 B]
Get:6 http://httpredir.debian.org stretch/main i386 Packages/DiffIndex [7876 B]
Get:7 http://httpredir.debian.org stretch/contrib amd64 Packages/DiffIndex [7267 B]
Get:8 http://httpredir.debian.org stretch/non-free i386 Packages/DiffIndex [6163 B]
Get:9 http://httpredir.debian.org stretch/contrib i386 Packages/DiffIndex [7405 B]
Get:10 http://httpredir.debian.org stretch/contrib Translation-en/DiffIndex [3403 B]
Get:11 http://httpredir.debian.org stretch/main Translation-en/DiffIndex [7876 B]
Get:12 http://httpredir.debian.org stretch/non-free Translation-en/DiffIndex [3265 B]
Fetched 77.1 kB in 5s (14.7 kB/s)
Reading package lists...
Ensuring system is up-to-date...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version.
ca-certificates is already the newest version.
sudo is already the newest version.
wget is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 972a551818d490974f437bf5e96f3e8baa72e81b)...
--2015-07-30 23:55:57--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/972a551818d490974f437bf5e96f3e8baa72e81b.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 173.194.67.82, 2a00:1450:400c:c05::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.67.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.47bGZW/adhd.tar.gz'

     0K .......... .......... .......... .......... ..........  821K
    50K .......... .......... .......... .......... .......... 1.84M
   100K .......... .......... .......... .......... .......... 1.79M
   150K .......... .......... .......... .......... .......... 1.56M
   200K .......... .......... .......... .......... .......... 4.87M
   250K .......... .......... .......... .......... .......... 1.39M
   300K .......... .......... .......... .......... .......... 1.55M
   350K .......... .......... .......... .......... .......... 9.59M
   400K .......... .......... .......... .......... .......... 1.99M
   450K ....                                                   8.61M=0.3s

2015-07-30 23:55:58 (1.75 MB/s) - '/tmp/crouton-cras.47bGZW/adhd.tar.gz' saved [465319]

Reading package lists...
Building dependency tree...
Reading state information...
alsa-utils is already the newest version.
libasound2:i386 is already the newest version.
libspeexdsp1:i386 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version.
gcc-multilib is already the newest version.
pkg-config is already the newest version.
libc6-dev:i386 is already the newest version.
libspeexdsp-dev:i386 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
libasound2-dev:i386 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
patch is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (i386)...
Installing CRAS...
Reading package lists...
Building dependency tree...
Reading state information...
libasound2 is already the newest version.
alsa-utils is already the newest version.
libspeexdsp1 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version.
libc6-dev is already the newest version.
pkg-config is already the newest version.
libspeexdsp-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
libasound2-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
patch is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (native)...
Installing CRAS...
Installing target xorg...
Installing dependencies for /usr/local/lib/croutonfreon.so...
Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version.
libc6-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/lib/croutonfreon.so...
Reading package lists...
Building dependency tree...
Reading state information...
Package 'xserver-xorg-video-all' is not installed, so not removed
xorg is already the newest version.
xserver-xorg-core is already the newest version.
xserver-xorg-video-intel is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package 'xserver-xorg-video-fbdev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing dependencies for /usr/local/bin/croutonwmtools...
Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version.
libc6-dev is already the newest version.
libx11-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonwmtools...
Installing dependencies for /usr/local/bin/croutonxi2event...
Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version.
libc6-dev is already the newest version.
libx11-dev is already the newest version.
libxi-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonxi2event...
Reading package lists...
Building dependency tree...
Reading state information...
dbus is already the newest version.
xdg-utils is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
dmz-cursor-theme is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
bsdmainutils is already the newest version.
kbd is already the newest version.
xautomation is already the newest version.
xbindkeys is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing target x11...
Installing target gtk-extra...
ar: creating /tmp/crouton.vLIU9N/crouton-network-manager.deb
(Reading database ... 38745 files and directories currently installed.)
Preparing to unpack .../crouton-network-manager.deb ...
Unpacking crouton-network-manager (0) over (0) ...
Setting up crouton-network-manager (0) ...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
gdebi is already the newest version.
gksu is already the newest version.
netsurf-gtk is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing target gnome...
Reading package lists...
Building dependency tree...
Reading state information...
Package gnome-session-fallback is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gnome-session-flashback

E: Package 'gnome-session-fallback' has no installation candidate
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...

**Comment by voidplayer** [comment]
Btw, this wouldnt be an issue if there werent that many packages specified by hand instead of letting debian handeling the dependences...

**Comment by tsmock** [comment]
I used enter-chroot, not crouton -r sid -t gnome -u when "fixing" the problem.

**Comment by voidplayer** [comment]
```shell
$ sudo crouton -r sid -t gnome 
```
or
```shell
$ sudo crouton -r sid -t gnome -u
```
depending on whether if its your first launch or your consecutive ones. Then, after the error
```shell
$ sudo vim /usr/local/chroots/sid/prepare.sh
```
fix the error and then launch
```shell
$ sudo /usr/local/bin/enter-chroot
```
it will detect an installation in progress and ask you if you want to finish it before entering. Answer yes and you are done :)

**Comment by GBouerat** [comment]
Doesn't work for me.

**Comment by GBouerat** [comment]
With -r stretch -t gnome this workaround works, but gnome crash at launch ...

pro tip : in vim enter this to apply this workaround:

```
:%s/fallback/flashback:
```

**Comment by voidplayer** [comment]
i wrote ```-r sid -t gnome``` because OP was using sid, but i really used ```-r stretch -t gnome``` because thats the release i wanted... I wonder now why it didnt work with sid... :)

and yeah, gnome crashes with a useless error... I dont know if this is debian's or crouton's fault...

in doubt i will blame gnome for such a useless error screen... I mean, you dont get whats wrong and you cant recover from it (they could use some basic templates and defaults to recover for whatever is failing)

im using semi successfully kde instead now :P

**Comment by dnschneid** [comment]
Handled in #1689, referenced by #1706
