### ISSUE TITLE
Error installing elementary OS

### ISSUE THREAD

**Issue by SanicX** [dnschneid/crouton#1984]
Hello, I'm having a error installing elementary OS on top of Ubuntu running the XFCE desktop environment, I've did everything a tutorial explained, although when I'm starting the script I come up with the following error:

/etc/X11/Xsession.d/99x11-common_start: line 5: exec: init: not found
Running exit commands...
/usr/bin/xinit: connection to X server lost

If anybody could fix this error within the hour, I'd gladly be able to reward them.

**Comment by macfact4** [comment]
Use the MyDearWatson script.

**Comment by dnschneid** [comment]
See #1571
