### ISSUE TITLE
Xephyr down - crouton update down

### ISSUE THREAD

**Issue by smbgaiden** [dnschneid/crouton#1986]
crouton: unsure, not working
release: precise
host: version : ( samsung arm, 2013 )

Recently restarted the computer about a week ago which ran an update. Received the same problem as the Xephyr down thread. Mine is all run as on MMC and do not have alternative path required.

Running: chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n precise
Results in:
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
x11 target does not work on ARM. Substituting in xephyr.
Installing brightness into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing croutoncycle into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonwheel into the chroot...
Installing croutonwm into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xserverrc-xephyr into the chroot...
x11 target does not work on ARM. Substituting in xephyr.
Installing startxfce4 into the host...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Couldn't open /dev/tty1
Failed to complete chroot setup.
Not unmounting /usr/local/chroots/precise as another instance is using it.
Done! You can enter the chroot using enter-chroot.

Hoping this was a non-critical failure, optimistically ran the following: chronos@localhost / $ sudo enter-chroot startxfce4
Unfortunately resulted in this:
Entering /usr/local/chroots/precise...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n] y
Preparing chroot environment...
Couldn't open /dev/tty1
Failed to complete chroot setup.
Not unmounting /usr/local/chroots/precise as another instance is using it.

Unsure where to go from here, so reporting it at this site. First thought was to see what the chroot setup script says, but was unable to locate it.

**Comment by MeneerJansen** [comment]
The problem may be that your chroot (i.e. Ubuntu) is still "active" when you run the update. Try to log out from Ubuntu ans run the commands again from the shell in ChromeOS (i.e. start crosh w/ crtl-alt T, type "shell" and run the commands from there).

**Comment by smbgaiden** [comment]
Thanks, unfortunately once I execute the command shell from the terminal I begin to hog the tty1:

chronos@localhost / $ ps -a
  PID TTY          TIME CMD
10626 pts/3    00:00:00 bash
11364 pts/1    00:00:00 bash
11365 pts/1    00:00:00 bash
11370 pts/1    00:00:00 ps
chronos@localhost / $ 

The tty3 is the developer mode window idling. However, I've tried the crouton update with and without the tty3 entry and both wind up with the same result as above. Any way to execute the update on crouton from either the terminal window or the developer console section in order to leave tty1 undisturbed during the update?

**Comment by MeneerJansen** [comment]
Are you absolutely **sure** that Linux is shut down when you try the update from within ChromeOS? On the crouton "home page" there is a procedure to update/upgrade ([link] (https://github.com/dnschneid/crouton#a-new-version-of-crouton-came-out-my-chroot-is-therefore-obsolete-and-sad)). You also might like to be sure that you've got the latest version of the `crouton` script/executable from: https://goo.gl/fd3zc

Good luck!

**Comment by smbgaiden** [comment]
You also might like to be sure that you've got the latest version of the crouton script/executable from: https://goo.gl/fd3zc


This was the key, got back to where I was before after using the updated crouton and using the update command. Thank you immensely!
