### ISSUE TITLE
MySQL will not install

### ISSUE THREAD

**Issue by zwhitchcox** [dnschneid/crouton#1987]
I've tried on trusty and precise, whenever I install mysql with ```sudo apt-get install mysql-server```, and I try the command ```mysql```, I get this error. This only happens on crouton installations of ubuntu, and it works on other installations, so I suspect it's something to do with crouton.

```shell
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by DennisLfromGA** [comment]
Does it need to have some [ports opened up](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton)?
Have you started the necessary software in `/etc/rc.local`, etc.?

**Comment by zwhitchcox** [comment]
No, I didn't know you had to do that...although I've run servers with NodeJS before, and they worked. But I'll give it a shot, thanks!

**Comment by zwhitchcox** [comment]
Wow, that worked! I'm as grateful as I am envious of your skill. Thanks a lot.

**Comment by DennisLfromGA** [comment]
Great!
BTW - No skill, I've just picked up a few morsels from the gurus on this site mostly...

**Comment by DennisLfromGA** [comment]
@zwhitchcox - If you're satisfied, you can close this issue if you like.

**Comment by zwhitchcox** [comment]
Thanks. I always forget to do that
