### ISSUE TITLE
Xephyr cannot open host display. Is DISPLAY set?

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#1988]
Doing `sudo startlxde` in the shell results in:

```
Entering /mnt/stateful_partition/crouton/chroots/trusty...
Xephyr cannot open host display. Is DISPLAY set?
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```

I've been using this command for ~8 months and haven't seen this problem until today. Hoping you can suggest a way I can regain access to my Ubuntu (Trusty 14.04) environment.

My hardware:
HP Chromebook 11 using a Samsung ARM processor.

**Comment by DennisLfromGA** [comment]
Update your chroot and see if that fixes it.
Refer to this wiki for more details: 
https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by henrywright** [comment]
@DennisLfromGA Thanks. Updating the chroot fixed it!
