### ISSUE TITLE
Audio Not Working

### ISSUE THREAD

**Issue by EvilRoda** [dnschneid/crouton#1989]
I'm on an Acer C720. I recently attempted to use RetroArch, only to find out that it would not output sound. I then realized nothing else would output sound. I tried the update method under common issues, it did not work. I tried making another chroot with XBMC as the DE, because I knew that would have a menu that would output sound, in order to make sure the problem was with Crouton/the chroot itself, as opposed to RetroArch and my inability to work the music player that comes with LXDE. Rather than having its normal clicky sound effect, XBMC's menu sound effect was staticky. I then installed VLC and attempted to run audio. It worked at first, but when I changed the volume in VLC, the audio was horrible and staticky. After searching around for a solution, I decided to perform a powerwash and just do everything over again. Still, the problem persisted. I installed VLC, tried to play audio, and when I changed the volume, the audio turned staticky and horrible. Keep in mind, throughout all of this, Chrome OS played audio perfectly.

The current output of croutonversion is as follows:

crouton: version 1-20150730171703
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde,extension
host: version 7077.111.0 (Official Build) stable-channel peppy
kernel: Linux localhost 3.1.11 #1 SMP Tue Jul 28 15:00:32 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by DennisLfromGA** [comment]
This might be Issue https://github.com/dnschneid/crouton/issues/1590

**Comment by drinkcat** [comment]
Not sure, might be....
