### ISSUE TITLE
crouton extension doesn't save settings

### ISSUE THREAD

**Issue by Xodiced** [dnschneid/crouton#1990]
The crouton integration extension doesn't save settings.  For example if you enable the HiDPI setting or disable the extension on the next login the HiDPI setting is disabled and the extension is no longer set to "Disable" (I'm not referring to the Chrome OS extension setting, the enable/disable setting in the extension itself).  Is there any way to make the extension remember previous settings on logout?

**Comment by dnschneid** [comment]
Yeah, known issue--see #1321
