### ISSUE TITLE
Office Suite for ARM: Chromebook, too?

### ISSUE THREAD

**Issue by rondomamatuer** [dnschneid/crouton#1991]
Hello,

So I read quite a few articles between this past year and especially now that deal with Microsoft converting from intel to arm. I was wondering if there was a way to get the office suite (arm version) onto a arm chromebook possibly using the dual boot linux system. As a side note, I have the chromebook series 3. I have been experimenting on this computer for a while, but I am amateur when it comes to playing around with code, etc. 

The reason I ask in this "contact" section is because I cannot find a site to direct me in my curiosity. I have to directly ask, since no one seems to have a guide or anything for me to follow. I also believe it should be more possible to do this now, since before you need to have an intel processor and then use wine and qemu and a bunch of other extras...

Any thoughts?

**Comment by SimplySerenity** [comment]
Currently I think the best bet is to use exagear desktop, it's like qemu but much simpler to use and faster. It would allow you to install wine, and office too. I'm using it now and working on a review, it's pretty well rounded. Almost like a chroot, inside of your chroot...  
http://eltechs.com/product/exagear-desktop/

**Comment by MeneerJansen** [comment]
I don't know what you mean exactly. But can't you use crouton to have Linux on your Chromebook and install [Libre Office] (https://www.libreoffice.org/) to use as an office suitte?

**Comment by rondomamatuer** [comment]
@SimplySerenity Thanks! I wouldn't have found out about Exagear any sooner. I think I might try this...
@MeneerJansen I meant Office Suite as in the Microsoft version, but thanks anyway for the Libre Office suggestion.

**Comment by rondomamatuer** [comment]
This may sound dumb to more experienced people using crouton, but with using Exagear with crouton per se why do I need to use wine to get to the Microsoft Office? If someone can give me an explanation as to why that is that will be helpful. I'm learning...

Exagear is like Qemu they convert binaries so intel and arm can work together since some programs are only compatible with certain chips such as arm and intel.

**Comment by SimplySerenity** [comment]
So even though MO is a program made for x86 architecture it's still not compiled for linux. Wine is just another intermediary to run the program in a way that linux understands. The problem with that is that it's still written for another operating system so it still had plenty of bugs, and incompatibility. I don't have any experience with 365 so I can't really answer that question though sorry.

**Comment by MeneerJansen** [comment]
1. One musrt pay for Exagear.
2. I still don't understand exactly what it is: a windows emulator? Is it a virtual machine like Oracle Virtualbox?
3. Is wine not available Linux ARM?
4. What Linux distribution are you running? If its Ubuntu then install the "Synaptic" package manager and determine if LibreOffice is available for your Linux ARM flavor. If not, see if Wine (makes running Win apps possible on Linux) and install Microsoft Office 2007. That one runs fine in most instances in Wine. I believe that newer version of MSO do not run very fine in Wine ([link] (https://appdb.winehq.org/objectManager.php?sClass=application&iId=31))

**Comment by SimplySerenity** [comment]
Okay first Wine isn't a windows emulator, and Exagear isn't virtual machine either as rondomamatuer said it converts binaries at runtime. Next, since Wine isn't an windows emulator it doesn't exactly work on linux ARM. Maybe in the future support could be better but that's only if ARM windows becomes popular.

**Comment by MeneerJansen** [comment]
[off topic] Converting binaries at runtime? If that's possible, why not permanently convert them then? I have a sneaking suspicion that Exagear actually is a virtuaul machine and that Rondomamatuer doesn't know for sure what Exagear is. Indeed, **W**ine **i**s **n**o **e**mulator, but for most people's sake one might think of it as one. But you're right: it aint no emu and that's probably the reason that it don't work on ARM. 

Pity, though. I thought all Linux packages were available for all platforms (ppc, i86, amd64, arm, etc.). One must be very careful in one's choice of Chromebook then, since arm based ones exist. Anybody know of a way to determine, before buying one, what platform a Chromebook has?

**Comment by dnschneid** [comment]
First paragraph on [Exagear's website](http://eltechs.com/product/exagear-desktop/)

> With Eltechs ExaGear Desktop you can run Intel x86 application on your ARM-based Mini PC simultaneously with common native applications. ExaGear is a virtual machine that implements virtual x86 Linux container on ARM and allows you to run Intel x86 applications directly on ARM. It is like QEMU but 5 times faster! You can even run Windows applications on your ARM Mini PC if you install Wine.

...I suspect nobody reads crouton's README either :)

**Comment by dnschneid** [comment]
First paragraph of [Wine's about page](https://www.winehq.org/about/), too:

> Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, Mac OSX, & BSD. Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly, eliminating the performance and memory penalties of other methods and allowing you to cleanly integrate Windows applications into your desktop.

So yes, via Exagear, Wine, crouton, and some animal sacrifices, you should be able to run Microsoft Office on your ARM Chromebook.

**Comment by MeneerJansen** [comment]
> So yes, via Exagear, Wine, crouton, and some animal sacrifices, you should be able to run Microsoft Office on your ARM Chromebook.

I'm afraid that Wine is not widely available for the ARM platform. I think that Debian has the most support for ARM and they do not seem to have an ARM version of Wine ([link] (https://packages.debian.org/jessie/wine)). If Debian does have an ARM version of something then it is explicitly mentioned on their packages webpage. Take for instance LibreOfffice ([link](https://packages.debian.org/jessie/libreoffice)): that one is available for ARM.

Not a solution for the prob, but hope it does help....

**Comment by dnschneid** [comment]
You run Wine inside of Exagear.

**Comment by kapouer** [comment]
@MeneerJansen http://wiki.winehq.org/ARM states that Fedora distributes wine on ARM.
I'm not hallucinating...
http://koji.fedoraproject.org/koji/buildinfo?buildID=693517

**Comment by kapouer** [comment]
Now only you need to get that Office RT installer...

**Comment by MeneerJansen** [comment]
@kapouer I don't know if Crouton already supports installing Fedora in a chroot (@dnschneid will know this), but if so: apparently one can install Wine in Fedora for the ARM platform. I don't know if you necessarily need the Office RT version of MS Office (RT is a Windows version for the ARM platform). If I'm not mistaken Windows applications "in general" run in Wine. But I might be wrong though...

**Comment by kapouer** [comment]
@MeneerJansen on arm, you need arm binaries - whatever they're run using wine or not.
And there actually is an Office 2013 version that was made for Windows 8 RT (the one compiled for arm). So, IF latest wine can install office 2013 on amd64 binaries, maybe wine can install office 2013 RT on arm binaries... Anyway i ordered a C201 and am going to try dirty things next week :)

**Comment by MeneerJansen** [comment]
Pity that [WPS (Kingsoft) Office] (http://wps-community.org/downloads) is not available for ARM. There is a version for [Android] (https://play.google.com/store/apps/details?id=cn.wps.moffice_eng&hl=nl) though. And Android often runs on ARM platforms... Kingsoft (WPS) Office is the most fully Microsoft (doc at least) compatible suite I know (for free). Lbre Office and Apache Open Office have problems w/ cross-references and/or chapter numbering in DOC files.

**Comment by kapouer** [comment]
Found out that debian package "wine-development" (currently at version 1.7.52) is available on armhf (and powerpc !).

**Comment by dnschneid** [comment]
Wine on ARM running Office RT...a strange world it is we live in

**Comment by courville** [comment]
OK I took the $$$ approach but I have on a ARM RK3288 C201, Office 2010 running on chromeos -> crouton debian stretch chroot -> exagear jessie chroot -> crossover office wine.
I am positively surprised by the performance achieved. This is usable.

**Comment by rondomamatuer** [comment]
@courville That is AWESOME. My first computer was a samsung chromebook during the start of this thread and wanted to see if I could actually use it for school with ARM. Turns out I could, yet I believe Eltechs no longer exists so unless I found the program on the internet archive posted there somewhere then maybe I could tinker around. If you can believe it, I got Microsoft XP to load onto a virtualbox on this same chromebook...yet it was pretty much useless haha

**Comment by BetaPictoris** [comment]
@rondomamatuer it's a dead thread.
