### ISSUE TITLE
Freon?

### ISSUE THREAD

**Issue by SimplySerenity** [dnschneid/crouton#1992]
I've had a hard time finding much information on this, but I've heard that the freon version of crouton allows access to the framebuffer on the tegra and thus improves performance? Do I need to be on the freon version of chrome os first?

**Comment by tista500** [comment]
@SimplySerenity,
Though I'm not sure what you really want to know, Phoronix wrote an useful article for fre(c)on:
http://www.phoronix.com/scan.php?page=news_item&px=chrome-os-freon-graphics And if you want to know much more technical informations for fre(c)on, it would be better to ask it on ChromeOS forum...

Already, In Mar 2015, ChromeOS has employed freon as default, and crouton can run X11 with freon by compiling/adding special library when you set/add a crouton target "xorg".

Finally, talking about Tegra K1, did you read this thread?: #1089 

Regards.
