### ISSUE TITLE
kde5 not working without kwin-x11

### ISSUE THREAD

**Issue by voidplayer** [dnschneid/crouton#1996]
windows dont work without installing kwin-x11

**Comment by dnschneid** [comment]
`croutonversion`?

**Comment by voidplayer** [comment]
i was running the latest at the time i reported the bug. The dependency was not pulled by anything :)

Since I installed it manually for kde to work, my current croutonversion is not not much relevance now, is it?

:S

**Comment by voidplayer** [comment]
This was using debian stretch

**Comment by dnschneid** [comment]
So you installed kde without the kde target?  I wonder if a fresh chroot with the kde target would pull in kwin-x11 or not.

**Comment by voidplayer** [comment]
I installed the kde target with debian stretch and nothing pulled kwin-x11. Its been a while since this bug, stretch target was not installable for a while (and i didnt know how to fix it) and I moved to trusty

~~I dont have the space in my chromebook to install another chroot right now~~ I made a syslink and Im trying to `./crouton -r stretch -t kde-desktop -e`. Will report back if the bug is still present :)

**Comment by voidplayer** [comment]
Okay, couldnt install stretch again, it complains about:

```
E: there were unauthenticated packages and -y was used without --allow-unauthenticated
```

I deleted the chroot and tried again with the same error :(

**Comment by salinasv** [comment]
I just installed crouton, installed the "kde" target, and it didn't pulled kwin. I tried installing the "kde-desktop" target and it also don't pull kwin. I had to install it manually: apt-get install kwin-x11

croutonversion:

(sid)salinasv@localhost:~$ croutonversion 
crouton: version 1-20160902144033~master:9f8e9a22
release: sid
architecture: amd64
xmethod: xiwi
targets: kde-desktop,extension,kde,xiwi
host: version 8350.68.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:11:23 PDT 2016 x86_64 GNU/Linux
freon: yes

**Comment by drinkcat** [comment]
@smibarber got kde almost working, and did not hit this issue, right?
