### ISSUE TITLE
Change the default bootstrap release to trusty?

### ISSUE THREAD

**Issue by tonyxue** [dnschneid/crouton#1997]
The default release is still precise, which is really out of date. As trusty is working quite well now, how about switch to it?

If so, I'll submit the pr.

**Comment by tedm** [comment]
@tonyxue Can you qualify or quantify "really out of date" ?

**Comment by divx118** [comment]
@tonyxue  #1351 prevents a good experience with Unity on ARM. That is why it is still precise.

**Comment by DennisLfromGA** [comment]
@tedm,

> Can you qualify or quantify "really out of date" ?

[Here 'tis](http://goo.gl/qzpDjj)

**Comment by tedm** [comment]
this link?

http://askubuntu.com/questions/450555/very-slow-graphics-performance-after-upgrade-12-04-14-04

**Comment by drinkcat** [comment]
Dupe of #1671.
