### ISSUE TITLE
Can't copy paste across browser windows

### ISSUE THREAD

**Issue by MartinMalinda** [dnschneid/crouton#1998]
I am using xiwi to open Sublime text in a tab.
On another screen I have another browser window with different tabs and content. Basically if I want to copy paste across these windows I have to Copy in window A, paste in window B (not in Sublime), copy in window B and paste it sublime. Copying stuff out of Sublime is sometimes even more problematic.

Is there any solution for that?

**Comment by SimplySerenity** [comment]
If you have the chrome extension + xiwi it should be working fine, since as I understand it then shares a single clipboard. Maybe you need the extension target too? I have unified clipboard working with extension, but that is without xiwi.

**Comment by MartinMalinda** [comment]
These are the targets I have ```targets: cli-extra,core,extension,x11,xiwi``` as far as I know that should b enough to have clipboard working properly right?

**Comment by drinkcat** [comment]
Should be enough, if you have the extension installed. Please re-open if this is still an issue.
