### ISSUE TITLE
Chromebook not supporting Crouton

### ISSUE THREAD

**Issue by xfusionx** [dnschneid/crouton#1999]
Is there anything I need to download first or do before I try again? I have tried to download multiple times but it keeps saying that its not supported.. What do I do?

**Comment by DennisLfromGA** [comment]
Clicking on https://goo.gl/fd3zc should download 'crouton' to your Downloads folder.

You cannot, however, click on 'crouton' in the Files manager to invoke it, you have to have your Chromebook in 'Developer Mode' and open a crosh <kbd>Ctrl+Alt+t</kbd> *shell* session before you can run crouton ( sudo sh ~/Downloads/crouton ...). 

See the [README](https://github.com/dnschneid/crouton) for lots more info.

**Comment by DennisLfromGA** [comment]
[this can probably be closed now]
