### ISSUE TITLE
Not able to start crouton on Chromebook

### ISSUE THREAD

**Issue by dbrewitz** [dnschneid/crouton#2000]
I followed instructions from here:http://lifehacker.com/how-to-install-linux-on-a-chromebook-and-unlock-its-ful-509039343. and other places but still have errors when entering the shell console and typing "sudo startxfce4"

I have a new Asus C201. Tried updating, reinstalling, rebooting. No luck. Here is the log... Any ideas?

<h2>Details from /tmp/Xorg.crouton.1.log </h2>

[   814.670] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[   814.672] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[   814.672] X Protocol Version 11, Revision 0
[   814.672] Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
[   814.672] Current Operating System: Linux localhost 3.14.0 #1 SMP Tue Jul 28 16:26:06 PDT 2015 armv7l
[   814.672] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=20f9748c-9a5b-cd42-aed4-caf9543528ea/PARTNROFF=1 hashtree=PARTUUID=20f9748c-9a5b-cd42-aed4-caf9543528ea/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=6dd069323a418af962407b7fce1324999d6bd089 salt=458438494df0d75516c1775e7c8d5b183e19e6ee280c1b03d25330b7274fb3bc" noinitrd vt.global_cursor_default=0 kern_guid=20f9748c-9a5b-cd42-aed4-caf9543528ea  
[   814.673] Build Date: 05 November 2013  03:23:26PM
[   814.673] xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
[   814.673] Current version of pixman: 0.30.2
[   814.673] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[   814.673] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   814.673] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Aug  6 22:18:41 2015
[   814.674] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   814.675] (==) No Layout section.  Using the first Screen section.
[   814.675] (==) No screen section available. Using defaults.
[   814.675] (**) |-->Screen "Default Screen Section" (0)
[   814.675] (**) |   |-->Monitor "<default monitor>"
[   814.675] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[   814.675] (==) Automatically adding devices
[   814.675] (==) Automatically enabling devices
[   814.675] (==) Automatically adding GPU devices
[   814.675] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   814.675] 	Entry deleted from font path.
[   814.675] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   814.675] 	Entry deleted from font path.
[   814.675] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   814.675] 	Entry deleted from font path.
[   814.675] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[   814.675] 	Entry deleted from font path.
[   814.675] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   814.675] 	Entry deleted from font path.
[   814.676] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   814.676] 	Entry deleted from font path.
[   814.676] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[   814.676] 	Entry deleted from font path.
[   814.676] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[   814.676] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[   814.676] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[   814.676] (II) Loader magic: 0xb6fb4e58
[   814.676] (II) Module ABI versions:
[   814.676] 	X.Org ANSI C Emulation: 0.4
[   814.676] 	X.Org Video Driver: 13.0
[   814.676] 	X.Org XInput driver : 18.0
[   814.676] 	X.Org Server Extension : 7.0
[   814.676] Initializing built-in extension Generic Event Extension
[   814.676] Initializing built-in extension SHAPE
[   814.676] Initializing built-in extension MIT-SHM
[   814.676] Initializing built-in extension XInputExtension
[   814.676] Initializing built-in extension XTEST
[   814.676] Initializing built-in extension BIG-REQUESTS
[   814.676] Initializing built-in extension SYNC
[   814.676] Initializing built-in extension XKEYBOARD
[   814.676] Initializing built-in extension XC-MISC
[   814.676] Initializing built-in extension SECURITY
[   814.677] Initializing built-in extension XINERAMA
[   814.677] Initializing built-in extension XFIXES
[   814.677] Initializing built-in extension RENDER
[   814.677] Initializing built-in extension RANDR
[   814.677] Initializing built-in extension COMPOSITE
[   814.677] Initializing built-in extension DAMAGE
[   814.677] Initializing built-in extension MIT-SCREEN-SAVER
[   814.677] Initializing built-in extension DOUBLE-BUFFER
[   814.677] Initializing built-in extension RECORD
[   814.677] Initializing built-in extension DPMS
[   814.677] Initializing built-in extension X-Resource
[   814.677] Initializing built-in extension XVideo
[   814.677] Initializing built-in extension XVideo-MotionCompensation
[   814.677] Initializing built-in extension XFree86-VidModeExtension
[   814.677] Initializing built-in extension XFree86-DGA
[   814.677] Initializing built-in extension XFree86-DRI
[   814.677] Initializing built-in extension DRI2
[   814.677] (II) LoadModule: "glx"
[   814.678] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   814.679] (II) Module glx: vendor="X.Org Foundation"
[   814.679] 	compiled for 1.13.0, module version = 1.0.0
[   814.679] 	ABI class: X.Org Server Extension, version 7.0
[   814.679] (==) AIGLX enabled
[   814.679] Loading extension GLX
[   814.679] (==) Matched modesetting as autoconfigured driver 0
[   814.679] (==) Matched fbdev as autoconfigured driver 1
[   814.679] (==) Assigned the driver to the xf86ConfigLayout
[   814.679] (II) LoadModule: "modesetting"
[   814.680] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   814.681] (II) Module modesetting: vendor="X.Org Foundation"
[   814.681] 	compiled for 1.13.0, module version = 0.5.0
[   814.681] 	Module class: X.Org Video Driver
[   814.681] 	ABI class: X.Org Video Driver, version 13.0
[   814.681] (II) LoadModule: "fbdev"
[   814.682] (WW) Warning, couldn't open module fbdev
[   814.682] (II) UnloadModule: "fbdev"
[   814.682] (II) Unloading fbdev
[   814.682] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   814.682] (==) Matched modesetting as autoconfigured driver 0
[   814.682] (==) Matched fbdev as autoconfigured driver 1
[   814.682] (==) Assigned the driver to the xf86ConfigLayout
[   814.682] (II) LoadModule: "modesetting"
[   814.682] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   814.682] (II) Module modesetting: vendor="X.Org Foundation"
[   814.682] 	compiled for 1.13.0, module version = 0.5.0
[   814.682] 	Module class: X.Org Video Driver
[   814.682] 	ABI class: X.Org Video Driver, version 13.0
[   814.682] (II) UnloadModule: "modesetting"
[   814.682] (II) Unloading modesetting
[   814.682] (II) Failed to load module "modesetting" (already loaded, -1200187128)
[   814.682] (II) LoadModule: "fbdev"
[   814.683] (WW) Warning, couldn't open module fbdev
[   814.683] (II) UnloadModule: "fbdev"
[   814.683] (II) Unloading fbdev
[   814.683] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   814.683] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   814.683] (--) using VT number 7

[   814.698] (WW) Falling back to old probe method for modesetting
[   814.698] (II) modesetting(0): using default device
[   814.698] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[   814.698] (II) modesetting(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[   814.698] (==) modesetting(0): Depth 24, (--) framebuffer bpp 32
[   814.698] (==) modesetting(0): RGB weight 888
[   814.698] (==) modesetting(0): Default visual is TrueColor
[   814.698] (II) modesetting(0): ShadowFB: preferred NO, enabled NO
[   814.698] (EE) modesetting(0): KMS setup failed
[   814.698] (II) UnloadModule: "modesetting"
[   814.698] (EE) Screen(s) found, but none have a usable configuration.
[   814.698] 
Fatal server error:
[   814.698] no screens found
[   814.698] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[   814.698] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[   814.698] (EE) 

Thanks,

**Comment by tista500** [comment]
@dbrewitz There's quite similar issue on new RockChip Chromebook Flip: #1938 

Regards.

**Comment by twoodhouse** [comment]
Any progress on this @dbrewitz ? 
I just got the same computer and am having exactly the same issue. From what I have seen reading through other posts, it might have to do with the OS. Try reverting to the previous version if you are able. It seems that I cannot because my machine has nothing to revert back to (I just got it).

One other thing to note is that I WAS able to get around this problem at least temporarily by using the qiwi target. Couton will run as a windowed application when you do sudo startfxce4. This is not what I want though, because the Chrome text popup for getting out of full-screen mode is very annoying.

**Comment by dbrewitz** [comment]
@twoodhouse 
I was only able to run it with the Chrome extension as you did so far. For anyone else, to get that far I ran the command for installation: <code>sudo sh ~/Downloads/crouton -e -r trusty -t xfce,xfce-desktop,xiwi</code>. Then I installed <code>xorg</code> but when trying to run <code>sudo startxfce4 -X xorg</code> I gott the same errors. Running <code>sudo startxfce4 -X xiwi</code> is the only way I get it to run but the full-screen popup is bothersome.

**Comment by drinkcat** [comment]
Presumably fixed? See #1938.
