### ISSUE TITLE
UID 1000

### ISSUE THREAD

**Issue by scoopers** [dnschneid/crouton#2001]
I have read the other forums about this but i need exact instructions because i'm a noob. It works with LXDE, i want to fix it for desktop environment Xfce its always says
Mounting....
uid 1000 error
UnMounting....
Btw can someone tell me how to install the unity desktop to my pin drive please.

**Comment by DennisLfromGA** [comment]
> It works with LXDE

Does that mean you have a working chroot using the lxde desktop?

> i want to fix it for desktop environment Xfce its always says...uid 1000 error...

It looks like the installation didn't finish. It'd probably be best to delete it and start over - or, add the xfce target to your chroot with lxde.

> Btw can someone tell me how to install the unity desktop to my pin drive please.

Use crouton's '-p' option to specify where you want to install it, something like:

`sudo sh ~/Downloads/crouton -r trusty -t xfce,extension,keyboard -p /path/to/pindrive/`

**Comment by scoopers** [comment]
No, i keep try to I re-install fxce but it always keeps saying Uid 1000.
I need to format the pin drive for it to install but idk how to.

**Comment by DennisLfromGA** [comment]
>> It looks like the installation didn't finish. It'd probably be best to delete it and start over - or, add the xfce target to your chroot with lxde.

> No, i keep try to I re-install fxce but it always keeps saying Uid 1000.

You might want to try the 'trusty' release instead of 'precise', use '-r trusty' when intalling.

> I need to format the pin drive for it to install but idk how to.

Take a look at this thread for instructions, substituting sdb2 with your media device: https://github.com/dnschneid/crouton/issues/1515#issuecomment-83831807

**Comment by scoopers** [comment]
Yes i keep on trying to re install it and delete it and i'm using
sudo ~/Downloads/crouton -t trusty -r xfce

**Comment by scoopers** [comment]
I have tried other supported ones with xfce but it keeps getting an error saying
Uid 1000
when i try to mount it.

**Comment by scoopers** [comment]
I'm just going to use LXDE and move it to my pin drive so i have extra space programs.
But i was wondering can i install windows 10 iso file to a pin drive and mount it and install windows 10 on
here. USB booting through the bios does not work because i"m using a Acer 11 BIII

**Comment by scoopers** [comment]
Forget the windows 10 part its just stupid. But i wanna say thanks ill see if a can get the lxde to the Pin Drive.

**Comment by DennisLfromGA** [comment]
> Yes i keep on trying to re install it and delete it and i'm using
> sudo ~/Downloads/crouton -t trusty -r xfce

If that's what you actually entered (I doubt it), it should give you an error right away.
The options are turned around, it should be: `sudo `**sh**` ~/Downloads/crouton -r trusty -t xfce`

----

> I have tried other supported ones with xfce but it keeps getting an error saying
> Uid 1000
> when i try to mount it.

Then I would try lxde or another target besides xfce.

----

> But i was wondering can i install windows 10 iso file to a pin drive and mount it and install windows 10 on here.

Nope.

**Comment by scoopers** [comment]
My problem is solved i'm just going to install LXDE to a pin drive and just use it.

**Comment by DennisLfromGA** [comment]
That sounds like a very good solution, I use a trusty/lxde-desktop about 90% of the time.
