### ISSUE TITLE
keyboard target not working in gnome shell

### ISSUE THREAD

**Issue by avernan** [dnschneid/crouton#2002]
I've added the keyboard target to my gnome shell crouton with
```
sudo sh ~/Downloads/crouton -n croutonName -t keyboard -u
```
after starting it neither alt+backspace nor alt+search worked. Also I used to be able to use the search key to launch the exposed mode (the one with search bar and all open windows), but after adding the keyboard target it doesn't work any more. I'm not sure if the latter is intended, though. 

Edit. Search+Alt for caps lock is actually working. I was trying to use it on reverse (Alt+Search)
Edit2. As I was expecting, the change in behaviour of the search key is intended. When reading the wiki before I didn't associate the behaviour with the Super key

**Comment by tista500** [comment]
@avernan Keyboard target works well for me (Vivid Gnome + staging-PPA + extras).

If you had some custom keybindings, first you should remove xkb caches:
`sudo rm -f /var/lib/xkb/*.xkm`
And then re-assign them (via gnome-tweak-tool and/or gsettings).

Regards.

**Comment by avernan** [comment]
I've solved my 'problem' by reading other issues and the actual keyboard target file. It was a misunderstanding due to me using alt+key shortcuts in chromeos without knowing that a search+key equivalent existed and that is the one coming with the keyboard target.
@tista500 thanks anyway, and sorry for wasting your time
