### ISSUE TITLE
USB Device

### ISSUE THREAD

**Issue by scoopers** [dnschneid/crouton#2004]
I try to do
sudo umount /dev/sdb2
but it says that sdb2 is not a mounting point how do i fix this?

**Comment by scoopers** [comment]
BTW i"m using a 16 gig Sandisk USB device

**Comment by tcagle** [comment]
The mount command with no arguments will show all raw devices (like your /dev/sdb2) and the associated file system mount point path for the device.

**Comment by scoopers** [comment]
Speak English please.

**Comment by DennisLfromGA** [comment]
\<English>Also [google+ crouton users forum](https://plus.google.com/communities/109120069102230291151) is a better place for this question.\</English>

**Comment by scoopers** [comment]
What do you mean i did 
cd /dev/
dir
ashmem            cpu_dma_latency  full    i2c-3  log    loop-control     mmcblk0p1   mmcblk0p7           port    sda     tty1     vhci
block             cros_ec          fuse    i2c-4  loop0  mapper           mmcblk0p10  mmcblk0p8           ppp     sda1    tty8     video0
bsg               disk             hpet    i2c-5  loop1  max_online_cpus  mmcblk0p11  mmcblk0p9           pstore  shm     uhid     zero
bus               dm-0             hwrng   i2c-6  loop2  mcelog           mmcblk0p12  mmcblk0rpmb         ptmx    snd     uinput   zram0
char              dm-1             i2c-0   i2c-7  loop3  mem              mmcblk0p2   net                 pts     stderr  urandom
chromeos-low-mem  dri              i2c-1   i2c-8  loop4  min_online_cpus  mmcblk0p3   network_latency     random  stdin   usbmon0
console           esif_lf          i2c-10  i2c-9  loop5  mmcblk0          mmcblk0p4   network_throughput  rfkill  stdout  usbmon1
core              fb0              i2c-11  input  loop6  mmcblk0boot0     mmcblk0p5   null                rtc     tpm0    usbmon2
cpu               fd               i2c-2   kmsg   loop7  mmcblk0boot1     mmcblk0p6   nvram               rtc0    tty     v4l
WHat would it be????

**Comment by scoopers** [comment]
it was apparently sda1 for me not sdb.
So yeah hopefully this works.
