### ISSUE TITLE
No sceen found when lauching kde after installing crouton

### ISSUE THREAD

**Issue by lilou999999999** [dnschneid/crouton#2005]
I checked for updates but is didn't solve the problem.
What should i do ?

[  2569.983] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[  2569.983] X Protocol Version 11, Revision 0
[  2569.983] Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
[  2569.983] Current Operating System: Linux localhost 3.14.0 #1 SMP Tue Jul 28 16:26:06 PDT 2015 armv7l
[  2569.983] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=f0c4a91a-2d47-2845-a5c4-20a04f264e2b/PARTNROFF=1 hashtree=PARTUUID=f0c4a91a-2d47-2845-a5c4-20a04f264e2b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=6dd069323a418af962407b7fce1324999d6bd089 salt=458438494df0d75516c1775e7c8d5b183e19e6ee280c1b03d25330b7274fb3bc" noinitrd vt.global_cursor_default=0 kern_guid=f0c4a91a-2d47-2845-a5c4-20a04f264e2b  
[  2569.984] Build Date: 05 November 2013  03:23:26PM
[  2569.984] xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
[  2569.984] Current version of pixman: 0.30.2
[  2569.984] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  2569.984] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  2569.984] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Aug  8 19:25:28 2015
[  2569.985] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  2569.985] (==) No Layout section.  Using the first Screen section.
[  2569.985] (==) No screen section available. Using defaults.
[  2569.985] (**) |-->Screen "Default Screen Section" (0)
[  2569.985] (**) |   |-->Monitor "<default monitor>"
[  2569.986] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[  2569.986] (==) Automatically adding devices
[  2569.986] (==) Automatically enabling devices
[  2569.986] (==) Automatically adding GPU devices
[  2569.986] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  2569.986] 	Entry deleted from font path.
[  2569.986] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  2569.986] 	Entry deleted from font path.
[  2569.986] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  2569.986] 	Entry deleted from font path.
[  2569.986] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  2569.986] 	Entry deleted from font path.
[  2569.986] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  2569.986] 	Entry deleted from font path.
[  2569.986] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  2569.986] 	Entry deleted from font path.
[  2569.986] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  2569.986] 	Entry deleted from font path.
[  2569.986] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[  2569.986] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  2569.986] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[  2569.986] (II) Loader magic: 0xb6f39e58
[  2569.986] (II) Module ABI versions:
[  2569.986] 	X.Org ANSI C Emulation: 0.4
[  2569.986] 	X.Org Video Driver: 13.0
[  2569.986] 	X.Org XInput driver : 18.0
[  2569.986] 	X.Org Server Extension : 7.0
[  2569.987] Initializing built-in extension Generic Event Extension
[  2569.987] Initializing built-in extension SHAPE
[  2569.987] Initializing built-in extension MIT-SHM
[  2569.987] Initializing built-in extension XInputExtension
[  2569.987] Initializing built-in extension XTEST
[  2569.987] Initializing built-in extension BIG-REQUESTS
[  2569.987] Initializing built-in extension SYNC
[  2569.987] Initializing built-in extension XKEYBOARD
[  2569.987] Initializing built-in extension XC-MISC
[  2569.987] Initializing built-in extension SECURITY
[  2569.987] Initializing built-in extension XINERAMA
[  2569.987] Initializing built-in extension XFIXES
[  2569.987] Initializing built-in extension RENDER
[  2569.987] Initializing built-in extension RANDR
[  2569.987] Initializing built-in extension COMPOSITE
[  2569.987] Initializing built-in extension DAMAGE
[  2569.987] Initializing built-in extension MIT-SCREEN-SAVER
[  2569.987] Initializing built-in extension DOUBLE-BUFFER
[  2569.987] Initializing built-in extension RECORD
[  2569.987] Initializing built-in extension DPMS
[  2569.987] Initializing built-in extension X-Resource
[  2569.987] Initializing built-in extension XVideo
[  2569.988] Initializing built-in extension XVideo-MotionCompensation
[  2569.988] Initializing built-in extension XFree86-VidModeExtension
[  2569.988] Initializing built-in extension XFree86-DGA
[  2569.988] Initializing built-in extension XFree86-DRI
[  2569.988] Initializing built-in extension DRI2
[  2569.988] (II) LoadModule: "glx"
[  2569.989] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  2569.989] (II) Module glx: vendor="X.Org Foundation"
[  2569.989] 	compiled for 1.13.0, module version = 1.0.0
[  2569.989] 	ABI class: X.Org Server Extension, version 7.0
[  2569.989] (==) AIGLX enabled
[  2569.989] Loading extension GLX
[  2569.989] (==) Matched modesetting as autoconfigured driver 0
[  2569.989] (==) Matched fbdev as autoconfigured driver 1
[  2569.989] (==) Assigned the driver to the xf86ConfigLayout
[  2569.989] (II) LoadModule: "modesetting"
[  2569.990] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  2569.990] (II) Module modesetting: vendor="X.Org Foundation"
[  2569.990] 	compiled for 1.13.0, module version = 0.5.0
[  2569.990] 	Module class: X.Org Video Driver
[  2569.990] 	ABI class: X.Org Video Driver, version 13.0
[  2569.990] (II) LoadModule: "fbdev"
[  2569.991] (WW) Warning, couldn't open module fbdev
[  2569.991] (II) UnloadModule: "fbdev"
[  2569.991] (II) Unloading fbdev
[  2569.991] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  2569.991] (==) Matched modesetting as autoconfigured driver 0
[  2569.991] (==) Matched fbdev as autoconfigured driver 1
[  2569.991] (==) Assigned the driver to the xf86ConfigLayout
[  2569.991] (II) LoadModule: "modesetting"
[  2569.992] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  2569.992] (II) Module modesetting: vendor="X.Org Foundation"
[  2569.992] 	compiled for 1.13.0, module version = 0.5.0
[  2569.992] 	Module class: X.Org Video Driver
[  2569.992] 	ABI class: X.Org Video Driver, version 13.0
[  2569.992] (II) UnloadModule: "modesetting"
[  2569.992] (II) Unloading modesetting
[  2569.992] (II) Failed to load module "modesetting" (already loaded, -1217006560)
[  2569.992] (II) LoadModule: "fbdev"
[  2569.992] (WW) Warning, couldn't open module fbdev
[  2569.992] (II) UnloadModule: "fbdev"
[  2569.993] (II) Unloading fbdev
[  2569.993] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  2569.993] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  2569.993] (--) using VT number 7

[  2570.004] (WW) Falling back to old probe method for modesetting
[  2570.005] (II) modesetting(0): using default device
[  2570.005] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  2570.005] (II) modesetting(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[  2570.005] (==) modesetting(0): Depth 24, (--) framebuffer bpp 32
[  2570.005] (==) modesetting(0): RGB weight 888
[  2570.005] (==) modesetting(0): Default visual is TrueColor
[  2570.005] (II) modesetting(0): ShadowFB: preferred NO, enabled NO
[  2570.005] (EE) modesetting(0): KMS setup failed
[  2570.005] (II) UnloadModule: "modesetting"
[  2570.005] (EE) Screen(s) found, but none have a usable configuration.
[  2570.005] 
Fatal server error:
[  2570.005] no screens found
[  2570.005] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[  2570.005] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  2570.005] (EE) 
[  2570.018] Server terminated with error (1). Closing log file.

**Comment by tista500** [comment]
@lilou999999999 Oh please let us know the output of `croutonversion` at least... Because we don't know which machine you had, what version you've tried, so please...

Then is this issue related to #1996 ? If crouton installation might misunderstand the K-desktop dependency, after entering chroot via `sudo enter-chroot`, try apt-getting to install missing packages.

Regards.

**Comment by lilou999999999** [comment]
sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)lilou@localhost:~$ sudo startkde
[sudo] password for lilou: 
Do not launch startkde as root inside the chroot.
(precise)lilou@localhost:~$ croutonversion
crouton: version 1-20150730171703~master:f8fdfb0c
release: precise
architecture: armhf
xmethod: xorg
targets: kde
host: version 7077.111.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP Tue Jul 28 16:26:06 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes

when apt-getting : 

(precise)lilou@localhost:~$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(precise)lilou@localhost:~$

**Comment by tista500** [comment]
Codename "veyron_speedy" is ASUS C201, right? It has new Rockchip SoC and Chromebook Flip as well. So Flip owner reported DRI issue on X11/freon: #1938 You should read that thread.

>when apt-getting :
>(precise)lilou@localhost:~$ sudo apt-get -f install

And I meant `sudo apt-get install kwin-x11` since K user had reported so... crouton would not break package dependencies within installation, but sometimes it forgets to install a couple of packages outside of core desktop environment.
