### ISSUE TITLE
minor problem: background not being erased

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#2007]
A few days ago a problem appeared.  When I close a xiwi window it leaves part of the window image on my desktop.  The window painting logic is flawed.  I assume it was some upgrade to the OS.  I.E. not a crouton bug.  Although so far I've only seen it with xiwi windows.  I have not upgraded crouton in a long time and I will do that now.  BTW, how do I find the crouton version number?

Loosely-related topic:  I have found chromebooks to be buggy when the browser isn't full screen.  For example many web pages appear with no border.  They are hard to read when pixels bleed directly into other windows.  I assume chromebooks are run with the browser full-screen 99% of the time so the bugs aren't noticed.  The painting bug I am reporting would fall into this category.

crouton date: 7/28
2015 pixel
Version 44.0.2403.90 (64-bit)
Platform 7077.95.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.128.0

**Comment by DennisLfromGA** [comment]
@mark-hahn,

> BTW, how do I find the crouton version number?

`sudo sh ~Downloads/crouton -V` will show you what version the indirect installer will provide you.
`sudo edit-chroot -al` will show you the croutonversion and other details of your chroot(s).

**Comment by drinkcat** [comment]
Please reopen if this happens again...
