### ISSUE TITLE
Latest Intel Graphics Driver doesn't work on Ubuntu Trusty (14.04)

### ISSUE THREAD

**Issue by juangril** [dnschneid/crouton#2008]
Hey everybody. I have a Chromebook Pixel 2, and I've been having some problems with OpenGL. I wanted to update to the latest Intel Graphics Drivers, and from what I read they don't support Ubuntu Trusty anymore:
https://01.org/linuxgraphics/forum/graphics-installer-discussions/do-not-use-ubuntu-14.04
 
Crouton states that it doesn't support 15.04. Has anyone tried it?

**Comment by dnschneid** [comment]
You probably want to read and follow along with #1706.
