### ISSUE TITLE
Unlocking the Chromebook via command line (within a chroot)

### ISSUE THREAD

**Issue by Sebb767** [dnschneid/crouton#2010]
This may be a little off-topic here, but I'm onto writing a script to synchronize locking between a chroot and chromebook (in order to contribute it later on). It works by starting a lockscreen in the chroot as soon as the "ScreenIsLocked"-Signal is received and killing the lockscreen when the screen is unlocked via the ChromeOS lockscreen. The actual commands for (un-)locking are configurable. This would fix #573 and improve user security.

By now it's possible to start a screensaver when the chromebook is locked and to disable it when it's being unlocked. It's also possible to lock the chromebook from within the chroot via

```
host-dbus dbus-send --system --dest=org.chromium.SessionManager \
    --type=method_call --print-reply /org/chromium/SessionManager \
    org.chromium.SessionManagerInterface.LockScreen
```

The problem is that I don't know how to unlock the chromebook in case it's unlocked via the chroots lockscreen. It should be possible somehow without password since SmartLock can do it. I couldn't find anything useful in the [session manager interface](https://chromium.googlesource.com/chromiumos/platform2/+/master/login_manager/org.chromium.SessionManagerInterface.xml) though, but this doesn't necessarily mean anything ;)

Another possibility would be to prevent switching VTs when the chromebook is locked, but I'd prefer to keep it this way to allow for custom lockscreen setups (in case you want customized backgrounds or another auth method unsupported by ChromeOS). Also, this would mean that I need to mess with croutoncycle, which should probably be avoided.

Any idea how to do this?

**Comment by divx118** [comment]
IMO it should work as @drinkcat mentioned [here](https://github.com/dnschneid/crouton/issues/573#issuecomment-32010186) So no unlocking chromiumos from a chroot, if it is even possible.

Just my 2 cents.

**Comment by Sebb767** [comment]
Possible, maybe even a better option, but as I mentioned above I'd like to keep core components untouched as far as possible (to make it a target instead of a core member) and to leave an option for custom unlocking options (usbs; wlan accesspoints; customizeable) which are not supported by ChromeOS. 

The chroot being (un-)locked (as in: lock command executing) when ChromeOS is (un-)locked is already possible.

Ideally you could switch modes by changing a variable, but if impossible this is the way to go I guess :/

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
