### ISSUE TITLE
Error to output - fwrite (28: No space left on device) after Chrubuntu installation

### ISSUE THREAD

**Issue by JohnLawsonParticle** [dnschneid/crouton#2013]
Hello everyone, 

I've just bought a ASUS C300 and I installed crouton a first time without any problem. 
After I heard about Chrubuntu I decided I would try it and I tried to installed it. As the ASUS C300 doesn't support legacy boot apparently, It did not work and I wanted to get back to crouton. 

So, I switched back from developper mode to OS verification and switch back again to Developper mode, hoping that it would erease all the data from Chrubuntu. 

Unfortunatly, when I try to install crouton (-t ubunty -r trusty) I get this message : 

WARNING: icon cache generation failed
dpkg: unrecoverable fatal error, aborting:
 unable to flush /var/lib/dpkg/updates/tmp.i after padding: No space left on device
E: Sub-process /usr/bin/dpkg returned an error code (2)
E: IO Error to output - fwrite (28: No space left on device)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

As i found this issue : https://github.com/dnschneid/crouton/issues/461

I decided to run the command df -h /usr/local and I get :  

Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1  1.9G  1.9G     0 100% /usr/local

When running df -h /home/chronos/user : 

Filesystem                                                    Size  Used Avail Use% Mounted on
/home/.shadow/46809b3deae6f34ccac4b0119988963ae23d5131/vault  1.9G  1.9G     0 100% /home/chronos/user

I tired to remove the chroot and run the same commands and I get :

Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1  1.9G  188M  1.6G  11% /usr/local

Filesystem                                                    Size  Used Avail Use% Mounted on
/home/.shadow/46809b3deae6f34ccac4b0119988963ae23d5131/vault  1.9G  188M  1.6G  11% /home/chronos/user

I guess Chrubuntu messed up with my partitionning. I have tried to use a recovery USB for Chrome OS but I can't get it to work. 

I guess I could try to install my chroot in another directory but I would like to remove all the messy partitionning Chubuntu did. 

Please, could you help me? I would be quite disappointed to realise that I turned my chromebook into a brick. 
Thank you very much.

**Comment by tista500** [comment]
@JohnLawsonParticle,
ChromeOS's recovery USB (factory refresh image) should work even if chrubuntu had changed/created its partition, Yep, I've tried it before and it could recover my Asus C200 from chrubuntu state...

**off-topic**
John had finally opened a custom firmware for BayTrail-M Chromebooks: https://johnlewis.ie/baytrail-release/ This would be able to install standard x86_64 Ubuntu with the same way we do on Windows desktop/laptop. :)

Regards.

**Comment by JohnLawsonParticle** [comment]
Thank you for your answer. Chrome OS recovery USB doesn't seem to work on my case. I'll try again. 

In case it doesn't work, is there a way to change the partitionning of my chromebook? I am interrested in it anyway. 

Regarding the custom firmware, I'm quite afraid to go too far into unknown territory at the moment, but thank you for your tip!

**Comment by tista500** [comment]
@JohnLawsonParticle,

>In case it doesn't work, is there a way to change the partitionning of my chromebook? I am interrested in it anyway.

We would be able to delete the unused partition from chroot via fdisk and/or gnome-disk utility, but we can't resize partition for **current running system root partition** in general. In other words, we should hack chrubuntu script somehow to resize partition (`/dev/mmcblk0p1`) and run it on crosh without entering chroot...

Anyway ChromeOS recovery USB is the best choice I think (if it worked properly).

Regards.

**Comment by tista500** [comment]
@JohnLawsonParticle,

This thread might be useful (First comment seems to explain how chrubuntu create/resize partition)?
https://productforums.google.com/forum/#!msg/chromebook-central/ZNMEZf41eOo/LmlOVGtrEd8J

Regards.

**Comment by JohnLawsonParticle** [comment]
@tista500 Thank you for your help! I managed to get the ChromeOS Recovery USB to work and now I can run crouton without any flaw. Except for the language module that always crash when I try to change the system language. 

Thank you for the thread also. 

Regards.
