### ISSUE TITLE
How to migrate from chroot Ubuntu to a directly booted Ubuntu?

### ISSUE THREAD

**Issue by yangguang760** [dnschneid/crouton#2014]
Hi,

I've been using chroot for a while, everything is OK but functions over VM.
So, are there any solution to migrate chroot Ubuntu to a directly booted Ubuntu together with all data and configurations?

**Comment by DennisLfromGA** [comment]
No mechanism is in place to directly install your crouton chroot to your Chromebook with the required repartitioning, etc.

HugeGreenBug (Hugh Greenburg) has a site named [Distroshare](https://www.distroshare.com/) where he has created several custom distros for various [Chromebooks and Chromeboxes](https://www.distroshare.com/distros/category/) with SeaBIOS. He also has a [shell script](https://www.distroshare.com/wiki/distroshare_imager/) for "re-mastering" your current installation that may be what you're looking for. I don't know if it will work correctly on a crouton chroot installation but I guess it's worth a shot. If that doesn't work, he has [other methods](https://www.distroshare.com/wiki/) that may work for you.
