### ISSUE TITLE
After latest update sound not working in 14.04

### ISSUE THREAD

**Issue by bosiakov** [dnschneid/crouton#2015]
After latest update on my Acer 720 audio not work. System - 14.04.

If i try run audio mixer:

```
GStreamer was unable to detect any sound devices. Some sound system specific GStreamer packages may be missing. It may also be a permissions problem.
```

All video/audio players not start. VLC:
```
$ vlc
VLC media player 2.2.1 Terry Pratchett (Weatherwax) (revision 2.2.1~trusty1)
[000000000181a548] pulse audio output error: PulseAudio server connection failure: Connection refuse
```

```
ver: 45.0.2454.26 beta (64-bit)
platform: 7262.25.0 (Official Build) beta-channel peppy
Google_Peppy.4389.93.0
```

```
$ croutonversion
crouton: version 1-20150716185530~master:aba2c948
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,xorg,xfce-desktop
host: version 7262.25.0 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 3 21:46:45 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by tista500** [comment]
@bosiakov, I have some questions.

**1. Was audio card registered correctly?**
let us see the output of `cat /proc/asound/cards`.

**2. alsamixer works?**
`alsamixer` is simply launched this command, and see top-left of terminal, if Card and Chip were set as "CRAS", it would be normal.

**3. pulseaudio was installed properly?**
if you haven't, please install those packages with `sudo apt-get install pulseaudio`.

Regards.

**Comment by bosiakov** [comment]
@tista500
1)
```
$ cat /proc/asound/cards
 0 [MID            ]: HDA-Intel - HDA Intel MID
                      HDA Intel MID at 0xe0510000 irq 60
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xe0514000 irq 61
```
2) Alsamixer dont work.

3) Pulseaudio is already the newest version.

**Comment by tista500** [comment]
OK, it might need re-compile CRAS module, so how about updating crouton (your crouton version is not the latest one)? In ChromeOS's "crosh" window, give it a try:
```
sudo sh ~/Downloads/crouton -u
```
Simple way is something like that. If you had multi chroots, or special install locations, please set them with proper options for crouton.

Regards.

**Comment by drinkcat** [comment]
@tista500 is probably right, try a chroot update... Looks like we should revive #1049...

**Comment by dahveed** [comment]
Hi, I have this same issue (as I wrote here: https://github.com/dnschneid/crouton/issues/2174 ), but I can't seem to be able to update my chroot.

**Comment by krypticwolf3** [comment]
I actually have the same issue.  The sound stopped working after I updated my chroot a couple days ago, though admittedly, I do not remember when I last updated.

**Comment by dahveed** [comment]
I "fixed" this by deleting the chroot and creating a new one. Certainly not an ideal solution, but it worked! I still get occasional audio creaks and pops, but those seem tied to high system load or having many audio-using programs open at the same time. Restarting (powerwash, not just logging out of the chroot) fixes that, at least for a day or two.

**Comment by drinkcat** [comment]
Duping to #1049.
