### ISSUE TITLE
Crouton update broken (again) ....  xiwi connectivity to extension working (again)

### ISSUE THREAD

**Issue by tcagle** [dnschneid/crouton#2018]
My xiwi was broken on my precise chroot for several iterations of chromeos updates then suddenly started working again with most recent update of butterfly stable. Now my crouton update is broken and is terminating early with the following output....

chronos@localhost ~ $ /usr/bin/sudo sh ~/Downloads/crouton -u -n precise.pws 
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise.pws already exists; updating it...
Enter encryption passphrase for precise.pws: 
WARNING: USB booting is enabled; consider disabling it.
WARNING: Legacy booting is enabled; consider disabling it.
WARNING: Signed boot verification is disabled; consider enabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_legacy=0 dev_boot_signed_only=1
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
xephyr target does not work with Freon. Use xiwi instead.

**Comment by tonyxue** [comment]
Could you please provide the output of ```croutonversion``` ?

**Comment by tcagle** [comment]
Yes....

(precise.pws)tim@localhost:~$ croutonversion
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: xiwi,xorg,xephyr,xfce-desktop,keyboard,xfce,extension
host: version 7077.123.0 (Official Build) stable-channel butterfly_freon 
kernel: Linux localhost 3.8.11 #1 SMP Sat Aug 8 00:59:47 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
(precise.pws)tim@localhost:~$

**Comment by DennisLfromGA** [comment]
It looks like 'xorg' is your default xmethod, to use 'xiwi' try: `sudo startxfce4 -n precise.pws -X xiwi`

**Comment by 1rocketdude** [comment]
doesn't work for me. I get the long list of "Cannot connect to extension, retrying"

**Comment by DennisLfromGA** [comment]
@1rocketdude - I was replying to @tcagle, you may have a different problem.
Show us the output of: `sudo edit-chroot -al` and we can go from there.

**Comment by 1rocketdude** [comment]
help would be appreciated. Crouton is now a necessity for me - better
than any other laptop solution. I know my Samsung 550C Chromebook is a
bit "old", but it still works great in ChromeOS.


name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,lxde,audio,xorg,chrome
host: version 7077.123.0 (Official Build) stable-channel lumpy
kernel: Linux localhost 3.4.0 #1 SMP Sat Aug 8 00:58:09 PDT 2015
x86_64 x86_64 x86_64 GNU/Linux
freon: no

**Comment by tcagle** [comment]
I guess I can close this as the most recent butterfly_freon (stable) update has gone back to this behavior (see paste below). I can still (once again) start my DE by using the xmethod xephyr. I see a vicious cycle starting here ;) 

$ sudo startxfce4 -n precise.pws -X xiwi
Enter encryption passphrase for precise.pws: 
Entering /mnt/stateful_partition/crouton/chroots/precise.pws...
WARNING: /etc/rc.local failed with code 1
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Sun Aug 16 14:38:38 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=51af3536-2488-c043-a4bc-6329ac85d87a/PARTNROFF=1 hashtree=PARTUUID=51af3536-2488-c043-a4bc-6329ac85d87a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=8964eea391e19aa40d90e617bbbb37583a569ede salt=c5608c9216a49c1403e026d30d88d11f5b437cd41f06e535518d705ce5053a8c" noinitrd vt.global_cursor_default=0 kern_guid=51af3536-2488-c043-a4bc-6329ac85d87a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Aug 19 09:25:16 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150811114815~master:f6b810fe
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xephyr,xfce-desktop,keyboard,xfce,extension
host: version 7077.134.0 (Official Build) stable-channel butterfly 
kernel: Linux localhost 3.4.0 #1 SMP Sun Aug 16 14:38:38 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
 ddxSigGiveUp: Closing log
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise.pws...
chronos@localhost ~ $

**Comment by DennisLfromGA** [comment]
@1rocketdude - You could try adding the 'xorg' xmethod and see if that works for you in the interim.
Just add it using: `sudo sh ~/Downloads/crouton -t xorg -n trusty -u`
Then you can start your desktop with:
`sudo startlxde` for 'xorg' and `sudo startlxde -X xiwi` for 'xiwi'.

**Comment by 1rocketdude** [comment]
I was hopeful, but no luck. Neither desktop nor xiwi work. The desktop
starts but all I get is a black screen. starting with xiwi I get the same
stuff I've seen in the past

Loading extension GLX
Unable to set master
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,lxde,audio,chrome
host: version 7077.123.0 (Official Build) stable-channel lumpy
kernel: Linux localhost 3.4.0 #1 SMP Sat Aug 8 00:58:09 PDT 2015
x86_64 x86_64 x86_64 GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...

**Comment by tcagle** [comment]
Doing the -t xorg target update as suggested above has repaired my default xmethod to a working condition. The xiwi however continues to throw this stuff though...

Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
croutonwebsocket error: Error timeout
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
 ddxSigGiveUp: Closing log
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise.pws...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/precise.pws...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/precise.pws...

**Comment by timnolte** [comment]
My xiwi chroot is broken once again as well. Actually for awhile I had to hack my chroot to even get xiwi to run but then I lost copy/paste. I had always launched a specific app the following way:

`sudo enter-chroot -n trusty xiwi easytag`

When I do that all I get is the `Cannot connect to extension, retrying...` error.

```
Entering /mnt/stateful_partition/crouton/chroots/trusty...


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Sun Aug 16 12:47:02 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-1 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="2 vboot none ro 1,0 2545920 bootcache PARTUUID=52591659-ca71-3a45-8fff-d4ece0f3e95b/PARTNROFF=1 2545920 caed6d3a0e7d0a25fc56054fc12e5debf3095c92 512 20000 100000, vroot none ro 1,0 2506752 verity payload=254:0 hashtree=254:0 hashstart=2506752 alg=sha1 root_hexdigest=70965d07a115efa0eb44350bd9d57fb20d3ded6b salt=7220a874d9ff38a304b7cf32fc1ec371fbd446a258058ab50497175611e5ed33" noinitrd vt.global_cursor_default=0 kern_guid=52591659-ca71-3a45-8fff-d4ece0f3e95b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Aug 23 15:03:25 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,audio,keyboard,extension,cli-extra,xorg
host: version 7077.134.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Sun Aug 16 12:47:02 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Error: target STRING not available
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

My `croutonversion` result:

```
(trusty)timnolte@localhost:~$ croutonversion
crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,audio,keyboard,extension,cli-extra,xorg
host: version 7077.134.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Sun Aug 16 12:47:02 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
```

I've also tried `sudo startxiwi easytag` and I get the same cannot connect errors and failure.

```
Entering /mnt/stateful_partition/crouton/chroots/trusty...


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.4.0 #1 SMP Sun Aug 16 12:47:02 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-1 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="2 vboot none ro 1,0 2545920 bootcache PARTUUID=52591659-ca71-3a45-8fff-d4ece0f3e95b/PARTNROFF=1 2545920 caed6d3a0e7d0a25fc56054fc12e5debf3095c92 512 20000 100000, vroot none ro 1,0 2506752 verity payload=254:0 hashtree=254:0 hashstart=2506752 alg=sha1 root_hexdigest=70965d07a115efa0eb44350bd9d57fb20d3ded6b salt=7220a874d9ff38a304b7cf32fc1ec371fbd446a258058ab50497175611e5ed33" noinitrd vt.global_cursor_default=0 kern_guid=52591659-ca71-3a45-8fff-d4ece0f3e95b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Aug 23 15:09:47 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,audio,keyboard,extension,cli-extra,xorg
host: version 7077.134.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Sun Aug 16 12:47:02 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Error: target STRING not available
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by tcagle** [comment]
Well the vicious cycle has cycled again... Now the xiwi sessions work again with latest chromeos update:
Version 45.0.2454.86 (64-bit)
Platform 7262.52.0 (Official Build) stable-channel butterfly
Firmware Google_Butterfly.2788.39.0
 
BUT... the crouton update no longer works (again) like this...

crosh> shell
chronos@localhost / $ /usr/bin/sudo sh ~/Downloads/crouton -u -n precise.pws
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise.pws already exists; updating it...
WARNING: USB booting is enabled; consider disabling it.
WARNING: Legacy booting is enabled; consider disabling it.
WARNING: Signed boot verification is disabled; consider enabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_legacy=0 dev_boot_signed_only=1
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
xephyr target does not work with Freon. Use xiwi instead.
chronos@localhost / $

**Comment by divx118** [comment]
@tcagle Use `sudo sh ~/Downloads/crouton -u -n precise.pws -t xiwi` to update your chroot. This will set xiwi as default instead of xephyr which you now have as default.

**Comment by cvmiller** [comment]
I too am now seeing this problem. And have followed much of what is in this thread. The key difference is that I am using ARM.


Google Chrome	45.0.2454.86 (Official Build) (32-bit)
Revision	c9cfd5572d17dddaaef69cd6e45ebd76750a2150
Platform	7262.52.0 (Official Build) stable-channel daisy
Blink	537.36 (@201276)

crouton: version unknown
release: unknown
architecture: unknown
xmethod: xiwi
targets: xiwi,xfce,extension,audio,core,xephyr,x11,keyboard
host: version 7262.52.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 31 19:45:33 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes

chronos@localhost ~/Downloads $ sudo sh -e ~/Downloads/crouton -u -r trusty -t xiwi
/usr/local/chroots/trusty already exists; updating it...
...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
xephyr target does not work with Freon. Use xiwi instead.

It appears that using -t xiwi does not _disable_ xephr. Is there a way to force disabling xephr (since I only use xiwi)?

Thanks in advance,

Craig...

**Comment by DennisLfromGA** [comment]
@cvmiller - It looks like, since you specified 'xephyr' as a target during an install or update, crouton is trying to update the chroot with it and failing.

I don't have a very good answer for you but you could remove `,xephyr` from your `/usr/local/chroots/trusty/etc/crouton/targets` file, leaving the other targets in place and then try updating the chroot again with just: `sudo sh ~/Downloads/crouton -u -n trusty` and see if it completes successfully.

**Comment by cvmiller** [comment]
That did the trick! Thanks Dennis. Not sure how xephyr got in there, but without it the update works, and I can use xiwi as I did before. 

Thanks again.

Craig...

**Comment by tcagle** [comment]
That may have worked for Craig Miller but not for my precise butterfly
stable install HP Chromebook pavilion 14.  Still getting the same error
message. I assume the full path you are giving indicates that your chroot
is not encrypted either Craig Miller. I opened my DE and performed the
suggested edit of the /etc/crouton/targets file as root and still no joy
trying to update the chroot. If history repeats itself a future chromeos
update will flip it back to the other issue any day now. I would hate to
rely on this for my every day linux system ;) Even so it is the best linux
portable system I've ever personally owned and my hat is off to the
developers.

**Comment by cvmiller** [comment]
tcagle, 

I am sorry to hear that this work-around didn't solve your problem. If you remove xephyr from the target list, do you get a different error when trying to update?

I agree, there are serious challenges for the Crouton developers with Google changing things without regard to the folks who want to use Chromebook as Linux machines. My hat is off to the great things the Crouton Devs have done so far. Thank you.

Craig...

**Comment by DennisLfromGA** [comment]
@tcagle -

> I opened my DE and performed the
> suggested edit of the /etc/crouton/targets file as root and still no joy
> trying to update the chroot.

Do you mean it's still failing with the last error line:

> xephyr target does not work with Freon. Use xiwi instead.

That shouldn't be happening.

If you are getting other errors, let us know what they are.

**Comment by tcagle** [comment]
Yes I was still getting the "xephyr target does not work with Freon. Use xiwi instead." Based on your comment I reexamined the "targets" file and found that the edit was incorrect and the file now contained a leading comma before the xiwi and an addition to the end of the line of ",xephyr". Those were definitely not my edits.... So I edited a second time and ran the crouton upgrade and it appears to be working now. Thanks for suggesting something was awry with the edited file. I am going to close this issue and pray that the flip side of it (the crouton extension failing to respond to chroot connection attempts) doesn't recur in the near future. Thanks for the input folks.

**Comment by 1rocketdude** [comment]
what does a leading comma in the target file mean? Is it erroneous. My
chroot now works, but out of curiosity I checked and I have a leading comma
as well. Should I manually delete it? Without looking/understanding the
crouton script, I wonder if a parse error could occur.

thanks - Tom

**Comment by tcagle** [comment]
It must be the crouton update that is adding the leading "," to the targets
file because that leading comma is back on mine now too. But the xephyr
entry stayed deleted so mine system is okay for now. The update still works
a bit strangely but it does finally complete successfully and a
croutonversion -u -d -c shows that my chroot is fully up to date now.

**Comment by DennisLfromGA** [comment]
Yep, crouton adds the leading comma but it's inconsequential.

**Comment by DennisLfromGA** [comment]
Maybe we need to revisit '[DE/target removal](https://github.com/dnschneid/crouton/issues/717)'.

**Comment by DennisLfromGA** [comment]
@dnschneid - Would something like [this](https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:patch-5) work on systems with Freon *and* xephyr in the interim?
