### ISSUE TITLE
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as as another instance is using it.

### ISSUE THREAD

**Issue by Noble99** [dnschneid/crouton#2019]
Hello.
I have tried everything to I can to unmount this chroot for backup, and the only thing that works is force unmounting. I updated to the latest version of crouton and it still will not unmount. 

```javascript
(trusty)mwaara99@localhost:~$ croutonversion
crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 7077.123.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Aug 7 23:11:02 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

When using the command unmount-chroot -p trusty:
```javascript
chronos@localhost / $ sudo unmount-chroot -p trusty
26936 su - mwaara99
27416 su - mwaara99
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```

Again, the only thing that seems to work is force unmounting the chroot.

**Comment by tonyxue** [comment]
Please check whether you have any upstart process that would run in the background. Sometimes it keeps running in the chroot.

**Comment by Noble99** [comment]
Thanks, I just ended up powerwashing my chromebook and re-installing. So far, so good! It unmounts without any issues.
