### ISSUE TITLE
Unable to switch between keyboard layouts in xiwi

### ISSUE THREAD

**Issue by tedodactyl** [dnschneid/crouton#2020]
Greetings,
For some reason, whenever I launch an application through xiwi (without launching the full xfce4 desktop) with the command "sudo startxiwi -b app-name" I am unable to switch between different keyboard layouts, but can only type in English. This forces me to launch the full xfce4 desktop with "sudo startxfce4 -b -X xiwi" just to open the same app, only with the ability to use my second language as well.
Any suggestions on how I can get this fixed?
Thanks in advance,
Daniel

**Comment by SnarkBoojum** [comment]
In fact, the problem is that the default layout is qwerty ; with a full desktop we can override it, but with a single app, we're somehow trapped with it.

So the question is : how to change the default layout ?

**Comment by jmaris** [comment]
Hey, I've got a fix for this. You need to launch your settings daemon with xiwi, if you use xfce : 
add the following to your ~/.xiwirc file
```
xfsettingsd&

**Comment by SnarkBoojum** [comment]
@jmaris I tried your fix with emacs : it just doesn't work. Which is quite natural, since we need a way to override the default layout for every X app, and not just XFCE ones...

**Comment by robert-johansson** [comment]
I have the same issue with crouton/Ubunty trusty. If I start Unity with `startunity` I have my Swedish default keyboard. However, if I start for example xterm with `sudo enter-chroot xiwi xterm` then I get English keyboard.

Any ideas how to fix this?

**Comment by jmaris** [comment]
@SnarkBoojum This should work for everything, as xfsettingsd manually sets the keyboard layout for your X Session. It isn't defined per app.
It should work with emacs, trying now

**Comment by SnarkBoojum** [comment]
@jmaris Oh, I just saw in the log that xfsettingsd isn't available on my system... it might work better if I install it...

**Comment by robert-johansson** [comment]
Will the `xfsettingsd` command also work without xfce, for example with Unity?

**Comment by SnarkBoojum** [comment]
@jmaris nope, now xfsettingsd complains in the log that it doesn't find the session management -- so it's not working. Perhaps some .xinitrc or some such would be better ?

**Comment by jmaris** [comment]
@SnarkBoojum  i suppose it's because I installed the XFCE target
@robert-johansson This won't work with Unity, if you want to do this with unity you need to find ubuntu's session manager (i believe it's called unity-settings-daemon),
try putting 
```
unity-settings-daemon&
```

in the forementioned file

**Comment by jmaris** [comment]
Keep me up to date on if it works, psuedo-unrelated information : I'm working on a launcher that automatically runs crouton apps via xiwi in chromeOS. If your interested in not having to open things via terminal every time, feel free to take a look : https://www.reddit.com/r/Crouton/comments/3hazuo/crouton_launcher_launch_crouton_apps_with_xiwi/

**Comment by robert-johansson** [comment]
`setxkbmap se` in my ~/.xiwirc did what I was looking for! Thanks!

**Comment by SnarkBoojum** [comment]
Excellent!

**Comment by drinkcat** [comment]
@robert-johansson : Thanks for the tip!

This, at the very least, needs a wiki entry, and possibly a better fix in crouton.

**Comment by liapman** [comment]
This fix allows me to launch the program with a different language as my keyboard layout. However, I can't switch layouts while typing in the application. So if I'm using libreoffice for example and need to use both English and Hebrew in a single document, I can't do that with this method.

**Comment by liapman** [comment]
This fix allows me to launch the program with a different language as my keyboard layout. However, I can't switch layouts while typing in the application. So if I'm using libreoffice for example and need to use multiple languages in a single document, I can't do that with this method.
