### ISSUE TITLE
broken crouton chroots after chrome os update

### ISSUE THREAD

**Issue by NoPinky** [dnschneid/crouton#2021]
It seems like many people are having the same problem as me after one of the recent chrome os update. 
After 
```
sudo enter-chroot -n [name of my chroot] 
```
it still seems to be as usual. 
Then I went with 
```
startlxde
```

but get:
```
(trustylxde)pigrider@localhost:~$ startlxde
Agent pid 25546
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE

(lxsession:25538): Gtk-WARNING **: cannot open display: 
```
Apparently people got some workaround to solve this, but I don't understand what is really going on. Usually when those kind of things happen, there is a little writeup on what is causing it, "who is to blame" and what one can do. I want to understand the cause instead of just copy and paste some command and hope this will solve the problem. 
Sure, crouton is experimental and we have been warned that it is messy. But it seems to me that there are people who have deep understanding of what is under the hood.
So, can someone give me and other people a brief explanation on what is going on, please? 
Thank you in advance!

**Comment by 1rocketdude** [comment]
crickets.... 
I haven't been this long without functioning chroot forever. Anyone have any suggestions? Seems to be an interplay with the latest OS update, so I don't think rolling back to a backup of my chroot will help.

**Comment by NoPinky** [comment]
I've found this regarding reverts:
http://www.chromestory.com/2014/11/chromebooks-get-options-downgrade-operating-system/
I might do that, but maybe I will wait some more time, because I'm to lazy to transfer my files around (got a C710 with 320GB HDD)

**Comment by DennisLfromGA** [comment]
If you've recently received a Chrome OS update *and* your having problems with your chroot, it's a very good idea to update your chroot. See '[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)' for help.

Also, I like to backup my chroot(s) occasionally and especially before doing an update. See '[A backup a day keeps the price-gouging data restoration services away](https://github.com/dnschneid/crouton#a-backup-a-day-keeps-the-price-gouging-data-restoration-services-away)' for help.

**Comment by NoPinky** [comment]
@DennisLfromGA 
jep, I got some backups on my HDD. That's not really the problem if the chroot just simply isn't able to start it's desktop.
However I got it solved. After pulling a new crouton script, update the existing chroot, adding xiwi (didn't feel the need to use it before) and xorg (not sure if xorg is necessary) to the targets, then: following this instruction to make it work:
https://github.com/dnschneid/crouton/issues/1815
I guess I'm happy for now that it is working again.

**Comment by DennisLfromGA** [comment]
> That's not really the problem if the chroot just simply isn't able to start it's desktop.

In my experience, that could very well be the problem.

> After pulling a new crouton script, update the existing chroot

And that, alone, may have *fixed* it; adding 'xiwi' is probably a bonus though...
