### ISSUE TITLE
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg

### ISSUE THREAD

**Issue by tylerdefoor** [dnschneid/crouton#2022]
I had successfully installed Ubuntu on my Chromebook earlier today, and everything seemed to go fine. I could get in and do everything I needed. After powering on later, I couldn't get in! I figured the install had just gotten corrupted somehow, so I deleted it and reinstalled it. The reinstallation was taking forever! I cancelled it and tried again, but I noticed the first thing I got was:
Installing precise-amd64 chroot to /usr/local/chroots/precise
Downloading latest debootstrap...
2015-08-15 03:19:54 URL:http://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [62068] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving Release 
I: Retrieving Packages 

Am I doing something incorrectly?

The command I'm using is: sudo sh -e ~/Downloads/crouton -t unity

**Comment by DennisLfromGA** [comment]
@dnschneid - Could this be due to a 'left over' key? (https://github.com/dnschneid/crouton/pull/1993#discussion_r36221301)

**Comment by dnschneid** [comment]
Nope, we don't use keyrings with debootstrap yet.  Filed a bug for that #2103.
