### ISSUE TITLE
Switching from XFCE to Unity

### ISSUE THREAD

**Issue by juangril** [dnschneid/crouton#2023]
Hi. Is there a way of doing this without having to start from scratch?

**Comment by DennisLfromGA** [comment]
Yup, just update your chroot adding the unity target at the same time, something like:

`sudo sh ~/Downloads/crouton -t unity -u`
                          or
`sudo sh ~/Downloads/crouton -t unity-desktop -u`

Then to start it, do:

`sudo startunity`

If you have more than one chroot you may need to add `-n chrootname` to the above commands substituting 'chrootname' with the name of your desired chroot.

**Comment by juangril** [comment]
Fantastic Dennis, that did the trick, thank you!

And if I want to remove XFCE, how do I do that?

Again, thanks for your help.

Juan

**Comment by DennisLfromGA** [comment]
> And if I want to remove XFCE, how do I do that?

That's a more difficult task to do, you may end up removing too much and causing problems with existing packages due to inter-dependencies, etc. I would recommend ignoring it just using 'startunity'.

**Comment by juangril** [comment]
Will do. Thanks again mate. Cheers,

Juan
