### ISSUE TITLE
Return of Xephyr

### ISSUE THREAD

**Issue by Firestarthirty** [dnschneid/crouton#2024]
I have a chromebook samsung 1 after crouton working working for I year I get an update on August 15th and suddenly Xephyr cannot open host display. Is DISPLAY set?
This has been fixed a few times but 
when I try to update (enter "sudo sh ~/Downloads/crouton -u -n chrootname") it says 
"sh: Can't open /home/chronos/user/Downloads/crouton" any clues?

**Comment by DennisLfromGA** [comment]
It looks like your local copy of '[crouton](https://goo.gl/fd3zc)' may have been removed.
You can download a fresh copy from here - https://goo.gl/fd3zc

Also, your Chromebook may be using 'freon' now, so a chroot update is probably necessary.

**Comment by Firestarthirty** [comment]
I have downloaded a new crouton also I've tried updatijgn but the sh is broken

**Comment by DennisLfromGA** [comment]
> I have downloaded a new crouton also I've tried updatijgn but the sh is broken

Can you show us what is displayed when you try to update your chroot?

NOTE: You should first login to your Google account and then get to a crosh shell using:
<kbd>Ctrl+Alt+t</kbd>
  and then entering: 
`shell`

**Comment by Firestarthirty** [comment]
sh: Can't open /home/chronos/user/Downloads/crouton (I know how to do it im not stupid)

**Comment by divx118** [comment]
@Firestarthirty Nobody is calling anybody stupid we are just trying to help and narrow down the problem which sometimes means giving obvious pointers just to be sure they can be excluded.
What is the output of `ls -al /home/chronos/user/Downloads/crouton` and what is the content of crouton `cat /home/chronos/user/Downloads/crouton` ?

**Comment by Firestarthirty** [comment]
ls: cannot access /home/chronos/user/Downloads/crouton: No such file or directory

**Comment by divx118** [comment]
@Firestarthirty Well then you need to download crouton again it isn't there, that is why sh fails. [crouton download](https://goo.gl/fd3zc) After that try again your update command `sudo sh ~/Downloads/crouton -u -n <chrootname>` \<chrootname\> is normally the same as the release you choose on install precise, trusty etc

**Comment by Firestarthirty** [comment]
sh: Can't open /home/chronos/user/Dowloads/crouton 
Its getting to the point where I'll just powerwash my chromebook and try resetting it

**Comment by divx118** [comment]
So is the file "crouton" in your Downloads folder now? You can see that by using the File manager and look at your Downloads folder, or with `ls -al /home/chronos/user/Downloads/crouton`
If you click [the link](https://goo.gl/fd3zc) I gave you above on your chromebook it should automatically start downloading "crouton" to your Downloads folder.

**Comment by Firestarthirty** [comment]
ls: cannot access /home/chronos/user/Downloads/crouton: No such file or directory 
(and yes crouton is in my Downloads folder)

**Comment by Firestarthirty** [comment]
I apologize it was on my thumb drive

**Comment by Firestarthirty** [comment]
-rw-r----- 1 chronos chronos 3653 Aug 22 19:51 /home/chronos/user/Downloads/crouton

**Comment by Firestarthirty** [comment]
Got it

**Comment by Firestarthirty** [comment]
G0d damn it should have looked at files more carefully sorry and thank you

**Comment by DennisLfromGA** [comment]
https://github.com/dnschneid/crouton/issues/2024#issuecomment-131554774 ;o)
