### ISSUE TITLE
Cannot open /dev/tty0

### ISSUE THREAD

**Issue by darwinv** [dnschneid/crouton#2025]
Hi

I have this error when i try to start my xubuntu with startxfce4
I have already try to update my crouton, on the process i got the same  error

 xf86OpenConsole: Cannot open /dev/tty0

How can I fix it? please help?﻿

**Comment by darwinv** [comment]
I Fix it!

**Comment by DennisLfromGA** [comment]
> I Fix it!

Cool, let us know how so we can all learn from it.
