### ISSUE TITLE
No screen found

### ISSUE THREAD

**Issue by jessietn** [dnschneid/crouton#2026]
Hello.

I'm a bit of a newbie trying to get this set up on my Asus C201P.  I get the usual No screen found error most of the time when I install.  I've had a few successes, mostly from about 4 or 5 days ago.  I finally got a working version of Trusty with LXDE installed.  However, I decided to try out other targets so I made more Chroots, and get these errors.  Including when I do another install of Trusty LXDE.  If I add xiwi, I seem to have no problems getting it to work, but would prefer not to run in a window if possible.  In order to get it to work, I have to use the workaround in issue [1938](https://github.com/dnschneid/crouton/issues/1938).  It seems if the install works, it always works, but if not, it never does except using xiwi.  Any ideas, I'm stumped?  I've included a version of croutonversion and the (hopefully) relevant portion of the X11 log.

Thank you very much for your time.

crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: armhf
xmethod: xiwi
targets: xiwi,kde
host: version 7077.123.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP Sat Aug 8 00:30:10 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes

 1210.236] Initializing built-in extension DRI2
[  1210.236] (II) LoadModule: "glx"
[  1210.238] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  1210.258] (II) Module glx: vendor="X.Org Foundation"
[  1210.258]    compiled for 1.15.1, module version = 1.0.0
[  1210.258]    ABI class: X.Org Server Extension, version 8.0
[  1210.258] (==) AIGLX enabled
[  1210.258] Loading extension GLX
[  1210.258] (==) Matched modesetting as autoconfigured driver 0
[  1210.258] (==) Matched fbdev as autoconfigured driver 1
[  1210.258] (==) Assigned the driver to the xf86ConfigLayout
[  1210.258] (II) LoadModule: "modesetting"
[  1210.258] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  1210.263] (II) Module modesetting: vendor="X.Org Foundation"
[  1210.263]    compiled for 1.15.0, module version = 0.8.1
[  1210.263]    Module class: X.Org Video Driver
[  1210.263]    ABI class: X.Org Video Driver, version 15.0
[  1210.263] (II) LoadModule: "fbdev"
[  1210.265] (WW) Warning, couldn't open module fbdev
[  1210.265] (II) UnloadModule: "fbdev"
[  1210.265] (II) Unloading fbdev
[  1210.265] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1210.265] (==) Matched modesetting as autoconfigured driver 0
[  1210.265] (==) Matched fbdev as autoconfigured driver 1
[  1210.265] (==) Assigned the driver to the xf86ConfigLayout
[  1210.265] (II) LoadModule: "modesetting"
[  1210.265] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  1210.265] (II) Module modesetting: vendor="X.Org Foundation"
[  1210.265]    compiled for 1.15.0, module version = 0.8.1
[  1210.265]    Module class: X.Org Video Driver
[  1210.265]    ABI class: X.Org Video Driver, version 15.0
[  1210.265] (II) UnloadModule: "modesetting"
[  1210.265] (II) Unloading modesetting
[  1210.265] (II) Failed to load module "modesetting" (already loaded, -1205305368)
[  1210.265] (II) LoadModule: "fbdev"
[  1210.266] (WW) Warning, couldn't open module fbdev
[  1210.266] (II) UnloadModule: "fbdev"
[  1210.266] (II) Unloading fbdev
[  1210.266] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1210.266] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  1210.266] (--) using VT number 7

[  1210.281] (EE) open /dev/dri/card1: No such file or directory
[  1210.282] (II) modesetting(G0): using drv /dev/dri/card0
[  1210.282] (WW) Falling back to old probe method for modesetting
[  1210.282] (EE) No devices detected.
[  1210.282] (EE) 
Fatal server error:
[  1210.282] (EE) no screens found(EE) 
[  1210.282] (EE)

**Comment by DennisLfromGA** [comment]
> I finally got a working version of Trusty with LXDE installed. However, I decided to try out other targets so I made more Chroots...

There's really no need to install a chroot for each desktop environment. You can add them to your working trusty/lxde chroot and save precious disk space. Just update your existing chroot and add the target(s) at the same time. I would just make a [backup](https://github.com/dnschneid/crouton#a-backup-a-day-keeps-the-price-gouging-data-restoration-services-away) of your chroot before adding any additional targets/Desktop Environments.

For 'kde', something like:

`sudo sh ~/Downloads/crouton -u -t kde [-n chrootname]`

Then, to start it use: `sudo startkde [-n chrootname]`

> If I add xiwi, I seem to have no problems getting it to work, but would prefer not to run in a window if possible.

'xiwi' does run in a window by default *but* you can run it in a tab '`-X xiwi-tab`' or full-screen '`-X xiwi-fullscreen`' if you like when starting it. Just add those '-X ...' options tou your start script, something like:

`sudo startkde -X xiwi-tab`

**Comment by jessietn** [comment]
Thanks DennisLfromGA, I didn't know about -tab.  That looks better, but would still prefer to have a full screen without the popup when working.  However this may be my goto for the the time being. (Yeah, I don't know why the window bothers me but tab doesn't as much.  I'm strange that way.)

What I'm actually hoping to do is to create another trusty from scratch since I've done so much messing around inside that one.  That's actually what started me trying to create another trusty chroot.  However, I can not seem to get another install of trusty or debian-jessie won't work except with xiwi.  However an install of precise/Lxde seems to run fine.  I think at this point I'm just intrigued why my install from last week works and any new ones won't.  The croutonversion outputs are identical for both.

**Comment by jessietn** [comment]
Interestingly enough, adding gnome to the working trusty/lxde not only resulting with a gnome installation that does not work, but also broke the working Lxde.  Both now produce the no screen error.

**Comment by 1rocketdude** [comment]
doesn't work for me. Get the loop of "Cannot connect to extension, retrying"
ever since the last ChromeOS update, no luck.

**Comment by jessietn** [comment]
I see some of those when on the ones with xiwi, but usually after a few it connects, or maybe a few retrys.  The No screens does not change no matter how many times i retry.

**Comment by jessietn** [comment]
Just an interesting observation.  Today I tried creating a LXDE/Trusty with lxde-desktop,xorg as the targets.  Low and behold, it works.  I thought great, whatever was wrong is fixed.  I decided to do it again to replicate it, same commands, and no joy.  I tried it 3 more times and none worked except the first.  The croutonversion output for the new working and non-working is the same.  I backed up both a working and a non working fresh install, so if anyone has any requests, I'm glad to dig into them or even provide them.

**Comment by 1rocketdude** [comment]
"consistent" with what I observed - basically each time I updated crouton
or ChromeOS, I got a different failure mechanism. When I went back to a May
2015 backup, it just worked. Happy again. The benefit of easy/fast chroot
clones.

**Comment by dnschneid** [comment]
Hopefully the situation will be improved by #2097

**Comment by jessietn** [comment]
I installed the dri branch indicated in [#2097](https://github.com/dnschneid/crouton/pull/2097) and created two new chroots.  One Jessie-KDE and one trusty-KDE.  Jessie required the card0/card1 swap to run, but trusty-KDE gave me the no screen error with and without the card swap.

**Comment by dnschneid** [comment]
Try the updated crouton and see if things are fixed now...

**Comment by dnschneid** [comment]
Oh wait, veryon devices don't seem to work with xorg on Jessie.  trusty, vivid, and wily are the only ones that work with that combo at the moment.

Could you post the output of /tmp/Xorg.crouton.1.log after it says "no screens found"?

**Comment by jessietn** [comment]
Hmm.  I've actually had success with jessie and stretch, even before the dri branch.  I'm doing a trusty install now and will report back after.

**Comment by jessietn** [comment]
It seems to be working great.  I've installed a trusty with kde, xfce and lxde and all work.  Also, I do not have to do the card swap game to get them working. 

Great Job.  Thanks.
