### ISSUE TITLE
issues switching from chrome os to linux

### ISSUE THREAD

**Issue by hackerDEpandas** [dnschneid/crouton#2027]
I put linux on my samsung chromebook a few years ago and everything has been working great! When my laptop dies I simply type, sudo startxfce4, and linux boots right up. However, recently I tried that and got this error, Xephyr cannot open host display. Is DISPLAY set? Not sure how to fix this. Any, and all help is much appreciated!

**Comment by 1rocketdude** [comment]
lots of similar episodes since the last ChromeOS update. I don't get the error you note, but I do get a blank screen. For an instance, I can see my desktop, but then nothing.

**Comment by DennisLfromGA** [comment]
You probably need to update your chroot(s); take a look at this similar issue https://github.com/dnschneid/crouton/issues/2024

**Comment by hackerDEpandas** [comment]
I'll admit my ignorance I'm not sure how to update my chroot. In the issue you reference I found that I could enter "sudo sh ~/Downloads/crouton -u -n chrootname" (my chrootname is precise). Is an update that would do the job? If so I tried it and got a different problem. Here are the screenshots of what I see when i try to boot linux using the command "sudo startxfce4".
![screenshot 2015-08-18 at 5 45 31 pm](https://cloud.githubusercontent.com/assets/6182680/9346401/1e942962-45d1-11e5-8bbe-590896ab5c17.png)
![screenshot 2015-08-18 at 5 46 03 pm](https://cloud.githubusercontent.com/assets/6182680/9346405/2a24d222-45d1-11e5-8f12-a0cae3b69e83.png)

**Comment by 1rocketdude** [comment]
We are in the same boat. I think I understand the word "update my chroot". I did exactly what you did, except I'm using trusty; e.g., sudo sh ~/Downloads/crouton -u -n trusty
.
.
... lots of compile and downloads later, everything completes as expected. But still no ability to sudo startlxde. Each time I update the chroot hoping a fix has arrived, I get a slightly different error, but still no x-win environment. I even added xiwi, but that also failed, with a different set of errors.
