### ISSUE TITLE
how to update my unity browser?

### ISSUE THREAD

**Issue by xxsoapxx** [dnschneid/crouton#2029]
im new to this and i just want to play a simple free to play game on my acer c720 i got into the install first as xcfe4, after countless hours of trying to get wine, i finally get it but the game will not run so i went and searched how to install unity without restarting from scratch, everything went smoothly but wine will not allow me to run the game... how can i upgrade unity as i am currently on ubuntu 12.04 lts,and my graphics driver says unknown

**Comment by tista500** [comment]
@xxsoapxx Unfortunately I can't find any crouton issues from your post and title as well...

If you had some issues of graphic driver (Haswell ?), let me see the final output:
```
sudo apt-get install mesa-utils
glxinfo | grep 'renderer string'
```
> my graphics driver says unknown

Although I'm not sure what is the reason you said and why you wanted to upgrade your unity desktop environment after encountering graphic driver warning with wine...

But anyway we need more "detailed" logs and system state.

Regards.

**Comment by xxsoapxx** [comment]
i read online that the new ubuntu has fixes is why i wanted to upgrade

**Comment by xxsoapxx** [comment]
how do i put more detailed information?

**Comment by xxsoapxx** [comment]
i wrote the code above, it says renderer string: Mesa DRI Intel(R) Haswell Mobile...

**Comment by tista500** [comment]
> renderer string: Mesa DRI Intel(R) Haswell Mobile

OK. OpenGL/Mesa driver was registered normal as we expected. Then let us see the error massage or log when you have failed to load such wine application. And the result of `croutonversion` inside the chroot, too.

> i read online that the new ubuntu has fixes is why i wanted to upgrade

Could you please post that URL here? Because today crouton has some issues on latest Ubuntu release, 15.04 (Vivid) especially Unity desktop.

Regards.

**Comment by xxsoapxx** [comment]
i do not get an error message, the game loads up with choppy graphics almost like a broken screen, but my screen is fine. the link i read was how to get the drivers but only on the newer ubuntu but u fixed that problem. now the game still gives me this weird graphical error as if the game isnt loading correctly. i have tried changing the wine configurations but still cannot get passed the login screen

**Comment by xxsoapxx** [comment]
if this helps the game i am trying to run is fallen-evolution the requirements page states this 
Image Minimum system requirements :
Operating Systems: Windows 98, ME, 2000, XP, Vista,Windows 7, Windows 8,Mac Using Wine, Linux using Wine.

Pentium 233 Mhz, 32 MB RAM
1 MB RAM video card
80 MB Hard drive or more
Direct x 7.0 or above
and an internet connection
Image Wine Configuration (For Mac & Linux users):

Open Wine Config-->Click "Drives" tab-->Click "C:"-->Then "Show Advanced"-->Change the "Label" to anything and change the "Serial" to anything other than "0".

i did this, and the game stays on a white screen. i am able to open the game using the wine c drive explorer and edit the game to remove almost ALL graphics (log in screen video skip, show shadows off, fullscreen off etc.) and i make it into the log in screen but the game doesnt register my keyboard, and it looks as if the screen (only new window that opens) is broken with weird colors and dead pixel lines and i cannot fix this

**Comment by tista500** [comment]
![screenshot from 2015-08-21 08-11-54](https://cloud.githubusercontent.com/assets/6073622/9397926/863581ee-47dc-11e5-9095-885053cf0388.png)

Is the game correct?
It seems to work at least on my Asus C200 (Don't forget I am quite not a gamer, and I don't know how to do next on this game at all...).  My chroot has a bit different packages compared with the native Vivid though... Basically DirectX 7.0 would work with OpenGL drivers which were included in Precise (But DirectX 9.0 needs more tweaks for Gallium-3D driver).

Newer wine seems to be placed in Wine-PPA: https://launchpad.net/~ubuntu-wine/+archive/ubuntu/ppa?field.series_filter=precise. Then you'd better to give a try the version 1.7 first on Precise. 

If you need the high performance OpenGL graphic driver, do not use X-edgers, but Oibaf's PPA: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers. Today he only supports both Trusty and Vivid, so  upgrading Precise to Trusty 14.04 LTS would be the 2nd choice...

Regards.

**Comment by xxsoapxx** [comment]
how do i upgrade any of this?

**Comment by xxsoapxx** [comment]
![screenshot - 082215 - 14-46-58](https://cloud.githubusercontent.com/assets/13844553/9425410/72fc4c8c-48dd-11e5-8f56-e8ea12df793e.png)

**Comment by xxsoapxx** [comment]
ok after a few google searches i find this https://www.digitalocean.com/community/tutorials/how-to-upgrade-ubuntu-12-04-lts-to-ubuntu-14-04-lts

im currently running everything now to upgrade

**Comment by xxsoapxx** [comment]
i do not know how do add these PPA to my apt-get i didnt realize i could update wine before updating my system.... oh well ill be on 14.04 lts soon so ill just move on

**Comment by xxsoapxx** [comment]
and i broke it...

**Comment by xxsoapxx** [comment]
https://github.com/dnschneid/crouton/issues/1706 fixed it using this replaced vivid with trusty

**Comment by xxsoapxx** [comment]
no go restarted everything still wont load into trusty

**Comment by xxsoapxx** [comment]
idk how i did it but i got it to load...

**Comment by xxsoapxx** [comment]
i cannot seem to update to the new wine

**Comment by xxsoapxx** [comment]
i got it thank you :D

**Comment by tista500** [comment]
Sorry for my delayed response...

Sounds you could run that game on Trusty. Then if you had other issues, please post it as new another topic.

Finally I'm glad and hope you could close this issue (Because developers have to watch a lot of "opened" isses every day). :-)

Regards.

**Comment by xxsoapxx** [comment]
i cannot load the game now it says cannot connect to an extension retrying.....after 10 of those messages still nothing

**Comment by xxsoapxx** [comment]
i cannot load the game now it says cannot connect to an extension retrying.....after 10 of those messages still nothing

**Comment by tista500** [comment]
In my imagination, you would login into chroot via: `sudo startunity` on crosh window, and it would load **Xiwi** XMethod to run chroot desktop. SInce `cannot connect to an extension retrying` could be shown in crosh window only for Xiwi instead of X11/freon.

So you need to login into chroot via cli: `sudo enter-chroot`, and then let me see the output of this command: 
```
croutonversion
```

Regards.
