### ISSUE TITLE
Update Kali Crouton

### ISSUE THREAD

**Issue by frafrichile** [dnschneid/crouton#2030]
Hi
I recently got back to my chromebook and notice I still have Kali
I was wondering what command do I need to run to update it 

Also , dmesg shows my wireless cards but it won't recognize them under
airmon-ng 
they show up in lsusb

what am I missing here? 

THanks !

**Comment by NoPinky** [comment]
drivers are not included in the kernel I guess. I've been trying and looking for a way to use external usb-wifi-dongles to do wifi shinanigans for almost a year now... no luck yet.

**Comment by frafrichile** [comment]
How can we install the firmware ? I believe from what I read that the drivers or firmware are missing.

**Comment by divx118** [comment]
@frafrichile https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules
