### ISSUE TITLE
External USB drive is READ ONLY in Crouton (Trusty)

### ISSUE THREAD

**Issue by Turntaker** [dnschneid/crouton#2031]
I don't know what happened but I had steam games on my USB and I was using it fine.
Today I couldn't update my game and Steam showed a disk error.
I realised that the USB was read only.

What can I do to make it work?

**Comment by jessietn** [comment]
Do you use the USB on another computer?  I've seen this error before when I didn't do a clean eject.  Usually it fixes itself if I reinsert it in the other computer and do a clean eject.

**Comment by Turntaker** [comment]
Yes I used it on another linux machine and sometimes windows. It is formatted as FAT

**Comment by jessietn** [comment]
You could perhaps try 
sudo fdisk -l 
to get the device name for the drive, then
sudo dosfsck -v /dev/xxx
to see if there are any errors detected.  If so, you could rerun it with -a added.

**Comment by Turntaker** [comment]
It is working now

**Comment by jessietn** [comment]
Great.
