### ISSUE TITLE
The Shift+2 is not @ instead its "

### ISSUE THREAD

**Issue by BottleSpeaker** [dnschneid/crouton#2032]
and Shift + ' does not give " instead it gives @.

What is the cause of this.
btw this occurs only in chromeos not the chroot.

**Comment by jessietn** [comment]
Check to make sure your keyboard input is set to English.  Go to settings, Keyboard settings, change language and input settings and make sure english (USA) is set and that english keyboard is selected on the right.  It sounds like its in a UK setting.

**Comment by drinkcat** [comment]
> btw this occurs only in chromeos

So this is a Chrome OS issue, not crouton? Right?
