### ISSUE TITLE
I reset my Chromebook, and i mapped my chroot to usb, but i dont know how to get chroot commands back on my chromebook without deleting my chroot?

### ISSUE THREAD

**Issue by TyJoKo** [dnschneid/crouton#2033]
I was formatting an SD Card and i entered the wrong location and it wiped a system partition, and it reset itself. is there a way i can get crouton commands back without deleting my current chroot?

**Comment by jessietn** [comment]
You could do a quick install of a new chroot.  That should recreate the bin directory.  Then you can delete the new sacrificial chroot with

`sudo delete-chroot name`

The bin directory will remain.

**Comment by TyJoKo** [comment]
awesome. thankyou very much

**Comment by DennisLfromGA** [comment]
Also, 'crouton' has an option to restore the '`bin`' files -
> -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.

**Comment by jessietn** [comment]
@DennisLfromGA thank you.
