### ISSUE TITLE
Sudo startxfce4 is not working please have quick reply school starts tomorrow for me

### ISSUE THREAD

**Issue by joeman720** [dnschneid/crouton#2034]
Every time I do sudo startxfce4 this comes up
![screenshot 2015-08-19 at 1 06 05 pm](https://cloud.githubusercontent.com/assets/13873303/9363237/3a33513c-4673-11e5-942e-8891dab4d9e6.png)
![screenshot 2015-08-19 at 1 06 18 pm](https://cloud.githubusercontent.com/assets/13873303/9363242/4260b304-4673-11e5-80b8-f0a3487f2314.png)
![screenshot 2015-08-19 at 1 06 26 pm](https://cloud.githubusercontent.com/assets/13873303/9363245/464d754c-4673-11e5-9fa2-015fd1c01e6f.png)

I have looked at others comments with my problem to try to fix my problem but it does not work. I tried commands and not a single one works except the one that where already in the orginal crosh.

**Comment by joeman720** [comment]
i have reset everything and did everything over again and it doesn't work

**Comment by jessietn** [comment]
Can you give us the output of crouton version?
`sudo enter-chroot -n precise`
`croutonversion`

**Comment by joeman720** [comment]
chronos@localhost / $ sudo enter-chroot -n precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)josef@localhost:~$ croutonversion
crouton: version 1-20150811114815~master:f6b810fe
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 7077.134.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:10:15 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes

**Comment by joeman720** [comment]
it worked somehow

**Comment by jessietn** [comment]
Ok, try this.  
If you have not already, type exit and hit enter.  Then enter:
`sudo rm /dev/dri/card0`
`sudo mv /dev/dri/card1 /dev/dri/card0`
Then try starting the chroot.
`sudo startxfce4`

**Comment by joeman720** [comment]
It works! Why wasn't it working before I put the commands?

**Comment by jessietn** [comment]
Not entirely sure myself.  I've only been fooling with this for a week or so myself.  But it seems that arm processors (rockchip for sure) have to have this set of code run before it will start.  You will have to enter those two commands every time the laptop reboots.  But be careful only to run it one time per boot or you will have to reboot to reset it.  What I did was create a file in my user directory called card and put those two commands in it.  Then, when I reboot, I just type

`sh card` 

then you can run  sudo startxfce4 after.

**Comment by hackerDEpandas** [comment]
I have a similar issue but different error message! I tried the commands you gave and that didn't work. here is what I see when I give the command sudo startxfce4
![screenshot 2015-08-18 at 5 45 31 pm](https://cloud.githubusercontent.com/assets/6182680/9388218/f808732c-4718-11e5-9fb0-feaf37e623f6.png)
![screenshot 2015-08-18 at 5 46 03 pm](https://cloud.githubusercontent.com/assets/6182680/9388220/fc4cb060-4718-11e5-8782-f7e5a9a0d435.png)

**Comment by hackerDEpandas** [comment]
I have a similar issue but different error message! I tried the commands you gave and that didn't work. Here is what I see when I give the command sudo startxfce4 
![screenshot 2015-08-20 at 8 54 55 am](https://cloud.githubusercontent.com/assets/6182680/9388272/4d39a410-4719-11e5-8be9-e8f8307afaae.png)
![screenshot 2015-08-20 at 8 55 08 am](https://cloud.githubusercontent.com/assets/6182680/9388290/537b6f66-4719-11e5-8c50-11b7ab3558f6.png)

**Comment by jessietn** [comment]
You may be in the same boat as me then.  You could add xiwi to your chroot and run it in a window.  It's what I have to do for now.

'sudo sh ~/Downloads/crouton -u -n precise -t xiwi'

You may want to back it up before you do this just in case.
Lxde works under precise for me without xiwi, but xfce on mine needs xiwi to run.
Sorry, that's the best I've got.

**Comment by hackerDEpandas** [comment]
I appreciate the effort! I'll give it a try. Thanks!

**Comment by jessietn** [comment]
No problem, let me know how it turns out.

**Comment by rhettprestwich** [comment]
@jessietn  You're the best. Thanks!

**Comment by EPicnesss** [comment]
i also need some help. when i type in sudo startxfce, it says rhat there is a an error and unable to connect of x server (im on chromebook 3)
![screenshot 2018-02-19 at 1 07 18 pm](https://user-images.githubusercontent.com/36642330/36391761-f181424e-1575-11e8-9c37-3eb0348245da.png)
