### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by thatoneguy64** [dnschneid/crouton#2035]
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:10:32 PDT 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72/PARTNROFF=1 hashtree=PARTUUID=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=7d16dfd6647864317c84b64ffd092069c8507f65 salt=f5db6aaf07f8653cd319eee1dd47e2f34be8a2272c27cd8823d15901f314c15c" noinitrd vt.global_cursor_default=0 kern_guid=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Aug 19 22:48:35 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

someone please tell me what went wrong lol

**Comment by jessietn** [comment]
Can you give us the output of crouton version?
`sudo enter-chroot -n precise`
`croutonversion`

Also, have you ever been able to see the gui on this chroot or is this right after an install?

**Comment by thatoneguy64** [comment]
right after install:

chronos@localhost / $ sudo enter-chroot precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
-su: 1: precise: not found
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by thatoneguy64** [comment]
chronos@localhost / $ sudo enter-chroot -n precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)welch@localhost:~$ croutonversion
crouton: version 1-20150811114815~master:f6b810fe
release: precise
architecture: armhf
xmethod: xorg
targets: unity
host: version 7077.134.0 (Official Build) stable-channel veyron_jerry 
kernel: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:10:32 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
(precise)welch@localhost:~$

**Comment by thatoneguy64** [comment]
there ya go

**Comment by jessietn** [comment]
Ok, try this.  I'm not as confident about this but it should be worth trying.  

If you have not already, type exit and hit enter. Then enter:

`sudo rm /dev/dri/card0`
`sudo mv /dev/dri/card1 /dev/dri/card0`

Then try starting the chroot.

`sudo startunity`

If this works, you will have to run those top two commands every time you reboot the system.  Rebooting sets card0 and card1 to the default settings.

**Comment by thatoneguy64** [comment]
alright thanks a bunch
just saved me a lot of time haha
also, what is the issue i keep having with updating unbuntu?

**Comment by thatoneguy64** [comment]
like it,ll do the exact same fatal error message

**Comment by jessietn** [comment]
I'm  not sure.  I have a similar problem when I try to use the trusty version of Unbuntu.  I have a working older copy but any new chroots don't work, they give that error even if I do the card change.  For now, I can get a trusty version working if I add xiwi to the target during the install.  I have my own issue down below about this and I'm just trying to help out here while waiting on a response.

**Comment by thatoneguy64** [comment]
thanks it really did help a lot

**Comment by jessietn** [comment]
No problem.  I spent a good chunk of time figuring that out.  Glad to help save you that time.

**Comment by thatoneguy64** [comment]
wish i could help out, but i am really new to this, and only understand a small portion of it

**Comment by jessietn** [comment]
Same, but you got to start somewhere.

**Comment by thatoneguy64** [comment]
yeah

**Comment by thatoneguy64** [comment]
like i don't even know what changing the cards did haha

**Comment by jessietn** [comment]
To tell you the truth, I'm not 100%.  Here is what I "think" is happening.  They seem to be files that let the kernel talk to the video drivers.  Apparently when starting, something is causing it to choose the wrong one.  

Check out  [this link](http://www.moi.vonos.net/linux/drm-and-kms/) for more info.

**Comment by thatoneguy64** [comment]
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Creating hwaudio group with GID 18...
Changing cdrom GID from 24 to 19...
Changing floppy GID from 25 to 11...
Changing plugdev GID from 46 to 85...
Changing uucp GID from 10 to 14...
Changing video GID from 44 to 27...
Moving sudo GID from 27 to 28...


X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:10:32 PDT 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72/PARTNROFF=1 hashtree=PARTUUID=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=7d16dfd6647864317c84b64ffd092069c8507f65 salt=f5db6aaf07f8653cd319eee1dd47e2f34be8a2272c27cd8823d15901f314c15c" noinitrd vt.global_cursor_default=0 kern_guid=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Aug 20 12:12:16 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed
crouton: version 1-20150811114815~master:f6b810fe
release: precise
architecture: armhf
xmethod: xorg
targets: unity
host: version 7077.134.0 (Official Build) stable-channel veyron_jerry 
kernel: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:10:32 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by jessietn** [comment]
@thatoneguy64 I think you are in the same boat as me.  I have to use xiwi in order to load in a window.
Load into your shell window and enter

`sudo sh ~/Downloads/crouton -u -t xiwi -n precise`

After all that finishes, try running your `sudo startunity`

Also, make sure you have the crouton extension installed on the chromebook side, just search for crouton in the web store.

**Comment by thatoneguy64** [comment]
nothing for crouton shows up on the web store

**Comment by jessietn** [comment]
Ok.  Use this [link](https://goo.gl/OVQOEt) for it then.

**Comment by divx118** [comment]
@thatoneguy64 crouton extension is hidden from search on the web store, so people don't think they can install crouton with installing the extension. You can find the extension on https://goo.gl/OVQOEt link should also be presented to you when finishing updating with xiwi or can be found in the [README.md](https://github.com/dnschneid/crouton/blob/master/README.md)

**Comment by jessietn** [comment]
@divx118 Thanks.  I didn't know it was hidden.

**Comment by thatoneguy64** [comment]
thanks guys

**Comment by thatoneguy64** [comment]
another question: what does it mean when it says
mv: cannot stat ‘/dev/dri/card1’: No such file or directory

**Comment by jessietn** [comment]
You only need to do the rm and mv commands  when you reboot the chromebook.
