### ISSUE TITLE
Unable to run arch after fresh install. Issues with hanging processes and attempting to update crouton

### ISSUE THREAD

**Issue by ddrizn** [dnschneid/crouton#2037]
After doing a fresh install attempting to start xfce4 give me the following error:

sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/arch...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.17.2
Release Date: 2015-06-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.10.69-1-ARCH armv7l 
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Aug 11 21:43:14 PDT 2015 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=794bc942-6ff1-964b-b90f-aae8215c4934/PARTNROFF=1 hashtree=PARTUUID=794bc942-6ff1-964b-b90f-aae8215c4934/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=01e252d7fb202333917fd31d4b4470d4511eb840 salt=4641d1e7349200d56c1c9d07c80436e29af3c9c4cf5d80502ed2b50c38b70b37" noinitrd vt.global_cursor_default=0 kern_guid=794bc942-6ff1-964b-b90f-aae8215c4934  
Build Date: 17 July 2015  12:23:38PM
 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Aug 22 07:44:30 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

If I attempt to unmount the chroot I get the following error:

chronos@localhost / $ sudo unmount-chroot arch
Not unmounting /mnt/stateful_partition/crouton/chroots/arch as another instance is using it.

I then have to  run:
chronos@localhost / $ sudo unmount-chroot -p arch
 2119 dbus-daemon --system --fork
Not unmounting /mnt/stateful_partition/crouton/chroots/arch as another instance is using it
I then have to kill the offending process in order to unmount the chroot.

Attempting to update after fetching a fresh version of crouton yields:
chronos@localhost / $ sudo sh ~/Downloads/crouton -n arch -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/arch already exists; updating it...
Unable to determine the release in /usr/local/chroots/arch. Please specify it with -r.

Specifying the release gives me:
chronos@localhost / $ sudo sh ~/Downloads/crouton -n arch -u -r arch
arch does not belong to any supported distribution.

My croutonversion is:
[bruce@localhost ~]$ croutonversion
crouton: version git
release: arch
architecture: armv7h
xmethod: xiwi
targets: xfce
host: version 7262.33.0 (Official Build) beta-channel daisy

**Comment by jessietn** [comment]
You said it was a fresh install.  Have you made sure you installed the chrome side extension from [http://goo.gl/OVQOEt](http://goo.gl/OVQOEt)?

**Comment by ddrizn** [comment]
Installing the extension allows me to run xfce but it complains that it is
a outdated server version VF2 when it should be VF3 and suggests that I
update the chroot. When I try to update the chroot with a newly downloaded
installer I still get the following error:

chronos@localhost / $ sudo sh ~/Downloads/crouton -n arch -u
/usr/local/chroots/arch already exists; updating it...
Unable to determine the release in /usr/local/chroots/arch. Please specify
it with -r.
gpg-agent[31854]: SIGTERM received - shutting down ...
gpg-agent[31854]: gpg-agent (GnuPG) 2.1.7 stopped

On Sat, Aug 22, 2015 at 9:28 AM, jessietn <notifications@github.com> wrote:

> You said it was a fresh install. Have you made sure you installed the
> chrome side extension from http://goo.gl/OVQOEt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/2037#issuecomment-133598308>.
>



-- 
Bruce Reed

**Comment by jessietn** [comment]
When I run 
`sudo sh ~/Downloads/crouton -r help`
I don't see arch being an recognized release.  Maybe it's not supported anymore?

**Comment by BooDoo** [comment]
afaik Arch has never(?) been supported in crouton proper, but drinkcat/chroagh fork added support. 

That hasn't been updated in a while but I recently published a branch merging chroagh with modern crouton and it works for arch on my Samsung Chromebook 2 at least. YMMV.

to update your `arch` chroot from ChromeOS `shell` prompt:
```
curl https://codeload.github.com/BooDoo/chroagh/tar.gz/arch-chromebook2 | tar xz  
cd chroagh-arch-chromebook2/installer  
sudo sh main.sh -r arch -n arch -u
```

**Comment by ddrizn** [comment]
That helped some. It got about halfway through the update process and
errors out at
error: target not found: xserver-xorg-video-modesetting
but at least now it exits cleanly, and with the crouton extension in chrome
I can run it so it's better than it was. Modifying the main.sh script might
fix it but I have no idea what changes would need to be made.
Thank you,

On Tue, Aug 25, 2015 at 6:24 AM, Joel McCoy <notifications@github.com>
wrote:

> afaik Arch has never(?) been supported in crouton proper, but
> drinkcat/chroagh fork added support.
>
> That hasn't been updated in a while but I recently published a branch
> merging chroagh with modern crouton and it works for arch on my Samsung
> Chromebook 2 at least. YMMV.
>
> to update your arch chroot from ChromeOS shell prompt:
>
> curl https://codeload.github.com/BooDoo/chroagh/tar.gz/arch-chromebook2 | tar xz
> cd chroagh-arch-chromebook2/installer
> sudo sh main.sh -r arch -n arch -u
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/2037#issuecomment-134384800>.
>



-- 
Bruce Reed

**Comment by BooDoo** [comment]
I believe that's specific to Intel-based devices (which I'm not using this fork on) but you'll probably want to look at [Intel Graphics \[ArchWiki\]](https://wiki.archlinux.org/index.php/Intel_graphics) and check `targets/xorg` to adjust the logic re: graphics drivers for your use.

**Comment by dnschneid** [comment]
This should probably be tracked on drinkcat's chroagh issue tracker, or in the merge request: #1201 .
