### ISSUE TITLE
Minimising Developer Install

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#2040]
Unfortunately I wasn't able to source my dream machine of a Toshiba Chromebook 2 with IPS and 32 GB. I ended up with 16GB, and because of the apps I have to run, I'm permanently flirting with my disk filling up completely when running Crouton. I've run Bleachbit, uninstalled everything I can and moved everything I can data-wise off onto the SD card.

Can anyone suggest a way to minimise the disk usage of the Chrome OS portion of the machine, (e.g. are there any subsets of the developer mode functionality that I can afford to uninstall and how would I do that). I've emptied the browser cache and have very few apps installed on it already. 

Offline docs don't seem to be possible to remove. It simply tells me it's syncing the Offline status when I visit Google Drive and no controls ever appear for me to turn it off.

Any other thoughts for how to prevent my machine from running out of space?

**Comment by cefn** [comment]
Perhaps the obvious is to delete the Chrome OS user account from the machine altogether. However, how do I recover access to my Chroot after doing so? Is it reliable?

**Comment by cefn** [comment]
I ran...

    find /home/user/fe50d01e4e7507c7766dd826995f963683258da5/ -maxdepth 1 -mindepth 1 -print0 | xargs -0 -n1 sudo du -s | sort -n

Which produced the following, suggesting I might be able to shave off some usage by minimising extensions, assuming they are not fundamental...

```
4       /home/user/fe50d01e4e7507c7766dd826995f963683258da5/crash
4       /home/user/fe50d01e4e7507c7766dd826995f963683258da5/databases-incognito
4       /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Feedback Reports
4       /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.ssh
8       /home/user/fe50d01e4e7507c7766dd826995f963683258da5/RLZ Data.lock
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/App Launcher Search
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.bash_logout
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.bash_profile
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.bashrc
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.crosh_history
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/login-times
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/logout-times
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/README
12      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/RLZ Data
16      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.bash_history
16      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Extension Cookies-journal
16      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/WebRTCIdentityStore-journal
20      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.com.google.Chrome.Gzdje2
20      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Extension Cookies
20      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/QuotaManager-journal
20      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/TransportSecurity
20      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/WebRTCIdentityStore
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Favicons-journal
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/History-journal
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Login Data-journal
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Origin Bound Certs-journal
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/QuotaManager
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Shortcuts-journal
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Top Sites-journal
24      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Web Data-journal
28      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.config
28      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Cookies-journal
28      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Network Action Predictor-journal
52      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Login Data
52      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Shortcuts
56      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Platform Notifications
64      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Origin Bound Certs
64      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/.pki
72      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Extension Rules
80      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/History Provider Cache
80      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Sync Extension Settings
88      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/cmt
96      /home/user/fe50d01e4e7507c7766dd826995f963683258da5/databases
132     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Bookmarks
132     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Bookmarks.bak
132     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Webservice Search Cache
136     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/GCM Store
136     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Visited Links
148     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Web Data
200     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Certificate Revocation Lists
244     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Preferences
244     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Sync App Settings
244     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Top Sites
288     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Network Action Predictor
348     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Current Tabs
500     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Current Session
504     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Last Tabs
592     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/GPUCache
668     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/ev_hashes_whitelist.bin
740     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Sync Data
780     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Last Session
816     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Favicons
988     /home/user/fe50d01e4e7507c7766dd826995f963683258da5/History
1124    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Local App Settings
1148    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Cookies
1416    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/GCache
2180    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/log
2208    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/File System
3624    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Extension State
5004    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Local Extension Settings
5260    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Session Storage
6064    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Application Cache
6740    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Pepper Data
7284    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Service Worker
8936    /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Downloads
23140   /home/user/fe50d01e4e7507c7766dd826995f963683258da5/IndexedDB
26536   /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Local Storage
40152   /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Storage
49776   /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Media Cache
115296  /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Cache
717500  /home/user/fe50d01e4e7507c7766dd826995f963683258da5/Extensions
```

**Comment by cefn** [comment]
I have found that there's something going on during uptime which causes the disk to fill. This explains why I am always at the point of running out of space. Diagnosing now. 

When I reboot I have nearly 2Gb free and after running for a day or so I have 200Mb free and applications starting to throw errors, but I have not explicitly stored that amount of data during uptime, so it must be some kind of cache or log causing the system to fill.

**Comment by dnschneid** [comment]
I think you can go into settings on drive.google.com and disable offline syncing.  What targets did you use when you installed crouton?

**Comment by tcagle** [comment]
+cefn I suggest you install lsof utility and see if you can locate the open files that are being written and filling the available file space.

**Comment by cefn** [comment]
A weird and amazing datapoint on the problem. 

Since my original post I have powerwashed the Chromebook which got me back to something like 2GB free space (after Crouton was restored). 

After a few days of working since the powerwash my drive was basically full (100 Meg left). I tidied up a few things and reclaimed space until there was 300 Meg free then rebooted.

Note that Crouton is not running again at all, at this point. I checked the filesystem availability and at that moment another 300Meg had become available since the reboot. Then I checked it again immediately to see if the amount of free space was steadily decreasing (I was expecting to be able to observe the shrinking space), AND THEN...!. 

Amazingly between the first and the second request (about 10 seconds apart), some kind of background process in ChromeOS had just freed 1.2 Gig!

chronos@localhost / $ df -h /home/
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   11G  9.2G  605M  94% /home
chronos@localhost / $ df -h /home/
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   11G  8.0G  1.8G  83% /home
chronos@localhost / $

I have so far struggled to find the right invocation for getting a full snapshot of filesystem usage (so that I could diff it against a later snapshot). Any ideas how I should do this. 

@tcagle LSOF gives me way too much information to be able to follow it.

@dnschneid there's a bug in Google, which means that the status indicator (and controls) for Google Drive never actually appear. A progress indicator is there, claiming... "Checking Offline Sync Status, Please Wait". I've been waiting about 6 months. Perhaps it's long enough :) 

Will I get weirdness from running crouton from a guest account, is it even feasible? Could be a useful thing to try next.

**Comment by cefn** [comment]
It's now about 15 minutes later. I still haven't launched Crouton. The only activities I have completed are visiting this page, and visiting http://drive.google.com to write down the error message. In that time I have just lost 0.6 GB of storage...

```bash
chronos@localhost / $ df -h /home/
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   11G  8.6G  1.2G  89% /home 
```

**Comment by drinkcat** [comment]
> Will I get weirdness from running crouton from a guest account, is it even feasible? Could be a useful thing to try next.

Guest account is a good thing to try, yes.

Can you also run your `du` command on subdirectories of `/mnt/stateful_partition`? (/home and /mnt/stateful_partition are the same physical partition)

**Comment by cefn** [comment]
Guest account didn't seem to mitigate the problem. Half a meg still disappeared somewhere. 

Incidentally I did notice with Shift+Escape in ChromeOS that there was a process describing itself as something like "Background Page Google Now" which was using 100% CPU. I don't have any Google Now extensions installed, at least not deliberately.

**Comment by cefn** [comment]
Another data point - after my regular reboot to free space, I found that the ChromeOS space-freeing didn't take place until the moment the network came up. Here's the reports before and after network loading (and haven't run Crouton at all at this stage).

```bash
chronos@localhost / $ df -h /mnt/stateful_partition/
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   11G  9.1G  661M  94% /mnt/stateful_partition
chronos@localhost / $ df -h /mnt/stateful_partition/
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   11G  8.5G  1.3G  88% /mnt/stateful_partition
```

It's possible I can therefore withhold the network next time, run a scan with a console-comand in crosh=>shell and then connect the network and run the scan again, to see what changes are made.

Any idea what the scan should be, in order to get a decent (diffable) summary of the filesystem under /mnt/stateful_partition for diagnosis?
