### ISSUE TITLE
unmount chroot help needed

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#2041]
I often get the error `Not unmounting /mnt/stateful_partition/crouton/chroots/mychroot as another instance is using it` when I somehow leave something running in the background.  I need to unmount because I have an app that will sometimes refuse to start until I unmount and remount.

When I do `umount /mnt/stateful_partition/crouton/chroots/mychroot` i get the message `umount: /mnt/stateful_partition/crouton/chroots/mychroot: not mounted`.  The two errors are contradictory.  One says it is mounted and the other says it isn't.  Could the path in the first message be wrong?

Can someone tell the right way to unmount a chroot?

**Edit:** I just realized that a good way to solve this is to find what process is causing the problem and killing it.  Any hints on how to do this?

**Comment by tedm** [comment]
@mark-hahn you want to use unmount-chroot, umount is for unmounting standard linux /dev devices, see this thread:

https://github.com/dnschneid/crouton/issues/117

**Comment by mark-hahn** [comment]
Thanks ...
