### ISSUE TITLE
Trackpad stops working

### ISSUE THREAD

**Issue by Dimikosta** [dnschneid/crouton#2042]
On my Toshiba Chromebook 2 halfway through an install of a Chroot, the trackpad stops working. The installation continues and the keyboard still works however, and a USB mouse can be used. The trackpad works again after rebooting though, what is causing this?

**Comment by tista500** [comment]
@Dimikosta, The issue should be marked as duplicated of this: #1994 

Yep, the latest crouton version might happen this issue on fresh install. 

Regards.

P.S. @dnschneid, Was there anything wrong in latest codes caused udev dead-lock?
