### ISSUE TITLE
Possible to backup chroot without sudo?

### ISSUE THREAD

**Issue by usfbrian** [dnschneid/crouton#2044]
I lost my boot kernel after lending my Chromebook (space at boot screen), but because there was an SD card in, the OS didn't completely powerwash. SOMEHOW (possibly Esc+Refresh+Power, then Ctrl+D or Ctrl+L or some series of keypresses) the system eventually loaded into ChromeOS OOBE without the powerwash. It seemed to delete or overwrote each user's Downloads folder, but I used my wife's account to log in, "just in case." (There's also a dialog to type the OLD ChromeOS password, and I tried this, but it didn't work.)

I can access a terminal, but my sudo password doesn't work anymore.

Fortunately, /mnt/stateful_partition/crouton still exists and has all my data!! (Additionally, the backups/ folder exists with 3 "kernel_A" and 3 "kernel_B" .bin files, there are dev_image/, encrypted/, and a half dozen other folders.)

I'm not sure if I could simply copy the contents of stateful_partition to an external drive, powerwash, set my chronos password, and copy from external back into stateful_partition, and I'm reluctant to try. Worst case scenario, I can copy over all of the configuration files (vimrc, git, zsh, etc) I'm just elated that my random, blank SD card saved me from total disaster.

**Comment by DennisLfromGA** [comment]
> I can access a terminal, but my sudo password doesn't work anymore.

Do you mean you can access a terminal in crosh or in your chroot?
If you mean in the chroot, that's an easy fix once you've got everything else working again.
Just get into the chroot as root and then change the password for your username:

`sudo enter-chroot -n precise -u root`
`passwd [username]` (enter the password twice, it won't be displayed in the terminal)
`exit`

> Fortunately, /mnt/stateful_partition/crouton still exists and has all my data!!

If that's the case, you could re-download [crouton](https://goo.gl/fd3zc) and you might be able to restore the scripts in `/usr/local/bin/` and then backup your chroot(s) with:

 `sudo edit-chroot -b -f /path/to/external/media [-c /mnt/stateful_partition/crouton/chroots/]`

If that doesn't work, you may just be able to '`tar`' it yourself placing the backup on external media.

Hope this helps,
-DennisL

**Comment by usfbrian** [comment]
Nope, my crosh password doesn't work. No sudo at all...

**Comment by usfbrian** [comment]
Also, no chromeos-setpasswd either in the developer terminal. Sadly, I
think a powerwash is required but I really hope I can drop my old chroot
into the fresh install and it just works like before, sans the few bashed
aliases I had in crosh. I'll let you all know how it goes!

**Comment by DennisLfromGA** [comment]
> Nope, my crosh password doesn't work. No sudo at all...

But you can still get to a terminal session as user 'chronos'?
That's a little strange it seems to me. If you can somehow delete '`/mnt/stateful_partition/etc/devmode.passwd`', then you should be able to get to both 'chronos' and 'root' without a password.

**Comment by usfbrian** [comment]
I can ctrl+alt+t and type shell, but if I sudo anything, it asks for
password and doesn't accept anything I've tried. So I can't even enter
chroot.

**Comment by usfbrian** [comment]
Pulled the trigger today. I forgot all about Ctrl+Alt+Shift+R, that would've been the way to reset my password without potentially clearing the /mnt/stateful_partition folder. Instead, I did the full Protected Mode --> Dev Mode --> Powerwash --> Reset.

I backed up what was readable by chronos in my /mnt/stateful_partition/crouton and /mnt/stateful_partition/dev_image folders. Trying to load a fresh install of crouton with the same targets, then copy the contents of the backup directly into stateful_partition. I'm worried there will be permission issues, but I'll update everyone with the results.

Thankfully, I still have config files for vim, zsh, git, and a handful of other programs, and I didn't have too many programs outside of the official repositories. I'll be keeping an SD card in the slot permanently from now on (until I learn how to custom kernel around the scary message).

**Comment by DennisLfromGA** [comment]
I don't know what kind of Chromebook you have but I've got one with SeaBIOS and have the 'legacy boot' option enabled which allows me to boot other OSes externally and gain access to `/dev/sda1` and others. I have done this on occasion to circumvent disasters in the past.

**Comment by usfbrian** [comment]
Asus C300

**Comment by DennisLfromGA** [comment]
> Asus C300

The developer site doesn't have any links to it - http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices ???

Does it do 'legacy boot' ?

**Comment by DennisLfromGA** [comment]
I just read that the ASUS C300 and other baytrail processors do not have legacy boot - bummer...

**Comment by usfbrian** [comment]
![screenshot 2015-08-30 at 10 30 54 pm](https://cloud.githubusercontent.com/assets/4408242/9571134/dc99b636-4f66-11e5-854c-b99eb640f78e.png)

It even kept my old Github token, rc files, octave installation, ... seemingly everything.

It seems---for now---to be a successful recovery from the recovery process.
