### ISSUE TITLE
Update XBMC to Kodi

### ISSUE THREAD

**Issue by MarhyCZ** [dnschneid/crouton#2046]
Hi, 
Would it be possible to update XBMC target to a new version that supports Kodi?

**Comment by DennisLfromGA** [comment]
Not really a crouton question but -
here's one link explaining *[How to upgrade XBMC to Kodi Media Center?](http://www.htpcbeginner.com/upgrade-xbmc-to-kodi-media-center/)*
You can just google it if you need more info.

**Comment by MarhyCZ** [comment]
No, I know how to update software, but they renamed the app, so when I issue a crouton -t xbmc install script, it will install some old version of xbmc, instead of a new kodi.

**Comment by DennisLfromGA** [comment]
Sorry, I misread your question.
I'm not sure about that but I'll try to find out and get back to you.

**Comment by MarhyCZ** [comment]
​​
No problem. Thanks for hearing out :)

2015-08-27 18:23 GMT+02:00 DennisL <notifications@github.com>:

> Sorry, I misread your question.
> I'm not sure about that but I'll try to find out and get back to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/2046#issuecomment-135483939>.
>



-- 
Hezký den přeje,
Michal Marhan

**Comment by DennisLfromGA** [comment]
'kodi' doesn't seem to show up in 'synaptic' or the Software Center, they still just show 'xbmc', at least on my 'trusty' chroot. I suppose one could write a target that adds the `team-xbmc/ppa` and then perform the other steps to get kodi:
```
sudo apt-get install python-software-properties pkg-config
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi
```
You'd most likely have to add and rename `xbmc-keyboard.xml`, `xbmc-cycle.py`, and `crouton-xbmc-keymaps.sh` plus do the other things that are currently in the '[xbmc](https://github.com/dnschneid/crouton/blob/master/targets/xbmc)' target.

I'm afraid I'm not that ambitious at the moment ;), I usually just add the 'xbmc' target and then do the steps I linked above to get 'kodi'.

-DennisL

**Comment by thetwoflower** [comment]
Hi I've installed crouton to get Kodi a few times. The best way so far is to install -
sudo sh ~/Downloads/crouton -r trusty -t xfce,xiwi
I have always hated not being able to copy and paste into linux from chrome so this sorts that.
https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom you'll need this extension.
Now you can expand and move around windows easier.
This means you just then install Kodi from terminal

sudo apt-get install python-software-properties pkg-config
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi

Then also install PVR addons
http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux.


Whatever you use Kodi for will work with a bit of trial and error. There are more PVR addons on unofficial websites.

Then just Back up your Kodi Build alot!!!

**Comment by divx118** [comment]
@thetwoflower copy paste also works in xorg, but you have to install the extension target. So in your case `sudo sh ~/Downloads/crouton -r trusty -t xfce,extension` and of course install the crouton-integration extension in chromeos like your mentioned. xorg has the advantage over xiwi that if your chromebook supports it, it will have hardware acceleration for video.

**Comment by thetwoflower** [comment]
Sounds great ill look into it now.

Date: Tue, 5 Jan 2016 08:43:23 -0800
