### ISSUE TITLE
proper window close signals

### ISSUE THREAD

**Issue by shanemikel** [dnschneid/crouton#2047]
I've noticed that closing the xiwi window doesn't really stop the running process (at least it wasn't the case for me running eclipse).  For the time being, I try to remember to exit from the file menu, but I feel like closing a window should SIGHUP the xiwi process, or it's child.

Most linux gui programs respond to some kind of signal and clean up after themselves.  Maybe the answer isn't HUP (as I'm not quite sure), but it's something that doesn't seem to be happening with crouton.

**Comment by jmaris** [comment]
I +1 this, it's an enormous pain in the ass !

**Comment by dnschneid** [comment]
It's a bit too easy to close a Chrome window, but maybe it could auto-kill the app after X seconds if you don't re-open it.

**Comment by shanemikel** [comment]
What do you mean?  I would generally expect that if you close a window, the ideal solution is to signal the so-called app.  Perhaps the HUP isn't the right signal for this, I'm not quite sure, just going with my gut.  Some signals kill a program, while some politely ask it to shutdown of it's own accord.  I haven't really build any production linux gui programs, so I don't know the convention for this, however I'm confident there is one.

I may head over to gnome (or another) IRC and see If I can get an answer.

**Comment by shanemikel** [comment]
I've talked to some Gnome people, and it appears that I'm wrong.  Closing a window isn't a unix signal, but a signal sent over the X11 socket.  Looks like it's something that should be part of Xiwi implementation.

There are utilities like wmctrl that can deliver these signals via a CLI, but i'm not sure how involved this hackish approach would be, as it becomes a matter of accounting for window ownership.

**Comment by jmaris** [comment]
i agree with @dnschneid that that is a good solution, the issue, as he stated, is that hitting the cross and pkill'ing the app doesn't leave time for prompts like "You haven't saved ! are you sure".

Another solution would be to have all xiwi windows as frameless windows and then create them a frame, with a close button that sends a ALT-F4 to the app. Then the app itsself can display any messages it needs to and close after.

**Comment by dnschneid** [comment]
There's an X11 server per xiwi window; killing the X server should make all the applications in that instance quit as gracefully as if you logged out.

Sending Alt+F4 (well, the equivalent close window client message) and properly re-displaying a xiwi window if the app responds would be a very complex feature to implement...

**Comment by shanemikel** [comment]
I, personally, like the solution proposed by @jmaris

**Comment by emanuensis** [comment]
i have a Zombie XiWi that will not let me start a new one, yet will not connect to the Crouton Integration. So how do i find its `PID` so i can send a `SIGHUP` to it? Nothing really stands out on `ps aux`, but then i do not know what to look for, let alone `grep` for.

**Comment by shanemikel** [comment]
@emanuensis AFAICT, that doesn't really belong in this thread.  Take it back to your bug report for Zombie Xiwi and I'll try to help you there.  (That bug would be more aptly named something like 'Running, accounting for, and ending a xiwi session)

**Comment by jmaris** [comment]
I'll try to implement something if i have time

**Comment by jmaris** [comment]
It shouldn't be too complex to implement. I'm taking a look at the source code now

**Comment by jmaris** [comment]
Basicly what needs to be done is :
1. Remove native chromeOS Window Frames.
2. Create a frame in HTML in the window.html file (in the extension), using webkit-app-region make the frame draggable. Add a cross to close the window and make that cross send a signal via websocket (or however they are supposed to be sent)
3. On the chroot side of things that command needs to be recieved. Using xdotool we can then send an ALT-F4 to the application and The application will prompt the user as to if they wish to save or not.

What thinkith thee ? (sorry for the tripple post)

**Comment by poxin13** [comment]
I believe I am having this problem as well. Using ```sudo enter-chroot -b xiwi telegram``` to launch telegram in a window. Telegram itself doesn't have a button for Quit within the application and closing the window with [X] leaves it running and my chroot mounted. I have to kill the app.
