### ISSUE TITLE
Chroot asking for password that I did NOT set [Solved]

### ISSUE THREAD

**Issue by adhoc92** [dnschneid/crouton#2050]
I just bought a new Chromebook. I downloaded Chrouton and typed "sudo sh ~/Downloads/crouton -t xfce" into Crosh > Shell.

Then I received the following message:

" We trust you have received the usual lecture from the local System
 Administrator. It usually boils down to these three things:

1) Respect the privacy of others.
2) Think before you type.
3) With great power comes great responsibility.

 Password: "

I've tried every password I can think of with no success. Any ideas?

**Comment by DennisLfromGA** [comment]
By default, there is no password for chronos or root so if one is set, you'll have to remove it. 

Before installing a new chroot or anything else, it might be best if you saved everything you need in ~/Downloads, etc. and do a 'powerwash'. 
You can access 'powerwash' from Advanced settings or press <kbd>Ctrl+Alt+Shift+R</kbd> from the sign-in screen.

**Comment by adhoc92** [comment]
I have powerwashed several times. After each wash, I have enabled developer settings. Crosh > shell still asks me for a password after any Sudo command.

**Comment by tcagle** [comment]
You should read the sudo man page or google sudo and read what it does.
Sounds like normal behavior to me.

**Comment by adhoc92** [comment]
I just finished reading the manual. I don't see anything that will help me. I have found a few ways to change the password, but I need Sudo access to do so.

**Comment by tcagle** [comment]
If memory serves (big if) there is a default password for the sudo
(chronos) login and it is documented on the crouton website.

**Comment by DennisLfromGA** [comment]
> I just bought a new Chromebook.

If that's the case, I don't see how you could have anything other than the 'stock' Chrome OS.
But, if a powerwash doesn't do it, then you may need to use the '[Chromebook Recovery Utility](https://support.google.com/chromebook/answer/6002417?hl=en&source=genius-rts)'.

**Comment by adhoc92** [comment]
Dennis, I have done that as well :/ Same result.

**Comment by adhoc92** [comment]
SOLVED.

I fixed it by NOT enabling debug features on the setup screen. I don't know why, but that locks me out of Sudo.

So if any future adventurers with an Acer CB3-111 Chromebook have the same problem, that may work.

**Comment by DennisLfromGA** [comment]
> I fixed it by NOT enabling debug features on the setup screen.

Well I'd say *that* was an important omission.

See **[Debugging Features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features)*
> [OPTIONAL] Set the new root password. 
Note: If you leave the root password blank, the password defaults to test0000.

**Comment by adhoc92** [comment]
Yeah, that's my my bad. I thought it was a normal part of the process that went without saying. That was obviously NOT the case. Thanks for sticking around and helping me out guys!

**Comment by tedm** [comment]
k, so now we know you're not crazy ;)

**Comment by billunique** [comment]
Thanks, this is just what I am finding.

**Comment by DennisLfromGA** [comment]
There seems to be a glitch in setting up the [Debugging features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features) in CrOS that leads to this issue. I don't know if it's a WAI (works as intended) thing or not but it can throw a kink in things if you're not aware of it.
This thread talks about it and has a workaround for it too - https://github.com/dnschneid/crouton/issues/2927#issuecomment-264746586

*Hope this helps,*
-**DennisL**

**Comment by scottdavisxx** [comment]
I just ran into the same problem. It turns out. it is not asking for your password to download. It is asking you to create a password. If you type in a password of your choice and then confirm that same password. It will then ask for another password to be created. I used the same password. 

I followed this guide. https://www.lifewire.com/install-linux-on-chromebook-4125253

This is how they describe this process.
"You may now be prompted to provide and verify both a password and an encryption passphrase at this juncture, the reason being that you chose to encrypt your Ubuntu installation via the "-e" parameter in the previous step. While this flag is not required, it is highly recommended. Choose a secure password and passphrase that you will remember and enter them accordingly, if applicable."

**Comment by ollie05w** [comment]
Guys I found a password for it 
What I did for both debugging and without debugging for when it says think before you type 
The password I guessed is 
Passwd= localhost lower case 
This was lucky I tried so many others it's only this what I found to work

**Comment by ollie05w** [comment]
Localhost is the password

**Comment by aleksclark** [comment]
for what it's worth, I discovered the following: the root password you set when enabling debugging tools will work over SSH but will NOT work from the local shell. if you ssh in as root, you can then change all the passwords to be what you want.

**Comment by johanwitters** [comment]
Thanks @aleksclark  That's the solution for me

**Comment by jschnarr** [comment]
Yep, @aleksclark is right (thanks!). The user you need to set the password for is chronos, so run:
ssh root@localhost (use the root password you set enabling debug features)
passwd chronos

**Comment by cierracarmon18** [comment]
The ssh root@localhost keeps refusing the connection I'm not really computer savvy but installing the software did take so long of a time I don't wish to resit through it I just need to reset the password and this is frustrating

**Comment by jschnarr** [comment]
It's actually simpler than @aleksclark and I previously said, and SSH doesn't work reliably.

Press ctl+alt+forward (by forward I mean the F2 equivalent, not the right arrow). It will pop up the proper developer console which allows you to logon as root with the password you set during setup. It also has instructions for setting the chronos password properly using chromeos-setdevpasswd.

**Comment by patsprice** [comment]
Thank you @jschnarr, your solution worked perfectly.

**Comment by IgorGanapolsky** [comment]
@johanwitters 
> Localhost is the password
No it is not

**Comment by mosesdel** [comment]
where do you type in chromeos-setdevpaswd

**Comment by patsprice** [comment]
I cannot remember exaclty but it prompted me sometime during the install, if I remember correctly. Now when I boot up, if I go CTRL-ALT-T, I get to the crosh prompt, then I type in shell and hit Enter and then I type in sudo enter-chroot and it prompts me for the password I set during install.  At that point I am logged in as the username@localhost that I created during install.

**Comment by KevinVandy** [comment]
Took me a while to find all the relevant information on this page, but I was able to figure it out. I had the same problem OP had. I made a root password while putting it into developer mode, but that password did not work in the crosh prompt (Ctrl + Alt + t). Here is exactly what worked for my asus chromebook flip c302 chromeos ver 63.

1. Press Ctrl-Alt-forward
2. Login as the user "root" and the password that you made while putting it into developer mode.
3. You should be in as localhost now. Then from here you can set a new password that works in your crosh shell. So, in the shell that we just logged into, type the command
chromeos-setdevpasswd
then you can set a password, which you will probably want to be the same password that you just used if you want to keep it simple.
4. After you have set the password from that prompt you can get sudo privileges with that password.

**Comment by tomford007** [comment]
KevinVandy, THANK YOUUUUUUUUU!!!!!

**Comment by jonmorales89** [comment]
@KevinVandy , thank you! Worked for me on an Acer C910.

**Comment by laurentschneider** [comment]
if you set a root password for debugging, use it with

ssh root@localhost

from shell (CTRL-ALT-T + shell)

**Comment by primeroseis** [comment]
I had the same issue installing crouton on a samsung chromebook, and solved it skipping to check the debugger features as user adhoc92  pointed out.....   I am still waiting for the install to conclude  .....but  would like to know which might be  a good forum about how to use  the xfce desktop all the links I follow point to unity ... Thanks for any advice

**Comment by patsprice** [comment]
I uninstalled it all, returned my pixel book to standard and started using
Google cloud shell, I'm connected to the cloud just about 24/7 anyway

**Comment by citydesi** [comment]
THANKS TO KEVIN

**Comment by ieee488** [comment]
Thank you Kevin !!!!

I had enabled debugging features but I did not set a password so I had the default password  **test0000**   mentioned by DennisLfromGA.

Dell 11 3120 Chromebook.

**Comment by vibraniumdroid** [comment]
guys guys guys!

Easy solution CTRL + ALT +2
login with username: root
and password: test0000

run the set password command and leave it empty

Chrome OS with debugging features enabled :)

**Comment by Ouranophobia** [comment]
> 
> 
> if you set a root password for debugging, use it with
> 
> ssh root@localhost
> 
> from shell (CTRL-ALT-T + shell)

This worked for me thank you!

**Comment by clintryan413211** [comment]
I'm on a Samsung chrome book and can't get shit done on finding out the password

**Comment by DennisLfromGA** [comment]
@clintryan413211,

1. Follow the instructions [two comments up](https://github.com/dnschneid/crouton/issues/2050#issuecomment-493717206) or 
2. powerwash your device and don't select Debugging Features. Once you're signed-in you can enable any of the Debugging features you like by running one or more of the following scripts:
```
/usr/libexec/debugd/helpers/dev_features_chrome_remote_debugging
/usr/libexec/debugd/helpers/dev_features_password
/usr/libexec/debugd/helpers/dev_features_rootfs_verification
/usr/libexec/debugd/helpers/dev_features_ssh
/usr/libexec/debugd/helpers/dev_features_usb_boot
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by GCStokum** [comment]
was having the same issue, and found that while there Hasn't been a password set, the default is <NULL> NOT <empty>  so you should Set one with a quick:
sudo su
passwd
<then enter your new pass>

(I've not tried this with setting the su to <empty> but has sorted out all my other pw issues)

hope that helps some of you

**Comment by schester44** [comment]
I was never given a password prompt, but using "localhost" as the password worked for me 👍

**Comment by anthello147** [comment]
I am running Chromium OS (Version 48, Developer Build) by Neverware on VirtualBox 6.1. As I do not have a Google Account, I login as Guest, and I did not know how to run commands as superuser because I did not know my UNIX password (as I was logged in as Guest):
```
chronos@localhost / $ sudo su

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
Sorry, try again.
Password: 
Sorry, try again.
Password:
Sorry, try again.
sudo: 3 incorrect password attempts.
chronos@localhost / $
```
I had tried multiple different passwords, such as `localhost`, `facepunch`, `test0000`. None of these worked. Eventually I stumbled across a website (I do not remember which), which said that the default password for user `chronos` was `chrome`. I tried this out, and it worked:
```
chronos@localhost / $ sudo su

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
localhost / #
```
I hope this helps.

**Comment by sppidy** [comment]
better solution which worked for me 

sudo -i (logins as root)
passwd root (Change password of root)
passwd <ur username> (Change Ur Password)
exit

now ,
su - root (Enter The Password u Set)

> I just bought a new Chromebook. I downloaded Chrouton and typed "sudo sh ~/Downloads/crouton -t xfce" into Crosh > Shell.
> 
> Then I received the following message:
> 
> " We trust you have received the usual lecture from the local System
> Administrator. It usually boils down to these three things:
> 
> 1. Respect the privacy of others.
> 2. Think before you type.
> 3. With great power comes great responsibility.
> 
> Password: "
> 
> I've tried every password I can think of with no success. Any ideas?

**Comment by mph-code** [comment]
> Took me a while to find all the relevant information on this page, but I was able to figure it out. I had the same problem OP had. I made a root password while putting it into developer mode, but that password did not work in the crosh prompt (Ctrl + Alt + t). Here is exactly what worked for my asus chromebook flip c302 chromeos ver 63.
> 
> 1. Press Ctrl-Alt-forward
> 2. Login as the user "root" and the password that you made while putting it into developer mode.
> 3. You should be in as localhost now. Then from here you can set a new password that works in your crosh shell. So, in the shell that we just logged into, type the command
>    chromeos-setdevpasswd
>    then you can set a password, which you will probably want to be the same password that you just used if you want to keep it simple.
> 4. After you have set the password from that prompt you can get sudo privileges with that password.

I spent ages looking for this information last year and am so glad I finally was able to quickly take care of this impediment!! Not sure how I didn't find this when I was trying to figure this out a year ago. Thank you for laying out this information. Super easy fix.

**Comment by DennisLfromGA** [comment]
@mph-code,

The method/procedure you outlined above does work but just an fyi:
- The password you set when you enabled the Debugging Features was for username: 'root'
- The password you set with the script `chromeos-setdevpasswd` is for username: 'chronos'.

*Hope this helps,*
-**DennisLfromGA**

**Comment by jcoles56** [comment]
@mph-code 

Thanks for trying to summarize the solution. But it's not clear enough for me (I need everything clear and unambiguous). At what point do you enter Ctrl-Alt-Forward? (Recovery screen?)

Tech threads often mark a problem as "Solved" but all too often I can't find the solution in it! People made all kinds of suggestions. I can't tell which one is right. For this annoying problem, I'm trying every hack and password suggestion I can find. So far, nothing works.

Thanks.

**Comment by jcoles56** [comment]
"Soluitions" that involve the use of chromeos-setdevpasswd CANNOT WORK because they require root access, which requires the password. Is there a genuine solution to being asked for a password that you never set or were never given?
