### ISSUE TITLE
Backup Directory - No Such File Or Directory

### ISSUE THREAD

**Issue by AndromedaOnGIT** [dnschneid/crouton#2051]
When trying to create a backup to my USB called USBDISK I cd /media/USBDISK/ but it returns "No Such File Or Directory" How to I Fix. or can I create the backup and move it to my usb?

**Comment by DennisLfromGA** [comment]
Are you sure it's not '/media/**removable**/USBDISK/' ?
Can you access it from the 'Files' app? If so, then it is mounted and you should be able to '`cd`' to it.
But yes, as long as you have enough disk space, you could back it up on your Chromebook and then move or copy it to your removable media.

**Comment by AndromedaOnGIT** [comment]
k thankyou
