### ISSUE TITLE
Issues when installing ubuntu on usb for chromebook

### ISSUE THREAD

**Issue by sgonzalez301301** [dnschneid/crouton#2052]
I have been following this youtube video (https://www.youtube.com/watch?v=wJ4WcfHFjKg) to install ubuntu on a usb drive for my chromebook. I have also been using this document (https://docs.google.com/document/d/1MJZYllAj_o-erv4WF2CKdjtHjT6Wee4t4mj6SlDRG8c/edit)  made by the youtube video creator that has updated a few things to type in the terminal. I manage to get to step 20 in the document without any errors. However when i try to type in step 21 that will install crouton to my flash drive ( sudo sh  ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive 2), i get the following message. Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo sh  ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive 2
Downloading latest crouton installer...
######################################################################## 100.0%
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: precise,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.
chronos@localhost / $ 

I dont know if it helps, but i am using a Lenovo X131e Intel chromebook.

**Comment by DennisLfromGA** [comment]
> It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

It looks like you're attempting to run it from VT2 and not from a terminal session - which is *not* recommended per the above message.

----
The display that crouton is showing you is one that can be caused when something on the command is not quite correct. linux is very particular about *spaces* and upper/lowercase letters, it looks like you possibly may have not 'escaped' the last space in your command - before the number 2:

`sudo sh ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive 2`

Try using another 'backslash' character '\' before the the number 2 and see if that helps.
Also, you can type in part of the path and then press the 'tab' key and the shell will complete the remainder by itself, adding any 'backslach' characters needed in the command.

**Comment by sgonzalez301301** [comment]
ok thanks ill try it right now

**Comment by sgonzalez301301** [comment]
I typed sudo sh ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive \2 and i am still getting this message. 
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive \2
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: precise,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
Okay, try just typing:

`sudo sh ~/Downloads/crouton -r trusty -t xfce -p /media/removable`

and then press the 'tab' key one or twice to see if it completes it.

**Comment by sgonzalez301301** [comment]
I typed it and i pressed the tab key twice. It did not show usb drive 2 it only showed this
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive
/media/removable/USB Drive/chroots/trusty is not an ext filesystem.
chronos@localhost / $ 
but on my filesystem it shows usb drive 1 and usb drive 2

**Comment by DennisLfromGA** [comment]
Do you have more than one usb stick plugged in?
Also, did you perform steps 9 thru 13 to format it ext4?

**Comment by sgonzalez301301** [comment]
I only have 1 usb plugged in. I did perform the steps. Should i redo the steps?

**Comment by sgonzalez301301** [comment]
Now that I remember I saw in the video that it first showed that there were two usb but later after a different step it showed that he had 1 usb. I'll try re doing the steps

**Comment by DennisLfromGA** [comment]
You may have to re-run those steps again if it's not recognizing it as an ext file system.
If you run `sudo fdisk -l` it should tell you what the partitions are. Also, if you do re-run the stpes, mkae sure they all complete without error.

**Comment by sgonzalez301301** [comment]
This is what i got when i typed it.

chronos@localhost / $ sudo fdisk -l

Disk /dev/loop0: 3.1 GiB, 3372515328 bytes, 6586944 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/sda: 14.9 GiB, 16013942784 bytes, 31277232 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 45A73F95-F50F-014C-B28E-FA7ED0817A70

Device        Start      End  Sectors  Size Type
/dev/sda1    282624 22855679 22573056 10.8G Microsoft basic data
/dev/sda2     20480    53247    32768   16M ChromeOS kernel
/dev/sda3  27049984 31244287  4194304    2G ChromeOS root fs
/dev/sda4     53248    86015    32768   16M ChromeOS kernel
/dev/sda5  22855680 27049983  4194304    2G ChromeOS root fs
/dev/sda6     16448    16448        1  512B ChromeOS kernel
/dev/sda7     16449    16449        1  512B ChromeOS root fs
/dev/sda8     86016   118783    32768   16M Microsoft basic data
/dev/sda9     16450    16450        1  512B ChromeOS reserved
/dev/sda10    16451    16451        1  512B ChromeOS reserved
/dev/sda11       64    16447    16384    8M unknown
/dev/sda12   249856   282623    32768   16M EFI System

Partition table entries are not in disk order.
Disk /dev/mapper/encstateful: 3.1 GiB, 3372515328 bytes, 6586944 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/sdc: 28.9 GiB, 31009800192 bytes, 60566016 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xf12f7589

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdc1  *     8064 60566015 60557952 28.9G  c W95 FAT32 (LBA)
/dev/sdc2        2048     8063     6016    3M 83 Linux

Partition table entries are not in disk order.

**Comment by sgonzalez301301** [comment]
I did the next to steps and got this.
chronos@localhost / $ sudo umount /dev/sdb1
umount: /dev/sdb1: mountpoint not found
chronos@localhost / $ sudo mke2fs -t ext4 /dev/sdb1
mke2fs 1.42.12 (29-Aug-2014)
The file /dev/sdb1 does not exist and no size was specified.
chronos@localhost / $ sudo mount /dev/sdb1 /media/removable/SD\ Card
mount: mount point /media/removable/SD Card does not exist
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
> Device Boot Start End Sectors Size Id Type
> /dev/sdc1 * 8064 60566015 60557952 28.9G c W95 FAT32 (LBA)
> /dev/sdc2 2048 8063 6016 3M 83 Linux

It looks like your USB stick is detected as `/dev/sdc` not `/dev/sdb` and the biggest partiton, /dev/sdc1` is FAT32 not ext2/3/4. The second partition, `/dev/sdc2` is only 3M.

**Comment by sgonzalez301301** [comment]
so what should i do?

**Comment by DennisLfromGA** [comment]
> so what should i do?

You need to repeat steps 9 thru 14 substituting `/dev/sdb` with `/dev/sdc` - but *please* make sure you have only *one* USB stick plugged in and it's the one you want to use for your 'crouton' chroot(s)/

**Comment by sgonzalez301301** [comment]
ok thanks. I will try this.

**Comment by DennisLfromGA** [comment]
The command `lsblk` is handy also and will tell you a little bit  about what devices are in use.

**Comment by sgonzalez301301** [comment]
thanks

**Comment by sgonzalez301301** [comment]
i did step 9. On step 10 i press d than it asks if i want to choose 1 or 2 partitions and it has in parenthesis that default is two. Should i choose 1 or two?

**Comment by sgonzalez301301** [comment]
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo fdisk /dev/sdc

Welcome to fdisk (util-linux 2.25.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): d
Partition number (1,2, default 2): d

**Comment by sgonzalez301301** [comment]
I did this next
Welcome to fdisk (util-linux 2.25.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): d
Partition number (1,2, default 2): d
Value out of range.
Partition number (1,2, default 2): 1

Partition 1 has been deleted.

Command (m for help): d
Selected partition 2
Partition 2 has been deleted.

Command (m for help): d
No partition is defined yet!
Could not delete partition 140728473680401

Command (m for help): n
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (1-4, default 1): 
First sector (2048-60566015, default 2048): 
Last sector, +sectors or +size{K,M,G,T,P} (2048-60566015, default 60566015): 

Created a new partition 1 of type 'Linux' and of size 28.9 GiB.

**Comment by DennisLfromGA** [comment]
The instructions say:
\> d
(This command will delete the partition currently existing on the SD card.  If there are multiple partitions on the card, you will need to enter d more than once, deleting each successive partition with each entry until there are none remaining on the SD card.)

**Comment by sgonzalez301301** [comment]
Got it. Thanks.

**Comment by DennisLfromGA** [comment]
That looks good!

**Comment by sgonzalez301301** [comment]
After pressing p i have to press 1.
I did it. And got.
Command (m for help): n
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (1-4, default 1): 
First sector (2048-60566015, default 2048): 
Last sector, +sectors or +size{K,M,G,T,P} (2048-60566015, default 60566015): 

Created a new partition 1 of type 'Linux' and of size 28.9 GiB.

Command (m for help): 1
1: unknown command

Command (m for help): 


Command (m for help): v

Command (m for help): w

The partition table has been altered.
Calling ioctl() to re-read partition table.
Re-reading the partition table failed.: Device or resource busy

The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or kpartx(8).

**Comment by sgonzalez301301** [comment]
should i just reboot?

**Comment by sgonzalez301301** [comment]
sorry. I missed to go directly to step 21

**Comment by DennisLfromGA** [comment]
> should i just reboot?

Did you finish all the steps successfully, especially: `sudo mke2fs -t ext4 /dev/sdb1` ?
( using `/dev/sdc` if need be )

If so, then you can reboot and run your 'crouton' install ocmmand again.

**Comment by sgonzalez301301** [comment]
I tired it again and got 
chronos@localhost / $ /dev/sdc sudo umount /dev/sdc
bash: /dev/sdc: Permission denied

**Comment by DennisLfromGA** [comment]
I don't know why you're trying to 'unmount' it. If all the steps (9-17) were completed successfully then you're good to go, you should be able to continue on with step 20 and/or 21.

**Comment by sgonzalez301301** [comment]
oh ok.

**Comment by sgonzalez301301** [comment]
I tried the step again and got the same thing as i did at the start.

chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive/
Downloading latest crouton installer...

######################################################################## 100.0%
/media/removable/USB Drive/chroots/trusty is not an ext filesystem.
chronos@localhost / $ 
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r trusty -t xfce -p /media/removable/USB\ Drive 2/
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: precise,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
Something didn't work or complete successfully then.
Try running `sudo fdisk -l` again and let us know what it displays.

**Comment by sgonzalez301301** [comment]
ok

**Comment by sgonzalez301301** [comment]
chronos@localhost / $ sudo fdisk -l

Disk /dev/loop0: 3.1 GiB, 3372515328 bytes, 6586944 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/sda: 14.9 GiB, 16013942784 bytes, 31277232 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 45A73F95-F50F-014C-B28E-FA7ED0817A70

Device        Start      End  Sectors  Size Type
/dev/sda1    282624 22855679 22573056 10.8G Microsoft basic data
/dev/sda2     20480    53247    32768   16M ChromeOS kernel
/dev/sda3  27049984 31244287  4194304    2G ChromeOS root fs
/dev/sda4     53248    86015    32768   16M ChromeOS kernel
/dev/sda5  22855680 27049983  4194304    2G ChromeOS root fs
/dev/sda6     16448    16448        1  512B ChromeOS kernel
/dev/sda7     16449    16449        1  512B ChromeOS root fs
/dev/sda8     86016   118783    32768   16M Microsoft basic data
/dev/sda9     16450    16450        1  512B ChromeOS reserved
/dev/sda10    16451    16451        1  512B ChromeOS reserved
/dev/sda11       64    16447    16384    8M unknown
/dev/sda12   249856   282623    32768   16M EFI System

Partition table entries are not in disk order.
Disk /dev/mapper/encstateful: 3.1 GiB, 3372515328 bytes, 6586944 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk /dev/sdc: 28.9 GiB, 31009800192 bytes, 60566016 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xf12f7589

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdc1        2048 60566015 60563968 28.9G 83 Linux

chronos@localhost / $

**Comment by DennisLfromGA** [comment]
Okay, drive `/dev/sdc1` looks like a Linux partiton. 
Did you successfully perform steps 12 & 13 on it or did you not get it 'unmounted' earlier?

**Comment by sgonzalez301301** [comment]
I think that i performed them. Should i just do them again?

**Comment by DennisLfromGA** [comment]
It couldn't hurt, just make sure it's 'ejected' in the 'File' manager and that it's unmounted first before you try - and that you use `/dev/sdc1` instead of `/dev/sdb1`.

**Comment by sgonzalez301301** [comment]
Got it. Thanks

**Comment by sgonzalez301301** [comment]
I pressed the eject button on file manager. I did step 12 and got this output.
chronos@localhost / $ sudo umount /dev/sdc1
umount: /dev/sdc1: not mounted
chronos@localhost / $

**Comment by sgonzalez301301** [comment]
Is the output good or bad?

**Comment by DennisLfromGA** [comment]
If you ejected it in the file manager that 'unmounted' it so you can do steps 12 & 13 now.

**Comment by sgonzalez301301** [comment]
ok thanks. ill do step 13 now.

**Comment by DennisLfromGA** [comment]
Yeah, sorry, just step 13.

**Comment by sgonzalez301301** [comment]
I did step 13 and got this.
chronos@localhost / $ sudo mke2fs -t ext4 /dev/sdc1
mke2fs 1.42.12 (29-Aug-2014)
/dev/sdc1 contains a ext4 file system
        last mounted on Sun Aug 30 10:40:06 2015
Proceed anyway? (y,n) 
Do i choose yes?

**Comment by DennisLfromGA** [comment]
It wouldn't hurt to say 'y' or yes...

**Comment by sgonzalez301301** [comment]
ok

**Comment by DennisLfromGA** [comment]
Once that's done, unplug it and then plug it in again and see what 'name' it's given.

**Comment by sgonzalez301301** [comment]
I pressed y and got this
chronos@localhost / $ sudo mke2fs -t ext4 /dev/sdc1
mke2fs 1.42.12 (29-Aug-2014)
/dev/sdc1 contains a ext4 file system
        last mounted on Sun Aug 30 10:40:06 2015
Proceed anyway? (y,n) y
Creating filesystem with 7569408 4k blocks and 1896048 inodes
Filesystem UUID: f7fb2a9c-f3f1-4aa5-9d8b-efdc24629b16
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
        4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done

**Comment by sgonzalez301301** [comment]
ok thanks

**Comment by sgonzalez301301** [comment]
ill unplug right now

**Comment by sgonzalez301301** [comment]
I plugged it in and a pop up stated that it couldent recognize my usb. I opened file manager and my usb is called USB Drive 1. It is blank. There is an option to "format device".

**Comment by sgonzalez301301** [comment]
oh it also says that the device cannot be opened because the filesystem was not recognized. It says this in filesystem.

**Comment by sgonzalez301301** [comment]
should i do step 14 and mount it

**Comment by DennisLfromGA** [comment]
Don't format it, see what it displays when you enter: `ls -l /media/removable/USB\ Drive\ 1`

**Comment by sgonzalez301301** [comment]
i go this 
chronos@localhost / $ ls -l /media/removable/USB\ Drive\ 1
total 0

**Comment by DennisLfromGA** [comment]
It seems to be mounted, enter: `mount|grep sdc`

**Comment by sgonzalez301301** [comment]
I did and got this
chronos@localhost / $ mount|grep sdc
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
It may not be mounted, try rebooting and then run the mount command again: `mount|grep sdc`

**Comment by sgonzalez301301** [comment]
ok. it may take a while to reboot. Do i eject my usb prior to rebooting?

**Comment by DennisLfromGA** [comment]
Just leave it in...

**Comment by sgonzalez301301** [comment]
ok thanks

**Comment by sgonzalez301301** [comment]
I got the sam output.
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ mount|grep sdc
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
This is really not the place to troubleshoot this problem in real-time. Do you have access to the #crouton IRC channel on freenode.net? That'd be a better place to continue this, we might be able to recruit more help there too.

**Comment by sgonzalez301301** [comment]
i dont have access

**Comment by sgonzalez301301** [comment]
do i make an account?

**Comment by DennisLfromGA** [comment]
Yup.

**Comment by DennisLfromGA** [comment]
Once you have an account, enter: /join #crouton

**Comment by sgonzalez301301** [comment]
I went to the site and i don't see a place to make an account.

**Comment by sgonzalez301301** [comment]
i made an account in their webchat

**Comment by DennisLfromGA** [comment]
https://github.com/dnschneid/crouton/issues/2052#issuecomment-136176648

**Comment by sgonzalez301301** [comment]
the link takes me to this same blog

**Comment by DennisLfromGA** [comment]
Yes, it does. In your webchat on freenode.net enter the #crouton channel.

**Comment by sgonzalez301301** [comment]
ok. I made a username and typed #crouton channel under channels. It took me to a chat room

**Comment by sgonzalez301301** [comment]
there doesnt appear to be anyone chatting there

**Comment by DennisLfromGA** [comment]
I'm there as 'DennisL' - and attempting to chat with you.
