### ISSUE TITLE
Avoid battery going flat without warning

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#2054]
I have occasionally found that when I'm running Crouton I have flattened my battery without warning (running LXDE Trusty). This is fairly serious when I'm working on un-backed-up files, although most of my editors have a fairly forgiving resume.

I'm sure ChromeOS is silently notifying me in the background of battery events, but I need something that has access to the Crouton VT if I'm going to rely on warnings.

Preferably I would like to know if there's a mainstream way to trigger a warning, and then a follow-up auto-suspend on a specific battery percentage. I note that in https://github.com/dnschneid/crouton/issues/71 @dnschneid warns not to enable autosuspend in xfce4-power-manager, so I guess using regular utilities isn't an option. 

Are there any options which are known to work apart from rolling your own logic?

**Comment by tista500** [comment]
@cefn,

I think there would be the theoretical way like this:

 1. Create custom udev rule to watch the battery state and to hook script actions
 2. Create some shell script to warn battery capacities by ringing bell and/or backlight flashing, and to run suspend hook after warning
 3. Insert that rule to /run/udev/rules.d from chroot
 4. Insert those scripts to somewhere 

Were those enough? I suppose the owner of udev (and dbus as well) is ChromeOS, so we will have to  make those scripts to run properly from ChromeOS... If so, we also need to set the "absolute path" to script and its contents carefully.

For example, the udev rule is something like this:
```
# Warn when capacity drops to 7% (and keep warning to 5%)
SUBSYSTEM=="power_supply", \
ATTR{status}=="Discharging", \
ATTR{capacity}=="[5-7]", \
RUN+="WARN_SCRIPT"

# Then drops to 5% or lower, run suspend
SUBSYSTEM=="power_supply", \
ATTR{status}=="Discharging", \
ATTR{capacity}=="[0-5]", \
RUN+="SUSPEND_SCRIPT"
```

Backlight flashing as warning would be a bit easier than ringing bells via aplay, as long as we want to do sound actions, we have to search some sound files within both ChromeOS and chroot, but backlight control could be done by inserting brightness values to sysfs parameters only without any other resources.

Regards.

**Comment by dnschneid** [comment]
Stuff like xfce4-power-manager should work fine inside the chroot.  You just have to go into its settings and make sure it doesn't auto-suspend on idle (auto-suspend on critical power is fine if you want it).
