### ISSUE TITLE
weird

### ISSUE THREAD

**Issue by thatoneguy64** [dnschneid/crouton#2055]
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:10:32 PDT 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72/PARTNROFF=1 hashtree=PARTUUID=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=7d16dfd6647864317c84b64ffd092069c8507f65 salt=f5db6aaf07f8653cd319eee1dd47e2f34be8a2272c27cd8823d15901f314c15c" noinitrd vt.global_cursor_default=0 kern_guid=f26d5cf9-8cbc-e74e-a721-4ba656b3bf72  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Aug 31 21:29:34 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed
crouton: version 1-20150827155505~master:edbce112
release: precise
architecture: armhf
xmethod: xorg
targets: unity
host: version 7077.134.0 (Official Build) stable-channel veyron_jerry 
kernel: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:10:32 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
chronos@localhost / $

**Comment by thatoneguy64** [comment]
i upgraded ubuntu through crosh to 14.04.1 trusty tahr through crosh; how to fix?

**Comment by thatoneguy64** [comment]
tried updating crouton, but it said this:
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -n precise -u
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
unity target does not work in xephyr in trusty due to missing egl support.

**Comment by thatoneguy64** [comment]
and i rewrote the drive card 0 to be in place of drive card 1, and it worked for a little while, but then stopped.

**Comment by tista500** [comment]
@thatoneguy64,

> unity target does not work in xephyr in trusty due to missing egl support.

That's the reason you've failed. so give it a try other xmethods.

**Xiwi**
`sudo sh ~/Downloads/crouton -n precise -t xiwi -u`
**Xorg**
`sudo sh ~/Downloads/crouton -n precise -t xorg -u`

And you'd better to define those xmethods expressly when launching crouton:

**Xiwi**
`sudo startunity -X xiwi`
**Xorg**
`sudo startunity -X xorg`

Regards.

**Comment by thatoneguy64** [comment]
thanks
