### ISSUE TITLE
Trusty + Unity - Cannot get right click to work (two finger on touchpad)

### ISSUE THREAD

**Issue by bmoscon** [dnschneid/crouton#2057]
I've tried the synclient commands mentioned online synclient TapButton2=2 TapButton3=3, but this does not work. 

I also tried XFCE with Trusty and right click also did not work (again, two finger right click, on touch pad). Does two finger right click work on any of the other versions of Ubuntu?

In case it matters, I'm using the 2015 Chromebook Pixel

**Comment by trenzafeeds** [comment]
On an HP 11 G3, right click with the touchpad never worked for me on KDE or on Elementary. Most likely just not supported.

**Comment by tista500** [comment]
Greetings,

Please let me see the output of these:
`xinput list`
and 
`gsettings get org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled`
(I don't know Kdesktop had such a settings key though...)

Regards.

**Comment by mark-hahn** [comment]
What wouldn't support it?  It should be a normal right click in the touch
driver or maybe even in the touchpad hardware module itself.  If the
left-click works then both of those are working.

**Comment by bmoscon** [comment]
$xinput list
� Virtual core pointer                    	id=2	[master pointer  (3)]
�   ��� Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
�   ��� Atmel maXTouch Touchpad                 	id=8	[slave  pointer  (2)]
�   ��� Atmel maXTouch Touchscreen              	id=9	[slave  pointer  (2)]
� Virtual core keyboard                   	id=3	[master keyboard (2)]
    ��� Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ��� Power Button                            	id=6	[slave  keyboard (3)]
    ��� Power Button                            	id=7	[slave  keyboard (3)]
    ��� AT Translated Set 2 keyboard            	id=10	[slave  keyboard (3)]


$ gsettings get org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled
true

**Comment by tista500** [comment]
@bmoscon,

Thanks.
Well, crouton devs seemed to implement such CMT driver as "cmt" target already: https://github.com/dnschneid/crouton/pull/1302

Didn't that target work properly today?

Regards.

**Comment by bmoscon** [comment]
so are you saying I need to install the cmt target with the crouton shell script? How is this different than touch?

**Comment by tista500** [comment]
@bmoscon,

I've searched on the web so, now CMT driver was provided by this PPA for Trusty:
https://launchpad.net/~hugegreenbug/+archive/ubuntu/cmt2

AFAIK you'd better to add thiat PPA...

Regards.

**Comment by bmoscon** [comment]
marking this as closed since the issue has been resolved. Thanks everyone!
