### ISSUE TITLE
Black Screen Override

### ISSUE THREAD

**Issue by khs** [dnschneid/crouton#2058]
What's happening: I recently saved my session in XFCE as I logged out, obeyed my ChromeOS reinstall, and was unable to enter my session. Indeed, all I see is a totally black screen (in some cases when switching or starting I can see my normal background for a fraction of a second before the black screen takes over).
croutonversion output:
crouton: version 1-20150827155505~master:edbce112
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 7077.134.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Sun Aug 16 12:47:02 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Output when trying to use sudo startxfce4, switching back to ChromeOS immediately afterwards: http://pastebin.com/6CHB2uAy
C710 Acer Chromebook. Running Crouton for several months.

**Comment by tista500** [comment]
@khs,

Sorry for the delayed respose...
You've fixed this issue already? If not, please remove the saved session caches with this:
```
sudo enter-chroot -n trusty
rm ~/.cache/sessions/*
exit
```
and then re-login with X11:
```
sudo startxfce4
```
Anythiing changed the situation?

Regards.

**Comment by khs** [comment]
I ended up installing a new chroot, but I'd love to have easy access to my old one. I can't rm as specified because it's a directory: I'm assuming rm -rf will do the trick but I want to be careful.

**Comment by khs** [comment]
rm fails, because you're asking it to delete the folder. I assume rm -rf is safe to run?

**Comment by tista500** [comment]
@khs,

Yeah my fault. that's typo. `rm -rf ~/.cache/sessions/*` would work properly and safe.

Regards.

**Comment by khs** [comment]
@tista500
Just tried that. This time I got a "No window manager registered on screen 0. To start the xfdesktop without this check, run with --disable-wm-check"
Which is interesting. Again, I saw a completely black screen (not black like background black, black like no backlight black) after a tiny fraction of a second of seeing my familiar background, with everything apparently in place.

**Comment by tista500** [comment]
OK.

> `No window manager registered on screen 0. `

Seems weird... `DISPLAY=:0` should be for ChromeOS instead of chroot (without xiwi). Well, try to add xorg target into existed chroot, run this from crosh:
```
sudo sh ~/Downloads/crouton -n trusty -t xorg -u
```
And launch XFce4 with:
```
sudo startxfce4 -n trusty -X xorg
```

Regards.

**Comment by khs** [comment]
It said that "The following packages will be upgraded" 
bind9-host google-chrome-stable:i386 libbind9-90 libdns100 libexpat1
  libexpat1:i386 libexpat1-dev libisc95 libisccc90 libisccfg90 liblwres90
  libvdpau1 linux-libc-dev
None of which look like relevant xorg packages.
Ran it again as instructed (though it has a custom name), I noted the error
(xfsettingsd:1256): xfsettingsd-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
Nothing else is obviously broken, except that the error persists.

Regards.

**Comment by tista500** [comment]
??? :(

From crosh, `sudo sh ~/Downloads/crouton -t xfce -u` worked and exited normally?

Regards.

**Comment by khs** [comment]
Yes.

**Comment by tista500** [comment]
Let me see the final output of this from crosh:
```
sudo enter-chroot
croutonversion
```

Regards.

**Comment by khs** [comment]
chronos@localhost / $ sudo enter-chroot -n newname
Password: 
Entering /mnt/stateful_partition/crouton/chroots/newname...
(newname)keller@localhost:~$ croutonversion
crouton: version 1-20150827155505~master:edbce112
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce
host: version 7077.134.0 (Official Build) stable-channel parrot 
kernel: Linux localhost 3.4.0 #1 SMP Sun Aug 16 12:47:02 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no
(newname)keller@localhost:~$

**Comment by tista500** [comment]
@khs,

Is this related to this known bug on XFce4?: http://forum.xfce.org/viewtopic.php?id=8082&p=1

> (xfsettingsd:1256): xfsettingsd-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS 

I don't think this is an critical error at least to lanch desktop session.

And by searching the web, we might need to disable the option for saved-session:
`xfconf-query -c xfce4-session -p /general/SaveOnExit -s false`
Then set "read-only" permission to cache directory:
`rm -rf ~/.cache/sessions/* && chmod 500 ~/.cache/sessions `
(From Arch wiki: https://wiki.archlinux.org/index.php/Xfce#Disable_saved_sessions)

So give it a try inside the chroot, exit, and re-login into chroot via `sudo startxfce4 -n newname`

If this won't work, try to restore settings via: https://wiki.archlinux.org/index.php/Xfce#Restore_default_settings

Regards.

**Comment by khs** [comment]
(newname)keller@localhost:~$ xfconf-query -c xfce4-session -p /general/SaveOnExit -s false
Failed to init libxfconf: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11.
I'm not quite sure what that means, but I thought I should record it here for posterity.

I did the restore settings as instructed, and now when I have the brief flash of light on switching, I can see that it's welcoming me to a new setup, suggesting a success of sorts.

Thanks for your ongoing assistance.

**Comment by khs** [comment]
Update: installing the latest crouton update, after ChromeOS updated, solved my problem.
