### ISSUE TITLE
Odd error, unable to launch KDE

### ISSUE THREAD

**Issue by trenzafeeds** [dnschneid/crouton#2059]
I successfully installed kde on my system, and I've been using it with no problems for a couple days, but today after installing steam I shut it down and when I tried to restart, it gave be a wall of text and threw the error "Fatal server error: no screens found". It also gave a server-terminating error code of 1 if that means anything. If anyone would like to see the full text, I'm happy to screenshot it.

**Comment by tista500** [comment]
@trenzafeeds,

I'm not sure which was related to this issue:
* Installing steam
* ChromeOS update

Anyway you'd better to update crouton at first.

Regards.

**Comment by v1cow** [comment]
Maybe having your log would help.
