### ISSUE TITLE
permissions?!?!?

### ISSUE THREAD

**Issue by smokinzoltar** [dnschneid/crouton#2062]
i've installed exactly as stated in the readme here(and many others as well) after going through all the setups etc,i have NO write permissions to any of my usb,sd,flash drives!this is my 10th attempt to re-install under crouton,all without success in writing to external!I'm not sure if i am entering the chroot wrong(without root permissions) or not.again i followed the readme which says sudo enter-chroot startxfce4 . any help!!

**Comment by gregnwosu** [comment]
ive noticed that my ssd drives tend to get mounted without exec permission 
i tend to have to issue 
``` sudo mount -t [FS type] -o exec,remount,defaults,nosuid,nodev /dev/...blah /var/host/media/removable/somename
```
any way round this?

**Comment by drinkcat** [comment]
mount -o remount,exec /path
