### ISSUE TITLE
Bluetooth audio experiences breakup under moderate CPU load

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#2065]
Routing via the CRAS audio adaptor from Crouton's chroot works pretty well, (using Guayadeque or Quod Libet), even when relaying audio to a nearby Bluetooth Audio adaptor.

However, I experience issues when any CPU load is introduced, such as when scrolling browser windows or loading new pages. It sounds like it's causing buffers to underrun as the browser process priority allows it to take resources from the processes serving the audio relay.

Any idea what processes I need to 'renice' in order to prioritise the various audio buffer daemons over the browser. I've tried prioritising like `sudo renice 19 28734` with the appropriate process numbers  for Guayadeque and Quod Libet, the minijail of bluetoothd, and the minijail of cras, cras itself, pulseaudio but so far I still experience the issue whenever anything's happening in Chromium. 

I've also tried the opposite - deprioritising Chromium like...

`ps aux | grep chromium | awk '{print $2}' | xargs -n1 sudo renice -19`

...but the breakups still occur.

Do I have to go down the route of changing the kernel scheduler to make this possible? Any other options I have?

Without solving this, I can't easily have audio in my office environment as almost any use of the chromebook causes breakups.

**Comment by drinkcat** [comment]
Do you have similar issues when playing audio on Chrome OS directly? Or is it just when playing from crouton?

Can you provide the output of `croutonversion`? Is `pulseaudio` running in the chroot?

**Comment by cefn** [comment]
I've encountered breaks in audio within Google's Play Music, and BBC's online audio player. It doesn't seem to be as easy to recreate there, however. Within e.g. Guayadeque, I can consistently recreate the problem by launching a rebuild in the Java-based software I use to edit javascript. However, this doesn't consistently affect playback in Google Play Music the same way. Somehow the ChromeOS media playback, isn't exposed to the CPU burstiness the same way.

This Crouton build is a fairly recently-updated LXDE Ubuntu Trusty. 

```$ croutonversion 
crouton: version 1-20150811114815~master:f6b810fe
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde-desktop,core,extension,keyboard
host: version 7077.134.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Sun Aug 16 14:03:22 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes```

I can see a process like ```/usr/bin/pulseaudio --start --log-target=syslog``` which I think proves pulseaudio is running.
