### ISSUE TITLE
Bugs with latest Crouton release

### ISSUE THREAD

**Issue by Fatal1ty93RUS** [dnschneid/crouton#2066]
Device: Asus C300
ChromeOS version: 45
Crouton version: latest 

So, basically I had my Ubuntu setup working percectly since ChromeOS v43, until a couple of days I go I attempted to update the chroot to reinstall the Unity's desktop apps, which have disappeared after unsuccessful attempt of fixing the input method switch

To do so, I used the -u(pdate) command from with Crosh terminal, and everything seemed to go well, until I saw (approximately) this:

The message said that my Ubuntu release (I had Trusty Tahr installed) has reached its EOL and is no more supported. Right after that I attempted to boot back into Ubuntu...and failed. 

So I deleted it and tried installing a newer version - no success, even if I got to successfully install the newer build, it would either get stuck on a black screen, or loaded up the desktop with no interface (this was the case with Vivid and Wily), also the touchpad did not work

Then I thought...well, screw it, I'll try Debian instead. Several attempts were unsuccessful, and all of them finished with message:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup
Unmounting...

So I assumed that I should execute that command from within chroot. My next step was:
sudo enter-chroot -n [chroot name]

And then I see this:
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d]

Obviously I agreed, and watched as the script was doing its thing and apparently downloading some additional stuff. Then I see another error:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in debian
Unmounting /mnt/stateful_partition/crouton/chroots/debian...

So I try to execute the enter-chroot command again - same error (UID 1000 not found)

Finally, I attempted to update the chroot and add xorg target so it, and lo and behold - I actually managed to launch Debian this time

The question is - is this just a one big bug I face due to possible incompatibility with ChromeOS 45, or did I add too many targets to previous chroot install? Or is it just because I didn't add the x.org target? 
If so, why did my original Ubuntu setup stop working after Crouton/chroot update?

**Comment by bhsnll** [comment]
+1
