### ISSUE TITLE
pulseaudio fails

### ISSUE THREAD

**Issue by wymby** [dnschneid/crouton#2069]
Since version :f6b810fe I've been unable to run pulseaudio -- it fails to find cras-sink and cras-source. Output from `pulseaudio -v` includes:
```
I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted
I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted
I: [pulseaudio] core-util.c: Failed to acquire high-priority scheduling: No such file or directory
I: [pulseaudio] main.c: This is PulseAudio 5.0
.....
I: [pulseaudio] module.c: Loaded "module-gconf" (index: #8; argument: "").
I: [pulseaudio] module-default-device-restore.c: Saved default sink 'cras-sink' not existent, not restoring default sink setting.
I: [pulseaudio] module-default-device-restore.c: Saved default source 'cras-source' not existent, not restoring default source setting.
I: [pulseaudio] module.c: Loaded "module-default-device-restore" (index: #12; argument: "").
I: [pulseaudio] module.c: Loaded "module-rescue-streams" (index: #13; argument: "").
I: [pulseaudio] module-device-restore.c: Restoring volume for sink auto_null: front-left: 45875 /  70%,   front-right: 45875 /  70%
I: [pulseaudio] sink.c: Created sink 0 "auto_null" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] sink.c:     device.description = "Dummy Output"
I: [pulseaudio] sink.c:     device.class = "abstract"
I: [pulseaudio] sink.c:     device.icon_name = "audio-card"
I: [pulseaudio] source.c: Created source 0 "auto_null.monitor" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     device.description = "Monitor of Dummy Output"
I: [pulseaudio] source.c:     device.class = "monitor"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
I: [pulseaudio] module.c: Loaded "module-null-sink" (index: #15; argument: "sink_name=auto_null sink_properties='device.description="Dummy Output"'").
I: [pulseaudio] module.c: Loaded "module-always-sink" (index: #14; argument: "").
I: [pulseaudio] module.c: Loaded "module-intended-roles" (index: #16; argument: "").
```

My .pulse/default.pa is a symlink to /etc/crouton/pulseaudio-default.pa, which looks correct (forwards audio to cras). Cras works (`aplay -Dcras - </dev/urandom`).

This is a Debian jessie chroot with x11 target on an Acer C710.  Suggestions?

**Comment by tista500** [comment]
@wymby,

I'm also tracking another pulseaudio issue on #2039, so how about making cras-sink manually:
```
pacmd unload-module module-alsa-sink
pacmd load-module module-alsa-sink device=cras sink_name=cras-sink
pacmd set-default-sink cras-sink
```
Line 1 might not be needed if you did not load...

Regards.

**Comment by wymby** [comment]
@tista500,

Thanks, but pacmd doesn't work, because pulseaudio failed to start.  Further down the `pulseaudio -v` output (which I somehow missed before):
```
E: [pulseaudio] module-console-kit.c: GetSessionsForUnixUser() call failed: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
E: [pulseaudio] module.c: Failed to load module "module-console-kit" (argument: ""): initialization failed.
E: [pulseaudio] main.c: Module load failed.
E: [pulseaudio] main.c: Failed to initialize daemon.
```
I (re)installed consolekit and everything works.  It still complains about finding cras, but discovers and loads it later.  I don't remember removing consolekit -- it was there in June; might the crouton update process have done it? I'm also puzzled because my non-crouton jessie system does not have consolekit installed, but pulseaudio works.

**Comment by tista500** [comment]
@wymby,

From the file-list of pulseaudio 5.0-13 of Jessie (stable): https://packages.debian.org/jessie/amd64/pulseaudio/filelist
Yes. `module-console-kit` was included exactly, but consolekit was not included in dependency-list of pulseaudio? If so, I suspect Jessie's packaging problem (upstream issue).

Regards.

**Comment by wymby** [comment]
@tista500,

I think you're right -- a somewhat confusing upstream dependency problem. I'll just keep consolekit installed..

Thanks.
