### ISSUE TITLE
How to only start chroot (and sshd) in background at Chrome OS startup?

### ISSUE THREAD

**Issue by lixiaoyan** [dnschneid/crouton#2071]
I used `START_DE=enter-chroot` in `crouton.init` but it seemed not worked well.
It often give me the error "PTY allocation request failed on channel 0" when I tried to connect to the ssh server.
Any way to let it works well?

**Comment by DennisLfromGA** [comment]
- Does the chroot open but your ssh daemon is just not starting?

> I used START_DE=enter-chroot in crouton.init but it seemed not worked well.

- What other entries are in your `crouton.init` file?

- Have you looked at the log file in `/tmp/crouton-$PID.log` for any clues ?

**Comment by lixiaoyan** [comment]
1. I added `sshd` to `/etc/rc.local` following the wiki, and it worked fine if I run "enter-chroot" manually. When it started by `crouton.conf`, I can login success, but it didn't give me the shell and print the error message above.

2. `crouton.init` just contains three lines:
  ``` shell
  DELAY=0
  CHROOT=linux
  START_DE=enter-chroot
  ```

3. And now... it cannot start.
  here is the full content of the log file: <https://gist.github.com/lixiaoyan/3f4261b3f3cf849a5d51>.

**Comment by DennisLfromGA** [comment]
@lixiaoyan - 

> And now... it cannot start.

I believe it is *starting* but it' also immediately terminating.
It seems `enter-chroot` needs something to do...

Try changing the START_DE value to:

`START_DE=enter-chroot sleep infinity`

and then see if it works.
Please let us know either way.

**Comment by lixiaoyan** [comment]
It works fine! Thank you!

**Comment by DennisLfromGA** [comment]
Your welcome.
I've added a few additional notes in '[crouton.init](https://gist.github.com/DennisLfromGA/aa1c92ebe77c3df4ca84)' about this for headless operatons, etc.
