### ISSUE TITLE
Setting a non-US keyboard layout

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2073]
I tried setting a non-US keyboard layout by following the [wiki instructions](https://github.com/dnschneid/crouton/wiki/Keyboard#non-us-layout). `setxkbmap -layout gb` works fine when I run the command in Bash but the change doesn't persist after system shutdown. Adding the command to `~/.xiwirc` didn't work for me. Do you have any suggestions?

I'm running Ubuntu 14.04, LXDE via Crouton.

**Comment by tista500** [comment]
@henrywright,

Is there a `autostart` file in `/etc/xdg/lxsession/LXDE/`?
If it exists, add your desired command to bottom line of that file.
I hope it worked...

Regards.

**Comment by henrywright** [comment]
Thanks for the tip but that didn't work for me either.

**Comment by tista500** [comment]
@henrywright,

OK. First you should rollback that modification above.
Then, the next is to create autostart file placed in `~/.config/autostart` like this:
* make a file with editor (i.e. nano, gedit leafpad etc...)
```
nano ~/.config/autostart/xkb.desktop
```
* paste this into a file above
```
[Desktop Entry]
Name=xkb
Comment=Change keyboard layout to gb
Exec=setxkbmap -layout gb
Terminal=false
Type=Application
NoDisplay=false
```
* save and exit editor
* logout and re-login into LXDE

Regards.
