### ISSUE TITLE
built-in U2F support

### ISSUE THREAD

**Issue by jeff-regier** [dnschneid/crouton#2074]
To get my FIDO U2F device to work in Crouton, every time I reboot I have to run these 3 commands: 

```
mkdir /run/udev/rules.d/
echo 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0120", OWNER="root", GROUP="devbroker-access", MODE="0660"' | sudo tee /run/udev/rules.d/999-securitykey.rules
sudo udevadm control --reload
```

(The `idVendor` and the `idProduct` are specific to the brand of my U2F device---a Yubikey. I get them by running `lsusb`.)

Could Crouton support U2F devices natively?

**Comment by tista500** [comment]
@jeff-regier,

I hope you could file a "feature-request" to ChromeOS devs, because udev should be maintained by upstream (ChromeOS), I think. :)

Regards.
