### ISSUE TITLE
Funny how a 15 minute delay in a script can add up to 17 hours: Minor bug

### ISSUE THREAD

**Issue by johmorrisbeck** [dnschneid/crouton#2075]
Could be a problem with ubuntu core so bear with me. I'll just give you plain steps

>grab acer c720
>go into dev mode
>download the main crouton script from git
>I used 'sudo sh ~/Downloads/crouton -t xiwi,core -r trusty -u', (after 17 hours of resetting my chromebook, going to dev mode, and trying new commands. I blame this in the xiwi documentation not being linked in the main crouton page)

If the issue happens for you with that command, then it should take about fifteen minutes to load any package transaction minimum. If you are running an acer c720 I would appreciate if you could try it out.

I asked very thoroughly in #Ubuntu and ##networking on freenode. The networking people had me try these commands

>ping -c 3 archive.ubuntu.com
>wget http://archive.ubunutu.com
>also loading archive.ubuntu.com in a websitie

In all three examples this works flawlessly.

Next time I am back on my home network I will try it, and in that case I will delete this report. Or whatever, this is my first git post.

I am willing to give you SSH into my machine but not for at least a couple days.

Thanks. I appreciate all you guys do for crouton.

**Comment by tedm** [comment]
whats the pwd ??

**Comment by johmorrisbeck** [comment]
Sorry for abandoning this. Pretty much consider it resolved. I am almost certain it was my network.
