### ISSUE TITLE
SSH into my Crhomebook/Crouton

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#2076]
I want to send files from my desktop Linux PC to my chroot on the Chromebook using SSH. The IP address of my Chromebook is 192.168.0.110. Usually I can do this:

`ssh 192.168.0.110`

And I will be asked for my password. But it prompts me the following error message:

`ssh: connect to host 192.168.0.110 port 22: Connection timed out`

And when I try to see what daemons are up on my Chromebook w/ the following command:

`sudo nmap -sS 192.168.0.100-120`

Then (after a l.o.n.g wait of 9 min)  I get the following message:

`Nmap scan report for 192.168.0.110`
`Host is up (0.011s latency)`
`All 1000 scanned ports are closed`

Does the Ubuntu 14.4 version in my chroot have a Firewall up or is this caused by ChromiumOS?

**Comment by tcagle** [comment]
Did you read and follow this on the wiki? ...
https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton

**Comment by MeneerJansen** [comment]
That Hat Trick did it for me! Thanks. :)
