### ISSUE TITLE
audio DTS, Dolby, 5.1

### ISSUE THREAD

**Issue by runppy** [dnschneid/crouton#2077]
Hello,

I'm running Precise under Crouton. I want to use my Toshiba chromebook 2 with a videoprojector and a 5.1 audio amplifier. Problem : the amplifier is old and don't support hdmi. Consequently I bought an audio extractor to send the audio to the amplifier using an optical spdif. I was expecting to have a 5.1 dolby signal but I only receive 2.0 (using kodi). 

My first question is : is it a hardware limitation ? If it is a software issue, do you know a solution ?

I just want to add that I have the same problem under Windows. It seems that Windows is discussing with the videoprojector who answers that it's only 2.0 compatible (stereo speaker on that benq W1070). COnsequently Windows only sends a 2.0 signal and I found no way to force the 5.1 signal... I was expecting Chrome OS and LInux to have a different behaviour but I didn't succeeded to find a solution...

If someone could help me....
THank you very much

runppy

**Comment by MeneerJansen** [comment]
Could be a hardware limitation of the "audio extractor" (do you have a web-link to the site where you bought the device or it's manufacturer)? HDMI is copy protected. That is: no device may forward the digital audio part. Except some televisions. Chances are that your audio extractor downmixes the signal to (analogue) stereo.

I feed the HDMI signal of my Raspberry Pi (haven't tried it w/ my Chromebook yet) to my LG television that has an optical output for audio. That optical cable is connected to my antique Dolby Digital / DTS capable Receiver. My receiver doesn't have HDMI inputs either. Beware: most TV's do not pass through DTS audio (some sort of copy right thingy). The only multi-channel audio I receive from the TV is DD5.1, But that's enough for me.

**Comment by drinkcat** [comment]
Looks like a Chromium OS bug, not sure if there is support for 5.1 audio in CRAS, especially via the ALSA plugin.
