### ISSUE TITLE
Restore taking unusually long time

### ISSUE THREAD

**Issue by Oliver84** [dnschneid/crouton#2081]
I'm trying to restore a Chroot to a USB 3.0 drive that is symbolically linked to my Chrome OS Chroot folder. I ran this thing all night last night and it still didn't finish. It gets up to like 7.5gb and then just hangs. The led on the usb still blinks so it looks like it's writing but I don't think it's suppose to take this long.

How long do Chroots usually take to restore? Would the symbolic link to USB 3.0 have something to do with it?

**Comment by drinkcat** [comment]
Some USB mass storage devices are slow...
