### ISSUE TITLE
X11 fails after last ChromeOS update

### ISSUE THREAD

**Issue by wymby** [dnschneid/crouton#2083]
After the recent ChromeOS update (7262.52.0), X11 (started via xinit) fails:

```
X.Org X Server 1.16.4
Release Date: 2014-12-20
...
Failed to open connection to "system" message bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE)
Fatal server error:
(EE) no screens found(EE)
...
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
```

The crouton version was already current (..:edbce112).  Re-running `crouton -u` didn't help. I have a Debian jessie chroot with an x11 target on an Acer C710.

**Comment by vsukul** [comment]
similar problem, cant start X either after new chrome os update.

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

(EE) 
Fatal server error:
(EE) Cannot move old log file "/tmp/Xorg.crouton.1.log" to "/tmp/Xorg.crouton.1.log.old"
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) 
^[[A^[[A/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by tista500** [comment]
@wymby,

Seems https://github.com/dnschneid/crouton/issues/335 happened again?

Regards.

**Comment by wymby** [comment]
Some similarities to #335, but not the same. And I haven't found a workaround for it...

**Comment by wymby** [comment]
Thanks @tista500, #335 got me digging further.  It appears to be a permissions problem -- xinit starts ok as root. If I do `chmod +s /usr/bin/Xorg` (or /usr/bin/xinit; neither of which should be necessary) and run as myself I get
```
(EE)
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
```
/usr/bin/X has correct permissions:
```
-rwsr-sr-x 1 root root 9468 Apr  1  2014 /usr/bin/X
```
Google finds similar symptoms, but no solutions.

**Comment by wymby** [comment]
A workaround: my script invokes xinit as root (via sudo), specifying an XINITRC file that sudo's back to me.  Works fine, but I shouldn't have to do that...

**Comment by divx118** [comment]
@wymby Did you try updating the chroot. If not, Revert your changes and follow https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by wymby** [comment]
Yes, the chroot was up-to-date. Downloading a new installer and re-updating had no effect.

**Comment by tedm** [comment]
Are you using an Asus 201? This is the only chromebook I have noted that Crouton is not currently working on: https://github.com/tedm/chromebook_notes/issues/1

**Comment by wymby** [comment]
No, it's an Acer C710.

**Comment by tedm** [comment]
Well if you try a new chroot with 12.04 and xfce, and it doesn't work, then I'll add the C710 to the list of chromebooks temporarily bricked by auto-updates.
