### ISSUE TITLE
xf86OpenConsole: VT_ACTIVATE failed: Permission denied

### ISSUE THREAD

**Issue by dreamwavedev** [dnschneid/crouton#2086]
Was trying to get Pantheon working on Trusty. Used the method here: http://bradmont.net/posts/2013-11-27-elementary-os-on-chromebook-acer-c7/ but came across a few problems after trying to boot the system. I get the same output whether I put in `sudo startxfce` or `sudo startelementary` and it goes as follows:

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/elementary...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Tue Sep 8 01:47:06 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=89b306d1-595c-3840-8ccf-eb90e5d84099/PARTNROFF=1 hashtree=PARTUUID=89b306d1-595c-3840-8ccf-eb90e5d84099/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=d179c9ed32d3d2a43502e44783a47a5379f0bc7b salt=75b10aba691f071dd0c9087eae35ae9ee7a88abefce29a02a1aa21fe35b8d4f6" noinitrd vt.global_cursor_default=0 kern_guid=89b306d1-595c-3840-8ccf-eb90e5d84099 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Sep 13 16:45:12 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Unable to open display lock file.
Unable to claim display lock
(EE) 
Fatal server error:
(EE) xf86OpenConsole: VT_ACTIVATE failed: Permission denied
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/elementary...
chronos@localhost / $

I'm quite a bit of a newb when it comes to both Linux and chrome, so I probably need a bit more instruction than some people here :/

Thanks in advance for any help.

**Comment by dnschneid** [comment]
Could you post the output of `sudo edit-chroot -al`?  Also, reboot once and try again and see if things work better.

**Comment by dreamwavedev** [comment]
I had deleted that Chroot but I can install it again (currently using this guide: http://jeanlouisnguyen.blogspot.ca/2014/01/guide-how-to-install-elementary-os-on.html) and see how things turn out. I'll check what that command spits out and post back here.
