### ISSUE TITLE
No audio, plus other ominous gibberish 

### ISSUE THREAD

**Issue by Zik-Nazouk** [dnschneid/crouton#2087]
I'm new to this, so forgive me. 
My mission to bring linux to my hp 14 chromebook has surpassed my intelligence and ability. Even this, my plea for help, is certain to violate convention. Whatever. Help the retard. 

Did everything you guys told me to. I think.

But when I go to start up the "chroot"

chronos@localhost ~ $ sudo startxfce4 -X xiwi
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Sep 8 01:53:03 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=f9a6ab0e-1f6f-de4a-9836-bcdfafaa143f/PARTNROFF=1 hashtree=PARTUUID=f9a6ab0e-1f6f-de4a-9836-bcdfafaa143f/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=8407b37c4a3cb09c08690bb837b5d307fe1ca31c salt=5a9f9bd17ca70b7ca3574cb251b0ea90b9b77686b606be2e839cceeea01ec821" noinitrd vt.global_cursor_default=0 kern_guid=f9a6ab0e-1f6f-de4a-9836-bcdfafaa143f add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Sep 13 18:25:57 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Unable to set master
xf86: found device 0
xf86: found device 0
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150827155505~master:edbce112
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xfce-desktop,xiwi,extension
host: version 7390.17.0 (Official Build) dev-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Sep 8 01:53:03 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
Error: target STRING not available
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:3950): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:3950): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
sh: 1: exec: jockey-gtk: not found
process 4019: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../dbus/dbus-message.c line 1263.
This is normally a bug in some application using the D-Bus library.

** (process:4097): WARNING **: killswitch.vala:103: Can't open /dev/rfkill for use as a killswitch backend: Permission denied

** (process:4097): CRITICAL **: bluez.vala:104: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez was not provided by any .service files
env: wrapper-1.0: No such file or directory
Loading configuration plugins

(xfce4-volumed:4148): xfce4-volumed-CRITICAL **: xvd_context_state_callback: The connection failed or was disconnected, is PulseAudio Daemon running?
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
blueman-applet version 1.23 starting
Stale PID, overwriting
Using gconf config backend
Using gconf config backend
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.25" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

Using gconf config backend

** (process:4106): CRITICAL **: volume_control_set_volume_internal: assertion '_tmp1_ == PA_CONTEXT_READY' failed

** (process:4106): CRITICAL **: file /build/buildd/indicator-sound-12.10.2+14.04.20140401/obj-x86_64-linux-gnu/src/volume-control.c: line 1775: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface (g-dbus-error-quark, 16)
Using gconf config backend
Using gconf config backend
Using gconf config backend
Using gconf config backend
Using gconf config backend
Using gconf config backend
Using gconf config backend

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

^[[B
** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

 
** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

** (process:4106): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

**Comment by DennisLfromGA** [comment]
@Zik-Nazouk - 

You installed the target 'extension' but have you also installed the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension from the chrome web store? Both are required for xmethod 'xiwi'.

If you've got both installed successfully, then you might want to try and update the chroot one more time just to make sure all is well with it before trying to enter your chroot again.

----

Also, something looks a little strange -

> chronos@localhost ~ $ sudo startxfce4 -X xiwi
Entering /mnt/stateful_partition/crouton/chroots/precise...

and 

> crouton: version 1-20150827155505~master:edbce112
release: trusty

The above seems to indicate that you have a chroot named 'precise' using a 'trusty' release.
Is that true? Did you upgrade the chroot from 'precise' to 'trusty' and just didn't get around to renaming it?  

One last thing, not that it matters but the '-X xiwi' really isn't necessary since 'xiwi' is the only xmethod intalled.

**Comment by Zik-Nazouk** [comment]
I appreciate the reply! Actually, installing the Web store crouton extension was the first thing I did. Confident about that, if nothing else. 
   And yes, whenever  the literature calls for "chrootname" I am substituting "precise".

**Comment by dnschneid** [comment]
What happens if you launch pulseaudio from a terminal inside xfce?

**Comment by Zik-Nazouk** [comment]
More baffling nonsense!

(precise)nickmasiuk@localhost:~$ sudo pulseaudio
[sudo] password for nickmasiuk: 
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
E: [pulseaudio] core-util.c: Home directory not accessible: Permission denied

**Comment by dnschneid** [comment]
Well, yeah, you're not supposed to run as root.

**Comment by Zik-Nazouk** [comment]
I gather? Here's it without:

(precise)nickmasiuk@localhost:~$ pulseaudio
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.

**Comment by dnschneid** [comment]
try `sudo killall pulseaudio` first.

**Comment by dnschneid** [comment]
And then reboot for good measure :)

**Comment by Zik-Nazouk** [comment]
reboot xfce, right? Or the whole damn mess?

**Comment by dnschneid** [comment]
The whole chromebook

**Comment by Zik-Nazouk** [comment]
(precise)nickmasiuk@localhost:~$ pulseaudio
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.
(precise)nickmasiuk@localhost:~$ sudo killall pulseaudio
[sudo] password for nickmasiuk: 
(precise)nickmasiuk@localhost:~$ pulseaudio
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.

**Comment by dnschneid** [comment]
What do you get out of `paplay -v /usr/share/sounds/alsa/Front_Center.wav`?

**Comment by Zik-Nazouk** [comment]
Good lord, it spoke!

(precise)nickmasiuk@localhost:~$ paplay -v
/usr/share/sounds/alsa/Front_Center.wav
Opening a playback stream with sample specification 's16le 1ch 48000Hz' and
channel map 'mono'.
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=192000, prebuf=190082,
minreq=1920
Using sample spec 's16le 1ch 48000Hz', channel map 'mono'.
Connected to device cras-sink (2, not suspended).
Stream started.
Playback stream drained.: 38113 usec.
Draining connection to server.
(precise)nickmasiuk@localhost:~$ paplay -v
/usr/share/sounds/alsa/Front_Center.wav
Opening a playback stream with sample specification 's16le 1ch 48000Hz' and
channel map 'mono'.
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=192000, prebuf=190082,
minreq=1920
Using sample spec 's16le 1ch 48000Hz', channel map 'mono'.
Connected to device cras-sink (2, not suspended).
Stream started.
Playback stream drained.: 31376 usec.
Draining connection to server.
(precise)nickmasiuk@localhost:~$


​

**Comment by dnschneid** [comment]
So...is anything still not working?

**Comment by Zik-Nazouk** [comment]
Well youtube is making noise, so progress! But Jack still won't boot up.

**Comment by dnschneid** [comment]
Jack is a totally different story.  See #1434

**Comment by Zik-Nazouk** [comment]
No good.

(precise)nickmasiuk@localhost:~$ sudo adduser nickmasiuk audio-hwaudio
> adduser: The group `audio-hwaudio' does not exist.
> (precise)nickmasiuk@localhost:~$ sudo adduser nickmasiuk audio-hw
> adduser: The group `audio-hw' does not exist.


Here's the Jack complaint:

19:29:50.908 Patchbay deactivated.
> 19:29:50.925 Statistics reset.
> 19:29:50.935 ALSA connection change.
> 19:29:50.947 D-BUS: Service is available (org.jackaudio.service aka
> jackdbus).
> 19:29:51.100 D-BUS: JACK server could not be started. Sorry
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> 19:29:51.144 ALSA connection graph change.
> Wed Sep 16 19:29:50 2015: Starting jack server...
> Wed Sep 16 19:29:50 2015: JACK server starting in realtime mode with
> priority 10
> Wed Sep 16 19:29:50 2015: ERROR: Cannot lock down 82274202 byte memory
> area (Cannot allocate memory)
> Wed Sep 16 19:29:51 2015: ERROR: control open "hw:3" (No such file or
> directory)
> Wed Sep 16 19:29:51 2015: ERROR: control open "hw:3" (No such file or
> directory)
> Wed Sep 16 19:29:51 2015: creating alsa driver ...
> hw:3|hw:3|1024|2|44100|0|0|nomon|swmeter|-|32bit
> Wed Sep 16 19:29:51 2015: ERROR: control open "hw:3" (No such file or
> directory)
> Wed Sep 16 19:29:51 2015: ERROR: ALSA: Cannot open PCM device alsa_pcm for
> playback. Falling back to capture-only mode
> Wed Sep 16 19:29:51 2015: ERROR: Cannot initialize driver
> Wed Sep 16 19:29:51 2015: ERROR: JackServer::Open failed with -1
> Wed Sep 16 19:29:51 2015: ERROR: Failed to open server
> Wed Sep 16 19:29:52 2015: Saving settings to
> "/home/nickmasiuk/.config/jack/conf.xml" ...
> 19:29:55.285 Could not connect to JACK server as client. - Overall
> operation failed. - Unable to connect to server. Please check the messages
> window for more info.
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started

**Comment by dnschneid** [comment]
hwaudio, not audio-hwaudio

**Comment by dnschneid** [comment]
Please look at that other issue and follow the linked wiki carefully.

**Comment by Zik-Nazouk** [comment]
Looks like I had already tried this:

(precise)nickmasiuk@localhost:~$ sudo adduser nickmasiuk hwaudio
[sudo] password for nickmasiuk:
The user `nickmasiuk' is already a member of `hwaudio'.
​
In any event, stopped and started cras
​
​

​chronos@localhost / $ sudo stop cras
> cras stop/waiting
> chronos@localhost / $ sudo start cras
>
> cras start/running, process 6302


​
Received the same error from Jack

19:39:36.927 D-BUS: JACK server could not be started. Sorry
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> 19:39:36.978 ALSA connection graph change.
> Wed Sep 16 19:39:36 2015: Starting jack server...
> Wed Sep 16 19:39:36 2015: JACK server starting in realtime mode with
> priority 10
> Wed Sep 16 19:39:36 2015: ERROR: Cannot lock down 82274202 byte memory
> area (Cannot allocate memory)
> Wed Sep 16 19:39:36 2015: ERROR: control open "hw:3" (No such file or
> directory)
> Wed Sep 16 19:39:36 2015: ERROR: control open "hw:3" (No such file or
> directory)
> Wed Sep 16 19:39:36 2015: creating alsa driver ...
> hw:3|hw:3|1024|2|44100|0|0|nomon|swmeter|-|32bit
> Wed Sep 16 19:39:36 2015: ERROR: control open "hw:3" (No such file or
> directory)
> Wed Sep 16 19:39:36 2015: ERROR: ALSA: Cannot open PCM device alsa_pcm for
> playback. Falling back to capture-only mode
> Wed Sep 16 19:39:36 2015: ERROR: Cannot initialize driver
> Wed Sep 16 19:39:36 2015: ERROR: JackServer::Open failed with -1
> Wed Sep 16 19:39:36 2015: ERROR: Failed to open server
> Wed Sep 16 19:39:38 2015: Saving settings to
> "/home/nickmasiuk/.config/jack/conf.xml" ...
> 19:39:42.315 Could not connect to JACK server as client. - Overall
> operation failed. - Unable to connect to server. Please check the messages
> window for more info.
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started


​What's D-Bus? It seems as though #1434's Jack instance had it working,
whereas mine does not.
