### ISSUE TITLE
so need fast help please

### ISSUE THREAD

**Issue by thatoneguy64** [dnschneid/crouton#2088]
sudo apt-get install wine1.6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wine1.6
E: Couldn't find any package by regex 'wine1.6'
(precise)welch@localhost:~$ apt-get install wine
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
(precise)welch@localhost:~$ sudo apt-get install wine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wine' has no installation candidate
(precise)welch@localhost:~$ sudo add-apt-repository git://source.winehq.org/git/wine.git
Error: 'git://source.winehq.org/git/wine.git' invalid
(precise)welch@localhost:~$ sudo apt-get install wine1.5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine1.5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wine1.5' has no installation candidate
(precise)welch@localhost:~$

**Comment by wuyuanyi135** [comment]
mine trusty ubuntu repository contains wine1.6

**Comment by thatoneguy64** [comment]
hmm mine says it does have one but by another name; i tried all of the wine versions, and it says there is no package with the regex <wineversionname>

**Comment by tista500** [comment]
@thatoneguy64,

Why didn't you run `sudo apt-get update` after adding PPA? If this lack causes your issue, you should post somewhere else like Ubuntu Forum with title "How to add wine on Precise". I don't think this issue was related to crouton at all...

Regards.

**Comment by thatoneguy64** [comment]
Did run sudo apt-get update after adding repository

**Comment by thatoneguy64** [comment]
still said the regex doesn't exist

**Comment by tista500** [comment]
@thatoneguy64,

Completely wrong:
> `(precise)welch@localhost:~$ sudo add-apt-repository git://source.winehq.org/git/wine.git`

Do like this:
```
sudo apt-add-repository ppa:ubuntu-wine/ppa
sudo apt-get update
sudo apt-get install wine1.6
```

Regards.

**Comment by thatoneguy64** [comment]
chronos@localhost / $ sudo sh ~/Downloads/crouton -t unity -u
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
unity target does not work in xephyr in trusty due to missing egl support.

**Comment by Kuifie** [comment]
@thatoneguy64 , I suspect this issue has to do with the secure boot preferences in your PC's bias boot settings interfering with the Wine Installation. I had to restart, log into my boot menu, change the boot method to "UEFI ... Secure Boot Off"
Then when running the sudo commands you show, Ubuntu Terminal suggested to run the following
`sudo dpkg --configure -a`

In short terms, this worked for me:
`sudo apt-add-repository ppa:ubuntu-wine/ppa
sudo apt-get update
sudo dpkg --configure -a
sudo apt-get install wine1.6`
