### ISSUE TITLE
If file in SD card is opened, close the lid then open causes it mount to another place

### ISSUE THREAD

**Issue by wuyuanyi135** [dnschneid/crouton#2089]
For example, /dev/sdb1 was originally mounted to /media/removeable/SD Card
I opened one file in atom, then closed lid, resume, /media/removeable/SD Card exists but /dev/sdb1 gone.  Instead it becomes /dev/sdc1 and mount to /media/removable/SD Card 1

I have seen many similar issues. I assume it is because when I close the lid the SD card is unmounted and remount when resume. If file in that device is opened, it can not be unmounted. Is there any way to force unmount the SD card before entering suspending? I tried write a script in /etc/pm/sleep.d/ but not work. It seems closing the lid does not actually bring the system to suspend or hibernate: my script is not called at all.

I always write my stuff in SD card, once it switch to another mount point I can no longer save file at original path. Can anyone give some advice?

Thanks

**Comment by wuyuanyi135** [comment]
Solved by:
echo 1 | sudo tee /sys/bus/usb/devices/power/persist

**Comment by thatoneguy64** [comment]
someone come help me with my weird issue lol
