### ISSUE TITLE
zombie XiWi process

### ISSUE THREAD

**Issue by emanuensis** [dnschneid/crouton#2092]
i had stretch/xfce installed with crouton integration. It ran ok, if slow on my HP14 w 4GB. Then it quit. But as i was soon to find it was undead. XiWi kept trying to "connect" with it - to no avail so far: 1) did a cold reboot 2) installed and ran (w/o XiWi) a new crouton (stretch/lxde) 3) wiped and reinstalled XiWi. Still the Zombie persists.

Anyway to kill off this Zombie and maybe start anew ... or reenter her and have a more gracious relationship anon?

**Comment by tista500** [comment]
@emanuensis,

This issue might be related to #2047...
So when you quit, you did "logout" the desktop environment properly?

Regards.

**Comment by emanuensis** [comment]
Thanks

No i did not logout properly, "it quit", meaning it closed its window interface to me. i would like to be able to reattach to that process. Or kill it.

**Comment by tista500** [comment]
@emanuensis,

As devs said above, xiwi doesn't send "close" signal via X11 handler today so, you might need to do somehow (I haven't a clue because I don't run Xiwi in a daily use)...

Anyway I agreed with devs, sending 'force-close' signal might lead some downside effects.

Regards.

**Comment by emanuensis** [comment]
So how do i find its `PID` so i can send a `SIGHUP` to it? There must be something the Crouton Integration process sees ... but cannot connect to. How do i find that?

**Comment by shanemikel** [comment]
How did you run your program in the chroot? (Did you use a shell, what was the command, etc)

**Comment by emanuensis** [comment]
`sudo startxiwi -n strx startxfce4` in a crosh window

**Comment by shanemikel** [comment]
Do you mean startx?

Btw, you shouldn't need to use startxiwi and startxfce4, you should only need to run 'sudo startxfce4' from the chromebook host.

Also, are you leaving the terminal open that owns the running xiwi process?

**Comment by emanuensis** [comment]
Prolly that would do as a shortcut, but i do not have enough experience with XiWi yet. Thanks. I do have a huge number of tabs open at most any time, so keeping track of a crosh window is problematic. (Especially as Chromes window changing mechanism is rather poor. Its animations are hard on the eyes and it lacks an overall summary) Likely that one was closed.

**Comment by shanemikel** [comment]
If you are running a desktop environment in your chroot (e.g. xfce), there are 2 common ways to close it.  The first, and best, is to use the xfce menu to logout the xfce session (this should stop the xfce session and xiwi processes gracefully).  The second is to close the xiwi window circumscribing the xfce session and sending a SIGINT to the xiwi process by pressing CTRL-C while focused in the terminal that is controlling the running process (The one you run startxfce4 in).

Also, I personally recommend using something like TMUX to start the xiwi/xfce-session process, so you can detach from the tmux session that has the terminal running xiwi/xfce-session (leaving you free to close the crosh window, and reattach with tmux in a new terminal later on)

**Comment by emanuensis** [comment]
Sure there are nicer ways to log out:-) Problem is i did not have a chance. Did not even want to. The window just disappeared and i cannot reconnect to it. i would be happy enough just `SIGHUP`ing the process. Is its name rumpelstiltskin;-)

TMUX is new to me. (`tmux` is not recognised by crosh) It sounds like a better way to bundle XiWi session ahead of time?

But i do need to either reattach or destroy the process.

**Comment by shanemikel** [comment]
You don't have a terminal with the process running open still?  How do you know it's running?

**Comment by emanuensis** [comment]
i do not "think" i have a GUI connection to the process - but ChromeOS's gui is pretty primitive at least to my eyes.

Clicking the `c` icon gives the error connecting. And reissuing another start request `sudo startxfce4' gives me a

`Cannot connect to extension, retrying...`

In the mean time clicking the `c` icon `1:strx`

**Comment by shanemikel** [comment]
A Terminal like crosh with the process running in the foreground (like the one you ran startxiwi in).. 

Either way, you could try looking for processes including crouton, xorg, or x11 in the name and killing them, (Xorg or xinitrc are good bets).  Otherwise you can restart the computer, but you could have another unrelated problem with your chroot.

**Comment by emanuensis** [comment]
`pidof xorg
pidof initrc
pidof x11`

all came up empty:-((

i HAVE cold booted my chromebook HP14 many times (i have been trying to get rid of this zombie for days:-).

Maybe i should leave the battery out for a few hours in an OFF state?

**Comment by shanemikel** [comment]
If you've rebooted (I'm no chromium os expert), then you don't have the process around anymore.  It looks like you've made some untrue assumptions about your issue (unless you can substantiate the claim that there is truly a rogue process).

Also, pidof is probably not the easiest command to use for this purpose.

**Comment by emanuensis** [comment]
i did cold boot several times, and i did the crosh test i mentioned above before i sent it out (ie it is not from memory but cut and paste from an actual immediate (ie NOW) session). Stronger proof involves physically bringing in the machine ... impractical.

For killing a process i have been using the guide at

`http://www.cyberciti.biz/faq/kill-process-in-linux-or-terminate-a-process-in-unix-or-linux-systems/`

If there is a better nix command than `pidof` i can use it?

As i said above, i visually scanned `ps aux`, and redid it again for the four terms you mentioned and found nothing obvious. But it is BIG.

**Comment by emanuensis** [comment]
i just used grep for your four terms ...

`ps aux | grep xorg

xorg      1374  0.1  0.2  46372 11672 tty1     S<s+ Sep13   9:15 /usr/bin/X -nohwaccess -noreset -maxvt 2 -nolisten tcp vt1 -auth /var/run/chromelogin.auth -logfile /var/log/xorg/Xorg.0.log

chronos  13306  0.0  0.0   6012  1040 pts/3    S+   18:17   0:00 grep --colour=auto xorg`

Perhaps 1374 or 13306 is it??:-)

**Comment by emanuensis** [comment]
Nah

`sudo kill -9 1374`

kills off my ChromeOS session:-(( Leaving the Zombie still in place.

**Comment by emanuensis** [comment]
@shanemikel

tmux would be very nice:) Much better than screen and would be great inside of ChomeOS. But a google of

`site:chromium.org tmux`

showed no hits except usage cases.

Do you have it running on your CB? (Ie NOT in a Crouton). If so how did you get it there?

**Comment by shanemikel** [comment]
If that is the only result you had from ps (within the four patterns), you don't have a crouton xiwi running.

Also, chromium.org will not tell you how to install tmux specifically, but how to install the tool (emerge) that will allow you to install a few things the chrome people have built for installation on chrome dev boxes.  If you don't get enough from chromium.org on how to use the emerge command, you need to head over to the Gentoo wiki, as that is the linux distro that chromium is built upon.  I AM using tmux on my chromebook, and that isn't related to crouton, so I'm not going to continue the conversation about general use of chrome/gentoo/linux here on the crouton bug tracker.

**Comment by emanuensis** [comment]
Following is the full CROSH session of an attempt to invoke the crouton in STRX. while i am running this the crouton integration module is actively displaying its attempts to `connect` to STRX. When it is finished i am not connected to anything.


        Welcome to crosh, the Chrome OS developer shell.
        
        If you got here by mistake, don't panic!  Just close this tab and carry on.
        
        Type 'help' for a list of commands.
        
        crosh> shell
        WARNING: Permission on /mnt/stateful_partition/etc/devmode.passwd is not 0600.
        WARNING: Please fix by running: sudo chmod 600 /mnt/stateful_partition/etc/devmode.passwd
        WARNING: You might also consider changing your password.
        chronos@localhost / $ sudo startxfce4
        Password:
        Entering /mnt/stateful_partition/crouton/chroots/strx...
        xprop:  unable to open display ''
        /usr/bin/startxfce4: Starting X server
        
        
        X.Org X Server 1.17.2
        Release Date: 2015-06-16
        X Protocol Version 11, Revision 0
        Build Operating System: Linux 4.1.0 x86_64 Debian
        Current Operating System: Linux localhost 3.4.0 #1 SMP Sun Aug 16 14:38:38 PDT 2015 x86_64
        Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9ae432f9-cab0-2f47-b562-30b013fc2c8f/PARTNROFF=1 hashtree=PARTUUID=9ae432f9-cab0-2f47-b562-30b013fc2c8f/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=8964eea391e19aa40d90e617bbbb37583a569ede salt=c5608c9216a49c1403e026d30d88d11f5b437cd41f06e535518d705ce5053a8c" noinitrd vt.global_cursor_default=0 kern_guid=9ae432f9-cab0-2f47-b562-30b013fc2c8f add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3
        Build Date: 11 August 2015  10:51:15AM
        xorg-server 2:1.17.2-1.1 (http://www.debian.org/support)
        Current version of pixman: 0.32.6
                Before reporting problems, check http://wiki.x.org
                to make sure that you have the latest version.
        Markers: (--) probed, (**) from config file, (==) default setting,
                (++) from command line, (!!) notice, (II) informational,
                (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
        (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Sep 18 08:01:50 2015
        (++) Using config file: "/etc/X11/xorg-dummy.conf"
        (==) Using system config directory "/usr/share/X11/xorg.conf.d"
        xf86: found device 0
        /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
        crouton: version 1-20150827155505~master:edbce112
        release: stretch
        architecture: amd64
        xmethod: xiwi
        targets: xiwi,xfce
        host: version 7077.134.0 (Official Build) stable-channel butterfly
        kernel: Linux localhost 3.4.0 #1 SMP Sun Aug 16 14:38:38 PDT 2015 x86_64 GNU/Linux
        freon: no
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Error: target STRING not available
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Cannot connect to extension, retrying...
        Unable to start display, make sure the crouton extension is installed
        and enabled, and up to date. (download from http://goo.gl/OVQOEt)
        Running exit commands...
        /usr/bin/xinit: connection to X server lost
        
        waiting for X server to shut down Hangup
        Hangup
        (II) Server terminated successfully (0). Closing log file.
        
        Unmounting /mnt/stateful_partition/crouton/chroots/strx...
        chronos@localhost / $

**Comment by emanuensis** [comment]
The good news is this Zombie does not exist anymore!-)

i let Google power wash the system by turning off/on developer mode. When it came back up the Zombie was gone (and everything else...).

The  power wash followed from the instructions at http://sites.google.com/site/chromeoswikisite/home/what-s-new-in-dev-and-beta/shell-acess-with-verified-boot used to get `tmux` and `emerge` and etc etc working. A very useful intro to dev use of a ChromeBook - better than most on the web!

If i can figure out how to get a server (http://jsoftware.com) going i may not even need a Crouton now.
