### ISSUE TITLE
Anyway to configure IPv4/6 settings for crouton's apt usage?

### ISSUE THREAD

**Issue by PastyPilgrim** [dnschneid/crouton#2093]
I've had trouble across all of my Linux machines (laptop, desktop, etc.) and all of my Linux distros (Mint, Ubuntu, Elementary, Chrome, etc.) when using apt. They all hang for 5-10 minutes when making the initial connection to the standard ubuntu package archives. Crouton attempts to reconnect to the archives a dozen+ times during various stages of chroot installation. This means that every chroot that I want to create will take 2-3 hours to complete (with Chrome constantly trying to go to sleep, so it needs constant attention).

I've gotten around this problem by changing /etc/gai.conf in all of my Linux installs so that IPv4 is used instead of IPv6. Is there any way to modify crouton to do the same?

**Comment by tista500** [comment]
@PastyPilgrim,

You meant the way of disabling IPv6?

The top-rated (temporary) method didn't work properly?
```
sysctl net.ipv6.conf.all.disable_ipv6 = 1
sysctl net.ipv6.conf.default.disable_ipv6 = 1
```

Regards.

**Comment by PastyPilgrim** [comment]
I'm sorry, I haven't seen this method. Where are these changes being made?

**Comment by tista500** [comment]
@PastyPilgrim,

Run those with `sudo` inside the chroot (but it's temporal way so reboot could reset this).

Regards.

**Comment by PastyPilgrim** [comment]
Wouldn't that just change the settings for that chroot? I want crouton to use IPv4 when installing chroots, I've already gotten my installs using IPv4 by editing gai.conf.

**Comment by tista500** [comment]
@PastyPilgrim,

Means "disabling IPv6 *during crouton install*"?
OK. those would work on crosh shell as well.

Regards.

**Comment by PastyPilgrim** [comment]
That does the trick, thanks.
