### ISSUE TITLE
Can't sudo startxfce4

### ISSUE THREAD

**Issue by DrAndrew667** [dnschneid/crouton#2094]
I've had crouton on my chromebook for a year and a half now, and I haven't had any issues. Now when I try logging into it, it comes up with this: 

Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

crosh> shell
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
Unknown username "dnsmasq" in message bus configuration file
/usr/bin/startxfce4: Starting X server

ERROR: ld.so: object '/usr/local/lib/croutonfreon.so' from LD_PRELOAD cannot be preloaded: ignored.
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Aug 31 21:52:04 PDT 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=e318115a-73f3-4943-9b78-7f19f04fb90a/PARTNROFF=1 hashtree=PARTUUID=e318115a-73f3-4943-9b78-7f19f04fb90a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=97f3c010c35a301da5b2bbdde594e7b5f33f1822 salt=d782623d84a02500514a17653b1a1870033555e7788eac299b0331b67c36042e" noinitrd vt.global_cursor_default=0 kern_guid=e318115a-73f3-4943-9b78-7f19f04fb90a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Sep 15 16:33:14 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $

**Comment by DrAndrew667** [comment]
Help would be awesome, thanks for reading.

**Comment by DennisLfromGA** [comment]
It may just require some updates, start with this - '[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)'.

**Comment by IAMBOB20** [comment]
I just did what you said @DennisLfromGA  with the common issues and reporting and i tried to do sudo startxfce4 but it still did work, it keeps saying something about not being unable to connect to X server: No such file or directory

**Comment by drinkcat** [comment]
Closing old issue, please file a new one if needed.
