### ISSUE TITLE
No sound, Unknown PCM pulse aplay: main:682: audio open error

### ISSUE THREAD

**Issue by lx1d** [dnschneid/crouton#2096]
I have a problem playing any sound inside crouton. I tried all the steps from https://github.com/dnschneid/crouton/issues/849 , but it is still not working. I tried updating crouton and playing ```aplay -Dcras /usr/share/sounds/alsa/Front_Center.wav``` and ```aplay -Dpulse /usr/share/sounds/alsa/Front_Center.wav```. Before updating crouton I couldn't connect to alsamixer (CRAS client wouldn't connect), but now it works. Playing ```aplay -Dcras /usr/share/sound/alsa/Front_Center.wav``` does play a sound but ```aplay -Dpulse /usr/share/sounds/alsa/Front_Center.wav``` doesn't. The error given is: ```ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM pulse
aplay: main:682: audio open error: No such file or directory```.

Croutonversion output:
```
crouton: version 1-20150827155505~master:edbce112
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 7262.52.0 (Official Build) stable-channel leon 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 31 21:55:58 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
and ```cras_test_client --dump_server_info```
```
System Volume (0-100): 100 
Capture Gain (-17.25 - 30.00): 20.00dB 
Output Devices:
	ID	Name
	8	HDA Intel PCH: ALC283 Analog:1,0
	7	HDA Intel MID: HDMI 2:0,8
	6	HDA Intel MID: HDMI 1:0,7
	5	HDA Intel MID: HDMI 0:0,3
Output Nodes:
	 ID	 Vol   Plugged	L/R swapped	      Time	Type		 Name
	8:0	  100       no	            no	         0	HEADPHONE        Headphone
	8:1	   88      yes	            no	1442383765	INTERNAL_SPEAKER*Speaker
	7:0	  100       no	            no	         0	HDMI             HDMI/DP,pcm=8 Jack
	6:0	  100       no	            no	         0	HDMI             HDMI/DP,pcm=7 Jack
	5:0	  100       no	            no	         0	HDMI             HDMI/DP,pcm=3 Jack
	5:1	  100       no	            no	         0	HDMI             HDMI
Input Devices:
	ID	Name
	9	HDA Intel PCH: ALC283 Analog:1,0
	4	Post DSP Loopback
	3	Post Mix Pre DSP Loopback
Input Nodes:
	 ID	Gain   Plugged	L/R swapped	      Time	Type		 Name
	9:0	    0       no	            no	         0	MIC              Mic Jack
	9:1	    0      yes	            no	1442383765	INTERNAL_MIC    *Internal Mic
	4:0	    0      yes	            no	         0	POST_DSP_LOOPBACK Post DSP Loopback
	3:0	    0      yes	            no	         0	POST_MIX_LOOPBACK Post Mix Pre DSP Loopback
Attached clients:
	ID	pid	uid
	39	16581	1000
Num active streams: 0
Last audio active time: 2652, 443572546
```
I did google for this type of error but couldn't find anything useful. Can someone please help me out?

**Comment by AurelienLourot** [comment]
Hi @lx1d, my sound got also suddenly broken after a Chrome OS upgrade that came on last Friday night. `alsamixer` was also failing with `CRAS client wouldn't connect`. I've just updated all my packages in the chroot (`sudo apt-get update && sudo apt-get dist-upgrade`), which didn't help, so I've just updated my chroot with `sudo sh crouton -u`. Everything is working again (both `aplay -Dcras` and `aplay -Dpulse`). 

The crouton version I now have is `1-20150917212109~master:0f6ce0bb`, which is newer than yours. Would you mind updating your chroot again and see if you still have the issue?

As stated in issue #2015, could you please also check that `pulseaudio` is installed? (`sudo apt-get install pulseaudio`)

Thanks for keeping us updated.

**Comment by lx1d** [comment]
Hi @AurelienLourot, this actually solved the problem. Thank you very much for the help.
