### ISSUE TITLE
Check gksu behavior on fresh installs

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2098]
#1900 and other situations suggest gksu’s default setting isn’t reliable.  This is possibly because gconf isn't actually bringing in the defaults.

Need to confirm the following:
1. On a fresh install, does gksu from xinit accept the sudo password (and not the root password)?
2. On a fresh install with xfce, does gksu from startxfce4 accept the sudo password?
3. On a fresh install with unity, does gksu from startunity accept the sudo password?

In all cases, if it doesn't accept the sudo password, `gconftool -s -t b /apps/gksu/sudo-mode t` should fix it.

If 3 works but 1 and 2 do not, investigate if launching xfce/lxde via gnome-session fixes things.

**Comment by austinbro1000** [comment]
I can confirm that #'s 2 and 3 work (on an Acer C720P, 4GB ram, Celeron 2957U), and running `gconftool -s -t b /apps/gksu/sudo-mode t` was not required in my case.

**Comment by austinbro1000** [comment]
I can confirm that #'s 2 and 3 work (on an Acer C720P, 4 GB RAM, Celeron 2957U), and running `gconftool -s -t b /apps/gksu/sudo-mode t` was not required.
