### ISSUE TITLE
question - how to keep chroot from sleeping 

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#210]
I am having trouble keeping the chroot from sleeping.

First, I have caffeine extension on the ChromeOS side to keep the screen and system awake, and am on AC power.

I type sudo stop powerm (lid), and sudo stop powerd.

I am wondering if the caffeine extension is failing in dev channel? 

What's the simplest way to keep the chroot always running? 

If a program is running actively (e.g. Byte unix benchmarks), and ChromeOS sleeps for any reason, should the chroot just stop? Is there a way for the chroot to tell ChromeOS to not go to sleep?

Once the chroot sleeps, for any reason, some server processes (sshd) don't come back, so hitting the spacebar on a sleeping ChromeOS, doesn't wake the chroot up to the exact state it was in before the forced suspend mode.

**Comment by nickpitlosh** [comment]
i think this has to do with the suspension of the xclients when vt switching, or at least that is my problem. how do you run everything concurrently?
