### ISSUE TITLE
README: add size tables for various examples

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2107]
It'd be useful to put some of the README examples in context by noting how big the resulting chroot is.

**Comment by DennisLfromGA** [comment]
If you coud expound a little that may be something I could look at.
Right now, I'm not quite sure what your meaning/intent is - sorry. :/

**Comment by dnschneid** [comment]
My bad.  There's a bunch of example crouton commands in the README.  I think there should also be a note near each command saying how large (in terms of `du -hs` on an unmounted chroot) the resulting chroot is, approximately.

**Comment by DennisLfromGA** [comment]
Okay, let me ponder on that then ;) Thanx.

**Comment by Alfriadox** [comment]
This may be old or outdated, but if this is still relevant, perhaps I could work on it? It seems easy enough

**Comment by DennisLfromGA** [comment]
@Alfriadox,

If you'd like to work on it that'd be great I think.

I believe it's still relevant and would be helpful.
I just haven't gotten around to looking at it I'm afraid.

-**DennisL**
