### ISSUE TITLE
Backup chroot

### ISSUE THREAD

**Issue by sherip99** [dnschneid/crouton#211]
The wiki says to use "sudo edit-chroot -b nameofchroot" to backup a chroot, but the "-b" option doesn't seem to be available on my Acer chromebook. It is in Developer mode, does it also have to be running Developer channel? I did try switching from Stable to Beta, (under Chrome, Settings, Help) but no joy.

**Comment by tedm** [comment]
downloaded the latest crouton, updated precise chroot, and also latest edit-chroot

from outside the chroot, with the chroot unmounted, I can't edit-chroot -b backup.tar.gz

it gives an error that the file doesn't exist

going to /usr/local/chroots and manually using tar works, but gives errors on locked files, and resultant tar.gz is about 1GB less than previous edit-chroot backups?

Anyone else having trouble with edit-chroot -b today?

**Comment by DennisLfromGA** [comment]
@tedm, It looks for the file in ~/Downloads unless you give it another path.

On Tue, Apr 28, 2015 at 4:04 PM, tedm <notifications@github.com> wrote:

> downloaded the latest crouton, updated precise chroot, and also latest
> edit-chroot
>
> from outside the chroot, with the chroot unmounted, I can't edit-chroot -b
> backup.tar.gz
>
> it gives an error that the file doesn't exist
>
> going to /usr/local/chroots and manually using tar works, but gives errors
> on locked files, and resultant tar.gz is about 1GB less than previous
> edit-chroot backups?
>
> Anyone else having trouble with edit-chroot -b today?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/211#issuecomment-97191366>.
>



-- 
*DennyL@GMail*

**Comment by tedm** [comment]
@DennisLfromGA I'm trying to create a backup with -b, so am using unique filenames with extensions of .tar.gz I'm not specifying a path, so am expecting it in ~/Downloads where previous backups have gone fine. 

I've downloaded and moved the latest edit-chroot, chown it as root:root ; chmod it to 77 and it still does not run, but this time with permission errors.

**Comment by DennisLfromGA** [comment]
@tedm - You're in the root '/' directory, is that where you want to be?
Also, prefix your edit-chroot command with `sh` -
`sudo sh /path/to/edit-chroot -b /path/to/mybackup.tar.gz`

**Comment by tedm** [comment]
ahh, I was running edit-chroot as a command, forgot the sh, thanks!!

weird that I got it to run partially though ??

**Comment by tedm** [comment]
@DennisLfromGA is working fine now with sh as root, but I think usage could be better, I kept assuming it would back my only chroot at the time (precise), and kept passing it the destination filename, knowing that it would go in ~/Downloads, but it wants the source name, and automatically generates the target destination and filename (precise-datecode-info), which is pretty good, but if the usage returned the proper usage when improper arguments are passed, that would be good. What do you think?

**Comment by DennisLfromGA** [comment]
I do agree with you about returning more info. in the usage blurb.
I have been contemplating bringing up this very subject with the higher powers but didn't want to bother them with this now in the midst of 'freon' rolling out and all the 'black screen' problems and such.

In the crouton scripts, there are comments for the tests that kick out the usage message, I think it would be a good idea to also kick out the comment contents of why the test(s) failed in addition to the usage message.
Some examples of this are:
```
# At least one command must be specified
if [ -z "$ALLCHROOTS$BACKUP$DELETE$ENCRYPT$KEYFILE$LISTDETAILS$MOVE$RESTORE" ]; then
    error 2 "$USAGE"
fi

# Need at least one chroot listed if not using -r with -f or -a.
if [ $# = 0 ] && ! [ -n "$RESTORE" -a -n "$TARBALL" -o -n "$ALLCHROOTS" ]; then
    error 2 "$USAGE"
fi

# Cannot specify a chroot and -a.
if [ $# -gt 0 -a -n "$ALLCHROOTS" ]; then
    error 2 "$USAGE"
fi

# -f without -r or -b doesn't make sense
if [ -n "$TARBALL" -a -z "$BACKUP$RESTORE" ]; then
    error 2 "$USAGE"
fi

# Cannot specify both backup and restore.
if [ -n "$BACKUP" -a -n "$RESTORE" ]; then
    error 2 "$USAGE"
fi

# Cannot specify delete with anything else.
if [ -n "$DELETE" -a -n "$BACKUP$ENCRYPT$KEYFILE$MOVE$RESTORE" ]; then
    error 2 "$USAGE
fi
```
Like in the first example, instead of just spitting out -
 `error 2 "$USAGE"`
Maybe it could be -
 `echo "At least one command must be specified" 1>&2`
 `error 2 "$USAGE"`

Just an idea but I think it might help users to understand sometimes why their command failed and they're getting the usage message.

**Comment by tedm** [comment]
@DennisLfromGA yeah, that would be good. For -b errors, this would be nice:

`echo "enter name of source chroot and optionally target directory or filename" 1>&2`
`error 2 "$USAGE"`
