### ISSUE TITLE
enter-chroot eats most signals

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2111]
Historically we had issues with enter-chroot eating signals and not passing it down the pid chain.  Is this still the case?

**Comment by shanemikel** [comment]
What kind of test are you looking for?

I've whipped up a couple shell scripts, not sure if this helps or not https://gist.github.com/shanemikel/51fa4172896e53c8dc0a

**Comment by shanemikel** [comment]
also tried this:
```
#!/bin/bash

trap 'echo "trap2.sh: caught TERM" && exit' SIGTERM
trap 'echo "trap2.sh: caught PIPE" && exit' SIGPIPE
trap 'echo "trap2.sh: caught INT" && exit' SIGINT
trap 'echo "trap2.sh: caught HUP" && exit' SIGHUP

while true; do sleep 0.5s; done
```
and running `sudo enter-chroot ./trap2.sh`, finding the process for the enter-chroot command, and signalling that process with kill.  The signals did NOT get passed to trap2.sh for ANY of the signals

**Comment by dnschneid** [comment]
Okay, that's what I thought.  I think we need to pass those signals on, since `enter-chroot` is supposed to behave like the command it is told to run.
