### ISSUE TITLE
croutonurlhandler should work without X server

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2113]
croutonurlhandler does not work without an X server, since croutonclip is not started, and does not fail with a clear message: it times out.

**Comment by dnschneid** [comment]
From #2161: we should fix the pipe permissions and autorun the daemon as an unprivileged system user as part of the glorious enter-chroot script.

**Comment by radix** [comment]
fwiw, it seems that the timeout bug is fixed? I can run croutonwebsocket from a CLI. but I suppose this should still be automated in enter-chroot so I don't need to start it myself.
