### ISSUE TITLE
Add edit-chroot -u for updating chroots

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2115]
`edit-chroot -u` should download crouton (once) and updates the chroot(s).  Either explicitly list chroots or use -a to update everything.

**Comment by DennisLfromGA** [comment]
pie???

**Comment by dnschneid** [comment]
Possibly. Give it a shot and let me know :)

**Comment by DennisLfromGA** [comment]
Will do.

**Comment by DennisLfromGA** [comment]
I have a home-grown script that does someting similar but I'd have to incorporate it in to `edit-chroot`.

**Comment by tedm** [comment]
how about an -s switch for "safety mode" - if -s is specified, copy the working chroot and crouton to ~/Downloads/backup/ and append the backup chroot name to chrootname_backup

then an -r restore mode, if the newly updated crouton and chroot give a blank screen or other odd behavior, -r reverts to a working system, then "echo, it almost worked, try next week..."

**Comment by DennisLfromGA** [comment]
@tedm - `edit-chroot` already has a 'backup' and 'restore' option, why not use them?
```
    -b          Backs up the chroot to a tarball. Compression format is chosen
                based on the tarball extension. Backups always take place before
                other actions on a given chroot.
    -r          Restores a chroot from a tarball. The tarball path can be
                specified with -f or detected from name. If both are specified,
                restores to that name instead of the one in the tarball.
                Will not overwrite a chroot when restoring unless -r is
                specified twice.
```
