### ISSUE TITLE
Speed up xiwi launching

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2118]
xiwi takes forever to launch (and sometimes it fails).  We need to speed it up significantly.  The main issue is in somehow notifying the extension that the websocket server is ready for connections.

One possibility: have a hidden pnacl process that then gets found and killed by crouton after the websocket is ready.

**Comment by jmaris** [comment]
This is something i've noticed a lot, the proposed solution seems like a good one.
