### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by rinkebab** [dnschneid/crouton#2123]
hello smart devs,

i'm a school boy 14 years old i got a laptop from school to work on i did get premissions to go and have funn with it so installed ubuntu trusty tahr 14.04 lts on my acer c720p WORKS GREAT. but i had a few thing i wanted to do to make usage more efficient and faster 
i am kinda noob

so i had a few questions 

1: can i run chrome from chrome os in the chroot because if i need to install it twice it takes more RAM and memory and we only have 32 gb and i had a really hot laptop after using chrome in the chroot

2: can i use the F5 button to see workspaces like in chrome os ( but then with windows ) 

3: can i change the vt switch button because i searched for option 1 i didn't find anything so i tought i swtich the button to alt gr i never use alt gr and i can switch fast to chrome but i struggeled a bit with the  xbindkeys file but it wont work :(

4: can i have the wifi indicator on my ubuntu panel so i can see to wich wifi i am connected ( it would even be greater if i can connect to the networks via the chroot but i think that isnt possable because the root premmisions and stuff  )

5: can i have the nautilus kinda file explorer with al the folders and locations in chrome os ( or even better in de chrome file manager ) because i don´t like that i only can see the downloads folder :(   )

6: can i have gnome shell 3+ or KDE plasma or Unity 8 ?

7: UBUNTU 15.04? vivid wont install 

i had a few more questions than i tought xD

i am a noob i can't break the chromebook because it is for school 
and i am not goning to delete chrome os. i asked if i could do that but i wasn´t allowed ... :(

i hope you can help me or anything 

sorry for my bad inglish i´am dutch  soo yeah

stuff you guys maybe need 

crouton: version 1-20150917212109~master:0f6ce0bb
release: trusty
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,xorg,unity,touch,audio,gtk-extra
host: version 7262.52.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 31 19:53:26 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

i use the command for xorg : sudo startunity -X xorg 
but i wanted to copy and paste between the 2 for teminal thingies and not have 2 the same browsers 

thanks for your help

(ps if you coudnt understand my inglish tell me i ty to translate it again but better i guess xD

**Comment by Alfriadox** [comment]
Hello! Glad you are asking.

1. No You cannot, use the keyboard command to switch. (Ubuntu does not have much access to chrome) or (since you are using xiwi) just esc out of fullscreen 

2. No you cannot use the f5 to do that, unless you find a keymapping command for that. look up xmodmap.

3. VT switch is crlt+alt+shift+f1

4. Maybe you could look for an app?

5. No.

6. I don't think so.

7. Try updating crouton.


copy and pasting: install extension target.

thanks.
