### ISSUE TITLE
Are cli-extra and startcli still needed/used?

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#2124]
With the advent of Freon on most or maybe all Chromebooks/boxes now, do we still need the cli-extra target and the host-bin/startcli scripts? 

If not, they should probably be retired and the [README](https://github.com/dnschneid/crouton/blob/master/README.md#i-dont-always-use-linux-but-when-i-do-i-use-cli) updated to just use `enter-chroot` for command line operations instead.

**Comment by dnschneid** [comment]
`cli-extra` is still useful, but startcli should indeed be just a symlink to enter-chroot now.

**Comment by DennisLfromGA** [comment]
Sounds good. 
I re-read the README and it looks like it's worded just fine once `startcli` is linked to `enter-chroot`.

**Comment by dnschneid** [comment]
`startcli` lives!  We should take advantage of the [new VT-like dbus messages](https://code.google.com/p/chromium/issues/detail?id=445003#c6).

**Comment by DennisLfromGA** [comment]
That is great news!

@drinkcat - ...and now that vt's are alive and well again, maybe revisit/revive crispy (ChRoots In a Seperate Partition - Yay) crouton ???
