### ISSUE TITLE
crouton update won't succeed with both xephyr and Freon

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#2125]
I know [Issue 2018 'Crouton update broken (again) ....'](https://github.com/dnschneid/crouton/issues/2018) is *closed* but the resolution left a lot to be desired. 
Would something like [this proposed change](https://github.com/dnschneid/crouton/compare/master...DennisLfromGA:patch-5) be worth considering? If so, I'll submit a PR.

**Comment by dnschneid** [comment]
Yeah, that would be good until we remove xephyr entirely.

**Comment by DennisLfromGA** [comment]
Cool, PR submitted: https://github.com/dnschneid/crouton/pull/2128

**Comment by dnschneid** [comment]
Okies, this should be fixed then.

**Comment by DennisLfromGA** [comment]
Thanx for the merge :+1:  ;)
