### ISSUE TITLE
sudo start broken, please help :)

### ISSUE THREAD

**Issue by joejoepojoe** [dnschneid/crouton#2127]
![screenshot 2015-09-21 at 8 40 52 pm](https://cloud.githubusercontent.com/assets/14627211/10002970/06d2b370-60a2-11e5-8ebf-62c684d33a19.png)
![screenshot 2015-09-21 at 8 41 00 pm](https://cloud.githubusercontent.com/assets/14627211/10002985/172a5c96-60a2-11e5-9312-f93ba5a98ae5.png)

**Comment by tonyxue** [comment]
As it prompts, you should set the owner of ```/tmp/.X11-unix``` back to your own user, not root.
