### ISSUE TITLE
Keyboard and mouse stop working during crouton "install".

### ISSUE THREAD

**Issue by JoshMcCullough** [dnschneid/crouton#2133]
I've been trying to re-create my chroot (trusty) on my Pixel (2), but every time it gets to the step where I enter a username for the primary user, my keyboard and/or mouse stop working! So I can't get past this step.I have to force-shutdown and start over. I tried with just the minimal install:

    sudo sh crouton -r trusty -t core,cli-extra

And I still can't input a username. In the latest case, the mouse works but the keyboard does not. Any suggestions?! At this point it seems like there's no way for me to get trusty installed again!

**Machine Info**
- Google Pixel 2 (i5)
- Just powerwashed, on Beta channel.

**Comment by jessietn** [comment]
I had the same problem.  Once you get to the spot asking for the username, shutdown your computer and reboot it.  Then, when back at the shell, enter
`sudo enter-chroot -n trusty`
assuming your chroot is named trusty.  It will detect it did not complete and ask if you want to continue.  Answer yes and it will scroll a bit then ask for your name again.  It will finish now.

This is not a good solution, but it does work.

**Comment by JoshMcCullough** [comment]
Awesome, trying that now -- thanks!

**Comment by JoshMcCullough** [comment]
Success. Not sure why it happened originally, seems like a bug, so I'll leave this open.

**Comment by jessietn** [comment]
Glad to hear.  I had just assumed it was mine acting up.

**Comment by tista500** [comment]
This issue seems an exact duplicate of this bug: #1994 
So I hope you guys let this close and post your issues to original one... 

Regards.

**Comment by dnschneid** [comment]
Thanks for flagging :)

**Comment by JoshMcCullough** [comment]
Thanks, couldn't find that one.
