### ISSUE TITLE
I want to run a kali sana chroot as root?

### ISSUE THREAD

**Issue by TyJoKo** [dnschneid/crouton#2135]
Me and my friend are both running Asus C200s and both have kali sana installed on a flash drive, and both need to access root. I am able to type `sudo startkde -u root` and successfully enter the chroot graphically under the root user. When he types the identical command, it says not to run it as root, and kicks him back out. How can this issue get resolved?

**Comment by dnschneid** [comment]
You're running it from the crosh shell.  Your friend is running it from the enter-chroot shell.

Why are you running a graphical desktop as root, anyway?  Just run only the things you really need as root using gksudo...
