### ISSUE TITLE
I downloaded crouton but crosh won't open it

### ISSUE THREAD

**Issue by joeman720** [dnschneid/crouton#2137]
it has been happening for weeks now. I tried everything. I thought it would be fixed by now but it is not. What am I doing wrong
![screenshot 2015-09-25 at 4 22 19 pm](https://cloud.githubusercontent.com/assets/13873303/10111403/c6fe88a2-63a1-11e5-9be8-1b9f73448c06.png)
![screenshot 2015-09-25 at 4 22 32 pm](https://cloud.githubusercontent.com/assets/13873303/10111406/ca9a3970-63a1-11e5-8360-94322e978757.png)

**Comment by DennisLfromGA** [comment]
Re-download '[crouton](https://goo.gl/fd3zc)' and try again:

 `sudo sh ~/Downloads/crouton -r list` 

(you don't need to add the '-e', it's now done internally.)

If that works, then try again:

`sudo sh ~/Downloads/crouton -r trusty -t unity`

**Comment by joeman720** [comment]
still not working

**Comment by DennisLfromGA** [comment]
> still not working

Can you please be a little more explicit, give us some more to go on so we can help you?

Have you changed your Downloads location in Settings?
The default is *Downloads* - like so -
![screenshot 2015-09-26 at 3 27 44 pm](https://cloud.githubusercontent.com/assets/3418772/10119430/79b883a0-6463-11e5-87f2-0069bdde2499.png)

If *Downloads* is your default like shown above, what do you get when you enter: 

`ls -l ~/Downloads/crouton`

The below is a typical display (on my system) -
```
chronos@localhost ~ $ ls -l ~/Downloads/crouton
-rwxr-x--x 1 chronos chronos 3.6K Jul  6 13:31 /home/chronos/user/Downloads/crouton
```

Once you get something similar to the above, the 'crouton' install command should work.

**Comment by walker12001** [comment]
are you updating it or installing it for the first time

**Comment by joeman720** [comment]
neither

**Comment by brmbrmcar** [comment]
Problem with sudo itself, looks like.
