### ISSUE TITLE
Asus flip Server terminated with error (1)

### ISSUE THREAD

**Issue by googites** [dnschneid/crouton#2139]
I am very novice to the world of Linux and have tried practically every solution, but I can't seem to solve this issue. I installed crouton with kde precise on a Asus flip Chromebook wih the rockchip soC processor. I under stand the the rockchip has had difficulties in the past, but the solutions suggested don't seem to work.   

This is the result of startkde:

Entering /mnt/stateful_partition/crouton/chroots/precise...

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Sun Aug 16 14:25:37 PDT 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=6e8d32a4-4e7d-8849-85bb-9bc746db160e/PARTNROFF=1 hashtree=PARTUUID=6e8d32a4-4e7d-8849-85bb-9bc746db160e/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=c98748e9f40ab55a98d1d54cf311bfcc6233fce5 salt=64acc1468d4995c8170b85286001ab3b5b9a03b95b82bb86da41c5d1741e985c" noinitrd vt.global_cursor_default=0 kern_guid=6e8d32a4-4e7d-8849-85bb-9bc746db160e  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Sep 26 22:01:59 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.

**Comment by heri** [comment]
I have the same error. Trying again with `sudo enter-chroot startxfce4` freezes the computer. I had to re-install chromeOS all over again

**Comment by dnschneid** [comment]
Fixed in the latest crouton.
