### ISSUE TITLE
Mouse moving doesn't work

### ISSUE THREAD

**Issue by cnicodeme** [dnschneid/crouton#214]
Hi!

I just installed Unity via crouton and called `sudo startunity` which perfectly loaded me Ubuntu, but I can't move the mouse.

I can right click (the context menus shows), close it (via esc), but I can't move my mouse (I can't say if I can left clic).

I tried going back to ChromeOs and then regoing into Ubuntu, but the mouse still don't move.

For information, I use a HP Chromebook 14 with the original mouse (not a plugged USB one). With an external mouse (USB), it works greats!

Is there something I am missing ?

After some trying it appears the mouse is moving, but I have to press really hard on the touchpad to make it move, and the behavior is not great at all.

**Comment by dereckson** [comment]
In December 2014, on an Asus C200, installing Unity on the top of a chroot with Ubuntu Trusty, all worked fine.

Recently, powerwashed, with the last Crouton version, I have a queer behavior with the touchpad, not affected by the synclient FingerLow=1 FingerHigh=5.

* No cursor move is achievable with one, two or three fingers
* Left and right click replies (but not tap)
* When I left or right click, and maintain this tap pressed, I can move the cursor with a correct sensitivity, but only if I use two fingers.
* Triple finger click seems to be recognized too.

**Comment by davidthewatson** [comment]
@dnschneid I'm running on Acer Chromebook 14. I installed crouton from the link on the github repo today 5/6/2016 and installed xfce-desktop on trusty with every extension except keyboard. I had the same problem described here evidenced by the fact that the touchpad responded to clicks fine but would not move unless I I used my palm as if it was my finger. The touchpad worked fine using my palm as a finger, but that is obviously not an effective prosthetic! My problem was solved by:

    synclient FingerLow=1 FingerHigh=5

at which point the touchpad works perfectly. Wasn't sure if you wanted to re-open this bug and address it in crouton since the Acer Chromebook 2014 just started shipping from Amazon a few days ago.

**Comment by CreepGin** [comment]
Just got the Acer CB14 and I can confirm the same problem described by @davidthewatson above.

**Comment by JonathanNagy** [comment]
I have the same problem on a Acer CB3-431 (Aluminum 14"),though maybe less severe that some.  Touchpad Input responds intermittently, but touchpad hardware click functions work fine.  Fixed with "synclient FingerLow=1 FingerHigh=5".

**Comment by haithcockce** [comment]
HP Chromebook 12 G1, 
The `synclient` command worked for me as well.

**Comment by iansltx** [comment]
HP Chromebook 13 G1 has the same issue (as did the Chromebook 14 G1, heh).

**Comment by taktak** [comment]
ASUS c202 has the same issue and same fix.

**Comment by XtrmJosh** [comment]
Lenovo N22 same issue and same fix - is there any chance this fix can be somehow built in? I have literally no idea how this stuff works otherwise I'd consider raising a pull myself.

**Comment by DennisLfromGA** [comment]
Wow, looks like quite a few models are being bitten by this touchpad issue.

Maybe the [`chroot-bin/croutonxinitrc-wrapper`](https://github.com/dnschneid/crouton/commit/2909da0fd8f2fcce255aa4169dedc5c4c20e1d0b#diff-09f1b13720f5c0eb6d62a572f8011876R73) script could be updated to include:

- falco ([HP Chromebook 14](https://github.com/dnschneid/crouton/issues/214#issue-15396955))
- peppy ([Acer C720](https://github.com/dnschneid/crouton/issues/214#issuecomment-26631279))
- edgar ([Acer Chromebook 14](https://github.com/dnschneid/crouton/issues/214#issuecomment-217562412))
- chell ([HP Chromebook 13](https://github.com/dnschneid/crouton/issues/214#issuecomment-228248193))
- terra ([ASUS Chromebook C202SA](https://github.com/dnschneid/crouton/issues/214#issuecomment-232345773))
- reks ([Lenovo N22 Chromebook](https://github.com/dnschneid/crouton/issues/214#issuecomment-232489158))

There may be others too I guess.

**Comment by XtrmJosh** [comment]
What impact does changing these values on a machine that's working out of the box? Has anyone got one they can try it on? If the impact is nil (unlikely, but it could be), might be worth just running this change by default. There's a huge scope for testing to see how different machines respond to it.

**Comment by lenniea** [comment]
synclient FingerLow=1 FingerHigh=5 works like a charm on my Acer Chromebook 14 (all aluminum)!  Thanks,
Lennie

**Comment by IlIlIlIlIlIlIl** [comment]
Same issue with *CAVE* model (Asus C320CA) using Xenial. Had to enter Synclient FingerLow=1 FingerHigh=5.

Touchpad seems to be disabled in ChromeOS while crouton is running, I havent been able to address that

**Comment by gardwired** [comment]
asus c302ca intel m3
figured out trackpad sensitivity as above.  defaults were 25/30.  set them to 12/15 much better.  still very, very laggy usb mouse.

**Comment by mprajescu** [comment]
HP Chromebook 11 G5 has the same issue. Running the `synclient FingerLow=1 FingerHigh=5` command worked like a charm.

**Comment by legel** [comment]
Just for the @gardwired, @IlIlIlIlIlIlIl and others running the Asus C320CA, the fix also worked for me with no major problems elsewhere on a Trusty.

**Comment by IlIlIlIlIlIlIl** [comment]
@legel you don't have issues with the trackpad *in chromeOS* when crouton is running? Mine seems to be disabled 90% of the time, it sometimes works for a while

**Comment by fuho** [comment]
Same issue on Pixelbook.
`synclient FingerLow=1 FingerHigh=` fix works.

**Comment by DennisLfromGA** [comment]
@fuho,

For the Pixelbook trackpad workaround see this issue:

- Pixelbook trackpad sensitivity #3487

*Hope this helps,*
-**DennisL**

**Comment by onevalidboi** [comment]
For my Lenovo N22 Chromebook the `synclient FingerLow=1 FingerHigh=5` command doesn't work. it gives me the error `bash: synclient: command not found`.

**Comment by DennisLfromGA** [comment]
`synclient` appears to be in Ubuntu 18.04 Bionic Beaver:
- http://manpages.ubuntu.com/manpages/bionic/man1/synclient.1.html

If it doesn't have it maybe try installing `xserver-xorg-input-synaptics`.

*Hope this helps,*
-**DennisLfromGA**

**Comment by RobertKirk** [comment]
When I try this with xenial on HPx2 Chromebook/tablet, synaptics is installed but says
`Couldn't find synaptics properties. No synaptics driver loaded?`

**Comment by DennisLfromGA** [comment]
@RobertKirk,

See if this helps:
- [synclient does not find synaptics properties despite Synaptics Touchpad in xinput list](https://unix.stackexchange.com/questions/210144/synclient-does-not-find-synaptics-properties-despite-synaptics-touchpad-in-xinpu)

*Hope this helps,*
-**DennisLfromGA**

**Comment by RobertKirk** [comment]
unfortunately I don't have a synaptic touchpad listed. I tried that link anyway and it didn't seem to work. The touchpad produces scroll events rather than moving the mouse. If i drag 2 fingers it tries to zoom in or out in firefox, so it must b somhow sending input, but ot the right kind. Also clicking creates a click, it's just the movement which is interpreted as scrolling.
```❯ xinput list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Google Inc. Hammer                        id=8    [slave  pointer  (2)]
⎜   ↳ WCOMCOHO:00 2D1F:4876                     id=9    [slave  pointer  (2)]
⎜   ↳ WCOMCOHO:00 2D1F:4876 Pen                 id=10   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Google Inc. Hammer                        id=7    [slave  keyboard (3)]
    ↳ cros_ec_buttons                           id=11   [slave  keyboard (3)]
    ↳ kblrt5663max Headset Jack                 id=12   [slave  keyboard (3)]```

**Comment by justchen1369** [comment]
this fixed low touchpad sensitivity on banon in a bionic install.
