### ISSUE TITLE
Android chroot environment

### ISSUE THREAD

**Issue by WiWa** [dnschneid/crouton#2140]
Would this be possible? It'd be sick to have people start using their chromebooks as superpowered android tablets.

**Comment by mark-hahn** [comment]
> start using their chromebooks as super-powered android tablets.

Google announced a while ago that they are supporting android apps on
chromebooks.  So far there aren't many.

**Comment by dnschneid** [comment]
See #972 and maybe even #83.

Basically, as far as I know, Chromium OS's kernel is missing stuff needed for running Android's system services.  Android doesn't use X11 either, so integration is difficult.  You're welcome to try running a system image and report back on your findings, though.

**Comment by rinkebab** [comment]
soo it isnt posable ?

if you could run android with limited features it would be cool already 

i think it is worth a shot 
 i'm i school boy so i aint have time to figure it out 

IT WOULD BE REALY USEFULL
