### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by rinkebab** [dnschneid/crouton#2142]
Hey !

is there a way you can add android 5.0 or 4.4 to the chroot .i know loads of apps already support chrome os arc with arc welder ect. but i have an app for my tv network but it wont work on arc and i just like to have android 

(could it be rooted if it is already possable )
it would  be freaking nice 

THANKS FOR YOUR HELP

**Comment by mark-hahn** [comment]
> i just like to have android

Can Android run on the ChromeOS kernel?  I doubt it.

**Comment by stephengale801** [comment]
I was just searching for the possibility for this as well.  I think that adding an Android target/chroot.
There are chroots for Android to use gentoo\Ubuntu\debian on your Android device - I don't see why Android wouldn't be able to run on the ChromeOS kernel... but I've not looked too far into it.

**Comment by dnschneid** [comment]
Dupe of #2140
