### ISSUE TITLE
"[Directory] Already Exists" Error while trying to move a Chroot

### ISSUE THREAD

**Issue by RavenSteam** [dnschneid/crouton#2147]
Good day/evening,

After attempting the same thing for almost 10-30 minutes, and almost throwing my computer out the window in the process, I'm trying to collect myself enough to post to here, so I won't have to do so.

Due to limited space on the Chromebook, I wanted to move my Chroot installation into my Ext4-Formatted USB Drive, to free up space and the like. After making it read and writable, one of the earlier error messages through attempting the usage of the command below, I try again, getting an error message saying the directory I'm trying to move it to already exists, an error message that makes absolutely no sense to me.

Command: "edit-chroot trusty -m [Directory]" and "edit-chroot -m [Directory] trusty" were both attempted.

I just want to know how to solve this, as soon as it's possible to do so, as I have a fair bit of work dependent upon the Chroot, and eventual dependency on its existence on the USB Drive.

Appreciations in advance!

**Comment by dnschneid** [comment]
Any chance you could print out the exact error?  Does it fail on the same file each time you try?  If so, could you run `ls -l` on that file?

**Comment by RavenSteam** [comment]
Sadly, I have since removed the entire chroot, as I realized that moving it to a USB Drive would make it slower, and not do much for me in the first place.

However, that was the error, I'm fairly certain pretty exact.

**Comment by Alfriadox** [comment]
Sorry you had to remove your chroot.
This issue can probably be closed now.
