### ISSUE TITLE
Can't Switch From ChromeOS to Chroot, and Vice Versa

### ISSUE THREAD

**Issue by RavenSteam** [dnschneid/crouton#2149]
Hello,

This issue came about late during the lifespan of my previous Chroot(referenced in my other issue), and is appearing every time within every new Chroot I create.

Basically, Ctrl+Alt+Shift+Forward and Ctrl+Alt+Shift+Back fail to produce the proper results they're supposed to(switching between the two active environments). Details of my System are below:
ChromeOS Channel-Canary
Crouton Integration Extension Installed and Set-Up Through Target-Yes
Keyboard Target Utilized-Yes(with or without didn't help)
Linux Release-Trusty
Linux Environment-Xfce

I was able to make a workaround to get from the Chroot to ChromeOS, but then I can't get back to the Linux Environment. I did this through binding a new shortcut with the listed Crouton Shortcut, to run the command "croutoncycle forward" and "croutoncycle back" respectively. This appears to break though upon re-entrance into the Chroot for a bit though, and it's highly inconvenient to begin with.

Thank you in advance for your help,
-RavenSteam

**Comment by DennisLfromGA** [comment]
> but then I can't get back to the Linux Environment.

You should be able to do that via the 'crouton integration' extension by clicking on the active chroot name.

Can you please show us the output of: `sudo edit-chroot -al` ?
It might shed some more light on the problem.
