### ISSUE TITLE
Unity/xfce4 error

### ISSUE THREAD

**Issue by ComputerGeek586** [dnschneid/crouton#2150]
Ok so I have a Asus C100 chromebook with crouton installed. I have reinstalled it updated it and tried every solution I can find on the internet. When ever I run sudo startunity or sudo startxfce4 I get this error every time.

chronos@localhost / $ sudo startunity
Password: 
Enter encryption passphrase for precise: 
Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Sep 18 00:43:27 PDT 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4c6ceb88-fdbc-694a-85fb-4120aa45dd8a/PARTNROFF=1 hashtree=PARTUUID=4c6ceb88-fdbc-694a-85fb-4120aa45dd8a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=62c74a5310b5469154d5073d69c5fa5ccb0174bf salt=36d505e4df1a4b47db560c612c669a802a4d262b0004cdb028236b4d2a209a27" noinitrd vt.global_cursor_default=0 kern_guid=4c6ceb88-fdbc-694a-85fb-4120aa45dd8a  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Oct  1 17:45:07 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $

**Comment by FlamingTaco7101** [comment]
I had this error, and just deleted the evil chroot with the command:

>sudo delete-chroot evilchroot

**Comment by DennisLfromGA** [comment]
Before deleting the evil chroot, you might try following the steps in: '[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)'
