### ISSUE TITLE
Crouton Shutdown Crash

### ISSUE THREAD

**Issue by RavenSteam** [dnschneid/crouton#2152]
Whenever I log out of Ubuntu Trusty(Xfce Environment), in order to shut down the Chroot and return to the standard ChromeOS, either the open browser or the entire computer crashes, also never actually processing the shutdown procedures of the Chroot(though it appears to crash as well, given the lack of activity from the Crouton Integration Plugin).

Details of the set-up are below:
Model: HP Chromebook 14
Channel: Canary
Crouton Release: Latest
Crouton Extension Plugin: Installed
Amount of Chroots: 1
Chroot: Ubuntu Trusty
Targets: keyboard,extension,xfce
Encryption: Yes

Thank you in advance for a way to fix this!

**Comment by dnschneid** [comment]
Has this been a problem for a while, or just the latest canaries?  Could you post the output of `sudo edit-chroot -al`?

**Comment by RavenSteam** [comment]
It's been an issue only since I installed the Xfce Trusty Chroot, with the recent canaries. The Unity Trusty Chroot worked up to that point though. Once I get the chance, I will reply with the output of that command.
