### ISSUE TITLE
touchpad

### ISSUE THREAD

**Issue by walker12001** [dnschneid/crouton#2153]
the touchpad is not working right on acer Chromebook. please fix

**Comment by dnschneid** [comment]
Reboot and try again, then post more information if you still have issues.

**Comment by walker12001** [comment]
when you click or touch the the touchpad it messes up on unity but it works fine on chrome os

**Comment by dnschneid** [comment]
What do you mean by "messes up"?  Please post the output of `sude edit-chroot -al`

**Comment by walker12001** [comment]
here is before the update a hour ago
![capture image2](https://cloud.githubusercontent.com/assets/6394247/10473065/d451f5f0-71db-11e5-881e-680bc21d8c52.png)
![capture image](https://cloud.githubusercontent.com/assets/6394247/10473066/d475c23c-71db-11e5-8f47-6596a39dd080.png)

**Comment by dnschneid** [comment]
try again. you typo'd the command.

**Comment by walker12001** [comment]
how should i type it

**Comment by dnschneid** [comment]
correctly

**Comment by DennisLfromGA** [comment]
>> What do you mean by "messes up"? Please post the output of sude edit-chroot -al

> correctly

Ha, ha ;)

Try: `sudo edit-chroot -al`

**Comment by dnschneid** [comment]
Oof, that's a special kind of fail...
Although it seems @walker12001 didn't get tripped up on that.  I suspect he put in a one instead of an L.

**Comment by walker12001** [comment]
well i copied it like you did dnschneid

**Comment by walker12001** [comment]
is this right?
![capture image3](https://cloud.githubusercontent.com/assets/6394247/10500664/cb61c746-728e-11e5-8bc1-0633c4cd3abe.png)

**Comment by DennisLfromGA** [comment]
You got it. :+1:
