### ISSUE TITLE
Can I use bluetooth in the chroot?

### ISSUE THREAD

**Issue by 4k-developer** [dnschneid/crouton#2154]
Is there a way so i can use the bluetooth in the chroot?

**Comment by dnschneid** [comment]
What kind of bluetooth device?  Audio and input devices are already handled by Chromium OS; setting them up there should make them work in the chroot.

**Comment by 4k-developer** [comment]
I want to connect my phone for data transfer.

**Comment by lgleasain** [comment]
I have a similar question,  but in my case I want to use the blue-z library to connect to a Mbientlab Metawear board to do some development on it.

**Comment by chonkey821** [comment]
im trying to play audio inside crouton using my phone so using it as a bluetooth reciever...is this possible
