### ISSUE TITLE
KDE won't start anymore.

### ISSUE THREAD

**Issue by kranicac** [dnschneid/crouton#2155]
I try to start KDE in the chrome dev console with sudo startkde but then this happens.

Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri Sep 18 01:16:45 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=435e91db-0393-6f47-b214-1e1905bf6c04/PARTNROFF=1 hashtree=PARTUUID=435e91db-0393-6f47-b214-1e1905bf6c04/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=8538d84d5e2930973cc30990d5cf2eb86a448af2 salt=3051b521efbc47425e01685cfa80c61ff4be5d83a664ebec54828ef7f1013708" noinitrd vt.global_cursor_default=0 kern_guid=435e91db-0393-6f47-b214-1e1905bf6c04 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Oct  2 14:38:59 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

Please help.

**Comment by ComputerGeek586** [comment]
I have the same dam error and can't find a solution. I posted this same thing and all they said was update it and still get this error. This goes deeper then a corrupt install or bad launcher.

**Comment by kranicac** [comment]
I talked to my friend and I think it has something to do with installing certain libraries. (I got mine from downloading Steam) I believe the libraries make Crouton corrupt or something. The same thing happened to him too.

**Comment by ComputerGeek586** [comment]
How do you fix it? The first thing I did was setup my Chromebook then try to install crouton and I get this error. I didn't install anything before crouton and xfce unity or kde never opened once. I get the same error on all no screens found.

**Comment by kranicac** [comment]
I don't know I never fixed it. I the only reason I got crouton was to go on steam, so I gave up. Sorry.
