### ISSUE TITLE
Unity not starting. I couldn't find this issue anywhere else.

### ISSUE THREAD

**Issue by CoolCheetah1** [dnschneid/crouton#2157]
On running ls -l/tmp, as suggested on another thread (https://github.com/dnschneid/crouton/issues/1073), this was my output:
ls -l /tmp
total 132
drwxrwxrwx 2 root      root       60 Oct  3 10:19 crouton-installer-cache
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-boot-complete
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-chrome-exec
-rw-r--r-- 1 chronos   chronos     0 Oct  3 10:17 disk-chrome-first-render
-rw-r--r-- 1 chronos   chronos     0 Oct  3 10:16 disk-chrome-main
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-lockbox-cache-end
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-lockbox-cache-exec
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-lockbox-cache-start
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-login-prompt-visible
-rw-r--r-- 1 chronos   chronos     0 Oct  3 10:16 disk-login-start-signin-screen
-rw-r--r-- 1 chronos   chronos     0 Oct  3 10:17 disk-login-success
-rw-r--r-- 1 chronos   chronos     0 Oct  3 10:16 disk-login-wait-for-signin-state-initialize
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-network-wifi-association
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-network-wifi-configuration
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-network-wifi-online
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-network-wifi-ready
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-post-startup
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-pre-startup
-rw-r--r-- 1 root      root       99 Oct  3 10:16 disk-shill-start
-rw-r--r-- 1 root      root        5 Oct  3 10:16 firmware-boot-time
prw------- 1 bluetooth bluetooth   0 Oct  3 10:16 hogsuspend
-rw-r--r-- 1 root      root      831 Oct  3 10:16 mount-encrypted.log
-rw------- 1 root      root        0 Oct  3 10:16 update_engine_update_recorded
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-boot-complete
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-chrome-exec
-rw-r--r-- 1 chronos   chronos    12 Oct  3 10:17 uptime-chrome-first-render
-rw-r--r-- 1 chronos   chronos    10 Oct  3 10:16 uptime-chrome-main
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-lockbox-cache-end
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-lockbox-cache-exec
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-lockbox-cache-start
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-login-prompt-visible
-rw-r--r-- 1 chronos   chronos    10 Oct  3 10:16 uptime-login-start-signin-screen
-rw-r--r-- 1 chronos   chronos    12 Oct  3 10:17 uptime-login-success
-rw-r--r-- 1 chronos   chronos    10 Oct  3 10:16 uptime-login-wait-for-signin-state-initialize
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-network-wifi-association
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-network-wifi-configuration
-rw-r--r-- 1 root      root       11 Oct  3 10:16 uptime-network-wifi-online
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-network-wifi-ready
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-post-startup
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-pre-startup
-rw-r--r-- 1 root      root       10 Oct  3 10:16 uptime-shill-start

with crouton-installer, hogsuspend and mount-encrypted.log highlighted.

Everytime I try sudo startunity, I get
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/local/bin/xinit: 34: exec: /usr/bin/xinit: not found
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Whereas, sudo edit-chroot -al yielded:

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150924014025~master:04ff0c11
release: trusty
architecture: amd64
xmethod: xiwi
targets: unity,xiwi
host: version 7262.57.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Fri Sep 18 01:00:15 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I tried upgrading Precise to Trusty yesterday, and this was the first time I switched my computer on again.

Everytime I try updating, it goes half-way through and then stops abruptly, like so:

Compiling CRAS (native)...
Installing CRAS...
Installing target extension...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
x11-utils is already the newest version.
xclip is already the newest version.
The following packages were automatically installed and are no longer required:
  bluez-alsa:i386 esound-common glib-networking:i386
  gstreamer0.10-plugins-base:i386 gstreamer0.10-plugins-good:i386
  gstreamer0.10-x:i386 gtk2-engines:i386 gtk2-engines-murrine:i386
  gtk2-engines-oxygen:i386 gtk2-engines-pixbuf:i386 gvfs:i386 gvfs-libs:i386
  ibus-gtk:i386 libaa1:i386 libaio1:i386 libao-common libao4:i386
  libasn1-8-heimdal:i386 libatk1.0-0:i386 libaudio2:i386 libaudiofile1:i386
  libavahi-client3:i386 libavahi-common-data:i386 libavahi-common3:i386
  libavc1394-0:i386 libcaca0:i386 libcairo-gobject2:i386 libcairo2:i386
  libcanberra-gtk-module:i386 libcanberra-gtk0:i386 libcanberra0:i386
  libcapi20-3:i386 libcdparanoia0:i386 libcroco3:i386 libcups2:i386
  libcupsfilters1:i386 libcupsimage2:i386 libcurl3:i386 libdbus-glib-1-2:i386
  libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdv4:i386
  libelf1:i386 libesd0:i386 libexif12:i386 libexpat1:i386 libfluidsynth1:i386
  libfontconfig1:i386 libfreetype6:i386 libgail-common:i386 libgail18:i386
  libgconf-2-4:i386 libgcrypt11:i386 libgd3:i386 libgdbm3:i386
  libgdk-pixbuf2.0-0:i386 libgettextpo0:i386 libgl1-mesa-dri:i386
  libgl1-mesa-glx:i386 libglapi-mesa:i386 libglu1-mesa:i386 libgnutls26:i386
  libgpg-error0:i386 libgphoto2-6:i386 libgphoto2-port10:i386
  libgraphite2-3:i386 libgssapi-krb5-2:i386 libgssapi3-heimdal:i386
  libgstreamer-plugins-base0.10-0:i386 libgstreamer-plugins-base1.0-0:i386
  libgstreamer0.10-0:i386 libgstreamer1.0-0:i386 libgtk2.0-0:i386
  libgudev-1.0-0:i386 libharfbuzz0b:i386 libhcrypto4-heimdal:i386
  libheimbase1-heimdal:i386 libheimntlm0-heimdal:i386 libhx509-5-heimdal:i386
  libibus-1.0-5:i386 libice6:i386 libidn11:i386 libiec61883-0:i386
  libieee1284-3:i386 libjasper1:i386 libjbig0:i386 libjpeg-turbo8:i386
  libjpeg8:i386 libk5crypto3:i386 libkeyutils1:i386 libkrb5-26-heimdal:i386
  libkrb5-3:i386 libkrb5support0:i386 libldap-2.4-2:i386 libllvm3.4:i386
  libltdl7:i386 libmad0:i386 libmikmod2:i386 libmpg123-0:i386
  libmysqlclient18:i386 libnspr4:i386 libnss3:i386 libodbc1:i386
  libopenal-data libopenal1:i386 liborc-0.4-0:i386 libp11-kit0:i386
  libpango1.0-0:i386 libpangocairo-1.0-0:i386 libpangoft2-1.0-0:i386
  libpangoxft-1.0-0:i386 libpciaccess0:i386 libpixman-1-0:i386 libproxy1:i386
  libpulse-mainloop-glib0:i386 libpulsedsp:i386 libqt4-dbus:i386
  libqt4-declarative:i386 libqt4-designer:i386 libqt4-network:i386
  libqt4-opengl:i386 libqt4-qt3support:i386 libqt4-script:i386
  libqt4-scripttools:i386 libqt4-sql:i386 libqt4-sql-mysql:i386
  libqt4-svg:i386 libqt4-test:i386 libqt4-xml:i386 libqt4-xmlpatterns:i386
  libqtcore4:i386 libqtdbus4:i386 libqtgui4:i386 libqtwebkit4:i386
  libraw1394-11:i386 libreadline6:i386 libroken18-heimdal:i386 librsvg2-2:i386
  librsvg2-common:i386 librtmp0:i386 libsane:i386 libsasl2-2:i386
  libsasl2-modules:i386 libsasl2-modules-db:i386 libsdl-image1.2:i386
  libsdl-mixer1.2:i386 libsdl-net1.2:i386 libsdl-ttf2.0-0:i386
  libsdl1.2debian:i386 libsecret-1-0:i386 libshout3:i386 libsm6:i386
  libsoup-gnome2.4-1:i386 libsoup2.4-1:i386 libsqlite3-0:i386 libssl0.9.8:i386
  libssl1.0.0:i386 libstdc++5:i386 libtag1-vanilla:i386 libtag1c2a:i386
  libtasn1-6:i386 libtdb1:i386 libtheora0:i386 libtiff5:i386
  libtxc-dxtn-s2tc0:i386 libunistring0:i386 libusb-0.1-4:i386
  libusb-1.0-0:i386 libv4l-0:i386 libv4lconvert0:i386 libvisual-0.4-0:i386
  libvisual-0.4-plugins:i386 libvorbisfile3:i386 libvpx1:i386 libwavpack1:i386
  libwebp5:i386 libwind0-heimdal:i386 libx11-xcb1:i386 libxaw7:i386
  libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386
  libxcb-render0:i386 libxcb-shm0:i386 libxcb-sync1:i386 libxcomposite1:i386
  libxcursor1:i386 libxdamage1:i386 libxext6:i386 libxfixes3:i386 libxft2:i386
  libxi6:i386 libxinerama1:i386 libxml2:i386 libxmu6:i386 libxp6:i386
  libxpm4:i386 libxrandr2:i386 libxrender1:i386 libxshmfence1:i386
  libxslt1.1:i386 libxss1:i386 libxt6:i386 libxtst6:i386 libxv1:i386
  libxxf86vm1:i386 odbcinst odbcinst1debian2 odbcinst1debian2:i386 xaw3dg:i386
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Installing dependencies for /usr/local/bin/croutonwebsocket...
Reading package lists... Done
Building dependency tree        
Reading state information... Done
gcc is already the newest version.
libc6-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  bluez-alsa:i386 esound-common glib-networking:i386
  gstreamer0.10-plugins-base:i386 gstreamer0.10-plugins-good:i386
  gstreamer0.10-x:i386 gtk2-engines:i386 gtk2-engines-murrine:i386
  gtk2-engines-oxygen:i386 gtk2-engines-pixbuf:i386 gvfs:i386 gvfs-libs:i386
  ibus-gtk:i386 libaa1:i386 libaio1:i386 libao-common libao4:i386
  libasn1-8-heimdal:i386 libatk1.0-0:i386 libaudio2:i386 libaudiofile1:i386
  libavahi-client3:i386 libavahi-common-data:i386 libavahi-common3:i386
  libavc1394-0:i386 libcaca0:i386 libcairo-gobject2:i386 libcairo2:i386
  libcanberra-gtk-module:i386 libcanberra-gtk0:i386 libcanberra0:i386
  libcapi20-3:i386 libcdparanoia0:i386 libcroco3:i386 libcups2:i386
  libcupsfilters1:i386 libcupsimage2:i386 libcurl3:i386 libdbus-glib-1-2:i386
  libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdv4:i386
  libelf1:i386 libesd0:i386 libexif12:i386 libexpat1:i386 libfluidsynth1:i386
  libfontconfig1:i386 libfreetype6:i386 libgail-common:i386 libgail18:i386
  libgconf-2-4:i386 libgcrypt11:i386 libgd3:i386 libgdbm3:i386
  libgdk-pixbuf2.0-0:i386 libgettextpo0:i386 libgl1-mesa-dri:i386
  libgl1-mesa-glx:i386 libglapi-mesa:i386 libglu1-mesa:i386 libgnutls26:i386
  libgpg-error0:i386 libgphoto2-6:i386 libgphoto2-port10:i386
  libgraphite2-3:i386 libgssapi-krb5-2:i386 libgssapi3-heimdal:i386
  libgstreamer-plugins-base0.10-0:i386 libgstreamer-plugins-base1.0-0:i386
  libgstreamer0.10-0:i386 libgstreamer1.0-0:i386 libgtk2.0-0:i386
  libgudev-1.0-0:i386 libharfbuzz0b:i386 libhcrypto4-heimdal:i386
  libheimbase1-heimdal:i386 libheimntlm0-heimdal:i386 libhx509-5-heimdal:i386
  libibus-1.0-5:i386 libice6:i386 libidn11:i386 libiec61883-0:i386
  libieee1284-3:i386 libjasper1:i386 libjbig0:i386 libjpeg-turbo8:i386
  libjpeg8:i386 libk5crypto3:i386 libkeyutils1:i386 libkrb5-26-heimdal:i386
  libkrb5-3:i386 libkrb5support0:i386 libldap-2.4-2:i386 libllvm3.4:i386
  libltdl7:i386 libmad0:i386 libmikmod2:i386 libmpg123-0:i386
  libmysqlclient18:i386 libnspr4:i386 libnss3:i386 libodbc1:i386
  libopenal-data libopenal1:i386 liborc-0.4-0:i386 libp11-kit0:i386
  libpango1.0-0:i386 libpangocairo-1.0-0:i386 libpangoft2-1.0-0:i386
  libpangoxft-1.0-0:i386 libpciaccess0:i386 libpixman-1-0:i386 libproxy1:i386
  libpulse-mainloop-glib0:i386 libpulsedsp:i386 libqt4-dbus:i386
  libqt4-declarative:i386 libqt4-designer:i386 libqt4-network:i386
  libqt4-opengl:i386 libqt4-qt3support:i386 libqt4-script:i386
  libqt4-scripttools:i386 libqt4-sql:i386 libqt4-sql-mysql:i386
  libqt4-svg:i386 libqt4-test:i386 libqt4-xml:i386 libqt4-xmlpatterns:i386
  libqtcore4:i386 libqtdbus4:i386 libqtgui4:i386 libqtwebkit4:i386
  libraw1394-11:i386 libreadline6:i386 libroken18-heimdal:i386 librsvg2-2:i386
  librsvg2-common:i386 librtmp0:i386 libsane:i386 libsasl2-2:i386
  libsasl2-modules:i386 libsasl2-modules-db:i386 libsdl-image1.2:i386
  libsdl-mixer1.2:i386 libsdl-net1.2:i386 libsdl-ttf2.0-0:i386
  libsdl1.2debian:i386 libsecret-1-0:i386 libshout3:i386 libsm6:i386
  libsoup-gnome2.4-1:i386 libsoup2.4-1:i386 libsqlite3-0:i386 libssl0.9.8:i386
  libssl1.0.0:i386 libstdc++5:i386 libtag1-vanilla:i386 libtag1c2a:i386
  libtasn1-6:i386 libtdb1:i386 libtheora0:i386 libtiff5:i386
  libtxc-dxtn-s2tc0:i386 libunistring0:i386 libusb-0.1-4:i386
  libusb-1.0-0:i386 libv4l-0:i386 libv4lconvert0:i386 libvisual-0.4-0:i386
  libvisual-0.4-plugins:i386 libvorbisfile3:i386 libvpx1:i386 libwavpack1:i386
  libwebp5:i386 libwind0-heimdal:i386 libx11-xcb1:i386 libxaw7:i386
  libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386
  libxcb-render0:i386 libxcb-shm0:i386 libxcb-sync1:i386 libxcomposite1:i386
  libxcursor1:i386 libxdamage1:i386 libxext6:i386 libxfixes3:i386 libxft2:i386
  libxi6:i386 libxinerama1:i386 libxml2:i386 libxmu6:i386 libxp6:i386
  libxpm4:i386 libxrandr2:i386 libxrender1:i386 libxshmfence1:i386
  libxslt1.1:i386 libxss1:i386 libxt6:i386 libxtst6:i386 libxv1:i386
  libxxf86vm1:i386 odbcinst odbcinst1debian2 odbcinst1debian2:i386 xaw3dg:i386
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Compiling /usr/local/bin/croutonwebsocket...
Installing target xiwi...
xserver-xorg-video-dummy was already not hold.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xorg : Depends: xserver-xorg (>= 1:7.7+1ubuntu8.1) or
                 xserver-xorg-renamed
 xserver-xorg-video-dummy-lts-trusty : Conflicts: xserver-xorg-video-dummy
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Over and over again.

Any help will be appreciated.

**Comment by dnschneid** [comment]
Try `sudo enter-chroot -n precise -u root apt-get remove 'xorg.*' 'xserver.*'` then run the updater again.

**Comment by Kleak** [comment]
same problem for me and remove and run again i have the same problem

**Comment by Juanvulcano** [comment]
This worked ! Thanks
