### ISSUE TITLE
Please fix

### ISSUE THREAD

**Issue by Tdx3gamer** [dnschneid/crouton#2158]
I get -r trusty and -t kde,chrome and my touchpad doesnt work

**Comment by dohliam** [comment]
Recent ChromeOS updates have had the side effect of disabling tap-to-click in some crouton chroots (see e.g. #2043). It seems to have something to do with freon and targets that don't have xiwi installed.

The temporary workaround suggested in the issue above is to enter the following in a terminal:

    synclient FingerLow=1 FingerHigh=5

This should reset the touchpad to its normal settings, but it won't stick so you'll have to enter it every time you log in.
