### ISSUE TITLE
Debian Stretch - Switching back to chrome yields only black screen

### ISSUE THREAD

**Issue by c200chromebook** [dnschneid/crouton#2159]
Hi - I recently upgraded to Stretch from Jessie. I updated my crouton after upgrading. However, now, after the chroot is started, switching back to Chrome makes the screen go dead black - not even backlight. Any first steps to debug? Version info below.

```
crouton: version 1-20150924014025~master:04ff0c11
release: stretch
architecture: amd64
xmethod: xorg
targets: keyboard,xfce
host: version 7262.57.0 (Official Build) stable-channel squawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Sep 17 23:07:25 PDT 2015 x86_64 GNU/Linux
freon: yes
```

**Comment by jamgregory** [comment]
I've been seeing the same thing as @c200chromebook on my Asus C300:

```
crouton: version git
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,xorg,xiwi,xfce,extension
host: version 7262.57.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Fri Sep 18 01:00:15 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

I'm up to revision edbce1122edaf48d259b5580f718141a760d7ecc on my crouton installation.

**Comment by jamgregory** [comment]
If it helps at all, I don't remember seeing this issue before switching to use the xorg-edgers PPA to fix some graphical glitches in Hearthstone...

**Comment by dnschneid** [comment]
@c200chromebook are you using the xorg-edgers PPA as well?

**Comment by c200chromebook** [comment]
Oh sorry, missed this. No. Xorg 7.7+12. I do get an error when upgrading stating it can't install modesetting. A bit of googling reveals this was integrated into xorg-core.  
* xserver-xorg-video-modesetting:i386 depends on xorg-video-abi-18:i386
    (provided by xserver-xorg-core:i386 2:1.16.4-1)

**Comment by c200chromebook** [comment]
Please closed - reinstalled with Ubuntu, working brilliantly.
