### ISSUE TITLE
Pixel 2 Touch Events only work in Chrome browser

### ISSUE THREAD

**Issue by cwmoo740** [dnschneid/crouton#2160]
In ChromeOS touch events work as expected. In the chroot, touch events only work in a chrome browser window.

crouton: version 1-20150924014025~master:04ff0c11
release: trusty
architecture: amd64
xmethod: xorg
targets: touch,chrome,extension,unity-desktop,keyboard,audio
host: version 7262.57.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Thu Sep 17 22:59:22 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by dnschneid** [comment]
The touch extension adds some generic touch event handling via the `touchegg` utility.  You could try disabling it via #660 to see if it's conflicting with other stuff.  You also could be hitting #1050.
