### ISSUE TITLE
Proper way to run croutonwebsocket on enter-chroot without permission issues?

### ISSUE THREAD

**Issue by shippy** [dnschneid/crouton#2161]
My primary use case for crouton is the terminal environment. Sometimes, I'd like to take advantage of `croutonurlhandler` to open links from Mutt (by setting `export BROWSER="croutonurlhandler -n"` in my `.zshrc`. To do this, `croutonwebsocket` needs to run as a background process.

If I put `croutonwebsocket &` in `/etc/rc.local`, it is (obviously) run as root -- consequently, only `sudo croutonurlhandler` works as expected. Without it, the following error happens:
```
$ croutonurlhandler http://www.google.com/
/usr/local/bin/croutonurlhandler: 207: /usr/local/bin/croutonurlhandler: cannot create /tmp/crouton-ext/lock: Permission denied
Error timeout
```

If I run `croutonwebsocket &` in terminal as current user, it does not have an available pipe: `checkfifo: /tmp/crouton-ext/in exists, but not readable and writable.`

Is there an expected setup that I'm missing here? Should I be running `croutonwebsocket` with `upstart`?

```
$ croutonversion
crouton: version 1-20150730171703~master:f8fdfb0c
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,extension,audio,keyboard,cli-extra,core
host: version 7390.48.0 (Official Build) beta-channel swanky
kernel: Linux localhost 3.10.18 #1 SMP Wed Sep 30 18:28:58 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by dnschneid** [comment]
You should be able to run `croutonwebsocket &` as non-root, although if you ran it as root before you may have permissions issues.  Either reboot or manually `sudo rm -rf /tmp/crouton-ext` and try again.

**Comment by dnschneid** [comment]
Related: #2113

**Comment by shippy** [comment]
Thank you; this works. (For posteriority, my setup is `croutonwebsocket &` in `.zprofile`, then `export BROWSER="croutonurlhandler -n"` in `.zshrc`.)

On reflection, this doesn't seem like it can be addressed by code (if a user-run `croutonwebsocket` fails to get pipe, it has probably no way to reset permissions on `/tmp/crouton-ext` with current privileges?), so I'll make a note on the `croutonwebsocket` wiki page the next chance I have.

**Comment by dnschneid** [comment]
Well, the permissions on /tmp/crouton-ext should never get messed up unless you try to run croutonwebsocket or X11 as root (which you shouldn't).  That's a bit of a cop-out though; in #2113 we should fix the pipe permissions and autorun the daemon as an unprivileged system user as part of the glorious enter-chroot script.
