### ISSUE TITLE
navigate().back() ---iteration

### ISSUE THREAD

**Issue by Ravi220** [dnschneid/crouton#2162]
Protractor tool is new to me, could you please help me with the following.

How to iterate through browser.navigate().back()??

I have a page to automate where I need to click on all the links in home page, and then go back to the home page to click on the remaining links.

For time being I derived like the following:

  HomePage.HomegMenuItem.click();
  HomePage.reference.click();
	browser.navigate().back();
  HomePage.machine.click();
	browser.navigate().back();
  HomePage.connectivity.click();
	browser.navigate().back();
		
Homepage and other var's are declared in page objects.
	
	Thanks!!

**Comment by Ravi220** [comment]
@sjelin @ramonvictor

**Comment by dnschneid** [comment]
*@*irrelephant
#262
