### ISSUE TITLE
Page up/down in Terminal (xfce)

### ISSUE THREAD

**Issue by xorb0ss** [dnschneid/crouton#2163]
For some reason I can't get Page Up/Down working in Terminal using xfce, especially in stuff like irssi so I can't scroll up.

I've updated `/etc/default/keyboard` to 'chromebook' under the model, I've even ran `./crouton -t keyboard` on my current chroot, however no matter what I press (alt+up, ctrl+up, ctrl+alt+up, etc...) page up/down won't work.

**Comment by SnarkBoojum** [comment]
In irssi, alt+P scrolls up... for down, "/scrollback end".

**Comment by dnschneid** [comment]
iirc it's search key + up/down to do page up/down.
