### ISSUE TITLE
Warning or problem?

### ISSUE THREAD

**Issue by prstockton** [dnschneid/crouton#2165]
Toshiba Chromebook 2
-r Trusty
-t xiwi
Single application i.e: xiwi subl -w

I get this message in terminal whilst launching as above:

Connected to extension, launched crouton in a window.
deciding for version 4 due to this line: # i3 config file (v4)
06/10/15 14:40:23 - ERROR: Could not translate string to key symbol: "button2"
06/10/15 14:40:23 - ERROR: Could not translate string to key symbol: "button2"
06/10/15 14:40:23 - ERROR: Could not translate string to key symbol: "button2"
Unable to connect to dbus
Error: target STRING not available
06/10/15 14:40:45 - ERROR: Could not translate string to key symbol: "button2"
06/10/15 14:40:45 - ERROR: Could not translate string to key symbol: "button2"

Everything seems to run as expected but unsure whether i am going to encounter issues further down the line.

Any guidance really appreciated.

**Comment by dnschneid** [comment]
Nothing to worry about.  i3 is noisy, and we don't currently adjust the config file based on the version of i3 you're running.

**Comment by Roaders** [comment]
Hi @ghost it seems that you are doing exactly what I am trying to do but am having issues with. I have posted about it in #2996.
I created a trusty chroot with xiwi, installed sublime text and tried to launch it but nothing happens.
Do you have any suggestions?
Many Thanks.

**Comment by Roaders** [comment]
Never mind, using the same command as you to launch did the trick.
