### ISSUE TITLE
Removing Gnome (not working)

### ISSUE THREAD

**Issue by rgeorgioff** [dnschneid/crouton#2166]
I tried Gnome with Jessie on a whim, although I usually use xfce. It refused to start on my Chroebook 11 and I can't be bothered right now to fix it. If you know how, let me know.

In the meantime, it's yet unclear how I might remove a target from my chroot. I have considered using something like purge, but I'm still a novice and don't want to screw up the implementation.

How do I remove the base gnome package (the 400 MB one)?

**Comment by DennisLfromGA** [comment]
There's been some success in removing targets manually using '`apt-mark auto ...`' - see https://github.com/dnschneid/crouton/issues/717.
However, a formal, built-in method to remove targets has yet to be incorporated.
