### ISSUE TITLE
Add edit-chroot option to duplicate a chroot

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#2168]
As a user I would like the ability to easily copy a chroot. Currently to achieve this I backup, then move, then restore from the backup.

I am not sure what option to use as `edit-chroot -c` and `edit-chroot -d` are already taken.

**Comment by dnschneid** [comment]
If the chroot is unmounted, you can `sudo cp -a old_chroot new_chroot`.

You can also restore the backup using the crouton installer and specify `-n` to change the name.

But I guess we could add a command to edit-chroot as well.  Maybe `-C` or `-u`...

**Comment by justinguy** [comment]
Great I will use `-u` as `-c` is already in use and submit a pull request.

**Comment by tonyxue** [comment]
Maybe just write a simple function to ```cp``` and edit ```/etc/crouton/name```?

**Comment by dnschneid** [comment]
/etc/crouton/name is updated on `enter-chroot`
