### ISSUE TITLE
Console command for interacting with Chromium OS clipboard

### ISSUE THREAD

**Issue by jbaum98** [dnschneid/crouton#2169]
Right now, if you are using the regular Secure Shell and `enter-chroot`, `croutonurlhandler` doesn't work. Also, there is no way to synchronize the Chrome OS clipboard with the clipboard inside the chroot, for use with `vim` or `emacs` clipboard integration. Can these features be implemented, or do they rely too heavily on X?

**Comment by dnschneid** [comment]
See #2113 for the first item.  I'm not sure what you want for the second item, since vim/emacs without X11 have their own internal buffers that aren't synchronized via any standard.

**Comment by jbaum98** [comment]
Thanks for the quick response. I guess I meant getting `xclip` or some equivalent to work in the console, and it would be easy to have that command talk to whatever other programs.

**Comment by dnschneid** [comment]
Ohhh, that makes sense.  Basically, we need to add xclip-like `-i` and `-o` parameters to `croutonclip`.

**Comment by jbaum98** [comment]
Yeah, that work even without X, from `enter-chroot` in secure shell.
`xclip` actually works if I do `xiwi uxterm`.

**Comment by acornejo** [comment]
I hacked up something in go to do what I needed (of course it requires the crouton chrome extension installed), but since it doesn't have a dedicated server process it has a high latency (depends on the extension reconnecting to the server).

I could refactor slightly to have a long running server to which I communicate with using named pipes, but I presume croutonclip is already doing something like this?

In case its useful to others, here is what I came up with so far:

https://gist.github.com/acornejo/763f8540dd01090955f3ddcbfee55d42

**Comment by acornejo** [comment]
I've since put it in a proper repo and updated it to use a long running process to avoid any lag, works well enough for me, perhaps its useful to others:

https://github.com/acornejo/croshclip

**Comment by eyqs** [comment]
Is this also addressed by https://github.com/zwhitchcox/crouton-clipboard? I think this should be closed.

**Comment by rackstraw** [comment]
Examine the FAQ for "Secure Shell".  It has a link to a utility program called "osc52" which copies from stdin to the system clipboard, up to 100K chars.

1) As a filter to vim, to copy a whole file to system clipboard:
*
$ vim somefile
gg
!G osc52.sh
*

2) Copy a few words, lines or whole file direct from command line:

$ echo foo bar | osc52.sh
*
$ cat | osc52,sh
There was a young person from Ride
Who had a most practical side
^D
*
$ cat somefile | osc52.sh

**Comment by trusktr** [comment]
How do we use croutonclip?

**Comment by trusktr** [comment]
Or, more specifically, if we have croutonclip installed inside enter-chroot, how do we get Vim/NeoVim to actually yank to the Chrome OS clipboard?

**Comment by trusktr** [comment]
Hmmm, I'm getting somewhere. If I let it run for a while, it says

```
❯ croutonclip
Timeout waiting for extension to connect.
Cannot open /sys/class/tty/tty0/active: No such file or directory
```

**Comment by rackstraw** [comment]
I gave up on all that, and use Secure Shell - logging into
"username@localhost" - together with the osc52.sh utility that comes with
Secure Shell, in order to copy text to the system clipboard.

**Comment by trusktr** [comment]
Ah, cool, got croshclip working (needed Crouton Chrome plugin). I'm still not sure how croutonclip works though, but croshclip meets the need!
