### ISSUE TITLE
[Question] How do I add the .bash_aliases and .bashrc files in chromeOS?

### ISSUE THREAD

**Issue by laizureboi** [dnschneid/crouton#2175]
For example, I've moved my chroot precise to `/media/removable/laizureboi/precise` and I don't want to have to type `sudo startxfce4 -c /media/removable/laizureboi/precise` every time I want to start my environment. I've added `alias s-xfce4='sudo startxfce4 -c /media/removable/laizureboi'` to the .bash_aliases file, and it's in the Downloads folder... But it doesn't work. I'm assuming this means that it's not in the correct spot - could someone nudge me in the right direction? Where should I move the file? 

Thanks!

**Comment by tonyxue** [comment]
Do the aliases in your ```~/.bashrc```

**Comment by DennisLfromGA** [comment]
As @tonyxue mentioned, put your alias assignments in your `~/.bashrc` file.
Or, if you have many, put them in a `~./.bash_aliases` file and use something like this in your `~/.bashrc` file - 
`[ -f ~/.bash_aliases ] && . ~/.bash_aliases`
