### ISSUE TITLE
[RESOLVED] sudo startxfce4 not mounting after crouton encryption

### ISSUE THREAD

**Issue by chuckawe** [dnschneid/crouton#2176]
After encrypting my trusty crouton and trying to start xfce i get "Permission denied" outputs

    chronos@localhost / $ sudo startxfce4
    Password: 
    Sorry, try again.
    Password: 
    Enter encryption passphrase for Chosen: 
    Entering /mnt/stateful_partition/crouton/chroots/Chosen...
    -su: 1: id: Permission denied
    -su: 12: [: Illegal number: 
    -su: 1: /etc/profile.d/crouton-pulseaudio-cras.sh: id: Permission denied
    -su: 5: [: Illegal number: 
    -su: 1: exec: startxfce4: Permission denied
    Unmounting /mnt/stateful_partition/crouton/chroots/Chosen...

I'm not able to run `sudo enter-chroot -n chrootname croutonversion` either. When i do i receive another "permissions denied" output 

    chronos@localhost / $ sudo enter-chroot -n Chosen croutonversion
    Password: 
    Enter encryption passphrase for Chosen: 
    Entering /mnt/stateful_partition/crouton/chroots/Chosen...
    -su: 1: id: Permission denied
    -su: 12: [: Illegal number: 
    -su: 1: /etc/profile.d/crouton-pulseaudio-cras.sh: id: Permission denied
    -su: 5: [: Illegal number: 
    -su: 1: croutonversion: Permission denied
    Unmounting /mnt/stateful_partition/crouton/chroots/Chosen...

**Comment by chuckawe** [comment]
I just did a fresh install. Nothing really too serious. Didn't want to lose al customization, but i got over it.

**Comment by DennisLfromGA** [comment]
For future reference, you can get in to your chroot as 'root' using: 

`sudo enter-chroot -u root ...`

That sometimes helps when permissions in the chroot are hosed and you need to do something like:

`sudo chown -R 1000:1000 "$HOME"`
