### ISSUE TITLE
Launching KDE with Wheezy fails

### ISSUE THREAD

**Issue by mrkapqa** [dnschneid/crouton#2177]
Hello ,

after several quite unstable experiences with DualBoot on my Acer C720 with HugeGreenBugs awesome Distros and ChromeOS ,

i am trying to install my favorite Distro via Crouton

to so i did 

sudo sh ... crouton -r wheezy -t kde-desktop

the install seemed to work flawlessly; upon invoking 

sudo startkde i get the following

sudo startkde
Entering /mnt/stateful_partition/crouton/chroots/wheezy...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Sep 17 23:14:49 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=df15db84-aae5-a640-bd92-764d537f1ba8/PARTNROFF=1 hashtree=PARTUUID=df15db84-aae5-a640-bd92-764d537f1ba8/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b845cce0ad76148214153bceb37ac78854c5a4ed salt=6f7b35b25daeb73216af71f368a88156aa8d98bf7837c88e101dd0bf3868de8d" noinitrd vt.global_cursor_default=0 kern_guid=df15db84-aae5-a640-bd92-764d537f1ba8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 09 February 2015  09:46:52AM
xorg-server 2:1.12.4-6+deb7u6 (Julien Cristau <jcristau@debian.org>) 
Current version of pixman: 0.26.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Oct 11 20:04:56 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20150924014025~master:04ff0c11
release: wheezy
architecture: amd64
xmethod: xiwi
targets: kde-desktop
host: version 7262.57.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Sep 17 23:14:49 PDT 2015 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/wheezy...
chronos@localhost / $

**Comment by mrkapqa** [comment]
sudo enter-chroot startkde
Entering /mnt/stateful_partition/crouton/chroots/wheezy...
$DISPLAY is not set or cannot connect to the X server.
Unmounting /mnt/stateful_partition/crouton/chroots/wheezy...

**Comment by mrkapqa** [comment]
wow - installing the "Crouton Extension" solved the problem for me.

Question: is it possible to install a HugeGreenBug. configured / flavored iso of kubuntu using Crouton so that it would be possible to have already all the multimediakeys and various other fixes active?

f

**Comment by DennisLfromGA** [comment]
@dnschneid, @drinkcat -

>> Unable to start display, make sure the crouton extension is installed
>> and enabled, and up to date. (download from http://goo.gl/OVQOEt)

> wow - installing the "Crouton Extension" solved the problem for me.

I know it's nit-picky but maybe the error message in `chroot-bin/croutonxinitrc-wrapper` could be a little more precise and say 'crouton integration' extension when referring to the Web Store extension, especially since the crouton target is named 'extension'.
