### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tdx3gamer** [dnschneid/crouton#2178]
I keep trying to get linux and at the moment this is broken  for me so plz update!!!

**Comment by DennisLfromGA** [comment]
> I keep trying to get linux and at the moment this is broken for me so plz update!!!

We need ( a lot ) more info. to work with than the above.
- What are you trying to do?
- What command(s) are you using to do it?
- If you have a chroot installed, what does `edit-chroot -al` show?
