### ISSUE TITLE
three.js skybox

### ISSUE THREAD

**Issue by kuhu12** [dnschneid/crouton#2180]
/ standard global variables
var container, scene, camera, renderer, controls, stats;
var keyboard = new THREEx.KeyboardState();
var clock = new THREE.Clock();
// custom global variables
var skyBox;

init();
animate();

// FUNCTIONS 		
function init() 
{
	// SCENE
	scene = new THREE.Scene();
	// CAMERA
	var SCREEN_WIDTH = window.innerWidth, SCREEN_HEIGHT = window.innerHeight;
	var VIEW_ANGLE = 45, ASPECT = SCREEN_WIDTH / SCREEN_HEIGHT, NEAR = 0.1, FAR = 20000;
	camera = new THREE.PerspectiveCamera( VIEW_ANGLE, ASPECT, NEAR, FAR);
	scene.add(camera);
	camera.position.set(0,150,400);
	camera.lookAt(scene.position);	
	// RENDERER
	if ( Detector.webgl )
		renderer = new THREE.WebGLRenderer( {antialias:true} );
	else
		renderer = new THREE.CanvasRenderer(); 
	renderer.setSize(SCREEN_WIDTH, SCREEN_HEIGHT);
	container = document.getElementById( 'ThreeJS' );
	container.appendChild( renderer.domElement );
	// EVENTS
	THREEx.WindowResize(renderer, camera);
	THREEx.FullScreen.bindKey({ charCode : 'm'.charCodeAt(0) });
	// CONTROLS
	controls = new THREE.OrbitControls( camera, renderer.domElement );
	// STATS
	stats = new Stats();
	stats.domElement.style.position = 'relative';
	stats.domElement.style.bottom = '0px';
	stats.domElement.style.zIndex = 100;
	container.appendChild( stats.domElement );
	// LIGHT
	//var light = new THREE.PointLight(0xffffff);
	//light.position.set(0,250,0);
	//scene.add(light);
	// FLOOR
	//var floorTexture = new THREE.ImageUtils.loadTexture( 'images/checkerboard.jpg' );
	//floorTexture.wrapS = floorTexture.wrapT = THREE.RepeatWrapping; 
	//floorTexture.repeat.set( 10, 10 );
	//var floorMaterial = new THREE.MeshBasicMaterial( { map: floorTexture, side: THREE.DoubleSide } );
	//var floorGeometry = new THREE.PlaneGeometry(100, 100, 10, 10);
	//var floor = new THREE.Mesh(floorGeometry, floorMaterial);
	//floor.position.y = -0.5;
	//floor.rotation.x = Math.PI / 2;
	//scene.add(floor);
	
	////////////
	// CUSTOM //
	////////////
	
	// axes
	//var axes = new THREE.AxisHelper(100);
	//scene.add( axes );
	
	var imagePrefix = "images/DSCN";
	var directions  = ["left", "right", "up", "", "back", "front"];
	var imageSuffix = "2.jpg";
	var skyGeometry = new THREE.CubeGeometry( 1500, 500, 1500 );	

	var materialArray = [];
	for (var i = 0; i < 6; i++)
		materialArray.push( new THREE.MeshBasicMaterial({
			map: THREE.ImageUtils.loadTexture( imagePrefix + directions[i] + imageSuffix ),
			side: THREE.BackSide
		}));
	var skyMaterial = new THREE.MeshFaceMaterial( materialArray );
	var skyBox = new THREE.Mesh( skyGeometry, skyMaterial );
	scene.add( skyBox );
	

	}

function animate() 
{
    requestAnimationFrame( animate );
	render();		
	update();
}

function update()
{
	var delta = clock.getDelta(); // seconds.
	var moveDistance = 200 * delta; // 200 pixels per second
	var rotateAngle = Math.PI / 2 * delta;   // pi/2 radians (90 degrees) per second
	
	// local coordinates

	// local transformations

	// move forwards/backwards/left/right
	if ( keyboard.pressed("W") )
		skyBox.translateZ( -moveDistance );
	if ( keyboard.pressed("S") )
		skyBox.translateZ(  moveDistance );
	if ( keyboard.pressed("Q") )
		skyBox.translateX( -moveDistance );
	if ( keyboard.pressed("E") )
		skyBox.translateX(  moveDistance );	

	// rotate left/right/up/down
	var rotation_matrix = new THREE.Matrix4().identity();
	if ( keyboard.pressed("A") )
		skyBox.rotateOnAxis( new THREE.Vector3(0,1,0), rotateAngle);
	if ( keyboard.pressed("D") )
		skyBox.rotateOnAxis( new THREE.Vector3(0,1,0), -rotateAngle);
	if ( keyboard.pressed("R") )
		skyBox.rotateOnAxis( new THREE.Vector3(1,0,0), rotateAngle);
	if ( keyboard.pressed("F") )
		skyBox.rotateOnAxis( new THREE.Vector3(1,0,0), -rotateAngle);
	
	if ( keyboard.pressed("Z") )
	{
		skyBox.position.set(0,25.1,0);
		skyBox.rotation.set(0,0,0);
	}
		
	// global coordinates
	if ( keyboard.pressed("left") )
		skyBox.position.x -= moveDistance;
	if ( keyboard.pressed("right") )
		skyBox.position.x += moveDistance;
	if ( keyboard.pressed("up") )
		skyBox.position.z -= moveDistance;
	if ( keyboard.pressed("down") )
		skyBox.position.z += moveDistance;
		
	controls.update();
	stats.update();
	$("#button").mousedown(function(){
	mousemove()
    
});
	
}

function render() 
{
	renderer.render( scene, camera );
}

</script>

</body>
</html>

**Comment by kuhu12** [comment]
how can i link two skybox...by clicking on the side of the cube...i want to enter the next skybox?

**Comment by dnschneid** [comment]
The current Skybox has been [bought by Google](http://www.skyboximaging.com/blog/skybox-imaging-google).  It's hard to tell what the next Skybox will be; try looking into joining some space/satellite startup and hope for the best.

See #262 for more details.
