### ISSUE TITLE
chromebook froze during installation in shell

### ISSUE THREAD

**Issue by Beaudion** [dnschneid/crouton#2182]
I was trying to install ubuntu and typed in the following command: sudo sh ~/Downloads/crouton -r trusty -t unity,extension
During the installation the mouse and everything else froze so i had to do a hard shutdown. Now when i go back to the installation phase and type in the same command it says the program is already installed even though i have yet to make a password for when i get scrivener on here. My question is this: how do i delete what I downloaded so I can reinstall and make everything right?

**Comment by DennisLfromGA** [comment]
You might be able to gain access and finish your install via the command line as root, try this:
`sudo enter-chroot -u root`
It will probably tell you the setup script didn't finish and then prompt you to let it finish.

If that doesn't work, you may need to just delete your chroot and start over.

It may be the same as or related to issue [1994 - Keyboard and mouse get disabled during crouton install](https://github.com/dnschneid/crouton/issues/1994)
