### ISSUE TITLE
How to restore from sd card?

### ISSUE THREAD

**Issue by kgoode517** [dnschneid/crouton#2183]
I have successfully copied and saved my old chroot to my SD card. What is the command to restore it from there? How do I figure out the path for the command? It looks like I have two files 1. precise-20151012-1937.tar and 2. precise-20151012-1937.tar.part-aaab

**Comment by DennisLfromGA** [comment]
You can restore it with either `edit-chroot` or `crouton`. Take a look at this entry in the [README](https://github.com/dnschneid/crouton#a-backup-a-day-keeps-the-price-gouging-data-restoration-services-away) for suggestions. 
The *path* to your backed up chroot will most likely be somewhere in `/media/removable/`, maybe something like '`/media/removable/USB Drive`', etc. You can use something like this to find out:
`ls -l /media/removable`.

**Comment by kgoode517** [comment]
Dennis,

Thank you for taking the time to view and help me with my problem I have tried both commands and I had viewed the readme but here is the output I get from them. For edit-chroot -are precise, which is  my Linux version here is the output I receive /mnt/stateful_partition/crouton/chroots/precise already exists! Specify a second -r to overwrite it (dangerous). With crouton it doesn't recognize it as a command do you have any suggestions?

**Comment by kgoode517** [comment]
Furthermore, here is what happens when I pass a second -r parameter. I am thoroughly confused.
chronos@localhost / $ sudo edit-chroot -r precise
/mnt/stateful_partition/crouton/chroots/precise already exists! Specify a second -r to overwrite it (dangerous).
chronos@localhost / $ -r
bash: -r: command not found
chronos@localhost / $ sudo edit-chroot -r -r precise
Unable to find a tarball for precise. You can specify one with -f.
chronos@localhost / $ sudo edit-chroot -r -r -f precise
Detecting chroot name...

**Comment by DennisLfromGA** [comment]
> Thank you for taking the time to view and help me with my problem...

No problem.

> For edit-chroot -are precise, which is my Linux version here is the output I receive /mnt/stateful_partition/crouton/chroots/precise already exists!

The options `-are precise` aren't correct.
The `-a` and `-e`, in this case,  have no place in the restore operation and the chrootname of `precise` is only needed/used if you want to overwrite the name in the tarball.

Take a look at the descripton for 'edit-chroot' -

```
    -r          Restores a chroot from a tarball. The tarball path can be
                specified with -f or detected from name. If both are specified,
                restores to that name instead of the one in the tarball.
                Will not overwrite a chroot when restoring unless -r is
                specified twice.

    -f TARBALL  When used with -b, overrides the default tarball to back up to.
                If unspecified, assumes NAME-yyyymmdd-hhmm.tar[.gz], where .gz
                is included for unencrypted chroots, and not for encrypted ones.
                When used with -r, specifies the tarball to restore from.
                If TARBALL is a directory, automatic naming is still used.
                If multiple chroots are specified, TARBALL must be a directory.
```

> Furthermore, here is what happens when I pass a second -r parameter. I am thoroughly confused.
> chronos@localhost / $ sudo edit-chroot -r precise

Again, the options `-r precise` are not correct if there is a chroot named 'precise' installed.
If you want to overwrite an *existing* chroot named 'precise' you need a second `-r`,
plus, unless the tarball is in ~/Downloads and it's chrootname is 'precise', you need to specify the `-f` option along with the path to the tarball.

Perhaps one of these command strings will do what you want -

to restore a chroot named 'precise' when there is *none* installed:
`sudo edit-chroot -rf ~/Downloads/precise-201*.tar.gz`

to restore a chroot named 'precise' when there is *one already* installed:
`sudo edit-chroot -rrf ~/Downloads/precise-201*.tar.gz`

or, if the tarball is in ~/Downloads, and you want to restore a chroot named 'precise' when there is *one already* installed:
`sudo edit-chroot -rr precise`

I haven't tried that last command, I *always* use the `-f ...` option to ensure I restore from the tarball I intended.

-----
Hopefully what I have described above is correct, it's based on my understanding and experience which may not be :100:% valid... :/

It would probably be a good idea to try to read and understand the README where applicable, it may help to clear up a few points.

-DennisL

**Comment by kgoode517** [comment]
Dennis,
Unfortunately, that has not seemed to work for me as current the output I recieve tells me that the crosh doesn't recognize edit-chroot as a command. I have consulted the readme as well as the Crouton Command cheat sheet I was hoping this would be my solution. sudo edit-chroot -f /media/removable/SD\ Card/ -r -r precise alas, I am at a complete loss.

**Comment by DennisLfromGA** [comment]
> Unfortunately, that has not seemed to work for me as current the output I recieve tells me that the crosh doesn't recognize edit-chroot as a command.

Well 'crosh' won't, you have to open crosh and then type 'shell' to get a bash terminal session.
You were able to do that in the past looking at some of your outputs above. Possibly something went wrong and you need to re-install the scripts in `/usr/local/bin` by entering:

`sudo sh ~/Downloads/crouton -b`

**Comment by kgoode517** [comment]
My apologies, I have misspoken that was open within bash. Your command worked perfectly precise has been reinstalled onto my machine. However I was running kde before I backed up my chroot and now when I enter sudo startkde within bash it does not recognize it. Why would this be?

Here is my terminal output
 sudo startkde
Password: 
sudo: startkde: command not found
chronos@localhost / $ sudo enter-chroot startkde
Entering /usr/local/chroots/precise...
-su: 26: [[: not found
$DISPLAY is not set or cannot connect to the X server.
Not unmounting /usr/local/chroots/precise as another instance is using it.

**Comment by DennisLfromGA** [comment]
Let's see the output of: `sudo edit-chroot -al`
From there we can tell what's installed and what version(s) you're using.
It should be easier to diagnose that way.

**Comment by kgoode517** [comment]
Sure thing. Here is what it outputs
crosh> shell
chronos@localhost / $ sudo edit-chroot -al
Password: 
name: precise
encrypted: yes, unlocked
Entering /usr/local/chroots/precise...
crouton: version 1-20150924014025~master:04ff0c11
release: precise
architecture: amd64
xmethod: xorg
targets: kde
host: version 7390.59.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Mon Oct 12 19:42:09 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /usr/local/chroots/precise as another instance is using it.

**Comment by FullMetal0** [comment]
I am having a similar issue. I backed up my chroot with sudo edit-chroot -f /media/removable/SD\ Card/ -b trusty, I tried to restore with sudo edit-chroot -f /media/removable/SD\ Card/ -r trusty and am getting the same error of command not found. I usually would place the tar file in the downloads folder and restore with sudo sh ~/Downloads/crouton -f ~/Downloads/trusty.tar.gz, however my chroot is too large to be restored this way. No way can I start from scratch, please help! Thanks!

**Comment by DennisLfromGA** [comment]
@kgoode517 - It looks like you're chroot is behind by about 13 iterations of crouton, since you already have a backed up copy of it, it would probably best to update your chroot and see if it works, if not, come back here.

**Comment by DennisLfromGA** [comment]
@FullMetal0 - If your problem is similar, then the solution may be similar.

Download a fresh version of crouton from: https://goo.gl/fd3zc

Then restore your chroot using something like:

`sudo sh ~/Downloads/crouton -f /path/to/external/media/trusty-*.tar.gz`

Then re-install the scripts using: `sudo sh ~/Downloads/crouton -b`

If you don't have enough room on your Chromebook to do this anymore, then you may have to restore it to an external SD card and run it from there.

**Comment by kgoode517** [comment]
Dennis,

I cannot believe that I did not think to do this myself that fixed it entirely thank you so much for your help I would never have figured this out without it.

**Comment by DennisLfromGA** [comment]
Glad it worked out. :+1:
