### ISSUE TITLE
How to change the crouton toggle? I made a command but something is wrong with it and I don't know what?

### ISSUE THREAD

**Issue by Mediocorite** [dnschneid/crouton#2187]
So I wanted to change the toggle between Unity and chromebook. Because I have the integration installed I didn't install any browser over on ubuntu. So i have to constantly switch back and forth and with 4 keys that's frustiating. I'm noob so i only know basic in crouton. I was able to write a command in order to edit xbindkeysrc.scm

Command:-
sudo sh -c "echo \"(xbindkey '(control up) \"croutoncycle next\")\" >> /etc/crouton/xbindkeysrc.scm"

But that gives an error of :- 
sh: cannot create /etc/crouton/xbindkeysrc.scm: Directory nonexistent

What did I do wrong ??

**Comment by dnschneid** [comment]
You probably want to run that inside the chroot, not outside.  You'll also have to modify /usr/local/bin/croutontriggerd (also inside the chroot).  See #280 for more details.
