### ISSUE TITLE
My Asus C300MA  is not able to read the crouton download file. what is the problem here?

### ISSUE THREAD

**Issue by gmutchko** [dnschneid/crouton#2188]

**Comment by DennisLfromGA** [comment]
You first download crouton via the link: https://goo.gl/fd3zc

then enter a crosh terminal session -

<kbd>Ctrl+Alt+t</kbd> 

then get into a bash shell -

`shell`

then do the crouton thing -

`sudo sh ~/Downloads/crouton ...`

**Comment by gmutchko** [comment]
It's not letting me download from the link. I click it and the download
starts in the bottom corner but when its done it says it can't reconize the
file

**Comment by DennisLfromGA** [comment]
Don't select it from within Chrome or the Files app, it has to be invoked in a terminal like I detailed above.
It might be a good idea to first review the README, especiall the part about '[Usage](https://github.com/dnschneid/crouton#usage)'.
