### ISSUE TITLE
Crouton died on me: No Chromium OS X server is available.

### ISSUE THREAD

**Issue by myrvolln** [dnschneid/crouton#2189]
Hi!
I am not an experienced linux user, but i recently bought a chromebook for linux purposes. After following the guidelines for updating the chroot from the website (and answering 'Y' to everything) it suddenly doesnt want to boot. Amoung the things the dev mode terminal tells me after unmounting is "No Chromium OS X server is available.". As I am quite the newbie I havent tickled around in the more advanced corners of ubuntu, so it's probably (hopefully) quite simple. Do anyone have a clue for what is going on here? :)

**Comment by ReconPirate** [comment]
So just to start off from the basics here, when fully powered off (by holding the power button till the unit fully powers off (can be up to 30 seconds))  and then powered back on it does it go through the "os verification is off" screen?( then some amount of beeping and would start the os (if all things were well)

Just wondering where you are getting up to at the boot process, because easy fix if you get to that screen would be just to re-enable protection which effectively reformats the unit and then can give it another go, as it will be at out of the box state.

**Comment by DennisLfromGA** [comment]
>  it go through the "os verification is off" screen?( then some amount of beeping and would start the os (if all things were well)

You can circumvent that delay by pressing <kbd>Ctrl+d</kbd>

**Comment by myrvolln** [comment]
Hi again and thanks for the fast replies. Starting the computer goes without a hitch. The problem occurs when activating ubuntu from the developer terminal in chrome OS. "shell" followed by the "sudo startunity" command. I can copy/paste the entire thing if it would help, but its a quite large wall of text.

**Comment by DennisLfromGA** [comment]
> The problem occurs when activating ubuntu from the developer terminal in chrome OS. "shell" followed by the "sudo startunity" command. I can copy/paste the entire thing if it would help, but its a quite large wall of text.

That might be the best way to let us see what's going on. 
You don't have to copy-n-paste it here though, you can upload the output to a website and give us the link. [Paste.bin](http://pastebin.com/) and [gist.github.com](https://gist.github.com/) are just a couple of sites that provide this service.

Also, what will be helpful is to show us the output of: `sudo edit-chroot -al`

**Comment by myrvolln** [comment]
Everything:

Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:54:39 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=ef87ddb1-c4c2-2943-b4be-417e429094b2/PARTNROFF=1 hashtree=PARTUUID=ef87ddb1-c4c2-2943-b4be-417e429094b2/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=c1dc6d700aee10315215a9f8ad88306b4a17b8bf salt=3a69c783a32d9615f08427b8e63618175716d8136c4c1c14a99dbf2f8ffc5e76" noinitrd vt.global_cursor_default=0 kern_guid=ef87ddb1-c4c2-2943-b4be-417e429094b2 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Oct 27 11:23:07 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20150924014025~master:04ff0c11
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 7390.61.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:54:39 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...

-sudo edit-chroot -al
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150924014025~master:04ff0c11
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 7390.61.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:54:39 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...


Hope this clarifies it a bit :)

**Comment by DennisLfromGA** [comment]
> No Chromium OS X server is available.

I'm getting the same thing on my wily chroot with both gnome and unity - just after an update.
```
name: wily
encrypted: no
Entering /var/crouton/chroots/wily...
crouton: version 1-20151104200003~master:2a1fc9da
release: wily
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,cli-extra,gnome-desktop,unity,chrome-beta
host: version 7520.49.0 (Official Build) beta-channel parrot 
kernel: Linux localhost 3.8.11 #1 SMP Wed Nov 18 21:09:02 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by DennisLfromGA** [comment]
***# UPDATE #***

I got the very same 'No Chromium OS X server is available.' error on my trusty chroot but it *still* works, even with other errors too so I don't think that message is where the problem originates.

Unity is working great even though these errors are displayed:
```
No Chromium OS X server is available.
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
```

Here's my trusty chroot:
```
crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,cli-extra,unity,chrome-beta
host: version 7520.49.0 (Official Build) beta-channel parrot 
kernel: Linux localhost 3.8.11 #1 SMP Wed Nov 18 21:09:02 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by DennisLfromGA** [comment]
**# UPDATE 2 #**

My default xmethod is 'xorg' so I tried 'xiwi' and had success with wily/gnome but wily/unity still draws a blank (pun intended), but I get a mouse cursor.

After successfully opeing xiwi:wily/gnome, I tried xorg:wily/gnome and it is now working. I don't know if I broke something loose so to speak but it now works, repeatedly using either xmethod.

Unfortunately, both xorg:wily/unity and xiwi:wily/unity are still broken, blank screen.

**Comment by jpw1116** [comment]
I'm experiencing the same blank screen after sudo startunity . . . all after changing my Chrome OS channel to dev for the first time (hoping it would have an upstream kernel but no-go; still 3.10.18). 

Anyway, the blank screen eventually loads up the DE no problem, after a seemingly too long delay. I think CTRL-ALT-SHIFT-RIGHT and LEFT to pop back into Chrome OS *may* help. 

Note, I've also noticed the cursor is dead at times in the Linux session--but not the left/right mouse buttons on a Bluetooth mouse. Twice, though, I've been able to resume full cursoring via the trackpad or the mouse, once after a reboot, once not.

It's all flaky enough for me to presume that a crouton update wouldn't hurt. . . .

**Comment by josephcureton** [comment]
I am experiencing the same problems. When I `sudo startunity` after a version upgrade to Ubuntu distro I get:

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: unity-desktop
host: version 7834.60.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP Thu Mar 10 05:49:31 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...

My precise chroot:

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: unity-desktop
host: version 7834.60.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP Thu Mar 10 05:49:31 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Any new thoughts?? Thanks!

**Comment by roger77** [comment]
Same problem here:
`chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Mar 10 07:47:18 PST 2016 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=fc3826f3-41db-c745-840c-f367513cad6b/PARTNROFF=1 hashtree=PARTUUID=fc3826f3-41db-c745-840c-f367513cad6b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=56f820ed1aca5bd6a3f3a2e708f95935ae390eb8 salt=80e1b0082f6abdbf0a22af65b4edd028f1de9bedb511b03b1ffc533604950b5d" noinitrd vt.global_cursor_default=0 kern_guid=fc3826f3-41db-c745-840c-f367513cad6b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  gpt 
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Mar 23 10:01:29 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20160125112815~b78906bc
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,x11,extension,unity,unity-desktop,xiwi,touch
host: version 7834.60.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Thu Mar 10 07:47:18 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch`

`crouton: version 1-20160125112815~b78906bc
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,x11,extension,unity,unity-desktop,xiwi,touch
host: version 7834.60.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Thu Mar 10 07:47:18 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes`

**Comment by jpw1116** [comment]
Just offering this, straight out of my notes from last summer when I had a server issue, and the following command did repair it. Use at your own risk:
```
# Exit the chroot and run from terminal in Chrome OS, e.g., chronos@localhost / $:

$ sudo CROUTON_BRANCH=x11.freon sh -e ~/Downloads/crouton -u -n trusty  
```

**Comment by DennisLfromGA** [comment]
@jpw1116 - That 'freon' branch has already been merged so I don't think that'll help this situation.

**Comment by roger77** [comment]
I downloaded the latest crouton and just rerun:
`sudo sh -e ~/Downloads/crouton -u -n trusty `

this fixed my problem even if croutonversion reported there was no new version. I hope it helps.

**Comment by divx118** [comment]
@roger77 FYI There doesn't need to be a new crouton version. If you do the update, then some things like audio gets recompiled or some things changed in chromeos where crouton needs to adapt your chroot to keep working with the new chromeos update. That is why it is important to do a crouton update after a chromeos update.
