### ISSUE TITLE
How to find min, max and mean of wordcount from text file in hadoop mapreduce

### ISSUE THREAD

**Issue by sathishpakalapati** [dnschneid/crouton#2192]
public class MaxMinReducer extends Reducer<Text, IntWritable, Text, IntWritable> {
	 int max_sum=0; 
	 int mean=0;
	 int count=0;
	 Text max_occured_key=new Text();
	 Text mean_key=new Text("Mean : ");
	 Text count_key=new Text("Count : ");
	 int min_sum=Integer.MAX_VALUE; 
     Text min_occured_key=new Text();

	 public void reduce(Text key, Iterable<IntWritable> values, Context context) throws IOException, InterruptedException {
	       int sum = 0;           

	       for (IntWritable value : values) {
	             sum += value.get();
	             count++;
	       }
	       
	       if(sum < min_sum)
	          {
	              min_sum= sum;
	              min_occured_key.set(key);        
	          }     

	       if(sum > max_sum) {
	           max_sum = sum;
	           max_occured_key.set(key);
	       }          
	       
	       mean=max_sum+min_sum/count;
	  }

	 @Override
	 protected void cleanup(Context context) throws IOException, InterruptedException {
	       context.write(max_occured_key, new IntWritable(max_sum));   
	       context.write(min_occured_key, new IntWritable(min_sum));   
	       context.write(mean_key , new IntWritable(mean));   
	       context.write(count_key , new IntWritable(count));   
	 }
}

Here I am writing minimum,maximum and mean of wordcount.

My input file :

high low medium high low high low large small medium

Actual output is :

high - 3------maximum

low - 3--------maximum

large - 1------minimum

small - 1------minimum

but i am not getting above output ...can anyone please help me?

**Comment by tedm** [comment]
I always run this code when crouton is broken or gives a black screen ;)

**Comment by mark-hahn** [comment]
Isn't anyone going to tell him/her about their mistaken posting?

**Comment by dnschneid** [comment]
Dunno.  Maybe we should help them with their homework first?  

Anyway, @sathishpakalapati, read [this](https://wiki.haskell.org/MapReduce_as_a_monad); it should explain everything you need to know to get your assignment working.

Closing as #262.

**Comment by sathishpakalapati** [comment]
where is the solution?

**Comment by sathishpakalapati** [comment]
is this invalid question?

**Comment by sathishpakalapati** [comment]
And why are you closing this issue .. ..you are not giving any solution.....

**Comment by DennisLfromGA** [comment]
@sathishpakalapati  - I think the crouton developer and other posters are trying to tell you that your question/problem doesn't pertain to 'crouton', specifically or otherwise. If it does, then explain how and you might get some help.

**Comment by sathishpakalapati** [comment]
kk..
