### ISSUE TITLE
Update seems to be broken

### ISSUE THREAD

**Issue by Snowflake6** [dnschneid/crouton#2193]
Tried to update before launching crouton today, running _utopic_.  Same chroot has been operating quite happily for a month or two, up until now.

[20151016 - Edited to correct unity to _utopic_]

Log:

---

chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n utopic
Downloading latest crouton installer...
###### ################################################################## 100.0%

/usr/local/chroots/utopic already exists; updating it...
WARNING: utopic is an unsupported release.
You will likely run into issues, but things may work with some effort.
If this is a surprise to you, utopic has probably reached end of life.
Refer to https://goo.gl/Z5LGVD for upgrade instructions.
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing startcli into the host...
Installing croutonpowerd into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startunity into the host...
Installing crouton-noroot into the chroot...
Installing startunity into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing crouton-unity-autostart into the chroot...
Installing unity-autostart.desktop into the chroot...
Installing unity-profiled into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Ign http://dl.google.com stable InRelease
Hit http://dl.google.com stable Release.gpg  
Hit http://dl.google.com stable Release  
Hit http://apt.insynchq.com utopic InRelease  
Hit http://dl.google.com stable/main amd64 Packages  
Hit http://dl.google.com stable/main i386 Packages  
Ign http://archive.ubuntu.com utopic InRelease  
Ign http://dl.google.com stable/main Translation-en  
Ign http://archive.ubuntu.com utopic-updates InRelease
Ign http://archive.ubuntu.com utopic-security InRelease
Ign http://archive.ubuntu.com utopic Release.gpg
Ign http://archive.ubuntu.com utopic-updates Release.gpg
Hit http://apt.insynchq.com utopic/non-free amd64 Packages
Ign http://archive.ubuntu.com utopic-security Release.gpg
Hit http://apt.insynchq.com utopic/contrib amd64 Packages
Ign http://archive.ubuntu.com utopic Release  
Hit http://apt.insynchq.com utopic/non-free i386 Packages
Ign http://archive.ubuntu.com utopic-updates Release
Hit http://apt.insynchq.com utopic/contrib i386 Packages
Ign http://archive.ubuntu.com utopic-security Release  
Ign http://archive.ubuntu.com utopic/main Sources/DiffIndex
Ign http://archive.ubuntu.com utopic/restricted Sources/DiffIndex
Ign http://archive.ubuntu.com utopic/universe Sources/DiffIndex
Ign http://archive.ubuntu.com utopic/multiverse Sources/DiffIndex
Ign http://archive.ubuntu.com utopic/main amd64 Packages/DiffIndex
Ign http://apt.insynchq.com utopic/contrib Translation-en
Ign http://apt.insynchq.com utopic/non-free Translation-en
Ign http://archive.ubuntu.com utopic/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic/multiverse amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic/main i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic/restricted i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic/universe i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic/multiverse i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-updates/main Sources/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/restricted Sources/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/universe Sources/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/multiverse Sources/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/main amd64 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/restricted amd64 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/universe amd64 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/multiverse amd64 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/main i386 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/restricted i386 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/universe i386 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-updates/multiverse i386 Packages/DiffIndex  
Ign http://archive.ubuntu.com utopic-security/main Sources/DiffIndex  
Ign http://archive.ubuntu.com utopic-security/restricted Sources/DiffIndex
Ign http://archive.ubuntu.com utopic-security/universe Sources/DiffIndex
Ign http://archive.ubuntu.com utopic-security/multiverse Sources/DiffIndex
Ign http://archive.ubuntu.com utopic-security/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-security/restricted amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-security/universe amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-security/multiverse amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-security/main i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-security/restricted i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-security/universe i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic-security/multiverse i386 Packages/DiffIndex
Ign http://archive.ubuntu.com utopic/main Translation-en
Ign http://archive.ubuntu.com utopic/multiverse Translation-en
Ign http://archive.ubuntu.com utopic/restricted Translation-en
Ign http://archive.ubuntu.com utopic/universe Translation-en
Ign http://archive.ubuntu.com utopic-updates/main Translation-en
Ign http://archive.ubuntu.com utopic-updates/multiverse Translation-en
Ign http://archive.ubuntu.com utopic-updates/restricted Translation-en
Ign http://archive.ubuntu.com utopic-updates/universe Translation-en
Ign http://archive.ubuntu.com utopic-security/main Translation-en
Ign http://archive.ubuntu.com utopic-security/multiverse Translation-en
Ign http://archive.ubuntu.com utopic-security/restricted Translation-en
Ign http://archive.ubuntu.com utopic-security/universe Translation-en
Err http://archive.ubuntu.com utopic/main Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/restricted Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/universe Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/multiverse Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/main amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/universe amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/multiverse amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/main i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/restricted i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/universe i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic/multiverse i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/main Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/restricted Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/universe Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/multiverse Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/main amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/universe amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/multiverse amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/main i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/restricted i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/universe i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-updates/multiverse i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/main Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/restricted Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/universe Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/multiverse Sources
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/main amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/restricted amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/universe amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/multiverse amd64 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/main i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/restricted i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/universe i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
Err http://archive.ubuntu.com utopic-security/multiverse i386 Packages
  404  Not Found [IP: 91.189.88.149 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/main/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/restricted/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/multiverse/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/main/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-updates/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/main/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/restricted/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/universe/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/multiverse/source/Sources  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic-security/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.149 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
apt-transport-https is already the newest version.
ca-certificates is already the newest version.
sudo is already the newest version.
wget is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target cli-extra...
Reading package lists... Done
Building dependency tree  
Reading state information... Done
kbd is already the newest version.
openssh-client is already the newest version.
dbus is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing target audio...
Fetching CRAS (branch 1d79eb5178711820ee38055e0eb53999b54687f9)...
--2015-10-15 05:54:38--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/1d79eb5178711820ee38055e0eb53999b54687f9.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 173.194.203.82
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.203.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.CPh6nZ/adhd.tar.gz'

```
 0K .......... .......... .......... .......... ..........  697K
50K .......... .......... .......... .......... .......... 1.39M
```

   100K .......... .......... .......... .......... .......... 1.49M
   150K .......... .......... .......... .......... .......... 1.65M
   200K .......... .......... .......... .......... .......... 1.95M
   250K .......... .......... .......... .......... .......... 1.79M
   300K .......... .......... .......... .......... ..........  598K
   350K .......... .......... .......... .......... .......... 3.05M
   400K .......... .......... .......... .......... .......... 1.89M
   450K ...                                                    16.6M=0.3s

2015-10-15 05:54:38 (1.28 MB/s) - '/tmp/crouton-cras.CPh6nZ/adhd.tar.gz' saved [464655]

Reading package lists... Done
Building dependency tree  
Reading state information... Done
alsa-utils is already the newest version.
libasound2:i386 is already the newest version.
libspeexdsp1:i386 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
gcc is already the newest version.
gcc-multilib is already the newest version.
pkg-config is already the newest version.
Suggested packages:
  glibc-doc:i386 manpages-dev:i386 speex:i386
The following NEW packages will be installed:
  libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 linux-libc-dev:i386
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 2522 kB of archives.
After this operation, 13.3 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libspeex1:i386 linux-libc-dev:i386 libc6-dev:i386 libspeex-dev:i386 libspeexdsp-dev:i386
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/utopic...
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
> 404 Not Found [IP: 91.189.88.149 80]
> Err http://archive.ubuntu.com utopic/restricted Sources

To me, that long string of '404 Not Found's looks like you may have had a network glitch or the site was temporarily down. I would reboot and try again...

**Comment by Snowflake6** [comment]
I'd agree with you, except i'm getting the same error when connected to home, work, and while tethered to my cell phone.

This site suggests it's possible that utopic support might have been moved to a different server... The error messages match, although it's for a yet older version.

https://smyl.es/how-to-fix-ubuntudebian-apt-get-404-not-found-package-repository-errors-saucy-raring-quantal-oneiric-natty/

I forget, is it possible to do an apt-get dist-upgrade from within crouton?

**Comment by Snowflake6** [comment]
Further update, yes, it appears utopic support ended in late July.  I'm surprised that the package files have been removed from archive.ubuntu.com though, and haven't been moved to old-releases.ubuntu.com.  So i'll need to update to a newer version, and likely i'll need to re-syncrhonize my google drive as well... I use insync to keep a local copy of my Google drive in my crouton.  I really wish there was an option to upgrade the distribution within the crouton, so I don't have to blow away the Google drive and re-sync.
