### ISSUE TITLE
Crouton supported Chromebook models?

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#2195]
I wonder which Chromebook models are supported by Crouton. Because I'd never buy a Chromebook without Crouton/Linux support. On the [Crouton Wiki] (https://github.com/dnschneid/crouton/wiki) here's a header saying "Devices" and then there's a link to a table on the [Wikipedia site about the Chromebook] (https://en.wikipedia.org/wiki/Chromebook#Chromebook_models) in general  which lists all Chromebook models to date. But are *all these models* supported by Crouton? And if not: shouldn't we make a list of supported models?

**Comment by tedm** [comment]
It varies from week to week, chromium OS and Crouton version. If you have it working, don't upgrade if you don't need to, or just do security upgrades. At some point, probably all chromebooks worked.

**Comment by dnschneid** [comment]
Thanks for the vote of confidence, Ted :)

crouton should work with all Chromebooks.  We have automated testing across pretty much every chipset in use.  The main variation between devices you'll see is whether there's GPU acceleration (most but not all Intel platforms), and whether closed-source software will work (all Intel platforms).

**Comment by tedm** [comment]
@dnschneid I'm mentioning it from a real-life crouton user point of view. e.g. setting up demos that work with a target date, but losing sleep that a reboot might happen with chromeos upgrade before the demo, or server use, where you want to maximize availability over new widget additions. I'd be pleased to keep a list of what's working, or not working at any given time, maybe update weekly?

**Comment by tedm** [comment]
@dnschneid I also, would have little use for a Chromebook without Crouton. I'd probably buy a tablet over a chromebook if it weren't for Crouton.

**Comment by MeneerJansen** [comment]
@dnschneid : Thanks for clearing that up! :-)

I love my Chr.book so much, might buy me another one if this one breaks up... Use it daily for office work. The on-line versions of G-office and MS-Office do not support features like cross referencing and multiple columns so I have to use proper versions like Libre Office and WPS (Kingsoft) Office.

And, if I'm not mistaken, an Intel based one would be the best choice.
