### ISSUE TITLE
Support for Neverware's Cloudready builds?

### ISSUE THREAD

**Issue by ojdon** [dnschneid/crouton#2196]
Hi there. I'm using Neverware's [cloudready](http://www.neverware.com/free/#freedetails) version of Chromium OS due to the vanilla builds not supporting my wireless card. I was just wondering if it's possible to get crouton installed on these images as they are a few versions out of date compared to vanilla builds of Chromium OS, therefore getting the `Your version of Chromium OS is extraordinarily old.` message.

**Comment by DennisLfromGA** [comment]
Yup, I ran into the same thing and had to modify a couple of crouton files to get it working, see https://github.com/dnschneid/crouton/issues/2126#issuecomment-148827233.

I got it installed but can't run any desktops in either xmethod 'xorg' or 'xiwi'. `enter-chroot` and `startcli` work great though.

**Comment by gnidorah** [comment]
No luck man, their stuff is always few releases behind and is too tweaked. But you may compile Chromium OS for PC by yourself if you have some time. Just follow an easy guide: https://gist.github.com/gnidorah/8ca4f7db3af38b1622a8

**Comment by drinkcat** [comment]
Generally yes, we'd like to support Chromium OS derivatives. But we need clear bug descriptions, and, ideally, pull requests.
