### ISSUE TITLE
Cannot install Crouton

### ISSUE THREAD

**Issue by Squooshi** [dnschneid/crouton#2197]
Hello! I need help with this please. I can't seem to find an answer for this and I've searched everywhere.
Alright so I had to load Chrome OS v.36 because it's the only version working for me on Developer Mode. I would update but there's no use in doing so.
I have to install Linux and am not allowed to do so because I get the following message:

Downloading latest crouton installer...
######################################################################## 100.0%
Your version of Chromium OS is extraordinarily old.
If there are updates pending, please reboot and try again.
Otherwise, you may not be getting automatic updates, in which case you should
post your update_engine.log from chrome://system to http://crbug.com/296768 and
restore your device using a recovery USB: https://goo.gl/AZ74hj

Is there anything I can do about it? Perhaps get a previous version of Crouton working with Chrome 36? Or any other way to resolve this or alternatives for Linux? I'd really appreciate the help.
The chromebook I have is a Dell 11.

**Comment by DennisLfromGA** [comment]
Yup, I ran into the same thing and had to modify a couple of crouton files to get it working, see https://github.com/dnschneid/crouton/issues/2126#issuecomment-148827233

**Comment by Squooshi** [comment]
Oh alright!
Also I'm sorry but I'm not very good at this modifying files/changing much in Crosh and etc.
Would you maybe be kind enough to explain what I have to do? As in how do I change build/wrapper.sh and installer/main.sh ?
Sorry for bothering! And thank you for helping me out already!

**Comment by DennisLfromGA** [comment]
I have re-made 'crouton' with the changes, I'll send you a download link to it when I get back to that Chromebook - soon'ish...

**Comment by Squooshi** [comment]
Wow thank you so much! I greatly appreciate your help a lot!

**Comment by DennisLfromGA** [comment]
@Squooshi - Below is a link to the version of 'crouton' where I made a couple of minor changes so it would work on both Chrome OS and Chromium. It's based on the latest crouton commit: version 1-20151013174138~master:488c9e21.

I renamed it 'crouton.r39' since it's set to 'CROS_MIN_VERS=39' and to tell it apart from the unmodded one - [crouton.r39]
(https://goo.gl/PWQTI5)

**Comment by Squooshi** [comment]
@DennisLfromGA Thanks, I got it to install I think and set up a user and a password like normal, but when I try to actually: sudo startxfce4
it gives me the following: 
Entering /mnt/stateful_partition/crouton/chroots/precise...
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

And then it doesn't open xfce at all. I restarted and tried again just in case, but it didn't seem to work. Is there something I'm doing wrong?

**Comment by DennisLfromGA** [comment]
Yup, there is something wrong but it's not just you.
Like I mentioned in my comment earlier, I also got it installed but I can't run any desktops in either xmethod - 'xorg' or 'xiwi'.
However both `enter-chroot` and `startcli` work great though if all you need is a command-line.

Hopefully some of the heavies will weigh in and help figure this thing out...
