### ISSUE TITLE
I can't start crouton

### ISSUE THREAD

**Issue by kylethomas1029** [dnschneid/crouton#2199]
The error I'm getting is :

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by sedlund** [comment]
Wondering whats in /tmp/Xorg.crouton.1.log as stated in the error

**Comment by kylethomas1029** [comment]
I tried to access it and this is what I got, it says that permission is denied.

chronos@localhost /tmp $ ls
crouton-lock                                 disk-network-wifi-online       uptime-login-start-signin-screen
disk-boot-complete                           disk-network-wifi-ready        uptime-login-success
disk-chrome-exec                             disk-post-startup              uptime-login-wait-for-signin-state-initialize
disk-chrome-first-render                     disk-pre-startup               uptime-network-wifi-association
disk-chrome-main                             disk-shill-start               uptime-network-wifi-configuration
disk-lockbox-cache-end                       firmware-boot-time             uptime-network-wifi-failure
disk-lockbox-cache-exec                      mount-encrypted.log            uptime-network-wifi-idle
disk-lockbox-cache-start                     update_engine_update_recorded  uptime-network-wifi-online
disk-login-prompt-visible                    uptime-boot-complete           uptime-network-wifi-ready
disk-login-start-signin-screen               uptime-chrome-exec             uptime-post-startup
disk-login-success                           uptime-chrome-first-render     uptime-pre-startup
disk-login-wait-for-signin-state-initialize  uptime-chrome-main             uptime-shill-start
disk-network-wifi-association                uptime-lockbox-cache-end       Xorg.crouton.1.log
disk-network-wifi-configuration              uptime-lockbox-cache-exec      Xorg.crouton.1.log.old
disk-network-wifi-failure                    uptime-lockbox-cache-start
disk-network-wifi-idle                       uptime-login-prompt-visible

chronos@localhost /tmp $  ./Xorg.crouton.1.log
bash: ./Xorg.crouton.1.log: Permission denied
chronos@localhost /tmp $

**Comment by sedlund** [comment]
sudo cat /tmp/Xorg.crouton.1.log

**Comment by caryw1** [comment]
I have the exact same problem.  Brand new Chromebook, recently updated, first install of Crouton with:
sudo sh ~/Downloads/crouton -t kde

Output from /tmp/Xorg.crouton.1.log:
chronos@localhost /tmp $ cat Xorg.crouton.1.log
[  1357.585] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[  1357.587] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[  1357.587] X Protocol Version 11, Revision 0
[  1357.587] Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
[  1357.587] Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Sep 18 00:34:04 PDT 2015 armv7l
[  1357.587] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=811ed7d6-10d3-6a4c-bbeb-5b41f09e981d/PARTNROFF=1 hashtree=PARTUUID=811ed7d6-10d3-6a4c-bbeb-5b41f09e981d/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=e0f59c0791ea08312fd366884d39458309355dea salt=7ffbfb0e6fd7ca8668047c436e1cf01973e8a6f739e7b8cb558d3a146d2c68f3" noinitrd vt.global_cursor_default=0 kern_guid=811ed7d6-10d3-6a4c-bbeb-5b41f09e981d  
[  1357.588] Build Date: 05 November 2013  03:23:26PM
[  1357.588] xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
[  1357.588] Current version of pixman: 0.30.2
[  1357.588]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[  1357.588] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1357.588] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Oct 20 01:52:05 2015
[  1357.589] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  1357.589] (==) No Layout section.  Using the first Screen section.
[  1357.589] (==) No screen section available. Using defaults.
[  1357.589] (**) |-->Screen "Default Screen Section" (0)
[  1357.589] (**) |   |-->Monitor "<default monitor>"
[  1357.590] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  1357.590] (==) Automatically adding devices
[  1357.590] (==) Automatically enabling devices
[  1357.590] (==) Automatically adding GPU devices
[  1357.590] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1357.590]    Entry deleted from font path.
[  1357.590] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1357.590]    Entry deleted from font path.
[  1357.590] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1357.590]    Entry deleted from font path.
[  1357.590] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  1357.590]    Entry deleted from font path.
[  1357.590] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1357.590]    Entry deleted from font path.
[  1357.590] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1357.590]    Entry deleted from font path.
[  1357.590] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  1357.590]    Entry deleted from font path.
[  1357.590] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[  1357.590] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  1357.590] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[  1357.590] (II) Loader magic: 0xb6f65e58
[  1357.590] (II) Module ABI versions:
[  1357.590]    X.Org ANSI C Emulation: 0.4
[  1357.590]    X.Org Video Driver: 13.0
[  1357.590]    X.Org XInput driver : 18.0
[  1357.590]    X.Org Server Extension : 7.0
[  1357.591] (II) config/udev: Adding drm device (/dev/dri/card1)
[  1357.591] setversion 1.4 failed
[  1357.592] Initializing built-in extension Generic Event Extension
[  1357.592] Initializing built-in extension SHAPE
[  1357.592] Initializing built-in extension MIT-SHM
[  1357.592] Initializing built-in extension XInputExtension
[  1357.592] Initializing built-in extension XTEST
[  1357.592] Initializing built-in extension BIG-REQUESTS
[  1357.592] Initializing built-in extension SYNC
[  1357.592] Initializing built-in extension XKEYBOARD
[  1357.592] Initializing built-in extension XC-MISC
[  1357.592] Initializing built-in extension SECURITY
[  1357.592] Initializing built-in extension XINERAMA
[  1357.592] Initializing built-in extension XFIXES
[  1357.592] Initializing built-in extension RENDER
[  1357.592] Initializing built-in extension RANDR
[  1357.592] Initializing built-in extension COMPOSITE
[  1357.592] Initializing built-in extension DAMAGE
[  1357.592] Initializing built-in extension MIT-SCREEN-SAVER
[  1357.592] Initializing built-in extension DOUBLE-BUFFER
[  1357.592] Initializing built-in extension RECORD
[  1357.592] Initializing built-in extension DPMS
[  1357.592] Initializing built-in extension X-Resource
[  1357.592] Initializing built-in extension XVideo
[  1357.592] Initializing built-in extension XVideo-MotionCompensation
[  1357.592] Initializing built-in extension XFree86-VidModeExtension
[  1357.593] Initializing built-in extension XFree86-DGA
[  1357.593] Initializing built-in extension XFree86-DRI
[  1357.593] Initializing built-in extension DRI2
[  1357.593] (II) LoadModule: "glx"
[  1357.594] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  1357.594] (II) Module glx: vendor="X.Org Foundation"
[  1357.594]    compiled for 1.13.0, module version = 1.0.0
[  1357.594]    ABI class: X.Org Server Extension, version 7.0
[  1357.595] (==) AIGLX enabled
[  1357.595] Loading extension GLX
[  1357.595] (==) Matched modesetting as autoconfigured driver 0
[  1357.595] (==) Matched fbdev as autoconfigured driver 1
[  1357.595] (==) Assigned the driver to the xf86ConfigLayout
[  1357.595] (II) LoadModule: "modesetting"
[  1357.595] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  1357.596] (II) Module modesetting: vendor="X.Org Foundation"
[  1357.596]    compiled for 1.13.0, module version = 0.5.0
[  1357.596]    Module class: X.Org Video Driver
[  1357.596]    ABI class: X.Org Video Driver, version 13.0
[  1357.596] (II) LoadModule: "fbdev"
[  1357.597] (WW) Warning, couldn't open module fbdev
[  1357.597] (II) UnloadModule: "fbdev"
[  1357.597] (II) Unloading fbdev
[  1357.597] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1357.597] (==) Matched modesetting as autoconfigured driver 0
[  1357.597] (==) Matched fbdev as autoconfigured driver 1
[  1357.597] (==) Assigned the driver to the xf86ConfigLayout
[  1357.597] (II) LoadModule: "modesetting"
[  1357.597] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  1357.597] (II) Module modesetting: vendor="X.Org Foundation"
[  1357.597]    compiled for 1.13.0, module version = 0.5.0
[  1357.597]    Module class: X.Org Video Driver
[  1357.597]    ABI class: X.Org Video Driver, version 13.0
[  1357.598] (II) UnloadModule: "modesetting"
[  1357.598] (II) Unloading modesetting
[  1357.598] (II) Failed to load module "modesetting" (already loaded, -1207990040)
[  1357.598] (II) LoadModule: "fbdev"
[  1357.598] (WW) Warning, couldn't open module fbdev
[  1357.598] (II) UnloadModule: "fbdev"
[  1357.598] (II) Unloading fbdev
[  1357.598] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1357.598] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  1357.598] (--) using VT number 7

[  1357.612] (WW) Falling back to old probe method for modesetting
[  1357.612] (II) modesetting(0): using default device
[  1357.612] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  1357.612] (II) modesetting(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 24/32
[  1357.612] (==) modesetting(0): Depth 24, (--) framebuffer bpp 32
[  1357.612] (==) modesetting(0): RGB weight 888
[  1357.612] (==) modesetting(0): Default visual is TrueColor
[  1357.613] (II) modesetting(0): ShadowFB: preferred NO, enabled NO
[  1357.613] (EE) modesetting(0): KMS setup failed
[  1357.613] (II) UnloadModule: "modesetting"
[  1357.613] (EE) Screen(s) found, but none have a usable configuration.
[  1357.613] 
Fatal server error:
[  1357.613] no screens found
[  1357.613] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[  1357.613] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  1357.613] (EE) 
[  1357.628] Server terminated with error (1). Closing log file.

Downgraded ("reverted") the Chrome OS and the same problem persists.

**Comment by kylethomas1029** [comment]
mine crashes in the same spot and the log in almost exactly the same

**Comment by tedm** [comment]
kde is kind of funky. Try xfce, lxde and if those don't work, please provide your config, and if it's not resolved in a day or two, I'll put the system on the "crouton hall of shame" website ;)

**Comment by caryw1** [comment]
Hello tedm,

I actually did try again with xfce with extremely similar results ("no screens found").  The log I pasted may actually be from xfce, I've now gone back-and-forth so many times it's hard to keep track.

I just tried again with a fresh "Powerwash" and experienced the same results.  The box is question is a brand new ASUS C201.

I can enter-chroot and use CLI tools without trouble, I just can't start X.

Thank you!

**Comment by kylethomas1029** [comment]
I'm also using a ASUS C201. I attempted to use both unity and xfce with the same results

**Comment by sedlund** [comment]
interested in if you can install the xiwi target and it works?

**Comment by kylethomas1029** [comment]
Is this useful?

chronos@localhost / $ sudo startunity -X -xiwi
/mnt/stateful_partition/crouton/chroots/precise does not contain XMETHOD ''

chronos@localhost / $ sudo startunity -X -Xorg
/mnt/stateful_partition/crouton/chroots/precise does not contain XMETHOD ''

chronos@localhost / $ sudo enter-chroot
Enter encryption passphrase for precise: 
Entering /mnt/stateful_partition/crouton/chroots/precise...

(precise)kyle@localhost:~$ xiwi gimp
-su: xiwi: command not found

(precise)kyle@localhost:~$ xiwi -T gimp
-su: xiwi: command not found

**Comment by tedm** [comment]
OK, so it seems like the Asus C201 has a couple of user reported outages today. I think they'll be resolved soon. 

https://github.com/tedm/chromebook_notes/issues/1

**Comment by DennisLfromGA** [comment]
@kylethomas1029 - It would be interesting to know just what you installed.
Let's see the output of: `sudo edit-chroot -al`

**Comment by kylethomas1029** [comment]
I'll get back to you later today, I'm currently at work

**Comment by kylethomas1029** [comment]
@DennisLfromGA Here is what it gave back
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20151013174138~master:488c9e21
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 7390.61.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP Thu Oct 15 04:46:52 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by DennisLfromGA** [comment]
`xmethod: xorg` looks strange to me, I thought ARMs were now using `xiwi` but I may be wrong.

**Comment by kylethomas1029** [comment]
Any suggestions on how to fix it?

**Comment by DennisLfromGA** [comment]
You could try to *update* your chroot adding xmethod 'xiwi' at the same time:

`sudo sh ~/Downloads/crouton -t xiwi -u [-n precise]`

This will make 'xiwi' the default so just you won't need to use the '-X' option for 'xiwi' but you *will* need to use the '-X xorg' option if you want to try to use 'xorg' again.

**Comment by Askofep-1** [comment]
uncompleted

**Comment by Askofep-1** [comment]
/var/run/crw/crw is denied
