### ISSUE TITLE
Running ftp server in crouton

### ISSUE THREAD

**Issue by ferb96** [dnschneid/crouton#2200]
Hi, Loving your work so far!! Such a wonderful piece of hack. I'm pretty new to bash scripting, so please bear with me if I can't quite get something right.

I'm trying to run an ftp server on chromebook. Apparently it is not as simple as `sudo apt-get install vsftpd`. When I run `sudo service vsftpd status` it returns `vsftpd: unrecognized service`, and ftp doesn't run at startup either. I got the ssh server up and running thanks to the wiki, so i figured i should put something in `rc.local` for ftp to work too. But I don't know how to do it (last time I did it, I screwed up my crouton installation so hard i had to restore it from a tar ball).

I'm running pretty standard xfce on intel chromebook. Thanks for any help!

**Comment by DennisLfromGA** [comment]
If you haven't seen it yet, maybe this official Ubuntu documentation will help - [vsftpd](https://help.ubuntu.com/community/vsftpd).

**Comment by ferb96** [comment]
Alright, I have been able to figure out how to set up FTP server on crouton. Just post here if anyone has trouble setting up FTP server.

Just doing `sudo apt-get install vsftpd` won't be enough on crouton. Reading all the normal guides on the internet, I got stuck at the steps that tell me to restart ftp using `sudo service vsftpd restart`. Comparing to an ordinary ubuntu installation, you won't be able to control it that way on crouton. There is no such file `vsftpd` inside `/etc/init.d/` either. However there is a file `vsftpd` in `/sbin/`. The only way to get the server running is running `sudo vsftpd &` on terminal (the & is necessary because running `sudo vsftpd` alone will stop your terminal since it won't start in background like sshd does. It can be configured to start everytime you log into crouton below.

After installing through apt-get, open up `/etc/rc.local` and add the following lines:

```
/sbin/iptables -I INPUT -p tcp --dport 21 -j ACCEPT
mkdir -p -m0755 /var/run/ftp
# uncomment this next line if you want vsftpd to auto start
# everytime you log into crouton
# /usr/sbin/vsftpd &
```

And then open up `/etc/vsftpd.conf` and edit the line `secure_chroot_dir=/var/run/ftp`

And that's it, you are all set.

**Comment by dnschneid** [comment]
Thanks for reporting back with your findings!

**Comment by obonyojimmy** [comment]
@ferb96  on line 2 of `/etc/rc.local` why run vftpd  shell chroot  on ftp shell chroot why not run it on default  `/var/run/vftp` ?

**Comment by DennisLfromGA** [comment]
@ferb96 - Thanx for the feedback and procedure, this would make a *great* wiki contribution.

**Comment by jaffe59** [comment]
I don't see any /sbin/vsftpd after installing with apt-get.  I have an /etc/vsftpd.conf file, but can't find any start/stop scripts.  Running Trusty with Crouton latest: version 1-20160518095657~master:fd37bb79.
