### ISSUE TITLE
Let Linux handle lid close action

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#2202]
I've set my Linux Ubuntu chroot to a higher screen resolution [(link to topic in this "forum")](https://github.com/dnschneid/crouton/issues/1336). However, when I open the lid from my Chromebook it is in the standard lower resolution. I then have to set this higher resolution manually again. So I'd like my Ubuntu handle the lid close action.

In the Crouton Wiki is described how to stop ChromeOS from handling the [lid close action](https://github.com/dnschneid/crouton/wiki/Power-manager-overrides). But how do I tell my Lunux chroot to handle it instead? Because in the Control Center of Gnome 3 (gnome-control-center) under 'Power' the options to do something when on lid close _are grayed out_!

Before I disable CromeOS's lid close management I'd like to know how to enable it in Ubuuntu 14.04/Gnome 3.

**Comment by drinkcat** [comment]
You can get events from evtest, I think. Not sure what the appropriate daemon would be on ubuntu side.
