### ISSUE TITLE
Native or VM?

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#2203]
Does crouton run a native chroot? Is it as fast as running on metal from boot?

**Comment by drinkcat** [comment]
Native.

Yes (of course RAM, CPU and other resources are shared with Chomium OS, so there is some slight performance impact depending on your use case).

**Comment by trusktr** [comment]
Sweet. I don't have a Chromebook yet, so I'm just wondering: how's the video support? Does hardware acceleration work in the chroot?

**Comment by drinkcat** [comment]
If you use crouton-in-a-tab (xiwi target), no hardware acceleration for video/graphics.

On Intel-based platform, you can use full-screen switching (xorg target), and then you get GL acceleration. I'm not sure about video (hardware decode), I don't think anyone tested that.

**Comment by trusktr** [comment]
Sweet. I'd love to try it. Gotta save up.
