### ISSUE TITLE
Mouse cursor is not visible on xiwi when screen is rotated

### ISSUE THREAD

**Issue by tmagara** [dnschneid/crouton#2205]
Hi.

My setup of crouton xiwi gives me no mouse cursor visible if I rotate the screen (ex. 270 degrees) on ChromeOS settings menu.
However the mouse cursor is just working (move, click or drag) on xiwi window, it's completely invisible.
Outside the crouton window, I have no problem with mouse cursor.
If I launch crouton with '-X xorg' option, cursor appears just fine.

Is anyone having the same issue?
Thanks.

```
$ croutonversion
crouton: version 1-20151013174138~master:488c9e21
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,xorg,xfce,audio,extension
host: version 7390.59.0 (Official Build) stable-channel panther 
kernel: Linux localhost 3.8.11 #1 SMP Mon Oct 12 16:54:39 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

**Comment by YOWGEO** [comment]
Same issue here. 
* Rotated screen + `-X xiwi` = invisible mouse pointer/cursor
* Standard monitor orientation + `-X xiwi` = mouse pointer just fine
* Rotated screen + `-X xorg` = mouse pointer just fine
```
$ croutonversion
crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,cli-extra,audio,chrome,core,keyboard,xiwi
host: version 7390.61.0 (Official Build) stable-channel squawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Oct 15 02:16:25 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes 
```
