### ISSUE TITLE
UID 1000 not found in arch when trying to start  kde-desktop on trusty

### ISSUE THREAD

**Issue by aurey2244** [dnschneid/crouton#2206]
Everytime now that i install kubuntu desktop on trusty it always give me this error "UID 1000 not found in arch" and i just don't know why because the chroot has been fully completed and i have updated it like 5 times, could it be that I'm using an samsung chromebook with ARM instead of Intel because i did notice it said at the top that Xephyr no longer works with freon anymore. Anybody have any solutions or explaination of some kind?

**Comment by DennisLfromGA** [comment]
That's is strange; what do you get when, in a chroot terminal session, you enter: `id`

**Comment by aurey2244** [comment]
localhost Downloads # enter-chroot -n trusty -u root
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)root@localhost:~# id
uid=0(root) gid=0(root) groups=0(root)
(trusty)root@localhost:~# 

This is what i get

**Comment by DennisLfromGA** [comment]
Well it's definitely assigned your uid to 1000, it may be a problem with ARM but I haven't seen the error -
`"UID 1000 not found in arch"` reported by anyone else.
Guess the guru's will have to address this one - sorry...

**Comment by dnschneid** [comment]
Can you post the output of the command that has that line?
