### ISSUE TITLE
Pruning /mnt/stateful_partition/crouton/chroots/wheezy mounts...

### ISSUE THREAD

**Issue by mrkapqa** [dnschneid/crouton#2207]
Hello ,

i am trying to install debian wheezy on my Acer C720.

some days ago it worked well ... then i deleted the chroot for some reason.

today again i tried to install wheezy

chronos@localhost / $ sudo sh ~/Downloads/crouton -r wheezy -t kde

...after downloading files

it says

I: Base system installed successfully.
Pruning /mnt/stateful_partition/crouton/chroots/wheezy mounts...

but keeps on hanging after that. what did i do wrong this time?

**Comment by aurey2244** [comment]
try deleting the chroot again, and if that doesn't work u could try the other versions of debian, if u haven't already

**Comment by mrkapqa** [comment]
now it worked k, but i get no sound . thats a pity.

**Comment by mrkapqa** [comment]
with squeeze i also have problems

Installing target audio...
Fetching CRAS (branch 5c1b8df3853498e30e416b6289c12dab41a5988a)...
--2015-11-05 19:55:51--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/5c1b8df3853498e30e416b6289c12dab41a5988a.tar.gz
Resolving chromium.googlesource.com... 64.233.166.82, 2a00:1450:400c:c0b::52
Connecting to chromium.googlesource.com|64.233.166.82|:443... connected.
ERROR: certificate common name `*.googlecode.com' doesn't match requested host name `chromium.googlesource.com'.
To connect to chromium.googlesource.com insecurely, use `--no-check-certificate'.
Error fetching CRAS
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/squeeze...
