### ISSUE TITLE
Touch pad not working on switch back to chrome

### ISSUE THREAD

**Issue by mosqueteiro** [dnschneid/crouton#2210]
I've just started using a second monitor with my chromebook (Acer C720 with haswell i3 processor) and it has been working well in chrome and ubuntu crouton. However, upon switching back to chrome os, while crouton is still running, the touch pad is unresponsive. The keyboard and a usb mouse work fine. The touch pad works fine in crouton even when switching back and forth. The touch pad will start working again in chrome os after I've logged out of crouton and I drum my fingers across the touch pad.

**Comment by Talor-A** [comment]
I've noticed the same thing too- i usually just swipe across the whole touchpad several times, though a real fix would be nice to find. happens about half the time I switch back and forth.

**Comment by rumpaar1** [comment]
Happens here too, just using the inbuilt monitor. Only happens when using a USB mouse.
