### ISSUE TITLE
Chromebook factory return - re-instating Crouton

### ISSUE THREAD

**Issue by chrisofCCL** [dnschneid/crouton#2212]
My Asus C300 has to go and be repaired - display screen fault.  I have backed up my chroot and all my documents reside on an SD card, which obviously I will remove before sending the C300 back to Asus.  I intend to powerwash it and take it out of developer mode before returning. My plan to re-install when I get it back is as follows:

1. Reset developer mode
2. re-link my Google account with the machine
3. Create the path in which to place the backed up chroot (ie  /mnt/stateful_partition/crouton/chroots) and copy the tarball to there from the SD card.
4. Download the latest crouton installer or use the one I have already downloaded.
5. Restore the chroot by "sudo sh ~/Downloads/crouton -f mybackup.tar.gz"

Al sounds pretty straightforward but have I missed something?

Chris

**Comment by DennisLfromGA** [comment]
@chrisofCCL - Looks good but I don't believe you need to do step 3., when doing step 5., give it the full path to your SD card (`... -f /path/to/SD\ card/mybackup.tar.gz`).

**Comment by chrisofCCL** [comment]
Thanks Dennis.

Chris
