### ISSUE TITLE
Im trying to delete a chroot

### ISSUE THREAD

**Issue by CharlieHammons** [dnschneid/crouton#2213]
THIS IS WHAT I GET WHEN I TRY TO INSTALL/REMOVE A CHROOT
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xiwi,xfce
/usr/local/chroots/trusty already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.
chronos@localhost / $ sudo enter-chroot -n trusty
Entering /mnt/stateful_partition/crouton/chroots/trusty...
UID 1000 not found in trusty
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
chronos@localhost / $

**Comment by CharlieHammons** [comment]
Please help

**Comment by DennisLfromGA** [comment]
Your previously installed 'trusty' chroot may not have finished the installation.
You can enter it as root and see if it has an unfinished 'setup' script -

`sudo enter-chroot -u root -n trusty`

If so, tell it to finish the setup.
If you don't get prompted to complete the setup, then you may have to do one of the above recommendations -

`Either delete it, specify a different name (-n), or specify -u to update it.`

**Comment by tedm** [comment]
I just use delete-chroot -n <nameofchroot> I think delete-chroot calls edit-chroot.

**Comment by CharlieHammons** [comment]
Okay I tried what both of you said.. I got this 
chronos@localhost / $ sudo enter-chroot -u root -n trusty
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)root@localhost:~# delete-chroot -n
-su: delete-chroot: command not found
(trusty)root@localhost:~#

**Comment by CharlieHammons** [comment]
Okay, I looked up how to delete it and I got this someone please help
chronos@localhost / $ sudo delete-chroot trusty
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Failed to unmount /mnt/stateful_partition/crouton/chroots/trusty. Kill processes? [a/k/y/p/N] y
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
Delete /mnt/stateful_partition/crouton/chroots/trusty? [a/y/N] y
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/tmp’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/dev’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/run’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/sys’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/proc’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/var/host/media’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/var/host/udev’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/var/host/cras’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/var/host/dbus’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/var/host/timezone’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/var/host/shill’: Device or resource busy
rm: cannot remove ‘/mnt/stateful_partition/crouton/chroots/trusty/lib/modules/3.10.18’: Device or resource busy
chronos@localhost / $

**Comment by divx118** [comment]
Your chroot is still running. Simple way --> reboot your chromebook and try
again.
