### ISSUE TITLE
tun interface is broken, ChromeOS issue

### ISSUE THREAD

**Issue by jasoncook** [dnschneid/crouton#2215]
**Version 48.0.2546.0 dev (64-bit)
Platform 7583.0.0 (Official Build) dev-channel leon
Firmware Google_Leon.4389.61.46**

When creating a **tun** interface for VPN connections the tun device is immediately destroyed. This means that VPN connections will fail. Example output below.

From ChromeOS:

```
localhost ~ # openvpn --mktun --dev tun0
Thu Oct 29 22:15:45 2015 TUN/TAP device tun0 opened
Thu Oct 29 22:15:45 2015 Persist state set to: ON
localhost ~ # ifconfig tun0 up
tun0: ERROR while getting interface flags: No such device
```

From inside the chroot:

```
(sana)jason@localhost:~$ sudo ip tuntap add dev tun0 mode tun
(sana)jason@localhost:~$ sudo ifconfig tun0 up
tun0: ERROR while getting interface flags: No such device
```

This is problem does not effect **tap** interfaces.

**Comment by DennisLfromGA** [comment]
Maybe this wiki article can help if you haven't seen it - [Using Cisco AnyConnect VPN with openconnect](https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect)

**Comment by jasoncook** [comment]
Thanks for the link. I've followed the wiki in the past and it worked perfectly.
The problem now is that the tun interface is unstable and is destroyed within a
few seconds of its creation. Not just in a down state, but completely removed
from the system. This behavior is consistent both inside and outside the chroot
so I've reported it to the Chromium team as well. Not sure how to further
troubleshoot this. Is there a debugger or a log I could look at for more
details?

On Fri, Oct 30, 2015 at 8:38 AM, DennisL < notifications@github.com [notifications@github.com] > wrote:
Maybe this wiki article can help if you haven't seen it - Using Cisco AnyConnect VPN with openconnect
[https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect]

—
Reply to this email directly or view it on GitHub
[https://github.com/dnschneid/crouton/issues/2215#issuecomment-152559108] .[https://github.com/notifications/beacon/AEXA8KrOaf7cH_8cgqT2o9hwVdgQU89kks5pA4aIgaJpZM4GYxPK.gif]

**Comment by unlikelylass** [comment]
This is affecting me as well.

crouton: version 1-20151104200003~master:2a1fc9da
release: jessie
architecture: amd64
xmethod: xorg
targets: xorg,cli-extra,e17,lxde,extension,xiwi,chrome,keyboard
host: version 7520.34.0 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Nov 3 22:59:57 PST 2015 x86_64 GNU/Linux
freon: yes

**Comment by emidln** [comment]
I encountered this as well. I'm not sure exactly how to tell Chrome OS to create a persistent tun0 interface, but I did notice that if I setup a fake openvpn connection through the network settings and try to connect to that, it will create a tun0 until reboot that my openvpn command in the shell can take advantage of.

**Comment by henkjan** [comment]
@jasoncook do you have the chromium bug report id? I would like to subscripe to the bug as i'm facing the same issue right now.

**Comment by ivr588** [comment]
using: acer C201P armv7

Hi, thought it might be worth mentioning that I see the same effect with any network interface. First they must be loaded/started in ChromeOS via the network applet, then the chroot can use it. Not tested with VPN, see the same effect with wlan0. **To clarify, even with wlan0 up but not associated, I cannot from within the chroot associate with another base station.** It connects then disconnects. If I change stations, I have to switch to ChromeOS to associate.

**Comment by pippo0312** [comment]
HI,
I think I found a reliable solution to make topenvpn command working.
The tun0 interface is destroyed by the shill services which automatically kills the "useless" connections.

The solution is to enter the following commands before openvpn:

sudo stop shill
sudo start shill BLACKLISTED_DEVICES=tun0

the BLACKLISTED_DEVICES tells shill to ignore the "tun0" device.

I put in a script  /usr/local/bin/openvpn2 all this, adding also a trick to change the DNS on the flight (to cure another problem with openvpn on chromebooks):

chronos@localhost /usr/local/bin $ cat openvpn2
```
#!/bin/sh -e
trap '' 2

cat > dns.conf <<EOF
nameserver 8.8.8.8
nameserver 8.8.4.4
search lan.
options single-request timeout:1 attempts:5
EOF

sudo stop shill
sudo start shill BLACKLISTED_DEVICES=tun0
sudo sleep 5
sudo openvpn --mktun --dev tun0
sudo sleep 3
sudo mount --bind ./dns.conf /var/run/shill/resolv.conf
sudo openvpn --config $1 --dev tun0
sudo openvpn --rmtun --dev tun0
sudo umount /var/run/shill/resolv.conf
trap 2
```

---------------------------------------------------------------------------

to open openvpn connection with a configuration file vpn.conf  I give the command:

`openvpn2  vpn.conf`

hit ctrl-c to close the VPN 
It works and it is very reliable.
Let me know if it solves also your problems!

**Comment by DennisLfromGA** [comment]
@pippo0312 - Great sleuthing and nice remedy. Maybe you could update the [wiki](https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect) with your new info. and solution...

**Comment by pippo0312** [comment]
[wiki](https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect) updated

**Comment by DennisLfromGA** [comment]
@pippo0312 - Great! Thanx.

**Comment by imain** [comment]
This works!  However it now breaks android apps.  I found you need to use:

sudo start shill BLACKLISTED_DEVICES="br0,tun0"

to make it work with them.

**Comment by DennisLfromGA** [comment]
@imain, Thanx. 👍  
That may also be worthy of a [wiki](https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect#solution-to-make-the-tun0-interface-stable-and-the-openvpn-command-reliable) update. 
-DennisL

**Comment by jayp0521** [comment]
> This works! However it now breaks android apps. I found you need to use:
> 
> sudo start shill BLACKLISTED_DEVICES="br0,tun0"
> 
> to make it work with them.

Is there an update to this? I am on Kali Linux and I keep getting `sudo: start: command not found` when running this
