### ISSUE TITLE
 Not unmounting /mnt/stateful_partition/crouton/chroots/trusty Error

### ISSUE THREAD

**Issue by CharlieHammons** [dnschneid/crouton#2216]
I've been trying to unmount (delete) this chroot, but I gives me an error when I try doing so...
chronos@localhost / $ sudo enter-chroot -n trusty
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
UID 1000 not found in trusty
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
chronos@localhost / $ 

Please help??!

**Comment by DennisLfromGA** [comment]
The answer I provided in your other similar issue may help: https://github.com/dnschneid/crouton/issues/2213#issuecomment-152557822

**Comment by brmbrmcar** [comment]
You have to force unmount. A big pain, I know.
