### ISSUE TITLE
not a crouton issue: chrome v45 is spewing memory. can i launch shell without chrome?

### ISSUE THREAD

**Issue by falafflepotatoe** [dnschneid/crouton#2218]
can i launch crouton without opening a crosh (chrome) shell even to save the memory for linux?

- the versions of chrome since they announced blink have been leaking memory, and its getting worse each version
- v45 is so spewy after 1hr it takes 20-30 seconds to launch a app or new tab
- constant tabs crashing due to out of memory

anyone know why?

while the obvious fix is for chrome to patch its 100 memory leaks (looking at the bug reports), im just going to use crouton

anyway to `enter-chroot` automatically or without using crosh?

i would humbly suggest the authors of crouton make launching chroot without chrome their next priority. (i assumed (at v40) they would fix the memory leak. its been 6 months and its only getting worse)

**Comment by DennisLfromGA** [comment]
> can i launch crouton without opening a crosh (chrome) shell even to save the memory for linux?
> anyway to enter-chroot automatically or without using crosh?

Nope.

> not a crouton issue:

Agreed.

**Comment by falafflepotatoe** [comment]
Actually theres a crouton process using 94% cpu

htop says `-su -c (exec 1>&0 2>&0 while read /tmp/crouton/frecon.lock do ... loop)` is using 94% cpu

wat.

ideas?

**Comment by dnschneid** [comment]
#2190 may (eventually) allow launching crouton from frecon without logging into Chromium OS...

**Comment by falafflepotatoe** [comment]
fixed when updated crouton!

**Comment by DennisLfromGA** [comment]
>> can i launch crouton without opening a crosh (chrome) shell even to save the memory for linux?
anyway to enter-chroot automatically or without using crosh?

> Nope.

>> not a crouton issue:

> Agreed.

So, it seems I was wrong on *both* counts!
I sometimes wonder why I even try... :/

**Comment by dnschneid** [comment]
Because 95% of the time you're right, and the remaining 5% you learn for next time :)
