### ISSUE TITLE
Can no longer enter Ubuntu after updating?

### ISSUE THREAD

**Issue by Jimzyboi** [dnschneid/crouton#2219]
Not sure what's happened, just updated my chroot and now I can't get back into ubuntu, this is what came up. 

chronos@localhost / $ sudo sh /media/removable/"SD Card"/bin/startxfce4
Entering /media/removable/SD Card/chroots/trusty...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:50:48 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=334036c4-a9a8-c040-848b-4bf8d0e6e521/PARTNROFF=1 hashtree=PARTUUID=334036c4-a9a8-c040-848b-4bf8d0e6e521/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=db22780bb4f72cf5cff440a5821216bf6d9b312a salt=2265addac1abf4298de4b02d3db9b0ef32903ca4bf4d38bf9062f39bd06d7d4f" noinitrd vt.global_cursor_default=0 kern_guid=334036c4-a9a8-c040-848b-4bf8d0e6e521 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Oct 31 15:45:18 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x48) [0x7fd757be2848]
(EE) 1: /usr/bin/Xorg (0x7fd757a39000+0x1ad539) [0x7fd757be6539]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7fd756932000+0x10340) [0x7fd756942340]
(EE) 3: /usr/bin/Xorg (0x7fd757a39000+0xb57a6) [0x7fd757aee7a6]
(EE) 4: /usr/bin/Xorg (xf86BusProbe+0x9) [0x7fd757ac2099]
(EE) 5: /usr/bin/Xorg (InitOutput+0x74d) [0x7fd757ad06fd]
(EE) 6: /usr/bin/Xorg (0x7fd757a39000+0x59bab) [0x7fd757a92bab]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7fd755372ec5]
(EE) 8: /usr/bin/Xorg (0x7fd757a39000+0x451ee) [0x7fd757a7e1ee]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /media/removable/SD Card/chroots/trusty...

Any help will be much appreciated, Thanks.

**Comment by dnschneid** [comment]
You're probably making the same mistake as in #2222
