### ISSUE TITLE
Unable to download kali.

### ISSUE THREAD

**Issue by DrunkenAngel** [dnschneid/crouton#2220]
Hi Guys getting an issue downloading kali. Crouton seems to be unable to pull down the kali release. 

<a href=http://pastebin.com/h68B6fNm>pastebin of terminal</a>

any ideas ?

**Comment by DennisLfromGA** [comment]
I'm not sure what's changed or when but `http://http.kali.org/dists/kali/Release` doesn't seem to exist anymore. There is no `kali` sub-folder under `http://http.kali.org/dists/`.

**Comment by DrunkenAngel** [comment]
Yea I noticed that guess its just wait for the next build?
