### ISSUE TITLE
Gnome Debian Jessie not working

### ISSUE THREAD

**Issue by brmbrmcar** [dnschneid/crouton#2224]
Just a screen saying something has failed and log off button that you cannot use.

**Comment by divx118** [comment]
Yes see https://github.com/dnschneid/crouton/issues/1266

**Comment by brmbrmcar** [comment]
Not my issue. It was very different. But any info is long gone and I have not got the disk space to retry it.

**Comment by divx118** [comment]
@brmbrmcar No it is the same issue.

**Comment by brmbrmcar** [comment]
Can they even get a boot? I could. They did not mention the white screen. Otherwise Iwill close this.

**Comment by divx118** [comment]
@brmbrmcar first line in the issue  
 > you get the white gnome error screen on startup

**Comment by brmbrmcar** [comment]
Oh,sorry.

**Comment by divx118** [comment]
no problem Thanks
