### ISSUE TITLE
Cannot get Sana Linux to start on Acer C720

### ISSUE THREAD

**Issue by joshsharrer** [dnschneid/crouton#2225]
sudo startkde
Entering /mnt/stateful_partition/crouton/chroots/sana...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.17.2
Release Date: 2015-06-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Oct 15 02:29:56 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=81281d3f-7129-6243-8a34-c2a369aed6e4/PARTNROFF=1 hashtree=PARTUUID=81281d3f-7129-6243-8a34-c2a369aed6e4/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=04164b9d3b0b25d7b1ac9d9bbf924e48c49af65f salt=baef8d6e069d150736b4ab91f4409dc04ea62c1c16a7ddceb60bead9a34289b3" noinitrd vt.global_cursor_default=0 kern_guid=81281d3f-7129-6243-8a34-c2a369aed6e4 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 01 July 2015  05:17:14PM
xorg-server 2:1.17.2-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Nov  3 18:22:38 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20151013174138~master:488c9e21
release: sana
architecture: amd64
xmethod: xiwi
targets: kde
host: version 7390.61.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Oct 15 02:29:56 PDT 2015 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/sana...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/sana...

**Comment by dnschneid** [comment]
Do you have [the crouton extension](http://goo.gl/OVQOEt) installed?

**Comment by bas-r** [comment]
I have the same issue, on an Acer C730. I have the crouton extension installed.

The following happens (have reproduced several times): 
When installing sana (with either kde or xfce4) my keyboard and / or touchpad become unresponsive. The installation process seems to run fine, but obviously I cannot give in a user and pwd when prompted to do so. The only button that works is the powerbutton to shutdown the machine.

After a restart I can start sana, and it asks me to finish installation. I proceed with this, and now both my keyboard and touchpad will keep on working. I can give in a user and pwd. It seems to finish ok.
Now when I start sana again, it gives the same output as user joshsharrer posted.

What can I test, or what logs should I produce to try and find a solution?

**Comment by joshsharrer** [comment]
I had the same issue during installation but overcame it by using an external usb keyboard to complete the setup. After the install finished and I rebooted, the onboard equipment began working again. 

Thanks,
Josh Sharrer

**Comment by joshsharrer** [comment]
I also had to install the crouton extension as I was suggested to do. After doing all these steps my acer is up and running sana great!

Thanks,
Josh Sharrer

**Comment by DennisLfromGA** [comment]
In addition to the 'Crouton Integration' extension, the 'extension' target is also required...
