### ISSUE TITLE
0 bytes of storage after running BleachBit,  developer shell won't start, file manager won't show any files. [Fixed now]

### ISSUE THREAD

**Issue by ajshell1** [dnschneid/crouton#2226]
I think I REALLY screwd up today. I ran BleachBit (a program that cleans out space-hogging files), but I didn't realize that part of this cleaning process involved filling all disk space. A freeze followed by a forced shutdown later, everything runs slower. I can't edit my docs offline, and I can't even open the developer shell to delete the chroot. I see the red rectangle in the top left corner, but NOTHING else appears. So I open the Chrome OS file explorer, and while it opens up, it doesn't show any text. So I'm stuck. What do I do now?
By the way, I have a backup SD, so I could use that if I needed to, but that would mess up the chroot I have on an external hard drive.

**Comment by DennisLfromGA** [comment]
You may be able to gain access to your chroot(s) without logging in by -
- Pressing <kbd>Ctrl+Alt+F2/Right-Arrow</kbd> at the login screen
- Enter: chronos (no password is set by default)

Logging in this way takes much fewer resources and may be just enough to get a terminal session.

- Then: `cd /usr/local/chroots/` (the default location for chroots)
- Then, if you want to delete *all* your chroot(s), enter `sudo delete-chroot *`
- If you want to delete a particular chroot, enter: `sudo delete-chroot [chrootname]`

substituting [chrootname] with the name of your chroot, like 'trusty', for example.

**Comment by ajshell1** [comment]
That worked! Thanks!

**Comment by DennisLfromGA** [comment]
Cool, cool, cool!
You can probably *close* this issue now if you like...

**Comment by ajshell1** [comment]
Okay then. Will do.
