### ISSUE TITLE
Touchpad needs a lot of pressure applied

### ISSUE THREAD

**Issue by roryaherne** [dnschneid/crouton#2228]
Hello, I updated my chroot today. When I went into xfce4 I thought at first that the mousepad was broken but then realised that i need to apply a lot of pressure to the mousepad in order to get it to react. Also, tap to click doesn't work.

I have the Samsung Chromebook XE303C12

Here is the output from croutonversion

```
chronos@localhost / $ sudo enter-chroot croutonversion
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: armhf
xmethod: xorg
targets: keyboard,xfce
host: version 7390.61.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Oct 15 02:21:14 PDT 2015 armv7l armv7l armv7l    GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

Is there anything else you need from me?

Edit: After a restart I went back into crouton and for the first few seconds the mousepad worked, but then quickly required more and more pressure to register. Thought that might help.

**Comment by blaskovic** [comment]
Exactly the same issue with my Acer Chromebook 14. Weird is, that it works fine in xfce4 but not in DWM (apt-get install dwm).

**Comment by DennisLfromGA** [comment]
I haven't noticed any issues reported with the Samsung ARM Chromebook (daisy) but there have been some adjustments made on a few others. Take a look at this [Pull Request#725](https://github.com/dnschneid/crouton/commit/4e2df2cf73c390a57914f6e2bebc24a02cac52a4) merged on Mar 29, 2014.
You might be able to use that method to adjust the trackpad sensitivity, it uses the `synclient` command with a couple of parameters, similar to:

`synclient FingerLow=1 FingerHigh=5`

You may have to experiment with the values but hopefully it'll make an improvement.

Hope this helps,
-**DennisL**
