### ISSUE TITLE
TrakEM2 question on transferring  manual aligmentss

### ISSUE THREAD

**Issue by PalomaSJ** [dnschneid/crouton#2229]
I hope this is the right place to ask this question. In TrakEM2, can I transfer the alignment data (i.e. rotation angle/ translation/ scaling) from one stack of images to another stack of images?

My problem is that I have to align the slices of a mouse brain but there are two channels, one red and one blue.  Is there any way that I can only align one channel and translate that information to have the other channel exactly like the first one?

The only option I could come up with is to align my first channel, then interleave the second channel in the aligned stack ( add the images of the unaligned stack in between the images of the aligned stack) and try to apply the changes visually. 

Please and thanks in advance for the help.

**Comment by dnschneid** [comment]
I run into this problem all the time too (monkies in my case), but unfortunately this isn't the right place to ask that question.

#262
