### ISSUE TITLE
How to get XML response in readable format in flight API

### ISSUE THREAD

**Issue by amitdoeacc** [dnschneid/crouton#2230]
i am using travelport flight api. when i send request by curl getting response in non readable format. how i will get response in readable. this is flight api response

RESPONSE->

"H4sIAAAAAAAAAJ1UTUwTQRR+LZQfqRLEEINRNBrh4i4UaVnxooAEskWkaEKRw7A7XQa3O8vstCzGmOjFePDixWBigjESTTxwNDHxqgcPxHgwMR4MZ++SmODM0gIr0UZ72O68+eZ7733vm331HWIeg+Y5VERKgRNbucAYWtSJx/07H48uvUNPqiAyDNUeuYl9FwAiC9XyKQ6dMWhesRLeAuHGrGKZnoJM5HLMPEXs5KmjDPqcIYNP0BvY0e9+aSObTStRqJuCBsTYBMljmYdD15QuDqhlKlVQ5amJbXWLRpXIjIsNkiMG4oQ6fYLBxO4Og1aB4ZKNfTJj471MumTyOHGCJYeDupRCtZFjqRnOiGMJSMxitOByaN61OexwbGEmduvzlOGgx3m4DTEdaigjFimv4i6jRWJi1i8qKsVifBvuuwVWUiAkZlB/Wci9dT8/fm3t7aPUgyhAMBYQLFoFlj+r8OnN9Lkj99any2xyvMn/41r6vDz1YiT3MwoRHRo9jJgxG/hgAC16HJS/DyoTxvf5DJR/U2Z8khlqw4flKFRnoYV4YwznMMOmBI5SPkSKwouw3w3CpTiHk+GyStXIC6EOIB50KSYd90qZ5FpOr1FMn4v3ceEIwdJR2ccBsk+ILBQ+Eeqs1FBwCcs5YesXiUJNFuKmiJZbyEIjcYrIJkEDWergLByguZyH+Q4kzkNN181RE0lqDod1yixVrlWJCTXJS4SjaKvJ2LYlWsQhRR5SJGa7ytfnfXNu6uuGdA+DtjBoBnlYuSgeZfTm5sa3y9PKsyhER6CWpIltE09cQ9I/y6hDbWotcmj9rb6dPakdRK5cXb0uJWwPJzMCmDKcubxz4FSGF2Zevm/KzafG2qukwb09RZZrk20H+BU18vhWonU9wC/UQ+0gN9Sh9ITvu/L46YqeDOb88Ef66epax/0oVAldhbVtIr41u8yzzxaJQ5GwMYOgSOnKl0PiC1SVHtTF37HuzrOdPZ2JXq27R9NSWq+WSHYmtGR3IpXUUl0Cl5kccF3/F4HiyMrfBQAAQANTAS AIRWAYS LIMITEDVIRGIN AUSTRALIA INTLQANTAS AIRWAYS LIMITEDVIRGIN AUSTRALIA INTLVIRGIN AUSTRALIA INTLQANTAS AIRWAYS LIMITEDQANTAS AIRWAYS LIMITEDQANTAS AIRWAYS LIMITEDVIRGIN AUSTRALIA INTLVIRGIN AUSTRALIA INTLVIRGIN AUSTRALIA INTL"

**Comment by DennisLfromGA** [comment]
What is the full curl command you are entering ?

**Comment by drinkcat** [comment]
#262
