### ISSUE TITLE
question on virtualbox vs multiple crouton sessions

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#2231]
I am going to try to use my chromebook for a seminar that involves using a couple of virtualbox images.

I'm wondering what the diff. would be between virtual box in a crouton chroot, vs two chroots, one natively running each session?

The two sessions need networking between them (same subnet).

I realize there is a chance that if the power resets and an os update is pushed, I may have to go to best buy and get a regular notebook, but assuming the chromebook can maintain state for 3 days, which way is better, virtualbox with two sessions, or just two choots?

**Comment by DennisLfromGA** [comment]
@tedm,

I haven't run multiple vm's so I can't speak to that specifically but I do believe that one or more vm's will take considerably more resources than multiple chroots. I have and do run multiple chroots with no problem whatsoever, and it's much simpler to setup. Just today, in fact, I was running tursty/unity and wily/gnome-desktop via xorg, easy peasy...

**Comment by tedm** [comment]
Thanks @DennisLfromGA Yes, VMs take a lot of resources to not feel sluggish vs chroots, but the chroots need to communicate with each other, to emulate being cluster nodes, so that's where the benefint of vm virtual networking helps. If the chroots could have their own network manager (new feature?) that would solve them just inheriting the core os's ip config info.

For now, I've ordered a refurb < $200 i5 Lenovo, but if I can get a couple of choots to have different IP addresses I might be able to get the cluster emulation down.

**Comment by DennisLfromGA** [comment]
I guess you've answered your own question then ;)

**Comment by dnschneid** [comment]
Chroots share the same network interface, so running multiple network managers would just confuse things. Without going to VMs, you'd have to use containers with separate network namespaces and some sort of NAT to achieve what you want.

**Comment by tedm** [comment]
So what is the easiest way to give a chroot it's own /etc/network/interfaces file, assuming say 2 usb to ethernet network adapters installed, and not using network manager or wifi ?
