### ISSUE TITLE
How to make a MATE target

### ISSUE THREAD

**Issue by seijinshu** [dnschneid/crouton#2233]
Hello everyone.

I am wanting to know how to go about setting up a MATE target and make a pull request.
I use a dual boot setup, and I just do not have any room on my SSD for either OS. If I could do a MATE setup in crouton, I might go back to crouton and run it off my SD card.

**Comment by DennisLfromGA** [comment]
You could take a look at some of the built-in desktop targets, [gnome-desktop](https://github.com/dnschneid/crouton/blob/master/targets/gnome-desktop) for instance, might be a good start.

You can 'build' it on your Chromebook by extracting crouton using the '-x' option. Once you have your target(s) scripted, use the '-T' option to install it.

**Comment by seijinshu** [comment]
Ok, and how would I go about doing a pull request?

**Comment by DennisLfromGA** [comment]
Like so: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/).
