### ISSUE TITLE
Failed to load session "cinnamon"

### ISSUE THREAD

**Issue by wdiip** [dnschneid/crouton#2235]
https://tr1t.wordpress.com/2015/04/21/installing-mint-cinnamon-in-crouton/
http://jeanlouisnguyen.blogspot.ca/2014/01/guide-how-to-install-elementary-os-on.html
I've been following these two guides to install cinnamon on my Toshiba Chromebook 2. Part of the process is installing xfce and I can run xfce just fine. But when I try sudo startcinnamon the screen goes black an a white window pops up saying 'failed to load session "cinnamon" ' with a button that says logout.

Any idea what might be the problem? People have gotten cinnamon working with this tutorial apparently.

sudo startcinnamon outputs

Entering /mnt/stateful_partition/crouton/chroots/cinnamon...
/usr/bin/startcinnamon: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:50:48 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=8006c220-338c-5740-b705-71af8bd68db2/PARTNROFF=1 hashtree=PARTUUID=8006c220-338c-5740-b705-71af8bd68db2/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=db22780bb4f72cf5cff440a5821216bf6d9b312a salt=2265addac1abf4298de4b02d3db9b0ef32903ca4bf4d38bf9062f39bd06d7d4f" noinitrd vt.global_cursor_default=0 kern_guid=8006c220-338c-5740-b705-71af8bd68db2 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Nov 11 20:09:58 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
setversion 1.4 failed: Permission denied
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce,keyboard,extension
host: version 7390.61.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:50:48 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
cinnamon-session[875]: WARNING: Unable to find required component 'nm-applet'
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/cinnamon as another instance is using it.

Output from croutonversion:
Entering /mnt/stateful_partition/crouton/chroots/cinnamon...
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce,keyboard,extension
host: version 7390.61.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:50:48 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/cinnamon as another instance is using it.

**Comment by mads256c** [comment]
Restart and try again ;)

**Comment by wdiip** [comment]
I tried that and I still get the same error message. Thanks for trying though.

**Comment by dnschneid** [comment]
Looks like cinnamon requires nm-applet (NetworkManager) to be installed. you could try running `sudo apt-get install nm-applet` and see if you can launch cinnamon, but that may or may not make networking behave stangely.

**Comment by wdiip** [comment]
Awesome, that did the trick! Thanks.

`install nm-applet` didn't return any results, but `install network-manager-gnome` got it.
