### ISSUE TITLE
unable to update 

### ISSUE THREAD

**Issue by garethjscoleman** [dnschneid/crouton#2236]
I;m trying to update crouton - previously I was getting and Xserver error, but then I hadn;t used it for a while

now when I try 

```
sudo sh ~/Downloads/crouton -n precise -u 
```

I get a few lines of the installer trying to work and then an error:

```
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Creating devbroker-access group with GID 403...
-su: 1: groupadd: not found
Unmounting /mnt/stateful_partition/crouton/chroots/precise.
```

here is the output of 

`sudo enter-chroot -n precise croutonversion`

```
Entering /mnt/stateful_partition/crouton/chroots/precise...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] Y
Preparing chroot environment...
Creating devbroker-access group with GID 403...
-su: 1: groupadd: not found
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
Creating devbroker-access group with GID 403...
-su: 1: groupadd: not found
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

Anu suggestions on what to try next - most of the things I've tried so far result in the above reference to being unable to locate groupadd

thanks

Gareth

**Comment by walker12001** [comment]
can you screenshot.

**Comment by DennisLfromGA** [comment]
It looks like your chroot is missing some critical files/apps and the crouton setup script was removed.
You could try going into your chroot as 'root' and then doing an update/fix.

Try the following: 
- `sudo enter-chroot -u root`
- `sudo apt-get install -f`
- `sudo apt-get update`
- `sudo apt-get upgrade`

If those commands succeed, you can exit your chroot and re-enter with your desktop app:
- `sudo startxfce4`

Hope that works,
-DennisL

**Comment by garethjscoleman** [comment]
Ok, when I try to enter chroot as root I get this:
```
chronos@localhost / $ sudo enter-chroot -u root
Entering /mnt/stateful_partition/crouton/chroots/precise...
Creating devbroker-access group with GID 403...
-su: 1: groupadd: not found
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

I'll try to get a screenshot, uploaded but not really sure what more you'll get from that.

I suspect this chroot is toast, but i'll give recovery a go if anyone has any ideas.

**Comment by DennisLfromGA** [comment]
From the error message above, I don't believe the chroot got far enough along in the installation process to be usable, for root or anyone - and in your vernacular: It's 'toast' ;)
I believe your only recourse at this point is to delete the chroot and start over.

**Comment by chandshr** [comment]
I have a trusty installed in SDcard. When I run the command sudo startunity its giving me the following error message
/media/remoable/SD Card/os/trusty doesn't appear to be a valid chroot.
Unmounting /media/removable/SD Card/os/trusty...

And I tried to update it and it also gives the same error

chronos@localhost ~ $ sudo enter-chroot -n trusty croutonversion
Enter encryption passphrase for trusty: 
Entering /media/removable/SD Card/os/trusty...
/media/removable/SD Card/os/trusty doesn't appear to be a valid chroot.
Unmounting /media/removable/SD Card/os/trusty...

I have a backup of trusty and when tried to restore that file 
chronos@localhost ~ $ sudo edit-chroot -r -f /media/removable/SD\ Card/backup/trusty-20150802-1608.tar 
Detecting chroot name...
/media/removable/SD Card/os/trusty already exists! Specify a second -r to overwrite it (dangerous).

Detecting chroot name...
WARNING: /media/removable/SD Card/os/trusty already exists. Deleting it before restoring.
Press Control-C to abort; restoration will continue in 5 seconds.
Unmounting /media/removable/SD Card/os/trusty...
/ Deleting /media/removable/SD Card/os/trusty...

And the above script is like running forever

**Comment by DennisLfromGA** [comment]
@chandshr,

Your problem is different from the OP so you might consider opening a new issue.
However...
> I have a trusty installed in SDcard. When I run the command sudo startunity its giving me the following error message
/media/remoable/SD Card/os/trusty doesn't appear to be a valid chroot.

That error message is due to a missing or unreadable `/etc/passwd` file so your chroot either didn't finish installing or something happened to your chroot to corrupt it.

> chronos@localhost ~ $ sudo edit-chroot -r -f /media/removable/SD\ Card/backup/trusty-20150802-1608.tar 
Detecting chroot name...
/media/removable/SD Card/os/trusty already exists! Specify a second -r to overwrite it (dangerous).

Did you specify a second `-r` in your command ?

> Detecting chroot name...
WARNING: /media/removable/SD Card/os/trusty already exists. Deleting it before restoring.
Press Control-C to abort; restoration will continue in 5 seconds.
Unmounting /media/removable/SD Card/os/trusty...
/ Deleting /media/removable/SD Card/os/trusty...

Here it looks like you did specify a second `-r` and it's trying to delete it before it restores your backup. Depending on the media speed, your Chromebook, your chroot size, etc. this part can take a while.

If you didn't get a message something like "Restoring /media/removable/SD\ Card/backup/trusty-20150802-1608.tar  to trusty...", then it is still trying to delete the original.

I would reboot your Chromebook and enter that last restoral command again, it should work.
