### ISSUE TITLE
Keyboard target on xiwi

### ISSUE THREAD

**Issue by commiades** [dnschneid/crouton#2239]
I have an Asus C300m and am using a Xfce trusty chroot with the following targets: extension, keyboard and audio. In order to get a Logitech T630 bluetooth mouse to work, I added the target xiwi.

On xiwi I can use the mouse, but the keyboard is a mess. None of the function keys work as function keys, but as they would on a vanilla chromebook. Some of the attempts at Search + something else open the Whisker menu.

The same configuration works normally on xorg instead of xiwi, and both display the same settings for "setxkbmap -print":

> xkb_keymap {
>    xkb_keycodes  { include "evdev+aliases(qwerty)"    };
>    xkb_types     { include "complete" };
>    xkb_compat    { include "complete+chromebook"  };
>    xkb_symbols   { include "pc+us+inet(evdev)+chromebook(overlay)"    };
>    xkb_geometry  { include "pc(pc104)"    };
> };

I tried a powerwash and creating a new chroot, but got the same result. This is what is produced when I run startxfce4 -X xiwi:

> /usr/bin/startxfce4: Starting X server
> 
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> 
> X.Org X Server 1.15.1
> Release Date: 2014-04-13
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:54:39 PDT 2015 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=5d820b40-24fc-3649-945d-a21344ec446c/PARTNROFF=1 hashtree=PARTUUID=5d820b40-24fc-3649-945d-a21344ec446c/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=c1dc6d700aee10315215a9f8ad88306b4a17b8bf salt=3a69c783a32d9615f08427b8e63618175716d8136c4c1c14a99dbf2f8ffc5e76" noinitrd vt.global_cursor_default=0 kern_guid=5d820b40-24fc-3649-945d-a21344ec446c add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
> Build Date: 12 February 2015  02:49:29PM
> xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.30.2
>    Before reporting problems, check http://wiki.x.org
>    to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>        (++) from command line, (!!) notice, (II) informational,
>       (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Nov 15 12:41:11 2015
> (++) Using config file: "/etc/X11/xorg-dummy.conf"
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Initializing built-in extension Generic Event Extension
> Initializing built-in extension SHAPE
> Initializing built-in extension MIT-SHM
> Initializing built-in extension XInputExtension
> Initializing built-in extension XTEST
> Initializing built-in extension BIG-REQUESTS
> Initializing built-in extension SYNC
> Initializing built-in extension XKEYBOARD
> Initializing built-in extension XC-MISC
> Initializing built-in extension SECURITY
> Initializing built-in extension XINERAMA
> Initializing built-in extension XFIXES
> Initializing built-in extension RENDER
> Initializing built-in extension RANDR
> Initializing built-in extension COMPOSITE
> Initializing built-in extension DAMAGE
> Initializing built-in extension MIT-SCREEN-SAVER
> Initializing built-in extension DOUBLE-BUFFER
> Initializing built-in extension RECORD
> Initializing built-in extension DPMS
> Initializing built-in extension Present
> Initializing built-in extension DRI3
> Initializing built-in extension X-Resource
> Initializing built-in extension XVideo
> Initializing built-in extension XVideo-MotionCompensation
> Initializing built-in extension SELinux
> Initializing built-in extension XFree86-VidModeExtension
> Initializing built-in extension XFree86-DGA
> Initializing built-in extension XFree86-DRI
> Initializing built-in extension DRI2
> Loading extension GLX
> /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
> crouton: version 1-20151104200003~master:2a1fc9da
> release: trusty
> architecture: amd64
> xmethod: xiwi
> targets: xiwi,extension,audio,keyboard,xfce
> host: version 7390.61.0 (Official Build) stable-channel quawks 
> kernel: Linux localhost 3.10.18 #1 SMP Thu Oct 15 04:54:39 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Cannot open /sys/class/tty/tty0/active: No such file or directory
> Connected to extension, launched crouton in a window.
> Error: target STRING not available
> _IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
> 
> (xfce4-session:15995): xfce4-session-WARNING **: Unable to launch "/usr/lib/x86_64-linux-gnu/indicator-sound/indicator-sound-service" (specified by autostart/indicator-sound.desktop): Failed to execute child process "/usr/lib/x86_64-linux-gnu/indicator-sound/indicator-sound-service" (No such file or directory)
> /usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
> 
> (xfsettingsd:16154): xfsettingsd-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
> 
> (polkit-gnome-authentication-agent-1:16150): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
> 
> (polkit-gnome-authentication-agent-1:16150): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
> QGtkStyle was unable to detect the current GTK+ theme.
> 
> *\* (wrapper-1.0:16219): WARNING **: Binding 'XF86AudioLowerVolume' failed!
> 
> *\* (wrapper-1.0:16219): WARNING **: Binding 'XF86AudioRaiseVolume' failed!
> 
> *\* (wrapper-1.0:16219): WARNING **: Binding 'XF86AudioMute' failed!
> Error: target STRING not available
> 
> (gnome-terminal:16416): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.

**Comment by tmagara** [comment]
Try checking "Treat Top-Row Keys as Function Keys" on Setting > Device > Keyboard.
It's on ChromeOS setting panel, not on crouton.
So this causes effect on whole ChromeOS windows, which may not what you want.

**Comment by commiades** [comment]
Thanks, that's a great fix. The random behaviour was fixed when I deleted a keyboard shortcut for the Windows key that I'd created with an external keyboard.
