### ISSUE TITLE
Very high keyboard lag in chroot if Auto-correction is enabled

### ISSUE THREAD

**Issue by Powerlink01** [dnschneid/crouton#2241]
Hi everyone,

I discovered that if you enable auto-completion on your physical keyboard in Chrome OS, it will make it almost impossible to input text to a guest os. Il will only work if you press a key for 2-4secs.

Auto-completion can be enabled here: Settings > Languages > Language and input settings > Input Method > _your_keyboard_here_ > Configure > Auto-correction > change box to "Modest"

I discovered this behaviour using a trusty chroot with xfce stored on an USB drive (complete crouton command: sudo sh -e crouton -r trusty -p /media/removable/crouton/ -t xiwi,audio,extension,cli-extra,xfce,keyboard).
The same behaviour ocured on a similar chroot running Kali Sana.

I'm using a German(Switzerland) > French(Switzerland) keyboard.

I don't know if this can be fixed, but it should at least be mentioned somewhere. I couldn't find a single line about this issue.

Thank you all for this great tool, it's amazing!!!

Powerlink01

PS: sorry if this issue is known, didn't find anything about it ...

**Comment by dnschneid** [comment]
Probably needs to be resolved with #1457
