### ISSUE TITLE
Two Questions: 'Baytrail SOC' SD cards unmounting. USB workaround? Where's the Bug to Track?

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#2242]
Had another go at being able to externalise files, programs or the whole OS to the SD card (Toshiba Chromebook 2). This device has its SD card wired to the System on Chip, so doesn't seem to have the same failure pathway for filesystem persistence when suspending as external USB filesystems, but it certainly fails.

Question 1: Is there now a fix/workaround for the case of USB-mounted external filesystems (meaning I can run Crouton from a USB-mounted filesystem on an SD card). In other words if I buy an external adaptor that could fix it.

Question 2: Where is the Crouton or Chromium bug to track which is specific to the Baytrail SOC case? Has the Kernel commit which seems to have triggered problems in USB-land anything at all to do with it.

What I experience is that all programs running off or using the SD card inserted in the Toshiba Chromebook's port are unstable or die when the system resumes. 

This could be because the filesystem descriptors they are retaining are invalid. However the filesystem also cannot be remounted after suspend until all running programs or open files are closed and the SD card is removed and reinserted. Then the filesystem automounts and becomes visible again. If the resume process was robust to some FDs still being open, then the problem wouldn't be as critical.

Below are some basic logs regarding the SD card filesystem run from within Crouton. Are any other logs worth exploring to identify what's going on?

```
(trusty)cefn@localhost:~$ mount -l | grep -E "BackupCard|Fat32Card"
/dev/mmcblk1p2 on /var/host/media/removable/Fat32Card type vfat (rw,nosuid,nodev,noexec,relatime,dirsync,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,flush,errors=remount-ro) [Fat32Card]
/dev/mmcblk1p1 on /var/host/media/removable/BackupCard type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered) [BackupCard]

(trusty)cefn@localhost:~$ sudo /sbin/fdisk -l /dev/mmcblk1

Disk /dev/mmcblk1: 128.7 GB, 128713752576 bytes
255 heads, 63 sectors/track, 15648 cylinders, total 251394048 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00012f39

        Device Boot      Start         End      Blocks   Id  System
/dev/mmcblk1p1            2048   131074047    65536000   83  Linux
/dev/mmcblk1p2       131074048   251394047    60160000    b  W95 FAT32
```

**Comment by dnschneid** [comment]
There's no baytrail-specific bug; most of it is mixed into #288.  I believe there are a couple crbugs linked in there as well.  It's really a Chromium OS issue, and probably needs a kernel patch to work around.
