### ISSUE TITLE
I'm having issues pulling up KDE on my Acer chromebook

### ISSUE THREAD

**Issue by sylvah** [dnschneid/crouton#2243]
I could pull it up before but then I donwloaded TF2 via steam, and now I get this error

Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Nov 5 10:38:47 PST 2015 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-1 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="2 vboot none ro 1,0 2545920 bootcache PARTUUID=367f9ccd-efbb-d541-8b04-eeedcf744779/PARTNROFF=1 2545920 347dcc3a890314fd79cc2bc9e012503488e9f98d 512 20000 100000, vroot none ro 1,0 2506752 verity payload=254:0 hashtree=254:0 hashstart=2506752 alg=sha1 root_hexdigest=4ed15a71b82ecd3e5342ff82f97dc6b286c22fea salt=3eadc2b4293b7d7aa6094e96c685f0ee865616960e68c96e5834e8c3564f4694" noinitrd vt.global_cursor_default=0 kern_guid=367f9ccd-efbb-d541-8b04-eeedcf744779 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Nov 16 09:33:10 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
Entering /mnt/stateful_partition/crouton/chroots/precise...

Help!!

**Comment by dnschneid** [comment]
Could you please post the output of `sudo edit-chroot -al`?
