### ISSUE TITLE
chroot won't unmount

### ISSUE THREAD

**Issue by Draenator** [dnschneid/crouton#2244]
So I'm sort of new to the bug/issue reporting thing; apologies if I'm doing it wrong.

Background: I was curious, making gdb debug dumps and prodding them with a hex editor because why not? Attached it to a running flash plugin (THIS is why not) and chroot is now impressively locked up - not a black screen, it looks perfectly normal and the mouse cursor moves, but xfce window/desktop/panels won't respond. ChromeOS side is still functional.

The issue: Tried to unmount nicely and I was rebuffed. The readout looks like what others w/ unmount issues have gotten before but since the session went rogue beforehand, I'm not sure its the same issue (or that it's even an error - like, major hanging process in the chroot, of course it'd say it's in use?) I'll use unmount -f next but just in case the nice way is supposed to handle this type of situation, here's the output/crouton version info.

    chronos@localhost / $ sudo unmount-chroot -p xfcechroot
    19656 su -s /bin/sh -c export SHELL='/bin/bash';'exec' 'startxfce4'  - andrea
    Not unmounting /mnt/stateful_partition/crouton/chroots/xfcechroot as another instance is using it.
    chronos@localhost / $ sudo enter-chroot -n xfcechroot
    Entering /mnt/stateful_partition/crouton/chroots/xfcechroot...
    (xfcechroot)andrea@localhost:~$ croutonversion
    crouton: version 1-20151104200003~master:2a1fc9da
    release: trusty
    architecture: amd64
    xmethod: xiwi
    targets: xfce,xiwi
    host: version 7390.68.0 (Official Build) stable-channel gandof 
    kernel: Linux localhost 3.14.0 #1 SMP Thu Nov 5 13:06:47 PST 2015 x86_64 x86_64 x86_64   GNU/Linux
    freon: yes
    (xfcechroot)andrea@localhost:~$ exit
    logout
    Not unmounting /mnt/stateful_partition/crouton/chroots/xfcechroot as another instance is using it.

**Comment by brmbrmcar** [comment]
This is very annoying. Sometimes -f will work, but you still then have to select SIGKILL.

**Comment by dnschneid** [comment]
Yeah, since you still have a (frozen) xfce session running in the background, unmount-chroot won't let you try unmounting the chroot without specifying -f.

@brmbrmcar: if you specify -y as well, unmount-chroot will escalate through SIGTERM and SIGKILL for you.
