### ISSUE TITLE
Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees)

### ISSUE THREAD

**Issue by wb0gaz** [dnschneid/crouton#2245]
I'm trying to use Crouton (on Acer C720) with Virtualbox to make an external USB device available to the Virtualbox guest (which is windows XP in this case.) I had not tried this before, but when I did, Virtualbox sees no USB devices, even though there is an external mouse and the other (USB modem) device attached. lsusb (done within the crouton environment) shows the mouse, USB modem, and a few other (internal to C720) devices present.

Is there something I need to do in crouton to expose USB devices to virtualbox?

Thank you!

**Comment by divx118** [comment]
Just to be sure: Did you install the virtualbox extension pack
https://www.virtualbox.org/wiki/Downloads

**Comment by wb0gaz** [comment]
Yes, virtualbox extension pack is installed and (otherwise) working (and guest extension icon is present in the tray of the windows xp guest.)

**Comment by divx118** [comment]
I never tried usb with virtualbox on chromebook, only on my regular linux
notebook, so it could be a chromebook/crouton issue. However since I don't
know your skills and to exclude things, you know your way around virtualbox
and have in the past setup usb devices with it? If not, I would suggest to
first take a look at the virtualbox documentation about adding usb devices.

**Comment by wb0gaz** [comment]
Still no headway... I tried

sudo VBoxManage list usbhost

and got

Host USB Devices:
<none>

while lsusb still shows all of the expected devices.




--------------------------------------------
On Tue, 11/17/15, Maurice van Kruchten <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees) (#2245)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Tuesday, November 17, 2015, 2:38 PM
 
 I never tried usb with virtualbox on
 chromebook, only on my regular linux
 notebook, so it could be a chromebook/crouton issue. However
 since I don't
 know your skills and to exclude things, you know your way
 around virtualbox
 and have in the past setup usb devices with it? If not, I
 would suggest to
 first take a look at the virtualbox documentation about
 adding usb devices.
 
 On Tue, Nov 17, 2015 at 9:29 PM, wb0gaz <notifications@github.com>
 wrote:
 
 > Yes, virtualbox extension pack is installed and
 (otherwise) working (and
 > guest extension icon is present in the tray of the
 windows xp guest.)
 >
 > —
 > Reply to this email directly or view it on GitHub
 > <https://github.com/dnschneid/crouton/issues/2245#issuecomment-157497476>.
 >
 
 
 ---

**Comment by wb0gaz** [comment]
Also, failed to answer your other question - I have been extensive virtualbox user for ~6 years (mostly linux host machines).

This (c720 with crouton and precise/gnome) machine/configuration is my "daily use" machine, and as I need to transition from wifi to usb modem for internet access (specific situation), I could also solve my problem by using linux as the client for the USB modem (it appears well supported under ubuntu), however, the configuration tools for managing network connections and devices appear missing or inoperative, so I was trying to run the service provider's client under virtualbox/windows guest with bridged Ethernet (which is also something I have used successfully in the past.)


--------------------------------------------
On Tue, 11/17/15, Maurice van Kruchten <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees) (#2245)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Tuesday, November 17, 2015, 2:38 PM
 
 I never tried usb with virtualbox on
 chromebook, only on my regular linux
 notebook, so it could be a chromebook/crouton issue. However
 since I don't
 know your skills and to exclude things, you know your way
 around virtualbox
 and have in the past setup usb devices with it? If not, I
 would suggest to
 first take a look at the virtualbox documentation about
 adding usb devices.
 
 On Tue, Nov 17, 2015 at 9:29 PM, wb0gaz <notifications@github.com>
 wrote:
 
 > Yes, virtualbox extension pack is installed and
 (otherwise) working (and
 > guest extension icon is present in the tray of the
 windows xp guest.)
 >
 > —
 > Reply to this email directly or view it on GitHub
 > <https://github.com/dnschneid/crouton/issues/2245#issuecomment-157497476>.
 >
 
 
 ---

**Comment by divx118** [comment]
@wb0gaz Almost forgot about this, I haven't had time yet to try it myself. However did you take a look at https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration Seems the way to go.

**Comment by wb0gaz** [comment]
That looks exactly like my issue!

I will apply the information this weekend and advise.

Thank you!

Dave
--------------------------------------------
On Fri, 12/4/15, Maurice van Kruchten <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees) (#2245)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Friday, December 4, 2015, 8:02 AM
 
 @wb0gaz Almost forgot about this, I
 haven't had time yet to try it myself. However did you take
 a look at https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration
 Seems the way to go.
 
 ---

**Comment by wb0gaz** [comment]
So far progress, not fully successful - I followed the configuration information for udev (which seeks to leverage chrome OS udev in the chroot space), then virtualbox (to enable USB devices); as far as I can tell, the /dev/vboxusb device node(s) is/are not getting created, so I manually (in the chroot) created /dev/vboxusb, and now virtualbox is seeing USB devices, but the guest (Windows XP) is not able to identify the attached device (for my test case, just using a USB thumb drive.)

Thanks for the pointer, still interested in getting this going!

Dave

--------------------------------------------
On Fri, 12/4/15, David Feldman <wb0gaz@yahoo.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees) (#2245)
 To: "dnschneid/crouton" <crouton@noreply.github.com>, "dnschneid/crouton" <reply@reply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Friday, December 4, 2015, 9:42 AM
 
 That looks exactly like my issue!
 
 I will apply the information this weekend and advise.
 
 Thank you!
 
 Dave
 --------------------------------------------
 On Fri, 12/4/15, Maurice van Kruchten <notifications@github.com>
 wrote:
 
  Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not
 seeing USB devices (lsusb sees) (#2245)
  To: "dnschneid/crouton" <crouton@noreply.github.com>
  Cc: "wb0gaz" <wb0gaz@yahoo.com>
  Date: Friday, December 4, 2015, 8:02 AM
  
  @wb0gaz Almost forgot about this, I
  haven't had time yet to try it myself. However did you
 take
  a look at https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration
  Seems the way to go.
  
  ---

**Comment by wb0gaz** [comment]
I think the Virtualbox/USB issue is solved - it was necessary to add a command in /etc/rc.local to mkdir /dev/vboxusb at each start of crouton (I doubt there is a problem with the original contributor's scripts, just something I didn't implement correctly at the outset). At this point, the AT&T wireless manager fails to see the device, even though it is fully present on windows xp device manager and meeting all of the various built in diagnostics of the AT&T wireless manager software, so even though crouton+Virtualbox+USB seems happy, my end goal is not met due to some misfire in AT&T application.

Much learned and appreciated, but probably not something I can put into regular use.

Dave

--------------------------------------------
On Mon, 12/7/15, David Feldman <wb0gaz@yahoo.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees) (#2245)
 To: "dnschneid/crouton" <crouton@noreply.github.com>, "dnschneid/crouton" <reply@reply.github.com>, "David Feldman" <wb0gaz@yahoo.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Monday, December 7, 2015, 11:15 AM
 
 So far progress, not fully successful
 - I followed the configuration information for udev (which
 seeks to leverage chrome OS udev in the chroot space), then
 virtualbox (to enable USB devices); as far as I can tell,
 the /dev/vboxusb device node(s) is/are not getting created,
 so I manually (in the chroot) created /dev/vboxusb, and now
 virtualbox is seeing USB devices, but the guest (Windows XP)
 is not able to identify the attached device (for my test
 case, just using a USB thumb drive.)
 
 Thanks for the pointer, still interested in getting this
 going!
 
 Dave
 
 --------------------------------------------
 On Fri, 12/4/15, David Feldman <wb0gaz@yahoo.com>
 wrote:
 
  Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not
 seeing USB devices (lsusb sees) (#2245)
  To: "dnschneid/crouton" <crouton@noreply.github.com>,
 "dnschneid/crouton" <reply@reply.github.com>
  Cc: "wb0gaz" <wb0gaz@yahoo.com>
  Date: Friday, December 4, 2015, 9:42 AM
  
  That looks exactly like my issue!
  
  I will apply the information this weekend and advise.
  
  Thank you!
  
  Dave
  --------------------------------------------
  On Fri, 12/4/15, Maurice van Kruchten <notifications@github.com>
  wrote:
  
   Subject: Re: [crouton] Crouton (Acer C720) -
 Virtualbox not
  seeing USB devices (lsusb sees) (#2245)
   To: "dnschneid/crouton" <crouton@noreply.github.com>
   Cc: "wb0gaz" <wb0gaz@yahoo.com>
   Date: Friday, December 4, 2015, 8:02 AM
   
   @wb0gaz Almost forgot about this, I
   haven't had time yet to try it myself. However did
 you
  take
   a look at https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration
   Seems the way to go.
   
   ---

**Comment by divx118** [comment]
IMO can be closed, to get USB working in virtualbox there is the following wiki https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration

**Comment by wb0gaz** [comment]
Agree to close.

Wiki procedure worked OK, however, application I require (ATT wireless manager for cellular device) did not work under virtualbox with XP guest on C720 (failed to find USB device, even though USB device is present in windows device manager), however, other USB devices are OK with wiki procedure to set up.

--------------------------------------------
On Sun, 12/27/15, Maurice van Kruchten <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees) (#2245)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Sunday, December 27, 2015, 7:49 AM
 
 IMO can be closed, to get USB working
 in virtualbox there is the following wiki https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration
 
 ---

**Comment by divx118** [comment]
@wb0gaz Can you close it (I don't have permission), thanks in advance. Less issues @dnschneid has to look over. He is a bit busy at the moment.

**Comment by wb0gaz** [comment]
Done

Thank you

--------------------------------------------
On Sun, 12/27/15, Maurice van Kruchten <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Virtualbox not seeing USB devices (lsusb sees) (#2245)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Sunday, December 27, 2015, 8:11 AM
 
 @wb0gaz Can you close it (I don't
 have permission), thanks in advance. Less issues @dnschneid
 has to look over. He is a bit busy at the moment.
 
 ---
