### ISSUE TITLE
Crouton (Acer C720) - Configure USB (cellular) modem as network device?

### ISSUE THREAD

**Issue by wb0gaz** [dnschneid/crouton#2246]
I wish to configure a USB cellular modem device (LG AD600 with AT&T wireless in US network) on Crouton configured with precise Ubuntu 12.04. Do I need to add a utility to facilitate configuration of the USB modem device? Applications->System Tools->System Settings->Network brings up a dialog box "The system network services are not compatible with this version".

Thank you!

**Comment by wb0gaz** [comment]
Thank you, Tony - that makes good sense. Unfortunately, without support for USB cellular modem in Chrome OS, Crouton or via USB Virtualbox (USB devices not accessible via Virtualbox), my daily-use Crouton on C720 must end. It has been good system...

--------------------------------------------
On Wed, 11/18/15, Tony Xue <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Configure USB (cellular) modem as network device? (#2246)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Wednesday, November 18, 2015, 2:26 PM
 
 The chroots directly use the Internet
 connection from Chrome OS. That's said, the work needs to be
 done on the Chrome OS side to make the device functional.
 However, I have no idea about third party modem on Chrome
 OS. Maybe you can try to ask around on Chrome OS mailing
 list?
 
 ---

**Comment by divx118** [comment]
You could enable legacy boot on the C720 and then just use a regular ubuntu
iso. I did that with fedora (lxde) on a HP chromebook 14 on a SD card. It
boots up in about 20-25 seconds. If I have some time this weekend I will
try USB devices on virtualbox.

**Comment by wb0gaz** [comment]
Thank you! I appreciate if you are able to test virtualbox issue.

I have looked at the alternative of regular ubuntu on c720 (there is good documentation for procedure) - if I cannot solve with crouton (only chance now is virtualbox, because usb modem is not part of chrome os), then legacy boot ubuntu is alternative, but crouton is much nicer system after almost 2 years using crouton!

Dave

--------------------------------------------
On Thu, 11/19/15, Maurice van Kruchten <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Configure USB (cellular) modem as network device? (#2246)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Thursday, November 19, 2015, 9:38 AM
 
 You could enable legacy boot on the
 C720 and then just use a regular ubuntu
 iso. I did that with fedora (lxde) on a HP chromebook 14 on
 a SD card. It
 boots up in about 20-25 seconds. If I have some time this
 weekend I will
 try USB devices on virtualbox.
 
 On Thu, Nov 19, 2015 at 3:43 PM, wb0gaz <notifications@github.com>
 wrote:
 
 > Thank you, Tony - that makes good sense. Unfortunately,
 without support
 > for USB cellular modem in Chrome OS, Crouton or via USB
 Virtualbox (USB
 > devices not accessible via Virtualbox), my daily-use
 Crouton on C720 must
 > end. It has been good system...
 >
 > --------------------------------------------
 > On Wed, 11/18/15, Tony Xue <notifications@github.com>
 wrote:
 >
 > Subject: Re: [crouton] Crouton (Acer C720) - Configure
 USB (cellular)
 > modem as network device? (#2246)
 > To: "dnschneid/crouton" <crouton@noreply.github.com>
 > Cc: "wb0gaz" <wb0gaz@yahoo.com>
 > Date: Wednesday, November 18, 2015, 2:26 PM
 >
 > The chroots directly use the Internet
 > connection from Chrome OS. That's said, the work needs
 to be
 > done on the Chrome OS side to make the device
 functional.
 > However, I have no idea about third party modem on
 Chrome
 > OS. Maybe you can try to ask around on Chrome OS
 mailing
 > list?
 >
 > ---
 > Reply to this email directly or view it on GitHub:
 > https://github.com/dnschneid/crouton/issues/2246#issuecomment-157869374
 >
 > —
 > Reply to this email directly or view it on GitHub
 > <https://github.com/dnschneid/crouton/issues/2246#issuecomment-158076298>.
 >
 
 
 ---

**Comment by tonyxue** [comment]
There is still a hope if your modem does support a regular linux system. I believe some work can be done to port it to Chrome OS. However, the job would be difficult as I think the modem driver wouldn't be opensource.

**Comment by wb0gaz** [comment]
Thank you, Tony, I appreciate your thoughts ---

The USB modem is LG AD600 with AT&T cellular service. While the modem is already supported by Ubuntu linux (and probably others) via the network manager utility, you helped me understand that crouton leverages chrome OS for network connectivity, and I am not prepared to participate in software development for Chrome OS, so my perspective is entirely as an end-user for that platform.

Thanks again,

Dave

--------------------------------------------
On Thu, 11/19/15, Tony Xue <notifications@github.com> wrote:

 Subject: Re: [crouton] Crouton (Acer C720) - Configure USB (cellular) modem as network device? (#2246)
 To: "dnschneid/crouton" <crouton@noreply.github.com>
 Cc: "wb0gaz" <wb0gaz@yahoo.com>
 Date: Thursday, November 19, 2015, 1:21 PM
 
 There is still a hope if your modem
 does support a regular linux system. I believe some work can
 be done to port it to Chrome OS. However, the job would be
 difficult as I think the modem driver wouldn't be
 opensource.
 
 ---
