### ISSUE TITLE
Hearthstone inside wine, inside linux, in a xiwi?

### ISSUE THREAD

**Issue by Anzii** [dnschneid/crouton#2248]
I was trying to run Hearthstone through wine inside a xiwi instance on chrome OS.
Now, since I'm new to this, it makes it quite a project, if not even impossible. :laughing: 
I've also installed the crouton extension.

I tried to change my Precise (has sound problem no matter what I do btw) build into a xiwi, but it lagged sooo bad and I couldn't make it fire up Battle.net, Hearthstone or Wine without booting the entire desktop environment. :confused: 

Next up, I tried making a setup with Core, Keyboard, Sound, X11, xiwi and a few more - it would only run in the background and I couldn't make it do anything at all, no matter what commands I fired at it. :cry: 

I'm running this on a Lenovo N20 Chromebook (Veeery low hardware)
If this is the wrong place to post, please point me in the right direction. :+1:

**Comment by Anzii** [comment]
So my idea was to make a clean installation, only with the needed things to run this, so that means a core, some xiwi, sound, keyboard and wine.
I am pretty sure I have to run wine in a xiwi before I can get battle.net or Hearthstone running over that, but I'm not even sure if I can run Bnet or HS directly in a xiwi without running wine first, so I'm here to ask for some assistance on what to do and what not to do. :smile:

**Comment by ComputerLag** [comment]
https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)

> xiwi (X11 in a Window) works by creating a window in Chrome and channeling a virtual X11
> framebuffer over to it. While crouton transfers the framebuffer relatively efficiently, there's **no GPU**
> **acceleration** and a fair bit of overhead, so **don't expect games** or graphics-heavy desktop environments
> **to perform well.** For basic productivity use it works great, though.

**Comment by boydkelly** [comment]
Just as a note of encouragement.....  I'm not a gamer, so no comment on the apps in particular that you want to run.  But I had the same lenovo as you, and I successfully ran windows apps within wine on ubuntu precise.  I now have an asus chromebook 11 and run stuff under wine with no desktop (although to get started you might want to install wine within an xfce4 desktop).   Once you confirm your app works under wine, you can migrate to a bash script that starts the wine apps either in a tab or window.    Works awesome and not really difficult.

**Comment by Anzii** [comment]
Thanks! ^_^

I'm running hearthstone with no lag in precise with desktop, then wine and so on.

Just how do you port it from a desktop installation to a non-desktop installation?
Do you simply uninstall the desktop part, or do you have to sort of "export" the installations?

**Comment by boydkelly** [comment]
You can just install wine to your chroot and once inside run "xiwi wine notepad".  If your program installs easily under wine you can reinstall with xiwi wine setup.exe.   If that doesn't work well then zip or tar your .wine directory from your xfce4 chroot and copy it to the new one.  You can make a bash script for the chronos user that calls the wine startup script in the chroot.

**Comment by divx118** [comment]
FYI Outside of the chroot you can use `startxiwi` to call xiwi in the chroot. So for example `startxiwi wine notepad` outside the chroot should work.

**Comment by Anzii** [comment]
Ok - I've come to the part where I have to run wine in order to install.
the setup file is located where it sould be (C:/windows/system32) in order for me to simply run
<code>sudo startxiwi wine setup.exe</code>
but it still says it can't find it and shuts down.. frustrating. :(

**Comment by boydkelly** [comment]
ok since your setup.exe windows program is not installed yet, why is it in
the sysem32 directory?  I should just be in your linux home directory.  To
make things a bit easier, do a sudo enter-chroot first so you can see whats
happening on the command line.  Then xiwi wine ~/Downloads/setup.exe.
As mentioned previously, you can always just tar up your .wine directory
from the xfce4 or gnome install and copy it to the new chroot and
everything is already installed.

**Comment by Anzii** [comment]
I put it there, since wine didn't find the file in there (in that specific folder).
But I'll try the folder you specified and update when I know more. :)

**Comment by Anzii** [comment]
Ok, at this point, I'm trying to figure out what I'm doing wrong as it opens the battle.net client, but then closes.
I try to open through the chroot shell terminal, but it says:
[code] (precise)admin@localhost:~/Desktop$ ./Battle.net.desktop
./Battle.net.desktop: line 1: [Desktop: command not found
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
fixme:exec:SHELL_execute flags ignored: 0x00000100
fixme:exec:SHELL_execute flags ignored: 0x00004100
./Battle.net.desktop: line 6: here: command not found
./Battle.net.desktop: line 7: syntax error near unexpected token `('
./Battle.net.desktop: line 7: `Path=/home/admin/.wine/dosdevices/c:/Program Files (x86)/Battle.net'
(precise)admin@localhost:~/Desktop$ fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:process:GetLogicalProcessorInformation (0x33ea70,0x33f07c): stub
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.[/code]

**Comment by Anzii** [comment]
oh, and now I tried to use PlayOnLinux to open the file and got:
<code>wine: /home/admin/.PlayOnLinux//wineprefix/default is not owned by you</code>

**Comment by DennisLfromGA** [comment]
> wine: /home/admin/.PlayOnLinux//wineprefix/default is not owned by you

@Anzii - Sometimes file & folder permissions in your chroot get messed up, especially when starting/running apps as 'root'. You can reset them all to your ownership - see https://github.com/dnschneid/crouton/issues/2176#issuecomment-147473247.

**Comment by Anzii** [comment]
thanks for all the help - I ended up getting it to work with a clean install (including the XFCE desktop environment), working on playonlinux to get the game running inside without problems, then running it in xiwi.

Result: Working but with 4-6 frames per second. :+1: 

Thanks for all the help, support and tips. I'm starting to like linux more, the more I work with it and I think I might keep linux close for the next few projects I'm starting! :smile_cat:
