### ISSUE TITLE
Crouton fails to start

### ISSUE THREAD

**Issue by otny1** [dnschneid/crouton#2249]
I am currently using a Samsung Chromebook 2 (winky)

(output of sudo enter-chroot -n precise croutonversion)
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 7390.68.0 (Official Build) stable-channel winky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Nov 5 13:16:55 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

When ever I try to use the command  sudo startxfce4 i get this:
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Nov 5 13:16:55 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=2f758a82-b2fc-4a4a-a1c4-0619a611080d/PARTNROFF=1 hashtree=PARTUUID=2f758a82-b2fc-4a4a-a1c4-0619a611080d/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=cfc1c1113a27a21ce4e751ce2127ce13246302e1 salt=f7c95420ed6aebe52ea34025da54810b436a4138880a8e443b8d51fc50922b1f" noinitrd vt.global_cursor_default=0 kern_guid=2f758a82-b2fc-4a4a-a1c4-0619a611080d add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Nov 19 21:33:15 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I am not sure what is going on I have tried updating crouton and uninstalling trying unity and then going back.  This always seems to happen on the second boot can anyone please help?

**Comment by brookschilders** [comment]
I have the same problem on a Hisense Chromebook 11. Tried both xfce and unity installs. No joy.

**Comment by otny1** [comment]
The no screens found just means that there was an error and there are no screens left which the server can successfully drive

**Comment by anoda9** [comment]
Similar problem here, using an asus c201 chromebook.

**Comment by raphaelfalc** [comment]
similar problem also... ASUS c100

**Comment by anoda9** [comment]
For the asus c201 chromebook, this solved the problem: 
https://github.com/dnschneid/crouton/wiki/Asus-C201#x11-does-not-find-any-screensfbdev-not-found

For more help try searching on reddit/r/crouton - 
https://www.reddit.com/r/Crouton/comments/3jte7e/help_fatal_server_error_no_screens_found/
