### ISSUE TITLE
Specify cache directory for apt-get commands

### ISSUE THREAD

**Issue by cornop** [dnschneid/crouton#2251]
Is it possible to specify a cache directory for the `apt-get` commands that crouton invokes, i.e. add `-o dir::cache::archives="/path/to/somewhere"` to the command line flags of `apt-get`?

**Comment by dnschneid** [comment]
You should be able to set preferences (such as cache directory) in the chroot's [apt.conf](http://linux.die.net/man/5/apt.conf), and crouton will respect it.
