### ISSUE TITLE
installing 32 bit trusty / precise

### ISSUE THREAD

**Issue by rowokii** [dnschneid/crouton#2253]
I've been trying to install 32 bit linux chroot on my Acer CB3-111 chromebook.
Version 46.0.2490.82 (64-bit)
Platform 7390.68.0 (Official Build) stable-channel gnawty
Firmware Google_Gnawty.5216.239.34

I have tried several fresh install using the -a i386 / -a i686 on both trusty and precise, for example:
sudo sh ~/Downloads/crouton -t xfce -r trusty -a i386 -e

but each time, when I type uname -m in the linux terminal, it comes back as x86_64, instead of expected i686 or i386.  

Any way to install 32 bit on the 64bit Chromos?

Thanks.

**Comment by DennisLfromGA** [comment]
You can specify the architecture when installing your chroot using the `-a` option - see https://github.com/dnschneid/crouton/issues/734#issuecomment-39347222

**Comment by divx118** [comment]
The command line you used will install i386 packages, however the kernel will not change, because it is the kernel from chromeos and cannot be changed. So `uname -m` will always keep reporting x86_64.  That said the 64 bit kernel will support the i386 packages.
Any specific reason for using 32bit?

**Comment by rowokii** [comment]
Thanks for the reply divx118.  Hum... i guess I need to forget about getting my crusty old windows CAD program to run on my chromebook.  It will run in wine, but only under 9x mode.  Wine 9X mode seems to break in 64 bit kernel.   Something about 16bit mode no longer being supported in 64bit kernel, which breaks wine.  I can't even start the wine config program once I set the mode to 98....

**Comment by dnschneid** [comment]
If your goal is running Windows 9x software, you should look into Dosbox.
