### ISSUE TITLE
I've pdf files stored at Parse DB, when user tapped a selected file at collection viewcontroller and would like to display the content using GitHub open source pdf reader

### ISSUE THREAD

**Issue by vin8899** [dnschneid/crouton#2254]
I'm learning swift code now have no knowledge in objective-c , the pdf file was uploaded using parse backend. 
I knew that Github pdf reader required the filename and document path , so how am i get the filename in e.g.."Humour 1.pdf" and how to get the document path/directory  which i can assigned to the pdf reader ?. So far googling only showed that the url is hardcoded or get from local directory but doesn't mention how to get path from the selected row from Parse database!  
Appreciates anyone can help and provide some swift code!. thanks

The parse structure as below:
![parse-bookmaster](https://cloud.githubusercontent.com/assets/15228579/11322720/1fe2ca36-9134-11e5-88df-aca340cb759b.png)

The Github pdf reader below which incorporated into swift code:

class ViewController: UIViewController , ReaderViewControllerDelegate{
@IBAction func didClickOpenPDF(sender: AnyObject) {
let file = NSBundle.mainBundle().pathForResource("Test", ofType: "pdf")
let document:ReaderDocument = ReaderDocument.withDocumentFilePath(file, password: nil)
print(file)
print("DOcument = ", document)

if (document != "")
{
    print("not empty")
    let readerViewController:ReaderViewController = ReaderViewController(readerDocument: document)
    readerViewController.delegate = self
   readerViewController.modalTransitionStyle = UIModalTransitionStyle.CrossDissolve
    readerViewController.modalPresentationStyle = UIModalPresentationStyle.FullScreen
 [self.presentViewController(readerViewController, animated: true, completion: nil)]
}
}

**Comment by divx118** [comment]
Looks to me like another #262, so you are posting on the wrong issue tracker this has nothing to do with [crouton on chromebooks](https://github.com/dnschneid/crouton/).

**Comment by vin8899** [comment]
yea just realise will delete. Thanks

**Comment by divx118** [comment]
Thanks for closing :)
