### ISSUE TITLE
X server prognosis after Freon?

### ISSUE THREAD

**Issue by fortran77** [dnschneid/crouton#2256]
Now that Google is switching to the new Freon graphics stack, more and more Crouton users are reporting various issues related to a missing X server. Just recently, I was trying to invoke an X command (specifically, virt-manager) on a remote system accessed via ssh from a Crouton environment on a Chromebox, and got error messages, because there's no X server any more.

The purpose of my opening this issue is to try to get an answer to this question:

For those of us who sometimes need to execute X programs on a remote machine and pipe them via ssh into our Crouton display, is there some possibility that in the near future Crouton will be able to provide something to replace the X server that it used to have?

Or should we (with great sadness) begin migrating away from Crouton?

**Comment by dnschneid** [comment]
For the most part, crouton works just fine with freon.  And when the native X11 server that crouton launches (alongside freon) doesn't work, there's always xiwi.  If you're looking for a good X11-forwarding experience, I recommend installing the xiwi target and running `sudo startxiwi -T xterm` or something, and then sshing from the terminal that appears in a tab.

**Comment by fortran77** [comment]
Thank-you, X11-forwarding is working nicely now.
