### ISSUE TITLE
Chromebook died, needs a restore usb. Is the chroot gonna get deleted?

### ISSUE THREAD

**Issue by falafflepotatoe** [dnschneid/crouton#2258]
Hey Im trying to save my src code and would love to ask @dnschneid if he has any suggestions. sorry this is not a crouton issue.

My chromebook powered off and now wants a restore image, i would love to get my src from the chroot first.

If I do the restore instructions from google what happens to the chroot?

If you know how I can:

-get past the chromeos encryption
-boot and get a term
-enter chroot with wifi to backup my code

or have any suggestions im willing to listen.

sorry for asking but i dont know much about the chrome os internals.

**Comment by divx118** [comment]
I think you got a problem. Best change would be if it is possible on your chromebook (not every chromebook has a removable ssd) to remove the SSD and mount it on a linux machine. With a restore USB (following instructions from google)  the chroot will get wiped.

**Comment by falafflepotatoe** [comment]
@divx118 or @dnschneid 
If i move the SSD to a linux box -- the entire chromeOS is encrypted no? How can i mount it? I thought the encryption key was stored in a shadowed + enecrypted file. :/ if you know more about how chrome does this plz let me know.

**Comment by divx118** [comment]
The chroot is on the first partition of the ssd. This partition is not encrypted and can be mounted with a normal mount command (type is ext4). Note that  the dir `Downloads` in the chroot is a bindmount with the one from chromeos, that one is encrypted so no access to that. I don't know a way to access the encrypted files from chromeos. Success on getting your files back, I don't think I need to tell you to make a backup next time... I also learned more then once the hard way.
