### ISSUE TITLE
fail to use docker on my chromebook pixel in crouton.

### ISSUE THREAD

**Issue by harryprince** [dnschneid/crouton#2259]
I fail to use docker on my chromebook pixel in crouton.
this is the error:

```
$ docker pull
docker: "pull" requires 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry
```

```
$ docker pull ubuntu
Using default tag: latest
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```
$ sudo docker pull ubuntu
Using default tag: latest
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```
sudo docker daemon
WARN[0000] Your Linux kernel version 3.8.11 can be unstable running docker. Please upgrade your kernel to 3.10.0. 
ERRO[0000] [graphdriver] prior storage driver "devicemapper" failed: Error running deviceCreate (CreatePool) dm_task_run failed 
FATA[0000] Error starting daemon: error initializing graphdriver: Error running deviceCreate (CreatePool) dm_task_run failed 
```

and here is the information of core:

```
$ uname -a
Linux localhost 3.8.11 #1 SMP Mon Nov 16 23:42:11 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```
$ sudo service docker start
start: Unknown job: docker
```

I am really confusing why I can find the path of docker from /etc/init and /etc/default， but I fail to start my docker deamon?

```
$ ls /etc/init |grep docker
docker.conf
```

```
$ ls /etc/default/ |grep docker
docker
```

I have tried some methos from Google and GitHub, but I failed.

**Comment by sedlund** [comment]
docker will not run in crouton.  chromeos will not give access to the network and kernel modules required to start docker.  If you want docker I suggest learning how to install virtualbox in crouton, run a regular linux distribution in that, and then run docker on it.

**Comment by perpen** [comment]
Running docker natively for now involves installing a custom kernel and quite a bit of hacking.
I used to do this but I'm now pretty satisfied just using docker-machine to run the containers on a remote box on digitalocean.

**Comment by air** [comment]
Rkt works fine https://github.com/dnschneid/crouton/issues/2777#issuecomment-286509382
