### ISSUE TITLE
Is the volume control button works only for pulseaudio?

### ISSUE THREAD

**Issue by KirisDK** [dnschneid/crouton#2262]
I'm using precise now. In my case, the volume is not synced. I can hear the sound. The volume control button was not working and but the volume of chromeOS and crouton is synced. I install pulseaudio because mixer shows error about Gstreamer. 
After I install pulseaudio, I can change the volume with volume button in crouton but ChromeOS's volume is not moving at all. How can I use volume control button to control crouton and chromeos's volume synced?

**Comment by dnschneid** [comment]
The best way (at the moment) is to set up a keyboard shortcut to use the `volume up` and `volume down`  commands, which will directly affect Chromium OS's volume setting.
