### ISSUE TITLE
Keycodes for croutontriggerd

### ISSUE THREAD

**Issue by eeg710** [dnschneid/crouton#2264]
I am trying to replace the Ctrl-Alt-Shift-F1 and Ctrl-Alt-Shift-F2 with Ctrl-Alt-Shift-Up and Ctrl-Alt-Shift-Down. I am able to change that for one direction using xbindkeysrc.scm but I can't figure out what keycodes to use for croutontriggerd. Is there a list somewhere?

**Comment by dnschneid** [comment]
It's the evdev codes.  The easiest way is probably to just edit croutontriggerd and add a line `$TYPE == $TYPE_EV_KEY { print $KEY }` around line 91, then run croutontriggerd and hit the keys you're interested in.
