### ISSUE TITLE
No sound and super slow Kodi after updating Crouton

### ISSUE THREAD

**Issue by paultje1981** [dnschneid/crouton#2265]
I was having some crackling issues when using Kodi in the Crouton (xfce4) on a Chromebook C720 so I decided to try and update the chroot. After the update, there is no sound in the chroot and while Kodi starts it is super slow and impossible to watch anything. Almost like something is slowing down the internet connection. The problem also persists when opening Youtube in the xfce built in browser- videos will load but not play. Within the ChomeOS everything works fine.

I'm a complete newbie, however I was so happy that everything was working prior that I now have no clue what to do. Someone please help?

**Comment by paultje1981** [comment]
I just did a powerwash and started from scratch, but the issue remains. Here's the steps I took:

- Press space at startup, let it restore to original state)
- enter development mode (Press and hold the Esc and Refresh keys together, then press the Power button)
- sudo chromeos-setdevpasswd
- sudo sh ~/Downloads/crouton -t xfce
- sudo startxfce4
- Kodi install from within xfce terminal window:

sudo apt-get install python-software-properties pkg-config
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi

Any thoughts would be much appreciated!

**Comment by DennisLfromGA** [comment]
@paultje1981 - What's the output of: `sudo edit-chroot -al` ?
If you're using 'xiwi' then you might try switching to 'xorg'.

**Comment by paultje1981** [comment]
The problem actually resolved after upgrading from precise to trusty and subsequently updating Kodi to 15.2! No idea what the problem was...

**Comment by DennisLfromGA** [comment]
*Good that you could figure it out yourself*. :+1: 
I've been using kodi on a trusty release with 'xorg' for a while now and it seems to work really well.

**Comment by paultje1981** [comment]
It's the best! Got me stressed out for about 8 hours thinking the crouton update completely broke it... Thank you!

**Comment by DennisLfromGA** [comment]
Now make sure you back it up and save it with something like:

`sudo edit-chroot -b -f /path/to/external/media -n [chrootname]`
