### ISSUE TITLE
error, no screens found, asus c100 flip chromebook

### ISSUE THREAD

**Issue by raphaelfalc** [dnschneid/crouton#2266]
I'm trying to start linux on my asus C100 flip chromebook, my log:

[  2652.893] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[  2652.894] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[  2652.894] X Protocol Version 11, Revision 0
[  2652.894] Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
[  2652.894] Current Operating System: Linux localhost 3.14.0 #1 SMP Thu Nov 5 13:08:24 PST 2015 armv7l
[  2652.894] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=ad98e513-46d2-2c40-8fcd-1dbbe0068fcf/PARTNROFF=1 hashtree=PARTUUID=ad98e513-46d2-2c40-8fcd-1dbbe0068fcf/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=4466da948e47b46a641a199779da748deacd6c56 salt=cb9998eeefe1f35b7ed7728df16d17fb53f284c334c6a886d415e9052eb43dde" noinitrd vt.global_cursor_default=0 kern_guid=ad98e513-46d2-2c40-8fcd-1dbbe0068fcf  
[  2652.894] Build Date: 05 November 2013  03:23:26PM
[  2652.894] xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
[  2652.894] Current version of pixman: 0.30.2
[  2652.895] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  2652.895] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  2652.895] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Nov 28 21:49:55 2015
[  2652.895] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  2652.896] (==) No Layout section.  Using the first Screen section.
[  2652.896] (==) No screen section available. Using defaults.
[  2652.896] (**) |-->Screen "Default Screen Section" (0)
[  2652.896] (**) |   |-->Monitor "<default monitor>"
[  2652.896] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[  2652.896] (==) Automatically adding devices
[  2652.896] (==) Automatically enabling devices
[  2652.896] (==) Automatically adding GPU devices
[  2652.896] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  2652.896] 	Entry deleted from font path.
[  2652.896] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  2652.896] 	Entry deleted from font path.
[  2652.896] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  2652.896] 	Entry deleted from font path.
[  2652.896] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  2652.896] 	Entry deleted from font path.
[  2652.896] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  2652.896] 	Entry deleted from font path.
[  2652.896] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  2652.896] 	Entry deleted from font path.
[  2652.896] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  2652.896] 	Entry deleted from font path.
[  2652.896] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[  2652.896] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  2652.896] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[  2652.896] (II) Loader magic: 0xb6fd1e58
[  2652.896] (II) Module ABI versions:
[  2652.896] 	X.Org ANSI C Emulation: 0.4
[  2652.897] 	X.Org Video Driver: 13.0
[  2652.897] 	X.Org XInput driver : 18.0
[  2652.897] 	X.Org Server Extension : 7.0
[  2652.897] (II) config/udev: Adding drm device (/dev/dri/card1)
[  2652.898] Initializing built-in extension Generic Event Extension
[  2652.898] Initializing built-in extension SHAPE
[  2652.898] Initializing built-in extension MIT-SHM
[  2652.898] Initializing built-in extension XInputExtension
[  2652.898] Initializing built-in extension XTEST
[  2652.898] Initializing built-in extension BIG-REQUESTS
[  2652.898] Initializing built-in extension SYNC
[  2652.898] Initializing built-in extension XKEYBOARD
[  2652.898] Initializing built-in extension XC-MISC
[  2652.898] Initializing built-in extension SECURITY
[  2652.898] Initializing built-in extension XINERAMA
[  2652.898] Initializing built-in extension XFIXES
[  2652.898] Initializing built-in extension RENDER
[  2652.898] Initializing built-in extension RANDR
[  2652.898] Initializing built-in extension COMPOSITE
[  2652.898] Initializing built-in extension DAMAGE
[  2652.898] Initializing built-in extension MIT-SCREEN-SAVER
[  2652.898] Initializing built-in extension DOUBLE-BUFFER
[  2652.898] Initializing built-in extension RECORD
[  2652.898] Initializing built-in extension DPMS
[  2652.898] Initializing built-in extension X-Resource
[  2652.898] Initializing built-in extension XVideo
[  2652.898] Initializing built-in extension XVideo-MotionCompensation
[  2652.899] Initializing built-in extension XFree86-VidModeExtension
[  2652.899] Initializing built-in extension XFree86-DGA
[  2652.899] Initializing built-in extension XFree86-DRI
[  2652.899] Initializing built-in extension DRI2
[  2652.899] (II) LoadModule: "glx"
[  2652.904] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  2652.905] (II) Module glx: vendor="X.Org Foundation"
[  2652.905] 	compiled for 1.13.0, module version = 1.0.0
[  2652.905] 	ABI class: X.Org Server Extension, version 7.0
[  2652.905] (==) AIGLX enabled
[  2652.905] Loading extension GLX
[  2652.905] (==) Matched modesetting as autoconfigured driver 0
[  2652.905] (==) Matched fbdev as autoconfigured driver 1
[  2652.905] (==) Assigned the driver to the xf86ConfigLayout
[  2652.905] (II) LoadModule: "modesetting"
[  2652.906] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  2652.906] (II) Module modesetting: vendor="X.Org Foundation"
[  2652.906] 	compiled for 1.13.0, module version = 0.5.0
[  2652.906] 	Module class: X.Org Video Driver
[  2652.906] 	ABI class: X.Org Video Driver, version 13.0
[  2652.906] (II) LoadModule: "fbdev"
[  2652.906] (WW) Warning, couldn't open module fbdev
[  2652.906] (II) UnloadModule: "fbdev"
[  2652.906] (II) Unloading fbdev
[  2652.907] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  2652.907] (==) Matched modesetting as autoconfigured driver 0
[  2652.907] (==) Matched fbdev as autoconfigured driver 1
[  2652.907] (==) Assigned the driver to the xf86ConfigLayout
[  2652.907] (II) LoadModule: "modesetting"
[  2652.907] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  2652.907] (II) Module modesetting: vendor="X.Org Foundation"
[  2652.907] 	compiled for 1.13.0, module version = 0.5.0
[  2652.907] 	Module class: X.Org Video Driver
[  2652.907] 	ABI class: X.Org Video Driver, version 13.0
[  2652.907] (II) UnloadModule: "modesetting"
[  2652.907] (II) Unloading modesetting
[  2652.907] (II) Failed to load module "modesetting" (already loaded, -1224009512)
[  2652.907] (II) LoadModule: "fbdev"
[  2652.908] (WW) Warning, couldn't open module fbdev
[  2652.908] (II) UnloadModule: "fbdev"
[  2652.908] (II) Unloading fbdev
[  2652.908] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  2652.908] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  2652.908] (--) using VT number 7

[  2652.917] (WW) Falling back to old probe method for modesetting
[  2652.918] (EE) open /dev/dri/card0: No such file or directory
[  2652.918] (EE) No devices detected.
[  2652.918] 
Fatal server error:
[  2652.918] no screens found
[  2652.918] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[  2652.918] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  2652.918] (EE) 
[  2652.933] Server terminated with error (1). Closing log file.

I've updated my crouton and have tried these commands https://github.com/dnschneid/crouton/issues/1938
but after typing sudo rm /dev/dri/card0 all I get is "cannot remove `/dev/dri/card0': No such file or directory"

**Comment by davidgiven** [comment]
AFAIK Framebuffer X isn't supported on the C100 (I have one too). I use the X server which embeds into a Chrome tab --- sorry, I can't remember the name right now. It's not as fast but does have the advantage of working.

**Comment by DennisLfromGA** [comment]
@raphaelfalc - I think @davidgiven is referring to the xmethod 'xiwi' that can be added using the '-t xiwi' option to crouton either with the initial installation or during an update.

**Comment by dnschneid** [comment]
You should be able to use xorg in the latest crouton on the Flip; no hacks needed.
