### ISSUE TITLE
Unreliable X refresh with Chrome integration

### ISSUE THREAD

**Issue by davidgiven** [dnschneid/crouton#2267]
I have an Asus Flip C100PA; I've just installed crouton running jessie, with X running in a Chrome tab (because fbdev X isn't supported on Freon, right?). It's a custom desktop environment based on Awesome.

Unfortunately I'm finding that X refresh doesn't work all the time, which means I get dirty rectangles which aren't flushed onto the screen. It's most pronounced with gtk and qt apps, but I can see it happen occasionally with good old fashioned rxvt too.

I assume this isn't a common occurrance --- any ideas why I am special?

**Comment by dnschneid** [comment]
I think this is fixed now; please re-open if you still see it.
