### ISSUE TITLE
Starting two X11 sessions causes random vt switching

### ISSUE THREAD

**Issue by wymby** [dnschneid/crouton#2268]
Since about 2 months ago, starting two X11 sessions (one local, one to a remote machine) from a chroot shell prompt in vt1 causes random switching back to vt1 from either of them. It happens every 1-15 seconds or so for no apparent reason, and returns to the X11 vt in 1-to-10 seconds, or immediately if something is typed. It persists if one of the X11 sessions is terminated or even if the chroot is exited and re-entered and one X11 session restarted. The 2nd session says "Another instance of croutontriggerd running, waiting..." on vt1.

This has been happening since I implemented the 10/24 root/sudo workaround in #2083. Crtl-Alt-Back/Forward stopped working at the same time, but Ctrl-Alt-Shift-Back works. Crouton version is :2a1fc9da. I have a Debian jessie chroot with an x11 target on an Acer C710.

**Comment by drinkcat** [comment]
Obsolete since freonization, I guess.
