### ISSUE TITLE
Can't upgrade Ubuntu from precise to trusty

### ISSUE THREAD

**Issue by eeg710** [dnschneid/crouton#2269]
When I try to run `sudo do-release-upgrade` I get an error

```
Could not calculate the upgrade 

An unresolvable problem occurred while calculating the upgrade. 

This can be caused by: 
* Upgrading to a pre-release version of Ubuntu 
* Running the current pre-release version of Ubuntu 
* Unofficial software packages not provided by Ubuntu
```

Is there some information I can provide to help fix this?

**Comment by DennisLfromGA** [comment]
@eeg710 - It looks like this may be a known bug: [Bug #1357566](https://bugs.launchpad.net/ubuntu/+source/update-manager/+bug/1357566).

**Comment by Kali341** [comment]
Have you tried backing up any personal files and creating a new bootable drive?
