### ISSUE TITLE
Mousepad and xfce (trustry): cannot move or resize windows

### ISSUE THREAD

**Issue by gerald-drissner** [dnschneid/crouton#2270]
I have an Asus C200 and use crouton: xfce, 14.04. Everything is working fine, except my mousepad. I can move the curse, double click works fine - but I cannot drag and drop, nor can I resize or move windows. It seems like that clicking and moving all together doesn't work. Any thoughts? Thanks!

**Comment by vomc** [comment]
Having the same issue, running ubuntu trusty (14.04) with KDE and I can't drag or resize windows. Also stock KDE notifications pop up without disappearing and they obstruct all other browser tabs. Guessing that this is not something that can be addressed through crouton though...

**Comment by drinkcat** [comment]
Might be missing some synclient setting...
