### ISSUE TITLE
Unable to background chroot in Acer Chromebook 13 [CB5-311]

### ISSUE THREAD

**Issue by KenDickey** [dnschneid/crouton#2274]
In my old Samsung ARM Chromebook I was able to background the ChromeOS shell, exit to CROSH, and exit the CROSH shell, then use shift+ctrl+alt + left|right arrows to switch between Ubuntu and ChromeOS.

On the Acer Chromebook 13 I am unable to do this.

Backgrounding the chroot causes the loss of ability to switch between ChromeOS and Ubuntu views.

Any hints on how to properly do this?

Thanks much,
-KenD

**Comment by DennisLfromGA** [comment]
It *should* still work when using xmethiod 'xorg'. 
I run mine in the background (-b) regularly and am still able to switch back and forth using the <kbd>shift+ctrl+alt+left|right</kbd> arrows.

**Comment by ramonsuarez** [comment]
I had the same issue and it was due to some problem with xiwi and updates. I had to uninstall xiwi by running ```sudo sh -e crouton -u -n trusty -t x11 ``` from the directory where the crouton script is saved (\Downloads)
