### ISSUE TITLE
is the "Build chrome os kernel and kernel modules" wiki still valid?

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#2276]
I am trying to run `autofs` on my pixel 2015 with crouton but the autofs service won't start.  I've heard rumors that I need to install an autofs kernel module.  I tried to follow the wiki page "Build chrome os kernel and kernel modules" to build my `autofs5.ko` module but I ran into a problem quickly.  Here is what happened when I tried `modprobe configs`.

```
FATAL: Error inserting configs (/lib/modules/3.14.0/kernel/kernel/configs.ko): Operation not permitted
``` 

Is this the module_locking problem?  If so how can I get past this?

**Comment by divx118** [comment]
Probably yes, you can be sure when you look at the dmesg messages. To disable the module locking you will have to either follow https://github.com/dnschneid/crouton/wiki/Enable-kernel-VT_x-for-Virtualbox or you can use my script which automates the process [change-kernel-flags](https://github.com/divx118/crouton-packages/blob/master/change-kernel-flags)
> For being able to load modules outside /lib/modules from chromeos we will need to disable module_locking.
This can be done by changing the kernel flags. I wrote a little script that does this for you and also has the option to revert the changes.  
Open a **crosh** shell and follow on screen instructions:
```
$ cd ~/Downloads
$ wget https://raw.githubusercontent.com/divx118/crouton-packages/master/change-kernel-flags
$ sudo sh ~/Downloads/change-kernel-flags
```
When running `sudo sh ~/Downloads/change-kernel-flags -h` it will give you the usage. 
When you want to revert the changes so put back a backup kernel use -r  
`sudo sh ~/Downloads/change-kernel-flags -r`  

**Note:** You will need to repeat the above steps after each chromeos update.

**Comment by mark-hahn** [comment]
I saw that script.  I meant to also ask if that was up-to-date.  So thanks
for the info and the script.  Now I just need to have a few drinks to get
the courage to mess with the kernel.

**Comment by mark-hahn** [comment]
I built the module and installed it.  Thanks mucho.  Now I just have to figure out how to use it.  See #1046.
