### ISSUE TITLE
Change default folder for chroot?

### ISSUE THREAD

**Issue by bangity** [dnschneid/crouton#2278]
I installed to /media/removable/SD_Card. whenever I update crouton, i have to specify the -p and -c for backup and restore.

Is there a way to change the default chroot folder permanently?

**Comment by DennisLfromGA** [comment]
@bangity - 

I don't think *permanently* but you can setup 'aliases' in a `.bashrc` or `.bash_aliases` file, etc. that make it painless to launch them.
I have some setup to use my 'crispy' crouton partition but you could do the same for your external media.  *Here are a couple examples of mine:*

`alias startunity='sudo startunity -c /var/crouton/chroots'`
`alias edit-chroot='sudo edit-chroot -c /var/crouton/chroots'`
`alias enter-chroot='sudo enter-chroot -c /var/crouton/chroots'`

I included *`sudo`* in mine which I'm sure is probably frowned upon...

-**DennisL**
