### ISSUE TITLE
how to add my own target for crouton ubuntu

### ISSUE THREAD

**Issue by aurey2244** [dnschneid/crouton#2280]
Can anyone help me understand how to do this please? I looked online but couldn't find anything. target ex: fvwm-crystal, mate, etc

**Comment by DennisLfromGA** [comment]
I did it once upon a time, making a slight modification to an existing target, but not recently.

You can get an idea of how to format them by looking at one or more of crouton's targets, '[gnome-desktop]()' for example. Once you have your target scripted, you can add it to crouton with the '-T' option:
```
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
```

**Comment by aurey2244** [comment]
OK so I've made my own, and tried:
bash crouton -r trusty -T mate

and i get in return:
 Moving bootstrap files into the chroot...
Preparing chroot environment...
No target list found (your chroot may be very old).
Please specify targets with -t.

I put the custom chroot in the downloads folder what am I doing wrong?

**Comment by DennisLfromGA** [comment]
@aurey2244,

> I put the custom chroot in the downloads folder what am I doing wrong?

That's good, make sure you 'cd' into 'crouton-master' or whatever yours is named.
Once you've placed your custom targets file in the `targets` folder, run something like: 

`sudo sh installer/main.sh -r trusty -t xorg,xiwi,extension -T targets/mate`

You should use 'sh' not 'bash'.

**Comment by aurey2244** [comment]
Thanks you very much, been trying to do this i will try immediately

**Comment by dnschneid** [comment]
fwiw, if you're going to use `-T`, you don't need to place the target in the targets folder.  That means you can use the stock bundled installer as well.

**Comment by DennisLfromGA** [comment]
Good to know, thanx.
I know it's supposed to point to the path of a custom target file so maybe the '`-T mate`' that the OP listed wasn't the actual file.
