### ISSUE TITLE
External Wireless Adapter

### ISSUE THREAD

**Issue by SaMuR4i** [dnschneid/crouton#2282]
Hello all.  Is there anyway to enable an external USB wireless adapter?  I know that Chrome OS won't allow it, but I was hoping to bypass that in Kali 2.0 (sana).  The drivers for my adapter are already installed, but I can't seem to enable the device.  Is that due to the Chomebook firmware/Chrome OS' built-in restriction?  Thank you!

**Comment by SaMuR4i** [comment]
I'm using a Toshiba Chromebook 2 (Swanky).  I'd prefer to use the built-in wifi card, but I can't seem to get packet injection to work on the current iwlwifi driver.  Any advice would be greatly appreciated.  Thank you.

**Comment by Kali341** [comment]
Are you running it on VM?

**Comment by SaMuR4i** [comment]
I'm using crouton.

**Comment by drinkcat** [comment]
Not really. If Chrome OS does not have driver support, and you're not willing to build your own kernel modules, it won't work.

You could file a Chromium OS bug though, if you want some specific device support to be added (no guarantee though).
