### ISSUE TITLE
Failed to complete chroot setup (failed to fetch)

### ISSUE THREAD

**Issue by ohnoplus** [dnschneid/crouton#2284]
Hello, I am trying to install crouton on an ASUS Chromebok Flip. I tried running sudo sh -e ~/Downloads/crouton -t touch,xfce and the installation doesn't seem to work. 
The last few lines of my installation, which are after a wall of other "failed to fetch" messages look like this:

Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/x/xscreensaver/xscreensaver-data_5.15-2ubuntu1.1_armhf.deb  Temporary failure resolving 'ports.ubuntu.com'
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/x/xscreensaver/xscreensaver_5.15-2ubuntu1.1_armhf.deb  Temporary failure resolving 'ports.ubuntu.com'
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/libc/libcanberra/libcanberra-gtk3-module_0.28-3ubuntu3_armhf.deb  Temporary failure resolving 'ports.ubuntu.com'
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/universe/l/lm-sensors/lm-sensors_3.3.1-2ubuntu1_armhf.deb  Temporary failure resolving 'ports.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Any suggestions for how I might get things working?

**Comment by DennisLfromGA** [comment]
Try adding `-r trusty`, that will install the trusty release instead of the default precise, It's more up to date and has long term support, I think it'll be a lot better.

**Comment by ohnoplus** [comment]
Yep. That worked great. Thanks!

**Comment by DennisLfromGA** [comment]
Great! :+1:
