### ISSUE TITLE
Unable to run system I have restored restore from backup

### ISSUE THREAD

**Issue by ohnoplus** [dnschneid/crouton#2285]
I am trying to restore an old version of a crouton system I am running from backup. It is an encrypted system and I restored it with 
sudo edit-chroot -r -f /media/removable/restofpath/ogog-20150706-2225.tar
That seems to work, but when I run it I try to run it I get an error message

sudo enter-chroot -n ogog startxfce4
You must have a root password in Chromium OS to mount encrypted chroots.
Password: 
Verifying - Password: 
Enter encryption passphrase for ogog: 
Entering /mnt/stateful_partition/crouton/chroots/ogog...
chroot: failed to run command 'su': Exec format error
WARNING: starting chroot system dbus daemon failed with code 126
chroot: failed to run command 'su': Exec format error
Unmounting /mnt/stateful_partition/crouton/chroots/ogog...

Any ideas what is going on? Or is this backup just toast?
Thanks!

**Comment by DennisLfromGA** [comment]
@ohnoplus,
[ I've only experimented with 'chronos' / chroot passwords a few times in the distant past so hopefully what I'm suggesting below is still valid. ]  
Hopefully you remember what password you entered when you installed the chroot originally.
Encrypted chroots need to have a password set for 'chronos' before they encrypt the chroot.
In your case, if you know the encrypted password you set in the chroot, then you can set up the same password for chronos. In a crosh terminal enter: 

`sudo chromeos-setdevpasswd`

and enter the chroot's password, twice.

I think you will now be able to run your command: `sudo enter-chroot -n ogog startxfce4`
Or even better: `sudo startxfce4 -n ogog`

If you need/want to change your chroot's password, 'edit-chroot' has an option for that:
```
    -e          If the chroot is not encrypted, encrypt it.
                If it is encrypted, change the encryption passphrase.
```
-DennisL

**Comment by ohnoplus** [comment]
No luck, unfortunately. The password I am using then is the same as the one I am using now (I'm pretty sure), and resetting it with "sudo chromos-setdevpasswd" as you suggested doesn't seem to have any effect. If I just put in the wrong password for the decription part I get a "failed to decript" error instead of the one in my first post.

**Comment by DennisLfromGA** [comment]
@ohnoplus,

> ...resetting it with "sudo chromos-setdevpasswd" as you suggested doesn't seem to have any effect.

I guess you mean it doesn't have any effect on the outcome - even if the chronos password is the same as the chroot's encrypted password.

Can you change the chroot's encryption password using the '-e' option?
