### ISSUE TITLE
No input from keyboard when autocorrection is on

### ISSUE THREAD

**Issue by dadexix86** [dnschneid/crouton#2287]
Hi, I'm a new user so I do not know if this is a known issue.

I installed Trusty + Xfce on Asus C201.

When the autocorrect service is on in Chrome OS, the keyboard does not input anything in Xubuntu.
As soon as one disables it, everything goes back to normal.

Using `xev` one can see that the "normal" keys (alphanumerical characters) are not received by "X" in this case.

**Comment by Powerlink01** [comment]
Probably the same issue as: https://github.com/dnschneid/crouton/issues/2241

**Comment by dadexix86** [comment]
Yes, I just checked and it is exactly the same issue.
