### ISSUE TITLE
F1 continously pressed

### ISSUE THREAD

**Issue by dadexix86** [dnschneid/crouton#2290]
Hi all.
I am using Asus C201 + Crouton + Trusty + Xfce4 mainly to write and compile LaTeX.

My favourite editor is TeXStudio, whose "compile+view" keybinding is F1.

No problem, with Search+← one gets F1.

The problem is that this F1 doesn't stop.

With xev one can see it really easily, it is like F1 stays pressed.
To "unpress" it, it is enough to re-press it.

Unfortunately, in the meanwhile, one has launched like 100 compilations of the same TeX file, which is pretty annoying.

Is it a known issue? What else can I provide to debug the problem?

**Comment by drinkcat** [comment]
No idea. I hope this is not an issue anymore.
