### ISSUE TITLE
SD card encrypted

### ISSUE THREAD

**Issue by xorb0ss** [dnschneid/crouton#2291]
So I moved my chroots with edit-chroot to my SD card for extra space. It was encrypted.

I then shut the lid of my chromebook, and the SD became unmounted, and now will no longer remount. When I run `dmesg` it's unable to decrypt the SD card.

Not sure how to get back into it now.

**Comment by rprr** [comment]
Did you try it after a reboot?

**Comment by xorb0ss** [comment]
What's the default path for crouton to store encryption/decryption keys if -K wasn't specified during installation?

**Comment by rprr** [comment]
According to help page

-k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
