### ISSUE TITLE
crouton integration extension is unlisted on the Chrome Web Store

### ISSUE THREAD

**Issue by eligrey** [dnschneid/crouton#2292]
Having the extension unlisted makes it hard to find for people who just want to search "crouton integration" on the Chrome Web Store or Google. Please reconsider having this extension unlisted. I could understand hiding it from non-Chrome OS users but not from all users. I know you want people to read your readme to find the link, but not everyone is going to do this, and it's still an inconvenience for users who are already familiar with crouton that simply want to reinstall the extension after a quick Google search.

For reference, I do not see the extension at [https://chrome.google.com/webstore/search/crouton+integration](https://chrome.google.com/webstore/search/crouton%20integration?_category=extensions) ([screenshot](http://i.imgur.com/hHNMEfJ.png)), even when searching from my Chromebook.

Googling "crouton integration extension" also doesn't show the extension at all in any of the search results either, because keeping your extension unlisted means that Google won't index it. The closest thing to a link to your extension is six search results down, in a Google+ post by François Beaufort.

I don't understand why you would want it to be so difficult to discover your extension. If you don't want to make it listed I guess I will upload a second entry on the Chrome Web Store for this extension so users who would normally give up after a Google search will still be able to find it. Since I'm not the project maintainer for crouton, I'm probably going to lag behind in updates. For users who can't find your extension, having an outdated version will be better than nothing.

**Comment by cvmiller** [comment]
There is a pointer in the Crouton Docs on how to get the extension, but I agree, this threw me off the first time I was "looking" for the extension.

**Comment by dnschneid** [comment]
The issue I'm trying to avoid by de-listing it, is people installing the extension expecting it to install crouton, especially when they're in verified mode.  There are pointers in both the crouton docs and in the final output of the install (if it detects you don't have it installed), so most people seem to find it one way or another.

I searched for "crouton integration extension" on Google (in incognito mode), and every single result on the first page has a link to the extension.

I suggest bookmarking it if you find yourself installing it frequently (are you not syncing extensions?), or memorizing the "OVQOEt" goo.gl link.  I know I have fd3zc memorized :)

**Comment by A-Shadow-Shows** [comment]
Here is the website: https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom. Hope this helps

**Comment by DennisLfromGA** [comment]
@A-Shadow-Shows,

The crouton author actually posted the shortcut link [above](http://goo.gl/OVQOEt), which is easier & quicker to type.

*Hope this helps,*
-**DennisLfromGA**

**Comment by himylol** [comment]
Google just blocked it
