### ISSUE TITLE
Add backup functionality to the chromium integration extension to enable backups directly to network drives

### ISSUE THREAD

**Issue by eligrey** [dnschneid/crouton#2293]
My chroot is bigger than all of my USB drives, and if I did have a big enough USB drive I'd rather not wear down my NAND unnecessarily. I would like to be able to directly backup my chroots to my 6TB network drive. Yes, I can unplug my network storage from my router and plug it into my Chromebook over USB, but I enjoy the freedom of wireless too much to do this.

Chrome OS supports mounting samba shares in the Files app, but not directly in the filesystem, so I have an idea. The [Chrome Filesystem API](https://developer.chrome.com/apps/app_storage) allows manipulation of samba shares mounted in the Files app, so how about adding backup functionality to the crouton integration extension?

Since crosh can't directly communicate with the crouton integration extension, this might require a single-purpose "backup manager" chroot which creates the backup file, and then sends parts of it at a time over a websocket to the crouton integration extension, which could save the backup file directly to any mounted storage in the Files app.

This would also require adding a backup folder selection UI to the extension.

I realize that this would be an insane amount of work, so I don't really expect you to take on such a task. Mostly I just wanted to store my thoughts on GitHub of how such a thing could be done in case anyone is interested enough to tackle this in the future.

**Comment by divx118** [comment]
@eligrey You could use https://github.com/divx118/cifs those will work in chromeos, or setup a chroot with one of the following options https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc) Not really the solution you asked for, but it could helpyou out.

**Comment by eligrey** [comment]
Thanks, that really helps me!
