### ISSUE TITLE
Installing jessie with all valid targets for kde freezes acer C720p

### ISSUE THREAD

**Issue by davidthewatson** [dnschneid/crouton#2294]
I am running crouton like:

```
sudo sh crouton -r jessie -t kde-desktop,audio,core,x11,xorg,cli-extra
```

The last line I see in the terminal is "Please specify a username for the primary user".

At this point, the chrome desktop is frozen, all keyboard input is rejected, and the mouse pointer is gone along with control of the mouse from the touch pad. The only thing that works at this point is a long press of the power button.

I've repeated this crash multiple times. I tried to recall the targets from memory since I keep losing the history. Basically, all valid targets for jessie/kde except touch.

**Comment by divx118** [comment]
Probably the same issue as https://github.com/dnschneid/crouton/issues/1994
