### ISSUE TITLE
Gaming issue on Chromebook Pixel 2015

### ISSUE THREAD

**Issue by tobyfive1222** [dnschneid/crouton#2295]
Have anyone tried to play Company of Heroes 2 on Chromebook Pixel 2015? I bought it through steam but couldn't play. I could enter the game, but when I try to "press any key" and enter a match/mission, the game crashed. It went back to the desktop and closed the game. And Team Fortress 2 runs pretty smoothly. Is it because of the game itself or something I have to do on Pixel. Thanks.
For your information, I have xfce trusty installed. Does changing it to Ubuntu help with the gaming/graphic driver issue?

By the way, is there a way I can use usb peripherals in Virtualbox windows? I installed and did the setting about usb but the virtual machine just couldn't detect them (usb hard drives can be detected in linux).

**Comment by divx118** [comment]
For the virtualbox question there is this https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration
For the gaming question, sorry I wouldn't know. Gaming is not my thing.
