### ISSUE TITLE
packages have unmet dependencies: gcc-multilib, libc6-dev:i386

### ISSUE THREAD

**Issue by IL2** [dnschneid/crouton#2296]
In this trusty setup on Acer 720p

crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
architecture: amd64
xmethod: xiwi
targets: cli-extra,xfce,xiwi,extension
host: version 7520.63.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Dec 11 17:23:12 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

A problem arised which hinders crouton target update:
...skipped...
[trusty-update-error.txt](https://github.com/dnschneid/crouton/files/65884/trusty-update-error.txt)

2015-12-17 23:02:27 (126 KB/s) - '/tmp/crouton-cras.ZNiSNt/adhd.tar.gz' saved [466696]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version.
libasound2:i386 is already the newest version.
libspeexdsp1:i386 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version.
pkg-config is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gcc-multilib : Depends: gcc-4.8-multilib (>= 4.8.2-5~) but it is not going to be installed
 libc6-dev:i386 : Depends: libc6:i386 (= 2.19-0ubuntu6) but 2.19-0ubuntu6.6 is to be installed
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.

What possibly had gone wrong?

**Comment by IL2** [comment]
That's because of /etc/apt/sources.list contained only two entries:
deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse
after I inadvertently turned off in the Synaptic Package Manager trusty-security and trusty-updates.
With them enabled crouton have updated trusty target just fine.

**Comment by tomtobback** [comment]
i had the same issue upgrading from trusty to xenial and it wasn't because of sources.list
none of the apt-get install, remove and dpkg --purge --force-depends tricks worked, so i ended up installing aptitude to fix gcc-multilib; then the crouton update finally worked
