### ISSUE TITLE
xclip on Chromebook Pixel 2015 LS

### ISSUE THREAD

**Issue by whitneyit** [dnschneid/crouton#2298]
I've installed [extension](https://github.com/dnschneid/crouton/blob/master/targets/extension) target which has [`xclip`](https://github.com/dnschneid/crouton/blob/master/targets/extension#L22) in it but I can't get it to work via `enter-chroot`. The release that I have installed is `trusty`.

I keep getting the following error

> Error: Can't open display: (null)

And when I set a display

``` sh
$ export DISPLAY=:99
```

I get a similar error

> Error: Can't open display: :99

The code that I am trying to run is

``` sh
$ xclip -selection clipboard
```

Is there a work around for this?

**Comment by zwhitchcox** [comment]
Same problem!

**Comment by drinkcat** [comment]
xclip needs an X server. #2114.
