### ISSUE TITLE
Cursor graphic glitches out

### ISSUE THREAD

**Issue by wxv** [dnschneid/crouton#2299]
Normally, the cursor displays fine. After pressing ctrl-alt-shift-<= (or =>) to switch back to crosh and then back to Ubuntu, the cursor graphic glitches out. It becomes a distorted image repeated 4 times horizontally. It still functions perfectly. Typing anything into an Ubuntu textbox, like terminal, fixes the issue.
Using acer-c740

crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 7520.62.0 (Official Build) stable-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP Tue Dec 8 02:00:18 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by Sunappnio** [comment]
The easiest way is to press "esc" or any other key in chromeOS before you switch to chroot.
For some cpu series it's possible to install display drivers to fix, but that's dangerous.

**Comment by wxv** [comment]
I wonder if it's a problem crouton can solve or just inevitable

**Comment by dnschneid** [comment]
This has been fixed (a while ago)
