### ISSUE TITLE
Black screen after restart of chroot

### ISSUE THREAD

**Issue by STQZ** [dnschneid/crouton#2303]
Sorry if this happens to be a duplicate problem, I couldn't find the case that I'm having.

I've had to reinstall the chroot multiple times because after exiting re-entering the chroot would result in a black screen, and it would exit the chroot.

This is the result after the black screen:

```
crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome-desktop
host: version 7729.0.0 (Official Build) dev-channel enguarde 
kernel: Linux localhost 3.10.18 #1 SMP Thu Dec 10 21:16:00 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
```

There seems to be many problems with this exact error, but I believe I've found the cause, at least for my case. I restarted the chroot after each individual setting that I changed. I was unable to get back into the chroot after trying to change the clock from 24 hour time to AM/PM. As far as I know this is the case for targets: gnome and gnome-desktop.

It would also be appreciated if someone could provide a terminal command that would change the time back to 24 hour mode if possible in case this exact problem arises for anyone else, so that it would prevent reinstalling the chroot.

**Comment by tista500** [comment]
@STQZ,

Unfortunately I could not reproduce your issue on my machines, releases, and targets... :(
* ASUS C200MA
 * Release: Wily, Trusty
 * Targets: gnome, keyboard, xorg

* ASUS C100P
 * Release: Wily
 * Targets: gnome, keyboard, xorg, xiwi

The *clock-format* could not cause the black screen when I switched 12h/24h before logout:
`gsettings set org.gnome.desktop.interface clock-format '24h'` (24h format)
`gsettings set org.gnome.desktop.interface clock-format '12h'` (AM/PM format)

Regards.

**Comment by nortzt** [comment]
I think I have this same problem, and I think it is related to changing the clock settings.  I've been running a trusty/gnome chroot for a while now, and I have only had this problem recently.  Up until reading this post, I had no idea what was causing it, but each time this has happened to me, it was directly following a restart after changing the clock settings from 24 -hour to 12-hour.

**Comment by pointful** [comment]
I just had the same problem, although not sure what exact settings in gnome caused it -- I had been configuring things via both the gnome-control-center as well as gnome-tweak-tool. I was able to recover from it by starting up gnome-tweak-tool directly via xiwi and then having it reset everything to defaults. Now it starts up fine again. I'll tweak more carefully going forward. :)
