### ISSUE TITLE
Gnome won't run in xiwi

### ISSUE THREAD

**Issue by fraserYT** [dnschneid/crouton#2306]
The patchy hidpi settings for xfce was giving me eye-strain so I decided to try Gnome, since I seem to remember that it ran quite smoothly in xiwi when I tried it a few months back, unlike Unity. 

What I'm finding though is that it will launch fine in Xorg, but when I try to launch using -X xiwi, I get a black screen for a few seconds, then it crashes back out to ChromeOS.

The output I get is:

```
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost
```

Any ideas of anything I might be doing wrong?

**Comment by Snotes** [comment]
I have this problem running gnome in xiwi and xorg; i.e.:
sudo startgnome -X xorg
sudo startgnome -X xiwi
