### ISSUE TITLE
Memory Leakage in case of many switches between ChromeOS and Ubuntu

### ISSUE THREAD

**Issue by 1kastner** [dnschneid/crouton#2307]
First of all thanks for this great project, I highly appreciate your work!
For some jobs I need to switch back and forth between ChromeOS and Ubuntu. While this works very smoothly in the beginning, after a certain amount of times I can feel how the performance lowers. At some point it is so slow that I restart my chromebook and then everything is fine again. The performance loss is both when running Ubuntu and ChromeOS. While in the beginning just software is executed slower, in the end I can hardly move the mouse and JavaScript applications refuse to respond.
I guess for this issue you might need some log files, tell me which ones and I will attach them here.

**Comment by divx118** [comment]
I would first try to see with `top` what is using your resources when it is running slow.

**Comment by 1kastner** [comment]
Ok, I just had one such a case from which it could recover. That is by
the way not always the case, sometimes it seems to get stuck. After I
waited for 2min I normally assume it won't come back.

THis time, next to the normally running software it showed kswapd0. It
went up to 70%. Well, the only difficulty of course is that when it runs
low on ressources it is also difficult to run all those programs.

Anyhow, after I observed the 70%, some seconds later it could recover
and I could show this:

top - 09:58:51 up 20:07,  0 users,  load average: 3.79, 2.82, 2.11
Tasks: 245 total,   2 running, 242 sleeping,   0 stopped,   1 zombie
Cpu(s): 10.5%us,  9.1%sy,  0.0%ni, 73.8%id,  6.4%wa,  0.0%hi,  0.2%si,  0.0%
Mem:   1966832k total,  1931180k used,    35652k free,      564k buffers
Swap:  2881100k total,  2359796k used,   521304k free,   339352k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 6865 marvin    20   0 1072m  50m 5280 S   13  2.6  70:35.94 chrome
   27 root      20   0     0    0    0 S    7  0.0   4:26.31 kswapd0
23168 marvin    20   0  390m  13m 3324 S    3  0.7   7:50.06 Xorg
 1071 marvin    20   0  409m 4944 2852 S    2  0.3   0:04.48 xfce4-terminal
18922 marvin    20   0  455m  13m 1492 R    2  0.7  39:30.25 skype
23890 marvin    20   0 1716m 338m  10m S    2 17.6  22:42.04 firefox
23442 marvin    20   0 1300m  14m 3192 S    2  0.8   8:29.54 compiz
   54 root      20   0     0    0    0 S    1  0.0   1:29.94 mmcqd/0
 8258 marvin    20   0  675m  31m 7320 S    1  1.7   0:13.65 chrome
   52 root     -51   0     0    0    0 D    1  0.0   0:08.45 irq/51-ELAN0000
 7250 root      20   0     0    0    0 S    1  0.0   0:06.21 kworker/u4:20
15298 marvin    20   0 11252 1068  512 S    1  0.1   0:01.59 top
15868 marvin    20   0 17472 1068  596 R    1  0.1   0:00.19 top
25417 root      20   0     0    0    0 S    1  0.0   0:27.31 kworker/u4:2
  712 marvin    20   0 1081m  63m 9080 S    0  3.3  10:14.77 chrome
 1216 root      20   0  166m  244  216 S    0  0.0   0:16.09 esif_ufd
 5889 marvin    20   0  916m  34m 6876 S    0  1.8   0:25.95 chrome


For comparison, now, while I am writing the email, top shows the following:

top - 10:11:28 up 20:20,  0 users,  load average: 0.53, 2.06, 2.89
Tasks: 240 total,   1 running, 238 sleeping,   0 stopped,   1 zombie
Cpu(s): 11.8%us,  3.7%sy,  1.0%ni, 83.2%id,  0.3%wa,  0.0%hi,  0.0%si,  0.0%
Mem:   1966832k total,  1892172k used,    74660k free,     5328k buffers
Swap:  2881100k total,  1611604k used,  1269496k free,   354844k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 6865 marvin    20   0 1072m  40m 5304 S   16  2.1  72:00.69 chrome
 8258 marvin    20   0  682m  32m  10m S    6  1.7   0:46.24 chrome
 1120 marvin    20   0  376m  24m 6612 S    3  1.3   6:19.55 chrome
23890 marvin    20   0 1721m 410m  25m S    2 21.4  23:22.68 firefox
18922 marvin    20   0  455m  31m 9284 S    2  1.7  39:49.15 skype
  712 marvin    20   0  952m  63m  13m S    2  3.3  10:43.11 chrome
17797 marvin    20   0 17472 1568 1104 R    1  0.1   0:00.11 top
15298 marvin    20   0 11252 1008  524 S    1  0.1   0:10.15 top
10082 root      20   0     0    0    0 S    0  0.0   0:00.88 kworker/0:3
23168 marvin    20   0  372m  30m  14m S    0  1.6   8:12.43 Xorg
23471 marvin    20   0 20184  236  172 S    0  0.0   0:11.45 syndaemon
23608 marvin    20   0  849m 117m  21m S    0  6.1   1:34.38 thunderbird
23612 marvin    20   0  398m 4604 2716 S    0  0.2   0:02.19 unity-applicati
27004 marvin    20   0 1402m  29m 3596 S    0  1.6   2:19.29 soffice.bin
    1 root      20   0 11856  768  204 S    0  0.0   0:00.41 init
    2 root      20   0     0    0    0 S    0  0.0   0:00.99 kthreadd
    3 root      20   0     0    0    0 S    0  0.0   0:01.28 ksoftirqd/0

I hope you can read the numbers and the table is not totally distorted;
if it is so, tell me and I can format it.

**Comment by divx118** [comment]
It is readable. To me it seems you are running out of physical and swap memory. Especially compiz is using a lot. Maybe this is related https://bugs.launchpad.net/compiz/+bug/1315261 However not really a solution offered in that bug report. Maybe disabling the transition effects in windows will reduce it, or like I would prefer, switch to xfce or lxde especially on a 2Gb ram chromebook.

**Comment by 1kastner** [comment]
Thank you very much. I guess because everything is neatly set up I will just take care to close programs and tabs accordingly and restart it properly more often. In case it turns out more annoying I might change the desktop environment. Still my feeling continues that sometimes the working memory is not cleaned appropriately after closing some software. The problem occurs after I ran the laptop for a longer time and not always clearly related to my usage in the moment of slowing down.

**Comment by divx118** [comment]
@1kastner Yes, [compiz](http://www.compiz.org/) shouldn't use so much memory. It doesn't seem to clean up properly. You could backup your chroot, then add the xfce target to the original and try that. If you don't like it put your backup back.
