### ISSUE TITLE
Need help. I can not see ubuntu desktop.

### ISSUE THREAD

**Issue by WaKeMaTTa** [dnschneid/crouton#2308]
Hello everyone. 

I followed the instructions [The easy way](https://github.com/dnschneid/crouton#the-easy-way-assuming-you-want-an-ubuntu-lts-with-xfce), but after the step number 4 (`sudo startxfce4`) it opens a terminal and i can't access to ubuntu desktop (*see screenshot*).

Help pls.

![12431591_10207567538778352_558893535_n](https://cloud.githubusercontent.com/assets/3450257/11997516/455e123a-aa7e-11e5-99f6-414c6b11ff97.jpg)

**Comment by Sunappnio** [comment]
this console will appear when you press ctrl+alt+f2, and will disappear when you press ctrl+alt+f1
I think you have to provide more information, like more screenshots

**Comment by WaKeMaTTa** [comment]
My computer is French. Has french keyboard. But i used i only use `Ctrl+Alt+Arrow right` and `Ctrl+Alt+Arrow left`

![image](https://cloud.githubusercontent.com/assets/3450257/12003091/7cc8818a-ab12-11e5-8fb9-fbe47cc4dc85.png)

Which information do you want?

**Comment by Sunappnio** [comment]
Usually step number 3 takes some time(20min+ and based on your internet connection speed).
And when the installation ends, it will ask you to set a password, do you make it to that step?

**Comment by WaKeMaTTa** [comment]
When the terminal ask me the username and password for UNIX i put my name in username (wakematta) and password (1234) and i hit press enter.

**Comment by alicein1derland** [comment]
Wrong terminal. Reboot. Login. Open Chrome browser. New tab. 
Chrome-extension://pnhechapfaindjhompbnflcldabbghjo/html/crosh.html
At prompt.
crosh> shell
chronos@localhoast / $ sudo startxfce4
It will launch.
Bookmark the crosh shell terminal page to find it faster later.
Please post if this doesn't work. :)

**Comment by WaKeMaTTa** [comment]
@alicein1derland LOL, that was easy. Thank you very much. :+1:

**Comment by alicein1derland** [comment]
The chronos@localhoast is where you will type for update commands too.

**Comment by WaKeMaTTa** [comment]
@alicein1derland You mean `$ sudo apt-get update` or `$ croutonversion -u -d -c` :question:

**Comment by alicein1derland** [comment]
If you encrypted.
$ sudo sh -e ~/Downloads/crouton -n -u <chroot_name>

Normal.
$ sudo sh ~/Downloads/crouton -n -u <chroot_name>

This will update all. No need "sudo apt-get update"

For mine:
$ sudo sh -e ~/Downloads/crouton -n -u trusty


Switches -d -c I don't know.

**Comment by alicein1derland** [comment]
Oops! 
If you encrypted.
$ sudo sh -e ~/Downloads/crouton -n -u (croutonname)

Normal.
$ sudo sh ~/Downloads/crouton -n -u (croutonname)

**Comment by WaKeMaTTa** [comment]
Ok thanks :)

**Comment by DennisLfromGA** [comment]
> If you encrypted.
$ sudo sh -e ~/Downloads/crouton -n -u (croutonname)

> Normal.
$ sudo sh ~/Downloads/crouton -n -u (croutonname)

Guys, The syntax is just a little off.

To update an existing chroot use:

`sudo sh ~/Downloads/crouton -u [-n chrootname]`
Substituting 'chrootname' with your actual chrootname - and don't type the brackets [ ].

The '`sh -e ...`' part is *not* for encryption, it's used to exit when the script encounters an error.
However it's no longer necessary since it's now included in the scripts.
If you want to encrypt your chroot, the '-e' option is used after the .../crouton part.

**Comment by WaKeMaTTa** [comment]
Thanks for that explenation :+1:
