### ISSUE TITLE
Chromebook c201 - Fails to open any downloaded distros

### ISSUE THREAD

**Issue by Spodess** [dnschneid/crouton#2309]
Last night I was attempting to install ubuntu and it failed to do something with X server I think and I tried to install other distros after removing the ubuntu files and it just gives me the same result every time. I'm on the stable channel and on a side note when installing screenfetch in crosh will shell, when I tried to execute it, it said something like permission denied or something and I'm the only user and admin on here. All though screenfetch did kinda work after I typed "bash screenfetch" instead of "./screenfetch" but instead didn't recognize the OS and some other stuff. If it makes a big difference I'm using an ARM CPU.

**Comment by divx118** [comment]
Does this solve the issue? https://github.com/dnschneid/crouton/wiki/Asus-C201#x11-does-not-find-any-screensfbdev-not-found related issues https://github.com/dnschneid/crouton/issues/2249 and https://github.com/dnschneid/crouton/issues/2252

**Comment by Spodess** [comment]
@divx118 I'll go ahead and download the ubuntu stuff again from crouton and try this before I do sudo startunity, all though I tried to do it one time and after that sudo-enter chroot wouldnt work, so hopefully this works.

**Comment by divx118** [comment]
If you got any errors, then please copy/paste them from the command window  on pastebin.com, gist or something alike and post the link here.

**Comment by Spodess** [comment]
@divx118 alright will do, it's downloading/unpacking stuff now

**Comment by Spodess** [comment]
@divx118 LOL, IT WORKKSSSS. I can now switch between them thank you!!!! The first root command didnt work but the other two let me in ubuntu. Hopefully I dont have to run those scripts every time but thank you thank you thank you.

**Comment by Spodess** [comment]
@divx118 one thing that i need help with is getting wifi to work on this. network settings brings up something like not compatible.

**Comment by DennisLfromGA** [comment]
@Spodess - All the network settings are done on the Chrome OS side, you can't change or configure them in your chroot(s).

**Comment by Spodess** [comment]
@DennisLfromGA so is there any way to get wifi on ubuntu? there isnt really much options do anything like connecting.

**Comment by divx118** [comment]
@Spodess like @DennisLfromGA said, no need to do any networking stuff in the chroot. The connection is shared with chromeos and up and running. If you need to switch AP then switch to chromeos, connect your wifi to another AP and switch back to ubuntu again.

**Comment by Spodess** [comment]
Ok thank you all, getting some stuff working right now like ubuntu not installing packages correctly from term and stuff. Might have to do the little c201 commands every time but it should be good.
