### ISSUE TITLE
Difficulties with the packages xbindkeys & xautomation when trying to install to external HDD (ext4)

### ISSUE THREAD

**Issue by sean-shelton** [dnschneid/crouton#2310]
I typed in the following to try to install Unity onto my extermal hard drive:

```
sudo sh ~/Downloads/crouton -r trusty -t unity-desktop -p /media/removable/hardDriveName
```

However, I ran into the following error:

```
E: Unable to locate package xbindkeys
E: Unable to locate package xautomation
Failed to complete chroot setup.
Unmounting /media/removable/hardDriveName/chroots/trusty...
```

I've tried using -u to update the chroot, I've tried entering the chroot to install the packages myself, and I've tried simply starting unity again, but they all lead to the same error above.

I've tried looking for solutions to my problem, but I wasn't able to find any. I also don't know too much about Linux/crouton, so there may have been some things that I haven't tried yet. If there is a solution out there, please leave a link to it. 

Thank you.

**Comment by DennisLfromGA** [comment]
I found a similar issue on github here ([Issue 5](https://github.com/eyecreate/ubuntu-chromebook-installer/issues/5)) so you may need to modify your `/etc/apt/sources.list` file to append the 'universe' repo and then do `sudo apt-get update; sudo apt-get upgrade` to fix it.

**Comment by Tomstah** [comment]
Excuse me for not knowing anything about ChromeOS, or Crouton, which is the main reason in the first place I'm trying to use Crouton, but I do not understand what you mean... esp. since Sudo apt-get update is an invalid command.

Trying to install Unity (Trusty).

**Comment by maibaum** [comment]
I was able to fix this issue for the Zesty release by editing `/etc/apt/sources.list` located in your chroot's filesystem (using the base ChromeOS shell) and adding `deb http://archive.ubuntu.com/ubuntu zesty universe` on a new line at the bottom.
