### ISSUE TITLE
Missing Egl Support Error

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2311]
Hello I Am Fairly Familiar With Linux But There Is An Error I'm Getting When I Try Install Any Release. When I Tried To Download Debian Stretch With A Target Of Kde The Installation Runs And Then I Get An Error, And If I Try Updating It Gives The Same. The Error Is "unity target does not work in xephyr in trusty due to missing egl support." I Am Using A Samsung Chromebook With An ARMV7 Processor. (V71)

Please Respond ASAP.

Thanks Ahead Of Time

**Comment by Linux-Distros** [comment]
The Command I Run is _sudo sh ~/Downloads/crouton -r stretch -t kde -n debian_

**Comment by DennisLfromGA** [comment]
@Linux-Distros - Try Using The 'xiwi' Xmethod/Target:
- When Installing: `sudo sh ~/Downloads/crouton -r stretch -t xiwi,kde -n debian`
- After Installing: `sudo sh ~/Downloads/crouton -t xiwi -n debian -u`

**Comment by Linux-Distros** [comment]
ok ill try

**Comment by Linux-Distros** [comment]
ill get back to you when its done or whatever happens.

**Comment by Linux-Distros** [comment]
the download finished now im running the update...

**Comment by Linux-Distros** [comment]
it has worked, thanks for the help! :smile:

**Comment by Linux-Distros** [comment]
btw is there anyway to speed up the performance? its kinda of laggy

**Comment by DennisLfromGA** [comment]
Cool!
I'm sorry, I should have ben more clear about the instructions though.
You only needed to do the 'After Install ...' part if you already had it installed *without* the 'xiwi' target.
No harm done though...

**Comment by DennisLfromGA** [comment]
@Linux-Distros,

> btw is there anyway to speed up the performance? its kinda of laggy

Unfortunately no, that's the one drawbck with 'xiwi', there's no hardware acceleration - yet...

**Comment by Linux-Distros** [comment]
ok thanks
