### ISSUE TITLE
Twitter.com blocked in Acer C7 Crouton Wheezy Firefox

### ISSUE THREAD

**Issue by steptayl** [dnschneid/crouton#2313]
Why does Acer C7 / crouton / wheezy / Firefox / twitter.com site load, then show error dialog "Your account may not be allowed to perform this action. Please refresh the page and try again." then block any tweet, retweet, password change, etcetera? Refresh does not solve the problem.

The problem only occurs for Firefox within the crouton chroot on chromebook environment, (version 41.0.2 but previous versions also). The chromium browser or midori browser load twitter.com without similar error in this crouton wheezy. Firefox on other systems, desk or mobile, no problem.

Help or re-direction would be much appreciated / Thank you

The croutonversion output:

Entering /mnt/stateful_partition/crouton/chroots/wheezy...
crouton: version 1-20151104200003~master:2a1fc9da
release: wheezy architecture: amd64
xmethod: xorg targets: audio,chrome,cli-extra,core,extension,gtk-extra,keyboard,lxde,xorg,xiwi,x11
host: version 7520.63.0 (Official Build) stable-channel parrot kernel: Linux localhost 3.8.11 #1 SMP Fri Dec 11 17:05:19 PST 2015 x86_64 GNU/Linux
freon: yes
[on an Acer C7]

**Comment by Linux-Distros** [comment]
Are you able to upgrade to jessie? It might be a problem within the release your running or you can try using twidge if your only going to tweet.

Sincerely Linux.

**Comment by steptayl** [comment]
I can but the only "upgrade chroot release..." how-to I've found is for Ubuntu, "wiki/upgrade chroot release". How do I upgrade? /thanks

**Comment by Linux-Distros** [comment]
one sec let me launch my stretch and check

**Comment by Linux-Distros** [comment]
On Debian and most Debian-based distributions (including Ubuntu):

Refresh the package database: apt update, apt-get update or aptitude update

Install new packages: apt upgrade,  apt-get upgrade, or aptitude safe-upgrade.

apt(-get) upgrade only updates existing packages and is safer, while apt full-upgrade or apt-get dist-upgrade may install new dependencies or remove existing ones.

I Googled how to update debian with terminal

Idk If Its Helps But I Tried... :smile:

**Comment by Linux-Distros** [comment]
Right now im trying to download elementary os. but having troubles :frowning:

**Comment by steptayl** [comment]
I'm already doing that, finishing with apt-get dist-upgrade. I think it's by changing /etc/debian_version and/or /etc/apt/sources.list - then doing update/upgrade. I'll check Debian Reference later

**Comment by Linux-Distros** [comment]
ok

**Comment by Linux-Distros** [comment]
it would have to do with the sources.list thats the repos for all the apps you have like software-center

**Comment by steptayl** [comment]
Daily update/dist-upgrade already. But if crouton sources.list points to wheezy it stays wheezy IIRC. Not sure why upgrading would fix a bug when chromium, midori have no problem.

**Comment by divx118** [comment]
Yes, upgrading wouldn't normally fix this problem. I would look at the firefox version see if that is outdated. Maybe also clear cache in firefox...

**Comment by steptayl** [comment]
Crouton wheezy firefox version is 41.0.2 and cache clears on shutdown or 5 minutes idle. Debian stable firefox (iceweasel) version 38.5.0 has no block. Where are logs showing / comparing how a Twitter page loads in these browsers?

**Comment by steptayl** [comment]
LOL Tweetdeck.twitter.com is not blocked but plain old twitter.com is. On wheezy. So something in the javascript / page code  is blocked in twitter, not tweetdeck.

**Comment by steptayl** [comment]
Upgraded to debian/jessie, 8.3; the block continued. Found another possible answer by searching web: 
[open Firefox ]
1a) open about:config
1b) search for the string network.http.sendRefererHeader
1c) reset to default either by right-clicking -> reset or editing the value to 2
That fixed the block on a retweet and tweet. Thanks folks.
