### ISSUE TITLE
Crouton Question

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2316]
I Know This Isn't Technically An Issue But I Have A Question. Would There Be Any Way To Get Elementary Os On A Target? I've Read Many Ways To Do It But They Are Too Confusing. If Anyone Can Give Me An Easy Way Or A Guide I'd Greatly Appreciate It. Thanks In Advance

Sincerely Linux.

**Comment by DennisLfromGA** [comment]
@Linux-Distros - That question's been asked a couple of times before that I know of, so far, no one has taken on the task of creating the target. See https://github.com/dnschneid/crouton/issues/1571 and https://github.com/dnschneid/crouton/issues/1725.

**Comment by Linux-Distros** [comment]
Could You Give Me A Guide Because Im Running On Arm And Idk If It Is Supported. :P

**Comment by DennisLfromGA** [comment]
You can look at some existing targets, like [kde](https://github.com/dnschneid/crouton/blob/master/targets/kde), [lxde-desktop](https://github.com/dnschneid/crouton/blob/master/targets/lxde-desktop), etc. for some examples and guidance.

ARM is now supported, see https://github.com/dnschneid/crouton/issues/1571#issuecomment-91626698.

**Comment by Linux-Distros** [comment]
yes but i want to install via ppa and terminal but i keep getting no candidate errors on packages

**Comment by DennisLfromGA** [comment]
> yes but i want to install via ppa and terminal but i keep getting no candidate errors on packages

It's pretty hard to tell what's wrong (for me at least) with just that snippet.
You could look at these repos for clues and guidance possibly: 
- '[MyDearWatson](https://github.com/Alfriadox/MyDearWatson) by @Alfriadox' and 
- '[MyDearFreya](https://github.com/jeremy-breidenbach/MyDearFreya) by @jeremy-breidenbach'

And talk to some of the people in this 'reddit' discussion: 
- '[Any guides to getting the new Elementary / Freya release going ?](https://www.reddit.com/r/Crouton/comments/32akho/any_guides_to_getting_the_new_elementary_freya/)'

There is no ***'How to make your very own crouton target'*** wiki page ( *I looked* ;)
Perhaps one day someone will do a write-up - keep your fingers crossed...
