### ISSUE TITLE
Flip

### ISSUE THREAD

**Issue by Jackhford** [dnschneid/crouton#2318]
I'm experimenting with both the Asus Chromebook Flip and the Acer Chromeboook R11. Both are 2-in-1 360 degree rotatable devices. The former uses a Rockchip and the latter an Intel processor. My one complaint is that the onscreen keyboards popup on both devices popup whenever a text field appears on the display. I thought this would only happen when the devices were in tablet mode and not laptop mode, but that's not the case. Does anyone know how to control this? I happened again as I was typing this post.
Thanks

**Comment by DennisLfromGA** [comment]
@Jackhford - You might have more luck with this question on [Chromebook Central](https://productforums.google.com/forum/#!forum/chromebook-central).
