### ISSUE TITLE
Sd Card Issue

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2319]
I'm Familiar With Crouton And How You Can Specify A Path For The Chroot To Install To. But My Sd Card Isn't Working. I've Made It An Ext4 File System But Crouton doesnt read it.

Heres My Log
_chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t kde-_ _desktop,xorg,core,x11,audio,keyboard,extension -p /media/removable/sd-card_
_Password:_ Blah Blah
_/media/removable/sd-card/chroots/trusty is not an ext filesystem._
_chronos@localhost / $_

And If I try /dev/mmcblk1
it says
_/dev/mmcblk1 is not a valid prefix_

When Clearly In The Command _sudo fdisk -l | grep Disk_
It Says _Disk /dev/mmcblk1: 59.7 GiB, 64034439168 bytes, 125067264 sectors_
Which Is My Sd Card Which Is A
Samsung Evo 64 GB MicroSD Card
Im Using The Adapter To Use It Does That Matter?
     I Would Greatly Appreciate It If Someone Helped Me, Thanks! :smile:

**Comment by DennisLfromGA** [comment]
> And If I try /dev/mmcblk1
it says
/dev/mmcblk1 is not a valid prefix

I believe you need to specify the partition, like for instance: `/dev/mmcblk1p1` 

What do you get with: `sudo lsblk -f`

**Comment by Linux-Distros** [comment]
the partition thing doesnt work and i got 
NAME          FSTYPE LABEL      UUID                                 MOUNTPOINT
loop0                                                                
└─encstateful ext4              b84cefa4-5daa-433e-ae2b-02ed0a0a280a /mnt/stateful_partition/encrypted
zram0                                                                [SWAP]
mmcblk0rpmb                                                          
mmcblk0boot0                                                         
mmcblk0boot1                                                         
mmcblk0                                                              
├─mmcblk0p1   ext4              6fbb73ad-d952-4742-b13b-74bf631361ba /mnt/stateful_partition
├─mmcblk0p2                                                          
├─mmcblk0p3   ext4   ROOT-A                                          
├─mmcblk0p4                                                          
├─mmcblk0p5   ext4   ROOT-A                                          
│ └─vroot     ext4   ROOT-A                                          /
├─mmcblk0p6                                                          
├─mmcblk0p7                                                          
├─mmcblk0p8   ext4   OEM        449b3579-fca3-46cd-be92-8ad1b4e296b7 /usr/share/oem
├─mmcblk0p9                                                          
├─mmcblk0p10                                                         
├─mmcblk0p11                                                         
└─mmcblk0p12  vfat   EFI-SYSTEM 0453-D634                            
mmcblk1                                                              
└─mmcblk1p1

**Comment by DennisLfromGA** [comment]
@Linux-Distros,

Well, the output says it is indeed partition 1:   └─mmcblk1p1

But, it doesn't show an ext2/3/4 file system on it.
You may need to re-format it to ext4 then try the crouton command again.

**Comment by Linux-Distros** [comment]
should i still use gparted to do it? or something different

**Comment by DennisLfromGA** [comment]
You should be able to use `mkfs.ext4` in a crosh shell, something like:

`sudo mkfs.ext4 -L CROUTON /dev/mmcblkp1`

...but don't hold me to it... ;)

**Comment by Linux-Distros** [comment]
i did that and it gave a warning.
chronos@localhost / $ sudo mkfs.ext4 -L CROUTON /dev/mmcblk1p1
mke2fs 1.42.12 (29-Aug-2014)
/dev/mmcblk1p1 contains a ext4 file system labelled 'CroutonSD'
        last mounted on Mon Dec 28 18:03:42 2015

**Comment by DennisLfromGA** [comment]
You need to unmount it first but it looks like it is already ext4 so it *should* work as is.

**Comment by Linux-Distros** [comment]
ok thanks!

**Comment by Linux-Distros** [comment]
its still giving the issue where its a invalid prefix

**Comment by DennisLfromGA** [comment]
> Im Using The Adapter To Use It Does That Matter?

I think that's a distinct possibility.

**Comment by Linux-Distros** [comment]
its a microSd card idk if that helps
