### ISSUE TITLE
Problem with back button in the case of forms PHP

### ISSUE THREAD

**Issue by youch12** [dnschneid/crouton#2320]
I know that this question has been asked quite many times, but for some reason I couldn't find a clear answer, one that works sufficiently. I'm currently working on a project using mainly php (a newbie here), one of features of the site is allowing the user to comment on some articles. The problem is, I'm using the post method in these forms, once the user clicks add comment for example, another input is shown, if he decides to fill it out and click submit, the data is then transmitted to a page where I insert the new content in the DB, and bring him back to the original page, so he can repeat the process if he feels like it. However if the user decides to click the previous button, an error occures telling the user that the page requested doesn't exist anymore. I'm really lost here guys, I've tried many solutions, like putting the data in session but it doesn't seem to be working. I appreciate all the help I can get.

**Comment by divx118** [comment]
You are on the wrong issue tracker. This is for crouton on chromebooks. Please close this issue and search for the relevant issue tracker and post your question there. Thanks in advance :) .
#262

**Comment by youch12** [comment]
close #2320

**Comment by divx118** [comment]
Thanks
