### ISSUE TITLE
Crouton Error

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2323]
I had to recently switch out of dev mode because my account was glitching. Crouton worked before i switched it. I turned it off then back on, now my crouton wont download the latest debootstrap. i tried install kde with trusty and the debootstrap failed downloading. I tried other targets same issue. here the log.
_chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t kde,extension,keyboard,core_
_Downloading latest crouton installer..._
_######################################################################## _100.0%_
_Installing trusty-armhf chroot to /usr/local/chroots/trusty_
_Downloading latest debootstrap..._
_Download from Debian gitweb failed. Trying latest release..._
_2015-12-29 09:15:29 URL:http://debian.mirror.constant.com/debian/pool/main/d/debootstrap/ _[4070]_ -> "-" [1]_
_Downloading debootstrap version 1.0.75.tar.gz..._
_2015-12-29 09:15:30_ _URL:http://noodle.portalus.net/debian/pool/main/d/debootstrap/debootstrap_1.0.75.tar.gz_ _[61897/61897] -> "-" [1]_
Patching debootstrap...
Downloading bootstrap files...

**Comment by Rochey** [comment]
I've got the same issue. Started happening today and it was fine yesterday as I built a load of test chroots then. Here is my output.

sudo sh crouton -n stretch-i3 -r stretch -t x11
Downloading latest crouton installer...
######################################################################## 100.0%
Installing stretch-amd64 chroot to /usr/local/chroots/stretch-i3
Downloading latest debootstrap...
2015-12-29 17:23:38 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [63296] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
I: Retrieving Release 
W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/Release
W: http://httpredir.debian.org/debian/dists/stretch/Release was corrupt
E: Failed getting release file http://httpredir.debian.org/debian/dists/stretch/Release

**Comment by divx118** [comment]
Just be patient, most of these errors are related to temporary down time of the repos or a bad internet connection. Try again later and it should work.

**Comment by Linux-Distros** [comment]
ok thanks...
