### ISSUE TITLE
sudo startunity is not working

### ISSUE THREAD

**Issue by ZachBeckham** [dnschneid/crouton#2325]
Whenever I try to use the command sudo startunity, it fails.
Log text:
[  5646.464] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[  5646.466] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[  5646.466] X Protocol Version 11, Revision 0
[  5646.466] Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
[  5646.466] Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Dec 11 19:06:17 PST 2015 armv7l
[  5646.466] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9389c9eb-d493-1444-9fb9-20c423dd092d/PARTNROFF=1 hashtree=PARTUUID=9389c9eb-d493-1444-9fb9-20c423dd092d/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=1ddae0e334c6f5370ed76ff018d56b17ae1e602d salt=0ea3654ed084cebeb5d7c60bba61061e3a0f1f019cf47f42e67c32e24a50ae5f" noinitrd vt.global_cursor_default=0 kern_guid=9389c9eb-d493-1444-9fb9-20c423dd092d  
[  5646.466] Build Date: 05 November 2013  03:23:26PM
[  5646.466] xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
[  5646.467] Current version of pixman: 0.30.2
[  5646.467] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  5646.467] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  5646.467] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec 29 13:56:04 2015
[  5646.467] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  5646.468] (==) No Layout section.  Using the first Screen section.
[  5646.468] (==) No screen section available. Using defaults.
[  5646.468] (**) |-->Screen "Default Screen Section" (0)
[  5646.468] (**) |   |-->Monitor "<default monitor>"
[  5646.468] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[  5646.468] (==) Automatically adding devices
[  5646.468] (==) Automatically enabling devices
[  5646.468] (==) Automatically adding GPU devices
[  5646.469] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  5646.469] 	Entry deleted from font path.
[  5646.469] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  5646.469] 	Entry deleted from font path.
[  5646.469] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  5646.469] 	Entry deleted from font path.
[  5646.469] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  5646.469] 	Entry deleted from font path.
[  5646.469] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  5646.469] 	Entry deleted from font path.
[  5646.469] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  5646.469] 	Entry deleted from font path.
[  5646.469] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  5646.469] 	Entry deleted from font path.
[  5646.469] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	built-ins
[  5646.469] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  5646.469] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[  5646.469] (II) Loader magic: 0xb6f88e58
[  5646.469] (II) Module ABI versions:
[  5646.469] 	X.Org ANSI C Emulation: 0.4
[  5646.469] 	X.Org Video Driver: 13.0
[  5646.469] 	X.Org XInput driver : 18.0
[  5646.469] 	X.Org Server Extension : 7.0
[  5646.471] (II) config/udev: Adding drm device (/dev/dri/card1)
[  5646.471] setversion 1.4 failed
[  5646.472] Initializing built-in extension Generic Event Extension
[  5646.472] Initializing built-in extension SHAPE
[  5646.472] Initializing built-in extension MIT-SHM
[  5646.472] Initializing built-in extension XInputExtension
[  5646.472] Initializing built-in extension XTEST
[  5646.472] Initializing built-in extension BIG-REQUESTS
[  5646.472] Initializing built-in extension SYNC
[  5646.473] Initializing built-in extension XKEYBOARD
[  5646.473] Initializing built-in extension XC-MISC
[  5646.473] Initializing built-in extension SECURITY
[  5646.473] Initializing built-in extension XINERAMA
[  5646.473] Initializing built-in extension XFIXES
[  5646.473] Initializing built-in extension RENDER
[  5646.473] Initializing built-in extension RANDR
[  5646.473] Initializing built-in extension COMPOSITE
[  5646.473] Initializing built-in extension DAMAGE
[  5646.473] Initializing built-in extension MIT-SCREEN-SAVER
[  5646.473] Initializing built-in extension DOUBLE-BUFFER
[  5646.473] Initializing built-in extension RECORD
[  5646.473] Initializing built-in extension DPMS
[  5646.474] Initializing built-in extension X-Resource
[  5646.474] Initializing built-in extension XVideo
[  5646.474] Initializing built-in extension XVideo-MotionCompensation
[  5646.475] Initializing built-in extension XFree86-VidModeExtension
[  5646.475] Initializing built-in extension XFree86-DGA
[  5646.475] Initializing built-in extension XFree86-DRI
[  5646.475] Initializing built-in extension DRI2
[  5646.475] (II) LoadModule: "glx"
[  5646.477] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  5646.478] (II) Module glx: vendor="X.Org Foundation"
[  5646.478] 	compiled for 1.13.0, module version = 1.0.0
[  5646.478] 	ABI class: X.Org Server Extension, version 7.0
[  5646.478] (==) AIGLX enabled
[  5646.478] Loading extension GLX
[  5646.478] (==) Matched modesetting as autoconfigured driver 0
[  5646.478] (==) Matched fbdev as autoconfigured driver 1
[  5646.478] (==) Assigned the driver to the xf86ConfigLayout
[  5646.479] (II) LoadModule: "modesetting"
[  5646.479] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  5646.480] (II) Module modesetting: vendor="X.Org Foundation"
[  5646.480] 	compiled for 1.13.0, module version = 0.5.0
[  5646.480] 	Module class: X.Org Video Driver
[  5646.480] 	ABI class: X.Org Video Driver, version 13.0
[  5646.480] (II) LoadModule: "fbdev"
[  5646.487] (WW) Warning, couldn't open module fbdev
[  5646.487] (II) UnloadModule: "fbdev"
[  5646.487] (II) Unloading fbdev
[  5646.487] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  5646.487] (==) Matched modesetting as autoconfigured driver 0
[  5646.487] (==) Matched fbdev as autoconfigured driver 1
[  5646.487] (==) Assigned the driver to the xf86ConfigLayout
[  5646.487] (II) LoadModule: "modesetting"
[  5646.487] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  5646.488] (II) Module modesetting: vendor="X.Org Foundation"
[  5646.488] 	compiled for 1.13.0, module version = 0.5.0
[  5646.488] 	Module class: X.Org Video Driver
[  5646.488] 	ABI class: X.Org Video Driver, version 13.0
[  5646.488] (II) UnloadModule: "modesetting"
[  5646.488] (II) Unloading modesetting
[  5646.488] (II) Failed to load module "modesetting" (already loaded, -1211455272)
[  5646.488] (II) LoadModule: "fbdev"
[  5646.488] (WW) Warning, couldn't open module fbdev
[  5646.489] (II) UnloadModule: "fbdev"
[  5646.489] (II) Unloading fbdev
[  5646.489] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  5646.489] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  5646.489] (--) using VT number 7

[  5646.504] (WW) Falling back to old probe method for modesetting
[  5646.504] (II) modesetting(0): using default device
[  5646.504] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  5646.504] (II) modesetting(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[  5646.504] (==) modesetting(0): Depth 24, (--) framebuffer bpp 32
[  5646.505] (==) modesetting(0): RGB weight 888
[  5646.505] (==) modesetting(0): Default visual is TrueColor
[  5646.505] (II) modesetting(0): ShadowFB: preferred NO, enabled NO
[  5646.505] (EE) modesetting(0): KMS setup failed
[  5646.505] (II) UnloadModule: "modesetting"
[  5646.505] (EE) Screen(s) found, but none have a usable configuration.
[  5646.505] 
Fatal server error:
[  5646.505] no screens found
[  5646.505] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[  5646.505] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  5646.505] (EE) 
[  5646.516] Server terminated with error (1). Closing log file.

I also can enter chroot with CTRL + ALT + Forward. However, the username and password are incorrect.

**Comment by divx118** [comment]
CTRL + ALT + Forward brings up the chromeos dev console and has nothing to do with crouton. Also the switch keys for crouton are CTR-ALT-SHIFT Forward/Backward.
Did you try updating the chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting.

**Comment by ZachBeckham** [comment]
I tried updating it but it still returns with the same error.

**Comment by Linux-Distros** [comment]
its seem like a problem with the Module fbdev Have you tried reinstalling the whole thing and see if it gives the same error? If it does there might be a problem with a website for the script or your computer cant find it on the website its directed to.

**Comment by divx118** [comment]
@ZachBeckham Ok, can you please post croutonversion output? `sudo enter-chroot -n chrootname croutonversion` change chrootname to the name you have, probably `precise` So `sudo enter-chroot -n precise croutonversion`

BTW it is not fbdev.

**Comment by Linux-Distros** [comment]
div, could you help me im going to open an issue will you mind looking into it?

**Comment by ZachBeckham** [comment]
@divx118 
here is the output:
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: armhf
xmethod: xorg
targets: unity,unity-desktop
host: version 7520.63.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP Fri Dec 11 19:06:17 PST 2015 armv7l armv7l armv7l GNU/Linux
freon: yes

**Comment by divx118** [comment]
@ZachBeckham Thanks, Does this work for you https://github.com/dnschneid/crouton/wiki/Asus-C201#x11-does-not-find-any-screensfbdev-not-found

**Comment by ZachBeckham** [comment]
@divx118 Thank you so much. I probably should have specified that first. I am at Ubuntu desktop now.
