### ISSUE TITLE
Debian Issue

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2326]
Hello, Today I Recently Tried To Install Debian Using Crouton. But I Kept Running Into An Issue. Heres the command i used to install it.
_chronos@localhost / $ sudo sh ~/Downloads/crouton -r sid -t xfce,keyboard,core,x11,xorg,extension_
I Breifly Looked At The Install Log And There Was No Install Errors. But At The End It Spit Out A Issue.
Heres The Issue.
_sed: can't read /etc/X11/Xwrapper.config: No such file or directory_
_Failed to complete chroot setup._
_Unmounting /mnt/stateful_partition/crouton/chroots/sid..._

**Comment by divx118** [comment]
Yes, known issue see https://github.com/dnschneid/crouton/issues/2185 please close this one it is tracked there. Also please don't clutter other issues with personal comments Thanks :)

**Comment by Linux-Distros** [comment]
ok sorry..

**Comment by divx118** [comment]
no problem. If I have some time I will create a pull request to fix #2185 seems no one has done that yet.
