### ISSUE TITLE
How do you set the crouton channel?

### ISSUE THREAD

**Issue by kstenerud** [dnschneid/crouton#2328]
I've done google searches, github searches, and the crouton command line help, but nothing seems to actually tell you how to set the channel to beta or development.

**Comment by divx118** [comment]
If you mean beta or dev channels for chromeos http://www.omgchrome.com/how-to-change-channels-on-chromebook/
However I think you mean developer mode so you can install crouton. See https://github.com/dnschneid/crouton#prerequisites, read the Prerequisites and follow the link in there.

**Comment by kstenerud** [comment]
No, I meant the beta and dev channels. Didn't realize it's a chrome thing, not a crouton thing, which explains why searches turned up nothing.
