### ISSUE TITLE
Crouton extension not able to establish web sockets

### ISSUE THREAD

**Issue by Jzarecta** [dnschneid/crouton#2329]
The crouton extension has been failing on me trying to stablish a websocket connection and I am unable to get into X11. All this happened after the latest update of chromeos and I think it might have broken something with the extension. Anyone else experience this with more knowledge of the code might know a good workaround. 

Regards.

**Comment by divx118** [comment]
croutonversion output? Also did you try updating your chroot after the chromeos update? see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by zillz** [comment]
having similar issues.

here is the output from the extension:

19:30:41	Connection closed
19:30:36	Opening a web socket
19:30:31	Connection closed
19:30:27	Opening a web socket
19:30:21	Connection closed
19:30:17	Opening a web socket
19:30:12	Connection closed
19:30:08	Opening a web socket
19:30:03	Connection closed
19:30:00	Opening a web socket
19:29:55	Connection closed
19:29:51	Opening a web socket
19:29:46	Connection closed
19:29:43	Opening a web socket
19:29:38	Connection closed
19:29:35	Opening a web socket
19:29:30	Connection closed
19:29:25	Opening a web socket
19:29:20	Connection closed
19:29:16	Opening a web socket

This is before and after performing the update steps listed here: https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi
host: version 8172.47.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jun 1 19:55:19 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
