### ISSUE TITLE
Failed to complete chroot setup

### ISSUE THREAD

**Issue by plomas** [dnschneid/crouton#2333]
Got this error during installation:

/prepare.sh 704: /prepare.sh: ar: not found

**Comment by Linux-Distros** [comment]
Could you please paste the command your running and the output of _croutonversion_? Thanks

**Comment by koug** [comment]
Same issue here. Command is:  `sudo sh ~/Downloads/crouton -t xfce`

it fails this way:

    Installing target x11...
    Installing target gtk-extra...
    /prepare.sh: 704: /prepare.sh: ar: not found
    Failed to complete chroot setup.
    Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Same happens if `sudo sh ~/Downloads/crouton -t gtk-extra` is used.

Can't even enter chroot at this point. `sudo enter-chroot` gives the following:

    Entering /mnt/stateful_partition/crouton/chroots/precise...
    A chroot setup script still exists inside the chroot.
    The chroot may not be fully set up.
    Would you like to finish the setup? [Y/n/d] n
    Skipping setup. You will be prompted again next time.
    UID 1000 not found in precise
    Unmounting /mnt/stateful_partition/crouton/chroots/precise...

After deleting chroot and installing only `core`, `croutonversion` output is the following:

    crouton: version 1-20151231015955~master:cc3f601b
    release: precise
    architecture: amd64
    targets: core
    host: version 7520.63.0 (Official Build) stable-channel gnawty 
    kernel: Linux localhost 3.10.18 #1 SMP Fri Dec 11 19:13:56 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
     freon: yes

Thank you for the help
Nico

**Comment by Linux-Distros** [comment]
try updating your crouton and try again to update and post log.

**Comment by erfgypO** [comment]
have the same issue here. even after updating crouton :/

**Comment by Linux-Distros** [comment]
hmm im out of ideas have you tried reinstalling the chroot?

**Comment by erfgypO** [comment]
yes. a few times

**Comment by bristolred** [comment]
same problem here

**Comment by Darrendmj** [comment]
Same problem here:
/prepare.sh: 704: /prepare.sh: ar: not found

**Comment by hentoesch** [comment]
got also same problem.

**Comment by Linux-Distros** [comment]
idk im running xfce fine on a ARM processor precise

**Comment by Linux-Distros** [comment]
Are you able to delete the precise chroot and use trusty as a target?

**Comment by hentoesch** [comment]
tried it with -r trusty, precise. -t  unity, xfce -> always same error:
/prepare.sh: 704: /prepare.sh: ar: not found

**Comment by Linux-Distros** [comment]
it might be a problem with your end

**Comment by dnschneid** [comment]
I just reverted the latest release.  Please try again and see if things are working.

**Comment by Darrendmj** [comment]
Worked fine. Thanks.

**Comment by erfgypO** [comment]
worked fine for me too :+1: thanks and happy new year to u guys :)

**Comment by hentoesch** [comment]
worked great. thanks a lot.

**Comment by rplaughlin** [comment]
Working for me as well. Thanks dnschneid.

**Comment by divx118** [comment]
Sorry to all for any inconvenience it was my fault I made a stupid typo in a pull request. @dnschneid thanks for correctng it.

**Comment by koug** [comment]
No problem @divx118, it felt like it was a silly bug. Glad you guys figured it out quickly!

Thanks!

**Comment by TridentMustang** [comment]
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

? Guys im struggling with this think someone could help?

**Comment by Linux-Distros** [comment]
@TridentMustang Error Is Being Resolved #2387

**Comment by doogalbear** [comment]
First, I understand this is an old topic but it applies to me and I hope someone can help. I am also having this issue. I can no longer install Ubuntu, Kali or any other linux distro on my R11 I get the same error: 
```
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
```
Then the system tries to install packages, but when I get to the point where I can startxfce4 I can get in and here is where I have problems. I get 
```
E: Method http has died unexpectedly 
E: Sub process http recieved signal 4.
``` 
I have no idea why I am getting these errors and I hope someone can help.

**Comment by DennisLfromGA** [comment]
@doogalbear,

The crouton devs have marked this a priority issue so hopefully a fix will be in the pipes soon'ish.
It's being tracked here if you'd like to follow: https://github.com/dnschneid/crouton/issues/2688

*Hope this helps,*
-**DennisL**

**Comment by fox-lucas** [comment]
Hey can someone help me with this. I've powerwashed and tried the same thing atleast 15 times. `Installing CRAS...
/prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r sana -t xfce
WARNING: sana has reached upstream end-of-life.
That means there will be no package updates available.
You also have to specify a mirror to crouton (-m) for installation to proceed.
chronos@localhost / $ `

**Comment by DennisLfromGA** [comment]
@fox-lucas,

That issue is being tracked here:
- /prepare.sh cannot create as Directory is nonexistent #3930

A PR is in the works to fix it here:
- Find the correct alsa configuration directory #3955

*Hope this helps,*
-**DennisLfromGA**

**Comment by wangjianyuweg** [comment]
hello, when i try `sudo sh ~/Downloads/crouton -t xfce` (chromebook hp11)
`Installing target audio...
Fetching CRAS (branch 5f16bef2b57e4335c86b14355c57069ae2c1637e)...
--2019-02-22 19:29:48--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/5f16bef2b57e4335c86b14355c57069ae2c1637e.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 108.177.97.82, 2404:6800:4008:c00::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|108.177.97.82|:443... sudo sh ~/Downloads/crouton -t xfcefailed: Connection timed out.
Connecting to chromium.googlesource.com (chromium.googlesource.com)|2404:6800:4008:c00::52|:443... failed: Network is unreachable.
Error fetching CRAS
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`
how to solve it? please!

**Comment by DennisLfromGA** [comment]
@wangjianyuweg,

> Connection timed out. Connecting to chromium.googlesource.com (chromium.googlesource.com)|2404:6800:4008:c00::52|:443... failed: Network is unreachable.

A lot of times these are just transient network errors, you can wait and try again (and again) later and it will probably connect.

*Hope this helps,*
-**DennisLfromGA**
