### ISSUE TITLE
Chroot Moving Error

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2334]
Today I Used Gparted To Format My MicroSD Card To Ext4 But When I Try Moving My Chroot It Gives Me An Error. Here Is The Error.

>chronos@localhost / $ sudo edit-chroot trusty -m /dev/mmcblk1p1/
>Chroots can only be moved to ext filesystems.

**Comment by Linux-Distros** [comment]
I Tried /root/dev/mmcblk1p1 it worked but it gave me a error
>mkdir: cannot create directory ‘/root/dev’: Read-only file system
>Unable to create directory for /root/dev/mmcblk1p1

**Comment by DennisLfromGA** [comment]
This sounds like the same problem you were having in Issue https://github.com/dnschneid/crouton/issues/2319 - that you closed.

**Comment by Linux-Distros** [comment]
Yes but it says it that it can only be moved to ext filesystems while the other error was /dev/mmcblk1 is not a valid prefix.

**Comment by Linux-Distros** [comment]
I Want To Be Able To Move My Xfce4 Trusty Enviorment For Lots Of Space So i have the rest of the space for chromeos

**Comment by divx118** [comment]
@Linux-Distros You can't just write files to the /dev/mmblk1p1 partition. The partition should already be mounted by chromeos. To find that mount point do:
```
$ mount | grep /dev/mmcblk1p1
```
The output should be something in the "/var/host/media/removable/" path.

**Comment by DennisLfromGA** [comment]
> Yes but it says it that it can only be moved to ext filesystems while the other error was /dev/mmcblk1 is not a valid prefix.

Same problem I believe, *and* this is part of your initial post from the previous issue,
note the last line about 'an ext filesystem':

> Heres My Log
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t kde- desktop,xorg,core,x11,audio,keyboard,extension -p /media/removable/sd-card
Password: Blah Blah
/media/removable/sd-card/chroots/trusty is not an ext filesystem.

**Comment by Linux-Distros** [comment]
Is There Anyone To Get My Sd-Card To Hold My Chroot?

**Comment by DennisLfromGA** [comment]
We *have* tried to help you.
I think you need to review and apply the suggestions here and in Issue https://github.com/dnschneid/crouton/issues/2319

**Comment by Linux-Distros** [comment]
The Anyone Was A Typo I Meant To Say Anyway.

**Comment by DennisLfromGA** [comment]
@Linux-Distros - I didn't mean to drive you away and have you close the issue.

If you've tried all the suggestions and are still having a problem, then maybe give us some more specific details about what you are using, what commands you are issuing and what messages are displayed when it fails.

I may not be able to help you but there are other people here that possibly could.

**Comment by Linux-Distros** [comment]
ok should i start a new thread?

**Comment by Linux-Distros** [comment]
i started a new issue...
[#2337] https://github.com/dnschneid/crouton/issues/2337
