### ISSUE TITLE
Failed to complete chroot setup

### ISSUE THREAD

**Issue by ghuckins** [dnschneid/crouton#2336]
Hi,

I'm trying to install crouton onto my Chromebook (Toshiba Chromebook 2), which I have successfully done previously. However, I am now persistently getting the following error:

I: Base system installed successfully.
Pruning /mnt/stateful_partition/crouton/chroots/trusty mounts...
Creating hwaudio group with GID 18...
Changing audio GID from 29 to 220...
Changing cdrom GID from 24 to 19...
Creating devbroker-access group with GID 403...
Changing floppy GID from 25 to 11...
Creating i2c group with GID 404...
Creating input group with GID 222...
Creating serial group with GID 402...
Changing plugdev GID from 46 to 85...
Changing uucp GID from 10 to 14...
Changing video GID from 44 to 27...
Moving sudo GID from 27 to 28...
Installing target x11...
Installing target gtk-extra...
/prepare.sh: 704: /prepare.sh: ar: not found
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

I have tried powerwashing my Chromebook, but it did nothing. Any idea what might be going on?

**Comment by dnschneid** [comment]
See #2333. I reverted the latest release (so if you download crouton again it should work) and will be looking into the breakage.
