### ISSUE TITLE
Error With Moving Chroot To A MicroSD Card With Adapter

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2337]
I Am Trying To Move My Xfce Chroot To My Samsung 64GB EVO Class 10 Micro SDXC Memory Card with An Adapter. Ive Formatted My Card To Ext4 With Crosh. I Formatted It With The Command...

> sudo mkfs.ext4 -L sd-card /dev/mmcblk1

It Formatted But I Am Unable To Use It As A Destination For My Chroot. And If I Do

> sudo lsblk -f
> I Get 
> NAME          FSTYPE LABEL      UUID                                 MOUNTPOINT
> loop0  
> └─encstateful ext4              0f3bfae7-8ea0-4a6e-a59a-c6bae270ce4a /mnt/statef
> zram0                                                                [SWAP]
> mmcblk0rpmb  
> mmcblk0boot0  
> mmcblk0boot1  
> mmcblk0  
> ├─mmcblk0p1   ext4              20fe3360-95a3-4c79-98e9-c3d7960d0595 /mnt/statef
> ├─mmcblk0p2  
> ├─mmcblk0p3   ext4   ROOT-A  
> ├─mmcblk0p4  
> ├─mmcblk0p5   ext4   ROOT-A  
> ├─mmcblk0p6  
> ├─mmcblk0p7  
> ├─mmcblk0p8   ext4   OEM        449b3579-fca3-46cd-be92-8ad1b4e296b7 /usr/share/
> ├─mmcblk0p9  
> ├─mmcblk0p10  
> ├─mmcblk0p11  
> └─mmcblk0p12  vfat   EFI-SYSTEM 0453-D634  
> mmcblk1       ext4   sd-card    06378966-2909-4186-bd59-f81055eeca3e 
> └─mmcblk1p1  

Which It Clearly States That mmcblk1 the sd-card is ext4
But if i try to move the Chroot I Get An Error.

> chronos@localhost / $ sudo edit-chroot trusty -m /dev/mmcblk1p1
> Chroots can only be moved to ext filesystems.

But The File System Is Ext4. If I Use The directory /media/removable/sd-card it gives the same error heres the output of my enviorment.

**Comment by Linux-Distros** [comment]
Continued From Original Message.

>chronos@localhost / $ sudo edit-chroot trusty -l
>name: trusty
>encrypted: no
>Entering /mnt/stateful_partition/crouton/chroots/trusty...
>crouton: version 1-20151104200003~master:2a1fc9da
>release: trusty
>architecture: armhf
>xmethod: xorg
>targets: xfce,xorg,x11,core,audio,extension,keyboard
>host: version 7520.63.0 (Official Build) stable-channel daisy 
>kernel: Linux localhost 3.8.11 #1 SMP Fri Dec 11 17:09:50 PST 2015 armv7l armv7l armv7l >GNU/Linux
>freon: yes
>Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

If You Could Help Me Resolve This Message I'd Appreciate It! Thanks.

Linux-Distros

**Comment by DennisLfromGA** [comment]
> sudo mkfs.ext4 -L sd-card /dev/mmcblk1

`/dev/mmcblk1` is the *disk* - you need to format the *partition*:

`sudo mkfs.ext4 -L sd-card /dev/mmcblk1p1`

----
> chronos@localhost / $ sudo edit-chroot trusty -m /dev/mmcblk1p1

You can't use the raw device, like @divx118 mentioned earlier, you need to find where it's mounted.
Once partition 1 is formatted per above, it most likely will be at `/media/removable/sd-card`

**Comment by Linux-Distros** [comment]
Thanks Ill Try That.

**Comment by Linux-Distros** [comment]
I tried formating and it gave me
>read_bad_blocks_file: No such file or directory while trying to open sd-card

**Comment by DennisLfromGA** [comment]
Was that the message you received after entering: `sudo mkfs.ext4 -L sd-card /dev/mmcblk1p1` ?

The partition cannot be mounted when formatting it, please tell us *exactly* what steps / commands you used and the messages displayed.

**Comment by Linux-Distros** [comment]
Fixed It Accidently used lower case l instead of capital.

**Comment by Linux-Distros** [comment]
But if i try do format p1 it gives
>chronos@localhost / $ sudo mkfs.ext4 -L sd-card /dev/mmcblk1p1
>mke2fs 1.42.12 (29-Aug-2014)
>The file /dev/mmcblk1p1 does not exist and no size was specified.

**Comment by Linux-Distros** [comment]
Why Cannot I Format mmcblk1p1 but only mmcblk1?

**Comment by Linux-Distros** [comment]
nvm got it copying thanks for helping me! :smile:

**Comment by Linux-Distros** [comment]
how do i start my chroot its finished copying please help. thanks!

**Comment by tedm** [comment]
curious if crouton users using usb or sd cards long term, are having reliability issues? I ran arch linux for 3 years on usb flash, and gave up after it became hit or miss with the media, with heavy read/writes (e.g. samba server, etc. use).

**Comment by Linux-Distros** [comment]
i tried many solutions to launch it but none work i need help launching my enviorment from the sd card

**Comment by DennisLfromGA** [comment]
@Linux-Distros - Use crouton's '`-p`' option.
This is all covered in the [README](https://github.com/dnschneid/crouton/blob/master/README.md#i-want-to-install-the-chroot-to-another-location).
