### ISSUE TITLE
"sudo startunity" won't work on my chromebook... HELP!

### ISSUE THREAD

**Issue by SketchyGuy** [dnschneid/crouton#2338]
So i watched a video on how to get linux on my chromebook ( https://www.youtube.com/watch?v=7KGcd9sSQok )[<--- Video Link] ... Followed every step and then got to the download part of it and downloaded it from crouton off of the croot. Now whenever i type sudo startunity, this is the message i get (down below). All I want is to be able to play steam games on my chromebook. My chromebook is a Hisense.

((((What is said after typing sudo startunity))))

Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Fri Dec 11 19:07:06 PST 2015 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=5a81f4b4-5a68-774b-8249-89de158e3d0f/PARTNROFF=1 hashtree=PARTUUID=5a81f4b4-5a68-774b-8249-89de158e3d0f/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=07ca6e24dbb1ef26fe0759ad4ded3691d5ef1c41 salt=8cb94e00521bcfed5928edd85944e29b85c0b62d859f580c27c2f915e804734c" noinitrd vt.global_cursor_default=0 kern_guid=5a81f4b4-5a68-774b-8249-89de158e3d0f  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Dec 31 18:51:43 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
^C/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: unexpected signal 2
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by Linux-Distros** [comment]
Try Reinstalling crouton to see if you have the latest version and post the outcome of
>sudo sh ~/Downloads/crouton -V

**Comment by SketchyGuy** [comment]
@Linux-Distros Can you send me a link to the latest version?? And should i remove all of my linux and crouton downloads?

**Comment by Linux-Distros** [comment]
heres the link https://goo.gl/fd3zc you could try that and see if it work then

**Comment by DennisLfromGA** [comment]
@SketchyGuy - Steam won't run on ARM processors.
