### ISSUE TITLE
enters linux then freezes

### ISSUE THREAD

**Issue by teeeejo** [dnschneid/crouton#2341]
I recently upgraded ubuntu 14.04 to 15.04 "successfully". All was working fine till i restarted the system and now when I enter linux everything freezes and I can see my desktop background but nothing else. When i try to switch back to chrome OS all I see is a black screen. 

Please help!

**Comment by tista500** [comment]
@teeeejo,

Now I'm afraid that you would run Unity7 Desktop on your Vivid. Please see details in #2144.
Unity7 on Vivid/Wily didn't work properly out of the box so, you'd better to switch to another WM/DE. For example, XFCE and GNOME will work as you expected.

Regards.

**Comment by teeeejo** [comment]
Thanks for the useful information. :+1:
