### ISSUE TITLE
Lid action separate for AC/Bat

### ISSUE THREAD

**Issue by mr-wong** [dnschneid/crouton#2342]
Hi. I've configured powerd via /var/lib/power_manager file variables, but don't know how to make different lid actions for AC and Bat. What I'd prefer:
Battery lid close: instant suspend with timeout, say 10 seconds if I changed my mind after close.
AC lid close: any timeout, including 'never suspend'.

Maybe via udev rules? I've already made governor switch and cores shutdown on udev power state events.

**Comment by drinkcat** [comment]
See #2202, not sure.
