### ISSUE TITLE
Unity Updating Error.

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2345]
I Want To Update My Unity Chroot From 12.04 To 14.04 And Run Gnome-Shell On It. But Whenever I Try To Update To It Fails Updating At First It Gives An Error Where InitScripts Cant Be Downloaded And It Continues Then It Stops From To Many Errors It Says And When It Finishes The Dash Home Logo Is Blank And Then When I Restart It Wont Launch What Am I Doing Wrong Thanks!

Please Respond ASAP

**Comment by Linux-Distros** [comment]
Also If I Trying Using Trusty Release I Get A Missing EGL Support Error After It Starts Preparing Chroot Enviorment

**Comment by DennisLfromGA** [comment]
Let's see what you've installed; what's the output of:

`sudo edit-chroot -al`

For guidance in general, check out the wiki page: [Upgrade chroot release](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release)

**Comment by Linux-Distros** [comment]
this is the error i got.

>chronos@localhost / $ sudo edit-chroot -al
>name: trusty
>encrypted: no
>Entering /mnt/stateful_partition/crouton/chroots/trusty...
>chroot: failed to run command '/usr/local/bin/croutonversion': No such file or directory

**Comment by DennisLfromGA** [comment]
> When I Restart It Wont Launch What Am I Doing Wrong Thanks!

Judging by the result of `croutonversion`, your update attempt(s) may have broken your chroot.

Can you get into your chroot shell using:

`sudo enter-chroot -n trusty`

**Comment by DennisLfromGA** [comment]
Wait a minute, are you working on two different chroots 'precise' and 'trusty' ?
If so, let's work on the original problem with 'precise' before we get to the problem with 'trusty'.

For the problem with 'trusty', you can join in on a couple of other issues already open.

**Comment by Linux-Distros** [comment]
for some reason my unity chroot got deleted so im going to retry it. idk what happened :I

**Comment by DennisLfromGA** [comment]
A 'unity' chroot ???

*I think it'd be a very good idea to close this issue.*

Once you straighten out things on your end, you can try again.

If you run into trouble later, then come back.

**Comment by Linux-Distros** [comment]
i meant my precise chroot with the target of unity.

**Comment by DennisLfromGA** [comment]
Whew!!!!
