### ISSUE TITLE
Audio doesn't work when running Kodi on a chroot

### ISSUE THREAD

**Issue by kourtni-zz** [dnschneid/crouton#2349]
Hi,
I've previously installed Kodi on a chroot with an xcfe target and just recently with an xmbc target, and both times the audio was not being routed anywhere (speakers, headphones, etc).

The current information returned from chrootversion is:
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xbmc
host: version 7520.63.0 (Official Build) stable-channel lumpy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Dec 11 19:12:55 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

It should be very easy to test this. Here are the exact steps I took.
1. Created chroot with `sudo sh ~/Downloads/crouton -t xbmc`
2. Entered chroot with `sudo enter-chroot`
3. Installed tools required for add-apt-repository with `sudo apt-get install software-properties-common python-software-properties`
4. Added apt repo for Kodi with `sudo add-apt-repository ppa:team-xbmc/ppa`
5. Ran `sudo apt-get update`
6. Ran `sudo apt-get install kodi`
7. Ran `sudo apt-get remove xbmc`
8. exited the chroot with `exit`
9. entered the the chroot with `sudo startxmbc`

There is no sound. If you navigate to `System -> Settings -> System -> Audio Output` the selection for `Audio output device` will be empty. Clicking on the selection area brings up a menu with the empty option and "Chromium OS Audio Server". Selecting `Chrome OS Audio Server` and exiting the menus does not resolve the issue, as there is still no audio output.

**Comment by kourtni** [comment]
It should be noted that when I installed Kodi on the chroot with the xcfe target, audio did worked from the web browser fine, but from within Kodi there was no sound.

**Comment by thetwoflower** [comment]
This works best for me compared to xbmc chroot.
Depends if you want to save space or not as Xfce could us a lot.

Hi I've installed crouton to get Kodi a few times. The best way so far is to install -
sudo sh ~/Downloads/crouton -r trusty -t xfce,xiwi
I have always hated not being able to copy and paste into linux from chrome so this sorts that.
https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom you'll need this extension.
Now you can expand and move around windows easier.
This means you just then install Kodi from terminal

sudo apt-get install python-software-properties pkg-config
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi

Then also install PVR addons
http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux.

Whatever you use Kodi for will work with a bit of trial and error. There are more PVR addons on unofficial websites.

Then just Back up your Kodi Build alot!!!

**Comment by kourtni** [comment]
Hi and thanks... That actually worked!

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 5, 2016 at 4:26 AM, thetwoflower<notifications@github.com> wrote:   
This works best for me compared to xbmc chroot.
Depends if you want to save space or not as Xfce could us a lot.

Hi I've installed crouton to get Kodi a few times. The best way so far is to install -
sudo sh ~/Downloads/crouton -r trusty -t xfce,xiwi
I have always hated not being able to copy and paste into linux from chrome so this sorts that.
https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom you'll need this extension.
Now you can expand and move around windows easier.
This means you just then install Kodi from terminal

sudo apt-get install python-software-properties pkg-config
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi

Then also install PVR addons
http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux.

Whatever you use Kodi for will work with a bit of trial and error. There are more PVR addons on unofficial websites.

Then just Back up your Kodi Build alot!!!

**Comment by thetwoflower** [comment]
No problem any issues message me back!

Date: Wed, 6 Jan 2016 01:38:26 -0800

**Comment by tnevs23** [comment]
I followed your steps exactly. It didnt work, still no audio. i tried it with xiwi as well and its telling me there is already info in the xcfe file. how does that extension work by the way? still trying to learn all this scripting mumbo jumbo and the extension is incomprehensible to me. are PVR add-ons necessary to making the audio work on kodi for chroot? also linux does not let me copy and paste into terminal...bummer. but i dont see how the pvr addons relate to this issue. Please help!

**Comment by thetwoflower** [comment]
Hmmm.... ok have a look in sound settings and try and use pulse audio. If I have an issue I just start again. https://gist.github.com/gszauer/6842950
[https://avatars0.githubusercontent.com/u/1061030?v=3&s=400]<https://gist.github.com/gszauer/6842950>

Chromebook<https://gist.github.com/gszauer/6842950>
gist.github.com
property=

×


Have a look here as well may be some answers...Copy and paste using shift and control and v/c. Yeah no I realised PVR addons are no essential for kodi.
Message back with an update of the problem and i'll see what i can do or alternatives i can suggest...

________________________________
