### ISSUE TITLE
VPN Issue with AnyConnect

### ISSUE THREAD

**Issue by croiad** [dnschneid/crouton#235]
Hoping someone can give me some direction here.  My company uses AnyConnect with the Cisco Trojan (CSD) which has stopped me from being able to get OpenConnect to work correctly so I have resorted to the Cisco AnyConnect App.  

The App works perfectly the first time I launch it.  It connects to my work network and I have no issues.  After I disconnect I cannot ever reconnect.  I receive the error "The VPN client driver encountered an error".  This appears to be a common error with the Windows client but I cannot find anyone who has experienced it under Linux.  

Even if I uninstall/reinstall the app, as well as delete every Cisco/AnyConnect folder I can find, it will give me the same error.  The only solution I have found is to completely reinstall my chroot (not really a solution).  After the reinstall it will work once again.  

I believe it is creating a file, or modifying a file somewhere, but I cannot find it.  Anyone have any suggestions?

I am currently running Raring.

Thanks

6/24 EDIT:  After more testing it acts as if it does not have control over the network interface device.  If I attempt to reconnect 5-10 times after it fails I will be able connect again.  This leads me to believe that it is not a file that is being changed after install as I originally thought, but is a permission or access problem to a kernel component.  

6/25 EDIT:  I have come to the conclusion that I think my chroot and chromeos are battling for control of network devices.  it is the only thing that I can find that could be causing the inconsistency that I am seeing.  Sometimes it will connect fine, other times not.  I have noticed the same behavior with the audio hardware within KDE(pulse).  I am getting close to just dual booting so that it will work every time but haven't given up quite yet.  

One plus is that when the chroot has control over the network device it never disconnects.  All I need is a way to focus control to the chroot long enough to make the connection, then I would not have to worry about it.  I have tried to restart the networking daemons from within the chroot thinking that might do it, but I cannot seem to get that to work.

Any Ideas from anyone?

**Comment by fleminra** [comment]
You can also use this inside your chroot to create the TUN device:
`/sbin/ip tuntap add dev tun0 mode tun`
... so as to eliminate the dependency on OpenVPN.

This is just to show that there's nothing magical going on in the OpenVPN code, and maybe gives hope to the possibility that openconnect could simply be modified to take care of the TUN device itself.

In any case, `openvpn --mktun ...` is working for me inside the chroot (openvpn package version 2.3.2-9ppa1~precise), so there's no need to use the openvpn binary provided by Chrome OS.

FWIW, OpenVPN tunneling also also seems to have this problem under ChromeOS+crouton -- it doesn't work unless you create a TUN device for it in advance, before trying to establish the OpenVPN tunnel.

Can anyone confirm all this? If so, I reckon the wiki should be updated.

**Comment by zhengwy888** [comment]
recently `openvpn --mktun` stopped working for me. the tun device does not persist for more than 10 sec even though I do have the persistent flag set. any advice on where I should look for where the problem is? I tried both jessie (debian) and trusty (ubuntu) distribution but the results are the same. 

```
(liftoff)ezheng@localhost:~$ sudo /sbin/ip tuntap add dev tun1 mode tun
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
tun1: ERROR while getting interface flags: No such device
(liftoff)ezheng@localhost:~$ 
(liftoff)ezheng@localhost:~$ sudo ifconfig tun1 up
tun1: ERROR while getting interface flags: No such device
```

**Comment by fleminra** [comment]
Do this in a shell in Chrome OS:

```
sudo stop shill
sudo start shill BLACKLISTED_DEVICES=tun1
```

Then the VPN client inside crouton should be able to use tun1 without interference from Chrome OS.

**Comment by zhengwy888** [comment]
Thanks! great solution! but I ended up used this app from wiki and all
problem seems to go away.

https://chrome.google.com/webstore/detail/cisco-anyconnect/jacdijibdjifphcecdielmekkmfdpgee



Edward Weiyi Zheng
