### ISSUE TITLE
Wifi disconnect on wake from sleep?

### ISSUE THREAD

**Issue by free-variation** [dnschneid/crouton#2350]
Intermittently my HP chromebook 14 (2015 model -- celeron n2940) will not reconnect to wifi networks on wake from sleep and must be rebooted.  I've filed a [fairly detailed bug](https://code.google.com/p/chromium/issues/detail?id=572592) with the Chromium people, who think this may be a hardware-related PCIe problem.  But I have this nagging worry that this happens only when I'm in a crouton chroot.  Of course I'm often in a chroot -- not always -- so the correlation might be spurious. 

Has anyone else observed this?  Is there any reason that crouton could mess with the hardware on wake from sleep?

**Comment by tista500** [comment]
@free-variation,

I'm not sure whether it related to the kernel-space driver of wifi chip or not, at least as of my ASUS C200 (BayTrail-M, AC7260), sometimes wireless networking was failed on resume after updating ChromeOS system/kernel...

In my case, the 'iwlwifi' module might have an issue of power-saving feature in some kernel release cycles, so I had to disable power-saving feature in that time from chroot:
`iw dev wlan0 set power_save off`

This command might be able to avoid the power cut in suspend/resume cycles of ChromeOS... But surely this causes bad power-consumption at idle as side effect.

Regards.
