### ISSUE TITLE
Is it possible to run GUI programs with cli-extra?

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2351]
Is it possible to open programs such as gedit without a desktop installed? I'm using `cli-extra`. When I run `sudo gedit` I get the message "Cannot open display:". Also, the `gksudo` command doesn't seem to be found.

**Comment by divx118** [comment]
@henrywright No, you will need at least x11 target be it using xiwi or xorg, so you can have a display. I think for you it will be best and easiest to use xiwi. You can add it to your current chroot when you update it with `-t xiwi`. Then you are able to launch gedit in a chromeos window with `sudo startxiwi gedit`

**Comment by henrywright** [comment]
Thanks for this info, @divx118
