### ISSUE TITLE
Crouton Host Commands Not Re-Installed

### ISSUE THREAD

**Issue by rumpaar1** [dnschneid/crouton#2352]
After having the Crouton host commands (enter-chroot, edit-chroot etc.) installed, and running a dev_install --uninstall which deletes /usr/local (where crouton commands are kept), creating another chroot does not reinstall the commands.

**Comment by DennisLfromGA** [comment]
'crouton's '-b' option was created just for these situations:
```
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
```

**Comment by rumpaar1** [comment]
Thanks. Missed that option. Still, the chroot install said it was putting those commands in but they weren't there, so that might be something to check out.

**Comment by DennisLfromGA** [comment]
Yes, that does sound unusual, normally they are installed along with the chroot.

That '`dev_install`' command bit me once or twice too - had to reinstall all my `/usr/local/*` stuff, not fun...
