### ISSUE TITLE
How to share the clipboard between Chrome OS and a chroot

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2353]
I've already created a chroot and was wondering if clipboard sharing between the chroot and Chrome OS is possible? When I list all targets, I see this:

```
extension
        Clipboard synchronization and URL handling with Chromium OS.
        Requires: x11
```

Would this be the recommended approach to get a shared clipboard?

`sudo sh ~/Downloads/crouton -u -t extension -n chrootname`

I couldn't see any info on clipboard sharing in the Wiki. Thanks in advance.

**Comment by divx118** [comment]
@henrywright Yes correct, you will then also need to install the chromeos extension from the webstore. It will be mentioned with the link when you complete the update.

**Comment by henrywright** [comment]
Thanks for the info @divx118

**Comment by zwhitchcox** [comment]
I just tried this, and it didn't work...I'm on the new chromebook pixel...I installed the target extension, I installed it on my computer, and I tried to update it like shown in this script, and it still doesn't work....any idea what I'm doing wrong?

**Comment by zwhitchcox** [comment]
Ok, actually, it does work on the gui, but in vim, when I try to pull from the "*" register, there's nothing there

**Comment by zwhitchcox** [comment]
Also, when I try to use xclip, i get `Error: Can't open display: :0`

**Comment by japrogramer** [comment]
also having this issue, I would like to do "+y from normal mode in vim but I get an error
clipboard: No provider. Try ":CheckHealth" or ":h clipboard".
