### ISSUE TITLE
No wifi icon in the top of my screen? (HELP)

### ISSUE THREAD

**Issue by FroZoneTechnology** [dnschneid/crouton#2354]
I recently installed Ubuntu on my Dell 11 chromebook... I am running 14.04 LTS on Ubuntu. My issue is, I tried to install CyberGhost 5 while using wine (windows application packager).. Here is what happens when I try to install: http://i.imgur.com/j32zqgl.png

Please help me solve this issue!

**Comment by CoolOppo** [comment]
ur gay

**Comment by CoolOppo** [comment]
not safe for work
![](http://i.imgur.com/s50IGaZ.gif)
