### ISSUE TITLE
Unable to locate package kde-plasma-desktop

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2356]
Hey guys,

Chroot setup fails to complete when running `sudo sh ~/Downloads/crouton -r wily -t kde -n kde`

Error dump:

```
E: Unable to locate package kde-plasma-desktop
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kde
Unmounting /mnt/stateful_partition/crouton/chroots/kde...
```

**Comment by DennisLfromGA** [comment]
Looks like the 'wily' release is having the same issue as 'vivid'.
Take a look at Issue https://github.com/dnschneid/crouton/issues/2260, there's a pull request to fix that issue that will also take care of 'wily' and anything newer. See PR https://github.com/imakiro/crouton/commit/206d8dc6fd0c1b45ea8cbad29c090922f46650b6.

**Comment by henrywright** [comment]
Thanks for the link. I realise wily isn't a supported release, but has a suspicion it wasn't the only release affected.

**Comment by DennisLfromGA** [comment]
No problem.
You can probably close this issue unless you want to keep it open until the fix is in place.

**Comment by henrywright** [comment]
Probably best to close this as it does seem to be a duplicate.
