### ISSUE TITLE
Sharing a permanent folder

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2357]
It's great to see sharing files and folders is supported. Looking inside `/etc/crouton/shares`, I see the downloads folder is already shared by default:

```
downloads ~/Downloads
```

However, when I visit my Files app in Chrome OS, I see this notice which refers to the files inside the Downloads folder:

> Caution: These files are temporary and may be automatically deleted to free up disk space.

I've also heard horror stories of Chrome OS power-washing directories after system failure which causes their data to be wiped.

I'd like to share a host folder which has content that isn't at risk of being deleted. With this in mind, which folder on the host (Chrome OS) would you recommend I share with my chroot?

Ideally, I'd like to share a Google Drive folder, but I don't believe this is possible.

Thanks in advance.

Ref: https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders

**Comment by DennisLfromGA** [comment]
As you've discovered, anything stored on the 'stateful' partition is susceptible to getting wiped out.
I think about the only way to tuck things away in a semi-safe place is to resize a partition or create a new one. I've done both but I had to first replace my SSDs with a much larger one. I have a ChrUbuntu partition (# 7) and a CROUTON partition (# 13) on both my HP Chromebook 14 (falco) and my Acer C710 (parrot). My Acer C710 is below:
```
Filesystem                                                    Size  Used Avail Use% Mounted on
/dev/sda1                                                      20G   14G  4.9G  74% /home
/dev/sda7                                                      25G  9.7G   14G  42% /var/chrubuntu
/dev/sda13                                                     70G   57G  9.2G  87% /var/crouton
```
This works great for me but it's not possible for everyone. Plus, a full usb restoral will wipe out all of these so if something gets really borked, these partitions aren't super safe either.

I haven't experimented with it but you can change your 'Downloads location:' under Settings to use a Google Drive folder so this, in theory, could work. You may want to give that a try.

**Comment by henrywright** [comment]
Interesting to hear you're using a larger SSD. I'm currently making use of a 1TB Google disk space allowance but need to consider my options in ~1 year when that promotion ends.

> I haven't experimented with it but you can change your 'Downloads location:' under Settings to use a Google Drive folder so this, in theory, could work. You may want to give that a try.

That sounds like a possibility, although I'm not sure how it'd work with reference to setting the host directory?

`HOSTDIR CHROOTDIR`

**Comment by rprr** [comment]
You can mount a google drive folder in linux. Look at

http://gdfuse.forge.ocamlcore.org/

You will likely need to download/compile/install additional software.

**Comment by dnschneid** [comment]
If the concern is just auto-wipe, the "encrypted" and "shared" sections of /etc/crouton/shares won't get autowiped if space is low.  If you (accidentally?) do a dev wipe, though, Dennis is right and you'll lose everything on stateful.

**Comment by henrywright** [comment]
Thanks @dnschneid, but is /etc/crouton/shares on the host OS? I can't seem to find the crouton/ directory there with:

```
shell
cd /etc
ls
```

**Comment by DennisLfromGA** [comment]
@henrywright,

`/etc/crouton/shares` is the file in your chroot where you specify what you want to share.
The 'shares' file itself has some examples and there's a wiki on it too:

- [Sharing files and folders between Chrome OS and your chroot](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders#sharing-files-and-folders-between-chromeos-and-your-chroot)

The actual share point on the Chrome OS side is at: `/mnt/stateful_partition/crouton/shared/`

**Comment by henrywright** [comment]
> /etc/crouton/shares is the file in your chroot where you specify what you want to share

@DennisLfromGA right, I think I may have known that but got temporarily confused :)

I tried accessing /mnt/stateful_partition/crouton/shared but for some reason got a permission denied message?

I found out GNOME 3.18 has native support for Google Drive. That sounds exciting; although finding a release `-r` that has 3.18 is proving a little difficult.

**Comment by DennisLfromGA** [comment]
@henrywright,

I just explained where the sharepoint was on the Chrome OS side for completeness.

The folders there are handled by 'crouton' and are determined by what you place in `/etc/crouton/shares` in your chroot. They're not meant to be directly manipulated by the user.

**Comment by henrywright** [comment]
Ah OK. Thanks for clarifying

**Comment by pippo0312** [comment]
My experience:
I uncommented the following line in /etc/crouton/shares
```
shared/home   ~/Share
```
after rebooting chroot the newly created  ~/Share folder was owned by root:root 
To make it readable/writable I had to make a chown (in the chroot)
In ChromeOS this folder was mapped under 
```
/mnt/stateful_partition/crouton/shared/home
```
I have a question:
Is there any way to see in the ChromeOS file manager the folder
```
/mnt/stateful_partition/crouton/shared/home
```

**Comment by divx118** [comment]
@pippo0312 there are ways, but there all a bit of a hack. So nothing straight forward for now.

**Comment by henrywright** [comment]
```
shared/home ~/Share
```

Sorry for the noob question but trying to understand how this is intended to work. Uncommenting that line in /etc/crouton/shares will create a /home/henrywright/Share directory in my chroot and the content of that will be whatever is in /mnt/stateful_partition/crouton/shared/home on the host OS. Does that should right?

If that's the case, should I `chown` of both these folders to henrywright as currently their owner is set to root (as @pippo0312 described in the comment above)? And then I assume I just move the files I want to share into those folders? And those files won't be at risk of auto deletion (as mentioned above by @dnschneid)?

**Comment by pippo0312** [comment]
@henrywright I made  chown only inside the chroot. This automatically made the directory read/writable also in ChromeOS.

Changing slightly the subject: does anybody know when exactly ChromeOS may decide to start a cleanup of the ~/Downloads directory ? Is there a threshold on the space left ?

**Comment by DennisLfromGA** [comment]
@pippo0312,

> Changing slightly the subject: does anybody know when exactly ChromeOS may decide to start a cleanup of the ~/Downloads directory ? Is there a threshold on the space left ?

That's a good question; you might be able to get answer or at least get a good discussion going in [Chromebook Central](https://productforums.google.com/forum/#!newtopic/chromebook-central).

**Comment by dnschneid** [comment]
It's also worth noting that the encrypted/ share will get deleted if you have multiple logins on your Chromebook and you fill up the disk while logged out.

**Comment by henrywright** [comment]
@dnschneid my understanding is:

A powerwash will wipe everything local. So that means Chrome OS files and folders stored outside Google Drive and all chroots will be deleted.

Running `sudo delete-chroot chrootname` will wipe everything associated with `chrootname`.

So far I'm thinking a) Don't hit the Powerwash button and b) don't run the `delete-chroot` command.

The part I'm struggling to understand is the "Delete stuff because I'm low on space" part. Do you have any info with reference to what exactly on my local device will be at risk here? I'm asking because the only safe place are Google Drive folders which, to the best of my knowledge, cannot be shared with a chroot.

**Comment by dnschneid** [comment]
Yeah, Chromium is a little more complicated than that.

Doing a recovery will wipe the entire system, including any additional partitions you've made or modified.

A powerwash or dev wipe (space bar at the boot screen) will wipe the entire stateful partition, including all shared folders and chroots, but NOT wipe any additional partitions you've made (as @DennisLfromGA has done).

`delete-chroot` will delete the specific chroot, but not any of the shared folders.  Similarly, `edit-chroot` will only backup and restore specific chroots, and not any of the shared folders.

The "shared" share will be deleted only during a powerwash, dev wipe, or recovery.

The "downloads" share is subject to random file deletions in a single-Chromium-user environment if you are low on disk space.  In a multi-Chromium-user environment, any logged-out users can have their profile wiped (downloads, synced data, "encrypted" share, all in one fell swoop) if space gets low.  This is because Chromium cannot decrypt logged-out users' profiles, so it just has to delete the whole thing assuming it's synced to the cloud (a good assumption if it weren't for crouton).

The "encrypted" share is not subject to random file deletions when you're logged in, but impacted the same way as the downloads folder in a multi-Chromium-user scenario.

I wish it were simpler, but this is a case of Chromium OS being very smart for its intended usage at the expense of being kind of random and annoying for other things :)

**Comment by pippo0312** [comment]
I noticed that, when ChromeOS is low on disk space, a warning is shown on top of the file manager saying that files can be deleted  in the Downloads folder.
Can we safely assume that if the above warning is not shown there is no lack of space and no random deletion will be done ?

**Comment by henrywright** [comment]
@dnschneid many thanks for those clarifications, useful to know :)
