### ISSUE TITLE
Cannot move old log file fatal server error

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2358]
I installed a chroot with these targets: core, xiwi, keyboard, x11, cli-extra and extension. I've also installed the extension from the app store.

After running `sudo enter-chroot` and then trying to open a program `xiwi gimp`, I get a fatal server error:

```
(EE) 
Fatal server error:
(EE) Cannot move old log file "/tmp/Xorg.crouton.1.log" to "/tmp/Xorg.crouton.1.log.old"
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) 
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
```

**Comment by divx118** [comment]
@henrywright You probably did start with root once. Remember outside the chroot in a crosh shell we need to use sudo startxiwi, however inside a chroot you mustn't use `sudo` just `startxiwi`. To solve this issue, in a crosh shell use `sudo rm /tmp/Xorg.crouton.1.log` then try again, or you can just restart your chromebook that will also clear the `/tmp` folder.

**Comment by henrywright** [comment]
Thanks @divx118, restarting did the trick. For the record, I do seem to remember using `sudo startxiwi` inside the chroot so won't do that again :)
