### ISSUE TITLE
Failed to fetch gvfs-daemons_1.22.2-1_armhf.deb

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2359]
When running `sudo sh ~/Downloads/crouton -r jessie -t gnome-desktop -n jessie`, I get this error which indicates the chroot setup failed to complete:

```
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/g/gvfs/gvfs-daemons_1.22.2-1_armhf.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
```

My system architecture is `armhf`. Not sure if that matters?

**Comment by DennisLfromGA** [comment]
​I think it could be a temporary network glitch, maybe try again.​

On Sun, Jan 10, 2016 at 4:47 PM, Henry Wright <notifications@github.com>
wrote:

> When running sudo sh ~/Downloads/crouton -r jessie -t gnome-desktop -n
> jessie, I get this error which indicates the chroot setup failed to
> complete:
>
> E: Failed to fetch http://httpredir.debian.org/debian/pool/main/g/gvfs/gvfs-daemons_1.22.2-1_armhf.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]
>
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> Failed to complete chroot setup.
>
> My system architecture is armhf, not sure if that matters?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/2359>.
>



-- 
*DennyL@GMail*

**Comment by henrywright** [comment]
I thought the same, and actually tested twice already (the first time with the `gnome` target and then again with the `gnome-desktop` target): 

1. `sudo sh ~/Downloads/crouton -r jessie -t gnome -n jessie`
2. `sudo sh ~/Downloads/crouton -r jessie -t gnome-desktop -n jessie`

Same outcome for both.

**Comment by DennisLfromGA** [comment]
Maybe you could install a plain vanilla chroot with xorg & xiwi for instance and then add your gnome desktop while in the chroot.

Something like this might work: [Installing "GNOME Desktop" task](https://wiki.debian.org/Gnome#task)

**Comment by divx118** [comment]
@henrywright  like @DennisLfromGA  this will be a network glitch. Debian repos tend to be a bit unreliable in my experience. I had such errors often when installing a debian release. At the moment http://httpredir.debian.org/debian/pool/main/g/gvfs/gvfs-daemons_1.22.2-1_armhf.deb works for me. Just try again, but it can be in the worst case, take a couple of hours before it works again.

**Comment by henrywright** [comment]
@DennisLfromGA 

Would that mean running these commands? I'll try that

```
apt-get install aptitude tasksel
tasksel install gnome-desktop --new-install
```

**Comment by henrywright** [comment]
@divx118  strange I tried twice and got the exact same error on each attempt (attempts were ~6 hours apart; I tried this morning and then again this evening just before I opened this issue).

**Comment by divx118** [comment]
@henrywright Or are you perhaps running out of disk space?

**Comment by DennisLfromGA** [comment]
@henrywright - Yes, those commands should work.

However, you may have to edit your 'crouton' target files (`/.crouton-targets`, `/etc/crouton/targets` ) to add 'gnome' & 'gnome-desktop' manually and then either do a crouton update or use the `crouton -b` option to install the `startgnome` script.

I tried the above on my Chromebit (veyron_mickey) / trusty chroot and the installation went fine but I still can't launch 'gnome' on this thing.

**Comment by henrywright** [comment]
@divx118 
> Or are you perhaps running out of disk space?

I have ~2.3 GB spare, that should be enough for just the gnome target, if not for gnome-desktop?

**Comment by divx118** [comment]
@henrywright That should be indeed more then enough for the gnome target.

**Comment by henrywright** [comment]
@DennisLfromGA 
> However, you may have to edit your 'crouton' target files (/.crouton-targets, /etc/crouton/targets ) to add 'gnome' & 'gnome-desktop' manually and then either do a crouton update or use the crouton -b option to install the startgnome script.

Thanks, will keep that in mind

**Comment by henrywright** [comment]
3rd attempt went better:

`sudo sh ~/Downloads/crouton -r jessie -t gnome -n jessie`

seemed to be successful but after running `sudo startgnome`, I had an error message display something like "Oops, an error occurred from which the system couldn't recover. Please log out". That's all that was on the screen with a button to accept. Clicking the button gave a blank grey screen and from that point all I could do was hit the power off button.

But I guess that's a separate issue to the original issue I opened.

**Comment by henrywright** [comment]
Thanks for your help guys. I'll close because the original issue has been sorted. Looks like it was a glitch when downloading after all.
