### ISSUE TITLE
croutonversion

### ISSUE THREAD

**Issue by shar33f** [dnschneid/crouton#236]
Hey everyone, for some reason I am having a problem running croutonversion. Here's what happens when I run croutonversion -u -d -c

localhost:~$ croutonversion -u -d -c
crouton: version 0-20130617130435~master:9358b9d0
Retreiving latest version of crouton
latest: version 0-20130621110823~master:22bc1c1f
Saving latest version to /home/Downloads/crouton
exo-open: Cannot open display: .
Failed to launch browser to view https://github.com/dnschneid/crouton/compare/9358b9d0...master

Any ideas?

**Comment by ZachSaucier** [comment]
sudo enter-chroot croutonversion -u -d -c

The above worked for me

**Comment by DennisLfromGA** [comment]
@MaxGhenis,

IIUC when you're running it from crosh then yes, it can be ignored.
But if you're running it in the chroot it *should* launch a browser and show you the changes.

*Hope this helps,*
-**DennisLfromGA**
