### ISSUE TITLE
problem getting some trusty packages (octave)

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#2360]
Err http://archive.ubuntu.com/ubuntu/ trusty-security/main libcupsfilters1 amd64 1.0.52-0ubuntu1.5
  404  Not Found [IP: 91.189.88.153 80]
Err http://archive.ubuntu.com/ubuntu/ trusty-security/main libcupsimage2 amd64 1.7.2-0ubuntu1.6
  404  Not Found [IP: 91.189.88.153 80]
Fetched 48.3 MB in 1min 33s (518 kB/s)                                         
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cups-filters/libcupsfilters1_1.0.52-0ubuntu1.5_amd64.deb  404  Not Found [IP: 91.189.88.153 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cups/libcupsimage2_1.7.2-0ubuntu1.6_amd64.deb  404  Not Found [IP: 91.189.88.153 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
(trusty)root@localhost:/home/ted# ping 91.189.88.153
PING 91.189.88.153 (91.189.88.153) 56(84) bytes of data.
64 bytes from 91.189.88.153: icmp_seq=1 ttl=56 time=163 ms
64 bytes from 91.189.88.153: icmp_seq=2 ttl=56 time=162 ms
^C
--- 91.189.88.153 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 162.214/162.993/163.773/0.877 ms
(trusty)root@localhost:/home/ted# ping 91.189.88.153
PING 91.189.88.153 (91.189.88.153) 56(84) bytes of data.
64 bytes from 91.189.88.153: icmp_seq=1 ttl=56 time=167 ms
64 bytes from 91.189.88.153: icmp_seq=2 ttl=56 time=158 ms
^C
--- 91.189.88.153 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 158.508/162.923/167.339/4.433 ms
(trusty)root@localhost:/home/ted#

**Comment by tedm** [comment]
fixed it.

**Comment by DennisLfromGA** [comment]
@tedm - 

> fixed it.

How?
Was it just a temporarynetwork glitch or was the package not there?
...Just curious...

**Comment by tedm** [comment]
I think it was probably there, I hadn't run apt-get upgrade in a while...

**Comment by divx118** [comment]
@tedm I think you mean `sudo apt-get update` to update your sources list.

**Comment by tedm** [comment]
@divx118 Yes, it was the `apt-get update` command that got the package to install. Thanks for the correction.
