### ISSUE TITLE
Can't login to Linux and can't switch to XFCE desktop environment from Chromebook

### ISSUE THREAD

**Issue by dutchmandonpedro** [dnschneid/crouton#2361]
I just loaded Linux on my Chromebook but after some minutes of installation I was unable to access the XFCE desktop environment. Whenever I strike CTRL+ALT+FORWARD ( Trying to switch to Linux) it shows a black screen asking me for "localhost login". The screen has " Developer Console" as it's heading. But whenever I typed in the username and password I used while configuring the Crouton it say " Login incorrect". I been reading many posts here but none of them help.
 Am new to Linux but I want to start running it on my chromebook so I can be able to run some applications.  You help will be so appreciated. 
Thanks.

**Comment by dutchmandonpedro** [comment]
![img_20160111_161954](https://cloud.githubusercontent.com/assets/16648831/12237519/651e6fb6-b87f-11e5-9df5-f90e47e9b8e0.jpg)

THIS IS THE SCREEN I GOT BUT CANT LOGIN WITH MY USERNAME AND PASSWORD. PLEASE KINDLY HELP ME

**Comment by DennisLfromGA** [comment]
@dutchmandonpedro,

> Whenever I strike CTRL+ALT+FORWARD

This puts you in the Development console on VT2, not where you want to be.

> I was unable to access the XFCE desktop environment.

You'll need to login to your Google account, then press <kbd>Ctrl+Alt+t</kbd> to get a 'crosh' prompt, then type `shell` and press `enter` to get a bash shell prompt.

Then, to start your xfce session, enter: `sudo startxfce4`

**Comment by dutchmandonpedro** [comment]
Wow! Thanks so much. This works so fine. Am getting used to Linux now. Thanks so much for your support.

**Comment by DennisLfromGA** [comment]
No problem at all. :+1: 
( You can probably close this issue now. )

**Comment by Naiobi** [comment]
When I put in ctrl alt forward it asks me for a login username, & I put chronos & it gives me an option to put in a command. What do I do from there cause I've tried so many things but it just dosent enter into the desktop. 
What am I doing wrong can someone help please?

**Comment by DennisLfromGA** [comment]
@Naiobi,

Don't use <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>forward</kbd>, that puts you on VT2 in the Developer Console. 
Please follow the suggestion offered here: https://github.com/dnschneid/crouton/issues/2361#issuecomment-170597550

*Hope this helps,*
-**DennisL**

**Comment by nighthawk15** [comment]
I tried using sudo startxfce4 for the chronos shell, but it says that there is no command found.. I'm lost

**Comment by DennisLfromGA** [comment]
@nighthawk15,

This issue is over two years old, is closed, and is not your issue so I'm not sure how you wandered in here, I guess it popped up in a Google search for some obscure reason.

However, for your issue please follow the wiki guide below:
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

It will help you determine if you have a crouton chroot installed and where the problem is.

*Hope this helps,*
-**DennisLfromGA**

**Comment by zhmed** [comment]
reset chromebook open crosh type **shell** enter the command then type **sudo startxfce4**
