### ISSUE TITLE
How can I disabled 'Ctrl+Space' key from change language?

### ISSUE THREAD

**Issue by snowcat-Jung** [dnschneid/crouton#2363]
Chromebook Pixel 2015 LS

I just changed key 'change language' right Alt key(Multi_Key).
and It really works well.

but also 'ctrl+space' is still change language.
I really interrupt when I using IDE or text editor.

How can I disabled 'Ctrl+Space' key from change language?

**Comment by divx118** [comment]
Just so we have everything clear:
@snowcat-Jung it changes the language in a chroot or chromeos? If in a chroot, I would google the release + DE you are using and the change language hotkey.
