### ISSUE TITLE
I can't start Unity on an Ubuntu installation

### ISSUE THREAD

**Issue by ealgase** [dnschneid/crouton#2366]
To create my chroot, there are a few different installs I've tried:
* `sudo sh ~/Downloads/crouton -t xfce,unity,xiwi`
* `sudo sh ~/Downloads/crouton -t unity`
* `sudo sh ~/Downloads/crouton -t unity -r trusty`

The last 20 lines of `sudo sh ~/Downloads/crouton -t unity`([full-output](https://github.com/dnschneid/crouton/files/88147/full-output.txt)):

    Removing linux-libc-dev:i386 ...
    Removing x11proto-fixes-dev ...
    Removing x11proto-xext-dev ...
    Processing triggers for libc-bin ...
    ldconfig deferred processing now taking place
    Processing triggers for man-db ...
    Please specify a username for the primary user: ealgase
    Enter new UNIX password: 
    Retype new UNIX password: 
    passwd: password updated successfully

    Here's some tips:

    Audio from the chroot will now be forwarded to CRAS (Chromium OS audio server),
    through an ALSA plugin.

    Future Chromium OS upgrades may break compatibility with the installed version
    of CRAS. Should this happen, simply update your chroot.

    You can flip through your running chroot desktops and Chromium OS by hitting
    Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.

    You can start Unity via the startunity host command: sudo startunity

    Unmounting /mnt/stateful_partition/crouton/chroots/precise...
    Done! You can enter the chroot using enter-chroot
When attempting to start Unity from a crosh shell(with the command `sudo startunity`), the output is:

    chronos@localhost / $ sudo startunity
    Entering /mnt/stateful_partition/crouton/chroots/precise...

    _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

    X.Org X Server 1.15.1
    Release Date: 2014-04-13
    X Protocol Version 11, Revision 0
    Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
    Current Operating System: Linux localhost 3.14.0 #1 SMP Wed Jan 6 22:11:19 PST 2016 x86_64
    Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashtree=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=9028b2c6603c8794a57f22e5fc0c373173b4678d salt=9ab22ec5e6fd851f64f4950229276d5eb03dc94758b3f467780f8245ba04706d" noinitrd vt.global_cursor_default=0 kern_guid=9c4a8b66-bf2d-8344-b395-cc24c0f465ca add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
    Build Date: 12 February 2015  03:37:52PM
    xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
    Current version of pixman: 0.30.2
            Before reporting problems, check http://wiki.x.org
            to make sure that you have the latest version.
    Markers: (--) probed, (**) from config file, (==) default setting,
            (++) from command line, (!!) notice, (II) informational,
            (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jan 12 18:27:33 2016
    (==) Using system config directory "/usr/share/X11/xorg.conf.d"
    setversion 1.4 failed: Permission denied
    Initializing built-in extension Generic Event Extension
    Initializing built-in extension SHAPE
    Initializing built-in extension MIT-SHM
    Initializing built-in extension XInputExtension
    Initializing built-in extension XTEST
    Initializing built-in extension BIG-REQUESTS
    Initializing built-in extension SYNC
    Initializing built-in extension XKEYBOARD
    Initializing built-in extension XC-MISC
    Initializing built-in extension SECURITY
    Initializing built-in extension XINERAMA
    Initializing built-in extension XFIXES
    Initializing built-in extension RENDER
    Initializing built-in extension RANDR
    Initializing built-in extension COMPOSITE
    Initializing built-in extension DAMAGE
    Initializing built-in extension MIT-SCREEN-SAVER
    Initializing built-in extension DOUBLE-BUFFER
    Initializing built-in extension RECORD
    Initializing built-in extension DPMS
    Initializing built-in extension X-Resource
    Initializing built-in extension XVideo
    Initializing built-in extension XVideo-MotionCompensation
    Initializing built-in extension XFree86-VidModeExtension
    Initializing built-in extension XFree86-DGA
    Initializing built-in extension XFree86-DRI
    Initializing built-in extension DRI2
    Loading extension GLX
    Unable to open display lock file.
    Unable to claim display lock
    (EE) 
    Fatal server error:
    (EE) xf86OpenConsole: VT_ACTIVATE failed: Permission denied
    (EE) 
    (EE) 
    Please consult the The X.Org Foundation support 
             at http://wiki.x.org
     for help. 
    (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
    (EE) 
    (EE) Server terminated with error (1). Closing log file.

When going into the chroot and then typing `startunity`:

    chronos@localhost / $ sudo enter-chroot
    Entering /mnt/stateful_partition/crouton/chroots/precise...
    (precise)ealgase@localhost:~$ startunity

    _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

    X.Org X Server 1.15.1
    Release Date: 2014-04-13
    X Protocol Version 11, Revision 0
    Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
    Current Operating System: Linux localhost 3.14.0 #1 SMP Wed Jan 6 22:11:19 PST 2016 x86_64
    Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashtree=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=9028b2c6603c8794a57f22e5fc0c373173b4678d salt=9ab22ec5e6fd851f64f4950229276d5eb03dc94758b3f467780f8245ba04706d" noinitrd vt.global_cursor_default=0 kern_guid=9c4a8b66-bf2d-8344-b395-cc24c0f465ca add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
    Build Date: 12 February 2015  03:37:52PM
    xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
    Current version of pixman: 0.30.2
            Before reporting problems, check http://wiki.x.org
            to make sure that you have the latest version.
    Markers: (--) probed, (**) from config file, (==) default setting,
            (++) from command line, (!!) notice, (II) informational,
            (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jan 12 18:28:35 2016
    (==) Using system config directory "/usr/share/X11/xorg.conf.d"
    setversion 1.4 failed: Permission denied
    Initializing built-in extension Generic Event Extension
    Initializing built-in extension SHAPE
    Initializing built-in extension MIT-SHM
    Initializing built-in extension XInputExtension
    Initializing built-in extension XTEST
    Initializing built-in extension BIG-REQUESTS
    Initializing built-in extension SYNC
    Initializing built-in extension XKEYBOARD
    Initializing built-in extension XC-MISC
    Initializing built-in extension SECURITY
    Initializing built-in extension XINERAMA
    Initializing built-in extension XFIXES
    Initializing built-in extension RENDER
    Initializing built-in extension RANDR
    Initializing built-in extension COMPOSITE
    Initializing built-in extension DAMAGE
    Initializing built-in extension MIT-SCREEN-SAVER
    Initializing built-in extension DOUBLE-BUFFER
    Initializing built-in extension RECORD
    Initializing built-in extension DPMS
    Initializing built-in extension X-Resource
    Initializing built-in extension XVideo
    Initializing built-in extension XVideo-MotionCompensation
    Initializing built-in extension XFree86-VidModeExtension
    Initializing built-in extension XFree86-DGA
    Initializing built-in extension XFree86-DRI
    Initializing built-in extension DRI2
    Loading extension GLX
    Unable to open display lock file.
    Unable to claim display lock
    (EE) 
    Fatal server error:
    (EE) xf86OpenConsole: VT_ACTIVATE failed: Permission denied
    (EE) 
    (EE) 
    Please consult the The X.Org Foundation support 
             at http://wiki.x.org
     for help. 
    (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
    (EE) 
    (EE) Server terminated with error (1). Closing log file.

When going into the chroot and just typing `unity`:

    (precise)ealgase@localhost:~$ unity
    WARNING: no DISPLAY variable set, setting it to :0
    unity-panel-service: no process found
    compiz (core) - Fatal: Couldn't open display :0
    (precise)ealgase@localhost:~$ 

The same happens when using other versions of Ubuntu.

**Comment by DennisLfromGA** [comment]
What's the output of: `sudo edit-chroot -al` ?
