### ISSUE TITLE
ubuntu won't launch after first use

### ISSUE THREAD

**Issue by wgustlin** [dnschneid/crouton#2374]
I've been trying to get it work for a little while now. It will work fine the first time I boot it but when I try to launch it again I get the error below. I have tried xfce, unity, and kde and as far as I know its the same error on every one of them.

**Comment by wgustlin** [comment]
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Jan 6 22:10:17 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=84722435-30e5-b749-af34-ea11ee60b6a9/PARTNROFF=1 hashtree=PARTUUID=84722435-30e5-b749-af34-ea11ee60b6a9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5dbeabc47ff66a2119a6ea1d4e0d51618a5813b3 salt=5f14cea1890a61628725a31558d6ae63b10f55d7dba1988f6924212daf59ad8c" noinitrd vt.global_cursor_default=0 kern_guid=84722435-30e5-b749-af34-ea11ee60b6a9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jan 15 18:27:08 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
^C/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: unexpected signal 2
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by wgustlin** [comment]
I've downloaded the latest crouton build and am currently downloading that to see if that fixes the issue

**Comment by wgustlin** [comment]
The issue was that I had an old version of crouton. For people having the same issue, update your crouton and it should work

**Comment by wgustlin** [comment]
I updated my crouton and it still did the same thing

**Comment by wgustlin** [comment]
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Jan 6 22:10:17 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=84722435-30e5-b749-af34-ea11ee60b6a9/PARTNROFF=1 hashtree=PARTUUID=84722435-30e5-b749-af34-ea11ee60b6a9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5dbeabc47ff66a2119a6ea1d4e0d51618a5813b3 salt=5f14cea1890a61628725a31558d6ae63b10f55d7dba1988f6924212daf59ad8c" noinitrd vt.global_cursor_default=0 kern_guid=84722435-30e5-b749-af34-ea11ee60b6a9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jan 15 21:19:34 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by tista500** [comment]
@wgustlin,

```
Fatal server error:
no screens found
```
So what did `/tmp/Xorg.crouton.1.log` say?

Regards.

**Comment by wgustlin** [comment]
[  4129.234] _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[  4129.236] 
X.Org X Server 1.11.3
Release Date: 2011-12-16
[  4129.236] X Protocol Version 11, Revision 0
[  4129.236] Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
[  4129.236] Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Jan 6 22:10:17 PST 2016 x86_64
[  4129.236] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=84722435-30e5-b749-af34-ea11ee60b6a9/PARTNROFF=1 hashtree=PARTUUID=84722435-30e5-b749-af34-ea11ee60b6a9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5dbeabc47ff66a2119a6ea1d4e0d51618a5813b3 salt=5f14cea1890a61628725a31558d6ae63b10f55d7dba1988f6924212daf59ad8c" noinitrd vt.global_cursor_default=0 kern_guid=84722435-30e5-b749-af34-ea11ee60b6a9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
[  4129.237] Build Date: 12 February 2015  02:49:01PM
[  4129.237] xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
[  4129.237] Current version of pixman: 0.30.2
[  4129.237] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  4129.237] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  4129.237] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jan 18 21:21:49 2016
[  4129.240] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  4129.242] (==) No Layout section.  Using the first Screen section.
[  4129.242] (==) No screen section available. Using defaults.
[  4129.242] (**) |-->Screen "Default Screen Section" (0)
[  4129.242] (**) |   |-->Monitor "<default monitor>"
[  4129.243] (==) No device specified for screen "Default Screen Section".
	Using the first device section listed.
[  4129.243] (**) |   |-->Device "Intel Graphics SNA+TearFree"
[  4129.243] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[  4129.244] (==) Automatically adding devices
[  4129.244] (==) Automatically enabling devices
[  4129.246] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  4129.246] 	Entry deleted from font path.
[  4129.246] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  4129.246] 	Entry deleted from font path.
[  4129.246] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  4129.246] 	Entry deleted from font path.
[  4129.247] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  4129.247] 	Entry deleted from font path.
[  4129.247] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  4129.247] 	Entry deleted from font path.
[  4129.247] (WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  4129.247] 	Entry deleted from font path.
[  4129.247] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/Type1,
	built-ins
[  4129.247] (==) ModulePath set to "/usr/lib/x86_64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  4129.247] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[  4129.247] (II) Loader magic: 0x7fb9c6412b00
[  4129.247] (II) Module ABI versions:
[  4129.247] 	X.Org ANSI C Emulation: 0.4
[  4129.247] 	X.Org Video Driver: 11.0
[  4129.247] 	X.Org XInput driver : 16.0
[  4129.247] 	X.Org Server Extension : 6.0
[  4129.247] (--) PCI:*(0:0:2:0) 8086:0f31:8086:0f31 rev 14, Mem @ 0xd0000000/4194304, 0xc0000000/268435456, I/O @ 0x00001000/8
[  4129.248] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
[  4129.248] (II) LoadModule: "extmod"
[  4129.249] (II) Loading /usr/lib/xorg/modules/extensions/libextmod.so
[  4129.251] (II) Module extmod: vendor="X.Org Foundation"
[  4129.251] 	compiled for 1.11.3, module version = 1.0.0
[  4129.251] 	Module class: X.Org Server Extension
[  4129.251] 	ABI class: X.Org Server Extension, version 6.0
[  4129.251] (II) Loading extension MIT-SCREEN-SAVER
[  4129.251] (II) Loading extension XFree86-VidModeExtension
[  4129.251] (II) Loading extension XFree86-DGA
[  4129.251] (II) Loading extension DPMS
[  4129.251] (II) Loading extension XVideo
[  4129.251] (II) Loading extension XVideo-MotionCompensation
[  4129.251] (II) Loading extension X-Resource
[  4129.251] (II) LoadModule: "dbe"
[  4129.251] (II) Loading /usr/lib/xorg/modules/extensions/libdbe.so
[  4129.252] (II) Module dbe: vendor="X.Org Foundation"
[  4129.252] 	compiled for 1.11.3, module version = 1.0.0
[  4129.252] 	Module class: X.Org Server Extension
[  4129.252] 	ABI class: X.Org Server Extension, version 6.0
[  4129.252] (II) Loading extension DOUBLE-BUFFER
[  4129.252] (II) LoadModule: "glx"
[  4129.252] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  4129.256] (II) Module glx: vendor="X.Org Foundation"
[  4129.256] 	compiled for 1.11.3, module version = 1.0.0
[  4129.256] 	ABI class: X.Org Server Extension, version 6.0
[  4129.256] (==) AIGLX enabled
[  4129.257] (II) Loading extension GLX
[  4129.257] (II) LoadModule: "record"
[  4129.257] (II) Loading /usr/lib/xorg/modules/extensions/librecord.so
[  4129.258] (II) Module record: vendor="X.Org Foundation"
[  4129.258] 	compiled for 1.11.3, module version = 1.13.0
[  4129.258] 	Module class: X.Org Server Extension
[  4129.258] 	ABI class: X.Org Server Extension, version 6.0
[  4129.258] (II) Loading extension RECORD
[  4129.258] (II) LoadModule: "dri"
[  4129.258] (II) Loading /usr/lib/xorg/modules/extensions/libdri.so
[  4129.262] (II) Module dri: vendor="X.Org Foundation"
[  4129.262] 	compiled for 1.11.3, module version = 1.0.0
[  4129.262] 	ABI class: X.Org Server Extension, version 6.0
[  4129.262] (II) Loading extension XFree86-DRI
[  4129.262] (II) LoadModule: "dri2"
[  4129.262] (II) Loading /usr/lib/xorg/modules/extensions/libdri2.so
[  4129.263] (II) Module dri2: vendor="X.Org Foundation"
[  4129.263] 	compiled for 1.11.3, module version = 1.2.0
[  4129.263] 	ABI class: X.Org Server Extension, version 6.0
[  4129.263] (II) Loading extension DRI2
[  4129.263] (II) LoadModule: "intel"
[  4129.264] (WW) Warning, couldn't open module intel
[  4129.264] (II) UnloadModule: "intel"
[  4129.264] (II) Unloading intel
[  4129.264] (EE) Failed to load module "intel" (module does not exist, 0)
[  4129.264] (==) Matched intel as autoconfigured driver 0
[  4129.264] (==) Matched vesa as autoconfigured driver 1
[  4129.264] (==) Matched fbdev as autoconfigured driver 2
[  4129.264] (==) Assigned the driver to the xf86ConfigLayout
[  4129.264] (II) LoadModule: "intel"
[  4129.265] (WW) Warning, couldn't open module intel
[  4129.265] (II) UnloadModule: "intel"
[  4129.265] (II) Unloading intel
[  4129.265] (EE) Failed to load module "intel" (module does not exist, 0)
[  4129.265] (II) LoadModule: "vesa"
[  4129.266] (WW) Warning, couldn't open module vesa
[  4129.266] (II) UnloadModule: "vesa"
[  4129.266] (II) Unloading vesa
[  4129.266] (EE) Failed to load module "vesa" (module does not exist, 0)
[  4129.266] (II) LoadModule: "fbdev"
[  4129.266] (WW) Warning, couldn't open module fbdev
[  4129.266] (II) UnloadModule: "fbdev"
[  4129.266] (II) Unloading fbdev
[  4129.266] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  4129.266] (EE) No drivers available.
[  4129.266] 
Fatal server error:
[  4129.266] no screens found
[  4129.266] 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[  4129.266] Please also check

**Comment by wgustlin** [comment]
I'm new to all this so that may not be the right thing.

**Comment by tista500** [comment]
As your log shown above, an intel driver might not be installed properly. If you've already started over re-installing, please see the messages remained in crosh within installation carefully. There might be something wrong with finishing processes of install...

Regards.

**Comment by masterpaper** [comment]
I had that problem all you have to do is update the chroot try this udo sh ~/Downloads/crouton -u -n precise
