### ISSUE TITLE
crouton and use of fuse to mount google drive

### ISSUE THREAD

**Issue by kcoyner** [dnschneid/crouton#2377]
I'm using crouton to run a Debian Sid chroot.  Overall it works great, but recently I tried using fuse to mount my Google Drive account per the instructions found here:

https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie

I am able to get it all working and actually mount my Google Drive.  However, if I shut down the chroot, and then start it up again, I get the following error message:

WARNING: starting chroot system dbus daemon failed with code 2

Fortunately I'm able to resort to my backup and get the chroot back and running again.  But I'm wondering why this won't work.

Thanks.

**Comment by tista500** [comment]
@kcoyner,

Though I could not answer your issue clearly, Sid might have GNOME 3.18.x already so did you try the combination of goa and nautilus if you had Gnome Desktop? For me, Ubuntu Xenial Gnome fortunately could work nice with Google-Drive on crouton.

I have not any clue some other desktop environments... :/

Regards.

P.S.
I would see that link/code and try it on my croutons as well.

**Comment by drinkcat** [comment]
Some ideas here #2173 .
