### ISSUE TITLE
external usb for crouton

### ISSUE THREAD

**Issue by danram111** [dnschneid/crouton#2378]
hay guys im new at this but i really need to know how to mount an external usb on my chromebook linux (crouton) i tried everything dasnt seem to work

**Comment by nigelhealy** [comment]
What happens if you're in ChromeOS and plug it in? Does ChromeOS recognize
it?

Then the mount carries over to Crouton in my experience.

If you simply want to mount in Crouton then this is generic linux skills.

What does
dmesg|tail

show after you plug in the drive?

**Comment by danram111** [comment]
thanks for the fast respond when i did that it says its mounted 
 14.138124] tpm_tis tpm_tis: command 0xba (size 18) returned code 0x22
[   24.816317] usb 2-1.2: USB disconnect, device number 3
[   24.995771] usb 2-1.2: new high-speed USB device number 5 using ehci-pci
[   25.081590] usb 2-1.2: New USB device found, idVendor=18d1, idProduct=4ee1
[   25.081606] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   25.081618] usb 2-1.2: Product: Nexus 5
[   25.081627] usb 2-1.2: Manufacturer: LGE
[   25.081639] usb 2-1.2: SerialNumber: 0303c9350937eb57
[   35.667538] ca0132 DOWNLOAD OK :-) DSP IS RUNNING.
[   47.060782] EXT4-fs (sda1): re-mounted. Opts: commit=600,data=ordered


 however where do i see the files on itv

**Comment by nigelhealy** [comment]
Don't understand "however where do i see the files on itv"

What does
sudo fdisk -l
say?
What does
df -TH
say?
What does
mount

The first command will list all storage devices /dev/sdb1 is probably your
attached disk or might be /deb/sdc1
The 2nd command will show all that is mounted
The 3rd command will show all mounts

At the end of that you should see where it is mounted and browse it. If its
showing up in the 1st command but not the latter it may be because its
corrupted and needs a repair (fsck) but important to repair it with the
correct filesystem, if its not mounted then use
sudo file -sL /dev/.... (e.g. /dev/sdc1)
to see its filesystem type.

**Comment by danram111** [comment]
WARNING: GPT (GUID Partition Table) detected on '/dev/sda'! The util fdisk doesn't support GPT. Use GNU Parted.


Disk /dev/sda: 64.0 GB, 64023257088 bytes
256 heads, 63 sectors/track, 7753 cylinders, total 125045424 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1               1   125045423    62522711+  ee  GPT

Disk /dev/mapper/encstateful: 17.3 GB, 17306009600 bytes
255 heads, 63 sectors/track, 2104 cylinders, total 33800800 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000

Disk /dev/mapper/encstateful doesn't contain a valid partition table
     thats what fdisk -1 says

**Comment by danram111** [comment]
df: `/mnt/stateful_partition': No such file or directory
df: `/usr/share/oem': No such file or directory
df: `/mnt/stateful_partition/encrypted': No such file or directory
df: `/home/chronos': No such file or directory
df: `/run/debugfs_gpu': No such file or directory
df: `/home/.shadow/877f1ae15b28209c1b61b36f3ac9b08fe046cc7a/mount': No such file or directory
df: `/home/chronos/user': No such file or directory
df: `/home/user/877f1ae15b28209c1b61b36f3ac9b08fe046cc7a': No such file or directory
df: `/home/chronos/u-877f1ae15b28209c1b61b36f3ac9b08fe046cc7a': No such file or directory
df: `/home/root/877f1ae15b28209c1b61b36f3ac9b08fe046cc7a': No such file or directory
df: `/run/crw': No such file or directory
Filesystem                                                   Type      Size  Used Avail Use% Mounted on
rootfs                                                       rootfs     58G  3.3G   52G   7% /
/dev/root                                                    ext2       58G  3.3G   52G   7% /
devtmpfs                                                     devtmpfs  2.1G     0  2.1G   0% /dev
tmp                                                          tmpfs     2.1G  2.6M  2.1G   1% /tmp
run                                                          tmpfs     408M   25k  408M   1% /run
shmfs                                                        tmpfs     2.1G  206M  1.9G  11% /dev/shm
/dev/sda1                                                    ext4       58G  3.3G   52G   7% /home
/dev/mapper/encstateful                                      ext4       58G  3.3G   52G   7% /var
media                                                        tmpfs      58G  3.3G   52G   7% /media
/dev/sda1                                                    ext4       58G  3.3G   52G   7% /usr/local
none                                                         pstore    2.1G     0  2.1G   0% /dev/pstore
none                                                         tmpfs     2.1G     0  2.1G   0% /sys/fs/cgroup
/dev/sda1                                                    ext4       58G  3.3G   52G   7% /
devtmpfs                                                     devtmpfs  2.1G     0  2.1G   0% /dev
shmfs                                                        tmpfs     2.1G  206M  1.9G  11% /dev/shm
tmp                                                          tmpfs     2.1G  2.6M  2.1G   1% /tmp
tmpfs                                                        tmpfs     408M   25k  408M   1% /run
tmpfs                                                        tmpfs     5.3M     0  5.3M   0% /run/lock
run                                                          tmpfs     2.1G  439k  2.1G   1% /var/host/dbus
run                                                          tmpfs     2.1G  439k  2.1G   1% /var/host/shill
/dev/mapper/encstateful                                      ext4       18G   60M   17G   1% /var/host/timezone
/dev/root                                                    ext2      1.3G  1.1G  172M  87% /lib/modules/3.8.11
run                                                          tmpfs     2.1G  439k  2.1G   1% /var/host/udev
run                                                          tmpfs     2.1G  439k  2.1G   1% /var/host/cras
media                                                        tmpfs     2.1G     0  2.1G   0% /var/host/media
/home/.shadow/877f1ae15b28209c1b61b36f3ac9b08fe046cc7a/vault ecryptfs   58G  3.3G   52G   7% /home/danram/Downloads
none                                                         tmpfs     2.1G     0  2.1G   0% /sys/fs/cgroup
tmpfs                                                        tmpfs     408M   25

**Comment by danram111** [comment]
thanks dude i really dont know what im douing

**Comment by nigelhealy** [comment]
Crouton is a chroot off a kernel on ChromeOS so your kernel messages are from ChromeOS, NOT related to Chrouton whatsoever.

So ignore Crouton, this is Linux which is underneath ChromeOS.

Your lack of a device in dmesg shows you have a basic hardware/driver problem between your harddrive and your Chromebook. The dmesg command is showing it is detecting something on USB but no drive messages means there isn't a drive being detected. That is why you aren't see anything in fdisk and then not either in df.

That would be a cabling or a power issue, like say your drive isn't getting enough power from your Chromebook, or you plugging (somehow) incompatible USB cables.

Check for obvious problems related to ChromeOS first.

Once you got it working in ChromeOS, then Crouton is seeing your files too.

**Comment by nigelhealy** [comment]
Ahh I see your problem looking at detail. You aren't actually plugging in USB storage at all. You are plugging in a mobile phone a Nexus 5.

So then your issue is about MTP. Your problems are not Linux related. You have an issue with the MTP software on your Chromebook not working with whatever you have done to your Nexus 5. Try different cables, different USB sockets and enable/disable USB debugging on Android.

Not a Crouton dimension issue.

**Comment by danram111** [comment]
Thanks bro I ldk if your getting paid for this but your awesome
