### ISSUE TITLE
Can't open Ubuntu after dual-booting an asus chromebook

### ISSUE THREAD

**Issue by jwatson123** [dnschneid/crouton#2379]
I followed this guide "http://lifehacker.com/how-to-install-linux-on-a-chromebook-and-unlock-its-ful-509039343" and typed sudo startxfce4 to start the desktop and also tried the ctrl alt shift back etc. I also tried start-chroot but just got "Must be run as root" but nothing would happen the response from the startxfce command was

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Wed Jan 6 21:59:46 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=60656b1e-553c-134a-a573-dab719e5497a/PARTNROFF=1 hashtree=PARTUUID=60656b1e-553c-134a-a573-dab719e5497a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=7ec8aab8d0474c61188a7e77e1ac14f9a5241745 salt=3c289cf34a5047aec2ac59337f59907f12bd1946972fa345d2043c6e95cb554a" noinitrd vt.global_cursor_default=0 kern_guid=60656b1e-553c-134a-a573-dab719e5497a  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jan 18 11:53:44 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Do i have to set to root (what does that mean??)
Any help would be much appreciated

Thanks

**Comment by tista500** [comment]
@jwatson123,

Please let us see the output of this command from your crosh:
```
sudo edit-chroot -al
```

You seem to run crouton on ARM architectures, so today you'd better to add `xiwi` target to launch X11 and an extension of Chrome browser: https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom as well...

Anyway see details in Wiki: https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)

Regards.
