### ISSUE TITLE
xiwi: chroot can't connect to the extension

### ISSUE THREAD

**Issue by piquan** [dnschneid/crouton#2380]
I haven't been able to get xiwi to work.  If I run "sudo startxiwi xterm" from a shell within crosh, for example, I always get a message like this:

```
 Cannot connect to extension, retrying...
 [repeats]
 Unable to start display, make sure the crouton extension is installed
 and enabled, and up to date. (download from http://goo.gl/OVQOEt)
```

During this process, the Crouton extension button switches from grey to green, and if I click on it I see "1: trusty" (or whatever my chroot name is), but once the chroot startup fails, the extension button switches back to grey.  If I show the log, I don't get anything terribly useful:

```
 16:59:50   Connection closed
 16:59:41   Connection established
```

This is using an HP Chromebook G3 14, in developer mode, with a stock OS.  I've added some command line utilities through dev_install, but was having this problem before doing so.

Below is an example session.

```
 chronos@localhost ~/Downloads $ sudo sh crouton -e -t xiwi,xfce
 [snip]
 Processing triggers for libc-bin ...
 ldconfig deferred processing now taking place
 Please specify a username for the primary user: joelh
 Enter new UNIX password: 
 Retype new UNIX password: 
 passwd: password updated successfully

 Here's some tips:

 Audio from the chroot will now be forwarded to CRAS (Chromium OS audio server),
 through an ALSA plugin.

 Future Chromium OS upgrades may break compatibility with the installed version
 of CRAS. Should this happen, simply update your chroot.

 You already have the Chromium OS extension installed, so you're good to go!

 You can open your running chroot desktops by clicking on the extension icon.
 Once in a crouton window, press fullscreen or the "switch window" key to switch
 back to Chromium OS.

 You can launch individual apps in crouton windows by using the "xiwi" command
 in the chroot shell. Use startxiwi to launch directly from the host shell.
 Use the startxiwi parameter -b to run in the background.
 Example: sudo startxiwi -b xterm

 You can start Xfce via the startxfce4 host command: sudo startxfce4

 Unmounting /mnt/stateful_partition/crouton/chroots/precise...
 Done! You can enter the chroot using enter-chroot.



 chronos@localhost ~/Downloads $ sudo startxiwi xterm
 Password: 
 Entering /mnt/stateful_partition/crouton/chroots/precise...

 _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

 X.Org X Server 1.11.3
 Release Date: 2011-12-16
 X Protocol Version 11, Revision 0
 Build Operating System: Linux 2.6.42-68-highbank armv7l Ubuntu
 Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Jan 6 22:00:52 PST 2016 armv7l
 Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=a1937b41-ddb7-434c-ad5d-eea2eaf01d77/PARTNROFF=1 hashtree=PARTUUID=a1937b41-ddb7-434c-ad5d-eea2eaf01d77/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=7f3d77c2232eb689492333719ab9986991423ca3 salt=995992f3b7c3c7eb04c925852bed5fa4b37b2db05447c73d8612eac88638ffc9" noinitrd vt.global_cursor_default=0 kern_guid=a1937b41-ddb7-434c-ad5d-eea2eaf01d77  
 Build Date: 12 February 2015  02:54:30PM
 xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see  http://www.ubuntu.com/support) 
 Current version of pixman: 0.30.2
         Before reporting problems, check http://wiki.x.org
         to make sure that you have the latest version. 
 Markers: (--) probed, (**) from config file, (==) default setting,
         (++) from command line, (!!) notice, (II) informational,
         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
 (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Jan 17 16:59:39 2016
 (++) Using config file: "/etc/X11/xorg-dummy.conf"
 (==) Using system config directory "/usr/share/X11/xorg.conf.d"
 /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
 crouton: version 1-20160116142703~master:d9b40a7f
 release: precise
 architecture: armhf
 xmethod: xiwi
 targets: xiwi,xfce
 host: version 7520.67.0 (Official Build) stable-channel nyan_blaze 
 kernel: Linux localhost 3.10.18 #1 SMP Wed Jan 6 22:00:52 PST 2016 armv7l armv7l armv7l GNU/Linux
 freon: no
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Cannot connect to extension, retrying...
 Unable to start display, make sure the crouton extension is installed
 and enabled, and up to date. (download from http://goo.gl/OVQOEt)
 Running exit commands...
 /usr/bin/xinit: connection to X server lost

 waiting for X server to shut down Hangup
 Hangup
  ddxSigGiveUp: Closing log
 Server terminated successfully (0). Closing log file.

 Unmounting /mnt/stateful_partition/crouton/chroots/precise...
 Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/precise...
```

**Comment by mark-hahn** [comment]
I just saw this exact same thing today for the first time and I've used xiwi for a long time.  It has always said `Cannot connect to extension, retrying...` four or five times before working but this is the first time it failed completely.

ubuntu 12.02
chromebook pixel 2015

**Comment by mahasamoot** [comment]
xiwi & extension are useless, don't work, have never worked for any version I've tried.  I have the impression that they are not maintained.  Perhaps support should be removed so we don't wast our time trying to use features that don't work with current versions of ChromeOS?

I'm running an HP Chromebook 14 3G with an Nvidia tegra k1.

**Comment by mark-hahn** [comment]
> xiwi & extension are useless, don't work, have never worked for any
version I've tried.

Weird.  I use them constantly.  Are you on freon like I am?

**Comment by mahasamoot** [comment]
freon ?

**Comment by mark-hahn** [comment]
I don't know what freon means, I just know I have it on my pixel 2 and some
have it and some don't.  I've had bugs that were only on freon.  I was just
throwing it out there.

**Comment by Piquan** [comment]
Freon is a display stack that's an alternative to X; see also https://www.phoronix.com/scan.php?page=news_item&px=Chrome-OS-Freon-Graphics and https://plus.google.com/+FrancoisBeaufort/posts/L3zmATV8BW5 .  The HP Chromebooks that mahasamoot and I are using are not using Freon; the Pixel that mark-hahn uses does.  This could be related, yes.

**Comment by divx118** [comment]
@Piquan all chromebooks should be using freon by now. You can easily check it on your chromebook by looking in a crosh shell if `/sbin/frecon` exists.

**Comment by smibarber** [comment]
nyan based boards (Tegra K1) are not yet freonized.

**Comment by divx118** [comment]
@smibarber Ah thanks for the info. I thought they already switched to freon my mistake.

**Comment by solamour** [comment]
I'm having the exactly same problem. It was working a couple of weeks (or so) ago, but I use the command line mode most of the time, so I didn't notice the problem until now. I rebooted once or twice to update, but other than that, I didn't make any changes. I'm using Acer C720, if that matters at all.
__
sol

**Comment by DennisLfromGA** [comment]
@solamour,

Your Acer C720 is 'freonized' so this issue shouldn't affect you.

Just make sure to follow these guidelines to make sure you're up-to-date:

[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

Also, you may have to try a few times to get it to launch/connect.

*Hope this helps,*
-**DennisL**

**Comment by solamour** [comment]
I have an HP Chromebook 14  with the identical setting, and xiwi works every time; I do need to wait a few seconds for it to show up, but it does work.

One thing I noticed is that on the working machine, in Crouton Integration extension icon, I see "Connecting..." and "Disconnected (retrying every 5 seconds)" alternatively every few seconds or so if xiwi is not running. But on the non-working machine, I see "Connecting..." only; it's just stuck there without trying again. Let me know if there is a way to get a log to identify the problem.
__
sol

**Comment by piquan** [comment]
(I'm the OP of this issue.)

I no longer have the computer in question; I have a different model of Chromebook, and it works fine.  I can't test the current code after @solamour's comment.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
