### ISSUE TITLE
MySQL not installing properly

### ISSUE THREAD

**Issue by yaboicree** [dnschneid/crouton#2382]
I am trying to install a LAMP stack on my Toshiba Chromebook 2 (CB35-B3340) but am having trouble installing mysql. My machine has been running Ubuntu 14.04 and Unity for about 6 months (and did Ruby on Rails dev without major issues) and I created a new chroot with Ubuntu 12.04 and XFCE after running into a lot of issues with mysql on my other install.

Every time I run mysql on either chroot, it gives me the following error: 

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

I have checked the my.cnf file and created a folder at the location it expects for mysqld.sock to appear. I have mysql-server installed. I tried running commands like /etc/init.d/mysql start, and also tried various commands to get mysqld to start. The mysqld file was very difficult to find in the 14.04 system, and entire folders of the install seemed to be missing. 

How should I deal with this? I just want to do local wordpress theme development.

**Comment by divx118** [comment]
@yaboicree Does this help https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton#lamp

**Comment by yaboicree** [comment]
@divx118 Nope, tried it in both OS's and didn't work.

I don't think I was clear enough - there is no mysqld.sock on either system (tried to search by find / -type s and couldnt find it, also searched for all files with mysql in name).

**Comment by divx118** [comment]
@yaboicree Sorry can't help you much, I never tried installing mysql. I just remembered it was mentioned in the wiki. Well maybe someone else has some good suggestions for you.

**Comment by tedm** [comment]
did you open up iptables with the input accept all or equivalent commands? I ran LAMP stacks on 12.04 reliably, but the setup was a bit tricky, though I think everything was explained in either my ebook on amazon (hacking the chromebook), or the wiki here on running services. If you are using DHCP, use localhost when setting up mysql.

**Comment by ncc1701v** [comment]
On Wed, Jan 20, 2016 at 10:56 AM, yaboicree <notifications@github.com>
wrote:
>
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket
'/var/run/mysqld/mysqldsock' (2)

You have to start the daemon by hand to start with. /etc/init.d/mysql start

**Comment by yaboicree** [comment]
@tedm the iptables (from this link https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton#lamp) did the trick. 

@ncc1701v i ran that command before installing the iptables package and setting to accept all. 

Thank you all for the help!! I will try to pass it forward as I gain more experience with crouton :D

**Comment by G3zz** [comment]
Sorry to bring this up again - @yaboicree could you give me more specific steps on what you did to solve this? I'm tearing my hair out trying to install mysql on my Toshiba Chromebook 2.
