### ISSUE TITLE
Unable to update properly

### ISSUE THREAD

**Issue by TheWiseYoda** [dnschneid/crouton#2384]
Sorry if this is a duplicate, I couldn't find a solution.

Crouton fails to update, I posted the end of the log below. I downloaded the crouton installer again after deleting the old one, and the problem persisted.

Command I ran: sudo sh ~/Downloads/crouton -u -n trusty

Output of sudo enter-chroot -n trusty croutonversion:

crouton: version 1-20160116142703~master:d9b40a7f
release: trusty
architecture: armhf
xmethod: xiwi
targets: lxde,xiwi
host: version 7834.0.0 (Official Build) dev-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Jan 16 02:54:48 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes

Log:

Installing target xiwi...
xserver-xorg-video-dummy was already not hold.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xserver-xorg-video-dummy is already the newest version.
xorg is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
i3 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing dependencies for /usr/local/bin/croutonfbserver...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6-dev is already the newest version.
libxext-dev is already the newest version.
libxfixes-dev is already the newest version.
gcc is already the newest version.
libx11-dev is already the newest version.
libxdamage-dev is already the newest version.
libxtst-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonfbserver...
Installing dependencies for /usr/local/bin/croutonfindnacld...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6-dev is already the newest version.
gcc is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonfindnacld...
Download Xorg dummy driver...
--2016-01-22 11:48:24--  http://xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
Resolving xorg.freedesktop.org (xorg.freedesktop.org)... 131.252.210.176
Connecting to xorg.freedesktop.org (xorg.freedesktop.org)|131.252.210.176|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 346888 (339K) [application/x-gzip]
Saving to: '/tmp/crouton-cras.jFeX0P/dummy.tar.gz'

100%[===========================================================================================================>] 346,888     1.56MB/s   in 0.2s   

2016-01-22 11:48:24 (1.56 MB/s) - '/tmp/crouton-cras.jFeX0P/dummy.tar.gz' saved [346888/346888]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libc6-dev' instead of 'libc-dev'
libc6-dev is already the newest version.
patch is already the newest version.
gcc is already the newest version.
pkg-config is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-dev : Depends: mesa-common-dev
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by tista500** [comment]
@TheWiseYoda,

Try to install `mesa-common-dev` manually from crosh:
```
sudo enter-chroot -n trusty
sudo apt-get update
sudo apt-get install mesa-common-dev
```
These commmands might show some error messages casued by unmet dependencies within installing mesa-common-dev, so let us see the whole output of the last command.

Regards.

**Comment by TheWiseYoda** [comment]
@tista500 

sudo apt-get install mesa-common-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mesa-common-dev : Depends: libdrm-dev (>= 2.4.52) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by tista500** [comment]
OK.

In Jan 08, trusty seems to have libdrm 2.4.64-1 already:
https://launchpad.net/ubuntu/+source/libdrm/2.4.64-1~ubuntu14.04.1
So you'd better to upgrade your trusty release at first:
```
sudo enter-chroot -n trusty
sudo apt-get dist-upgrade -y
```
I'm afraid that you did not do upgrading trusty for a while...
After upgrading, retry courton updating once more.

Regards.

**Comment by TheWiseYoda** [comment]
@tista500 

sudo apt-get dist-upgrade -y
[sudo] password for ********: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tista500** [comment]
??

Btw, what did `sudo apt-get install libdrm-dev` say?

Regards.

**Comment by TheWiseYoda** [comment]
@tista500 

sudo apt-get install libdrm-dev
[sudo] password for **********: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdrm-dev : Depends: libdrm2 (= 2.4.56-1~ubuntu2) but 2.4.60-2~ubuntu14.04.1 is to be installed
              Depends: libdrm-radeon1 (= 2.4.56-1~ubuntu2) but 2.4.60-2~ubuntu14.04.1 is to be installed
              Depends: libdrm-nouveau2 (= 2.4.56-1~ubuntu2) but 2.4.60-2~ubuntu14.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by tista500** [comment]
So let me see the output of:

`dpkg -l | grep libdrm | awk '{ print $1,$2,$3 }'`

and 

`apt-mark showhold`

Both commands work without sudo.

Regards.

**Comment by TheWiseYoda** [comment]
For 

dpkg -l | grep libdrm | awk '{ print $1,$2,$3 }'

ii libdrm-nouveau2:armhf 2.4.60-2~ubuntu14.04.1
ii libdrm-radeon1:armhf 2.4.60-2~ubuntu14.04.1
ii libdrm2:armhf 2.4.60-2~ubuntu14.04.1

apt-mark showhold does not give a response

**Comment by tista500** [comment]
Sorry for my delayed response...

Try to search all version installable:
` apt-cache showpkg libdrm-dev`
Then coudl you verify the current  2.4.60-2~ubuntu14.04.1 was shown.

If true, finally let's try to install specific version:
`sudo apt-get install libdrm-dev=2.4.60-2~ubuntu14.04.1`

Regards.

**Comment by TheWiseYoda** [comment]
Output of apt-cache showpkg libdrm-dev

Package: libdrm-dev
Versions: 
2.4.56-1~ubuntu2 (/var/lib/apt/lists/ports.ubuntu.com_ubuntu-ports_dists_trusty-security_main_binary-armhf_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/ports.ubuntu.com_ubuntu-ports_dists_trusty-security_main_binary-armhf_Packages
                  MD5: 26367cfc3b23b21ad8b59e1f0974ff45
 Description Language: en
                 File: /var/lib/apt/lists/ports.ubuntu.com_ubuntu-ports_dists_trusty-security_main_i18n_Translation-en
                  MD5: 26367cfc3b23b21ad8b59e1f0974ff45

2.4.52-1 (/var/lib/apt/lists/ports.ubuntu.com_ubuntu-ports_dists_trusty_main_binary-armhf_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/ports.ubuntu.com_ubuntu-ports_dists_trusty-security_main_binary-armhf_Packages
                  MD5: 26367cfc3b23b21ad8b59e1f0974ff45
 Description Language: en
                 File: /var/lib/apt/lists/ports.ubuntu.com_ubuntu-ports_dists_trusty-security_main_i18n_Translation-en
                  MD5: 26367cfc3b23b21ad8b59e1f0974ff45


Reverse Depends: 
  linux-libc-dev:i386,libdrm-dev
  mesa-common-dev,libdrm-dev 2.4.52
  linux-libc-dev,libdrm-dev
  libgl1-mesa-dev,libdrm-dev 2.4.52
  libegl1-mesa-dev,libdrm-dev 2.4.52
  libcogl-pango-dev,libdrm-dev
  libcogl-dev,libdrm-dev
  libclutter-1.0-dev,libdrm-dev
  mesa-common-dev-lts-utopic,libdrm-dev 2.4.52
  linux-libc-dev,libdrm-dev
  libgl1-mesa-dev-lts-utopic,libdrm-dev 2.4.52
  libegl1-mesa-dev-lts-utopic,libdrm-dev 2.4.52
Dependencies: 
2.4.56-1~ubuntu2 - libdrm2 (5 2.4.56-1~ubuntu2) libdrm-radeon1 (5 2.4.56-1~ubuntu2) libdrm-nouveau2 (5 2.4.56-1~ubuntu2) libdrm-omap1 (5 2.4.56-1~ubuntu2) libdrm-freedreno1 (5 2.4.56-1~ubuntu2) libdrm-exynos1 (5 2.4.56-1~ubuntu2) linux-libc-dev (3 2.6.32-10) linux-libc-dev:i386 (3 2.6.32-10) 
2.4.52-1 - libdrm2 (5 2.4.52-1) libdrm-radeon1 (5 2.4.52-1) libdrm-nouveau2 (5 2.4.52-1) libdrm-omap1 (5 2.4.52-1) linux-libc-dev (3 2.6.32-10) linux-libc-dev:i386 (3 2.6.32-10) 
Provides: 
2.4.56-1~ubuntu2 - 
2.4.52-1 - 
Reverse Provides: 

It doesn't look like 2.4.60-2 is installed.

Output of sudo apt-get install libdrm-dev=2.4.60-2~ubuntu14.04.1

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '2.4.60-2~ubuntu14.04.1' for 'libdrm-dev' was not found

Also, thanks for your help, your responses aren't slow :)

**Comment by tista500** [comment]
Ughhh :(

I don't know why current version could not be searched from anywhere...
First, please check your own `/etc/apt/sources.list`, mine's here:
```
deb http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-proposed main restricted universe multiverse
```
(You can check them by replacing "xenial" with "trusty", and proposed repo is usually unlisted as default, so skip the final line...)

If there is not huge differences, then try this:
```
sudo apt-get clean
sudo apt-get update
sudo apt-get dist-upgrade
```

Regards.

**Comment by TheWiseYoda** [comment]
**/etc/apt/sources.list**
deb http://uk.old-releases.ubuntu.com/ubuntu/ trusty main restricted universe multiverse
deb-src http://uk.old-releases.ubuntu.com/ubuntu/ trusty main restricted universe multiverse
deb http://uk.old-releases.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse
deb-src http://uk.old-releases.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ trusty-security main restricted universe multiverse
deb-src http://uk.old-releases.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ trusty main universe restricted multiverse

**No response when running sudo apt-get clean**

**Output of sudo apt-get update**
Err http://uk.old-releases.ubuntu.com trusty InRelease
  
Err http://uk.old-releases.ubuntu.com trusty-updates InRelease
  
Err http://uk.old-releases.ubuntu.com trusty-security InRelease
  
Err http://uk.old-releases.ubuntu.com trusty Release.gpg
  Could not resolve 'uk.old-releases.ubuntu.com'
Err http://uk.old-releases.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'uk.old-releases.ubuntu.com'
Err http://uk.old-releases.ubuntu.com trusty-security Release.gpg
  Could not resolve 'uk.old-releases.ubuntu.com'
Hit http://ports.ubuntu.com trusty-security InRelease
Hit http://ppa.launchpad.net trusty InRelease 
Ign http://ports.ubuntu.com trusty InRelease     
Hit http://ports.ubuntu.com trusty-security/main armhf Packages
Hit http://ppa.launchpad.net trusty/main Sources
Hit http://ports.ubuntu.com trusty-security/restricted armhf Packages
Hit http://ppa.launchpad.net trusty/main armhf Packages
Hit http://ports.ubuntu.com trusty-security/universe armhf Packages
Hit http://ppa.launchpad.net trusty/main i386 Packages
Hit http://ports.ubuntu.com trusty-security/multiverse armhf Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ports.ubuntu.com trusty-security/main Translation-en
Hit http://ports.ubuntu.com trusty-security/multiverse Translation-en
Hit http://ports.ubuntu.com trusty-security/restricted Translation-en
Hit http://ports.ubuntu.com trusty-security/universe Translation-en
Hit http://ports.ubuntu.com trusty Release.gpg    
Hit http://ports.ubuntu.com trusty Release
Err http://ports.ubuntu.com trusty-security/main i386 Packages
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com trusty-security/restricted i386 Packages
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com trusty-security/universe i386 Packages
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com trusty-security/multiverse i386 Packages
  404  Not Found [IP: 91.189.88.151 80]
Hit http://ports.ubuntu.com trusty/main armhf Packages
Hit http://ports.ubuntu.com trusty/universe armhf Packages
Hit http://ports.ubuntu.com trusty/restricted armhf Packages
Hit http://ports.ubuntu.com trusty/multiverse armhf Packages
Hit http://ports.ubuntu.com trusty/main Translation-en                         
Hit http://ports.ubuntu.com trusty/multiverse Translation-en                   
Hit http://ports.ubuntu.com trusty/restricted Translation-en                   
Hit http://ports.ubuntu.com trusty/universe Translation-en                     
Err http://ports.ubuntu.com trusty/main i386 Packages                          
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com trusty/universe i386 Packages                      
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com trusty/restricted i386 Packages                    
  404  Not Found [IP: 91.189.88.151 80]
Err http://ports.ubuntu.com trusty/multiverse i386 Packages                    
  404  Not Found [IP: 91.189.88.151 80]
Reading package lists... Done                                                  
W: Failed to fetch http://uk.old-releases.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://uk.old-releases.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://uk.old-releases.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://uk.old-releases.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'uk.old-releases.ubuntu.com'

W: Failed to fetch http://uk.old-releases.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'uk.old-releases.ubuntu.com'

W: Failed to fetch http://uk.old-releases.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'uk.old-releases.ubuntu.com'

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty-security/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty-security/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty-security/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty-security/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty/universe/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/trusty/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.88.151 80]

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Output of sudo apt-get dist-upgrade**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tista500** [comment]
Ah, that's the problem in your sources.list...

So try this:
```
sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
sudo sed -i -e 's@http://uk.old-releases.ubuntu.com/ubuntu/@http://ports.ubuntu.com/ubuntu-ports/@g' /etc/apt/sources.list
sudo apt-get clean
sudo apt-get update
sudo apt-get dist-upgrade -y
```
And then retry updating crouton...

Regards.

**Comment by TheWiseYoda** [comment]
@tista500 

That worked, thank you. Crouton updated. A somewhat new problem is that VLC and QupZilla won't start when I open them. Other programs like libreoffice do. Do you know what might be wrong? thanks

**Comment by tista500** [comment]
@TheWiseYoda,

OK. I think you should just close this issue at first, and then file a new issue of your current problem. Because your last comment seems completely independent from the original issue/title...

And I'm sorry Qt related issues are not my things to be able to help you guys since I'm really far from Qt apps and K desktop environment, so someone could help you I hope...

Regards.

**Comment by TheWiseYoda** [comment]
@tista500 

All right, thanks a lot for all of your help :)
