### ISSUE TITLE
How to use edit-chroot -c CHROOTS (for changing chroot dir)

### ISSUE THREAD

**Issue by liamhetkoekie** [dnschneid/crouton#2386]
I don't know how to use the command.

**Comment by DennisLfromGA** [comment]
@liamhetkoekie - Please refer to the answer I gave you for a similar question here https://github.com/dnschneid/crouton/issues/960#issuecomment-174312063. 
Also, you can take a look at the other replies in that thread for a lot of good info. in general.

**Comment by DennisLfromGA** [comment]
Also, this issue can probably be closed.
