### ISSUE TITLE
Failed to complete chroot setup

### ISSUE THREAD

**Issue by kims923** [dnschneid/crouton#2389]
I tried to install linux last night, it finished and my computer froze when the system ask for username in the terminal. So i tried to reinstall it  and now im stucked. It always said " Failed to complete chroot set up". 

Installing crash_reporter_wrapper into the host...
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

and 

Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by Linux-Distros** [comment]
This issue is being reviewed, #2387

**Comment by DamianRuBlue** [comment]
It was working fine for me since new years.

**Comment by Linux-Distros** [comment]
It Might Be Due To The File Not Being In Mirrors.kernel.org/debian

**Comment by Linux-Distros** [comment]
Or An Issue With The Website

**Comment by DamianRuBlue** [comment]
How do I fix that?

**Comment by Sulfyre** [comment]
I have the same issue and have been trying to get rid of it to no avail.
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

Plz help!!

**Comment by RastaManKing** [comment]
i can replicate this problem, installed fine a week ago, today i tried three times through the day and keep getting this error, help is greatly appreciated.

**Comment by DennisLfromGA** [comment]
This issue is being tracked here: https://github.com/dnschneid/crouton/issues/2387#issuecomment-174343219
It'd probably be best to close this issue to better concentrate everyone's efforts there.
