### ISSUE TITLE
The File is broken everytime I Download it

### ISSUE THREAD

**Issue by masterpaper** [dnschneid/crouton#2390]
The owner of this needs to check all the files somthing wrong with this It used to work all the time for me And I downloaded this 6 times and still said the file was broken I tryed updating the chroot and nothing it said that was broken too. It said Failed to complete chroot setup. Also it said /mnt/stateful_partition/crouton/chroots/precise doesn't appear to be a valid chroot. plz help

**Comment by qrkourier** [comment]
[upstream is currently broken](https://github.com/dnschneid/crouton/issues/2387)
