### ISSUE TITLE
Dev_boot_legacy=1 Beeping sounds when CTRL+L

### ISSUE THREAD

**Issue by kims923** [dnschneid/crouton#2391]
After crouton is not working, so i tried Chrumuntu, but now im stuck because the legacy boot is not working. I tried to do the sudo crossystem dev_boot_legacy=1 but when i check crossystem it shows that Dev_boot_legacy=error

**Comment by Linux-Distros** [comment]
try powerwashing to see if it works

**Comment by kims923** [comment]
tried it already. btw when i try CTRL+I(i) it said Dev_boot_legacy=1 on the booting screen

**Comment by Linux-Distros** [comment]
Weird

**Comment by kims923** [comment]
i will try to reinstall Chrubuntu. btw have you guys dfound a solution for the crouton? @Linux-Distros

**Comment by Linux-Distros** [comment]
@kims923 no

**Comment by kims923** [comment]
same thing. in Dev console Dev_boot_legacy=error but CTRL+i Dev_boot_legacy=1 and CTRL+L results beep sounds

**Comment by kims923** [comment]
@Linux-Distros ok i kinda fingure it out. I use Chronos = error but it shows as 1 when i use root. But still beeping when i try CTRL+L

**Comment by Linux-Distros** [comment]
might have to disable the rootfs on the boot partition

**Comment by kims923** [comment]
how to do it?? im pretty new to linux

**Comment by Linux-Distros** [comment]
do you have a chromebook with a bios screw?

**Comment by kims923** [comment]
I dont know.. even usb doesnt boot

**Comment by kims923** [comment]
help...

**Comment by DennisLfromGA** [comment]
This topic does *not* pertain to crouton, please close this issue and discuss it elsewhere.
