### ISSUE TITLE
Debootstrap Error Still...

### ISSUE THREAD

**Issue by Linux-Distros** [dnschneid/crouton#2397]
I Used Drinkcats Methods To Fix It And Now When I Try Downloading I Get

I Running The Command
chronos@localhost / $ sudo sh ~/Downloads/crouton -r vivid -t xfce-desktop,audio,core,x11,keyboard,extension -n xfce-main

Installing vivid-armhf chroot to /usr/local/chroots/xfce-main
Downloading debootstrap 1.0.75...
2016-01-25 06:55:57 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=1.0.75;sf=tgz [63296] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
E: Error executing gpgv to check Release signature

Please Help ASAP

**Comment by OkoWsc** [comment]
Do you get an error trying to install trusty? I had last nights error as well, now resolved and i have Trusty installed with XiWi?

**Comment by Linux-Distros** [comment]
same with trusty

**Comment by Linux-Distros** [comment]
i wiped the install cache and had no chroots to delete. Why isnt it working for me

**Comment by OkoWsc** [comment]
Can you do sudo sh ~/Downloads/crouton -t xfce?

**Comment by OkoWsc** [comment]
(i think that defaults to precise)

**Comment by Linux-Distros** [comment]
nope still same error

**Comment by Linux-Distros** [comment]
This Is The Error ![screenshot 2016-01-25 at 7 22 21 am](https://cloud.githubusercontent.com/assets/16448605/12550862/6ad34480-c334-11e5-9072-9cda2b626c8f.png)

**Comment by OkoWsc** [comment]
mayby in trying to fix last nights error you caused another one? I would try deleting the crouton download, re downloading and trying again. 


Failing that, powerwash.

**Comment by Linux-Distros** [comment]
Ok I Already Tried Deleting The File SO Ill Powerwash

**Comment by OkoWsc** [comment]
(make sure you take a backup of anything important in your downloads folder first)

**Comment by Linux-Distros** [comment]
I Dont Have Anything Important There XD

**Comment by Linux-Distros** [comment]
Ok Be Back soon

**Comment by Linux-Distros** [comment]
Nope Powerwashing didn't fix it

**Comment by Linux-Distros** [comment]
Stupid Problems..

**Comment by drinkcat** [comment]
Alright, can we not start any centithread here? This is not a chat, nor a random discussion forum. If you want to have us looking at your issues, please stay on the topic, and limit the chatter to the necessary. Thanks!

**Comment by Linux-Distros** [comment]
Your Fix Has Not Fixed My Crouton @drinkcat

**Comment by drinkcat** [comment]
In the snapshot, I see that your rootfs is writable, is that still the case after powerwash?

**Comment by Linux-Distros** [comment]
no

**Comment by Linux-Distros** [comment]
wait i mean yes

**Comment by Linux-Distros** [comment]
my boot partition is selected

**Comment by drinkcat** [comment]
Do you get the "WARNING: Your rootfs is writable" warning, or not?

**Comment by Linux-Distros** [comment]
yes

**Comment by drinkcat** [comment]
alright, do you have any idea what you did to the rootfs? If not I suggest that you follow the advise on the following line.

**Comment by Linux-Distros** [comment]
no, i just enabled it to see what it would do, but it did nothing

**Comment by drinkcat** [comment]
Not even this? https://github.com/dnschneid/crouton/issues/2387#issuecomment-174339655

**Comment by drinkcat** [comment]
Anyway, just recover from USB. https://support.google.com/chromebook/answer/1080595?hl=en

**Comment by dnschneid** [comment]
Recovering from USB will definitely fix this particular problem of yours.

**Comment by DennisLfromGA** [comment]
@drinkcat, @dnschneid,  
This has me a little concerned, do the recent fixes preclude having your rootfs r-w ?
Just wondering because I put things in `/etc/init` to [mount CROUTON and autostart chroots](https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup).

**Comment by dnschneid** [comment]
Nope, OP just moved a file (the keyring) into a place that confused debootstrap.

**Comment by DennisLfromGA** [comment]
Okay, thanx. Sorry for the unwarranted panicking. ;-)
