### ISSUE TITLE
Fedora 23 support

### ISSUE THREAD

**Issue by nmilosev** [dnschneid/crouton#2398]
First of all, thank you thank you thank you for this project. You are all great guys and I love you all. :)

Just wanted to let you know that I've managed to get Fedora 23 to work with Crouton and wrote about it on my blog here:

http://nmilosev.svbtle.com/crouton-with-fedora-chroot-chromebook

All the code is there, but sadly I don't think it can be merged and it's really ugly. I will try to keep it updated with new versions for as much as I can. I only got my Chromebook 2 days ago, and already I'm loving it!

Again thank you so much @dnschneid and the rest of you guys for this wonderful software.

Have a great day, cheers!
-Nemanja

**Comment by nmilosev** [comment]
Hello all, a small update! :)

Since my last writing here, I've updated my version of the script. It no longer depends on the Fedora 20 as a base and therefore installs much faster. You can read all about it here:

http://nmilosev.svbtle.com/crouton-with-fedora-chroot-2-0

I've also made a small chrome app which uses noVNC to connect to the local VNC server running inside Fedora 23 chroot. (There is even a GIF of it in action, yay!)

http://nmilosev.svbtle.com/fedora-crouton-connector-chrome-app

Anyway I need your help... Can somebody please just point me in the right direction of completely passing this VNC stuff and connecting to the local X server? If I understand correctly, the X server is gone in newer ChromeOS versions because Freon has replaced it? Where can I find about Freon? And can I "override" the tty I'm seeing when I press CTRL ALT and arrow keys? Is there a way for me to integrate with xiwi? Just a nudge in a right direction would be great! The VNC server works fine and CPU usage isn't that bad (4-5% in idle) but I would love to just go the proper way of doing it.

Thank you all in advance!

And a quick info about my modified script, I can somehow run Fedora with really minimal modification to the original Crouton scripts, so a version which could be merged is maybe possible. However it will require a lot of work, which is something I'm not sure I could do alone... Especially when there is so little interest for an RPM distro in Crouton.

Anyway, thank you again and I really hope somebody can help me with the X stuff.

Cheers!

**Comment by tedm** [comment]
That is cool! Is VNC faster than it used to be to connect to chroot GUIs?

**Comment by nmilosev** [comment]
It's really fast, I don't know how was it before, but it takes less than a second to load and is very very responsive afterwards. You can get it to work even faster if you play with the VNC client settings for compression and check rate. For video and graphics stuff it sucks obviously, but for what I'm mostly using it (IntelliJ Idea) it works great! I'm using TigerVNC from the fedora repository, for the record. CPU usage is from 5-10% mostly from rendering it in Chrome app. I would to have full X display though, but the more I'm reading about it, the more impossible it seems. :(

**Comment by nmilosev** [comment]
Well, seems like impossible is nothing. 

![Imgur](http://i.imgur.com/J9RzbVo.jpg)

I've used the compiled croutonfreon.so because it was easier for me.

```sudo DBUS_SYSTEM_BUS_ADDRESS='unix:path=/var/host/dbus/system_bus_socket' LD_PRELOAD='/usr/local/lib/croutonfreon.so' XARGS='-nolisten tcp' croutonpowerd -i startx :1```

I've decided to put my code to GitHub since it is much easier to read, and it can be probably used to port any distribution to Crouton since it is very generic. The repository is here:

https://github.com/nmilosev/crouton-fedora

Yay for my first repo, directly from the Fedora chroot. :)

I wasn't sure if I needed to sign the CLA so I did it anyway. Thanks again to the authors, it's been one hell of a ride to run this but so worth it. I will update this with every big Fedora release. 

Till then.

**Comment by dnschneid** [comment]
This is an awesome effort.  Great job in getting it working!

Now that you have a stable baseline, do you have any interest in working towards something mergeable?

**Comment by nmilosev** [comment]
Hello, and thanks for replying!

I will continue to work on this in my spare time, and I can see it as being mergeable in the future. However it is a very distant future. It's definitely top priority to get this fully 100% compatible with the main Crouton installer. I've only had my chromebook for a week now so I'm still not very familiar with ChromeOS and scripting but I will keep learning since it is a very nice platform to work on. So in short, I will try to make it prettier as much as I can so it can be merged one day. :)

I have to thank you again for Crouton, this is awesome work.

Cheers!

**Comment by dnschneid** [comment]
Great!  Looking forward to hearing about your progress.  If you have any questions, feel free to ask here or on #crouton-devel

**Comment by Asuza** [comment]
Wow, this is impressive stuff! Is it possible to use this Fedora crouton on a USB stick while still using the main crouton? (I can move my questions to to @nmilosev's Github repo if that's preferred). I don't want to break what I have now.

**Comment by nmilosev** [comment]
Of course you can. 

To have it your USB, you have to format the drive with the ext4 are tun the installer with something like this: ```-p /media/removable/your-usb-label/``` and it will install onto the USB as normal Crouton does. Afterwards run it with ```sudo sh /media/removable/your-usb-label/bin/enter-chroot``` and it will work. I'm running it the other way around at the moment (Debian on USB, Fedora on default) and both versions work fine. :)

**Comment by Conan-Kudo** [comment]
@nmilosev Since you've been keeping up with the crouton fedora support in your fork, have you considered merging it into mainline Crouton?
