### ISSUE TITLE
Trying to install mysql-server properly.

### ISSUE THREAD

**Issue by Guo-William** [dnschneid/crouton#2399]
I have IPtables installed and have set `/sbin/iptables -P INPUT ACCEPT.`
Then I did `sudo apt-get install mysql-server`
when I try `mysql -u root -p`
I get `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

I've already looked at https://github.com/dnschneid/crouton/issues/2382
I also know I don't actually have a mysqld.sock in /var/run/mysqld/
I also have added the necessary lines to `rc.local` but that has started to give me an error upon getting into chroot `error 127`

**Comment by DavidMcLaughlin29** [comment]
I have this problem, too.
