### ISSUE TITLE
Cannot get additional shares from /etc/crouton/shares

### ISSUE THREAD

**Issue by raygeeknyc** [dnschneid/crouton#2400]
Hi
 I am trying to export my ~/Documents directorys so that I can open files contained therein from my Chrone browser
I added "documents ~/Documents" to /etc/crouton/shares
but when the chroot starts it tells me "invalid share"
So I did some experiments and cannot get *anything* exported :(
Back to square one, try the examples.
I've tried adding
shared /mnt/stateful_partition/crouton/shared
after mkdir -p of that directory, but this doesn't show up in Chrome either.
Can you help or provide me with more of an explanation as to what can be shared?

Thanks

**Comment by DennisLfromGA** [comment]
@raygeeknyc,

**"The `/etc/crouton/shares` file in your chroot defines directories to map *into* the chroot from the host."** 

The operative word there is 'into' the chroot. There is currently no supported 'crouton' way to map directories into Chrome OS from the chroot. See this wiki page for more info. - [Sharing files and folders](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders)
You *may* be able to achieve it with bind-mounts, etc. but I haven't done it nor put a whole lot of effort into doing it either.

----
However, using the Chrome OS '**Files**' app, you can select '*Add new services*' and choose '*SFTP File System*' for access *into* your chroot.
You need to install the openssh-server package in your chroot first and add a few lines to your `/etc/rc.local` file to open up the firewall and start the ssh daemon for this to work. See this wiki page for pointers - [Running servers in crouton](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton#openssh-server).

I have it setup in my 'trusty' chroot and it works just fine -
![screenshot 2016-01-25 at 5 52 17 pm](https://cloud.githubusercontent.com/assets/3418772/12568152/b07f6362-c391-11e5-91cd-985127df8cef.png)

-**DennyL**

**Comment by raygeeknyc** [comment]
Ah ha!  Thanks much

**Comment by DennisLfromGA** [comment]
*Glad I could help*.

**Comment by divx118** [comment]
FYI bindmounts will work when you use it on external media, but not on
directories in ~/Downloads.

**Comment by raygeeknyc** [comment]
Thanks. FYI sftp is working for me flawlessly.

**Comment by raygeeknyc** [comment]
I thought it was a violation of the entire point of a jail to expose arbitrary internal paths, but I was overcome by the scent of an easy fix.  :)
