### ISSUE TITLE
Wily+Gnome support

### ISSUE THREAD

**Issue by fennexin** [dnschneid/crouton#2402]
I tried to install Wily and Gnome, and I got a gnome-fallback-error. I would send a screenshot of some sort, but right when it showed that the chroot setup failed, my keyboard was disabled. I had to restart.

**Comment by tista500** [comment]
@fennexin,

Please read details in here: #1689.
That pull-request is still "pending" to merge into master so, you can do it yourself...

Regards.

**Comment by Voronsky** [comment]
@fennexin I have updated my work and attempt in #1689, if you haven't already fixed the problem yourself, perhaps my approach may give you an idea as to how to solve the problem temporarily until this issue is permanently resolved.
