### ISSUE TITLE
Can't reinstall xfce

### ISSUE THREAD

**Issue by carljohan** [dnschneid/crouton#2403]
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t xfce
Downloading latest crouton installer...
###### ################################################################## 100.0%

/usr/local/chroots/precise already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.
chronos@localhost / $

How do I delete the file?

**Comment by divx118** [comment]
`sudo delete-chroot precise`
