### ISSUE TITLE
sudo staartxfce4 has error (EE) The '-logfile' option cannot be used with elevated privileges.

### ISSUE THREAD

**Issue by fishfishfish2104** [dnschneid/crouton#2405]
when i try to sudo startxfce4 this happens 
![screenshot 2016-01-28 at 12 42 38 pm](https://cloud.githubusercontent.com/assets/16485618/12632423/a924d61a-c5bc-11e5-807a-e94c7b29dc7e.png)

**Comment by fishfishfish2104** [comment]
after that it just dosn't do anything dosn't quit untill I crtl c

**Comment by gconz** [comment]
Same thing for me.  It is a kali linux chroot that was working until I updated packages.

**Comment by gconz** [comment]
I did find that if i edited this file: /etc/crouton/xserverrc-xiwi
And commented this line: #XARGS="-nolisten tcp -config xorg-dummy.conf -logfile $logfile"
And added this: XARGS="-nolisten tcp -config xorg-dummy.conf"
X11 would start.  Not sure the remifications of turning off logging like this, though.

**Comment by GITHUBEROI** [comment]
That happens to me also, but I only get 2 (EE)

**Comment by msdos41** [comment]
I have the same problem. Is there a solution?

/etc/crouton/xserverrc-xiwi   the file does not exist.

I am confused.

**Comment by ikeahloe** [comment]
also affects me on xenial after some ubuntu OS updates.

**Comment by dnschneid** [comment]
#2875
