### ISSUE TITLE
Restoring Chroot.tar.gz from SD Card

### ISSUE THREAD

**Issue by sodakill420** [dnschneid/crouton#2408]
Hello, i know this has been posted before, but i am having problems restoring it from my SD card.

I backed up the chroot to /media/removable/UNTITLED
and when i try to restore it with edit-chroot it says
"Command edit-chroot not found"

Also i have tried using other peoples methods of restoring chroot but all it says is "Cant open crouton"
I saw something about having to get the latest installer? but i wasnt sure.
Sorry im new at this :)

**Comment by sodakill420** [comment]
when ever i run 
sudo sh ~/Downloads/crouton -n precise -p /media/removable/UNTITLED -u 
it shows :
 /media/removable/UNTITLED/chroots not found.
/media/removable/UNTITLED/chroots/precise does not exist; cannot update.
Valid chroots:

but i have the Tar.gz on my sd card.?

**Comment by DennisLfromGA** [comment]
@sodakill420,

You can restore a chroot from a backup tarball with `crouton` itself, you don't actually *need* to do it with `edit-chroot`. If you want to restore your chroot back to `/usr/local/chroots`, the default, then you would use something like:

`sudo sh ~/Downloads/crouton -f /media/removable/UNTITLED/Chroot.tar.gz`

Replace the `Chroot.tar.gz` part with your actual backup tarball name if that's not correct.

----
I'm not sure why the edit-chroot command was not found, did you powerwash or do something to delete crouton's host-bin commands? Whatever the case, after you restore your chroot using the above procedure, you can then restore all the host-bin files that would normally accompany your chroot[s] with:

`sudo sh ~/Downloads/crouton -b`

-**DennisL**

**Comment by sodakill420** [comment]
Thank you! thats what i was looking for i do believe i will try this now!

**Comment by sodakill420** [comment]
yes this worked thank you!

**Comment by DennisLfromGA** [comment]
You're very welcome, glad it all worked out.
( you can probably close this issue now too )
