### ISSUE TITLE
Very slow scrolling in vertical split screen

### ISSUE THREAD

**Issue by cnshenyi** [dnschneid/crouton#2409]
I‘ve installed crouton in my asus c201 chromebook with a arm cpu(RK3288).
When I scroll in vim using j, k or mouse wheel it is very responsive and fast, but as soon as I open a new buffer in vertical split screen scrolling becomes very slow/delayed. It manly occurs in very large files (1000+ Lines), even if the second buffer in split screen is empty.
If I open just one file plus NERDTree and change the layout to horizontal split, the scrolling is also fast.

**Comment by cnshenyi** [comment]
ps. I‘m in CLI（using enter-chroot )，when I use startxfce4，in the terminal emulator, it's fine.

**Comment by dnschneid** [comment]
You're running into [crbug.com/527475](crbug.com/527475).  Fortunately, it looks like they're fixing it.
