### ISSUE TITLE
Wily unity issue

### ISSUE THREAD

**Issue by budnik** [dnschneid/crouton#2412]
Hi, I just tried to install `wily` on `pixel` on ext4 formated SD card. It almost works As I see desktop and I'm able to create folder with nautilus but that's all. I don't have any other UI panels or whatever. I'm also unable to run terminal from context menu:
![20160201_185825](https://cloud.githubusercontent.com/assets/1160699/12724415/91f0dea0-c916-11e5-9e36-0bfbac5935f9.jpg)
After when I switch back to chromeOS windows decoration is missing:
![20160201_190604](https://cloud.githubusercontent.com/assets/1160699/12724485/e154632c-c916-11e5-9f47-e51854d8252a.jpg)

Here's part of console output that seem relevant
```
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Feb  1 18:57:45 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20160125112815~b78906bc
release: wily
architecture: amd64
xmethod: xorg
targets: unity-desktop,touch,keyboard,chrome-beta
host: version 7647.73.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jan 24 13:51:22 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
```

I know that `wily` is not officialy supported. But I wonder if there is a way I can debug\fix it?

**Comment by tista500** [comment]
@budnik,

This issue is a duplicate of this issue (maybe): #2144
If so, could you please close this and file your issue to the original one?

Regards.

**Comment by budnik** [comment]
Yes, indeed. I think that I don't need update original issue as your mention links this issue to original one.
