### ISSUE TITLE
crouton-xorg depend not installed

### ISSUE THREAD

**Issue by xuanirelia** [dnschneid/crouton#2413]
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 crouton-xorg : Depends: libglu1-mesa but it is not installed
                Depends: xfonts-base but it is not installed
                Depends: x11-apps but it is not installed
                Depends: x11-session-utils but it is not installed
                Depends: x11-utils but it is not installed
                Depends: x11-xfs-utils but it is not installed
                Depends: x11-xserver-utils but it is not installed
                Depends: xauth but it is not installed
                Depends: xinit but it is not installed
                Depends: xfonts-utils but it is not installed
                Depends: xorg-docs-core but it is not installed
                Depends: xterm but it is not installed
                Depends: xinput but it is not installed
E: Unmet dependencies. Try using -f.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by Linux-Distros** [comment]
could you be more specific? what command are you running to produce this error?

**Comment by xuanirelia** [comment]
chronos@localhost ~/Downloads/croutonforme $ sudo sh -e installer/main.sh -u
/usr/local/chroots/precise already exists; updating it...
installer/../installer/debian/getrelease.sh: 1: ../ubuntu/getrelease.sh: not found
installer/../installer/kali/getrelease.sh: 1: ../ubuntu/getrelease.sh: not found
WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
If this is a surprise to you, you should do a full system recovery via USB.
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Hit http://ports.ubuntu.com precise Release.gpg    
Hit http://ports.ubuntu.com precise-updates Release.gpg
Hit http://ports.ubuntu.com precise-security Release.gpg
Hit http://ports.ubuntu.com precise Release
Hit http://ports.ubuntu.com precise-updates Release
Hit http://ports.ubuntu.com precise-security Release
Hit http://ports.ubuntu.com precise/main Sources
Hit http://ports.ubuntu.com precise/restricted Sources
Hit http://ports.ubuntu.com precise/universe Sources
Hit http://ports.ubuntu.com precise/multiverse Sources
Hit http://ports.ubuntu.com precise/main armhf Packages
Hit http://ports.ubuntu.com precise/restricted armhf Packages
Hit http://ports.ubuntu.com precise/universe armhf Packages
Hit http://ports.ubuntu.com precise/multiverse armhf Packages
Hit http://ports.ubuntu.com precise/main TranslationIndex
Hit http://ports.ubuntu.com precise/multiverse TranslationIndex
Hit http://ports.ubuntu.com precise/restricted TranslationIndex
Hit http://ports.ubuntu.com precise/universe TranslationIndex
Hit http://ports.ubuntu.com precise-updates/main Sources
Hit http://ports.ubuntu.com precise-updates/restricted Sources
Hit http://ports.ubuntu.com precise-updates/universe Sources
Hit http://ports.ubuntu.com precise-updates/multiverse Sources
Hit http://ports.ubuntu.com precise-updates/main armhf Packages
Hit http://ports.ubuntu.com precise-updates/restricted armhf Packages
Hit http://ports.ubuntu.com precise-updates/universe armhf Packages
Hit http://ports.ubuntu.com precise-updates/multiverse armhf Packages
Hit http://ports.ubuntu.com precise-updates/main TranslationIndex
Hit http://ports.ubuntu.com precise-updates/multiverse TranslationIndex
Hit http://ports.ubuntu.com precise-updates/restricted TranslationIndex
Hit http://ports.ubuntu.com precise-updates/universe TranslationIndex
Hit http://ports.ubuntu.com precise-security/main Sources
Hit http://ports.ubuntu.com precise-security/restricted Sources
Hit http://ports.ubuntu.com precise-security/universe Sources
Hit http://ports.ubuntu.com precise-security/multiverse Sources
Hit http://ports.ubuntu.com precise-security/main armhf Packages
Hit http://ports.ubuntu.com precise-security/restricted armhf Packages
Hit http://ports.ubuntu.com precise-security/multiverse armhf Packages                                                                              
Hit http://ports.ubuntu.com precise-security/main TranslationIndex                                                                                  
Hit http://ports.ubuntu.com precise-security/multiverse TranslationIndex                                                                            
Hit http://ports.ubuntu.com precise-security/restricted TranslationIndex                                                                            
Hit http://ports.ubuntu.com precise-security/universe TranslationIndex                                                                              
Get:1 http://ports.ubuntu.com precise-security/universe armhf Packages [113 kB]                                                                     
Hit http://ports.ubuntu.com precise/main Translation-en                                                                                             
Hit http://ports.ubuntu.com precise/multiverse Translation-en                                                                                       
Hit http://ports.ubuntu.com precise/restricted Translation-en                                                                                       
Hit http://ports.ubuntu.com precise/universe Translation-en                                                                                         
Get:2 http://ports.ubuntu.com precise-updates/main Translation-en [411 kB]                                                                          
Hit http://ports.ubuntu.com precise-updates/multiverse Translation-en                                                                               
Hit http://ports.ubuntu.com precise-updates/restricted Translation-en                                                                               
Hit http://ports.ubuntu.com precise-updates/universe Translation-en                                                                                 
Hit http://ports.ubuntu.com precise-security/main Translation-en                                                                                    
Hit http://ports.ubuntu.com precise-security/multiverse Translation-en                                                                              
Hit http://ports.ubuntu.com precise-security/restricted Translation-en                                                                              
Hit http://ports.ubuntu.com precise-security/universe Translation-en                                                                                
Fetched 524 kB in 38s (13.7 kB/s)                                                                                                                   
Reading package lists... Done
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 crouton-xorg : Depends: libglu1-mesa but it is not installed
                Depends: xfonts-base but it is not installed
                Depends: x11-apps but it is not installed
                Depends: x11-session-utils but it is not installed
                Depends: x11-utils but it is not installed
                Depends: x11-xfs-utils but it is not installed
                Depends: x11-xserver-utils but it is not installed
                Depends: xauth but it is not installed
                Depends: xinit but it is not installed
                Depends: xfonts-utils but it is not installed
                Depends: xorg-docs-core but it is not installed
                Depends: xterm but it is not installed
                Depends: xinput but it is not installed
E: Unmet dependencies. Try using -f.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost ~/Downloads/croutonforme $ sudo enter-chroot -x
Entering /mnt/stateful_partition/crouton/chroots/precise...
# sudo apt-get install xiwi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xiwi
# root
/bin/sh: 2: root: not found
# sudo apt-get -f install xiwi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xiwi
# exit
suUnmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost ~/Downloads/croutonforme $ sudo startxiwi xterm
sudo: startxiwi: command not found
chronos@localhost ~/Downloads/croutonforme $

**Comment by DennisLfromGA** [comment]
@xuanirelia - I believe I ran into a similar problem when downloading and running crouton on my system. I think the problem stems from Chrome OS's zip doesn't restore symlinks so they're 'broken' and won't work. You can download a tarball instead of a zip by using the 'Copy link address' option of the zip. 
![screenshot 2016-02-02 at 2 30 03 pm](https://cloud.githubusercontent.com/assets/3418772/12761622/adffb2ee-c9b9-11e5-8170-9cd1bfa30b53.png)


Then paste it in as the url, and change the suffix to `.tar.gz` instead of `.zip`. 
![screenshot 2016-02-02 at 2 32 42 pm](https://cloud.githubusercontent.com/assets/3418772/12761684/f0a5bd50-c9b9-11e5-8f9c-ada7ba84bcfd.png)

Once downloaded, just untar it with:

`tar xvaf https://github.com/dnschneid/crouton/archive/master.tar.gz`

That has worked for me.
