### ISSUE TITLE
Something is messed up when I try to run, PLZ help :(

### ISSUE THREAD

**Issue by GITHUBEROI** [dnschneid/crouton#2414]

**Comment by DennisLfromGA** [comment]
What command are you trying to run?

**Comment by GITHUBEROI** [comment]
sudo startxfce4

**Comment by DennisLfromGA** [comment]
Please give us some more details so that we can help.
You can start by showing us the output of: `sudo edit-chroot -al`

**Comment by GITHUBEROI** [comment]
Ok

**Comment by GITHUBEROI** [comment]
I typed in sudo edit-chroot-al and it gave me this. name: precise 
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160125112815~b78906bc
release: precise
architecture: armhf 
xmethod: xorg 
targets: xfce 
host: version 7647.73.0 (Official Build) stable-channel veyron_speedy
kernel: Linux localhost 3.14.0 #1 SMP Sun Jan 24 12:57:39 PST 2016 armv7l armv7l armv7l GNU/Linux
Unmounting /mnt/stateful_partion/crouton/chroots/precise...

**Comment by tedm** [comment]
so what happens after you type sudo startxfce4 ? and are you typing it in a crtl-alt-T window, and then typing shell <enter> before the sudo startxfce4 ?

**Comment by GITHUBEROI** [comment]
I get 3 (EE)'s and it shuts down the sudo startxfce4 and nothing happens

**Comment by DennisLfromGA** [comment]
@GITHUBEROI - It's time to follow this troubleshooting guide: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

**Comment by GITHUBEROI** [comment]
I went to the website and did everything, but nothing worked. When I typed in sudo edit-chroot -a the only thing there was
precise
So I did sudo me /urs/local/chroots again I got 
precise
Then I typed in sudo sh ~/Downloads/crouton -n chrootname -u and I got 
/urs/local/chroots/chrootname does not exist; cannot update. 
Valid chroots:
precise
Then I tried sudo enter-chroot -n chrootname croutonversion and got
/mtn/stateful_partion/crouton/chroots/chrootname not found
I've been trying to fix this for 4 days and everything I've tryed didn't work Can I get a command or a code or some help PLEASE 
Nothing works and I'm ready to smash my chrome book in pieces

**Comment by DennisLfromGA** [comment]
@GITHUBEROI,

> Valid chroots:
precise

Your chroot's name is `precise` *not* `chrootname`.

To update your chroot, enter:

`sudo sh ~/Downloads/crouton -n precise -u`

Maybe spend some time with the [README](https://github.com/dnschneid/crouton/blob/master/README.md) and some other resources on this site and others. 

Note though that when it says 'chrootname' or [chrootname] you need to substitute that with your own 'valid' chrootname.

**Comment by GITHUBEROI** [comment]
Thank you
