### ISSUE TITLE
Can't read/write file-system on Chromebook (HELP)

### ISSUE THREAD

**Issue by FroZoneTechnology** [dnschneid/crouton#2415]
I am trying to be able to read/write the file-system on my chromebook to be able to install custom .ttf fonts. I have tried a few tutorials like disabling my rootfs_verification and rebooting and I still do not have the file-system access in the chromebook default "files" app. Please help me figure this out.

**Comment by firestar115** [comment]
Have you successfully disabled rootfs read-only?
