### ISSUE TITLE
Is the "3D Hardware acceleration" page out of date?

### ISSUE THREAD

**Issue by Asuza** [dnschneid/crouton#2416]
I've been using Debian (jessie) for a long while now, and it definitely has 3D Hardware Acceleration. I don't remember if I changed something to make it work or not, though. Regardless, I was wondering if there were other known distros that work with hardware acceleration that aren't listed on the wiki page (which was last updated in 2014).

Thanks!

**Comment by drinkcat** [comment]
yeah, it's quite out of date: https://github.com/dnschneid/crouton/wiki/3D-Hardware-acceleration
