### ISSUE TITLE
After upgrading to 14.04 LTS can't launch Chroot

### ISSUE THREAD

**Issue by ashtell** [dnschneid/crouton#2421]
I upgraded to 14.04 with XTerm, now when I try to re-launch I get this. Even after upgrading crouton. It tells me 

```
Entering /mnt/stateful_partition/crouton/chroots/precise...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d]
```

after I respond Y,
it goes through the setup process, and then this happens:

```
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160125112815~b78906bc
release: trusty
architecture: amd64
xmethod: xiwi
targets: unity,xiwi
host: version 7647.73.0 (Official Build) beta-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Sun Jan 24 13:12:37 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/precise...
```

what is wrong. How can I fix it. And how do I update to 14.04 correctly?

**Comment by mr-wong** [comment]
Maybe try make fresh install (crouton -r trusty), not upgrade from precise?

**Comment by ashtell** [comment]
Yes, that might work. the xiwi extension will work with that?

**Comment by ashtell** [comment]
so is it not possible to upgrade a chroot without it breaking?

**Comment by mr-wong** [comment]
@ashtell 

> Yes, that might work. the xiwi extension will work with that?
Hope yes, full cmd should be: crouton -r trusty -t xiwi (and whatever you need too)

> so is it not possible to upgrade a chroot without it breaking?
I dunno. I've assumed you're made fresh install of Precise, then trying to upgrade to Trusty inside chroot. This makes less sense than install Trusty initially.

Personally I disabled update engines both inside host and chroot and sticked to 12.04, since see no significant difference with newer distro versions.

**Comment by ashtell** [comment]
I didn't see that you could just install trusty right out of the gate. Im sort of new to this

**Comment by mr-wong** [comment]
@ashtell I am little familiar with Linux, but new to crouton too, especially for chroot-related things. Anyway, as stated in Help, crouton not fully supports Ubuntu distros other than Precise. My intuition tells that such tricks like upgrade major version inside chroot might not work. Try to delete chroot, then install via "-r" option or just stay with 12.04 (I briefly looked for comparison tests and didn't find any advantages).

**Comment by ashtell** [comment]
yeah, I installed trusty, but it was really glitchy and slow, so I think Ill just stay with precise.

**Comment by DennisLfromGA** [comment]
> Anyway, as stated in Help, crouton not fully supports Ubuntu distros other than Precise.

Actually, several releases are 'supported', note those *without* an asterisk below -
```
Recognized debian releases:
    potato* woody* sarge* etch* lenny* squeeze* wheezy jessie stretch sid
Recognized kali releases:
    kali* sana
Recognized ubuntu releases:
    warty* hoary* breezy* dapper* edgy* feisty* gutsy* hardy* intrepid* jaunty*
    karmic* lucid* maverick* natty* oneiric* precise quantal* raring* saucy*
    trusty utopic* vivid* wily* xenial*
```
**Releases marked with * are unsupported, but may work with some effort.**

**Comment by ashtell** [comment]
Just because it is "supported" doesn't mean its going to work as it should.

**Comment by DennisLfromGA** [comment]
@ashtell - True indeed but just because you install 'precise' doesn't mean that it will work as it should either. Knowing that it's supported means that you get can help more readily here and elsewhere.

**Comment by ashtell** [comment]
ok, I understand. it was just really slow and glitchy.

**Comment by bemcfarland** [comment]
Just upgraded precise inside existing chroot and xserver is broken.  Seems that is a terminal flaw and no upgrades are possible.  Too bad . . . .

**Comment by ashtell** [comment]
We should get that fixed. Ill look into it a little bit
