### ISSUE TITLE
12.04 Enviornment switchin issue

### ISSUE THREAD

**Issue by user4a50** [dnschneid/crouton#2425]
I did all of the update steps on the guidelines and have looked at other issues, no errors with the updating. 

I'm running precise with xfce on a samsung chromebook. Every time I enter crosh and launch the environment, it initially allows me to switch back and forth with the ctrl-alt-shift-back/forward command, but if I close the crosh shell, I can't switch. 

**Exact command I ran in shell:** `sudo startxfce4`

**Exact output:**
`Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Jan 24 10:55:46 PST 2016 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=ea5979c7-9715-374d-8546-19b0b66c0399/PARTNROFF=1 hashtree=PARTUUID=ea5979c7-9715-374d-8546-19b0b66c0399/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b04af99a3f831eb997600d3725c6b55e83b60fed salt=85da75cabbb12fbd22c707fe5b5f4063f4af2380360c9576d5b096c581c65c63" noinitrd vt.global_cursor_default=0 kern_guid=ea5979c7-9715-374d-8546-19b0b66c0399  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Feb  7 13:34:47 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 7647.73.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jan 24 10:55:46 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
No Chromium OS X server is available.
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
xfdesktop[30332]: starting up

(polkit-gnome-authentication-agent-1:30342): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:30342): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfce4-settings-helper:30347): xfce4-settings-helper-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.`

**The output of `sudo enter-chroot -n precise croutonversion`**

`Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 7647.73.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jan 24 10:55:46 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...`

Thanks

**Comment by user4a50** [comment]
Sorry about the formatting I pressed the insert code button for all of the inputs/outputs, not sure what happened.

**Comment by DennisLfromGA** [comment]
@user4a50 - This is not a solution for your key combo problem but you can switch back to Chrome OS from a chroot shell terminal by entering: `croutoncycle cros`
