### ISSUE TITLE
Fatal Server error: no screens found, crouton on Asus Flip Chromebook

### ISSUE THREAD

**Issue by Stretholox** [dnschneid/crouton#2426]
[  2113.376] (WW) Warning, couldn't open module fbdev
[  2113.376] (II) UnloadModule: "fbdev"
[  2113.376] (II) Unloading fbdev
[  2113.376] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  2113.376] (==) Matched modesetting as autoconfigured driver 0
[  2113.376] (==) Matched fbdev as autoconfigured driver 1
[  2113.376] (==) Assigned the driver to the xf86ConfigLayout
[  2113.376] (II) LoadModule: "modesetting"
[  2113.376] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  2113.377] (II) Module modesetting: vendor="X.Org Foundation"
[  2113.377] 	compiled for 1.13.0, module version = 0.5.0
[  2113.377] 	Module class: X.Org Video Driver
[  2113.377] 	ABI class: X.Org Video Driver, version 13.0
[  2113.377] (II) UnloadModule: "modesetting"
[  2113.377] (II) Unloading modesetting
[  2113.377] (II) Failed to load module "modesetting" (already loaded, -1201481512)
[  2113.377] (II) LoadModule: "fbdev"
[  2113.378] (WW) Warning, couldn't open module fbdev
[  2113.378] (II) UnloadModule: "fbdev"
[  2113.378] (II) Unloading fbdev
[  2113.378] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  2113.378] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  2113.378] (--) using VT number 7

[  2113.396] (WW) Falling back to old probe method for modesetting
[  2113.396] (II) modesetting(0): using default device
[  2113.396] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  2113.396] (II) modesetting(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[  2113.396] (==) modesetting(0): Depth 24, (--) framebuffer bpp 32
[  2113.396] (==) modesetting(0): RGB weight 888
[  2113.396] (==) modesetting(0): Default visual is TrueColor
[  2113.396] (II) modesetting(0): ShadowFB: preferred NO, enabled NO
[  2113.396] (EE) modesetting(0): KMS setup failed
[  2113.396] (II) UnloadModule: "modesetting"
[  2113.396] (EE) Screen(s) found, but none have a usable configuration.
[  2113.396] 
Fatal server error:
[  2113.396] no screens found
[  2113.396] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[  2113.397] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  2113.397] (EE) 
[  2113.413] Server terminated with error (1). Closing log file.

The error above occurs on sudo startxfce4 after installing Crouton. Not sure how to give version information because croutonversion doesn't seem to be an appropriate command. I used the most recent Crouton file on this page.

**Comment by tista500** [comment]
@Stretholox,

In a crosh window, run this and then post the output:
`sudo edit-chroot -al`

Regards.

**Comment by Stretholox** [comment]
ERROR: unknown command: Sudo.

**Comment by Stretholox** [comment]
I was probably supposed to do that after shell wasn't I. Here's the output.

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: armhf
xmethod: xorg
targets: touch,xfce
host: version 7647.73.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP Sun Jan 24 13:02:23 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by tista500** [comment]
@Stretholox,

Ah, I see.
In conclusion, our Flip can run freon with **modesetting** user-space driver (or specially compiled **armsoc** driver) instead of fbdev (debian seems slightly different though).

Here is the post I've provided sample xorg configuration file: https://github.com/dnschneid/crouton/issues/2424#issuecomment-180875613

That file should work for our Flip as well without any tweaks. And remember that modesetting driver today does not need renaming `/dev/dri/card0` tweaks anymore in Ubuntu, so please do not touch there (but armsoc still needs that)...

Regards.

**Comment by Stretholox** [comment]
What I am gather is that I need to edit a file within Crouton to use modesetting user-space driver instead of fbdev. Although, I am very new to this and I'm not exactly sure what to do. Could you walk me through the moving parts of the system. I'm just getting into Ubuntu, Crouton... well everything.

**Comment by tista500** [comment]
OK.

1. Download this file to your "Downloads" directory in ChromeOS:
[20-armsoc.txt](https://github.com/dnschneid/crouton/files/121172/20-armsoc.txt)

2. In crosh window, run `shell` command to launch bash-like shell
3. Rename downloaded file from `.txt` to `conf`:
  ```
cd ~/Downloads
mv 20-armsoc{.txt,.conf}
  ```

4. Login into chroot without X11:
  ```
sudo enter-chroot -n precise
  ```

5. Move that file into proper place and flush the RAM cache:
  ```
sudo mv ~/Downloads/20-armsoc.conf /usr/share/X11/xorg.conf.d/
sync
  ```

6. Logout chroot with "Ctrl + d" or run `exit` command
7. Re-login into chroot with X11/freon:

  ```
sudo startxfce4
```

That's all, maybe...

Regards.

**Comment by Stretholox** [comment]
At step 4.

/mnt/stateful_partition/crouton/chroots/-precise not found.

**Comment by tista500** [comment]
?? :(
Well, do this simply:
`sudo enter-chroot`

Regards.

**Comment by Stretholox** [comment]
I apologize on that previous error. I made a stupid mistake. 

chronos@localhost ~/Downloads $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Sun Jan 24 13:02:23 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cd4b8329-e0dc-754f-bc89-60343b427898/PARTNROFF=1 hashtree=PARTUUID=cd4b8329-e0dc-754f-bc89-60343b427898/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=5bc41b410469dae358e39400592001d074308568 salt=9a68f10c215d82ca9928f1efc868beada582b7030bf8c824a3da381ffa5f924f" noinitrd vt.global_cursor_default=0 kern_guid=cd4b8329-e0dc-754f-bc89-60343b427898  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Feb  8 11:17:34 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.

**Comment by Stretholox** [comment]
Its the same error as before.

**Comment by tista500** [comment]
@Stretholox,

Please post the `/tmp/Xorg.crouton.1.log` here as attachment...

Regards.

**Comment by Stretholox** [comment]
[Xorg.crouton.1_SP.pdf](https://github.com/dnschneid/crouton/files/121864/Xorg.crouton.1_SP.pdf)

**Comment by Stretholox** [comment]
crosh> shell
chronos@localhost / $ cd ~/Downloads mv 20-armsoc{.txt,.conf}
chronos@localhost ~/Downloads $ sudo enter-chroot -n precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)user@localhost:~$ sudo mv ~/Downloads/20-armsoc.conf /usr/share/X11/xorg.conf.d/sync
mv: cannot stat `/home/user/Downloads/20-armsoc.conf': No such file or directory
(precise)user@localhost:~$ sudo mv ~/Downlaods/20-armsoc.conf /user/share/X11/xorg.conf.d/sync
mv: cannot stat `/home/user/Downlaods/20-armsoc.conf': No such file or directory
(precise)user@localhost:~$

**Comment by tista500** [comment]
Oh wait..
1 command line needs 1 "enter" (or line-feed). can you understand this meaning?
Type `cd ~/Downloads` and hit Enter key.
Then type `mv 20-armsoc{.txt,.conf}` and hit Enter key.
....

Regards.

**Comment by Stretholox** [comment]
Cool. So that fixed the errors that said mv 20-armsoc.conf didn't exist and that /usr/share/X11/xorg.con.d didn't exist. But I'm still getting the main error after logging out and trying sudo startxfce4. 
[Xorg.crouton.1_SP_V2.pdf](https://github.com/dnschneid/crouton/files/121916/Xorg.crouton.1_SP_V2.pdf)

**Comment by tista500** [comment]
@Stretholox,

Bad:
` sudo mv ~/Downloads/20-armsoc.conf /usr/share/X11/xorg.conf.d/sync`
Good:
` sudo mv ~/Downloads/20-armsoc.conf /usr/share/X11/xorg.conf.d/`

Regards.

**Comment by Stretholox** [comment]
(precise)user@localhost:~$ sudo mv ~/Downloads/20-armsoc.conf /usr/share/X11/xorg.conf.d/
(precise)user@localhost:~$ sync
(precise)user@localhost:~$ logout
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost ~/Downloads $ sudo startxfce4

[Xorg.crouton.1_SP_v3.pdf](https://github.com/dnschneid/crouton/files/122054/Xorg.crouton.1_SP_v3.pdf)

**Comment by tista500** [comment]
@Stretholox,

OK.
Now I just created precise chroot with xfce, and confirmed your issue.
Precise seems to need dirty hack that was not needed in Xenial...

So try this from crosh window:
```
shell
sudo rm -f /dev/dri/card0
sudo mv /dev/dri/card{1,0}
sudo startxfce4
```
In this case, you have to do those commands for launching crouton at first-time-login, and those fixes will be cleared by rebooting chromebook, so next-time boot also needs those again...

Regards.

**Comment by Stretholox** [comment]
Ok. So I was automatically brought into Ubuntu when I did the above in a crosh window. However, the Ctrl+Alt+forward/backward function doesn't work. Is that correct? Will I have to type the above formula every time I want to log into Ubuntu

**Comment by divx118** [comment]
@Stretholox Ctrl+Alt+SHIFT+forward/backward notice the shift.

**Comment by Stretholox** [comment]
Neither work. Ctrl+Alt+Forward takes me to developer console requiring a password I have never created.

**Comment by DennisLfromGA** [comment]
@Stretholox  -

> ...notice the shift.

Ctrl+Alt+SHIFT+forward/backward

**Comment by tista500** [comment]
@divx118 and @DennisLfromGA,

Thank you for helping us!! :- )

@Stretholox,

Before playing crouton, you should remove that directory (or file) which were created unexpectedly if it existed inside the chroot: `sudo rm -rf /usr/share/X11/xorg.conf.d/sync`

Regards.

**Comment by RoryDuncan** [comment]
Hi, I ran into the same problem as Stretholox, with the Asus Flip.
I followed your instructions and all is well, I just wanted a clarification.

Is this the part that needs re-typing for each reboot:
```
shell
sudo rm -f /dev/dri/card0
sudo mv /dev/dri/card{1,0}
sudo startxfce4
```

Or do we have to go through all of the steps you listed each time?
I'm curious if I can just add the above code block into a script and run it each time and save myself from future hassle.

Thanks for all your hard work.

**Comment by tista500** [comment]
@RoryDuncan,

> Is this the part that needs re-typing for each reboot:
> ```
> shell
> sudo rm -f /dev/dri/card0
> sudo mv /dev/dri/card{1,0}
> sudo startxfce4
> ```

Yes.
Because those device files named `card0` and `card1` are created by ChromeOS's udev inside its boot sequence. And whenever crouton sets up sysfs for chroot, those should be the problem. So that "renaming card" hack must be needed in every time you did "boot" and "reboot" to your Flip. However, in other words, once you have done such hack at first-time logging into chroot after boot/reboot, then next-time, you don't have to do this again within powering your machine up (means 2nd-time login only needs `sudo startxfce4`, indeed, "login" and/or "logout" can keep that hack safely)...

> Or do we have to go through all of the steps you listed each time?

No.
Step 1 to 5 I've posted above could be stored in chroot permanently so you don't have to dup those steps in each time.

> I'm curious if I can just add the above code block into a script and run it each time and save myself from future hassle.

Sounds nice and let us know if you could do right things...

Regards.

**Comment by chrisnatali** [comment]
In case it helps someone, @tista500's [config change](https://github.com/dnschneid/crouton/issues/2424#issuecomment-180875613) and [device removal hack](https://github.com/dnschneid/crouton/issues/2426#issuecomment-181532932) suggestions got "X" (or freon I suppose) support working natively (i.e. without the unusable xiwi + extension solution) on an Asus c100p.

**Comment by zlehmann** [comment]
OMG thank you! Had no idea what was wrong with my setup but following this thread got it to work!

**Comment by NathanDetr0it** [comment]
so... what do I do if I accidentally ran this twice:
`sudo rm -f /dev/dri/card0
sudo mv /dev/dri/card{1,0}'
? Hoping these were files crouton can replace with an update?

**Comment by NathanDetr0it** [comment]
no luck. Entering the chroot as root to try to apt-get these...

**Comment by tista500** [comment]
@NathanDetr0it,

Reboot your Flip, so that device files will be re-created. And such dirty hack is NOT needed in Trusty, Wily and Xenial. If you guys don't have the specific reason to stack with unity-2d, you'd better to move to Trusty or higher...

Regards.

**Comment by Hadlock** [comment]
There's no current support for Unity-2D above 12.04 (precise) on ARM, so it impacts a fair number of chromebook users. Since Unity 3D isn't supported on ARM for whatever reason, dirty arm users are leaning on this dirty crutch/hack...

**Comment by Theduud** [comment]
Late to the party, quick question. This method did help me get linux set up, but every time I log out I have to redownload the armsoc and enter those few lines of text. Is there any way to at least get out of redownloading the amrsoc file? It is a bit of a hastle to have to download a document every time I use my chromebook.

**Comment by dnschneid** [comment]
Try the latest crouton; no hacks should be necessary anymore.
