### ISSUE TITLE
no startwily command

### ISSUE THREAD

**Issue by fishfishfish2104** [dnschneid/crouton#2430]
i got wily i know it says its not supported but when i type sudo startwily it says no such command i went and looked where most of the start(chrootname) files are and there isn't one i also went in the chroot dir and check if it is there and it is please help
![screenshot 2016-02-10 at 18 44 57](https://cloud.githubusercontent.com/assets/16485618/12939627/6a0f588c-d026-11e5-968c-41a96e720fa7.png)

**Comment by DennisLfromGA** [comment]
@fishfishfish2104,

'wily' is the *release* you installed, it's Ubuntu 15.10.
xfce4 is the *target/desktop* you installed. 

I'm making the assumption that you installed xfce4 on both your 'precise' & 'wily' chroots -

To start your xfce4 desktop in the '*wily*' chroot, use: `sudo startxfce4 -n wily`
To start your xfce4 desktop in the '*precise*' chroot, use: `sudo startxfce4 -n precise`
