### ISSUE TITLE
Aura root window title is no more present

### ISSUE THREAD

**Issue by gnidorah** [dnschneid/crouton#2431]
Broken by this old Chromium OS commit https://chromium.googlesource.com/chromium/src/+/1c007d5de979461ae400c95c4309e2955de094c6%5E%21
On freonless builds it brakes at least two visible parts:
xiwi https://github.com/dnschneid/crouton/issues/1976
clipboard sync between host and chroot window

**Comment by gnidorah** [comment]
Pinning related
#2196 
#2126 
Maybe @dnschneid could give some insight into all this.

**Comment by gnidorah** [comment]
Got success with latest ArnoldTheBat daily build (Camd64OS-20160213010102.img.7z, 50.0.2639.0, 7917.0.2016_02_13_0345) and latest crouton https://github.com/dnschneid/crouton/commit/daa872a0d183b417c27c3f74b37f5eeb96755a5e
Looks like both ArnoldTheBat special build and CloudReady are too old.

Thanks.

**Comment by gnidorah** [comment]
Leave a comment

**Comment by arnoldthebat** [comment]
Untested but give http://arnoldthebat.co.uk/wordpress/2016/02/14/chromiumos-special-build-r50-7881/ a go.

**Comment by gnidorah** [comment]
@arnoldthebat Thank you, but unfortunately new build doesn't help. Could you please make a special build with a graphics stack switched to Freon?
Details: I've looked further, and seeing that your special builds (even new one) don't use freon yet, while daily builds do so. I've picked few last builds of both and tested crouton. Results:
1. on daily builds both accelerated X works (via crouton's startxfce4, using Intel integrated graphics, hardware acceleation ensured by https://github.com/dnschneid/crouton/wiki/3D-Hardware-acceleration#tools-to-check-hardware-acceleration-support) and xiwi do work
2. on special builds neither work falling to https://github.com/dnschneid/crouton/issues/1976
Looks like old, non-freon support for graphics in crouton is broken for Chromium OS builds.

**Comment by arnoldthebat** [comment]
OK. Ill need to go and spend some time on the special builds! I did try a build with Freon but it broke graphics on all the laptops I have barring one gen 2 intel...

**Comment by gnidorah** [comment]
@arnoldthebat 

> but  it broke graphics on all the laptops I have barring one gen 2 intel...

Oh, I expected something like that... That's makes sense why not all official Chrome OS devices switched to freon then.
Pity that crouton X11 at non-freon Chromium OS is currently non-functional. But that's up to crouton team or those Chromium OS internals gurus interested in fixing this.

Sorry I understand you may have little time for this. Maybe its possible to automate special builds process? Or perhaps are there any instructions on how should I build and add device firmwares after I do plain Chromium OS build at my side https://www.chromium.org/chromium-os/quick-start-guide and possibly useful configs, scripts etc you use to produce a special build? Something like "build your own ArnoldTheBat build" :-) Info on how to bring stateful_update in this case would be also much useful.

Thanks!

**Comment by gnidorah** [comment]
Ok, self built a Chromium OS 50.0.2652.0 (64-bit) 7933 with disabled freon (ensured).
Unlike with ArnoldTheBat (old one, not tried with new one!) and CloudReady, xiwi and xorg work fine after doing this fix https://github.com/dnschneid/crouton/issues/1976#issuecomment-126783866
Case closed!

**Comment by gnidorah** [comment]
Wrote a simple guide on how to cook a PC compliant Chromium OS build https://gist.github.com/gnidorah/8ca4f7db3af38b1622a8

**Comment by drinkcat** [comment]
Everything should be freonized now.
