### ISSUE TITLE
wily install failed

### ISSUE THREAD

**Issue by fishfishfish2104** [dnschneid/crouton#2432]
i tried reinstalling wily with this command sudo sh ~/Downloads/crouton -t xfce -t chrome -r wily 
and it failed with this error 
WARNING: The following packages cannot be authenticated!
  libidn11 libkeyutils1 libroken18-heimdal libasn1-8-heimdal libhcrypto4-heimdal libheimbase1-heimdal libwind0-heimdal libhx509-5-heimdal
  libkrb5-26-heimdal libheimntlm0-heimdal libgssapi3-heimdal libsasl2-modules-db libsasl2-2 libldap-2.4-2 libkrb5support0 libk5crypto3 libkrb5-3
  libgssapi-krb5-2 librtmp1 libcurl3-gnutls apt-transport-https openssl ca-certificates wget
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/wily...

**Comment by TyJoKo** [comment]
I just had the same issue, and I think what happened was a hashsum mismatch when it ran apt-get update for the required sources. running installation again, hopefully this time it works. I have the same computer, and it is just barely making it by with that i need it to do.
