### ISSUE TITLE
Google Maps Location Accuracy

### ISSUE THREAD

**Issue by hornok** [dnschneid/crouton#2433]
Hello guys,

I am using google maps api's. can i know how do i increase the location accuracy using google api's. Do i have to go for premium plan in google api's to achieve accuracy or is there any api that i can make use of, to achieve location accuracy?
Please help me !!

with regards,
HornOk

**Comment by smibarber** [comment]
#262 has some tips on that, actually.

**Comment by hornok** [comment]
Thank you smibarber !
