### ISSUE TITLE
Is there anyway to use alias on ubuntu?

### ISSUE THREAD

**Issue by xz15** [dnschneid/crouton#2435]
I'm using ubuntu14.04+xfce
I created ~/.bash_alias **on ubuntu**, but it doesn't work, how do I use alias?

**Comment by DennisLfromGA** [comment]
Yup, put something like this in your `.bashrc` file:

`[ -f ~/.bash_alias ] && . ~/.bash_alias`

That also works on the Chrome OS side...

**Comment by xz15** [comment]
oops, just realized I typed the wrong name, it should be ~/.bash_aliases
