### ISSUE TITLE
Chromebook crashes when shutting down ubuntu trusty

### ISSUE THREAD

**Issue by ucobbi** [dnschneid/crouton#2436]
When pressing the power off button in ubuntu trusty or using the command poweroff in crosh when logged into its terminal, the computer crashes. First the screen goes dark for about 3 seconds then the chromebook shuts off. I also have ubuntu precise installed but I have no such issue with it.

Edit: Nevermind, I didn't know you could shut down the chroot by logging out.

**Comment by DennisLfromGA** [comment]
Don't power-off from the chroot, use logout instead.
It's best to exit your chroot so everything shuts down properly, then power-off from Chrome OS.
