### ISSUE TITLE
port chromeos touchpad driver on crouton

### ISSUE THREAD

**Issue by xz15** [dnschneid/crouton#2437]
I'm trying to use hugegreenbug's method(https://github.com/hugegreenbug/xf86-input-cmt) to install chromeos touchpad driver
how do I figure out which "50-touchpad-cmt-xxx.conf" to put in /usr/share/X11//xorg.conf.d? 

These are the confs in the "xf86-input-cmt" folder, I don't know which one to choose

20-mouse.conf
50-touchpad-cmt-kaen.conf
50-touchpad-cmt-pit.conf
20-touchscreen.conf
50-touchpad-cmt-leon.conf
50-touchpad-cmt-puppy.conf
50-touchpad-cmt-aebl.conf
50-touchpad-cmt-link.conf
50-touchpad-cmt-spring.conf
50-touchpad-cmt-alex.conf
50-touchpad-cmt-lumpy.conf
50-touchpad-cmt-stout.conf
50-touchpad-cmt-butterfly.conf
50-touchpad-cmt-mario.conf
50-touchpad-cmt-wolf.conf
50-touchpad-cmt-daisy.conf
50-touchpad-cmt-parrot.conf
50-touchpad-cmt-zgb.conf
50-touchpad-cmt-elan.conf
50-touchpad-cmt-peppy.conf
50-touchpad-cmt-falco.conf
50-touchpad-cmt-pi.conf

I'm running ubuntu 14.04+xfce on a dell 13 chromebook(i3)

xinput list: (I believe ID8 is my touchpad)

� Virtual core pointer                    	id=2	[master pointer  (3)]
�   ��� Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
�   ��� SYNA0000:00 06CB:7AB3                   	id=8	[slave  pointer  (2)]
� Virtual core keyboard                   	id=3	[master keyboard (2)]
    ��� Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ��� Power Button                            	id=6	[slave  keyboard (3)]
    ��� Power Button                            	id=7	[slave  keyboard (3)]
    ��� AT Translated Set 2 keyboard            	id=9	[slave  keyboard (3)]

**Comment by tista500** [comment]
@xz15,

We can find a "codename" of own chromebooks from chroot, something like:
` croutonversion | grep 'host:' | awk '{print $7}'`

And known codenames are listed here:
https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices

Then you could pull your suitable conf from that directory. However, if the proper configuration file for your exact model did not exist there, you might need to try some similar configurations though...

Regards.

**Comment by xz15** [comment]
Thanks! looks like I have to configure the driver myself, do you know where I could find a list of explanation for the cmt driver properties?

**Comment by tista500** [comment]
@xz15,

If your machine was "lulu", the file is here?:
https://chromium.googlesource.com/chromiumos/platform/xorg-conf/+/master/50-touchpad-cmt-lulu.conf

Regards.

**Comment by xz15** [comment]
Yes, I found it, thanks. What I did was using his ppa to install xf86-input-cmt, and somehow lulu was not included in xf86-input-cmt.

There's one problem though, the "smooth scrolling" or "coasting" is disabled, so the scrolling stops as soon as my fingers leave the touchpad, do you know which properties/option is related to this?

**Comment by tista500** [comment]
@xz15,

Unfortunately no... Since all of my chromebooks doesn't need such driver.

> There's one problem though, the "smooth scrolling" or "coasting" is disabled, so the scrolling stops as soon as my fingers leave the touchpad, do you know which properties/option is related to this?

I think you should better to contact to developer of the codes, at least I can't help you (maybe your issue can be related to its code)...

Regards.
