### ISSUE TITLE
update chroot installed in non default location

### ISSUE THREAD

**Issue by Bertieio** [dnschneid/crouton#2438]
I am trying to update my chroot installed on /media/removable/Test/chroots/chroots/trusty
 With `sudo sh ./crouton -n /media/removable/Test/chroots/chroots/trusty -u -t xiwi` but get `Invalid chroot name '/media/removable/Test/chroots/chroots/trusty'.` How do I do this?

**Comment by DennisLfromGA** [comment]
Looks like you've got an extra level chroots folder but in any case, this should work:

`sudo ./crouton -n trusty -p /media/removable/Test/chroots/ -t xiwi -u`

crouton's '-p' option is used to point to the chroot's parent directory in order to place the chroots and bin folders under it.
