### ISSUE TITLE
create "cmt" target to enable chromium's cmt touchpad driver inside crouton

### ISSUE THREAD

**Issue by jacklevy** [dnschneid/crouton#244]
on the pixel, chrome OS ships with touchpad support that provides good responsiveness/sensitivity, two-finger scrolling, palm/edge detection, and smooth sub-pixel scrolling.  these features are made possible by the google-developed `cmt` touchpad driver, which is currently only supported under chrome OS.  a standard ubuntu crouton chroot utilizes the synaptics touchpad driver, which provides a much poorer experience.  using synaptics, crouton users have found the touchpad to be hypersensitive, tap-to-click is less reliable, and two-finger scrolling (which is not enabled by default) often stops working when switching back and forth between the chroot and chrome OS.

in lieu of a real port of `cmt` to linux, the goal of this "issue" is to create a new `cmt` target for crouton that imports `cmt` driver binaries from the chrome OS host and enables it inside crouton.  two-finger scrolling can then be enabled via customizations to `croutonwheel`, which can aggregate sub-pixel scrolling events and emit the "chunky" wheel events that standard linux applications expect.

advantages (vs.synaptics driver):
- reliable two-finger scrolling
- three-finger multi-touch detection
- better palm/edge detection
- this may be the only way to use `cmt` in crouton, since a port is not currently underway

disadvantages:
- this target is not a proper port of `cmt`; it is a hack that imports and enables the `cmt` binaries shipped with chromium OS.  this works well on the pixel for the popular xfce and unity targets, but compatibility has not been tested on other devices or configurations.
- google may break `cmt` on this target at any time via updates to chromium OS
- this won't work if chromium OS and your chroot don't use the same architecture (64-bit vs. 32-bit)
- thinking about how this works may give you bitter beer face

**Comment by jacklevy** [comment]
Opened pull request #1302

**Comment by eighthave** [comment]
I'm a Debian Developer, and I'd like to get as much of the Chromebook support stuff as possible integrated into Debian (and therefore Ubuntu, etc) so its easy to run Debian via crouton, etc.  Is it still useful to upload @hugegreenbug's libgestures and cmt packages to Debian?  Uploading libgestures to Debian looks like an easy place to start, if that is still useful.  My guess is that the libevdevc stuff should be integrated into the upstream libevdev, but I haven't looked at it.

**Comment by DennisLfromGA** [comment]
Since the PR 'Experimental cmt target #1302' for this feature request has been closed -
> Going to close this (quite nifty) pull-request due to apparent lack of interest. I think as we move towards containers and Wayland and whatever, this won't be needed anyway.

I'll close this issue also.
