### ISSUE TITLE
After sudo startkde,  Welcome Screen freeze.

### ISSUE THREAD

**Issue by dwightblackwell** [dnschneid/crouton#2440]
After following steps for Acer Chromebook 15, crouton install, i get to, sudo startkde. After it starts, the startup window just freezes empty with an empty window. New to chromebooks. but not linux. This was a fresh install. I would have taken a screenshot but dont know how in ubuntu. Please help someone.

chronos@localhost / $ sudo startkde
Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Sun Jan 24 13:12:41 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashtree=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=94f24782d800e2abb5df56bbb3143a8fe70a7c2c salt=5f62c00040d6f7b0de40599ad6bb468285b80a86eb2637d4ba65791fda133de2" noinitrd vt.global_cursor_default=0 kern_guid=9c4a8b66-bf2d-8344-b395-cc24c0f465ca add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Feb 14 13:44:00 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
setversion 1.4 failed: Permission denied
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: kde
host: version 7647.73.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP Sun Jan 24 13:12:41 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
startkde: Starting up...
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
kbuildsycoca4 running...
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
kded(12298)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: name 'org.kde.kglobalaccel' had owner '' but we thought it was ':1.5'
kwin(12365) KWin::Extensions::init: Extensions: shape: 0x "11"  composite: 0x "4"  render: 0x "b"  fixes: 0x "50"  non_native_pixmaps:  true
(II) AIGLX: Suspending AIGLX clients for VT switch
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusObjectPath: invalid path ""
QDBusObjectPath: invalid path ""
plasma-desktop(12445)/libplasma Plasma::isPluginVersionCompatible: unversioned plugin detected, may result in instability 
plasma-desktop(12445)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "kde4-kmenuedit.desktop" not found
plasma-desktop(12445)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "systemsettings" not found
link XMLID_34_ hasn't been detected!
link XMLID_34_ hasn't been detected!
link XMLID_36_ hasn't been detected!
plasma-desktop(12445)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
plasma-desktop(12445)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "" not found
file:///usr/share/kde4/apps/plasma/plasmoids/notifier/contents/ui/devicenotifier.qml:166:5: QML QDeclarativeListView_QML_20: Possible anchor loop detected on vertical anchor.
QGraphicsScene::addItem: item has already been added to this scene
link XMLID_34_ hasn't been detected!
link XMLID_34_ hasn't been detected!
link XMLID_36_ hasn't been detected!
plasma-desktop(12445)/libakonadi Akonadi::AgentManagerPrivate::createDBusInterface: AgentManager failed to get a valid AgentManager DBus interface. Error is: 1 "org.freedesktop.DBus.Error.NameHasNoOwner" "Could not get owner of name 'org.freedesktop.Akonadi.Control': no such name" 
plasma-desktop(12445)/libakonadi Akonadi::SessionPrivate::socketError: Socket error occurred: "QLocalSocket::connectToServer: Invalid name" 
plasma-desktop(12445)/libakonadi Akonadi::SessionPrivate::socketError: Socket error occurred: "QLocalSocket::connectToServer: Invalid name" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
search paths:  ("/usr/local/bin", "/usr/bin", "/bin", "/usr/local/games", "/usr/games", "/usr/sbin", "/usr/local/sbin", "/usr/local/libexec", "/usr/libexec", "/opt/mysql/libexec", "/opt/local/lib/mysql5/bin", "/opt/mysql/sbin") 
Found mysql_install_db:  "/usr/bin/mysql_install_db" 
Found mysqlcheck:  "/usr/bin/mysqlcheck" 
QGridLayoutEngine::addItem: Cell (0, 1) already taken
plasma-desktop(12445)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
akonadi.collectionattributetable                   OK
akonadi.collectionmimetyperelation                 OK
akonadi.collectionpimitemrelation                  OK
akonadi.collectiontable                            OK
akonadi.flagtable                                  OK
akonadi.mimetypetable                              OK
akonadi.parttable                                  OK
akonadi.pimitemflagrelation                        OK
akonadi.pimitemtable                               OK
akonadi.resourcetable                              OK
akonadi.schemaversiontable                         OK
mysql.columns_priv                                 OK
mysql.db                                           OK
mysql.event                                        OK
mysql.func                                         OK
mysql.general_log                                  OK
mysql.help_category                                OK
mysql.help_keyword                                 OK
mysql.help_relation                                OK
mysql.help_topic                                   OK
mysql.host                                         OK
mysql.ndb_binlog_index                             OK
mysql.plugin                                       OK
mysql.proc                                         OK
mysql.procs_priv                                   OK
mysql.proxies_priv                                 OK
mysql.servers                                      OK
mysql.slow_log                                     OK
mysql.tables_priv                                  OK
mysql.time_zone                                    OK
mysql.time_zone_leap_second                        OK
mysql.time_zone_name                               OK
mysql.time_zone_transition                         OK
mysql.time_zone_transition_type                    OK
mysql.user                                         OK
Database "akonadi" opened using driver "QMYSQL" 
DbInitializer::run() 
checking table  "SchemaVersionTable" 
checking table  "ResourceTable" 
checking table  "CollectionTable" 
checking table  "MimeTypeTable" 
checking table  "PimItemTable" 
checking table  "FlagTable" 
checking table  "PartTable" 
checking table  "CollectionAttributeTable" 
checking relation  "PimItemFlagRelation" 
checking relation  "CollectionMimeTypeRelation" 
checking relation  "CollectionPimItemRelation" 
DbInitializer::run() done 
skipping update 2 
skipping update 3 
skipping update 4 
skipping update 8 
skipping update 10 
skipping update 12 
skipping update 13 
skipping update 14 
skipping update 15 
skipping update 16 
skipping update 17 
skipping update 18 
skipping update 19 
skipping update 20 
Database "akonadi" opened using driver "QMYSQL" 
Nepomuk Query Server not available 
DataStore::unhideAllPimItems() 
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
Database "akonadi" opened using driver "QMYSQL" 
PLUGINS:  "/usr/share/akonadi/agents" 
PLUGINS:  ("akonadinepomukfeederagent.desktop", "akonotesresource.desktop", "birthdaysresource.desktop", "calendarsearchagent.desktop", "contactsresource.desktop", "davgroupwareresource.desktop", "icalresource.desktop", "imapresource.desktop", "invitationsagent.desktop", "kabcresource.desktop", "kalarmdirresource.desktop", "kalarmresource.desktop", "kcalresource.desktop", "kdeaccountsresource.desktop", "knutresource.desktop", "kolabproxyresource.desktop", "localbookmarksresource.desktop", "maildirresource.desktop", "maildispatcheragent.desktop", "mboxresource.desktop", "microblog.desktop", "mixedmaildirresource.desktop", "mtdummyresource.desktop", "nepomuktagresource.desktop", "nntpresource.desktop", "notesresource.desktop", "openxchangeresource.desktop", "pop3resource.desktop", "vcarddirresource.desktop", "vcardresource.desktop") 
search paths:  ("/usr/local/bin", "/usr/bin", "/bin", "/usr/local/games", "/usr/games") 
PLUGINS inserting:  "akonadi_nepomuk_feeder" 0 ("Unique", "Autostart", "NoConfig") 
PLUGINS inserting:  "akonadi_akonotes_resource" 1 ("Resource", "Notes") 
PLUGINS inserting:  "akonadi_birthdays_resource" 0 ("Resource", "Unique") 
PLUGINS inserting:  "akonadi_calendarsearch_agent" 0 ("Unique", "NoConfig") 
PLUGINS inserting:  "akonadi_contacts_resource" 1 ("Resource") 
Database "akonadi" opened using driver "QMYSQL" 
PLUGINS inserting:  "akonadi_davgroupware_resource" 0 ("Resource", "FreeBusyProvider") 
PLUGINS inserting:  "akonadi_ical_resource" 1 ("Resource") 
PLUGINS inserting:  "akonadi_imap_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_invitations_agent" 0 ("NoConfig") 
PLUGINS inserting:  "akonadi_kabc_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kalarm_dir_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kalarm_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kcal_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kdeaccounts_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_knut_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_kolabproxy_resource" 0 ("Resource", "Unique") 
PLUGINS inserting:  "akonadi_localbookmarks_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_maildir_resource" 1 ("Resource") 
PLUGINS inserting:  "akonadi_maildispatcher_agent" 0 ("Unique", "Autostart") 
PLUGINS inserting:  "akonadi_mbox_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_microblog_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_mixedmaildir_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_mailtransport_dummy_resource" 0 ("Resource", "MailTransport") 
PLUGINS inserting:  "akonadi_nepomuktag_resource" 0 ("Resource", "Virtual", "Unique", "NoConfig") 
PLUGINS inserting:  "akonadi_nntp_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_notes_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_openxchange_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_pop3_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_vcarddir_resource" 0 ("Resource") 
PLUGINS inserting:  "akonadi_vcard_resource" 0 ("Resource") 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Akonadi server is now operational. 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
search paths:  ("/home/dwightblackwell/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/lib/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/dwightblackwell/.kde/lib/kde4/", "/usr/lib/kde4/") 
search paths:  ("/home/dwightblackwell/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/lib/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/dwightblackwell/.kde/lib/kde4/", "/usr/lib/kde4/") 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Known subscriber "AkonadiAgentServer" subscribes again 
void Akonadi::NotificationSource::addClientServiceName(const QString&) Notification source "AkonadiAgentServer" now serving: (":1.21", ":1.22") 
search paths:  ("/home/dwightblackwell/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/lib/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/dwightblackwell/.kde/lib/kde4/", "/usr/lib/kde4/") 
search paths:  ("/home/dwightblackwell/.kde/lib/kde4/plugins/", "/usr/lib/kde4/plugins/", "/usr/lib/x86_64-linux-gnu/qt4/plugins", "/usr/lib/qt4/plugins", "/usr/bin", "/usr/lib/kde4/plugins", "/home/dwightblackwell/.kde/lib/kde4/", "/usr/lib/kde4/") 
Known subscriber "AkonadiAgentServer" subscribes again 
void Akonadi::NotificationSource::addClientServiceName(const QString&) Notification source "AkonadiAgentServer" now serving: (":1.21", ":1.22", ":1.23") 
Database "akonadi" opened using driver "QMYSQL" 
Database "akonadi" opened using driver "QMYSQL" 
Known subscriber "AkonadiAgentServer" subscribes again 
void Akonadi::NotificationSource::addClientServiceName(const QString&) Notification source "AkonadiAgentServer" now serving: (":1.21", ":1.22", ":1.23", ":1.25") 
Agent instance created in separate process. 
Known subscriber "AkonadiAgentServer" subscribes again 
Database "akonadi" opened using driver "QMYSQL" 
Object::connect: No such signal QDBusAbstractInterface::StateChanged(uint)
Agent instance created in separate process. 
Known subscriber "AkonadiAgentServer" subscribes again 
Database "akonadi" opened using driver "QMYSQL" 
Agent instance created in separate process. 
Known subscriber "AkonadiAgentServer" subscribes again 
Database "akonadi" opened using driver "QMYSQL" 
Agent instance created in separate process. 
Known subscriber "AkonadiAgentServer" subscribes again 
Database "akonadi" opened using driver "QMYSQL" 
"/usr/bin/akonadi_nepomuk_feeder(12498)" Soprano: "QLocalSocket::connectToServer: Invalid name"
"/usr/bin/akonadi_nepomuk_feeder(12498)" Soprano: "QLocalSocket::connectToServer: Invalid name"
"/usr/bin/akonadi_nepomuk_feeder(12498)" Soprano: "QLocalSocket::connectToServer: Invalid name"
Known subscriber "akonadi_nepomuk_feeder" subscribes again 
Known subscriber "akonadi_maildispatcher_agent" subscribes again 
Known subscriber "akonadi_maildispatcher_agent" subscribes again 
Known subscriber "akonadi_maildispatcher_agent" subscribes again 
Database "akonadi" opened using driver "QMYSQL" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Database "akonadi" opened using driver "QMYSQL" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
[/usr/bin/nepomukservicestub] Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)"
"/usr/bin/kactivitymanagerd(12357)" Soprano: "QLocalSocket::connectToServer: Invalid name"
"/usr/bin/kactivitymanagerd(12357)" Soprano: "QLocalSocket::connectToServer: Invalid name"
"/usr/bin/kactivitymanagerd(12357)" Soprano: "QLocalSocket::connectToServer: Invalid name"
[/usr/bin/nepomukservicestub] virtual bool Soprano::Virtuoso::BackendPlugin::isAvailable() const could not find virtuoso-t binary 
(Soprano::PluginManager) plugin  "virtuosobackend" is not available.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Application '/usr/bin/nepomukservicestub nepomukstorage' exited normally...
QGraphicsLinearLayout::removeAt: invalid index 1
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Nepomuk server already running.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QGridLayoutEngine::addItem: Cell (0, 1) already taken
Invalid usage: expected: ./agent_launcher pluginName agentIdentifier 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QGridLayoutEngine::addItem: Cell (1, 1) already taken
Invalid usage: expected: ./agent_launcher pluginName agentIdentifier 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Invalid usage: expected: ./agent_launcher pluginName agentIdentifier 
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
Invalid usage: expected: ./agent_launcher pluginName agentIdentifier 
"/usr/bin/krunner(12546)" Soprano: "QLocalSocket::connectToServer: Invalid name"
"/usr/bin/krunner(12546)" Soprano: "QLocalSocket::connectToServer: Invalid name"
"/usr/bin/krunner(12546)" Soprano: "QLocalSocket::connectToServer: Invalid name"
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
akonaditray is already running!
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
krunner(12546)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "searchproviders/wikit.desktop" not found
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" 
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
krunner(12546)/libplasma Plasma::Package::isValid: Could not find required file mainscript 
plasma-desktop(12445)/plasma StatusNotifierItemSource::refreshCallback: DBusMenu disabled for this application 
plasma-desktop(12445)/plasma StatusNotifierItemSource::refreshCallback: DBusMenu disabled for this application 
I/O warning : failed to load external entity "/home/dwightblackwell/.qalculate/eurofxref-daily.xml"
I/O warning : failed to load external entity "/home/dwightblackwell/.qalculate/eurofxref-daily.xml"
plasma-desktop(12445)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:

**Comment by dwightblackwell** [comment]
Thanks for the help! :( Did i post in the wrong github):

**Comment by DennisLfromGA** [comment]
@dwightblackwell - It looks like you've got a ton of errors in that output.
Can you get into the chroot via `enter-chroot` or anything?
You could just try to get into the chroot and then do some updates to see if that fixes some of the above package problems/errors. Try -

  `sudo enter-chroot`
  `sudo apt-get update`
  `sudo apt-get install -f`
  `sudo apt-get upgrade`
  `exit`

Then maybe try your `startkde` command again.

**Comment by dwightblackwell** [comment]
Ok thanks 1000,s. Ill try and reply back.

**Comment by dwightblackwell** [comment]
That worked like a charm. I had tried the update, install, and upgrade lines, enter-chroot. thanks you saved me so much time.

**Comment by DennisLfromGA** [comment]
Great! I get lucky every now and then...

**Comment by DennisLfromGA** [comment]
Sometimes the 'use' account gets hosed or not setup completely so you can get into yur chroot directly as root like this: `sudo enter-chroot -u root`

**Comment by dwightblackwell** [comment]
Ive copied it to my notes. Its all coming back to me now. With your help.

**Comment by DennisLfromGA** [comment]
Good job and thanx for closing the issue. :+1:
