### ISSUE TITLE
xorg.freedesktop.org 403 Forbidden using latest crouton

### ISSUE THREAD

**Issue by tclc25** [dnschneid/crouton#2441]
Just trying to install Kali Sana via the following command

sudo sh -e crouton -r sana -t xfce

Everything goes through fine until this:
--2016-02-15 14:58:37--  http://xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
Resolving xorg.freedesktop.org (xorg.freedesktop.org)... failed: Name or service not known.
wget: unable to resolve host address 'xorg.freedesktop.org'
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/sana...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/sana...

Have tried browsing to http://xorg.freedesktop.org/releases/ on another computer/network and get the same 403 so I am going to guess it isn't a bug or anything. But is there a workaround available?

**Comment by drinkcat** [comment]
Works fine from here. Try again?

**Comment by tclc25** [comment]
Thanks. I tried again a few hours later and it was working.
