### ISSUE TITLE
setversion 1.4 failed && Fatal server error: no screens found

### ISSUE THREAD

**Issue by OlsonJ** [dnschneid/crouton#2442]
~ $ sudo startxfce4

Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Thu Feb 11 00:04:19 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=c885aa3a-cb83-f948-8be6-58c70e1fe23a/PARTNROFF=1 hashtree=PARTUUID=c885aa3a-cb83-f948-8be6-58c70e1fe23a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=d31714affa789eb0b6f4817de01150434d0e10b5 salt=99cda79b4363fa224390611409e8537795dabf3f45228d0648a293ab99a12794" noinitrd vt.global_cursor_default=0 kern_guid=c885aa3a-cb83-f948-8be6-58c70e1fe23a  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Feb 15 14:47:50 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I am ware that this problem has been posted already on GitHub, but none of the posts have helped me. I have a HiSense Chromebook C11 and have been trying to launch ubuntu of various GUI for about a week now.

**Comment by tista500** [comment]
@OlsonJ,

Recently I've confirmed that the combo "Precise and Rockchip" might have a pitfall in freonized X11 : #2426 

So could you please check this issue happens with Trusty as well if you had enough eMMC space: `sudo sh ~/Downloads/crouton -t xfce,xorg -r trusty -n trusty`
This would make another chroot  with Trusty so that you don't have to worry about loosing current Precise chroot. However, if you did not have much eMMC space, the same method above (#2426) will be able to solve your issue on Precise as well. But still, Trusty or newer releases can improve basic freon implementations better, I just think so...

Finally, by the way, our Rockchip can not launch modern 3D-accelerated desktop environments which required OpenGL/EGL (like Gnome-Shell, Pantheon, Budgie, Unity7, Plasma, Cinnamon, ...etc), please remember.

Regards.

**Comment by OlsonJ** [comment]
Thank you.

cd dri/dri
rm card0
mv card1 card0

This worked! Although I will have to try trusty now. I have only been using precise.
