### ISSUE TITLE
Invalid/untrusted certificates

### ISSUE THREAD

**Issue by sgosnell** [dnschneid/crouton#2444]
Started getting this today when updating crouton chroot:

`Installing target audio...
Fetching CRAS (branch b68f203eba1e2aa1ac0a6b8b72b679817fa623ff)...
--2016-02-16 09:50:07--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/b68f203eba1e2aa1ac0a6b8b72b679817fa623ff.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 173.194.202.82, 2607:f8b0:400e:c00::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.202.82|:443... connected.
ERROR: The certificate of 'chromium.googlesource.com' is not trusted.
ERROR: The certificate of 'chromium.googlesource.com' hasn't got a known issuer.
Error fetching CRAS
Failed to complete chroot setup.
Unmounting /media/removable/SD Card/chroots/sid...`

I don't know if this is a crouton issue or a Google issue, probably Google. But crouton is broken until it's fixed, the setup failed to complete so can't enter chroot.

**Comment by DennisLfromGA** [comment]
@sgosnell - I saw your G+ post but I haven't run into this one yet...
I'm at the current version of crouton so I'd like to wait 'til something gets merged before I update again - if it aint broke, don't fix it. ;-)

**Comment by sgosnell** [comment]
It's a new one on me too. I can enter the chroot by choosing to complete the
setup but the file system is mounted read only.

Regards,

Stan On Tue, Feb 16, 2016 at 12:49 PM, DennisL < notifications@github.com [notifications@github.com] > wrote:
@sgosnell [https://github.com/sgosnell] - I saw your G+ post but I haven't run into this one yet...
I'm at the current version of crouton so I'd like to wait 'til something gets
merged before I update again - if it aint broke, don't fix it. ;-)

—
Reply to this email directly or view it on GitHub
[https://github.com/dnschneid/crouton/issues/2444#issuecomment-184824176] .[https://github.com/notifications/beacon/AKfzN-yjAvMlY_E7PzbcjwnFJrr6IRNbks5pk2bSgaJpZM4HbRMl.gif]

**Comment by DennisLfromGA** [comment]
@sgosnell - You can sometimes get into your chroot as 'root' and fix things.
To enter and finish the setup script, if it's still there, use:

`sudo enter-chroot -u root -xx`


If you just want to get into the chroot as root to fix something like an incomplete or absent user account, just do it without the '-xx' part:

`sudo enter-chroot -u root`

**Comment by sgosnell** [comment]
It's not a problem with the user account, the entire rootfs is mounted ro.  I'm hoping it's a glitch on the chromium.googlesource.com website, and will go away soon.  I can get by without a chroot on the chromebook for awhile, I really only use it when on a trip, mostly for email.  Not having a reliable email client is a serious shortcoming of CrOS, IMO.  I use Icedove in the chroot for that, and usually don't need much more.  I have my Debian desktop at home, which I use most of the time.

**Comment by tedm** [comment]
You can temporarily use --no-check-certificate with wget, and a similar command with curl, until the cert gets fixed.

**Comment by sgosnell** [comment]
I think that would require modifying the crouton script, and I'm not ready to do that.  

I am curious about whether this is happening to anyone else.  Am I the only one getting this?  If so, why?
