### ISSUE TITLE
Impossible to install/run linux-tools

### ISSUE THREAD

**Issue by gkontsevich** [dnschneid/crouton#2446]
Hi guys,
Love crouton - it's been almost problem free up till now (except it doesn't like me having /usr/local on the SD card =S)

I'm running Debian jessie on a ASUS 201 ARM machine. From what I gather Debian jessie is designed to run on top of Linux kernel version 3.16. Though ChromeOS runs on 3.14 (as of the last update [2016-2-17]) I guess crouton just somehow makes it all work! 

However, I've been trying to install the linux-tools package so that I can run perf() and do some ARM-specific benchmarking, but linux-tools-3.14 is unavailable in the Debian repository (or any of the backports). Other version of the linux-tools (like 3.16 that is in the main jessie repository) refuse to run b/c of a kernel version mismatch.

Does anyone have a solution? Am I misunderstanding something? Maybe the ChromeOS kernel can be updated?

**Comment by tista500** [comment]
@gkontsevich,

I've not tried but how about cross-build the package with sources? : https://chromium.googlesource.com/chromiumos/third_party/kernel/+/chromeos-3.14

Debian would have `linux-chromebook` source package (in Ubuntu, its version was 3.4.0 though) as well, and you can pull `debian` and `debian.linaro` directories from source's diff.gz, even though you might need to do some patchworks anyhow...

Anyway if I were you, I'll try cross-build on other machines. 

Regards.

**Comment by gkontsevich** [comment]
@tista500 

Thank you for the help. I tried cloning the tools directory and running make but I guess there is more to it =) 
(some dependency issues which I assume mean you have to build the whole kernel). 
So I guess unfortunately this is a bit beyond my abilities. Sorry to hear there isn't a simpler solution.
