### ISSUE TITLE
Help me install linux, what are the steps to installing linux?

### ISSUE THREAD

**Issue by munxie21** [dnschneid/crouton#2447]
I would love to install the linux in my chromebook, this is because it is not easy to do all the things i want to do. I have already downloaded the crouton integration. What is the next step? I want it to run safely and properly. When I download all this and the linux run will I have to add more applications as I want. I really want that so urgently.  Please help. Thanks in advance.

**Comment by idvoretskyi** [comment]
@munxie21, the following links will help start working with crouton:
1) https://github.com/dnschneid/crouton/wiki
2) https://github.com/dnschneid/crouton/blob/master/README.md

Please, keep in mind that Crouton allows you to run different Linux-based environments in chroot while the host OS on your Chromebook will remain ChromeOS.

If you'd like to run a completely full Linux distribution on your Chromebook, you may search some recommendations how to run your desired distribution on your Chromebook.

**Comment by wevinkong** [comment]
I recommend you see this:  
http://www.everydaylinuxuser.com/2014/03/how-to-install-ubuntu-and-minecraft-on.html
