### ISSUE TITLE
Switching issues - windows not drawn correctly on return to Chrome OS

### ISSUE THREAD

**Issue by tinmice** [dnschneid/crouton#2448]
Chromebook Pixel:
When switching back to Chrome OS every other time the windows are not correct, I can't see the tabs on the browser window and there is a black border around the entire screen a couple of cm wide.

I've updated everything, crouton script, chroots, drivers etc etc and this still happens when switching back. Ubuntu itself is fine so it looks like it is different to the distorted mouse etc that happens before updating drivers. It's pretty much a clean install of Ubuntu as well as I have just started building this one to be a clean template.

**Comment by DennisLfromGA** [comment]
I don't have an explanation or a great fix but I'm wondering if toggling the F4 &/or F5 key(s) would remove the border?

![screenshot 2016-02-17 at 7 05 42 pm](https://cloud.githubusercontent.com/assets/3418772/13129292/15c8c022-d5aa-11e5-95f9-128c34205ab7.png)

**Comment by tinmice** [comment]
Yeah I have and sadly it didn't work, thanks for the suggestion though.

**Comment by krellen** [comment]
I have the exact same issue. Sometimes switching back and forth a few times resolves it. Othertimes not. This also happens sometimes when logging out and closing down the chroot, at which point ChromeOS is unusable and needs to be restarted.

**Comment by EscCtrlPgUp** [comment]
I've been experiencing this issue for a while too. Has continued throughout crouton and Chrome OS updates including the latest versions too. To prevent logging out of the chroot and returning to an unusable Chrome OS, always switch back and forth a few times until you see the full Chrome OS UI. As soon as you do, switch back to the chroot and logoff. That way you should return to a usable Chrome. Hope it at least alleviates the symptoms until the issue can be fixed.

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
