### ISSUE TITLE
mounting executable usb on chroton... code blocks 

### ISSUE THREAD

**Issue by danram111** [dnschneid/crouton#2449]
hay im kind of new at this . i have the chromebook pixel and im running linux throw crouton. And i got a removable sd card for it. the problem is when im running code blocks c++ on the sd card its telling me permission  denied. i was googling this prob and i found a temp fix 
sudo umount /dev/sdb1
mkdir ~/usbdrive
sudo mount -t vfat -o rw,exec,uid=1000,gid=1000,umask=022 /dev/sdb1 usbdrive

but when i do this chrome os doesn't read the sd  and when i restart it goes back to the original prob can anyone help me

**Comment by tista500** [comment]
@danram111,

May I ask a question?
Why the linux binary written in C++ was placed in vfat partition, or you meant C++ compiler said compiler warning when compiling the codes placed in vfat partition?

I think it's quite better to explain precisely what you did and saw in actual...

Regards.
