### ISSUE TITLE
invalid 'type' (character) of argument occurs while using ca() in r

### ISSUE THREAD

**Issue by HarryUBC** [dnschneid/crouton#2450]
Hi, I'm a beginner of R, and trying to use ca() to do a correspondence analysis with the csv. data shown below using：
    X trim spin mohn kell kuda
1  BT   23   26   24  100   20
2  CT   11   36   21    0   47
3  DN    3    5    0    0    0
4  CD   10   33    0    0   33
5  PS    0    0    0    0    0
6  MT    0    0    0    0    0
7  SB   28    0    4    0    0
8  SG    4    0   10    0    0
9  SN    7    0   26    0    0
10 ST    8    0    0    0    0
11 TB    8    0   15    0    0
Basically there are five species named and 11 observations at different sites. I used the following code to do a correspondence analysis, but it failed:
dat
    X trim spin mohn kell kuda
1  BT   23   26   24  100   20
2  CT   11   36   21    0   47
3  DN    3    5    0    0    0
4  CD   10   33    0    0   33
5  PS    0    0    0    0    0
6  MT    0    0    0    0    0
7  SB   28    0    4    0    0
8  SG    4    0   10    0    0
9  SN    7    0   26    0    0
10 ST    8    0    0    0    0
11 TB    8    0   15    0    0

> ca(dat)
> Error in sum(N) : invalid 'type' (character) of argument

So, I checked the sample data in the ca package, which is called smoke, and I read the data structure in r compared with mine. Here are the results:
str(dat)
'data.frame':   11 obs. of  6 variables:
 $ X   : Factor w/ 11 levels "BT","CD","CT",..: 1 3 4 2 6 5 7 8 9 10 ...
 $ trim: int  23 11 3 10 0 0 28 4 7 8 ...
 $ spin: int  26 36 5 33 0 0 0 0 0 0 ...
 $ mohn: int  24 21 0 0 0 0 4 10 26 0 ...
 $ kell: int  100 0 0 0 0 0 0 0 0 0 ...
 $ kuda: int  20 47 0 33 0 0 0 0 0 0 ...

> str(smoke)
> 'data.frame':   5 obs. of  4 variables:
>  $ none  : num  4 4 25 18 10
>  $ light : num  2 3 10 24 6
>  $ medium: num  3 7 12 33 7
>  $ heavy : num  2 4 4 13 2
> smoke
>    none light medium heavy
> SM    4     2      3     2
> JM    4     3      7     4
> SE   25    10     12     4
> JE   18    24     33    13
> SC   10     6      7     2
> dat
>     X trim spin mohn kell kuda
> 1  BT   23   26   24  100   20
> 2  CT   11   36   21    0   47
> 3  DN    3    5    0    0    0
> 4  CD   10   33    0    0   33
> 5  PS    0    0    0    0    0
> 6  MT    0    0    0    0    0
> 7  SB   28    0    4    0    0
> 8  SG    4    0   10    0    0
> 9  SN    7    0   26    0    0
> 10 ST    8    0    0    0    0
> 11 TB    8    0   15    0    0
> I don't know what is wrong in my data set. Could anyone help me solve it?
> Thank you in advance!

**Comment by DennisLfromGA** [comment]
Is this a 'crouton' issue?

**Comment by drinkcat** [comment]
#262
