### ISSUE TITLE
modify sudoers to allow enter-chroot to be run w/o password

### ISSUE THREAD

**Issue by mpcusack** [dnschneid/crouton#2451]
Has anyone tried this before? The /etc/sudoers file can be edited to allow specific commands/users/groups/combination to be sudo'd without a password. I'd feel more comfortable with the machine having a password for sudo by default, but prefer the convenience of being able to enter a chroot without one.

```
$ ls -la `which enter-chroot`
-rwxr-xr-x 1 root root 33008 Feb 16 23:42 /usr/local/bin/enter-chroot
```

The command can only be changed by root, so it should be safe.

Problem is the sudoers file is on the / read-only partition. I don't know much about chronos/crouton, can this still be changed without messing up warrenty/updates?

**Comment by DennisLfromGA** [comment]
'`enter-chroot`' and other crouton scripts plus other Chrome OS commands *can* be run without a password *unless* you encrypted your chroot(s) and/or chose to run `chromeos-setdepasswd` to set a password for chronos. If a chronos password is set, then you will have to enter it. 

Like you mentioned, the `/etc/sudoers` file is read-only and protected by default.
The only way to change that is to remove rootfs verification and re-mount / as rw.
