### ISSUE TITLE
ImportError: No module named sip. ARM Hisense c11 12.04 ubuntu

### ISSUE THREAD

**Issue by OlsonJ** [dnschneid/crouton#2452]
$ sudo python main.py

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    import sip
ImportError: No module named sip
(precise)olsonj@localhost:~/Desktop/fightcade$ 

Getting this "ImportError: No module named 'sip' " error. I've read a couple of posts concerning this issue but I could not understand the solution. Thanks in advance!

**Comment by OlsonJ** [comment]
I found an issue that prevents me from fixing this one. 

echo "Please install 'pyqt4' and 'wine' to run fightcade.

 I am mainly concerned figuring how to run wine. I am informed that arm based processors are unable to use wine because the architecture is not compatible but there is something called qemu? I've tried to get qemu but the instructions were not clear as well.

I am aware of the 50%-75% power reduction when attempting to run wine on qemu, but I'd like to try it out anyways to see if it will be good enough to do what I need.

**Comment by tista500** [comment]
@OlsonJ,

Is this issue related to crouton specific environments?
I'm wondering this is based on generic 'linux on arm' environments even though I didn't know about 'fightcade' at all... Isn't it better to file this issue on its own forum and/or somewhere else?

Regards.

**Comment by OlsonJ** [comment]
Right. It is not specific to crouton, linux on arm. Yeah 'fightcade' was a emulated rom with a server that my friends wanted me to try out.
