### ISSUE TITLE
Unable to correct problems, you have held broken packages

### ISSUE THREAD

**Issue by Asuza** [dnschneid/crouton#2453]
I installed a chroot the other day with the `e17` target running on Ubuntu `trusty`. After starting my new chroot with `sudo starte17`, I was unable to get past the initial wizard without the whole thing crashing. I then went into the chroot via `sudo enter-chroot` and completely wiped out e17 (as far as I know) and installed the latest version instead, e20 (hoping that would fix the bug).

Now that I've done all of that, when I try to update the chroot to add the `xiwi` target, I can't. I get the following error:

```
The following packages have unmet dependencies:
 e17 : Depends: libecore-con1 (>= 1.7.7) but it is not going to be installed
       Depends: libecore-evas1 (>= 1.7.7) but it is not going to be installed
       Depends: libecore-file1 (>= 1.7.7) but it is not going to be installed
       Depends: libecore-imf1 (>= 1.7.7) but it is not going to be installed
       Depends: libecore-input1 (>= 1.7.7) but it is not going to be installed
       Depends: libecore-ipc1 (>= 1.7.7) but it is not going to be installed
       Depends: libecore-x1 (>= 1.7.7) but it is not going to be installed
       Depends: libecore1 (>= 1.7.7) but it is not going to be installed
       Depends: libedbus1 (>= 1.7.7) but it is not going to be installed
       Depends: libedje1 (>= 1.7.4) but it is not going to be installed
       Depends: libeet1 (>= 1.6.0) but it is not going to be installed
       Depends: libefreet1 (>= 1.7.7) but it is not going to be installed
       Depends: libeina1 (>= 1.7.4) but it is not going to be installed
       Depends: libeio1 (>= 1.7.4) but it is not going to be installed
       Depends: libevas1 (>= 1.7.7) but it is not going to be installed
       Depends: libevas1-engine-software-x11
       Depends: libedje-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
```

So I'm not sure if I messed something up and didn't get rid of `e17`, or if crouton is trying to re-install it as part of the update process and can't because I removed some things out from under it.

Is crouton doing this? Is it something else? Do I just need to start completely over and try again?

Thank you!

**Comment by nmilosev** [comment]
Try to do ```sudo apt-get update```. I would suggest trying the same thing you did but with ```aptitude install``` instead of ```apt-get install``` but I'm in no way an Ubuntu expert ;)

**Comment by Asuza** [comment]
Well, I can successfully do `sudo apt-get update` from within the chroot. What I can't do is update the chroot from the outside using `crouton` without it failing for `e17` (which was one of the original targets of the chroot). So I wonder if `crouton` is trying to re-install or update `e17`? I'm not sure how to tell it to stop if that's the case.

**Comment by nmilosev** [comment]
Pretty sure you can delete the target from ```.crouton-targets``` in your chroot. Not sure what will happen if you try to update then.

**Comment by DennisLfromGA** [comment]
@Asuza,

To see what is actually being held, run: `dpkg --get-selections | grep hold`
You can then remove any non-critical packages reported.

Sometimes cleaning things up will help, using: `sudo apt-get autoclean`

Also, after a `sudo apt-get update` you can try 'fix'ing things with: `sudo apt-get -f install`
