### ISSUE TITLE
"cap locks" seems to be slow/delayed in crouton

### ISSUE THREAD

**Issue by xz15** [dnschneid/crouton#2457]
I'm a fast typer, if I try to type "DdDdDdDdDdDdDdDdDdDdDdDdDd.........",
in crouton it almost always become
"DDDdDDDDDDDDDDdDDDDDDDDDDDDDDDDD......"
unless I type it slow.
It's very annoying because commands like "cd ~/Documents" often become "cd ~/DOcuments"

in chromeos, everything is normal, I never mistype anything, so it's probably a software issue.

I'm using ubuntu14.04+xfce4+chromeos CMT driver, on a dell 13(i3 4G) chromebook

**Comment by tista500** [comment]
@xz15,

Please let this issue be clear which X-method you usually run for crouton : 
```sudo edit-chroot -al```

Regards.

**Comment by xz15** [comment]
name: trusty
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 7647.84.0 (Official Build) stable-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP Wed Feb 17 22:13:25 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
