### ISSUE TITLE
X11 Fails to Start - No Screens Found (Chromebook Flip C100/c100p) Latest Crouton Feb 21/16

### ISSUE THREAD

**Issue by HaiKaiDo** [dnschneid/crouton#2460]
This issue was marked as closed however I dont believe it was ever properly addressed (or maybe the fix wasnt actually merged?)

After installing precise with xfce4(and then even tried running the update command) running "sudo startxfce4" still yields the following error.

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Thu Feb 18 00:20:36 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cf4f4418-f377-3846-827e-27d58e6b544b/PARTNROFF=1 hashtree=PARTUUID=cf4f4418-f377-3846-827e-27d58e6b544b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=2ad8c39d3170674892253f36c95df004419ff680 salt=1f4426f406109a0956a3633f991c78164eae5b6e38db789ef3f227163182cd79" noinitrd vt.global_cursor_default=0 kern_guid=cf4f4418-f377-3846-827e-27d58e6b544b  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Feb 21 23:07:27 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

You can get around it by doing:

sudo enter-chroot
sudo rm /dev/dri/card0
sudo mv /dev/dri/card1 /dev/dri/card0

But this has to be done EVERY single time you want to get into linux after a reboot.

Is there a more permanent solution to this issue?

**Comment by tista500** [comment]
@HaiKaiDo,

Try Trusty, that's all. The combo Precise + Rockchip + Xorg(freon) was not freonized well: https://github.com/dnschneid/crouton/issues/1978#issuecomment-142181260

Regards.

**Comment by HaiKaiDo** [comment]
Thanks! This has 100% resolved the issue.
