### ISSUE TITLE
Asus Chromebook Flip c100p (Trusty) Gnome will not launch. Gives Error "No Chromium OS X Server Is available" when Sudo StartGnome is Run

### ISSUE THREAD

**Issue by HaiKaiDo** [dnschneid/crouton#2464]
# Method One:
- Installing Via "sudo sh ~/Downloads/crouton -r trusty -t gnome" 
- Running the command "Sudo StartGnome" 
               yields the error "No Chromium OS X Server Is available" 
  # Method Two:
- Installing Via "sudo sh ~/Downloads/crouton -r trusty -t gnome,xiwi"
- Running the command  "Sudo StartGnome" or "Sudo StartGnome -x xiwi"
        I get the error "Error: Target String Not Available" however I at least get a weird black screen which then turns into multi colors and says "please close" and then closes.

More logs can be obtained per any request.

**Comment by DennisLfromGA** [comment]
@HaiKaiDo,

You don't *launch* your desktop with a 'crouton' command, you *launch* it with the start* script for your target/desktop. So, if you installed gnome, you'd *launch* it using:

`sudo startgnome -n trusty`

If you want to make sure it uses an installed 'xmethod', you can specify it with on command line.
'xiwi' for instance would use:

`sudo startgnome -n trusty -X xiwi`

@DennisL

**Comment by HaiKaiDo** [comment]
Sorry @DennisL I completely forgot to put that in my post. I'm indeed launching by "sudo startgnome" (I'm also no specifying the chroot because I only have trusty installed). I edited my post to reflect this. Sorry again for that one.

**Comment by DennisLfromGA** [comment]
@HaiKaiDo,

Your title says you're using `sudo startgnome` but the first post says you're using 'crouton' so I wasn't sure how you were trying to launch it.

It would help if we could see the output of: `sudo edit-chroot -all`

If you have xmethod 'xiwi' and only 'xiwi' installed, just using `sudo startgnome` *should* work.

@DennisL

**Comment by HaiKaiDo** [comment]
So i just switch from dev and back again so my machine would be fresh after the wipe.
I installed trusty with gnome like this "sudo sh ~/Downloads/crouton -r trusty -t gnome" 

Then I ran sudo edit-chroot -all and heres the output.

ame: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: armhf
xmethod: xorg
targets: gnome
host: version 7647.84.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP Thu Feb 18 00:20:36 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by HaiKaiDo** [comment]
One more time I tried "sudo sh ~/Downloads/crouton -r trusty -t gnome,xiwi" and then attempted to launch via sudo startgnome -n trusty -X xiwi

I Received The Following Output:

sudo startgnome -n trusty -X xiwi
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-67-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Thu Feb 18 00:20:36 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cf4f4418-f377-3846-827e-27d58e6b544b/PARTNROFF=1 hashtree=PARTUUID=cf4f4418-f377-3846-827e-27d58e6b544b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=2ad8c39d3170674892253f36c95df004419ff680 salt=1f4426f406109a0956a3633f991c78164eae5b6e38db789ef3f227163182cd79" noinitrd vt.global_cursor_default=0 kern_guid=cf4f4418-f377-3846-827e-27d58e6b544b  
Build Date: 12 February 2015  02:55:07PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Feb 23 22:22:57 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: armhf
xmethod: xiwi
targets: gnome,xiwi
host: version 7647.84.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP Thu Feb 18 00:20:36 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
 Server terminated successfully (0). Closing log file.
Hangup

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by DennisLfromGA** [comment]
@HaiKaiDo,

With xmethod 'xiwi' you *have* to install the '[crouton integration](http://goo.gl/OVQOEt)' extension also, notice the message at the end of the output:
```
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
```
Just install that extension and try to launch gnome again, you shouldn't have to add the '-X xiwi' part.

@DennisL

**Comment by HaiKaiDo** [comment]
I thought that was weird my self. I have had the extension installed the whole time.

**Comment by DennisLfromGA** [comment]
You had another similar issue https://github.com/dnschneid/crouton/issues/2460#issuecomment-187301491 that now appears to be working, is it not?

**Comment by HaiKaiDo** [comment]
This was for xfce4 which seems to be the only thing that works for me on this setup at the moment. The original issue was that I was using a version previous to trusty that was listed as supported, however someone suggested i try trusty and it worked no problems (albeit theres some odd error messages but I havent given it much thought since things seem to work fine) via launching it as "sudo startxfce4"

Im simply opening a ticket for gnome not launching properly on the asus chromebook c100
Finding broken things was encouraged by the developer :D and if I can find a resolution to this I play to make a writeup in the wiki.

**Comment by DennisLfromGA** [comment]
@HaiKaiDo - How many times have you tried to launch gnome, mine don't always 'connect' on the first attempt and I have to try a few times more to get it launched. @DennisL

**Comment by tista500** [comment]
Greetings,

First of all, as a result, veyron CAN run Gnome-Shell on crouton.
![screenshot from 2016-02-24 23-35-16](https://cloud.githubusercontent.com/assets/6073622/13288996/ae4e9a90-db51-11e5-83f0-93c84d7bfdab.png)

But it just launch at this time, it can't be acceptable for many users in "performance". All we could do is run gnome-shell directly without (bypassing) gnome-session-binary via LLVM swrast. Indeed, it's very hackish way (I actually did).

So you should stay on XFce4/LXDE desktops to get "decent" performance on daily-use. Or additionally Gnome-Flashback 3.18.x (16.x, too?) seems very stable and lightweight in most cases as well. Anyway I won't suggest to run Gnome-Shell on our beyron (Rockchip) Chromebooks, 99% of people will be disappointed its performance.

Regards.

**Comment by HaiKaiDo** [comment]
@tista500 Thanks very much for looking into that one (and helping me again for a second time). As far as gnome-flashback would it actually be possible for me to use? In all honesty my favorite is Mate (A close second is cinnamon). Would it be possible to use any of those? I just like the simple look of gnome2/mate/cinnamon and how theme-able it is.

**Comment by tista500** [comment]
@HaiKaiDo,

We will be able to make Mate/couton on Trusty if you like it.

* First, need to setup/install Mate components inside the chroot :
http://wiki.mate-desktop.org/download (see the section of Trusty)
* Second, need to tweak/create Mate specific chroot scripts, more easier, modifying gnome-target files will be enough for just testing (my thoughts, we just only have to edit a couple of lines to launch mate-session, maybe).

Regards.

**Comment by DennisLfromGA** [comment]
@tista500, 
Thanx for your very helpful replies and knowledge, I was quickly running out of ideas. ;) 
@DennisL

**Comment by HaiKaiDo** [comment]
Thanks for your help too @DennisL ! :D

@tista500 If i install trusty, can i install it without a desktop environment so that I can try getting mate to work without another desktop env. getting in the way? Or would it be equally as good just to install trusty with lxde and from there use the guide you linked to get mate up and running (Which at that point I guess would have 2 options for desktop environments in the same install until we can figure out how to just get mate working).

**Comment by DennisLfromGA** [comment]
@tista500 - Got it!
I installed Ubuntu Mate Remix on my Dell Chromebook 13 with both 'xorg' & 'xiwi' and it works in both!
I just modified the `startlxde` script to launch `mate-session` -
```
...
exec sh -e "`dirname "\`readlink -f "$0"\`"`/enter-chroot" -t xorg "$@" "" \
    exec xinit /usr/bin/mate-session
```
Check it out -
![screenshot 2016-02-24 at 6 08 54 pm](https://cloud.githubusercontent.com/assets/3418772/13304424/86ae4672-db22-11e5-87bd-7842728374fa.png)


*Thanx man*,
-DennisL

**Comment by tista500** [comment]
@DennisLfromGA,

You did it!! :smile: 
Yeah Mate will help many people who had to be stuck with "limited" 3D graphics support like armhf, and for those who want to run Gtk+ environments as lightweight as possible... Now I think Mate (without Compiz) can be added to crouton targets because it doesn't require any hardware specific 3D acceleration stack in both Intel and Arm architectures.

Thanks for your implementations!

Regards.

**Comment by tista500** [comment]
@HaiKaiDo,

> If i install trusty, can i install it without a desktop environment so that I can try getting mate to work without another desktop env. getting in the way? Or would it be equally as good just to install trusty with lxde and from there use the guide you linked to get mate up and running (Which at that point I guess would have 2 options for desktop environments in the same install until we can figure out how to just get mate working).

Yes. Until Mate target can be merged into master, you'd better to add some unwanted desktop environments to get both `host` side and `chroot` side crouton scripts for modifying them.

In another way, you can apply to do patchwork to crouton sources and compile before you start installing to actual machine. Then you should copy the compiled `crouton` script to your `~/Downloads` directory on Flip, so you can run something like `sh ~/Downloads/crouton -t mate -r trusty` from crosh window if you added the custom mate target into sources. This way, you don' t have to employ any other "meaningless" desktop environments but pure Mate...

Regards.

**Comment by HaiKaiDo** [comment]
you guys ever seen that picture of the dog at the computer sitting in the chair with the caption "I have no idea what Im doing" ? Yeah that's me right now lol. Im just good enough with linux to mess with it sufficiently in a regular desktop install(throw in some googling of course). Throw in all the crouton wizardry mixed with some arm incompatibility and ive gotten myself in too deep lol.

**Comment by HaiKaiDo** [comment]
@DennisL @tista500  If i made my own target file to install mate and made a file to launch mate in host-bin how can I go about using them? (i downloaded the whole crouton zip from the github main page and made my edits in those files. So I have that whole thing in a folder on my chromebook, just not sure how to tell it to use my custom target file)

**Comment by DennisLfromGA** [comment]
@tista500,

You should be able to install it using crouton's '-T' option, for an update, try:

`sudo sh ~/Downloads/crouton -T /path/to/target/file -u`

After that, your new host-bin launcher should work.

-**DennisL**

**Comment by HaiKaiDo** [comment]
I must not have made edits to my target file properly. It keeps telling me my chroot might be very old because no target list found.

this is what is inside my mate file.

`#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='mate'
DESCRIPTION='Installs the MATE desktop environment.'
HOSTBIN='startmate'
CHROOTBIN='crouton-noroot startmate mate-session'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install --no-install-recommends ubuntu-mate-core ubuntu-mate-desktop

TIPS="$TIPS
You can start mate via the startmate host command: sudo startlxde
"
`

any Ideas?

**Comment by DennisLfromGA** [comment]
@HaiKaiDo - Did you add your mate target to an existing chroot or did you install it in a new chroot?

The example I gave above was for an existing chroot where other targets were already installed.
If you want to install it in a new chroot, you'll have to specify *all* the targets you want, including your new 'mate' target.

Since your 'mate' target file points to a `host-bin/startmate` and a `startmate` script in the `chroots-bin`, you'll need to have created those too. I haven't done this myself so I'm just throwing out things I think might be causing these errors. Hopefully someone with more hands-on experience can chime in.

-*DenniL*

**Comment by DennisLfromGA** [comment]
@HaiKaiDo,

After looking at the `installer/main.sh` script, I saw the following routine:
```
    if [ -z "$UPDATEIGNOREEXISTING" ]; then
        TARGETSFILE="$CHROOT/etc/crouton/targets"

        # Read the explicit targets file in the chroot
        deduptargets "$TARGETSFILE"

        if [ -z "$TARGETS" ]; then
            error 1 "\
No target list found (your chroot may be very old).
Please specify targets with -t."
```
So it looks like your target isn't getting added to `/etc/crouton/tarets` for whatever reason...

-**DennisL**
