### ISSUE TITLE
Unity Greeter screen

### ISSUE THREAD

**Issue by PearcePunisher** [dnschneid/crouton#2465]
Hello, I am running Unity 14.04 on a Toshiba Chromebook and I am having issues getting to the lock screen where I can switch sessions. Anyone know of a command line I can use to switch to my cinnamon session?
Thanks

**Comment by DennisLfromGA** [comment]
@PearcePunisher,

You can't log out to get the display manager in a crouton chroot like you would on a normal distro.
You'l have to create a custom `startcinnamon` script or something similar either outside the chroot or inside the chroot or both to launch your cinnamon desktop. 

The following article may give you some guidance - 
[INSTALL CINNAMON ON A CHROMEBOOK WITH CROUTON](https://techblog.jeppson.org/2015/07/install-cinnamon-on-a-chromebook-with-crouton/)
