### ISSUE TITLE
xorg.freedesktop.org Connection timeout

### ISSUE THREAD

**Issue by Kleak** [dnschneid/crouton#2466]
I'm updating my chroots with the option -t keyboard
my chroot is just a xiwi chroots

![screenshot 2016-02-24 at 12 03 28 pm](https://cloud.githubusercontent.com/assets/5434752/13283583/c2064564-daee-11e5-95f4-4c90ebca1a2e.png)

**Comment by DennisLfromGA** [comment]
Probably a network glitch, keep trying.

**Comment by Kleak** [comment]
you have right it success this time.

**Comment by DennisLfromGA** [comment]
Great, glad to hear it!
