### ISSUE TITLE
Hercules DjControl Instinct Midi Controller not recognised in Mixxx

### ISSUE THREAD

**Issue by nigelwheeler** [dnschneid/crouton#2467]
Mixxx (1.10.1) will not recognise my Hercules DJContol Instinct as a controller.

I've found other issues on here suggesting there may be ALSA permissions problems with Crouton but nothing directly relevant.

If I run mixxx with sudo the controller is recognised...
Debug [Main]: Scanning PortMIDI devices: 
Debug [Main]:  Found output device # 0 Midi Through Port-0 
Debug [Main]:  Found output device # 2 Hercules DJControl Instinct MID ....
...but mixxx will not launch: 
Warning [Main]: X Error: BadAccess (attempt to access private resource denied)

Without sudo I get an ALSA permission error at the same point:
Debug [Main]: Scanning PortMIDI devices: 
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied

I have a freshly built trusty chroot having gone round in circles with this issue before using various suggestions on the mixxx forum etc. but have the same problem.

If anyone has idea if this is likely to be a Crouton issue I will of course add full log outputs etc.

**Comment by nigelwheeler** [comment]
Following advice of @drinkcat in #1174 I did:
chmod a+rw /dev/snd/seq
and as if by magic, controller has appeared. Will close this issue now but it would appear there is some audio permission issue outstanding.

**Comment by savmctavish** [comment]
Thank you.

After hours of searching I found this. Can now see my controller. :-)
