### ISSUE TITLE
Make xiwi quiet (or provide quiet option)

### ISSUE THREAD

**Issue by fubuloubu** [dnschneid/crouton#2468]
Just a simple issue. I've tried `xiwi [app] $> file` and any other combo I could think of. Basically, there's a lot of junk xiwi prints to the window that I don't care about. I would like to pipe that stuff to a file (for debug porpoises) or otherwise suppress it (or minimize it to something like "oops... error connecting")

I've been working with OpenCV so it's been getting kind of annoying for me to keep seeing all that junk.

**Comment by fubuloubu** [comment]
I found a workaround: `xiwi [app] >>file 2>&1`
But I still think there should be an argument to quiet output from xiwi

**Comment by tonyxue** [comment]
If you really want, you can simply ```xiwi [app] >/dev/null 2>&1```. The xiwi functionality is not stable enough to just hide the outputs. They have been always helpful.
