### ISSUE TITLE
I logged out of my chromebook and now my "sudo startxfce4" wont work anymore.

### ISSUE THREAD

**Issue by LittleGamingPrince** [dnschneid/crouton#2469]
When I start up the terminal I type in shell the when "chronos@localhost / $"  comes up I type in "sudo startxfce4" then I type my password and encryption paraphrase and then this comes up:
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Feb 18 00:25:22 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=396b7f47-ae0e-9c41-b11f-b39a543224b0/PARTNROFF=1 hashtree=PARTUUID=396b7f47-ae0e-9c41-b11f-b39a543224b0/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=a6869002bbb3a4f0b818653c08d1213ea2817122 salt=baf49ee2bb6713b381e35bfa749b754cef51ac6bf7ef0ff0ab75d9b08db2947e" noinitrd vt.global_cursor_default=0 kern_guid=396b7f47-ae0e-9c41-b11f-b39a543224b0 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Feb 27 11:42:37 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by zlehmann** [comment]
I'm having the same issue. I disabled my touchscreen and it worked for a few days. Now I'm back to this issue again.

**Comment by DennisLfromGA** [comment]
To better help you, please provide us the output of: `sudo edit-chroot -all`

**Comment by sidharthsiddapureddy** [comment]
I also have this issue

**Comment by Imperial-Industries** [comment]
To better help you, please provide us the output of: sudo edit-chroot -all
