### ISSUE TITLE
how to  presisting data between different states in stateprovider

### ISSUE THREAD

**Issue by saanviboyapati** [dnschneid/crouton#2471]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
// Code goes here

angular.module('main', ['main.guides', 'main.projects', 'ui.router']).config(function ($stateProvider, $urlRouterProvider) {
    $stateProvider.
        state('main', {
            url: '/',
            template: '<div>index</div>',
            controller: 'IndexCtrl'
        }).
        state('login', {
            url: '/login',
            template: '<div>login</div>',
            controller: 'LoginCtrl'
        }).
        state('guides', {
            url: '/guides',
            template: '<div>guides<div ui-view></div></div>',
            controller: 'GuidesCtrl'
        }).
        state('projects', {
            url: '/projects',
            templateUrl: 'project.html',
            controller: 'ProjectsCtrl'
        });
        
        $urlRouterProvider.otherwise('/main');
})
.controller('IndexCtrl', function() {
  console.log('Index');
})
.controller('LoginCtrl', function() {
  console.log('Login');
})
.controller('GuidesCtrl', function() {
  console.log('GuidesCtrl');
})
.controller('ProjectsCtrl', function() {
  console.log('Projects');
})
.controller('ListCtrl', function() {
  console.log('List');
})
angular.module('main.guides', ['ui.router']).config(function ($stateProvider) {
    $stateProvider.
        state('guides.login', {
            url: '/login',
            template: '<div>guides login</div>',
            controller: 'LoginCtrl'
        }).
        state('guides.menu', {
            url: '/login',
            template: '<div>guides-menu</div>',
            controller: 'LoginCtrl'
        }).
        state('guides.web', {
            url: '/web',
            template: '<div>guides web</div>',
            controller: 'ListCtrl'
        }).
        state('guides.mobile', {
            url: '/web',
            template: '<div>guildes mobile</div>',
            controller: 'ListCtrl'
        });
});

angular.module('main.projects', ['ui.router']).config(function ($stateProvider) {
    $stateProvider.
        state('projects.login', {
            url: '/login',
            template: '<div>projects login</div>',
            controller: 'LoginCtrl'
        }).
        state('projects.business', {
            url: '/business',
            templateUrl:'project.html',
            controller: 'ListCtrl'
        }).
        state('projects.menu', {
            url: '/menu',
            template: '<div>projects menu</div>',
            controller: 'ListCtrl'
        }).
        state('projects.community', {
            url: '/community',
            template: '<div>projects-community</div>',
            controller: 'ListCtrl'
        })
});

#### Please describe your issue:

When  navigating through different states i want persist the data.I attached the punker for that example  let say i entered some data in the projects(project.html) page and navigate to index(index.html) page and come back to projects page the data should persist on the text box but it is refreshing and making blank.i want to cache the whole view when i coming back to that view.
#### If known, describe the steps to reproduce the issue:
https://plnkr.co/edit/XtfZtDPeWSuMlURZHXbS?p=preview

Please advise.

**Comment by dnschneid** [comment]
...thus proving #2454 was totally worth it.

See #262.

**Comment by DennisLfromGA** [comment]
*It's the thought that counts...* :+1:
