### ISSUE TITLE
Logmein hamachi does not work after reboot

### ISSUE THREAD

**Issue by wuyuanyi135** [dnschneid/crouton#2472]
```
Please paste the output of the following command here: 
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,keyboard,xiwi,xfce
host: version 7647.84.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Feb 17 22:18:44 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```
#### Please describe your issue:

I installed logmein-hamachi from [here](https://secure.logmein.com/labs/logmein-hamachi-2.1.0.139-x64.tgz). The first boot was normal, I can connect to my peer machine using the virtual network ip. After reboot, hamachi never connect. I looked at `/sbin/ifconfig`

```
ham0      Link encap:Ethernet  HWaddr 7a:79:19:4c:66:5a  
          inet6 addr: fe80::7879:19ff:fe4c:665a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1404  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:2112 (2.1 KB)
```

For some reason, the inet addr is missing, which should be like 25.X.X.X. Therefore this gateway does not work. 

I caught some log messages

```
2016-03-01T13:22:19.248652-05:00 ERR shill[727]: [ERROR:logging.h(779)] Failed to call method: org.chromium.dhcpcd.Release: object_path= /org/chromium/dhcpcd: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
2016-03-01T13:22:19.248674-05:00 ERR shill[727]: [ERROR:dbus_method_invoker.h(111)] CallMethodAndBlockWithTimeout(...): Domain=dbus, Code=org.freedesktop.DBus.Error.NoReply, Message=Message did not receive a reply (timeout by message bus)
2016-03-01T13:23:16.257683-05:00 ERR shill[727]: [ERROR:dhcp_config.cc(297)] Timed out waiting for DHCP lease on ham0 (after 30 seconds).
2016-03-01T13:23:46.274767-05:00 ERR shill[727]: [ERROR:dhcp_config.cc(297)] Timed out waiting for DHCP lease on ham0 (after 30 seconds).
```

Looks something relating to DHCP fails

Does anyone use hamachi here? How do you solve this problem
#### If known, describe the steps to reproduce the issue:
- You may need `lsb` first
  `apt-get install lsb`
- download the package (if your system is 64bit)
  `wget https://secure.logmein.com/labs/logmein-hamachi-2.1.0.139-x64.tgz`
- untar
  `tar xvzf logmein-hamachi-2.1.0.139-x64.tgz`
- install
  `sudo ./install.sh`
- connect to your network, and see `/sbin/ifconfig`. For the first time the inet should be present.
- reboot, start hamachi again 
  `sudo /etc/init.d/logmein-hamachi start`
- see if you can connect to your peer (or ping). And now, your `ham0` interface may lose ipv4 address as well.

**Comment by Matttter** [comment]
Have you managed to solve this issue? I can't get it to work...
