### ISSUE TITLE
Chrome application for easy chroot starting

### ISSUE THREAD

**Issue by idvoretskyi** [dnschneid/crouton#2475]
I'm not sure if ChromeOS security restrictions will allow this, but if it is possible to create a simple Chrome application to launch Crouton chroot easily?

**Comment by mr-wong** [comment]
+1 for that feature. if possible make as icon on logon screen

**Comment by divx118** [comment]
Sadly not possible, because of the security restrictions.

**Comment by drinkcat** [comment]
> Sadly not possible, because of the security restrictions.

Yep. I'm pretty sure there were some old issues on this topic, but can't find them.
