### ISSUE TITLE
No Youtube sound in Firefox, Chromium browser works

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#2478]
I'm trying to watch and listen to Youtube video's on my chroot. It works fine in the Cromium browser in my chroot, but no matter what I try: youtube plays the video, but no sound...

How can I enable sound in Firefox?

**Comment by tista500** [comment]
No problems here...

* Chromebook Flip (stable-channel)
* Gnome-Flashback 3.18.1
* Firefox (Gtk+-2.0) 45.0
* Freshplayerplugin 0.3.5
* Pepperflash 20.0.0.306-r2

Regards.

**Comment by MeneerJansen** [comment]
@tista500 Are those packages you installed via Synaptic or Add-ons in Firefox? Anyway, I've got all those packages. In the Chromuim browser it works. But Firefox... Nope.

**Comment by tista500** [comment]
@MeneerJansen,

If I remembered well, freshplayerplugin was not packaged in main repository yet... So you could just build it from source : https://github.com/i-rinat/freshplayerplugin
This wrapper is written in C++ so it's quite easy to build.

And please verify the `libfreshwrapper-flashplayer.so` was recognized as Firefox's extension properly : 
![screenshot from 2016-03-15 12-23-00](https://cloud.githubusercontent.com/assets/6073622/13766870/0db86c0c-eaa9-11e5-80e9-112f802a72bf.png)

By the way, if we don't have any damned flash library, YouTube runs with HTML5 in most cases? I know some Firefox add-ons like Ad-Blocker causes audio playing issue with white noise on Dailymotion player, etc. But I have not seen such audio issue on Youtube anyway...

Regards.

**Comment by MeneerJansen** [comment]
Your html5 and Flash remark got me thinking. Went to ye' ol' html5 video test site: http://www.quirksmode.org/html5/tests/video.html

And guess what? All video's play but _no one_ with sound! So I guess Flash is not the problem. I disabled all Firefox plugins to no avail. Downloaded Firefox from Mozilla's website and ran it. No sound either...

**Comment by MeneerJansen** [comment]
De-installed al extensions, disabled all Plugins, downloaded Firefox from the Mozilla site and extracted the tar ball. But none of that helps. See the html5 video test page:

http://www.quirksmode.org/html5/tests/video.html

All video's play in Firefox, but _none_ with sound. Even on my other PC w/ Linux Mint: no sound in Firefox either!!!! I must have set something that Firefox doesn't like. But no matter where I look, nowhere can I find audio settings in Firefox (i.e. what device/mixer it uses etc.).

**Comment by tista500** [comment]
@MeneerJansen,

If Gnome and/or some other Gnome-compliant Desktops are run with Pulseaudio, `settings`->`sound`->`applications` will contain all of child processes like "play/record patch-bay" when playing/recording:
![screenshot from 2016-03-15 23-00-40](https://cloud.githubusercontent.com/assets/6073622/13780430/ca93540a-eb02-11e5-8e29-b394ad5614af.png)

I'm afraid that your applications were muted in that place...

Regards.

**Comment by MeneerJansen** [comment]
I think I'm getting closer. I use my Chromebook for Midi audio too (classic synt emulation, LMMS, etc.). I disable PulseAudio for that (I HATE pulseaudio). I've had to de-install PA on my other Linux machine too. Because with pulse audio: no pass through of Dolby Digital audio. 

Anyway when I enable PA w/ the command `pulseaudio --start` then the dialog screen that you posed it no longer greyed out (I can find it in `gnome-control-center` and then click on "Hardware --> Sound").

**Comment by MeneerJansen** [comment]
Got it! 

I installed the 'PulseAudio Volume Control' application via Synaptic, fiddled w/ the output settings in it after starting something w/ audio in it in Firefox and now sound works! Can somebody with basic Linux knowledge PLEASE tell the Firefox boys that their software don't work without PA? Only having Alsa ain't enough for them where it IS enough for Chromium and everything else Linux. Ffffff. 

Anyway thank you very much for thinking with me! :)

**Comment by dnschneid** [comment]
#1550
