### ISSUE TITLE
Network Settings / Top Panel nm-app

### ISSUE THREAD

**Issue by ianmac1964** [dnschneid/crouton#248]
Almost there now with my config. Just one last thing.

I want to be able to change wireless networks on the fly.

If I 'sudo gnome-control-center' and open Network I get a message 'System network services are not compatible with this version'. 

(note: the terminal I sudo'd from has the warning - 'The name org.freedesktop.NetworkManager was not provided by any .service files'. Also: Network Manager appears in list of services - sudo service --status-all -> "[ ? ] network-manager")

sudo ifconfig -a says I have eth0 lo and wlan0
Using wicd I can not see any networks and it looks like the wireless hardware isn't communicating with the utility.

Also nm-app is missing from the Top Panel.

Is there a procedure for configuring the wirless controls on the Unity destop?

Many thanks.

**Comment by chonkey821** [comment]
Anyone able to get NM working in crouton..Im using xfce with ubuntu bionic and wanted to control WiFi from crouton so that i can force 5ghz band...since chromeos keeps switching to the 2.4 band and changing the ssid is not an option for me.

**Comment by primas305** [comment]
i did the same and it worked on kali rolling....one think to keep in mind tho...by default the nm-applet was already loaded but it was loaded by a regular user hence it failed to connect to any networks i had to kill the process and start it as sudo nm-applet

**Comment by joax** [comment]
How did you stop shill? I am on ChromeOS 100 and cannot execute `sudo stop shill` on the chroot. It says `stop` is not found.

**Comment by chonkey821** [comment]
> How did you stop shill? I am on ChromeOS 100 and cannot execute `sudo stop shill` on the chroot. It says `stop` is not found.

shill is actually the ChromOS network service not croutons. So you need to stop it in crosh shell outside the chroot.

**Comment by joax** [comment]
Ok, got it working! thanks for the heads up. I haven't figured out yet how to start NetworkManager and nm-applet on root mode at start. Have you figured out that part?

**Comment by VenomousSteam81** [comment]
> Ok, got it working! thanks for the heads up. I haven't figured out yet how to start NetworkManager and nm-applet on root mode at start. Have you figured out that part?

I got it to work. Here is what I did:

1. `sudo service network-manager start`
2. `sudo nm-applet`

It disables and doesn't allow wifi in ChromeOS, though. Logout of crouton, then do `sudo start shill` in ChromeOS to restore wifi in ChromeOS
