### ISSUE TITLE
Minecraft lwjgl error

### ISSUE THREAD

**Issue by IamCarbonMan** [dnschneid/crouton#2482]
```
$ sudo edit-chroot -all -c /media/removable/Crouton/chroots
name: trusty
encrypted: no
Entering /media/removable/Crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xiwi
targets: e17,xiwi,keyboard
host: version 7647.84.0 (Official Build) stable-channel parrot_ivb 
kernel: Linux localhost 3.8.11 #1 SMP Thu Feb 18 00:33:08 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /media/removable/Crouton/chroots/trusty as another instance is using it.
```

#### Please describe your issue:
I have an acer c710, installed a trusty chroot to a usb drive with cli-extra, e17, xiwi, xorg and keyboard targets. Installed Oracle JRE 8. Installed Minecraft. When running minecraft via starte17 -X xorg, Minecraft runs fine and even gets 55 FPS on low settings. But when I run it with xiwi, it crashes with an error like [this](http://pastebin.com/raw/pNs48aYm), the stack trace points to `OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.` as the error. What's up with that? I know this isn't exactly supported, but why would lwjgl work just fine in the native xorg server and not the xiwi one?

#### If known, describe the steps to reproduce the issue:
1. Install a chroot with `sudo crouton -r trusty -t cli-extra,xorg,e17,xiwi,keyboard -p`
2. Install Oracle JRE 8.
3. Install Minecraft.
4. do:
    $ chronos@localhost / sudo enter-chroot
    $ xiwi java -jar minecraft.jar

**Comment by firestar115** [comment]
This means that OpenGL can't grab the `xiwi` display. You have to run the desktop environment in xiwi and then run Minecraft in that: `sudo starte17 -X xiwi`.

**Comment by IamCarbonMan** [comment]
Okay. That solves it. Closed.
