### ISSUE TITLE
Random switching between OS's

### ISSUE THREAD

**Issue by zlehmann** [dnschneid/crouton#2484]
Hey all, so I finally got the xfce4 gui to work for me. Now having a weird issue where after switching from chrome gui to xfce4, it will randomly switch back after a few seconds. After that happens the mouse is unresponsive for a while. I also have to try the cntrl+shift+alt+back/forward commands a few times to get it to go back to the other gui or get the mouse to work. 

Anyone have any ideas? I'm very new to this. 

Thanks!

**Comment by zlehmann** [comment]
Disabling the touch screen in chrome got it to work.

**Comment by fishfishfish2104** [comment]
in the chrome os terminal when you type sudo startxfce4 what does it say when this happens

**Comment by destroyboy** [comment]
I've been having this issue on my acer c720 with precise. It's been getting worse and worse....

**Comment by khannie** [comment]
Also on a C720. I'm using LXDE / lubuntu and it's also basically unusable. Fairly recent issue for me.

**Comment by destroyboy** [comment]
It seems to be not as bad if I switch to a tab on chrome that's not constantly updating the screen. I'm developing some graphics in javascript which is refreshing 60fps. If I switch to ubuntu when I'm displaying the tab it flickers between chromos/ubuntu rapidly. If I then switch back to chromos it become stable, then switch to say the shell tab then switch to ubuntu then it's mostly ok, but still randomly flashes back to chrome.

**Comment by destroyboy** [comment]
I'm getting the idea somehow the xorg drivers are broken somehow. I can't update my chroot. I've uninstalled precise and I'm trying trusty. Maybe I installed some xorg thing and that broke it. Anyway it is no more.

**Comment by destroyboy** [comment]
Ok. Not fixed. I've installed trusty/unity on acer C720 and it's still happening. But although I have not proved it yet, it seems to not happen after a reboot and only happen after I've closed the lid and opened it, so it's a suspend/resume issue maybe. I hope this comment helps somebody.

**Comment by khannie** [comment]
That is super helpful! Confirmed that it doesn't happen for me after a reboot also. Thank you!!

**Comment by destroyboy** [comment]
There are a bunch of people here who have the same problem https://plus.google.com/111050484964599665608/posts/H58ZwPqxz4L

**Comment by drinkcat** [comment]
Hopefully obsolete?
