### ISSUE TITLE
Cannot enter crouton session

### ISSUE THREAD

**Issue by l0ran** [dnschneid/crouton#2485]
```
Please paste the output of the following command here: sudo enter-chroot startxfce4
```
#### Please describe your issue:

I followed the instructions to install ubuntu on my chromebook from How to Geek. After downloading crouton and installing with this command : 
sudo sh ~/Downloads/crouton -e -t xfce

I cannot enter a crouton session to switch to ubuntu.
Please note that I never used Linux and only need it to run R Studio for some programming at school.
#### Here is the log :

[  4486.068] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[  4486.074] 
X.Org X Server 1.13.0
Release Date: 2012-09-05
[  4486.074] X Protocol Version 11, Revision 0
[  4486.074] Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
[  4486.074] Current Operating System: Linux localhost 3.14.0 #1 SMP Thu Feb 18 00:16:10 PST 2016 armv7l
[  4486.074] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9be2e87f-e12a-b746-a082-7d379ecd1381/PARTNROFF=1 hashtree=PARTUUID=9be2e87f-e12a-b746-a082-7d379ecd1381/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=de1c1d0cdbc81518fd209a4586a0eb7609a0a18c salt=b17035702157ceeb33c83b7f702ba48e12a87d407d28148b0cb4d20e93c36fd1" noinitrd vt.global_cursor_default=0 kern_guid=9be2e87f-e12a-b746-a082-7d379ecd1381  
[  4486.074] Build Date: 05 November 2013  03:23:26PM
[  4486.075] xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
[  4486.075] Current version of pixman: 0.30.2
[  4486.075]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[  4486.075] Markers: (--) probed, (**) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  4486.075](++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Mar 16 16:17:47 2016
[  4486.078](==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  4486.080](==) No Layout section.  Using the first Screen section.
[  4486.080](==) No screen section available. Using defaults.
[  4486.080](**) |-->Screen "Default Screen Section" (0)
[  4486.080](**) |   |-->Monitor "<default monitor>"
[  4486.081](==) No monitor specified for screen "Default Screen Section".
    Using a default monitor configuration.
[  4486.081](==) Automatically adding devices
[  4486.081](==) Automatically enabling devices
[  4486.081](==) Automatically adding GPU devices
[  4486.082](WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  4486.082]    Entry deleted from font path.
[  4486.082](WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  4486.082]    Entry deleted from font path.
[  4486.082](WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  4486.082]    Entry deleted from font path.
[  4486.082](WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[  4486.082]    Entry deleted from font path.
[  4486.082](WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  4486.082]    Entry deleted from font path.
[  4486.082](WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  4486.082]    Entry deleted from font path.
[  4486.082](WW) The directory "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType" does not exist.
[  4486.082]    Entry deleted from font path.
[  4486.082](==) FontPath set to:
    /usr/share/fonts/X11/misc,
    built-ins
[  4486.082](==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  4486.082](II) The server relies on udev to provide the list of input devices.
    If no devices become available, reconfigure udev or disable AutoAddDevices.
[  4486.082](II) Loader magic: 0xb6feae58
[  4486.082](II) Module ABI versions:
[  4486.082]    X.Org ANSI C Emulation: 0.4
[  4486.082]    X.Org Video Driver: 13.0
[  4486.082]    X.Org XInput driver : 18.0
[  4486.082]    X.Org Server Extension : 7.0
[  4486.083](II) config/udev: Adding drm device (/dev/dri/card1)
[  4486.084] setversion 1.4 failed
[  4486.084] Initializing built-in extension Generic Event Extension
[  4486.084] Initializing built-in extension SHAPE
[  4486.084] Initializing built-in extension MIT-SHM
[  4486.084] Initializing built-in extension XInputExtension
[  4486.084] Initializing built-in extension XTEST
[  4486.084] Initializing built-in extension BIG-REQUESTS
[  4486.084] Initializing built-in extension SYNC
[  4486.084] Initializing built-in extension XKEYBOARD
[  4486.084] Initializing built-in extension XC-MISC
[  4486.084] Initializing built-in extension SECURITY
[  4486.085] Initializing built-in extension XINERAMA
[  4486.085] Initializing built-in extension XFIXES
[  4486.085] Initializing built-in extension RENDER
[  4486.085] Initializing built-in extension RANDR
[  4486.085] Initializing built-in extension COMPOSITE
[  4486.085] Initializing built-in extension DAMAGE
[  4486.085] Initializing built-in extension MIT-SCREEN-SAVER
[  4486.085] Initializing built-in extension DOUBLE-BUFFER
[  4486.085] Initializing built-in extension RECORD
[  4486.085] Initializing built-in extension DPMS
[  4486.085] Initializing built-in extension X-Resource
[  4486.085] Initializing built-in extension XVideo
[  4486.085] Initializing built-in extension XVideo-MotionCompensation
[  4486.085] Initializing built-in extension XFree86-VidModeExtension
[  4486.085] Initializing built-in extension XFree86-DGA
[  4486.085] Initializing built-in extension XFree86-DRI
[  4486.085] Initializing built-in extension DRI2
[  4486.085](II) LoadModule: "glx"
[  4486.087](II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  4486.089](II) Module glx: vendor="X.Org Foundation"
[  4486.089]    compiled for 1.13.0, module version = 1.0.0
[  4486.089]    ABI class: X.Org Server Extension, version 7.0
[  4486.089](==) AIGLX enabled
[  4486.089] Loading extension GLX
[  4486.090](==) Matched modesetting as autoconfigured driver 0
[  4486.090](==) Matched fbdev as autoconfigured driver 1
[  4486.090](==) Assigned the driver to the xf86ConfigLayout
[  4486.090](II) LoadModule: "modesetting"
[  4486.091](II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  4486.092](II) Module modesetting: vendor="X.Org Foundation"
[  4486.092]    compiled for 1.13.0, module version = 0.5.0
[  4486.092]    Module class: X.Org Video Driver
[  4486.092]    ABI class: X.Org Video Driver, version 13.0
[  4486.092](II) LoadModule: "fbdev"
[  4486.095](WW) Warning, couldn't open module fbdev
[  4486.095](II) UnloadModule: "fbdev"
[  4486.095](II) Unloading fbdev
[  4486.095](EE) Failed to load module "fbdev" (module does not exist, 0)
[  4486.096](==) Matched modesetting as autoconfigured driver 0
[  4486.096](==) Matched fbdev as autoconfigured driver 1
[  4486.096](==) Assigned the driver to the xf86ConfigLayout
[  4486.096](II) LoadModule: "modesetting"
[  4486.097](II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  4486.097](II) Module modesetting: vendor="X.Org Foundation"
[  4486.097]    compiled for 1.13.0, module version = 0.5.0
[  4486.097]    Module class: X.Org Video Driver
[  4486.097]    ABI class: X.Org Video Driver, version 13.0
[  4486.097](II) UnloadModule: "modesetting"
[  4486.097](II) Unloading modesetting
[  4486.097](II) Failed to load module "modesetting" (already loaded, -1199265592)
[  4486.097](II) LoadModule: "fbdev"
[  4486.099](WW) Warning, couldn't open module fbdev
[  4486.099](II) UnloadModule: "fbdev"
[  4486.099](II) Unloading fbdev
[  4486.099](EE) Failed to load module "fbdev" (module does not exist, 0)
[  4486.099](II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  4486.099](--) using VT number 7

[  4486.110](WW) Falling back to old probe method for modesetting
[  4486.110](II) modesetting(0): using default device
[  4486.110](WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  4486.111](II) modesetting(0): Creating default Display subsection in Screen section
    "Default Screen Section" for depth/fbbpp 24/32
[  4486.111](==) modesetting(0): Depth 24, (--) framebuffer bpp 32
[  4486.111](==) modesetting(0): RGB weight 888
[  4486.111](==) modesetting(0): Default visual is TrueColor
[  4486.111](II) modesetting(0): ShadowFB: preferred NO, enabled NO
[  4486.111](EE) modesetting(0): KMS setup failed
[  4486.111](II) UnloadModule: "modesetting"
[  4486.111](EE) Screen(s) found, but none have a usable configuration.
[  4486.111] 
Fatal server error:
[  4486.111] no screens found
[  4486.111](EE) 
Please consult the The X.Org Foundation support 
     at http://wiki.x.org
 for help. 
[  4486.111](EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  4486.111](EE) 
[  4486.134] Server terminated with error (1). Closing log file.

**Comment by DennisLfromGA** [comment]
To better help you, we'll need to see the output of: `sudo edit-chroot -all`
In the meantime, try using xmethod 'xiwi'.
