### ISSUE TITLE
After I updated my unity to 14.10 and I restarted my chrome book, my startunity will not work

### ISSUE THREAD

**Issue by joeman720** [dnschneid/crouton#2486]
```
sudo: edit-chroot-all: command not found
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: armhf
xmethod: xorg
targets: unity
host: version 7834.60.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP Thu Mar 10 04:33:03 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Thu Mar 10 04:33:03 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=75b5c414-1ee6-1645-b251-02bbaa1c4353/PARTNROFF=1 hashtree=PARTUUID=75b5c414-1ee6-1645-b251-02bbaa1c4353/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=fd3745ccd4e8b1f93622c81a8826fdd3a841ef88 salt=11d6832e81595565a26720a4057ba28d6779112acfe650af0e102fcca2adfbac" noinitrd vt.global_cursor_default=0 kern_guid=75b5c414-1ee6-1645-b251-02bbaa1c4353  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Mar 17 18:25:38 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: armhf
xmethod: xorg
targets: unity
host: version 7834.60.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP Thu Mar 10 04:33:03 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by tista500** [comment]
@joeman720,

Unity7 doesn't work on your veyron chromebook properly ( more precisely, 3D-acceleration of Mali-T764 could not work on Xorg/crouton).

So it's quite better to go back to Precise if you would like to stay with Unity, or switch to XFce4, LXDE and some other 2D-limited desktop environments on Trusty...

By the way, your `release` seemed stuck with Precise, did you do dist-upgrade properly?

Regards.

**Comment by DennisLfromGA** [comment]
@joeman720 - You might want to try using 'xiwi' instead of 'xorg' also.
