### ISSUE TITLE
Upstart config question in installation process

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#2487]
I attempted to install the LXDE target with the Xenial release to an external chroot folder (on USB).

I had previously successfully installed the XCFE precise target to the same external chroot folder.

During installation, I have been challenged by a prompt as below, and I don't know what the right answer is, or why there is such a collision of config data. This time I chose YES to install the package maintainer's version.

However, I don't know what implication this might have, and I would like advice regarding the correct answer to choose as well as perhaps filing a bug to eliminate this prompt in future installations as we approach Xenial full release.

``` bash
Setting up upstart (1.13.2-0ubuntu19) ...

Configuration file '/etc/upstart-xsessions'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** upstart-xsessions (Y/I/N/O/D/Z) [default=N] ? d

Configuration file '/etc/upstart-xsessions'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
```

**Comment by tista500** [comment]
@cefn,

I've already purged all of upstart related packages from my Xenial Gnome though, if I remembered well, crouton installation process will overwrite `/etc/upstart-session` with `null` when `x11-common` target is installed...

In general desktops, once installed upstart, `/etc/upstart-xsessions` may contain some entries like:
```
gnome-session
budgie-session
...
```
That list was created by upstart when checking system-wide desktop sessions, I think. I don't know why crouton wants to remove such list, but normally we should have *empty* `/etc/upstart-xsessions`, right? (actual startup scripts are placed in `/usr/share/upstart/` directory.)

**Off-topic**
But unfortunately upstart in Xenial seems to prevent to run gnome-session-binary (I saw some fail-whale errors, but gnome-session of Ubuntu kills whale as default) , so I've decided to purge all upstart packages (upstart, upstart-bin, upstart-sysv, and etc...) then moved to systemd-sysv and finally could run gnome-session-binary as we expected...

Regards.
