### ISSUE TITLE
Running profile-sync-daemon

### ISSUE THREAD

**Issue by cefn** [dnschneid/crouton#2488]
Tried to install and launch profile-sync-daemon since I'm now running from my USB drive (My Lexar S45 128GB on Toshiba Chromebook 2 now seems to survive a sleep cycle).

If I launch with

```
/usr/bin/profile-sync-daemon sync &
```

I get the following error...

```
ERROR: Cannot find XDG_RUNTIME_DIR which should be set by systemd
```

I don't know if that means it's actually a systemd dependency, (which I gather can't be met), or if there's some other way to satisfy the need for a XDG_RUNTIME_DIR value. Any ideas? It would make my browsing much more efficient to be running in tmpfs.

There's some detailed information about profile-sync-daemon at https://wiki.archlinux.org/index.php/Profile-sync-daemon

**Comment by DennisLfromGA** [comment]
@cefn,

Looking at the author's github repo [here](https://github.com/graysky2/profile-sync-daemon#note-for-version-6), it looks like they won't be supporting anything other than 'systemd' going forward:

- With the release of psd version 6.x I will no longer be supporting alternative init systems such as upstart and openrc.

-**DennisL**

**Comment by cefn** [comment]
That seems fair enough, but I was assuming that systemd was just doing the job of starting up the program and providing a folder, so if I chose to launch it myself, then I could satisfy it's requirements by pointing to appropriate directories. 

Was thinking of pointing $XDG_RUNTIME_DIR to something in /var/run perhaps, as described at...  http://unix.stackexchange.com/questions/162900/what-is-this-folder-run-user-1000

However, I'm unfamiliar with the conventions and permissions which such a startup configuration should have in order for programs to behave themselves, and how this interacts with Chrome or Crouton chroot filesystem structures and conventions.

Perhaps the dependency on systemd is deeper than I recognise, though.

**Comment by DennisLfromGA** [comment]
@cefn - I don't know if you've seen this PR https://github.com/dnschneid/crouton/pull/2474 but it offers some hope I think.
