### ISSUE TITLE
-add-architecture and add-apt-repository not working

### ISSUE THREAD

**Issue by jcoonrod** [dnschneid/crouton#2490]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
#### Please describe your issue:

I've just loaded crouton in order to use skype, but this requires doing an -add-architecture i386 and an add-apt-repository to the skype location - and neither of these commands work. I've tried adding software-properties, and fiddling with multiarch - both to no avail.

**Comment by DennisLfromGA** [comment]
First, please complete the form that requested you enter: `sudo edit-chroot -all`
Then we can intelligently respond to your question.

**Comment by HaiKaiDo** [comment]
apt-get install software-properties-common    Should fix your issue. Keep in mind that if you have an ARM based machine there is no skype that will work for you unless you use something like exagear.
