### ISSUE TITLE
Chroot on USB causes mount problems

### ISSUE THREAD

**Issue by IamCarbonMan** [dnschneid/crouton#2492]
``` bash
$ sudo edit-chroot -a -c /media/removable/USB\ Drive/chroots
name: stretch
encrypted: no
Entering /media/removable/USB Drive/chroots/stretch...
crouton: version 1-20160206234800~master:daa872a0
release: stretch
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,keyboard,core
host: version 7647.84.0 (Official Build) stable-channel parrot_ivb 
kernel: Linux localhost 3.8.11 #1 SMP Thu Feb 18 00:33:08 PST 2016 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/chroots/stretch...
```
#### Please describe your issue:

Entering, exiting, or updating the chroot seems to have two strange effects. First, sometimes when I am in the chroot and open a new crosh shell, I will find that the USB drive is not mounted; that is, `mount | grep sdb` has no output. This happens while I am still working in the chroot on one crosh terminal or xorg/xiwi window. Second, sometimes when updating, entering or exiting the chroot, the USB is mounted in multiple places; that is, `mount | grep sdb` returns something like:

``` bash
/dev/sdb2 on /run/crouton/media/removable/USB Drive/chroots/stretch type ext4 (rw,relatime,dirsync,data=ordered)
/dev/sdb2 on /run/crouton/media/removable/USB Drive/chroots/stretch/media/removable/USB Drive type ext4 (rw,relatime,dirsync,data=ordered)
/dev/sdb2 on /run/crouton/media/removable/USB Drive/chroots/stretch/media/removable/USB Drive/media/removable/USB Drive type ext4 (rw,relatime,dirsync,data=ordered)
```

and so on.

**Comment by DennisLfromGA** [comment]
If your USB drive is identified as /dev/sdb and you chroot is running then `mount | grep sdb` will show multiple mount points, that's normal.
