### ISSUE TITLE
Black Screen, Only Cursor Shown. Gnome on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Polygon-6789** [dnschneid/crouton#2493]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome,keyboard
host: version 7834.60.0 (Official Build) beta-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:11:12 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue: 
When entering the chroot, all that is displayed is a black screen with a visible, and movable cursor.

#### If known, describe the steps to reproduce the issue:
When using the GNOME target on crouton, and then installing the "ubuntu-gnome-desktop" , "ubuntu-restricted-extras", and "ubuntu-restricted-addons". When entering the chroot a 2nd or 3rd time.

**Comment by tista500** [comment]
@Polygon-6789,

Could you please let us see your `$HOME/.xsession-errors` if it existed inside your chroot?
Usually when logging was started in X11 sessions, the first line of section would be: `Xsession: X session started for`.

2nd, I'm afraid that you might not be clarify you current 'locale'. As known well, gnome-terminal and some other apps need to look your current locale settings before launching itself. In general desktop installation, it could set that locale properly within install processes, but crouton sometimes forgot to do so. If that happens, you can re-set them with this workaround: https://github.com/dnschneid/crouton/wiki/Languages
(means I'm worried about `locale` returns `POSIX`).

Regards.

**Comment by Polygon-6789** [comment]
Thanks, updating my locales solved the problem!

**Comment by tista500** [comment]
@Polygon-6789,

OK.
I hope you could close this issue...

Regards.
