### ISSUE TITLE
xinit cannot type in console

### ISSUE THREAD

**Issue by giliammc** [dnschneid/crouton#2494]
```
name: spore
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/spore...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,extension,xiwi
host: version 7834.60.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Mar 10 03:33:26 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/spore as another instance is using it.
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,unity,xiwi,extension,audio
host: version 7834.60.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Mar 10 03:33:26 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
#### Please describe your issue:

Here are the steps that lead to the issue 

1: sudo enter-chroot (in chrome terminal)
2: xinit (in chroot terminal)
3: run wine application (in xinit terminal)\
4:quit wine application

once i quit the application i cannot type exit or even switch back to chrome. the only option i have is to hold the power button down until my chromebook shuts down

thank you in advance for any help

**Comment by DennisLfromGA** [comment]
I don't know why it's hanging but you could try a couple of things that might help you avoid a hard shutdown.

- Open a crosh shell session in VT2 (using <kbd>Ctrl+Alt+F2/RightArrow</kbd>)
- Login as user `chronos`
- To find processes still mounted enter: `sudo unmount-chroot -p trusty`
- Kill those processes

I found another quick *and dirty* way to close out the X window is to use: pkill crouton-fbserver

Note that these are not elegant ways to end your chroot session but I believe it's better than holding down the power button, that could lead to corrupt user directories,etc.

**Hopefully someone much wiser than me will see this and provide the *correct* solution(s)**

**Comment by giliammc** [comment]
i tried that and i cant switch to crosh

**Comment by DennisLfromGA** [comment]
@giliammc,

So you can't even get to VT2 using  <kbd>Ctrl+Alt+F2/RightArrow</kbd> ?

That's not good, I've run out of suggestions at this point.
Hopefully someone else will know what to do and help out.

Sorry,
-**DennisL**

**Comment by giliammc** [comment]
Thanks for trying

**Comment by DennisLfromGA** [comment]
@giliammc, No problem, just wish we could've figured it out. :'(

**Comment by zxvv** [comment]
I've seen this, and I believe one issue is that the X server is using VT1, so that one cannot see the chromebook desktop (also running on VT1) till the chroot's X server exits.

I don't know why it's using VT1, but I'm sure I can reproduce it.

And now that you mention it, perhaps we should be looking at the X server log. 

Another way to get out of this, is to switch to VT2 (ctrl-alt-"->"), login, and "pkill xinit".
