### ISSUE TITLE
I can't get into Ubuntu, please help

### ISSUE THREAD

**Issue by TheGlamourGroup** [dnschneid/crouton#2496]
```
Please paste the output of the following command here: sudo edit-chroot -all 
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: unity
host: version 7834.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue: I just got Ubuntu 12.04 LTS and tried upgrading to 14.04 LTS. It said that the upgrade finished but there were errors or something and I rebooted my chromebook and came back to the crosh shell. I put in sudo startunity and it says this:
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Creating hwaudio group with GID 18...
Changing cdrom GID from 24 to 19...
Changing floppy GID from 25 to 11...
Changing plugdev GID from 46 to 85...
Changing uucp GID from 10 to 14...
Changing video GID from 44 to 27...
Moving sudo GID from 27 to 28...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=1bafbe4d-a93e-3d41-be36-ea940fdb11e9/PARTNROFF=1 hashtree=PARTUUID=1bafbe4d-a93e-3d41-be36-ea940fdb11e9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=0f5340f74cd923b0d348939e445ed16762560183 salt=a2b9f363ce95098ff7c8c444935eb0548b4a07cd3c08fe9bd826c96d21a6fce1" noinitrd vt.global_cursor_default=0 kern_guid=1bafbe4d-a93e-3d41-be36-ea940fdb11e9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Mar 24 11:59:08 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 7834.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Then, I updated my chroot:**

chronos@localhost / $ sudo sh -e ~/Downloads/crouton -n precise -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startunity into the host...
Installing crouton-noroot into the chroot...
Installing startunity into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing crouton-unity-autostart into the chroot...
Installing unity-autostart.desktop into the chroot...
Installing unity-profiled into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
dpkg: dependency problems prevent configuration of printer-driver-gutenprint:
 printer-driver-gutenprint depends on libgutenprint2 (>= 5.2.10~pre2); however:
  Version of libgutenprint2 on system is 5.2.8~pre1-0ubuntu2.1.

dpkg: error processing package printer-driver-gutenprint (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 printer-driver-gutenprint
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**I tried sudo startunity again:**

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
dpkg: dependency problems prevent configuration of printer-driver-gutenprint:
 printer-driver-gutenprint depends on libgutenprint2 (>= 5.2.10~pre2); however:
  Version of libgutenprint2 on system is 5.2.8~pre1-0ubuntu2.1.

dpkg: error processing package printer-driver-gutenprint (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 printer-driver-gutenprint
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=1bafbe4d-a93e-3d41-be36-ea940fdb11e9/PARTNROFF=1 hashtree=PARTUUID=1bafbe4d-a93e-3d41-be36-ea940fdb11e9/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=0f5340f74cd923b0d348939e445ed16762560183 salt=a2b9f363ce95098ff7c8c444935eb0548b4a07cd3c08fe9bd826c96d21a6fce1" noinitrd vt.global_cursor_default=0 kern_guid=1bafbe4d-a93e-3d41-be36-ea940fdb11e9 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Mar 24 12:02:48 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: unity
host: version 7834.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**I'm frustrated. Anyone help?**

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup - 

>Failed to complete chroot setup.

There are *way* too many 'unknown's in your 'croutonversion' output.
It might be best if you entered it and let the setup script finish, if it's still there hopefully, by doing this:

`sudo enter-chroot -u root -n precise -xx`

-**DennisL**

**Comment by TheGlamourGroup** [comment]
I actually ended up deleting Ubuntu and getting out of developer mode, and restarting the whole again. but what do the 'unknown's indicate, do I need to update crouton? I'm reusing the same copy and I got it kinda a while ago.

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup - 

> I actually ended up deleting Ubuntu and getting out of developer mode, and restarting the whole thing again.  

If you got out of Developer mode, you're crouton chroot will have been removed along with all of the user data.

> but what do the 'unknown's indicate, do I need to update crouton?  

It means the crouton installation didn't finish and a setup script ~~is~~ *was* still there.

> I'm reusing the same copy and I got it kinda a while ago.  

I don't know what you mean by that.
You'll need to get a fresh copy of ['crouton](https://goo.gl/fd3zc)' and start again - I wouldn't use your old chroot even if you have it backed up.

-**DennsiL**

**Comment by TheGlamourGroup** [comment]
@DennisLfromGA Yeah I backed up my copy of crouton and reuse that every time I reinstall Ubuntu. I'll try a new copy if I run into anymore problems

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup - Why don't you try a new copy *before* you run into anymore problems???

**Comment by TheGlamourGroup** [comment]
@DennisLfromGA The update was already going before I got a new copy and it finished now but i'm back to the same error again, but this time the unknowns are replaced: 
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 7834.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Ubuntu said to restart the computer to finish updating but I can't even get into it

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup,

> ...but this time the unknowns are replaced

Believe it or not, that's great progress.

> Ubuntu said to restart the computer to finish updating but I can't even get into it

Now just reboot, open a crosh shell, and let it finish the setup by entering:

`sudo enter-chroot -u root -n precise -xx`

After that completes successfully, exit the chroot and try:

`sudo startunity`

-----

A word of advice: The 'precise' release is years old, I would recommend using the newer 'trusty' LTS release.

-**DennisL**

**Comment by TheGlamourGroup** [comment]
@DennisLfromGA When I enter that it says:
chronos@localhost / $ sudo enter-chroot -u root -n precise -xx
chroot: failed to run command '/prepare.sh': No such file or directory
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup, 

> Ubuntu said to restart the computer to *finish updating* but I can't even get into it

Okay, from the above I thought it hadn't finished since you said you couldn't get into it.

Maybe it *did* finish and all is well; just try this and see if you can get into it: `sudo enter-chroot -n precise`

If that works and you get a shell terminal session, then exit and try: `sudo startunity -n precise`

-**DennisL**

**Comment by TheGlamourGroup** [comment]
@DennisLfromGA When I put in the sudo enter-chroot -n precise, it says this:
chronos@localhost / $ sudo enter-chroot -n precise
Entering /mnt/stateful_partition/crouton/chroots/precise...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
dpkg: dependency problems prevent configuration of printer-driver-gutenprint:
 printer-driver-gutenprint depends on libgutenprint2 (>= 5.2.10~pre2); however:
  Version of libgutenprint2 on system is 5.2.8~pre1-0ubuntu2.1.

dpkg: error processing package printer-driver-gutenprint (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 printer-driver-gutenprint
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup,

> You may want to update your chroot again.

Try that first: sudo sh ~/Downloads/crouton -n precise -u`

If that doesn't work, get back into your chroot: `sudo enter-chroot -n precise`
If it wants to finish the setup script again, let it, then try this in the chroot:

`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get -f install`

See if that completes successfully, if so, try starting 'unity' again.

-**Dennis**

**Comment by TheGlamourGroup** [comment]
@DennisLfromGA Ok it says (precise)theglamourgroup@localhost:~$ like how it would in the Ubuntu terminal, I just never noticed it. I'm updating using those commands now

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup - 

It looks like you've regressed and your back to square one with all the 'unknown's.

I had asked you to "Try that first: sudo sh ~/Downloads/crouton -n precise -u`"
That might have 'fixed' it but we'll never know.

At this point I would 'punt' - just remove the chroot and install the 'trusty' release this time IMHO.

-**DennisL**

**Comment by TheGlamourGroup** [comment]
@DennisLfromGA How do I install the trusty release? Whenever I install Ubuntu it always takes me to 12.04 LTS.

**Comment by DennisLfromGA** [comment]
@TheGlamourGroup - *Please* familiarize yourself with the crouton [README](https://github.com/dnschneid/crouton/blob/master/README.md), the crouton [WIKI](https://github.com/dnschneid/crouton/wiki), and other sources first - it will save you and others unnecessary problems and false starts.

**Comment by TheGlamourGroup** [comment]
This may be good news, but I did the sudo sh ~/Downloads/crouton -n precise -u command and it worked. I also noticed the unknowns are replaced again:
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 7834.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
