### ISSUE TITLE
No audio working (after Chrome OS update)

### ISSUE THREAD

**Issue by wthit56** [dnschneid/crouton#2497]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: keyboard,xiwi,xfce
host: version 7834.60.0 (Official Build) stable-channel lumpy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Mar 10 05:57:13 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
name: xiwi
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xiwi...
Creating hwaudio group with GID 18...
su: pam_start: error 26
```

#### Please describe your issue:
No audio working at all. Youtube doesn't play, but loads in Chrome browser. MP3s don't play, videos don't play.

Recently updated chrome os, if that affects anything.

**Comment by divx118** [comment]
Try updating your chroot See https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting on how to.

**Comment by DennisLfromGA** [comment]
@wthit56,

It looks like you have at least two chroots - one named '**precise**' and one named '**xiwi**'.
It also looks like the one name '**xiwi**' didn't finish the installation or at least not successfully.

So, like @divx118 said, update the chroot your having problems with first, most likely '**xiwi**', then come back here if it's still giving you problems.

-**DennisL**

**Comment by wthit56** [comment]
@divx118 I've tried an update a few times, to no avail.

@DennisLfromGA As far as I understand it, Xiwi is the thing to get the Chrome OS "linux as a tab" stuff working. But when I first installed xfce, I didn't know that. So then later I tried to add xiwi to the xfce install. I guess I did it wrong or something? The "linux in a tab" stuff still doesn't work, so I guess so. Any advice on how to add that in, and remove that half-install of Xiwi?

But that's by-the-by. Either way, my actual linux instal is xfce, or "precise." And that's what I'm having audio trouble with... Hope that helps.

**Comment by DennisLfromGA** [comment]
@wthit56,

> ...and remove that half-install of Xiwi?

First, let's get rid of the semi-installed 'xiwi' chroot to free-up some space and simplify things by doing this:

`sudo delete-chroot xiwi`

-----

> Any advice on how to add that in...

No need to, according to croutonversion above, you already have 'xiwi', along with 'xorg' installed in your 'precise' chroot. Since 'xorg' is the default xmethod, you'll just need to specify '-X...' when you start it like this:

`sudo startxfce4 -n precise -X xiwi`

NOTE: If you haven't yet installed the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension, you'll need to do that first.

If you want to make 'xiwi' the *default* xmethod, you can re-add it to your chroot like this:

`sudo sh ~/Downloads/crouton -n precise -t xiwi -u`

Re-adding 'xiwi' to your chroot with crouton's update option has the added benefit of updating your entire chroot, not just adding 'xiwi' so it may also fix your audio problems - *BONUS*

-**DennisL**

**Comment by wthit56** [comment]
Thanks for the help on xiwi--though it's still not working, for whatever reason. I'll make a separate thread for that issue, though.

Still no joy. On the audio front. Things just hang when trying to play any audio (such as loading an mp3 into gnome-mplayer--it just says "loading" forever; or trying `aplay` in the terminal which just hangs).

**Comment by DennisLfromGA** [comment]
Some have had success with installing 'pulseaudio' in the chroot.

**Comment by wthit56** [comment]
Yes, I just tried that again and it still doesn't work. In fact, opening the PulseAudio Volume Control app doesn't get past "Establishing connection to PulseAudio. Please wait..."

**Comment by DennisLfromGA** [comment]
@wthit56, Well, you might take a look at alsa, which controls sound in Linux

**Comment by wthit56** [comment]
As in *install* "alsa"? What should I do?

**Comment by DennisLfromGA** [comment]
@wthit56 - 

Sorry, but I don't have the experience to guide you through step-by-step to resolve your problem, I'm just a typical user, not a developer. I'm throwing out ideas that come to mind; not knowing your exact scenario, it's very hard to tell you what to do.

You can take a look at the 'alsa' website for ideas, that's what I was referring to, see this site for instance -
- [SoundcardTesting](http://www.alsa-project.org/main/index.php/SoundcardTesting)

Hope this helps,
-**DennisL**

**Comment by wthit56** [comment]
Oh right. Thanks. I have tried quite a few things from different
audio-related threads here, so I've done stuff with alsa before, I think.
Maybe someone more experienced will be able to help... Thanks for trying
anyway! ^^

**Comment by DennisLfromGA** [comment]
@wthit56 - No problem. I agree we need someone else to step in at this point though.

**Comment by pcwalden** [comment]
I have the same problem after the last Chrome update. I will try some of the solutions suggested above and will add to this thread.

**Comment by pcwalden** [comment]
Here is my aplay output in Chrome and Crouton shells. Is the cras device no longer showing in the Chrome shell?

[aplayout.txt](https://github.com/dnschneid/crouton/files/192816/aplayout.txt)

**Comment by pcwalden** [comment]
I am getting sound but I have to run the app using sudo and specify the alsa device. For example:

sudo mplayer -ao alsa:device=hw=1.0 scifri201603111.mp3

**Comment by pcwalden** [comment]
The group owner seems to have changed to hwaudio, from audio:

$ ll /dev/snd
total 0
drwxr-xr-x  3 root root        240 Mar 28 19:33 ./
drwxr-xr-x 16 root root       2000 Mar 28 19:54 ../
drwxr-xr-x  2 root root         80 Mar 28 19:33 by-path/
crw-rw----  1 root hwaudio 116,  5 Mar 28 19:33 controlC0
crw-rw----  1 root hwaudio 116,  8 Mar 28 19:33 controlC1
crw-rw----  1 root hwaudio 116,  4 Mar 28 19:33 hwC0D2
crw-rw----  1 root hwaudio 116,  3 Mar 28 19:33 pcmC0D3p
crw-rw----  1 root hwaudio 116,  2 Mar 28 19:33 pcmC0D7p
crw-rw----  1 root hwaudio 116,  7 Mar 28 19:33 pcmC1D0c
crw-rw----  1 root hwaudio 116,  6 Mar 28 20:46 pcmC1D0p
crw-rw----  1 root hwaudio 116,  1 Mar 28 19:33 seq
crw-rw----  1 root hwaudio 116, 33 Mar 28 19:33 timer
(precise)pwalden@localhost:~/Music$ ll /dev/snd/by-path/
total 0
drwxr-xr-x 2 root root  80 Mar 28 19:33 ./
drwxr-xr-x 3 root root 240 Mar 28 19:33 ../
lrwxrwxrwx 1 root root  12 Mar 28 19:33 pci-0000:00:1b.0 -> ../controlC0
lrwxrwxrwx 1 root root  12 Mar 28 19:33 platform-byt-max98090 -> ../controlC1

**Comment by pcwalden** [comment]
Following the standard chroot update process worked for me. During the update I saw that the cras was recompiled, so you might want to go to a backup of your chroot and try another upgrade.

**Comment by wthit56** [comment]
Got it working by deleting crouton, redownloading it, restart the laptop (to clear any lingering mounted chroots), and updating again. I kinda half-updated linux itself to trusty, but it crashed half-way through, hence the restart. But it seemed to be working... Now I have a different problem (for a different thread).

Thanks for your help, guys!

**Comment by pcwalden** [comment]
Don't forget to close this issue if your problem is solved.

**Comment by wthit56** [comment]
Yes--sorry, @pcwalden...
If anyone has explanations on these things I might find useful, you can message me maybe?

**Comment by wthit56** [comment]
Or just leave another comment--wasn't sure if it would stop any more comments once closed ;D
