### ISSUE TITLE
Slow startup/sign out (1 minute +) Trusty - Unity - Extension

### ISSUE THREAD

**Issue by TsinghuaMike** [dnschneid/crouton#2498]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,touch,unity,extension
host: version 7834.60.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Thu Mar 10 03:29:27 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue:
After updating chrome os, my startup has run into this issue of taking over 1 minute long. It starts as a black screen, and eventually it loads. Same occurs when signing out. I tried updating crouton, but it doesn't update smoothly.

Here's a piece of it: (I use R studio/R so a lot of these updates seem to reference that)
sudo sh ~/Downloads/crouton -u -n trusty

The following NEW packages will be installed:
  i965-va-driver va-driver-all vdpau-va-driver
The following packages will be upgraded:
  coreutils gir1.2-javascriptcoregtk-3.0 gir1.2-webkit-3.0
  google-chrome-stable initramfs-tools initramfs-tools-bin libgraphite2-3
  libjavascriptcoregtk-1.0-0 libjavascriptcoregtk-3.0-0 libpam-modules
  libpam-modules-bin libpam-runtime libpam0g libtiff5 libtiff5:i386 libva1
  libwebkitgtk-1.0-0 libwebkitgtk-1.0-common libwebkitgtk-3.0-0
  libwebkitgtk-3.0-common linux-libc-dev linux-libc-dev:i386 openjdk-7-jre
  openjdk-7-jre-headless r-base r-base-core r-base-dev r-base-html r-cran-nlme
  r-doc-html r-recommended tzdata tzdata-java
33 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 134 MB of archives.
After this operation, 2587 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  i965-va-driver libva1 r-base-core r-cran-nlme r-base r-recommended
  r-base-dev r-doc-html va-driver-all r-base-html
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

So when I log into ubuntu, it tries again to update things but it just gives up:

udo startunity
Entering /mnt/stateful_partition/crouton/chroots/trusty...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] 

If some things need to be forced to be installed, how can I do that from the shell? I also have the same question about software updates once I log into unity. (software updates need to be forced through in the terminal because I can't get them to install by using the software updater) I suppose I could read about that elsewhere, but if anyone knows I appreciate the help.

**Comment by DennisLfromGA** [comment]
@TsinghuaMike, 

You might want to try entering the chroot and fixing the package errors first using something like this:

- `sudo enter-chroot -n trusty` (if it asks to finish the setup, choose 'n' for no.)
- `sudo apt-get update`
- `sudo apt-get -f install`
- `sudo apt-get upgrade`
- `exit`
- `sudo enter-chroot -n trusty -xx`

See if that finishes successfully, if so, exit and try `sudo startunity -n trusty`

-**DennisL**

**Comment by wucheeman** [comment]
I have the same problem. Very slow booting/very slow log-off on my Acer C720 which was previously very fast. I've updated all packages in Ubuntu 14.04.03. I am running the most recent version of crouton according to croutonversion. Chrome OS info: Version 49.0.2623.95 (64-bit)
Platform 7834.60.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.93.0
This is the March 10 2016 build.
Any suggestions for next steps? Thanks for any help!

**Comment by TsinghuaMike** [comment]
@DennisLfromGA 

First of all just want to say thanks for everything you do for the community of crouton users!

I went through these steps. It seems that one file from the cran archives is causing some problems, but it appears to have updated everything. I have to imagine I have the newest version of crouton but I don't know how to be 100% certain.

I'm curious about the difference between` sudo startunity -n trusty` and `sudo startunity` . Either way I updated things the best I could and launched unity through both methods and still no luck.

@wucheeman 

Sounds like you do have the same exact problem, and since your packages are all up to date, too, it's likely related to something else (such as the chrome os update). Thanks for sharing your situation.

**Comment by DennisLfromGA** [comment]
@TsinghuaMike,

>  I have to imagine I have the newest version of crouton but I don't know how to be 100% certain.

'crouton' implemented an indirect installer quite a while back that downloads the latest version of crouton when you run it so it's a pretty safe bet you have the latest version. But, to be absolutely sure, just re-download a new installer from here: https://goo.gl/fd3zc
You can check to see if you have the latest version of your chroot installed by entering this *inside* your chroot:

`sudo croutonversion -u`

-----

> I'm curious about the difference between `sudo startunity -n trusty` and `sudo startunity`

Usually, `sudo startunity` will suffice but some ppl have more than one chroot installed so I also like to add the name of the chroot using the '-n' option to eliminate any problems.

The start* scripts state this: "By default, it will log into the primary user on the first chroot found."

But I like to be cautious.

Updating the packages *inside* the chroot hopefully did fix those problems but you may still need to update your chroot using 'crouton'. I should have added that one more step to the above, sorry.
So, try this in a crosh shell outside your chroot and hopefully everything will be fixed:

`sudo sh ~/Downloads/crouton -n trusty -u`

If you get a Chrome OS update and your chroot(s) suddenly stop working or don't work well, it's a very good idea to do a 'crouton' update. If you have anything in your chroot you absolutely need, do a backup of your chroot first to be safe.

-----

If you *still* have problems launching 'unity', you might try using xmethod 'xiwi', it won't have hardware acceleration but it's pretty nifty and works great for non-graphics intensive stuff.
You can add it to your existing chroot like this:

`sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`

You'll also need to install the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) app from the webstore with it.

**Comment by TsinghuaMike** [comment]
I've done both the crouton integration style and the extension style, and now I quite enjoy the extension style. I ran into issues with my firefox in xiwi using gnome. And I found by switching to unity a lot of things ran smoother. I'm just not that experienced or knowledgeable with linux or crouton to really figure my way out of these small inconveniences that keep popping up.

1.  Question: If I switched to the xiwi, could I switch back with a code like:

`sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`

2. As for my issues with updating, they're still there:

`sudo sh ~/Downloads/crouton -n trusty -u`

3. Something appears to be related to R Studio. If worst comes to worst, I could try and just delete that? Obviously that's a frustration in it's own right, because I have to remember how to install all these dependencies, but I'm kind of running out of ideas. Maybe someone can weigh in on that before I do something potentially stupid!

`sudo croutonversion -u`
crouton: version 1-20160206234800~master:daa872a0
Retrieving latest version of crouton
latest: version 1-20160206234800~master:daa872a0

So it does appear that I have the latest crouton. 

4. Allow me to further characterize my problem.

- Firefox suddenly gets overloaded quite easily and starts to turn black. 

- Sometimes the command for the terminal doesn't work and I have to launch it manually. Other times it does work. 

- When waiting to startup, sometimes there's a huge mouse cursor on the screen, but it doesn't move. And when it loads sometimes I can't see the mouse cursor, but it does respond when I move it around and click on things.

**Comment by wucheeman** [comment]
I checked this morning. Although croutonversion said I had the most recent version, I ran "sudo sh ~/Downloads/crouton -u -n trusty" and crouton did indeed need an update. From the fast-scrolling text, it looked like there was a libc update... making me wonder if the response to the glibc bug hadn't screwed something up. Anyway, crouton is back to its usual snappy boot / logout behavior.

Thanks, Dennis. Someday I will get it into my head to always try a crouton update when it stops working as it should.

**Comment by TsinghuaMike** [comment]
Figured out my issue as well. Although it said my crouton was updated, it wasn't either.

The issue was exactly what I thought it was:

There were some missing keys and I was able to take this code:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABCDEFGH12345678`

and just substituted the keys with those from my previous post:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys  A902DDA375E52366`
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9`

So I suppose we could close this topic. Thanks again @DennisLfromGA Dennis

**Comment by DennisLfromGA** [comment]
@TsinghuaMike - Glad you figured it out and got it working. :+1: 

> Question: If I switched to the xiwi, could I switch back with a code like:
sudo sh ~/Downloads/crouton -n trusty -t extension -u

If you want to make 'xorg' the default instead of 'xiwi', just re-add it like this:
`sudo sh ~/Downloads/crouton -n trusty -t xorg -u`

However, when you have both 'xiwi' and 'xorg' installed and you want to use one or the other, just add the '-X' opiton something like this:

- For a new xorg 'desktop' use: `sudo startunity -n trusty -X xorg`
- For a new xiwi 'window' use: `sudo startunity -n trusty -X xiwi`
- For a new xiwi 'browser tab' use: `sudo startunity -n trusty -X xiwi-tab`

You can even create aliases and put them in your `.bashrc` file or a `.bash_aliases` file.
Something like this to run your chroot in a tab:

  `alias xiwitab='sudo startunity -X xiwi-tab'`

Then to run it just do: `xiwitab -n trusty` (the '-n trusty' part is optional.)

-**DennisL**

**Comment by wxv** [comment]
I had the same issue, Ubuntu 14.04 on Acer C740. Running `sudo sh ~/Downloads/crouton -u -n trusty` reduced the startup time to a few seconds, which is acceptable enough for me.
