### ISSUE TITLE
Error Timeout

### ISSUE THREAD

**Issue by HeroBrineDRG** [dnschneid/crouton#2500]
Please paste the output of the following command here.                                                       ```Entering/mnt/stateful_partition/crouton/chroots/precise...  
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:11:12 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=8006c220-338c-5740-b705-71af8bd68db2/PARTNROFF=1 hashtree=PARTUUID=8006c220-338c-5740-b705-71af8bd68db2/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=4e9b414bae166191f327061db1e0104e14931c37 salt=6e87672096a04fb9a0ba805901d389751453d204165b651c52f73d0c74f829e0" noinitrd vt.global_cursor_default=0 kern_guid=8006c220-338c-5740-b705-71af8bd68db2 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.2.log", Time: Sat Mar 26 18:16:29 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 7834.60.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:11:12 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Another instance of croutonclip running, waiting...
Another instance of croutontriggerd running, waiting...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Error timeout
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.```    

Sorry if the answer to this question is obvious but I am new to crouton and have been using it the past month. Recently when ever I try to start crouton I can't connect to the extension and it says error timeout and I don't know what to do because I can't open any chroot.

**Comment by DennisLfromGA** [comment]
@HeroBrineDRG,

> Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)

Hopefully, you may simply need install the 'crouton integration' extension as noted above.

-**DennsiL**
