### ISSUE TITLE
i cant start unity 

### ISSUE THREAD

**Issue by enohpsyeoj** [dnschneid/crouton#2501]
```
Please paste the output of the following command here: Downloading latest crouton installer...
######################################################################## 100.0%
unity target does not work in xephyr in raring due to missing egl support.
Invalid target "unity".
```

**Comment by DennisLfromGA** [comment]
@enohpsyeoj,

The 'New issue' template was asking you to paste the output of croutonversion so we can better help you. Please show us the output of: `sudo edit-chroot -all`

And, please show us exactly the command and options you used when installing the chroot.
They were probably something like:

`sudo sh ~/Downloads/crouton -r raring -t kde,unity ...`

It looks like you may be using an ARM processor so you may need to specify the 'xiwi' target.

Also, the 'raring' release has already reached [end-of-life](https://wiki.ubuntu.com/Releases) so it would be better to use something like 'trusty'.

-**DennisL**

**Comment by enohpsyeoj** [comment]
dennis ill have to ga back and restart t get the error again to nstall it i did : sudo sh -e ~/Downloads/crouton -t unity

**Comment by enohpsyeoj** [comment]
go not ga

**Comment by DennisLfromGA** [comment]
How about showing us the output of: `sudo edit-chroot -all` ???

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
