### ISSUE TITLE
Session not locked when suspend

### ISSUE THREAD

**Issue by jaimejimbo** [dnschneid/crouton#2502]
Closing lid on asus chromebook cb3-111 doesn't lock ubuntu's session, so all my data is exposed.

**Comment by DennisLfromGA** [comment]
@jaimejimbo ,

I believe it would only be 'exposed' if they *opened* the lid but I get your point.

You didn't say which desktop/target you're using but Unity has 'Power Management Preferences' to configure the lid action, see below -
![dckca](https://cloud.githubusercontent.com/assets/3418772/14068228/c9cea01e-f44a-11e5-8c90-ef0dbe3fd125.png)

And xfce / lxde have the Xfce Power Manager, see below -
![screenshot 2016-03-27 at 6 35 43 pm](https://cloud.githubusercontent.com/assets/3418772/14068230/e2c1c1aa-f44a-11e5-803d-56a4b9322484.png)

Other desktops may have the same or similar tools.

-**DennisL**

**Comment by tista500** [comment]
greetings,

In crouton, gnome(cinnamon)-settings-daemon has some limitations in accessing hardware switches via DBus:
```
power-plugin-WARNING **: Unable to inhibit lid switch: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Permission denied
```
Though there might be something to do with it, but I did not track this down yet... Once this happened, g-s-d could not detect the state of lid-switch and then it could not start its 'lock-on-suspend' patched feature (ubuntu specific gnome-shell feature, and unity as well maybe) anymore.

So workaround is lock manually before closing lid with something like 'pressing Super + L' or so...

Regards.

**Comment by jdloft** [comment]
I believe this is a recent regression. I just reinstalled my chroot (tried Gnome and XFCE) chroot after a Chrome OS reset and locking isn't triggered when notebook lid is closed. The computer does suspend, though. None of the recent commits hints at a change that removed or broke the feature.
