### ISSUE TITLE
How can I use this wrapper script?

### ISSUE THREAD

**Issue by Mediocorite** [dnschneid/crouton#2506]
In your power management article [https://github.com/dnschneid/crouton/wiki/Power-manager-overrides] you wrote a wrapper script which looks like can save me a lot of trouble. How can I use it?
The only way i know how to use scripts is by downloading them and launching them using sh command. Please help

**Comment by DennisLfromGA** [comment]
@Mediocorite,

You would save @MAkerboom's script to ~/Downloads or somewhere in your $PATH,
  ( you can name it `lid-idle` or something else you prefer ) 
edit it to replace `startunity` on line 13 with *your* start* script if need be,
and then execute it with: `sudo sh ~/Downloads/lid-idle`

-**DennyL**

**Comment by Mediocorite** [comment]
Do I have to excute everytime i boot chroot or only when there is a chrome OS update?

**Comment by DennisLfromGA** [comment]
Yup.
