### ISSUE TITLE
VirtualBox startup failures *even after* usual post-CrOS upgrade fixes

### ISSUE THREAD

**Issue by laurenweinstein1** [dnschneid/crouton#2508]
Hmm. After the most recent CrOS upgrade, I'm getting the typical:

Kernel driver not installed (rc=-1908)

error when starting VirtualBox. However, my usual scripts to fix this -- setting the kernel flags, setting rw -- while apparently successful in their actions -- have not fixed the error this time.

Before I start screwing around with the kernel headers and dig myself in deeper, has anyone else seen a problem with this cycle? 

I've already done a crouton update, and updated VirtualBox. 

Any suggestions?  Thanks!

**Comment by DennisLfromGA** [comment]
@laurenweinstein1 - 

Same thing happenned to me and I'm still unable to fix it.

Normally, I run the change-kernel flags and sometimes I've had to run setup-headers in the chroot
but this time I get nowhere with that. I also upgraded VirtualBox, I guess I may have borked something doing that.

We'll have to wait until @divx118 or someone else has time to take a look or can hold our hand through it.

-**DennisL**

**Comment by laurenweinstein1** [comment]
Thanks. Will hold off tinkering with it myself!

L

**Comment by laurenweinstein1** [comment]
Anyone have any ideas on this? Dead in the water here. Thanks.

**Comment by laurenweinstein1** [comment]
New CrOS version came in. Did the usual fixes. Still no joy.

**Comment by divx118** [comment]
@laurenweinstein1 @DennisLfromGA  which kernel are you guys using? `uname -a`

**Comment by laurenweinstein1** [comment]
Still 3.8.11. Thanks.

L

**Comment by divx118** [comment]
Ok 3.8.11 I am building now. It will be up in about 15 minutes

**Comment by laurenweinstein1** [comment]
Super. What's the safest install technique? Thanks again!

L

**Comment by divx118** [comment]
Normally you can just run `sudo apt-get update && sudo apt-get upgrade`  on the commandline in the chroot.

**Comment by laurenweinstein1** [comment]
Got it. Much appreciated.

L

**Comment by divx118** [comment]
Ok done they are up now https://github.com/divx118/crouton-packages/commit/4d0cc4786a3d4b4942e81a7397990db226bec5d2

**Comment by laurenweinstein1** [comment]
Did the sudo apt-get update && sudo apt-get upgrade -- nothing header
related came in and drivers still not loading. Thanks.

L

**Comment by divx118** [comment]
@laurenweinstein1 Try running the setup-headers script again.
Open a shell in your chroot:
```
$ cd ~
$ wget https://raw.githubusercontent.com/divx118/crouton-packages/master/setup-headers.sh
$ sudo sh setup-headers.sh
```

**Comment by laurenweinstein1** [comment]
I'm at the:

You are attempting to install a kernel image (version 3.8.11) However,       
 | the directory /lib/modules/3.8.11/kernel still exists.  If this              
 | directory belongs to a previous linux-image-3.8.11 package, and if you       
 | have deselected some modules, or installed standalone modules packages,      
 | this could be bad.  

selection, seeking OK or move /lib/modules/3.8.11/kernel out of the way.

How do I proceed. I've gotten burned by this before and had an unbootable chroot when
I apparently made the wrong choice.

Thanks.

L


On 04/02 08:44, Maurice van Kruchten wrote:
> @laurenweinstein1 Try running the setup-headers script again.
> Open a shell in your chroot:
> ```
> $ cd ~
> $ wget https://raw.githubusercontent.com/divx118/crouton-packages/master/setup-headers.sh
> $ sudo sh setup-headers.sh
> ```
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dnschneid/crouton/issues/2508#issuecomment-204741029--Lauren--
Lauren Weinstein (lauren@vortex.com): http://www.vortex.com/lauren 
Founder:
 - Network Neutrality Squad: http://www.nnsquad.org 
 - PRIVACY Forum: http://www.vortex.com/privacy-info
Co-Founder: People For Internet Responsibility: http://www.pfir.org/pfir-info
Member: ACM Committee on Computers and Public Policy
Lauren's Blog: http://lauren.vortex.com
Google+: http://google.com/+LaurenWeinstein 
Twitter: http://twitter.com/laurenweinstein
Tel: +1 (818) 225-2800 / Skype: vortex.com
I have consulted to Google, but I am not currently 
doing so -- my opinions expressed here are mine alone.

**Comment by laurenweinstein1** [comment]
It's Groundhog day all over again. Even though I aborted the last step of
the header install as described above, headers seem confused. Ubuntu
updater keeps wanting to reinstall them, and crouton-update is failing with
header-related messages. Haven't I been here before? Also, after I ran the
header update shell file (and aborted at the last step), I'm now seeing an
rc.d error from apt-get. I have to grab it next time. I already moved back
my rc.local (that already has the module loading section in it).

**Comment by divx118** [comment]
@laurenweinstein1 You should have just completed the setup-headers script. by overwriting the kernel. Also it is wise to create a backup of your chroot, so you can always restore.
I just updated the 3.8.11 headers on my system with no problems. After rebuilding the vboxdrv modules they loaded with no problems.

**Comment by laurenweinstein1** [comment]
I reran the setup-headers script and let it run to completion including the kernel overwrite without obvious errors. Ubuntu updater has stopped asking to update the headers. Crouton-update ran to completion OK. However, the drivers are still not loading, e.g.:

modprobe: ERROR: could not insert 'vboxdrv': Invalid argument

**Comment by divx118** [comment]
@laurenweinstein1 You need to recompile the drivers with the new headers installed. If you installed virtualbox from oracle just run `sudo /etc/init.d/vboxdrv setup` to do that. If you installed virtualbox from ubuntu repo then you have no `/etc/init.d/vboxdrv` script. I forgot how to do it then. I will see if I can find it again.

**Comment by laurenweinstein1** [comment]
@divx118 That did it (using the script for directly installed VB). Back up. Thanks!!

L

**Comment by divx118** [comment]
@laurenweinstein1 Great, can you please close this issue then. Thanks
