### ISSUE TITLE
Another instance of croutonclip running, waiting...

### ISSUE THREAD

**Issue by wthit56** [dnschneid/crouton#2509]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160330180425~master:43e2fca0
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,xfce
host: version 7834.60.0 (Official Build) stable-channel lumpy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Mar 10 05:57:13 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
```
I cannot get into linux (`sudo startxfce4`) or run xiwi'd modules (`sudo startxiwi smplayer`). They both end with the message: "Another instance of croutonclip running, waiting..." which I have no clue about.

A couple of possible contributing factors:
- I ran a "background" xiwi for an app. I then made the mistake of closing the tab, which did not actually terminate the application itself (that would be a nice feature to add in, by the way).
- I then sent a SIGTERM to the process in question to stop the darned video from playing in the app--but maybe that left some unresolved state hanging around in some way..?

Also, I always seem to get the message: "Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it." This happens even when there is no linux open anywhere (as far as I can see), and there is only that one terminal tab open (not `enter-chroot`ed). The only thing that seems to clear this up is to restart the laptop. Not sure if that has something to do with the problem above, or if I just don't understand what it means; but any help on that score would be appreciated, also.

Thanks in advance for your help!

**Comment by tista500** [comment]
@wthit56,

After reading #1456, `sudo unmount-chroot -f your_chroot_name` may help you.

Regards.

**Comment by wthit56** [comment]
Ah, okay. THanks, @tista500. I've kinda sorted this by restarting the laptop, so I'll probably close this soon. Still curious as to what it all means though, if some kind soul would like to enlighten me..? ^^

**Comment by wthit56** [comment]
All seems to be working okay for me right now; I'll reopen if something like this happens again.
