### ISSUE TITLE
Xiwi External Storage

### ISSUE THREAD

**Issue by wthit56** [dnschneid/crouton#2512]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160330180425~master:43e2fca0
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,xfce
host: version 7834.66.0 (Official Build) stable-channel lumpy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 29 03:53:16 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

I can't seem to see external storage drives (USB, SD) within a Xiwi app (full linux seems to work okay). I'm using VLC in particular; in xfce it shows all the drives when trying to open a file, but in a windowed xiwi app version it only shows "Computer" (/) and my home directory (/home/...).

**Comment by drinkcat** [comment]
The files should be bind mounted properly in /media.
