### ISSUE TITLE
Crackly audio in xiwi

### ISSUE THREAD

**Issue by spencerrecneps** [dnschneid/crouton#2514]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160330180425~master:43e2fca0
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi
host: version 7834.66.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 29 04:00:50 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ 
```
#### Please describe your issue:

I installed a Trusty xiwi chroot and am attempting to run a MythTV frontend that connects to a separate backend server. Everything works fine except for audio, which is crackly. As far as I can tell, there is no Pulseaudio server running and the MythTV settings are routing audio through alsa:cras.

Audio tested in the chroot but outside of MythTV via `aplay -Dcras /usr/share/sounds/alsa/Front_Center.wav` seems to work OK.
#### If known, describe the steps to reproduce the issue:

Install Trusty xiwi chroot
Install MythTV `sudo apt-get install mythtv-frontend`
Run MythTV

**Comment by helpdeskdan** [comment]
Arg!  I just upgraded my beta to find I now have the same issue!
