### ISSUE TITLE
Keyboard layout switching under Unity

### ISSUE THREAD

**Issue by larixer** [dnschneid/crouton#2515]
Hi There,

This is not really an issue, but rather an observation that might be helpful for other people using Crouton and having problems with switching keyboard layout under Unity. 
1. I've noticed that at least under Ubuntu Trusty if gnome-settings-daemon gets installed into the system the keyboard layout switching does not really work. One should have unity-settings-daemon installed instead and gnome-settings-daemon MUST be uninstalled.
2. Another important thing, after crouton installation, gnome-language-selector should be launched and languages need to be configured within it. It then installs necessary packages for language support. 

Thank you very much for doing such an amazing project as Crouton!

I hope other users could check these guidelines and they will be moved into Keyboard wiki page after verification.

**Comment by yannym** [comment]
I can confirm that the above fix, did repair my broken keyboard controls such as changing brightness and volume. However, as I am using xenial, I had to install ````unity-settings-daemon```` as ````ubuntu-settings-daemon```` is not present in xenial. In addition, because I was using gnome, removing ````gnome-settings-daemon```` would have removed all of gnome so I ran ````$ sudo dpkg -r --force-all gnome-settings-daemon````

**Comment by vlasenko** [comment]
Actually in Trusty it is unity-settings-daemon as well, no such package as ubuntu-settings-daemon. I have fixed my description. Thanks for noticing.
