### ISSUE TITLE
Unable to remove croot from chromebook with sudo delete-chroot evilchroot

### ISSUE THREAD

**Issue by plasmafart** [dnschneid/crouton#2517]
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: kde
host: version 7834.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

When i try to remove croot with sudo delete-chroot evilchroot it gives me /mnt/stateful_partition/crouton/chroots/evilchroot not found.
Im trying to remove croot because i all of a sudden have no space on my chromebook and i am unable to enter KDE because there is no space left. i want remove croot and free up space on my chromebook.

**Comment by plasmafart** [comment]
Here is what happens when i try to start KDE 









Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cd3f1204-a214-3343-a31e-94209b777256/PARTNROFF=1 hashtree=PARTUUID=cd3f1204-a214-3343-a31e-94209b777256/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=0f5340f74cd923b0d348939e445ed16762560183 salt=a2b9f363ce95098ff7c8c444935eb0548b4a07cd3c08fe9bd826c96d21a6fce1" noinitrd vt.global_cursor_default=0 kern_guid=cd3f1204-a214-3343-a31e-94209b777256 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Apr  5 12:55:02 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
setversion 1.4 failed: Permission denied
crouton: version 1-20160206234800~master:daa872a0
release: precise
architecture: amd64
xmethod: xorg
targets: kde
host: version 7834.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 10 05:45:38 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
cat: write error: No space left on device
startkde: Starting up...
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
kbuildsycoca4 running...
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
kded(16054) LayoutMemoryPersister::restoreFromFile: Failed to open layout memory xml file for reading "/home/plasma/.kde/share/apps/kded/session/keyboard/layout_memory.xml" error: 5 
The following installation problem was detected
while trying to start KDE:

    $HOME directory (/home/plasma) is out of disk space.

KDE is unable to start.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
kded(16054)/kdecore (KConfigSkeleton) KCoreConfigSkeleton::writeConfig:
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: name 'org.kde.kglobalaccel' had owner '' but we thought it was ':1.5'
kglobalaccel(16058) KConfigIniBackend::writeConfig: Couldn't write "/home/plasma/.kde/share/config/kglobalshortcutsrc" . Disk full? 
startkde: Could not start ksmserver. Check your installation.
startkde: Shutting down...
klauncher: Exiting on signal 1
kded(16054) LayoutMemoryPersister::saveToFile: Failed to store keyboard layout memory, error 4 
startkde: Running shutdown scripts...
startkde: Done.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/precise...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/precise...

**Comment by divx118** [comment]
@plasmafart You should replace "evilchroot" in `sudo delete-chroot evilchroot` with the name of the chroot. In your case it should be `sudo delete-chroot precise` It seems your chromebook is running out of space seeing.

> $HOME directory (/home/plasma) is out of disk space.
