### ISSUE TITLE
gnome-session-flashback not installing on xenial

### ISSUE THREAD

**Issue by yannym** [dnschneid/crouton#2519]
```
$ sudo sh /media/removable/USB/bin/edit-chroot -all
name: chroot
encrypted: no
Entering /media/removable/USB/chroots/chroot...
crouton: version 1-20160206234800~master:daa872a0
release: xenial
architecture: amd64
xmethod: xorg
targets: extension,x11,gnome,keyboard,audio
host: version 8134.0.0 (Official Build) dev-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Thu Mar 31 05:08:07 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB/chroots/chroot...
```

Attempting to install a xenial chroot with the "gnome" target results in the following-

```
Package gnome-session-fallback is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gnome-session-flashback

E: Package 'gnome-session-fallback' has no installation candidate
Failed to complete chroot setup.
Unmounting /media/removable/USB/chroots/chroot...
```

I had assumed this was fixed a while back as referenced in #1689 
I was using XFCE prior to this on xenial, and decided to erase my chroot and start fresh with gnome, but it is not working, attempting to modify the crouton file to target other forks does not change anything either.

**Comment by yannym** [comment]
Alright, I went and edited the /etc/crouton/targets file manually and removed the gnome target, this allowed me to complete the chroot installation, I am now going to attempt installing gnome inside the chroot manually. I will report if this works...

**Comment by yannym** [comment]
After installing gnome manually I got everything working smoothly, here's what I did.

````
$ sudo chown chronos:chronos /media/removable/USB/chroots/chroot/etc/targets
$ sudo sh ~/Downloads/crouton -u -n chroot -p /media/removable/USB -r xenial
````
After I got the chroot to complete its installation, I installed gnome like this.
(The chown command was only used so I could edit the targets file with a chrome os text editor)
(My chroot is installed to an external usb, thats why I keep working in that directory)
````
$ sudo apt-get install gnome-shell
$ startgnome
````
The first command only installs the shell, as I did not want the full package
This workaround should be able to get gnome working with xenial, until a fix is implemented.

**Comment by nahtnam** [comment]
Hey!

I am having this same issue when installing crouton with encryption, gnome, and xenial. I tried the above commands and replaced the location with my location and it didnt work. Any other fix?

@yannym You should probably leave this open until its fixed.

Thanks.

**Comment by alexluecke** [comment]
This is still an issue and should not be closed.

**Comment by divx118** [comment]
Actually this is a duplicate. #1706 #2355 and #2429 is the relevant pull request.
