### ISSUE TITLE
Compiling issues, Permission Denied, trusty xfce

### ISSUE THREAD

**Issue by digheal** [dnschneid/crouton#2522]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

targets : keyboard 

Hi all,
For some reason, any of the IDE's that I am trying are able to run code, they all throw a Permission denied in the output window.
[Screencap](http://imgur.com/nPIz2BP)
Is this because I have encrypted the chroot?
I have tried opening/starting the file, within the chroot, and in the shared downloads folder, but to no avail. 

I also tried 
$ `sudo` chmod 755 ~/Desktop/testfile
but that did not change the outcome. 

Here are the permissions that show after the $ sudo ls -l
[Pastebin link](http://pastebin.com/QaC14x5z)

I don't know what could be wrong.  
I am using the codeblocks IDE for my C++ class.

**Comment by 6ghosts** [comment]
You should try using 
`sudo su`
then
`chmod 755 ~/Desktop/testfile`

Another method is cding to the desktop.
`cd Desktop`
and trying this
`chmod 755 testfile`
