### ISSUE TITLE
Crouton loses added network (ifconfig) interfaces and routes when coming out of sleep

### ISSUE THREAD

**Issue by laurenweinstein1** [dnschneid/crouton#2526]
I have a number of ifconfig commands (e.g. to create eth0:100) and routes that are added to my chroot on boot (in /etc/rc.local). They work fine. However, it appears that all of the added network interfaces and associated added routes vanish when the crouton trusty chroot comes out of sleep. Any suggestions on avoiding this? Thanks! Addendum: Putting commands to redo these actions in a /usr/lib/pm-utils/sleep.d wakeup script appears not to function.

**Comment by drinkcat** [comment]
Probably conflicting with whatever Chromium OS/shill decides to do.
