### ISSUE TITLE
/home/.shadow/ takes up several GB of space: are these encrypted copies of (deleted) Downloads files? How to remove them?

### ISSUE THREAD

**Issue by ataiprojects** [dnschneid/crouton#2527]
```
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20150620222151~master:89796a99
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi
host: version 7834.66.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Mar 29 03:18:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160330180425~master:43e2fca0
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 7834.66.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Mar 29 03:18:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```
#### Please describe your issue:

Very little free disk space: even after cleaning up the Downloads folder, 9.4G out of 11G is still used in /home/.shadow/[long id]/vault. How to clean it up?

**Comment by DennisLfromGA** [comment]
@ataiprojects - You could try going to `chrome://drive-internals` , then click on the *"Clear local metadata"*

**Comment by ataiprojects** [comment]
@DennisLfromGA This has cleared something, but not the main problem, I fear. Local Free Space went from 573 MB to 576 MB, but the home/.shadow/[long id]/vault still appears to be nearly full:
`Filesystem                                                    Size  Used Avail Use% Mounted on
/dev/mmcblk0p1                                                 11G  9.2G  570M  95% /
devtmpfs                                                      1.9G     0  1.9G   0% /dev
shmfs                                                         1.9G  188M  1.8G  10% /dev/shm
tmp                                                           1.9G   38M  1.9G   2% /tmp
tmpfs                                                         387M   28K  387M   1% /run
tmpfs                                                         5.0M     0  5.0M   0% /run/lock
run                                                           1.9G  424K  1.9G   1% /var/host/dbus
/dev/mapper/encstateful                                       3.1G  128M  2.9G   5% /var/host/timezone
/dev/root                                                     1.2G  1.1G  127M  90% /lib/modules/3.10.18
media                                                         1.9G     0  1.9G   0% /var/host/media
/dev/sda1                                                      29G  1.7G   28G   6% /var/host/media/removable/USB DISK
/home/.shadow/6aea447d1e0f0238e004d0fc480141318520e2c7/vault   11G  9.2G  570M  95% /home/slavek/Downloads
none                                                          1.9G   24K  1.9G   1% /sys/fs/cgroup
`

**Comment by DennisLfromGA** [comment]
@ataiprojects,

Then you might be in need of a ['powerwash'](https://support.google.com/chromebook/answer/183084?hl=en&source=genius-rts)
But before you do that -
- make sure you've backed up everything you need in Downloads - for each account setup on the Chromebook
- backup your crouton chroot(s) using `sudo edit-chroot -bf /path/to/external/media [chrootname]`  
  you can use the 'USB DISK' for that most likely.

-*DennisL*

**Comment by ataiprojects** [comment]
@DennisLfromGA Ok, since there's no other way around it, I've just backed-up, powerwashed and freshly downloaded crouton into Downloads folder. Now:
`chronos@localhost / $ sudo edit-chroot -f /media/removable/"USB DISK"/chroot/trusty-20160412-1319.tar.gz -r trusty
sudo: edit-chroot: command not found`
What am I missing?

**Comment by divx118** [comment]
You should run `sudo sh ~/Downloads/crouton -f /media/removable/"USB DISK"/chroot/trusty-20160412-1319.tar.gz` There is no `edit-chroot` yet in `/usr/local/bin/`, because of the powerwash.

**Comment by ataiprojects** [comment]
Done. Thank you @DennisLfromGA and @divx118 for instructions! Still:
Filesystem                                                    Size  Used Avail Use% Mounted on
/dev/mmcblk0p1                                                 11G  8.8G  951M  91% /
devtmpfs                                                      1.9G     0  1.9G   0% /dev
shmfs                                                         1.9G   53M  1.9G   3% /dev/shm
tmp                                                           1.9G  304K  1.9G   1% /tmp
tmpfs                                                         387M   28K  387M   1% /run
tmpfs                                                         5.0M     0  5.0M   0% /run/lock
run                                                           1.9G  428K  1.9G   1% /var/host/dbus
/dev/mapper/encstateful                                       3.1G   53M  3.0G   2% /var/host/timezone
/dev/root                                                     1.2G  1.1G  126M  90% /lib/modules/3.10.18
media                                                         1.9G     0  1.9G   0% /var/host/media
/home/.shadow/76f5cc90bc1fda4a4796685d27ccdbb73dcccae3/vault   11G  8.8G  951M  91% /home/slavek/Downloads
none                                                          1.9G   24K  1.9G   1% /sys/fs/cgroup
/dev/sda1                                                      29G  9.2G   20G  32% /var/host/media/removable/USB DISK

So what is it then, in the .shadow/.../vault, which takes up so much space even after powerwash? Is it normal?

**Comment by areyoueye** [comment]
I am having the same issue.  Any updates on this?

**Comment by areyoueye** [comment]
It seems that the /home/.shadow/<some id>/vault is mounted on /home/<user>/Downloads.
/dev/mmcblk0p1/ is mounted on /home.  This also happens to be mounted on the / of my chroot.  So the 'Used' amount you see attributed to /home/.shadow/<id>/vault should be the same as /dev/mmcblk0p1 (your chroot's /).

If your chroot is full I'd recommend looking at 'du -h -d 1 /home/<user>'

**Comment by ataiprojects** [comment]
@areyoueye du -h -d 1 /home/<user>' shows 1.3G, while /home/.shadow/<some id>/vault - 8.8G out of 11G, so it must be something else. This doesn't normally disturb me since I use a USB stick as a main storage. Still, I don't understand what this shadow vault is full of and where exactly it is located. Any other ideas? Thanks

**Comment by ataiprojects** [comment]
Once again I have a "Device space critically low" notification pop up...
chronos@localhost / $ sudo du -h -d 1 /home/
1.4G    /home/user
132K    /home/root
2.7G    /home/.shadow
2.7G    /home/chronos
6.7G    /home/
I have read here: https://www.reddit.com/r/Crouton/comments/3qy64a/cant_free_disk_space_on_chromebook/ that deleting files from Downloads folder may not completely remove them - and I think it is exactly my problem: I once let many files accumulate in the Downloads folder, but after deleting them all, the space did not free up much.

The poposed solution in the link above is to check ls - l /home/chronos/user/Downloads/.Trash-1000/files/, but for me this shows "No such file or directory".

If according to  https://chromium.googlesource.com/chromiumos/platform/cryptohome/+/0.12.369.B/README,
/home/.shadow/<s_h_o_u>/vault  is The user's vault (the encrypted version of their home directory), and I don't have anything in Downloads anymore, can the files in the vault be removed too?

@DennisLfromGA @divx118 @rjloura @drinkcat Have you encountered anything similar. Thank you!
