### ISSUE TITLE
-n option of croutonurlhandler does not work

### ISSUE THREAD

**Issue by patelbhavesh** [dnschneid/crouton#2528]
Whether we use -n or no parameters the behavior is the same and it throws you to the same URL which you are opening.
So for example if you issue the command
croutonurlhandler http://www.google.com or croutonurlhandler -n http://www.google.com , in both cases the focus is shifted to the newly opened tab with www.google.com

**Comment by DennisLfromGA** [comment]
@patelbhavesh,

What 'xmethod' are you using?
I believe it will only switch back to Chrome OS when using 'xmethod:xorg'

-*DennisL*

**Comment by patelbhavesh** [comment]
Thank you Dennis for responding.I am using xiwi.

**Comment by patelbhavesh** [comment]
I had already tested with croutoncycle cros where in stays in the chrome os tab which i run it from 
Also I am unable to change the xmethod from xiwi to anything else inspite of running 
$xinit -X xorg & and yes i have the x11/xorg target installed.

**Comment by DennisLfromGA** [comment]
@patelbhavesh,

You can use the '-X' option with your `start*` script, like `sudo startxfce4 -X xorg`
Or you can re-install the 'xorg' target to make it the default
( or edit the chroot's `/etc/crouton/xmethod` file to us xorg instead of xiwi )

-**DennisL**

**Comment by patelbhavesh** [comment]
You are perfectly right .Seems like it only works in xorg(and maybe x11).So once I changed it the xmethod to xorg in /etc/crou* it started working.
So should this bug be closed or keep it open as an enchancement request to make it work in xiwi ? or technically it might never be possible to make it work in xiwi ?

**Comment by DennisLfromGA** [comment]
It's my understanding that it won't switch in 'xiwi' but maybe someone with a better understanding of it will let us know for sure. And also let us know if this issue can be closed.
