### ISSUE TITLE
Ubuntu installing apache2 subversion

### ISSUE THREAD

**Issue by CryptoMatrix** [dnschneid/crouton#2529]
Hello everyone.
I am trying to install subversion apache2 using the code: sudo apt-get install subversion apache2 libapache2-svn , but when I use that code I get this error: 
Setting up libapache2-mod-svn (1.8.8-1ubuntu3) ...
dpkg: error processing package libapache2-mod-svn (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of libapache2-svn:
 libapache2-svn depends on libapache2-mod-svn; however:
  Package libapache2-mod-svn is not configured yet.

dpkg: error processing package libapache2-svn (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                          Errors were encountered while processing:
 libapache2-mod-svn
 libapache2-svn
E: Sub-process /usr/bin/dpkg returned an error code (1)

Could anyone tell me how to solve this problem?
Thank you!

**Comment by 6ghosts** [comment]
Haven't heard of this issue before, you could try purging it.
If that doesn't work, I recommend updating, a distribution upgrade, and a reboot.
`apt-get update`
`apt-get dist-upgrade`
`reboot`

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by rahulghanate** [comment]
I am facing the same issue, and dist-upgrade is not helping it.

**Comment by rahulghanate** [comment]
Found the issue,
My old file /etc/apache2/mods-enabled/dav_svn.conf was causing the configuration issue. Had to remove it make apt-get install work.
