### ISSUE TITLE
Newbie looking for help

### ISSUE THREAD

**Issue by zacknorman** [dnschneid/crouton#2531]
Hey guys,

Recently I've been trying to install Plasma 5 on my crouton, I'm running a Nyan-Blaze HP chromebook. I've had no success adding the 'kubuntu/next' launchpad PPA (tells me it doesn't exist) and I don't know where to go next. Is there any way to install Plasma 5 on the crouton? It looks fantastic, and I heard it runs great on the Chromebook.
Any help is greatly appreciated 
(This is a question, someone should probably mark it as such)

**Comment by AdmiralAsshat** [comment]
Did a standard wily + kde install not give you Plasma 5?

**Comment by zacknorman** [comment]
I didnt think it would, because Xenial + KDE didn't give me Plasma 5, but I'm going to try Wily + KDE right now and I'll let you know

**Comment by zacknorman** [comment]
Update: The wily install with the KDE target errors out halfway through the install

`E: Unable to locate package kde-plasma-desktop`

Sounds like a problem in the script, or my CB doesn't support that package...?

**Comment by 6ghosts** [comment]
`sudo apt-get install kde-standard -y `

**Comment by AdmiralAsshat** [comment]
See [https://github.com/dnschneid/crouton/issues/2260](url) and try the fix there. I believe that's what I had to do to get wily working.

Sorry for not mentioning it earlier, I did my wily-plasma install several months ago and I saw some commits on one of those tickets, so I assumed it had been fixed upstream.

**Comment by zacknorman** [comment]
@AdmiralAsshat  Thanks a ton, I'm going to check it out right after class, I'll let you know how it works out!

@6ghosts Says there's no package by that name

**Comment by zacknorman** [comment]
Update: @AdmiralAsshat I got Plasma up and running by following those steps, but whenever I 
`sudo startkde`
It loads the login screen, then I'm greeted with an error message 
> we are sorry, Plasma closed unexpectedly
With an option to file a bug report and do a few other things
And I'm unable to do anything, it just keeps displaying the error.
Any help is really appreciated, thanks for all the help so far!

**Comment by AdmiralAsshat** [comment]
I believe your Nyan-Blaze is ARM-based. I'm on a 2013 Pixel, which is Intel-based, so I'm afraid it's difficult for me to try to duplicate your scenario because our laptops will download different packages. I do apologize for that.
  
You may wish to try some of the troubleshooting steps [here](https://github.com/dnschneid/crouton/issues/2440), namely jumping into your chroot manually and trying to update your packages like so:

> sudo enter-chroot
> sudo apt-get update
> sudo apt-get install -f
> sudo apt-get upgrade
> exit

If that still fails, you may wish to grab the output from your terminal before KDE launches or during the crash and spit them out here so that we can take a look and advise.

Good luck!

**Comment by zacknorman** [comment]
Okay, @AdmiralAsshat . so it seems as if KDE is hanging on some PID being killed -- check this out

`libEGL warning: DRI2: failed to authenticate
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Qt: Session management error: networkIdsList argument is NULL
klauncher not running... launching kdeinit
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
kdeinit5: preparing to launch 'libkdeinit5_klauncher'
kdeinit5: Launched KLauncher, pid = 23916, result = 0
libEGL warning: DRI2: failed to authenticate
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Qt: Session management error: networkIdsList argument is NULL
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
kdeinit5: opened connection to :1
kdeinit5: Got EXEC_NEW '/usr/lib/arm-linux-gnueabihf/libexec/kf5/kconf_update' from launcher.
kdeinit5: preparing to launch '/usr/lib/arm-linux-gnueabihf/libexec/kf5/kconf_update'
kdeinit5: PID 23923 terminated.`

That's the output from `xinit /usr/bin/kded5`

I tried entering the chroot manually, updating and fixing dependencies. It seems like some crucial process is being killed or something isn't being started properly. I haven't worked with KDE much, but I just love the look of Plasma5. If it's not really possible on ARM based machines, It's no worries, I'll just go back to a PekWM crouton. 

Thanks again for all the help, man, I appreciate it.

Cheers

**Comment by AdmiralAsshat** [comment]
FWIW, I tried your own command "xinit /usr/bin/kded5" inside of my chroot and the thing failed to launch. I believe the startkde script simply calls /usr/bin/kde, not kded5. Not sure if that will make any difference.

**Comment by zacknorman** [comment]
Guess it's just not meant to be on Intel ARMs... Il try that command, but
if it doesn't work, thanks for your help man!

On Saturday, April 16, 2016, Admiral Asshat <notifications@github.com>
wrote:

> FWIW, I tried your own command "xinit /usr/bin/kded5" inside of my chroot
> and the thing failed to launch. I believe the startkde script simply calls
> /usr/bin/kde, not kded5. Not sure if that will make any difference.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/2531#issuecomment-210912685>
>


-- 
Regards,
Zack Norman

**Comment by zacknorman** [comment]
Update: Google turns up nothing from my specific error message, and I've exhausted pretty much all of my options. I'm guessing that Plasma 5 just wasn't made for Nyan_Blaze. @AdmiralAsshat major props to you for the help -- and just to clarify, the problem is _not_ in the crouton script, it's likely just Plasma not being able to run on my specific chromebook. 

Cheers

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
