### ISSUE TITLE
DPI Doesn't Change When Modifying X11 Config Files

### ISSUE THREAD

**Issue by chepurko** [dnschneid/crouton#2534]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: trusty
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160330180425~master:43e2fca0
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,touch,xfce,extension,xiwi,core,cli-extra
host: version 7834.70.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP Sat Apr 9 16:02:43 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
-dpi flag doesn't work in X11/xiwi config files (in `/etc/crouton/`)

#### If known, describe the steps to reproduce the issue:
I'm using the instructions from [this page](https://github.com/dnschneid/crouton/wiki/Chromebook-Pixel) specifically trying to fix high DPI display on my Chromebook Pixel 2015.

I've tried using the X11 `-dpi` flag in the `/etc/crouton/xserverrc-local` file and starting via xorg. Any DPI setting I put in the XARG line (`XARGS="$XARGS -dpi 135x135"`) doesn't have any effect when starting up.

Also tried doing the dpi setting for xiwi via

> To support HiDPI in your application window, you need to:
> 
> Check HiDPI in your "Crouton Integration" extension. (By doing this alone, the font will be super small).
> 
> Edit your chroot: sudo enter-chroot sudo vi /etc/crouton/xserverrc-xiwi add "-dpi 135x135" at the end of XARGS line.

Starting up via `startxfce4` and HiDPI checked in the extension again doesn't produce any difference with any dpi setting there.

Any idea if this settings still works or if X11 is just ignoring it? Or am I just clueless and doing something incorrectly? Would love to have some support for the display on my new Pixel :-P

**Comment by anywhim** [comment]
Did you find any solutions?

**Comment by chepurko** [comment]
Yeah I switched to startxfce4 -x xorg. Then I switched to chrx with a complete Xubuntu install)

**Comment by fgblanch** [comment]
I have the exact same problem. Any ideas why -dpi parameter is being ignored?
