### ISSUE TITLE
Used to work

### ISSUE THREAD

**Issue by NoBadMojo** [dnschneid/crouton#2535]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20151104200003~master:2a1fc9da
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 7834.70.0 (Official Build) stable-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP Sat Apr 9 18:25:12 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ 
```

Crouton extension used to work perfectly for me,  Running Trusty and xfce4.  Now when I start up xfce it goes full screen and there is a splash screen which quickly goes away telling me to press f11 to exit full screen.  well chromebooks dont have an f11 key and pressing the keyboard combo of search hyphen (f11 sub) does not work. So I can not run xfce in a Chrome window any longer. To get back to Chrome I have to log out of xfce.  what gives?  this used to work flawlessly.

**Comment by divx118** [comment]
Try updating your chroot see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting for a how to.

**Comment by NoBadMojo** [comment]
Thanks...I successfully did that and still have the problem.  Oddly, the Search-hyphen keystroke combo did provide me with a window where I could minimize, etc.  But that only worked once. Next time  I launched xfce, I was presented with the same problem and the Search-hyphen keystroke combo did nothing,  As I recall, you used to be able to just hover your mouse at the top of the screen and be presented with an option to exit full screen mode

**Comment by divx118** [comment]
@NoBadMojo Yes, you are right I just checked. It indeed isn't there anymore. to exit full screen you can use the toggle full screen button in the top row right next to refresh. You can also use three finger swipe up/down depends on your scrolling setting to switch between windows, same as the button right next to the toggle chrome full screen button.

**Comment by NoBadMojo** [comment]
I dont have the toggle full screen button in the top row nor a refresh button on my screen...But a 3 finger swipe does work fine, so i;m good to go. Thanks for your help

**Comment by divx118** [comment]
@NoBadMojo Sorry for the confusion I meant the buttons on you keyboard.
