### ISSUE TITLE
kali-rolling in crouton error: The '-logfile' option cannot be used with elevated privileges

### ISSUE THREAD

**Issue by msdos41** [dnschneid/crouton#2536]
```
chronos@localhost / $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20160330180425~master:43e2fca0
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce-desktop,core,cli-extra,keyboard,audio,chrome
host: version 7834.70.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 9 16:08:37 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
When I want to enter the chroot, the error showed: 

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

(EE) 
Fatal server error:
(EE) The '-logfile' option cannot be used with elevated privileges.
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) 
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### If known, describe the steps to reproduce the issue:

I installed kali-rolling in crouton using xfce-desktop. It was normal when I installed nmap, metasploit,armitage manuelly. But after I installed several packages by the command "apt-get install kali-linux-full" or "apt-get install kali-linux-top10", I could not enter Kali anymore. 

Thank you for your help!

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
