### ISSUE TITLE
Accidentally Pressed SpaceBar -- Daughter lost hundreds of hours of minecraft - please help

### ISSUE THREAD

**Issue by timothyjlaurent** [dnschneid/crouton#2540]
```
Please paste the output of the following command here: sudo edit-chroot -all
I don't have access to `edit-chroot` right now.
```

#### Please describe your issue:

My kids friend was over and pushed spacebar on the load screen which turned off developer mode.
I have reenabled developer mode and when I navigate to `/mnt/stateful_partition`, I see this:
```
chronos@localhost /mnt/stateful_partition $ ls -las
total 30604
    4 drwxr-xr-x 7 root root       4096 Apr 19 21:55 .
    4 drwxr-xr-x 3 root root       4096 Apr  9 20:12 ..
    0 -rw-r--r-- 1 root root          0 Apr 19 21:45 .developer_mode
    4 drwxr-xr-x 2 root root       4096 Apr 19 21:45 dev_image
    4 drwxr-xr-x 5 root root       4096 Apr 19 21:45 encrypted
30552 -rw------- 1 root root 7878258688 Apr 19 22:06 encrypted.block
    4 -rw------- 1 root root         48 Apr 19 21:55 encrypted.key
    4 drwxr-xr-x 6 root root       4096 Apr 19 21:55 home
   16 drwx------ 2 root root      16384 Apr 19 21:45 lost+found
    0 -rw-r--r-- 1 root root          0 Apr 19 21:54 .tpm_owned
    4 -rw------- 1 root root        317 Apr 19 21:55 .tpm_status
    4 -rw------- 1 root root          8 Apr 19 21:55 .tpm_status.sum
    4 drwxr-xr-x 4 root root       4096 Apr 19 21:45 unencrypted
```
Is there a way to get the linux system back? I think we may be out of luck with the minecraft worlds as they are stored in the home directory..  argh!
Can anyone shed light on this?

Also it is a super bummer that it is so easy to erase your disk in developer mode :/

**Comment by timothyjlaurent** [comment]
Hundreds of hours is (hopefully) an exaggeration.

**Comment by tcagle** [comment]
I am pretty sure your chroot is gone. You should read and understand the backup page on the wiki before putting any significant data on your chroot(s). Removable media or a USB hdd is your best friend but it does require effort to create and maintain backups.
https://github.com/dnschneid/crouton/wiki/Backups
HTH (in the future).

**Comment by timothyjlaurent** [comment]
Thanks @tcagle ... Again, it is deplorable that getting out of dev mode is a spacebar press away, and that is the only key mentioned on the splash screen.
I guess it's a (stupid) lesson on the impermanence of everything. I think a USB drive is in order.
