### ISSUE TITLE
Kali-Rolling - Failed to complete chroot setup.

### ISSUE THREAD

**Issue by snelhezt** [dnschneid/crouton#2542]
Using sudo sh ~/Downloads/crouton -r kali-rolling -t xfce as i've done with both Trusty and Jessie.
But with Kali-Rolling i get this error message after the install.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by divx118** [comment]
duplicate #2513

**Comment by snelhezt** [comment]
Thanks. Tryed with the last solution but that did not solve my problem.
Both Kali-Rolling and XFCE installs just fine, but it wont start.

**Comment by msdos41** [comment]
edit prepare.sh, search netsurf-gtk,and delete related sentences.

However, I cannot start xfce4   #2536   Do you have the same problem?

**Comment by snelhezt** [comment]
No, not the same. But i still have problems.
As i said before. I'm using [this](https://github.com/dnschneid/crouton/issues/2513) method

> For the moment, here is one possible recipe to workaround:
> omit xfce when creating the chroot, and install it afterward:
> 
> sudo sh -e crouton -r kali-rolling -t extrension,xiwi
> sudo enter-chroot
> sudo apt-get install xfce4 xfce4-goodies xfce4-artwork xubuntu-icon-theme
> exit
> sudo startxiwi -F startxfce4

The installation works fine without any error message, but here's what happens when i'm trying to launch it.

> Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
> 
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> 
> X.Org X Server 1.18.3
> Release Date: 2016-04-04
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
> Current Operating System: Linux localhost 3.10.18 #1 SMP Sat Apr 9 17:49:30 PDT 2016 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=16171051-88b7-6a46-a3e6-ee9fe90820e3/PARTNROFF=1 hashtree=PARTUUID=16171051-88b7-6a46-a3e6-ee9fe90820e3/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=faea32b33fdf1848f701f358830e60f71f801b99 salt=5a9c8f25115478c9d93fb37b4fdf0ccdb843c125560eb6cc45e658ea36bede73" noinitrd vt.global_cursor_default=0 kern_guid=16171051-88b7-6a46-a3e6-ee9fe90820e3 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
> Build Date: 05 April 2016  07:00:43AM
> xorg-server 2:1.18.3-1 (http://www.debian.org/support) 
> Current version of pixman: 0.33.6
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Apr 23 12:21:22 2016
> (++) Using config file: "/etc/X11/xorg-dummy.conf"
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
> crouton: version 1-20160420122426~master:46f3c372
> release: kali-rolling
> architecture: amd64
> xmethod: xiwi
> targets: extension,xiwi
> host: version 7834.70.0 (Official Build) stable-channel candy 
> kernel: Linux localhost 3.10.18 #1 SMP Sat Apr 9 17:49:30 PDT 2016 x86_64 GNU/Linux
> freon: yes
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Unable to start display, make sure the crouton extension is installed
> and enabled, and up to date. (download from http://goo.gl/OVQOEt)
> Running exit commands...
> /usr/bin/xinit: connection to X server lost
> 
> waiting for X server to shut down Hangup
> Hangup
> Hangup
> (II) Server terminated successfully (0). Closing log file.
> 
> Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by divx118** [comment]
```
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
```
@snelhezt Well do you have the extension installed?

**Comment by snelhezt** [comment]
Well if you mean this sudo sh -e crouton -r kali-rolling -t **extension**,xiwi then yes. If not, then no.
Never had to use it with Ubuntu or Debian, so why do i need it with Kali-Rolling?

**Comment by tonyxue** [comment]
It means the extension for your browser on Chrome OS

**Comment by Penguination** [comment]
You are missing the chrome extension for crouton. This should fix your problem
[https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom](url)
If it doesn't let me know and we'll try to troubleshoot some more.

**Comment by DennisLfromGA** [comment]
Yes, like @tonyxue mentioned, it's a 'browser extension' named 'crouton integration' that's installed from the Chrome Web Store. It can be a little confusing because crouton has a *target* named 'extension' but these are two completely different things. They are however related in that both are required for the 'xiwi' xmethod.

**Comment by mrspedro** [comment]
can some help me, i need to know how to install kali-rolling in chromebook using crouton 
every time i do sudo sh ~/Downloads/crouton -r kali-rolling -t xfce i get an error on unable to locate netsurf. please help

**Comment by DennisLfromGA** [comment]
@mrspedro,

There have been several methods proposed and even a pull request submitted.
One method that looks promising in the interim was proposed in issue https://github.com/dnschneid/crouton/issues/2513#issuecomment-230125641

-**DennisL**

**Comment by snelhezt** [comment]
Hmm this is wierd. I can't start Ubuntu Precise with crouton integration anymore. Don't know why, but i decided to try out several distros, but went back to Precise since it worked best for me.
Now crouton integration is trying to connect without success.
[Screenshot](https://s31.postimg.org/u3wwhqbwr/Screenshot_2016_07_11.jpg)

But there's still some hope. Time to time i'm able to start it from shell, but only some times.
Here's the log from when i was able to connect, after some errors.

_chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Jun 23 01:52:09 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4c6076d6-bc5a-3e47-aa21-10ca13f42e5b/PARTNROFF=1 hashtree=PARTUUID=4c6076d6-bc5a-3e47-aa21-10ca13f42e5b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=ea603d2ab43c35566e8d10a5327b61411009388a salt=e113b8e100b8d74829c95706369bb50bfbadd318c569179a2a22bf2a2fab26b6" noinitrd vt.global_cursor_default=0 kern_guid=4c6076d6-bc5a-3e47-aa21-10ca13f42e5b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jul 11 18:50:16 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160620130246~master:c39102d9
release: precise
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,extension,gtk-extra,core,keyboard,chrome,x11,audio
host: version 8172.60.0 (Official Build) stable-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Thu Jun 23 01:52:09 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.

(xfwm4:16516): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-session:16477): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfsettingsd:16527): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
xfdesktop[16600]: starting up

(xfdesktop:16600): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-panel:16579): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(polkit-gnome-authentication-agent-1:16611): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:16611): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(wrapper:16617): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",_

**Comment by dnschneid** [comment]
The netsurf stuff has been fixed; I'm not sure if you're hitting other issues still, but feel free to open a new bug if you are.

**Comment by datkeydo2** [comment]
@DennisLfromGA 

I have experienced a issue saying "failed to complete chroot setup"

**Comment by DennisLfromGA** [comment]
@datkeydo2 ,

As I noted in the other issue where you posted -
There's a PR #3955 to fix this issue but it hasn't been reviewed and merged yet, hopefully soon.

Hope this helps,
-DennisLfromGA
