### ISSUE TITLE
Cannot start Unity on Ubuntu 16.04

### ISSUE THREAD

**Issue by Polygon-6789** [dnschneid/crouton#2543]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20160420122426~master:46f3c372
release: xenial
architecture: amd64
xmethod: xorg
targets: x11,keyboard
host: version 7978.57.0 (Official Build) beta-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Thu Apr 14 22:17:34 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
I cannot start Unity using the "enter-chroot xinit" command. I keep getting this error:
```
dconf-CRITICAL **: unable to create directory '/home/paul/.cache/dconf': Permission denied.  dconf will not work properly.
```
#### If known, describe the steps to reproduce the issue:
Create a chroot with the "x11" target on the 16.04 release.
Install the ubuntu-desktop, ubuntu-restricted-extras, and ubuntu-restricted addons packages from the repositories and then add
```
exec unity
```
to ~/.xinitrc

**Comment by brmbrmcar** [comment]
Is it supported yet?

**Comment by Polygon-6789** [comment]
Ubuntu 16.04 isn't officially supported by crouton yet.

**Comment by brmbrmcar** [comment]
When will support be added? Is there a release date or anything?

**Comment by Polygon-6789** [comment]
I don't know of any dates when 16.04 gets official support, we'll have to wait for an announcement.

**Comment by 1rocketdude** [comment]
regardless of it being "officially supported", 16.04 works for me pretty much without issue on a Toshiba2 Chromebook 2014. Are you sure you don't need a few more targets, such as lxde or unity?

**Comment by divx118** [comment]
@1rocketdude 16.04 works pretty good with xfce, lxde maybe also some other DE I didn't try. Unity target however will need a bit of work to be supported on 16.04.

**Comment by nahtnam** [comment]
There is one issue with gnome that has yet to be fixed, but there is a PR in the works. #2429.

**Comment by DanHolli123** [comment]
I have the same problem and updating through the installer script breaks #2649

**Comment by msolters** [comment]
Hi I've gotten Unity running in Xenial: https://github.com/dnschneid/crouton/issues/2720

Unity can be successfully launched and used per the instructions in that issue description.  The glitches I encountered were related to setting & saving some Unity UI settings.  It seems there should be a folder called `/org` in the chroot, but there isn't.  But I found the `sudo xinit unity` would be enough to launch the X server and get Unity up and running, which is progress.

**Comment by lzantal** [comment]
@msolters Can you please share what crouton target you installed? I tried installing the X.org target only, then after entering in I did sudo apt-get install unity-desktop. It installed but every time I try to run it it just shows the background and the X for the cursor.

Thank you.

**Comment by DanHolli123** [comment]
@lzantal : this is with the unity flag in the installer/updater
@msolters : I have xinit set to start Awesome so your command sadly doesn't work for me

**Comment by dnschneid** [comment]
I think @smibarber fixed this, although it won't work on ARM.
