### ISSUE TITLE
After latest CrOS update, multiple tries required to enter chroot, and other instabilities

### ISSUE THREAD

**Issue by laurenweinstein1** [dnschneid/crouton#2544]
Crouton seems to be very unstable since the most recent CrOS update. Not only are the usual fixes to enable loading the VirtualBox kernel modules failing again, but it's taking multiple tries to successfully enter the chroot at all! That is, following the normal procedure, it appears that the process begins, then boom, you're back at the CrOS boot screen. _So far_ it's been possible to get back into the chroot after two or three additional tries like this in sequence. A bit perturbing. I updated the chroot of course -- no visible effect.

**Comment by divx118** [comment]
Seems to me loading the virtualbox modules could be the problem. Did you try disabling the loading in /etc/rc.local or just do `$ sudo mv /etc/rc.local /etc/rc.local.disabled` ? See if starting the choot then works normal, so we can pin point the problem.

**Comment by laurenweinstein1** [comment]
On 04/22 23:02, Maurice van Kruchten wrote:
> Seems to me loading the virtualbox modules could be the problem. Did you try disabling the loading in /etc/rc.local or just do `$ sudo mv /etc/rc.local /etc/rc.local.disabled` ? See if starting the choot then works normal, so we can pin point the problem. 
> 
> ---

In fact, I checked this late last night by commenting out the driver load
code in rc.local. That indeed *did* appear to restore chroot startup stability.

--Lauren--
Lauren Weinstein (lauren@vortex.com): http://www.vortex.com/lauren 
Founder:
 - Network Neutrality Squad: http://www.nnsquad.org 
 - PRIVACY Forum: http://www.vortex.com/privacy-info
Co-Founder: People For Internet Responsibility: http://www.pfir.org/pfir-info
Member: ACM Committee on Computers and Public Policy
Lauren's Blog: http://lauren.vortex.com
Google+: http://google.com/+LaurenWeinstein 
Twitter: http://twitter.com/laurenweinstein
Tel: +1 (818) 225-2800 / Skype: vortex.com
I have consulted to Google, but I am not currently 
doing so -- my opinions expressed here are mine alone.

**Comment by laurenweinstein1** [comment]
Has anyone looked into the current problems with virtualbox drivers no longer loading? Thanks.

**Comment by divx118** [comment]
@laurenweinstein1 I am aware of it. I probably need to update the headers once again, but currently I have not enough time. Next week or maybe over the upcoming weekend.

**Comment by laurenweinstein1** [comment]
Thanks.

**Comment by divx118** [comment]
@laurenweinstein1 
I updated the kernel headers again and tested. They should work now.
Steps to follow:
 1. Be sure you have disabled the loading of the kernel modules in /etc/rc.local, so it doesn't reboot when you enter the chroot.
 2. `$ sudo enter-chroot -n <chrootname>` to enter the chroot. Replace <chrootname> with your chroot name for example "trusty"
 3. `$ sudo apt-get update && sudo apt-get upgrade` to update the kernel headers. If you get scary warnings about the kernel leave the options at there default, just press enter.
 4. `$ sudo /etc/init.d/vboxdrv setup` To recompile the modules.
 5. Edit the rc.local to revert the changes of disabling loading the kernel modules.
 6. `$ exit` To leave the chroot.
 7. Start your chroot normally and try virtualbox.

Please close this issue, if you have problems we can discuss this at https://github.com/divx118/crouton-packages/issues/35 , so we don't pollute the crouton issues here.

Thanks
