### ISSUE TITLE
Feature proposal: Installing from a tarball instead of the traditional way

### ISSUE THREAD

**Issue by nmilosev** [dnschneid/crouton#2545]
Hey guys! If you remember me, I made a version of Crouton for Fedora Workstation. 

Anyway, lately I have been experimenting with installing the base CLI system from a tarball instead of pulling all the packages and extracting them and marking them installed. In Fedora, we have something called Koji build system, which produces docker builds, which are basically fresh updated rootfses with some small metadata. I am pretty sure that there are similar build systems for Ubuntu/Debian/Kali.

I've modified my Crouton Fedora script a lot lately and I am now using those builds. Some reasoning for this is that whatever you do you will end up with the same base system on which you install the rest of the targets. I know our machines are very fast, but I did some "benchmarking" and here are the results:

All tests are on the internal storage of my Toshiba Chromebook.
- Debian Jessie base system from the latest Crouton takes about 11 minutes to install
- Fedora 24 Alpha with the old system takes about the same (11 minutes)
- Fedora 23 from a Koji tarball takes 45 seconds - 50 seconds.

I don't know if this has been discussed before, so I thought I'd bring it up. I will polish my Crouton Fedora script a bit more and upload it in the following days so you guys can test it out. I need to add support for i686 and ARM which shouldn't be very difficult because Koji makes those builds too.

Cheers! :)

**Comment by nmilosev** [comment]
I've recorded a screencast so you can see it in action. 

Sorry about the awful download speed, internet very slow here today...

http://webmshare.com/74VrR

**Comment by AdmiralAsshat** [comment]
What DE do you usually use in your Fedora crouton?

**Comment by nmilosev** [comment]
I currently use XFCE4.

**Comment by dnschneid** [comment]
Yeah, that is a faster way, but crouton's more about low maintenance and avoiding the need to trust a distro repackager.

Are you going to update #2398 ?
