### ISSUE TITLE
Two crouton issues: no Xenial and 2-stage set up for Trusty.

### ISSUE THREAD

**Issue by mistermarko** [dnschneid/crouton#2548]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160420122426~master:46f3c372
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 7834.70.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 9 18:32:52 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
The first issue is that after I installed Crouton Xenial I got a 'UID 1000 not found' error in red and it refused to load. I then installed Crouton Trusty and got 'A chroot setup script still exists inside the chroot. The chroot may not be fully set up. Would you like to finish the set up? [Y/n/d]' I chose Yes but I didn't have time so I aborted and then the same thing happened again later, but that time the second stage finished. Why does it always have to install in two stages? Surely one should be enough? (In future I'll probably go for LXDE and the last supported LTS).

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
