### ISSUE TITLE
Random restarts after/while using crouton

### ISSUE THREAD

**Issue by me-lina** [dnschneid/crouton#2550]
Hello,

I'm using crouton as well as the developer mode now for over an year and my Toshiba Chromebook 2 randomly restarts after putting it to sleep.

First, I used a Crouton installation on a SD card. I always had to log out of Crouton to put my Chromebook to sleep. After waking it up from sleep then sometimes the screen was black for about 30 seconds and after that Chrome opened with the notification: "An error occured, do you want to restore chrome?". And sometimes it just rebooted.

Now, since 2 months I'm using Crouton on an USB Stick, therefore I can put the Chromebook into sleep without stopping Crouton. But I still have random shut downs sometimes when I put it to sleep.
Sometimes I recognized this because I charged some device at the USB port of the Chromebook while it was in sleep mode and the charging stopped some time after closing the lid.

This happens about 2-3 times a week when I'm using it every day.

**Comment by yannym** [comment]
Is it completely shutting down, or is the screen just going black. Usually if there is an overload of RAM, or if the computer simply dies for any reason, it will try to restart straight away (at least that's what my C300 does.) 

If it is simply going blank and not shutting down, this could be an issue with power management in Chrome OS. Next time it goes blank try pressing CTRL + ALT + F2, if it shows a screen that says developer console, press CTRL + ALT + F1, and it will go back to Chrome OS.

**Comment by me-lina** [comment]
Hi, I can try it, but I'm pretty sure, that it's shutting down: the power light is off, no reaction when I try using the keyboard or mouse, the charging stopps.
When I push the power button (short, like for a normal start) it starts normally.

since my post above I am using LXDE instead of XFCE and the error didn't occur again up until now, but that can be by chance.

**Comment by SudoDiamond** [comment]
Im not sure exactly what you mean, but I've been having a problem similar to yours where if I put it to sleep/close the lid in the chroot enviroment when I log in it will repeatedly switch back and forth between them, but wont stay on one or the other for more than half a second
