### ISSUE TITLE
Unable to re-open a program in a browser tab after the program crashes

### ISSUE THREAD

**Issue by henrywright** [dnschneid/crouton#2552]
I'm using this command to open Chromium in a browser tab:

`sudo enter-chroot -b xiwi -T chromium-browser`

If Chromium crashes and the tab closes and then I run the same command again to re-open Chromium in a new browser tab, Chromium doesn't open. I think this is because Crouton thinks Chromium is still open. See:

![screenshot 2016-04-27 at 13 04 30 - edited](https://cloud.githubusercontent.com/assets/1963288/14851635/13005b10-0c79-11e6-9263-3ba1eaed51f5.png)

**Comment by DennisLfromGA** [comment]
@henrywright,

You might try the '-f' option to 'xiwi' to see if it behaves any better (or worse):
```
-f          Prevent xiwi from quitting automatically. (see NOTE below)

NOTE:
xiwi will normally close when the application returns. Some gui applications
fork before or during normal operation, which can confuse xiwi and cause it to
quit prematurely. If your application does not have a parameter that prevents
it from forking, and crouton is unable to automatically detect the fork, you can
use -f to prevent xiwi from quitting automatically.
xiwi will quit if you close the Chromium OS window when nothing is displayed.
```

You can add it similar to:
`sudo enter-chroot -b xiwi -fT chromium-browser`

Or, to simplify,  just use:
`sudo startxiwi -bfT chromium-browser`

-**DennisL**

**Comment by henrywright** [comment]
Thanks @DennisLfromGA I will give that a try
