### ISSUE TITLE
Is it possible upgrade Ubuntu version?

### ISSUE THREAD

**Issue by snowcat-Jung** [dnschneid/crouton#2553]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Chromebook Pixel 2 LS**

#### Please describe your issue:

I currently use Ubuntu 14.04 unity on Pixel2 LS.
Can I update to 16.04 with no problem??
Or I just have to powerwash my chromebook and reinstall Crouton??

**Comment by divx118** [comment]
Unity has some issues on xenial in crouton right now, so I would wait to upgrade or switch to another DE like xfce. You don't have to powerwash. You can upgrade your chroot see  https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release. However I am not a big fan of distupgrades. I would prefer deleting the old chroot with `sudo delete-chroot <chrootname>` and then create a new one from scratch. A powerwash is really not needed and unnecessary, actually I never had a scenario to do a powerwash because of crouton.

**Comment by snowcat-Jung** [comment]
@divx118 If I delete chroot, It clearly delete whole old Ubuntu??
By the way, always thanks to divx!!

**Comment by divx118** [comment]
@snowcat-Jung Yes, it will completely wipe the ubuntu chroot no residue left so really no need to powerwash.

**Comment by r0b0ts** [comment]
`sudo apt-get dist-upgrade`
I've only used crouton several times in the past, so it's just an assumption that this functions properly.

**Comment by skiman6010** [comment]
@divx118 Is it possible to back data up with crouton and restore it on the new chroot?

**Comment by divx118** [comment]
@skiman6010 Not directly with crouton. You can copy your data when you are in the chroot to a usb stick or to ~/Downloads then delete the chroot create a new one and copy it back. However you probably mean some clever way to backup your settings or data with the crouton script and then restore that in a chroot. That is not possible and would also be very hard or even impossible to implement in the crouton script.

**Comment by skiman6010** [comment]
@divx118 That was my plan on backing up my data, I was just hoping there was some easy script that I didn't know about to do it for me. Thanks for your help!

**Comment by snowcat-Jung** [comment]
When does 16.04 will supported?

**Comment by zxvv** [comment]
The various target will eventually be working on 16.04.

Meanwhile, one way to install 16.04 is to initially only use crouton to install the X window system baseline.  After that, enter the chroot, and install a desktop:

sudo sh couton -r xenial -t xiwi
sudo enter-chroot
sudo apt-get install lxde-desktop
sudo xiwi -F startlxde

**Comment by SoccerPie** [comment]
I have found that xiwi slows down the chroot a bit, is there a way to install xenial without xiwi? I would also like my desktop environment to be gnome. Thanks!

**Comment by DennisLfromGA** [comment]
@SoccerPie - I don't know what device you're using but you might try 'xorg'.

**Comment by tbc** [comment]
How about now that 16.04.1 is out? Software Updater made the offer to me tonight.
