### ISSUE TITLE
failed connect to chromium googlesource com 443

### ISSUE THREAD

**Issue by mrbian** [dnschneid/crouton#2554]
Hi, I got a problem when I was running
``` 
sudo sh -e ./crouton -t unity 
```
everything is ok until 

```
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 5c1b8df3853498e30e416b6289c12dab41a5988a)...
--2016-04-28 16:25:11--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/5c1b8df3853498e30e416b6289c12dab41a5988a.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 64.233.189.82, 2404:6800:4008:c01::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|64.233.189.82|:443... failed: Connection timed out.
Connecting to chromium.googlesource.com (chromium.googlesource.com)|2404:6800:4008:c01::52|:443... failed: Network is unreachable.
Error fetching CRAS
```
However, I can visit chromium.googlesource.com. I have tried three times but failed so I come here for help.

**Comment by mrbian** [comment]
I am living in China. But I can connect google server by changing my hosts file. Is there any problem with My DNS or something?

**Comment by thatblstudio** [comment]
I lives in China too. I just figure it out. 
I'm using shadowsocks to cross the GFW.
There are my steps:
1. Using shadowsocks-win on another windows platform, and check on "allow connection from LAN", use ipconfig /all in command line to find out you windows' ip address
2. Connect chromebook to the same WLAN as the windows platform
3. Open shell in chromebook
4. `sudo sh ~/Downloads/crouton -t xfce -P http://youripaddress:port` (replace with your windows' ip address and the port which shadowsocks uses)
5. That's all.
The trick is using "-P", that means using proxy. You can use ssh or something else, but I never tried that. Hope that can help you.

**Comment by mrbian** [comment]
😂谢谢啦。

**Comment by chengmo8888** [comment]
I met the same issue, thanks for the explanation. I solved the problem.

**Comment by Nathan903** [comment]
same exact problem, how should I use proxy if im using vypr or astrill app that is not http?

**Comment by bingliang-zh** [comment]
Try search "port forwarding" with these softwares.

**Comment by DennisLfromGA** [comment]
Also see this comment for possible solutions: https://github.com/dnschneid/crouton/issues/3672#issuecomment-370526591

*Hope this helps,*
-**DennisLfromGA**
