### ISSUE TITLE
Screen flicker on linux ubuntu on my c720

### ISSUE THREAD

**Issue by DerpyKirby** [dnschneid/crouton#2559]
whenever im on my acer c720's linux using crouton my screen flickers to the chrome OS screen,

it happend after i reloaded linux once
the time i installed it and immediatly loaded it, it was perfect,
but one time it randomly crashed and now i reloaded it and it flickers
IT BUGS ME ALOT

**Comment by brandonwu** [comment]
Started having this problem on the Pixel 1 too (using Xorg). Just tried updating to latest crouton, no dice. It sporadically flickers to chrome OS when using crouton. Possibly an interaction between the xorg and xiwi target; every time it flickers it emits a " => message from non-tab target" to the crosh, and disabling the extension makes it flicker less, but then it emits a "croutonwebsocket error: Error: not connected."

Chrome OS version: 50.0.2661.91 beta (64-bit)

croutonversion:
crouton: version 1-20160420122426~master:46f3c372
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,touch,xfce
host: version 7978.66.0 (Official Build) beta-channel link
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 27 15:27:04 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by powapowa** [comment]
Hello.
I'm using same env as Mr.DerpyKirby (crouton/Ubuntu on c720), and the flicker had occurred.

After running of crouton's script,  I changed my Chrome OS channel from stable to beta, and Ubuntu began to work correctly.

(Possibly it was a bad method. But some crouton's problem are complex because of the combination of Chrome OS, crouton and OSes on crouton. so, sometimes I try changing the channel.)

**Comment by davidlowryduda** [comment]
I have encountered the screen flicker now as well. It does not seem to occur immediately after a restart, but some time later (perhaps after the machine sleeps, I haven't figured it out yet) it comes back. In particular, using ctrl-alt-right to go to the chroot works, but very frequently (but not consistently --- sometimes more than once a second) the screen will flicker back to the Chrome OS screen+browser.

I'm on a c720p.

I've updated crouton, but that has not fixed the flicker. I've been using crouton for several years, and this is new. I suspect it has something to do with the most recent Chrome OS update.

**Comment by slhale** [comment]
I also have been experiencing this screen flicker issue since the last Chrome OS update. It does not appear for me when Chrome OS is freshly restarted and then I start up crouton, but it does happen after my computer has fallen asleep. 

I'm on a c720p as well. 
version 1-20160420122426~master:46f3c372
trusty

**Comment by wkhalidman2** [comment]
Exact same thing as slhale, but I use xfce.

**Comment by LukeLindsey** [comment]
I'm having the same issue on Dell Chromebook 11 using xfce. This is from the console when it happens.

`No Chromium OS X server is available.
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(xfwm4:27203): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfwm4:27203): xfwm4-WARNING **: The property '/general/double_click_distance' of type int is not supported

(polkit-gnome-authentication-agent-1:27223): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:27223): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfsettingsd:27229): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed
Timeout waiting for extension to connect.
Cannot open /sys/class/tty/tty0/active: No such file or directory
croutonwebsocket error: Error: not connected.(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
croutonwebsocket error: EError: not connected.(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available`

**Comment by gboudreau** [comment]
The v51 is now on the stable channel, and I updated from 50.0.2661 to 51.0.2704, and the problem seems to be resolved for me (C720, unity target, on Ubuntu trusty).

**Comment by chunyang** [comment]
I tried the fix in the second post of #1519 and it does not stop the flickering for me (C720, trusty). I have not received the v51 update yet, but keeping my hopes up!

**Comment by gboudreau** [comment]
I myself had to manually check for updates manually to get it: https://support.google.com/chromebook/answer/177889?hl=en

If that doesn't work, you might be able to get it from the beta channel: https://support.google.com/chromebook/answer/1086915?hl=en
You can always go back to stable just after getting v51, if you're not comfortable running beta software in the long run.

**Comment by peepo** [comment]
I also have flickering in ChromeOS only not Ubuntu
this only started after presumed crash, when battery dried up.
It would be nice to have some guidance on procedure to identify problem....

**Comment by peepo** [comment]
deleting $HOME/.config/plasma-org.kde.plasma.desktop-appletsrc
wfm
https://forum.kde.org/viewtopic.php?f=289&t=128589
