### ISSUE TITLE
Starting a chroot Seems to Pick the Wrong chroot.

### ISSUE THREAD

**Issue by ianbarton** [dnschneid/crouton#2561]
I have created a chroot based on xenial with targets xiwi,keyboard,lxde:

sudo sh ~/Downloads/crouton -f ~/Downloads/xenial-bootstra.tar.bz2 -t xiwi,keyboard,lxde -u -n xenial-lxde

I have created an .xinitrc with /usr/bin/startlxde

Now when I try to start it:
chronos@localhost ~/Downloads $ sudo enter-chroot xenial-lxde xinit
Entering /mnt/stateful_partition/crouton/chroots/trusty-i3...
-su: 1: xenial-lxde: not found
Unmounting /mnt/stateful_partition/crouton/chroots/trusty-i3...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty-i3.

Crouton seems unable to find the chroot and it looks as though it's trying to mount the wrong chroot.

However, I can enter the chroot in a terminal:

chronos@localhost ~/Downloads $ sudo enter-chroot -n xenial-lxde
Entering /mnt/stateful_partition/crouton/chroots/xenial-lxde...
(xenial-lxde)ian@localhost:~$ 

```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost ~/Downloads $  sudo edit-chroot -all
name: trusty-i3
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty-i3...
crouton: version 1-20160125112815~b78906bc
release: trusty
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,lxde
host: version 7834.70.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 9 16:08:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty-i3...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20160420122426~master:46f3c372
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 7834.70.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 9 16:08:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
name: xenial-i3
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial-i3...
crouton: version 1-20160420122426~master:46f3c372
release: xenial
architecture: amd64

xmethod: xorg
targets: x11,xiwi,keyboard
host: version 7834.70.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 9 16:08:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial-i3...
name: xenial-lxde
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial-lxde...
crouton: version 1-20160420122426~master:46f3c372
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,lxde
host: version 7834.70.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 9 16:08:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial-lxde...
name: xenial-xfce
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial-xfce...
crouton: version 1-20160420122426~master:46f3c372
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,keyboard
host: version 7834.70.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 9 16:08:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial-xfce as another instance is using it.

**Comment by divx118** [comment]
Try using `sudo enter-chroot -n xenial-lxde xinit` Notice "-n"

**Comment by zxvv** [comment]
If "-n <chroot-name>" is not specified, then enter-chroot will start the first one, ordered alphabetically.

**Comment by ianbarton** [comment]
Thanks specifying "-n" worked. I have another problem when LXDE starts up, but I'll see if I can fix it an raise another issue if I can't.
