### ISSUE TITLE
Change username?

### ISSUE THREAD

**Issue by wxv** [dnschneid/crouton#2563]
Is it possible to change the administrator username? Creating a temporary account does not seem to work. Running Ubuntu 14.04.

**Comment by andregirol** [comment]
Hello wxv,
Do you mean your system username? Ubuntu doesn't have an administrator account (_root_). You run administrator's commands and tools using `sudo`. If you want do become _root_ temporarily, just type in your terminal:
`$ sudo -i`

If you want to change **your** username, maybe this can help you:

[(http://askubuntu.com/questions/34074/how-do-i-change-my-username)]

**Comment by RTbecard** [comment]
Yes, I think the OP means chroot username.  I have the same issue.

The typical command for changing usernames `sudo usermod -l newUsername oldUsername` will only work when the users who's name is being changed is not currently logged in.  As crouton doesn't support multiple accounts (right?), this poses an issue, preventing me from using the typical Ubuntu workflow for this action.  Any suggestions for alternate methods to change the username?

**Comment by DennisLfromGA** [comment]
@RTbecard,

>  Any suggestions for alternate methods to change the username?  

You can enter your chroot as root and then run the usermod command, just use:

`sudo enter-chroot -u root`

Then go for it.

> As crouton doesn't support multiple accounts (right?), this poses an issue, preventing me from using the typical Ubuntu workflow for this action.

A recent [multi-user branch merge and a few other fixes](https://github.com/dnschneid/crouton/pull/2820) enables crouton to support multi-users with just a little bit of work. See [this comment](https://github.com/dnschneid/crouton/issues/908#issuecomment-253298327) for more info. 

*Hope this helps,*
-**DennisL**

**Comment by RTbecard** [comment]
Great!  I wasn't aware of the possibility of selecting ` -u root`.

I just tested this out and can confirm changing the username works when logging in as root with `sudo enter-chroot -u root` then running `usermod -l newUsername oldUsername`.

**Comment by DennisLfromGA** [comment]
*Cool!*
