### ISSUE TITLE
Chroot wont make up its mind...

### ISSUE THREAD

**Issue by SudoDiamond** [dnschneid/crouton#2564]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
#### Please describe your issue:

I am currently running a unity chroot on my acer c720 chromebook and my computer has completely lost it. So the boot up works fine but if chroot is running and I am In my unity enviroment if I shut the lid of my laptop (suspend) when I wake it up it will flash the chrome login and the unity desktop, it continues to flash until I run the command to switch to chrome repeatedly. Any fix would be greatly appreciated.

**Comment by davidlowryduda** [comment]
I believe this is the same issue as in https://github.com/dnschneid/crouton/issues/2559

Or at the very least, I believe their cause is the same. These both are also very recent, which reinforces my belief that something strange occurred with the last ChromeOS update.
