### ISSUE TITLE
how to we set preference to change the download location in chrome while using pytest mozwebqa

### ISSUE THREAD

**Issue by jaya-best** [dnschneid/crouton#2565]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
#### Please describe your issue:

how to we set preference to change the download location in chrome while using pytest mozwebqa.
i tried with below command

--chromeopts='{"prefs":["download.default_directory":"c:\ler","download.directory_upgrade":true]}'
but its not working.

Please help on this

**Comment by dnschneid** [comment]
#262
