### ISSUE TITLE
Cannot open display (trusty, LXDE or KDE) and cannot update crouton or complete crouton setup.

### ISSUE THREAD

**Issue by RyM21** [dnschneid/crouton#2566]
#### Please describe your issue:

I am currently able to enter the chroot and work on the command line, but cannot access the X-window system, cannot update crouton, and cannot complete crouton's setup script. Attempting to start lxde or kde either (a) causes the system to hang so I have to turn off my Chromebook manually, or (b) returns "Gtk-WARNING **: cannot open display: localhost:0.0". I am running an Asus Flip C100P. Here are the error messages:

#### 1
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xorg-video-abi-11
                            Depends: xserver-xorg-core (>= 2:1.10.99.901)
E: Unable to correct problems, you have held broken packages.
```
#### 2
```
The following held packages will be changed:
  xserver-xorg-video-dummy

```
#### 3
`E: Unable to find a source package for xorg-video-abi-11`

#### 4
```
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
```

#### 5
```
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
```

#### 6
```
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
```

#### 7
`(lxsession:26843): Gtk-WARNING **: cannot open display: localhost:0.0`

#### 8
`xhost:  unable to open display "localhost:0.0"`

#### 9
`xhost:  unable to open display ""`

#### 10
`ssh: connect to host localhost port 22: Connection refused`

I know there are many issues related to this (e.g. #524 , #1702 , #1789 , #2021, #2491, #2252) and many solutions listed here and on various forums, but I have tried them; this is an issue I have faced very frequently since I first installed crouton a few months ago. It recurs despite powerwashing, updates, etc., and it has affected me with both Precise and Trusty, and with various desktop environments (XFCE, LXDE, KDE). Relatedly, I cannot update crouton.

Note that the setup script says that `xorg-video-abi-11` is missing dependencies, but apt-get cannot find this package.

This time, I have tried the following: 

#### 1: Updating crouton (doesn`t work, fails to complete setup):

`sudo sh ~/Downloads/crouton -u -n trusty

#### 2: Updating crouton and re-adding xiwi, xorg, and extension targets: 

`sudo sh ~/Downloads/crouton -u -n trusty -t xiwi,xorg,extension`

#### 3: Trying to fix potential display and .Xauthority issues within the chroot:

```
sudo rm /tmp/Xorg.crouton.1.log // file does not exist

xhost +localhost // fails 
sudo xhost +localhost // fails 
xhost + // fails 
sudo xhost +  // fails 

export DISPLAY=localhost:0.0
export DISPLAY=localhost:0 1099  export XAUTHORITY=$HOME/.Xauthority
ssh ryan@localhost +X +Y
ssh ryan@localhost +X
sudo ssh ryan@localhost +X +Y
sudo ssh ryan@localhost +X
sudo ssh ryan@localhost +Y

sudo rm /dev/dri/card0; sudo mv /dev/dri/card1 /dev/dri/card0 // this has worked in the past
```
#### 4: Updates and installations within the chroot; these complete without incident

`croutonversion -u -d -c

`apt-get update --fix-missing`

`sudo apt-get autoremove -f -y -m && sudo apt-get autoclean -f -y -m && sudo apt-get build-dep -f -y -m xserver-xorg-core xserver-xorg-video-dummy lxde && sudo apt-get install -f -y -m && sudo apt-get upgrade -f -y -m && sudo apt-get update -f -y -m && sudo apt-get autoremove -f -y -m && sudo apt-get autoclean -f -y -m`

`sudo apt-get update -f -y -m`, `sudo apt-get build-dep -f -y -m`, and `sudo apt-get install -f -y -m` for all of the following packages where the setup script seems to get stuck: 

```
xserver-xorg-video-dummy
libglapi-mesa-lts-quantal
libgbm1-lts-quantal
libgl1-mesa-dri-lts-quantal
libgl1-mesa-glx-lts-quantal
libglapi-mesa-lts-quantal
libgles2-mesa-lts-quantal
libwayland-ltsq0
xserver-common-lts-quantal
xserver-xorg-core-lts-quantal
xserver-xorg-input-evdev-lts-quantal
xserver-xorg-input-synaptics-lts-quantal
xserver-xorg-lts-quantal
xserver-xorg-video-modesetting-lts-quantal
libgbm1-lts-quantal
libgl1-mesa-dri-lts-quantal
libglapi-mesa-lts-quantal
libwayland-ltsq0
xserver-common-lts-quantal
xserver-xorg-core-lts-quantal
xserver-xorg-input-evdev-lts-quantal
libegl1-mesa-lts-quantal
libgbm1-lts-quantal
libgl1-mesa-dri-lts-quantal
libgl1-mesa-glx-lts-quantal
libglapi-mesa-lts-quantal
libgles2-mesa-lts-quantal
libwayland-ltsq0
xserver-common-lts-quantal
xserver-xorg-core-lts-quantal
xserver-xorg-input-evdev-lts-quantal
xserver-xorg-input-synaptics-lts-quantal
xserver-xorg-lts-quantal
xserver-xorg-video-modesetting-lts-quantal
xserver-xorg-video-dummy
```

#### Please paste the output of the following command here: sudo edit-chroot -all
```
Password: 
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by dnschneid** [comment]
Your trusty chroot is actually a precise chroot (you probably specified `-n trusty` instead of `-r trusty` when you originally created it).

In trusty, you should be able to install both xorg and xiwi at the same time.  In precise, that's broken (and will probably stay broken): #2822

**Comment by DennisLfromGA** [comment]
_Wow, great catch!_
