### ISSUE TITLE
croutonversion -d does not download crouton installer

### ISSUE THREAD

**Issue by RyM21** [dnschneid/crouton#2567]
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
#### Please describe your issue:

`croutonversion -d` does not download crouton installer. I am on an ASUS Chromebook Flip C100.

'(trusty)ryan@localhost:~$ croutonversion -u -d -c
crouton: version 1-20160420122426~master:46f3c372
Retrieving latest version of crouton
latest: version 1-20160420122426~master:46f3c372
(trusty)ryan@localhost:~$ croutonversion -d  
crouton: version 1-20160420122426~master:46f3c372
Retrieving latest version of crouton
latest: version 1-20160420122426~master:46f3c372'

This does not result in the Crouton installer being downloaded to my Downloads folder.

**Comment by dnschneid** [comment]
That's odd; `croutonversion -u -d -c` shouldn't download (since you're already at the latest version), but `croutonversion -d` should have.  Are you still hitting this issue?  If so, please try running `sh -x /usr/local/bin/croutonversion -d` and post the output.
