### ISSUE TITLE
Xorg dummy driver certificate not trusted

### ISSUE THREAD

**Issue by paleomedia** [dnschneid/crouton#2569]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: debian
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/debian...
crouton: version 1-20160420122426~master:46f3c372
release: wheezy
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,cli-extra
host: version 7834.70.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Sat Apr 9 17:50:02 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/debian...
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160206234800~master:daa872a0
release: trusty
architecture: amd64
targets: cli-extra
host: version 7834.70.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Sat Apr 9 17:50:02 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
#### Please describe your issue:

Xorg dummy driver certificate not trusted:

Download Xorg dummy driver...
--2016-05-06 19:01:34--  http://xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
Resolving xorg.freedesktop.org (xorg.freedesktop.org)... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to xorg.freedesktop.org (xorg.freedesktop.org)|131.252.210.176|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.x.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz [following]
--2016-05-06 19:01:35--  https://www.x.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
Resolving www.x.org (www.x.org)... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to www.x.org (www.x.org)|131.252.210.176|:443... connected.
ERROR: The certificate of `www.x.org' is not trusted.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/debian...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/debian...
#### If known, describe the steps to reproduce the issue:

updating debian with: sudo sh ~/Downloads/crouton -u -n debian

**Comment by greg-kennedy** [comment]
Same here, with xorg and xiwi targets.

**Comment by killzoms** [comment]
![img_20160509_013035](https://cloud.githubusercontent.com/assets/13115936/15104400/d0b800da-1585-11e6-9b6c-586ec463cceb.JPG)
the certificate was very recently validated for the www.x.org website

**Comment by c-f-h** [comment]
I have a similar, but not identical, problem: when I try to update my `precise` chroot with xorg and xiwi, I get this:

```
Download Xorg dummy driver...
--2016-05-09 23:21:52--  http://xorg.freedesktop.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
Resolving xorg.freedesktop.org (xorg.freedesktop.org)... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to xorg.freedesktop.org (xorg.freedesktop.org)|131.252.210.176|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.x.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz [following]
--2016-05-09 23:21:53--  https://www.x.org/releases/individual/driver//xf86-video-dummy-0.3.7.tar.gz
Resolving www.x.org (www.x.org)... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to www.x.org (www.x.org)|131.252.210.176|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name `www.x.org'.
To connect to www.x.org insecurely, use `--no-check-certificate'.
Failed to complete chroot setup.
```

By googling this error message I found that this sometimes occurs because the version of wget in precise is too old?

I would add the `--no-check-certificate` argument but I have no idea where I could do that.

**Comment by wiredin** [comment]
This issue exists because the certificate chain used by x.org is newer than what is available in [ca-certificates] (http://packages.ubuntu.com/precise/ca-certificates), which is the certificate authority package for precise and is not up to date.

In my opinion the easiest fix to get your crouton update to complete is to do the following.

> $ sudo enter-chroot
$ sudo su 
$ echo "check-certificate = off" > /root/.wgetrc
$ exit
$ exit
$ sudo sh ~/Downloads/crouton -n [Your Chroot] -u
$ sudo enter-chroot
$ sudo rm /root/.wgetrc

**Comment by greg-kennedy** [comment]
Thanks.  I couldn't enter-chroot because it wasn't setup yet, so instead I did simply
    $ sudo vi /mnt/stateful_partition/crouton/chroots/precise/root/.wgetrc
and added check-certificate = off.

**Comment by wiredin** [comment]
That works too, but don't forget to remove the .wgetrc when your done! You don't want to turn off check-certificate in wget forever.

**Comment by paleomedia** [comment]
Thanks... @wiredin's solution worked. Shall I close this issue or leave it open for future reference?

**Comment by wiredin** [comment]
I've submitted a bug report here to update ca-certificates
https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1580700
Probably could use everyone's support in getting it attention.

**Comment by transp** [comment]
I tried "sudo sh ~/Downloads/crouton -r wheezy -t xiwi", but bumped into same issue as OP.
Fix proposed by greg-kennedy above worked for me too.
Successfully completed installation with: "sudo sh ~/Downloads/crouton -r wheezy -t xiwi -u".

**Comment by WaslowMunglebork** [comment]
I don't vi, so did this:

`sudo su`
`echo "check-certificate = off" > /mnt/stateful_partition/crouton/chroots/MyChroot/root/.wgetrc`
`exit`
...
`sudo rm /mnt/stateful_partition/crouton/chroots/MyChroot/root/.wgetrc`

**Comment by dnschneid** [comment]
This is fixed in upstream precise, but not in wheezy.  Maybe we should just disable cert checking for dummy in wheezy alone?  Or can we ship the cert with crouton and pass it to wget somehow?

**Comment by dnschneid** [comment]
Wait, https://launchpad.net/debian/wheezy/+source/wget/+changelog suggests wheezy should have the same fix.  What's going wrong?

**Comment by dnschneid** [comment]
Oh, I see, the error in precise was "no certificate subject alternative name matches", vs the untrusted error.  So are we just missing ca-certificates?

**Comment by dnschneid** [comment]
No, we are installing it.  Maybe I should stop spamming the issue tracker :)

**Comment by dnschneid** [comment]
Okay, wheezy ignores certs for that instance.  No need to hack things yourselves anymore.
