### ISSUE TITLE
Upgrade OpenGL

### ISSUE THREAD

**Issue by firestar115** [dnschneid/crouton#2573]
I know this doesn't use the default format, but anyway...

I'm running on an Acer C7 Chromebook on the latest DEV update.

I have a `trusty` chroot running GNOME Shell.

I need OpenGL 2.0 for a game, and I have 1.4.

I want to upgrade it without any hassle.

**Comment by drinkcat** [comment]
I'm pretty sure trusty's mesa supports OpenGL 2.0.
