### ISSUE TITLE
Graphical glitches when switching out of and back into X

### ISSUE THREAD

**Issue by c-f-h** [dnschneid/crouton#2579]
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160420122426~master:46f3c372
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,xorg,xiwi
host: version 7978.66.3 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue May 3 18:13:44 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

---

My hardware is an Acer Chromebook 15. I used to be able to switch in and out of xfce4 fine (on precise), but since a short while (I think since a recent Chrome OS update), when I switch out and back into X, I get lots of graphical glitches, switching workspaces doesn't work, basically it's unusable.

Here's a screenshot: http://s32.postimg.org/kfjhw4k3p/shot1.png
I managed to type into the terminal to take a screenshot, but as you can see it's otherwise messed up.

I updated the chroot, and I even removed it and created a new one using trusty. The issue is still there.

I'd be very grateful for any hints because my chroot is basically unusable like this.

**Comment by roger77** [comment]
I think I have a similar issue. While in X, the screen randomly switches to ChromeOS side, most often if I just move the mouse I go back to X... so it is usable, but quite annoying.

`$ croutonversion 
crouton: version 1-20160420122426~master:46f3c372
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,x11,extension,unity,unity-desktop,xiwi,touch
host: version 7978.66.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 27 15:27:04 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
`

**Comment by c-f-h** [comment]
If anybody else has these problems on the same hardware (Intel 3205U): I switched to a xenial chroot and everything works pretty much flawlessly, despite the "unsupported" status.
