### ISSUE TITLE
help! screen REALLY flashing!

### ISSUE THREAD

**Issue by wkhalidman2** [dnschneid/crouton#2580]
**# ISSUE BELOW**
"XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Apr 27 11:10:19 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=84de0146-4580-ca4f-823c-989c25105b57/PARTNROFF=1 hashtree=PARTUUID=84de0146-4580-ca4f-823c-989c25105b57/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=c998148011e30c4ef534a72b73188de80d518959 salt=093630db3193c681c10a1614e0e45ff97796f18c22783d5d1ec5a7f5f7a2c7b6" noinitrd vt.global_cursor_default=0 kern_guid=84de0146-4580-ca4f-823c-989c25105b57 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed May 11 17:57:25 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20160420122426~master:46f3c372
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 7978.66.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 27 11:10:19 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:25168): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:25168): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(II) AIGLX: Suspending AIGLX clients for VT switch 
(xfce4-session:3919): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 18:32:53: SIGHUP received: restarting...
xscreensaver: 18:32:53: running as wkhalid/wkhalid (1000/1000)

Hangup
xfce4-volumed: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xscreensaver: 18:32:53: Can't open display: :1.0
xscreensaver: 18:32:53: running as wkhalid/wkhalid (1000/1000)

xscreensaver: 18:32:53: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html

(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty..."

#### Please describe your issue:  
Hi guys, I'm new here, but I've been using crouton for 11 months or so now. I've used trusty at all times on my acer-c720 chromebook, having unity, kde, and xfce. So far it's been flawless, but then IT happened. You see, I just finished downloading a fresh install of trusty amd64 (xfce) and then decided to enter it. But then my screen started flashing alot, and xfce started. Then, xfce and chrome os would flicker back and forth with linux a ton, and it's really, really terrible. The above code is what I get while I'm in linux (talking about crosh). I've searched this problem, but got absolutely no results. Plz help me solve this issue. 

#### If known, describe the steps to reproduce the issue:
All I did was download linux trusty xfce, and then typed in "sudo startxfce4" 
(note: this happened with kde also, kind of recently after the new chrome os update)

**Comment by wkhalidman2** [comment]
Basically, I'm not switching between chrome os and linux, instead, chrome os keeps on flashing onto my screen while I'm on linux. Make sense? It's also gets really annoying and irritating cause I'm trying to log out, (you know, get out of linux). Should I just try the crouton integration thingy? (not a big fan of crouton in  tab).

**Comment by Kalirren** [comment]
This is happening with me too on an Acer C720 running xenial.  When I am in a linux chroot, the Chrome OS screen output will "flash in" and overwrite the linux screen.  Notably, it's not a fully functional Chrome OS screen, because I can click the tabs and the tabs do not switch; same with the taskbar. However, if I actually switch back to Chrome OS using Ctrl+Alt+Shift+F1 and click the tabs and taskbar, they actually respond.  Strangely, one can still open a new tab using Ctrl+T and even type in a Google query, hit return and have it go.

After having switched back to ChromeOS, I can switch back to the linux using Ctrl+Alt+Shift+F2 and have it work for a while, but the ChromeOS screen output spontaneously flashes in after a while again. Sometimes it "flashes back out" again of its own accord; other times not; sometimes it flashes in for only a single frame.  Many times, the ChromeOS screen will "flash in" and write only the active browser window, with no scrollbar or bookmarks tab or address bar or tabs or OS taskbar, overwriting all those areas instead with plain black.  In both cases the linux screen is completely blocked off, and chroot focus cannot be regained without switching out and back in.

Uncertain what causes this to happen: rebooting seems to fix the problem temporarily, but as soon as it starts happening, it keeps happening until reboot.

**Comment by joshuarrrr** [comment]
I think this is definitely related to the recent ChromeOS update, as I didn't experience it until then. I updated crouton today, but that didn't fix the problem.

It seems like it is related to the Chrome tab that's in focus when you switch. If the focused tab is running tasks in the background, the chroot screen will flash. But if the focused tab is not running any background tasks (like an Ubuntu help page, for instance), the screen remains stable.

**Comment by wkhalidman2** [comment]
Update: I tried updating the chroot, but no result. I rebooted, it worked perfectly, but then once my chromebook goes to sleep mode it starts again. Maybe it's something to do with sleep mode...

**Comment by flactemnad** [comment]
I've had the same issue here myself.  It started after the last ChromeOS update on my Acer C720P.  I'm hoping a ChromeOS update will fix the issue next time around, as this is making things quite difficult.  
Currently running:
Version 50.0.2661.91 (64-bit)
Platform 7978.66.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.93.0

Even closing all tabs and extensions in the ChromeOS side still results in screen focus switching back and forth, although all key input is strictly on the Linux side of the system.

**Comment by wkhalidman2** [comment]
continued results here: issue #2576

**Comment by Alfriadox** [comment]
Same issue

**Comment by wkhalidman2** [comment]
Today, there was a new update of chrome os. Tried running linux after sleep mode, but the problem still remains.

**Comment by hsc36** [comment]
Same issue here, but running xenial on my Acer C720.

**Comment by umataro** [comment]
on hp chromebook 14 (falco), i have chromeos stable branch and ubuntu 14.04 (with gnome) in crouton. i have the same symptoms. flashing back and forth.

**Comment by zelemo** [comment]
Just to say that updating my ChromeOS stream to the latest beta seems to have solved it for me as well.  Using an Acer C720 and running Kubuntu.

**Comment by dnschneid** [comment]
#2576
