### ISSUE TITLE
Trouble installing Xenial. How do I install crouton with flashback not fallback

### ISSUE THREAD

**Issue by SoccerPie** [dnschneid/crouton#2581]
**I tried to install Xenial today and got this error message**

_Package gnome-session-fallback is not available, but is referred to
by another package._

_This may mean that the package is missing, has been obsoleted, or_
_is only available from another source_

_However the following packages replace it:_
_gnome-session-flashback_

_E: Package 'gnome-session-fallback' has no installation candidate_

_Failed to complete chroot setup._

How would I change gnome-session-fallback to gnome-session-flashback, I'm new to GitHub. Could you make a new repository or a branch of the origanal with that small change?

**Comment by anywhim** [comment]
You can install trusty with gnome DE and then upgrade it to xenial.

See https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release for upgrade instructions. Use -d flag when you will do do-release-upgrade.

**Comment by SoccerPie** [comment]
Thank you very much, I'll try it out and let you know! Thanks again.

**Comment by anywhim** [comment]
I went this way yesterday. Be sure it works.

**Comment by SoccerPie** [comment]
Alright thanks again!!!

**Comment by SoccerPie** [comment]
I updated it to xenial and said yes to every recommend change to the install and when I did sudo startgnome I got a black screen, but right after I entered gnome it said unknown user name.

**Comment by SoccerPie** [comment]
When you did it, did it come up with any yes or no suggestions?

**Comment by SoccerPie** [comment]
This time it said a fatal error occurred; I did exactly what you said.

**Comment by anywhim** [comment]
I tried to make dist upgrade from Ubuntu terminal and it fails. Then i used chrome os crosh terminal just as described in the instruction, chose default answers for all the questions and it was upgraded successfully.

After dist upgraded make sure that crouton is updated:
sudo sh -e ~/Downloads/crouton -n <chroot_name> -u

**Comment by SoccerPie** [comment]
That's what I was missing thanks.

**Comment by SoccerPie** [comment]
It gave the same error as when I just tried to install xenial without updating

**Comment by SoccerPie** [comment]
Both software centers say that they don't have authentication service. How do I install that.

**Comment by SoccerPie** [comment]
There is no authentication at all, and steam games don't work.

**Comment by drinkcat** [comment]
See #2723.
