### ISSUE TITLE
Sorry!(chromium.googlesource.com)|173.194.72.82|:443... failed: Connection timed out.   But ,i can open this webpage!

### ISSUE THREAD

**Issue by chen969196657** [dnschneid/crouton#2582]
--2016-05-13 14:16:21--  (try: 6)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/020abee6b983186bf3c60c6938021d7f1a8fae9a.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.72.82|:443... failed: Connection timed out.
Retrying.

--2016-05-13 14:18:35--  (try: 7)  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/020abee6b983186bf3c60c6938021d7f1a8fae9a.tar.gz
Connecting to chromium.googlesource.com (chromium.googlesource.com)|173.194.72.82|:443... failed: Connection timed out.
Retrying.

sorry. i english is so bad,please help me!

**Comment by divx118** [comment]
Take a look at https://github.com/dnschneid/crouton/issues/2554 see if that solves it.

**Comment by chen969196657** [comment]
Thank you!for this!😌

**Comment by divx118** [comment]
If that solved it for you, can you please close this issue. Thanks :)

**Comment by chen969196657** [comment]
sorry
