### ISSUE TITLE
CRAS compile failure

### ISSUE THREAD

**Issue by jasoncook** [dnschneid/crouton#2583]
```
name: kali-rolling
encrypted: no
Entering /var/crouton/chroots/kali-rolling...
crouton: version git
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 8302.0.0 (Official Build) dev-channel leon 
kernel: Linux localhost 3.8.11 #1 SMP Mon May 9 22:09:11 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /var/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
I just upgraded to Version 52.0.2727.0 dev (64-bit) and I'm receiving the same error as listed in #2572 
```
Compiling CRAS (i386)...
common/cras_config.c: In function 'cras_config_get_system_socket_file_dir':
common/cras_config.c:16:9: error: 'CRAS_SOCKET_FILE_DIR' undeclared (first use in this function)
  return CRAS_SOCKET_FILE_DIR;
         ^
common/cras_config.c:16:9: note: each undeclared identifier is reported only once for each function it appears in
common/cras_config.c:17:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
Failed to complete chroot setup.
```

#### If known, describe the steps to reproduce the issue:
Previous version of ChromeOS did not produce this error.

**Comment by randfur** [comment]
Seeing this as well when running `crouton -t xfce`.
Using Chrome 52.0.2727.0 (Official Build) dev (64-bit).
```
Compiling CRAS (i386)...
common/cras_config.c: In function 'cras_config_get_system_socket_file_dir':
common/cras_config.c:16:9: error: 'CRAS_SOCKET_FILE_DIR' undeclared (first use in this function)
common/cras_config.c:16:9: note: each undeclared identifier is reported only once for each function it appears in
common/cras_config.c:17:1: error: control reaches end of non-void function [-Werror=return-type]
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

**Comment by sgosnell** [comment]
Same thing for me, running Jessie.  It started today after updating to the newest Dev Channel version.  It won't run as is, and won't update.

**Comment by gs0622** [comment]
I am guessing it might be due to this commit:
https://chromium.googlesource.com/chromiumos/third_party/adhd/+/8d225aa3ef953f235d788509a0ba23b1f6504a5d%5E%21/

It looks to me expecting to use configure script to define CRAS_SOCKET_FILE_DIR however crouton installation script uses Makefile.am directly.

**Comment by drinkcat** [comment]
Can someone test https://github.com/dnschneid/crouton/pull/2589 ? I only compile tested it. Thanks!

**Comment by sgosnell** [comment]
I get this:`Compiling CRAS (i386)...
common/cras_config.c: In function 'cras_config_get_system_socket_file_dir':
common/cras_config.c:16:9: error: 'CRAS_SOCKET_FILE_DIR' undeclared (first use in this function)
  return CRAS_SOCKET_FILE_DIR;
         ^
common/cras_config.c:16:9: note: each undeclared identifier is reported only once for each function it appears in
common/cras_config.c:17:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
Failed to complete chroot setup.`

**Comment by gs0622** [comment]
Tested #2589 twice, works for me.

**Comment by jasoncook** [comment]
#2589 worked for me too. Excellent work.

**Comment by chrisj42** [comment]
I have been having this problem for the last couple months as well. I was getting desperate just when I saw #2589 had been merged. Resolved problem! Thanks so much!
