### ISSUE TITLE
[QUESTION] Is it possible to run react os in a chroot?

### ISSUE THREAD

**Issue by josephbarneslgs** [dnschneid/crouton#2584]
I was looking into react os and was wondering if it would be possible to install using crouton. Is it possible?

**Comment by connorkendrick** [comment]
I don't think so. Here's a forum where someone asked a similar question: https://www.reactos.org/forum/viewtopic.php?f=4&t=12946
There are other crouton-like services out there that might do the job, though it may just be too much work to get it working on a Chromebook.

**Comment by vladashram** [comment]
No, the chroots use the same kernel as the host OS. Ubuntu, Kali, debian, etc all use a Linux kernel(albeit tweaked for each one), so to get them to work with the ChromeOS-flavored Linux kernel isn't too tricky.
ReactOS however uses it's own kernel, based on Windows NT.
