### ISSUE TITLE
Hello,i used chroagh install archlinux ,But I have a problem，

### ISSUE THREAD

**Issue by chen969196657** [dnschneid/crouton#2587]
```
Please paste the output of the following command here: sudo enter-chroot
```
#### Please describe your issue:

chronos@localhost ~/Downloads $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/arch...
chown: invalid user: 'messagebus:messagebus'
[chen@localhost ~]$ 

 And  i use   :sudo startxfce4     

chronos@localhost ~/Downloads $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/arch...
chown: invalid user: 'messagebus:messagebus'
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.3
Release Date: 2016-04-04
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.2.5-1-ARCH x86_64 
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Apr 27 13:41:40 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4b356b89-75f7-7346-9975-1ff5c16b37f4/PARTNROFF=1 hashtree=PARTUUID=4b356b89-75f7-7346-9975-1ff5c16b37f4/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=07e3742c19e56b89d7092db9e9ff0ec33281ab05 salt=1d56cf0797d013802de94b27d604b52b057b3ef9628cd6603954f8a999f67168" noinitrd vt.global_cursor_default=0 kern_guid=4b356b89-75f7-7346-9975-1ff5c16b37f4 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 05 April 2016  05:24:02PM
 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun May 15 18:55:41 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version git
release: arch
architecture: x86_64
xmethod: xiwi
targets: xfce,xiwi
host: version 7978.66.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 27 13:41:40 PDT 2016 x86_64 GNU/Linux
freon: yes
hexdump: hexdump: /dev/input/event4: Permission denied
hexdump: /dev/input/event6: Permission denied
hexdump: all input file arguments failed

If you know what's reason ，Please help me

**Comment by drinkcat** [comment]
chroagh isn't well supported anymore, sorry...
