### ISSUE TITLE
chroot update (and subsequent reinstall) not completed

### ISSUE THREAD

**Issue by prostaff58** [dnschneid/crouton#2593]
this is the final section of the screen at reinstall (after a failed update) ARM 7l Samsung Chromebook. Trusty was running nicely for months until now. Ideas?

```The following NEW packages will be installed:
  patch
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 80.5 kB of archives.
After this operation, 183 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports/ trusty-updates/main patch armhf 2.7.1-4ubuntu2.3 [80.5 kB]
Fetched 80.5 kB in 0s (122 kB/s)
Selecting previously unselected package patch.
(Reading database ... 13881 files and directories currently installed.)
Preparing to unpack .../patch_2.7.1-4ubuntu2.3_armhf.deb ...
Unpacking patch (2.7.1-4ubuntu2.3) ...
Setting up patch (2.7.1-4ubuntu2.3) ...
patch set to automatically installed.
Compiling CRAS (native)...
common/cras_config.c: In function 'cras_config_get_system_socket_file_dir':
common/cras_config.c:16:9: error: 'CRAS_SOCKET_FILE_DIR' undeclared (first use in this function)
  return CRAS_SOCKET_FILE_DIR;
         ^
common/cras_config.c:16:9: note: each undeclared identifier is reported only once for each function it appears in
common/cras_config.c:17:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $ 
```

#### Please describe your issue

when updating it wouldn't complete the setup of chroot and at subsequent reinstallation AFTER powerwash, I get the same message.

#### If known, describe the steps to reproduce the issue:

update process and subsequently reinstall process

**Comment by prostaff58** [comment]
I should have mentioned that I am on:

Version 52.0.2727.0 dev
Platform 8302.0.0 (Official Build) dev-channel daisy
Firmware Google_Snow.2695.117.0

and using the latest crouton version:

 Chromium OS Universal Chroot Environment https://goo.gl/fd3zc

**Comment by prostaff58** [comment]
all of this while trying to update (then reinstall Trusty) with targets xfce and core.

**Comment by prostaff58** [comment]
OKay I see it's a CRAS issue from #2583. What is the solution to this?

**Comment by drinkcat** [comment]
Fix was merged, just try again. (you will want to remove the cache in `/tmp/*-installer-cache` before re-running the installer)

**Comment by prostaff58** [comment]
tip o' my cap to you, Drinkcat. amazing that you guys can figure this stuff
out and make it fly. miraculous that I found the temp directory you flagged
figured out rm -rf to eradicate the old cache. an old dog learning new
tricks.

best wishes and thanks,
Dave
