### ISSUE TITLE
Read-Only File System Errors w/ SD Card Install

### ISSUE THREAD

**Issue by mikepalarz** [dnschneid/crouton#2594]
#### Output of `sudo sh edit-chroot -all`:

```
name: trusty
encrypted: no
mount: cannot remount /dev/sdb1 read-write, is write-protected
```
#### The Issue:

I've been using crouton to primarily be able to run Android Studio on my Chromebook for quite some time now. The special case that I have with my crouton install is that I've performed the installation onto an SD card instead of directly onto my SSD storage. The main reasoning for this is so that I don't waste any of the precious SSD that I have available (16GB) and make use of the 64GB I have on the SD. 

However, every now and then, I run into read-only file system errors. What I mean by this is that I can't perform any tasks after some time because of some strange read-only errors. When I initially boot up my crouton target (which is XFCE), everything works great: Android Studio runs, as well as Google Chrome, etc. However, after closing and reopening my CBook a few times, the read-only errors arise.  The number of times the close/reopens need to happen in order to reproduce the issue varies: sometimes it only occurs after closing/reopining once, sometimes it occurs after several closes/reopens. And when I say close/reopen, I mean "putting the CBook to sleep" and "reawakening it". What I believe the issue is that upon reawakening the CBook, the SD card isn't mounted properly in the way it was originally. A very vague explanation but it's the best I can come up with on my own. 

For example, I was going to take a screenshot of one of the errors that normally occur when I try to relaunch Android Studio. However, when I attempted to save the screenshot onto my desktop, I received the following error message:

`Failed to open '/home/mike/Desktop/Screenshot - 051716 - 20:51:55.png' for writing: Read-only file system`

Furthermore, the error message that I received when I try to launch Android Studio is the following:

```
Log path '/root/.AndroidStudio2.1/system/log' is inaccessible.
If you have modified the 'idea.log.path' property please make sure it is correct,
otherwise please re-install the IDE.
```

After doing some research, it turns out that I need to edit the idea.log.path property in the mentioned file. However, when I attempted to do this using vim, it would not allow me to save my edits since the file was marked as read-only. 

I tried chown, chmod, which I don't completely understand how to use, but it did not make a difference for the issue. 

I've given two examples on what occurs with this issue in order to emphasize that this is not a software-specific issue (not just Android Studio is experiencing this problem). Obviously, if I can't even take a simple screenshot using the default program that's built into XFCE (straight from the applications menu) and save the image onto my desktop, then the problem is more widespread. 

I'm not expecting a complete resolution to this. However, what I would like to know is what is the cause of this issue, why is it happening? I've already prepared myself that this will eventually lead me down the road to reinstall crouton onto my SSD and use the SD as expanded storage. However, some explanation for potential causes of the problem would be appreciated. 
#### Temporary Solution to the Issue

In order for me to get back into my crouton target, I need to restart my CBook and relaunch it. This is because once I log out of XFCE and `trusty` and try to launch the target once again, the following happens:

`chronos@localhost /media/removable/SDCard/crouton/bin $ sudo sh /media/removable/SDCard/crouton/bin/enter-chroot 
Entering /media/removable/SDCard/crouton/chroots/trusty...
/media/removable/SDCard/crouton/bin/enter-chroot: 509: cannot create /run/crouton/media/removable/SDCard/crouton/chroots/trusty/etc/crouton/name: Read-only file system
Unmounting /media/removable/SDCard/crouton/chroots/trusty...`

I then `umount` my SD card and run `sudo mount -a` to be certain that every device is properly mounted and retry the above command. However, I always receive the same output. So, in order to avoid manually removing the SD card (and cringing over the thought of ruining the card), I simply reboot and start up XFCE once again.

**Comment by lzantal** [comment]
I solved this issue by installing Keep Awake extension. When running my chroot I just click the icon to be sunset which keeps the system awake when the lid is closed. Battery life seems to be the same.

**Comment by BIGxRED** [comment]
Hey, appreciate the input! Just curious, even if I enable the PC to be awake through the extension, does the screen at least turn off when I close the lid? As in, when I close the lid, I shouldn't see the light emitting from the screen in a dark room.

**Comment by lzantal** [comment]
Yep it puts the screen nicely into sleep and other stuff too. I haven't noticed a bit on the battery life.
