### ISSUE TITLE
Installing Xenial with unity fails

### ISSUE THREAD

**Issue by lzantal** [dnschneid/crouton#2596]
Was trying to install xenial with unity to take it for a spin. Everything seems to be installing fine but then I get this error
```
E: Unable to locate package unity-2d
Failed to complete chroot setup.
```

Installing it on Toshiba Chromebook 2

**Comment by JasonSwindle** [comment]
I got the same error, and have not found a work-around.

**Comment by 1rocketdude** [comment]
unless you're wedded to unity, have a try at LXDE or XFCE. I have been running LXDE since xenial came out. Works great.

**Comment by lzantal** [comment]
Hi, I have tried to install LXDE but it never worked. I am using xfce for now until its fixed. I'ts ok but all my windows look like crap 👎 
When trying to use LXDE as a target it errors out at the installation part.

**Comment by 1rocketdude** [comment]
I don't know what to say. I've used LXDE on two different chromebooks
(Intel ones), and it always "just works". Never had installation problems.

**Comment by DennisLfromGA** [comment]
For a possible, temporary workaround, see: https://github.com/dnschneid/crouton/issues/2720

**Comment by drinkcat** [comment]
See #2720.
