### ISSUE TITLE
Installing Ubuntu on Hisense Chromebook, Fatal Error No Screens Found.

### ISSUE THREAD

**Issue by danethemichael** [dnschneid/crouton#2599]
Hello, I've been trying to install Ubuntu on my Hisense Chromebook and I keep running into the same issue. Everytime I try sudo startunity I get this:

Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP Sat Apr 9 17:15:17 PDT 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=3a8f1e18-a664-6447-90d6-4715725ca459/PARTNROFF=1 hashtree=PARTUUID=3a8f1e18-a664-6447-90d6-4715725ca459/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=30066b3bc42cb96863745304ea2fe313a308c3b1 salt=1f55cec66376d459492cb9a095de5752511e9d614035bd3d492abdc0b0d3831e" noinitrd vt.global_cursor_default=0 kern_guid=3a8f1e18-a664-6447-90d6-4715725ca459  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun May 22 17:39:26 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I'm not very experienced at this, I've looked all over some kind of fix and so far none of them have worked.

**Comment by tredoran** [comment]
I'm having the same issue.

**Comment by yooncheolc** [comment]
Try below:
sudo enter-chroot
sudo rm /dev/dri/card0
sudo mv /dev/dri/card1 /dev/dri/card0
exit

then startunity

**Comment by tredoran** [comment]
@yooncheolc Thank you so much. This solved my issue. To break it down for a noob like myself, what exactly did we do here which made it work? I read other threads that said to downgrade my version of chromeOS to fix it which did not work for me. What did we basically do here that made it work per say? Just curious. Anyway, thanks again.

**Comment by yooncheolc** [comment]
@tredoran I'm no expert on these as well, but as far as I can tell those commands just make the system indicate and use the correct graphic driver - card0 with contents in card1.

**Comment by dnschneid** [comment]
This is fixed now in the latest crouton, no hacks needed.
