### ISSUE TITLE
can't execute script with ./

### ISSUE THREAD

**Issue by trogdan** [dnschneid/crouton#26]
So, apps I'm using in the chroot have scripts that expect to be able to use ./ to execute.  Using this gives permission denied errors.  I assume this is because the inherited mount from chrome , that is the root mountpoint, does not appear to have exec privileges, hence why you have to execute crouton with sh -e

Any ideas to enable using ./ in the chroot?  Another mount point for the chroot root maybe?

**Comment by harryganz** [comment]
@dnschneid Hi, I am having the same issue executing a script on a removable SD card. Your workaround works, but I have to redo it every time I remount the chroot. Should I create a new issue?
