### ISSUE TITLE
Sana/Lxde VirtualBox Problem

### ISSUE THREAD

**Issue by LinuxJunkie** [dnschneid/crouton#2603]
Hello. I am trying to install virtualbox in sana/lxde, and I have/had encountered a problem after utilizing the following steps:

Step One: I had ran this command in to the terminal, "sudo apt-get install libncurses5-dev dpkg-dev" to obtain the tool that I needed to compile the kernel. Which that was/is a success.

Step two: I ran this command, "sudo apt-get install git-core make kernel-package", also to obtain another tool that I needed to compile the kernel. Which that was/is a success.

Next, I ran the command, "sudo git clone https://chromium.googlesource.com/chromiumos/third_party/kernel -b chromeos-3.8", to clone the kernel into my home directory. Which that was a success too.

After that command. I changed into the kernel directory using the cd command to edit the base config file with the following command, "sudo leafpad chromeos/config/base.config", and I succeeded with the editing the part that I need to from the following webpage, "https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)".

Then, I ran the command, "sudo /chromeos/scripts/prepareconfig chromeos-intel-pineview", in the kernel directory, which was a success as well.

Furthermore, I issued the command, "sudo make oldconfig" within the kernel directory without any problems too.

From this point, I edited my rc.local file from using the directions of the webpage I had listed above. No problems were found at this point either. Everything was smooth sailing, so I logged out and back in to issue the command, "sudo cat /proc/mounts | grep /lib/modules", to find that no modules were mounted. Of course this was after the fact I had already granted permission to the new rc. local file with the command, "sudo chmod +x /etc/rc.local".

Finally, I started to build my kernel headers and images with the following commands found on the webpage that I listed above, and I had no problems.

Here is where I started to gain a problem though. I tried to install virtualbox by downloading the debian wheezy x86 deb package, in which I succeeded with that, but once I tried to run the OS that I had set up in the virtual machine; I was greeted with an error that displayed that I needed to run the following command, "sudo /sbin/rcvboxdrv setup", so I did. 

Anyway, it appeared that all was going well until it advised me, Starting VirtualBox kernel modules ...failed! (modprobe vboxdrv failed. Please use 'dmesg' to find out why), so I did run the command dmesg, and I was greeted with the following:

[18902.505261] Chromium OS LSM: init_module denied module="/lib/modules/3.8.11/kernel/misc/vboxdrv.ko" pid=21777 cmdline="/sbin/modprobe vboxdrv"
[19683.364214] Chromium OS LSM: init_module denied module="/lib/modules/3.8.11/kernel/misc/vboxdrv.ko" pid=26899 cmdline="/sbin/modprobe vboxdrv"

Can Anyone help me please?

**Comment by divx118** [comment]
@LinuxJunkie Yep, you need to disable module locking. See section https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)#installing-kernel-headersimage First few lines of that chapter.

**Comment by LinuxJunkie** [comment]
Okay, I ran the procedure from the page that you had mentioned, in order to disable the module locking. It definitely did something, but it did not make everything work. The out put of the command dmesg gave back this following results:

[  313.087243] Chromium OS LSM: init_module locking-ignored module="/lib/modules/3.8.11/kernel/misc/vboxdrv.ko" pid=26872 cmdline="/sbin/modprobe vboxdrv"
[  313.088520] vboxdrv: Unknown symbol alloc_pages_current (err 0)
[  627.442824] Chromium OS LSM: init_module locking-ignored module="/lib/modules/3.8.11/kernel/misc/vboxdrv.ko" pid=30003 cmdline="/sbin/modprobe vboxdrv"
[  627.443923] vboxdrv: Unknown symbol alloc_pages_current (err 0)

What is it that I need to do now? Thank you for your help in advance!
