### ISSUE TITLE
gnome-session-fallback is not available while installing xenial

### ISSUE THREAD

**Issue by MobFactory** [dnschneid/crouton#2607]
```
sudo sh -e ~/Downloads/crouton -r xenial -t gnome,gnome-desktop,xiwi
```

#### Please describe your issue:
I cant get xenial to install with gnome. I can get trusty and precise to install but xenial is not having it. System used is a macbook pro 2011 running cloudready. Everythng runs fine except xenial

#### If known, describe the steps to reproduce the issue:
just attempt to run the code above. Ive tried to install it on several chromebooks all have this problem.

**Comment by anywhim** [comment]
You can install trusty with gnome DE and then upgrade it to xenial.

**Comment by MobFactory** [comment]
trusty gave me the same problem. Only precise will install. How can i upgrade precise to xenial

**Comment by anywhim** [comment]
See https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release for upgrade instructions. Use -d flag when you will do do-release-upgrade.

**Comment by anywhim** [comment]
I tried to make dist upgrade from Ubuntu terminal and it fails. Then i used chrome os crosh terminal just as described in the instruction, chose default answers for all the questions and it was upgraded successfully.  

After dist upgraded make sure that crouton is updated:
`sudo sh -e ~/Downloads/crouton -n <chroot_name> -u`

**Comment by drinkcat** [comment]
See #2723.
