### ISSUE TITLE
Crouton UI crashes after a couple of seconds

### ISSUE THREAD

**Issue by guimingTang** [dnschneid/crouton#2608]
sudo edit-chroot -all output:

```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160518095657~master:fd37bb79
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 7978.69.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Apr 28 15:48:22 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
```

Hi all, 
I'm trying to install Crouton on my Asus Flip (C100). I managed to install everything without issues, crouton even booted smoothly on the first try. 

After switching back to ChromeOS and working on it for a while I tried to switch to crouton again. This time it failed. The screen would freeze on ChromeOS's UI, and crouton's ui was absent. Switching between chrome and crouton using Shift+Alt+Ctrl +forward/back seemed to fix the issue for a couple of seconds, but as soon as I attempted to do anything crouton ui would crash again. 

It seems the UI was the only thing that crashed because mouse hover animations still reacted to the crouton ui's buttons, but not to chromeOS. Keyboard input was still captured by crouton while UI crashed (I tried it by opening shell in crouton on the frozen ui and typed a bunch of commands, they worked).

I also tried installing different UIs (unity, xfce, touch/no touch). All crashed the same way.

There is no error message on the chroot output. The rest were warnings.

```
No Chromium OS X server is available.
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
(xfsettingsd:24253): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(xfwm4:24245): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(xfce4-session:24239): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
xfdesktop[24251]: starting up
(polkit-gnome-authentication-agent-1:24259): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed
(polkit-gnome-authentication-agent-1:24259): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(xfdesktop:24251): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(xfce4-panel:24247): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(xfce4-settings-helper:24268): xfce4-settings-helper-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
(wrapper:24277): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
```

Has anyone experienced this issue before? Thanks a lot

UPDATE: Rebooting chromebook seems to fix the problem. Still have no idea why

**Comment by LandonPowell** [comment]
I experienced this issue as well. 
The only fix for me is a reboot to the chromebook. 

The xfce desktop launched for a few seconds, and then as soon as I touched the mouse cursor the DE disappears and leaves you with a non-functioning chrome desktop with the XFCE cursor. 

That was using the `startxfce4` command. `startx` seems to just make everything go blank and not work.

**Comment by guimingTang** [comment]
I found a temporary solution by running crouton in windowed mode. 

Install xiwi using: (https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi))
`crouton -u -t xiwi`
Then install the Crouton integration extension [here](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)
Lastly launch Crouton using `sudo startxfce4 -X xiwi`. 
At least this worked for me, and it seems to be a better way of launching crouton too

**Comment by RyM21** [comment]
I have this same issue. Very frustrating.

**Comment by drinkcat** [comment]
Hopefully fixed?
