### ISSUE TITLE
Display Issues chromebook pixel 2

### ISSUE THREAD

**Issue by ianhalpern** [dnschneid/crouton#2609]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,cli-extra,touch,unity
host: version 8172.45.0 (Official Build) beta-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 25 20:59:06 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```
#### Please describe your issue:

Below is an example of a display issue I've been experiencing on the Chromebook Pixel 2. Sometimes letters disappear, sometimes they render incorrectly, sometimes windows or overlays don't fully render but you can click away and then click back on the window and it will correct itself. This has only recently become an issue.

![screenshot from 2016-06-02 22 30 29](https://cloud.githubusercontent.com/assets/382123/15767013/5d02812e-2912-11e6-9d9e-3c756625c462.png)

**Comment by phedders** [comment]
I have the same - in a xiwi terminal window the top left quarter stays updating, and the rest stops all redraw unless I change focus and return.
I'm on the dev channel at the moment (eager for android apps :) )

name: deb
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/deb...
crouton: version 1-20160518095657~master:fd37bb79
release: stretch
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,audio,cli-extra
host: version 8350.1.0 (Official Build) dev-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue May 24 17:48:18 PDT 2016 x86_64 GNU/Linux
freon: yes

Really hope someone has a fix or workaround!

**Comment by phedders** [comment]
I have the same - in a xiwi terminal window the top left quarter stays updating, and the rest stops all redraw unless I change focus and return.
I'm on the dev channel at the moment (eager for android apps :) )

name: deb
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/deb...
crouton: version 1-20160518095657~master:fd37bb79
release: stretch
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,audio,cli-extra
host: version 8350.1.0 (Official Build) dev-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue May 24 17:48:18 PDT 2016 x86_64 GNU/Linux
freon: yes

Really hope someone has a fix or workaround!

**Comment by ianhalpern** [comment]
So the card is a Broadwell-U card and I just found this:

http://askubuntu.com/questions/625978/graphics-and-font-problem-in-ubuntu-14-04-with-intel-broadwell-u-integrated-grap

So I'm going to do some digging but it sounds like it's not so much a crouton issue but a intel driver issue.

lspci output:
```
VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
```

**Comment by greghendershott** [comment]
I'm seeing similar issues with Xorg. I used Crouton on Pixel 2 heavily for many months and did not see this issue. Then I (sadly) did not use  it the last ~4-5 months. About a week ago I started using it again, and needed to update ChromeOS and to the latest version of Crouton.

Now I'm seeing "black boxes" in Firefox, and partial lines fail to redraw in Emacs 24.5. It's infrequent and I can manually cause a redraw, so it's only mildly annoying. But it's nothing like the rock-solid display I had in all my previous time using Crouton. So I came here to see if this was just a glitch I had the bad timing to upgrade into.

```
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Thu May 12 21:47:41 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=e4b65bd6-7d6e-ca46-ae25-57c0b8275b4a/PARTNROFF=1 hashtree=PARTUUID=e4b65bd6-7d6e-ca46-ae25-57c0b8275b4a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=ab498bb8ca011ab439ea02000f6e0fdfb888f14d salt=54d05e36d80cb11eff6eb5626872a072b6b1e0f0f009c824386c0b33595e72e7" noinitrd vt.global_cursor_default=0 kern_guid=e4b65bd6-7d6e-ca46-ae25-57c0b8275b4a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue May 31 09:27:39 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: touch,unity
host: version 7978.76.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu May 12 21:47:41 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) AIGLX: Suspending AIGLX clients for VT switch
```

**Comment by danopia** [comment]
I have the same report as @phedders , switched to Beta recently and today (after an update) I launched Atom and only the top left was updating properly.

For the most part, it appears that only the top left quadrant of *every paint blitting* was coming through. I immediately suspected Retina problems, but it doesn't seem relevant.

**Comment by phedders** [comment]
So the key problem for me is resizing a xiwi window.

I have found that if I resiez then click on the title bar and "refresh" it seems to work better for a while.

**Comment by radix** [comment]
Yeah, Atom works fine for me until I try to maximize, move, or resize the window it's in. It gets fixed if I close the window and use the chrome extension to reopen it, but it reopens at a size that's much too small...

**Comment by phedders** [comment]
See [https://bugs.chromium.org/p/chromium/issues/detail?id=633806](url).
I think this ticket can be closed now.

**Comment by robertoandrade** [comment]
Was having the same issue with Chrome 52 (stable), upgraded to 53 (beta) and the issue went away! Thanks for the pointer. It was driving me nuts!
