### ISSUE TITLE
starte17 fails when included in enter-chroot command

### ISSUE THREAD

**Issue by elperdido** [dnschneid/crouton#2613]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xiwi
targets: gtk-extra,e17,gnome,xiwi,xfce
host: version 7978.74.0 (Official Build) stable-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Thu May 12 00:50:00 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:

```
chronos@localhost / $ sudo enter-chroot -n trusty starte17
Entering /mnt/stateful_partition/crouton/chroots/trusty...
-su: 1: starte17: not found
```

`sudo enter-chroot -n trusty startgnome || startxfce4 `
work as expected.

Enlightenment can be started by running the wrapper script directly:

`sudo /usr/local/bin/starte17`

#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
It's in the host-bin not the chroot-bin so, from crosh, just use: `sudo starte17 -n trusty`
It will, in turn run `xinit /usr/bin/enlightenment_start` in the chroot shell.

**Comment by elperdido** [comment]
Thanks Dennis. Turns out the bug was in the user!

**Comment by DennisLfromGA** [comment]
Happens to all of us - especially me! :+1:
