### ISSUE TITLE
Unable to switch back to Chrome OS after upgrading to wily.

### ISSUE THREAD

**Issue by WastingAway1** [dnschneid/crouton#2616]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

sudo: edit-chroot: command not found
#### Please describe your issue:

I am using xfce4 on a Toshiba Chromebook 2, I recently upgraded to wily on it and am now having the issue of being unable to switch back to Chrome OS after turning on xfce. I am using the correct command (ctrl+shift+alt+f1/f2) however whenever I try the screen just goes black, when I use the command again I switch back into xfce, as if I had just switched back from Chrome OS.
**I saw another issue like this before that just said to update the chroot, it hasn't worked**

**Comment by DennisLfromGA** [comment]
While in your chroot at a shell prompt, enter: `croutoncycle cros` and see if that takes you back to crosh.

**Comment by WastingAway1** [comment]
I tried it and the same thing happened as when I did ctrl+shift+alt+f1/f2, the screen went black. I was able to get back into xfce the same way. @DennisLfromGA

**Comment by WastingAway1** [comment]
Side note - this is really only a problem for me because you can't shut down the Chromebook properly inside xfce, I prefer using it so I would be perfectly alright removing Chrome OS altogether so long as it will work properly. @DennisLfromGA

**Comment by DennisLfromGA** [comment]
I didn't see the output of croutonversion so I don't know what targets you've installed or what xmethod you're using but, you might want to try installing/using 'xiwi' instead of 'xorg'. You can open it in a full window or even in a tab in the browser. It's a good alternative if you aren't using graphic intensive apps. I even run kodi in a tab on mine and it still works great.

**Comment by idvoretskyi** [comment]
@WastingAway1 wily is a bit outdated version, have you tried xenial?
