### ISSUE TITLE
xiwi launch problems (xorg works fine)

### ISSUE THREAD

**Issue by TsinghuaMike** [dnschneid/crouton#2618]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,keyboard,touch,unity,extension
host: version 8350.21.0 (Official Build) dev-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Jun 6 22:07:35 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue:
I've been trying for weeks to get my chroot to launch in an xiwi window. I use and love xorg, but with the new android apps soon coming to chromeos, I would like to have this option. As per instructions from @DennisLfromGA , I used this command to add the xiwi target to my chroot:
`sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`

xorg is still my default:  (I used this command):
`sudo sh ~/Downloads/crouton -n trusty -t xorg -u`

However, when I try to launch xiwi with this command...
`sudo startunity -n trusty -X xiwi`

....my output includes this:

Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...

In case anyone is wondering, I do indeed have the crouton integration web store extension installed. Unfortunately, I do not know what any of this output means or how to interpret a log file. I appreciate anyone taking their time to read this and help me out!

#### If known, describe the steps to reproduce the issue:

I'm not sure if this problem is unique to my chroot, or to others. I would appreciate if others chime in if they have this problem.

Note: I second the occasional issue with graphics display that other pixel 2 users have mentioned. (seemingly related to an intel driver)

**Comment by phedders** [comment]
You wouldn't run unity in a xiwi - the point of xiwi is to use chrome native window manager and the X windows in chrome window.

Try
sudo startxiwi -n trusty -b sakura &
sudo startxiwi -n trusty -b firefox &
sudo startxiwi -n trusty -b .... &

**Comment by DennisLfromGA** [comment]
@phedders,

Yes, you can indeed run a unity desktop or any other desktop via the 'xiwi' xmethod.
You can run it full-screen with '-F', in a window with no option, or in a tab with '-T'.

You can also run chroot 'apps' like you recommend but you're not limited to just apps with 'xiwi'.

----

@TsinghuaMike,

I'm not sure what's causing your desktop to fail when launching.
I know I personally sometimes have to try to start it a time or two, or three before it kicks in.

When I get a chance, I'll try to research this; wish I had a Pixel, it'd make the testing (and a lot of things) so much easier. ;)

-**DennyL**

**Comment by TsinghuaMike** [comment]
@phedders  Holy cow! I didn't know you could just launch like say R Studio like that. Thanks!

@DennisLfromGA Not sure exactly what my issue is/was, but I just started a new chroot from scratch. Hate when it comes to that but I've gotten used to it and actually I'm starting to get quite efficient at making new chroots

**Comment by DennisLfromGA** [comment]
@TsinghuaMike,

Glad you got it worked out and glad that you learned some new stuff from @phedders.

You can probably close this issue now if you like.

-**DennisL**
