### ISSUE TITLE
Toshiba Chromebook 2 broadwell, too many issues

### ISSUE THREAD

**Issue by alexmigf** [dnschneid/crouton#2619]
Hi,

I have installed Crouton based on this guide http://www.voltron00x.com/?p=1091 and i'm facing too many issues, don't know what do.

Sometimes mouse don't work, sometimes the screen stop and goes black, sometimes when i power off it shows white screen, and i can't for example change the background image, when i boot again it shows the default greek island image.

I have updated chroot but the problems persist.

Can anyone with this device help me?

**Comment by cefn** [comment]
Not sure what configuration you have gone for, but I'm running LXDE trusty fine on a Toshiba Chromebook 2, and have been for a long while. I tend to leave the Chrome OS running for weeks, closing to suspend, opening to resume though, so potentially there could be issues which I haven't encountered around hibernation, power-cycling etc.

**Comment by alexmigf** [comment]
Are you using the Broadwell Celeron?

**Comment by cefn** [comment]
I have the Baytrail version.

**Comment by alexmigf** [comment]
Yeah, not the same. I end up installing Gallium, i can't waste more time with this right now :(.

**Comment by raidzero** [comment]
FWIW, I run crouton on my broadwell CB2 (i3 version), and it works perfectly. The only issue I have is if I do not hide the mouse cursor before switching my chroot xorg environment the cursor will be corrupted like in the video issue #1519. I have no screen flashing. I did install the 01.org graphics drivers but it has made no difference on the cursor thing.

I run i3wm via xinit on a xenial chroot. I can even run half life 2 on my CB2 :) 
I also use xiwi to launch certain apps within the chrome environment. 

This is my /etc/crouton/targets: `xorg,xfce,xiwi,extension,x11`

**Comment by 1rocketdude** [comment]
no problems with my Toshiba CB2 running LXDE. Reports are that Unity will not work, but LXDE and XFCE work well. chroots are cheap and easy to create. Try either LXDE or XFCE.

**Comment by alexmigf** [comment]
I was using XFCE, are you sure you have the Broadwell?

**Comment by pmarkkula** [comment]
Following combination works for me:

- 3205U
- Xenial
- XFCE
- ChromeOS 56.x
- Modesetting driver with glamor acceleration.

There is tearing and other problems if you don't enable compositing.

I used to have the mouse cursor corruption problem with SNA and Intel (https://download.01.org) driver, but with modesetting driver there is no corruption even with stock xenial driver.

There is possibility that it was the ChromeOS upgrade (56.x) that fixed the cursor as I did not test with that and Intel driver. I upgraded ChromeOS and changed to modesetting driver at the same time.

**Comment by DennisLfromGA** [comment]
@alexmigf,

#### I'm using a Dell Chromebook 13 which is a Broadwell device (Intel Core i5-5300U CPU @ 4x 2.9GHz), it's not a Celeron so my experience may be a little different.

> I have installed Crouton based on this guide http://www.voltron00x.com/?p=1091 and i'm facing too many issues, don't know what do.

##### The voltorn00x guide is a pretty good one so I don't think that's the problem.

> Sometimes mouse don't work,...

##### I have a [Logitech M-325](https://www.amazon.com/Logitech-Wireless-Mouse-Designed-Scrolling/dp/B005DSPLCQ) that works perfectly well in CrOS and in my crouton desktops, perhaps your mouse isn't 100% compatible.

> sometimes the screen stop and goes black,...

##### There have been some recent problems with blackscreens using the 'xorg' xmethod that have [a workaround](https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795) but that doesn't sound like what you're running in to. I would think your issue pertains to the xfce4 desktop and not so much a crouton issue so I would search for help with that on [stackexchange](http://unix.stackexchange.com/questions/tagged/ubuntu), etc.
##### If you can't find any answers you might try using the 'xiwi' xmethod.

> sometimes when i power off it shows white screen,...

##### I also have that happen to me when I forgot to resume the power daemon that I stop when I enter a shell.
##### I use a `.bash_logout` script to restart it, it contains the following procedure:

```
# Re-Start Screen Timeout
powerd_status=$(sudo initctl status powerd|grep -q stop; echo $?)
if [ "$powerd_status" = 0 ];
then sudo initctl start powerd 2>&1 >/dev/null; fi
```

> and i can't for example change the background image, when i boot again it shows the default greek island image.

##### That again sounds like an xfce4 desktop issue, see this page for some possible fixes: [save xfce4 settings](https://ubuntuforums.org/showthread.php?t=2048945)

*Hope this helps,*
-**DennisL**
