### ISSUE TITLE
autostart scripts generates wrong command ?

### ISSUE THREAD

**Issue by pebauer68** [dnschneid/crouton#2623]
I am running xenial on Asus C100 with xiwi, Chrome 51 beta.
crouton manul start works fine, but the autostart command parsing fails ?

Autostart configured accroding to:
https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup

The Autosart script has a bug ?
Is the passed command wrong, or is it missing a parameter ?
output in /var/log/message:
localhost bin # sudo /usr/local/bin/enter-chroot -c /usr/local/chroots -n xenial -X xiwi xfce4-terminal
Entering /mnt/stateful_partition/crouton/chroots/xenial...
(xfce4-terminal:749): Gtk-WARNING **: cannot open display:
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...

This would work (tested via ssh login):
localhost bin # sudo /usr/local/bin/enter-chroot xiwi xfce4-terminal

Best Regards,
Peter
pebauer68@gmail.com

**Comment by DennisLfromGA** [comment]
@pebauer68,

[I *swear* I responded to this yesterday but I can't find it today - oh well.]

So, when you enter:

`sudo /usr/local/bin/enter-chroot -c /usr/local/chroots -n xenial -X xiwi xfce4-terminal`

from the command-line it launches correctly but it won't launch from the 'autostart' script - correct?

If that's the case, then you should be able to get more details from the debug output stored in `/tmp/crouton-$PID.log`. The $PID is the process that the 'autostart' script was running.

If we could see those details, we can try to narrow down the cause and hopefully fix it.

---
If you have modified the `/etc/crouton.conf` file (not recommended for other than setting one of the 4 starting options), let us see that.

Also, if you have a `crouton.init` file in `/usr/local` or in `~/Downloads`, let us see it so we can look for some anomalies in it.

In your scenario, you could put the following contents in a `/usr/local/crouton.init` file and I think it should work:

```
CHROOT=xenial
START_DE=startxiwi
CHROOT_APP=xfce4-terminal
```

*Hope this helps,*
-**DennisL**

**Comment by pebauer68** [comment]
Thank you for your help:
The "-X" Parameter ist too much for my configuration, it comes from your file crouton.conf located here:
https://gist.githubusercontent.com/DennisLfromGA/6443733/raw/c24908947576ad0687ac5006427fc48a51bc774c/crouton.conf

I changed lines 207 in crouton conf and now it works:
please check line 207: 
case $XMETHOD in
    xorg|xiwi|xephyr)
      XMARG="$XMETHOD"      /*this works for me

your original file:
case $XMETHOD in
    xorg|xiwi|xephyr)
      XMARG="-X $XMETHOD"       /*this gives me wrong/unknown parameter error

crouton.init:
CHROOT=xenial
START_DE=startxiwi
CHROOT_APP=xfce4-terminal

Best Regards,
Peter
http://www.bitkistl.com

**Comment by DennisLfromGA** [comment]
@pebauer68,

*Glad you got it working.* 👍 

----
I thought the error you received was:
>(xfce4-terminal:749): Gtk-WARNING **: cannot open display:

I didn't see the error: 
>wrong/unknown parameter error

The XMETHOD routine starting on line 205 and ending on line 216 in `crouton.conf` is to determine if a temporary XMETHOD was specified in the `crouton.init` file. If you don't specify an XMETHOD in your `crouton.init` file, then the script will use the one that is set as the default in your chroot (`/etc/crouton/xmethod`).

In the `crouton.init` file you show above, there is no XMETHOD parameter specified so the XMETHOD routine should not specify an $XMARG value (it will be null). You can verify this from the debug output file `/tmp/crouton-$PID.log`.

----
I'll run a few different scenarios with different XMETHODS and CHROOT_APPs to see if I get any errors. I know everything was working at one time but I'll check again.

-**DennisL**

**Comment by pebauer68** [comment]
This is the subsequent error in terminal:
(xfce4-terminal:749): Gtk-WARNING **: cannot open display:

/tmp/crouton-$PID.log shows:
+ eval sudo /usr/local/bin/startxiwi -c /usr/local/chroots -n xenial -X xiwi xfce4-terminal
+ sudo /usr/local/bin/startxiwi -c /usr/local/chroots -n xenial -X xiwi xfce4-terminal
**Illegal option -X**          /* wrong/unknown parameter !?
startxiwi [options] chroot_app [parameters]

Sorry I did not include the log before.
Thank you

**Comment by DennisLfromGA** [comment]
@pebauer68,

That's just *part* of the debug output and it doesn't show if an XMETHOD was acted upon.
I'd like to examine the entire output to see exactly what's going on.
I can't understand where the '-X xiwi' is coming from in your output above if an XMETHOD is *not* specified in the `crouton.init1 file - something seems awry...

Also, it looks like you're still getting the 'Gtk-WARNING' so does it work or not?

-**DennisL**
