### ISSUE TITLE
Removing  A desktop enviroment from a release

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#2628]
I Would like to know how I can remove a desktop from a release. I installed e17 and lxde on Xenial but I don't want e17 anymore, how can I remove it? Btw I am using a ChromeBook.

**Comment by DennisLfromGA** [comment]
@brandon26901,

There's another issue where target/desktop removal was discussed here: DE/target removal #717
It detailed a method using `apt-mark auto` that worked for me. It's a bit of a manual process but it *does* seems to work well.

'crouton' hasn't incorporated this or any other methods yet though so we're left with manual methods for now. 

Hope this helps,
-**DennisL**
