### ISSUE TITLE
chroot not loading

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#2629]
I have created a chroot with lxde and it won't load the desktop. Whenever I type `sudo startlxde` it loads a blank screen then goes back to the crosh terminal, except it loads the lxde mouse cursor and I can't do anything after, unless i press `ctrl + alt + shift + <-` the <- would also be known as f1.

**Comment by DennisLfromGA** [comment]
Please show us the output of `sudo edit-chroot -all`
It helps us help you.

**Comment by brandon26901** [comment]
sudo: edit-chroot: command not found

**Comment by DennisLfromGA** [comment]
@brandon26901,

The `edit-chroot` script should be run from a crosh shell session, not from your chroot.
You can also get these results from a chroot shell session by entering: `croutonversion`.

-**DennisL**
