### ISSUE TITLE
Opening xiwi window/tab in background?

### ISSUE THREAD

**Issue by ecollins** [dnschneid/crouton#2630]
```
name: jessie
encrypted: no
Entering /media/removable/mnemo/chroots/jessie...
crouton: version 1-20150620222151~master:89796a99
release: jessie
architecture: amd64
xmethod: xorg
targets: lxde,e17,xorg,xiwi
host: version 8172.47.1 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Mon Jun 6 15:26:51 PDT 2016 x86_64 GNU/Linux
freon: yes
```
#### Please describe your issue:

I have my Debian terminal open in a tab whenever I'm working (via enter-chroot), and open graphical applications with "xiwi -T [application]". On any other machine, I'd use "[application] &" to run it in the background so I can have access to the prompt, but xiwi tabs don't seem to have a way of running in the background. Do I have to run enter-chroot a second time in another tab to get my precious greping and finding back, or is there a way to mimic the functionality of that trailing ampersand?

**Comment by DennisLfromGA** [comment]
@ecollins,

I don't know that I've tried to use `xiwi` with a trailing ampersand in a chroot, I am surprised it doesn't allow it to run in the background that way though. If I get some time, I'll experiment with it.

I usually run `startxiwi` from a crosh shell specifying the chroot app and freeing up the terminal.
The 'start*' scripts use `enter-chroot` with some additional parameters so you can use many of `edit-chroot's` options when launching them.

Here's `startxiwi's` usage syntax -
```
startxiwi [options] chroot_app [parameters]

Wraps enter-chroot to launch a window or tab in Chromium OS for any graphical application.
Applications launched in this way show in independent windows or tabs.

By default, it will use the primary user on the first xiwi-enabled chroot found and launch
the chroot_app in a window.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -F          Launch the chroot_app full-screen.
    -T          Launch the chroot_app in a tab.
    -f          Prevent xiwi from quitting automatically. (see NOTE below)

NOTE:
xiwi will normally close when the application returns. Some gui applications
fork before or during normal operation, which can confuse xiwi and cause it to
quit prematurely. If your application does not have a parameter that prevents
it from forking, and crouton is unable to automatically detect the fork, you can
use -f to prevent xiwi from quitting automatically.
xiwi will quit if you close the Chromium OS window when nothing is displayed.
  
You can cycle through multiple windows inside the application
via Ctrl-Alt-Tab/Ctrl-Alt-Shift-Tab, or close them via Ctrl-Alt-Shift-Escape.
If the chroot_app begins with 'start' but you still want to
use the default window manager, specify the full path of the application.
```

Note the first option, '-b', is probably what you want to use -

> `    -b          Fork and run the specified command silently in the background.`

So, to start `guake` (my favorite terminal) in a tab for instance, just use: sudo startxiwi -bT guake`

You can start/run other 'chroot apps' in a similar fashion from the same or different chroots.

Hope this helps,
-**DennisL**
