### ISSUE TITLE
dpkg: error processing archive /var/cache/apt/archives/linux-libc-dev_3.13.0-88.135_armhf.deb (--unpack):

### ISSUE THREAD

**Issue by JonahWong** [dnschneid/crouton#2631]
```
name: xfce
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xfce...
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: armhf
xmethod: xiwi
targets: xfce,touch,xiwi,audio,chrome-beta
host: version 8459.0.0 (Official Build) dev-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jun 15 18:53:41 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xfce as another instance is using it.
```

When I tried to update the chroot using sudo sh ~/Downloads/crouton -u -n xfce, it give me the following error:

dpkg: error processing archive /var/cache/apt/archives/linux-libc-dev_3.13.0-88.135_armhf.deb (--unpack):
 cannot get security labeling handle: No such file or directory
Errors were encountered while processing:
 /var/cache/apt/archives/linux-libc-dev_3.13.0-88.135_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.

If it helps, this happened after I updated my Asus Flip to v53 of dev channel. All is fine before doing this.

**Comment by spafindoople** [comment]
Try to run this command: 
`sudo dpkg --force-all -i /var/cache/apt/archives/linux-libc-dev_3.13.0-88.135_armhf.deb`
I had this error once and this solution worked for me.

Hope I helped,

**~Spafindoople**
