### ISSUE TITLE
Can't switch runtime the os

### ISSUE THREAD

**Issue by ReactiioN1337** [dnschneid/crouton#2637]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

chronos@localhost / $ sudo edit-chroot -all
name: wily
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/wily...
crouton: version 1-20160518095657~master:fd37bb79
release: wily
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8172.47.0 (Official Build) stable-channel nyan_big 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jun 1 22:45:23 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: no
Not unmounting /mnt/stateful_partition/crouton/chroots/wily as another instance is using it.
#### Please describe your issue:

When I'm booting xfce4, the desktop environment gets loaded. But when I switch back to chrome os and then back to xfce, the desktop environment doesn't get loaded.
#### If known, describe the steps to reproduce the issue:

Load xfce with sudo startxfce4
Swtich back to chrome os
Switch back to xfce4

**Comment by DennisLfromGA** [comment]
@ReactiioN1337,

The [nyan based boards (Tegra K1) are not yet freonized](https://github.com/dnschneid/crouton/issues/2380#issuecomment-180444052) according to one of our distinguished developers so they may have some unique problems in crouton it seems.

I'm afraid I don't know what might be causing your display issues, I can sometimes overcome a blank/black screen by toggling the 'full screen' key but my system is much different than yours.
Hopefully, someone with experience or knowledge about your system will pop in here and help out.

I don't know if installing the 'xiwi' target will help you but it might be worth a try. It seems there are problems with it by looking at this issue: [sudo startxfce4 fails on Tegra K1 HP G3 #1937](https://github.com/dnschneid/crouton/issues/1937).
If you do decide to try 'xiwi', you may have to apply [this fix](https://github.com/dnschneid/crouton/issues/1976#issuecomment-126783866).

*Hope this helps,*
-**DennisL**
