### ISSUE TITLE
Can't get Search to work as Super_L

### ISSUE THREAD

**Issue by mjwhitta** [dnschneid/crouton#2639]
``` bash
$ sudo edit-chroot -all
name: sid
encrypted: no
crouton: version 1-20160620130246~master:c39102d9
release: sid
architecture: amd64
xmethod: xiwi
targets: lxde,keyboard,cli-extra,xiwi,extension
host: version 8350.31.0 (Official Build) beta-channel peppy
kernel: Linux greenarrow 3.8.11 #1 SMP Tue Jun 14 21:57:05 PDT 2016 x86_64 GNU/Linux
freon: yes
```
#### Please describe your issue:

I'm not sure what changed but I noticed the other day that the Search button no longer worked as `Super_L`. I did some searching and found [this wiki](https://github.com/dnschneid/crouton/wiki/Keyboard#super_l-key). I then installed the `keyboard` target:

``` bash
$ sudo bash crouton -u -p /media/removable/64GB_USB/crouton -n sid -t keyboard
```

This caused some permissions issues when starting my chroot. Most likely because I have `umask 077` in my bashrc, and I think that gets persisted into the chroot so the updates from the previous command get installed with no group or other permissions. The following command fixed my issue:

``` bash
$ sudo bash enter-chroot -x chmod -R go+rX /usr/share/X11/
```

Running `umask 022` before `crouton` updates also seems to fix the problem. It might be worth adding a `umask 022` at the beginning of `crouton` but this likely isn't critical.

After I got that worked out I used the `xmodmap` command inside the chroot:

``` bash
$ xmodmap -e "keycode 133 = Super_L"
```

Unfortunately this didn't fix my problem. I still can't get the Search button to behave as `Super_L` as before. Any help would be greatly appreciated.

**Comment by drinkcat** [comment]
Looks like a Chromium OS bug, key input appears to be passed to the window.

**Comment by drinkcat** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=655748 . Feel free to star, refrain from commenting unless you have valuable information,

**Comment by dnschneid** [comment]
Derp, it got wontfix'd.  What happens if you change the config for the search key in Chromium OS's settings?

**Comment by drinkcat** [comment]
Well, nowadays you can remap Search to a lot of things... "Disabled" won't work (xiwi does not get a key symbol, neither will "Caps Lock" (it's still captured by Chrome OS)). I'm not too sure what you could do with Backspace/Esc.

That leave Ctrl/Alt...

**Comment by mjwhitta** [comment]
Sorry for the late response. I guess if this got wontfix'd, then this issue is closable? Should it be labeled as wontfix or maybe just left open? I'll close it for now and someone can reopen if deemed necessary.

**Comment by burgerga** [comment]
@drinkcat why is "Caps Lock" captured by Chrome OS? I am tempted to open a separate issue for that, since it breaks my colemak keyboard layout...
