### ISSUE TITLE
Installing Virtualbox - wrong kernel version after building headers?

### ISSUE THREAD

**Issue by Pitey** [dnschneid/crouton#2642]
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,xfce,touch,extension
host: version 8459.0.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 3.18.0-12438-gfa5c4dd #1 SMP PREEMPT Wed Jun 15 19:01:06 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

I'm trying to install Virtualbox on my Acer Chromebook R11
```
$ uname -r
3.18.0-12438-gfa5c4dd
```

i cloned the source for 3.18 and followed the steps in the Build kernel headers and install Virtualbox wiki page. 
everything went successful, but the kernel and image files are named like this:
```
linux-headers-3.18.0-12453-g22f7042-dirty_3.18.0-12453-g22f7042-dirty-10.00.Custom_amd64.deb
linux-image-3.18.0-12453-g22f7042-dirty_3.18.0-12453-g22f7042-dirty-10.00.Custom_amd64.deb
```

So, the version appendix is 12453 instead of 12438

I think this leads to the following error, when trying to install the virtualbox modules with modprobe:
```
$ modprobe vboxdrv
bash: modprobe: command not found
(trusty)pitey@localhost:~/kernel$ sudo modprobe vboxdrv
modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/3.18.0-12438-gfa5c4dd/modules.builtin.bin'
modprobe: FATAL: Module vboxdrv not found.
```

Running /etc/init.d/vboxdrv setup gives the following:
```
$ sudo /etc/init.d/vboxdrv setup
Stopping VirtualBox kernel modules ...done.
Uninstalling old VirtualBox DKMS kernel modules ...done.
Trying to register the VirtualBox kernel modules using DKMSError! Your kernel headers for kernel 3.18.0-12438-gfa5c4dd cannot be found.
Please install the linux-headers-3.18.0-12438-gfa5c4dd package,
or use the --kernelsourcedir option to tell DKMS where it's located
 ...failed!
  (Failed, trying without DKMS)
Recompiling VirtualBox kernel modules ...failed!
  (Look at /var/log/vbox-install.log to find out what went wrong)
(trusty)pitey@localhost:~/kernel$ 

```

My understanding is, that the kernel headers and modules I build are newer than the actual kernel in my chromebook. Can i point to the correct version number when building? or do I have to build the complete kernel from source?

**Comment by spafindoople** [comment]
There is a [link](https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)) on the wiki which explains this.

**~Spafindoople**

**Comment by Pitey** [comment]
Yes, I did that, it explians how to build the kernel headers and and the image. Everything works fine like it's explained in the wiki page.
My problem is, that the new kernel won't activate. After rebooting/loging off and on, uname -r still shows the old kernel version. 
and the vboxdrv-setup tries to access the modules folder of the old version.

**Comment by DennisLfromGA** [comment]
@Pitey,

Take a look at this thread and https://github.com/dnschneid/crouton/issues/2544#issuecomment-216020041

It might give you some pointers.

Hope this helps,
-**DennisL**

**Comment by divx118** [comment]
@Pitey I still hadn't the time to look at it. It should be somehow possible to clone or checkout the chromeos git at the right point so the kernel versions match. This seems to be only an issue on 3.18.0 chromeos kernels they post fix the main version. Older kernel versions don't do this, they just stick to the main version. You cannot change the kernel version when building the headers. The version comes from the source.
BTW with the wiki guide you won't get a new kernel for your chromeos to use. It builds kernel-headers so you can use those to build modules. So the kernel version of your chromebook won't change when installing the build deb packages.
 
Maybe @drinkcat would know more if he has some spare time :).

**Comment by Pitey** [comment]
Thanks for the tips.
There was a ChromeOS update yesterday and they updated the kernel, i'm cloning the new kernel version right now. Maybe the version is now the same.

**Comment by Pitey** [comment]
Ok.. same problem again ;)
chromeOS kernel is now version 3.18.0-12480 and the builded headers and image are version -12520

i tried make-kpkg with -revision command, but it always builds the newest version.

**Comment by wildbill12** [comment]
echoing that I am having the same issue with a HP chromebook 13

The headers and image version I built are actually 3.18.0-12563 and uname -r gives me a kernel version of 3.18.0-11125-g013294a

So I guess we just wait until chromeOS updates to a kernel version that matches the headers I've built? 12563?  Maybe pitey can share his packages with if it makes it to -12520 sooner? :)

Hope my chromebook's kernel catches up soon - there is a critical windows-only program I really need to use.

Thanks for the help

**Comment by araisovich** [comment]
I had to do something like this with git; this is part of an update to divx118's wiki page I'd like to make at some point, if I can get my headers to install:

> If the version from the uname command above does not match what is displayed, and is indeed a later version, then one can do the following to download an earlier version:
> 
> ```
> $ git reset --hard origin/chromeos-3.18
> $ git checkout HEAD~[number of commits prior to current version]
> $ ./chromeos/scripts/prepareconfig chromeos-intel-pineview
> $ make oldconfig
> $ make kernelrelease
> ```
> 

where I played with the number of commits, after having cloned down the most recent commit.  When I fetched down 12480 today (7/8/2016), I had to use HEAD~128, I believe.

Note that building this will append a "-dirty" to the kernel version name, because you're using a version of the code earlier in the repository.  After installation, I was able to just put in a symlink in /lib/modules that pointed to the installation directory (e.g.; 3.18.0-12480_gb1b3e14 points to 3.18.0-12480_gb1b3e14-dirty).

Executing /sbin/rcvboxdrv setup compiled the kernel modules, but trying to load them via modprobe gives me the following error:

```
modprobe: ERROR: could not insert 'vboxdrv': Exec format error
```

Maybe someone could give me a hand on this?

**Comment by araisovich** [comment]
Well, I'm not 100% sure why, after issuing the ```make-dpkg``` command to build the installation modules, and then installing header and image packages, the modules were giving me the ```Exec formt error```. nd However, after installation I went back to the kernel directory and did:

```
sudo make modules
sudo make modules_install
```

and then reran:

```
/sbin/rcvboxdrv setup
```

And finally checked to see if the Virtualbox modules were loaded, and they were!  I'm unsure why the virtualbox kernel modules weren't building correctly after just installing the .deb packanywayages, but this seemed to work for me, anyway.  Hope it helps someone else.

**Comment by araisovich** [comment]
So what I finally was able to replicate for myself, end-to-end, was basically divx118's method to build the headers and packages using make-kpkg, with a slight twist.  Edit the file scripts/setlocalversion, search for the text "-dirty", and remark out the conditional statements in which you find the reference; there should be a case statement and an if statement.  Finish building the packages using make-kpkg, and the name of the .deb package and the installed name under /lib/modules will not have "-dirty" in them.  Building and installing the vboxdrv modules with VirtualBox should match the installed kernel exactly and work.

I updated the wiki page with these instructions, and the instructions on getting prior versions of the kernel s

**Comment by araisovich** [comment]
So what I finally was able to replicate for myself, end-to-end, was basically divx118's method to build the headers and packages using make-kpkg, with a slight twist.  Edit the file scripts/setlocalversion, search for the text "-dirty", and remark out the conditional statements in which you find the reference; there should be a case statement and an if statement.  Finish building the packages using make-kpkg, and the name of the .deb package and the installed name under /lib/modules will not have "-dirty" in them.  Building and installing the vboxdrv modules with VirtualBox should match the installed kernel exactly and work.

I updated the wiki page with these instructions, and the instructions on getting prior versions of the kernel source.

**Comment by divx118** [comment]
@araisovich Thanks, I still didn't find the time to take a look at this issue. Glad you did the work for me :)

**Comment by Pitey** [comment]
@araisovich Thank you so much! It works finally! :)
I repeated all the steps in the wiki including your additions, i had to use HEAD~27. After disabling module locking with @divx118 script, I could install virtualbox without errors and the virtual machine is working!

**Comment by wildbill12** [comment]
Thanks so much for your work!

I have one question - is there any better way than trial and error in finding the right HEAD~[#]?  I have went from 1 to 71 and haven't found the correct kernel version

uname -r tells me I have 3.18.0-12587-g724983b
The closest I've got is HEAD~40 which was 3.18.0-12587-g724983b

I tried this version but it virtualbox wouldn't install.

I'm perfectly happy to keep trying numbers until I hit on the right one since I really do need this to work, just wondering if there is a better way.

Thanks

**Comment by araisovich** [comment]
Hi, @Pitey.  No problem.  Glad I could help.  I was just looking to expose myself to using git, mostly.

**Comment by araisovich** [comment]
HI, @wildbill12 .  Strangely enough, I'm much in the same boat.  Can you tell me what model of Chromebook you happen to be using?  I'm using an Acer R11, which is one of the first to get the Android App Store modifications, so I'm running on the dev channel, not beta or stable.  So, I'm currently in the same boat as yours.

I'm still by no means an expert with git, so perhaps our version exists somewhere, somehow, in the repository.  If I happen across the solution, I'll definitely post back here.

In the meantime, you were asking for a "better way."  I won't say that my shell scripting ability is stellar, but I've written a shell script, git-rewind that I'll attach here.  It does a half-hearted attempt at a binary search down through the repository for your running kernel version.  I haven't tested it extensively, but I was using it in the following fashion:

- become root; e.g., sudo su - root
- position yourself into the top level of the cloned kernel directory
- /path/to/git-rewind

It accepts a couple of optional parameters:

- search interval, the number by which you start hopping back through the git repository backwards by HEAD on each iteration, until you either hit the correct version or get far enough back that you're before your running version.  Default 50
- sequential search threshold, used to determine when to stop trying to binary search and just brute force search.  Default 5

I'm guessing this can also be executed as "sudo /path/to/git-rewind", but I haven't tried it.  Of course, being in a similar boat as you, I currently get the "not found" message, same as you.

**Comment by wildbill12** [comment]
Hi @araisovich ,

Different Chromebook but we're in the same boat - I'm using the HP Chromebook 13 on the dev channel.

Thanks for the script!  It's working great, but sadly giving me the "not found" message. I was going to whip up one myself since the trial and error method was just too much work.  

Maybe we'll get lucky the next time we get an update. I imagine I could drop down to the beta or stable channel and give it a try as I won't be getting the play store anytime soon.

Regardless - thanks again for all the work on this!

**Comment by anonby** [comment]
Hi @wildbill12 did you ever get this working?  i'm having the exact same issue...
