### ISSUE TITLE
can't startunity with a UID other than 1000 ?

### ISSUE THREAD

**Issue by TimFH** [dnschneid/crouton#2643]
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160620130246~master:c39102d9
release: trusty
architecture: amd64
xmethod: xorg
targets: core,extension,audio,chromium,x11,xorg,gtk-extra,touch,unity,unity-desktop
host: version 8172.56.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Jun 16 13:49:01 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
chronos@localhost / $
```

#### Please describe your issue:
Created a new user with UID=501 in all the same groups as chronos (UID=1000) so I could use an external disk from a Mac with Ubuntu on a Chromebook without any permissions issues, but I can't get the xserver to start when logged in to the chroot as this new user, apparently because of some permission problem that must be related to the change in UID since the new user has been given the same group permissions. The specific error from the xserver is:

Loading extension GLX
Failed to open connection to "system" message bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Failed to open connection to "system" message bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Unable to set master
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 

#### If known, describe the steps to reproduce the issue:
Create a new user with useradd and some UID other than 1000, enter-chroot -u new_user and type "startunity". In principle it should  also be possible to startunity as chronos and then do a "Switch User" from the gear-menu at the upper right of the screen, but that seems not to work in crouton since "logout" exits the server and pops you back in the shell rather than bringing up lightdm for a new login. 

Any and all help deeply appreciated, like crouton itself!

**Comment by DennisLfromGA** [comment]
@TimFH,

There was activity on this topic in issue #908 a while back, see -

- "I had intended to make crouton multi-user safe from the start..." https://github.com/dnschneid/crouton/issues/908#issuecomment-48064931
- "Running sudo usermod -a -G video,sudo,plugdev,audio u1100..." https://github.com/dnschneid/crouton/issues/908#issuecomment-47962560

*'crouton's author* created a [multiuser branch](https://github.com/dnschneid/crouton/tree/multiuser) which has [several proposed changes](https://github.com/dnschneid/crouton/compare/multiuser) but it hasn't been reviewed or merged as yet - AFAIK.

Hope this helps,
-**DennisL**

**Comment by altoning** [comment]
I would love to see the [multiuser branch](https://github.com/dnschneid/crouton/tree/multiuser) merged into the master.

Not sure when I'll get around to testing the multi-user branch but it is 2 years old.

For now my manual workaround is to create a symbolic link to the second user's home directory as follows:

```
sudo mv /home/DEFAULTUSER /home/user1

sudo useradd -m user2
sudo passwd user2
sudo adduser user2 sudo
sudo adduser user2 audio
sudo adduser user2 video
sudo adduser user2 plugdev
sudo adduser user2 input
sudo adduser user2 lpadmin

sudo chown -R 1000:1000 /home/user2

sudo ln -s /home/user2 /home/DEFAULTUSER
```

**Comment by DennisLfromGA** [comment]
@altoning - Thanx for that workaround.
