### ISSUE TITLE
Update error (trying to install xiwi)

### ISSUE THREAD

**Issue by qtv** [dnschneid/crouton#2645]
Closed
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue:
Running  sudo sh -e ~/Downloads/crouton -u -t xiwi -n trusty and it has a problem updating here: 

The following NEW packages will be installed:
  libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386
  linux-libc-dev:i386
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 2517 kB of archives.
After this operation, 13.5 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libspeex1:i386 libspeex-dev:i386 libspeexdsp-dev:i386
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.

Has same issue using -r trusty instead of -n.
I have updated crouton before with no issue but now even removing -t xiwi makes this same error happen 
Full command : http://pastebin.com/5Y868uA1

**Comment by matty312** [comment]
Try Forcing it:
sudo sh -e ~/Downloads/crouton -u -n trusty --force-yes

**Comment by DennisLfromGA** [comment]
@qtv,

I found a couple of possible solutions by googling, I'd try the simplest one first, which is:

`sudo apt-key update; sudo apt-get update`

If you're still getting the 'GPG error's, then try this:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys`

And then add the hexadecimal numbers to the command, like:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32`

*Hope this helps,*
-**DennisL**

**Comment by qtv** [comment]
Thank you DennisL, the second solutions worked great.

**Comment by DennisLfromGA** [comment]
*Cool, cool, cool!*
( You can probably close this issue if you like. )
