### ISSUE TITLE
Chroot file size and xiwi crashes

### ISSUE THREAD

**Issue by TsinghuaMike** [dnschneid/crouton#2647]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160620130246~master:c39102d9
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,xorg,xiwi,touch
host: version 8172.60.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jun 22 23:08:58 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
#### Please describe your issue:

Mine launches and then crashes:

Connected to extension, launched crouton in a window.
Error: target STRING not available
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup
Hangup

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
#### If known, describe the steps to reproduce the issue:

My chroot is, I believe, around 5 gb. I like to launch the desktop in a window, but it seems possible that file size might be preventing xiwi from functioning. Here is a conversation about it on reddit:

https://www.reddit.com/r/Crouton/comments/4p84je/i_think_i_broke_my_crouton_by_installing_xiwi/

For others with this problem, we are able to launch individual programs with the tab. That is why I suspect it has something to do with the capacity of the chrome extension.

![newissue](https://cloud.githubusercontent.com/assets/11172428/16354428/53fb3956-3a59-11e6-9b93-32eae0f40a18.png)

**Comment by DennisLfromGA** [comment]
@TsinghuaMike,

Does it *always* crash immediately after it's 'connected' and never actually launches the desktop?

I don't think it's related to the size of your chroot; I guess it could be the combination of the chroot size and how much free space you have left though. How much free space do you have on your stateful partition I wonder?

I have a 5.6GB 'trusty' chroot that I most often run in a tab and haven't run into this issue, consistently at least. Mine will *occasionally* abort before it 'connects' to the extension but it will usually work on the next attempt, or the next one. I have just 1.7GB free space left on the partition which is not a whole lot but my chroot still runs just fine.

-**DennisL**

**P.S.** *Thanx for the reddit link, it was interesting.*

**Comment by TsinghuaMike** [comment]
Hey @DennisLfromGA ,

I'm working on piecing together this puzzle, because all my chroots eventually run into problems. I have developed the habit of saving them incrementally.

I made a series of updates to my chroot, and over the past few days my chroot went from 

- launching  in xiwi, but having display issues before loading up anyway and running smoothly, 

 to

-  launching and then crashing, but still allowing for individual app launches via: `sudo startxiwi -b [application name]`,  

and now this (doesn't even launch, individual apps don't launch either):

```
Loading extension GLX
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
^C
Session terminated, terminating shell.../usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: unexpected signal 2
 ...terminated.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

My last update to my chroot came from the process of setting up a 1280X850 display setting, and saving a txt file.

xorg always works. I have a 16 GB ram and almost 30 GB of storage available.

I'm not sure I'm on the right track with this line of thinking, but if I'm right, your chroot is right around the size that would start to cause some problems.

![screenshot 2016-06-26 at 12 17 18 pm](https://cloud.githubusercontent.com/assets/11172428/16360465/0cb1e842-3b2b-11e6-952f-4c8701600a81.png)

**Comment by DennisLfromGA** [comment]
@TsinghuaMike,

Sorry it's failing on you, it's hard to tell what might be going on and if it's related to the chroot size.
I haven't seen anyone else report problems with large chroots though. 

At one time, I had a chroot that was over 11GB due to 3 VMs setup in it. It always worked for me however I believe I pretty much used 'xorg' exclusively.

Since you have a backup ready to go, you might try restoring it to external media and try to run it from there to see if you get the same behavior. It might give us another point of reference.

-**DennisL**

**Comment by TsinghuaMike** [comment]
It's actually too late for that. I deleted it and restored a backup. But I think we can try and get a conversation going on this on reddit if it is more active.

We can disprove my hypothesis if someone shows up with a 7+ GB chroot and it runs xiwi consistently and smoothly. I'll try the external media idea next time. 

PS. Interesting to get an idea of how you go about solving these things.

Thanks again @DennisLfromGA

**Comment by DennisLfromGA** [comment]
@TsinghuaMike - *It's ***never** too late to do a backup* :)

**Comment by TsinghuaMike** [comment]
Seems to not be related to file size after all. I can confirm from restoring chroots at various points that every time I perform a particular system update it ruins xiwi functionality. Which update exactly? It's one of these (see images attached):

It doesn't matter if I update through the shell on chrome os, or from inside the chroot. Either way, it causes problems. 

Now that I know it comes from one of these updates I can update a few at a time and eliminate some candidates.

![workspace 1_013](https://cloud.githubusercontent.com/assets/11172428/16644309/9ee42f04-43e1-11e6-9bbc-827933726d65.png)
![workspace 1_012](https://cloud.githubusercontent.com/assets/11172428/16644308/9ee39fe4-43e1-11e6-904d-afa24ef9f5d6.png)

**Comment by DennisLfromGA** [comment]
Good sleuthing, you'll get to the bottom of this yet. ;)
Hopefully, we'll all learn something from this eventually.

I just upgraded my Dell to 256GB so space won't be a problem for some time to come.
```
SOURCE                 FSTYPE  SIZE    USED   AVAIL   USE%  TARGET
/dev/dm-0              ext2    1.7G    1.1G   587.5M  66%   /
/dev/sda1              ext4    58.8G   2.2G   53.6G   4%    /mnt/stateful_partition
/dev/sda7              ext4    65.8G   6G     56.5G   9%    /var/mint18
/dev/sda8              ext4    11.5M   24K    11.1M   0%    /usr/share/oem
/dev/sda13             ext4    105.6G  59.6M  100.2G  0%    /var/crouton
```
I don't have my chroots re-installed quite yet as you can see.
