### ISSUE TITLE
update breaking in xenial [bug]

### ISSUE THREAD

**Issue by DanHolli123** [dnschneid/crouton#2649]
```
1 Ubuntu
```
#### The problem
after updating to xenial from precise 'sudo startunity' only starts nautilus
update script is also broken trying to install unity-2d and the old kde desktop pakage

#### To reproduce
install chroot with `-t unity,kde,xorg,xiwi,audio,touch,extension` added to the installer script
possibly install KDE5
update from precise to xenial
update all packages
set default xserver as xorg
then start unity with `sudo startunity`

**Comment by divx118** [comment]
Duplicate #2476 #2489 #2596

**Comment by DanHolli123** [comment]
but it first errors with the kde desktop update

**Comment by DanHolli123** [comment]
which is different from the other three

**Comment by drinkcat** [comment]
@smibarber : You fixed the kde issue, right?

**Comment by smibarber** [comment]
Will be fixed with #2817

**Comment by dnschneid** [comment]
It was fixed !

**Comment by DanHolli123** [comment]
thank you
