### ISSUE TITLE
Asus Flipbook v53 update/install issues

### ISSUE THREAD

**Issue by rudedog830** [dnschneid/crouton#2652]
```
Please paste the output of the following command here: sudo edit-chroot -all

chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
Creating hwaudio group with GID 18...
Password: 
```

#### Please describe your issue:

I attempted to update Crouton to latest version after my Asus Flipbook was upgraded to development version 53.  When I attempted to update I receive a password prompt and I have no indication what the prompt is for.  All passwords I've tried do not work.

#### If known, describe the steps to reproduce the issue:

Here is the output of the install script:

chronos@localhost / $ sudo sh ~/Downloads/crouton -u
/usr/local/chroots/precise already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Creating hwaudio group with GID 18...
Password: 
su: Authentication failure

**Comment by DennisLfromGA** [comment]
@rudedog830,

I've attempted to answer your question on [Crouton Central](https://groups.google.com/d/msg/crouton-central/uZWmDdI8OSY/r71J92YwBQAJ) where you first brought it up.

Please try my suggestions there and if they don't work, you can pursue help from others if you wish.

I would recommend that you stick with just one forum to get your problem solved however, it's frustrating to those of us that find the same questions popping up in different places only to find it's the same OP.

-**DennisL**

**Comment by drinkcat** [comment]
See #2655.
