### ISSUE TITLE
Kali Sana login not wokring

### ISSUE THREAD

**Issue by Elowan** [dnschneid/crouton#2653]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: sana
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sana...
crouton: version 1-20160620130246~master:c39102d9
release: sana
architecture: armhf
xmethod: xiwi
targets: gnome,xiwi
host: version 8172.56.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Thu Jun 16 14:45:49 PDT 2016 armv7l GNU/Linux
freon: yes
```

#### Please describe your issue:
"Oh no! Someting is wrong" on login-screen:chronos@localhost / $ sudo startxiwi -n sana -F gnome-session
Entering /mnt/stateful_partition/crouton/chroots/sana...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.17.2
Release Date: 2015-06-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Jun 16 14:45:49 PDT 2016 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=93a8c50a-bc62-4b44-b1d0-2999019148e3/PARTNROFF=1 hashtree=PARTUUID=93a8c50a-bc62-4b44-b1d0-2999019148e3/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=138be242822890dcac1cc888ce9409da6e009225 salt=c326d30f817d2c38a3d5466478925e5b8decb69b2c407dc0d51b19c5d66903a4" noinitrd vt.global_cursor_default=0 kern_guid=93a8c50a-bc62-4b44-b1d0-2999019148e3  
Build Date: 01 July 2015  05:24:31PM
xorg-server 2:1.17.2-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.2.log", Time: Sun Jun 26 18:44:00 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160620130246~master:c39102d9
release: sana
architecture: armhf
xmethod: xiwi
targets: gnome,xiwi
host: version 8172.56.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Thu Jun 16 14:45:49 PDT 2016 armv7l GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Error: target STRING not available
gnome-session-is-accelerated: No hardware 3D support.
gnome-session-check-accelerated: Helper exited with code 256
gnome-session-is-accelerated: No hardware 3D support.
gnome-session-check-accelerated: Helper exited with code 256

** (process:29588): WARNING **: software acceleration check failed: Child process exited with code 1

** (gnome-session-quit:29992): WARNING **: Failed to call logout: The name org.gnome.SessionManager was not provided by any .service files
socket_client_read_frame_header: Connection close from WebSocket client.
^C
Session terminated, terminating shell.../usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup

``

#### If known, describe the steps to reproduce the issue:

sudo startxiwi -n sana -F gnome-session brings up the issue...

**Comment by drinkcat** [comment]
sana is apparently not supported anymore.
