### ISSUE TITLE
Can't open /home/chronos/user/Downloads/crouton

### ISSUE THREAD

**Issue by Aarca** [dnschneid/crouton#2656]
I'm typing in "sudo sh -e ~/Downloads/crouton -t xfce" after typing in shell and I'm getting that error. I want to download Linux so I can play Undertale, but it doesn't seem to be working. Help?

**Comment by DennisLfromGA** [comment]
@Aarca - 

Please make sure you've actually downloaded 'crouton' and placed it in `~/Downloads`
You can get it from here - https://goo.gl/fd3zc

-**DennisL**
