### ISSUE TITLE
Cannot start Xorg server. Dev channel  ARM processor HP Chromebook 14-x013dx

### ISSUE THREAD

**Issue by panaman26** [dnschneid/crouton#2658]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160627183059~master:e3c0a690
release: precise
architecture: armhf
xmethod: xiwi
targets: audio,chrome-dev,cli-extra,core,lxde,xfce,gtk-extra,xiwi,keyboard,extension
host: version 8481.0.0 (Official Build) dev-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jun 21 02:58:29 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

#### Please describe your issue:

Not sure what I am doing wrong, but I am pretty sure being on the dev channel is not helping. Every time I try to start crouton, the xorg server craps out. I am not sure what xiwi is or freon. I would mainly like to be able to start up a Linux desktop to mess around with. I have looked around on the website here, but haven't found the fix for my particular problem. I also am running on a ARM processor and I know this complicates running Linux. I have tried using both XFCE4 and LXDE environments and both Trusty and Precise versions of Ubuntu to no avail. If anyone can clear up this problem for me, I would be grateful. 

#### If known, describe the steps to reproduce the issue:
chronos@localhost ~/Downloads $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-68-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Tue Jun 21 02:58:29 PDT 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=8b25ffb9-cffa-cd4d-9a79-53f2ec45648f/PARTNROFF=1 hashtree=PARTUUID=8b25ffb9-cffa-cd4d-9a79-53f2ec45648f/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=0517f62f68d0c7a42066489903134e033cae0b31 salt=3268f61f4b5ebf218d4060d371edf00fb2e2575658fec41f3697f289939cff4e" noinitrd vt.global_cursor_default=0 kern_guid=8b25ffb9-cffa-cd4d-9a79-53f2ec45648f  
Build Date: 12 February 2015  02:54:30PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jun 30 01:44:00 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160627183059~master:e3c0a690
release: precise
architecture: armhf
xmethod: xiwi
targets: audio,chrome-dev,cli-extra,core,lxde,xfce,gtk-extra,xiwi,keyboard,extension
host: version 8481.0.0 (Official Build) dev-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jun 21 02:58:29 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: no
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
 ddxSigGiveUp: Closing log
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/precise...

**Comment by divx118** [comment]
> Unable to start display, make sure the crouton extension is installed
> and enabled, and up to date. (download from http://goo.gl/OVQOEt)

Did you install the chromeos extension from http://goo.gl/OVQOEt ? If not then install it and try again.

**Comment by panaman26** [comment]
Yes, Crouton extension is installed, updated, and re-updated. When I try to start the Linux session it shows up on the extension as precise. It says connection established and then connection lost, meanwhile the Linux output says cannot connect.

**Comment by divx118** [comment]
@panaman26 Ok, just wanted to be sure nothing obvious was the cause.

**Comment by panaman26** [comment]
I'll probably just revert back to table channel because I think this will solve the problem. Most of the features of dev channel will probably not work any due to the ARM processor.
