### ISSUE TITLE
Problems with downloading Linux for Chromebook

### ISSUE THREAD

**Issue by shomalzadeh** [dnschneid/crouton#2662]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
#### Please describe your issue:

Issues downloading files for enabling Ubunto on my Chromebook consistently hits error (please see screenshot)
#### If known, describe the steps to reproduce the issue:

Trying to download files using this link  https://github.com/dnschneid/crouton

![screenshot 2016-06-03 at 14 41 12](https://cloud.githubusercontent.com/assets/20264556/16544604/5d6814cc-4121-11e6-8b4e-9a18f3a6e2f8.png)

**Comment by DennisLfromGA** [comment]
@shomalzadeh - I think it might be a temporary network glitch, mine works fine at the moment.
