### ISSUE TITLE
have a problem in npm when I install in my terminal.

### ISSUE THREAD

**Issue by Guhananthan** [dnschneid/crouton#2663]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Screen Shot 2016-07-03 at 9.57.14 PM
<img width="732" alt="screen shot 2016-07-03 at 9 57 14 pm" src="https://cloud.githubusercontent.com/assets/18332319/16549898/9c6d5ae0-4169-11e6-9b9f-b741375de0e5.png">
#### Please describe your issue:
Have a problem in installation . Kindly need help very badly
#### If known, describe the steps to reproduce the issue:
Please describe the steps and provide the exact solution ASAP.

**Comment by divx118** [comment]
You seem to be posting on the wrong issue tracker.  Please close this issue if it indeed has nothing to do with running a chroot on a chromebook. Thanks

Seems to me it is a #262 .
