### ISSUE TITLE
xiwi window blanked out when returning from another window

### ISSUE THREAD

**Issue by mathnic** [dnschneid/crouton#2664]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: mySid
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/mySid...
crouton: version 1-20160627183059~master:e3c0a690
release: sid
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi,xorg,keyboard
host: version 8172.60.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jun 22 22:31:31 PDT 2016 armv7l GNU/Linux
freon: yes
```
#### Please describe your issue:

"sudo startxfce4" works fine and gets xiwi window up and running. However, any time I switch to another window and then switching back to the xiwi window, it is now just a black window. This chroot has been running fine for a long time until now. 
In the original terminal window where I launch "sudo startxfce4", I get this type of output:

Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
Error: target STRING not available
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
gpg-agent[23384]: WARNING: "--write-env-file" is an obsolete option - it has no effect

(xfce4-session:23297): xfce4-session-WARNING **: gpg-agent returned no PID in the variables
gpg-agent[23393]: gpg-agent (GnuPG) 2.1.11 started
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
shared memfd open() failed: Function not implemented

(xfsettingsd:23449): xfsettingsd-WARNING **: Unknown mode '1100x716 @ 59.7' for output default, aborting.
Xlib:  extension "GLX" missing on display ":1.0".
process 23480: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../dbus/dbus-message.c line 1363.
This is normally a bug in some application using the D-Bus library.
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented

(xfwm4:23406): xfwm4-WARNING **: output size (532x716) and logical screen size (1366x768) do not match
process 23480: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../dbus/dbus-message.c line 1363.

**Comment by mathnic** [comment]
More precisely, I can actually switch between xiwi window and others for a while. Eventually the xiwi window does blank out.

**Comment by mathnic** [comment]
Not just xiwi is broken, also xorg target behaves the same. After 15-20 minutes, display goes blank.
Current status of crouton is completely useless to me so I'm pitching my chromebook for now. Too bad since it was running well for such a long time, til the last round of chrome os updates...perhaps Android is out to kill the real linux systems.
If i can be of any help to pinpoint the problem, I'd be happy to do so.

**Comment by DennisLfromGA** [comment]
I have run into this on occasion and can bring the screen back using the <kbd>full screen</kbd> and/or <kbd>switch window</kbd> keys.
![fs-sw](https://cloud.githubusercontent.com/assets/3418772/16673420/fe9cc5b0-447b-11e6-8e2e-0a2ffa747bde.jpg)

**Comment by mathnic** [comment]
I believe I've tried just about all keys + clicks that there is;) But I'll try again to be sure. Which target should I use when I try, xiwi or xorg?
Thanks!

**Comment by DennisLfromGA** [comment]
I (currently) prefer `lxde-desktop`, it's working for me on my lulu with 'trusty using both 'xiwi' and 'xorg'.

**Comment by mathnic** [comment]
So I tried again in xiwi mode, sudo startxfce4 with a fresh update of the chroot. Screen still blacks out. The full screen key works but it just changes the size format of the blacked out window. 
It feels a bit like some form of screensaver issue since it seems to take some inactivity for this to happen. But as I said it worked fine til now. Any reason to think it's related to debian/Sid?

**Comment by DennisLfromGA** [comment]
I haven't used debian/sid in quite a while, sorry.
Did you check to see if a screensaver is running? (`ps -ef|grep screen`)

**Comment by mathnic** [comment]
I see plenty of processes for chrome like this;

/opt/google/chrome/chrome --type=renderer --enable-logging --log-level=1 --use-gl=egl --vmodule=screen_locker=2....

**Comment by DennisLfromGA** [comment]
@mathnic - That doesn't look like a screensaver to me, maybe there isn't one running.

**Comment by mathnic** [comment]
Yeah didn't think so.  Anyways, as said on the wiki, chroots are cheap so I've retired this one.
And I'm having another go with a shiny new one. Not ready to give up on the awesome work done on crouton. Hopefully I'll get it going for another long stretch. Thanks!

**Comment by mathnic** [comment]
I got myself a shiny new Sid+xfce and it failed same way as my old tired one. If I then switch to the less than ideal desktop lxde, tada!!! it works fine. Mentally I just have to figure out how to live with that desktop, ouch!
On the more serious side, could it be that Sid (on the bleeding edge) implements xfce's transition to GTK3 and that makes crouton go sour, or chrouchy, as they say. Just my five cents, but somewhere in there is trouble.

**Comment by mathnic** [comment]
Hopefully this will be my last post on this thread. Wanted to report in case anyone else runs into this.
1. As previous post noted, a new Sid+xfce-desktop chroot did not work. After an update with lxde target , it does work with lxde.
2. Now the weird thing. Starting that new chroot in xfce mode now suddenly works!!! 
3. Brought my old chroot back to life, updated and tried xfce just to check. Sure enough it did not work, black screen after some 15-ish minutes.
4. Updated the old chroot with lxde target and tried to start. Black screen right at startup. Hmmm.
5. Started again, no other changes. Lxde desktop works fine!
6. Started xfce desktop on that old chroot and it works!!!!! I've been using it through the day, solid.

This is totally weird to me but it seems I'm back in business with my old Sid+xfce chroot.
Fingers crossed, I hope it keeps working. If anyone wants to dig deeper in this, I'm happy to help in any way I can.

**Comment by DennisLfromGA** [comment]
I would guess that something the lxde packages brought in fixed it, hard to say what exactly though.
