### ISSUE TITLE
VirtualBox USB Passthrough - Suggestion

### ISSUE THREAD

**Issue by mangas** [dnschneid/crouton#2665]
#### Please describe your issue:

Due to the way VirtualBox sets up their USB detection it doesn't work for a debian chroot (only one I've tested). 

Main issue is that VirtualBox requires a script to be run by udev on USB device events (add, remove) and setting udev on ChromeOS to run that script would require changing the script a bit, copying it to somewhere on the host and potentially remounting the whole mountpoint with exec 

I would like to propose mounting the chroot with /usr/share/virtualbox bind mounted to the same place on the host which should make it work fine even if the udev rules needs to be tweaked for group permissions the script would work out of the box or almost

Even if virtualbox is not used I can't see a problem with a mounted empty dir but please advise

If this is acceptable I will raise the PR with the necessary changes. 

@drinkcat @dnschneid thoughts? Suggestions?

**Comment by drinkcat** [comment]
Sounds reasonable to me, please make a PR and we can discuss it better there.
