### ISSUE TITLE
Problems running Kali-Rolling on HP Chromebook.

### ISSUE THREAD

**Issue by OsirisPatron** [dnschneid/crouton#2666]
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20160627183059~master:e3c0a690
release: kali-rolling
architecture: armhf
xmethod: xorg
targets: kde
host: version 8172.60.0 (Official Build) stable-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Thu Jun 23 01:21:34 PDT 2016 armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/kali...

After typing sudo startkde into terminal it gives the following error.

X.Org X Server 1.18.3
Release Date: 2016-04-04
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Jun 23 01:21:34 PDT 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=576579f8-f909-de43-a48e-c4ccd243150a/PARTNROFF=1 hashtree=PARTUUID=576579f8-f909-de43-a48e-c4ccd243150a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=e9dcf7f5f5245a6cfcd14247b3a2175c844d733b salt=a5a80212b2ef811bd5b4e0d31ec2ca209f126b537a8771f5a9f3c2024f56fa18" noinitrd vt.global_cursor_default=0 kern_guid=576579f8-f909-de43-a48e-c4ccd243150a  
Build Date: 05 April 2016  07:04:24AM
xorg-server 2:1.18.3-1 (http://www.debian.org/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/troy/.local/share/xorg/Xorg.1.log", Time: Wed Jul  6 09:29:16 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/troy/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file. 

I've tried other methods, they've all failed.
sudo enter-chroot
startkde
$DISPLAY is not set or cannot connect to the X server.
startx
X.Org X Server 1.18.3
Release Date: 2016-04-04
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Jun 23 01:21:34 PDT 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=576579f8-f909-de43-a48e-c4ccd243150a/PARTNROFF=1 hashtree=PARTUUID=576579f8-f909-de43-a48e-c4ccd243150a/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=e9dcf7f5f5245a6cfcd14247b3a2175c844d733b salt=a5a80212b2ef811bd5b4e0d31ec2ca209f126b537a8771f5a9f3c2024f56fa18" noinitrd vt.global_cursor_default=0 kern_guid=576579f8-f909-de43-a48e-c4ccd243150a  
Build Date: 05 April 2016  07:04:24AM
xorg-server 2:1.18.3-1 (http://www.debian.org/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/troy/.local/share/xorg/Xorg.1.log", Time: Wed Jul  6 09:31:28 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/troy/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

Can someone please help?

**Comment by penntaylor** [comment]
See if the workaround I give in #2676 works for you.
