### ISSUE TITLE
My sudo startxfce4 is not working please help!!

### ISSUE THREAD

**Issue by AfricanMob** [dnschneid/crouton#2667]
I am currently trying to install Xiwi and Xfce together and I have tried for 3 times. The first time I did not enter a password so I deleted Xiwi and Xfce and redowloaded and for 2 times now sudo startxfce4 is not working.

I start by inputing sudo sh ~/Downloads/crouton -r trusty -t xfce,xiwi and it downloads like normal. But then when I input sudo startxfce4 this is what happens: 
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

What should I do?

**Comment by DennisLfromGA** [comment]
@AfricanMob,

> Cannot connect to extension, retrying...
Error: not connected.

> Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)

You need to install the ['crouton integration' extension](http://goo.gl/OVQOEt) from the Chrome Web Store as noted above, it's trying to connect to it but can't.

-**DennisL**

**Comment by AfricanMob** [comment]
@DennisLfromGA 

Well I did already have the crouton integration extension from the Chrome Web Store, I disabled the extension earlier when I tried the first time. Well now that I have found out the problem. All I needed to do was enable the extension so I am all good for right now. But I do have one last question. How can you increase space in Linux?

**Comment by DennisLfromGA** [comment]
@AfricanMob,

> How can you increase space in Linux?

Do you mean increase your chroot's space?
If so, it will use whatever space it needs, the space will just grow in the chroot's folder when you add packages and such - typically `/usr/local/chroots/trusty` in your case.
'crouton' does not re-partition or re-size anything on your Chromebook, it use existing space on your 'stateful' partition. This is unlike 'ChrUbuntu' or 'chrx' and others that actually do re-size partitions.

If you want to increase space on your Chromebook, you'll have to buy one with a larger drive or upgrade your SSD if it's possible on your device.

Hope this helps,
-**DennisL**

**Comment by AfricanMob** [comment]
@DennisLfromGA 

Well I am currently trying to play steam games on my Chromebook,(that's why I installed Linux) and I noticed that you can only have 3.3 GB of space on Linux and really that is not enough to play the good games. So I have an external hard drive all I need to know how to do is mount it to the Computer and be able to use it.

**Comment by DennisLfromGA** [comment]
@AfricanMob,

An external drive plugged into a USB port *might* work, it depends on the model and format, etc.
If it's compatible, when you plug it in it should 'mount' automatically and show up in your 'Files' app.

A better option might be, and I should have mentioned this earlier, is to use a USB stick or an SD Card.
You can install your chroot on the external media and run everything from it, no need to take up space on your Chromebook.

Hope this helps,
-**DennisL**
