### ISSUE TITLE
Kali-rolling login as root

### ISSUE THREAD

**Issue by zeldoon** [dnschneid/crouton#2668]
Is there anyway to just login as root? I tried to setup the first unix request for username and password as root but it says there is already root... obviously. I tried to run su but the password established wasn't the password I setup or toor. Am I missing something obvious here?

**Comment by zeldoon** [comment]
on a side note I just want to say you have done something great here with crouton, truely made me excited about the possibilities of the chromebook.

**Comment by DennisLfromGA** [comment]
@zeldoon,

Did you *'encrypt'* your chroot with a password using crouton's '-e' option?
If so, then that's the password you need to enter when launching `'su'` or `'sudo'`.

crouton's '-e' option calls `sudo chromeos-setdevpasswd` to install a password for 'chronos', that's the username that Chrome OS uses.

Once you can properly use `'sudo'`, then you can login to your chroot *as root* using something like:

`sudo enter-chroot -u root`

*Hope this helps,*
-**DennisL**

**Comment by zeldoon** [comment]
uhg I knew it was going to be something like that, yes I did set the -e option to encrypt and that is the issue. THANK YOU!!!!!!!!!!!!!!!

**Comment by DennisLfromGA** [comment]
@zeldoon - No problem, glad you got it figured out.

( You can probably close this issue now if you like. )

**Comment by Cryptiiiic** [comment]
@DennisLfromGA I know you commented this over a year ago, sorry for replying in 2017. Can you set the default user as root instead of having to do -u everytime?

**Comment by DennisLfromGA** [comment]
@Cryptiiiic,

I imagine you can but I believe crouton would at a minimum complain and/or 'fix' it on each update.
But, you could make a bash alias that does it I guess, something like:

`alias enter-chRoot='enter-chroot -u root'`

Note the upper-case 'R' in the alias.
Then run it like this:

`sudo enter-chRoot`

You can add the alias to your `.bashrc` or `.bash_aliases` file so you don't have to re-define it each session.

*Hope this helps,*
-**DennisL**

**Comment by tcwhite101** [comment]
having a similar problem except i didnt ecrypt my crouton. have no problem running sudo apt-get install or similar sudo commands

**Comment by Cryptiiiic** [comment]
@DennisLfromGA Thanks

**Comment by tcwhite101** [comment]
update. havent tried to enable root inside of chroot. but did have success with sudo su command to enable root (chronos). Anyways still having trouble apt-getting anything inside of chroot ex. metasploit framework. did manage to get nmap and stuff but the error i get with installing most of the required tools
is no results.
so what could be the issue? if i can log in chronos as root then why is kali giving so many problems.
tried to dual-boot a later windows system with kali. didnt habe certain network drivers i needed so i stuck with chroot as i dont understand drivers for the most part.
thanks team
