### ISSUE TITLE
Error while creating new project on cordova

### ISSUE THREAD

**Issue by xavier143** [dnschneid/crouton#2669]
Creating a new cordova project.
Error: EPERM: operation not permitted,

![20160706_195716](https://cloud.githubusercontent.com/assets/20093636/16621398/b6cb7c2c-43b3-11e6-85ae-158e98a8645f.jpg)
When I am creating a project on Cordova through cmd I m getting the above error.
Can anyone please help me\
I m using Windows 7 with 32 bit.

**Comment by DennisLfromGA** [comment]
@xavier143 - I believe you took a wrong turn, this site is for issues with **'crouton'** not *'windoze'*...

**Comment by drinkcat** [comment]
#262...........!
