### ISSUE TITLE
Questions about the keyboard overlay

### ISSUE THREAD

**Issue by fpp-gh** [dnschneid/crouton#267]
[ In retrospect it was probably a mistake to post these in a closed issue (#138), although its topic was appropriate, so I'm adding them here in full view :-) ]

Since I upgraded to the "keyboard" target, my ARM Chromebook has become a lot more comfortable to use (I had tried to hack some Search key shortcuts with xmodmap myself, with little success).
I do have some follow-up questions about how this is done :
-    was it finally implemented through xbmap ?
-   in the initial xmodmap approach, why and how was the Search key remapped to Mode_switch ?
-    for non US keyboards, the wiki says that "setxkbmap -layout xx" should be ran each time the chroot is restarted : on mine (xfce + raring), the layout seems to stick around, even across reboots.
  At first I thought this was because I left "save session" checked by default in the logout panel, but it works just the same with that unchecked.
- About once a day, after using some Search+ combination, I end up stuck in Caps Lock. Is there a way to get out of that mode, other than restarting xfce ?
-    now I would like to define my own Search+key combos (with plain letters, to launch apps).
  What would the simplest way to go about this without breaking anything else ? xmodmap ? .xbindkeys.scm ?
  Most user-level utilities (like xfce's shortcut manager) don't recognize the Search key (Overlay1_Enable in xev) as a modifier, and by tinkering with .xbindkeys.scm I even managed to disable the functionality on F6/F7 :-)

Thanks for any tips,
fp

**Comment by rumly111** [comment]
I found this very useful. It is also possible to change Mod4 to Control (https://pastebin.com/e68xg2mG). Very useful for Emacs users ^_^
