### ISSUE TITLE
Crouton install on 64GB SD card -- Not enough free space error?

### ISSUE THREAD

**Issue by UnknownFearNG** [dnschneid/crouton#2670]
Hey guys. I'm trying to install Crouton on a 64 GB ext2 formatted SD card. It mounts to /media/removable/SDCard just fine, and it even seems to install just fine after running:

sudo sh -e ~/Downloads/crouton -r xenial -t xfce -p /media/removable/SDCard/

But, it then gives me this error:

Moving bootstrap files into the chroot...
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/bin’: Input/output error
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/boot’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/debootstrap’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/dev’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/etc’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/home’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/lib’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/proc’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/root’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/run’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/sbin’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/sys’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/tmp’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/usr’: No space left on device
mv: cannot create directory ‘/run/crouton/media/removable/SDCard/chroots/xenial/var’: No space left on device
rm: cannot remove ‘/run/crouton/media/removable/SDCard/chroots/xenial’: Device or resource busy
rm: cannot remove ‘/media/removable/SDCard/chroots/xenial’: Input/output error

Not sure why it's saying there isn't enough space on my SD card. Here's the output for:

chronos@localhost / $ df -h /media/removable/SDCard/
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk1p1   62G   52M   59G   1% /media/removable/SDCard

Not sure what the issue is. I even made a post on the crouton-central Google Groups, DennyL and I have been going back and forth, trying to figure out what the issue is. Nothing seems to be working.

**Comment by DennisLfromGA** [comment]
I don't know why it's telling you "No space left on device" when '`df -h `' shows 59G is available.
Maybe someone here can figure it out hopefully.

**Comment by drinkcat** [comment]
Not sure either...
