### ISSUE TITLE
Installing Crouton on HiSense Chromebook 11, need a password?

### ISSUE THREAD

**Issue by yuffi369** [dnschneid/crouton#2671]
```
Please paste the output of the following command here: sudo edit-chroot -all
Password: 
```
#### Please describe your issue:

I'm trying to install crouton on my HiSense Chromebook 11, but whenever I try to install it I get prompted to a password screen. The problem is that I can't type or copy/paste a password in, no keys other than enter work and I can't install crouton.
#### If known, describe the steps to reproduce the issue:

Ctrl+Alt+T to go into chronos
crosh>shell
chronos@localhost / $ sudo sh ~/Downloads/crouton -e -t xfce
Password:

**Comment by DennisLfromGA** [comment]
@yuffi369,

> chronos@localhost / $ sudo sh ~/Downloads/crouton -e -t xfce

Don't use crouton's '-e' option to encrypt your chroot and it won't ask for a password.

**Comment by yuffi369** [comment]
@DennisLfromGA ,
Thank you so much! So I did successfully install, but I have no clue what to input in order to enter the session. It said to put enter-chroot so that's what I did.

chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)jeren@localhost:~$ 

After that I think I'm supposed to enter something but I'm not sure what.

**Comment by DennisLfromGA** [comment]
That's why we ask that you show us the output of: `sudo edit-chroot -all`

If you used the above command but without the 'e' option, then you've installed a 'precise' chroot with the xfce4 desktop.

You've already discovered how to get a shell session using: `sudo enter-chroot`
To start the XFCE4 gui desktop session, enter: `sudo startxfce4`

> After that I think I'm supposed to enter something but I'm not sure what.

You can do all kinds of linux things once your in the chroot; I don't know what you had intended to do when you installed it, you must have had a reason???

**Comment by yuffi369** [comment]
@DennisLfromGA 

Ok, I figured out I actually did install it, no other action necessary from that menu. Now the switch screen is asking for another password. I'm still hunting around for how to reset it or find out what it is.

I also decided to re enter `sudo edit-chroot -all` , typed in the password I put in when I installed the user, and then got this;

`name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160627183059~master:e3c0a690
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8172.60.0 (Official Build) stable-channel veyron_jerry 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jun 22 22:58:23 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $ `

Does that mean the password is "precise"? Or something else?

Also, I'm only trying to get Linux because my graphics tablet doesn't work well with Chrome, as pen pressure is nonexistent, so installing Wine and running the driver through that should work, as I've been told.

**Comment by DennisLfromGA** [comment]
> Does that mean the password is "precise"? Or something else?

No, the release name is 'precise'.
You entered a username and password at a prompt when the chroot was installed.
Your username is 'jeren' but I don't know what you entered as the password, hopefully you do.

> Now the switch screen is asking for another password.

I don't understand that statement but enter the password for user 'jeren' and see if that works.
If you don't remember the password you gave it, you can login as root and change it.

**Comment by yuffi369** [comment]
@DennisLfromGA 

Well, it's supposed to come up as a different OS when I hit the key commands, correct? It's currently just sending me to a prompt screen that looks similar to crosh, instead of what I want, which is ubuntu software. I'm not sure if there are any further steps or if I just installed an improper version.
I did try logging in as jeren on the other OS, but it didn't recognize it as a usernname, but I was able to log in as "chronos" with the same password I used.

**Comment by DennisLfromGA** [comment]
> Well, it's supposed to come up as a different OS when I hit the key commands, correct? It's currently just sending me to a prompt screen that looks similar to crosh, instead of what I want, which is ubuntu software.

Like I mentioned above, To start the XFCE4 gui desktop session, enter: `sudo startxfce4`

Then spend some time getting familiar with things in your chroot and your Chromebook in general.

**Comment by yuffi369** [comment]
@DennisLfromGA 

When I tried the command `sudo startxfce4` on crosh, I got this whole message;

` Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jun 22 22:58:23 PDT 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9bd83dc5-475d-644e-ad95-4b516616035e/PARTNROFF=1 hashtree=PARTUUID=9bd83dc5-475d-644e-ad95-4b516616035e/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=ae0e7bb28a22db73865c61e8682cf3b46a4b3053 salt=bdb1992e9532267bca5d77edade61b594575638640a4807588d3336c5915322b" noinitrd vt.global_cursor_default=0 kern_guid=9bd83dc5-475d-644e-ad95-4b516616035e  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jul  8 15:31:01 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise... `

Also when I use the other OS to type this command, I get 
`Xorg X11 servers cannot be launched from Frecon.
Return to Chromium OS and use crosh to launch X.`

**Comment by DennisLfromGA** [comment]
Try below:
> CTRL+ALT+T
shell
sudo rm /dev/dri/card0
sudo mv /dev/dri/card1 /dev/dri/card0
sudo startxfce4

**Comment by IAMBOB20** [comment]
so ive seen this before and i tried this again just to make sure it wasn't different and it still did work please help

**Comment by TheSaltyc** [comment]
@DennisLfromGA . Hi Sorry for bothering you but I was just wondering if you could help me? where and when do i put the /dev/dri parts? Thanks

**Comment by DennisLfromGA** [comment]
@TheSaltyc,

Reboot your C hromebook, 
Then do the procedure above: https://github.com/dnschneid/crouton/issues/2671#issuecomment-235670851,
Then start your desktop

-**DennisL**

**Comment by Qwerty-Space** [comment]
@DennisLfromGA so after restarting the PC, running that command in #2671 I run ```sudo startxfce4```?

**Comment by DennisLfromGA** [comment]
yup

**Comment by Qwerty-Space** [comment]
It didn't work for me
