### ISSUE TITLE
Hard freeze on Chromebook Flip after switching to XFCE after sleep

### ISSUE THREAD

**Issue by floe** [dnschneid/crouton#2674]
```
$ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20160627183059~master:e3c0a690
release: xenial
architecture: armhf
xmethod: xorg
targets: keyboard,extension,xfce-desktop
host: version 8350.38.0 (Official Build) beta-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Jun 21 21:43:55 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```
#### Please describe your issue:

After starting XFCE with `sudo startxfce4`, I can switch back and forth between ChromeOS and XFCE just fine, unless I suspend the device in between. In this case, attempting to switch to XFCE triggers a hard freeze, just the cursor on black screen. Need to hold power for 10s to hard-reset.
#### If known, describe the steps to reproduce the issue:
- Launch XFCE4 with `sudo startxfce4`.
- Switch to XFCE and back to ChromeOS.
- Suspend the device by closing the lid.
- Open it again.
- Switch to XFCE -> hard freeze.

**Comment by floe** [comment]
Maybe related: https://github.com/dnschneid/crouton/issues/2576

**Comment by floe** [comment]
Problem persists after updating to:
`host: version 8350.55.0 (Official Build) beta-channel veyron_minnie `

**Comment by drinkcat** [comment]
Can't reproduce on recent images, wondering if the recent render node fixes helped. Please reopen if it happens again.

**Comment by floe** [comment]
Please reopen, still happens with the following configuration:

```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161014161205~master:16fd55fd
release: xenial
architecture: armhf
xmethod: xorg
targets: keyboard,extension,xfce-desktop
host: version 8743.65.0 (Official Build) beta-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Oct 12 19:54:05 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

**Comment by floe** [comment]
Note: immediately before testing, I had run `sudo sh ~/Downloads/crouton -u -n xenial`, so the chroot should be fully up-to-date.

**Comment by dnschneid** [comment]
@drinkcat, did you test a canary or something?

**Comment by floe** [comment]
Still happens with the following configuration:

```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161116131524~master:9db73043
release: xenial
architecture: armhf
xmethod: xorg
targets: keyboard,extension,xfce-desktop
host: version 8872.54.0 (Official Build) beta-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Nov 16 21:38:16 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

**Comment by floe** [comment]
Note: I'd be happy to help to debug this, any hints would be appreciated.

**Comment by floe** [comment]
I wiped my chroot and re-installed xenial with targets xfce,keyboard,extension. I didn't yet customize the chroot in any way, but the default install seems to work, even across multiple suspend and resume cycles.

I noticed that when I switch back to Xorg after suspend, I'm greeted by xscreensaver. I also remember that I had removed xscreensaver in my previous attempt at some point, as I found it annoying. Is it possible that something locks the Xorg session at suspend, and if xscreensaver is not running, there is nothing left to unlock it, thereby triggering the freeze?

**Comment by swors** [comment]
@floe 
I meet the same problem. Is there any solution?

**Comment by floe** [comment]
The problem disappeared after I had reinstalled my chroot, so I can't really suggest any other solution...

**Comment by divx118** [comment]
@swors Did you try updating your chroot `sudo sh ~/Downloads/crouton -u `

**Comment by swors** [comment]
@divx118 yes
chronos@localhost / $ sudo enter-chroot -n stretch croutonversion
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20170619181610~master:980f090f
release: stretch
architecture: amd64
xmethod: xorg
targets: extension,xfce,cli-extra
host: version 9592.42.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-14861-g70c266fc4519 #1 SMP PREEMPT Thu Jun 29 22:03:53 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...

**Comment by swors** [comment]
@floe  I‘ll try to install a new chroot later

**Comment by divx118** [comment]
@swors well I asked just to be sure, maybe you did install something that broke the chroot then. If you have enough free space you could try installing a new chroot along side the old one. No powerwash needed and see if it works then.

**Comment by swors** [comment]
@divx118 
I guess that this  'sudo apt remove --purge xserver-xorg-legacy' broke the chroot.
But if I don't do this, I can't startxfce4.
[Debian Stretch Crouton Problem](https://www.reddit.com/r/Crouton/comments/6ihmhk/debian_stretch_crouton_problem/)

**Comment by divx118** [comment]
@swors Oh, that should be reported as an issue here, so it can be solved. Best is to create a separate issue for that. I will try it sometime this week and see if I also encounter the  xserver-xorg-legacy issue with stretch.

**Comment by swors** [comment]
#3242 
I find someone has reported the bug

**Comment by arcutright** [comment]
I also came across this issue, and for me it was due to locale settings (my language was set to "C" after setting up xenial). If you run `sudo locale` and get output anything like this:
```
$ sudo locale
LANG=C
LANGUAGE=
LC_CTYPE=fi_FI.UTF-8
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE=fi_FI.UTF-8
LC_MONETARY="C"
LC_MESSAGES=fi_FI.UTF-8
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

Here's the fix:
```
$ sudo locale-gen "en_US.UTF-8"
Generating locales...
  en_US.UTF-8... done
Generation complete.
$ sudo dpkg-reconfigure locales
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
```

Follow this up by appending this to `/etc/default/locale` and `/etc/environment`
```
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```

And adding these lines to `~/.bashrc`
```
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
```

Obviously, sub in your language region settings.
Credit to the folks at https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

**Comment by gardwired** [comment]
still no joy.  did the locale thing.  still hard freeze on my asus c302

**Comment by gardwired** [comment]
some news.  i did a fresh install of stretch/xfce-desktop, removed xserver-org-legacy, got into xfce then turned off all of the screenlock/screensaver/power management in xfce and i can now suspend from either chromeos or chroot without hard freeze.  this is on asus c302.  fyi.
