### ISSUE TITLE
Can't install Google Chrome

### ISSUE THREAD

**Issue by snelhezt** [dnschneid/crouton#2677]
(precise)xxx@localhost:~$ sudo apt-get install google-chrome-stable
[sudo] password for xxx: 
Läser paketlistor... Färdig
Bygger beroendeträd         
Läser tillståndsinformation... Färdig
Några paket kunde inte installeras. Det kan betyda att du har begärt
en omöjlig situation eller, om du använder den instabila utgåvan
att några nödvändiga paket ännu inte har skapats eller flyttats
ut från "Incoming".
Följande information kan vara till hjälp för att lösa situationen:

Följande paket har beroenden som inte kan tillfredsställas:
 google-chrome-stable : Beroende av: libstdc++6 (>= 4.8.0) men 4.6.3-1ubuntu5 kommer att installeras
                                        Beroende av: lsb-base (>= 4.1) men 4.0-0ubuntu20.3 kommer att installeras
E: Kunde inte korrigera problemen, du har hållit tillbaka trasiga paket.
(precise)xxx@localhost:~$

Sorry for the Swedish, but in short. I can't install Google Chrome since i'm missing libstdc++6 and lsb-base. I have no idea what they do or why i'm missing them since i could install Chrome earlier without any problems.

**Comment by DennisLfromGA** [comment]
You might have to install it in the chroot [from the web](https://www.google.com/chrome/browser/desktop/index.html) instead of having crouton do it.

**Comment by snelhezt** [comment]
Same problem there

**Comment by DennisLfromGA** [comment]
Have you tried fixing & updating the packages in your chroot via -

`sudo apt-get install -f`
`sudo apt-get update`

**Comment by snelhezt** [comment]
Thanks, but i did not do much and so did not help :/

**Comment by idvoretskyi** [comment]
@snelhezt what chroot (distro) version do you use?

What output do you receive after running `sudo apt-get install -f`?

**Comment by snelhezt** [comment]
Ubuntu Precise

Here's what happens when running sudo apt-get install -f

chronos@localhost / $ sudo enter-chroot -n precise sudo apt-get install -f
Entering /mnt/stateful_partition/crouton/chroots/precise...
[sudo] password for xxx:
Läser paketlistor... Färdig
Bygger beroendeträd
Läser tillståndsinformation... Färdig
0 att uppgradera, 0 att nyinstallera, 0 att ta bort och 0 att inte uppgradera.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by idvoretskyi** [comment]
@snelhezt Ubuntu Precise is pretty old, I suppose the best issue solution for you will be upgrading to Trusty at least.

**Comment by DennisLfromGA** [comment]
It looks like it succeeded but I don't speak or read Swedish, English would be helpful.
Did you do an `sudo apt-get update` ?

**Comment by divx118** [comment]
@snelhezt FYI before running a command and get the output messages in english use the following command first. `export LC_ALL=C`

**Comment by snelhezt** [comment]
@idvoretskyi I know it's pretty old, but i used it earlier before i tried out Debian, and then it worked. But i might give Trusty a go just to see if it works better.

@DennisLfromGA Yes i have. Only some translations that had some update and nothing more.

Thanks @divx118 I did not know about that command.
Here it is in English
(precise)xxx@localhost:~sudo apt-get install -f
[sudo] password for xxx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by divx118** [comment]
@snelhezt You probably are running into the issue that google has stopped support for precise. So switching to trusty would be my advice. Also see http://askubuntu.com/questions/758571/google-chrome-stable-depends-on-libstdc6-4-8-0-however-version-of-libs

**Comment by DennisLfromGA** [comment]
@divx118 - Thanx, that looks to be exactly the problem. I've been using 'trusty' for quite a while now with no issues.

**Comment by snelhezt** [comment]
Thanks guys.
Just tried Trusty and everything works as it should.

**Comment by DennisLfromGA** [comment]
@snelhezt - You can probably close this issue then if you like.

**Comment by divx118** [comment]
@DennisLfromGA  @snelhezt  Probably we need a fix in the chrome target so it installs chromium for the non supported distros or spits out a warning. I rather would keep this issue open to track it.

**Comment by DennisLfromGA** [comment]
Okay, guess I got a little hasty.
