### ISSUE TITLE
Can't access my shared files from Windows

### ISSUE THREAD

**Issue by snelhezt** [dnschneid/crouton#2678]
I've done it before so i don't know why i can't do it again.
Trying to access my shared files from a Windows machine. But with a fresh install of Ubuntu Precise i'm not able to locate that machine anymore, and even worse, i'm missing the Network tab in the file explorer.
Samba is installed and i'm out of ideas.

**Comment by snelhezt** [comment]
Solved since i changed to Trusty

**Comment by DennisLfromGA** [comment]
That's good to know, thanx.
