### ISSUE TITLE
"system network services are not compatible with this version" 

### ISSUE THREAD

**Issue by TerryMinal** [dnschneid/crouton#2679]
print out: 
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160627183059~master:e3c0a690
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 8172.62.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jul 6 18:07:54 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/... 

```
issue:
I'm not very familiar with linux, chromeOS, or crouton. My issue is the network manager and internet connection. I cannot get the system network to work at all. On my first crouton install, I first thought that linux itself was the issue leading me to uninstall, reinstall, and alter multiple files. After hours of struggling no result was produced, so I began thinking that it was a crouton issue. My initial crouton install was the ubuntu precise(12.04 LTS ubuntu, I believe) distribution. I later uninstalled the precise distro and installed the trusty(14.04 ubuntu) and the issue still endures. I greatly appreciate any kind of help.

**Comment by divx118** [comment]
Network is shared with chromeos. You shouldn't use the networkmanager in the chroot. After you installed the chroot and start it up then you should have internet connection automatically. At least if you are connected to internet on the chromeos side. If you need or want to change wifi networks, then you have to do it in chromeos not the chroot.

**Comment by TerryMinal** [comment]
@divx118 Thank you for the response. I understand the issue now

**Comment by divx118** [comment]
@TerryMinal Please close this issue then. Thanks.
