### ISSUE TITLE
only have a mouse on screen... just installed 1st time 12.04 xfce

### ISSUE THREAD

**Issue by michael-harings** [dnschneid/crouton#2680]
Got a refurb acer 571 chromebook this afternoon. Explored a couple hours, added crouton. 
Successfully went back & forth between chromebook & xfce a number of times. Updated chromebook.

Eventually put it to sleep with xfce still running. Opened up chromebook environment, went to xfce, only saw mouse and a terminal (everything else was black). Closed terminal, can't get back to chromeos. Ctrl-shift-alt-Back key ctrl-alt-shift-Forward key don't do anything. ctrl+alt+-> ctrl+alt+-< keys don't either. power button doesn't do anything. Putting system to sleep by closing lid and restoring by opening lid gives me a cursor back. :-). 

I'd pull the battery on a regular laptop & start over... but I don't want to open it on my first day to unplug the battery if there's other options. Any suggestions?

TIA, Michael

**Comment by divx118** [comment]
@michael-harings Just hold down the power button for at least 10 seconds. That should do a forced shutdown of your chromebook. If you updated chromeos, you also need to update your chroot. see https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

**Comment by michael-harings** [comment]
Thanks for the tip Maurice!

I'm having a lot of fun playing with this chromebook, it's a really nice
price $150 for a refurb 15" screen. Nice hardware/software design by
Google.
