### ISSUE TITLE
FILE SYSTEM OUT OF SPACE DURING CLONING OF KERNEL

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#2681]
```
git clone https://chromium.googlesource.com/chromiumos/third_party/kernel -b chromeos-[version]

after running this... clones kernel file but system runs out of space afterwards..
```

#### Please describe your issue:
I simply ran out of space on the filesystem... how do I find this massive file and delete it? where is is cloned on the filesystem?

**Comment by Carl393** [comment]
nevermind it was located in ~/kernel

are there any residual files I can remove to save space?
please advise.

**Comment by divx118** [comment]
@Carl393 No, everything is in ~/kernel, so if you deleted that folder no residual files are left. For saving space you could look at what you have in ~/Downloads, or if you have multiple chroots, maybe backup and then delete. Not much else you can do. You could use an external storage where you clone the kernel, but that increases time when building. Fastest way for building is on the internal storage (SSD).
