### ISSUE TITLE
Which kernel modules are required to be loaded for KVM support?

### ISSUE THREAD

**Issue by ddykhoff** [dnschneid/crouton#2682]
I am trying to get the Android Studio emulators working on my C720. I have enabled VT-x and module loading from the following guide: https://github.com/dnschneid/crouton/wiki/Enable-kernel-VT_x-for-Virtualbox

As @dnschneid says in #189:

> You'd have to compile KVM for the Chromium OS kernel, disable verified boot, make the root FS writable (you'll lose auto-updates), and then install the kernel module. 

I've already performed all of those steps previously to get cifs installed for mounting SMB shares in my chroot, so I'm not afraid to do it again. My question is what kernel modules do I need to compile from the kernel source to be loaded in able to get KVM going? Previously I had set chromeos/config/base.config line entries to 'm' (external module) so that I could later load the .ko files into the kernel using insmod (for example, CONFIG_CIFS=m in base.config generated cifs.ko and was loaded using `sudo insmod cifs.ko`). 

What line entries in base.config do I need to edit or add in order to generate the KVM kernel modules?

**Comment by idvoretskyi** [comment]
cc @divx118
