### ISSUE TITLE
Pixel 2015, Xorg, Unity - Trackpad Skipping When Trying to Click 

### ISSUE THREAD

**Issue by ewhill** [dnschneid/crouton#2683]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160627183059~master:e3c0a690
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,touch,unity
host: version 8172.60.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jun 22 23:08:58 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

On Chromebook Pixel 2015 - The trackpad within unity, xorg skips a lot when trying to click. I'm assuming this is because of a phantom or lingering finger on the trackpad and finicky sensitivity in the trackpad's driver; however, the cursor skips halfway across the screen making it hard to click something most of the time.

Using a USB mouse does not have the same problem (as expected), bug only occurs when using the trackpad.

This is the second Pixel 2015 that I've owned and it also occurred on my last pixel's chroot running xfce with xorg.

Interestingly enough, when I use xiwi as opposed to xorg, the same trackpad skipping **does not** occur at all (at least not for the amount of time that I had xiwi set as my chroot's target).

**Comment by ikeahloe** [comment]
This does the same regardless of desktop for me

**Comment by GertBurger** [comment]
Same issue for me on a 2015 Pixel LS.

Tapping on the touchpad does the right thing but clicking on the touchpad makes the cursor jump far right.

**Comment by ewhill** [comment]
Hi, is there any news on this?

**Comment by drinkcat** [comment]
synclient commands sometimes can help with these...
