### ISSUE TITLE
Proposal: switch from precise as a default release for building chroot

### ISSUE THREAD

**Issue by idvoretskyi** [dnschneid/crouton#2684]
As an end-user, I'd like to use the actual version of ubuntu/debian as a default release for chroot.

I may propose Trusty (as the stable Ubuntu LTS), Xenial (as the latest Ubuntu LTS) or Debian Jessie for this role.

**Comment by DennisLfromGA** [comment]
@idvoretskyi - This has been brought up a few times but there are still some issues on some platforms that prevent it, see https://github.com/dnschneid/crouton/issues/1671#issuecomment-98594134

**Comment by drinkcat** [comment]
Duplicate of #1671.
