### ISSUE TITLE
Fatal server error: no screen found

### ISSUE THREAD

**Issue by YakketyYak00** [dnschneid/crouton#2686]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by YakketyYak00** [comment]
Im installing crouton on a Hisense Chromebook, the start command sudo startxfce4, when used gives me the error "fatal server error: no screen found.

How do I correct this error? (installing ubuntu 16.04 w crouton integration) powerwashed before device before comment.

**Comment by jackamofinane** [comment]
I get the same exact error on Haier chromebook after installation per: http://lifehacker.com/how-to-install-linux-on-a-chromebook-and-unlock-its-ful-509039343
All steps seemed to work fine except the last step. sudo startxfce4
Output of sudo edit-chroot -all     is as follows:
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 7262.57.0 (Official Build) stable-channel veyron_jaq 
kernel: Linux localhost 3.14.0 #1 SMP Fri Sep 18 00:43:21 PDT 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I am attempting install on brand new Haier chromebook. Just noticed, it is pending some updates so I will restart and check again.

**Comment by DennisLfromGA** [comment]
See https://github.com/dnschneid/crouton/issues/2671#issuecomment-235670851

**Comment by jackamofinane** [comment]
Thanks DennisLfromGA,  I decided to try the trusty release, re wiped everthing and trusty worked for me on the Haier chrombook. Also loaded chrome extension per crouton instructions. If I end up trying the latest build again I will try this solution and post here.

**Comment by DennisLfromGA** [comment]
@jackamofinane - Great, glad you got something to work for you.

I've been using 'trusty' in my chroots for quite a while now and it just works.
I've played with 'xenial' a bit but not everything works just yet.

-**DennisL**

**Comment by dnschneid** [comment]
Fixed in latest crouton; no hacks needed.
