### ISSUE TITLE
Problem with unwrapping passphrase

### ISSUE THREAD

**Issue by AlbertoElias** [dnschneid/crouton#269]
Hi, I've been using my chroot with unity for a while, which I created thanks to a slightly older version of crouton, but a week ago I couldn't continue executing it because when I type in my passphrase I get the following error:

Enter encryption passphrase for precise: 
Error: Unwrapping passphrase failed [-5]
Info: Check the system log for more information from libecryptfs
Error: Unwrapping passphrase failed [-5]
Info: Check the system log for more information from libecryptfs
mount: No such file or directory
Failed to mount precise.

I don't know what happened because I'm quite sure I haven't manipulated anything since the last time I executed my chroot. Any suggestions?

Thanks a lot

**Comment by son21u** [comment]
how can i find the passphrase??????

**Comment by dnschneid** [comment]
Search your workspace for a sticky note with the passphrase written on it?

**Comment by DennisLfromGA** [comment]
@dnschneid - You are tooooo funny ;)

**Comment by son21u** [comment]
I sorted it out. recovered the data without the phassphrase. : )

**Comment by 4myle** [comment]
@son21u if you don't mind, how did you do it?

**Comment by sirkubax** [comment]
I had even more stupid case ecryptfs-unwrap-passphrase FAILS with with working logging password.
b
https://askubuntu.com/questions/1134452/ecryptfs-unwrap-passphrase-fails-with-working-loggin-password/1134455#1134455

I can login with my new password, it uses new password to decrypt and mount files, yet ecryptfs demands my old (very very old, maybe compromised?) password to ecryptfs-unwrap-passphrase /home/username/.ecryptfs/wrapped-passphrase

**Comment by DennisLfromGA** [comment]
@sirkubax,

Try using crouton's '**-e**' option *twice* to change it -
```
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
```
Like: `sudo crouton -u -ee [-n chrootname]`

*Hope this helps,*
-**DennisLfromGA**
