### ISSUE TITLE
Failed to open "/ on ". The specific location is not supported.

### ISSUE THREAD

**Issue by snelhezt** [dnschneid/crouton#2690]
Don't think this is a Crouton problem, but since i never got answer in ubuntuforums and askubuntu i give it a try here and hopefully solve this problem.

First out.
What's the different between Samba and cifs-utils?

I've done it before without any problem, but now when i click on the Browse network tab i recieve a error message -Failed to open "/ on ". The specificlocation is not supported.

Im trying to access my shared folder that are shared from my Windows PC, and as i said before, there was no problem earlier when i tried it. But now when i've re-installed **Trusty** there's no way to even find the Windows PC.

So i've read alot of guides and some say Samba while other say cifs-utils. I've tried them both and non of them works. And yes, i've tried with a correct setup of samba.conf with no luck.

**Comment by drinkcat** [comment]
Looks like you're not really getting any answer here either, and I have zero clue... Sorry.
