### ISSUE TITLE
Update chroot / no sound / keep settings

### ISSUE THREAD

**Issue by MeneerJansen** [dnschneid/crouton#2691]
Output of the command `sudo edit-chroot -all`
```
name: trusty
encrypted: no
crouton: version 1-20150620222151~master:89796a99
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome
host: version 7978.74.0 (Official Build) stable-channel leon 
kernel: Linux localhost 3.8.11 #1 SMP Thu May 12 00:55:50 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
I have no sound (cras doesn't work).

#### If known, describe the steps to reproduce the issue:
I updated ChromeOS (even-though I didn't want that). And cras didn't work anymore. I readthat updating one's chroot might work to get cras back. I do very important work w/ my Cghromebook, but only in my chroot/Linux. I do NOT want to loose any settings or work. Is it safe to update my chroot w/ the following command (from within Chrome OS??? or from within my chroot??):

```
sudo sh ~/Downloads/crouton -u -n trusty
```
I only want cras to work again, the rest may ***_NOT_*** (I repeat: ***_NOT_***) change!!!!!

**Comment by DennisLfromGA** [comment]
@MeneerJansen,

I realize this advice comes a little late but it's always a good idea to keep a backup of your working chroot, just in case...

It's always a little bit of a gamble but updating your chroot via crouton's update mechanism that you show above is *normally* safe.

Before you do that though, to be just a little more on the safe side, you could log into your chroot and update the chroot's packages/applications first to see if that brings back your sound, using something like this -

`sudo enter-chroot -n trusty`
`sudo apt-get -f install`
`sudo apt-get update`
`sudo apt-get upgrade`
`exit`

Then, log back into your chroot using your gnome desktop gui and see if the sound works.

`sudo startgnome -n trusty`

If sound works again, exit then backup your chroot to the internal drive or to external media - or both.

Either way, now would be a good time to update your chroot via crouton like you showed above:

`sudo sh ~/Downloads/crouton -n trusty -u`

This will ujpdate your chroots packages/applications but, maybe more importantly, update all of crouton's files including re-compiling and installing 'cras' and others.

Hope this helps,
-**DennisL**

**Comment by MeneerJansen** [comment]
@DennisLfromGA

Thank you for the advise. It is not too late to backup my current chroot: I didn't change it yet. So I'll backup first. I "upgraded" Chrome OS. 

As for the `sudo apt-get upgrade`. I've been using Linux as my default OS for ten years now (don't have or need no Windows anymore) but I ***never*** upgrade my Linux distro that way. Might render my PC unusable. I always make an extra partition to install an new Linux version and see if it works to my satisfaction.

Furthermore, `sudo apt-get upgrade` will probably upgrade my chroot from Trusty to Xenial, or worse, the non-long term support Ubuntu 16.10 Yakkety Yak. Nonetheless I'' backup my chroot to a SD card do the `sudo apt-get update` and then upgrade the chroot. 

Does anybody exactly know what the Crouton update process does? Does it radically change my Linux Trusty chroot, or does it only install new things that are needed for Crouton to work w/ the latest version of  ChromeOS?

**Comment by DennisLfromGA** [comment]
@MeneerJansen - sounds like you know better than, I'll leave it in your capable hands.

**Comment by bmorris22** [comment]
I can't tell who's being sarcastic, so I'll bite. `sudo apt-get upgrade` does not upgrade your distro version. It upgrades packages, installed kernels, headers, etc. Here's the wiki: [https://help.ubuntu.com/community/AptGet/Howto](url)

Hope this helps!

**Comment by DennisLfromGA** [comment]
@bmorris22 - I think it might have been a little of both (of us), thanx for clarifying the update process.

**Comment by MeneerJansen** [comment]
My apologies. I was not trying to be sarcastic. And I was plainly wrong too! The command `sudo apt-get upgrade` does not upgrade one's distro! That's the command `sudo apt-get dist-upgrade`. For somebody like me who's been using Linux for ten years on a daily basis that's pretty dumb mistake to make, ha ha! 

Thank you both very much for your replies! Does anybody know what updating one's chroot does then exactly? My guess that it's updating "special" adjustments to Linux to get it to work well as a chroot within ChromeOS (like cras for audio instead of your average basic Alsa).

**Comment by fuzetsu** [comment]
Updating your chroot runs through more or less the same process as installing it. It will run through the installation scripts and install any necessary packages (upgrade them if they're already installed), it will also run through all the targets installed on your chroot and run the new scripts for them, again applying any changes to them and upgrading any related packages.

(Someone correct me if I'm wrong! I'm basing this on my experience as a user and quick scan of the install, prepare and target scripts).

**Comment by DanHolli123** [comment]
do `sudo sh ~/Downloads/crouton -n trusty -u` as it only updates existing packages, crouton, and targets it does not change the release of the chroot

**Comment by MeneerJansen** [comment]
@DanHolli123 Thanks for the info! I feel relieved. First the backup w/ (see the [Crouton Cheat Sheet](https://github.com/dnschneid/crouton/wiki/Crouton-Command-Cheat-Sheet)):
```
sudo edit-chroot -f /media/removable/SDcard_32GB/Cromebook/backupchroot -b trusty
```
Determine chrootname w/ `sudo edit-chroot -a`. In my case this took about xxx minutes. I can restore w/:
```
sudo edit-chroot -f /media/removable/SDcard_32GB/Cromebook/backupchroot -r chrootname
```

**Comment by DanHolli123** [comment]
You are VERY welcome.
Glad I helped!

**Comment by DanHolli123** [comment]
btw since your problem has been solved you should close the issue

**Comment by MeneerJansen** [comment]
@DanHolli123 How do I close this issue?

**Comment by DanHolli123** [comment]
@MeneerJansen The button next to 'Comment' should say 'Close' or 'Comment and Close' click it
