### ISSUE TITLE
Xterm registers too many keystrokes in Xiwi

### ISSUE THREAD

**Issue by tnibert** [dnschneid/crouton#2693]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: armhf
xmethod: xiwi
targets: xiwi
host: version 8172.60.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jun 22 22:31:31 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```

#### Please describe your issue:
I am running xterm in a xiwi window under Ubuntu Trusty on Samsung ARM Chromebook.  I have noticed that frequently I will be typing and the terminal will respond as though I held down a key for a long time when I didn't.  E.g. trying to type 'mkdir' and it comes out as 'mkkkkkkkkkkkkkkkkkkkdir'

#### If known, describe the steps to reproduce the issue:
The issue is intermittent but frequent, haven't figured out how to consistently reproduce.

**Comment by drinkcat** [comment]
I guess that can happen if the system is under heavy load. Not sure what can be done...
