### ISSUE TITLE
Can'r load encryption or Unix password

### ISSUE THREAD

**Issue by speedinggoop** [dnschneid/crouton#2694]
Every single time it asks me to make a unix password or an encryption password, Chrosh will  freeze and not allow me to enter any text . I've made a chroot, deleted it, then rebooted my computer and made another chroot to no avail. Any advice?

**Comment by divx118** [comment]
When entering a password on a linux system in the shell, it won't show you any ... or ***. Just type in your password and press enter.

**Comment by speedinggoop** [comment]
Thanks.
