### ISSUE TITLE
- X xiwi command doesn't load

### ISSUE THREAD

**Issue by ssyyddii** [dnschneid/crouton#2696]
```
Please paste the output of the following command here: sudo edit-chroot -all
crosh> shell
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce
host: version 8530.24.0 (Official Build) dev-channel panther 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jul 20 04:19:49 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
chronos@localhost / $
```
#### Please describe your issue:

When I try to enter xiwi using: sudo startxfce4 -X xiwi the window opens but doesn't load.  When I enter using only: sudo startxfce4 there is no problem.
![screenshot 2016-07-23 at 3 33 04 pm]
![screenshot 2016-07-23 at 3 33 04 pm](https://cloud.githubusercontent.com/assets/12481134/17085604/cff4571e-51dc-11e6-87af-2e7bb6249815.png)
#### If known, describe the steps to reproduce the issue:

I open Crosh
I type: shell
then: sudo startxfce4 -X xiwi

**Comment by JVTEAM** [comment]
The x must be a capital "X"
