### ISSUE TITLE
black screen on startunity, then crash with 

### ISSUE THREAD

**Issue by jbgross** [dnschneid/crouton#2698]
I have a Toshiba Chromebook 2 - 2015 Edition (CB35-C3350). I just got it. I installed crouton and trusty. I followed the directions at [http://www.voltron00x.com/?p=1091](http://www.voltron00x.com/?p=1091)

I have two installations: one is local (on internal SSD) and is named trusty2. It is not encrypted. It works, but I don't have enough room. The other is on a USB drive. It's symlinked to /mnt/stateful__partitions/chroots as trusty. It is encrypted and not working (although it was yesterday). Here's the output from sudo edit-chroot -all:

> name: trusty
> encrypted: yes, locked
> Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
> name: trusty2
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/trusty2...
> crouton: version 1-20160715134041~master:0dc76a22
> release: trusty
> architecture: amd64
> xmethod: xiwi
> targets: unity,extension,xiwi
> host: version 8172.62.0 (Official Build) stable-channel gandof 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 17:53:44 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/trusty2...

Here's the output from sudo enter-chroot -n trusty croutonversion:

> Enter encryption passphrase for trusty: 
> Entering /mnt/stateful_partition/crouton/chroots/trusty...
> crouton: version 1-20160715134041~master:0dc76a22
> release: trusty
> architecture: amd64
> xmethod: xiwi
> targets: xiwi,unity
> host: version 8172.62.0 (Official Build) stable-channel gandof 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 17:53:44 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
> Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
#### Please describe your issue:

Yesterday I had my installation up and running and ran apt-get updates & upgrade but I"m not sure if this is related (I think I successfully launched unity after the updates/upgrade). Now when I call startunity, all I end up with is a black screen (that briefly flashes "Press F11 to Exit Fullscreen", and that black screen eventually dies with no further input. It can't connect  xinit to X server (see below). The process takes maybe 30 seconds.

Here's my output:

chronos@localhost / $ sudo sh startunity -n trusty 

> Enter encryption passphrase for trusty: 
> Entering /media/removable/USB Drive/chroots/trusty...
> 
> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
> 
> X.Org X Server 1.15.1
> Release Date: 2014-04-13
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 17:53:44 PDT 2016 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=02a35465-8e8a-9340-8339-bf410bfb84ce/PARTNROFF=1 hashtree=PARTUUID=02a35465-8e8a-9340-8339-bf410bfb84ce/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=c63fcf39d458faa0860e4908a3f2f35d3c2564fc salt=412ab82058dffb3c7dfcf73b725623db528a0c9866429255a608b2add15a315a" noinitrd vt.global_cursor_default=0 kern_guid=02a35465-8e8a-9340-8339-bf410bfb84ce add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
> Build Date: 12 February 2015  02:49:29PM
> xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.30.2
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jul 26 14:51:55 2016
> (++) Using config file: "/etc/X11/xorg-dummy.conf"
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Initializing built-in extension Generic Event Extension
> Initializing built-in extension SHAPE
> Initializing built-in extension MIT-SHM
> Initializing built-in extension XInputExtension
> Initializing built-in extension XTEST
> Initializing built-in extension BIG-REQUESTS
> Initializing built-in extension SYNC
> Initializing built-in extension XKEYBOARD
> Initializing built-in extension XC-MISC
> Initializing built-in extension SECURITY
> Initializing built-in extension XINERAMA
> Initializing built-in extension XFIXES
> Initializing built-in extension RENDER
> Initializing built-in extension RANDR
> Initializing built-in extension COMPOSITE
> Initializing built-in extension DAMAGE
> Initializing built-in extension MIT-SCREEN-SAVER
> Initializing built-in extension DOUBLE-BUFFER
> Initializing built-in extension RECORD
> Initializing built-in extension DPMS
> Initializing built-in extension Present
> Initializing built-in extension DRI3
> Initializing built-in extension X-Resource
> Initializing built-in extension XVideo
> Initializing built-in extension XVideo-MotionCompensation
> Initializing built-in extension SELinux
> Initializing built-in extension XFree86-VidModeExtension
> Initializing built-in extension XFree86-DGA
> Initializing built-in extension XFree86-DRI
> Initializing built-in extension DRI2
> Loading extension GLX
> /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
> crouton: version 1-20160715134041~master:0dc76a22
> release: trusty
> architecture: amd64
> xmethod: xiwi
> targets: xiwi,unity
> host: version 8172.62.0 (Official Build) stable-channel gandof 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 17:53:44 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Connected to extension, launched crouton in a window.
> Error: target STRING not available
> Running exit commands...
> /usr/bin/xinit: connection to X server lost
> Hangup
> Hangup
> 
> waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.
> 
> Unmounting /media/removable/USB Drive/chroots/trusty...
> Sending SIGTERM to processes under /media/removable/USB Drive/chroots/trusty...
> chronos@localhost / $ 
#### If known, describe the steps to reproduce the issue:

After getting this up and running, I performed Step 6 of the instructions linked above to pull drivers:
sudo apt-get install software-properties-common python-software-properties
sudo add-apt-repository https://download.01.org/gfx/ubuntu/14.04/main
wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg -O - | sudo apt-key add -
wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg-2 -O - | sudo apt-key add -
sudo apt-get update
sudo apt-get upgrade

I was running after the upgrade, and then I believe I shut down and started successfully, but I can't swear to that. After the error happened, I did update per [https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting), to no effect.

**Comment by lightstrike** [comment]
I was just helping a friend set up a Toshiba 2 and we hit this issue as well. A weird workaround for the moment worked:

1. Press the power button for about a second => screen locks and brings you back to the Chrome OS login
2. Log back into Chrome OS
3. Unity now visible!

Does that work for you too?

**Comment by jbgross** [comment]
I've hit that exact same condition with another install; Unity comes up in a windows, not fullscreen. However, that's not what I'm experiencing here. The process shuts down, so Unity is not running anymore. I did try to lock/unlock, to be on the safe side, but no luck.

I tried a fresh install, identical process, and after Step 6, the same thing happened; unity won't continue running.

I've now installed precise, so we'll see what happens. Since installing a chroot is relatively easy, it's not a huge time investment.

**Comment by jbgross** [comment]
I'm now up and running with precise and XFCE. I had to modify my apt-get repo file, since it looks like 01.org is not consistently organized:
`deb http://archive.ubuntu.com/ubuntu/ precise main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ precise main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse
#deb https://download.01.org/gfx/ubuntu/12.04/main precise main
deb https://download.01.org/gfx/ubuntu/12.04/main Ubuntu 12.04
deb-src https://download.01.org/gfx/ubuntu/12.04/main Ubuntu 12.04
deb-src http://archive.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse
`
This isn't a full solution (I'd rather be on Unity and trusty), but it's workable.

Regardless of the hassle, crouton is awesome. I love this machine. The screen is amazing, as is battery life.

**Comment by Dracos85** [comment]
I am experiencing this same issue.  Im running an HP Chromebook 14.  I have installed and ran trusty with Gnome, Unity, and XFCE just fine, and they work just fine without xiwi.   With xiwi, I get the black screen with all of them but XFCE.  XFCE seems to work fine but seems to be the only one, and like you, I would rather have something else.  So no solutions here, just a note that I did get XFCE and xiwi working with trusty so I dont think it has any relation to whether it is trusty or precise.

**Comment by jbgross** [comment]
Someone indicated that Xenial seems to run fine, and I did a test install and that seems correct; I haven't tried Xiwi, but Unity is running fine. I'll see if I can find that other discussion thread (I thought they were both here, but obviously not). The other thread is critical of 14.X as a platform.

**Comment by rustvariable2** [comment]
Same issue here on an Acer Chromebook 14. Trusty and Xenial worked for five days whether using xiwi to launch a single app in a browser tab, xiwi to launch XFCE in a browser tab, or launching XFCE in a new window without xiwi.

Two days ago, launching of single apps as well as XFCE in a browser tab stopped working with a black screen and "Press F11 to Exit Full Screen" message as described above. Launching XFCE in new window still works for both Trusty and Xenial. 

I was on an island with no cellular or WiFi during the aforementioned five days. Now that I have internet, I'll update all targets and report back.

**Comment by jbgross** [comment]
I'm being very, very cautious with adding software, let alone updating. The machine isn't really vulnerable the way a standing Linux box would be, so I'm not worrying too much. The backup option for edit-chroot works well (it backs up the whole  install to a gzipped tarball). I  know that Ubuntu 12 has a near-future EOL, but I see no reason to upgrade to trusty at all. When I feel like it's stable, I'll upgrade to xenial. My code and data are both backed up (github and dropbox, respectively). 

rustyvariable2, please let me know where you're at. Hopefully we can help keep each other up and running. I thought this was an issue related to the Broadwell architecture, but you're on Airmont (assuming you have this machine: [](https://www.amazon.com/Acer-Chromebook-Aluminum-Quad-Core-CB3-431-C5FM/dp/B01CVOLVPA))

**Comment by rustvariable2** [comment]
Yes, that is the machine. My Trusty chroot starts using either of these two command lines:
sudo enter-chroot -n trusty00 startxfce4
sudo enter-chroot -n trusty00 xiwi -F startxfce4

It does not start using any of these:
sudo enter-chroot -n trusty00 xiwi startxfce4
sudo enter-chroot -n trusty00 xiwi -T startxfce4
sudo enter-chroot -n trusty00 xiwi -f startxfce4

**Comment by rustvariable2** [comment]
Now, two weeks after I wrote the comment above, no more blank screen when I run
sudo enter-chroot -n trusty00 xiwi -T startxfce4. Xfce desktop appears in a new tab no problem.

What's up with that?

**Comment by drinkcat** [comment]
> What's up with that?

Probably magically fixed ,-)

**Comment by jbgross** [comment]
This is not fixed. The user rustvariable2 has an entirely different machine and a different problem. I have this problem to this very day.

**Comment by drinkcat** [comment]
Did you try a xenial chroot?
