### ISSUE TITLE
Search Key Has Stopped Working in Crouton with the  Latest Stable Release of Chrome.

### ISSUE THREAD

**Issue by ianbarton** [dnschneid/crouton#2699]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20160518095657~master:fd37bb79
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,lxde
host: version 8350.60.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jul 20 21:05:40 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
name: xenial-i3
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial-i3...
crouton: version 1-20160715134041~master:0dc76a22
release: xenial
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,lxde
host: version 8350.60.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jul 20 21:05:40 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial-i3...

#### Please describe your issue:
On my Acer c730 the latest stable release of Chrome seems to have disabled the Search key in Crouton (it works fine in Chrome OS).

If I run xev no output is produced, although other keys work as expected. I am using i3 and have stripped my .xinitrc back to a minimum:

setxkbmap gb
exec i3

I am using Ubuntu xenial.

**Comment by ianbarton** [comment]
Just an extra datapoint. I have transferred the chroot to my Tosiba Chromebook 2 and the Search Key is detected by xev.

**Comment by mrvdb** [comment]
I have the same issue on Asus C100PA on chrome beta

**Comment by mwhipple** [comment]
Same issue on an Acer C720: I have Search and Ctrl swapped in ChromeOS resulting in neither `Ctrl` key being picked up by xev in crouton but the Search key sends a 37/Ctrl_L code + sym.

**Comment by mjwhitta** [comment]
I believe this is the same issue as #2639.

**Comment by drinkcat** [comment]
Duping to #2639.
