### ISSUE TITLE
kali rolling installation error

### ISSUE THREAD

**Issue by thejbruu** [dnschneid/crouton#2701]
hey people, firstly i want to say i have seen the recommended steps to fixing this and none have worked.  when trying to install kali rolling it ends with the failure to locate netsurf.  
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
**E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
chronos@localhost / $** 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
thank you in advance for you help

**Comment by DennisLfromGA** [comment]
@thejbruu,

Why open a new issue?
See https://github.com/dnschneid/crouton/issues/2513#issuecomment-230125641

-**DennisL**
