### ISSUE TITLE
kali startup issue

### ISSUE THREAD

**Issue by thejbruu** [dnschneid/crouton#2702]
sorry for 2 issues back to back. dont remember having these issues the last time i installed kali a few months ago. 
anyway, getting this when trying to startup xfce
---------------------------------------------------------------------------------------------------------------------------------------------------------------
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by thejbruu** [comment]
bump someone please help me out with this

**Comment by drinkcat** [comment]
Works fine here... Please reopen with more details if this happens again after a chroot update.
