### ISSUE TITLE
several problems with xfce, xorg

### ISSUE THREAD

**Issue by mark-hahn** [dnschneid/crouton#2703]
### sudo edit-chroot -al

```
###  this is NOT the chroot with the problem.  See chroot `tru` below.

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: amd64
targets: xiwi,keyboard
host: version 8172.62.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 15:29:29 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
name: roo
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/roo...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard
host: version 8172.62.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 15:29:29 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/roo as another instance is using it.

### this is the chroot with the problem

name: tru
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/tru...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,xorg,xiwi,keyboard
host: version 8172.62.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 15:29:29 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/tru...
Failed to unmount /mnt/stateful_partition/crouton/chroots/tru. Kill processes? [a/k/y/p/N] a
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/tru...
name: xf
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xf...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8172.62.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 15:29:29 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xf...

```
#### Please describe your issue:

I have two problems.  This first one can be fixed by deleting  /tmp/Xorg.crouton.1.log.old on every start 
...

> sudo startxfce4
> Entering /mnt/stateful_partition/crouton/chroots/tru...
> /usr/bin/startxfce4: Starting X server
> (EE) 
> Fatal server error:
> (EE) Cannot move old log file "/tmp/Xorg.crouton.1.log" to "/tmp/Xorg.crouton.1.log.old"
> ...
### This second problem is a show-stopper.  I haven't figured out a work-around for this ...

...

> sudo startxfce4
> Entering /mnt/stateful_partition/crouton/chroots/tru...
> /usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 15:29:29 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=3cfbabd8-0e66-1945-b83e-d2635d113c57/PARTNROFF=1 hashtree=PARTUUID=3cfbabd8-0e66-1945-b83e-d2635d113c57/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=1b7d1ce2afee68be622402213dcf669b5c348363 salt=87924df85650ef190ddbe8dc5932776aa3e791f41810da0450917e43eab4c399" noinitrd vt.global_cursor_default=0 kern_guid=3cfbabd8-0e66-1945-b83e-d2635d113c57 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Jul 30 13:10:45 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Unable to open display lock file.
Unable to claim display lock
(EE) 
Fatal server error:
(EE) xf86OpenConsole: VT_ACTIVATE failed: Permission denied
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/tru...
...

I searched for `VT_ACTIVATE` here and there were two people asking about this problem.  In both cases they were asked to do `sudo edit-chroot -al` and neither one responded again.
#### If known, describe the steps to reproduce the issue:

I just installed the chroot with 

```
sudo sh ~/Downloads/crouton -t xiwi,keyboard -r trusty -n tru
```

and then later ...

```
sudo sh ~/Downloads/crouton -t xfce,xorg -u -n tru
```

FWIW, I'm dead in the water since xiwi broke and now I can't get xorg to work.

**Comment by mark-hahn** [comment]
I just tried this from a brand new chroot and got the same results ...

```
sudo sh ~/Downloads/crouton -t xfce,xorg,keyboard -r trusty -n xfc
```

**Comment by ivr588** [comment]
Hi,

For the first problem you describe, I ran as root chmod 777 /tmp/Xorg.crouton.1.log and the problem disappeared.

**Comment by mark-hahn** [comment]
Thx.
