### ISSUE TITLE
xiwi low framerate when not in focus

### ISSUE THREAD

**Issue by qtv** [dnschneid/crouton#2710]
trusty - Ubuntu 14.04 with LXDE
latest chroot/crouton updates
#### Please describe your issue:

When using xiwi for my chroot, when the window is not in focus i.e. when I am browsing Chrome in ChromeOS, any playing video in my xiwi window has its framerate drop significantly. The audio stays the same but the video lags and stutters and generally slows down. The source of the video doesn't matter (smplayer, firefox, etc).

croutonpowerd -i does not help

**Comment by drinkcat** [comment]
That's by design, as there is no way to tell if the xiwi window is totally, or partially, obscured, and we want to save CPU cycles when obscured.

**Comment by drinkcat** [comment]
We could provide some option to keep the framerate high, though.
