### ISSUE TITLE
Virtual Terminal enviornment

### ISSUE THREAD

**Issue by gstoykov88** [dnschneid/crouton#2711]
Hi,

I am no profession or experienced, but I did use to work on Linux when I was younger so I am not a complete newbie.

So to make things quick, I install Cloudready Chromium OS on an old desktop machine of mine out of curiosity and because I am considering buying a Pixel & Chromebox for my new apartment instead of keeping my old desktop.

This desktop has nVidia 520 graphics card, however, installing the supported distro's install the nouveau drivers and I am trying to do some graphic intensive stuff. The drivers don't work well with OpenGL.

So I tried to update my drivers doing the usual
sudo apt-get install nvidia-current
and so on...
However, whatever I do, even when I blacklist nouveau drivers the drivers won't run.

So, I wanted to do a complete purge of the drivers, which means I need to exit graphic environment and work in a virtual terminal and run the nVidia driver install.

However, Ctrl+Alt+F1 obviously doesn't work because its overriden by Chromium.

Is there any work around this?

**Comment by DennisLfromGA** [comment]
In Chrome OS, you can get to VT2 using: <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>F2</kbd>

When logged into your account, you can open a crosh terminal session by using: <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>t</kbd>, then entering `shell`.

I haven't used Chromium in a while so I'm not sure if it supports those key combos.

**Comment by gstoykov88** [comment]
Hi,

I know both of those, however, that isn't what I am asking to.

The VT2 relates to Chromium and not to the installed via crouton linuxes. If it does work for the latter I have no idea how to log in on the specific machine without X.

**Comment by divx118** [comment]
@gstoykov88 Just use `sudo enter-chroot` to get just to the terminal of your chroot.

**Comment by DennisLfromGA** [comment]
Sorry @gstoykov88, I did misunderstand you.
Just do what @divx118 recommended for a non-gui environment.

**Comment by gstoykov88** [comment]
Looks like I can't install the drivers even with entering via chroot

`sudo apt-get --purge remove xserver-xorg-video-nouveau`

says no nouveau drivers are install
killing Xorg also doesn't work

`sudo service lightdm stop`

says service lightdm isn't present

think this is linked to the way crouton works...I suppose the drivers used in Ubuntu for graphics are the one used in ChromeOS or something like that

When I did

`sudo enter-chroot -n ubuntu
sudo killall X`

My ChromeOS X died...I am going to give it one more go, but I think it just cant happen

Has anyone of you had success with installing Nvidia drivers on their linuxes?

**Comment by drinkcat** [comment]
You will probably need kernel support to use the nvidia drivers. This involves building the kernel modules for the Chromium OS kernel.

Doable, but will require some amount of work...

**Comment by drinkcat** [comment]
Duping to #1787.
