### ISSUE TITLE
kali: Enter-Chroot not working 

### ISSUE THREAD

**Issue by Westpanda** [dnschneid/crouton#2712]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

sudo edit-chroot -all -c /media/removable/SD\ Card/ 
name: bin
encrypted: no
Entering /media/removable/SD Card/bin...
/usr/local/bin/enter-chroot: 509: cannot create /run/crouton/media/removable/SD Card/bin/etc/crouton/name: Directory nonexistent
#### Please describe your issue:

I have a installed version of Linux installed on my SSD on my Toshiba chromebook 2015 model, however its just ubuntu and very lightweight and I wanted to get Kali the full package installed so I bought a SD card and have not gotten anything to work so far. This is about my 4th day playing with it and doing a bunch of fixes to get it work, first I had to edit the script for installing xfce because of netsurf and KDE when I tried that was not installing a window manager but telling me xwin was installed when I tried that. Anyways so finally was able to get xfce kali-rolling installed on my SD card, went to launch and extension was not connecting at all, I am not sure how but managed to fix this and so went to launch and got into Kali and was like woah after 2 days progress! 

Went into just normal terminal no startxfce to install full-linux-kali packages and it installed them and was like yah again! now I was having the can not start X server only console users allowed, after some more searching was able to edit the line in config file to say anybody and it started to launch and well thats where I am at now...

It just gives me  the line that says its entering the dir of the chroot and stays there for like 5mins without moving into the chroot at all
( currently tried running it again to get the output and is just nothing now )

So just looking for some help here :)! 

This is going to be a little bit touch and go seeing as there are a lot of fixes and things I have to edit and mess with just to get this far. I am ok with reformating SD all over and starting again as there is nothing inside my Kali at this point but I want to know how to get it to work on the SD because I have formated like multiple times and just kept going at it and so I am asking for help now ^_^

**Comment by Westpanda** [comment]
just rebooted and remounted my SD card and tried again with the following ; 

sudo enter-chroot -c /media/removable/SD\ Card/chroots/ startxfce4
Entering /media/removable/SD Card/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

(EE) 
Fatal server error:
(EE) The '-logfile' option cannot be used with elevated privileges.
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) 
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

**Comment by Westpanda** [comment]
Update : I was able to get the logfile error to be fixed but then the extension was broken again and after trying to edit too many files I felt just best to redo the whole thing and exclude xiwi and the extension for now. 

Going to update after I get everything including full kali packages installed. 

Feel free to close this if you want sorry for wasted internet trees ;)

**Comment by Westpanda** [comment]
Ok so I narrowed it down the problem but not sure why its happening; 
So I did a fresh Kali-Rolling install on my SD card like fresh format fresh and it installed I tested Xfce boom boots up and is fine easy no problem. So I quit out of it and go into just the terminal and no gui and run the apt-get install kali-linux-full and let it go all the way through. After its done i quit again and try to boot with xfce4 again and I get only console users are allowed to start X server and I had to fix this problem before so I knew where to go and what to edit so I edit that to be anybody and try boot again and its telling me

The '-logfile' option cannot be used with elevated privileges.

as why I can not boot... I am too tired and can't think right now to deal with this but any help to get this up and running with FULL kali would be great, seems one of the packages from the full install is breaking the installtion hard.

**Comment by WFTDelta** [comment]
I have the same exact problem. Kali Rolling bare bones runs flawlessly. As soon as I 'apt-get install kali-linux-top10' it's fine and dandy until I shut down. After I reboot its game over. I'm on my 4th installation...I have a TBI so I'm kinda used to things like this being my fault but holy shit 4 times now. No way its just me. 
Westpanda I was also reading to add another line to the config file however it doesnt work for me.

**From another forum:**
One way to fix it:
$cat /etc/X11/Xwrapper.config 
allowed_users = anybody
needs_root_rights = no

**Comment by drinkcat** [comment]
Not quite sure, but I suspect `apt-get install kali-linux-full` resets some configuration files, I'd suggest re-running the installer with `-u` after doing that.

**Comment by dnschneid** [comment]
#2875
