### ISSUE TITLE
Kali 

### ISSUE THREAD

**Issue by axeeon** [dnschneid/crouton#2713]
```
No chroots found in /mnt/stateful_partition/crouton/chroots
```

#### Please describe your issue:
Trying to install Kali but 404 no dists found. https://www.kali.org/dists/ 
is there a way to edit the crouton to look for the dists in a new area?

#### If known, describe the steps to reproduce the issue:
sudo sh crouton -r kali-rolling -t xiwi,xfce

**Comment by drinkcat** [comment]
Hard to tell without more details...
