### ISSUE TITLE
UID 000 not found in trusty

### ISSUE THREAD

**Issue by peacock17** [dnschneid/crouton#2714]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
targets: xfce
host: version 8350.68.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:11:23 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
#### Please describe your issue:
I'm completely new to this, any help would be appericated. I've been trying to download steam.

**Comment by drinkcat** [comment]
Not sure what's the problem here.

Please provide more info and reopen if necessary.
