### ISSUE TITLE
Sound/Microphone Not Working in Zoom.us with Cras on Ubuntu 16.04

### ISSUE THREAD

**Issue by zkrebs** [dnschneid/crouton#2715]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20160715134041~master:0dc76a22
release: xenial
architecture: amd64
xmethod: xorg
targets: lxde
host: version 8673.0.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Aug 4 02:51:42 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

```
#### Please describe your issue:

I can not get the sound/microphone to work in the Zoom.US client (http://www.zoom.us/download). No volume or mic input is registered, no other choices are available.

![screenshot from 2016-08-09 18-46-23](https://cloud.githubusercontent.com/assets/366418/17539254/a0e8e534-5e61-11e6-8553-04baad238de7.png)

![screenshot from 2016-08-09 18-47-20](https://cloud.githubusercontent.com/assets/366418/17539266/bb548e3c-5e61-11e6-98fe-d0f8a21ed435.png)

![screenshot from 2016-08-09 18-48-07](https://cloud.githubusercontent.com/assets/366418/17539284/d6d72a66-5e61-11e6-9cb7-dd86f4c8038e.png)
#### If known, describe the steps to reproduce the issue:

Install Ubuntu Xenial fresh chroot, download Zoom.us from zoom.us/download and pick Ubuntu. Install, and then run. Try to join/host meeting.

**Comment by drinkcat** [comment]
If `aplay -f dat /dev/urandom` and `arecord -f dat | aplay -` work (it does for me on xenial, at least when pulseaudio is installed), then it's probably an application issue.

**Comment by gsf** [comment]
Works for me in xorg but not xiwi.

**Comment by lap91** [comment]
Works for me on trusty 64bit on Acer Chromebook 14 CB3-431 (Edgar) after a fresh install. Couldn't get the `zoom_amd64.deb` package to work for other reasons, was getting this error on startup:

`/opt/zoom/zoom: error while loading shared libraries: libsmime3.so: cannot open shared object file: No such file or directory
`

`zoom_i386.deb` works great though!
