### ISSUE TITLE
Problem installing kali-rolling on samsung chromebook!

### ISSUE THREAD

**Issue by butters22** [dnschneid/crouton#2716]
```
chronos@localhost / $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
Creating hwaudio group with GID 18...
Changing audio GID from 29 to 600...
Changing cdrom GID from 24 to 19...
Creating devbroker-access group with GID 403...
Changing floppy GID from 25 to 11...
Creating i2c group with GID 404...
Creating input group with GID 222...
Creating serial group with GID 402...
Changing plugdev GID from 46 to 85...
Changing uucp GID from 10 to 14...
Changing video GID from 44 to 27...
Moving sudo GID from 27 to 28...
crouton: version unknown
release: unknown
architecture: unknown
targets: xfce
host: version 8350.68.0 (Official Build) stable-channel x86-alex_he 
kernel: Linux localhost 3.8.11 #1 SMP Tue Aug 2 21:02:54 PDT 2016 i686 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:

Every time I try installing kali-rolling with xfce on my samsung chromebook, I make it all the way until where it starts unpacking the base system, and then I get an error...

Here is the output when I type "sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce":

chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
Downloading latest crouton installer...
######################################################################## 100.0%
Installing kali-rolling-i386 chroot to /usr/local/chroots/kali-rolling
Downloading latest debootstrap...
2016-08-10 00:50:38 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [64429] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving Release 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: insserv libaudit1 libaudit-common libbz2-1.0 libcap-ng0 libdb5.3 libdebconfclient0 libgcrypt20 libgpg-error0 liblocale-gettext-perl libncursesw5 libsemanage1 libsemanage-common libsystemd0 libudev1 libustr-1.0-1 startpar 
I: Found additional base dependencies: dmsetup libapparmor1 libbsd0 libcap2 libcap2-bin libcryptsetup4 libdevmapper1.02.1 libdns-export162 libffi6 libgmp10 libgnutls30 libhogweed4 libicu55 libidn11 libip4tc0 libip6tc0 libiptc0 libisc-export160 libjson-c3 liblz4-1 libmnl0 libnetfilter-acct1 libnetfilter-conntrack3 libnettle6 libnfnetlink0 libp11-kit0 libpsl0 libseccomp2 libtasn1-6 
I: Checking component main on http://http.kali.org...
I: Retrieving adduser 3.115
I: Validating adduser 3.115
I: Retrieving apt 1.3~pre2
I: Validating apt 1.3~pre2
I: Retrieving apt-utils 1.3~pre2
I: Validating apt-utils 1.3~pre2
I: Retrieving base-files 1:2016.2.1
I: Validating base-files 1:2016.2.1
I: Retrieving base-passwd 3.5.39
I: Validating base-passwd 3.5.39
I: Retrieving bash 4.3-15
I: Validating bash 4.3-15
I: Retrieving blends-tasks 0.6.93
I: Validating blends-tasks 0.6.93
I: Retrieving bsdmainutils 9.0.10
I: Validating bsdmainutils 9.0.10
I: Retrieving bsdutils 1:2.28-6
I: Validating bsdutils 1:2.28-6
I: Retrieving coreutils 8.25-2
I: Validating coreutils 8.25-2
I: Retrieving cpio 2.11+dfsg-5
I: Validating cpio 2.11+dfsg-5
I: Retrieving cron 3.0pl1-128
I: Validating cron 3.0pl1-128
I: Retrieving dash 0.5.8-2.3
I: Validating dash 0.5.8-2.3
I: Retrieving debconf 1.5.59
I: Validating debconf 1.5.59
I: Retrieving debconf-i18n 1.5.59
I: Validating debconf-i18n 1.5.59
I: Retrieving debian-archive-keyring 2014.3
I: Validating debian-archive-keyring 2014.3
I: Retrieving debianutils 4.8
I: Validating debianutils 4.8
I: Retrieving diffutils 1:3.3-3
I: Validating diffutils 1:3.3-3
I: Retrieving dmidecode 3.0-3
I: Validating dmidecode 3.0-3
I: Retrieving dmsetup 2:1.02.130-1
I: Validating dmsetup 2:1.02.130-1
I: Retrieving dpkg 1.18.10
I: Validating dpkg 1.18.10
I: Retrieving e2fslibs 1.43.1-1
I: Validating e2fslibs 1.43.1-1
I: Retrieving e2fsprogs 1.43.1-1
I: Validating e2fsprogs 1.43.1-1
I: Retrieving findutils 4.6.0+git+20160703-2
I: Validating findutils 4.6.0+git+20160703-2
I: Retrieving gcc-4.9-base 4.9.3-14
I: Validating gcc-4.9-base 4.9.3-14
I: Retrieving gcc-5-base 5.4.0-6
I: Validating gcc-5-base 5.4.0-6
I: Retrieving gcc-6-base 6.1.1-10
I: Validating gcc-6-base 6.1.1-10
I: Retrieving gnupg 1.4.20-6
I: Validating gnupg 1.4.20-6
I: Retrieving gpgv 1.4.20-6
I: Validating gpgv 1.4.20-6
I: Retrieving grep 2.25-6
I: Validating grep 2.25-6
I: Retrieving gzip 1.6-5
I: Validating gzip 1.6-5
I: Retrieving hostname 3.18
I: Validating hostname 3.18
I: Retrieving ifupdown 0.8.13
I: Validating ifupdown 0.8.13
I: Retrieving init 1.37kali1
I: Validating init 1.37kali1
I: Retrieving init-system-helpers 1.37kali1
I: Validating init-system-helpers 1.37kali1
I: Retrieving initscripts 2.88dsf-59.8
I: Validating initscripts 2.88dsf-59.8
I: Retrieving insserv 1.14.0-5.4
I: Validating insserv 1.14.0-5.4
I: Retrieving iproute2 4.6.0-1
I: Validating iproute2 4.6.0-1
I: Retrieving iptables 1.6.0-3
I: Validating iptables 1.6.0-3
I: Retrieving iputils-ping 3:20150815-2
I: Validating iputils-ping 3:20150815-2
I: Retrieving isc-dhcp-client 4.3.4-1
I: Validating isc-dhcp-client 4.3.4-1
I: Retrieving isc-dhcp-common 4.3.4-1
I: Validating isc-dhcp-common 4.3.4-1
I: Retrieving kali-archive-keyring 2015.2
I: Validating kali-archive-keyring 2015.2
I: Retrieving kmod 22-1.1
I: Validating kmod 22-1.1
I: Retrieving libacl1 2.2.52-3
I: Validating libacl1 2.2.52-3
I: Retrieving libapparmor1 2.10.95-4
I: Validating libapparmor1 2.10.95-4
I: Retrieving libapt-inst2.0 1.3~pre2
I: Validating libapt-inst2.0 1.3~pre2
I: Retrieving libapt-pkg5.0 1.3~pre2
I: Validating libapt-pkg5.0 1.3~pre2
I: Retrieving libattr1 1:2.4.47-2
I: Validating libattr1 1:2.4.47-2
I: Retrieving libaudit-common 1:2.6.5-1
I: Validating libaudit-common 1:2.6.5-1
I: Retrieving libaudit1 1:2.6.5-1
I: Validating libaudit1 1:2.6.5-1
I: Retrieving libblkid1 2.28-6
I: Validating libblkid1 2.28-6
I: Retrieving libboost-iostreams1.58.0 1.58.0+dfsg-5.1
I: Validating libboost-iostreams1.58.0 1.58.0+dfsg-5.1
I: Retrieving libboost-iostreams1.60.0 1.60.0+dfsg-6+b1
I: Validating libboost-iostreams1.60.0 1.60.0+dfsg-6+b1
I: Retrieving libboost-iostreams1.61.0 1.61.0+dfsg-2.1
I: Validating libboost-iostreams1.61.0 1.61.0+dfsg-2.1
I: Retrieving libbsd0 0.8.3-1
I: Validating libbsd0 0.8.3-1
I: Retrieving libbz2-1.0 1.0.6-8
I: Validating libbz2-1.0 1.0.6-8
I: Retrieving libc-bin 2.23-4
I: Validating libc-bin 2.23-4
I: Retrieving libc6 2.23-4
I: Validating libc6 2.23-4
I: Retrieving libcap-ng0 0.7.7-3
I: Validating libcap-ng0 0.7.7-3
I: Retrieving libcap2 1:2.25-1
I: Validating libcap2 1:2.25-1
I: Retrieving libcap2-bin 1:2.25-1
I: Validating libcap2-bin 1:2.25-1
I: Retrieving libcomerr2 1.43.1-1
I: Validating libcomerr2 1.43.1-1
I: Retrieving libcryptsetup4 2:1.7.0-2kali1
I: Validating libcryptsetup4 2:1.7.0-2kali1
I: Retrieving libdb5.3 5.3.28-12
I: Validating libdb5.3 5.3.28-12
I: Retrieving libdebconfclient0 0.215
I: Validating libdebconfclient0 0.215
I: Retrieving libdevmapper1.02.1 2:1.02.130-1
I: Validating libdevmapper1.02.1 2:1.02.130-1
I: Retrieving libdns-export162 1:9.10.3.dfsg.P4-10.1
I: Validating libdns-export162 1:9.10.3.dfsg.P4-10.1
I: Retrieving libestr0 0.1.10-2
I: Validating libestr0 0.1.10-2
I: Retrieving libfdisk1 2.28-6
I: Validating libfdisk1 2.28-6
I: Retrieving libffi6 3.2.1-4
I: Validating libffi6 3.2.1-4
I: Retrieving libgcc1 1:6.1.1-10
I: Validating libgcc1 1:6.1.1-10
I: Retrieving libgcrypt20 1.7.2-2
I: Validating libgcrypt20 1.7.2-2
I: Retrieving libgdbm3 1.8.3-14
I: Validating libgdbm3 1.8.3-14
I: Retrieving libgmp10 2:6.1.1+dfsg-1
I: Validating libgmp10 2:6.1.1+dfsg-1
I: Retrieving libgnutls30 3.5.2-2
I: Validating libgnutls30 3.5.2-2
I: Retrieving libgpg-error0 1.24-1
I: Validating libgpg-error0 1.24-1
I: Retrieving libhogweed4 3.2-1
I: Validating libhogweed4 3.2-1
I: Retrieving libicu55 55.1-7
I: Validating libicu55 55.1-7
I: Retrieving libidn11 1.33-1
I: Validating libidn11 1.33-1
I: Retrieving libip4tc0 1.6.0-3
I: Validating libip4tc0 1.6.0-3
I: Retrieving libip6tc0 1.6.0-3
I: Validating libip6tc0 1.6.0-3
I: Retrieving libiptc0 1.6.0-3
I: Validating libiptc0 1.6.0-3
I: Retrieving libisc-export160 1:9.10.3.dfsg.P4-10.1
I: Validating libisc-export160 1:9.10.3.dfsg.P4-10.1
I: Retrieving libjson-c3 0.12-3
I: Validating libjson-c3 0.12-3
I: Retrieving libkmod2 22-1.1
I: Validating libkmod2 22-1.1
I: Retrieving liblocale-gettext-perl 1.07-3
I: Validating liblocale-gettext-perl 1.07-3
I: Retrieving liblogging-stdlog0 1.0.5-2
I: Validating liblogging-stdlog0 1.0.5-2
I: Retrieving liblognorm2 1.1.2-1.1+b2
I: Validating liblognorm2 1.1.2-1.1+b2
I: Retrieving liblz4-1 0.0~r131-2
I: Validating liblz4-1 0.0~r131-2
I: Retrieving liblzma5 5.1.1alpha+20120614-2.1
I: Validating liblzma5 5.1.1alpha+20120614-2.1
I: Retrieving libmnl0 1.0.3-5
I: Validating libmnl0 1.0.3-5
I: Retrieving libmount1 2.28-6
I: Validating libmount1 2.28-6
I: Retrieving libncurses5 6.0+20160625-1
I: Validating libncurses5 6.0+20160625-1
I: Retrieving libncursesw5 6.0+20160625-1
I: Validating libncursesw5 6.0+20160625-1
I: Retrieving libnetfilter-acct1 1.0.2-1.1
I: Validating libnetfilter-acct1 1.0.2-1.1
I: Retrieving libnetfilter-conntrack3 1.0.5-1
I: Validating libnetfilter-conntrack3 1.0.5-1
I: Retrieving libnettle6 3.2-1
I: Validating libnettle6 3.2-1
I: Retrieving libnewt0.52 0.52.18-3
I: Validating libnewt0.52 0.52.18-3
I: Retrieving libnfnetlink0 1.0.1-3
I: Validating libnfnetlink0 1.0.1-3
I: Retrieving libp11-kit0 0.23.2-4
I: Validating libp11-kit0 0.23.2-4
I: Retrieving libpam-modules 1.1.8-3.3
I: Validating libpam-modules 1.1.8-3.3
I: Retrieving libpam-modules-bin 1.1.8-3.3
I: Validating libpam-modules-bin 1.1.8-3.3
I: Retrieving libpam-runtime 1.1.8-3.3
I: Validating libpam-runtime 1.1.8-3.3
I: Retrieving libpam0g 1.1.8-3.3
I: Validating libpam0g 1.1.8-3.3
I: Retrieving libpcre3 2:8.39-1
I: Validating libpcre3 2:8.39-1
I: Retrieving libpipeline1 1.4.1-2
I: Validating libpipeline1 1.4.1-2
I: Retrieving libpopt0 1.16-10
I: Validating libpopt0 1.16-10
I: Retrieving libprocps6 2:3.3.12-2
I: Validating libprocps6 2:3.3.12-2
I: Retrieving libpsl0 0.11.0-2
I: Validating libpsl0 0.11.0-2
I: Retrieving libreadline6 6.3-8+b4
I: Validating libreadline6 6.3-8+b4
I: Retrieving libseccomp2 2.3.1-2
I: Validating libseccomp2 2.3.1-2
I: Retrieving libselinux1 2.5-3
I: Validating libselinux1 2.5-3
I: Retrieving libsemanage-common 2.5-1
I: Validating libsemanage-common 2.5-1
I: Retrieving libsemanage1 2.5-1
I: Validating libsemanage1 2.5-1
I: Retrieving libsepol1 2.5-1
I: Validating libsepol1 2.5-1
I: Retrieving libslang2 2.3.0-3
I: Validating libslang2 2.3.0-3
I: Retrieving libsmartcols1 2.28-6
I: Validating libsmartcols1 2.28-6
I: Retrieving libss2 1.43.1-1
I: Validating libss2 1.43.1-1
I: Retrieving libssl1.0.2 1.0.2h-1
I: Validating libssl1.0.2 1.0.2h-1
I: Retrieving libstdc++6 6.1.1-10
I: Validating libstdc++6 6.1.1-10
I: Retrieving libsystemd0 230-7
I: Validating libsystemd0 230-7
I: Retrieving libtasn1-6 4.8-1
I: Validating libtasn1-6 4.8-1
I: Retrieving libtext-charwidth-perl 0.04-7+b4
I: Validating libtext-charwidth-perl 0.04-7+b4
I: Retrieving libtext-iconv-perl 1.7-5+b3
I: Validating libtext-iconv-perl 1.7-5+b3
I: Retrieving libtext-wrapi18n-perl 0.06-7.1
I: Validating libtext-wrapi18n-perl 0.06-7.1
I: Retrieving libtinfo5 6.0+20160625-1
I: Validating libtinfo5 6.0+20160625-1
I: Retrieving libudev1 230-7
I: Validating libudev1 230-7
I: Retrieving libusb-0.1-4 2:0.1.12-30
I: Validating libusb-0.1-4 2:0.1.12-30
I: Retrieving libustr-1.0-1 1.0.4-5
I: Validating libustr-1.0-1 1.0.4-5
I: Retrieving libuuid1 2.28-6
I: Validating libuuid1 2.28-6
I: Retrieving libxapian22v5 1.2.23-1
I: Validating libxapian22v5 1.2.23-1
I: Retrieving libxtables11 1.6.0-3
I: Validating libxtables11 1.6.0-3
I: Retrieving login 1:4.2-3.1
I: Validating login 1:4.2-3.1
I: Retrieving logrotate 3.8.7-2
I: Validating logrotate 3.8.7-2
I: Retrieving lsb-base 9.20160629
I: Validating lsb-base 9.20160629
I: Retrieving mawk 1.3.3-17
I: Validating mawk 1.3.3-17
I: Retrieving mount 2.28-6
I: Validating mount 2.28-6
I: Retrieving multiarch-support 2.23-4
I: Validating multiarch-support 2.23-4
I: Retrieving nano 2.6.2-1
I: Validating nano 2.6.2-1
I: Retrieving ncurses-base 6.0+20160625-1
I: Validating ncurses-base 6.0+20160625-1
I: Retrieving ncurses-bin 6.0+20160625-1
I: Validating ncurses-bin 6.0+20160625-1
I: Retrieving net-tools 1.60+git20150829.73cef8a-2
I: Validating net-tools 1.60+git20150829.73cef8a-2
I: Retrieving netbase 5.3
I: Validating netbase 5.3
I: Retrieving netcat-traditional 1.10-41
I: Validating netcat-traditional 1.10-41
I: Retrieving nfacct 1.0.1-1.1
I: Validating nfacct 1.0.1-1.1
I: Retrieving passwd 1:4.2-3.1
I: Validating passwd 1:4.2-3.1
I: Retrieving paxctld 1.1-1
I: Validating paxctld 1.1-1
I: Retrieving perl-base 5.22.2-3
I: Validating perl-base 5.22.2-3
I: Retrieving procps 2:3.3.12-2
I: Validating procps 2:3.3.12-2
I: Retrieving readline-common 6.3-8
I: Validating readline-common 6.3-8
I: Retrieving rsyslog 8.16.0-1+b3
I: Validating rsyslog 8.16.0-1+b3
I: Retrieving sed 4.2.2-7.1
I: Validating sed 4.2.2-7.1
I: Retrieving sensible-utils 0.0.9
I: Validating sensible-utils 0.0.9
I: Retrieving startpar 0.59-3.1
I: Validating startpar 0.59-3.1
I: Retrieving systemd 230-7
I: Validating systemd 230-7
I: Retrieving systemd-sysv 230-7
I: Validating systemd-sysv 230-7
I: Retrieving sysv-rc 2.88dsf-59.8
I: Validating sysv-rc 2.88dsf-59.8
I: Retrieving sysvinit-utils 2.88dsf-59.8
I: Validating sysvinit-utils 2.88dsf-59.8
I: Retrieving tar 1.29b-1
I: Validating tar 1.29b-1
I: Retrieving tasksel 3.35
I: Validating tasksel 3.35
I: Retrieving tasksel-data 3.35
I: Validating tasksel-data 3.35
I: Retrieving tzdata 2016f-1
I: Validating tzdata 2016f-1
I: Retrieving udev 230-7
I: Validating udev 230-7
I: Retrieving util-linux 2.28-6
I: Validating util-linux 2.28-6
I: Retrieving vim-common 2:7.4.1829-1
I: Validating vim-common 2:7.4.1829-1
I: Retrieving vim-tiny 2:7.4.1829-1
I: Validating vim-tiny 2:7.4.1829-1
I: Retrieving wget 1.18-2
I: Validating wget 1.18-2
I: Retrieving whiptail 0.52.18-3
I: Validating whiptail 0.52.18-3
I: Retrieving zlib1g 1:1.2.8.dfsg-2+b1
I: Validating zlib1g 1:1.2.8.dfsg-2+b1
I: Chosen extractor for .deb packages: ar
I: Extracting base-files...
I: Extracting base-passwd...
I: Extracting bash...
I: Extracting bsdutils...
I: Extracting coreutils...
I: Extracting dash...
I: Extracting debconf...
I: Extracting debconf-i18n...
I: Extracting debianutils...
I: Extracting diffutils...
I: Extracting dpkg...
I: Extracting e2fslibs...
I: Extracting e2fsprogs...
I: Extracting findutils...
I: Extracting gcc-4.9-base...
I: Extracting gcc-5-base...
I: Extracting gcc-6-base...
I: Extracting grep...
I: Extracting gzip...
I: Extracting hostname...
I: Extracting init-system-helpers...
I: Extracting initscripts...
I: Extracting insserv...
I: Extracting libacl1...
I: Extracting libattr1...
I: Extracting libaudit-common...
I: Extracting libaudit1...
I: Extracting libblkid1...
I: Extracting libbz2-1.0...
I: Extracting libc-bin...
I: Extracting libc6...
I: Extracting libcap-ng0...
I: Extracting libcomerr2...
I: Extracting libdb5.3...
I: Extracting libdebconfclient0...
I: Extracting libfdisk1...
I: Extracting libgcc1...
I: Extracting libgcrypt20...
I: Extracting libgpg-error0...
I: Extracting liblocale-gettext-perl...
I: Extracting liblzma5...
I: Extracting libmount1...
I: Extracting libncurses5...
I: Extracting libncursesw5...
I: Extracting libpam-modules...
I: Extracting libpam-modules-bin...
I: Extracting libpam-runtime...
I: Extracting libpam0g...
I: Extracting libpcre3...
I: Extracting libselinux1...
I: Extracting libsemanage-common...
I: Extracting libsemanage1...
I: Extracting libsepol1...
I: Extracting libsmartcols1...
I: Extracting libss2...
I: Extracting libsystemd0...
I: Extracting libtext-charwidth-perl...
I: Extracting libtext-iconv-perl...
I: Extracting libtext-wrapi18n-perl...
I: Extracting libtinfo5...
I: Extracting libudev1...
I: Extracting libustr-1.0-1...
I: Extracting libuuid1...
I: Extracting login...
I: Extracting lsb-base...
I: Extracting mawk...
I: Extracting mount...
I: Extracting multiarch-support...
I: Extracting ncurses-base...
I: Extracting ncurses-bin...
I: Extracting passwd...
I: Extracting perl-base...
I: Extracting sed...
I: Extracting sensible-utils...
I: Extracting startpar...
I: Extracting sysv-rc...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting util-linux...
I: Extracting zlib1g...
Moving bootstrap files into the chroot...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
I: Installing core packages...
I: Unpacking required packages...
I: Unpacking base-files...
I: Unpacking base-passwd...
I: Unpacking bash...
I: Unpacking bsdutils...
I: Unpacking coreutils...
I: Unpacking dash...
I: Unpacking debconf...
I: Unpacking debconf-i18n...
I: Unpacking debianutils...
I: Unpacking diffutils...
I: Unpacking dpkg...
I: Unpacking e2fslibs:i386...
I: Unpacking e2fsprogs...
I: Unpacking findutils...
I: Unpacking gcc-4.9-base:i386...
I: Unpacking gcc-5-base:i386...
I: Unpacking gcc-6-base:i386...
I: Unpacking grep...
I: Unpacking gzip...
I: Unpacking hostname...
I: Unpacking init-system-helpers...
I: Unpacking initscripts...
I: Unpacking insserv...
I: Unpacking libacl1:i386...
I: Unpacking libattr1:i386...
I: Unpacking libaudit-common...
I: Unpacking libaudit1:i386...
I: Unpacking libblkid1:i386...
I: Unpacking libbz2-1.0:i386...
I: Unpacking libc-bin...
I: Unpacking libc6:i386...
I: Unpacking libcap-ng0:i386...
I: Unpacking libcomerr2:i386...
I: Unpacking libdb5.3:i386...
I: Unpacking libdebconfclient0:i386...
I: Unpacking libfdisk1:i386...
I: Unpacking libgcc1:i386...
I: Unpacking libgcrypt20:i386...
I: Unpacking libgpg-error0:i386...
I: Unpacking liblocale-gettext-perl...
I: Unpacking liblzma5:i386...
I: Unpacking libmount1:i386...
I: Unpacking libncurses5:i386...
I: Unpacking libncursesw5:i386...
I: Unpacking libpam-modules:i386...
I: Unpacking libpam-modules-bin...
I: Unpacking libpam-runtime...
I: Unpacking libpam0g:i386...
I: Unpacking libpcre3:i386...
I: Unpacking libselinux1:i386...
I: Unpacking libsemanage-common...
I: Unpacking libsemanage1:i386...
I: Unpacking libsepol1:i386...
I: Unpacking libsmartcols1:i386...
I: Unpacking libss2:i386...
I: Unpacking libsystemd0:i386...
I: Unpacking libtext-charwidth-perl...
I: Unpacking libtext-iconv-perl...
I: Unpacking libtext-wrapi18n-perl...
I: Unpacking libtinfo5:i386...
I: Unpacking libudev1:i386...
I: Unpacking libustr-1.0-1:i386...
I: Unpacking libuuid1:i386...
I: Unpacking login...
I: Unpacking lsb-base...
I: Unpacking mawk...
I: Unpacking mount...
I: Unpacking multiarch-support...
I: Unpacking ncurses-base...
I: Unpacking ncurses-bin...
I: Unpacking passwd...
I: Unpacking perl-base...
I: Unpacking sed...
I: Unpacking sensible-utils...
I: Unpacking startpar...
I: Unpacking sysv-rc...
I: Unpacking sysvinit-utils...
I: Unpacking tar...
I: Unpacking tzdata...
I: Unpacking util-linux...
I: Unpacking zlib1g:i386...
I: Configuring required packages...
I: Configuring gcc-6-base:i386...
I: Configuring lsb-base...
I: Configuring sensible-utils...
I: Configuring ncurses-base...
I: Configuring libsemanage-common...
I: Configuring gcc-4.9-base:i386...
I: Configuring libaudit-common...
I: Configuring gcc-5-base:i386...
I: Configuring libc6:i386...
I: Configuring startpar...
I: Configuring libbz2-1.0:i386...
I: Configuring libgpg-error0:i386...
I: Configuring libc-bin...
I: Configuring libdebconfclient0:i386...
I: Configuring diffutils...
I: Configuring insserv...
I: Configuring libcomerr2:i386...
I: Configuring libcap-ng0:i386...
I: Configuring libsepol1:i386...
I: Configuring libgcc1:i386...
I: Configuring libustr-1.0-1:i386...
I: Configuring libsmartcols1:i386...
I: Configuring libaudit1:i386...
I: Configuring libtinfo5:i386...
I: Configuring libudev1:i386...
I: Configuring libss2:i386...
I: Configuring liblzma5:i386...
I: Configuring base-passwd...
I: Configuring e2fslibs:i386...
I: Configuring debianutils...
I: Configuring libgcrypt20:i386...
I: Configuring libncursesw5:i386...
I: Configuring libdb5.3:i386...
I: Configuring hostname...
I: Configuring multiarch-support...
I: Configuring mawk...
I: Configuring libpcre3:i386...
I: Configuring base-files...
I: Configuring libselinux1:i386...
I: Configuring findutils...
I: Configuring ncurses-bin...
I: Configuring libncurses5:i386...
I: Configuring libattr1:i386...
I: Configuring zlib1g:i386...
I: Configuring libsystemd0:i386...
I: Configuring libsemanage1:i386...
I: Configuring libacl1:i386...
I: Configuring bsdutils...
I: Configuring coreutils...
I: Configuring tar...
I: Configuring dpkg...
I: Configuring sed...
I: Configuring perl-base...
I: Configuring grep...
I: Configuring debconf...
I: Configuring tzdata...
I: Configuring gzip...
I: Configuring dash...
I: Configuring init-system-helpers...
I: Configuring libtext-iconv-perl...
I: Configuring liblocale-gettext-perl...
I: Configuring libtext-charwidth-perl...
I: Configuring libpam0g:i386...
I: Configuring libpam-modules-bin...
I: Configuring bash...
I: Configuring libtext-wrapi18n-perl...
I: Configuring libpam-modules:i386...
I: Configuring libpam-runtime...
I: Configuring debconf-i18n...
I: Configuring passwd...
I: Configuring login...
I: Configuring libuuid1:i386...
I: Configuring libblkid1:i386...
I: Configuring libmount1:i386...
I: Configuring mount...
I: Configuring libfdisk1:i386...
I: Configuring util-linux...
I: Configuring e2fsprogs...
I: Configuring sysvinit-utils...
I: Configuring sysv-rc...
I: Configuring initscripts...
I: Configuring libc-bin...
**I: Unpacking the base system...**
W: Failure trying to run:  dpkg --force-overwrite --force-confold --skip-same-version --install /var/cache/apt/archives/adduser_3.115_all.deb /var/cache/apt/archives/dmsetup_2%3a1.02.130-1_i386.deb /var/cache/apt/archives/libapparmor1_2.10.95-4_i386.deb /var/cache/apt/archives/libcap2_1%3a2.25-1_i386.deb /var/cache/apt/archives/libcap2-bin_1%3a2.25-1_i386.deb /var/cache/apt/archives/libcryptsetup4_2%3a1.7.0-2kali1_i386.deb /var/cache/apt/archives/libdevmapper1.02.1_2%3a1.02.130-1_i386.deb /var/cache/apt/archives/libidn11_1.33-1_i386.deb /var/cache/apt/archives/libkmod2_22-1.1_i386.deb /var/cache/apt/archives/libseccomp2_2.3.1-2_i386.deb /var/cache/apt/archives/systemd_230-7_i386.deb
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### If known, describe the steps to reproduce the issue:

To reproduce just type "sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce"

By the way sorry if this post sucks, it's my first post...

**Comment by butters22** [comment]
By the way I bolder where I thought the problem was...

**Comment by redengin** [comment]
I'm getting the same error on a Samsung Chromebook XE500C21.  I've tried fixing things from within the chroot, but the failure comes so early that tools like editors, apt-get, etc. haven't been added to the chroot yet.

**Comment by redengin** [comment]
As a workaround, sana installed fine, and then I did the dist-upgrade to move onto kali rolling

cat << EOF > /etc/apt/sources.list
deb http://http.kali.org/kali kali-rolling main non-free contrib
EOF

apt-get update
apt-get dist-upgrade # get a coffee, or 10.
reboot

**Comment by butters22** [comment]
I tried rebooting it but it wouldn't let me since sana was running in crouton... Should I just restart it from the top right where you can choose to log out?

**Comment by redengin** [comment]
Sorry, I just copy-pasted that from the kali linux page.  Just restart the container rather than reboot.  I'm not entirely sure it even requires that you restart the container- but it can't hurt.

**Comment by butters22** [comment]
Alright, thanks. Is it possible you could give me a tutorial on how to do a live usb install of Kali rolling on my chrome book. I know once your chromebook is in developer mode you can enable usb booting. I just need help with what to do... I'm pretty sure you have to download the ARM image from the Kali site and then use the dd utility to image it to the usb. If you know how a tutorial would be well appreciated :).

**Comment by drinkcat** [comment]
Works fine here with the latest crouton, I don't know what's wrong. Maybe some transient issue? I'd suggest starting from scratch.
