### ISSUE TITLE
UID 1000 not found in jessie

### ISSUE THREAD

**Issue by Ajacmac** [dnschneid/crouton#2718]
name: jessie
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/jessie...
crouton: version 1-20160715134041~master:0dc76a22
release: jessie
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8350.68.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:08:34 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/jessie...

When I try to enter the chroot I see UID 1000 not found in jessie and it kicks me back out, I can't get in to make any fixes, etc.

#### If known, describe the steps to reproduce the issue:

I made a new chroot with sudo sh ~/Downloads/crouton -t xfce -r jessie
When it finished I entered the chroot and it said "a chroot setup script still exists inside the chroot"
and asked me if I wanted to run the script, I said yes and it did a whole bunch more stuff, then when it finished I tried to enter the chroot and got the above error.

**Comment by DennisLfromGA** [comment]
@Ajacmac,

It sounds like the installation aborted at an early point and no user id was created.

You could just attempt to update it via crouton using: 
 `sudo sh ~/Downloads/crouton -n jessie -u`

Or you could *try* to fix it as root from inside the chroot using:
 `sudo enter-chroot -u root -n jessie`
 `sudo apt-get install -f`
 `sudo apt-get update`
 `sudo apt-get upgrade`
 `exit`

and see if that fixes it.

I would try the crouton update method first though.

-**DennisL**
