### ISSUE TITLE
Kde needs password

### ISSUE THREAD

**Issue by zpmatm** [dnschneid/crouton#2719]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t kde

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
#### Please describe your issue:
What is the password?

#### If known, describe the steps to reproduce the issue:
Typing the commands
![screenshot 2016-08-11 at 10 32 49 pm](https://cloud.githubusercontent.com/assets/18463644/17612132/236e9b28-6003-11e6-811c-f222e3fb79df.png)

**Comment by davidlowryduda** [comment]
By default, there is not password unless you made a password, either at developer-mode setup or later. So I'm afraid that you won't find much help here.

**Comment by Qetar** [comment]
thanks for the help i found out you need to powerwash then allow developer mode and create your root passwod then go on VT2 and make a password by using username root and whatever password you made to allow root access and there is a command there to show you above how to set chrome password its chromeos-setdevpasswd and its set.
