### ISSUE TITLE
/org Missing in Xenial (Unity)

### ISSUE THREAD

**Issue by msolters** [dnschneid/crouton#2720]
Hi, I've managed to get Unity working in Xenial.  I did not use the `unity` target, but rather, entered the chroot and manually `sudo apt-get install ubuntu-destop`.

Then, I can start a working Unity session using `sudo xinit unity`.  This requires the `x11` target.
## Problem

It works almost perfectly!  There's some weird glitches that I'm trying to iron out.  It seems the errors that occur mostly all mention the keyword `org`.

Researching, I found similar issues where users had reset using e.g.

```
sudo dconf reset -f /org/compiz/
```

But, it seems the issue boils down to the fact that the `/org` directory does not exist!

Now, I am not an expert on the window managers.  **What package would I be looking for that is responsible for generating this `/org` directory?**
## Things I Have Tried
-  I have tried adding the `xorg` target but it does not help.
-  I have tried reinstalling basically anything to do with Unity (`ubuntu-desktop`, `unity`, `compiz`, etc.)  Does not help.

**Comment by DennisLfromGA** [comment]
@msolters,

I'm not sure why you added the unity desktop yourself but that may be what's causing the problem.
When crouton adds desktops targets, it does things specifically for the chroot environment running under Chrome OS.

I would recommend that you update your chroot via crouton with the unity-desktop target, something similar to the following should work:

`sudo sh ~/Downloads/crouton -t unity-desktop -u [-n xenial]`

This way, packages that are already installed and updated will be skipped but other packages that are needed will be added.

Hope this helps,
-**DennisL**

**Comment by msolters** [comment]
Hey @DennisLfromGA, the issue is that part of the `unity` target is the `unity-2d` package.  This is unresolvable in 16.04.

The two solutions are

*  To remove `unity-2d` from `prepare.sh` mid-installation, or to remove it from the `targets` file (https://github.com/dnschneid/crouton/blob/58b76a38ce4125373da8dc4023a9ab9570269482/targets/unity#L20) and recompile crouton.  Both have the same result.
*  Do not use the `unity` target and manually install.

You get different outcomes for each.  If I use the `unity` target, with the workaround described above, Unity will only render a background and a weird X-shaped cursor.

If I install manually, I get the full UI (dash, menu, windows, etc.).  This is why I used the manual approach.

I will verify whether or not that `/org` folder is generated by using the target method.  I doubt it will be but we simply don't know yet.

**Comment by DennisLfromGA** [comment]
@msolters,

Thanx for clarifying and good to know.

-----
I get the same thing on my Acer C710 but didn't know why, maybe I'll re-install using your approach.

When I get to my Acer C710, I'll check to see if the `/org` folder is present.

I may even remove the unity target from crouton's targets files, update via crouton and then install the unity-desktop from within the chroot.

Thanx again,
-**DennisL**

**Comment by msolters** [comment]
Yeah manually installing, you also have to launch the xsession manually e.g. `sudo xinit unity` after entering the chroot of course.

The degree to which it works is amazing.  The glitches are almost all settings-related.  For instance, you can scale the Menus & UI from Unity's Display settings.  But, not all application fonts are resized.  I don't mean Chrome or Firefox, I mean Unity itself.  For instance, the text inside the Display settings dialog itself doesn't scale when that slider is changed.  But it does on vanilla Ubuntu 16.04 installed to the same Chromebook natively.  So there's something to do with how various settings are stored in this `/org` object or directory that is compromised with the Crouton approach.

**Comment by blydro** [comment]
I've tried installing unity using your method of installing xenial with target x11 and then running `apt install ubuntu-desktop` from the shell.

Problem is, `sudo xinit unity `gives me an xterm full of errors.

Any idea whats going on? Seems like essential services aren't starting. Are there any other packages that have to be installed for this to work?

Thanks

**Comment by idvoretskyi** [comment]
@msolters 

> Do not use the unity target and manually install.

How to run Unity after the manual installation (as `startunity` doesn't work)?

**Comment by blydro** [comment]
From the first post:

> Then, I can start a working Unity session using `sudo xinit unity`. This requires the x11 target.

**Comment by idvoretskyi** [comment]
@blydro I have the same issue as you:

> Problem is, sudo xinit unitygives me an xterm full of errors.
