### ISSUE TITLE
How to implement bob packages in raspberry pi

### ISSUE THREAD

**Issue by renzzy10** [dnschneid/crouton#2721]
hello friend. i want to ask on how to implement bob packages in raspberry pi? can anyone share ideas , procedure or source code? thank you in advance.

**Comment by DennisLfromGA** [comment]
You've taken a wrong turn I'm afraid, this is the crouton development & support site.

( note: try installing [pip](https://www.raspberrypi.org/documentation/linux/software/python.md) then [bob](https://pypi.python.org/pypi/bob) )

**Comment by drinkcat** [comment]
#262. pip bob pip bob meh bah.......
