### ISSUE TITLE
manjaro installation instructions

### ISSUE THREAD

**Issue by githubgnulinux** [dnschneid/crouton#2722]
According to a blog, it is possible to run manjaro within chromebook (https://edgelinux.wordpress.com/category/linux/chromebook/)

The instructions on the manjaro fork are not understood. (https://github.com/edge226/celce)

The command

sudo sh ~Downloads/crouton -r list

shows recognised debian, kali and ubuntu releases, but not manjaro. How to select a manjaro release please?

**Comment by davidlowryduda** [comment]
The manjaro fork (which seems to have been made by the writer of that blog post) that you linked to has not been updated for 3 years. This is not something that has been supported by crouton.

But if you (or if someone you know) wants it, you can fork crouton, add support, and submit a pull request.

**Comment by githubgnulinux** [comment]
Please excuse ignorance to understand. Is it not possible to download this old fork then update manjaro from within the chroot environment? Is it important tat crouton does not support this old fork?

> fork crouton, add support, and submit a pull request

Not a programmer, so this is not understood but thanks anyway.
