### ISSUE TITLE
On Pixel, running anything under xiwi only updates 1/4 of screen

### ISSUE THREAD

**Issue by tabatkins** [dnschneid/crouton#2729]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,audio,cli-extra,extension,keyboard,touch,xfce
host: version 8350.68.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Tue Aug 2 21:09:23 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

Launching any application only updates the top-left 1/4 of the screen. Mousing over to my ChromeOS taskbar and back usually does a full-screen repaint, and if I immediately scroll around the whole screen updates properly for a few seconds, but it quickly reverts to only painting a quarter of the screen.

This occurs whether I launch an individual application with `startxiwi` or launch the full xfce environment with `startxfce4`.  It's relatively recent, so must be a result of a ChromeOS update.  It persists after I did a crouton update.  I am also definitely following the instructions in <https://github.com/dnschneid/crouton/wiki/Chromebook-Pixel#hidpi-in-xiwi-window>.  I have not yet tried to do a full crouton reinstall, as that's annoying if I don't need it.

**Comment by sshivaji** [comment]
Interestingly, I notice this problem after moving to the developer channel. This was not an issue in the stable channel.

**Comment by sethml** [comment]
Dup of #2692.

**Comment by tabatkins** [comment]
Ah, indeed. Thanks!
