### ISSUE TITLE
Leveling Chart with 4 co-ordinates

### ISSUE THREAD

**Issue by khyatiChitroda** [dnschneid/crouton#2730]
I am developing an android app for leveling measurement, for that i need to draw graph with four co-ordinates, and i need to fill diff colors on that axis according to values, please help me sort it out. I need like below image.
![20140513_172118](https://cloud.githubusercontent.com/assets/17641624/17725746/cf4082f6-6402-11e6-94de-b76b8e1fa8d9.jpg)

**Comment by DennisLfromGA** [comment]
Sorry, but this does not sound like a 'crouton' issue.
This site is for developing, discussing, and troubleshooting 'crouton' issues.

**Comment by drinkcat** [comment]
#262.
