### ISSUE TITLE
failed to download raw.github.com files "bad header line"

### ISSUE THREAD

**Issue by nigelhealy** [dnschneid/crouton#2731]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue:

Err https://raw.github.com 3.14.0/main amd64 Packages                          
  Bad header line
Err https://raw.github.com 3.14.0/main i386 Packages                           
  Bad header line
W: There is no public key available for the following key IDs:                 
1397BC53640DB551
W: Failed to fetch https://raw.github.com/divx118/crouton-packages/master/dists/3.14.0/main/binary-amd64/Packages  Bad header line

W: Failed to fetch https://raw.github.com/divx118/crouton-packages/master/dists/3.14.0/main/binary-i386/Packages  Bad header line

E: Some index files failed to download. They have been ignored, or old ones used instead.
#### If known, describe the steps to reproduce the issue:

sudo sh ...crouton -u -n trusty

**Comment by mwhipple** [comment]
This looks like the same issue as https://github.com/divx118/crouton-packages/issues/40 and appears to belong in the `crouton-packages` repo rather than `crouton`

**Comment by drinkcat** [comment]
Yep, see issue above.

(And yes, I'm considering crouton-packages to be upstream ,-P)
