### ISSUE TITLE
Sudo startxfce4 does not work when i enter it in gives me 

### ISSUE THREAD

**Issue by IAMBOB20** [dnschneid/crouton#2732]
![screenshot 2016-08-17 at 1 00 53 pm](https://cloud.githubusercontent.com/assets/21082653/17745650/abc762d6-647a-11e6-9d48-ae84ac6973a3.png)
```
Please paste the output of the following command here: sudo edit-chroot -all
```

 I've tried this a good 20 times by now none of them working please help if you can

**Comment by davidlowryduda** [comment]
What is the output of the following command: `sudo edit-chroot -all`

**Comment by davidlowryduda** [comment]
Also, this is likely the same issue as found in https://github.com/dnschneid/crouton/issues/2686

**Comment by IAMBOB20** [comment]
it comes out as this 

chronos@localhost / $ sudo edit-chroot -all
Password: 
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 8350.68.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:08:34 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by IAMBOB20** [comment]
Ill also check out #2686

**Comment by IAMBOB20** [comment]
when i put in the sudo rm /dev/dri/cardo and sudo mv /dev/dri/card1 /dev/dri/cardo it just says that there is no such file or directory.

**Comment by TheSaltyc** [comment]
same thing here. the first time i did the card 0 it worked then the second command didnt work. should i just white wash and try again?

**Comment by dnschneid** [comment]
Fixed in latest crouton, no hacks needed.
