### ISSUE TITLE
Vim system clipboard

### ISSUE THREAD

**Issue by zwhitchcox** [dnschneid/crouton#2733]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20160715134041~master:0dc76a22
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: extension,xiwi,audio,keyboard,cli-extra,x11
host: version 8350.68.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 2 21:32:14 PDT 2016 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling as another instance is using it.
```

As per [vim's instructions](http://vim.wikia.com/wiki/Accessing_the_system_clipboard), I have made sure to install a version of vim with +xterm-clipboard. I also added the target `extension` to my chroot and installed the chrome OS crouton extension.

I can copy and paste between windows using xiwi, but when I try to pull from my system clipboard in vim, using the `*` register, I get nothing. Also, when I try to use tools like `xclip` this doesn't work either. I know there's crouton clip, but is there any way to make X11 run in the background, even when running on just the command line? Or maybe add a `-x` argument or something to share the clipboard when running on the command line for `sudo enter-chroot`?

**Comment by davidlowryduda** [comment]
I also use xiwi, through which I routinely run vim (and other things) in an awesome wm. I have no problem using the system clipboard, copying from ChromeOS to vim or vice-versa.

I'm not sure what the difference is, but have you tried using the + register instead of the * register? This is the difference between the CLIPBOARD register and the PRIMARY register. [I must admit I never use the PRIMARY register, so I cannot say anything more about it].

**Comment by zwhitchcox** [comment]
Oh, right, it does work if I'm using xiwi...It just doesn't work if I use `sudo enter-chroot`, and I was wondering if there were a way to use the system's register through `vim` or `xclip` even if the GUI, even if I'm not actually running the GUI by just running X in the background, even though I don't really need the gui

**Comment by zwhitchcox** [comment]
Just for the clipboard

**Comment by zwhitchcox** [comment]
So, I made a thing.

Oddly specific subset of crouton users, but if you're using the crosh shell without running the display, you can use [this chrome extension](https://chrome.google.com/webstore/detail/crouton-clipboard/jipofmbanedhjnpooojdeeddanhfljif) to integrate the clipboard between vim and chrome os.

See, [the github repo](https://github.com/zwhitchcox/crouton-clipboard) for installation to your distro.

**Comment by divx118** [comment]
@zwhitchcox Nice, but how about right clicking in a crosh/chroot shell window. This will paste the text from your clipboard. Just selecting the text in a a crosh/chroot shell window will copy the selected text to your clipboard, or am I overlooking something besides that this doesn't work with the hotkeys in vim?

**Comment by zwhitchcox** [comment]
Yes, you can usually do that, but in vim, there are certain inconveniences...like if you are going to paste in, you have to `set paste`, `insert`, and then `set nopaste`, or else it won't paste the file in correctly, vs `"*p`. And even this doesn't always work, because when pasting something really large, sometimes halfway through it will mess up for whatever reason.

Also, if you're copying in vim, you can't just `"*y`, you have to use the cursor, to select, and if the text is longer than one screen, you have to copy one screen at a time (because vim can only show one screen worth of text). Or you have to just `cat` the file, and then manually go through and copy what you want, but even this isn't an option if you're using `tmux`, for the same problem as vim.

Eventually, I got so sick of this, I'm just like I'm fixing this for good, and I though I could add stuff if I wanted too.

So, yeah, it's a lot of work to save a little work, but it's nice not to have to stop what you are doing and think of the most efficient work around, and just `"*y`/`"*p` and get back to exactly what you're doing.

Plus I could implement a clipboard history or whatever I wanted.

**Comment by divx118** [comment]
Ah ok, clear now. Thanks for explaining it. Maybe something to add to the crouton wiki so that people can easily find it.

**Comment by zwhitchcox** [comment]
Yes, thank you for asking! When you work hard on something, it's nice when people show interest!

But yeah, I [added a page](https://github.com/dnschneid/crouton/wiki/Integrate-Crosh-Shell-Vim-Clipboard-With-Chrome-OS-Clipboard)...not sure where else I should put it in the wiki though..is that good?

Also, there will be an update coming hopefully next week if you're interested!

**Comment by dnschneid** [comment]
Nifty!  Thanks for sharing your solution!

**Comment by zwhitchcox** [comment]
No problem! Thanks for creating the platform in general!
