### ISSUE TITLE
(crouton) Is it possible to change the keyboard language within an app executed on a tab?

### ISSUE THREAD

**Issue by KYSSelectron** [dnschneid/crouton#2736]
Having started an app from crouton-xiwi

`sudo startxiwi -bT app`

I have the keyboard layout as the preferred one. I could change it when running startxcfe4 just by clicking the icon, but here this does not seem to be possible

Then I have started xcfe in another tab

`sudo startxiwi -bT startxcfe4`

And from there I have changed the language (by clicking the icon)

However, this doesn't affect the app started in the first tab, I guess it only affects the applications started under "that" xcfe4 environment.

The question is: is there any way to do this?

**Comment by drinkcat** [comment]
First figure out what's the correct `setxkbmap` command for your case, then add that to `$HOME/.xiwirc`.
