### ISSUE TITLE
Suddenly Asking for Password

### ISSUE THREAD

**Issue by judsonmitchell** [dnschneid/crouton#2737]
```
ame: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version unknown
release: unknown
architecture: unknown
targets: cli-extra
host: version 8530.62.0 (Official Build) beta-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 16 21:54:41 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
```

#### Please describe your issue: 
I've had the same chroot on my Flip for over a year now. After an update (to  53.0.2785.70 beta) I get asked for a password when I try to enter the chroot. I have never set a password, nor have I had to provide one before. I see from other threads that this happens when you have debugging enabled, but I presumably don't, as I didn't change anything as far as my Chrome set up. 

I have a recent backup of my chroot so, I could Powerwash and start from scratch, but is there any other way around this issue? Thanks.

#### If known, describe the steps to reproduce the issue:
```
sudo enter-chroot
```

**Comment by mpmilano** [comment]
I have also begun seeing this behavior, alongside a new behavior in which dbus insists on having an SELinux policy. 

Does your chromeOS install have an enabled SELinux policy? there should be a variable set to "enforcing" in /etc/selinux/config if it does.

**Comment by judsonmitchell** [comment]
Yes, it does have the variable set to enforcing. As far as I can tell, that file cannot be edited. Any suggestions?

I have also seen that warning about dbus. That started after the update that introduced Google Play apps to Chrome OS, which leads me to believe that all of these problems are caused by the Android apps thing.

**Comment by mpmilano** [comment]
You're right. There's a pull request out that should fix this; not sure how
long it's going to take the devs to incorporate it.

I'm also having trouble with dbus failing to do anything, which the
outstanding patch does not fix. It looks like if I write a selinux policy
for dbus that should start working, but I'm not quite sure how to do that.

**Comment by judsonmitchell** [comment]
Just in case anyone comes here with this issue, this problem basically bricks your crouton install. What I did to temporarily get around it was to change to the Stable channel and then restore my crouton from a backup. If this selinux policy makes it in to the stable branch, I'm not sure what I'm going to do.

(Note that deactivating the Google Play Store option in Settings did not help this).

**Comment by mpmilano** [comment]
https://github.com/dnschneid/crouton/pull/2735

This pull request contains a fix for specifically enter_chroot; it does not
disable SELinux sufficiently well for SELinux-aware services such as dbus
to work correctly.  I've figured out some basic dbus policies that at least
allows it to start, but they're all too restrictive for most X11 desktop
environments to function correctly.

**Comment by pjchamberlain** [comment]
I gave in to reinstalling crouton to fix this issue ..   

The issue with the Google Play store crashing appeared with the same Chrome update  - which I've now resolved with the help of the advice on https://github.com/dnschneid/crouton/issues/2706 to edit the enter-chroot script (as mentioned above pull request #2735 is the fix for this issue)

**Comment by drinkcat** [comment]
Latest version should have the fix.
