### ISSUE TITLE
Unmounting a chroot after closing single-app xiwi window

### ISSUE THREAD

**Issue by w0de** [dnschneid/crouton#2738]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: syo
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/syo...
crouton: version 1-20160715134041~master:0dc76a22
release: jessie
architecture: amd64
xmethod: xiwi
targets: xiwi,core,cli-extra,gtk-extra,lxde,keyboard
host: version 8350.68.0 (Official Build) stable-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:08:52 PDT 2016 x86_64 GNU/Linux
freon: yes
#### Please describe your issue:

Unable to unmount chroot (except with unmount-chroot command) after I close a single-app xiwi tab.
#### If known, describe the steps to reproduce the issue:

sudo enter-chroot -b -n syo xiwi -T atom

-> Starts crouton tab with atom GUI, great
-> I quit atom, close tab
-> Chroot is sill mounted, I need to run sudo unmount-chroot to unmount

Is this the correct behavior? If so, am I using the unmount-chroot utility correctly in this instance? If not, what am I, xiwi, crouton or atom doing wrong?

**Comment by l3eta** [comment]
If you leave the console window that started the chroot you can hit Control-C and it will trigger an unmount, however if it doesn't, you can use 'unmount-chroot -p {CHROOT_NAME}' to get the process id's and then simply 'kill -9 {PID}' and then 'unmount-chroot {CHROOT_NAME}' should work. 

The answer to your question is yes, I believe it is the correct behavior.
