### ISSUE TITLE
Can't type password in crosh terminal

### ISSUE THREAD

**Issue by natertayt** [dnschneid/crouton#2741]
```
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
```
when it prompts me for my password in crosh it will not let me type anything.All i can do is press enter.

**Comment by DennisLfromGA** [comment]
@natertayt,

Did you encrypt your chroot or set a chronos passwd with `chromeos-setdevpasswd` ?
If so, use that password when prompted.

Did you choose to [enable Debugging features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features) after a powerwash, a recovery, or when you first set it up?
If so, it will let you assign a new root password or it will default to `test0000`.

Hope this helps,
-**DennsiL**

**Comment by natertayt** [comment]
@DennisLfromGA 

my bad i did not search the issues thoroughly as i should of before creating a new one. i have the asus c100. for some reason the playstore messes with the password some how, but i installed the trusty instead of the precise version and it worked fine. thanks and sorry

**Comment by DennisLfromGA** [comment]
No problemmo, glad you got it sorted out.

**Comment by skyqupid** [comment]
I'm having the same issue and have tried all troubleshooting methods I could find even did a recovery Could someone please assist?

**Comment by DennisLfromGA** [comment]
@skyqupid,

Just being thorough here but you will NOT see anything you type when entering your password but it WILL accept the input, this is done for added security.

*Hope this helps,*
-**DennisLfromGA**
