### ISSUE TITLE
Add LXQt support

### ISSUE THREAD

**Issue by tsimonq2** [dnschneid/crouton#2743]
Add support for the LXQt desktop.

Soon (**not now**) we'll also have the `lubuntu-qt-desktop` package to use. I'm personally leading that effort and I'll comment here when it's ready.

But for the time being, for Yakkety, we could have LXQt support. The `lxqt` package works fine.

Speaking of this, I created a PR adding Yakkety support. (#2742)

**Comment by dnschneid** [comment]
There's a WIP in #2525, but it (along with the Mate target #2532) still have unresolved installation issues.

**Comment by drinkcat** [comment]
Let's track in #2525.
