### ISSUE TITLE
Audacity doesn't launch on ASUS Flip C100p

### ISSUE THREAD

**Issue by GeitHub** [dnschneid/crouton#2744]
>Freshly Power-washed Chromebook (beta channel, for the ability to use the Play Store)
>ASUS Chromebook Flip C100p (4gb RAM Model)
>Newest Crouton version available on this Github
>Chrome Extension up-to-date
>sudo sh ~/Downloads/crouton -r trusty -t xiwi,xfce,extension

On the system:
>sudo apt-get install audacity
>Download/install completes fine, with no errors reported
>Launch Audacity
> Splash screen pops up, and then nothing happens

If there is anything else I can provide that might help in resolving the error, please let me know (I'm new to Chromebooks and Linux generally). Obviously, I'm not expecting the world here given that this is an ARM chipset/I'm on the beta channel until Chrome Apps hits the stable channel, it's also quite possible that Audacity may just have problems with ARM to begin with, but a cursory Google search didn't turn anything up.

Thanks for providing us this awesome tool! ChromeOS + Android apps + Crouton is really something to behold, especially in this 2 in 1 form factor.

**Comment by drinkcat** [comment]
Fails with
```
FATAL: cannot locate cpu MHz in /proc/cpuinfo
```

Appears that the problem is in jackd: https://bugs.launchpad.net/ubuntu/+source/jackd2/+bug/1353832 .

audacity in xenial works fine, so you might want to use that instead.
