### ISSUE TITLE
Toshiba Chromebook 2 Broadwell crouton XFCE video glitches

### ISSUE THREAD

**Issue by aok1425** [dnschneid/crouton#2745]
#### Please paste the output of the following command here: `sudo edit-chroot -all`

```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,xfce,extension
host: version 8350.68.0 (Official Build) stable-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 2 21:10:00 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
I've run into a video issue that I haven't seen mentioned here or in my Google search:
![alt text](http://i.imgur.com/x2Ay1sS.gif "Logo Title Text 1")

I have to click the "old" portion of the screen for it to update.

My attempts:
- I updated the Intel video drivers; that didn't help.
- `set res` didn't help either; when I use it, it freezes the crouton window.

Any other suggestions on how to resolve this? @cefn @raidzero @Voltron00x ?

#### If known, describe the steps to reproduce the issue:

This happens in both xiwi and before I updated the target with xiwi. I think it's related to me setting the resolution in ChromeOS to 1536x864, bc when it's 1200x675 (which I think is the resolution of the top-left portion of the screen), it's fine.

**Comment by aok1425** [comment]
It also works fine on 1920x1080. Maybe it's something related to XFCE not supporting 1536x864?

**Comment by aok1425** [comment]
I can also re-create the issue this way:
1. `sudo startxfce4`, which opens up xiwi full-screen in 1536x864. Everything is fine at this moment.
2. When I get out of full-screen, either by F5 to view all windows, or F4 to leave full-screen, the issue starts. When I re-full-screen the xiwi window, the issue now persists.

**Comment by drinkcat** [comment]
Oh, this really looks like #2692/https://bugs.chromium.org/p/chromium/issues/detail?id=633806, but at tha different scale (this device does 1.25x scaling), does it still happen on the latest R53/R54 images?

**Comment by aok1425** [comment]
Looks like it works now, under R53--thanks!
