### ISSUE TITLE
Installation issues, Mount errors even after chrome powerwash.

### ISSUE THREAD

**Issue by Ltbattlebadger** [dnschneid/crouton#2747]
```
Please paste the output of the following command here: chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
mount: /run/crouton/mnt/stateful_partition/crouton/chroots/precise/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

#### Please describe your issue:
This is my first time doing something like this so please excuse me if I miss some piece of information that I am supposed to post here. Also posting before I leave for work so any immediate responses this morning will be delayed. 

I was able to install everything just fine on the first run yesterday and installed Unity using Crouton. However, I got really confused trying to get the crouton extension to work. After getting frustrated I ended up putting any little snippet of code into both the chrome side terminal as well as the ubuntu side terminal and things just got weird so I tried to delete the chroot and do a fresh install the correct way the first time. Well, ever since then, I get a mount error when try to an install. I got the same error after a powerwash this morning. 

mount: /run/crouton/mnt/stateful_partition/crouton/chroots/precise/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by DennisLfromGA** [comment]
@Ltbattlebadger,

Since your `croutonversion` command didn't get executed, we don't have a lot of the details we need to troubleshoot your issue yet.

Do you by chance have one of the three Chromebooks that have Android apps (Pixel 2, Asus Chromebook Flip, Acer R11) on the beta or dev channel?

You may need to update your chroot to get the latest crouton changes for Chrome OS and SELinux, you can do that using something like:

`sudo sh ~/Downloads/crouton -n precise -u`

You also may be running into issue https://github.com/dnschneid/crouton/issues/2706 if Google Play is crashing. See issue https://github.com/dnschneid/crouton/issues/2706#issuecomment-241812246 for a possible temporary fix.

-**DennisL**

**Comment by DennisLfromGA** [comment]
@Ltbattlebadger,

This is happening on mine too now when doing a crouton update but the changes in https://github.com/dnschneid/crouton/issues/2706#issuecomment-241812246 fixed it.

-**DennisL**

**Comment by choas0422** [comment]
FINALLY SOMEONE WITH THE SAME ISSUE!!!
This is the error I get when trying to launch the chroot environment:
launching Kali Linux...
Entering /media/removable/sd/chroots/kali-rolling...
mount: /run/crouton/media/removable/sd/chroots/kali-rolling/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Unmounting /media/removable/sd/chroots/kali-rolling...
chronos@localhost / $ 

I'm on the Dev channel for updates:
Version 54.0.2837.0 dev
Platform 8737.1.0 (Official Build) dev-channel veyron_speedy
Firmware Google_Veyron_Speedy.6588.197.0

After the last system update this started happening. I tried to Google around to find a solution and I 
even tried to use an older sd card with a previouse installation of the chroot environment just to verify it was
not my chroot environment. I also noticed that I can't enter the chroot, I can't use xiwi to pull single apps out,
I can't update chroot, nothing. The error recommended looking at dmesg but I could find anything in there that
 stood out.
 
 dmesg output:
 chronos@localhost / $ dmesg | tail
[ 2072.299011] mmc0: BKOPS_EN bit is not set
[ 2072.310520] dwmmc_rockchip ff0c0000.dwmmc: Successfully tuned phase to 133
[ 2072.312927] mmc_host mmc0: Bus speed (slot 0) = 148500000Hz (slot req 150000000Hz, actual 148500000HZ div = 0)
[ 2072.606862] elan_i2c 4-0015: invalid report id data (ff)
[ 2072.829652] dwmmc_rockchip ff0f0000.dwmmc: Successfully tuned phase to 177
[ 2075.723619] tpm_i2c_infineon 1-0020: command 0x65 (size 18) returned code 0x0
[ 2075.764941] tpm_i2c_infineon 1-0020: command 0x21 (size 14) returned code 0x0
[ 2075.796740] tpm_i2c_infineon 1-0020: command 0x65 (size 18) returned code 0x0
[ 2076.035757] tpm_i2c_infineon 1-0020: command 0x1e (size 274) returned code 0x0
[ 2077.709753] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
chronos@localhost / $

**Comment by Ltbattlebadger** [comment]
@DennisLfromGA 

I am using the newest Toshiba Chromebook 2. I updated my chroot using the command you supplied. At the end of that script running, it gave me this:

Pruning /mnt/stateful_partition/crouton/chroots/precise mounts...
mount: /run/crouton/mnt/stateful_partition/crouton/chroots/precise/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...


I looked at the comment #2706  and I have no idea how to begin doing that.

**Comment by DennisLfromGA** [comment]
@Ltbattlebadger,

> I updated my chroot using the command you supplied.

Sorry, the `edit-chroot` script needs to be edited per https://github.com/dnschneid/crouton/issues/2706#issuecomment-241812246.
If you're not comfortable with editing the script, you may have to wait until pull request https://github.com/dnschneid/crouton/pull/2735 is approved and merged, sorry.

-**DennisL**

**Comment by BKPepe** [comment]
Hello,
I have same issue on Lenovo N22 :(

Installation: https://paste.ee/p/h11A4

Starting (  sudo enter-chroot startxfce4 ) : https://paste.ee/p/RaMIP

Tried even sudo sh ~/Downloads/crouton -n precise -u  and result is same: https://paste.ee/p/9unXt

**Comment by trance1975t** [comment]
Same issue, Acer Chromebook 14. Seems to have happened after the most recent Chrome developer channel update.

**Comment by DennisLfromGA** [comment]
Same issue, same temporary solution: https://github.com/dnschneid/crouton/issues/2706#issuecomment-241812246

**Comment by BKPepe** [comment]
I'm newbie with it, please can you tell me what to do next?

I saved it, did exit, then shell and tried sudo sh ~/Downloads/crouton -t xfce (so I edited file again, then tried sudo enter-chroot startxfce4 result is same)
tried also -n precise -u and same still warning and still nothing :(

**Comment by DennisLfromGA** [comment]
@BKPepe,

> I saved it, did exit, then shell and tried sudo sh ~/Downloads/crouton -t xfce (so I edited file again, then tried sudo enter-chroot startxfce4 result is same)

The command you used will install a brand new 'precise' chroot with an new `enter-chroot` script that doesn't have your changes.
[ I think you'd be better off installing 'trusty' with: `sudo sh ~/Downloads/crouton-r trusty  -t xfce` ]

> tried also -n precise -u and same still warning and still nothing :(

When either of those fail, you can re-modify `/usr/local/bin/edit-chroot` and then run it without any command-line options, like: `sudo enter-chroot`

This will hopefully prompt you with *'Would you like to finish the setup? [Y/n/d] '*
Now press '`enter`' or enter `Y` and let it finish.
Once it finishes successfully, you'll be able to run your desktop gui, using: `sudo startxfce4`

Hope this helps,
-**DennisL**

**Comment by BKPepe** [comment]
Did it, but without success. Maybe its wrong to run: sudo vim ?

http://paste.ee/p/C0Dv8

**Comment by Ltbattlebadger** [comment]
@DennisLfromGA  

I am comfortable trying to edit the script. However what I am unsure about is it a physical file that I am editing on my chromebook? Would that be the crouton file I downloaded and what program do I use to open that up and edit it. or do I edit a command when I type it into shell?

**Comment by DennisLfromGA** [comment]
@BKPepe,

> The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.

So, *'You may want to update your chroot again.'* may be what you need to do at this point.
When it fails, try running your modified `enter-chroot` script again.

If that doesn't work, there's another way to extract crouton on your Chromebook, modify `edit-chroot`, and run the `main.sh` script. That will require many more directions that I would prefer to avoid if at all possible.

-**DennisL**

**Comment by BKPepe** [comment]
I tried enter-chroot again and it doesn't work. Still same result. :(

**Comment by BKPepe** [comment]
Now it says this: http://paste.ee/p/Q6Zzi

**Comment by DennisLfromGA** [comment]
@BKPepe,

> I am comfortable trying to edit the script. However what I am unsure about is it a physical file that I am editing on my chromebook? Would that be the crouton file I downloaded and what program do I use to open that up and edit it. or do I edit a command when I type it into shell?

So, you haven't modified the file yet? If not, you'll get 'mount' error above every time.

The file you need to modify is `/usr/local/bin/edit-chroot` on your Chromebook.
The modifications are explained in https://github.com/dnschneid/crouton/issues/2706#issuecomment-241812246

I use `vi` (vim) to edit files, it has a bit of a learning curve for the uninitiated but it's powerful.
I noticed you were trying to get 'nano' [here](https://gist.github.com/alex-endfinger/1510908#gistcomment-1859589) but that's now a dead link.

-**DennisL**

**Comment by BKPepe** [comment]
I have it modified the file as you can see it says unmount isnt possible.
edit-chroot, are you sure? In #2706 it says enter-chroot

I use vim as you can see. I liked nano, but nvm

**Comment by DennisLfromGA** [comment]
@BKPepe,

> **edit-chroot, are you sure? In #2706 it says enter-chroot**

You're right, **I mistakenly said `edit-chroot` instead of `enter-chroot`, I fixed it now - sorry.**

I looked at your output above and the failure may now be due to the error thrown when trying to `umount` selinux. I would suggest editing an un-modified `/usr/local/bin/enter-chroot` script as follows:
( I'm using `sed` so there's no need to use `vi` )

  `cd /usr/local/bin`
  `sudo sed -i.orig 's:mount -o remount,ro "$CHROOT/sys/fs/selinux":umount $CHROOT/sys/fs/selinux || true:' enter-chroot`

That should modify the file and make a copy of the original named `enter-chroot.orig` for safe keeping.
Then try running `sudo enter-chroot` again and see if it works.

-**DennisL**

**Comment by BKPepe** [comment]
Wohoo, finally its working. Awesome job, man.
Thanks

**Comment by BKPepe** [comment]
Kinda reminder that I have Lenovo N22, but on Ubuntu - Trusty
touchpad and even keyboard doesnt work (Linux localhost 3.18.0-12913-g0be86ca #1 SMP PREEMPT Thu Aug 25 01:07:11 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by tanjinjack** [comment]
It appears that the fix (editing enter-chroot) only works for the xfce interface. I tried it several times with kde but only trying with xfce would the installation continues.

**Comment by DennisLfromGA** [comment]
@tanjinjack - Try this simple fix instead and see if it works on a broader scale: https://github.com/dnschneid/crouton/pull/2748/commits/fe9dad6b3d569c1a97411aa7318582dc8c31b27a

**Comment by Herran** [comment]
How do you edit the file?? in the terminal?  can someone explain how?? I have this same problem.

**Comment by choas0422** [comment]
I've been putting the sd card in a seperate linux pc to make the changes.
Seems to be the easiest way without using vim...

**Comment by Herran** [comment]
smart. Ill try that on a usb.

**Comment by choas0422** [comment]
checkout the issue I mentioned earlier... It might help you at least get
into linux. #2758

**Comment by SilverWave** [comment]
I have done the -DennisL sed thing, and I an now back up and running... (Thanks Dennis).
... so what is the next step?
Do I update the crouton file as normal and update everything? (I'm running trusty).

**Comment by DennisLfromGA** [comment]
@SilverWave,

> I have done the -DennisL sed thing, and I am now back up and running... (Thanks Dennis).

That should not be necessary any longer since PR https://github.com/dnschneid/crouton/pull/2748 has been merged.

> ... so what is the next step?
Do I update the crouton file as normal and update everything? (I'm running trusty).

Since you're a little late to the party ;), we don't know what you're working with/on and what you've done/not done. But you can hardly go wrong by updating your chroot. You can do that for a 'trusty' chroot using something like:

`sudo sh ~/Downloads/crouton -n trusty -u`

> sudo enter-chroot -n trusty -b xiwi -T startxfce4

The command string you show above would just drop you into your xfce4 desktop and not perform any updates. If you just want to get into your desktop, you can do it a little easier with the following:

`sudo startxfce4 -n trusty -bX xiwi-tab`

*Hope this helps,*
-**DennisL**
