### ISSUE TITLE
Fatal server error,no screens found

### ISSUE THREAD

**Issue by umpienoob** [dnschneid/crouton#2750]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160823173305~master:1e0c0488
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8350.68.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-12320-gbb6b499 #1 SMP PREEMPT Tue Aug 2 21:10:11 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

#### Please describe your issue:
Whenever i try to use xfce,it wont work,giving me the no screen error. It works the 1st time i installed,but after that it wont work.I reinstalled xfce after powerwashing and it worked once before getting that error.Here are the logss that happen when i put in "sudo startxfce4"

Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-12320-gbb6b499 #1 SMP PREEMPT Tue Aug 2 21:10:11 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=15f77060-5f09-8a44-ab58-5b11af26fc82/PARTNROFF=1 hashtree=PARTUUID=15f77060-5f09-8a44-ab58-5b11af26fc82/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=c4881dcb04911e8abee3f41dc53772575351d211 salt=d491b53a01cfc204568c9ed84a7fc64a5d69407b27dffbbea58ab6d955c697a1" noinitrd vt.global_cursor_default=0 kern_guid=15f77060-5f09-8a44-ab58-5b11af26fc82 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Aug 28 21:42:55 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

#### If known, describe the steps to reproduce the issue:
Unknown

**Comment by l3eta** [comment]
try sudo apt-get install xinit and see what it says, seems you don't have xserver properly installed.

**Comment by umpienoob** [comment]
@l3eta  said apt-get wasn't a command soooo

**Comment by DennisLfromGA** [comment]
@umpienoob,

Do it inside the chroot -

`sudo enter-chroot`
`sudo apt-get install xinit`
`exit`
`sudo startxfce4`

-**DennisL**

**Comment by Qwerty-Space** [comment]
I tried that @DennisLfromGA and xinit was already installed.
