### ISSUE TITLE
Can't install ubuntu trusty - package was corrupt.

### ISSUE THREAD

**Issue by gergesh** [dnschneid/crouton#2752]
I can't seem to install trusty. The installation just starts and then it says:
I: Retrieving Packages 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages
W: http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages was corrupt.

I guess the mirrors are broken?

Here's the command just in case it's related.

name: kali-rolling
encrypted: no
Entering /media/removable/SD Card/chroots/kali-rolling...
crouton: version 1-20160823173305~master:1e0c0488
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,extension,keyboard
host: version 8350.68.0 (Official Build) stable-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 2 21:10:00 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/SD Card/chroots/kali-rolling...
name: precise
encrypted: no
Entering /media/removable/SD Card/chroots/precise...
crouton: version 1-20160823173305~master:1e0c0488
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,keyboard,gnome,extension
host: version 8350.68.0 (Official Build) stable-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 2 21:10:00 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/SD Card/chroots/precise...

**Comment by l3eta** [comment]
-- This
release: kali-rolling
architecture: amd64

-- And this
release: precise
architecture: amd64

It doesn't seem like you have trusty, only precise and kali-rolling, if I'm not mistaken. I'm downloading trusty for arm right now so I can let you know if it works for me.

**Comment by drinkcat** [comment]
Sounds like some network error, please reopen if it happens again.
