### ISSUE TITLE
Magento2 product not editable

### ISSUE THREAD

**Issue by devqualwebs** [dnschneid/crouton#2753]
```
Notice: Undefined offset: 90 in /opt/lampp/htdocs/magento2/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 167
```

1.When i edit product inmagnto2 i got above error what should i do
2. On frontend product not shoing i got below notice

Notice;- We can't find products matching the selection.

**Comment by drinkcat** [comment]
#262.

**Comment by dnschneid** [comment]
I fixed the description, at least.

**Comment by drinkcat** [comment]
chomp chomp
