### ISSUE TITLE
iOS 10 Push Notifications with Beacons

### ISSUE THREAD

**Issue by rteshler** [dnschneid/crouton#2756]
#### Please describe your issue:

Hello, I am trying to build an application that will send a user a push notification if they have entered the range for a beacon. I have done all of the steps that are required to send the notification, but I'm having trouble with writing the code since the syntax has been changed for iOS 10 and I have not been able to find any useful resources. Any help would be great.

**Comment by Happy-Ferret** [comment]
Since this is the crouton issue tracker and your question is not in any way related to crouton, you might want to check out something like gitter (https://gitter.im/orgs/FreeCodeCamp/rooms is a good starting point, I've found) or stackoverflow.

**Comment by drinkcat** [comment]
#262.
