### ISSUE TITLE
still having mounting issues with selinux

### ISSUE THREAD

**Issue by choas0422** [dnschneid/crouton#2758]
First things first.

Chrome version and channel:
Version 54.0.2840.6 dev
Platform 8743.4.0 (Official Build) dev-channel veyron_speedy
Firmware Google_Veyron_Speedy.6588.197.0

When I try to load the chroot environment I get this error first:
Entering /media/removable/sd/chroots/kali-rolling...
mount: /run/crouton/media/removable/sd/chroots/kali-rolling/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Unmounting /media/removable/sd/chroots/kali-rolling...
chronos@localhost / $ 

I then run the crouton update (sudo sh ~/Downloads/crouton -u -n kali-rolling -p /media/removable/sd) and it fails:
Downloading latest crouton installer...
######################################################################## 100.0%
/media/removable/sd/chroots/kali-rolling already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
mount: /run/crouton/media/removable/sd/chroots/kali-rolling/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Unmounting /media/removable/sd/chroots/kali-rolling...
chronos@localhost / $ 

Then I try to enter Chroot again and get the startup scrip prompt. But it also fails, but it bumps me into chroot anyways:
Entering /media/removable/sd/chroots/kali-rolling...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
mount: /run/crouton/media/removable/sd/chroots/kali-rolling/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
(kali-rolling)groot@localhost:~$ 

At this point I can run anything in chroot I want as long as I keep this terminal open. As soon as I close it I start getting the mount errors again.

dmesg | tails output before update:
chronos@localhost / $ dmesg | tail
[   25.872207] tpm_i2c_infineon 1-0020: command 0xba (size 18) returned code 0x22
[   25.903196] tpm_i2c_infineon 1-0020: command 0x65 (size 18) returned code 0x0
[   25.939516] tpm_i2c_infineon 1-0020: command 0x21 (size 14) returned code 0x0
[   25.973968] tpm_i2c_infineon 1-0020: command 0x65 (size 18) returned code 0x0
[   26.215134] tpm_i2c_infineon 1-0020: command 0x1e (size 274) returned code 0x0
[   26.494392] EXT4-fs (mmcblk1p1): recovery complete
[   26.496488] EXT4-fs (mmcblk1p1): mounted filesystem with ordered data mode. Opts: 
[   32.808095] max98090 2-0010: mclk 12288000, pclk 12288000
[   40.441452] EXT4-fs (mmcblk1p1): re-mounted. Opts: data=ordered
[   47.149391] usb 1-1: reset high-speed USB device number 2 using ehci-platform

dmesg | tails output after update:
chronos@localhost / $ dmesg | tail
[  122.540502] EXT4-fs (mmcblk1p1): re-mounted. Opts: data=ordered
[  573.898615] rk3288-dmc ff610000.dmc: timeout before pausing cpus
[  573.898679] rk3288-dmc ff610000.dmc: failed to change dmc freq
[  650.190526] EXT4-fs (mmcblk1p1): re-mounted. Opts: data=ordered
[  670.576069] elan_i2c 4-0015: invalid report id data (ff)
[  744.455440] EXT4-fs (mmcblk1p1): re-mounted. Opts: data=ordered
[  750.124383] systemd-logind[13699]: Failed to enable subscription: Launch helper exited with unknown return code 1
[  750.124450] systemd-logind[13699]: Failed to fully start up daemon: Input/output error
[  750.375165] systemd-logind[13711]: Failed to enable subscription: Launch helper exited with unknown return code 1
[  750.375230] systemd-logind[13711]: Failed to fully start up daemon: Input/output error

output of edit-chroot -all:
chronos@localhost / $ sudo sh /media/removable/sd/bin/edit-chroot -all
name: kali-rolling
encrypted: no
Entering /media/removable/sd/chroots/kali-rolling...
mount: /run/crouton/media/removable/sd/chroots/kali-rolling/sys/fs/selinux not mounted or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

I've tried adding "bind" to the mounting lines for selinux, and that didn't work. I also tried the initial fix for issue #2747, 
but that didn't work either. Please let me know if there is any more info I can give to help with this issue.

**Comment by jharder91** [comment]
I am experiencing this exact issue as well! As long as I keep the terminal session open, I can open everything else. If that terminal session ends, You can sometimes get it back up by restarting the whole process over again (including the failed update), but it tends to hang when trying to update/enter chroot until I reboot the chromebook.

**Comment by jharder91** [comment]
I also tried the bind fix and issue fixed choas0422 tried as well to no avail.

**Comment by DennisLfromGA** [comment]
Make sure you reboot your Chromebook before trying to update your chroot.

**Comment by choas0422** [comment]
I tried that before and after the update...

**Comment by choas0422** [comment]
I also downloaded the latest version of crouton.

**Comment by jharder91** [comment]
I also downloaded the newest crouton file and tried rebooting before and after updating a few times.

**Comment by choas0422** [comment]
I just tried downloading the new version of crouton again, and it looks like it might be working... I'm not sure what changed. I'll let you guys know what the outcome is when it's finished.

**Comment by jharder91** [comment]
Re-downloading crouton file to check and ensure as well

**Comment by jharder91** [comment]
Check with version downloaded 5 minutes ago. Rebooted and tried to update which failed with the same errors as before.

**Comment by choas0422** [comment]
well it did update but as soon as it hit net-ng part of the prepare.sh script it stopped. I fixed the couple of lines for net-ng but then it wouldn't mount again.

**Comment by choas0422** [comment]
so I'm right back to my original issue.

**Comment by choas0422** [comment]
This is my new dmesg | tail output:

(kali-rolling)groot@localhost:~$ dmesg | tail
[   18.672372] EXT4-fs (mmcblk1p1): recovery complete
[   18.673204] EXT4-fs (mmcblk1p1): mounted filesystem with ordered data mode. Opts: 
[   25.977997] max98090 2-0010: mclk 12288000, pclk 12288000
[   41.097686] usb 1-1: reset high-speed USB device number 2 using ehci-platform
[   54.535040] EXT4-fs (mmcblk1p1): re-mounted. Opts: data=ordered
[   70.915912] EXT4-fs (mmcblk1p1): re-mounted. Opts: data=ordered
[   74.560715] systemd-logind[12579]: Failed to enable subscription: Launch helper exited with unknown return code 1
[   74.560807] systemd-logind[12579]: Failed to fully start up daemon: Input/output error
[   74.665084] systemd-logind[12591]: Failed to enable subscription: Launch helper exited with unknown return code 1
[   74.665154] systemd-logind[12591]: Failed to fully start up daemon: Input/output error

**Comment by DennisLfromGA** [comment]
To see if you're using the latest version of 'crouton' -

Enter: `sudo sh ~/Downloads/crouton -V`
It should return:: `crouton: version 1-20160831210747~master:77150969`

**Comment by choas0422** [comment]
thats what it shows.

chronos@localhost / $ sudo sh ~/Downloads/crouton -V
crouton: version 1-20160831210747~master:77150969

**Comment by DennisLfromGA** [comment]
Okay, that's the latest and I'm out of ideas - sorry.

**Comment by choas0422** [comment]
darn... well... thanks anyways. I'll keep trying to get it to work. I'll report back if I have any more info.

**Comment by DennisLfromGA** [comment]
Great, please report back if you discover the problem, it'll help all of us.

**Comment by choas0422** [comment]
@dnschneid 
maybe the dev has some input...? or maybe an idea of where to start trouble shooting...?

**Comment by dnschneid** [comment]
Try running `mountpoint /sys/fs/selinux` outside of the chroot and see what it says.

**Comment by choas0422** [comment]
so I entered the shell but not the chroot and the output was:

/sys/fs/selinux is not a mountpoint

**Comment by dnschneid** [comment]
Try the latest version and see if that fixes things.

**Comment by choas0422** [comment]
I'm currently on version 1-20160831210747~master:77150969.

**Comment by dnschneid** [comment]
I literally just pushed a new version :)

**Comment by choas0422** [comment]
oh... lol. thanks! i'll give it a shot and let you know. and thanks for the speedy replies and thanks for this project in general you've really added a ton of missing functionality to the chromebooks.

**Comment by DennisLfromGA** [comment]
i had used that on the other PR https://github.com/dnschneid/crouton/pull/2735#issuecomment-242823908 but didn't think to suggest it again.

**Comment by dnschneid** [comment]
This *should* be fixed.  Please re-open if it's not.

**Comment by jharder91** [comment]
I can confirm that this resolved my issue. Thank you for the quick response and resolution!

**Comment by choas0422** [comment]
Issue fixed! Thank you very much!
