### ISSUE TITLE
kernel module: Missing /build folder when compiling with "make"

### ISSUE THREAD

**Issue by aleisterdev** [dnschneid/crouton#2761]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20160902144033~master:9f8e9a22
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,cli-extra,extension
host: version 8350.68.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-12320-gbb6b499 #1 SMP PREEMPT Tue Aug 2 21:12:32 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### Please describe your issue:
Cannot "make" drivers for a wifi usb adapters.

Error message: 
make[1]: *** /lib/modules/3.18.0-12320-gbb6b499/build: No such file or directory.  Stop.

#### If known, describe the steps to reproduce the issue:

Just try to "make" anything I assume. 
In this specific case, I'm trying to compile the drivers for ralink usb adapters:
http://www.mediatek.com/AmazonS3/Downloads/linux/DPO_RT5572_LinuxSTA_2.6.1.3_20121022.tar.bz2
Or even the older version of the drivers (that it's possible to find looking around internet and old forums).

There's always this issue with the missing "build" folder. I've tried to install the kernel headers, but:

(kali-rolling)kali@localhost:~$ sudo apt-get install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-3.18.0-12320-gbb6b499
E: Couldn't find any package by glob 'linux-headers-3.18.0-12320-gbb6b499'
E: Couldn't find any package by regex 'linux-headers-3.18.0-12320-gbb6b499'

So I've tried to install other linux headers and the build-essentials (don't remember which version of kernel headers as this is my third re-installation of the chroot, but they were suggested in the command line when I've tried to "apt-get install" the headers) and they ended up into another folder inside /lib/modules/.

Then I've:
ln -s /usr/src/linux-headers-2.6.38/ /lib/modules/3.18.0-12320-gbb6b499/build 

(the linux headers version in the first part of the command here is an example, I've used a recent version of the headers, something ending in rt-amd64 and other ending amd64 but I couldn't find which one. I've actually tried 2-3 different versions of kernel headers).

At this point I could go forward a bit more with the "make" process, but eventually it started to ask  for "gcc6" (that was already installed according to apt-get , but inside the required folder arrived only up to gcc5.h", so I've again made a link gcc6 pointing to gcc5). 
I've managed to get the make process a little bit more, but eventually I found another error.

I've done all of this also with a "jessie" installation, just to make sure that wasn't an issue of kali-rolling.

Sorry for the long post, but in the end I just need to understand how to compile files here on a chromebook with crouton as this missing "build" folder and the fact that the kernel has the name: 3.18.0-12320-gbb6b499 seems to create the issue here.

Any hints, help or workaround on how to successfully compile drivers here on kali-rolling, and the explanation of this missing /build folder inside the kali-rolling headers folder would be really appreciated, as it's been a week now that I'm working on this but we no luck.

**Comment by divx118** [comment]
@aleisterdev You cannot install headers from the kali repo. They won't work, the chroot is using the chromeos kernel and not a kali released kernel. So you have to build the headers yourself see https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86). Also you need to disable module_locking when you want to be able to load external modules. This is mentioned also on the linked page. Note that building the correct headers for the 3.18.0-xxxxx kernel is a pain. There is some kind of workaround mentioned on the above linked page. However I think the easiest way for you is to build the required modules on a normal amd64 linux PC with the chromeos kernel source and then copy them to your chromebook.

**Comment by aleisterdev** [comment]
Thank you very much for you reply! I'll look into the link you provided.
I hope I don't have to go to the other route as I don't have another amd64 linux PC to build the modules :/
I will update this ticket when I will make it work, so that the other people that may have this issue will know how to solve it.

**Comment by drinkcat** [comment]
@aleisterdev Did you manage to get it to work?

**Comment by aleisterdev** [comment]
Not at all, I kinda give up after a couple of weeks of forum surfing, tutorials, installations, errors, etc... I'm still trying to figure it out if it was worth it to buy the Chromebook :/

**Comment by GarethHards** [comment]
im having a issue as well bought a 6000Mbit/s wifi N usb antenna and ran a folder for it and named the folder and and then boom it says cant find kernal in the v7 ive got a v8 on my pi4 ubuntu 19.04, so is this antenna not seeing the updated version from 7 to 8 or does it work on 5.10.11-v7l+ only and not on 5.10.11-v8+
