### ISSUE TITLE
linux/compiler-gcc6.h: No such file or directory

### ISSUE THREAD

**Issue by aleisterdev** [dnschneid/crouton#2762]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20160902144033~master:9f8e9a22
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,cli-extra,extension
host: version 8350.68.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-12320-gbb6b499 #1 SMP PREEMPT Tue Aug 2 21:12:32 PDT 2016 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling as another instance is using it.
```

#### Please describe your issue:
I get en error about a missing gcc6.h when compiling 

#### If known, describe the steps to reproduce the issue:

While following this tutorial:
https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)

When arrived to the command:
$ make-kpkg --rootcmd fakeroot kernel_image kernel_headers

It exited with:

In file included from include/linux/compiler.h:54:0,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from include/linux/page-flags.h:8,
                 from kernel/bounds.c:9:
include/linux/compiler-gcc.h:107:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
compilation terminated.
Kbuild:35: recipe for target 'kernel/bounds.s' failed
make[3]: *** [kernel/bounds.s] Error 1
Makefile:1006: recipe for target 'prepare0' failed
make[2]: *** [prepare0] Error 2
make[2]: Leaving directory '/home/kali/kernel'
debian/ruleset/targets/common.mk:194: recipe for target 'debian/stamp/conf/kernel-conf' failed
make[1]: *** [debian/stamp/conf/kernel-conf] Error 2
make[1]: Leaving directory '/home/kali/kernel'
/usr/share/kernel-package/ruleset/minimal.mk:93: recipe for target 'debian/stamp/conf/minimal_debian' failed
make: *** [debian/stamp/conf/minimal_debian] Error 2
Failed to create a ./debian directory: No such file or directory at /usr/bin/make-kpkg line 970.

But of course:
(kali-rolling)kali@localhost:~/kernel$ sudo apt-get install gcc-6 g++-6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-6 is already the newest version (6.1.1-11).
g++-6 set to manually installed.
gcc-6 is already the newest version (6.1.1-11).
gcc-6 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

=================

That's not the first time that I had this issue, I had it also when compiling the drivers for my wifi adapter.
Can someone help me with this please? 
I'm compiling the kernel headers:
3.18.0-12320-gf988d48
That's the version I have on: $ uname -r
3.18.0-12320-gbb6b499

I know that the last bit is different and not sure if it matters.
The commit for that kernel was found with:
kali@localhost:~/kernel$ git checkout HEAD~675

Any other number different from 675 would have changed the "12320" part of the kernel version.

Thank you!

**Comment by aleisterdev** [comment]
I've managed to go forward with the make process using a symlink:

ln -s compiler-gcc5.h compiler-gcc6.h

inside the /linux folder.

I've got now another error:

arch/x86/kernel/ptrace.c:129:18: error: 'arg_offs_table' defined but not used [-Werror=unused-const-variable=]
 static const int arg_offs_table[] = {
                  ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors

But I'm not sure that it's still related to the gcc6 issue, probably not so I'm going to close this issue.

**Comment by divx118** [comment]
@aleisterdev You have ERROR_ON_WARNING set to yes. I guess it is somewhere set in the makeFile. You can safely disable it and try again building. All compiler warnings you get will be treated as errors and stop the build when ERROR_ON_WARNING is set.

**Comment by aleisterdev** [comment]
Thank you very much for your advice.
I had changed "CONFIG_ERROR_ON_WARNING=y" inside chromeos/config/base.config as suggested by the guide, but at every build it kept giving the error and when opened the file the changes were reverted back, not sure why.
After your comment here I then looked also inside the MakeFile and commented out a part about the -Werror and this made it work the make.

Unfortunately after an hour or so of compiling I had another error:

CC [M]  sound/pci/hda/hda_generic.o
In file included from sound/pci/hda/hda_generic.c:31:0:
include/linux/module.h:138:40: error: storage size of '__mod_hdaudio__snd_hda_id_generic_device_table' isn't known
   extern const struct type##_device_id __mod_##type##__##name##_device_table \
                                        ^
sound/pci/hda/hda_generic.c:5887:1: note: in expansion of macro 'MODULE_DEVICE_TABLE'
 MODULE_DEVICE_TABLE(hdaudio, snd_hda_id_generic);
 ^~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:257: recipe for target 'sound/pci/hda/hda_generic.o' failed
make[4]: *** [sound/pci/hda/hda_generic.o] Error 1
scripts/Makefile.build:402: recipe for target 'sound/pci/hda' failed
make[3]: *** [sound/pci/hda] Error 2
scripts/Makefile.build:402: recipe for target 'sound/pci' failed
make[2]: *** [sound/pci] Error 2
Makefile:965: recipe for target 'sound' failed
make[1]: *** [sound] Error 2
make[1]: Leaving directory '/home/kali/kernel'
debian/ruleset/targets/common.mk:295: recipe for target 'debian/stamp/build/kernel' failed
make: *** [debian/stamp/build/kernel] Error 2

Today I will look into this error as well, hopefully one step at the time I can make it to the end goal :)

Thanks again for your help!
