### ISSUE TITLE
Installed Crouton, get "no screens found" error

### ISSUE THREAD

**Issue by Qwerty-Space** [dnschneid/crouton#2764]
```
chronos@localhost / $ sudo edit-chroot -all
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20160902144033~master:9f8e9a22
release: sid
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8350.60.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-12318-g6183b25 #1 SMP PREEMPT Wed Jul 20 21:07:10 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

```

When running ```sudo enter-chroot startxfce4``` I get a ```no screens found(EE)``` error and ```unable to connect to X server```

#### If known, describe the steps to reproduce the issue:
I just typed ```sudo enter-chroot startxfce4```

Thanks!

**Comment by Qwerty-Space** [comment]
Here is my ```tmp/Xorg.crouton.1.log```
http://pastebin.com/raw/pPNiR2bm

**Comment by Qwerty-Space** [comment]
This fix works for Intel Chromebooks
Fixed by doing the following from crosh:
```
shell
sudo enter-chroot
sudo X -configure
sudo cp /root/xorg.conf.new /etc/X11/xorg.conf
sudo nano /etc/X11/xorg.conf
```
Then add a new line under line 21 (section "Module") you should see ```Load "glx"``` and on the new line type ```Load "intel"``` save and exit, then type
```
exit
sudo enter-chroot startxfce4
```
And it should work!

**Comment by bjines** [comment]
I am getting 
`/tmp/.X11-unix has suspicious ownership (not root:root), aborting `
when I use
`sudo X -configure`

**Comment by ealgase** [comment]
Note that this happens on Asus Chromebook Flips.

**Comment by dnschneid** [comment]
Could you please try updating with the latest crouton and re-open if you still hit the issue?
