### ISSUE TITLE
Lack of KVM Support for Chrome OS

### ISSUE THREAD

**Issue by AwlsomeAlex** [dnschneid/crouton#2769]
```
name: trusty
encrypted: no
Entering /media/removable/Linux/chroots/trusty...
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: armhf
xmethod: xorg
targets: touch,xfce
host: version 8350.68.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 2 21:07:06 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /media/removable/Linux/chroots/trusty...
```
#### Please describe your issue:

I'm trying to use an emulation programs called "virt-manager", but whenever I fire it up it gives me the following error on my ASUS Chromebook Flip:
"Unable to connect to libvirt.

Verify that:
- The 'libvirt-bin' package is installed
- The 'libvirtd' daemon has been started
- You are a member of the 'libvirtd' group."

I have the 'libvirt-bin' package installed,
The daemon can't be found "libvirtd: Unrecognized Service"
I added myself to the group.

Is it a problem with being on ARM? Because QEMU seems to work fine (but slow) in the command line. Do I need to compile an ARM Linux Kernel with KVM Enabled? Do I need to add a module to the Kernel? Help, I really wish to have virtualization on my Chromebook (Since QEMU is slow without KVM and Virtualbox requires 'x86'.

**Comment by darkgeek** [comment]
Nope, stock chrome os kernel doesn't have kvm built-in. However, there's a [page](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/running-virtual-machines-on-your-chromebook) introducing how you could run kvm by rebuilding chrome os kernel, if kvm is important to you, try it.

**Comment by DennisLfromGA** [comment]
The [page](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/running-virtual-machines-on-your-chromebook) that @darkgeek referenced above changes a couple of kernel flags that enables VMX support.
Another gentlemen (@divx118)  that contributes to crouton has experience with this and has provided a script that does it called '[change-kernel-flags]()' that might help.

**Comment by AwlsomeAlex** [comment]
@darkgeek Alright, I'll consider it, my main concern however is that it's Chrome OS **NOT** Chromium OS, means that the device I'm currently using is a Chromebook. What happens if I mess up the Kernel? How would I be able to recover it? Also I would like Virtualization, but would it even work for ARM-Based CPUs?

**Comment by DennisLfromGA** [comment]
@AwlsomeAlex,

> Also I would like Virtualization, but would it even work for ARM-Based CPUs?

I don't think it's easy to do on ARM devices unless the later kernels have added it.

> What happens if I mess up the Kernel? 

[Switching channels](https://support.google.com/chromebook/answer/1086915?hl=en) or doing a [full recovery](https://support.google.com/chromebook/answer/6002417?hl=en) would get you going again.

> How would I be able to recover it?   

You most likely won't be able to recover it, you'll have to do one of the two I mentioned above.

*Hope this helps,*
-**DennisL**
