### ISSUE TITLE
No keyboard or mouse movement Acer Chromebook 14

### ISSUE THREAD

**Issue by MattEbert94** [dnschneid/crouton#2770]
sudo edit-chroot -all produces the following:

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160902144033~master:9f8e9a22
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 8350.60.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-12318-g6183b25 #1 SMP PREEMPT Wed Jul 20 21:07:10 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 8350.60.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-12318-g6183b25 #1 SMP PREEMPT Wed Jul 20 21:07:10 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

My problem is that when I load into ubuntu with "sudo startunity", it loads up just fine, but then there is no mouse or keyboard functionality. The only thing that does work is pressing Alt to bring up the "Type a command" prompt at the top left.

A little history on this. I had ubuntu working fine on the chromebook just the way I wanted besides that fact that when I loaded in I had to type "synclient FingerLow=1 FingerHigh=5" into the terminal to make the mouse work, but I can deal with that. Then it said there was a new version of Ubuntu and I upgraded which made the whole thing not work with the "no user named "whoopsie" found" thing. I researched that a bunch and couldn't find a solution that worked. So I reset the chromebook to try again and now this happens. I can get the Alt button to work, but I can't get Ctrl + Alt + t to work to bring up the command prompt.

This is the output when I type "sudo startunity" if that helps at all. And as you probably saw from the top output, I have precise and trusty installed. When I had it working originally, I used trusty which I liked although I don't really know the difference between them too much. But I also tried precise to see if I could get that to work, but I couldn't.

[Output.txt](https://github.com/dnschneid/crouton/files/466056/Output.txt)

Any help is appreciated! Thanks

**Comment by MattEbert94** [comment]
Anyone?

**Comment by wiredin** [comment]
Have you reviewed this open issue? 
https://github.com/dnschneid/crouton/issues/2657

**Comment by drinkcat** [comment]
The keyboard issue is intriguing, but the trackpad issue is indeed covered in #2657.

@MattEbert94 Can you try again with the settings in #2759?
