### ISSUE TITLE
Run Unity on Xenial

### ISSUE THREAD

**Issue by idvoretskyi** [dnschneid/crouton#2771]
I'm going to run Ubuntu Xenial with Unity, but due to existing bugs (there's no package `unity-2d` in Xenial),  the installation fails.

How can I run Ubuntu Xenial with Unity manually?

**Comment by DennisLfromGA** [comment]
@idvoretskyi - Take a look at this similar issue for a possible solution: https://github.com/dnschneid/crouton/issues/2720#issuecomment-239538217

**Comment by drinkcat** [comment]
Let's duplicate to #2720.
