### ISSUE TITLE
OpenVPN connection with NetworkManager

### ISSUE THREAD

**Issue by idvoretskyi** [dnschneid/crouton#2772]
I'd like to establish OpenVPN connection from Crouton using NetworkManager - will it work?

Otherwise, which extra available options are for setting OpenVPN client on Crouton (expect of running OpenVPN on ChromeOS itself)?

**Comment by DennisLfromGA** [comment]
*Checkout these crouton wikis:*

- [Using Cisco AnyConnect VPN with openconnect](https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect)
- [Juniper Junos Pulse VPN with OpenConnect](https://github.com/dnschneid/crouton/wiki/Juniper-Junos-Pulse-VPN-with-OpenConnect)
- [VPNC](https://github.com/dnschneid/crouton/wiki/VPNC)

*Hope this helps,*
-**DennisL**
