### ISSUE TITLE
Failed to complete chroot setup

### ISSUE THREAD

**Issue by adunny** [dnschneid/crouton#2773]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160902144033~master:9f8e9a22
release: precise
architecture: amd64
targets: xfce
host: version 8530.81.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Wed Sep 7 16:51:22 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

After 10-15 minutes of installation, a bunch of archives are failed to fetch, and I am left with:
```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
```

**Comment by bennettscience** [comment]
Were the packages from the Ubuntu archives page? If so, I'm seeing the same thing. First error during the `chroot` setup was trying to fetch `http://archive.ubuntu.com/ubuntu/dists/precise/main.source/Sources`

Returned: `503 Service Unavailable [IP: 91.189.88.152.80]`

Each call to that IP failed.

**Comment by adunny** [comment]
Yep, all the packages were from the archives

**Comment by bennettscience** [comment]
Are you on a managed network (school, office, etc)? I tested at home and was able to install fine last night. It looks like the firewall on my office network was blocking direct socket connections to the ubuntu archive servers. Try a different network and see how it goes.

**Comment by drinkcat** [comment]
Yep, looks like some transient network error.
