### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by 1kastner** [dnschneid/crouton#2779]
```
chronos@localhost / $ sudo edit-chroot -all
name: debiane17
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/debiane17...
```

#### Please describe your issue:
The installation fails after a while stating

```
[...]
The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 libxext-dev libxfixes-dev libxi-dev linux-libc-dev:i386
  x11proto-fixes-dev x11proto-xext-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netsurf-gtk
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/debiane17...
```

#### If known, describe the steps to reproduce the issue:
I tried to install my environment by typing:
    `sudo sh ~/Downloads/crouton -e -r stretch -t e17 -n debiane17`
This was my only attempt to install the environment. Before this, I was running an ubuntu but I completely erased it.

**Comment by DennisLfromGA** [comment]
@1kastner,

Yes, you'll run into this issue with debian stretch and kali-rolling.
See https://github.com/dnschneid/crouton/issues/2513#issuecomment-230125641 for a way around it.

-**DennisL**

**Comment by 1kastner** [comment]
The same happens when I run
`sudo sh ~/Downloads/crouton -e -r kali-rolling -t e17 -n kalie17`

**Comment by 1kastner** [comment]
Ah, the refresh function did not work, thanks for the reply, I will try my way around!
