### ISSUE TITLE
WP Config WordPress Auto Update Issue

### ISSUE THREAD

**Issue by mtiii** [dnschneid/crouton#2780]
I have about 3 dozen WordPress websites, I am trying to make it quick to update all of the website.

In the WP Config file I have `define('DISALLOW_FILE_MODS',true);` added because I can not have users adding plugins to the website, but of course this disable all auto updates.

I am trying to quickly update all websites by temporarily commenting out the `//define('DISALLOW_FILE_MODS',true);` and adding `define( 'WP_AUTO_UPDATE_CORE', true );` to the WP Config file... though when I do this WordPress doesn't automatically update (maybe it waits 24hr or something, I don't know).

Is there a way to have WordPress automatically update the second comment out `//define('DISALLOW_FILE_MODS',true);` and add  `define( 'WP_AUTO_UPDATE_CORE', true );`?

Any help would be appreciated! Thank you in advance!

**Comment by drinkcat** [comment]
#262.
