### ISSUE TITLE
"Correct way of shutting down a chroot" should perhaps be added to the README / wiki? 

### ISSUE THREAD

**Issue by mikehgentry** [dnschneid/crouton#2783]
Hi,

I've had no corruption shutting down my system with a chroot running, but I'm wondering whether I've just been lucky (and I haven't been brave enough to try on an sd card). The way I'm doing it is switching back to ChromeOS with ctrl-alt-shift-F1, holding the power button until it logs me out, then holding it again until the system shuts down.

I opened this question [1] on Crouton Users, and had a search through the issues here, but the only reference I've found is rather old and marked as fixed [2].

Is it safe to do what I'm doing? I think perhaps it deserves a mention in the wiki or the README, but I suppose if I'm the only person stupid enough to be asking... ;)

Thanks for the great work on Crouton.

[1] https://plus.google.com/104783710709588163822/posts/69sMUrL6ySx
[2] #237

**Comment by divx118** [comment]
Best way is to just logout of your chroot first. When logging out (logout button in your chroot windows manager) of the chroot everything should be nicely shutdown/unmounted related to your chroot. Then it will be safe to shutdown your chromebook. That said I also have many times done a forced shutdown and had never any problems with a corrupted chroot, but the method above is the proper way.

**Comment by mikehgentry** [comment]
OK, thanks. What do you think of adding that to the docs somewhere (maybe under 'Tips', or in the wiki)? As far as I can tell it isn't clear from them at present, and seems like a significant omission to me; I couldn't figure out whether everything was being unmounted cleanly from the logs I looked at, though I may well have been looking in the wrong places.

**Comment by mikehgentry** [comment]
OK, on the principal of 'being bold' I went ahead and added a page - I hope that's OK.

https://github.com/dnschneid/crouton/wiki/Shutting-Down-Safely

Obviously feel free to correct it or nuke it outright if you think there's a better place for it, or it's just clutter.

Thanks.

**Comment by DennisLfromGA** [comment]
@mikehgentry - Looks very good, thanx. I made a couple of small tweaks.

**Comment by idvoretskyi** [comment]
@mikehgentry thank you.

**Comment by mikehgentry** [comment]
No worries! 

The only other thing that springs to mind that I think should be added is what to do in the event of a crash. Occasionally when I've been running Steam, for example, I've got things into a pretty messy state where I can't switch back to Chrome, and I've been forced (apparently) to hold the power button to switch off.

Certain sysrq type commands work in the chroot - altg-f10-r, for example. There's a list here, which I assume is only partial:

https://bugs.chromium.org/p/chromium/issues/detail?id=471876

If any of you know if there are any better options than just forcing power off (e.g. syncing disks, closing user processes), I for one would be very grateful if you added it.

Cheers!

**Comment by DennisLfromGA** [comment]
If you can get to VT2 using <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>F2/-></kbd> then you might be able to kill the chroot(s) from the shell. 
There's a crouton script called `unmount-chroot` for this, here's the help message for it -
```
Unmounts one or more chroots, optionally killing any processes still running
inside them.

By default, it will run in interactive mode where it will ask to kill any
remaining processes if unable to unmount the chroot within 5 seconds.

Options:
    -a          Unmount all chroots in the CHROOTS directory.
    -c CHROOTS  Directory the chroots are in. Default: /usr/local/chroots
    -f          Forces a chroot to unmount, potentially breaking or killing
                other instances of the same chroot.
    -k KILL     Send the processes SIGKILL instead of SIGTERM.
    -p          Print to STDOUT the processes stopping a chroot from unmounting.
    -t TRIES    Number of seconds to try before signalling the processes.
                Use -t inf to be exceedingly patient. Default: 5
    -x          Keep the root directory of the chroot mounted.
    -y          Signal any remaining processes without confirmation.
                Automatically escalates from SIGTERM to SIGKILL.
```
To  kill all running chroots, try using something like `unmount-chroot -afk`
It will list the processes and ask what you'd like to do with them.

I've also had luck with just killing the `croutonfbserver` process(es).

Hope this helps,
-**DennisL**

**Comment by mikehgentry** [comment]
Thanks for the response - and apologies for taking so long to reply.

I'll fill in what I can once I've had a chance to test things (I only have one Chromebook, and not much space or time with which to smash chroots up purely for testing purposes - kinda easier to wait till they crash of their own accord :)

Nonetheless, the input is appreciated.
