### ISSUE TITLE
mysql xml parsing using Extractvalue function

### ISSUE THREAD

**Issue by varun2494** [dnschneid/crouton#2784]
```
while(count)
SELECT valuestring = concat(valuestring , ' , ') +  ExtractValue(xml_content,concat('//ROOT/Table[$',counter,']/',Column_Names))
FROM columnlist where Column_Names IS NOT NULL;
```
using ExtractValue in the query gives out an error stating  Error Code:1105 ONLY constant XPATH queries are supported"

can i get any more info as to how i can fix this problem

**Comment by DennisLfromGA** [comment]
Does this specifically pertain to 'crouton'?
If not, please close this issue and search elsewhere, thanx.

**Comment by drinkcat** [comment]
#262
