### ISSUE TITLE
Kodi black screen...

### ISSUE THREAD

**Issue by bob1966** [dnschneid/crouton#2786]
Please paste the output of the following command here: sudo edit-chroot -all
name: scotty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/scotty...
crouton: version 1-20160902144033~master:9f8e9a22
release: stretch
architecture: armhf
xmethod: xorg
targets: xfce,x11
host: version 8350.68.0 (Official Build) stable-channel nyan_big 
kernel: Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:26:16 PDT 2016 armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/scotty...
#### Please describe your issue:

when I try and run kodi, all I get is a black screen.
#### If known, describe the steps to reproduce the issue:

sudo apt install kodi -y on debian stretch with xfce.

**Comment by drinkcat** [comment]
Hard to tell. Might be best to file a bug upstream.
