### ISSUE TITLE
Selenium 3.0 beta version is not supporting implicit wait and Wait for Page load. Does anybody knows how to use implicit wait in selenium 3.0 beta which uses geckodriver. Following code is not working. 

### ISSUE THREAD

**Issue by anukriti-chawla** [dnschneid/crouton#2788]
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

**Comment by FFLSH** [comment]
@anukriti-chawla What was the resolution for this? I am having the same issue.

**Comment by dnschneid** [comment]
@FFLSH: see #262

**Comment by FFLSH** [comment]
@dnschneid I don't get it

**Comment by DennisLfromGA** [comment]
@FFLSH, This topic and the resolution is not relevant.
It should probably be researched elsewhere since this forum is for 'crouton' issues.
