### ISSUE TITLE
With Android on Chrome >= 53 crouton should no longer install precise by default

### ISSUE THREAD

**Issue by fulv** [dnschneid/crouton#2789]
I just went through the ordeal of salvaging my _precise_ chroots which became unusable after I upgraded my ASUS Flip to Chrome 53 (i.e. with Android): #2787 

The bottom line is _precise_ can not be used when Android is installed in ChromeOS.

Therefore, _precise_ should not be the default when creating a chroot with crouton.

See #2787 for details.

**Comment by bairaelyn** [comment]
I have a question relating to this. After updating to Chrome 53, I'm experiencing exactly the same problem as in [#2787](https://github.com/dnschneid/crouton/issues/2787). (I have an encrypted _precise_ chroot installed locally and want file access, so the powerwashing solution won't help me any.)

Are there any plans to update the crouton installer to work with _precise_ and Chrome 53, or is this a lost cause?

**Comment by fulv** [comment]
Here is what I would do:  Make a tarball of your _precise_ chroot and put it on external storage.  It probably lives in `/mnt/stateful_partition/crouton/chroots/precise`.  Once you have it backed up, you should be able to powerwash, downgrade to 52, and restore the backup.  Now you can `enter-chroot` again, and do a `sudo do-release-upgrade`.  You should be able to do it all using the guest account.  
By the time you are done with the upgrade to _trusty_, chromeos will have downloaded 53 again, and you should be ready to re-upgrade.  In my case, the second upgrade from 52 to 53 did not erase my internal storage, so I did not need to do another restore from backup and could carry on happily from there.

Caveat emptor and all that...  In particular, I have not yet used encrypted chroots, so I don't know if that makes anything more difficult.

**Comment by fulv** [comment]
Here is another one: #2794 
These are going to start mounting.

**Comment by bairaelyn** [comment]
Ah, my mistake. I thought all scripts for the chroot were broken, but since edit-chroot still works I at least have a backup now. I tried your solution, only to find that after multiple "Powerwash + Revert"s I always have exactly the same ChromeOS version, namely 53 (with no internet connection throughout), and the same chroot access problems. I'm not sure why it won't revert, but that's a whole other problem.

So my question still stands. I'll hope that there will be a fix eventually.

**Comment by dnschneid** [comment]
Well, the issue with installing precise is at least fixed.  Xenial as the default release is something we're considering.

**Comment by MigrationKing** [comment]
Xenial kept crashing with installation on 53. Here is the release version where I experienced the crashes.
Ver. 53.0.2785.154 (64-bit), Plat: 8530.96.0, FW Google_Banjo.5216.334.4. May want to test. I'm troubleshooting the package that kept failing now.

**Comment by dnschneid** [comment]
Yeah, xenial has a bunch of issues...there's even a [milestone](https://github.com/dnschneid/crouton/milestone/9) open for tracking fixing them.
