### ISSUE TITLE
UID 1000 error code please help!

### ISSUE THREAD

**Issue by Jerememe** [dnschneid/crouton#2791]
```

```When I try to use the command _sudo startunity_ I get the error dode UID 1000 not found in precise.

I really want to run a game (PTCGO) on my chromebook. I would really appreciate some help! Thanks!

**Comment by DennisLfromGA** [comment]
You're crouton installation probably didn't get far enough along to add a user.

You can try the get into it and let it finish setting up using: `sudo enter-chroot -u root`

If that doesn't work then you can try updating the chroot with crouton using: `sudo sh ~/Downloads/crouton -u`

**Comment by llkkdd7** [comment]
I had this same problem, try downloading the crouton Chrome extension and using
 `sudo sh ~/Downloads/crouton -n trusty -t kde,extension`
and/or mapping the download to an external device [here](https://www.maketecheasier.com/map-crouton-installation-external-device-chromebook/).
