### ISSUE TITLE
Google Pixel LS 2015 Chrome v53 chroots are running into lots of issues compared to v52

### ISSUE THREAD

**Issue by ryanphjohnson** [dnschneid/crouton#2792]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: eigth
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/eigth...
crouton: version 1-20160518095657~master:fd37bb79
release: precise
architecture: amd64
xmethod: xiwi
targets: xfce,touch,xiwi,x11,unity,xorg
host: version 8530.90.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 20 00:35:43 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

NOTE: this command hung here before printing out anymore.

#### Please describe your issue:
On Google Chromebook Pixel 2 LS on Chrome v53, chroots are throwing way more errors than on v52. New chroots can't install new software like "man-db". It throws security errors like "cannot get security labeling handle: No such file or directory". 

Also, its more difficult to even create new chroots, they complain about "groupadd: failure while writing changes to /etc/group".

Lastly, Xiwi doesn't seem to work at all. It throws this error:
Loading extension GLX
(EE) 
Fatal server error:
(EE) SELinux: Failed to open x_contexts mapping in policy
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 

#### If known, describe the steps to reproduce the issue:
Update Chrome to v53, create a new chroot using trusty, then try to install "man-db".

**Comment by gestapolur** [comment]
Seems you're not using latest crouton release, run `sudo sh -e ~/Downloads/crouton -n <chroot_name> -u` (see [wiki](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release#upgrade-instructions--be-wary-with-this-process--many-users-experience-terminal-issues-with-x-following-the-upgrade)) to update and see if any issue exists.

**Comment by ryanphjohnson** [comment]
Thanks, I tried that, and it looks like it had an error:

chronos@localhost / $ sudo sh -e ~/Downloads/crouton -n nerd -u
/usr/local/chroots/nerd already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-x11 into the chroot...
Installing startcli into the host...
Installing croutonpowerd into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
Setting up libpipeline1:amd64 (1.3.0-1) ...
dpkg (subprocess): cannot set security execution context for maintainer script: Invalid argument
dpkg: error processing package libpipeline1:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 libpipeline1:amd64
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/nerd...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/nerd...

**Comment by ryanphjohnson** [comment]
This seems like an important discovery/piece of information. Crouton can't update itself:

rj@localhost:~$ croutonversion -u -d -c
crouton: version unknown
Retrieving latest version of crouton-unknown
--2016-09-28 09:51:40--  https://github.com/dnschneid/crouton/raw/releases/crouton-unknown
Resolving github.com (github.com)... 192.30.253.113
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-28 09:51:40 ERROR 404: Not Found.

Failed to retrieve latest version of crouton-unknown

**Comment by ryanphjohnson** [comment]
So after some more digging it looks like the issue may be caused/related to unable to update chroots. I ran this and it threw an error:

chronos@localhost ~/Downloads $ sudo enter-chroot -n nerd sudo apt-get update
Entering /mnt/stateful_partition/crouton/chroots/nerd...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] 
Preparing chroot environment...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
Setting up libpipeline1:amd64 (1.3.0-1) ...
dpkg (subprocess): cannot set security execution context for maintainer script: Invalid argument
dpkg: error processing package libpipeline1:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 libpipeline1:amd64
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
sudo: no tty present and no askpass program specified
Unmounting /mnt/stateful_partition/crouton/chroots/nerd...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/nerd...

**Comment by ryanphjohnson** [comment]
A quick google of 'Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory' says to just create that folder and the dbus_contexts file but I run into a permissions issue when trying to do that:

"mkdir: cannot create directory ‘/etc/selinux/targeted’: Read-only file system"

**Comment by ryanphjohnson** [comment]
So I think at this point I may be in a pretty bad spot. I can't update my crouton, because it doesn't know what croutonversion its on, and I can't create new chroots because of this "groupadd: failure while writing changes to /etc/group". My current version is "crouton: version 1-20160518095657~master:fd37bb79". @DennisLfromGA @drinkcat Is there a way to update my crouton version from outside a chroot?

**Comment by ryanphjohnson** [comment]
Update: I've managed to solve the updating issue by downloading a new version of crouton. Xiwi still isn't working however. It throws this error: 

(signal)rj@localhost:~$ find . -name "eclipse"
./Downloads/workspace/android-studio/plugins/android/lib/templates/eclipse
./Downloads/workspace/android-studio/gradle/m2repository/org/eclipse
./Downloads/workspace/mxnet/opencv-2.4.13/samples/java/eclipse
./Downloads/eclipse-mars/eclipse
./Downloads/eclipse-mars/eclipse/eclipse
./Downloads/eclipse-mars/eclipse/configuration/org.eclipse.osgi/193/0/.cp/org/eclipse
./Downloads/eclipse-mars/eclipse/configuration/org.eclipse.osgi/208/0/.cp/org/eclipse
./Downloads/eclipse-mars/eclipse/configuration/org.eclipse.osgi/690/0/.cp/tern/eclipse
./Downloads/eclipse-mars/eclipse/configuration/org.eclipse.osgi/336/0/.cp/org/eclipse
./Downloads/eclipse-mars/eclipse/configuration/org.eclipse.osgi/545/0/.cp/org/eclipse
(signal)rj@localhost:~$ PATH=$PATH:./Downloads/eclipse-mars/eclipse
(signal)rj@localhost:~$ xiwi eclipse

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 20 00:35:43 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=b3b26307-1215-674f-b9be-f39cd7a11fc7/PARTNROFF=1 hashtree=PARTUUID=b3b26307-1215-674f-b9be-f39cd7a11fc7/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=f43d6349137dbf3bd06b1529a9761e162be0a782 salt=636d4bd47524c0c5996453f1e379c29066445733917f12d6e43d806e031da5df" noinitrd vt.global_cursor_default=0 kern_guid=b3b26307-1215-674f-b9be-f39cd7a11fc7 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Sep 28 12:08:45 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,cli-extra,keyboard,x11
host: version 8530.90.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 20 00:35:43 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

**Comment by ryanphjohnson** [comment]
Getting closer. I've added several more targets to my chroot, and the xiwi will now briefly open before closing again:

(signal)rj@localhost:~$ xiwi eclipse

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 20 00:35:43 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=b3b26307-1215-674f-b9be-f39cd7a11fc7/PARTNROFF=1 hashtree=PARTUUID=b3b26307-1215-674f-b9be-f39cd7a11fc7/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=f43d6349137dbf3bd06b1529a9761e162be0a782 salt=636d4bd47524c0c5996453f1e379c29066445733917f12d6e43d806e031da5df" noinitrd vt.global_cursor_default=0 kern_guid=b3b26307-1215-674f-b9be-f39cd7a11fc7 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Sep 28 14:31:46 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,cli-extra,keyboard,x11,core,audio,touch,xorg
host: version 8530.90.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 20 00:35:43 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
deciding for version 4 due to this line: # i3 config file (v4)
09/28/16 14:31:50 - ERROR: Could not translate string to key symbol: "button2"
Error: target STRING not available
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Eclipse:
An error has occurred.  See the log file
/home/rj/Downloads/eclipse-mars/eclipse/configuration/1475091111614.log
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

**Comment by ryanphjohnson** [comment]
All problems seem to have resolved themselves. The last issue was an issue specific to eclipse, which I was able to fix. Thanks for the help
