### ISSUE TITLE
Chroot unmounts immediately

### ISSUE THREAD

**Issue by MattEbert94** [dnschneid/crouton#2795]
```
sudo edit-chroot -all outputs:
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 8530.81.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-12632-g42a6df4 #1 SMP PREEMPT Wed Sep 7 16:51:08 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
I have had this problem happen multiple times to me and every time the only solution I have found is to delete the chroot and reinstall it. It then works for a couple days before breaking again. When I run "sudo startunity", this is the output:

sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/trusty...
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

I can sudo enter-chroot -n trusty just fine and use it that way, but I really like having a graphical way to see the linux OS.

I installed with this: 
sudo sh -e ~/Downloads/crouton -r trusty -t unity

I have also tried:
sudo sh -e ~/Downloads/crouton -r trusty -t unity-desktop
which has the same problem after a few days.

I thought at first that it was because I wasn't "logging out" of the chroot when I was done using it, but this most recent problem happened even after I tried logging out.

Thanks for the help!

**Comment by mwhipple** [comment]
Have you tried running startx after entering the CLI chroot? There's likely to be helpful messages in the console or the X log.

**Comment by MattEbert94** [comment]
@mwhipple Can you elaborate on how to do this? I googled it and looked in the issues forum within this repository and couldn't find anything. Thanks!

**Comment by DennisLfromGA** [comment]
@MattEbert94,

I think what @mwhipple was referring to is something like this:

`sudo enter-chroot -n trusty`
`startx`

You might also try this:

`sudo enter-chroot -n trusty`
`startunity`

Then look for errors or warnings that might pop up.

-**DennisL**

**Comment by MattEbert94** [comment]
Omg thank you so much. Entering the chroot and then running startunity worked for me

**Comment by DennisLfromGA** [comment]
@MattEbert94,

Great & that's good to know.
It would be good to know why `startunity` is not working from outside the chroot too.
If anyone else runs into this problem report it here.

Thanx,
-**DennisL**
