### ISSUE TITLE
touchpad loosing precision after starting chroot

### ISSUE THREAD

**Issue by Phill23** [dnschneid/crouton#2796]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: ubuntu
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/ubuntu...
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce
host: version 8530.81.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-12632-g42a6df4 #1 SMP PREEMPT Wed Sep 7 16:55:22 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
#### Please describe your issue:

after starting a chroot the touchpad gets insensitive and sloppy in booth chroot and chrome.
tried dis-/enable tap-to-click, did reboots, after 10sec drumrol  on the touchpad it gets a bit better but only temporarily.
Don't know if it is Braswell related.

thanks in advance   
#### If known, describe the steps to reproduce the issue:

installed chroot with targets and started it.
extension is installed in chrome.

**Comment by DennisLfromGA** [comment]
Your Lenovo Chromebook 11 (reks) may be running into the same issue that discussed here:  

> [Mouse moving doesn't work #214](https://github.com/dnschneid/crouton/issues/214)

There's a temporary workaround here: https://github.com/dnschneid/crouton/issues/214#issuecomment-19280624, a permanent fix may be in place eventually.

Please track this issue here: https://github.com/dnschneid/crouton/issues/214

**Comment by Phill23** [comment]
Sorry @DennisLfromGA but I tried that. The touchpab is working just not very well.
The BAD thing is that after switching back to Chrome OS the behaviour persists meaning it is not only affecting the chroot but the whole system even after rebooting.
It takes some hours to go back to normal.

**Comment by DennisLfromGA** [comment]
@Phill23,

> Sorry @DennisLfromGA but I tried that. The touchpab is working just not very well.

Wish we'd have known what you already tried, please let us know if you have any other pertinent info.

> The BAD thing is that after switching back to Chrome OS the behaviour persists meaning it is not only affecting the chroot but the whole system **even after rebooting.
It takes some hours to go back to normal.**

If it happens after a reboot, maybe it's not related to 'crouton'.
