### ISSUE TITLE
Touchpad settings for ASUS Chromebook C202SA

### ISSUE THREAD

**Issue by dcecile** [dnschneid/crouton#2798]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,extension,xiwi,xfce,lxde
host: version 8530.93.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-12637-gab5706d #1 SMP PREEMPT Mon Sep 26 14:33:35 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

I'm using a ASUS Chromebook C202SA, and I've installed the Xorg version of XFCE. When I try to run it with `sudo startxfce -X xorg`, the touchpad doesn't work.

The touchpad started responding after I edited `/usr/local/bin/croutonxinitrc-wrapper` according to [a comment](https://github.com/dnschneid/crouton/issues/214#issuecomment-232519598) in #214, but the acceleration is too slow.

To get things "on par" with ChromeOS behaviour, there might be a few things to pursue:

1. Is it possible to find out the ChromeOS settings for acceleration?
2. Is it possible to double check the ChromeOS settings for high/low sensitivity?
3. Can any ChromeOS user-configurable settings (e.g. scroll direction) be ported automatically to the chroot?
4. Do the [other laptops mentioned](https://github.com/dnschneid/crouton/issues/214#issuecomment-232519598) also need a fix?

**Comment by DennisLfromGA** [comment]
> Is it possible to find out the ChromeOS settings for acceleration?
> Is it possible to double check the ChromeOS settings for high/low sensitivity?
> Can any ChromeOS user-configurable settings (e.g. scroll direction) be ported automatically to the chroot?

I don't know how to obtain the CrOS values but as far as I can tell there are no user configurable settings in CrOS.
> Do the other laptops mentioned also need a fix?

It looks like falco and peppy have been merged but your terra and the others in that comment still need a pull request.

**Comment by dcecile** [comment]
These are the user-configurable trackpad settings that I was thinking of:
* speed
* tap-to-click
* traditional/Australian scrolling
* tap dragging
* auto-click-on-motion-end

**Comment by DennisLfromGA** [comment]
@dcecile,

Apart from 'speed', those options can be configured in Settings, see below -

![screenshot 2016-10-07 at 12 41 41 am](https://cloud.githubusercontent.com/assets/3418772/19179044/2db6111a-8c27-11e6-944f-0c6d0a3bd2ad.png)

and

![screenshot 2016-10-07 at 12 43 10 am](https://cloud.githubusercontent.com/assets/3418772/19179056/4f1df99e-8c27-11e6-9446-b7dc65b0e680.png)

But, I don't know where those values are stored nor how to retrieve them for porting into a chroot.

-**DennisL**

**Comment by dcecile** [comment]
OK, I see. I took a quick peek at the [extension APIs](https://developer.chrome.com/extensions/api_index), and it doesn't seem like there's anything public for these settings.

**Comment by drinkcat** [comment]
I don't think there is a good way to directly mirror the settings (except maybe traditional/Australian scrolling), as the drivers in Xorg and Chromium OS are quite different...

`synclient` provides a bunch of parameters, you should try to use that.

**Comment by dcecile** [comment]
👍 OK, I'll set up a custom configuration for my `synclient`. I've done it before on a different laptop, so I don't think it will be a problem for me.

**Comment by dcecile** [comment]
Sorry for mixing two concerns into one issue; how about these `/usr/local/bin/croutonxinitrc-wrapper` changes?

> It looks like falco and peppy have been merged but your terra and the others in that comment still need a pull request.
