### ISSUE TITLE
Change CTRL+ALT+SHIFT+<- Hotkey?

### ISSUE THREAD

**Issue by jprichardson** [dnschneid/crouton#280]
Is it possible to change the `Change CTRL+ALT+SHIFT+<-` hotkey or even better map it to a three finger left or right swipe sorta like switching workspaces on a Mac? (Probably wishful thinking).

**Comment by MikRoscope** [comment]
I have the same issue as @jancona mentioned. Modifying xbindkeysrc.scm works for switching from chromeos to chroot but wont work for the other way. I might add that previous key combination (Ctrl-Alt-F2) was much better than the four key one (Ctrl-Alt-Shift-F2). I can manage three keys with one hand but four keys no way! Was this change necessary?

**Comment by dnschneid** [comment]
Look at /usr/local/bin/croutontriggerd in the chroot to fix the second half.  The four-finger shortcut is necessary because pretty much everything else potentially conflicts with Chromium OS.

**Comment by Charlesetc** [comment]
I've been able to change the key combination on the linux side by modifying the xbindkeysrc.scm. 
Is there a similar file for changing the hotkey in chrome os?

**Comment by taydakov** [comment]
@Charlesetc see the previous answer by @dnschneid 
go to the chroot (your second OS) and edit
1. /etc/crouton/xbindkeysrc.scm file to set up chroot->ChromeOS transition
2. /usr/local/bin/croutontriggerd file to set up ChromeOS->chroot transition

**Comment by taydakov** [comment]
But I found that using CTRL+ALT+SHIFT on the right side is pretty comfortable. So I gonna leave it like this :)

**Comment by bmarons** [comment]
@taydakov what do you edit in /usr/local/bin/croutontriggerd

**Comment by taydakov** [comment]
@bmarons I'm sorry but I forgot already :( I should have posted it right away

**Comment by ConnorGutman** [comment]
Hello from the future! To anyone else wondering how to edit /usr/local/bin/croutontriggerd to replace F1 & F2 with Left & Right you just need to alter lines 34, 35, 99, and 100:

`KEY_F1=59` -> `KEY_LEFT=105`
`KEY_F2=60` -> `KEY_RIGHT=106`

`$TYPE == $TYPE_EV_KEY && $KEY == $KEY_F1         {  p = $STATE; update() }` -> `$TYPE == $TYPE_EV_KEY && $KEY == $KEY_LEFT         {  p = $STATE; update() }`

`$TYPE == $TYPE_EV_KEY && $KEY == $KEY_F2         {  n = $STATE; update() }` -> `$TYPE == $TYPE_EV_KEY && $KEY == $KEY_RIGHT         {  n = $STATE; update() }`

If you plan on utilizing another hotkey you can figure out the keyboard code by adding `$TYPE == $TYPE_EV_KEY { print $KEY }` to the bottom of /usr/local/bin/croutontriggerd before the double quote. Reboot your device, spin up the chroot, and it will log the keys you press to crosh. 🙌
