### ISSUE TITLE
Android Chroot [Question]

### ISSUE THREAD

**Issue by DanHolli123** [dnschneid/crouton#2800]
is there any way of running Android in crouton so I can have it in a window or by using ctrl+alt+shift+f1/f2?
I would prefer using RemixOS  or if not something made for a more desktop friendly environment, even though I do have a touchscreen Chromebook

**Comment by drinkcat** [comment]
We don't have any plans to support that as part of crouton (especially now that ARC++ is shipping on many devices).

But, for sure, could be an interesting project ,-)

**Comment by DanHolli123** [comment]
I would still like to do it if it is possible

**Comment by DanHolli123** [comment]
I would just need some help to do it
