### ISSUE TITLE
Cannot Install Kali On Chromebook (UID 1000 Error)

### ISSUE THREAD

**Issue by D3F4L7** [dnschneid/crouton#2801]
```
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20160902144033~master:9f8e9a22
release: kali-rolling
architecture: amd64
targets: xiwi
host: version 8530.81.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Sep 7 17:09:28 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20160902144033~master:9f8e9a22
release: kali-rolling
architecture: amd64
targets: xfce
host: version 8530.81.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Sep 7 17:09:28 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
After several hours of messing with it, I still cannot seem to be able to install kali-rolling on my Acer Chromebook. I've tried re-installing crouton, as well as removing and re-installing kali-rolling, but I've had no luck with either. I've attached a few photos of the errors that I receive when I either install or update the chroot. I also get the "UID 1000 not found in kali-rolling" error that I've seen around here, and even after going through all the troubleshooting given, I still haven't had any luck. I wouldn't consider myself a pro in Linux by any means, so some of what was thrown out to me in errors is completely foreign to me, so I figured I'd ask and see if anyone had any suggestions. Thanks in advance!

#### If known, describe the steps to reproduce the issue:
The attached files detailing the issue can be reproduced using:

sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce

but adding -u to the end of that command produces the same errors as well.
![screenshot 2016-10-04 at 2 02 49 am](https://cloud.githubusercontent.com/assets/13984803/19064574/307fcc94-89dc-11e6-9c32-29ecad4e9d5a.png)
![screenshot 2016-10-04 at 2 03 09 am](https://cloud.githubusercontent.com/assets/13984803/19064577/3710e138-89dc-11e6-9ee0-c3c7f42cf230.png)
This is the error I receive if I try and use the "sudo startxfce4" command:
![screenshot 2016-10-04 at 2 43 56 am](https://cloud.githubusercontent.com/assets/13984803/19064623/70c8738c-89dc-11e6-8093-c3204e727fbf.png)

**Comment by DennisLfromGA** [comment]
It seems to be getting a lot of hash sum mismatch errors from the source files so the packages don't install and the chroot installation aborts before a user is added. Hopefully, this was just temporary, did you get it working?

**Comment by D3F4L7** [comment]
No, I never ended up getting it to work so I just went ahead and downloaded another distro and found packages that included all the Kali tools that I could want to work with. I'm considering going back again sometime and maybe trying it again, but for now this workaround seems to be doing the trick.

**Comment by DennisLfromGA** [comment]
@D3F4L7,

Sorry for your troubles but glad you found a way around it.
And thanx for getting back to us with your resolution.

-**DennisL**
