### ISSUE TITLE
Commands(Question)

### ISSUE THREAD

**Issue by Joshua420** [dnschneid/crouton#2802]
When i go into crosh and type shell everything is fine, but when i type the second command it says,
 sh: Can't open /home/chronos/user/Downloads/crouton
What should i do? Also i typed all commands available and i was in developer mode. Also i tried it when i had crouton downloaded and not downloaded

**Comment by D3F4L7** [comment]
Did you do all of this using the sudo command? I'm not entirely sure if that would fix the problem, but I feel like I vaguely recall having the same issue.

**Comment by DennisLfromGA** [comment]
1. download 'crouton' from here: https://goo.gl/fd3zc
2. open a crosh session by pressing: <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>T</kbd>
3. open a shell session by entering: `shell`
4. enter crouton and your installation options: `sudo sh ~/Downoads/crouton ...`

**Comment by DennisLfromGA** [comment]
Also, for a lot of good info., checkout the [README]() and the [Crouton Command Cheat Sheet](https://github.com/dnschneid/crouton/wiki/Crouton-Command-Cheat-Sheet).
