### ISSUE TITLE
FATAL server error: no screens found

### ISSUE THREAD

**Issue by caesared** [dnschneid/crouton#2805]
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Sep 26 14:27:40 PDT 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=85cc39d6-3d4f-9a48-88d6-89dac40f82e2/PARTNROFF=1 hashtree=PARTUUID=85cc39d6-3d4f-9a48-88d6-89dac40f82e2/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=4748f77f4dfa972ea2ae1aa9752d0a93cbccf438 salt=c3fb0f7bee896381b632add97716756e645eff0c24cc59eb271101368b11604d" noinitrd vt.global_cursor_default=0 kern_guid=85cc39d6-3d4f-9a48-88d6-89dac40f82e2  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Oct  5 18:46:53 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX

Fatal server error:
no screens found
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Server terminated with error (1). Closing log file.

/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

#### Please describe your issue:
Just never get in the ubuntu after completing the installation. The error occurs when i "sudo startunity" 
btw Asus c201 with ARM cpu

**Comment by tdingman** [comment]
Experiencing the same issue with a fresh install of trusty with xfce on a Pixel 2 using the newest version of crouton.

**Comment by DennisLfromGA** [comment]
Duplicate, please track this issue here: https://github.com/dnschneid/crouton/issues/1978
And see this for a temporary fix: https://github.com/dnschneid/crouton/issues/1978#issuecomment-244761453
