### ISSUE TITLE
Install is unable to establish SSL connection 

### ISSUE THREAD

**Issue by Krob99** [dnschneid/crouton#2808]
```
sudo sh ~/Downloads/crouton -t xfce
```

#### Please describe your issue: It gets down to Fetching CRAS then cant establish SSL connection. Here is the last few lines

Reading package lists... Done                                                                                                                       
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version.
ca-certificates is already the newest version.
sudo is already the newest version.
wget is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch f9354dd7aeb4842b42204e8b4cb89ee2f0a4c5c8)...
--2016-10-07 11:42:49--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/f9354dd7aeb4842b42204e8b4cb89ee2f0a4c5c8.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 74.125.200.82, 2607:f8b0:400d:c00::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|74.125.200.82|:443... connected.
Unable to establish SSL connection.
Error fetching CRAS
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by drinkcat** [comment]
Looks like transient network error, please try again and reopen if required.

**Comment by blinderjay** [comment]
hello,have you solved the problem,it seemed that i meet the same problem

**Comment by ateufel** [comment]
@blinderjay i had the same issue and just tried again. then it worked. may have been a temporary network issue, as i was in a train. try a different internet connection if it does not work.
