### ISSUE TITLE
Installing xiwi on precise on ARM fails

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2822]
```
Installing target xiwi...
xserver-xorg-video-dummy was already not hold.
Segmentation fault (core dumped)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xorg-video-abi-11
                            Depends: xserver-xorg-core (>= 2:1.10.99.901)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

Specifically, this was a jerry (RK3288)

**Comment by DennisLfromGA** [comment]
What does `sudo edit-chroot -all` show? ( just kiddin' ;-) )

**Comment by dnschneid** [comment]
Yeah, pretty bad bug reporting style \*slaps self on wrist\*.

Trusty gets through install.

**Comment by DennisLfromGA** [comment]
Do we still care about precise (and wily) ?

**Comment by dnschneid** [comment]
Okay, this is actually due to installing both xorg and xiwi in the same chroot on ARM with precise.  The xorg target is smarter than the xiwi target about bringing in the quantal-backported xorg versions and the various hacks needed to do so.

This is kind of a mess, and would result in a bunch of duplicated code to fix.
@DennisLfromGA is right, and precise is on its way out, so probably not worth fixing this.
