### ISSUE TITLE
Getting segmentation fault even after updating chroot

### ISSUE THREAD

**Issue by TheOdd** [dnschneid/crouton#2825]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
Segmentation fault (core dumped)
```

#### Please describe your issue:
I've had Ubuntu 14.04 (Trusty) with XFCE4 environment up and running for a while on my Chromebook. I was switching between the two environments and when I tried to switch back to XFCE from ChromeOS, it didn't do anything, so I ended up powering down my computer and after I booted up again, I got the segmentation fault error when trying to do sudo startxfce4. I've already tried updating the chroot and got the same error. Any help would be greatly appreciated.

#### If known, describe the steps to reproduce the issue:
Switching between environments, then once trying to go back doesn't work, restarting computer.

**Comment by drinkcat** [comment]
What command are you using to start the chroot?

**Comment by TheOdd** [comment]
@drinkcat I'm using sudo startxfce4

**Comment by drinkcat** [comment]
Did you try updating your chroot?

Can you provide all the command output?

**Comment by TheOdd** [comment]
chronos@localhost / $ sudo sh ~/Downloads/crouton -n trusty -u
/usr/local/chroots/trusty already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Segmentation fault (core dumped)
WARNING: starting chroot system dbus daemon failed with code 139
Segmentation fault (core dumped)
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by drinkcat** [comment]
Can you run:
`sudo sh -x ~/Downloads/crouton -n trusty -u | tee ~/Downloads/log.txt`

and attach log.txt here?

**Comment by TheOdd** [comment]
Each time I run that, it gives me a blank log.txt file.

**Comment by drinkcat** [comment]
sorry... `sudo sh -x ~/Downloads/crouton -n trusty -u 2>&1 | tee ~/Downloads/log.txt`

**Comment by TheOdd** [comment]
[log.txt](https://github.com/dnschneid/crouton/files/528166/log.txt)

**Comment by TheOdd** [comment]
I ended up grabbing all my personal files from the chroot directories and putting them on a backup drive and reinstalled. Thanks for your help, though @drinkcat !

**Comment by drinkcat** [comment]
Yeah, probably easiest that way ,-)
