### ISSUE TITLE
Can't find card error

### ISSUE THREAD

**Issue by memcallen** [dnschneid/crouton#2828]
sudo edit-chroot -all:
name: file
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/file...
/usr/local/bin/enter-chroot: 511: cannot create /run/crouton/mnt/stateful_partition/crouton/chroots/file/etc/crouton/name: Directory nonexistent

When I try to start precise or enter-chroot, it says that there's no card under /dev/dri.
I accidentally uninstalled a ton of stuff using apt-get autoremove a while back, but I don't think that had anything to do with this. I also tried to update using crouton, but it gave the same 'no card found' error.
My chromebook is the asus c201p.

**Comment by DennisLfromGA** [comment]
Update your chroot, this has recently been fixed: `sudo sh ~/Downloads/crouton -u`

**Comment by memcallen** [comment]
I tried but it gave me this error: 
`mv: cannot stat ‘/run/crouton/mnt/stateful_partition/crouton/chroots/precise/run/dri/card*’: No such file or directory`, which is the same as the original error.

**Comment by dnschneid** [comment]
Please make sure you don't have any /dev/dri hacks applied, then reboot and try again.

**Comment by memcallen** [comment]
Thanks, it worked. I should've tried 'turn it off and on again' earlier though...

**Comment by DennisLfromGA** [comment]
@memcallen,

Phew! Glad it was nothing more serious.
Thanx for getting back to us with your findings.

I'll close this now.

-**DennisL**
