### ISSUE TITLE
xfce chroot giving error on start with ASUS C100P

### ISSUE THREAD

**Issue by dte8506** [dnschneid/crouton#2830]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161013144521~master:9110be57
release: precise
architecture: armhf
xmethod: xorg
targets: touch,xfce
host: version 8530.96.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 4 15:38:26 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes

An error window pops up right when the startxfce4 command is put in saying:
"Unable to contact settings server" 
//bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon

and followed by a second error message that is:
"unable to load a failsafe session"
Unable to determine failsafe session name. Possible causes:xfconfd isn't running (D-Bus setup problem); environment variable $XDG_CONFIG_DIRS is set incorrectly (must include "/etc"), or xfce4-session is installed incorrectly.

How should I go about fixing this? 
```

**Comment by egg1st** [comment]
I have the same issue, but I've been able to fix this part. The dbus_contexts file is missing

I had to create the file path first
`sudo mkdir /etc/selinux/targeted/contexts`

then to create the file with the contents
`sudo cat "<busconfig><selinux></selinux></busconfig>" > dbus_contexts`

You can see another example of the file here:
https://selinuxproject.org/page/PolicyConfigurationFiles#contexts.2Fdbus_contexts_File

However I now get a different issue

> crouton: version 1-20161014161205~master:16fd55fd
> release: precise
> architecture: armhf
> xmethod: xorg
> targets: xfce
> host: version 8530.96.0 (Official Build) stable-channel veyron_minnie 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 4 15:38:26 PDT 2016 armv7l armv7l armv7l GNU/Linux
> freon: yes
> /etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
> 
> ** (xfce4-session:24202): CRITICAL **: Unable to contact D-Bus session bus: Unknown error
> 
> ** (xfce4-session:24202): CRITICAL **: Unable to contact D-Bus session bus: An SELinux policy prevents this sender from sending this message to this recipient, 0 matched rules; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_disconnect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_disconnect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:24202): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:24202): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:24202): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> Failed to connect to Xfconf daemon: An SELinux policy prevents this sender from sending this message to this recipient, 0 matched rules; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
> running 'ssh-agent -s -k'
> /etc/xdg/xfce4/xinitrc: 1: eval: ssh-agent: not found
> Running exit commands...
> /usr/bin/xinit: connection to X server lost
> 
> waiting for X server to shut down Hangup
> xscreensaver: 20:57:39: SIGHUP received: restarting...
> xscreensaver: 20:57:39: running as rebecca/rebecca (1000/1000)
> 
> xscreensaver: 20:57:39: Can't open display: :1
> xscreensaver: 20:57:39: running as rebecca/rebecca (1000/1000)
> 
> xscreensaver: 20:57:39: Errors at startup are usually authorization problems.
>               But you're not logging in as root (good!) so something
>               else must be wrong.  Did you read the manual and the FAQ?
> 
>               http://www.jwz.org/xscreensaver/faq.html
>               http://www.jwz.org/xscreensaver/man.html
> 
> Server terminated successfully (0). Closing log file.

**Comment by egg1st** [comment]
I found a solution. The release we had installed was "precise", but the latest stable release is "trusty". Worked first time.

You can see the current relases by running, and "trusty" is the most recent which is supported.
`sh ~/Downloads/crouton -r list`

So I just installed "trusty" instead. You can force the installation of a release by using:
`sudo sh ~/Downloads/crouton -r trusty -t xfce

If you want to encrypt it then it's
`sudo sh ~/Downloads/crouton -r trusty -e -t xfce

Make sure you remove the "precise" installation first
`sudo rm -R -f /usr/local/chroots/precise

Otherwise you'll need to specify the chroot instance everytime.
