### ISSUE TITLE
How to download a file

### ISSUE THREAD

**Issue by Crushmount** [dnschneid/crouton#2836]
Hi, I'd like to download the Import OpenStreetMap (.osm) add-on for Blender from this page:

 [https://github.com/vvoovv/blender-geo/wiki/Import-OpenStreetMap-(.osm)/640f402d748a2e6b0bc8fd957b62955a844fae99](url)

When I click on the file in the Installation section raw code appears and I don't know what to do with it.

Sorry for such a beginner question and thank you for help!

**Comment by divx118** [comment]
This is a #262. You are posting on the wrong issue tracker this is for crouton issues on a chromebook. Please close this one.  Thanks.
