### ISSUE TITLE
Syntax error: newline unexpected

### ISSUE THREAD

**Issue by rick-newsy** [dnschneid/crouton#2840]
I was unable to start an existing chroot (been a few months since I used the chromebook)  -- probably just needed to do an update. But it had worked perfectly fine before. So used edit-chroot -d and moved on with my life. However after re-downloading crouton again and trying to install anything gives me issues as you'll see below.

Tried both power washing and deleting the /tmp directory.

```
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce -e -n kali
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
Choose an encryption passphrase for kali: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
Installing kali-rolling-i386 chroot to /usr/local/chroots/kali
Downloading latest debootstrap...
2016-10-18 19:51:20 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [65573] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
/tmp/crouton.35s/functions: 560: Syntax error: newline unexpected
```

Also tried the following
```
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t xfce -e -n ubuntu
Choose an encryption passphrase for ubuntu: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
Installing precise-i386 chroot to /usr/local/chroots/ubuntu
Downloading latest debootstrap...
2016-10-18 19:58:09 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [65573] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
/tmp/crouton.gKi/functions: 560: Syntax error: newline unexpected
```

and just for simplicity sake
```
chronos@localhost / $ sudo sh ~/Downloads/crouton -t xfce
Installing precise-i386 chroot to /usr/local/chroots/precise
Downloading latest debootstrap...
2016-10-18 20:03:32 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [65573] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
/tmp/crouton.QMX/functions: 560: Syntax error: newline unexpected
```

Now this only RECENTLY started happening after I rebooted for a chromos update. All other attempts would create the environment but fail when building/extracting? something about dpkg and then would fail install -- trying to run the chroot would ask me if i'd like to finish it -- which it would error with something else. But obviously that's not the issue anymore.

**Comment by dnschneid** [comment]
https://anonscm.debian.org/cgit/d-i/debootstrap.git/commit/?id=8a77b648b1a989962314a7d389a529bdef66cf1d was just commited an hour ago.  Looks like that broke things.

**Comment by dnschneid** [comment]
Checking with Julien to fix debootstrap.  In the meantime, I've disabled pulling debootstrap from gitweb, so please try again.

**Comment by rick-newsy** [comment]
Nice. Thanks for a prompt fix in the meantime =)
