### ISSUE TITLE
install kali linux on chromebook but syntax error

### ISSUE THREAD

**Issue by pcmschool** [dnschneid/crouton#2841]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
I try to install kali linux on my acer chromebook using crouton, but there is an error.
Here is what I typed:
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r kali-rolling -n kali -t xiwi

Then the respond:
 Installing kali-rolling-amd64 chroot to /usr/local/chroots/kali
Downloading latest debootstrap...
2016-10-19 00:15:36 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [65573] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
/tmp/crouton.yGy/functions: 560: Syntax error: newline unexpected

How can I fix it?

Thx for everyone who respond to me!

**Comment by ericjcoleman** [comment]
I am having the same issue

**Comment by dnschneid** [comment]
#2840
