### ISSUE TITLE
Issue on installing crouton, unexpected newline in functions

### ISSUE THREAD

**Issue by ericjcoleman** [dnschneid/crouton#2842]
After trying to run:
sudo sh ~/Downloads/crouton -t xfce

I keep getting the following error although the three character series after "crouton." changes each time:

Installing precise-amd64 chroot to /usr/local/chroots/precise
Downloading latest debootstrap...
2016-10-18 17:47:15 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [65573] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
/tmp/crouton.akZ/functions: 560: Syntax error: newline unexpected

**Comment by dnschneid** [comment]
Fixed in #2840.  Try again.

**Comment by ericjcoleman** [comment]
Awesome, thanks for the quick fix! It works.
