### ISSUE TITLE
Running crouton instance causes android apps to force close

### ISSUE THREAD

**Issue by lifeofcoding** [dnschneid/crouton#2845]
```
crouton: version 1-20160823173305~master:1e0c0488
release: trusty
architecture: armhf
xmethod: xorg
targets: touch,kde
host: version 8743.69.0 (Official Build) beta-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Oct 19 01:30:06 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
```
#### Please describe your issue:

Since android support was added to my chromebook, when I start and run an instance, Google Play Services, and android apps running start force closing, unable to reopen, and apps not running force close when trying to start them. No all the time, some apps work fine, sometimes they don't, and sometimes it takes a few minutes before they eventually force close, but more often than not, it causes them all to eventually pop up with force close. Making it so I have to restart after closing the linux instance for android parts of the OS to work again.

Often times I just start the instance, and do not boot the desktop interface, so I can use the terminal, along side chrome os to do what I want, like running git, node, etc.. as I use an editor in chrome, so this happens even when desktop is started or not.
#### If known, describe the steps to reproduce the issue:

Start crouton, with `sudo enter-chroot` or `start kde`/`sudo startxfce4` etc.. after a few moments android services and apps will start displaying force close popups.

**Comment by DennisLfromGA** [comment]
@lifeofcoding,

> crouton: version 1-20160823173305~master:1e0c0488

There's been several changes & fixes applied to 'crouton' since you last updated your chroot and some of them have addressed your issue I believe.

Please update your chroot (`sudo sh ~/Downloads/crouton -n trusty -u`) and try again.

*Hope this helps,*
-**DennisL**

**Comment by drinkcat** [comment]
As Dennis said. Please reopen if this is still an issue.
