### ISSUE TITLE
Cant install xiwi after making chroot

### ISSUE THREAD

**Issue by 5nowx** [dnschneid/crouton#2846]
```
Name= Kali-rolling
encrypted: yes, locked

```

#### Please describe your issue:

Cant install xiwi after i created the chroot

#### If known, describe the steps to reproduce the issue:

executing "crouton -u -t xiwi "gives:

```
 /usr/local/chroots/precise does not exist: cannot update
valid chroots:
kali-rolling
```

**Comment by DennisLfromGA** [comment]
@5nowx,

It default to 'precise' so you just have to give it the name of your chroot, like:

`sudo sh ~/Downloads/crouton -n kali-rolling -t xiwi -u`

*Hope this helps,*
-**DennisL**

**Comment by 5nowx** [comment]
This is exactly the solution. Thanks @DennisLfromGA

**Comment by DennisLfromGA** [comment]
Great! And you're very welcome.
