### ISSUE TITLE
keyboard

### ISSUE THREAD

**Issue by rlruff** [dnschneid/crouton#2848]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by DennisLfromGA** [comment]
@rlruff,

What question do you have about 'keyboard'?

There is a `keyboard` target, that "Adds support for Chromebook keyboard special keys."
You add it like any other target withv the '-t' option.

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment]
The OP has left the building...
