### ISSUE TITLE
Getting error installing crouton on a ChromiumOS VirtualBox

### ISSUE THREAD

**Issue by aghasemi** [dnschneid/crouton#2850]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
cp: cannot stat ‘/run/crouton/mnt/stateful_partition/crouton/chroots/precise/dev/dri’: No such file or directory

```

I get the following error when trying to install crouton on the un-official VirtualBox image of the Neverware Cloudaready ChromiumOS:

```
cp: cannot stat ‘/run/crouton/mnt/stateful_partition/crouton/chroots/precise/dev/dri’: No such file or directory
```

I tried trusty and precise for release, and combinations of xiwi,xfce, and core for target. All the same.

**Comment by dnschneid** [comment]
Huh, neat.  Should be easy enough to fix--just need to add a directory check to https://github.com/dnschneid/crouton/blob/master/host-bin/enter-chroot#L554

**Comment by aghasemi** [comment]
How?

**Comment by DennisLfromGA** [comment]
@aghasemi,

Just a guess but maybe something like:

from: 
> `if [ ! -d "$varrundrm" -a -d "$sysclassdrm" ]; then`

to: 
> `if [ ! -d "$varrundrm" -a -d "$sysclassdrm" -a -d "$devdri" ]; then`

*Hope this helps,*
-**DennisL**

**Comment by aghasemi** [comment]
It worked. Thanks. I proposed the required change in enter-chroot.

**Comment by DennisLfromGA** [comment]
Cool, I'll close this now...
