### ISSUE TITLE
Blue-tinted display after installing crouton with unity shell on Acer Chromebook 13 with NVIDIA processor.

### ISSUE THREAD

**Issue by Hailong** [dnschneid/crouton#2853]
Blue-tinted display after installing crouton with unity shell on Acer Chromebook 13 with NVIDIA processor.

This is due to the arm processor I think, please advise the workaround to fix this.

**Comment by DennisLfromGA** [comment]
@Hailong,

So we know what you've installed and to help narrow down the problem, please show us the output of:

 `sudo edit-chroot -all` 

- Is the blue-tinted display only visible in the chroot or does it affect Chrome OS screens too?
- If it affects Chrome OS screens, do they appear normal after the chroot is terminated?

-**DennisL**

**Comment by Hailong** [comment]
Thanks Dennis, here is the output:

> chronos@localhost / $ sudo edit-chroot -all
> name: precise
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/precise...
> crouton: version 1-20161024163924~master:9a805611
> release: precise
> architecture: armhf
> xmethod: xorg
> targets: unity
> host: version 6310.61.0 (Official Build) stable-channel nyan_big 
> kernel: Linux localhost 3.10.18 #1 SMP Tue Dec 2 17:12:55 PST 2014 armv7l armv7l armv7l GNU/Linux
> freon: no
> Unmounting /mnt/stateful_partition/crouton/chroots/precise...

And the problem is in the Ubuntu screen only. It's looks like the "inverted color" bug by googling. But I have not found a solution so far.

**Comment by dnschneid** [comment]
You are running an *extremely* old version of ChromeOS.  In fact, it's so old, that crouton should have been refusing to install on it.  Please run `cat /etc/lsb-release` outside of the chroot, then follow the directions the crouton installer should have given you:

```
Your version of Chromium OS is extraordinarily old.
If there are updates pending, please reboot and try again.
Otherwise, you may not be getting automatic updates, in which case you should
post your update_engine.log from chrome://system to http://crbug.com/296768 and
restore your device using a recovery USB: https://goo.gl/AZ74hj
```

**Comment by Hailong** [comment]
Following is the output of `cat /etc/lsb-release`

```
chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_RELEASE_BOARD=nyan_big-signed-mpkeys
CHROMEOS_RELEASE_DESCRIPTION=6310.61.0 (Official Build) stable-channel nyan_big 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6310.61.0
GOOGLE_RELEASE=6310.61.0
```

**Comment by Hailong** [comment]
Output after restoring the device using a recovery USB:
```
chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_RELEASE_BOARD=nyan_big-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=93
CHROMEOS_RELEASE_BUILD_NUMBER=8530
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=53
CHROMEOS_RELEASE_DESCRIPTION=8530.93.0 (Official Build) stable-channel nyan_big 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=8530.93.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=8530.93.0
```

**Comment by DennisLfromGA** [comment]
That's much better, maybe do a crouton update now also.
And let us know if you still get the blue-tinted display?

**Comment by Hailong** [comment]
I just bought it from BestBuy last month, not sure why it has such an old OS version. Because I want to get one with NVIDIA Tegra chip, this is the only choice for me.

Great thanks to dnschneid, now the OS is up to date. I'm reinstalling crouton, and let's see if the color problem gone.

**Comment by Hailong** [comment]
It's still installing, while seems gets stuck at the following step:

```
Processing triggers for man-db ...
```

**Comment by Hailong** [comment]
Successfully installed `unity`, and the color is back to normal.

**Comment by DennisLfromGA** [comment]
@Hailong,

*That excellent news*, thanx for getting back to us with your results.

> I just bought it from BestBuy last month

You're not the first person that's happened to, sometimes a Chrome device will sit on a store shelf for months so it's not too uncommon for them to have very old versions.

-**DennisL**

**Comment by dnschneid** [comment]
Yeah, but they *should* get updates.  It'd be good to file a crbug on this if you still have the update_log from the original install.

**Comment by Hailong** [comment]
Appreciate your great help! Unfortunately, I don't have the original update_log, not able to file a crbug.
