### ISSUE TITLE
X starts, but Unity and window managers don't?

### ISSUE THREAD

**Issue by Snowflake6** [dnschneid/crouton#2858]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

chronos@localhost / $ sudo edit-chroot -all
name: elementary
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/elementary...
crouton: version 1-20150127081428~master:e1bcac2b
release: precise
architecture: amd64
targets: xfce,keyboard,extension
host: version 8872.15.0 (Official Build) dev-channel peppy 
Unmounting /mnt/stateful_partition/crouton/chroots/elementary...
name: utopic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/utopic...
crouton: version 1-20161026164931~master:34389250
release: utopic
architecture: amd64
xmethod: xorg
targets: cli-extra,audio,chrome,core,keyboard,touch,unity
host: version 8872.15.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Oct 17 21:49:19 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/utopic...
#### Please describe your issue:

When starting crouton, I get an X-window screen, with no content.  The X-shaped cursor will come up, and I can open a folder that was left on my desktop from a previous session, but I don't get a status bar, or a Unity bar down the left side of the screen.  All was working the last time I used it a couple of weeks ago, this time I ran an update before entering.  I didn't see anything odd in the update, and it completed with the usual "you may use startunity to start unity" messages.
#### If known, describe the steps to reproduce the issue:

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/utopic...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.16.0
Release Date: 2014-07-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-70-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Oct 17 21:49:19 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=026e4d31-5fc1-f44e-b168-5b06a0d47f3b/PARTNROFF=1 hashtree=PARTUUID=026e4d31-5fc1-f44e-b168-5b06a0d47f3b/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=097a09cb139e8bb5c629a413e308ce055e7e6f01 salt=5f210f4d8786db475bc817b1e91ab542d3472b5daced55d94e00199c2d15fc47" noinitrd vt.global_cursor_default=0 kern_guid=026e4d31-5fc1-f44e-b168-5b06a0d47f3b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:46:23PM
xorg-server 2:1.16.0-1ubuntu1.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.32.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Oct 27 22:03:44 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20161026164931~master:34389250
release: utopic
architecture: amd64
xmethod: xorg
targets: cli-extra,audio,chrome,core,keyboard,touch,unity
host: version 8872.15.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Oct 17 21:49:19 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
The XKEYBOARD keymap compiler (xkbcomp) reports:

> Warning:          Compat map for group 2 redefined
>                   Using new definition
> Warning:          Compat map for group 3 redefined
>                   Using new definition
> Warning:          Compat map for group 4 redefined
>                   Using new definition
> Errors from xkbcomp are not fatal to the X server
> (II) AIGLX: Suspending AIGLX clients for VT switch

**Comment by Snowflake6** [comment]
Okay, I fixed one error that I only noticed after posting this:

> **If known, describe the steps to reproduce the issue:**
> 
> chronos@localhost / $ sudo startunity
> Entering /mnt/stateful_partition/crouton/chroots/utopic...
> 
> _XSERVTransmkdir: **_Owner of /tmp/.X11-unix should be set to root_**

I did an "enter-chroot" then "sudo chown root.root /tmp/.X11-unix" to get ownership set back to root.root.

Still get the other error later in the log:

> xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
> Error executing command as another user: Not authorized
> 
> This incident has been reported.

Although I don't know if it's related or not.

Any help is appreciated...

**Comment by smibarber** [comment]
Utopic was end-of-life'd on July 23, 2015, so we removed it in #2827. Can you upgrade the chroot to xenial? There are some instructions to do so here: https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release

**Comment by Snowflake6** [comment]
Ah, that's interesting.  It's really too bad there isn't a better way of letting people know these things rather than just failing without warning.  I know it was end-of-life'd, but it's continued to work just fine for over a year now.

I have a Google Drive sync'ed to my chroot so i've been waiting for an upgrade path that doesn't require me to blow that away and spend two days waiting for it all to sync up again in a brand new chroot.  I'll check and see if that's been made possible yet.

**Comment by Snowflake6** [comment]
Well, I was able to update to Vivid, but still have the same issue.  Trying to run sudo do-release-upgrade a second time to get to Xenial doesn't work:

> (vivid)rb4@localhost:~$ sudo do-release-upgrade
> Checking for a new Ubuntu release
> Your Ubuntu release is not supported anymore.
> For upgrade information, please visit:
> http://www.ubuntu.com/releaseendoflife
> 
> Get:1 Upgrade tool signature [198 B]                                                                                                                
> Get:2 Upgrade tool [1,265 kB]                                                                                                                       
> Fetched 1,265 kB in 0s (0 B/s)                                                                                                                      
> authenticate 'xenial.tar.gz' against 'xenial.tar.gz.gpg' 
> extracting 'xenial.tar.gz'
> 
> Reading cache
> 
> Checking package manager
> 
> Can not upgrade 
> 
> An upgrade from 'vivid' to 'xenial' is not supported with this tool. 
> 
> (vivid)rb4@localhost

**Comment by DennisLfromGA** [comment]
@Snowflake6,

[Vivid](https://wiki.ubuntu.com/Releases#line-76), a non-LTS release, was end-of-life'd on February 4, 2016

*Hope this helps,*
-**DennisL**

**Comment by Snowflake6** [comment]
Yes, i'm aware Vivid was EOL'd too.  The intent was to go to xenial, but it wasn't offered and now doesn't want to do it.

Ubuntu's update manager would be an ideal way to do it, but unfortunately I can't run it.  If I do a "startunity", I get to an X desktop, and I can right-click and do desktop-type things but I can't run any software as I have no launcher.  I can't even get to a terminal.  Unless someone knows of a keyboard shortcut to open a terminal?

Mildly frustrating.  I guess I will have to make a xenial chroot separately and start over.

**Comment by DennisLfromGA** [comment]
@Snowflake6,

If you simply want to get to a terminal, use: `sudo enter-chroot -n utopic`
Unless of course you've renamed 'utopic' to something else.

*Hope this helps,*
-**DennisL**

**Comment by Snowflake6** [comment]
Hmm... I hadn't considered trying "sudo apt-get dist-upgrade" from the command prompt.  Won't that just do the same thing that "sudo do-release-upgrade" does?  I actually didn't know about do-release-upgrade until I saw it in the crouton upgrade notes... I figured it was just another way to trigger the same process... I'll try it when I get home.

**Comment by Snowflake6** [comment]
Update:  I tried dist-upgrade, but that didn't work, it didn't offer me anything.  A short google search later revealed the -d option for the do-release-upgrade program.  That started an update from Vivid to Wily, and after that was finished I tried it again without the -d and it upgraded from Wily to Xenial.

"sudo startunity" now brings up my full desktop like it used to, now running xenial.  Thanks for the hints that put me on the right upgrade path.  I'm still confused why it would suddenly stop working like that... I didn't think chroot affected how unity would operate.  I thought it might be because I switched to the Chrome OS Developer Channel, but I know I used unity after doing that, and before it stopped working.

I'll put the galliumOS USB stick away for another day.  I prefer having a Chrome install with Ubuntu on a "when I need it" basis.  Chrome is much more convenient for 90% of what I do on this laptop.

**Comment by DennisLfromGA** [comment]
@Snowflake6,

That's excellent news, your persistence has paid off.

I guess the uptake is that as soon as a chroot release hits its end-of-life or sooner, it would be best to upgrade. I tend to stick with LTS releases to try to avoid these problems, in chroots and on my desktop PC.

As you alluded, It might be helpful if 'crouton' displayed a warning message when you start a session with a release that has reached its end-of-life but some may not appreciate the nag or quickly grow tired of it. I actually appreciate that the crouton devs make an effort to keep up with the releases that come and go, maybe just a little more due diligence on us users is warranted. 

As far as Gallium OS, or any other distro, your Acer C720 can boot external media if the legacy boot option is set. You can also install Gallium OS as a dual-boot alternative via ['chrx'](https://github.com/reynhout/chrx) if you have the space. But, like you, I prefer using Chrome OS and having the ability to quickly switch into and out of a crouton chroot at will.

*Hope this helps,*
-**DennisL**

**Comment by Snowflake6** [comment]
crouton does actually remind you all the time that your release is end-of-life... I only use it occasionally so I make a habit of doing an update every time before I enter the chroot.  Each update starts with "your release is end of life, consider updating, etc., etc."

When utopic went end-of-life, there was no recommended way to update.  The best suggestion was to create a new chroot with the new release and delete the old one.  I didn't do that because I have my google drive sync'd to my chroot, and didn't want to lose that and have to wait for it to all download and synchronize again.  Some people were reporting breaking their chroots using the ubuntu built-in dist-upgrade method at the time, so I just elected to stick with utopic until such time as someone figured out how to update cleanly.

I'm aware of chrx, and was setting up to do that as a backup plan.  I still prefer ChromeOS most of the time though, and when I want full Ubuntu, I really do want full Ubuntu and not a stripped down version so Gallium might have worked but wouldn't really be what I wanted.

**Comment by DennisLfromGA** [comment]
@Snowflake6, 

I didn't recall that crouton warns you, I guess I don't use end-of-life releases often enough. : )

I've got a Dell Chromebook 13, I upgraded the SSD to 256GB and installed Linux Mint 18 'Sarah' as a dual-boot alternative, it's very nice. I've also setup crouton in a separate partition so I can run and store multiple chroots and other things.

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       1.7G  1.2G  570M  67% /
/dev/sda1        59G   19G   38G  33% /home
/dev/sda13      106G   36G   65G  36% /var/crouton
/dev/sda7        66G  9.7G   53G  16% /var/linux
```

*Hope this helps,*
-**DennisL**

**Comment by Snowflake6** [comment]
I've been thinking about upgrading my C720P for a while, but I haven't
found a new chromebook that I really like.  I don't want anything
physically larger than my C720P, and I want at least 4GB RAM.  Don't care
how big the drive is as long as it's replaceable.  Upgradeable to 8GB RAM
would be great, and i'd definitely go with a 256GB SSD now (my 128GB on the
C720P has been adequate, but 256 is now at the "cheap" price point).

**Comment by DennisLfromGA** [comment]
@Snowflake6,

I often refer to this [zipso site](https://zipso.net/chromebook-specs-comparison-table/), it is kept pretty current and has very helpful info. on [upgradability](https://zipso.net/chromebook-specs-comparison-table/#upgrade).

It looks like the C720P's RAM is not upgradable but the SSD is.

*Hope this helps,*
-**DennisL**

**Comment by Snowflake6** [comment]
The Dell gets good reviews, but is more than an inch wider than the C720, and just under an inch deeper.  To get an i3 processor with 8GB RAM is about $900 in Canada, plus ~$100 for the 256GB SSD.  Chromebooks just aren't as cheap as they used to be.  My C720 was $550, *including* the 128GB SSD.
