### ISSUE TITLE
Handle detection of really, really old releases

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2860]
As highlighted in #2853, the current logic for checking the release version fails when the release gets super-old.

Example lsb-release:

```
chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2FC0F0CF-1A55-DF3F-73E6-517389444085}
CHROMEOS_RELEASE_BOARD=nyan_big-signed-mpkeys
CHROMEOS_RELEASE_DESCRIPTION=6310.61.0 (Official Build) stable-channel nyan_big 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=6310.61.0
GOOGLE_RELEASE=6310.61.0
```

The code should probably fall back on parsing CHROMEOS_RELEASE_VERSION or CHROMEOS_RELEASE_DESCRIPTION if CHROMEOS_RELEASE_BUILD_NUMBER is missing.  Probably best to also have a sane warning message in case both styles can't be detected.

**Comment by DennisLfromGA** [comment]
Probably have to be careful with other variations like cloudready and arnoldthebat builds.
We ran into that here https://github.com/dnschneid/crouton/issues/2126#issuecomment-150843117 I think.
