### ISSUE TITLE
Problems testing crouton downstream

### ISSUE THREAD

**Issue by citrusui** [dnschneid/crouton#2861]
Hi! I'm working on adding a new target to crouton with my own fork. However, if I [download](https://raw.githubusercontent.com/citrusui/crouton/master/installer/crouton) my forked version and run it, it still fetches info from the main crouton repo, meaning it won't recognize the targets I'm testing.

Here's output of the script, run with `sudo bash -x ~/Downloads/crouton`:

https://gist.github.com/anonymous/4374a63b9b32bfcfbb9eb70783eb61bc

As noted by [line 2](https://gist.github.com/anonymous/4374a63b9b32bfcfbb9eb70783eb61bc#file-output-sh-L2), the version fetched is 1-20161028111244~master:`948ee6dc`. My fork is 1 commit above that, at ` 0b6eeac`.

Is this a bug? Or is there some flag I should specify when running crouton for the first time?

**Comment by smibarber** [comment]
If I'm testing a target locally, I usually invoke `installer/main.sh` directly in my crouton checkout. That takes the usual arguments and lets you test without interference from the `crouton` wrapper script.

**Comment by citrusui** [comment]
Thank you! (for those curious, download a zip of your forked repo, unzip it in your chroot into ~/Downloads, and run installer/main.sh).

I'll report the results of my new target if I can get it working.
