### ISSUE TITLE
Problems starting gnome-session

### ISSUE THREAD

**Issue by citrusui** [dnschneid/crouton#2862]
Follow-up to brief progress on #2861.

Having problems starting gnome-session with my custom Pantheon target. Anyone mind helping me out? Here's a log:

https://gist.github.com/anonymous/06958779bdd54f82c935987d5c6db29e

**Comment by dnschneid** [comment]
@smibarber has fought with gnome-session the most.  You might want to look at recently-merged PRs to see what he had to do to get gnome-session to work.
