### ISSUE TITLE
page up down home end keyboard keys

### ISSUE THREAD

**Issue by githubgnulinux** [dnschneid/crouton#2864]
#### Please describe your issue:

How to add new shortcuts for page up, page down, home, end, keyboard keys?

**Comment by DennisLfromGA** [comment]
You might want to add the `keyboard` target to your chroot.
This is part of the comments from the `keyboard` target:

> \# This adds support for Chromebook keyboard special keys.
\#
\# For example, we map Search+arrows to Page Up/Down/Home/End. This is
\# done at the browser level in Chromium OS (i.e., not at the hardware
\# or keymap level).

Also, I've never felt the need to customize my keys but the wiki might help: [Keyboard](https://github.com/dnschneid/crouton/wiki/Keyboard)
