### ISSUE TITLE
Mint PL0X?

### ISSUE THREAD

**Issue by LinuxGNUB** [dnschneid/crouton#2865]
Sudo sh -e ~/Downloads/crouton -r maya -t cinnamon -n mint

Possible?

**Comment by DennisLfromGA** [comment]
No, not currently possible.

Here are the 'releases' currently available on 'crouton' -

> _Recognized debian releases:_
    potato* woody* sarge* etch* lenny* squeeze* wheezy jessie stretch sid
Recognized kali releases:
    kali* sana* kali-rolling
Recognized ubuntu releases:
    warty* hoary* breezy* dapper* edgy* feisty* gutsy* hardy* intrepid* jaunty*
    karmic* lucid* maverick* natty* oneiric* precise quantal* raring* saucy*
    trusty utopic* vivid* wily* xenial* yakkety*
__Releases marked with * are unsupported, but may work with some effort.__

Also, here is the current list of targets/desktops available with their typical footprint -

> e17 - Installs the enlightenment desktop environment. (Approx. 50MB)
gnome - Installs the GNOME desktop environment. (Approx. 400MB)
gnome-desktop - Installs GNOME along with common applications. (Approx. 1100MB)
kde - Installs a minimal KDE desktop environment. (Approx. 600MB)
kde-desktop - Installs KDE along with common applications. (Approx. 1000MB)
lxde - Installs the LXDE desktop environment. (Approx. 200MB)
lxde-desktop - Installs LXDE along with common applications. (Approx. 800MB)
unity - Installs the Unity desktop environment. (Approx. 700MB)
unity-desktop - Installs Unity along with common applications. (Approx. 1100MB)
xfce - Installs the Xfce desktop environment. (Approx. 250MB)
xfce-desktop - Installs Xfce along with common applications. (Approx. 1200MB)

*Hope this helps,*
-**DennisL**

**Comment by dnschneid** [comment]
I think he meant this as a feature request :)

**Comment by DennisLfromGA** [comment]
*Shrewd way to do it I guess. : )*

Linux Mint 'Maya' is version 13, 'Sarah' is version 18, the latest I think.
But that's academic since crouton doesn't do any Mint editions, I don't know how feasible that is.

I guess cinnamon could come back at sometime, not sure if it's widely available though.

There is a [MATE](https://github.com/dnschneid/crouton/pull/2532) PR that hasn't made it through the gauntlet yet.
