### ISSUE TITLE
How to make the odata version 7.0 case insensitive 

### ISSUE THREAD

**Issue by spuc** [dnschneid/crouton#2866]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
After upgrading to odata version 7, the config.EnableCaseInsensitive   does not work any more
I tried several work arounds, such as ..
-1.	Added a class with CaseInsensitiveResolver specification to the ODataUriResolver singleton
 -add a ODataUriHelper class to rewrite the filter
nothing worked

are there any working solutions to making odata version 7 work with case insensitivity?

thanks!

#### If known, describe the steps to reproduce the issue:
upgrade odata to latest version (version 7)
keep case insensitivity configuration or make a case insensitive query

**Comment by dnschneid** [comment]
how insensitive. #262
