### ISSUE TITLE
Unable to start unity after fresh install

### ISSUE THREAD

**Issue by steinbarge1** [dnschneid/crouton#2869]
name: trusty
Enter encryption passphrase for trusty: 
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161028111244~master:948ee6dc
release: trusty
architecture: armhf
xmethod: xorg
targets: unity-desktop,gtk-extra,cli-extra,extension,keyboard,xbmc,chrome
host: version 8743.76.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 25 23:32:44 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

After installing unity from the guide located at chromebook.guide/crouton and running the command sudo startunity I get the following errors:
Loading extension GLX
crouton: version 1-20161028111244~master:948ee6dc
release: trusty
architecture: armhf
xmethod: xorg
targets: unity-desktop,gtk-extra,cli-extra,extension,keyboard,xbmc,chrome
host: version 8743.76.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 25 23:32:44 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(EE) 
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

Does anybody know a way to fix this?

**Comment by DennisLfromGA** [comment]
@steinbarge1,

It looks like both your 'crouton' version and your CrOS version are up to date, thanx for that info.

Just checking to be sure, does this happen each and every time?
Can you get into your chroot and start it there using:
> `sudo enter-chroot`
`startunity`

You could try adding the 'xiwi' target/xmethod using:
> `sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`

And see if that will be satisfactory for you, it won't have hardware acceleration but it might be good enough.

*Hope this helps,*
-**DennisL**

**Comment by dnschneid** [comment]
unity doesn't really work on ARM on anything other than precise, due to missing DRI stuff yadda yadda yadda.  We'll probably be disabling it people don't install it expecting it to work.  Sorry for the bad news :/

**Comment by DennisLfromGA** [comment]
Guess I missed that little tidbit, sorry... : (
