### ISSUE TITLE
symlink loop when stored on usb

### ISSUE THREAD

**Issue by fishfishfish2104** [dnschneid/crouton#2871]
when chroots are stored on a usb the chroot will mount the usb in its self so it will become a symlink loop
`sudo find /media/removable/usb/ > /dev/null`
Password: 
find: File system loop detected; /media/removable/usb/chroots/server/var/host/media/removable/usb is part of the same file system loop as `/media/removable/usb/'.
 this isn't a severe issue but i thought i would post it anyway thanks :)

**Comment by dnschneid** [comment]
Probably the same root cause as #2876
