### ISSUE TITLE
'/dev/tty0 is not a directory' "cannot connect to x server" after using chroot once 

### ISSUE THREAD

**Issue by Astrades** [dnschneid/crouton#2872]
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20161028111244~master:948ee6dc
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: gnome-desktop
host: version 8530.96.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 4 15:40:35 PDT 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

Earlier today, I installed kali rolling edition with crouton on gnome and used it for a little while. I didn't install anything that had to do with either the xorg session or crouton and edited no crouton/system files. Now, I am unable to start kali rolling and am given the errors of "dev/tty0 is not a file or directory" and "fatal server error: cannot connect to x server"
What's wrong here and how do I fix it?

I saw that this was a bug to be fixed a while back and from the looks of it, still has not. Thanks for looking into this,
Astrades.

**Comment by drinkcat** [comment]
Can you provide console output when xorg startup fails? Also, does a reboot fix the issue?

**Comment by dnschneid** [comment]
This is probably #2875
