### ISSUE TITLE
UID 1000 not found in stretch

### ISSUE THREAD

**Issue by aghasemi** [dnschneid/crouton#2873]
Happened while installing Debian stretch. Did `enter-chroot` to complete it but faced the same thing:

```
Entering /mnt/stateful_partition/crouton/chroots/stretch...
UID 1000 not found in stretch
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
```

What does that mean?

**Comment by DennisLfromGA** [comment]
@aghasemi,

Get into your chroot as root and let if finish using: `sudo enter-chroot -u 0 -n stretch`
This might give you more info. to go on and then allow you to fix it.

Or try a crouton update using: sudo sh ~/Downloads/crouton -n stretch -u`

*Hope this helps,*
-**DennisL**
