### ISSUE TITLE
Too many instances of my chroot

### ISSUE THREAD

**Issue by TenTypesOfPeople** [dnschneid/crouton#2877]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: debbie
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/debbie...
crouton: version 1-20161026164931~master:34389250
release: jessie
architecture: armhf
xmethod: xiwi
targets: xiwi,lxde
host: version 8530.96.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 4 15:34:50 PDT 2016 armv7l GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/debbie as another instance is using it.

```

#### Please describe your issue:

In the crouton integration extension, it appears I have 12 instances (?) of my debian chroot running, if I deduce correctly (under crouton integration, and under cros Chrome OS, I see :12 debbie). If so, is there any way to bring it down to 1, and would that take up less battery power?

**Comment by DennisLfromGA** [comment]
@TenTypesOfPeople,

> In the crouton integration extension, it appears I have 12 instances (?) of my debian chroot running...

It may appear that way but the number shown on the 'crouton integration' extension represents the DISPLAY number, not the number of procsses.

Here's a snapshot of my system running 4 different chroots -

![screenshot 2016-11-11 at 10 51 37 am](https://cloud.githubusercontent.com/assets/3418772/20220918/5792141a-a7fd-11e6-8674-ff1b167f126f.png)

And here's another showing the various windows -

![screenshot 2016-11-11 at 10 51 47 am](https://cloud.githubusercontent.com/assets/3418772/20220946/728cbcde-a7fd-11e6-9e6a-7307b4524f80.png)

**DISPLAY=:12** does sound unusual, they normally are assigned sequentially I think  but it's nothing to be concerned about.

*Hope this helps,*
-**DennisL**
