### ISSUE TITLE
edit-chroot, Command Not Found

### ISSUE THREAD

**Issue by neauoire** [dnschneid/crouton#2879]
```
sudo: edit-chroot: command not found
```

#### Please describe your issue:

Chroot backup seems to be broken?

#### If known, describe the steps to reproduce the issue:

(precise)neauoire@localhost:/media/removable/SD Card/backups$ sudo edit-chroot -b testing
[sudo] password for neauoire: 
sudo: edit-chroot: command not found

**Comment by DennisLfromGA** [comment]
@neauoire,

Try using crouton's own '-b' restore option -
>
 -b          Restore crouton scripts in PREFIX/bin, as required by the chroots currently installed in PREFIX/chroots.

And be sure to specify the path/prefix to your chroot(s) if they are not in the default location (`/usr/local`) with the '-p' option -
>
-p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: `/usr/local`, with `/usr/local/chroots` linked to
                `/mnt/stateful_partition/crouton/chroots`.

*Hope this helps,*
-**DennisL**

**Comment by neauoire** [comment]
thank you :)
