### ISSUE TITLE
how do i know when installation is done?

### ISSUE THREAD

**Issue by xxcriticxx** [dnschneid/crouton#2881]
```
`chronos@localhost / $ sudo edit-chroot -all`
`name: xenial`
`encrypted: no`
`Entering /mnt/stateful_partition/crouton/chroots/xenial...`
`crouton: version 1-20161028111244~master:948ee6dc`
`release: xenial`
`architecture: amd64`
`xmethod: xorg`
`targets: xfce`
`host: version 8743.83.0 (Official Build) stable-channel edgar` 
`kernel: Linux localhost 3.18.0-13100-g25aa309 #1 SMP PREEMPT Wed Nov 2 23:40:00 PDT 2016` `x86_64 x86_64 x86_64 GNU/Linux`
`freon: yes`
`Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.`
```

#### Please describe your issue:

installing on Acer Chromebook 14 CB3-431

i been stock on Processing triggers for libc-bin (2.23-0ubuntu4) for about 20 min now. how can i check if something crashed? how do i access debug log?

**Comment by xxcriticxx** [comment]
trusty gets stocks in same place

Processing triggers for libc-bin (2.19-0ubuntu6.9)

chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161028111244~master:948ee6dc
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8743.83.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13100-g25aa309 #1 SMP PREEMPT Wed Nov 2 23:40:00 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161028111244~master:948ee6dc
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8743.83.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13100-g25aa309 #1 SMP PREEMPT Wed Nov 2 23:40:00 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

**Comment by drinkcat** [comment]
Can you provide the full install command, and a bit more of the output? (a least a few lines before the installation gets stuck).

You could also check `top` when the installation is stuck/

**Comment by xxcriticxx** [comment]
how can i provide the output because i closed the terminal tab. is there repair mode or debug mode?

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

> how can i provide the output because i closed the terminal tab. is there repair mode or debug mode?

Run the command again, grab the command and the output and paste it all in a [pastebin.com file](http://pastebin.com/) or somewhere else of your choosing, then share the link with us.

**Comment by xxcriticxx** [comment]
ok give me 5 min

what is the correct command to install ubuntu 16.04?

**Comment by xxcriticxx** [comment]
do i have to delete anything from old installations?

**Comment by xxcriticxx** [comment]
setup log: `http://pastebin.com/HnPwTHy4`
top log: `http://pastebin.com/XNZTYbWW`
chroot -all: `http://pastebin.com/CQyPPgVL`

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

> what is the correct command to install ubuntu 16.04?

With just the 'xfce' target like you show above, use this:

`sudo sh ~/Downloads/crouton -r xenial -t xfce`

> do i have to delete anything from old installations?

No, you shouldn't have to as long as we can get this one working.

-**DennisL**

**Comment by xxcriticxx** [comment]
i got precise to install and work 

how to i remove rest?

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

Okay, your ['setup log'](http://pastebin.com/HnPwTHy4) shows that you installed a 'precise' release, not 'xenial' and the log is incomplete for whatever reason.

The ['chroot -all log'](http://pastebin.com/CQyPPgVL) shows that you now have three chroots on three different releases - precise, trusty, & xenial.

If you want to remove 'trusty', use this: `sudo delete-chroot trusty`

Since you first asked about when the installation finished on the 'xenial' release, let's concentrate on that and forget the others for now.

So to update your 'xenial' release and get back to the point where the installation gets stuck, run this command and then show us the **full** output: 

`sudo sh ~/Downloads/crouton -n xenial -u`

*Hope this helps,*
-**DennisL**

**Comment by xxcriticxx** [comment]
ok it finished correctly now ask me for username and password

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

If it got that far then you're good to go, just enter a username & password and let it finish.

The initial issue may have just been a transient network glitch.

*Hope this helps,*
-**DennisL**

**Comment by xxcriticxx** [comment]
getting few error from time to time but most of the stuff works i will test and report back

`http://pastebin.com/LvZKMhXp`

**Comment by xxcriticxx** [comment]
and touch pad is kind off and slow

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
