### ISSUE TITLE
xenial: update fails when installing crouton-network-manager

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#2883]
#### Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost ~ $ sudo edit-chroot -c /var/crouton/chroots -l xenial-lxqt 
name: xenial-lxqt
encrypted: no
Entering /var/crouton/chroots/xenial-lxqt...
crouton: version 1-20161028111244~master:948ee6dc
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,gtk-extra,keyboard,chrome-beta
host: version 8872.44.0 (Official Build) beta-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 7 21:58:35 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /var/crouton/chroots/xenial-lxqt...
```

#### Please describe your issue:
When updating my xenial chroot, the setup failed to complete with the following message:
```
.....
Installing target gtk-extra...
ar: creating /tmp/crouton.JoVE7k/crouton-network-manager.deb
dpkg: regarding .../crouton-network-manager.deb containing crouton-network-manager:
 connman conflicts with network-manager
  crouton-network-manager provides network-manager and is to be installed.

dpkg: error processing archive /tmp/crouton.JoVE7k/crouton-network-manager.deb (--install):
 conflicting packages - not installing crouton-network-manager
Errors were encountered while processing:
 /tmp/crouton.JoVE7k/crouton-network-manager.deb
Failed to complete chroot setup.
Unmounting /var/crouton/chroots/xenial-lxqt...
Sending SIGTERM to processes under /var/crouton/chroots/xenial-lxqt...
chronos@localhost ~ $ 
```
#### If known, describe the steps to reproduce the issue:
`sudo sh ~/Downloads/crouton -p /var/crouton -n xenial -u`

-----
I re-entered the chroot and let it try to finish but it failed again.
I then tried -

`sudo apt-get -f install`
`sudo apt-get update`
`sudo apt-get upgrade`

but didn't get any further.

I'm not sure where 'connman' is coming from, I suppose I could try to install 'connman' but I don't think that would help.

**Comment by DennisLfromGA** [comment]
I should have mentioned the `lxqt` target installs: lxqt lxqt-common openbox
So I guess that 'connman' is coming from one of the above.

**Comment by DennisLfromGA** [comment]
I discovered that 'connman' is installed with lxqt and Conflicts: network-manager, wicd
And the `gtk-extra` target installs network-manager.

I modded the prepare script to remove network-manager and it finished the setup.

I guess `gtk-extra` and the `lxqt` target have conflicts, the PR for lxqt may want to consider this.

*Sorry for the false alarm,*
-**DennisL**

**Comment by dnschneid** [comment]
Definitely feed that back into the PR itself, please.
