### ISSUE TITLE
The NaCI and the Data Execution Prevention Erorrs like to appear (On CloudReady, and on a BIOS computer)

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#2884]
(Note: I am using the **crouton integration extension** in **Chromium** OS.)
(Version: 53.0.2785.148)
(Platform: 53.2.49)
(Developer Build -neverware developer-build chromeover64)
(Note: This is actually CloudReady, Neverware's polished version of Chromium OS.)

Here is my (Weird) issue:
Whenever I run `sudo startunity` and `sudo startxfce4`, I get this weird message from a xiwi Window:

'ERROR: NaCl module load failed: Data Execution Prevention is required but is not supported 
ERROR: NaCl module load failed: PnaclCoordinator: Compile stream init failed: reply not received from PNaCl translator (it probably crashed)'

I installed different desktop environments, but they gave me the same error. Ouch!

What can I do? (I will try do find solutions myself)

**Comment by drinkcat** [comment]
I'd suggest reporting this issue to the CloudReady folks.

**Comment by dnschneid** [comment]
Almost sounds like you've configured your VM without the no execute bit enabled.

**Comment by MelonFlare** [comment]
Can I enable that no execute bit?

**Comment by Seanld** [comment]
This is the error I have as well.

**Comment by uygwfd254** [comment]
I had this issue with xiwi too. Try to use xorg by **sudo enter-chroot -n trusty -X xorg startxfce4**. This work for me.
