### ISSUE TITLE
Difficulty with Anyconnect/Openconnect VPN for Matlab

### ISSUE THREAD

**Issue by Paulkaryote** [dnschneid/crouton#2886]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161028111244~master:948ee6dc
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde,chrome,cli-extra,audio,cli-extra,keyboard,extension,xorg
host: version 8986.0.0 (Official Build) canary-channel reks 
kernel: Linux localhost 3.18.0-13449-gfaaa058 #1 SMP PREEMPT Sun Nov 13 03:00:53 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:

Hey I am trying to run Matlab (licensed with my university) on my Trusty LXDE crouton (Lenovo N22/Intel) but it only works if am connected to my university's internet (urutu.concordia.ca) with my username and pasword. On my windows desktop it works well with Cisco Anyconnect.

#### If known, describe the steps to reproduce the issue:

1. Tried the Cisco Anyconnect Chrome App on ChromeOS, but it wouldn't let me input urutu.concordia anywhere. There is an option to import certificate or profile, but no idea how to use those.
2. Tried the Cisco Anyconnect Linux program on Crouton but doesn't fully connect, says reconnecting constantly on the status.
3. With some basic googling, I found: https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect which suggested I install Openconnect and some other programs via Apt-Get. So I tried that then tried the command: Sudo Openconnect urutu.concordia.ca, input my username and password and got the following error:

> Got CONNECT response: HTTP/1.1 200 OK
> CSTP connected. DPD 30, Keepalive 20
> resolvconf: Error: /run/resolvconf/interface either does not exist or is not a directory
> Connected tun0 as 172.16.248.158, using SSL
> Established DTLS connection (using OpenSSL)
> Failed to write incoming packet: File descriptor in bad state

So I have no idea what to do next, any guidance would be appreciated!

**Comment by mschendel** [comment]
Hi! I am having an extremely similar problem.  Any help would be appreciated!!

chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160715134041~master:0dc76a22
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 8743.83.0 (Official Build) stable-channel kip 
kernel: Linux localhost 3.10.18 #1 SMP Wed Nov 2 23:37:35 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

1. I was able to use the anyconnect app up until a few days ago.  The error I get is that my environment doesn't meet admin's requirements.  Talked to admin - he said he didn't know how to set up his end for Chrome OS.  Suggested try linux?
2. Got the Cisco anyconnect program running on linux, but once connected, hangs with status reconnecting.
3. Found same use anyconnect with openconnect, and tried same.  I use a slightly different anyconnect command... I had to follow [http://askubuntu.com/questions/815145/ubuntu-16-04-openconnect-cisco-vpn-failed-to-obtain-webvpn-cookie](url) to get the csd wrapper problem solved first.  

Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connect Banner:
<banner text>
resolvconf: Error: /run/resolvconf/interface either does not exist or is not a directory
Connected tun1 as XX.X.XX.XX, using SSL
Established DTLS connection (using OpenSSL)
Failed to write incoming packet: File descriptor in bad state

If I ctrl c to quit, I get an additional line about the run/resolvconf/interface error.

**Comment by DennisLfromGA** [comment]
@Paulkaryote & @mschendel,

I haven't tried to use 'Anyconnect/Openconnect VPN' so I can't speak from experience but sometimes communication is cut-off due to CrOS's firewall, all incoming ports are closed by default. You could try opening them up to see if that helps by following the instructions in this wiki: [Running servers in crouton](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton) and doing items 1, 2, and 3i.

@mschendel,

It looks like both your HP Chromebook 11 (kip) and your crouton version are behind a little.
I would first navigate to URL __chrome:chrome__ then tap the *'Check for and apply updates'* button to prompt a CrOS update. 
Once that's done, then do a crouton update using: `sudo sh ~/Downloads/crouton -n trusty -u`

*Hope this helps,*
-**DennisL**

**Comment by mschendel** [comment]
Thanks for your advice, Dennis!
Question... to follow the instructions in the wiki, for #2, what kind of service would this be?  Cisco has a vpnagentd service that is necessary, but should start when you start the anyconnect..  Would one of the options listed be useful in this case? Or is step 2 unnecessary, because we really want step 3 - to open the firewall?  
Megan

**Comment by mschendel** [comment]
A little additional info.  Was able to update chrome OS, and crouton fine.  I tried following step 1 and step 3 of the suggested wiki. Now it looks like everything is connected, but I can't do anything.

POST https://vpn.mrn.org/
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connect Banner:

RTNETLINK answers: File exists
resolvconf: Error: /run/resolvconf/interface either does not exist or is not a directory
Connected tun1 as XX.X.XX.XX, using SSL
Established DTLS connection (using OpenSSL)

I leave the terminal sitting there, but I can't access any network resources on the VPN and when I try to use a browser, it hangs, showing "resolving host."

**Comment by DennisLfromGA** [comment]
@Paulkaryote & @mschendel ,

> resolvconf: Error: /run/resolvconf/interface either does not exist or is not a directory

You seem to be getting stuck at the same point per the above.

I found a couple of crouton issues and a couple of others on the web, 
hopefully, one of the following will help -
- [vpnc resolvconf issues #372](https://github.com/dnschneid/crouton/issues/372)
- [vpnc and resolvconf issue #1320](https://github.com/dnschneid/crouton/issues/1320)
- [Resolvconf problem on ubuntu server 14.04](https://ubuntuforums.org/showthread.php?t=2300270)
- [How can I repair “/run/resolvconf/interface” missing error?](http://askubuntu.com/questions/740304/how-can-i-repair-run-resolvconf-interface-missing-error)

*Hope this helps,*
-**DennisL**

**Comment by mschendel** [comment]
Thanks for the links!  

I don't know enough myself to generate the nameservers required to create a resolv.conf  file for myself, so I found instructions to repair it http://askubuntu.com/questions/134121/how-to-restore-recreate-etc-resolv-conf-files 

However, that didn't change anything.  

Here is the command I'm using (snagged csd wrapper script from above mentioned)
sudo /usr/sbin/openconnect -s--user=myvpnuser --authgroup=grpname --interface=tun1 --csd-user=mylinuxuser --csd-wrapper=/home/mschendel/.cisco/csd-wrapper.sh --passwd-on-stdin --no-cert-check vpn_address

I still get stuck with 
resolvconf: Error: /run/resolvconf/interface either does not exist or is not a directory
Connected tun1 as 10.0.97.24, using SSL
Established DTLS connection (using OpenSSL)

I will dig around more to find how to create the nameservers.

Thanks again,
Megan

**Comment by DennisLfromGA** [comment]
@mschendel,

Thanx for getting back to us, I was hoping something might work out but guess not yet anyway.
I wish I knew more about it, sorry.

-**DennisL**

**Comment by mschendel** [comment]
AH HA!  I finally got it!

I did a number of things; not entirely sure what was the magic that made it work.

- The last thing I tried was installing openconnect and vpnc on my chroot, previously it was in the crouton.  I didn't have to follow all of faxe78's instructions, just installed openconnect and vpnc on my chroot (https://github.com/dnschneid/crouton/issues/235, https://github.com/dnschneid/crouton/issues/1533).

- I did the following, and the resolvconf error went away.
Tried re-installing resolvconf. I can't remember if I had to purger and reinstall, or just reinstall, and I'm not sure if that helped or not  (http://askubuntu.com/questions/134121/how-to-restore-recreate-etc-resolv-conf-files)
Added the following in /etc/rc.local 
`mkdir -p /run/resolvconf/interface
cp /etc/resolv.conf /run/resolvconf/resolv.conf
mv /etc/resolv.conf /run/resolvconf/interface/mlan0
ln -s /run/resolvconf/resolv.conf /etc/resolv.conf
resolvconf --enable-updates`
eg https://github.com/dnschneid/crouton/wiki/VPNC 

- Opened up the firewall (just followed 1 & 3 here: https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton)

- Every time I run the VPN, in the chroot I stop shill and start with tun in the BLACKLISTED_DEVICES 
eg https://github.com/dnschneid/crouton/issues/2215

- In the chroot, I bring up the tun (https://github.com/dnschneid/crouton/wiki/Using-Cisco-AnyConnect-VPN-with-openconnect)

- Finally, start up crouton, and run the openconnect command.  WHEW.

Goodluck @Paulkaryote!  Thanks @DennisLfromGA!

Megan
