### ISSUE TITLE
touchpad on Acer Chromebook 14

### ISSUE THREAD

**Issue by xxcriticxx** [dnschneid/crouton#2887]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

how do i get mouse to work correctly in ubuntu 16.04?

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

> Please paste the output of the following command here: sudo edit-chroot -all

We ask that you provide those details for a reason, it helps us better help you.

-----
Are you talking about an external mouse or the touchpad?

I use a [~$15 Logitech wireless mouse](https://smile.amazon.com/gp/product/B007T1CTDE) and it works perfectly, just plug it in. 
See this article for more: ['Best wireless mice for Chromebooks'](http://www.androidcentral.com/best-wireless-mice-chromebooks).

If it's the touchpad sensitivity you're talking about, you might want to look at a couple issues that discuss the touchpad and some workarounds. For instance, some devices have had luck with changing the settings with one of the following two -
- `synclient FingerLow=1 FingerHigh=5`
- `synclient FingerLow=5 FingerHigh=10`

You could try those and see if it solves your issue.

*Hope this helps,*
-**DennisL**

**Comment by xxcriticxx** [comment]
@DennisLfromGA sorry boss

`chronos@localhost / $ sudo edit-chroot -all`
`name: xenial`
`encrypted: no`
`Entering /mnt/stateful_partition/crouton/chroots/xenial...`
`crouton: version 1-20161028111244~master:948ee6dc`
`release: xenial`
`architecture: amd64`
`xmethod: xorg`
`targets: keyboard,xfce`
`host: version 8743.83.0 (Official Build) stable-channel edgar` 
`kernel: Linux localhost 3.18.0-13100-g25aa309 #1 SMP PREEMPT Wed Nov 2 23:40:00 PDT 2016` `x86_64 x86_64 x86_64 GNU/Linux`
`freon: yes`
`Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.`

i think `synclient FingerLow=5 FingerHigh=10` works better touchpad (mouse) moves quicker and its more responsive

**Comment by xxcriticxx** [comment]
should I add this to `/etc/rc.local` to run it on startup?

**Comment by xxcriticxx** [comment]
@DennisLfromGA i tried logitech mouse also but wheel speed is kind of crazy

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

> should I add this to /etc/rc.local to run it on startup?

I haven't tried adding it to `/etc/rc.local` but that might work.
Another place than others have used is in your `~/.bashrc` file.

*Hope this helps,*
-**DennisL**

**Comment by xxcriticxx** [comment]
@DennisLfromGA how do you adjust scroll speed of the wheel on Logitech mouse?
