### ISSUE TITLE
Is it possible to edit config files in a chroot when not able to boot? 

### ISSUE THREAD

**Issue by glynhudson** [dnschneid/crouton#2890]
```
Please paste the output of the following command here: sudo edit-chroot -all

sudo edit-chroot -all
Password: 
name: fig
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/fig...
```

#### Please describe your issue:

After updating to 54.0.2840.93 (64-bit) on Pixel 2 LS crouton won't boot. 

```
Entering /mnt/stateful_partition/crouton/chroots/fig...
Still running chroot's rc.local...
```

I think it is due to an entry I have in rc.local. 

**Is there anyway to edit rc.local without being able to boot the chroot?**

**Comment by DennisLfromGA** [comment]
@glynhudson,

You may be able to get into your chroot to fix `/etc/rc.local` or whatever else is ailing, try:

`sudo enter-chroot -n fig`

If you want to get into your chroot as root, use:

`sudo enter-chroot -u 0 -n fig`

*Hope this helps,*
-**DennisL**

**Comment by divx118** [comment]
@glynhudson You can also edit the /etc/rc.local of your chroot fig in a crosh shell with `sudo vi /mnt/stateful_partition/crouton/chroots/fig/etc/rc.local`

**Comment by glynhudson** [comment]
@DennisLfromGA thanks for your suggestion, I'm afraid neither options works:

```
sudo enter-chroot -u 0 -n fig
Enter encryption passphrase for fig: 
Entering /mnt/stateful_partition/crouton/chroots/fig...
Still running chroot
```

***

@divx118 thanks for your suggestion, unfortunately since my chroot is encrypted I cannot edit the files. In `/mnt/stateful_partition/crouton/chroots/fig/` all I see is encrypted files. Is there any way to decrypt and edit the files externally?

***

Or can a chroot be booted in a safe mode which does not execute rc.local?  My chroot was working great before updating ChromeOS. Is there anyway to roll back an OS update? 

Thanks again for your help.

**Comment by dnschneid** [comment]
`sudo enter-chroot -x -n fig` is probably what you want. It will pop you into a recovery shell, similar to `init=/bin/sh` on native installs. 

You can also use `mount-chroot fig` to mount the chroot without launching anything, then navigate (in a root crosh shell) to the shadow mount in /run/crouton/mnt/...

**Comment by glynhudson** [comment]
Awesome! Thanks a lot @dnschneid 👍 

`sudo enter-chroot -x -n fig`

did the trick. I was able to fix the issue in rc.local
