### ISSUE TITLE
Be smarter about touchpad configuration

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#2891]
As highlighted in #2868, we need to apply relatively simple touchpad config tweaks to a fair number of units to improve performance.
As also highlighted in that issue is that manually adding models is a slow process (not helped by yours truly often being super-slow to merge stuff).

Can we be smarter about trackpad config?  Is there something in common with these trackpads that would indicate the changes are needed?

**Comment by xxcriticxx** [comment]
thx for the merge

**Comment by xxcriticxx** [comment]
is `setxkbmap` necessary? or only `synclient FingerLow=1 FingerHigh=5`?

**Comment by dnschneid** [comment]
synclient is for the trackpad.  setxkbmap is for the keyboard.

**Comment by dnschneid** [comment]
Implemented #3142
