### ISSUE TITLE
got error i don't know how to fix

### ISSUE THREAD

**Issue by xxcriticxx** [dnschneid/crouton#2892]
```
crosh> shell
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161028111244~master:948ee6dc
release: xenial
architecture: amd64
xmethod: xorg
targets: unity-desktop
host: version 8743.83.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13100-g25aa309 #1 SMP PREEMPT Wed Nov 2 23:40:00 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
error msg `http://pastebin.com/efXHxaeM`. i don't how to fix this, when i try to open terminal it's closes by itself

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

Your pastebin file doesn't seem to show the whole output, all the way down to the where it exits and you get the command prompt back.

Does your unity desktop open or does it fail/quit before that?
If it does not open, try getting into the chroot and launching it there -
> `sudo enter-chroot -n xenial`
> `startunity`

And let us know if your unity desktop opens then.

If that doesn't work, you may have to run it again and give us the entire output to dig deeper.

*Hope this helps,*
-**DennisL**

**Comment by xxcriticxx** [comment]
`http://pastebin.com/NmtrPm83` thats the whole log there is nothing more pass `(II) AIGLX: Suspending AIGLX clients for VT switch`

desktop opens but with error `Unknown username "geoclue" in message bus configuration file`

**Comment by DennisLfromGA** [comment]
@xxcriticxx,

If the desktop opens I would ignore the error and go on about my business.

There may be some kind of problem with geoclue and the d-bus but it's for geolocation so I don't think it will interfere with what you're doing.

note: you may see other errors and you can report them if you like but please let us know if thy are preventing your desktop from opening, etc.

*Thanx,*
-**DennisL**

**Comment by xxcriticxx** [comment]
my terminal crashes upon opening it

**Comment by xxcriticxx** [comment]
getting more and more errors

`http://pastebin.com/V86gtRyr`
