### ISSUE TITLE
Sass Error - excluding symbolic link index.js & lib\index.js

### ISSUE THREAD

**Issue by Kyterneser** [dnschneid/crouton#2895]
The sass installation has the following response:

C:\Dev>npm install sass
**npm WARN excluding symbolic link index.js -> lib/sass.js
npm WARN excluding symbolic link lib\index.js -> sass.js**
sassEssentials@0.0.1 C:\Dev
`-- sass@0.5.0

npm WARN sassEssentials@0.0.1 No license field.

C:\Dev>npm install -g sass
npm WARN excluding symbolic link index.js -> lib/sass.js
npm WARN excluding symbolic link lib\index.js -> sass.js
C:\Users\Zoltán\AppData\Roaming\npm
`-- sass@0.5.0

After the installation I tried to check the version:

C:\Dev>sass -v
'sass' is not recognized as an internal or external command,
operable program or batch file.

Could you please advise?

**Comment by dnschneid** [comment]
> `C:\`

I see your problem there.  Try wiping and installing Linux.

Also, #262

**Comment by KIC** [comment]
This also happens on my ubuntu machine it is not windows related ...
