### ISSUE TITLE
keyring file not available... can't install

### ISSUE THREAD

**Issue by doogalbear** [dnschneid/crouton#2897]
After updating my chroot about a week or so ago and it failed, I have not been able to install Ubuntu on my chromebook. I use the following command to install as I'm installing on a SD card: 
`sudo sh -e ~/Downloads/crouton -r trusty -t touch,xfce -e -p /media/removable/Ubuntu`
**Then it ask for password as it should:** 
Choose an encryption passphrase for trusty: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
Installing trusty-amd64 chroot to /media/removable/Ubuntu/chroots/trusty
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2016-11-19 19:47:34 URL:http://dist1.800hosting.com/debian/pool/main/d/debootstrap/ [6912/6912] -> "-" [1]
Downloading debootstrap version 1.0.87...
2016-11-19 19:47:35 URL:http://dist1.800hosting.com/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease

I get this error and it fails to install. I have also tried using `-m http://mirror.hmc.edu/ubuntu` with no luck. Can someone tell what I am doing wrong?

**Comment by leoparder** [comment]
I have the same issue. I tried two days ago and today, same :

> Download from Debian gitweb failed. Trying latest release...
> 2016-12-21 12:10:07 URL:http://debian.proxad.net/debian/pool/main/d/debootstrap/ [6667/6667] -> "-" [1]
> Downloading debootstrap version 1.0.87...
> 2016-12-21 12:10:11 URL:http://debian.bononia.it/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
> Patching debootstrap...
> Downloading bootstrap files...
> W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
> I: Retrieving InRelease 
> W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease

Checking this link, I see the file seems named "Release" and not "InRelease".
See : http://archive.ubuntu.com/ubuntu/dists/trusty/

What should I do ? I tried a mirror like advised on some websites, no luck.

**Comment by ChaosSpear** [comment]
Having the same issue.  I tried the solution that was found in https://github.com/dnschneid/crouton/issues/2387, i.e. removing the installer-cache file, which I think is automatically cleaned up at this point(at least, it's never there when I look for it).

Reading through the archives, I'm a little confused - does crouton currently make use of the keyring or not?  I.e. is the error message legitimate or not?

**Comment by ChaosSpear** [comment]
OKAY!  I tried this with xenial instead of trusty, and it worked.  The keyring error still came up but there were no failed downloads and at the end of it all, it worked!

**Comment by doogalbear** [comment]
ChaosSpear,  can you verify when installing either by terminal or software manager you don't get the http failed error. I would really like to have Linux back on my chromebook, but keep running into these errors. Thank you

**Comment by ChaosSpear** [comment]
Terminal. Wasn't even aware that you could set up Crouton otherwise.

**Comment by doogalbear** [comment]
ChaosSpear, my apologies. That was worded wrong. I meant after getting xenia, trusty, or whatever version you chose and successfully installed now you need programs. Say you were to install libreoffice for example, either in terminal or by software manager do you get any errors. I was getting http failed error 4. Have you encountered this issue?

**Comment by ChaosSpear** [comment]
So far, I've installed VLC and removed Transmission.  Everything seems fine so far.  I'm certainly getting further than I was with precise or trusty.

**Comment by doogalbear** [comment]
That is good to hear. I'll give it a try. Are you using any special commands or servers during setup. Thank you for your time.

**Comment by ChaosSpear** [comment]
I didn't find any advantage to using a mirror, but you may find otherwise.  I just specified encryption, xenia for the release, and I was using lxde-desktop as my target.  I did make sure to delete all my previous chroots before starting.

**Comment by drinkcat** [comment]
#2362
