### ISSUE TITLE
sudo startxfce4 error

### ISSUE THREAD

**Issue by macroghan** [dnschneid/crouton#2899]
When running the following command

`sudo startxfce4`

I receive the following error:

```
(xfce4-session:14534): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
Failed to connect to Xfconf daemon: //bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon
```

Anyone know how to fix this?

Thanks!

**Comment by jimbo10001** [comment]
i got the exact same one. im using the acer r11 chromebook but its too plain so i want to get ubuntu. i hope someone can fix this also.

**Comment by DennisLfromGA** [comment]
@macroghan & @jimbo10001,

I don't know if you noticed but there is a form that we ask you to complete when opeinng a new issue.
It gathers some important details which helps us help you, I'm providing it below, please complete it.

#### Please paste the output of the following command here: sudo edit-chroot -all
```
```

#### Please describe your issue:


#### If known, describe the steps to reproduce the issue:

------
*Thanx,*
-**DennisL**

**Comment by jimbo10001** [comment]
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161116131524~master:9db73043
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8743.85.0 (Official Build) stable-channel cyan
kernel: Linux localhost 3.18.0-13101-g57e8190 #1 SMP PREEMPT Tue Nov
15 18:22:39 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as
another instance is using it.

**Comment by DennisLfromGA** [comment]
@jimbo10001,

Well that's a start, now:

#### Please describe your issue:


#### If known, describe the steps to reproduce the issue:

-----
-**DennisL**
