### ISSUE TITLE
realtime audio not working (after installing cast/chromecast?)

### ISSUE THREAD

**Issue by ZestieBumwhig** [dnschneid/crouton#2903]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20160715134041~master:0dc76a22
release: xenial
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi,xorg
host: version 8743.85.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Nov 15 18:15:16 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Yesterday I was running Supercollider in Crouton (through Jack), as well as this lil' guy could be expected to (no Xruns, real-time, etc). Later, I tried installing the software to use my friend's Chromecast, and now I seem unable to run audio with real-time permissions. Even simple Supercollider patches experience massive Xruns, and the audio glitches.

Various forums also seem to suggest that I can't completely uninstall the Cast "things" I installed (I don't know if it's an extensions or an app or what). The icon is, indeed, still on my toolbar, right next to the sexy Crouton "C".

It COULD be coincidence... minor issues always come up. But I don't think so. The lack of real-time priority came RIGHT after I installed "cast."

(new error from Pure Data:
JACKerror: cannot use real-time scheduling (RR/5) (1: Operation not permitted)
and from Supercollider:
Couldn't set realtime scheduling priority 1: operation not permitted
)

Also, I've up-to-date via Synaptic, but the crouton -u hasn't worked for me for a while, b/c of "unable to determine the release."

any ideas, anybody?

**Comment by DennisLfromGA** [comment]
@ZestieBumwhig,

> crouton: version 1-20160715134041~master:0dc76a22

That's a very old version of crouton, what I would do is -
1. Backup your chroot: `sudo edit-chroot -bf ~/Downloads xenial`
2. Update your chroot: `sudo sh ~/Downloads/crouton -n xenial -u`

And see if the issue goes away.

*Hope this helps,*
-**DennisL**

**Comment by ZestieBumwhig** [comment]
Thank you @DennisLfromGA .

I've been unable to update my chroot for a few months now. First - following your example - I am told "Unable to determine the release... please specify it with -r." I assume this is also xenial, so when I enter
... -n xenial -u -r xenial

I am told:
Release doesn't match! Please correct the -r option, or specify a second -u to
change the release, upgrading the chroot (dangerous).

I've never done anything weird to warrant such behavior.  So... maybe it's time to re-install, since I've just backed up my chroot onto a USB?

Thanks again.

**Comment by DennisLfromGA** [comment]
@ZestieBumwhig,

If you're really curious as to what release is *supposed* to be installed you can get into your chroot and look at a couple of files using:  

    sudo enter-chroot -n xenial
    cat /etc/lsb-release
    cat /etc/apt/sources.list
    exit

and check to see if those files show 'xenial` as the release or some other.

I've never *forced* a release wth the `-uu` option so I can't really recommend that but if the above files actually show 'xenial' and you have it backed up I think it might be worth a try - and a good experiment.

*Hope this helps,*
-**DennisL**

**Comment by ZestieBumwhig** [comment]
@DennisLfromGA 

This is now well outside the scope of my original question - but as long as I've got you on the line...

Apparently I don't know how to "force[d] a release with the `-uu` option." It looks like SOMETHING special is happening, but then, five seconds later, nothing is changed - I receive the same errors when trying to upgrade with -u, -n, and/or -r.
`$ sudo sh ~/Downloads/crouton -uu -n xenial -r xenial`
`/usr/local/chroots/xenial already exists; updating it...
WARNING: Changing the chroot release to xenial.
Press Control-C to abort; upgrade will continue in 5 seconds.`

And it seems as though I do have only xenials in my wheelhouse - here's the results of the `cat`s you suggested:
`$ cat /etc/lsb-release`
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"`
`$ cat /etc/apt/sources.list`
`deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial multiverse universe restricted main 
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-updates multiverse universe restricted main 
deb http://ports.ubuntu.com/ubuntu-ports/ xenial multiverse universe restricted main 
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-updates multiverse universe restricted main 
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse universe restricted main 
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse universe restricted main `

Any suggestions? Is it powerwash time?
