### ISSUE TITLE
which all version of selenium and gc driver is compatible with windows 8.1 64 bit

### ISSUE THREAD

**Issue by shivanipatwal90** [dnschneid/crouton#2909]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by shivanipatwal90** [comment]
I am using window 8.1 64 bit. and i have tried my scripts on it using selenium 3.0 and FireFox 50, used gecko driver too. nut no luck
i too tried with selenium version 2.53 with Google chrome 54 on same OS but getting error like
Invalid port. Exiting...
????? ??, ???? ??:??:?? ??????? org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

**Comment by divx118** [comment]
Your posting on the crouton issue tracker. Please close this issue and post your question on the relevant issue tracker.
see #262
