### ISSUE TITLE
shema update problem 

### ISSUE THREAD

**Issue by mustaphajamel** [dnschneid/crouton#2910]
i typed doctrine:shemaupdate 
error : No Metadata Classes to process.
here's the entity
<?php
/**
 * Created by PhpStorm.
 * User: jamel_pc
 * Date: 2016-11-27
 * Time: 9:16 PM
 */

namespace Esprit\ParcBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Modele
 * @package ParcBundle\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="Modele")
 */
class Modele{
    /**
     *@ORM\GeneratedValue(strategy="Auto")
     *@ORM\Id
     *@ORM\Column(type="integer")
     */
private $id;
    /**
     * @ORM\Column(type="string",length=255)
     *
     */

    private $Libelle;
    /**
     * @ORM\Column(type="string",length=255)
     */

    private $Pays;
    /**
     * @ORM\Column(type="string",length=255)
     */

    /**
     * @return mixed
     */
    public function getLibelle()
    {
        return $this->Libelle;
    }

    /**
     * @param mixed $Libelle
     */
    public function setLibelle($Libelle)
    {
        $this->Libelle = $Libelle;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPays()
    {
        return $this->Pays;
    }

    /**
     * @param mixed $Pays
     */
    public function setPays($Pays)
    {
        $this->Pays = $Pays;
    }

}

**Comment by mustaphajamel** [comment]
<?php
/**
 * Created by PhpStorm.
 * User: jamel_pc
 * Date: 2016-11-27
 * Time: 9:16 PM
 */

namespace Esprit\ParcBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Modele
 * @package ParcBundle\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="Modele")
 */
class Modele{
    /**
     *@ORM\GeneratedValue(strategy="Auto")
     *@ORM\Id
     *@ORM\Column(type="integer")
     */
private $id;
    /**
     * @ORM\Column(type="string",length=255)
     *
     */

    private $Libelle;
    /**
     * @ORM\Column(type="string",length=255)
     */

    private $Pays;
    /**
     * @ORM\Column(type="string",length=255)
     */

    /**
     * @return mixed
     */
    public function getLibelle()
    {
        return $this->Libelle;
    }

    /**
     * @param mixed $Libelle
     */
    public function setLibelle($Libelle)
    {
        $this->Libelle = $Libelle;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPays()
    {
        return $this->Pays;
    }

    /**
     * @param mixed $Pays
     */
    public function setPays($Pays)
    {
        $this->Pays = $Pays;
    }

}

**Comment by mustaphajamel** [comment]
`<?php
/**
 * Created by PhpStorm.
 * User: jamel_pc
 * Date: 2016-11-27
 * Time: 9:16 PM
 */

namespace Esprit\ParcBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Modele
 * @package ParcBundle\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="Modele")
 */
class Modele{
    /**
     *@ORM\GeneratedValue(strategy="Auto")
     *@ORM\Id
     *@ORM\Column(type="integer")
     */
private $id;
    /**
     * @ORM\Column(type="string",length=255)
     *
     */

    private $Libelle;
    /**
     * @ORM\Column(type="string",length=255)
     */

    private $Pays;
    /**
     * @ORM\Column(type="string",length=255)
     */

    /**
     * @return mixed
     */
    public function getLibelle()
    {
        return $this->Libelle;
    }

    /**
     * @param mixed $Libelle
     */
    public function setLibelle($Libelle)
    {
        $this->Libelle = $Libelle;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPays()
    {
        return $this->Pays;
    }

    /**
     * @param mixed $Pays
     */
    public function setPays($Pays)
    {
        $this->Pays = $Pays;
    }









}`

**Comment by dnschneid** [comment]
#262
