### ISSUE TITLE
Kali-Rolling Starts after first install then install kali-linux-full then can't access using startxxxxx (EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)

### ISSUE THREAD

**Issue by McR1c0chet** [dnschneid/crouton#2912]
Build Date: 06 September 2016  01:32:44PM
xorg-server 2:1.18.4-2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Nov 27 20:23:22 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

After installing basic kali-rolling in crouton everything starts as normal,
Close the chroot and get log filr error.
Deleting log file and will start again once. After that I get the error above.

Lived, died, raved and repeated but always end up in the same place.

Please help!!

Using Lenovo N22.

Much appreciated,

RICO

**Comment by McR1c0chet** [comment]
Log file output:

[ 34968.230] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[ 34968.233] 
X.Org X Server 1.18.4
Release Date: 2016-07-19
[ 34968.234] X Protocol Version 11, Revision 0
[ 34968.234] Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
[ 34968.234] Current Operating System: Linux localhost 3.18.0-13101-g57e8190 #1 SMP PREEMPT Tue Nov 15 18:23:54 PST 2016 x86_64
[ 34968.234] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=5d79dbe9-d819-0843-8bb2-73ded3f35ba8/PARTNROFF=1 hashtree=PARTUUID=5d79dbe9-d819-0843-8bb2-73ded3f35ba8/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=c40e8b02494e2cb3e3b8863fcb7453802f7528f1 salt=1099e9495b172f61d71068b04e74cfdb15ac8b12683867f5b8219521e6284048" noinitrd vt.global_cursor_default=0 kern_guid=5d79dbe9-d819-0843-8bb2-73ded3f35ba8 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
[ 34968.234] Build Date: 06 September 2016  01:32:44PM
[ 34968.234] xorg-server 2:1.18.4-2 (https://www.debian.org/support) 
[ 34968.234] Current version of pixman: 0.34.0
[ 34968.234]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[ 34968.234] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 34968.246] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Dec  8 19:35:10 2016
[ 34968.247] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 34968.248] (==) No Layout section.  Using the first Screen section.
[ 34968.248] (==) No screen section available. Using defaults.
[ 34968.248] (**) |-->Screen "Default Screen Section" (0)
[ 34968.248] (**) |   |-->Monitor "<default monitor>"
[ 34968.249] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[ 34968.249] (==) Automatically adding devices
[ 34968.249] (==) Automatically enabling devices
[ 34968.249] (==) Automatically adding GPU devices
[ 34968.249] (==) Max clients allowed: 256, resource mask: 0x1fffff
[ 34968.251] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[ 34968.251]    Entry deleted from font path.
[ 34968.261] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/100dpi/:unscaled,
        /usr/share/fonts/X11/75dpi/:unscaled,
        /usr/share/fonts/X11/Type1,
        /usr/share/fonts/X11/100dpi,
        /usr/share/fonts/X11/75dpi,
        built-ins
[ 34968.261] (==) ModulePath set to "/usr/lib/xorg/modules"
[ 34968.261] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[ 34968.262] (II) Loader magic: 0x7fa654623dc0
[ 34968.262] (II) Module ABI versions:
[ 34968.262]    X.Org ANSI C Emulation: 0.4
[ 34968.262]    X.Org Video Driver: 20.0
[ 34968.262]    X.Org XInput driver : 22.1
[ 34968.262]    X.Org Server Extension : 9.0
[ 34968.309] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[ 34968.310] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 34968.310] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 34968.313] (--) PCI:*(0:0:2:0) 8086:22b1:8086:7270 rev 53, Mem @ 0xd0000000/16777216, 0xc0000000/268435456, I/O @ 0x00001000/64
[ 34968.313] (II) LoadModule: "glx"
[ 34968.314] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[ 34968.329] (II) Module glx: vendor="X.Org Foundation"
[ 34968.329]    compiled for 1.18.4, module version = 1.0.0
[ 34968.329]    ABI class: X.Org Server Extension, version 9.0
[ 34968.329] (==) AIGLX enabled
[ 34968.329] (==) Matched modesetting as autoconfigured driver 0
[ 34968.329] (==) Matched fbdev as autoconfigured driver 1
[ 34968.329] (==) Matched vesa as autoconfigured driver 2
[ 34968.329] (==) Assigned the driver to the xf86ConfigLayout
[ 34968.329] (II) LoadModule: "modesetting"
[ 34968.329] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[ 34968.331] (II) Module modesetting: vendor="X.Org Foundation"
[ 34968.331]    compiled for 1.18.4, module version = 1.18.4
[ 34968.331]    Module class: X.Org Video Driver
[ 34968.331]    ABI class: X.Org Video Driver, version 20.0
[ 34968.331] (II) LoadModule: "fbdev"
[ 34968.331] (WW) Warning, couldn't open module fbdev
[ 34968.331] (II) UnloadModule: "fbdev"
[ 34968.331] (II) Unloading fbdev
[ 34968.331] (EE) Failed to load module "fbdev" (module does not exist, 0)
[ 34968.331] (II) LoadModule: "vesa"
[ 34968.332] (WW) Warning, couldn't open module vesa
[ 34968.332] (II) UnloadModule: "vesa"
[ 34968.332] (II) Unloading vesa
[ 34968.332] (EE) Failed to load module "vesa" (module does not exist, 0)
[ 34968.332] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[ 34968.332] (EE) 
Fatal server error:
[ 34968.332] (EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
[ 34968.332] (EE) 
[ 34968.336] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[ 34968.344] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[ 34968.344] (EE) 

Thanks in advance!!

**Comment by vbouderau03** [comment]
I have been having the same problem forever!

**Comment by divx118** [comment]
@McR1c0chet @vbouderau03 Did you try updating the chroot after installing kali-linux-full?

**Comment by vbouderau03** [comment]
yes @divx118

**Comment by divx118** [comment]
@vbouderau03 Could you give the output of `sudo edit-chroot -al` so we have all the information? I just tried to replicate on my acer chromebook for work (lars), but the chroot still started. Maybe it is device related.

**Comment by dnschneid** [comment]
#2875

**Comment by McR1c0chet** [comment]
Thanks all!!
#2875 fixed the issue for me.
