### ISSUE TITLE
How to or Where to put an API of social media in Ionic Framework

### ISSUE THREAD

**Issue by jb181991** [dnschneid/crouton#2913]
Good day to all. Badly need help here.
I just wanna ask about Ionic Framework. I want to create an android and iOS app that can manage all communication tools (e.g. Gmail, Outlook, Facebook, Twitter, LinkedIn etc.) just like this app right here [https://play.google.com/store/apps/details?id=com.Creata.socialnetworkingall&hl=en](here) but since I'm new in Ionic, I don't know where to start yet. Though I know that it needs an API but I don't know where to put the API.

**Comment by dnschneid** [comment]
Welcome to the **crouton** issue tracker!
#262
