### ISSUE TITLE
Running openVPN in your chroot, a fix

### ISSUE THREAD

**Issue by l8rb8r** [dnschneid/crouton#2916]
Hey everybody.  I spent most of the day trying to get my internet traffic going through a VPN network with openVPN.  I thought I'd gather together all the pieces for an easy solution that worked on my Dell Chromebook 13, though it should work on any Chromebook.  Basically, I ran into 2 problems:

1.  Chrome OS keeps tight control over all network traffic.  This means:
* Since Chrome OS destroys all unrecognized tun devices, your VPN will likely fail.  Or, at the least, generate an enormous amount of error messages, which, if kept in a log file will overwhelm your storage space in a short time.  To fix this see [here](https://github.com/dnschneid/crouton/issues/2215).  In short, you must enter the following before running openVPN:
```
sudo stop shill
sudo start shill BLACKLISTED_DEVICES=tun0
```
* But see the scripts on that page for a cleaner implementation.  You probably don't need to worry about forwarding the DNS because, see 2.
* Chrome OS does not, as far as I'm aware, allow any Linux program access to the network configuration.  I haven't found a fix for this yet.  The issue was raised [here](https://github.com/dnschneid/crouton/issues/611), but unfortunately, it was closed before there was any resolution.  There may be no viable solution.  For now, you'll just have to configure all networking in Chrome.

2. DNS requests do not make it back to the sender.  The fix I am using at the moment is to direct all DNS traffic through Google Public DNS (8.8.4.4,8.8.8.8).  You can set this quickly by going into *SETTINGS*>*Internet connection*, clicking on *your network name*, clicking on the *Network* tab, and selecting the *Google name servers* radio button. 

That should do the trick for anyone having internet problems when running openVPN in Linux.  One thing you might notice, for good or for ill, is that with openVPN running in Linux, all your internet traffic will be routed through your VPN--even traffic generated by Chrome OS.

**Comment by marczis** [comment]
l8rb8r: After several days, trying to setup vpn on chrome os, I found your answer... THANKS A LOT !

**Comment by aubguillemette** [comment]
mvp! thanks!

**Comment by mrmcboomer** [comment]
I tried what you said, but for some reason, the process always hangs on 'Initialization Sequence Completed'. Any help would be appreciated.

**Comment by skuldug12** [comment]
@mrmcboomer it's supposed to... that means that everything went successfully, and the process is just running without output. if u kill the terminal instance it's on u kill the vpn connection too.

**Comment by chonkey821** [comment]
This doesn't work anymore on Version 91.0.4472.25 (Official Build) beta (64-bit)

**Comment by primas305** [comment]
Found a fix....the shill command has changed now
sudo stop shill
sudo start shill BLOCKED_DEVICES=tun0

although i could get he vpn to connect now the traffic is not being routed through th vpn smh...can anyone help with this
