### ISSUE TITLE
Acer C720 Crosh Won't Open

### ISSUE THREAD

**Issue by zclayhubbard** [dnschneid/crouton#2918]
Hello! I'm fairly new to programming, currently taking classes in Java. However, my main computer is an Acer C720, and I wanted to use Crouton to give me access to Ubuntu. I believe I have successfully installed the chroot, but in order to launch xfce I need to open a crosh shell, and I can't open one. The shortcut doesn't work for me, unless I use a Guest account.

Is this normal? Is there a setting in my account that is stopping the crosh? Anyone know what I'm doing wrong? I'd really appreciate any help anyone can offer.

Thank you so much!

**Comment by DennisLfromGA** [comment]
@zclayhubbard,

>  I believe I have successfully installed the chroot, ...

You would need to use a crosh shell terminal session to install a crouton chroot, do you mean you 'downloaded' crouton and are now trying to open a crosh shell?

> but in order to launch xfce I need to open a crosh shell, and I can't open one.

Are you logged into your Chromebook with the same account that you installed crouton with?

> The shortcut doesn't work for me, unless I use a Guest account.

You should be using <kbd>Ctrl</kbd> + <kbd>Altl</kbd> +<kbd>t</kbd>, what shortcut are you using?

Can you open the Developer Console using <kbd>Ctrl</kbd> + <kbd>Altl</kbd> +<kbd>F2/-></kbd> and login as user 'chronos'?

> Is this normal? Is there a setting in my account that is stopping the crosh?

Nope, not normal. Are you absolutely sure you are in ['Developer mode'](http://www.chromium.org/a/chromium.org/dev/chromium-os/developer-information-for-chrome-os-devices/acer-c720-chromebook#TOC-Developer-Mode) and not just using the ['Dev channel'](https://support.google.com/chromebook/answer/1086915?hl=en)?

*Hope this helps,*
-**DennisL**

**Comment by zclayhubbard** [comment]
@DennisLfromGA I did successfully open the crosh shell in a Guest account and launched my chroot. However whenever I'm logged into my personal account, the only one on this computer, the ctrl + alt + t command doesn't garner a reaction at all. I can open a Developer console and login as chronos. I'm positive that I'm in developer mode, but I'm in the Beta Channel, not the Dev Channel. Should I switch?

Thank you so much!

**Comment by DennisLfromGA** [comment]
@zclayhubbard,

If it works using the guest account and not in yours then it may be an extension interfering with it.
This is something we deal with frequently in [Chromebook Central](https://productforums.google.com/forum/#!forum/chromebook-central) and can usually be resolved by a ['Reset Chrome settings to default'](https://support.google.com/chromebook/answer/3296214?hl=en).
If you use the ['Extensity'](https://chrome.google.com/webstore/detail/extensity/jjmflmamggggndanpgfnpelongoepncg) extension you can toggle your extensions on/off one-at-a-time or all at once, it's very handy.

One other thing you could try and one that I use is the ['Crosh Window'](https://chrome.google.com/webstore/detail/crosh-window/nhbmpbdladcchdhkemlojfjdknjadhmh?utm_source=chrome-app-launcher-search) extension, it requires the ['Secure Shell'](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?utm_source=chrome-app-launcher-search) extension to be installed too. It doesn't rely on the <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>t</kbd> keyboard combo.

*Hope this helps,*
-**DennisL**

**Comment by zclayhubbard** [comment]
@DennisLfromGA That's so helpful! I'll try those thank you so much!

**Comment by zclayhubbard** [comment]
For the record, I ended up fixing this problem! The crosh window app works great, but the reason my ctrl - alt - T command wasn't working was because I had assigned alt to do something different in my Keyboard Settings. Replacing it allowed the command to work and a terminal to open in Chrome like normal! Thanks so much.
