### ISSUE TITLE
No Audio in chroot

### ISSUE THREAD

**Issue by Nerfan** [dnschneid/crouton#2925]
```
sudo edit-chroot -all
name: stretch
encrypted: no
Entering /media/removable/USB Drive/stretch...
crouton: version 1-20161129162558~master:5f2f11f9
release: stretch
architecture: amd64
xmethod: xorg
targets: keyboard,core,chromium,audio
host: version 8743.85.0 (Official Build) stable-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Tue Nov 15 18:26:30 PST 2016 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
When in my chroot, audio from browsers and from `speaker-test` will not play. Audio from `mpd` or `aplay /usr/share/sounds/alsa/Front_Center.wav` will play. `aplay -l` gives `aplay: device_list:268: No sound card found...`.

#### If known, describe the steps to reproduce the issue:
`sudo enter-chroot`
`xinit`
Try to play sound from Firefox; it doesn't play.

I'm using i3wm via xinit, so no DE.

**Comment by DanHolli123** [comment]
try using alsamixier in a terminal

**Comment by Nerfan** [comment]
alsamixer works properly, or at least I think it does. It shows Card and Chip as CRAS, and displays the current audio level properly. My chroot is updated as of 12/4.

**Comment by dcecile** [comment]
@Nerfan Were you able to solve this?

I think I'm seeing the same problem on Debian Sid (before and after updating my chroot today).

(Audio from browser or `mpv` doesn't work, but both `alsamixer` and `aplay /usr/share/sounds/alsa/Front_Center.wav` work, while `aplay -l` fails with your same error message.)

The error message ("No sound card found") is weird because there are two cards shown when using `cat /proc/asound/cards`:

```
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xd1314000 irq 314
 1 [chtrt5650      ]: chtrt5650 - chtrt5650
                      chtrt5650
```

Maybe this issue is similar to #45? Running `sudo aplay -l` gives me these devices:

```
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: chtrt5650 [chtrt5650], device 0: 1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by Nerfan** [comment]
@dcecile I haven't been able to solve this problem. I get very similar output to you when running those two commands (basically identical but different hardware).

**Comment by dcecile** [comment]
I wanted to see if there's something that I messed up in my chroot after creating it, so I created two new chroots from scratch...

* **Debian Sid**: no setup changes, same release as my primary chroot, same sound playback problems
* **Ubuntu Trusty**: no setup changes, no sound playback problems

Why would Trusty be fine? Is there something in Sid that's incompatible with the CRAS that gets put into the chroot?

**Comment by baltedewit** [comment]
@dcecile Ubuntu Trusty runs on an older Linux kernel. Audio will work on kernels 3.x but not on kernels 4.x

There is an issue about this in either the GalliumOS or chrx repo (can't remember which) with no solution yet.

**Comment by dcecile** [comment]
OK, so I think I've got it working now by installing an older version of [`libasound2`](https://packages.debian.org/jessie/libasound2) (and [`libasound2-data`](https://packages.debian.org/jessie/libasound2-data)).

1. Debian Jessie works fine, so I copied the `sid` lines in `/etc/apt/sources.list` file and modified them to say `jessie`
2. Uninstalled new ALSA with `sudo apt remove libasound2{,-data}`
3. Installed old ALSA with `sudo apt install -t jessie libasound2{,-data}`
4. Put holds on these packages to avoid upgrading `sudo apt-mark hold libasound2{,-data}`

(You'll also need to use `alsa-utils` from Jessie.)

P.S. I couldn't find any similar [GalliumOS](https://github.com/GalliumOS/galliumos-distro/issues?utf8=%E2%9C%93&q=is%3Aissue%20audio) or [chrx](https://github.com/reynhout/chrx/issues?utf8=%E2%9C%93&q=is%3Aissue%20audio) issues. Also, I think this might not be kernel related, because `dpkg -l | grep linux-image` seems to indicate that no kernel is installed in the chroot.

**Comment by dcecile** [comment]
I had to update Crouton today, and after updating back to the latest version of `libasound2`, the problem is still here. I can't figure out how to work around this beside downgrading `libasound2`.

**Comment by pogo555** [comment]
New crouton. Debian buster armhf. No sound. Sound in CrOS ok.

**Comment by pogo555** [comment]
@dcecile ,I tried this and failed half way through. Uninstalling ALSA went ok, but it uninstalled 500Mb of files, which seemed quite a lot. 

Installing the old ALSA using `sudo apt install -t jessie libasound2{,-data}` failed with:

`E: The value 'jessie' is invalid for APT::Default-Release as such a release is not available in the sources
` 
So I put the sources.list file back as it was and reinstalled ALSA. Trying to start pulseaudio returns
`bash: /usr/bin/pulseaudio: No such file or directory`
So I still have no sound, but seem to have done more damage during the uninstall/reinstall loop.

Ah well, it was worth a try...

**Comment by pogo555** [comment]
But I couldn't just leave it broken, so I reinstalled the crouton using jessie as the release and I have sound. So something is broken in later debian releases.

I'll leave it at that for now, but if anyone can suggest how to get sound in a later release, I'd be happy(ish) to try it out.

**Comment by chriswells0** [comment]
Just FYI: This seems to be fixed. I was having the same issue earlier today, updated my Stretch chroot, and it's working now.

**Comment by Aspiring-Writer** [comment]
No audio in Debian Buster, I'm going to try Stretch

**Comment by myelin** [comment]
I have no audio in sid, but it looks like the root user does.  Adding myself to the hwaudio group fixed this:

```phil@localhost:~$ strace aplay -l
[...]
ioctl(0, TCGETS, {B9600 opost isig icanon echo ...}) = 0
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/dev/aloadC0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

phil@localhost:~$ sudo strace aplay -l
[...]
ioctl(0, TCGETS, {B9600 opost isig icanon echo ...}) = 0
openat(AT_FDCWD, "/dev/snd/controlC0", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7ffdbf5a9c50) = 0
close(3)                                = 0
newfstatat(1, "", {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x6), ...}, AT_EMPTY_PATH) = 0
write(1, "**** List of PLAYBACK Hardware D"..., 44**** List of PLAYBACK Hardware Devices ****

phil@localhost:~$ ls -al /dev/snd/controlC0
crw-rw----. 1 root hwaudio 116, 13 Jan 10 08:52 /dev/snd/controlC0

phil@localhost:~$ sudo gpasswd -a phil hwaudio
Adding user phil to group hwaudio

phil@localhost:~$ logout

localhost ~ # enter-chroot -n sid-test-from-zipfile2
Entering /media/removable/extssd/crouton/chroots/sid-test-from-zipfile2...

(sid-test-from-zipfile2)phil@localhost:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofrt5682 [sof-rt5682], device 0: smart373-spk (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by myelin** [comment]
Ah, no, that's not the problem.  It looks like the cras module isn't loading, and adding myself to hwaudio just let ALSA bypass it and talk to the hardware directly -- as in https://github.com/dnschneid/crouton/wiki/Access-audio-hardware-directly-(ALSA,-JACK)

Confirmation that ALSA doesn't know about cras:

```
(sid-test-from-zipfile2)phil@localhost:~$ cat /dev/urandom | aplay -Dcras -                                                                                                                                                                                    
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cras
aplay: main:831: audio open error: No such file or directory
```

Trying to start pulseaudio:

```
(sid-test-from-zipfile2)phil@localhost:~$ DISPLAY=:1.0 pulseaudio 
E: [pulseaudio] module.c: Failed to load module "module-alsa-sink" (argument: "device=cras sink_name=cras-sink"): initialization failed.
E: [pulseaudio] module.c: Failed to load module "module-alsa-source" (argument: "device=cras source_name=cras-source"): initialization failed.
E: [pulseaudio] main.c: Sink cras-sink does not exist.
E: [pulseaudio] main.c: Source cras-source does not exist.
```

(I'm specifying DISPLAY here because I'm doing this over ssh, but I have a running xfce session).

It does look like we have access to CRAS:

```
(sid-test-from-zipfile2)phil@localhost:~$ cras_test_client --dump_server_info                                                                                                                                                                                  
System Volume (0-100): 100 
Capture Muted : Not muted
User muted: Not muted
Output Devices:
	ID	MaxCha	Name
	15	0	sof-rt5682: :0,5
	14	0	sof-rt5682: :0,4
	13	0	sof-rt5682: :0,3
	12	0	sof-rt5682: :0,2
	8	2	sof-rt5682: :0,1
	7	2	sof-rt5682: :0,0
Output Nodes:
	Stable Id	ID	Vol  UI       Plugged	L/R swapped	     Time Hotword	Type		MaxCha Name
	(76f39a73)	15:0	 100 0.000000      no	           no	        0        	HDMI                 0 sof-rt5682 HDMI/DP,pcm=5
	(b5fe4622)	14:0	 100 0.000000      no	           no	        0        	HDMI                 0 sof-rt5682 HDMI/DP,pcm=4
	(dfa08336)	13:0	 100 0.000000      no	           no	        0        	HDMI                 0 sof-rt5682 HDMI/DP,pcm=3
	(8a033e9d)	12:0	 100 0.000000      no	           no	        0        	HDMI                 0 sof-rt5682 HDMI/DP,pcm=2
	(62f96cde)	8:0	 100 0.000000      no	           no	        0        	HEADPHONE            2 Headphone
	(72a57953)	7:0	   8 0.000000     yes	           no	1641833549        	INTERNAL_SPEAKER     2*Speaker
Input Devices:
	ID	MaxCha	Name
	16	2	sof-rt5682: :0,100
	11	2	sof-rt5682: :0,1
	10	4	sof-rt5682: :0,99
	9	2	sof-rt5682: :0,0
	6	2	Post DSP Delayed Loopback
	5	2	Post DSP Loopback
	4	2	Post Mix Pre DSP Loopback
Input Nodes:
	Stable Id	ID	Gain  UI       Plugged	L/R swapped	     Time Hotword	Type		MaxCha Name
	(01cdda27)	16:0	  20 1.000000     yes	           no	1641833550 en_all 	HOTWORD              X Wake on Voice
	(61aab6ba)	11:0	  20 1.000000      no	           no	        0        	MIC                  X Mic
	(0039c920)	10:0	  17 1.000000     yes	           no	1641833549        	INTERNAL_MIC         X*Internal Mic
	(b90e0a61)	9:0	  20 1.000000     yes	           no	1641833549        	ECHO_REFERENCE       X Echo Reference
	(ec289a19)	6:0	   0 1.000000     yes	           no	        0        	POST_DSP_DELAYED_LOOPBACK     X Post DSP Delayed Loopback
	(8c74f766)	5:0	   0 1.000000     yes	           no	        0        	POST_DSP_LOOPBACK     X Post DSP Loopback
	(8a04af91)	4:0	   0 1.000000     yes	           no	        0        	POST_MIX_LOOPBACK     X Post Mix Pre DSP Loopback
Attached clients:
	ID	pid	uid
	33	635	1000
Num active streams: 0
Last audio active time: 19507, 528748970
```

**Comment by myelin** [comment]
CRAS does indeed work; I hear static when running this (after bumping up the volume a little) inside the chroot:

```
cras_test_client --playback_f /dev/urandom
```

**Comment by myelin** [comment]
Adding an .asoundrc file setting the default pcm and ctl devices to `type cras` makes aplay work!

```
$ cat > .asoundrc <<EOF
pcm.!default { 
    type cras
}
 
ctl.!default { 
    type cras
}
EOF

$ cat /dev/urandom | aplay -
[static]
```

No luck with speaker-test; it outputs "Stream error -22" and does nothing.

**Comment by myelin** [comment]
Aha!  The trick was to specify pcm.cras and ctl.cras in /etc/asound.conf, as that results in the 'cras' device being created, and PulseAudio can now find it.

```
$ cat | sudo dd of=/etc/asound.conf <<EOF
pcm.cras { 
    type cras
}
 
ctl.cras { 
    type cras
}
EOF

$ cat /dev/urandom | aplay -
[static]

$ pulseaudio
```

I need to manually run 'pulseaudio', but after that the Xfce audio mixer works, and I can play music through SoundCloud on Firefox!

**Comment by myelin** [comment]
Test progress:
- sid, focal, impish: Sound works in Firefox, requires pulseaudio to be started manually.
