### ISSUE TITLE
File system loop error when trying to update

### ISSUE THREAD

**Issue by dvwz** [dnschneid/crouton#2928]
#### Please describe your issue:

I tried to update my chroot using the command below, but I got a file system loop error, seemingly when it tried to move sys to ECRYPTFS_MOVE_STAGING in /media/removable/USB Drive/chroots/trusty. Is this caused by my command or is something else going on?

#### If known, describe the steps to reproduce the issue:

```
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -u -e -k ~/Downloads -p /media/removable/USB\ Drive -n trusty
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
/media/removable/USB Drive/chroots/trusty already exists; updating it...
Choose an encryption passphrase for trusty: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...

done
Encrypting trusty; please wait...mv: cannot move ‘./sys’ to ‘./ECRYPTFS_MOVE_STAGING_Uvr2gs/./sys’: Device or resource busy
find: File system loop detected; `./ECRYPTFS_MOVE_STAGING_Uvr2gs/var/host/media/removable/USB Drive/chroots/trusty' is part of the same file system loop as `.'.
```

**Comment by pmou** [comment]
Newbie. I have this also.  Same as above except with `sudo sh -e ~/Downloads/crouton -u -e -k ~/Downloads -p /media/removable/SD\ Card -n trusty`  Any reason why the command shouldn't work? Thanks.
