### ISSUE TITLE
Can't remove a chroot, command not found 

### ISSUE THREAD

**Issue by lowkey1701** [dnschneid/crouton#2930]
**I'm having a very hard time removing a chroot. When I type into my shell it gives me an error saying** 

chronos@localhost / $ sudo delete-chroot precise
sudo: delete-chroot: command not found

**I've tried shutting off my chromebook, did not work. 
There is however a chroot for sure because I tried updating the chroot via a command and it prompted everything but got an error since i don know the password for that specific chroot.**

chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n precise
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/precise already exists; updating it...
Enter encryption passphrase for precise: 
Failed to decrypt precise.

**(Note: I'm not very experienced with crosh so I might be doing something wrong.)**

**Comment by DennisLfromGA** [comment]
@lowkey1701,

Maybe all or some of the hostbin files were deleted???
You can reinstall them using: `sudo sh ~/Downloads/crouton -n precise -b`
Once that completes try your command again: `sudo delete-chroot precise`

If that doesn't work you can remove it manually but it's a little more dangerous, let us know if the above doesn't work and we'll give you another workaround.

*Hope this helps,*
-**DennisL**

**Comment by lowkey1701** [comment]
@DennisLfromGA 

I got this error:

chronos@localhost / $ sudo sh ~/Downloads/crouton -n precise -b
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
Name, release and encrypt cannot be specified with -b.

**Comment by DennisLfromGA** [comment]
@lowkey1701, 

Sorry, don't specify the name, just use: sudo sh ~/Downloads/crouton -b`

*Hope this helps,*
-**DennisL**

**Comment by lowkey1701** [comment]
@DennisLfromGA 

chronos@localhost / $ sudo sh ~/Downloads/crouton -b
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Done! You can enter the chroot using enter-chroot.


Then I executed

**Comment by DennisLfromGA** [comment]
@lowkey1701,

> Would it be safe to reinstall crouton now?

Yes, it should be, it looks like you successfully removed your precise chroot.
Just to be sure you can run: `sudo edit-chroot -all`
It should come back with something like -
```
chronos@localhost ~ $ sudo edit-chroot -all
No chroots found in /mnt/stateful_partition/crouton/chroots
```

*Hope this helps,*
-**DennisL**
