### ISSUE TITLE
How to Implement OAuth2 server / provider using Hapi?

### ISSUE THREAD

**Issue by mayankkumar0072** [dnschneid/crouton#2931]
I tried, Hapi OAuth2orize is not working properly.
Getting Plugin registration error.

I need to implement following end points in hapijs.

exports.endpoints = [
    {method: 'GET', path: '/',  config:RequestCtrl.index},
    {method: 'GET', path: '/login', config: RequestCtrl.loginForm},
    {method: 'POST', path: '/login',  config:RequestCtrl.login},
    {method: 'GET', path: '/api/userinfo',  config:RequestCtrl.userDetails},
    {method: 'GET', path: '/dialog/authorize', config:{auth:false,handler: AuthorizeCtrl.authorize}},
    {method: 'POST', path:'/dialog/authorize/decision', handler: AuthorizeCtrl.decision},
    {method: 'POST', path:'/oauth/token', handler: AuthorizeCtrl.token}
];

Want to use JWT2 Tokens.
A sample code will be appreciated. 
Thanks,

**Comment by octopusnz** [comment]
@mayankkumar0072 You may have already resolved this but I feel this is not related to crouton?
Might be worth updating/closing this in that case.

**Comment by dnschneid** [comment]
#262
