### ISSUE TITLE
CROUTON : URL error in the script? 

### ISSUE THREAD

**Issue by SynthSy01** [dnschneid/crouton#2932]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Hello 

There might be an error in the script. More specifically, it seems the URL has disappeared. 
This would explain why many Chromebook users (including me) get disconnected when they attempt to establish a connexion to Linux via CROUTON. 

The potentially mistake appears as following : 
"https://github.com/dnschneid/crouton/raw/releases/ error 404" 
"https://github.com/dnschneid/crouton/raw/releases/$INSTALLER"

Many thanks

**Comment by DennisLfromGA** [comment]
@SynthSy01,

Are you getting an error when running `sudo edit-chroot -all` ?

It looks like that is from [croutonversion #L21](https://github.com/dnschneid/crouton/blob/master/chroot-bin/croutonversion#L21) & [#106](https://github.com/dnschneid/crouton/blob/master/chroot-bin/croutonversion#L106) however the command works fine for me.

> This would explain why many Chromebook users (including me) get disconnected when they attempt to establish a connexion to Linux via CROUTON.

What do you mean by *'disconnected'*  when attempting to establish a connection?
Are you not able to open your desktop target, please explain.

-**DennisL**
