### ISSUE TITLE
No chroots found

### ISSUE THREAD

**Issue by Jimzyboi** [dnschneid/crouton#2935]
chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={493FA09F-94EA-B829-46E0-48B12FD7264D}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={493FA09F-94EA-B829-46E0-48B12FD7264D}
CHROMEOS_RELEASE_BOARD=swanky-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=85
CHROMEOS_RELEASE_BUILDER_PATH=swanky-release/R54-8743.85.0
CHROMEOS_RELEASE_BUILD_NUMBER=8743
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=54
CHROMEOS_RELEASE_DESCRIPTION=8743.85.0 (Official Build) stable-channel swanky 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=8743.85.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=8743.85.0

Hi guys,

I've started having issues entering xfce and I'm not entirely sure why. All I know is that everything I've tried used to work but no longer does. I've pasted everything that I've tried below but I'm repeatedly having the same problem. I'm hoping that there's a simple fix but I have no idea what it could be, could you please help?

Thanks,
James

chronos@localhost / $ sudo startxfce4 
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ sudo startxfce4 -c /media/removable/"SD Card"/chroots
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ sudo startxfce4
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ sudo startxfce4
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ sudo startxfce4 -c /media/removable/"SD Card"/chroots
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n trusty
Downloading latest crouton installer...
######################################################################## 100.0%
/media/removable/SD Card/chroots not found.
/usr/local/chroots/trusty does not exist; cannot update.
Valid chroots:
chronos@localhost / $ sudo startxfce4
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ sudo startxfce4
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ startxfce4
enter-chroot must be run as root.
chronos@localhost / $ sudo enter-chroot xfce
No chroots found in /media/removable/SD Card/chroots
chronos@localhost / $ sudo edit-chroot -b trusty
/media/removable/SD Card/chroots/trusty not found.
chronos@localhost / $ sudo enter-chroot -n trusty
/media/removable/SD Card/chroots/trusty not found.
chronos@localhost / $ croutonversion -u -d -c

**Comment by DennisLfromGA** [comment]
@Jimzyboi,

You should see `bin/` & `chroots/` folders when you enter:

`ls -l "/media/removable/SD Card"`

If your external media is truly at `/media/removable/SD Card/` then try this:

`cd "/media/removable/SD Card/"`
`sudo ./bin/startxfce4 -n trusty`

If that doesn't work, after reseating the media again, enter this to see what the mountpoint is named:

`ls -l /media/removable/`

Then adjust the path in your command with the correct mountpoint.

*Hope this helps,*
-**DennisL**

**Comment by Jimzyboi** [comment]
@DennisLfromGA 

Thanks Dennis, I've just tried everything you've mentioned but still haven't got anywhere. I've pasted the outputs below. I was personally worried that my SD Card had been corrupted however I got into xfce around an hour ago using just sudo startxfce4. Once I entered it worked for around 10 minutes and then crashed and since then this issue has started again. 

crosh> shell
chronos@localhost / $ ls -l /media/removable
total 0
drwxrwx--- 2 root chronos 40 Dec  7 17:52 SD Card
chronos@localhost / $ ls -l "/media/removable/SD Card"
total 0
chronos@localhost / $ cd "/media/removable/SD Card/"
chronos@localhost /media/removable/SD Card $ sudo ./bin/startxfce4 -n trusty
sudo: ./bin/startxfce4: command not found
chronos@localhost /media/removable/SD Card $

**Comment by DennisLfromGA** [comment]
@Jimzyboi,

Unfortunately, it looks like there are no chroots on the SD Card.
Does anything show up in the CrOS File app at all?

-**DennisL**

**Comment by Jimzyboi** [comment]
@DennisLfromGA 

Hi Dennis, Thanks for all your help. I've just managed to enter the chroot again and therefore I believe the problem is with my SD Card and not crouton.

**Comment by DennisLfromGA** [comment]
@Jimzyboi,

Okay, good to know.

Please keep us informed and if you find it's not a crouton issue please close this issue.

*Thanx,*
-**DennisL**
