### ISSUE TITLE
Freshly installed precise crouton issues  (black screen | no screens found | server terminated )

### ISSUE THREAD

**Issue by Spirex56** [dnschneid/crouton#2937]
```
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 53.2.49 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Wed Nov 9 04:50:28 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/precise...```

i just installed Crouton but then i had an issue idenntical to the one here : https://github.com/dnschneid/crouton/issues/2599 
but my crouton is XFCE not Unity , i tried following the steps in the reply to solve it but had no luck 
also am using cloudready's version of chromium 


#### If known, describe the steps to reproduce the issue:

**Comment by Spirex56** [comment]
Also am a complete noob so if you know a fix , it would be lovely if you broke it down into newbie steps

**Comment by aleifuu** [comment]
Hi there, What ChromeOS version are you on ?

what `sudo startxfce4` spits out ?

**Comment by Spirex56** [comment]
Version 53.0.2785.148 (64-bit)
Platform 53.2.49 (Developer Build - neverware) developer-build chromeover64
Check for and apply updates

and sudo startxfce4 gives this : 
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.14+ #1 SMP Wed Nov 9 04:50:28 UTC 2016 x86_64
Kernel command line: BOOT_IMAGE=/syslinux/vmlinuz.A init=/sbin/init boot=local rootwait ro noresume noswap loglevel=3 quiet noinitrd console= i915.modeset=1 cros_efi cros_debug root=PARTUUID=26C36D83-0395-1D4D-A5FC-A9CE5F19FEBB
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Thu Dec  8 03:20:20 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.   




@aleifuu thanks in advance for your quick reply

**Comment by Spirex56** [comment]
@DennisLfromGA it would be lovely if you could join in and help :)

**Comment by aleifuu** [comment]
Hmm I was having black screen issue myself with standard crouton installation ( ie xfce ) then I choose to build another xfce but with trusty `-t xfce -r trusty` on the backend and it now works

Reading from your output, it seems a different black screen issue than mine though. mine was something to do with unable to make connection to server and some dbus problem.

Try install xfce with trusty build on the back. see how it goes

**Comment by Spirex56** [comment]
@aleifuu so should i delete iit using : 
    `cd /usr/local/chroots && sudo delete-chroot -y * && rm -rf /usr/local/bin
`
and then reinstall it using trusty's build , could u link me to tutorial or so ? i kinda dont get ho to install Trusty

**Comment by Spirex56** [comment]
wait should i `sudo sh ~/Downloads/crouton -t xfce -r trusty` ? i feel like an idiot

**Comment by Spirex56** [comment]
so i unistalled precise and installed trust using  `sudo sh ~/Downloads/crouton -t xfce -r trusty `

but now i get this when i startxfc

`chronos@localhost /usr/local/chroots $  sudo startxfce4
Password: 
Sorry, try again.
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.14+ #1 SMP Wed Nov 9 04:50:28 UTC 2016 x86_64
Kernel command line: BOOT_IMAGE=/syslinux/vmlinuz.A init=/sbin/init boot=local rootwait ro noresume noswap loglevel=3 quiet noinitrd console= i915.modeset=1 cros_efi cros_debug root=PARTUUID=26C36D83-0395-1D4D-A5FC-A9CE5F19FEBB
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Thu Dec  8 05:22:29 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...`

**Comment by aleifuu** [comment]
hey @Spirex56 , nice jobs reinstall using trusty release. but we seem to be getting same issue unable connect to X-server 

You may want to do this `sudo crouton -t xiwi -u -n trusty`

This will add `xiwi` as alternative to starting in X-server, so hopefully that can by pass the X-server issue for now 

> 
t's also highly recommended that you install the crouton extension, which, when combined with the extension or xiwi targets, provides much improved integration with Chromium OS.

From crouton README page. Well make sure you have enable crouton integration app beforehand

**Comment by Spirex56** [comment]
@aleifuu sorry for inconvenience , i tried  `sudo crouton -t xiwi -u -n trusty` it gave me `sudo: crouton: command not found` i thought maybe i needed to enter chroot first , i did that but gave me same output

**Comment by aleifuu** [comment]
`sudo sh ~/Downloads/crouton` instead of `sudo crouton`

I meant, just run the crouton script as per usual but adding 'xiwi' as its target and `-u` flag is to indicate update instead of fresh install

Have fun

**Comment by Spirex56** [comment]
`sudo sh ~/Downloads/crouton -t xiwi -u -n trusty` is this what you meant ? if not well i think its kinda late i already typed it in . 

Thanks Alot @aleifuu

**Comment by Spirex56** [comment]
@aleifuu  it worked all the thanks to you :) 👍

**Comment by DennisLfromGA** [comment]
@Spirex56,

I don't know if the already merged PR: ['Fix card# selection once and for all #2823'](https://github.com/dnschneid/crouton/pull/2823) will apply to your neverware chroot. It probably depends on what hardware it's running on to some extent.

> (EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.

If you get ambitious you could launch it again using the 'xorg' xmethod and show us the output of the log file above. You can launch it like this: `sudo startxfce4 -X xorg -n trusty`

However, if you are happy with using 'xiwi' then just use it to avoid any hassle. It's what I use mostly.

*Hope this helps,*
-**DennisL**

**Comment by Spirex56** [comment]
@DennisLfromGA  well i dont really know the difference between the xorg and the xiwi , but i just tried doing what you said and launched it using `sudo startxfce4 -X xorg -n trusty` but i got this :  `/mnt/stateful_partition/crouton/chroots/trusty does not contain XMETHOD 'xorg'`   

so i dont really know  , if youd explain the difference between xorg and xiwi , because for now everything seems fine , so am gonna probably stick with Xiwi , but id still like to know the difference

**Comment by DennisLfromGA** [comment]
@Spirex56,

> so i dont really know , if youd explain the difference between xorg and xiwi , because for now everything seems fine , so am gonna probably stick with Xiwi , but id still like to know the difference

No problem, stick with 'xiwi' if you're happy with it.

As far as the difference between the two I'm afraid I am no authority on that but here's what the description for each xmethod says about it -

- [xorg](https://github.com/dnschneid/crouton/blob/master/targets/xorg) - 'X.Org X11 backend. Enables GPU acceleration on supported platforms.'
- [xiwi](https://github.com/dnschneid/crouton/blob/master/targets/xiwi) - 'X.org X11 backend running unaccelerated in a Chromium OS window.'
> sudo sh ~/Downloads/crouton -t xiwi -u -n trusty is this what you meant ? if not well i think its kinda late i already typed it in .

You can take a look at the links above to see exactly what the difference is, what packaes they install, etc. if that would help.

I thought by the above update command and the original issue was that you had previously been using 'xorg' and were adding 'xiwi'.

*Hope this helps,*
-**DennisL**

**Comment by Spirex56** [comment]
@DennisLfromGA am good at c++ and javascribt but i seriously understand nothing from those links but i think am good for now , you mentioned something about GPU acceleration which i might need in the future , but for now its all good and i kinda like the way that its open in a chromium os window ! so am pretty good , ill reopen this thread if i ever have any issues or think of going xorg 

all thanks to @aleifuu  and @DennisLfromGA    xoxo

**Comment by aleifuu** [comment]
Hi @Spirex56 , Wow nice. I'm glad I could be of help ! 

Hey you know what,  I just learned from @DennisLfromGA that this was happening on your neverware. In fact, I just learned what neverware/cloudready is. What a great platform ! I'm gonna 'revive' my old laptops with these tech

@DennisLfromGA : I don't think this black screen issue not only affecting those with neverware chroots, I had a fine smooth xfce/precise installation few months back when I try crouton for 1st time then ( on the very same chromebook ). Then after update to chrome56, I am having this black issue 

Only recently I learned about `xiwi` by-pass trick too and luckily it works

**Comment by Spirex56** [comment]
@aleifuu yeah cloud ready is pretty useful , i didnt really use it to revive my laptop , its pretty decent but i was sick of windows updates so i was gonna install linux , then i came across crouton and chrome os , so i thought i would install cloud ready and when i need something that is not web based il just run crouton , almost everything is web based , we even have office and skype for web !

**Comment by Ders2212** [comment]
@DennisLfromGA 

I am having having the no screens found error as well have tried everything to get it to work on the multiple forums where this is brought up but still have no luck. Could you please help me? 

Error Message: Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:34:05 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=5ba313cf-1e37-7740-a314-e067d126a92e/PARTNROFF=1 hashtree=PARTUUID=5ba313cf-1e37-7740-a314-e067d126a92e/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=bc4b56db04ab647e24cc83c4e9c1d3ab23befe07 salt=f0f132479996b812e136d7a405b0692f126d03facd2e995f2e26b59818376e1e" noinitrd vt.global_cursor_default=0 kern_guid=5ba313cf-1e37-7740-a314-e067d126a92e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Mar  9 09:48:39 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by DennisLfromGA** [comment]
@Ders2212, Multiple posts of the same issue won't help anyone, please track this issue [here](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting).
