### ISSUE TITLE
Cloudready Chrome OS on a Dell 11z - Asking for password when installing Crouton

### ISSUE THREAD

**Issue by mrlee727** [dnschneid/crouton#2938]
Hi -

I'm new to this site so forgive me if i'm not formatting this issue correctly.

I'm running Cloudready Chrome OS on a Dell 11z that was previously running WIndows 7. I've followed the steps for installing Crouton and when I run the command: sudo _sh ~/Downloads/crouton -t unity_ and hit enter its asking for a password.

I've tried the steps outlined on other issue threads with no success and I'm not sure if the issue is with the Cloudready install vs the OE installs on Chromebooks.

Any help is appreciated.

**Comment by Spirex56** [comment]
its the sudo password , by default its chrome no caps no nothing

**Comment by mrlee727** [comment]
Thanks! That worked! I was able to get through the install but ran into another issue. 

In the shell I ran the _sudo startunity_ command to load Ubuntu and encountered these errors:

Loading extension GLX
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Any ideas?

**Comment by DennisLfromGA** [comment]
@mrlee727,

You may be running into the same issue that @Spirex56 did here: https://github.com/dnschneid/crouton/issues/2937 - with his neverware installation.
 
So you can probably apply the same solution also: install the 'trusty' release and use xmethod 'xiwi'.

*Hope this helps,*
-**DennisL**

**Comment by Spirex56** [comment]
@mrlee727 if you want to chat somewhere else without the comment of hassle to walk you through what i did exactly i will be pleased , just remember i am not a pro or anything i just followed the steps people told me , but i had the same issue that you had and wished someone would help me , and they did ! so am willing to give back and help you , follow the steps in my thread #2937  if you couldnt just tell me and we can figure out something

**Comment by mrlee727** [comment]
Hi @Spirex56 

Thanks for your help. I was out of pocket last few days so I'm now looking at this. I started looking at the the install logs in /var/log/ folders to see if something obvious sticks out with the GLX files which seems to be the root cause for the system no loading. If I can't determine cause I nay either re-install over or try the option you guys sugested. Just for my curiosity are there any pros and cons with installing the 'trusty' release and using xmethod 'xiwi'? I'm not familiar with those and I've installed Ubuntu over a dozen times on various PCs so I like the standard unity setup.

Thanks

**Comment by Spirex56** [comment]
@mrlee727 I dont really know the cause of your issue as am no expert . But answering your curiosity about trusty , according to one of @DennisLfromGA comments , precise is old and out dated and full of bugs , he recommended us to Use trusty as its updated and has less bugs , So i would recommend installing it on trusty 

> Your chroot is running the precise release which no longer works well on a lot of devices.
And its pretty unstable 
With so many issues it's hard to know where to start diagnosing errors, I would suggest installing a new chroot using the 'trusty' or 'xenial' release, they are newer and have fewer problems.

Sorry I couldn't be more help,
-DennisL,

 now about the xiwi method am not an expert either but this is what @DennisLfromGA said 

> As far as the difference between the two I'm afraid I am no authority on that but here's what the description for each xmethod says about it -

xorg - 'X.Org X11 backend. Enables GPU acceleration on supported platforms.'
xiwi - 'X.org X11 backend running unaccelerated in a Chromium OS window.' 



now to your last point you said you'd like the unity setup , well precise/trusty are chroot types so you can still install unity with the trusty chroot , but it has been mentioned that unity is heavy and slower than xfce , but its totally your choice ! 

I know i am not of much help , but hopefully i answered few of your questions !

**Comment by DennisLfromGA** [comment]
@mrlee727, 

'`unity'` or the `'unity-desktop'` should be fine, it's up to you.

'crouton' has plain vanilla desktops and full desktops for a lot of targets.
You can get an idea of the targets and their sizes below -
```
e17 - Installs the enlightenment desktop environment. (Approx. 50MB)
gnome - Installs the GNOME desktop environment. (Approx. 400MB)
gnome-desktop - Installs GNOME along with common applications. (Approx. 1100MB)
kde - Installs a minimal KDE desktop environment. (Approx. 600MB)
kde-desktop - Installs KDE along with common applications. (Approx. 1000MB)
lxde - Installs the LXDE desktop environment. (Approx. 200MB)
lxde-desktop - Installs LXDE along with common applications. (Approx. 800MB)
unity - Installs the Unity desktop environment. (Approx. 700MB)
unity-desktop - Installs Unity along with common applications. (Approx. 1100MB)
xfce - Installs the Xfce desktop environment. (Approx. 250MB)
xfce-desktop - Installs Xfce along with common applications. (Approx. 1200MB)
```

Also, here's a wiki page that one of the crouton developers wrote about ['3D Hardware acceleration'](https://github.com/dnschneid/crouton/wiki/3D-Hardware-acceleration)

*Hope this helps,*
-**DennisL**

**Comment by mrlee727** [comment]
@DennisLfromGA -Thanks you've been a LOT of help and I appreciate the feedback. I'll give these a try and update asap with results.
