### ISSUE TITLE
When will xenial lose its '*' status on crouton -r list?

### ISSUE THREAD

**Issue by jvschiavo** [dnschneid/crouton#2939]
I mean, when will it be fully supported? I'm waiting since the xenial release for this, 16.04.1 has already been released but xenial is still unsupported on the list. I was avoiding it because of this, cause I want stability, but I'm very excited to use the new LTS soon.
Do you have a schedule about when it will be stable enough?

**Comment by DennisLfromGA** [comment]
@jvschiavo,

The devs are still trying to work out some issues with getting it to work on all platforms, not a simple task.
It is their intent to make 'xenial' the default release *soon'ish* though, see: Set default release to xenial #2833

*Hope this helps,*
-**DennisL**
