### ISSUE TITLE
Facing issue in # based routing in durandal

### ISSUE THREAD

**Issue by siddhartham-1989** [dnschneid/crouton#2940]
Hi Team,

We are working with single page application in which we are using Durandal router for routing as shown below,

Parent level routing:-

router.makeRelative({ moduleId: 'viewmodels' }) 
                .map([
                    { route: '', moduleId: 'login', title: 'Login', nav: true },
                   
                    { route: 'Product*details', moduleId: 'Product/product', title: 'Product', nav: true, hash:              

                             '#product'},//Map the routes

                ]).buildNavigationModel();

Child level routing:-

            routeConfigs = [
                { route: ['', 'child1'], moduleId: 'child1', title: 'Home', type: 'detailed', nav: true },
                { route: 'child2', moduleId: 'Product/child2', title: 'Child2List', type: 'detailed', nav:                   

       true, hash: '#product/child2' },
            ],
        childRouter = router.createChildRouter()
                        .makeRelative({
                            moduleId: 'viewmodels/',
                            fromParent: true
                        }).map(routeConfigs).buildNavigationModel();

and once user logged in successfully we navigate the user to respective product page like,

router.navigate('#product') which works properly and shows the url in browser like http://localhost:12345/#product(which is 

route name).

Now we are White labeling our application and trying to modify our route which is visible in the browser url for e.g.: we want  

(changing Productname to Product123 or something else), for which we are trying to create generic route table without much 

changes in our code, so that in results we will be able to see browser url like  http://localhost:12345/#product123.

So is there any way to solve this so that we can achieve the same without changing our internal routing.

Please Advise.

Thanks in advance.

**Comment by DennisLfromGA** [comment]
Is this related to crouton ???

**Comment by dnschneid** [comment]
nooooooooooo
#262

**Comment by siddhartham-1989** [comment]
Thanks for reply, this is irrelevant to above mentioned query .
