### ISSUE TITLE
HELP PLS~

### ISSUE THREAD

**Issue by Espe0** [dnschneid/crouton#2941]
chronos@localhost / $ sudo sh ~/Downloads/crouton -r saucy -t kde
WARNING: saucy is an unsupported release.
You will likely run into issues, but things may work with some effort.
Press Ctrl-C to abort; installation will continue in 5 seconds.
Installing saucy-amd64 chroot to /usr/local/chroots/saucy
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2016-12-09 15:58:40 URL:http://ftp.ticklers.org/debian/pool/main/d/debootstrap/ [6662/6662] -> "-" [1]
Downloading debootstrap version 1.0.87...
Cannot write to '-' (Broken pipe).
Failed to download debootstrap.

**Comment by DennisLfromGA** [comment]
@Espe0,

Try again (and again ), it may just be a transient network error.

*Hope this helps,*
-**DennisL**

**Comment by Espe0** [comment]
@DennisLfromGA It is still not working. -_- with same error

**Comment by DennisLfromGA** [comment]
@Espe0 ,

I would try a different release other than 'saucy' then, perhpas 'trusty' or 'xenial'.

*Hope this helps,*
-**DennisL**
