### ISSUE TITLE
speed up without scan

### ISSUE THREAD

**Issue by JunHanStudy** [dnschneid/crouton#2942]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
I have a three dimensional matrix, for example, 10000 * 5 * 5, I want to calculate the determinant of 5 * 5 matrix for each element in first dimension to get 10000 * 1 number. I use scan but it is too slow. Since there is no recurrent in this loop, any suggestion to speed up?  I know numpy can calculate it without scan. But in theano, the input of theano.tensor.nlinalg.Det() must be two dimension, i.e, 5*5, I have to use scan. It is too slow. How can I speed up?

**Comment by DennisLfromGA** [comment]
Your matrix is an element not in crouton's dimension, see https://github.com/dnschneid/crouton/issues/262
