### ISSUE TITLE
Black Screen On XFCE Startup

### ISSUE THREAD

**Issue by ZavaleHD** [dnschneid/crouton#2943]
```
Please paste the output of the following command here: sudo startxfce4
```
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Thu Dec 1 21:55:19 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=597c006a-89d7-bb42-a45d-d1ef9d3cfe03/PARTNROFF=1 hashtree=PARTUUID=597c006a-89d7-bb42-a45d-d1ef9d3cfe03/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=f275e92521c42221b24926cbb06446e01be1ec1b salt=c65bec8bed83c4f775c721df083454cfd30d003306ab86e3af041a6b0c5769ed" noinitrd vt.global_cursor_default=0 kern_guid=597c006a-89d7-bb42-a45d-d1ef9d3cfe03 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.3.log", Time: Sun Dec 11 01:56:50 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.15.0 (Official Build) dev-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Thu Dec 1 21:55:19 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Another instance of croutontriggerd running, waiting...
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root

(xfsettingsd:8942): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
xfdesktop[8936]: starting up

(xfce4-session:8924): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfwm4:8930): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfdesktop:8936): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(polkit-gnome-authentication-agent-1:8940): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:8940): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(migrate:8951): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-settings-helper:8952): xfce4-settings-helper-WARNING **: Failed to get the _NET_NUMBER_OF_DESKTOPS property.
#### Please describe your issue:
Whenever I try to start up xfce on my Acer Chromebook C11, it always ends up with a completely black screen.

**Comment by DennisLfromGA** [comment]
This seems to be pretty much the same as this issue: https://github.com/dnschneid/crouton/issues/2934
Please track it there.
