### ISSUE TITLE
Trouble getting Crouton Ubuntu to work on  Chromebook N22 Lenovo (Braswell)

### ISSUE THREAD

**Issue by Enochwel** [dnschneid/crouton#2944]
I am a total beginner, but am hoping to use my 150$ blackfriday chromebook deal for my computer programing course coming up.  I've not been able to get Ubuntu to work using any of the commands I've found online.  Has anyone done this on an Lenovo N22 Braswell Chromebook and willing to share step by step instructions?

When I try to install it using various commands Ive found online, I either get a blank (black) screen when I shift-ctrl-alt-arrow to Ubuntu screen, or I get nothing, or I get a mere linux command line that does seem to work.

**Comment by DennisLfromGA** [comment]
@Enochwel,

Please show us the output of: `sudo edit-chroot -all`
Then we'll try to figure out what's wrong.

-**DennisL**

**Comment by Enochwel** [comment]
chronos@localhost / $ sudo edit-chroot -all
name: enochwel
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/enochwel...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: lxde,xiwi
host: version 9000.15.0 (Official Build) dev-channel reks 
kernel: Linux localhost 3.18.0-13492-g308c6f5 #1 SMP PREEMPT Thu Dec 1 22:00:14 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/enochwel...
chronos@localhost / $

**Comment by aleifuu** [comment]
maybe try running the script with the flag -X xiwi to output it to xiwi instead the default x11

something like : `sudo sh ~/Downloads/crouton startlxde -X xiwi`

**Comment by Enochwel** [comment]
Ok I did that.  Should I do this one now?
rm -rf /tmp/crouton-installer-cache/crouton

Here is my latest action:
chronos@localhost / $ sudo sh ~/Downloads/crouton startlxde -X xiwi
Downloading latest crouton installer...
######################################################################## 100.0%
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball
etc...

**Comment by aleifuu** [comment]
You tried the command and did it work ?

**Comment by Enochwel** [comment]
I guess my problem is that I don't really know what my problem is.  When I first started doing this I had definite errors on installation etc..., then I had a blank screen on one of my installs.  Anyways, I did a powerwash and did this install after downloading crouton:
sudo sh ~/Downloads/crouton -r trusty -t lxde,xiwi -n enochwel
I've got a command line that seems to work, but I don't know how to get the ubuntu experience from where I am now.  
Just did this:
crosh> shell
chronos@localhost / $ rm -rf /tmp/crouton-installer-cache/crouton
chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/enochwel...
(enochwel)enochwel@localhost:~$ rm -rf /tmp/crouton-installer-cache/crouton
(enochwel)enochwel@localhost:~$ ^C

All of this for now is a stab in the dark.

**Comment by DennisLfromGA** [comment]
@aleifuu,

> maybe try running the script with the flag -X xiwi to output it to xiwi instead the default x11

@Enochwel does not have the 'xorg' xmethod installed so he will be using 'xiwi' by default.

> something like : sudo sh ~/Downloads/crouton startlxde -X xiwi

You're mixing up the installation script (`crouton`) with the start script (`startlxde`), that's not gonna work.

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment]
@Enochwel,

> When I try to install it using various commands Ive found online, I either get a blank (black) screen when I shift-ctrl-alt-arrow to Ubuntu screen, or I get nothing, or I get a mere linux command line that does seem to work.

Have you also installed the ['crouton integration' extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) from the Chrome Webstore, it's required with 'xiwi'.

What happens when you try to start your 'lxde' desktop using: `sudo startlxde` ?
Can you show us the display and any errors that you get please?
Does your 'lxde' desktop launch and you're just having trouble switching into and out of CrOS?

We need some more details....

*Hope this helps,*
-**DennisL**

**Comment by Enochwel** [comment]
Ok so it actually does work, mostly.  For some reason my crouton extention from webstore doesnt connect, so I  cant switch between OS's, even when using alt-ctrl-shift-arrow.

chronos@localhost / $ sudo startlxde
Entering /mnt/stateful_partition/crouton/chroots/enochwel...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13492-g308c6f5 #1 SMP PREEMPT Thu Dec 1 22:00:14 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=f1751b30-f733-f94d-84a8-750cc70265d5/PARTNROFF=1 hashtree=PARTUUID=f1751b30-f733-f94d-84a8-750cc70265d5/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=f347a9d09058c7eedfd7c1f3107694b30987ae12 salt=8c6ad1ba734bd2e21866665e37978ee7ac9959a1cb3cb64b278f97fb8936b44c" noinitrd vt.global_cursor_default=0 kern_guid=f1751b30-f733-f94d-84a8-750cc70265d5 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Dec 12 11:25:56 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: lxde,xiwi
host: version 9000.15.0 (Official Build) dev-channel reks 
kernel: Linux localhost 3.18.0-13492-g308c6f5 #1 SMP PREEMPT Thu Dec 1 22:00:14 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Agent pid 4536
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE
** Message: main.vala:131: log directory: /home/enochwel/.cache/lxsession/LXDE
** Message: main.vala:132: log path: /home/enochwel/.cache/lxsession/LXDE/run.log
Error: target STRING not available
Terminated
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/enochwel as another instance is using it.
chronos@localhost / $ ^C

**Comment by Enochwel** [comment]
I'm going to try removing the extension and re-downloading it.

**Comment by Enochwel** [comment]
Ok I just did that and same issue.  Extension is not connecting:

chronos@localhost / $ sudo startlxde
Entering /mnt/stateful_partition/crouton/chroots/enochwel...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13492-g308c6f5 #1 SMP PREEMPT Thu Dec 1 22:00:14 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=f1751b30-f733-f94d-84a8-750cc70265d5/PARTNROFF=1 hashtree=PARTUUID=f1751b30-f733-f94d-84a8-750cc70265d5/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=f347a9d09058c7eedfd7c1f3107694b30987ae12 salt=8c6ad1ba734bd2e21866665e37978ee7ac9959a1cb3cb64b278f97fb8936b44c" noinitrd vt.global_cursor_default=0 kern_guid=f1751b30-f733-f94d-84a8-750cc70265d5 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Dec 12 11:45:20 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: lxde,xiwi
host: version 9000.15.0 (Official Build) dev-channel reks 
kernel: Linux localhost 3.18.0-13492-g308c6f5 #1 SMP PREEMPT Thu Dec 1 22:00:14 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Agent pid 10895
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE
** Message: main.vala:131: log directory: /home/enochwel/.cache/lxsession/LXDE
** Message: main.vala:132: log path: /home/enochwel/.cache/lxsession/LXDE/run.log
Error: target STRING not available
Terminated
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/enochwel as another instance is using it.
chronos@localhost / $ ^C

**Comment by DennisLfromGA** [comment]
@Enochwel,

> Connected to extension, launched crouton in a window.

It looks like it launched from the above but then terminated right away - possibly.

> Not unmounting /mnt/stateful_partition/crouton/chroots/enochwel as another instance is using it.

Maybe you tried to launch it more that once or did something else but it's not unmounting for some reason.
I would reboot and try again.

*Hope this helps,*
-**DennisL**

**Comment by Enochwel** [comment]
Still the same thing after rebooting:
kernel: Linux localhost 3.18.0-13492-g308c6f5 #1 SMP PREEMPT Thu Dec 1 22:00:14 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Connected to extension, launched crouton in a window.
Agent pid 4950
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE
** Message: main.vala:131: log directory: /home/enochwel/.cache/lxsession/LXDE
** Message: main.vala:132: log path: /home/enochwel/.cache/lxsession/LXDE/run.log
Error: target STRING not available
Error: target STRING not available
Terminated
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/enochwel...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/enochwel...
chronos@localhost / $

**Comment by Enochwel** [comment]
oops it said connected after several errors.

**Comment by Enochwel** [comment]
Great!  All is well!  Thanks!  Now on to installing IDE's for class.
