### ISSUE TITLE
crahes computer

### ISSUE THREAD

**Issue by loltroll12** [dnschneid/crouton#2950]
the code that it said at end was 
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[intel_init_bufmgr:1069] Error initializing buffer manager.
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 8872.70.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-13434-gc3678fb #1 SMP PREEMPT Wed Dec 7 23:29:16 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

i dont know whats causing it but it crashes my computer when i try to start the unity version of it

:

**Comment by octopusnz** [comment]
@loltroll12 Not too sure if you have solved this already - but have a look at some wisdom here:

https://github.com/dnschneid/crouton/issues/2978#issuecomment-269849365
