### ISSUE TITLE
Am I using .Map() wrongly? (Javascript)

### ISSUE THREAD

**Issue by emilyheng** [dnschneid/crouton#2951]
```
function titleCase(str) {
 str= str.toLowerCase().split("");
 var newArr= str.map( function(i,j){
   if ( j===0 ){
  return i.toUpperCase();
}
  else if (str[j--]===" "){
    return i.toUpperCase();
  }
    return i; 
});

return newArr.join("");
}
  
 

console.log(titleCase("i'm a little tea pot"));
```

#### Please describe your issue:
I want to capitalise the first letter of each word in a string. However, the output that I got for my code below is "I'm a little tea pot". I tried to find explanations on the internet on how to use the index argument for the callback function in .map(), but I could not find any. Am I using it wrongly? 

Any help is appreciated!

**Comment by DennisLfromGA** [comment]
Sorry but this is a crouton site that deals with crouton issues.
I think you might find better help if you look for sites that provide javascript support.
