### ISSUE TITLE
Crouton extension websocket dies

### ISSUE THREAD

**Issue by w0de** [dnschneid/crouton#2952]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: syo
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/syo...
crouton: version 1-20161129162558~master:5f2f11f9
release: jessie
architecture: amd64
xmethod: xiwi
targets: core,keyboard,lxde,xiwi,audio,gtk-extra,extension
host: version 9000.26.0 (Official Build) dev-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Sun Dec 11 21:56:49 PST 2016 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/syo as another instance is using it.

#### Please describe your issue:

Crouton extension drop connection after about 5 minutes of use. The crouton window functions, and the chroot remains mounted. Really the only annoyance is the loss of a the shared clipboard. 

Output:

> chronos@localhost / $ sudo startlxde -n syo
> ...
> /usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
> crouton: version 1-20161129162558~master:5f2f11f9
> release: jessie
> architecture: amd64
> xmethod: xiwi
> targets: core,keyboard,lxde,xiwi,audio,gtk-extra,extension
> host: version 9000.26.0 (Official Build) dev-channel candy 
> kernel: Linux localhost 3.10.18 #1 SMP Sun Dec 11 21:56:49 PST 2016 x86_64 GNU/Linux
> freon: yes
> Error: not connected.
> Cannot connect to extension, retrying...
> Error: not connected.
> Cannot connect to extension, retrying...
> Connected to extension, launched crouton in a window.
> ** Message: main.vala:99: Session is LXDE
> ** Message: main.vala: 100: DE is LXDE
> ** Message: main.vala:131: log directory: /home/sysooo/.cache/lxsession/LXDE
> ** Message: main.vala:132: log path: /home/sysooo/.cache/lxsession/LXDE/run.log
> Error: target STRING not available
> croutonwebsocket error: 
>
>

/tmp/Xorg.crouton.1.log:

> chronos@localhost / $ grep "(EE)" /tmp/Xorg.crouton.1.log
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> [ 38631.336] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
> [ 38631.341] (EE) Failed to load module "kbd" (module does not exist, 0)
> [ 38631.353] (EE) AIGLX: reverting to software rendering
> [ 38631.446] (EE) <default pointer>: Cannot find which device to use.
> [ 38631.446] (EE) xf86OpenSerial: No Device specified.
> [ 38631.446] (EE) xf86OpenSerial: No Device specified.
> [ 38631.447] (EE) Failed to load module "kbd" (module does not exist, 0)
> [ 38631.447] (EE) No input driver matching `kbd'
> [ 38631.451] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
> [ 46882.037] (EE) Server terminated successfully (0). Closing log file.

#### If known, describe the steps to reproduce the issue:

No idea. Not noticed any correlations. Always occurs within a few minutes, but not programmatically.

**Comment by DennisLfromGA** [comment]
@w0de,

Interesting, it appears to be having problems with `/dev/dri/card0` and a few other things.
I know one of those issues had been fixed here: **Fix card# selection once and for all #2823**
Maybe this is different; the (EE) lines are helpful but could you show us the entire log please?

-**DennisL**
