### ISSUE TITLE
shell isnt working on my crouton crosh

### ISSUE THREAD

**Issue by leiuare** [dnschneid/crouton#2954]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by leiuare** [comment]
i was just gonna have tuxracer and change my chromebook to linux but when i type in shell it doesnt work. (i have the extensions, os verification off and im on the dev channel)

**Comment by DennisLfromGA** [comment]
You need to be in ['Developer mode'](https://www.chromium.org/chromium-os/chromiumos-design-docs/developer-mode), the ['channel'](https://support.google.com/chromebook/answer/1086915?hl=en) you're on doesn't matter.
