### ISSUE TITLE
Fatal error, cannot enter croot

### ISSUE THREAD

**Issue by babswatch** [dnschneid/crouton#2960]
```
No output from: sudo edit-chroot -all 
or:
sudo cat /ect/lsb-release
 
I'm completely new to linux but I installed crouton on my lenovo 100S chromebook w/ intel to get some programming homework done over break. I had it working for a while but when I was installing Steam, the battery of my laptop died. 
I currently get the following output from sudo startxfce4:


Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Dec 7 23:27:37 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=0b7ddecf-5f27-a54c-a098-b8ae6dc8397e/PARTNROFF=1 hashtree=PARTUUID=0b7ddecf-5f27-a54c-a098-b8ae6dc8397e/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=e05ff82b27b1ced19a0173d7925876b476065610 salt=b87d8c79cf761fd885b0aa627fbaa346b7548151591e71792c71356e4c672acd" noinitrd vt.global_cursor_default=0 kern_guid=0b7ddecf-5f27-a54c-a098-b8ae6dc8397e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec 20 00:30:56 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
^C/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: unexpected signal 2
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Any advice would be appreciated! (:

**Comment by DennisLfromGA** [comment]
@babswatch,

> No output from: sudo edit-chroot -all 
or:
sudo cat /ect/lsb-release

You should be able to get the 'croutonversion' output from: `sudo edit-chroot -all`
You have a type in 'sudo cat /**ect**/lsb-release', it should be `sudo cat /etc/lsb-release`

Without knowing more details, I recommend you follow the wiki guide here: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**

**Comment by babswatch** [comment]
Here's the output from 'sudo cat /etc/lsb-release': 

CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C13F1877-80F6-0531-A06A-FA478898AA73}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C13F1877-80F6-0531-A06A-FA478898AA73}
CHROMEOS_RELEASE_BOARD=orco-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=70
CHROMEOS_RELEASE_BUILDER_PATH=orco-release/R55-8872.70.0
CHROMEOS_RELEASE_BUILD_NUMBER=8872
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=55
CHROMEOS_RELEASE_DESCRIPTION=8872.70.0 (Official Build) stable-channel orco 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=8872.70.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=8872.70.0

I followed the instructions and downloaded a new crouton installer but:
I still get this output from 'sudo edit-croot -all' 
sudo: edit-croot: command not found

I also tried to use 'sudo ls /usr/local/chroots' which outputs:
ls: cannot access usr/local/croots: No such file or directory

Thanks so much for the help!

**Comment by DennisLfromGA** [comment]
@babswatch,

If you are sure your chroot(s) are still installed then you may need to restore your host-bin scripts.
You can do that using: `sudo sh ~/Downloads/crouton -b`

*Hope this helps,*
-**DennisL**

**Comment by babswatch** [comment]
@DennisLfromGA 

The command ran  but it doesn't seem like anything has changed. I still get the same errors from 
'sudo startxfce4'
'sudo cat /etc/lsb-release'
'sudo edit-croot -all'

**Comment by DennisLfromGA** [comment]
@babswatch,

> The command ran but it doesn't seem like anything has changed. I still get the same errors from
'sudo startxfce4'
'sudo cat /etc/lsb-release'
'sudo edit-croot -all'

Could you please be more explicit?
We need details in order to help you.

-**DennisL**

**Comment by babswatch** [comment]
This was the output from the command:

Downloading latest crouton installer...
######################################################################## 100.0%
Installing startxfce4 into the host...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Done! You can enter the chroot using enter-chroot.

I am going to update Chrome OS right now to see if that fixes anything

**Comment by DennisLfromGA** [comment]
@babswatch,

The above output is *exactly* what you *should* get, all the host-bin files are now installed.

> 'sudo edit-croot -all'

There is a typo in that command, it should be: `sudo edit-chroot -all`

*Hope this helps,*
-**DennisL**

**Comment by babswatch** [comment]
Thanks!

I followed the prompt and used the command 'sudo enter-chroot' and now I have this:

Entering /mnt/stateful_partition/crouton/chroots/precise...
(precise)[my unix username]@localhost:~$

**Comment by DennisLfromGA** [comment]
@babswatch,

*Great*, you're now back into your chroot.
Do you have a question?

-**DennisL**

**Comment by babswatch** [comment]
Yeah how do I get back to the xfce desktop. It is just giving me the prompt: (precise)[my username]@localhost:~$
and 'sudo startxfce4' gives me a prompt for my password but then outputs:
Do not launch startxfce4 as root inside the chroot.

**Comment by DennisLfromGA** [comment]
@babswatch,

Outside the chroot use: `sudo startxfce4`
Inside the chroot you can use: `startxfce4`

You should not launch your desktop inside the chroot as root (using sudo), if you do it will mess up your permissions.

When using `sudo` inside the chroot for doing updates with `apt-get` and the like, at the password prompt enter the password for your username, in your case the password for 'my username'.

*Hope this helps,*
-**DennisL**

**Comment by babswatch** [comment]
It's still giving me the big error message from startxfce4:

/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Dec 7 23:27:37 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=0b7ddecf-5f27-a54c-a098-b8ae6dc8397e/PARTNROFF=1 hashtree=PARTUUID=0b7ddecf-5f27-a54c-a098-b8ae6dc8397e/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=e05ff82b27b1ced19a0173d7925876b476065610 salt=b87d8c79cf761fd885b0aa627fbaa346b7548151591e71792c71356e4c672acd" noinitrd vt.global_cursor_default=0 kern_guid=0b7ddecf-5f27-a54c-a098-b8ae6dc8397e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec 20 15:51:56 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error

**Comment by DennisLfromGA** [comment]
@babswatch,

Please list the output of: `sudo edit-chroot -all`

-**DennisL**

**Comment by babswatch** [comment]
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel orco 
kernel: Linux localhost 3.10.18 #1 SMP Sat Dec 17 11:04:04 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by babswatch** [comment]
If it helps, I wiped the laptop, went through the process of setting up crouton and xfce again and tried to replicate the issue by installing Steam and the same thing happened.

**Comment by DennisLfromGA** [comment]
@babswatch,

I would recommend trying 'xiwi' or using a release newer than precise.

You can add 'xiwi' to your existing chroot using: `sudo sh ~/Downloads/crouton -n precise -t xiwi -u`
You'll also need to install the ['crouton integration' extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) from the Chrome Webstore.

*Hope this helps,*
-**DennisL**

**Comment by babswatch** [comment]
I added xiwi using sudo sh ~/Downloads/crouton -n precise -t xiwi -u
It prompted me to use sudo enter-chroot. From there I attempted to use startxfce4 which gave me the following output:

/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Sat Dec 17 11:04:04 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=d3ec1e33-819b-c24f-90c0-2058d5702b56/PARTNROFF=1 hashtree=PARTUUID=d3ec1e33-819b-c24f-90c0-2058d5702b56/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=e46709b68a1bf0d6078ccf2230a74bb0b79fa70c salt=d5c60dbfa238c6e9d2cd92c2d3a87cc5fc9516088a175fe3f6473cbf52fa5df8" noinitrd vt.global_cursor_default=0 kern_guid=d3ec1e33-819b-c24f-90c0-2058d5702b56 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Dec 21 17:43:38 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 8872.73.0 (Official Build) stable-channel orco 
kernel: Linux localhost 3.10.18 #1 SMP Sat Dec 17 11:04:04 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(EE) Server terminated successfully (0). Closing log file.

**Comment by aidflood** [comment]
what does this mean 
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1

**Comment by aidflood** [comment]
then the screen goes black with smears of i dont even know what it is but there are little colorful smears on it then it just takes me back to the crosh and it says this

**Comment by DennisLfromGA** [comment]
@babswatch,

> It prompted me to use sudo enter-chroot. 

Just use: `sudo startxfce4` from *outside* the chroot.

> Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from http://goo.gl/OVQOEt)

You'll also need to install the ['crouton integration' extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) from the Chrome Webstore.

-**DennisL**

**Comment by JCoderLi** [comment]
Hello, I would just like to state that previously I had problems with a black screen, but after installing xiwi and the chrome extension, it works now!
Thank you!

**Comment by DennisLfromGA** [comment]
@JCoderLi,

Glad to hear you got something working.

Hopefully the blackscreen glitch will be fixed soon.

-**DennisL**

**Comment by aidflood** [comment]
how do install xiwi

**Comment by aidflood** [comment]
ok now its just saying that something is wrong with the dbus

**Comment by aidflood** [comment]
please help

**Comment by DennisLfromGA** [comment]
@aidflood,

> how do install xiwi

I showed the command to install 'xiwi' here: https://github.com/dnschneid/crouton/issues/2960#issuecomment-268642187
If your chroot is not named precise then use the name of your chroot instead.

*Hope this helps,*
-**DennisL**

**Comment by aidflood** [comment]
lxde I think that's what it's called but anyway, lxde works but you can't well download anything on that is that normal?

**Comment by DennisLfromGA** [comment]
@aidflood,

Your questions and responses are a little cryptic to me at least.
What is it you are trying to do and what problems are you having.

Note: *Details are important*, like the output of: `sudo edit-chroot -all`

Also, you seem to have hi-jacked this topic with your own so it might be best to start a new one or chime in on one that fits your dilemma.

*Hope this helps,*
-**DennisL**

**Comment by aidflood** [comment]
i did but it was ignored it was under my other account but forgot what it was and was to lazy to go through the frogot password thing but anyway this is the last question on this one does this mean anything to you 
Loading extension GLX
setversion 1.4 failed: Permission denied
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xiwi
targets: unity,lxde,xiwi,xfce
host: version 8872.73.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:07:06 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by DennisLfromGA** [comment]
@aidflood,

What gave you that display, was it from `sudo startlxde`?
Can you launch your lxde desktop or not?

-**DennisL**

**Comment by aidflood** [comment]
yes

**Comment by aidflood** [comment]
sorry ive been busy

**Comment by aidflood** [comment]
no i think its in unity or something
lxde is working but it keeps asking for admin password when i do stuff

**Comment by aidflood** [comment]
no it was xfce

**Comment by aidflood** [comment]
100% sure that it was xfce

**Comment by DennisLfromGA** [comment]
@aidflood,

I have no clue what desktop you're trying to use or what your issue is and your sentence fragments aren't helping *at all*.

I suggest you *please* start a [new issue](https://github.com/dnschneid/crouton/issues/new) and give us all the details you can.

Let's not hi-jack this thread any longer....

*Hope this helps,*
-**DennisL**

**Comment by Goldshot21** [comment]
@DennisLfromGA  how do i sign in to the account ive already logged in to? When i tried using sudo sh ~/Downloads/crouton -r xenial -t xfce it showed this...
/usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

**Comment by DennisLfromGA** [comment]
@Goldshot21,

Another hi-jacker but I'll be brief.

> how do i sign in to the account ive already logged in to?

You use: `sudo startxfce4 -n xenial`

> When i tried using sudo sh ~/Downloads/crouton -r xenial -t xfce it showed this...  
>> /usr/local/chroots/xenial already has stuff in it!  
> Either delete it, specify a different name (-n), or specify -u to update it.

You use the installation command shown above *once*, then you use the start* script I showed above to launch your desktop.
The only time you would ever use the 'crouton' command again is when you want to add a target and/or update your chroot. An update uses slightly different options similar to: 

`sudo sh ~/Downloads/crouton -n xenial -u`

*Hope this helps,*
-**DennisL**

**Comment by Goldshot21** [comment]
@DennisLfromGA Thank you it worked

**Comment by Goldshot21** [comment]
@DennisLfromGA are there any faster browsers i can use? Sorry im a newbie at this

**Comment by DennisLfromGA** [comment]
@Goldshot21,

> are there any faster browsers i can use?

No only Chrome sorry. :(

Just kidding, https://www.linux.com/news/which-linux-web-browser-right-you

*Hope this helps,*
-**DennisL**
