### ISSUE TITLE
How to invoke keyboard program

### ISSUE THREAD

**Issue by githubgnulinux** [dnschneid/crouton#2961]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

There is a file called keyboard: https://github.com/dnschneid/crouton/blob/master/targets/keyboard

How to apply it please? Can't see/understand any instructions how to use it.

Is it correct to conclude that this program will change the keyboard so that 'search key + up' is equivalent to 'home' key?

#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
@githubgnulinux,

> How to apply it please? Can't see/understand any instructions how to use it.

The `keyboard` file you linked above is a 'target' and can be installed similar to other desktop targets, etc.
To add it to an existing chroot use: `sudo sh ~/Downloads/crouton -t keyboard -u [-n chrootname]`
Substitute the name of your chroot for chrootname in the above example - and don't use the brackets.

> Is it correct to conclude that this program will change the keyboard so that 'search key + up' is equivalent to 'home' key?

No, not according to the `keyboard` file's comment: '...we map Search+arrows to Page Up/Down/Home/End.'
The file shows this assignment:
```
    key <LEFT> { overlay1=<HOME> };
    key <RGHT> { overlay1=<END> };
    key <UP>   { overlay1=<PGUP> };
    key <DOWN> { overlay1=<PGDN> };
```
So the <kbd>SEARCH</kbd> + <kbd><</kbd> keys would map to the <kbd>HOME</kbd> key like in CrOS.

See below:
![cb_search keycombos](https://cloud.githubusercontent.com/assets/3418772/21360984/275f437c-c6b0-11e6-9c96-b5bfa435cb2a.png)

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by trusktr** [comment]
Ah, I was about to post a new issue asking how to press home/end keys in Linux. So I guess just install this target and it should work.

Will it work if I've modified my modifiers? For example, in CrOS I've swapped Search (Super) and Control, and in Linux I also swapped Super (Search) and Control. I guess I'll try it out...
