### ISSUE TITLE
Full Linux Distro Install on External Device: Use for Crouton?

### ISSUE THREAD

**Issue by darethehair** [dnschneid/crouton#2964]
Hypothetical question(s)...

I have sucessfully installed both crouton (Debian Jessie + Cinnamon) *and* a full linux distro (Linux Mint Debian Edition) onto external devices (SD card and USB stick), and with USB booting enabled on my Chromebook I can either start up the crouton chroot (within ChromeOS) or dual-boot to the LMDE install.

It seems to me, without knowing otherwise, that my crouton linux partition is very similar to any other full Linux distro install -- but some of the system directories are not needed (and are therefore empty).  Can crouton be started by pointing a a full distro install partition -- instead of a crouton chroot partition -- and work properly?

Being able to do this would mean many good things:

- Install Linux onto a USB stick and use it *both* for crouton and full Linux operation
- Being able to run (in this case) a full legitimate version of LMDE in crouton without needing to make it one of the crouton 'install' choices (potentially run *any* Linux one desires)

So, what does my LMDE install 'lack' that would be required for it to work under crouton?

**Comment by divx118** [comment]
I think you should read some more about chroots. See for example http://askubuntu.com/questions/162808/what-exactly-is-a-chroot-is-it-similar-to-a-simultaneous-dual-boot and of course https://github.com/dnschneid/crouton#whats-a-chroot 
So, it could be done however not that simple. You would need to copy some crouton chroot scripts to your LMDE and adjust some stuff in enter-chroot. 
I think it will be easier to write your own equivalent to an "enter-chroot" script specific to your LMDE install. That script could be a lot shorter then the one from crouton. That said, you will need linux and chroot knowledge to accomplish this.
