### ISSUE TITLE
Some authorization problem with a fresh install

### ISSUE THREAD

**Issue by anuddawang45** [dnschneid/crouton#2965]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all

name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel clapper
kernel: Linux localhost 3.10.18 #1 SMP Sat Dec 17 11:30:31 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
Hi. I seem to be having some sort of authorization problems with a fresh install of Ubuntu (and powerwashed Chromebook). When I do "sudo startxfce4" the OS *does* start (which it couldn't when I was in beta channel), but there seems to be some persistent errors.

```
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

[further down]

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel clapper
kernel: Linux localhost 3.10.18 #1 SMP Sat Dec 17 11:30:31 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
```

And then I get a whole bunch of "'Unable to locate theme engine in module_path: 'pixmap'" errors. Then I log out from Ubuntu and come back to my Chrome tab and it says

```
xscreensaver: 11:45:01 Errors at startup are usually authorization problems.
But you're not logged in as root (good!) so something else must be wrong.
```

I could ignore it, but the same user authorization problem seems to come up when I further install programs on Ubuntu.

#### If known, describe the steps to reproduce the issue:
1. Put in stable channel; dev mode disabled
2. Powerwash
3. Put in developer mode
4. Download crouton from https://goo.gl/fd3zc
5. Ctrl+Alt+T
6. "shell"
7. "sudo sh ~Downloads/crouton -t xfce"
8. "sudo startxfce4"

**Comment by octopusnz** [comment]
@anuddawang45 Not too sure if you have fixed this already but have a look at some wisdom here:

https://github.com/dnschneid/crouton/issues/2978#issuecomment-269849365
