### ISSUE TITLE
Error When Starting Xfce Linux Session (dbus error)

### ISSUE THREAD

**Issue by AlexObliv2029** [dnschneid/crouton#2970]
```
Please paste the output of the following command here: sudo startxfce4
```Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
EOF in dbus-launch reading address from bus daemon
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found

** (xfce4-session:19058): CRITICAL **: Unable to contact D-Bus session bus: Unknown error

** (xfce4-session:19058): CRITICAL **: Unable to contact D-Bus session bus: //bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon

#### Please describe your issue: I just recently installed crouton, but when attempting to open a Linux session receive the error above. Please help.


#### If known, describe the steps to reproduce the issue: Run xfce on Samsung Chromebook 3

**Comment by DennisLfromGA** [comment]
Please post the output of: `sudo edit-chroot -all`

**Comment by 10BaseTwo** [comment]
Hello, I am running into the same error on an Acer Chromebook 14:

> chronos@localhost / $ sudo edit-chroot -all
> Password: 
> name: precise
> encrypted: yes, locked
> Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Sorry about the output formatting, to me, it displays better (recognizes carriage returns) when using 'insert a quote' instead of 'insert code' I am very new to Linux and Unix and GH, but am very excited to be tinkering around with a Chromebook and Linux. 

Here is what I get for the initial output of the `sudo startxfce4` command. Later on, i see the same messages that Alex posted above.

> chronos@localhost / $ sudo startxfce4
> Enter encryption passphrase for precise: 
> Entering /mnt/stateful_partition/crouton/chroots/precise...
> Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
> WARNING: starting chroot system dbus daemon failed with code 1

**Comment by DennisLfromGA** [comment]
You'll have to enter your password to unlock your chroot before we can see what crouton version you're using.
Another way is to get into your chroot and then show us the output of `croutonversion`.

**Comment by 10BaseTwo** [comment]
Dennis, thank you for the quick reply, and sorry for my ignorance. I hope I'm running this the way you have asked, but I feel like I am still doing something wrong. I did enter my password to run the sudo cmd the first time, then ran it again in a few other directories.

> chronos@localhost /mnt/stateful_partition/crouton/chroots $ sudo croutonversion
> sudo: croutonversion: command not found
> chronos@localhost /mnt/stateful_partition/crouton/chroots $ cd /
> chronos@localhost / $ sudo croutonversion
> sudo: croutonversion: command not found
> chronos@localhost / $ 

This was the beginning of the install I did earlier tonight using `sudo sh ~/Downloads/crouton -e -t xfce`

looks like I might have downloaded version 1.0.87

> Downloading latest crouton installer...
> ######################################################################## 100.0%
> You must have a root password in Chromium OS to mount encrypted chroots.
> Password: 
> Verifying - Password: 
> Choose an encryption passphrase for precise: 
> Please confirm your passphrase: 
> Generating keys (move the mouse to generate entropy)...
> done
> WARNING: Signed boot verification is disabled; enabling it for security.
> You can disable it again using: sudo crossystem dev_boot_signed_only=0
> Installing precise-amd64 chroot to /usr/local/chroots/precise
> Downloading latest debootstrap...
> Download from Debian gitweb failed. Trying latest release...
> 2017-01-02 20:13:51 URL:http://mirror.math.princeton.edu/pub/debian/pool/main/d/debootstrap/ [6591/6591] -> "-" [1]
> Downloading debootstrap version 1.0.87...
> 2017-01-02 20:13:51 URL:http://ftp-nyc.osuosl.org/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
> Patching debootstrap...
> Downloading bootstrap files...
> W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
> I: Retrieving InRelease 
> W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/InRelease
> I: Retrieving InRelease 
> W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/InRelease
> I: Retrieving InRelease 
> W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/InRelease
> I: Retrieving InRelease 
> W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/InRelease

After about 10 retries, it looks like it determined it was a corrupted file and moved on with the install.

> W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/InRelease
> W: http://archive.ubuntu.com/ubuntu/dists/precise/InRelease was corrupt
> I: Retrieving Release 
> I: Retrieving Packages 
> I: Validating Packages 
> I: Resolving dependencies of required packages...
> I: Resolving dependencies of base packages...
> I: Checking component main on http://archive.ubuntu.com/ubuntu...

**Comment by DennisLfromGA** [comment]
@AlexObliv2029,

No problem.

> chronos@localhost /mnt/stateful_partition/crouton/chroots $ sudo croutonversion

Don't use the 'sudo' prefix *inside* your chroot for crouton stuff, that'll get you into trouble with permissions, just use 'sudo' *outside* your chroot for crouton stuff in your crosh shell.

----
Let's please start over with something that works better.

First of all delete the chroots you've started that don't work using -

`cd /usr/local/chroots ; sudo delete-chroot * ; cd`

Then instead of 'precise', we'll install a newer release but we won't encrypt it to make it simpler, if you really want to encrypt it you can do that later, use this -

`sudo sh ~/Downloads/crouton -r trusty -t xiwi,xorg,xfce,keyboard`

Then install the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension from the Chrome Webstore.

Now you can start your xfce4 desktop in a number of ways -

1. `sudo startxfce4` (that will launch in a window via 'xiwi', the default)

2. `sudo startxfce4 -X xiwi-fullscreen` (that will launch fullscreen via 'xiwi')

3. `sudo startxfce4 -X xiwi-tab` (that will launch in a browser tab via 'xiwi' - *my favorite*)

4. `sudo startxfce4 -X xorg` (that will launch in a separate screen via 'xorg')

Please note, the last option using 'xorg' is having some temporary difficulties (blackscreens) so it may not work for you without some [extra effort](https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795).

*Hope this helps,*
-**DennisL**

**Comment by jhut1971** [comment]
DennisL,
I'm having the identical issue. I will try your suggestion and let you know how I make out.
Joe

**Comment by 10BaseTwo** [comment]
Thanks Dennis! That worked perfectly for me, I am now up and running. Thanks again for your patience and help!!

@AlexObliv2029 @jhut1971, I hope this works for you!

**Comment by jhut1971** [comment]
Thank you, all worked for me as well

**Comment by Hasaf** [comment]
I am still unable to get it to work.

when I ent4er:
sudo sh ~/Downloads/crouton -r trusty -t xiwi,xorg,xfce,keyboard

Linux starts; I cam see the terminal prompt change to what I expect a Linux prompt to look like. However, the GUI never starts. I see several "Cannot connect to the extension, retrying ...

Then is says 
Unable to start display, make sure crouton extension is installed 



I ahve also noticed that when I run this command:
sudo sh ~/Downloads/crouton -r trusty -t xiwi,xorg,xfce,keyboard

I get several messages:
Cannot check release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
Retrying failed download of http://archiveubuntu.com/ubuntu/dists/trusty/InRelease

**Comment by DennisLfromGA** [comment]
@Hasaf,

> when I enter:
sudo sh ~/Downloads/crouton -r trusty -t xiwi,xorg,xfce,keyboard

> Linux starts; I cam see the terminal prompt change to what I expect a Linux prompt to look like. However, the GUI never starts.  

The first 'crouton' command will *install* your chroot not start a desktop session.
I think you are referring to using `sudo startxfce4`.

> I see several "Cannot connect to the extension, retrying ...

With the 'xiwi' xmethod you also have to install the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension from the Chrome Webstore. If you don't you'll get this message:
```
You must install the Chromium OS extension for integration with crouton to work.
The extension is available here: https://goo.gl/OVQOEt
```
It's easy to miss these messages sometimes.

> I ahve also noticed that when I run this command:
sudo sh ~/Downloads/crouton -r trusty -t xiwi,xorg,xfce,keyboard

> I get several messages:
Cannot check release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg

The 'keyring' warnings are not critical.

> Retrying failed download of http://archiveubuntu.com/ubuntu/dists/trusty/InRelease

You may have to re-run the 'crouton' installation command or do a 'crouton' update using the '-u' option.

------
Since you also installed the 'xorg' xmethod you should be able to launch your xfce desktop using:

`sudo startxfce4 -X xorg`

*Hope this helps,*
-**DennisL**

**Comment by Hasaf** [comment]
Dennis, 

Thanks, that was it. I already had crouton integration, I didn't have the correct start command.

Regards,
Hasaf

**Comment by jbeale1** [comment]
Acer Chromebook 15 having trouble with crouton, can't download "InRelease", don't know why?

(precise)john@localhost:~$ sudo sh ~/Downloads/crouton -r trusty -t xiwi,xorg,xfce,keyboard
WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
If this is a surprise to you, you should do a full system recovery via USB.
Installing trusty-amd64 chroot to /usr/local/chroots/trusty
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2017-01-28 10:40:06 URL:http://mirrors.ocf.berkeley.edu/debian/pool/main/d/debootstrap/ [6179/6179] -> "-" [1]
Downloading debootstrap version 1.0.87...
2017-01-28 10:40:07 URL:http://debian.mirror.constant.com/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
W: http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease was corrupt

**Comment by jbeale1** [comment]
as far as I know my crouton version is the latest:

(precise)john@localhost:~$ croutonversion -u -d -c
crouton: version 1-20161129162558~master:5f2f11f9
Retrieving latest version of crouton
latest: version 1-20161129162558~master:5f2f11f9

**Comment by DennisLfromGA** [comment]
@jbeale1,

Your issue doesn't seem to be related to this topic but...
A lot of times these are just transient network glitches, try again (and again). :)

-----
> _**(precise)john@localhost:~$**_ sudo sh ~/Downloads/crouton -r trusty -t xiwi,xorg,xfce,keyboard

Taking a second look at your command string, it looks like you're trying to install a new 'trusty' chroot _**inside**_ your 'precise' chroot - *not good!*
Exit your 'precise' chroot and try again if you like.

*Hope this helps,*
-**DennisL**

**Comment by jbeale1** [comment]
If you browse to http://archive.ubuntu.com/ubuntu/dists/trusty you can see that "Release" does exist, however "InRelease" does not exist. Is this a typo in the install script? Did the name change? Was the InRelease file deleted?

**Comment by zaky46** [comment]
hello dennis I'm sorry I want to ask my password can not be pressed in ubuntu how to solve it? I want to use ubuntu to install application on my chromebook
can you help me? can i Ask  your facebook address

**Comment by DennisLfromGA** [comment]
@zaky46,

[ This is way off topic but it's a quick fix so I'll respond. ]

> I'm sorry I want to ask my password can not be pressed in ubuntu how to solve it? I want to use ubuntu to install application on my chromebook
can you help me? 

Get into your chroot as root using: 

`sudo enter-chroot -u root`

Then run the `passwd` command for the username you want to set a new password for, somthing like this: 

`passwd zack`

Then enter the new password twice, it won't be displayed for security reasons.
Then exit your chroot and re-enter it again, `sudo` and other commands should now work with your new password.

> can i Ask your facebook address

Sorry, I don't do facebook.

*Hope this helps,*
-**DennisL**

**Comment by persondave** [comment]
I was struggling to get into xfce it gave me this
chronos@localhost / $ sudo startxfce4 -X xorg
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-101-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Mar 6 00:48:40 PST 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=c49e8bc6-17b3-874a-81f6-d365891763d1/PARTNROFF=1 hashtree=PARTUUID=c49e8bc6-17b3-874a-81f6-d365891763d1/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=4c4a4802b46620e295a0e1290f301282e3937acd salt=095217dc15841800c6f07e195546de1d5ec45c19e22478a19efacaf6250eb957" noinitrd vt.global_cursor_default=0 kern_guid=c49e8bc6-17b3-874a-81f6-d365891763d1  
Build Date: 24 November 2017  09:45:24AM
xorg-server 2:1.19.5-0ubuntu2~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Mar 30 09:26:29 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1522416390.381939 sender=:1.7 -> destination=:1.40 serial=477 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1522416390.669875 sender=:1.7 -> destination=:1.42 serial=479 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

please help

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.

**Comment by zaky46** [comment]
Why so late ? -_-? I change my chroombook back.
Tq for respon -,,

Pada tanggal Sel, 17 Jul 2018 05.50, DennisL <notifications@github.com>
menulis:
