### ISSUE TITLE
uid 1000 not found in trusty

### ISSUE THREAD

**Issue by mikeydoesit** [dnschneid/crouton#2971]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
Password: 
Sorry, try again.
Password: 
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue: when i attempt to start ubuntu on crouton i get the same error message everytime.  uid 1000 not found in trusty. Below is an example:

chronos@localhost / $ sudo startunity
Enter encryption passphrase for trusty: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
UID 1000 not found in trusty
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

Can anyone help?

**Comment by DennisLfromGA** [comment]
Try updating your chroot, it looks like the installation didn't finish successfully.
You can update it using either of these two ways -
1. `sudo sh ~/Downloads/crouton -n trusty -u` 
2. `sudo enter-chroot -n trusty -u root` (and let it finish the setup.)

*Hope this helps,*
-**DennisL**

**Comment by mikeydoesit** [comment]
Evening Dennis,

Thanks for the reply.  I sincerely appreciate your help.

Well I followed your instructions and unfortunately didn't rectify the issue

chronos@localhost / $ sudo edit-chroot -all
Password: 
name: trusty
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: unity-desktop,gtk-extra,cli-extra,extension,keyboard,xbmc,chrome
host: version 8872.73.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:07:06 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

and again when I attempt to start ubuntu I get this:

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/trusty...
UID 1000 not found in trusty
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

Note: The first line you gave me runs and there's a lot text scrolling rapidly on the monitor.

The second option you gave me outputs:

chronos@localhost / $ sudo enter-chroot -n trusty -u root
Password: 
Sorry, try again.
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
(trusty)root@localhost:~# 

Any idea what is going on or what else i could try?

Thanks Dennis

**Comment by DennisLfromGA** [comment]
@mikeydoesit,

Strange...

> Note: The first line you gave me runs and there's a lot text scrolling rapidly on the monitor.

Hard to tell without knowing what text scrolled by but if it enters the chroot as root (the second option) and doesn't ask you to complete the setup then it sounds like it *may* have been successful.

Can you enter your chroot with the username you provided when you installed it (`sudo enter-chroot -n trusty`)?

If not use `sudo enter-chroot -n trusty -u root` and then show us the output of `tail /etc/passwd`

I'm just shooting in the dark really, I don't know why it either wouldn't update and prompt you for a username/password or show an error and leave an incomplete setup file.  (???)

*Hope this helps,*
-**DennisL**

**Comment by mikeydoesit** [comment]
If its alright with you perhaps we could video call on google hangouts.
That way I could share the screen and you could see exactly what might be going wrong?

At a time of your own convenience of course.

**Comment by DennisLfromGA** [comment]
@mikeydoesit,

Let's try log outputs and screenshots first, we should be able to tell from those I think.

*Hope this helps,*
-**DennisL**

**Comment by mikeydoesit** [comment]
@DennisLfromGA ,

Sincerest apologies for the late response.  I recently lost someone dear to me.  I could bore you with the details but i won't.  I'd rather jump straight in and pickup where we left off.

So..... I entered `sudo enter-chroot -n trusty -u root` as `sudo enter-chroot -n trusty` returned the same `UID 1000 not found in trusty` error message.

The output from `tail /etc/passwd` is:

`(trusty)root@localhost:~# tail /etc/passwd
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
libuuid:x:100:101::/var/lib/libuuid:
syslog:x:101:104::/home/syslog:/bin/false
messagebus:x:102:105::/var/run/dbus:/bin/false
colord:x:103:108:colord colour management daemon,,,:/var/lib/colord:/bin/false
usbmux:x:104:85:usbmux daemon,,,:/home/usbmux:/bin/false
avahi:x:105:112:Avahi mDNS daemon,,,:/var/run/avahi-daemon:/bin/false
lightdm:x:106:113:Light Display Manager:/var/lib/lightdm:/bin/false
pulse:x:107:116:PulseAudio daemon,,,:/var/run/pulse:/bin/false
rtkit:x:108:118:RealtimeKit,,,:/proc:/bin/false`

Is this getting any closer to identifying the issue?
@mikeydoesit

**Comment by DennisLfromGA** [comment]
@mikeydoesit,

If the command: "`sudo sh ~/Downloads/crouton -n trusty -u`" does *not* fix it then your chroot may be toast I'm afraid. If you don't have too much invested in it I would delete it and try to install a new one using:

`sudo sh ~/Downloads/crouton -r trusty -t xorg,xiwi,unity-desktop,cli-extra,keyboard,xbmc,chrome`

Then install the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension for 'xiwi'.

That will set xmethod 'xorg' as the default but let you use 'xiwi' also if you like.
And if you want to encrypt it you can do it afterward with an update.

*Hope this helps,*
-**DennisL**

**P.S.** *Sorry for your loss.*

**Comment by mikeydoesit** [comment]
@DennisLfromGA ,

I thought that might be the case.  Is it better to perform a powerwash or is there an easier way to delete it from the command line?

Thank you for all your time and advice.
-**mikeydoesit**

**Comment by DennisLfromGA** [comment]
@micahflee,

You can delete just your 'trusty' chroot using: `sudo delete-chroot trusty`

If you want to delete all of your chroots I would do this:

`cd /usr/local/chroots ; sudo delete-chroot * ; cd`

*Hope this helps,*
-**DennisL**

**Comment by mikeydoesit** [comment]
@DennisLfromGA 

Thanks again, 

I'm guessing the semi-colon is used to concatenate commands in one line?  Also i noticed you ended with cd. Why exactly is that necessary? Is it to close the command?

**-mikeydoesit**

**Comment by DennisLfromGA** [comment]
@mikeydoesit,

Yes, the semi-colon separates commands and is an easy way of doing it on one line.

Since I cd'ed into `/usr/local/chroots` to execute the commands, I just used 'cd' to put me back in my $HOME directory. Probably not *necessary* but just safer to 'operate' in one's $HOME directory.

*Hope this helps,*
-**DennisL**

**Comment by mikeydoesit** [comment]
@DennisLfromGA,

Ahh, good to know.

Much appreciated.
