### ISSUE TITLE
"Sudo startunity" crashing in chromebook

### ISSUE THREAD

**Issue by EvonR** [dnschneid/crouton#2972]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
crosh> shell
chronos@localhost / $ sudo edit-chroot -all
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 8872.73.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $ 

#### Please describe your issue: 
I had an issue with xfce4 starting to ask me an unknown password when doing "sudo startxfce4" so I powerwashed my Acer chromebook 14. After that tried to install KDE, but after doing so and doing "sudo startkde" I got some "D-bus" error. So I powerwashed my chromebook again and tried with unity. but now can't start unity either without crashing. I am very very begginner in linux, so I really can't understand the "basic knowledge" of linux and linux commands. So please if possible tell me the commands to enter and other stuff to do. 

#### If known, describe the steps to reproduce the issue:

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=f48ed039-5e51-f14f-b6a0-e7dc8e4dac10/PARTNROFF=1 hashtree=PARTUUID=f48ed039-5e51-f14f-b6a0-e7dc8e4dac10/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=4534f027f05bf44cd9353db7bc208a36aa165c8a salt=c3ddc1a30ef1cbe0cebdd1255c02d4495fee4eeb64329bc324ac6c74d226e063" noinitrd vt.global_cursor_default=0 kern_guid=f48ed039-5e51-f14f-b6a0-e7dc8e4dac10 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Dec 25 17:04:09 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[intel_init_bufmgr:1069] Error initializing buffer manager.
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 8872.73.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $

**Comment by chrisortman** [comment]
I am getting this too. It was working the first time I set every thing up, then I tried turning supervised users on and this started happening.

I've since powerwashed and tried redoing everything, but now can't get past this.

**Comment by drrobotnic** [comment]
If you take a look here

![screen shot 2016-12-31 at 10 03 09 am](https://cloud.githubusercontent.com/assets/10187542/21578917/6437b502-cf40-11e6-8a98-f8f836c2dc3e.png)

They have disabled running with root. Try running `startunity` or `enter-chroot`

**Comment by DennisLfromGA** [comment]
@drrobotnic, 

*That's not entirely correct*, see this comment for clarification on when to use 'sudo': https://github.com/dnschneid/crouton/issues/2982#issuecomment-269881293

*Hope this helps,*
-**DennisL**

**Comment by drrobotnic** [comment]
Oh ok, thanks for the headsup

**Comment by drrobotnic** [comment]
Also, what is the danger of running `sudo` inside a chroot? I did not entirely get that part. Thanks for the quick reply, as well.

**Comment by DennisLfromGA** [comment]
@drrobotnic,

Using sudo *inside* the chroot for the crouton scripts will hose up your permissions and break things.
To fix things again when that happens use: `chown -R 1000:1000 "$HOME"`

*Hope this helps,*
-**DennisL**

**Comment by drrobotnic** [comment]
Ok, thanks for the quick reply!
