### ISSUE TITLE
X server: undefined symbol: ChangeWindowProperty (kali linux)

### ISSUE THREAD

**Issue by pcmschool** [dnschneid/crouton#2974]
```
Please paste the output of the following command here: sudo startxfce4
```

#### Please describe your issue:
Here is the error (while installing kali linux):
Compiling Xorg dummy driver...
dummy_driver.c: In function 'DUMMYCreateWindow':
dummy_driver.c:868:15: warning: implicit declaration of function 'ChangeWindowProperty' [-Wimplicit-function-declaration]
___ ret = ChangeWindowProperty(pWinRoot, VFB_PROP, XA_STRING,
________^~~~~~~~~~~~~~~~~~~~
And here also is the same error ( when executing sudo startxfce4 ):
Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.0
Release Date: 2016-11-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=fa704f1e-7cf3-4448-8b7d-6b6af628097c/PARTNROFF=1 hashtree=PARTUUID=fa704f1e-7cf3-4448-8b7d-6b6af628097c/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=4534f027f05bf44cd9353db7bc208a36aa165c8a salt=c3ddc1a30ef1cbe0cebdd1255c02d4495fee4eeb64329bc324ac6c74d226e063" noinitrd vt.global_cursor_default=0 kern_guid=fa704f1e-7cf3-4448-8b7d-6b6af628097c add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 23 November 2016  07:20:23PM
xorg-server 2:1.19.0-2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Dec 26 01:56:28 2016
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/lib/xorg/Xorg: symbol lookup error: /usr/lib/xorg/modules/drivers/dummy_drv.so: undefined symbol: ChangeWindowProperty
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/kali...

Hope managers can fix this soon as no new installing kali linux user can access kali linux because of this error. (chromebook)

**Comment by arj03** [comment]
https://github.com/dnschneid/crouton/pull/2953
