### ISSUE TITLE
Black Screen Lockup On Suspend

### ISSUE THREAD

**Issue by dmnorth** [dnschneid/crouton#2976]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: obuntu
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/obuntu...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,extension
host: version 8872.73.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:05:03 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

```
Latest xserver-xorg-video-intel ( version 7 in trusty-updates) causes my crouton to lock up with black screen if I suspend my chromebook. Reverting to previous version (6) solves problem. This is an Asus c202 chromebook with OS 55.blahblah.  This may be unique to my setup since nobody else is mentioning anything, so I don't think it's terribly urgent. I removed trusty-updates from my sources.list and expect to be able to run just fine indefinitely.

Hmm. Would it have made a difference if I added the xorg target?

#### If known, describe the steps to reproduce the issue:

Update Trusty with trusty-updates in sources.list, getting the latest  xserver-xorg-video-intel. Start the crouton. Suspend. Resume. Try to do the four-finger salute to get back into the crouton. Observe The Edge Of Space.

**Comment by AllHopeLost** [comment]
Im also having this issue but it happens with kali-linux rolling and this is with the command line interface only. this started happening after thee most recent update to chrome os. 

If I enter the chroot at all and even log out and make sure I unmount all chroots it hangs if the chromebook is put into suspend and when I try to wake it back up just black screen with a solid blue status light and have to hardboot the chromebook to get it back. 

name: kali
encrypted: no
Entering /media/removable/crouton-sd/chroots/kali...
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: amd64
targets: core,cli-extra
host: version 8872.73.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:06:39 PST 2016 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/crouton-sd/chroots/kali...

Im on an acer r11 the cb5-132t-c8zw series. 

Proccessor: Intel Celeron N3060
Memory: 4 GB 
Storage: 16 GB eMMC

**Comment by dmnorth** [comment]
I'm going to leave this open for a while just in case, but in the third iteration of setting this up the problem has disappeared, at least for now. Beats me.

**Comment by DennisLfromGA** [comment]
I've heard 'third time's the charm', let's hope the issue was just a glitch.

**Comment by azertyfun** [comment]
I have the same problem. However, I was able to SSH the chromebook and run dmesg:

```
[  450.034708] audit: type=1400 audit(1484414881.660:304): avc:  denied  { ioctl } for  pid=2692 comm="netfilter-queue" path="socket:[64725]" dev="sockfs" ino=64725 ioctlcmd=8910 scontext=u:r:chromeos:s0 tcontext=u:r:chromeos:s0 tclass=unix_dgram_socket permissive=1
[  450.034961] audit: type=1400 audit(1484414881.660:305): avc:  denied  { ioctl } for  pid=2692 comm="netfilter-queue" path="socket:[64727]" dev="sockfs" ino=64727 ioctlcmd=8910 scontext=u:r:chromeos:s0 tcontext=u:r:chromeos:s0 tclass=unix_dgram_socket permissive=1
[  453.034541] audit: type=1400 audit(1484414884.660:306): avc:  denied  { ioctl } for  pid=2692 comm="netfilter-queue" path="socket:[63919]" dev="sockfs" ino=63919 ioctlcmd=8910 scontext=u:r:chromeos:s0 tcontext=u:r:chromeos:s0 tclass=unix_dgram_socket permissive=1
[  470.733660] audit: type=1400 audit(1484414902.359:307): avc:  denied  { write } for  pid=15762 comm="sshd" scontext=u:r:chromeos:s0 tcontext=u:r:chromeos:s0 tclass=key permissive=1
[  470.733682] audit: type=1400 audit(1484414902.359:308): avc:  denied  { link } for  pid=15762 comm="sshd" scontext=u:r:chromeos:s0 tcontext=u:r:chromeos:s0 tclass=key permissive=1
[  470.742781] systemd-logind[15765]: Failed to enable subscription: Launch helper exited with unknown return code 1
[  470.742799] systemd-logind[15765]: Failed to fully start up daemon: Input/output error
```

Here is my `sudo edit-chroot -all`:
```
name: stretch
encrypted: no
crouton: version 1-20161129162558~master:5f2f11f9
release: stretch
architecture: amd64
xmethod: xorg
targets: xfce,keyboard,extension
host: version 8872.76.0 (Official Build) stable-channel lars 
kernel: Linux localhost 3.18.0-13437-g2bea612c #1 SMP PREEMPT Fri Jan 6 23:51:59 PST 2017 x86_64 GNU/Linux
freon: yes
```

The chromebook is an Acer CP5-471.

**Comment by dmnorth** [comment]
I'm going to close this issue since it has simply stopped happening. Nothing to see here, folks.
