### ISSUE TITLE
Black Screen w/ Xorg but not Xiwi

### ISSUE THREAD

**Issue by eliot2** [dnschneid/crouton#2978]
```
name: test
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/test...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,lxde,xiwi,extension,keyboard
host: version 9000.29.0 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Dec 14 22:03:23 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/test...
```

#### Please describe your issue:
Black screen after fresh install AND on old install. Occurred on both Trusty and Xenial, LXDE and XFCE4.

#### If known, describe the steps to reproduce the issue:
Fresh install, then the usual "sudo startxfce4"

Using ACER C720p Chromebook.

Command line output:

> chronos@localhost ~/Downloads $ sudo startlxde -X xorg
> Entering /mnt/stateful_partition/crouton/chroots/test...
> 
> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
> 
> X.Org X Server 1.15.1
> Release Date: 2014-04-13
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Dec 14 22:03:23 PST 2016 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=4486abfc-5454-6443-9d28-02cb3ccd67a3/PARTNROFF=1 hashtree=PARTUUID=4486abfc-5454-6443-9d28-02cb3ccd67a3/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=3d59e801875cf113c93ab641157ba7d601d34a43 salt=280c655fa742032b6186b82da975766b8e90a538e2102a515204058902243b42" noinitrd vt.global_cursor_default=0 kern_guid=4486abfc-5454-6443-9d28-02cb3ccd67a3 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
> Build Date: 12 February 2015  02:49:29PM
> xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.30.2
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec 27 12:32:33 2016
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Initializing built-in extension Generic Event Extension
> Initializing built-in extension SHAPE
> Initializing built-in extension MIT-SHM
> Initializing built-in extension XInputExtension
> Initializing built-in extension XTEST
> Initializing built-in extension BIG-REQUESTS
> Initializing built-in extension SYNC
> Initializing built-in extension XKEYBOARD
> Initializing built-in extension XC-MISC
> Initializing built-in extension SECURITY
> Initializing built-in extension XINERAMA
> Initializing built-in extension XFIXES
> Initializing built-in extension RENDER
> Initializing built-in extension RANDR
> Initializing built-in extension COMPOSITE
> Initializing built-in extension DAMAGE
> Initializing built-in extension MIT-SCREEN-SAVER
> Initializing built-in extension DOUBLE-BUFFER
> Initializing built-in extension RECORD
> Initializing built-in extension DPMS
> Initializing built-in extension Present
> Initializing built-in extension DRI3
> Initializing built-in extension X-Resource
> Initializing built-in extension XVideo
> Initializing built-in extension XVideo-MotionCompensation
> Initializing built-in extension SELinux
> Initializing built-in extension XFree86-VidModeExtension
> Initializing built-in extension XFree86-DGA
> Initializing built-in extension XFree86-DRI
> Initializing built-in extension DRI2
> Loading extension GLX
> xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
> crouton: version 1-20161129162558~master:5f2f11f9
> release: trusty
> architecture: amd64
> xmethod: xorg
> targets: xorg,lxde,xiwi,extension,keyboard
> host: version 9000.29.0 (Official Build) beta-channel peppy 
> kernel: Linux localhost 3.8.11 #1 SMP Wed Dec 14 22:03:23 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Agent pid 5286
> ** Message: main.vala:99: Session is LXDE
> ** Message: main.vala:100: DE is LXDE
> ** Message: main.vala:131: log directory: /home/eliot/.cache/lxsession/LXDE
> ** Message: main.vala:132: log path: /home/eliot/.cache/lxsession/LXDE/run.log
> (II) AIGLX: Suspending AIGLX clients for VT switch
> Cannot open /sys/class/tty/tty0/active: No such file or directory
> Error: target STRING not available
> (II) AIGLX: Suspending AIGLX clients for VT switch
> ^C
> Session terminated, terminating shell.../usr/bin/xinit: connection to X server lost
> 
> waiting for X server to shut down Hangup
> Hangup
> Hangup
> Running exit commands...
> (EE) Server terminated successfully (0). Closing log file.
> 
> /usr/bin/xinit: unexpected signal 2
>  ...terminated.
> Unmounting /mnt/stateful_partition/crouton/chroots/test...

**Comment by w-barath** [comment]
Fresh install with xiwi and xorg, starting with "sudo startxfce4 -n xfce -X xorg"

symptoms:
Black screen regardless of chroot.  Usual fixes don't work: Flipping the lid, ssh into running chroot and  "brightness 0; brightness 100" also did nothing.

Obviously different on the error log:
"Error: target STRING not available"

Temporary workaround: I can use it by starting Xephyr on xiwi, or by starting xvnc and then accessing it with vnc extension, but its not ideal.  Surprisingly x11vnc doesn't work.  Apparently xorg on the unmapped VT locks itself up until it gets mapped again, so no joy.

**Comment by eliot2** [comment]
Update:
https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795
This change ALMOST fixes it. Now, the screen just doesn't update, and doesn't update everything, so it's not black, and you can move stuff around, but that's it.

Tested w/ fresh install of Trusty+XFCE4.

**Comment by eliot2** [comment]
FIXED!

If your problem is the IOPL error, do the following:
(this worked on my c720p Acer)
Change 
/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf 
to

```
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# On Intel platforms with FBC enabled, in order to see anything we need to use
# the SNA driver with the TearFree option.
Section "Device"
   #Identifier "Intel Graphics SNA+TearFree"
   #Driver     "intel"
   # Option     "AccelMethod" "uxa"
   # Option     "TearFree"    "true"
   Identifier "Modesetting"
   Driver "modesetting"
   Option "AccelMethod" "sna"
   Option "TearFree" "true"
EndSection
```

Keep in mind, depending on your system, it might be /mnt/stateful_partition/crouton/chroots/test2/usr/share/X11/xorg.conf.d/20-crouton.conf
That you have to modify, OR
/mnt/stateful_partition/crouton/chroots/test2/usr/share/X11/xorg.conf.d/20-crouton-intel-sna.conf 
but that last file is actually just a symbolic link to
/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf

**Comment by eliot2** [comment]
Editted w/ "glamor" info for acceleration.

**Comment by zgriesinger** [comment]
THANK YOU @eliot2!!!!!!!!!!!!!! I have been wrestling with this issue for so long on my Toshiba Chromebook 2, having ran at least 25 different chroots a new update must have botched things (At least I think that was the issue) 

Can confirm your solution works for Toshiba Chromebook 2 SWANKY with XFCE

**Comment by MCBGamingYT** [comment]
how do you modify files like that when you cant open it normally? do you do it only with the chrosh terminal?

**Comment by brentirwin** [comment]
MCBGamingYT, I'm having the same problem. Says xorg-intel-sna.conf is readonly. Like zgriesinger I am also on a Toshiba Chromebook 2. I was playing Minecraft in XFCE and quit the game while still in full-screen. Since then, XFCE has been complete black. Mine didn't have anything to do with a Chrome update. I guess I'll know to exit full screen before quitting Minecraft next time.

**Comment by bgroenks96** [comment]
@eliot2 You're the best, my friend, thank you! I'd buy you a drink if I could!

**Comment by davidlowryduda** [comment]
@eliot2 I wanted to thank you --- this worked for me with the most recent update.

**Comment by punchline18** [comment]
@eliot2 I am a total noob going through all these black screen issues, and I have xfce booted with xiwi in a tab, but I still cant seem to get xorg to work. I think I need to try your edditted change to the config file with "glamour" and "PageFlip", but honestly, Idk how to change/modify those files specifically (sorry for being a total noob). Can someone please post the command? Thx

**Comment by davidlowryduda** [comment]
@punchline18 

This is something that needs to be done from ChromeOS. Here's what you do.

Begin in ChromeOS. Open up a shell (probably using ctrl+alt+T). Enter a "real" shell by typing `shell`.

You should now navigate to `/mnt/stateful_partition/crouton/chroots/test2/etc/crouton/xorg-intel-sna.conf`. Note that this is only an approximate name. It will begin with `/mnt/stateful_partition/crouton/chroots/`. Then you may have many chroots, named whatever you named them. eliot2 has one named `test2`. I happen to have one named `precise`. But you'll have whatever your chroot is. But inside of your <chrootname> will be `/etc/crouton/` and an xord config file.

So you will need to go to `/mnt/stateful_partition/crouton/chroots/<chrootname>/etc/crouton/`. (I'm assuming you know how to use `cd` and `ls` --- reasonable, right?)

Now the config file is there. You will need to edit the config file. By default, vi is installed, so you could use `vim xorg-intel-sna.conf` if you know anything about vim. If not, then either follow a vim tutorial or choose a different editor.

Does that make sense?

**Comment by punchline18** [comment]
@davidlowryduda , Thanks for the beginner rundown, I have gotten to: `/mnt/stateful_partition/crouton/chroots/<chrootname>`
and then I run `ls` and I get a bunch of encrypted mumbo jumbo.. so the encryption might be  problem? anyway around this? thanks again

**Comment by davidlowryduda** [comment]
@punchline18 Can you give the copy in the output of the following two commands in that directory:

`pwd`
`ls`

**Comment by punchline18** [comment]
@davidlowryduda sure thing and I'll add `edit-chroot -all` too. (note: I have also tried this on trusty, aswell as the other channels, but I have not tried it without encryption)

`sudo edit-chroot -all`
```
Password: 
name: yakkety
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/yakkety...
crouton: version 1-20161129162558~master:5f2f11f9
release: yakkety
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi,keyboard,chrome,extension
host: version 9000.82.0 (Official Build) stable-channel winky 
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 1 15:04:35 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/yakkety as another instance is using it.
```

 `pwd`
`/mnt/stateful_partition/crouton/chroots/yakkety`

`ls`
```
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQl21gfFtE3FcVN-BLbAWwQW---
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQl3PDScx7NxX5KO1drBYYjVk--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQl7rpvEf5VCdJ6eyQ52u2CuU--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQl87USK4Tltl3iwu23fn7OgU--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQl8suHdGhooCi50uVyMudlzE--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlBhp4fiNQ5WlMx.vzsbGAZE--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlDIb7Y.2NQTsoDJ2N2rRv.E--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQleT-WAQhJ2MctyxvbzP8AoE--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlf7kllmO6M2w-48KhVeuyak--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlFaHRtqDo7gzbV7lWDTmr8k--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlFHerp-y-VxoX8.OD.hV.wE--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQl-IFhyQziQ0EOsiP6NFrx3U--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlIWE5AA5GQGAT93YcIDUr.---
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlpgsbgTfS8JoD.UswP2ovC---
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlPxj-m42u1Vzbb.EZYVt6p---
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlqdllalRxLctL9IuYe.2Km---
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlsnabtQr-zxx0hAOjr4SPeU--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQltzRS6fQkpRlfHB.7W.f2a---
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlu4KIzhIxUQvhbc9zybruNU--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlxOfX-q40Fq1oGUGUMJQZnE--
ECRYPTFS_FNEK_ENCRYPTED.FWaHR15k.B.RI-QBv.rL0.0lcJEDnEdkoiQlXyrBABbc6rxX69jCxWXWTU--
```

**Comment by davidlowryduda** [comment]
@punchline18 Interesting, I have not played around with encrypting chroots. So unfortunately, I'm not familiar with how to unencrypt that segment.

Are you capable of accessing a terminal from within xfce in a xiwi tab? [If not, then I'm afraid I don't know how to help, and additional expertise will be needed]

**Comment by punchline18** [comment]
@davidlowryduda yes, everything is running great in xiwi-tab, I just feel like I coud gain some snappiness from xorg.. plus better game performance with the 3D acceleration. my ultimate goal being [Autostart crouton chroot at ChromeOS startup](https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup) but with xorg

**Comment by davidlowryduda** [comment]
@punchline18 Now, it is probably a good idea to back up your chroot (if you haven't already).

Now open a terminal in your xiwi-tab. In your terminal, type `cd /etc/crouton`. You are now in the relevant directory, and there should be a `xorg-intel-sna.conf` file (or a file looking like that) there. Edit that file using your preferred text editor (e.g,. perhaps `vim xorg-intel-sna.conf`).

**Comment by punchline18** [comment]
@davidlowryduda After learning vim and modifying the file, it works!! can't thank you enough!

**Comment by DennisLfromGA** [comment]
@punchline18, **et all**,

Try updating your chroot, the devs have put in place some patches that may alleviate all these workarounds.

*Hope this helps,*
-**DennisL**

**Comment by w-barath** [comment]
> DennisLfromGA commented 5 days ago
> @punchline18, et all,
> 
> Try updating your chroot, the devs have put in place some patches that may alleviate all these workarounds.
> 
> Hope this helps,
> -DennisL

This bug is definitely still in effect.  I updated my chroots today and without disabling SNA I still get a black screen (with a live mouse pointer).

I haven't done proper research but I remember reading not long ago that Intel were dropping support for SNA, so maybe the Chromium team were a little too adventurous in accepting new driver patches, resulting in this regression.

Without SNA the X11 performance is noticeably slower, and we've lost scaled displays with the XRANDR extension... but other than that it seems to be fine.

**Comment by PedroKay** [comment]
Thank you all.  Worked on acer CB3-111 today.
