### ISSUE TITLE
Black screen on startxfce4

### ISSUE THREAD

**Issue by grabbeh** [dnschneid/crouton#2979]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.29.0 (Official Build) beta-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Dec 14 21:55:56 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

#### Please describe your issue:

Black screen on start up. On the command line I get the following output:

(precise)michael@localhost:~$ startxfce4
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Dec 14 21:55:56 PST 2016 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=f2e10a87-e50e-2241-a98c-a502a631b487/PARTNROFF=1 hashtree=PARTUUID=f2e10a87-e50e-2241-a98c-a502a631b487/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=97c70e56c98bcef5e72a444c9ff38e643c1a2cfc salt=9fd37dc2080a1bfa633c065fcd576d0f1947d81da3c8e2ee8374ef6c04bfd819" noinitrd vt.global_cursor_default=0 kern_guid=f2e10a87-e50e-2241-a98c-a502a631b487 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  gpt 
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec 27 20:25:28 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
setversion 1.4 failed: Permission denied
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.29.0 (Official Build) beta-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Dec 14 21:55:56 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
Agent pid 5537
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.

(xfce4-session:5544): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfsettingsd:5551): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfwm4:5549): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
xfdesktop[5558]: starting up

(xfdesktop:5558): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-panel:5557): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
xfce4-settings-helper: Another instance is already running. Leaving...

(xfce4-terminal:5575): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(polkit-gnome-authentication-agent-1:5569): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:5569): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(wrapper:5581): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
xfce4-terminal: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
running 'ssh-agent -s -k'
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 5537 killed;
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 20:26:27: SIGHUP received: restarting...
Hangup
xscreensaver: 20:26:27: running as michael/michael (1000/1000)

xscreensaver: 20:26:27: Can't open display: :1
xscreensaver: 20:26:27: running as michael/michael (1000/1000)

xscreensaver: 20:26:27: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html

(EE) Server terminated successfully (0). Closing log file.

#### If known, describe the steps to reproduce the issue:

Issue arises on entering 'start xfce4'

**Comment by DennisLfromGA** [comment]
Probably a dup of #2923, #2926, #2946, etc.
For a possible fix see https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795

**Comment by eliot2** [comment]
https://github.com/dnschneid/crouton/issues/2978#issuecomment-269849365

**Comment by grabbeh** [comment]
Fixed using eliot2's fix in the above linked post. Thanks both!

**Comment by DennisLfromGA** [comment]
@grabbeh et all,

I think the fix in @eliot2's [post](https://github.com/dnschneid/crouton/issues/2978#issuecomment-269849365) is the way to go since it still uses SNA not UXA.  

I saw this error in the log:  
> "(WW) modeset(0): Option "TearFree" is not used"

So maybe it's just SNA without Tearfree but it works.

-**DennisL**
