### ISSUE TITLE
Cannot run command "sudo startxfce4"

### ISSUE THREAD

**Issue by phoenixdown9** [dnschneid/crouton#2982]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: x
orgtargets: xfce
host: version 8872.73.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
When i enter "sudo startxfce4" to crosh, it returns lines too quickly for me to read, turns my screen into a black background with a lot of white spots on it, and then displays an error box followed by another error box. The first error box is titled: "Unable to contact settings server" and it reads: "//bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon" The second error box is titled: "Unable to load a failsafe session" and reads: "Unable to determine failsafe session name. Possible causes: xfcond isn't running (D-Bus setup problem); environment variable $XDG_CONFIG_DIRS is set incorrectly (must include "/etc"), or xfce4-session is installed incorrectly."

#### If known, describe the steps to reproduce the issue:
I have no idea what caused this. I am a total noob (no experience with linux) , and I am installing crouton on a Chromebook I got for Christmas so that I can run a Java IDE. I would appreciate any help as to how to even get into the distro.

**Comment by drrobotnic** [comment]
Actually, you should not run crouton with root. They have edited `startxfce` to not run with root. Try running `enter-chroot` or `startxfce`

**Comment by DennisLfromGA** [comment]
@drrobotnic,

Just a clarification:

**_Outside_ your chroot** you need to use '*sudo*' for your crouton scripts, like:

  `sudo enter-chroot`, `sudo startxfce4`, `sudo edit-chroot`, etc.

**_Inside_ your chroot** you should *not* use '*sudo*' for your crouton scripts, like:

  `croutonversion`, `xinit`, `startxfce4`, etc.

*Hope this helps,*
-**DennisL**

**Comment by phoenixdown9** [comment]
To fix this, I just installed trusty xfce instead. Apparently there is some type of issue with an update to chromeOS that I don't understand.

**Comment by DennisLfromGA** [comment]
Thanx for the feedback @phoenixdown9.
I was going to point you to this unresolved issue https://github.com/dnschneid/crouton/issues/2917 but no need now.

**Comment by benclarkgray** [comment]
I have this same exact issue with precise as well.  How did you install trusty?  I'm pretty new to Linux

**Comment by zachrattner** [comment]
@bclarkgray this did the trick for me, from the crosh Terminal (ctrl + alt + T)

`sudo sh -e ~/Downloads/crouton -r trusty -t xfce -e`

**Comment by andro7991** [comment]
good
