### ISSUE TITLE
Xfce4 fails on Acer Chromebook 15

### ISSUE THREAD

**Issue by startographer** [dnschneid/crouton#2984]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel banon 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:07:12 PST 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### Please describe your issue:

I have installed kali linux using crouton like 25 times now. Once every now and then when I type sudo enter-chroot startxfce4 it will launch, but if I ever close the lid, even for a second, I'll open it to a backlit black screen and have to power off the chromebook. If I try to launch after rebooting I'll get the log below. Then the next 4 or 5 attempts to install chroot, delete chroot, powerwash, repeat return the same log. I've been all over google, I've tried updating the chroot, using crouton and kali crouton,  and even tried sana.  

xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel banon 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:07:12 PST 2016 x86_64 GNU/Linux
freon: yes
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
xfce4-session: No SSH authentication agent found
gpg-agent[20750]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent[20750]: directory '/home/cloud/.gnupg' created
gpg-agent[20750]: directory '/home/cloud/.gnupg/private-keys-v1.d' created

(xfce4-session:20734): xfce4-session-WARNING **: gpg-agent returned no PID in the variables

(xfce4-session:20734): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /home/cloud/.cache/sessions/xfce4-session-localhost:1, Does it exist? Permissions issue?
gpg-agent[20751]: gpg-agent (GnuPG) 2.1.16 started
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(xfwm4:20753): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfwm4:20753): xfwm4-WARNING **: The property '/general/double_click_distance' of type int is not supported
process 20763: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1367.
This is normally a bug in some application using the D-Bus library.

(xfsettingsd:20765): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfsettingsd:20765): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfsettingsd:20765): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfwm4:20753): xfwm4-WARNING **: Another compositing manager is running on screen 0
(II) AIGLX: Suspending AIGLX clients for VT switch
method return time=1482902567.779418 sender=:1.11 -> destination=:1.60 serial=528 reply_serial=2
   boolean true

#### If known, describe the steps to reproduce the issue:

1) sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce

2) Enter chroot name and password

3) sudo enter-chroot startxfce4

4) Error log

**Comment by lmoryl** [comment]
When this happens, is it unresponsive to (e.g.) ctrl-alt-shift-left?  I ask because in my own travels with crouton and xfce4 I've opened my (similarly Acer '15) chromebook to a black screen, and resuscitated switching window away and back.

**Comment by longzhixin** [comment]
I have the same error
