### ISSUE TITLE
Kali linux (full) Asus C201

### ISSUE THREAD

**Issue by steinbarge1** [dnschneid/crouton#2985]
Hey guys, relative Kali newbie here, ran into an issue on my new install of Kali Linux (with the command apt-get kali-linux-full). Wondering if I can get some help on this? Thanks

Platform: Asus C201 Chromebook
Text out put of edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Dec 17 10:58:23 PST 2016 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

Text output of starxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.0
Release Date: 2016-11-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Dec 17 10:58:23 PST 2016 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=ed21f7be-3065-134e-a6c9-1fc9b1d248e3/PARTNROFF=1 hashtree=PARTUUID=ed21f7be-3065-134e-a6c9-1fc9b1d248e3/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=b9086073d292a64002a53eec7c18f9d34290b67a salt=7b2a47218b8631883603b562d259e9ddf77f82045120837bf744169ed89a8a0c" noinitrd vt.global_cursor_default=0 kern_guid=ed21f7be-3065-134e-a6c9-1fc9b1d248e3  
Build Date: 23 November 2016  08:27:42PM
xorg-server 2:1.19.0-2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Dec 28 00:54:14 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by Xciser** [comment]
had he same issue,  I have found that kali-rolling is just unstable and some of the tools in the full download do not work properly
