### ISSUE TITLE
Failed to Download

### ISSUE THREAD

**Issue by SpaceboyRoss01** [dnschneid/crouton#2986]
```
sudo sh ~/Downloads/crouton -t xiwi,core,kde,lxde,unity,x11,xfce -n xenial
```

#### Please describe your issue:
The shell says:
```
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/precise/InRelease
I: Retrieving InRelease 
```
`http://archive.ubuntu.com/ubuntu/dists/precise/InRelease` is not a valid url

#### If known, describe the steps to reproduce the issue:
Just run the crouton command

**Comment by octopusnz** [comment]
@SpaceboyRoss01 This looks like the same issue as #2966  - have a read through for some wisdom but no solutions as yet.

Just a suggestion though, looking at your example command above if you wanted to install the xenial release you could try just running this:

```
sudo sh ~/Downloads/crouton -r xenial 

```
This seems to work better for a few people.

**Comment by hoosierEE** [comment]
For what it's worth, I had this same issue when trying to install with `-r jessie`.

However, installing with `-r xenial` seems to be working.
