### ISSUE TITLE
crouton install will not connect to archive.ubuntu.com

### ISSUE THREAD

**Issue by DaddioDickerson** [dnschneid/crouton#2989]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Password: 
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
targets: xfce,xiwi
host: version 8872.73.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:06:42 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
#### Please describe your issue:

When installing any version of ubuntu with any version of desktop the install always completes with some archives not installed because of not connecting to archive.ubuntu.com.
#### If known, describe the steps to reproduce the issue:
sudo sh ~/Downloads/crouton -t xfce,xiwi

**Comment by octopusnz** [comment]
@DaddioDickerson Looks like the same issue as #2966 
You can see some wisdom in there but no solution as yet.

If you'd like to try a xenial chroot you can get that using this command, which seems to be working for some people:

```
sudo sh ~/Downloads/crouton -r xenial -t xfce
```

Or do let us know if you have seen the same issue with xenial as well (might need a copy/paste of the specific packages that are failing in that scenario)

**Comment by DaddioDickerson** [comment]
That did not work either. I will get the log and send it to you.


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: octopusnz <notifications@github.com> Date: 12/30/16  7:39 PM  (GMT-06:00) To: dnschneid/crouton <crouton@noreply.github.com> Cc: DaddioDickerson <thomas@tdickerson.com>, Mention <mention@noreply.github.com> Subject: Re: [dnschneid/crouton] crouton install will not connect to
  archive.ubuntu.com (#2989) 
@DaddioDickerson Looks like the same issue as #2966

You can see some wisdom in there but no solution as yet.
If you'd like to try a xenial chroot you can get that using this command, which seems to be working for some people:
sudo sh ~/Downloads/crouton -r xenial -t xfce

Or do let us know if you have seen the same issue with xenial as well (might need a copy/paste of the specific packages that are failing in that scenario)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dnschneid/crouton","title":"dnschneid/crouton","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dnschneid/crouton"}},"updates":{"snippets":[{"icon":"PERSON","message":"@octopusnz in #2989: @DaddioDickerson Looks like the same issue as #2966 \r\nYou can see some wisdom in there but no solution as yet.\r\n\r\nIf you'd like to try a xenial chroot you can get that using this command, which seems to be working for some people:\r\n\r\n```\r\nsudo sh ~/Downloads/crouton -r xenial -t xfce\r\n```\r\n\r\nOr do let us know if you have seen the same issue with xenial as well (might need a copy/paste of the specific packages that are failing in that scenario)"}],"action":{"name":"View Issue","url":"https://github.com/dnschneid/crouton/issues/2989#issuecomment-269842484"}}}
