### ISSUE TITLE
Having Issue with Ubuntu Crouton installation on Braswell chip.

### ISSUE THREAD

**Issue by Enochwel** [dnschneid/crouton#2990]
So I had a bunch of junk coming from my Linux area and decided to start clean and redo everything.  Did everything (I thought) the same, but now I'm getting black screen on startup.  Thanks for any help!

This is what I ran to install:
sudo sh ~/Downloads/crouton -e -t lxde
I do have the crouton extension
This is the startup: 

You can start LXDE via the startlxde host command: sudo startlxde

Unmounting /mnt/stateful_partition/crouton/chroots/precise...
Done! You can enter the chroot using enter-chroot.
chronos@localhost / $ sudo startlxde
Password: 
Enter encryption passphrase for precise: 
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13532-g18a7100 #1 SMP PREEMPT Wed Dec 14 06:17:09 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=5e8f2632-4837-d040-a334-4921c9a968d2/PARTNROFF=1 hashtree=PARTUUID=5e8f2632-4837-d040-a334-4921c9a968d2/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=114c1e71f9248410ad58660f1e15fc618ded73db salt=7549df3caaae6b69c259363f5a04796624b5c76bf5d98b49484ed77cf14132f9" noinitrd vt.global_cursor_default=0 kern_guid=5e8f2632-4837-d040-a334-4921c9a968d2 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Dec 31 03:32:06 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[intel_init_bufmgr:1069] Error initializing buffer manager.
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: lxde
host: version 9086.0.0 (Official Build) dev-channel reks 
kernel: Linux localhost 3.18.0-13532-g18a7100 #1 SMP PREEMPT Wed Dec 14 06:17:09 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
EOF in dbus-launch reading address from bus daemon
Obt-Message: Xinerama extension is not present on the server

(polkit-gnome-authentication-agent-1:11865): polkit-gnome-1-WARNING **: Error getting authority: Error initializing authority: Could not connect: No such file or directory
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
                
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
Openbox-Message: Requested key "XF86Terminal" does not exist on the display
^[[A^C/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
xscreensaver: 03:38:18: SIGHUP received: restarting...
xscreensaver: 03:38:18: running as enochwel/enochwel (1000/1000)

Hangup
pcmanfm: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
Running exit commands...
XIO:  fatal IO error 104 (Connection reset by peer) on X server ":1"
      after 5663 requests (5526 known processed) with 0 events remaining.
(EE) Server terminated successfully (0). Closing log file.
xscreensaver: 03:38:18: Can't open display: :1
xscreensaver: 03:38:18: running as enochwel/enochwel (1000/1000)

xscreensaver: 03:38:18: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html

/usr/bin/xinit: unexpected signal 2
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $ ^C

**Comment by Enochwel** [comment]
Here is something else:
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: precise
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $

**Comment by chasechasechase** [comment]
I'm having the same issue on my Acer R11. I've tried installing trusty with both KDE and xfce with same outcomes.

With xfce I only booted to a black screen and that's it, but KDE at least gives me the welcome chime, however still black screen.

**Comment by chasechasechase** [comment]
I can confirm that enrolling into the stable channel and power washing has resolved the issue for me.

**Comment by drrobotnic** [comment]
Same for me. Happy new year!

**Comment by Enochwel** [comment]
I'm going to powerwash and try again.  Happy New Year!

**Comment by Enochwel** [comment]
I always had problems with the previous installation, which is why I wanted to start fresh.  Anyways, after powerwash, I ran this:

sudo sh -e ~/Downloads/crouton -r trusty -t xfce,xiwi,extension

On my Lenovo N22 with N3050 Braswell Celeron CPU, 
I havent had any problems except one minor issue - 
which is that the crouton extension app disables itself unless I immediately alt-shift-ctrl--> after logging on to ubuntu.  If I can never solve that, I think I'd still be perfectly happy given what I have to play with at no cost.  

Thanks!
