### ISSUE TITLE
Try to retry failed download, keeps failing ubuntu install

### ISSUE THREAD

**Issue by drrobotnic** [dnschneid/crouton#2991]
Trying to install a new chroot after my old one got corrupted. Tried running
`sudo sh -e crouton -t kde`
But keeps on telling me that there was a failed download, and it is retrying the failed download. I checked my connections, and I am connected to the internet. The link of the failed install was ports.ubuntu.com/dists/precise/stable. Checked it out, said that it was a bad link. There was nothing there.

**Comment by DennisLfromGA** [comment]
@drrobotnic,

I would suggest a newer release using something like the following:

`sudo sh ~/Downloads/crouton -r trusty -t kde`

*Hope this helps,*
-**DennisL**

**Comment by drrobotnic** [comment]
Ok, tried it out, and everything is working! Thanks so much
