### ISSUE TITLE
Kali will not start xserver

### ISSUE THREAD

**Issue by pswiifanwmi** [dnschneid/crouton#2993]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce-desktop,extension
host: version 8872.73.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:05:03 PST 2016 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
I'm trying to start XFCE with the startxfce4 command, however when I do, it fails even with a fresh chroot.

I get this as the output:
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.0
Release Date: 2016-11-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:05:03 PST 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=66c55ce6-bb17-c445-9309-ce315284b589/PARTNROFF=1 hashtree=PARTUUID=66c55ce6-bb17-c445-9309-ce315284b589/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=bdd2412288f8336bfcac1dd268e5fab6f0504c48 salt=a1578c2ad900eba4f4231ef0bffac23acff06c2da7478912286447eb47c0714d" noinitrd vt.global_cursor_default=0 kern_guid=66c55ce6-bb17-c445-9309-ce315284b589 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 16 December 2016  07:30:27PM
xorg-server 2:1.19.0-3 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jan  2 15:17:05 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1483388225.391621 sender=:1.11 -> destination=:1.64 serial=424 reply_serial=2
   boolean true
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce-desktop,extension
host: version 8872.73.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:05:03 PST 2016 x86_64 GNU/Linux
freon: yes
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No SSH authentication agent found
gpg-agent[1416]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent[1416]: directory '/home/will/.gnupg' created
gpg-agent[1416]: directory '/home/will/.gnupg/private-keys-v1.d' created
gpg-agent[1417]: gpg-agent (GnuPG) 2.1.16 started

(xfce4-session:1399): xfce4-session-WARNING **: gpg-agent returned no PID in the variables

(xfce4-session:1399): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /home/will/.cache/sessions/xfce4-session-localhost:1, Does it exist? Permissions issue?

(xfwm4:1419): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(xfwm4:1419): xfwm4-WARNING **: The property '/general/double_click_distance' of type int is not supported
process 1434: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1367.
This is normally a bug in some application using the D-Bus library.

(xfsettingsd:1428): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed

(xfsettingsd:1428): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed

(xfsettingsd:1428): GLib-GObject-CRITICAL **: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
/usr/share/system-config-printer/applet.py:45: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
system-config-printer-applet: failed to start NewPrinterNotification service
system-config-printer-applet: failed to start PrinterDriversInstaller service: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.40" is not allowed to own the service "com.redhat.PrinterDriversInstaller" due to security policies in the configuration file

(xfwm4:1419): xfwm4-WARNING **: Another compositing manager is running on screen 0
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
method return time=1483388256.578113 sender=:1.11 -> destination=:1.66 serial=425 reply_serial=2
   boolean true
Error: target STRING not available
^[[23;2~method return time=1483388287.168628 sender=:1.11 -> destination=:1.69 serial=434 reply_serial=2
   boolean true
(EE) 
Fatal server error:
(EE) EnterVT failed for screen 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(II) AIGLX: Suspending AIGLX clients for VT switch
method return time=1483388287.199632 sender=:1.11 -> destination=:1.70 serial=435 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
xfce4-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

(xfsettingsd:1428): libxfce4ui-WARNING **: ICE I/O Error

(xfsettingsd:1428): libxfce4ui-WARNING **: Disconnected from session manager.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xfdesktop: Fatal IO error 4 (Interrupted system call) on X server :1.0.
Hangup
Hangup

I've been able to cause it to crash so that I can use the CLI, but I have to spam CTRL-ALT-SHIFT-BACK/FORWARD.
#### If known, describe the steps to reproduce the issue:
Start Kali-rolling, extension, and xfce-desktop in chroot.  Install kali-desktop-xfce package, remove xserver-legacy (or whatever it's called).  Put Chromebook to sleep, reopen.  You should need to force a shutdown, start up again, and you should get this error.

**Comment by octopusnz** [comment]
@pswiifanwmi This may or may not help but have a look at some wisdom here:

https://github.com/dnschneid/crouton/issues/2978#issuecomment-269849365

**Comment by drinkcat** [comment]
Update should fix this.
