### ISSUE TITLE
Not start xserver

### ISSUE THREAD

**Issue by ShapeGz** [dnschneid/crouton#2994]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde
host: version 53.2.49 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Wed Nov 9 04:50:28 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
Entering /mnt/stateful_partition/crouton/chroots/trusty...

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.14+ #1 SMP Wed Nov 9 04:50:28 UTC 2016 x86_64
Kernel command line: init=/sbin/init boot=local rootwait ro noresume noswap loglevel=3 quiet noinitrd console= root=PARTUUID=A667A424-8164-DE43-B929-DEBDB72EBC1D i915.modeset=1 cros_legacy cros_debug BOOT_IMAGE=vmlinuz.A 
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Tue Jan  3 02:36:47 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
. /usr/bin/xinit: server error

Xorg:
Fatal server error:
Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.

**Comment by DennisLfromGA** [comment]
@ShapeGz,

> (==) Log file: "/var/log/Xorg.1.log", Time: Tue Jan 3 02:36:47 2017

Can you show us the contents of "/var/log/Xorg.1.log" please?

> Server is already active for display 0
If this server is no longer running, remove /tmp/.X0-lock

Please reboot and try launching your desktop again.

-**DennisL**
*Hope this helps,*
-**DennisL**

**Comment by ShapeGz** [comment]
@DennisLfromGA,

Fatal server error:
Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.


Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help.

**Comment by DennisLfromGA** [comment]
@ShapeGz,

> Rebooting didnt help

Good to know.

Now how about showing us the contents of `/var/log/Xorg.1.log` or whatever file it's now reporting.

*Hope this helps,*
-**DennisL**

**Comment by ShapeGz** [comment]
@DennisLfromGA,

How do I know the content /var/log/Xorg.1.log?

**Comment by DennisLfromGA** [comment]
You can upload it to https://gist.github.com/ or http://pastebin.com/ or some other site then give us the link to view it.

**Comment by ShapeGz** [comment]
Which command must be entered in order to know the contents /var/log/Xorg.1.log?

**Comment by DennisLfromGA** [comment]
@ShapeGz,

I'm sorry but some basic understanding of Linux and the shell is needed to perform a lot of the things that 'crouton' can do. It might be best to do some online courses or reading before going any further at this point.

Sorry to bail out on you, maybe someone else will step in, who knows...

*Hope this helps,*
-**DennisL**

**Comment by ShapeGz** [comment]
@DennisLfromGA, 
I upload contents Xorg.1.log, please see.

**Comment by octopusnz** [comment]
@ShapeGz Not sure if you're still having this issue but you might have a lock file that's got stuck?
See this wisdom in the error message: "If this server is no longer running, remove /tmp/.X0-lock"

You could try something like:

```
sudo enter-chroot -n chrootname
```
Replace chroot name with your name (like trusty maybe).

```
cd /tmp
```
```
ls -la
```
Is there a .X0-lock file in there?
If so:
```
rm .X0-lock
```
Then try and start the desktop environment again.
