### ISSUE TITLE
cant start crouton xfce

### ISSUE THREAD

**Issue by TravelingWise** [dnschneid/crouton#2995]
Im currently trying to run linux, but i get this following error

> Entering /mnt/stateful_partition/crouton/chroots/precise...
> Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
> WARNING: starting chroot system dbus daemon failed with code 1
> /usr/bin/startxfce4: Starting X server
> 
> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
> 
> X.Org X Server 1.13.0
> Release Date: 2012-09-05
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
> Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Dec 17 10:58:23 PST 2016 armv7l
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=87eff41b-5f87-f84a-a242-d1635d51e0fe/PARTNROFF=1 hashtree=PARTUUID=87eff41b-5f87-f84a-a242-d1635d51e0fe/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=b9086073d292a64002a53eec7c18f9d34290b67a salt=7b2a47218b8631883603b562d259e9ddf77f82045120837bf744169ed89a8a0c" noinitrd vt.global_cursor_default=0 kern_guid=87eff41b-5f87-f84a-a242-d1635d51e0fe  
> Build Date: 05 November 2013  03:23:26PM
> xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.30.2
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jan  2 21:18:07 2017
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Initializing built-in extension Generic Event Extension
> Initializing built-in extension SHAPE
> Initializing built-in extension MIT-SHM
> Initializing built-in extension XInputExtension
> Initializing built-in extension XTEST
> Initializing built-in extension BIG-REQUESTS
> Initializing built-in extension SYNC
> Initializing built-in extension XKEYBOARD
> Initializing built-in extension XC-MISC
> Initializing built-in extension SECURITY
> Initializing built-in extension XINERAMA
> Initializing built-in extension XFIXES
> Initializing built-in extension RENDER
> Initializing built-in extension RANDR
> Initializing built-in extension COMPOSITE
> Initializing built-in extension DAMAGE
> Initializing built-in extension MIT-SCREEN-SAVER
> Initializing built-in extension DOUBLE-BUFFER
> Initializing built-in extension RECORD
> Initializing built-in extension DPMS
> Initializing built-in extension X-Resource
> Initializing built-in extension XVideo
> Initializing built-in extension XVideo-MotionCompensation
> Initializing built-in extension XFree86-VidModeExtension
> Initializing built-in extension XFree86-DGA
> Initializing built-in extension XFree86-DRI
> Initializing built-in extension DRI2
> Loading extension GLX
> crouton: version 1-20161129162558~master:5f2f11f9
> release: precise
> architecture: armhf
> xmethod: xorg
> targets: xfce
> host: version 8872.73.0 (Official Build) stable-channel veyron_speedy 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Dec 17 10:58:23 PST 2016 armv7l armv7l armv7l GNU/Linux
> freon: yes
> Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
> EOF in dbus-launch reading address from bus daemon
> /etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
> 
> ** (xfce4-session:21006): CRITICAL **: Unable to contact D-Bus session bus: Unknown error
> 
> ** (xfce4-session:21006): CRITICAL **: Unable to contact D-Bus session bus: //bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon
> 
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_connect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_disconnect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_disconnect_signal: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> _IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> 
> (xfce4-session:21006): xfconf-CRITICAL **: xfconf_init() must be called before attempting to use libxfconf!
> 
> ** (xfce4-session:21006): CRITICAL **: dbus_g_proxy_call: assertion `DBUS_IS_G_PROXY (proxy)' failed
> 
> (xfce4-session:21006): GLib-CRITICAL **: g_propagate_error: assertion `src != NULL' failed
> Failed to connect to Xfconf daemon: //bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon
> 
> running 'ssh-agent -s -k'
> /etc/xdg/xfce4/xinitrc: 1: eval: ssh-agent: not found
> Running exit commands...
> /usr/bin/xinit: connection to X server lost
> 
> waiting for X server to shut down Hangup
> xscreensaver: 21:18:15: SIGHUP received: restarting...
> xscreensaver: 21:18:15: running as urban/urban (1000/1000)
> 
> xscreensaver: 21:18:16: Can't open display: :1
> xscreensaver: 21:18:16: running as urban/urban (1000/1000)
> 
> xscreensaver: 21:18:16: Errors at startup are usually authorization problems.
>               But you're not logging in as root (good!) so something
>               else must be wrong.  Did you read the manual and the FAQ?
> 
>               http://www.jwz.org/xscreensaver/faq.html
>               http://www.jwz.org/xscreensaver/man.html
> 
> Server terminated successfully (0). Closing log file.
> 
> Unmounting /mnt/stateful_partition/crouton/chroots/precise...

```
sudo edit chroot gives me

> name: precise
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/precise...
> crouton: version 1-20161129162558~master:5f2f11f9
> release: precise
> architecture: armhf
> xmethod: xorg
> targets: xfce
> host: version 8872.73.0 (Official Build) stable-channel veyron_speedy 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Dec 17 10:58:23 PST 2016 armv7l armv7l armv7l GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/precise...

I wish to know how to fix this

**Comment by octopusnz** [comment]
@TravelingWise Do you want to have a look at some wisdom posted here and see if it helps:

https://github.com/dnschneid/crouton/issues/2970#issuecomment-270053222
