### ISSUE TITLE
Installing to an external drive, is not an ext filesystem

### ISSUE THREAD

**Issue by Astrades** [dnschneid/crouton#2998]
Whenever i try to install kali-rolling on gnome-desktop to my flash drive, it always returns the error below:
/media/removable/STUFF/chroots/kali-rolling is not an ext filesystem

To start the installation, I use the command below:
sudo sh -e ~/Downloads/crouton -r kali-rolling -t gnome-desktop -p /media/removable/STUFF/

What am I doing wrong? My flash drive was edited using gparted and is on an ext4 filesystem with 115.4 GB. How do I fix this error?

**Comment by DennisLfromGA** [comment]
@Astrades,

See what it's mounted as with: `mount | grep STUFF`

It should tell you if it's mounted as 'type ext4' or not.

*Hope this helps,*
-**DennisL**

**Comment by HPchrome** [comment]
I have the same problem when i run`sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce -n Kali -p '/media/removable/UNTITLED'` it gave 

> /media/removable/UNTITLED/chroots/Kali is not an ext filesystem.

after i run `mount | grep UNTITLED`
> `/dev/mmcblk1p1 on /media/removable/UNTITLED type vfat (rw,nosuid,nodev,noexec,relatime,dirsync,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,flush,time_offset=60,errors=remount-ro)

`how can i continue with installation?
