### ISSUE TITLE
Possible to launch app NOT in chrome tab?

### ISSUE THREAD

**Issue by Roaders** [dnschneid/crouton#2999]
As discussed in #2996 I am trying to get crouton working and launching apps without using a linux desktop environment.

Assuming that I can get this working I was wondering if it is possible to launch application using the x-windows server thing (sorry, very new to this, don't know correct terminology) but not in a chrome tab.

The address bar, tabs and book mark bar and so on at the top of the browser takes up a significant amount of room and if I am working in Visual Studio Code for example and more pixels I can use to display my code is a win!

Is there a way to launch apps in a "chromeless" chrome tab?

Thanks

**Comment by octopusnz** [comment]
@roaders I don't know of a way to launch the chroot without having the crosh shell tab open - but you might be able to full screen the browser window/tab that would give you more screen real estate?

You can try:

```
Shift + F4 (maximise window)
```
Or - if you browse to: chrome://flags in a tab
One of the options there should be 'Immersive Fullscreen' which you can enable (requires a restart).

**Comment by octopusnz** [comment]
I found some more wisdom -you might be able to launch it full screen using the -F argument:

```
Options:
$("$ENTERCHROOT" -h 2>&1 | grep -e ' -[bckntu]')
    -F          Launch the chroot_app full-screen.
    -T          Launch the chroot_app in a tab.
    -f          Prevent xiwi from quitting automatically. (see NOTE below)
```

**Comment by Roaders** [comment]
Aha- that help screen did the trick, many thanks.
