### ISSUE TITLE
Want to change to a Ubuntu 16.04 LTS version

### ISSUE THREAD

**Issue by Outpact** [dnschneid/crouton#3000]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8872.73.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Dec 17 11:22:39 PST 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
Explained in the title. Is it possible or something similar possible?

#### If known, describe the steps to reproduce the issue:
N/A

**Comment by DennisLfromGA** [comment]
Yup, see this wiki page: ['Upgrade chroot release'](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release)

**Comment by Outpact** [comment]
@DennisLfromGA alright so im on precise but I would like to update to trusty. Do I just follow that?

**Comment by DennisLfromGA** [comment]
@Outpact, 

I would suggest trying it first and then if you have questions come back and we'll try to answer them.

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment]
@Outpact, I don't know... **DennisL**

**Comment by drinkcat** [comment]
You could file a separate issus for the mouse.

**Comment by minecraftmasterfun** [comment]
try this:
**sudo do-release-upgrade**
