### ISSUE TITLE
apt-get command not found

### ISSUE THREAD

**Issue by jhut1971** [dnschneid/crouton#3001]
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce,keyboard
host: version 8872.73.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:06:39 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
Simply I can't seem to make the apt-get command to work. I have completely deleted trusty twice and reinstalled. I have no idea what to try, this is a fresh install.

example:
chronos@localhost / $ sudo apt-get update
sudo: apt-get: command not found

**Comment by jhut1971** [comment]
It looks like I may have just been running the command in the wrong place. I tried running the apt-get from the terminal in xfce with the sudo command, it asked for a password and worked.
example:
(trusty)liv@localhost:~$ sudo apt-get update

**Comment by DennisLfromGA** [comment]
Yup, *inside the chroot is where it's at!*
