### ISSUE TITLE
software updater 

### ISSUE THREAD

**Issue by xxcriticxx** [dnschneid/crouton#3002]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161116131524~master:9db73043
release: xenial
architecture: amd64
xmethod: xorg
targets: unity-desktop
host: version 8872.73.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:04:16 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:

something happen to my main user. when using software updater program tells me "you are not allowed to perform this action"

**Comment by octopusnz** [comment]
@xxcriticxx Not too sure! Would you be able to provide us with some more details - what command are you trying to run ? Is this in Ubuntu on a desktop ?

**Comment by xxcriticxx** [comment]
@octopusnz this ubuntu 16.04 on unity desktop am starting up software updater to update my system. program opens finds updates but when i update i get that msg

**Comment by octopusnz** [comment]
I found some wisdom here: #457
Basically it should be prompting you for your root password. Maybe some update has broken this at the moment.

My suggestion  - you could use the command line pretty easily to manage updates using apt (some examples below in case you're not familiar with it):

```
sudo apt-get update
```

And then

```
sudo apt-get upgrade
```

**Comment by xxcriticxx** [comment]
@octopusnz thx good read now i understand
