### ISSUE TITLE
please apply -m to bootstrap

### ISSUE THREAD

**Issue by gperciva** [dnschneid/crouton#3003]
At the time of this writing, Debian's `httpredir.debian.org` service redirects me to `debian.mirror.netelligent.ca`, which has no DNS entry.

I managed to work around this by manually untarring the crouton installer and editing `installer/debian/bootstrap`, because this value wasn't modified by the `-m MIRROR` option.  It would be nice if that value was automatically used for the bootstrap.

**Comment by octopusnz** [comment]
This sounds sensible - it would be awesome if you could report the issue with that mirror to Debian as well so they can hopefully get it sorted.

Looks like: http://bugs.debian.org/mirrors is the place.
