### ISSUE TITLE
Awesome not displaying, no back light [bug] [awesome WM]

### ISSUE THREAD

**Issue by DanHolli123** [dnschneid/crouton#3004]
I'm not currently on my chromebook right now... will update with more specific info later

i'm using an unsupported Ubuntu version (more info later) on an Acer C720P (on Dev channel)

When typing KDE in my terminal (made it an alias to `sudo startkde`) KDE Plasma 5 starts fine
But when typing Awesome (alias to the awesome xinit file) the backlight turns off and no AwesomeWM

Worked before (a few months ago when I was on last before this time) just updated last night when I used it and the problem happened

I updated the chroot by doing `sudo sh ./home/user/(user code here)/crouton -n Ubuntu -u -u` (I copied the script there)

problem still persisted
Please help, and I will revise tomorrow or at midnight tonight
also note that i'm not on often (<1 time a month) but I use AwesomeWM for everything but N64 Emulation witch I use KDE Plasma 5

**Comment by drinkcat** [comment]
Hard to tell without the output of croutonversion. Updating the chroot might help too.

Please reopen if this is still an issue.
