### ISSUE TITLE
External displays without HiDPI and laptop with HiDPI

### ISSUE THREAD

**Issue by fgblanch** [dnschneid/crouton#3009]
Hi,

I'm using a Chromebook with a HiDPI (Chromebook pixel 2)  using the configuration from the wiki (option 1 and 4) https://github.com/dnschneid/crouton/wiki/Chromebook-Pixel 
for the xiwi apps without any problem

But when i connect an external display without HiDPI, the same configuration is applied so the apps look huge. Is there a way to apply different configurations for different displays?

**Comment by michaelgosling** [comment]
AFAIK X11 only allows one DPI setting for all monitors. Wayland allows different DPI settings per monitor with the latest gnome-shell but I can't figure out how to get Wayland on crouton to run the full desktop environment.
