### ISSUE TITLE
Acer R11 Xorg willl not start after first reboot.

### ISSUE THREAD

**Issue by yitsheyzeus** [dnschneid/crouton#3010]
Searching for a solution, I saw several suggestions to replace /dev/dri/card0 with card1; I only have the 0 file.  X11 worked fine immediately after installation, but after reboot has this error:

[   202.865] (II) LoadModule: "modesetting"
[   202.865] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   202.865] (II) Module modesetting: vendor="X.Org Foundation"
[   202.865]    compiled for 1.18.4, module version = 1.18.4
[   202.866]    Module class: X.Org Video Driver
[   202.866]    ABI class: X.Org Video Driver, version 20.0
[   202.866] (II) UnloadModule: "modesetting"
[   202.866] (II) Unloading modesetting
[   202.866] (II) Failed to load module "modesetting" (already loaded, 32742)
[   202.866] (II) LoadModule: "fbdev"
[   202.866] (WW) Warning, couldn't open module fbdev
[   202.866] (II) UnloadModule: "fbdev"
[   202.866] (II) Unloading fbdev
[   202.866] (EE) Failed to load module "fbdev" (module does not exist, 0)
[   202.866] (II) LoadModule: "vesa"
[   202.867] (WW) Warning, couldn't open module vesa
[   202.867] (II) UnloadModule: "vesa"
[   202.867] (II) Unloading vesa
[   202.867] (EE) Failed to load module "vesa" (module does not exist, 0)
[   202.867] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   202.867] (WW) xf86OpenConsole: setpgid failed: Operation not permitted
[   202.867] (WW) xf86OpenConsole: setsid failed: Operation not permitted
[   202.882] (EE) open /dev/dri/card0: Permission denied
[   202.882] (WW) Falling back to old probe method for modesetting
[   202.882] (EE) open /dev/dri/card0: Permission denied
[   202.882] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[   202.882] (EE) Screen 0 deleted because of no matching config section.
[   202.882] (II) UnloadModule: "modesetting"
[   202.882] (EE) Device(s) detected, but none match those in the config file.
[   202.882] (EE) 
Fatal server error:
[   202.882] (EE) no screens found(EE) 
[   202.882] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[   202.882] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[   202.882] (EE) 
[   202.899] (EE) Server terminated with error (1). Closing log file.

**Comment by yitsheyzeus** [comment]
I changed some stuff, and did the card1/card0 thing, now I get a VT_ACTIVATEFAILED

[  1081.280] (II) LoadModule: "vesa"
[  1081.281] (WW) Warning, couldn't open module vesa
[  1081.281] (II) UnloadModule: "vesa"
[  1081.281] (II) Unloading vesa
[  1081.281] (EE) Failed to load module "vesa" (module does not exist, 0)
[  1081.281] (==) Matched modesetting as autoconfigured driver 0
[  1081.281] (==) Matched fbdev as autoconfigured driver 1
[  1081.281] (==) Matched vesa as autoconfigured driver 2
[  1081.281] (==) Assigned the driver to the xf86ConfigLayout
[  1081.281] (II) LoadModule: "modesetting"
[  1081.281] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  1081.281] (II) Module modesetting: vendor="X.Org Foundation"
[  1081.281]    compiled for 1.18.4, module version = 1.18.4
[  1081.281]    Module class: X.Org Video Driver
[  1081.281]    ABI class: X.Org Video Driver, version 20.0
[  1081.281] (II) UnloadModule: "modesetting"
[  1081.281] (II) Unloading modesetting
[  1081.281] (II) Failed to load module "modesetting" (already loaded, 32650)
[  1081.281] (II) LoadModule: "fbdev"
[  1081.282] (WW) Warning, couldn't open module fbdev
[  1081.282] (II) UnloadModule: "fbdev"
[  1081.282] (II) Unloading fbdev
[  1081.282] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  1081.282] (II) LoadModule: "vesa"
[  1081.283] (WW) Warning, couldn't open module vesa
[  1081.283] (II) UnloadModule: "vesa"
[  1081.283] (II) Unloading vesa
[  1081.283] (EE) Failed to load module "vesa" (module does not exist, 0)
[  1081.283] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  1081.283] (WW) xf86OpenConsole: VT_ACTIVATE failed: Invalid argument
[  1081.283] (EE) 
Fatal server error:
[  1081.283] (EE) xf86OpenConsole: Switching VT failed
[  1081.283] (EE) 
[  1081.283] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[  1081.283] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  1081.283] (EE)

**Comment by DennisLfromGA** [comment]
The card0/card1 problems have been fixed since Oct. 12, 2016 per this merge https://github.com/dnschneid/crouton/commit/68e8a3542b47e734e9820704bac1b82fc581f1c6

Please make sure to update your chroot(s) to get all the fixes then try again.

If you still have problems then show us the output of: `sudo edit-chroot -all`

*Hope this helps,*
-**DennisL**

**Comment by yitsheyzeus** [comment]
name: yakkety
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/yakkety...
crouton: version 1-20161129162558~master:5f2f11f9
release: yakkety
architecture: amd64
xmethod: xorg
targets: gnome-desktop,touch
host: version 8872.73.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13436-g8b496ef #1 SMP PREEMPT Sat Dec 17 11:06:39 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/yakkety as another instance is using it.

**Comment by yitsheyzeus** [comment]
I worked "pretty flawlessly" upon the initial install.  I noticed the vgem in /dev/dri symlink is broken only after reboot.

**Comment by DennisLfromGA** [comment]
Thanx for the info. but I can't tell what the issue is exactly.

Can you be more specific and give us more details?

**Comment by yitsheyzeus** [comment]
X11 won't start.  I get a variety of errors, but the one i am seeing right now is "no screen found."

I think if I had the right screen definition for the R11 it would work.

**Comment by DennisLfromGA** [comment]
You might be running into the blackscreen issue, maybe try this workaround: https://github.com/dnschneid/crouton/issues/2926#issuecomment-269165182

**Comment by yitsheyzeus** [comment]
this fixed teh issue

Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
EndSection

yakkety seems to work great, only issue i have now is it doesn't do sudo authorization in the GUI

I also had to do a locale-gen to get gnome-terminal working

**Comment by DennisLfromGA** [comment]
Interesting that you didn't need the `'Option "AccelMethod" "uxa"'` entry.

Anyway, glad it's working.
