### ISSUE TITLE
Debain is not installing: "debain does not belong to any supported distribution."

### ISSUE THREAD

**Issue by CapKenway** [dnschneid/crouton#3013]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/local/bin/enter-chroot: 511: cannot create /run/crouton/mnt/stateful_partition/crouton/chroots/precise/etc/crouton/name: Directory nonexistent
```

Description of the issue:
Debain is not installing. I already have a chroot. But I also want to install Debain (core) but It is saying that "debain does not belong to any supported distribution." Please someone help.

*Note: I am using a HP Chromebook 14 (intel) and I already have a chroot (ubuntu-unity).

**Comment by simonccc** [comment]
is it as simple as a typo? ie debian rather than "debain" ?

**Comment by DennisLfromGA** [comment]
@CapKenway,

> Debain is not installing. I already have a chroot. But I also want to install Debain (core) but It is saying that "debain does not belong to any supported distribution."

I'm not sure I understand what you're trying to do. It looks like your 'precise' chroot is failing or broken.

Do you want to install another chroot in addition to 'precise' or do you want to replace it?
If you want to install another 'debian' release you can choose from the ones that 'crouton' offers, see below:

```
Recognized debian releases:
    potato* woody* sarge* etch* lenny* squeeze* wheezy jessie stretch sid

Releases marked with * are unsupported, but may work with some effort.
```

You select a *'release'* when installing the crouton chroot using the '-r' option, similar to:

`sudo sh ~/Downloads/crouton -r sid -t xfce,...`

Specify any targets/desktop you prefer above after the '-t' option.

*Hope this helps,*
-**DennisL**
