### ISSUE TITLE
Versions chromebook 13

### ISSUE THREAD

**Issue by maddin200** [dnschneid/crouton#3015]
Here is my experience with a Acer ARM chromebook 13: 
ubuntu 12.04 precise unity - works
update 14.04 unity - do not work
ubuntu 16.04 unity - do not work
ubuntu 16.10 unity - do not work

**Comment by maddin200** [comment]
ubuntu 16.10 xfce - works !

**Comment by DennisLfromGA** [comment]
That hasn't been my experience.

I'm not sure if you're just posting your findings, which is fine, or if you want help getting unity to work on the other releases???

If you want help give us some more details about what failed, etc.

*Hope this helps,*
-**DennisL**

**Comment by maddin200** [comment]
It was just a summary of current experience.

**Comment by maddin200** [comment]
System chromebook Acer 13:
32 GB Harddisk
4 GB Memory
current crouton version
encrypted chroot

Asus Chromebook C 300 ubuntu 16.04 unity - works !

**Comment by DennisLfromGA** [comment]
Cool, I'll close this non-issue then.
