### ISSUE TITLE
Black screen when running 'sudo startxfce4'

### ISSUE THREAD

**Issue by GoRacerGo** [dnschneid/crouton#3016]
> name: trusty
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/trusty...
> crouton: version 1-20161129162558~master:5f2f11f9
> release: trusty
> architecture: amd64
> xmethod: xorg
> targets: xfce
> host: version 9000.50.0 (Official Build) beta-channel cyan 
> kernel: Linux localhost 3.18.0-13506-ge9db8d0 #1 SMP PREEMPT Wed Jan 4 22:05:42 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

#### Please describe your issue:

I'm new to linux/crouton/etc, so I don't know much. I'm in the process of learning.

I did `sudo sh ~/Downloads/crouton -e trusty -t xfce`, it installed, then I did `sudo startxfce4`. My screen changed to black. I can move back and forth between the black screen and chromeos using the ctrl+alt+shift+back/forward combo. 

I'm on an Acer Chromebook R11.

> Version 56.0.2924.53 beta (64-bit)
> Platform 9000.50.0 (Official Build) beta-channel cyan
> ARC Version 3612333
> Firmware Google_Cyan.7287.57.92

Here's what appears in the crosh terminal:

> chronos@localhost / $ sudo startxfce4
> Entering /mnt/stateful_partition/crouton/chroots/trusty...
> /usr/bin/startxfce4: Starting X server
> 
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> 
> X.Org X Server 1.15.1
> Release Date: 2014-04-13
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.18.0-13506-ge9db8d0 #1 SMP PREEMPT Wed Jan 4 22:05:42 PST 2017 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=b7f1f5ca-6733-774e-81eb-71170bfa4cb2/PARTNROFF=1 hashtree=PARTUUID=b7f1f5ca-6733-774e-81eb-71170bfa4cb2/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=213fb79dbd78458ea73c4f9d493444b1d1e57759 salt=c7fe8a5bd88f9f07e66c8488b1b895966deb003bcb24a0b4284eaad2989b3825" noinitrd vt.global_cursor_default=0 kern_guid=b7f1f5ca-6733-774e-81eb-71170bfa4cb2 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
> Build Date: 12 February 2015  02:49:29PM
> xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.30.2
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jan 10 18:36:10 2017
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Initializing built-in extension Generic Event Extension
> Initializing built-in extension SHAPE
> Initializing built-in extension MIT-SHM
> Initializing built-in extension XInputExtension
> Initializing built-in extension XTEST
> Initializing built-in extension BIG-REQUESTS
> Initializing built-in extension SYNC
> Initializing built-in extension XKEYBOARD
> Initializing built-in extension XC-MISC
> Initializing built-in extension SECURITY
> Initializing built-in extension XINERAMA
> Initializing built-in extension XFIXES
> Initializing built-in extension RENDER
> Initializing built-in extension RANDR
> Initializing built-in extension COMPOSITE
> Initializing built-in extension DAMAGE
> Initializing built-in extension MIT-SCREEN-SAVER
> Initializing built-in extension DOUBLE-BUFFER
> Initializing built-in extension RECORD
> Initializing built-in extension DPMS
> Initializing built-in extension Present
> Initializing built-in extension DRI3
> Initializing built-in extension X-Resource
> Initializing built-in extension XVideo
> Initializing built-in extension XVideo-MotionCompensation
> Initializing built-in extension SELinux
> Initializing built-in extension XFree86-VidModeExtension
> Initializing built-in extension XFree86-DGA
> Initializing built-in extension XFree86-DRI
> Initializing built-in extension DRI2
> Loading extension GLX
> xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
> crouton: version 1-20161129162558~master:5f2f11f9
> release: trusty
> architecture: amd64
> xmethod: xorg
> targets: xfce
> host: version 9000.50.0 (Official Build) beta-channel cyan 
> kernel: Linux localhost 3.18.0-13506-ge9db8d0 #1 SMP PREEMPT Wed Jan 4 22:05:42 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> _IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
> xfce4-session: No gpg or ssh authentication agent found
> 
> (xfwm4:11224): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed
> 
> (xfwm4:11224): xfwm4-WARNING **: The property '/general/double_click_distance' of type int is not supported
> /usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
> 
> (polkit-gnome-authentication-agent-1:11236): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed
> 
> (polkit-gnome-authentication-agent-1:11236): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
> 
> (xfsettingsd:11256): GLib-CRITICAL **: g_str_has_prefix: assertion 'prefix != NULL' failed
> (II) AIGLX: Suspending AIGLX clients for VT switch
> (II) AIGLX: Suspending AIGLX clients for VT switch

**Comment by DennisLfromGA** [comment]
It looks like you're running into the same blackscreen issue (#2923) that others are having.
For a temporary workaround, try this metod: https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795

**Comment by GoRacerGo** [comment]
Can you help run me through the steps to edit the file? I apologize - I'm a complete noob.

**Comment by DennisLfromGA** [comment]
@GoRacerGo,

The `/etc/crouton/` directory is *inside* your chroot.
First get into the chroot using: `sudo enter-chroot`
Then `cd /etc/crouton` to get into that directory and work on the file.

*Hope this helps,*
-**DennisL**

**Comment by The1andONLYdave** [comment]
@GoRacerGo,
seems your X11 uses another directory for config files:

> "(==) Using system config directory "/usr/share/X11/xorg.conf.d"" 

please try to copy your (edited) /etc/crouton/xorg-intel-sna.conf to this directory. Both paths are inside the chroot as DennisL mentioned above.

**Comment by MegaWalls** [comment]
`(trusty)thomas@localhost:~$ /usr/share/X11/xorg.conf.d -su: /usr/share/X11/xorg.conf.d: Is a directory`

that is the stage that I got to. How can I edit the file?

**Comment by The1andONLYdave** [comment]
You can use nano (apt-get Install nano, then "sudo nano /Path/to/File", exit n save with Ctrl+x and answering yes) or if apt-get not working "sudo vi /Path/File", but vi is a bit complicated to operate.

**Comment by MegaWalls** [comment]
used vi to change the file, but the error is still there!

**Comment by PeterMilley** [comment]
Just had this issue last night; editing the xorg-intel-sna.conf file as per the other thread and copying it to /usr/share/X11/xorg.conf.d/ appears to have worked. Thanks!

**Comment by dpilgrim** [comment]
I can also confirm that editing xorg-intel-sna.conf and copying it to /usr/share/X11/xorg.conf fixes the issue for me.

**Comment by The1andONLYdave** [comment]
@MegaWalls make sure xorg.conf.d is a directoy and you moved the file *inside* it. Can you post output of "ls -alh /usr/share/X11/xorg.conf.d/“ and  "ls -alh /usr/share/X11/" please?

**Comment by DennisLfromGA** [comment]
For those using the 'trusty' release with black screen issues, please update your chroot.
The latest crouton patches have fixed it.

**Comment by w-barath** [comment]
Dennis hasn't tested, he's making assumptions.

See #2978 for something that will actually work.

**Comment by DennisLfromGA** [comment]
@w-barath,

> Dennis hasn't tested, he's making assumptions.

Actually, @DennisLfromGA has tested it along with others and it has worked.

If you are still having problems then I'd suggest following this guide:  
#### ['Common issues and reporting'](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

If that doesn't help then please file a new issue and provide all the details you can, like croutonversion, xorg log, what you have tried, etc., etc.

*Hope this helps,*
-**DennisL**

**Comment by Urugami** [comment]
I was having this same issue after ChromeOS updated.
I updated my chroot by first deleting crouton and re-downloading it, then running
`sudo ~/Downloads/crouton -u -n trusty`

That churned for a while with a bunch of downloading and installing (even Java 8), and when it was over, I could get back to my kde session.

Try what @DennisLfromGA said, "Update your CHROOT"
