### ISSUE TITLE
Kali-Rolling Mouse Glide Issue

### ISSUE THREAD

**Issue by hickory88** [dnschneid/crouton#3018]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.50.0 (Official Build) beta-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jan 4 21:55:23 PST 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: precise
Enter encryption passphrase for precise: 
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.50.0 (Official Build) beta-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Wed Jan 4 21:55:23 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
#### Please describe your issue: 
In Kali-Rolling the mouse seems to "glide" about 500ms after the last touch. I have both tried reducing the sensitivity on both the Kali OS and the Chrome OS. After much testing I haven't seemed to be able to fix it. Currently, this only happens inside of Kali-rolling using both a mouse and the touchpad.
Running Chromebook Dell 11 MODEL CANDY.

#### If known, describe the steps to reproduce the issue: 
1. Download xfce (sudo sh ~/Downloads/crouton -t xfce)
2. Run xfce.
3. Exit xfce.
4. Download Kali-rolling (sudo sh ~/Downloads/crouton -r kali-rolling -t xfce)
5. Run Kali-rolling.
6. Move mouse/touchpad on default settings.

**Comment by drinkcat** [comment]
I'm not sure what trackpad candy uses, but one of these commands might help:
```
synclient FingerLow=1 FingerHigh=5
synclient FingerLow=5 FingerHigh=10
```

Please let us know, the output of:
`grep . /sys/class/input/event*/device/name`
would also be useful.
