### ISSUE TITLE
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1 - crouton will not load

### ISSUE THREAD

**Issue by joseph-palmer** [dnschneid/crouton#3019]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: gnome,xiwi,extension,xorg
host: version 8872.76.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13437-g2bea612c #1 SMP PREEMPT Fri Jan 6 23:53:17 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
#### Please describe your issue: when I try to load crouton it just says connection timed out. see bellow. 

Entering /mnt/stateful_partition/crouton/chroots/trusty...
Failed to start message bus: The pid file "/usr/local/var/run/dbus/pid" exists, if the message bus is not running, remove this file
WARNING: starting chroot system dbus daemon failed with code 1

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13437-g2bea612c #1 SMP PREEMPT Fri Jan 6 23:53:17 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=889fb3db-22e3-874d-8e93-dee3a2581737/PARTNROFF=1 hashtree=PARTUUID=889fb3db-22e3-874d-8e93-dee3a2581737/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=2c84b95c70c70e068111768c18e2a28474c144ff salt=d2048a015a0302eee52b0c54bcd32733d624af3cbdbad5fd39190c05035bb8f3" noinitrd vt.global_cursor_default=0 kern_guid=889fb3db-22e3-874d-8e93-dee3a2581737 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Jan 11 20:20:00 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: gnome,xiwi,extension,xorg
host: version 8872.76.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13437-g2bea612c #1 SMP PREEMPT Fri Jan 6 23:53:17 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
Error: target STRING not available
Trace/breakpoint trap (core dumped)
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup
Hangup

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file.

Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

**Comment by hickory88** [comment]
I had this error when running it with full Kali. What I have done to fix this is to powerwash the device and reinstall everything. Of course, best thing to do is to install Full Kali on a Removable Drive and boot it from there.

**Comment by joseph-palmer** [comment]
Yeah I thought that might be the only option. I'm trying to avoid that as I did it for a crouton I had before which crashed with the same error and I lost everything. I reinstalled crouton and closed it to back up the file and now ironically I can't get back in. I'd just like to know why it's happened and how I can stop it happening again if it can't be fixed

**Comment by hickory88** [comment]
@joseph-palmer I don't really see any other option so far. It has worked for me and I haven't had any other problems...Good luck though!
