### ISSUE TITLE
Chromebit, VLC, SMB to Windows not Playing

### ISSUE THREAD

**Issue by WMetzner** [dnschneid/crouton#3022]
I have enjoyed VLC for many years. Now I am connecting my brand new ChromeBit to my Windows file server to play videos, connected through the extensions "File system for Windows" and "Network File Share for Chrome OS". No luck with neither. I can navigate in VLC to the folder with the media files, but when I open a folder or file, I get "No media files found". Also saw the post about loading additional codecs, but there is no such option in this version.
Your help is very much appreciated and thanks for making VLC available.
Wolf Metzner, Austin TX

**Comment by drinkcat** [comment]
Is this VLC in crouton? Can you provide the output of croutonversion?

**Comment by DennisLfromGA** [comment]
Not sure but maybe you'll need to open some ports.
See the wiki ['Running servers in crouton'](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton) and look at the `iptables` commands.
