### ISSUE TITLE
Linux not extending to external monitor

### ISSUE THREAD

**Issue by MCBGamingYT** [dnschneid/crouton#3023]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde
host: version 9000.58.0 (Official Build) beta-channel gnawty 
kernel: Linux localhost 3.10.18 #1 SMP Tue Jan 10 22:01:43 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
When booting linux it does not extend to my secondary screen and i am unable to fix it due to the fact that my laptop screen is broken

#### If known, describe the steps to reproduce the issue:
install linux lxde using the latest version of crouton, run sudo startlxde on second screen while chromebook is in docked mode

**Comment by MCBGamingYT** [comment]
This showed up 

Fatal server error:
(EE) EnterVT failed for screen 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(II) AIGLX: Suspending AIGLX clients for VT switch
(EE) Server terminated with error (1). Closing log file.
Terminated
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by drinkcat** [comment]
xrandr --auto might fix that, not sure, so maybe the workaround in #3086 would fix that.
