### ISSUE TITLE
Building headers fails on arm chromebook 

### ISSUE THREAD

**Issue by lyons88** [dnschneid/crouton#3024]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: armhf
xmethod: xorg
targets: unity
host: version 8872.76.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Jan 7 00:03:49 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

#### Please describe your issue:

I need to build the sheepnet.ko for BasiliskII on my Arm Chromebook, but I'm having trouble building the kernel headers.

 I fallowed the guide https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86), but when I issue the command:

`make-kpkg --rootcmd fakeroot kernel_image kernel_headers`

It bombs out with this error:

`CC drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.o drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c: In function ‘pm_callback_suspend’: drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:1724:32: error: ‘level’ may be used uninitialized in this function [-Werror=uninitialized] drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:1710:9: note: ‘level’ was declared here drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c: In function ‘kbase_platform_cmu_pmu_control’: /home/jam/Downloads/kernel/arch/arm/include/asm/io.h:107:2: error: ‘g3d_status_reg’ may be used uninitialized in this function [-Werror=uninitialized] drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:608:8: note: ‘g3d_status_reg’ was declared here /home/jam/Downloads/kernel/arch/arm/include/asm/io.h:107:2: error: ‘g3d_status_reg’ may be used uninitialized in this function [-Werror=uninitialized] drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:641:8: note: ‘g3d_status_reg’ was declared here cc1: all warnings being treated as errors make[7]: *** [drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.o] Error 1 make[6]: *** [drivers/gpu/arm/midgard/platform/chromebook] Error 2 make[5]: *** [drivers/gpu/arm/midgard/platform] Error 2 make[4]: *** [drivers/gpu/arm/midgard] Error 2 make[3]: *** [drivers/gpu/arm] Error 2 make[2]: *** [drivers/gpu] Error 2 make[1]: *** [drivers] Error 2`

Any idea how I can get around this error?

**Comment by divx118** [comment]
It seems disabling warning on errors will solve it for you.
It can be that it is set as a config option in `chromeos/config/base.config` when it is you should find `CONFIG_ERROR_ON_WARNING=y` and turn it into `CONFIG_ERROR_ON_WARNING=n`
It can also be that it is set in the Makefile with the -Werror flag.

**Comment by lyons88** [comment]
Thanks for the reply divx, I gave that a try, but it still bombs out with the same error.

`  CC      drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.o
drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c: In function ‘pm_callback_suspend’:
drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:1724:32: error: ‘level’ may be used uninitialized in this function **[-Werror=uninitialized]**
drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:1710:9: note: ‘level’ was declared here
drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c: In function ‘kbase_platform_cmu_pmu_control’:
/home/jam/Downloads/kernel/arch/arm/include/asm/io.h:107:2: error: ‘g3d_status_reg’ may be used uninitialized in this function [-Werror=uninitialized]
drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:608:8: note: ‘g3d_status_reg’ was declared here
/home/jam/Downloads/kernel/arch/arm/include/asm/io.h:107:2: error: ‘g3d_status_reg’ may be used uninitialized in this function [-Werror=uninitialized]
drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.c:641:8: note: ‘g3d_status_reg’ was declared here
cc1: all warnings being treated as errors
make[7]: *** [drivers/gpu/arm/midgard/platform/chromebook/mali_kbase_config_chromebook.o] Error 1
make[6]: *** [drivers/gpu/arm/midgard/platform/chromebook] Error 2
make[5]: *** [drivers/gpu/arm/midgard/platform] Error 2
make[4]: *** [drivers/gpu/arm/midgard] Error 2
make[3]: *** [drivers/gpu/arm] Error 2
make[2]: *** [drivers/gpu] Error 2
make[1]: *** [drivers] Error 2
make[1]: Leaving directory `/home/jam/Downloads/kernel'
make: *** [debian/stamp/build/kernel] Error 2`

First I edited the `chromeos/config/base.config`changing` CONFIG_ERROR_ON_WARNING=y` to `CONFIG_ERROR_ON_WARNING=n`, that didn't seem to do anything, so I edited the Makefile:

```
# SHELL used by kbuild
CONFIG_SHELL := $(shell if [ -x "$$BASH" ]; then echo $$BASH; \
	  else if [ -x /bin/bash ]; then echo /bin/bash; \
	  else echo sh; fi ; fi)

HOSTCC       = gcc
HOSTCXX      = g++
HOSTCFLAGS   = -Werror -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer
HOSTCXXFLAGS = -O2 -Werror
'''

For some reason it still says  [-Werror=uninitialized]?

**Comment by divx118** [comment]
You shouldn't enable the Werror flag. See https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
After you changed the base.config did you run
 ```
$ ./chromeos/scripts/prepareconfig chromeos-exynos5
$ make oldconfig
```
If you didn't run those commands again the config didn't get updated so you would still get that error.

**Comment by lyons88** [comment]
Ok, thanks divx, running prepareconfig and make oldconfig again worked, and I can confirm that when I built my own header, it included many headers that weren't in your packaged headers.

**Comment by divx118** [comment]
@lyons88 Nice
