### ISSUE TITLE
Shows Error when booting into Crouton

### ISSUE THREAD

**Issue by GERMANGSG9** [dnschneid/crouton#3027]
Hi y´all,
I tried to install crouton on my asus c100p- It looked like if it worked out well but when I tried to start Linux with # sudo startxfc4, it showed me (after typing in the password) a black screen and the error: "unable to contact settings server"
 "//bin/dbus-launch terminated abnormally with the following error: EOF in dbus- launch reading adress from bus daemon"
After I hit "close" it showed me following Error:
"Unable to load a failsafe session"
"Unable to determine failsaife session name. Possible causes: xfconfd isn´t running (D-Bus setup problem) ; environment variable $XDG_CONFIG_DIRS is set incorrectly or xfce4-session is installed incorrectly"

Can somebody help me please and tell me what to to? I´m a newbie and have no idea what I should do... Start all over and wipe it off so I can reinstall it?
Thanks,
Ben

**Comment by DennisLfromGA** [comment]
@GERMANGSG9,

If you're using the 'precise' release, you may want to look at this: https://github.com/dnschneid/crouton/issues/2970#issuecomment-270053222

*Hope this helps,*
-**DennisL**

**Comment by GERMANGSG9** [comment]
I´m sorry but I´m not sure what you mean- I got to install Arch on my Asus Chromebook Flip but it was to difficult to work with (at least for a newbie). I may have found the problem. Later it downloads several stuff, but right at the beginning it shows, that it failed to download some packages (I checked the internet connection but it´s working perfectly):
ARNING: USB booting is enabled; consider disabling it.
WARNING: Legacy booting is enabled; consider disabling it.
WARNING: Signed boot verification is disabled; consider enabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_legacy=0 dev_boot_signed_only=1
Installing precise-armhf chroot to /usr/local/chroots/precise
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2017-01-19 18:25:00 URL:http://mirror.unitedcolo.de/debian/pool/main/d/debootstrap/ [6713/6713] -> "-" [1]
Downloading debootstrap version 1.0.87...
2017-01-19 18:25:02 URL:http://debian.mirror.net-d-sign.de/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/precise/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/precise/InRelease

(Some more Retrying)

W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/precise/InRelease
W: http://ports.ubuntu.com/ubuntu-ports/dists/precise/InRelease was corrupt
I: Retrieving Release 
I: Retrieving Packages


After that it seems to work. So maybe that´s the problem?
Thanks!:)

**Comment by DennisLfromGA** [comment]
@GERMANGSG9,

> I may have found the problem. Later it downloads several stuff, but right at the beginning it shows, that it failed to download some packages (I checked the internet connection but it´s working perfectly):
...
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/precise/InRelease
W: http://ports.ubuntu.com/ubuntu-ports/dists/precise/InRelease was corrupt
...

> After that it seems to work. So maybe that´s the problem?
Thanks!:)

I'm not sure what the current status of your chroot is exactly but if it's now working then all's well that ends well. If it's not working then a crouton update might fix it, use: `sudo ~/Downloads/crouton -u`

If that doesn't work then you might want to try a different Ubuntu release like I mention here: https://github.com/dnschneid/crouton/issues/2970#issuecomment-270053222

*Hope this helps,*
-**DennisL**
