### ISSUE TITLE
Keyboard layout inside xiwi launched apps

### ISSUE THREAD

**Issue by Roaders** [dnschneid/crouton#3028]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: unity,xiwi,keyboard,cli-extra,touch,chrome
host: version 9150.0.0 (Official Build) dev-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jan 4 03:28:45 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

Hi All

I have setup my chroot pretty successfully and it's all good - except for keyboard layout.
I have set the correct keyboard layout in unity and when running in unity it's fine.

However when I launch visual studio code:

`sudo start xiwi -b code`

The keyboard is not right, I go to type an @ and I get a ".

Any tips on how to solve this?

Many thanks

**Comment by GiowGiow** [comment]
Tried putting "setxkbmap layout (the layout you want)" on **~/.xiwirc** and it didn't work, this was supposed to be the official method.
