### ISSUE TITLE
Trusty fails to load on Dell Chromebook 13 after update

### ISSUE THREAD

**Issue by mattbreeden** [dnschneid/crouton#3030]
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xiwi
host: version 8872.76.0 (Official Build) stable-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Fri Jan 6 23:49:10 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
Can no longer load into trusty/i3 on my Dell Chromebook 13. I've looked through and tried a lot of misc solutions on other issues without success- trying xiwi, editing the /usr/share/x11 configs. I'm unsure the actual error, I've gotten both dbus and ioports issues.

When trying to launch it also makes the chromebook unresponsive except for the power button, though the log continues to display in. Because of this, I have been unable to get at the /tmp Xorg log.

**Comment by DennisLfromGA** [comment]
@mattbreeden,

I also have a Dell Chromebook 13 (lulu) with the broadwell processor.

I haven't tried i3 on my trusty chroot but lxde-desktop works fine with the '[uxa](https://github.com/dnschneid/crouton/issues/2923#issuecomment-268418795)' tweak.
I've also used the '[glamor modesetting](https://github.com/dnschneid/crouton/issues/2917#issuecomment-269906678)' tweak and it seems to work too.

Keep in mind that if you run a crouton update you may have to re-tweak your 'xorg' file(s).

'xiwi' still works fine without any changes.

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment]
@mattbreeden,

Using my 'trusty' chroot I just launched an 'xorg/i3' window using `sudo enter-chroot xinit /usr/bin/i3` and a 'xiwi/i3' window using `sudo startxiwi xinit /usr/bin/i3` and was able to open a terminal session in each so it seems to work in my configuration.

*Hope this helps,*
-**DennisL**

**Comment by mattbreeden** [comment]
Ah, super embarrassing. I just needed to update Crouton, thought I already had. With crouton updated I didn't even need any config tweaks.

Really appreciate all your hard work on my and everyone else's issues @DennisLfromGA !

**Comment by DennisLfromGA** [comment]
No problemmo, all's well that ends well...
