### ISSUE TITLE
Chromebook crashing whenever I try to run a crouton environment

### ISSUE THREAD

**Issue by notebookowner5** [dnschneid/crouton#3031]
```
chronos@localhost / $ sudo edit-chroot -all
name: debian
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/debian...
crouton: version 1-20161129162558~master:5f2f11f9
release: jessie
architecture: amd64
xmethod: xorg
targets: kde
host: version 9150.0.0 (Official Build) dev-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jan 4 03:28:45 PST 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/debian...
```

#### Whenever I try to `sudo startkde` the machine crashes. Installation of the environment however seemed to succeed.

If anyone has any thoughts on how I might get up and running in KDE, I'd be much appreciative.

**Comment by doriclazar** [comment]
If you really want to use xorg, you can try running:
`echo 'exec startkde' > ~/.xinitrc` inside your chroot, 
and then run `startx`, or `sudo startx` if running as chronos.

I would suggest running with [xiwi](https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)) instead. It's not hard to set up:
1. Install [crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom).
2. Add xiwi to your chroot.
`sudo crouton -u -t xiwi -n debian`
3. Run your environment:
`sudo startkde -X xiwi-tab`

**Comment by drinkcat** [comment]
@smibarber : Is kde on jessie supposed to work?
