### ISSUE TITLE
E: Unable to locate package xserver-xorg-input-vmmouse

### ISSUE THREAD

**Issue by SnarkBoojum** [dnschneid/crouton#3034]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20161129162558~master:5f2f11f9
release: sid
architecture: armhf
targets: lxde,keyboard,xorg
host: version 9150.0.0 (Official Build) dev-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jan 4 03:01:11 PST 2017 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

#### Please describe your issue:

The chroot setup can't finish, because it's trying to do something with xserver-xorg-input-vmmouse, a package it can't find.

#### If known, describe the steps to reproduce the issue:
Just try to create a chroot:
 sudo sh ~/Downloads/crouton -r sid -u -t lxde,keyboard,xorg

**Comment by SnarkBoojum** [comment]
For others getting the same problem, until that is really fixed in crouton, you can force things by doing:
`sudo enter-chroot -u 0 -n sid`
this will get you a root shell, allow you to edit /setup.sh (or some such -- a shell script at the root) to remove the line mentioning the *vmmouse package (don't forget to remove the continuation backslash at the previous line too!) ; then get out and:
`sudo enter-chroot` 
will ask to finish the setup, and answering 'yes' will actually work.

**Comment by DennisLfromGA** [comment]
@SnarkBoojum,

Thanx for the workaround.

It looks like it's coming from [xorg#L189](https://github.com/dnschneid/crouton/blob/master/targets/xorg#L189), maybe it is not valid with the 'sid' / 'arm' combo ???

Perhaps some more conditionals will have to be added once the devs get a chance to look at it.

*Hope this helps,*
-**DennisL**

**Comment by msturgill** [comment]
This also occurs with the stretch target, but the same work around applies (modify prepare.sh, etc).

**Comment by divx118** [comment]
As a reference https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831420 xserver-xorg-input-vmmouse package is obsolete. This will also affect newer ubuntu releases (need to check which). Checked Kali-rolling it is also missing the package.
Should be labelled as a crouton bug.

**Comment by divx118** [comment]
@SnarkBoojum @msturgill Can one of you please post the error messages you get with xserver-xorg-input-vmmouse . I can't replicate it on amd64 and I don't have an arm based chromebook. It will be trying to [remove xserver-xorg-input-vmmouse](https://github.com/dnschneid/crouton/blob/master/targets/xorg#L194), but maybe for some reason when doing that it errors out on arm.

**Comment by SnarkBoojum** [comment]
Well, the error message is that the package doesn't exist anymore ; if you look [here](https://packages.qa.debian.org/x/xserver-xorg-input-vmmouse.html), you'll see it is gone from testing, unstable and experimental : it won't be in the next stable. My guess is that you can't replicate because you try to install the current stable, which is the last one to have it.

**Comment by divx118** [comment]
@SnarkBoojum On amd64 it works ok. It does see that the package doesn't exists and ignores uninstalling just fine and continues the install script. I need the exact error messages that it spits out on arm, so we can fix it in crouton. It should not error out on a non existing package trying to uninstall.

**Comment by cjfh** [comment]
E: Unable to locate package xserver-xorg-input-vmmouse
Failed to complete chroot setup.

The armhf package for xserver-xorg-input-vmmouse doesn't exist.
