### ISSUE TITLE
Bluetooth in the crouton environment

### ISSUE THREAD

**Issue by aanastasiou** [dnschneid/crouton#3036]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161116131524~master:9db73043
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 8872.76.0 (Official Build) stable-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Fri Jan 6 23:48:52 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
(Just a note, the name of the chroot is precise but the installed version is trusty.)

I cannot understand bluetooth while within crouton and as a result of this, I cannot get bluetooth to work. I understand that, to an extent, crouton has to "interface" with chromeOS' existing buetooth system but no matter what I have tried, the bluetooth daemon fails to start from within Trusty.

I plugged an external USB Bluetooth adapter that I know that it works with Linux, hoping that I could control that one independently but the two distros are using the same kernel, so that is not going to work. `lsusb` shows the device but `hcitool` does not. In addition, `modprobe btusb` returns nothing but that could be due to the way crouton works with chromeOS. `bluetoothctl` is not available from within crouton but it is on chromeOS (and is working fine too with the builtin hardware).

I can see that there are hints towards solutions here and there and that bluetooth seems to work in some hardware + software combinations but not others (?)

Would it be possible for someone more knowledgable to put up a wiki page on how does bluetooth work from within crouton? Is it just a matter of renaming some interface so that the existing bluetooth subsystem is picked up by crouton or is it something more complex?

#### If known, describe the steps to reproduce the issue:
The problem manifests itself on a Dell Chromebook 11 with crouton which has been updated to Trusty

**Comment by DennisLfromGA** [comment]
@aanastasiou,

> **name: precise**
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161116131524~master:9db73043
**release: precise**

Your chroot still thinks the 'release' is `precise` too???

-**DennisL**

**Comment by drinkcat** [comment]
Yeah, there is something weird with the release, a chroot update might help.

For the original question, I'm not sure how Bluetooth is supposed to work in crouton, see #437 for a long-standing issue on the topic...
