### ISSUE TITLE
Error when executing "sudo startxfce4"

### ISSUE THREAD

**Issue by harmonioushedgehog** [dnschneid/crouton#3037]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xfce
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xfce...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: x11,gtk-extra
host: version 8872.76.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13437-g2bea612c #1 SMP PREEMPT Fri Jan 6 23:53:17 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xfce...

#### Please describe your issue:
Attempting to install linux system onto Acer chromebook 14 (Intel Celeron N3160 Quad-Core Processor) using guide provided by lifehacker. Installation of crouton seems to be okay, but I'm unable to open xfce.

#### If known, describe the steps to reproduce the issue: 
1) downloaded crouton install file from GitHub on 1.23.17

2) Entered "chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t x11,gtk-extra -n xfce"
Note: this was not my first attempt (I spent a few hours last night and this morning troubleshooting following an installation ran as "chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t xfce") I removed previous installations "chronos@localhost / $ sudo delete-chroot precise"

3) a.Specified username and set UNIX password as prompted.
b.Recieved following message: 
"Here's some tips:

Audio from the chroot will now be forwarded to CRAS (Chromium OS audio server),
through an ALSA plugin.

Future Chromium OS upgrades may break compatibility with the installed version
of CRAS. Should this happen, simply update your chroot.

You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.

Unmounting /mnt/stateful_partition/crouton/chroots/xfce...
Done! You can enter the chroot using enter-chroot."

 5) a. entered: "chronos@localhost / $ sudo startxfce4"
 b.entered previously specified password
 c.recieved following message:
"No chroots with target 'xfce' found in /mnt/stateful_partition/crouton/chroots"

7) a. attempted to execute 'startxfce4' from inside chroot by entering:
"chronos@localhost / $ sudo enter-chroot"
b. entered previously specified password
c. recieved following output: "Entering /mnt/stateful_partition/crouton/chroots/xfce...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1"

**Comment by DennisLfromGA** [comment]
@harmonioushedgehog,

> Entered "chronos@localhost / $ sudo sh -e ~/Downloads/crouton -t x11,gtk-extra -n xfce"

You named your chroot 'xfce' by specifying the '-n xfce' option to crouton but you didn't specify the 'xfce' target/desktop. It's easy to fix though, just *update* your chroot using the following:

`sudo ~/Downloads/crouton -n xfce -t xfce -u`

That will install the plain vanilla 'xfce4' desktop (Approx. 250MB).
For an 'xfce4' desktop with a few more bells & whistles (Approx. 1200MB), use `-t xfce-desktop` instead.

Then you'll be able to launch it using: `sudo startxfce4`

*Hope this helps,*
-**DennisL**

**Comment by harmonioushedgehog** [comment]
Thank you! I followed your suggestion to use the 'trusty' release and things appear to be in order now.

**Comment by DennisLfromGA** [comment]
_**Awesome! 🥇**_
