### ISSUE TITLE
Failing to install trusty/precise, keyring not available and failing InRelease download.

### ISSUE THREAD

**Issue by WeberMen** [dnschneid/crouton#3038]
#### Please describe your issue:
Trying to install trusty with `sudo sh ~/Downloads/crouton -t xfce -r trusty` and when I hit enter I receive: `Downloading latest crouton installer...
######################################################################## 100.0%
Installing trusty-amd64 chroot to /usr/local/chroots/trusty
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2017-01-24 20:31:31 URL:http://mirrors.linux.iu.edu/linux/debian/pool/main/d/debootstrap/ [4369/4369] -> "-" [1]
Downloading debootstrap version 1.0.87...
2017-01-24 20:31:31 URL:http://mirrors.linux.iu.edu/linux/debian/pool/main/d/debootstrap/debootstrap_1.0.87.tar.gz [65875/65875] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
W: http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease was corrupt`

This is followed by all of the regular install gibberish, and it ends the install successfully without presenting any other errors except for the ones posted. When trying to start xfce it gives some error about bus something and other stuff I can't remember, but I have tried installing trusty and precise and they have both had the same outcome. 

#### If known, describe the steps to reproduce the issue:
Seems like just trying to install anything in crouton right now reproduces this.

**Comment by WeberMen** [comment]
Closing this, retried with trusty ~10 times, and it just worked. It still failed the download, but it just worked.

**Comment by bothandeach** [comment]
Why closed?  I've been trying for a week!
