### ISSUE TITLE
X initialization fails with permissions error while trying to enter-chroot

### ISSUE THREAD

**Issue by cspoleta** [dnschneid/crouton#3039]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161129162558~master:5f2f11f9
release: xenial
architecture: amd64

#### Please describe your issue:

Startup command:
/bin/bash -c 'exec sh -e /usr/local/bin/enter-chroot -t gnome exec xinit /usr/bin/mate-session'

Above command line, which has started up the desktop without problems 100 times before has suddenly stopped working correctly and falls into an infinite loop during X initialization with the error:

Error: "dconf-CRITICAL: unable to create file '/home/cvs/.cache/dconf/user': Permission denied. dconf will not work properly".

#### If known, describe the steps to reproduce the issue:

NB:

home is ~cvs
~/.cache/dconf/ is owner cvs.cvs, mode 600
~/.cache/dconf/user is owner root.root, mode 600, size 2 bytes
~/.cache/dconf/user contents, piped to od -c, are:

    0000000 \0 \0
    0000002

**Comment by DennisLfromGA** [comment]
@cspoleta,

I haven't run into that error before but if your permissions get hosed you can usually fix things by doing the following:

    sudo enter-chroot
    sudo chown -R 1000:1000 "$HOME"

It might help in your situation.

*Hope this helps,*
-**DennisL**
