### ISSUE TITLE
how to download crouton

### ISSUE THREAD

**Issue by bro9** [dnschneid/crouton#3041]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
 sudo edit-chroot -all
#### Please describe your issue:

i have my chromebook in developer mode but whenever i try to download crouton it always says "file type is not supported. Please search the chrome web store for an app that supports this type of file." I try to find an app but cannot find one.

**Comment by HellzAngel86** [comment]
Same here. Only when I use that command it says command not found

**Comment by SneakyBastardSword** [comment]
instead of clicking on the file in the file manager, go into crosh by pressing ctrl+alt+t. Then type `shell` to bring up the bash prompt. From there, type `sudo sh ~/Downloads/crouton -e -r [distro name] -t [desktop manager name]`. You can find supported distro and desktop environment names by using `sudo sh ~/Downloads/crouton -r help` and `sudo sh ~/Downloads/crouton -t help` respectively.

**Comment by bro9** [comment]
I did that, but now what do i do??

**Comment by DennisLfromGA** [comment]
Spend a few moments reading this: [Usage](https://github.com/dnschneid/crouton#usage)

**Comment by bro9** [comment]
is there an app in the chrome web store that helps me open unsupported files?

**Comment by DennisLfromGA** [comment]
@bro9, 

No.

*Hope this helps,*
-**DennisL**

**Comment by bro9** [comment]
Oh, ok.

**Comment by G3zz** [comment]
@bro9 so did you run the command successfully? If so, then you can just follow the instructions and run the the chroot startup script inside a shell.

**Comment by DennisLfromGA** [comment]
@bro9,

Please take another look at @SneakyBastardSword's [comment](https://github.com/dnschneid/crouton/issues/3041#issuecomment-275103472) and the [README](https://github.com/dnschneid/crouton/blob/master/README.md), your questions are addressed there.

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by bro9** [comment]
Sorry, my whole computer was shut down for a bit. I'm going to be done
messing with it. No need to reopen issue though. Thank you for helping me
through the steps. I got as far as putting it into developer mode.
