### ISSUE TITLE
chronos@localhost / $ sudo apt-get install git sudo: apt-get: command not found

### ISSUE THREAD

**Issue by Jungeh** [dnschneid/crouton#3043]
```
Please paste the output of the following command here: sudo edit-chroot -all

```
chronos@localhost / $ sudo edit-chroot -all
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20170124013033~c161e9c1
release: kali-rolling
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi
host: version 8872.76.0 (Official Build) stable-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Fri Jan 6 23:44:58 PST 2017 armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8872.76.0 (Official Build) stable-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Fri Jan 6 23:44:58 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by r4d1n** [comment]
It looks like you may be running the command from the ChromeOS shell, rather than the shell of the Linux install inside your chroot.

**Comment by DennisLfromGA** [comment]
@r4d1n, Nice catch, I totally missed that...

**Comment by Jungeh** [comment]
Thank you so much its working

**Comment by DennisLfromGA** [comment]
Awesome 🥇

**Comment by gh4one** [comment]
hey  can you tell me why i cant download kali or that it keeps asking for a passwd or how to reset passwd

**Comment by DennisLfromGA** [comment]
@gh4one,

See this related issue comment for a possible workaround - and *please* don't hijack someone else's issue/thread with an unrelated question -
- https://github.com/dnschneid/crouton/issues/4153#issuecomment-560190450

-**DennisLfromGA**

**Comment by ShamoneyX** [comment]
Hello people of GitHub i need help trying to update using the developer console using ctrl+alt+f2 or foward i logged in then i try updating the system using sudo apt-get install or sudo apt-get update and even sudo apt-get upgrade it didn't wprk then i tried sudo edit-chroot -all and sudo enter-chroot and it didn't work can anyonee help me with this???

**Comment by DennisLfromGA** [comment]
@ShamoneyX,

See this previous comment:
- https://github.com/dnschneid/crouton/issues/3043#issuecomment-275457972

-**DennisLfromGA**

**Comment by cressat** [comment]
please i use chromebook with chrome os, and anytime that i enter command and type shell and want to use sudo account it ask of password whilst i have not st a password. Please can someone help me?

**Comment by DennisLfromGA** [comment]
@cressat,

Please don't hijack topics that don't pertain to your issue.

Take a look at this https://github.com/dnschneid/crouton/issues/2050#issuecomment-348382431 for help with *your* issue.

*Hope this helps,*
-**DennisLfromGA**
