### ISSUE TITLE
After installing kali tools 

### ISSUE THREAD

**Issue by Jungeh** [dnschneid/crouton#3044]
```
Please paste the output of the following command here: sudo edit-chroot -allchronos@localhost / $ sudo edit-chroot -all
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20170124013033~c161e9c1
release: kali-rolling
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi
host: version 8872.76.0 (Official Build) stable-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Fri Jan 6 23:44:58 PST 2017 armv7l GNU/Linux
freon: no
Not unmounting /mnt/stateful_partition/crouton/chroots/kali as another instance is using it.
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8872.76.0 (Official Build) stable-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Fri Jan 6 23:44:58 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

```

#### If known, describe the steps to reproduce the issue:
chronos@localhost / $ sudo startxfce4 -n kali
Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/bin/startxfce4: Starting X server

(EE) 
Fatal server error:
(EE) 
Invalid argument for -logfile - "/tmp/Xorg.crouton.2.log"
        With elevated privileges -logfile must specify a relative path
        without any ".." elements.

(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) 
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/kali as another instance is using it.

**Comment by dnschneid** [comment]
#2875
