### ISSUE TITLE
Coding Issue

### ISSUE THREAD

**Issue by joshuagrant731** [dnschneid/crouton#3045]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

I am using R markdown and I need to change the words atmos and nasaweather into monofonts using backticks.  My code doesn't work for some reason.  Can you help

Code here: 

## Data

The  `{r}  paste("atmos")` data set resides in the  `{r} paste("nasaweather")` package of the *R* programming language. It contains a collection of atmospheric variables measured between 1995 and 2000 on a grid of 576 coordinates in the western hemisphere. The data set comes from the [2006 ASA Data Expo](http://stat-computing.org/dataexpo/2006/).

**Comment by DennisLfromGA** [comment]
@joshuagrant731, 

I don't believe this is a 'crouton' issue.

But, we're here to help. 😀 
A couple of links that might be of guidance -
- [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
- [R Markdown links](https://goo.gl/3VjncS)

*Hope this helps,*
-**DennisL**
