### ISSUE TITLE
gandof synclient settings incorrect

### ISSUE THREAD

**Issue by qtv** [dnschneid/crouton#3046]
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome,extension
host: version 9000.66.0 (Official Build) beta-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Jan 17 21:54:23 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
With gnome-ubuntu the mouse barely works - requires a hard click to actually register a click. No right click works (two finger tap) and it would be nice to have just a tap-click like I had on lubuntu/native ChromeOS.

**Comment by tomcannady** [comment]
Add this to your start-up or run at the command prompt (ctl+alt+t) 
$> synclient FingerLow=1 FingerHigh=5

**Comment by qtv** [comment]
I'd try that but now having other issues with the chroot, namely _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root and xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted), whatever it is is limiting me getting into the chroot. Looks like I will have to reinstall and try out your fix.

**Comment by drinkcat** [comment]
See #2891.
