### ISSUE TITLE
Cannot update Chroot

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#3047]
Please help: :-(
No chroots found in /mnt/stateful_partition/crouton/chroots

**How do you specify to crouton where your chroot folder is in order to update crouton?**
I installed this before using a directory other than the default directory..

However I don't remember the command i used to do this...

When I type...
**sudo sh ~/Downloads/crouton -u -t** 

my chroot folder (Debian Stretch) is located in..
**/home/linux/chroots/**

I can enter my chroot by doing this:
**sudo enter-chroot -c /home/linux/chroots**

However I am not sure how to update the chroot in this case....

If I type:
**sudo sh ~/Downloads/crouton -u** 

I get the following error message:
**No chroots found in /mnt/stateful_partition/crouton/chroots
/usr/local/chroots/precise does not exist; cannot update.**

Can anyone tell me what the appropriate syntax is to make the crouton update work? I have no idea. :(

**Comment by syitong** [comment]
```bash
sudo sh -e path/to/crouton -u -n yourchroot -p path/to/chroots
```

**Comment by Carl393** [comment]
Thank you so much!!!!
