### ISSUE TITLE
can't get real time audio privileges on Asus Chromebook

### ISSUE THREAD

**Issue by ZestieBumwhig** [dnschneid/crouton#3048]
Please paste the output of the following command here: sudo edit-chroot -all
```
name: testy
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/testy...
crouton: version 1-20161129162558~master:5f2f11f9
release: jessie
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8872.76.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Fri Jan 6 23:43:39 PST 2017 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/testy...
name: yakkety
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/yakkety...
crouton: version 1-20161129162558~master:5f2f11f9
release: yakkety
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi,audio
host: version 8872.76.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Fri Jan 6 23:43:39 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/yakkety...
```

#### Please describe your issue:
I cannot get Crouton / Jack to have real-time priority.
I am PRETTY sure that it used to work...
but it's been since November (two months ago), so it's possible - but unlikely - that I'm wrong.

I've followed the instructions (which I've followed before) for re-routing Jack / qjackctl to cras.
Sound works, but without RT... which leads to Xruns in some pretty minor SuperCollider patches.

I've tried this:
https://github.com/dnschneid/crouton/wiki/Access-audio-hardware-directly-(ALSA,-JACK)
... and this:
https://github.com/dnschneid/crouton/wiki/Full-Blown-Audio-Video-Workstation-using-KDE-chroot-and-KXStudio
... and have had no success. I've tried Debian and Ubuntu, various versions, always with the same result.

Has there possibly been some change to ChromeOS to break this workaround?
(User error is far more likely, of course.)
This is an Asus C-100P with Arm processor, if that is possibly affecting things.

Coincidence or not? This happened when I installed Chromecast on this Chromebook.
Since then, I've done a powerwash, and also set up the ChromeOS with a different gmail account (b/c Cast seemed to still be associated with the account, not the physical computer).
But I still can't get real-time privileges.

I'd really appreciate any help.
It's VERY possible that I've overlooked something obvious that I got right the first time (six months ago), but I've been wrestling with this for months now, with no success.

**Comment by socalledsound** [comment]
Having similar problem with realtime audio on a pixelbook as of chrome os Version 77.0.3865.18.  Supercollider stutters with one sin oscillator.
