### ISSUE TITLE
Extracting mean rainfall data from netcdf file inside shapefile using python

### ISSUE THREAD

**Issue by John277** [dnschneid/crouton#3052]
I have netcdf file and I want to extract mean rainfall data within shapefile boundary. The shapefile contains 3 features, I have started as follows:

```
from netCDF4 import Dataset
import numpy as np
import geopandas as gpd
from osgeo import ogr
```

# then I can access or slice variables from netcdf
```
dataset = Dataset('mynetcdf.nc')
long = dataset.variables['lon'][:]
lati = dataset.variables['lat'][:]
rainfall = dataset.variables['pr'][:]
```

> Until this it is fine and working, I can see the data:

> Now the next step is to read shapefile and extract the above variables (long, lati, rainfall) for inside the shapefile. I know I can read shapefile using ogr or geopandas but I don't know how to continue afterwards

```
shapfile 1 = gpd.read_file('myshapefile.shp'), or using ogr
shapefile 2 = ogr.open('myshapefile.shp',0)
```

> Another issue is there is a lot of netcdf files and the extraction has to go through each file (loop) and the process will get slow as some stage and I am looking solution that will extract for each 3 features as fast as possible and I thought Python could be possible solution.
> Thanks for your help!

**Comment by DennisLfromGA** [comment]
@John277,

It looks like you've posted this *same* [issue](https://github.com/Unidata/netcdf4-python/issues/634) on the 'netcdf4-python' site. 
Since it's not a 'crouton' problem per say, I suggest you track it there.

*Hope this helps,*
-**DennisL**
