### ISSUE TITLE
Consistent hard-crash (immediate power off?) from within Crouton

### ISSUE THREAD

**Issue by ramses0** [dnschneid/crouton#3054]
```
$ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 8872.76.0 (Official Build) stable-channel chell 
kernel: Linux localhost 3.18.0-13437-g2bea612c #1 SMP PREEMPT Fri Jan 6 23:52:09 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:

Crouton installed and trusty chroot running `i3` WM, probably `gnome-terminal`, `google-chrome` (hidpi) and nothing else.  Somehow I've gotten it so that running a shell script that does nodejs build stuff (JS transpile, template compilation, css / js minification) causes the machine to basically power off immediately.

It's tough to repro and figure out exactly _what's_ causing it, but I'm *in* the chroot, fresh, started up google chrome, run my build process (which I'd previously run for several months on the same hardware and a previous chromebook) and bam.  Black screen.  I thought the battery had died, but nope... full battery, turn on, get "Chrome Developer Mode" (Ctrl-D) danger screen and was able to immediately cause it again. (???) 

#### If known, describe the steps to reproduce the issue:

It seem to consistently repro, but I'll try and figure if it's a particular command which is causing it, but it's "costly" to repro as it takes time to reboot and start the chroot up again.  Wanted to log the issue asking for help on how to get appropriate logs to better report / diagnose this issue.  Thanks!

#### $ cat /proc/cpuinfo 
(CPU 1 of 4 shown here)
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 78
model name      : Intel(R) Core(TM) m7-6Y75 CPU @ 1.20GHz
stepping        : 3
microcode       : 0x8a
cpu MHz         : 753.984
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat pln pts dtherm hwp hwp_noitfy hwp_act_window hwp_epp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1
bugs            :
bogomips        : 2400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

**Comment by ramses0** [comment]
...has also occurred with `-X xiwi`, no thermal or processor load to speak of (6m uptime is post-crash, I know, but literally, I have 5-10 xterms open, a node transpiler and google chrome running)

```
$ cat /sys/devices/virtual/thermal/thermal_zone0/temp
38000
$ uptime
 21:23:44 up 6 min,  0 users,  load average: 0.82, 0.87, 0.44
```

**Comment by dnschneid** [comment]
It shuts down without going back to the dev screen automatically?  Is /dev/pstore/console-ramoops recent?

**Comment by ramses0** [comment]
Just happened again... `pstore` seems to be empty (this is ChromeOS side of things(?)), 

```
chronos@localhost ~ $ cd /dev/pstore/
bash: cd: /dev/pstore/: Permission denied
chronos@localhost ~ $ sudo bash
localhost u-025...79d # cd /dev/pstore/
localhost pstore # ls -al
total 0
drwx--x---.  2 root debugd    0 Mar  8 01:55 .
drwxr-xr-x. 16 root root   2160 Mar  8 01:55 ..
localhost pstore #
```

This has happened 2-3 times since reporting, with usage of max 2hrs per day, ~2-3 days per week doing basic JS/node development in a crouton/ubuntu/trusty "subshell", using -X xiwi.

Generally coincidental with build activities, doesn't feel like thermal issues, although I'd love to get some info on how to try troubleshooting beyond pstore-ramoops.  # processes active in crouton were 4 workspaces (i3 wm), `google-chrome`, 8 terminal windows, 5 vim sessions, and 1 node / webpack session.

/var/log/messages doesn't have anything obvious glancing through it, if you can point me in the right direction as to what to look for I'll look for it the next time it occurs.  Thanks!

**Comment by drinkcat** [comment]
This might be a Chrome OS issue, can you try updating Chrome OS (you should get R56-9000.91.0 on stable channel now, R57 might actually be better but you might need to switch to beta channel) and check again?

**Comment by ramses0** [comment]
```Version 56.0.2924.110 (64-bit)
Platform 9000.91.0 (Official Build) stable-channel chell
ARC Version 3756504
Firmware Google_Chell.7820.215.0
 
Your Chromebook is up to date.```

...it has been happening less frequently- I'm rebooting now due to some sort of crouton-lockup (mostly non-responsive to mouse/keyboard input, so I'm killing the crouton window and rebooting in case of process detritus).  Will keep trying to catch it in the act if you can think of any other ways of getting data on it (or is `pstore` going to be the only area which is worth investigating?).

**Comment by ramses0** [comment]
Google Chrome	57.0.2987.137 (Official Build) (64-bit)
Revision	0
Platform	9202.60.0 (Official Build) stable-channel chell
ARC	3852170

...another hard crash after running `npm install`
