### ISSUE TITLE
trusty, precise and others fetching from InRelease - 404

### ISSUE THREAD

**Issue by xorb0ss** [dnschneid/crouton#3058]
I've been trying to install crouton but during setup, it's trying to fetch packages from `http://archive.ubuntu.com/ubuntu/dists/precise/InRelease`

Keep getting errors and nothing works.
The InRelease file has been deleted from the repo and I can't find it in any of the other mirrors either.

Any ideas?

**Comment by Edwardthedog2** [comment]
I get the same errors when installing crouton, however eventually the errors stop displaying and it continues the installation. Apparently InRelease is not actually required for installing Ubuntu (Precise or Trusty; they both install and work fine after).

**Comment by xorb0ss** [comment]
@Edwardthedog2 When you say, eventually, do you mean you just keep trying to install until it works?

For me I get told `prepare.sh can not be found` after I get InRelease errors...

**Comment by octopusnz** [comment]
You can see some wisdom about this issue here: #2966 
Not sure exactly what is getting stuck and where, but some people have reported success by just re-trying a few times.
