### ISSUE TITLE
Learn Python with visual output?

### ISSUE THREAD

**Issue by ariadnemazed** [dnschneid/crouton#3060]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

Hello. I'm not sure this is the place to ask, but after long searches on the Internet, I still couldn't find a proper answer. I want to learn Python, but after 2 failed attempts, I think some sort of visual output for my code practice would make a huge difference in terms of motivation. I found DrawBot and PlotDevice, but since I don't have a Mac OS X, these can't be of much help. So, what alternatives are there for Windows or what other suggestions do you have?
P.S. I want to try making some generative art further along the way using Python and other means (Nodebox, Processing), but to get there I still have/would like to learn Python _first_. I am also a total newbie when it comes to programming.

**Comment by DennisLfromGA** [comment]
Sorry, but this is not the place.
Take a look [here](https://goo.gl/XZ04DY) or [here](https://goo.gl/kyA1DS).
