### ISSUE TITLE
Error with Crouton Install Script - Xorg and xserver-xorg-video-modesetting

### ISSUE THREAD

**Issue by rwwishart** [dnschneid/crouton#3061]
```
Entering /mnt/stateful_partition/crouton/chroots/unity...
crouton: version 1-20161129162558~master:5f2f11f9
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,keyboard,unity
host: version 9000.82.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Feb 1 15:13:00 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/unity...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/unity...
```

#### Please describe your issue:
Following the recent Chrome OS update:
```
Version 56.0.2924.87 (64-bit)
Platform 9000.82.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.93.0

```
There now appears to be an error associated with the Crouton install / upgrade script. Prior to the recent Chrome OS update, this did not occur. I do not know if they are related, however. When the Crouton installer is run now, the shell outputs the following error:
```
Installing CRAS...
Installing target xorg...
xserver-xorg-video-intel was already not hold.
Installing dependencies for /usr/local/lib/croutonfreon.so...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libc6-dev is already the newest version (2.23-0ubuntu5).
libdrm-dev is already the newest version (2.4.70-1~ubuntu16.04.1).
libdrm-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/lib/croutonfreon.so...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package xserver-xorg-video-modesetting is a virtual package provided by:
  xserver-xorg-core-hwe-16.04 2:1.18.4-1ubuntu6.1~16.04.1
  xserver-xorg-core 2:1.18.4-0ubuntu0.2
You should explicitly select one to install.
E: Package 'xserver-xorg-video-modesetting' has no installation candidate
```

#### If known, describe the steps to reproduce the issue:
Running upgrade script `sudo sh ~/Downloads/crouton -n unity -u` will produce this error.
I have verified that it occurs on a fresh install with the same targets using the following code:
`sudo sh -e ~/Downloads/crouton -t xorg,xiwi,keyboard,unity -r xenial -e`

**Comment by TheReelDeal** [comment]
As of so far, Crouton does not fully support Utopic and newer Ubuntu versions. Try using Unity or something else.

**Comment by rwwishart** [comment]
@TheReelDeal Correct, I realize Xenial is not officially supported yet. Discussion elsewhere on the Wiki suggests support is a goal, however, given Xenial is the latest LTS release.

In trying to replicate the error, you are correct that `sudo sh -e ~/Downloads/crouton -t xorg,xiwi,keyboard,unity -r trusty -e` does not result in the same issue.

I am not familiar enough with Ubuntu internals to know where this problem originates. Note the following actions and responses from inside the chroot.
`sudo apt-get -s upgrade xserver-xorg-core`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xserver-xorg-core is already the newest version (2:1.18.4-0ubuntu0.2).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
`sudo apt-get -s upgrade xserver-xorg-core-hwe-16.04`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 xserver-xorg : Depends: xserver-xorg-core (>= 2:1.17.2-2)
 xserver-xorg-input-evdev : Depends: xserver-xorg-core (>= 2:1.17.99.902)
 xserver-xorg-input-synaptics : Depends: xserver-xorg-core (>= 2:1.17.99.902)
 xserver-xorg-input-wacom : Depends: xserver-xorg-core (>= 2:1.17.99.902)
 xserver-xorg-video-dummy : Depends: xserver-xorg-core (>= 2:1.17.99.902)
 xserver-xorg-video-intel : Depends: xserver-xorg-core (>= 2:1.17.99.902)
E: Broken packages
```
Am I correct in thinking that a check somewhere is not recognizing `xserver-xorg-core` is now at 2:1.18 and incorrectly returning an error?

**Comment by c-f-h** [comment]
I'm having the same problem while updating a xenial chroot.

I'm still on ChromeOS 55 though:

```
Version 55.0.2883.105 (64-bit)
Platform 8872.76.0 (Official Build) stable-channel auron_yuna
ARC Version 3617689
Firmware Google_Auron_yuna.6301.59.8
```

I can still enter the chroot and start the X server. However I cannot toggle out of the chroot X server (screen goes black), and when I quit X, the screen goes black and I can't seem to get back into ChromeOS without hard rebooting.

Any help in resolving this would be greatly appreciated. I can't use Trusty because the old graphics driver version in Trusty has problems with my Intel graphics chipset.

**Comment by c-f-h** [comment]
I figured out a simple hack: in `target/xorg`, change this line

`modesetting="xserver-xorg-video-modesetting$backport,debian~sid+ubuntu~vivid="`

to this:

`modesetting="xserver-xorg-video-modesetting$backport,debian~sid+ubuntu~xenial="`

That's assuming you're trying to update/install a xenial chroot.

Then run `make` and use the produced `crouton` script instead of the one which downloads the latest installer.

It seems crouton isn't being maintained anymore...? That would be sad indeed.

**Comment by divx118** [comment]
@DennisLfromGA Can you mark this as a bug? We need to remove modesetting for sid and higher and for vivid and higher. Just need to look at if kali is also affected and xserver-xorg-video-modesetting is there also part of xserver-xorg-core
I encountered the same on a lars acer chromebook for work while trying to setup the chroot.

**Comment by rwwishart** [comment]
@c-f-h This solution worked for me just as you described. I updated the line replacing 'vivid' with 'xenial' and the script processed as before. Thanks for sharing this! I too hope the developers keep maintaining the project.

**Comment by DennisLfromGA** [comment]
@divx118,

Yes, no problem. 
I guess this would be an 'upstreambug' as opposed to a 'crosbug' or a crouton 'bug' ???

-**DennisL**

**Comment by Kalirren** [comment]
Hi, I'm new to maintaning linux in general. Where is targets/xorg? I'm trying to implement c-f-h 's fix and can't find the file to edit.

**Comment by DennisLfromGA** [comment]
@Kalirren,

Take a look at the README under the ['Usage' section](https://github.com/dnschneid/crouton#usage) where it talks about 'modifying crouton'.

*Hope this helps,*
-**DennisL**
