### ISSUE TITLE
<command> "not found" when redirecting output of xiwi

### ISSUE THREAD

**Issue by Huge** [dnschneid/crouton#3062]
```
name: trustyWithUnity
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trustyWithUnity...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: armhf
xmethod: xorg
targets: xorg,xiwi,unity-desktop
host: version 9202.12.0 (Official Build) dev-channel elm 
kernel: Linux localhost 3.18.0-13739-gbf5e73b #1 SMP PREEMPT Tue Jan 31 22:01:10 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trustyWithUnity as another instance is using it.
```

#### Please describe your issue:
When using qoutes as needed for enclosing the command to be run in Chrome GUI, which( said enclosing) I expect would be needed for proper output redirection ie. silencing in the example below. 
Also adding some -q/--quiet or -s/--silent option to xiwi would be nice and also solve my original problem.

#### If known, describe the steps to reproduce the issue:
iex. `xiwi "ssh -X host app" 1>/dev/null` 
  `xiwi: ssh -X remote firefox: not found` is what you will most likely see.

**Comment by dnschneid** [comment]
xiwi passes parameters individually, so `xiwi ssh -X host app` (i.e., no quotes) should work...as long as you don't need keyboard-interactive authentication.  If you do, you should wrap it in an xterm command: `xiwi xterm -e ssh -X host app`, and if you don't want the ugly xterm window all the time, you can make ssh fork, but you'll need to tell xiwi to stay alive: `xiwi -f xterm -e ssh -f -X host app`

**Comment by Huge** [comment]
Sure `xiwi ssh -X host app` works fine, it is the output redirection that is broken. I'd like to make `xiwi` give less output basically in that case.

**Comment by dnschneid** [comment]
throwing `&>/dev/null` after the command doesn't work?
