### ISSUE TITLE
Ubuntu Will Not Boot Properly

### ISSUE THREAD

**Issue by zmcase** [dnschneid/crouton#3063]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

If you could solve my problem - I will be eternally grateful.

I tried downloading ubuntu on my thinkpad chromebook. I typed in the following command after download:

sudo startunity

After, the page turned black and stayed black. I can right on the screen and a drop down menu comes up with no clickable options. A weird start menu is accessible but with limited access to files. I can not Cntrl + Alt + Arrow key or refresh key, Terminal wont start and the power button doesn't work. But if i leave the computer alone, it logs me out of ubuntu. so technically  i did something right and something wrong.

help please

**Comment by DennisLfromGA** [comment]
### Please paste the output of the following command here: sudo edit-chroot -all

**Comment by zmcase** [comment]
chronos@localhost / $ sudo edit-chroot - all

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: edit-chroot: command not found

**Comment by dnschneid** [comment]
#2923
