### ISSUE TITLE
Disable Auto Unmount

### ISSUE THREAD

**Issue by rober42539** [dnschneid/crouton#3067]
#### Please describe your issue:
I'd like to be able to disable automatic unmount so that apache and mysql keep running after I exit the chroot. However, I'm not wanting an auto-started chroot on chromeos boot - as I want to manually start both services, or anything else for that matter. What modifications would I need to do in order to make this work? I am looking a simple way to modify crouton or my chroot to accomplish this.

**Comment by DennisLfromGA** [comment]
@rober42539,

I think a couple of things might work for you -

1. There's a CROUTON_NO_UNMOUNT variable that can be set in your launch command that will prevent unmounting your chroot. You can prefix your 'start*' script or 'enter-chroot' with it similar to this:  

#####    `sudo CROUTON_NO_UNMOUNT=1 startxfce4`

2. Run your chroot in the background infinitely similar to this:

#####    `sudo enter-chroot -b sleep infinity`

Hopefully one of the methods above or something similar will fit your scenario.

*Hope this helps,*
-**DennisL**

**Comment by rober42539** [comment]
Awesome! Exactly what I needed... 👍
