### ISSUE TITLE
open vt consoles in a chroot

### ISSUE THREAD

**Issue by mjonsson1986** [dnschneid/crouton#3071]
are it not possible? e.g launch a desktop and open a vt console by ctrl+alt+f1 or will chromeos eat the keys?

**Comment by DennisLfromGA** [comment]
@mjonsson1986,

Not by using <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>f1</kbd>, that will normally place you back in CrOS.
You could use <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>f2</kbd> or possibly <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>f3/f4</kbd> to open a Developer console I believe.

But why, you can use multiple 'xterm's or another terminal emulator like 'guake' that let's you open multiple terminals in tabs in your chroot.

What is it exactly that you are trying to do?

*Hope this helps,*
-**DennisL**
