### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by MegaWalls** [dnschneid/crouton#3072]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
black screen
`chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Feb 1 15:00:25 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=500953d2-bb00-1441-a798-3537ee80bf2b/PARTNROFF=1 hashtree=PARTUUID=500953d2-bb00-1441-a798-3537ee80bf2b/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=276648fc097559d81f97d575edc1db257f942a23 salt=59105bf58b656b3f4e03c2bf91281c3ab8bf5bb0a7a9b8e827dfac5a58d4729f" noinitrd vt.global_cursor_default=0 kern_guid=500953d2-bb00-1441-a798-3537ee80bf2b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Feb 14 16:48:34 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.82.0 (Official Build) stable-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Feb 1 15:00:25 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:13810): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:13810): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
(II) AIGLX: Suspending AIGLX clients for VT switch
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported input device type.
thunar-volman: Unsupported input device type.
thunar-volman: Unsupported input device type.
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.
hexdump: /dev/input/event10: No such device
hexdump: /dev/input/event11: No such device
hexdump: /dev/input/event12: No such device
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported input device type.
thunar-volman: Unsupported input device type.
thunar-volman: Unsupported input device type.
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.
(II) AIGLX: Suspending AIGLX clients for VT switch`
#### If known, describe the steps to reproduce the issue:

NOTE: I know this can be solved by editing a file. change `/usr/share/X11/xorg.conf.d` to 
`Section "Device"
   Identifier "Intel Graphics SNA+TearFree"
   Driver     "intel"
   Option     "AccelMethod" "uxa"
   # Option     "TearFree"    "true"
EndSection`
BUT I don't know anything about linux commands so I can't edit it. Please help

**Comment by DennisLfromGA** [comment]
@MegaWalls,  

See @The1andONLYdave's https://github.com/dnschneid/crouton/issues/3016#issuecomment-279769020

*Hope this helps,*
-**DennisL**

**Comment by abc123me** [comment]
That solution didn't work for me

**Comment by RalphCorderoy** [comment]
@MegaWalls, use the `cd` and `ls` commands to move to the directory containing the file to edit. Use `vi foo` to edit the file foo using the editor vi. Using the `j` and `k` keys, lowercase, move to the line to edit. Use `h` and `l` to move along the line to the first character to delete. Delete the old text using `x`. This will probably leave and empty string with just double quotes: `""`. Position the cursor on the second. Type `i` to enter text-insert mode. Enter the new text, only use `backspace` for corrections. Type `esc` to exit insert mode. Type `:wq` and press Enter to write the file. Or use `:q!` and Enter to abort your edits.

**Comment by ahidalgob** [comment]
@DennisLfromGA tried this, (copying and without copying to /usr/share/X11/xorg.conf.d/) and didn't work. The bug changed though, now I get the black screen with a cursor, and if I go to chrome os and switch back to xubuntu the gui shows up but freezed.

Thanks :)

**Comment by drinkcat** [comment]
#2923
