### ISSUE TITLE
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory

### ISSUE THREAD

**Issue by OnARoel** [dnschneid/crouton#3073]
**Please paste the output of the following command here: sudo edit-chroot -all**
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: armhf
xmethod: xorg
targets: unity-desktop
host: version 9000.82.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Feb 1 14:52:30 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Please describe your issue:**
Can't boot into Unity, I've also tried xfce4, xiwi, no distro works for me, I always get the same error. I'm on an Asus C201, on the default channel with the latest update. I've had this problem for a couple months, one of the chrome os updates from a couple months ago stopped unity from working for me. I've tried fresh installs, wiping my chromebook and starting again, nothing works. 

**If known, describe the steps to reproduce the issue:**
I simply installed unity using: 
sudo sh -e ~/Downloads/crouton -t unity

And I attempt to start it using sudo startunity

Any help would be much appreciated.

**Comment by DennisLfromGA** [comment]
@OnARoel,

Try a newer supported release like 'trusty', similar to this:

`sudo sh ~/Downloads/crouton -r trusty -t unity`

*Hope this helps,*
-**DennisL**

**Comment by OnARoel** [comment]
I tried that last time and it didn't work, but I'll try it again. Also whenever I try to install crouton (Any flavor of it), I get the error: W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/trusty/InRelease

I've tried different mirrors but nothing ever seems to fix that, everything gets installed anyway, but obviously the black screen issue still comes up.

**Comment by DennisLfromGA** [comment]
@OnARoel,

If you get the 'blackscreen' issue, try one or more of the workarounds here: https://github.com/dnschneid/crouton/issues/3057#issuecomment-279196855

Or, simply use the 'xiwi' target/xmethod.

*Hope this helps,*
-**DennisL**

**Comment by OnARoel** [comment]
I'm now getting the issue of "_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root"
Is that the blackscreen issue?

**Comment by DennisLfromGA** [comment]
@OnARoel, 

Do you have a black screen?
Does it work otherwise?

-**DennisL**

**Comment by OnARoel** [comment]
No it doesn't work otherwise, and Yeah I get the blackscreen that flashes for a second then comes back, giving me the same "Owner" error.

**Comment by DennisLfromGA** [comment]
https://github.com/dnschneid/crouton/issues/3073#issuecomment-279808340

**Comment by OnARoel** [comment]
I tried the workarounds (All of them tell me to change that file), I saved the file. I tried to start unity regularly, and with the -X xorg flags, and it still gives me the same error.

**Comment by drinkcat** [comment]
See #2923.

**Comment by Fawwad1** [comment]
Here is what I did and that's resolved my issue.

mkdir -p /etc/selinux/targeted/contexts/
echo '<busconfig><selinux></selinux></busconfig>' > /etc/selinux/targeted/contexts/dbus_contexts

This fixed the issue. On my second server I was having the same issue but I changed the syntax a little bit and it just worked fine over there as well.

mkdir -p /etc/selinux/disabled/contexts/
echo '<busconfig><selinux></selinux></busconfig>' > /etc/selinux/disabled/contexts/dbus_contexts
