### ISSUE TITLE
Black screen since Chrome OS update (XFCE 14.04)

### ISSUE THREAD

**Issue by Benjadahl** [dnschneid/crouton#3074]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.82.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13527-gc2f2230 #1 SMP PREEMPT Wed Feb 1 15:01:31 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
Since my CB3-431 updated to the new version of chromeos, using the startxfce4 command has resulted in a black screen, with no response at all. Having to force restart. 

I have update all software in the chroot and also updated the chroot using the crouton script.

**Comment by DennisLfromGA** [comment]
@Benjadahl,

See https://github.com/dnschneid/crouton/issues/3057#issuecomment-279196855

And *please* use the [search feature](https://github.com/dnschneid/crouton/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20black%20screen%20) on this site to look for your issue before posting.

*Hope this helps,*
-**DennisL**
