### ISSUE TITLE
Console asks to start x

### ISSUE THREAD

**Issue by vinicfmor** [dnschneid/crouton#3075]
So, I have a samsung chromebook 3, and i already downloaded the chroot and setted up a user an a password, but when I go **ctrl alt left** and put "sudo startxfce4" It says me to start x on promp, but when i go on **ctrl alt T** an put "sudo startx " it just doesn't works..

What should I do??

(Pardon for my english if it has any errors, I'm Brazilian kkk)

**Comment by DennisLfromGA** [comment]
@vinicfmor,

1. First login to your account at the login screen
2. Then press <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>t</kbd> to open a crosh session
3. Then type `shell` and press <kbd>enter</kbd> to get a shell terminal session
4. Laslty enter `sudo startxfce4` to lanuch your desktop.

Using <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>F2</kbd> opens the Developer console and it is not recommended to lanuch a gui desktop from there.

*Hope this helps,*
-**DennisL**

**Comment by vinicfmor** [comment]
So, I did what you told me to do, but when i use the ``sudo startxfce4`` commad, my chromebook screen just goes black (I have a samsung chromebook 3)

**Comment by DennisLfromGA** [comment]
@vinicfmor,

Show us the output of: `sudo edit-chroot -all`

Also, if you are using the 'trusty' release just update your chroot using:

`sudo sh ~/Downloads/crouton -n trusty -u`

The latest crouton update fixes the black screen issue.

*Hope this helps,*
-**DennisL**
