### ISSUE TITLE
Can't enter LXDE, Black screen, happened after update

### ISSUE THREAD

**Issue by abc123me** [dnschneid/crouton#3076]
`sudo etit-chroot -all` output:
> name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20170214182546~master:163e0d26
release: precise
architecture: amd64
xmethod: xorg
targets: x11,lxde
host: version 9000.82.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13527-gc2f2230 #1 SMP PREEMPT Wed Feb 1 15:01:31 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

I updated chromeOS and afterwards couldn't start lxde with `sudo startlxde`
And yes, I've tried `sudo sh -e ~/Downloads/crouton -u -n precise -t x11`
Also, `sudo enter-chroot -n precise` works just fine

Here is the output of `sudo startlxde` 
[out.txt](https://github.com/dnschneid/crouton/files/777269/out.txt)
Here it starts up but it just goes to pure black screen so I switch out and press Ctrl+C
Here is the output of when it quits
[out2.txt](https://github.com/dnschneid/crouton/files/777267/out2.txt)

**Comment by drinkcat** [comment]
See #2923.

**Comment by abc123me** [comment]
#2923 Did NOT work for me, nothing on any related issues works

**Comment by drinkcat** [comment]
I only tested trusty release, do you mind trying that?

**Comment by e1337sheep** [comment]
I am using trusty and lxde, and have tried methods from [#2923](https://github.com/dnschneid/crouton/issues/2923), to no avail.

**Comment by abc123me** [comment]
I don't know how to switch from precise to trusty

**Comment by DennisLfromGA** [comment]
@abc123me,

Your `croutonversion` output in your first post shows you have a 'precise' chroot.
You can install a 'trusty' chroot using:

`sudo sh ~/Downloads/crouton -r trusty -t lxde`

The 'trusty' release works with the latest changes to crouton, no black screens.

*Hope this helps,*
-**DennisL**

**Comment by wallace11** [comment]
This might be totally unrelated, since I checked the output file attached and nothing was mentioned there, however I spent two hours now trying to move from xiwi to xorg on xenial with the same problem. Solved this by changing kernel flags:
`sudo crossystem dev_boot_usb=0 dev_boot_legacy=0 dev_boot_signed_only=1`

**Comment by DennisLfromGA** [comment]
@wallace11,

I doubt the `crossystem` command was the answer.

If you have both 'xiwi' & 'xorg' xmethods already installed you can launch either one using the '-X' option.
For instance, if you use lxde like the OP try this:

To launch using 'xorg': `sudo startlxde -X xorg`
To launch using 'xiwi': `sudo startlxde -X xiwi`

To see which xmethod is the default and to list the targets you've installed for all chroots, use this:

`sudo edit-chroot -all`

Lastly, to 'switch' xmethods just do a crouton update specifying the target/xmethod you want as the default, similar to: 

For 'xorg': `sudo sh ~/Downloads/crouton -n trusty -t xorg -u` 
For 'xiwi': `sudo sh ~/Downloads/crouton -n trusty -t xiwi -u` 

*Hope this helps,*
-**DennisL**

**Comment by punchline18** [comment]
@DennisLfromGA I am a total noob going through all these black screen issues, and I have xfce booted with xiwi in a tab, but I still cant seem to get xorg to work. I think I need to try comment #2978  edditted change to the config file with "glamour" and "PageFlip", but honestly, Idk how to change/modify those files specifically (sorry for being a total noob). Can someone please post the command?

**Comment by davidlowryduda** [comment]
I'll note that I responded to punchline18 in https://github.com/dnschneid/crouton/issues/2978#issuecomment-280536745

**Comment by drinkcat** [comment]
@abc123me I'm pretty sure updating your chroot will fix the problem, please report back if it doesn't.
