### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Jonathan1223** [dnschneid/crouton#3077]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170214182546~master:163e0d26
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.82.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Feb 1 15:13:00 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
#### Please describe your issue:
When i use sudo startxfce4 turns blackscreen, cant acces to linux

**Comment by abc123me** [comment]
Same exact problem, I haven't found a fix yet but working on it

**Comment by mojopong** [comment]
getting same issue i think it was due to the most recent chrome update since i just installed it. On Version 56.0.2924.87 (64-bit) on my toshiba chromebook 2 (2014)

**Comment by divx118** [comment]
@Jonathan1223 Can you please not write the issue title in capitals. Thanks.
Also if you look at the known issues there are several of them that mention black screen. Did you look at those and see if this is not a duplicate?

**Comment by Jonathan1223** [comment]
@divx118 I did and tried shut down and open again but didnt work

**Comment by soulesb** [comment]
Try installing the xiwi target using the command, sudo sh ~/Downloads/crouton -u -n chrootname -t xiwi. This fixed the black screen issue for me.

**Comment by drinkcat** [comment]
See #2923.
