### ISSUE TITLE
Unable to switch between crouton and ChromeOS, black screen on log out.

### ISSUE THREAD

**Issue by Lunderberg** [dnschneid/crouton#3079]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161129162558~master:5f2f11f9
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome
host: version 9202.18.0 (Official Build) beta-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Mon Feb 6 22:10:28 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
The linux partition can be started successfully, with "sudo startgnome".  Once it starts, the shortcut "Ctrl-Alt-Shift F1" does not function to bring me back to ChromeOS.   If I log out, the system displays a blank screen until I restart using the power button.

#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
@Lunderberg,

Try using <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>F2</kbd>.
Or, get into a terminal session in your chroot and enter `croutoncycle cros`

*Hope this helps,*
-**DennisL**

**Comment by Lunderberg** [comment]
@DennisLfromGA 

Thank you.  The "Ctrl + Alt + Shift + F2" shortcut is also ignored.  When I run `croutoncycle cros`, it results in a black screen, the same as if I had logged out.  

I performed the same test in a Ubuntu Trusty chroot, as Ubuntu Xenial is unsupported by crouton, and the behavior is slightly different.  The shortcuts still don't work, but `croutoncycle cros` does return to ChromeOS, rather than giving a black screen.  Once in ChromeOS, the shortcut does not work to return to the crouton session.  It is possible to return by running `sudo startcli`, then using `croutoncycle next`.  The details of the new chroot are as follows.

```
name: gnome
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/gnome...
crouton: version 1-20170214182546~master:163e0d26
release: trusty
architecture: amd64
xmethod: xorg
targets: gnome,keyboard,audio,extension,cli-extra
host: version 9202.18.0 (Official Build) beta-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Mon Feb 6 22:10:28 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/gnome as another instance is using it.
```

A possibly related detail: a recent ChromeOS update caused some issues with the keyboard shortcuts in ChromeOS.  The "Search + Arrow Key" shortcuts just cause the search window to show up.  The two might be connected to each other, so I'm going to try switching back to the stable channel and see what happens.

**Comment by Lunderberg** [comment]
Looks like the shortcut issue is definitely caused by an update between the stable channel (version 9000.82.0 (Official Build) stable-channel falco) and the beta channel.  When I switched back to the stable channel, the shortcuts started working again.  Crossing fingers that google gets it sorted out by the time that update makes it to stable.

Regarding the black screen when switching back to ChromeOS, that has only happened on a xenial chroot that was made with an older version of crouton, then updated to the latest version.  Using the latest version, a newly-made chroot with either trusty or xenial can switch back and forth freely, without running into the black screen.

**Comment by Lunderberg** [comment]
Two months later, the stable channel has caught up to that same update, and the bug has returned.  I can switch between ChromeOS and crouton using `croutoncycle next`, but the keyboard shortcuts do not function.

It may be related to this bug (https://bugs.chromium.org/p/chromium/issues/detail?id=701643), which affects only HP Chromebook 14 machines running falco.  Both are issues involving keyboard shortcuts that appeared on the same build on my machine.

```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170215183440~master:5127f68c
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome,keyboard,audio,extension,cli-extra
host: version 9202.60.0 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 28 23:30:38 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

**Comment by Lunderberg** [comment]
After updating to Chrome OS version 57.0.2987.148, the keyboard shortcut works again.  As the issue related to the search key was also fixed in the same update, I think that the two are connected, and are now fixed.
