### ISSUE TITLE
black screen when starting crouton

### ISSUE THREAD

**Issue by risingsun007** [dnschneid/crouton#3082]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20170215183440~master:5127f68c
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.82.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 1 15:07:23 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
I just get a black screen when the screen switches over to ubuntu after issuing the command sudo startxfce4.    crouton was working for over a year and it suddenly I just started getting a black screen.  I powerwashed my chromebook, but I still have the same issue.   I can still switchback to my normal chromebook by pressing ctrl-alt-shift-back_arrow

**Comment by dnschneid** [comment]
#2923
