### ISSUE TITLE
Cant connect to MySQL Debian 8

### ISSUE THREAD

**Issue by DavidMcLaughlin29** [dnschneid/crouton#3085]
```
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: jessie
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/jessie...
```

Cannot get MySQL running on Debian 8.
![screenshot - 021617 - 20 56 38](https://cloud.githubusercontent.com/assets/21325428/23049486/72b411ba-f48a-11e6-9c3e-38a82f04102a.png)

Try mysql_secure_installion or mysql. 

Error
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
I had the problem with Ubuntu Trusty 14.04. I've been stuck here for days. I'm trying to get wordpress set up. 

Here is the rc.local file:
```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

sudo /etc/init.d/apache2 start
/sbin/iptables -P INPUT ACCEPT
/usr/sbin/sshd
export HOME=/etc/mysql
umask 007
[ -d /var/run/mysqld ] || install -m 755 -o mysql -g root -d /var/run/mysqld
/usr/sbin/mysqld &
exit 0
```
It seems to be a known issue but I've tried everything I've found.

**Comment by DavidMcLaughlin29** [comment]
Update. I realized that there is not a mysqld directory.

**Comment by DavidMcLaughlin29** [comment]
Update: I got it working last night using [these instructions ](http://superuser.com/questions/980841/why-is-mysqld-pid-and-mysqld-sock-missing-from-my-system-even-though-the-val). When I started this morning the problem was back.

**Comment by DavidMcLaughlin29** [comment]
Got it working again. The server wasn't running. Started it with sudo /etc/init.d/mysql start. Then logged in with mysql -u root -p.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
