### ISSUE TITLE
Crouton not working on Chrome OS 58

### ISSUE THREAD

**Issue by cnclockwork** [dnschneid/crouton#3087]
it's just not..
goes to a black screen when you try to switch over to ubuntu

????????????????????????????

**Comment by DennisLfromGA** [comment]
@cnclockwork - Update your chroot to get the latest fixes.

**Comment by cnclockwork** [comment]
im so sorry im a noob with linux
what exactly is a chroot?

**Comment by DennisLfromGA** [comment]
Read this for lots of good info. - [README](https://github.com/dnschneid/crouton/blob/master/README.md)

Then update your ['chroot'](https://github.com/dnschneid/crouton/blob/master/README.md#whats-a-chroot) using: `sudo sh ~/Downloads/crouton -u`

*Hope this helps,*
-**DennisL**
