### ISSUE TITLE
Protractor chromedriver version 2.27 windows 32 bits  - click on element not working as expected

### ISSUE THREAD

**Issue by chantalv** [dnschneid/crouton#3088]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Since I've migrated to version 2.27 for chromedriver (as Chrome is now version Version 55.0.2883.87 m (64-bit)), my automated tests (protractor) are not working anymore . Now apparently the click on elements doesn't work fine . 
Or the problem is now linked with the search I am doing to get the element back ... 

#### If known, describe the steps to reproduce the issue:
I am doing something like 
var ftth_rb = element(by.id('FTTH'));   - as my page has only one element having this id
..... 
obj.selectRadioButton(ftth_rb);

with 
obj.selectRadioButton = function(button){
        browser.wait(function (){
            return button.isPresent();
        }).then(function (){
        //console.log('FOUND element: ' + button);
        });
        button.click( );
        browser.sleep(1000);
     
    };
 
Any idea  :) ?? Thank you

**Comment by dnschneid** [comment]
#262

**Comment by chantalv** [comment]
sorry this was for angular/protractor  ... don't know if there is a way to move it  under the right 'folder'  ...

**Comment by divx118** [comment]
@chantalv  Just re-post it at their git https://github.com/angular/protractor/issues AFAIK no way to move it.
