### ISSUE TITLE
I-D-K what I am doing..... :(

### ISSUE THREAD

**Issue by zmcase** [dnschneid/crouton#3089]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

I have downloaded and installed Crouton. I entered the following command: 

sudo startunity

Which went black for a second and then went back to chromebook with the following in the terminal;

chronos@localhost ~/Downloads $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13527-gc2f2230 #1 SMP PREEMPT Wed Feb 1 15:08:20 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=19a28b48-3f80-894b-ba19-46d6aaa818bc/PARTNROFF=1 hashtree=PARTUUID=19a28b48-3f80-894b-ba19-46d6aaa818bc/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=44225f79a27b9aeb9436c73033bf600cb26245a5 salt=a15acb0bf4c70e61e6138718acfc1c653c70c7797e7ae0fcb275908e10354a2c" noinitrd vt.global_cursor_default=0 kern_guid=19a28b48-3f80-894b-ba19-46d6aaa818bc add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Feb 17 19:49:37 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[intel_init_bufmgr:1069] Error initializing buffer manager.
setversion 1.4 failed: Permission denied
crouton: version 1-20170216202114~master:2f7cfb5e
release: precise
architecture: amd64
xmethod: xorg
targets: unity
host: version 9000.82.0 (Official Build) stable-channel sentry 
kernel: Linux localhost 3.18.0-13527-gc2f2230 #1 SMP PREEMPT Wed Feb 1 15:08:20 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...

WHAT AM I DOING WRONG!?!?!??!?!?!?!? Please help!

**Comment by rwwishart** [comment]
My recommendation is, if possible, keep experimenting with different setups and don't worry too much if the first time fails. One major benefit to this environment is that chroots are easy to create and modify. 

Given your current issue, try one or more of the following:
1). Install more targets. I use xorg, xiwi, keyboard, and unity
`sudo sh -e ~/Downloads/crouton -t xorg,xiwi,keyboard,unity -r precise -e`
That command assumes you also want encryption.
2). After running the install script, try starting the chroot with a different target. Add the crouton Chrome extension and try running with the xiwi target: `sudo enter-chroot -n chrootname -X xiwi`
See here: [https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)](url)
3). Try a different release. Trusty is well-supported. I'm running Xenial (with a bit of effort).
4). Finally, if you can't get unity to run on your system, try installing with xfce.
Happy hunting! Don't give up!

**Comment by zmcase** [comment]
So first type;

sudo sh -e ~/Downloads/crouton -t xorg,xiwi,keyboard,unity -r precise -e

then install using command;

sudo enter-chroot -n chrootname -X xiwi

Im a super beginninger.... sssoooooo.... laying out the steps would be super greatful.

**Comment by zmcase** [comment]
Also, when I type in: 

sudo sh -e ~/Downloads/crouton -t xorg,xiwi,keyboard,unity -r precise -e

Then the files were downloaded and updated. After, I typed;

sudo enter-chroot -n chrootname -X xiwi

Which this had came up in the terminal; 

grep: /mnt/stateful_partition/crouton/chroots/chrootname/.crouton-targets: No such file or directory
/mnt/stateful_partition/crouton/chroots/chrootname does not contain XMETHOD 'xiwi'

Sooooo what am I doing wrong?

**Comment by IMadeYouReadThis777** [comment]
I am also having this issue. Is there a way to directly download the
missing files straight to the path folder?
TIA
Caleb

**Comment by drinkcat** [comment]
Might be good to try xenial instead.
