### ISSUE TITLE
Chromebook issue, black screen

### ISSUE THREAD

**Issue by mbennett024** [dnschneid/crouton#3090]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.82.0 (Official Build) stable-channel banjo 
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 1 15:10:35 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
#### If known, describe the steps to reproduce the issue:

After a Chromebook update the screen is just black when I try to switch to the crouton (not sure of the terminology). I'm a total noob but was having fun trying to learn more about Linux so any help to get this up and running would be appreciated!

**Comment by DennisLfromGA** [comment]
For help see '[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)'
