### ISSUE TITLE
Fatal Server error: no screens found, crouton on dell 11 Chromebook

### ISSUE THREAD

**Issue by Siemen04** [dnschneid/crouton#3092]
When I try to open unity, I get this this error message:

Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.44-07169-g8391de9 #1 SMP PREEMPT Mon Feb 13 03:00:01 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=f1c10cce-c7db-5147-843e-0f2260bbfe4d/PARTNROFF=1 hashtree=PARTUUID=f1c10cce-c7db-5147-843e-0f2260bbfe4d/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=b0ca2ac0fb3482649c4335b6687072532b59098f salt=50b7f42a1b5e16bb0327354a050dbc4298bf21aff3247a11db290f8f1a0683f5" noinitrd vt.global_cursor_default=0 kern_guid=f1c10cce-c7db-5147-843e-0f2260bbfe4d add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Feb 19 14:25:37 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

And when I do sudo edit-chroot -al it says: 
name: precise
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

Please help me

**Comment by DennisLfromGA** [comment]
Make sure your chroot is up to date, see '[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)'
