### ISSUE TITLE
three tap gestures not working on xenial 

### ISSUE THREAD

**Issue by BluesparkYT** [dnschneid/crouton#3095]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: vivid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/vivid...
/usr/local/bin/enter-chroot: 511: cannot create /run/crouton/mnt/stateful_partition/crouton/chroots/vivid/etc/crouton/name: Directory nonexistent
```

#### Please describe your issue:
i installed xenial with xfce keyboard xorg chrome and extension and i can't do three tap gestures 

#### If known, describe the steps to reproduce the issue:
do ```sudo sh ~/Downloads/crouton -r xenial -t xfce,keyboard,xorg,chrome``` and you can't middle click might be a xenial issue :/

**Comment by izohar** [comment]
Have you tried running:

> synclient TapButton3=2

? 
`synclient -l` will give you all the gesture options.

Itai
