### ISSUE TITLE
Ble Beacon is not pairing in Marshmallow

### ISSUE THREAD

**Issue by siddharthanP** [dnschneid/crouton#3096]
For my application, I'm trying to pair a Ble Beacon using BluetoothGatt API.I'm able to show the pairing dialog for the device and I can enter a pin code. When I press "Pair" it is not pairing in marshmallow. But the same code and passkey are working in less than Marshmallow.

Also, i gave ACCESS_COARSE_LOCATION,ACCESS_FINE_LOCATION permission in the manifest file and turned on GPS location.

     public void connectToDevice(String sMacId) {//here i'm passsing ble beacon macid
        
        BluetoothDevice device = baBluetoothAdapter.getRemoteDevice(sMacId);       
        if (mGatt == null) {
            mGatt = device.connectGatt(this, false, gattCallback);

        }
    }

    private final BluetoothGattCallback gattCallback = new BluetoothGattCallback() {
        @Override
        public void onConnectionStateChange(BluetoothGatt gatt, int status, int newState) {
           
            switch (newState) {
                case BluetoothProfile.STATE_CONNECTED:                    
                    gatt.discoverServices();
                    break;
                case BluetoothProfile.STATE_DISCONNECTED:
                    Log.e("gattCallback", "STATE_DISCONNECTED");   

                    break;
                default:
                    Log.e("gattCallback", "STATE_OTHER");
            }
        }
    }

In Receiver class i'm checking bound state.bound state always giving 10 in Marshmallow.  

     private BroadcastReceiver myReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            String action = intent.getAction();
            if (BluetoothDevice.ACTION_BOND_STATE_CHANGED.equals(action)) {
                BluetoothDevice device = intent.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);
                int nState = device.getBondState();//
                
            }
        }
    };

**Comment by divx118** [comment]
I wonder how people end up all the time on the wrong git when posting there issues? #262

**Comment by dnschneid** [comment]
I dunno, but I don't blame them.  crouton has the best git.

(Nice to see you active again, @divx118)
