### ISSUE TITLE
Samsung Chromebook Plus - crouton not working

### ISSUE THREAD

**Issue by cdgaggie** [dnschneid/crouton#3098]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20170216202114~master:2f7cfb5e
release: precise
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9000.87.1 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.21-06459-ge91c124 #1 SMP PREEMPT Thu Feb 16 21:44:33 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

#### Please describe your issue: chroot setup fails every time.
Please specify a username for the primary user: cdg
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in precise
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

#### If known, describe the steps to reproduce the issue: 
followed example 1 for xfce precisely

Please advise me on what i'm doing wrong???

**Comment by DennisLfromGA** [comment]
@cdgaggie,

It may not have accepted your username & password, it's complaining about '*UID 1000 not found in precise*'

I would try to do a crouton update follwoing these excellent instructions:
- ['Common issues and reporting'](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**

**Comment by DennisLfromGA** [comment]
@cdgaggie,

If the above steps don't work for you then you may be running into this issue:

#### ['X11 will not install on Samsung Chromebook Plus #3083'](https://github.com/dnschneid/crouton/issues/3083)

They're still working on it but you can probably track it there.

*Hope this helps,*
-**DennisL**
