### ISSUE TITLE
crouton must be run as root

### ISSUE THREAD

**Issue by ayoungdude** [dnschneid/crouton#3099]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found

```

#### Please describe your issue:
crosh> shell
chronos@localhost / $ sh ~/Downloads/crouton -t kde
Downloading latest crouton installer...
######################################################################## 100.0%
crouton must be run as root.

#### If known, describe the steps to reproduce the issue:

So I followed this guide:
https://lifehacker.com/how-to-install-linux-on-a-chromebook-and-unlock-its-ful-509039343

I was trying to install xfce on my little chromebook and got quite far.

I had followed the instuctions to a t:

shell
sudo sh -e ~/Downloads/crouton -t xfce
and finally
sudo startxfce4

Except xfce isn't working properly at the moment. So I had a black screen and an error with "unable to contact settings server"

So I think "hay no biggie!" just powerwash and start again

So I did and now when I do:
crosh> shell
chronos@localhost / $ sh ~/Downloads/crouton -t kde
Downloading latest crouton installer...
######################################################################## 100.0%
crouton must be run as root.

... I don't actually understand where I went wrong. And STFW hasn't given me any clear solutions. please help?

**Comment by DennisLfromGA** [comment]
https://github.com/dnschneid/crouton#examples
