### ISSUE TITLE
Chrome inside Crouton inside ChromeOS: sad tabs

### ISSUE THREAD

**Issue by nigeltao** [dnschneid/crouton#3106]
Not sure if this is a bug, but I don't know where else to ask. Also, trying to search for [run chrome in crouton] is full of things unrelated to my specific problem.

I can get Ubuntu Xenial up inside Crouton. Great.

I want to run google-chrome inside Xenial. Why don't I just use the 'host' ChromeOS browser? One reason is that I'm used to my window manager providing a keyboard shortcut for creating new browser windows. Another reason is that I use multiple profiles, and it's not obvious what the ChromeOS model is for multiple windows for multiple profiles on the one screen at the one time.

Anyway, most of the time it works, but sometimes a race condition fails and tabs keep dying with a "sad tab" page. I don't have a reliable repro, other than to use my computer for a day.

Is there some sort of extra logging I can enable somehow that would help debug this?

Is what I'm doing supposed to work? Or is there always going to be some sort of fundamental weirdness where the presence of the host Chrome processes (running ChromeOS) is confusing the guest Chrome processes (running inside Xenial)? For example, chroot isolates the file system that the guest Chrome processes sees, but it doesn't isolate the process tree, and running "killall chrome" from inside my Xenial instance leads to a Bad Time.

**Comment by drinkcat** [comment]
This should work, looks like a Chrome issue. You might want to file a feedback in the nested Chrome that crashes (https://support.google.com/chrome/answer/95315?hl=en).
