### ISSUE TITLE
Equity Framework (Must See Theme) Nenus

### ISSUE THREAD

**Issue by brettcairns** [dnschneid/crouton#3107]
Have asked the theme producer with no reply. Have the equity framewor and must see them for a business site and the mobile menu does not work (had to install slick nav menu as a temporary fix for that) and now the dropdown submenus no longer display or work. They should (and used to) open on hover but now the only way to see them is to left click and they appear momentarily or right click and they are not functional. Need to fix them for the site to be useful on desktop but cannot find the problem. Does anyone have any thoughts on how I find the problem and fix? thanks

site is www. brettcairns. com

**Comment by DennisLfromGA** [comment]
You've wandered into the 'crouton' development & support site.

You'll have to look elsewhere for [Equity Framework support](http://lmgtfy.com/?q=Equity+Framework+Menus) I'm afraid.
