### ISSUE TITLE
Newbie, encryption passphrase help needed

### ISSUE THREAD

**Issue by Pocky4141** [dnschneid/crouton#3109]
```
Please paste the output of the following command here: sudo edit-chroot -all
![screenshot 2017-02-23 at 5 06 57 pm](https://cloud.githubusercontent.com/assets/20023802/23286132/802e74f6-f9ea-11e6-9a23-ee709c7ad9ed.png)

Password:
name: precise
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/precise. . .
```
#### Please describe your issue:
I am brand new to using crouton or actually hacking in any sense, if not to basic coding. I was trying to install crouton and every time I attempted to install it it required an encryption passphrase. I've only been playing with crosh for about a day and I don't recall setting this passphrase. Is it asking me to set one? In which case why does it say "failed to decrypt precise"? Please help!

(line of code: //(its -u because if I don't update the folder it says "theres already something in that folder"

chronos@localhost / $ sudo sh ~/Downloads/crouton -e -t xfce -u 
/usr/local/chroots/precise already exists; updating it...
Enter encryption passphrase for precise: "BLAH BLAH BLAH"
Failed to decrypt precise

I have tried my password I set, my username, ENTER, precise, and just about anything else I could think of. 

-Pocky

**Comment by DennisLfromGA** [comment]
@Pocky4141,

You don't have to encrypt your chroot, it's just an option that's important to some.
Also, even if you do want to encrypt your chroot you can do it after installation and configuration.

If you can't get into your chroot you may be better off deleting it and starting over.
To delete it, use this: `

`sudo delete-chroot -n precise`

To install a crouton chroot without encryption initially just leave out the '-e' option, like -

`sudo sh ~/Downloads/crouton -t xfce`

Once installed and setup you can encrypt it if you like with an update, like -

`sudo sh ~/Downloads/crouton -e -u`

Also, without specifying a 'release' with the '-r' option you'll get the default 'precise' release.

*Hope this helps,*
-**DennisL**

**Comment by Pocky4141** [comment]
Ah wonderful thanks
