### ISSUE TITLE
revert back to a certain commit 

### ISSUE THREAD

**Issue by aleksss55** [dnschneid/crouton#3116]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
I recently started using git and site github.com and would like to clarify one moment. I created a project on the site and then document for testing purposes. All operations (like editing file, commiting changes) I do directly on the site github. I make changes to the document and then commit them. Everything is fine, if I open History tab, I can see history of all changes. The question is - how I can revert back to a certain commit using web-interface of github? Unfortunately, I was not able to find such feature.

**Comment by dnschneid** [comment]
#262
