### ISSUE TITLE
How to center navigation bar 

### ISSUE THREAD

**Issue by kadefoster** [dnschneid/crouton#3118]
How can I center my menu in my navigation bar? I would like to keep the social media icons where they are but move the menu items on the left to the center of the screen. 

``<html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>Twitter Bootstrap Social Media Icons to Navbar</title>
    <link href="/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/font-awesome.css" rel="stylesheet" type="text/css" />
     <link href="/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/custom.css" rel="stylesheet" type="text/css" />
</head>
<body>
    
    
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            
                
                <a class="navbar-brand" href="#"></a>
           
            
            
            </div>
            
            <div class="collapse navbar-collapse" id="navbar1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Info</a></li>
                    <li id="fest"><a href="#">Festival</a></li>
                    <li><a href="#">Get Involved</a></li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right social">
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>
    </nav>
    
      <div class="jumbotron">

    </div>
    
    <div class="video-section">
			<video id="video-elem" preload="auto" autoplay="true" loop="loop" muted="muted" poster="videoGIF.gif"> 
				<source src="video.mp4" type="video/mp4">
				Video not supported
			</video>
            
		</div>
        
        <div class="content-section">
            <h1>Video As A Background For Website Section</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget aliquam massa. Donec feugiat, tortor ac feugiat auctor, purus augue rhoncus neque, at tristique tortor urna at velit. Nullam in maximus quam. Suspendisse aliquam enim nibh, ac scelerisque justo sollicitudin eget. In sed lacinia quam, a viverra diam.</p>
        </div>

    <script src="/jquery-3.1.1.min.js"></script>
    <script src="/bootstrap.min.js"></script>
</body>
</html>

**Comment by dnschneid** [comment]
#262

**Comment by kadefoster** [comment]
I like trout yogurt. Sorry I didnt realize where I posted, thanks for the laugh though lol

**Comment by dnschneid** [comment]
No worries.  Out of curiosity, where were you aiming for?

**Comment by kadefoster** [comment]
I'm not sure... lol I'm usually not totally inept but at the moment i
certainly am. I'm trying to move my menu over in the top bar with out
affecting my social media icons where would I post my issue?

**Comment by dnschneid** [comment]
Yeah, I have no idea.  Not here, though :)
