### ISSUE TITLE
new Target install is mistaken for Unity install.

### ISSUE THREAD

**Issue by Asternitix** [dnschneid/crouton#3119]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: beta
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/beta...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: x11,e17,unity,xfce,extension,gnome-desktop
host: version 9000.91.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Feb 22 23:39:40 PST 2017 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
When I try to install a new target, it is interpreted as -t unity and fails to install in my Debian chroot.

#### If known, describe the steps to reproduce the issue:
install a new target into an already existing chroot.

**Comment by dnschneid** [comment]
When you go to install a new target, crouton also updates your existing targets.  Since you already have unity installed in your chroot, unity will update when you go to install a new target.

**Comment by Asternitix** [comment]
how would I fix this?

**Comment by Asternitix** [comment]
I found and edited the targets file. that should do it.

**Comment by Asternitix** [comment]
It seems to work so far.

**Comment by Asternitix** [comment]
It works! finally!

**Comment by DennisLfromGA** [comment]
@Asternitix,

'crouton' won't see your 'unity' target any longer but if you update your chroot from within with `apt-get` or something unity will still get updated so be careful.

*Hope this helps,*
-**DennisL**
