### ISSUE TITLE
How do I increase woo commerce columns?

### ISSUE THREAD

**Issue by shahjahanbdsyl** [dnschneid/crouton#3121]
How do I increase woo commerce columns?
For example-[sale_products per_page="12" columns="4"] this short code display per page-12 products and per columns 4 products.
And what are columns? **# **Columns means, Line.****
1 columns mean= 1 Lines. That’s why; I need 3 lines/Columns. And it will display (3 x 4) =12 product in 3 columns.
What will be that code? Please, anybody, help me.

**Comment by DennisLfromGA** [comment]
I believe you've gone astray, this is the 'crouton' support site.
You won't get any help here by ['woo'ing](http://lmgtfy.com/?q=woo+commerce+columns) us. :)
