### ISSUE TITLE
"no instance returned" Zend Framework 2

### ISSUE THREAD

**Issue by monteiro07** [dnschneid/crouton#3125]
Hi, i have been following step by step the beginners guide of Zend Framework 2 on their website (https://framework.zend.com/manual/2.4/en/in-depth-guide/preparing-db-backend.html) and i encountered the following error: 
An exception was raised while creating "Blog\Controller\List"; no instance returned

stack trace: 

#0 C:\wamp64\www\zf2\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(284): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'blogcontrollerl...', 'Blog\\Controller...')
#1 C:\wamp64\www\zf2\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(242): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'blogcontrollerl...', 'Blog\\Controller...')
#2 C:\wamp64\www\zf2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(638): Zend\ServiceManager\AbstractPluginManager->createFromFactory('blogcontrollerl...', 'Blog\\Controller...')
#3 C:\wamp64\www\zf2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('Blog\\Controller...', 'blogcontrollerl...')
#4 C:\wamp64\www\zf2\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#5 C:\wamp64\www\zf2\vendor\zendframework\zend-servicemanager\src\AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('Blog\\Controller...', false)
#6 C:\wamp64\www\zf2\vendor\zendframework\zend-mvc\src\Controller\ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('Blog\\Controller...', Array, false)
#7 C:\wamp64\www\zf2\vendor\zendframework\zend-mvc\src\DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('Blog\\Controller...')
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 C:\wamp64\www\zf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 C:\wamp64\www\zf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 C:\wamp64\www\zf2\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 C:\wamp64\www\zf2\public\index.php(21): Zend\Mvc\Application->run()
#13 {main}

Any help apreciated, i been stuck for ages now D:
thanks for the atention

**Comment by divx118** [comment]
#262 again :)

**Comment by monteiro07** [comment]
sorry, first post.. xd

**Comment by divx118** [comment]
no problem, can you please close this.

**Comment by monteiro07** [comment]
why? what am i doin wrong?

**Comment by divx118** [comment]
@monteiro07 You are posting your issue on the issue tracker of crouton. Looking at your question this has nothing to do with crouton, you probably want another git here on github. Like somewhere here https://github.com/zendframework/
