### ISSUE TITLE
possible : crouton breaks Chromebook imput methods for sharing, non-owner logins

### ISSUE THREAD

**Issue by aldobranti** [dnschneid/crouton#3126]
```
edit-chroot not found
```

#### Please describe your issue:

the owner of the CB has designated the CB with a GB keyboard and is able to additionally add other KB and input methods IM . THe owner has installed crouton/unity.
The owner has added other users who may login with their own profiles.
THese users are not able to add input methods/different keyboards
Chromebook central query if this failing behaviour goes with crouton
We are not in a position to remove crouton at this point in time

#### If known, describe the steps to reproduce the issue:

Allow other sharing users
Install crouyton
Owner attempt to add keyboards/IM's
Sharing user attempt to add keyboards/IM

**Comment by drinkcat** [comment]
I'm pretty sure crouton does not fiddle with Chrome OS input methods.
