### ISSUE TITLE
New to Xcode need help

### ISSUE THREAD

**Issue by wadst3** [dnschneid/crouton#3127]
I'm new to Xcode, i'm trying to create and app where i have a uiwebview in one storyboard. My issue i can't seem to get the right syntax of how to write in Xcode, is that i wanna detect a url click from within the webview and then check if the link is a certain link. for example if user pressed link https://www.something.com/redirect.php?value=1, i would like to break down the link to find the redirect.php part and if the link is that then i have another uiwebview that is essentially a modal pop up and would like that link to be passed to the second webview and open the link like a pop up but a pop up that is essentially still with in the app and not to safari. I'm using -(BOOL)webViewer:(UIWebView*)webViewer shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType{ to detect when a url is pressed, i'm not sure how to do the checking if it's the certain link and then pass the link to the second webview as a popup. Thanks for your time

**Comment by dnschneid** [comment]
#262

**Comment by DennisLfromGA** [comment]
https://github.com/search?utf8=%E2%9C%93&q=xcode
