### ISSUE TITLE
I have no clue what is happening

### ISSUE THREAD

**Issue by sirduffy4242** [dnschneid/crouton#3128]
Doing this guide. http://platypusplatypus.com/chromebooks/play-runescape-chromebook/

sudo sh ~/Downloads/crouton -r trusty -t xfce
```
Please paste the output of the following command here: Nothing happends
```

#### Please describe your issue:
This doesn't do anything. Or maybe I am just a dumbass. Probably the ladder. It just ignores it and is ready for the next command. Like I typed nothing

#### If known, describe the steps to reproduce the issue:
Type shell then "sudo sh ~/Downloads/crouton -r trusty -t xfce" into the chrome crosh thing. Please help when able. Thank you

**Comment by DennisLfromGA** [comment]
@sirduffy4242,

Assuming you followed **Step 1** and placed crouton in Downloads -
> Step 1: Download Crouton from the github page [here](https://goo.gl/fd3zc).

I don't see *anything* wrong with the command -

> `sudo sh ~/Downloads/crouton -r trusty -t xfce`

Enter the following and see if it lists 'crouton': `ls -l ~/Downloads/crouton`
It should show something like:

> -rw-r--r--. 1 chronos chronos 3.6K Mar  8 14:13 /home/chronos/user/Downloads/crouton

If that works then try it prefixed with 'sudo':  **`sudo`**`ls -l ~/Downloads/crouton`
It should work and display the same thing.

*Hope this helps,*
-**DennisL**

**Comment by sirduffy4242** [comment]
Hey @DennisLfromGA 
Thank you for the quick response. Here's what I got. [Screenshot](http://imgur.com/a/fNwCg)
Does this look right?

**Comment by DennisLfromGA** [comment]
@sirduffy4242,

I see what happened, `~/Downloads/crouton` is a directory, not the downloaded file.
You may have inadvertently 'unbundled' or 'unzipped' the crouton source files instead of downloading the file. 

If I were you I'd completely remove the entire 'crouton' directory using: 

`cd ~/Downloads && rm -rf ./crouton && cd`

Then download just the crouton installer file from [here](https://goo.gl/fd3zc): https://goo.gl/fd3zc

*Hope this helps,*
-**DennisL**

**Comment by sirduffy4242** [comment]
@DennisLfromGA 
Thank you again. Thanks for caring so much about little issues like mine. I am almost completely new to linux. I will try your idea. Thanks! Do I literally just use the zip file and do the sudo sh command with that?

**Comment by DennisLfromGA** [comment]
@sirduffy4242,

No *zip* file is involved at all, just the download the 'crouton' file from:  https://goo.gl/fd3zc

That should place the crouton installer file, which is named `crouton` in your ~/Downloads directory.
Then run the command above: `sudo sh ~/Downloads/crouton -r trusty -t xfce`

*Hope this helps,*
-**DennisL**
