### ISSUE TITLE
Not able to use x11 with Trusty

### ISSUE THREAD

**Issue by shichuzhu** [dnschneid/crouton#3129]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170228132702~master:21cb695b
release: trusty
architecture: armhf
xmethod: xiwi
targets: xfce,x11,keyboard,cli-extra,xiwi
host: version 9000.91.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.21-06459-ge91c124 #1 SMP PREEMPT Wed Feb 22 23:26:03 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue:
OK to sudo startcli, but error when trying to use x11, e.g. sudo startxfce4, whose output is pasted below:
chronos@localhost /usr/local/bin $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-67-highbank armv7l Ubuntu
Current Operating System: Linux localhost 4.4.21-06459-ge91c124 #1 SMP PREEMPT Wed Feb 22 23:26:03 PST 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashtree=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=193d05fdc12bcf8c2c458f07d51981005fd09c07 salt=831085ab289b9bc7386e63c717424f696805c436924f1705827c0c53ab1a795a" noinitrd vt.global_cursor_default=0 kern_guid=12a8c470-5762-934e-adb4-39c1a1843329  
Build Date: 12 February 2015  02:55:07PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Mar  8 14:41:35 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### If known, describe the steps to reproduce the issue:
Machine is a samsung chrombook plus
cannot utilize x11 such as
sudo startxfce4

**Comment by DennisLfromGA** [comment]
@shichuzhu,

I haven't seen the segmentation fault on trusty, just on precise (https://github.com/dnschneid/crouton/issues/3083). 
There's also some proposed fixes for aarch64 (https://github.com/dnschneid/crouton/pull/2874)

Unfortunately, I don't know enough about the SC+ or either of these issues but maybe you'll be able to find something that makes sense.

The crouton devs are aware of these issues so help is on the way...

*Hope this helps,*
-**DennisL**

**Comment by shichuzhu** [comment]
@DennisLfromGA 
Thanks, I looked into a couple of them and don't have much idea about the details. Is there currently any combination of release(precise,trusty,xenial etc)/x11 environment(xiwi,unity etc) that works on SC+ that you are aware of? I'm just looking for a temporary solution before a fix comes so that I can get things done...

**Comment by DennisLfromGA** [comment]
@shichuzhu,

If you can hold off on doing anything immediately some crouton work is being done as we speak.
Hopefully this issue will be addressed too.

*Hope this helps,*
-**DennisL**

**Comment by drinkcat** [comment]
I can reproduce here. The easiest workaround is to switch to using xenial/xfce, that works fine for me.

**Comment by shichuzhu** [comment]
@drinkcat Confirmed. Xenial/xfce works fine. Only issue is the screen resolution which refers to
https://github.com/dnschneid/crouton/issues/3144

The other thing I wanna mention. After I try to install xfce, I would also wanna get xiwi. However, I need to manually install xserver-xorg-core inside the enter-chroot first, otherwise the xiwi installation fails somehow. Now I'm fine testing something like
sudo startxiwi glxgears
