### ISSUE TITLE
Chromebook unable to open file

### ISSUE THREAD

**Issue by 123456Dd** [dnschneid/crouton#3134]
I clicked on the link to download crouton and my computer says that the file is unable to be opened on a Lenovo N42. When I open up my files it describes the file type simply as file. Is there another way to download crouton?

**Comment by DennisLfromGA** [comment]
@123456Dd,

You do the magic in a terminal session.
Take a look at the [README](https://github.com/dnschneid/crouton) and especially the part about ['Usage'](https://github.com/dnschneid/crouton#usage)

*Hope this helps,*
-**DennisL**

**Comment by 123456Dd** [comment]
I have gone through all the steps to use crouton through the terminal, however my computer sends an error, because it is unable to open the file. I added to chrome multiple apps that claim to link the computer to crouton allowing it to read the file, however none of them seem to work.

**Comment by DennisLfromGA** [comment]
@123456Dd, Try this: https://goo.gl/qLMpO2
