### ISSUE TITLE
how to build a database for my little project

### ISSUE THREAD

**Issue by inh556** [dnschneid/crouton#3136]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
https://inh556.github.io/coursera-test/TableTopicSelectionTool/tableTopicSelectionTool.html
#### Please describe your issue:
Hi guys, I am new for coding.  I'll do my best to make me clear. 
Background: I wanna make a little tool for my table topic practice. On one hand, I can select a topic from a bunch of topics held in database. One the other hand, topics can be add to the database. [https://inh556.github.io/coursera-test/TableTopicSelectionTool/tableTopicSelectionTool.html](url)

Honestly, I almost knew nothing about how to hold my topics in somewhere, like Jquery. So, please give me some suggestion that how I can start doing it. 

By the way, if there are too much words when adding a new topic, how to change the line automatically, I tried several times, that didn't work. 
Thanks very much.

**Comment by dnschneid** [comment]
#262
