### ISSUE TITLE
don't use `echo -n` in shell scripts

### ISSUE THREAD

**Issue by vapier** [dnschneid/crouton#3137]
`echo -n` isn't portable.  some shells will write out a literal `-n` or just ignore it.

instead you can do things like:
```
-  echo -n "$1"
+  printf '%s' "$1"
```

printf also has `%b` in case you want escape sequences to be processed safely:
```
  printf '%b' '\nfoo\n\tbar %s\n'
```

**Comment by dnschneid** [comment]
Probably needs to be fixed sooner rather than later, if [this](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/87fbbd4efe14479fb2167d16cc99d54ba2678856) ever gets reverted.

**Comment by vapier** [comment]
yes my intention is to revert that CL at some point.  but it's a bit of yak shaving i don't have time for atm :).
