### ISSUE TITLE
Is there any way to run Elementary OS luna, using crouton. 

### ISSUE THREAD

**Issue by deolarte** [dnschneid/crouton#314]
I have tried running, with luna, or eos, or elementary, it does not seem to recognize repo. would it be possible to add to recognized repo list? If so thanks.

**Comment by bahaaaldin214** [comment]
I keep on getting this error on the last line
** (lightdm:4735): WARNING **: Failed to get list of logind seats: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

**Comment by aetinx** [comment]
> I keep on getting this error on the last line ** (lightdm:4735): WARNING **: Failed to get list of logind seats: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1 I did sudo /usr/sbin/lightdm right after sudo apt-get install elementary-desktop

Same here.
