### ISSUE TITLE
Samsung Chromebook Plus changing resolution?

### ISSUE THREAD

**Issue by serfma** [dnschneid/crouton#3144]
```
name: xenial
encrypted: yes, unlocked
crouton: version 1-20170309181220~master:a72a0cb5
release: xenial
architecture: arm64
xmethod: xorg
targets: gnome,touch,extension,keyboard
host: version 9000.91.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.21-06459-ge91c124 #1 SMP PREEMPT Wed Feb 22 23:26:03 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
```

#### Please describe your issue:
Using `setres` doesn't properly change resolution (as I've read it does no sanity checking) and I'm stuck at an unusable 2400x1600 resolution.

**Comment by Burgal** [comment]
I wouldn't call it unusable but it is a bit uncomfortable.  :)

I found a somewhat bad hack that gets us to the correct resolution but kills responsiveness.

xrandr --output eDP-1 --scale .75x.75 --fb 1800x1200 --panning 1800x1200

**Comment by Burgal** [comment]
##WARNING: DO NOT RUN SETRES:  IT CAN DAMAGE YOUR SCREEN ON THE SAMSUNG CHROMBOOK PLUS## 

I wish I knew this.

**Comment by serfma** [comment]
Is it still occurring even after a device reboot?

**Comment by Burgal** [comment]
It did stay after device reboot, yes.  I played one of those pixel fixing videos https://www.youtube.com/watch?v=GQBz4khU_ck and kept my screen on white for an hour each.  Using `setres` to make my display1800x1200 probably shortened the life of my screen a bit but it's now it looks  like it's back to normal.

Be careful with xrandr, the same thing happened with some of the setting I tried besides:
`xrandr --output eDP-1 --scale .75x.75 --fb 1800x1200 --panning 1800x1200`

**Comment by serfma** [comment]
Hmmm. Yeah I tried to reduce scale to 0.5 but of course there's performance issues with that. Starting to believe that there's not really a swell solution.

**Comment by drinkcat** [comment]
If you use xiwi there is a HiDPI option in the popup menu that should do what you want.

**Comment by drinkcat** [comment]
@Burgal: I didn't see any flickering issue on my kevin (R58-9227.0.0), running the xrandr command above (but, yes, frame rate seems to drop considerably).

**Comment by serfma** [comment]
I'd like to update this as I've finally gotten back around to messing with my CB+. The only thing that I've found to work is using XFCE with the default hidpi theme while increasing icon sizes and font sizes. KDE seemed to be more promising but scaling changes refuse to take effect even after restart (as they should). Has anyone thus far found a better solution?

**Comment by aleifuu** [comment]
I'm using CB Pro with lxde and jessie as a backend

Have no success at adjusting resolution either using setres, xandr, or any other method outlines here yet

Probably going to stop trying since your warning if potential "dead" screen on this baby's sibling ... 

not unusable, just uncomfortable 

What works so far is that you hook your CB to external monitor, then the resolution will just fit nicely 

I think CB's unusual 3:2 is just unusual to adjust
