### ISSUE TITLE
debootstrap download sed fail

### ISSUE THREAD

**Issue by yuwash** [dnschneid/crouton#3145]
```
Choose an encryption passphrase for xenial: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2017-03-10 23:39:18 URL:http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/ [888/888] -> "-" [1]
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.
```

#### debootstrap download fails when creating a chroot

As It’s downloading 888/888 and manually wget’ing the url succeeds, the reason is probably in the wget coming after that. The [/installer/ubuntu/bootstrap](/dnschneid/crouton/blob/master/installer/ubuntu/bootstrap) script pipes the html file into sed, but that html is encoded utf-16, so running

```
wget -O- --no-verbose --timeout=60 -t2 "http://httpredir.debian.org/debian/pool/main/d/debootstrap/" \
            | sed -ne 's ^.*\(debootstrap_[0-9.]*.tar.gz\).*$ \1 p'
```

actually fails. For converting utf-16 to utf-8 normally `iconv` is used, but that’s not available.

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the debootstrap problem.
You can do a quick test with something like the following: crouton -r xenial -d -f xenial.bs

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....

Please re-open this issue if it's not fixed and give us some more details.

-DennisLfromGA
