### ISSUE TITLE
Cannot switch to chrome OS after entering xenial chroot

### ISSUE THREAD

**Issue by omarwh** [dnschneid/crouton#3150]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170309181220~master:a72a0cb5
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 9000.95.0 (Official Build) stable-channel panther 
kernel: Linux localhost 3.8.11 #1 SMP Fri Mar 3 11:23:58 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:

Cannot switch back to chrome OS after entering chroot either by keyboard shortcut or by logging out of chroot on asus chromebox cn60

#### If known, describe the steps to reproduce the issue:

Enter chroot and then log out of chroot or press ctrl + shift + alt + back or forward  switch shortcuts keys. Chroot will exit into a blank screen which does not accept input.
Machine needs to powered and restarted down to escape this screen

**Comment by DennisLfromGA** [comment]
@omarwh,

It's working for me with the latest crouton version on lxde, gnome, & kde desktops, I don't currently have unity installed.

See if you can switch back to CrOS from a terminal in the chroot using: `croutoncycle cros`

You could also add the 'xiwi' target and see if that will work for you, it's my favorite.

*Hope this helps,*
-**DennisL**

**Comment by abc123me** [comment]
I can't switch back either but the croutoncycle cros works
Also, I can't use bluez becuase of a dbus file not found error

**Comment by JeffreyWerner** [comment]
I have the same issue, but only if I install the xorg target. If I leave out the xorg target and just use x11, I'm able to switch between crouton and chrome. It's too bad; things run really snappy with the xorg target! Anyway, it isn't an ideal fix, but you might try building an environment without xorg and see if that behaves better. Or I think if you add xiwi to your current environment, and do something like "startxiwi -T startxfce4" (or whatever DE you use). 

One difference though between my problem and yours is that I *was* able to go back to chrome by logging out of the DE.  Well, okay, once or twice I had to open a terminal and "sudo killall X.org"

**Comment by srinathh** [comment]
I have run into this issue since yesterday night immediately after ChromeOS upgraded - so I'm guessing something has changed or broken in the update on hotkey binding. It was working fine just before the update (when I switched back to ChromeOS to initiate the update) & stopped working right after the update after reboot.

Working ChromeOS Version
------------------------------------
Version 56.0.2924.110 (64-bit)
Platform 9000.91.0 (Official Build) stable-channel falco
Firmware Google_Falco.4389.92.0

Not Working ChromeOS Version
----------------------------------------
Version 57.0.2987.123 (64-bit)
Platform 9202.56.1 (Official Build) stable-channel falco
Firmware Google_Falco.4389.92.0

**Comment by DennisLfromGA** [comment]
Y'all, Make sure to upgrade your chroot(s) after a CrOS update, it just might take care of the issue.

**Comment by srinathh** [comment]
Just did that. Doesn't fix the issue. Here's the output of `sudo edit-chroot -all`

```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce,cli-extra,extension
host: version 9202.56.1 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Wed Mar 22 23:43:55 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by jheiselman** [comment]
Same issue with the hotkeys, however, `croutoncycle` isn't working for me.

name: code-oss-chroot
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/code-oss-chroot...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xiwi
targets: extension,xfce,xiwi
host: version 9901.77.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:38:30 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/code-oss-chroot...
