### ISSUE TITLE
Can't remove failed install : circular dependency

### ISSUE THREAD

**Issue by seandarcy** [dnschneid/crouton#3153]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
n/a
#### Please describe your issue:
I can't remove the chroots directory on an sd card from a failed install.

#### If known, describe the steps to reproduce the issue:
 sudo rm -r  '/media/removable/SD Card/chroots/trusty'
.................
rm: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ‘/media/removable/SD Card/chroots/trusty/var/host/media/removable/SD Card/chroots/trusty’

All the trusty folders are removed except for var and sys.

**Comment by divx118** [comment]
@seandarcy Just reboot your chromeos and then try it. The chroot is still mounted that is why you can't remove them.
