### ISSUE TITLE
start* permissions fail on sdcard install 

### ISSUE THREAD

**Issue by seandarcy** [dnschneid/crouton#3154]
```
Please paste the output of the following command here: sudo edit-chroot -all


#### Please describe your issue:
Permissions of the host executables installed on sd card screwed up
 
If known, describe the steps to reproduce the issue:
I've just installed trusty lxde,xiwi on an sdcard on a Acer R13.

sudo sh  ~/Downloads/crouton -r trusty -t xiwi,lxde -p '/media/removable/SD Card'

The host executables are installed in bin on the sdcard. 

/media/removable/SD Card $ ls -l bin
total 124
-rwxr-xr-x. 1 root root  7304 Mar 12 11:42 crash_reporter_wrapper
lrwxrwxrwx. 1 root root    11 Mar 12 11:42 delete-chroot -> edit-chroot
-rwxr-xr-x. 1 root root 32045 Mar 12 11:42 edit-chroot
-rwxr-xr-x. 1 root root 34290 Mar 12 11:42 enter-chroot
-rwxr-xr-x. 1 root root 19774 Mar 12 11:42 mount-chroot
-rwxr-xr-x. 1 root root   550 Mar 12 11:42 startlxde
-rwxr-xr-x. 1 root root  2123 Mar 12 11:42 startxiwi
-rwxr-xr-x. 1 root root 18639 Mar 12 11:42 unmount-chroot

All seem to have the correct permissions, but :

chronos@localhost /media/removable/SD Card $ sudo /media/removable/SD\ Card/bin/startlxde 
sudo: unable to execute /media/removable/SD Card/bin/startlxde: Permission denied
chronos@localhost /media/removable/SD Card $ sudo /media/removable/SD\ Card/bin/enter-chroot 
sudo: unable to execute /media/removable/SD Card/bin/enter-chroot: Permission denied

Any thoughts ?

**Comment by divx118** [comment]
You could use:
```
sudo sh /media/removable/SD\ Card/bin/startlxde
```
External media is mounted with no execute flag on chromeos.

**Comment by seandarcy** [comment]
>External media is mounted with no execute flag on chromeos.

Ah. Good to know.

It seems enter-chroot doesn't work on the sdcard :

sudo sh /media/removable/SD\ Card/bin/enter-chroot 
Entering /media/removable/SD Card/chroots/trusty...
mkdir: cannot create directory ‘/run/crouton/media/removable/SD Card/chroots/trusty/sys/fs/cgroup/systemd’: Operation not permitted

Nor does startxiwi:

chronos@localhost ~ $ sudo sh /media/removable/SD\ Card/bin/startxiwi
chronos@localhost ~ $ 

The crouton extension is installed. The icon on chrome shows disconnected.

startlxde does work !

**Comment by divx118** [comment]
@seandarcy startxiwi is used for starting certain apps in your chroot in a chrome window without starting the com[plete windows manager in your case lxde.
So `sudo sh /media/removable/SD\ Card/bin/startxiwi xterm` should work.

**Comment by seandarcy** [comment]
You deserve a lot of thanks for all this help.

sudo startlxde  -X xiwi-tab

was what I was looking for.

Sadly enter-chroot still doesn't work, but gives a different error message:

sudo sh /media/removable/SD\ Card/bin/enter-chroot
Entering /var/host/media/removable/SD Card/chroots/trusty...
mount: Too many levels of symbolic links
WARNING: Unable to register core dump handler.
mount: special device /var/run/shill does not exist
Unmounting /var/host/media/removable/SD Card/chroots/trusty...

I'm beginning to think the space in the chromeos mount point "SD Card" may be part of the problem.

**Comment by DennisLfromGA** [comment]
@seandarcy,

You could change into the directory of the external media first and then try it, like:

`cd /media/removable/SD\ Card/`
`sudo ./bin/enter-chroot`

*Hope this helps,*
-**DennisL**

**Comment by seandarcy** [comment]
I should have tried that. Instead I redid the ext4 partition and set a label :

blkid  /dev/mmcblk0p1
/dev/mmcblk0p1: LABEL="crouton" UUID="4da45f2b-f497-42f7-a193-fa1afc64cea1" TYPE="ext4" PARTUUID="5585da3d-01"

but now chrome won't mount it. chrome does see it:

dmesg
............
mmc1: new ultra high speed SDR104 SDHC card at address aaaa
[ 8251.537339] mmcblk1: mmc1:aaaa SE32G 29.7 GiB 
[ 8251.539810]  mmcblk1: p1

but doesn't mount it. At least nothing in Files.

But df shows it mounted in /home

df
Filesystem                                                   1K-blocks    Used Available Use% Mounted on
/dev/root                                                      1640868 1301392    339476  80% /
devtmpfs                                                       2015356       0   2015356   0% /dev
tmp                                                            2016548    1444   2015104   1% /tmp
run                                                            2016548     412   2016136   1% /run
shmfs                                                          2016548  134472   1882076   7% /dev/shm
/dev/mmcblk0p1                                                25641188 2436596  21879024  11% /home
/dev/mmcblk0p8                                                   11760      24     11412   1% /usr/share/oem

which is weird, because it's not. At least there's no folder in /home for it:

ls -l /home
total 12
drwxr-xr-x. 14 chronos chronos 4096 Mar 13 13:48 chronos
drwxrwx--t.  3 root    root    4096 Feb 23 19:33 root
drwxr-xr-x.  3 root    root    4096 Feb 23 19:33 user

Thanks again.

**Comment by seandarcy** [comment]
Powered off and on. Now ext4 partition appears. Mounted as /media/removable/crouton .

Not a hard rest, just on and off.

**Comment by seandarcy** [comment]
For those who find this issue and want to change the chrome os mount point, you need to relabel the ext* partition to "newname". e2label will do it. If the partition does not have a label, chrome os will assign "SD Cardx", but if a partition label exists, it will use that label as the mount point under /media/removable .
