### ISSUE TITLE
lose crouton on usb after lid close

### ISSUE THREAD

**Issue by westmj** [dnschneid/crouton#3155]
Any way to fix this sleep problem by remounting without reboot?

sudo edit-chroot -all -c /media/removable/usb-ext4/chroots/
name: trusty
encrypted: no
Entering /media/removable/usb-ext4/chroots/trusty...
crouton: version 1-20170228132702~master:21cb695b
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,core,cli-extra,extension,lxde-desktop,x11,xorg
host: version 9000.91.0 (Official Build) stable-channel banjo
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:34:05 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/usb-ext4/chroots/trusty...
chronos@localhost / $

I have trusty on /usb-ext4/chroots/trusty. Things screw up with sleep or closing lid. Acer CB3-531-C4A5 with system details (croutonversion, cat /etc/lsb-release) attached.

chronos@localhost / $ sudo startlxde -c /media/removable/usb-ext4/chroots/ -X xorg -n trusty

works to get started.

After closing the lid, when in crouton, upon opening lid, I have linux for some seconds before screen goes black and cannot get display back, need to use power button to reset.  Shift-control-alt arrow also does not work.

If in chromeOS on lid close, the OS is available on lid opening, but I can not get into crouton with shift-control-alt-arrow. Also, if I CTRL-C out of crouton via cronos, I get:

Hangup
Running exit commands...
.(EE) Server terminated successfully (0). Closing log file.

/usr/bin/xinit: unexpected signal 2
 ...terminated.
/media/removable/usb-ext4/chroots/trusty not found.

At that point, in chromeOS, /usb-ext4 is not mounted in "Files", but another partition on the same device, ntsf-usb, still appears.

Trying to get back in, the /media/removable/usb-ext4 exists but has no files:

chronos@localhost / $ sudo startlxde -c /media/removable/usb-ext4/chroots/ -X xorg -n trusty
Password:
/media/removable/usb-ext4/chroots/trusty does not contain target 'lxde'
chronos@localhost / $ ls /media/removable/
ntsf-usb  usb-ext4
chronos@localhost / $ ls /media/removable/usb-ext4
chronos@localhost / $

To get linux again, a restart is necessary for this rookie. Is there a way to correct this without a restart?

Typical startup:

chronos@localhost / $ sudo startlxde -c /media/removable/usb-ext4/chroots/ -X xorg -n trusty
Password:
Entering /media/removable/usb-ext4/chroots/trusty...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
...
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20170228132702~master:21cb695b
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,core,cli-extra,extension,lxde-desktop,x11,xorg
host: version 9000.91.0 (Official Build) stable-channel banjo
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:34:05 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Agent pid 5312
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE
** Message: main.vala:131: log directory: /home/westmj/.cache/lxsession/LXDE
** Message: main.vala:132: log path: /home/westmj/.cache/lxsession/LXDE/run.log
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch

(trusty)westmj@localhost:~$ croutonversion
crouton: version 1-20170228132702~master:21cb695b
release: trusty
architecture: amd64
xmethod: xorg
targets: audio,core,cli-extra,extension,lxde-desktop,x11,xorg
host: version 9000.91.0 (Official Build) stable-channel banjo
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:34:05 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
(trusty)westmj@localhost:~$ ^C

chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={3A837630-D749-4B7A-86C1-DB0ECC07A08B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={3A837630-D749-4B7A-86C1-DB0ECC07A08B}
CHROMEOS_RELEASE_BOARD=banjo-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=91
CHROMEOS_RELEASE_BUILDER_PATH=banjo-release/R56-9000.91.0
CHROMEOS_RELEASE_BUILD_NUMBER=9000
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=56
CHROMEOS_RELEASE_DESCRIPTION=9000.91.0 (Official Build) stable-channel banjo
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9000.91.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9000.91.0

Thanks!

**Comment by ipstone** [comment]
I have similar issues when running crouton on thinkpad chromebook 13 of an USB drive.
The system runs fine before sleeping, but I could not wake it up to work properly (though sometimes the interface is responsive, but disk connection seems to be lost after waking up).

Might there need to be a waking up/mounting disk process invoked when running crouton from the usb drive?

As I tested my setup, with internal crouton running on the laptop disk, everything works fine when waking up.

thanks

**Comment by coderofsalvation** [comment]
The pattern here is that chromeos seems to remount all usb disk with `noexec`-permissions.
Im running crouton on the internal disk, with some (large) linux-folders symbolically linked to my usb-drive.
Everytime when i wakeup my chromebook, i need to run this command:

`mount | grep USB | grep noexec && sudo mount -o remount,exec /media/removable/USB\ Drive`

It basically checks if my usbdrive is remounted with `noexec`, and remounts it with `exec` if so.

I haven't figured out how to hook this into the wakeup-event, because eventually that would fix it.
