### ISSUE TITLE
Start xfce4 problems

### ISSUE THREAD

**Issue by john2day** [dnschneid/crouton#3157]
```
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20161129162558~master:5f2f11f9
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 9000.91.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13530-g8bc6aca #1 SMP PREEMPT Wed Feb 22 23:41:44 PST 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170309181220~master:a72a0cb5
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9000.91.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13530-g8bc6aca #1 SMP PREEMPT Wed Feb 22 23:41:44 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

When I run the following command:
chronos@localhost / $ sudo enter-chroot startxfce4

I get the following result:
Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.1
Release Date: 2017-01-11
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-13530-g8bc6aca #1 SMP PREEMPT Wed Feb 22 23:41:44 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=37a48586-4522-0341-afc2-e07a88425af2/PARTNROFF=1 hashtree=PARTUUID=37a48586-4522-0341-afc2-e07a88425af2/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=eb306a8393dae9c82e6efa835a13e93450079edb salt=97e953709bac895d0fb8166de0408682a846f1c4b700cc3127b1c1ebcdf7b3d2" noinitrd vt.global_cursor_default=0 kern_guid=37a48586-4522-0341-afc2-e07a88425af2 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 20 January 2017  02:50:48AM
xorg-server 2:1.19.1-4 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Mar 14 06:36:24 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/lib/xorg/Xorg: symbol lookup error: /usr/lib/xorg/modules/drivers/dummy_drv.so: undefined symbol: ChangeWindowProperty
^C
Session terminated, terminating shell.../usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: unexpected signal 2
 ...terminated.
Unmounting /mnt/stateful_partition/crouton/chroots/kali...

This happens whenever I start xfce4.

**Comment by john2day** [comment]
I have tried multiple times, and I don't know how to fix it.

Thanks for any help.

**Comment by DennisLfromGA** [comment]
@john2day,

If you run `sudo enter-chroot startxfce4` like you show above it will try to launch your `kali-rolling` / `xfce4` desktop using the `xiwi` xmethod. That particular chroot is old so maybe just updating it will fix it.
Use this to update it: `sudo sh ~/Downloads/crouton -n kali-rolling -u`

Your other chroot is a `xenial`  / `xfce4` desktop using the `xorg` xmethod, it's fully up-to-date.
Does it work if you enter:  `sudo startxfce4 -n xenial` ?

*Hope this helps,*
-**DennisL**

**Comment by john2day** [comment]
Thanks for your helpful comments, but I have decided to not use this method to install Linux.

**Comment by DennisLfromGA** [comment]
@john2day,

No problem, hope you find something that'll work for you.

*Hope this helps,*
-**DennisL**
