### ISSUE TITLE
New to Xcode 

### ISSUE THREAD

**Issue by wadst3** [dnschneid/crouton#3159]
Hi, I'm more than sure this has been answered before but i've been trying to find a solution in forums and tried using other methods and i still can't find a solution that works. My issue is that i can load a page fine:
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    NSString *fullURL = @"https://www.something.com";
    NSURL *url = [NSURL URLWithString:fullURL];
    NSLog(@"first page loaded=%@",url);
    NSURLRequest *requestObj = [NSURLRequest requestWithURL: url];
    [_webViewer loadRequest:requestObj];
}
but when i try to detect when a url link has been clicked, i can't seem to figure out why shouldStartLoadWithRequest never gets called:
- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType {
   if (navigationType == UIWebViewNavigationTypeLinkClicked) {
      NSURL *strurl = request.URL;
      NSString *urlString = strurl.relativeString;
      NSLog(@"link clicked=%@",urlString);
      NSLog(@"%@",[request.URL lastPathComponent]);
   }
   return YES;
}
Any help would be greatly appreciated

**Comment by divx118** [comment]
Yes it has been answered before #262

I wonder how you did end up here on the crouton issue tracker instead of the github whatever issue tracker  where you should have posted.

**Comment by wadst3** [comment]
oh, i just googled searched for how to submit question to GitHub and send me here.

**Comment by dnschneid** [comment]
Oh snap, #188 has been the top result for that for the past four years...

**Comment by DennisLfromGA** [comment]
The price of fame...
