### ISSUE TITLE
Can't switch away and back (AIGLX)

### ISSUE THREAD

**Issue by wycats** [dnschneid/crouton#316]
I can start my windowing manager fine (via startgnome, startxfce, etc.), but if I leave (via ctrl-alt-back) and return, I see the Developer Console, and:

```
(II) AIGLX: Suspending AIGLX clients for VT switch.
```

I don't know how to get the GUI back.

**Comment by Rivas2016** [comment]
Hi, 

I can only switch between desktops using ctr-alt forward/back and am running into the same error. crt-alt-shift back is not an option. Any ideas?
