### ISSUE TITLE
Error creating textual authentication agent (admin/sudo prompt)

### ISSUE THREAD

**Issue by liltinkerer** [dnschneid/crouton#3160]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170309181220~master:a72a0cb5
release: xenial
architecture: amd64
xmethod: xorg
targets: x11,core,audio,cli-extra,extension,xiwi,xorg,xfce
host: version 9000.91.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13530-g8bc6aca #1 SMP PREEMPT Wed Feb 22 23:33:57 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

I cannot launch programs that need administrative privileges (gparted, software center, synaptic etc). Sometimes my Chromebook freezes (have to force restart), or just chroot and I have to force unmount. Launching from command line using gksudo opens the program.

`Error creating textual authentication agent: Error opening current controlling terminal for the process ('/dev/tty'): No such device or address`

If I do `/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1`, I get:

`(polkit-gnome-authentication-agent-1:20723): polkit-gnome-1-WARNING **: Unable to determine the session we are in: No session for pid 20723`

Which sort of makes sense since x-server is not ran as root, I guess. Is there any fix to this or should I just use gksudo instead of opening things from the menu.

#### If known, describe the steps to reproduce the issue:

Run a program needing administrative privileges not from command line using gksudo, but from the DE's menu.

**Comment by jayvir101** [comment]
I have the same issue and I don't know how to fix it. Can Someone please fix this issue.

**Comment by liltinkerer** [comment]
@jayvir101 In the meantime, you can launch the program you want from terminal using `gksudo gparted` -- gparted as an example of the program you need.

**Comment by jayvir101** [comment]
Thx and I'll keep checking back to see if bug as been fixed.

**Comment by jayvir101** [comment]
I think its also DBus that is cause this error. There is a folder at ` ~/.dbus` . You might find something interesting.
