### ISSUE TITLE
Crouton keeps switching to Debian Jessie

### ISSUE THREAD

**Issue by CROUUUUTON** [dnschneid/crouton#3163]
So my friend was trying to install Ubuntu via crouton, he went with a debian release first, then xenial ubuntu, but the chroot keeps switching to jessie. Any help? I can't paste the commands and stuff, this was on his PC not mine. Any help David? Or anyone else who has a fix?

**Comment by jayvir101** [comment]
try deleting the chroot that jessie was installed on by doing `delete-chroot chrootname`
