### ISSUE TITLE
Crouton disabling access to internal and external storage

### ISSUE THREAD

**Issue by mobamoba** [dnschneid/crouton#3165]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xiwi
targets: lxde,xiwi,e17
host: version 9000.91.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13530-g8bc6aca #1 SMP PREEMPT Wed Feb 22 23:41:44 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

I've noticed this recently so I'm guessing it's a consequence of a change somewhere in Chrome OS, but, after launching Crouton - I've tried Trusty and Xenial with XFCE and LXDE - I lose access to both internal storage and external storage until I reboot. Chrome keeps running fine. However, if I open the file manager in Chrome, it's either completely empty (not even directories, just nothing) or there's the green "loading" bar but nothing ever happens.

When I run a mount command in a shell, I can see all the drives listed; they're simply completely inaccessible to both Chrome and to Crouton.

Logging out of Crouton does not resolve the problem. The only resolution is a reboot.

I have no clue where to start debugging this, but I'm able to reproduce it over and over. Simply doing a backup of an unmounted chroot, for example, will cause the drive failure on remounting. I've tried wiping my chroots and starting from scratch with a fully updated crouton, but that doesn't solve the problem either.

Additionally, crouton never fully unmounts (likely because it's lost access to the drive). It logs out and shuts down fine but will never fully unmount.

**Comment by jayvir101** [comment]
Is there any error messages it show when the bug happens.

**Comment by mobamoba** [comment]
No, there are no bugs being generated. Access to all drives simply vanishes. It's weird because, for example, I can take a screenshot with my Chromebook when this happens. I can't open the screenshot or copy/paste the screenshot. On reboot, however, the screenshot is sitting there on my drive.

This made me wonder if some kind of permissions issue was being generated by crouton (as opposed to a hardware issue of some kind).

**Comment by jayvir101** [comment]
I also think its something to do with crouton rather then the hardware. I'll try it out on my chromebook and see if I get the same result.

**Comment by mobamoba** [comment]
An update that might be helpful in tracking down the problem: When I run a program in app mode - sudo startxiwi etc. - the problem of the vanishing internal and external drives never happens - everything works fine. The moment I start crouton in full desktop mode, the problem with the drives shows up.

Dunno if that helps debug but thought I'd pass it along.

**Comment by liltinkerer** [comment]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: x11,keyboard,core,audio,cli-extra,extension,xiwi,xorg,xfce
host: version 9202.56.1 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-13753-gc65690b #1 SMP PREEMPT Wed Mar 22 23:49:40 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

I can confirm the same bug. I can't really tell for sure how and when it's happening, since it's random, but only reboot helps. @mobamoba does it always happen with you?

**Comment by mobamoba** [comment]
Yeah. There's something in crouton that's affecting disk access in some way because it happens basically every time for me.
