### ISSUE TITLE
"sudo startxfce4", does this. 

### ISSUE THREAD

**Issue by MaxSpiralAxle** [dnschneid/crouton#3167]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 8872.76.0 (Official Build) stable-channel nyan_blaze 
kernel: Linux localhost 3.10.18 #1 SMP Fri Jan 6 23:44:58 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
I try to do "sudo startxfce4", and I get this error: " http://prntscr.com/elke5f ".

#### If known, describe the steps to reproduce the issue:
Uh, do "sudo startxfce4"..?

**Comment by liltinkerer** [comment]
What is your Chromebook's model?

**Comment by DennisLfromGA** [comment]
@liltinkerer,

@MaxSpiralAxle's Chromebook is the [HP Chromebook 14 G3 (Blaze)](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices#goog-ws-list-table) which is one of the few using the Tegra K1 chips. They've all been freonized now though so it should be easier to deal witn.

-**DennisL**
