### ISSUE TITLE
backup on sd woes

### ISSUE THREAD

**Issue by seandarcy** [dnschneid/crouton#3172]
Please paste the output of the following command here: sudo edit-chroot -all
 /media/removable/crouton $ sudo sh bin/edit-chroot -all
name: xenial
encrypted: no
Entering /media/removable/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: arm64
xmethod: xiwi
targets: lxde,xiwi
host: version 9000.91.0 (Official Build) stable-channel elm 
kernel: Linux localhost 3.18.0-13530-g8bc6aca #1 SMP PREEMPT Wed Feb 22 23:26:43 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/crouton/chroots/xenial...

#### Please describe your issue:

I've got an sdcard with 2 partitons: 1: "crouton" ext4 with xenial. 2: "data" exfat. I want to backup xenial to exfat partition, but edit-chroots doesn't recognize the chroot name:

chronos@localhost /media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b /media/removable/crouton/chroots/xenial
Invalid chroot name '/media/removable/crouton/chroots/xenial'.
chronos@localhost /media/removable/crouton $ ls /media/removable/crouton/chroots/xenial
bin  boot  dev  etc  home  lib  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

#### If known, describe the steps to reproduce the issue:

Also tried 
media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b /media/removable/crouton/chroots
Invalid chroot name '/media/removable/crouton/chroots'.
chronos@localhost /media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b /media/removable/crouton/
Invalid chroot name '/media/removable/crouton/'.

**Comment by DennisLfromGA** [comment]
@seandarcy,

Try appending *just* the name of the chroot, `xenial`, to that command, like -

`media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b /media/removable/crouton/chroots`**`xenial`**

If that doesn't work you also might try using the '-c' option with it like: 

`media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b /media/removable/crouton/chroots` `-c /media/removable/crouton/chroots`**`xenial`**

*Hope this helps,*
-**DennisL**

**Comment by seandarcy** [comment]
Thanks for the suggestions. I must be doing something wrong:

chronos@localhost /media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data/ -b /media/removable/crouton/chroots xenial
Invalid chroot name '/media/removable/crouton/chroots'.
chronos@localhost /media/removable/crouton $ ls
bin  chroots  data  lost+found  start-xiwi-tab  unencrypted
chronos@localhost /media/removable/crouton $ ls /media/removable/crouton/chroots
xenial
chronos@localhost /media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data/ -b /media/removable/crouton/chroots -c /media/removable/crouton/chroots xenial

immediately returns, no error message, but does nothing. Only file in backup is an old backup:

chronos@localhost /media/removable/crouton $ ls -l /media/removable/data/backup/
total 447104
-rwxr-xr-x. 1 chronos chronos 457815678 Mar 18 11:25 xenial-20170318-1123.tar.gz

**Comment by DennisLfromGA** [comment]
@seandarcy,

Sorry I hadn't noticed this before but the '**-b**' option does *not* take an argument.
Either of these *should* work *if* it accepts your '*exfat*' partition:

`media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b`**`xenial`**

or

`media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b`**`-c /media/removable/crouton/chroots xenial`**

*Hope this helps,*
-**DennisL**

**Comment by seandarcy** [comment]
I owe you a beer, or even two:

chronos@localhost /media/removable/crouton $ sudo sh bin/edit-chroot -f /media/removable/data -b  -c /media/removable/crouton/chroots xenial
Unmounting /media/removable/crouton/chroots/xenial...
tar: xenial/home/r13/.cache/keyring-ZKP8WY/control: socket ignoredovable/data/xenial-20170326-1356.tar.gz...
Finished backing up /media/removable/crouton/chroots/xenial to /media/removable/data/xenial-20170326-1356.tar.gz

Thanks for sticking with me here.
