### ISSUE TITLE
Split `xiwi` into a standalone tool

### ISSUE THREAD

**Issue by jbaum98** [dnschneid/crouton#3173]
Although crouton is an amazing project, I think there are other ways people might want to install software on their chromebooks like the [Nix package manger](https://nixos.org/nix) and [Chromebrew](https://skycocker.github.io/chromebrew). The `xiwi` tool would be useful to anyone using a chromebook from the command line who would like to be able to use graphical applications they've installed alongside ChromeOS apps and browser windows.

Is there a way to split the codebase so that one could install `xiwi` without crouton?

With some guidance, I'd be willing to try and do this myself. I just don't really understand the crouton codebase well enough to understand where to start.

**Comment by kirbyfan64** [comment]
:+1:

**Comment by DennisLfromGA** [comment]
This may not be exactly what you are after but you can use `startxiwi` to launch a gui app in a chroot -
```
startxiwi [options] chroot_app [parameters]

Wraps enter-chroot to launch a window or tab in Chromium OS for any graphical application.
Applications launched in this way show in independent windows or tabs.

By default, it will use the primary user on the first xiwi-enabled chroot found and launch
the chroot_app in a window.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -F          Launch the chroot_app full-screen.
    -T          Launch the chroot_app in a tab.
    -f          Prevent xiwi from quitting automatically. (see NOTE below)

NOTE:
xiwi will normally close when the application returns. Some gui applications
fork before or during normal operation, which can confuse xiwi and cause it to
quit prematurely. If your application does not have a parameter that prevents
it from forking, and crouton is unable to automatically detect the fork, you can
use -f to prevent xiwi from quitting automatically.
xiwi will quit if you close the Chromium OS window when nothing is displayed.
  
You can cycle through multiple windows inside the application
via Ctrl-Alt-Tab/Ctrl-Alt-Shift-Tab, or close them via Ctrl-Alt-Shift-Escape.
If the chroot_app begins with 'start' but you still want to
use the default window manager, specify the full path of the application.
```

*Hope this helps,*
-**DennisL**

**Comment by spaceface777** [comment]
@jbaum98 I agree

**Comment by JL2210** [comment]
Ping.
I don't think this will work. `xiwi` is just a shell script that uses Crouton to forward X from Linux to the Crouton integration extension (NaCL, deprecated). The code of the Crouton integration may be useful, but it probably wouldn't be practical to get it working without a proper NaCL environment and Crouton with native X libs.

**Comment by sudo-power** [comment]
I think xiwi would be great for things like chromebrew! Lets hope this becomes a thing.

**Comment by refi64** [comment]
Nowadays, since Chrome OS already exposes a Wayland socket, wouldn't it be possible to use Sommelier instead?
