### ISSUE TITLE
GNU Octave only opens in a terminal window

### ISSUE THREAD

**Issue by uncripted** [dnschneid/crouton#3174]
```
name: jessie
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/jessie...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: xorg,xiwi,xbmc,x11,touch,keyboard,gtk-extra,extension,core,cli-extra,chrome,audio,xfce
host: version 9000.91.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13530-g8bc6aca #1 SMP PREEMPT Wed Feb 22 23:41:44 PST 2017 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/jessie as another instance is using it.
```

#### Please describe your issue:
I am running Debian Jessie xfce in Crouton. I installed GNU Octave (my primary reason for using Crouton) using apt-get, but when I open the application it opens in a terminal as opposed to a GUI. This is a bit of an obstacle for the work I need to do.

GNU Octave has a terminal setting used for debugging. Maybe it is somehow booting into that by default? I hope that there is a way to fix this and get the GUI running, but I'm not sure where to start. Should I mess around with the system files or should I try creating a new chroot with Ubuntu installed instead? I'm already using all the targets I think I would need so I don't think that's it. Any help would be appreciated.

**Comment by JoseJX** [comment]
It's been a while since I've used Octave, but try:
`octave --force-gui`

**Comment by uncripted** [comment]
Thanks! That worked. After looking into it, I found that the version installed by Debian is only 3.8, which opens in terminal by default and the GUI is in beta. The latest version (4.2) doesn't appear to be in the Debian repository for some odd reason. I'll probably try switching to an Ubuntu chroot and see if I fare better.

Thanks so much again.
