### ISSUE TITLE
Hardware acceleration on the chromebook c302ca

### ISSUE THREAD

**Issue by TesseractCat** [dnschneid/crouton#3177]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xiwi
targets: touch,lxde,xiwi
host: version 9202.54.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-13753-gc65690b #1 SMP PREEMPT Sat Mar 18 09:22:59 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

After installing crouton on the c302ca, and attempting to run graphics intensive applications on it, I noticed that instead of using hardware acceleration, it is using the driver `Gallium 0.4 on llvmpipe`. I have tried a few different fixes, like updating intel drivers using this tool: https://01.org/linuxgraphics/downloads/intel-graphics-update-tool-linux-os-v2.0.2. But nothing seems to work.

#### If known, describe the steps to reproduce the issue:

1. Install crouton with the targets mentioned above.
2. Install mesa-utils
3. Run glx-gears -info
4. Check the GL_RENDERER output.

**Comment by DennisLfromGA** [comment]
@TesseractCat,

Yes, xmethod 'xiwi' does not offer hardware acceleration atm.
You could install xmethod 'xorg' that does on most platforms I believe.
I'm not sure it's been tested on the ASUS Chromebook Flip C302 yet.

*Hope this helps,*
-**DennisL**

**Comment by TesseractCat** [comment]
Ok, so I ran the command `sudo bash crouton -t xorg -u`. Then I started lxde with `sudo startlxde -X xorg` and that fixed the issue!

Thanks!

**Comment by DennisLfromGA** [comment]
@TesseractCat,

**_Good job_** & _you're welcome_.

-**DennisL**

**P.S.** If you're satisfied with this outcome you can close the issue.
