### ISSUE TITLE
Is it possible to remove 'noexec' in chroot for a mounted SD Card?

### ISSUE THREAD

**Issue by JeffreyWerner** [dnschneid/crouton#3178]
```
$ sudo edit-chroot -all
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: arm64
xmethod: xiwi
targets: xfce-desktop,touch,extension,xiwi
host: version 9000.91.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.21-06459-ge91c124 #1 SMP PREEMPT Wed Feb 22 23:26:03 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
```

#### Please describe your issue:
Sorry, this might be more of a question than a bug, but on a chromebook most folks need to use the SD card as a second hard drive and this seems like an issue where folks would want a quick fix of some kind. Chrome has the SD card mounted with "noexec." My SD card is my main data storage location, though my chroot environment itself is installed on the hard drive. So, I have lots of folders with scripts in them on the SD card, but I'm unable to run any of those scripts because there is a noexec attribute to the mounted SD card. 

Can I get the environment inside the chroot to think that the SD Card is mounted *without* the noexec flag? I do not want to run scripts as root, that would be a mess, and I don't want the chroot to unmount and remount the SD Card when it starts, that would be a mess for everything in Chrome outside the chroot. Am I stuck with Chrome's noexec flag for everything on the SD card, or is there perhaps a trick to getting the chroot to think that I *can* execute scripts?

The sd card is formatted ext4. Both Chrome and the chroot have perfectly fine-working read and write privilages to the sd card. I always leave it in, and it's mounted automatically by chrome when I boot, and that's all pretty seamless.

I assume that if I try to change the way Chrome mounts the SD card, rather than changing something in the chroot, this would be a solution that breaks itself at Google's whim.

#### If known, describe the steps to reproduce the issue:
```
$ sudo enter-chroot
$ cd /media/removable/SD\ Card/MyData
$ echo 'echo hi' > scripttest
$ chmod a+x scripttest
$ ./scripttest
bash: ./scripttest: Permission denied
$ mount | grep 'removable'
/dev/mmcblk1p1 on /var/host/media/removable/SD Card type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,seclabel,data=ordered)
```
Please, if anyone knows, can I maybe mount it a second time in the chroot, somehow, while leaving Chrome's mount alone?  In a reliable way that won't break things when I start and stop chroots?

Or, perhaps, is the chroot's mount table totally independent of chrome's? and maybe can I just edit /etc/fstab in the chroot environment without affecting Chrome? Sorry this is where I reveal that I have no idea how this chroot business really works.

Thanks for your time and help!!!

**Comment by JeffreyWerner** [comment]
One additional note. An annoying partial solution for now is that I can use a bash script with
`sh /path/to/bash/script`
and e.g. a perl script with
`perl /path/to/perl/script`
but that still leaves out binaries, and the utility of having folders in my PATH.

**Comment by JeffreyWerner** [comment]
I found [this](https://github.com/dnschneid/crouton/issues/928) which suggests that the easiest thing to do is just do this
`sudo mount -o remount,exec /media/removable/SD\ Card`
Which works, so I guess I just have two questions:

- What happens if something is writing to the card when that remount happens?  I tested it while rsync was writing to the card and it didn't seem to notice. Are there no worries here?
- Where can I best put this? It's an sudo command, so in the bashrc would be annoying, would have to enter a password.

**Comment by dnschneid** [comment]
> What happens if something is writing to the card when that remount happens? I tested it while rsync was writing to the card and it didn't seem to notice. Are there no worries here?

It shouldn't impact anything.

> Where can I best put this? It's an sudo command, so in the bashrc would be annoying, would have to enter a password

If the SD card is present when you enter the chroot, add the remount to the chroot's /etc/rc.local.  If you're inserting and removing the SD card constantly, your options aren't as good...

**Comment by JeffreyWerner** [comment]
Thanks for the help, that works perfectly!  

I almost have a perfectly smooth-working chroot set up for productivity... now to back it up before I go ahead and break it. :)
