### ISSUE TITLE
I think the new chromeOS update broke the script for flipping back and forth between chromeOS and crouton

### ISSUE THREAD

**Issue by Mediocorite** [dnschneid/crouton#3180]
The keyboard shortcuts no longer work. Once I start chroot session, I'm locked out from chromeOS until I log out (which really sucks cause I was a heavy user of crouton clipboard extension)

I originally encountered this issue in the beta version 56, and now after multiple powerwashes and trials between beta, stable and dev I'm on stable channel version 57. I have updated, reinstalled numerous times already.

**Comment by DennisLfromGA** [comment]
@Mediocorite,

So we can get a better starting point, please show us the output of `sudo edit-chroot -all`

> The keyboard shortcuts no longer work.

Are you referring to switching to / from CrOS & your chroot(s) using the key-combo: <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>left-arrow / right-arrow</kbd> ?

Or do you mean the support for Chromebook keyboard special keys provided by the `keyboard` target?

-**DennisL**

**Comment by gabriel-wilkes** [comment]
I can confirm that the same happened to me on update to stable channel 57. Here is the output of my `sudo edit-chroot -all` if it helps:

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xorg
targets: extension,xfce
host: version 9202.56.1 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Wed Mar 22 23:43:55 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by DennisLfromGA** [comment]
@Mediocorite,

>  is there some way besides the key-combo?

Yes, I do it using the 'crouton integration' extension.

Even though you are using just the '`xorg`' xmethod you can install the '`extension`' target and also the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension from the Chrome Web Store and switch from CrOS to any of your running chroots using the  '`xorg`' or '`xiwi`' xmethod. 

Just click on the extension for a drop-down menu and then select to chroot you want to switch to, see mine below -

![screenshot 2017-03-30 at 11 33 47 am](https://cloud.githubusercontent.com/assets/3418772/24512512/c498c9da-153c-11e7-83c6-8d630051ad3b.png)

*Hope this helps,*
-**DennisL**

**Comment by Mediocorite** [comment]
Output:-

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,extension,xorg,unity
host: version 9202.56.1 (Official Build) stable-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Wed Mar 22 23:43:55 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

> Yes, I do it using the 'crouton integration' extension.

Even though you are using just the 'xorg' xmethod you can install the 'extension' target and also the 'crouton integration' extension from the Chrome Web Store and switch from CrOS to any of your running chroots using the 'xorg' or 'xiwi' xmethod.

Just click on the extension for a drop-down menu and then select to chroot you want to switch to, see mine below -


Yes but this method doesn't let me switch back to chromeOS back after entering the chroot.

**Comment by DennisLfromGA** [comment]
@Mediocorite,

I'm sorry, my response was meant for @gabriel-wilkes but I addressed it incorrectly, I've since corrected it.
@gabriel-wilkes said:

> I can switch to ChromeOS with the command croutoncycle cros but not sure how to switch back to crouton, is there some way besides the key-combo?

You said:

> Yes but this method doesn't let me switch back to chromeOS back after entering the chroot.

You may then have to revert to the method in a chroot terminal session using: `croutoncycle cros`

*Hope this helps,*
-**DennisL**

**Comment by gabriel-wilkes** [comment]
@DennisLfromGA Thanks, works perfectly, I had the crouton integration extension from the Chrome Store installed but since I've always used the key-combo, never realized that it could be used that way.

**Comment by Mediocorite** [comment]
@DennisLfromGA 
Thanks for the command. I set up a keyboard shortcut in ubuntu that triggers it with the terminal.

**Comment by grandrew** [comment]
Hi! I can't see it fixed. Is the fix committed into master? They key combos still don't work - instead the xfce's default back/forward actions kick in and no switching occurs disregarding the modifier keys.

**Comment by DennisLfromGA** [comment]
@grandrew,

Please show us the output of: `sudo edit-chroot -all`

-**DennisL**

**Comment by grandrew** [comment]
That seems to be a bug in chrome OS related to https://bugs.chromium.org/p/chromium/issues/detail?id=712709 on certain platforms

**Comment by Mediocorite** [comment]
I believe I should reopen the issue as we still haven't solved it, but rather discovered a work around. The key combos still remain unusable.

**Comment by grandrew** [comment]
I can confirm that the upstream issue is now fixed and stable CrOS 58 works as expected: https://bugs.chromium.org/p/chromium/issues/detail?id=701643

**Comment by DennisLfromGA** [comment]
@grandrew,

Thanx for that update.
If @Mediocorite could test this on M58 and it works then this can probably be put to bed.

-**DennisL**

**Comment by Mediocorite** [comment]
After doing a quick update, things are back to normal :]

**Comment by k1ypp** [comment]
I too am suffering this problem with switching the OS from Chrome to Linux KDE and back. Yes, I am including the shift key. It was working and then just stopped. Being a newbie I'm not certain I know how to "test M58." How does one try that?

chronos@localhost / $ sudo edit-chroot -all
Password: 
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20170315143304~master:95589555
release: precise
architecture: amd64
xmethod: xiwi
targets: xiwi,unity,kde
host: version 9334.58.0 (Official Build) stable-channel winky 
kernel: Linux localhost 4.4.44-07356-g3b524e9 #1 SMP PREEMPT Wed Apr 26 12:20:16 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by k1ypp** [comment]
Additional information: If I start a Linux KDE session in Crouton and don't do anything (for example, start an app, such as notebook or something) I AM able to use the Alt-CTRL-Shift---> function to switch back to Chrome. Once I do anything, such as change the panel size at the bottom of the screen, then the function fails.

**Comment by k1ypp** [comment]
Crickets? Has anyone else seen this problem as described above? Am I alone on this? I can't believe I'm the only one seeing this.
Thanks.

**Comment by DennisLfromGA** [comment]
@k1ypp,

Sorry, but it works for me on all of my chroots and all of my desktops.

```
Listing chroot targets in: /var/crouton/chroots -
gentoo:targets:         xiwi,cli-extra,keyboard,lxde-desktop,chrome-beta

trusty:targets:         ,xiwi,xorg,keyboard,cli-extra,lxde-desktop,chrome-beta

xen.elem:targets:       ,xorg,xiwi,elementary,cli-extra,chrome-beta

xenial:targets:         ,xiwi,xorg,lxde-desktop,cli-extra,keyboard,chrome-beta

xenial-lxqt:targets:    ,xorg,xiwi,lxqt,gtk-extra,keyboard,chrome-beta

xenial-mate:targets:    ,xorg,xiwi,mate,keyboard,gtk-extra,chrome-beta

zesty:targets:  ,gnome-desktop,kde-desktop,xorg,xiwi,xfce,cli-extra,keyboard,chrome-beta
```

-**DennisL**
