### ISSUE TITLE
Kali-rolling fails to launch after first time set-up

### ISSUE THREAD

**Issue by 4rson** [dnschneid/crouton#3182]
```
Please paste the output of the following command here: sudo edit-chroot -all

kali

```

#### Please describe your issue:

I've installed kali-rolling with KDE-desktop onto my Chromebook Pixel 2013 which is running stable OS version 57.0.2987.123 (64-bit). After installation I installed the latest kali metapackage "kali-linux-all". After I exit the croot and restart my laptop I am facing the following error once I try to enter the chroot again via "sudo startkde -n kali"

crosh> shell chronos@localhost / $ sudo startkde -n kali Entering /mnt/stateful_partition/crouton/chroots/kali...
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
X.Org X Server 1.19.2 Release Date: 2017-03-02 X Protocol Version 11, Revision 0 Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Mar 22 23:46:47 PDT 2017 x86_64 Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=39be837f-3819-9840-a4a0-45e94adabc2e/PARTNROFF=1 hashtree=PARTUUID=39be837f-3819-9840-a4a0-45e94adabc2e/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=78ae12c7753ef20aca7df72c42928a9a2a7c9567 salt=b498de76873fb744ad0d5e41a941f76e73de930f7d72ab4e56feb1b78891c4ab" noinitrd vt.global_cursor_default=0 kern_guid=39be837f-3819-9840-a4a0-45e94adabc2e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3 gpt Build Date: 03 March 2017 03:14:41PM xorg-server 2:1.19.2-1 (https://www.debian.org/support) Current version of pixman: 0.34.0 Before reporting problems, check http://wiki.x.org to make sure that you have the latest version. Markers: (--) probed, (**) from config file, (==) default setting, (++) from command line, (!!) notice, (II) informational, (WW) warning, (EE) error, (NI) not implemented, (??) unknown. (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Mar 29 16:24:17 2017 (==) Using system config directory "/usr/share/X11/xorg.conf.d" (EE) Fatal server error: (EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory) (EE) (EE) Please consult the The X.Org Foundation support at http://wiki.x.org for help. (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information. (EE) (EE) Server terminated with error (1). Closing log file. /usr/bin/xinit: giving up /usr/bin/xinit: unable to connect to X server: Connection refused /usr/bin/xinit: server error Unmounting /mnt/stateful_partition/crouton/chroots/kali...

#### If known, describe the steps to reproduce the issue:

Chromebook Pixel 2013 running latest Stable branch of ChromeOS.

1. Install kali-rolling via "sudo sh ~/Downloads/crouton -r kali-rolling -t audio,chrome,core,extension,keyboard,kde-desktop -n kali"

2. Install Kali Metapackage via "sudo install kali-linux-all" within Chroot.

3. Shutdown/exit Chroot, then try and enter it again via "sudo startkde -n kali"

**Comment by WagnerBeccard** [comment]
Same heere ( i think..) 
But, attention. Linux noob incoming.

```
(kali)kali@localhost:~$ croutonversion
crouton: version 1-20170315143304~master:95589555
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: audio,chrome,core,extension,keyboard,kde-desktop
host: version 9413.0.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 3.18.0-14511-g55d103f4e8cd #1 SMP PREEMPT Wed Mar 29 18:46:15 PDT 2017 x86_64 GNU/Linux
freon: yes
```

sudo startkde -n kali
```

Entering /mnt/stateful_partition/crouton/chroots/kali...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-14511-g55d103f4e8cd #1 SMP PREEMPT Wed Mar 29 18:46:15 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=cf467906-38d9-614c-85ac-d989d41961bd/PARTNROFF=1 hashtree=PARTUUID=cf467906-38d9-614c-85ac-d989d41961bd/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=732c71f68e55840f8da5c1ce6cbe3a45821d9233 salt=59ffc584990f1c90700db58e4bcc7f200a3fa89c6a95b7ca6a5fb9ff251e4d77" noinitrd vt.global_cursor_default=0 kern_guid=cf467906-38d9-614c-85ac-d989d41961bd add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 03 March 2017  03:14:41PM
xorg-server 2:1.19.2-1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Apr 10 16:12:28 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali...

```


But! - WtF - Wow for this work! 
at least it worked once =D

**Comment by 4rson** [comment]
Did further testing, the error is generated after installing the kali-linux-all metapackage. I'm going to test the other metapackages now.

**Comment by daangruijters** [comment]
@4rson Currently having the same issue and looking in to it. Let me know if you found something

**Comment by 4rson** [comment]
@daangruijters I tested the kali-linux-full metapackage as well, same problem occurs. If I don't install any of the kali metapackages I can keep using kali-rolling.

**Comment by Cryptiiiic** [comment]
@4rson How do i prevent It from installing meta packages

**Comment by TrueExile** [comment]
@4rson @daangruijters I too am brand new and having the same problem. However the guide I fallowed only had me use
"sudo sh ~/Downloads/croutons -r kali-rolling -t xfce"
I have a symbolic link pointing the chroot directory to my micro sd card slot. and a ubuntu release 
" -r trusty -t xfce"  installed and brought up a gui 

the kali starts out with the same error you have. however I can still use the kali command line by using 
"sudo enter-chroot -kali-rolling"  but if I try to start ether gnome or xfce it brings up the same error. 

Ill keep working at it but if you find anything please let me know. 
-Cheers
