### ISSUE TITLE
Add a .desktop file for interacting with Chromium OS

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#3183]
crouton's `extension` target should install a .desktop file for interacting with Chromium OS.  Running it should `croutoncycle cros`.  It should be able to handle URLs by passing them to `croutonurlhandler`.

The MIME types should be properly set, so that distros like Gentoo pick up on it as a default URL handler.

**Comment by keyteben** [comment]
I am currently having a slight problem with my hp chromebook 14 - I entered dev mode and installed crouton and then ubuntu but couldn't get back to ubuntu, once I returned to chromeos. I tried everything including opening up crosh but it wouldn't recognise the word "shell." So, hoping to get back to ubuntu by re - entering dev mode the manual way, I found that no matter what I do, I can't reinstall crouton and therefore can't get back to linux. Is there any way you can help?

**Comment by liltinkerer** [comment]
@keyteben this is wrong thread, but probably you disabled developer mode.

**Comment by abc123me** [comment]
touch chrome-os.desktop
gedit chrome-os.desktop

```
[Desktop Entry]
Type=Application
Name=ChromeOS
Icon=your/icon/here
Exec=croutoncycle cros
```

xdg-desktop-menu install chrome-os.desktop
xdg-desktop-menu uninstall chrome-os.desktop

That should do it!
**This is untested, may need minor fixes**
