### ISSUE TITLE
Black screen and error after somewhat recent chromeos update

### ISSUE THREAD

**Issue by batspaceman** [dnschneid/crouton#3184]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde
host: version 9000.91.0 (Official Build) stable-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:33:48 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
#### Please describe your issue:
After an update in February, whenever I have tried to open it, and use linux, it would give me a black screen. Usually it would be totally unresponsive, but sound would still play. Sometimes if I wait (or maybe if I wait long enough) I can go back to my chromeos without force powering off my computer. 
I have tried deleting my chroot, and reinstalling crouton entirely, but it had no effect.
Here is the error log if I can go back to chromeos:
Entering /mnt/stateful_partition/crouton/chroots/trusty...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:33:48 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=713effe0-76be-cf49-925e-e2d1bf039bfb/PARTNROFF=1 hashtree=PARTUUID=713effe0-76be-cf49-925e-e2d1bf039bfb/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=cfaa1bbde9156289fbb94d94d96522fc14c4cf97 salt=080d83b88c754f5f1382cf899cfdc82dd40c36f0ba4fe01a16d43c06dd5439a4" noinitrd vt.global_cursor_default=0 kern_guid=713effe0-76be-cf49-925e-e2d1bf039bfb add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.2.log", Time: Sat Apr  1 18:50:14 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: lxde
host: version 9000.91.0 (Official Build) stable-channel candy 
kernel: Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:33:48 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Another instance of croutontriggerd running, waiting...
Agent pid 13711
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE
** Message: main.vala:131: log directory: /home/batspaceman/.cache/lxsession/LXDE
** Message: main.vala:132: log path: /home/batspaceman/.cache/lxsession/LXDE/run.log
(II) AIGLX: Suspending AIGLX clients for VT switch
Full disclosure, I  have no practice or knowledge of coding and have only fumbled my way through getting linux and making it run like a normal computer by looking up errors for hours and my cynical older brother's infinite computer knowledge.

#### If known, describe the steps to reproduce the issue:
type sudo startlxde into the console, and it will give me a black screen.

**Comment by DaleTheGoat** [comment]
I like the random :100:

**Comment by DennisLfromGA** [comment]
@batspaceman,

> crouton: version 1-20161129162558~master:5f2f11f9

I believe you just need to update your chroot with the latest version of crouton.
For more help, see: ['Common issues and reporting'](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**
