### ISSUE TITLE
Minecraft on xiwi not working

### ISSUE THREAD

**Issue by Frostizzle** [dnschneid/crouton#3186]
When I load up ubuntu with the crouton extension and I run Minecraft, it crashes when it's done loading!

**Comment by seitensei** [comment]
What crashes? The chroot/xiwi or the game?

**Comment by liltinkerer** [comment]
Does it work with Xorg? Why would you want to run it with Xiwi anyway, there is no hardware acceleration.

**Comment by Frostizzle** [comment]
The game crashes

**Comment by 9291Sam** [comment]
It is a problem with the LWJGL Libaries used and the Method of the $DISPLAY value that is assigned I know this much.

**Comment by Cyan101** [comment]
Any solution?

**Comment by 9291Sam** [comment]
No not currently I was trying to do this so I could use my displaylink monitor (yes that is a standard) as a second screen while playing a gamr

**Comment by 9291Sam** [comment]
@Frostizzle I have not had the second part of the issue you described.
