### ISSUE TITLE
Latest chromeOS snd precise update breaks pulseaudio

### ISSUE THREAD

**Issue by pcwalden** [dnschneid/crouton#3188]
```
name: precise
encrypted: no
crouton: version 1-20170315143304~master:95589555
release: precise
architecture: amd64
xmethod: xorg
targets: xfce-desktop
host: version 9202.60.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 4.4.35-06796-g0d8baba #1 SMP PREEMPT Tue Mar 28 23:35:35 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

The latest chromeOS and precise update is breaking pulseaudio

Error by starting pulse in non-daemon mode:

```
~$ pulseaudio
W: [pulseaudio] pid.c: Stale PID file, overwriting.
E: [pulseaudio] alsa-mixer.c: Assertion 'ea = p->elements' failed at modules/alsa/alsa-mixer.c:3190, function path_set_condense(). Aborting.
Aborted (core dumped)
```

**Comment by pcwalden** [comment]
Just had another ChromeOS update and precise pulseaudio is still broken.

**Comment by pcwalden** [comment]
I moved to Trusty with xfce-desktop and the sound is working again.

Precise is still broken.

Should I close this issue?

**Comment by DennisLfromGA** [comment]
@pcwalden,

Thanx for getting back to us with your resolution.

I think I'll close it since 'precise' has reached EOL. and is no longer viable

-**DennisL**
