### ISSUE TITLE
Kill openGL ES on ChromeOS to Allow Use With Crouton?

### ISSUE THREAD

**Issue by uwu-boy** [dnschneid/crouton#3189]
From what I have seen in past issues regarding hardware acceleration, the reason why we can not obtain GPU usage is due to openGL ES already running with ChromeOS' x-server. I have questioned for some time whether or not it is possible to kill the process and restart it when the new server is started OR modify the ChromeOS init scripts to stop openGL ES from starting on boot, that way we can start it when we choose.

**Comment by seitensei** [comment]
OpenGL ES is a hardware feature on certain chipsets, mainly the ARM-based ones. My understanding is that OpenGL (not OpenGL ES) is required for hardware acceleration in crouton/x.

"Disabling" OpenGL ES still doesn't give you OpenGL, unless the GPU hardware has support for OpenGL.

**Comment by uwu-boy** [comment]
My apologies, yes, this is orientated towards ARM based devices that use openGL ES for their graphics processing. The fact that they are embedded doesn't seem it should create much of an issue, unless the server is not compatible. I know that on certain ARM Chromebooks, others have built open source variants of their GPUs modules to accomplish hardware acceleration. I may be wrong in assuming that the modules that shipped with the device should be enough to accomplish such feat.

**Comment by uwu-boy** [comment]
I understand that openGL ES is a stripped down version of openGL, but it doesn't seem stripped down to the point Xorg wouldn't be able to use it, seeing how others are on USB installations.
