### ISSUE TITLE
error when running npm install command on Ubuntu 

### ISSUE THREAD

**Issue by rrababah** [dnschneid/crouton#3196]
![image](https://cloud.githubusercontent.com/assets/26218897/24863444/89689cde-1e09-11e7-94c3-b3eb586b0c40.png)

959 silly install printInstalled
960 verbose stack Error: Registry returned 500 for GET on http://registry.npmjs.org/marked-man/-/marked-man-0.1.5.tgz/chai
960 verbose stack     at makeError (/home/rrababah/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
960 verbose stack     at CachingRegistryClient.<anonymous> (/home/rrababah/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
960 verbose stack     at Request._callback (/home/rrababah/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
960 verbose stack     at Request.self.callback (/home/rrababah/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/request/request.js:187:22)
960 verbose stack     at emitTwo (events.js:106:13)
960 verbose stack     at Request.emit (events.js:191:7)
960 verbose stack     at Request.<anonymous> (/home/rrababah/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/request/request.js:1048:10)
960 verbose stack     at emitOne (events.js:96:13)
960 verbose stack     at Request.emit (events.js:188:7)
960 verbose stack     at IncomingMessage.<anonymous> (/home/rrababah/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/request/request.js:969:12)
961 verbose statusCode 500
962 verbose pkgid marked-man
963 verbose cwd /media/ssd/dev/source/github/atypon/styleguide/ux3/user
964 error Linux 3.13.0-52-generic
965 error argv "/home/rrababah/.nvm/versions/node/v6.9.4/bin/node" "/home/rrababah/.nvm/versions/node/v6.9.4/bin/npm" "install"
966 error node v6.9.4
967 error npm  v3.10.10
968 error code E500
969 error Registry returned 500 for GET on http://registry.npmjs.org/marked-man/-/marked-man-0.1.5.tgz/chai
970 error If you need help, you may report this error at:
970 error     <https://github.com/npm/npm/issues>
971 verbose exit [ 1, true ]

#### If known, describe the steps to reproduce the issue:
when running npm install command

**Comment by hugoShaka** [comment]
It looks like the issue is not related to crouton or chromeOS : Your NPM tries to retrieve something online and is not able to do so (error 500 returned on GET).

**Comment by DennisLfromGA** [comment]
To add:

> 970 error If you need help, you may report this error at:
970 error https://github.com/npm/npm/issues

Seems to be 'npm issues' / 'node issues' not 'crouton issues' ...

-**DennisL**
