### ISSUE TITLE
When specifying a backup location, edit-chroot says it's literally backing up to what you put for -f

### ISSUE THREAD

**Issue by Wizardcrying** [dnschneid/crouton#3199]
#### Please describe your issue:
Minor. `edit-chroot`, when backing up and specifying `-f`, it will just take what you put for the flag instead of the actual path.
![pic](http://i.imgur.com/dQeEFvZ.png)
#### If known, describe the steps to reproduce the issue:
* Make a chroot.
* Go to your `bin` directory for the chroot.
* Back it up through `edit-chroot`, and specify a path for `-f` (maybe even one that includes `../`).
* See something like the picture above happen.

**Comment by dnschneid** [comment]
I take it you'd rather that the display path be canonicalized?

So it would display `/media/removable/Chrome Thumb/backup/xubuntubackup.tar.bz2` in your case.

**Comment by DennisLfromGA** [comment]
Oh, so you want the `realpath` ???

**Comment by Wizardcrying** [comment]
@dnschneid Yes, it's just a small matter.
