### ISSUE TITLE
"possibly the package systemd is at fault"

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3202]
Hi!
Please help me to make my live complete...
#### Please paste the output of the following command here: sudo edit-chroot -all
`sudo edit-chroot -all`
`name: kali-rolling`
`encrypted: no`
`Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...`
`crouton: version unknown`
`release: unknown`
`architecture: unknown`
`targets: xfce`
`host: version 9334.18.0 (Official Build) dev-channel x86-alex_he `
`kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 21 22:04:34 PDT 2017 i686 GNU/Linux`
`freon: yes`
`Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...`

#### Please describe your issue:
I would like to install Kali Linux on my Chromebook XE500C21 device like everyone does:
#### sudo sh ~/Downloads/crouton -r kali-rolling -t xfce
I'm in developer mode. Everything should be fine. But output seems like there is something wrong with the installation of systemd:

`sudo sh ~/Downloads/crouton -r kali-rolling -t xfce`
`...`
`I: Configuring sysvinit-utils...`
`I: Configuring libc-bin… `
`I: Unpacking the base system...`
`W: Failure trying to run:  dpkg --force-overwrite --force-confold --skip-same-version --install /var/cache/apt/archives/adduser_3.115_all.deb /var/cache/apt/archives/dmsetup_2%3a1.02.137-2_i386.deb /var/cache/apt/archives/libapparmor1_2.11.0-3_i386.deb /var/cache/apt/archives/libcap2_1%3a2.25-1_i386.deb /var/cache/apt/archives/libcryptsetup4_2%3a1.7.3-3kali1_i386.deb /var/cache/apt/archives/libdevmapper1.02.1_2%3a1.02.137-2_i386.deb /var/cache/apt/archives/libidn11_1.33-1_i386.deb /var/cache/apt/archives/libip4tc0_1.6.0+snapshot20161117-6_i386.deb /var/cache/apt/archives/libkmod2_23-2_i386.deb /var/cache/apt/archives/libseccomp2_2.3.1-2.1_i386.deb /var/cache/apt/archives/systemd_232-22_i386.deb`
`W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)`
`Failed to complete chroot setup.`
`Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...`

debootstrap.log:

`chronos@localhost /mnt/stateful_partition/crouton/chroots/kali-rolling $ cat` `debootstrap/debootstrap.log -b | grep "systemd"`
`   113   bsdutils pre-depends on libsystemd0`
`  114    libsystemd0 is not installed.`
`   339  Selecting previously unselected package libsystemd0:i386.`
  ` 340  dpkg: regarding .../libsystemd0_232-22_i386.deb containing libsystemd0:i386, pre-dependency problem:`
   `341   libsystemd0 pre-depends on libgcc1 (>= 1:4.2)`
  ` 344  dpkg: regarding .../libsystemd0_232-22_i386.deb containing libsystemd0:i386, pre-dependency problem:`
  ` 345   libsystemd0 pre-depends on libgcrypt20 (>= 1.7.0)`
 `  348  dpkg: regarding .../libsystemd0_232-22_i386.deb containing libsystemd0:i386, pre-dependency problem:`
  ` 349   libsystemd0 pre-depends on liblz4-1 (>= 0.0~r113)`
  ` 352  dpkg: regarding .../libsystemd0_232-22_i386.deb containing libsystemd0:i386, pre-dependency problem:`
  ` 353   libsystemd0 pre-depends on liblzma5 (>= 5.1.1alpha+20120614)`
 `  356  dpkg: regarding .../libsystemd0_232-22_i386.deb containing libsystemd0:i386, pre-dependency problem:`
 `  357   libsystemd0 pre-depends on libselinux1 (>= 2.1.9)`
  ` 360  Preparing to unpack .../libsystemd0_232-22_i386.deb ...`
 `  361  Unpacking libsystemd0:i386 (232-22) ...`
`   506   util-linux pre-depends on libsystemd0`
  ` 507    libsystemd0:i386 is unpacked, but has never been configured.`
 `  573  Setting up libsystemd0:i386 (232-22) ...`
 `  633  Preparing to unpack .../systemd_232-22_i386.deb ...`
 `  634  Unpacking systemd (232-22) ...`
 `  645  Setting up systemd (232-22) ...`
`   646  Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service -> /lib/systemd/system/getty@.service.`
 `  647  Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target -> /lib/systemd/system/remote-fs.target.`
  ` 648  Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service -> /lib/systemd/system/systemd-timesyncd.service.`
  ` 650  dpkg: error processing package systemd (--install):`
`   654   systemd`

Kind regards
Robert

**Comment by wozziwozziwozzi** [comment]
Anyone? dnschneid? Do you need more dumps? This forum is really my last chance cause there is no help in the rest of the internet.

**Comment by jcxian** [comment]
Have you solved this problem? I have the same problem

**Comment by shubhamagarwal3010** [comment]
I'm also facing similar error "possibly the package /var/cache/apt/archives/systemd-shim_10-3_amd64.deb is at fault"

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
