### ISSUE TITLE
How to recover files from encrypted chroot stored in a USB drive?

### ISSUE THREAD

**Issue by bussyjd** [dnschneid/crouton#3203]
#### Please describe your issue:
My chromebook harddisk died and I need to recover files residing in my chroot install that was stored in a USD drive.
I can mount the USB stick properly on my ubuntu box but I can't recover the chroot files.
So far I tried `sudo ecryptfs-recover-private chrootfolder` which prompted for the mount passphrase and  mounted the exact same encrypted folders in a /tmp/ecryptfs.XXXXXXXX.
What am I missing? What are the proper step to unencrypt the chroot folders?

#### If known, describe the steps to reproduce the issue:
Have a encrypted crouton install in a USB stick.
Have the chromebook disk failing.

**Comment by bussyjd** [comment]
Ok,
by looking into the `mount-chroot` I came up with the following:
I copied the chroot folder with `cp -pr /mnt/chroot/silveri3 /home/me/Documents/chroots/`
```
$ export KEYFILE=/home/me/Documents/chroots/silveri3/.ecryptfs
$ tail -c 160 "$KEYFILE" | head -c 80 > wrappedkey
$ tail -c 80 "$KEYFILE" > wrappedfnek
$ echo -n "REDACTED" | ecryptfs-unwrap-passphrase wrappedkey |  ecryptfs-add-passphrase |  sed -n 's/.*\[\([0-9a-zA-Z]*\)\].*/\1/p'
xxxxxxxxx
$ echo -n "REDACTED" | ecryptfs-unwrap-passphrase wrappedfnek |  ecryptfs-add-passphrase |  sed -n 's/.*\[\([0-9a-zA-Z]*\)\].*/\1/p'
yyyyyyyyyy
$  sudo mount -t ecryptfs -o ecryptfs_sig=xxxxxxxxx,ecryptfs_fnek_sig=yyyyyyyyyy,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs,rw,dev,exec,suid /home/me/Documents/chroots/silveri3/ /secret
Passphrase: 
Enable plaintext passthrough (y/n) [n]: 
Attempting to mount with the following options:
  ecryptfs_unlink_sigs
  ecryptfs_fnek_sig=79da5c27b08bb9cc
  ecryptfs_key_bytes=16
  ecryptfs_cipher=aes
  ecryptfs_sig=65aca4a3247d1500
mount: mount(2) failed: No such file or directory
```
I am 100% sure the password I provide is correct. The same passwords are provided twice making `xxxxxxxxx` and `yyyyyyyyyy` the same.

I know this is not a direct bug of chrouton but I hope this can at least help somebody in the same situation.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
