### ISSUE TITLE
Cannot install xiwi on Chromebook Flip C100

### ISSUE THREAD

**Issue by deahl1** [dnschneid/crouton#3204]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce,touch,extension,xiwi,lxde
host: version 9000.91.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Feb 22 23:17:59 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes

#### Please describe your issue:
this command:
sudo sh ~/Downloads/crouton -u -n xenial -t xfce,touch,extension

gets me this error:
Installing target xiwi...
xserver-xorg-video-dummy was already not hold.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xorg is already the newest version (1:7.7+13ubuntu3).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xserver-xorg-core (>= 2:1.17.99.902)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.

#### If known, describe the steps to reproduce the issue:
I'm not sure if it's a known issue, but in reading around I found that there was some backported version for ARM, the issue may be originating there.

**Comment by 9291Sam** [comment]
You have a ARM based chromebook they have some support for programs but most programs are IA-32,X86,AMD64,X86-64 only
