### ISSUE TITLE
Unable to install environment with crouton - Failed to mount xenial.

### ISSUE THREAD

**Issue by winterwarmer** [dnschneid/crouton#3205]
```
Please paste the output of the following command here: sudo edit-chroot -all (not available as not installed)
```
I am trying to use crouton to give me a Linux environment on a Lenovo N22 Chromebook and keep getting a message about failed to mount xenial.  

I have tried clearing everything out and restarting and also tried differentt targets (xfce and unity) but keep getting the same message - an example is below with a ls of local before I start to show that there is no chroots folder 

chronos@localhost / $ sudo rm -f -r /usr/local/chroots
chronos@localhost / $ ls /usr/local
chronos@localhost / $ sudo sh ~/Downloads/crouton -u -t unity
/usr/local/chroots/xenial already exists; updating it...
Enter encryption passphrase for xenial:    [password entered]
mount: mount(2) failed: No such file or directory
Failed to mount xenial.
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
@winterwarmer,

Maybe it's still linked or busy, try rebooting after you remove it manually or use crouton's own `delete-chroot` to do it.

*Hope this helps,*
-**DennisL**

**Comment by winterwarmer** [comment]
Thanks but I have tried rebooting several times and that didn't work.  delete-chroot is not available as the install does not seem to have got far enough to install it.

**Comment by winterwarmer** [comment]
`I don't know what caused the problem but I think I have resolved it.

I switched the Chromebook back to normal (verified) mode and then re-enabled developer mode. I then re-downloaded crouton and went through the installation process again and now it seems to be working (part way through installing xfce)

- Thanks Gary

**Comment by DennisLfromGA** [comment]
@winterwarmer,

Taking it in/out of developer mode will essentially 'powerwash' it and remove all user data and files to include those under `/usr/local/`. It's kind of a drastic step but it certainly does the job and is sometimes necessary

If everything works out pleae close this issue, thanx.

*Hope this helps,*
-**DennisL**

**Comment by winterwarmer** [comment]
The first attempt failed trying to get some packages but trying again with -r trusty has worked and this reply is from xfce on my chromebook
