### ISSUE TITLE
How to move crouton on sd card to chromebook plus ?

### ISSUE THREAD

**Issue by seandarcy** [dnschneid/crouton#3206]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost /media/removable/crouton $ sudo sh bin/edit-chroot -all
name: xenial
encrypted: no
Entering /media/removable/crouton/chroots/xenial...
mount: mount /sys on /run/crouton/media/removable/crouton/chroots/xenial/sys failed: No space left on device
Unmounting /media/removable/crouton/chroots/xenial...

#### Please describe your issue:
I have xenial on an ext4 partition of an sdcard. It runs on an Acer R13. Now trying to mount it on a Samsung Chromebook Plus (also armv8).  I get the "No space..." error both on edit-chroot and enter-chroot, but there's plenty of space

/media/removable/crouton $ df | grep k1p1
/dev/mmcblk1p1                                                12319880 3844596   7829756  33% /media/removable/crouton
/dev/mmcblk1p1                                                12319880 3844596   7829756  33% /media/removable/crouton/chroots/xenial/var/host/media/removable/crouton

I tried:

/media/removable/crouton $ sudo sh ~/Downloads/crouton -p . -u -n xenial
/media/removable/crouton/chroots/xenial already exists; updating it...
WARNING: Signed boot verification is disabled; enabling it for security.
You can disable it again using: sudo crossystem dev_boot_signed_only=0
Preparing chroot environment...
...............
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
Installing target core...
..............
The following NEW packages will be installed:
  libspeex-dev libspeexdsp-dev
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 92.0 kB of archives.
After this operation, 352 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports xenial/main arm64 libspeex-dev arm64 1.2~rc1.2-1ubuntu1 [53.2 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial/main arm64 libspeexdsp-dev arm64 1.2~rc1.2-1ubuntu1 [38.9 kB]
Fetched 92.0 kB in 1s (51.1 kB/s)          
dpkg: error processing archive /var/cache/apt/archives/libspeex-dev_1.2~rc1.2-1ubuntu1_arm64.deb (--unpack):
 cannot get security labeling handle: No such file or directory
Selecting previously unselected package libspeexdsp-dev:arm64.
(Reading database ... 89916 files and directories currently installed.)
Preparing to unpack .../libspeexdsp-dev_1.2~rc1.2-1ubuntu1_arm64.deb ...
Unpacking libspeexdsp-dev:arm64 (1.2~rc1.2-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libspeex-dev_1.2~rc1.2-1ubuntu1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.

And I can't start crouton:

sudo sh bin/startlxde -n xenial -X xiwi-tab
Entering /media/removable/crouton/chroots/xenial...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-45-generic aarch64 Ubuntu
Current Operating System: Linux localhost 4.4.35-06801-g74bef12 #1 SMP PREEMPT Wed Apr 5 13:00:27 PDT 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashtree=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=42a56615ccea5fdfbcb9f135e9815a1c670816d2 salt=eec94b47b2510006902daf90b564270202d947a78f42b7def421f984554f66af" noinitrd vt.global_cursor_default=0 kern_guid=12a8c470-5762-934e-adb4-39c1a1843329  
Build Date: 02 November 2016  10:05:28PM
xorg-server 2:1.18.4-0ubuntu0.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Apr 15 13:34:28 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) SELinux: Failed to open x_contexts mapping in policy

**Comment by DennisLfromGA** [comment]
@seandarcy,

> /media/removable/crouton $ sudo sh ~/Downloads/crouton -p . -u -n xenial

This command will not *move* your chroot from the sd card, it will *update* the chroot *on* the sd card.

> sudo sh bin/startlxde -n xenial -X xiwi-tab
Entering /media/removable/crouton/chroots/xenial...

This command will attempt to launch the lxde desktop on the sd card, not on your Chromebook.

> Failed to complete chroot setup.

It looks like the chroot on the sd card may not be working any longer, you can check to see if it still launches on your R13 or SCB+, I don't think it will. If not, it will have to be fixed before you attempt any copy routine probably.

----
To move a (functional) chroot from your sd card to your SCB+, I think the following should work:

`sudo edit-chroot -c /media/removable/crouton/chroots xenial -m /usr/local/chroots/xenial/`

*Hope this helps,*
-**DennisL**

**Comment by seandarcy** [comment]
I've described my issue incorrectly.  I want to leave crouton on the sdcard, just use the sd card on the chromebook plus. I don't want to move the chroot from the sd card to the cb+ internal memory.

**Comment by DennisLfromGA** [comment]
@seandarcy,

> I want to leave crouton on the sdcard, just use the sd card on the chromebook plus.

If that's all you want to do you should be able to just plug the sd card into the SCB+ and run it as you do on the R13.

If you want to **_copy_** it from the sd card to the internal drive on the SCB+ just use the same command above but replace the `-m` with a `-C`.

*Hope this helps,*
-**DennisL**
