### ISSUE TITLE
I unchecked 'use this monitor' for internal monitor and can't enable it again

### ISSUE THREAD

**Issue by WouterVdS** [dnschneid/crouton#3208]
```
Acer C720P Chromebook
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20161028111244~master:948ee6dc
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9334.33.0 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Apr 3 22:09:37 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:

I hooked up an external monitor (which I had to manually turn on by going to Settings -> Display -> Use this monitor). I unchecked the 'Use this monitor' option for my internal monitor. 
When finished working, I logged out of my crouton back to Chrome OS and disconnected my external monitor. Now when I restart my crouton, my internal display is still disabled. And any external monitor needs to be enabled first...

I have access to my terminal (thanks Guake!), but I can't see what I type. I don't have SSH access. I tried: xrandr --output LVDS --auto, but that didn't do anything.

#### If known, describe the steps to reproduce the issue:
Go to Settings -> Display -> (uncheck) Use this monitor

**Comment by WouterVdS** [comment]
Solved!

In terminal I entered 
xrandr -q > Downloads/output.txt
Which gave me a list of displays I could view in Chrome OS.
Then a simple
xrandr --output eDP1 --auto
did the trick!

**Comment by DennisLfromGA** [comment]
Thanx, that's good to know. 👍
