### ISSUE TITLE
Can't move or close windows i KDE

### ISSUE THREAD

**Issue by VSvensli** [dnschneid/crouton#3210]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: kde
host: version 9334.52.0 (Official Build) beta-channel swanky 
kernel: Linux localhost 4.4.44-07349-gf08a9db #1 SMP PREEMPT Tue Apr 18 10:32:05 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
When inside kde i can't move or close any windows. I have tried powerwashing and reinstalling, but that didn't fix the issue.

**Comment by VSvensli** [comment]
The problem did not occure when i use kde-desktop when installing insted. So i guess that's a fix.

**Comment by DennisLfromGA** [comment]
@VSvensli,

That's is strange, I don't know why the minimal kde target didn't work.
I usually add the '-desktop' targets myself so I don't have a system installed to test it on.

I'm going to close this issue for now but if it happens again please reopen it and we'll dig into it.

-**DennisL**

**Comment by Pythonmaster1508** [comment]
You may not have KWin installed.
If so, use this command in a terminal: `sudo apt-get install kwin`
After it completes, reboot the chroot, you should be able to move the windows and close them

**Comment by peepo** [comment]
wfm using xenial kwin provides windows with cyan blue top to active window.
 and one can now drag & resize windows! tx ~:"
