### ISSUE TITLE
Cannot find /usr/local/bin/enter-chroot when trying to boot MATE

### ISSUE THREAD

**Issue by morbocodes** [dnschneid/crouton#3212]
Output of sudo edit-chroot -all:
`name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: touch,e17,extension,audio
host: version 9202.64.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 5 13:04:49 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.`

I followed this guide: https://medium.com/power-user/ubuntu-mate-on-a-chromebook-with-crouton-2cebd167382 to set up MATE. But when I have completed every step and try to use `sudo startmate` to start MATE, I get this:
`sh: 0: Can't open /usr/local/bin/enter-chroot`

**Comment by DennisLfromGA** [comment]
@morbocodes,

The guide you linked above installs the `xfce` target, your chroot shows you installed the `e17` target.

The article gives you instructions to install the `startmate` script and goes on to say:

> "Now all that you have to do is type the command “sudo startmate” and you will launch into Ubuntu Mate!

The `startmate` script provided by the author is reliant on the `xfce` target that you did *not* install.
When you try to launch the mate desktop you should get an error similar to the following:

> /usr/local/chroots/xenial does not contain target 'xfce4'

So your error message:

> sh: 0: Can't open /usr/local/bin/enter-chroot

Does sound a little strange if your chroot installed completely without error.
Is it possible you installed your chroot in another locaton and not under `/usr/local/chroots` ?

*Hope this helps,*
-**DennisL**

**Comment by morbocodes** [comment]
I did actually manage to resolve this myself by writing `exec mate-session` to ~/.xinitrc and then running `startx`. Thank you for the help.

**Comment by DennisLfromGA** [comment]
Glad you figured something out. 👍
