### ISSUE TITLE
doesnt even try..

### ISSUE THREAD

**Issue by BatPon3Mango** [dnschneid/crouton#3215]
welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

If you want to customize the look/behavior, you can use the options page.
Load it by using the Ctrl+Shift+P keyboard shortcut.

crosh> shell
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r sana -t xfce
sh: Can't open /home/chronos/user/Downloads/crouton

**Comment by DennisLfromGA** [comment]
@BatPon3Mango,

Be sure you first download crouton using this link: [https://goo.gl/fd3zc](https://goo.gl/fd3zc)
Save it in your Downloads folder, that's where it will save to by default unless you've changed it.

Then run your crouton installation command shown above again if you like.
Note that the `sana` release has reached it's end of life so it would probably be best to use `kali-rolling` now.

*Hope this helps,*
-**DennisL**
