### ISSUE TITLE
crouton working with ubuntuGnome zesty upgraded to artful

### ISSUE THREAD

**Issue by fedrox** [dnschneid/crouton#3217]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
..working but every time I exit from ubuntu and returning to chronos shell, sudo startgnome doesn't start because of installed gnome-shell extensions, Removed the extensions, it starts again

**Comment by DennisLfromGA** [comment]
@fedrox 

I'm not sure I follow, please show us the output of: `sudo edit-chroot -all`

Is this someting you installed in the chroot or something that was installed by crouton?

-**DennisL**
