### ISSUE TITLE
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)

### ISSUE THREAD

**Issue by softmochi** [dnschneid/crouton#3219]
I have been getting this error message whenever I switch between ubuntu (14.04) and chromeos, it doesn't stop me from switching, but the error message worries me. I'm using a Dell Chromebook 13 i3 version 64 bit.
--------------------------------------------------------------------------------------------------------------------------------------
Error message
```
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
```
-------------------------------------------------------------------------------------------------------------------------------------

Here is my sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,unity,extension
host: version 9202.64.0 (Official Build) stable-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Apr 5 13:05:30 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by DennisLfromGA** [comment]
@softmochi,

The `xenial` release is the new default, you might try using that instead.
If you don't want to take that step then I'd suggest adding another desktop like `lxde` and see if that works.

I also have a Dell Chromebook 13 and use the `trusty` release but with `lxde`.

*Hope this helps,*
-**DennisL**

**Comment by softmochi** [comment]
@DennisLfromGA ,

Thank you for your help. I have a few questions though. Will I be able to preserve my data from `trusty` when I upgrade it to `xenial`?

Also, what's the benefit running `trusty` with `lxde`?

Thanks

**Comment by DennisLfromGA** [comment]
@softmochi,

> Will I be able to preserve my data from trusty when I upgrade it to xenial?

In a perfect world the upgrade from trusty to xenial should work flawlessly preserving all of your data and it has for me the couple of times I've done it. I have had trouble updating from precise --> trusty --> xenial though which is much more complicated. I would always suggest doing a backup of your chroot before attempting any upgrade of course.

> Also, what's the benefit running trusty with lxde?

Well it just works as opposed to unity in your situation.
It's also my preferred desktop but that's a personal choice and not for everyone - YMMV.

*Hope this helps,*
-**DennisL**
