### ISSUE TITLE
Can't start (or update, or anything else) chroot, everything appears to be broken

### ISSUE THREAD

**Issue by Sarvadi** [dnschneid/crouton#3221]
I appear to have gotten myself into quite a few problems, all of which are likely related.
I have Xenial (16.04) installed on a flash drive. After the Chrome OS update last night, Crouton no longer seems to like it.

`chronos@localhost ~/Downloads $ sudo sh crouton -p /media/removable/XFCE/ -n xenial -u
/media/removable/XFCE/chroots not found.
/media/removable/XFCE/chroots/xenial does not exist; cannot update.
Valid chroots:`
Why is it adding `chroots/` to the path? Perhaps I'm misinterpreting the purpose of `-p`, but in this case, it looks to be similar to the `-c` flag of `edit-chroot`.

`chronos@localhost ~/Downloads $ sudo edit-chroot -a -c /media/removable/XFCE
System Volume Information lost+found xenial`
I'm not sure it should be listing all 3 folders on the USB, as only one is a chroot.

`chronos@localhost ~ $ sudo edit-chroot -all -c /media/removable/XFCE
name: System Volume Information
encrypted: no
Entering /media/removable/XFCE/System Volume Information...
chroot: failed to run command '/usr/local/bin/croutonversion': No such file or directory`
This looks, to me, like my crouton installation is broken. And that it thinks `System Volume Information` is a chroot.

`chronos@localhost /media/removable/XFCE $ ls System\ Volume\ Information/
dev  etc  IndexerVolumeGuid  lib  media  proc  sys  tmp  var`
Probably relevant. I don't think most of that is supposed to be in there.

`chronos@localhost ~ $ sudo startxfce4 -c /media/removable/XFCE
Entering /media/removable/XFCE/xenial...
Changing wayland GID from 999 to 601...
Password: `
I haven't the slightest clue what the password would be, and I've never heard of Wayland until now. Also notable (to me) is that `startxfce4` knows that `xenial` is the chroot, but `edit-chroot` does not.

Asus C300M
`chronos@localhost ~ $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=3942165
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={A772AA64-E906-A01E-1DFD-1856870D39EC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={A772AA64-E906-A01E-1DFD-1856870D39EC}
CHROMEOS_RELEASE_BOARD=quawks-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=quawks-release/R58-9334.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=9334
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=58
CHROMEOS_RELEASE_DESCRIPTION=9334.58.0 (Official Build) stable-channel quawks
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9334.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9334.58.0`

The obvious solution is probably to nuke it all and start over, but I'd rather not spend hours (days, even) restoring every little setting in my chroot. Creating a backup does nothing (i.e. no tarball created, no output, etc).

**Comment by DennisLfromGA** [comment]
@Sarvadi,

> Why is it adding chroots/ to the path? Perhaps I'm misinterpreting the purpose of -p, but in this case, it looks to be similar to the -c flag of edit-chroot.

True, similar but slightly different.

crouton's '-p' option looks for the **_parent_** of the `/bin` & `/chroots` folders.
edit-chroot's '-c' option looks for the **_location / folder_** that your chroots are in.

`edit-chroot` and the `start*` scripts aren't too particular about where your chroots are or what folder they're in but `crouton` definitely is.

So I think if you rename your XFCE folder to chroots you should be fine.
To do that use something like:

`sudo mv /media/removable/XFCE /media/removable/chroots`

Then to update use:

`sudo sh ./crouton -p /media/removable -n xenial -u`

To list all of your chroots use:

`sudo edit-chroot -all -c /media/removable/chroots`

And finally to launch your xfce desktop use:

`sudo startxfce4 -c /media/removable/chroots [-n xenial]`

*Hope this helps,*
-**DennisL**

**P.S.**  To create a backup and store it in your ~/Downloads folder use:

`sudo edit-chroot -b -c /media/removable/chroots -f ~/Downloads xenial`

**Comment by Sarvadi** [comment]
@DennisLfromGA,
I'm unable to rename the XFCE folder easily, so I made a `chroots` folder inside of it and moved `xenial` into it, which leads me to:
`chronos@localhost /media/removable $ sudo sh ~/Downloads/crouton -p /media/removable/XFCE -n xenial -u
Downloading latest crouton installer...
######################################################################## 100.0%
/media/removable/XFCE/chroots/xenial already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Changing wayland GID from 999 to 601...
Password: `

Which is where all of this started. I have no idea what Wayland is, other than an X replacement. Nor do I know what the password is, or what it's for. The chroot isn't encrypted, so it's not for that.

Also, while confirming that the chroot isn't encrypted, I got this:
`chronos@localhost /media/removable/XFCE/chroots $ sudo edit-chroot -all -c .
name: xenial
encrypted: no
Entering /media/removable/XFCE/chroots/xenial...
mount: mount /media on /run/crouton/media/removable/XFCE/chroots/xenial/var/host/media failed: No space left on device`
I have plenty of free space. I've never used `mount` before in my life and have no idea where I'd start debugging that.

**Comment by Sarvadi** [comment]
Powerwashed and made a fresh chroot, same problem. Ended up ditching replacing Chrome OS entirely because I _need_ a functioning Linux install.

Closing this since it's no longer relevant to me and, evident from the lack of any other comments, nobody else seems to have this issue.
