### ISSUE TITLE
Ctrl-w tab protection for xiwi

### ISSUE THREAD

**Issue by spiffytech** [dnschneid/crouton#3222]
When I have a xiwi tab open and hit `Ctrl-w` the tab gets closed.

Please add basic tab protection (prompt the browser's unsaved input "Are you sure you want to close this tab?"), or more preferable, create an app version of xiwi windows (similar to the Crosh Window app) that can capture and use `Ctrl-w`.

**Comment by jeremylinlin** [comment]
I have the same issue here. Any shortcuts that are available in chromeOS won't work inside the xiwi tab. Some really annoying ones include ctrl+w, ctrl+alt+t.

I am thinking it would be the best to assign all key combinations to crouton if the xiwi tab is active. Otherwise some useful hotkeys will become useless in xiwi mode.

**Comment by spiffytech** [comment]
I found a partial solution to this on [the cheatsheet page](https://github.com/dnschneid/crouton/wiki/Crouton-Command-Cheat-Sheet): 

> Launch a single app in a Window in the background: `sudo startxiwi -b -n chrootname app_name`

This is a specific version of the generality `sudo enter-chroot -n chrootname xiwi app_name`, which opens any application in a new window that is protected from `Ctrl-w`, `Ctrl-tab`, etc.

However:
1. [The xiwi documentation](https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)) doesn't mention this is possible
2. I can't find documentation on launching new windows from inside an existing chroot
    * The crouton extension seems to only support grabbing one window at a time. This should be a separate ticket.

So given (1), I'd say this ticket could be closed with a documentation update.

**Comment by NerdsvilleCEO** [comment]
@spiffytech do you mean that if you run ``sudo startxiwi -b -n chrootname app_name``, that it is protected against ``Ctrl-w``? That does not seem to be the case on my end :/

**Comment by DennisLfromGA** [comment]
Clicking on the ['Crouton Integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension allows you to select and open any chroots in the drop-down.

*Hope this helps,*
-**DennisL**
