### ISSUE TITLE
CB Plus : install fails - selinux ?

### ISSUE THREAD

**Issue by seandarcy** [dnschneid/crouton#3223]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Can't do that now, but I did save this from when it was installed:

sudo sh  /media/removable/crouton/bin/enter-chroot -n xenial croutonversion
Entering /media/removable/crouton/chroots/xenial...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: arm64
xmethod: xiwi
targets: xiwi,xfce
host: version 9202.64.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.35-06801-g74bef12 #1 SMP PREEMPT Wed Apr 5 13:00:27 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/crouton/chroots/xenial...

#### Please describe your issue:
I installed crouton, but it wouldn't start. Error message about selinux.

I then tried updating this install:

sudo sh ~/Downloads/crouton -u -p /media/removable/crouton
Downloading latest crouton installer...
######################################################################## 100.0%
/media/removable/crouton/chroots/xenial already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
...............
Installing mount-chroot into the host...
nstalling unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
Installing target core...
Preparing environment...
Preparing software sources...
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [102 kB]
...............
Get:1 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 libicu55 arm64 55.1-7ubuntu0.2 [7489 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 linux-libc-dev arm64 4.4.0-77.98 [809 kB]                    
Fetched 8298 kB in 24s (337 kB/s)                                                                                                 
dpkg: error processing archive /var/cache/apt/archives/libicu55_55.1-7ubuntu0.2_arm64.deb (--unpack):
 cannot get security labeling handle: No such file or directory
(Reading database ... 68932 files and directories currently installed.)
Preparing to unpack .../linux-libc-dev_4.4.0-77.98_arm64.deb ...
Unpacking linux-libc-dev:arm64 (4.4.0-77.98) over (4.4.0-75.96) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libicu55_55.1-7ubuntu0.2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.

So then I deleted the chroot, and tried to reinstall:

sudo sh -e ~/Downloads/crouton -r xenial -t xiwi,xfce -p '/media/removable/crouton'
Downloading latest crouton installer...
######################################################################## 100.0%
Installing xenial-arm64 chroot to /media/removable/crouton/chroots/xenial
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
2017-05-04 21:19:51 URL:http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/ [7115/7115] -> "-" [1]
Downloading debootstrap version 1.0.90...
2017-05-04 21:19:53 URL:http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.90.tar.gz [69936/69936] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
…………
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.39_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.39_arm64.deb is at fault)
Failed to complete chroot setup.
Unmounting /media/removable/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@seandarcy,

One thing you might try is to link the chroots folder on your external media to your internal drive, try something like this:

`cd /usr/local`
`sudo ln -s /media/removable/crouton/chroots/ ./chroots`

Then try your crouton commands without using the '`-p ...`' option.

*Hope this helps,*
-**DennisL**

**Comment by kjelly** [comment]
I have the same issue. And I don't know how to solve it.
The way that "link the chroots folder on your external media to your internal drive" is not work for me.

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
