### ISSUE TITLE
Can't Configure Wifi Dongle Drivers!

### ISSUE THREAD

**Issue by Astrades** [dnschneid/crouton#3225]
Okay, so I just bought a new wifi dongle for my acer chromebook. I have Ubuntu 16.04 installed on it from crouton; the dongle is an Edimax AC-600 and comes with an Ubuntu driver. I noticed that when trying to run "make" in the driver directory (as told to in the directions), I am returned with this error:
```

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/3.14.0/build M=/home/to/Desktop/rtl8821AU_linux_v4.3.14_13455.20150212_BTCOEX20150128-51  modules
make[1]: *** /lib/modules/3.14.0/build: No such file or directory.  Stop.
Makefile:1551: recipe for target 'modules' failed
make: *** [modules] Error 2
```

 I got the dongle for pentesting using some home made tools that require an external wifi card, similar to that of aircrack-ng, wifite, fluxion, etc. I'm not even too sure as to what the problem is, honestly. How do I go about fixing this?

**Comment by DennisLfromGA** [comment]
To the best of my knowledge all networking is handled and more or less locked down on the Chrome OS side and can't be configured in a chroot so I don't think you'll succeed even if it did compile.

**Comment by divx118** [comment]
@Astrades It should be possible, however if you want to build the drivers on your chromebook you will need to install kernel headers. Those aren't installed, that is why you get that error. One way is to build and install the kernel headers by yourself following https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86). Or another way is to build the drivers on another linux machine with the chromeos kernel source. See https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules
NOTE: you will also need to disable module_locking so you can load other modules that are not provided by chromeos. This is also mentioned in the guides posted above.
