### ISSUE TITLE
Samsung Chromebook Plus stylus (S-Pen) not pressure-sensitive in Crouton

### ISSUE THREAD

**Issue by jgyllinsky** [dnschneid/crouton#3226]
# issue
---
Samsung Chromebook Plus stylus not pressure-sensitive inside of crouton. Stylus confirmed working with BOTH base installed applications AND a android application which was designed for the Samsung S-Pen of the Samsung Galaxy Note (SGN) series (originally tested on SGN3 SGN4).

## To reproduce issue

1. Get New Samsung Chromebook Plus
2. Enable Developer-mode
3. Install crouton
4. `sudo sh -e ~/Downloads/crouton -t touch,xiwi,xfce`
5. Reboot
6. open terminal (Crosh, Crtl+Alt+T from anywhere in chromebook)
7. get into shell (type `shell` from Crosh)
8. Start X Server (type `sudo startxfce4` from shell)
9. Open a terminal
10. Update (type `sudo apt-get update` from terminal in xfce4)
11. Upgrade (type `sudo apt-get upgrade` from terminal in xfce4)
12. Install a program that uses a stylus (type `sudo apt install krita` from terminal in xfce4)
13. open krita (type `krita` from terminal in xfce4)
14. Attempt to draw
15. Find that stylus location (and touch) work, but the stylus pressure does not get detected meaning that opacity or brush-size cannot be varied based on it.

# info
---
## Setup
Crouton was installed with `sudo sh -e ~/Downloads/crouton -t touch,xiwi,xfce`. Krita, a drawing program which is normally stylus pressure aware was installed after updating (`sudo apt-get update` and `sudo apt-get upgrade`) with `sudo apt install krita`.

## What works

- Touch seems to work.
- Xfce4 seems to work with ubuntu 16
- xiwi seems to work ok, I'm able to toggle back and forth

## What DOESN'T work (maybe unrelated)

- Pressure (means that opacity or size of brushes cannot be based on pressure, this is a deal-breaker for this device as this is a critical part of digital drawing)
- Tablet mode onscreen keyboard (it pops up every time the pen gets lifted in tablet mode, meaning half the screen isn't usable when in tablet mode, laptop mode doesn't have this issue)
- Multi-touch (this means that two finger zoom doesn't work in mypaint [install via `sudo apt install mypaint`]) (See "Pixel - Multitouch support in Chromium with xfce" issue #60 from 2013) 
- Palm rejection (causes continuously jumping [lines between hand and pen tip] during drawing)
- Accelerometer and Gyroscope (I don't actually believe the device has these because the native ChromeOS can't use them, not in Chrome Experiments nor in youtube 360 view... so maybe the specs from samsung are wrong.)

## sudo edit-chroot -all
---
```
$ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: arm64
xmethod: xiwi
targets: touch,xiwi,xfce
host: version 9202.64.0 (Official Build) stable-channel kevin
kernel: Linux localhost 4.4.35-06801-g74bef12 #1 SMP PREEMPT Wed Apr 5 13:00:27 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

## cat /etc/lsb-release
```
chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_ARC_VERSION=3880239
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_RELEASE_BOARD=kevin-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=kevin-release/R57-9202.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=9202
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=57
CHROMEOS_RELEASE_DESCRIPTION=9202.64.0 (Official Build) stable-channel kevin 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9202.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9202.64.0
chronos@localhost / $ croutonversion
bash: croutonversion: command not found
chronos@localhost / $ crouton-version
bash: crouton-version: command not found
```

**Comment by jgyllinsky** [comment]
Maybe https://github.com/Agamnentzar/chrome-stylus-pressure might be helpful?

**Comment by jjramsey-personal** [comment]
Looks like there is a "wacom" kernel module on the Chromebook Plus, but it isn't automatically loaded. Running "modprobe wacom" does indeed load the module. However, loading the module before starting the XFCE chroot doesn't get me pressure sensitivity.

**Comment by foxmajik** [comment]
Any update on this?

Seems like a pretty major flaw and it hasn't been touched since 2017...
