### ISSUE TITLE
Can't enter xfce4

### ISSUE THREAD

**Issue by Cryptiiiic** [dnschneid/crouton#3228]
sudo edit-chroot -all
Password: 
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170315143304~master:95589555
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9202.64.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13759-g98e7e0e #1 SMP PREEMPT Wed Apr 5 12:54:58 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

I can't enter xfce for on kali-rolling
Entering chroot works fine just not 
https://ghostbin.com/paste/z3kfy

**Comment by notimaginative** [comment]
I had the same problem. Removing the recently installed xserver-xorg-legacy package fixed it.

**Comment by Cryptiiiic** [comment]
@notimaginative Thanks so much!!! It worked. Some people were telling me to mess with dm-vertity on reddit.

**Comment by giltee** [comment]
Hey Guys, same issue here. Trying to figure out how to remove the package, seems that debian shell commands such as apt-get purge are not working. Any ideas?

**Comment by notimaginative** [comment]
@giltee If you are running jessie or newer then "sudo apt remove --purge xserver-xorg-legacy" should do what you need. If it doesn't work for some reason then apt-get instead of apt, with the same commands otherwise, should do it.

**Comment by giltee** [comment]
interestingly enough both commands do not seem to be available. Seems odd that chrome OS doesn't have their own package manager type dealio.

**Comment by notimaginative** [comment]
@giltee You have to do it from within the chroot. "sudo enter-chroot" should still work fine and get you to a command line where you can remove the package. Once the package has been removed exit the chroot (with "exit" or Ctrl-D) and then "sudo startxfce4 -b" should work again.

**Comment by Cryptiiiic** [comment]
@notimaginative OMG face palm for this guy

**Comment by giltee** [comment]
@Cryptiiiic No need to be a jerk when someone is simply trying to learn.
