### ISSUE TITLE
Autostart chroot from sd-card

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3230]
```
Please paste the output of the following command here: sudo edit-chroot -all
No chroots found in /mnt/stateful_partition/crouton/chroots
```

#### Please describe your issue:
I installed a chroot on a 64 gb sd-card. Because I want to autostart it, I used your guide to do this. 
Now the autostart won't work. It probably has to do with the chroot moving to a non-default folder (see outcome of the command above), but I don't know how to edit the config files.

#### If known, describe the steps to reproduce the issue:
Install chroot to sd-card, follow the steps in https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup

**Comment by DennisLfromGA** [comment]
@planckm,

Sorry, I hadn't anticipated or provided for external media in my '.conf' file.
Lines 114 thru 121 are where the changes would go, they are shown below -
```
  if [ -d /var/crouton/chroots ]; then
  ## Uses the @drinkcat 'separate_partition' branch - as DEFAULT
    CROUTON_BIN=/var/crouton/bin
    CROUTON_CHROOTS=/var/crouton/chroots
  elif [ -d /usr/local/chroots ]; then
  ## Uses the @dnschneid 'master' branch
    CROUTON_BIN=/usr/local/bin
    CROUTON_CHROOTS=/usr/local/chroots
```
You could add the following, as an example, and see if it launches -
```
if [ -d '/media/removable/SD Card/chroots' ]; then
  ## Uses external SD Card - as DEFAULT
    CROUTON_BIN='/media/removable/SD Card/bin'
    CROUTON_CHROOTS='/media/removable/SD Card/chroots'
elif [ -d /var/crouton/chroots ]; then
  ## Uses the @drinkcat 'separate_partition' branch - as DEFAULT
    CROUTON_BIN=/var/crouton/bin
    CROUTON_CHROOTS=/var/crouton/chroots
elif [ -d /usr/local/chroots ]; then
  ## Uses the @dnschneid 'master' branch
    CROUTON_BIN=/usr/local/bin
    CROUTON_CHROOTS=/usr/local/chroots
```
I may add an option for external media if I get a chance. If I do I'll report back her.

*Hope this helps,*
-**DennisL**

**Comment by planckm** [comment]
@DennisLfromGA 
I made the changes as you suggested (with the right path to my sd card of course) but no autostart is happening at startup. (it doesn't has anything to do with the ' ' around the path to the chroot, does it?).
After startup and waiting a while I hear a beep (suggesting the script gave an error, I don't know?).
Thanks for the help.

**Comment by DennisLfromGA** [comment]
@planckm,

The single-quotes should not be a problem, you can use double-quotes instead or even preceed the space in the path with a backslash if you like, I don't believe that's the problem.

Debugging is 'on' by default so there should be a file named with the $PID, similar to: 

`/tmp/crouton-$PID.log`

You'll have to substitute the $PID with the actual PID of the process.

Examine the debug file carefully, it should at least narrow down where it might be failing.

*Hope this helps,*
-**DennisL**

**Comment by planckm** [comment]
In the debug file the crouton bin and chroot directory is still the default one.
```
+ CROUTON_BIN=/usr/local/bin
+ CROUTON_CHROOTS=/usr/local/chroot'
```
At the end of the file there's this, for which the above accounts, in my opinion.
```
+ logger -p local3.info -t crouton(2585) *** Crouton 'trusty' directory is missing. Aborting!
+ logger -p local3.info -t crouton(2585) ###############
+ exit 1
/proc/self/fd/9: 1: Syntax error: "(" unexpected
```

**Comment by DennisLfromGA** [comment]
@planckm,

> In the debug file the crouton bin and chroot directory is still the default one.

Sounds like that's the problem. 
Make sure `/etc/init/crouton.conf` has the saved changes I listed above with the correct path to your external media.

*Hope this helps,*
-**DennisL**

**Comment by planckm** [comment]
In my conf file:
`  $LOGGER "##- Main checks started."
  if [ -d '/media/removable/sd-card/chroots' ]; then
    ## Uses external SD Card - as DEFAULT
    CROUTON_BIN='/media/removable/sd-card/bin'
    CROUTON_CHROOTS='/media/removable/sd-card/chroots'
elif [ -d /var/crouton/chroots ]; then
  ## Uses the @drinkcat 'separate_partition' branch - as DEFAULT
    CROUTON_BIN=/var/crouton/bin
    CROUTON_CHROOTS=/var/crouton/chroots
elif [ -d /usr/local/chroots ]; then
  ## Uses the @dnschneid 'master' branch
    CROUTON_BIN=/usr/local/bin
    CROUTON_CHROOTS=/usr/local/chroots
  else
  ## Nothing found...
    $LOGGER "*** Crouton 'chroots' directory is missing. Aborting!"
    $LOGGER "###############"
    exit 1
  fi`

In according part of debug file:
`+ logger -p local3.info -t crouton(2674) ##- Main checks started.
+ [ -d /media/removable/sd-card/chroots ]
+ [ -d /var/crouton/chroots ]
+ [ -d /usr/local/chroots ]
+ CROUTON_BIN=/usr/local/bin
+ CROUTON_CHROOTS=/usr/local/chroots
+ [ ! -d /usr/local/bin ]
+ logger -p local3.info -t crouton(2674) *** Crouton 'bin' directory is /usr/local/bin
+ logger -p local3.info -t crouton(2674) *** Crouton 'chroots' directory is /usr/local/chroots
+ logger -p local3.info -t crouton(2674) ##- Check for external control.`

So, it seems the sd card is recognized, but still the bin and chroots directories are linked to the wrong directories.

I check /usr/local/ and found a entity called 'chroots', probably from an earlier installation. I cannot remove it, I get the very strange following comments (is it a directory or not?):

`chronos@localhost /usr/local $ sudo rmdir chroots/
rmdir: failed to remove ‘chroots/’: Not a directory
chronos@localhost /usr/local $ sudo rm chroots/
rm: cannot remove ‘chroots/’: Is a directory`

**Comment by DennisLfromGA** [comment]
@planckm,

Interesting, your conf file looks to be correct but it seems that `/media/removable/sd-card/chroots` is either not the correct path or it's not mounted. The script falls through to `/usr/local/chroots` instead.

I have a separate partiton for my crouton chroots mounted at `/var/crouton` so the debug output for mine shows:
```
+ logger -p local3.info -t crouton(2692) ##- Main checks started.
+ [ -d /var/crouton/chroots ]
+ CROUTON_BIN=/var/crouton/bin
+ CROUTON_CHROOTS=/var/crouton/chroots
+ [ ! -d /var/crouton/bin ]
+ logger -p local3.info -t crouton(2692) *** Crouton 'bin' directory is /var/crouton/bin
+ logger -p local3.info -t crouton(2692) *** Crouton 'chroots' directory is /var/crouton/chroots
```
Which is correct in my case.

Sorry about these issues, I'll try to find time to put a chroot on external media and test it myself.
I'll get back to you ASAP.

----
If you're sure you want to remove `/usr/local/chroots` then this should work:

`sudo rm -rf /usr/local/chroots`

*Hope this helps,*
-**DennisL**

**Comment by planckm** [comment]
Thanks for all the help.

**Comment by DennisLfromGA** [comment]
No problem.
Just for sanity sake could you show us the output of:

`ls -l /media/removable/sd-card/`

It should show the `/bin` & `/chroots` folders at a minimum.

*Thanx,*
-**DennisL**

**Comment by planckm** [comment]
It does. Also a lost+found folder.

```
chronos@localhost / $ ls -l /media/removable/sd-card/
total 24
drwxr-xr-x 2 root root  4096 May 11 19:42 bin
drwxr-xr-x 3 root root  4096 May 11 19:40 chroots
drwx------ 2 root root 16384 May 11 18:59 lost+found
```

**Comment by DennisLfromGA** [comment]
@planckm,

I installed (restored) a chroot to an external sd card and got the same, disappointing results as you -
```
+ logger -p local3.info -t crouton(2740) ##- Main checks started.
+ [ -d /media/removable/8GB.EXT4/chroots ]
+ [ -d /var/crouton/chroots ]
+ CROUTON_BIN=/var/crouton/bin
+ CROUTON_CHROOTS=/var/crouton/chroots
+ [ ! -d /var/crouton/bin ]
+ logger -p local3.info -t crouton(2740) *** Crouton 'bin' directory is /var/crouton/bin
+ logger -p local3.info -t crouton(2740) *** Crouton 'chroots' directory is /var/crouton/chroots
```

I'm not sure why the conf script doesn't recognize the sd card, I know the path (`/media/removable/8GB.EXT4/chroots`) is correct 'cause I can launch it the same way from the command line.

I'll try to spend some more time with it and maybe ask one of the devs for some clues in the meantime.
I'll get back to you again ASAP.

*Hope this helps,*
-**DennisL**

**Comment by planckm** [comment]
Has there been some advancement with respect to these issues? Looking forward.

**Comment by DennisLfromGA** [comment]
@planckm,

Sorry no, not yet anyway.
I need to run this by someone more familiar with this or maybe the crouton devs if I'm really lucky.
 
I'll try to get you some feedback ASAP.

-**DennisL**

**Comment by planckm** [comment]
Still unresolved?

**Comment by DennisLfromGA** [comment]
As far as I know, yes, still unresolved.

**Comment by cobalt2727** [comment]
Any progress on this?

**Comment by DennisLfromGA** [comment]
None, I don't know what's preventing Chrome OS from recognizing external media unless it's just too early in the boot process or it's not allowed. I haven't figured it out.
