### ISSUE TITLE
Fullscreen (F11) Key in crouton.

### ISSUE THREAD

**Issue by 19nano** [dnschneid/crouton#3232]
```
sudo edit-chroot -all
Password: 
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
When using the "fullscreen" option in crouton, the fullscreen button on the chromebook does not work. In certain apps (ex Google Chrome in crouton), this means that you're stuck and you have to log out of chrome in order to use crouton again. Is there a way to make a button combination that will result in F11? Because F11 is what all the apps use to exit fullscreen.
I think that alt + fullscreen would work, because it would still work in xiwi. Right?
Any ideas? I'm still beginning my journey into the programming world so I can't really do anything...
On an Acer R11 flip.
PS: In an attempt to solve the issue, I did 

> sudo sh -e ~/Downloads/crouton -t keyboard -u

to try to fix it. see the github page for it here: [https://github.com/dnschneid/crouton/wiki/Keyboard](https://github.com/dnschneid/crouton/wiki/Keyboard)
#### If known, describe the steps to reproduce the issue:
Enter any app (like Terminal) and click the "Fullscreen" option in "View". Then try to use the fullscreen button on your keyboard that usually works in Chrome OS. It doesn't.

**Comment by DennisLfromGA** [comment]
@19nano,

I have chroot apps that need a full set of function keys, <kbd>F1</kbd> to <kbd>F12</kbd>
Chrome OS uses the <kbd>Search</kbd> key to enable them.

Use F keys (<kbd>F1</kbd> to <kbd>F12</kbd>)	<kbd>Search</kbd> + <kbd>1</kbd> through <kbd>Search</kbd> + <kbd>+
 =</kbd>

![KeyboardOverlay](http://i.imgur.com/hwW1OkE.jpg)

The keyboard overlay (chrome://keyboardoverlay/) will show you the shortcuts available.

*Hope this helps,*
-**DennisL**

**Comment by 19nano** [comment]
@DennisLfromGA Thank you.
