### ISSUE TITLE
Restore backup tar.gz to powerwashed chromebook.

### ISSUE THREAD

**Issue by the-pete** [dnschneid/crouton#3233]
```
Strangely, the install script doesn't seem to be adding the helper tools in the /usr/local/bin.  As this is a fresh install, and the files don't seem to be getting laid down, I can't run this command and I also don't have any chroots to show.

#### Please describe your issue:
After power wash, both restore and install are failing with a mount error.

#### If known, describe the steps to reproduce the issue:

chronos@localhost ~/Downloads $ curl https://raw.githubusercontent.com/dnschneid/crouton/master/installer/crouton -o ~/Downloads/crouton
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3653  100  3653    0     0  26379      0 --:--:-- --:--:-- --:--:-- 27674
chronos@localhost ~/Downloads $ sudo sh ~/Downloads/crouton -t core,cli-extra,extension,audio -r xenial -n xenial -e
Downloading latest crouton installer...
######################################################################## 100.0%
Choose an encryption passphrase for xenial: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
mount: mount(2) failed: No such file or directory
Failed to mount xenial.
chronos@localhost ~/Downloads $ su
Password: 
su: Permission denied
chronos@localhost ~/Downloads $ sudo -i
localhost ~ # cd /usr/local/bin
-bash: cd: /usr/local/bin: No such file or directory
localhost ~ # cd /usr/local
localhost local # ls -al
total 12
drwxr-xr-x.  2 root root 4096 May 13 13:54 .
drwxr-xr-x. 10 root root 4096 May  9 16:01 ..
-rw-r--r--.  1 root root 2305 May 13 12:14 chrome_dev.conf
lrwxrwxrwx.  1 root root   39 May 13 13:54 chroots -> /mnt/stateful_partition/crouton/chroots
localhost local # ls ./chroots/
trusty  xenial
localhost local # exit
logout
chronos@localhost ~/Downloads $ sudo rm -rf /usr/local/chroots/trusty/
chronos@localhost ~/Downloads $ ls /usr/local/chroots/
xenial
chronos@localhost ~/Downloads $ ls
crouton  trusty-20170513-1111.tar
chronos@localhost ~/Downloads $ sudo sh -e crouton -r trusty -t cli-extra -f ./trusty-20170513-1111.tar 
Specify -u if you want to add targets when you restore a chroot.
chronos@localhost ~/Downloads $ sudo sh -e crouton -r trusty -f ./trusty-20170513-1111.tar 
Finished restoring ./trusty-20170513-1111.tar to /mnt/stateful_partition/crouton/chroots/trusty
Enter encryption passphrase for trusty: 
mount: mount(2) failed: No such file or directory
Failed to mount trusty.
chronos@localhost ~/Downloads $ sudo find / -name edit-chroot
chronos@localhost ~/Downloads $

**Comment by DennisLfromGA** [comment]
@the-pete,

You might try using 'crouton's '-b' option to restore the needed host-bin files.

Just use: `sudo sh ~/Downloads/crouton -b`

*Hope this helps,*
-**DennisL**

**Comment by the-pete** [comment]
Output above shows trust chroot being removed since the data is copied there but then never able to be unlocked or restored.  A second attempt to restore fails because there is an existing directory in the path, however since the host helper files are not being put in place, I cannot attempt to enter or restore.

Output about host:
crosh> shell
chronos@localhost ~ $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=3986825
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={E020B8D4-CA96-4599-84DA-5017455418AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={E020B8D4-CA96-4599-84DA-5017455418AE}
CHROMEOS_RELEASE_BOARD=sentry-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=34
CHROMEOS_RELEASE_BUILDER_PATH=sentry-release/R59-9460.34.0
CHROMEOS_RELEASE_BUILD_NUMBER=9460
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=59
CHROMEOS_RELEASE_DESCRIPTION=9460.34.0 (Official Build) beta-channel sentry 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=beta-channel
CHROMEOS_RELEASE_VERSION=9460.34.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9460.34.0

**Comment by the-pete** [comment]
Same thing once the scripts are installed:

chronos@localhost ~ $ sudo sh ~/Downloads/crouton -b
Password: 
Downloading latest crouton installer...
######################################################################## 100.0%
WARNING: Signed boot verification is disabled; enabling it for security.
You can disable it again using: sudo crossystem dev_boot_signed_only=0
Installing startcli into the host...
Installing startxiwi into the host...
Installing startgnome into the host...
Installing startlxde into the host...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Done! You can enter the chroot using enter-chroot.

chronos@localhost ~ $ cd /usr/local/bin/
chronos@localhost /usr/local/bin $ ls -al
total 140
drwxr-xr-x. 2 root root  4096 May 14 11:57 .
drwxr-xr-x. 3 root root  4096 May 14 11:32 ..
-rwxr-xr-x. 1 root root  7304 May 14 11:57 crash_reporter_wrapper
lrwxrwxrwx. 1 root root    11 May 14 11:57 delete-chroot -> edit-chroot
-rwxr-xr-x. 1 root root 32076 May 14 11:57 edit-chroot
-rwxr-xr-x. 1 root root 34291 May 14 11:57 enter-chroot
-rwxr-xr-x. 1 root root 19775 May 14 11:57 mount-chroot
-rwxr-xr-x. 1 root root   724 May 14 11:57 startcli
-rwxr-xr-x. 1 root root   537 May 14 11:57 startgnome
-rwxr-xr-x. 1 root root   550 May 14 11:57 startlxde
-rwxr-xr-x. 1 root root  2123 May 14 11:57 startxiwi
-rwxr-xr-x. 1 root root 18640 May 14 11:57 unmount-chroot

chronos@localhost /usr/local/bin $ sudo sh -e ~/Downloads/crouton -r trusty -n trusty -f ~/Downloads/trusty-20170513-1111.tar 
Finished restoring /home/chronos/user/Downloads/trusty-20170513-1111.tar to /mnt/stateful_partition/crouton/chroots/trusty
Enter encryption passphrase for trusty: 
mount: mount(2) failed: No such file or directory
Failed to mount trusty.

**Comment by DennisLfromGA** [comment]
@the-pete,

Unless you're renaming the chroot there should be no need to enter '`-r trusty -n trusty`', it will obtain than info. from the backup file, you might just try this instead:

`sudo sh ~/Downloads/crouton -f ~/Downloads/trusty-20170513-1111.tar`

*Hope this helps,*
-**DennisL**

**Comment by the-pete** [comment]
I have, I was renaming the chroots trusty{1,2,3,4,5,6,} as I was trying things.

**Comment by DennisLfromGA** [comment]
@the-pete,

Maybe it's due to the encryption, I don't know.
I like to install my chroots and tweak them first then encrypt them after the fact if need be, it seems easier that way to me.

*Hope this helps,*
-**DennisL**
