### ISSUE TITLE
Reboot at gui boot (Samsung chromebook plus)

### ISSUE THREAD

**Issue by JulienAFrozenMiddle** [dnschneid/crouton#3234]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: arm64
xmethod: xorg
targets: xfce
host: version 9460.34.0 (Official Build) beta-channel kevin 
kernel: Linux localhost 4.4.52-08217-gc6521f7e1e75 #1 SMP PREEMPT Tue May 9 14:15:23 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...```

#### Please describe your issue:
On my Samsung Chromebook Plus, all used to be fine. Had not booted crouton in a while and the past few tries, when I sudo startgui (I have tried gnome, xfce, kde and lxde), I get a blank screen followed by a reboot.

Tried powerwashing, brought the device back to stable (from beta), nothing changes. My Asus C201 is still chugging along, it's just the CP that's acting up.

#### If known, describe the steps to reproduce the issue:
Any attempt to start a gui leads to this problem.

**Comment by DennisLfromGA** [comment]
@JaviMerino,

I haven't come across this issue before and I don't have that device so I can't be of much help I'm afraid.
There may be some logs that would shed some light on what caused the reboot but I don't know where to direct you. Maybe someone else can pitch in.

One thing you could try is to add & use the 'xiwi' target / xmethod and see if your desktop will launch properly. You can add it to your existing chroot by entering this command:

`sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

Once that installs successfully you can launch your desktop with 'xiwi' in a window by default or in fullscreen with `-X xiwi-fullscreen` or in a tab with `-X xiwi-tab` appended to your `start*` script.

Hope this helps,
-DennisL

**Comment by JulienAFrozenMiddle** [comment]
Thanks! I had not realized I could run xiwi fullscreen (I used it only to render windows with startxiwi -b command). That provides a not great but decent alternative to running xorg, so it will do for now until.. something is fixed, I guess.
