### ISSUE TITLE
linux wont boot up on my chrome book

### ISSUE THREAD

**Issue by snefftw** [dnschneid/crouton#3235]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9334.69.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 10 18:41:18 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

My issue is that i can no longer get crouton to boot up on my chrome book, because it says 
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

I have no idea how to recreate this, the first time i used it it opened perfectly and then power washed my chrome book and when i tried to reinstall crouton i keep getting this message.

**Comment by runner18** [comment]
You're not the only one. I've had a similar issue along with [OsiRex1020](https://github.com/dnschneid/crouton/issues/3276).
