### ISSUE TITLE
DisplayLink installation issue - Missing component: Linux headers for kernel, 3.14.0.

### ISSUE THREAD

**Issue by Tzuridis** [dnschneid/crouton#3236]
I have tried for trusty 14.04 and xenial 16.04 - and can even print out linux header kernel version to be 3.14.0 but no matter what I do I get:

Unsatisfied dependencies. Missing component: Linux headers for running kernel, 3.14.0. This is a fatal error, cannot install DisplayLink Linux Software.

Any ideas?

From what I can tell it doesn't seem like anyone else who isn't using chroots has this problem.

**Comment by cujo0072** [comment]
I think this issue: https://issuetracker.google.com/issues/187791868 with the chromeOS has to with the "missing" kernel headers. It looks like google is not going to fix it at all.
Thanks for using google chromeOS! :)
