### ISSUE TITLE
Ctrl-Space causing endless keyboard repeat of spaces

### ISSUE THREAD

**Issue by RobertGoulding** [dnschneid/crouton#3238]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: trusty
encrypted: no
Entering /media/removable/Crouton/chroots/trusty...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce-desktop,keyboard,chrome,audio
host: version 9460.42.0 (Official Build) beta-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Tue May 16 15:06:15 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
#### Please describe your issue:

The key combination ctrl-space starts repeating spaces -- as if you were holding down space bar with key repeat.

I first noticed this when using emacs, where ctrl-space to set mark is pretty essential.

The only solution is to turn off key repeat in the xfce keyboard settings.  Then ctrl-space sets mark in emacs, and doesn't keep printing spaces.  But that's not a great solution, becuse I *want* key repeat sometimes!

Going through all the various keyboard settings, I don't find where ctrl-space has been bound to anything.

I removed ibus, as other people have had a problem with it capturing ctrl-space - but it didn't make any difference.

#### If known, describe the steps to reproduce the issue:

In any open app that takes keyboard input, hit ctrl-space, and watch the screen fill up with spaces.

**Comment by wallace11** [comment]
I'll just mention that switching to Xorg would fix this problem.

**Comment by nxtr** [comment]
Feel your pain, very annoying with xiwi emacs.

I have found the repeating space to kick in with two or more input methods on the chromeos side. Still, ctrl+shift+space or ctrl+@ will work and give null char, debug with `xev`.

As a workaround for xiwi I kind of add a shift with xbindkeys.
Add `(xbindkey '(control space) "xset r off; xte 'keyup space'; xte 'keydown Shift_L' 'key space' 'keyup Shift_L'; xset r on" )` to [~/.xbindkeysrc.scm](https://github.com/nxtr/dotfiles/blob/ae6dc4fee6ced6a6e55d932c80131ffe41456b26/.xbindkeysrc.scm#L66-L67)  
Start `xbindkeys` manually or with [~/.xiwirc](https://github.com/nxtr/dotfiles/blob/ae6dc4fee6ced6a6e55d932c80131ffe41456b26/.xiwirc#L3)

**Comment by liuxiawei** [comment]
> Feel your pain, very annoying with xiwi emacs.
> 
> I have found the repeating space to kick in with two or more input methods on the chromeos side. Still, ctrl+shift+space or ctrl+@ will work and give null char, debug with `xev`.
> 
> As a workaround for xiwi I kind of add a shift with xbindkeys.
> Add `(xbindkey '(control space) "xset r off; xte 'keyup space'; xte 'keydown Shift_L' 'key space' 'keyup Shift_L'; xset r on" )` to [~/.xbindkeysrc.scm](https://github.com/nxtr/dotfiles/blob/c3b7089c2d433a72d57289b4eca77e127e2ec5bd/.xbindkeysrc.scm#L66-L67)
> Start `xbindkeys` manually or with [~/.xiwirc](https://github.com/nxtr/dotfiles/blob/c3b7089c2d433a72d57289b4eca77e127e2ec5bd/.xiwirc#L3)

Thanks,It's helpful

**Comment by abliss** [comment]
Also seeing this (on a first-gen chromebook pixel).
```
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 10895.78.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Oct 3 23:30:23 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
Thanks for the xbindkeys trick, but it does not seem to be working for me.
