### ISSUE TITLE
Crouton For Non-Chromebook Keyboards and Alt+Ctrl+Shift+Forward

### ISSUE THREAD

**Issue by ilyaigpetrov** [dnschneid/crouton#3239]
Hi.
I use crouton with [CloudReady](https://neverware.com) on a regular notebook (not chromebook), so I don't have Alt+Ctrl+Shift+Forward and Alt+Ctrl+Shift+Backward. I tried switching between VTs with Ctrl+Alt+Fx and sometimes it doesn't work.

How can I configure other shortcuts that will work on a standard keyboard?

**Comment by jcoonrod** [comment]
I have the same problem on a chromebox that uses a standard keyboard - surely there is some combination on a regular keyboard that should work?

**Comment by DennisLfromGA** [comment]
You can use '`croutoncycle`' in a crouton chroot shell to switch back to CrOS.
See the `croutoncycle` usage below:
```
croutoncycle -h
croutoncycle next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number
```

You can use the 'crouton integration' extension in CrOS to switch into your chroot(s)

*Hope this helps,*
-**DennisLfromGA**
