### ISSUE TITLE
i want to install only kali linux but when installing it give an error

### ISSUE THREAD

**Issue by siddhantsid** [dnschneid/crouton#3241]
I WANT TO DOWNLOAD THIS

sudo  sh ~/Downloads/crouton -r kali -t kde -n kali

  WHEN INSATLLING  THIS SHOWS

WARNING: kali has reached upstream end-of-life.
That means there will be no package updates available.
You also have to specify a mirror to crouton (-m) for installation to proceed.

CAN ANYONE TELL ME

**Comment by DennisLfromGA** [comment]
Use `'kali-rolling'`, see below for releases supported, unsupported, and eol'ed -

> Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch sid

> Recognized kali releases:
    moto! kali! sana! **kali-rolling**

> Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety* zesty*

> **Releases marked with ! are upstream end-of-life, and should be avoided.**
**Releases marked with * are unsupported, but may work with some effort.**

*Hope this helps,*
-**DennisL**
