### ISSUE TITLE
sudo startxfce4 not working

### ISSUE THREAD

**Issue by Blaze2658** [dnschneid/crouton#3242]
```
Please paste the output of the following command here: sudo edit-chroot -all

crosh> shell
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/bin/startxfce4: Starting X server

/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/kali...
chronos@localhost / $ 

#### Please describe your issue:
No idea what is going wrong, can someone walk me through it?
Might have to do with the kali linux ARM download?

#### If known, describe the steps to reproduce the issue:
I did what he told me to :
https://www.youtube.com/watch?v=ExRR3w4-8cg&index=1&list=PLuoU9aDujU800YCYi30WFLYWWy1gyP12S&spfreload=5

Thank you

**Comment by fergara** [comment]
Same here. The diff is that I tried using Debian sid: sudo sh -e ~/Downloads/crouton -r sid -t xfce-desktop

I am on Version 59.0.3071.57 (Official Build) beta (64-bit).

**Comment by TrueExile** [comment]
@Blaze2658 I don't think your doing anything wrong. I think its a problem with Kali right now. If I install -r Trusty it works fine for me. However when I try Kali-rolling it has the same problem every time.

**Comment by Scott-McD** [comment]
@fergara I am having the same issue. Please let me know if you find a fix.

**Comment by fergara** [comment]
I was able to install and run successfully using Xenial. Problem should be related to Kali n Sid (Debian). My hardware is the toshiba chromebook 2 cb35-b3340.

**Comment by Scott-McD** [comment]
@fergara Thanks for the help!

**Comment by Blaze2658** [comment]
@fergara if i use that command will that work on an hp chromebook? will it work this time? thanks for the help

**Comment by fergara** [comment]
Hey, @Blaze2658. Not sure. I believe the issue is Debian Sid, no matter the hardware you have. Give it a try and let us know the result. If it does not work, delete the chroot: `sudo delete-chroot sid`.

**Comment by TrueExile** [comment]
@fergara Ok so I'm pretty new to the linux party.... This may be a stupid question.. What is Xenial?

**Comment by fergara** [comment]
Xenial is Ubuntu 16.04 LTS. Zesty is 17.04. Check http://distrowatch.com/table.php?distribution=ubuntu and you will see a list of all Ubuntu versions. I use the site to check for new versions of all Linux flavors and go to a specific distro website.

**Comment by TrueExile** [comment]
AAAAHHHHhhh... Here I was trying to use it as a GUI target. Now if we want to use kali-rolling are we just SOL until the sid gets fixed/updated?

Thanks

**Comment by Blaze2658** [comment]
@fergara didn't work, deleted the chroot. I cant figure out how to make this work. may or may not have left out that i'm using kali-rolling :\   P.S. i'm NO expert at all on this.

If you can walk me through the steps from the start, i would appreciate it 👍

**Comment by fergara** [comment]
I believe the problem is Kali, the same way I had problems with Debian Sid.

sudo sh -e ~/Downloads/crouton -r sid -t xfce-desktop -- install Debian with Xfce -- did not work for me
sudo sh -e ~/Downloads/crouton -r xenial -t xfce-desktop -- install Ubuntu 16.04 with Xfce -- this worked!

You should try a different distro and forget Kali for now.

**Comment by Blaze2658** [comment]
chronos@localhost / $ sudo startxfce4
Password: 
Entering /mnt/stateful_partition/crouton/chroots/sid...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.10.18 #1 SMP Wed May 17 17:56:16 PDT 2017 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=f8d26eb0-ecc6-4e4d-8211-8e91c7585ba1/PARTNROFF=1 hashtree=PARTUUID=f8d26eb0-ecc6-4e4d-8211-8e91c7585ba1/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=3a9577bd5f40d736a77c0134a250b8113daefd98 salt=0041823f1e0537ba377e4a1b442cc69c00a21e4cf58946079bfb0ee333dd1dd8" noinitrd vt.global_cursor_default=0 kern_guid=f8d26eb0-ecc6-4e4d-8211-8e91c7585ba1  
Build Date: 15 March 2017  09:47:32PM
xorg-server 2:1.19.3-1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jun  1 16:53:21 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

0_0 *wtf

**Comment by TrueExile** [comment]
Yep. Think the consensus is there is something broken. Ubuntu is working fine. I haven't found a work-around yet.

**Comment by dcecile** [comment]
@Blaze2658 Did you do something to get this error to go away?

```
/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server
```

Also, is there anything in your `/etc/X11/Xwrapper.config` file? I'm thinking we might be missing group membership... (I've got the same `parse_vt_settings` error right now.)

**Comment by dcecile** [comment]
OK, I think I found the fix over in #2875?

> @dnschneid: We could consider making crouton install a fake version of xserver-xorg-legacy just to make sure it never accidentally gets installed...

In my `/var/log/apt/history.log` file, I found that `xserver-xorg-legacy` got installed together with my most recent system update. Then I remembered the title of #2875, so I tried `sudo apt remove xserver-xorg-legacy`.

Does this also work for anyone else?

**Comment by wdmjun** [comment]
Worked for me.
I am running Debian Sid and LXDE in my chroot.
I ran 'aptitude purge xserver-xorg-legacy' and now X starts.
Looks like my system update from May 6 installed xserver-xorg-legacy and caused the problem.
Thanks dcecile

**Comment by swors** [comment]
@wdmjun Did you have this problem #2674 , after ' aptitude purge xserver-xorg-legacy'

**Comment by Blaze2658** [comment]
Thanks for your help everyone, but I have since uninstalled kali and moved on to ubuntu after too many failed attempts. Thanks anyway though.

**Comment by wdmjun** [comment]
swors:No. After 'aptitude purge xserver-xorg-legacy' everything has been working swimmingly.

**Comment by jernic** [comment]
I had this problem after upgrading a chroot (kali-rolling, xiwi, xfce). Logged into the chroot using enter-chroot, ran 'sudo apt remove xserver-xorg-legacy', and this seems to have fixed it. Thanks!

**Comment by ncouture** [comment]
see https://github.com/dnschneid/crouton/issues/2676#issuecomment-338672876.

**Comment by TrueExile** [comment]
What I did was download a core version and then installed what I needed. I
kept having an audio driver error that it wouldn't get past. It's now
working but I have done anything with it sense I got past the problem.

**Comment by CroutonGeek** [comment]
If deleting the xserver-xorg-legacy package deosn't resolve the issue, add the x11 target to your chroot.
