### ISSUE TITLE
Turn off gnome

### ISSUE THREAD

**Issue by razmikb** [dnschneid/crouton#3243]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome
host: version 9334.72.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 17 17:58:32 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

Hi, how should I disable gnome? It doesn't have log out function (as far as I know) like other desktops.

**Comment by DennisLfromGA** [comment]
@razmikb,

I've run into this a couple of times at least, most recently with an elementary desktop and found one or both of the following to work:
```
exec gnome-session-quit --no-prompt
exec gnome-session-quit --logout --force
```
I actually use both in a `logout.sh` script that simply contains the above two lines.
You have to run it from the command line or I guess you could make a `.desktop` file for it and luanch it in a gui.

*Hope this helps,*
-**DennisL**
