### ISSUE TITLE
Xenial file not found?

### ISSUE THREAD

**Issue by Cyan101** [dnschneid/crouton#3247]
```
Please paste the output of the following command here: sudo edit-chroot -all

chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue: When trying to run `sudo startxfce4` i get this output
```
chronos@localhost / $ sudo startxfce4
Enter encryption passphrase for xenial: 
mount: mount(2) failed: /run/crouton/mnt/stateful_partition/crouton/chroots/xenial: No such file or directory
Failed to mount xenial.
```

Trying to manually list out the files in that folder returns nothing and it looks empty, although 
`mnt/stateful_partition/crouton/chroots/xenial/` has 3.8GB of files/folders in it so i'm unsure what happened

#### If known, describe the steps to reproduce the issue:
Not too sure, been using Xenial for a while and has been fine, recently i did follow a guide on how to use android apps in chromeos
I followed this guide: https://www.reddit.com/r/chromeos/comments/63nfy6/how_to_get_android_apps_on_most_chromebooks_dev/

**Comment by DennisLfromGA** [comment]
@Cyan101,

> encrypted: yes, locked

Your chroot is encrypted & locked.

Can you run `sudo enter-chroot -n xenial croutonversion` and show us the output please?

-**DennisL**

**Comment by Cyan101** [comment]
```
chronos@localhost / $ sudo enter-chroot -n xenial croutonversion
Password: 
Enter encryption passphrase for xenial: 
mount: mount(2) failed: /run/crouton/mnt/stateful_partition/crouton/chroots/xenial: No such file or directory
Failed to mount xenial.
```

The passwords were entered fine, its just... gone?

**Comment by DennisLfromGA** [comment]
@Cyan101,

I don't think enabling Android apps harmed anything in your chroot, I do that too on my Dell and it hasn't affected my chroots in any way.

I'm stumped though about why it stopped working all of a sudden unless it's related to the encryption somehow. Maybe someone more knowledgeable will jump in.

*Sorry I couldn't be more help,*
-**DennisL**_

**Comment by Cyan101** [comment]
/shrug looks like its just gone, no idea why ;-;

**Comment by Cyan101** [comment]
```
chronos@localhost / $ sudo sh ~/Downloads/crouton -e -r trusty -t xfce
Choose an encryption passphrase for trusty: 
Please confirm your passphrase: 
Generating keys (move the mouse to generate entropy)...
done
mount: mount(2) failed: /run/crouton/mnt/stateful_partition/crouton/chroots/trusty: No such file or directory
Failed to mount trusty.```

Tried to make a new Trusty, didn't work :/ same with making a new xenial..... whats happening?

**Comment by DennisLfromGA** [comment]
@Cyan101,

I would try it without using the '-e' option to encrypt your chroot, you can always encrypt it later if need be.

*Hope this helps,*
-**DennisL**

**Comment by Cyan101** [comment]
Yeah tried with that too, still the same thing :(

ended up powerwashing and redoing it all

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by jessaustin** [comment]
Uh, my chromebook just insisted on auto-updating for "Android apps", and now I have the same problem as OP.

**Comment by DennisLfromGA** [comment]
DUP: This issue may be the same or related to the work being done on this PR:

Link user keychain to session keychain #3246 --> Create new session, then link user keychain to session keychain #3278

Hope this helps,
-DennisL

**Comment by jessaustin** [comment]
Oh thanks @DennisLfromGA -- those two `keyctl` lines did the trick.

**Comment by petitdemon** [comment]
Hi! I came accross the same issue ("Failed to mount trusty") and I understand you have found a solution. I tried to copy the keyctl lines you mentioned but as I don't know much about coding and don't speak a very good English, I must have missed something. Would you mind explaining how you solved this?
Thanks a lot.

**Comment by DennisLfromGA** [comment]
@petitdemon,

No need for any extra effort now, the changes have been merged so just update your chroot using something like: `sudo sh ~/Downloads/crouton -u`

*Hope this helps,*
-**DennisL**

**Comment by petitdemon** [comment]
Yes, it works. Thank you so much!
