### ISSUE TITLE
disable lock screen

### ISSUE THREAD

**Issue by peepo** [dnschneid/crouton#3248]
almost new install of kde using crouton on Asus C200M intel chromebook

I installed powerdevil wfm

Is there a way to disable lock screen, default is password is required after 4 minutes?

I searched for lock, screen, display, behavior, widgets and more, but did not find way to alter.

I like to watch things for more than 4 minutes, so this is a deal breaker.....

I also appreciate this is likely kde issue, but did not find solution on www
apologies

croutonpowerd -i &
        did not wfm

**Comment by macemoneta** [comment]
For people from the future, there's a missing package from the kde installation.

`# apt-get install kde-config-screenlocker`

You can then go to KDE's system settings -> Desktop behavior

Select the screen locking icon on the left, and you'll have the option to disable the screen lock.

**Comment by mikefedyk** [comment]
I can confirm installing kde-config-screenlocker works with kubuntu 16.04 as well.

**Comment by peepo** [comment]
Bloatware? 92Mb? really?

installed and found under screensaver

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
