### ISSUE TITLE
Trying to install Crouton on SD Card /dev/mmcblk1p1 not a valid prefix.

### ISSUE THREAD

**Issue by Hunter115** [dnschneid/crouton#3252]
```

Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9334.72.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-13985-g8bf2eb2 #1 SMP PREEMPT Wed May 17 17:45:59 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
chronos@localhost / $ name: trusty
#### Please describe your issue:
I've been working on getting crouton on my SD Card. My chromebook has limited space and I'd like to have Steam games on it. Right now I can't download Crouton directly to my SD card as it says not a valid prefix. 

#### If known, describe the steps to reproduce the issue:
I've tried variations of sudo sh -e ~/Downloads/crouton -r trusty -t xfce -e -p /media/removable/dev/SD
or /dev/mmcblk1p1 but I haven't been able to install crouton on the SD Card.

**Comment by DennisLfromGA** [comment]
@Hunter115,

With your SD Card plugged in, enter this: `ls -l /media/removable/`
That should give you the name of your external media. Then you can enter it in quotes in case there's a space or other character that's interfering using something like this:

 `sudo sh ~/Downloads/crouton -r trusty -t xfce -e -p "/media/removable/dev/SD Card"`

If it were me, I would not encrypt it initially, I would get it working first and then encrypt it with a crouton update once everything is working smoothly.

*Hope this helps,*
-**DennisL**

**Comment by Hunter115** [comment]
Crouton started installing on my SD card

With this command 

sudo sh ~/Downloads/crouton -r trusty -t xfce -e -p "/media/removable/SD Card"

the install failed though and I updated the install but that didn't work either.


Building dependency tree... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apt apt-utils base-files bash bsdutils coreutils cpio dh-python dpkg e2fslibs e2fsprogs eject file gcc-4.8-base gcc-4.9-base gnupg gpgv ifupdown
  init-system-helpers initramfs-tools initramfs-tools-bin initscripts iproute2 iputils-ping isc-dhcp-client isc-dhcp-common klibc-utils
  libapt-inst1.5 libapt-pkg4.12 libblkid1 libc-bin libc6 libcgmanager0 libcomerr2 libdbus-1-3 libdrm2 libexpat1 libffi6 libgcc1 libgcrypt11
  libgnutls-openssl27 libgnutls26 libjson-c2 libjson0 libklibc libmagic1 libmount1 libpam-modules libpam-modules-bin libpam-runtime libpam0g
  libpcre3 libplymouth2 libpng12-0 libprocps3 libpython3.4-minimal libpython3.4-stdlib libselinux1 libsepol1 libsqlite3-0 libss2 libssl1.0.0
  libstdc++6 libtasn1-6 libudev1 libuuid1 locales login lsb-base lsb-release makedev mime-support mount multiarch-support net-tools ntpdate passwd
  perl perl-base perl-modules plymouth procps python3.4 python3.4-minimal resolvconf rsyslog sudo sysv-rc sysvinit-utils tar tzdata udev upstart
  util-linux vim-common vim-tiny
96 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 37.3 MB of archives.
After this operation, 131 kB disk space will be freed.
E: Method http has died unexpectedly!
E: Sub-process http received signal 4.
Failed to complete chroot setup.
Unmounting /media/removable/SD Card/chroots/trusty...

**Comment by DennisLfromGA** [comment]
@Hunter115,

> E: Method http has died unexpectedly!

I think that's a transient network error that happens sometimes.

I would either try to update your chroot using: 

`sudo sh ~/Downloads/crouton -n trusty -p "/media/removable/SD Card" -u`

Or just get into the chroot and let the setup finish using: 

`sudo enter-chroot -n trusty -c "/media/removable/SD Card/chroots"`

*Hope this helps,*
-**DennisL**

**Comment by Hunter115** [comment]
Tried that and it says

The following packages will be upgraded:
  apt apt-utils base-files bash bsdutils coreutils cpio dh-python dpkg e2fslibs e2fsprogs eject file gcc-4.8-base gcc-4.9-base gnupg gpgv ifupdown
  init-system-helpers initramfs-tools initramfs-tools-bin initscripts iproute2 iputils-ping isc-dhcp-client isc-dhcp-common klibc-utils
  libapt-inst1.5 libapt-pkg4.12 libblkid1 libc-bin libc6 libcgmanager0 libcomerr2 libdbus-1-3 libdrm2 libexpat1 libffi6 libgcc1 libgcrypt11
  libgnutls-openssl27 libgnutls26 libjson-c2 libjson0 libklibc libmagic1 libmount1 libpam-modules libpam-modules-bin libpam-runtime libpam0g
  libpcre3 libplymouth2 libpng12-0 libprocps3 libpython3.4-minimal libpython3.4-stdlib libselinux1 libsepol1 libsqlite3-0 libss2 libssl1.0.0
  libstdc++6 libtasn1-6 libudev1 libuuid1 locales login lsb-base lsb-release makedev mime-support mount multiarch-support net-tools ntpdate passwd
  perl perl-base perl-modules plymouth procps python3.4 python3.4-minimal resolvconf rsyslog sudo sysv-rc sysvinit-utils tar tzdata udev upstart
  util-linux vim-common vim-tiny
96 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 37.3 MB of archives.
After this operation, 131 kB disk space will be freed.
WARNING: The following packages cannot be authenticated!
  base-files bash coreutils dpkg libpcre3 libselinux1 sysv-rc sysvinit-utils mount lsb-base libpam0g libpam-modules-bin libpam-modules passwd
  initscripts libdbus-1-3 libjson-c2 libuuid1 libblkid1 libcgmanager0 tzdata util-linux libprocps3 procps udev libudev1 iproute2 ifupdown libjson0
  upstart libc-bin gcc-4.9-base libgcc1 libc6 e2fslibs e2fsprogs login perl perl-base perl-modules tar gcc-4.8-base libstdc++6 libapt-pkg4.12 gpgv
  gnupg apt bsdutils libcomerr2 libmount1 libsepol1 libss2 libapt-inst1.5 libexpat1 libffi6 libgcrypt11 libtasn1-6 libgnutls-openssl27 libgnutls26
  file libmagic1 mime-support libsqlite3-0 python3.4 libpython3.4-stdlib python3.4-minimal libssl1.0.0 libpython3.4-minimal ntpdate resolvconf
  libdrm2 klibc-utils libklibc initramfs-tools initramfs-tools-bin cpio plymouth libpng12-0 libplymouth2 libpam-runtime multiarch-support apt-utils
  dh-python eject init-system-helpers iputils-ping isc-dhcp-client isc-dhcp-common lsb-release net-tools rsyslog sudo vim-tiny vim-common locales
  makedev
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in trusty
Unmounting /media/removable/SD Card/chroots/trusty...

**Comment by DennisLfromGA** [comment]
@Hunter115,

I looked up **"WARNING: The following packages cannot be authenticated!"** and found this answer -

> [Why am I getting authentication errors for packages from an Ubuntu repository?](https://askubuntu.com/a/75575)

I don't know why that's happening and, since the setup script was deleted, you won't be able to apply that solution.

At this point I would try to update your chroot again using:

sudo sh ~/Downloads/crouton -n trusty -p "/media/removable/SD Card" -u

If that doesn't work then I would first install it on the internal drive and then move or copy it to the external media using something like:

`sudo edit-chroot trusty -m  "/media/removable/SD Card/chroots/trusty"`

*Hope this helps,*
-**DennisL**

**Comment by Hunter115** [comment]
I tried updating the chroot several times. Then I used the command 

sudo edit-chroot trusty -m "/media/removable/SD Card/chroots/trusty"

but it says

Chroots can only be moved to ext filesystems.

Which is strange because I formatted my SD Card to ext4 and GParted says it is that format.

**Comment by Hunter115** [comment]
I figured it out. 

I went to this page

https://www.maketecheasier.com/map-crouton-installation-external-device-chromebook/

Changed chroot to trusty at the end

sudo ln -s /media/removable/SD/chroots/ trusty

For symbolic link

sudo sh ~/Downloads/crouton -r trusty -t xfce -p "/media/removable/SD"

To Enter Chroot

sudo enter-chroot -n trusty -c "/media/removable/SD/chroots"

then

startxfce4.

Thanks for the help.

**Comment by DennisLfromGA** [comment]
@Hunter115,

Glad you figured it out 'cause I was stumped, especially after the message:

> Chroots can only be moved to ext filesystems.

That didn't make any sense to me.

I've seen others use the link to external media before successfully but I hadn't thought of suggesting it.
I'll definitely offer that solution the if/when this issue crops up again.

Thanx,
-**DennisL**
