### ISSUE TITLE
Transparent Terminal?

### ISSUE THREAD

**Issue by ryanphjohnson** [dnschneid/crouton#3257]
```
sudo startxiwi -b -n chrootname xfce4-terminal
```

#### Please describe your issue:
Would love to have a transparent terminal. Not certain if its possible or not. I tried to open xfce4-terminal in its own window, but that gave me a black background.

#### If known, describe the steps to reproduce the issue:
Install a terminal that can be transparent like xfce4-terminal. Switch background to transparent. See solid black background.

I like the default terminal well enough, but it'd be nice to have a transparent one. I'm wondering if I'm doing it wrong, or if its simply not possible.

Thanks

**Comment by DennisLfromGA** [comment]
@ryanphjohnson,

According to [this page](http://docs.xfce.org/apps/terminal/preferences#background), you can set a transparent background.

I use ['guake'](http://guake-project.org/) for my terminal emulator, the background can made totally transparent or in varying steps and has a bunch of other nice options. 

It can be launched with the `startxiwi` command also.

*Hope this helps,*
-**DennisL**

**Comment by ryanphjohnson** [comment]
Well, I appreciate the help, but while trying to get this to work I updated crouton, and am now suffering from issue #2194. So I can still open my primary terminal, but from there, I cannot run xiwi guake or xiwi xfce4-terminal. It would seem I've shot myself in the foot while trying to fix something that wasn't broken :(

**Comment by ryanphjohnson** [comment]
I resolved that issue. Back to my main point. So I tried both, but I'm still not seeing the transparent window. I tried including xfce, and xfce-dersktops as targets to the chroot, but that didnt seem to help.

![screenshot 2017-06-07 at 6 28 07 pm](https://user-images.githubusercontent.com/5459646/26905815-24e3e31c-4baf-11e7-9163-e5233677cb3b.png)

**Comment by ryanphjohnson** [comment]
So I'm trying to follow the instructions listed here: http://users.ox.ac.uk/~kell3138/code/notes/Hardware/graphicscard/REFERENCE/TIP_Xorg_X11_and_Transparency.htm under the assumption that the terminal is using xorg. So my thought process is lets just make an xorg terminal transparent. I'm running into an issue where xdpyinfo says there is no display. or more specifically:
xdpyinfo:  unable to open display "".
If I could resolve that, I may be able to continue following these instructions and get that sweet sweet transparent terminal.

**Comment by ryanphjohnson** [comment]
Perhaps its failing because there is no xserver running inside the chroot? Or at least its not accessible (speaking way beyond my knowledge at this point)?

**Comment by ryanphjohnson** [comment]
So, it seems like I just need to get this working: http://forchheimer.se/transset-df/. It also runs into an issue with finding the display:

unknown_program:  unable to open display ''

If I could get that working, I may get what I want... maybe.

**Comment by DennisLfromGA** [comment]
@ryanphjohnson,

Well, you seem to have drilled down to the problem at least, good job.
I usually just use a terminal emulator while in the chroot and hadn't really found a need to run it as a xiwi app - but that's just me.

I wonder if setting the DISPLAY might help.
Here's [another issue](https://github.com/dnschneid/crouton/issues/3237) that's probably related, maybe the devs will see this and offer some suggestions.

-**DennisL**

**Comment by ryanphjohnson** [comment]
Well, this seems to be a bust/limitation of Crouton. I was able to get transset-df "working", and it was able to run without errors. The window is still not transparent though.

**Comment by Chlerry** [comment]
Hi. I just got a Pixelbook a few days ago and I am also digging into this issue. 
I have found a solution yet but I am pretty sure that you can not get a transparent terminal because your graphic is inside Crosh Window (which is a Chrome app). 
I guess the only possibility for solving this is trying to find a way to get Chrome app transparent. 
Please let me know if you have more thoughts on this. Thanks.

**Comment by DennisLfromGA** [comment]
guake terminal -

![screenshot 2018-06-12 at 11 26 35 pm](https://user-images.githubusercontent.com/3418772/41328830-39b8aa68-6e98-11e8-8dfd-c149f9dcefc9.png)

*Hope this helps,*
-**DennisLfromGA**

**Comment by Chlerry** [comment]
Thank. I tried Guake but I cant make it work with xiwi.
