### ISSUE TITLE
nfs module install

### ISSUE THREAD

**Issue by tjtr33** [dnschneid/crouton#3258]
Please paste the output of the following command here: sudo edit-chroot -all

```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9334.72.0 (Official Build) stable-channel quawks
kernel: Linux localhost 4.4.44-07366-g24ac249 #1 SMP PREEMPT Wed May 17 18:06:46 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
Difficulty getting nfs filesystem to work with crouton/chromium

NFS is not enabled in Chromium, so i built new kernel using master. 
To build, I followed
 https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules
 
I use this script to unlock the ro filesystem ( to allow new module to be loaded )
https://raw.githubusercontent.com/divx118/crouton-packages/master/change-kernel-flags

I cannot install new nfs.ko because vermagic differs. 
what crouton installed automatically for ubuntu xenial   4.4.44-07366-g24ac249
what i built                                                                                4.4.64-09688-g37a1dbd

I could not find how to 'git' the correct version ( the running version )
so i think i need to build same as i run... but
I fear that one update to master during the hour or so i need to install crouton and build kernel modules would yield the same vermagic problem. 

Is there a way to specify the kernel version source version (like 073660g24ac249)?

Am i trying impossible (or near)  by forcing the nfs feature into crouton?

#### If known, describe the steps to reproduce the issue:
... well the above shows the steps taken, hope thats sufficient

thanks tomp

**Comment by tjtr33** [comment]
update: 06082017 tonight i was able to git linux4.4.44 and checkpout branch 07366-g24ac249. I did not have the correct version before, thats why the branch didnt exist. I will now config to allow NFS and build. I will try insmod after i get a successful build. cul8r, tomp

**Comment by tjtr33** [comment]
update: 10 june 2017, 
short story: build ok but cant insmod the .ko
insmod: ERROR: could not insert module ./fs/nfs/nfs.ko: Operation not permitted
i used the 'change-kernel-flags' script to allow module loading 

long story: 
Please paste the output of the following command here: sudo edit-chroot -all
"""
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9334.72.0 (Official Build) stable-channel quawks
kernel: Linux localhost 4.4.44-07366-g24ac249 #1 SMP PREEMPT Wed May 17 18:06:46 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
chronos@localhost / $
"""
build ok,
kernel modules built ok

check the modules exist
"""
(xenial)tomp@localhost:/media/removable/Toms4TB/buildChromeOSwithNSFability/tmp4gitver07366-g24ac249/kernel$ find ./ -name *.ko | grep nfs   
./fs/nfs/nfs.ko
./fs/nfs/nfsv2.ko
./fs/nfs/nfsv3.ko
./fs/nfs_common/grace.ko
"""
i installed the modules to /lib/modules by editing /etc/rc.local per instructions

i have run script   sudo sh ~/Downloads/change-kernel-flags and rebooted
"""
chronos@localhost ~ $ sudo sh ~/Downloads/change-kernel-flags
Password:
/tmp/change-kernel-flags.ywP.2
Saving Kernel A config to /tmp/change-kernel-flags.ywP.2
(Kernels have not been resigned.)

Kernel flags added or changed are:
"lsm.module_locking=0 disablevmx=off"

Full cmdline is:
console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 
dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=%U/PARTNROFF=1 hashtree=PARTUUID=%U/PARTNROFF=1 hashstart=3584000 alg=sha1 
root_hexdigest=3024546be8a5bf4c0dcff3da4c2bf45291c8fe2c salt=7f7cfd4441f401e914d99d266aa81ba8dec033d6b3d7982403ef3cad19b65c97" 
noinitrd vt.global_cursor_default=0 kern_guid=%U add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 
nmi_watchdog=panic,lapic maxcpus=3   lsm.module_locking=0 disablevmx=off

Do you want to apply those changes (y/N)?y
 Kernel A: Replaced config from /tmp/change-kernel-flags.ywP.2
Backup of Kernel A is stored in: /mnt/stateful_partition/backups/kernel_A_20170610_162916.bin
Kernel A: Re-signed with developer keys successfully.
Successfully re-signed 1 of 1 kernel(s)  on device /dev/mmcblk0.
dev_boot_usb           = 1                              # Enable developer mode boot from USB/SD (writable)
dev_boot_legacy        = 1                              # Enable developer mode boot Legacy OSes (writable)
dev_boot_signed_only   = 0                              # Enable developer mode boot only from official kernels (writable)

Reboot to make the changes take effect.
"""
i rebooted and then tried to insmod a kernel module

(xenial)tomp@localhost:/media/removable/Toms4TB/buildChromeOSwithNSFability/tmp4gitver07366-g24ac249/kernel$ sudo insmod ./fs/nfs/nfs.ko
[sudo] password for tomp: 
insmod: ERROR: could not insert module ./fs/nfs/nfs.ko: Operation not permitted

i do not know what 'Operation not permitted' means

I think the operation should be permitted becasue:
I have removed the module locking using the script 
I ran the command as sudo
I verified the file is of the same branch and version using modinfo
I checked every log and found no more information
I tried modprobe -v also, but got no additional info 

any ideas?
thanks TomP

**Comment by AdamDanischewski** [comment]
Unfortunately you can't load kernel modules on a Chromebook because of a decision by Google (geniuses) to not allow a root user who has control over their whole system otherwise to be capable of dynamically loading kernel modules. It is a boot flag, and to change it is somewhat dangerous because you have to dd your drive to hit the flag. If you are going to try it, I suggest you make a full back up image of the drive so you can put it back if something goes wrong. 

See here for instructions on how: https://github.com/dnschneid/crouton/issues/1278

**Comment by AdamDanischewski** [comment]
I recommend you look into user space solutions like sshfs.

**Comment by divx118** [comment]
@AdamDanischewski He already disabled module_locking.
@tjtr33 Take a look at the output of dmesg and see why the operation is not permitted. You also need to load the required modules in a specific order see https://github.com/dnschneid/crouton/wiki/How-to-mount-network-shares-on-Chromebook-(sshfs,-cifs,-nfs-etc)#mounting-network-shares-with-autofs

**Comment by AdamDanischewski** [comment]
He has to make sure that what he ran ended up with: `crossystem dev_boot_signed_only=0`

Here is some history on this issue, looks like dschneid fought the smart fight on this, unfortunately politics and likely undiscussed rationales prevailed: 
https://bugs.chromium.org/p/chromium/issues/detail?id=451125
More history: 
https://lwn.net/Articles/526983/

**Comment by divx118** [comment]
@AdamDanischewski Yeah, but he used my script and that makes sure that the flag is set. https://github.com/divx118/crouton-packages/blob/master/change-kernel-flags#L281 Best way to see if everything goes well is to look at dmesg. That will tell you why the insmod failed also there it will show if module_locking is disabled. My guess is that it will fail, because you need to insmod some other modules first where nfs.ko depends on. This is mentioned in the wiki page I posted above.

**Comment by AdamDanischewski** [comment]
I took a quick look at the scripts involved, they look fine. He should still probably check it to make sure that everything with make_dev_ssd.sh worked as expected. He can open a shell from chrome and simply type: `crossystem dev_boot_signed_only` to make sure it is set to **0** (not empty/error). 

He can test with other kernel modules to see if it's related specifically to nfs.ko.
