### ISSUE TITLE
Failed to complete chroot setup

### ISSUE THREAD

**Issue by pskishere** [dnschneid/crouton#3264]
![screenshot 2017-06-10 at 2 55 16 pm](https://user-images.githubusercontent.com/24949944/27001158-836e1abe-4d77-11e7-92b9-8e7df2264dab.png)
I do not know how to handle it . I am using samsung chromebook plus .

![screenshot 2017-06-10 at 2 42 06 pm](https://user-images.githubusercontent.com/24949944/27001100-4d7d3c42-4d76-11e7-8e13-9960a4985a5a.png)

**Comment by DennisLfromGA** [comment]
@pskishere,

I think you need to delete it and start over.

*Hope this helps,*
-**DennisL**
