### ISSUE TITLE
Cannot run XBMC (segmentation error)

### ISSUE THREAD

**Issue by namethinger1234** [dnschneid/crouton#3265]
```
Please paste the output of the following command here: 
name: jessie
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/jessie...
crouton: version 1-20170315143304~master:95589555
release: jessie
architecture: armhf
xmethod: xorg
targets: xbmc
host: version 9334.72.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 17 17:55:22 PDT 2017 armv7l GNU/Linux
freon: yes
```

---------------------------------------------------------------------------------------------------------------------------------

I installed the XBMC target with Jessie Debian and every time i type try to start xbmc it is "Unable to create GUI" due to a segmentation error if im reading it correctly.

---------------------------------------------------------------------------------------------------------------------------------

Here is the text in crosh after i run it if it helps: 
Entering /mnt/stateful_partition/crouton/chroots/jessie...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-0.bpo.4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 17 17:55:22 PDT 2017 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=aecd52b1-3d20-c244-b35d-a88bdb27d223/PARTNROFF=1 hashtree=PARTUUID=aecd52b1-3d20-c244-b35d-a88bdb27d223/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=13c86f05e01f42cd3329f8f4c9078c47a394acd8 salt=ea496081b0bf8b361be9496738b2d40be53159adbaeaf53e35f3dd46c16b1ce5" noinitrd vt.global_cursor_default=0 kern_guid=aecd52b1-3d20-c244-b35d-a88bdb27d223  
Build Date: 11 February 2015  01:18:06AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Jun 10 09:57:48 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
crouton: version 1-20170315143304~master:95589555
release: jessie
architecture: armhf
xmethod: xorg
targets: xbmc
host: version 9334.72.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 17 17:55:22 PDT 2017 armv7l GNU/Linux
freon: yes
Stream error -12
ERROR: Unable to create GUI. Exiting
Segmentation fault (core dumped)
Crash report available at /home/jim/xbmc_crashlog-20170610_095750.log
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(EE) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/jessie...

**Comment by zguithues** [comment]
Xbmc has been renamed to Kodi.

I have created a pull request #3277 that provides the necessary changes to incorporate the new name.

I don't remember running into the same issue you're having, but i can tell you it works great with xenial.  If/when my pull request gets approved, i'd recommend giving it a try with xenial.  The PPA i used has a much more recent version of kodi.  The Debian repositories have a very old version of kodi.

sudo sh ~/Downloads/crouton -t kodi -n kodi
this works great for me.  but you'll have to either build your own crouton from my source, or wait for the changes to be imported.
https://github.com/zguithues/crouton/tree/kodi

**Comment by zguithues** [comment]
one thing i noticed... when i was testing, it would bail out for kali & debian before creating the chroot & downloading the bootstrap.  but now it's downloading the whole thing before stopping.  I'm not sure what i did to change it, and i can't duplicate the quick bailout.

Any thoughts?  am i just crazy?
