### ISSUE TITLE
Xiwi launches window with everything small

### ISSUE THREAD

**Issue by ConProgramming** [dnschneid/crouton#3266]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: arm64
xmethod: xiwi
targets: xiwi
host: version 9334.72.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.44-07366-g24ac249 #1 SMP PREEMPT Wed May 17 18:11:20 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
When I open an individual app in its own window with xiwi (ex: xiwi terminator) all of the text in the app is incredibly small. I know this isn't limited to only terminator, however, because whether I open terminator, xterm, or gnome-tweak-tool the same thing happens. It also happened on an old (now deleted) chroot where xfce was installed.

#### If known, describe the steps to reproduce the issue:
Running any standalone app with xiwi (ex: xiwi terminator).

Does anyone know how to fix this? I've been researching the whole day, and haven't seen anything. If it helps, I'm on the Samsung Chromebook Plus.
 
**EDIT: On the Crouton Integration Extension I'm in HiDPI mode, but when I'm not in that mode everything is blurry**

**Comment by namethinger1234** [comment]
I did some poking and it says I apparently dont have a graphics driver for openGL acceleration
