### ISSUE TITLE
Installing program binaries to SD card while keeping chroot on SSD.

### ISSUE THREAD

**Issue by G3zz** [dnschneid/crouton#3270]
First of all, thanks for all your hard work making crouton - I can't imagine life without it!

I am currently running my chroot on my SSD, but I no longer have enough space to install new program binaries using `apt`.  An obvious solution is to simply move the whole chroot onto my SD card, but I would prefer to keep the chroot on the SSD and install program binaries onto my external SD card.  

I can't find any resources for this, so is this behaviour supported by crouton at the moment?  If not, how would I go about doing this?  One option seems to me to create a symlink in my chroot home directory to the SD card, add this folder to my `$PATH` and use `apt-get source` to install there, but I a no expert on this!

FYI, I am running trusty.

Thanks,
Geraint

**Comment by andersan** [comment]
Hey Geraint, 

I'm trying to do the same. This doesnt appear to be supported by crouton, but I imagine someone has done it successfully. I'm trying to use symlinks as well, creating a new link for each program within /usb/lib, but it gives me a permissions issue.

Have you gotten any further on this?

Best,
Chris
