### ISSUE TITLE
readlink should consistently use --

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#3271]
Some instances of readlink do not have the --...that is, it's `readlink -f "$param"` instead of `readlink -f -- "$param"`.

Should be fixed in case someone wants to poke at files with -'s at the start.

**Comment by jbaum98** [comment]
Should this be used even when the argument to `readlink` is a constant value? For example [here](https://github.com/dnschneid/crouton/blob/8eb0d8d068ad7b9696bd760410877e4033200a7f/host-bin/mount-chroot#L15) we have
```sh
ROOT="`readlink -m '/var/run/crouton'`"
```
We know that there are no -'s in the value, so there is no need for `--`, but for style/consistency should the `--` be added anyway?

**Comment by dnschneid** [comment]
No, no need to add it to anything that includes a fixed prefix (e.g., `"/var/run/crouton/$variable"` also doesn't need the --)
