### ISSUE TITLE
Precise install ARM Chromebook

### ISSUE THREAD

**Issue by steinbarge1** [dnschneid/crouton#3275]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

> name: precise
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/precise...
> crouton: version 1-20170315143304~master:95589555
> release: precise
> architecture: armhf
> xmethod: xorg
> targets: gnome
> host: version 9334.72.0 (Official Build) stable-channel veyron_speedy 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 17 17:44:10 PDT 2017 armv7l armv7l armv7l GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/precise...

#### Please describe your issue:
Downloaded Xenial today with a Gnome desktop environment, and running sudo startgnome returns the error "/usr/bin/xinit: Connection to X server lost

#### If known, describe the steps to reproduce the issue:
Run sudo startgnome on ARM Chromebook (ASUS C201PA)

**Comment by DennisLfromGA** [comment]
@steinbarge1,

The above output shows a 'precise' release, please show us the `croutonversion` output of your 'xenial' release.

-**DennisL**

**Comment by steinbarge1** [comment]
@DennisLfromGA That's what I meant, sorry. The precise release is the only one I have
I'm in the process of downloading the same release onto my brother's Samsung Chromebook with an Intel processor to find out if it's a processor issue or if it's something else

**Comment by steinbarge1** [comment]
Update: Download finished, tried running the entrance command again. Same error and yet Xenial with Unity works just fine on the same Samsung device. Should I try a different release?

**Comment by DennisLfromGA** [comment]
@steinbarge1,

> That's what I meant, sorry. The precise release is the only one I have

Okay, no problem.
The 'precise' release has reached End-Of-Life and is no longer supported, see [this wiki page](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release) for more info.

- [Upgrade chroot release](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release)

> I'm in the process of downloading the same release onto my brother's Samsung Chromebook with an Intel processor to find out if it's a processor issue or if it's something else

If you mean you're downloading the 'precise' release then don't bother, as I noted above, it's not supported in crouton or anywhere else.

`crouton` now defaults to the 'xenial' release so try it instead.

*Hope this helps,*
-**DennisL**

**Comment by steinbarge1** [comment]
@DennisLfromGA Ah, that makes sense. Well thanks for your help!

**Comment by DennisLfromGA** [comment]
@steinbarge1,

No problemmo, let us know how it goes. :+1: 

-**DennisL**
