### ISSUE TITLE
Crouton installed, but doesn't start

### ISSUE THREAD

**Issue by OsiRex1020** [dnschneid/crouton#3276]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
![screenshot 2017-06-15 at 7 42 34 pm](https://user-images.githubusercontent.com/29465303/27196582-e6f34c64-5202-11e7-8502-1f909689dff2.png)

#### Please describe your issue:
I've installed crouton, no qualms, but it won't open start when I input the command ; sudo startxfce4. Instead, I get this ;
![error message](https://user-images.githubusercontent.com/29465303/27196670-59d08c1a-5203-11e7-8d56-c2e86927f653.png)

**Comment by runner18** [comment]
I have had this same problem, and seems to be the same scenario for both kde and xcfe.
[BlnKgl has had a similair issue.](https://github.com/dnschneid/crouton/issues/3281l)
