### ISSUE TITLE
Unable to enter chroot

### ISSUE THREAD

**Issue by BlnKgl** [dnschneid/crouton#3281]
```
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

When I try to enter my chroot, the process stops with the following output:
```
chronos@localhost / $ sudo startxfce4
Enter encryption passphrase for trusty: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
ln: ‘/run/crouton/mnt/stateful_partition/crouton/chroots/trusty/media/removable’: cannot overwrite directory
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
ln: ‘/run/crouton/mnt/stateful_partition/crouton/chroots/trusty/media/removable’: cannot overwrite directory
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
I probably brought this upon myself, be changing permissions in the chroot of /media/removable (or making such a directory.)

(The reason that I was trying to change the permissions was because under "Devices" in the sidebar of Thunar any USB drives I plugged in appeared very briefly and then disappeared, although I was still able to see the drives at /media/removables and access the drives.)

Any help would be greatly appreciated. Thank you very much.  Kai Arste

**Comment by runner18** [comment]
I have had this same problem, and seems to be the same scenario for both kde and xcfe.

**Comment by BlnKgl** [comment]
The problem may be that the script to enter a chroot tries to make a
directory, and if the permissions have been changed so that it can't,
or a previous one could not be deleted when closing, then it fails.
And because the chroot is encrypted, we cannot get at it. (I think.)
Any suggestions? (Like having a modified script that does not make
that new directory, and knowing what the permissions on that directory
should be.)

Thanks.  Kai
