### ISSUE TITLE
I ran crouton without -r, can I run it again with -r?

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3282]
I was too fast, I followed the "easy" steps, but I want to be young and hip! Is it too late to do `-r`?

**Comment by DennisLfromGA** [comment]
@trusktr, 

Yup, it's too late baby, sorry. 
However, you can slay that monster using:

`sudo delete-chroot xenial`

-----
'crouton' defaults to the 'xenial' LTS release now, which is much younger & hippier than the older 'precise' release.  There are even younger & hippier ones out there, namely 'yakkety' & 'zesty' but, as denoted by the asterisk '*', they aren't supported yet, see below -

```
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch sid

Recognized kali releases:
    moto! kali! sana! kali-rolling

Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety* zesty*

Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```

*Hope this helps,*
-**DennisL**

**Comment by trusktr** [comment]
oh okay, cool. It would be easy anyways since all my stuff is in the home folder, then it's just a matter of reinstalling some packages with the new chroot.

Any plan for Arch Linux? Or would that introduce too much maintenance work for this project? Linode.com manages to somehow deploy Arch Linux distros in a custom way, maybe they have the money to keep someone constantly updating their scripts due to the ever-changing bleeding edge.

**Comment by DennisLfromGA** [comment]
@trusktr,

> Any plan for Arch Linux? Or would that introduce too much maintenance work for this project? 

The renowned Dr. Inkcat ( @drinkcat ) has a ['chroagh' branch](https://github.com/drinkcat/chroagh) but I don't think it's current:

- ['croagh+arch: Add support for Arch Linux.'](https://github.com/drinkcat/chroagh#chroagh)

*Hope this helps,*
-**DennisL**
