### ISSUE TITLE
[SOLVED] Unable to launch Gnome Terminal, Error constructing proxy for org.gnome.Terminal

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3283]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome
host: version 9334.72.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-14453-g2356e6e #1 SMP PREEMPT Wed May 17 18:05:37 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
I'm getting the same error as here: https://github.com/dnschneid/crouton/issues/1266#issuecomment-67756004

```
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Terminal exited with status 8
```

#### If known, describe the steps to reproduce the issue:

```
sudo sh ~/Downloads/crouton -t gnome
sudo startgnome
```

then run xterm, then

```
sudo apt-get install gnome-terminal
```

then try to open Gnome Terminal but the cursor hangs loading.

Then I try running `gnome-terminal` in xterm, and it gives that error

**Comment by trusktr** [comment]
Ah, oh well, startcli inside a crosh shell works nicely, I can paste into that. I was just having a hard time with the default xterm.

It might be nice to at least include a good terminal with the desktop targets. For example `gnome-terminal` with the `gnome` target, etc.

**Comment by trusktr** [comment]
Looks like the problem was with locales. I was able to fix it based on this comment: https://github.com/dnschneid/crouton/issues/2921#issuecomment-266349209

I was having trouble running `mongod` (in `meteor`) which depends on having locales set up, then I thought this would probably fix gnome-terminal too and it did.

Should locales be configured by default, or maybe run dpkg-reconfigure during target installs?

**Comment by DennisLfromGA** [comment]
@trusktr,

> Should locales be configured by default, or maybe run dpkg-reconfigure during target installs?

On 'debian' releases, it is configured in the '`core`' target which every chroot has, see the routine starting on [core#ln115](https://github.com/dnschneid/crouton/blob/master/targets/core#L115)

*Hope this helps,*
-**DennisL**

**Comment by trusktr** [comment]
Maybe that should be ran on more releases, like the default one which many people are likely to try, the "easy" way.

**Comment by DennisLfromGA** [comment]
@trusktr,

Maybe, perhaps running `dpkg-reconfigure locales` on more releases or even on all of them wouldn't harm anything and may just help to avoid this issue.

The devs can take a look at this maybe when they get a free cycle or two.

-**DennisL**

**Comment by trusktr** [comment]
I changed the title to better reflect this idea. Maybe you can re-open so it stays on the list?
