### ISSUE TITLE
Lack of color in the Crosh terminal, when using startcli

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3285]
When I'm in Crosh, and I enter the chroot terminals with `sudo startcli`, there's limited color. When I start vim, the text is all black/white.

However, in Gnome Terminal in Gnome Desktop, I have the full satisfying colors.

Is there some setting I have to set to enable color in the chroot running in crosh?

Note, if I install Vim or Neovim using Chromebrew so it runs natively in Chrome OS, it has full color, so crosh isn't limited, just something inside the chroot is limiting the color.

**Comment by trusktr** [comment]
I'd preferably like to stay in Chrome OS and do all dev in Chrome OS, and as I develop web apps I can see them in Chrome OS, and I'd like to switch to Gnome for the occasional "oh hey, I need to run Gimp real quick to edit an image"). 

This is nice because while Linux is turned off, Chrome OS is much much better (out of the box) at power management, whereas Linux kills the battery. The graphic acceleration in Linux isn't quite as smooth as in Chrome OS either.

So for now I'm going in Linux because the terminal has full color, but I think I'll just be back in `startcli` from ChromeOS once the color works there.

Oh, but wait, `startcli` also runs linux, so will that kill the battery too? If so, maybe I need Chromebrew as well, so I can install Vim, etc, and work in the native terminal, and then really just save Linux for those moments where I really need a Linux app.

**Comment by trusktr** [comment]
Ah, looks like running

```sh
TERM=xterm-256color nvim
```

makes NeoVim have full-color glory. It might be needed for other apps too?

**Comment by trusktr** [comment]
For what it's worth, the Chrome OS crosh shell reports `xterm` as the value for `TERM`. Maybe it's worth making the `startcli` target report the same thing?

**Comment by dnschneid** [comment]
Does xterm-256color work well for frecon too? (ctrl-alt-forward)

If so, then yeah, it might make sense to add this to the environment set up in `enter-chroot` (which startcli is just a wrapper for).

**Comment by trusktr** [comment]
It may not be the best approach to add a specific value of this env var
according to @ZyX-I <https://github.com/ZyX-I>, see his suggestion here
what problem it can make: https://github.com/neovim/neovim/issues/2334#
issuecomment-309641681

On Jun 19, 2017 9:59 PM, "David Schneider" <notifications@github.com> wrote:

Does xterm-256color work well for frecon too? (ctrl-alt-forward)

If so, then yeah, it might make sense to add this to the environment set up
in enter-chroot (which startcli is just a wrapper for).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dnschneid/crouton/issues/3285#issuecomment-309645106>,
or mute the thread
