### ISSUE TITLE
Accidentally deleted xbindkeys from Startup Applications in Gnome. Is it okay?

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3287]
Is that okay? I meant to delete the app I added, but not xbindkeys. Just want to double check if crouton replies on that, or if it is okay. I've no idea how to add it back (I don't know if it was running with any number of command line args).

**Comment by DennisLfromGA** [comment]
@trusktr,

I think a 'crouton' update should take care of it.
It's installed via the [x11-common](https://github.com/dnschneid/crouton/blob/master/targets/x11-common#L31) script and some custom configs are done in [xbindsrc.scm](https://github.com/dnschneid/crouton/blob/master/chroot-etc/xbindkeysrc.scm).

I have both gnome & kde desktop targets in my 'zesty' chroot so I'm not sure which one created this file but here are the contents of my `/etc/xdg/autostart/xbindkeys.desktop` file, if it helps:

```
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=xbindkeys
Comment=Start xbindkeys
Exec=xbindkeys_autostart
Terminal=false
Type=Application
Categories=
GenericName=
```

*Hope this helps,*
-**DennisL**
