### ISSUE TITLE
How to remove a target? (specifically keyboard target)

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3288]
The `keyboard` target completely conflicts with my xmodmap setting. Can I remove the keyboard target, as least for now.

I think it would be great to figure out how to [read Chrome OS settings and apply the Chrome OS modifier alterations in Linux](https://github.com/dnschneid/crouton/issues/3284), as when I apply them manually with an xmodmap configuration, it breaks the keyboard target so that there is no left control key.

**Comment by trusktr** [comment]
I saw this [other issue](https://github.com/dnschneid/crouton/issues/3249) makes it seem like targets are not designed to be removed.

I think it would be great to make that an easy thing to do, and that all targets should be removable/replaceable.

**Comment by chonkey821** [comment]
Yea idk why but my fullscreen key used to work before but the keyboard target remapped it to F11 and F11 doesn't exist! I only needed the target for brightness and volume keys...but i realized i can configure that through the xfce keyboard shortcuts settings..so basically i don't need that target anymore..did you find any ways yet to remove it manually maybe?

**Comment by DennisLfromGA** [comment]
@trusktr,

Yeah, unfortunately there currently is no built-in mechanism for removing crouton targets so I'd just suggest the method below:

> Remove the installed 'keyboard' target entries from crouton by editing both /.crouton-targets and /etc/crouton/targets files inside the chroot then do a crouton update.

*Hope this helps,*
-**DennisLfromGA**
