### ISSUE TITLE
Open web links in tabs in CromeOS from crouton

### ISSUE THREAD

**Issue by pierslawrence** [dnschneid/crouton#3290]
I am often switching back and forth between my xubuntu chroot (for real work) and ChromeOS for browsing. This is partly due to a continual memory issue (having 2GB of RAM is not fantastic), and running google chrome within the chroot makes this much worse.

Basically I would like to be able to click on a link in the chroot, and have this open a new tab in ChromeOS. Is this possible?

**Comment by dnschneid** [comment]
If you install the `extension` target, you can set `croutonurlhandler` as your default browser and it will automatically open links on the Chromium OS side.
