### ISSUE TITLE
Crouton installation "Failed to download debootstrap." error

### ISSUE THREAD

**Issue by Zuksod** [dnschneid/crouton#3292]
Hello people, I recently downloaded ubuntu, and it was working fine, until after logging out I couldn't log back in. So, I decided to powerwash my computer, (as I was facing storage issues) and re-install ubuntu. However, I keep running into this error! 
When I put in "sudo sh ~/Downloads/crouton -t unity" I get
**Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...
Download from Debian gitweb failed. Trying latest release...
https://sources.debian.net/api/src/debootstrap/:
2017-06-19 20:46:15 ERROR 500: Internal Server Error.
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.**

I am a noob to both this site and Ubuntu, and all this tech and command stuff, so I have no clue what to do. Also, please speak English, as I don't know what a _"crosh"_ even is...

Any assistance will be appreciated, thank you.

**Comment by mtree22** [comment]
I can confirm the same behavior for me. I have no proxy running, and internet connection is fine. I used a web browser to successfully access [ftp://ftp.debian.org](url)

I read some previous issues of simple typographical errors in the scripts pulling these ftp files, so may be a quick fix?!?!

Any help is appreciated. Thanks!

**Comment by dnschneid** [comment]
Okay, I've re-enabled gitweb downloading, so try crouton again.  @yuwash, are the debian APIs not reliable at the moment?

**Comment by mtree22** [comment]
Just ran command again. Same result.

**Comment by mtree22** [comment]
Just tried again; seems to be working.

**Comment by dnschneid** [comment]
Yeah, crouton only re-downloads the installer once every 30 minutes.  You can also force a re-download by removing the cache: `rm -rf /tmp/crouton-installer-cache`.

**Comment by Zuksod** [comment]
@dnschneid Thank you for the sorta-assistance, my dear sir.

**Comment by dnschneid** [comment]
Going to keep this open, awaiting @yuwash's insights.

**Comment by yuwash** [comment]
It seem to be working now, but I have no idea about any recent uptime issues of that api. To test, the following

```bash
d_api='https://sources.debian.net/api/src/debootstrap/'
f="$(wget -O- --no-verbose --timeout=60 -t2 "$d_api" | sed -ne 's ^.*\"version\":\ \"\([0-9.]*\)\".*$ debootstrap_\1.tar.gz p' | sort -V | tail -n 1)"
d='http://httpredir.debian.org/debian/pool/main/d/debootstrap/'
wget --no-verbose --timeout=60 -t2 "$d$f"
```

should result in

```
2017-06-21 20:11:00 URL:https://sources.debian.net/api/src/debootstrap/ [1354/1354] -> "-" [1]
2017-06-21 20:13:22 URL:http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.90.tar.gz [69936/69936] -> "debootstrap_1.0.90.tar.gz" [1]
```

**Comment by Knightlycat** [comment]
Same problem here, but I tried everything!

**Comment by brainsolutions-io** [comment]
Hi everyone,

At this moment I'm trying to install the gnome desktop environment through crouton.

Enter the following command in the terminal `sudo sh ~/Downloads/crouton -t gnome` ends up with the following ouput:

Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading debootstrap 1.0.101...
################################################################################################################################################ 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.

Apparently the requested debootstrap version is not present. It would be very appreciated if somebody could help me out on this.

Thanks in advance!

**Comment by troy0820** [comment]
I'm having the same problem as well.  I deleted the cache, but I'm receiving 404 errors when trying to install it.

**Comment by vitosans** [comment]
same here, leaving on a trip and wanted a small comp to take with me. Guess not.

**Comment by azzer1996** [comment]
I’ve tried...
Sudo sh ~/Downloads/crouton -t unity
(Xfce) (gnome) 

They all say failed to download debootstrap.
Check your internet connection or proxy settings and try again.

I am Using a acer chromebook and just want to install Ubuntu so I can play RuneScape through it.

Very new to this but I do know how to get into developer mode and download crouton to begin trying to download Ubuntu but don’t seem to be getting anywhere! It use to work before xfce and unity but now I can’t get any to install through crosh/shell ??

Be great if some one could help getting really annoyed lol... 👍🏻

**Comment by vitosans** [comment]
debootstrap is missing from the debian mirrors. I tried downloading it and passing in the -f option but thats not what -f is really used for.

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the problem.
You can do a quick test with something like the following: `crouton -r xenial -d -f xenial.bs`

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: `sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....`

-**DennisLfromGA**
