### ISSUE TITLE
sudo password not working within chroot (xfce)

### ISSUE THREAD

**Issue by mtree22** [dnschneid/crouton#3293]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9647.0.0 (Official Build) dev-channel gnawty 
kernel: Linux localhost 4.4.70-09727-g529640aa7e9b #1 SMP PREEMPT Tue Jun 13 03:03:33 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
I can successfully start xfce, and was able to use apt-get to install some programs within Ubuntu, but at some point my sudo password stops being accepted. This has happened twice now. The first time I deleted the chroot and started a completely new one. As you can see, I have not encrypted the chroot, so there really should only be one password that I'm working with...within the chroot, and used to give myself sudo access to xfce. Any help will be appreciated.

**Comment by DennisLfromGA** [comment]
@mtree22,

Not sure how that happened but I do know how to fix it.

Enter the chroot as root:
`sudo enter-chroot -n xenial -u root`

Change the 'username' password: 
`passwd [username]`

Substitute [username] with the one you originally created,
you'll be prompted to enter the password twice for verification.

Exit the chroot.

Now when you run any sudo commands in the chroot it will prompt for the 'username' password you just set.

Hope this helps,
-DennisL
