### ISSUE TITLE
ARM Chromebook - Crouton fails to complete installation if a single package fails

### ISSUE THREAD

**Issue by namp** [dnschneid/crouton#3295]
I've just run into the following issue trying to install crouton on my Samsung CB+ :

`chronos@localhost / $ sudo sh ~/Downloads/crouton -t xfce,core,cli-extra,chrome,audio,extension,touch -r trusty -p /media/removable/SD\ Card/ 
`

All goes well up to the point where I notice the message:

`Google Chrome does not yet have an ARM build. Installing Chromium instead.
`

which later on results to the following error: 

`Package chromium-browser is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or 
is only available from another source
However the following packages replace it:
  chromium-browser-l10n
E: Package 'chromium-browser' has no installation candidate
Failed to complete chroot setup.
Unmounting /media/removable/SD Card/chroots/trusty...
`

Seems that the whole installation fails if a single package fails to install. Any ideas how to overcome this?

Thanks

**Comment by DennisLfromGA** [comment]
@namp,

Thanx for flagging this.

As a workaround, I'd remove the `chrome` target from your installation command string and then attempt to add the [chromium browser](https://apps.ubuntu.com/cat/applications/chromium-browser/) in the chroot after the installation.

This will get you going and give the devs some time to figure out what's changed and how to fix it.

*Hope this helps,*
-**DennisL**

**Comment by namp** [comment]
Yes, it seems like the most sensible thing to do.

However issuing the command again without the chrome target and with -u does not work. The chroot has to be deleted and the installation to be started from scratch, otherwise the same error occurs.

Many thanks for the answer

**Comment by DennisLfromGA** [comment]
@namp,

That's because a crouton update ('-u'), uses the targets previously specified.

If you want to update it instead of installing a new one then you'd have to edit & remove the `chrome` target listed in your chroot in both `/.crouton-targets` & `/etc/crouton/targets`.

*Hope this helps,*
-**DennisL**

**Comment by namp** [comment]
Oh - I did not know that. Thanks!

Still, the problem remains as another package failed to install (lsb-release apparently) and the whole installation failed as well.
