### ISSUE TITLE
Xiwi with Mate?

### ISSUE THREAD

**Issue by juliocese** [dnschneid/crouton#3296]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: arm64
xmethod: xorg
targets: xiwi,xfce
host: version 9592.15.0 (Official Build) beta-channel elm 
kernel: Linux localhost 3.18.0-14852-gd99af821993c #1 SMP PREEMPT Fri Jun 9 02:45:17 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

UPDATE: I have since encrypted and now this (everything after is the same still)
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I am unable to use sudo startmate -x xiwi

I am using Mate via the instructions from:
https://medium.com/power-user/ubuntu-mate-on-a-chromebook-with-crouton-2cebd167382

If I just open the chroot with sudo startmate, the Chrouton integration extension shows a connection, but I can't do any xiwi-type stuff with it. I still have to control-shift-alt Back and Forth.

Any work-arounds? Heads up--I am the newbiest of newbs.

#### If known, describe the steps to reproduce the issue:
Check it out:

chronos@localhost / $ sudo startmate -x xiwi
Entering /mnt/stateful_partition/crouton/chroots/xenial...
chroot: failed to run command 'xiwi': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

chronos@localhost / $ sudo startmate -x xorg
Entering /mnt/stateful_partition/crouton/chroots/xenial...
chroot: failed to run command 'xorg': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by juliocese** [comment]
Also, I checked to see if xfce4 is still up. 
Sudo startxfce4 
Xfce4 starts right up. When I attempt -X xiwi or -X xorg, I received the same responses as my attempts with  startmate.

**Comment by DennisLfromGA** [comment]
@juliocese,

Just one minor tweak to your command: `sudo startmate`**`-X`**`xiwi`

Linux is case sensitive and the '**-X**' option needs to be uppercase.

*Hope this helps,*
-**DennisL**

**Comment by juliocese** [comment]
@DennisLfromGA 
Thanks. I gave it a shot. I get this message:
Entering /mnt/stateful_partition/crouton/chroots/xenial...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-59-generic aarch64 Ubuntu
Current Operating System: Linux localhost 3.18.0-14852-gd99af821993c #1 SMP PREEMPT Fri Jun 9 02:45:17 PDT 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=217c6955-3e43-7346-96cf-4d7b5ed03ee1/PARTNROFF=1 hashtree=PARTUUID=217c6955-3e43-7346-96cf-4d7b5ed03ee1/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=a4dafe62ed82b05f9d55b26765a001262f3d2cf1 salt=bd39f80a507f201029b93ae5b5891e7c5a5f7af8a654d6953fb7e92ec301a948" noinitrd vt.global_cursor_default=0 kern_guid=217c6955-3e43-7346-96cf-4d7b5ed03ee1  
Build Date: 26 January 2017  12:26:17AM
xorg-server 2:1.18.4-1ubuntu6.1~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Jun 25 23:08:55 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by juliocese** [comment]
Using the right case for an xorg chroot:

/mnt/stateful_partition/crouton/chroots/xenial does not contain XMETHOD 'xorg'

**Comment by DennisLfromGA** [comment]
@juliocese,

Your `croutonversion` output shows:

```
xmethod: xorg
targets: xiwi,xfce
```

That says that xmethod 'xorg' is the default but you added the 'xiwi' xmethod also.
Either xmethod should work, keep in mind with 'xiwi' you'll also need to install the ['crouton integration' extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom).

*Hope this helps,*
-**DennisL**

**Comment by juliocese** [comment]
Just did a clean install of xfce4 and xorg and xiwi work like a dream. Might give Mate another go later in the game.
