### ISSUE TITLE
samsung chromebook plus xe513c24 restarts when i use sudo startkde -n zesty or sudo startkde (xenial)

### ISSUE THREAD

**Issue by rustinpieces** [dnschneid/crouton#3297]
```
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: arm64
xmethod: xorg
targets: kde
host: version 9460.60.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 16:59:00 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
name: zesty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/zesty...
crouton: version 1-20170619181610~master:980f090f
release: zesty
architecture: arm64
xmethod: xorg
targets: kde
host: version 9460.60.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 16:59:00 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/zesty...
```
output from sudo cat /dev/pstore/console-ramoops :  
zesty: https://pastebin.com/vqhaUdKq
xenial: https://pastebin.com/P3qbK01J

**Comment by rustinpieces** [comment]
I tried installing debian (sid) with kde, when I run it I get this:
`chronos@localhost / $ sudo startkde -n sid
Entering /mnt/stateful_partition/crouton/chroots/sid...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-arm64 aarch64 Debian
Current Operating System: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 16:59:00 PDT 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=a769d5a1-b39d-b24d-9717-737c4f9c398f/PARTNROFF=1 hashtree=PARTUUID=a769d5a1-b39d-b24d-9717-737c4f9c398f/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=9005d7ee3373d08420125894c7b06aa1a5e59e77 salt=b60f6e72f02b2e6303c0415dda350bd50c71fbaed40c931fa847cbcdb584b226" noinitrd vt.global_cursor_default=0 kern_guid=a769d5a1-b39d-b24d-9717-737c4f9c398f  
Build Date: 15 March 2017  09:22:01PM
xorg-server 2:1.19.3-1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jun 26 16:44:19 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/sid...
chronos@localhost / $ chronos@localhost / $ sudo startkde -n sid
bash: chronos@localhost: command not found
chronos@localhost / $ Entering /mnt/stateful_partition/crouton/chroots/sid...
bash: Entering: command not found
chronos@localhost / $ 
chronos@localhost / $ _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
bash: _XSERVTransmkdir:: command not found
chronos@localhost / $ 
chronos@localhost / $ X.Org X Server 1.19.3
bash: X.Org: command not found
chronos@localhost / $ Release Date: 2017-03-15
bash: Release: command not found
chronos@localhost / $ X Protocol Version 11, Revision 0
bash: X: command not found
chronos@localhost / $ Build Operating System: Linux 3.16.0-4-arm64 aarch64 Debian
bash: Build: command not found
chronos@localhost / $ Current Operating System: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 16:59:00 PDT 2017 aarch64
bash: Current: command not found
chronos@localhost / $ Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=a769d5a1-b39d-b24d-9717-737c4f9c398f/PARTNROFF=1 hashtree=PARTUUID=a769d5a1-b39d-b24d-9717-737c4f9c398f/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=9005d7ee3373d08420125894c7b06aa1a5e59e77 salt=b60f6e72f02b2e6303c0415dda350bd50c71fbaed40c931fa847cbcdb584b226" noinitrd vt.global_cursor_default=0 kern_guid=a769d5a1-b39d-b24d-9717-737c4f9c398f  
bash: Kernel: command not found
chronos@localhost / $ Build Date: 15 March 2017  09:22:01PM
bash: Build: command not found
chronos@localhost / $ xorg-server 2:1.19.3-1 (https://www.debian.org/support) 
bash: syntax error near unexpected token `('
chronos@localhost / $ Current version of pixman: 0.34.0
bash: Current: command not found
chronos@localhost / $         Before reporting problems, check http://wiki.x.org
bash: Before: command not found
chronos@localhost / $         to make sure that you have the latest version.
bash: to: command not found
chronos@localhost / $ Markers: (--) probed, (**) from config file, (==) default setting,
bash: syntax error near unexpected token `--'
chronos@localhost / $         (++) from command line, (!!) notice, (II) informational,
        (++) from command line, (Markers: (--) probed, (**) from config file, (==) default setting,) notice, (II) informational,
bash: syntax error near unexpected token `from'
chronos@localhost / $         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
bash: syntax error near unexpected token `warning,'
chronos@localhost / $ (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Jun 26 16:44:19 2017
bash: syntax error near unexpected token `Log'
chronos@localhost / $ (==) Using system config directory "/usr/share/X11/xorg.conf.d"
bash: syntax error near unexpected token `Using'
chronos@localhost / $ (EE) 
bash: EE: command not found
chronos@localhost / $ Fatal server error:
bash: Fatal: command not found
chronos@localhost / $ (EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
bash: syntax error near unexpected token `parse_vt_settings:'
chronos@localhost / $ (EE) 
bash: EE: command not found
chronos@localhost / $ (EE) 
bash: EE: command not found
chronos@localhost / $ Please consult the The X.Org Foundation support 
bash: Please: command not found
chronos@localhost / $          at http://wiki.x.org
bash: at: command not found
chronos@localhost / $  for help. 
> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
bash: syntax error near unexpected token `('
chronos@localhost / $ (EE) 
bash: EE: command not found
chronos@localhost / $ (EE) Server terminated with error (1). Closing log file.
bash: syntax error near unexpected token `Server'
chronos@localhost / $ /usr/bin/xinit: giving up
bash: /usr/bin/xinit:: No such file or directory
chronos@localhost / $ /usr/bin/xinit: unable to connect to X server: Connection refused
bash: /usr/bin/xinit:: No such file or directory
chronos@localhost / $ /usr/bin/xinit: server error
bash: /usr/bin/xinit:: No such file or directory
chronos@localhost / $ Unmounting /mnt/stateful_partition/crouton/chroots/sid...
chronos@localhost / $ `

**Comment by rustinpieces** [comment]
chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=23
CHROMEOS_ARC_VERSION=4059099
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_RELEASE_BOARD=kevin-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=60
CHROMEOS_RELEASE_BUILDER_PATH=kevin-release/R59-9460.60.0
CHROMEOS_RELEASE_BUILD_NUMBER=9460
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=59
CHROMEOS_RELEASE_DESCRIPTION=9460.60.0 (Official Build) stable-channel kevin 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9460.60.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9460.60.0

**Comment by DennisLfromGA** [comment]
@rustinpieces,

You might try adding the 'xiwi' xmethod/target with a crouton update and see if it works.

*Hope this helps,*
-**DennisL**

**Comment by rustinpieces** [comment]
I tried xiwi earlier, it also does not work.  I deleted my zesty chroot with xiwi on it, but my xenial has xiwi target.  this is what happens:  https://pastebin.com/zfu8CFH7   

When I tried zesty xiwi, it would not connect to extension, even though extension is installed.

**Comment by rustinpieces** [comment]
I got xiwi to work with zesty using sudo startkde -X xiwi with these targets:  (xorg still does not work, also I can't get rid of chromebook icons on bottom of screen, even in fullscreen)
crosh> shell
chronos@localhost / $ sudo edit-chroot -al
Password: 
name: zesty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/zesty...
crouton: version 1-20170619181610~master:980f090f
release: zesty
architecture: arm64
xmethod: xorg
targets: kde-desktop,core,audio,xorg,xiwi,keyboard,extension
host: version 9460.60.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 16:59:00 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/zesty as another instance is using it.
