### ISSUE TITLE
AddScreen/ScreenInit failed for driver 1

### ISSUE THREAD

**Issue by kamnida1992** [dnschneid/crouton#3299]
(xenial)kamnida@localhost:~$ sudo startxfce4
[sudo] password for kamnida: 
Do not launch startxfce4 as root inside the chroot.
(xenial)kamnida@localhost:~$ sudo startx    

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-59-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Jun 20 22:56:11 PDT 2017 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=70decbf0-1469-4f4f-9dd8-534a720e41ed/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 2539520 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2539520 alg=sha1 root_hexdigest=fa73b006d69c3bc52ce0d0e87660fae3d933bcc6 salt=3a0f75bb764b091fcd4f01017f9dca289e8c603d31a937cea31c15925a38145a" noinitrd vt.global_cursor_default=0 kern_guid=70decbf0-1469-4f4f-9dd8-534a720e41ed  
Build Date: 26 January 2017  12:27:19AM
xorg-server 2:1.18.4-1ubuntu6.1~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Jun 28 01:22:25 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org

My Chromebook is SAMSUNG Xe303c12 Chromebook.. 

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9592.29.0 (Official Build) beta-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jun 20 22:56:11 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

What i gonna do ?

**Comment by NoPenSource** [comment]
Here you go #3291 
Second Post
