### ISSUE TITLE
kali-rolling fails to start on new install

### ISSUE THREAD

**Issue by Lite5h4dow** [dnschneid/crouton#3301]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170619181610~master:980f090f
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 56.3.82 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Fri Apr 7 04:10:21 UTC 2017 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 56.3.82 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Fri Apr 7 04:10:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/xenial


```
I just installed crouton on my custom chromebook, however after installing xfce i wanted something a little more so i installed Kali, (kali-rolling) now im having an error that i dont know how to solve, since im still pretty new to this. any help would be greatly appreciated.

error log =
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170619181610~master:980f090f
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 56.3.82 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Fri Apr 7 04:10:21 UTC 2017 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 56.3.82 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Fri Apr 7 04:10:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by Lite5h4dow** [comment]
And another question, how do I encrypt this version of Kali in croutons?

**Comment by DennisLfromGA** [comment]
@Lite5h4dow,

> host: version 56.3.82 (Developer Build - neverware) developer-build chromeover64

What device are you using?

Maybe try installing and using the 'xiwi' xmethiod on this chroot too.

-----
> And another question, how do I encrypt this version of Kali in croutons?

You can encrypt an existing chroot using the '-e' option with an update, like: 

`sudo sh ~/Downloads/crouton -n kali-rolling -e -u`

*Hope this helps,*
-**DennisL**

**Comment by Lite5h4dow** [comment]
@DennisLfromGA I'm using an HP pavilion x360 2016 Intel i5

**Comment by Lite5h4dow** [comment]
@DennisLfromGA  that hasent seemed to have worked, i dont have  different results from the previous post. same error.

**Comment by Lite5h4dow** [comment]
just reinstalled now im getting
`chronos@localhost / $ sudo startxfce4 -n kali-rolling -X xiwi
/mnt/stateful_partition/crouton/chroots/kali-rolling does not contain XMETHOD 'xiwi'`

**Comment by DennisLfromGA** [comment]
@Lite5h4dow,

Did you add 'xiwi' first using: `sudo sh ~/Downloads/crouton -n kali-rolling -t xiwi -u` ?

-**DennisL**

**Comment by Lite5h4dow** [comment]
i didnt know i had to, it wasnt a step on the wiki, let me do that now.

**Comment by DennisLfromGA** [comment]
@Lite5h4dow,

*Good job!*

'xiwi' is an xmethod but it can be added as a target using the '-t' option.
Check out this wiki article for more about it: [crouton in a Chromium OS window (xiwi)](https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi))

*Hope this helps,*
-**DennisL**

**Comment by Lite5h4dow** [comment]
@DennisLfromGA gotcha, im so bad at this, i still bearly understand the crouton commands, and all the readme's and wiki make bearly any sense to a n00b like me

**Comment by DennisLfromGA** [comment]
It takes time grasshopper; I've been at it a while and I still only scratch the surface. ;)
