### ISSUE TITLE
sh: cant open crouton

### ISSUE THREAD

**Issue by brno2** [dnschneid/crouton#3305]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
command not found

**Comment by divx118** [comment]
try `sudo sh ~/Downloads/crouton` Note the capital "D". Folder,file names are case sensitive on linux/chromeos.   
`-e` is not needed anymore, but doesn't let the command fail when you use it.

**Comment by brno2** [comment]
Same issue. Any other ideas?

**Comment by divx118** [comment]
Did you download [crouton](https://goo.gl/fd3zc)? So it is in your Dowloads folder.
To check if crouton is there you can use `ls -al ~/Downloads/crouton` it should give you:
```
chronos@localhost / $ ls -al ~/Downloads/crouton
-rw-r--r--. 1 chronos chronos 3653 Mar 19 08:59 /home/chronos/user/Downloads/crouton
```

**Comment by brno2** [comment]
It says: "ls: cannot access /home/chronos/user/Dowloads/crouton: No such file or directory" What does this mean?

**Comment by divx118** [comment]
Well that you need to download it first here --> https://goo.gl/fd3zc . After you have downloaded it, it is recommended to also read https://github.com/dnschneid/crouton/blob/master/README.md

**Comment by DennisLfromGA** [comment]
To add, it should be '/Do**w**nloads' not '/Dowloads', your missing an 'n'.

**Comment by divx118** [comment]
@DennisLfromGA 👍 Ah you are right. missed that.

**Comment by brno2** [comment]
It is definitely in my downloads folder. I really don't understand what is wrong with it. Do you guys have any other ideas?

**Comment by divx118** [comment]
@brno2 What does `ls -al ~/Downloads/crouton` say then?
If it say `No such file or directory` then a file named `crouton is not in your `Downloads` folder or has the wrong name, maybe a space behind it so you don't notice. Solution delete the file and download again.

**Comment by brno2** [comment]
thank you
