### ISSUE TITLE
Cannot Enter chroot

### ISSUE THREAD

**Issue by brianazick** [dnschneid/crouton#3306]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170617004221~master:8d470f1b
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9693.1.0 (Official Build) dev-channel swanky 
kernel: Linux localhost 4.4.70-10450-gcfafb2bfd34c #1 SMP PREEMPT Thu Jun 29 01:50:56 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
When I start by chroot by typing `sudo startxfce4` a few lines of output show up and I can briefly see what I think is an error message when the screen on my chromebook goes to black. Once the screen is black I cannot return to Chromium OS with the `SHIFT+CTRL+ALT+Forward` key combination. This issue did not occur prior to Saturday July 1st and I believe there was a Chromium OS update installed on Friday June 30th, which may have caused this behavior.

#### If known, describe the steps to reproduce the issue:
I have not tried to replicate the issue with another chroot.

**Comment by DennisLfromGA** [comment]
@brianazick,

There are [several open black screen issues](https://github.com/dnschneid/crouton/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20black%20screen).
Take a look at this thread for a possible workaround: [Linux will not start after installing...](https://github.com/dnschneid/crouton/issues/3291)

*Hope this helps,*
-**DennisL**

**Comment by brianazick** [comment]
The instructions there were very helpful. Thank you so much!
