### ISSUE TITLE
Samsung Chromebook Plus crashes and reboots every time I use the command "sudo startxfce4"

### ISSUE THREAD

**Issue by kpalian** [dnschneid/crouton#3309]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: arm64
xmethod: xorg
targets: gtk-extra,touch,extension,keyboard,xfce
host: version 9592.37.0 (Official Build) beta-channel kevin 
kernel: Linux localhost 4.4.64-09086-gaace1482168b #1 SMP PREEMPT Tue Jun 27 23:26:16 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

**Comment by erhbirol** [comment]
hello everyone, i have this issue too, today i upgraded my chromeos, and i can do "sudo enter-chroot -n xenial" from terminal but i can't start X, i mean im giving sudo startxfce4 but blackscreen is comming and then chromebook(samsung chromebookplus) is rebooting. Please help me, i like my ubuntu on chromebook.

**Comment by DennisLfromGA** [comment]
DUP - Take a look at this issue for a workaround: https://github.com/dnschneid/crouton/issues/3234

*Hope this helps,*
-**DennisL**

**Comment by timozel** [comment]
I am also experiencing the exact same issue with my Samsung Plus. Run 'sudo startxfce4' then it goes to black screen and ultimately restarts the Chromebook.
