### ISSUE TITLE
ALSA woes.... PERMISSION DENIED

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#3312]
Tried to open Guitar Pro 6 program

Unless I run with sudo first I get this error.
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied

what does this mean? can I simply add permission to the  normal user somehow?

**Comment by DennisLfromGA** [comment]
@Carl393,

Please show us the output of the following two commands:

- `sudo enter-chroot croutonversion`
- `sudo enter-chroot groups`

-**DennisL**
