### ISSUE TITLE
Installation hangs up at "I: Retrieving InRelease" step.

### ISSUE THREAD

**Issue by magnetholik** [dnschneid/crouton#3314]
#### Please describe your issue:
I have been trying to install Ubuntu on my Acer Chromebook according to the instructions given on the main page. I have looked at all the other threads where people have similar issues, but I cannot seem to figure out what's going wrong. I have tried a lot of things, but nothing seems to work. It always seems to become unresponsive when reaching the "I: Retrieving InRelease" step. I will produce what it looks like in the shell.

> chronos@localhost / $ sudo sh ~/Downloads/crouton -r xenial -t xfce 
> /usr/local/chroots/xenial already has stuff in it! Either delete it, specify a different name (-n), or specify -u to update it. 
> chronos@localhost / $ sudo sh ~/Downloads/crouton -n other -r xenial -t xfce 
> Installing xenial-amd64 chroot to /usr/local/chroots/other 
> Downloading latest debootstrap... 
> Unable to establish SSL connection. 
> Download from Debian gitweb failed. 
> Trying latest release... 
> Unable to establish SSL connection. 
> Failed to download debootstrap. 
> Check your internet connection or proxy settings and try again. 
> chronos@localhost / $ sudo sh ~/Downloads/crouton -n other -r xenial -t xfce 
> Installing xenial-amd64 chroot to /usr/local/chroots/other 
> Downloading latest debootstrap... 
> Read error (Connection timed out) in headers. 
> Unable to establish SSL connection. 
> Download from Debian gitweb failed. 
> Trying latest release... 2017-07-10 00:20:50 URL:https://sources.debian.net/api/src/debootstrap/ [1486/1486] -> "-" [2] Downloading debootstrap version 1.0.90... 
> 2017-07-10 00:20:51 URL:http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.90.tar.gz [69936/69936] -> "-" [1] Patching debootstrap... 
> Downloading bootstrap files... 
> W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg 
> I: Retrieving InRelease

Just for the record, there are no problems with my internet, and I am not using a proxy.

**Comment by divx118** [comment]
@magnetholik Could be that the sources are down or not accessible for some time. It happened to me a couple of times. I would try it again at a later time.

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the debootstrap problem.
You can do a quick test with something like the following: crouton -r xenial -d -f xenial.bs

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....

Please re-open this issue if it's not fixed and give us some more details.

-DennisLfromGA
