### ISSUE TITLE
Password prompt when trying to reenter Chroot after reboot

### ISSUE THREAD

**Issue by Cnidarias** [dnschneid/crouton#3316]
```
chronos@localhost ~ $ sudo /media/removable/sd/bin/edit-chroot -all
name: xenial
encrypted: no
Entering /media/removable/sd/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 9460.67.0 (Official Build) stable-channel squawks 
kernel: Linux localhost 4.4.52-08264-gaa3473cb9b04 #1 SMP PREEMPT Thu Jun 22 14:37:29 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Unmounting /media/removable/sd/chroots/xenial...
```
After installing crouton to the SD-card (as seen above /media/removable/sd) I was able to start the xfce4 enviornment just as per usual.
After logging out of the environment and reopening xfce4 it still works as expected BUT 

After restarting the chromebook and attempting to start xfce4 again I get a password prompt.
I get the same password prompt when only trying to enter the chroot:

```
chronos@localhost / $ sudo sh /media/removable/sd/bin/enter-chroot 
Entering /media/removable/sd/chroots/xenial...
Password: 
```

Now it does not matter what password I enter it will not get accepted and there should not be a password prompt to begin with!
 
I tried:
```sudo chromeos-setdevpasswd```

which had no effect and when I just want to enter sudo su I get no problems either:

```
chronos@localhost / $ sudo su
localhost / # 

````

Interesting is also the mounting point of the SD-card when checking (device in question is on the last line):

```
chronos@localhost / $ lsblk
lsblk: dm-0: failed to get device path
lsblk: dm-0: failed to get device path
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0           7:0    0   7.3G  0 loop 
└─encstateful 253:1    0   7.3G  0 dm   /mnt/stateful_partition/encrypted
loop1           7:1    0 469.7M  1 loop /opt/google/containers/android/rootfs/ro
loop2           7:2    0  48.2M  1 loop /opt/google/containers/android/rootfs/ro
loop3           7:3    0     4K  1 loop /opt/google/containers/arc-removable-med
loop4           7:4    0     4K  1 loop /opt/google/containers/arc-sdcard/mountp
loop5           7:5    0     4K  1 loop /opt/google/containers/arc-obb-mounter/m
zram0         252:0    0   5.5G  0 disk [SWAP]
mmcblk0rpmb   179:48   0     4M  0 disk 
mmcblk0boot0  179:16   0     4M  1 disk 
mmcblk0boot1  179:32   0     4M  1 disk 
mmcblk0       179:0    0  29.1G  0 disk 
├─mmcblk0p1   179:1    0    25G  0 part /mnt/stateful_partition
├─mmcblk0p2   179:2    0    16M  0 part 
├─mmcblk0p3   179:3    0     2G  0 part 
├─mmcblk0p4   179:4         16M  0 part 
├─mmcblk0p5   179:5          2G  0 part 
├─mmcblk0p6   179:6        512B  0 part 
├─mmcblk0p7   179:7        512B  0 part 
├─mmcblk0p8   179:8         16M  0 part /usr/share/oem
├─mmcblk0p9   179:9        512B  0 part 
├─mmcblk0p10  179:10       512B  0 part 
├─mmcblk0p11  179:11         8M  0 part 
└─mmcblk0p12  179:12        16M  0 part 
mmcblk1       179:64   0  59.5G  0 disk /media/removable/sd/chroots/xenial/var/h
```
When trying to umount now it only tells me the device is busy.
When running ```sudo umount -l /dev/mmcblk1``` the command runs through but 
when running lsblk again I get the same results!

As for reproduction hard to say:

I power washed my chromebook - did NOT enable debugging features - 
Downloaded crouton
unmounted the SD-card: 
```sudo umount /dev/mmcblk1```
formated it using mkfs.ext4 
```sudo mkfs.ext4 -L "sd" /dev/mmcblk1```
mounted SD-card again
```sudo mount /dev/mmblk1 /media/removable/sd```
installed crouton using: 
```sudo sh -e ~/Downloads/crouton -r xenial -t xiwi,xfce -p /media/removable/sd```

Entered the chroot after wards with: ```sudo sh /media/removable/sd/bin/startxfce4```

Left the xfce4 using logout.
Waited for the chroot to shutdown completely and then restarted my chromebook!

Have verified that the problem persists when using trusty instead of xenial.

Regards

**Comment by DennisLfromGA** [comment]
@Cnidarias,

If you've enabled debugging features see if this comment helps: https://github.com/dnschneid/crouton/issues/825#issuecomment-280964330

*Hope this helps,*
-**DennisL**
