### ISSUE TITLE
crouton must be run as a root

### ISSUE THREAD

**Issue by hylkevdveen** [dnschneid/crouton#3319]
I have deleted a chroot, now I want to install a new one. I enter the exact same code I did before, and get this message:
![crouton must be run as a root](https://user-images.githubusercontent.com/30147000/28163453-7edf0fee-67cb-11e7-9df0-e099bf655525.png)
Does anyone know if, or where I screwed up? And how can I make crouton run as a root? 

Thanks in advance.

Edit: 

Before that line of code I wrote this line, does it have anything to do with it?
![screenshot 2017-07-13 at 13 05 53](https://user-images.githubusercontent.com/30147000/28163569-0b81b2a8-67cc-11e7-97bd-b6c0c0bb4974.png)

**Comment by DennisLfromGA** [comment]
@hylkevdveen,

> I enter the exact same code I did before, and get this message:

> Before that line of code I wrote this line, does it have anything to do with it?

Maybe not quite the *exact* same code, you're missing the '**sudo**' prefix -

**`sudo`**`sh ~/Downloads/crouton -t kde`

*Hope this helps,*
-**DennisL**
