### ISSUE TITLE
No display configuration in kde

### ISSUE THREAD

**Issue by l8rb8r** [dnschneid/crouton#3321]
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170619181610~master:980f090f
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,kde,extension
host: version 9460.60.0 (Official Build) stable-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Jun 5 17:01:17 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Hello.  I'm having a silly issue with not being able to change my display resolution in the kde desktop.  There is no "display configuration" tab in the "display and monitor" section of "system settings".  I'm assuming that it's an issue that should be addressed here, rather than a general kde problem as I have found no help for this particular problem elsewhere.  Or am I just missing a package?

**Comment by l8rb8r** [comment]
Never mind, it was a silly issue.  I didn't have the kscreen package installed.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
