### ISSUE TITLE
OpenGL 3d acceleration fails on Chromebook Pro

### ISSUE THREAD

**Issue by sanicki** [dnschneid/crouton#3322]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,extension,touch,audio,keyboard
host: version 9334.72.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-14453-g2356e6e #1 SMP PREEMPT Wed May 17 18:05:37 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Following [this guide](https://help.ubuntu.com/community/WorldofWarcraft#Enabling_OpenGL) to install World of Warcraft. Works (poorly) using Direct3D by default. Fails to start with the following message when `SET gxApi "opengl"` is added to `config.wtf`:
![screenshot 2017-07-13 at 3 27 26 pm](https://user-images.githubusercontent.com/6764844/28188633-1dc01982-67e0-11e7-9525-d1030990ceba.png)

#### If known, describe the steps to reproduce the issue:
Add `SET gxApi "opengl"` is added to WoW's `config.wtf`.

**Comment by sanicki** [comment]
Nevermind. Switched to X11 and it runs like butter.

**Comment by DennisLfromGA** [comment]
@sanicki,

Thanx for reporting back with your resolution, it may help others.

-**DennisL**
