### ISSUE TITLE
Mount SD card from Crouton chroot?

### ISSUE THREAD

**Issue by nicolas161** [dnschneid/crouton#3323]
I have set up my chroot to start automatically before logging in Chrome OS following this guide: https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup

It works flawlessly, but the problem is that I cannot open any SD Card or USB stick. When I try to mount them, I get a "permission denied" message. That happens -I guess- because, without having logged in, Chrome OS hasn't mounted all the inserted devices automatically.

Is there any way in which I could mount my SD Card -or any other inserted device- from the chroot?

Thank you.

**Comment by DennisLfromGA** [comment]
@nicolas161,

> Is there any way in which I could mount my SD Card -or any other inserted device- from the chroot?

Not sure, you could try adding the mount command to the `/etc/rc.local` file and see if that works.
If you start your chroot before you're logged in, it will probably limit your options though.

See this slightly similar and yet unresolved issue for a little more info. -

- Autostart chroot from sd-card #3230

*Hope this helps,*
-**DennisL**
