### ISSUE TITLE
[Image request] alpine

### ISSUE THREAD

**Issue by japrogramer** [dnschneid/crouton#3324]
Is there any way that alpine could be added as a supported image?

**Comment by boydkelly** [comment]
Although xiwi and some stuff (like xiwi) doesn't work.....  I just tared up an lxc chroot of alpine and copied it to my chromebook.   I had to fix a few things but I can enter-chroot to the instance just fine.  I have also run fluxbox and vncserver and I can use the chrome vnc server app to connect to it.

**Comment by mgrechukh** [comment]
Hi,

Here goes basic implementation of how to build crouton-ready images from Alpine in docker

https://github.com/mgrechukh/alpine-croutons

Somewhere with access to docker:
./build.sh
scp out/alpine_croutons.tar.gz mychromebook:Downloads/

On crosh:

sudo sh -x crouton -n vpns -f alpine_croutons.tar.gz 
sudo enter-chroot -u 0 -n vpns /bin/sh

Final image is about ~30Mb. Enjoy, hope it will be useful.

(I plan to remove layer of tinc & ipsec installation from image and better try to reimplement  'alpine-core' and 'alpine-tinc', 'alpine-ipsec', etc. targets on crouton itself. Core image should be really slick in this case)
