### ISSUE TITLE
Is it possible to stop a chroot install and start it again?

### ISSUE THREAD

**Issue by Astrades** [dnschneid/crouton#3326]
Hey guys. So, I was wondering if it was possible to resume install of a chroot after cancelling the operation. My install command was:
`sudo sh ~/Downloads/crouton -r xenial -n stuff -t x11` 
and it was taking a very long time, so I cancelled the install. Would I use the update command, another command I have no clue about, or do I have to install it freshly? Thanks for reading.

**Comment by Astrades** [comment]
**UPDATE** 
I'm trying the -u command and it seems to be working.

**Comment by DennisLfromGA** [comment]
@Astrades,

Seems you found your answer.
Usually, an update will work if it's far enough along.

-**DennisL**
