### ISSUE TITLE
White noise instead of sound on some online videos with Firefox

### ISSUE THREAD

**Issue by nicolas161** [dnschneid/crouton#3328]
When playing videos with Firefox, instead of the normal sound of the video I get a burst of white noise. The sound of some videos works, some don't. This one works perfectly: https://www.youtube.com/watch?v=sbBW7H6edgQ   This one doesn't: http://www.sensacine.com/noticias/series/noticia-18558322/

I have installed the pepperflash plugin with no results.

I was wondering if any of you had the same problem, and if so, how did you make it work?

Thank you.

**Comment by Pogo555** [comment]
I have had the same problem with audio from a camera. I' sure that it is a codec problem. Choosing a different codec sometimes gets the sound working, but it is hit and miss.
