### ISSUE TITLE
Questions on encryption and ~/Downloads

### ISSUE THREAD

**Issue by prairiedock** [dnschneid/crouton#3329]
Despite the extensive documentation and discussion of developer mode and crouton available on the web, I've been unable to find answers anywhere to some elementary questions about encryption and security. (I have read the wiki article on crouton security.) I've surrounded these questions with some declarative statements (marked by *) for context that reflect my current understanding; if some of these statements are false, I'd be grateful for any correction.

*When not in developer mode, Chrome OS encrypts the Downloads directory, where my local data resides. This data is transparently decrypted whenever I access it after signing in. The data is thereby protected by my Google password.

(1) After entering developer mode (which wipes Downloads), are all files later placed in Downloads, using (say) the Files App, NOT encrypted?

*Since the Downloads directory is shared (via symlinks) with the crosh shell and also with any (unencrypted) crouton chroots, a yes answer to (1) should mean no encryption for the ~/Downloads directory under these applications either.

(2) After establishing an encrypted crouton chroot, is the ~/Downloads directory now encrypted too? It is part of the chroot after all. (But how could it be encrypted? Downloads has to be accessible by the ordinary Chrome OS side of things too, and how would that side know about the crouton encryption?)

Semi-rhetorical question: if Downloads is NOT encrypted, what good are encrypted chroots really? All the local data I really care about protecting on my Chromebook resides in Downloads.

(3) if Downloads is not encrypted, couldn't I establish in the chroot a folder, ~/private say, which WOULD therefore be encrypted, and store sensitive data there? Of course, ~/private wouldn't be directly accessible to the Chrome OS side, but I could "cp" data temporarily from there to Downloads as needed...

**Comment by dnschneid** [comment]
> (1) After entering developer mode (which wipes Downloads), are all files later placed in Downloads, using (say) the Files App, NOT encrypted?

All files in your user profile are still encrypted in dev mode, including the downloads folder.  When you log in on Chromium OS, the encrypted section is accessible in its decrypted form to a select set of processes.  In dev mode, you can access the decrypted form from a root shell, which is wide-open on VT2 if you don't set a root password.  When you log out, the decryption mountpoint is removed and your profile returns to being inaccessible, even with VT2.

> (2) After establishing an encrypted crouton chroot, is the ~/Downloads directory now encrypted too? It is part of the chroot after all. (But how could it be encrypted? Downloads has to be accessible by the ordinary Chrome OS side of things too, and how would that side know about the crouton encryption?)

Downloads is not part of the chroot; it is a bind-mount of the user's Downloads folder.  It is only accessible when you are logged in, and encrypted with your profile when you are not.

> Semi-rhetorical question: if Downloads is NOT encrypted, what good are encrypted chroots really? All the local data I really care about protecting on my Chromebook resides in Downloads.

It helps prevent tampering, and also makes crouton enforce good hygiene such as ensuring there's a root password set in Chromium OS.

> (3) if Downloads is not encrypted, couldn't I establish in the chroot a folder, ~/private say, which WOULD therefore be encrypted, and store sensitive data there? Of course, ~/private wouldn't be directly accessible to the Chrome OS side, but I could "cp" data temporarily from there to Downloads as needed...

~/private would be managed in the same way that Downloads is (they're both just directories inside of your encrypted user profile).  In fact, if you add an "encrypted" entry to the [crouton shares file](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders), crouton will create a directory in ~/crouton/ for you.

**Comment by prairiedock** [comment]
Thanks for the rapid response!

>All files in your user profile are still encrypted in dev mode, including the downloads folder.

This really should be in the documentation, probably in the Security article. It is great news to me. (I don't remember where I picked up the erroneous idea that profile encryption was disabled in developer mode, but it's out there somewhere.)

This encryption renders my other questions moot, but thanks for the elaboration anyway.
