### ISSUE TITLE
black screen and reboot after installation

### ISSUE THREAD

**Issue by haowu0625** [dnschneid/crouton#3331]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: xenial
Enter encryption passphrase for xenial: 
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: arm64
xmethod: xorg
targets: lxde
host: version 9460.60.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 16:59:00 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

#### Please describe your issue:

black screen and reboot after installation

**Comment by crony1** [comment]
I have the same issue on my Samsung Chromebook Plus if I don't run it with xiwi.

**Comment by DennisLfromGA** [comment]
Mostly likely dup of: https://github.com/dnschneid/crouton/issues/3195
Please track it there.
