### ISSUE TITLE
chroot no longer executing url's in ChromeOS

### ISSUE THREAD

**Issue by Lite5h4dow** [dnschneid/crouton#3332]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170619181610~master:980f090f
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xiwi,gnome
host: version 57.1.91 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Tue Jun 20 23:58:57 UTC 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,gnome
host: version 57.1.91 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.4.14+ #1 SMP Tue Jun 20 23:58:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
I was an idiot and decided I wanted to use the gnome extension for chromium, not realizing that this cut the link to crouton opening URL's in Chrome OS instead of in chromium in gnome. now I realized what I've done I want to change it back, I've already purged chromium from my gnome install. I just want it to execute URLs in Chrome OS again :'(

#### If known, describe the steps to reproduce the issue:
sudo apt-get install chromium (and my world was destroyed)

**Comment by dnschneid** [comment]
You could try using `update-alternatives` to make sure x-www-browser, gnome-www-browser, and www-browser point to the croutonurlhandler.  You may also want to look at your gnome settings for default applications.

**Comment by Lite5h4dow** [comment]
perfect, that fixed it :D thanks
