### ISSUE TITLE
How to -t xiwi but keep -t xorg default?

### ISSUE THREAD

**Issue by jvschiavo** [dnschneid/crouton#3338]
#### Please describe your issue:
I usually use my own notes tutorial to set up a chroot that starts with:
```
sudo sh ~/Downloads/.crouton -r xenial -t xiwi,xfce,keyboard
sudo sh ~/Downloads/.crouton -n xenial -u -t xorg
```
My question is: is there a way to merge them into one line? I mean, I want xiwi to be installed, but I want xorg to keep being the default one, that's why I do this update after that, but it takes too much unnecessary time (I mean, xorg is installed anyway if I target xiwi, right? Question#2).

Also, I'm not sure if it is the right place to ask, I think I shouldn't be doing questions here. If that's the case please let me know. Also, please tell where I can ask questions like this about crouton.

Thank you. :)

**Comment by DennisLfromGA** [comment]
@jvschiavo,

I believe the first xmethod specified will be the default, so the following should install both 'xorg' & 'xiwi' but make 'xorg' the default: 

`sudo sh ~/Downloads/crouton -r xenial -t xorg,xiwi,xfce,keyboard`

> *NOTE: I removed the dot '.' in front of `crouton`, not sure why it was there????*

----
And this is the place to ask questions also, no worries. :)

*Hope this helps,*
-**DennisL**

**Comment by jvschiavo** [comment]
I really hope that the order makes the difference, thank you. I will try that.

And about the dot, it is something that I do. I name it .crouton because it stays hidden on my Downloads folder, so I don't keep seeing it in the file explorer of the Chrome OS and also there is less risk of deleting it accidentally etc. haha :)

**Comment by DennisLfromGA** [comment]
@jvschiavo,

Just installed a new chroot specifying `-t xorg,xiwi,....` and 'xorg' was indeed the default xmethod so if 
 'xorg' is specified before 'xiwi' it will be the default, alleviating the need to update the chroot with the second command.

*Hope this helps,*
-**DennisL**

**Comment by jvschiavo** [comment]
Just wanted to say that I used it now and I can confirm too that this works. Thank you.
