### ISSUE TITLE
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)

### ISSUE THREAD

**Issue by peepo** [dnschneid/crouton#3339]
I installed standard ubuntu which runs startkde as expected on Asus C200M tx
however when I added chroot sid & run alone:
sudo startkde -n debian
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)

sudo startkde -n xenial
wfm

these are vanilla installs: sudo sh ~/Downloads/crouton -r sid -t kde -n debian
I have only a couple weeks experience with crouton 
found similar issues, but felt they are not similar enough....

$ sudo edit-chroot -all
name: debian
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/debian...
crouton: version 1-20170619181610~master:980f090f
release: sid
architecture: amd64
xmethod: xorg
targets: kde
host: version 9763.0.0 (Official Build) canary-channel squawks 
kernel: Linux localhost 4.4.70-11145-ge5e3d36c33c6 #1 SMP PREEMPT Thu Jul 20 11:09:30 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/debian...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: kde
host: version 9763.0.0 (Official Build) canary-channel squawks 
kernel: Linux localhost 4.4.70-11145-ge5e3d36c33c6 #1 SMP PREEMPT Thu Jul 20 11:09:30 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by RyuzakiKK** [comment]
same here with debian stretch and gnome

**Comment by m0nk3d0** [comment]
MIght as well chime in, any debian or kail-rolling I try gives the same error as above.

**Comment by TheCookieHero** [comment]
Same problem on xfce.

**Comment by zeroasterix** [comment]
I am also stuck here. I have experimented with startxiwi -b xterm, xorg logs, modifying config files to allow any users, even removing a write-protect screw for chromium OS. The only success I have had is in using unity desktop. No luck with Debian, kali-rolling,or gnome. What is the common thread here? Are we just missing something? I am using a Asus Chromebook 301S and have applied -t audio,x11,extension,keyboard,gtk-extra,core,xfce,xfce-desktop,xiwi... and still no luck

**Comment by rogue417** [comment]
This challenges me on a Lenovo Yoga 11e Chromebook.  The thing is I have a /dev/tty file, just no tty0.  Does this mean I should try swapping out my tty file, or modify xinitrc to call for the current tty?

**Comment by Edelis1931** [comment]
found solution from :https://github.com/dnschneid/crouton/issues/3242

@jernic
jernic commented on Jul 26
I had this problem after upgrading a chroot (kali-rolling, xiwi, xfce). Logged into the chroot using enter-chroot, ran 'sudo apt remove xserver-xorg-legacy', and this seems to have fixed it. Thanks!

**Comment by rogue417** [comment]
This solution worked for me.  Many thanks!

**Comment by DennisLfromGA** [comment]
Dup of https://github.com/dnschneid/crouton/issues/2875, please track there.

**Comment by CroutonGeek** [comment]
If removing the xserver-xorg-legacy package doesn't work, add the x11 target to your chroot.

**Comment by Huixxi** [comment]
> If removing the xserver-xorg-legacy package doesn't work, add the x11 target to your chroot.

what the meaning of `add the x11 target to your chroot.`

**Comment by CroutonGeek** [comment]
> > If removing the xserver-xorg-legacy package doesn't work, add the x11 target to your chroot.
> 
> what the meaning of `add the x11 target to your chroot.`

Suppose you installed -r xenial -t whatever. So you can't get /dev/tty0 to show up:

`sudo sh ~/Downloads/crouton -r xenial -t x11 -u`

In other words, update your release with the x11 target. To see a list of targets:

`sudo sh ~/Downloads/crouton -t list`

I hope this helps! ~James

**Comment by DennisLfromGA** [comment]
**Note**: If you've previously installed *any* of the below targets the x11 target will have been installed along with it:
   
```
chrome
        Google Chrome browser, stable channel.
        Requires: x11
chrome-beta
        Google Chrome browser, beta channel.
        Requires: x11
chrome-dev
        Google Chrome browser, dev channel.
        Requires: x11
chromium
        Chromium browser. Uses the distro's version, which may be old.
        Requires: x11
extension
        Clipboard synchronization and URL handling with Chromium OS.
        Requires: x11
gtk-extra
        GTK-based tools including gdebi and a simple browser.
        Requires: x11
kde
        Installs a minimal KDE desktop environment. (Approx. 600MB)
        Requires: x11
keyboard
        Adds support for Chromebook keyboard special keys.
        Requires: x11
kodi
        Installs the KODI media player. (Approx. 200MB)
        Requires: x11
touch
        Touchscreen and limited generic gesture support.
        Requires: x11
```

*Hope this helps,*
-**DennisLfromGA**
