### ISSUE TITLE
Malformed proxy settings fail in unclear ways

### ISSUE THREAD

**Issue by rjhorn-agfa** [dnschneid/crouton#3341]
I noticed this bug setting up a new Chromebook with a freshly downloaded crouton on 24 July 2017.  I attempted to set up new partitions of "trusty" and "Xenial".  This was on a network where the proxy was at 192.168.1.1:8118.

Both went part way, downloading and installing some packages.  Then there was a series of errors reporting that it was unable to connect to "8118:80".  This looks like a parsing or argument passing error somewhere.

There were no problems with installation when I moved to a network with direct connectivity.

**Comment by dnschneid** [comment]
Are you still able to repro?  Could you please post the logs around where it failed?  If it's failing partway through downloading packages, it may be an upstream bug.

**Comment by rjhorn-agfa** [comment]
I'll recheck, probably Wednesday.  I'm not  sure about logs.  I never 
tried tee and re-directs of stdout/stderr with the chromium bash.  I hope 
that's sufficient for log.

It's conceivable that it's upsteam, but it happens in the transition 
between the downloads of the updates for packages that I've selected for 
installation (those work) and the re-building of the X/CRAS/etc. that is 
part of crouton (those get the incorrect proxy).

Kind Regards,

Robert Horn | Agfa HealthCare
Interoperability Architect | HE/Technology Office
T  +1 978 897 4860

Agfa HealthCare Corporation, Gotham Parkway 580, Carlstadt, NJ 07072-2405, 
USA
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Click on link to read important disclaimer: 
http://www.agfahealthcare.com/maildisclaimer

**Comment by rjhorn-agfa** [comment]
```
It's still there.  

Using the command, the error shows up when the package checks begin.  First, some are IGN, and then some are errors.  This is on the network that is proxied.  Note that when the error is finally reported, the proxy is wrong.

sudo sh ~/Downloads/crouton -P 192.168.1.10:8118 -t xiwi,xfce -r xenial -e -u 
...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Ign:1 http://cran.rstudio.com/bin/linux/ubuntu xenial/ InRelease
Ign:2 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Release
Ign:3 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Packages.diff/Index
Ign:4 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Translation-en
Ign:5 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Packages
Ign:4 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Translation-en
Ign:5 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Packages
Ign:4 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Translation-en
Ign:5 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Packages
Ign:4 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Translation-en
Ign:5 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Packages
Ign:4 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Translation-en
Ign:5 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Packages
Ign:4 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Translation-en
Err:5 http://cran.rstudio.com/bin/linux/ubuntu xenial/ Packages
 Cannot initiate the connection to 8118:80 (0.0.31.182). - connect (22: Invalid argument)
Ign:6 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:7 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Ign:8 http://archive.ubuntu.com/ubuntu xenial-security InRelease
Ign:9 http://archive.ubuntu.com/ubuntu xenial Release
Ign:10 http://archive.ubuntu.com/ubuntu xenial-updates Release

I tried suppressing the proxy while still on the network that is proxied.  Now there is an immediate error.

﻿sudo sh ~/Downloads/crouton -P “”  -t xiwi,xfce -r xenial -e -u 
...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Err:1 http://cran.rstudio.com/bin/linux/ubuntu xenial/ InRelease      
 Temporary failure resolving 'cran.rstudio.com'
Err:2 http://archive.ubuntu.com/ubuntu xenial InRelease               
 Temporary failure resolving 'archive.ubuntu.com'
0% [Connecting to archive.ubuntu.com]^CUnmounting /mnt/stateful_partition/crouton/chroots/xenial...
^C^C[: 1: Illegal number:

```

Finally, on the guest network, that is not proxied:

Get:1 http://cran.rstudio.com/bin/linux/ubuntu xenial/ InRelease [3590 B]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease  
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [272 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [628 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [603 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-security/main Sources [89.7 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages [353 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-security/main i386 Packages [330 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-security/main Translation-en [154 kB]
Fetched 2638 kB in 2s (1286 kB/s)                               
Reading package lists... Done

Sorry about the cut and paste logs.  I couldn't figure out how to capture the output from crouton into a file.

**Comment by dnschneid** [comment]
What happens if you do `-P http://192.168.1.10:8118/`?  Maybe apt's config is treating 192.168.1.10 as the protocol.

**Comment by rjhorn-agfa** [comment]
That's the problem.  It needs the protocol.  I recall there used to be a clearer error when that was missing.  Thank you.

I also noticed that it will use the same protocol for both http and https.  Some proxy/client combinations require that https:// be used for TLS and http:// be used when not TLS.  

It's too bad proxy can't be inherited from the Chromebook settings.  I had to get them right for basic Chrome functions to work.

**Comment by dnschneid** [comment]
If you can figure out some way to do it...

Do we need some sanity checking on the `-P` input?

**Comment by rjhorn-agfa** [comment]
The proxy reference is required to be a URL and a format catcher could have caught that one.

All URLs for an IP-based protocol take the form   "<protocol>//<user>:<password>@<host>:<port>/<url-path>" where parts can be left out.  But all valid URLs will contain the string "//" and there will be something in <protocol>.  That would have caught this error.

It might also make sense to limit proxies to start with "http://", "https://", and "ftp://".  The apt-get manual only identifies http and ftp as proxy options.  Perhaps a warning if the string does not start with "http://", "https://", or "ftp://", and an error if there is not a "//" somewhere in the string.

**Comment by KNLc** [comment]
> What happens if you do `-P http://192.168.1.10:8118/`? Maybe apt's config is treating 192.168.1.10 as the protocol.

It works for me!

**Comment by KNLc** [comment]
> The proxy reference is required to be a URL and a format catcher could have caught that one.
> 
> All URLs for an IP-based protocol take the form "//:@:/" where parts can be left out. But all valid URLs will contain the string "//" and there will be something in . That would have caught this error.
> 
> It might also make sense to limit proxies to start with "http://", "https://", and "ftp://". The apt-get manual only identifies http and ftp as proxy options. Perhaps a warning if the string does not start with "http://", "https://", or "ftp://", and an error if there is not a "//" somewhere in the string.

Thanks, it works for me!
