### ISSUE TITLE
Installing Virtualbox modules, how do I find my kernel on git?

### ISSUE THREAD

**Issue by libjared** [dnschneid/crouton#3342]
```
$ sudo edit-chroot -all
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20170619181610~master:980f090f
release: sid
architecture: amd64
xmethod: xorg
targets: extension,keyboard,xfce,gnome
host: version 9592.71.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Wed Jul 26 23:33:35 PDT 2017 x86_64 GNU/Linux
freon: yes
```

I'm the owner of an ASUS C302 and I'm trying to install VirtualBox on Debian sid. As described on [the wiki page](https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)), I'm supposed to find the right kernel commit from which to build headers.

The closest I could get, at `chromeos-3.18~603` was

```
uname -r: 3.18.0-14875-g438cb8ab27c6
git     : 3.18.0-14875-g5fa75c00eeca
```

I also tried the git rewind script posted in #2642, no luck.

I've matched the "3.18.0-14875" part, but where does the hash afterwards come from? What are some other steps I can take to find the correct kernel commit for my machine?

**Comment by libjared** [comment]
I got VirtualBox installed and running okay. Because it was such a pain in the ass, I’ll document all my steps. IMO the [wiki page](https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)) needs futher work.

# Finding the Right Kernel Version

I dug a little deeper into the kernel repo's [branches and tags](https://chromium.googlesource.com/chromiumos/third_party/kernel/+refs).

First I tried the recommended "chromeos-3.18", then CTRL+F’d for [my device's codename](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices) "glados" and found a few, but still no $(uname -r) match. Then I remembered that "About Chrome OS" has a submenu called "Detailed build information".
Here’s what’s written in Platform: `9592.71.0 (Official Build) beta-channel cave`

So I CTRL+F'd for "9592". 
```
release-R60-9592.B-chromeos-3.18    : 3.18.0-14875-g438cb8ab27c6
uname -r                            : 3.18.0-14875-g438cb8ab27c6
```
Success! I found the commit for my specific kernel version. I check it out, and the build continued from the wiki as normal, with some extra tips I’ll list below.

# Some GCC Errors

This is sorta similar to some info in the wiki but my case differs.

GCC may fail with errors like `code model kernel does not support PIC mode` or `Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler`. It’s because Debian sid uses GCC _6_. I fixed this by installing gcc-5 from apt and making the `/usr/bin/gcc` symlink point to `gcc-5` instead of `gcc-6`.
```
sudo ln -sf gcc-5 /usr/bin/gcc
# to switch back (which I must do after building the kernel,
# else my next chroot update will fail to compile CRAS!)
sudo ln -sf gcc-6 /usr/bin/gcc
```

If you are in the far future, reading this ancient tome, keep in mind that gcc-9 or something may be the Debian sid default by then, not 6.

# Annoyingly Persistent Mounting Script

When I installed virtualbox, I noticed that the module installer wouldn’t find the linux headers I’d painstakingly built and installed. I think most crouton scripts `startxfce4` or `enter-chroot` re-mount `/lib/modules` (which is what we were trying to _prevent_ with that /etc/rc.local script). I dunno why! For now, frequently double and triple check by unmounting `/lib/modules/$(uname -r)`. Good thing it was readonly at the time.

# Keep Your Kernel Source

It's a good idea for you to never move/rename/replace the contents of OR the `~/kernel` directory itself. Buuut if you’re dumb like me, you’ll do it anyway, and here’s why virtualbox module installation breaks as a result…

This symlink in `/lib/modules` points to where you compiled the kernel from. In our case that’s ~/kernel. Who ever heard of a compiled project keeping track of the original source folder by path only? But since I’m shuffling directories around in my home folder, virtualbox-dkms mindlessly follows this link, and the resulting vbox* modules become rabies-infested hybrids of two different kernel versions (modprobe calls it `Exec format error`). Solution? Rewrite a symlink and point to the copy in `/usr/src`. That’s what it’s there for.
```
sudo ln -sf /usr/src/linux-headers-$(uname -r) /lib/modules/$(uname -r)/build
```
(A million thanks to [this guy](https://askubuntu.com/a/714875/317450))

**Comment by DennisLfromGA** [comment]
@libjared,

Excellent, thanx for the detailed info. and your persistence.

> IMO the wiki page needs futher work.

That's an excellent suggestion too, *go for it!*

-**DennisL**
