### ISSUE TITLE
script is referencing "InRelease" instead of "Release"

### ISSUE THREAD

**Issue by spearthistle** [dnschneid/crouton#3345]
a number of the targets "Precise", "Trusty", "Wheezy", "Stretch", etcetera, for ARMHF architecture cannot install because "W: Retrying failed download of http://httpredir.debian.org/debian/dists/stretch/InRelease" is referencing the InRelease file, which doesn't exist.  Only "Release" exists in these directories.

**Comment by bubby131** [comment]
Im having the same exact problem but have found no solution, good luck!

**Comment by octopusnz** [comment]
I think this is a thing - but not too sure what causes it. It was discussed quite a lot in #2966 (more wisdom and possible causes there but no definite solution).

**Comment by nynymike** [comment]
Ditto

**Comment by nynymike** [comment]
https://askubuntu.com/questions/903611/apt-get-tries-to-get-inrelease-which-does-not-exists-anymore

Solved with:

**Comment by DennisLfromGA** [comment]
@nynymike,

Thanx for the link to '[renewing `/var/lib/apt/lists/*`](https://askubuntu.com/questions/903611/apt-get-tries-to-get-inrelease-which-does-not-exists-anymore#comment1421511_903611)'.

It does appear that this error can manifest itself in some systems, I haven't run into it myself but it's great to have a remedy at the ready.

-**DennisLfromGA**
