### ISSUE TITLE
trouble starting chroot

### ISSUE THREAD

**Issue by arcaniussainey** [dnschneid/crouton#3346]
```
Please paste the output of the following command here: sudo edit-chroot -all
```name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/local/bin/enter-chroot: 511: cannot create /run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/crouton/name: Directory nonexistent
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...


#### Please describe your issue:
when i try to create a chroot with sudo enter-chroot or sudo enter-chroot startxfce4 i get this
No chroots found in /mnt/stateful_partition/crouton/chroots
why is this, i have tried updating xenial, but that hasn't worked

#### If known, describe the steps to reproduce the issue:
![screenshot 2017-07-29 at 10 33 40 pm](https://user-images.githubusercontent.com/28377119/28750133-33e89e8e-74ae-11e7-9334-836a2daa8ec4.png)

**Comment by DennisLfromGA** [comment]
@aghasemi,

You may have some permission problems with your chroot.
Try following this wiki guide for help: ['Common issues and reporting'](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**

**Comment by 9291Sam** [comment]
Are you starting with root perms?

**Comment by arcaniussainey** [comment]
i have already read and tried the common issues page and looked at updating
it, but i get the same errors, and i have rootfs and my root/sudo passwd.

**Comment by 9291Sam** [comment]
Have a you (seriously) tried turning it off and back on again and then if that does not work reinstall the chroot after deleting it

**Comment by DennisLfromGA** [comment]
@arcaniussainey,

Please show us what is displayed when you enter the following two commands:

- `ls -l /usr/local/chroots`
- `ls -l /mnt/stateful_partition/crouton/chroots`

*Hope this helps,*
-**DennisL**

**Comment by arcaniussainey** [comment]
Uninstall/re-install worked, and i installed gnome.
