### ISSUE TITLE
Segmentation fault (core dumped) on Chromebook Pro - Crouton unstable

### ISSUE THREAD

**Issue by neodata686** [dnschneid/crouton#3347]
```
chronos@localhost / $ sudo enter-chroot -n xenial croutonversion
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce
host: version 9592.71.0 (Official Build) beta-channel caroline 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Wed Jul 26 23:32:53 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
I've tried Crouton with XFCE4 (Xenial) on Chrome OS 58, 59, and now 60 (beta channel). I've done multiple installs and power washes. No matter what when running in -xOrg mode (not xiwi) Ubuntu eventually gets to an unusable state. Anything I try to launch via the UI doesn't launch. If I try to launch something from a terminal (within XFCE) I get:

```
(xenial)username@localhost:~$ firefox
ExceptionHandler:GenerateDump cloned child 28655
ExceptionHandler::SendContiueSignaltoChild sent continue signal to child
ExceptHandler::WaitForContinueSignal waiting for continue signal...
Segmentation Fault (core dumped)
```
Essentially anything I try to launch causes this. I noticed that certain driver features (e.g. trackpad off while typing) no longer work either. Neither does copy/paste between Chrome OS and XFCE.

Since I started XFCE and the chroot became unusable/unstable:

```
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Wed Jul 26 23:32:53 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=177dfb36-8aad-b945-9240-35c479dc770a/PARTNROFF=1 hashtree=PARTUUID=177dfb36-8aad-b945-9240-35c479dc770a/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=af31498e7c13aa7c751573c029cb862e61c6e355 salt=a95fe1dadca15a34806805f8be5301218e352b8d0181fa67a526958c46cb833f" noinitrd vt.global_cursor_default=0 kern_guid=177dfb36-8aad-b945-9240-35c479dc770a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 17 July 2017  05:05:12PM
xorg-server 2:1.18.4-0ubuntu0.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jul 28 13:10:28 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce
host: version 9592.71.0 (Official Build) beta-channel caroline 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Wed Jul 26 23:32:53 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output HDMI2 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output HDMI2 is not disconnected but has no modes
Kicking xrandr again
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
xfce4-session: No GPG agent found
xfce4-session: No SSH authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: NetworkError when attempting to fetch resource.
Full stack: loadFile@resource://gre/modules/services-common/blocklist-clients.js:119:30
TaskImpl_run@resource://gre/modules/Task.jsm:319:42
TaskImpl@resource://gre/modules/Task.jsm:277:3
asyncFunction@resource://gre/modules/Task.jsm:252:14
Task_spawn@resource://gre/modules/Task.jsm:166:12
loadDumpFile@resource://gre/modules/services-common/blocklist-clients.js:118:12
syncCollection@resource://gre/modules/services-common/blocklist-clients.js:212:39
TaskImpl_run@resource://gre/modules/Task.jsm:319:42

*************************
(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
Error: target STRING not available
selfservice is unable to find a compatible webkit library and will now exit.
selfservice is unable to find a compatible webkit library and will now exit.
(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
^TError: target STRING not available
Segmentation fault (core dumped)
Segmentation fault (core dumped)
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
ExceptionHandler::GenerateDump cloned child 26863
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...

(xfce4-terminal:23480): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
ExceptionHandler::GenerateDump cloned child 27923
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
ExceptionHandler::GenerateDump cloned child 28564
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
(II) AIGLX: Suspending AIGLX clients for VT switch
Segmentation fault (core dumped)
Segmentation fault (core dumped)
(II) AIGLX: Suspending AIGLX clients for VT switch
```
Any ideas? At this point I'm at a loss. After multiple tries it seems like an issue with Chromebook Pro and Crouton. Has anyone had success running Crouton on their CBPro?

After researching the various error messages I haven't come across anything solid. The most common theme has been an issue with the Intel driver. 

Again this occurs after a powerwash and fresh install of the latest version of Crouton (Xenial) and xorg in xfce on a Samsung Chromebook Pro. 

#### If known, describe the steps to reproduce the issue:
Switching back and forth seem to cause this "state" to occur faster. Sometimes I'll even get a black screen when switching back to ChromeOS. The only way to remedy is holding down the power button to shut down and restart. Often I'll be able to work in xorg for an hour and have it remain stable. I do however get mini-freezes every once in a while. These only last 1-2 seconds. I'm not sure if this is related or not. However after switching back and forth a few times it eventually becomes unstable with the semgentation fault (core dumps).

**Comment by brandinchiu** [comment]
I have crouton Xenial-Unity working on my Chromebook Pro.  However, I have experienced the Segmentation fault error occasionally.  I seem to be able to go 3-4 days in between them.  I'm using my Chromebook for work, at least 8 hours a day, exclusively in Ubuntu -- so it definitely hasn't been a limiting factor in my ability to use it.

I'm not sure why you seem to be seeing this error more often than me.  Granted I don't spend a lot of time switching back and forth between the two.  I have also noticed the "mini-freezes" (although mine tend to last a lot longer than yours), and I've also encountered the ChromeOS black screen.

All that said, I wouldn't say my device is any _more_ unstable than my Windows machine was, factoring issues with sleep, handling multiple screens, running linux in VMs, coupled with the constant Windows spam of updates and other garbage bloat.

**Comment by neodata686** [comment]
That's strange - it happens enough where I can't really use Xenial-Unity as a working solution. I have a dedicated Dell XPS as my work laptop and a Chromebook could never replace that. Windows 10 is far more stable than trying to use Linux on this thing. It's more of just an experiment for me. I don't have any issues with sleep, multiple VMs, or bloatware (there really isn't any once you've got a good install going). With any OS it's about fine tuning it. Unfortunately Windows just takes a little more time for that. 

Anywho I'll wait around and hope future updates fix this. It's really only for native ops I want to run (e.g. Steam games) as Xiwi seems to work flawlessly.

**Comment by friedman101** [comment]
I also have this problem, it's caused me to switch to Gallium for the time being. I'd prefer to use crouton but the segfaults and "mini freezes" are too bothersome.

**Comment by neodata686** [comment]
Yes it's still happening enough where Crouton really isn't usable on the Samsung CB Pro.

**Comment by friedman101** [comment]
Xiwi works but the lag is annoying, especially when I extend my desktop to an external monitor. Has anyone found a work-around for this issue?

**Comment by peterwilli** [comment]
I get core dumped errors for quite some time. It seems worse then normal, actually. I got the Acer R11 with 4GB ram. Should be enough to run XFCE.

**Comment by fsharpasharp** [comment]
Is this still an issue? I'm interested in the CB Pro and this might be a dealbreaker. Can it be avoided if you don't switch back and forth? I want to use Xorg.

**Comment by friedman101** [comment]
this issue still exists as far as i can tell.

**Comment by fsharpasharp** [comment]
I had the mini freezes when running i3wm, but not while using Unity.

**Comment by peterwilli** [comment]
A side note: I'm now using Xiwi in tabs, which is much faster right now. It works much better especially when switching screens a lot.

**Comment by fsharpasharp** [comment]
I suspected the "mini freezes" had something to do with the screen refreshing since it didn't actually freeze the system only the display. They disappeared completely in Unity which is probably because of the composite manager, I'm now using i3wm again with compton running with vsync enabled. Try it out if you have any mini freezes.

**Comment by fortran77** [comment]
I've seen segmentation faults from Crouton installations on two different devices: An Asus CN62 series Chromebox2-G013U, and a Samsung Chromebook Pro. I installed Crouton with the following command line in both cases:

    sudo bash ./crouton -e -r xenial -t xiwi,audio,chrome,cli-extra,extension,xorg,gnome-desktop,gtk-extra -n xenial

In both cases I tried to find a core file by cd'ing into / (from a crosh window after the 'shell' command, and also after doing 'sudo enter-chroot') and doing a 'find' looking for 'core' and 'core.[0-9]*', and found none. Presumably a core file it not actually being generated, even though some of the segmentation fault errors print a 'core dumped' indication. (Note: There are a lot of files that begin with the string 'core' but they are JavaScript and Python files, not core dump files. Somebody has a sense of humor and they like to name a lot of their programs with the word 'core'.)

**Samsung Chromebook Pro**

On the Samsung Chromebook Pro, the Crouton environment was installed a couple of weeks ago, and worked perfectly until today. I did a normal update today from within a crosh window thus:

    (ctrl-alt-T to get crosh window)
    shell
    sudo enter-chroot
    sudo apt-get update
    sudo apt-get upgrade

After this everything broke. Now I get a fatal segmentation fault if I invoke the graphical desktop environment with the commands:

    (ctrl-alt-T to get crosh window)
    shell
    sudo startgnome -X xiwi

I also get a fatal segmentation fault when I use the following sequence of commands:

    (ctrl-alt-T to get crosh window)
    shell
    sudo enter-chroot
    dropbox start

The above is a pure command-line program, with no graphics, so it's odd that it broke too.

So I decided to try to install Galliumos instead on this machine, and sad to say that doesn't work either, as it ignores all touchpad presses.

**Asus CN62 series Chromebox2-G013U**

I had the same problems a week ago when I installed Crouton on this machine. None of the xiwi-related commands listed above ever worked. All exited with a fatal segmentation fault error. I also got a fatal segmentation fault error when trying to invoke commands in a tab, thus:

    (ctrl-alt-T to get crosh window)
    shell
    xiwi <any-gui-command>

Fortunately I was able to successfully install Galliumos on this machine.

**Comment by Invisiblehacker** [comment]
I get this issue too. I have been running xfce4, lxde desktop for about a month with no problems. but today i ran the lxde command and got this error. I also downloaded chromebrew today and got the same error

**Comment by friedman101** [comment]
This issue has caused me to stop using crouton. Is there any hypothesis what might be causing this?

I noticed that when running an unencrypted chroot the sessions were much more stable.

**Comment by fortran77** [comment]
On both devices on which I reported segmentation faults (Asus CN62 series Chromebox2-G013U and Samsung Chromebook Pro), repeating the installation attempt a number of times always lets it complete, usually within 3-4 repetitions.

The key is to make sure the chroot directory tree is unmounted and remounted before making another install or upgrade attempt. If the chroot directory tree remains mounted, then once segmentation fault occurs, it will occur again on every subsequent install or upgrade attempt.
