### ISSUE TITLE
When ever i try to install crouton on my chromebook...

### ISSUE THREAD

**Issue by hansxd** [dnschneid/crouton#3349]
```

``` 
#### Please describe your issue:      Hi , I used this command to install crouton on my Chromebook : sudo sh ~/Downloads/crouton -r trusty -t xfce
Everything was going smoothly , fine until my screen unexpectedly turned black , it was still downloading when google chrome closed , so i opened chrome and try to install crouton again but now this appears when i type the previous command :    /usr/local/chroots/trusty already has stuff in it! Either delete it, specify a different name (-n), or specify -u to update it. 

PS:  the output of sudo edit-chroot -all  Its : 
name: trusty
encrypted : no 
Entering  /mnt/stateful_partition/crouton/chroots/trusty...
crouton:  version  1-20170619181610-master:980f090f
release:  trusty 
architecture:  armhf 
targets:  xfce
host:  version  9765.16.0  (Official  Build)  dev-channel daisy 
kernel :  Linux localhost  3.8.11  #1  SMP Wed Aug 2  21:49:57  PDT 2017 armv7l armv7l armv7l GNU/linux
freon: yes
unmounting /mnt/stateful_partition/crouton/chroots/trusty...

What does this mean? that the download was successful? i still dont have a password , username , etc.

**Comment by DennisLfromGA** [comment]
@hansxd,

> ... /usr/local/chroots/trusty **already has stuff in it!** 

It means you have an existing chroot, even though the installation may not have completed.

> Either delete it, specify a different name (-n), or specify -u to update it.

So now, those are your options.
If it were me, I would first try to *update* it then if that fails delete it and start over.

You can update your chroot using the following:

`sudo sh ~/Downloads/crouton -n trusty -u`

*Hope this helps,*
-**DennisL**
