### ISSUE TITLE
Is there support for newer kernels for 32bits ARM based chromebooks?

### ISSUE THREAD

**Issue by chrisics** [dnschneid/crouton#3351]
Xenial under chroot reports kernel 3.10.18. 
Is this correct?
If so, is there no support for newer kernels?
Thanks

**Comment by icecream95** [comment]
The kernel version for Chromebooks are not changed over time, which I presume is to make them more stable.

All Chromebooks with the same platform (e.g. Tegra K1, RK3288, Skylake) have the same kernel version. The newest 32bit ARM kernel version in 3.14, for Chromebooks with the RK3288 platform.

For more information about Chromebook kernel versions, look at the [Developer Information for Chrome OS Devices](http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/) page

You could try compiling your own kernel, but I'm not sure what steps are needed to get hardware OpenGL support.
