### ISSUE TITLE
Please Help Cant start Kali linux

### ISSUE THREAD

**Issue by awsomo26** [dnschneid/crouton#3354]
Hello i have been trying to start kali linux so when i type in sudo startxfce4 i get this error

Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/local/bin/startxfce4: 32: exec: /usr/bin/startxfce4: not found
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/kali...
chronos@localhost / $ Entering /mnt/stateful_partition/crouton/chroots/kali...

Please any help would be great 
Thanks

**Comment by DennisLfromGA** [comment]
Likely dup of #2875, please track it there.
