### ISSUE TITLE
[Distro support] Devuan?

### ISSUE THREAD

**Issue by jxyzn** [dnschneid/crouton#3355]
How feasible is support for Devuan Jessie/Stable and/or Testing?

**Comment by DennisLfromGA** [comment]
@jxyzn,

If you are talking about 'debian jessie' then you're in luck.

The following releases are available in 'crouton' -
```
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety* zesty*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```
Just use `-r jessie` for the release when installing your crouton chroot.

*Hope this helps,*
-**DennisL**

**Comment by jxyzn** [comment]
@DennisLfromGA  Thanks, but no. Devuan is a fork of Debian, minus systemd. http://devuan.org

**Comment by DennisLfromGA** [comment]
@jxyzn,

Sorry, I should have googled it before responding, just thought it was a typo - duh!

> Devuan GNU+Linux is a fork of Debian without systemd.

That sounds to me like a good candidate for crouton but it's plain to see I don't know everything. :)

Maybe one of the devs or someone else with more knowledge about it might take a stab at it, or explain why it might not be worthy.

I'll butt out before I dig a deeper hole.

-**DennisL**

**Comment by shelleyvadams** [comment]
Personally, I'd be interested in a systemd-less distro because changes in Debian 9 (stretch) are giving me grief #3318 -- but that's just me whining.  🎻 

Others, [including Linus Torvalds][1], have made more technical and/or philosophical arguments about [why systemd is problematic][2].

[1]: http://www.zdnet.com/article/linus-torvalds-and-others-on-linuxs-systemd/
[2]: https://duckduckgo.com/?q=systemd+(criticism+OR+problems)

**Comment by CameronNemo** [comment]
Void Linux could be a great candidate! It has eudev and elogind packaged, so lots of common desktop environments do fine.
