### ISSUE TITLE
Attempting to startxfce4 crashes Chromebook Plus

### ISSUE THREAD

**Issue by nukachicken** [dnschneid/crouton#3363]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
Enter encryption passphrase for xenial: 
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: arm64
xmethod: xorg
targets: xfce-desktop
host: version 9460.73.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.52-08273-ge6c7193d61d7 #1 SMP PREEMPT Thu Jul 13 12:07:57 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
Attempting to start crouton as instructed (using "sudo startxfce4") results in a black screen, and eventually a restart of the Chromebook Plus.

#### If known, describe the steps to reproduce the issue:
I installed crouton by using "sudo sh ~/Downloads/crouton -e -t xfce-desktop" as suggested by other Chromebook Plus users. I am open to uninstalling and trying other builds etc

**Comment by DennisLfromGA** [comment]
@nukachicken,

DUP - Take a look at this issue for a workaround: #3234

Hope this helps,
-DennisL
