### ISSUE TITLE
can't install any distro on my xe503c12

### ISSUE THREAD

**Issue by ville1001** [dnschneid/crouton#3364]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170619181610~master:980f090f
release: kali-rolling
architecture: armhf
targets: xfce
host: version 9869.0.0 (Official Build) dev-channel peach_pit 
kernel: Linux localhost 3.8.11 #1 SMP Tue Aug 22 18:57:57 PDT 2017 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
http://i.imgur.com/Gbnrg0T.png
This happends everytime i install a distro, i have tried debian and kali
#### If known, describe the steps to reproduce the issue:
just install the distro

**Comment by DennisLfromGA** [comment]
@ville1001,

DUP - Take a look at this issue for a the root cause & a workaround: #3352

Hope this helps,
-DennisL
