### ISSUE TITLE
Cannot move chroot to SD Card

### ISSUE THREAD

**Issue by chiragzq** [dnschneid/crouton#3365]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,touch,extension,xorg
host: version 9460.73.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Jul 13 12:08:15 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
I have been trying to move my chroot to an external SD Card, but I am unable to mount it to a directory. It just displays the error:
```
chronos@localhost / $ sudo mount /dev/sdb1 /media/removable/sd-card
mount: /dev/sdb1 is already mounted or /media/removable/sd-card busy
```
However the partition is not mounted:
```
chronos@localhost / $ sudo umount /dev/sdb1
umount: /dev/sdb1: not mounted
```
But I do know that the partition is ext4:
```
Device     Boot Start       End   Sectors  Size Id Type
/dev/sdb1        2048 262143999 262141952  125G 83 Linux
```
Any help?

**Comment by DennisLfromGA** [comment]
@spafindoople,

Reboot & try crouton's own method using `edit-chroot` options `-m` or `-C`, see below -
```
edit-chroot [options] name [...]

Edits a chroot.

Options:
    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.
    -C DEST     Like -m, but copies instead of moves.
```
*Hope this helps,*
-**DennisL**

**Comment by spafindoople** [comment]
Thanks for the prompt reply. I got the following output:
```
chronos@localhost / $ sudo edit-chroot -m /dev/sdb1 xenial
Chroots can only be moved to ext filesystems.
```

**Comment by DennisLfromGA** [comment]
@spafindoople,

Yup, crouton chroots need to be on ext2/3/4 file systems.

>    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                **If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.**

To see what file system type it is enter: `mount | grep /dev/sdb`

*Hope this helps,*
-**DennisL**

**Comment by spafindoople** [comment]
Hi, that command doesn't seem to print anything when I run it, but I have already formatted the sd card to ext4. When I type ``` sudo fdisk -l ```
```
Disk /dev/sdb: 125 GiB, 134217728000 bytes, 262144000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x979343de

Device     Boot Start       End   Sectors  Size Id Type
/dev/sdb1        2048 262143999 262141952  125G 83 Linux
```
it says type: linux. Does that mean it on an ext filesystem?

**Comment by spafindoople** [comment]
Any help?

**Comment by spafindoople** [comment]
:(

**Comment by DennisLfromGA** [comment]
@spafindoople,

> To see what file system type it is enter: mount | grep /dev/sdb

>> Hi, that command doesn't seem to print anything when I run it, but I have already formatted the sd card to ext4. 

What is displayed when you enter `mount | grep /dev/sd` ?

-**DennisL**

**Comment by spafindoople** [comment]
```
chronos@localhost / $ mount | grep /dev/sd
/dev/sda1 on /mnt/stateful_partition type ext4 (rw,nosuid,nodev,noexec,relatime,seclabel,commit=600,data=ordered)
/dev/sda8 on /usr/share/oem type ext4 (ro,nosuid,nodev,noexec,relatime,seclabel,data=ordered)
/dev/sda1 on /home type ext4 (rw,nosuid,nodev,noexec,relatime,seclabel,commit=600,data=ordered)
/dev/sda1 on /usr/local type ext4 (rw,nodev,relatime,seclabel,commit=600,data=ordered)
/dev/sda1 on /run/crouton/mnt/stateful_partition/crouton/chroots/xenial type ext4 (rw,relatime,seclabel,commit=600,data=ordered)
```

**Comment by DennisLfromGA** [comment]
@spafindoople,

Sorry, I should have been clearer. Make sure you have the external media inserted and mounted.
It should then show up as `/dev/sdb...` with more details about the file system.

*Hope this helps,*
-**DennisL**

**Comment by spafindoople** [comment]
Ok, this was on of the problems I was having. When I try to mount:
```
chronos@localhost / $ sudo mkdir /media/removable/SD\ Card
chronos@localhost / $ sudo mount /dev/sdb1 /media/removable/SD\ Card
mount: wrong fs type, bad option, bad superblock on /dev/sdb1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```
So when I repair it and try again
```
chronos@localhost / $  sudo e2fsck -f /dev/sdb1
e2fsck 1.43.3 (04-Sep-2016)
Superblock has an invalid journal (inode 8).
Clear<y>? yes
*** journal has been deleted ***

Superblock has_journal flag is clear, but a journal is present.
Clear<y>? yes
Pass 1: Checking inodes, blocks, and sizes
Journal inode is not in use, but contains data.  Clear<y>? yes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Block bitmap differences:  -(2105376--2129919) -(2629664--2654207) -(3153952--3178495) -(3678240--3702783) -(4202528--4227071) -(4726816--4751359) -(5251104--5275647) -(5775392--5799935) -(6299680--6324223) -(6823968--6848511) -(7348256--7372799) -(7872544--7897087) -(8396832--8421375) -(8921120--8945663) -(9445408--9469951) -(9969696--9994239) -(10493984--10518527) -(11018272--11042815) -(11542560--11567103) -(12066848--12091391) -(12591136--12615679) -(13115424--13139967) -(13639712--13664255) -(14164000--14188543) -(14688288--14712831) -(15212576--15237119) -(15736864--15761407) -(16261152--16416767) -(16785440--16809983) -(17309728--17334271) -(17834016--17858559) -(18358304--18382847) -(18882592--18907135) -(19406880--19431423) -(19931168--19955711) -(20455456--20479999) -(20979744--21004287) -(21504032--21528575) -(22028320--22052863) -(22552608--22577151) -(23076896--23101439) -(23601184--23625727) -(24125472--24150015) -(24649760--24674303) -(25174048--25198591) -(25698336--25722879) -(26222624--26247167) -(26746912--26771455) -(27271200--27295743) -(27795488--27820031) -(28319776--28344319) -(28844064--28868607) -(29368352--29392895) -(29892640--29917183) -(30416928--30441471) -(30941216--30965759) -(31465504--31490047) -(31989792--32014335) -(32509968--32538623) -(32735232--32767743)
Fix<y>? yes
Free blocks count wrong for group #497 (0, counted=32768).
Fix<y>? yes
Free blocks count wrong for group #498 (0, counted=32768).
Fix<y>? yes
Free blocks count wrong for group #499 (0, counted=32768).
Fix<y>? yes
Free blocks count wrong for group #500 (0, counted=32768).
Fix<y>? yes
Free blocks count wrong (32107051, counted=32238123).
Fix<y>? yes
Recreate journal ('a' enables 'yes' to all) <y>? yes
Creating journal (131072 blocks):  Done.

*** journal has been regenerated ***
chronos@localhost / $ sudo mount /dev/sdb1 /media/removable/SD\ Card/
mount: /dev/sdb1 is already mounted or /media/removable/SD Card busy
```

**Comment by DennisLfromGA** [comment]
@spafindoople,

> mount: /dev/sdb1 is already mounted or /media/removable/SD Card busy

After the above repair does it now report an ext4 file system?
If not you may have to erase it and start over.

*Hope this helps,*
-**DennisL**

**Comment by spafindoople** [comment]
Yup, it still says that it is linux type. I have erased it and started over lots of times already, all of them have yielded the same results.

**Comment by DennisLfromGA** [comment]
@spafindoople,

Okay, I'm out of ideas, so let's go back a bit.

If you reboot and plug-in your external media it should mount without you having to do anything.
Issuing the mount command will show you where.

> sudo edit-chroot -m /dev/sdb1 xenial

You should be specifying the mount point not the raw partition.
Something like: `sudo edit-chroot -m "/media/removable/SD Card/chroots/" xenial`

If you can't get `edit-chroot` to work for you perhaps go back to your original method by hand copying it to the external media., you can use the syntax in `edit-chroot` like: 

`cp -av --one-file-system "/mnt/stateful_partition/crouton/chroots/xenial" "/media/removable/SD Card/chroots/"`

*Hope this helps,*
-**DennisL**

**Comment by spafindoople** [comment]
Nope, it doesn't mount at all, and I get a notification saying that it is an unrecognized type.

Running the first command says that it can only be moved to ext filesystems.

**Comment by DennisLfromGA** [comment]
@spafindoople,

Well both of those messages suggest your external media is hosed.

-**DennisL**

**Comment by spafindoople** [comment]
Dang, should I try again with a different card?

**Comment by eritain** [comment]
I had a very similar issue with a USB stick. On checking the system logs (in Crosh, `sudo dmesg | tail`) after failing to mount it, I found Chrome was not finding the filesystem journal superblock. 

When I formatted the disk ext4 with journaling turned off (by adding the `-O ^has_journal` option to my `mkfs.ext4` call), Chrome mounted it just fine.

**Comment by eritain** [comment]
... well, there were some subsequent issues with it that produced "Structure needs cleaning" errors, strongly suggesting that the filesystem was borked anyway. I think just bad media. I'm not having these problems with a different external disk.
