### ISSUE TITLE
xserver-xorg-video-dummy has unmet dependencies

### ISSUE THREAD

**Issue by nukachicken** [dnschneid/crouton#3366]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost ~ $ sudo edit-chroot -all
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

I distinctly remember this being more helpful last time and don't know what I did differently. My old readout can be found at #3363.

#### Please describe your issue:

The fix to my last problem (#3363) had me install target xiwi. The process results in one package failing to install due to unmet dependencies.

Installing target xiwi...
xserver-xorg-video-dummy was already not hold.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xorg is already the newest version (1:7.7+13ubuntu3).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xorg-video-abi-20
                            Depends: xserver-xorg-core (>= 2:1.17.99.902)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### If known, describe the steps to reproduce the issue:
I ran "sudo sh ~/Downloads/crouton -n xenial -t xiwi -u" as suggested for the problem in #3234.

**Comment by Derpjohn** [comment]
I am having this same issue. I tried solving it with what was suggested as a workaround in #3234

**Comment by zguithues** [comment]
@nukachicken It looks like you installed only the xiwi target, and didn't choose any other targets...  The xiwi target is a helper that enables the crouton extension, but without choosing any other targets, it doesn't have anything to load into...

Try installing with `sudo sh ~/Downloads/crouton -n test1 -t xfce,xiwi` and start with `sudo startxfce4 -n test1`

This will determine if my guess is correct, or if the problem is deeper...

**Comment by DennisLfromGA** [comment]
@nukachicken,
Since your chroot is encrypted could you please login to it and then show us the output of `croutonversion` so we can figure out what device you're using and other pertinent details ?

@zguithues,
I think @nukachicken may have other targets/desktops installed, the '`-t xiwi -u`' argument just adds the 'xiwi' xmethod to his existing chroot.

-**DennisL**

**Comment by zguithues** [comment]
@DennisLfromGA DUH!!!!
Thanks for pointing that out...  using -u to add targets should perhaps be added to the main page...

**Comment by DennisLfromGA** [comment]
@nukachicken,

Agreed.
It does briefly mention -
> Don't worry if you forget to include a target; you can always update the chroot later and add it. You can see the list of available targets by running sh ~/Downloads/crouton -t help.

But maybe it should go a little further and explain how.

-**DennisL**

**Comment by DennisLfromGA** [comment]
@zguithues,

> Thanks for pointing that out... using -u to add targets should perhaps be added to the main page... 

[Done.](https://github.com/dnschneid/crouton/blob/master/README.md#i-want-to-open-my-desktop-in-a-window-or-a-tab-but-i-dont-have-the-xiwi-targetxmethod) 👍 

*Hope this helps,*
-**DennisL**

**Comment by nukachicken** [comment]
Here it is, figured it out.

(xenial)[REDACTED]@localhost:~$ croutonversion
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: arm64
xmethod: xorg
targets: xiwi,xfce-desktop
host: version 9592.85.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:02:10 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes

**Comment by DennisLfromGA** [comment]
@nukachicken,

Just trying to clear up a few things...

The output above shows just the 'xorg' target/xmethod.
1. Are you trying to launch xfce and it's failing?
2. Are you trying to do a crouton update and it's failing?
3. Are you trying to add the 'xiwi' target/xmethod and it's failing?

Once we know what you're running into, we can dig deeper.

*Hope this helps,*
-**DennisL**

**Comment by nukachicken** [comment]
The output shown in the original post results from running "sudo sh ~/Downloads/crouton -n xenial -t xiwi -u"; that is, attempting to add the xiwi target. However, attempting to update it will yield the same error, as it keeps trying to install the same package.

**Comment by DennisLfromGA** [comment]
@nukachicken,

Okay, seems we've had problems with `xserver-xorg-video-dummy` on ARM devices in the past on previous releases, here's a report from crouton's author/developer -
- Installing xiwi on precise on ARM fails #2822

And here's another current one -
- Cannot install xiwi on Chromebook Flip C100 #3204 

One possible workaround is to manually install `xserver-xorg-core` and `xserver-xorg-video-dummy` first, then add 'xiwi'.

If you try that please let us know how it goes since it may help others - either way.

*Hope this helps,*
-**DennisL**

**Comment by nukachicken** [comment]
I am completely new to Linux and am kind of starting from scratch on how I can manually install those two. Crouton doesn't seem to offer anything to help me install these specific packages: the most specific target I can hit is xorg, which results in the same error. 

I've found that I can find and download specific packages browsing online and using the command wget. However, installing these packages is another matter: suggestions online such as apt-get and dpkg seem to be for different contexts than my little Chrome OS shell. What do I use to put the package in?

**Comment by nukachicken** [comment]
Oh, I've discovered I can use the -T flag to target a specific file. That may work. Will find the specific ARM file and see if I can do it

EDIT: Never mind. I feel like I've led myself down a path of useless expenditure and will wait for guidance

chronos@localhost ~/Downloads $ sudo sh crouton -T xserver-xorg-core_1.18.3-1ubuntu2_arm64.deb -u
/usr/local/chroots/xenial already exists; updating it...
Enter encryption passphrase for xenial: 
Preparing chroot environment...
/home/chronos/user/Downloads/xserver-xorg-core_1.18.3-1ubuntu2_arm64.deb: 1: Syntax error: newline unexpected

**Comment by DennisLfromGA** [comment]
@nukachicken,

> I am completely new to Linux and am kind of starting from scratch on how I can manually install those two. 

You'll need to get into the chroot -

> `sudo enter-chroot`

Then install the packages using `apt` or `apt-get` -

> `sudo apt install xserver-xorg-core xserver-xorg-video-dummy`

There are tons of resources on the internet that will help you learn more about Linux.

*Hope this helps,*
-**DennisL**

**Comment by Samtarkras** [comment]
Thanks, this solved my problem which seemed to be exactly the same as Nukachicken's

**Comment by nukachicken** [comment]
Works like a charm. Installing the packages manually from inside the chroot solves the problem, thanks.

**Comment by DennisLfromGA** [comment]
*Great!*

Leaving this issue open since **'Fix xserver-xorg-legacy issue with dummy package #3380'** is still under review and has not yet merged.

-**DennisL**

**Comment by razrjk** [comment]
This resolved my issues as well.  Very nice way to run Linux on my Samsung Chromebook Plus along with all the Android apps.

**Comment by jywarren** [comment]
> `sudo apt install xserver-xorg-core xserver-xorg-video-dummy`

This worked perfectly for me as well, on `hana` mediatek chromebook while upgrading my `crouton` install. Thank you! 🎉
