### ISSUE TITLE
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

### ISSUE THREAD

**Issue by peepo** [dnschneid/crouton#3368]
Version 62.0.3195.0 (Official Build) canary (64-bit)
ASUS C200M

System has been working fine, but after freeze & reboot: WiP #3025

/tmp/Xorg.crouton.1.log
[Xorg_crouton_1.txt](https://github.com/dnschneid/crouton/files/1251901/Xorg_crouton_1.txt)

$ sudo enter-chroot -n xenial
Entering /mnt/stateful_partition/crouton/chroots/xenial...
$ sudo apt remove xserver-xorg-legacy  // #3310 #2875
....
Package 'xserver-xorg-legacy' is not installed, 

 $ sudo startkde -n xenial
...
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
...
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership

" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

$ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: kde
host: version 9874.0.0 (Official Build) canary-channel squawks 
kernel: Linux localhost 4.4.79-11523-g797702bdfae8 #1 SMP PREEMPT Thu Aug 24 03:05:42 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by peepo** [comment]
maybe related to #2926
tried:
sudo sh ~/Downloads/crouton -u -n xenial
result unchanged.

**Comment by dwaindibbly** [comment]
i'm having this problem now! it's not related because... well...
![screenshot 2017-08-31 at 12 37 02](https://user-images.githubusercontent.com/16360233/29921336-1f9b5336-8e49-11e7-8b6a-e0bf5b8df79e.png)

probably to do with the following:

`Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist`

**Comment by senlyu** [comment]
also have this problem after I update chromeOS.



chronos@localhost / $ sudo startunity
.........
X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-15976-g75b344ab7870 #1 SMP PREEMPT Mon Aug 28 11:13:29 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=af91e370-fefe-c440-aa5f-aa0c75384420/PARTNROFF=1 hashtree=PARTUUID=af91e370-fefe-c440-aa5f-aa0c75384420/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=b35c22516e2ce65efbbff8a62889d6e94a7fbeea salt=1d5fdcf5c8d59d29f792976bffe990dec263f91ff22271458f48f5d10b3e7570" noinitrd vt.global_cursor_default=0 kern_guid=af91e370-fefe-c440-aa5f-aa0c75384420 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 17 July 2017  05:05:12PM
xorg-server 2:1.18.4-0ubuntu0.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Aug 31 10:44:25 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

chronos@localhost / $ sudo enter-chroot -n xenial croutonversion
crouton: version 1-20170830174419~master:0b3ec2c2
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 9887.0.0 (Official Build) dev-channel edgar 
kernel: Linux localhost 3.18.0-15976-g75b344ab7870 #1 SMP PREEMPT Mon Aug 28 11:13:29 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by c-dante** [comment]
Also getting this now.
```
Entering /mnt/stateful_partition/crouton/chroots/xfce...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 5 03:03:41 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=c40e2bed-36a9-154b-ac0a-42a5db64df9b/PARTNROFF=1 hashtree=PARTUUID=c40e2bed-36a9-154b-ac0a-42a5db64df9b/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=3cbdb8286f0d9acdf6a33f11d52170a375984826 salt=dbfc84a5ff629ffeb8fd54e70b51ea7979a2bfe810af661bfc6f34811df86d45" noinitrd vt.global_cursor_default=0 kern_guid=c40e2bed-36a9-154b-ac0a-42a5db64df9b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 17 July 2017  05:05:12PM
xorg-server 2:1.18.4-0ubuntu0.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Sep  9 02:27:45 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xfce...
```

**Comment by dwaindibbly** [comment]
@c-dante try updating the chroot now with the newest version of crouton.

**Comment by c-dante** [comment]
@dwaindibbly Yep -- thanks! solve'd

**Comment by DennisLfromGA** [comment]
@peepo, 

Maybe see if a crouton update might resolve your issue too.

*Hope this helps,*
-**DennisL**

**Comment by c-dante** [comment]
Updating crouton then the release worked like a charm. Thanks!
