### ISSUE TITLE
PSA - Beta Channel ChromeOS v61 breaks crouton without xiwi

### ISSUE THREAD

**Issue by zguithues** [dnschneid/crouton#3369]
Sorry I didn't save an output of `sudo edit-chroot -all`

My chromebook (Toshiba Chromebook2 swanky) which is in the beta channel, updated to ChromeOS v61 yesterday.  Immediately after, when launching a crouton that doesn't use xiwi, i got a blank screen.  The key combination to switch back to ChromeOS did not work, i was forced to hold down the power to turn off.

I tested with a fresh official crouton, I power washed, i tried other targets, nothing worked.  Only when i had the xiwi target installed and used the crouton extension was I able to actually use the chroot's x.

I switched to the Stable Channel (v60), and crouton worked per normal.   I switched to Dev Channel(v62), crouton also worked per normal.  After testing both, i returned to Beta Channel (v61), and had the same blank screen issue.

I tried looking through logs, but nothing jumped out at me.

I'm going to switch to the Dev channel for now, and re-setting up my chroots.  I just wanted to report in-case others experience it.  I'm not sure if it's device specific, or an issue with ChromeOS v61 globally.

If requested, prior to setting it back up under Dev Channel, i can switch back to Beta Channel and run `sudo edit-chroot -all` and post the output.

**Comment by DennisLfromGA** [comment]
@zguithues,

I have a lulu, Dell Chromebook 13, that upgraded to version 61 yesterday -

> Google Chrome	61.0.3163.51 (Official Build) beta (64-bit)
Platform	9765.31.0 (Official Build) beta-channel lulu
Firmware Version	Google_Lulu.6301.136.57
ARC	4279895

I haven't seen any other reports of this yet, I launched three different desktops in 'xorg' and had no problem.
Mine is using a much older 3.14 kernel compared to yours on 4.4 so it may be it's device specific.
Since the issue is on M61 only for you and seems to be fixed in M62 I guess your workaround may be the best course of action. 

Sounds like it'll work itself out but thanx for reporting it since others may run into this and now have a way around it.

*Hope this helps,*
-**DennisL**

**Comment by Asternitix** [comment]
@zguithues #3310's solution should fix the problem. Thanks for PSA in the header.

**Comment by DennisLfromGA** [comment]
@Asternitix,

Glad you got it fixed.
With no mention of what release or desktop was having issues, it's just a shot in the dark.

-**DennisL**

**Comment by rsriniv** [comment]
I too have Toshiba CB2 on the beta channel.

I too have the same issue as  @zguithues - after my CB updated to M61, I get a blank screen and a hard freeze. Ctrl-Shft-Alt back/forward do not work.

Tried the #3310 "fix", but that didn't work either.

Using the xiwi target does work, but video is very laggy and unwatchable.

Unfortunately, as I have to do a hard reboot, I cannot access the log file of the "sudo startxfce4" command.

Being a newbie, I have no suggestions - hoping the next beta build will resolve the issue!!

**Comment by zguithues** [comment]
@Asternitix I'm very aware of that issue, and have commented on it in the past.  It was related to x not starting at all.  ChromeOS remains responsive, and the chroot shuts down on it's own.

This new issue results in the chroot loading to a blank screen, and ChromeOS completely locking up.  The only way out that i have found is a hard reboot.

**Comment by zguithues** [comment]
I'm happy to report that the update to Beta Channel today fixed this issue!
Version 61.0.3163.70 beta starts xfce4 without issue!

@rsriniv while crouton stuff works just fine in the dev channel, i'm currently experiencing graphical glitches throughout chrome os, so i'm going back to beta channel.

**Comment by Asternitix** [comment]
@zguithues thanks!

**Comment by Asternitix** [comment]
@zguithues #3372 is pretty weird.

**Comment by zguithues** [comment]
I'm closing this, as the Beta Channel is working again.
