### ISSUE TITLE
Debian Stretch gives a mysterious message.

### ISSUE THREAD

**Issue by Asternitix** [dnschneid/crouton#3372]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: beta
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/beta...
crouton: version 1-20170825164243~master:6af640de
release: stretch
architecture: amd64
xmethod: xorg
targets: gnome-desktop,gnome,extension
host: version 9592.71.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Jul 27 00:04:59 PDT 2017 x86_64 GNU/Linux
freon: yes
#### Please describe your issue:
When startgnome is run this error message is given:
Entering /mnt/stateful_partition/crouton/chroots/beta...
Unknown username "geoclue" in message bus configuration file

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-3-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Jul 27 00:04:59 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=84de0146-4580-ca4f-823c-989c25105b57/PARTNROFF=1 hashtree=PARTUUID=84de0146-4580-ca4f-823c-989c25105b57/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=678204cbba46b8ad7ee4f033691fbe11a833d104 salt=475c61b6682e9441f2e7ffe37e2cb2e38283084af1e2993424a01692ff6e2d65" noinitrd vt.global_cursor_default=0 kern_guid=84de0146-4580-ca4f-823c-989c25105b57 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 07 July 2017  06:14:06AM
xorg-server 2:1.19.2-1+deb9u1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Aug 26 08:42:02 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/beta...
#### If known, describe the steps to reproduce the issue:
install the stretch chroot with gnome-desktop and extension targets
run startgnome

**Comment by Asternitix** [comment]
#3310 solution solves this.

**Comment by Asternitix** [comment]
What does this message mean?
"Unknown username "geoclue" in message bus configuration file"

**Comment by zguithues** [comment]
Unfortunately, I don't think this is related to #3369.  I'm much more familiar with ubuntu flavors than debian.  I'd recommend trying to install the same targets on xenial to make sure that crouton is working properly with your chromebook and chrome os version.  If that works, then it must be something that changed in debian.

Good luck tracking it down!

**Comment by shelleyvadams** [comment]
@Asternitix Have you tried creating a chroot with only the `gnome` target, which provides only the basic setup with just a few applications? 

[GeoClue][1] is a geolocation service used by [Maps][2] and various other stuff that's part of the complete Gnome desktop. That's why I wonder if there could be a problem with the `gnome-desktop` target, which installs many more applications.

The message you asked about,
> Unknown username "geoclue" in message bus configuration file

probably means that `geoclue` appears as a username somewhere in the configuration file for the message bus, but the user `geoclue` doesn't exist.

[1]: https://www.freedesktop.org/wiki/Software/GeoClue/
[2]: https://wiki.gnome.org/Apps/Maps

**Comment by Asternitix** [comment]
@shelleyvadams  yeah, I tried that, how do I remove geoclue from the configuration file?

**Comment by radumas** [comment]
>Unfortunately, I don't think this is related to #3369. I'm much more familiar with ubuntu flavors than debian. I'd recommend trying to install the same targets on xenial to make sure that crouton is working properly with your chromebook and chrome os version. If that works, then it must be something that changed in debian.

I have `xenial` installed, 
```
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/devbox...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xorg
targets: unity,extension
host: version 10176.22.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-16352-g01e32a3522ff-dirty #1 SMP PREEMPT Tue Dec 19 22:22:39 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

and I get the same error message as OP. 

Though I have to say that the chroot _works_ (mostly). Though there are some display issues over time as I switch between the chroot and ChromeOS:
 - certain letters stop appearing 
 - terminal emulator displays contents beneath until I select the window and scroll up and down.

Hope this helps?

**Comment by knuesel** [comment]
Regarding the "geoclue" message, it might be a bug in the `iio-sensor-proxy` package that should depend on the `geoclue-2.0` package. To get rid of the error message you can install `geoclue-2.0`. Another option is to edit the file `/etc/dbus-1/system.d/net.hadess.SensorProxy.conf` and comment-out the part that refers to the user geoclue.

**Comment by radumas** [comment]
Installing `geoclue-2.0` worked for me!
