### ISSUE TITLE
What are the steps to be taken after moving a chroot to a sd card and you need to powerwash the chormebook and then use the chroot as well?

### ISSUE THREAD

**Issue by Sandaru-Tissera** [dnschneid/crouton#3376]
I have installed Xenial (Ubuntu 16) to my Chromebook and then I moved it to my SD card. I need to power wash my Chromebook. But I need to use the chroot after I power wash as well. What are the steps I should take before I power wash and the steps to be taken after I power wash.

**Comment by DennisLfromGA** [comment]
@Sandaru-Tissera,

After a powerwash you'll need to re-install the 'host-bin' files to launch your desktop and other things.
So you will need to enter something like this:

- `sudo sh ~/Downloads/crouton -b -p "/media/removable/SD Card/"`

'crouton' will then find your chroot and restore the pertinent files to your `/usr/local/bin/` directory.

After that, just launch your desktop with something like: 

- `sudo startxfce4 -c "/media/removable/SD Card/chroots/"`

And substitute `startxfce4` with the desktop start script you installed in your chroot if it's different.

*Hope this helps,*
-**DennisL**

**Comment by Sandaru-Tissera** [comment]
I did as you told me so but (Check screenshot)
It didn't work.
![screenshot 2017-10-19 at 8 35 18 pm](https://user-images.githubusercontent.com/31498818/31778030-6f3ae54c-b4a4-11e7-86ee-2bab8081a127.png)

According to what I think, maybe the OS doesn't recognize any of the chroot commands and I thought so as (Check screenshot) the crosh system replies to the command 'enter-chroot' as 'sudo: enter-chroot: command not found' 
What am I supposed to do??
I have installed many Linux programs and I don't want to waste time installing them all over again. 
Please tell me a solution as soon as possible.
Thanks,

Cheers,
Sandaru Tissera.

**Comment by DennisLfromGA** [comment]
@Sandaru-Tissera,

Sorry, my instructions weren't quite correct, forget this:

~'crouton' will then find your chroot and restore the pertinent files to your /usr/local/bin/ directory.~

In your case, I think the host-bin scripts will be restored to '/media/removable/SD Card/bin/'
So you'll need to launch them with something like:

- sudo "/media/removable/SD Card/bin/startxfce4"

Please let me know if this works.

Thanx,
-**DennisL**

**Comment by Sandaru-Tissera** [comment]
I don't think that the problem is with that either. I still think that the
bash doesn't understand and chroot command. It still says
command-not-found. And I still tried your command and it says the same
"command not found". Please tell me a fix when you find one.

**Comment by DennisLfromGA** [comment]
@Sandaru-Tissera,

I just noticed your command to restore the host-bin files specifies an incorrect path I believe.
crouton's '-p' option needs the **root directory** of your '/bin' & '/chroots' subdirectories, see below -
```
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
```
You entered: `sudo sh ~/Downloads/crouton -b -p "/media/removable/Linux/chroots/"`
it should have been: `sudo sh ~/Downloads/crouton -b -p "/media/removable/Linux"`

*Hope this helps,*
-**DennisL**

**Comment by Sandaru-Tissera** [comment]
@DennisLfromGA,

Did all what you told me to but still didn't work. ( Screenshot given)
![screenshot 2017-10-21 at 10 03 29 am](https://user-images.githubusercontent.com/31498818/31848076-74277e5e-b647-11e7-9d01-80850a5f180b.png)
Still what I think is that bash doesn't understand the commands.
Another thing what I thought is if the default directory is "/mnt/stateful_partition/crouton/chroots" , then can't we copy it to that directory???
![screenshot 2017-10-21 at 10 02 30 am](https://user-images.githubusercontent.com/31498818/31848084-bbdc450e-b647-11e7-9121-cc99e35d2cb7.png)
**_"In your case, I think the host-bin scripts will be restored to '/media/removable/SD Card/bin/'
So you'll need to launch them with something like:

sudo "/media/removable/SD Card/bin/startxfce4" "_**
On your second reply as above, you said that the host-bin scripts will be restored to '/media/removable/SD Card/bin/' so then can't we copy this to "/mnt/stateful_partition/crouton/chroots"??

Looking forward for your reply and comments.
Thanks,

Cheers,
Sandaru Tissera.

**Comment by DennisLfromGA** [comment]
@Sandaru-Tissera,

Just try: `sudo /media/removable/Linux/bin/startunity`

*Hope this helps,*
-**DennisL**

**Comment by Sandaru-Tissera** [comment]
@DennisLfromGA ,

Tried it and it contains a very unexpected result.
![screenshot 2017-10-22 at 12 11 45 am](https://user-images.githubusercontent.com/31498818/31854896-c7a1e9cc-b6bd-11e7-93bc-a9dd0f04df88.png)
It says permission denied.
I used sudo bash as well but still permission denied. So what is the highest applicable privilege given more than sudo bash???
Looking forward for your reply.
Thanks,

Cheers,
Sandaru Tissera.

**Comment by DennisLfromGA** [comment]
@Sandaru-Tissera,

Okay a slight tweak, try: `sudo sh /media/removable/Linux/bin/startunity`

*Hope this helps,*
-**DennisL**

**Comment by Sandaru-Tissera** [comment]
@DennisLfromGA ,

Thank you very much for your support. The command worked. So I guess that even if you powerwash your chromebook, you can just run the chroot by this command right??? Thank you very much for your support.

Regards,
Sandaru Tissera.

**Comment by DennisLfromGA** [comment]
@Sandaru-Tissera,

Glad I could help.

The real problem is the external media doesn't always get mounted with exec permissions.
One workaround that doesn't require using 'sh' is described here -
- [Can't execute files from ext4-formatted SDcard #3423](https://github.com/dnschneid/crouton/issues/3423#issuecomment-337694385)

*Hope this helps,*
-**DennisL**

**Comment by Sandaru-Tissera** [comment]
@DennisLfromGA,

One last thing. I noticed that it kind of lagged so much that you can't do any work with it. Any solutions???
