### ISSUE TITLE
I am having trouble loading the chroot after Ioading the chroot after I did......

### ISSUE THREAD

**Issue by Sandaru-Tissera** [dnschneid/crouton#3377]
I typed the command sudo enter-chroot -c /media/removable/Linux/chroots ( My sd card directory) and updated the repository typing sudo apt update.
Thats all I basically did. and after that Ubuntu wont load. Check screenshot.

Please help me fix this ASAP.
![screenshot 2017-08-31 at 4 13 34 pm](https://user-images.githubusercontent.com/31498818/29919559-71b597da-8e67-11e7-807d-da94d104169a.png)

**Comment by dwaindibbly** [comment]
i'd look at #2926 for a bit first. but if i am right you are on dev channel. is it correct? because i see weirdness like what happens here:
![screenshot 2017-08-31 at 12 37 02](https://user-images.githubusercontent.com/16360233/29921918-740e6fa0-8e4b-11e7-8403-409272c41025.png)

**Comment by Sandaru-Tissera** [comment]
Yep you are right I am on a dev channel.
