### ISSUE TITLE
Crouton broken after update in BETA and DEV channels

### ISSUE THREAD

**Issue by MarkisDev** [dnschneid/crouton#3379]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170830174419~master:0b3ec2c2
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9765.48.0 (Official Build) beta-channel reks 
kernel: Linux localhost 3.18.0-15946-gcf8b2a86d44d #1 SMP PREEMPT Mon Aug 28 22:02:58 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
ntering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-3-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-15946-gcf8b2a86d44d #1 SMP PREEMPT Mon Aug 28 22:02:58 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=01404395-734a-064d-a389-0572b8234470/PARTNROFF=1 hashtree=PARTUUID=01404395-734a-064d-a389-0572b8234470/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=d86cd06923cc28b2e5e8c71bb61f70bc2d83f97c salt=b5440e1686cc96644d9a456f4b3df19e55a128cedd2564bf00d7349c6d93fbd8" noinitrd vt.global_cursor_default=0 kern_guid=01404395-734a-064d-a389-0572b8234470 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 07 July 2017  06:22:09AM
xorg-server 2:1.19.3-2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Aug 31 19:25:39 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
I get this every time. Previously I was using crouton with stable-channel and then moved to dev-channel. Today I installed the latest update from dev-channel and since then crouton is broken. I moved to Beta-channel and still the issue persists. Please help me out!

**Comment by DennisLfromGA** [comment]
Likely dup of #2875
