### ISSUE TITLE
How can I get access to ChromeOS from chrooted environment?

### ISSUE THREAD

**Issue by koji-kojiro** [dnschneid/crouton#3384]
Hi,

I added the following line at the end of my `.bashrc`. 

```
enter-chroot; exit
```
So, I can start and exit chroot directly from crosh.
However, I've lost access to ChromeOS ...
How can I fix this?

Thanks.

**Comment by DennisLfromGA** [comment]
@koji-kojiro,

*Out on a limb are you? ;-)*

Have you tried accessing a shell from **VT2** using <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F2/-></kbd> ?
If it still exhibits the same behavior as user 'chronos' then try the following -

- [ ] open **VT2**
- [ ] login in as user 'root'
- [ ] ` cd /home/chronos/`
- [ ] `ls -ld u-*`
- [ ] find the mounted user directory among those listed above
- [ ] cd into the mounted user directory
- [ ] edit the `.bashrc` script to remove `enter-chroot; exit`
- [ ] exit and open a shell from your account, you should be able to now

Please let us know how it goes.

*Hope this helps,*
-**DennisL**

**Comment by koji-kojiro** [comment]
@DennisLfromGA 
Perfect! Thanks a lot!

**Comment by DennisLfromGA** [comment]
Awesome!
Thankx for letting us know too.

-**DennisL**
