### ISSUE TITLE
Alt+Up == PgUp

### ISSUE THREAD

**Issue by mdi** [dnschneid/crouton#3387]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20170901092920~master:0216f9d1
release: stretch
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,x11,audio
host: version 9592.85.0 (Official Build) stable-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Aug 21 20:13:32 PDT 2017 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/stretch as another instance is using it.
```

#### Please describe your issue:

Pressing `Alt`+`Up` sends `Prior` (`PgUp`). Verified using `xev`. I've tried with/without keyboard target (same behavior). I don't have any custom xbindkeys or Xmodmap config.

**Comment by eyqs** [comment]
Chrome OS always maps Alt+Up and Alt+Down to Prior and Next, and I couldn't find any way to disable or change those keyboard shortcuts.

**Comment by eyqs** [comment]
Chrome OS always maps Alt+Up and Alt+Down to Prior and Next, and I couldn't find any way to disable or change those keyboard shortcuts. What app are you using that needs Alt+Up?

**Comment by mdi** [comment]
VS Code. I know I can reconfigure the keybindings for it, but I was hoping to avoid doing that if possible.

**Comment by eyqs** [comment]
I think it'd be easier to rebind the shortcuts in VS Code than in Chrome OS, though someone else may have a smart solution.

**Comment by mdi** [comment]
Installing the `xorg` target fixed this.
