### ISSUE TITLE
Question: Backup without unmounting?

### ISSUE THREAD

**Issue by tve** [dnschneid/crouton#3392]
Is there anything to the chroot environment that would make a backup from a live chroot (without unmounting) problematic? I mean, I understand that it's a tar of a live filesystem, I just wonder whether there's something particular. A -force flag to backup allowing it would be nice.

**Comment by dnschneid** [comment]
It just makes the backup less reliable and trustworthy, really.  All sorts of things can go wrong:

* If you have temporary mounts, any files or directories hidden by that mount won't be backed up.  tar of course should be run with --one-filesystem, which I believe it already is in `edit-chroot`.  So at least you don't have to worry about it trying to back up external media.
* Temporary sockets and whatnot may be backed up, or tar may skip them and spit out errors
* If your chroot is encrypted, it's possible that the encrypted store may be in an inconsistent state, which can result in particularly nasty random data corruption (I've run into this on .git directories...)
* If an application is saving some data, you may end up with the old version, the new version, both, an inconsistent mix of new and old files, or some empty files in the tarball.

Yes, we could probably add a --force flag to give users the option of shooting themselves in the foot, but you can already do that by just running tar yourself...
