### ISSUE TITLE
crash after starting Chroot on Samsung Chromebook

### ISSUE THREAD

**Issue by Derpjohn** [dnschneid/crouton#3394]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: arm64
xmethod: xorg
targets: touch,xfce
host: version 9592.85.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:02:10 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial.
```
Okay so I am new to crouton, ubuntu and really everything to do with coding. I have a samsung chromebook plus and have been having a bunch of problems trying to get it started. Whenever i do sudo startxfce4 my computer crashes and reboots. I have tried all of the work-arounds and most of the time they come down to using xiwi. The issue I have with this is I type "sudo sh -e ~/Downloads/crouton -u -t xiwi -n xenial" and this is what happens:

xorg is already the newest version (1:7.7+13ubuntu3).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xorg-video-abi-20
                            Depends: xserver-xorg-core (>= 2:1.17.99.902)
E: Unable to correct problems, you have held broken packages.

I have tried to solve this by using apt-get but when i do sudo apt-get whatever whatever it says apt-get is an unknown command. 

I really have no clue where to go from here so any suggestions would be awesome. I have tried reinstalling and everything I have seen on the forums so I don't know where to go from here, Thank you.

#### If known, describe the steps to reproduce the issue:
install using, sudo sh -e ~/Downloads/crouton -t touch,xfce     Start using sudo startxfce4

**Comment by JulienAFrozenMiddle** [comment]
Same machine. Everything was working well up to now running things within xiwi, but a recent attempt to install a gnome client went bad and even broke my capacity to run xfce. 

Some xfce packages that were already installed go bad.. taking a quick look, it seems that they are armhf. The ChromebookPlus comes out as arm64 and so during install, the armhf packages are held back.

Downgraded to the pre-update backup, things are back to normal. But I am guessing the OP does not have that option. Later today, when I have a bit more time, I will try to see if I can get things to go badly again and post the output.

**Comment by JulienAFrozenMiddle** [comment]
I stand corrected: not adding the gnome target, things go bad but xiwi still works.Below are the first few errors I get when I issue the command
`sudo sh ~/Downloads/crouton -u -n xenial`
This armhf vs arm64 thing has been annoying in many instances..


Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lubuntu-desktop:armhf : Depends: abiword:armhf but it is not going to be installed
                         Depends: alsamixergui:armhf but it is not going to be installed
                         Depends: apport-gtk:armhf but it is not installable
                         Depends: blueman:armhf but it is not going to be installed

**Comment by Derpjohn** [comment]
update: I was able to get the package downloaded the problem was I wasn't in my chroot when using apt-get. So now I was able to install xiwi. I will update again if I get it to work finally.

**Comment by Derpjohn** [comment]
HUZZAH I got it to work. I just am having trouble cycling screens now.
