### ISSUE TITLE
Unable to locate package kodi

### ISSUE THREAD

**Issue by kvngtass** [dnschneid/crouton#3395]
chronos@localhost / $ sudo edit-chroot-all
sudo: edit-chroot-all: command not found

I tried to install ubunto on my samsung chromebook xe 303 and went fine until...

E: Unable to locate package kodi
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

I inputed this...

chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce,cli-extra,extension,keyboard,xbmc,chrome
Google Chrome does not yet have an ARM build. Installing Chromium instead.

that also came up and I thought it was wierd
Thanks in advance

**Comment by zguithues** [comment]
It looks like you're using an arm Chromebook.  All of my chromebooks are x86, so i'm more familiar with the packages in those repositories...

I'm fairly certain that Kodi exists in Ubuntu arm, but perhaps only in the latest LTS, Xenial.  Try installing with `-r xenial` or just drop the `-r`, as crouton defaults to xenail/16.04.

Also, kodi isn't going to run properly using the extension/xiwi targets.  While they work great with desktops like xfce, they don't provide the needed hardware acceleration for kodi.  I recommend creating Kodi in a separate chroot.  I always create using this command: `sudo sh ~/Downloads/crouton -t kodi -n kodi`

Please report back whether installing kodi works with xenial.  If so, i'll update the target to fail gracefully on arm/trusty.

**Comment by kvngtass** [comment]
chronos@localhost / $ sudo sh ~/Downloads/crouton trusty -t xfce,cli-extra,extension,keyboard,xbmc,chrome
Downloading latest crouton installer...
######################################################################## 100.0%
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: xenial,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.


This came up after

**Comment by zguithues** [comment]
sorry i wasn't more clear...

in your original command, you had `-r trusty` which is telling crouton to install Ubuntu 14.04 Trusty.  When i said to remove the `-r`, i meant to remove the entire section `-r trusty`.

Also, you will not get good performance with kodi/xbmc if you use the `extension` target.

**Comment by DennisLfromGA** [comment]
@kvngtass,

I just installed it and got great results with just: `sudo sh ~/Downloads/crouton -n kodi -t kodi`

Granted it only runs kodi and no other desktop but it's a small footprint and starts easily with `sudo startkodi`

*Hope this helps,*
-**DennisL**

**Comment by kvngtass** [comment]
idk what happened I'm a total noob so

chronos@localhost / $ sudo startkodi
Entering /mnt/stateful_partition/crouton/chroots/kodi...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-87-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Aug 21 19:59:18 PDT 2017 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=3192238f-1bd4-b540-81be-5db733381d39/PARTNROFF=1 hashtree=PARTUUID=3192238f-1bd4-b540-81be-5db733381d39/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=bd637843748b4dced79fb42b3f1530c2b095a0cd salt=c2d46d30104b959c316cb433f1fbee2e5bcd8e87eb419e9bc8655ba0e089e672" noinitrd vt.global_cursor_default=0 kern_guid=3192238f-1bd4-b540-81be-5db733381d39  
Build Date: 25 July 2017  01:30:24PM
xorg-server 2:1.19.3-1ubuntu1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Sep  7 18:01:04 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1504774864.526762 sender=:1.11 -> destination=:1.82 serial=1729 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
method return time=1504774865.232440 sender=:1.11 -> destination=:1.83 serial=1730 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kodi...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/kodi...

**Comment by zguithues** [comment]
ok, this is much closer...  though i'm not sure exactly what's causing the issue, I see a couple things...

`MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos`

Looks like a video driver problem

`(EE) AddScreen/ScreenInit failed for driver 1`

is probably also related to the video driver...

Please confirm, you installed this chroot using `sudo sh ~/Downloads/crouton -n kodi -t kodi`

If so, I'd like to make sure that xorg works on your laptop by installing just xfce.  Please run this command to create a new chroot with just xfce
`sudo sh ~/Downloads/crouton -n xfce -t xfce`
Then start with `sudo startxfce -n xfce`

Let me know if this starts into the desktop, or if it also gives the same X server errors.

@dnschneid  any other ideas?
does mesa work on the samsung chromebook xe 303?

**Comment by kvngtass** [comment]
yes I used chronos@localhost / $ sudo sh ~/Downloads/crouton -n kodi -t kodi

**Comment by kvngtass** [comment]
chronos@localhost / $ sudo startxfce -n xfce
sudo: startxfce: command not found

should i do 
sudo startxfce4
instead

**Comment by zguithues** [comment]
@kvngtass Yes!  `sudo startxfce4 -n xfce`

Sorry for my typo!

**Comment by kvngtass** [comment]
chronos@localhost / $ sudo startxfce4 -n xfce
Entering /mnt/stateful_partition/crouton/chroots/xfce...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-87-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Aug 21 19:59:18 PDT 2017 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=3192238f-1bd4-b540-81be-5db733381d39/PARTNROFF=1 hashtree=PARTUUID=3192238f-1bd4-b540-81be-5db733381d39/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=bd637843748b4dced79fb42b3f1530c2b095a0cd salt=c2d46d30104b959c316cb433f1fbee2e5bcd8e87eb419e9bc8655ba0e089e672" noinitrd vt.global_cursor_default=0 kern_guid=3192238f-1bd4-b540-81be-5db733381d39  
Build Date: 25 July 2017  01:30:24PM
xorg-server 2:1.19.3-1ubuntu1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Sep  9 17:35:09 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1504946109.232594 sender=:1.11 -> destination=:1.106 serial=3902 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
method return time=1504946110.070830 sender=:1.11 -> destination=:1.107 serial=3903 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xfce...

Wonder what all these errors are

**Comment by zguithues** [comment]
Ok, well this is definitely a larger issue with crouton & your chromebook model.  I think it's related to the graphics drivers.

Please post the output of `sudo edit-chroot -all` (when you ran it before, you missed the space after the t in `chroot`)
That will provide the info that the experts will need to diagnose further.

**Comment by kvngtass** [comment]
chronos@localhost / $ sudo edit-chroot -all
name: kodi
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kodi...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xorg
targets: kodi
host: version 9592.85.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 21 19:59:18 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kodi...
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170901092920~master:0216f9d1
release: trusty
architecture: armhf
xmethod: xorg
targets: xfce,cli-extra,extension,keyboard,xbmc,chrome
host: version 9592.85.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 21 19:59:18 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: xfce
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xfce...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9592.85.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Aug 21 19:59:18 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xfce...

**Comment by rcamp48** [comment]
did anyone ever solve the problem of running kodi on samsung xe303c12 chromeboks?
