### ISSUE TITLE
can't cycle/change my operating system samsung chromebook plus

### ISSUE THREAD

**Issue by Derpjohn** [dnschneid/crouton#3396]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: arm64
xmethod: xiwi
targets: xiwi,touch,xfce
host: version 9592.85.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:02:10 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
```

#### Please describe your issue:
I try using ctrl+alt+f1/f2 and it brings me to a screen asking for a localhost login. I put in chronos and my password i set and it just brings me a prompt saying something along the lines of chronos@localhost: / $ 
From here i can just type commands but that is not what I want. I have seen people say to do ctrl+shit+alt+f1/f2 but that does nothing when i press it. I have also tried in the terminal emulator to type "startx" and it will say waiting for xserver to respond for about 3 minutes then it will say it gave up because it took too long to respond. 

#### If known, describe the steps to reproduce the issue:
sudo startxfce4 
ctrl+alt+forward 
ctrl+alt+refresh

**Comment by DennisLfromGA** [comment]
@Derpjohn,

Not quite sure what the problem might be so let's start from scratch -

- Make sure you login to your account when the Chromebook boots up at the sign-in screen.
- Then press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>t</kbd> and enter `shell`
- Then enter `sudo startxfce4 -n xenial`

By default, the desktop should open in a window.
Once the desktop opens you should be able to use the 'full screen' / <kbd>F4</kbd> key to toggle between 'full screen' & a 'window'.
The 'switch window' / <kbd>F5</kbd> key will switch between Chrome OS and your chroot.

On the Chrome OS side you can also use the 'crouton integration' extension to the right of the omnibar to get into your chroot -

![ci switch](https://user-images.githubusercontent.com/3418772/30125448-6d6bdbd2-9306-11e7-95df-33d831efc0a6.png)

And open your chroot from the 'crouton integration' icon in the taskbar -

![ci tb](https://user-images.githubusercontent.com/3418772/30125516-9d40d98e-9306-11e7-8400-083418e9184d.png)

Finally, there are other options to open your desktop using the `start*` script optons -
- `sudo startxfce4 -X xiwi-fullscreen`
- `sudo startxfce4 -X xiwi-tab` (my favorite)

*Hope this helps,*
-**DennisL**

**Comment by Derpjohn** [comment]
yeah I thanks you really cleared up the issue. thanks.
