### ISSUE TITLE
Mouse encryption "done" immediately

### ISSUE THREAD

**Issue by jonathonbaron** [dnschneid/crouton#3397]
```
Generating keys (move the mouse to generate entropy)...
done
Installing trusty-amd64 chroot to /usr/local/chroots/trusty
Downloading latest debootstrap...
2017-09-07 14:35:31 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [70034] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
```
Apologies in advance for my low comprehension---probably quite a lot of dumb language in here.

I've been trying to set up Crouton with Ubuntu, but have had issues. The first time I went through the process, my machine froze part of the way through. I attempted to wipe everything and start over by exiting and restarting dev mode, but I suspect that that failed.

So, the proximate problem: as soon as I enter my passphrase, I get the above output (`Generating keys (move the mouse to generate entropy)...` and then, immediately, `done` before I even have a change to move the mouse around.

Again, sorry for the silly line of questioning and probably idiotic approach(es) here!

Please help!

**Comment by jonathonbaron** [comment]
Perhaps I should also note that I had the Crouton extension still installed upon reboot.

**Comment by dnschneid** [comment]
Don't worry too much about that.  crouton uses /dev/random to generate encryption keys, which requires a non-zero entropy pool.  User input (i.e., mouse movement) is one way to generate entropy if there's not enough, but network traffic (such as opening tabs) is a good source as well.

If the system has been up for a while when you go to create an encrypted chroot, there may be enough entropy that it finishes instantly.  If not, then it'll pause there, and the "move the mouse" hint (which isn't necessarily the best way of refilling the entropy pool) at least stops people from sitting there staring at the screen and waiting...

**Comment by jonathonbaron** [comment]
Thanks so much for the detailed reply. How informative! If I may ask: does
the rest of the output I posted look standard, as well? All of the
"failed"s concerned me.

**Comment by dnschneid** [comment]
Naw, InRelease failures are fine.

**Comment by jonathonbaron** [comment]
Cool, thanks a lot; I'm looking forward to playing around in the system!
Take it easy, and thanks again!
