### ISSUE TITLE
nano, enter-chroot flashing

### ISSUE THREAD

**Issue by mickbeck** [dnschneid/crouton#3398]
```
Please paste the output of the following command here: sudo edit-chroot -all
____________________________________________________________________________
name: manifest
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/manifest...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9460.60.0 (Official Build) stable-channel peach_pi 
kernel: Linux localhost 3.8.11 #1 SMP Mon Jun 5 16:51:44 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/manifest...
_____________________________________________________________________________
```

#### Please describe your issue
 I use xfce4 with the "enter-chroot" command, once in, I run nano but the whole terminal starts 
flashing, but not all at once, it's like some sort of segmented flashing where parts of the terminal screen/text will flash out of sync of other parts of the terminal/text. 

Thanks for taking the time to read this.

#### If known, describe the steps to reproduce the issue:
shell
sudo enter-chroot -n manifest 
sudo apt-get install nano 
nano *

**Comment by mickbeck** [comment]
I also have an issue with firefox crashing immediately recently, if this is related.

**Comment by icecream95** [comment]
Compiling [ncurses](https://www.gnu.org/software/ncurses/ncurses.html) from source should fix this issue.

**Comment by mickbeck** [comment]
it seems to have been fixed
