### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by LiamPlayz** [dnschneid/crouton#3399]
```
Please paste the output of the following command here: sudo edit-chroot -all
```everytime i go to start unity it changed to xenial 

#### Please describe your issue:

same thing i said 
#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
@LiamPlayz,

Not sure there's a problem. 'unity' is a desktop target that runs in the default 'xenial' Ubuntu release.

If there's a problem plese show us the output of `sudo edit-chroot -all` and then give details about your issue.

*Hope this helps,*
-**DennisL**
