### ISSUE TITLE
Can's Start Kali-Rolling Linux Tried Almost All Options

### ISSUE THREAD

**Issue by anonymouseprogrammer** [dnschneid/crouton#3400]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170901092920~master:0216f9d1
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9901.5.0 (Official Build) dev-channel relm 
kernel: Linux localhost 3.18.0-16002-g2644da09535f #1 SMP PREEMPT Mon Sep 4 22:14:23 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: xfce
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xfce...
/usr/local/bin/enter-chroot: 511: cannot create /run/crouton/mnt/stateful_partition/crouton/chroots/xfce/etc/crouton/name: Directory nonexistent
Unmounting /mnt/stateful_partition/crouton/chroots/xfce...

#### Please describe your issue:
There seems to be many issues with this. I know I'm entering the right passwords and everything, and I've update it a thousand time along with cleaning it, but to no prevail. I can still open the command line (enter-chroot) but that's the extent. I'm wondering if it has to do with my downloading of GalliumOS as a dual-boot (even though I've turned it off with the dev_boot_legacy command). I don't know what's wrong, especially since I've downloaded it before with this same user in this same device (I just powerwashed it.)

#### If known, describe the steps to reproduce the issue:
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-3-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-16002-g2644da09535f #1 SMP PREEMPT Mon Sep 4 22:14:23 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=8d604fd7-3aa1-5e43-82d2-76f129201e1d/PARTNROFF=1 hashtree=PARTUUID=8d604fd7-3aa1-5e43-82d2-76f129201e1d/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=4f2d44204e2e91bb3a444dbafe7229294ba0145e salt=71afe38f959fb4c13de4debffb2520ecc879bfe10ed1ecc1de971da2e132cdff" noinitrd vt.global_cursor_default=0 kern_guid=8d604fd7-3aa1-5e43-82d2-76f129201e1d add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 07 July 2017  06:22:09AM
xorg-server 2:1.19.3-2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Sep 10 21:28:43 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by anonymouseprogrammer** [comment]
Okay, a little embarrassed here. I decided to just test some things I thought would work (thinking I probably wouldn't have gotten anything), but miraculously found the answer. The folder the Kali-Linux startup is held in is /usr/bin/startxfce4. Since I had access to the chroot still, this is the steps it took to start it:
crosh> **_shell_**
chronos@localhost / $ **_sudo enter-chroot_**
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
(kali-rolling)user@localhost:~$ **_sudo su_**
[sudo] password for user: **_(Input pass-code)_**
(kali-rolling)root@localhost:/home/user# **_/usr/bin/startxfce4_**
This would force the folder to open, therefore forcing Linux to open up. I have given these steps to a friend with a different Chromebook and a different distribution and it still worked, all he had to do was replace "xfce4" with his environment, "kde".
I hope those who come across this can find the answer works for them (as it should!)

**Comment by DennisLfromGA** [comment]
@anonymouseprogrammer, **_et all_**,

**PLEASE do not** launch `startxfce4` *in the chroot* as **root**, it will hose your permissions and many things will fail after that.

If you've done that tho, you can fix it with the following -
```
sudo enter-chroot
sudo chown -R 1000:1000 "$HOME"
```
----
 I believe the original issue is caused by the installation of 'xserver-xorg-legacy'.
A workaround for it is here: https://github.com/dnschneid/crouton/issues/3310#issuecomment-313692575

A [PR](https://github.com/dnschneid/crouton/pull/3380) is in the works but not yet approved and merged.

*Hope this helps,*
-**DennisL**

**Comment by oneshasappleton** [comment]
whenever I do a sudo startxfce4 to boot linux on my chromebook this is the error that  i am getting ,after which the laptop screen turns dark for two seconds and returns to chrome help is wanted.


chronos@localhost /usr/local $ sudo startxfce4
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-109-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=922500af-600e-5c4b-998e-daf87f04a622/PARTNROFF=1 hashtree=PARTUUID=922500af-600e-5c4b-998e-daf87f04a622/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=3bfc672b009a3247d3cd8399a74f96ac53188553 salt=306427720380043295ff7f5e5f7ef68a81138057901e316471bd1520719b78b2" noinitrd vt.global_cursor_default=0 kern_guid=922500af-600e-5c4b-998e-daf87f04a622  
Build Date: 04 September 2020  03:36:48PM
xorg-server 2:1.19.6-1ubuntu4.1~16.04.4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Oct 22 22:21:25 2020
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1603423285.559485 sender=:1.9 -> destination=:1.89 serial=4041 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1603423286.048767 sender=:1.9 -> destination=:1.91 serial=4042 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by oneshasappleton** [comment]
it doesnt want to boot in linux it just makes the screen dark then exit .

**Comment by traviszim** [comment]
chronos@localhost / $ sudo  enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/xenial...
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

Not sure what happened but even after powrwashing and redownloading im still having issues
