### ISSUE TITLE
startgnome not working

### ISSUE THREAD

**Issue by HenricHintze** [dnschneid/crouton#3401]
```
When trying to use sudo startgnome (kali-rolling gnome install) I briefly see the kali desktop after which it terminates and I see the following:

#### Please describe your issue:

Enter encryption passphrase for kali-rolling: 
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-3-amd64 x86_64 Debian
Current Operating System: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:11:06 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=fe41eb3b-bf42-624b-bbb1-a8a18942ab4b/PARTNROFF=1 hashtree=PARTUUID=fe41eb3b-bf42-624b-bbb1-a8a18942ab4b/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=6d335d76e811108f013dec2ed772fc5f132efe22 salt=715e538d9ca36cd2c7fb04f3967220b51af52d8343c90bc9a8fd3075083cdcd1" noinitrd vt.global_cursor_default=0 kern_guid=fe41eb3b-bf42-624b-bbb1-a8a18942ab4b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.preliminary_hw_support=1  
Build Date: 07 July 2017  06:22:09AM

xorg-server 2:1.19.3-2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Sep 11 21:11:49 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1505157109.693101 sender=:1.10 -> destination=:1.83 serial=1291 reply_serial=2
   boolean true
crouton: version 1-20170831074915~master:d11442d5
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: gnome
host: version 9592.85.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:11:06 PDT 2017 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
method return time=1505157119.040088 sender=:1.10 -> destination=:1.84 serial=1292 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/kali-rolling...

Any idea what is causing this?

**Comment by dontpokethebear3893** [comment]
Same issue with ubuntu artful
(artful)achilles@localhost:~$ startgnome

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-92-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Tue Sep 12 13:57:41 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=177dfb36-8aad-b945-9240-35c479dc770a/PARTNROFF=1 hashtree=PARTUUID=177dfb36-8aad-b945-9240-35c479dc770a/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=ba0aa37191df5a292f822ac6994b70b6cec171e3 salt=4ea4f443279648fb55366e94951bab304c7cacd2b947b6b847063a9c6e01ee20" noinitrd vt.global_cursor_default=0 kern_guid=177dfb36-8aad-b945-9240-35c479dc770a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 30 August 2017  11:54:15AM
xorg-server 2:1.19.3-1ubuntu6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Sep 18 13:34:37 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1505756078.441516 sender=:1.11 -> destination=:1.129 serial=6107 reply_serial=2
   boolean true
crouton: version 1-20170901092920~master:0216f9d1
release: artful
architecture: amd64
xmethod: xorg
targets: gnome,extension,keyboard
host: version 9592.94.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Tue Sep 12 13:57:41 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
method return time=1505756082.277313 sender=:1.11 -> destination=:1.130 serial=6108 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.

I wonder if crouton could officially support a wayland session for ubuntu gnome being that a fedora-wayland session is proven to work with the crouton method
