### ISSUE TITLE
black screen, newbie (I apologize in advance)

### ISSUE THREAD

**Issue by moh230** [dnschneid/crouton#3402]
```
Please paste the output of the following command here: sudo edit-chroot -all
```name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: arm64
xmethod: xorg
targets: kde
host: version 9592.85.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:02:10 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes

#### Please describe your issue:
resulted in blackscreen. black screen stays for 15 seconds or so and then restarts the chromebook back to where i can disable developer mode and where i press "ctrl+d" to enter chromeos.


#### If known, describe the steps to reproduce the issue:

Installed fresh chroot via sudo sh ~/Downloads/crouton -t kde
I ran sudo startkde

NOTE: I tried installing xfce4 and got the same result, that is why i tried kde right after.
ALSO: I installed xfce4 for the first time ever on my chromebook and it worked perfectly fine. I then started messing around and tried installing archlinux and tried a few other tutorials on youtube. I am not sure if maybe there are some files that are interfering with this process. I have disabled developer mode and re-enabled it (to wipe the system). Is there another way to make sure there are no files interfering with my installation?

sorry again for the long post, just starting with linux for the first time

**Comment by zguithues** [comment]
This sounds a lot like issues i was having in the beta channel on my swanky (toshiba chromebook 2).  It was resolved with an updated build about a week later...

If you want to try other things, try with the beta and dev channels to see if the same problem exists.   You also might want to try just powerwashing it, since you think it may be related to messing around with archlinux.

Good luck!

**Comment by moh230** [comment]
I just tried with the beta channel , same issue, going to try dev channel soon and see what happens

**Comment by moh230** [comment]
okay so I just tried xfce with trusty instead of xenial (if that even makes any sense)

I do not get the black screen but I do get this error 
-------------------------------------------------------------------------------------------
sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic aarch64 Ubuntu
Current Operating System: Linux localhost 4.4.70-11339-gb1947ccd8d12 #1 SMP PREEMPT Tue Sep 5 12:32:55 PDT 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=5595f841-6d62-3949-abc5-424dd3d2155e/PARTNROFF=1 hashtree=PARTUUID=5595f841-6d62-3949-abc5-424dd3d2155e/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=4bb2c0cb103a67bcfeca09cbfcb6c316065bc589 salt=511f6e1ffb885a070d9b873ef8ab9008b2ddbc9b4c73d77ebf2f1d6fb11a4355" noinitrd vt.global_cursor_default=0 kern_guid=5595f841-6d62-3949-abc5-424dd3d2155e  
Build Date: 20 July 2017  07:12:02PM
xorg-server 2:1.15.1-0ubuntu2.9 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Sep 12 15:52:55 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x44) [0x5693f3fc94]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/trusty...
----------------------------------------
Can anyone guide me on how to fix the xorg issue? (if that again makes any sense)

**Comment by zguithues** [comment]
man, I wish i could provide more assistance, but there seems to be an issue with your chromebook and xorg.  Your chromebook is arm64, all mine are x86; so there is little troubleshooting i can do on my end...

Try with the xiwi target and install the crouton chrome extension.  This bypasses xorg and runs xfce4 (or other) in a window within chromeOS.

You can add the target to an existing chroot by executing `sudo sh ~/Downloads/crouton -n CHROOTNAME -u -t xiwi` (i think)

But it might be best to just make a new one with `sudo sh ~/Downloads/crouton -n test1 -t xfce,xiwi`
then launch with `sudo startxfce4 -n test1`

Good Luck!

Hopefully one of the resident wizards can provide further insight... @DennisLfromGA @dnschneid

**Comment by waldoxhm** [comment]
same issue with my Lenovo yoga n23，arm64 also，get a blank screen after startx

**Comment by moh230** [comment]
Hey guys, Yeah so to be honest I sold my chromebook plus and just bought the pro. The ARM rockchip processor has been a pain. I got galliumOS installed on my chromebook pro now and everything has been amazing.

**Comment by aleifuu** [comment]
Hi @moh230 , I've got a Chromebook Pro. installed crouton on it ( xenial ). however when running edit-chroot -all , I got the architecture recognized as 

`architecture: arm64`

the crouton works though, but there is separate issue that im opening in this discussion also
