### ISSUE TITLE
"Shell" is not working!

### ISSUE THREAD

**Issue by LiamPlayz** [dnschneid/crouton#3403]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
hello everyone so when i type the shell command is says crosh> shell
ERROR: unknown command: shell can anyone help me this is really annoying!

**Comment by PMaxDS** [comment]
You need to change your chromebook to Developer Mode for the command to work. The procedure is device dependant.

A simple google search like "*chromebook model* developer mode will give you results. Follow the procedure and the shell command will work as intented after that.

**Comment by LiamPlayz** [comment]
@PMaxDS its in developer mode....

**Comment by DennisLfromGA** [comment]
@LiamPlayz,

Can you login as user 'chronos' in VT2 (via <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F2</kbd>) ?

-**DennisL**

**Comment by LiamPlayz** [comment]
@DennisLfromGA nope doesnt work

**Comment by LiamPlayz** [comment]
the thing wont even open D:

**Comment by DennisLfromGA** [comment]
@LiamPlayz,

Even though you think you are still in Developer mode it sounds like you may not be any longer.
Do you get something similar to the following and have to press <kbd>ctrl</kbd>+<kbd>D</kbd> to boot into the login screen -

![image](https://user-images.githubusercontent.com/3418772/30345960-29cf0c7c-97d5-11e7-8c59-de41aa0e7241.png)
If not, then take a look at these links for more info. -
- [Developer Information for Chrome OS Devices](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices#goog-ws-list-table) - click on the Model name of your device
- [Poking around your Chrome OS Device](https://www.chromium.org/chromium-os/poking-around-your-chrome-os-device)

*Hope this helps,*
-**DennisL**

**Comment by LiamPlayz** [comment]
@DennisLfromGA i re downloaded it looks like some glitch happends with my laptop working fine now thanks very much

**Comment by DennisLfromGA** [comment]
👍
