### ISSUE TITLE
Can't switch to eu keyboard layout

### ISSUE THREAD

**Issue by NWuensche** [dnschneid/crouton#3405]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: x11
host: version 9765.53.0 (Official Build) beta-channel celes 
kernel: Linux localhost 3.18.0-15946-gcf8b2a86d44d #1 SMP PREEMPT Tue Sep 5 12:37:30 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I want to switch my keyboard layout in crouton with `setxkbmap eu`. However, I can't write Umlaute (like ü) when I press LeftAlt + u. This works on Linux normally

#### If known, describe the steps to reproduce the issue:
I just installed i3.

**Comment by GrimGrape** [comment]
One command I found helped me switch the default of the system to Dvorak, and had options for modifiers in later options was: 
`sudo dpkg-reconfigure keyboard-configuration linux dpkg keyboard config` 

This let me change layout with arrow keys, and the third screen should have an 'accented keys' option to add in for you. Best of luck.
