### ISSUE TITLE
USB drives automount under xiwi but not under xorg

### ISSUE THREAD

**Issue by beadsland** [dnschneid/crouton#3406]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,xorg,unity,touch,extension,xiwi
host: version 9460.60.1 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-14582-g2fa17b5c810f #1 SMP PREEMPT Tue Jun 6 21:33:50 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

Recently switched from using "startunity -X xiwi" to "startunity -X xorg" as my goto for launching crouton.

_[Aside: I found that xiwi insisted on opening to a full-screen black screen, that necessitated an F11 (or, rather, F4) every launch—resizing the window to half-screen width window—followed by expanding the window back to full width. (Full screen would then display semi-reliably.) It got tedious. Going the xorg route, by comparison, just opens full screen without any extra keystrokes/mouse clicks to be able to see what I'm doing. I haven't opened an issue about the xiwi black screen as it appears this is already a known problem under other open issues.]_

Discovered that while both xiwi and xorg throw a nuisance "Unable to mount XX GB Volume \ Not authorized to perform operation." whenever a USB drive is inserted, they nonetheless handle the volume differently.

**xiwi**:  nuisance error; _yet volume automounts_ -- opens in nautilus, appears as new entry under /media/removable.

**xorg**: nuisance error. That's it. _No automount._ Selecting in nautilus just throws same error again. No new entry under /media/removable. 

I can, of course, manually mount the volume that xorg fails to automount. But that does seem to be swapping one bit of tedium (keystrokes/mouse clicks to get a viewable screen on xiwi launch) for another (manually mount every USB drive inserted under xorg).

I've tried various ubuntu troubleshooting steps modifying various polkit files, on the off chance these'd fix the issue, to no avail. Suggestions welcome. I'm happy to work in either xorg or xiwi, just so long as I can launch into one or the other and just have things work. So if the solution is a fix to the xiwi black screen on launch, that'd be just as good.

#### If known, describe the steps to reproduce the issue:

chronos@localhost ~ $ sudo startunity -X xiwi
* F11 (i.e., F4) to get past black screen
* resize window to get out of half-width window
* insert USB drive
* click past nuisance error
* drive is mounted and useable

VS.

chronos@localhost ~ $ sudo startunity -X xorg
* immediately visible full screen without any fiddling around
* insert USB drive
* click past nuisance error
* drive is not mounted
* open terminal and mount manually

**Comment by EnderNightLord-ChromeBook** [comment]
Sorry I can't help you with this but they may have different actions

**Comment by DennisLfromGA** [comment]
@beadsland,

There are a couple of other ways to launch your desktop using xiwi, you might try these -

- fullscreen: `sudo startxfce4 -X xiwi-fullscreen`
- in a tab: `sudo startxfce4 -X xiwi-tab`

*Hope this helps,*
-**DennisL**
