### ISSUE TITLE
Removed a file from Downloads folder inside chroot, trash empty, but space not freed

### ISSUE THREAD

**Issue by BramVandendriessche** [dnschneid/crouton#3407]
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /media/removable/SD Card/chroots/trusty...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,touch,extension
host: version 9592.94.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Tue Sep 12 14:04:44 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

Hi,

I have a Acer Chromebook R11, and have installed a chroot (trusty, xfce4) on an SD-card. 
I removed a tarball of a chroot backup using Thunar, (about 4GB) located in the (shared) Downloads folder from inside the chroot. It did not appear in the trash of the chroot, but the space is not freed on the Chromebooks SSD.

Any suggestions about how to recover the "lost" disk space?

-Bram

**Comment by DennisLfromGA** [comment]
@BramVandendriessche,

Does the space free up after a reboot?

*Hope this helps,*
-**DennisL**

**Comment by BramVandendriessche** [comment]
@DennisLfromGA 

I tried that, didn't work.
Sorry, should've mentioned that!

-Bram

**Comment by DennisLfromGA** [comment]
@BramVandendriessche,

> I removed a tarball of a chroot backup using Thunar, (about 4GB) located in the (shared) Downloads folder from inside the chroot. 

If it's in the 'shared Downloads folder' then you should be able to do it in a crosh shell session outside of the chroot. You may have to prefix the command with 'sudo, something' like -

chronos@localhost ~ $ `sudo rm ~/Downloads/trusty-2017*.tar.gz`

*Hope this helps,*
-**DennisL**

**Comment by BramVandendriessche** [comment]
Hi @DennisLfromGA,

The file cannot be removed, since it is not located in the Downloads folder, nor the trash anymore.

-Bram

**Comment by DennisLfromGA** [comment]
@BramVandendriessche,

When you said 'shared Downloads folder' I assumed you meant `~/Downloads`.
If that's not the case then I'm not sure what you were referring to or where your file may still exist.

Sorry,
-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
In the chromeOS downloads press show hidden files then delete trash.1000 that is where all the rubbish goes in ubuntu so it was created by ubuntu

**Comment by BramVandendriessche** [comment]
@DennisLfromGA,
I was referring to the Downloads folder of ChromeOS, which is shared with the chroot in ~/Downloads.

@EnderNightLord-ChromeBook, 
Thanks, your suggestion did work!

-Bram

**Comment by DennisLfromGA** [comment]
@BramVandendriessche,

> I was referring to the Downloads folder of ChromeOS, which is shared with the chroot in ~/Downloads.

Hmmm, so was I.

-**DennisL**
