### ISSUE TITLE
Cannot read from external CD drive.

### ISSUE THREAD

**Issue by PatheticLoser** [dnschneid/crouton#3409]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9592.94.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 4.4.64-09102-g03fd4b865e5b #1 SMP PREEMPT Tue Sep 12 13:58:40 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
I have an external USB DVD drive. It is detected by the system, and if I put a disc in, that is detected too. However, if I try to read from the disc, it can't. The error message states 'Failed to mount "Audio Disc".', with the subtitle stating 'Cannot find drive /dev/sr0.'
The file in question does exist, however the icon has an 'X' with a red background in the bottom corner. I am new to Ubuntu, so I don't know the significance of the symbol. I tried reading the file with MousePad, the error includes the message "permission denied", which I think has something to do with it.

I have tried with a regular audio CD and the CD-Rom for Quake II. Both have been detected as "Audio Disc". I have tested the drive to work on my (Windows) PC.

#### If known, describe the steps to reproduce the issue:
1. Plug in disc drive.
2. Eject drive, insert disc.
3. Click "Audio CD" on the sidebar of the file manager.
4. Receive error message.

I have no idea if this is just a standard issue with Ubuntu, if it is, I'm sorry for wasting your time.

**Comment by octopusnz** [comment]
Hey there. Not too sure if this is crouton specific - you could try manually mounting the drive.

Have a look at this search result - and maybe refine the search on askubuntu a bit: 

https://askubuntu.com/questions/99202/how-to-mount-a-cd-rom-from-a-usb-cd-rom-drive-on-ubuntu-10-04-3-server

**Comment by EnderNightLord-ChromeBook** [comment]
Chromebooks are not used to this happening so im not really sure about this
