### ISSUE TITLE
debian stretch x dont work

### ISSUE THREAD

**Issue by mjonsson1986** [dnschneid/crouton#3411]
i install crouton with: sudo sh ./crouton -r stretch -t core,cli-extra,x11
after that i install mate manually
in the chroot
sudo apt-get install mate-desktop-environment-core
it have worked before

**Comment by EnderNightLord-ChromeBook** [comment]
Stange it should work i have done this myself but maybe you have done somthing wrong? Check again or reinstall 
Might have somthing to do with your chrome version?

**Comment by mjonsson1986** [comment]
Seems a apt-get upgrade solved it..

Skickades från E-post för Windows 10

Från: Ender
Skickat: den 8 oktober 2017 09:23
Till: dnschneid/crouton
Kopia: mjonsson1986; Author
Ämne: Re: [dnschneid/crouton] debian stretch x dont work (#3411)

Stange it should work i have done this myself but maybe you have done somthing wrong? Check again or reinstall
Might have somthing to do with your chrome version?

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
