### ISSUE TITLE
Applications opened using xiwi look weird

### ISSUE THREAD

**Issue by ryanwhite04** [dnschneid/crouton#3412]
```
sudo /media/removable/SD\ Card/bin/edit-chroot -all
name: cli
encrypted: no
Entering /media/removable/SD Card/chroots/cli...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce,x11,xorg,xiwi,touch,audio,gtk-extra,lxde,cli-extra,keyboard,extension
host: version 9765.53.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-15946-gcf8b2a86d44d #1 SMP PREEMPT Tue Sep 5 12:34:38 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /media/removable/SD Card/chroots/cli as another instance is using it.
```

When I open Applications such as Praat and Xterm in windows or tabs using Xiwi there is a weird bright white background which seems to show different tabs overlayed, kind of see-through, also the mouse leaves copies of itself behind. I'm not sure how to describe it other than it looks really weird and it's hard to tell what I'm clicking on.

![screenshot 2017-09-18 at 3 09 44 pm](https://user-images.githubusercontent.com/5384154/30531867-7da6654a-9c83-11e7-8baa-ef98f4bd2bed.png)

When I go into screenshot mode, it goes back to normal.

The command i'm running from the shell is:
```
sudo sh /media/removable/SD\ Card/bin/enter-chroot -n cli -b xiwi xterm
```

Also, I just found out that the problem only occurs when I have the "Night Light" on.
So if anyone else is having this issue, just turn the nightlight off.

**Comment by icecream95** [comment]
Weird. I have the same issue. When Night Light was introduced, this wasn't a problem, though the mouse cursor was stuck in "Chrome OS mode".
An interesting thing I found is that when recording a screencast, slight cursor trails appear (in the screencast), but not long ones.

```name: artful
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/artful...
crouton: version 1-20170826174936~master:6af640de
release: artful
architecture: armhf
xmethod: xorg
targets: lxde,xorg,xiwi,core
host: version 9765.53.0 (Official Build) beta-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 5 12:28:44 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/artful...```

**Comment by icecream95** [comment]
This also happens in high contrast mode.

**Comment by danopia** [comment]
I've noticed that the affected regions aren't even impacted by Night Light. They shine through the yellowness of the rest of the screen, and seem a little extra blue as well. I experience the glitch only on GNOME's native dialogs, so only part of the xiwi window - the main window (Atom) is always fine.

When toggling off night mode, the dialog snaps back to normal as soon as the animation is complete. Screenshots of the glitched region also render incorrectly, but a different kind of incorrect. The icons are all artifacted and low-bitdepth.

Badly compressed photograph of a screenshot and real deal side-by-side https://i.imgur.com/mlGbTtA.png

**Comment by brillout** [comment]
Did someone manage to workaround this? Disabling night light only works partially.
