### ISSUE TITLE
New chroot installation(s) failing on Acer C7 (parrot)  - for me.

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#3413]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
< no chroot installed >
```

#### Please describe your issue:
I'm getting stuck installing any new chroot on my Acer C7. It seems to bomb out after extracting 'adduser'.
I haven't been able to pin down what's going wrong. Here's the tail end of the installation log -
```
I: Retrieving zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Validating zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting adduser...
+ set +e
+ trap - INT HUP TERM 0
+ umount -l /tmp/crouton.zmA
+ rm -rf --one-file-system /tmp/crouton.zmA
+ sh /tmp/crouton.0H7/host-bin/unmount-chroot -y -c /usr/local/chroots -- kodi
+ ls+ wc -l
-a /usr/local/chroots/kodi
+ [ 2 -le 3 ]
+ rm -rf /usr/local/chroots/kodi
+ rm -f /tmp/crouton-dedup.XL2
+ stty echo
+ rm -rf --one-file-system /tmp/crouton.0H7
```
I can't figure out how to get more diagnostics.

The full crouton intallation log is here: [crouton.kodi.log](https://pastebin.com/HSVsrUGN)
Also, if it helps, a full dmesg log is here: [dmesg.log](https://pastebin.com/tz8xbKT1)

It seems to trigger [this trap](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L469) used when bootstrapping fails.

#### If known, describe the steps to reproduce the issue:
Install a new 'kodi' chroot with: `sudo sh ~/Downloads/crouton -n kodi -t kodi`

Note: As far as I can tell it happens on any release with any target(s) so it's not specific to 'kodi'.

----
If someone can show me how to get more diagnostics out I'd appreciate that too.

Thanx to anyone for any insight.
-**DennisL**

**Comment by dnschneid** [comment]
Looks like this issue was hit years ago as well: #1628, although no conclusions there.

The "extractor" line is extremely suspicious: `I: Chosen extractor for .deb packages: dpkg-deb`.  I believe that should be `ar`, not `dpkg-deb`.

So...why is debootstrap picking dpkg-deb?

**Comment by dnschneid** [comment]
Looks like debootstrap recently changed their extractor detection to use their own `in_path` instead of `type` ([commit](https://anonscm.debian.org/cgit/d-i/debootstrap.git/tree/functions#n8)).  I can only assume that dpkg-deb exists but is missing some prerequisites to be actually useful -- it's either that or somehow that code is totally broken in a non-obvious (to me) way.

It looks like there's an EXTRACTOR_OVERRIDE environment variable you can set to force `ar`.

Try adding `EXTRACTOR_OVERRIDE=ar` to the [debootstrap call](https://github.com/dnschneid/crouton/blob/master/installer/ubuntu/bootstrap#L75).

**Comment by DennisLfromGA** [comment]
Hmmm, it failed at the same point, it looks like it still tried to use `dpkg-deb`

```
I: Retrieving zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Validating zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting adduser...
+ set +e
+ trap - INT HUP TERM 0
+ umount -l /tmp/main.sh.zx5
+ rm -rf --one-file-system /tmp/main.sh.zx5
+ sh ./installer/../host-bin/unmount-chroot -y -c /usr/local/chroots -- kodi
+ ls -a /usr/local/chroots/kodi
+ wc -l
+ [ 2 -le 3 ]
+ rm -rf /usr/local/chroots/kodi
+ rm -f /tmp/main.sh-dedup.c9h
+ stty echo
```

Here's where I added the variable -
```
# Grab the release and drop it into the subdirectory
echo 'Downloading bootstrap files...' 1>&2
PATH="$newpath" DEBOOTSTRAP_DIR="$tmp" EXTRACTOR_OVERRIDE=ar $FAKEROOT \
    "$tmp/debootstrap" --foreign --arch="$ARCH" \
    "$RELEASE" "$tmp/$subdir" "$MIRROR" 1>&2
```

Thanx for the help,
-**DennisL**

**Comment by dnschneid** [comment]
Oops, sorry, that should be done via the --extractor parameter of 
debootstrap, not an environment variable.

That's what I get for only looking at a single source file...

**Comment by DennisLfromGA** [comment]
Also strange to me is that it seems to only be happening on my Acer C7 -

```
Google Chrome	63.0.3218.0 (Official Build) canary (64-bit)
Platform	9950.0.0 (Official Build) canary-channel parrot
Firmware Version	Google_Parrot.2685.37.0
```
It was also failing when I was on the dev channel. 

-**DennisL**

**Comment by dnschneid** [comment]
Does the rootfs have dpkg-deb for some reason?

**Comment by DennisLfromGA** [comment]
@dnschneid,

**_Wow, you're the man!_**

It got past the trap and is installing as I/we speak. 
Now to figure out why it's only happening on this and possibly other devices...

Thanx a million,
-**DennisL**

**Comment by DennisLfromGA** [comment]
@dnschneid,

> Does the rootfs have dpkg-deb for some reason?

Yup, I'm my own worst enemy it seems. 😕
I install and use `busybox` to get past some of Chrome OS'es omissions but it came back to bite me this time -
```
lrwxrwxrwx 1 root    root        22 Aug 27 02:43 dpkg-deb -> /usr/local/bin/busybox
```
I have `busybox` installed on my Dell Lulu too but it didn't link `dpkg-deb` for some (yet unknown to me) reason.

So long story short, I'll remove my local `dpkg-deb` link and all should be well.

Many thanx again,
-**DennisL**

**Comment by dnschneid** [comment]
It's probably worth adding the --extractor parameter to crouton, though.  It shouldn't have any negative consequences.

**Comment by DennisLfromGA** [comment]
Should it be set to 'ar' ?

I just noticed I have 'ar' linked too but it seemed to work.
```
lrwxrwxrwx 1 root root 22 Aug 27 02:43 ar -> /usr/local/bin/busybox
```
-**DennisL**

**Comment by dnschneid** [comment]
ar is correct.  busybox's is likely fine (it's a dead-simple archiver), but crouton ships with its own version that gets priority.

**Comment by EnderNightLord-ChromeBook** [comment]
Happend to me too I saw that it said dpkg-deb instead of ar thanks

**Comment by dnschneid** [comment]
Okay, well hopefully both of you will be saved from yourselves by the latest crouton :)

**Comment by DennisLfromGA** [comment]
No more busybox for this guy.
