### ISSUE TITLE
Can't start up

### ISSUE THREAD

**Issue by MrBreadWater** [dnschneid/crouton#3415]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I can't start up the Ubuntu desktop. Here is the output it gives me right after the screen goes black:

        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Sep 18 20:01:38 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1505790098.666869 sender=:1.11 -> destination=:1.55 serial=1295 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
method return time=1505790099.714811 sender=:1.11 -> destination=:1.56 serial=1296 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@MrBreadWater,

See if this guide helps: ['Common issues and reporting'](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**

**Comment by MrBreadWater** [comment]
I tried re-installing a few times before this, but I will retry using the intructions posted there. I will let you know how it goes

**Comment by MrBreadWater** [comment]
@DennisLfromGA That didn't work, any other suggestions?

**Comment by DennisLfromGA** [comment]
@MrBreadWater,

Please run `croutonversion` in your chroot and show us the output.

> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE)

Also, please post your `Xorg.crouton.log` file on pastebin.com, gist.github.com, etc. and give us the link .

-**DennisL**

**Comment by MrBreadWater** [comment]
> Please run croutonversion in your chroot and show us the output.

I am not sure how to do this. 

Here is a link to the pastebin: [https://pastebin.com/rQD6GfEm](https://pastebin.com/rQD6GfEm)

**Comment by DennisLfromGA** [comment]
@MrBreadWater,

1. `enter-chroot`
2. `croutonversion`

-**DennisL**

**Comment by MrBreadWater** [comment]
@DennisLfromGA 

Here you go:

crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9592.94.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Sep 12 13:52:25 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes

**Comment by DennisLfromGA** [comment]
@MrBreadWater,

A while back there were a number of 'blackscreen' issues relating to 'modesetting' that look a little similar to your issue -

> [ 13048.164] (EE) modeset(0): glamor initialization failed

- Black screen #2923
- chroots will no longer boot to gui after updating chrome OS to version 56.0.2924.9 dev (64-bit) https://github.com/dnschneid/crouton/issues/2917#issuecomment-267411158

But there was a PR merged to fix it -

- croutonxinitrc-wrapper: xorg target: kick the display on startup #3081

Your chroot seems up-to-date so you may be running into a little different issue.

If I were you, I'd try adding the 'xiwi' target/xmethod and use it when launching your 'xfce4' desktop.
If that works you could use it as a workaround and we could then work on this 'xorg' issue.

*Hope this helps,*
-**DennisL**

**Comment by MrBreadWater** [comment]
@DennisLfromGA 

Ok, I've did that, but what do I put for the chroot_app on startxiwi? I reinstalled it with xiwi this time, and used the startxiwi command, and it game me this: startxiwi [options] chroot_app [parameters] (along with a few other things, but they were just parameters). So my question is, what is the chroot_app?

**Comment by DennisLfromGA** [comment]
@MrBreadWater,

> I reinstalled it with xiwi this time...

You took the long way around, I said **add** the 'xiwi' target/xmethod but, never the less...

You start it the same way you always do but this time, since 'xiwi' is the default xmethod, it will use it instead of 'xorg', like so -

- To start in a window: `sudo startxfce4 -n xenial`
- To start in a fullscreen: `sudo startxfce4 -n xenial -X xiwi-fullscreen`
- To start in a tab: `sudo startxfce4 -n xenial -X xiwi-tab` *(my favorite)*

And if you want to use 'xorg' again instead, assumng you installed it too, use this -

- To start in a fullscreen: `sudo startxfce4 -n xenial -X xorg`

*Hope this helps,*
-**DennisL**

**Comment by MrBreadWater** [comment]
Sorry if I sound like an idiot, I am **not** well versed in this at all. I so appreciate your help on this. I had thought that startxiwi was the way to go, I was kind of just going on a whim though. I feel like I'm really close to getting this going, but, what does this error:

/mnt/stateful_partition/crouton/chroots/xenial does not contain target 'xfce'

mean? My guess is that it means that when I was reinstalling with xiwi, I messed something up and didn't install xfce. Can I just add it as a target (Like I should have done with xiwi in the first place)? If so, what would be the command to do that?

Thanks again!

**Comment by DennisLfromGA** [comment]
@MrBreadWater,

>  My guess is that it means that when I was reinstalling with xiwi, I messed something up and didn't install xfce. 

That's my guess too at this point but it's only a guess. To be sure tho, we'll need to see the output of:

`sudo edit-chroot -l xenial`

> Can I just add it as a target (Like I should have done with xiwi in the first place)? If so, what would be the command to do that?

Yes, you can add any target to an exisitng chroot with an update using the '-u' option.
To add 'xiwi' to an 'xenial' chroot with 'xorg' use this -

`sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

*Hope this helps,*
-**DennisL**

**Comment by MrBreadWater** [comment]
Here is the output: 

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xiwi
targets: xiwi
host: version 9592.94.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Sep 12 13:52:25 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@MrBreadWater,

Yup, as we expected there is trouble in River City. :)

Just add your xfce desktop target with an update like this -

`sudo sh ~/Downloads/crouton -n xenial -t xfce4 -u`

For the 'xiwi' xmethod you'll also need to install the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension from the Chrome Web Store.

If you want to add 'xorg' again to this chroot but leave 'xiwi' as the default xmethod then update it like this -

`sudo sh ~/Downloads/crouton -n xenial -t xiwi,xorg,xfce4 -u`

Once the update completes successfully you can start your chroot using the methods I showed above in https://github.com/dnschneid/crouton/issues/3415#issuecomment-331038413

*Hope this helps,*
-**DennisL**

**Comment by MrBreadWater** [comment]
@DennisLfromGA 

That worked. It said something about not being able to move a log file at first, and that kept it from starting up, but I went ahead and deleted it, and finally I got this working. Thanks so much!

**Comment by DennisLfromGA** [comment]
*Awesome* and your welcome.
