### ISSUE TITLE
Kali Linux on Asus Chromebook 201p

### ISSUE THREAD

**Issue by nishantrama** [dnschneid/crouton#3416]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20170901092920~master:0216f9d1
release: kali-rolling
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9460.73.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Jul 13 11:51:36 PDT 2017 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xiwi
targets: core,xiwi,keyboard,x11,cli-extra,extension
host: version 9460.73.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Jul 13 11:51:36 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
When I try and load Kali Linux through sudo startxfce4 I get the following:

Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Jul 13 11:51:36 PDT 2017 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=ef87c6d4-f576-754c-82ee-9df262c921aa/PARTNROFF=1 hashtree=PARTUUID=ef87c6d4-f576-754c-82ee-9df262c921aa/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=e223d5a96d097fa871de3a047a744ada018fbe00 salt=761a4fced57053f54f9fd14faaced478e70a63a0aa83a6a7e2ce32baf7fe181e" noinitrd vt.global_cursor_default=0 kern_guid=ef87c6d4-f576-754c-82ee-9df262c921aa  
Build Date: 07 July 2017  08:55:08AM
xorg-server 2:1.19.3-2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Sep 18 22:45:15 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

When I cat the log files I get the following:

[ 12658.876] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[ 12658.881] 
X.Org X Server 1.19.3
Release Date: 2017-03-15
[ 12658.881] X Protocol Version 11, Revision 0
[ 12658.881] Build Operating System: Linux 3.16.0-4-armmp-lpae armv7l Debian
[ 12658.881] Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Jul 13 11:51:36 PDT 2017 armv7l
[ 12658.881] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=ef87c6d4-f576-754c-82ee-9df262c921aa/PARTNROFF=1 hashtree=PARTUUID=ef87c6d4-f576-754c-82ee-9df262c921aa/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=e223d5a96d097fa871de3a047a744ada018fbe00 salt=761a4fced57053f54f9fd14faaced478e70a63a0aa83a6a7e2ce32baf7fe181e" noinitrd vt.global_cursor_default=0 kern_guid=ef87c6d4-f576-754c-82ee-9df262c921aa  
[ 12658.881] Build Date: 07 July 2017  08:55:08AM
[ 12658.881] xorg-server 2:1.19.3-2 (https://www.debian.org/support) 
[ 12658.881] Current version of pixman: 0.34.0
[ 12658.881]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[ 12658.881] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 12658.882] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Sep 18 22:45:15 2017
[ 12658.883] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 12658.883] (==) No Layout section.  Using the first Screen section.
[ 12658.883] (==) No screen section available. Using defaults.
[ 12658.883] (**) |-->Screen "Default Screen Section" (0)
[ 12658.883] (**) |   |-->Monitor "<default monitor>"
[ 12658.884] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[ 12658.884] (==) Automatically adding devices
[ 12658.884] (==) Automatically enabling devices
[ 12658.884] (==) Automatically adding GPU devices
[ 12658.884] (==) Max clients allowed: 256, resource mask: 0x1fffff
[ 12658.884] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[ 12658.884]    Entry deleted from font path.
[ 12658.884] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/100dpi/:unscaled,
        /usr/share/fonts/X11/75dpi/:unscaled,
        /usr/share/fonts/X11/Type1,
        /usr/share/fonts/X11/100dpi,
        /usr/share/fonts/X11/75dpi,
        built-ins
[ 12658.884] (==) ModulePath set to "/usr/lib/xorg/modules"
[ 12658.884] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[ 12658.884] (II) Loader magic: 0x35d11f60
[ 12658.884] (II) Module ABI versions:
[ 12658.884]    X.Org ANSI C Emulation: 0.4
[ 12658.884]    X.Org Video Driver: 23.0
[ 12658.885]    X.Org XInput driver : 24.1
[ 12658.885]    X.Org Server Extension : 10.0
[ 12658.942] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[ 12658.945] (II) xfree86: Adding drm device (/dev/dri/card1)
[ 12658.945] (II) no primary bus or device found
[ 12658.945] (II) LoadModule: "glx"
[ 12658.946] (II) Loading /usr/lib/xorg/modules/linux/libglx.so
[ 12658.974] (II) Module glx: vendor="NVIDIA Corporation"
[ 12658.974]    compiled for 4.0.2, module version = 1.0.0
[ 12658.974]    Module class: X.Org Server Extension
[ 12658.974] (II) NVIDIA GLX Module  340.102  Mon Jan 16 11:20:39 PST 2017
[ 12658.974] (==) Matched modesetting as autoconfigured driver 0
[ 12658.974] (==) Matched fbdev as autoconfigured driver 1
[ 12658.974] (==) Assigned the driver to the xf86ConfigLayout
[ 12658.975] (II) LoadModule: "modesetting"
[ 12658.975] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[ 12658.975] (II) Module modesetting: vendor="X.Org Foundation"
[ 12658.975]    compiled for 1.19.3, module version = 1.19.3
[ 12658.975]    Module class: X.Org Video Driver
[ 12658.975]    ABI class: X.Org Video Driver, version 23.0
[ 12658.976] (II) LoadModule: "fbdev"
[ 12658.976] (WW) Warning, couldn't open module fbdev
[ 12658.976] (II) UnloadModule: "fbdev"
[ 12658.976] (II) Unloading fbdev
[ 12658.976] (EE) Failed to load module "fbdev" (module does not exist, 0)
[ 12658.976] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[ 12658.977] (EE) 
Fatal server error:
[ 12658.977] (EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
[ 12658.977] (EE) 
[ 12658.977] (EE) 
Please consult the The X.Org Foundation support          at http://wiki.x.org
 for help. 
[ 12658.977] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[ 12658.977] (EE) 
[ 12658.977] (WW) xf86CloseConsole: KDSETMODE failed: Bad file descriptor
[ 12658.977] (WW) xf86CloseConsole: VT_GETMODE failed: Bad file descriptor
[ 12658.977] (EE) Server terminated with error (1). Closing log file.

#### If known, describe the steps to reproduce the issue:
Any help you can give much appreciated. have been banging my head against a wall for the last 2 days.

**Comment by DennisLfromGA** [comment]
@nishantrama,

You may be running into this issue: 
- Installing xserver-xorg-legacy (part of the kali-linux meta package) breaks startxfce4 #2875
See this issue comment for a possible workaround:
- can't startxfce4 (sid&stretch) https://github.com/dnschneid/crouton/issues/3310#issuecomment-313692575

*Hope this helps,*
-**DennisL**

**Comment by nishantrama** [comment]
@DennisLfromGA 
random it works now. I didnt do anything.... thanks for the info!!!

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
