### ISSUE TITLE
Updating chroot from USB.

### ISSUE THREAD

**Issue by Sandaru-Tissera** [dnschneid/crouton#3417]
Hi guys, Please help me out here.
I installed Ubuntu 16.04 Xenial and moved the chroot to my SDXC card in the chromebook.
It moved succesfully. However now I get the X server problems and so I found out that to fix this you could update the chroot with @farmerbb crouton script. I tried to do so but since my chroot is in the usb, I do not know the command in which I could do so. I also tried moving it back to the state... partition.... but they said it could only be moved to ext partitions.

Please reply me with a command in which I could update my chroot which is currently present in my SDXC card.

Thanks guys.

**Comment by DennisLfromGA** [comment]
@Sandaru-Tissera,

> However now I get the X server problems and so I found out that to fix this you could update the chroot with @farmerbb crouton script. I tried to do so but since my chroot is in the usb, I do not know the command in which I could do so.

Per @farmerbb's https://github.com/dnschneid/crouton/issues/3375#issuecomment-326399238 -
> Download the new crouton binary from my last post, unzip it, then run sudo sh ~/Downloads/crouton -u -n <chroot name> and it will update your existing chroot with the fixes.

The only thing you need to do differently is add the '-p' option to let crouton know where your chroot's parent folder is so it would be something like:

`sudo sh ~/Downloads/crouton -u -n <chroot name> -p </path/to/external/media/chroots/parent`

*Hope this helps,*
-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
Yes I was thinking the exactly same thing on this good job dennis
