### ISSUE TITLE
Unable to mount xenial.

### ISSUE THREAD

**Issue by bANNji** [dnschneid/crouton#3418]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce,touch
host: version 9592.96.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Sat Sep 16 09:58:36 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I am attempting to boot into my chroot | xenial

#### If known, describe the steps to reproduce the issue:
sudo startxfce4 | sudo enter-chroot xenial

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
-su: 21: Syntax error: Unterminated quoted string
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Crouton Version info

chronos@localhost / $ cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=23
CHROMEOS_ARC_VERSION=4328948
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={11130F0B-738A-C024-7A78-CF72D93B77AF}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={11130F0B-738A-C024-7A78-CF72D93B77AF}
CHROMEOS_RELEASE_BOARD=cyan-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=96
CHROMEOS_RELEASE_BUILDER_PATH=cyan-release/R60-9592.96.0
CHROMEOS_RELEASE_BUILD_NUMBER=9592
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=60
CHROMEOS_RELEASE_DESCRIPTION=9592.96.0 (Official Build) stable-channel cyan 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9592.96.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9592.96.0

**Comment by bANNji** [comment]
I have been scanning the chroot for errors but i really dont know what im looking at.

**Comment by DennisLfromGA** [comment]
@bANNji,

It seems your chroot is up-to-date but the error you're getting is unusual -

> -su: 21: Syntax error: Unterminated quoted string

Try reinstalling all of the host-bin files with the following command -

`sudo sh ~/Downloads/crouton -b`

Then try to launch your xfce desktop again with -

`sudo startxfce4 -n xenial`

*Hope this helps,*
-**DennisL**

**Comment by bANNji** [comment]
Thank you for your reply, I have tried what you had recommended to no avail.  unfortunately i still receive the same error. `chronos@localhost / $ sudo sh ~/Downloads/crouton -b
Downloading latest crouton installer...
######################################################################## 100.0%
Installing startxfce4 into the host...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Done! You can enter the chroot using enter-chroot.
chronos@localhost / $ sudo startxfce4 -n xenial
Entering /mnt/stateful_partition/crouton/chroots/xenial...
-su: 21: Syntax error: Unterminated quoted string
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`

**Comment by DennisLfromGA** [comment]
@bANNji,

Let's try to get more diagnostics, please enter the following:

`sudo sh -x /usr/local/bin/startxfce4 -n xenial 2>&1 | tee /tmp/xfce4-diag.log`

Then post the `/tmp/xfce4-diag.log` to pastebin or gist.github and give us the link.
Hopefully, that way we can see just where it's failing.

*Hope this helps,*
-**DennisL**

**Comment by bANNji** [comment]
https://gist.github.com/bANNji/404a3ee6146a916f40b293752ec730ab

**Comment by DennisLfromGA** [comment]
@bANNji,

Okay, that didn't help much, sorry. :(

Can you enter your chroot as root, using -

`sudo enter-chroot -n xenial -u root`

If so, you may have some permission problems in your home folder that are causing the issue.
You can run the following command to set everything back to your ownership -

`sudo chown -R 1000:1000 "$HOME"`

Then exit and try launching your xfce desktop again from outside the chroot.

*Hope this helps,*
-**DennisL**

**Comment by bANNji** [comment]
I have tried this, unfortunately it did not fix the problem. the same output is present. Would there be any way my ~/.profile might affect this?

**Comment by DennisLfromGA** [comment]
@bANNji,

Without knowing what's in your `~/.profle` I cant say for sure.
But, since getting into the chroot as root doesn't work I don't think your `~/.profle` is the problem.

Let's see if we can get more info. by just using `enter-chroot` with this -

`sudo sh -x /usr/local/bin/enter-chroot -n xenial 2>&1 | tee /tmp/xen.diag.log`

Then give is the link to the gist file again.

If you suspect something in your home folder might be causing the issue you can `cd` into it in a `crosh shell` session under `/usr/local/chroots/xenial/home/[username]` to work on it without a chroot session.

*Hope this helps,*
-**DennisL**

**Comment by bANNji** [comment]
Turns out it was my .profile something went wrong in there what i did to fix it was copy the default profile from skel inside the chroot to the home folder of my chroot! I was messing around with paths trying to get familiar with linux, I had no idea when I had quit my last session that it was broken.  What led me to think it was the .profile is when i ran "enter-chroot" stated something was wrong with .profile. I appreciate you helping me diagnose this.

**Comment by DennisLfromGA** [comment]
@bANNji,

> What led me to think it was the .profile is when i ran "enter-chroot" stated something was wrong with .profile.

Ya think???
