### ISSUE TITLE
Newbie cannot run chroot

### ISSUE THREAD

**Issue by ferum1** [dnschneid/crouton#3426]
```
chronos@localhost / $ sudo startxfce4
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-87-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:40:47 PDT 2017 armv7l
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=984196af-390b-1640-9c49-aa758a59a033/PARTNROFF=1 hashtree=PARTUUID=984196af-390b-1640-9c49-aa758a59a033/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=b30fcee37cb0db2d4c2e757120dd89c358cdaf26 salt=6e8585e7cc0c5b01d0806b1dab3065200da47885aba90c9fa7a67a592d4905f9" noinitrd vt.global_cursor_default=0 kern_guid=984196af-390b-1640-9c49-aa758a59a
033  
Build Date: 25 July 2017  01:30:24PM
xorg-server 2:1.19.3-1ubuntu1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Sep 26 20:46:49 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1506451610.003413 sender=:1.11 -> destination=:1.62 serial=989 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
method return time=1506451610.408649 sender=:1.11 -> destination=:1.63 serial=990 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:

I recently decided to try to download linux to my chromebook, but so far its been a mess. I have tried starting up my chroot several times without sucess. This error occurs everytime. Neither is it possible to delete the chroot. I tried powerwashing my chromebook and restart the process but the same error returned. Anyone who knows how to solve this?

**Comment by PMaxDS** [comment]
After you finish your Linux installation through crouton, try rebooting you chromebook before trying to launch your Linux distro through the shell.

**Comment by ferum1** [comment]
I'm still getting the same error. I also tried deleting the chroot but it doesn't let me. This appears when I try to delete

chronos@localhost / $ sudo edit-chroot -d xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Delete /mnt/stateful_partition/crouton/chroots/xenial? [a/y/N] 
Aborting deletion of /mnt/stateful_partition/crouton/chroots/xenial

**Comment by DennisLfromGA** [comment]
@ferum1,

Please show us the output of:

`sudo edit-chroot -all`

I imagine you're using the 'xorg' xmethod, you might have more success with the 'xiwi' xmethod.
You can add it to your existing 'xenial' chroot with the following:

`sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

Once that completes successfully and you've installed the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension you should be able to  launch you desktop with:

`sudo startxfce4 -n xenial` 

*Hope this helps,*
-**DennisL**

**Comment by ferum1** [comment]
This is the output for sudo edit-chroot -all

chronos@localhost / $ sudo edit-chroot -all
Password: 
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xorg
targets: xiwi,xfce
host: version 9592.96.0 (Official Build) stable-channel peach_pit 
kernel: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:40:47 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by ferum1** [comment]
I tried adding xiwi, but didn't work.

chronos@localhost / $ sudo sh ~/Downloads/crouton -n xenial -t xiwi -u
/usr/local/chroots/xenial already exists; updating it...
Enter encryption passphrase for xenial: 
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [102 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [102 kB]
Fetched 204 kB in 1s (113 kB/s)                              
Reading package lists... Done
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20160104ubuntu1).
apt-transport-https is already the newest version (1.2.24).
sudo is already the newest version (1.8.16-0ubuntu1.5).
wget is already the newest version (1.17.1-1ubuntu1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 6e9aa2b7a694ee79518f05d544999468c4fd7055)...
--2017-09-27 21:46:42--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/6e9aa2b7a694ee79518f05d544999468c4fd7055.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 108.177.14.82, 2a00:1450:4010:c0a::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|108.177.14.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '/tmp/crouton-cras.AuiwZQ/adhd.tar.gz'

     0K .......... .......... .......... .......... ..........  276K
    50K .......... .......... .......... .......... ..........  243K
   100K .......... .......... .......... .......... ..........  496K
 150K .......... .......... .......... .......... ..........  493K
   200K .......... .......... .......... .......... ..........  265K
   250K .......... .......... .......... .......... ..........  399K
   300K .......... .......... .......... .......... ..........  318K
   350K .......... .......... .......... .......... ..........  358K
   400K .......... .......... .......... .......... ..........  151K
   450K .......... .......... .......... .......... ..........  740K
   500K .......... .......... .......... .......... ..........  434K
   550K .......... .......... .......... .......... ..........  437K
   600K .......... ..........                                   445K=1.9s

2017-09-27 21:46:45 (331 KB/s) - '/tmp/crouton-cras.AuiwZQ/adhd.tar.gz' saved [634939]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version (1.1.0-0ubuntu5).
libasound2 is already the newest version (1.1.0-0ubuntu1).
libspeexdsp1 is already the newest version (1.2~rc1.2-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libspeexdsp-dev is already the newest version (1.2~rc1.2-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
libc6-dev is already the newest version (2.23-0ubuntu9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libasound2-dev is already the newest version (1.1.0-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (native)...
Installing CRAS...
Installing target extension...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
x11-utils is already the newest version (7.7+3).
xclip is already the newest version (0.12+svn84-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing dependencies for /usr/local/bin/croutonwebsocket...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libc6-dev is already the newest version (2.23-0ubuntu9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling /usr/local/bin/croutonwebsocket...
Installing target xiwi...
xserver-xorg-video-dummy was already not hold.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xorg is already the newest version (1:7.7+13ubuntu3).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xorg-video-abi-20
                            Depends: xserver-xorg-core (>= 2:1.17.99.902)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-87-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:40:47 PDT 2017 armv7l
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=984196af-390b-1640-9c49-aa758a59a033/PARTNROFF=1 hashtree=PARTUUID=984196af-390b-1640-9c49-aa758a59a033/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=b30fcee37cb0db2d4c2e757120dd89c358cdaf26 salt=6e8585e7cc0c5b01d0806b1dab3065200da47885aba90c9fa7a67a592d4905f9" noinitrd vt.global_cursor_default=0 kern_guid=984196af-390b-1640-9c49-aa758a59a033  
Build Date: 25 July 2017  01:30:24PM
xorg-server 2:1.19.3-1ubuntu1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Sep 27 21:52:43 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1506541964.207192 sender=:1.11 -> destination=:1.52 serial=760 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
method return time=1506541964.556172 sender=:1.11 -> destination=:1.53 serial=761 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@ferum1,

> I tried adding xiwi, but didn't work.

You *already had* 'xiwi' installed but it wasn't the default xmethod -

> xmethod: xorg
targets: xiwi,xfce

It may have failed before like it did above when you tried to add it again.

Take a look at this comment for a possible workaround: https://github.com/dnschneid/crouton/issues/3366#issuecomment-329266281

Also, when both 'xorg' & 'xiwi' xmethods are installed you can choose which to use when you launch it, similar to -

For 'xorg': `sudo startxfce4 -n xenial -X xorg`
For 'xiwi': `sudo startxfce4 -n xenial -X xiwi`

*Hope this helps,*
-**DennisL**

**Comment by ferum1** [comment]
Thank you for your help, but I managed to solve my problem by deleting the chroot and downloading trusty instead

**Comment by DennisLfromGA** [comment]
@ferum1,

Okay, that's cool.
I'll close this snce I think it's related to several other issues and PR https://github.com/dnschneid/crouton/pull/3380

-**DennisL**

**Comment by DennisLfromGA** [comment]
Seems this issue has been around for quite a while now and is related to video-armsoc drivers.

Take a look at this comment for a little more info.: https://github.com/dnschneid/crouton/issues/3611

For a couple of workarounds, see this comment: https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813
Note that in Solution 1 above you may have to substitute 'startxfce4' with your start script.

*Hope this helps,*
-**DennisLfromGA**

**Comment by usaamgilani** [comment]
mo it doesn't work......not even with trusty.....is there any way other than arch and kali.....
