### ISSUE TITLE
With crosvm and vm_launcher does crouton need developer mode?

### ISSUE THREAD

**Issue by gvrajesh** [dnschneid/crouton#3427]
I have been catching up on crosvm and vm_launcher.

https://chromium.googlesource.com/chromiumos/platform/crosvm/
https://chromium.googlesource.com/chromiumos/platform2/+/6c976ef165ee22ddf274035d16b8e2071b29cb0f/vm_tools/
https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/24a9d16fc15c3d07d726f3f974a541572d3584e5/project-termina/

With these crouton will run inside a VM?

**Comment by DennisLfromGA** [comment]
> With these (let) crouton will run inside a VM?

Interesting question and the answer may be even more interesting.

That 'project-termina' looks *especially* interesting to me. ;-)


-**DennisL**

**Comment by DennisLfromGA** [comment]
Update:

This is how I understand it, I could be wrong but -
- Termina runs in a vm (crosvm) and Crostini runs in a container in that vm (lxc).
- As of version 67, currently in the dev channel, you no longer need dev mode, it runs in verified boot mode.

Whether crouton will run in the vm or if you'd even want to I'm not certain but I don't think it's possible as is.

*Hope this helps,*
-**DennisLfromGA**
