### ISSUE TITLE
alsa cras integration crashes audacious and cmus (on ARM)

### ISSUE THREAD

**Issue by urjaman** [dnschneid/crouton#3429]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xiwi
targets: audio,cli-extra,extension,xiwi
host: version 9976.0.0 (Official Build) canary-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Sep 26 04:04:20 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
```

#### Please describe your issue:
\# apt-get install cmus
$ cmus
Segmentation fault (core dumped)
$ gdb --args cmus
...
(gdb) run
...
Thread 1 "cmus" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xb2995cd8 in snd_hctl_handle_events () from /usr/lib/arm-linux-gnueabihf/libasound.so.2
#2  0xb299db40 in snd_mixer_handle_events () from /usr/lib/arm-linux-gnueabihf/libasound.so.2
#3  0xb2a1c87e in ?? () from /usr/lib/cmus/op/alsa.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

And that's about it. audacious crashes in a similar-looking place.

**Comment by EnderNightLord-ChromeBook** [comment]
Wow thats strange that does not happen to me when i use xiwi try updating the chroot

**Comment by urjaman** [comment]
Tried that (a week ago or so), updated the xenial and then the chroot things but not change.

(N.B. This was on canary channel, since then I've switched to dev channel... havent tested since because well I've learned to use the CrOS music player.)
