### ISSUE TITLE
Crouton integration not working

### ISSUE THREAD

**Issue by magicbeto** [dnschneid/crouton#3431]
```
Please paste the output of the following command here: sudo edit-chroot -all
```Password: 
name: trusty
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170901092920~master:0216f9d1
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9901.29.0 (Official Build) dev-channel reef 
kernel: Linux localhost 4.4.79-11624-g782dc516445d #1 SMP PREEMPT Mon Sep 25 22:05:58 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 9901.29.0 (Official Build) dev-channel reef 
kernel: Linux localhost 4.4.79-11624-g782dc516445d #1 SMP PREEMPT Mon Sep 25 22:05:58 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
Crouton integration is not running in a window and i don't know what to do...

#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
@magicbeto,

In your 'trusty' chroot using 'xorg' you might want to add the 'extension' target for copy pasta & 'crouton integration' integration. :)

In your 'xenial' chroot using 'xiwi' you have to add the ['crouton integration'](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension form the Chrome Web Store.

Once that's done you can access any running chroot from CrOS using the 'crouton integration' tool -

![ci-tool](https://user-images.githubusercontent.com/3418772/31026384-47052f8c-a514-11e7-8f15-47b90322a7e1.png)

*Hope this helps,*
-**DennisL**

**Comment by magicbeto** [comment]
@DennisLfromGA 
Hi,
For "In your 'xenial' chroot using 'xiwi' you have to add the 'crouton integration' extension form the Chrome Web Store." it's already added. I had the crouton integration since the beginning.

But for "In your 'trusty' chroot using 'xorg' you might want to add the 'extension' target for copy pasta & 'crouton integration' integration."....i don't understand what i have to do...what do you mean?

**Comment by DennisLfromGA** [comment]
@magicbeto,

> it's already added. I had the crouton integration since the beginning.

Good to know. 

> i don't understand what i have to do...what do you mean?

Sorry, I didn't mean to confuse things.
You don't *have* to do anything, it's just a very handy target to have & use.

-----
You started off stating -

> Crouton integration is not running in a window and i don't know what to do...

Do you see the extension in the toolbar with a number like I show in my example above?
If so, it's running and you can click it and choose to switch to a any chroot listed.
If not, it's not running and may have to be re-installed.

*Hope this helps,*
-**DennisL**

**Comment by magicbeto** [comment]
@DennisLfromGA 

> Do you see the extension in the toolbar with a number like I show in my example above?
Yes, but the color of the "C" is always grey, never green...and there is no number

**Comment by DennisLfromGA** [comment]
@magicbeto,

>> Do you see the extension in the toolbar with a number like I show in my example above?

> Yes, but the color of the "C" is always grey, never green...and there is no number

That's what it looks like when there are no chroots running.

- Do you have any chroots running when it appears grey with no number?
- Which chroot are you running, trusty or xenial?
- If it's trusty can you switch to it using the keyboard shortcuts <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>F1/F2</kbd> ?
- If it's xenial can you switch to it by pressing the <kbd>switch windowl</kbd> key ?

*Hope this helps,*
-**DennisL**

**Comment by magicbeto** [comment]
@DennisLfromGA 

> o you have any chroots running when it appears grey with no number?

yes

> Which chroot are you running, trusty or xenial?

trusty

> If it's trusty can you switch to it using the keyboard shortcuts ctrl+alt+shift+F1/F2 ?

yes

**Comment by DennisLfromGA** [comment]
@magicbeto,

Don't know why it's not working for you.
Have you tried removing and reinstalling it ?

*Hope this helps,*
-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
1. You need the xiwi target for it to work
2. You also need the extention target installed with the chroot

**Comment by raza-jahangir** [comment]
> 1. You need the xiwi target for it to work
> 2. You also need the extention target installed with the chroot

how?

**Comment by EnderNightLord-ChromeBook** [comment]
Get the chrome extension: https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom

add ,xiwi to the end of your build

boom done...

**Comment by EnderNightLord-ChromeBook** [comment]
eg: sudo sh ~/Downloads/crouton -r trusty -t xfce,xiwi

**Comment by DennisLfromGA** [comment]
@EnderNightLord-ChromeBook, @raza-jahangir  & @magicbeto,

Not quite, to *add* the 'xiwi' xmethod to your *existing* trusty chroot use this: 

- `sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`

*Hope this helps,*
-**DennisLfromGA**

Closing. Please re-open if this issue is still a concern.
