### ISSUE TITLE
Failed to download latest installer

### ISSUE THREAD

**Issue by crawphish** [dnschneid/crouton#3432]
```
sudo sh ~/Downloads/crouton -t xfce
```
#### Please describe your issue:
I tried to download the latest installer using the link provided in the instructions (https://goo.gl/fd3zc), however that link seems to be broken and it says it is unreachable. So I downloaded the installer folder from git and ran the above command using that directory. However the URL in the shell file seems to be broken as well. I get the following error when I run it:

```
chronos@localhost / $ sudo sh ~/Downloads/crouton -t xfce
Downloading latest crouton installer...
######################################################################## 100.0%Warning: Transient problem: timeout Will retry in 1 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 1 retries left.

curl: (28) Connection timed out after 60000 milliseconds
Failed to download crouton installer.
Check your internet connection or proxy settings (-P) and try again.
```
Is there an alternate link to get the installer or is the server just down and I can try again later?

**Comment by DennisLfromGA** [comment]
@crawphish,

The link to the installer ( https://goo.gl/fd3zc ) isn't broken.
It looks & sounds like you are having temporary network problems

> Warning: Transient problem: timeout Will retry in 2 seconds. 1 retries left.

> curl: (28) Connection timed out after 60000 milliseconds
Failed to download crouton installer.
Check your internet connection or proxy settings (-P) and try again.

Are you using a proxy ?

*Hope this helps,*
-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
Yes you need internet to download/retrieve the files so you can't just do it offline
