### ISSUE TITLE
slow ( unresponsive ? ) logout / shutdown after running a succesful xfce session

### ISSUE THREAD

**Issue by aleifuu** [dnschneid/crouton#3433]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
```
name: xenial
encrypted: no
Entering /media/removable/USB Drive/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,audio,keyboard,touch,core,xfce-desktop,extension
host: version 9592.96.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Sat Sep 16 10:00:51 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/chroots/xenial...

```

#### Please describe your issue:

I had crouton installed on a separate external USB stick as I don't really want to 'clutter' my current ChromeOS. Installation took a while, but it was succesful. This was the command that I used to install:

`sudo sh ~/Downloads/crouton -r xenial -t audio,keyboard,touch,core,xfce-desktop,xiwi,extension -p /media/removable/sd-card -u
`

and to run it, simply using 

`sudo sh /media/removable/sd-card/bin/startxfce4
`

I've got few connection error, but then the screen switches full screen bringing up the XFCE interface up. it's great. Everything seems fine with running the Linux part of it. Unfortunately adding "-xiwi" somehow doesn't, but "-xiwi-tab" is working although resolution will be very very small 

Now the real issue is that after I log-out/shutdown the XFCE session and when I want to lock/log-out/shutdown my ChromeOS, it tooks either very slow ( or just unresponsive ) to a point I had to pressed the "off" button just to shut it down.

I think the normal behaviour when you want to lock/log-out is that ChromeOS will get you back to login screen, however in my case the screen will just go black ( okay, i thought it's a between process that will eventually got you to login screen ), but it just stay there .... for a long time ... and pressing any button doesn't seem to response anything 

Has anyone encountered similar issue ? It did give me a thought that crouton brick my ChromeOS, so I'm quite reluctant to use it at the moment 

I had crouton experience before with my previous Chromebook, it was an Acer Chromebook 15 and it ran great

This is my 2nd Chromebook and I thought I go higher with Samsung Chromebook Pro

**Comment by DennisLfromGA** [comment]
@aleifuu,

It may just be slow or having a hard time unmounting everything on the external media.
You can switch back to Chrome OS while the chroot is running and press <kbd>ctrl</kbd>+<kbd>c</kbd> in the shell session that launched your desktop, that should shutdown your chroot and unmount everything also.

You can also use `unmount-chroot` to see what's still mounted and even terminate them if need be.
Here's the usage -
```
chronos@localhost ~ $ unmount-chroot 
unmount-chroot [options] name [...]

Unmounts one or more chroots, optionally killing any processes still running
inside them.

By default, it will run in interactive mode where it will ask to kill any
remaining processes if unable to unmount the chroot within 5 seconds.

Options:
    -a          Unmount all chroots in the CHROOTS directory.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -f          Forces a chroot to unmount, potentially breaking or killing
                other instances of the same chroot.
    -k KILL     Send the processes SIGKILL instead of SIGTERM.
    -p          Print to STDOUT the processes stopping a chroot from unmounting.
    -t TRIES    Number of seconds to try before signalling the processes.
                Use -t inf to be exceedingly patient. Default: 5
    -x          Keep the root directory of the chroot mounted.
    -y          Signal any remaining processes without confirmation.
                Automatically escalates from SIGTERM to SIGKILL.
```

*Hope this helps,*
-**DennisL**

**Comment by aleifuu** [comment]
Alright. Cool 

I could try that later on. You may be right with the unmounting part. Since using dongle for adapting usb-c interface for normal usb-stick, I think it does slow the system a bit ( or maybe I just got a 'bad' dongle ) *sigh*

**Comment by aleifuu** [comment]
Okay, I just tried again. Unfortunately, it's the same result

So the process was logging out from xfce4 ( i was using -X xiwi-tab btw,
and crouton-integration is working ), going back to shell wait untill the
process unmounts the chroots itself, did the 'sudo unmount-chroot' command
... It just give me one line response like 'Unmounting
/media/removable/USB\ Drive\ 1/chroots/xenial'

Then, just to make sure I unplug the usb stick and  dongle before pressing
the sign out on the ChromeOS

Still faded out to blank screeen, instead of login screen ...

Maybe I should close out the chronos shell tab too maybe ... Do you think ?

**Comment by DennisLfromGA** [comment]
@aleifuu,

> Maybe I should close out the chronos shell tab too maybe ... Do you think ?
…

I don't know but it may help.
Sorry but I haven't run many chroots on external media of late.

*Hope this helps,*
-**DennisL**

**Comment by aleifuu** [comment]
Do you think installing crouton not on external media could solve the
isssue that I am having ?

I'm just super cautious when it comes to shutting down electronic devices
by force you know. Lol

I meant, any log/output that I could post that might help too ?

**Comment by DennisLfromGA** [comment]
@aleifuu,

> Do you think installing crouton not on external media could solve the
isssue that I am having ?

Yes, I think it could. I think shutting down & unmounting the chroot on external media may be the problem.
You could try installing a new chroot or moving the existing one on external media to your internal drive.
Then see if it behaves any differently when shutting it down. You can always delete it from your Chromebook if need be.

> Maybe I should close out the chronos shell tab too maybe ... Do you think ?

Yes, that might help. Sometimes the powerd process can interfere with logging out, it's happened to me.

> Still faded out to blank screeen, instead of login screen ...

If that happens again try pressing the <kbd>full screen</kbd> and/or the <kbd>switch window</kbd> key and see if that helps.

*Hope this helps,*
-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
Might be because it is a small memory stick
Or because you have barely any space left

**Comment by EnderNightLord-ChromeBook** [comment]
Or maybe cause xiwi is more slow than without xiwi

**Comment by aleifuu** [comment]
it's a typical 16GB SanDisk stick. with crouton installed, it occupies
around 3.9GB i think. So it's still plenty of space left

My Chromebook lists still having 20GB left free

It looks like unmounting process takes a long time eating up the RAM (
maybe ) ...
