### ISSUE TITLE
Terminal won't open

### ISSUE THREAD

**Issue by rulon1** [dnschneid/crouton#3437]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: unity-desktop
host: version 9901.29.0 (Official Build) dev-channel gnawty 
kernel: Linux localhost 4.4.79-11624-g782dc516445d #1 SMP PREEMPT Mon Sep 25 22:04:31 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
I can't open terminal after installing unity-desktop. Am I missing something totally obvious? Apologies, I'm pretty new to all this. It also hangs on 'waiting to install' when trying to install additional programs. Any thoughts?

I used 'sudo sh ~/Downloads/crouton -t unity-desktop' to install ubuntu. Does it matter I omitted -e? I'm not doing anything sensitive, just trying to learn more about linux on this cheap Chtomebook.

**Comment by rulon1** [comment]
Nevermind, I just used XTerm instead. Anyway I can no play Minecraft on my Chromebook!!!!

**Comment by rwwishart** [comment]
Not to sound like I'm jumping on your case, but this is a good example of needing to exhaust troubleshooting options on your end before opening an issue.

**Comment by EnderNightLord-ChromeBook** [comment]
Install somthing else like konsole or gnome terminal

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
