### ISSUE TITLE
Random Clicking

### ISSUE THREAD

**Issue by MysteryPig** [dnschneid/crouton#3438]
While I type, the computer randomly acts as if I have clicked the mouse. It does not seem to be me accidentally tapping the trackpad, but it doesn't happen if my left hand is not resting on the edge of the computer. It also happens at the same time as a keypress, but it isn't the same key every time. This happens on both my Acer Chromebook 11, and my Acer Chromebook 14. Neither has this issue while I'm not using crouton.

**Comment by rwwishart** [comment]
Disable the trackpad to make sure and if you're using a mouse, turn it off or unplug it. See if the issue persists. If so, provide more information on your build, setup, and exact conditions when the problem occurs.

**Comment by EnderNightLord-ChromeBook** [comment]
Interesting maybe it would be the mouse that is causing
