### ISSUE TITLE
Trying to install crouton on my chromebook

### ISSUE THREAD

**Issue by Aetheric1** [dnschneid/crouton#3439]
```
sh: Can't open /home/chronos/user/Downloads/crouton
```

#### Please describe your issue:
I am trying to install crouton on my chromebook and it says sh: Can't open /home/chronos/user/Downloads/crouton
Please help, The chromebook I am trying to install it on is the Acer Chromebook 14 cb3-431
(I am in developer mode already)

#### If known, describe the steps to reproduce the issue:
open crosh (ctrl alt t)
type shell
type sudo sh ~/Downloads/crouton -e -t xfce
Then error comes up sh: Can't open /home/chronos/user/Downloads/crouton

**Comment by divx118** [comment]
Be sure you have downloaded the crouton script https://goo.gl/fd3zc first before you execute `sudo sh ~/Downloads/crouton -e -t xfce`

**Comment by rwwishart** [comment]
Sounds like you need to download the crouton script like divx118 suggests.

**Comment by Aetheric1** [comment]
nevermind I found out why, I forgot to add some parameters
