### ISSUE TITLE
Does Crouton work on the new PixelBook?

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#3440]
If so, this is on my Black Friday list!!

**Comment by DennisLfromGA** [comment]
@tedm,

It's still Chrome OS so I don't see why not. Of course, the experts will have to weigh in for an authoritative answer.

If it were me and I had any of the larger cap SSD's I would run the 'chrx' script once to make a larger partition 7 for my crouton chroots. That way they'll survive a powerwash at least.

-**DennisL**

**Comment by dnschneid** [comment]
Works great.

**Comment by tedm** [comment]
Thanks @DennisLfromGA and @dnschneid I think I'll be fine with the lowest end 128GB as my 32GB has rarely filled up. Plus, I have one of those mini Toshiba USB 3.1 drives. What I really like about it is that it's fanless, smaller and light, has USB C like my pixel phone. For traveling, I think I can take that instead of my current notebook and ipad and save some weight with chargers and 2 devices. Not that excited about the pixel2 over pixel regular phone though. Wish they had more speed or RAM, but nice to be able to skip that upgrade and apply those savings to a pixelbook.
