### ISSUE TITLE
Installing Apps not Working

### ISSUE THREAD

**Issue by RyanGamingXbox** [dnschneid/crouton#3442]
I haven't been using this for a long while so I decided to launch it from a long time. I redownloaded it, because I now have a new chromebook. When I downloaded it. I downloaded my apps, but it has an error.

Error Code/Message:
Software can not be install because the authentication service is not available

**Comment by DennisLfromGA** [comment]
@RyanGamingXbox,

> I haven't been using this for a long while so I decided to **_launch_** it from a long time. 
> I redownloaded it, because I now have a new chromebook.

When you downloaded *what* exactly?
Are you speaking of 'crouton' or *launching* a chroot desktop?

> When I downloaded it. I downloaded my apps, but it has an error.
>> Error Code/Message:
>> Software can not be install because the authentication service is not available

What 'apps' do you mean?
Did you install a new chroot?
If so please show us the output of: `sudo edit-chroot -all`

Sorry for all the questions but it's a little confusing to me to tell if you have a chroot installed and you're having issues with it or if it's Chrome OS you're having issues with.

-**DennisL**

**Comment by RyanGamingXbox** [comment]
The problem is chroot.
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
Also this error code appears when VT switching from Linux to CHrome

**Comment by RyanGamingXbox** [comment]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 9901.35.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Oct 1 22:03:58 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
Output of Command

**Comment by RyanGamingXbox** [comment]
I think the problem is that the Software Center can not perform Admin Permissions

**Comment by RyanGamingXbox** [comment]
Well, I found a fix for that with console packages, like for firefox "sudo apt-get install firefox"

**Comment by DennisLfromGA** [comment]
@RyanGamingXbox,

I've run into that too sometimes.
For the Synaptic package manager, for instance, I run: `gksudo synaptic-pkexec`

*Hope this helps,*
-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
Gksu software-center will help too

**Comment by vitaly200326** [comment]
I have a same problem. But your solutions do not help me. Any other advice/solutions that might help me please?

**Comment by vitaly200326** [comment]
@EnderNightLord-ChromeBook how do you get to Gksu software-center?

**Comment by RyanGamingXbox** [comment]
ok thanks

**Comment by alexthebeamer1** [comment]
downloading in ubunto sofware center dosnt work for me

**Comment by alexthebeamer1** [comment]
pls help

**Comment by alexthebeamer1** [comment]
@DennisLfromGA

**Comment by yeetsup-git** [comment]
Bro was ignored 💀
