### ISSUE TITLE
xiwi extension - capslock is always "key down", never up

### ISSUE THREAD

**Issue by sunaku** [dnschneid/crouton#3444]
```
$ sudo edit-chroot -all
name: sid
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20170901092920~master:0216f9d1
release: sid
architecture: amd64
xmethod: xiwi
targets: xiwi
host: version 9592.96.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Sat Sep 16 10:00:51 PDT 2017 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/sid as another instance is using it.
```

#### Please describe your issue:
Tapping CapsLock on _any_ external USB keyboard connected to my Chromebook always registers as:
![screenshot 2017-10-05 at 2 13 43 am](https://user-images.githubusercontent.com/9863/31219880-84aec4d4-a973-11e7-8f62-43e07f828881.png)
```
debug:(1) ... Key DOWN: C:CapsLock, JSKC:14 => KC:42 searchstate:0
```
Since the CapsLock key release event is not registered, I have to use an unreliable workaround of holding the Shift key down for a moment, tapping the CapsLock key while Shift is still held down, and finally releasing the Shift key in order to turn off capslock mode inside the xiwi environment. 😱  But that's not the end of it: I also have to go manually check and reset any unwanted CapsLock state that has propagated up into ChromeOS. 😰 

#### If known, describe the steps to reproduce the issue:
1. Connect an external USB keyboard to your Chromebook.
2. Tap the CapsLock key on your external keyboard _twice_.
3. Observe that capslock mode was _not_ toggled inside xiwi.

Thanks for your consideration.

**Comment by bdodroid** [comment]
Exact same issue. I will add that I am using Crouton on Neverware's CloudReady OS v61 (ChromiumOS)

**Comment by gcaliber** [comment]
I have the same problem with the built in keyboard after changing search to caps lock it causes the same behavior.
