### ISSUE TITLE
Xenial Wont Boot up

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [dnschneid/crouton#3447]
I set up a new chroot with xenial KDE it work once but then after a few months my device packed up because of space I deleted and went to precise unity 

What it does is it boots and then it says error unmounting then goes back to the normal shell

My device is a 
Samsung chromebook 3
Armv7
Does arm come into this?

**Comment by DennisLfromGA** [comment]
@EnderNightLord-ChromeBook .

Please try the methods mentioned here: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)
If that doesn't help then show us the output of: `sudo edit-chroot -all`
And provide more detail about your issue if possible.

-**DennisL**

**Comment by EnderNightLord-ChromeBook** [comment]
Thanks just what I needed
