### ISSUE TITLE
OK, I have tried everything and still no luck.

### ISSUE THREAD

**Issue by TheMinigun** [dnschneid/crouton#3448]
Sudo says this... 
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
I have tried default passwords and nothing works also I did not enable debugging features on the setup screen. I really would like to get crouton. Please Help!!!!
![screenshot 2017-10-09 at 10 43 06 pm](https://user-images.githubusercontent.com/32660762/31367148-3cceffac-ad43-11e7-9a58-26b9aa0724dc.png)

**Comment by TheMinigun** [comment]
Also i have an Acer C720 Chromebook.

**Comment by DennisLfromGA** [comment]
@TheMinigun,

It looks like things are working correctly.
There is no password for chronos or root by default.
When you entered '`sudo su`' it thought you were trying to access user 'su' which doesn't exist.
Why are you trying to use '`sudo`' in that context?

Take a look at the '[README](https://github.com/dnschneid/crouton/blob/master/README.md)' to get started.
You'll need to know what targets or desktop(s) you want to install and optionally what release you want to use before installing your chroot.
If you need help with that let us know.

*Hope this helps,*
-**DennisL**

**Comment by TheMinigun** [comment]
I read that README file and still no help

**Comment by TheMinigun** [comment]
But i may need more help

**Comment by TheMinigun** [comment]
Maybe a tutorial video or something would be helpful?! (if there is one post it please!!!)

**Comment by TheMinigun** [comment]
![screenshot 2017-10-10 at 10 02 17 am](https://user-images.githubusercontent.com/32660762/31390525-24f7367e-ada2-11e7-96fc-ffccb013c0d3.png)

**Comment by DennisLfromGA** [comment]
@TheMinigun,

Looks like you may need to re-visit the [README](https://github.com/dnschneid/crouton/blob/master/README.md), the syntax you used above won't work.

Also, maybe this'll help: [How to install crouton on your Chromebook](https://lmgtfy.com/?q=how+to+install+crouton+on+your+chromebook)

*Hope this helps,*
-**DennisL**

**Comment by TheMinigun** [comment]
Ok i powerwashed it again (even though i have done it multipule times) and finally it works!!!! Thanks for the help!!
