### ISSUE TITLE
Trouble with usbip

### ISSUE THREAD

**Issue by jgyllinsky** [dnschneid/crouton#3449]
```
$ sudo modprobe usbip
modprobe: FATAL: Module usbip not found in directory /lib/modules/3.8.11
```

#### Please describe your issue:
Chromebook running crouton connects to Ubuntu remote server through `ssh` and `vnc` using `remmina`. USB device need by server is local. USB over IP is supported at kernel level through `usbip`.

Following tutorial: [https://askubuntu.com/questions/612355/share-usb-drive-over-network](https://askubuntu.com/questions/612355/share-usb-drive-over-network)

#### Next Steps?
I'm going to try to compile it from source I guess. Look at https://blog.danman.eu/usbip-utils-2-0-on-ubuntu/

#### Referencing:

- https://askubuntu.com/questions/612355/share-usb-drive-over-network

- https://blog.danman.eu/usbip-utils-2-0-on-ubuntu/

- https://www.howtoforge.com/how-to-set-up-a-usb-over-ip-server-and-client-with-debian-lenny

- https://github.com/solarkennedy/wiki.xkyle.com/wiki/USB-over-IP-On-Ubuntu

- https://www.element14.com/community/thread/26533/l/detailed-steps-to-install-usbip-on-pcduino?displayFullThread=true

- https://bianchirick.wordpress.com/2014/03/07/gumstix-overo-installing-usbip-on-linaro-ubuntu-image/

- https://3mdeb.com/os-dev/linux-rpi-and-usb-over-ip-updated/

#### Steps to reproduce the issue:
```
$ sudo apt install usbip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
usbip is already the newest version (0.1.7-3).
usbip set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo modprobe usbip
modprobe: FATAL: Module usbip not found in directory /lib/modules/3.8.11

$ sudo modprobe usbip-host
modprobe: FATAL: Module usbip-host not found in directory /lib/modules/3.8.11

$  sudo usbip list -l
usbip err: usbip_network.c: 206 (tcp_connect ) list 3240: Name or service not known
- list failed

$ sudo modprobe usbip-core
modprobe: FATAL: Module usbip-core not found in directory /lib/modules/3.8.11

$ sudo usbipd -D                  
usbip err: stub_driver.c:  33 (open_sysfs_stub_driver) usbip_common_mod.ko and usbip.ko must be loaded

** (process:6885): ERROR **: driver open failed
Trace/breakpoint trap (core dumped)


```

**Comment by jgyllinsky** [comment]
Next commands / steps in order

```
$ usbip --port
bash: usbip: command not found

$ sudo apt install linux-tools-generic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
```
...


```
$ usbip version
WARNING: usbip not found for kernel 3.8.11

  You may need to install the following packages for this specific kernel:
    linux-tools-3.8.11

  You may also want to install one of the following packages to keep up to date:
    linux-tools

```

```
$ which usbip
/usr/bin/usbip

$ uname -a
Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:46:23 PDT 2017 armv7l armv7l armv7l GNU/Linux

$ /usr/lib/linux-tools/4.4.0-96-generic/usbip version
usbip (usbip-utils 2.0)

```


Should I use `/usr/lib/linux-tools/4.4.0-96-generic/usbip` going forward? This doesn't match my kernel of `3.8.11`...

**Comment by divx118** [comment]
You will need to build the module yourself see https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules . Maybe @mark-hahn who posted #3434 can give you some tips if you are up to it.

**Comment by divx118** [comment]
You will need to build the module yourself see https://github.com/dnschneid/crouton/wiki/Build-chrome-os-kernel-and-kernel-modules . Maybe @mark-hahn who posted #3434 can give you some tips if you are up to it.

**Comment by DennisLfromGA** [comment]
@divx118, 

Thanx 👍 
I was just searching for your conversations with @mark-hahn.

-**DennisL**

**Comment by xinheng0816** [comment]
Hello all
Sorry for interupt!
Someone can guide me how to install compile and install usbip driver in RedHat system ?
BTW, I downlod all source code with verison = Linux version 3.10.0-514.el7.x86_64. When I tied to build usbip module, it seems always nothing happen and the expected kos (usbip-core.ko & usbip-host.ko) can't be generated.
Thank you all!

**Comment by divx118** [comment]
@xinheng0816 I don't think this has something todo with crouton. Crouton is a bunch of scripts to create chroots for chromebooks. I suggest you look at some driver red hat build guides/fora/irc channels and if you want to ask there, you should at least describe what you exactly have done and what errors you encounter. Sorry we can't get you much help here.

**Comment by xinheng0816** [comment]
@divx118  
Thanks for your response.
Let me describe my quesiton more clearly.
**Precondition:**
OS:  RedHat 7.3
Linux kenel: Linux version 3.10.0-514.el7.x86_64

**Background:**
As required, i need to setup usbip env in my Linux station,  so I'm considerring to build usbip source code locally.

**Problem:**
Until now, I downloaded the specified linux kernel source code (3.10.0-514.el7).  Following https://wiki.centos.org/HowTos/BuildingKernelModules, when I execute below command under root directory of linux kernel source, I can't build out the expected Ko files.
$ make
$ make M=drivers/staging
Expected result:
usbip-host.ko and usbip-core.ko can be generated
Actual result:
From build log, I saw  drivers/staging/usbip wasn't built at all.

Thanks for you time and expect your instruction!!

**Comment by divx118** [comment]
Like I said before this is not the git you should ask these questions. This here are crouton based issues.
You should ask on one of the centos mailing list https://wiki.centos.org/GettingHelp/ListInfo
You probably need to enable the build of the usbip somewhere in your config. For more info please ask on centos and not here.

Thanks for your understanding.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
