### ISSUE TITLE
Installing to USB drive; install can't move bootstrap files to the chroots directory. Says device or resource busy/ is read only

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3450]
I am trying to install a xenial Ubuntu to a USB drive, where the -p specification is working in starting the process. After the install hits the extracting phase and moves on to this command: 

Moving bootstrap files into the chroot...

It consistently fails with the message:
    

mv: inter-device move failed: '/tmp/crouton.4N2/xenial-amd64/bin' to '/run/crouton/media/removable/USB Drive/chroots/xenial/bin'; unable to remove target: Read-only file system

That error pops up about 20 times before it ends the whole install at a similar error with the ending:
      
...to remove target: Device or resource busy.

I tried reformatting the drive and made sure that I could write files on it.

I tried to use an SD card I had on hand, and this install process worked, but the system was super slow due to the abysmal read/write performance of the card. Moving to the USB drive, I'm not sure what is different. I tried reformatting the drive and made sure that I could write files on it. Chronos sees the drive as valid, though it lists the drive as vFAT, **I know it is in ext4, confirmed by my local drive's xfce chroot** (out of space, ~600MB left due to one thing, an 18GB MatLab install, hence a second crouton system), and the drive is mounted and clear before install. I tried reformatting the drive and made sure that I could write files on it.

**Comment by DennisLfromGA** [comment]
@GrimGrape,

> mv: inter-device move failed: '/tmp/crouton.4N2/xenial-amd64/bin' to '/run/crouton/media/removable/USB Drive/chroots/xenial/bin'; unable to remove target: Read-only file system

Perhaps copy it instead of moving it and when complete reboot and delete the chroot on the internal drive.
 
Here's the `edit-chroot` syntax, very similar to move '-m' only using '-C' to copy -
```
    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.
    -C DEST     Like -m, but copies instead of moves.
```

*Hope this helps,*
-**DennisL**

**Comment by ipstone** [comment]
Just a comment on the SD card - I am trying to do the same but the behavior of ChromeOS mounting the  card is somewhat bizzar (I read somewhere that ChromeOs will not auto-mount ext4, but in my chromebook/s, it did mount the drive)... but bizzar thing is the SD card will become unrecognizable after some time ... 

A related issue is that if the SD card is formatted as FAT, then the performance is good at 40M/sec (reading), but once in ext4 format, the speed is abysmal - I think that's the reason why the performance of Crouton is slow on the SD card - I think it's the driver of SD card on ubuntu - it has been reported else where.

So the problem on SD-card seems to be mostly driver related.
