### ISSUE TITLE
[Question] Is it possible to "export" all of my files on crouton so that I can use them on another computer?

### ISSUE THREAD

**Issue by EtchJetty** [dnschneid/crouton#3452]
I love crouton. I use my setup almost every day. It's speedy, customizable, and everything I would want out of a laptop. In fact, it's what I want out of a desktop, too. My question is, is it possible to move everything from my Chromebook (files, programs, repositories, settings, etc) to a Linux setup on a desktop? Or would I have to manually reinstall everything? I've already backed up my chroot onto a USB drive, but I've got no idea if that's the right first step or not.

**Comment by RyanGamingXbox** [comment]
What do you mean? Also of you want to move files make sure it is in the Downloads folder, it is shared with crouton and chromeos.
