### ISSUE TITLE
LUKS (Linux Unified Key Setup) Does Not Work

### ISSUE THREAD

**Issue by nkhabarov** [dnschneid/crouton#3453]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: precise
encrypted: yes, unlocked
crouton: version 1-20170901092920~master:0216f9d1
release: precise
architecture: armhf
xmethod: xorg
targets: lxde
host: version 9765.81.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Oct 9 00:37:31 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes

#### Please describe your issue:
Here is the problem that popped up after upgrading to new Chrome OS - cannot open LUKS encrypted device:

(precise)root@localhost:~# cryptsetup luksOpen --key-file ./key2_file /dev/mmcblk1 encryptedS
/dev/mapper/.qFeWCH: lsetfilecon failed: Permission denied
/dev/mapper/.1n5rdv: lsetfilecon failed: Permission denied
/dev/mapper/temporary-cryptsetup-3617: open failed: No such file or directory
Failed to open temporary keystore device.
Failed to read from key storage.

#### If known, describe the steps to reproduce the issue:
The just one step needed is above. Here is strace grepped output:
...
mknod("/dev/mapper/.Z4fKP7", S_IFBLK|0660, makedev(254, 2)) = 0
chown32("/dev/mapper/.Z4fKP7", 0, 6)    = 0
lsetxattr("/dev/mapper/.Z4fKP7", "security.selinux", "system_u:object_r:fixed_disk_device_t:s0", 41, 0) = -1 EACCES (Permission denied)
...
I suspect the problem is SELinux in the host OS and I am curious if anything can be done to solve it.

**Comment by DennisLfromGA** [comment]
Unfortunately, the 'precise' release isn't supported any longer.
Hopefully, this issue is confined to it.

-**DennisL**

**Comment by nkhabarov** [comment]
Thank you, Dennis. Yes, there were indeed other problems with 'precise'. Installing 'xenial' release has solved the problem.

-Nikolay
