### ISSUE TITLE
Unbuntu Software Center

### ISSUE THREAD

**Issue by TheMinigun** [dnschneid/crouton#3454]
The issue is that basically i try to install things on the unbuntu software center i get this out put: Software can't be installed or removed because the authentication service is not available. (org.freedesktop.PolicyKit.Error.Failed: ('system-bus-name', {'name':  ':1.94'}): org.debian.apt.install-or-remove-packages Followed By: You dont have permission to perform this action PLEASE HELP as i would like to get java on the crouton Linux distribution

**Comment by DennisLfromGA** [comment]
Probably a dup of this: Installing Apps not Working #3442

**Comment by johanson** [comment]
Try starting software-center using sudo.
`gksudo software-center `most likely.

**Comment by TheMinigun** [comment]
Thanks the gksudo command helped and i am able to install things now

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
