### ISSUE TITLE
How do you get back on Linux after Chromebook restarts?

### ISSUE THREAD

**Issue by vitaly200326** [dnschneid/crouton#3455]

**Comment by DennisLfromGA** [comment]
@vitaly200326,

You didn't tell us what desktop you use, or anything else about your chroot, but here's an example of what you need to do for an xfce4 desktop -

- When you first powerup and the login screen appears enter your credentials and login.
- Press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>T</kbd> to get a crosh prompt.
- Enter '`shell`' to get a bash shell prompt.
- To launch your desktop enter: `sudo startxfce4`

*Hope this helps,*
-**DennisL**

**Comment by vitaly200326** [comment]
Thanks @DennisLfromGA ! Ill try this next time my chromebook shuts off.

**Comment by vitaly200326** [comment]
Thanks @DennisLfromGA

**Comment by DennisLfromGA** [comment]
@vitaly200326,

The command you're using to launch your desktop isn't correct.
That's one of the reasons we ask for the output of: `sudo edit-chroot -all`
It will tell us what target/desktop you installed.
However, I'll make a guess that you installed Unity so to launch use:
- `sudo startunity` 

If that doesn't work then you need to show us or tell us what you installed.

*Hope this helps,*
-**DennisL**

**Comment by vitaly200326** [comment]
Yes that worked thank you very much @DennisLfromGA
