### ISSUE TITLE
16.04 goes to black screen when I try to go back to Chrome

### ISSUE THREAD

**Issue by Alanba42** [dnschneid/crouton#3457]
Just upgraded to 16.04 and everything works fine BUT

When I use Shift-Control-Alt-F1 to go back to Chrome I get a black screen. I can Shift-Control-Alt-F1 and go back to Crouton. Can go back and forth, but no Chrome. Problem still there when I re-boot

name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9592.96.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Sep 16 09:59:24 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:


#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
@Alanba42,

Try pressing the <kbd>F4/full screen</kbd> and/or <kbd>F5/switch window</kbd> keys and see if the display comes back.

*Hope this helps,*
-**DennisL**

**Comment by Alanba42** [comment]
nope, still black

**Comment by DennisLfromGA** [comment]
@Alanba42,

Then try 'xiwi' -
1. `sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`
2. Install the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension.
3. Launch it using: `sudo startxfce4 -X xiwi-tab`

*Hope this helps,*
-**DennisL**

**Comment by Alanba42** [comment]
Works fine. Thanks

**Comment by DennisLfromGA** [comment]
@Alanba42,

I know your original issue isn't resolved but if you're satisfied with the outcome you can close this issue if you like.

-**DennisL**

**Comment by Alanba42** [comment]
and now it is not working again. Trying to load it gives me a cannot connect to extension message


chronos@localhost / $ sudo startxfce4 -X xiwi-tab
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Oct 15 16:57:57 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=b4a52e4c-2a90-234d-bbcd-a697b113e0f1/PARTNROFF=1 hashtree=PARTUUID=b4a52e4c-2a90-234d-bbcd-a697b113e0f1/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=1900f0e499f08dd20a263c11fc4ce3f4415bc11c salt=0e5a5d9efc99a9870423311dcf0dcc88a85186d58926ca929b2a21e892ba5b82" noinitrd vt.global_cursor_default=0 kern_guid=b4a52e4c-2a90-234d-bbcd-a697b113e0f1 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 13 October 2017  01:57:05PM
xorg-server 2:1.18.4-0ubuntu0.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Oct 29 07:57:26 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 9765.85.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Oct 15 16:57:57 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from https://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by DennisLfromGA** [comment]
@Alanba42,

This may be the same or a similar issue:

- Having issues connecting to crouton integration extension #3477

There are some troubleshooting steps to follow in that thread.

*Hope this helps,*
-**DennisL**
