### ISSUE TITLE
Resolved: USN-3455-1: wpa_supplicant and hostapd vulnerabilities https://www.krackattacks.com/ .... edit: looks good

### ISSUE THREAD

**Issue by westmj** [dnschneid/crouton#3458]
```
Please paste the output of the following command here: sudo edit-chroot -all

chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue:

How do we get upgrades/patches that take care of recent wpa2 vulnerability?

https://www.krackattacks.com/
https://usn.ubuntu.com/usn/usn-3455-1/

I can not seem to find my version of wpa_supplicant . 

Whoops!  There it is:

(trusty)westmj@localhost:~$ sudo wpa_supplicant -v
wpa_supplicant v2.1
Copyright (c) 2003-2014, Jouni Malinen <j@w1.fi> and contributors

Looks good!


#### If known, describe the steps to reproduce the issue:

**Comment by divx118** [comment]
@westmj chromeos will take care of that. Wifi or ethernet connection are handled by chromeos which is the host of your chroot.

**Comment by DennisLfromGA** [comment]
Discussed [here](https://productforums.google.com/d/msg/chromebook-central/GaQ64xem3wQ/VdNO0LyOAwAJ) in Chromebook Central:

> Ernest - Community Manager said:
>>Hi everyone,

>>We're aware of the issue, and a patch will be rolling out to any affected devices in the coming weeks

>Thanks!

And fixes addressed here: [Search for status:open krack](https://chromium-review.googlesource.com/#/q/status:open+krack)

*Hope this helps,*
-**DennisL**
