### ISSUE TITLE
Accidentally went off dev mode and it restore my chromebook and deleted chroot 

### ISSUE THREAD

**Issue by DavidVUSA** [dnschneid/crouton#3459]
```
Please paste the output of the following command here: sudo edit-chroot -all (Dont have chroot anymore, havent tried to install due to the following issue)
```

#### Please describe your issue:

My chromebook died and when plugged back on the screen with "OS verification is off - press space to re-enable" came up (which i understand is normal on developer mode) and somebody pressed space, it immediately said that it was deleting all my files and bringing it back to factory. The big problem is that i had very important and sensitive files saved on the linux chroot that i had installed. Is there a way to restore those files?? or bring back the chroot normally? 

Thanks in advance.

**Comment by DennisLfromGA** [comment]
@DavidVUSA,

Please refer to the response I gave you on Crouton Central -

- [Accidentally went off dev mode and it restore my chromebook and deleted chroot](https://groups.google.com/d/msg/crouton-central/2jjnjxHp19U/Gj5-0-p_BAAJ)

*Hope this helps,*
-**DennisL**
