### ISSUE TITLE
Chromebook (running Crouton, xiwi) automatically closes session, dumps tabs, erases data

### ISSUE THREAD

**Issue by penthimos** [dnschneid/crouton#3460]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170828233514~master:f9765f9a
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,keyboard,unity
host: version 9765.81.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-15956-gde0b452850f1 #1 SMP PREEMPT Mon Oct 9 00:43:09 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```
I'm having the problem described here:
https://productforums.google.com/forum/#!msg/chromebook-central/hRQyFET05l8/Jq0DXqcFAQAJ

The local experts said that this problem is Crouton-related. I'm reproducing my original post because it is still all I know: 

"I have an ASUS Chromebook C300S with updated OS, with developer mode activated and running Ubuntu 16.04 via Crouton (I'm not sure which of these features is relevant). When I close the lid, my session is usually logged out within five minutes. I have been taking the computer abroad in situations where I don't have wifi and where retention of browsing data is critical, and would be happy with a mere suspension, but instead the session quits and I have to restore all these tabs. Usually there is not connection to restore them with. Any changed preferences in programs in Ubuntu are also lost when this happens because functionally the plug is being pulled on the session without a proper shutdown. This behavior has already cost me many hours of lost productivity. 

"The Stay Awake extension has been suggested in other answers to similar questions I've found online, but it doesn't really do what I want (I do not actually want the device unsuspended when the lid is closed) and also doesn't stop my sessions from logging out.

"What can I do to fix this?"

P.S.: It was suggested in the thread that a rogue chrome extension was responsible for these difficulties. It wasn't: I disabled all but the "crouton integration" extension and the problem persisted.

**Comment by DennisLfromGA** [comment]
@penthimos,

Take a look at this issue and comment, maybe it'll help:

- [What's a good way to recover from `Disconnected` due to power management? #3451](https://github.com/dnschneid/crouton/issues/3451#issuecomment-335863510)

*Hope this helps,*
-**DennisL**

**Comment by penthimos** [comment]
Hi DennisL,

Thanks for this! But it seems like a different kind of problem, no? I am happy with my computer sleeping, and I never have an error message when I get back, but it always closes all my tabs and makes me have to restore them when I log in, as well as deal with whatever consequences arise from Ubuntu not having been properly shut down. I suppose if it never sleeps, it won't log me out, but this is a pretty severe option as regards battery life? What I'd really like is to not get logged out completely whenever the device sleeps.

**Comment by DennisLfromGA** [comment]
@penthimos,

> When I close the lid, my session is usually logged out within five minutes.

> ... but instead the session quits and I have to restore all these tabs.

Logged out of which session, you're Chrome OS account or your crouton chroot account/session?

It sounds like it's logging you out of your Chrome OS account - it shouldn't, it should just sleep and then prompt you for a password to resume. All of your tabs and apps that were previously in use should still be there. If this is happening I don't think it's at all 'crouton' related. Perhaps an extension has gone awry.

 >  **_I am happy with my computer sleeping_**, and I never have an error message when I get back, but it always closes all my tabs and makes me have to restore them when I log in, as well as deal with whatever consequences arise from Ubuntu not having been properly shut down.

If that's what's happening it doesn't sound like you're happy.
Why not just change the behavior of the lid closure to not sleep when it's closed?

*Hope this helps,*
-**DennisL**

**Comment by penthimos** [comment]
The Chrome OS session requires me to type my password, and Chrome starts
with one blank tab and prompts me to restore. It usually takes some ten
minutes to reload the tabs. One of those tabs is inevitably my crouton
session, and this is also inactive. Anything I've done in Ubuntu, such as
saving preferences, is often undone, and sometimes other sensitive things
are misconfigured. So what happens in the Ubuntu partition is much like
what happens if my regular laptop just is shut off with the power button
without doing a proper shutdown.

I didn't believe this problem should be crouton-related either, but the
people at that forum said it was. Shutting down all the extensions except
the crouton extension had no effect, but when I did shut down that
extensions (not that I could bear to do it for long, because much of what I
do on that computer uses crouton), the log-out problem seemed to have gone
away. I can redo the experiment if it would help, and would be happy to
send any diagnostics.

I think I wasn't quite clear with the passage you've bolded. I am happy, *in
principle*, with my computer going to sleep sometimes, but not *in practice
*if every time it sleeps, the consequence is that it dumps all my work!

I will disable sleeping if that's what it takes to resolve this, but I
think my battery will run out much faster. Part of why I don't just log out
every time in the first place is because I don't want to have to take the
time to charge it very frequently, and want to be able to use it quickly in
places without an outlet available, but that advantage will be lost if the
battery is always running down in my bag unless I want to do a full
shut-down and start-up.

**Comment by DennisLfromGA** [comment]
@penthimos,

> The Chrome OS session requires me to type my password, and Chrome starts
with one blank tab and prompts me to restore.

That sounds like the browser is crashing not just sleeping.

> I didn't believe this problem should be crouton-related either, but the
people at that forum said it was.

I saw your issue on Chromebook Central -
> In ChromeOS here is how it behaves:

> 1) login to your Chromebook, the Chrome browser auto launches. Open some tabs. Then:
> 2) **if you put the CB to sleep by closing the lid the tabs should still be there on awake UNLESS you locked it, closed down the browser or logged off in which case a new session is started.**

> If you get something other than the above then you might have **an interfering extension or something else wrong with your user profile, in which case you need to do a browser reset or a powerwash.**

> **With Crouton you can change the behaviour of browser sessions so the above does not apply and you are on your own and should visit their forums.**

Not to nit pick but I don't think that necessarily points to 'crouton' unless of course you 'change the behaviour of browser sessions'.

> Shutting down all the extensions except
the crouton extension had no effect, but when I did shut down that
extensions (not that I could bear to do it for long, because much of what I
do on that computer uses crouton), the log-out problem seemed to have gone
away.

That definitely seems 'extension' related like I suspected.
Since the browser is crashing along with the 'xiwi' tab as an experiment why don't you try to launch your desktop in a window or fullscreen instead of in a tab.

You can do that with one of the following:

- To launch in a window (the default): `sudo startxfce4`
- To launch in a fullscreen: `sudo startxfce4 -X xiwi-fullscreen`

*Hope this helps,*
-**DennisL**

**Comment by penthimos** [comment]
That's fair. I'd forgotten the details of their request I go here.

I'll try opening it in a fullscreen instead and see how that goes. I think
it defaults to a fullscreen window, actually. That way I can switch with
the "switch window" button as if it were a different desktop. Maybe I
should make it open in one tab instead? How can I check these defaults.

I just opened up the Chromebook, which had been charging since my last
message, and it opened fine. I need to start keeping statistics on this,
but could it be that it worked because this time, it is plugged in?

My session does usually seem to crash, but the computer doesn't shut down,
so is there any place errors related to this log-out behavior might be
found?

**Comment by DennisLfromGA** [comment]
@penthimos,

Perhaps some more experimentation with windowed vs. fullscreen vs. xiwi-tabs might help, probably couldn't hurt.

In Chrome OS *'Settings' -> 'Advanced' -> 'Privacy and security'* if you enable *'Automatically send diagnostic and usage data to Google'* then Google should be getting your crash reports. 
However, you can navigate to '[chrome://crashes/](chrome://crashes/)' and select *'Provide additional details'* on the latest crash to give them more details. You won't get a reply or response but they *will* definitely read your logs and act accordingly.

*Hope this helps,*
-**DennisL**

**Comment by penthimos** [comment]
OK, sorry for the huge delay. I've found that this shutdown happens
independent of whether I'm running Crouton, although it took a long time
for me to accidentally run a session without it and thus discover this. So
I suppose I should take the problem back to Google, although they basically
said because I was running Crouton they wouldn't consider it. Advice?

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
