### ISSUE TITLE
"xiwi in a window" problem: mute/volume/brightness keys do not work after update to ChromeOS ver 61/62

### ISSUE THREAD

**Issue by kapilhp** [dnschneid/crouton#3462]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: min
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/min...
crouton: version 1-20170901092920~master:0216f9d1
release: buster
architecture: amd64
xmethod: xiwi
targets: xiwi,x11
host: version 9901.46.0 (Official Build) beta-channel cyan 
kernel: Linux localhost 3.18.0-16036-g30f3f9ed6ff1 #1 SMP PREEMPT Thu Oct 12 22:02:10 PDT 2017 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:

In brief. When one uses xiwi in a window, the special keys like volume/brightness control no longer work. (They worked fine with Chrome OS version 59 and possibly 60.) On the other hand these keys work with xiwi in a tab.

Specificially, if I run: 'sudo startxiwi -b -n min xterm', this opens a window. As long as focus is in this window, the volume/brightness keys don't work. The "expose" key (F5) works to close the window. After that the volume/brightness keys work (the xiwi window is not in focus.)

On the other hand, if I run: sudo startxiwi -T -b -n min xterm', this opens xiwi in a tab. Now the special keys work fine.

By keys "working", I mean that volume goes up/down, muting is toggled, brightness goes up/down and so on. On-screen display also works. Note that the "manual" host-dbus CLI method works in both cases.

#### If known, describe the steps to reproduce the issue:

I tried to test this in various ways:

1. Create a new chroot with Debian "stretch" (instead of "buster") containing a minimal installation for xiwi.

2. Powerwash and (1).

The same result as before. I have no way of going back to ChromeOS 59/60 to check that it works with that version. However, I recall that the keys worked before the most recent updates to 61/62.

**Comment by DennisLfromGA** [comment]
@kapilhp,

Perhaps adding the '[keyboard](https://github.com/dnschneid/crouton/blob/master/targets/keyboard)' target will help: 

- DESCRIPTION='Adds support for Chromebook keyboard special keys.

It addresses the volume/brightness control keys and many others

*Hope this helps,*
-**DennisL**

**Comment by kapilhp** [comment]
Adding the 'keyboard' target did not do the trick. In fact, I suspected that it might not since it seems to "trap" the keys and send them to the crouton extension, whereas the behaviour that I expect (and 
which was the default earlier) was that the keys were handled by ChromeOS.

As I said above, the keys work "like they should" (i.e. like they did earlier) when the XMETHOD is xiwi-tab. They don't work when the XMETHOD is xiwi-window.

So something seems to have changed (post version 61) in the way ChromeOS manages applications that run in their own window. The keys like volume up/down are sent to the application rather than handled by ChromeOS or perhaps extensions have to indicate to Chrome which way they want to go.

Kapil.
--

**Comment by DennisLfromGA** [comment]
@kapilhp,

> So something seems to have changed (post version 61) in the way ChromeOS manages applications that run in their own window.

You're probably right but I don't know what might have changed upstream, sorry.
Maybe someone else will have some ideas...

-**DennisL**

**Comment by kapilhp** [comment]
Turning on "debug" in the crouton extension shows that the volumeup key is *not* being passed to the extension if it is running in a tab. However, it *is* being passed to the extension if it is running in a window or fullscreen. In spite of that, running "xev" shows that the volumeup key does not generate an event in the latter case. So there is some mis-match between the configuration of the X server and the way the extension interacts with it.

**Comment by kapilhp** [comment]
Some more info via debug button in the crouton extension.
The BrightnessUp key produces the following:
`Key DOWN: C:BrightnessUp,JSKC:d9=>KC:e9`
On the other hand the VolumeUp key produces:
`Key DOWN: C:AudioVolumeUp,JSKC:af=>KC:0(KEY UNKNOWN!)`
This seems to indicate that the latter is not even being recorded by the X server as a proper key.

Also followed up DennisL's suggestion a bit further. If the `keyboard` target is installed and `xbindkeys` is run with a suitable binding, then the Search+BrightnessUp/Down keys do appear to do the right thing. Even in this case, the VolumeUp/Down/Mute do not seem to be recognised by `xbindkeys` (probably as made clear by the above "debug" run of the crouton extension).

Moreover, this action seems to be taken by the programs inside the chroot, whereas, I think that earlier they *were* handled by ChromeOS directly.
