### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by DeadRoblox** [dnschneid/crouton#3463]
When I start the computer using the os it says system program problem detected. It said something about gnome-session-client and compwiz or something like that. I really dont know what it means and am wondering if my computer is dying or something. If you can help or know what is causing this then please tell me.

**Comment by TheMinigun** [comment]
[hs_err_pid29513.log](https://github.com/dnschneid/crouton/files/1396527/hs_err_pid29513.log)
(This is an error log that might help)

**Comment by DennisLfromGA** [comment]
@TheMinigun,

To help us help you troubleshoot a problem we ask that you *please* show us the out;put of:

- `sudo edit-chroot -all`

----
The log you linked above clearly states:

- "A fatal error has been detected by the Java Runtime Environment:"

Perhaps you first need to search for answers on [StackExchange](https://stackexchange.com/) or pursue other Linux resources.

*Hope this helps,*
-**DennisL**

**Comment by TheMinigun** [comment]
sudo edit-chroot: command not found.

**Comment by DennisLfromGA** [comment]
@TheMinigun,

Then first launch your crouton desktop, open a terminal session and show us the output of:

- `croutonversion`

*Hope this helps,*
-**DennisL**
