### ISSUE TITLE
Kali Linux Problems

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [dnschneid/crouton#3464]
Kali Linux will not install 1-2 packages wont install 
I too like to tinker with your work I added mate desktop environment and used fedora
but kali is the only one that does not download all the packages!!!

ALSO please add Feddora for normal install eg
 sudo sh ~/Downloads/crouton -r feddora -t xfce
and add mate 
sudo sh ~/Downloads/crouton -r trusty -t mate

Thanks I want to contribute if I can!!!

**Comment by EnderNightLord-ChromeBook** [comment]
Oh and the thing that happend
I: Extracting sensible-utils...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting util-linux...
I: Extracting zlib1g...
Moving bootstrap files into the chroot...
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/bin’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/boot’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/debootstrap’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/dev’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/etc’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/home’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/lib’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/proc’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/root’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/run’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/sbin’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/sys’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/tmp’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/usr’: No such file or directory
mv: cannot create directory ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/var’: No such file or directory
rm: cannot remove ‘/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling’: Device or resource busy
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
