### ISSUE TITLE
can't switch back to chrome os after installing elan touchpad driver for Acer C720P

### ISSUE THREAD

**Issue by TimFH** [dnschneid/crouton#3465]
### Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: trusty
Enter encryption passphrase for trusty: 
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170901092920~master:0216f9d1
release: trusty
architecture: amd64
xmethod: xorg
targets: core,extension,audio,chromium,x11,xorg,gtk-extra,touch,unity,unity-desktop
host: version 9765.81.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Oct 9 00:22:23 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

#### Please describe your issue:
I used the script on https://github.com/dnschneid/crouton/wiki/Acer-C720-C720P to install the Elan touchpad driver, and that seems to have worked fine save for the fact that I can no longer use shift-ctrl-alt-F1/F2 to switch between Ubuntu/trusty and ChormeOS. I will paste the ouput of edit-chroot -all after I reboot my way back to ChromeOS so that I can ... done!

#### If known, describe the steps to reproduce the issue:
as above (but, after I rebooted, I found myself with a different login screen, which implies that Chrome OS updated recently; perhaps that has something to do with it, but I doubt it since it was only a matter of minutes between when I installed the Elan touchpad driver, switched back to Chrome OS as usual, killed unity, exited and re-entered the trusty chroot, re-started unity, and then found I couldn't switch back)

**Comment by DennisLfromGA** [comment]
@TimFH,

Perhaps running `croutoncyle cros` in a chroot shell session will switch you back to CrOS.
I use it occasionally to switch to other chroots and CrOS.

*Hope this helps,*
-**DennisL**

**Comment by TimFH** [comment]
@DennisLfromGA 

Wow, that worked immediately, and even more astonishing is the fact that after doing it I was able to use shift-ctrl-alt-F1/F2 to switch back to Unity, and then again back to Chrome OS, and then back again!

Thank you!
