### ISSUE TITLE
The reason to backup your chroot

### ISSUE THREAD

**Issue by pierslawrence** [dnschneid/crouton#3467]
Just a few minutes ago, by Acer C720 chromebook decided to reboot (not sure the reason why, possibly updating itself). I herd the beep on the "OS verification is off" screen from another room and came up to see that it began repairing itself--after finishing this it rebooted and I come to the screen saying that Chrome OS is missing or damaged. My Friday is only going to get worse....

Unfortunately for me, it has been a while since I have backed up my chroot. What I am wondering about is what are my options?

I can use the legacy boot to boot into a USB drive with Xubuntu  on it, but I am not really sure enough about the internals to see what I might be able to recover from my chroot, or how to (or if I can) mount and back up any of my chroot.

So the information I can provide about the chromebook is:

On the Chrome OS is missing page it tells me:

Peppy C8A-W3C-E8S

The chroot I want to back up is a xenial release.

Not really sure what other info I can give.

**Comment by DennisLfromGA** [comment]
@pierslawrence,

It can be done, I do it on my Chromebook, it's setup as a dual-boot system.
I'll try to provide the steps needed below, bear in mind my system is setup differently than yours and most others too so you'll have to adjust the locations, etc. to fit your needs.

------
Here's what I do -
- Bootup Linux (Linux Mint dual-boot setup on my Chromebook)
- Mount /dev/sda1 (stateful_partition) for access

`sudo mkdir /var/cros`
`sudo mount /dev/sda1 /var/cros`

- Check to ensure the (/dev/sda) partitions are mounted 

```
mount|grep /dev/sda
/dev/sda1 on /var/cros type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda7 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda13 on /var/crouton type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

- Ensure your chroots are there (depends on the mountpoint you used)

`ls -l /var/cros/crouton/chroots/`
(empty)

- NOTE: The above is empty since I have my crouton chroots and archives stored on a custom partition

```
ls -l /var/crouton/chroots/
total 36K
drwxr-xr-x. 20 root root 4.0K Mar 28  2017 gentoo/
drwxr-xr-x. 23 root root 4.0K Sep  6 13:09 kodi/
drwxr-xr-x  23 root root 4.0K Sep  3 14:52 trusty/
drwxr-xr-x. 23 root root 4.0K Mar 10  2017 xen.elem/
drwxr-xr-x  24 root root 4.0K Mar 10  2017 xenial/
drwxr-xr-x  23 root root 4.0K Mar 10  2017 xenial-lxqt/
drwxr-xr-x  23 root root 4.0K Mar 10  2017 xenial-mate/
drwxr-xr-x. 23 root root 4.0K Aug 14 10:10 xen.unity/
drwxr-xr-x. 24 root root 4.0K May 17 17:53 zesty/

ls -l /var/crouton/archive/chroots/
total 24G
-rw-r--r--. 1 denny denny 2.0G Apr 22 15:05 gentoo-20170422-1501_DellCB13.tar.gz
-rw-r--r--. 1 denny denny 1.2G Sep 11 22:49 kodi-20170911-2147_DellCB13.tar.gz
-rw-r--r--. 1 denny denny 969M Mar 16  2017 precise-20170316-1642_DellCB13.tar.gz
-rw-r--r--  1 denny denny 2.5G Jul  7  2016 trusty-20160617-1133_DellCB13.tar.gz
-rw-r--r--  1 denny denny 1.9G Aug 27  2016 trusty-20160827-1233_DellCB13.tar.gz
-rw-r--r--  1 denny denny 2.4G Sep 24  2016 trusty-20160924-1852_DellCB13.tar.gz
-rw-r--r--. 1 denny denny 4.1G Sep  3 14:46 trusty-20170903-1439_DellCB13.tar.gz
-rw-r--r--. 1 denny denny 643M May 13 14:32 xen.elem-20170513-1430_DellCB13.tar.gz
-rw-r--r--. 1 denny denny 643M May 13 16:14 xen.elem-20170513-1612.tar.gz
-rw-r--r--  1 denny denny 1.5G Jul  9  2016 xenial-20160709-2126_DellCB13.tar.gz
-rw-r--r--. 1 denny denny 1.4G Oct 15 14:13 xenial-20171015-1410_DellCB13.tar.gz
-rw-r--r--  1 denny denny 730M Jul 25  2016 xenial-lxqt-20160725-1320_DellCB13.tar.gz
-rw-r--r--  1 denny denny 730M Aug 27  2016 xenial-lxqt-20160827-1406_DellCB13.tar.gz
-rw-r--r--  1 denny denny 3.5G Aug 27  2016 xenial-mate-20160827-1411_DellCB13.tar.gz
```

- Backup your chroot(s) using tar
- (I use something like this, your variables will be different)

```
tar -cf - ${CHROOTS}/${CHROOT}/ -P 2>/dev/null |\
  pv -i 5 -w 80 -berps $(du -sb ${CHROOTS}/${CHROOT} |\
  awk '{print $1}') |\
  gzip > ${DESTDIR}/${BACKUP}
```

-----
Save your chroot backup(s) to external media, the cloud, etc., just somewhere safe and accessible.
You can use 'crouton' to restore your chroot(s) after a powerwash, recovery, etc.

-----
*Hope this helps,*
-**DennisL**

**Comment by pierslawrence** [comment]
Thanks for the response.

I was able to mount /dev/sda1 on /var/cros as you have done. It mounts successfully but has only one folder "unencrypted" with the following log file in it:

>2017/10/20 11:38:28 UTC (repair): /dev/sda1 Self-repair corrupted stateful partition
dumpe2fs 1.43.4 (31-Jan-2017)
dumpe2fs: Bad magic number in super-block while trying to open /dev/sda1
Couldn't find valid filesystem superblock.
-- Ramoops (logs from last boot):
-- File system /dev/sda1 block data (gz+base64):

So perhaps it is a failing SSD drive.

Just to make sure I understand you correctly. In a normal crouton setup, the crouton directory would be mounted from /dev/sda1 (as opposed to your partition /dev/sda13)?

Regards,

Piers

**Comment by DennisLfromGA** [comment]
@pierslawrence,

>> 2017/10/20 11:38:28 UTC (repair): /dev/sda1 Self-repair corrupted stateful partition
dumpe2fs 1.43.4 (31-Jan-2017)
dumpe2fs: Bad magic number in super-block while trying to open /dev/sda1
Couldn't find valid filesystem superblock.
-- Ramoops (logs from last boot):
-- File system /dev/sda1 block data (gz+base64):

> So perhaps it is a failing SSD drive.

Ooh, that looks pretty bad, sorry.
I wouldn't necessarily say it's a failing SSD but it does look like the stateful_partition is/was corrupt.

> In a normal crouton setup, the crouton directory would be mounted from /dev/sda1 (as opposed to your partition /dev/sda13)?

Yes, that is correct.

Here's what my /dev/sda1 mounted as /var/cros looks like, this is a healthy system -
```
ls -l /var/cros/
total 559M
drwxr-xr-x   2 root root 4.0K Oct 19 15:59 backups/
drwxr-xr-x   3 root root 4.0K Oct 26  2016 crouton/
drwxr-xr-x  11 root root 4.0K May 20 14:39 dev_image/
drwxr-xr-x   2 root root 4.0K Aug 27  2016 encrypted/
-rw-------.  1 root root  18G Oct 20 15:21 encrypted.block
-rw-------.  1 root root   48 Apr 21 20:40 encrypted.key
drwxr-xr-x   3 root root 4.0K Jun  9 12:28 etc/
drwxr-xr-x   6 root root 4.0K Apr 21 20:40 home/
drwx------   2 root root  16K Aug 27  2016 lost+found/
-rw-r--r--   1 root root  17K Oct 20 15:21 shutdown_stateful_umount_failure
-rw-r--r--.  1 root root  189 Oct 20 15:21 umount-encrypted.log
drwxr-xr-x   4 root root 4.0K Aug 27  2016 unencrypted/

ls -l /var/cros/dev_image/bin/
total 22M
-rwxr-xr-x. 1 denny denny 3.7K Apr 22 15:06 chrootbu*
-rwxr-xr-x. 1 root  root  7.2K Sep  6 11:58 crash_reporter_wrapper*
lrwxrwxrwx. 1 root  root    11 Sep  6 11:58 delete-chroot -> edit-chroot*
-rwxr-xr-x. 1 root  root   32K Sep  6 11:58 edit-chroot*
-rwxr-xr-x. 1 root  root   34K Sep  6 11:58 enter-chroot*
-rwxr-xr-x  1 root  root   33K Aug 26  2016 enter-chroot.orig*
-rwxr-xr-x. 1 root  root   20K Sep  6 11:58 mount-chroot*
-rwxr-xr-x  1 root  root  5.0K Mar 11  2017 rw-rootfs*
-rwxr-xr-x. 1 root  root   727 Sep  3 14:51 startcli*
-rwxr-xr-x. 1 root  root   547 Mar 10  2017 startelementary*
-rwxr-xr-x. 1 root  root   537 May 15 21:36 startgnome*
-rwxr-xr-x. 1 root  root   546 May 15 21:36 startkde*
-rwxr-xr-x. 1 root  root   578 Sep  6 11:58 startkodi*
-rwxr-xr-x. 1 root  root   553 Sep  3 14:51 startlxde*
-rwxr-xr-x. 1 root  root   550 Mar 10  2017 startlxqt*
-rwxr-xr-x. 1 root  root   553 Mar 10  2017 startmate*
-rwxr-xr-x. 1 root  root   540 Aug 14 09:44 startunity*
-rwxr-xr-x. 1 root  root   536 May 15 21:36 startxfce4*
-rwxr-xr-x. 1 root  root  2.1K Sep  6 11:58 startxiwi*
-rwxr-xr-x. 1 root  root   19K Sep  6 11:58 unmount-chroot*
```

It doesn't look very promising at all, I don't see anyway to recover/backup your chroot(s) now.

I would suggest doing a [complete recovery](https://support.google.com/chromebook/answer/1080595?hl=en) which will reformat your Chromebook using OEM partitions & sizes. That will probably fix any issues with the stateful partition. It will of course wipe out any user data so you'll have to add your account(s) again, etc.

*Hope this helps,*
-**DennisL**

**Comment by pierslawrence** [comment]
After poking around on the web, it does seem all a little bit disappointing that I will have to do a complete recovery.

I came across this post: [https://productforums.google.com/forum/#!topic/chromebook-central/JI0P07mghKU](https://productforums.google.com/forum/#!topic/chromebook-central/JI0P07mghKU)

Giving a bit of hope that there might be a way to recover the data. Does anyone here have an idea how I might be able to take an image of the disk in order to run some sort of data recovery on the drive?

Thanks!

**Comment by DennisLfromGA** [comment]
@pierslawrence,

I saw the Chromebook Central topic but I don't think the '--preserve_stateful' flag will help in your situation since the stateful partition is already corrupt.

You might be able to boot a Linux OS and run 'fsck' or other repair utilities to try and fix it, I don't think it would hurt anything at this point.

That's about all I know though, I've never been able to fix a corrupt stateful partition but maybe others have - let's hope so.

*Hope this helps,*
-**DennisL**

**Comment by pierslawrence** [comment]
@DennisLfromGA Thanks for all of your input. Unfortunately, after a few days of frantically trying to get my data back, the drive has given up completely.

What I did try in the for the last few days was to follow the [Ubuntu Data Recovery](https://help.ubuntu.com/community/DataRecovery) Wiki to see what I could recover from the drive. So far it is really not been promising.

I have tried to recover an image from the drive. First attempt with `ddrescue`
`sudo ddrescue -r 3 /dev/sda1 /media/piers/chroot.img logfile` 
It had numerous read errors so I had to run it a few times to recover an image:
`sudo ddrescue -r 3 -C /dev/sda1 /media/piers/chroot.img logfile` 

This extracted a 631MB image from the disk... not looking good. I subsequently ran `foremost` on the image file:

`foremost -w -i chroot.img -o /media/piers/recovery`

in the resulting audit.txt it shows 0 files 

After that unsuccessful attempt I tried testdisk, and used the backup option to take an image of the disk. It did throw out a bunch of read errors. On completion, I recovered about 5.3GB of something, however, after running foremost on the image file, nothing was found.

I ran testdisk a bunch more times, getting different quantities of data each time. After one reboot, the drive failed completely, now I am stuck waiting for a new 128GB replacement which should arrive tomorrow. (The legacy boot option also got disabled, annoyingly).

It would be nice to know how it is best to set up the bigger drive once I have run the recovery of Chrome OS. Any pointers would be appreciated.

Kind regards,
Piers

**Comment by DennisLfromGA** [comment]
@pierslawrence,

> It would be nice to know how it is best to set up the bigger drive once I have run the recovery of Chrome OS. Any pointers would be appreciated.

If by that you mean create a larger custom partition for your crouton chroots the way I did it was using @drinkcat's "crouton in a separate partition" branch that's no longer viable.

I can tell you one way that would still work though and is what I now use going forward -
- resize "partition 7 / ROOT-C" using the '[chrx](https://github.com/reynhout/chrx#usage)' script choosing the size you want to reserve for crouton and anything else. Don't steal too much space from partition 1 tho, you can get in trouble with that.
- If you want it just for crouton then don't run 'chrx' a second time. Now you mount '/dev/sda7' as '/var/crouton' or whatever you like and store your crouton chroots and backups there. You'll have to use '`-c /var/crouton/chroots`' when launching your desktops, etc.
- If you want to install a dual-boot Linux distro then run 'chrx' a second and install the [distro](https://github.com/reynhout/chrx#operating-systems) of your choice. This is what I do and then just make a subdirectory for crouton.

*Hope this helps,*
-**DennisL**

**Comment by pierslawrence** [comment]
I have a bit of a technical question about how chroots are stored. Is this encrypted with the google credentials? If so, is there a way to decrypt an image of the stateful_partition?

I ask because I have managed to take images (of differing sizes) of the failing drive, but running photorec on it, I am surprised that it does not find anything at all.

Cheers,
Piers

**Comment by DennisLfromGA** [comment]
@pierslawrence,

Without using 'crouton's encryption '-e' option they aren't encrypted at all and reside on the unencrypted space in `/usr/local/chroots` - as opposed to the encrypted user space in `/home/chronos/user`.

But with chroot encryption this is how 'crouton's message describes it:

> Encrypted chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.

*Hope this helps,*
-**DennisL**
