### ISSUE TITLE
Prevent leaving chroot for adb

### ISSUE THREAD

**Issue by DanHolli123** [dnschneid/crouton#3468]
I've been wanting to run adb on my chromebook, I got it working with a few alias, but every time i do a command it starts and ends crouton, I'd like in to not close the chroot so I can continue using adb while saving time.

I have the aliases as `alias adb="sudo enter-chroot adb"` and `alias fastboot="sudo enter-chroot fastboot"`

Is there something I could add to those so it doesn't automatically exit the chroot?

**Comment by DennisLfromGA** [comment]
@DanHolli123,

I'm not sure but if you have the 'xiwi' xmethod installled perhaps you could use '`startxiwi`' instead of '`enter-chroot`' using something like this -

`sudo startxiwi -f adb` and `sudo startxiwi -f fastboot`

Here's the usage & command syntax for '`startxiwi`' -
```
chronos@localhost ~ $ startxiwi
startxiwi [options] chroot_app [parameters]

Wraps enter-chroot to launch a window or tab in Chromium OS for any graphical application.
Applications launched in this way show in independent windows or tabs.

By default, it will use the primary user on the first xiwi-enabled chroot found and launch
the chroot_app in a window.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -F          Launch the chroot_app full-screen.
    -T          Launch the chroot_app in a tab.
    -f          Prevent xiwi from quitting automatically. (see NOTE below)

NOTE:
xiwi will normally close when the application returns. Some gui applications
fork before or during normal operation, which can confuse xiwi and cause it to
quit prematurely. If your application does not have a parameter that prevents
it from forking, and crouton is unable to automatically detect the fork, you can
use -f to prevent xiwi from quitting automatically.
xiwi will quit if you close the Chromium OS window when nothing is displayed.
  
You can cycle through multiple windows inside the application
via Ctrl-Alt-Tab/Ctrl-Alt-Shift-Tab, or close them via Ctrl-Alt-Shift-Escape.
If the chroot_app begins with 'start' but you still want to
use the default window manager, specify the full path of the application.
```

You can even add the '-T' option to launch it in a tab, pretty slick.

*Hope this helps,*
-**DennisL**

**Comment by DanHolli123** [comment]
They are command line tools, they don't have a gui of any sort, just terminal input and output

**Comment by kapilhp** [comment]
You *could* run `sudo enter-chroot`. This will give you a bash shell inside the chroot. You can *then* run `adb` from the command line. When you quit from `adb` you will still be in the bash shell inside the chroot. not sure if this is what you want!

-Kapil.

**Comment by DanHolli123** [comment]
I'd prefer if i can just have the chroot still running, but still be able to use it directly from the chromebook shell like that if possible without entering the chroot's bash command line

**Comment by divx118** [comment]
@DanHolli123 can't you just use adb/fastboot which is available in the chromeos shell? 
```
chronos@localhost / $ which adb
/usr/bin/adb
chronos@localhost / $ which fastboot
/usr/bin/fastboot
```

**Comment by kapilhp** [comment]
> I'd prefer if i can just have the chroot still running, but still be able to use it directly from the chromebook shell like that if possible without entering the chroot's bash command line

A chroot is "running" as long as it is mounted *and* there is a program running inside it.

You can use "mount-chroot" to mount the chroot. You can use "enter-chroot long_running_program" to ensure that it does not unmount the chroot until the long_running_program exits. I don't know if this is what you want but you can do the following (`-b` forks and runs in the background):
`sudo enter-chroot -b sleep 3600`
After this, your chroot will remain mounted for one hour while you can run a program like
`sudo enter-chroot adb` as often as you like without the need to mount the chroot again. (Basically, you will save the time required to mount and unmount the chroot each time.)

Perhaps this helps.

-Kapil.

**Comment by DanHolli123** [comment]
@divx118 I've already tried that with 3 different methods, none worked.
@kapilhp thank you, I can just add that to my commands, thank you

**Comment by DennisLfromGA** [comment]
@DanHolli123,

I know this issue is closed and you've found a resolution but I thought I'd mention this article I just came across that's a pretty nifty way to run Android Studio in a xiwi window/tab -

- ### [Developing Android Apps, right on your Chromebook](https://android.jlelse.eu/developing-android-apps-right-on-your-chromebook-f3a00cb78e0e)

I hope that someday soon we'll be able to run Android Studio and other apps & even OS'es in containers on Chrome OS.

*Hope this helps,*
-**DennisL**

**Comment by DanHolli123** [comment]
Thanks for the tip @DennisL, I'll look into it.

-----Original Message-----
