### ISSUE TITLE
Unable to finish setup after initial install

### ISSUE THREAD

**Issue by IsaiahJean** [dnschneid/crouton#3470]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
![screenshot 2017-10-21 at 3 59 24 am](https://user-images.githubusercontent.com/21188893/31849683-3f3312b8-b5fb-11e7-805b-91c3da5fee28.png)

#### Please describe your issue:
Won't let me finish the setup. Above error keeps popping up.

#### If known, describe the steps to reproduce the issue:
I used ```sudo sh -e ~/Downloads/crouton -t xfce``` to install Crouton. Then ran following code ```sudo startxfce4``` to start new desktop environment.

**Comment by DennisLfromGA** [comment]
@IsaiahJean,

It may be bombing out on your device with 'xorg'.
Do this then show us what's displayed for 'croutonversion' -

- `sudo enter-chroot -n xenial`
- `croutonversion`
- `exit`

*Hope this helps,*
-**DennisL**

**Comment by IsaiahJean** [comment]
![screenshot 2017-10-21 at 6 15 03 pm](https://user-images.githubusercontent.com/21188893/31856315-d24dbb12-b672-11e7-989c-ee67141558f6.png)

**Comment by DennisLfromGA** [comment]
@IsaiahJean,

Thanx for the 'croutonversion' output.
I didn't notice any message like '*Would you like to finish the setup?*' so it seems to have finished okay.

But, there seems to be problems with the 'xorg' xmethod on devices employing ARM chips like you Samsung Chromebook.

There are some things you could try to fix it, see below -
- [Help! I´m just a newbie trying to install Linux on my ARM Chromebook..and STUCK! #3359](https://github.com/dnschneid/crouton/issues/3359#issuecomment-327838969)

And there is a workaround using 'xiwi' instead of 'xorg', see below -
- [Linux will not start after installing. Three other users have had this problem: "Fatal server error: (EE) AddScreen/ScreenInit failed for driver 1" #3291](https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813)

Personally, I like to use the 'xiwi' xmethod and run my chroot in a tab, YMMV.

*Hope this helps,*
-**DennisL**

**Comment by IsaiahJean** [comment]
@DennisLfromGA 
I'm sorry Dennis, I'm new to this and really confused. Here is a screen shot when i tried the method you linked in your reply.

![screenshot 2017-10-22 at 7 28 26 pm](https://user-images.githubusercontent.com/21188893/31867548-8e37a3e6-b746-11e7-939c-4dbaf0bd17e4.png)

I tried to install it with out xorg. It shows the above message. what do I do next or am I doing something wrong?

**Comment by DennisLfromGA** [comment]
@IsaiahJean,

There are no spaces allowed when specifying targets so it spit out the usage display.
But I don't think you want to install another chroot, you can just add 'xiwi' to your existing chroot like this:

- `sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

Then install the '[crouton integration]()' extension from the Chrome Web Store.
Now can can launch your desktop with any of the following:

- `sudo startxfce4 -X xiwi` (that will launch in a window via 'xiwi')

- `sudo startxfce4 -X xiwi-fullscreen` (that will launch fullscreen via 'xiwi')

- `sudo startxfce4 -X xiwi-tab` (that will launch in a browsing tab)

*Hope this helps,*
-**DennisL**

**Comment by IsaiahJean** [comment]
@DennisLfromGA 

this is after `sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`
![screenshot 2017-10-22 at 10 04 43 pm](https://user-images.githubusercontent.com/21188893/31869324-0d1f8664-b75c-11e7-93ee-20a2573dabfb.png)

this is after `sudo startxfce4 -X xiwi`
![screenshot 2017-10-22 at 10 07 18 pm](https://user-images.githubusercontent.com/21188893/31869383-5f4d78b0-b75c-11e7-8032-83dd960905e3.png)

**Comment by DennisLfromGA** [comment]
@IsaiahJean,

The first screenshot shows you're having trouble with 'xserver-xorg-video-dummy' package.
I think you can fix it by doing the following:
- `sudo enter-chroot`
   ( If asked *"'Would you like to finish the setup? [Y/n/d]'"* enter '**n**' )
- `sudo apt remove xserver-xorg-legacy`
- `exit`
- `sudo enter-chroot -xx`

Now try to launch your desktop again:
- `sudo startxfce4 -X xiwi`

*Hope this helps,*
-**DennisL**

**Comment by IsaiahJean** [comment]
@DennisLfromGA 

wierd

![screenshot 2017-10-22 at 10 57 56 pm](https://user-images.githubusercontent.com/21188893/31870565-71584b8c-b763-11e7-81cc-1743df6f3d48.png)

**Comment by DennisLfromGA** [comment]
@IsaiahJean,

Sorry, it's late and I'm clearly not thinking clearly. :)
Let me look at it tomorrow and we'll try again.

-**DennisL**

**Comment by IsaiahJean** [comment]
@DennisLfromGA 

Sure, thanks for taking time out of your day to help. I really appreciate it.

**Comment by waldoxhm** [comment]
same issue and solved
first
`sudo enter-chroot`
`sudo apt-get remove xserver-xorg-core-hwe-16.04` in chroot
`exit`then logout.
`sudo sh ~/Downloads/crouton -u -t xiwi -n xenial` in shell
`sudo startxfce4 -X xiwi` make sure you installed the crouton extension before running it

**Comment by IsaiahJean** [comment]
@waldoxhm 
You're the man! It works! Thanks alot.

**Comment by DennisLfromGA** [comment]
@waldoxhm,

Thanx for stepping in and helping out.
I hadn't run into that issue so was at a bit of a loss as to what was wrong and how to fix it.
## *Teamwork!*

-**DennisL**
