### ISSUE TITLE
no dpkg or apt-get in core or cli-extra

### ISSUE THREAD

**Issue by lucasgonze** [dnschneid/crouton#3476]
```
$ sudo edit-chroot -all
Password: 
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: cli-extra,xiwi
host: version 9765.85.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-15958-g5ed7bd9927cb #1 SMP PREEMPT Sun Oct 15 17:47:19 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

1. Running under startcli. 
2. dpkg is not installed. apt-get is not installed.

I can go find dpkg, and that's probably what I'll do, but not having it suggests there is some setup step I have missed, because it's so basic. 

Is there a standard bundle with all that kind of basic goo, like git, gcc, dpkg?

Thanks in advance. And hella thanks for crouton.

**Comment by lucasgonze** [comment]
Installing gnome did the trick.

**Comment by DennisLfromGA** [comment]
@lucasgonze,

I don't know if installing the '[gtk-extra](https://github.com/dnschneid/crouton/blob/master/targets/gtk-extra)' target would have done the trick or not but I usually install it if it's not required by anything else.
I think any desktop target would do the trick though, and '[gnome](https://github.com/dnschneid/crouton/blob/master/targets/gnome)' is a nice one.

*Hope this helps,*
-**DennisL**
