### ISSUE TITLE
Having issues connecting to crouton integration extension

### ISSUE THREAD

**Issue by dolanthewise** [dnschneid/crouton#3477]
```
Please paste the output of the following command here: sudo edit-chroot -all
sudo edit-chroot -all
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20170901092920~master:0216f9d1
release: stretch
architecture: arm64
xmethod: xiwi
targets: kde,xiwi,gnome,core,extension,audio,keyboard,xorg
host: version 9765.85.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.70-11386-g8271523ecf43 #1 SMP PREEMPT Sun Oct 15 17:38:26 PDT 2017 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
```

#### Please describe your issue:
Whenever I try to start a desktop environment, it gets through the first few steps but always gets stuck on "cannot connect to extension, retrying..." and does about ten times and then it says "Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from https://goo.gl/OVQOEt)" but I do have it installed and enabled and then it runs exit commands. I'm at a loss because I've tried a lot of things. 

```
Entering /mnt/stateful_partition/crouton/chroots/stretch...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-3-arm64 aarch64 Debian
Current Operating System: Linux localhost 4.4.70-11386-g8271523ecf43 #1 SMP PREEMPT Sun Oct 15 17:38:26 PDT 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=a769d5a1-b39d-b24d-9717-737c4f9c398f/PARTNROFF=1 hashtree=PARTUUID=a769d5a1-b39d-b24d-9717-737c4f9c398f/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=05c383fb44e0a8c8ff56e65634260390c7ea82c1 salt=ee7b0e43a91ec93dc9ea579b4f00cffb709e2c3b7910fa66296e5c025f620972" noinitrd vt.global_cursor_default=0 kern_guid=a769d5a1-b39d-b24d-9717-737c4f9c398f  
Build Date: 07 July 2017  06:15:16AM
xorg-server 2:1.19.2-1+deb9u1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Oct 27 10:21:17 2017
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20170901092920~master:0216f9d1
release: stretch
architecture: arm64
xmethod: xiwi
targets: kde,xiwi,gnome,core,extension,audio,keyboard,xorg
host: version 9765.85.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.70-11386-g8271523ecf43 #1 SMP PREEMPT Sun Oct 15 17:38:26 PDT 2017 aarch64 GNU/Linux
freon: yes
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from https://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/stretch...
```
#### If known, describe the steps to reproduce the issue:
I installed all the necessary targets and then tried launching kde and gnome

**Comment by DennisLfromGA** [comment]
@dolanthewise,

I have experienced it giving up but it's pretty rare for me.
I'm not sure what it might be but maybe turning on the debugging and logging options might help give us some more clues. You can toggle them on/off by clicking on the 'crouton integration' extension in the toolbar at the top, see below -

![screenshot 2017-10-27 at 11 43 21 am](https://user-images.githubusercontent.com/3418772/32112869-814d4112-bb0c-11e7-9c76-224db81b9865.png)


*Hope this helps,*
-**DennisL**

**Comment by dolanthewise** [comment]
Yeah, I thought that might be it, but that didn't work either.

**Comment by DennisLfromGA** [comment]
@dolanthewise,

What didn't work?
You didn't any debugging logs?

-**DennisL**

**Comment by Alanba42** [comment]
I tried to load and kept getting the same problem with 
Cannot connect to extension, retrying...
and then being dropped. Tried it several times. Then I tried it with debugging and logging activated and it worked. Not sure that is the solution, but there it is.

**Comment by DennisLfromGA** [comment]
@Alanba42,

You didn't get any debugging logs to post either?

-**DennisL**

**Comment by espang** [comment]
I have similar problems:
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 9901.54.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.79-11650-ge987f76b729a #1 SMP PREEMPT Tue Oct 24 23:57:37 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
I have made screenshots from the shell and the logs of the crouton integration extension.


![screenshot 2017-11-09 at 08 52 29](https://user-images.githubusercontent.com/9658576/32596702-1806d2f2-c52c-11e7-81b0-16e647391deb.png)
![screenshot 2017-11-09 at 08 52 15](https://user-images.githubusercontent.com/9658576/32596703-181f97b0-c52c-11e7-8e83-fb42816a4448.png)

**Comment by DennisLfromGA** [comment]
@espang,

The crouton integration extension logs in both of the above screenshots show 'Connection established' at one point, is your desktop launching then or not? If not, I guess it thinks it opened and stopped trying but that's only a guess.

Maybe one of the devs or someone more familiar with this issue will drop by and help out.

-**DennisL**

**Comment by espang** [comment]
I am not sure. Most of the time it works fine and I don't know how to reproduce the error. Will check the next time this error occurs.
