### ISSUE TITLE
User accounts menu "unlock" feature not working (Unity)

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3478]
THIS ISSUE IS FOR UNITY UBUNTU!

Hey guys!
To add users I need to "Unlock" the settings right? But I can't for some reason? The button is blocked and says
"
System policy prevents changes.
Contact your system administrator
"
I use an Acer chromebook in dev mode, installed Crouton using the method at https://lifehacker.com/how-to-install-linux-on-a-chromebook-and-unlock-its-ful-509039343 and the download of crouton is at http://goo.gl/fd3zc
Please help thanks! :)

**Comment by icecream95** [comment]
Try adding users using `adduser` or `useradd`:

Run `sudo enter-chroot` to enter a shell then type `sudo adduser [USER]`, replacing [USER] with the name of the user you want to add. After answering the prompts, type `exit`.

You can now start unity for the new user with `sudo startunity -u  [USER]`.

**Comment by DennisLfromGA** [comment]
To add, you may encounter some issues with additional users id's, see https://github.com/dnschneid/crouton/issues/908#issuecomment-47890462 for some workarounds.

*Hope this helps,*
-**DennisL**
