### ISSUE TITLE
Linux asking me for password

### ISSUE THREAD

**Issue by KibSquib48** [dnschneid/crouton#3479]
I successfully installed crouton on my chromebook but many features require an admin password, such as installing steam and other apps, and I am guessing its the login password, but the problem is that I set no password for the Linux system, because it prompted me for a UNIX password, but it didnt let me type in any words. I then tried to change the password through the Linux system, and it still didn't let me type in anything other than enter. So then I looked here for answers and possibly a solution

**Comment by DennisLfromGA** [comment]
@MemesDank456,

In Linux when you are prompted for a password it won't show you what you are typing for better security but it *will* accept the characters you enter.

To assign a new or different password to the username you created in the chroot do this:
1. Get into the chroot as user 'root': 
    - `sudo enter-chroot -u root`

2. Run the 'passwd' command for the username you created:
    - `passwd [username]` (substitute [username] with yours)

3. Exit the chroot

Now you should be able to launch your desktop and/or terminal.
When you enter any 'sudo' or other command that needs root permissions it will prompt for *your* username's password, the one you just entered above.

*Hope this helps,*
-**DennisL**
