### ISSUE TITLE
good news about chromeos vs google's new fuchsia os / magenta kernel

### ISSUE THREAD

**Issue by coderofsalvation** [dnschneid/crouton#3480]
For those who wondered like me 'ohno..will crouton still work on newer chromebooks?'

> Answer: 99% yes

I got a bit worried, since i ♥♥♥ my chromeos/crouton setup.
It seems there's a lot of rumours online that chromeos *might* be replaced with fuchsia.
There's nothing factual (Except rumours) which points into that direction. 

## sources: 

* https://chromeunboxed.com/googles-fuchsia-os-some-perspective
* https://www.youtube.com/watch?v=fG10IFj3NQE
* https://www.youtube.com/watch?v=pibRpDmQ7kU

**Comment by dnschneid** [comment]
phew!
