### ISSUE TITLE
xiwi: crossover:i386: not found

### ISSUE THREAD

**Issue by Grace2354** [dnschneid/crouton#3482]
```
sudo sh /media/removable/SD\ Card/bin/edit-chroot -all
name: xenial
encrypted: no
Entering /media/removable/SD Card/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xiwi
targets: core,cli-extra,xiwi,xorg,xfce
host: version 9765.85.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 4.4.70-11386-g8271523ecf43 #1 SMP PREEMPT Sun Oct 15 17:37:03 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/SD Card/chroots/xenial...```

**#### Please describe your issue:**
I've been trying to launch CrossOver in a browser tab, but I haven't been able to do so.
My chroot is installed on an SD Card also, so I had to modify the way to launch it.
Here's what I use:
**#### If known, describe the steps to reproduce the issue:**
sudo sh '/media/removable/SD Card/bin/enter-chroot' xiwi -F 'CrossOver'(also: crossover, crossover:i386, crossoveri386)
Entering /media/removable/SD Card/chroots/xenial...
Unknown username "geoclue" in message bus configuration file
xiwi: CrossOver: not found
Unmounting /media/removable/SD Card/chroots/xenial...
Sending SIGTERM to processes under /media/removable/SD Card/chroots/xenial...

**Comment by tblaschke** [comment]
seems that you installed CrossOver in a non-standard path. Just specify the complete path to start it.
Btw. There is an android version of CrossOver such you don't need Crouton at all to run crossover. [Link](https://www.codeweavers.com/products/crossover-chromeos)

**Comment by Grace2354** [comment]
unfortunately, my Chromebook doesn't have android support as of yet. It's a CB3-111. 
How would I go about specifying the complete path? Would it be something like: '/directory/directory/cxoffice/microsoft.blah'?

**Comment by Grace2354** [comment]
This works, the only issue I have is that the view is rather small.

![screenshot 2017-11-01 at 1 51 39 pm](https://user-images.githubusercontent.com/30673725/32289644-a8c0eb7c-bf0d-11e7-8b1b-76538a95ec5f.png)
This is when the xiwi screen is defaulted (not fullscreen)

![screenshot 2017-11-01 at 1](https://user-images.githubusercontent.com/30673725/32289667-c0eaa59e-bf0d-11e7-8017-26c3a6804d4e.png)
This is what happens when I try to make it fullscreen

I don't have this issue with other programs, I'm guessing it has something to do with the Crossover program itself

**Comment by tblaschke** [comment]
You made the xiwi window fullscreen but it seems your office is not registering the change. Try to press the windowed and then the fullscreen button on the office decorator to see if it's size gets adjusted. If not then start office from the beginning in a fullscreen xiwi window.

**Comment by Grace2354** [comment]
Sorry for the long delay!
I wasn't able to fix the xiwi window, and when I started it in fullscreen, it had the same issue, unfortunately. I will tinker some more to see if there's a way around this. For now, marking it as closed though.
