### ISSUE TITLE
Cannot access chroot

### ISSUE THREAD

**Issue by kevomaco** [dnschneid/crouton#3484]
```
Please paste the output of the following command here: sudo edit-chroot -all
mount: mount(2) failed: /run/crouton/mnt/stateful_partition/crouton/chroots/gnome: No such file or directory
Failed to mount gnome.
```

#### Please describe your issue:
I cannot access my chroot.  Every attempt leads to a No such file or directory error.  I have deleted the chroot in question and restored from a backup from before the error occured, but the problem persists.

This seems to have started after my most recent OS update.

I installed a new test chroot with:
sudo sh ~/Downloads/crouton -t core -n test

I can access it fine.

I have a Chromebook Pixel 2015 with OS version: 61.0.3163.123 (Official Build) (64-bit)

I would prefer not to Powerwash my machine as it is always a chore, but I will if necessary.

**Comment by DennisLfromGA** [comment]
@kevomaco,

No need to powerwash, that's rarely needed when dealing with 'crouton', if ever.

> mount: mount(2) failed: /run/crouton/mnt/stateful_partition/crouton/chroots/gnome: No such file or directory
Failed to mount gnome.

It looks like you have a leftover in '`/usr/local/chroots`' that isn't a valid chroot.

Please show us what's displayed when you enter:

- `ls -l /usr/local/chroots`

If the following doesn't work:

- `sudo enter-chroot -n gnome`

Then you may need to delete it with either:

- `sudo delete-chroot gnome`

or, if that fails use:

- `sudo rm -f /usr/local/chroots/gnome`

*Hope this helps,*
-**DennisL**

**Comment by kevomaco** [comment]
Successfully restored!

Thank you for the help.

I ended up just deleting and restoring the chroot, I am not entirely sure what was different.  Perhaps because I made a new test chroot?  Regardless, I can access my chroot, so the problem is resolved.

-Kevin
