### ISSUE TITLE
Installing Ubuntu Xenial/Trusty on Chromebook ASUS C200 Fails when trying to install base-passwd

### ISSUE THREAD

**Issue by stephensekula** [dnschneid/crouton#3485]
```
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: sid
encrypted: no
Entering /media/removable/wildebookssd/chroots/sid...
crouton: version 1-20170901092920~master:0216f9d1
release: sid
architecture: amd64
xmethod: xorg
targets: xfce-desktop
host: version 9765.85.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 4.4.70-11386-g8271523ecf43 #1 SMP PREEMPT Sun Oct 15 17:29:38 PDT 2017 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/wildebookssd/chroots/sid...
name: xenial
encrypted: no
Entering /media/removable/wildebookssd/chroots/xenial...
crouton: version unknown
release: unknown
architecture: unknown
targets: xfce-desktop
host: version 9765.85.0 (Official Build) stable-channel quawks 
kernel: Linux localhost 4.4.70-11386-g8271523ecf43 #1 SMP PREEMPT Sun Oct 15 17:29:38 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/wildebookssd/chroots/xenial...
```

(NOTE: I pasted the above after posting this bug report and rebooting the Chromebook. The failed installation seems to have left chroots in a bad state and mounting/unmounting them when this command runs is hanging. This was resolved by rebooting)

#### Please describe your issue:

When running this installation command:

```
sudo sh ./crouton -r xenial -t xfce-desktop
```

the process fails with this message (I've tried this about 10 times):

```
...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.39_amd64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.39_amd64.deb is at fault)
Failed to complete chroot setup.
Unmounting /media/removable/wildebookssd/chroots/xenial...
```
Disk space is NOT a problem:

```
chronos@localhost ~/Downloads $ df -h /media/removable/wildebookssd/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       118G  3.3G  109G   3% /media/removable/wildebookssd
```

also:

```
chronos@localhost ~/Downloads $ df -h /run/crouton/
Filesystem      Size  Used Avail Use% Mounted on
run             1.9G  620K  1.9G   1% /run
```

#### If known, describe the steps to reproduce the issue:

I have only tried these two methods of installation:

```
sudo sh ./crouton -r xenial -t xfce-desktop
```
```
sudo sh ./crouton -r xenial -t ubuntu-desktop
```

Both fail. I alternatively tried Debian Sid and that installed just fine. It seems to at least be Ubuntu Xenial that is the problem.

I have already tried the suggestions found here:

https://github.com/dnschneid/crouton/issues/2387

but that does not resolve the problem (the problem does not appear to be the cache). I have also tried updating crouton, re-downloading crouton, and even wiping my entire SSD and starting over. Something very specific must be happening here. 

Thanks in advance for the insights!

**Comment by stephensekula** [comment]
Brief update. Tried Trusty tonight, too. That also did not work, and failed installing in the same way. I dumped the contents of the log file it mentioned when it failed:
```
chronos@localhost ~/Downloads $ more /media/removable/wildebookssd/chroots/trusty/debootstrap/debootstrap.log
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg: error processing archive /var/cache/apt/archives/base-passwd_3.5.33_amd64.deb (--install):
 cannot get security labeling handle: No such file or directory
Errors were encountered while processing:
 /var/cache/apt/archives/base-passwd_3.5.33_amd64.deb
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 10 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 10 package 'dpkg':
 missing architecture
dpkg: error: parsing file '/var/lib/dpkg/status' near line 10 package 'dpkg':
 multiple non-coinstallable package instances present; most probably due to an upgrade from an unofficial dpkg
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg: error: parsing file '/var/lib/dpkg/status' near line 10 package 'dpkg':
 duplicate value for `Package' field
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
dpkg: error: parsing file '/var/lib/dpkg/status' near line 10 package 'dpkg':
 duplicate value for `Package' field
```

This seems to be the key error:

```
dpkg: error processing archive /var/cache/apt/archives/base-passwd_3.5.33_amd64.deb (--install):
 cannot get security labeling handle: No such file or directory
```

I have not tried other Ubuntu flavors, but this seems a common problem at least among two stable Ubuntu release targets.

**Comment by cd109876** [comment]
Identical issue on Samsung Chromebook Plus. Only difference is that I have an ARM CPU. 
`I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.39_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.39_arm64.deb is at fault)
Failed to complete chroot setup.`

**Comment by stephensekula** [comment]
Since there has been no support response to this report, and since the problem persists, I wanted to post here the contents of the debbootstrap.log file in the chroot:

```
dpkg: error processing archive /var/cache/apt/archives/base-passwd_3.5.39_amd64.deb (--install):
 cannot get security labeling handle: No such file or directory
Errors were encountered while processing:
 /var/cache/apt/archives/base-passwd_3.5.39_amd64.deb
```

**Comment by DennisLfromGA** [comment]
All,

>I: Installing core packages...
**W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.39_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.39_arm64.deb is at fault)**
*Failed to complete chroot setup.*

The above seems to point to an upstream bug, not a crouton issue but I'm no expert.
Hopefully, someone with more knowledge or even a crouton dev or will pop in to help out.

-**DennisLfromGA**

**Comment by dnschneid** [comment]
C200...Chromebook Plus...strange errors across architectures and distros...I smell selinux.

@smbarber?

**Comment by stephensekula** [comment]
So, just out of curiosity (and to try to revive this discussion), do we think it's SELINUX on ChromeOS that is causing all the trouble, or do we think it's SELINUX _during_ the installation of Ubuntu that is the problem? If it's the latter, why did it never affect installing 14.04 until last autumn? To me, I smell a change in ChromeOS that messed up all of this for Ubuntu... but then, why does it affect Ubuntu and not Debian? Thanks, @dnschneid!

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.
