### ISSUE TITLE
Pixelbook trackpad sensitivity

### ISSUE THREAD

**Issue by t0rv1c** [dnschneid/crouton#3487]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9901.54.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4. Tue Oct 24 23:57:37 PDT 2017 x86_64 x86_64 x86_64 GNU/Lin

```

Hi, I installed Crouton on my brand new Pixelbook. There is a problem with the trackpad. It is impossible to move around the arrow but it works when clicking the trackpad at the same time (but then it does a selection). Any idea what might be causing this issue? Thanks for your help.
I actually noticed that it's a sensitivity issue as if I press harder on the trackpad, I can move around. Not sure what can be done to fix this.

**Comment by seiflotfy** [comment]
Same here

**Comment by Hodges3902** [comment]
I am having the same issue.. here is the temporary fix I have been using...
`synclient FingerLow=1 FingerHigh=5`

**Comment by DennisLfromGA** [comment]
@Hodges3902,

Thanx for the workaround.
I haven't had a chance to play with it much but if I run into trouble I'll try that.

-**DennisL**

**Comment by t0rv1c** [comment]
@Hodges3902 Thanks for your help. It works better now. Now I have another annoying issue which I'm going to post in a separate thread: keystroke lag...
