### ISSUE TITLE
New Pixelbook - no forward button

### ISSUE THREAD

**Issue by letllve** [dnschneid/crouton#3488]
#### Please describe your issue:
Apologies if this has been posted before, I have tried to do some research before asking anything. I successfully installed everything and had ubuntu running fine, I can switch from ubuntu back to chromeos just fine. The issue if switching from chromeos to ubuntu as the new PIxelbook does not have a forward button. Is there a workaround for this? Can the buttons be remapped?

**Comment by DennisLfromGA** [comment]
@letllve,

On the Pixelbook, the <kbd>refresh</kbd> key works like the <kbd>forward</kbd> key did before, it's still more or less <kbd>F2</kbd>.

So you would now use:  <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>refresh/F2</kbd>.

I have a Pixelbook too and it's working just fine & dandy.

*Hope this helps,*
-**DennisL**
