### ISSUE TITLE
Issue with artful on Pixelbook

### ISSUE THREAD

**Issue by HedgeHodge** [dnschneid/crouton#3492]
```
name: artful
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/artful...
crouton: version 1-20170901092920~master:0216f9d1
release: artful
architecture: amd64
xmethod: xorg
targets: unity,touch
host: version 9901.54.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.79-11650-ge987f76b729a #1 SMP PREEMPT Tue Oct 24 23:57:37 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/artful...
```

#### Please describe your issue:

Every time I try to startunity I get this error.

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

#### If known, describe the steps to reproduce the issue:
sudo startunity

**Comment by ucmucm** [comment]
Same issue

**Comment by ucmucm** [comment]
Also, if I install xenial, the issue is becoming I cannot open the terminal.

**Comment by markstos** [comment]
Translation for "euid != 0" is "you are not root".  That said, I'm not sure why it's an issue here and not on Xenial.

**Comment by EnderNightLord-ChromeBook** [comment]
Artfull is a UNSUPPORTED release these releases are not stable and will mostly cause problems!
stick with LTS
