### ISSUE TITLE
noexec mount permission changes

### ISSUE THREAD

**Issue by KeithIMyers** [dnschneid/crouton#3493]
Just a heads up on some major changes coming to noexec mounts on ChromeOS relating to https://bugs.chromium.org/p/chromium/issues/detail?id=569168

I know Crouton runs a lot of things out of /tmp/, especially in the installer and will likely be rendered useless in ChromeOS 64+

**Comment by dnschneid** [comment]
Thanks for the heads-up!  This is a pretty big deal, but hopefully we'll be able to minimize the crouton impact.

**Comment by azet** [comment]
It's no longer possible to just run the `crouton` script downloadable from this website

example:
```
chronos@localhost ~/Downloads $ sh crouton 
sh: 0: Refusing to exec crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
```
