### ISSUE TITLE
sudo startxfce4 won't run after command

### ISSUE THREAD

**Issue by KnosisEgudin** [dnschneid/crouton#3494]
![screenshot 2017-11-06 at 9 52 46 pm](https://user-images.githubusercontent.com/33441995/32477763-b1aaa366-c33d-11e7-8a75-42e2a750db63.png)
![screenshot 2017-11-06 at 9 38 59 pm](https://user-images.githubusercontent.com/33441995/32477386-fdb77b06-c33a-11e7-848f-52f194b96547.png)
![screenshot 2017-11-06 at 9 34 37 pm](https://user-images.githubusercontent.com/33441995/32477391-03307c9a-c33b-11e7-96a2-bfe6a3b6e6d7.png)

**Comment by DavidBeale** [comment]
Getting the same issue, after latest chromeOS update

**Comment by DeepForestGreen** [comment]
Me, too. I've updated my Croot, but it's the same message. Glad I'm not the only one. Anyone got a clue?

**Comment by DennisLfromGA** [comment]
Some fixes have recently been applied; please update your chroot(s) and then try to launch your desktop(s) again. If they fail again show us the output.

*Hope this helps,*
-**DennisL**

**Comment by DeepForestGreen** [comment]
I just upgrade my Croot using this command: "run sudo sh ~/Downloads/crouton -t xfce."

But I'm getting the same problem when I try "sudo startxfce4"

I appreciate any insight. Here's what I get:

Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 31 22:07:48 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashtree=PARTUUID=9c4a8b66-bf2d-8344-b395-cc24c0f465ca/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=a10b60a9429fc895093ffd0e5e68ee9d0247e61f salt=daefda212e1fad73b5b94f147e155dda617674c8eeb19f772b00eb224775242c" noinitrd vt.global_cursor_default=0 kern_guid=9c4a8b66-bf2d-8344-b395-cc24c0f465ca add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 13 October 2017  01:57:05PM
xorg-server 2:1.18.4-0ubuntu0.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Nov 11 17:27:41 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by DennisLfromGA** [comment]
@DeepForestGreen,

> I just upgrade my Croot using this command: "run sudo sh ~/Downloads/crouton -t xfce."

That command will not update your chroot.

It might be best for to start with this troubleshooting guide: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**

**Comment by DeepForestGreen** [comment]
I appreciate your help. As usual, I know enough to screw things up.

Now the problem is a lack of storage space. I've removed everything from my Chromebook's download folder and it says the same thing. Earlier I removed many files and it went from 50mb available to 0. I'm slightly confused.

However, I was able to use the Shell to find the files I need, so it looks like a power wash is in my future.

**Comment by DennisLfromGA** [comment]
@DeepForestGreen,

The 'Downloads' folder is where the user's files are stored by default.
You can clean that folder and still have space issues if you've installed crouton or other things.

crouton chroots are stored in '/usr/local/chroots' by default. You can delete one or more chroots with the `delete-chroot` command. Usually deleting your chroot(s) and removing unnecessary files in 'Downloads' is enough to regain plenty of space. 

A powerwash will remove all user data including anything in 'Downloads' and *any and all* chroots in /usr/local/chroots' so it's kind of a drastic step but sometimes necessary.

*Hope this helps,*
-**DennisL**

**Comment by DeepForestGreen** [comment]
The strange thing is that every time I deleted stuff it would say I had LESS free space. I have no idea what kind of math it's doing, but I sense I screwed something up. Either way, lucky for me I run a very sparse setup, and powerwashing and resetting things is done in a blur. I'm already back to normal. Thanks for your help, though. Thanks to you, I'll do a much better job in the future when this comes up again.

**Comment by AndyGaskell** [comment]
I think I may be having the same problem.  I've got a HP 14" and since the ChromeOS update yesterday I've been hitting this error when I start the crouton.

It's not disk space, as I've got plenty of room.

Starting the crouton...
```sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
Setting up mysql-server-5.7 (5.7.18-0ubuntu0.16.04.1) ...
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of stop.
Renaming removed key_buffer and myisam-recover options (if present)
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of stop.
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
Upgrade process encountered error and will not continue.
mysql_upgrade failed with exit status 11
dpkg: error processing package mysql-server-5.7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-5.7; however:
  Package mysql-server-5.7 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-5.7
 mysql-server
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-45-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.79-11650-ge987f76b729a #1 SMP PREEMPT Tue Oct 31 22:02:27 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=56a7812d-07bf-b54b-8f83-c79f5770bc30/PARTNROFF=1 hashtree=PARTUUID=56a7812d-07bf-b54b-8f83-c79f5770bc30/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=42349f367481d97d923539ccd3fa3a5cfd2187ca salt=50dd750a4c99aeb692bf720136870bbea48d14fc74f4332a309608a21f6895d3" noinitrd vt.global_cursor_default=0 kern_guid=56a7812d-07bf-b54b-8f83-c79f5770bc30 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 02 November 2016  10:06:10PM
xorg-server 2:1.18.4-0ubuntu0.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Nov 16 19:40:16 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

Updating the crouton...

```sudo sh ~/Downloads/crouton -n xenial -u
/usr/local/chroots/xenial already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Setting up mysql-server-5.7 (5.7.18-0ubuntu0.16.04.1) ...
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of stop.
Renaming removed key_buffer and myisam-recover options (if present)
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of stop.
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
Upgrade process encountered error and will not continue.
mysql_upgrade failed with exit status 11
dpkg: error processing package mysql-server-5.7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-5.7; however:
  Package mysql-server-5.7 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-5.7
 mysql-server
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...```

I worked through the https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting page and did some google searches, but found no solution.  I'll try and figure it out, but any ideas or suggestions would be very welcome.

**Comment by DavidBeale** [comment]
I have update to the latest version, and the error has now changed to:

`Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist`

**Comment by pboxinator** [comment]
Anyone have any luck with this bug? I also have this bug. It looks to be pretty common and recent.

**Comment by bhaskarsuper9000** [comment]
Had the same exact problem as described by @KnosisEgudin 
Could get into chroot through enter-chroot though.
Updated to latest crouton
And then update xenial by
sudo sh ~/Downloads/crouton -n chrootname -u 
(from https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

Solved the issue. Can run X successfully again.

**Comment by pboxinator** [comment]
@bhaskarsuper9000 enter-chroot allows me to access the filesystem through the terminal, which helped me salvage some important files on my previously unaccessable partition. For this I thank you ^_^b
Otherwise, my problems continue...

**Comment by jkoudys** [comment]
@pboxinator I had this same problem, where I couldn't update my crouton install because the mysql install failure was blocking it. I still don't have a satisfactory resolution to the mysql-server errors (which cause it to update mysql-server, but apt fails to complete because it can't start/stop the server from a chroot), but I have X running again.

I forced my mysql-server package to uninstall by doing a dpkg purge: `dpkg -P mysql-server`, _then_ did the crouton update. Once that was finished I reinstalled mysql-server. My DBs are all there and I can `startxfce4` again.

**Comment by cor14095** [comment]
@jkoudys I tryed runing:
`dpkg -P mysql-server`
and got:
`dpkg is not a command.`

how did you run it?

**Comment by jkoudys** [comment]
sudo that

**Comment by cor14095** [comment]
@jkoudys 
`sudo: dpkg: command not found`
