### ISSUE TITLE
Xenial using GNOME won't start

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3495]
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
`Xenial fails to start due to a X server error:`

Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Sun Oct 15 17:45:31 PDT 2017 armv7l
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=9e17c183-7d90-b244-996a-f42177acafcc/PARTNROFF=1 hashtree=PARTUUID=9e17c183-7d90-b244-996a-f42177acafcc/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=ba8eee117d51320fef8a24a13f90c29f6ae8ad0e salt=036ec0eacec8a4c1ed1c25724ef564c3e68bb309daf136d037b401e690be0aed" noinitrd vt.global_cursor_default=0 kern_guid=9e17c183-7d90-b244-996a-f42177acafcc  
Build Date: 13 October 2017  02:13:29PM
xorg-server 2:1.19.3-1ubuntu1~16.04.4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Nov  6 21:52:27 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

`log file from /tmp/Xorg.crouton.1.log`

[  9626.917] 
X.Org X Server 1.19.3
Release Date: 2017-03-15
[  9626.917] X Protocol Version 11, Revision 0
[  9626.917] Build Operating System: Linux 4.4.0-97-generic armv7l Ubuntu
[  9626.917] Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Sun Oct 15 17:45:31 PDT 2017 armv7l
[  9626.917] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=9e17c183-7d90-b244-996a-f42177acafcc/PARTNROFF=1 hashtree=PARTUUID=9e17c183-7d90-b244-996a-f42177acafcc/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=ba8eee117d51320fef8a24a13f90c29f6ae8ad0e salt=036ec0eacec8a4c1ed1c25724ef564c3e68bb309daf136d037b401e690be0aed" noinitrd vt.global_cursor_default=0 kern_guid=9e17c183-7d90-b244-996a-f42177acafcc  
[  9626.918] Build Date: 13 October 2017  02:13:29PM
[  9626.918] xorg-server 2:1.19.3-1ubuntu1~16.04.4 (For technical support please see http://www.ubuntu.com/support) 
[  9626.918] Current version of pixman: 0.33.6
[  9626.918] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  9626.918] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  9626.919] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Nov  6 21:25:26 2017
[  9626.921] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  9626.923] (==) No Layout section.  Using the first Screen section.
[  9626.923] (==) No screen section available. Using defaults.
[  9626.923] (**) |-->Screen "Default Screen Section" (0)
[  9626.923] (**) |   |-->Monitor "<default monitor>"
[  9626.924] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[  9626.924] (==) Automatically adding devices
[  9626.924] (==) Automatically enabling devices
[  9626.924] (==) Automatically adding GPU devices
[  9626.924] (==) Automatically binding GPU devices
[  9626.924] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  9626.925] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  9626.925] 	Entry deleted from font path.
[  9626.925] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  9626.925] 	Entry deleted from font path.
[  9626.925] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  9626.925] 	Entry deleted from font path.
[  9626.925] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  9626.925] 	Entry deleted from font path.
[  9626.925] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  9626.925] 	Entry deleted from font path.
[  9626.925] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/Type1,
	built-ins
[  9626.925] (==) ModulePath set to "/usr/lib/arm-linux-gnueabihf/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[  9626.925] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[  9626.925] (II) Loader magic: 0xee2ef70
[  9626.925] (II) Module ABI versions:
[  9626.925] 	X.Org ANSI C Emulation: 0.4
[  9626.925] 	X.Org Video Driver: 23.0
[  9626.925] 	X.Org XInput driver : 24.1
[  9626.925] 	X.Org Server Extension : 10.0
[  9626.959] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[  9626.962] (II) xfree86: Adding drm device (/dev/dri/card1)
[  9626.962] (II) no primary bus or device found
[  9626.962] (II) LoadModule: "glx"
[  9626.965] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  9626.980] (II) Module glx: vendor="X.Org Foundation"
[  9626.981] 	compiled for 1.19.3, module version = 1.0.0
[  9626.981] 	ABI class: X.Org Server Extension, version 10.0
[  9626.981] (==) Matched modesetting as autoconfigured driver 0
[  9626.981] (==) Matched fbdev as autoconfigured driver 1
[  9626.981] (==) Assigned the driver to the xf86ConfigLayout
[  9626.981] (II) LoadModule: "modesetting"
[  9626.982] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  9626.984] (II) Module modesetting: vendor="X.Org Foundation"
[  9626.984] 	compiled for 1.19.3, module version = 1.19.3
[  9626.984] 	Module class: X.Org Video Driver
[  9626.984] 	ABI class: X.Org Video Driver, version 23.0
[  9626.984] (II) LoadModule: "fbdev"
[  9626.986] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[  9626.987] (II) Module fbdev: vendor="X.Org Foundation"
[  9626.987] 	compiled for 1.19.3, module version = 0.4.4
[  9626.987] 	Module class: X.Org Video Driver
[  9626.987] 	ABI class: X.Org Video Driver, version 23.0
[  9626.987] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  9626.987] (II) FBDEV: driver for framebuffer: fbdev
[  9626.987] (EE) 
Fatal server error:
[  9626.987] (EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
[  9626.987] (EE) 
[  9626.987] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[  9626.987] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  9626.987] (EE) 
[  9626.988] (WW) xf86CloseConsole: KDSETMODE failed: Bad file descriptor
[  9626.988] (WW) xf86CloseConsole: VT_GETMODE failed: Bad file descriptor
[  9626.988] (EE) Server terminated with error (1). Closing log file.

#### If known, describe the steps to reproduce the issue:
`sudo startgnome`

**Comment by zguithues** [comment]
this might be related to the xserver-xorg-legacy issue.  a fix was just merged into the release version of crouton yesterday.  try to update your chroot and it might fix your problem.

`sudo sh ~/Downloads/crouton -u -n CHROOTNAME`
run the above command substituting your chroot name.

please post back here whether this solves your problem or not.
