### ISSUE TITLE
Unable to get back to chromeOS

### ISSUE THREAD

**Issue by DanHolli123** [dnschneid/crouton#3497]
I'm running to latest supported version of Ubuntu on my Acer C720p

occasionally if I have it idle in KDE long enough, i the background or the foreground I'm unable to return to ChromeOS, but I'm able to get into KDE if I'm not already

**Comment by icecream95** [comment]
This might be a screensaver problem so try disabling it (try System Settings and/or xscreensaver).

**Comment by ibrado** [comment]
You mean via Ctrl-Alt-Shift-Forward/Back? I found that if I press the Overview key (box with two vertical lines beside the -Brightness key, it will then start to work again...
