### ISSUE TITLE
How to launch Crouton in X11 OR XIWI mode.

### ISSUE THREAD

**Issue by limegorilla** [dnschneid/crouton#3499]
`name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170901092920~master:0216f9d1
release: trusty
architecture: amd64
xmethod: xorg
targets: extension,xorg,xiwi,x11,unity,touch,core,audio
host: version 9765.85.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-15958-g5ed7bd9927cb #1 SMP PREEMPT Sun Oct 15 17:28:39 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...`

#### How on earth is this done?
Really all I want to do is boot into X11 when I just want to use an app like VLC but I want the option to boot into XIWI for apps like Android studio. I did install both when I installed unity, but for good measure I have just updated the chroot thusly: `sudo sh ~/Downloads/crouton -u -n trusty -t x11,touch,extension,xiwi` 

Yet when I launch Unity using the command `sudo startunity -x x11` or `sudo startunity -x xorg` (found it from a guide can't remember where, sorry)  it will fail, giving me this:
`Entering /mnt/stateful_partition/crouton/chroots/trusty...
chroot: failed to run command 'x11/xorg': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...`

So is this possible? Oh, and can I set it to default to X11 when booting?

**Comment by icecream95** [comment]
First of all, the target for X in a window is xiwi, not x11. x11 just installs either xorg or xiwi.

You need to use a capital X: lowercase x runs a command:

`sudo startunity -X  xiwi` (or xorg).

From the `enter-chroot` help:
>     -X XMETHOD  Override the auto-detected XMETHOD for this session.
>     -x          Does not log in, but directly executes the command instead.
>                 Note that the environment will be empty (sans TERM).
>                 Specify -x a second time to run the /prepare.sh script.

To set xiwi as default, you can install the xiwi target again:

`sudo sh -e ~/Downloads/crouton -u -n trusty -t xiwi`

**Comment by divx118** [comment]
@limegorilla @icecream95 is correct. So because you want to set X11 xorg as default you could use `sudo sh ~/Downloads/crouton -u -n <replace with name of your chroot> -t xorg`
@icecream95 FYI `-e` is not needed anymore since a couple of years it is already set in the scripts for example https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L6
