### ISSUE TITLE
Replace all usage of wget with curl

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#3501]
See https://crbug.com/781538

wget is going away, so we should switch to using curl.  Fortunately, the crouton meta-installer uses curl, so this will be transparent to users.

I think there are only a couple uses of wget that happen outside of the chroot, so those definitely need to change, but we should probably change the uses inside the chroot as well for consistency.

**Comment by nickpitlosh** [comment]
the crouton installer fails hard due to 3514
