### ISSUE TITLE
Remapping the "Google Asistant" key as Super key on the Pixelbook

### ISSUE THREAD

**Issue by nickjmeyer** [dnschneid/crouton#3505]
```
name: xenial-i3
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial-i3...
crouton: version 1-20171109145451~master:35a16889
release: xenial
architecture: amd64
xmethod: xorg
targets: x11
host: version 9901.66.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.79-11650-ge987f76b729a #1 SMP PREEMPT Tue Oct 31 22:05:39 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial-i3 as another instance is using it.
```

#### Please describe your issue:
With the new Pixelbook, we have an additional key.  The new key is the dedicated Google Assistant key, but conveniently its located where the Super / Windows key would usually be.  Is there any way to remap this key?  I seems like Chrome OS intercepts the keystroke because `xbindkeys -k` doesn't pick up the key press.

Any ideas for how to get Chrome OS to pass that keystroke to crouton?

**Comment by markstos** [comment]
From within an X11 environment in Crouton on the Pixelbook, run this:

     xev 2>&1 | grep keycode

Then press the super/assistant key, then Control-C to cancel capture mode.. On a Dell XPS 13 running Ubuntu, here's what I capture:

   state 0x10, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,

What do you get on the Pixelbook? If nothing, this may just confirm that ChromeOS isn't passing the key on through to Crouton.

**Comment by markstos** [comment]
Have you checked your keyboard settings in ChromeOS to see if the Assistant key can be remapped like the Search Key could? See: https://www.howtogeek.com/265207/how-to-remap-the-search-key-on-your-chromebook/

**Comment by nickjmeyer** [comment]
When running `xev` nothing shows up.  I also checked dmesg for any "unknown key" messages, but I don't see anything there either.  Chrome OS must not pass it through.

There is no option in settings to remap the key.  Here are the only keys available in the Chrome OS settings.
![screenshot 2017-11-13 at 11 13 44 pm](https://user-images.githubusercontent.com/9648755/32762637-886497c4-c8c8-11e7-9b2f-0559edb81d71.png)

I alos tried disabling the assistant thinking that maybe if it wasn't active, then the key might not get intercepted by Chrome OS.  Sadly that didn't work either.

**Comment by markstos** [comment]
I opened a feature request with the Chromium project to support this. We'll see if it goes anywhere: https://bugs.chromium.org/p/chromium/issues/detail?id=784857

**Comment by DennisLfromGA** [comment]
@markstos,

Thanx for that feature request, I '*' it to keep an eye on it, hopefully, it'll get some traction.

-**DennisL**

**Comment by nickjmeyer** [comment]
Whoops.  Looks like I accidentally closed this.  Sorry about that.

@markstos Thanks for posting that request.  Assuming it gets picked up, what does that process look like?  I'm pretty new to the Chrome OS world.  Does it get put into Chromium OS and then at some point google adds it to Chrome OS?  I imagine that's typically a long timeline?

**Comment by markstos** [comment]
@nickjmeyer I think it could happen quickly if there were traction, where "quickly" might still be a couple months before a stable release, but we have to see what the response is. I understand it's also possible to dual-boot Chromebooks, like with ChromeOS and Ubuntu. I haven't read about someone doing it on the Pixelbook yet. If you ran Ubuntu that way, I presume Ubuntu would be able access the Assistant key and would not be surprised to find that the Assistant Key already sends a "Super" keypress in that context. As a prospective Pixelbook owner, that's the most likely way that I would use the device for now,  as it would be too frustrating not to have a "Super" key when using Ubuntu via Crouton.

**Comment by DennisLfromGA** [comment]
The [feature request](https://bugs.chromium.org/p/chromium/issues/detail?id=784857#c3) is at Pri-2 but It's been 'assigned' so that's a good thing.

-**DennisL**

**Comment by markstos** [comment]
According to Chromium project docs, "assigned" means "in someone's work queue" and "Pri-2" means 
"P2 - Wanted for current milestone". So there's hope this could happen relatively soon, but a "want" is not a  "need".

**Comment by nickjmeyer** [comment]
You have good timing.  I was just looking up what those desginations meant.

This is awesome!

**Comment by DennisLfromGA** [comment]
I saw what 'assigned' means here: [Bug Life Cycle and Reporting Guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines)
But only saw a general reference to 'priorities' here: [Chromium Bug Labels](https://www.chromium.org/for-testers/bug-reporting-guidelines/chromium-bug-labels)

Just wondering where @markstos found the 'project docs' ???

Very interesting, thanx,
-**DennisL**

**Comment by markstos** [comment]
@DennisLfromGA, If you search for the phrase I pasted ["P2 - Wanted for current milestone"](https://encrypted.google.com/search?hl=en&q=%22P2%20-%20Wanted%20for%20current%20milestone%22), it takes you right to the [Triage Best Practices](https://www.chromium.org/for-testers/bug-reporting-guidelines/triage-best-practices) doc that I found.

**Comment by DennisLfromGA** [comment]
Thanx @markstos, still refining my googling skilz.

**Comment by rickybrent** [comment]
This sounds like a great idea; I don't mind having an assistant key, but right now it's dead in Xenial. :(

I think 784857 is a great feature request in its own right, but it won't actually help for this; Chrome OS can remap the search and ctrl keys and so on already and the chroot doesn't get the remapped versions.

The good news is that I don't think we need it, it's a valid (but fairly new) key in regular Linux too.  :) This might fix itself depending on the distro you use, or at least get to the point where the more common tools can handle remapping it.

Running 'sudo evtest /dev/input/event3' from inside the chroot and pressing KEY_ASSISTANT shows us:
```
type 4 (EV_MSC), code 4 (MSC_SCAN), value d8;
type 1 (EV_KEY), code 583 (?),
```
Also, the menu key in the top right is KEY_CONTROLPANEL; it shows up with the correct input event code as well. (579 is 0x243 in hex; code 583 is likewise 0x247, which looks right. Oddly it doesn't show the names for either even though we should have KEY_CONTROLPANEL, at least.)

I tried using a custom hwdb (which I *think* is the proper way to do it) with no luck yet; I had better luck using python to hack at it though.

**Comment by nickjmeyer** [comment]
Ah interesting.  I wasn't able to get it to show up with `xbindkeys`, but it looks like the chroot is still receiving the input.  Is that right?

**Comment by rickybrent** [comment]
Yep, that's exactly right -- xbindkeys only sees what Xorg sees, and Xorg [can't see keycodes over 255](https://bugs.freedesktop.org/show_bug.cgi?id=11227) I suspect this would Just Work in Wayland -- not with xbindkeys -- but didn't test.

Remapping the keys with [evdevremapkeys](https://github.com/philipl/evdevremapkeys) works nicely, but also remaps them in Chrome OS (it has to be run outside of X, and you must not close it while X is running.) I'd rather not lose the Assistant key in ChromeOS just to use it inside the chroot, though.

**Comment by rickybrent** [comment]
I gave up on finding a better way (not sure there is one) and just wrote a wrapper around evdevremapkeys; if anyone's interesting you can grab it [here](https://github.com/rickybrent/croutonremapkeys). :) All it does is swap remaps depending on if you're in Chrome OS or X11 but it does the trick for me.

**Comment by DennisLfromGA** [comment]
@rickybrent,

*Very nice, thanx!*

Perhaps a pull request is in order to either make this a standalone crouton target or incorporate it into the existing [`keyboard`](https://github.com/dnschneid/crouton/blob/master/targets/keyboard) target  if feasible.

-**DennisLfromGA**

**Comment by markstos** [comment]
Looks very helpful!  One suggestion for the docs. Where it says: *run it as
root before X11 grabs the keyboard*, it would be helpful if a specific
example or command was provided for this. Some interested users wouldn't be
sure at which point "X11 grabs the keyboard", or how to automate running
something before that.

**Comment by DennisLfromGA** [comment]
To add to @markstos's suggestion, you have to very careful when running things in your chroot as root since it can mess up permissions.

*Hope this helps,*
-**DennisLfromGA**

**Comment by rickybrent** [comment]
Welcome, and thanks too! I hadn't actually thought of making this into a proper pull request or target; it looks like Kali uses a bit of python, so it's not out of the question... hmm.

I added an installation script that sets up a virtual env and adds it to rc.local, keepign things automated. You definitely do have to be careful running things as root, but we need write access to /dev/uinput for this and changing the permissions or group there would effect Chrome OS and other chroots as well, so this might actually be the safer approach.

**Comment by rifaterdemsahin** [comment]
can this be implemented in pixel book 2?

**Comment by rifaterdemsahin** [comment]
Ahh I got pixel book
2 is not out yet.
https://www.techradar.com/uk/news/google-pixelbook-2

**Comment by StephanX** [comment]
@rickybrent Thanks a ton for your script, it works for me.

**Comment by gaustin** [comment]
This is generating a blank rc.local file for me. Any ideas what that means?

I did have to manually install wheel.

I would be fine having the assistant key remapped in both ChromeOS and Linux if that simplifies anything.

**Comment by gaustin** [comment]
Nevermind. I'm using crostini 🤦‍♂️

**Comment by spitfire55** [comment]
For those still waiting for this, the Chromium issue tracker has been updated from "Untriaged" to "Assigned".  See https://bugs.chromium.org/p/chromium/issues/detail?id=784857

**Comment by markstos** [comment]
The Chromium issue was assigned to someone who has logged into the bug tracker in the past 41 days. It also still lakes a priority or a target milestone, but yes-- it's good to see some movement on the issue besides just comments.

**Comment by markstos** [comment]
Hey, this feature has landed in Chrome OS now. Look for it start to make it's way into Canary -> Dev -> Beta -> Stable, arriving in Stable in Chrome OS 73 or 74.

https://bugs.chromium.org/p/chromium/issues/detail?id=784857#c41

**Comment by nickjmeyer** [comment]
Very exciting!

**Comment by markstos** [comment]
It looks like it will start out behind a flag for now, but that's easy enough to deal with.
