### ISSUE TITLE
awk: run time error: 'system' function not allowed in sandbox mode

### ISSUE THREAD

**Issue by CactusGhost** [dnschneid/crouton#3506]
I wiped my chroots all out earlier today and then powerwashed my chromebook. After that, I tried to create a more minimal chroot with just xiwi and xfce, but each time I try to create a new chroot, no matter whether it's in the default chroot location or on my SD Card, I'm getting the following strange errors at the end of the process:

```
Moving bootstrap files into the chroot...
Preparing chroot environment...
awk: run time error: 'system' function not allowed in sandbox mode
        FILENAME="/tmp/crouton.TLx/installer/prepare.sh" FNR=25 NR=25
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
awk: run time error: 'system' function not allowed in sandbox mode
        FILENAME="/tmp/crouton.TLx/chroot-bin/croutonpowerd" FNR=25 NR=25
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0
```

When I try to run edit-chroot or enter-chroot to see what happened, I find that the process never created these scripts within the bin directory (although the bin directory is present and empty, whether in the default spot or on my SD card). I'm thinking this must be a recent issue, because I successfully installed a number of chroots on this chromebook through crouton as recently as Monday night. 

For reference, I received this error with the following crouton inputs:
`sudo sh crouton -u -t xfce-desktop -r xenial -p /media/removable/SD\ Card `
`sudo sh crouton  -t xfce-desktop -r xenial -p /media/removable/SD\ Card`
`sudo sh crouton -t xiwi,xfce`

**Comment by drinkcat** [comment]
Seen on R64-10117.0.0 as well.

This is due to https://bugs.chromium.org/p/chromium/issues/detail?id=767182. We'll need to workaround that, too.

**Comment by hanguokai** [comment]
just upgrade my chromebook to version 64, it shows this error, but still work:
```bash
Entering /mnt/stateful_partition/crouton/chroots/xenial...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0
```

**Comment by DennisLfromGA** [comment]
@hanguokai,

That error's been fixed & merged, just update your chroot using:

- `sudo sh ~/Downloads/crouton -n xenial -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by hanguokai** [comment]
@DennisLfromGA It works! Thank you!

**Comment by gowen2** [comment]
Thank you @DennisLfromGA !

**Comment by plutoniclama** [comment]
@DennisLfromGA  the command you've suggested has not worked for me :(. I am still getting the same issue of running in sandbox.
sudo sh ~/Downloads/crouton -n xenial -u

**Comment by MilaThePurpleOne** [comment]
When I run
sudo sh ~/Downloads/crouton -n xenial -u
I just get the same error

**Comment by DennisLfromGA** [comment]
@plutoniclama & @MilaThePurpleOne,

Please follow the troubleshooting steps in the wiki: ['Common issues and reporting'](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisLfromGA**
