### ISSUE TITLE
crouton taking too long to retrieve and validate (problem was my internet), it'd be helpful if someone can explain why my internet was slow on downloading crouton

### ISSUE THREAD

**Issue by Importunity** [dnschneid/crouton#3508]
I'm unsure if you guys would be able to help me, but it's been 10+ hours and crouton is still taking forever to install. I've left it downloading through out the afternoon and night, but it still hasnt downloaded and It's been over 10 hours. It's skipped a few packages in which I am unsure if it will even install at this point. I'm unsure if it's my internets fault, but I doubt it, as my internet is average. I have installed crouton in the past, but some recent update to chromebook or something that made it so I was unable to sudo startxfce4, therefore I just decided to reinstall crouton. But right now it's taking way too long and I am unsure if it will still work, as it may not go back and retrieve the packages they have been skipped. The first time I installed crouton it only took 30 mins, but idk what's going on why is it taking so long to download. Ive even reset my Chromebook, but it's still taking a very long time to download. I just stopped and exited the Chrome OS developer shell, as I think it suddenly just stopped retrieving. I'm going to attempt to reinstall crouton again, but I doubt it'd be any faster than it was. If you guys can help me with this issue it'd be great thanks! 
I am using:
Acer cb3-131-c8gz

Here's the first few lines:
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...
failed: Connection timed out.
2017-11-12 09:22:23 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [70532] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 

Getting to this point took me 20 mins: It states that it should only take 15 mins, but it barely started downloading and it took me 20 mins to start retrieving
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...
failed: Connection timed out.
2017-11-12 09:29:02 URL:https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz [70532] -> "-" [1]
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://archive.ubuntu.com/ubuntu...
I: Retrieving adduser 3.113+nmu3ubuntu4

I'll attempt again when going to my local library to see if it works, as I have a feeling that it is my internet's fault, but am unsure if it is. My DL speed is 50-60mb(megabit) 

Okay I'm at the library and reinstall crouton, it turns out that it was my internet. I am still unsure why my internet was so slow at downloading it will be of great help if someone can help clarify it for me.

**Comment by iansltx** [comment]
Could be your ISP's IPv6 support. Depending, you can turn that off on your router and force apt-get to pull packages over v4. Had to do that for the initial install here (or switch to a v6 connection where Ubuntu's mirror was reachable), then configure apt afterward to only pull packages over v4. Which ISP are you on at home?

**Comment by lalaland1234** [comment]
I am on xfinity, I thought it was ipv6 too, but when I checked my chromebook using:  chrome://net-internals/#dns, and it said that ipv6 is false. That's why I was unsure. 

use_local_ipv6 | false

**Comment by DennisLfromGA** [comment]
Closing. Please update your chroot and try again, re-open if this issue is still a concern.

**Comment by Importunity** [comment]
Thank you, I didnt know how to close the thread it was due to ipv6
