### ISSUE TITLE
Can't upgrade SD based chroot with -p

### ISSUE THREAD

**Issue by econcrank** [dnschneid/crouton#3509]
```
chronos@localhost / $ sudo sh ~/Downloads/crouton -p /media/removable/USB\ Drive/chroots -u -n precise2
/media/removable/USB Drive/chroots/chroots not found.
/media/removable/USB Drive/chroots/chroots/precise2 does not exist; cannot update.
Valid chroots:
chronos@localhost / $ ls /media/removable/USB\ Drive/chroots/
precise  precise2  precise3  xenial
chronos@localhost / $ 
```

#### Please describe your issue:
chroots not found despite them being there

#### If known, describe the steps to reproduce the issue:

I'm upgrading precise2 after a chrome upgrade and the system can't find the chroots despite being directed there and the chroots being available as described by the ls command.

**Comment by DennisLfromGA** [comment]
@econcrank,

> sudo sh ~/Downloads/crouton -p /media/removable/USB\ Drive/chroots -u -n precise2

> /media/removable/USB Drive/**chroots/chroots**/precise2 does not exist; cannot update.

crouton's '-p' option is looking for the chroot's parent folder, unlike edit-chroot's '-c' option that is looking for the actual chroots folder.

So, using your example, I think the following should work:

- `sudo sh ~/Downloads/crouton -p /media/removable/USB\ Drive -u -n precise2`

*Hope this helps,*
-**DennisL**

**Comment by econcrank** [comment]
Thank you!
