### ISSUE TITLE
debian sid fails to start X after chrome update

### ISSUE THREAD

**Issue by githubgnulinux** [dnschneid/crouton#3510]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

Unable to submit using chromebook via anonymous exit relay. Copy typed manually

xservtransmkdir euid!=0 /tmp/.X11-unix will not be created

x.org x server 119

linux 31604amd64

error org.freedesktop,dbus.error.unknownmethod : method "releasedisplayownership" with signature on interface org.chromium.libcrosserverinterface doesn't exist

xf86enableioports failed to set iopl for i/o operation not permitted
/usr/bin/xinit unable connect to x server connection refused
...server error

#### Please describe your issue:

How to prevent chromebook software upgrade? Not wanted! debian sid xfce working before chromium upgrade

**Comment by nemo-nullius** [comment]
I also came up with this problem today after my chrome os updated automatically this morning, and the script from @farmerbb in https://github.com/dnschneid/crouton/issues/3375 helps solve the problem.

Maybe you could also try the latest crouton.

**Comment by DennisLfromGA** [comment]
@githubgnulinux & @nemo-nullius,

It's usually a good idea to update your crouton chroots after a CrOS update, especially if you encounter problems.

*Hope this helps,*
-**DennisL**

**Comment by nemo-nullius** [comment]
@DennisLfromGA I then update my crouton to the latest version by downloading it directly from github, run `sudo sh ~/Downloads/crouton -u`, and the problem is gone.  Thank you so much for your advice!

**Comment by DennisLfromGA** [comment]
@nemo-nullius,

No problem.

A CrOS update can cause your chroot(s) to get out of sync so I update mine when needed or when crouton itself has been updated.

*Hope this helps,*
-**DennisL**
