### ISSUE TITLE
Can't update chroot as per #3375 due to script termination?

### ISSUE THREAD

**Issue by duranzaf** [dnschneid/crouton#3511]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170831074915~master:d11442d5
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,keyboard
host: version 9901.66.0 (Official Build) stable-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 31 22:04:48 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: trusty1
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty1...
crouton: version 1-20171109145451~master:35a16889
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9901.66.0 (Official Build) stable-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 31 22:04:48 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty1...```

#### Please describe your issue:
I am unable to update my chroot using the latest version of crouton.
The update is interrupted with an error due to skypeforlinux (which had stopped working with a Microsoft message that it is no longer supported) but I never removed the package.

Had been using trusty OK but now I am unable to initialize ubuntu as described in #3375. It would appear to me that my chroot is not properly fixed due to the skypeforlinux error?

This is causing the script to terminate and I assume the desired updates were not applied?
I did try to resume the script but am still unable to start ubuntu.

Maybe deleting that skype package prior to the crouton update would help, but I don't know how.
Any help is greatly appreciated by this rookie.

thanks,
Frank

crosh> shell
chronos@localhost / $ ls /usr/local/chroots
trusty
chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n trusty
/usr/local/chroots/trusty already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into

.....

libxslt1.1:i386 linux-libc-dev login logrotate multiarch-support
mysql-common ntpdate openssl passwd poppler-utils python-libxml2
python-samba python3-apport python3-problem-report
python3-software-properties python3-update-manager remmina remmina-common
remmina-plugin-rdp remmina-plugin-vnc rsyslog samba-common samba-common-bin
samba-libs skypeforlinux smbclient software-properties-common
software-properties-gtk sudo systemd-services tzdata udev
unattended-upgrades update-manager update-manager-core update-notifier
update-notifier-common vlc vlc-data vlc-nox vlc-plugin-notify
vlc-plugin-pulse wget xserver-common xserver-xorg-core xul-ext-ubufox
176 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 253 MB of archives.
After this operation, 124 MB of additional disk space will be used.
**WARNING: The following packages cannot be authenticated!
skypeforlinux**
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
Installing target core...
Preparing environment...
Preparing software sources...

.....

Ign http://ppa.launchpad.net trusty/main i386 Packages/DiffIndex
Ign http://ppa.launchpad.net trusty/main Translation-en
Ign http://ppa.launchpad.net trusty/main Translation-en
Err http://ppa.launchpad.net trusty/main amd64 Packages
403 Forbidden
Err http://ppa.launchpad.net trusty/main i386 Packages
403 Forbidden
Fetched 4486 B in 10s (416 B/s)
W: GPG error: https://repo.skype.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1F3045A5DF7587C3
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-amd64/Packages 403 Forbidden

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-i386/Packages 403 Forbidden

......

Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Unable to set master
(EE)
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE)
(EE)

note: After the update failure, I installed a new chroot named trusty1. But I haven't figured out yet what option would allow me to startxfce4 in that chroot. I was trying to verify that the new crouton download worked correctly. My goal is to fix the original trusty since it has many packages and shortcuts installed.

#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
@duranzaf,

> Maybe deleting that skype package prior to the crouton update would help, but I don't know how.

I think that might be your best way forward. I'm not that well versed with Linux package installation & removal but I'll try to help, try the following -

- `enter-chroot -n trusty`
If prompted to finish the setup enter `n`

- `sudo apt remove skypeforlinux`

If that doesn't work try -

- `sudo apt remove skype*`

You may also have to manually remove the skype sources file in `/etc/apt/sources.list.d`
- `cd /etc/apt/sources.list.d`
Then look for and remove any file name containing the word 'skype'

Once that's done you may be able to re-run the `prepare.sh` script -
- `sudo /prepare.sh`

Hopefully, it will finish the setup without error and you can then exit the chroot and do a crouton update.

*Hope this helps,*
-**DennisL**

**Comment by duranzaf** [comment]
Thank you DennisL for your time and effort.
It is very much appreciated.

I was able to make progress after following your suggestions.
The remove skypeforlinux worked, but I also had to remove skype*

I then also removed two files with skype from sources.list.d

I was not able to find a 'prepare.sh'.

So I exited and closed the terminal.
Then went back into the shell and tried the crouton -u update.

But still encountering errors, first with references to 

------------------------------------------------------------------
Preparing software sources...
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-amd64/Packages  403  Forbidden

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-i386/Packages  403  Forbidden

E: Some index files failed to download. They have been ignored, or old ones used instead.

----------------------------------------------------------------------------------------------------------------

I tried to capture all the screen output - but it doesn't all end up in the file.

I used this command
crosh> shell
chronos@localhost / $ sudo sh ~/Downloads/crouton -u -n trusty > ~/crouton-u.txt

This is the output on the terminal window...
/usr/local/chroots/trusty already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...

Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Installing target core...
Preparing environment...
Preparing software sources...
W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-amd64/Packages  403  Forbidden

W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-i386/Packages  403  Forbidden

E: Some index files failed to download. They have been ignored, or old ones used instead.
Ensuring system is up-to-date...
Syncing timezone...
Installing target audio...
Fetching CRAS (branch 8979ddbd6756877f7963479293addfe24d74a683)...
Compiling CRAS (i386)...
Installing CRAS...
Compiling CRAS (native)...
Installing CRAS...
Installing target xorg...
Installing dependencies for /usr/local/lib/croutonfreon.so...
Compiling /usr/local/lib/croutonfreon.so...
ar: creating /tmp/crouton.oYm40M/crouton-xserver-xorg-legacy.deb
Installing dependencies for /usr/local/bin/croutonxi2event...
Compiling /usr/local/bin/croutonxi2event...
Installing target x11...
Installing target gtk-extra...
ar: creating /tmp/crouton.1r3r59/crouton-network-manager.deb
Installing target xfce...
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

the attached file has the redirected output.
[crouton-u.txt](https://github.com/dnschneid/crouton/files/1467917/crouton-u.txt)

At the end of the file is this:
....
0 upgraded, 36 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.4 MB/13.4 MB of archives.
After this operation, 37.2 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libxfcegui4-4 mousepad xfburn xfce4-clipman xfce4-clipman-plugin
  xfce4-cpugraph-plugin xfce4-dict xfce4-mailwatch-plugin xfce4-mount-plugin
  xfce4-netload-plugin xfce4-notes xfce4-notes-plugin xfce4-places-plugin
  xfce4-quicklauncher-plugin xfce4-smartbookmark-plugin xfce4-timer-plugin
  xfce4-verve-plugin xfce4-xkb-plugin xfce4-screenshooter xfce4-taskmanager

Would you or someone know if all these packages (mostly web browser plug-ins) would have to be removed as well as with the skype package? hopefully not..

thanks much,
Frank

**Comment by DennisLfromGA** [comment]
@duranzaf,

> W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-amd64/Packages 403 Forbidden

> W: Failed to fetch http://ppa.launchpad.net/xubuntu-dev/xfce-4.12/ubuntu/dists/trusty/main/binary-i386/Packages 403 Forbidden

The two errors above look to be repositories offline for some reason, you may want to remove those ppa's and review others you've installed. Take a look at [this help article](https://askubuntu.com/a/310) for more on that: [How can PPAs be removed?](https://askubuntu.com/a/310)

*Hope this helps,*
-**DennisL**

**Comment by duranzaf** [comment]
great news for me! so i commented out the entries in the parent xubuntu.. PPA list file and I was able to update the chroot and initialize ubuntu.

When I first encountered the problem (underlying display server problems due to Chrome OS revisions, more or less?) not knowing what it was I reverted to a three month backup which contained 90% of what I now see.

I do notice some gadgets missing and when I switch back to chrome - I see a number of errors that seem to be display-related as in 
........................................................
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLXrror org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20171109145451~master:35a16889
release: trusty
......

DennisL so bailed me out.. I had forgotten how this is all on a non-supported product and am so grateful that dnschneid and Dennis are kind with their time.

I will try to research the errors  a bit more (and I did figure out  startxfce4 -n Trusty1 option) but am attaching file with all the terminal output just for reference.

Is there some other update I should be doing due to the chrome os revision?

thank you so much.
Frank

[startxfce4 errors.txt](https://github.com/dnschneid/crouton/files/1469189/startxfce4.errors.txt)

I do not understand the open and close protocol, so please excuse if I should not have re-opened.

**Comment by DennisLfromGA** [comment]
@duranzaf,

If this issue is resolved to your satisfaction then you can close it or let me know and I'll close it.
If you still have questions or concerns then give us more detail and we'll go from there.

*Hope this helps,*
-**DennisL**

**Comment by duranzaf** [comment]
That's what I thought,  but somehow this issue was closed and I had not consciously done it.

So I believe there is still an issue related to other components still calling the old dbus method calls.  I see some similar reports in #3442 

Can someone offer a suggestion on how to address these errors showing up when I switch back to the chrome bash.. to determine what is using glx or the mentioned interface.

(A similar entire capture is attached to the posting 'great news' above.)

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Oct 31 22:04:48 PDT 2017 x86_64

.....

Initializing built-in extension DRI2
Loading extension GLX
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20171109145451~master:35a16889


I will try updating any packages from Synaptic that may be showing updates available.
thank you.
Frank
