### ISSUE TITLE
Backup generates .part files?

### ISSUE THREAD

**Issue by ezuk** [dnschneid/crouton#3513]
```
sudo edit-chroot -f /media/removable/UNTITLED -b xenial

Generated files:

-rwxr-xr-x. 1 chronos chronos 4.0G Nov 13 22:58 xenial-20171113-2245.tar
-rwxr-xr-x. 1 chronos chronos 1.5G Nov 13 23:02 xenial-20171113-2245.tar.part-aaab

```

Wondering if the `.part` file is by design. If so, how would I restore this tar? And is there a way to configure the backup so it generates just a single file?

I will open a PR for the backup docs with the reply to this issue. Thank you!

**Comment by icecream95** [comment]
edit-chroot:

    -s SPLIT    Force a backup archive to be split into SPLIT-sized chunks.
                SPLIT is specified in megabytes (1048576 bytes), and cannot be
                smaller than 10.
                FAT32 filesystems are split by default to fit within 4GB.

The only way to make it generate a single file is to format it with another filesystem such as ext4, but then you'd lose existing data and you'll only be able to read it on Linux.

To restore just use edit-chroot or the crouton script with the file that doesn't have the .part bit.

I agree that there probably does need to be some better documentation around this. You might want to edit the wiki page at https://github.com/dnschneid/crouton/wiki/Backups.

**Comment by ezuk** [comment]
Thanks so much! Added here: https://github.com/dnschneid/crouton/wiki/Backups#large-backups-are-split

**Comment by forresthopkinsa** [comment]
Since GNU Tar doesn't support extraction of multi-volume compressed archives, I have to ask -- how can this be manually extracted? Without extracting it into a chroot?

**Comment by icecream95** [comment]
The restore script at [edit-chroot](https://github.com/dnschneid/crouton/blob/master/host-bin/edit-chroot#L471-L492) just `cat`s all the `.part` files on to the first file, then extracts that with `tar`.

Note that [edit-chroot](https://github.com/dnschneid/crouton/blob/master/host-bin/edit-chroot) `cat`s that backup files into a FIFO (made with `mkfifo`) so the resulting file doesn't need to be stored.

**Comment by forresthopkinsa** [comment]
Perfect, thanks for looking into the code for me! Super helpful 👍
