### ISSUE TITLE
Failed to download debootstrap.

### ISSUE THREAD

**Issue by Aukerer** [dnschneid/crouton#3515]
```
No chroots found in /mnt/stateful_partition/crouton/chroots
```

chronos@localhost / $ sudo sh ~/Downloads/crouton -t unity -r xenial

Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...
/tmp/crouton-installer-cache/crouton: 14: /tmp/crouton.eYG/installer/ubuntu/bootstrap: wget: not found
Download from Debian gitweb failed. Trying latest release...
/tmp/crouton-installer-cache/crouton: 19: /tmp/crouton.eYG/installer/ubuntu/bootstrap: wget: not found
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.

I tried to install ubuntu, but it didn't work.
I don't have any proxy running, and on other WiFi networks this happens too. I also tried waiting for a day to try it again, it still didn't work.

Does anyone know how to fix this issue?
Thanks.

**Comment by dnschneid** [comment]
You're seeing #3501.  Fix is in progress.

**Comment by yoyomon99** [comment]
any news on when it will be back up?

**Comment by Aukerer** [comment]
thank you

**Comment by dnschneid** [comment]
You'll want to monitor the progress of #3514

**Comment by Aukerer** [comment]
Does this mean that it will be fixed soon?

**Comment by SimpleWolf** [comment]
Do you know if it will be fixed today? Been trying to reinstall everything because Chromebook has been a bit silly lately.

**Comment by yoyomon99** [comment]
not working yet, wget still is not recognized

**Comment by DennisLfromGA** [comment]
@yoyomon99,

Per above:
- You're seeing #3501. Fix is in progress.
- You'll want to monitor the progress of #3514

So until that PR is reviewed, approved & merged it will not work.

-**DennisL**

**Comment by yoyomon99** [comment]
Ayyyy we're back up, thanks so much guys
