### ISSUE TITLE
Downloads Acess Unavailable

### ISSUE THREAD

**Issue by RyanGamingXbox** [dnschneid/crouton#3517]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
I was trying to send a file from Ubuntu to ChromeOS
The Downloads folder was unable to open and had one lock icon.

#### If known, describe the steps to reproduce the issue:
Unknown

**Comment by DennisLfromGA** [comment]
Please paste the output of the following command below: `sudo edit-chroot -all`

**Comment by RyanGamingXbox** [comment]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171109145451~master:35a16889
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10134.0.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Nov 16 03:16:49 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@RyanGamingXbox,

- Are you logged into your Chromebook and is Downloads available on the CrOS side?
- Are you launching Unity while logged in or are you starting it on VT2 without logging in?
- Did you launch something in your chroot as root and possibly mess up permissions?
- When did this start happening, after a CrOS or crouton update?

-**DennisL**

**Comment by tkamat** [comment]
I am having the same problem, I had changed some permissions around when installing something, and I think that could be the culprit. Is there any way to fix it?

**Comment by dnschneid** [comment]
Are you logging into multiple ChromeOS accounts simultaneously?

**Comment by DennisLfromGA** [comment]
@tkamat,

When that happens you can usually recover by doing the following:

```
sudo enter-chroot
sudo chown -R 1000:1000 "$HOME"
exit
```

*Hope this helps,*
-**DennisL**

**Comment by tkamat** [comment]
Just tried that, the Downloads folder is still showing up as empty. I also checked the /etc/crouton/shares file, and it seems to be okay, the only entry is "downloads ~/Downloads" In desperation, I attempted deleting the Download folder completely in the chroot, but after logging back in it just created a new, empty download folder. The downloads on the chromeos side are still intact.

**Comment by dan-s-schultz** [comment]
Same issue, output from `sudo edit-chroot -all`

```
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 10134.0.0 (Official Build) dev-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Nov 16 03:17:04 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

**Comment by dan-s-schultz** [comment]
in ChromeOS, in chroot, I can access the Downloads folder with the following path:

`/home/user/47e7c03d59b1c3bda9b663f66eb08c80c19d8969/Downloads`

In xfce4, the only thing in home is `/chronos/`  Inside that I have an empty Downloads folder

**Comment by RyanGamingXbox** [comment]
@DennisLfromGA Yes, Yes, No, I do not update crouton, It is probably from a ChromeOS update!

**Comment by DennisLfromGA** [comment]
@dnschneid asked an important question earlier which has not yet been answered:
- Are you logging into multiple ChromeOS accounts simultaneously?

-**DennisL**

**Comment by tkamat** [comment]
@DennisLfromGA I am still having this same problem after trying the solution you posted, again I am not using multiple accounts.

**Comment by DennisLfromGA** [comment]
All,

A lot of important crouton fixes & changes have been merged recently and Chrome OS updates can affect your chroot(s) too a lot of times so I would suggest updating your chroot(s) before doing any more troubleshooting. At least that way you'll all be on the same page and we can go from there.

The following wiki has some very good troubleshooting suggestions: 
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**

**Comment by tkamat** [comment]
Thanks so much, updating my chroot fixed the problem, I can now see all of my Downloads from chromeos in my chroot.

**Comment by dan-s-schultz** [comment]
The update worked for me as well! Thanks a bunch!

**Comment by DennisLfromGA** [comment]
Cool. 👍 

Since the OP has left the building but others with this identical issue have had it resolved I'm gonna close it for now. The OP can re-open it if an update doesn't help.

-**DennisL**
