### ISSUE TITLE
startxfce4 error after most recent chromeos update

### ISSUE THREAD

**Issue by mkitzan** [dnschneid/crouton#3518]
```
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: The pid file "/usr/local/var/run/dbus/pid" exists, if the message bus is not running, remove this file
WARNING: starting chroot system dbus daemon failed with code 1
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.79-11650-ge987f76b729a #1 SMP PREEMPT Tue Oct 31 22:03:34 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=52f1d823-079f-7844-968b-472159949fd1/PARTNROFF=1 hashtree=PARTUUID=52f1d823-079f-7844-968b-472159949fd1/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=bf6f304880eed822e0670e3d5141e07f38b89161 salt=24b8ba5a5d43a8b1d5c83360437f79c9d921b727e2f471c8d857346636f17f37" noinitrd vt.global_cursor_default=0 kern_guid=52f1d823-079f-7844-968b-472159949fd1 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 13 October 2017  01:59:06PM
xorg-server 2:1.15.1-0ubuntu2.11 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Nov 17 15:52:41 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Unable to set master
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```

#### Please describe your issue:
After updating my chromebook yesterday when I run "sudo startxfce4" I get that output.
I have since tried many of the fixes recommended in this forum, but they didn't help.

My suspicion about the issue is that startxfce4 is trying to open the "precise" chroot, and not my recently installed "xenial" chroot (one of the fixes I tried). There's probably something more to it than just that, but I guess it's a start. If I were to delete my "precise" chroot, would startxfce4 automatically choose the "xenial" version? 
Any help would be appreciated. Thanks. 
#### If known, describe the steps to reproduce the issue:
sudo startxfce4

**Comment by ShrekMate** [comment]
I am having the exact same problem. When a fix is found, could whoever figures it out respond with a clear, explaining-something-to-someone-who-doesnt-know-anything-about-coding-so-hold-my-hand kind of way? thanks!

**Comment by bormara** [comment]
I was able to circumvent this issue by just updating crouton too.

**Comment by DennisLfromGA** [comment]
@mkitzan & @ShrekMate,

Please follow the guide: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

Then let us know if you're still having this same issue.

*Hope this helps,*
-**DennisL**

**Comment by SimpleWolf** [comment]
I can't even install it in the first place :L

**Comment by lightjl** [comment]
I ran `sudo sh ~/Downloads/crouton -n xenial -u` and then 
I run `sudo startxfce4`
It still show the errors:
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Oct 31 21:58:25 PDT 2017 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=2c2f0208-9165-4e47-a4ee-51a7850fa63a/PARTNROFF=1 hashtree=PARTUUID=2c2f0208-9165-4e47-a4ee-51a7850fa63a/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=2bc7d22e11fef5ce97e7bd60cd3e99a77be257ef salt=a44aaa5f07b4a4e78b60402bec0a16d25c907a375fba4f8177e697c2d45990ee" noinitrd vt.global_cursor_default=0 kern_guid=2c2f0208-9165-4e47-a4ee-51a7850fa63a  
Build Date: 13 October 2017  02:13:29PM
xorg-server 2:1.19.3-1ubuntu1~16.04.4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Nov 19 11:42:39 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1511062960.366173 sender=:1.11 -> destination=:1.52 serial=514 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1511062961.197092 sender=:1.11 -> destination=:1.54 serial=516 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by mkitzan** [comment]
Got it! @ShrekMate, @lightjl, the key for me was installing a "xenial" chroot and deleting my old "precise" chroot. Copy your files to another machine (enter the chroot with the command line and  scp your files to some other machine). Then delete your problem chroot (look at the first line of output from sudo startxfce4 and it will state which chroot it's trying to enter). Afterwards reinstall a xenial chroot, and you _should_ be good... _**should**_
Hope it helps

**Comment by gabe-connolly** [comment]
I am having the same issue described above.  

Output of `sudo enter-chroot -n xenial croutonversion`:
````
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:28:54 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
````

Output of `sudo startxfce4`:
````
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:28:54 PST 2017 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=ea6b08c8-c6d1-c845-97e2-af13b302ab79/PARTNROFF=1 hashtree=PARTUUID=ea6b08c8-c6d1-c845-97e2-af13b302ab79/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=cb0652fe268f3ed387337531c4521f5b4e413293 salt=e317721aeae38191facdc54f87c50a4c2d181fd3041e9a365b7deedab02607bf" noinitrd vt.global_cursor_default=0 kern_guid=ea6b08c8-c6d1-c845-97e2-af13b302ab79  
Build Date: 13 October 2017  02:13:29PM
xorg-server 2:1.19.3-1ubuntu1~16.04.4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Dec 13 13:04:06 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1513188246.985491 sender=:1.11 -> destination=:1.64 serial=811 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1513188247.282005 sender=:1.11 -> destination=:1.66 serial=813 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
````

Result of `sudo ls /usr/local/chroots`: `xenial`

I have tried:
* deleting and re-downloading the latest version of crouton
* deleting /usr/local/chroots/xenial
* re-running `sudo sh ~/Downloads/crouton -t xfce`

I am still unable to get a running Ubuntu desktop because of this error.  Any suggestions on how to resolve this would be much appreciated!

**Comment by laitilari** [comment]
> I am having the same issue described above.
> 
> Output of `sudo enter-chroot -n xenial croutonversion`:
> 
> ```
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
> crouton: version 1-20171122220410~master:99877eaf
> release: xenial
> architecture: armhf
> xmethod: xorg
> targets: xfce
> host: version 9901.77.0 (Official Build) stable-channel daisy 
> kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:28:54 PST 2017 armv7l armv7l armv7l GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
> ```
> Output of `sudo startxfce4`:
> 
> ```
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
> /usr/bin/startxfce4: Starting X server
> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
> 
> X.Org X Server 1.19.3
> Release Date: 2017-03-15
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 4.4.0-97-generic armv7l Ubuntu
> Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:28:54 PST 2017 armv7l
> Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=ea6b08c8-c6d1-c845-97e2-af13b302ab79/PARTNROFF=1 hashtree=PARTUUID=ea6b08c8-c6d1-c845-97e2-af13b302ab79/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=cb0652fe268f3ed387337531c4521f5b4e413293 salt=e317721aeae38191facdc54f87c50a4c2d181fd3041e9a365b7deedab02607bf" noinitrd vt.global_cursor_default=0 kern_guid=ea6b08c8-c6d1-c845-97e2-af13b302ab79  
> Build Date: 13 October 2017  02:13:29PM
> xorg-server 2:1.19.3-1ubuntu1~16.04.4 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.33.6
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Dec 13 13:04:06 2017
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> method return time=1513188246.985491 sender=:1.11 -> destination=:1.64 serial=811 reply_serial=2
>    boolean true
> MESA-LOADER: failed to retrieve device information
> gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
> failed to load driver: exynos
> EGL_MESA_drm_image required.
> (EE) 
> Fatal server error:
> (EE) AddScreen/ScreenInit failed for driver 1
> (EE) 
> (EE) 
> Please consult the The X.Org Foundation support 
>          at http://wiki.x.org
>  for help. 
> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
> (EE) 
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> method return time=1513188247.282005 sender=:1.11 -> destination=:1.66 serial=813 reply_serial=2
>    boolean true
> (EE) Server terminated with error (1). Closing log file.
> /usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> /usr/bin/xinit: server error
> Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
> ```
> Result of `sudo ls /usr/local/chroots`: `xenial`
> 
> I have tried:
> 
> * deleting and re-downloading the latest version of crouton
> * deleting /usr/local/chroots/xenial
> * re-running `sudo sh ~/Downloads/crouton -t xfce`
> 
> I am still unable to get a running Ubuntu desktop because of this error. Any suggestions on how to resolve this would be much appreciated!

I am having the same error as this one, still, over year later
