### ISSUE TITLE
Horizontal scrolling is not "Austrailian"

### ISSUE THREAD

**Issue by DavidFrahm** [dnschneid/crouton#3519]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171109145451~master:35a16889
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,touch
host: version 9901.66.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.79-11650-ge987f76b729a #1 SMP PREEMPT Tue Oct 31 22:05:39 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

In Chrome OS settings I have set the touchpad to the "Austrailian" (aka "natural") setting.

After installing crouton, the crouton/xiwi windowed apps I run do not scroll horizontally the same way Chrome OS does.

Crouton/xiwi apps do obey that setting for vertical scrolling.

Please advise if there is a crouton config or anything I could try to get natural scrolling horizontally. Alternatively, if there's a different crouton install, target, etc. that should yield better results that would be helpful as well.

#### If known, describe the steps to reproduce the issue:

Chromebook model: Google Pixelbook
Crouton install: `$ sudo sh ~/Downloads/crouton -t xiwi,touch`

**Comment by dnschneid** [comment]
We only process the wheel messages we receive; see https://github.com/dnschneid/crouton/blob/master/host-ext/nacl_src/kiwi.cc#L610

I dunno if we have access to the australian scrolling setting to do anything smarter.  @drinkcat?

**Comment by ibrado** [comment]
I inserted the following as line 125 (right after the `if` of `# Crouton-in-a-tab: Start fbserver and launch display`) in `/usr/local/bin/croutonxinitrc-wrapper`:
```
xmodmap -e "pointer = 1 2 3 4 5 7 6"
```
This works for me for both windowed and full-desktop (KDE) apps. Scroll drection remained consistent between ChromeOS and the xiwi apps even as I toggled between traditional/Australian scrolling.

**Comment by DavidFrahm** [comment]
The solution from @ibrado worked perfectly for me.

Is there something we can do to detect Austrailian and apply this automatically for people?

**Comment by DavidFrahm** [comment]
I'm just using plain xiwi with the extension to run one app (WebStorm IDE) in a window.

My crouton install:

```
$ sudo sh ~/Downloads/crouton -t xiwi,touch
```

My app launch:

```
$ sudo enter-chroot xiwi webstorm
```
