### ISSUE TITLE
Can't install any chroot within the new ChromeOs update.

### ISSUE THREAD

**Issue by New2GitHub1** [dnschneid/crouton#3523]
I can't install any chroot and i get this

**chronos@localhost / $ sudo sh ~/Downloads/crouton -t xfce
Downloading latest crouton installer...
######################################################################## 100.0%
WARNING: USB booting is enabled; consider disabling it.
WARNING: Legacy booting is enabled; consider disabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_legacy=0
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...
/tmp/crouton-installer-cache/crouton: 14: /tmp/crouton.5zp/installer/ubuntu/bootstrap: wget: not found
Download from Debian gitweb failed. Trying latest release...
/tmp/crouton-installer-cache/crouton: 19: /tmp/crouton.5zp/installer/ubuntu/bootstrap: wget: not found
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.**

I even tried unity and unity-desktop and get the same thing. I really don't wanna format my chromebook or start continuously reverting to a previous version (because ChromeOs keeps auto updating) so if someone has a fix it's gladly needed.

**Comment by dnschneid** [comment]
Should be fixed in the latest crouton.

**Comment by pogo555** [comment]
I have this problem. I have downloaded the latest crouton (as far as I can tell) and I get very similar output to @New2GitHub1 when trying to install xenial (or trusty). Any hints?
