### ISSUE TITLE
Open GL Broken

### ISSUE THREAD

**Issue by AmintaDefender** [dnschneid/crouton#3527]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171119224248~master:c73e7a80
release: xenial
architecture: amd64
xmethod: xorg
targets: touch,xfce
host: version 10134.0.0 (Official Build) dev-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Nov 16 03:28:42 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

(Note: I'm a noob at linux.) I have been running XFCE4 on my chromebook pixel for a couple months with no issue. A couple days ago I tried to use Blender and noticed that the UI wouldn't load. Since then I've factory reset and reinstalled xfce4. Unfortunately the issue still persists.

A little bit of trouble shooting: I used the website ScultpGL (https://stephaneginier.com/sculptgl/) on Chrome OS with no problem. The same website refused to load properly on firefox in XFCE4. I've also booted off a usb stick for ubuntu and was able to run everything. I can only conclude that crouton has an issue with the graphics acceleration or something.

Also an error message that I started receiving: Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

**Comment by abc123me** [comment]
Same here, every game I run fails some won't start while some run fine then crash, it seems that the audio always dies or goes on a loop whenever it is about to crash
