### ISSUE TITLE
Change-kernel-flags trashes ChromeOS, resulting in a boot loop

### ISSUE THREAD

**Issue by libjared** [dnschneid/crouton#3529]
**Note:** My Chromebook ID is CAVE.

I use VirtualBox and CIFS modules, so I disable module locking using change-kernel-flags. Up until now, that script was working fine, and every time my device got an update on beta channel, I needed to re-run it. But a recent update caused the script to instead **cripple** the Chromebook. Even without any crouton environment installed, and from a fresh install of ChromeOS, the following steps is enough to cause a boot loop. From there, you must use the Chromebook Recovery Utility, which wipes the device.

1. Get sudo working
1. Download and run `sudo sh ./change-kernel-flags`
1. Reboot normally
1. Get `OS verification is OFF, press space to reenable.` warning screen
1. Either CTRL+D, or wait 30s
1. Return to step 4!

Any suggestions?

**Comment by libjared** [comment]
Being on beta (or dev) channel is a requirement for reproduce, it turns out. Stable is fine. But since beta eventually becomes stable, I think a diagnosis is a good idea.

**Comment by divx118** [comment]
@libjared Can you please open a ticket on https://github.com/divx118/crouton-packages/issues , so we can discuss it there since it has nothing to do with the crouton scripts.

Thanks.

**Comment by libjared** [comment]
Here you go: divx118/crouton-packages#69
