### ISSUE TITLE
Firefox for armv7 chromebook wont work anymore

### ISSUE THREAD

**Issue by mickbeck** [dnschneid/crouton#3530]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by DennisLfromGA** [comment]
Is this a crouton issue or a Firefox issue?

**Comment by mickbeck** [comment]
Firefox worked in crouton before, but that was around last January. I remember it specifically had stopped working after an update and I haven't been able to get it working since

**Comment by DennisLfromGA** [comment]
@mickbeck,

I may be wrong but according to [this page](https://developer.mozilla.org/en-US/docs/Supported_build_configurations), Firefox on a Linux armv7 platform falls into the Tier-3 catagory:

> Tier-3 platforms have a maintainer or community which attempt to keep the platform working. These platforms may or may not work at any time, and often have little test coverage:  
>> Linux on various CPU architectures including ARM,  PPC, 68k and x86 CPUs without SSE2 support — maintained by various Linux distributions

*Hope this helps,*
-**DennisL**

**Comment by mickbeck** [comment]
Do you know where I could get access to the Tier-3 community version?

**Comment by DennisLfromGA** [comment]
@mickbeck,

No, sorry. 
I don't know what release you're using, you didn't show us the output of: `sudo edit-chroot -all`
I found some info. '[here](https://raspberrypi.stackexchange.com/questions/43577/how-to-download-iceweasel/68606#68606)' for the `trusty` release, maybe it'll help.

-**DennisL**

**Comment by rprr** [comment]
Happens for me as well. On an ASUS Chromebook ARM C100 Flip :(

$ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi
host: version 9901.77.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:31:23 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by mickbeck** [comment]
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171119224248~master:c73e7a80
release: trusty
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel peach_pi 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:24:13 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by yeswap** [comment]
Firefox crashing on Ubuntu ARM has been confirmed on Ubuntu Launchpad.[](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1711337)

**Comment by mickbeck** [comment]
I saw that but I still haven't seen a solution

**Comment by DennisLfromGA** [comment]
Closing. This appears to be a Firefox issue only.

**Comment by mickbeck** [comment]
Gg

**Comment by mickbeck** [comment]
If this was a Firefox only issue, then why did it work on crouton before but not now? What changed? Was it Firefox or crouton?

**Comment by Invisiblehacker** [comment]
niether does thunderbord
