### ISSUE TITLE
Chrome stable target script stops due incorrect url

### ISSUE THREAD

**Issue by onneau** [dnschneid/crouton#3532]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: browser
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/browser...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: i386
xmethod: xorg
targets: chrome
host: version 9592.88.2017_08_28_1442 (Developer Build - tonyd) developer-build x86-atb
kernel: Linux localhost 4.4.64 #6 SMP PREEMPT Mon Aug 28 12:35:38 BST 2017 i686 i686 i686 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/browser...

#### Please describe your issue:
--2017-11-24 23:57:52--  https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb
Resolving dl.google.com (dl.google.com)... 172.217.20.78, 2a00:1450:400e:80a::200e
Connecting to dl.google.com (dl.google.com)|172.217.20.78|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-24 23:57:52 ERROR 404: Not Found.

Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/browser...

#### If known, describe the steps to reproduce the issue:

sudo sh ~/Downloads/crouton -t chrome -n browser

**Comment by DennisLfromGA** [comment]
@onneau,

32-bit Chrome may no longer be available for your Developer build.

-**DennisL**

**Comment by Tokyodays** [comment]
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20180329190032~master:d287904a
release: trusty
architecture: i386
xmethod: xorg
targets: xfce-desktop,keyboard,audio,extension,touch,chrome
host: version 64.4.34 (Developer Build - neverware) developer-build chromeover32
kernel: Linux localhost 4.14.31+ #1 SMP Fri Apr 27 02:22:37 UTC 2018 i686 i686 i686 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...


@DennisLfromGA 
i have a same probrem.

```
--2018-06-11 22:57:56--  https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb
Resolving dl.google.com (dl.google.com)... 2404:6800:4004:816::200e, 172.217.25.110
Connecting to dl.google.com (dl.google.com)|2404:6800:4004:816::200e|:443... failed: Connection refused.
Connecting to dl.google.com (dl.google.com)|172.217.25.110|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-06-11 22:57:56 ERROR 404: Not Found.

Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by Tokyodays** [comment]
command is this
`
sudo sh ~/Downloads/crouton -r trusty -t xfce-desktop,keyboard,audio,extension,touch`
