### ISSUE TITLE
Opening single app fails for sublime, works pretty well for others (Sudo startxiwi)

### ISSUE THREAD

**Issue by chadali** [dnschneid/crouton#3533]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171122220410~master:99877eaf
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce,touch
host: version 9901.77.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:37:19 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue:
sudo startxfce4 - works everytime
sudo startxiwi xterm/vim/any other small app - works pretty consistently 
sudo startxiwi subl - miracle if it opens. I usually get a "connection failed" screen with this in the logs (below). Other times all of ChromeOS just crashes, goes to a black screen for a second or two, and then returns with all previously opened tabs gone ( this happens when memory runs out? )

Edit: Works on fresh reboot, but once I put the laptop to sleep or other stuff happens it starts to fail again.

I'm using a PixelBook, so hopefully RAM isn't the issue. I would love to be able to open sublime in a tab or window of it's own, but for the time being I'll just continue to use the full desktop environment which runs very well.

Thank You

![connectionfailed1](https://user-images.githubusercontent.com/15786391/33246025-e41d6f0e-d2dd-11e7-8cec-97ca7f855fbf.png)
![connectionfailed2](https://user-images.githubusercontent.com/15786391/33246026-e42baa4c-d2dd-11e7-91f2-28bb15945584.png)

Sometimes, as I keep spamming stuff to I get this error. To solve I run `sudo unmount-chroot -afy`. I don't know if it's relevant, but I thought I'd just include it to be safe 

![error-unmount](https://user-images.githubusercontent.com/15786391/33246040-09439dee-d2de-11e7-8173-5ce1ded102ca.png)

**Comment by alex3d** [comment]
`startxiwi subl -w` works for me (`-w or --wait:        Wait for the files to be closed before returning`)
