### ISSUE TITLE
Trackpad disabled in ChromeOS when I virtualize into crouton

### ISSUE THREAD

**Issue by pairwiseseq** [dnschneid/crouton#3535]
I am not 100%, but this issue seemed to arise after I connected Logitech MX Anywhere 2S bluetooth mouse.

When crouton is not on, trackpad works fine. Once I enter into crouton, inside crouton trackpad works fine. But once I CTRL+ALT+leftArrow out to ChromeOS, the trackpad seems off. Only once I log out of crouton does trackpad function normally.

Note that when I have the mouse connected to my Chromebook, the pointer works both inside and outside crouton.

I am on stable channel for Samsung Chromebook Pro. I am using Ubuntu Xenial with integration extension installed. I only enter crouton in Xorg mode, however.

EDIT:
To my surprise, if I completely remove the device from bluetooth paired device list, trackpad functionality returns when I tab out to ChromeOS while crouton is active. So it is certainly the bluetooth mouse causing this issue.

**Comment by AthreyaV** [comment]
same issue on Unity desktop, setup is exactly the same as op described. Only difference is that this problem started out of the blue and I have no bluetooth devices paired.
