### ISSUE TITLE
Cannot entering the xfce.

### ISSUE THREAD

**Issue by shockw4ver** [dnschneid/crouton#3542]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version git
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel glimmer 
kernel: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:31:32 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
After installation, I try to ``sudo startxfce4``, but ``unmounting`` showed immediatly after ``entering`` showed. 

#### If known, describe the steps to reproduce the issue:
**first**: sudo sh ~/Downloads/crouton -r xenial -t xfce
**second**: wating...
**third**: sudo startxfce4
**now**: have no idea...

**Comment by DennisLfromGA** [comment]
@shockw4ver,

> crouton: version git

Are you using a branch or modified version of crouton?

-**DennisL**

**Comment by shockw4ver** [comment]
@DennisLfromGA   Yes, I used a modified version whose source of audio module is reachable for me.

**Comment by DennisLfromGA** [comment]
@shockw4ver,

We normally suggest you update your chroot to incorporate the latest changes but that may not be an option for you. It's difficult to make any suggestions without knowing what you're using.

-**DennisL**

**Comment by shockw4ver** [comment]
@DennisLfromGA 
I used the original edition just now and met another problem...

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libgssapi3-heimdal_1.7~git20150920+dfsg-4ubuntu1_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cyrus-sasl2/libsasl2-modules-db_2.1.26.dfsg1-14build1_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.26.dfsg1-14build1_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.42+dfsg-2ubuntu3_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/r/rtmpdump/librtmp1_2.4+20151223.gitfa8646d-1build1_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl3-gnutls_7.47.0-1ubuntu2_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apt/apt-transport-https_1.2.10ubuntu1_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.0.2g-1ubuntu4_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20160104ubuntu1_all.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/w/wget/wget_1.17.1-1ubuntu1_amd64.deb  Cannot initiate the connection to 8888:80 (0.0.34.184). - connect (22: Invalid argument)
```
first met logs above I tried to ``sudo sh crouton -r xenial -u`` after stop proxy, but useless...

**Comment by DennisLfromGA** [comment]
@shockw4ver,

> first met logs above I tried to sudo sh crouton -r xenial -u **after stop proxy**, but useless...

It appears it can't reach the repo site, are you sure the proxy is not interfering?

I just updated an 'xenial' release without a problem.

-**DennisL**

**Comment by shockw4ver** [comment]
@DennisLfromGA 
I'm sure that stop proxy now, but first time run crouton I used ``-P`` to set a proxy whose port is '8888', and now the log has an '8888:80' word, did this means proxy was still working ? Or it was just cached by the first time ran.

**Comment by TheAspiringHacker** [comment]
I have this problem as well, and it persists even though I successfully updated my chroot. I am using the version of Crouton downloaded from the README's link.

    name: stretch
    encrypted: no
    Entering /mnt/stateful_partition/crouton/chroots/stretch...
    crouton: version 1-20171122220410~master:99877eaf
    release: stretch
    architecture: amd64
    xmethod: xorg
    targets: xfce,keyboard
    host: version 9901.77.0 (Official Build) stable-channel auron_yuna 
    kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:30:51 PST 2017 x86_64 GNU/Linux
    freon: yes
    Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
    name: xenial
    encrypted: no
    Entering /mnt/stateful_partition/crouton/chroots/xenial...
    crouton: version 1-20171122220410~master:99877eaf
    release: xenial
    architecture: amd64
    xmethod: xiwi
    targets: xiwi,xfce
    host: version 9901.77.0 (Official Build) stable-channel auron_yuna 
    kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:30:51 PST 2017 x86_64 x86_64 
    x86_64 GNU/Linux
    freon: yes
    Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

https://github.com/dnschneid/crouton/issues/3557 is probably the same issue...
