### ISSUE TITLE
sh: Can't open /home/chronos/user/downloads/crouton

### ISSUE THREAD

**Issue by HELPMEPLS47** [dnschneid/crouton#3545]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by DennisLfromGA** [comment]
@HELPMEPLS47,

The 'downloads' part should be '**D**ownloads' since it's case sensitive.
So for example, it should be: `sudo sh ~/Downloads/crouton ...`

Hope this helps,
-DennisL
