### ISSUE TITLE
localhost login 

### ISSUE THREAD

**Issue by MinasY** [dnschneid/crouton#3551]
Please paste the output of the following command here: `sudo edit-chroot -all`

#### Please describe your issue:   
Cannot access Linux it keeps telling me I have incorrect login it will not boot up anything besides chrome os and the dev console 

#### If known, describe the steps to reproduce the issue:   
after I enter sudo startxfce4 my Chromebook resets to back to chrome os and I press ctrl+ alt +forward which takes me to  the dev console which ask  for my localhost login and password no matter how many times I enter it and reset the process it does not work

**Comment by DennisLfromGA** [comment]
@MinasY,

Please show us the output of: `sudo edit-chroot -all`

----
> after I enter sudo startxfce4 my Chromebook resets to back to chrome os and I press ctrl+ alt +forward which takes me to the dev console which ask for my localhost login and password no matter how many times I enter it and reset the process it does not work

Did you set a root or chronos password?
If so, you'll need to enter the password you set it up with.

----
To switch between your chroot(s) and Chrome OS use: 
<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>back</kbd> and <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>forward</kbd>

----
*Hope this helps,*
-**DennisL**

**Comment by MinasY** [comment]
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171122220410~master:99877eaf
release: trusty
architecture: arm64
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:29:42 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by MinasY** [comment]
it will not let me switch out using  ctrl+alt+shift+forward

**Comment by DennisLfromGA** [comment]
@MinasY,

I would suggest adding the 'xiwi' xmethod and trying it instead of 'xorg'.
You can add it to your existing chroot using the following:

`sudo sh ~/Downloads/crouton -n trusty -t xiwi -u`

Then be sure to install the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension from the Chrome Web Store.

After that just launch your desktop the same way using:

`sudo startxfce4`

If you want to launch it using 'xorg' again use this:

`sudo startxfce4 -X xorg`

*Hope this helps,*
-**DennisL**

**Comment by MinasY** [comment]
nothing has worked up to this date I just reset my Chromebook can anyone give me a guide maybe I'm doing something wrong

**Comment by DennisLfromGA** [comment]
@MinasY,

Sorry to hear you couldn't get anything to work.

Here's a pretty good, thorough walk-thru that I often refer people to:
- [Install Apps on Your Chromebook With Ubuntu Linux](https://chromeunboxed.com/install-native-apps-on-your-chromebook-with-ubuntu-linux/)

I think it's very helpful and fairly recent too, it has a good step-by-step guide along with a youtube video

*Hope this helps,*
-**DennisL**
