### ISSUE TITLE
Firefox no longer runs on any chroot

### ISSUE THREAD

**Issue by ohnoplus** [dnschneid/crouton#3552]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

chronos@localhost / $ sudo edit-chroot -all

> name: autumnwind
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/autumnwind...
> crouton: version 1-20170901092920\~master:0216f9d1
> release: xenial
> architecture: armhf
> xmethod: xiwi
> targets: xfce,xiwi
> host: version 9901.77.0 (Official Build) stable-channel veyron_minnie 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:31:23 PST 2017 armv7l armv7l armv7l GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/autumnwind...
> name: foxtest
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/foxtest...
> crouton: version 1-20171122220410\~master:99877eaf
> release: xenial
> architecture: armhf
> xmethod: xorg
> targets: xfce
> host: version 9901.77.0 (Official Build) stable-channel veyron_minnie 
> kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:31:23 PST 2017 armv7l armv7l armv7l GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/foxtest...
> name: xenial
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
> /usr/local/bin/enter-chroot: 511: cannot create /run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/crouton/name: Directory nonexistent
> Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
As of a chrome update several months ago, Firefox crashes upon initialization every time.

This happens even with a freshly installed chroot. It happened even after powerwashing my chromebook.

This is an asus c100p

I haven't yet tested this on non xenial xfce chroots, but can if someone thinks that will help.

#### If known, describe the steps to reproduce the issue:

1. Download crouton from https://goo.gl/fd3zc
2.  `sudo sh ~/Downloads/crouton -t xfce -n foxtest`
3. `sudo startxfce4 -n foxtest`
4. From the terminal window in foxtest : ` sudo apt-get install firefox`
5. run firefox from terminal with firefox
6.  Mozilla Crash Reporter opens directly. If I restart, the crash reporter opens back up. If I quit, firefox shuts down as expected.

**Comment by DennisLfromGA** [comment]
@ohnoplus,

Correct, it no longer works on ARM devices and is only supported on Tier-3 platforms.
See this page for more info. - [Supported build targets](https://developer.mozilla.org/en-US/docs/Mozilla/Supported_build_configurations)

(Dup of Firefox for armv7 chromebook wont work anymore #3530)

*Hope this helps,*
-**DennisL**
