### ISSUE TITLE
Cannot startxfce4.

### ISSUE THREAD

**Issue by closedbob** [dnschneid/crouton#3557]
Please paste the output of the following command here: ```sudo edit-chroot all```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171122220410~master:99877eaf
release: trusty
architecture: arm64
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:29:42 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: touch,xfce,xiwi,unity
host: version 9901.77.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:29:42 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@closedbob,

- Are you not able startxfce4 for either trusty or xenial chroots?
- What errors are displayed if any?

> name: xenial
> crouton: version unknown

- What version of xenial are you using?
- Have you tried using the 'xiwi' xmethod in your xenial chroot?

-**DennisLfromGA**

**Comment by TheAspiringHacker** [comment]
@DennisLfromGA I don't know what @closedbob has experienced, but for me, the problem is with `enter-chroot` (therefore also occurring with Xiwi).

**Comment by DennisLfromGA** [comment]
@TheAspiringHacker,

> ... the problem is with enter-chroot (therefore also occurring with Xiwi).

Your issue may not be related to @closedbob 's issue, it's hard to tell without any diagnostics.

- Show us the output of: `sudo edit-chroot -all`
- What errors are displayed if any when running `enter-chroot`?

Anything you can tell us or show us would probably be helpful, right now there's not much to go on.

-**DennisLfromGA**

**Comment by TheAspiringHacker** [comment]
Output:

    name: stretch
    encrypted: no
    Entering /mnt/stateful_partition/crouton/chroots/stretch...
    crouton: version 1-20171122220410~master:99877eaf
    release: stretch
    architecture: amd64
    xmethod: xorg
    targets: xorg,xiwi,xfce,keyboard
    host: version 9901.77.0 (Official Build) stable-channel auron_yuna 
    kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:30:51 PST 2017 x86_64 GNU/Linux
    freon: yes
    Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
    name: xenial
    encrypted: no
    Entering /mnt/stateful_partition/crouton/chroots/xenial...
    crouton: version 1-20171122220410~master:99877eaf
    release: xenial
    architecture: amd64
    xmethod: xiwi
    targets: xiwi,xfce
    host: version 9901.77.0 (Official Build) stable-channel auron_yuna 
    kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Nov 13 16:30:51 PST 2017 x86_64 x86_64 
    x86_64 GNU/Linux
    freon: yes
    Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

When I do `sudo startxfce4` or `sudo enter-chroot`, the output

    Entering /mnt/stateful_partition/crouton/chroots/stretch...
    Unmounting /mnt/stateful_partition/crouton/chroots/stretch...

occurs. Since I added xiwi as a target,

    Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/stretch...

appears afterward. (The message has appeared before when I could still enter the chroot.) Also see https://github.com/dnschneid/crouton/issues/3542.

**Comment by TheAspiringHacker** [comment]
@DennisLfromGA 

Update: I don't know what I exactly did, but after updating my chroot (perhaps adding Gnome as a target made a difference, even though I'm still using XFCE?), I was able to do `enter-chroot` without having the problem. From there, I ran `startxfce4` and got the display to work via Xiwi. If I do `sudo startxfce4` from Chrome OS, I still get the error (and apparently Xiwi is not used).

**Comment by DennisLfromGA** [comment]
@TheAspiringHacker,

Hmmm, that sounds strange. 
I don't know why it wouldn't work from CrOS but I guess if you can get it to launch from inside the chroot it's a workaround at least - that's good.

-**DennisLfromGA**

**Comment by closedbob** [comment]
@DennisLfromGA i get `chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic aarch64 Ubuntu
Current Operating System: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:29:42 PST 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashtree=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=a071e6b8e6ccbfbf469a307c340eda33c30cc440 salt=d5c1b01c9c1b1a9eb5c753ffba5258a77a740e96f7320f545023bb389e4acce0" noinitrd vt.global_cursor_default=0 kern_guid=12a8c470-5762-934e-adb4-39c1a1843329  
Build Date: 13 October 2017  01:59:18PM
xorg-server 2:1.15.1-0ubuntu2.11 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jan 16 12:25:50 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x44) [0x7622d591c]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...`
sorry for taking so long to respond but i was researching. Also, this is another problem that i saw others having. didnt exactly see a solution except installing precise but crouton wont open for some reason to install precise.

**Comment by closedbob** [comment]
Hey-
The issue is that `startxfce4` doesn't work, but `enter-chroot` does. The output is this:
`chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic aarch64 Ubuntu
Current Operating System: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:29:42 PST 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashtree=PARTUUID=12a8c470-5762-934e-adb4-39c1a1843329/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=a071e6b8e6ccbfbf469a307c340eda33c30cc440 salt=d5c1b01c9c1b1a9eb5c753ffba5258a77a740e96f7320f545023bb389e4acce0" noinitrd vt.global_cursor_default=0 kern_guid=12a8c470-5762-934e-adb4-39c1a1843329  
Build Date: 13 October 2017  01:59:18PM
xorg-server 2:1.15.1-0ubuntu2.11 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jan 18 08:24:01 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x44) [0x36f6b191c]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.`
