### ISSUE TITLE
Subsequent xinit calls fail with inability to move logs.

### ISSUE THREAD

**Issue by plbogen** [dnschneid/crouton#3558]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,keyboard,extension,core,x11
host: version 9901.77.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-16037-gf59ef0b48a68 #1 SMP PREEMPT Mon Nov 13 16:36:01 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
Log file for Xorg cannot be moved by xinit

#### If known, describe the steps to reproduce the issue:
While in the chroot, I do xinit. It comes up fine. 
I close it and do xinit again, I get:
    Cannot move old log file "/tmp/Xorg.crouton.2.log" to "/tmp/Xorg.crouton.2.log.old"

I remove the log and repeat and the same thing happens, works once than the error.
I

**Comment by icecream95** [comment]
It seems you're having problems with permissions on the tmp files.
Try giving the user you want to log in to ownership of the tmp files so crouton can move around the log files:
`chown 1000 /tmp/Xorg.crouton*`

**Comment by plbogen** [comment]
I did try that but each time I restart crouton I have to redo it.

However a second identical machine did not have that issue. The one that did, I ended up telling X to save logs elsewhere.
