### ISSUE TITLE
shell, sudo startxfce4 not working, (ee) no screens found (ee)

### ISSUE THREAD

**Issue by AndiKosno** [dnschneid/crouton#3560]
INPUT:
shell
sudo startxfce4
OUTPUT:
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-45-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-16037-gf59ef0b48a68 #1 SMP PREEMPT Mon Nov 13 16:34:35 PST 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=65dac64c-483e-6546-99aa-495fde44b40e/PARTNROFF=1 hashtree=PARTUUID=65dac64c-483e-6546-99aa-495fde44b40e/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=53c3923b5822815799aca8135af727782ae18d2e salt=803a9a5e9cf04a9112c72cb6ed011280e1eb19b92abdfb9460beac870f149652" noinitrd vt.global_cursor_default=0 kern_guid=65dac64c-483e-6546-99aa-495fde44b40e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 02 November 2016  10:06:10PM
xorg-server 2:1.18.4-0ubuntu0.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Dec 16 11:03:29 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
Session terminated, terminating shell.../usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: unexpected signal 2
 ...terminated.

I cannot access my linux from a basic samsung chromebook intel
I got my older brother to help me install this but he has no clue on how to fix this.
Thanks

**Comment by AndiKosno** [comment]
Could my build possibly be outdated, as it is the build from November 2, 2016?

**Comment by closedbob** [comment]
update it ASAP, most likely is bugged.

**Comment by AndiKosno** [comment]
I do not know what component I need to update, could you help?

**Comment by tblaschke** [comment]
Just update crouton and also your chroot.
Taken from the readme:

> A new version of crouton came out; my chroot is therefore obsolete and sad
> Check for updates, download the latest version, and see what's new by running croutonversion -u -d -c from the chroot (run croutonversion -h to see what those parameters actually do).
> Exit the chroot and run sudo sh ~/Downloads/crouton -u -n chrootname. It will update all installed targets.
