### ISSUE TITLE
Black window with Firefox and Chromium inside chroot with GPU acceleration after upgrade to ChromeOs 64.

### ISSUE THREAD

**Issue by pmarkkula** [dnschneid/crouton#3565]
```
name: xenial-xorg
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial-xorg...
crouton: version 1-20171119224248~master:c73e7a80
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,xfce,extension,xorg
host: version 10176.13.1 (Official Build) beta-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Dec 13 11:58:09 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial-xorg as another instance is using it.
```

#### Please describe your issue:
Firefox and Chromium in chroot show only black window if GPU acceleration is in use.

#### If known, describe the steps to reproduce the issue:
Upgrade to ChromeOs 64, start either Firefox or Chromium with GPU acceleration enabled.

**Comment by pmarkkula** [comment]
Starting Chromium with --disable-gpu works. Removing

`user_pref("layers.acceleration.force-enabled", true);`

from my prefs.js makes Firefox work.

**Comment by pmarkkula** [comment]
After todays updates to Xenials graphics stack, everything seems to be working again.

**Comment by Ots-darva** [comment]
Hello pmarkkula - or anyone else here,

I've also been running into this issue on a trusty install on a Toshiba Chromebook 2 (2015). Your workaround for chromium has worked a treat but unfortunately Steam also launches in a black window for me and updating the chroot doesn't seem to have worked.

Anyone have any suggestions for getting Steam to work? Or do I just have to wait for an update to fix it?

Thanks
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: amd64
xmethod: xorg
targets: xiwi,xfce,keyboard,extension
host: version 10315.0.0 (Official Build) dev-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Jan 16 19:22:42 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by pmarkkula** [comment]
Moving on to Xenial might also work. I haven't had this problem since the update fixed it for me. There is no guarantee that it will be fixed in Trusty.

This issue should be reopened, or new one should be created , if this is affecting you.

**Comment by Ots-darva** [comment]
Thanks, I'll have to give Xenial a go. For now I've opened another ticket (3618).
