### ISSUE TITLE
How do I update ubuntu

### ISSUE THREAD

**Issue by AndiKosno** [dnschneid/crouton#3567]
```
Please paste the output of the following command here: sudo edit-chroot -all
```name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce

When I do sudo startxfce4 it says no screens found, and I think I have an outdated ubuntu, and if I do not, what is it? (my other post https://github.com/dnschneid/crouton/issues/3560 )

**Comment by DennisLfromGA** [comment]
@AndiKosno,

In your case, to update your chroot enter the following:

- `sudo sh ~/Downloads/crouton -n xenial -u`

For help with many issues take a look at this guide:

- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisLfromGA**

**Comment by AndiKosno** [comment]
the output
sh: Can't open /home/chronos/user/Downloads/crouton
any more help?

**Comment by DennisLfromGA** [comment]
@AndiKosno,

It looks like crouton was removed from your `~/Downloads` folder.
You can get a brand new one from here; [https://goo.gl/fd3zc](https://goo.gl/fd3zc)

*Hope this helps,*
-**DennisLfromGA**

**Comment by AndiKosno** [comment]
@DennisLfromGA Thank you so much!
