### ISSUE TITLE
Functional key mapping changes in chromeos after running crouton

### ISSUE THREAD

**Issue by terry-flowers** [dnschneid/crouton#3570]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xiwi
targets: keyboard,core,extension,xiwi
host: version 10176.22.0 (Official Build) beta-channel eve 
kernel: Linux localhost 4.4.96-12261-gdb097edeea73-dirty #1 SMP PREEMPT Tue Dec 19 22:25:42 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

After running crouton to create a chroot, some of the function key mappings no longer map correctly within ChromeOS and the chroot.

Reload => forward
Fullscreen => Reload
Switch window => Full screen
Brightness down => Switch Window
Brightness up => Brightness down
play/pause => brightness up

The others remain correct.

**Comment by DennisLfromGA** [comment]
@johnsmith240,

The Pixelbook keyboard shuffled the top row keys around a bit so this may be contributing to some of these anomalies I think. 

The Pixelbook Keyboard Overlay with the *'Launcher'* key pressed shows the following -
![keyboard_overlay_search](https://user-images.githubusercontent.com/3418772/34320954-f453dbca-e7d1-11e7-9ff2-a5ae74723f50.png)

But the [Pixelbook Help page](https://support.google.com/pixelbook/answer/7504061?hl=en) describes it a bit differently -
![pixelbookhelp_toprowkeys](https://user-images.githubusercontent.com/3418772/34320977-7b3e03fe-e7d2-11e7-8d8d-fe7f751e901b.png)

There is a [`keyboard target`](https://github.com/dnschneid/crouton/blob/master/targets/keyboard) that "adds support for Chromebook keyboard special keys."
I don't know if it needs tweaking for the Pixelbook or not, I'm afraid I quickly get lost when talking about keycode assignments and such.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DavidMorton** [comment]
I managed to mostly fix this by replacing the file at /usr/share/X11/xkb/symbols/chromebook with the contents of the attached text file. I'm not positive on the "PLAY" overlay (someone might be able to correct me here), but this should at least shift the keys so they make more sense. 

[chromebook.txt](https://github.com/dnschneid/crouton/files/2398885/chromebook.txt)
