### ISSUE TITLE
How do I add support for chrome crouton extension?

### ISSUE THREAD

**Issue by novamelissa** [dnschneid/crouton#3572]
I installed crouton/ubuntu with the command "sudo sh crouton -t kde-desktop" how do I fix so that I can use the chrome extension ?

**Comment by divx118** [comment]
`sudo sh ~/Downloads/crouton -n trusty -u -t extension`

**Comment by novamelissa** [comment]
Ok thanks, one more stupid question, I think "xenial" -version was installed. Do I replace trusty with xenial?

**Comment by divx118** [comment]
`-n <chrootname>` So if you indeed installed xenial then yes you should replace `trusty` with `xenial` in your command.

**Comment by novamelissa** [comment]
Thanks for the quick answer.
