### ISSUE TITLE
xiwi screen freezes and repeats last key stroke

### ISSUE THREAD

**Issue by hofstee** [dnschneid/crouton#3575]
```
chronos@localhost / $ sudo edit-chroot -all
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20171122220410~master:99877eaf
release: sid
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,lxde,keyboard,cli-extra
host: version 10230.0.0 (Official Build) dev-channel sentry 
kernel: Linux localhost 3.18.0-16380-ged556dd88087-dirty #1 SMP PREEMPT Tue Dec 19 11:20:31 PST 2017 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...
```

#### Please describe your issue:
I wasn't sure if I should resurrect a closed issue or create a new one, so I created a new one. This is basically the exact same problem as described in #2181. I noticed some `xsel: realloc error: Resource temporarily unavailable` on the shell I launched the chroot from. I'm not sure if these are related.

#### If known, describe the steps to reproduce the issue:
Just use a chroot in xiwi for a while, and it will appear, and then appear more frequently after the first occurrence.

**Comment by afraser3** [comment]
Hi, I'm having exactly the same issue. From what I can tell, my setup is the same as yours, too. Were you ever able to resolve this?
