### ISSUE TITLE
Black Screen on entering chroot

### ISSUE THREAD

**Issue by CJ-Griffin** [dnschneid/crouton#3576]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.22.0 (Official Build) beta-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Dec 19 22:33:40 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
unity (xenial) 
toshiba cb2 2015 i3, 
worked fine until one day it ran out of battery and when I turned it back on the issue began.
When I use "sudo startunity", I boot into a black screen with a mouse on it. Occasionally if I press the mouse the proper desktop will flash on screen. The following is output in bash:

> chronos@localhost
/usr/local/chroots $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Unknown username "geoclue" in message bus configuration file
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

>X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Dec 19 22:33:40 PST 2017 x86_64
>Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=d6a8268b-d354-1a45-8122-54b3c5fd0691/PARTNROFF=1 hashtree=PARTUUID=d6a8268b-d354-1a45-8122-54b3c5fd0691/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=afe9fbeb30b21abc6edd87949e7b1fdf45dc8ea4 salt=adf7e4a4b681f16f3985752214e9318fcb119cff505be36b2e79b6ad91823c78" noinitrd vt.global_cursor_default=0 kern_guid=d6a8268b-d354-1a45-8122-54b3c5fd0691 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 13 October 2017  01:57:05PM
xorg-server 2:1.18.4-0ubuntu0.7 (For technical support please see http://www.ubuntu.com/support) 
>Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
>Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
>(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec 26 12:01:24 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

>xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

>This incident has been reported.
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.22.0 (Official Build) beta-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Dec 19 22:33:40 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
Kicking xrandr again
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't `exist`

Powerwashed Chromebook and uninstalled chroot many times. Tried to use kbe instead of unity- no different except seeing the kbe mouse.

using sudo enter-chroot I enter the (xenial)[user]@local menu but dont know what to do from here

Thanks very much for your time

**Comment by fgblanch** [comment]
I'm having the same problem. I think it has to do with the latest chromeOS update (v64 in beta channel):

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xiwi
targets: core,xiwi,gnome,xorg,keyboard,touch,x11,gtk-extra,cli-extra,extension
host: version 10176.22.0 (Official Build) beta-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Dec 19 22:15:55 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

I'm also getting the error:
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20171122220410~master:99877eaf
release: xenial
architecture: amd64
xmethod: xiwi
targets: core,xiwi,gnome,xorg,keyboard,touch,x11,gtk-extra,cli-extra,extension
host: version 10176.22.0 (Official Build) beta-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Dec 19 22:15:55 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
Kicking xrandr again
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
Cannot open /sys/class/tty/tty0/active: No such file or directory

**Comment by ProfGryphon** [comment]
@fgblanch I thought it could be too, guessing I auto-updated on restart and that's why it was broken. I'll try one of the old patches

**Comment by fgblanch** [comment]
Please add the link to the old patches if they work.

**Comment by ProfGryphon** [comment]
@fgblanch I wasn't able to work it out so in the end, I have installed GalliumOS as the sole OS on my device, and i'm really enjoying it
