### ISSUE TITLE
PolicyKit breaks whenever updating Crouton

### ISSUE THREAD

**Issue by KibSquib48** [dnschneid/crouton#3582]
I installed crouton and then decided to update the chroot so I can use Xiwi (I am on trusty 14.04) and then PolicyKit just broke. It worked fine so updating had to be the problem. So then I tried uninstalling the software center and installing it again... and it worked! This isn't really an issue, more of a solution, but I thought I should share this with the many people who are having trouble with this.

**Comment by Alexfebbraio** [comment]
The same for me.
Trusty works perfectly
Xenial and bionic have problem with policykit agent
I have read many many post but nothing solution
