### ISSUE TITLE
sh: Can't open /home/chronos/user/Downloads/crouton

### ISSUE THREAD

**Issue by milkythegoldfish** [dnschneid/crouton#3584]
```
sudo sh -e ~/Downloads/crouton -r saucy -t unity -e
```

I keep putting this in to download linux. I'm new to this and just trying to download a game on my chromebook os. I've been typing thing in numerous times correctly and searching for help re-downloading but nothing is working and I don't know what to do.

**Comment by DennisLfromGA** [comment]
@milkythegoldfish,

The Ubuntu 'saucy' release has reached end-of-life and should be avoided.
You can see which releases are current, unsupported and to be avoided below:
```
crouton -r list
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch buster sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety! zesty* artful* bionic*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```

The Ubuntu 'xenial' release is the current default and has Long Term Support (LTS) so it will be installed if you don't specify a release with the '-r' option. You might want to use the following to install an Ubuntu 'xenial' release, it will also name the chroot 'xenial' by default too:

- `sudo sh ~/Downloads/crouton -t unity`

You can add encryption after it's installed and working correctly using:

- `sudo sh ~/Downloads/crouton -n xenial -e -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by stephengale801** [comment]
If you notice, at the launch of Crouton with Chrome v64 it states that it's running in Sandboxed mode...
![image](https://user-images.githubusercontent.com/14339317/34628550-f47fa5de-f221-11e7-8eaf-03a1b2e10f4e.png)
This prevents redirection of the Downloads folder.

**Comment by DennisLfromGA** [comment]
@stephengale801,

That's a different issue (Get rid of wget dependency, and workaround awk sandbox #3514) that's already been merged, just update your chroot for the fix.

*Hope this helps,*
-**DennisLfromGA**

**Comment by stephengale801** [comment]
Updated chroot (trusty) a moment ago and still getting the awk error.

**Comment by DennisLfromGA** [comment]
@stephengale801,

Okay, but let's not confuse this issue. 

Maybe take a look at this issue 'Merge commits not in newest release? #3528' and this comment 'https://github.com/dnschneid/crouton/issues/3528#issuecomment-346537667' for help - or open a new issue with details about what you've tried and what's happening.

*Hope this helps,*
-**DennisLfromGA**
