### ISSUE TITLE
Edit-Chroot not found

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3587]
```
edit-chroot command not found
```

#### Please describe your issue:
edit-chroot is not found. Cant edit-chroot or back up chroot or anything. I have crouton downloaded on my chromebook but my linux and everything is on a sd card. I tried running in shell and in the sd card place where i run startxfce4.

**Comment by Lionbrine** [comment]
I am guessing this has to do with the way everything is routed. I do not know what to type to get where I need to type edit-chroot commands etc. My sd card is named kali btw.

**Comment by DennisLfromGA** [comment]
@Lionbrine,

Where did you install it, what's the PATH to your chroots?
If they are in: `/media/removable/kali/chroots` then you can probably run the `edit-chroot` command like so:
- `sudo /media/removable/kali/bin/edit-chroot -all`

Adjust the PATH above if the `/bin` folder is different from above.

You can also launch your desktop in a similar fashion like:
- `sudo /media/removable/kali/bin/startxfce4`

If you installed a different desktop use its start* script instead.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Lionbrine** [comment]
@DennisLfromGA It currently says permission denied and also my chroot folder is outside the bin folder. in the bin folder there are files like edit-chroot and enter-chroot and startxfce4

**Comment by DennisLfromGA** [comment]
@Lionbrine,

> It currently says permission denied ...

Okay, sorry, the default mount options are noexec for external media so those commands are not executable. You'll need to add '`sh`' after sudo like below:
- `sudo sh /media/removable/kali/bin/edit-chroot -all`
- `sudo sh /media/removable/kali/bin/startxfce4`

> and also my chroot folder is outside the bin folder.

The '/bin' and '/chroots' folders *should* be under the same *parent* folder, in your case probably under:
- `/media/removable/kali`

If not you may need to adjust the PATH above if they are in a different location.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Lionbrine** [comment]
@DennisLfromGA It gives me a bunch of information about the chroot and it says it failed to unmount the chroot. How would I change the chroot to add a proxy?

-------------------------------------------------------
chronos@localhost / $ sudo sh /media/removable/kali/bin/edit-chroot -all
name: kali-rolling
encrypted: no
Entering /media/removable/kali/chroots/kali-rolling...
crouton: version 1-20171122220410~master:99877eaf
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-16037-gf59ef0b48a68 #1 SMP PREEMPT Mon Nov 13 16:34:35 PST 2017 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/kali/chroots/kali-rolling...
Failed to unmount /media/removable/kali/chroots/kali-rolling. Kill processes? [a/k/y/p/N] y
Sending SIGTERM to processes under /media/removable/kali/chroots/kali-rolling...
---------------------------------------------------------------------------------------------------------------------

**Comment by DennisLfromGA** [comment]
@Lionbrine,

> It gives me a bunch of information about the chroot ...

It also tells us some very important things about your chroot too like -
- if it's using the latest version, which it is: 99877eaf
- what device your using: Samsung Chromebook 3
- what release your using: kali-rolling
- what xmethod your using: xorg
- what targets you specified on the command line: xfce

> ... and it says it failed to unmount the chroot. 

No biggey, you could have answered 'k' to kill the processes but a reboot will definitely unmount everything too.

> How would I change the chroot to add a proxy?

You set a proxy for 'crouton' using the '-P' option as shown below -
```
   -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
```

> Also what does sh mean/do?

[ *This is my understanding that is probably not entirely correct so apply a grain of salt* ]
When the script is not executable, in this case on media that's mounted as 'noexec' the 'sh' uses the command line interpreter, in CrOS `/bin/sh -> dash` to read & execute the script ignoring any file permissions it has. 

*Hope this helps,*
-**DennisLfromGA**

**Comment by Lionbrine** [comment]
@DennisLfromGA Thanks for all the help and information and help, yet I am still stuck, feel so dumb lol :D. Where would I run the -P PROXY command at?

**Comment by mckaygerhard** [comment]
why the editchroot command are not inside the crouton-installer downloaded in the /tmp path? why in the chroot install path?

@DennisLfromGA documentation wiki must point that this command are only available AFTER install a chroot environment, not before... and only in specific path...

**Comment by DennisLfromGA** [comment]
@Lionbrine,

The proxy is sometimes needed when you install your crouton chroot, it's entered as an option when you're installing crouton similar to below:

`sudo sh ~/Downloads/crouton -r kali-rolling -p /media/removable/kali -t xfce -P 80.211.157.69`

I think that's the correct way, I've honestly never used one myself so you may have to tweak that a little.
> Note: The address above is one I found for Italy here: https://www.proxynova.com/proxy-server-list/

*Hope this helps,*
-**DennisLfromGA**
