### ISSUE TITLE
No WiFi after installing Crouton & Ubuntu (latest)

### ISSUE THREAD

**Issue by BusterGasket** [dnschneid/crouton#359]
I have just gone through the process of installing Crouton and Ubuntu on an Acer C7 Chromebook.  All seems to have gone OK, but when in Ubuntu I have no internet access, yet Chrome OS does. When I open up the network prefs it tells me that "The system network services are not compatible with this version"

The network prefs pane shows "Network Proxy" in the left hand side as the only choice. I tried clicking the + button to add a wifi connection, but all I get as an option is VPN.

I have no idea how to get around this.  Will anyone help please?

**Comment by RoseAfriyie** [comment]
@dnschneid - I am having issues connecting to the internet and having trouble navigating to the chroot. Any suggestions?

**Comment by RoseAfriyie** [comment]
That is, connecting to the internet with Crouton.

**Comment by RoseAfriyie** [comment]
My apologies! Totally fixed it. Sorry to bug you @dnschneid

**Comment by Jackhford** [comment]
I'm having the same problem with my C720 which I'm about to give to my grandson. Wifi works perfectly in Chrome OS, but it's not working in my chroot running Ubuntu 14.04.
Interfaces file contains the following:
"source-directory /etc/network/interfaces.d" and the directory "interfaces.d" is empty.
Thanks
