### ISSUE TITLE
Crouton doesn't start after (attempted?) upgrade to xenial

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3592]
I tried to upgrade from trusty to xenial today following the instructions on this git. I'm not really sure if it worked or not, but I do know that I can't get anything to start anymore.

```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,xfce
host: version 9901.77.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:38:30 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Failed to unmount /mnt/stateful_partition/crouton/chroots/xenial. Kill processes? [a/k/y/p/N] y
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
When I try to start crouton, this is where it fails:

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
vesa: Ignoring device with a bound kernel driver
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

**Comment by DennisLfromGA** [comment]
@rlb178,

> I tried to upgrade from trusty to xenial today following the instructions on this git. 

What instructions did you follow, these? [Upgrade chroot release](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release)
If so, which method did you use: the Ubuntu Update Manager or the command line?
Did the update complete successfully?

> I'm not really sure if it worked or not, but I do know that I can't get anything to start anymore.

Your chroot still reports the 'trusty' release.
Have you updated your chroot after the upgrade attempt with crouton's '-u' option?

-**DennisLfromGA**
