### ISSUE TITLE
No more cinnamon target?

### ISSUE THREAD

**Issue by dakotasings** [dnschneid/crouton#3595]
Okay, maybe I'm schizophrenic but I swear to god I saw a target for cinnamon like 3 days ago. I've been trying multiple different distros and was going to try it but now it's dissappeared?

**Comment by DennisLfromGA** [comment]
@dakotasings,

Maybe you saw this discussion: **Replacing XFCE with Cinnamon #3573**

The cinnamon target was removed a while ago: **remove cinnamon target #832**
And was requested again: **REQ: re-add cinnamon target #1381**

But nothing has been done recently.

*Hope this helps,*
-**DennisLfromGA**
