### ISSUE TITLE
E: Failed getting release file http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release

### ISSUE THREAD

**Issue by Mohamedemad4** [dnschneid/crouton#3596]
Hello,I have recently Powerwashed my Chromebook Asus C201, Before that I Had _xenial_ with _cli-extra_ and it was working well so I decided this time around to try _xiwi_ so I download crouton install  from  _https://raw.githubusercontent.com/dnschneid/crouton/master/installer/crouton_ and ran the following command `sudo sh ~/Downloads/crouton -t xiwi 2>&1 | tee  ~/Downloads/out.txt`
I am on chrome os  `64.0.3282.41 (Official Build) beta (32-bit)`
but it had the following output:

`Installing xenial-armhf chroot to /usr/local/chroots/xenial
Downloading latest debootstrap...

######################################################################## 100.0%
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
I: Retrieving InRelease 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease
W: http://ports.ubuntu.com/ubuntu-ports/dists/xenial/InRelease was corrupt
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
I: Retrieving Release 
W: Retrying failed download of http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release
W: http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release was corrupt
E: Failed getting release file http://ports.ubuntu.com/ubuntu-ports/dists/xenial/Release`

so I retried  but with cli-extra  `sudo sh ~/Downloads/crouton -t cli-extra` but it had the same output
I dont know what is happing I can still ping and download files from shell without any trouble 
but I can`t reach it via the browser or shell.

**Comment by DennisLfromGA** [comment]
@Mohamedemad4,

I opened a few of the links above and they worked.
It may have been a temporary transient network error, try again (and again) later.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Mohamedemad4** [comment]
I Have figured it out my router blocks all HTTP traffic, thanks anyway
