### ISSUE TITLE
Trackpad won't move cursor on Acer R11 

### ISSUE THREAD

**Issue by kateneedham14** [dnschneid/crouton#3597]
```
Output of sudo edit-chroot -all:
name: gnomechroot
encrypted: yes, locked

Output of sudo edit-chroot -n gnomechroot croutonversion:
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome-desktop,touch
host: version 10032.75.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Dec 18 20:26:57 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
I'd been running crouton on a Acer R11 pretty successfully for about a week when the trackpad suddently stopped responding partially. It can click and scroll but it can't move the cursor around the screen. Using an external Logitech USB mouse has no problems. The trackpad has no problems in ChromeOS.

(For reference, the the trackpad had previously been working fine except that tap-to-click was disabled, but I had fixed that by enabling it through the Mouse and Touchpad settings in Ubuntu. Now when I look at those settings, the tap-to-click and two finger scroll buttons are greyed out, but the natural scroll, touchpad On/Off button, and speed slider are active but adjusting them has no impact on the cursor problem. Not sure if this is relevant but thought I'd throw it in.)

I've attempted the `synclient FingerLow=1 FingerHigh=5` fix but it returns "Couldn't find synaptics properties. No synaptics driver loaded." When I check `xinput -list` "Elan Touchpad" is listed right there, but I don't understand the readout in `xinput list-props 12` enough to try readjusting the sensitivity there.

I'm pretty new to Linux and I've been trying to find fixes out there and I've seen there's been a couple similar problems with Acer touchpads but I haven't had any success-- I read somewhere that synclient has been replaced by libinput but I haven't figured out how to install `xf86-input-libinput`. And I'm too new to this to understand how to port the ChromeOS driver as listed here: https://github.com/hugegreenbug/xf86-input-cmt

When I update the chroot I get this error:
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome-desktop,touch
host: version 10032.75.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Dec 18 20:26:57 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output HDMI2 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output HDMI2 is not disconnected but has no modes
Kicking xrandr again
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

Any suggestions or gentle nudges in the right direction would be so helptul. Thank you and thank you for making crouton, it's awesome!

**Comment by maniyar1** [comment]
Late reply for this. Preemptive note that I have not contributed to Crouton and have not read up about its most inner workings, that being said I have the same laptop (and the same problem), and I have pseudo-fix for you. I'm not sure if this is a crouton thing, but I've been having the same issue. My current advice is to run Debian Stretch, it is the only distro I found to work (previous not tested). Even Buster and Sid don't work which I find interesting. I hope this helps!
