### ISSUE TITLE
Move my chroot "FROM" sd card ( /media/removable/UNTITLED/xenial ) "TO" /mnt/stateful_partition/crouton/chroots/ 

### ISSUE THREAD

**Issue by sujaybr** [dnschneid/crouton#3598]
Solved the problem by first backing it up and then restoring it back to /mnt/stateful_partition/crouton/chroots/xenial.
The Problem is now solved.
Thank You

**Comment by DennisLfromGA** [comment]
@sujaybr,

Backing up & restoring is a very good, safe way to do it and the one I use when moving a chroot.

Just for future reference you *can* also use `edit-chroot` to move or even copy it, see the syntax below:

```
    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.

    -C DEST     Like -m, but copies instead of moves.
```

So to move a chroot from external media to internal storage you would use something like the following:

- `sudo  /media/removable/usbstick/bin/edit-chroot xenial -m /usr/local/chroots/`

*Hope this helps,*
-**DennisLfromGA**
