### ISSUE TITLE
Getting error as soon as I try to launch trusty

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3599]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: arm64
xmethod: xiwi
targets: xiwi,xfce
host: version 10032.75.1 (Official Build) stable-channel bob 
kernel: Linux localhost 4.4.86-11976-gc4c6234ae4f3 #1 SMP PREEMPT Wed Dec 20 21:49:04 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
#### Please describe your issue:
I cannot launch trusty on crouton, I tried multiple ways and looked on youtube to try their way with trusty.
https://pastebin.com/raw/wxuTvsC6
#### If known, describe the steps to reproduce the issue:
I just install trusty as normal with and without xiwi then try to start it up and get the same issue with trusty.

**Comment by closedbob** [comment]
i got this too, still can't fix it.
can you do the terminal by doing `sudo enter-chroot`?

**Comment by YoloManOof** [comment]
@closedbob Yes I can but I want to fully view trusty
