### ISSUE TITLE
sh: Can't open /home/chronos/user/downloads/crouton

### ISSUE THREAD

**Issue by bayboi1020** [dnschneid/crouton#360]
Ive followed all the instructions to add xfce to my chromebook but when i type sudo sh -e ~/downloads/crouton into shell all i get is 

we trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sh: Can't open /home/chronos/user/downloads/crouton

can someone please help me

**Comment by rleezim** [comment]
I'm having that problem as well...I type sudo sh -e ~/Downloads/crouton -t gnome-desktop -r xenial or when I did have it installed I typed sudo sh -e ~/Downloads/crouton -u -n xenial and both have returned sh: can't open /home/chronos/user/Downloads/crouton

**Comment by DennisLfromGA** [comment]
@rleezim, Try downloading crouton again: https://goo.gl/fd3zc

**Comment by smcgregor25** [comment]
@DennisLfromGA Hello! I recently started trying to download linux on my chromebook. Developer mode is on and I am entering the command correctly. However I am getting the exact same response that @rleezim was getting. Do you have any idea of an alternative way I can download linux or ubuntu?

**Comment by DennisLfromGA** [comment]
@smcgregor25,

Follow the suggestion I gave @rleezim then get familiar with the [crouton README](https://github.com/dnschneid/crouton/blob/master/README.md) before you dive in.

*Hope this helps,*
-**DennisL**

**Comment by AniAsborn** [comment]
Hi! I recently have tried all said suggestions (as I have the same problem). What I did to make this work is to rename crouton to Crouton the I typed the command: sudo sh -e ~/Downloads/Crouton -t xfce
I hope this helps!

**Comment by DennisLfromGA** [comment]
@AniAsborn,

Actually, no, that doesn't help and may just confuse others.
Linux is case sensitive and 'crouton' is all lower case and should be entered that way.

*Hope this helps,*
-**DennisL**

**Comment by chris14341** [comment]
please help says dowloaded but that my os is extraordinarily old

**Comment by DennisLfromGA** [comment]
@chris14341,

For help, please see: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisL**

**Comment by chris14341** [comment]
thank you, its exactly what ive been looking for.

**Comment by OomyGoomy** [comment]
sudo sh -e ~/Downloads/crouton -t gnome ive done everything correct and i still get 
sh: Can't open /home/chronos/user/Downloads/crouton 
I have a chrome book hp

**Comment by DennisLfromGA** [comment]
@OomyGoomy,

See https://github.com/dnschneid/crouton/issues/360#issuecomment-315504935

*Hope this helps,*
-**DennisLfromGA**

**Comment by OomyGoomy** [comment]
it did not help me it said sudo: edit-chroot: command not found.

**Comment by SkyFireSorcerer** [comment]
I used https://goo.gl/fd3zc for my cloudready and had success.

**Comment by NobodyThatMatters** [comment]
I've tried every command, and every command I do says:
sh: 0: Can't open /home/chronos/user/Downloads/crouton

**Comment by DennisLfromGA** [comment]
@NobodyThatMatters,

1. Download the crouton installer and place it in **Downloads** with this link: https://goo.gl/fd3zc
2. Open a shell session using the following key-combo: <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>t</kbd>
3. Enter: `shell`
4. Run your crouton installation command, something like: 
- `sudo sh ~/Downloads/crouton -t xfce`

*Hope this helps,*
-**DennisLfromGA**

**P.S.** You do matter... 😊

**Comment by NobodyThatMatters** [comment]
Yeah the reason it didn't work was a completely different reason, and also I'd appreciate it if you stopped closing issues even though all aspects have not been properly considered and taken into account. Crouton is now working on my chromebook, and I no longer need help with this. But you keep closing issues before they're properly resolved.

**Comment by NobodyThatMatters** [comment]
The issue I had was that certain files were not downloading properly due to an extension I had that deemed some of the files unsafe so they were not downloaded. And an example would be how I posted my own issue and you just redirected me here and closed my issue, which I guess makes sense considering, but you just proceeded to post the standard way of opening crouton without actually addressing the issue I had presented to you and then closed the issue. Also I meant every command that has been given here, it just came out wrong.

**Comment by DennisLfromGA** [comment]
@NobodyThatMatters,

> I posted my own issue and you just redirected me here and closed my issue, which I guess makes sense considering, but you just proceeded to post the standard way of opening crouton without actually addressing the issue I had presented to you and then closed the issue.

The other issue you posted did sound similar enough to me at least that I thought it would be best to close it and track everything here, sorry you thought it was over the top.

We usually bypass extension troubleshooting in here and concetrate on crouton problems, the [Chromebook Central forum](https://productforums.google.com/forum/#!forum/chromebook-central) is a good place to get help with other non-crouton problems. I do support there too so you may not be able to avoid me. 😉

Extensions can indeed be troublesome and they are sometimes difficult to troubleshoot.
I use an extension called '[Extensity](https://chrome.google.com/webstore/detail/extensity/jjmflmamggggndanpgfnpelongoepncg)' which allows you to toggle on/off one or more extensions or all of them at once.  You can even set up profiles that may help in your case and allow you to dsable that interfering extension when using crouton, etc.

*Hope this helps,*
-**DennisLfromGA**

**Comment by KhushPatel365** [comment]
I have an issue with this where whenever i type:
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
it would say:
 sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
I tried all of the steps above but none worked

**Comment by DennisLfromGA** [comment]
@KhushPatel365,

This issue was opened and closed in 2013 so I wouldn't expect it to work for you now.
Please *read* the [README](https://github.com/dnschneid/crouton/blob/master/README.md) for the new installation guide.

-**DennisLfromGA**

**Comment by zhmed** [comment]
when you write (downloads) the d needs to be in caps mean needs to be big D like this

**Comment by zhmed** [comment]
and put crouton file in Downloads not in folder

**Comment by MrHallway0** [comment]
This issue is from 2013...

**Comment by AniAsborn** [comment]
how are y'all doing? its been a few years

**Comment by tallestwheat** [comment]
I am still having trouble with this, and have not found a solution throughout the numerous comments posted here in the past seven years. 

When I press Control Alt T, type in shell, and then enter 

sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton   

It still says "Cant open /home/chronos/user/Downloads/crouton"

Could you aid me in resolving this issue?

**Comment by MrHallway0** [comment]
@tallestwheat make sure you have downloaded the file, `crouton`, to the Downloads folder of your device. Also this is a very old issue and has outdated information, a newer issue may be #4385.

**Comment by tallestwheat** [comment]
Thank you for the quick feedback, I will check out the newer thread you linked.

**Comment by tea808mups** [comment]
sudo crouton -t xfce should do the trick

**Comment by omar321mm** [comment]
![Uploading 20240729_152319.jpg…]()

**Comment by omar321mm** [comment]
sudo sh -e ~/downloads/crouton into shell all i get is

we trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
https://github.com/dnschneid/crouton/issues/1) Respect the privacy of others.
https://github.com/dnschneid/crouton/issues/2) Think before you type.
https://github.com/dnschneid/crouton/issues/3) With great power comes great responsibility.

sh: Can't open /home/chronos/user/downloads/crouton

**Comment by betapictoris** [comment]
Hello @omar321mm, welcome to GitHub!  First off, this is a fairly old closed issue, so in the future you may want to consider either searching for, or creating, a newer one (if you can't find another issue that solves your problem or seems similar to yours).  

> `sudo sh -e ~/downloads/crouton` into shell all i get is
> 
> ```
> we trust you have received the usual lecture from the local System Administrator. It usually boils down to these three things:
> #1) Respect the privacy of others.
> #2) Think before you type.
> #3) With great power comes great responsibility.
> 
> sh: Can't open /home/chronos/user/downloads/crouton
> ```

Make sure you're following the [community maintained installation instructions](https://github.com/dnschneid/crouton/wiki/Updated-Installation-Instructions-for-Crouton).  Crouton and Chrome OS has both existed for, and evolved over, many years so a guide might be out-of-date.  All things considered this error message generally means a few things for Crouton users: 

- Make sure you've downloaded the `crouton` file, as well as that it completed and has been saved correctly, from the correct URL (https://goo.gl/fd3zc?si=1).
- You shouldn't be accessing the `crouton` file directly anymore, this was a change for Chrome OS, instead you'll need to install it and access it simply with the `crouton` command: 
  ```
  sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
  ```
- Check spelling and casing of the path you're using, Linux is case sensitive and it seems that you're trying to access the file with `/home/chronos/user/downloads/crouton` instead of `/home/chronos/user/Downloads/crouton`.  

Good luck!

**Comment by KazDuCaine** [comment]
SO. I found out something that *might* work. I have yet to test it, but will in  a couple moments.
I dragged my Crouton file into Chrome and got this:
file:///home/chronos/u-676694dfb7295abc010306ea06f6e111315c78e4/MyFiles/Downloads/crouton

The file is NOT at /home/chronos/user/downloads/crouton
There are a few extra folders

I'm guessing the u-####### thing is a User ID, so each person might need to drag the file into Chrome to find out what to use in the shell. I'm testing it now, tho I'll let you know the result
