### ISSUE TITLE
Unable to launch startxfce4 on Chrome OS

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3600]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 10278.0.0 (Official Build) dev-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Jan 4 03:26:39 PST 2018 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
Unable to launch sudo startxfce4

#### If known, describe the steps to reproduce the issue:
I have tried installing crouton, sucessfully (i think) and am trying to run
bash
sudo startxfce4
i get an error saying:

Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-101-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Jan 4 03:26:39 PST 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=68f9f34c-d452-5c42-811a-ee3a7080a2a6/PARTNROFF=1 hashtree=PARTUUID=68f9f34c-d452-5c42-811a-ee3a7080a2a6/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=b89a76fa5023c7117368c0596185b11b2f07c184 salt=2f712eb6330f916cf53b806ca4c929f03216de9409f3ca5c7f80696ea868d99a" noinitrd vt.global_cursor_default=0 kern_guid=68f9f34c-d452-5c42-811a-ee3a7080a2a6  
Build Date: 24 November 2017  09:45:24AM
xorg-server 2:1.19.5-0ubuntu2~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Jan  7 15:20:30 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1515356430.236616 sender=:1.9 -> destination=:1.41 serial=617 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1515356430.621424 sender=:1.9 -> destination=:1.43 serial=619 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by dhambloch** [comment]
Hey, I'm having the same problem too (#3606). Just seen your posted issue. Any luck?
What Chromebook you got? I have  Samsung, Snow, Daisy ARM, xenial, which seems the same as yours?
Were you trying sudo startxfce4 ?

**Comment by 16200JT** [comment]
Unfortunately, no luck. 
Trying to run "sudo startxfce4" results in an error shown above.
I am also running a Samsung chrome.

**Comment by dhambloch** [comment]
I've managed to get some assistance from a friend at work who knows linux so will report back if we make progress.

**Comment by 16200JT** [comment]
@dhambloch Any luck?

**Comment by fulviofedericofarina** [comment]
Same problem here, I also have a samsung chromebook. Would be nice to get some assistance on this!

**Comment by 16200JT** [comment]
@fulviofedericofarina Yeah. Still waiting, however, no response.
