### ISSUE TITLE
Can't install crouton on Acer Chromebook 14 (CB3-431)

### ISSUE THREAD

**Issue by SniperAF** [dnschneid/crouton#3602]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Just says "Password:" and then I can't type anything
#### Please describe your issue:
I have enabled developer mode on my chromebook and installed crouton but when I go to crosh and type "shell" and then "sudo sh ~/Downloads/crouton -e -t xfce" it just says "password:"
 but I can only press enter, not that I would know what password to type anyway. How do I get past this?

**Comment by Ziinc** [comment]
The password field is hidden. Try typing out your password and pressing the return (enter) key.

It should prompt you for a password retype.

**Comment by SniperAF** [comment]
No password seems to work.

**Comment by Snotes** [comment]
Try this:

1. Press Ctrl-Alt-forward
2. Login as the user "root" and the password that you made while putting it into developer mode.
3. You should be in as localhost now. Then from here you can set a new password that works in your crosh shell. So, in the shell that we just logged into, type the command
chromeos-setdevpasswd
then you can set a password, which you will probably want to be the same password that you just used if you want to keep it simple.
4. After you have set the password from that prompt you can get sudo privileges with that password.

**Comment by DennisLfromGA** [comment]
If you enabled Debugging Feature at the first sign-in screen and didn't set a root password it will default to `test0000`.  If it still won't accept any password and you can't get a shell session then you'll have to powerwash again to remove it.

*Hope this helps,*
-**DennisLfromGA**
