### ISSUE TITLE
Useless tag

### ISSUE THREAD

**Issue by FlashDaggerX** [dnschneid/crouton#3604]
I don't have an issue with the project itself, but there's no need for a Minecraft tag. It bothers me that this is in that topic ._.

**Comment by dnschneid** [comment]
Well, a lot of people apparently install crouton solely to play Minecraft.  But I can change the tag, if it's really that bothersome to you.

**Comment by FlashDaggerX** [comment]
Well, if that's the reason, that's fine I guess...

**Comment by 1ReimuReimu1** [comment]
I wondered why that tag was there
