### ISSUE TITLE
Im having problems with starting crouton 

### ISSUE THREAD

**Issue by DJTheSage** [dnschneid/crouton#3605]
Ive installed everything correctly i think i used the developer mode i was following this site to install crouton: **https://www.codedonut.com/chromebook/install-crouton-chromebook/**
And like im having problems starting it up i put this command into the local host: sudo startxfce4 or whatever and then this popped up: Enter encryption passphrase for xenial: only problem is i dont have a passphrase what do i do ??? HELP!!!

**Comment by bfayers** [comment]
I guess you created the chroot with the -e option..

**Comment by DennisLfromGA** [comment]
@DJTheSage,

Most likely @bfayers is correct.

If you don't know the chroot's password then you'll have to start over and install the chroot again. 

You can delete the existing chroot using: 
- `sudo delete-chroot xenial`

If you want to use encryption I suggest you first install your chroot without encryption, get everything setup the way you want and then add encryption afterward with a crouton update similar to: 
- `sudo sh ~/Downloads/crouton -n xenial -e -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by DJTheSage** [comment]
Thanks guys its fixed
