### ISSUE TITLE
Newbie can't install ubuntu linux onto Samsung Chromebook *crouton *xenial *xf

### ISSUE THREAD

**Issue by dhambloch** [dnschneid/crouton#3606]
```
chronos@localhost / $ sudo startXfce4
sudo: startXfce4: command not found
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-101-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Jan 8 23:08:25 PST 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=4ffef4e3-d5d9-014c-8913-870f9cb251ca/PARTNROFF=1 hashtree=PARTUUID=4ffef4e3-d5d9-014c-8913-870f9cb251ca/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=5dfc0e062471fc717ee69c072cd2de2109072dc1 salt=a4347e1553b1a02b9bbaa9246374e08325dd29be09820ebd10525225453a5ef9" noinitrd vt.global_cursor_default=0 kern_guid=4ffef4e3-d5d9-014c-8913-870f9cb251ca  
Build Date: 24 November 2017  09:45:24AM
xorg-server 2:1.19.5-0ubuntu2~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jan 12 01:01:16 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1515718876.563506 sender=:1.13 -> destination=:1.44 serial=1071 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1515718877.629928 sender=:1.13 -> destination=:1.46 serial=1073 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

Hi, I'm new to Linux and new to github, but was hoping someone from the community could help me with this problem I'm having trying to install ubuntu on an old Samsung Chrome book (Snow: Daisy - CPU: Samsung Exynos 5 Dual (5250) (Cortex A15; 1.7GHz dual core cpu). GPU: ARM Mali-T604 (Quad Core). I have tried various crouton installs but always fail at the 'sudo startXfce4' command? Any advice would be greatly appreciated and/or a pointer in the right direction. thanks guys.

**Comment by gabedj2** [comment]
Same problem happening to me, but it seems like nothing / nobody is helping other with this problem.

**Comment by dhambloch** [comment]
:( sorry to hear it. I've managed to tap up someone here at work who is knowledgeable in Linux so will see if they can help and share what i learn.

**Comment by gabedj2** [comment]
that would be great. i tried to get windows on this chromebook but unfortunately its not 64 bit. i mainly want linux just to jailbreak my phone :D ..

**Comment by Morantz** [comment]
Just tried to install this myself.  I consider myself an average Linux user (been using Ubuntu for alot of years...)

I am getting this same error.  So I don't think it is something you did wrong.

I am installing on an old Samsung chromebook also.

**Comment by gabedj2** [comment]
I doubt its something we did wrong nor our chromebooks. Im using samsung chromebook 2 (winky) but other users with other chromebooks do seem to have the same problem

**Comment by DennisLfromGA** [comment]
**All**,

Please show us the output of: `sudo edit-chroot -all`

-**DennisLfromGA**

**Comment by gabedj2** [comment]
`sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:28:54 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`

**Comment by Morantz** [comment]
After no real assistance with this, I followed directions at https://calvin.me/arch-linux-samsung-arm-chromebook/ and just replaced ChromeOS completely.  Arch Linux for ARM isn't my prefered linux distro (I LIKE apt-get....) but it does install and work. 

Linux is a better fit for me than ChromeOS.

**Comment by dhambloch** [comment]
Thanks for the useful link, I'll give this a go too and hope it works. I have no prior linux experience apart from wrestling with this issue and I guess necessity is the engine of creation, so what better way to learn than trying to solve this problem.

I'll let you know how I get on.

**Comment by Poochyena** [comment]
Hey-

I had this problem on my machine too. I'm pretty sure most of the problem stems from having an arm processor, but I don't know much more than that. Thanks for that resource, Morantz!

**Comment by pogo555** [comment]
I'm not so sure about the arm processor thing. I had until recently run trusty in a crouton. I am currently having trouble reinstalling it after corrupting the SD card it was on, and wondered if xenial had a problem with the arm processor, but trusty definitely works.

**Comment by dhambloch** [comment]
Hey guys, thanks for helpful advice and resources/links.

I tried trusty the first time and when that failed I tried xenial, which
also failed. I suspect it is to do with the arm chip. Also my machine has
lost its OS now after all this flipping between developer mode, so won't
boot now, so have to start from new. Lol

Best way to learn linux I guess?



Regards,

Dieter

**Comment by DennisLfromGA** [comment]
Seems this issue has been around for quite a while now and is related to video-armsoc drivers.

Take a look at this comment for a little more info.: https://github.com/dnschneid/crouton/issues/3611

For a couple of workarounds, see this comment: https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813
Note that in Solution 1 above you may have to substitute 'startxfce4' with your start script.

*Hope this helps,*
-**DennisLfromGA**
