### ISSUE TITLE
sudo sh -e ~/Downloads/crouton -t gnome

### ISSUE THREAD

**Issue by OomyGoomy** [dnschneid/crouton#3607]
```
Please paste the output of the following command here: sh: Can't open /home/chronos/user/Downloads/crouton
```

#### If known, describe the steps to reproduce the issue:I did shell then i typed 
sudo sh -e ~/Downloads/crouton -t gnome and entered it and it still says sh: Can't open /home/chronos/user/Downloads/crouton

**Comment by scolphoy** [comment]
It looks like the script is not downloaded to that location and so sh can't open it
Try running "wget https://goo.gl/fd3zc  -o ~/Downloads/crouton" first.

**Comment by DennisLfromGA** [comment]
'[wget](https://bugs.chromium.org/p/chromium/issues/detail?id=781538)' has been deprecated so we use `curl` now instead. 

Try running: `curl -# -L -o ~/Downloads/crouton https://goo.gl/fd3zc`
Or just click on [https://goo.gl/fd3zc](https://goo.gl/fd3zc) and save it to ~/Downloads.

*Hope this helps,*
-**DennisLfromGA**

**Comment by OomyGoomy** [comment]
that did nothing but thanks. I am quite a noob im only 13 so yeah.

**Comment by OomyGoomy** [comment]
it ended up saying 
/home/chronos/user/Downloads/crouton: 1: --2018-01-17: not found
/home/chronos/user/Downloads/crouton: 2: Resolving: not found
/home/chronos/user/Downloads/crouton: 3: :443...: not found
/home/chronos/user/Downloads/crouton: 3: 172.217.6.78: not found
/home/chronos/user/Downloads/crouton: 3: Connecting: not found
/home/chronos/user/Downloads/crouton: 4: HTTP: not found
/home/chronos/user/Downloads/crouton: 5: Location:: not found
/home/chronos/user/Downloads/crouton: 6: --2018-01-17: not found
/home/chronos/user/Downloads/crouton: 7: Resolving: not found
/home/chronos/user/Downloads/crouton: 8: :443...: not found
/home/chronos/user/Downloads/crouton: 8: 192.30.255.112: not found
/home/chronos/user/Downloads/crouton: 8: Connecting: not found
/home/chronos/user/Downloads/crouton: 9: HTTP: not found
/home/chronos/user/Downloads/crouton: 10: Location:: not found
/home/chronos/user/Downloads/crouton: 11: --2018-01-17: not found
/home/chronos/user/Downloads/crouton: 12: Resolving: not found
/home/chronos/user/Downloads/crouton: 13: :443...: not found
/home/chronos/user/Downloads/crouton: 13: 151.101.40.133: not found
/home/chronos/user/Downloads/crouton: 13: Connecting: not found
/home/chronos/user/Downloads/crouton: 14: HTTP: not found
/home/chronos/user/Downloads/crouton: 15: Syntax error: "(" unexpected

**Comment by DennisLfromGA** [comment]
@OomyGoomy,

I'm not endorsing it per se but erhaps this guide will help:
- [Install Apps on Your Chromebook With Ubuntu Linux](https://chromeunboxed.com/install-native-apps-on-your-chromebook-with-ubuntu-linux/)

*Hope this helps,*
-**DennisLfromGA**

**Comment by OomyGoomy** [comment]
I tried it. It had the same result as before.

**Comment by DennisLfromGA** [comment]
@OomyGoomy,

Hmmm, works for me, you must be doing something wrong...
Please read the instructions *and* watch the video, it's all very helpful.

-**DennisLfromGA**

**Comment by EnderNightLord-ChromeBook** [comment]
Hi this happend to me so these are the instructions...

1. Delete the file 
2. Download again

if still not working try this

1. press [rename file]
2. <-- backspace
3. type in crouton again 
4. press [ <-- enter ]
Now try :)

**Comment by OomyGoomy** [comment]
It downloaded then when i did sudo startgnome it turns up with
Entering /mnt/stateful_partition/crouton/chroots/xenial...
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
**All**,

Please follow this guide: [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisLfromGA**

**Comment by OomyGoomy** [comment]
its still saying the same thing when i type:
sudo startgnome

**Comment by DennisLfromGA** [comment]
@OomyGoomy,

If the article & video I linked above and the crouton troubleshooting steps don't work then I'm afraid it's out of my depth, I'm just a crouton user like you, sorry.

-**DennisLfromGA**

**Comment by OomyGoomy** [comment]
k thanks anyway you were a really big help and ive started to teach and show my friends how to get linux on there chromebook too.
