### ISSUE TITLE
All I want to do is change the default place where ChromeOS puts removeable media.

### ISSUE THREAD

**Issue by binomine** [dnschneid/crouton#3609]
#### Please describe your issue:
When you insert an SD Card into the slot, it puts it /Media/Removable/SD Card 

I have a program, android studio, that doesn't like spaces. All I want to do is place the card in /Media/Removable/SDCard  

That's all I want. 

I've been to Linux forums, Ubuntu Forums, Crouton Forums. No one seems to know. 

I tried using symlinks, but it seems like Android Studio actively fights them. 

How do?

**Comment by divx118** [comment]
@binomine Try to use a bind mount
```
sudo mkdir /Media/Removable/SDCard
sudo mount --bind /Media/Removable/SD\ Card /Media/Removable/SDCard
```
Maybe if android studio it allows, you could try escaping the space with a `\` like I did above to avoid doing any trickery at all.

**Comment by binomine** [comment]
Thank you. I've been at this for a week.

**Comment by DennisLfromGA** [comment]
@binomine,

To add, this feature will be available soon in CrOS using the 'Files' app, it's slated for M64:

- [Right click and rename USB & SD volumes in the left nav](https://bugs.chromium.org/p/chromium/issues/detail?id=274041#c46)

*Hope this helps,*
-**DennisLfromGA**
