### ISSUE TITLE
Can start-chroot but startx or startxfce4 or init cause black screen and reboot

### ISSUE THREAD

**Issue by downshire** [dnschneid/crouton#3610]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
crosh> shell
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: arm64
xmethod: xorg
targets: xfce-desktop
host: version 9901.77.0 (Official Build) stable-channel bob 
kernel: Linux localhost 4.4.79-11654-g7e0f59a105a1 #1 SMP PREEMPT Mon Nov 13 16:30:12 PST 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 
```

#### Please describe your issue:

Asus C101 Flip - ARM

Put it into dev mode
Downloaded script and ran as xfce4
I can start-chroot and use as terminal 

startx
startxfce4
initx

All cause black screen instantly, pause for around 1 minute and then reboot.
Also tried kde install and restore from rescue media

Help!!!



#### If known, describe the steps to reproduce the issue:

**Comment by downshire** [comment]
tried a different target and session. I now get a mouse pointer and 

chronos@localhost / $ sudo startgnome
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
dbus[9478]: Unknown username "geoclue" in message bus configuration file

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-4-arm64 aarch64 Debian
Current Operating System: Linux localhost 4.4.86-11979-g09b49365a3c4 #1 SMP PREEMPT Mon Jan 8 23:09:02 PST 2018 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=0212e17e-4f05-0d4b-b98e-ca92f031122e/PARTNROFF=1 hashtree=PARTUUID=0212e17e-4f05-0d4b-b98e-ca92f031122e/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=aa13817085316a71998632c6500ad5af9f8657f8 salt=ec6d89cc0a1f6151177b7a9a6c49e6b9a6d2170a74fff8348f11803318681414" noinitrd vt.global_cursor_default=0 kern_guid=0212e17e-4f05-0d4b-b98e-ca92f031122e  
Build Date: 16 October 2017  10:37:36AM
xorg-server 2:1.19.5-1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jan 16 21:06:26 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1516136787.273671 sender=:1.11 -> destination=:1.57 serial=296 reply_serial=2
   boolean true
gbm: failed to open any driver (search paths /usr/lib/aarch64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/rockchip_dri.so: cannot open shared object file: No such file or directory
failed to load driver: rockchip
EGL_MESA_drm_image required.
crouton: version 1-20171230152552~master:de1361af
release: kali-rolling
architecture: arm64
xmethod: xorg
targets: gnome-desktop
host: version 10032.86.0 (Official Build) stable-channel bob 
kernel: Linux localhost 4.4.86-11979-g09b49365a3c4 #1 SMP PREEMPT Mon Jan 8 23:09:02 PST 2018 aarch64 GNU/Linux
freon: yes
Terminated
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1516136793.893597 sender=:1.11 -> destination=:1.59 serial=298 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by DennisLfromGA** [comment]
Seems this issue has been around for quite a while now and is related to video-armsoc drivers.

Take a look at this comment for a little more info.: https://github.com/dnschneid/crouton/issues/3611

For a couple of workarounds, see this comment: https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813

*Hope this helps,*
-**DennisLfromGA**
