### ISSUE TITLE
Cannot start linux / run sudo startxfce4..

### ISSUE THREAD

**Issue by gabedj2** [dnschneid/crouton#3611]
I followed every step correctly, unfortunately this is the error I get after doing `sudo startxfce4`...

`Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-101-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:28:54 PST 2017 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=f087c549-d73b-7740-829e-3cda57c258b9/PARTNROFF=1 hashtree=PARTUUID=f087c549-d73b-7740-829e-3cda57c258b9/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=cb0652fe268f3ed387337531c4521f5b4e413293 salt=e317721aeae38191facdc54f87c50a4c2d181fd3041e9a365b7deedab02607bf" noinitrd vt.global_cursor_default=0 kern_guid=f087c549-d73b-7740-829e-3cda57c258b9  
Build Date: 24 November 2017  09:45:24AM
xorg-server 2:1.19.5-0ubuntu2~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jan 16 17:32:05 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1516152725.622391 sender=:1.11 -> destination=:1.79 serial=1925 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1516152726.419518 sender=:1.11 -> destination=:1.81 serial=1927 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

I also then ran `sudo edit-chroot -all` as instructed on a related post and this was the output...
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9901.77.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Nov 13 16:28:54 PST 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

I have no idea how to fix this and it seems like other don't either. No one has helped/responded to this issue on other post, so I just decided to post my issue to bring more awareness to this. If you do know how to fix this please help, thanks!

**This issue is related to #3606**

**Comment by panther001** [comment]
i got this as well here's my log of it:
[sudo startxfce4.txt](https://github.com/dnschneid/crouton/files/1645312/sudo.startxfce4.txt)

and here's the important part of that log:
 Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

i think the issue has something to do with the new version of chrome. that's just a guess tho

**Comment by RyuzakiKK** [comment]
Same error here. I tried Debian buster and sid with no luck.

**Comment by DennisLfromGA** [comment]
**All,**

Yes, it definitely looks related to or a dup of https://github.com/dnschneid/crouton/issues/3606
It think the problem stems from the following error -

> MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.

It appears the necessary drivers/libraries cannot be found.
The Xorg log file noted below *may* provide more details about the error that could be helpful.

> (EE) Please also check the log file at **"/tmp/Xorg.crouton.1.log"** for additional information.

Unfortunately, I don't have a Samsung Chromebook (daisy) or any ARM device to test with.
Let's hope others with a similar device can test this and dig up more details.

*Sorry I couldn't be more help,*
-**DennisLfromGA**

**Comment by RyuzakiKK** [comment]
@DennisLfromGA I don't get the mesa error, but only the `Error org.freedesktop.DBus.Error.UnknownMethod`

I checked my Xorg.crouton.1.log and the only errors are the following:
```
(EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
(EE) Failed to load module "fbdev" (module does not exist, 0)
(EE) Failed to load module "vesa" (module does not exist, 0)
```

**Comment by DennisLfromGA** [comment]
Seems this issue has been around for quite a while now and is related to video-armsoc drivers.

Take a look at this comment for a little more info.: https://github.com/dnschneid/crouton/issues/3611

For a couple of workarounds, see this comment: https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813
Note that in Solution 1 above you may have to substitute 'startxfce4' with your start script.

*Hope this helps,*
-**DennisLfromGA**
