### ISSUE TITLE
when i type in sudo sh ~/Downloads/crouton -e -t xfce it asks for a password?

### ISSUE THREAD

**Issue by fangasour** [dnschneid/crouton#3619]
when i type in sudo sh ~/Downloads/crouton -e -t xfce it asks for a password and i've tried my password and any other one i know for my accounts and it says.
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
Sorry, try again.
Password:

**Comment by DennisLfromGA** [comment]
@fangasour,

> when i type in sudo sh ~/Downloads/crouton -e -t xfce it asks for a password ...

Don't use the '-e' option, it's for encryption and hence, requires the use of a password.

*Hope this helps,*
-**DennisLfromGA**

**Comment by t0rv1c** [comment]
@fangasour I don't think it's got anything to do with -e and if you want to encrypt your chroot, then you should be free to do it. Have you or someone else set up a root password (sudo chromeos-setdevpasswd)?
I'm not sure you can change it if you can't remember it, so you may have to powerwash and start over with the installation of crouton.

**Comment by DennisLfromGA** [comment]
@t0rv1c,

In [`main.sh` (crouton)](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L67) : 
```
    -e          If the chroot is not encrypted, encrypt it.
                If it is encrypted, change the encryption passphrase.
```
Also, when encryption is requested `mount-chroot` will [prompt for an encryption passphrase](https://github.com/dnschneid/crouton/blob/master/host-bin/mount-chroot#L61) and will [invoke `chromeos-setdevpasswd`](https://github.com/dnschneid/crouton/blob/master/host-bin/mount-chroot#L143) if needed. 

And yes, you should be free to encrypt your chroot if that's what you want, no argument there.
A lot of times users will be following guides that specify the '-e' option and fail to mention it's for encryption, hence, the dilemma.

You're also correct that if a valid password can't be provided they'll have to powerwash and start over.

*Hope this helps,*
-**DennisLfromGA**
