### ISSUE TITLE
Packages missing for kali-rolling (gksu has no installation candidate) (probably should be under PIE)

### ISSUE THREAD

**Issue by pcs3rd** [dnschneid/crouton#3621]
I can't paste output of edit-chroot all, I don't have a chroot, it is failing to finish installation with apt-get error out
```
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libdrm-dev libpthread-stubs0-dev
  libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 libx11-dev libxau-dev
  libxcb1-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev
  linux-libc-dev:i386 x11proto-core-dev x11proto-fixes-dev x11proto-input-dev
  x11proto-kb-dev x11proto-xext-dev xorg-sgml-doctools xtrans-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gksu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gksu' has no installation candidate
Failed to complete chroot setup.
Unmounting /media/removable/crouton/chroots/kali-rolling...
```
any 'official' fix, or is there a way to specify to brute through errors and just work with an incomplete chroot. If not, I am going to (kindly) make a feature request.

**Comment by pcs3rd** [comment]
This isn't an answer, but for now, users MAY be able to install kali sana (2.0)and use [THIS PAGE](https://forums.kali.org/showthread.php?32697-How-to-upgrade-to-latest-kali-rolling-2016-1) to at least get up to date where rolling should be (hopefully)

**Comment by hsosa88** [comment]
I have same problem, but when I try to install kali sana get this:
```
WARNING: sana has reached upstream end-of-life.
That means there will be no package updates available.
You also have to specify a mirror to crouton (-m) for installation to proceed.
```

**Comment by pcs3rd** [comment]
Yea, I was going to go from sana and upgrade, but there doesn't seem to be a way to. @dnschneid is there a way to do this? what mirrors are there?

**Comment by pcs3rd** [comment]
yet again another potential temporary solution, instead of installing xfce at time of setup, run 'sudo sh -e ~/Downloads/crouton -r kali-rolling -n kali -t xiwi' and then install xfce

**Comment by ivo-wang** [comment]
Me too                          sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce


Installing target x11...
Installing target gtk-extra...
ar: creating /tmp/crouton.mFAiby/crouton-network-manager.deb
(Reading database ... 21044 files and directories currently installed.)
Preparing to unpack .../crouton-network-manager.deb ...
Unpacking crouton-network-manager (0) over (0) ...
Setting up crouton-network-manager (0) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gksu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gksu' has no installation candidate
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by dnschneid** [comment]
Should be fixed in the latest crouton.
