### ISSUE TITLE
Artful not booting AT ALL

### ISSUE THREAD

**Issue by limegorilla** [dnschneid/crouton#3622]
## FROM "sudo edit-chroot -all"

> name: artful
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/artful...
> crouton: version 1-20171230152552 master:de1361af
> release: artful
> architecture: amd64
> xmethod: xorg
> targets: unity,touch
> host: version 10323.1.0 (Official Build) dev-channel cyan 
> kernel: Linux localhost 3.18.0-16495-g32e8729786d0-dirty #1 SMP PREEMPT Mon Jan 22 17:52:03 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/artful...
> name: buster
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/buster...
> crouton: version 1-20171230152552~master:de1361af
> release: buster
> architecture: amd64
> xmethod: xorg
> targets: xfce
> host: version 10323.1.0 (Official Build) dev-channel cyan 
> kernel: Linux localhost 3.18.0-16495-g32e8729786d0-dirty #1 SMP PREEMPT Mon Jan 22 17:52:03 PST 2018 x86_64 GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/buster...

## ISSUE:

Whenever I try to boot my ubuntu partition (installed today - artful) the screen will go black when I have typed my password in then 30 seconds later, it looks as if it has shut down normally. Included the script below.

## STEPS TO REPRODUCE

> $ sudo start-unity

This returns:

>

>  Password: 
> Entering /mnt/stateful_partition/crouton/chroots/artful...
> 
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> 
> X.Org X Server 1.19.5
> Release Date: 2017-10-12
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.18.0-16495-g32e8729786d0-dirty #1 SMP PREEMPT Mon Jan 22 17:52:03 PST 2018 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=0b007043-1497-8645-9df0-726c18a5c6de/PARTNROFF=1 hashtree=PARTUUID=0b007043-1497-8645-9df0-726c18a5c6de/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=a7fee6d5b2a5da60188716ef477ff0d397480047 salt=34b0e67e59394344bfea9c072156486e3c0129b7587cac8044bf3e0700f1fdc6" noinitrd vt.global_cursor_default=0 kern_guid=0b007043-1497-8645-9df0-726c18a5c6de add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
> Build Date: 15 October 2017  05:51:19PM
> xorg-server 2:1.19.5-0ubuntu2 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.34.0
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jan 26 14:47:56 2018
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> method return time=1516978077.091971 sender=:1.9 -> destination=:1.51 serial=1502 reply_serial=2
>    boolean true
> crouton: version 1-20171230152552~master:de1361af
> release: artful
> architecture: amd64
> xmethod: xorg
> targets: unity,touch
> host: version 10323.1.0 (Official Build) dev-channel cyan 
> kernel: Linux localhost 3.18.0-16495-g32e8729786d0-dirty #1 SMP PREEMPT Mon Jan 22 17:52:03 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Running exit commands...
> /usr/bin/xinit: connection to X server lost
> 
> waiting for X server to shut down Hangup
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> method return time=1516978090.141050 sender=:1.9 -> destination=:1.53 serial=1505 reply_serial=2
>    boolean true
> (II) Server terminated successfully (0). Closing log file.
> 
> Unmounting /mnt/stateful_partition/crouton/chroots/artful...
> Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/artful...
> -chronos@localhost / $ sudo startunity
> Entering /mnt/stateful_partition/crouton/chroots/artful...
> 
> _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
> 
> X.Org X Server 1.19.5
> Release Date: 2017-10-12
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.18.0-16495-g32e8729786d0-dirty #1 SMP PREEMPT Mon Jan 22 17:52:03 PST 2018 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=0b007043-1497-8645-9df0-726c18a5c6de/PARTNROFF=1 hashtree=PARTUUID=0b007043-1497-8645-9df0-726c18a5c6de/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=a7fee6d5b2a5da60188716ef477ff0d397480047 salt=34b0e67e59394344bfea9c072156486e3c0129b7587cac8044bf3e0700f1fdc6" noinitrd vt.global_cursor_default=0 kern_guid=0b007043-1497-8645-9df0-726c18a5c6de add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
> Build Date: 15 October 2017  05:51:19PM
> xorg-server 2:1.19.5-0ubuntu2 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.34.0
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jan 26 14:48:57 2018
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> method return time=1516978138.409575 sender=:1.9 -> destination=:1.55 serial=1531 reply_serial=2
>    boolean true
> crouton: version 1-20171230152552~master:de1361af
> release: artful
> architecture: amd64
> xmethod: xorg
> targets: unity,touch
> host: version 10323.1.0 (Official Build) dev-channel cyan 
> kernel: Linux localhost 3.18.0-16495-g32e8729786d0-dirty #1 SMP PREEMPT Mon Jan 22 17:52:03 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Running exit commands...
> /usr/bin/xinit: connection to X server lost
> 
> waiting for X server to shut down Hangup
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> method return time=1516978148.348785 sender=:1.9 -> destination=:1.57 serial=1535 reply_serial=2
>    boolean true
> (II) Server terminated successfully (0). Closing log file.
> 
> Unmounting /mnt/stateful_partition/crouton/chroots/artful...
> Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/artful...

**Comment by limegorilla** [comment]
I assume it has something to do with the GUI bc I can get into command-line if I enter

> sudo enter chroot

-- FYI I am a complete noob.

**Comment by DennisLfromGA** [comment]
@limegorilla,

Artful isn't supported - yet -

`crouton -r list`
```
Downloading latest crouton installer...
######################################################################## 100.0%
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch buster sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety! zesty* artful* bionic*
```
`Releases marked with ! are upstream end-of-life, and should be avoided.`
**`Releases marked with * are unsupported, `*`but may work with some effort.`***

I guess this is the part where the _**'may work wth some effort'**_ kicks in. ;-)

This part looks very suspicious, to me -
```
method return time=1516978090.141050 sender=:1.9 -> destination=:1.53 serial=1505 reply_serial=2
boolean true
(II) Server terminated successfully (0). Closing log file.
```
I don't know what's causing it though I'm afraid.

One thing you might try is installing the 'xiwi' xmethod and see if unity will launch then.
You can add it to your existing chroot with the following -
- `sudo sh ~/Downloads/crouton -n artful -t xiwi -u`

Then install the '[crouton integraton](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension from the Chrome Web Store.

*Hope this helps,*
-**DennisLfromGA**
