### ISSUE TITLE
issue #3621 (gksu has no install candidate when installing with xfce)

### ISSUE THREAD

**Issue by pcs3rd** [dnschneid/crouton#3623]
```
Please paste the output of the following command here: sudo edit-chroot -
Can't get kali-rolling to start even, nothing to start, chroot doesn't finish set up.
```
(the original issue #3621 )
when trying to install kali-rolling, it gets to installing xfce and manages to choke this out...
```
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libdrm-dev libpthread-stubs0-dev
  libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 libx11-dev libxau-dev
  libxcb1-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev
  linux-libc-dev:i386 x11proto-core-dev x11proto-fixes-dev x11proto-input-dev
  x11proto-kb-dev x11proto-xext-dev xorg-sgml-doctools xtrans-dev
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package gksu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gksu' has no installation candidate
Failed to complete chroot setup.
Unmounting /media/removable/crouton/chroots/kali-rolling...
```
[Exact same thing mentioned on stack exchange](https://unix.stackexchange.com/questions/419199/package-gksu-has-no-installation-candidate-on-chromebook-kali-installation) 3 days ago (as of Friday, January 26). I have a feeling this is more of a bug with how crouton sets up kali than a bug with kali itself. Does anyone know where the setup script is in the chroot? I can't find it.

**Comment by rickybrent** [comment]
I ran into the same issue with buster -- it's [targets/gtkextra](https://github.com/dnschneid/crouton/pull/3624/commits/5d905ebf931e523c135c0d3e082ebb486f8686fb).

Seems like debian's [removed it](https://bugs.debian.org/867236).

**Comment by pcs3rd** [comment]
@rickybrent , is there any quickfix. I really want to install kali. And once the fix is released, Will I have to redownload crouton?

**Comment by rickybrent** [comment]
Sure, I made a pull request for it -- you can get the fixed code from my [fork](https://github.com/rickybrent/crouton/tree/master) and build it in another chroot.

Or this might be quicker for you:
[https://github.com/rickybrent/crouton/releases/download/20180127/crouton](https://github.com/rickybrent/crouton/releases/download/20180127/crouton)

**Comment by pcs3rd** [comment]
OK, does this mean that I can peacefully close this issue?

**Comment by DennisLfromGA** [comment]
@pcs3rd,

Probably not quite yet.
Let's wait until the devs can take a look at @rickybrent's PR first.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pcs3rd** [comment]
@DennisLfromGA ok, thank you. Quick question, when the next release comes out, the only thing I should have to do is run crouton, right?

**Comment by DennisLfromGA** [comment]
@pcs3rd,

Yup, once the PR gets merged all you have to do is update your chroot with crouton's '-u' option.
But if you want to try it now just download @rickybrent's version of [`crouton`](https://github.com/rickybrent/crouton/releases/download/20180127/crouton) he mentioned [above](https://github.com/dnschneid/crouton/issues/3623#issuecomment-360983767).

*Hope this helps,*
-**DennisLfromGA**

**Comment by Snotes** [comment]
I had the same issue installing kali-rolling with gnome-desktop, and @rickybrent's fork worked for me; while I can't gnome started; xfce,xiwi works.

**Comment by x52559** [comment]
Any updates on the "Package 'gksu' has no installation candidate
Failed to complete chroot setup" issue? I encountered the issue today trying to install rolling-kali.

**Comment by brizzbane** [comment]
I'm new to using crouton.  

**_[start irrelevant details]--->_** 
Made one, liked it--it worked! NEAT!, but prefer Debian (never really used Ubuntu--but wanted to see if touch support worked nicely with gnome). 
**_<----[end irrelevant details]_**

Just tried:

`sudo sh ~/Downloads/crouton -r buster -t gnome-desktop,chrome,core,extension,keyboard -n debian`

got error:

> E: Package 'gksu' has no installation candidate


more before:

> Processing triggers for man-db (2.7.6.1-4) ...
> Setting up guile-2.0-libs:amd64 (2.0.13+1-4+b1) ...
> Setting up xbindkeys (1.8.6-1+b1) ...
> Processing triggers for libc-bin (2.26-4) ...
> Installing target x11...
> Installing target gtk-extra...
> ar: creating /tmp/crouton.NEmuEi/crouton-network-manager.deb
> Selecting previously unselected package crouton-network-manager.
> (Reading database ... 21041 files and directories currently installed.)
> Preparing to unpack .../crouton-network-manager.deb ...
> Unpacking crouton-network-manager (0) ...
> Setting up crouton-network-manager (0) ...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
>   libasound2-dev:i386 libc6-dev:i386 libdrm-dev libpthread-stubs0-dev libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 libx11-dev libxau-dev libxcb1-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev
>   linux-libc-dev:i386 x11proto-core-dev x11proto-fixes-dev x11proto-input-dev x11proto-kb-dev x11proto-xext-dev xorg-sgml-doctools xtrans-dev
> Use 'apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package gksu is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
>
> E: Package 'gksu' has no installation candidate
> Failed to complete chroot setup.
> Unmounting /mnt/stateful_partition/crouton/chroots/debian...

**Comment by DennisLfromGA** [comment]
@brannon,

A fix for this issue has been proprosed by @rickybrent, you can wait until his pull request is reviewed and merged or you can look at https://github.com/dnschneid/crouton/issues/3623#issuecomment-360983767 for a workaround.

*Hope this helps,*
-**DennisLfromGA**

**Comment by johanson** [comment]
I had the same problem with Debian Buster because of gtk-extra target. The patch/fork from @rickybrent seems to fix the issue.

**Comment by brizzbane** [comment]
@DennisLfromGA -- did you mean to @ me? ..(Don't see a brannon in this thread).

With issue being still open, I'm guessing it wasn't merged into release? 

Also, since I'm a newb, it looks like crouton that I downloaded doesn't ever need updating, because it is a script that downloads latest--is this correct?

**Comment by DennisLfromGA** [comment]
@brizzbane,

> did you mean to @ me? ..(Don't see a brannon in this thread).

Yup, sorry, my response was directed to you.
When I typed *@br* I hit the <kbd>tab</kbd> key it grabbed the wrong dude, not my fault. ;-)

> With issue being still open, I'm guessing it wasn't merged into release?

Correct, it's not been merged just yet, it's still being reviewed.

> Also, since I'm a newb, it looks like crouton that I downloaded doesn't ever need updating, because it is a script that downloads latest--is this correct?

Correct again, the devs implemented an '[indirect installer](https://goo.gl/UAfW3o)' a while back, here are some comments from the script:
```
# This is an indirect script. The actual installer will be downloaded, cached,
# and run with any parameters provided. Cached installer will be retained for
# 30 minutes unless this downloader is newer than the timestamp of the cache.
# Set CROUTON_BRANCH to change the branch downloaded.
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by Fataly-Insane** [comment]
Yea im getting this error too, hope there will be a fix soon.

**Comment by DennisLfromGA** [comment]
@Fataly-Insane,

For a temporary workaround see: https://github.com/dnschneid/crouton/issues/3623#issuecomment-360983767

*Hope this helps,*
-**DennisLfromGA**

**Comment by brizzbane** [comment]
@rickybrent 's fork worked for me (installing the Debian version w/gnome ..the command I listed above).

Also was happy to see that touch support worked in gnome!  (Without adding to command line...said it wasn't supported when I tried to do that way).

**Comment by dnschneid** [comment]
Merged @rickybrent's fix.
