### ISSUE TITLE
startcli does not start a new VT?

### ISSUE THREAD

**Issue by threefcata** [dnschneid/crouton#3625]
I'm new to this, and as how I understand it, startcli should start a new VT. But it does not seem to be started, all I got is a shell in the crosh window. Anything wrong?

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome,extension,cli-extra
host: version 10032.86.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Mon Jan 8 23:13:53 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@threefcata,

> freon: yes

From what I understand it's not possible anymore with the implementation of Freon.
[`startcli`](https://github.com/dnschneid/crouton/commits/master/host-bin/startcli) instead now just uses [`enter-chroot`](https://github.com/dnschneid/crouton/blob/master/host-bin/enter-chroot) in the same terminal.

*Hope this helps,*
-**DennisLfromGA**

**Comment by threefcata** [comment]
OK, just learned what Freon is. It's a little sad that this cannot be done anymore.
