### ISSUE TITLE
Install script exits if a invalid username is entered

### ISSUE THREAD

**Issue by pcs3rd** [dnschneid/crouton#3626]
Once you get to this part of the installation, if you enter a taken/invalid username, the setup script exits instead of asking for username again.
'''
Please specify a username for the primary user: root
useradd: user 'root' already exists
Failed to complete chroot setup.
Unmounting /media/removable/crouton/chroots/tor...
'''

**Comment by DennisLfromGA** [comment]
@pcs3rd,

> Install script exits if a invalid username is entered

True that.
Enter a username that does not yet exist.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pcs3rd** [comment]
@DennisLfromGA I know root would already be taken, but they must follow this format I beleive

> Usernames must start with a lower case letter or an underscore, followed by lower case letters, digits, >underscores, or dashes. They can end with a dollar sign. In regular expression terms: [a-z_][a-z0-9_-]* >[$]?
>Usernames may only be up to 32 characters long.
So, if someone attempts to make a password with a period in it, the script would fail, instead of going "invalid username, try again"

**Comment by DennisLfromGA** [comment]
@pcs3rd,

>  I know root would already be taken, ...

If that's the case it seems odd that you would try to enter it knowing it was already in use.

> _**Usernames**_ must start with a lower case letter or an underscore, ...

'root' does indeed follow that convention.

> So, if someone attempts to make a _**password**_ with a period in it, ...

It looks like you're getting _**usernames**_ and _**passwords**_ confused to me....

Also, this is Linux behavior and conventions not crouton, perhaps take this discussion up on [Stack Exchange](https://stackexchange.com/) or another  Linux site.

*Hope this helps,*
-**DennisLfromGA**
