### ISSUE TITLE
my crouton doesnt start on ldxe

### ISSUE THREAD

**Issue by alfredo-huerta** [dnschneid/crouton#3627]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

chronos@localhost / $ sudo edit-chroot -all 
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: armhf
xmethod: xorg
targets: lxde
host: version 10176.61.0 (Official Build) beta-channel veyron_jerry 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Thu Jan 25 06:54:39 PST 2018 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

#### Please describe your issue:

 I try to start my lxde  environment with 

sudo enter-chroot startlxde4 
or
sudo enter-chroot startlxde
#### If known, describe the steps to reproduce the issue:

chronos@localhost / $ sudo enter-chroot startlxde4 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
-su: 1: startlxde4: not found
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ sudo enter-chroot startlxde
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Agent pid 32712
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE

(lxsession:32710): Gtk-WARNING **: cannot open display: 
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

any ideas?

**Comment by DennisLfromGA** [comment]
@alfredo-huerta,

Probably shouldn't matter but try just launching it from CrOS and see if you get any more messages that might be useful. You can do that with: `sudo startlxde -n xenial`

*Hope this helps,*
-**DennisLfromGA**

**Comment by alfredo-huerta** [comment]
Thanks a lot. It's working now. However for some reason I am unable to install anaconda or miniconda.

**Comment by DennisLfromGA** [comment]
@alfredo-huerta,

*Great!*

If you haven't used it maybe this guide will help: [Conda Installation](https://conda.io/docs/user-guide/install/index.html)

*Hope this helps,*
-**DennisLfromGA**

**Comment by efundz1** [comment]
hi

I have a similar problem running lxde, after running a chrome update, just keep getting permission denied error - `sudo startlxde -n xenial` or `sudo startlxde`
output -
`name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`

help appreciated, do I need to delete chroot??

Many thanks
Jim

**Comment by DennisLfromGA** [comment]
@efundz1,

Yours is a different problem yet to be resolved, you can track it here:
- Can't run prepare.sh during setup, and can't access file when run separately #3695

*Hope this helps,*
-**DennisLfromGA**
