### ISSUE TITLE
Storage Space

### ISSUE THREAD

**Issue by DeadRoblox** [dnschneid/crouton#3630]
```
chronos@localhost / $ sudo: edit-chroot-all: command not found```

#### Please describe your issue:
It does not have enough storage. I need more and would like to mount google drive as a disk for crouton to use.


#### If known, describe the steps to reproduce the issue:

**Comment by divx118** [comment]
You can't, but you can use sd-card or external usb storage devices.

**Comment by TheMinigun** [comment]
What is one of the best sd cards that you can think of to run crouton as well as other things I put on it? Also how do I mount it as a drive?

**Comment by 16200JT** [comment]
@TheMinigun The bigger the better. I would personally use a USB storage device because then you could get like... a 2 TB storage device. Pretty much unlimited Linux!
