### ISSUE TITLE
startxfce4 is not working

### ISSUE THREAD

**Issue by XJgaming205** [dnschneid/crouton#3631]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
it says command not found
#### Please describe your issue:

it says command not found
#### If known, describe the steps to reproduce the issue:
shell 
sudo startxfce4
command not found

**Comment by XJgaming205** [comment]
why is it not working

**Comment by XJgaming205** [comment]
now it is saying command not found again

**Comment by DennisLfromGA** [comment]
@XJgaming205,

>> Please paste the output of the following command here: sudo edit-chroot -all

>it says command not found

It may not be apparent or visible to some but there is a required space after the `sudo edit-chroot` commands and before the `-all` options.

It should be: `sudo[space]edit-chroot[space]-all` OR `sudo edit-chroot -all`

*Hope this helps,*
-**DennisLfromGA**

**Comment by 16200JT** [comment]
Hi! Looks like you are having trouble running a command. Are you still in developer mode? If so, did you try running the command "shell" before it?

What system are you running, and what are the specs of it?

**Comment by MCJack123** [comment]
Are you sure you have the chroot installed? It seems like you haven't installed any chroot, and that's why it's not working. If you are sure you did, try running `echo $PATH` and look for `/usr/local/bin` in there. If it isn't there, run `export PATH=$PATH:/usr/local/bin` and try again.
