### ISSUE TITLE
Linux install not working 

### ISSUE THREAD

**Issue by soccersuperb57** [dnschneid/crouton#3634]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue: Tried using crouton to install Linux got the error: E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/s/sane-backends/libsane_1.0.25+git20150528-1ubuntu2.16.04.1_armhf.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by EazyErwin** [comment]
@soccersuperb57 
Hi!
I think I had the same issue recently. As far as I remember I just ran the same installation command again and it just finished the job. Worked fine afterwards. 
Hope this helps
