### ISSUE TITLE
~/Downloads unavailable; chroot not updateable

### ISSUE THREAD

**Issue by vrav** [dnschneid/crouton#3637]
#### Please paste the output of the following command here: `sudo edit-chroot -a`
```
arch precise

chronos@localhost / $ sudo enter-chroot -n arch croutonversion      
Entering /mnt/stateful_partition/crouton/chroots/arch...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0
chown: invalid user: ‘messagebus:messagebus’
crouton: version git
release: arch
architecture: x86_64
xmethod: xiwi
targets: xiwi,extension,x11
host: version 10323.9.0 (Official Build) dev-channel kip 
Unmounting /mnt/stateful_partition/crouton/chroots/arch...
```

#### Please describe your issue:
I have an archlinux chroot that's a few years old that I created using [chroagh]

(https://github.com/drinkcat/chroagh). 
Recently [this issue (https://github.com/dnschneid/crouton/issues/3517) has appeared; the ~/Downloads folder is empty when logged into the chroot. In the linked issue, it was solved by updating the chroot. Unfortunately with `sudo sh ~/Downloads/crouton -u -n arch -r arch`, the release arch does not belong to any supported distribution. Is there really no way I can update my chroot, because chroagh is abandoned? Does anyone know (for example) an updated fork of chroagh that can be used to update my chroot, or is that not possible? (I saw one, but it has been dead for 2 years as well.) At the moment it feels like I'll have to migrate to a non-arch chroot, which makes me very sad... RIP tiny arch terminal on my chromebook.

Thanks in advance for any help you can offer.

#### If known, describe the steps to reproduce the issue:
Have an old install of arch using chroagh; allow ChromeOS to update over the years.

**Comment by DennisLfromGA** [comment]
@vrav,

Unfortunately, as you have discovered the chroagh project is no longer updated.
You could *very carefully* manually apply the changes in PR #3514 (https://github.com/dnschneid/crouton/pull/3514/files) that addressed some of these issues.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. No response or follow-up (needed) at this time.

-**DennisLfromGA**
