### ISSUE TITLE
Auto Start

### ISSUE THREAD

**Issue by TheMinigun** [dnschneid/crouton#3638]
```
Please paste the output of the following command here: sudo edit-chroot -all
```name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.65.0 (Official Build) beta-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jan 30 17:07:46 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

#### Please describe your issue:
I would like to know how to auto start the OS


#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
@TheMinigun,

> I would like to know how to auto start the OS

By 'OS' I guess you mean your chroot, correct?
If so, there is one way to do it that I know of, maybe more, but it requires making your CrOS rootfs read-writable which can be a bit treacherous and not something to be taken lightly. 
Plus, every time you get an update the rootfs will have to be made read-writable again along with a few other things that need to be re-done.

If you're still interested check out the wiki posted here: [Autostart crouton chroot at ChromeOS startup](https://github.com/dnschneid/crouton/wiki/Autostart-crouton-chroot-at-ChromeOS-startup)

*Hope this helps,*
-**DennisLfromGA**
