### ISSUE TITLE
crouton on SD Card - how to get xiwi running?

### ISSUE THREAD

**Issue by EazyErwin** [dnschneid/crouton#3639]
#### Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost /media/removable/SD Card/bin $ sudo sh edit-chroot -all
name: xenial
encrypted: no
Entering /media/removable/SD Card/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 10032.86.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 4.4.86-11979-g09b49365a3c4 #1 SMP PREEMPT Mon Jan 8 23:14:58 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/SD Card/chroots/xenial...
chronos@localhost /media/removable/SD Card/bin $ 
```
#### Please describe your issue:
Hi guys! 
As the title suggests I want to open my desktop in a window using xiwi. But I could only find guides that explained how to do it post-installation when crouton was installed on the harddrive. I am not really expierienced with the terminal, so I was hoping for someone to help me with the commands. 
Anyway, thanks in advance!

**Comment by DennisLfromGA** [comment]
@EazyErwin,

Thanx for the croutonversion output above, it helps in determining what you'll have to do next to get 'xiwi'.

Since you just have the 'xorg' xmethod installed so far you can upgrade your chroot and add the 'xiwi' xmethod at the same time, here's what to do:

- `sudo sh ~/Downloads/crouton -p "/media/removable/SD Card/ -t xiwi -u"`
- Install the [crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension form the Chrome Web Store [**[link](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)**].

Note that the above will make 'xiwi' the default xmethod.
You can start your desktop with either xmethod now using the '-X' option like:

To start in a window: 
- `sudo "/media/removable/SD Card/bin/startxfce4 -n xenial -c"` 

To start in a fullscreen: 
- `sudo "/media/removable/SD Card/bin/startxfce4 -n xenial -X xiwi-fullscreen"`

To start in a tab: 
- `sudo "/media/removable/SD Card/bin/startxfce4 -n xenial -X xiwi-tab"` (my favorite)

And if you want to use 'xorg' instead, use this -

To start in a fullscreen: 
- `sudo "/media/removable/SD Card/bin/startxfce4 -n xenial -X xorg"`

Note that you can give the full path to the bin directory when launching your scripts like I did above or you can use the '-c' option with the full path to the chroots folder.

Hope this helps,
-DennisL

**Comment by EazyErwin** [comment]
Thank you for the quick reply, yeah this actually helps a lot
Cheers mate!

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by jadoff630** [comment]
I found this post and I am trying to use your method to add xiwi to my chroot, but every time I do it, it just gives me the following info, but won't actually let me install... 

> crouton[options] -t targets
> crouton [options] -f backup_tarball
> crouton [options] -d -f bootstrap_tarball
> 
> Constructs a chroot for running a more standard userspace alongside Chromium OS.
> 
> If run with -f, where the tarball is a backup previously made using edit-chroot,
> the chroot is restored and relevant scripts installed.
> 
> If run with -d, a bootstrap tarball is created to speed up chroot creation in
> the future. You can use bootstrap tarballs generated this way by passing them
> to -f the next time you create a chroot with the same architecture and release.
> 
> crouton must be run as root unless -d is specified AND fakeroot is
> installed AND /tmp is mounted exec and dev.
> 
> It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.
> 
> Options:
>     -a ARCH     The architecture to prepare a new chroot or bootstrap for.
>                 Default: autodetected for the current chroot or system.
>     -b          Restore crouton scripts in PREFIX/bin, as required by the
>                 chroots currently installed in PREFIX/chroots.
>     -d          Downloads the bootstrap tarball but does not prepare the chroot.
>     -e          Encrypt the chroot with ecryptfs using a passphrase.
>                 If specified twice, prompt to change the encryption passphrase.
>     -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
>                 When using an existing tarball, -a and -r are ignored.
>     -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
>                 If unspecified, the keys will be stored in the chroot if doing a
>                 first encryption, or auto-detected on existing chroots.
>     -m MIRROR   Mirror to use for bootstrapping and package installation.
>                 Default depends on the release chosen.
>                 Can only be specified during chroot creation and forced updates
>                 (-u -u). After installation, the mirror can be modified using
>                 the distribution's recommended way.
>     -M MIRROR2  A secondary mirror, often used for security updates.
>                 Can only be specified alongside -m.
>     -n NAME     Name of the chroot. Default is the release name.
>                 Cannot contain any slash (/).
>     -p PREFIX   The root directory in which to install the bin and chroot
>                 subdirectories and data.
>                 Default: /usr/local, with /usr/local/chroots linked to
>                 /mnt/stateful_partition/crouton/chroots.
>     -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
>                 Specify an empty string to remove a proxy when updating.
>     -r RELEASE  Name of the distribution release. Default: xenial,
>                 or auto-detected if upgrading a chroot and -n is specified.
>                 Specify 'help' or 'list' to print out recognized releases.
>     -t TARGETS  Comma-separated list of environment targets to install.
>                 Specify 'help' or 'list' to print out potential targets.
>     -T TARGETFILE  Path to a custom target definition file that gets applied to
>                 the chroot as if it were a target in the crouton bundle.
>     -u          If the chroot exists, runs the preparation step again.
>                 You can use this to install new targets or update old ones.
>                 Passing this parameter twice will force an update even if the
>                 specified release does not match the one already installed.
>     -V          Prints the version of the installer to stdout.
> 
> Be aware that dev mode is inherently insecure, even if you have a strong
> password in your chroot! Anyone can simply switch VTs and gain root access
> unless you've permanently assigned a Chromium OS root password. Encrypted
> chroots require you to set a Chromium OS root password, but are still only as
> secure as the passphrases you assign to them.

**Comment by DennisLfromGA** [comment]
@jadoff630,

Can you show us the whole crouton command-line, we might be able to figure out what's wrong with it then.

The command to add 'xiwi' above was for an external SD Card, if you're using a usb stick or if you've given the external storage 'volume' a name then you'll have to use that.

If your chroot is on internal storage in the default location then the following should work:

- `sudo sh ~/Downloads/crouton -t xiwi -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by jadoff630** [comment]
@DennisLfromGA 

I am using an external device for my chroot. Here are screenshots of my command line. The one thing that isn's shown on here is that before I entered in the code given (sudo sh ~/Downloads/crouton -p "/media/removable/julian/ -t xiwi -u") I used "sudo enter-chroot to mount. 


![screenshot 2018-09-14 at 3 05 43 pm](https://user-images.githubusercontent.com/25085973/45577249-db7a5000-b82f-11e8-9cf6-af4822f050c8.png)
![screenshot 2018-09-14 at 3 05 54 pm](https://user-images.githubusercontent.com/25085973/45577248-db7a5000-b82f-11e8-8ff2-b6c0fe545dcb.png)

**Comment by DennisLfromGA** [comment]
@jadoff630,

> The one thing that isn's shown on here is that before I entered in the code given (sudo sh ~/Downloads/crouton -p "/media/removable/julian/ -t xiwi -u") I used "sudo enter-chroot to mount.

You are attempting to update your xenial chroot inside your xenial chroot while it is running.
The `crouton` command is intended to be run from a CrOS shell session and with the chroot shutdown.
Try it that way and let us know if that helps.

*Hope this helps,*
-**DennisLfromGA**

**Comment by jadoff630** [comment]
when I run the command (sudo sh ~/Downloads/crouton -p "/media/removable/julian/ -t xiwi -u") it still gives me the same message.

**Comment by DennisLfromGA** [comment]
@jadoff630,

That sounds very peculiar, please show us the entire command and output including any errors.
You can paste it in a gist or on paste.bin if it's too much for here.

*Hope this helps,*
-**DennisLfromGA**

**Comment by jadoff630** [comment]
@DennisLfromGA 

Here is the gist. 

<script src="https://gist.github.com/jadoff630/6dca4c78ff7aa8ce768823b19c6cd35c.js"></script>

**Comment by jadoff630** [comment]
Thanks for that. It seems like it installed, but I am having trouble with the commands to start xiwi. I have the chrome addon, but it doesn't seem to work. 

```
(xenial)julian@localhost:~$ sudo /media/removable/julian/bin/startxfce4 -n xenial -X xiwi-tab
[sudo] password for julian: 
sudo: unable to execute /media/removable/julian/bin/startxfce4: Permission denied
Hangup
```

**Comment by jadoff630** [comment]
Actually, 

using startxfce4 does start it full screen (and I can then make it a new window), but the tab command doesn't work.

**Comment by DennisLfromGA** [comment]
@jadoff630,

1) Yay!
2) It's probably mounted as 'noexec' so you'll need to run it with '`sh`' like this:
- `sudo sh /media/removable/julian/bin/startxfce4 -n xenial -X xiwi-tab`

*Hope this helps,*
-**DennisLfromGA**

**Comment by jadoff630** [comment]
Thanks! that worked perfectly!
