### ISSUE TITLE
Debian jessie problems.

### ISSUE THREAD

**Issue by idSoftwareWolf** [dnschneid/crouton#3640]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
Sorry, this was an old error, so I currently don't have the output.
```
```
#### Please describe your issue: 
I tried to install Debian Jessie, when I typed `sudo startxfce4` it gets an XServer error and exits.

#### If known, describe the steps to reproduce the issue: 
Do `sudo startxfce4` On an Acer Chromebook R11 with Debian Jessie.

-----
Can I get some help @dnschneid ... or anyone?

**Comment by DennisLfromGA** [comment]
@idSoftwareWolf,

Please paste the output of the following command here: `sudo edit-chroot -all`
Then we'll know a little more about what we're dealing with.

> Sorry, this was an old error, so I currently don't have the output.

Can you reproduce it and show us or are you no longer getting any error messages?

-**DennisLfromGA**

**Comment by idSoftwareWolf** [comment]
https://github.com/dnschneid/crouton/issues/3711 @DennisLfromGA Follow-up problem...

**Comment by DennisLfromGA** [comment]
@idSoftwareWolf,

Without any error output, it's difficult to say but it might be related to an upstream bug:
- debootstrap: Figure out why debootstrap > 1.0.92~bpo9+1 is broken #3713

@drinkcat, a crouton dev, filed an upstream [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894415) and they're working on that issue so it should get fixed soon.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the debootstrap problem.
You can do a quick test with something like the following: crouton -r xenial -d -f xenial.bs

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....

Please re-open this issue if it's not fixed and give us some more details.

-DennisLfromGA
