### ISSUE TITLE
Issue with an application license ( after reboot ) that relies on host information.

### ISSUE THREAD

**Issue by dawid-s** [dnschneid/crouton#3642]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,unity-desktop
host: version 10032.86.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Jan 8 23:16:08 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
I am having issue with [Pixar's Renderman Non-Commercial](https://renderman.pixar.com/intro) license on Ubuntu using crouton because its issued for a specific host. When I installed it for the first time, it worked fine, but after the reboot of my Chromebook, it complained that the license is not issued for this host. This doesn't happen on a regular Ubuntu installation. Are there host information that change on reboot that don't in regular installation?

#### If known, describe the steps to reproduce the issue:
1. Install [Pixar's Renderman Non-Commercial](https://renderman.pixar.com/intro) ( using this [guide](https://quaintproject.wordpress.com/2015/07/12/installing-renderman-server-on-any-linux-system-debian-or-ubuntu/comment-page-1/) for example ). 
2. Run 'prman --version' this should work fine.
3. Reboot the machine and run the command again, it should complain about the license.

**Comment by DennisLfromGA** [comment]
@dawid-s,

It does sound like an issue with the chroot behavior but I'm not sure how to circumvent it or where to start looking. You might be able to list all the files in the package using `dpkg -L ...` to see if you can find a license file or something similar.

Failing that you may be able to get some answers on the [RenderMan Forums](https://renderman.pixar.com/forum/)

*Hope this helps,*
-**DennisLfromGA**

**Comment by dawid-s** [comment]
Thank you for your answer @DennisLfromGA . I guess I will try to see if I can get a bit more info from Pixar about what is the license relaying on. Perhaps once it's known we could have a place where to start looking for it. The license file is actually visible and installed along side the application in: 
`/opt/pixar/pixar.license` which is an xml file. There I can see a field called HostIdentifier which is a hex code, as far as I can guess generated by some combination of host information.

**Comment by DennisLfromGA** [comment]
@dawid-s,

Thanx, that's progress I think.
I hope Pixar will shed some more light on it.

-**DennisLfromGA**
