### ISSUE TITLE
starting os error when I update chromeos 63 

### ISSUE THREAD

**Issue by logmanCN** [dnschneid/crouton#3643]
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.3
Release Date: 2016-04-04
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-99-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Jan 8 23:08:33 PST 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=73ee81a7-181d-2c47-aaf3-5abec3369946/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none rw 1,0 2539520 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2539520 alg=sha1 root_hexdigest=d94a41e13b86bbb525d8e0350a54f35f4e8d7d0e salt=5df30150858d1bf09c3196aae3e0a6cafc3acee2705eda67189eca839da83cb3" noinitrd vt.global_cursor_default=0 kern_guid=73ee81a7-181d-2c47-aaf3-5abec3369946  
Build Date: 18 May 2016  01:09:49AM
xorg-server 2:1.18.3-1ubuntu2.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Feb  6 21:34:51 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

**Comment by DennisLfromGA** [comment]
@logmanCN,

Seems this issue has been around for quite a while now and is related to video-armsoc drivers.

Take a look at this comment for a little more info.: #3611

For a couple of workarounds, see this comment: https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813
Note that in Solution 1 above you'll have to substitute 'xfce4' with your desktop target.

Hope this helps,
-DennisLfromGA
