### ISSUE TITLE
Night brightness function on ChromeOS let bug screen inside Crouton

### ISSUE THREAD

**Issue by loorenz** [dnschneid/crouton#3644]
```
name: bionic
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,lxde
host: version 10176.65.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-16356-g15a3b7998c84 #1 SMP PREEMPT Tue Jan 30 17:11:41 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Problem:
Running Crouton when "night brightness" function is on, screen inside crouton window crash.

#### How to reproduce:
1) Run Crouton
2) Enable night brightness function on your chromebook

**Comment by DennisLfromGA** [comment]
@loorenz,

I just tried toggling night mode on/off on my xenial lxde desktop on my Pixelbook (Eve) and it worked okay, it looks terrible but it worked. It launched it in a window (-X xiwi), in fullscreen (-X xiwi-fullscreen), and in a tab (-X xiwi-tab). 

I'm not sure if your HP Chromebook 13 G1 would behave any differently when launched in fullscreen or in a tab but it might be worth a try.

*Hope this helps,*
-**DennisLfromGA**

**Comment by loorenz** [comment]
Hey @DennisLfromGA , my bad.
I mean no "crash", but visual bug ---> so i think it's the same of your "it looks terrible but it worked".

**Comment by DennisLfromGA** [comment]
@loorenz,

Yup, it's definitely fugly. ;-) 

-**DennisLfromGA**
