### ISSUE TITLE
Unknown username "geoclue" in message bus configuration file

### ISSUE THREAD

**Issue by nanahpang** [dnschneid/crouton#3646]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
chronos@localhost / $ sudo startunity
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Unknown username "geoclue" in message bus configuration file
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
#### Please describe your issue:

The output is only four lines. I have try many methods to fix it but still failed. Can someone help me with this issue? Thanks a lot

**Comment by DennisLfromGA** [comment]
#### Please paste the output of the following command below: `sudo edit-chroot -all`

**Comment by kipmacsaigoren** [comment]
Im not this person but I've been having the same problem. Here's the output for trying to start the chroot:
`Entering /mnt/stateful_partition/crouton/chroots/this...
Unknown username "geoclue" in message bus configuration file
-su: 1: this: not found
Unmounting /mnt/stateful_partition/crouton/chroots/this...`

and here's the output for what you said:
`name: this
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/this...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.72.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Feb 13 19:31:17 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/this...`

**Comment by Asternitix** [comment]
do you have geoclue-2.0 installed? if not, install it. it'll fix your problem.
