### ISSUE TITLE
Cant use synergy 

### ISSUE THREAD

**Issue by Knufle** [dnschneid/crouton#3648]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:

Hello everybody,
Im running synergy in both my Windows 10 PC and my Chromebook.
In the chromebook Im running Ubuntu 16.04 through Crouton, I have no problem downloading and installing synergy but as soon as I open it, it shows me the message: There was a problem connecting to the background service. I clicked retry several times and also went to the Help page where I was instructed to run the following command: ``sudo systemctl restart synergy`` but as soon as I run it the terminal returns this: ``Running in chroot, ignoring request`` could you please help me to solve this?

#### If known, describe the steps to reproduce the issue:

Install synergy from their website.

Run the command: sudo systemctl restart synergy

**Comment by Knufle** [comment]
Does anyone know how to fix this issue?

**Comment by DennisLfromGA** [comment]
@Knufle,

I don't since i don't use Synergy but you might be able to find some hep here:

- [Synergy 2: Manually restarting services](https://symless.com/forums/topic/4501-synergy-2-manually-restarting-services/)

*Hope this helps,*
-**DennisLfromGA**
