### ISSUE TITLE
sigkill is broken

### ISSUE THREAD

**Issue by Asternitix** [dnschneid/crouton#3650]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: beta
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/beta...
crouton: version 1-20171230152552~master:de1361af
release: stretch
architecture: amd64
xmethod: xorg
targets: gnome,audio,extension
host: version 10176.68.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Feb 2 17:11:57 PST 2018 x86_64 GNU/Linux
freon: yes
#### Please describe your issue:
sigkill keeps going and doesn't stop when exiting the chroot

#### If known, describe the steps to reproduce the issue:
I know I removed some of the gnome- packages, but Im not sure which one caused this.

**Comment by Asternitix** [comment]
gnome-menus/stable,now 3.13.3-9 amd64 [installed]
gnome-online-accounts/stable,now 3.22.5-1 amd64 [installed]
gnome-orca/stable,stable,now 3.22.2-3 all [installed,automatic]
gnome-screensaver/stable,now 3.6.1-7+b2 amd64 [installed]
gnome-session/stable,stable,now 3.22.3-1 all [installed]
gnome-session-bin/stable,now 3.22.3-1 amd64 [installed,automatic]
gnome-session-common/stable,stable,now 3.22.3-1 all [installed,automatic]
gnome-settings-daemon/stable,now 3.22.2-2+deb9u2 amd64 [installed]
gnome-shell/stable,now 3.22.3-3 amd64 [installed]
gnome-shell-common/stable,stable,now 3.22.3-3 all [installed,automatic]
gnome-software/stable,now 3.22.5-1 amd64 [installed]
gnome-software-common/stable,stable,now 3.22.5-1 all [installed,automatic]
gnome-sushi/stable,now 3.21.91-2 amd64 [installed]
gnome-system-monitor/stable,now 3.22.2-1 amd64 [installed]
gnome-terminal/stable,now 3.22.2-1 amd64 [installed]
gnome-terminal-data/stable,stable,now 3.22.2-1 all [installed,automatic]
gnome-themes-standard/stable,now 3.22.2-2 amd64 [installed]
gnome-themes-standard-data/stable,stable,now 3.22.2-2 all [installed,automatic]
gnome-tweak-tool/stable,stable,now 3.22.0-1 all [installed]
gnome-user-guide/stable,stable,now 3.22.0-1 all [installed]
gnome-user-share/stable,now 3.18.3-1+b1 amd64 [installed]

**Comment by Asternitix** [comment]
ill just start from scratch.

**Comment by DennisLfromGA** [comment]
@Asternitix,

Sounds like a plan, please let us know if you still run into this issue or not.

-**DennisLfromGA**

**Comment by Asternitix** [comment]
Ive changed my mind about starting from scratch, can you help fix my problem @DennisLfromGA

**Comment by DennisLfromGA** [comment]
@Asternitix,

Okay, I'll try to repo it on a couple of devices I have and get back to you.

-**DennisLfromGA**

**Comment by Asternitix** [comment]
is there any way to redownload the packages for a target? ive allready tried sudo sh -e ~/Downloads/crouton -n beta -u and it didn't do that.

**Comment by DennisLfromGA** [comment]
@Asternitix,

A crouton update using the '-u' option should do that.
You could specify the target to redownload if you like similar to `-t xfce -u` but I don't think it would do anything differently.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Asternitix** [comment]
if I do sudo sh -e ~/Downloads/crouton -n beta -t gnome-desktop -u it should reinstall all of the gnome packages which should fix the problem that I am having.

**Comment by Asternitix** [comment]
i'll let you know if this fixes it.

**Comment by Asternitix** [comment]
ooh, its doing something different than what it did without specifying a target with -t that should go in the readme or in the wiki.

**Comment by Asternitix** [comment]
yup it didn't reinstall samba-libs previously.

**Comment by Asternitix** [comment]
definitely doing something different this time.

**Comment by Asternitix** [comment]
here's the list of installed gnome-* packages:
gnome-backgrounds/stable,stable,now 3.22.1-1 all [installed]
gnome-bluetooth/stable,now 3.20.1-1 amd64 [installed]
gnome-calculator/stable,now 3.22.3-1 amd64 [installed]
gnome-characters/stable,now 3.22.0-1 amd64 [installed,automatic]
gnome-contacts/stable,now 3.22.1-1+b2 amd64 [installed]
gnome-control-center/stable,now 1:3.22.2-3 amd64 [installed]
gnome-control-center-data/stable,stable,now 1:3.22.2-3 all [installed,automatic]
gnome-core/stable,now 1:3.22+3 amd64 [installed,automatic]
gnome-desktop3-data/stable,stable,now 3.22.2-1 all [installed,automatic]
gnome-disk-utility/stable,now 3.22.1-1 amd64 [installed,automatic]
gnome-font-viewer/stable,now 3.22.0-1+b1 amd64 [installed,automatic]
gnome-icon-theme/stable,stable,now 3.12.0-2 all [installed,automatic]
gnome-keyring/stable,now 3.20.0-3 amd64 [installed]
gnome-logs/stable,now 3.22.1-2 amd64 [installed,automatic]
gnome-menus/stable,now 3.13.3-9 amd64 [installed]
gnome-online-accounts/stable,now 3.22.5-1 amd64 [installed]
gnome-online-miners/stable,now 3.22.0-1 amd64 [installed,automatic]
gnome-orca/stable,stable,now 3.22.2-3 all [installed,automatic]
gnome-screensaver/stable,now 3.6.1-7+b2 amd64 [installed]
gnome-session/stable,stable,now 3.22.3-1 all [installed]
gnome-session-bin/stable,now 3.22.3-1 amd64 [installed,automatic]
gnome-session-common/stable,stable,now 3.22.3-1 all [installed,automatic]
gnome-settings-daemon/stable,now 3.22.2-2+deb9u2 amd64 [installed]
gnome-shell/stable,now 3.22.3-3 amd64 [installed]
gnome-shell-common/stable,stable,now 3.22.3-3 all [installed,automatic]
gnome-shell-extensions/stable,stable,now 3.22.2-1 all [installed,automatic]
gnome-software/stable,now 3.22.5-1 amd64 [installed]
gnome-software-common/stable,stable,now 3.22.5-1 all [installed,automatic]
gnome-sushi/stable,now 3.21.91-2 amd64 [installed]
gnome-system-monitor/stable,now 3.22.2-1 amd64 [installed]
gnome-terminal/stable,now 3.22.2-1 amd64 [installed,automatic]
gnome-terminal-data/stable,stable,now 3.22.2-1 all [installed,automatic]
gnome-themes-standard/stable,now 3.22.2-2 amd64 [installed]
gnome-themes-standard-data/stable,stable,now 3.22.2-2 all [installed,automatic]
gnome-tweak-tool/stable,stable,now 3.22.0-1 all [installed]
gnome-user-guide/stable,stable,now 3.22.0-1 all [installed]
gnome-user-share/stable,now 3.18.3-1+b1 amd64 [installed]

the problem persists after the reinstall.

**Comment by Asternitix** [comment]
in other words, still broken.

**Comment by DennisLfromGA** [comment]
@Asternitix,

Well, crouton updates are not supposed to behave the way you reported.
Here's a snippet from crouton's *usage*:
```
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.

# "Undocumented" flags:
#   -U          Same as -u, but does not reinstall existing targets.
#               Targets specified with -t will be installed, but not recorded
#               for future updates.
```
It specifically says: **You can use this to install new targets or update old ones.**
Only if you (know to) pass it the '-U' option will it skip reinstalling existing targets.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Asternitix** [comment]
oh, interesting.

**Comment by Asternitix** [comment]
should have noticed that but didn't.

**Comment by DennisLfromGA** [comment]
@Asternitix,

> should have noticed that but didn't.

Hence term "*Undocumented" flags*". ;-)

-**DennisLfromGA**

**Comment by Asternitix** [comment]
I was referring to the -u part.

**Comment by Asternitix** [comment]
sigkill keeps going when I exit the chroot. I have to push ^c to stop the loop.

**Comment by DennisLfromGA** [comment]
@Asternitix,

I think I would open another CrOS shell session and enter: `sudo unmount-chroot -pa`
That should show you the processes stopping a chroot from unmounting.
Then we'll have something more to work with I hope.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Asternitix** [comment]
results of sudo unmount-chroot -pa:
20420 su - asternitix

**Comment by DennisLfromGA** [comment]
@Asternitix,

Do you gracefully logoff in the chroot or do you just switch to CrOS and attempt to stop the process with <kbd>ctrl</kbd>-<kbd>c</kbd> ?

I usually always try to logoff in the chroot first just so things shutdown cleanly.

-**DennisLfromGA**

**Comment by Asternitix** [comment]
I use the exit command when I am in the shell and log off when using startgnome or startcinnamon in the chroot.

**Comment by Asternitix** [comment]
how can I check if the chroot is still mounted even though I exited the shell?

**Comment by Asternitix** [comment]
seems like it's not mounted, but not sure.

**Comment by DennisLfromGA** [comment]
@Asternitix,

You could see what's left with: `mount | grep crouton`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Asternitix** [comment]
how do I unmount it without using unmount-chroot?

**Comment by Asternitix** [comment]
it doesn't do it.

**Comment by Asternitix** [comment]
are there logs I could send you?

**Comment by Asternitix** [comment]
odd, after a powercycling, seems like it is fixed. going to double check though.

**Comment by Asternitix** [comment]
yup, fixed by crash, what an odd coincidence. I'll reopen this issue if the problem resurfaces.

**Comment by Asternitix** [comment]
yeah, its back.

**Comment by Asternitix** [comment]
going to powercycle and hope.

**Comment by Asternitix** [comment]
@DennisLfromGA seems like starting cinnamon has something to do with what's causing this problem.
this issue is closed, 'cause I found a temporary fix. any idea what a permanent fix would be like?

**Comment by DennisLfromGA** [comment]
@Asternitix,

There's no longer an official cinnamon target so I guess you installed it in your chroot on your own which is fine but it makes it more difficult to support & troubleshoot when something goes sideways.

You said:
>yeah, it's still mounted. how do I unmount it without using unmount-chroot?

- What mountpoint was it that didn't unmount when you exited?
- Why not use `unmount-chroot`?  It was specifically designed for this purpose.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Asternitix** [comment]
how would I figure out what the mountpoint is?

**Comment by Asternitix** [comment]
the output of mount | grep chroots is:
/dev/sda1 on /run/crouton/mnt/stateful_partition/crouton/chroots/beta type ext4 (rw,noatime,commit=600,data=ordered)

**Comment by Asternitix** [comment]
using unmount-chroot continues the stream of sigkill, even with -f

**Comment by Asternitix** [comment]
that's why I dont use it as a temporary fix for this.

**Comment by Asternitix** [comment]
should I reopen this issue?

**Comment by Asternitix** [comment]
are there logs I can send you?

**Comment by DennisLfromGA** [comment]
@Asternitix,

Try: `sudo unmount-chroot -afky`

*Hope this helps,*
-**DennisLfromGA**

**Comment by b1gw0rm** [comment]
For what it's worth, I have the same problem with a recent crouton setup as @Asternitix when logging off from inside a chroot using either xiwi or xorg option. I'm running Xenial with xfce on an Acer C710. I know he uses the exit command from inside the shell which should work as well.

Here's what I'm seeing when logging off from xfce in chroot and it requires a full power cycle to force an unmount allowing access to the chroot again:

Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...
gpg-agent[13707]: SIGTERM received - shutting down ...
gpg-agent[13707]: gpg-agent (GnuPG) 2.1.11 stopped
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by Asternitix** [comment]
@DennisLfromGA that didn't fix it.

**Comment by DennisLfromGA** [comment]
okay, you got me stumped - but that's easy to do...

**Comment by d2cmath** [comment]
I have the same problem here with Acer C720 + Trusty + LXDE after some recent peppy's updates. As far as I can tell, this happens to different graphical environments (gnome for Asternitix, xfce for b1gw0rm, and lxde for me) regardless of Linux distribution, so the title of the issue may need some update.

In my case, there is no problem with normal chroot: 
> sudo enter-chroot
> exit

then there is no SIGKILL loop. 

However, as soon as I use LXDE: 
> sudo startlxde 

then logging out of LXDE will create an infinite SIGKILL loop. 

The trouble partition for me is: 
/run/crouton/mnt/stateful_partition/crouton/chroots/trusty/run 
according to mount command. Looking up inside the partition, the only difference between the two modes above (enter-chroot vs startlxde) is that there is another folder udisks2/ more (accessible only to root). Anyway, I am not sure if this information is helpful.

To stop the SIGKILL loop properly, I have to unmount the partition manually (in another shell) with:
> sudo umount -l /run/crouton/mnt/stateful_partition/crouton/chroots/trusty/run

that will break the SIGKILL loop, and I can start a next LXDE session without problem (but the next logout will create SIGKILL loop again).

@Asternitix: if you see the loop, you can open another shell and type:
> sudo umount -l /run/crouton/mnt/stateful_partition/crouton/chroots/beta

**Comment by b1gw0rm** [comment]
Thanks @d2cmath 
The following works in my case.
sudo umount -l /run/crouton/mnt/stateful_partition/crouton/chroots/xenial

**Comment by Asternitix** [comment]
sudo umount -l /run/crouton/mnt/stateful_partition/crouton/chroots/beta? what does it do?

**Comment by b1gw0rm** [comment]
If you run that command after you stop the sigkill loop it will allow you to go back into the chroot and not have to power cycle to do so. You can stop the sigkill loop with CTRL+c or by closing the window/tab and opening another command prompt window/tab.

**Comment by mhantsch** [comment]
I am observing the same problem with the SIGKILL loop when I 'exit' from the last shell. It's okay as long as I just entered the chroot, did something like 'ls', then exit. But if I start thunderbird first, then exit from thunderbird, then exit from the shell, SIGKILL loop occurs.

Will try to investigate next time with the tipps I found in this thread and post results.

**Comment by Asternitix** [comment]
has anyone seen this message before?:
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
0% [1 InRelease gpgv 94.3 kB] [Waiting for headers]gpgv: Signature made Wed Apr 11 11:26:01 2018 PDT
gpgv:                using RSA key D21169141CECD440F2EB8DDA9D6D8F6BC857C906
gpgv: Good signature from "Debian Security Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>"
gpgv: Signature made Wed Apr 11 11:26:01 2018 PDT
gpgv:                using RSA key A1BD8E9D78F7FE5C3E65D8AF8B48AD6246925553
gpgv: Good signature from "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>"
/usr/bin/apt-key: 596: /usr/bin/apt-key: cannot create /dev/null: Permission denied

any idea how to get it to dissapear?

**Comment by Asternitix** [comment]
when I hold down Ctrl+Alt+t to enter crosh while the message is on a different terminal window, the line that streams down the screen is: /usr/bin/crosh: line 43: /dev/null: permission denied

**Comment by Asternitix** [comment]
oh, and here's the new chroot info:
name: beta
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/beta...
crouton: version 1-20180329190032~master:d287904a
release: stretch
architecture: amd64
xmethod: xorg
targets: extension,audio,gnome
host: version 10323.67.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 3 11:54:45 PDT 2018 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/beta...

**Comment by Asternitix** [comment]
the error message if git is not sudoed: fatal: open /dev/null or dup failed: Permission denied

**Comment by Asternitix** [comment]
this problem got started my me moving a file to /dev/null to delete it

**Comment by Asternitix** [comment]
going to reset the chroot for the third time this month. Going to back it up after this reset.

**Comment by Asternitix** [comment]
and crouton broke installing the new chroot, marvelous. 😞 well at least an idea for a fix popped into my head.

**Comment by Asternitix** [comment]
yeah that broke it even more, does anyone know how to recreate /dev/null on the host?

**Comment by Asternitix** [comment]
and now I realize why I had a second laptop that I didn't need. /dev/null in chroot problem solved.

**Comment by Asternitix** [comment]
the sigkill problem seems to not happen anymore, will reopen issue if it rears it's ugly head again.

**Comment by Asternitix** [comment]
it's a cinnamon bug, startgnome from outside the chroot doesn't have the problem.

**Comment by d2cmath** [comment]
I've tested different chroots recently, it is still buggy for LXDE on most systems Trusty, Xenial, Stretch, and Sid. My workaround is to move to use XFCE instead ;D, I think the bug may have something todo with how some desktop environments manage the mounting or usb devices.
