### ISSUE TITLE
mount issue special device var/run/shill not found

### ISSUE THREAD

**Issue by sbastable** [dnschneid/crouton#3652]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: core,x11,gtk-extra,xfce
host: version 10032.86.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.86-11979-g09b49365a3c4 #1 SMP PREEMPT Mon Jan 8 23:19:25 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Looks similar to issue #56 - I realise that is a very old thread, but I am having the same issue on my Pixelbook. I am definitely running the latest version of the OS (Version 63.0.3239.140 (Official Build) (64-bit)). Issue is that error occurs on install of xfce using crouton with message /var/run/shill does not exist. xenial then unmounts.

#### If known, describe the steps to reproduce the issue:

I entered dev mode and then immediately downloaded Crouton from https://goo.gl/fd3zc . I then ran the following from terminal

shell
sudo sh ~/Downloads/crouton -t xfce

Install whirred away for a minute or so, but I then received the message

mount: special device /var/run/shill does not exist
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

I have tried other targets with the same result.

Thanks - Steve

**Comment by DennisLfromGA** [comment]
@sbastable,

That is strange, maybe something else is interfering with crouton.
I'd suggest you reboot and try again, if you run into the same issue we'll try to gather more info. to troubleshoot with.

Hope this helps,
-DennisLfromGA

**Comment by sbastable** [comment]
Will do - thanks. I'll give it a powerwash this evening. Seemed odd to me.

**Comment by DennisLfromGA** [comment]
@sbastable,

I'd powerwash as a last resort since it will remove all user accounts & user data, and any chroots you've installed.

*Hope this helps,*
-**DennisLfromGA**

**Comment by sbastable** [comment]
Powerwash seemed to do the trick. I was left with no choice in the end. I don't know why this should have worked, as I had not done anything at all prior to attempting the same last time, but am very pleased it is fixed.

Happily running Ubuntu in a browser tab at native resolution 1500 x 1000. Works brilliantly, looks fantastic, seamless integration with Chromium OS. Crouton is a fantastic project - thank you and excellent work @dnschneid

**Comment by sbastable** [comment]
And thanks @DennisLfromGA  for your advice
