### ISSUE TITLE
Black Screen with Mouse upon entering trusty

### ISSUE THREAD

**Issue by akrzy47** [dnschneid/crouton#3654]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.68.0 (Official Build) stable-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Fri Feb 2 17:09:09 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
I am on a toshiba chromebook 2 2015 (baytrail processor) laptop. With the most recent stable chromeOS update trusty no longer works properly. sudo startunity opens up a black screen with mouse. Xenial works but trusty does not. Any help is appreciated. I have updated the chroot but I'm out of options as to what else I can try to do to resolve the issue.

**Comment by wangbodng** [comment]
Hi,

I got same problem.
toshiba chromebook2, after chromeOS updated, trusty black screen with mouse.
following is my log. 

`Loading extension GLX
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[dix] Could not init font path element /usr/share/fonts/X11/misc, removing from list!
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,core,audio,x11,gtk-extra,unity,keyboard,cli-extra,extension
host: version 10176.68.0 (Official Build) stable-channel gandof 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Fri Feb 2 17:09:09 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Compat map for group 2 redefined
>                   Using new definition
> Warning:          Compat map for group 3 redefined
>                   Using new definition
> Warning:          Compat map for group 4 redefined
>                   Using new definition
Errors from xkbcomp are not fatal to the X server
Cannot open /sys/class/tty/tty0/active: No such file or directory
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist`

**Comment by akrzywosz** [comment]
@wangbodng Let me know if you come across a fix. I have yet to find something that works, aside from running xenial instead of trusty.

**Comment by akrzy47** [comment]
Still haven't been able to resolve the issue; I've tried several different suggestions posted in the past when this problem has occurred for other people. It seems like the only thing that works is booting into xenial, but of course that isn't trusty, which is what I actually need access to ...

Please update me if you do come across a fix that works.

**Comment by DennisLfromGA** [comment]
@akrzy47 & @wangbodng,

- Have you tried toggling the <kbd>fullscreen</kbd> and/or <kbd>switch window</kbd> keys?
- Have you tried switching into and out of your chroot with <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>forward/back</kbd> ?

As a a last resort -
- Have you tried adding the 'xiwi' target and the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension?

Please let us know if any of that works.

----
I have a trusty chroot with gnome-desktop, lxde-desktop, xfce-desktop targets but not the unity-desktop unfortunately. However, they all work very well with both 'xorg' & 'xiwi'.

*Hope this helps,*
-**DennisLfromGA**

**Comment by wangbodng** [comment]
@DennisLfromGA 
thank u.
**Have you tried toggling the fullscreen and/or switch window keys?**
     fullscreen: No;  switch: Yes
**Have you tried switching into and out of your chroot with ctrl+alt+shift+forward/back ?**
     switching in and out, Yes
     link external monitor, close-open lid also been tried. both failed.  

**As a a last resort -
Have you tried adding the 'xiwi' target and the 'crouton integration' extension?**
    xiwi work correctly. i'm using this now. but the short key input of application in ubuntu, will be captured by chrome. it's hard to use.

-WangBodong

**Comment by akrzy47** [comment]
So I did try xiwi earlier and it did not work. I removed and re-added the crouton integration extension, and now xiwi does work. Not the most ideal fix, but it's enough of a work-around for me to do what I need.  Hopefully the actual underlying issue is fixed soon. Thanks!

**Comment by DennisLfromGA** [comment]
I agree, 'xiwi' may not be the most ideal fix but hopefully it'll get you going again until the devs can repo it and get a real fix in place.

I'll add the 'unity' target and see if I run into this issue, I'll let you know.

*Hope this helps,*
-**DennisLfromGA**

**Comment by quybao** [comment]
I have a Dell Chromebook 13 which experienced the same symptom like that of @akrzy47 and @wangbodng. After the laptop was updated with latest chromeos 

Platform
10176.72.0 (Official Build) stable-channel lulu
Firmware
Google_Lulu.6301.136.57
Build Date
Tuesday, February 13, 2018

starting unity (as well as gnome) for a trusty chroot also resulted in black screen.

**Comment by quybao** [comment]
I suspected that this has something to do with the  Intel Xorg driver, so I switched the driver to "modesetting"

- Modify xorg-intel-sna.conf
sudo vi /mnt/stateful_partition/crouton/chroots/trusty/etc/crouton/xorg-intel-sna.conf

- Change  Driver from "intel" to "modesetting"

Section "Device"
   Identifier "Intel Graphics SNA+TearFree"
# Driver     "intel"
   Driver     "modesetting"
   Option     "AccelMethod" "sna"
   Option     "TearFree"    "true"
EndSection

And I was able to start unity in trusty again.  A workaround while waiting for this issue to be looked at and worked on.

**Comment by DennisLfromGA** [comment]
_**All**_,

There is an active PR '[Stop using the intel driver #3500](#3500)' that is still open, not merged yet.  
If you like, you can implement in it's current state following [the crouton author's suggestion](https://github.com/dnschneid/crouton/pull/3500#issuecomment-346539369) shown below: 

> You can give it a shot by updating your chroot with: 
>> `sudo CROUTON_BRANCH=nointeldrv crouton -u -n chrootname`

If you decide to try it please let us know how it goes.

*Hope this helps,*
-**DennisLfromGA**

**Comment by ammaarpatel99** [comment]
when i try to update crouton it stops after a bit and says:
WARNING: The following packages cannot be authenticated!
  libgbm1
E: There are problems and -y was used without --force-yes
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.

ive seen the bit about the -y before.

**Comment by oscady** [comment]
Hello

I've got this problem and have gone through the recommended steps. I've just deleted my last chroot and started a fresh one and I'm still having the error. Below is what it's telling me. Can anyone help me with this?

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Feb 24 13:35:36 PST 2018 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=e4b65bd6-7d6e-ca46-ae25-57c0b8275b4a/PARTNROFF=1 hashtree=PARTUUID=e4b65bd6-7d6e-ca46-ae25-57c0b8275b4a/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=a3fc0fee6a709c3064cd1bb1f91c0a38fb7843e9 salt=f1018bb48aee47d38708f9351bd22b7510787b9304b58ed8d3a067bea83ea68b" noinitrd vt.global_cursor_default=0 kern_guid=e4b65bd6-7d6e-ca46-ae25-57c0b8275b4a add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 13 October 2017  01:59:06PM
xorg-server 2:1.15.1-0ubuntu2.11 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Mar 12 13:43:15 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: amd64
xmethod: xorg
targets: unity-desktop,touch,extension
host: version 10176.76.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Feb 24 13:35:36 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Compat map for group 2 redefined
>                   Using new definition
> Warning:          Compat map for group 3 redefined
>                   Using new definition
> Warning:          Compat map for group 4 redefined
>                   Using new definition
Errors from xkbcomp are not fatal to the X server
Timeout waiting for extension to connect.
Cannot open /sys/class/tty/tty0/active: No such file or directory
croutonwebsocket error: Error: not connected.(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

croutonwebsocket error: EError: not connected.
