### ISSUE TITLE
Can't interact with USB devices

### ISSUE THREAD

**Issue by BearChavez** [dnschneid/crouton#3655]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 10032.86.0 (Official Build) stable-channel banon 
kernel: Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Jan 8 23:20:21 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
When trying to use Cydia Impactor on the default setup, the system refuses to interact with USB devices in the chroot
I found this error:

thunar-volman: Unsupported USB device type "usb".
thunar-volman: Unsupported USB device type "(null)".

#### If known, describe the steps to reproduce the issue:
Unplug then replug the device in, in my case, and iPhone

**Comment by DennisLfromGA** [comment]
@BearChavez,

Does it get mounted and show up in CrOS?

-**DennisLfromGA**

**Comment by ceedveed** [comment]
Have you solved this? I'm having this same issue.
