### ISSUE TITLE
acer chromebook 11, ubuntu new issues

### ISSUE THREAD

**Issue by atr162** [dnschneid/crouton#3657]
```
Please paste the output of the following command here: sudo edit-chroot -all:
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.68.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 4.4.96-12272-g2cbee1af2bec-dirty #1 SMP PREEMPT Fri Feb 2 17:05:19 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
I have used Java on my acer chromebook 11 by booting into Ubuntu with no problems up until this morning.

Typically I will load the Chrome OS terminal, enter:
shell
and then
sudo startunity
and Ubuntu loads, ready for me to enter XTerm and Sublime3 with no hiccups

This morning the Ubuntu desktop loaded but no bottom or top bars, and the usual ctrl + alt + T NOT bringing up XTerm to do any kind of debugging

EDIT: I found this Q/A before coming here:
https://askubuntu.com/questions/17381/unity-doesnt-load-no-launcher-no-dash-appears
but in following the top-voted answer, I am not able to load the terminal as described in step 1 
 
EDIT: phrasing

EDIT: Here is the message after running sudo startunity in the Chrome OS shell:

Entering /mnt/stateful_partition/crouton/chroots/xenial...
Unknown username "geoclue" in message bus configuration file

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.96-12272-g2cbee1af2bec-dirty #1 SMP PREEMPT Fri Feb 2 17:05:19 PST 2018 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=1a35240a-74f0-6d40-8865-2f28c75dde25/PARTNROFF=1 hashtree=PARTUUID=1a35240a-74f0-6d40-8865-2f28c75dde25/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=8c441426f1e4e8df7fffbea357ec1e861ef68688 salt=c94a6c5442fcbbb9ac2431f91950fd2efee44fa72c0ad8c8d908e314cee0d57d" noinitrd vt.global_cursor_default=0 kern_guid=1a35240a-74f0-6d40-8865-2f28c75dde25 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 13 October 2017  01:57:05PM
xorg-server 2:1.18.4-0ubuntu0.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Feb 20 11:59:43 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.68.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 4.4.96-12272-g2cbee1af2bec-dirty #1 SMP PREEMPT Fri Feb 2 17:05:19 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
Kicking xrandr again

EDIT: Spelling, formatting

**Comment by eldarerathis** [comment]
I think I hit this bug as well, and was also unable to get into a terminal with CTRL+ALT+[F Key]. I did find a workaround that allowed me to get into a terminal and ultimately fix Unity, though. If you're situation is the same root cause, then it might be worth a try:

- Launch crosh and run `shell`
- Change to the directory of your chroot (ex: for my xenial install this was `cd /mnt/stateful_partition/crouton/chroots/xenial`)
- Create a desktop shortcut for XTerm in your chroot's home directory: `ln -s usr/bin/xterm home/<username>/Desktop/xterm`
- Launch your chroot normally (`sudo startunity`) and you should get the desktop without a dash, but with a shortcut to XTerm available now
- Launch XTerm, install CCSM, and then launch it and enable the Unity plugin. You can follow the directions in the top AU answer for that (you shouldn't need to `export DISPLAY=:0`, though).

I didn't dig any deeper to try to determine why the Unity plugin was initially disabled after installing the chroot.

**Comment by Hodges3902** [comment]
I am having this same exact issue... I tried the solution above and was able to get the xterm shortcut on my screen but it wouldnt allow me to run the terminal. It said something about usr/bin not existing..

**Comment by Swcbn** [comment]
I saw a website that fixed this on Xenial. I'm not sure if it works yet, haven't tried it yet. But I also have this issue so I will try it when my new Xenial installs. Also, I couldn't get Xterm to come on my Desktop screen, so I skipped it and did everything else. It worked. I just had to do a powerwash now, so I'm reinstalling Xenial. I hope this helps. :)

Here's the website - https://itsfoss.com/how-to-fix-no-unity-no-launcher-no-dash-in-ubuntu-12-10-quick-tip/

**Comment by WTLM2013** [comment]
I am seeing this on revision 11316.66.0 (Official Build) dev-channel peppy. I tested to see if it was happening to just this device by testing it on revision 11151.59.0 (Official Build) beta-channel swanky with it working, so it may be system related (and based off the thread, may be an issue with Acer devices.)

**Comment by Scorpionist** [comment]
I am having the same exact issue on the same model chromebook. I am almost certain this is a model support problem. I have had no luck in finding a fix as there is no real way of opening the terminal since the terminal isnt actually installed when checking what programs can be opened within the chroot. Unless a fix is issued in the next update or you find a way to open the file explorer in root im afraid you won't be using unity on your device unfortunately.

**Comment by Swcbn** [comment]
If you can find a way, and you are willing to, you should do what I did.
I deleted my Unity crosh, and installed xenial on a different DE.
It works for me, with full app support, so if you don't need Unity, you should try converting your desktop environment to something different. It also is just faster on the DE I'm using, which is LXDE.

**Comment by Swcbn** [comment]
Also, this is not Crouton's fault. It is a compatibility issue on Xenail's part, as Chromebooks are not the only systems affected by this.

**Comment by DennisLfromGA** [comment]
According to @Swcbn's post above, the[ itsfoss link](https://itsfoss.com/how-to-fix-no-unity-no-launcher-no-dash-in-ubuntu-12-10-quick-tip/)'s one-liner sollution was:

- `rm -rf .compiz-1`

Instead, I would suggest just renaming it with something like:

- `mv .compiz-1 .compiz-1.bak`

And then see if Unity works again.

*Hope this helps,*
-**DennisLfromGA**
