### ISSUE TITLE
A way to hide Chrome drive partitions?

### ISSUE THREAD

**Issue by Maffyou** [dnschneid/crouton#3658]
First of all - thank you for your work on Crouton. I very much appreciate it.

In the Linux file manager, I can see 11 drive partitions that seem to be mostly to do with ChromeOS. They have names like "ROOT-A", "EFI-SYSTEM", "4.1KB VOLUME" etc...

If I click one of those partitions, I get a message with something like "Failed to mount...".

Can those partitions be hidden?

Many thanks in advance.

**Comment by DennisLfromGA** [comment]
@Maffyou,

> Can those partitions be hidden?

I think that would depend on your desktop target but probably yes, they can be hidden.
In my LXDE Desktop I can choose to show the volumes, see below -

![screenshot](https://user-images.githubusercontent.com/3418772/36458273-056109d2-167c-11e8-8bfa-25aee3e35508.jpg)

You didn't show us your croutonversion so we don't know what desktop you're using but I think you might find something similar to the above in 'Desktop Preferences'.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Maffyou** [comment]
Thank you for the reply. Here's my croutonversion:

crouton: version 1-20170901092920~master:0216f9d1
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce,touch,extension
host: version 10032.86.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Jan 8 23:17:59 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

But I think I failed to ask my question correctly - It's not just the desktop where these "extraneous" partitions exist - it's in the left sidebar in Thunar file explorer.

To be honest I'm not really that bothered by them. There not causing errors or anything - they're just clutter that I would prefer to not be there.

**Comment by DennisLfromGA** [comment]
@Maffyou,

If you hover your mouse over the icons in the left sidebar I'm pretty sure it'll offer an option to dismiss them or something similar.

*Hope this helps,*
-**DennisLfromGA**
