### ISSUE TITLE
Can not connect (I Think) trying to follow https://android.jlelse.eu/developing-android-apps-right-on-your-chromebook-f3a00cb78e0e

### ISSUE THREAD

**Issue by lhshenker** [dnschneid/crouton#3659]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Hi am new to linux and to chrome book ( Lenovo N23 ) so I have run the above command, I just cant work out how to find the output, so can some one help me there please.

Any way I have successfully followed most of the tutorial, I have Installed python it is the next bit when I go back to the Chrome Terminal that I experience a problem, the application just does not want to open 

I get an error saying Error not connected and can not connect to extension trying again ......

this fails and i have still not got an open android studio any suggestions are welcomed but i am a novice please keep it simple

thanks in advance 
lhshenk

**Comment by DennisLfromGA** [comment]
@lhshenker,

##### Please paste the output of the following command below: `sudo edit-chroot -all`

----
What tutorial did you use (link)?

Have you installed the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension?

-**DennisLfromGA**

**Comment by lhshenker** [comment]
Hi, I had but I needed to restart the chrome book, thanks for helping.

**Comment by DennisLfromGA** [comment]
@lhshenker,

Cool, glad you got it going.
And sorry for not noticing the link to the tutorial in your subject - duh!

-**DennisLfromGA**
