### ISSUE TITLE
Note: This isn't an issue, it's a request; Make Xiwi open-sourced, or a standalone application.

### ISSUE THREAD

**Issue by idSoftwareWolf** [dnschneid/crouton#3663]
This goes to @dnschneid , nobody else.

So, if you don't know about Chromebrew, it's a package manager for Chrome OS. It has many GUI applications, all which are just waiting to be shown, but Chrome OS can't handle the request. Xiwi integrates running Linux applications outside Xorg, even letting you run the apps themselves, with no desktop environment. (this is the part we need) So what if we could use the same code, and reuse it to run those applications? It should be just changing a few lines, or if you are busy, just open-source it so we can do this. Come on. Some of us like to keep our Chrome OS disk space. 

- Wolf

**Comment by dnschneid** [comment]
> just open-source it so we can do this

Already done.  Welcome to Github.

**Comment by idSoftwareWolf** [comment]
You have Xiwi open-sourced?
