### ISSUE TITLE
shared directory Downloads not working

### ISSUE THREAD

**Issue by awlnx** [dnschneid/crouton#3664]
##### Please paste the output of the following command here: `sudo edit-chroot -all`
```
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20170901092920~master:0216f9d1
release: stretch
architecture: amd64
xmethod: xorg
targets: xorg,gnome,xfce,extension,xiwi
host: version 10323.39.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-16503-ge33b03ba1f58-dirty #1 SMP PREEMPT Tue Feb 20 22:34:37 PST 2018 x86_64 GNU/Linux
freon: yes
```
#### If known, describe the steps to reproduce the issue:
chroot is on debian buster, not exactly sure when / if it broken
I have tried updating the chroot to buster

**Comment by DennisLfromGA** [comment]
@awlnx,

Are you getting an error similar to the following?

```
Entering /mnt/stateful_partition/crouton/chroots/xenial...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0
```

If so that's part of the problem and it's been fixed. 

You're 'stretch' chroot is about 28 versions behind so most likely you just need to update your chroot.
You can use the following to do it -

- `sudo sh ~/Downloads/crouton -n stretch -u`

[ You said your chroot is on debian buster but the croutonversion displayed above reports 'stretch' so that's what I went with above. ]

*Hope this helps,*
-**DennisLfromGA**

**Comment by awlnx** [comment]
yes! that is an error I am getting, but I did update, it failed because I have updated the chroot internally to buster. I forced it with -uu -n stretch -r buster and it succeeded but still fails.

**Comment by DennisLfromGA** [comment]
@awlnx,

I noticed you said:

> I have tried updating the chroot to buster

Did it succeed without error?

You also said:

>  I did update, it failed because I have updated the chroot internally to buster.

So where is the crouton update failing and what error messages do you see?

----
'buster' is supported in crouton now so it might be easier to install it anew.

*Hope this helps,*
-**DennisLfromGA**

**Comment by awlnx** [comment]
updating  does nothing, it succeeds with no error but also fails to update the release. I will have to try reinstalling. I have to ask though, why is "buster" supported but not testing, given the rolling release nature of debian testing it might be better to use the constant name testing instead of the transitional name buster

**Comment by DennisLfromGA** [comment]
Closing. No response or follow-up (needed) at this time.

-**DennisLfromGA**
