### ISSUE TITLE
Extension connection issue when crosh is in the foreground

### ISSUE THREAD

**Issue by notgne2** [dnschneid/crouton#3666]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce,x11,cli-extra,core,keyboard,touch
host: version 10032.86.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Jan 8 23:24:35 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
`startxiwi` logs

```
Error: not connected.
Cannot connect to extension, retrying...
```

Before timing out and quitting, whenever the browser window is not the active window. Activating the browser window right after running the command will result in instant connection.

#### If known, describe the steps to reproduce the issue:
run `startxiwi` from a terminal window, ran separately from the main browser window.

**Comment by notgne2** [comment]
Actually, I just tested this with crosh open in a tab, and interestingly it won't work when crosh is the active tab.

**Comment by notgne2** [comment]
Interestingly, theres no issue on my wife's laptop, just mine, here's some more info?

`Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Jan 8 23:24:35 PST 2018 x86_64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz GenuineIntel GNU/Linux`

It's an ASUS C302C, on Chrome OS stable channel.

**Comment by bupont** [comment]
Experiencing the same on my Pixelbook stable channel.
