### ISSUE TITLE
Downloads directory ownership is lost

### ISSUE THREAD

**Issue by rhodotherm** [dnschneid/crouton#3670]
```
name: trusty
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
When I open trusty, the "Downloads" folder is not accessible, Linux says I am not the owner. This is the only folder I can use as a bridge between Chrome-OS files and Linux's, plus is where all the info I download is stored (I work with biological data bases). Could this be related to a new update of Chrome-OS?.
Two days ago my Chromebook flagged an alert to restart the system so it can be updated. Last time the Chome-OS was updated I remember there were some twitches to be fix with Crouton to get Linux fully operative again (I don't remember exactly what was the issue but I found the solution here in those threads). Help, anyone?

When I open trusty I get some errors: the output is large. I don't know where to start with.

Entering /mnt/stateful_partition/crouton/chroots/trusty...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri Feb 2 17:11:57 PST 2018 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=22cd8242-8cce-874d-9542-91939ecfa17d/PARTNROFF=1 hashtree=PARTUUID=22cd8242-8cce-874d-9542-91939ecfa17d/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=98cd89a8e2cc0400f8d40ed7fd5924d5bde22779 salt=fb0bb7c6fc2e5ec6fb19f3f767ec47a66c83ab49eab697895071e1d7b113011d" noinitrd vt.global_cursor_default=0 kern_guid=22cd8242-8cce-874d-9542-91939ecfa17d add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 13 October 2017  01:59:06PM
xorg-server 2:1.15.1-0ubuntu2.11 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Mar  2 20:42:54 2018
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20171109145451~master:35a16889
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,extension,audio,keyboard,touch,xorg,xiwi,unity
host: version 10176.68.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Feb 2 17:11:57 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Cannot open /sys/class/tty/tty0/active: No such file or directory
Error: target STRING not available
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

THANKS!

**Comment by DennisLfromGA** [comment]
@rhodotherm,

The error:
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" 

was first reported in Aug. 2017 here: Can't Initialize ubuntu with crouton #3375
This issue was fixed in Sep. 2017 here: Use updated dbus method calls #3378

Since your croutonversion of Nov. 2017 looks to be newer: [Update contributors, I guess...](https://github.com/dnschneid/crouton/commit/35a16889055b22dfe3286541f1693587537283da)
it seems strange that you're still getting that error.

However, since your chroot is a bit out of date it probably wouldn't hurt to update it and then see if you're still having this issue.

*Hope this helps,*
-**DennisLfromGA**

**Comment by rhodotherm** [comment]
Thans Dennis!
I'm stepping into a new problem now; the command
sudo sh ~/Downloads/crouton -u -n trusty 
does not find crouton. 
I tried 
chronos@localhost / $ sudo sh ~/mnt/stateful_partition/crouton -u -n trusty
but again it does nothing (sh: 0: Can't open /home/chronos/user/mnt/stateful_partition/crouton)

**Comment by rhodotherm** [comment]
I think I solved it with another of your [entries](https://github.com/dnschneid/crouton/issues/2844)
Thanks a lot Dennis!

**Comment by rhodotherm** [comment]
Solved!

**Comment by DennisLfromGA** [comment]
@rhodotherm,

## _Awesome!_

-**DennisLfromGA**

**Comment by jywarren** [comment]
I also saw:

```
chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/xenial...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0
```

And noticed that the `Downloads` folder is no longer unified. I tried 

`sudo sh ~/Downloads/crouton -u -n trusty`

And also saw, as @rhodotherm did, 

```
sh: 0: Can't open /home/chronos/user/Downloads/crouton
```

Just chiming in, i'm now following https://github.com/dnschneid/crouton/issues/2844

**Comment by DennisLfromGA** [comment]
@jywarren,

*Please* read: https://github.com/dnschneid/crouton/issues/2844#issuecomment-255253154

*Hope this helps,*
-**DennisLfromGA**

**Comment by jywarren** [comment]
Many thanks, I figured it out with your help!
