### ISSUE TITLE
crouton no longer works with chrome os 64 update

### ISSUE THREAD

**Issue by ammaarpatel99** [dnschneid/crouton#3671]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,unity,touch
host: version 10176.73.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.96-12273-gff55511fceb9-dirty #1 SMP PREEMPT Wed Feb 14 09:31:55 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### Please describe your issue: 
crouton won't work after chrome os 64 update. doing sudo startunity mounts it, turns the screen black and then unmounts it.  this was on the pixelbook

#### If known, describe the steps to reproduce the issue: 
just entered shell in the terminal and then sudo startunity

**Comment by DennisLfromGA** [comment]
@ammaarpatel99,

This seems to be a dup of: Black Screen with Mouse upon entering trusty #3654

I'll close this issue and we can track it on #3654 

-**DennisLfromGA**
