### ISSUE TITLE
Error fetching CRAS Failed to complete chroot setup.

### ISSUE THREAD

**Issue by Nathan903** [dnschneid/crouton#3672]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
sudo sh -e ~/Downloads/crouton -u -r stretch -t x11,core,gtk-extra,extension,gnome,gnome-desktop,cli-extra
```

#### Please describe your issue:
I did switch to developer mode on a levono chromebook
I recently deleted ubuntu 16.04 on my chromebook and tried to install debian stretch several times
the installer always failed even if i didn't put the target "audio"
I have also tried installing stretch and xenial with "core" only  but the same error

The last code that come out is this
```
sudo is already the newest version (1.8.19p1-2.1).
wget is already the newest version (1.18-5+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Syncing timezone...
Installing target audio...
Fetching CRAS (branch d67885b57e9311c19be24acff1f69a20ebeae0a7)...
--2018-03-04 22:01:44--  https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive/d67885b57e9311c19be24acff1f69a
20ebeae0a7.tar.gz
Resolving chromium.googlesource.com (chromium.googlesource.com)... 108.177.125.82, 2404:6800:4008:c01::52
Connecting to chromium.googlesource.com (chromium.googlesource.com)|108.177.125.82|:443... failed: Connection timed out.
Connecting to chromium.googlesource.com (chromium.googlesource.com)|2404:6800:4008:c01::52|:443... failed: Network is unreacha
ble.
Error fetching CRAS
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
```

#### If known, describe the steps to reproduce the issue:

**Comment by Nathan903** [comment]
I just ping google.com and it works fine
![screenshot 2018-03-04 at 10 05 12 pm](https://user-images.githubusercontent.com/30803215/36946493-951535aa-1ff8-11e8-885f-872fd3d9c104.png)

**Comment by DennisLfromGA** [comment]
@Nathan903,

> Connecting to chromium.googlesource.com (chromium.googlesource.com)|108.177.125.82|:443... failed: Connection timed out.
Connecting to chromium.googlesource.com (chromium.googlesource.com)|2404:6800:4008:c01::52|:443... failed: Network is unreacha
ble.
Error fetching CRAS

Those may be due to transient network errors or proxy problems.
I think in most cases just retrying at another time will get past that issue.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Nathan903** [comment]
@DennisLfromGA 
I have retried several times and i believe it is not a network problem
i dont understand why even if I only install with core and nothing else, it will still install "target audio"

**Comment by DennisLfromGA** [comment]
@Nathan903,

- Are you using a proxy?
- Could it be the country you're in that's blocking it?

> i dont understand why even if I only install with core and nothing else, it will still install "target audio"

I don't believe the `core` target alone should pull in `audio`.

From the targets you specified below -

> `-t x11,core,gtk-extra,extension,gnome,gnome-desktop,cli-extra`

It looks like `audio` is first getting pulled in from your `x11` target, however, `gtk-extra`, `extension`, `gnome`, &  `gnome-desktop` targets pull in `x11` so it's unavoidable with your selection.
The `x11` target, in turn, requires the `xorg` xmethod but both `xorg` and `xiwi` pull in the `audio` target.

I think if you give up your gui desktop and other extras and just use `enter-chroot` for a shell session then you could avoid the `audio` target with the following:

`sudo sh ~/Downloads/crouton -r stretch -t cli-extra`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Nathan903** [comment]
@DennisLfromGA 
yes, I'm using vypr vpn which is an android app that i install on my chromebook since i live in China
Should I use the -P ? Since the vypr app already configure the network, and I ping www.google.com in terminal and everything is fine

**Comment by DennisLfromGA** [comment]
@Nathan903,

That may be part of the problem then.
Have you flipped the CrOS flag at **[chrome://flags/#arc-vpn](chrome://flags/#arc-vpn)**
> Enable ARC VPN integration
Allow Android VPN clients to tunnel Chrome traffic. – Chrome OS

That might help.

Also, take a look at these issues for possible soluitons:
- Installing Ubuntu in China #902
- Installing behind the Great Firewall of China, proxy problem #1150

*Hope this helps,*
-**DennisLfromGA**

**Comment by Nathan903** [comment]
@DennisLfromGA 
I tried again today with another laptop sharing wifi with vpn and it worked, so it is the tunneling problem with dns

thanks alot for helping

**Comment by DennisLfromGA** [comment]
@Nathan903,

Glad you found a solution, I don't know if I helped a lot but maybe nudged in the right direction.

-**DennisLfromGA**
