### ISSUE TITLE
Chroot Password Failure

### ISSUE THREAD

**Issue by Ahimele** [dnschneid/crouton#3674]
I have a samsung chromebook, and I've gone through the steps to install crouton.The issue is that even though I've successfully installed "Ubuntu" on the chromebook. It will not allow me to login. I keep getting the same "incorrect password", even though it did not allow me to set one during the installation process. I understand that evidently when you type your password it wont show up as your typing it. But even as I was typing, and pressing enter, it was not setting the password, and said I could setup a password later. I've tried to re-install it again, but it;s already on the system, and I'm sure I'll just have the same issue. How can I get my password set? 

I've even tried to correct the issue by entering the chromeos-setdevpasswd, but that command is not recognized.

**Comment by DennisLfromGA** [comment]
@Ahimele@Ahimele,

> The issue is that even though I've successfully installed "Ubuntu" on the chromebook. It will not allow me to login. I keep getting the same "incorrect password", even though it did not allow me to set one during the installation process.

As long as you haven't enabled 'Debugging Features' and haven't enabled encryption in your chroot it should be an easy fix. Just log in to your chroot as 'root' and then set a password for the `username` you specified when you installed it.

Something like the following should work:

- `sudo enter-chroot -u root`
- `passwd [username]` (enter a password of your choice twice when prompted, it will not be displayed)
- `exit`

Then you should be able to launch your desktop with your `start*` script or use `enter-chroot`.

Hope this helps,
-DennisLfromGA

**Comment by Ahimele** [comment]
I powerwashed my chromebook again to start over, and take note on every step I was doing. I did not enable debugging at all. And I downloaded the crouton installation. A new problem has now popped up. When in the developer shell as I am starting the process, the system will not recognize the command "sudo". It gives the error message "ERROR: unknown command: sudo ." I can't even move forward with the process if it can't even recognize code.

**Comment by DennisLfromGA** [comment]
@Ahimele,

You may know this but I'll point out the steps just in case and for others:

1. Sign-in using your gmail account.
2. Press <kbd>**ctrl**</kbd>+<kbd>**alt**</kbd>+<kbd>**t**</kbd>  to get a 'crosh session'
3. At the 'crosh >' prompt enter **`shell`** to get a bash shell session
4. At the shell prompt '$ ' enter **`sudo enter-chroot -u root`**
5. Enter **`passwd [username]`** (enter a password of your choice twice when prompted, it will not be displayed)
6. Enter **`exit`**

*Hope this helps,*
-**DennisLfromGA**

**Comment by Ahimele** [comment]
I appreciate you getting back to me. That did not work out for me either. This was the message I received. 
chronos@localhost / $ passwd [username]
passwd: user '[username]' does not exist

**Comment by DennisLfromGA** [comment]
@Ahimele,

> chronos@localhost / $ passwd [username]
passwd: user '[username]' does not exist

Note above that you are in a **_CrOS shell session_** and **NOT** in the chroot so it of course wouldn't work.
You'll need to follow the steps I outlined above **in that order**.

*Hope this helps,*
-**DennisLfromGA**
