### ISSUE TITLE
Linux localhost 3.18.0-16505-g3f26a8efd173-dirty

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3675]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome,chrome-beta
host: version 10323.46.0 (Official Build) beta-channel edgar 
kernel: Linux localhost 3.18.0-16505-g3f26a8efd173-dirty #1 SMP PREEMPT Tue Feb 27 22:15:53 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
#### Please describe your issue:

dev/root lib/modules is at 92% intermittent crashes
wind up a few processes

I appear to have 2 dirty kernels installed? have updated in crosh and in ubuntu to no effect - should i delete the old kernel?

**Comment by DennisLfromGA** [comment]
@Stockton-pr,

No need, I don't believe the 'dirty' kernel(s) are directly related to the crashes.

Take a look at this thread for somewhat of an explanaton: [kernel version is -dirty](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/zxOa0OLWFkw)

*Hope this helps,*
-**DennisLfromGA**
