### ISSUE TITLE
Screen starts blinking when casting

### ISSUE THREAD

**Issue by ChristopherKing42** [dnschneid/crouton#3677]
```
sudo enter-chroot xiwi -T startxfce4
```

#### Please describe your issue:
When using google cast, the screen starts blinking (the xiwi window only). Interestingly, it only appears on the chromebook, not the device I am casting to.

#### If known, describe the steps to reproduce the issue:
Run `sudo enter-chroot xiwi -T startxfce4`
Cast to a smart TV

**Comment by ChristopherKing42** [comment]
It also happens if you use `sudo enter-chroot xiwi -T startxfce4` instead.

**Comment by ralkia14** [comment]
I'm fairly certain the newest ChromeOS update broke a lot of things in Crouton. I'm using Ubuntu (don't remember which build) and when I start it up, the screen blinks and glitches and HUD elements don't appear, rendering the partition unusable. I haven't tried reinstalling Crouton yet, but I'm going to later.

**Comment by ChristopherKing42** [comment]
I am just using xfce. Luckily, it only blinks while casting.

**Comment by ChristopherKing42** [comment]
It actually seems to happen even when casting only single applications with xiwi.
