### ISSUE TITLE
Crouton not working on newest ChromeOS update

### ISSUE THREAD

**Issue by ralkia14** [dnschneid/crouton#3678]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
Loading extra module: /usr/share/crosh/dev.d/50-crosh.sh
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

If you want to customize the look/behavior, you can use the options page.
Load it by using the Ctrl+Shift+P keyboard shortcut.

crosh> shell
chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/xenial...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0
Unknown username "geoclue" in message bus configuration file

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
```

#### Please describe your issue:
Don't know if this is all that is needed to be pasted, but it wouldn't copy any more text. A friend told me that the newest ChromeOS update has problems running Crouton, but I didn't see any official word about it on here or the Crouton website so I just wanted to ask. Whenever I open my Ubuntu partition using Crouton the screen just flickers and I can't click on anything in the partition, making it unusable. It worked fine yesterday, then my Chromebook updated itself and it stopped working. Thanks for any help.

#### If known, describe the steps to reproduce the issue:
Just starting up my Crouton partition.

**Comment by DennisLfromGA** [comment]
Dup of -

- awk: run time error: 'system' function not allowed in sandbox mode #3506

Please update your chroot for the fix using:

- `sudo sh ~/Downloads/crouton -n xenial -u`

*Hope this helps,*
-**DennisLfromGA**
