### ISSUE TITLE
Running Wayland compositors using ChromeOS's Wayland server?

### ISSUE THREAD

**Issue by duckdodger** [dnschneid/crouton#3680]
```
name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20180127033952~master:de1361af
release: buster
architecture: armhf
xmethod: xorg
targets: kde,xorg,xfce,xiwi
host: version 10176.72.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Feb 13 19:10:13 PST 2018 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster
```

I tried running individual wayland supported apps with host-wayland and it worked very well; much better than it ever did on X11 for my ARM Chromebook, so I naturally wanted to see if I can run an entire desktop like KDE or GNOME with host-wayland or something equivalent because I believe that would work nicely compared to X11 where there is no graphics acceleration. But I couldn't find any information about this anywhere. There is some information about running Weston in the [Wayland Notes](https://github.com/dnschneid/crouton/wiki/Wayland-Notes) section on the wiki, but I don't know how that translates to a desktop environment like KDE Plasma or GNOME. So I need some input on this, whether it would work and how. Thanks!

**Comment by ccaapton** [comment]
I've also had mpv/wayland working on mine.

There is a fork of crouton to run fedora with wayland, https://github.com/nmilosev/crouton-fedora-wayland, maybe you could have a try, and give us some feedback here:)

**Comment by ccaapton** [comment]
I just succeed in running weston inside crouton with debian/stretch. If you are still interested, here are the command line in crouton terminal shell(not in xorg/xiwi) :
`host-wayland weston    -S02 -Bwayland-backend.so  --fullscreen`

**Comment by duckdodger** [comment]
Thanks, but I have indeed tried running Weston and it works although it is kinda slow. I also have the double cursor issue. It is not nearly as fast as running XFCE on X server. However, running individual Wayland applications without compositor is very smooth, like GNOME or KDE apps.
