### ISSUE TITLE
ChromeOS Audio and Microphone no longer work on websites. Android apps are fine.

### ISSUE THREAD

**Issue by ryanphjohnson** [dnschneid/crouton#3681]
##### Please paste the output of the following command here: `sudo edit-chroot -all`
```
chronos@localhost / $ sudo edit-chroot -all
name: ie
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/ie...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,cli-extra,keyboard,x11,core,audio,touch,xorg,xfce-desktop
host: version 10176.72.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Feb 13 19:18:58 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/ie...

name: nerd
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/nerd...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xiwi
targets: core,cli-extra,touch,xiwi
host: version 10176.72.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Feb 13 19:18:58 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/nerd...

name: signal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/signal...
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xfce-desktop,xiwi,cli-extra,keyboard,x11,core,audio,touch,xorg
host: version 10176.72.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Feb 13 19:18:58 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/signal as another instance is using it.
```
#### Please describe your issue:

Ever since Android was introduced to ChromeOS websites like YouTube,com stopped playing video and audio. Some site with videos will play, but audio is always missing. I've not seen any articles mentioning this as a bug with ChromeOS, so I suspect its crouton. The YouTube App video and audio work just fine. It feels like Android has stolen control of all audio and microphone usage. I've tried plugging in and removing headphones to see how that affects things, but it appears to have no effect.

#### If known, describe the steps to reproduce the issue:
Visit youtube.com on a ChromeOS laptop with crouton. See this error:

![image](https://user-images.githubusercontent.com/5459646/37116641-83dab53a-2214-11e8-832b-d80e8a157b1a.png)

**Comment by ryanphjohnson** [comment]
Worth pointing out/updating: I tried closing Crouton windows, and this fixes the issue. So I can have crouton windows OR I can have YouTube video and audio, and my microphone works.

**Comment by ryanphjohnson** [comment]
Seems to be XIWI related. Crosh Windows are not breaking stuff, just XIWI.

**Comment by ryanphjohnson** [comment]
Attempted to run a chroot that didn't have Audio target, but that didn't resolve my issues either.

**Comment by tonyjmartinez** [comment]
Bump. I'm having the same [issue.](PRB8Model.getmTxtPRB8Output().setBackgroundResource(R.color.lightRed);)

**Comment by DennisLfromGA** [comment]
@ryanphjohnson,

> Some site with videos will play, but audio is always missing. I've not seen any articles mentioning this as a bug with ChromeOS, so I suspect its crouton.

I have a 'trusty' chroot configured as follows:

```
name: trusty
encrypted: no
Entering /var/crouton/chroots/trusty...
crouton: version 1-20180329190032~master:d287904a
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,keyboard,cli-extra,lxde-desktop,chrome-beta
host: version 10539.0.0 (Official Build) dev-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Apr 2 04:14:26 PDT 2018 x8
```

I get audio in a 'xiwi' tab in the chroot and audio in CrOS, see: https://goo.gl/2sdhx1
I'm not sure why it's happening to you but I can't repo it, sorry.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@tonyjmartinez,

You could check out the following wiki's for some tips -
- [Audio](https://github.com/dnschneid/crouton/wiki/Audio)
- [Access audio hardware directly (ALSA, JACK)](https://github.com/dnschneid/crouton/wiki/Access-audio-hardware-directly-(ALSA,-JACK))
- [Full Blown Audio Video Workstation using KDE chroot and KXStudio](https://github.com/dnschneid/crouton/wiki/Full-Blown-Audio-Video-Workstation-using-KDE-chroot-and-KXStudio)

*Hope this helps,*
-**DennisLfromGA**

**Comment by tonyjmartinez** [comment]
I finally fixed this by running 
`sudo sysctl fs.inotify.max_user_watches=1048576`
Within xfce. Couldn't fix it by running it outside the graphical xfce desktop environment.
