### ISSUE TITLE
Won't run in background

### ISSUE THREAD

**Issue by ChristopherKing42** [dnschneid/crouton#3682]
```
sudo enter-chroot xiwi -T startxfce4 &
```

#### Please describe your issue:

When I try to run it in the background, nothing happens. A little bit later `[3]+  Stopped                 ( sudo LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" enter-chroot xiwi -T startxfce4 )` appears.

#### If known, describe the steps to reproduce the issue:

Run `sudo enter-chroot xiwi -T startxfce4 &`

**Comment by DennisLfromGA** [comment]
@ChristopherKing42,

It's understandable to use the **`&`** character to put the process in the background but crouton has an option that does that in spades.  You can use `edit-chroot's` '**-b**' option to take care of all the intricacies, for details see [edit-chroot#L628](https://github.com/dnschneid/crouton/blob/master/host-bin/enter-chroot#L628)

`    -b          Fork and run the specified command silently in the background.`

*Hope this helps,*
-**DennisLfromGA**

**Comment by ChristopherKing42** [comment]
Thank you (although maybe it should give a more informative error when you use `&`).

**Comment by ChristopherKing42** [comment]
Also, I think you mean `enter-chroot`'s `-b`, not `edit-chroot`'s `-b`.

**Comment by DennisLfromGA** [comment]
@ChristopherKing42,

Yup, sorry, I meant `enter-chroot`, I edited it above so I don't lead others astray.

-**DennisLfromGA**
