### ISSUE TITLE
Starting KDE doesn't work.

### ISSUE THREAD

**Issue by HeyItsHotshot** [dnschneid/crouton#3683]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: armhf
xmethod: xorg
targets: kde
host: version 10176.76.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Feb 24 13:19:22 PST 2018 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
Just installed crouton and I tried to run sudo startkde but was met with a quick black screen and what I'm assuming to be one big error. Now, I've spent like 5 minutes trying to find a simple error code but with everything meshed together I have no clue what the error code actually is. This is what comes after trying to launch it. 

----

chronos@localhost / $ sudo startkde
Entering /mnt/stateful_partition/crouton/chroots/xenial...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-101-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sat Feb 24 13:19:22 PST 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=f087c549-d73b-7740-829e-3cda57c258b9/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 2539520 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2539520 alg=sha1 root_hexdigest=83ea3a82b50927331c2ed1c0eb250addbee3c71d salt=5ad4e80e74761ef825de79b29083dff5f5b352ddf4eedc4f493f97b342fc78be" noinitrd vt.global_cursor_default=0 kern_guid=f087c549-d73b-7740-829e-3cda57c258b9  
Build Date: 24 November 2017  09:45:24AM
xorg-server 2:1.19.5-0ubuntu2~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Mar 10 23:52:43 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1520743964.144488 sender=:1.9 -> destination=:1.38 serial=440 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1520743964.424089 sender=:1.9 -> destination=:1.40 serial=442 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

---

It does this every time I try to launch it. Tried reinstalling it and couldn't get it to work after a google search of the issue, or I'm just stupid and couldn't piece it together. Any help is greatly appreciated! Thank you!

**Comment by HeyItsHotshot** [comment]
Anyone? :-(

**Comment by DennisLfromGA** [comment]
@HeyItsHotshot,

Seems this issue has been around for quite a while now and is related to video-armsoc drivers.

Take a look at this comment for a little more info.: https://github.com/dnschneid/crouton/issues/3611

For a couple of workarounds, see this comment: https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813
Note that in Solution 1 above you'll have to substitute 'xfce4' with 'kde'.

*Hope this helps,*
-**DennisLfromGA**
