### ISSUE TITLE
Google Play / Android App support breaks 3D graphics on Acer CB5-571

### ISSUE THREAD

**Issue by jpmilton** [dnschneid/crouton#3685]
Just want to say what a great thing crouton is and well done. Have been using it for 18 months now, this is the first problem I have had.

```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20171230152552~master:de1361af
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,extension,xiwi
host: version 10176.76.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Feb 24 13:30:35 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
Failed to unmount /mnt/stateful_partition/crouton/chroots/trusty. Kill processes? [a/k/y/p/N] 

#### Please describe your issue:

I have 3 ACER Chromebook 15 CB5-571 (Intel) on which I have been successfully running Minecraft for over a year using crouton trusty.

Last week we received updates to support Google Play store and this appears to have broken the graphics drivers in some way. I am confident the update is to blame as it hits the three chromebooks at different times and Minecraft only stops working when it hits. 

When Minecraft starts, it gets through the the game screen, which would normally be the rendered 3D game, but the window is all black. Sound effects can be heard and the game does not crash.

I am using the latest oracle JRE

Bad ChromeOS : 64.0.3282.190 (official)
Last Good Chrome OS : 63.0.3239.140 (official)

When XFCE is started, there is a permissions error relating to the graphics GLX 
<snip>
....
Loading extension GLX
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
</snip>

Looks like the play update has made changes to the way the graphics works.

#### If known, describe the steps to reproduce the issue:

Run minecraft on a Google Play enabled CB5-571

**Comment by DennisLfromGA** [comment]
@jpmilton,

I have Intel Chromebooks with trusty/xfce chroots and I haven't run into this issue.
I don't have *'minecraft'* installed and running though so the issue may be confined to it.

There's a pull request in the works by the crouton author but it hasn't been fully tested & merged yet:
- Stop using the intel driver #3500

You might want to try some of the *workarounds* mentioned in this 'Black Screen' issue to get past it:
- https://github.com/dnschneid/crouton/issues/3654#issuecomment-367838170
- https://github.com/dnschneid/crouton/issues/3654#issuecomment-370006188

*Hope this helps,*
-**DennisLfromGA**

**Comment by jpmilton** [comment]
Hi @DennisLfromGA
Thank you so much for these links. #3654 hit the jackpot. Editing the
Driver and related options in the xorg-intel-sna.conf did the business.
Thanks again. Now I have two more Chromebooks to powerwash and update
to get Google Play, without losing Crouton.
Jonathan
