### ISSUE TITLE
No UI or terminal

### ISSUE THREAD

**Issue by rossjrw** [dnschneid/crouton#3689]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,extension,keyboard,touch,unity-desktop
host: version 10176.76.0 (Official Build) stable-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sat Feb 24 13:28:49 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

I've just removed my old trusty chroot and installed a new xenial one to see if it would fix previous issues.

I can enter the chroot via `sudo startunity` but beyond there I can't progress. I'm presented with the chroot's desktop but no menu or navigation bars. I can right-click, and from that dialogue I can access the settings menu and I can create new documents/folders onto the desktop. Clicking into each opens gedit and nautilus respectively, and both seem to work as expected.

I cannot close any windows once opened, minimise/maximise, or drag them around on the desktop. The buttons to do so do not appear.

Alt+Tab allows me to switch between any opened windows, but not the desktop.

I cannot open the terminal from the right-click menu (despite the option being presented) or via Ctrl+Alt+T.

Running from ChromeOS `sudo enter-chroot xiwi -T gnome-terminal` outputs `Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Terminal exited with status 8`

Running from ChromeOS `sudo enter-chroot xiwi -T xterm` works as expected.

I have updated the chroot using `sudo sh ~/Downloads/crouton -n xenial -u`, and problems persist.

Any assistance is much appreciated.

**Comment by rossjrw** [comment]
I fixed this by reinstalling with "unity" as a target instead of "unity-desktop", then updating the chroot with the "unity-desktop" target.

**Comment by Geraldalingod** [comment]
I Have the same problem with you someone help?

**Comment by Geraldalingod** [comment]
I Reset my Chrome OS nothing works then i install ubuntu again and enter the same username and password .

The Question › did the data was saved when i enter an existing username and password then it would load all setting i made and data or etc?


Sorry for bad english.

**Comment by DennisLfromGA** [comment]
@Geraldalingod,

It depends on what you mean by 'Reset my Chrome OS', if you did a 'powerwash' or 'full recovery' then no, nothing is saved, it's gone.

A Chrome OS update and/or a crouton update should leave all of your user data and settings intact but, apart from that, it will get removed.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@rossjrw,

Glad you figured a way around the issue and got it fixed.

It's a bit strange since installing the `unity-desktop` target requires the installation of the `unity` target as a prerequisite but I guess stranger things have happened. 

-**DennisLfromGA**
