### ISSUE TITLE
Chromebook hardware too behind

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#3691]
I was intent on getting a fanless pixel i5 or i7, but after doing quite a bit of research, the 6th gen cpus, and overall design just didn't cut it.

Ended up with an i5 surface pro, but would love to see Google come back with an ultralight 7th or later i series non throttling fanless device.

**Comment by dnschneid** [comment]
Sounds good.  Do you have any other hardware requests for the crouton bugtracker?
