### ISSUE TITLE
Cannot start Lubuntu since update

### ISSUE THREAD

**Issue by bmoffitt** [dnschneid/crouton#3693]
Updated Chrome-OS, and then Crouton. Since then, crouton will not start up. This is running on an acer 710-2856 with dual-core 1.5 GHz. Celery processor and 10 GB memory.

Please paste the output of the following command here: sudo edit-chroot -all

> name: lxde
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/lxde...
> crouton: version 1-20171230152552~master:de1361af
> release: trusty
> architecture: amd64
> xmethod: xiwi
> targets: xiwi,lxde-desktop
> host: version 10176.76.0 (Official Build) stable-channel parrot_ivb 
> kernel: Linux localhost 3.8.11 #1 SMP Sat Feb 24 13:12:10 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
> freon: yes
> Unmounting /mnt/stateful_partition/crouton/chroots/lxde...
> Failed to unmount /mnt/stateful_partition/crouton/chroots/lxde. Kill processes? [a/k/y/p/N] y
> Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Failed to unmount /mnt/stateful_partition/crouton/chroots/lxde. Kill processes? [a/k/y/p/N] a
> Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...

(continues)

#### Please describe your issue:
When chroot is started via "sudo startlxde" it dies with the following error:

> Current version of pixman: 0.30.2
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Mar 23 14:05:09 2018
> (++) Using config file: "/etc/X11/xorg-dummy.conf"
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> (EE) 
> (EE) Backtrace:
> (EE) 0: /usr/bin/Xorg (xorg_backtrace+0x48) [0x7f1b66a4a598]
> (EE) 1: /usr/bin/Xorg (0x7f1b668a1000+0x1ad289) [0x7f1b66a4e289]
> (EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f1b6599d000+0x10330) [0x7f1b659ad330]
> (EE) 3: /usr/bin/Xorg (0x7f1b668a1000+0xb56b6) [0x7f1b669566b6]
> (EE) 4: /usr/bin/Xorg (xf86BusProbe+0x9) [0x7f1b6692a149]
> (EE) 5: /usr/bin/Xorg (InitOutput+0x74d) [0x7f1b669386bd]
> (EE) 6: /usr/bin/Xorg (0x7f1b668a1000+0x59beb) [0x7f1b668fabeb]
> (EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7f1b643d8f45]
> (EE) 8: /usr/bin/Xorg (0x7f1b668a1000+0x451fe) [0x7f1b668e61fe]
> (EE) 
> (EE) Segmentation fault at address 0x0
> (EE) 
> Fatal server error:
> (EE) Caught signal 11 (Segmentation fault). Server aborting
> (EE) 
> (EE) 
> Please consult the The X.Org Foundation support 
>          at http://wiki.x.org
>  for help. 
> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
> (EE) 
> (EE) Server terminated with error (1). Closing log file.
> /usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> /usr/bin/xinit: server error
> Unmounting /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...
> Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/lxde...

(continues)

For some reason, it cannot finish killing processes - it seems to just keep running until interrupted via ctrl-c.

#### If known, describe the steps to reproduce the issue:
Unknown. Entering the chroot works fine, just fails starting Xorg.

**Comment by bmoffitt** [comment]
Update. Rebooted the Chromebook again and it suddenly started to work again. Your guess is as good as mine...

**Comment by DennisLfromGA** [comment]
@bmoffitt,

Sometimes just a Chrome OS update can't break things, just guessing but maybe that was the culprit this time.

-**DennisLfromGA**
