### ISSUE TITLE
Kafka consumer group fails to read data from one/more partitions

### ISSUE THREAD

**Issue by dineshkumars1985** [dnschneid/crouton#3698]
We are using 3 kafka consumers with same group id to read data. 
Kafka topic with Replication factor:5, Partition: 5

Initially all works fine, but after some time (say after 1 week), consumer group fails to read data from one or more partitions. We don't see any error being logged.

We use kafka version = 0.10.0.1

Any help here will be much appreciated.

**Comment by DennisLfromGA** [comment]
@dineshkumars1985,

Is this a 'crouton' issue?

-**DennisLfromGA**
