### ISSUE TITLE
startxfce4 not working anymore

### ISSUE THREAD

**Issue by TheMiner622** [dnschneid/crouton#3699]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
crosh> shell
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

#### Please describe your issue:

Two weeks ago, everything worked fine. But last week or so, whenever I tried going into linux, it would give me this. I tried re downloading crouton and rebooting my chromebook, but nothing seems to work.

**Comment by DennisLfromGA** [comment]
@TheMiner622,

- What Chrome OS version are you currently using?
  - Show us the first six lines when you navigate to: chrome://version
- Do you know what Chrome OS version may have caused this behavior?

There's another issue that may be the same or at least similar to this one:
- Can't run prepare.sh during setup, and can't access file when run separately #3695

We're still trying to narrow down what may be causing this but the more info. we have the better.

-**DennisLfromGA**

**Comment by TheMiner622** [comment]
Here they are:

Google Chrome | 67.0.3376.0 (Official Build) canary (64-bit)
-- | --
Revision | 0
Platform | 10516.0.0 (Official Build) canary-channel celes
Firmware Version | Google_Celes.7287.92.104
ARC | 4676007
JavaScript | V8 6.7.106

I was looking at the issue you referenced, and I was having a similar scenario:
I'm on the Canary Channel.
Maybe that has something to do with it.

**Comment by DennisLfromGA** [comment]
@TheMiner622,

Yup, that seems to be the case, at least it's the most common denominator in this and the other issue.

-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@TheMiner622,

I'm gonna close this issue so we can all track it in the same place, see:
- Can't run prepare.sh during setup, and can't access file when run separately #3695

-**DennisLfromGA**
