### ISSUE TITLE
Permission Denied on starting lxde

### ISSUE THREAD

**Issue by efundz1** [dnschneid/crouton#3702]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
`name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
`
#### Please describe your issue:
Updated chrome and have gotten the permission denied error eversince 

#### If known, describe the steps to reproduce the issue:
whenever I attempt to start lxde

many thanks
Jim

**Comment by tkamat** [comment]
Getting the same problem, seems to have happened after the last Dev channel update to Chrome 67.

**Comment by malkia** [comment]
Same here.

**Comment by efundz1** [comment]
tried to create a new chroot, however having the same `permission denied` errors. seems all related to the latest chrome update ;(

**Comment by cjzlol** [comment]
I have this question too, and i just updated

**Comment by DennisLfromGA** [comment]
Duping this issue to #3695 so it can be tracked there.
