### ISSUE TITLE
(Please label as question) Why was Cinnamon DE removed?

### ISSUE THREAD

**Issue by idSoftwareWolf** [dnschneid/crouton#3703]
Just a question. When I started using Crouton it had a DE named Cinnamon, and with more recent versions, it has been removed. Can someone tell me why?

**Comment by DennisLfromGA** [comment]
@idSoftwareWolf,

crouton's author explains it in this comment: https://github.com/dnschneid/crouton/issues/812#issuecomment-43784309
And here's where and when it was actually pulled: remove cinnamon target #832

*Hope this helps,*
-**DennisLfromGA**
