### ISSUE TITLE
Kali-rolling and sid Debian both run into this problem"W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg" (For Debian same for kali as well)

### ISSUE THREAD

**Issue by vonvy** [dnschneid/crouton#3704]
```
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
sudo sh -e ~/Downloads/crouton -r sid -t xfce 
"W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg"
```

#### Please describe your issue:
As I run both of these, they get the same output. I tried again with an Ubuntu install and it installed perfectly! I have looked up the issue and have seen it popping up over and over again and cannot seem to find a solution to the problem. I powerwashed my chromebook last night because of the issue, but it seems it did not work. 

Thanks

#### If known, describe the steps to reproduce the issue:
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
or
sudo sh -e ~/Downloads/crouton -r sid -t xfce

**Comment by guilala** [comment]
Bump, after upgrade to 67.0.3376.0 (Official Build) dev (64-bit)

**Comment by my0sin** [comment]
I'm having the same issue. Cannot write to that location anyways. on a pixelbook trying to do kde instead of xfce though

**Comment by leesthomas** [comment]
Same issue here on an Acer R11. Everything except Ubuntu refuses to install, and when Ubuntu is installed apt refuses to work so it's not really usable anyway.

**Comment by xwordforge** [comment]
I am having the same issue on an ASUS c202.  I have tried it on kde, gnome, xfce, xiwi.
chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r kali-rolling -t kde 

Installing kali-rolling-amd64 chroot to /media/removable/UNTITLED/chroots/kali-rolling
Downloading latest debootstrap...
-=#=-  #    #       #                                                                                                                                 
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg

**Comment by didipluto** [comment]
Same issue on Chromebook Pixel 2 LS．

**Comment by vonvy** [comment]
Looks like dnschneid needs to take a look for us. Hopefully we can get the issue resolved in a short time.

**Comment by Kakise** [comment]
I'm having the same issue. Acer Chromebook 14 for work.

`chronos@localhost ~/Downloads $ sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
Installing kali-rolling-amd64 chroot to /usr/local/chroots/kali-rolling
Downloading latest debootstrap...
-#O=#    #      #                                                                                                                                                        
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg`

Can't wirte to that location

**Comment by arias93jordy** [comment]
I cannot install any version of linux on my Samsung Chromebook for I don't know what reason....



help anyone???

Thank you

**Comment by drinkcat** [comment]
I can reproduce.

For now, I think we can pin debootstrap to version `1.0.92~bpo9+1` (still includes artful and bionic releases)

**Comment by vonvy** [comment]
So what should we do as of now, just wait and see?
