### ISSUE TITLE
Cannot start crouton with sudo startxfce4

### ISSUE THREAD

**Issue by tehkurt** [dnschneid/crouton#3706]
```
sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Crouton fails to load since ChromeOS updated recently to 67.0.3376.

Attemptiong to run an update on my install gives:

Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
cp: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/usr/local/bin/startxfce4': Permission denied

#### If known, describe the steps to reproduce the issue:
Reproducible by running sudo startxfce4 from shell. Output received:
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by tehkurt** [comment]
Issuing ls command in /mnt/stateful_partition/crouton/chroots/xenial/etx shows broken symlinks for the following files/folders:
debian_chroot
localtime
resolv.conf
vtrgb

**Comment by DennisLfromGA** [comment]
A fix has been pushed, update your chroot(s).
