### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Coyote4522** [dnschneid/crouton#3709]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
I can't
#### Please describe your issue:
I am having permission issues as of today using sudo startxfce4. saying I need root, don't have permission. I haven't changed anything either which I thought was strange.

#### If known, describe the steps to reproduce the issue:
crosh> shell
chronos@localhost / $ sudo edit-chroot-all
sudo: edit-chroot-all: command not found
chronos@localhost / $ sudo edit -chroot -all
sudo: edit: command not found
chronos@localhost / $ enter-chroot
enter-chroot must be run as root.
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by Finbae** [comment]
Also having this very similar output as of today, but with unity.

**Comment by dwaindibbly** [comment]
did you try `sudo edit-chroot -all` for the edit chroot? also, this is happening on all chroots so stay tight, it's gonna be a long journey.

**Comment by hammy3502** [comment]
You should be able to fix the error `ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied` with the following command:
`sudo sh ~/Downloads/crouton -u`.
See issue 
https://github.com/dnschneid/crouton/issues/3708

**Comment by Coyote4522** [comment]
I have tried all of the above suggestions to no success so far.

When I try updating crouton it gives me: sudo: /home/chronos/user/Downloads/crouton -u: command not found

**Comment by hammy3502** [comment]
@Coyote4522 , do you have the crouton script downloaded right now? Please download it from https://goo.gl/fd3zc and place it in your downloads folder without changing the name of the file. Afterward, you should be able to run the previously mentioned command.

**Comment by Coyote4522** [comment]
@hammy3502 I do indeed, just deleted and re-downloaded. Sameeeee deal. Very odd as it was working the day previous without issue.

**Comment by chaseweaver** [comment]
`Entering /mnt/stateful_partition/crouton/chroots/pendragon...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/pendragon/etc/resolv.conf': Permission denied`

Happening on my end here on `67.0.3383.0` canary.

**Comment by hammy3502** [comment]
Have you tried my solution? It fixed it for me.

**Comment by chaseweaver** [comment]
@hammy3502 Yeah, unfortunately I still do not have permission.

I just restored from a backup and updated and now:
`Unable to cd to '/home/chase'
Unmounting /mnt/stateful_partition/crouton/chroots/pendragon...`

and also

`su: warning: cannot change directory to /home/chase: Permission denied
su: failed to execute /bin/bash: Permission denied`

I'll give it a powerwash and try again sometime later.

**Comment by DennisLfromGA** [comment]
The issue regarding `.../resolv.conf: Permission denied` has been resolved.
Please refer to this comment for a resolution: https://github.com/dnschneid/crouton/issues/3695#issuecomment-376780085

*Hope this helps,*
-**DennisLfromGA**
