### ISSUE TITLE
Keyring file not available

### ISSUE THREAD

**Issue by idSoftwareWolf** [dnschneid/crouton#3711]
```
sudo sh ~/Downloads/crouton -t kde -r jessie
Installing jessie-amd64 chroot to /usr/local/chroots/jessie
Downloading latest debootstrap...                                                                                                       
Patching debootstrap...
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
chronos@localhost:~$
```

#### Please describe your issue:
Can't get a keyring..? I dunno.

#### If known, describe the steps to reproduce the issue:
Let's see... try to install debian stretch or jessie with kde on the Acer R11 Chromebook.

**Comment by DennisLfromGA** [comment]
That's a warning, not an error.

-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Please track this issue on: https://github.com/dnschneid/crouton/issues/2362
