### ISSUE TITLE
Error org.freedesktop.DBus.Error.UnknownMethod

### ISSUE THREAD

**Issue by dxwjoy** [dnschneid/crouton#3716]
I have seen there a lot of people got the same issue(but seems not work for me), and I hope if anyone could help me with this issue.
I tried **sudo sh ~/Downloads/crouton -n xenial -u** but it won't help.
Thanks a lot!!!

### Env info
1. Samsung chromebook pro 
1. ChromeOS 64.0.3282.190 (stable)

```
sudo startunity
```
#### Please describe your issue:
After I start the unity in shell ,  I will get a desktop with nothing on it , no menus, no icons, only the wallpaper.

log shows below:

(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Mar 31 00:48:26 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10176.76.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-16387-g09d1f8eebf5f #1 SMP PREEMPT Sat Feb 24 13:34:10 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output HDMI2 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output HDMI2 is not disconnected but has no modes
Kicking xrandr again
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

#### If known, describe the steps to reproduce the issue:
Just run sudo startunity

**Comment by DennisLfromGA** [comment]
@WoodrowDay,

You may be running into this issue:

- Can't Initialize ubuntu with crouton #3375

A fix for this has been merged:

- Use updated dbus method calls #3378

If this is your issue then a crouton update should get you back in business.

*Hope this helps,*
-**DennisLfromGA**
