### ISSUE TITLE
Black screen with cursor on xorg - xiwi works fine

### ISSUE THREAD

**Issue by chiragzq** [dnschneid/crouton#3721]
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180329190032~master:d287904a
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,unity,touch,extension
host: version 10323.62.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Mar 20 23:37:50 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
Running  'sudo startunity' yields a black screen with a mouse pointer. I believe something is wrong with the graphics drivers, as I can "click" on the launchers on the left side of the screen and see the cursor begin loading. I have tried solutions from #2923, which doesn't change anything, and #2978, which just crashes my computer. When I switch to xiwi everything seems to work perfectly.

**Comment by DennisLfromGA** [comment]
Not sure what's going on but there have been some other possibly related issues with the Intel driver.

See this comment for more info. and  a possible workaround: https://github.com/dnschneid/crouton/issues/3654#issuecomment-370006188

*Hope this helps,*
-**DennisLfromGA**

**Comment by spafindoople** [comment]
I also have seen that, I've tried using modesetting but that just crashes my computer.

**Comment by DennisLfromGA** [comment]
@spafindoople,

The comment I referred you to doesn't use modesetting, it uses a new branch the crouton author is working on: CROUTON_BRANCH=nointeldrv

*Hope this helps,*
-**DennisLfromGA**

**Comment by spafindoople** [comment]
Sorry for the misunderstanding! The link for some reason didn't redirect to your comment the first time I opened it.

After running the script, I got the followering error:
`E: Unable to locate package xserver-xorg-video-modesetting-lts-xenial`
This terminated the setup.

**Comment by SamFowler** [comment]
I am also facing this issue on Chromebook Pixel. I haven't had a chance to have another try recently, will keep updated if I make any progress
