### ISSUE TITLE
debootstrap cant download on install

### ISSUE THREAD

**Issue by OMaese** [dnschneid/crouton#3722]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

On install debootstrap fails to download "Empty reply from server" It has worked before on my network so I'm relatively sure its not on my end.

**Comment by DennisLfromGA** [comment]
@OMaese,

I'm not sure what release your using but your issue may be related to:

- Kali-rolling and sid Debian both run into this problem"W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg" (For Debian same for kali as well) #3704

A fix for this has been merged:

- ubuntu/boostrap: Pin debootstrap to 1.0.92~bpo9+1 #3714

If this is your issue then a crouton update should get you back in business.

*Hope this helps,*
-**DennisLfromGA**

**Comment by OMaese** [comment]
@DennisLfromGA 

I guess its not my problem, I don't know too much about linux or honestly most of what I'm doing. Still getting the [error](https://imgur.com/a/lz2cs) though, probably my network, haven't been able to test it on any other yet. Any help would be greatly appreciated.

**Comment by bet4a** [comment]
@OMaese,

The file that the installer is trying (and failing) to download is located at `http://httpredir.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.92~bpo9+1.tar.gz`. There’s a redirect involved, but that shouldn’t be causing problems.

To help troubleshoot any potential network issues, you can try running the command used by Crouton to download this file, but with verbose debugging output turned on. Run this command from a Crosh shell:

`curl -L -v --connect-timeout 60 --retry 2 "http://httpredir.debian.org/debian/pool/main/d/debootstrap/debootstrap_1.0.92~bpo9+1.tar.gz" > /dev/null`

That command is essentially a slightly modified version of what the [Crouton installer tries to do](https://github.com/dnschneid/crouton/blob/5430505a2daa972b064d027d002257528e3b80d3/installer/ubuntu/bootstrap#L23)—the *-v* option turns on verbose output, and since we’re just troubleshooting, the * > /dev/null* part causes the downloaded file to be discarded rather than saved to disk. Try running that command, then reply here with the output—hopefully that’ll help narrow down what’s causing your issue.

**Comment by Koleos4** [comment]
Same issue, here's my output for that line of code.

> curl

 -L -v --connect-timeout 60 --retry 2 "http://httpredir.debian.org/debian/pool/main/d/deboostrap/debootstrap_1.0.92~bpo9+1.tar.gz" > /dev/null
*   Trying 5.153.231.4...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2001:41c8:1000:21::21:4...
* TCP_NODELAY set
* Immediate connect fail for 2001:41c8:1000:21::21:4: Network is unreachable
*   Trying 2001:4f8:1:c::15...
* TCP_NODELAY set
* Immediate connect fail for 2001:4f8:1:c::15: Network is unreachable
*   Trying 2001:67c:2564:a119::148:14...
* TCP_NODELAY set
* Immediate connect fail for 2001:67c:2564:a119::148:14: Network is unreachable
* Connected to httpredir.debian.org (5.153.231.4) port 80 (#0)
> GET /debian/pool/main/d/deboostrap/debootstrap_1.0.92~bpo9+1.tar.gz HTTP/1.1
> Host: httpredir.debian.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Mon, 18 Jun 2018 07:42:48 GMT
< Server: Apache
< X-Content-Type-Options: nosniff
< X-Frame-Options: sameorigin
< Referrer-Policy: no-referrer
< X-Xss-Protection: 1
< Location: http://cdn-fastly.deb.debian.org/debian/pool/main/d/deboostrap/debootstrap_1.0.92~bpo9+1.tar.gz
< Content-Length: 349
< Content-Type: text/html; charset=iso-8859-1
< 
* Ignoring the response-body
{ [349 bytes data]
100   349  100   349    0     0    387      0 --:--:-- --:--:-- --:--:--   561
* Connection #0 to host httpredir.debian.org left intact
* Issue another request to this URL: 'http://cdn-fastly.deb.debian.org/debian/pool/main/d/deboostrap/debootstrap_1.0.92~bpo9+1.tar.gz'
*   Trying 151.101.172.204...
* TCP_NODELAY set
*   Trying 2a04:4e42:29::204...
* TCP_NODELAY set
* Immediate connect fail for 2a04:4e42:29::204: Network is unreachable
* Connected to cdn-fastly.deb.debian.org (151.101.172.204) port 80 (#1)
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0> GET /debian/pool/main/d/deboostrap/debootstrap_1.0.92~bpo9+1.tar.gz HTTP/1.1
> Host: cdn-fastly.deb.debian.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: Apache
< X-Content-Type-Options: nosniff
< X-Frame-Options: sameorigin
< Referrer-Policy: no-referrer
< X-Xss-Protection: 1
< Content-Type: text/html; charset=iso-8859-1
< Via: 1.1 varnish
< Content-Length: 324
< Accept-Ranges: bytes
< Date: Mon, 18 Jun 2018 07:42:49 GMT
< Via: 1.1 varnish
< Age: 597
< Connection: keep-alive
< X-Served-By: cache-ams4128-AMS, cache-jnb7520-JNB
< X-Cache: MISS, HIT
< X-Cache-Hits: 0, 1
< X-Timer: S1529307769.452763,VS0,VE0
< 
{ [324 bytes data]
100   324  100   324    0     0    160      0  0:00:02  0:00:02 --:--:--  1051
* Connection #1 to host cdn-fastly.deb.debian.org left intact

>

**Comment by DennisLfromGA** [comment]
It appears both version `1.0.92` and the version the latest merge is using `1.0.101` no longer exist on: 
- http://cdn-fastly.deb.debian.org/debian/pool/main/d/debootstrap/

Hopefully, someone will take a look at it soon.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Inumedia** [comment]
As Dennis said, those files are still missing from the link he provided.

Currently crouton is completely unusable on a freshly wiped Chromebook as I can't download debootstrap and can't set up any targets (My Chromebook is an Acer R13)

**Comment by dnschneid** [comment]
Please give the latest crouton a shot.

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the problem.
You can do a quick test with something like the following: crouton -r xenial -d -f xenial.bs

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....

-**DennisLfromGA**

**Comment by Inumedia** [comment]
Latest crouton works for me 👍
