### ISSUE TITLE
How to delete targets?

### ISSUE THREAD

**Issue by levistep32** [dnschneid/crouton#3723]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,unity-desktop,extension,xfce
host: version 10323.62.0 (Official Build) stable-channel setzer 
kernel: Linux localhost 3.18.0-16509-gfd728222c3ad-dirty #1 SMP PREEMPT Tue Mar 20 23:49:32 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

### I accidentally added some targets 
I accidentally added some targets to my chroot that I do not want! How do I delete this and save some storage?
For example, I used `sudo sh ~/Downloads/crouton -t unity-desktop -u` to install unity when i already had xfce. I accidentally closed my computer during the process and now I can run `sudo startunity` but it is very slow. This may be because my computer isn't very fast but I just want to remove the `unity-desktop` target.

**Comment by DennisLfromGA** [comment]
@levistep32,

There's no automated way to remove targets with crouton, it was discussed at one time but never came to fruition.

As a prerequisite to doing anything major like this, I would recommend performing a crouton backup of the chroot first.

I think you'll have to do it manually by removing unity, ubuntu-desktop, and related package(s) then deleting the targets from both `/.crouton-targets` and `/etc/crouton/targets` in the chroot.  After that exit, cross your fingers and perform a crouton update.

*Hope this helps,*
-**DennisLfromGA**
