### ISSUE TITLE
Audio doesn't play through headset

### ISSUE THREAD

**Issue by artemkolotilkin** [dnschneid/crouton#373]
I had this issue for a couple of weeks already, before updating to latest audio target with CRAS. Was hoping that CRAS could solve it, but unfortunately it's still there. 

When I start crouton without plugged headset and then plug it, headset is not being used and I cannot direct audio output on it. All the sounds are played through Chromebook speakers. In order to get it working I usually log out from crouton, plug headset and then start it again. 

Today I updated to latest audio target with CRAS support and now in Sound Settings on Ubuntu I only see CRAS device for both input and output.

Thanks in advance for looking into this.

**Comment by dnschneid** [comment]
I've heard reports that this has regressed; re-opening.

**Comment by dnschneid** [comment]
More specifically, switching between Chromium OS and VTs tends to reset audio selections.

**Comment by Muktee** [comment]
Pixel 2015, 
Trusty with xfce-desktop (Xubuntu), 
got same problem.

**Comment by kittenarmy** [comment]
I have the same problem with my ASUS Flip C100. No audio out of headphones, only out of speakers.

crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 9202.64.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Apr 5 13:01:00 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes

**Comment by ForceConstant** [comment]
Just wanted to report that I have this same issue with a samsung chromebook pro.

**Comment by nicolas161** [comment]
I have the same problem on my CTL J4+ with Ubuntu 16.04 and XFCE
