### ISSUE TITLE
(bug) blank screen in any target, any distro, lasted release

### ISSUE THREAD

**Issue by mckaygerhard** [dnschneid/crouton#3730]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: venenuxliuxlxde
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/venenuxliuxlxde...
crouton: version 1-20180329190032~master:d287904a
release: stretch
architecture: armhf
xmethod: xorg
targets: core,audio,lxde-desktop,x11
host: version 10323.67.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 3 11:52:52 PDT 2018 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/venenuxliuxlxde...
```

#### Please describe your issue:

sudo startlxde does not give start lxde

seems the x11 target are implits due dependences by the "Recommends" systems, and may cause some problems include the xorg packages, 

related: #2923 , #2978 and #3721 

#### If known, describe the steps to reproduce the issue:

shell
sudo su
sh crouton -r stretch -t core,audio,lxde-desktop

#### Log complete of running command:

```
chronos@localhost / $ sudo startlxde
Entering /mnt/stateful_partition/crouton/chroots/venenuxliuxlxde...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-4-armmp-lpae armv7l Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Apr 3 11:52:52 PDT 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=19793223-644f-5f45-b061-a9619556bb11/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none rw 1,0 2539520 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2539520 alg=sha1 root_hexdigest=65ea9f3f15e5188871d97f28e68e5a743478c0a3 salt=76773705a53b11a9b064c1d5f0889c6e80c45c1cfb37cc6ef055daf612ab1c0e" noinitrd vt.global_cursor_default=0 kern_guid=19793223-644f-5f45-b061-a9619556bb11  
Build Date: 16 October 2017  09:48:39AM
xorg-server 2:1.19.2-1+deb9u2 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Apr 12 09:18:50 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1523539130.949449 sender=:1.33 -> destination=:1.54 serial=789 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1523539131.264937 sender=:1.33 -> destination=:1.56 serial=791 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file
```

**Comment by mckaygerhard** [comment]
search in the others issues and seems its not only intel modesetting, due i have Chromebook ARM with Mali. 

seems that tried to load DRI) with display name and cannot get the display name, if get it, then modesetting its tried!

**Comment by mckaygerhard** [comment]
now using wheezy get in console that the scripts try to use the xmethod xiwi and i not have xiwi installed, maybe a bad detection are used, so force usage of x11 with vesa only installed modules (due the isse #3728 are a waste of time, installing lot of unsuported packages that can confuse the rootfs chrooted)

**Comment by mckaygerhard** [comment]
@dnschneid and @DennisLfromGA the information and documentation are very few, i try to help and theres many out of info in the project, my time are very limited and  i have resources, i have many issues open and receive vage responses, like : 

> The command is placed in your 'host-bin' when you install crouton.

the wiki does not said nothing about, only "sudo edit-chroot"

>Like the crouton README says 'Check out the edit-chroot command; it likely does what you need it to do.'

the readme doe snot say nothign abut path's only "checks" and in that oportunity the CHECK FAILS

now the device will be returned and thanks to you guys a great oportunity will be closed

if any person want to solve this, may need better info and better organization in the documentation, the wiki of the Chromiun Project helps so many but are not related to crouton.. 

thanks in any case, it's not my problem .. for now.. if i get another Chromebook device i recomended do not adquire.. 

close and end of support for many device are not more "close" and "little" and now devices will have less time supported, one this time pass.. what will be?

**Comment by DennisLfromGA** [comment]
@mckaygerhard,

Sorry we couldn't provide the information, documentation, and support you need.

I try but the result isn't always enough in some cases, I'm just another crouton user like you, not a crouton dev, so my knowledge and experience definitely has its limits.

-**DennisLfromGA**

**Comment by mjonsson1986** [comment]
seems we have the same issue
acer r11 cb5132t a x86 chromebook
i setup my chroot like this: crouton -r sid -t gnome-desktop,core,audio,xorg
and the xserver-xorg-video-intel are installed
and legacy are not installed
