### ISSUE TITLE
awk: run time error: redirection not allowed in sandbox mode

### ISSUE THREAD

**Issue by easierbycode** [dnschneid/crouton#3735]
```
Please paste the output of the following command here: sudo edit-chroot -all

![screenshot 2018-04-16 at 2 26 58 pm](https://user-images.githubusercontent.com/563975/38836279-6422950e-4182-11e8-938e-8d0880e821b9.png)

name: code-oss-chroot
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/code-oss-chroot...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 10176.76.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-16387-g09d1f8eebf5f #1 SMP PREEMPT Sat Feb 24 13:34:10 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/code-oss-chroot...

```

#### Please describe your issue:

if I type:
`sudo startxfce4`  I get this output before it fails to open:

Entering /mnt/stateful_partition/crouton/chroots/code-oss-chroot...
awk: run time error: redirection not allowed in sandbox mode
        FILENAME="" FNR=0 NR=0
-su: 34: [[: not found
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

#### If known, describe the steps to reproduce the issue:

sudo startxfce4

**Comment by DennisLfromGA** [comment]
@easierbycode,

That's an old issue that has been fixed now, just update your chroot for the changes.

*Hope this helps,*
-**DennisLfromGA**

**Comment by easierbycode** [comment]
is this correct?
do I run it again for xfce4?

`sudo sh ~/Downloads/crouton -u -n code-oss-chroot -t xiwi`
