### ISSUE TITLE
Crouton Integration Extension for Chrome causing Audio Issues - ASUS Chromebook C302CA

### ISSUE THREAD

**Issue by tonyjmartinez** [dnschneid/crouton#3736]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,xfce
host: version 10323.67.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-16510-gb08afe9c5feb-dirty #1 SMP PREEMPT Tue Apr 3 11:57:57 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
The crouton integration extension for chrome is preventing audio from working in Chrome. Whenever I go to Youtube, Netflix, Udemy, etc. the audio doesn't work. 

#### If known, describe the steps to reproduce the issue:
If I turn off or remove the extension, and reboot my Chromebook, audio starts working again. I've tried seeing if other extensions caused this issue but the Crouton extension is the only one that causes the issue. I've downloaded a new installer and updated my chroot.

**Comment by icecream95** [comment]
As a workaround, does `sudo restart cras` from the chronos shell fix the audio?

**Comment by tonyjmartinez** [comment]
This bug isn't happening to me right now. Usually, I powerwash my machine and reinstall crouton and it goes away for a couple weeks, then comes back. I'll give it a shot when it comes back.

**Comment by tonyjmartinez** [comment]
Audio issue just happened again and `sudo restart cras` didn't fix it.

**Comment by tonyjmartinez** [comment]
Fixed this by running 
`sudo sysctl fs.inotify.max_user_watches=1048576`

From the terminal within a graphical xfce4 desktop. Only worked when I ran this within the desktop.
