### ISSUE TITLE
No directory, logging in with HOME=/

### ISSUE THREAD

**Issue by scudette** [dnschneid/crouton#3739]
```
chronos@localhost / $  sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,cli-extra,xfce
host: version 10575.8.0 (Official Build) dev-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Apr 18 22:51:55 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
After chromeos update can no longer startcli.

#### If known, describe the steps to reproduce the issue:
I usually enter the chroot with startcli but this seems to fail now. It still leaves me in the chroot as the right user but the user's home directory seems to be owned by root and it is empty.

```
chronos@localhost / $ sudo startcli
Entering /mnt/stateful_partition/crouton/chroots/xenial...
No directory, logging in with HOME=/
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

mkdir: cannot create directory '//.config': Permission denied
ln: failed to create symbolic link '//.config/pulse/default.pa': No such file or directory
(xenial)mic@localhost:/$ ls -l /home/
total 12
drwx------. 2 root root 4096 Apr 21 07:41 mic
drwxr-xr-x. 2 root root 4096 Jan 23 15:48 scudette
(xenial)mic@localhost:/$ sudo ls /home/mic/
(xenial)mic@localhost:/$ 
```
But if I exit the chroot and look at the files from crosh the files are all still there:
```
chronos@localhost / $ ls /mnt/stateful_partition/crouton/chroots/xenial/home/mic/
bin  Desktop  Dev  Documents  Downloads  emacs.desktop 
```

**Comment by scudette** [comment]
Argh sorry it was my fault. I messed up the file `/etc/crouton/shares`. When I moved it out of the way it all works as normal.

**Comment by Alzimmers** [comment]
@scudette 
Sorry about this question, but what did you do to move the shares file?
I am currently have this exact same problem by attempting to have all my files accessible by ChromeOS but I don't really know that much about linux/crouton.
Any (Detailed) help would be greatly appreciated.

**Comment by scudette** [comment]
In my case there was a syntax error in the file - if you move it out the way it all works. I ended up having this in the file:
```
downloads ~/Downloads
```
Which just shares the downloads folder with the crouton home directory. You can just move it out of the way:
```
sudo mv /etc/crouton/shares  /etc/crouton/shares.backup
```
then exit and `sudo startcli` again

**Comment by DennisLfromGA** [comment]
@scudette,

My `/etc/crouton/shares` file is he original and untouched and works just fine.
The entire file is comments except for the last line -
```
........
# Share the downloads folder of the current user's profile
downloads ~/Downloads
````

-**DennisLfromGA**
