### ISSUE TITLE
Installing crouton with encryption causes apt-get to fail on Samsung Chromebook Pro

### ISSUE THREAD

**Issue by altacus** [dnschneid/crouton#3740]
I've installed crouton with the following commands
    sudo sh ~/Downloads/crouton -e -t touch,kde
    sudo sh ~/Downloads/crouton -e -t touch,xfce

After either of the above installs, a simple sudo apt-get update will error out. 

Removing the -e parameter will allow apt to work after install.

**Comment by DennisLfromGA** [comment]
@altacus,

The '-e' option above will install a chroot with encryption as you're aware, but it shouldn't prevent you from using `apt-get` afterward unless you're not entering the correct _user_ password.

> After either of the above installs, a simple sudo apt-get update will error out.  

What do you mean it will '*error out*', what is displayed?  

If you enter your chroot as root after it's installed, e.g. `sudo enter-chroot -n xenial -u root`,
 does `apt-get` work (without the use of `sudo`)?   
If so, you may need to reset the *user* password, you can do that by logging in as root as shown and then running the following: `passwd <user>`
Substitute <user> with the actual username you provided when you installed the chroot.
It will prompt you for a password (twice), it won't be displayed but it will be accepted if they match.

If `sudo apt-get` and everything else works after setting up a new user password then you *can* encrypt the chroot if you choose with a crouton update, e.g. `sudo sh ~/Downloads/crouton -n xenial -e -u`

*Hope this helps,*
-**DennisLfromGA**
