### ISSUE TITLE
sudo password?

### ISSUE THREAD

**Issue by XimThatGuyX** [dnschneid/crouton#3741]
everytime i do a debugg on my system on devolper mode i keep getting asked for a password after any sudo command i dont set any password after debugging and still all i get is asking for password tried nearly every password i could think of and nothing working 
this is what i get:
crosh> shell
chronos@localhost / $ sudo su

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 

after 3 tries i get this:
Password: 
Sorry, try again.
Password: 
Sorry, try again.
Password: 
sudo: 3 incorrect password attempts
chronos@localhost / $

any help willl be appericated

**Comment by DennisLfromGA** [comment]
See if this helps: https://github.com/dnschneid/crouton/issues/2050#issuecomment-348382431

The only thing I'd add to that comment is this: 
> Type the default password **test0000**, or the *custom password* you set previously.

For more info.see: [Debugging Features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features)

*Hope this helps,*
-**DennisLfromGA**
