### ISSUE TITLE
Unknown command installing withcrouton

### ISSUE THREAD

**Issue by yossjackson** [dnschneid/crouton#3749]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
sudo: edit-chroot: command not found

#### Please describe your issue:
Got Unknown command when executing "sudo sh -v -e ~/Downloads/crouton -r trusty -t xfce -e -u" 

#### If known, describe the steps to reproduce the issue:
1. Turn on developer mode on samsumg chromebook series 3 XE303C12
1. Download crouton script from http://goo.gl/fd3zc
2. Open terminal, execute "shell", then execute "sudo sh -v -e ~/Downloads/crouton -r trusty -t xfce -e -u" and got unknown command

**Comment by DennisLfromGA** [comment]
@yossjackson,

I'm not sure where you're getting those instructions and that installation command line, it uses some older option conventions and is for updating a chroot not installing a new one.  
If you want a to install a new chroot using the latest LTS distro that crouton supports try this:
- Click on [http://goo.gl/fd3zc](http://goo.gl/fd3zc) and save 'crouton' to your ~/Downloads folder.
- Then enter: `sudo sh ~/Downloads/crouton -t xfce`   

That will give you the 'xenial' distro with an xfce4 desktop using 'xorg', if you want to also use crouton in a tab or window you can add 'xwi' to your targets using this:
- Enter: `sudo sh ~/Downloads/crouton -t xorg,xiwi,xfce`
With 'xiwi' you also need to install the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension.

Once you have it installed successfully and setup you can add encryption if you like with an update similar to:
- This: `sudo sh ~/Downloads/crouton -n xenial -e -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by yossjackson** [comment]
Done. 

Audio from the chroot will now be forwarded to CRAS (Chromium OS audio server),
through an ALSA plugin.

Future Chromium OS upgrades may break compatibility with the installed version
of CRAS. Should this happen, simply update your chroot.

You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.

You can start Xfce via the startxfce4 host command: sudo startxfce4

Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Done! You can enter the chroot using enter-chroot.

Now, when I execute sudo startxfce4 got this:

Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Tue Oct 21 07:04:19 PDT 2014 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=9b643078-7733-0e4c-826d-2ac6bdd88ee2/PARTNROFF=1 hashtree=PARTUUID=9b643078-7733-0e4c-826d-2ac6bdd88ee2/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=62f3d5265c436ce63d4f895bb20bef9a83650c89 salt=5db019109c1750541ff72d408496cacdc57b5ce684fe61d950ceb6a402cb96c6" noinitrd vt.global_cursor_default=0 kern_guid=9b643078-7733-0e4c-826d-2ac6bdd88ee2 
Build Date: 13 October 2017  01:59:44PM
xorg-server 2:1.18.4-0ubuntu0.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/eluardo/.local/share/xorg/Xorg.1.log", Time: Thu May  3 11:48:26 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/eluardo/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
^[[A/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

**Comment by bobswaggit** [comment]
yea i get similar issue, also have xe303c12, maybe its something to do with ARM chip on video driver

**Comment by DennisLfromGA** [comment]
It could be the issue as or related to #3611 

See this comment for some possible workarounds: https://github.com/dnschneid/crouton/issues/3291#issuecomment-309564813

*Hope this helps,*
-**DennisLfromGA**
