### ISSUE TITLE
Cant open terminal after installing Ubuntu 18.04 Unity. 

### ISSUE THREAD

**Issue by Aetheric1** [dnschneid/crouton#3750]
When I try to start terminal, it shows that its running but then it closes.

**Comment by yiyuezhuo** [comment]
I find same problem, terminal can be searchred but run faily. But XTerm is still working though can't be called by ctrl+alt+t as usual.

**Comment by yiyuezhuo** [comment]
Well, it seems some setup configure are miss, the post solve my problem:

https://askubuntu.com/questions/608330/problem-with-gnome-terminal-on-gnome-3-12-2

**Comment by DennisLfromGA** [comment]
@Aetheric1,

Please show us the output of: `sudo edit-chroot -all`
It gives us important info. about your device, version, targets, etc. that will help us help you.

> When I try to start terminal, it shows that its running but then it closes.

I'm assuming you mean the 'terminal' in the chroot, not the 'terminal' in a crosh shell session.

Are you getting any error messages and if so what are they?
What command are you using 'to start terminal'?
Is it `sudo enter-chroot` or something else?

> BTW I have no text editor installed since it's a fresh install so I can't change any files.

Developer mode in CrOS has '`vim`' installed so if your chroot is installed in the default location, you *could* change directories into your chroot and edit the files directly without the chroot running.  
For instance, if you have installed the default 'xenial' release try this:

```
cd /usr/local/chroots/xenial
ls -l
```
That will list all the files & folders in your chroot's '/' directory.
From there you can `cd` into your home folder or anywhere else and edit the files using `vim`.
Beware this can render your chroot (even more) useless if you bork something.

*Hope this helps,*
-**DennisLfromGA**
