### ISSUE TITLE
ubuntu xenial just a blank screen

### ISSUE THREAD

**Issue by ammaarpatel99** [dnschneid/crouton#3751]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
name: xenial_main
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial_main...
chronos@localhost / $ 
```

#### Please describe your issue:
when starting the chroot it just brings up a blank screen. It has the colourful background but no icons, launcher etc. all you can do is move the mouse and return to chrome os. non of the ubuntu shortcuts do anything. the only way to close it is to unmount it from chrome os. Literally nothing can be done on it other than move the mouse around a colourful background
this is what the terminal says when I startunity

crosh> shell
chronos@localhost / $ sudo startunity
Password: 
Enter encryption passphrase for xenial_main: 
Entering /mnt/stateful_partition/crouton/chroots/xenial_main...
Unknown username "geoclue" in message bus configuration file

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.118-13211-geca7e0a1e0d8 #1 SMP PREEMPT Tue Apr 24 23:43:38 PDT 2018 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4710400 verity payload=PARTUUID=5a767cd7-c99a-a944-bd5f-a5b81a98cd8b/PARTNROFF=1 hashtree=PARTUUID=5a767cd7-c99a-a944-bd5f-a5b81a98cd8b/PARTNROFF=1 hashstart=4710400 alg=sha1 root_hexdigest=ff5b397aeda09a7955be63042423bf06e3610630 salt=894aeef508251d7b979ed46e01e1cc3fd5419b7a4d6d0bfb578f58e72837c0a6" noinitrd vt.global_cursor_default=0 kern_guid=5a767cd7-c99a-a944-bd5f-a5b81a98cd8b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic disablevmx=off  
Build Date: 13 October 2017  01:57:05PM
xorg-server 2:1.18.4-0ubuntu0.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat May  5 12:46:54 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xorg
targets: unity,touch
host: version 10452.74.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.118-13211-geca7e0a1e0d8 #1 SMP PREEMPT Tue Apr 24 23:43:38 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
Kicking xrandr again
(EE) BUG: triggered 'if (priv->num_active_touches == 0)'
(EE) BUG: ../../src/synaptics.c:2966 in UpdateTouchState()
(EE) 
(EE) Backtrace:
(EE) 0: /usr/lib/xorg/Xorg (xorg_backtrace+0x4e) [0x57cee65c66ce]
(EE) 1: /usr/lib/xorg/modules/input/synaptics_drv.so (0x7fb20000f000+0x5b9c) [0x7fb200014b9c]
(EE) 2: /usr/lib/xorg/modules/input/synaptics_drv.so (0x7fb20000f000+0x7682) [0x7fb200016682]
(EE) 3: /usr/lib/xorg/Xorg (0x57cee6414000+0x94268) [0x57cee64a8268]
(EE) 4: /usr/lib/xorg/Xorg (0x57cee6414000+0xb9652) [0x57cee64cd652]
(EE) 5: /lib/x86_64-linux-gnu/libc.so.6 (0x7fb207419000+0x354b0) [0x7fb20744e4b0]
(EE) 6: /lib/x86_64-linux-gnu/libc.so.6 (__select+0x33) [0x7fb2075165d3]
(EE) 7: /usr/lib/xorg/Xorg (WaitForSomething+0x1d7) [0x57cee65c33f7]
(EE) 8: /usr/lib/xorg/Xorg (0x57cee6414000+0x53bce) [0x57cee6467bce]
(EE) 9: /usr/lib/xorg/Xorg (0x57cee6414000+0x57e13) [0x57cee646be13]
(EE) 10: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf0) [0x7fb207439830]
(EE) 11: /usr/lib/xorg/Xorg (_start+0x29) [0x57cee6456069]
(EE) 
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

#### If known, describe the steps to reproduce the issue:
I created a chroot in shell with sudo sh ~/Downloads/crouton -t unity,touch -n xenial_main -e
when I did sudo startunity and entered password etc it happened and the only way to close the chroot is to manually unmount it from chrome os terminal
This problem occurs on my pixelbook. i don't know if this is specific to the pixelbook or if it is a problem with crouton

edit: I just created a trusty chroot and that seems to be working fine so it's definitely something to do with xenial

**Comment by Hodges3902** [comment]
same issue here...

**Comment by melc** [comment]
Same issue here

**Comment by oilrig11** [comment]
I have this issue on a gen1 Thinkpad Yoga 11e Chromebook.

**Comment by jots** [comment]
same issue here

**Comment by jots** [comment]
I got it working by doing this:
sudo enter-chroot -n (name of my chroot)
sudo apt-get install compizconfig-settings-manager
ln -s /usr/bin/xterm /home/<username>/Desktop/xterm
then exit the chroot and startunity like normal.
then click on the xterm icon to open a shell and enter: ccsm
search for unity in the search box and from there you should see a way to enable unity plugin (on left hand side).

**Comment by ammaarpatel99** [comment]
If you have a Chromebook that supports our will support crostini (Linux apps on Chrome OS) then you may be better off using that.
