### ISSUE TITLE
Stop imminent wipe

### ISSUE THREAD

**Issue by penthimos** [dnschneid/crouton#3752]
I also wrote here:

https://groups.google.com/forum/?nomobile=true#!topic/crouton-central/FVnhsdWFi5o

I accidentally hit the space bar at startup. I held down the power button to stop it... I would have done anything to kill the power on it. Is there any intervention I can launch when I restart that will prevent it from nuking my data?

**Comment by DennisLfromGA** [comment]
Just now seeing this issue here, sorry.
I responded on the Crouton Central site [here](https://groups.google.com/d/msg/crouton-central/FVnhsdWFi5o/iiZaXppmAQAJ) but, short answer, probably not possible to revert now.

Closing.
