### ISSUE TITLE
Network information recently changed?  "sudo iwconfig wlan0 | grep ESSID | awk -F: '{print }' " broken

### ISSUE THREAD

**Issue by westmj** [dnschneid/crouton#3760]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20180329190032~master:d287904a
release: trusty
architecture: amd64
xmethod: xiwi
targets: audio,cli-extra,core,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,kodi
host: version 10452.85.0 (Official Build) stable-channel banjo 
kernel: Linux localhost 4.4.118-13212-g6c21f415c5d1 #1 SMP PREEMPT Thu May 3 23:51:22 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

#### Please describe your issue:
When in crouton, I need to record the SSID of the wireless network that I am on.  The titled command used to work.  After recently upgrading crouton and chromebook, it is broken, and the outputs seem to indicate that crouton is not inheriting the network configuration of my chromebook.

sudo iwconfig wlan0 | grep ESSID | awk -F: '{print }'

#### If known, describe the steps to reproduce the issue:

(trusty)westmj@localhost:~$ sudo iwconfig wlan0 | grep ESSID | awk -F: '{print }'
wlan0     no wireless extensions.

**Comment by DennisLfromGA** [comment]
Hmmm, it's working for me:
```
(trusty)denny@localhost:~$ sudo iwconfig wlan0 | grep ESSID | awk -F: '{print }'
[sudo] password for denny: 
wlan0     IEEE 802.11abgn  ESSID:"LOCKSLAN_5G"  
```
My croutonversion is the same too:
```
(trusty)denny@localhost:~$ croutonversion
crouton: version 1-20180329190032~master:d287904a
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,gnome-desktop,lxde-desktop,xfce-desktop,cli-extra,keyboard,touch,chrome-beta
host: version 10635.0.0 (Official Build) dev-channel eve 
kernel: Linux localhost 4.4.129-13998-g73e0c22ceb8f #1 SMP PREEMPT Tue May 1 04:30:23 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
About the only difference is yours is an Acer Chromebook 15.6" (CB3-531) and mine is a Pixelbook but they're both Intel devices so it's not an ARM thing.

*Hope this helps,*
-**DennisLfromGA**

**Comment by westmj** [comment]
It fails on a Samsung Chromebook 3, 4/32, that is provided by a school to me with crouton.  It works on my HP chromebook with xenial, see below.  I tried switching to the developer channel on my Acer, but not sure if I need to restart again.  Initially it seems to still fail.  Any more thoughts? Thank you. 

HP:
(xenial)westmj@localhost: $ uname -a
Linux localhost 3.18.0-17579-gfb99dee6e87a #1 SMP PREEMPT Tue May 15 12:30:57 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
(xenial)westmj@localhost: $ sudo iwconfig wlan0 | grep ESSID | awk -F: '{print }'
[sudo] password for westmj: 
wlan0     IEEE 802.11abgn  ESSID:"Neltar's"  
(xenial)westmj@localhost: $ croutonversion
crouton: version 1-20180329190032 master:d287904a
release: xenial
architecture: amd64
xmethod: xiwi
targets: audio,chrome,core,cli-extra,e17,extension,gtk-extra,gnome,keyboard,lxde,lxde-desktop,x11,xfce,xiwi,xorg
host: version 10682.0.0 (Official Build) dev-channel chell 
kernel: Linux localhost 3.18.0-17579-gfb99dee6e87a #1 SMP PREEMPT Tue May 15 12:30:57 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
(xenial)westmj@localhost:~$

**Comment by divx118** [comment]
@westmj what does just `sudo iwconfig` give you as an output on the Samsung? Maybe Samsung Chromebook 3 uses a different wireless interface name as `wlan0`

**Comment by westmj** [comment]
Samsung Chromebook 3 (just updated xenial, still broken, but ifconfig correct)

(xenial)westmj@localhost:~$ sudo iwconfig
wlan0     no wireless extensions.

arcbr0    no wireless extensions.

lo        no wireless extensions.

(xenial)westmj@localhost:~$ sudo ifconfig
arcbr0    Link encap:Ethernet  HWaddr be:ba:7f:1e:1e:eb  
          inet addr:100.115.92.1  Bcast:100.115.92.3  Mask:255.255.255.252
          inet6 addr: fe80::bcba:7fff:fe1e:1eeb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:52 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:4184 (4.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:34826 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34826 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2389909 (2.3 MB)  TX bytes:2389909 (2.3 MB)

wlan0     Link encap:Ethernet  HWaddr b4:d5:bd:13:08:da  
          inet addr:192.168.1.107  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::b6d5:bdff:fe13:8da/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:106408 errors:0 dropped:0 overruns:0 frame:0
          TX packets:78112 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:150352096 (150.3 MB)  TX bytes:9990115 (9.9 MB)


Strangely, with an update, the Acer Chromebook now works correctly in trusty.

(trusty)westmj@localhost:~$ sudo iwconfig
[sudo] password for westmj: 
lo        no wireless extensions.

wlan0     IEEE 802.11abgn  ESSID:"Neltar's"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: 82:2A:A8:7F:A0:FD   
          Bit Rate=144.4 Mb/s   Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=57/70  Signal level=-53 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:649   Missed beacon:0

(trusty)westmj@localhost:~$ sudo ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:102922 errors:0 dropped:0 overruns:0 frame:0
          TX packets:102922 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:7380874 (7.3 MB)  TX bytes:7380874 (7.3 MB)

wlan0     Link encap:Ethernet  HWaddr 4c:eb:42:e0:b5:be  
          inet addr:192.168.1.108  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::4eeb:42ff:fee0:b5be/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:29308 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25627 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:29281724 (29.2 MB)  TX bytes:11016066 (11.0 MB)

(trusty)westmj@localhost:~$ croutonversion
crouton: version 1-20180329190032~master:d287904a
release: trusty
architecture: amd64
xmethod: xiwi
targets: audio,cli-extra,core,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,kodi
host: version 10682.0.0 (Official Build) dev-channel banjo 
kernel: Linux localhost 4.4.131-14109-g7f22e51e592d #1 SMP PREEMPT Tue May 15 12:25:30 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
(trusty)westmj@localhost:~$ 


Another Chromebook (HP) works.

(xenial)westmj@localhost:~$ croutonversion
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xiwi
targets: audio,chrome,core,cli-extra,e17,extension,gtk-extra,gnome,keyboard,lxde,lxde-desktop,x11,xfce,xiwi,xorg
host: version 10452.85.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-17026-g0cc3b9494cbf #1 SMP PREEMPT Fri May 4 00:00:55 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
(xenial)westmj@localhost:~$ uname -a
Linux localhost 3.18.0-17026-g0cc3b9494cbf #1 SMP PREEMPT Fri May 4 00:00:55 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
(xenial)westmj@localhost:~$ 




(xenial)westmj@localhost:~$ sudo iwconfig                                      
[sudo] password for westmj: 
wlan0     IEEE 802.11abgn  ESSID:"Neltar's"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: 82:2A:A8:7F:A0:FD   
          Bit Rate=144.4 Mb/s   Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=50/70  Signal level=-60 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:1009   Missed beacon:0

veth_android  no wireless extensions.

arcbr0    no wireless extensions.

lo        no wireless extensions.

(xenial)westmj@localhost:~$ sudo ifconfig 
arcbr0    Link encap:Ethernet  HWaddr 9e:b7:26:60:36:6b  
          inet addr:100.115.92.1  Bcast:100.115.92.3  Mask:255.255.255.252
          inet6 addr: fe80::109c:c5ff:fe20:83c4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1917 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1987 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:413052 (413.0 KB)  TX bytes:1073646 (1.0 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:28590 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28590 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2084247 (2.0 MB)  TX bytes:2084247 (2.0 MB)

veth_android Link encap:Ethernet  HWaddr 9e:b7:26:60:36:6b  
          inet6 addr: fe80::9cb7:26ff:fe60:366b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1917 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1958 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:439890 (439.8 KB)  TX bytes:1098724 (1.0 MB)

wlan0     Link encap:Ethernet  HWaddr 4c:80:93:b9:f9:b0  
          inet addr:192.168.1.110  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::4e80:93ff:feb9:f9b0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10706 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7710 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:9784572 (9.7 MB)  TX bytes:1514891 (1.5 MB)

(xenial)westmj@localhost:~$ croutonversion
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xiwi
targets: audio,chrome,core,cli-extra,e17,extension,gtk-extra,gnome,keyboard,lxde,lxde-desktop,x11,xfce,xiwi,xorg
host: version 10682.0.0 (Official Build) dev-channel chell 
kernel: Linux localhost 3.18.0-17579-gfb99dee6e87a #1 SMP PREEMPT Tue May 15 12:30:57 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
(xenial)westmj@localhost:~$ uname -a
Linux localhost 3.18.0-17579-gfb99dee6e87a #1 SMP PREEMPT Tue May 15 12:30:57 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
(xenial)westmj@localhost:~$

**Comment by DennisLfromGA** [comment]
Well, I guess the channel & version was the difference.  
I hadn't noticed that in my first post but I was already on the dev channel and you were on the stable channel.

**Comment by westmj** [comment]
I believe the problem was on dev and stable until recently, and the problem is still found in the wild. Still interested in extinguishing this bug.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
