### ISSUE TITLE
Unable to start Ubuntu Unity

### ISSUE THREAD

**Issue by Techiastronamo** [dnschneid/crouton#3761]
```

chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10452.85.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-17026-g0cc3b9494cbf #1 SMP PREEMPT Fri May 4 00:00:55 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

```
The following occurs when trying to start Unity through crouton in the console:

> crosh> shell
> chronos@localhost / $ sudo startunity
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
> awk: run time error: redirection not allowed in sandbox mode
>         FILENAME="" FNR=0 NR=0
> Unknown username "geoclue" in message bus configuration file
> 
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> 
> X.Org X Server 1.18.4
> Release Date: 2016-07-19
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 4.4.0-45-generic x86_64 Ubuntu
> Current Operating System: Linux localhost 3.18.0-17026-g0cc3b9494cbf #1 SMP PREEMPT Fri May 4 00:00:55 PDT 2018 x86_64
> Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=f37d1afa-50b8-c048-8794-67cbdb7bcd9b/PARTNROFF=1 hashtree=PARTUUID=f37d1afa-50b8-c048-8794-67cbdb7bcd9b/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=dc79ba6081d47280691fb1678a451a0d4b43cbaa salt=a5477f4c74b1173d9f833c4ffb07d3ebf69717ae1e5fb300c1c8d6ab4addf367" noinitrd vt.global_cursor_default=0 kern_guid=f37d1afa-50b8-c048-8794-67cbdb7bcd9b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
> Build Date: 02 November 2016  10:06:10PM
> xorg-server 2:1.18.4-0ubuntu0.2 (For technical support please see http://www.ubuntu.com/support) 
> Current version of pixman: 0.33.6
>         Before reporting problems, check http://wiki.x.org
>         to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
>         (++) from command line, (!!) notice, (II) informational,
>         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu May 17 12:26:06 2018
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
> (EE) 
> Fatal server error:
> (EE) no screens found(EE) 
> (EE) 
> Please consult the The X.Org Foundation support 
>          at http://wiki.x.org
>  for help. 
> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
> (EE) 
> Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist
> 
> (EE) Server terminated with error (1). Closing log file.
> /usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> /usr/bin/xinit: server error
> Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

```

#### Please describe your issue:
I attempt to start Ubuntu Unity through the Chromebook console but it fails and I cannot run the system.

#### If known, describe the steps to reproduce the issue:

1. I open the console (Ctrl+Alt+T).
2. I enter shell.
3. I then attempt to launch Unity with "sudo startunity". It spits out the above stuff in the log. 

```
Is it outdated?

**Comment by xsublinialx** [comment]
This seems to be an easy fix. If crouton has been deleted, try downloading the crouton file from the google link again. Then try to run ``sudo startxfce4``. This should work, as deleting crouton doesn't delete your chroots.
