### ISSUE TITLE
How to delete a Crouton file

### ISSUE THREAD

**Issue by Joshua10115** [dnschneid/crouton#3764]
``` 
/usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it
```

So I tried to download Crouton and halfway I accidentally stopped it I think by pressing enter and then this happened.

E: Method http has died unexpectedly!
E: Sub-process http received signal 4.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

 I tried to download it again but then this happened.

/usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

So I am trying to figrue out the command to delete this and have tried everything! Can anyone show the command to delete it or rename it?

**Comment by DennisLfromGA** [comment]
@Joshua10115,

Just try to update it with: `sudo sh ~/Downloads/crouton -n xenial -u`
Sometimes the `E: Method http has died unexpectedly!` error can be a network glitch I think.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Joshua10115** [comment]
/usr/local/chroots/xenial already exists; updating it...
Enter encryption passphrase for xenial: 
When I do that command this happens. I don't know what to do from there

**Comment by DennisLfromGA** [comment]
@Joshua10115,

You must've used crouton's '-e' option to encrypt your chroot when you installed it.
If you can't remember or don't know the password then you'll probably have to delete it and start over, there's no easy way out.  

Next time if you still want to encrypt it do it after everything's installed successfully with an update.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Joshua10115** [comment]
I was able to delete it am I am currently downloading the file again. Thank you for your help.
