### ISSUE TITLE
is it possible to use `crouton` offline with no internet connection?

### ISSUE THREAD

**Issue by wabarr** [dnschneid/crouton#3765]
I love `crouton`.   I do scientific fieldwork in remote places, and `crouton` allows me to get a powerful data collecting and data analysis machine for very cheap, so thanks!

Is there any way I could restore a `crouton` backup to a machine that has been powerwashed and that isn't connected to the internet?  It seems that the crouton script throws errors immediately in the absence of a network connection....is there any workaround?

Thanks!

**Comment by DennisLfromGA** [comment]
@wabarr,

If you're just restoring a crouton chroot from a backup tarball I don't understand why it would be throwing errors since [it's just uncompressing & untarring it](https://github.com/dnschneid/crouton/blob/master/host-bin/edit-chroot#L427).  If you are trying to update it then it will definitely complain about the absence of a network connection.

*Hope this helps,*
-**DennisLfromGA**

**Comment by wabarr** [comment]
@DennisLfromGA I am new to crouton but this is helping me understand how the different moving parts connect.  The non-networked powerwashed chromebook won't have crouton installed, so I downloaded the crouton install shell script https://goo.gl/fd3zc. The error I was referring to comes from that install script. 

So maybe a better question is: how do I get crouton installed in the absence of a network connection because the typical install script relies on a network. Assume I have an SD card that can be preloaded with whatever files I need.

**Comment by DennisLfromGA** [comment]
@wabarr,

> so I downloaded the crouton install shell script https://goo.gl/fd3zc. The error I was referring to comes from that install script.

I get it now, you're not literally *restoring* a crouton chroot, you're trying to install a new one, that won't work without an internet connection.

> how do I get crouton installed in the absence of a network connection because the typical install script relies on a network. Assume I have an SD card that can be preloaded with whatever files I need.

If you have a working crouton chroot on a system you can perform a backup and store it on external media for restoral and/or portablitity.  Here's a snippet of the `edit-chroot` script usage that pertains to backups and restorals -

```
    -b          Backs up the chroot to a tarball. Compression format is chosen
                based on the tarball extension. Backups always take place before
                other actions on a given chroot.

    -f TARBALL  When used with -b, overrides the default tarball to back up to.
                If unspecified, assumes NAME-yyyymmdd-hhmm.tar[.gz], where .gz
                is included for unencrypted chroots, and not for encrypted ones.
                When used with -r, specifies the tarball to restore from.
                If TARBALL is a directory, automatic naming is still used.

    -r          Restores a chroot from a tarball. The tarball path can be
                specified with -f or detected from name. If both are specified,
                restores to that name instead of the one in the tarball.
                Will not overwrite a chroot when restoring unless -r is
                specified twice.
```

You can back it up with something like this: 

- `sudo edit-chroot -b -f /media/removable/usbstick xenial`

Change the external media location 'usbstick' to the mountpoint name when it's inserted and replace the chrootname if it's different than 'xenial'.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
And to add, one other alternative I didn't mention but should have is copying or moving your chroot from internal storage to external storage.  You can use edit-chroot's '`-m`' or '`-C`' options to accomplish that, see below -
```
edit-chroot [options] name [...]

    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.

    -C DEST     Like -m, but copies instead of moves.
```

And adding to @icecream95's comment, you can also use crouton's '`-b`' option to restore all the host-bin files after a powerwash, etc.
```
   -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
```

*Hope this helps,*
-**DennisLfromGA**
