### ISSUE TITLE
Crosh prompt missing

### ISSUE THREAD

**Issue by econcrank** [dnschneid/crouton#3766]
```
NA
```

#### Please describe your issue:

I just updated my chromebook but now the prompt is missing in the  crosh screen and can't execute shell.

**Comment by DennisLfromGA** [comment]
@econcrank,

Yup, it's temporarily broken in CrOS on the dev channel, maybe on other channels too.

See this Pixelbook forum topic for more details and some workarounds -
- [Terminal Wont Work](https://productforums.google.com/forum/#!topic/pixelbook/TAVP_QDujtw;context-place=topicsearchin/pixelbook/crosh)

*Hope this helps,*
-**DennisLfromGA**

**Comment by econcrank** [comment]
Thank you
