### ISSUE TITLE
Is Ubuntu 18.04 Supported in crouton?

### ISSUE THREAD

**Issue by NanhuGITHUB** [dnschneid/crouton#3768]
#### Please describe your issue:

Just Asking

**Comment by DennisLfromGA** [comment]
@NanhuGITHUB,

No, not quite yet but "it may work with some effort", see below for release support status -
```
chronos@localhost ~ $ crouton -r list
Downloading latest crouton installer...
################################################################################################################## 100.0%################################################################################################################## 100.0%
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch buster sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety! zesty! artful* bionic*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```
*Hope this helps,*
-**DennisLfromGA**

**Comment by NanhuGITHUB** [comment]
OK. I'd Just Go Debain.

**Comment by jpivarski** [comment]
@DennisLfromGA I've been checking `-r list` for a few weeks now. Is there a schedule for when it's expected to be supported? I'm happy enough to wait; I'm just asking if there's a better way to follow its progress than manually polling. Thanks!

**Comment by DennisLfromGA** [comment]
@jpivarski,

Nope, I don't think there's a better way to check at the moment, wish there was.
I haven't heard about any plans from the devs but that doesn't mean they don't have one/any.

If I hear anything about it I'll report those findings back here.

-**DennisLfromGA**

**Comment by bahaaaldin214** [comment]
when do you think 18.04 will be supported?

**Comment by NanhuGITHUB** [comment]
Next month maybe
