### ISSUE TITLE
Error Updating Chroot

### ISSUE THREAD

**Issue by CamdynS-CBC** [dnschneid/crouton#3770]
Hello there, 

Thanks to Denny L. for guiding me. 

```
Please paste the output of the following command here: sudo edit-chroot -all

Command modified since using 32 GB SanDisk USB Drive:

crosh> shell
chronos@localhost / $ sudo edit-chroot -all -c "/media/removable/USB Drive/chroots/"
name: xenial
encrypted: no
Entering /media/removable/USB Drive/chroots/xenial...
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,xfce-desktop,cli-extra,keyboard,chrome
host: version 10754.0.0 (Official Build) canary-channel wolf 
kernel: Linux localhost 3.8.11 #1 SMP Tue Jun 5 04:16:38 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /media/removable/USB Drive/chroots/xenial as another instance is using it.
chronos@localhost / $ 


I have Crouton open while executing command above. 

```

#### Please describe your issue:
Trying to update chroot, spits out following error. 

![screenshot 2018-06-05 at 2 07 00 pm](https://user-images.githubusercontent.com/37196963/41010979-2b54d3c2-6900-11e8-9f84-6d9de7d06d4b.png)

Chrome OS is on the Canary Channel, Version: 69.0.3449.0 (Official Build) canary (64-bit)

#### If known, describe the steps to reproduce the issue:

- USB Drive w/ Crouton
- Attempt updating chroot
- Error

-------------------------------------------------------------------------------------------

Let me know if I can do anything else for you, if more info. is required. 

-Camdyn-

**Comment by DennisLfromGA** [comment]
Closing, please track on issue: https://github.com/dnschneid/crouton/issues/3811
