### ISSUE TITLE
Debootstrap download error

### ISSUE THREAD

**Issue by caillonantoine** [dnschneid/crouton#3772]
Hi,

I'm trying to install crouton on a **SAMSUNG 303C** chromebook by typing
```
sudo sh ~/Downloads/crouton -t e17
```
and an error message is being displayed:

```
Installing xenial-armhf chroot to /usr/local/chroots/xenial
Downloading debootstrap 1.0.92~bpo9+1...
################################################################################################################################################ 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Failed to download debootstrap.
Check your internet connection or proxy settings and try again.
```

I can access ftp.debian.org without any problem. Can anyone tell me how to proceed to make it work? Thanks

**Comment by DennisLfromGA** [comment]
The latest commit to crouton has some improved logic to print the debootstrap.log on errors.
If you haven't tried this again recently you might want to and see if it works or, if not, if the error messages will tell you a little more about what's going on.

*Hope this helps,*
-**DennisLfromGA**

**Comment by caillonantoine** [comment]
Hi,

Thanks, but I can't figure out where the log is? I've tried the solutions you proposed at #3620 but none of them are working.

**Comment by DennisLfromGA** [comment]
According to the script source, it will use a subdirectory in `/tmp` -

- ` tmp="`mktemp -d --tmpdir=/tmp "$APPLICATION.XXX"`"`

And a subfirectory under that based on the architecture & release -

- `subdir="$RELEASE-$ARCH"`

So just start searching from a CrOS shell session in `/tmp` for something along those lines, maybe using this would work -

- `sudo find /tmp -type f -name 'debootstrap.log' -ls`

*Hope this helps,*
-**DennisLfromGA**

**Comment by caillonantoine** [comment]
Nothing in ```/tmp``` nor with ```find```... Is there any possibility to download **debootstrap** manually?

**Comment by DennisLfromGA** [comment]
Yes'ish, if you take a look at crouton's options you'll see -
```
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by caillonantoine** [comment]
I've downloaded some tarball from ```ftp.debian.org```, still does'nt work, I really don't know what to do anymore... Don't know if the problem is coming from my computer of from the script? Is anyone able to install crouton now?

**Comment by caillonantoine** [comment]
Hi,

I managed to install crouton by changing a line in ```installer/ubuntu/bootstrap```, from

```debootstrap_version="1.0.92~bpo9+1"```

to

```debootstrap_version="1.0.89~bpo8+1"```


It seems like debootstrap version 1.0.92 isn't available anymore on ```ftp.debian.org```. Now crouton is working just fine.

Thanks for your help!

**Comment by DennisLfromGA** [comment]
@caillonantoine,

Thanx for troubleshooting this issue and providing a workaround.

Since it will still present problems for some I'm going to keep this open until the devs have a chance to investigate.

-**DennisLfromGA**

**Comment by caillonantoine** [comment]
No problem! Thanks for your time!

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the debootstrap problem.
You can do a quick test with something like the following: crouton -r xenial -d -f xenial.bs

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....

Please re-open this issue if it's not fixed and give us some more details.

-DennisLfromGA
