### ISSUE TITLE
Does crouton-integration extension do anything when not in Chrome OS?

### ISSUE THREAD

**Issue by trusktr** [dnschneid/crouton#3773]
Just curious, as when I'm in macOS or Windows I see the Crouton integration icon in my Chrome window, but I don't need it in those OSes. Ideally I'd like to turn it on only in Chrome OS, but there doesn't seem to be an option for that. Maybe I just have to load it as an unpacked extension in Chrome OS so it doesn't sync to other OSes (just guessing that this works).

**Comment by DennisLfromGA** [comment]
There's no built-in switch on that extension but you can disable it in chrome://extensions or use the [Extensity](https://chrome.google.com/webstore/detail/extensity/jjmflmamggggndanpgfnpelongoepncg) extension to toggle on/off any one or all of your extensions, it's very handy.

*Hope this helps,*
-**DennisLfromGA**
