### ISSUE TITLE
Problems starting Linux, Please Help.

### ISSUE THREAD

**Issue by gabedj2** [dnschneid/crouton#3774]
This problem happened to me several months ago when i tried to install linux, I just retried it and the same problem occured. Heres all the code right after i do sudo startxfce4-

Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-101-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon May 14 23:05:58 PDT 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=f087c549-d73b-7740-829e-3cda57c258b9/PARTNROFF=1 hashtree=PARTUUID=f087c549-d73b-7740-829e-3cda57c258b9/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=c6c6c5a5ff5f4cb3191c0cdeb30e8860b7a32bc3 salt=74c80ef06accc7cb07e578f6a0ffd1277170d2020b31a943544e52a9d833eb41" noinitrd vt.global_cursor_default=0 kern_guid=f087c549-d73b-7740-829e-3cda57c258b9  
Build Date: 24 November 2017  09:45:24AM
xorg-server 2:1.19.5-0ubuntu2~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jun  7 02:41:55 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1528364515.715905 sender=:1.41 -> destination=:1.53 serial=468 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1528364516.253891 sender=:1.41 -> destination=:1.55 serial=470 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by bjpafa** [comment]
Cff c NH ih

**Comment by CamdynS-CBC** [comment]
It seems a similar issue is being discussed here: https://github.com/dnschneid/crouton/issues/3753

_**Hope this helps,**_
-CamdynS-
