### ISSUE TITLE
Chromebook freezes with crouton active

### ISSUE THREAD

**Issue by edgreenberg** [dnschneid/crouton#3775]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180329190032~master:d287904a
release: xenial
architecture: amd64
xmethod: xorg
targets: lxde-desktop,chrome,cli-extra,touch
host: version 10452.99.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-17028-g3f022007a1b8 #1 SMP PREEMPT Tue May 29 21:54:09 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

Several times now, Chromebook freezes when switching BACK to crouton.  Black screen. Mouse pointer and keyboard unresponsive, can't switch back.  Only way out is the hold power until shutdown.

#### If known, describe the steps to reproduce the issue:

Intermittant:
1. start crouton environment from crosh > shell.  
2. switch back to android screen
3. hang out and do some browser work (read the comics, etc)
4. switch back to crouton and voila.

**Comment by DennisLfromGA** [comment]
Do the <kbd>fullscreen/F3</kbd> or <kbd>switch window/F4</kbd> keys help at all?

When it hangs maybe try switching to VT2 using:
- <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F2</kbd> 

Then immediately switch back with:
- <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F1</kbd>

And see if that *unhangs* it.

You could also try adding the 'xiwi' target/xmethod as a workaround.

*Hope this helps,*
-**DennisLfromGA**
