### ISSUE TITLE
failed to complete chroot setup

### ISSUE THREAD

**Issue by elovald** [dnschneid/crouton#3779]
```E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/lm-sensors/libsensors4_3.4.0-2_amd64.deb  Connection failed [IP: 91.189.88.161 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Acer Chromebook failed to complete chroot setup

**Comment by elovald** [comment]
the only response to any prompt tried is "bash: command not found"

**Comment by DennisLfromGA** [comment]
@elovald,

Sorry, to be clear the above '`sudo`' commands need to be run *in your chroot*, that's after you run '`sudo enter-chroot`.

*Hope this helps,*
-**DennisLfromGA**

**Comment by datkeydo2** [comment]
@DennisLfromGA 

I am receiving these issues with kali-rolling,

Installing CRAS...
/prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.



i am not a expert at this type of situation by the way.

**Comment by DennisLfromGA** [comment]
@datkeydo2,

That's a different issue than the OPs I believe.
There's a PR #3955 to fix this issue but it hasn't been reviewed and merged yet, hopefully soon.

Hope this helps,
-DennisLfromGA

**Comment by alex-xy** [comment]
Bien aqui esta lo que me funciono almenos a mi (ESTE METODO SOLO ME HA FUNCIONADO EN XFCE/XFCE4)

1- cuando te de el error entre en el chroot ( sudo enter-chroot) te pedira renudar el setup
2 -cuando lo anterior termine te dara error ejecuta este comando ¨"sudo sh -e ~/Downloads/crouton -n xenial -u ¨ + enter 
3- cuando termine te dara error denuevo y devuelta entra al chroot ¨ sudo enter-chroot¨
4- ya en este punto te pedira tu registro de usuario  creas tu user y cuando ya lo ayas completado le das exit y ya puedes ejecutar ¨sudo startxfce4¨ para arrancar el sistema
espero haberlos ayudado ya que este bug/error es muy molesto espero le aya  servido ;)

**Comment by Anurag0070** [comment]
same problem failed to comlete chroot setup
