### ISSUE TITLE
crouton update fails due to MySQL not running

### ISSUE THREAD

**Issue by pshotton** [dnschneid/crouton#3784]
```
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,unity-desktop,extension,audio,chrome,cli-extra,keyboard,touch,unity
host: version 10718.13.0 (Official Build) dev-channel eve 
kernel: Linux localhost 4.4.132-14136-g8f69237c056d #1 SMP PREEMPT Mon Jun 4 22:24:49 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes```

#### Please describe your issue:
sudo sh ~/Downloads/crouton -u -n xenial fails because I have MySql installed, and the post-install hooks require mysqld to be running. However the service start fails because policy-rc.d in a chroot environment.
I tried to change policy-rc.d but it gets overwritten on the update.

The only way to finish the update that I've found is to enter the chroot responding N to the 'continue update' question, start mysqld, and then run the update script.

To reproduce:
Have a chroot with mysql installed, and run crouton -u when there are pending updates to mysql.

**Comment by DennisLfromGA** [comment]
@pshotton,

You mentioned `policy-rc.d` but I'm wondering if anything 'mysql' related is launched from `/etc/rc/local`?

If so you could just comment that part out, exit, then do the update.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pshotton** [comment]
The problem is that in the update there was an update to mysql - which requires mysql to be running to do the configuration update.

I've found a workaround:
attempt the update (it will fail updating mysql)
then run sudo enter-chroot
It will inform you that the update failed and ask if you want to re-run it. Answer 'n'.
You'll then be at a shell prompt inside the chroot. Start mysql in the usual way. Then continue the update by running sudo /prepare.sh

The update should now run to completion
