### ISSUE TITLE
How can I disconnect the crouton web extension?

### ISSUE THREAD

**Issue by sidharthmrao** [dnschneid/crouton#3786]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20180611074759~master:3697b784
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,unity
host: version 10575.54.0 (Official Build) beta-channel edgar 
kernel: Linux localhost 3.18.0-17554-g9194949d4df2 #1 SMP PREEMPT Tue Jun 5 18:05:38 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: amd64
xmethod: xorg
targets: x11,xorg,xfce
host: version 10575.54.0 (Official Build) beta-channel edgar 
kernel: Linux localhost 3.18.0-17554-g9194949d4df2 #1 SMP PREEMPT Tue Jun 5 18:05:38 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

I am trying to remove the crouton web extension by removing xiwi, but 
it won't let me. Is there any way I can remove xiwi from unity (trust) or delete unity
and install gnome?

**Comment by sidharthmrao** [comment]
If I try to install gnome without uninstalling unity (sudo sh ~/Downloads/crouton -t gnome), this is what comes up:

/usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

If I use -u instead of -t, it gives me a really long message about -b, -d, -e, etc and what they do.

**Comment by DennisLfromGA** [comment]
@sidharthmrao,

There is no provision to remove a target/xmethod currently, you will probably have to get into your chroot using '`sudo enter-chroot -n xenial`' and then edit both '`/.crouton-targets`' & '`/etc/crouton/targets`' **as root** to remove the 'xwi' entries in those files.

Then you can replace the xiwi target/xmethod with xorg by doing a crouton update using something like:

- `sudo sh ~/Downloads/crouton -n xenial -t xorg -u`

'xiwi' will still be present but won't be used or updated any longer with this workaround.
You can also disable or remove the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension if you like.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@sidharthmrao,

The command you entered '`sudo sh ~/Downloads/crouton -t gnome`' will try to install a new 'xenial' chroot without the '-u' option.  To add the plain vanilla 'gnome' target (approx. 400MB) or the 'gnome-desktop' target (approx. 1100MB) use something lke this:

- `sudo sh ~/Downloads/crouton -n xenial -t gnome[-desktop] -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by sidharthmrao** [comment]
I was able to use 'sudo enter-chroot -n xenial' but when I entered /.crouton-targets into the shell it gave me the error:
(xenial)sidharthmrao@localhost:~$ /.crouton-targets
-su: /.crouton-targets: Permission denied
(xenial)sidharthmrao@localhost:~$ /usr/local/chroots/xenial already has stuff in it!
-su: /usr/local/chroots/xenial: No such file or directory
(xenial)sidharthmrao@localhost:~$ Either delete it, specify a different name (-n), or specify -u to update it.

**Comment by sidharthmrao** [comment]
I was successfully able to install gnome though.

**Comment by DennisLfromGA** [comment]
@sidharthmrao,

> I was able to use 'sudo enter-chroot -n xenial' but when I entered /.crouton-targets into the shell it gave me the error: ...

You were attempting to *execute* the file with that command, it won't work.
I said you need to *edit the files as root*, that means use your favorite editor and delete the 'xiwi' entries.
Something like the following should work, I use 'vi' but you can use 'nano' or the editor of your choosing:

1. `sudo enter-chroot -n xenial`
2. `sudo vi /.crouton-targets`
3. `sudo vi /etc/crouton/targets`
4. `exit`

*Hope this helps,*
-**DennisLfromGA**

**Comment by sidharthmrao** [comment]
When sudo asks me for a password, I enter the password I set but it doesn't work.

**Comment by DennisLfromGA** [comment]
@sidharthmrao,

> Is there any way to reset my password?

See: [How do I change my password in Linux?](https://stackoverflow.com/questions/9596108/how-do-i-change-my-password-in-linux)

You may need to bone up on your Linux skilz a little, Google is your friend for that....

*Hope this helps,*
-**DennisLfromGA**

**Comment by sidharthmrao** [comment]
Sorry, but the sudo password still doesn't work, so I will probably just powerwash unless there is another way. Like I said, I forgot my sudo password (or the computer made a mistake, which I doubt) so I can't use 'passwd' to reset it.

**Comment by sidharthmrao** [comment]
Thank you for all your help though.

**Comment by DennisLfromGA** [comment]
@sidharthmrao,

Make sure you know which user's password the application is asking for.
If it's the 'root' or 'administrative user' password that it's asking for there isn't one set by default so you may need to assign one, but that's unusual.

If you're talking about the password for the username you created in the chroot when you installed it you can get into the chroot as root and change it if that would be easier. 

If you need more help with this let me know.

Also, there is no need to powerwash, that's a pretty drastic step and not at all necessary.
You can delete the entire chroot and reclain all the space with a simple command and then start over if you like.  To delete the your chroot use this:

- `sudo delete-chroot xenial`

*Hope this helps,*
-**DennisLfromGA**
