### ISSUE TITLE
Youtube stop working on chromebook after loading ubuntu 16.04 unity

### ISSUE THREAD

**Issue by melc** [dnschneid/crouton#3787]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10718.13.0 (Official Build) dev-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Jun 4 22:23:33 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
There are two issues.
1) Youtube on dell chromebook 7310 stops working after login to ubuntu 16.04 unity.  
2) Cras is missing on both sound input and output. The sound icon is on disable, can't be enabled. 

#### If known, describe the steps to reproduce the issue:
I downloaded and installed the latest version of crouton.  Several issues arise. 
1) Youtube on chromebook main screen stops working after loading ubuntu 16.04 by typing "sudo startunity".  Youtube is on blank screen with error message "An error occurred. please try again later".  After exiting ubuntu 16.04 unity, youtube starts working. 
2) cras is missing from both sound input and output.  The sound icon is on disable, can't be enabled.  When I installed and opened ubuntu 16.04 unity first time, I saw cras there but the sound icon was disabled.
3) try "sudo restart cras", not working.

**Comment by melc** [comment]
Powerwash the chromebook and reinstall with the latest version.  Now the ubuntu screen is blank.

**Comment by melc** [comment]
**Solution:**

1) Update your crouton to the latest version, "sudo sh ~/Downloads/crouton -u"

2) Check if the sound card is installed successfully, (issue #2015)
2a) Launch the command, "cat /proc/asound/cards", the example output looks like,
```
 0 [MID            ]: HDA-Intel - HDA Intel MID
                      HDA Intel MID at 0xe0510000 irq 60
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xe0514000 irq 61
```
2b) Run the command, "alsamixer". On top left of the screen, it looks like,
```
Card: Cras
Chip: Cras
View: f3 [Playback]
Item: Master
```  
2c) Install pulseaudio package by running the command, "sudo apt-get install pulseaudio"

3) Launch the command "sudo enter-chroot", then check if the sound is working by running the command "aplay -Dcras /usr/share/sounds/alsa/Front_Center.wav" 

4) If you hear the voice "front", the sound card is still not working, run the command "sudo sysctl fs.inotify.max_user_watches=1048576" (issue #3553)

if it is still not working, I have no solution for you. :-(

**Comment by melc** [comment]
**Solution:**

1) Update your crouton to the latest version, "sudo sh ~/Downloads/crouton -u"

2) Check if the sound card is installed successfully, (issue #2015)
2a) Launch the command, "cat /proc/asound/cards", the example output looks like,
```
 0 [MID            ]: HDA-Intel - HDA Intel MID
                      HDA Intel MID at 0xe0510000 irq 60
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xe0514000 irq 61
```
2b) Run the command, "alsamixer". On top left of the screen, it looks like,
```
Card: Cras
Chip: Cras
View: f3 [Playback]
Item: Master
```  
2c) Install pulseaudio package by running the command, "sudo apt-get install pulseaudio"

3) Launch the command "sudo enter-chroot", then check if the sound is working by running the command "aplay -Dcras /usr/share/sounds/alsa/Front_Center.wav" 

4) If you hear the voice "front", the sound card is still not working, run the command "sudo sysctl fs.inotify.max_user_watches=1048576" (issue #3553)

if it is still not working, I have no solution for you. :-(

**Comment by DennisLfromGA** [comment]
Usually steps 1 &sometimes 2c will fix most audio but thanx for the other troubleshooting steps and details.

-**DennisLfromGA**
