### ISSUE TITLE
No Menubar, Launcher, and Top Panels (Blank Screen) on Ubuntu Xenial (16.04) Unity Desktop

### ISSUE THREAD

**Issue by melc** [dnschneid/crouton#3788]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
No menubar, launcher, and top panels after installing the latest version of crouton on ubuntu xenial (16.04 LTS) unity.

#### If known, describe the steps to reproduce the issue:
1) Chrome was updated to the version 68
2) Powerwash the chromebook dell 13 7310
3) Downloaded the latest version of crouton from https://goo.gl/fd3zc.
4) Installed ubuntu xenial unity by running the command, "sudo sh ~/Downloads/crouton -t unity"

**Comment by melc** [comment]
**Solution:**
1) Create a Chrome OS recovery usb drive by downloading and launching "Chromebook Recovery Utility" from chrome extensions tools.
2) Insert the recovery usb drive into your chromebook, follow the instruction.  
3) Download crouton from http://goo.gl/fd3zc
4) Install crouton by running the command, "sudo sh -e ~/Downloads/crouton -t unity"

if you have issues on media (no sound), follow the closed issue #3787

**Comment by DennisLfromGA** [comment]
You must've been on the 'beta' channel when things started going sideways:

![screenshot 2018-06-29 at 2 13 25 pm](https://user-images.githubusercontent.com/3418772/42107807-aee09a88-7ba6-11e8-96ea-e861f64d5830.png)

Another solution would be to move back to the 'stable' channel which requires a powerwash and not a full recovery.

*Hope this helps,*
-**DennisLfromGA**

**Comment by perryraskin** [comment]
Can we reopen this? I’m on v67 on an Asus C302, and I’m having the same issue. Driving me crazy.

**Comment by melc** [comment]
If the above solution can't solve your issues, an useful website may help you figure out.
[https://itsfoss.com/how-to-fix-no-unity-no-launcher-no-dash-in-ubuntu-12-10-quick-tip/](url)

1. Go to the command line interface,  
`sudo enter-chroot`

2. Execute the following commands.
`sudo apt-get update
sudo apt-get install --reinstall ubuntu-desktop
sudo apt-get install unity
sudo shutdown -r now` 

3. Execute the following command if step 2 is not working.
`mv ~/.config ~/.config_backup
sudo shutdown -r now`

4. Execute the following command if step 3 is not working.
`rm -rf .compiz-1
sudo shutdown -r now`

**Comment by Dulanic** [comment]
This seems to be a common issue /w the Asus C302. I have the same problem. We have no CLI to run those commands and terminal won't open.

**Comment by WTLM2013** [comment]
Didn't work for me on the c720. Any other work around?

**Comment by DennisLfromGA** [comment]
@Dulanic,

> We have no CLI to run those commands and terminal won't open.

You can open a shell session in your chroot by entering: 

- `sudo enter-chroot [-n chrootname]`

Then perform the workaround @melc [mentioned above](https://github.com/dnschneid/crouton/issues/3788#issuecomment-441898328).

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
I just installed the `unity-desktop` target in my xenial chroot to test this and it seems to work for me.

Using `xiwi-tab` -
![Screenshot_2019-04-11_22-34-24](https://user-images.githubusercontent.com/3418772/56008882-cc675d80-5cab-11e9-9790-591f47b2d4fe.png)

Using `xorg` -
![Screenshot_2019-04-11_22-36-18](https://user-images.githubusercontent.com/3418772/56008905-dbe6a680-5cab-11e9-93cd-89c79c05977a.png)

Occasionally I have to toggle 'overview mode' to get the desktop to display correctly -
> Enter Overview mode <kbd>[]</kbd>, which shows all windows

When all else fails try updating your chroot with: 

- `sudo crouton -u [-n chrootname]`

*Hope this helps,*
-**DennisLfromGA**

**Comment by casheta** [comment]
@DennisLfromGA 
If you are kind, please help me.
So i installed Croton, it start but the desktop freezes .
I tried to update , i installed and reinstalled for more than 10 time.
I tried every command that i got and i really want to try out this.
![59961593_305043320377841_2338029854907170816_n](https://user-images.githubusercontent.com/50510914/57565666-8e547b00-73ca-11e9-8dcf-e443ff01dae4.jpg)
![60559155_410064702910064_631251753177710592_n](https://user-images.githubusercontent.com/50510914/57565667-8e547b00-73ca-11e9-9997-0ce67d9adab5.jpg)

**Comment by WTLM2013** [comment]
Still not working on my C720, plus this is now effecting every target I install.
I have had no issues with my Toshiba CB 2 which has plain old unity installed.

**Comment by WTLM2013** [comment]
Contents of sudo edit-chroot -all:
`name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 12105.25.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu May 2 00:34:31 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes`

I done the recovery with no issues, I followed all of the steps as listed (with the only exception being `sudo shutdown -r now` as it is disabled) with no success. Any other suggestions other than restarting with the shutdown command enabled?

**Comment by DennisLfromGA** [comment]
@WTLM2013,

> Any other suggestions other than restarting with the shutdown command enabled?

The `shutdown -r now` step only does a shutdown and reboot which you can accomplish by just logging out of the chroot and rebooting your Chromebook. I'm not sure a reboot is really necessary for the changes though but I guess it can't hurt.

It may be just be an issue with unity and some wonkiness in dev 😵 

My eve is running the same version of crouton but I'm on the beta channel, not dev *and* I'm using the full unity meta-package that you get with the `unity-desktop` target, not the plain vanilla `unity` target -
```
name: xenial
encrypted: no
Entering /var/crouton/chroots/xenial...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xiwi
targets: unity-desktop,xiwi,xorg,gnome-desktop,lxde-desktop,xfce-desktop,cli-extra,keyboard,touch,chrome-beta
host: version 12105.31.0 (Official Build) beta-channel eve 
kernel: Linux localhost 4.4.178-16492-g4245c5e16521 #1 SMP PREEMPT Mon May 6 00:52:10 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

But as for as other suggestions I think I would try adding the `xiwi` xmethod and/or using one or more other desktop targets, I prefer lxde but you may like something else.

*Hope this helps,*
-**DennisLfromGA**

**Comment by ericsong1911** [comment]
Here is a possible fix:
First, do `sudo chroot-enter`
Then, run the following commands:
```
sudo apt-get update
sudo apt-get install –reinstall ubuntu-desktop
sudo apt-get install unity
rm -rf ~/.cache/compizconfig-1
sudo shutdown -r now
```

Hope this helps!

**Comment by mrjohnc** [comment]
Also have this issue on Lenovo Yoga Chromebook

**Comment by jamesMFelder** [comment]
I also had this problem on a fresh install.
`rm -r ~/.config`
worked for me.

**Comment by vodot** [comment]
Just had same issue on my i7 Pixelbook.
`rm -r ~/.config`
worked for me.
