### ISSUE TITLE
Failed to run debootstrap on Samsung CB 3

### ISSUE THREAD

**Issue by MyNameIsEZ** [dnschneid/crouton#3790]
```
Please paste the output of the following command here: N/a
```

#### Please describe your issue:
When attempting to install a new chroot enviroment on my Samsung CB 3 it gives the output "Failed to run debootstrap".
sudo sh -e ~/Downloads/crouton -r kali-rolling -t cli-extra -n cli
(I want to install a kali rolling CLI as a new chroot). I have tried installing several different distros and even powerwashed my device a few times, but every time it give the same output. I even tried searching it on the internet, but all the results have nothing to do with what I'm looking for. Is this the first time something like this occurs?
#### If known, describe the steps to reproduce the issue:
My input command was:
sudo sh -e ~/Downloads/crouton -r kali-rolling -t cli-extra -n cli
but I tried the following too:
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce -n kali
And
sudo sh -e ~/Downloads/crouton -r kali-rolling -t gnome

**Comment by drinkcat** [comment]
Can you please provide the full command output?

**Comment by MyNameIsEZ** [comment]
Hi,
I'll get back to you later. I'm not currently at my laptop.

**Comment by MyNameIsEZ** [comment]
Hi drinkcat,

It seems to work perfectly fine now.
Thanks for the concern.
