### ISSUE TITLE
Cannot mount crouton after update to 67.0.3396.87

### ISSUE THREAD

**Issue by pclerie** [dnschneid/crouton#3792]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/bionic/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...

#### Please describe your issue:

Above is pretty much my issue.

The machine was upgraded today and boom! no crouton. 

Version installed: Version 67.0.3396.87 (Official Build) (64-bit)
Platform: 10575.55.0 (Official Build) stable-channel cave
Firmware: Google_Cave.7820.347.0
Machine is: Asus C302C

 Thanks

**Comment by pclerie** [comment]
Please ignore. It's working fine this morning.

I swear these things have moods! :-)

**Comment by DennisLfromGA** [comment]
You probably just weren't holding your mouth right. 😁

![image](https://user-images.githubusercontent.com/3418772/42114058-a5b7b724-7bbb-11e8-9130-c1a2b1adfad2.png)
