### ISSUE TITLE
symlinks broken in /mnt/stateful_partition/crouton/shared mounts

### ISSUE THREAD

**Issue by beadsland** [dnschneid/crouton#3794]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,xorg,unity,touch,extension,xiwi
host: version 10575.55.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-17554-g9194949d4df2 #1 SMP PREEMPT Mon Jun 11 23:51:40 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:

I have my crouton home directory under /mnt/stateful_partition/crouton/shared, mounted within the chroot via /etc/crouton/shares. Have been working with this configuration the better part of a year without issue.

Today, I noticed the ChromeOS update indicator just as I powered off. When I powered back on, I kicked up startunity and immediately found that all the symlinks I rely on were throwing permission denied.

Have confirmed that this is an issue on the ChromeOS side, as symlinks created under /mnt/stateful_partition/crouton/shared likewise throw permission denied. I did try running a crouton -u repair, just to be completist, but the problem persists.

Googling turns up a discussion about hardening ChromeOS against symlink attacks via stateful partition (so perhaps a security measure in the latest update?). Yet symlinks in the rest of crouton (also under stateful_partition) work fine when poked and prodded.

Ideas? Work arounds? Something obvious I've missed?

**Comment by beadsland** [comment]
ls -l
`total 0`
ls -al
```
total 16
drwxrwxr-x.  2 beads beads  4096 Jun 21 22:43 .
drwxr-xr-x. 84 beads beads 12288 Jun 21 22:41 ..
```
touch hello
ln -s hello world
ls world
`ls: cannot access 'world': Permission denied`
ls -al
```
total 16
drwxrwxr-x.  2 beads beads  4096 Jun 21 22:43 .
drwxr-xr-x. 84 beads beads 12288 Jun 21 22:41 ..
-rw-rw-r--.  1 beads beads     0 Jun 21 22:43 hello
lrwxrwxrwx.  1 beads beads     5 Jun 21 22:43 world -> hello
```
pwd
`/home/beads/hmm`
ln -s /home/beads/hmm/hello folks
ls folks
`ls: cannot access 'folks': Permission denied`
ls -al
```
total 16
drwxrwxr-x.  2 beads beads  4096 Jun 21 22:44 .
drwxr-xr-x. 84 beads beads 12288 Jun 21 22:41 ..
lrwxrwxrwx.  1 beads beads    21 Jun 21 22:44 folks -> /home/beads/hmm/hello
-rw-rw-r--.  1 beads beads     0 Jun 21 22:43 hello
lrwxrwxrwx.  1 beads beads     5 Jun 21 22:43 world -> hello
```

**Comment by phummel** [comment]
I was having this issue show up with a mounted sdcard mounted to /opt. I had to unmount the sdcard inside my active crouton session, change the fs.protected_symlinks=0, and then remount the sdcard. Then I was able to follow symlinks or change their permissions.
