### ISSUE TITLE
Suspending AIGLX clients for VT switch

### ISSUE THREAD

**Issue by nickpitlosh** [dnschneid/crouton#3796]
Im sure you are aware that x clients are suspended when you are in chrome. I would like to turn that off and let the xclients run free.

Please tell me your secrets.

**Comment by DennisLfromGA** [comment]
Can you please expound on that a bit?
Whose secrets do you hope to unveil?

-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
I'm sure I don't know, maybe one of the devs or someone else with a lot more knowledge will see this and drop in.

-**DennisLfromGA**
