### ISSUE TITLE
Log out of trusty returns to blank screen

### ISSUE THREAD

**Issue by duranzaf** [dnschneid/crouton#3797]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20180611074759~master:3697b784
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce,keyboard
host: version 10575.55.0 (Official Build) stable-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Jun 11 23:53:28 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: trusty1
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty1...
crouton: version 1-20171109145451~master:35a16889
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 10575.55.0 (Official Build) stable-channel auron_paine 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Jun 11 23:53:28 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty1...
```

#### Please describe your issue:
Unable to return to chrome via shift ctrl alt arrow and logout returns to black screen and system hangs

#### If known, describe the steps to reproduce the issue:
OS 67.0.3396.87 open terminal, shell, sudo startxfce4

Two days ago was not able to enter ubuntu at all, then did a crouton update and it worked fine. Was able to go back and forth using shortcut keys. Today firefox acted strange and kept scrolling and refreshing so that I lost cursor. Rebooted and updated crouton again. Now I can enter ubuntu but it's welcome Hotel California time.

thanks for any guidance.
Francis

**Comment by duranzaf** [comment]
Hopefully I haven't wasted someone's valuable time yet. I had experienced the lock up repeatedly. I did now read "Common issues and reporting" and noticed that I had not fetched a fresh installer. So I did and ran with the -u flag again. I am now able to use the shortcut keys. However, I suspect I may still have issues, since going back and forth between chrome and ubuntu had worked initially even though I had updated using a Nov 2017 version of crouton.

I will attempt to fix the issues i see and then close in case someone does read this and is aware of some other problem that may have caused the no return to chrome problem. i will try attaching the Xorg.crouton.1.log file.

**Comment by DennisLfromGA** [comment]
I haven't run into this but just wondering if you still experience the issue if you switchto CrOS from a command-line in the chroot using: 
- `croutoncycle cros` 

*Hope this helps,*
-**DennisLfromGA**

**Comment by the-reallist** [comment]
Hi duranzaf, I'm having the same issue on an Acer CB5-571 running xenial with xfce4 and lxde. Logging out of the chroot also brings me to a black screen. However, (since my terminal under ChromeOS is by default still the window in focus) pressing the up arrow key to recall the last command to fire up my chroot's DE and pressing enter does successfully restart xfce. 

This tells me it's simply a matter of the chroot stealing display ownership from ChromeOS when xfce starts. I'm not aware of a way to prevent such aggressive behavior, but hopefully this helps isolate the root cause of the issue.
