### ISSUE TITLE
sudo startxfce4 will not start linux on my chromebook! please help!

### ISSUE THREAD

**Issue by volitivetitan32** [dnschneid/crouton#3798]
When i type sudo startxfce4 , it gives me this message:

chronos@localhost / $ sudo startxfce4
Password: 
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
mv: cannot stat '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/run/dri/card*': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 
please help!!

**Comment by qcu** [comment]
YMMV, however the workaround posted in #3799 may help while this issue is being addressed.
