### ISSUE TITLE
Xenial chroot broken after Version 67.0.3396.87 (Official Build) (64-bit) update

### ISSUE THREAD

**Issue by brianmingus** [dnschneid/crouton#3799]
After the most recent ChromeOS update today my chroot is broken :(

Version 67.0.3396.87 (Official Build) (64-bit)

```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

**Comment by qcu** [comment]
The path prefix `/var/run/crouton` in front of `/mnt/stateful_partition/...` is either a bug that appeared in a recent crouton update, or else there was a recent change in file system permissions. 

The following temporary workaround helped in my case. YMMV...

`sudo ln -s /mnt/stateful_partition /var/run/crouton/mnt/stateful_partition`

Note that if you try this workaround, you will want to remove the temporary symbolic link once a permanent fix is available: `sudo rm /var/run/crouton/mnt/stateful_partition`

I was running into a related error message when trying to install a new xenial chroot.

```
...
I: Extracting util-linux...
I: Extracting zlib1g...
Moving bootstrap files into the chroot...
mv: cannot create directory '/var/run/crouton/media/removable/SD32GBext4/chroots/xenial/bin': No such file or directory
mv: cannot create directory '/var/run/crouton/media/removable/SD32GBext4/chroots/xenial/boot': No such file or directory
...
rm: cannot remove '/var/run/crouton/media/removable/SD32GBext4/chroots/xenial': Device or resource busy
```

In the above, `/var/run/crouton` appears to be an erroneous path prefix for `/media/removable...`.

The following temporary workaround helped with a new xenial chroot installation: `sudo ln -s /media /var/run/crouton/media`

Chrome OS Version 68.0.3440.25 (Official Build) dev (32-bit)

**Comment by qcu** [comment]
To this casual user, it appears that the path prefix `/var/run/crouton` in front of `/mnt/stateful_partition/...` is either a bug that appeared in a recent crouton update, or else there was a recent change in file system permissions. 

The following temporary workaround helped in my case. YMMV...

`sudo ln -s /mnt/stateful_partition /var/run/crouton/mnt/stateful_partition`

Note that if you try this workaround, you will want to remove the temporary symbolic link once a permanent fix is available: `sudo rm /var/run/crouton/mnt/stateful_partition`

I was running into a related error message when trying to install a new xenial chroot.

```
...
I: Extracting util-linux...
I: Extracting zlib1g...
Moving bootstrap files into the chroot...
mv: cannot create directory '/var/run/crouton/media/removable/SD32GBext4/chroots/xenial/bin': No such file or directory
mv: cannot create directory '/var/run/crouton/media/removable/SD32GBext4/chroots/xenial/boot': No such file or directory
...
rm: cannot remove '/var/run/crouton/media/removable/SD32GBext4/chroots/xenial': Device or resource busy
```

In the above, `/var/run/crouton` appears to be an erroneous path prefix for `/media/removable...`.

The following temporary workaround helped with a new xenial chroot installation: `sudo ln -s /media /var/run/crouton/media`

Chrome OS Version 68.0.3440.25 (Official Build) dev (32-bit)

**Comment by volitivetitan32** [comment]
Now my screen shows the following:
Build Operating System: Linux 4.4.0-101-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Jun 20 22:38:42 PDT 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=9a5e5f11-1932-7943-b691-6db43fc7d9f3/PARTNROFF=1 hashtree=PARTUUID=9a5e5f11-1932-7943-b691-6db43fc7d9f3/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=703cd1eafdac3944825aa8798986a18ff339c20a salt=dc2a614071c0695ee82b41f015d39f5031ab758800dada901dfb1ca7a5c1d0d3" noinitrd vt.global_cursor_default=0 kern_guid=9a5e5f11-1932-7943-b691-6db43fc7d9f3  
Build Date: 24 November 2017  09:45:24AM
xorg-server 2:1.19.5-0ubuntu2~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jun 22 22:17:27 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1529723848.897985 sender=:1.9 -> destination=:1.52 serial=1064 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1529723849.386870 sender=:1.9 -> destination=:1.54 serial=1066 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

**Comment by secretrow** [comment]
Did you update your chroot? I was also locked out of my chroot after the same chromeos update, then updated my chroot, and it now works as before.

**Comment by brianmingus** [comment]
That worked thanks!
