### ISSUE TITLE
Can you run crouton from a USB drive?

### ISSUE THREAD

**Issue by Naatan** [dnschneid/crouton#3800]
Apologies for opening a ticket for this, I looked around for a community or forum link or something of the sort but could not find anything.

My question is simple: Can I run crouton from a USB drive?

I'd like to buy a simple cheap chromebook to experiment with, but it only has 16GB of storage, which obviously isn't going to suffice. Nothing an external drive can't help with, but will crouton play nice with that?

Additionally, while I'm here, does anyone have experience running this with 4GB of memory and if so, how well does it work? Do you run into limits fast? Again I intend just to experiment, but long term I hope I could use this as a travel solution.

Thanks!

**Comment by qcu** [comment]
This wiki topic is pretty basic, but introduces the `crouton -p` argument, which may be used to install a chroot to a USB drive or SD card.

https://github.com/dnschneid/crouton/wiki/How-To-Install-To-External-Drive
