### ISSUE TITLE
Crouton not installing (sh: 0: Can´t open)

### ISSUE THREAD

**Issue by trevor93** [dnschneid/crouton#3801]
I am using a chromebook and it only has one available directory called media. All of the examples have Downloads/crouton and i´ve tried switching downloads with media and writing out the whole pathway but so far i cant even run it. I installed crouton within media directory but the pathway is a little long. media/usb/bcrouton/crouton. It is installed on a usb so im not sure if that is the issue.
i´ve tried typing this in with a bunch of variations but i always get 

sh: 0: Can't open /home/chronos/user/media/usb/BCrouton/crouton
or
sh: 0: Can't open /home/chronos/user/media/crouton

if anyone can help id really appreciate it and if anymore info is needed just let me know

**Comment by Mario253** [comment]
If you installed it on a usb, you shouldn't have a ~/ at the beginning of the file path. Then, enter the path exactly as it is spelled/capitalized.

**Comment by DennisLfromGA** [comment]
@trevor93,

If it's on external media then the path would start with: `/media/removable/`

If you are using a Chromebook or any CrOS device then each user is given a **Downloads** folder and it's the default download location unless you changed it in Settings.  

*Hope this helps,*
-**DennisLfromGA**

**Comment by User-s-ops** [comment]
sh: 0: Can't open /home/chronos/user/Downloads/crouton

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
