### ISSUE TITLE
crouton not unmounting after installing pcmanfm

### ISSUE THREAD

**Issue by hpcb** [dnschneid/crouton#3803]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi
host: version 10718.22.0 (Official Build) dev-channel falco 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jun 13 22:15:36 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Failed to unmount /mnt/stateful_partition/crouton/chroots/xenial. Kill processes? [a/k/y/p/N] a
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:

I have to reboot my HP Chromebook 14 - SMB to be able to do at least a backup ...

#### If known, describe the steps to reproduce the issue:

Installed putty, remmina - ok
Installed smb (and added:
"sudo sed -i "/\\[global\\]/a client min protocol = SMB3\nclient max protocol = SMB3" /etc/samba/smb.conf" - as per "https://www.medo64.com/2017/12/solving-failed-to-mount-windows-share/" - in order to be able to access my Windows 10 share), pcmanfm - NOT OK

**Comment by DennisLfromGA** [comment]
> Failed to unmount /mnt/stateful_partition/crouton/chroots/xenial. Kill processes? [a/k/y/p/N] **a**

What happens if you respond with a '**k**' ?

*Hope this helps,*
-**DennisLfromGA**

**Comment by hpcb** [comment]
I have installed Debian Stretch, same results (ie it seems to loop with any response "a", "k", "y" - the only option is to stop with Ctrl-C and to reboot), and I wonder if my machine/ hardware is the cause, please see below ...


chronos@localhost / $ sudo edit-chroot -b stretch
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] k
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] k
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] k
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] k
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] y
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] y
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] p
Failed to unmount /mnt/stateful_partition/crouton/chroots/stretch. Kill processes? [a/k/y/p/N] a
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/stretch...
^Cchronos@localhost / $
