### ISSUE TITLE
Move chroot files to SD 

### ISSUE THREAD

**Issue by mohdyaser** [dnschneid/crouton#3804]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20171230152552~master:de1361af
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 10798.0.0 (Official Build) dev-channel celes 
kernel: Linux localhost 3.18.0-18024-gc429fbc8b604 #1 SMP PREEMPT Tue Jun 19 04:20:58 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

#### Please describe your issue:
I read issues regarding transfer chroot to external sd, but I have some questions. I already have many files on chroot will that affect them? if not, after moving them will chroot save files on the SD or chrome storage ? what are the steps to do all that?

 
Thanks beforehand

**Comment by DennisLfromGA** [comment]
I fielded your question here: "[Crouton Central › Where is the rest of the storage](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/crouton-central/2DlTz3mcKpQ)"

*Hope this helps,*
-**DennisLfromGA**
