### ISSUE TITLE
Colour Distortion when switching between Linux & Chrome OS

### ISSUE THREAD

**Issue by c1z** [dnschneid/crouton#3805]
```
Shift + Ctrl + Alt + Left Arrow / F1
```

When returning from Linux to Chrome OS (Shift + Ctrl + Alt + Left Arrow / F1) the colour is all distorted

#### If known, describe the steps to reproduce the issue:
^^^
Edit: (forgot link) https://imgur.com/4J2nefQ

**Comment by wollanup** [comment]
Is this https://github.com/dnschneid/crouton/issues/3791 ?
