### ISSUE TITLE
UID 1000 not found

### ISSUE THREAD

**Issue by Faliureatlife** [dnschneid/crouton#3806]
sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

when i just re-installed crouton this popped up

**Comment by DennisLfromGA** [comment]
That error message is most likely due to an incomplete crouton installation.
Try updating it with: `sudo sh ~/Downloads/crouton -n xenial -u`

*Hope this helps,*
-**DennisLfromGA**
