### ISSUE TITLE
failed to access '[...]resolv.conf': Permission denied

### ISSUE THREAD

**Issue by fitsum** [dnschneid/crouton#3807]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/precise/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/trusty/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
after upgrading to the latest version of ChromeOS and attempting
`sudo enter-chroot -n trusty`
I get the following output
```
Entering /mnt/stateful_partition/crouton/chroots/trusty...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/trusty/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

#### If known, describe the steps to reproduce the issue:
1. upgrade to latest version of ChromeOS (6/28/2018) for 2015 Chromebook Pixel
2. do `sudo enter-chroot -n trusty`

**Comment by fitsum** [comment]
same with my Chromebox
seems the given chroots directory -- whether it's xenial or trusty ... -- is still there but empty. maybe the chrome update nuked the contents? How should I go about restoring?

**Comment by c1z** [comment]
You need to download the newest version of crouton and then update your current chroot
