### ISSUE TITLE
Where is the software center?

### ISSUE THREAD

**Issue by superamario64** [dnschneid/crouton#3808]
I've heard of the Ubuntu Software Center, a graphical and user-friendly way to download applications and such. I've also heard that it may be depreciated. I am using Xenial. I've also heard of Debian Software Center. 
So my question is "What exactly is the Ubuntu and Debian Software Center, and how can I get it?"

**Comment by MyrmidonGit** [comment]
Try `sudo apt install software-center`

**Comment by levistep32** [comment]
It opens just fine, but when I try to download something it says something about the authentication service not being available. (org.freedesktop.PolicyKit.error.Failed: ('system-bus-name', {'name', ':1.36'}): org.debian.apt.install-or-remove-packages 
Then it says I'm not allowed to perform this action.
