### ISSUE TITLE
Failure starting Ubuntu LTS Xfce server in Chromebook Chroot

### ISSUE THREAD

**Issue by papacosmo** [dnschneid/crouton#3809]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 10575.58.0 (Official Build) stable-channel daisy_skate 
kernel: Linux localhost 3.8.11 #1 SMP Fri Jun 22 17:14:49 PDT 2018 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
excuse me being a linux noob, but I tried to start the linux server but was prompted with this error 
```
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.UnknownMethod: Method "ReleaseDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1530256068.643691 sender=:1.11 -> destination=:1.52 serial=1295 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.UnknownMethod: Method "TakeDisplayOwnership" with signature "" on interface "org.chromium.LibCrosServiceInterface" doesn't exist

method return time=1530256068.891961 sender=:1.11 -> destination=:1.54 serial=1297 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### If known, describe the steps to reproduce the issue: by opening chroot, 

```
chroot> shell`

chronos@localhost / $ sudo startxfce4 
```

then above error is prompted

all help is dearly appreciated, thank you

**Comment by EnderNightLord-ChromeBook** [comment]
what chromebook are you using??? ARM chromebooks don't seem to support xenial. If you do have a ARM chromebook e.g samsung chromebook series 3 then you should just go to trusty...

**Comment by DennisLfromGA** [comment]
@EnderNightLord-ChromeBook,

> what chromebook are you using???

We ask for the croutonversion so we can determine certain specifics, that includes the 'codename'.
@papacosmo has a HP Chromebook 11 G2.

> ARM chromebooks don't seem to support xenial.

That's not true, any supported crouton release should work on any Chromebook architecture.
There are occasionally issues & bugs with individual Chromebooks but they are usually resolved in time.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@papacosmo,

There may be some issues with the 'xorg' xmethod and your device currently.
Until they are resolved you may have luck with the 'xiwi' xmethod, you can install it in your existing xenial chroot with the following:
- `sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

Once that installs and updates successfully you'll also need to install the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension.

'xiwi' will now be the default xmethod.
You can then launch your chroot in a window by default or in a tab or fullscreen using the options below:

- in a window: `sudo startxfce4` 
- in a tab       : `sudo startxfce4 -X xiwi-tab`
- fullscreen   : `sudo startxfce4 -X fullscreen`

Once the 'xorg' issue is resolved you can launch your desktop using it with the following:

- `sudo startxfce4 -X xorg`

*Hope this helps,*
-**DennisLfromGA**)' extension.

**Comment by gummywormz** [comment]
Can confirm I get the same issue. edit-chroot output below
`name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20180611074759~master:3697b784
release: sid
architecture: armhf
xmethod: xiwi
targets: xiwi,extension,core,e17,cli-extra
host: version 10575.58.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Jun 22 17:15:14 PDT 2018 armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...`

I tried using xiwi, but launching it produces the following errors:
`Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
/usr/local/bin/croutoncycle: 503: kill: No such process`

The extension is installed and updated. The extension detects the chroot running, but I can not switch to it and it still errors out despite appearing to make a successful connection. Unsure if this is a related issue or not.

**Comment by IanHarvey** [comment]
I get the same error (`/usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory`) trying to run Xenial on an HP ARM Chromebook. I've now got a working system using:

`./crouton -r trusty -t xfce`
