### ISSUE TITLE
I cannot open crouton on my chromebook

### ISSUE THREAD

**Issue by NobodyThatMatters** [dnschneid/crouton#3810]
#### Please describe your issue:
So my issue is that I cannot open Crouton when I go into developer mode and try to open it with the terminal. When I do any kind of command that would open files via the terminal, it just says
sh: 0: Can't open home/chronos/user/Downloads/crouton
Any and all help would be appreciated, because I would very much like to be able to play steam game son this thing. I have a samsung chromebook model (I can't remember the exact model but it's a more recent model) that has an intel processor, which I have been informed will work with crouton.

**Comment by Mario253** [comment]
I had the same issue. It is probably that you moved crouton into a subfolder. I had done the same thing, though I didn't realize that until I reinstalled it.

**Comment by DennisLfromGA** [comment]
Duping to: https://github.com/dnschneid/crouton/issues/360#issuecomment-401499186
