### ISSUE TITLE
Black x mouse cursor and unresponsive keyboard

### ISSUE THREAD

**Issue by pleasehelpmegod** [dnschneid/crouton#3813]
After I updated from trusty to xenial, I went to try out xenial and when Ubuntu launched the only thing on the screen was my wallpaper and my desktop icons eventually I managed to get to the setting looking for a way to log out, but ended up on the Ubuntu login screen and not back on chromium is, I can’t access the terminal, because my keyboard isn’t working at all

**Comment by DennisLfromGA** [comment]
Did you do the 'update' on the same chroot or did you install it anew?
Sometimes that type of update (upgrade) is problemmatic.

Have you performed a crouton chroot update on that chroot?
Sometimes an update is all that is needed.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pleasehelpmegod** [comment]
At this point my problem is how to get out of my chroot sorry for not clarifying that, because currently I have no way to do so

**Comment by DennisLfromGA** [comment]
I guess I glossed over the part where you said:

> I can’t access the terminal, because my keyboard isn’t working at all

That *is* a problem and one I don't know how to resolve short of powering off and rebooting, sorry.
Once you do get out of the chroot I would suggest doing a crouton update and see if that helps.

For more troubleshooting tips see the wiki article: _**[Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)**_

*Hope this helps,*
-**DennisLfromGA**

**Comment by pleasehelpmegod** [comment]
Thank you for trying to help I ended up fixing it by letting the computer die

**Comment by pleasehelpmegod** [comment]
At which point it booted back into chromium os

**Comment by DennisLfromGA** [comment]
Then try a crouton update using: `sudo sh ~/Downloads/crouton -u`
If your chroot is still named 'trusty' just append '-n trusty' instead.
Once that finishes successfully try launching your desktop again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pleasehelpmegod** [comment]
Yeah I fixed it thank you for your help
