### ISSUE TITLE
Cannot get back onto kde after logging off

### ISSUE THREAD

**Issue by LeeLee2** [dnschneid/crouton#3815]
I have a chromebook and Yesterday I installed kde and everything seemed fine, I could switch between kde and chrome interface. Overnight I turned my laptop off, and when I tried to get onto kde today, it just showed the developer console, and asking for localhost login and password. I've tried entering the username and password I used yesterday to log on but it is saying it is incorrect. Does anyone know what I can try?

**Comment by DennisLfromGA** [comment]
Did you encrypt your chroot using the '-e' option when you installed it?
If so, that is the password it needs, not the one you assigned to the chroot's username, if they are different.

After a reboot you'll have to relaunch your crouton desktop before you can use the <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>forward/back</kbd> key-combos.

*Hope this helps,*
-**DennisLfromGA**
