### ISSUE TITLE
xorg jerky on Pixelbook + debian stretch or Ubuntu xenial

### ISSUE THREAD

**Issue by sethml** [dnschneid/crouton#3818]
```
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20180611074759~master:3697b784
release: stretch
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,keyboard,extension,core,xfce,cli-extra,audio,chrome,e17
host: version 10575.58.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.127-13890-g6c206f1711d4 #1 SMP PREEMPT Fri Jun 22 17:31:24 PDT 2018 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
```

#### Please describe your issue:
If I run a xiwi desktop (via 'sudo startxfce4'), everything works fine. If I start a standalone xorg desktop (via 'sudo startxfce4 -X xorg') it works, but graphics output stutters badly. In Terminal it seems like output pauses for about 1 second every few seconds. If I hold down a key, output will pause, then dozens of letters will appear, then pause, then dozens more letters. In Chrome, repeated characters appear smoothly if I hold down a key, but otherwise when I press a key or click there's often a ~1 second delay. Interestingly, glxgears animates smoothly. I get the feeling there's some kind of power saving delaying the X server. The mouse cursor always moves smoothly.

There's no interesting output in X server output from startxfce4. There's nothing relevant in dmesg output. I'm not sure of where else to look for logs.

The problem occurs with my Debian stretch install. I also tried creating a fresh xenial chroot with 'sudo sh Downloads/crouton -t xfce', and the behavior is exactly the same.

#### If known, describe the steps to reproduce the issue:

Run xorg in crouton on Pixelbook with ChromeOS 67.0.3396.99. It'd be nice to know if anybody else with the same hardware can either replicate the problem, or run xorg without stuttering. If other's can't replicate, I can investigate further. I do have a few experimental ChromeOS settings enabled - perhaps one of them is interacting poorly?

**Comment by DennisLfromGA** [comment]
@sethml,

I haven't tried stretch on my Pixelbook but when I get a moment I'll try to repo this behavior.
Admittedly, I usually run my chroots in a xiwi tab since they work great, I haven't used xorg in a while.

You might try adding another desktop to see if the issue is specific to e17.

BTW, if you like stretch and you're a bit adventurous you should check out Crostini by enabling Linux (beta) in the dev channel, it's lots of fun.

*Hope this helps,*
-**DennisLfromGA**

**Comment by sethml** [comment]
As mentioned in the bug, it happens on xenial as well, which presumably has a much older xorg than stretch, so I don't think it's a recent change in xorg - I think it's a recent change in ChromeOS.

I've tried crostini and it's pretty cool, but it's useless for my use cases. (Programming hardware using USB-JTAG/CAN/Serial adapters, and 3D support to run games.)
