### ISSUE TITLE
How to make KDE german

### ISSUE THREAD

**Issue by kev1807** [dnschneid/crouton#3824]
Hi there, 

I just installed Cloudready on my Lenovo Thinkpad T410s and it runs great. 
I was about to test some Kubuntu (have not worked with it that much before ...) when I used Kubuntu it was always preconfigured during installation for my language (which is german as should the keyboard layout be) how do I change that? :-/

**Comment by Mario253** [comment]
Well, I haven't used Kubuntu but I'm going to assume it's extremely similar to Ubuntu. Start by opening up the Terminal, then click Edit -> Preferences. Go into advanced, and there should be some settings that let you change the locale. You can click on the dropdown near the bottom right corner of the window to change the language. The keyboard layout, in the terminal itself, if you can type well enough, you should type ```sudo dpkg-reconfigure keyboard-configuration```. Then reboot and all should be well.

**Comment by kev1807** [comment]
there was nothing .. however searching the laptop helped a lot ... I was stupid. mea culpa!
