### ISSUE TITLE
Black screen when switching back to Chrome OS from Ubuntu

### ISSUE THREAD

**Issue by saricden** [dnschneid/crouton#3828]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180611074759~master:3697b784
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome
host: version 10575.58.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-17554-g9194949d4df2 #1 SMP PREEMPT Fri Jun 22 17:35:45 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
The issue I'm having is pretty straightforward, but not always easy to reproduce because sometimes it works just fine. Often however, when trying to use the keyboard shortcut or `sudo croutoncycle cros` or `sudo croutoncycle next` commands to switch back into Chrome OS from Ubuntu (Gnome), the screen will just go black and stay black. I'm pretty sure Chrome OS is still running, but the screen is just black.

I've seen similar issues posted so I think this is a relatively known issue. Just wanted to post the specifics of mine to see if I can get a solution.

I'm using an Acer Chromebook 11.

If there are any other details I can provide that would be helpful, please let me know and I'll do so ASAP.

---
EDIT:
---
Forgot to mention, I do have a kind of ghetto solution to the problem: if I run `croutoncycle next` (not cros) once, go to the black screen, use the keyboard shortcut to get back into Ubuntu, then do a hard power off (hold down the power button until it shuts off), turn it back on, run `shell` in the Chrome console, then run `sudo startgnome` and Gnome starts up, I can now use the keyboard shortcut to switch between them almost seamlessly. It seems that after running `gnome-session-quit` and turning off my Chromebook via the power off button in Chrome OS to turn it off properly, the next time I turn it on I have the issue again.

Oh also, I don't know if this is of any relevance, but even when switching between OSs and it works correctly I do see a black screen for a second or two. Don't know if that's a hint for anyone but I'll post it just in case.

**Comment by icecream95** [comment]
A few possible workarounds (they might not solve your problem, though it won't to any harm to try):
- Open a new tab in Chrome with Ctrl-T and type in `about:gpuclean` to the URL bar and hit enter.
- Try switching back to Gnome.
- Switch to a VT (Ctrl-Alt-F2 (->)) and back (Ctrl-Alt-F1 (<-))
- Rather than use `gnome-session-quit`, switch to the crosh tab you started Ubuntu from and press Ctrl-C.
- Open up a crosh tab, type shell, paste in this:
`ps ax -o sess,pgrp,pid,cmd | awk '$4 ~ /^\/opt\/google\/chrome\/chrome$/ { print $3 }' | xargs kill`, and when you get a black screen press enter. Note that you will lose any unsaved data in Chrome OS, but your chroot will be fine.

**Comment by icecream95** [comment]
@DennisLfromGA 

It works with either `chrome://gpuclean/` or `about://gpuclean/`, and also without a trailing slash and/or without the two slashes after chrome: or about:. I wrote `about:gpuclean` as it's the shortest permutation.
<br><br><br>
All the URL's for causing crashes, hangs and restarts are at the bottom of `chrome://about/`.

**Comment by DennisLfromGA** [comment]
@icecream95,

> I wrote about:gpuclean as it's the shortest permutation.

😄

Okay, I hope '`about:gpuclean`' works for the OP, it didn't work for me but '`chrome:gpuclean`' did.

-**DennisLfromGA**

**Comment by saricden** [comment]
Okay, I went to about:gpuclean and it kinda flashed for a second then went back to a new tab (not sure if that's a crash or not?).

Then switched into a VT and back.

Ctrl+c'd out of Ubuntu, then in the crosh tab I pasted the command: `ps ax -o sess,pgrp,pid,cmd | awk '$4 ~ /^\/opt\/google\/chrome\/chrome$/ { print $3 }' | xargs kill`. It restarted, and now I'm just about to turn off my computer, turn it back on, start Ubuntu, and see if I can get the black screen switching back into ChromeOS. Will post my results!

**Comment by saricden** [comment]
Well after turning it off and back on, restarting Ubuntu, and switching back into ChromeOS, I'm happy to report no black screen!

Should I always Ctrl+c out of Ubuntu from now on?

**Comment by icecream95** [comment]
Sorry for not making it clear, but the first three workarounds I posted were meant to be applied *after* you have the black screen problem (I've updated the comment for any new people looking at this).

If you want to try the Ctrl-C workaround, you will have to continue to do it every time to exit for it to work.

**Comment by saricden** [comment]
OH my bad! I was pretty tired when I tried that last night, I could have easily misread it.

But thanks, yeah the Ctrl-C workaround is fine for me, I have no preference when it comes to shutting down my computer.

I'll update this thread if I have any more relevant info.
