### ISSUE TITLE
error while compiling new i386 cras

### ISSUE THREAD

**Issue by nickpitlosh** [dnschneid/crouton#3829]
ran an update today after a chromeos update.

this was the output:

Compiling CRAS (i386)...
tests/cras_test_client.c: In function 'run_aecdump':
tests/cras_test_client.c:677:10: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Werror=format=]
   printf("Dumping AEC info to %s, stream %lu, fd %d\n",
          ^
tests/cras_test_client.c: At top level:
cc1: error: unrecognized command line option '-Wno-int-in-bool-context' [-Werror]
cc1: all warnings being treated as errors
/usr/lib/gcc/x86_64-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: error: ld returned 1 exit status
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
Please show us the output of: `sudo edit-chroot -all`

If you're on the 'canary' channel then let's track this issue here: CRAS cant be compiled #3811

*Hope this helps,*
-**DennisLfromGA**
