### ISSUE TITLE
Problem with debootstrap download in crouton... apparently again.

### ISSUE THREAD

**Issue by Knightlycat** [dnschneid/crouton#3830]
I am having quite the problem with downloading kali linux using the command 
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce

I know there is a problem during setup, so i will remove some specific file and it will work.
but for whatever reason, it does not get the debootstrap that it needs, and i have tried 
sudo sh -e ~/Downloads/crouton -t lxde 
and even getting lxde and it just doesn't work.

**Comment by cericdahl** [comment]
Same problem for xenial, I think.  First-time crouton user, attempting:

sudo sh ~/Downloads/crouton -e -t xfce,xiwi,xorg,touch

and see

"curl: (22) The requested URL returned error: 404 Not Found
Failed to download debootstrap."

**Comment by kapilhp** [comment]
The `debootstrap` required is being downloaded from `anonscm.debian.org` which is now permanently down as per [this link](https://anonscm.debian.org)

**Comment by winterfell125** [comment]
Is there any way around this issue I'm also running into the same problem.

**Comment by zsouthpaw** [comment]
Thats good to know @kapilhp 
Any ideas on how to fix it?

**Comment by Knightlycat** [comment]
wait, what? permenantly down? how am i supposed to get through?!

**Comment by zsouthpaw** [comment]
Since both the URL and the backup are down, but there is now a new 3rd location to get it from, I think we are stuck until the code is updated.

**Comment by Knightlycat** [comment]
ok, but i am still leaving this open until they finish the coding.

**Comment by V3rmeer** [comment]
how long till the code is updated?

**Comment by Knightlycat** [comment]
i believe.. they might keep it open for hours or days, i dont really know how i came to the conclusion.
they could be done in minutes.

**Comment by dnschneid** [comment]
Sorry about that; please give the latest crouton a try.

**Comment by Knightlycat** [comment]
Alright, i have, and for some reason it cant open the debootstrap.

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the problem.
You can do a quick test with something like the following: crouton -r xenial -d -f xenial.bs

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....

-**DennisLfromGA**
