### ISSUE TITLE
Debootstrap error 404 

### ISSUE THREAD

**Issue by winterfell125** [dnschneid/crouton#3831]
It appears the debootstrap link is down and not working at all preventing crouton being run in the Chromebook terminal.

**Comment by zsouthpaw** [comment]
Having the same issue here. Started last night, but wasn't able to get on here until today to try to look for a resolve. It seems the original link URL is dead (https://anonscm.debian.org/gitweb/?p=d-i/debootstrap.git;a=snapshot;h=HEAD;sf=tgz). However, the backup location code does not seem to be working. I was trying to figure out how to download a bootstrap and tell the install to reference that as I can see something from the home page about pre-downloading the bootstrap, but I can't seem to get it functioning. Any help here would be appreciated.

**Comment by cygnus8595** [comment]
Should be here:

https://salsa.debian.org/installer-team/debootstrap/-/archive/master/debootstrap-master.tar.gz

**Comment by dnschneid** [comment]
Yeah, debian seems to have changed servers.  I've updated the link to get things working again, but am looking into a proper solution that will avoid this issue in the future.

**Comment by DennisLfromGA** [comment]
All,

A fix had been merged now that seems to address the problem.
You can do a quick test with something like the following: crouton -r xenial -d -f xenial.bs

If that completes successfully then you can use the '.bs' bootstrap file to install your new chroot with something like this: sudo sh ~/Downloads/crouton -n xenial -f xenial.bs -t ....

-**DennisLfromGA**
