### ISSUE TITLE
Crouton - chromebook acer! 

### ISSUE THREAD

**Issue by azzer1996** [dnschneid/crouton#3833]
Can anyone please help me... 

I’m trying to run RuneScape on my acer chromebook series cb3-131.

I’ve put it In developer mode and downloaded crouton... from there I’ve tried 
Sudo sh ~/Downloads/crouton -t unity
(Xfce) (gnome)...

Failed to download debootstrap.
Check your internet connection or proxy settings and try again.

I don’t know why it’s saying this I use to run RuneScape through Ubuntu... Xfce and unity but since I washed my chromebook because of low storage I’ve never got it it work again!!

Would really appreciate some help or if some one could tell me how it’s possible to run RuneScape on my chromebook any other way than through Ubuntu!

Thanks in advance.

**Comment by Knightlycat** [comment]
Its because the URL that you use to get the debootstrap that downloads everything went dead or something. try again tomorrow, and it might run like butter. try again in at least 30 mins, at least.

**Comment by bahaaaldin214** [comment]
they updated it but than got more broken just wait for another update shouldnt take long

**Comment by azzer1996** [comment]
Okay guys thanks a lot...

So basically it’s down and just needs update so I should just wait and keep trying :)

**Comment by dnschneid** [comment]
Yep, I just tried a second time to fix it.  Please give it a shot.
