### ISSUE TITLE
startxfce4 failing on syntax error?

### ISSUE THREAD

**Issue by josejuanisaac** [dnschneid/crouton#3841]
```
sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: xfce
host: version 10718.29.0 (Official Build) beta-channel terra 
kernel: Linux localhost 3.18.0-17855-g76eb986d8948 #1 SMP PREEMPT Wed Jun 20 23:21:24 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

runing
```
sudo startxfce4
```
yields
```
Entering /mnt/stateful_partition/crouton/chroots/xenial...
-su: 25: Syntax error: "(" unexpected
```
I was using the crouton executable but had the same issue appear by cloning the repo. I expect the repo to hold the latest version.
I thought it might have been because I was running (`sudo enter-chroot`) on a different terminal window but unmounting that did not solve the issue.

I cannot find a similar issue so maybe I'm not observing an important guideline.

**Comment by DennisLfromGA** [comment]
@josejuanisaac,

> crouton: version unknown
release: unknown
architecture: unknown

Something's wrong with your chroot.  I'd suggest following this guide:
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

*Hope this helps,*
-**DennisLfromGA**

**Comment by josejuanisaac** [comment]
> I'd suggest following this guide:

> Common issues and reporting

Based on this i am attempting to perform an update
```
sudo /bin/sh installer/main.sh -u
/usr/local/chroots/xenial already exists; updating it...
installer/../installer/debian/getrelease.sh: 1: installer/../installer/debian/getrelease.sh: ../ubuntu/getrelease.sh: not found
installer/../installer/kali/getrelease.sh: 1: installer/../installer/kali/getrelease.sh: ../ubuntu/getrelease.sh: not found
WARNING: USB booting is enabled; consider disabling it.
WARNING: Legacy booting is enabled; consider disabling it.
WARNING: Signed boot verification is disabled; consider enabling it.
You can use the following command: sudo crossystem dev_boot_usb=0 dev_boot_legacy=0 dev_boot_signed_only=1
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/usr/src/crouton': Permission denied
```
I have been faced with similar issues having to execute sh using /bin/sh since i am mostly executing from an sd card. I solved that issue by remounting directories with noexec flags
```
sudo mount -o remount,rw -o exec PATH/TO/YOUR/FILE
```
but in this case the output of `mount | grep /var/run`
```
run on /var/run type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
run on /var/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,mode=755)
tmpfs on /var/run/crw type tmpfs (rw,nosuid,nodev,noatime,seclabel,size=128k,mode=700)
```
so i am not really understanding why i have no permissions in /var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/usr/src/crouton.

**Comment by DennisLfromGA** [comment]
@josejuanisaac,

No, I don't know of any reason it should be giving you the permission errors, I would reboot tho just in case something is hung up and try again.

One statement that does give me pause tho is this one:

> I was using the crouton executable but had the same issue appear by *cloning* the repo. I expect the repo to hold the latest version.

I'm not sure what method you used for '*cloning*'. but perhaps that's part of the problem.

Also, I'm not sure why you're using: `sudo /bin/sh installer/main.sh -u` unless you have a custom branch or something different from the latest crouton release that you want to preserve.

*Hope this helps,*
-**DennisLfromGA**

**Comment by josejuanisaac** [comment]
@DennisLfromGA 
> had the same issue appear by _cloning_ the repo

In most instructions we are advised to download the installer named `crouton`and use that. At some point I had already tried that and this was not fixing the issue. That is why I tried _cloning_ the repo = I used `git clone` to obtain the source code from github. I then used the installer located in `installer/main.sh`.
> I would reboot 

I restarted the chromebook and still have the same issue.

I went on to restart the whole process and got the installer itself. Now `sudo edit-root -all` yields:
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 10718.29.0 (Official Build) beta-channel terra 
kernel: Linux localhost 3.18.0-17855-g76eb986d8948 #1 SMP PREEMPT Wed Jun 20 23:21:24 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
but I still have the same original issue
```
sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
-su: 25: Syntax error: "(" unexpected
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
I am going to try removing everything and reinstalling, instead of attempting to update. I may be able to post results tomorrow.

**Comment by DennisLfromGA** [comment]
@josejuanisaac,

Before you remove everything maybe try this:

> Sometimes permissions can get set incorrectly when you become 'root' in your chroot profile.
To fix it, if it happens, you can do the following:

> `sudo enter-chroot -n xenial`
> `sudo chown -R 1000:1000 "$HOME"`
> `exit`

It probably couldn't hurt anything.

*Hope this helps,*
-**DennisLfromGA**

**Comment by josejuanisaac** [comment]
Since I posted this I reinstalled and was able to run xfce.
