### ISSUE TITLE
First time Linux user. Having difficulty installing on Samsung Chromebook

### ISSUE THREAD

**Issue by Spiritseeker111** [dnschneid/crouton#3843]
name: trustyencrypted: noEntering /mnt/stateful_partition/crouton/chroots/trusty...crouton: version 1-20180716182256~master:e89a4bb1release: trustyarchitecture: amd64targets: lxdehost: version 10032.86.0 (Official Build) stable-channel celes kernel: Linux localhost 3.18.0-16288-g64d05cf80004 #1 SMP PREEMPT Mon Jan 8 23:21:11 PST 2018 x86_64 x86_64 x86_64 GNU/Linuxfreon: yesUnmounting /mnt/stateful_partition/crouton/chroots/trusty...name: xenialencrypted: yes, lockedUnmounting /mnt/stateful_partition/crouton/chroots/xenial...```

```
This message continues to show everytime I try to install ubuntu using crouton. I literally have no coding or linux knowledge and I would appreciate the most easy to understand explanation as possible. Thank you.
The following packages will be upgraded:
  apt apt-utils base-files bash bsdutils coreutils cpio dh-python dpkg e2fslibs e2fsprogs eject file gcc-4.8-base gcc-4.9-base gnupg gpgv ifupdown
  init-system-helpers initramfs-tools initramfs-tools-bin initscripts iproute2 iputils-ping isc-dhcp-client isc-dhcp-common klibc-utils kmod
  libapt-inst1.5 libapt-pkg4.12 libblkid1 libc-bin libc6 libcgmanager0 libcomerr2 libdb5.3 libdbus-1-3 libdrm2 libexpat1 libffi6 libgcc1 libgcrypt11
  libgnutls-openssl27 libgnutls26 libjson-c2 libjson0 libklibc libkmod2 libmagic1 libmount1 libpam-modules libpam-modules-bin libpam-runtime libpam0g
  libpcre3 libplymouth2 libpng12-0 libprocps3 libpython3.4-minimal libpython3.4-stdlib libselinux1 libsepol1 libsqlite3-0 libss2 libssl1.0.0
  libstdc++6 libtasn1-6 libudev1 libuuid1 locales login logrotate lsb-base lsb-release makedev mime-support module-init-tools mount multiarch-support
  net-tools ntpdate passwd perl perl-base perl-modules plymouth procps python3.4 python3.4-minimal resolvconf rsyslog sensible-utils sudo sysv-rc
  sysvinit-utils tar tzdata udev upstart util-linux vim-common vim-tiny
102 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 250 kB/38.1 MB of archives.
After this operation, 71.7 kB disk space will be freed.
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main base-files amd64 7.2ubuntu5.5
  Connection failed [IP: 2001:67c:1560:8001::11 80]
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main e2fslibs amd64 1.42.9-3ubuntu1.3 [182 kB]
Fetched 182 kB in 23s (7722 B/s)  
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/base-files/base-files_7.2ubuntu5.5_amd64.deb  Connection failed [IP: 2001:67c:1560:8001
::11 80]

**Comment by DennisLfromGA** [comment]
@Spiritseeker111,

> Connection failed [IP: 2001:67c:1560:8001::11 80]

It could be a transient network glitch or possibly be due to being behind a proxy.

If not behind a proxy I would keep trying and see if it eventually connects.
If you're behind a proxy try a different one.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Spiritseeker111** [comment]
Well I am currently using hotspot from a cell phone. Could that be the problem? This has occurred 6 times in a row now. I have also powerwashed system twice to restart.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DennisLfromGA** [comment]
@Spiritseeker111,

I suppose the hotspot could be a problem.
If you could try it on a free wifi or somewhere else we might be able to eliminate the hotspot as the cause.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Spiritseeker111** [comment]
Yes this is going to be my next attempt. Once I try it I will comment back with how it went.

Sent from ProtonMail mobile

-------- Original Message --------
