### ISSUE TITLE
Can't access chroot: 'No chroots with target 'xfce' found in /mnt/stateful_partition/crouton/chroots'

### ISSUE THREAD

**Issue by secretrow** [dnschneid/crouton#3844]
I've been using Elementary OS for about a year with no real problems.  But as of yesterday, when I do sudo startelementary I get: 

sudo startelementary
No chroots with target 'xfce' found in /mnt/stateful_partition/crouton/chroots

I updated my chroot and rebooted, to no avail.  I have the latest version of crouton, and there hasn't been a recent ChromeOS update either. 

I am able to get into Elementary by sudo enter-chroot and startelementary -- but since I've always entered it through the shell, most programs and apps don't run.  

Here's my chroot info: 

sudo edit-chroot -all
name: freya
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/freya...
crouton: version 1-20180718130616~master:5d4c3014
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,extension
host: version 10575.58.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Fri Jun 22 18:18:57 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/freya...

Here's my /mnt/stateful_partition info:  

chronos@localhost /mnt/stateful_partition $ ls -la
total 293844
drwxr-xr-x 8 root root       4096 Jul 18 19:42 .
drwxr-xr-x 3 root root       4096 Jun 22 23:20 ..
drwxr-xr-x 3 root root       4096 Dec 25  2015 crouton
-rw-r--r-- 1 root root          0 Dec 25  2015 .developer_mode
drwxr-xr-x 3 root root       4096 Dec 25  2015 dev_image
drwxr-xr-x 5 root root       4096 Dec 25  2015 encrypted
-rw------- 1 root root 8097439744 Jul 19 13:05 encrypted.block
-rw------- 1 root root         48 Dec 25  2015 encrypted.key
drwxr-xr-x 6 root root       4096 Dec 25  2015 home
drwx------ 2 root root      16384 Dec 25  2015 lost+found
-rw-r--r-- 1 root root      44815 Jul 18 19:42 shutdown_stateful_umount_failure
-rw-r--r-- 1 root root          0 Dec 25  2015 .tpm_owned
-rw------- 1 root root          2 May  6  2017 .tpm_status
-rw------- 1 root root          8 May  6  2017 .tpm_status.sum
-rw-r--r-- 1 root root       4007 Jul 18 19:42 umount-encrypted.log
drwxr-xr-x 4 root root       4096 Dec 25  2015 unencrypted

I'd appreciate any suggestions, as I've never seen this error before.

**Comment by DennisLfromGA** [comment]
@secretrow,

In your `croutonversion` output I don't see any 'xfce' target, only 'x11' & 'extension'.
After looking at the [MyDearFreya](https://github.com/jeremy-breidenbach/MyDearFreya/blob/master/freya.sh) script it looks like it creates & uses a `startelementary` script, there is no mention of 'xfce' at all so I'm not sure why you're now getting that error.

I think if it were me I'd first try re-generating the `startelemmentary` script using the `freya.sh` script as follows: `sudo sh freya.sh continue`

That may be enough to get you going again, if not then you may have to run the elementary package installation again with: `sudo sh freya.sh installelementary`

If you're still stuck then you may need to just start from scratch with: `sudo sh freya.sh`

There's a subreddit r/crouton thread that discusses crouton/freya that I've linked below, they may be able to help:

- [Any guides to getting the new Elementary / Freya release going ?](https://www.reddit.com/r/Crouton/comments/32akho/any_guides_to_getting_the_new_elementary_freya/?st=jjsuzb0y&sh=5619d368)

*Hope this helps,*
-**DennisLfromGA**
