### ISSUE TITLE
Broken Linux on C202SA-YS02?

### ISSUE THREAD

**Issue by tibbeecode** [dnschneid/crouton#3848]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Backed out of Developer Mode due to issue - will reinstall if any hope of help. 

#### Please describe your issue:

Directly following all instructions from clean wipe, I entered linux with sudo startxfce4 - twice. Both times, the environment was unresponsive - even logging out was dicey. I have no previous experience with linux - but there was no dock, about 30 random "drives" scattered on the desktop, and clicking anything would only bring up a context menu. 

#### If known, describe the steps to reproduce the issue:

On Chromebook C202SA, follow the instructions exactly with fresh wipe (both times). And it seems I had the same experience back in May with the same Chromebook - I was busy at the time, so I just took it back. 

On the same Chromebook, I was able to install and run Gallium OS with no issues - but I'd prefer not to partition the drive. And I wiped the Chromebook of the partition before trying crouton. 

Fwiw, there's a mouse/rat in the middle of the desktop, around 20-30 odd "drives" showing, no dock, no way of "running" anything except for the contextual menu that pops up when clicking anything. And even pressing the power button to log out would freeze the chromebook, which is why I wiped my Chromebook. 

Any help would be GREATLY appreciated. Also, Amazon just had these on sale for their Prime Day - so I'm guessing tons of others might be experiencing the same "glitch", following the instructions? Thanks.

**Comment by DennisLfromGA** [comment]
@tibbeecode,

The [README]() offers some pretty good examples so take a look if you haven't yet.
This is a popular guide & video that might offer some important tips, it'll explain that rat in the middle of the desktop too -

- [Install Apps on Your Chromebook With Ubuntu Linux](https://chromeunboxed.com/install-native-apps-on-your-chromebook-with-ubuntu-linux/)

*Hope this helps,*
-**DennisLfromGA**

**Comment by tibbeecode** [comment]
THANK YOU!!!!!

I watched the video, then followed the instructions - flawless! Now to figure out how to use Linux. 

In case it helps with people searching - install crouton chromebook c202sa linux xfce broken fix - I'm guessing trusty works on mine whereas the default install is just busted? ;) And it was very cool that Robby actually ran into problems that would freak idiots like me out - and he's like "No worries - it's all good". Very chill. 

Thank y'all so VERY MUCH!
