### ISSUE TITLE
No desktop on fresh Unity install on Chromebook

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#3850]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10575.55.0 (Official Build) stable-channel reks 
kernel: Linux localhost 3.18.0-17554-g9194949d4df2 #1 SMP PREEMPT Mon Jun 11 23:53:09 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

```

#### Please describe your issue:
I am having an issue using the Unity desktop. I see only the background wallpaper, but no taskbar. I am able to move my mouse and right click, but attempting to open the terminal doesn't work. Interestingly, I am able to change my desktop background. 

This is my first time using Unity, but this appears to be similar to an issue caused by _compiz_. However, I have tried a handful of solutions, such as the ones suggested at [this link](https://itsfoss.com/how-to-fix-no-unity-no-launcher-no-dash-in-ubuntu-12-10-quick-tip/) but I am not sure they are relevant to crouton and therefore didn't work. I would be grateful for any help, and forgive me if this is something basic; I am a novice.

**Comment by Green-Robot-Dev-Studios** [comment]
BUMP! I have the exact same issue.

**Comment by Green-Robot-Dev-Studios** [comment]
Now I can add a file and folder to desktop. Try that. I even named a file index.html and opened it in firefox!

**Comment by Green-Robot-Dev-Studios** [comment]
Still no frame around the window and no menu on the left

**Comment by Pineapplezz** [comment]
@Green-Robot-Dev-Studios try ubuntu trusty. Everything works theres no internet browser. Bionic has only the top taskbar and xenial has nothing at all.

**Comment by Green-Robot-Dev-Studios** [comment]
OK! I will try. I will delete the current one then reinstall with trusty.

**Comment by levistep32** [comment]
The same thing happened to me installing Unity. I like xenial, so I guess I'll try another desktop
