### ISSUE TITLE
crouton shares need to be whitelisted for symlinks and fifos

### ISSUE THREAD

**Issue by pmarkkula** [dnschneid/crouton#3853]
#### Please describe your issue:
Building crouton inside crouton used to work. Now it seems to succeed, but because symlinks are used, ie. in chroot-bin, some files in installer are empty, ie. crouton-noroot. ("cat chroot-bin/startxfce4" gives permission error, even with sudo.) When upgrading existing chroot with created installer, result is chroot that works in cli mode, but startxfce4 does nothing and returns immediately.

#### If known, describe the steps to reproduce the issue:
Clone crouton into chroot and build it. Check files inside installer that depend on symlinks.

**Comment by dnschneid** [comment]
Are you building crouton in a directory that's not on the same mountpoint as the root directory of the chroot?

**Comment by pmarkkula** [comment]
Yes I am. Repo is under directory that is mounted via /etc/crouton/shares. I use it to share data between chroots.

**Comment by dnschneid** [comment]
Ooh.  Looks like we need to [whitelist](https://github.com/dnschneid/crouton/blob/master/host-bin/mount-chroot#L62) the download, encrypt, and share prefixes for symlinks and fifos...
