### ISSUE TITLE
Cannot start chroot

### ISSUE THREAD

**Issue by EternalFlameIV** [dnschneid/crouton#3854]
Please paste the output of the following command here: `sudo edit-chroot -all`
```
bash: edit-chroot: command not found
```

#### Please describe your issue:
Trying to create a Linux Mint-like Ubuntu chroot. All attempts at creating a chroot fail at the "Please specify a username for the primary user:" input. Tried rebooting, using VT2 and crosh shells, and fresh installer. All failed at the same step. Runnung below command with `-u` flag does the same thing.

Output: Normal until this line:
```
Please specify a username for the primary user: Failed to complete chroot setup.
Unmounting /media/removable/LinuxMint/chroots/mint...
Sending SIGTERM to processes under /media/removable/LinuxMint/chroots/mint...
chronos@localhost / $
```

#### If known, describe the steps to reproduce the issue:
1. Run this command: `cd /home/chronos/user/Downloads | sudo sh -e /home/chronos/user/Downloads/crouton -r xenial -t xiwi,xfce,keyboard,extension -n mint -p '/media/removable/LinuxMint'`

**Comment by DennisLfromGA** [comment]
@EternalFlameIV,

Wow, that's a bummer.
In the interim, until the issue is determined and a fix is merged maybe first install it on the internal storage device first and then copy or move it with `edit-chroot`.

*Hope this helps,*
-**DennisLfromGA**

**Comment by jnickerz** [comment]
i am having the same issue. waiting for a fix
