### ISSUE TITLE
linux won't start on my chromebook

### ISSUE THREAD

**Issue by letthereberock** [dnschneid/crouton#3856]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: armhf
xmethod: xorg
targets: extension,xiwi,xfce
host: version 10575.58.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Fri Jun 22 17:08:53 PDT 2018 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial..
#### Please describe your issue:
Linux won't start. The error message is similiar to this one:
https://github.com/dnschneid/crouton/issues/3291
I read what runner18 wrote, but I don't quite get it - first he tells people to update xorg (which is always included in the xfce, right?), but then he says it's best to not use the command.
There must be a way. Maybe I just don't get it - I'm pretty new to this but I really want to understand it.

#### If known, describe the steps to reproduce the issue:
Installing crouton via this command: " sudo sh ~/Downloads/crouton -t xfce"

**Comment by DennisLfromGA** [comment]
@letthereberock,

@runner18 is suggesting to install it with just the 'xiwi' xmethod using something like:

- `sudo sh ~/Downloads/crouton -t xiwi,xfce`

(You don't need to specify 'extension', it's gets installed with 'xiwi'.)

It looks like you have both 'xorg' & 'xiwi' installed so have you tried to launch your xfce desktop with one of the 'xiwi' options instead of using the default 'xorg'?

- `sudo startxfce4 -X xiwi` (that will launch in a window via 'xiwi')

- `sudo startxfce4 -X xiwi-fullscreen` (that will launch fullscreen via 'xiwi')

- `sudo startxfce4 -X xiwi-tab` (that will launch in a browsing tab)

*Hope this helps,*
-**DennisLfromGA**

**Comment by letthereberock** [comment]
Thanks Dennis!
I tried. It says: "Illegal option -i"
Seems like a minor problem. 
I still don't know what to do :-/

**Comment by letthereberock** [comment]
I just tried the following command:
"sudo enter-chroot startxfce4 -x -xiwi"
I don't know if that makes sense but t least it tried to execute something.
Here's what happened:

"MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) "

**Comment by letthereberock** [comment]
Thanks again.
Sadly still not working. The command with the capital X says:

"/mnt/stateful_partition/crouton/chroots/xenial does not contain XMETHOD ''"

With a regular x this happens:

"Illegal option -i
enter-chroot [options] [command [args...]]

Enters an installed Debian-based chroot for running alongside Chromium OS.

By default, it will log into the primary user on the first chroot found.
You can specify a command and parameters to run instead of an interactive shell.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -l          Make the command part of a login. Parameters are passed directly
                to the chroot command, and a call to su is appended.
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -X XMETHOD  Override the auto-detected XMETHOD for this session.
    -x          Does not log in, but directly executes the command instead.
                Note that the environment will be empty (sans TERM).
                Specify -x a second time to run the /prepare.sh script."

As I said - "illegal option -i" - no idea why this keeps happening.

**Comment by DennisLfromGA** [comment]
@letthereberock,

> With a regular x this happens:
"Illegal option -i

A 'regular'x *will not work*, don't use it.

> xmethod: xorg
targets: extension,xiwi,xfce

Your installed xenial chroot is using the 'xorg' xmethod by default but the 'xiwi' xmethod was specified & installed it appears.

It's saying it does not contain '**XMETHOD ""**' which looks like you didn't enter the command correctly.
Please copy & paste the following into your shell session *exactly* as given and it should work.

- `sudo startxfce4 -X xiwi`

*Hope this helps,*
-**DennisLfromGA**

**Comment by letthereberock** [comment]
Thanks again.
It's still not working. Copy & Paste. Here's what happened:

"
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
"
