### ISSUE TITLE
No Virtual machine to work because of constant problems and errors

### ISSUE THREAD

**Issue by Knightlycat** [dnschneid/crouton#3857]
I have tried every single VM that i could have bothered with which include virtualbox, QUMU, and vmware. All have not worked.

virtualbox just said something about not working with linux kernel headers not working with them, Not supported kernel version. 3 hours wasted...

Qumu would not work with Virt-manager because of some directory error in stage 5. i could literally not find a single soloution to this..

vmware was fine until the download was a bundle file..? i looked at it.. and thought about how i cant waste more time on this.  

I am wanting to run  windows XP home edition on my chromebook which has enough space...

plz help

**Comment by rmartin16** [comment]
The wiki below contains the instructions for installing virtualbox.

https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)

But it is not easy...i finally got it working...kind of...but only after overcoming many issues. It was ultimately recommended to me to use GalliumOS for purposes of VMs.
