### ISSUE TITLE
jupyter notebook: "Error /tmp/crouton-ext/in or /tmp/crouton-ext/out are not pipes"

### ISSUE THREAD

**Issue by MaxGhenis** [dnschneid/crouton#3859]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 10575.58.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.127-13890-g6c206f1711d4 #1 SMP PREEMPT Fri Jun 22 17:31:24 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
Running a `conda` installation of `jupyter notebook` produces this error:

```
(xenial)maxghenis@localhost:~$ jupyter notebook
[I 11:00:04.781 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 11:00:04.782 NotebookApp] Serving notebooks from local directory: /home/maxghenis
[I 11:00:04.782 NotebookApp] The Jupyter Notebook is running at:
[I 11:00:04.782 NotebookApp] http://localhost:8888/?token=a91933fcfc692bb5ba5b4f0066e5cfc32baedab89e422e2d
[I 11:00:04.782 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:00:04.784 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=a91933fcfc692bb5ba5b4f0066e5cfc32baedab89e422e2d
Error /tmp/crouton-ext/in or /tmp/crouton-ext/out are not pipes.
[I 11:00:13.495 NotebookApp] 302 GET /?token=a91933fcfc692bb5ba5b4f0066e5cfc32baedab89e422e2d (::1) 2.90ms
[I 11:00:18.394 NotebookApp] Kernel started: 00490efc-a559-4156-8268-c8e1c21c8e3a
```

After this initialization, Python Jupyter notebooks work, but the R kernel dies immediately. This may be related to https://github.com/IRkernel/IRkernel/issues/388, but I've gone through steps there and haven't been able to resolve the issue. 

#### If known, describe the steps to reproduce the issue:

Create clean conda environment:

```
conda create -n rjupyter -c anaconda jupyter r r-irkernel gerrymandr r-tidycensus
conda activate rjupyter
```

In this clean environment, running `jupyter notebook` throws the error above, but the R kernel doesn't die.

In my [default environment](https://gist.github.com/MaxGhenis/b32a42812d7de9e6942873d981745db1), I get the error and the R kernel dies.

**Comment by bamartin-ua** [comment]
has there been any movement on this issue? six months and not so much as a comment.

I can confirm that it has nothing to do with the R kernel as I am using the python kernel and am receiving this error as well.

it doesn't seem to be actually negatively affecting anything, but that red text is disconcerting to see.

**Comment by DennisLfromGA** [comment]
The original post is using: crouton: version 1-20180718130616~master:5d4c3014
Have you updated your chroot recently and does the issue persist?

Also, maybe this related issue will help:
- Proper way to run croutonwebsocket on enter-chroot without permission issues? #2161

*Hope this helps,*
-**DennisLfromGA**

**Comment by MaxGhenis** [comment]
I just updated crouton and created a new conda environment as (`r-tidycensus` moved), and am still getting the same error, though R notebooks run.

```
conda create -n rjupyter -c anaconda jupyter r r-irkernel gerrymandr r-tidycensus
...
conda activate rjupyter
...
(rjupyter2) (xenial)maxghenis@localhost:~$ jupyter notebook
...
Error /tmp/crouton-ext/in or /tmp/crouton-ext/out are not pipes.
```

**Comment by MaxGhenis** [comment]
After updating crouton, the R kernel also still dies when running `jupyter notebook` from my default environment.
