### ISSUE TITLE
"extraordinarily old" Chromium OS version check is failing

### ISSUE THREAD

**Issue by dnschneid** [dnschneid/crouton#3861]
From http://crbug.com/871804

Also: we should change the instructions to direct users to create a new bug.

**Comment by Davografie** [comment]
The requested file /etc/lsb-release is not found on my system. See screenshot.
![screenshot 2018-08-07 at 19 58 04](https://user-images.githubusercontent.com/10770805/43793604-591a6972-9a7c-11e8-968b-177a8ebf449a.png)

**Comment by Davografie** [comment]
lsb-release is installed as a package.
![screenshot 2018-08-07 at 20 16 47](https://user-images.githubusercontent.com/10770805/43794530-e35d3e14-9a7e-11e8-9b2d-b31d735f6406.png)

**Comment by dnschneid** [comment]
Oh, you're trying to install crouton inside of crostini.

That's really not a supported use of crouton, I'm afraid.
