### ISSUE TITLE
Thick black lines around application

### ISSUE THREAD

**Issue by Swcbn** [dnschneid/crouton#3864]
So, I'm running Ubuntu Xenial on an Asus c301SA, and its working fine, but one day, I open xterm, and there are thick black lines where the grey bars should be in unity. So I close xterm and open it again, black bars are still there. I open unetbootin, and it has black bars around it too. But in unetbootin, when I open the choose distribution drop-down menu, its a black box. Mind you, I can still select an OS from the list, but I have to guess where it is because there are no names showing up. Can someone please help me with this. Please let me know if I can clarify something. Thank you, even if you can't help me:)

**Comment by DennisLfromGA** [comment]
To help troubleshoot this issue we'll need a few more details.
Please show us the output of: `sudo edit-chroot -all`

**Comment by Swcbn** [comment]
sudo edit-chroot -all
name: gnome-writer
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/gnome-writer...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome
host: version 10895.10.0 (Official Build) dev-channel terra 
kernel: Linux localhost 3.18.0-18116-g109087054ee6 #1 SMP PREEMPT Mon Jul 30 23:40:12 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/gnome-writer...
name: secure
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/secure...
crouton: version 1-20180718130616~master:5d4c3014
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 10895.10.0 (Official Build) dev-channel terra 
kernel: Linux localhost 3.18.0-18116-g109087054ee6 #1 SMP PREEMPT Mon Jul 30 23:40:12 PDT 2018 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/secure...
**name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10895.10.0 (Official Build) dev-channel terra 
kernel: Linux localhost 3.18.0-18116-g109087054ee6 #1 SMP PREEMPT Mon Jul 30 23:40:12 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes**
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by Swcbn** [comment]
The bold part is the partition I have a problem with, all the other partitions are fine.

**Comment by DennisLfromGA** [comment]
@Swcbn,

Do `xterm`, `unetbootin`, and other apps work & display correctly in your 'gnome-writer' chroot?

It looks to be using the same 'xenial' release and 'xorg' xmethod, the difference being the 'gnome' desktop target instead of the 'unity' desktop target. 

If so, then this may be a glitch with Unity, possibly even an upstream bug.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Swcbn** [comment]
Thank you!

**Comment by Swcbn** [comment]
I found the bug:
https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1292830
