### ISSUE TITLE
C++ Dll Reading And Writing Memory

### ISSUE THREAD

**Issue by masterpaper** [dnschneid/crouton#3869]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Hi i have an issue with pointers and how to write to mem with them through a dll.
this is my code:

`// dllmain.cpp : Defines the entry point for the DLL application.
#include "stdafx.h"
#include "Windows.h"
void inject() {
	DWORD ptr = 0x0019E0D0 + 0x3C8;
	DWORD addr = ptr + 0x27C;
	*(int*)addr = 10000;
}
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
		inject();
		break;
    case DLL_THREAD_ATTACH:
		inject();
		break;
    case DLL_THREAD_DETACH:
		break;
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}

`

for the fist line of code it would just fine with one pointer. However if i add more pointers it doesn't Work 0_0. Sorry if this is a silly question i am a little new to this. Thanks!

**Comment by Mozzy-Diffuzer** [comment]
not sure if this is a crouton issue?
