### ISSUE TITLE
Cr-48 Installation Issue with kali-rolling

### ISSUE THREAD

**Issue by Villanta81** [dnschneid/crouton#3872]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### Please describe your issue:

I've tried 3 times with the same results. Any help would be appreciated.  Thanks.

First Error Result:
`sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce`
Downloading latest crouton installer...
######################################################################## 100.0%
Installing kali-rolling-i386 chroot to /usr/local/chroots/kali-rolling
Downloading bootstrap files...
...
I: Unpacking the base system...
W: Failure trying to run:  dpkg --force-overwrite --force-confold --skip-same-version --install /var/cache/apt/archives/libapparmor1_2.13-8_i386.deb /var/cache/apt/archives/libkmod2_25-1_i386.deb /var/cache/apt/archives/libncurses6_6.1+20180714-1_i386.deb /var/cache/apt/archives/libprocps7_2%3a3.3.15-2_i386.deb /var/cache/apt/archives/procps_2%3a3.3.15-2_i386.deb /var/cache/apt/archives/systemd_239-7_i386.deb
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)

Second Error Result:

` sudo enter-chroot -n kali-rolling
`
...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.45_i386.deb
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
chronos@localhost / $ W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.45_i386.deb
bash: W:: command not found
chronos@localhost / $ W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
bash: syntax error near unexpected token `('
chronos@localhost / $ Failed to complete chroot setup.
bash: Failed: command not found
chronos@localhost / $ The chroot setup script may be broken. Your chroot is not fully configured.
bash: The: command not found
chronos@localhost / $ Removing the chroot setup script. You may want to update your chroot again.
bash: Removing: command not found
chronos@localhost / $ UID 1000 not found in kali-rolling
bash: UID: command not found
chronos@localhost / $ Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by DennisLfromGA** [comment]
Not entirely sure what's going on but glad to see someone still using a Cr-48. 👍 

Can you please show or tell us what's displayed on the first five lines when you navigate to: 

- [chrome://version](chrome://version)

And if possible, please show us the output of: 

- `sudo edit-chroot -all`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Villanta81** [comment]
Hi Dennis, this thing still has value if I can get Kali on it. :)

chrome://version

Google Chrome | 56.0.2924.26 (Official Build) dev (32-bit)
-- | --
Revision | 0
Platform | 9000.26.0 (Official Build) dev-channel x86-mario
JavaScript | V8 5.6.326.25
Flash | 24.0.0.186

sudo edit-chroot -all

name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version unknown
release: unknown
architecture: unknown
targets: xfce
host: version 9000.26.0 (Official Build) dev-channel x86-mario 
kernel: Linux localhost 3.8.11 #1 SMP Sun Dec 11 21:48:10 PST 2016 i686 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by DennisLfromGA** [comment]
Thanx for the feedback and info.

What's very unusual about the Cr-48 is the stable channel is ahead of both beta & dev:  

- Stable: 56.0.2924.110
- Beta: 56.0.2924.87 
- Dev: 56.0.2924.26 

So if you want to be on the latest release for the Cr-48 you'll need to change the channel to stable but that requires a powerwash so you'll have to back up your crouton chroots and stuff in ~/Downloads beforehand.
And I don't know if that's really warranted for this issue, but it couldn't hurt. 

Your 'kali-rolling' chroot seems to be a bit unfinished and broken so an update might be best at this juncture. You can do that by entering the following:  

- `sudo sh ~/Downloads/crouton -n kali-rolling -u`

If that completes successfully then you can try to get back into your chroot with:  

- `sudo startxfce -n kali-rolling`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Villanta81** [comment]
Thanks man. I’ll check this out tonight and report back. Dawgs are on. ;)

**Comment by DennisLfromGA** [comment]
Watching the U.S. Open so I know what you mean...

**Comment by Villanta81** [comment]
Ok I lied, slightly...had to run home for a minute anyhow!

I tried without updating to the Stable channel.  No joy.

sudo sh ~/Downloads/crouton -n kali-rolling -u
Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/kali-rolling already exists; updating it...
Preparing chroot environment...
...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.45_i386.deb
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by Villanta81** [comment]
Ok, stable channel...still errors.

W: Failure trying to run:  dpkg --force-overwrite --force-confold --skip-same-version --install /var/cache/apt/archives/libapparmor1_2.13-8_i386.deb /var/cache/apt/archives/libkmod2_25-1_i386.deb /var/cache/apt/archives/libncurses6_6.1+20180714-1_i386.deb /var/cache/apt/archives/libprocps7_2%3a3.3.15-2_i386.deb /var/cache/apt/archives/procps_2%3a3.3.15-2_i386.deb /var/cache/apt/archives/systemd_239-7_i386.deb
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by DennisLfromGA** [comment]
@Villanta81,

When you moved to the stable channel I assume you started over and installed a new 'kali-rolling' chroot.
Is that now failing on you as shown above or is that the original chroot you were having trouble with?

-**DennisLfromGA**

**Comment by Villanta81** [comment]
Just re-ran, a new error at the front:

W: Cannot check Release signature; keyring file not available /usr/share/keyrings/kali-archive-keyring.gpg

Process continues and fails similarly as before.  Same errors at the end.
W: Failure trying to run:  dpkg --force-overwrite --force-confold --skip-same-version --install /var/cache/apt/archives/libapparmor1_2.13-8_i386.deb /var/cache/apt/archives/libkmod2_25-1_i386.deb /var/cache/apt/archives/libncurses6_6.1+20180714-1_i386.deb /var/cache/apt/archives/libprocps7_2%3a3.3.15-2_i386.deb /var/cache/apt/archives/procps_2%3a3.3.15-2_i386.deb /var/cache/apt/archives/systemd_239-7_i386.deb
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
Failed to complete chroot setup.

**Comment by DennisLfromGA** [comment]
@Villanta81,

Well, I'm stumped, I was gonna suggest starting over from scratch but that didn't work either.
Maybe the architecture of the Cr-48 is not compatible with the kali-rolling release.
And maybe someone smarter than me will pitch in and help out.

-**DennisLfromGA**

**Comment by Villanta81** [comment]
I appreciate you trying. If that’s the case another release may be. I’ll
test that out of curiosity, but would like to keep the issue open on the
chance someone can help resolve.

Thanks again.

**Comment by DennisLfromGA** [comment]
@Villanta81,

Yes, both good ideas.

-**DennisLfromGA**

**Comment by Villanta81** [comment]
So first part, complete. Issues persist with another release. 

sudo sh ~/Downloads/crouton -e -t xfce

Installing xenial-i386 chroot to /usr/local/chroots/xfce

W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg

....

W: Failure while configuring required packages.
W: See //debootstrap/debootstrap.log for details (possibly the package systemd is at fault)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@Villanta81,

I would suggest just installing your chroot *without* encryption first, without the '`-e`' option.
Then if it installs successfully you can encrypt with an update.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Villanta81** [comment]
Took your advice and I have a successful installation of Xubuntu Trusty on my Cr-48!  

Doesn't solve the issue but isolates it to kali-rolling.

**Comment by DennisLfromGA** [comment]
@Villanta81,

Thanx for the feedback, that's very helpful.

You could try installing some ['kali-linux' metapackages](https://www.kali.org/news/kali-linux-metapackages/) on Trusty if you're brave and you've first backed up your chroot of course.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Villanta81** [comment]
Sounds like fun.  I'll give it a go.  Sure I'll find some level of success and kill a few evilchroots along the way.  Thanks.
