### ISSUE TITLE
Linux not opening

### ISSUE THREAD

**Issue by jethan47** [dnschneid/crouton#3876]
```
Please paste the output of the following command here: sudo startxfce4
```

#### Please describe your issue:
when i do the key-bind ctrl+alt+shift+-> it doesn't register anything but with ctrl+alt+-> it brings me to the dev shell- does anyone know how i can get back into ubuntu? Im new to linux and im using a HP g4 14 chromebook.

Yesterday it all worked fine but now i cant get it to work plz help

**Comment by DennisLfromGA** [comment]
@jessaustin,

Please paste the output of the following command below: `sudo edit-chroot -all`

That info. is needed to see what targets and xmethods you've installed. 

----
The key-combo <kbd>**ctrl**</kbd>+<kbd>**alt**</kbd>+<kbd>**forward/back**</kbd>  will drop you into the Developer Concole on VT2, not what you want.   

With 'xorg' the key-combos <kbd>**ctrl**</kbd>+<kbd>**alt**</kbd>+<kbd>**shift**</kbd>+<kbd>**forward/back**</kbd> *should* work.

With 'xwi' you don't need them, you can open your running chroot desktops by clicking on the 'crouton integration' extension icon.  Once in a crouton window, press fullscreen or the "switch window" key to switch back to Chromium OS.


*Hope this helps,*
-**DennisLfromGA**

**Comment by jessaustin** [comment]
I don't think you intended to ping me on this? 😃

**Comment by DennisLfromGA** [comment]
Yup, so sorry, guess I got carried away with the 'tab' key, my bad. 😯

**Comment by jethan47** [comment]
when i use sudo edit-chroot -all this shows up 

chronos@localhost / $ sudo edit-chroot -all
Password: 
sudo: edit-chroot: command not found

**Comment by DennisLfromGA** [comment]
@jethan47,

That's not good. Can you still launch your desktop with your start* script?
You may need to restore your 'host-bin' files with the command:  
- `sudo sh ~/Downloads/crouton -b`  

After that try: `sudo edit-chroot -all`

*Hope this helps,*
-**DennisLfromGA**
