### ISSUE TITLE
Failed to Complete Chroot Setup.

### ISSUE THREAD

**Issue by ktea4** [dnschneid/crouton#3879]
Please paste the output of the following command here: 

useradd: group sudo exists - if you want to add this user to that group, use -g
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
Trying to install Ubuntu on my chromebook with Crouton.
Enabled chromebook into developer mode.
Downloaded Crouton & downloaded the latest script.
Opened the terminal & typed shell.
Have tried several desktop environments!
  Xfce; Unity; Trusty
After typing in the username: sudo startunity or sudo startxfce4 I get the below error.

Chromebook is an Asus.  
![screenshot 2018-09-10 at 12 32 47 am](https://user-images.githubusercontent.com/43127040/45277297-1e859d80-b495-11e8-97b0-edaf430c3aea.png)

**Comment by DennisLfromGA** [comment]
@ktea4,

It is expecting a 'username' at that prompt, you instead entered the start script for the xfce4 target.    

Try running the following command and see if it will again prompt you for a username:    

 - `sudo enter-chroot -n xenial`    

If that does not prompt you for a username then you may have to run the following:   

- `sudo sh ~/Downloads/crouton -n xenial -u`

Enter a unique username and when it's accepted it will prompt you for a password twice, you will NOT see the password you type in, that's normal.    

If neither of those commands prompts you for a username you may have to delete the chroot with:    

- `sudo delete-chroot xenial`    

Then start over.

*Hope this helps,*
-**DennisLfromGA**

**Comment by ktea4** [comment]
@DennisLfromGA 

Thank you! I typed sudo enter-chroot -n xenial 

How do I get the xfce session/ubuntu desktop to pop up? Sorry, I have no knowledge of this kind of stuff. Clearly. 

![screenshot 2018-09-11 at 2 01 04 pm](https://user-images.githubusercontent.com/43127040/45378626-fba9d500-b5cb-11e8-83f7-7d713736b260.png)

**Comment by DennisLfromGA** [comment]
@ktea4,

The 'start*' scripts allow you to launch your desktop(s) directly from outside your crouton chroot in a Chrome OS shell with elevated permissions like this:   

- `sudo startxfce4`

From inside the crouton chroot you *can* launch your desktop but *without* elevated permissions like this:   

- `startxfce4`

*Hope this helps,*
-**DennisLfromGA**
