### ISSUE TITLE
Documentation query: Sharing files and folders

### ISSUE THREAD

**Issue by dbaynard** [dnschneid/crouton#3888]
[The wiki page on sharing files and folders between ChromeOS and the chroot](https://github.com/dnschneid/crouton/wiki/Sharing-files-and-folders) gives a method to share an (encrypted) home directory between the chroot and the ChromeOS host.

> `encrypted/home ~`

It is not clear, however, what `encrypted` means in this context.
I had expected it would mean the same as it does for the chroot: that I would have to decrypt the directory by entering some sort of password before being able to use it. However, it appears not to be the case.

It would be helpful to improve the documentation, even if it just involves adding a link to an existing description. How do the `encrypted/` directories work?

Thanks!

**Comment by DennisLfromGA** [comment]
@dbaynard,

You're right, the documentation could be more clear for sure, if I understood it well enough I'd attempt it but I don't.

IIUC, the part about mapping outside the chroot that says these are the only folders crouton recognizes:
```
downloads: ~/Downloads
shared: /mnt/stateful_partition/crouton/shared
encrypted: ~/crouton/shared
```

The `encrypted: ~/crouton/shared` part is talking about creating this folder in CrOS:    
- `/home/chronos/user/crouton/shared`   

If you creat a sub-folder called `home` it can be accessed by your chroot(s) in your home folder '`~/`' if you add this entry the the chroot's `/etc/crouton/shared` file -
- encrypted/home ~   

I know that's not much clearer at all but it might help to look at the source code startng here: [enter-chroot#L404](https://github.com/dnschneid/crouton/blob/master/host-bin/enter-chroot#L404), it helped me.

*Hope this helps,*
-**DennisLfromGA**

**Comment by dbaynard** [comment]
Thanks @DennisLfromGA. That was helpful. It treats the `~/crouton/shared` folder just as the `~/Downloads` folder. And so I've found #3329 (which I had seen, but didn't understand).

So to clarify:

So let's say I set up a (default) crouton chroot. Any logged in ChromeOS user may decrypt and log in to that chroot?

Then, of the three directory roots:

```
downloads: ~/Downloads
shared: /mnt/stateful_partition/crouton/shared
encrypted: ~/crouton/shared
```

-   `downloads` is encrypted using the ChromeOS user profile — meaning it is avaliable iff that ChromeOS user is logged in
-   `encrypted` is the same
-   `shared` is available to any ChromeOS user who is logged in

In no case do any of those three directories need decrypting in the same way the chroot does?

**Comment by dnschneid** [comment]
> So let's say I set up a (default) crouton chroot. Any logged in ChromeOS user may decrypt and log in to that chroot?

You can access the chroot even without logging in, by going into guest mode or using frecon (ctrl-alt-f2).  If you've encrypted your chroot, they'll need a password (and the keyfile if you're stored it elsewhere).

> downloads is encrypted using the ChromeOS user profile — meaning it is avaliable iff that ChromeOS user is logged in

yep.  The Downloads folder also comes with the feature that ChromeOS may delete old files from there if you start to run out of disk space.

> encrypted is the same

yep!  But this one isn't subject to automatic clean-up.

> shared is available to any ChromeOS user who is logged in

similar to the chroot itself, you can also access it without logging in.

> In no case do any of those three directories need decrypting in the same way the chroot does?

that's correct.  They're all stored separately from the chroot and exist in folders managed one way or another by ChromeOS.

**Comment by dbaynard** [comment]
Thanks, @dnschneid! I'll put the detail in the wiki and then close the issue.

**Comment by dbaynard** [comment]
Closing as I've edited the wiki. Thanks!
