### ISSUE TITLE
Color Distortion after Chrome OS Update

### ISSUE THREAD

**Issue by danraies** [dnschneid/crouton#3892]
```
$sudo enter-chroot -n xenial croutonversion
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome-desktop
host: version 10895.56.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.141-14563-g78fd9f781aae #1 SMP PREEMPT Thu Sep 13 00:00:24 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

I'm using a Pixelbook with a single xenial chroot installed with the gnome desktop.  I recently updated to Chrome OS Version 69.0.3497.95 (Official Build) (64-bit) and this issue presented itself immediate after the update.  I have updated my chroot (using the instructions [here](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)).  There were no errors in the update (as far as I could tell) but it did not resolve the issue.

If I launch the gnome desktop for my chroot (`sudo startgnome`) and then return to Chrome OS (using either the keyboard shortcut or by logging out) the colors are distorted.  It is almost like the colors are inverted but they are also very blurry and the display will flicker back and forth between nearly normal colors and some different distorted colors.  If I return to the chroot everything looks fine on the gnome desktop but if I then return to Chrome OS things are still distorted.  Restarting my laptop returns everything to normal but the problem returns when I launch the gnome desktop.  I don't have any problems if I enter the chroot with `sudo enter-chroot`.

If I take a screenshot while the screen is distorted, the image does not capture the distortion.  That is, after I restart, the screenshot that I took of the distortion displays as a normal image with normal colors.  Here is a link to a photograph of the problem: [https://i.imgur.com/1t7DF9m.jpg](https://i.imgur.com/1t7DF9m.jpg)  If it helps, I could post a video of myself reproducing it as there is some flickering of the colors that isn't captured in a photo.

#### If known, describe the steps to reproduce the issue:

From a fresh restart I do the following:

1. Launch my chroot from a shell with `sudo startgnome`.
2. Return to the Chrome OS desktop either by logging out of the gnome desktop or by using `ctrl+alt+shift+back`.

At this point, the problem presents itself.  The colors are warped and the text is distorted and unreadable.

**Comment by danraies** [comment]
It has been recommended to me that I disable the night light flag in chrome://flags.  I did try that but unfortunately the problem persists.

**Comment by danraies** [comment]
I do have a workaround.  When the problem occurs, anything that refreshes the screen seems to clear it up the distortion momentarily (though it comes back again when you switch to gnome again).  I have found four ways (so far) to do that:

1. Switch to tablet mode and back.
2. Change the resolution.
3. Rotate the screen four times (`ctrl`+`shift`+`refresh`).
4. Toggle night light mode on or off (with the flag enabled).

**Comment by DennisLfromGA** [comment]
@danraies,

I'm not sure crouton is the culprit here, when it next happens you might want to file a report using the key-combo <kbd>**alt**</kbd>+<kbd>**shift**</kbd>+<kbd>**i**</kbd> or file a crbug **[here](http://chromiumbugs.appspot.com/?token=hXJ9BAhPwaGhH-M-a6y7EDoxNTM3NzExODAw&role=&continue=https%3A//bugs.chromium.org/p/chromium/issues/entry.do)**.

And perhaps close this issue if you agree.

-**DennisLfromGA**

**Comment by Wtcheesecakes** [comment]
i have the same issue and ive tried all the suggested solutions and none of them have worked

**Comment by acontributor0** [comment]
I have the same problem
The solution is enable night light (the real one) and turn back off.

**Comment by codyghind** [comment]
Issue persists across multiple (all?) Chromebooks until this day, on Chrome OS 74.
Any news on a potential fix?
