### ISSUE TITLE
Help! Downloaded crouton on toshiba chromebook but none of the sound is working. 

### ISSUE THREAD

**Issue by spicycowpie** [dnschneid/crouton#3893]
Hi, I recently got a toshiba chromebook and downloaded crouton onto it. [This](https://www.youtube.com/watch?v=7KGcd9sSQok) is the tutorial I used (if it helps). I tried unistalling alsa and pulsevolume(whatever its called) and I can't figure out what I need to do too play volume.

**Comment by jvschiavo** [comment]
Did you just use `sh ~/Downloads/crouton -e -t unity`? Please past the output of the command `sudo edit-chroot -all` on your shell terminal.
