### ISSUE TITLE
Chromebook Shutdown While In Chroot

### ISSUE THREAD

**Issue by TheMinigun** [dnschneid/crouton#3895]
My Chrome OS crashes in the background. And then when I try to shut my Chromebook down while still in the chroot by holding down the power key it comes back up with the infamous "Chrome OS Is Missing Or Damaged" then I have to recover and reset the entire Chromebook. Please send help as this has never happened before and it is annoying that this happens. Also I cant do sudo edit-chroot all because I have not gotten around to installing a chroot again.

**Comment by DennisLfromGA** [comment]
@TheMinigun,

- Would you please show us the first five lines displayed at: `chrome://version`
- What did you have installed in your chroot and running when this happened?
- What happened if you just exited the chroot?

- If you have a chroot installed again, please show us the output of: `sudo edit-chroot -all`

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheMinigun** [comment]
Yes I can. 

Google Chrome | 68.0.3440.118 (Official Build) (64-bit)
-- | --
Revision | a7ca4397b06108b300bc00c52932eaeae010e662-refs/branch-heads/3440@{#808}
Platform | 10718.88.2 (Official Build) stable-channel peppy
Firmware Version | Google_Peppy.4389.117.0

I had Minecraft and Java

It would not let me exit the chroot because chrome OS  was not open (because it had crashed) for the computer to go to.

**Comment by DennisLfromGA** [comment]
@TheMinigun,

I don't think Chrome OS will crash and not take down the chroot that it's running under.
Maybe it was not a full crash but unresponsive. 

Sometimes you can still get to VT2 using <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F2</kbd> and run `sudo restart ui`.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheMinigun** [comment]
OK I will thy this and come back if it works. Thanks

**Comment by TheMinigun** [comment]
Also Just a quick question is there a way to install items straight out of the box (like java)?

**Comment by TheMinigun** [comment]
ctrl+alt+F2 doesn't open VT2 while in a chroot.

**Comment by DennisLfromGA** [comment]
@TheMinigun,

Let's leave this discussion in this issue, I'm closing #3896.

-----
<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F2</kbd> works just fne for me, whether I'm in a chroot or not.
Does it work for you when you are *not* in a chroot?

-**DennisLfromGA**

**Comment by TheMinigun** [comment]
Yes  ctrl+alt+f2 does work in normal Chrome OS i have tried even turning on the function keys and that does not work inside of the chroot either. No I have not had the issue of chrome not responding but it has happened multiple times before and I don't like having to recover my chromebook.

**Comment by TheMinigun** [comment]
Also in case this helps I am using an Acer C720 chromebook. (one of the best chromebooks in my opinion)

**Comment by DennisLfromGA** [comment]
@TheMinigun,

> No I have not had the issue of chrome not responding but it has happened multiple times before and I don't like having to recover my chromebook.

That's good news.

You can ease the pain of recovering by backing up your important files & folders in ~/Downloads, setting up syncing of apps, extensions, and other important things, and backing up your chroots to external media.

Closing. Please re-open if this issue is still a concern.

-**DennisLfromGA**

**Comment by TheMinigun** [comment]
@DennisLfromGA How does one go about backing up a chroot? Do you use chrome recovery utility?

**Comment by DennisLfromGA** [comment]
@TheMinigun,

https://github.com/dnschneid/crouton#a-backup-a-day-keeps-the-price-gouging-data-restoration-services-away

https://github.com/dnschneid/crouton/wiki/Backups

-**DennisLfromGA**
