### ISSUE TITLE
ctrl+alt+F2 doesn't open VT2 while in a chroot.

### ISSUE THREAD

**Issue by TheMinigun** [dnschneid/crouton#3896]
_Originally posted by @TheMinigun in https://github.com/dnschneid/crouton/issues/3895#issuecomment-424135080_

**Comment by TheMinigun** [comment]
Yes I tried it and it did not work. 
This is the output of sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20180718130616~master:5d4c3014
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,extension
host: version 10718.88.2 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Aug 22 02:17:40 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

**Comment by DennisLfromGA** [comment]
Closing, this issue is being discussed in #3895.
