### ISSUE TITLE
Error starting crouton

### ISSUE THREAD

**Issue by mtira** [dnschneid/crouton#3900]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20180718130616~master:5d4c3014
release: xenial
architecture: armhf
xmethod: xorg
targets: kde
host: version 9460.60.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Jun 5 16:56:40 PDT 2017 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
When I type sudo startkde it fails and produces this code:

uild Date: 14 June 2018  05:10:24PM
xorg-server 2:1.19.6-1ubuntu4~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Sep 28 15:45:48 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
method return time=1538163948.757710 sender=:1.13 -> destination=:1.63 serial=942 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
method return time=1538163949.140378 sender=:1.13 -> destination=:1.64 serial=943 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
^C
Session terminated, terminating shell.../usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: unexpected signal 2
 ...terminated.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by jvschiavo** [comment]
This is a common error. First just restart your chromebook and try to launch it again. It may work.
If it doesn't work your build is probably old or some Chrome OS update might have broken it.
In this case just update your chroot:
`sudo sh ~/Downloads/crouton -u -n xenial`

If you are on a channel like beta/dev/canary which updates more frequently this is more likely to happen.

Hope this helps. :)
- jvschiavo

**Comment by bulldozerboy** [comment]
literally got the same error (apart from the error listing driver 0) and this fix didn't work. Help?

**Comment by DennisLfromGA** [comment]
@mtira,

Your 'armhf' device doesn't always play well with the 'xorg' xmethod. If it were me I'd try adding the 'xiwi' xmethod and see if it works better for you. You can do it with this:

- `sudo sh ~/Downloads/crouton -n xenial -t xiwi -u`

*Hope this helps,*
-**DennisLfromGA**
