### ISSUE TITLE
"Required key not available" can't unzip tor tar.xz package :/

### ISSUE THREAD

**Issue by acbdacaplaboa** [dnschneid/crouton#3901]
To get more online anonymity I have discovered Tor in kali linux, which i installed with
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
Im not used to kali, and im really confused as to why i can't unzip the package through the terminal or even open it with Xarchiver.

please help 

all it says is just required key not available and that it is exiting the failed "objective?" im not sure xd

**Comment by deltabravozulu** [comment]
Same.

**Comment by Asternitix** [comment]
this might be redundant, the fix should be the same as #3860
