### ISSUE TITLE
Auto Start a Program with bash script in  /etc/init.d/program

### ISSUE THREAD

**Issue by cmdwhoami** [dnschneid/crouton#3904]
Thank you for getting crouton to start at boot... Now I' stuck on figuring out how to auto start a program at boot along with crouton.

I have a bash script in /etc/init.d/ that starts the service with the command "service <program_name> start" or /etc/init.d/program_name start....

I tried "update-rc.d <program_name> defaults"
and "update-rc.d <program_name> enable"

I've also tried "systemctl enable <program_name>.service"

But no matter what I do I can't get this program to start at boot with crouton.

when i check the run levels of the program they are right... here is the init info of my script which should work.

```
#! /bin/sh
#######################################################
### SoftEther Client
#######################################################
### BEGIN INIT INFO
# Provides: vpnclient
# Required-Start: $all
# Required-Stop: $network $local_fs $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start VPN Client at boot time
# chkconfig: 345 44 56
# description: Start VPN Client at boot time.
# processname: vpnclient
### END INIT INFO
# /etc/init.d/vpnclient
###########################
```

**Comment by cmdwhoami** [comment]
I asked for help a second too soon. As soon as I posted this I found the answer...  by placing  /etc/init.d/vpnserver start in /etc/rc.local, as described in the LAMP section of the Running servers in crouton wiki page,

**Comment by DennisLfromGA** [comment]
Glad you got it figured out, thanx for the solution and letting us know what worked.

-**DennisLfromGA**
