### ISSUE TITLE
i cant access debuging features

### ISSUE THREAD

**Issue by PlasmonPlayz** [dnschneid/crouton#3907]
when i power wash and click on debugging features it says there was a issue and debugging features wasn't finished setting up completely

**Comment by DennisLfromGA** [comment]
@PlasmonPlayz,

There was a known [crbug #890898](https://bugs.chromium.org/p/chromium/issues/detail?id=890898) for this issue but it's been fixed and merged in R70-11021.B.

-**DennisLfromGA**
