### ISSUE TITLE
Cannot Finish Crouton update

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#3908]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: bin
encrypted: no
Entering /home/linux/bin...
/usr/local/bin/enter-chroot: 511: /usr/local/bin/enter-chroot: cannot create /var/run/crouton/home/linux/bin/etc/crouton/name: Directory nonexistent

Please describe your issue:
I try to update Crouton
using this command:
**sudo sh -e ~/Downloads/crouton -u -n stretch -p /home/linux/**

and it gets to this stage where this happens..
I'm not sure what to do now...
the volume won't mount.
![screenshot 2018-10-14 at 12 24 39 pm](https://user-images.githubusercontent.com/14049856/46919377-a555fa80-cfac-11e8-8ded-e18cf7e1caba.png)

Any help is appreciated.

**Comment by DennisLfromGA** [comment]
@Carl393,
```
> sudo edit-chroot -all
name: bin
encrypted: no
Entering /home/linux/bin...
/usr/local/bin/enter-chroot: 511: /usr/local/bin/enter-chroot: cannot create /var/run/crouton/home/linux/bin/etc/crouton/name: Directory nonexistent
```

You have your stretch chroot on internal storage at `/home/linux/chroots` but not in the default location at `/usr/local/chroots` so you'll need to specify `-c /home/linux/chroots` for the `edit-chroot` command.

> I try to update Crouton
using this command:
`sudo sh -e ~/Downloads/crouton -u -n stretch -p /home/linux/`

The image shows it having trouble with setting up an xmlcatalog, maybe that was just a transient network error or something worse but I'm not sure. If you haven't already I'd suggest trying to update it again - and again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Carl393** [comment]
I'm sorry I don't really understand
how do I use edit-chroot to change the default folder from:
 /usr/local/chroots/ 
to 
/home/linux/chroots

I'm guessing crouton is updating.. but when it does.. it cannot find the correct path to the chroot because it's assumed to be like you said.. /usr/local/chroots?

**Comment by Carl393** [comment]
Yes! Thanks for the reminder...
so updating the crouton... -p is for prefix...

-p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots **linked to
                /mnt/stateful_partition/crouton/chroots.**

In other words I installed the chroot to /home/linux/ by specifiying this as -p /home/linux/ but.. there's no way of changing how it is 'linked to' /mnt/stateful_partition/crouton/chroots ?

Sorry just trying to get this straight!!!

**Comment by DennisLfromGA** [comment]
@Carl393,

Even though you specified an alternate location for your `/chroot` & `/bin` **parent** folders with the '**-p**' option, `crouton` commands should still work fine. 

And if you provide the path to your '`/chroots`' folder with the '**-c**' option, then `edit-chroot`, `enter-chroot`, and your `start*` scripts should have no trouble either.

I use an alternate location for my chroots and don't have any issues at all even though my lchroots are *not* linked to `/mnt/stateful_partiton/chroots` -
```
chronos@localhost ~/Downloads $ ls -l /mnt/stateful_partition/crouton/
total 4.0K
drwxr-xr-x. 2 root root 4.0K Sep 18 20:46 shared
```
So I don't think that's necessary for things to work correctly.

*Hope this helps,*
-**DennisLfromGA**
