### ISSUE TITLE
black screen on sudo startgnome (bionic, xenial)

### ISSUE THREAD

**Issue by imeuro** [dnschneid/crouton#3915]
sudo edit-chroot -all:
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20181001133934~master:38012fdf
release: bionic
architecture: amd64
xmethod: xorg
targets: gnome,xorg,xiwi
host: version 10895.78.0 (Official Build) stable-channel swanky 
kernel: Linux localhost 4.4.141-14567-g26df737f0737 #1 SMP PREEMPT Wed Oct 3 23:41:45 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```

#### Please describe your issue:
black screen after starting gnome desktop via sudo startgnome command
output:
```
Cannot open /sys/class/tty/tty0/active: No such file or directory
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1540244830.763484 sender=:1.9 -> destination=:1.48 serial=673 reply_serial=2
   boolean true
```
then after some time i get the 
```Unmounting /mnt/stateful_partition/crouton/chroots/bionic...```

apps in xiwi window are ok 
ex. sudo startxiwi -b subl opens sublime text editor correcly in a window

already tried restoring an older chroot based on xenial (same gnome,xorg,xiwi targets) same black screen

#### If known, describe the steps to reproduce the issue:
just ```sudo startgnome``` after boot

does anyone got a clue on this?
thanks in advance! :)

**Comment by DennisLfromGA** [comment]
Try toggling the <kbd>full screen</kbd> / <kbd>F4</kbd> key on/off, that works for me with this or a similar issue.
I truly don't know what the root cause is but that workaround helps me.

*Hope this helps,*
-**DennisLfromGA**

**Comment by imeuro** [comment]
> Try toggling the full screen / F4 key on/off, that works for me with this or a similar issue.

Hi Dennis, i tried your advice but no luck for me... still stuck with a black screen
so far, the only partial success was adding the lxde target and now `sudo startlxde` bumps me in my chroot with some -sad- graphical environment... 

but i'd really like having my sooper cool gnome environment back

**Comment by DennisLfromGA** [comment]
Sorry that workaround didn't work for your issue.

One other thing you might want to try is installing the 'xiwi' target/xmethod, you can do that with an update like this: 

- `sudo sh ~/Downloads/crouton -n bionic -t xiwi -u`

That will change your default xmethod to xiwi but you can override it with the '-X' option in your start* scripts.

*Hope this helps,*
-**DennisLfromGA**
