### ISSUE TITLE
USB devices broken

### ISSUE THREAD

**Issue by Magnetesim** [dnschneid/crouton#3918]
thunar-volman: Unsupported USB device type "cdc_acm"

#### Please describe your issue:
Whenever connecting my arduino to try to upload some code, it says the above error message. This isn't specific for arduinos, but every single usb device I ever use. I have to connect my mouse before I type sudo startxfce4, then it works.

#### If known, describe the steps to reproduce the issue:
By connecting any usb device.

**Comment by DennisLfromGA** [comment]
> This isn't specific for arduinos, but every single usb device I ever use. I have to connect my mouse before I type sudo startxfce4, then it works.

That's unusual, so we know what you're working with please show us the output of: 

- `sudo edit-chroot -all`

-**DennisLfromGA**

**Comment by Magnetesim** [comment]
Sorry for responding so late.
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11021.51.0 (Official Build) beta-channel gnawty 
kernel: Linux localhost 4.4.153-15150-g43781e59fd96 #1 SMP PREEMPT Tue Oct 16 23:45:41 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
That looks like a very typical chroot, nothing out of the ordinary and a recent version of crouton too. 

Have you tried any other file managers besides Thunar? Perhaps installing `lxde` and the associated PCManFM file manager might get different results.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Magnetesim** [comment]
I installed it and connected it and it still didn’t work. Then I purged thunar and broke my desktop, but it still didn’t work. I tried plugging in a usb flash drive to see if it was just the arduino, and it didn’t work. It says on arduino that the permission is denied to /dev/ACM0. Maybe that helps?

**Comment by imeuro** [comment]
i have a similar issue with arduino IDE, and it's an ownership problem:
since the owner always defaults to root, i have to `sudo chown meuro /dev/ttyUSB0` before uploading any sketch

so maybe try to check the current ownership just after you insert any usb thing with an
`ls -la  /dev/ACM0`  (or any other name assigned to the usb thing)

and then, if it's not owned by your login user, throw a 
`sudo chown your_username /dev/ACM0`
