### ISSUE TITLE
Does this support the new Ubuntu 18.04 Cosmic Cuttlefish?

### ISSUE THREAD

**Issue by DeadRoblox** [dnschneid/crouton#3922]
Does this support Cosmic Cuttlefish? If so how do I update to it?

output of sudo edit-chroot -all name: trusty
```
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20180718130616~master:5d4c3014
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,extension
host: version 11151.11.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Oct 24 01:53:45 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by TheMinigun** [comment]
also this isnt an issue just asking

**Comment by DennisLfromGA** [comment]
> Does this support Cosmic Cuttlefish?

No, not yet. 
For a list of releases that crouton can install use the '-r list' option like: 

- `sudo sh ~/Downloads/crouton -r list`

The output of that command is shown below:
```
Downloading latest crouton installer...
########################################################################################################################### 100.0%
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch buster sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety! zesty! artful* bionic*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```
Please note that some of thoses releases are no longer supported and others are not yet supported.

> If so how do I update to it?

If you want to try the latest available ubuntu release that crouton can install - but not yet support, use the '-r [release]' option like this for example:

- `sudo sh ~/Downloads/crouton -r bionic -t lxde-desktop`

*Hope this helps,*
-**DennisLfromGA**

**Comment by dnschneid** [comment]
We should be adding new releases to the list, though...cosmic (18.10, not 18.04) is out now.

**Comment by TheMinigun** [comment]
Ok thanks!

**Comment by TheMinigun** [comment]
Also Just want to mention

> If you want to try the latest available ubuntu release that crouton can install - but not yet support, use the '-r [release]' option like this for example:

sudo sh ~/Downloads/crouton -r bionic -t lxde-desktop

You can do Gnome or Unity or whatever other distro you prefer.

**Comment by DarthFloopy** [comment]
Would this last command (‘sudo sh ~/Downloads/crouton -r bionic -t gnome-desktop’) give plain GNOME or the Ubuntu version of it, as in a normal 18.04 install? I want to use the second one.

**Comment by TheMinigun** [comment]
It gives the Ubuntu version of it. But I wouldn't recommend since the terminal doesn't launch.

**Comment by DarthFloopy** [comment]
" ... the terminal doesn't launch." Any clarification?
How did you test this?

**Comment by TheMinigun** [comment]
The terminal doesn't open on my chroot. I tested this with my chroot @DarthFloopy

**Comment by DennisLfromGA** [comment]
@DarthFloopy,

crouton has two gnome desktop targets to choose from, they are:
- gnome:  Installs the GNOME desktop environment. (Approx. 400MB)
This *mimimal* desktop installs these packages:
> --minimal evolution-data-server gnome-control-center \
        gnome-screensaver gnome-session $legacy_session_package \
        gnome-shell gnome-themes-standard gvfs-backends nautilus \
        unzip gtk2-engines-pixbuf pulseaudio

- gnome-desktop:  Installs GNOME along with common applications. (Approx. 1100MB)
This *meta* desktop installs all of the above plus these packages:
> ubuntu=ubuntu-gnome-desktop,task-gnome-desktop

I just now installed 'gnome-desktop' on my bionic release chroot and it launches just fine:
![screenshot from 2019-01-07 16-24-35](https://user-images.githubusercontent.com/3418772/50794778-16e6d180-129a-11e9-8eec-ddb8f1b33c8b.png)

I usually just use the lxde-desktop but I thought I'd test this myself.

*Hope this helps,*
-**DennisLfromGA**

**Comment by EnderNightLord-ChromeBook** [comment]
Well you better get ready cause 19.04 beta is already out... 

find the images here: http://cdimage.ubuntu.com/daily-live/current/

**Comment by TheMinigun** [comment]
Ok Thanks @DennisLfromGA

**Comment by DarthFloopy** [comment]
Thanks for everyone's input.
