### ISSUE TITLE
New Crouton version

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#3923]
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost /usr/local/bin $ sudo edit-chroot -all -c /home/linux
name: bin
encrypted: no
Entering /home/linux/bin...
**chroot: failed to run command '/usr/local/bin/croutonversion': No such file or directory**
```

I'm not sure what the above means....
#### Please describe your issue:
Ever since updating my chroot to version... everything is so slow...

I don't know what is going on.

**Comment by DennisLfromGA** [comment]
@Carl393,

I answered your first question in #3908.

> Ever since updating my chroot to version... everything is so slow...

What "version...." are you speaking of, did the `croutonversion` change when you updated?

> I don't know what is going on.

I don't know why it's slower after the update without more specifics.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Carl393** [comment]
Thank you for your help.
I keep encountering this error when I login to chroot (See photo)
![screenshot 2018-11-03 at 2 14 32 am](https://user-images.githubusercontent.com/14049856/47948819-7927fc80-df0e-11e8-9ecc-d430ffc06f87.png)

it will take like.. over a minute before it loads..
Plus it takes like over a minute to load xfce4... or doesn't show up at all

see second photo.
![screenshot 2018-11-03 at 2 18 02 am](https://user-images.githubusercontent.com/14049856/47948833-c0ae8880-df0e-11e8-83d3-86008c0eb3ff.png)
