### ISSUE TITLE
USB recognition on Xubuntu on crouton.

### ISSUE THREAD

**Issue by joey1801** [dnschneid/crouton#3924]
I am not familiar with PCs.
I am using Xubuntu with crouton.
The file manager does not connect the USB memory automatically.
Is this related to crouton?
I can confirm from / media / removable /.

**Comment by DennisLfromGA** [comment]
When you plug in your external media it should show up in the Chrome OS Files app *and* in your chroot's Files app. You may have to grant permission to mount it in the chroot so it may not be *automatic* but it should work.

*Hope this helps,*
-**DennisLfromGA**

**Comment by joey1801** [comment]
Thank you very much.
I wondered earlier that it was automatically displayed in the left pane of Thunar file manager.
I will examine the grant permission of chroot.
