### ISSUE TITLE
Ubuntu not updating or starting correctly after chromeos Update

### ISSUE THREAD

**Issue by 8shaks** [dnschneid/crouton#3926]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: unity
host: version 11021.56.0 (Official Build) stable-channel kip 
kernel: Linux localhost 4.4.153-15155-g656ec00c3ce2 #1 SMP PREEMPT Mon Oct 22 23:40:50 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
#### Please describe your issue:
I just updated my chromeos to version 70.0. After running `sudo startunity `my ubuntu sidebar and top navbar weren't appearing and I recieved this in my terminal:
```
5e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 10 August 2018  09:33:05AM
xorg-server 2:1.18.4-0ubuntu0.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Nov  3 17:32:21 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: unity
host: version 11021.56.0 (Official Build) stable-channel kip 
kernel: Linux localhost 4.4.153-15155-g656ec00c3ce2 #1 SMP PREEMPT Mon Oct 22 23:40:50 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
Kicking xrandr again
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
```
I tried updated my chroot(crouton?) after this with the command `sudo sh ~/Downloads/crouton -n xenial -u`. However this just gave me this error in the terminal:
```
mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
Upgrade process encountered error and will not continue.
mysql_upgrade failed with exit status 11
dpkg: error processing package mysql-server-5.7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-5.7; however:
  Package mysql-server-5.7 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-5.7
 mysql-server
Failed to complete chroot setup.
```

I am not sure what to do and need help. Any help is appreciated! Please ask for clarification if you need more information.

**Comment by DennisLfromGA** [comment]
@8shaks,

> I just updated my chromeos to version 70.0. After running sudo startunity my ubuntu sidebar and top navbar weren't appearing and I recieved this in my terminal:...

Often times when you get a Chrome OS update a crouton update is needed too.
I usually do the Chrome OS update and then launch my crouton desktop to see if it still works, if not I'll then perform a crouton update.

> dpkg: error processing package mysql-server-5.7 (--configure):

The 'mysql-server' errors will probably have to be fixed before you can update crouton successfully.
I would first use `sudo enter-chroot` and attempt to correct the errors with something like:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -f install
```
That *may* help to fix the 'mysql-server' errors, you may know more about it than me tho since I don't run any sql stuff.

Then exit and perform a crouton update.

*Hope this helps,*
-**DennisLfromGA**

**Comment by 8shaks** [comment]
Hey, so the sudo apt-get upgrade just gave me this error:

`mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
Upgrade process encountered error and will not continue.
mysql_upgrade failed with exit status 11
dpkg: error processing package mysql-server-5.7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-5.7; however:
  Package mysql-server-5.7 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mysql-server-5.7
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
Is there any way i can just delete the my-sql server so that I don't get the error when I upgrade crouton. I don't know why it is there in the first place. What command would remove my sql?

**Comment by 8shaks** [comment]
I ended up deleting my-sql and that solved the issue for me. I successfully update crouton however now the launcher on the left and navbar at the top do not apear when i run ```sudo startunity```, i just see my desktop and wallpaper. Here is the error I got when I run ```sudo startunity```:
```
Build Date: 10 August 2018  09:33:05AM
xorg-server 2:1.18.4-0ubuntu0.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.2.log", Time: Sun Nov  4 22:16:28 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 11021.56.0 (Official Build) stable-channel kip 
kernel: Linux localhost 4.4.153-15155-g656ec00c3ce2 #1 SMP PREEMPT Mon Oct 22 23:40:50 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Another instance of croutontriggerd running, waiting...
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
Kicking xrandr again
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
```
How can i make the left panel and top navbar appear?

**Comment by DennisLfromGA** [comment]
@8shaks,

> Kicking xrandr again
(II) AIGLX: Suspending AIGLX clients for VT switch

That error you're getting [was fixed & merged](https://github.com/dnschneid/crouton/pull/3086) quite a while back.
If that's the issue I'm not sure what might help but [a crouton dev suggested](https://github.com/dnschneid/crouton/issues/3023#issuecomment-285442604) running `xrandr --auto` as a possibility.

The Unity navbar & launcher issues *may* not be crouton related so I'd [google it](https://www.google.com/search?q=unity+navbar+and+launcher+not+displaying&rlz=1CAACAC_enUS812US814&oq=unity+navbar+and+launcher+not+displaying&aqs=chrome..69i57.16217j0j7&sourceid=chrome&ie=UTF-8) to see if anything helps.

*Hope this helps,*
-**DennisLfromGA**
