### ISSUE TITLE
Login incorrect when switching between ChromeOS and Ubuntu 

### ISSUE THREAD

**Issue by Anish0000** [dnschneid/crouton#3928]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by DennisLfromGA** [comment]
@Anish0000,

Can you please show us the complete command(s) you're entering and what specific errors you're getting.
And, if possible, show us the output of: `sudo edit-chroot -all`

-**DennisLfromGA**

**Comment by Anish0000** [comment]
1#First i log into chrome os
2#then ctrl+alt+->
3#then asked me to enterd me as local host login...here i entered the
detail i have entred during time of installation my name
4#then ask for password so enter the password which i have entrred durin
time of installation.
5#then theres a message login incoreect...

I tried multiple times but i cant get access to xfce..
Why is soo...
Please suggest me woking method plz

**Comment by DennisLfromGA** [comment]
@Anish0000,

When you press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>-></kbd> it opens up the Developers Console on VT2, that prompt is looking for a username of either 'root' or 'chronos' but that's not the preferred method to launch your crouton chroot(s).

The preferred way of doing it is as follows -
1. First sign-in to Chrome OS
2. Press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>t</kbd>
3. Enter `shell`
4. Enter `sudo startxfce4`

*Hope this helps,*
-**DennisLfromGA**
