### ISSUE TITLE
Cannot boot to Crouton after Ubuntu Cosmic update

### ISSUE THREAD

**Issue by Piipperi** [dnschneid/crouton#3929]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
I'm using Ubuntu on an external drive so how do I do this externally
#### Please describe your issue:
Ubuntu is not booting after I updated to Cosmic. If I try to boot to it, the booting takes really long and the result is a black screen, a bit of UI and crash after that.

#### If known, describe the steps to reproduce the issue:
Updated to Cosmic (18.10) via Software Update

**Comment by DennisLfromGA** [comment]
@Piipperi,

To get the croutonversion when you've installed your crouton chroot on external media plug it in and then look for the media name assigned to it under the `/media/removable/` directory. Once you have that name plug it into your command similar to the following:  

- `sudo "/media/removable/[media name]/bin/edit -chroot -all"`

Once we have those details we might be able to see what you've installed and help a little more.

*Hope this helps,*
-**DennisLfromGA**

**Comment by SaikoHaven** [comment]
@Piipperi 

Cosmic is not yet officially supported by crouton. Once it is, update your chroot, because it will be sad and old.
As for now, follow @DennisLfromGA for running the command when it's on another device.
