### ISSUE TITLE
/prepare.sh cannot create as Directory is nonexistent

### ISSUE THREAD

**Issue by fujiyama17** [dnschneid/crouton#3930]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20181001133934~master:38012fdf
release: kali-rolling
architecture: amd64
targets: core,audio,xfce
host: version 11151.11.0 (Official Build) dev-channel eve 
kernel: Linux localhost 4.4.159-15334-g388c74685442 #1 SMP PREEMPT Wed Oct 24 02:07:35 PDT 2018 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### Please describe your issue:

I get the following error:

Compiling CRAS (native)...
Installing CRAS...
/prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### If known, describe the steps to reproduce the issue:

I just ran:

sudo sh -e ~/Downloads/crouton -r kali-rolling -u -t core,audio,xfc

---

I have tried other targets, even just core, and this keeps coming up.  Can you assist?  Thank you!

**Comment by bitozoid** [comment]
Me too.

```
$ sudo edit-chroot -all
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20181001133934~master:38012fdf
release: kali-rolling
architecture: amd64
targets: xiwi,cli-extra,keyboard,xfce,extension
host: version 11021.56.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Mon Oct 22 23:38:25 PDT 2018 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
```

I did
```
sudo sh ~/Downloads/crouton -t xiwi,cli-extra,keyboard,xfce,extension -n kali -r kali-rolling
```

and got
```
...
Installing CRAS...
/prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
```

**Comment by fujiyama17** [comment]
I even made the directory, but I think it's in the chroot, not the chromeOS.  Not sure where to go from here...

**Comment by SamuelClyde** [comment]
> I even made the directory, but I think it's in the chroot, not the chromeOS. Not sure where to go from here...

Could you try making it in /mnt/stateful_partition/crouton/chroots/kali-rolling/usr/share/alsa/ ?

This seems to have worked for me for debian buster:
sudo mkdir /mnt/stateful_partition/crouton/chroots/buster/usr/share/alsa/alsa.conf.d

**Comment by fujiyama17** [comment]
@SamuelClyde that did it!  I can't thank you enough.  I am running kali-rolling in a KDE.  Thanks again!

**Comment by dnschneid** [comment]
Looks like the alsa configuration location has changed in Buster (and thus kali):

```
$ diff /usr/share/alsa/alsa.conf.old /usr/share/alsa/alsa.conf.new
11,17c11
<                       {
<                               @func concat
<                               strings [
<                                       { @func datadir }
<                                       "/alsa.conf.d/"
<                               ]
<                       }
---
>                       "/etc/alsa/conf.d"
```

That suggests two things:

1. Your workaround makes the installer finish, but I suspect audio won't work.
2. On systems with no /usr/share/alsa/alsa.conf.d, we should be writing the cras config to /etc/alsa/conf.d

**Comment by carsenk** [comment]
I can confirm I am getting this on the latest ChromeOS running the above command for crouton (latest)

```
Installing CRAS...
/prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
chronos@localhost / $ 
```

Trying to mkdir with sudo says Cannot create directory no such file or directory exists.

**Comment by Matrix-Guy** [comment]
Same problem as OP, adding the directory manually solved it

@carsenk You made sure to change 'buster' to 'kali-rolling' in the mkdir command?

For kali-rolling it would be this instead:
```
sudo mkdir /mnt/stateful_partition/crouton/chroots/kali-rolling/usr/share/alsa/alsa.conf.d
                                                       🡑 
```

**Comment by fujiyama17** [comment]
Thanks everyone.  I made the directory and voila, no problems.

**Comment by kapilhp** [comment]
That is odd. How did you test sound? I usually just do `aplay /usr/share/sounds/alsa/Front_Left.wav`.

**Comment by mikehgentry** [comment]
Ah, my bad. I tried playing a video on Firefox, and Battle for Wesnoth, neither of which worked - but you're right, aplay does. I'll investigate those.

Thank you.

**Comment by Alan-Penkar** [comment]
I have this issue (fails to install)- however when I manually add the directory I get the error 'UID 1000 not found in Kali" (named chroot since I have a couple)

**Comment by Knightlycat** [comment]
I tried, and then I tried to run it again.

**Comment by actionjaxon** [comment]
I'm having the same issue as knightlycat. I'm on a Samsung Chromebook3 

The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 linux-libc-dev:i386
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (native)...
Installing CRAS...
/prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

Any ideas on how to fix?

**Comment by actionjaxon** [comment]
Installed kali linux finally!

After power wash and re-entering developer mode, was able to 
sudo mkdir /mnt/stateful_partition/crouton/chroots/kali-rolling/usr/share/alsa/alsa.conf.d  
Then entered:
sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce

**Comment by Knightlycat** [comment]
How? I had to go back and make all the directories from kali-rolling and up, and after trying to execute the command, It wouldn't let me because there were things already in it. power washing it..?


I'll try to update it when I finish making it, though I feel like there will be the same consequence..
