### ISSUE TITLE
Audio problem with v70 and "buster"?

### ISSUE THREAD

**Issue by kapilhp** [dnschneid/crouton#3931]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: buster
encrypted: yes, unlocked
Entering /media/removable/sublin/chroots/buster...
crouton: version 1-20181001133934~master:38012fdf
release: buster
architecture: armhf
xmethod: xiwi
targets: xiwi,cli-extra
host: version 11021.56.0 (Official Build) stable-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Oct 22 23:37:38 PDT 2018 armv7l GNU/Linux
freon: yes

#### Please describe your issue:

Recently updated to v70. Audio playback does not work. Updating the chroot as suggested in the wiki does not work either.

Will investigate this more. Just put this bug out here so that others can chime in! (Or not, if their audio is not working ...)

#### If known, describe the steps to reproduce the issue:

Start `crouton` "buster" chroot and try:

```
 $ aplay /usr/share/sounds/alsa/Rear_Center.wav  
 ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
 ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
 ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
 ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
 ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
 ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
 ALSA lib conf.c:5034:(snd_config_expand) Evaluate error: No such file or directory
 ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
aplay: main:828: audio open error: No such file or directory
```

**Comment by kapilhp** [comment]
To check this I tried to do a fresh install of "buster" with target `cli-extra`. I got the error message
```
Compiling CRAS (native)...
Installing CRAS...
/prepare.sh: 1180: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent

This also appeared in #3930 and so the errors are likely to be related.

**Comment by dnschneid** [comment]
Merging into #3930
