### ISSUE TITLE
Slow c302 on kde xorg

### ISSUE THREAD

**Issue by danielfm123** [dnschneid/crouton#3933]
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20181001133934~master:38012fdf
release: bionic
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,xorg,x11,kde,extension,cli-extra
host: version 11021.56.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-18546-g285bb8d836e6 #1 SMP PREEMPT Mon Oct 22 23:44:17 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```

#### Please describe your issue:

I installed kde on bionic, and it works perfect for a while and then from time to time it gets stuck and very unresponsive.

meanwhile xiwi session (startkde -X xiwi) works perfect

#### If known, describe the steps to reproduce the issue:

startkde -X xorg

**Comment by gavinfernandes2012** [comment]
I'm getting similar responsiveness issues on my CBPro with bionic and gnome.
I don't have issues on xenial though, did you try xenial?

**Comment by danielfm123** [comment]
xiwi is what i need and works fine.... and my chroot is too tuned;
https://imgur.com/a/T3cO5Wk
https://imgur.com/a/uklpRfk 

i was just reporting
btw i tried padoka drivers and wasnt fixed

**Comment by danielfm123** [comment]
aahhh what i did was to install xfce, it worked fine, but chrome didnt.

**Comment by danielfm123** [comment]
just want to add... xfce works fine but chrome on xfce is slow as kde was

**Comment by gavinfernandes2012** [comment]
@danielfm123 If you still want to try and get plasma working on bionic, you could try the workaround I've described in #3988 , if that doesn't work then you could try replacing "sna" with "uxa" in the 20-crouton.conf config file.

**Comment by gavinfernandes2012** [comment]
Could someone with write access mark this or #3988 as a duplicate @dnschneid @DennisLfromGA

**Comment by DennisLfromGA** [comment]
Dup of: 
- Slow gnome on bionic #3988  

Closing, please track there.

**Comment by gavinfernandes2012** [comment]
Thanks! @DennisLfromGA
