### ISSUE TITLE
chroot blocks after Chrome Version 70.0.3538.76 (Official Build) (64-bit) update

### ISSUE THREAD

**Issue by nynymike** [dnschneid/crouton#3934]
```
targets: gnome-desktop,x11,extension
host: version 11021.56.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.153-15155-g656ec00c3ce2 #1 SMP PREEMPT Mon Oct 22 23:38:49 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/gtrusty...
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20181001133934~master:38012fdf
release: trusty
architecture: amd64
xmethod: xorg
targets: unity,extension
host: version 11021.56.0 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.153-15155-g656ec00c3ce2 #1 SMP PREEMPT Mon Oct 22 23:38:49 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
I'm using a PixelBook2. I've been using my trusty chroot as my main desktop for about six months. After installing the lastest update to ChromeOS 70.0.3538.76, things have gotten really bad. Frequently--every few minutes, but sometimes every few seconds--the chroot becomes totally unresponsive: the mouse is frozen, even a web page will stop loading.  Even more frequently, my USB mouse stops working. Weirdly, when I swtich from my chroot to chrome, my video (on ChromeOS) is messed up (it looks like it switched to 8 colors). I figured out I could fix the color issue by hitting the "night time color" button, but the freezing issue, and losing the mouse is really problematic. I noticed that if I switch to Chromeos, and then switch back to the chroot, it fixes the issue. 

I was wondering if the issue was specific to Ubuntu 14 or Unity. So I tried installing several other combinations: Xenial/Gnome, Bionic/Gnome, Stretch/Gnome, Trusty/Gnome... all had the same issue. So it doesn't seem to be related to which distribution or desktop I'm using. 

I'm wondering if anyone else is having this problem. Or if it's possibly a hardware issue. The weird thing is that everything was working perfectly before the update. My only complaint prior to this was that I kept losing Bluetooth. But it seems like the Bluetooth issue has been resolved by Google, but now it's been replaced with an even worse issue.

**Comment by DennisLfromGA** [comment]
@nynymike,

I have a Pixelbook on version 70.0.3538.76 with a trusty chroot, see below, and I'm not experiencing any of those issues.
```
chroot name: trusty
crouton: version 1-20180718130616~master:5d4c3014
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,gnome-desktop,lxde-desktop,xfce-desktop,cli-extra,keyboard,touch,chrome-beta
host: version 11021.56.0 (Official Build) beta-channel eve 
kernel: Linux localhost 4.4.153-15155-g656ec00c3ce2 #1 SMP PREEMPT Mon Oct 22 23:38:49 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
My croutonversion is a bit older than yours which is the latest but I don't think that's the problem.
I also have a xenial and bionic chroots which I don't use often but when I checked they seem to be working fine also.
I'll do a crouton update on my trusty chroot as soon as I finish a backup and see if that makes a difference, I'll let you know either way.

BTW, I always use the 'xiwi' xmethod not 'xorg' so that may be the difference but we'll see.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@nynymike,

**Update:**

----
When launching my desktop using the 'xorg' xmethod I did get the 8-bit-like color distortion when switching back into Chrome OS *but* I discovered I could quickly regain the full color pallette by switching into and out of VT2 by pressing <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F2</kbd> then <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>F1</kbd>.

I updated my trusty chroot:
```
chroot name: trusty
crouton: version 1-20181001133934~master:38012fdf
release: trusty
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,gnome-desktop,lxde-desktop,xfce-desktop,cli-extra,keyboard,touch,chrome-beta
host: version 11021.56.0 (Official Build) beta-channel eve 
kernel: Linux localhost 4.4.153-15155-g656ec00c3ce2 #1 SMP PREEMPT Mon Oct 22 23:38:49 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

But it didn't seem to change much if anything, I still get the color distortion when switching into Chrome OS but the workaround fixes it.

----
Just a suggestion but you might want to add the 'xiwi' xmethod and try it for a while, I love it and don't have any issues with it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by nynymike** [comment]
The color distortion is annoying, but it doesn't bother me that much. My main problem was the system freezing.  I can try to create a new distribution with `xiwi` to see if that helps.

Although, I'm sort of glad to hear you're also seeing the color issue, because I was worried it was a sign of a hardware problem.

**Comment by nynymike** [comment]
Is there any hope of xorg being fixed?
