### ISSUE TITLE
chronos@localhost can't open ~Downloads/crouton

### ISSUE THREAD

**Issue by Cyberation** [dnschneid/crouton#3935]
```
Please paste the output of the following command here: sudo edit-chroot -all
sudo: edit-chroot: command not found
```

#### Please describe your issue:
I'm trying to install Linux on my Pixelbook so I can do more. I'm specifically trying to install either Mint or Unity, as xfce was not what I wanted in a desktop. When I type in sudo sh ~Downloads/crouton -e -t touch,unity or sudo sh ~Downloads/crouton -e -t touch,mint it returns with "Can't open ~Downloads/crouton"

I've tried restarting, reinstalling, redownloading, and I have checked and confirmed that I am on my primary account, but nothing is working.

**Comment by gavinfernandes2012** [comment]
Is that a typo or is there no `/` between `~` and `Downloads` ?
You're supposed to enter:
```
~Downloads/crouton -e -t touch,unity
```

**Comment by Cyberation** [comment]
Thanks @gavinfernandes2012 @DennisLfromGA , I didn't realize that I wasn't including the '/' It's all working now, and I'm installing unity desktop as I type.

I'm pretty clueless when it comes to this kind of stuff, so thank you so much for helping me.
