### ISSUE TITLE
debian buster  wont install

### ISSUE THREAD

**Issue by danielfm123** [dnschneid/crouton#3936]
#### Please describe your issue:

sudo sh ./crouton -t xiwi,keyboard,extension,cli-extra,audio -r buster -n debian -m http://ftp.cl.debian.org/debian/ wont work

#### If known, describe the steps to reproduce the issue:

sudo sh ./crouton -t xiwi,keyboard,extension,cli-extra,audio -r buster -n debian -m http://ftp.cl.debian.org/debian/

will fail on something related to audio

**Comment by mikehgentry** [comment]
This is a duplicate of #3930

**Comment by mikehgentry** [comment]
Read the rest of the bug
