### ISSUE TITLE
Precise isn't found

### ISSUE THREAD

**Issue by SisterSoda** [dnschneid/crouton#3940]
```
/mnt/stateful_partition/crouton/chroots/precise not found.
```

I'm new to crouton and I downloaded precise 12.04. I've tried to update it but it continues to show this message(above). I've tried multiple commands but none of them work. I'd gladly appreciate it if someone could help me with my problem. Thanks!

**Comment by DennisLfromGA** [comment]
To add, crouton has tagged the precise release with an exclamation mark `!` and the following note:

> Releases marked with ! are upstream end-of-life, and should be avoided. 

If you run the crouton command with the '`-r list`' option you'll see which releases are supported and which are not -
```
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy jessie stretch buster sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty utopic! vivid! wily! xenial yakkety! zesty! artful* bionic*

Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```


*Hope this helps,*
-**DennisLfromGA**

**Comment by SisterSoda** [comment]
`/usr/local/chroots/xenial` already has stuff in it!`

I tried the first command but the message above is the only thing that appears.

**Comment by SisterSoda** [comment]
Thanks!

**Comment by SisterSoda** [comment]
Now its told me to enter-chroot, what should I enter here?

**Comment by DennisLfromGA** [comment]
Let it, especially if it says something like:

> 'A chroot setup script still exists inside the chroot.'

It will then attempt to resume the installation.

*Hope this helps,*
-**DennisLfromGA**

**Comment by SisterSoda** [comment]
"You can enter the chroot using enter-chroot."

This is what it tells me after, I'm not sure what command I'm supposed to place here.

**Comment by DennisLfromGA** [comment]
Okay, it appears to have finished the installation successfully.

Please show us the output of: `sudo edit-chroot -all`
Then we can tell what desktop(s) you installed and other pertinent info.

*Hope this helps,*
-**DennisLfromGA**

**Comment by SisterSoda** [comment]
`crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11021.56.0 (Official Build) stable-channel setzer 
kernel: Linux localhost 3.18.0-18546-g285bb8d836e6 #1 SMP PREEMPT Mon Oct 22 23:39:46 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/amelia as another instance is using it.
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`

That's the output of the: `sudo edit-chroot -all`

**Comment by DennisLfromGA** [comment]
Okay, thanx, that's most of it.

The command to launch your desktop is the one above and here:

- `sudo startxfce4 -n xenial`

*Hope this helps,*
-**DennisLfromGA**
