### ISSUE TITLE
OpenWRT support

### ISSUE THREAD

**Issue by sr229** [dnschneid/crouton#3941]
#### Please describe your issue:

OpenWRT is a Linux distribution focused for routers. While the nature of the project is such, they provide `x86` and `x86_64` images, and tarballs for the rootfs. Recommend we support OpenWRT as well since its a very minimal and small Linux distribution

**Comment by DennisLfromGA** [comment]
The network configuration in a crouton chroot is controlled by Chrome OS so I believe this would have to be implemented in Chrome OS and not in the chroot.

*Hope this helps,*
-**DennisLfromGA**
