### ISSUE TITLE
Xiwi: Implement mouselock

### ISSUE THREAD

**Issue by SaikoHaven** [dnschneid/crouton#3942]
```
name: KVMWeb
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/KVMWeb...
crouton: version 1-20181001133934~master:38012fdf
release: bionic
architecture: amd64
xmethod: xorg
targets: xfce,xorg,xiwi,touch,chrome
host: version 11021.56.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-18546-g285bb8d836e6 #1 SMP PREEMPT Mon Oct 22 23:32:29 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/KVMWeb...
```

#### Please describe your issue:
Half-Life (Steam version) as well as other games, Mouselock not usable.
Instead, moving the mouse makes the game have a seizure, until i stop moving the mouse.
#### If known, describe the steps to reproduce the issue:
run `sudo enter-chroot` then open steam via xiwi, then run half-life, (or any game) move the mouse and watch it go insane.

**Comment by dnschneid** [comment]
I guess we'd have to detect a mouse lock in X (is that even possible?) and then use https://www.chromium.org/developers/design-documents/mouse-lock somehow?

**Comment by SaikoHaven** [comment]
Well, WebQuake can do it. (webapp for chrome to play quake) As well as most web tabs, so maybe if we use the way they do it, you can maybe have a mouselock option at the commandline? for example: `sudo startxfce4 -X xiwi --mouse-lock`

**Comment by SaikoHaven** [comment]
@dnschneid i think it maybe wayland related though, as I had the same issue on crostini.
