### ISSUE TITLE
Are MediaTek 8173C Processors compatible with crouton?

### ISSUE THREAD

**Issue by DarthFloopy** [dnschneid/crouton#3946]
The MediaTek 8173C Processor is ARM-based.
Specifically, I am looking to buy a Lenovo 300e Chromebook in the near future, and I want to make sure I can use crouton (even though ARM doesn't work with e. g. Steam).
Thanks!

**Comment by DennisLfromGA** [comment]
Short answer: Yes

The Acer Chromebook R13 is one of the most popular Chromebooks and has had great success with crouton. It too uses the MT8173 along with the Lenovo 300e and other devices with baseboard 'oak'.

See [this page](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices#goog-ws-list-table) and below for reference -

![image](https://user-images.githubusercontent.com/3418772/48969701-4d111000-efd0-11e8-93cc-fbca707ab1c5.png)

*Hope this helps,*
-**DennisLfromGA**

**Comment by DarthFloopy** [comment]
Thanks! Very helpful!
