### ISSUE TITLE
Crouton Crashing On Chromebook

### ISSUE THREAD

**Issue by HRA2000** [dnschneid/crouton#3950]
When I Do sudo startxfce4, my chromebook crashes and be stuck on black screen and i have to force it to shutdown to go back to chrome OS. is there a way to fix this?

**Comment by DennisLfromGA** [comment]
#### Please show us the output of: `sudo edit-chroot -all`

**Comment by HRA2000** [comment]
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20181001133934~master:38012fdf
release: trusty
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11298.0.0 (Official Build) canary-channel celes 
kernel: Linux localhost 3.18.0-18738-gdf8697848d55 #1 SMP PREEMPT Mon Nov 26 04:02:56 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by DennisLfromGA** [comment]
@HRA2000,

- When did it start doing this, after a Chrome OS update, a crouton chroot update, etc.?
- Do you get any error messages at all?
- Will it switch back to Chrome OS when you press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>F1/F2</kbd>?
- Will the display come back if you toggle the <kbd>full screen</kbd> key?

-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Okay, thanx for the feedback and glad it's working again.

Closing. Please re-open if this issue is still a concern.
