### ISSUE TITLE
Intermittent screen freezing in KDE, Gnome.

### ISSUE THREAD

**Issue by quigley-c** [dnschneid/crouton#3957]
```
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20180718130616~master:5d4c3014
release: sid
architecture: amd64
xmethod: xorg
targets: kde,gnome
host: version 11307.0.0 (Official Build) dev-channel eve 
kernel: Linux localhost 4.4.164-15528-gf88dc13ea0a3 #1 SMP PREEMPT Wed Nov 28 03:36:41 PST 2018 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/sid as another instance is using it.
```

#### Please describe your issue:
Running Google Pixelbook i5, 2018,
Intermittently during regular use screen will freeze for a few seconds at a time then recover. Seems to be graphical as keyboard shortcuts and in-progress apps appear as though nothing has interrupted them, screen updates appropriately afterward.

Length of freeze is variable, ranging from a few seconds to a full lock-up. Most serious freeze forced a reboot, though this has only happened once. More graphically intensive apps seem to cause more serious freezes. Often a freeze will cause the screen to refuse to update so long as I remain in the current workspace. Swapping workspaces allows the screen to update, and I can swap back and continue using whatever app I had been. Commonly when using such applications I won't be able to trigger a screen update from inside chroot, will need to swap back to chromeOS to force the screen to update, then can always switch back to chroot with a now-working updated screen. Never had chroot become unusable during such transitions.

Tried running chroot with every version of Debian available, same issue. 

Currently running on debian sid with a bspwm wm, launching chroot with ```sudo enter-chroot``` followed by ```xinit```

#### If known, describe the steps to reproduce the issue:
Seems to have something to do with hardware acceleration. Animation of any kind has a chance to cause it. Everything from loading Gif's in Firefox to opening an openGL application. Triggers often when using Gimp for example. Chromium locks up the screen like crazy, making the chroot nearly unusable until switching to another workspace. Problem only persists as long as the apps are on-screen, having them open in another workspace seems to have no effect on freezing. Working with only a terminal open rarely causes freezes.

I've been running this chroot env. for a few months now, freezing is only persistent enough to be annoying, not enough to deter me from working seriously. As I mentioned, working with only a terminal open doesn't cause much freezing.

**Comment by Lightsockie** [comment]
Seconding with same symptoms, also on the new Google Pixel. Using whatever the default ubuntu version (pending #3955 being accepted). I use awesome, but looks like I flirted with that lxde target (it isn't called though). No Gnome or KDE for me, so I think it's unrelated to that. 
```
name: cancer
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/cancer...
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: audio,chrome-dev,core,cli-extra,extension,xorg,xiwi,lxde,touch
host: version 11151.51.0 (Official Build) beta-channel eve 
kernel: Linux localhost 4.4.159-15346-gc5e629939ae0 #1 SMP PREEMPT Mon Dec 3 22:41:11 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/cancer...
```

[From another project](https://github.com/lcpz/awesome-copycats/issues/236), totally unrelated to this, I had an issue with intermittent freezing because the main thread was being hog'd by a hanging NFS share timing out (the "issue" was traced back to glib). This feels similar to it. I wonder if something similar is happening here where the main thread is getting caught up with something?

**Comment by gavinfernandes2012** [comment]
@quigley-c Could you try the workaround I described in #3988 , my problem there also had to do with hardware acceleration, so it might be related, although it does seem like a bit of a long shot.

**Comment by quigley-c** [comment]
As soon as I apply the fix from #3988 I am no longer able to launch crouton with xinit: no input devices found.
I don't have time to fiddle with this at the moment but I will continue to look into this in the future.

**Comment by gavinfernandes2012** [comment]
Airtight, thanks for checking

**Comment by caev** [comment]
I can confirm the #3988 workaround 

```
sudo cp /etc/crouton/xorg-intel-sna.conf /usr/share/X11/xorg.conf.d/20-crouton.conf
```

fixes the X11 freezes on my Pixelbook.  They've gone from several per day to none for a month.
