### ISSUE TITLE
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files

### ISSUE THREAD

**Issue by ndarilek** [dnschneid/crouton#3958]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: audio,gnome,xorg
host: version 70.3.34 (Developer Build - neverware) developer-build chromeover64
kernel: Linux localhost 4.14.74+ #3 SMP Wed Nov 28 02:54:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

I can't get audio working in any combination of targets/releases under ChromeOS 70.3 running on Neverware. I've seen this error message referenced in bunches of other issues, but they all seem focused on other problems, and not the issue that audio isn't working. I'm blind, need audio working so I can use accessibility services in chroots, so audio not working is a non-starter for me. This used to work at one point--maybe back in 66 or so--but I can't get it working on a fresh install.

I can see enough to tell that X seems to start, so I'm definitely getting to a desktop, but audio just doesn't work for me. I've seen occasional other errors, but these usually coincide with what appears to be a dark screen, and the graphical issues just aren't a priority for me right now. The audio error is common to every chroot combination I've tried, though.

These are brand new chroots, built with a fresh Crouton installation, so the issue *shouldn't* be a need to upgrade anything (unless I need to upgrade things out of the box for some reason.)

#### If known, describe the steps to reproduce the issue:

1. Start with ChromeOS 70.3, Neverware if possible.
2. Make a fresh installation of Crouton.
3. Create a chroot with any combinations of targets and releases, though be sure to include the audio target.
4. Enter the chroot and try running anything that uses audio. I can't get any audio out of my chroot--no system beeps in terminals, no speech from Orca, etc.

Thanks!

**Comment by TheMinigun** [comment]
I get this error too. I have had several chroots with this error on startup and I believe that this is just a harmless error.

**Comment by Amplespencer** [comment]
#3931

**Comment by ndarilek** [comment]
Not the same issue. To be clear, audio now works for me. My issue was 
that I needed the Orca screen reader running to even *know* whether 
audio works or not, and I couldn't get it running because locales aren't 
being built for en-US.UTF-8, which I had to do manually since the PR to 
do so hasn't been accepted.


Once that finished, I launched Orca and confirmed audio works. But now 
this harmless error gets printed whenever I switch from and to the 
chroot, which is a bit of an accessibility annoyance because it makes 
Chrome OS/Chromevox talk, and I can't interrupt it since I'm then in Linux.


So it would be nice to make this harmless error go away somehow. I 
realize to most folks it's something they can ignore, but to me as a 
blind user, I have to wait for Chromevox to stop reading it before I can 
interact with the chroot. Otherwise both Chromevox and Orca are speaking 
at once.


Thanks.

**Comment by BackTheNerd** [comment]
I get this issue when even trying to start the chroot envirement on my samsung chromebook.

**Comment by R0aringMars** [comment]
> I get this issue when even trying to start the chroot environment on my Samsung Chromebook.

This also happened to me.

**Comment by joehardy3030** [comment]
Same here, on Samsung Chromebook

**Comment by MrLbird** [comment]
vbnm,gb vh vbucks
![chill1](https://user-images.githubusercontent.com/63524770/84345985-e8e77a00-ab7c-11ea-98bb-8de0708be1d2.jpeg)

**Comment by mjonsson1986** [comment]
> 
> 
> OK, made some progress. I've been confusing CROS with CRAS, and that error made me think that audio wasn't working because CRAS wasn't configured. I eventually discovered that the gnome-desktop target is needed to get Orca installed, which would explain why Orca wasn't launching. I also discovered that volume keys don't trigger Ubuntu's default audio indicator even when the audio target is working, and also that gnome-terminal and other apps don't launch because locales aren't configured, so my trick of launching a terminal and pressing backspace to trigger a system beep wasn't even getting to the terminal. :) I've now got things working somewhat.
> 
> So I'd probably be OK with closing this, but what is this service, why is it not found in any combination of targets I create, and if it's harmless then can the errors be removed from the startup sequence so folks like me aren't confused by them? :) An error message like that makes me think that I've either done something wrong, or that I'll be in for a world of hurt at some point in the future when something I count on doesn't work.
> 
> Thanks.

how do you generate locales manualy?

**Comment by ndarilek** [comment]
I'd have to google it for you--I do every time for myself as well. Maybe 
`dpkg-reconfigure locales && locale-gen`?

**Comment by mjonsson1986** [comment]
yes yes but good luck to do the reconfigure with chromevox because 
chromevox dont see the window


Den 15 juli 2020 15:00:52 skrev Nolan Darilek <notifications@github.com>:

**Comment by VelocityDesign** [comment]
Hey, I'm still getting this error.
Google Chrome: Version 86.0.4240.112 (Official Build)  (64-bit)
Platform: 13421.73.0 (Official Build) stable-channel snappy
Channel: stable-channel
Firmware Version: Google_Snappy.9042.244.0
ARC Enabled: true
ARC: 6912093
Enterprise Enrolled: false
Developer Mode: true
Running Debian Sid with Gnome
