### ISSUE TITLE
Can not stop using proxy specified by -P option

### ISSUE THREAD

**Issue by verniyb** [dnschneid/crouton#3961]
I used
`sudo bash crouton -t kde-desktop -u -P 127.0.0.1:1080`
to update my installation of ubuntu xenial.
Then I used <Crtl+C>  to stop downloading and started again without '-P' option:
`sudo bash crouton -t kde-desktop -u`
but the script still attempted to connect to my local proxy 127.0.0.1:1080
I tried to close the shell tab and restart my chromeos, but it did not work.

**Comment by dnschneid** [comment]
Use `-P ''` (that's an empty set of single quotes) to remove the proxy setting.
