### ISSUE TITLE
Error installing kali linux.

### ISSUE THREAD

**Issue by Knightlycat** [dnschneid/crouton#3962]
I was installing kali linux with the normal sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
and it was installing fine... until: 

alsa-utils is already the newest version (1.1.7-1).
libasound2 is already the newest version (1.1.7-1+b1).
libspeexdsp1 is already the newest version (1.2~rc1.2-1+b2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:8.2.0-2).
libc6-dev is already the newest version (2.27-8).
libspeexdsp-dev is already the newest version (1.2~rc1.2-1+b2).
pkg-config is already the newest version (0.29-4+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libasound2-dev is already the newest version (1.1.7-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.6-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (native)...
Installing CRAS...
/prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
chronos@localhost / $ 

I tried updating it with sudo sh -e ~/Downloads/crouton -u -n kali-rolling, but i got the same error.

**Comment by DennisLfromGA** [comment]
@Knightlycat,

There's a PR https://github.com/dnschneid/crouton/pull/3955 to fix this issue but it hasn't been reviewed and merged yet, hopefully soon.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Knightlycat** [comment]
I hope it gets fixed soon..

**Comment by DennisLfromGA** [comment]
Closing, please track on duplicate issue #3930.
