### ISSUE TITLE
Q: Will using the "core" target change chroot default from X to Wayland?

### ISSUE THREAD

**Issue by SaikoHaven** [dnschneid/crouton#3963]
I did some poking around to see what core did, and I saw it depends on host-wayland.

I may be crazily stupid, but will it change the chroot default from X to Wayland?

**Comment by DennisLfromGA** [comment]
@SaikoHaven,

Short answer: No

Longer answer:
I'm not sure '*depends on*' is the right term, `core` does install both `host-dbus` & `host-wayland` in the `chroot-bin` folder but `host-wayland` is not necessarily employed.  

Both `brightness` and `croutonpowerd` along with `freon` do require and employ `host-dbus`.

Also, both the `xorg` & `xiwi` xmethods require the `core` target so if you install any desktop you'll be getting and using `core`.

If you're interested in running the wayland server check out the below links:
- [Wayland Notes](https://github.com/dnschneid/crouton/wiki/Wayland-Notes)
- [Running Wayland compositors using ChromeOS's Wayland server?](https://github.com/dnschneid/crouton/issues/3680)

*Hope this helps,*
-**DennisLfromGA**

**Comment by Asternitix** [comment]
core is needed for e17 as far as I know.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
