### ISSUE TITLE
(question) chrooting to another linux instalaltion? 

### ISSUE THREAD

**Issue by rinaldohack** [dnschneid/crouton#3966]
this is a question. Is it possible if I run crouton on cloudready, but it chroot to my installation of ... lets say another ubuntu in another partition?  

Crouton with xiwi does work in cloudready, so good job on that.

**Comment by kapilhp** [comment]
Within crouton you can use various Debian/Ubuntu utilities to mount and use chroots. For example, plain old 'chroot' (after mounting of course) or 'schroot'. Some other techniques like 'lxc' or 'kvm' etc may not work if the kernel support is not present.

On the other hand, to "directly" use crouton to enter a non-crouton partition with chroot may require creation of new scripts to do so and also some compilations for 'cras' and 'xorg' support.

**Comment by Asternitix** [comment]
good luck
