### ISSUE TITLE
Method http has died unexpectedly.

### ISSUE THREAD

**Issue by F4LK5** [dnschneid/crouton#3969]
```
name: LXDE
encrypted: yes, locked
Unmounting /media/removable/Chroot/chroots/LXDE...
```

#### Please describe your issue:
Any attempt to update or install via apt-get results in Method http has died unexpectedly

#### If known, describe the steps to reproduce the issue:
sudo apt-get install <literally anything>
sudo apt-get install update

I can see there are many such issues similar to this, but none have a resolution and most are years old. Is this an issue that has been ignored? Will it ever be fixed?

**Comment by kapilhp** [comment]
Please at least link the older issue #2688.

**Comment by DennisLfromGA** [comment]
Closing, please track on issue #2688 as noted above.
