### ISSUE TITLE
Android VPN & Root

### ISSUE THREAD

**Issue by rj45jack** [dnschneid/crouton#3970]
```
`chronos@localhost / $ sudo edit-chroot -all -c /media/removable/SD\ Card/linux/ubuntu/chroots
name: xenial
encrypted: no
Entering /media/removable/SD Card/linux/ubuntu/chroots/xenial...
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce,extension,xorg,xiwi
host: version 11151.59.0 (Official Build) beta-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Mon Dec 10 23:49:58 PST 2018 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /media/removable/SD Card/linux/ubuntu/chroots/xenial...`
```

#### Please describe your issue:

I'm unsure if this expected behavior or not but here it goes;

When I use an Android VPN app, PIA to be specific, it appears that traffic is not routed through the tunnel when using sudo or root as a user in Ubuntu or Kali. Screenshot shows Ubuntu running the browser. One as myself and the other as sudo/root. The one as myself is traffic routed through the VPN.

![screenshot_2018-12-20_09-08-58](https://user-images.githubusercontent.com/16903209/50287728-10530000-043a-11e9-9647-a8a7e7b00d5c.jpg)

This presents an issue with Kali as most tools need to run as root and for security professionals, using a VPN for work is very common.

#### If known, describe the steps to reproduce the issue:
1. Connect to VPN via Android App
2. Launch chroot Ubuntu or Kali
3. Open a browser as yourself and navigate to "icanhazip.com" note the IP
4. Open a terminal and run a browser as root or sudo. eg "sudo dillo"
5. Navigate to the same address as in step 3. Note the IP.

**Comment by Asternitix** [comment]
make sure shill is blacklisting tun0. that will change chroot behavior a bit. hope it helps give thumbs if this helped.

**Comment by rj45jack** [comment]
> make sure shill is blacklisting tun0. that will change chroot behavior a bit. hope it helps give thumbs if this helped.

No difference. I blacklisted tun0, and the name of the virtual adapter, which is arcbr0. Neither made a difference. All "root/sudo" traffic is still routed around the VPN/Tunnel.

Thanks,

**Comment by Asternitix** [comment]
Use a firewall and block all traffic not going through the tunnel.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rj45jack** [comment]
I'll admit I don't know the finer details of ChromeOS's networking stack. But it appears that no tun adapter is created when using the Android app or the Chrome extension. With that said, I was able to use the root account on ChromeOS to launch OpenVPN after blacklisting tun0 all from the shell. This gave me the tun0 adapter, which in turn does successfully show up inside Ubuntu and Kali. All traffic, root or not is routed through tun0.

I will call this closed as the root of the issue is ChromeOS not creating an actual tunnel adapter, again I'm not sure how/what/why it is like that, it just is. So my solution, if anyone is interested, is connect using the built in OpenVPN application that is available to the root user in the shell.
