### ISSUE TITLE
Not a bug, but whatever. it's a stupid logo. delete this if you want. i don't care.

### ISSUE THREAD

**Issue by hvhpc4566** [dnschneid/crouton#3971]
i was bored. i was fascinated by crouton, i spent half an hour on a stupid logo. you're welcome.
![crouton](https://user-images.githubusercontent.com/36569935/50369239-b47e9900-0557-11e9-9555-5a1879dcbc6c.png)
yes i know, it looks like a sponge.

**Comment by dnschneid** [comment]
it looks like a sponge

a delicious, linux sponge

pretty sweet logo

**Comment by DennisLfromGA** [comment]
Too much olive oil??? 😅
