### ISSUE TITLE
debian xfce failure code 2

### ISSUE THREAD

**Issue by githubgnulinux** [dnschneid/crouton#3972]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
/mnt/stateful_partition/crouton/chroots/stretch...
crouton: version unknown
release:unknown
targets:keyboard,cli-extra,xfce
host:version 11021810 stable channel kip
kernel:4415315155g656ec00c3ce2 15-11-18
freon:yes
#### Please describe your issue:

-su:36:syntax error:unterminated quoted string
warning:starting chroot system dbus daemon failed with code 2

**Comment by DennisLfromGA** [comment]
@githubgnulinux,

> crouton: version unknown
release:unknown

The above seems to indicate that the chroot did not finish installing or was unsuccessful.
I'd try to do a crouton update and see if it helps, you can do that with:

- `sudo sh ~/Downloads/crouton -n stretch -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by githubgnulinux** [comment]
How to prevent automatical update of chromeos and crouton?

shell
sudo apt-get update

command not found

**Comment by DennisLfromGA** [comment]
@githubgnulinux,

> How to prevent automatical update of chromeos and crouton?

Chrome OS updates automatically without user intervention - or explicit permission.
There are things you can do when in Developer mode to prevent it but I'm not going to recommend it or tell you what to do. If you're intent on doing that then I'd just google it.

You have to update crouton manually with it's '-u' option. I usually only update crouton if there are major features or fixes that have rolled out or if a Chrome OS update breaks something.

> shell
sudo apt-get update

> command not found

Yes, that's expected in the shell. I asked that you use `sudo enter-chroot -n stretch` before running the update commands.

*Hope this helps,*
-**DennisLfromGA**

**Comment by githubgnulinux** [comment]
Yes, sorry forgot to add that the same error response is shown:

shell
sudo enter-chroot -n stretch

Entering /mnt/stateful.../stretch...
-su:36:syntax erroc:unterminated quoted string
warning:starting chroot system dbus daemon failed with code 2
-su:36:syntax erroc:unterminated quoted string
unmounting /mnt/.../stretch...
$

**Comment by DennisLfromGA** [comment]
@githubgnulinux,

Okay, thanx for the clarification.

I should have picked up on this earlier but you may be running into this issue:
- Cannot create files in `~/Downloads` #3860]

See this comment for a workaround:
- https://github.com/dnschneid/crouton/issues/3860#issuecomment-411264757

This should get fixed once the following PR is merged:
- Use sudo instead of su. #3956 

*Hope this helps,*
-**DennisLfromGA**

**Comment by githubgnulinux** [comment]
Sorry but do not understand the link: https://github.com/dnschneid/crouton/issues/3860#issuecomment-411264757

sudo -i -u stretch
sudo: unknown user: stretch
sudo: unable to initialize policy plugin
chronos@localhost / $ sudo -i -u "$USERNAME"
sudo: unknown user: 
sudo: unable to initialize policy plugin

> Use sudo instead of su. #3956

This is not understood because the command 'su' has not been used.

**Comment by githubgnulinux** [comment]
sudo sh -e ~/Downloads/crouton -t core -r buster -n test
sudo enter-chroot -n test startxfce4
Entering /mnt/stateful_partition/crouton/chroots/test...
-sh: 1: startxfce4: not found
Unmounting /mnt/stateful_partition/crouton/chroots/test...

**Comment by githubgnulinux** [comment]
just deleted stretch chroot and tried reinstall
sudo sh -e ~/Downloads/crouton -u stretch -t keyboard,cli-extra,extension
sudo startxfce4
No chroots with target 'xfce' found in /mnt/stateful_partition/crouton/chroots

**Comment by githubgnulinux** [comment]
sudo sh -e ~/Downloads/crouton -r buster -t keyboard,cli-extra,extension
sudo startxfce4
No chroots with target 'xfce' found in /mnt/stateful_partition/crouton/chroots

Time to rant: had a working system able to do the required tasks. Unrequired, unrequested upgrade, now unable to use computer as wanted. Not a rich employee with unlimited internet access...

**Comment by githubgnulinux** [comment]
You already have the Chromium OS extension installed, so you're good to go!

Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
Done! You can enter the chroot using enter-chroot.
chronos@localhost / $ sudo startxfce4
No chroots with target 'xfce' found in /mnt/stateful_partition/crouton/chroots
chronos@localhost / $ sudo enter-chroot startxfce4
Entering /mnt/stateful_partition/crouton/chroots/stretch...
-su: 1: startxfce4: not found
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...

**Comment by DennisLfromGA** [comment]
@githubgnulinux,

Sorry to confuse you, the workaround I linked above was intended to be applied in the `enter-chroot` script mainly but a couple of other scripts are affected too. For details see -
- https://github.com/dnschneid/crouton/pull/3956/files

Note that this will be fixed when the PR is merged.

*Hope this helps,*
-**DennisLfromGA**
