### ISSUE TITLE
Problem to initialize Ledger Nano S with Crouton and Ubuntu (unity)

### ISSUE THREAD

**Issue by msebastianfa** [dnschneid/crouton#3973]
I want to make a communication with this device:
https://www.ledger.com/

And run this archive:
https://support.ledger.com/hc/en-us/articles/360006395553-Download-and-install-Ledger-Live

In my case i have some connection issues:
https://support.ledger.com/hc/en-us/articles/115005165269

So i want to try this with "sudo startunity" wich is the OS to i want to run the apps.
https://github.com/meriadec/nanos-linux-install-instructions/blob/master/README.md

Following the Steps:

I made the edit of /etc/udev/rules.d/20-hw1.rules
Nothing Happens
i go back to the file and add to the text file:
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2c97"
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2581"
Nothing Happens

I tried the last option and added the 8 lines, also nothing happens.

It seems the issue it has something to do with the USB connection and the software recognition.

Additional notes:

*I'm in the plugdev group
*When i do: "sudo apt install usbutils" and then "lsusb" it shows me the ledger device, but still can't connect correctly.
*It seems that in normal ubuntu install this commands work fine but not in crouton.
*I'm completly noob in this

**Comment by lomax** [comment]
Last time I've tried it, I have to add udev rules to the Chrome OS itself, not just to the chrooted linux.

**Comment by msebastianfa** [comment]
hey @lomax how are you?. okay, so...the udev rules, where do i put in Chrome OS?. can you explain to me?. Also, the udev rules will be like the "/etc/udev/rules.d/20-hw1.rules" from linux?

**Comment by lomax** [comment]
You have to turn off rootfs verification and resign the kernel to make Chrome OS root filesystem writeable. Than you just run the https://github.com/LedgerHQ/udev-rules/blob/master/add_udev_rules.sh with sudo.

**Comment by msebastianfa** [comment]
Hey @lomax thanks for the quick response. Do you have like some guide or something to be able to do it?. because i'm really really noob in this. (for the first part), the second part I am already used to doing it.

**Comment by msebastianfa** [comment]
if you have some time, maybe we can see it trough telegram. and i will send you the screen prints with every step.

**Comment by lomax** [comment]
@msebastianfa you can find information how to do it here https://www.chromium.org/chromium-os/poking-around-your-chrome-os-device

**Comment by msebastianfa** [comment]
@lomax didn't worked. i tried all the options (modifying the 20-hw1.rules file) after turn of the rootfs verifications.
I have some alternatives that one of the support of ledger gave me, but i can't get it run. I will need some live help to accomplish the steps.
Can you help me?.

this is the link:
https://github.com/meriadec/nanos-linux-install-instructions/issues/1#issuecomment-451390157

there are some options there, but because i'm a noob with the linux commands i can't really run all the options..
my telegram is: @msebastianfa
i await your response.

**Comment by lomax** [comment]
Answered here https://github.com/meriadec/nanos-linux-install-instructions/issues/1#issuecomment-453858096
