### ISSUE TITLE
Gnome-Terminal wont open

### ISSUE THREAD

**Issue by DeadRoblox** [dnschneid/crouton#3977]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: unity,extension
host: version 11021.81.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Nov 15 22:43:40 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
I used the GNOME-Terminal (since xterm has such small font) and I have just updated to 16.04 today. When I click on the Gnome-terminal icon it flashes for a second and then nothing happens. The terminal has worked just fine on my old chroot (14.04). And when I try to launch it from XTerm it does the same thing.

**Comment by TheMinigun** [comment]
Also honestly if possible one day can someone make it so chroots come pre packaged with the Gnome-Terminal instead of xterm? (honestly i'm pretty sure everyone hates xterm)

**Comment by sajjaadf** [comment]
I like xterm

**Comment by TheMinigun** [comment]
Ok @gavinfernandes2012 thanks

**Comment by TheMinigun** [comment]
hey @gavinfernandes2012 How does one install Tilix?

**Comment by gavinfernandes2012** [comment]
@TheMinigun Since tilix isn't available from the default sources in xenial, you're going to have to use [a ppa](https://launchpad.net/~webupd8team/+archive/ubuntu/terminix).

So you gotta:
```bash
sudo add-apt-repository ppa:webupd8team/terminix && \
sudo apt update && \
sudo apt install tilix
```
Or something along those lines at least.

**Comment by JL2210** [comment]
I've had the same issue in the past. `gnome-terminal` gives a few D-Bus errors, and never shows up. `xterm` is definitely going to the point of unusable for me.
