### ISSUE TITLE
Wont Install kali-rolling

### ISSUE THREAD

**Issue by tysongr** [dnschneid/crouton#3979]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by TheMinigun** [comment]
You really need to put the info in the box in order for someone to be able to help. Just sayin. @tysongr

**Comment by DennisLfromGA** [comment]
This is a known issue, please track it here:
- /prepare.sh cannot create as Directory is nonexistent #3930

A Pull Request has been initated but not yet merged, see:
- Find the correct alsa configuration directory #3955
