### ISSUE TITLE
kali rolling wont install

### ISSUE THREAD

**Issue by tysongr** [dnschneid/crouton#3980]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20181001133934~master:38012fdf
release: kali-rolling
architecture: amd64
targets: gnome
host: version 11151.59.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-18720-g7b8c1dc67cda #1 SMP PREEMPT Tue Dec 11 00:02:09 PST 2018 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
when trying to install(it wont work properly) I get in response the last three lines are:
"
prepare.sh: 1166: /prepare.sh: cannot create /usr/share/alsa/alsa.conf.d/10-cras.conf: Directory nonexistent
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
"
i have made sure that i have the newest version of crouton 
"
sudo sh -e ~/Downloads/crouton -r kali-rolling -t gnome
"
is the command i use
#### If known, describe the steps to reproduce the issue:
when creating chroot use setup command : 
"
sudo sh -e ~/Downloads/crouton -r kali-rolling -t gnome
"

if this issue could be fixed that would be very useful but until it is i am using ubuntu

**Comment by Gonthey** [comment]
@tysongr,

This is a known issue, please track it here:

/prepare.sh cannot create as Directory is nonexistent #3930
A Pull Request has been initated but not yet merged, see:

Find the correct alsa configuration directory #3955
Hope this helps,
-Gonthey
Original Post by @DennisLfromGA, also please close this.
