### ISSUE TITLE
How do I access data from one chroot using another?

### ISSUE THREAD

**Issue by sendnukes** [dnschneid/crouton#3981]
So I basically f-ed up my chroot and didnt bother with any backups. Problem is, I have around 40 gigs worth of stuff I'd like to keep still in the old chroot. I tried looking in usr/local/chroots but that folder was not there, and I didnt change the install location from the default. Is there any way to access that old data using my new chroot?

**Comment by TheMinigun** [comment]
I am not a professional but I suggest: Download GParted and mount the partition that the old chroot was located in. Then you might be able to look and get all of the data off of the old chroot.

**Comment by gavinfernandes2012** [comment]
@sendnukes Yes, I think you need to be looking in `/mnt/stateful_partition/crouton/chroots` from chrome os (not from linux). So you need to be using the command line, not the files app.

@TheMinigun iirc crouton does not create a separate partition for its chroots.

**Comment by TheMinigun** [comment]
@gavinfernandes2012 Ok. I thought that would be how chroots would be done (to be efficient) but I guess I was wrong. Thank you for correcting me.
