### ISSUE TITLE
How to open an app in a new xiwi window from a xiwi terminal ?

### ISSUE THREAD

**Issue by vincowl** [dnschneid/crouton#3982]
How could I open a new xiwi window while I run a command such as `filezilla` in a terminal already running in a xiwi window ? Such a command's result is actually opened in a tab in the terminal xiwi window.

For instance, run in crosh's shell :
`sudo startxiwi terminator` and that terminal type `filezilla` which will open gimp in a tab instead of a new window.

**Comment by DennisLfromGA** [comment]
@vincowl,

Not quite I understand the question but....

If you want to run an app in it's own window you can use something like this for example:

- `startxiwi -bn trusty brasero`

If you want to run it in a tab just use the '-T' option like this:

- `startxiwi -Tbn trusty brasero`

Here's the usage for the '`startxiwi`' command:
```
startxiwi [options] chroot_app [parameters]

Wraps enter-chroot to launch a window or tab in Chromium OS for any graphical application.
Applications launched in this way show in independent windows or tabs.

By default, it will use the primary user on the first xiwi-enabled chroot found and launch
the chroot_app in a window.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /usr/local/chroots
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -F          Launch the chroot_app full-screen.
    -T          Launch the chroot_app in a tab.
    -f          Prevent xiwi from quitting automatically. (see NOTE below)

NOTE:
xiwi will normally close when the application returns. Some gui applications
fork before or during normal operation, which can confuse xiwi and cause it to
quit prematurely. If your application does not have a parameter that prevents
it from forking, and crouton is unable to automatically detect the fork, you can
use -f to prevent xiwi from quitting automatically.
xiwi will quit if you close the Chromium OS window when nothing is displayed.
  
You can cycle through multiple windows inside the application
via Ctrl-Alt-Tab/Ctrl-Alt-Shift-Tab, or close them via Ctrl-Alt-Shift-Escape.
If the chroot_app begins with 'start' but you still want to
use the default window manager, specify the full path of the application.
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by vincowl** [comment]
@DennisLfromGA Indeed this works and is the normal behavior.
What I want to do is :

- Open a crosh shell
- type `shell`
- type `sudo startxiwi -bn buster xfce4-terminal`
- In that new terminal, I would like to run `inkscape`. This should open a new window containing inkscape, instead it creates a tab in the xfce4-terminal window. 

This would allow me to open a terminal in the chroot with xiwi running. Then I will have to type only the commands as I would do in a classical linux instance instead of having to add a `sudo startxiwi -bn` before each command. Indeed, I just need a terminal and not the full xfce desktop running. That's the way I used to process when I had to work with remote ssh linux servers from a Windows 7 putty instance and a X11 forwarding (xming).

Hope this helps to clarify my needs and question.

**Comment by DennisLfromGA** [comment]
@vincowl,

I *may* still not understand but, in the chroot, you can launch apps with the `xiwi` script so maybe *that* will work for you. To do that do this:

- `sudo startxiwi -bn buster xfce4-terminal`
- `xiwi inkscape &`

That should leave your xfce4-terminal session free while opening a new window containing Inkscape.

Here's the usage for the '`xiwi`' command:
```
Usage: xiwi [-f] [-F|-T] APPLICATION [PARAMETERS ...]
Launches a windowed session in Chromium OS for any graphical application.
Applications launched in this way show in independent windows or tabs.
All parameters are passed to the specified application.

By default, the app is launched in a window.

Options:
    -F          Launch the APPLICATION full-screen.
    -T          Launch the APPLICATION in a tab.
    -f          Prevent xiwi from quitting automatically. (see NOTE below)

NOTE:
xiwi will normally close when the application returns. Some gui applications
fork before or during normal operation, which can confuse xiwi and cause it to
quit prematurely. If your application does not have a parameter that prevents
it from forking, and crouton is unable to automatically detect the fork, you can
use -f to prevent xiwi from quitting automatically.
xiwi will quit if you close the Chromium OS window when nothing is displayed.

A default window manager will full-screen all windows, unless APPLICATION begins
with 'start' or is 'xinit'. You can cycle through multiple windows inside the
application via Ctrl-Alt-Tab/Ctrl-Alt-Shift-Tab, or close them via
Ctrl-Alt-Shift-Escape.  If APPLICATION begins with 'start' but you still want to
use the default window manager, specify the full path of the application.
```

The options are very similar to the '`startxiwi`' script since '`xiwi`' is invoked in the chroot. 

*Hope this helps,*
-**DennisLfromGA**

**Comment by vincowl** [comment]
That's it. Is there a way to avoid typing `xiwi ... &` and produce the same result ?

**Comment by DennisLfromGA** [comment]
@vincowl,

I suppose you could append '`xiwi inkscape &`' to your `~/.bashrc` but if something goes awry you may be stuck.  I would just make an alias like the following to save keystrokes -
- `alias xi='xiwi inkscape &'`

*Hope this helps,*
-**DennisLfromGA**

**Comment by vincowl** [comment]
Inkscape was unfortunately just an example. This would be usefull to every other GUI app to display (gimp, filezilla, vscode, freemind, ....). A solution would indeed be to define an alias for each command but if I could avoid it, it would be great... ;-)

**Comment by DennisLfromGA** [comment]
@vincow,

Another option would be to make a function like the following which would allow you to plug in any app and use any option you want to launch:

```
xw()
{
	xiwi $* &
}
```

Then just use it like this: 
- `xw inkscape` 
- `xw -T code` 
- `xw -F gimp`, etc.

*Hope this helps,*
-**DennisLfromGA**

**Comment by vincowl** [comment]
@DennisLfromGA Great ! Since there's no way to redirect the display to a new window by default, I think this tweak would perfectly fit my needs. Thanks !!!
