### ISSUE TITLE
*issue because im too lazy to submit a pull request* alsa dir still partially broken

### ISSUE THREAD

**Issue by Amplespencer** [dnschneid/crouton#3985]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
when you mkdir the alsa directory on setting up cras (native) you need a -p at the end or else it fails on buster

#### If known, describe the steps to reproduce the issue:
'sudo ~/Downloads/crouton -r buster -f gnome    or    sudo ~/Downloads/crouton -n buster -u`

also if the directory is already there the script ends which is pretty stupid if you ask me

**Comment by Amplespencer** [comment]
sorry here is sudo edit-chroot -all, was still setting up my croot at the time


`name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20181001133934~master:38012fdf
release: buster
architecture: amd64
xmethod: xorg
targets: gnome
host: version 11151.59.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-18720-g7b8c1dc67cda #1 SMP PREEMPT Tue Dec 11 00:09:42 PST 2018 x86_64 GNU/Linux
freon: yes`

**Comment by DennisLfromGA** [comment]
This is a known issue, please track it here:
- /prepare.sh cannot create as Directory is nonexistent #3930

A Pull Request has been initated but not yet merged, see:
- Find the correct alsa configuration directory #3955
