### ISSUE TITLE
After installing xfce/bionic target, no /mnt/stateful partition, enter-chroot fails

### ISSUE THREAD

**Issue by CarlFink** [dnschneid/crouton#3987]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
chronos@localhost ~ $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20181001133934~master:38012fdf
release: bionic
architecture: amd64
xmethod: xiwi
targets: extension,audio,xiwi,xfce,touch,keyboard
host: version 11151.59.0 (Official Build) stable-channel kefka 
kernel: Linux localhost 3.18.0-18720-g7b8c1dc67cda #1 SMP PREEMPT Tue Dec 11 00:05:13 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
chronos@localhost ~ $ 
```

#### Please describe your issue:
When I try "sudo enter-chroot" I receive these messages:
```
chronos@localhost ~ $ sudo enter-chroot 
Entering /mnt/stateful_partition/crouton/chroots/bionic...
No directory, logging in with HOME=/
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

mkdir: cannot create directory '//.config': Permission denied
ln: failed to create symbolic link '//.config/pulse/default.pa': No such file or directory
(bionic)carlf@localhost:/$ 
```

As you see, I end up in an Ubuntu terminal session, with no graphical environment, despite using the extension and xorg targets.

#### If known, describe the steps to reproduce the issue:
1)Install crouton using the Readme's instructions, with targets bionic,xiwi,extension,audio,touch.
2)sudo enter-chroot as above.

Device is a Dell Inspiron P26T.

Thank you.

**Comment by DennisLfromGA** [comment]
@CarlFink,

I can't find the following in the crouton source code:

> No directory, logging in with HOME=/

It may be that the chroot installation didn't finish successfully and/or something didn't get setup correctly.
The following troubleshooting guide may just get you going again:
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

If not let us know and we'll try to dig deeper.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Amplespencer** [comment]
just reinstall the chroot. definitely a failed install script

**Comment by Hellmo-Panda** [comment]
I am having the same issue and i just re downloaded the crouton. Therefore it must be a new issue that should be fixed soon
