### ISSUE TITLE
Slow gnome on bionic

### ISSUE THREAD

**Issue by gavinfernandes2012** [dnschneid/crouton#3988]
```bash
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20181001133934~master:38012fdf
release: bionic
architecture: amd64
xmethod: xorg
targets: gnome,xorg
host: version 11316.66.0 (Official Build) dev-channel caroline 
kernel: Linux localhost 3.18.0-18745-g58b01e43715f #1 SMP PREEMPT Sun Jan 6 23:59:08 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: amd64
xmethod: xorg
targets: unity,chrome-dev,audio,cli-extra,gnome,keyboard,touch
host: version 11316.66.0 (Official Build) dev-channel caroline 
kernel: Linux localhost 3.18.0-18745-g58b01e43715f #1 SMP PREEMPT Sun Jan 6 23:59:08 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
I installed gnome and xorg on bionic, and the lag makes it unusable, gnome on xenial doesn't have any such lag. This is on my Samsung Chromebook Pro (Skylake) on Chrome Dev 72.
This may be a duplicate of #3933 , but I haven't tried this workaround with plasma, so I don't know for sure.

#### Workaround
Doing a 
```bash
sudo cp /etc/crouton/xorg-intel-sna.conf /usr/share/X11/xorg.conf.d/20-crouton.conf
```
does eliminate this lag completely. This enables the intel driver with sna acceleration and tearfree on, but this workaround might not be device agnostic, so further testing by people with other devices might be required.

#### If known, describe the steps to reproduce the issue:
sudo startgnome

**Comment by danielfm123** [comment]
seems to have fixed my c302 :)

you are the best!

**Comment by gavinfernandes2012** [comment]
Haha glad I could help, I just got lucky :)@danielfm123

**Comment by gavinfernandes2012** [comment]
PS: Sorry, accidentally closed and reopened.
