### ISSUE TITLE
Ran out of space while encrypting chroot, now it's half-encrypted and I can't get in

### ISSUE THREAD

**Issue by TheAbstractPainter** [dnschneid/crouton#3990]
```
name: xenial
encrypted: yes, locked
```

#### Please describe your issue:
I tried to encrypt my existing chroot (sudo edit-chroot -e) and it started out fine.  But it was too large I guess, because my system ran out of space.  Then, I got a bunch of error messages saying it had failed to remove various folders because they weren't empty.

Now, when try to enter the chroot (sudo startgnome) I still have no space on the machine, and I get a message saying it wants to continue encrypting, and gives me a list of things to do if I think this is unexpected.  None of the options allows me to get into my chroot (the "no" is the closest option, but I get the message that the chroot "doesn't appear to be a valid chroot.")

I think my best option is to remove the encryption, take a bunch of files off the chroot (so I don't run out of space again), and then start again.  But I can't find how to do that.

Is that even possible?  Is there another solution?

I assumed it would encrypt the files in place, so that I wouldn't need a lot of empty space to complete the encryption.  Maybe alternatively, I can plug in a usb drive and move it or something for the extra space?

**Comment by DennisLfromGA** [comment]
@TheAbstractPainter,

I would offload any large files in Downloads if you have any, then reboot.

Also, have you tried just getting into a shell session as root with: 
- `sudo enter-chroot -u root -n xenial`

If you can then you might be able to offload some files in the chroot, exit and try to encrypt it again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheAbstractPainter** [comment]
Thanks!  I ended up using this method:
(best) Get a large enough USB stick or SD card, format it ext4, copy the chroot directory to it, finish encryption, copy it back to your SSD.

It took a bit of time to get everything done, but it's all working now, and I have about the same amount of free space as I started with (i.e. ~5.5GB).  FYI, I don't think I have any files that big (maybe the biggest being ~3GB), so I suspect something in the process is using more than one file at a time.  It might be helpful to check how much space is available and give a warning if it looks like there isn't enough.

Oh, one other thing, it took a bit of time to find where the chroot had been installed.  In your documentation, it lists how to change the destination, but it doesn't say where the default is (e.g. in the cheat sheet and the readme.)  It could be helpful to list the default location as well.

Anyway, thanks again!  I was very happy I didn't lose my data!

**Comment by DennisLfromGA** [comment]
@TheAbstractPainter,

Great, glad that method worked.

> It might be helpful to check how much space is available and give a warning if it looks like there isn't enough.

There is an *old and outdated* PR for 'Size tests' but it hasn't been reviewed lately or implemented -
- Size tests #2240
> In your documentation, it lists how to change the destination, but it doesn't say where the default is

 True, **[I want to install the chroot to another location](https://github.com/dnschneid/crouton#i-want-to-install-the-chroot-to-another-location)** doesn't really say, it might be helpful.

FYI: If you run `crouton` without any options it wiil display the usage, there it talks about the '-p' option and the 'Default' location, see below:
```
  -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
```

-**DennisLfromGA**

P.S. If you're satisfied this issue is resolved please close it or let us knowand we'll close it.
