### ISSUE TITLE
Unable to locate package dconf-tools

### ISSUE THREAD

**Issue by guidoscientia** [dnschneid/crouton#3991]
```
Please paste the output of the following command here: sudo edit-chroot -all
(made a mistake and deleted it but i can share install command tho;
 
sudo sh ~/Downloads/crouton -e -r sid -t core,audio,extension,gnome,keyboard,xorg,xiwi -p '/media/removable/USB Drive/Crostini'

``'

#### Please describe your issue:

Installing target gnome...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dconf-tools
Failed to complete chroot setup.

Well that's all i can show

**Comment by Asternitix** [comment]
I’m having this problem too need fix.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asternitix** [comment]
Seems like a xiwi issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asternitix** [comment]
Found a fix do an install core only and then go from there.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asternitix** [comment]
Looks like it’s a dummy package.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asternitix** [comment]
``

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asternitix** [comment]
Found it. Fetch the deb file for stretch and install that. It should fix your problem. Either way xiwi will work the same.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
