### ISSUE TITLE
Chroot backup 

### ISSUE THREAD

**Issue by tonymurray** [dnschneid/crouton#3993]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Password: 
name: linux
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/linux...

#### Please describe your issue:

When backing-up chroot, I get messages 
: socket ignored

Perhaps this is OK? Or maybe not? I do not see error messages. 

Unfortunately I cannot test restoring the chroot since I only have space for one chroot 
(In other words, I would have to take a leap of faith and destroy my working chroot, then test restoring the possibly corrupt backup)

----- The following is summary of my backup procedure and messages:

$sudo edit-chroot -f '/media/removable/usbdisk/backupchroot' -b mychroot
Password:
Unmounting /mnt/stateful_partition/crouton/chroots/mychroot...
Backuping up /mnt_stateful_partition/crouton/chroots/mychroot to /media/removable/usbdisk/backupchroot/mychroot-20190123.tar... 
----- There follows the following Messages:
tar: mychroot/ECRYPTFS_FNEK_ENCRYPTED.FWTUHrLMrinCPAtYqkfltIKoFcdFE-VRW-IH.............--: socket ignored
...
----- (...above repeated several times)

... then finally...
Finished backing up /mnt/stateful_partition/crouton/chroots/linux to /media/removable/usbdisk/backupchroot/mychroot-20190125-1659.tar

#### If known, describe the steps to reproduce the issue:
... backup typical encrypted chroot as per above
... using latest chromeos on acer c720p

**Comment by sarahmccuan** [comment]
A socket is a special kind of "file" that different processes use to transfer information between each other while they are running. As such there is no need to back up sockets, and these messages can be safely ignored.

**Comment by tonymurray** [comment]
Thanks for the info!

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
