### ISSUE TITLE
Chromebook pixel 2013：crouton ubuntu xenial，no toolbar no launcher，just background and mouse pointer

### ISSUE THREAD

**Issue by liuruiyun** [dnschneid/crouton#4000]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190120145639~master:5bf96711
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10895.78.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Oct 3 23:30:23 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

#### Please describe your issue:
I install ubuntu by those commands
sudo sh ~/Downloads/crouton -t unity -P http://XXXXX:XXXX
(i live in China with Great Wall :( so i use a shadowsocks)

after setting username and password, I start unity
sudo startunity

it turns out some wrong:
background, mouse pointer(i can control it), right click and menu(i can switch a new background pic,:-)))
but no toolbar on left ,no launcher
where is my crouton ubuntu??

#### If known, describe the steps to reproduce the issue:
i tried to fix it with those command but no use
1. sudo enter-chroot 
2. sudo apt-ger update
3. sudo apt-get install unity
4.  mv ~/.config ~/.config_backup
5.  rm -rf .compiz-1

and i delete crouton ubuntu and reinstall it, blank background, mouse pointer come back :-))))

otherwise, i have those output:
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20190120145639~master:5bf96711
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 10895.78.0 (Official Build) stable-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Oct 3 23:30:23 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Another instance of croutontriggerd running, waiting...
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output VGA1 is not disconnected but has no modes
Kicking xrandr again
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output HDMI1 is not disconnected but has no modes
xrandr: Output VGA1 is not disconnected but has no modes
Kicking xrandr again
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files

**Comment by yanyuechuixue** [comment]
Same issue

**Comment by MrLbird** [comment]
woah 4000 issue...
