### ISSUE TITLE
Vscode wont start sommelier 

### ISSUE THREAD

**Issue by sajjaadf** [dnschneid/crouton#4002]
GDK_ERROR:Display 0: Not Found
code exited with exit code 1

**Comment by DennisLfromGA** [comment]
@sajjaadf,

That sounds like a Crostini issue, not a crouton issue.
See this for how to report Crostini bugs -
- [Where can I file bugs?](https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md#Where-can-I-file-bugs)

Also, this subreddit '[r/Crostini](https://www.reddit.com/r/Crostini/)' is where many Crostini enthusiasts hang out, they often provide help, tips & tricks so it's probably worth a visit.

*Hope this helps,*
-**DennisLfromGA**

P.S. Please close this issue if it's not relevant to crouton, thanx.

**Comment by sajjaadf** [comment]
Im on a crouton cli command line with sommelier installed, I don't have crostini, unfortunately, @DennisLfromGA

**Comment by sajjaadf** [comment]
I installed code-css from Debian deb package at https://github.com/headmelted/codebuilds/releases
the armhf version.

**Comment by sajjaadf** [comment]
sorry if I was not really expelling, I was typing on a phone.

**Comment by sajjaadf** [comment]
_Flatpack_ also won't work right. (**@ https://flatpak.org** )

**Comment by sajjaadf** [comment]
you know chromebrew? I use chromebrew and crouton

**Comment by sajjaadf** [comment]
Im on a Asus c201PA which has android apps, but not crostini, its on linux kernel 3.14, with google assistant and singleprosscessmash for sommelier to work properly with app icons.

**Comment by sajjaadf** [comment]
Im on chrome os 74.1 canary with dev mode enabled.

**Comment by sajjaadf** [comment]
arc version is 8.6 and android version is pie.

**Comment by sajjaadf** [comment]
with sudo enter-chroot

**Comment by apit** [comment]
hey @sajjaadf, wonder how you still have android on 74.1. mine is also c201PA, but android was couldnt be enabled anymore since ~69.

**Comment by sajjaadf** [comment]
oh @apit It have read write root enabled and edited the dev_CONFIG permanent.

**Comment by sajjaadf** [comment]
its a not so fun process...

**Comment by sajjaadf** [comment]
@DennisLfromGA  HELLO?

**Comment by apit** [comment]
@sajjaadf can you direct me to article or gist on how to that step by step? thanks

**Comment by sajjaadf** [comment]
okay!
[image: Picture]
Sajjaad Farzad
About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by sajjaadf** [comment]
I will!

**Comment by sajjaadf** [comment]
A Chromebook with storage space for a ~2GB file in /usr/local/. Exact space usage varies depending on device, but will usually be at least 1.3 GB.

The Chrome OS system partition needs to have been made writable. 
A straightforward way to enable this is usually to enter the following command in the shell, then reboot:
`sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions $(( $(rootdev -s | sed -r 's/.*(.)$/\1/') - 1))`

**Comment by sajjaadf** [comment]
[https://www.chromium.org/chromium-os/poking-around-your-chrome-os-device](https://www.chromium.org/chromium-os/poking-around-your-chrome-os-device)

**Comment by sajjaadf** [comment]
[https://sites.google.com/site/cr48ite/getting-technical/remove-rootfs-verification-make-read-write](https://sites.google.com/site/cr48ite/getting-technical/remove-rootfs-verification-make-read-write)

**Comment by sajjaadf** [comment]
cd /etc/chrome_dev.conf
nano or pico or vim chrome_dev.conf
add lines "--arc-availability=officially-supported"
into it

**Comment by sajjaadf** [comment]
[https://stackoverflow.com/questions/45875001/how-do-you-make-chromium-command-line-switches-on-a-chromebook](https://stackoverflow.com/questions/45875001/how-do-you-make-chromium-command-line-switches-on-a-chromebook)

**Comment by sajjaadf** [comment]
[https://sites.google.com/site/cr48ite/getting-technical/remove-rootfs-verification-make-read-write](https://sites.google.com/site/cr48ite/getting-technical/remove-rootfs-verification-make-read-write)

**Comment by DennisLfromGA** [comment]
This is getting *way off track*.

Closing. Please update your chroot and try again, re-open if this issue is still a concern.
