### ISSUE TITLE
Browsing encrypted backup

### ISSUE THREAD

**Issue by commiades** [dnschneid/crouton#4003]
I have a backup of my croot, which when I browse using an archive manager shows a series of encrypted files. I have now changed my Chromebook to a straight Linux machine running Gallium OS. Is there any way for me to browse the backup to extract some files? Can I mount the croot on another Linux machine, for instance?

**Comment by DennisLfromGA** [comment]
@commiades, 

If you have stored your key(s) on external media you *may* still be able to access your chroot.
See an explanation of encryption options the creator of crouton provides here:

- https://github.com/dnschneid/crouton/issues/3998#issuecomment-462670209

*Hope this helps,*
-**DennisLfromGA**

**Comment by commiades** [comment]
Thanks. I didn't specify the storage of the key outside of the croot, so it's unlikely to be possible, unless I restore the Chromebook for a while.

**Comment by DennisLfromGA** [comment]
> ... so it's unlikely to be possible, unless I restore the Chromebook for a while.

Well, maybe not ideal but it sounds like a possibility at least. 

Closing. Please re-open if this issue is still a concern.
