### ISSUE TITLE
cant mount flash drive 

### ISSUE THREAD

**Issue by JamBlueberry** [dnschneid/crouton#4004]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
i cant mount flash drive 

#### If known, describe the steps to reproduce the issue:
plug in flash drive  eject in chrome file manger tryd to mount flash drive. it says you dont have permission to mount

**Comment by icecream95** [comment]
If you have a USB drive accessible in Chrome OS, you should just be able to access it in crouton from `/media/removable` inside your chroots.

If you need to have the contents of the USB drive accessible somewhere else inside the chroot, you can run `sudo mount --bind /media/removable/USB\ Drive\ Name /where/I/want/it/to/be` from a terminal in your chroot. (You can use the tab key to list the USB drive names after typing `/media/removable`.)

If you can't access the drive in Chrome OS, however, it's a little more complicated.
First, run `lsblk` from inside your chroot. Look for a drive that's called either sdX or mmcblkX that *doesn't* have 12 partitions under it - that's the Chrome OS system drive. Let's say it's `/dev/sdb`. First, you'll need to create a directory to mount it: `sudo mkdir -p /media/removable/myusb`. Then, you'll need to mount it with something like `sudo mount /dev/sdb1 /media/removable/myusb` - sometimes you'll need the 1, other times it won't work if you use it. For mmcblk drives (usually SD cards), you might need to use something like mmcblk1p1.

**Comment by sdk03** [comment]
Saved my life, thanks !
