### ISSUE TITLE
Installing lxqt

### ISSUE THREAD

**Issue by MrMuttons** [dnschneid/crouton#4005]
I was wondering how i would go about installing and usning lxqt?
i love how it looks, and how light weight it is

**Comment by icecream95** [comment]
As long as you have Xenial or later, this isn't too hard:

If you don't already have a chroot, create one with at least the xiwi or xorg targets.

Enter your chroot with

    sudo enter-chroot -n CHROOTNAME

[Note that GitHub messes up triple-click select so you'll have to single-click drag select these commands to copy them. Right clicking (tapping with two fingers) pastes into crosh]

Install LXQt with

    sudo apt-get update; sudo apt-get install lxqt lxqt-common openbox

Now, install startlxqt into your chroot with

    sudo ln -s crouton-noroot /usr/local/bin/startlxqt

Tell crouton you now have LXQt with

    sudo sed -i 's/$/,lxqt/' /etc/crouton/targets

Exit your chroot (with `exit`) - make sure your prompt now shows `chronos@localhost`.


Now, you'll need to create a startlxqt script in Chrome OS.

Enter

    sudo su -c 'cat >/usr/local/bin/startlxqt'

Now, paste in the script:

    #!/bin/sh -e
    # Copyright (c) 2016 The crouton Authors. All rights reserved.
    # Use of this source code is governed by a BSD-style license that can be
    # found in the LICENSE file.

    set -e

    APPLICATION="${0##*/}"

    USAGE="$APPLICATION [options]

    Wraps enter-chroot to start an LXQt session.
    By default, it will log into the primary user on the first chroot found.

    Options are directly passed to enter-chroot; run enter-chroot to list them."

    exec sh -e "`dirname "\`readlink -f -- "$0"\`"`/enter-chroot" -t lxqt "$@" "" \
        exec xinit /usr/bin/startlxqt

Hit enter then Ctrl-D to save your changes.

Finally, paste this in to make startlxqt executable:

    sudo chmod +x /usr/local/bin/startlxqt


You can now start LXQt like you would any other DE with `startlxqt`.

**Comment by MrMuttons** [comment]
No chroots with target 'lxqt' found in /mnt/stateful_partition/crouton/chroots

**Comment by icecream95** [comment]
I've got a feeling you pasted in the command to enter your chroot directly, and tried to enter a chroot called CHROOTNAME.

Try running the steps up to the exit command again, but make sure you replace CHROOTNAME with the actual name of your chroot in the first command - if you get errors such as 'apt-get: command not found', you haven't entered your chroot correctly.

**Comment by MrMuttons** [comment]
> I've got a feeling you pasted in the command to enter your chroot directly, and tried to enter a chroot called CHROOTNAME.
> 
> Try running the steps up to the exit command again, but make sure you replace CHROOTNAME with the actual name of your chroot in the first command - if you get errors such as 'apt-get: command not found', you haven't entered your chroot correctly.

thats the error from running sudo startlxqt

**Comment by icecream95** [comment]
Sorry, my fault - it turns out crouton relies on a hidden file .crouton-targets for checking whether you have a target installed, but I thought it was /etc/crouton/targets and didn't bother checking.

Try running this once you've entered your chroot:

    echo lxqt | sudo tee -a /.crouton-targets

You *might* have problems when updating. If you do, enter your chroot, telling it to skip finishing the update, and run this:

    sudo sed -i 's/,lxqt//' /etc/crouton/targets

Exit and run the update again.

If an update breaks startlxqt again, you'll have to rerun the first command in this post.

**Comment by MrMuttons** [comment]
ended up installing arch on an sdcard and dual booting, thanks anyways!

**Comment by DennisLfromGA** [comment]
Just wanted to mention that there is an open PR for this:
- LXQT #2525

However, the original author recently stated:
> I'm not able to work on this currently, and if others would like to take it up, I'm happy to support that.

*Hope this helps,*
-**DennisLfromGA**
