### ISSUE TITLE
Does Crouton allow for regular Linux experience?

### ISSUE THREAD

**Issue by Jisenku** [dnschneid/crouton#4006]
I am very confused about ***Linux***. Does it allow for the regular Linux experience with regular setup, or do I have to do *additional* setup to get the desktop experience? I honestly have no idea how to use the command prompts, and I am really onto Linux as a way to get applications for my Chromebook.

**Comment by DennisLfromGA** [comment]
@Chi7519,

> Does it allow for the regular Linux experience with regular setup

Yes.

> ... or do I have to do _additional_ setup to get the desktop experience?

You can add a number of desktop 'targets' when installing the chroot to get a desktop experience. 
Some have both a minimal footprint/size and others with '-desktop' appended give you the full meta package.

I would recommend spending some quality time with the [README](https://github.com/dnschneid/crouton/blob/master/README.md) first & foremost then run the following commands to see what releases & desktop targets are supported -

- [show releases] `sudo sh ~/Downloads/crouton -r list`
- [show desktops] `sudo sh ~/Downloads/crouton -t list`

Then you'll have to decide what might best fit your needs.

*Hope this helps,*
-**DennisLfromGA**
