### ISSUE TITLE
Backups smaller today after installing more stuff

### ISSUE THREAD

**Issue by m2b** [dnschneid/crouton#4007]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /media/removable/CroutonKali/chroots/kali-rolling...
crouton: version 1-20190117121840~master:e7aa1694
release: kali-rolling
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 11316.123.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-18747-gdea8d908bd77 #1 SMP PREEMPT Tue Feb 5 22:43:47 PST 2019 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/CroutonKali/chroots/kali-rolling...
```
#### Please describe your issue:
I made a second backup after installing significant amounts more of software tools and having additional data.  The backup was smaller.  Why?  Is this incremental?

#### If known, describe the steps to reproduce the issue:
See the attached screenshot.
![screenshot 2019-02-25 at 1 13 58 pm](https://user-images.githubusercontent.com/773233/53369111-4c558600-38ff-11e9-8599-55db9a79b9bf.png)

**Comment by DennisLfromGA** [comment]
@m2b,

224KB does not look right, you might want to make yet another backup just to be sure.

*Hope this helps,*
-**DennisLfromGA**

**Comment by m2b** [comment]
Thanks @DennisLfromGA that did it.  It must not have finshed.

**Comment by m2b** [comment]
Fixed per @DennisLfromGA
