### ISSUE TITLE
Linux not opening

### ISSUE THREAD

**Issue by MercenaryT** [dnschneid/crouton#4010]
```
    When I open Crosh and try to open Linux from there I am answered with the error message of: "ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied". I'm not entirely sure what this means except for the fact that I need permission to open this. I am not running these programs on a work or school computer and I am not connected to any enterprise or enterprise like wifi networks. Every other time I have tried to open Linux this way, it works. I am using a Samsung Chromebook, but I am unsure of the model. If anyone knows a way to fix this or what is keeping me from opening Linux, that would be great, thanks 

What it looks like(not a screenshot):
Loading extra module: /usr/share/crosh/dev.d/50-crosh.sh
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

If you want to customize the look/behavior, you can use the options page.
Load it by using the Ctrl+Shift+P keyboard shortcut.

crosh> shell
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
ln: failed to access '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/etc/resolv.conf': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
Please show or tell us what the first six lines of `chrome://version` displays so we can tell which Chrome OS & Chrome versions are you using and on what device.

-**DennisLfromGA**

**Comment by icecream95** [comment]
Try running this:

    sudo mkdir -p /var/host/shill/
    sudo touch /var/host/shill/resolv.conf

Can you enter your chroot now? Can you connect to the internet from inside it?

**Comment by DennisLfromGA** [comment]
OPs response on issue#4133, now closed:

----------
Please show or tell us what the first six lines of chrome://version displays so we can tell which Chrome OS & Chrome versions are you using and on what device.

-DennisLfromGA

Response:
>Google Chrome 77.0.3822.0 (Official Build) canary (64-bit)
>Revision e7068223d3d645f3043956372bbd7922822b7008-refs/branch-heads/3822@{#1}
>Platform 12286.0.0 (Official Build) canary-channel celes
>Firmware Version Google_Celes.7287.92.164
>ARC 5673510

**Comment by DennisLfromGA** [comment]
@MercenaryT,

If you'v already tried @icecream95's suggestion and it hasn't helped perhaps try a crouton update following steps 1 thru 8 linked below:
- [Common issues and reporting](https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting)

Problems on the canary channel are definitely more prevalent, perhaps that's the real issue here.

*Hope this helps,*
-**DennisLfromGA**
