### ISSUE TITLE
I power washed chromebook but still asking for password...

### ISSUE THREAD

**Issue by keanec2** [dnschneid/crouton#4013]
I was told that I lost my password for running Linux, I would have to power wash my Chromebook. I did but when I tried installing ubuntu again it's still asking
 for the password. Plz help 

![Screenshot 2019-03-15 at 11 13 45 PM](https://user-images.githubusercontent.com/41767201/54470065-432a3d00-4778-11e9-9f18-11c200dc1368.png)

**Comment by DennisLfromGA** [comment]
After powerwashing one of the first screens will ask if you want to enable Debugging options, *don't do that*.
Instead, just add you're account and sign-in and you shouldn't need a password for chronos or root.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pcs3rd** [comment]
As @DennisLfromGA said, trying to set a password at the initial setup screen **doesn't** actually set your password (Don't know why...). But, if you don't want passwordless root, you can just use the `passwd` command.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
