### ISSUE TITLE
Crouton essentially broken on 32-bit x86 ChromeOS kernels > 3.4 and < 3.18

### ISSUE THREAD

**Issue by nh2** [dnschneid/crouton#4016]
This is the outcome of https://github.com/systemd/systemd/issues/11974#issuecomment-473754055 (found via #3914, which is just for the Samsung 500C, which may or may not have other issues; this issue is specifically about the kernel issue parts across all 32-bit x86 Chromebooks with certain kernel versions, thus a separate issue).

Copying over the summary:

* An [upstream Linux bug](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/urgent&id=554086d85e71f30abe46fc014fea31929a7c6a8a) broke `ENOSYS` being returned on invalid syscalls if `sysenter` was used.
* It was [fixed in upstream Linux](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/urgent&id=8142b215501f8b291a108a202b3a053a265b03dd) 1 month later (and the bug [apparently](https://patchwork.ozlabs.org/patch/372692/) never made it into an upstream kernel release without the fix).
* ChromiumOS cherry-picked the bug starting from their 3.8 release, but apparently forgot to cherry-pick the fix for years.
* As a result `systemd` based Linux distributions in [`crouton`](https://github.com/dnschneid/crouton) chroots work for any 32-bit `i686` ChromeOS that has `uname -a` < 3.8, break for everything above that until 3.18, where they should work again.
  * Unfortunately, many ChromeOS laptops (including the one I found this on) were end-of-lifed on versions within the broken range. For those, a workaround should be downgrading to a ChromeOS version that has a kernel <= 3.4. (Note that running unmaintained old kernels is generally insecure, but unfortunately booting custom kernels isn't easy on that range of devices either.)

This means that

* **Crouton will fail to install Linux distributions using `systemd` on Chromebooks with kernels 3.8, 3.10 or 3.14.**
* Even if systemd is not used, the underlying issue is a kernel bug that can also result in arbitrary behaviour of any other application.

I think we should

* [ ] Put a note on Crouton's `README` about this
* [ ] Figure out whether there's a workaround
  * for example, running applications under `strace` fixes the issue (as [described](https://github.com/systemd/systemd/issues/11974#issue-420059763))
  * a global workaround would be if we could tell glibc or the kernel to always use `int 0x80` for system calls instead `sysenter` via the VDSO (I don't know if glibc provides an override for that)
  * (perhaps not the right place here to figure this one out:) Running on old kernels is a security problem; figure out how we can boot a real, new Linux kernel instead of Crouton chroots for the affected end-of-life'd devices, like `ChrUbuntu` did.

**Comment by amstan** [comment]
Hello again,

Thanks for discovering this and for the thorough documentation.

While it would be super easy to cherry-pick that fixup patch in the chromeos kernel branches, none of the chromebooks that we still update are x86 32bit.

So landing the patch wouldn't really fix anything.

**Comment by jichu4n** [comment]
Thanks so much to @nh2 for the thorough investigation on this! I was able to find a (rather crude) workaround for this issue based on your findings: https://github.com/jichu4n/crouton/commit/0c61fd0b7e115ba2d9d0a9d818287bfc27940203

Basically, as long as we inject a `/etc/machine-id` before the systemd package is installed, it will turn `systemd-machine-id-setup` into a no-op and will allow the installation to bypass this problem.

That said, given how old these kernels are, I don't know if it's worth trying to submit a PR for this. But if someone comes across this in the future, please feel free to try patching in my commit above.
