### ISSUE TITLE
Question: Can I get my chroot to detect my Bluetooth from chromeos?

### ISSUE THREAD

**Issue by DeadRoblox** [dnschneid/crouton#4017]
Can I get that to work? I have been wanting to use a Wacom Tablet with my chromebook but it is a bluetooth one. Was wondering if I could somehow add a modifier that adds support for bluetooth.

**Comment by grantlmul** [comment]
As the chroot and Chrome OS run on the same kernel, it should just work because the Bluetooth kernel module is loaded in the first place.

**Comment by TheMinigun** [comment]
It does not appear to work.

**Comment by DennisLfromGA** [comment]
@TheMinigun,

As @grantlmul intimated, Bluetooth and other networking are controlled and run on the Chrome OS side of things so it *should* work without any intervention. Just make sure BT is enabled in Chrome OS.

It's working fine in my trusty chroot as shown below:
![Screenshot - 04042019 - 02:17:42 PM](https://user-images.githubusercontent.com/3418772/55578943-15844400-56e5-11e9-8745-24c5d811ced7.png)

*Hope this helps,*
-**DennisLfromGA**

Closing. Please re-open if this issue is still a concern.

**Comment by TheMinigun** [comment]
![Screenshot 2019-04-07 at 2 30 13 PM](https://user-images.githubusercontent.com/32660762/55688060-4319f900-5942-11e9-800d-732de5e1f069.png)
![Screenshot from 2019-04-07 14-31-36](https://user-images.githubusercontent.com/32660762/55688062-46ad8000-5942-11e9-8293-149281b77c88.png)

**Comment by TheMinigun** [comment]
I can't reopen
![Screenshot from 2019-04-07 14-31-36](https://user-images.githubusercontent.com/32660762/55688084-9db35500-5942-11e9-9b08-855710ce46cd.png)
![Screenshot 2019-04-07 at 2 30 13 PM](https://user-images.githubusercontent.com/32660762/55688085-9db35500-5942-11e9-9aff-1d20a0572eee.png)

**Comment by DennisLfromGA** [comment]
@TheMinigun,

You created this issue so you *should* be able to re-open it but I'll do it for you. I'm not sure how much that will help though.

-----
However, please show the output of the following command so we have some clue of what we're dealing with. 

- `sudo edit-chroot -all`

-----
-**DennisLfromGA**

**Comment by TheMinigun** [comment]
`chronos@localhost / $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190120145639~master:5bf96711
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome-desktop
host: version 11647.104.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Mar 20 23:36:13 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
chronos@localhost / $ ` Ok @DennisLfromGA Here it is.

**Comment by DennisLfromGA** [comment]
@TheMinigun, 

My bionic gnome-desktop behaves the same way.

The bluetooth preferences shows it off, like yours, and I couldn't enable it.
The bluetooth service/daemon reports that it's running though -
```
(bionic)denny@localhost:~$ sudo /etc/init.d/bluetooth  status
 * bluetooth is running
(bionic)denny@localhost:~$ 
```

I'm not sure what's wrong, there may be other services that need to be running.

Hopefully, others will drop by and offer some suggestions.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheMinigun** [comment]
Me too. Thanks for the help. I have been trying to get a BT wacom tablet to work through my Ubuntu so I could draw with Gimp.

**Comment by DennisLfromGA** [comment]
@TheMinigun,

You could try the 'trusty' release, it's still an LTS distro and seems to work with BT devices.
I think there are problems with chroots and 'systemd' in the newer releases.

*Hope this helps,*
-**DennisLfromGA**

**Comment by grantlmul** [comment]
Ah, is that why my 18.04 also hates internet?
