### ISSUE TITLE
bionic install fails when "Unable to locate package i3"

### ISSUE THREAD

**Issue by westmj** [dnschneid/crouton#4020]
```
Please paste the output of the following command here: sudo edit-chroot -all

chronos@localhost / $ sudo edit-chroot -all -c /media/removable/mwjwEXT4/chroots/
name: bionic
encrypted: no
Entering /media/removable/mwjwEXT4/chroots/bionic...
crouton: version 1-20190120145639~master:5bf96711
release: bionic
architecture: amd64
targets: audio,cli-extra,core,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg
host: version 11895.21.0 (Official Build) dev-channel banjo 
kernel: Linux localhost 4.4.176-16032-ga91d6ee3c7f6 #1 SMP PREEMPT Wed Mar 20 00:22:20 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/mwjwEXT4/chroots/bionic...
name: xenial
encrypted: no
Entering /media/removable/mwjwEXT4/chroots/xenial...
crouton: version 1-20190120145639~master:5bf96711
release: xenial
architecture: amd64
xmethod: xiwi
targets: audio,cli-extra,core,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg
host: version 11895.21.0 (Official Build) dev-channel banjo 
kernel: Linux localhost 4.4.176-16032-ga91d6ee3c7f6 #1 SMP PREEMPT Wed Mar 20 00:22:20 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /media/removable/mwjwEXT4/chroots/xenial as another instance is using it.

#### Please describe your issue:

bionic install fails, when package i3 not found.  To wit: 

chronos@localhost / $ sudo sh ~/Downloads/crouton -r bionic -p /media/removable/mwjwEXT4/  -t audio,cli-extra,core,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg -u  2>&1 | tee -a ~/Downloads/crouton-diagnosis-010.txt 

/media/removable/mwjwEXT4/chroots/bionic already exists; updating it...
WARNING: bionic is an unsupported release. 
You will likely run into issues, but things may work with some effort.
Press Ctrl-C to abort; update will continue in 5 seconds.
Preparing chroot environment...
Installing brightness into the chroot...
....
Installing CRAS...
Installing target cli-extra...
Reading package lists...
Building dependency tree...
Reading state information...
dbus is already the newest version (1.12.2-1ubuntu1).
kbd is already the newest version (2.0.4-2ubuntu1).
openssh-client is already the newest version (1:7.6p1-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing target xiwi...
xserver-xorg-video-dummy was already not hold.
Reading package lists...
Building dependency tree...
Reading state information...
xorg is already the newest version (1:7.7+19ubuntu7).
xserver-xorg-video-dummy is already the newest version (1:0.3.8-1build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package i3
Failed to complete chroot setup.
Unmounting /media/removable/mwjwEXT4/chroots/bionic...
Sending SIGTERM to processes under /media/removable/mwjwEXT4/chroots/bionic...


#### If known, describe the steps to reproduce the issue:

see above, reproducible.  ready to put in some effort.  Thanks.  xenial installed fine today.

**Comment by JL2210** [comment]
What does Debian do? Try `i3-wm`.

**Comment by westmj** [comment]
I just installed and ran "buster" with no problems, so that is a nice difference.  I do not understand how I can "try 'i3-wm'"?  Could you please be more specific? I wonder if I need to add a repository?  But I have no idea how to change the script that the crouton install follows.  Definite noobie here.  Thanks for any help.

**Comment by JL2210** [comment]
The `i3` package is deprecated (meta-package). Try replacing `i3` with `i3-wm` in the install scripts for Bionic.

**Comment by westmj** [comment]
I used 

 sh crouton -x

thinking this gives the install scripts. In crouton.unbundled I used rgrep i3 to find, in part

./crouton.unbundled/targets/xiwi:install --minimal i3
./crouton.unbundled/targets/xiwi:# Remove some unsupported options on old versions of i3
./crouton.unbundled/targets/kodi:if [ "$DISTRO" = 'ubuntu' ] && [ "$ARCH" = 'amd64' -o "$ARCH" = 'i386' ]; then    
./crouton.unbundled/chroot-bin/xiwi:        i3 -c "/etc/crouton/xiwi.conf" &
./crouton.unbundled/chroot-bin/xiwi:        # Wait for i3 to launch

So, do I replace those instances of "i3" with "i3-wm" ?  I thought my problem came before that, when i3 is not found, thus not installed.  Maybe just the "install --minimal i3" should be "install --minimal i3-wm" ?

And, after editing these file(s), what command do I give to run all those local copies of the scripts?

Thanks for any hints for a newbie.   bionic does seem to install on some of my chromebooks, but not all.

**Comment by JL2210** [comment]
Just replace `install --minimal i3` with `install --minimal i3-wm` in `xiwi`.

> And, after editing these file(s), what command do I give to run all those local copies of the scripts?

Not sure. All the stuff I'm finding online is along the lines of "How to update Crouton" or "How to install Crouton" :(.

Try running `crouton -x dir/; cd dir; SCRIPTDIR=. crouton -X targets/xiwi`
