### ISSUE TITLE
fcitx

### ISSUE THREAD

**Issue by Clearia** [dnschneid/crouton#4025]
In wps office and wine, I can't use fcitx to type chinese.
name: debian
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/debian...
crouton: version 1-20190120145639~master:5bf96711
release: sid
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11895.33.0 (Official Build) dev-channel coral 
kernel: Linux localhost 4.4.176-16032-ga91d6ee3c7f6 #1 SMP PREEMPT Tue Mar 26 00:59:08 PDT 2019 x86_64 GNU/Linux
freon: yes

I use ubuntu before, the same issue.
name: xenial
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190120145639~master:5bf96711
release: bionic
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,extension,keyboard,audio,xfce
host: version 11895.21.0 (Official Build) dev-channel coral
kernel: Linux localhost 4.4.176-16032-ga91d6ee3c7f6 #1 SMP PREEMPT Wed Mar 20 00:25:14 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by Clearia** [comment]
#### If known, describe the steps to reproduce the issue:

sudo gedit /etc/environment
### begin crouton-generated environment variables
### end crouton-generated environment variables

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

LC_CTYPE="zh_CN.UTF-8" LC_ALL="zh_CN.UTF-8"

export XMODIFIERS=@im=fcitx

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT4_IM_MODULE=fcitx
export QT5_IM_MODULE=fcitx

**Comment by DennisLfromGA** [comment]
@Clearia,

Sorry, I know nothing about `fcitx` but I found a few resources that may help:

- [Configure (Ubuntu)](https://fcitx-im.org/wiki/Configure_(Ubuntu))
- [Ubuntu Chinese Setup](https://www.pinyinjoe.com/linux/ubuntu-18-gnome-chinese-setup.htm)

Also, it may help to show us the error and/or warning message(s) you're getting if any.

*Hope this helps,*
-**DennisLfromGA**
