### ISSUE TITLE
can't open download file in debian sid

### ISSUE THREAD

**Issue by Clearia** [dnschneid/crouton#4027]
name: debian
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/debian...
crouton: version 1-20190120145639~master:5bf96711
release: sid
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11895.33.0 (Official Build) dev-channel coral
kernel: Linux localhost 4.4.176-16032-ga91d6ee3c7f6 #1 SMP PREEMPT Tue Mar 26 00:59:08 PDT 2019 x86_64 GNU/Linux
freon: yes

**Comment by Clearia** [comment]
required key not available

**Comment by DennisLfromGA** [comment]
@Clearia,

Would it be possible to show us the error and/or warning message(s), please?

-**DennisLfromGA**

**Comment by Clearia** [comment]
because of fcitx issue, I back to bionic.
the file in downloads canopen and edit.

**Comment by DennisLfromGA** [comment]
@Clearia,

I'm not sure what problems fcitx was having with keys on sid and it doesn't look like we'll be able to figure that out.

If you've moved on and are no longer interested in resolving this you can close this issue or let us know and we'll close it.

-**DennisLfromGA**

**Comment by Clearia** [comment]
the ficitx I write in #4025

**Comment by Clearia** [comment]
the file in downloads can't open and edit.
