### ISSUE TITLE
Ubuntu 18.04 Bionic install issue within concerning systemctl using Unity

### ISSUE THREAD

**Issue by greenking13** [dnschneid/crouton#4028]
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190403182822~master:174af0eb
release: bionic
architecture: amd64
xmethod: xorg
targets: unity,core
host: version 11647.104.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 4.4.171-15926-g798b963ebef9 #1 SMP PREEMPT Wed Mar 20 23:40:18 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```

#### Please describe your issue:
So, while I was having difficulty creating a unity version of bionic, I was able to find https://github.com/dnschneid/crouton/issues/3995 ovitotv's comment, which allowed me to be able to create and get into Unity. The issue arises with Snap, which doesn't appear to be running, which led me to a much more strange issue... I don't seem to be having systemctl running.

snap install p7zip-desktop
error: cannot communicate with server: Post http://localhost/v2/snaps/p7zip-desktop: dial unix /run/snapd.socket: connect: no such file or directory

systemctl status snapd.service
System has not been booted with systemd as init system (PID 1). Can't operate.

I was wondering if anybody could help me figure this stuff out. I basically am trying to get the linux gui version of 7zip installed, which comes through the snap store. 

Thank you,
Michael Merrick

**Comment by Clearia** [comment]
I install bionic stuck of xorg intel driver.

**Comment by Imperial-Industries** [comment]
@greenking13, could you show the outputs of `sudo apt-get update` and `sudo apt-get upgrade` please. I think I may have a solution for you.

**Comment by Imperial-Industries** [comment]
You could try `service snap start`

**Comment by shoummashams** [comment]
I'm having the same issue

`$ snap install midori
error: cannot communicate with server: Post http://localhost/v2/snaps/midori: dial unix /run/snapd.socket: connect: no such file or directory
$ systemctl status snapd.service
System has not been booted with systemd as init system (PID 1). Can't operate.`

`chronos@localhost / $ sudo enter-chroot -n bionic croutonversion
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: bionic
architecture: amd64
xmethod: xorg
targets: xfce-desktop,xorg,xiwi,extension,touch,core,audio,cli-extra
host: version 12371.75.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:32:21 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.`

`service snap start` gives an "unrecognised service" error.

**Comment by Imperial-Industries** [comment]
Do you have SnapStore installed?

**Comment by shoummashams** [comment]
I did. I can't test it anymore as I have replaced my Chromebook with a Windows laptop and removed Crouton from it.

**Comment by Imperial-Industries** [comment]
Oh well then...

**Comment by Imperial-Industries** [comment]
We clear to close then?

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
