### ISSUE TITLE
Ran of out disk space on C7

### ISSUE THREAD

**Issue by zachfeldman** [dnschneid/crouton#403]
I installed Ubuntu (Gnome) on a brand new Acer C7 and it was pretty awesome - got Chromium and Sublime Text 2 installed as well.

I tried installing RVM and halfway through installing a Ruby I got an error saying I've run out of disk space.

Is there a way to bushwhack some more disk space out of this thing, or a way to check if I'm even on the correct disk? I know it only has 16gb of space total but I thought I'd at least be able to install Ubuntu/Gnome/Chromium/Sublime/Ruby.

**Comment by matheusparisotto** [comment]
How do I do a recovery with the usb? I am having the same problem.

**Comment by divx118** [comment]
@matheusparisotto https://support.google.com/chromebook/answer/1080595?hl=en&source=genius-rts There is also a linux way, just scroll down the page under "Other ways to recover a Chromebook"
