### ISSUE TITLE
Wrong user after switching to Ubuntu 

### ISSUE THREAD

**Issue by CaydenTheGamer** [dnschneid/crouton#4031]
I switch to Ubuntu and it asks for a login. I put the right host user and password. I know for sure the password is correct. After typing the user and pass, it says incorrect user. I'm sure that this is the right user. If I can change it, can someone please help?

**Comment by DennisLfromGA** [comment]
@CaydenTheGamer,

> I switch to Ubuntu and it asks for a login. 

How are you '*switching*' to Ubuntu?

If you use `enter-chroot` or any of the `start*` scripts it will log you in without a username or password prompt.

But, if you want to reset your password you can get into your chroot as the 'root' user with this -

- `sudo enter-chroot -u root [-n chrootname]`

Then, if you don't know the username, enter this -

- `grep 1000:1000 /etc/passwd | cut -d: -f1`

With that info. change the password of the user with -

- `passwd [username]`

Substituting [username] with the username returned in the `grep` command.
Enter the password twice for verification, it will not be displayed on the terminal for security.

*Hope this helps,*
-**DennisLfromGA**
