### ISSUE TITLE
UID 1000 not found in bionic

### ISSUE THREAD

**Issue by goelvatsal** [dnschneid/crouton#4035]
#### Please describe your issue:
I just installed Ubuntu 18.04/18.10 on a Chromebook Acer R11 and I get, "UID 1000 not found in bionic"  

#### If known, describe the steps to reproduce the issue:
sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/bionic...
UID 1000 not found in bionic
unmounting /mnt/stateful_partition/crouton/chroots/bionic...

**Comment by DennisLfromGA** [comment]
It sounds like it didn't finish, did you get any errors when you installed it?
What was the complete command you entered to install it?

You could run the following and see if it will ask you to finish the setup -
- `sudo enter-chroot -n bionic`

You could also just run a crouton update with -

- `sudo sh ~/Downloads/crouton -n bionic -u`

If you've made `crouton` executable with the new method just use -
- `sudo crouton -n bionic -u`

There are at least a couple of issues others have encountered when installing bionic, for more details see -

- bionic install fails when "Unable to locate package i3" #4020
- Bionic install failure: The following packages have unmet dependencies (xorg, xserver-xorg-video-intel) #3995

Both of those issues have some technical workarounds so if you've run into one or both of them you may be able to get it working.

*Hope this helps,*
-**DennisLfromGA**

**Comment by goelvatsal** [comment]
Hi DennisLfromGA, 
      I have just typed in the command(sudo sh ~/Downloads/crouton -n bionic -u) right now. I will reply back later if I have any issues.

Thanks, 
goelvatsal

**Comment by goelvatsal** [comment]
I have received this error:
```
Package 'xserver-xorg-video-all' is not installed, so not removed
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xorg : Depends: xserver-xorg (>= 1:7.7+19ubuntu7.1)
 xserver-xorg-video-intel : Depends: xorg-video-abi-23
                            Depends: xserver-xorg-core (>= 2:1.18.99.901)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
sh: 0: /tmp/crouton.NmM/host-bin/unmount-chroot: warning: script from noexec mount
/tmp/crouton.NmM/host-bin/unmount-chroot: 42: .: /tmp/crouton.NmM/host-bin/../installer/functions: warning: script from noexec mount
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bionic...
```

**Comment by DennisLfromGA** [comment]
@goelvatsal,

It looks like you're now running into the second issue I linked above:

- Bionic install failure: The following packages have unmet dependencies (xorg, xserver-xorg-video-intel) #3995

Take a look at that for a workaround.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Dylan-dev8520** [comment]
having trouble installing ubuntu bionic newest realease on my chromebook, any help would be greatly appreciated problem is as follows
Package 'xserver-xorg-video-all' is not installed, so not removed
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xorg : Depends: xserver-xorg (>= 1:7.7+19ubuntu7.1)
 xserver-xorg-video-intel : Depends: xorg-video-abi-23
                            Depends: xserver-xorg-core (>= 2:1.18.99.901)
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bionic...
