### ISSUE TITLE
Sudo crouton -u

### ISSUE THREAD

**Issue by goelvatsal** [dnschneid/crouton#4036]
#### Please describe your issue:
When I type in `sudo crouton -u`, I get `/usr/local/chroots/xenial does not exist; cannot update.
Valid chroots:
bionic`. I want to switch to bionic. How do I do that?

#### If known, describe the steps to reproduce the issue:
sudo crouton -u

**Comment by DennisLfromGA** [comment]
@goelvatsal,

Please show us the output of: `sudo edit-chroot -all`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Clearia** [comment]
sudo crouton -u -n bionic

**Comment by goelvatsal** [comment]
Thanks Clearia!

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
