### ISSUE TITLE
Can't open "sudo sh ~/Downloads/crouton -r trusty -t xfce"

### ISSUE THREAD

**Issue by CroutonIsAwesome** [dnschneid/crouton#4037]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by DennisLfromGA** [comment]
- [ ]  Make sure you've downloaded [crouton](https://goo.gl/fd3zc) and placed it in your Downloads directory.

- [ ] Install it using the new method linked below:

- The internet is wrong and all the tutorials are broken #4026

*Hope this helps,*
-**DennisLfromGA**
