### ISSUE TITLE
How do you assign the forward and back keys on chromebook to actually using forward and back instead of f1 and f2?

### ISSUE THREAD

**Issue by diamondrel** [dnschneid/crouton#4038]
Could I have ALT to switch from forward and back to f1 and f2? would this screw with switching from xfce to chromeos?

**Comment by DennisLfromGA** [comment]
@diamondrel,

Take a look at the [keyboard](https://github.com/dnschneid/crouton/blob/master/targets/keyboard) target, if you haven't installed it yet you could add it to your existing chroot with the following and see if it helps -

- `sudo crouton -t keyboard -u [-n chrootname]`

Also, check out this keyboard wiki  for some tips -

- [Keyboard](https://github.com/dnschneid/crouton/wiki/Keyboard)

*Hope this helps,*
-**DennisLfromGA**
