### ISSUE TITLE
Black screen when entering chroot

### ISSUE THREAD

**Issue by Oliver125342956** [dnschneid/crouton#4039]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /media/removable/USB Drive/bionic...
crouton: version 1-20190120145639~master:5bf96711
release: bionic
architecture: amd64
xmethod: xorg
targets: gnome
host: version 12068.0.0 (Official Build) dev-channel snappy 
kernel: Linux localhost 4.4.178-16442-g0fbafff95662 #1 SMP PREEMPT Tue Apr 9 21:59:36 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/bionic...

#### Please describe your issue:
I was trying to modify the permissions on the ~ (home) as a directory under vscode to bypass the need for root status in order to run an extension.  I tried to change the permissions of all directories using the command below.  Now whenever I open the chroot, there is a black screen followed by a hangup of the xorg server.  Enter-chroot still works however, the GUI component is broken.

#### If known, describe the steps to reproduce the issue:

chmod -R a+rwX ~

After running this command that changes the permissions of every directory under home, the chroot screen froze and I was forced to reboot my chromebook.  When trying to go to my chroot, an error (_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created) is shown.
It was a mistake to change all the permissions of the home directory so that I can more easily access them.

**Comment by DennisLfromGA** [comment]
@Oliver125342956,

According to the `chmod` [man page]() the upper case 'X' is used as follows -
> Execute only if the file is a directory (or already has execute permission for some user)

So I think that effectively turns off execute permission for files that need it.
You *may* be able to undo that with: `chmod -R a+rwx ~`
But that would give every file and folder under $HOME execute permission which is not ideal.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Oliver125342956** [comment]
@DennisLfromGA 
Thank yoo so much! That fixed it and the permissions should not be a problem as I am using a personal computer.

Should I be worring about any of these errors that may hinder the ability to use the chroot?
`_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.`
`xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)`

**Comment by DennisLfromGA** [comment]
@Oliver125342956,

As long as everything is working okay I'd just ignore those errors/warnings.
They have been around for a while, see:

- _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created. (failed to retrieve device information?) #3446

- Probably to do with xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted) #2926

*Hope this helps,*
-**DennisLfromGA**

Closing. Please re-open if this issue is still a concern.
