### ISSUE TITLE
Asking or password 

### ISSUE THREAD

**Issue by Big2112Mike** [dnschneid/crouton#4040]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by DennisLfromGA** [comment]
@Big2112Mike,

I'm gonna guess that you get a password prompt when entering the shell or launching your chroot.
If you've enabled 'Debugging Features' then that's normal, you'll first have to login in as root with the password you gave it and then run `chromeos-setdevpasswd` to give chronos a password.

If that's not the case please give us more details.

*Hope this helps,*
-**DennisLfromGA**
