### ISSUE TITLE
How to force delete 

### ISSUE THREAD

**Issue by goelvatsal** [dnschneid/crouton#4041]
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xorg
targets: touch,unity
host: version 12068.0.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 3.18.0-19116-g628a4dc6ea66 #1 SMP PREEMPT Tue Apr 9 21:50:09 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

```

#### Please describe your issue:
 I want to force delete xenial, but I get this:(By the way, I am doing dual-boot)

https://lh3.googleusercontent.com/wbAJ2SH9LKAy-S-eMp8U4f3KmQ15348BVQkkNxrdIA2HL-13E0A6WXfQhZ9qd4MEMc9xsFzLq3BRRDoEQyMJpQE_oL_zobLxQl9h0dtmAKShnY7hlsL3_IQC5M0vu_j6DZ-6K9kGFtP9_TrXJ3PM16a1eFI12n7UWquBdtGMjQySszv-mrtm1NBK-RuB_lCxdn2Kdd2WDP8HJeTM_hJwhqQ_dWmeXI9d6skZ72ZTCwBzrlv-h0LsXC3nuZgf0bHpMKqxZ4kyW86fuQh0sEwaoowxiNxro2W7l05_GEiOl5nROinGlesHMu81kxGUz_Zdz1t4mH8Ba1NYgXIrNX4Hg7Xnn0Rfyzl_SpIdmC9Eos_K9frl6HfztL9i23vRhCeoeGPVEDpNRDVygw3knUNr6S30IL0Hzv7PXHnUxewnTHDl2iPbechDXG_yWJ6j5DRLocjah0fJdNiXe2J_uqGBtPSwzvhmlFusBMWhbgfR0pLSYFGqGoMPqXhhigtHTCXD8UR0f1SK8UIpaqJZbZk2Vjw9h-3bnBnuvZ6qZgr5tREZGc9z7PcfgBF73pBGmVv0dONU9XFn4iLd-h3FvlOSv50Hciqsi7galLNKsDdLB-UMPrCB8GMEDoySMPM0oHErVNIWem_ISG0i8q_KdhicJn_4uRgJFS4=w1186-h665-no

also I'm also trying to install bionic, but it is not letting me because I can't uninstall xenial!
https://lh3.googleusercontent.com/cYXup75J3Trr_vqsslXG4izcZ0dACpbZwR18f0HPBXJ3A45iCI9WmZX8oHr8QmkPaI9djJDCfZyzK4mS2OJ0bYsdVD82vV80-_Vvm7Ur68lWDhITD-vRE0JsCNfSf4eGo5N7HQDzwXn8EY8iOU32zEHOBKlPr_mb9zKrYhcMwinPAe2vCQBNozf-oIg-60c25Qtz6UCK9IcWKPRhjQG5xs5ZR6XtSDupLL-0SxK43adOcYPev8kKEgwbuT3rDjdymAdXYcXlw6F2xLIY9RvYUgCpp5abVOvKAd6HP-SuvW2NN64dlsX4smziT84M-zHVMJHFutsLLQSY3ZVnNqbavjaTpMy8gFru55yutwchbswLvgnUTATCbZoagQ2IGdNNNFxlBACo7UsCfNiO8JaRhZFyNne_ocNAWS0NQcTHwAixeSoVRk3MH6DTUQusSa7Th8jqIC91quj6FFM7Prau9__NhvJNyZshSMcjaJLqvp60i2sGlRLJqZJXzhM1KvI3-sGNLHWAjnUFCu57ZWkt2sHeaMt2Ck-8Lea_0T6hy9vOGrj5_QNPas-zTv2ShAI_gQAwd0zrrzCqgB9VymJ9yd8vCFyQNJdodFFelEY3Ml9rV0NthHNhLZp5eVjtTZghqc2C87AcgnJJ_kP1WsBuOGu2tR4OprI=w1365-h604-no
#### If known, describe the steps to reproduce the issue:
sudo unmount-chroot -f xenial

**Comment by DennisLfromGA** [comment]
@goelvatsal,

> I want to force delete xenial, but I get this:(By the way, I am doing dual-boot)

( Both of the above links are not viewable by me. )

As you've discovered your xenial chroot is still mounted. 
The easiest way around that is to reboot your Chromebook and without launching any start scripts or entering the chroot run:

- `sudo delete-chroot xenial`

Then you should be able to install your bionic chroot.

*Hope this helps,*
-**DennisLfromGA**

**Comment by goelvatsal** [comment]
Thanks Dennis!
