### ISSUE TITLE
[CloudReady Beta 74.2] cannot create /sys/kernel/debug/dri/drm_master_relax: Operation not permitted

### ISSUE THREAD

**Issue by T7J7L** [dnschneid/crouton#4043]
```
sudo edit-chroot -all
name: bionic
encrypted: no
/usr/local/bin/enter-chroot: 403: /usr/local/bin/enter-chroot: cannot create /sys/kernel/debug/dri/drm_master_relax: Operation not permitted
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```

#### Please describe your issue:
Hello. Ever since I updated to CloudReady Beta 74.2, I cannot get Crouton working. It always results in the same error whether I try to update my chroot, startxfce4, or even the list command as pasted above. I can delete the chroot, but unfortunately installing again results in the same error. I also tried "Disabling RootFS Verification", but that made no difference. I'd rather not reinstall CloudReady, at least not without knowing if it'll change anything. Please help, thank you.

#### If known, describe the steps to reproduce the issue:
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton (same result without this step)
sudo crouton -r bionic -t xfce,xiwi,xorg (fails here, same with default xenial)
sudo startxfce4 (also fails here)

**Comment by DennisLfromGA** [comment]
@T7J7L,

There was a crouton pull request merged a while back -

- Enable drm_master_relax: Allow normal user to set/drop DRM master. #602

It would "Allow X server running as **normal user** to set/drop DRM master"
I'm not sure why it can't create that file on the newer CloudReady Beta 74.2 

Maybe one of the devs will drop by and lend a hand and/or maybe the [Neverware Zendesk support site](https://neverware.zendesk.com/hc/en-us) could help out.

*Hope this helps,*
-**DennisLfromGA**

**Comment by T7J7L** [comment]
I updated my old thread at CloudReady support, here's what they said:
https://neverware.zendesk.com/hc/en-us/community/posts/360029034174-Cannot-start-Crostini-Flatpak-buggy-apps?mobile_site=true&page=1#community_comment_360004808593

**Comment by DennisLfromGA** [comment]
@T7J7L,

Thanx for the link.

We can keep this open for now since it's not clear to me at least what may be required.
You can close it of course if you're satisfied with the Zendesk response.

-**DennisLfromGA**

**Comment by T7J7L** [comment]
Since the installation was already not in a state I'd prefer, I poked around some more and decided to start fresh for this bug.
So fresh install it is, this time with a spare/testing Gmail that is pretty much clean/default. Updated to Beta 74.2, and followed "The easy way" in README.md, but failed with exact same error as before. See attached screenshot (made before) for more details.
TBH, I'm more likely going to restore my past MX Linux install than to set up everything with my main Gmail again at this point...

![error](https://user-images.githubusercontent.com/49735868/56381108-c9e39700-61c8-11e9-896c-53e5eaf7a90e.png)

**Comment by DennisLfromGA** [comment]
@T7J7L,

I'm wondering if you have the flag [#enable-myfiles-volume](https://neverware.zendesk.com/hc/en-us/community/posts/360029072334/comments/360004685913) and if disabling it helps at all?

-**DennisLfromGA**

**Comment by T7J7L** [comment]
Disabling/Enabling the flag made no difference unfortunately, even after full reboots.

**Comment by T7J7L** [comment]
I'm guessing everything is in control, and I don't need to do anything? So I can restore that machine back to what it had before this CloudReady mess of sorts? Though seriously please let me know soon, because I'm itching to just do that likely before tomorrow ends...

**Comment by mabalacat** [comment]
Did you ever find a solve for this? I'm encountering the same issue and can't find anything useful.

**Comment by T7J7L** [comment]
@mabalacat I actually tried Stable 74.4 not too long ago and experienced the same disappointment again. CloudReady Beta 76.2 is available now though, and they said the MyFiles issue is fixed. Maybe try that and please let me know? Thanks.

**Comment by T7J7L** [comment]
Bemused to report that nothing's changed on CloudReady 76.3 and w/e version of Crouton is the latest as of now. Though I didn't bother to "Install OS" onto internal drive (and signed in with a virtually barebones test Gmail), I doubt running it as a "Live Media" was the issue as the error is exactly the same other than Crouton's /tmp directory changes. Oh well, I can't say I won't bother with CloudReady or Crouton anymore, but disappointed to say the least.

**Comment by gimaldi** [comment]
Hello,
maybe I've found a fix. Here you can find my solution:
https://neverware.zendesk.com/hc/en-us/community/posts/360033733113-Problem-installing-Crouton
I also ask if the Crouton developers can check if it is the correct solution.
