### ISSUE TITLE
Cannot boot to Crouton 

### ISSUE THREAD

**Issue by BluebellGamer** [dnschneid/crouton#4044]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: armhf
xmethod: xorg
targets: gnome
host: version 11895.33.0 (Official Build) dev-channel daisy_skate 
kernel: Linux localhost 3.8.11 #1 SMP Tue Mar 26 00:22:27 PDT 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
Cannot boot into GNOME.
I have a HP Chromebook 11 G2
I am unable to boot into gnome using sudo startgnome
i get error addScreen/ScreenInit failed for driver 1
failed to load driver: exynos
EGL_MESA_drm_image required.
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1555594813.833446 sender=:1.11 -> destination=:1.64 serial=1015 reply_serial=2
   boolean true

#### If known, describe the steps to
 reproduce the issue:
Downloaded crouton file
Installed GNOME Ubuntu using sudo sh ~/Downloads/crouton -t gnome
ran sudo startgnome

**Comment by DennisLfromGA** [comment]
@BluebellGamer,

I'm going to dup this similar issue to:

- X startup failure: "AddScreen/ScreenInit failed for driver 1" #3164

For a possible workaround see the last comment.

*Hope this helps,*
-**DennisLfromGA**
