### ISSUE TITLE
Chroot fatal error

### ISSUE THREAD

**Issue by AnonymousAnon1178** [dnschneid/crouton#4045]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20190403182822~master:174af0eb
release: trusty
architecture: amd64
xmethod: xorg
targets: kde,touch
host: version 11647.104.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-19030-g15d00031737b #1 SMP PREEMPT Wed Mar 20 23:41:03 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 11647.104.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 3.18.0-19030-g15d00031737b #1 SMP PREEMPT Wed Mar 20 23:41:03 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:

on running sudo enter-chroot kde4, my terminal says, "Entering /mnt/stateful_partition/crouton/chroots/trusty...
Unmounting /mnt/stateful_partition/crouton/chroots/trusty..."
The chroot enters, but then immediately exits.

**Comment by DennisLfromGA** [comment]
@AnonymousAnon1178,

Have you tried this from crosh? `sudo startkde`
Or first enter the chroot with: `sudo enter-chroot`
And then enter: `kde4`

That might let you/us know where it's failing and give some error output.

*Hope this helps,*
-**DennisLfromGA**
