### ISSUE TITLE
Manjaro

### ISSUE THREAD

**Issue by DeadRoblox** [dnschneid/crouton#4046]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome-desktop
host: version 12068.0.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Tue Apr 9 21:58:23 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.
```
Is it possible to install manjaro?

**Comment by TheMinigun** [comment]
Also if I were to install manjaro I would install it on an external device. I can not find out how (since security has changed) in the README.md

**Comment by DennisLfromGA** [comment]
@TheMinigun,

> Is it possible to install manjaro?

There was a fork for Manjaro quite a while back but I think it's been abandoned -

- Adding Manjaro as a release #688

It might be doable but will undoubtedly take some time & effort.

> Also if I were to install manjaro I would install it on an external device. I can not find out how (since security has changed) in the README.md

The new installation method puts `crouton` in `/usr/local/bin` so it becomes executable, it doesn't change how you install `crouton` on external devices. But, some have run into issues with mounting external media, see this for a workaround -

- [Issue 914576: Chrome OS does not detect external drives properly#c7](https://bugs.chromium.org/p/chromium/issues/detail?id=914576#c7)

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheMinigun** [comment]
Thanks. Do you think  somebody actually will start making Manjaro a viable option again? (without it being a hassle to install)
