### ISSUE TITLE
sudo sh -e ~/Downloads/crouton -t list   --still works

### ISSUE THREAD

**Issue by prairiedock** [dnschneid/crouton#4048]
```
Please paste the output of the following command here: sudo edit-chroot -all
No chroots found in /mnt/stateful_partition/crouton/chroots

```

#### Please describe your issue:

Chrome OS v. 73.0.3683.114
Just downloaded newest crouton

Ran: sudo sh -e ~/Downloads/crouton -t list

Still works! Doesn't seem like much of a security "improvement". Perhaps crouton should verify it is located in /usr/local/bin before executing?

**Comment by icecream95** [comment]
The security improvement is part of a Chrome OS update.

This update hasn't arrived in the stable channel yet, and so only those who have chosen to use the dev channel (this is different from developer mode) of Chrome OS are affected currently - the patch will be part of a stable release in a month or so, and from then, you will need to follow the updated installation instructions.

**Comment by prairiedock** [comment]
If you're on the dev channel, perhaps you can tell us: does "bash -e ~/Downloads/my-script ..." not work anymore in crosh shell? If it does work, they don't seem to have accomplished very much in the way of preventing rogue executions. If it doesn't, haven't they broken bash?

I'm sure I'm not understanding something here....

**Comment by dnschneid** [comment]
The changes to bash haven't been merged yet; only dash is affected while
the chromium project cleans up its usage internally (mostly test-related, I
think). Similar enforcement is indeed coming to bash, though. The patch
exists and will be applied when it won't break everything.

**Comment by JL2210** [comment]
The update is out. We're all goners :P

**Comment by dnschneid** [comment]
💥
