### ISSUE TITLE
Getting App Armor To Run

### ISSUE THREAD

**Issue by jasonstone20** [dnschneid/crouton#4049]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: bionic
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,keyboard,xiwi,xorg
host: version 11647.154.0 (Official Build) stable-channel enguarde 
kernel: Linux localhost 4.4.171-15931-g4b1bceefc44c #1 SMP PREEMPT Sun Apr 14 19:11:03 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.
```
When I run:
etc/init.d/apparmor

I get:
-bash: etc/init.d/apparmor: No such file or directory

When I run:
sudo apparmor_status

I get:
apparmor module is not loaded.

I can't get App Armor running

**Comment by sarahmccuan** [comment]
This may be a silly question, but are you sure you have apparmor installed? If not, try
`sudo apt-get install apparmor`

Crouton is lightweight and doesn't install all the programs you might expect if you've used something like the standard Ubuntu iso's before.
