### ISSUE TITLE
can't enter desktop environment

### ISSUE THREAD

**Issue by Clearia** [dnschneid/crouton#4050]
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190403182822~master:174af0eb
release: bionic
architecture: amd64
xmethod: xorg
targets: keyboard,lxde
host: version 12105.11.0 (Official Build) dev-channel coral 
kernel: Linux localhost 4.4.178-16472-g09559f81b6bd #1 SMP PREEMPT Thu Apr 25 00:39:12 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
#### Please describe your issue:
sudo startlxde
Entering /mnt/stateful_partition/crouton/chroots/bionic...
-su: 1: /etc/profile.d/10-budgie-desktop-common.sh: [[: not found
-su: 1: /etc/profile.d/10-budgie-desktop.sh: [[: not found
-su: 2: [: x: unexpected operator
-su: 2: [: x: unexpected operator
dbus[17243]: Unknown group "power" in message bus configuration file
-su: 1: /etc/profile.d/10-budgie-desktop-common.sh: [[: not found
-su: 1: /etc/profile.d/10-budgie-desktop.sh: [[: not found
-su: 2: [: x: unexpected operator
-su: 2: [: x: unexpected operator
-su: 1: /etc/profile.d/10-budgie-desktop-common.sh: [[: not found
-su: 1: /etc/profile.d/10-budgie-desktop.sh: [[: not found
-su: 13: cd: can't cd to /usr/share/budgie-desktop/keycontrol/
-su: 13: .: Can't open ./gnome-custom-keybinding-setup
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bionic...
#### If known, describe the steps to reproduce the issue:
sudo enter-chroot
sudo xinit

**Comment by DennisLfromGA** [comment]
@Clearia,

It looks like some files are missing when you try to launch the desktop.

I'd suggest doing a crouton update with: `sudo crouton -n bionic -u`
Or at least a package update and upgrade in the chroot with: `sudo apt update && sudo apt upgrade`
You may also be abe to 'fix' things with this too: `sudo apt-get -f install`

*Hope this helps,*
-**DennisLfromGA**
