### ISSUE TITLE
I cant remove a croot, it says not found

### ISSUE THREAD

**Issue by manginger** [dnschneid/crouton#4052]
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost / $ sudo edit-croot -all
sudo: edit-croot: command not found
chronos@localhost / $ 



#### Please describe your issue:
Im trying to delete a croot but whenever i try to delete it with sudo delete-croot precise it says sudo: delete-croot: command not found

Ive tried alot of things and people had the same problem but whenever i did sudo sh ~/Downloads/crouton -b`  it said it installed the things but when i did sudo delete-croot precise it still said command not found.

#### If known, describe the steps to reproduce the issue:

**Comment by pcs3rd** [comment]
If needed, you could just run `$sudo rm -r /path/to/monstrous/chroot/`. If you are running crouton on a external device (such as an sd card), just reformat the card and the wiki has a guide to format cards ext4.

**Comment by JL2210** [comment]
You misspelled the command. Run `sudo edit-chroot -all`. Notice the `h`.

**Comment by JL2210** [comment]
For future reference, the actual word is "chroot". It stands for "**ch**ange **root**".

**Comment by DennisLfromGA** [comment]
@manginger,

Like mentioned above, you misspelled `edit-chroot` so that command failed.

To delete a chroot use: 

- `sudo delete-chroot [options] name [...]`

You can enter one or more names or use `*` to delete all of them.

If that doesn't work please let us know. 

*Hope this helps,*
-**DennisLfromGA**

**Comment by Imperial-Industries** [comment]
I would suggest closing this issue now unless your problem is not resolved yet.

**Comment by DennisLfromGA** [comment]
@Imperial-Industries,

Agreed.

Closing. Please re-open if this issue is still a concern.
