### ISSUE TITLE
Use Cros-guest-tools to get chromeos integration

### ISSUE THREAD

**Issue by pcs3rd** [dnschneid/crouton#4053]
Currently, I am setting up a ubuntu bionic chroot (completely irrelevent) as this is more of a question of how well the crostini guest tools would mesh and if they would even work. [This guide](http://linuxiumcomau.blogspot.com/2018/08/introduction-to-crostini-part-3-using.html) explains how to install cros-guest-tools in a new termina container. Could this be done with a crouton chroot and work?

**Comment by DennisLfromGA** [comment]
@pcs3rd,

What Chrome OS integration are you missing?

I don't know if anything would *break* but I don't think they'd *mesh* well.

According to the '[cros-guest-tools-deb](https://chromium.googlesource.com/chromiumos/containers/cros-container-guest-tools/+/master/cros-guest-tools/BUILD)' package description it includes things for plumbing it into the CrOS dbus that I don't think are appropriate or needed in crouton. You can take a look at the package build and install the other things you think you might want though.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pcs3rd** [comment]
@DennisLfromGA I was more or less wanting to see if I could get shelf integration with a running crouton instance since sommelier can be run too.

**Comment by erenoglu** [comment]
+1 for this. I'd love to have my crouton apps listed in the ChromeOS launcher and launched in a browser tab or separate window when clicked.

**Comment by erenoglu** [comment]
I'd love this as well so that I can get rid of Crostini. For me it's too complex (a container running in a VM!!!) for little benefit for my use case. The only downside of using Crouton is lack of Crostini level integration, ie applications appearing in launch menu, same window manager/taskbar, open with crouton app from files app, etc.

**Comment by pcs3rd** [comment]
@erenoglu as I hinted to earlier, if I remember right you can run versions of sommelier on crouton instances and that will give you window integration. Guest-tools would just make it easier to manage windows + start apps without using a cli. I haven't used crostini in a while (16gb Chromebook, crouton stuff on sdcard), because of the changes in where exacutables can be run. I've taken mr.chromebox's full eufi firmware in preferance.

**Comment by pcs3rd** [comment]
@erenoglu as I hinted to earlier, if I remember right you can run versions of sommelier on crouton instances and that will give you window integration. Guest-tools would just make it easier to manage windows + start apps without using a cli. I haven't used crostini in a while (16gb Chromebook, crouton stuff on sdcard), because of the changes in where exacutables can be run. I've taken mr.chromebox's full eufi firmware in preferance.
