### ISSUE TITLE
Can someone tell me how to install on an SD Card since the steps changed?

### ISSUE THREAD

**Issue by TheMinigun** [dnschneid/crouton#4054]
I don't have my chroot anymore, I deleted it and want to install a clean new install on an SD Card. But I have read through the README.md and it did not seem to help. I did not understand the steps to install on an SD Card. Please help!

-J

**Comment by virgilmk** [comment]
Hey, I updated the Wiki. Look there for how to install on an SD Card. Good luck, J!

**Comment by DennisLfromGA** [comment]
@virgilmk,

Link please, the below wiki article -

- [How To Install To External Drive](https://github.com/dnschneid/crouton/wiki/How-To-Install-To-External-Drive)

Still shows using: `sudo sh -e ~/Downloads/crouton ...`

----
@TheMinigun,

Not much has changed once you install `crouton` in `/usr/local/bin` just use:

- `sudo crouton -p ...`

----
*Hope this helps,*
-**DennisLfromGA**

**Comment by TheMinigun** [comment]
Ok thanks!

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
