### ISSUE TITLE
Sudo startunity command not found

### ISSUE THREAD

**Issue by virgilmk** [dnschneid/crouton#4056]
```
crosh> shell

chronos@localhost / $ cd /media/removable/SD\ Card/bin

chronos@localhost /media/removable/SD Card/bin $ sudo startunity

sudo: startunity: command not found
```

It seems that my computer does not have the tools to start crouton. Also, apt-get is not recognized by Chromebooks so doing ```sudo apt-get update``` doesn't work.

**Comment by virgilmk** [comment]
Does anyone have a way to install the tools?

**Comment by virgilmk** [comment]
So, I realize after looking back through the filesystem that ```startunity``` exists but is not recognized by the computer. Anyone got a hotfix?

**Comment by rmartin16** [comment]
(I"m not fully plugged in to the latest ChromeOS security updates but)

On SD Cards, you need to manually specify the interpreter. So, try `sudo sh startunity` or `sudo bash startunity`.

**Comment by virgilmk** [comment]
> (I"m not fully plugged in to the latest ChromeOS security updates but)
> 
> On SD Cards, you need to manually specify the interpreter. So, try `sudo sh startunity` or `sudo bash startunity`.

Hey, thanks! I forgot that I was stupid.
