### ISSUE TITLE
xiwi audio is broken

### ISSUE THREAD

**Issue by Asternitix** [dnschneid/crouton#4058]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: beta
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/beta...
crouton: version 1-20190403182822~master:174af0eb
release: buster
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,extension,core,audio
host: version 11895.95.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sat Apr 27 23:33:22 PDT 2019 x86_64 GNU/Linux
freon: yes
#### Please describe your issue:
audio is not present using vlc in a xiwi window

#### If known, describe the steps to reproduce the issue:
install vlc
execute sudo startxfce4
play any video.
 please let me know if you want the vlc errors.

**Comment by Hacksawfred3232** [comment]
Have you tried updating the chroot? A problem that I found (And trying to rectify) is that the Alsa directory does not get created before the config file is made, which causes it to drop the file into /tmp. Updating runs the script again, which then should detect the directory.

**Comment by Asternitix** [comment]
I’ll try that. Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Asternitix** [comment]
That fixed it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
