### ISSUE TITLE
sudo crouton -u -n xenial failed to update

### ISSUE THREAD

**Issue by mdwy62** [dnschneid/crouton#4062]
#### Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial
#### Here is the error statement: from sudo crouton -u -n xenial:
Extracting templates from packages: 100%
(Reading database ... 96993 files and directories currently installed.)
Preparing to unpack .../archives/apt_1.2.31_amd64.deb ...
Unpacking apt (1.2.31) over (1.2.29ubuntu0.1) ...
dpkg: error processing archive /var/cache/apt/archives/apt_1.2.31_amd64.deb (--unpack):
 unable to stat './usr/bin/apt' (which I was about to install): Structure needs cleaning
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu11) ...
/sbin/ldconfig.real: /usr/lib/x86_64-linux-gnu/libapt-inst.so.2.0.0 is not an ELF file - it has the wrong magic bytes at the start.

Errors were encountered while processing:
 /var/cache/apt/archives/apt_1.2.31_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial..

#### Please describe your issue:
Can't update the xenial chroot. 
First I downloaded the latest crouton and ran: 
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton

#### If known, describe the steps to reproduce the issue:
Here are my system specs:
cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={BABC2E82-8F7D-26E5-EE66-4C60A2B41DBC}
CHROMEOS_RELEASE_BOARD=candy-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=165
CHROMEOS_RELEASE_BUILDER_PATH=candy-release/R72-11316.165.0
CHROMEOS_RELEASE_BUILD_NUMBER=11316
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=72
CHROMEOS_RELEASE_DESCRIPTION=11316.165.0 (Official Build) stable-channel candy 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11316.165.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11316.165.0

**Comment by DennisLfromGA** [comment]
@mdwy62,

Haven't seen that myself but here are some suggestions:
1. reboot
2. Get into the chroot with `enter-chroot` and if it asks if you want to finish the setup let it try to do that.
3. Get into the chroot as root with `enter-chroot -u root` and run `apt update` then `apt upgrade`
4. Try updating your chroot again with `sudo crouton -u -n xenial`

*Hope this helps,*
-**DennisLfromGA**

**Comment by mdwy62** [comment]
Thanks Dennis. I tried all of these steps and at each one, I get the same error with apt_1.2.31_amd64.deb (below).
I had to use apt-get instead of apt for step 3. 
Is there a way to delete this downloaded deb file to force it to retrieve it again? If it is corrupted in some way, it seems to keep trying to install the local copy.

dpkg: error processing archive /var/cache/apt/archives/apt_1.2.31_amd64.deb (--unpack):
 unable to stat './usr/bin/apt' (which I was about to install): Structure needs cleaning
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu11) ...
/sbin/ldconfig.real: Cannot mmap file /usr/lib/x86_64-linux-gnu/libapt-inst.so.2.0.0.

Errors were encountered while processing:
 /var/cache/apt/archives/apt_1.2.31_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mdwy62** [comment]
There is some problem with /usr/bin/apt:
xenial)root@localhost:/usr/bin# cd ./apt
-su: cd: ./apt: Structure needs cleaning

**Comment by mdwy62** [comment]
Just documenting that there are earlier errors after sudo crouton -u -n xenial, about "no such file or directory"

After this operation, 155 kB of additional disk space will be used.
apt-extracttemplates: error while loading shared libraries: libapt-inst.so.2.0: cannot open shared object file: No such file or directory
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 32%apt-extracttemplates: error while loading shared libraries: libapt-inst.so.2.0: cannot open shared object file: No such file or directory
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 65%apt-extracttemplates: error while loading shared libraries: libapt-inst.so.2.0: cannot open shared object file: No such file or directory
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 98%apt-extracttemplates: error while loading shared libraries: libapt-inst.so.2.0: cannot open shared object file: No such file or directory
debconf: apt-extracttemplates failed: No such file or directory
Extracting templates from packages: 100%
(Reading database ... 96993 files and directories currently installed.)
Preparing to unpack .../archives/apt_1.2.31_amd64.deb ...
Unpacking apt (1.2.31) over (1.2.29ubuntu0.1) ...
dpkg: error processing archive /var/cache/apt/archives/apt_1.2.31_amd64.deb (--unpack):
 unable to stat './usr/bin/apt' (which I was about to install): Structure needs cleaning
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu11) ...
/sbin/ldconfig.real: Cannot mmap file /usr/lib/x86_64-linux-gnu/libapt-inst.so.2.0.0.

**Comment by DennisLfromGA** [comment]
@mdwy62,

> Is there a way to delete this downloaded deb file to force it to retrieve it again? If it is corrupted in some way, it seems to keep trying to install the local copy.

You may be able to remove it from: /var/cache/apt/archives/apt_1.2.31_amd64.deb 
But that may leave you out on a limb.

I think I would first rename /var/cache/apt/archives/apt_1.2.31_amd64.deb to something else then download it from here:
- http://mirrors.kernel.org/ubuntu/pool/main/a/apt/apt_1.2.31_amd64.deb

And install it with `dpkg -i apt_1.2.31_amd64.deb`

Also, if you can install `aptitude` (with `sudo apt-get install aptitude`) try updating & upgrading with it instead.
If you can't get it that way then maybe download it from here:

- http://mirrors.kernel.org/ubuntu/pool/main/a/aptitude/aptitude_0.7.4-2ubuntu2_amd64.deb

and install it with `dpkg` per above.

----
That 'Structure needs cleaning' error looks pretty serious. Hopefully re-installing `apt` will remedy it, otherwise, you may have to remove or rename /usr/bin/apt before you can move forward.

*Hope this helps,*
-**DennisLfromGA**

**Comment by mdwy62** [comment]
Thanks again, Dennis.

I think it is a file structure problem. So my understanding is that the "Structure that needs cleaning"  is  within the chroot (xenial) itself, which is unmounted every time I log out of ubuntu. I am not aware though that crouton (or ChromeOS) offers any tools like e2fsck or gparted for me to try to repair the chroot from outside, when it is unmounted. Do you know of any? Also do you know where the (default) location for chroot is, when it is unmounted? Without repair tools, I will revert to a backup and see if the problem persists there. 

Regards,

Mark

**Comment by mdwy62** [comment]
sudo edit-chroot -d xenial doesn't work either. Without being able to delete the chroot I cannot use my backup.  
Does anyone know if there a powerwash option that preserves developer mode or will I have to reset that as well?

**Comment by mdwy62** [comment]
Yes, Ctl-Alt-Shft-R from login will restore and one can remain in developer mode. Was able to restore backup and everything is running fine. Crouton is amazing!

**Comment by DennisLfromGA** [comment]
@mdwy62,

Glad you got it going again, good job. 👍

For future reference, you can powerwash and even do a full recovery while in Developer mode, the device will stay there until you explicitly leave Developer mode at the 'scary boot screen' by pressing the spacebar and following the prompts.

> I am not aware though that crouton (or ChromeOS) offers any tools like e2fsck or gparted for me to try to repair the chroot from outside, when it is unmounted. Do you know of any?

CrOS *does* come with `e2fsck` and a probably a few other repair tools.

> Also do you know where the (default) location for chroot is, when it is unmounted?

If you installed your chroot in the *default* location on internal storage your xenial chroot will be under -
- `/usr/local/chroots/xenial` 

You can access it directly while unmounted and not running.

*Hope this helps,*
-**DennisLfromGA**
