### ISSUE TITLE
Is there a way to make a crouton chroot use Chrome OS VPN (that is setup by an Android Play Store app)?

### ISSUE THREAD

**Issue by brizzbane** [dnschneid/crouton#4069]
```
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20190403182822~master:174af0eb
release: stretch
architecture: amd64
xmethod: xorg
targets: xorg,gnome,xiwi,keyboard,core,extension
host: version 12105.42.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-19339-g3e4e496860da #1 SMP PREEMPT Fri May 17 02:20:05 PDT 2019 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

I have a VPN running on Chrome OS that is setup by an Android Play Store app, https://play.google.com/store/apps/details?id=com.fast.free.unblock.thunder.vpn&hl=en_US, as an example.  

The chroot does not use this VPN connection.  (A curl request inside the chroot to http://api.ipify.org, shows that it is using the original, non-VPN IP address).

#### If known, describe the steps to reproduce the issue:

I have seen https://github.com/dnschneid/crouton/wiki/VPNC.  I do not have the 'settings' for the setup/config of vpnc.conf, **and ideally would like to be able to use any store VPN app**.  In the wiki I read:

> some VPNs requires client features and configurations that are not available. For those networks, it is possible to establish a VPN connection from a chroot that is usable from both within the chroot and Chromium OS.

Which made me hopeful when I first started reading it.  However, at configuration, it asks for settings, which I do not have access to since it is an android app.

If it is not possible, I get it.  If it is possible, or there is some way that it *could* be possible, if anyone could point me in the right direction, or offer any help at all, it would be much appreciated!

I have read, and seen the solutions (on Reddit) for using OpenVPN or Private Internet Access VPN (You would have knowledge of actual settings to use to be able to setup).  **I am wanting/trying to make this work with any Play Store VPN that sets up a VPN in ChromeOS.**  

***
I was actually kind of surprised when I first checked the IP that it was NOT going through the VPN.  I figured that "that" would be a problem people may have been trying to figure out (how to get chroot to NOT go through ChromeOS VPN).

Anyways...
***

Thank you.

**Comment by rmartin16** [comment]
I think this is much more a function of the VPN application creating the tunnel. Some VPN applications seem to configure the tunnel such that everything goes through it...others not...it may also be a function of chromeos version or even hardware. Google searching suggests this is certainly a varying topic.

For me anyway, running the TorGuard VPN android app on my samsung pro routes Android, ChromeOS, and crouton traffic through the VPN.

**Comment by rmartin16** [comment]
also...this might help...mine's been set to "default" for a while now though...

within [chrome://flags](chrome://flags), there's Enable ARC VPN integration. ("Allow Android VPN clients to tunnel Chrome traffic. – Chrome OS")
