### ISSUE TITLE
Problem installing new crouton

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [dnschneid/crouton#4070]
```
CHROOT DIDN'T FINISH
```

#### Please describe your issue:
E: Couldn't download packages: locales systemd
debootstrap error log:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 51328  100 51328    0     0  34822      0  0:00:01  0:00:01 --:--:-- 34964
Failed to run debootstrap.

#### If known, describe the steps to reproduce the issue:
`sudo crouton -r xenial -t xfce`

**Comment by petermmiller** [comment]
See https://github.com/dnschneid/crouton/issues/4106#issuecomment-526027391

**Comment by DennisLfromGA** [comment]
Thanx @petermmiller 

Closing, please track on: "Failed to run deboot strap" #4106
