### ISSUE TITLE
Can't use kali-rolling with GNOME

### ISSUE THREAD

**Issue by CroutonHacker** [dnschneid/crouton#4071]
On multiple times, I have tried setting up kali-rolling with the GNOME target. Every time, I get the same result near the end of setup:
```
E: Unable to locate package dconf-tools
Failed to complete chroot setup.
```
I have tried logging into the chroot as the root user and manually installing the dconf-tools package, but it produces the same result; unable to locate the package.

I typed:
```
sudo crouton -r kali-rolling -t gnome
```
How do I fix this issue? I do have the latest release of crouton!

**Comment by brizzbane** [comment]
Same for buster, and -t gnome-desktop

**Comment by brizzbane** [comment]
also same for sid
