### ISSUE TITLE
Observations on crouton and Crostini

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#4073]
I bought an HP Chromebook 4GB RAM (double the Dell). The native Chromebook terminal seems to run noticeably slower than the 2GB RAM Dell, but that may due to it being a VM and not a sandboxed part of the filesystem itself. They are both running in CLI mode.

**Comment by Amplespencer** [comment]
Virtualization doesn't need to be slow.. something something.. --some random guy probably on a google form somewhere

it's limited by hardware acceleration

when crostini gets hardware acceleration it will be fast

**Comment by Riktheprick** [comment]
> Virtualization doesn't need to be slow.. something something.. --some random guy probably on a google form somewhere
> 
> it's limited by hardware acceleration
> 
> when crostini gets hardware acceleration it will be fast

I honestly doubt it. I'm on a nami based chromebook and I've tested crostini hardware acceleration (with the cros-gpu-alpha packages) and the performance was utter dogshit in comparison to a dual boot or chroot. I was utterly shocked by just how much worse it was. I figured 5% or so was fair, but I straight up only 12fps in dolphin on the vulkan backend (if it wasn't working, it wouldn't have even opened at all)

**Comment by aidylewis** [comment]
What's the general consensus are we sticking with crouton over Google's native VM? I wasn't able to open greater than one crostini window, so I have been using crostini and crouton since yesterday which sounds nuts.

**Comment by Amplespencer** [comment]
Stick to crouton until google fixes it’s vm. If google optimizes enough
Virtualization could be fast enough to not need crouton mostly. Again,
virtualization *Doesn’t have to be* slow. it just is right now

**Comment by DennisLfromGA** [comment]
I'm sticking with both.

**Comment by danrmiller** [comment]
I used to think it would be handy to chroot via crouton the filesystem crostini uses, for the all-too-often times and instances when crostini doesn't work well. But that doesn't help, like in the case of the recent problem (https://bugs.chromium.org/p/chromium/issues/detail?id=969127) where the whole VM wouldn't boot because of a typo https://chromium-review.googlesource.com/c/chromiumos/platform2/+/1635832/2/vm_tools/concierge/service.cc#b1616

So I think with sommelier (https://github.com/dnschneid/crouton/wiki/Sommelier-%28A-more-native-alternative-to-xiwi%29) its back to crouton for me

**Comment by aidylewis** [comment]
Managed to completely break the VM and had to powerwash.  Dog slow as has been previously mentioned. Moved back to crouton. Thanks for the all the work @dnschneid. It would be an idea for Google to work with you.

**Comment by firepick1** [comment]
Crostini on my new Pixelbook 2019 is  over 3x SLOWER than crouton on my Chromebook Pixel 2015.  
Crostini feels like my Apple //c from decades ago. It's just not ready for real work.

Heading back to crouton. Thank you @dnschneid
