### ISSUE TITLE
[improvement] can budgie-desktop be added as a target?

### ISSUE THREAD

**Issue by Amplespencer** [dnschneid/crouton#4074]
I have no clue how to manually start it and would like to be able to type `sudo startbudgie`.

`budgie-desktop` is the version without common applications and `budgie-desktop-environment` has common apps.

I really like budgie-desktop (especially on laptops) and think it would work great on a chromebook. If this somehow isn't possible I just want to be able to start budgie-panel on gnome since it's almost the same thing.

*this is probably possible with gnome-session but it complains about logind not being setup*

**Comment by DennisLfromGA** [comment]
@Amplespencer,

This comment shows how to *re-start* the budgie desktop -
- https://github.com/UbuntuBudgie/budgie-desktop-environment/issues/10

I imagine setting up a start* script with those commands might work for you.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Amplespencer** [comment]
thanks bro, will try later.

**Comment by Amplespencer** [comment]
wait actually how do I make a start* script (bash I assume)? where is it
located? I assumed they would be in /usr/bin or /bin but they aren't


also this does start budgie-panel for me, but now I still have the gnome
panel at the top and I don't know what it is called so I can't just kill it
with killall.

**Comment by DennisLfromGA** [comment]
@Amplespencer,

The 'host-bin' files are located in `/usr/local/bin` by default.
Take a look at the 'start*' scripts here for examples: 
- https://github.com/dnschneid/crouton/tree/master/host-bin

I'm not sure about the gnome-panel issue, since you added the gnome target as a base for budgie it may not be able to be separated.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
If you'd like to invest the time & effort you can create a budgie-desktop target via a pull request.

I'm closing this issue/feature request now.

**Comment by Amplespencer** [comment]
thank you, if I get it working I will make a pull request
