### ISSUE TITLE
iPhone doesn't connect to xfce4 crouton

### ISSUE THREAD

**Issue by pardestakal** [dnschneid/crouton#4075]
Hello, I've installed xfce4 on my Chromebook R11 with the bionic release. Everything seems to be going well except one thing, I am trying to get my iPhone 8 to connect with the Chromebook. I am a beginner so I don't really understand the other posts. My iPhone is iOS 12.3.1. Also when I connect it to my Chromebook while ubuntu is running but I am on the Chrome OS shell it says `croutonwebsocket error: EError timeoutthunar-volman: Unsupported USB device type "usb". thunar-volman: Unsupported USB device type "(null)".` hope this info helps.

**Comment by ceedveed** [comment]
Have you solved this? I'm having the same issue.
