### ISSUE TITLE
chroot setup on USB drive.. /prepare.sh: Permission denied

### ISSUE THREAD

**Issue by quantumalchemy** [dnschneid/crouton#4077]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: stretch
encrypted: no
Entering /media/removable/V8/chroots/stretch...
crouton: version unknown
release: unknown
architecture: unknown
targets: xiwi
/usr/local/bin/croutonversion: 1: /usr/local/bin/croutonversion: awk: not found
Unmounting /media/removable/V8/chroots/stretch...


```

#### Please describe your issue:

sudo crouton -r stretch -t xiwi,xfce -p '/media/removable/sdx'

>>

getting.. " chroot: failed to run command '/prepare.sh': Permission denied"

>>

Installing unmount-chroot into the host...

Installing crash_reporter_wrapper into the host...

chroot: failed to run command '/prepare.sh': Permission denied

Failed to complete chroot setup.

Unmounting /media/removable/sdx/chroots/stretch...
<<
running on a brand new asus c434 chromebook

on.. latest on stable devel chromeos

I reformatted usb stick again ext4 chmod to 077

Anyway to fix?

Thanks!
#### If known, describe the steps to reproduce the issue:
On setup of a crouton  chroot to a usb drive

**Comment by quantumalchemy** [comment]
ok ended up just moving the chroot to the usb drive
ie:  edit-chroot stretch -m /media/removable/usb1
working ok.. But will leave this issue open .. as it would be good if 
you can setup chroots on an external device

**Comment by DennisLfromGA** [comment]
@quantumalchemy,

Glad you found a workaround.

There were [some issues](https://github.com/dnschneid/crouton/issues/3695#issuecomment-376661094) with symlinks & permissions but they were addressed in an earlier version.
We'll keep this open for a bit and see if anyone else runs into it.

*Thanx*,
-**DennisLfromGA**

**Comment by quantumalchemy** [comment]
Update I added the edit-chroot -all info..
 awk: not found
.. Im guessing awk is not  listed in path .. strange  
chrome os thing ?

**Comment by DennisLfromGA** [comment]
@quantumalchemy,

Check your $PATH, I'll bet it's contributing to the '** awk: not found' error.

*Hope this helps,*
-**DennisLfromGA**
