### ISSUE TITLE
Help with "Ubuntu Mate on a Chromebook with Crouton"

### ISSUE THREAD

**Issue by Oxika95** [dnschneid/crouton#4079]
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20190403182822~master:174af0eb
release: trusty
architecture: armhf
xmethod: xorg
targets: xfce
host: version 12105.47.0 (Official Build) beta-channel peach_pit 
kernel: Linux localhost 3.8.11 #1 SMP Thu May 23 01:19:46 PDT 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```

**Comment by DennisLfromGA** [comment]
@Oxika95,

Show us what your '`startmate`' script looks like, both inside and outside the chroot.

-**DennisLfromGA**

**Comment by Oxika95** [comment]
Yes it is that script, ill give that a shot now. Thanks for the quick reply

**Comment by Oxika95** [comment]
I gave that a shot, opening up the file from the described documentation listed above I switched the last line of the text so now the file reads...
`#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

APPLICATION="${0##*/}"

USAGE="$APPLICATION [options]
Wraps enter-chroot to start an Xfce session.
By default, it will log into the primary user on the first chroot found.
Options are directly passed to enter-chroot; run enter-chroot to list them."

exec sh -e "`dirname "\`readlink -f "$0"\`"`/enter-chroot" -t xfce "$@" "" \
    exec crouton-noroot xinit /usr/bin/mate-session
`
Then I reran the code below... 

`chronos@localhost / $ sudo cp ~/Downloads/startmate /usr/local/bin/startmate
chronos@localhost / $ sudo chmod +x /usr/local/bin/startmate
chronos@localhost / $ sudo startmate`

but still got 

`/bin/sh: 0: Illegal option -`

**Comment by DennisLfromGA** [comment]
@Oxika95,

I should've been more clear, you only *need* the last line, kinda like the '[startgnome](https://github.com/dnschneid/crouton/blob/master/chroot-bin/startgnome)' script:
```
#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Launches GNOME; automatically falls back to gnome-panel

exec crouton-noroot gnome-session-wrapper gnome
```
Only your `startmate` script would be:
```
#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Launches MATE

exec crouton-noroot xinit /usr/bin/mate-session
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by Oxika95** [comment]
Sorry for my misunderstanding, I'm really a bull in a china closet with all this very out of my element. So once again I edited the startmate file so this time it reads only the line below...

`exec crouton-noroot xinit /usr/bin/mate-session`

Then I reran the code below...

>chronos@localhost / $ sudo cp ~/Downloads/startmate /usr/local/bin/startmate 
chronos@localhost / $ sudo chmod +x /usr/local/bin/startmate
chronos@localhost / $ sudo startmate

yet again I get...

/bin/sh: 0: Illegal option -

I'm sorry if I have misunderstood again. for the heck of it, I tried this...

>chronos@localhost / $ sudo exec crouton-noroot xinit /usr/bin/mate-session
sudo: exec: command not found

**Comment by DennisLfromGA** [comment]
@Oxika95,

No problem, I can't figure it out either.

I would have thought it would run in `/usr/local/bin` with the proper permissions.
Try this and see if it launches: `sudo crouton-noroot xinit /usr/bin/mate-session`

If that works then it may be some kind of permissions issue.
You could try to *install* your start script like you now do for `crouton` with this:

- `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/startmate`

And see if that does any better.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Oxika95** [comment]
Unfortunately, that hasn't seemed to work either but I appreciate your help! Do you know if mate will ever be officially supported?

**Comment by DennisLfromGA** [comment]
@Oxika95,

> Unfortunately, that hasn't seemed to work either but I appreciate your help!

Sorry to hear that, maybe the *real* devs will see this and offer some help.

> Do you know if mate will ever be officially supported?

There were some earlier efforts but it seems they've been abandoned -
https://github.com/dnschneid/crouton/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+mate

I doubt if the devs will add the mate target, it takes a lot of work making sure it works on all supported distros & devices but you never know.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Oxika95** [comment]
I really appreciate all your help thank you!

**Comment by ctsao95** [comment]
The startmate script provided by the guide appears to have carriage returns, which probably confused the shell.  If you open the script in vi using the command sudo vi ~/Downloads/startmate, the file contains a series of ^M characters (representing the carriage returns) before every new line.  Delete these characters in vi, then save the changes.  Afterwards, install the revised script using sudo install -Dt /usr/local/bin -m 755 ~/Downloads/startmate.

**Comment by BlockHackTk** [comment]
Bonjour, 
another solution is to install only core:

`sudo crouton -n xenial -t core,keyboard,audio,extension,x11,gtk-extra,` 

Then connect `sudo enter-chroot` and install mate

`sudo apt install mate-desktop-environment-extra` 
or I'd like some help on this subject to know exactly which packages to install for mate

Modify and add in the file

> ~/.xinitrc

> exec mate-session  

`sudo nano ~/.xinitrc ` 

You can now launch `xinitrc`

don't hesitate to contribute or correct me but this solution works for me on an Asus C301

**Comment by mjonsson1986** [comment]
how to get this script working?
exec crouton-noroot xinit /usr/bin/mate-session
seems the commands never  being sent to the chroot? and the exec command are not included in chromeos (if it is a command)

**Comment by qaqak** [comment]
> Do you know if mate will ever be officially supported?
Can't `mate`be installed as a DE?
