### ISSUE TITLE
xiwi can't connect; crouton integration extension corrupts every time

### ISSUE THREAD

**Issue by kayshcache** [dnschneid/crouton#4085]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20190403182822~master:174af0eb
release: buster
architecture: amd64
xmethod: xorg
targets: x11,xorg,xiwi,core,keyboard,cli-extra,extension,audio
host: version 12239.19.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-19677-g1a6476d7970e #1 SMP PREEMPT Fri Jun 21 00:39:20 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,chrome,xorg,gnome-desktop,xiwi,touch,cli-extra,extension
host: version 12239.19.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-19677-g1a6476d7970e #1 SMP PREEMPT Fri Jun 21 00:39:20 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
I run xiwi (as per usual) but today since ChromeOS update to Version 76.0.3809.38 (Official Build) beta (64-bit): Crouton integration extension disables and states; "This extension may have been corrupted." on the chrome://extensions/ page. I click repair, does it again, I repair and reboot, it does it again. I updated crouton, and the chroot, no change. Crouton xiwi is now broken for me. Please help, workflow is severely disrupted at critical time.

See shell output:

```
XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-128-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-19677-g1a6476d7970e #1 SMP PREEMPT Fri Jun 21 00:39:20 PDT 2019 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3686400 verity payload=PARTUUID=14e4a785-f535-734d-a93e-1f00f0a68872/PARTNROFF=1 hashtree=PARTUUID=14e4a785-f535-734d-a93e-1f00f0a68872/PARTNROFF=1 hashstart=3686400 alg=sha1 root_hexdigest=623d842c62fe23b02b2d6a46dd5417995be783e1 salt=c92e1843afee3af5874dffff863db9e91469aceec48baf64a4da8e9452b2880b" noinitrd vt.global_cursor_default=0 kern_guid=14e4a785-f535-734d-a93e-1f00f0a68872 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7  
Build Date: 10 August 2018  09:33:05AM
xorg-server 2:1.18.4-0ubuntu0.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Jun 29 03:01:59 2019
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,chrome,xorg,gnome-desktop,xiwi,touch,cli-extra,extension
host: version 12239.19.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-19677-g1a6476d7970e #1 SMP PREEMPT Fri Jun 21 00:39:20 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
>                   Ignoring extra symbols
Errors from xkbcomp are not fatal to the X server
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Cannot open /sys/class/tty/tty0/active: No such file or directory
Connected to extension, launched crouton in a window.
Terminated
Running exit commands...
/usr/bin/xinit: connection to X server lost
The xiwi window that opens gives this error:
ERROR: Connection failed (code: -2).
```

#### If known, describe the steps to reproduce the issue:
Unknown. Update to latest Beta channel Chome OS version on Friday 28th of June with an Asus c302 and run xiwi with VS Code as with command: `sudo startxiwi code` or enter the cli first and use `xiwi code` or `xiwi -T code`

**Comment by DennisLfromGA** [comment]
Closing and duping to:

- The extension corrupted after last update dev chanel(ASUS C302) #4078
