### ISSUE TITLE
Releases link returning old file, several commits behind

### ISSUE THREAD

**Issue by NPastorale** [dnschneid/crouton#4090]
#### Please describe your issue:
When the Crouton script downloads the [crouton file](https://github.com/dnschneid/crouton/raw/releases/crouton) it gets an outdated one (VERSION='1-20190403182822~master:174af0eb') that does not include the latest commits (specifically the one I am looking for is **dfaa797** which replaces 'dconf-tools' with 'dconf-cli' in the gnome target

#### If known, describe the steps to reproduce the issue:
`sudo crouton -r buster -t core,gnome,audio,extension,keyboard`
That will do the trick

AFAIK in order to fix this, the releases branch needs to be updated

Thanks!!

**Comment by dnschneid** [comment]
Argh, thank you for calling this out.  Looks like I ran the release testing but never followed up on the results.

I've updated the release branch.

**Comment by NPastorale** [comment]
Thank you David!!!
