### ISSUE TITLE
Is there a way to verify backups?

### ISSUE THREAD

**Issue by lesatdgl** [dnschneid/crouton#4091]
```
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: xenial-xiwi
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial-xiwi...
crouton: version 1-20190403182822~master:174af0eb
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,gnome
host: version 12105.75.0 (Official Build) stable-channel guado 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jun 19 23:36:06 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial-xiwi...
name: xfce-desktop
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xfce-desktop...

#### Unable to restore from two different backups - backups go bad - but two in a row is UGLY - so  any way to verify a backup when it's done? 

chronos@localhost / $ sudo edit-chroot -f /media/removable/128Gb/xenial-20190704-1235.tar.gz -r xenial
/media/removable/128Gb/xenial-20190704-1235.tar.gz doesn't appear to be a valid tarball.
chronos@localhost / $ sudo edit-chroot -f /media/removable/128Gb/xenial-20190419-1214.tar.gz -r xenial
tar: Skipping to next header/128Gb/xenial-20190419-1214.tar.gz to /mnt/stateful_partition/crouton/chroots/xenial...
/
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

#### Did backups and then copied tarballs to usb drive - attempted to restore from that usb

**Comment by DennisLfromGA** [comment]
@lesatdgl,

*Ouch!* Sorry to hear that.

The [code](https://github.com/dnschneid/crouton/blob/master/host-bin/edit-chroot#L410) that creates the backup file is supposed to return an error if there is one so if you didn't get an error or warning when you created it I would *think* all went well.

You can list the files in your compressed archive with something like: 
- `tar -tvaf /media/removable/128Gb/xenial-20190704-1235.tar.gz `

That should show you file sizes and location of every file, if it errors with 'invalid tarball' or something similar when you invoke it then I'm afraid it may not be recoverable. However, I found this when I googled it so maybe there's still hope -
- [gzip Recovery Toolkit aka gzrecover](https://github.com/arenn/gzrt)

I usually backup to Downloads first and if all goes well copy it to external media, perhaps something went awry when it was written to your external media.

*Hope this helps,*
-**DennisLfromGA**

**Comment by lesatdgl** [comment]
Yes, that's what I do too. I guess my process needs to become backup and try to restore, before I believe the backup :-(

**Comment by DennisLfromGA** [comment]
Yup that's always a good idea and one that I should practice. :-)
