### ISSUE TITLE
noexec mount/invalid locale settings

### ISSUE THREAD

**Issue by binMonkey** [dnschneid/crouton#4092]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version git
release: sid
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12105.90.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-19346-g9ff80f5e4c97 #1 SMP PREEMPT Thu Jul 4 00:46:35 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...
name: stretch
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
```

#### Please describe your issue: update chroot -
when i try to update my chroot I get a ton of "warning: script from noexec mount;" warnings.  At the end of the update I get this warning:  "*** update-locale: Error: invalid locale settings:  LANG=en_US.UTF-8
Failed to complete chroot setup." plus some more noexec mount warnings.

When I enter-chroot, I get this notice:  "A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] "  I answer yes and get this notice:  
    "*** update-locale: Error: invalid locale settings:  LANG=en_US.UTF-8
    Failed to complete chroot setup.
    The chroot setup script may be broken. Your chroot is not fully configured.
    Removing the chroot setup script. You may want to update your chroot again."

This started yesterday after I updated my ChromeOS.  I always update my chroot when that updates.

I'm using an Acer 14, CB3-431 with 4GB/32GB.

***this is only happening on my Stretch chroot.  I just built the Sid one as a test and it seems ok.

***I spoke too soon.  Sid built fine, but has the same problems updating the chroot.

**Comment by mrredstone11** [comment]
to fix the noexec error type this before updating `sudo mount -o remount,exec /tmp` and it should work

**Comment by binMonkey** [comment]
Sorry, guys.  I'm kind of an idiot.  I read through the installation instructions for the umpteenth time and found my mistake.  I was still running "sudo sh crouton" instead of "sudo crouton".

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
