### ISSUE TITLE
/etc/rc.local is not being run on startup

### ISSUE THREAD

**Issue by MetaNite64** [dnschneid/crouton#4094]
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190403182822~master:174af0eb
release: bionic
architecture: amd64
targets: cli-extra
host: version 12105.90.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-19346-g9ff80f5e4c97 #1 SMP PREEMPT Wed Jul 3 23:42:28 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.
```
*Note- I have it running in the background, so that is why it is not unmounting.

#### Please describe your issue:
I am trying to run sshd on startup so I don't have to manually every time I log out and back in. The current content of my /etc/rc.local is:
```
/sbin/iptables -P INPUT ACCEPT

mkdir -p -m0755 /var/run/sshd
/etc/init.d/ssh start
```
I know that it is not being run at all because in /var/run, there is no sshd directory. I can still manually start it, so it is not an issue with openssh.

#### If known, describe the steps to reproduce the issue:
1.) Install a bionic chroot with the target cli-extra.
2.) Install openssh-server.
3.) Copy the above code into /etc/rc.local.
4.) Log out and log back in, then run `sudo service --status-all`. It should show a minus sign next to ssh.

**Comment by DennisLfromGA** [comment]
@Mario253,

It may be a 'systemd' glitch, see this or similar articles -
- [Ubuntu 18.04: /etc/rc.local does not exist anymore - does it still work?](https://www.claudiokuenzler.com/blog/783/ubuntu-18.04-rc.local-file-not-exist-launch-with-systemd-rc-local)

*Hope this helps,*
-**DennisLfromGA**

**Comment by Mario253** [comment]
After reading that article and doing some more research, it appears that this issue will not be fixed until PID namespace functionality is added to crouton. As a side note, I would like to know if any progress is being made on that, because the pull request at #2474 is roughly 3 years old now, and there is only one file left to be changed.

**Comment by erenoglu** [comment]
Yes this is a show stopper for me as well as I'd need some services to be launched automatically (proxy server, etc.)
