### ISSUE TITLE
chroot install  -  sed: can't read tests/cras_test_client

### ISSUE THREAD

**Issue by niveknosredneh** [dnschneid/crouton#4098]
```
chronos@localhost ~/Downloads $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20190710132432~master:7e345389
release: xenial
architecture: amd64
targets: xfce
host: version 12345.0.0 (Official Build) dev-channel cave 
kernel: Linux localhost 3.18.0-19718-g3647ead2beb2 #1 SMP PREEMPT Sun Jul 14 21:59:29 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

Trying to install a fresh chroot.  

sudo ~/Downloads/crouton -t xfce

```
...
The following packages were automatically installed and are no longer required:
  libasound2-dev:i386 libc6-dev:i386 libglib2.0-0 libspeex-dev:i386 libspeex1:i386 libspeexdsp-dev:i386 linux-libc-dev:i386 pkg-config
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sed: can't read tests/cras_test_client.c: No such file or directory
Failed to complete chroot setup.
sh: 0: /tmp/crouton.GLr/host-bin/unmount-chroot: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/tmp/crouton.GLr/host-bin/unmount-chroot: 42: .: /tmp/crouton.GLr/host-bin/../installer/functions: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

also fails after sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
and running crouton instead of ~/Downloads/crouton

**Comment by TopRamenModernShaman** [comment]
Bump, I have been battling this exact same issue.

I also notice you have the noexec mount issue. That could be fixed by typing 'mount -o remount,exec /tmp
' that essentially sets that directory to allow executables. New chrome update tried to secure those directories and made them by default nonexecutable

**Comment by alphawave7** [comment]
/sorry, posted this in another issue when it belonged here

Also experiencing hung install with unmount..example:

 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sed: can't read tests/cras_test_client.c: No such file or directory
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

**Comment by rjwboys1** [comment]
sudo edit-chroot -all
name: xenial
encrypted: no
Entering /media/removable/Linux/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20190710132432~master:7e345389
release: xenial
architecture: amd64
targets: unity
host: version 12345.0.0 (Official Build) dev-channel lulu 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Sun Jul 14 22:03:14 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/Linux/chroots/xenial...

**Comment by tjbergst** [comment]
I the same issue as the OP. I applied the noexec mount issue fix from @TopRamenModernShaman and it was able to successfully create the chroot.

**Comment by rjwboys1** [comment]
> I the same issue as the OP. I applied the noexec mount issue fix from @TopRamenModernShaman and it was able to successfully create the chroot.

i have done that and only got rid of the noexec messages but still can't create chroot

**Comment by Dupplicate** [comment]
Also have these issues. Was able to remount /tmp in exec mode, but missing cras_test_client stops installation anyway.

**Comment by rjwboys1** [comment]
i have even tried deleteing chroot and rebooting

**Comment by mrredstone11** [comment]
ive been getting the cras test error too

**Comment by slimsh0tty** [comment]
Same issue: 

chronos@localhost ~ $ sudo edit-chroot -all
Password: 
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190710132432~master:7e345389
release: xenial
architecture: amd64
targets: xfce
host: version 12345.0.0 (Official Build) dev-channel nocturne 
kernel: Linux localhost 4.4.185-16695-gfba3f42d7c64 #1 SMP PREEMPT Sun Jul 14 21:40:04 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost ~ $ 

Can anyone confirm that this is also broken for the stable channel?  This maybe a DEV channel issue.

**Comment by TopRamenModernShaman** [comment]
Yeah the noexec just gets rid of a few errors. I keep getting "Warning: unable to register core dump handler" aswell as the test/cras errors. I have not tried this out of dev channel, I havent been home to do so. Can anyone try this on the standard boot?

**Comment by Dupplicate** [comment]
I tried wiping the chromebook (out and back into devmode). Problem persists.
Can it be that using an alternative chroot root is a problem? Mine is on an (ext4) SD card.

**Comment by TopRamenModernShaman** [comment]
Ive gone to far down the rabbit hole on this one. I can't switch to a stable channel, everytime I try to and power wash. It will reboot back into dev channel

**Comment by TopRamenModernShaman** [comment]
GOOD NEWS!!!! I GOT IT!!

So based on @slimsh0tty the channel is part of the issue. So here's my break down for everyone.

-Power washed my chromebook;
-Put chromebook into Dev-mode;
-Logged in and went to settings -> About Chrome OS -> Detailed Build Info -> Change channel to Stable;

Now that we're back into a Dev-mode and stable channel chromebook we can almost start the crouton installation, but we need to do a few things.


-First we need to 'sudo mkdir /usr/local/bin' if that directory isnt already there;
-Secondly I had to do this to create a directory within chroot that I didnt have ''/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/var''  (replace xenial with what ever target you choose for the crouton flavor);
-Thirdly you have to run the "sudo mount -o remount,exec /tmp" ;(Note on that one, chromeOS had a new update that essentially for security wont let you run executables from just any directory, so you had to flip the NOEXEC flag on /tmp to executable);


From there you should be good to go! Hope this helps @niveknosredneh

**Comment by rjwboys1** [comment]
will try later

**Comment by slimsh0tty** [comment]
Thanks to @TopRamenModernShaman, I now have a working chroot on my Pixel Slate.  Going back to stable and powerwashing after was the key.

**Comment by Dupplicate** [comment]
Can confirm for Acer Chromebook R11.
After switching to stable channel + devmode error no longer occurs.

**Comment by boywondr16** [comment]
@TopRamenModernShaman - Step 2 - the creation of the "var" directory--and I'm limited in my knowledge, so bear with me--where do I input that? I can get enter-chroot to allow me into anything without unmounting because of that stupid UID 1000 error.

**Comment by Civon** [comment]
> GOOD NEWS!!!! I GOT IT!!
> 
> So based on @slimsh0tty the channel is part of the issue. So here's my break down for everyone.
> 
> -Power washed my chromebook;
> -Put chromebook into Dev-mode;
> -Logged in and went to settings -> About Chrome OS -> Detailed Build Info -> Change channel to Stable;
> 
> Now that we're back into a Dev-mode and stable channel chromebook we can almost start the crouton installation, but we need to do a few things.
> 
> -First we need to 'sudo mkdir /usr/local/bin' if that directory isnt already there;
> -Secondly I had to do this to create a directory within chroot that I didnt have ''/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/var'' (replace xenial with what ever target you choose for the crouton flavor);
> -Thirdly you have to run the "sudo mount -o remount,exec /tmp" ;(Note on that one, chromeOS had a new update that essentially for security wont let you run executables from just any directory, so you had to flip the NOEXEC flag on /tmp to executable);
> 
> From there you should be good to go! Hope this helps @niveknosredneh

that works! help a lot.
my symptom is always stop at compiling CRAS(i386).
[here is my gist note](https://gist.github.com/Civon/af7ab1820d8a05336c412854e147609c)

**Comment by nethershaw** [comment]
Fantastic. In 2024, this _still happens,_ and the only Google results _still lead here._

Thank you to @TopRamenModernShaman for not describing the process that led to discovering the three "do a few things" suggested here, since none of them in any combination any longer have an effect, and there is no way to tell why you suggested any of them.

Thank you to @dnschneid for referencing but not actually addressing this issue, leaving it as a rabbit hole for posterity to fall into.

Any of you could have described what `cras_test_client.c` is, where it comes from, why it's being compiled from source here to an object file, what that object file does, why that object file is necessary, and -- most crucially -- why it doesn't end up where it is supposed to. But guess what? _There's a secret!_ The answers to this and other questions are evidently buried in _discussion threads,_ leaving no one any confidence as to their authority.

Thank you to @CroutonIsFun for _those_ squirrel caches.

Abandon all hope, ye who enter here.

**Comment by dnschneid** [comment]
> Thank you to @dnschneid for referencing but not actually addressing this issue, leaving it as a rabbit hole for posterity to fall into.

You're welcome!  Looking forward to reading your wiki entry documenting everything you've learned.

**Comment by jlarrieux** [comment]
If you don't mind having No Audio, you can install the silence version using `sudo CROUTON_BRANCH=silence crouton -r xenial -t xfce` (replace xenial, with your prefered Ubuntu version, I did focal,... replace xfce with your preferred desktop environment). 

Here [where I got](https://github.com/dnschneid/crouton/discussions/4968) the idea from.
Here is [the actual article](https://github.com/dnschneid/crouton/discussions/4967) explaining it (also referenced in the link above)
