### ISSUE TITLE
warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by aidylewis** [dnschneid/crouton#4100]
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

#### Please describe your issue:
Installing Linuxbrew, because my version of tmux is showing `qqqqqqq` as a pane division. I am based in the U.K. and using Debian **buster**.

**Comment by aidylewis** [comment]
To fix the ```qqqqq``` in tmux the pane, include in .tmux.conf

# https://code.i-harness.com/en/q/8173d6
set-option -ga terminal-overrides ',*:enacs@:smacs@:rmacs@:acsc@

I remember with Crostini I couldn't set the locale from en_US.UTF-8 with **dpkg-reconfigure**. There doesn't seem to be a **dpkg-reconfigure** package, so I guess I am stuck with it.

**Comment by DennisLfromGA** [comment]
@aidylewis,

Very nice find, thanx for digging.

-**DennisLfromGA**

**Comment by MrLbird** [comment]
woah
