### ISSUE TITLE
Upgrade to 18.04 was successful.

### ISSUE THREAD

**Issue by mattzab** [dnschneid/crouton#4104]
#### Please describe your issue:
Upgrading from 16.04 to 18.04 was a huge success.

#### If known, describe the steps to reproduce the issue:
`sudo apt install ubuntu-release-upgrader-core`
`sudo do-release-upgrade -d`

During the installation, it asked if I want to add and remove packages and all that, I said Y. Then it said that it found files that are different from debian default, such as hwaudio. "Do you want to replace? It is strongly recommended to do so!" I chose N for all of those prompts- I figured that crouton did the modifying for certain hardware junk and what not, so I don't want debian default to override those.

Install couldn't have been any smoother.
Though I use GUI applications _on occasion,_ I usually stick with CLI. Technically, I use GUI for that too, as I prefer to get into my chroot in a window by using `sudo startxiwi -F lxterminal` so I'm running i3 window manager, at least as reported by neofetch.

Cheers!

**Comment by DennisLfromGA** [comment]
@mattzab,

Thanx for the steps and the successful report.
Hopefully it'll give others enough confidence to try it if they are so inclined.

One suggestion tho for those that want to try this: *Please backup your chroot(s) first*.

-**DennisLfromGA**

-Closing-
