### ISSUE TITLE
"Failed to run deboot strap"

### ISSUE THREAD

**Issue by Footsiefat** [dnschneid/crouton#4106]
Log follows:

chronos@localhost / $ sudo crouton -t xfce
Downloading latest crouton installer...

################################################################################################################################################ 100.0%################################################################################################################################################ 100.0%

/tmp/crouton-installer-cache/crouton: 93: .: /tmp/crouton.WIF/installer/main.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

/tmp/crouton-installer-cache/crouton: 113: .: /tmp/crouton.WIF/installer/functions: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

/tmp/crouton-installer-cache/crouton: 290: .: /tmp/crouton.WIF/installer/ubuntu/defaults: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

/tmp/crouton-installer-cache/crouton: 319: .: /tmp/crouton.WIF/targets/xfce: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

/tmp/crouton-installer-cache/crouton: 9: .: /tmp/crouton.WIF/targets/common: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

/bin/sh: 0: /tmp/crouton.WIF/host-bin/mount-chroot: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

/tmp/crouton.WIF/host-bin/mount-chroot: 33: .: /tmp/crouton.WIF/host-bin/../installer/functions: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.

If this is a surprise to you, you should do a full system recovery via USB.

Installing xenial-amd64 chroot to /usr/local/chroots/xenial

/tmp/crouton-installer-cache/crouton: 630: .: /tmp/crouton.WIF/installer/ubuntu/bootstrap: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

Downloading bootstrap files...

W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg

I: Retrieving InRelease

I: Retrieving Packages

I: Validating Packages

I: Resolving dependencies of required packages...

I: Resolving dependencies of base packages...

I: Checking component main on http://archive.ubuntu.com/ubuntu
...

...

I: Retrieving linux-base 4.0ubuntu1

I: Validating linux-base 4.0ubuntu1

I: Retrieving locales 2.23-0ubuntu3

W: Retrying failed download of http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/locales_2.23-0ubuntu3_all.deb

I: Retrieving locales 2.23-0ubuntu3

W: Retrying failed download of http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/locales_2.23-0ubuntu3_all.deb

I: Retrieving locales 2.23-0ubuntu3

I: Validating locales 2.23-0ubuntu3

I: Retrieving login 1:4.2-3.1ubuntu5

I: Validating login 1:4.2-3.1ubuntu5

...

I: Retrieving systemd 229-4ubuntu4

W: Retrying failed download of http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_229-4ubuntu4_amd64.deb

I: Retrieving systemd 229-4ubuntu4

W: Retrying failed download of http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_229-4ubuntu4_amd64.deb

I: Retrieving systemd 229-4ubuntu4

W: Retrying failed download of http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_229-4ubuntu4_amd64.deb

W: http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_229-4ubuntu4_amd64.deb
 was corrupt

W: Couldn't download package systemd (ver 229-4ubuntu4 arch amd64) at http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_229-4ubuntu4_amd64.deb

I: Retrieving systemd-sysv 229-4ubuntu4

I: Validating systemd-sysv 229-4ubuntu4

...

I: Retrieving zlib1g 1:1.2.8.dfsg-2ubuntu4

I: Validating zlib1g 1:1.2.8.dfsg-2ubuntu4

E: Couldn't download packages: systemd

debootstrap error log:

% Total % Received % Xferd Average Speed Time Time Time Current

Dload Upload Total Spent Left Speed

100 51328 100 51328 0 0 36979 0 0:00:01 0:00:01 --:--:-- 37167

Failed to run debootstrap.

**Comment by petermmiller** [comment]
The http://archive.ubuntu.com/ubuntu mirror is currently (August 2019) failing for the `systemd` and `locales` packages.

Work-around:  use the **-m** option to specify a different mirror, e.g. from:  https://launchpad.net/ubuntu/+archivemirrors

**Comment by DennisLfromGA** [comment]
For a workaround see: https://github.com/dnschneid/crouton/issues/4106#issuecomment-526027391
