### ISSUE TITLE
How do I fully remove crouton? (want to make fresh install)

### ISSUE THREAD

**Issue by SnippitCoder** [dnschneid/crouton#4109]
Hey everybody i was just wondering how i could fully remove crouton because i just want a fresh install, anybody know how there are no tutorials i could find on how to

**Comment by DennisLfromGA** [comment]
@SnippitCoder,

The README mentions it under the paragraph heading -
- [Help! I've created a monster that must be slain!](https://github.com/dnschneid/crouton#help-ive-created-a-monster-that-must-be-slain)

But there probably aren't many tutorials to be found since it's just a one line command -

- `sudo delete-chroot [chrootname]`

`delete-chroot` is just a link to `edit-chroot` which has many other options unrelated to deleting a chroot but I'll list them below for completeness -
```
delete-chroot [options] name [...]

Edits a chroot.

Options:
    -a          Operates on all chroots in /mnt/stateful_partition/crouton/chroots.
                If no other operation is specified, prints out the names of the chroots.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -b          Backs up the chroot to a tarball. Compression format is chosen
                based on the tarball extension. Backups always take place before
                other actions on a given chroot.
    -d          Deletes the chroot. Assumed if run as delete-chroot.
    -e          If the chroot is not encrypted, encrypt it.
                If it is encrypted, change the encryption passphrase.
    -f TARBALL  When used with -b, overrides the default tarball to back up to.
                If unspecified, assumes NAME-yyyymmdd-hhmm.tar[.gz], where .gz
                is included for unencrypted chroots, and not for encrypted ones.
                When used with -r, specifies the tarball to restore from.
                If TARBALL is a directory, automatic naming is still used.
                If multiple chroots are specified, TARBALL must be a directory.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or left in place on existing chroots.
                If specified, keyfile will be moved. Specify a dash - as the
                KEYFILE to move the key back into the chroot.
                If multiple chroots are specified, KEYFILE must either be -
                or a directory.
    -l          Prints out croutonversion details on the chroot, if available.
                Specify twice to prompt and unlock encrypted chroots as necessary.
    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.
    -C DEST     Like -m, but copies instead of moves.
    -r          Restores a chroot from a tarball. The tarball path can be
                specified with -f or detected from name. If both are specified,
                restores to that name instead of the one in the tarball.
                Will not overwrite a chroot when restoring unless -r is
                specified twice.
    -s SPLIT    Force a backup archive to be split into SPLIT-sized chunks.
                SPLIT is specified in megabytes (1048576 bytes), and cannot be
                smaller than 10.
                FAT32 filesystems are split by default to fit within 4GB.
    -y          Do all actions without confirmation.
```

You can delete more than one chroot by entering multiple chrootnames on the command line *or* you can delete all of them at once with the `-a` option as follows -
- `sudo delete-chroot -a`

There are other ways to delete your chroot(s) using Linux commands but the above is probably the easiest and best way to do it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by divx118** [comment]
`sudo rm /usr/local/bin/crouton` or you could also do a powerwash go to Settings -> about Chrome OS -> Powerwash for added security.

With the first command there could be some leftover files crouton uses in /usr/local/bin
Just list the files in there with `ls -al /usr/local/bin` post the output here and some of us can tell you if they are safe to delete.

The second option I mentioned using the chrome os interface erases everything you added and will leave developer mode, so your chromebook is stock again.

**Comment by DennisLfromGA** [comment]
Showing comments from related issue now closed -
> Ok, so I made an issue just like this yesterday and i got a response that seemed super helpful but im sure what it ment. I want to delete crouton, not a chroot. I'm brand new to this so I have no idea if crouton itself is a chroot or not. I have turned off developer mode and back on to see if I could erase it that way but it still works. I'm just wondering how to delete it to the point where the 'shell' command wont work at all. I just want crouton to basically delete itself.

Deleting crouton chroots essentially deletes crouton, there are a few files in `/usr/local/bin` (by default) that you could remove too if you like, for example:

`crash_reporter_wrapper cros_funcs crouton delete-chroot edit-chroot enter-chroot mount-chroot startcli startxfce4 startxiwi`, etc.

*Hope this helps,*
-**DennisLfromGA**

**Comment by SnippitCoder** [comment]
Thank you, I think I got the right command and it seemed to work! I'll close this issue now :)

**Comment by DennisLfromGA** [comment]
**FYI**: A powerwash will erase all users and user data (on the stateful partition) but will *not* leave Developer mode, in fact, even a full recovery will not leave Developer mode.

*Hope this helps,*
-**DennisLfromGA**

**Comment by divx118** [comment]
@DennisLfromGA for me after a powerwash or a full recovery I always had to reenable developer mode, maybe it changed now.

**Comment by DennisLfromGA** [comment]
@divx118,

Maybe it has changed over the years, it's *very* possible.

I seldom do either since I have so much custom stuff on my devices but, from what I've seen and heard of late, is that you have to leave Developer mode intentionally by pressing <kbd>space</kbd> followed by <kbd>enter</kbd> at the 'scary boot screen'.

-**DennisLfromGA**
