### ISSUE TITLE
Installing eoan or disco fails instantly

### ISSUE THREAD

**Issue by Mario253** [dnschneid/crouton#4110]
```
N/A
```

#### Please describe your issue:
When installing a chroot of Eoan Ermine or Disco Dingo (I assume with any and all targets), it gives the warning about being unsupported, and then moves on... to immediately give the error `sed: couldn't edit /tmp/crouton.6Zl/scripts/eoan: not a regular file`, where the 6Zl is a random 3 character alphanumeric set and eoan can be replaced with disco.

#### If known, describe the steps to reproduce the issue:
1.) Install crouton
2.) Run `sudo crouton -r eoan -t (any target)` OR `sudo crouton -r disco -t (any target)`.

**Comment by DennisLfromGA** [comment]
@Mario253,

I'm was able to repo the eoan issue, I'm sure that dingo will do the same thing you ran into.

I captured a diagnostic output here: [eoan.install.out.txt](https://pastebin.com/cegkYatZ)

The `sed` command throwing the error is here: 
```
+ sed -e s/ apt-transport-https / / -i /tmp/crouton.3jG/scripts/eoan
sed: couldn't edit /tmp/crouton.3jG/scripts/eoan: not a regular file
```
I'm not sure what's going on with `.../scripts/eoan` file, I'll try to play with it some more if I get a chance.

-**DennisLfromGA**
