### ISSUE TITLE
Fully deleting crouton

### ISSUE THREAD

**Issue by SnippitCoder** [dnschneid/crouton#4111]
Ok, so I made an issue just like this yesterday and i got a response that seemed super helpful but im sure what it ment. I want to delete crouton, not a chroot. I'm brand new to this so I have no idea if crouton itself is a chroot or not. I have turned off developer mode and back on to see if I could erase it that way but it still works. I'm just wondering how to delete it to the point where the 'shell' command wont work at all. I just want crouton to basically delete itself.

**Comment by DennisLfromGA** [comment]
***Please*** don't open another issue about this.
You can comment and track this on your original issue -
- How do I fully remove crouton? (want to make fresh install) #4109

I re-opened it - for now.

-**DennisLfromGA**
