### ISSUE TITLE
Failing at Installing Linux

### ISSUE THREAD

**Issue by Authora1604** [dnschneid/crouton#4116]
When I input `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton ` I got `install: cannot stat '/home/chronos/user/Downloads/crouton': No such file or directory` I know I have crouton installed 
![Screenshot 2019-08-06 at 5 27 21 PM](https://user-images.githubusercontent.com/53842437/62585879-d96a1700-b86f-11e9-96b7-40400894fc28.png)
 and I have a screenshot of the console 
![Screenshot 2019-08-06 at 5 29 17 PM](https://user-images.githubusercontent.com/53842437/62585890-ec7ce700-b86f-11e9-8fa2-2b58957384e7.png)
I really just want to install steam, please help

**Comment by DennisLfromGA** [comment]
From the image above it looks like your missing the `crouton` installer script in ~/Downloads.
The [README](https://github.com/dnschneid/crouton#usage) shows you the steps but I'll give you the basics below too -

> If you're just here to use crouton, you can grab the latest release from https://goo.gl/fd3zc. Download it, pop open a shell (Ctrl+Alt+T, type shell and hit enter), make the installer executable with sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton, then launch it with sudo crouton to see the help text. See the "examples" section for some usage examples.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Authora1604** [comment]
Ok, I'll look and see if that works, thank you!

**Comment by Authora1604** [comment]
Whelp, downloading the extra thing worked, but now it looks like there's some other problem. `0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sed: can't read tests/cras_test_client.c: No such file or directory
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
`
![Screenshot 2019-08-07 at 12 20 42 PM](https://user-images.githubusercontent.com/53842437/62651418-d32a7800-b90d-11e9-8349-3f7911b09cbf.png)

I'm just leaving it be for now and will come back if anything changes

**Comment by DennisLfromGA** [comment]
**Good News**:
 
The Chrome OS developers changed the location of 'cras_test_client' which was causing the problems in crouton that you are running into -
- [CRAS: Move cras_test_client, router and monitor out from tests](https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1687836)

The crouton developers have just recently merged a fix for this in a recent PR -
- Fix cras_test_client location #4117

So you should be able to just update your chroot after rebooting with:
- `sudo crouton -n xenial -u`

*Hope this helps,*
-**DennisLfromGA**
