### ISSUE TITLE
Issue with kali-rolling

### ISSUE THREAD

**Issue by GioPanaro** [dnschneid/crouton#4118]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20190807171712~master:6f45f06a
release: kali-rolling
architecture: amd64
targets: x11,xorg,audio,gtk-extra,gnome
host: version 12404.0.0 (Official Build) canary-channel eve 
kernel: Linux localhost 4.4.186-16724-g284c626f060d #1 SMP PREEMPT Wed Aug 7 21:07:31 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### Please describe your issue:
Error with buffer length in strncpy when installing kali-rolling

```
common/cras_shm.c: In function 'cras_shm_info_init':
common/cras_shm.c:29:2: error: 'strncpy' specified bound 255 equals destination size [-Werror=stringop-truncation]
  strncpy(info.name, stream_name, sizeof(info.name));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### If known, describe the steps to reproduce the issue:
set up kali with the command `sudo crouton -t x11,xorg,audio,gtk-extra,gnome -r kali-rolling`

**Comment by cceckman** [comment]
Related issue in #4120 (same trace, different invocation)

Looks like an issue with dev / canary channel Chrome?

**Comment by drinkcat** [comment]
Thanks for the report, "cras" fix is here: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1759370

We can also patch the file in the mean time on the crouton side.

**Comment by corlesss** [comment]
I'm having the same issue with both updating a Debian Bullseye and installing a Debian Sid chroot.

I'm on beta channel, Version 77.0.3865.35, running on an Asus C302.

Output of `sudo edit-chroot -all`
```name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
WARNING: Unable to register core dump handler.
crouton: version 1-20190807171712~master:6f45f06a
release: sid
architecture: amd64
targets: audio,extension,x11,xorg
host: version 12371.22.0 (Official Build) beta-channel cave 
kernel: Linux localhost 3.18.0-19728-g489554e8d014 #1 SMP PREEMPT Wed Aug 14 01:04:21 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...```

Output of updating Bullseye with targets; audio,xiwi,extension,x11.
```Compiling CRAS (i386)...
common/cras_shm.c: In function 'cras_shm_info_init':
common/cras_shm.c:29:2: error: 'strncpy' specified bound 255 equals destination size [-Werror=stringop-truncation]
  strncpy(info.name, stream_name, sizeof(info.name));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/bullseye...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bullseye...```

Output of installing Debian Sid with targets; audio,extension,x11,xorg.
```Compiling CRAS (i386)...
common/cras_shm.c: In function 'cras_shm_info_init':
common/cras_shm.c:29:2: error: 'strncpy' specified bound 255 equals destination size [-Werror=stringop-truncation]
   29 |  strncpy(info.name, stream_name, sizeof(info.name));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/sid...```

**Comment by Lightsockie** [comment]
Still getting same issue as OP, after redownloading crouton and installing to ensure above patch is in
```
sudo crouton -n kali -r kali-rolling -t core,cli-extra,lxde
```
```
Compiling CRAS (i386)...
common/cras_shm.c: In function 'cras_shm_info_init':
common/cras_shm.c:29:2: error: 'strncpy' specified bound 255 equals destination size [-Werror=stringop-truncation]
   29 |  strncpy(info.name, stream_name, sizeof(info.name));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Failed to complete chroot setup.
```

**Comment by Seal-Space** [comment]
How do you patch it?

**Comment by gitrubus** [comment]
im haveing the same problem 

>In function 'wake_aud_thread',
    inlined from 'stop_aud_thread' at libcras/cras_client.c:1398:3:
libcras/cras_client.c:1382:14: error: 'rc' may be used uninitialized [-Werror=maybe-uninitialized]
 1382 |         rc = write(stream->wake_fds[1], &rc, 1);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:45:
libcras/cras_client.c: In function 'stop_aud_thread':
/usr/include/unistd.h:367:16: note: in a call to 'write' declared with attribute 'access (read_only, 2, 3)' here
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
libcras/cras_client.c:1380:13: note: 'rc' declared here
 1380 |         int rc;
      |             ^~
In function 'write_message_to_server',
    inlined from 'cras_client_set_system_mute' at libcras/cras_client.c:2582:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_system_mute':
../src/common/cras_messages.h:183:36: note: source object 'header' of size 8
  183 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_system_volume' at libcras/cras_client.c:2571:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_system_volume':
../src/common/cras_messages.h:170:36: note: source object 'header' of size 8
  170 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_user_mute' at libcras/cras_client.c:2593:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_user_mute':
../src/common/cras_messages.h:183:36: note: source object 'header' of size 8
  183 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_system_mute_locked' at libcras/cras_client.c:2604:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_system_mute_locked':
../src/common/cras_messages.h:183:36: note: source object 'header' of size 8
  183 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_system_capture_mute' at libcras/cras_client.c:2615:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_system_capture_mute':
../src/common/cras_messages.h:183:36: note: source object 'header' of size 8
  183 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_system_capture_mute_locked' at libcras/cras_client.c:2627:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_system_capture_mute_locked':
../src/common/cras_messages.h:183:36: note: source object 'header' of size 8
  183 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_node_attr' at libcras/cras_client.c:3119:9:
libcras/cras_client.c:2165:28: error: 'write' reading 24 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_node_attr':
../src/common/cras_messages.h:225:36: note: source object 'header' of size 8
  225 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_select_node' at libcras/cras_client.c:3132:9:
libcras/cras_client.c:2165:28: error: 'write' reading 20 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_select_node':
../src/common/cras_messages.h:243:36: note: source object 'header' of size 8
  243 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_add_active_node' at libcras/cras_client.c:3145:9:
libcras/cras_client.c:2165:28: error: 'write' reading 20 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_add_active_node':
../src/common/cras_messages.h:259:36: note: source object 'header' of size 8
  259 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_rm_active_node' at libcras/cras_client.c:3158:9:
libcras/cras_client.c:2165:28: error: 'write' reading 20 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_rm_active_node':
../src/common/cras_messages.h:276:36: note: source object 'header' of size 8
  276 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_node_volume' at libcras/cras_client.c:3429:9:
libcras/cras_client.c:2165:28: error: 'write' reading 24 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_node_volume':
../src/common/cras_messages.h:225:36: note: source object 'header' of size 8
  225 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_swap_node_left_right' at libcras/cras_client.c:3442:9:
libcras/cras_client.c:2165:28: error: 'write' reading 24 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_swap_node_left_right':
../src/common/cras_messages.h:225:36: note: source object 'header' of size 8
  225 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_node_capture_gain' at libcras/cras_client.c:3456:9:
libcras/cras_client.c:2165:28: error: 'write' reading 24 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_node_capture_gain':
../src/common/cras_messages.h:225:36: note: source object 'header' of size 8
  225 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_add_test_iodev' at libcras/cras_client.c:3465:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_add_test_iodev':
../src/common/cras_messages.h:368:36: note: source object 'header' of size 8
  368 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_get_hotword_models' at libcras/cras_client.c:3558:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_get_hotword_models':
../src/common/cras_messages.h:412:36: note: source object 'header' of size 8
  412 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_hotword_model' at libcras/cras_client.c:3568:9:
libcras/cras_client.c:2165:28: error: 'write' reading 28 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_hotword_model':
../src/common/cras_messages.h:427:36: note: source object 'header' of size 8
  427 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_client_set_bt_wbs_enabled' at libcras/cras_client.c:3626:9:
libcras/cras_client.c:2165:28: error: 'write' reading 12 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_bt_wbs_enabled':
../src/common/cras_messages.h:472:36: note: source object 'header' of size 8
  472 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_output_volume_changed_callback' at libcras/cras_client.c:3661:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_output_volume_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_output_mute_changed_callback' at libcras/cras_client.c:3671:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_output_mute_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_capture_gain_changed_callback' at libcras/cras_client.c:3682:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_capture_gain_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_capture_mute_changed_callback' at libcras/cras_client.c:3693:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_capture_mute_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_nodes_changed_callback' at libcras/cras_client.c:3703:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_nodes_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_active_node_changed_callback' at libcras/cras_client.c:3713:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_active_node_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_output_node_volume_changed_callback' at libcras/cras_client.c:3724:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_output_node_volume_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_node_left_right_swapped_changed_callback' at libcras/cras_client.c:3735:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_node_left_right_swapped_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_input_node_gain_changed_callback' at libcras/cras_client.c:3747:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_input_node_gain_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
In function 'write_message_to_server',
    inlined from 'cras_send_register_notification' at libcras/cras_client.c:3648:7,
    inlined from 'cras_client_set_num_active_streams_changed_callback' at libcras/cras_client.c:3758:9:
libcras/cras_client.c:2165:28: error: 'write' reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
 2165 |                 write_rc = write(client->server_fd, msg, msg->length);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libcras/cras_client.c:50:
libcras/cras_client.c: In function 'cras_client_set_num_active_streams_changed_callback':
../src/common/cras_messages.h:485:36: note: source object 'header' of size 8
  485 |         struct cras_server_message header;
      |                                    ^~~~~~
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
cc1: all warnings being treated as errors

**Comment by juntakemura** [comment]
I'm having exactly the same problem. Any update?
