### ISSUE TITLE
in CrOS v76 Xiwi window disappears upon CB wakeup

### ISSUE THREAD

**Issue by cvmiller** [dnschneid/crouton#4123]
```
Please paste the output of the following command here: sudo edit-chroot -all
$ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190807171712~master:6f45f06a
release: bionic
architecture: armhf
xmethod: xiwi
targets: xfce,extension,audio,xiwi
host: version 12239.67.0 (Official Build) stable-channel veyron_speedy 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 6 05:44:26 PDT 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.
```

#### Please describe your issue:

Long time user of Crouton. As of CrOS v76, my Xiwi window (with xfce desktop running) disappears upon wake up (lift the lid) on my Asus C201PA chromebook. 

I can get the window back by clicking on the Crouton Extension and selecting Bionic (but then it is full screen, and I have to resize the window to my preference again)

#### If known, describe the steps to reproduce the issue:
Thought this might have something to do with enabling virtual desktops in CrOS v76 chrome://flags#enable-virtual-desks, but I reverted the flag, even did a power wash, and the Xiwi window problem persists.

**Comment by toorinl** [comment]
I can confirm the problem running beta CrOS 77 on Dell 13, 7310. The window does open normally when selecting it from the extension though.

**Comment by cvmiller** [comment]
@toorinl Just to clarify for the Devs, the Crouton window does open up "normally", but disappears again when the Chromebook is put to sleep (lid closed) and woken up again.

**Comment by cvmiller** [comment]
Just upgraded to: 
Google Chrome | 76.0.3809.136 (Official Build) (32-bit)

Hoping it would solve this problem, but alas, the problem of the disappearing Xiwi window remains.

**Comment by Chris-W65** [comment]
Just wanted to chime in and thank cvmiller for opening this issue.
I'm also on an Asus C201PA chromebook, using bionic with the same targets except lxde instead of xfce.

socket_client_read_frame_header: Read error.
is the line I consistently get on re-opening the lid and noting the xiwi crouton window has disappeared.

I also updated to 
Google Chrome | 76.0.3809.136 (Official Build) (32-bit)
with the problem still remaining the same.

**Comment by sethml** [comment]
Me too.

`$ sudo edit-chroot -all
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20190807171712~master:6f45f06a
release: stretch
architecture: amd64
xmethod: xiwi
targets: audio,chrome,cli-extra,core,extension,keyboard,xiwi,xorg,xfce,e17
host: version 12239.67.1 (Official Build) stable-channel eve 
kernel: Linux localhost 4.4.180-16566-g6d3d58f89527 #1 SMP PREEMPT Thu Aug 15 14:54:08 PDT 2019 x86_64 GNU/Linux
freon: yes`

I typically have a full-screen xiwi window. If I close the lid (or chromeos goes to sleep), after I wake it up and unlock the xiwi window is gone. The shell I started it from (with `sudo startxfce4`) shows output:

`socket_client_read_frame_header: Read error.
thunar-volman: Unsupported USB device type "usb".
thunar-volman: Unsupported USB device type "btusb".
thunar-volman: Unsupported USB device type "btusb".
thunar-volman: Unsupported USB device type "usb".
thunar-volman: Unsupported USB device type "uvcvideo".
thunar-volman: Unsupported USB device type "uvcvideo".
[6001:6025:0902/155857.097317:ERROR:connection_factory_impl.cc(413)] Failed to connect to MCS endpoint with error -137`

...and is hung. The crouton Chrome extension menu shows my xiwi listed, but if I click on it nothing happens - the xiwi window doesn't reappear. After I ^C my startxcfe4 shell I get a bunch more errors:

`^C
Session terminated, terminating shell.../usr/bin/xinit: connection to X server lost
Hangup
Hangup
Running exit commands...
Hangup

(xfsettingsd:5712): libxfce4ui-WARNING **: ICE I/O Error

(xfsettingsd:5712): libxfce4ui-WARNING **: Disconnected from session manager.

waiting for X server to shut down xfwm4: Fatal IO error 2 (No such file or directory) on X server :1.0.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
(II) Server terminated successfully (0). Closing log file.`

Happy to provide more details if helpful. PixelBook running ChromeOS Version 76.0.3809.102 (Official Build) (64-bit).

**Comment by jimrothstein** [comment]
One more, same as described above.    Acer Chromebook 14, CB3-431.  

>croutonversion

crouton: version 1-20190902190258~master:9a594a66
release: bionic
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,core,cli-extra,xorg,x11
host: version 12239.92.1 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-19679-gd1d0bbedf35d #1 SMP PREEMPT Tue Sep 3 11:14:23 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Chrome version:   76.0.3809

**Comment by cvmiller** [comment]
Seeing the same issue with ChromeOS 77.0.3865.105. Crash-shell shows the following upon wake-up:
```
socket_client_read_frame_header: Read error.
```

**Comment by aquatix** [comment]
Same here, but here it also complains about a missing input device:

```
socket_client_read_frame_header: Read error.
hexdump: /dev/input/event11: No such device
```

Anything we can do to dig into this ourselves further?

**Comment by dieseltravis** [comment]
Here's my updated info from #4141 :

Chrome version: `77.0.3865.105 (Official Build) (64-bit)`

From chronos: 
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: bionic
architecture: amd64
xmethod: xiwi
targets: lxde,keyboard,xiwi,xfce
host: version 12371.75.0 (Official Build) stable-channel lars 
kernel: Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:46:18 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

From linux:
```
uname -a
Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:46:18 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by aquatix** [comment]
Do we have any idea what's causing this? I would love to dive into it, but I'm a bit at a loss where to start. How can I help?

Would love to have my crouton Linux install working again, it makes my Chromebook so much more usable and fun :)

**Comment by dieseltravis** [comment]
I was looking at this function where the error occurs: 
https://github.com/dnschneid/crouton/blob/master/src/websocket.h#L382

Would it be helpful to update the various "Read error." messages to be more specific to help nail down where this is happening?

**Comment by kapilhp** [comment]
One data point. Can confirm that the solution of the earlier comment "works". After the `xiwi` window disappears, clicking on the Crouton Extension icon in a Chrome window allows one to re-open the `xiwi` window. In most cases, this manages to re-connect with the program running in the chroot.

**Comment by jmhammond** [comment]
The problem still exists on v81 (Version 81.0.4044.127 (Official Build) (64-bit)) on Pixelbook eve. I have a debian bullseye chroot.

**Comment by satmandu** [comment]
I'm wondering if this is linked to https://github.com/dnschneid/crouton/issues/4366 insofar as this is a ChromeOS suspend related failure of app connections to an X server. Maybe there is an issue with the suspend command not sending the right signals to suspend the server, leading the server to crash?

**Comment by kapilhp** [comment]
As mentioned above, the X server does not crash. The window becomes "inaccessible" since the crouton extension icon disappears from the shelf. One *can* access the window by going to the crouton extension icon in the add-on bar in Chrome. At that point one finds that the X server is alive and kicking.

**Comment by rmorehead** [comment]
Clicking the crouton extension icon does not always work, in fact for me it only works about 25% of the time. The other 75% of the time the X server cannot be connected despite repeated attempts.

**Comment by satmandu** [comment]
Thanks for the update @kapilhp. Does Xiwi do anything special during suspend? Does it have to notify X client apps that it is suspending? The closest I'm seeing for suspending apps during sleep is the path which is used when switching VTs which freezes all gpu using processes.

**Comment by pixeldashgames** [comment]
Clicking the crouton extension rarely works for me, can confirm the problem persist even if the chromebook is set to not sleep when closing the lid

**Comment by cvmiller** [comment]
Sadly, the issue continues with v96 (beta channel). With each passing version of ChromeOS, more things break on Crouton (such as 2 finger scrolling). For now, I have migrated off of Crouton to Crostini, which works well, unless I need to run Wireshark directly on the interface.

**Comment by cvmiller** [comment]
Not sure why this is stale, since I put an entry in last month (Nov 2021). But it certainly has been broken for a long time.

But I understand closing out old issues, and I have moved to Crostini (where window remain after sleep/wake and 2 finger scrolling work)
