### ISSUE TITLE
Error with crouton setup script with kali-rolling (Failure configuring Fuse)

### ISSUE THREAD

**Issue by Cyan101** [dnschneid/crouton#4130]
#### Please describe your issue:
Trying to install Kali with `sudo crouton -r kali-rolling -t xfce` works until I get an error during all the extra package downloads.

```
Setting up fuse (2.9.9-1) ...
dpkg: error processing package fuse (--configure):
 installed fuse package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 fuse
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

Attempting to then enter-chroot on the kali asks to run the setup script which also errors out
```
chronos@localhost / $ sudo enter-chroot kali-rolling
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
WARNING: Unable to register core dump handler.
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] Y
Preparing chroot environment...
WARNING: Unable to register core dump handler.
Setting up fuse (2.9.9-1) ...
dpkg: error processing package fuse (--configure):
 installed fuse package post-installation script subprocess returned error exit status 1
Setting up libntfs-3g883 (1:2017.3.23AR.3-3) ...
Setting up libsane-common (1.0.27-3.2) ...
Processing triggers for man-db (2.8.7-3) ...
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 fuse
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

#### If known, describe the steps to reproduce the issue:
Attempt to install Kali with `sudo crouton -r kali-rolling -t xfce`
Wait for it to finish and check the terminal
Attempt to enter the chroot and run the setup script

**Comment by Cyan101** [comment]
Declining to complete the script setup results in this

```
chronos@localhost / $ sudo enter-chroot kali-rolling
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
WARNING: Unable to register core dump handler.
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] n
Skipping setup. You will be prompted again next time.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
```

**Comment by Cyan101** [comment]
Only other thing I can wrong during the install is this at the very start, failing to get a keyring
```
Installing kali-rolling-amd64 chroot to /usr/local/chroots/kali-rolling
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/kali-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://http.kali.org...```

**Comment by Cyan101** [comment]
my edit-chroot -all output
```
chronos@localhost / $ sudo edit-chroot -all
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
WARNING: Unable to register core dump handler.
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: xfce,extension,core,cli-extra
host: version 12447.0.0 (Official Build) dev-channel cave 
kernel: Linux localhost 3.18.0-19742-g7eb2b7b38f54 #1 SMP PREEMPT Fri Aug 23 01:23:31 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xorg
targets: xfce
host: version 12447.0.0 (Official Build) dev-channel cave 
kernel: Linux localhost 3.18.0-19742-g7eb2b7b38f54 #1 SMP PREEMPT Fri Aug 23 01:23:31 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

My Xenial works fine

**Comment by AllHailRNJesus** [comment]
You are not the only one, I have exaclty the same problem trying to install kali-rolling.

**Comment by Cyan101** [comment]
@AllHailRNJesus What chromebook are you running and on what channel?

**Comment by AllHailRNJesus** [comment]
@Cyan101 Chromebook acer c740 (I don't know what channel).

**Comment by AllHailRNJesus** [comment]
Just checked, I am using stable.

**Comment by GioPanaro** [comment]
Same here running eve on the canary channel

**Comment by Asternitix** [comment]
same problem happens when installing debian bullseye.

**Comment by Cyan101** [comment]
Powerwashed my C302 and still have the same issue
```
chronos@localhost / $ sudo edit-chroot -all
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20190902190258~master:9a594a66
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce,extension,core,cli-extra
host: version 12239.92.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-19679-gd1d0bbedf35d #1 SMP PREEMPT Tue Aug 27 17:02:33 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
```

**Comment by Cyan101** [comment]
According to https://superuser.com/questions/790754/errors-were-encountered-while-processing-fuse there could be an error in the post installation scripts syntax, not too sure how to check or anything though

**Comment by AllHailRNJesus** [comment]
@Cyan101 When i checked out the fuse.postinst file using vim according to the link you provided, i see that the line that they mention over at superuser (which supposedly is the solution):
`udevadm test -a -p  $(udevadm info -q path -n /dev/fuse) > /dev/null 2>&1`
is instead the following:
'udevadm test --action -p  $(udevadm info -q path -n /dev/fuse) > /dev/null 2>&1'

I'm going to try changing --action to -a and see if i can get it to work or not.

**Comment by AllHailRNJesus** [comment]
I also found this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935885

**Comment by Asternitix** [comment]
bullseye is fixed.

**Comment by Asternitix** [comment]
no idea how

**Comment by AllHailRNJesus** [comment]
@Asternitix did you see what version of fuse was installed when it was fixed? They might have fixed it by updating to a newer version of fuse in bullseye.

**Comment by AllHailRNJesus** [comment]
According to the link I posted above, the issue is supposedly fixed in the latest version of fuse 2.9.9.2
I assume we will have to wait until crouton kali-rolling is updated.

**Comment by Cyan101** [comment]
where is the kali-rolling in crouton? would happily update it and PR myself

**Comment by AllHailRNJesus** [comment]
Does anyone have any ideas for how to get/update crouton to use the latest version of fuse? I looked around in the code but I couldn't find anything that seemed useful in this regard.

**Comment by Cyan101** [comment]
Same, am wondering if it's up to Kali to update their source/apt to the
latest version or what. Not sure how to have crouton install a specific
version either

**Comment by Asternitix** [comment]
> @Asternitix did you see what version of fuse was installed when it was fixed? They might have fixed it by updating to a newer version of fuse in bullseye.

it isn't fixed, I only used the core target.

**Comment by Asternitix** [comment]
> Does anyone have any ideas for how to get/update crouton to use the latest version of fuse? I looked around in the code but I couldn't find anything that seemed useful in this regard.

there are some targets that use fuse and some that don't, those are the ones you should modify.

**Comment by Cyan101** [comment]
> > Does anyone have any ideas for how to get/update crouton to use the latest version of fuse? I looked around in the code but I couldn't find anything that seemed useful in this regard.
> 
> there are some targets that use fuse and some that don't, the targets that do should be modified.

afaik it's required for kali, not in any targets. Doing a search for fuse in this repo doesn't return much so not too sure how to set a specific version to install in the script. Surprised fuse is optional too

**Comment by Cyan101** [comment]
**Temporary Fix**
`sudo enter-chroot -u root -n kali-rolling`
http://ftp.us.debian.org/debian/pool/main/f/fuse/libfuse2_2.9.9-2_amd64.deb
http://ftp.us.debian.org/debian/pool/main/f/fuse/fuse_2.9.9-2_amd64.deb
Download these and install them with `dpkg -i`, don't download them into your downloads as they give a keyring error.
After that exit the chroot and let it unmount, then `sudo crouton -u -n kali-rolling` to update/run the setup script again.

**Comment by Asternitix** [comment]
thanks.

**Comment by Asternitix** [comment]
in debian, dpkg requires forcing, but still works.

**Comment by RomHtK** [comment]
Thanx for this **Temporary Fix**
