### ISSUE TITLE
Downloading Linux on Chromebook; cannot run command "sudo startxfce4". Please Help!

### ISSUE THREAD

**Issue by zclay1** [dnschneid/crouton#4131]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 11316.165.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Sun Mar 3 22:44:20 PST 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I am trying to do coursework for Flatiron and when trying to open my IDE inside of the webpage, I am greeted with a message that says "Google Chrome OS can't open this page". I followed this (https://www.youtube.com/watch?v=QB9puwi2qTo) video exactly to gain access to Linux hoping that would fix this issue. That all seemed to work well until the “sudo startxfce4” command when it failed and said:  

(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Sep  4 14:26:29 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1567621590.112735 sender=:1.11 -> destination=:1.56 serial=989 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1567621590.656952 sender=:1.11 -> destination=:1.58 serial=990 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

Please help!

**Comment by jcd83a** [comment]
I'm having a very simlar problem. Have you tried the common issues process from the wiki? (https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting) Also, did you follow the process from #4026 ? Nothing from either helped me unfortunately, but maybe they'd help you.

**Comment by DennisLfromGA** [comment]
@zclay1,

That's a nice simple video that's easy to understand but it doesn't go into some of the other options available like xiwi probably for good reason as it does get more complicated.

The ARM devices like your HP Chromebook 11 G1 seem to have problems with the xorg xmethod.
I would suggest adding the 'xiwi' xmethod and then try launching your xfce4 desktop.

For your chroot you can add xiwi using the *update* method with the following:
- `sudo crouton -n xenial -t xiwi -u`

As noted in the installation you'll also have to add the ['crouton integration' extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)

*Hope this helps,*
-**DennisLfromGA**
