### ISSUE TITLE
Please show or tell us what the first six lines of `chrome://version` displays so we can tell which Chrome OS & Chrome versions are you using and on what device.

### ISSUE THREAD

**Issue by MercenaryT** [dnschneid/crouton#4133]
Please show or tell us what the first six lines of `chrome://version` displays so we can tell which Chrome OS & Chrome versions are you using and on what device.

-**DennisLfromGA**

Response:
Google Chrome	77.0.3822.0 (Official Build) canary (64-bit)
Revision	e7068223d3d645f3043956372bbd7922822b7008-refs/branch-heads/3822@{#1}
Platform	12286.0.0 (Official Build) canary-channel celes
Firmware Version	Google_Celes.7287.92.164
ARC	5673510

**Comment by MercenaryT** [comment]
The original issue:
https://github.com/dnschneid/crouton/issues/4010

**Comment by DennisLfromGA** [comment]
Closing, please continue to track on https://github.com/dnschneid/crouton/issues/4010
