### ISSUE TITLE
Linux os only runs in background

### ISSUE THREAD

**Issue by Thespy799** [dnschneid/crouton#4134]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12239.92.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.120-12149-g189abc2a39ee #1 SMP PREEMPT Tue Aug 27 17:04:59 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
chronos@localhost / $ 
#### Please describe your issue:
When I  switch to the other os, it will not let me click anything and nothing loads.

**Comment by Thespy799** [comment]
Also, when I try to update the chroot, it giive me:

chronos@localhost / $ sudo crouton -n xenial -u
sudo: crouton: command not found

**Comment by DennisLfromGA** [comment]
@Thespy799,

> When I switch to the other os, 
- What *other* os, do you mean Chrome OS or your chroot's desktop?...
- How are you switching to the other os, using <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>F1/Backward</kbd> and <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>F2/Forward</kbd>?

> ... it will not let me click anything and nothing loads.

- Do you mean nothing works on your xfce desktop?
- Can you open a terminal and interact with it?

---------
> Also, when I try to update the chroot, it giive me:

>> chronos@localhost / $ sudo crouton -n xenial -u
>> sudo: crouton: command not found

It appears you haven't *installed* `crouton`, please do this first -
1. Remove any existing installer from your Downloads folder.
2. Fetch a fresh installer: https://goo.gl/fd3zc
3. Open a crosh shell (Ctrl-Alt-T, then type shell)
4. Prep the installer with: sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton

You should then be able to run the update command.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
