### ISSUE TITLE
LXQt Support?

### ISSUE THREAD

**Issue by kingliamb** [dnschneid/crouton#4136]
### Please describe your issue:
Invalid target "lxqt".
crouton doesn't seem to have support for lxqt, one of the more basic lightweight desktops. Does anyone know how to make this work, and if not, is this in the works? Thanks for all the help.
#### If known, describe the steps to reproduce the issue:
By entering " sudo crouton -t lxqt " the issue is reproduces.

**Comment by DennisLfromGA** [comment]
@kingliamb,

There was a pull request for an LXQt desktop target here -
- LXQT #2525

Unfortunately, the original author is no longer able to work on it currently.
He is open to others helping out though but, as yet, no one has.

*Hope this helps,*
-**DennisLfromGA**
