### ISSUE TITLE
Ubuntu 18.04.3 LTS: socket_client_read_frame_header: Read error.

### ISSUE THREAD

**Issue by dieseltravis** [dnschneid/crouton#4141]
```
crosh> shell
chronos@localhost / $ sudo edit-chroot -all
Password: 
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190807171712~master:6f45f06a
release: bionic
architecture: amd64
xmethod: xiwi
targets: lxde,keyboard,xiwi,xfce
host: version 12239.92.0 (Official Build) stable-channel lars 
kernel: Linux localhost 3.18.0-19679-gd1d0bbedf35d #1 SMP PREEMPT Tue Aug 27 17:02:30 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
In Ubuntu 18.04.3 LTS, whenever the screen sleeps or the laptop is closed, the session gets disconnected and `socket_client_read_frame_header: Read error.` is written out to the crosh window.

#### If known, describe the steps to reproduce the issue:

1. install Ubuntu 18.04.3 LTS
2. use lxde
3. close laptop
4. open laptop

**Comment by dieseltravis** [comment]
This sounds like it is similar to what is happening with #4123

**Comment by cvmiller** [comment]
Agreed, it looks like #4123

**Comment by dieseltravis** [comment]
closing as duplicate of #4123
