### ISSUE TITLE
Terminal crashes upon opening [Kali-Rolling]

### ISSUE THREAD

**Issue by VenomiXeD** [dnschneid/crouton#4146]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Out: kali-rolling

#### Please describe your issue:
So, using kali-rolling and I can't seem to open the terminal. I've powerwashed and tried reinstalling it. No luck. I could use the terminal before but now I can't do it anymore. I've also looked around but no luck fixing it either.
Terminal opens very briefly after just a millisecond closes again.

#### If known, describe the steps to reproduce the issue:
Install kali-rolling
use it for a while
tada. It won't work

**Comment by rm1138** [comment]
I also have the same problem.

**Comment by Imperial-Industries** [comment]
Try seeing if you can enter the chroot.

Like type in 
`sude enter-chroot [CHROOT NAME]`

**Comment by rm1138** [comment]
Yes, I can basically do anything inside chroot. I also can open xterm, but when I open other terminal (tried xfce4-terminal, gnome-terminal and terminator) it just flashed and disappeared.

**Comment by Imperial-Industries** [comment]
Oh I also had this problem once.
Are you using xfce4?

**Comment by VenomiXeD** [comment]
Yes. I'm using xfce4, `sudo sh ~/Downloads/crouton -t xfce,extension -r kali-rolling`. Am I supposed to use something else?

**Comment by chrismhorner** [comment]
Same issue here. All of a sudden Terminator and XFCE Terminal refuse to run. The only command line interface that I can get to work is X Term. Updated everything, uninstalled and reinstalled Terminator which goes fine, but still will not launch.

**Comment by Imperial-Industries** [comment]
Does it just happen on xfce4?
Or does it happen on unity and gnome as well?

**Comment by VenomiXeD** [comment]
Unsure. I haven't tried.

**Comment by VenomiXeD** [comment]
Okay so now kali installation is completely broken. I can't install kali-rolling at all.

**Comment by Imperial-Industries** [comment]
try installing a different chroot and see what happens
