### ISSUE TITLE
Kali linux terminal not opening after the update

### ISSUE THREAD

**Issue by sameersh963** [dnschneid/crouton#4151]
I update Kali 
apt-get update and apt-get upgrade and after restart terminal was not opening

**Comment by dethslayer999** [comment]
Did The Same For Me,i Tried Deleting It and Reinstalling It But all it get is that something could not be installed so it unmount's and stop the install,

**Comment by dethslayer999** [comment]
here is the error i get 

Package 'xbindkeys' has no installation candidate
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in kali-rolling
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by chrismhorner** [comment]
Same issue here.  All of a sudden Terminator and XFCE Terminal refuse to run.  The only command line interface that I can get to work is X Term.  Updated everything, uninstalled and reinstalled Terminator which goes fine, but still will not launch.

**Comment by tdugger** [comment]
I saw this problem too, but now after deleting my chroot I can't even get kali to install.

**Comment by spaceinvators** [comment]
Any news?

**Comment by BlackAssassin** [comment]
> here is the error i get
> 
> Package 'xbindkeys' has no installation candidate
> Failed to complete chroot setup.
> The chroot setup script may be broken. Your chroot is not fully configured.
> Removing the chroot setup script. You may want to update your chroot again.
> UID 1000 not found in kali-rolling
> Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

When I use ubuntu,I get the same error.Any news?
