### ISSUE TITLE
Xenial sound is choppy / echoing

### ISSUE THREAD

**Issue by munsta0** [dnschneid/crouton#4154]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12371.75.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:34:54 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
Sounds played while inside xenial is choppy / echoing, Rebooted, ran update/upgrade in xenial, didn't fix.

Tested on youtube.com with chromium and on rythmbox, both show the same behavior

#### If known, describe the steps to reproduce the issue:
This is a brand new chromebook / install on an Asus 202 

I followed the steps 1-8 in the section "The easy way (assuming you want an Ubuntu LTS with Xfce)" in the README

Please let me know if there is anything I didn't include.

Thnak you.

**Comment by Glory-Be** [comment]
Same problem with my Acer CB3-131 (Baytrail) Chromebook running xenial/xfce; sound choppy/garbled in all applications (media player, browser, etc.) after recent ChromeOS update. All was fine for well over a year before this happened...also, sound is fine in ChromeOS.

**Comment by Glory-Be** [comment]
UPDATE: I updated my chroot (sudo crouton -u -n xenial) & that fixed my audio problem!
