### ISSUE TITLE
Issue with installing Crouton

### ISSUE THREAD

**Issue by SmolShibe** [dnschneid/crouton#4155]
```
`ERROR: unknown command: shell`
```
After downloading the file, and opening the shell (Ctrl+Alt+T), when typing "shell" the Chromebook does not identify the command.
Why is this? Is there any way to solve it?

**Comment by DennisLfromGA** [comment]
@SmolShibe,

> After downloading the file, and opening the shell (Ctrl+Alt+T), when typing "shell" the Chromebook does not identify the command.

It appears that you may not be in '[Developer Mode](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/generic)' which is entirely different from the '[dev channel](https://support.google.com/chromebook/answer/1086915?hl=en). You have to enable Developer mode to get access to the `shell` command. Please bear in mind that, along with many bnefits, it also comes with some risks, see below:

[Developer Mode](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/generic)
> Caution: Modifications you make to the system are not supported by Google, may cause hardware, software or security issues and may void warranty.

*Hope this helps,*
-**DennisLfromGA**

**Comment by SmolShibe** [comment]
Thank you!
This solved my problem completely
