### ISSUE TITLE
Gnome won't start, crashes

### ISSUE THREAD

**Issue by Cybercave** [dnschneid/crouton#4158]
```
Here is the output of 'sudo edit-chroot -all':

name: andrew
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/andrew...
name: anw
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/anw...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: buster
architecture: amd64
xmethod: xorg
targets: gnome
host: version 12371.75.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:32:21 PDT 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/anw...
```

Hi all.
I have had the following problem ever since I started using crouton.
I have an Asus C302C and have gotten e17 and xcfe to work with Debian buster.  But for the life of me I cannot get gnome to work.  I have tried [this](https://github.com/dnschneid/crouton/issues/3359#issuecomment-327838969), but it is not installed.

I get the following error when running "sudo startgnome" (note: I have gotten the core dump handler message since updating Chrome to the latest stable channel):

WARNING: Unable to register core dump handler.

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-8-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:32:21 PDT 2019 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3686400 verity payload=PARTUUID=9074433b-f369-a64f-8c21-6b7562003ecd/PARTNROFF=1 hashtree=PARTUUID=9074433b-f369-a64f-8c21-6b7562003ecd/PARTNROFF=1 hashstart=3686400 alg=sha256 root_hexdigest=203aa9f05513c575ced4e7eb962f7b57f76c3d1985107f1759b06d65f3005164 salt=ed507eaabb59ff604c6be79fec73a499590f71b052e9089e2bfee9c1f8a5beed" noinitrd vt.global_cursor_default=0 kern_guid=9074433b-f369-a64f-8c21-6b7562003ecd add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic intel_idle.max_cstate=7 tpm_tis.force=0  
Build Date: 05 March 2019  08:11:12PM
xorg-server 2:1.20.4-1 (https://www.debian.org/support) 
Current version of pixman: 0.36.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Oct 20 14:07:50 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1571598471.266244 sender=:1.9 -> destination=:1.78 serial=888 reply_serial=2
   boolean true
(II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
crouton: version 1-20190902190258~master:9a594a66
release: buster
architecture: amd64
xmethod: xorg
targets: gnome
host: version 12371.75.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-19733-g972ff9adcd38 #1 SMP PREEMPT Wed Sep 25 23:32:21 PDT 2019 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1571598522.729127 sender=:1.9 -> destination=:1.80 serial=890 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/anw...

**Comment by jamesMFelder** [comment]
I have had the exact same problem.
Just letting you know that you're not alone.
Someone else has the same problem [here.](https://github.com/dnschneid/crouton/issues/4163)

**Comment by jamesMFelder** [comment]
I fixed on xenial by running the command
`rm -r ~/.config/`
Updating eoan and then going to try it.

**Comment by jamesMFelder** [comment]
Updated eoan+gnome and it worked. I don't know what caused it or if it's going to happen again.
Good luck!
