### ISSUE TITLE
Horrible Lag after chroot reinstall on Acer Chromebook 15 i5-5200u @2.4GHz 4GB RAM

### ISSUE THREAD

**Issue by triplecombinationflusterbuster** [dnschneid/crouton#4160]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: lxde,xorg
host: version 12371.75.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Sep 25 23:32:59 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

Hi,

I have been using crouton since probably the time of winter 2016 and it has worked fantastically - until today.  Unfortunately, my XFCE chroot was accidentally boinked and I had to reinstall it.  Upon re-installation of both my chroot and Steam, my favorite games no longer worked properly when quite literally two hours before that, I was running Counter-Strike 1.6 at 150 fps flawlessly.  I know, it's a game made in 1999 but Chromebooks weren't exactly made with gaming in mind.  

This has been pretty disheartening because crouton has worked so wonderfully until today and I don't have a clue as to what happened between my previous chroot and the new, fresh chroot.  I have toyed with the idea of installing an older version of Ubuntu such as "precise" or "trusty" but I cannot find a reliable mirror that works.  My Chromebook is a tad old, but it has got an Intel i5 in it and XFCE is helluva lightweight desktop.

Some of this nay makes sense to me however since I always kept up with crouton updates.  So my last chroot (the one that was boinked) was on 16.04 xenial (after upgrades; kernel 3.14.0).  Lo and behold, I fresh install the crouton installer and fresh install 16.04 Xenial and nothing worked like it did literally 2 hours before.  

I have attempted to install LXDE since it is a tad lighter than XFCE, but no dice.  Still getting horrible FPS drops why trying to play my favorite games.  None of this makes any sense to me - it should be working just as it was before.  

Any pointers? Thanks.

Just to reiterate because this really does not make any sense to me; my previous chroot was the same as the freshly installed one.  3.14.0 kernel, 16.04 Xenial.  Why am I all of a sudden getting bad performance issues?

Another thing I noticed that may or may not be relevant: 
LXDE has a nice CPU monitor on the taskbar.  When I opened LXDE for the first time, the CPU monitor was full green.  Is crouton more CPU intensive now?  

EDIT: Ah yes, I have reinstalled XFCE for the umpteenth time now and my CPU usage is at 100% constantly.  This has never happened before.  I am actually using an Acer Chromebook 15 i5-5200U 2.4 GHz with 4GB ram.  I should be able to run all my programs perfectly.  What gives??

EDIT2: I have since powerwashed my Chromebook and noticed while running `sudo top` my CPU was clean.  Reinstalling crouton installer and installing a chroot immediately caused both my CPU's to operate at 100% **EACH**.  Removing both the crouton installer and nuking the chroot **IMMEDIATELY** freed up my CPU and everything went back to normal.

@dnschneid

**Comment by triplecombinationflusterbuster** [comment]
**UPDATE 0227 EST (EASTERN STANDARD TIME)**

So after about 32 hours of trying to figure out what the hell was going on, I simply restarted my Chromebook and whatever was eating my CPU alive ceased.  I don't know what was hogging my CPU since running `top` **WOULD NOT** show the heinous offender.  It was quite silly - looking in both the Chrome OS task manager and the respective chroot's task manager along with `top` or `htop` failed to identify the culprit.  It seemed to be a phantom process that was hogging 100% of system resources. 

If anybody hits this snag, simply restart your Chromebook and the bottleneck will go away.

**Comment by DennisLfromGA** [comment]
Thanx for the update.
Closing. Please re-open if this issue is still a concern.
