### ISSUE TITLE
Chrome to Crouton Install Issue

### ISSUE THREAD

**Issue by Chrome2Linux** [dnschneid/crouton#4161]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Hey I've been following the updated tutorial to install Crouton and I'm a total newb so this may be something silly... Any help would be dope

#### If known, describe the steps to reproduce the issue:
I pull the command window:
crosh> shell (enter)
chronos@local host / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton

install: cannot stat '/home/chronos/user/Downloads/crouton' : No such file or directory

**Comment by DennisLfromGA** [comment]
@Chrome2Linux,

It just looks like you may not have the `crouton` installer in your Downloads folder.
> You can grab the latest release from [https://goo.gl/fd3zc](https://goo.gl/fd3zc). 
> Download it and save it in your Downloads folder.

Once that's done you should be able to continue with the steps you listed above.

*Hope this helps,*
-**DennisLfromGA**
