### ISSUE TITLE
Trouble with 'sudo startxfce4' after linux installation on chromeOS

### ISSUE THREAD

**Issue by jcd83a** [dnschneid/crouton#4166]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

#### Please describe your issue: I was having trouble with online tutorials for how to install linux on a chrome book when I saw #4026 I then did a factory reset on my device, enabled developer mode, then followed the README exactly. Everything goes smoothly until the 'sudo startxfce' line where I put in my passphrase and password upon request and then it spits out an error. I'll copy paste the full output and error within below. I'm extremely new to all this, so I could be doing something quite obviously wrong. I also already tried 'sudo crouton -n chrootname -u' with xenial as my chrootname since thats what 'sudo edit-chroot -all' gave me. And I saw #4131 has a similar issue, but no one but me has responded to it. The chromebook I'm using is a model XE303C12. Please help! If you need any more info I missed, just ask. Thank you

chronos@localhost / $ sudo startxfce4
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=170ff689-5c5e-9d4e-819f-2af634431582/PARTNROFF=1 hashtree=PARTUUID=170ff689-5c5e-9d4e-819f-2af634431582/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=3bfc672b009a3247d3cd8399a74f96ac53188553 salt=306427720380043295ff7f5e5f7ef68a81138057901e316471bd1520719b78b2" noinitrd vt.global_cursor_default=0 kern_guid=170ff689-5c5e-9d4e-819f-2af634431582  
Build Date: 25 October 2018  04:16:21PM
xorg-server 2:1.19.6-1ubuntu4.1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Nov 10 12:15:39 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1573406139.575545 sender=:1.13 -> destination=:1.55 serial=865 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1573406140.687930 sender=:1.13 -> destination=:1.57 serial=866 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
s/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### If known, describe the steps to reproduce the issue:
1. factory reset
2. enter developer mode
3. downloaded crouton
4. ctrl alt T
5. shell
6. sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
7. sudo crouton -e -t xfce
8. wait a long time for everything to install and entered passwords and passphrase
9. sudo enter-chroot startxfce4
10. asks for passphrase and I enter it
11. outputs error seen above

**Comment by cubetronic** [comment]
Duplicated error, Samsung XE303C12. I used to use crouton with LXDE, so I'm going to try that instead... here's the output of trying to start Xfce:
```
chronos@localhost / $ sudo enter-chroot startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server


X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=e4b91921-1f75-6143-a179-b611f4bea3cc/PARTNROFF=1 hashtree=PARTUUID=e4b91921-1f75-6143-a179-b611f4bea3cc/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=3bfc672b009a3247d3cd8399a74f96ac53188553 salt=306427720380043295ff7f5e5f7ef68a81138057901e316471bd1520719b78b2" noinitrd vt.global_cursor_default=0 kern_guid=e4b91921-1f75-6143-a179-b611f4bea3cc  
Build Date: 25 October 2018  04:16:21PM
xorg-server 2:1.19.6-1ubuntu4.1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Nov 10 13:09:33 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1573420173.337962 sender=:1.10 -> destination=:1.51 serial=888 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1573420173.636635 sender=:1.10 -> destination=:1.53 serial=889 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 
```

**Comment by cubetronic** [comment]
no luck with Xenial and LXDE... i must've used Trusty.. it's all coming back to me now... this is why i got away from crouton and started using Arch Linux... but i'm back just to test x264 video in crouton because that worked, whereas in Arch it doesn't work full screen... even with xf86-video-fbdev driver and config file, which improves graphics.

so i'm just gonna bite the bullet on this and run:
`sudo crouton -r trusty -t lxde`

oh no!
```
chronos@localhost / $ sudo crouton -r trusty -t lxde
Downloading latest crouton installer...
############################################################################################################# 100.0%############################################################################################################# 100.0%
WARNING: trusty has reached upstream end-of-life.
That means there will be no package updates available.
You also have to specify a mirror to crouton (-m) for installation to proceed.
chronos@localhost / $ 
```
well R.I.P. crouton

**Comment by jcd83a** [comment]
Like I said, I'm very new to this, but the help is much appreciated! My main purpose for installing linux is because I need to use the Arduino IDE and Processing on the only portable laptop I currently own. Do you know of any other route I could take to have compatibility with that software? Currently I'm planning on settling for an arduino and a processing app on my phone, but there are issues there too that I'll need to figure out.

**Comment by cubetronic** [comment]
i recommend trying Archbk
https://github.com/altreact/archbk/blob/master/make-arch_drv.sh

it's based on these Arch Linux instructions:
https://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook

just don't use a USB stick. it won't work. and the SD Card you use should really be 4 GB at the extreme least, but at least 8 GB to make sure you can install dev packages.

and then you'll have to download the Arduino IDE source code and compile it. so you'll need to install developer packages, etc. the [Arch Linux Arduino](https://wiki.archlinux.org/index.php/arduino#On_Arm7_devices) page gives me the impression that there might be some issues. http://blog.tklee.org/2014/10/arduino-ide-158-on-banana-pi.html

i'm currently working on an Arch Linux installation image for the XE303C12, and i have most of the issues worked out, including graphics acceleration, caps lock, audio, etc, but i want to try to get full GPU support before releasing it.

**Comment by jcd83a** [comment]
I appreciate all the help! Looking at all of the info you provided, I think it's a viable path, but I doubt my competency in making it work. If you or anyone else finds a way to resolve the initial post, definitely let me know. For now, I'll see if I can use my phone for the purposes of getting my project done and revisit Arch Linux at a later date.

**Comment by cubetronic** [comment]
ok i just uploaded my current Arch Linux setup on the XE303C12.
https://github.com/cubetronic/aok-linux

it's basically for me right now, and the scripts prompt for things in the middle.. but hey.. seriously.. if you want the best distro on that XE303C12 right now, this is it.

you can at least get files 3 and 4 from my repo to patch caps lock, improve video, and get audio working... after running archbk. but archbk will just dump you out into a command line with NOTHING.. but.. at least that way you can set things up from scratch how you want..

anyway, my "distro" isn't tested as-is yet... so no guarantees..

**Comment by cubetronic** [comment]
i hear that.. it's a bunch of command line stuff, these scripts, and Archbk, and Arch in general. but i'm working to make an image- so it's extremely easy, no command line, no hassle.

**Comment by jcd83a** [comment]
That feels like it would be way more approachable for the layman like me. I'm not even sure what an image or a distro is in this context beyond what you just described. Not having to do command line feels ideal as I have no prior experience with it at all.

**Comment by cubetronic** [comment]
installing the official Arduino IDE from their website is working flawlessly.. i can't really thoroughly test it, but they have an image for ARMv7 32 bit which i downloaded, extracted, and ran the install.sh, and it works...

**Comment by DennisLfromGA** [comment]
All (using ARM chips),

Please see this topic comment for a possible workaround:

- [Downloading Linux on Chromebook; cannot run command "sudo startxfce4". Please Help!](https://github.com/dnschneid/crouton/issues/4131#issuecomment-555041929)

*Hope this helps,*
-**DennisLfromGA**

**Comment by jcd83a** [comment]
@DennisLfromGA 

Thanks for the advice in that topic. Unfortunately, that xiwi update didn't work for me as it ended in another error message. All I did was ctrl+alt+T, shell, sudo crouton -n xenial -t xiwi -u without altering any of the steps I took previously. If you have any ideas or if I did something wrong, definitely let me know! Thank you again.

**Comment by cubetronic** [comment]
@jcd83a 
i've improved my distro and it works alright. github.com/cubetronic/aok

this is not quite as easy as an image, but it's about as easy as crouton, and better than an image. it does require an SD Card or a lucky USB drive (not all USB's are created equal).

**Comment by bobo37462** [comment]
> ```
> Please paste the output of the following command here: sudo edit-chroot -all
> ```
> 
> chronos@localhost / $ sudo edit-chroot -all
> name: xenial
> encrypted: yes, locked
> Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
> chronos@localhost / $
> 
> #### Please describe your issue: I was having trouble with online tutorials for how to install linux on a chrome book when I saw #4026 I then did a factory reset on my device, enabled developer mode, then followed the README exactly. Everything goes smoothly until the 'sudo startxfce' line where I put in my passphrase and password upon request and then it spits out an error. I'll copy paste the full output and error within below. I'm extremely new to all this, so I could be doing something quite obviously wrong. I also already tried 'sudo crouton -n chrootname -u' with xenial as my chrootname since thats what 'sudo edit-chroot -all' gave me. And I saw #4131 has a similar issue, but no one but me has responded to it. The chromebook I'm using is a model XE303C12. Please help! If you need any more info I missed, just ask. Thank you
> chronos@localhost / $ sudo startxfce4
> Enter encryption passphrase for xenial:
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
> /usr/bin/startxfce4: Starting X server
> 
> X.Org X Server 1.19.6
> Release Date: 2017-12-20
> X Protocol Version 11, Revision 0
> Build Operating System: Linux 4.4.0-138-generic armv7l Ubuntu
> Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l
> Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=170ff689-5c5e-9d4e-819f-2af634431582/PARTNROFF=1 hashtree=PARTUUID=170ff689-5c5e-9d4e-819f-2af634431582/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=3bfc672b009a3247d3cd8399a74f96ac53188553 salt=306427720380043295ff7f5e5f7ef68a81138057901e316471bd1520719b78b2" noinitrd vt.global_cursor_default=0 kern_guid=170ff689-5c5e-9d4e-819f-2af634431582
> Build Date: 25 October 2018 04:16:21PM
> xorg-server 2:1.19.6-1ubuntu4.1~16.04.2 (For technical support please see http://www.ubuntu.com/support)
> Current version of pixman: 0.33.6
> Before reporting problems, check http://wiki.x.org
> to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
> (++) from command line, (!!) notice, (II) informational,
> (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Nov 10 12:15:39 2019
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
> method return time=1573406139.575545 sender=:1.13 -> destination=:1.55 serial=865 reply_serial=2
> boolean true
> MESA-LOADER: failed to retrieve device information
> gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
> failed to load driver: exynos
> EGL_MESA_drm_image required.
> (EE)
> Fatal server error:
> (EE) AddScreen/ScreenInit failed for driver 1
> (EE)
> (EE)
> Please consult the The X.Org Foundation support
> at http://wiki.x.org
> for help.
> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
> (EE)
> Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
> method return time=1573406140.687930 sender=:1.13 -> destination=:1.57 serial=866 reply_serial=2
> boolean true
> (EE) Server terminated with error (1). Closing log file.
> s/usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> /usr/bin/xinit: server error
> Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
> 
> #### If known, describe the steps to reproduce the issue:
> 1. factory reset
> 2. enter developer mode
> 3. downloaded crouton
> 4. ctrl alt T
> 5. shell
> 6. sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
> 7. sudo crouton -e -t xfce
> 8. wait a long time for everything to install and entered passwords and passphrase
> 9. sudo enter-chroot startxfce4
> 10. asks for passphrase and I enter it
> 11. outputs error seen above

I'm having the same issue and its a complete and utter pain. I am not a coder whatsoever and its a nightmare........
