### ISSUE TITLE
Installer keeps failing

### ISSUE THREAD

**Issue by Piflyer** [dnschneid/crouton#4167]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
If this is a surprise to you, you should do a full system recovery via USB.
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/var/run/drm': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
The installer keeps crashing whenever it reaches that point. I have tried running it with sudo and root. I also have created the directory '
/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/var/run/drm'.

#### If known, describe the steps to reproduce the issue:

Use FydeOS for Raspberry Pi on Pi 4 and follow the instructions.

**Comment by justchen1369** [comment]
have you run it with sudo?

**Comment by Piflyer** [comment]
Yes I have, and also have tried running sudo su first.

**Comment by justchen1369** [comment]
Hmm... I would try changing the permissions on mentioned directory.

**Comment by Carl393** [comment]
Did you find the solution to your problem?
