### ISSUE TITLE
Chromium Not Present On Unity Crouton Chroot 

### ISSUE THREAD

**Issue by ThomasTail** [dnschneid/crouton#4169]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: gnometrusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/gnometrusty...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
targets: keyboard,extension,gnome
host: version 12499.66.0 (Official Build) stable-channel kip 
kernel: Linux localhost 4.4.190-16770-gb3c36ab5af98 #1 SMP PREEMPT Thu Nov 14 23:11:43 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/gnometrusty...
name: unitytrusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/unitytrusty...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: keyboard,extension,unity
host: version 12499.66.0 (Official Build) stable-channel kip 
kernel: Linux localhost 4.4.190-16770-gb3c36ab5af98 #1 SMP PREEMPT Thu Nov 14 23:11:43 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/unitytrusty as another instance is using it.
#### Please describe your issue:
Chromium browser is not correctly installed on Crouton distributions. 

#### If known, describe the steps to reproduce the issue:
1. Install Unity Crouton (non-trusty as trusty will fail)
2. sudo startunity
3. Unity will start as normal but Chromium will not be present.
4. When reading shell log, find the following output repeated as soon as chroot is started:
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files

**Comment by ThomasTail** [comment]
Perhaps including a sudo apt-get install chromium --fix-missing into the bash file installation will fix this issue in further updates. Thank you for your time.

**Comment by justchen1369** [comment]
Can we close?

**Comment by DennisLfromGA** [comment]
@ThomasTail,

It looks like the targets you specified on the command-line were:
> targets: keyboard,extension,unity

crouton has both chrome and chromium targets, see below:
```
chrome
        Google Chrome browser, stable channel.
        Requires: x11
chrome-beta
        Google Chrome browser, beta channel.
        Requires: x11
chrome-dev
        Google Chrome browser, dev channel.
        Requires: x11
chromium
        Chromium browser. Uses the distro's version, which may be old.
        Requires: x11
```

So, to install it in your existing chroot named 'unitytrusty' use this:
- `sudo crouton -n unitytrusty -t chromium -u`

*Hope this helps,*
-**DennisLfromGA**
