### ISSUE TITLE
ACER Chromebook - Crouton fails to complete installation if a single package fails

### ISSUE THREAD

**Issue by thatonetechdude** [dnschneid/crouton#4171]
I am trying to install linux kali (kali-roling) to my cromebook acer CB3-111 I have downloaded

https://github.com/dnschneid/crouton
https://goo.gl/fd3zc

when installing with the code "sudo sh crouton -r kali-rolling -t xfce,extension,xiwi" for the first time all wne well exept untill what I think was the end of the instalation process when it gave the text

Package xbindkeys is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'xbindkeys' has no installation candidate
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

now then I try installing again it just says

/usr/local/chroots/kali-rolling already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

I dont know how to delete it and how to successfully install linux kali, Any help would be nice.

![Screenshot 2019-11-29 at 3 06 39 PM](https://user-images.githubusercontent.com/58344782/69890101-f3fe4b00-12b9-11ea-8eaf-b6beb1399f63.png)
![Screenshot 2019-11-29 at 3 07 49 PM](https://user-images.githubusercontent.com/58344782/69890130-0d06fc00-12ba-11ea-893a-01791e41a15c.png)
![Screenshot 2019-11-29 at 3 10 57 PM](https://user-images.githubusercontent.com/58344782/69890263-7981fb00-12ba-11ea-9fbf-44544a96ecf6.png)
![Screenshot 2019-11-29 at 3 12 35 PM](https://user-images.githubusercontent.com/58344782/69890333-b3eb9800-12ba-11ea-9217-ed15035f6f8e.png)

**Comment by monster1612** [comment]
try to run a Google search with your issue before posting - sometimes the errors you get aren't necessarily crouton-specific (but in this case, it's hard to tell). either way, try the steps outlined here as a possible solution: https://github.com/dnschneid/crouton/issues/4153#issuecomment-555853522

**Comment by thatonetechdude** [comment]
@monster1612 Thanks you for the help, although im fairly new this the chromebook coding and am takng measures to increase my coding experience and was wondering if you could put this in more "noob" freindly terms, thanks.
