### ISSUE TITLE
Launch Failure!!!! Error (1) - College student/Noob coder struggling to put linux on a samsung chromebook via youtube videos and forms

### ISSUE THREAD

**Issue by bobo37462** [dnschneid/crouton#4172]
Plz help....... so I did all the steps I installed crouton into my downloaders folder and I went thru and I did all the commands in the localhost console and then it said error (1) and that the launch terminated or something after spending four hours trying to fix it then gave up closed the lid I ate something after 30 mins I attempted to redo it to see if it failed to start again and it did but now shows this below? Help please....... Please try to say it in a way a gamer would know I'm not the best at this but just trying to get Linux onto my samsung chromebook so I can download steam and everything.....

 
chronos@localhost / $ sudo enter-chroot startxfce4
Entering /mnt/stateful_partition/crouton/chroots/sid...
UID 1000 not found in sid
Unmounting /mnt/stateful_partition/crouton/chroots/sid...
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/sid...
UID 1000 not found in sid
Unmounting /mnt/stateful_partition/crouton/chroots/sid...
chronos@localhost / $

**Comment by bobo37462** [comment]
Anything that'll help get back on track helps. I tried powerwashing my computer and starting over and ended up on the same route so I'm turning to yall.........

**Comment by gudhid71** [comment]
make sure you installed the crouton extension too this link right here https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom and then you type this code : sudo crouton -t xiwi,xfce this worked for me so i hope it does for you too
