### ISSUE TITLE
Soooo many issues with 'sudo startxfce4' after attempted linux installation on chromeOS

### ISSUE THREAD

**Issue by bobo37462** [dnschneid/crouton#4173]
Soooo many issues with 'sudo startxfce4' after attempted linux installation on chromeOS

chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=e4b91921-1f75-6143-a179-b611f4bea3cc/PARTNROFF=1 hashtree=PARTUUID=e4b91921-1f75-6143-a179-b611f4bea3cc/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=3bfc672b009a3247d3cd8399a74f96ac53188553 salt=306427720380043295ff7f5e5f7ef68a81138057901e316471bd1520719b78b2" noinitrd vt.global_cursor_default=0 kern_guid=e4b91921-1f75-6143-a179-b611f4bea3cc  
Build Date: 25 October 2018  04:16:21PM
xorg-server 2:1.19.6-1ubuntu4.1~16.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Nov 10 13:09:33 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1573420173.337962 sender=:1.10 -> destination=:1.51 serial=888 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1573420173.636635 sender=:1.10 -> destination=:1.53 serial=889 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $ 

I'm just trying to get Linux so I am able to use steam and roblox and play other various games and its a nightmare please help.......

**Comment by bobo37462** [comment]
It constantly shows this..............


(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
@bobo37462,

Please paste the output of the following command so we can see what device, version, chroot, etc. you're using:
- `sudo edit-chroot -all`

-**DennisLfromGA**

**Comment by bobo37462** [comment]
> @bobo37462,
> 
> Please paste the output of the following command so we can see what device, version, chroot, etc. you're using:
> 
> * `sudo edit-chroot -all`
> 
> -**DennisLfromGA**

when I attempt to run that command it says error (1) 

I attempted to powerwash and do the same steps and I get the same error. I’m on a Samsung Chromebook X303 and I’m running snow. Any advice?

**Comment by bobo37462** [comment]
> @bobo37462,
> 
> Please paste the output of the following command so we can see what device, version, chroot, etc. you're using:
> 
> * `sudo edit-chroot -all`
> 
> -**DennisLfromGA**

I’m a complete noob to this just a broke college kid trying to get Linux on my chrome book. Pretty well versed with tech though and into games and this is a complete nightmare I’ve tried the xiwi quick fix and that didn’t work either.

**Comment by bobo37462** [comment]
> @bobo37462,
> 
> Please paste the output of the following command so we can see what device, version, chroot, etc. you're using:
> 
> * `sudo edit-chroot -all`
> 
> -**DennisLfromGA**




Here is the info


name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 12105.100.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@bobo37462,

ARM devices often have issues with video drivers, etc.; this may be an old issue that is still a problem.
All I can suggest is take a look at this comment using Exynos, try it, and see if it helps at all -

- [https://github.com/dnschneid/crouton/issues/2424#issuecomment-180884944](https://github.com/dnschneid/crouton/issues/2424#issuecomment-180884944)

*Hope this helps,*
-**DennisLfromGA**

**Comment by bobo37462** [comment]
> @bobo37462,
> 
> ARM devices often have issues with video drivers, etc.; this may be an old issue that is still a problem.
> All I can suggest is take a look at this comment using Exynos, try it, and see if it helps at all -
> 
Sadly no luck. I was hoping it would work. I am debating just buying a newer type chromebook and doing it. It was worth a try.

> * [#2424 (comment)](https://github.com/dnschneid/crouton/issues/2424#issuecomment-180884944)
> 
> _Hope this helps,_
> -**DennisLfromGA**

**Comment by bobo37462** [comment]
Bought a new never touched chromebook just like the old one and experiencing what seems to be the same issue
