### ISSUE TITLE
Newbie Here: (EE) Server terminated with error (1). Closing log file.

### ISSUE THREAD

**Issue by samosley** [dnschneid/crouton#4175]
```
Please paste the output of the following command here: sudo edit-chroot -all
```ame: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 11316.165.0 (Official Build) stable-channel daisy_spring 
kernel: Linux localhost 3.8.11 #1 SMP Sun Mar 3 22:44:20 PST 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue: Im unable to start Linux on my Chromebook.  I get the Server Terminated error (1)
I'm entering   sudo startxfce4 on the command line, screen goes black, then get server error.

#### If known, describe the steps to reproduce the issue:

**Comment by bobo37462** [comment]
I'm having the same problem and have no clue what to do either. Do you have a samsung chromebook?

**Comment by samosley** [comment]
I have the HP Chromebook 11

Frustrating. Everything was fine until the end.

**Comment by bobo37462** [comment]
> I have the HP Chromebook 11 Frustrating. Everything was fine until the end.
> […](#)
 Had the only issues at the end as well. Took it into Office Depot today and they think the software is too outdated to install crouton and Linux. They said it would work fine on newer chrome books or pixel books but with older HP and Samsung chromebooks it can be tricky....

**Comment by monster1612** [comment]
does Trusty (ubuntu 14.04 LTS) work? your device (the Chromebook 11 G1) got EOL'd on October 2018, so crouton updates/possbily Ubuntu Xenial itself may be showing incompatibilities.

your best bet would be making a new chroot with the _-r trusty_ argument to check.

**Comment by Carl393** [comment]
Did you figure out the issue?
