### ISSUE TITLE
Running startxfce4 fails with multiple errors listed

### ISSUE THREAD

**Issue by scvannost** [dnschneid/crouton#4176]
After installing the xfce, I got the error below trying to run `sudo startxfce4`.
I followed several Issues' solutions, namely updating the target with several things including x11 and xfce-desktop.

I'm running ChromeOS Version 75.0.3770.144 (Official Build) (32-bit) on an XE303C12 chromebook.

I'm unsure what other information is useful or relevant so please do ask for anything helpful.

```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce-desktop,keyboard,x11,xfce
host: version 12105.100.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l armv7l armv7l GNU/Linux
freon: yes

#### Please describe your issue:
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1575180586.382627 sender=:1.13 -> destination=:1.83 serial=1192 reply_serial=2
   boolean true
MESA-LOADER: failed to retrieve device information
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
failed to load driver: exynos
EGL_MESA_drm_image required.
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 1
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1575180587.404096 sender=:1.13 -> destination=:1.85 serial=1193 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

**Comment by bobo37462** [comment]
Same issue here. No ones been of any help yet.....

**Comment by bobo37462** [comment]
> After installing the xfce, I got the error below trying to run `sudo startxfce4`.
> I followed several Issues' solutions, namely updating the target with several things including x11 and xfce-desktop.
> 
> I'm running ChromeOS Version 75.0.3770.144 (Official Build) (32-bit) on an XE303C12 chromebook.
> 
> I'm unsure what other information is useful or relevant so please do ask for anything helpful.
> 
> ```
> Please paste the output of the following command here: sudo edit-chroot -all
> ```
> 
> name: xenial
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
> crouton: version 1-20190902190258~master:9a594a66
> release: xenial
> architecture: armhf
> xmethod: xorg
> targets: xfce-desktop,keyboard,x11,xfce
> host: version 12105.100.0 (Official Build) stable-channel daisy
> kernel: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l armv7l armv7l GNU/Linux
> freon: yes
> 
> #### Please describe your issue:
> Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
> method return time=1575180586.382627 sender=:1.13 -> destination=:1.83 serial=1192 reply_serial=2
> boolean true
> MESA-LOADER: failed to retrieve device information
> gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
> failed to load driver: exynos
> EGL_MESA_drm_image required.
> (EE)
> Fatal server error:
> (EE) AddScreen/ScreenInit failed for driver 1
> (EE)
> (EE)
> Please consult the The X.Org Foundation support
> at http://wiki.x.org
> for help.
> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
> (EE)
> Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
> method return time=1575180587.404096 sender=:1.13 -> destination=:1.85 serial=1193 reply_serial=2
> boolean true
> (EE) Server terminated with error (1). Closing log file.
> /usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> /usr/bin/xinit: server error

Same issue here.... No fix as of yet

**Comment by bobo37462** [comment]
> After installing the xfce, I got the error below trying to run `sudo startxfce4`.
> I followed several Issues' solutions, namely updating the target with several things including x11 and xfce-desktop.
> 
> I'm running ChromeOS Version 75.0.3770.144 (Official Build) (32-bit) on an XE303C12 chromebook.
> 
> I'm unsure what other information is useful or relevant so please do ask for anything helpful.
> 
> ```
> Please paste the output of the following command here: sudo edit-chroot -all
> ```
> 
> name: xenial
> encrypted: no
> Entering /mnt/stateful_partition/crouton/chroots/xenial...
> crouton: version 1-20190902190258~master:9a594a66
> release: xenial
> architecture: armhf
> xmethod: xorg
> targets: xfce-desktop,keyboard,x11,xfce
> host: version 12105.100.0 (Official Build) stable-channel daisy
> kernel: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l armv7l armv7l GNU/Linux
> freon: yes
> 
> #### Please describe your issue:
> Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
> method return time=1575180586.382627 sender=:1.13 -> destination=:1.83 serial=1192 reply_serial=2
> boolean true
> MESA-LOADER: failed to retrieve device information
> gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> gbm: Last dlopen error: /usr/lib/dri/exynos_dri.so: cannot open shared object file: No such file or directory
> failed to load driver: exynos
> EGL_MESA_drm_image required.
> (EE)
> Fatal server error:
> (EE) AddScreen/ScreenInit failed for driver 1
> (EE)
> (EE)
> Please consult the The X.Org Foundation support
> at http://wiki.x.org
> for help.
> (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
> (EE)
> Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
> method return time=1575180587.404096 sender=:1.13 -> destination=:1.85 serial=1193 reply_serial=2
> boolean true
> (EE) Server terminated with error (1). Closing log file.
> /usr/bin/xinit: giving up
> /usr/bin/xinit: unable to connect to X server: Connection refused
> /usr/bin/xinit: server error

I’m told it’s driver or firmware issue. I bought a newer type chromebook for 99 bucks off eBay and tried putting Crouton Linux on it and it worked fine. It’s definitely a driver or firmware issue on the older type chromebooks.

**Comment by epicwappy20** [comment]
i have the same problem! so frustrating.

**Comment by itstimeforbigboi** [comment]
same here. Is there any other fix rather than buying a new one?
