### ISSUE TITLE
Chrome will not open in xiwi

### ISSUE THREAD

**Issue by penthimos** [dnschneid/crouton#4180]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,cli-extra,gtk-extra,keyboard,extension,chrome-beta
host: version 12499.66.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-19748-gc785fae00b84 #1 SMP PREEMPT Thu Nov 14 23:05:26 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.

------------------------------------------------------

When I enter crouton (sudo startxfce4) and try to open Chrome inside, which I need to do to attach files from a mounted cloud drive.

I try to open Chrome in the application launcher or in a terminal within crouton, and get "Opening in existing browser session." 

This has not always happened, but has happened the last few times. Sometimes restarting the Chromebook seems to resolve it and sometimes it doesn't. But I would like this to stop happening. What can I do?

**Comment by monster1612** [comment]
check CrOS; maybe the URL handler is forwarding the new window request to a new tab in Chrome. that's about the only guess I have right now.

**Comment by penthimos** [comment]
> check CrOS; maybe the URL handler is forwarding the new window request to a new tab in Chrome. that's about the only guess I have right now.

I've been embarrassed to ask this, but what do you mean by "check CrOS"? How can I do that?

**Comment by monster1612** [comment]
no problem! everyone starts somewhere. :)

you'd alt-tab out of xiwi (make sure to take xiwi out of fullscreen with the F4/key to the right of reload key if you need to) and see if any Chrome tabs opened. my apologies for not specifying.
