### ISSUE TITLE
Listing of targets & releases throws noexec warnings

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#4182]
Please paste the output of the following command here: `sudo edit-chroot -all`
```
chronos@localhost ~ $ sudo crouton -V
crouton: version 1-20190902190258~master:9a594a66
```

#### Please describe your issue:
When I list crouton targets or releases I get warnngs about using a script from noexec mount.
This only happens on 'lulu' not 'eve' for some unknown reason.

#### If known, describe the steps to reproduce the issue:
When I list targets or releases on lulu using either:
- `sudo crouton -t list` or `sudo crouton -r list`

I get the following output:
- `crouton -t list` : https://pastebin.com/JJTLYd5m
- `crouton -r list` : https://pastebin.com/V4QKNBee

I'm using the same Chrome & CrOS versions on both 'lulu' and 'eve'.

The following versions & device are for 'lulu':

> **Google Chrome**:	79.0.3945.42 (Official Build) dev (64-bit)
> **Revision**:			9b8e372c682a69656927ca46c7dd3d19ac0df1bc-refs/branch-heads/3945@{#703}
> **Platform**:			12607.34.0 (Official Build) dev-channel lulu
> **Firmware Version**:	Google_Lulu.6301.136.57
> **ARC**:			6017610

One of the differences I noticed is on 'eve' I have these mounted in `/tmp`:
```
chronos@localhost ~ $ mount | grep /tmp
tmp on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel)
tmp on /tmp/crouton-installer-cache type tmpfs (rw,nosuid,nodev,relatime,seclabel)
```

On 'lulu', only `/tmp` is mounted as noexec, `/tmp/crouton-installer-cache` is *not* mounted.

I can get around the noexec warnings by using the following as a workaround:
- `sudo crouton -t list 2>&1 | grep -v warning`

This is not at all a critical issue for me but it is a little annoying.
It very well could be an issue of my own making but I'm not sure what causes it.

Thanx for any help with this,
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Just an update on this issue...

I rebooted both devices, eve & lulu, and did *not* sign-in but instead opened the Developer console on VT2. I ran `sudo crouton -t list` on both devices and got the same results as above. lulu threw noexec warnings and eve did not. The difference seems to be that on eve `/tmp/crouton-installer-cache` is mounted with exec permissions.

*Hope this helps,*
-**DennisLfromGA**

**Comment by dnschneid** [comment]
Could you please make sure you have the latest crouton installer?  Seems
possible the one on your Lulu is old.

**Comment by DennisLfromGA** [comment]
Okay, so sorry for not checking that first. 😞

I guess I thought `crouton -V` was a valid check but but it downloads a fresh installer first:
```
chronos@localhost ~/MyFiles/Downloads $ crouton -V
Downloading latest crouton installer...
########################################################################################################## 100.0%########################################################################################################## 100.0%
crouton: version 1-20190902190258~master:9a594a66
```
Dumb rookie mistake. 😔

Although, I think it would be helpful if it compared the installed version with the fresh downloaded one.

**Comment by dnschneid** [comment]
Glad to hear it wasn't a larger issue at hand.
The issue is in the version of the downloader installed (the thing that runs the part that says "Downloading latest crouton installer").  We really should have had the downloader set an environment variable that the downloaded installer could check and warn about.  Doing that now, though, would mean everyone with the installer already updated would see warnings about the installer being potentially out-of-date...not good.

**Comment by DennisLfromGA** [comment]
Yep, I was just being stupid.

We'll just have to remind users to get a fresh copy before doing any installs or updates.
