### ISSUE TITLE
i cant install crouton on a sd card

### ISSUE THREAD

**Issue by austinttt** [dnschneid/crouton#4183]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
sudo: edit-chroot: command not found
#### Please describe your issue:
ive been at his for over a week ive installled cruton but the sd card wouldnt have the perms to mount so reinstalled ... it didnt work so i figured putting is on the sd card would work but i have no got daang clue how to do that

#### If known, describe the steps to reproduce the issue:
localhost / # umount /dev/mmcblk0
umount: /dev/mmcblk0: not mounted.
localhost / # mkfs -t ext4 /dev/mmcblk0
mke2fs 1.44.5 (15-Dec-2018)
/dev/mmcblk0 contains a ext4 file system labelled 'Sam64GBext4'
        created on Thu Dec 12 07:33:23 2019
Proceed anyway? (y,N) y
Discarding device blocks: done                            
Creating filesystem with 15591936 4k blocks and 3899392 inodes
Filesystem UUID: 96f86d90-5f6c-4209-9c81-e72b861f7b64
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
        4096000, 7962624, 11239424

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (65536 blocks): done
Writing superblocks and filesystem accounting information: done   

localhost / # fdisk -l
Disk /dev/loop0: 7.3 GiB, 7876964352 bytes, 15384696 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop1: 407.5 MiB, 427294720 bytes, 834560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop2: 4 KiB, 4096 bytes, 8 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop3: 4 KiB, 4096 bytes, 8 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop4: 49.6 MiB, 52006912 bytes, 101576 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mmcblk1: 29.1 GiB, 31268536320 bytes, 61071360 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mmcblk1boot1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mmcblk1boot0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/dm-0: 1.9 GiB, 1992294400 bytes, 486400 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/mapper/encstateful: 7.3 GiB, 7876964352 bytes, 15384696 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mmcblk0: 59.5 GiB, 63864569856 bytes, 124735488 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
localhost / # umount /dev/mmcblk0
umount: /dev/mmcblk0: not mounted.
localhost / # mkfs -t ext4 /dev/mmcblk0
mke2fs 1.44.5 (15-Dec-2018)
/dev/mmcblk0 contains a ext4 file system
        created on Thu Dec 12 08:30:06 2019
Proceed anyway? (y,N) y
Discarding device blocks: done                            
Creating filesystem with 15591936 4k blocks and 3899392 inodes
Filesystem UUID: 2be9dd52-766f-4afa-96fa-5f245c5c3fbd
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
        4096000, 7962624, 11239424

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (65536 blocks): done
Writing superblocks and filesystem accounting information: done   

localhost / # sudo sh -e ~/Downloads/crouton -r DISTRO -t xiwi,ENVIRONMENT -p '/media/removable/SD Card'
sh: 0: Can't open /root/Downloads/crouton
localhost / # sudo sh -e /Downloads/crouton -r DISTRO -t xiwi,ENVIRONMENT -p '/media/removable/SD Card'
sh: 0: Can't open /Downloads/crouton
localhost / # sudo sh -e /Downloads/crouton -r crouton -t xiwi,unity -p '/media/removable/SD Card'
sh: 0: Can't open /Downloads/crouton
localhost / # sudo sh -e /Downloads/crouton -r crouton -t xiwi,unity -p '/media/removable/SD Card'
sh: 0: Can't open /Downloads/crouton
localhost / # sudo sh -e ~/Downloads/crouton -r crouton -t xiwi,unity -p '/media/removable/SD Card'
sh: 0: Can't open /root/Downloads/crouton
localhost / # sudo sh -e ~/Downloads/crouton -r crouton -t xiwi,unity -p '/media/removable/SD Card'
sh: 0: Can't open /root/Downloads/crouton
localhost / # sudo sh -e ~/home/chronos/user//Downloads/crouton -r crouton -t xiwi,unity -p '/media/removable/SD Card'
sh: 0: Can't open /root/home/chronos/user//Downloads/crouton
localhost / # sudo sh -e /home/chronos/user//Downloads/crouton -r crouton -t xiwi,unity -p '/media/removable/SD Card'
sh: 0: /home/chronos/user//Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
Downloading latest crouton installer...
################################################################################################################################################ 100.0%################################################################################################################################################ 100.0%
/media/removable/SD Card is not a valid prefix
localhost / # sudo sh -e /home/chronos/user//Downloads/crouton -r crouton -t xiwi,unity -p '/media/removable/PP'
sh: 0: /home/chronos/user//Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
crouton does not belong to any supported distribution.
localhost / # sudo sh -e /home/chronos/user//Downloads/crouton -r chroot -t xiwi,unity -p '/media/removable/PP'
sh: 0: /home/chronos/user//Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
chroot does not belong to any supported distribution.
localhost / # sudo sh -e /home/chronos/user//Downloads/crouton -r xenial -t xiwi,unity -p '/media/removable/PP'
sh: 0: /home/chronos/user//Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/media/removable/PP/chroots/xenial is not an ext filesystem.
localhost / # sudo sh -e /home/chronos/user//Downloads/crouton -r trusty -t xiwi,unity -p '/media/removable/PP'
sh: 0: /home/chronos/user//Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/media/removable/PP/chroots/trusty is not an ext filesystem.
localhost / # sudo sh -e /home/chronos/user//Downloads/crouton -r xenial -t xiwi,unity -p '/media/removable/PP'
sh: 0: /home/chronos/user//Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/media/removable/PP/chroots/xenial is not an ext filesystem.
localhost / # mkfs xenial -p /media/removable/PP/chroots
mkfs.ext2: invalid option -- 'p'
Usage: mkfs.ext2 [-c|-l filename] [-b block-size] [-C cluster-size]
        [-i bytes-per-inode] [-I inode-size] [-J journal-options]
        [-G flex-group-size] [-N number-of-inodes] [-d root-directory]
        [-m reserved-blocks-percentage] [-o creator-os]
        [-g blocks-per-group] [-L volume-label] [-M last-mounted-directory]
        [-O feature[,...]] [-r fs-revision] [-E extended-option[,...]]
        [-t fs-type] [-T usage-type ] [-U UUID] [-e errors_behavior][-z undo_file]
        [-jnqvDFSV] device [blocks-count]
localhost / # mkfs xenial  /media/removable/PP/chroots
mke2fs 1.44.5 (15-Dec-2018)
mkfs.ext2: invalid blocks '/media/removable/PP/chroots' on device 'xenial'
localhost / # mkfs xenial -t /media/removable/PP/chroots
mkfs: failed to execute mkfs./media/removable/PP/chroots: No such file or directory
localhost / # mkfs xenial -t /media/removable/PP/chroots
mkfs: failed to execute mkfs./media/removable/PP/chroots: No such file or directory
localhost / # sudo sh -e /home/chronos/user//Downloads/crouton -r xenial -t xiwi,unity -p '/media/removable/PP'
sh: 0: /home/chronos/user//Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/media/removable/PP/chroots/xenial is not an ext filesystem.
localhost / # sudo deit -all
sudo: deit: command not found
localhost / # sudo edit -all
sudo: edit: command not found
localhost / # sudo edit-chroot -all
sudo: edit-chroot: command not found
localhost / #

**Comment by DennisLfromGA** [comment]
@austinttt,

It looks like you were able to format your external media as an ext4 file system so that step is complete.

But, for one, you are trying to run the crouton installation commands as 'root' instead of 'chronos' which will fail since all of file structure is not in place. 
> sh: 0: Can't open /root/Downloads/crouton

And secondly, it is a dangerous practice to login as root since a lot of bad things can happen if you don't know what you're doing.

It is best to sign-in to your account and then open a `crosh` session using '<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>t</kbd>. Once you have the `crosh> ` prompt enter '`shell`' to get a bash shell session. Now you can prefix commands with `sudo` that require root premission but don't use it when it's not needed.

Next, make sure you've downloaded a fresh copy of the crouton installer and placed it in ~/Downloads, you can get it from this link: [https://goo.gl/fd3zc](https://goo.gl/fd3zc). Then install it with this command:

- `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`

You're command to install a crouton chroot will not work, as you've discovered. I'm not sure where you found that command but there are no crouton releases named DISTRO and there is no crouton target named ENVIRONMENT.
> localhost / # sudo sh -e ~/Downloads/crouton -r DISTRO -t xiwi,ENVIRONMENT -p '/media/removable/SD Card'

For a list of crouton supported releases, at the `chronos@localhost` prompt enter:
- `sudo crouton -r list`

For a list of crouton targets, at the `chronos@localhost` prompt enter:
- `sudo crouton -t list`

If you want to install the default 'xenial' release, the 'xiwi' xmethod, and a 'unity' desktop target and the directory '/media/removable/SD Card' points to a valid ext4 file system, try the following at the `chronos@localhost` prompt:

- `sudo crouton -t xiwi,unity -p '/media/removable/SD Card'`

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
The below wiki has updated to reflect the new method of installation & execution:
- https://github.com/dnschneid/crouton/wiki/How-To-Install-To-External-Drive

Closing. Please re-open if this issue is still a concern.
