### ISSUE TITLE
failed to upload 

### ISSUE THREAD

**Issue by Savage200x** [dnschneid/crouton#4184]
```
Please paste the output of the following command here: 
```
E: Package 'xbindkeys' has no installation candidate
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
chronos@localhost / $ 
#### Please describe your issue:
I input this first step and the out come was that of the output 

chronos@localhost / $ sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
sh: 0: /home/chronos/user/Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
Downloading latest crouton installer...
################################################################################################################################################ 100.0%################################################################################################################################################ 100.0%
WARNING: Signed boot verification is disabled; enabling it for security.
You can disable it again using: sudo crossystem dev_boot_signed_only=0
Installing kali-rolling-amd64 chroot to /usr/local/chroots/kali-rolling
Downloading bootstrap files...

#### If known, describe the steps to reproduce the issue:
how can i mitigate this or is there another way or input i have Acer chromebook spin 11 
i downloaded crouton and crouton extension i need assistance if any.

**Comment by DennisLfromGA** [comment]
Duping this to https://github.com/dnschneid/crouton/issues/4153#issuecomment-560190450
Check out that comment for a workaround.
