### ISSUE TITLE
I can't install Kali Linux in Chrome OS using crouton

### ISSUE THREAD

**Issue by finderos47** [dnschneid/crouton#4186]
I can't install Kali Linux in Chrome OS using crouton
GET AN ERROR:
Package xbindkeys is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'xbindkeys' has no installation candidate
Failed to complete chroot setup.

What I should to do? 

```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by rj45jack** [comment]
See here: 
https://github.com/dnschneid/crouton/issues/4153

**Comment by finderos47** [comment]
Thank You!

Jevgenijs Belanins
about.me/finderos47
+371 24947154


вс, 15 дек. 2019 г. в 00:40, DennisL <notifications@github.com>:
