### ISSUE TITLE
Choppy Framerate in certain programs

### ISSUE THREAD

**Issue by ascent08** [dnschneid/crouton#4190]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,lxde
host: version 12607.58.0 (Official Build) beta-channel gnawty 
kernel: Linux localhost 4.4.196-16940-geab5e6346fdb #1 SMP PREEMPT Thu Dec 12 22:50:28 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
Certain programs (mainly Minecraft, although I have experienced this with OBS Studio and SuperTux) have a visual bug in which they are not properly displayed as of a recent beta channel update. It causes a low, choppy framerate and is very inconvenient, although the programs are somewhat useable. I have tried deleting the chroot and installing a new one, using a different desktop environment and even powerwashing my Chromebook, but that does not work.

Below I have included a screenshot of the Minecraft title screen with the display bug I am have trouble with.
![Screenshot 2019-12-20 at 17 59 32](https://user-images.githubusercontent.com/59103728/71300494-8c846a00-2352-11ea-962b-d073ce3bdf04.png)

I would really appreciate any help with this!

**Comment by itacotaco** [comment]
I'm also having the choppy framerate issue!

**Comment by n2Box** [comment]
What's the likelihood of helping me get my medications and money from
Toronto which have been stollen for over two years now as an attempt to
punish me for trying to get back on my feet??

Derek Dwinnell
2899434291

**Comment by brandinchiu** [comment]
I've seen similar issues with Slack, and Postman on Xenial, and other visual artifacts upon first-launch of Chrome within the chroot.

**Comment by Underscore13** [comment]
Update: I tried to boot Minecraft up, and while it was loading I switched back to Chrome OS and a page that was running in the background (Discord) displayed an error message saying it ran out of memory. It seems as though starting up prgrams that I've never had trouble with eats up more memory than it used to.

**Comment by Peowraaku** [comment]
rebooting for the Chrome OS 78 update broke my xenial/XFCE on acer spin 13. i tried crouton -u already. the steam UI causes full screen tearing when looking at animated images in the store. chrome has lots of visual artifacts on launch. FTL, a native linux game, has bad screen tearing. Heat Signature, a proton/wine game, doesn't seem to be affected at all. glxgears runs and looks fine. no issues prior to the update. other desktop apps i've looked at are fine in xfce.

**Comment by DennisLfromGA** [comment]
When you run into problems after a CrOS update it's always a good idea to update your chroot just to see if that fixes it as @Peowraaku did. 'course it doesn't *always* help. ;-)

There were a lot of GPU issues fixed/merged between [78.0.3904.106 & 79.0.3945.86](https://chromium.googlesource.com/chromium/src/+log/78.0.3904.106..79.0.3945.86?n=10000), maybe it'd be good to file a report the next time you see these glitches via the key-combo <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> so the CrOS devs can see what's happening - it's a start.

Maybe the crouton devs can come up with something if they can repo it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Underscore13** [comment]
While the framerate issue seems much better now, the screen tearing issue still remains. I'd file a report, but I don't know how to describe it without mentioning crouton. Should I mention crouton in the report?

**Comment by DennisLfromGA** [comment]
@Underscore13,

Yes, I would mention crouton in the report. crouton runs in CrOS unlike Crostini so it's an integral part of it. When filing reports in Crostini they recommend you include `#crostini` in the description so I don't see anything wrong with doing that for crouton too if you want. Of course the crostini author does mention this:

> Crostini is an official project within Chromium OS to bring the Linux shell and apps to the platform in verified mode with clean integration, multi-layered security, and all the polish you expect from Chromium OS proper.

> That means compared to crouton, Crostini has official support, competent engineers, and code that looks a little less like ramen. crouton, in its defense, has wider device compatibility, enables direct hardware access, and is named after an objectively tastier bread-based food item.

But if it's an issue with Chrome OS then it should be reported.

*Hope this helps,*
-**DennisLfromGA**

**Comment by brandinchiu** [comment]
Bumping for visibility, just in case there's something that can be done from the Crouton end while we wait for a fix from Google:

![](https://i.imgur.com/mdyNmKL.png)

**Comment by XiekenPlayz** [comment]
I still have the framerate problem, and the screen tearing occasionally happens when im using discord, but its not that much of a problem

**Comment by FadeShock** [comment]
Doesn't seem like there's a solution besides dealing with it. Oh well.

**Comment by FadeShock** [comment]
I found a small fix to the screen tearing: Its xenial. Try using another chroot, like Unity, which seems to work fine for me as of the time I am typing this.

**Comment by brandinchiu** [comment]
> I found a small fix to the screen tearing: Its xenial. Try using another chroot, like Unity, which seems to work fine for me as of the time I am typing this.

I'm using Unity and the issue is still very pervasive.

**Comment by FadeShock** [comment]
Hmm... Probably just me then. 
I'm running Unity on the Stable channel.

**Comment by NGamma** [comment]
Same here. Steam flickering, games freezing... since last chromeOS update. 
I'm using xenial and already updated the crouton installer with no improvement.

**Comment by crazyeights** [comment]
This seems to happen when I change the Intel xorg config to SNA and tearfree true (essentially the crouton Intel conf file).  Chromium has numerous artifacts along with Steam and Visual Studio Code.  Tested on Ubuntu Bionic and Debian Buster, all desktops.  Without this setting change, all desktops have terrible lag but display fine.  I would try Xenial but I'll have to compile Mesa drivers for Amber Lake support.

**Comment by NGamma** [comment]
Updating to ChromeOS Version 81.0.4028.0 (Official Build) dev (64-bit) does not fix it... 
Can I revert to 78?

**Comment by Underscore13** [comment]
@NGamma I don't think you can, actually.

**Comment by NGamma** [comment]
@Underscore13 That's disturbing, isn't it?

**Comment by brandinchiu** [comment]
Theoretically makes ChromeOS easier to maintain.

**Comment by Underscore13** [comment]
Yeah, I think that's the reason behind that. I have reverted back to an older version of Chrome OS before when using a recovery key, then had to update a whole lot to get to the then-current version. Maybe there is an unofficial way to revert back to a previous update, but personally I wouldn't recommend it

**Comment by NGamma** [comment]
@brandinchiu Theoretically, not been able to disable updates and not been able to revert those updates makes the user unable to fix the problem immediately... Honestly, I can't think of a more distopian OS (it's even worse than Windows Vista)

**Comment by NGamma** [comment]
This is from: https://www.chromium.org/chromium-os/chromium-os-faq

> Chromium OS FAQ
> What's the difference between Chromium OS and Google Chrome OS?
> **Chromium OS does not auto-update by default (so that changes you may have made to the code are not blown away)**, whereas Google Chrome OS seamlessly auto-updates so that users have the latest and greatest features and fixes.
> Google Chrome OS is supported by Google and its partners; Chromium OS is supported by the open source community.

**Comment by NGamma** [comment]
@Underscore13 Actually I've found that you can install any Chromium OS build you want from here:
https://arnoldthebat.co.uk/wordpress/chromium-os/

**Comment by Underscore13** [comment]
Right, I forgot about that.

**Comment by kketchmark** [comment]
I also had this issue with Chrome running in the Crouton Ubuntu system.  I Disabled Use hardware acceleration when available in the Chrome Browser.   Chrome Browser in Crouton/Ubuntu is working great again.

**Comment by life2977** [comment]
Since a month has passed, I'm really curious/hopeful if anyone has figured something out to fix the tearing and fps drops. If anything, I'd bump this up lmao.

**Comment by OKRD342** [comment]
Is there any fix for this yet? I used to love using crouton's hardware acceleration but it seems xorg has just been broken since December.

**Comment by QwertzyIsCool** [comment]
Disable Hardware acceleration on minecraft
