### ISSUE TITLE
I cant boot into ubuntu on a chromebook after a crash.

### ISSUE THREAD

**Issue by isaiahhoyt** [dnschneid/crouton#4192]
```
Please paste the output of the following command here: sudo edit-chroot -all

chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...


```

#### Please describe your issue:

I am unable to boot back into ubuntu, my computer crashed and now I am unable to.

#### If known, describe the steps to reproduce the issue:

Here's the output 

sudo startxfce4
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-128-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.196-16940-geab5e6346fdb #1 SMP PREEMPT Thu Dec 12 22:51:14 PST 2019 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4710400 verity payload=PARTUUID=295fa35d-2966-aa4c-8f34-1ec08d505dbb/PARTNROFF=1 hashtree=PARTUUID=295fa35d-2966-aa4c-8f34-1ec08d505dbb/PARTNROFF=1 hashstart=4710400 alg=sha256 root_hexdigest=6b67ebe4a88c1b22bb438abaf778f19aae06faf9bea8f90c9b5c6e694dd071d0 salt=52a9fc051381a2b6663cac6a34eccb0ad405d2838d54a942c0aeb8ee33fdfa38" noinitrd vt.global_cursor_default=0 kern_guid=295fa35d-2966-aa4c-8f34-1ec08d505dbb add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic disablevmx=off  
Build Date: 10 August 2018  09:33:05AM
xorg-server 2:1.18.4-0ubuntu0.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.0.log", Time: Sun Dec 22 16:35:04 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
sh: 1: host-dbus: not found
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.0.log" for additional information.
(EE) 
sh: 1: host-dbus: not found
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@isaiahhoyt,

See if these troubleshooting steps will help:
- https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
