### ISSUE TITLE
Failed to run debootstrap

### ISSUE THREAD

**Issue by EmattpoYou** [dnschneid/crouton#4193]
`chronos@localhost / $ sudo edit-chroot -all
/media/removable/SD Card/chroots not found.`

No matter what I do, on installation I get:
```
`chronos@localhost / $ sudo sh -e /usr/local/bin/crouton -r bionic -t xiwi,gnome -p 

'/media/removable/SD\ Card' -m bionic

WARNING: bionic is an unsupported release.

You will likely run into issues, but things may work with some effort.

Press Ctrl-C to abort; installation will continue in 5 seconds.

Installing bionic-amd64 chroot to /media/removable/SD\ Card/chroots/bionic

Downloading bootstrap files...

W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg

I: Retrieving InRelease 

E: unknown location bionic/dists/bionic/InRelease

debootstrap error log:

Failed to run debootstrap.`
```

I do not know how to reproduce.

**Comment by DennisLfromGA** [comment]
@EmattpoYou,

Maybe it's the debootstrap mirror that's the problem. You might try adding crouton's '`-m`' option and a mirror from [https://launchpad.net/ubuntu/+archivemirrors](https://launchpad.net/ubuntu/+archivemirrors) and see if that helps.

Also, the installation command you're using is very old and not correct, you now need to install `crouton` and run it differently. See the [README](https://github.com/dnschneid/crouton/blob/master/README.md#usage) for more about that.

*Hope this helps,*
-**DennisLfromGA**

**Comment by n2Box** [comment]
What's the likelihood of helping me get my medications and money from
Toronto which have been stollen for over two years now as an attempt to
punish me for trying to get back on my feet??

Derek Dwinnell
2899434291

**Comment by DennisLfromGA** [comment]
For a workaround see: https://github.com/dnschneid/crouton/issues/4106#issuecomment-526027391
