### ISSUE TITLE
Chronos command not found

### ISSUE THREAD

**Issue by Jacquelinemarie** [dnschneid/crouton#4194]
`sudo install-Dt/usr/local/bin-m755~/Downloads/crouton`

I'm just starting out in programming and stuff but I'm hopelessly attempting to install Linux on my Chromebook. I've powerwashed and entered Developer Mode. I've typed the code into the shell after downloading crouton and it still tells me command not found. At first it kept asking for a password and I powerwashed it again and that fixed that but now it doesn't even recognize the code anymore. I've typed it in every possible way. I honestly have no idea what else to do. I'm slowly descending into madness. Please help. 
![Screenshot 2019-12-22 at 6 30 45 PM](https://user-images.githubusercontent.com/25214424/71330352-d6538880-24e9-11ea-81e5-c0aa2415d857.png)

**Comment by ZycroNeXuS** [comment]
If I'm reading it right, it looks like you're missing some spaces:

`sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`

That should do it.

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by Jacquelinemarie** [comment]
Thank you so much. I figured it out like 20 minutes later and nearly threw my laptop across the room after I realized I missed a couple spaces. Thanks again!

**Comment by n2Box** [comment]
What's the likelihood of helping me get my medications and money from
Toronto which have been stollen for over two years now as an attempt to
punish me for trying to get back on my feet??

Derek Dwinnell
2899434291
