### ISSUE TITLE
No sound on Kali-Rolling

### ISSUE THREAD

**Issue by i6x** [dnschneid/crouton#4196]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: audio,xfce,core
host: version 12499.66.0 (Official Build) stable-channel kefka 
kernel: Linux localhost 3.18.0-19748-gc785fae00b84 #1 SMP PREEMPT Thu Nov 14 23:06:35 PST 2019 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
Installed Kali with the audio plugin today, there is no audio output at all. Audio worked fine on previous Xenial chroots before.

#### If known, describe the steps to reproduce the issue:
`crouton -r kali-rolling -t xfce,audio,core`

**Comment by DennisLfromGA** [comment]
This may *still* be a lingering bug on kali releases.
Bottom line, as a crouton dev puts it: *pulseaudio on kali is indeed broken.*

Closing and duping this issue to: https://github.com/dnschneid/crouton/issues/2039

*Hope this helps,*
-**DennisLfromGA**
