### ISSUE TITLE
CRAS Compiling error - sh: 119: Bad substitution

### ISSUE THREAD

**Issue by finderos47** [dnschneid/crouton#4199]
```
sudo edit-chroot -all
name: audio
Enter encryption passphrase for audio:
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/audio...
crouton: version 1-20190902190258master:9a594a66
release: kali-rolling
architecture: amd64
targets: core,xiwi
host: version 78.4.3 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 4.19.65+ #2 SMP Fri Nov 22 23:42:37 UTC 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/audio...
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
Creating hwaudio group with GID 18...
Changing audio GID from 29 to 600...
Changing cdrom GID from 24 to 19...
Creating crouton group with GID 1001...
Creating unassociated devbroker-access group...
Changing floppy GID from 25 to 11...
Creating i2c group with GID 404...
Changing input GID from 105 to 222...
Creating serial group with GID 402...
Changing plugdev GID from 46 to 85...
Changing uucp GID from 10 to 14...
Changing video GID from 44 to 27...
Moving sudo GID from 27 to 28...
Creating wayland group with GID 601...
crouton: version unknown
release: unknown
architecture: unknown
targets: audio,core
host: version 78.4.3 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 4.19.65+ #2 SMP Fri Nov 22 23:42:37 UTC 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: kaliz
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/kaliz...
name: kiwi
Enter encryption passphrase for kiwi:
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/kiwi...
crouton: version 1-20190902190258master:9a594a66
release: xenial
architecture: amd64
targets: xiwi
host: version 78.4.3 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 4.19.65+ #2 SMP Fri Nov 22 23:42:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kiwi...
name: new
Enter encryption passphrase for new:
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/new...
crouton: version 1-20190902190258master:9a594a66
release: xenial
architecture: amd64
targets: xfce
host: version 78.4.3 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 4.19.65+ #2 SMP Fri Nov 22 23:42:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/new...
name: xenial
Enter encryption passphrase for xenial:
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258master:9a594a66
release: xenial
architecture: amd64
targets: unity,xfce
host: version 78.4.3 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 4.19.65+ #2 SMP Fri Nov 22 23:42:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
name: xfcexenial
Enter encryption passphrase for xfcexenial:
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xfcexenial...
crouton: version 1-20190902190258master:9a594a66
release: xenial
architecture: amd64
targets: xfce
host: version 78.4.3 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 4.19.65+ #2 SMP Fri Nov 22 23:42:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xfcexenial...
name: xiwi
Enter encryption passphrase for xiwi:
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/xiwi...
crouton: version 1-20190902190258master:9a594a66
release: kali-rolling
architecture: amd64
targets: xorg,xiwi
host: version 78.4.3 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 4.19.65+ #2 SMP Fri Nov 22 23:42:37 UTC 2019 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xiwi...
```

#### Please describe your issue:

Try to install any release with crouton getting CRAS Compiling error: 
Compiling CRAS (i386)...
sh: 119: Bad substitution

Please help fix this or how I can pass this error?

**Comment by lcazan** [comment]
I had the same problem on Cloudready 78.4, but found a workaround.

I backed up my data then installed CloudReady 72.4 from getmyos.com. I installed crouton and created a chroot without any problems, then upgraded CloudReady to the latest version.

However I forgot to install the xfce target. When I tried updating the chroot to include the xfce target, it still gave me the error, so make sure to install all the targets you need before upgrading. As a workaround, I entered the chroot, and installed xubuntu-desktop using apt-get, and everything works fine.

**Comment by lcazan** [comment]
I had the same problem on Cloudready 78.4, but found a workaround.

I backed up my data then installed CloudReady 72.4 from getmyos.com. I installed crouton and created a chroot without any problems, then upgraded CloudReady to the latest version.

However I forgot to install the xfce target. When I tried updating the chroot to include the xfce target, it still gave me the error, so make sure to install all the targets you need before upgrading. As a workaround, I entered the chroot, and installed xubuntu-desktop using apt-get, and everything works fine.

**Comment by finderos47** [comment]
Anybody know how to make crouton usable again?

**Comment by toutheif** [comment]
I also encountered the same problem, if the solution is hoped to be notified.

**Comment by Quacksicle** [comment]
i have encountered the same problem also, hope they fix this issue...

**Comment by finderos47** [comment]
+1

Jevgenijs Belanins
about.me/finderos47
+371 24947154


пн, 13 янв. 2020 г. в 07:29, Quacksicle <notifications@github.com>:

**Comment by toutheif** [comment]
According to two friends, I tried to refresh the system, found that version 79 is a normal installation, only after 80 will appear that error, hope to fix it early. don't know what kind of situation is installed and then upgrading friends is？

**Comment by drinkcat** [comment]
the only recent change in Makefile.am is this:
2cb59d52fe1d1836bb311b185546c24d5f6e6f8f

So I'm going to assume something is going wrong there.

**Comment by drinkcat** [comment]
( . ~/chroagh/crouton/installer/prepare.sh; convert_automake ) | sh -s -e
sh: line 119: WITH_SYSTEM_RUST: invalid indirect expansion

Was looking at the wrong `Makefile.am`.

Basically our magic automake converter does not know how to do with this if statement:
if !WITH_SYSTEM_RUST

(added 522b37417 https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1968111 )

**Comment by DennisLfromGA** [comment]
All,

Please download a fresh **[crouton installer](https://goo.gl/fd3zc)** and update your chroot(s).
A fix has been merged for the [CrOS CRAS changes](https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1968111) now.

*Hope this helps,*
-**DennisLfromGA**
