### ISSUE TITLE
Any solutions for audio buttons, Delete key and other keyboard issues?

### ISSUE THREAD

**Issue by FossPrime** [dnschneid/crouton#42]
I can't seem to find anyone working on a fix. Any suggestions on mapping these out? Particularly volume, brightness, keyboard backlight and the delete key.

**Comment by jamesMFelder** [comment]
Thanks for the help. Just set up the keyboard shortcuts and they seem to be working.

**Comment by n2Box** [comment]
What's the likelihood of helping me get my medications and money from
Toronto which have been stollen for over two years now as an attempt to
punish me for trying to get back on my feet??

Derek Dwinnell
2899434291
