### ISSUE TITLE
No Extension Icon on Shelf (Pixel Slate)

### ISSUE THREAD

**Issue by ukgda** [dnschneid/crouton#4200]
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20190902190258~master:9a594a66
release: bionic
architecture: amd64
xmethod: xiwi
targets: xfce,touch,cli-extra,xiwi,audio,keyboard,core
host: version 12607.58.0 (Official Build) stable-channel nocturne 
kernel: Linux localhost 4.4.196-16940-geab5e6346fdb #1 SMP PREEMPT Thu Dec 12 22:55:39 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

A minor issue... but when my bionic chroot is running in a chrome window (xiwi) on my Pixel Slate there is no 'C' icon on the shelf. Where it should be there is a small underline to indicate there is something there and the area is clickable but there is no icon. On my old Samsung chromebook there is an icon.

As I say... a minor issue. All else works great, but it would be nice to have the icon back.

(I have removed and reinstalled the extension without success)

**Comment by phummel** [comment]
I have the same thing on my Samsung CBP running stable Version 79.0.3945.86 (Official Build) (64-bit) Crouton extension version 2.5.2

**Comment by DennisLfromGA** [comment]
IIUC, when you start a desktop using the xiwi xmethod in a tab (-X xiwi-tab) you won't get the crouton extension icon on the shelf but you *should* still be able to switch to/from it using the drop-down menu in crouton extension icon in the browser toolbar.

When you start a desktop using the xiwi xmethod in a window (-X xiwi) or in full screen (-X xiwi-fullscreen) 
 you *should* get the crouton extension icon on the shelf *and* you should be able to switch to/from it using the drop-down menu in crouton extension icon in the browser toolbar.

*Hope this helps,*
-**DennisLfromGA**

**Comment by ukgda** [comment]
Thank you @DennisLfromGA for the clarification.

The chroot opens in a window which when I shrink that window to see the shelf there is no icon there. All that is missing is the icon because the 'hotspot' is there - the space is still clickable to get to the chroot window - but just no 'C' icon.

As you say it is also accessible via the extension at the top right of the browser.

Minor, minor issue. Just a niggle.  Thanks for your help.

My version of chrome that it fails on is 79.0.3945.123. (my very old Chromebook on which it works is chrome 65.0.3325.209)

**Comment by DennisLfromGA** [comment]
Y'all,

> ... there is no 'C' icon on the shelf.

You *are* correct, sorry I misread the real issue. You can see *something* on the taskbar/shelf but it appears to be empty with no 'C' like there used to be. It still switches as you say but you can't really tell it's the crouton extension icon.

Maybe the crouton devs can figure out what happened and fix it, I'll let you know if I hear anything about it.

*Hope this helps,*
-**DennisLfromGA**
