### ISSUE TITLE
newbie issue, the command shell keeps giving unknown command

### ISSUE THREAD

**Issue by kimberlimonade** [dnschneid/crouton#4201]
#### Please describe your issue:

I put my asus chrome flipbook in developer mode, downloaded crouton and the extension. Im trying to enter the first command, shell, but it keeps giving a unknown command response. 
Im really not sure what im doing wrong, Help!

thank you

**Comment by DennisLfromGA** [comment]
@kimberlimonade,

Once you're in Developer mode you have access to the bash shell.

1. Sign-in and then press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>t</kbd> to get a `crosh> ` prompt.
2. At the `crosh> ` prompt type `shell` and press the <kbd>enter</kbd> key.

Once you have a bash shell prompt you can  enter the commands to install `crouton` and other things.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
