### ISSUE TITLE
Chinese Localization of README

### ISSUE THREAD

**Issue by Mrright024** [dnschneid/crouton#4202]
Crouton helps me a lot, but I wanna help more Chinese know about how to use it. So I plan to translate **README and some of the Wiki** into Chinese.  Considering about the Copyright ("All rights reserved" says README) , is it possible for me to do that?

**Comment by dnschneid** [comment]
That would be great!

You can either propose a README.zh.md with your translation (and [sign the CLA](https://cla.developers.google.com/clas/new?kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE)), or you can just make a translation of the README in a wiki page.

For the wiki pages, I guess just make a new page with the same subject and (zh) or (中文) or whatever appended.

**Comment by Jamie-Ya** [comment]
Thx,This isgreat i need

**Comment by DeletOtherSmokedSalmonGi-ImSmokedSalmon** [comment]
GAY
