### ISSUE TITLE
Crouton being nearly unusable after the latest chromeOS update

### ISSUE THREAD

**Issue by XiekenPlayz** [dnschneid/crouton#4203]
```
Please paste the output of the following command here: sudo edit-chroot -all
```name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12607.58.0 (Official Build) stable-channel coral 
kernel: Linux localhost 4.4.196-16940-geab5e6346fdb #1 SMP PREEMPT Thu Dec 12 22:49:50 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue: After my Chromebook died a couple of days ago, crouton has become nearly unusable. Chrome now runs terribly on crouton and has visual artifacts on launch. Minecraft now runs at a consistent 7fps, no matter what settings I use. It is most likely a memory issue, since whenever I go into task manager, I am usually at about 80% memory usage, and 100% cpu usage just my using the minecraft menu, because everything now takes loads of memory. I am quite certain that this is caused by the update, since my friend is also experiencing this problem.


#### If known, describe the steps to reproduce the issue:

**Comment by Underscore13** [comment]
I mentioned something similar in #4190 , could you provide screenshots?

**Comment by XiekenPlayz** [comment]
`[
![Minecraft 1 8 9_018](https://user-images.githubusercontent.com/53277907/72197951-6481a700-33e4-11ea-8f34-277d899c2f81.png)
](url)`

**Comment by XiekenPlayz** [comment]
![Minecraft 1 8 9_018](https://user-images.githubusercontent.com/53277907/72197959-80854880-33e4-11ea-95ec-82129a241503.png)

**Comment by XiekenPlayz** [comment]
The visual artifacts with chrome suddenly dissapeared after i restarted my computor

**Comment by finderos47** [comment]
Can anybody help me to understand how to work with crouton after ChromeOS update I have get an error while installing xfce, error compiling CRAS. Anybody can help?

**Comment by Underscore13** [comment]
@finderos47 try using this part of the README: https://github.com/dnschneid/crouton#a-new-version-of-crouton-came-out-my-chroot-is-therefore-obsolete-and-sad

@XiekenPlayz interesting, did you get any notifications about a chrome os update before restarting your chromebook?

**Comment by gerardwr** [comment]
@finderos47 
Installed my Chromebook today fresh in Developer Mode.

Installing Crouton I get the ¨bad substitution¨ error while compilimg CAS also.
```
Compiling CRAS (native)...
sh: 119: Bad substitution
Failed to complete chroot setup.
```

And tried your suggestion in the README, but the error remains :-(
```
sudo crouton -u -n xenial
```
Any other suggestions I can try?

**Comment by XiekenPlayz** [comment]
@Underscore13 no i did not

**Comment by XiekenPlayz** [comment]
ignore that, I misclicked. And no, i didnt recieve a notification about an update, it could have just been a temporary error

**Comment by XiekenPlayz** [comment]
@Underscore13 can you please check if this happens to you too? it says it isn't able to open /dev/zram, and i think that may be associated with the overly high menory usage...

![image](https://user-images.githubusercontent.com/53277907/72228529-9d488a00-3564-11ea-9d14-b4207324232a.png)

**Comment by Underscore13** [comment]
no, that doesn't show up for me. When exactly does this happen?

**Comment by XiekenPlayz** [comment]
Showed up for me when I launched crouton and switched back to crOS

**Comment by FadeShock** [comment]
If it has a problem with compiling the CRAS, simply put your chromebook back into the Stable channel.

**Comment by XiekenPlayz** [comment]
@FadeShock it's not a problem compiling the cras. 

@Underscore13 can you please tell me all the steps you did to fix the framerate problem with your apps

**Comment by Underscore13** [comment]
I haven't fixed it, at this point I'm just dealing with it.

**Comment by Underscore13** [comment]
I do recommend submitting a bug report to the Chrome OS devs though, scroll down in #4190 for a clearer explanation

**Comment by DennisLfromGA** [comment]
All,

If you're still running into the CRAS compile error please download a fresh **[crouton installer](https://goo.gl/fd3zc)** and update your chroot(s).
A fix has been merged for the [CrOS CRAS changes](https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/1968111) now.

*Hope this helps,*
-**DennisLfromGA**

**Comment by XiekenPlayz** [comment]
@DennisLfromGA  Uhh. Im sorry for asking a month later, but nothing helped. Crouton has been performing worse and worse, and I don't have any solutions. Can you please help me with my issue. Crouton isn't usable anymore, this includes games, discord, and chrome. They all run at terribly low fps, and i cannot use them.

**Comment by finderos47** [comment]
Everything workjs fine with crouton etc.

try this:
sudo crouton -r kali-rolling -t xfce -n kali -e


Jevgenijs Belanins
about.me/finderos47
+371 24947154


пт, 14 февр. 2020 г. в 04:32, XiekenPlayz <notifications@github.com>:

**Comment by XiekenPlayz** [comment]
@finderos47 Everything worked on the msot part, chromium was much smoother, but I cant download anything on chromium. It just says "error, download cancelled" Any ideas to help?

**Comment by finderos47** [comment]
@XiekenPlayz try to reinstal or format home partition

Jevgenijs Belanins
about.me/finderos47
+371 24947154


вс, 16 февр. 2020 г. в 05:27, XiekenPlayz <notifications@github.com>:

**Comment by XiekenPlayz** [comment]
@finderos47 how do you do that?

**Comment by RedCMD** [comment]
Can confirm the exact same problem
Minecraft now instantly crashes in KDE Debian Jessie and runs at 7fps in xfce4 Ubuntu Xenial no matter what settings I use
There are small visual bugs (black triangles) in the top left corner
This happened after a ChromeOS update. Which one I don't know (but was a long time ago)
