### ISSUE TITLE
mouse gets stuck

### ISSUE THREAD

**Issue by mandar1jn** [dnschneid/crouton#4206]
when closing my chromebook and opening it while in linux it opens chrome, but my mouse gets stuck in linux. I first have to switch back to linux to get control of my mouse and then back to chrome

**Comment by DennisLfromGA** [comment]
> when closing my chromebook and opening it while in linux it opens chrome, but my mouse gets stuck in linux.

Well, don't do that. ;-)

Seriously, try toggling <kbd>fullscreen [ ] </kbd> on/off and see if that works and is easier & quicker.

*Hope this helps,*
-**DennisLfromGA**
