### ISSUE TITLE
Screen flickers when using Steam or Minecraft

### ISSUE THREAD

**Issue by FadeShock** [dnschneid/crouton#4207]
So, there isn't anything to copy and paste, but every time I open up Steam or Minecraft, the screen just flickers continuously. This only seems to apply to Minecraft, Steam, and any games downloaded off of Steam. It used to work fine, but now... It's just really annoying, especially since the flickering can become so terrible that games become unplayable. 
Any ideas on how to solve this?
I am using a Hewlett-Packard Chromebook, Model Name: CHELL with and m7 core. It is also on the Stable channel.

**Comment by FadeShock** [comment]
Oh, and Steam Proton won't work.

**Comment by Underscore13** [comment]
#4190 is an issue I made becuase I experience this myself, I recommend you go check that out.

**Comment by FadeShock** [comment]
Thank you.
