### ISSUE TITLE
Cant reset my password

### ISSUE THREAD

**Issue by RiversideRocks** [dnschneid/crouton#4210]
#### I am currently trying to install steam on my computer using crouton. I forgot the admin password and am unsure of how to reset it.
To install steam I used:

```
sudo apt install steam-installer
```

#### Is there a way to boot it in safe mode to reset the password?

**Comment by DennisLfromGA** [comment]
You can get into your chroot as root and then use the `passwd` command to reset the password using:
- `sudo enter-chroot -n [chrootname] -u root`

Note: substitute `[chrootname]` above with your chroot's actual name.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
