### ISSUE TITLE
`sudo startxfce4` causes system crash

### ISSUE THREAD

**Issue by zantetsuken88** [dnschneid/crouton#4212]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12607.82.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.149-13636-g9eade7219710 #1 SMP PREEMPT Fri Jan 10 00:14:58 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

Hi, I followed the basic instructions to install Ubuntu LTS with Xfce - however issuing the command `sudo startxfce4` results in a total crash. The screen switches to a garbled multicoloured mess, sometimes I have the cursor, sometimes I don't. Otherwise totally unresponsive and I have to power off the chromebook by holding down the power button. Could I have done something wrong?

**Comment by zantetsuken88** [comment]
![image](https://user-images.githubusercontent.com/19647883/72664333-838bc480-39f4-11ea-886a-b3f5210612ab.png)

**Comment by DennisLfromGA** [comment]
@zantetsuken88,

I'm afraid it *may* be an issue with your particular Chromebook being that it uses an AMD chip.
There are similar issues being reported about it, see below -
- Crouton screen refresh freezing #3992 (may have a video fix/workaround)
- Desktop freeze #4063 (has a workaround using xiwi)
- Distorted blocked screen on HP 14 AMD GPU A4 and A6 system holds. #4138

I'm going to close & dup this issue to #3992 so we can track any progress in one place.

*Hope this helps,*
-**DennisLfromGA**
