### ISSUE TITLE
No privilege on a fresh install

### ISSUE THREAD

**Issue by BlockHackTk** [dnschneid/crouton#4213]
On an Asus C301SA
In graphical mod (unity or mate or gnome...)
`sudo enter-chroot`
`startunity`

> name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xorg
targets: audio,extension,keyboard,x11,xorg,unity
host: version 12607.58.0 (Official Build) stable-channel terra 
kernel: Linux localhost 3.18.0-19838-gc647e70c954a #1 SMP PREEMPT Thu Dec 12 22:51:04 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### My issue:
I've been working around the problem for a long time, but I'd like to find a lasting solution and understand what's wrong.
After a fresh installation of ubuntu or debian, unlike a year ago, I have no more privileges when I want to change the language with UI or any application requiring root access in UI. 
And no password is required. 
How to fix this problem? 
I can provide a screenshot if needed

**Comment by BlockHackTk** [comment]
![Screenshot from 2020-01-20 14-46-30](https://user-images.githubusercontent.com/51758614/72731301-c041f200-3b93-11ea-895f-1a088d954225.png)
![Uploading Screenshot from 2020-01-20 14-46-03.png…]()

**Comment by BlockHackTk** [comment]
![Screenshot from 2020-01-20 14-46-30](https://user-images.githubusercontent.com/51758614/72731380-ea93af80-3b93-11ea-9488-894f23eecf5c.png)
![Screenshot from 2020-01-20 14-46-03](https://user-images.githubusercontent.com/51758614/72731384-ebc4dc80-3b93-11ea-93c0-c821ecf70752.png)

**Comment by BlockHackTk** [comment]
I can't launch `sudo startunity`

> Do not launch gnome-session-wrapper as root inside the chroot.
How to have root access after start the desktop?

**Comment by DennisLfromGA** [comment]
@BlockHackTk,

As noted when you tried to launch it with sudo, the start* scripts *inside* the chroot *should* be run as the normal user *without* root permissions.

You only need to prefix the start* scripts from *outside* the chroot in a CrOS shell session, as chronos.

You *may* be able to launch the Settings app using `gksudo` or `pkexec` if needed.

You *can* get into your chroot as root with `sudo enter-chroot -u root` but I would NOT recommend launching your desktop as root, it will most likely hose up many permissions.
If you do hose up your permissions sometimes the below commands issued *inside* the chroot will fix them:
```
sudo chown -R "1000:1000" /home/user
sudo chown -R "0:0" /root
exit
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by BlockHackTk** [comment]
@DennisLfromGA  thanx for your help

I fully understand that you don't have to launch ubuntu in sudo but usually when you launch the preferences for example to change the language, a box will ask you for your password, and this is what I'd like to correct.

I tried to run sudo `enter-chroot -u root` but it broke my chroot.

> chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
-su: 2: [: x: unexpected operator
-su: 2: [: x: unexpected operator
-su: 2: [: x: unexpected operator
-su: 2: [: x: unexpected operator

> (bionic)rom@localhost:~$ xinit

> (EE) Fatal server error:
(EE) Cannot move old log file "/tmp/Xorg.crouton.1.log" to "/tmp/Xorg.crouton.1.log.old"
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) 

I've also run those  `sudo chown -R "1000:1000" /home/user`
`sudo chown -R "0:0" /root`
`exit` 
but without results...

What could be my solution to install Bionic, and not to be obliged to use `gksudo ?

Also i'm trying install binic, I found the tutorial here:
>https://github.com/dnschneid/crouton/wiki/3-Steps-to-Install-Bionic-Beaver
 and it work 
I also install `mate-desktop-environment-extra` and to launch it I create the file `~/.xinitrcin` which I add the lines `exec mate-session

Thank you for your help.

Translated with www.DeepL.com/Translator (free version)

**Comment by BlockHackTk** [comment]
Good morning,
normally, in a linux desktop session, a window should open and ask me to type my "root" password to validate the changes.

**Comment by Carl393** [comment]
Did you try installing gksudo? It should ask you for root permission to change those things, you shouldnt need to start a unity session as superuser. it's actually not recommended
