### ISSUE TITLE
Unable to boot XFCE4. CTRL+ALT+FORWARD brings me to chromeos developer console

### ISSUE THREAD

**Issue by Anthem22** [dnschneid/crouton#4214]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 12607.82.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-19838-gc647e70c954a #1 SMP PREEMPT Thu Jan 9 23:22:43 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...```

#### Please describe your issue: 
sudo startxfce4 does not book to XFCE. Also, even before attempting 'start XFCE4' I'm able to CTRL+ALT+FORWARD which brings me to chromeos developer console where it's prompting me for localhost username and pw. Previously, this would only get me to XFCE after running 'startxfce4'


#### If known, describe the steps to reproduce the issue: 
Step 1: CTRL+ALT+FORWARD brings me to chromeos developer console
Step 2: Go to crosh, type shell, then type 'sudo startxfce4' 
Step 3: Receive the following:
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Jan 22 21:04:38 2020
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20190902190258~master:9a594a66
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 12607.82.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-19838-gc647e70c954a #1 SMP PREEMPT Thu Jan 9 23:22:43 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from https://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by Anthem22** [comment]
Troubleshooting efforts:
Tried this links here https://github.com/dnschneid/crouton/issues/687 and used CTRL+ALT+REFRESH but no change.

Worth noting that I was able to boot XFCE4 fine a week or so ago. I have since downloaded steam. I'll also add that my xenial extension JUST started working coincidentally the same tie this problem occurred. Previously I was not using XENIAL because it didn't appear to be working. I don't need XENIAL so perhaps I remove that if that's causing the problem. Just not quite sure how to do that. 

Lastly, if I turn XENIAL on, I'm able to launch XFCE in a window but I can't seem to launch it uhh, natively?  Sorry, new to linux and programming so excuse the poor language.

**Comment by DennisLfromGA** [comment]
@Anthem22,

> sudo startxfce4 does not book to XFCE. 

Your chroot is not up-to-date, please download a fresh crouton installer and update your chroot.
For further troubleshooting steps see -
- https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

> Also, even before attempting 'start XFCE4' I'm able to CTRL+ALT+FORWARD which brings me to chromeos developer console where it's prompting me for localhost username and pw. Previously, this would only get me to XFCE after running 'startxfce4'

Use <kbd>CTRL</kbd>+<kbd>ALT</kbd>**+**<kbd>**SHIFT**</kbd>+<kbd>FRWD/BKWD</kbd> to switch to/from Chrome OS.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Anthem22** [comment]
Thanks @DennisLfromGA . Will downloading the installer refresh my crouton completely? AKA will I lose any saved data/files?

**Comment by DennisLfromGA** [comment]
@Anthem22,

Downloading and installing the crouton installer in `/usr/local/bin/` will not do anything at all to your chroot(s). Doing a crouton update to your chroot should not cause any loss of your saved data/files.
However, it's *always* a good idea to make a chroot backup before doing any updates - just in case.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Anthem22** [comment]
@DennisLfromGA  - Finally able to give it a go. Tried this "sudo crouton -n chrootname -u" where chrootname = XENIAL. Ran the update and rebooted my chromebook. Tried again and received the below after "sudo startxfce4" - any thoughts?

method: xiwi
targets: xiwi,xfce
host: version 12607.82.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-19838-gc647e70c954a #1 SMP PREEMPT Thu Jan 9 23:22:43 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from https://goo.gl/OVQOEt)
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Hangup
Hangup
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@Anthem22,

> Is "xenial" really my version or is it "precise" or something else? 

Your *release* is **xenial** according to your `croutonversion` shown in your first post.
For 'recognized releases' supported, unsupported, and end-of-life enter:
- `sudo crouton -r list` 

> I thougth XENIAL was just the extension that allows me to launch in a window.
xenial (case sensitive) is a release as mentioned above.

`xiwi` is an xmethod and target, similar to the `xorg` xmethod target.
You can install xorg or xiwi or both if you like to launch your desktops.
With xorg you launch your desktop fullscreen and get hardware acceleration on many devices.
With xiwi you don't get hardware acceleration but you can launch your desktop in a window, fullscreen, or in a tab.

When you installed your chroot you specified xiwi:
```
xmethod: xiwi
targets: xiwi,xfce
```

I think the errors you were getting are due to a missing '[crouton integration](https://goo.gl/OVQOEt)' extension, the error message warns about it:
```
Error: not connected.
Cannot connect to extension, retrying...
Unable to start display, make sure the crouton extension is installed
and enabled, and up to date. (download from https://goo.gl/OVQOEt)
```
So you'll need to download and install it if you want to use xiwi.

If you're not interested in xiwi then update your chroot and add xorg, like this:
-  `sudo crouton -n xenial -t xorg -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Anthem22** [comment]
@DennisLfromGA Your guidance did the trick. Thanks for the help
