### ISSUE TITLE
touch target is not supported on Debian

### ISSUE THREAD

**Issue by cvmiller** [dnschneid/crouton#4216]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
$ sudo edit-chroot -all
name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xiwi
targets: xiwi,extension,xorg,x11,xfce,touch,audio
host: version 12607.58.0 (Official Build) stable-channel bob 
kernel: Linux localhost 4.4.196-16940-geab5e6346fdb #1 SMP PREEMPT Thu Dec 12 23:09:53 PST 2019 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...

#### Please describe your issue:
Can't update chroot as the target 'touch' seems to be _always_ enabled.

#### If known, describe the steps to reproduce the issue:
Run the following command:
sudo  /usr/local/bin/crouton -u -n buster -t xiwi,extension

How does one _disable_ targets on the command line?

**Comment by DennisLfromGA** [comment]
@cvmiller,

> Can't update chroot as the target 'touch' seems to be always enabled.

Do you mean the 'touch' target is failing to install and in turn causing the chroot installation to also fail?

It appears that the 'touch' target installs the 'touchegg' package so if it got installed then removing it should be a first step with:
- `sudo apt remove touchegg`
                -or-
- `sudo apt purge touchegg`

There's also a config file that crouton uses, you can remove it too if you like from here:
- `-rw-r--r--. 1 root root 3622 Sep  8 17:15 /etc/touchegg.conf`


There's no good programmatic way to remove or uninstall a target currently. What I do and what occasionally  works ( ;-) ) for me is to remove the targets *in* the chroot's target files located here:
- `-rw-------. 1 root root 161 Sep  8 17:12 /.crouton-targets`
- `-rw-r--r--. 1 root root  88 Sep  8 17:12 /etc/crouton/targets`

Note: you'll have to be root to edit the files but simply open them and remove the 'touch' target, save,  then update your chroot: `sudo crouton -n buster -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by cvmiller** [comment]
I was on the road, and finally had time to test out your work-around. The good news is that removing 'touch' from /etc/crouton/targets does solve the problem, and I can do updates.

However, I have lost touch-tap capability both in Xiwi and Xorg on my trackpad, something I had before. We need a better solution for Debian, a supported version, for Crouon. The trackpad 'touch-tap' used to work in Debian Buster.

**Comment by SteveDesmond-ca** [comment]
Hoping for this too -- tap works in xiwi, but not xorg...looking into what it would take to setup manually for xorg, looks like the gestures aren't being recognized since touchegg doesn't seem to work at all

**Comment by SteveDesmond-ca** [comment]
OK, solution for now:
1 `sudo apt install xserver-xorg-input-synaptics` (no touchegg required)
1. `synclient TapButton1=1 TapButton2=3 TapButton3=2` (2 and 3 are flipped for me, these might be different for you) -- these should ideally go in `/etc/X11/xorg.conf.d/synaptics.conf`

I'm not sure these are generic enough to add to the `touch` target...

**Comment by cvmiller** [comment]
I am glad you found a solution. I am curious, if you got 2-finger scrolling back as well?

https://github.com/dnschneid/crouton/issues/4413

**Comment by SteveDesmond-ca** [comment]
Yeah, once you install the `synaptics` driver, you can run `synclient` without any args to see all the available options and their current/default values, and there are a bunch of scrolling settings there
