### ISSUE TITLE
Disable Xfce4 opening in window (PiP)

### ISSUE THREAD

**Issue by Anthem22** [dnschneid/crouton#4219]
```
hronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 12607.82.0 (Official Build) stable-channel caroline 
kernel: Linux localhost 3.18.0-19838-gc647e70c954a #1 SMP PREEMPT Thu Jan 9 23:22:43 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...```

#### Please describe your issue:
I installed the crouton integration extension. Every time I boot "sudo startxfce4" it launched PiP but I actually prefer lanching to a more native version without picture in picture. How do I disable the default launch to PiP?



#### If known, describe the steps to reproduce the issue:

As said above everytime I launch I get PiP.

I have tried researching and trying some of the advice here https://github.com/dnschneid/crouton/issues/1276 
I replaced with xiwi and xenial where made sense but no luck.

**Comment by DennisLfromGA** [comment]
@Anthem22,

With the xiwi xmethod you can launch your desktop three different ways:
- In a window (default): `sudo startxfce4 -n xenial -X xiwi`
- In full screen mode:  `sudo startxfce4 -n xenial -X xiwi-fullscreen`
- In a browser tab:  `sudo startxfce4 -n xenial -X xiwi-tab`

You can also just launch a Linux app without a desktop using something like:
- In a window (default) `sudo startxiwi -n xenial gnome-mahjongg`
- In full screen mode: `sudo startxiwi -n xenial -F gnome-mahjongg`
- In a browser tab: `sudo startxiwi -n xenial -T gnome-mahjongg`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Anthem22** [comment]
@DennisLfromGA -This is helpful but doesn't fully solve. When I first installed crouton I was able to switch between ChromeOS and Crouton as though they were separate OS. All of your suggestions are different versions of Linux within ChromeOS. When using CTRL+ALT+SHIFT+RIGHT ARROW I'd like it to have that native feel I once had.

**Comment by DennisLfromGA** [comment]
@Anthem22,

> All of your suggestions are different versions of Linux within ChromeOS.

Nope, all of those examples were for launching desktops and apps using the 'xiwi' xmethod, the Linux version doesn't change at all. 

>  When using CTRL+ALT+SHIFT+RIGHT ARROW I'd like it to have that native feel I once had.

What you're describing is the 'xorg' xmethod, you can update your chroot and add it as the default xmethod with the following:
- `sudo crouton -n xenial -t xorg -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Anthem22** [comment]
@DennisLfromGA - At what point do I start paying you?! That did the trick. Thanks again.

**Comment by DennisLfromGA** [comment]
@Anthem22,

If for some reason you need to *force* the 'xorg' xmethod just use it in a similar manner as the 'xiwi' examples I showed above with:
- `sudo startxfce4 -n xenial -X xorg`

*Hope this helps,*
-**DennisLfromGA**
