### ISSUE TITLE
The sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton command doesnt work

### ISSUE THREAD

**Issue by 8787989778ffd** [dnschneid/crouton#4220]
When I tryed to run the sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton command it would  not run or it would say command no found.

**Comment by DennisLfromGA** [comment]
@8787989778ffd 

Make sure you do the following:
1. Download a fresh crouton installer from **https://goo.gl/fd3zc**
2. Make sure it's saved or copied to your **`Downloads`** folder
3. Press <kbd>**Ctrl**</kbd>+<kbd>**Alt**</kbd>+<kbd>**t**</kbd> to open a **`crosh`** session.
4. Enter **`shell`** to get a **`bash`** session
5. Enter **`sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton `** to install it

*Hope this helps,*
-**DennisLfromGA**

**Comment by JoeGunSun** [comment]
I have (almost) the same problem as the op.
When trying to install using the above command line I get the error message I'm asked to enter root pw which I do and then the following is shown:

> install: target '/usr/local/bin' is not a directory

If I try to enter `sudo install -Dt /bin -m 755 ~/Downloads/crouton` then I get the following response:

> install: cannot create regular fil '/bin/crouton': Read-only file system

.

**Comment by JoeGunSun** [comment]
..And now I think I found the reason for the above error messages. The user account that was used was a "kids google account". I did switch to my account (parent) and now the installation is running just fine :)

**Comment by Hapi27** [comment]
I am having this issue on an adult account, I add the line and am still receiving regular file, read only. Any suggestions on how to get past this?
