### ISSUE TITLE
how to start kali rolling from sd card

### ISSUE THREAD

**Issue by HPchrome** [dnschneid/crouton#4226]
Please paste the output of the following command here: sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20190902190258~master:9a594a66
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12871.7.0 (Official Build) dev-channel setzer 
kernel: Linux localhost 4.19.98-08051-gb35890a7f038 #1 SMP PREEMPT Sun Feb 9 23:51:42 PST 2020 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

#### Please describe your issue:
How can i start kali from my sd card where i installed?

First i install kali on chromebook, but there was no space to install kali-linux-full and i installed on sd card kali rolling. Then i run `sudo startxfce4` and it run the kali that is installed on chromebook , i eject the sd card and run ` sudo delete-chroot Kali` to delete kali on chromebook.

**Comment by DennisLfromGA** [comment]
@HPchrome,

You can use `startxfce4`'s '`-c`' option to tell it where to find the chroot(s):

- `    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots`

Or you can specify the full path to your start script, something like this:
- ` sudo "/media/removable/SD Card/bin/startxfce4"`

You may have to prefix the command with '`sh`' if the external media is mounted 'noexec'.

*Hope this helps,*
-**DennisLfromGA**
