### ISSUE TITLE
Fresh Install - Screen Doesn't Update on Click/Keypress

### ISSUE THREAD

**Issue by TacClark** [dnschneid/crouton#4227]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12607.82.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.149-13636-g9eade7219710 #1 SMP PREEMPT Fri Jan 10 00:14:58 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Strange issue I'm having. Not even sure how to really describe it. Installed using the instructions in the readme and any time I click or press a key, I have to switch to Chrome OS and back for the screen to actually display what I've done. It seems like everything is being processed, just not displayed until switching. 

Running the sudo startxfce4 command:
![5D2C2601-970E-4E23-914B-9DF228D58349](https://user-images.githubusercontent.com/10742044/75262536-aca13100-57ba-11ea-8e7a-49cd8809540e.png)

Machine loads xfce and dumps me back in Chrome OS:
![47BC9814-6934-451C-9A58-79F5F0FE5BD6](https://user-images.githubusercontent.com/10742044/75262539-ae6af480-57ba-11ea-9455-2df038d2e497.png)

Swap to xfce, click to open 2 terminal windows (have already clicked in screenshot):
![F0F16C9D-FBC7-4FD0-BB2A-BE24B11418C6](https://user-images.githubusercontent.com/10742044/75262547-b034b800-57ba-11ea-8892-e3d7f5d4a083.png)

Switching to Chrome OS to get xfce display to update:
![5B9A0437-0B60-4BB5-9B68-FCEFB3B46B51](https://user-images.githubusercontent.com/10742044/75262552-b165e500-57ba-11ea-9005-dde7a5fb74ff.png)

Switching back to show updated display:
![219541AE-3C44-4650-8500-10CB592F1CA7](https://user-images.githubusercontent.com/10742044/75262554-b32fa880-57ba-11ea-9bf6-e8a5d26af651.png)

**Comment by malkia** [comment]
My stupid workaround is - run "glxgears" or anything that updates window every frame, and check if it works for you. Obviously not great way.

**Comment by DennisLfromGA** [comment]
@TacClark  & @malkia,

For some more info. and another possible workaround see https://github.com/dnschneid/crouton/issues/4241#issuecomment-602252335

*Hope this helps,*
-**DennisLfromGA**
