### ISSUE TITLE
sh: 0: Can't open /root/Downloads/crouton

### ISSUE THREAD

**Issue by User-s-ops** [dnschneid/crouton#4234]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by User-s-ops** [comment]
command not found

**Comment by DennisLfromGA** [comment]
@User-s-ops 

To show us what you have installed -
1. Open a crosh session by pressing <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>
2. At the `crosh> ` prompt enter: `shell`
3. Enter: `sudo edit-chroot -all`

Next explain in detail -
- what issue(s) you have
- what's errors or warnings are displayed
- what you've done to reconcile them.

*Hope this helps,*
-**DennisLfromGA**
