### ISSUE TITLE
I'm very confused.

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#4237]
```
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
^ 
this command would not download anything, I'm currently trying to download Ubuntu but it just wouldn't work.
I think this might be happing because the file is zipped. If you're able to please help me. 
[crouton-master.zip](https://github.com/dnschneid/crouton/files/4333878/crouton-master.zip)
Also, I'm on a Chromebook and i try to find how to do it but nothing works, they are mostly old  too    
so please tell me how to set this up.
Thanks for everything 
sincerely
{unknow}

**Comment by RedcatPhoenix** [comment]
welp. idk.

**Comment by DennisLfromGA** [comment]
@RedcatPhoenix,

> sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
> ^ 
> this command would not download anything,

You are correct, that command will *not* download anything. That command will install crouton on your system *after* it's downloaded.

It appears you do not have the crouton installer in your Downloads folder. Please ensure that downloads are saved in the Downloads folder then proceed as follows.

Please follow the prerequisite steps below:
1. Remove any existing installer from your Downloads folder.
2. Fetch a fresh installer: https://goo.gl/fd3zc
3. Open a crosh shell (Ctrl-Alt-T, then type shell)
4. Prep the installer with: sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton

--------
> I'm currently trying to download Ubuntu but it just wouldn't work.
> I think this might be happing because the file is zipped.

The crouton installer will download the Ubuntu distro for you, it is designed to do that so please don't try to install it from a zip file. The currently supported release is Ubuntu 16.04 xenial.

*Hope this helps,*
-**DennisLfromGA**
