### ISSUE TITLE
Problems playing media files after ChromeOS upgrade

### ISSUE THREAD

**Issue by izohar** [dnschneid/crouton#4239]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi
host: version 12739.94.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 4.14.157-14175-g1706f38e9a13 #1 SMP PREEMPT Wed Mar 4 23:26:55 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
Thanks so much for crouton!

After a ChromeOS upgrade and crouton update, I can no longer play local video files using mplayer. Chromium and firefox play youtube videos okay, although there is a lot of flickering when using the browsers after the upgrade. I would really appreciate your help!

I get the following error when attempting to play movies using mplayer:
X11 error: BadAlloc (insufficient resources for operation)

I don't know if this is related, but I get the following errors when entering the chroot:
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

If it helps, here's the error from ffplay:
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  150 (XVideo)
  Minor opcode of failed request:  19 ()
  Serial number of failed request:  47
  Current serial number in output stream:  48

And the error from VLC:
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory

#### If known, describe the steps to reproduce the issue:
mplayer _videofile.mp4_

**Comment by Asternitix** [comment]
you'll want the target: audio

**Comment by Asternitix** [comment]
that's what fixed that for me.

**Comment by Asternitix** [comment]
but check if you have libdvdcss2 installed

**Comment by Asternitix** [comment]
if you don't that'll definitely have it.

**Comment by izohar** [comment]
Added the target audio and installed libdvdcss2 as suggested, these had no effect. Same problem persists, thank you for the attempt though!

**Comment by izohar** [comment]
Update: after the latest update mplayer is playing perfectly with the flags "-vo=x11 -zoom"
