### ISSUE TITLE
I'm confused again. HOW DO I GET END OF LIFE UBUNTU VERSIONS!

### ISSUE THREAD

**Issue by RedcatPhoenix** [dnschneid/crouton#4240]
I really want to get ubuntu utopic with unity so, I can get more linux operating systems. But i dont know how to mirror download them!

**Comment by DennisLfromGA** [comment]
@RedcatPhoenix,

To see a list of crouton releases available enter:
- `sudo crouton -r list`  

When you do that you'll see`utopic!` listed with an exclamation point which means it is upstream end-of-life, *and should be avoided*.

A list of Ubuntu mirrors is here: 
- https://launchpad.net/ubuntu/+archivemirrors  

If you still want to install it and use a mirror try this, as just one example:
- `sudo crouton -r utopic -t xfce -m http://mirror.genesisadaptive.com/ubuntu/`

*Hope this helps,*
-**DennisLfromGA**
