### ISSUE TITLE
When trying to load Crouton, screen is unresponsive but I can move the mouse

### ISSUE THREAD

**Issue by Jay-1-16** [dnschneid/crouton#4241]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12739.105.0 (Official Build) stable-channel grunt
kernal: Linux localhost 4.14.157-14175-g1706f38e9a13 #1 SMP PREEMPT Tue Mar 17 20:42:10 PDT 2020 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/xenial...
```

#### Please describe your issue:
When I load up Linux with Crouton the screen freezes on a glitchy looking screen and if I switch to ChromeOS and back the screen updates but is still frozen except for the fact that I can still use my mouse and move it around and when I click on something it seems like nothing is happening but if I switch back and forth between Chrome and Linux the screen updates again showing what I clicked on but again I can't do anything because the screen is unresponsive.

#### If known, describe the steps to reproduce the issue:
Unknown

**Comment by Jay-1-16** [comment]
I forgot to mention that when switching back an error that keeps popping up is:
```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
```

**Comment by DennisLfromGA** [comment]
@Jay-1-16,

I'm afraid it may be an issue with your particular Chromebook being that it uses an AMD chip.
There are other similar issues being reported about it, see below -

- https://github.com/dnschneid/crouton/issues?q=is%3Aissue+grunt

A workaround using xmethod 'xiwi' is mentioned here: https://github.com/dnschneid/crouton/issues/4063#issuecomment-530028617

Hopefully, that will suffice for your needs until a resolution for xmethod 'xorg' can be found.

*Hope this helps,*
-**DennisLfromGA**
