### ISSUE TITLE
Debian buster will not open (GNOME, LXDE, XFCE, etc.)

### ISSUE THREAD

**Issue by jimmybungalo** [dnschneid/crouton#4242]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
```name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20200116214215~master:9017d640
release: buster
architecture: amd64
xmethod: xorg
targets: gnome,audio,keyboard,core,cli-extra
host: version 12871.48.0 (Official Build) beta-channel terra 
kernel: Linux localhost 4.19.98-08069-g99ac670127ec #1 SMP PREEMPT Tue Mar 17 00:12:17 PDT 2020 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...
```

#### Please describe your issue:
When trying to open Debian buster, it will not open at all, except for the attempt at loading.

#### If known, describe the steps to reproduce the issue:
Typing in `sudo startgnome` after installing Debian buster with `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`, and then `sudo crouton -r buster -t gnome,audio,keyboard,core,cli-extra`.

Also, I am using an ASUS C202SA.

**Comment by DennisLfromGA** [comment]
@jimmybungalo,

I just now installed a buster chroot with the same targets and get what may be similar results.
The gnome desktop attempts to open, I see a mouse pointer in the lower right corner and the screen starts to lighten up but then it fails and exits the chroot.

Here's the display output:
```
Entering /var/crouton/chroots/buster...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-8-amd64 x86_64 Debian
Current Operating System: Linux localhost 4.4.211-17198-ga431862f6e61 #1 SMP PREEMPT Tue Mar 17 00:18:48 PDT 2020 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=PARTUUID=d9bd98fe-eea2-9648-9fbf-69e9962235be/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 4710400 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=4710400 alg=sha256 root_hexdigest=a1ff557cfe24a2879eaebe2df940f42237ca8320c6289c68b6904f8644ed2411 salt=8e2ff44fb204f26eaeba3fa8c19aee6f5d1279c855dea0dc7d467836c47cbcb6" noinitrd vt.global_cursor_default=0 kern_guid=d9bd98fe-eea2-9648-9fbf-69e9962235be add_efi_memmap boot=local noresume noswap i915.modeset=1 nmi_watchdog=panic,lapic disablevmx=off  
Build Date: 05 March 2019  08:11:12PM
xorg-server 2:1.20.4-1 (https://www.debian.org/support) 
Current version of pixman: 0.36.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Mar 22 15:06:57 2020
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1584904018.391861 sender=:1.20 -> destination=:1.228 serial=43131 reply_serial=2
   boolean true
(II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
crouton: version 1-20200116214215~master:9017d640
release: buster
architecture: amd64
xmethod: xorg
targets: gnome,keyboard,cli-extra
host: version 12871.48.0 (Official Build) beta-channel eve 
kernel: Linux localhost 4.4.211-17198-ga431862f6e61 #1 SMP PREEMPT Tue Mar 17 00:18:48 PDT 2020 x86_64 GNU/Linux
freon: yes
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1584904026.058005 sender=:1.20 -> destination=:1.230 serial=43135 reply_serial=2
   boolean true
.(II) Server terminated successfully (0). Closing log file.

Unmounting /var/crouton/chroots/buster...
chronos@localhost ~ $ 
```

I took a look at the Xorg log file and found these errors:
```
chronos@localhost ~ $ grep EE ~/Downloads/Xorg.crouton.1.log 
[ 50819.351] Current Operating System: Linux localhost 4.4.211-17198-ga431862f6e61 #1 SMP PREEMPT Tue Mar 17 00:18:48 PDT 2020 x86_64
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 50819.354] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 50819.365] (EE) Failed to load module "fbdev" (module does not exist, 0)
[ 50819.365] (EE) Failed to load module "vesa" (module does not exist, 0)
[ 50820.784] (II) Initializing extension MIT-SCREEN-SAVER
[ 50820.966] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 50820.990] (II) XINPUT: Adding extended input device "WCOM50C1:00 2D1F:5143" (type: TOUCHSCREEN, id 8)
```

Next tried the lxde desktop and got a little further, the background wallpaper shows up with the trash can but no menu or right-click menu. I did get a virtual desktop menu and could add desktops but without a lxde menu it was useless basically. The Xorg log errors were pretty identical.

Since without specifying an xmethod crouton will install 'xorg', I decided to install 'xiwi' to see if I could launch gnome and lxde and that did **not** work either. In my experience, xiwi usually doesn't work where xorg doesn't so this seems like a pretty serious bug.

Maybe the devs or someone else will see this and have some ideas.

Sorry, I couldn't be more help,
-**DennisLfromGA**

**Comment by saqikawaay** [comment]
I installed buster for a minute last week and don't remember having too many issues, but did manage to get XFCE to work. I did install `xfce-desktop` full target, IIRC just `xfce` didn't work for me, but I'm not 100% sure of that.

**Comment by kingliamb** [comment]
I recently tried to switch to Debian Buster for a more updated system and got the same problem. `stdout` and the xorg error log were identical to @DennisLfromGA 's. The problem also appears nearly identically in Debian Bullseye and Sid as well. I haven't had any problems with stretch, although that kinda defeats the purpose of upgrading from xenial. I can post error logs for buster and bullseye if that's helpful for anyone.

**Comment by Endermen1094** [comment]
On my install of Buster I don't get and clicking response  and this appears in shell : 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1613840907.589956 sender=:1.37 -> destination=:1.161 serial=5382 reply_serial=2
   boolean true
(II) AIGLX: Suspending AIGLX clients for VT switch
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1613840914.804156 sender=:1.37 -> destination=:1.164 serial=5385 reply_serial=2
   boolean true
