### ISSUE TITLE
The Command to Prep the Installer Isn't Working for me

### ISSUE THREAD

**Issue by hope170** [dnschneid/crouton#4243]
I'm attempting to install crouton on my Chromebook. When I put in the command "sudo isntall -Dt /user/local/bin -m 755 ~/Downloads/crouton" it says "Install: cannot create directory '/user' : read only file system"

What does this mean? Are you able to tell how to fix this?

**Comment by DennisLfromGA** [comment]
@hope170,

That's because the directory is not '`user`' but '`usr`'.
Also, in your post you wrote '`isntall`' and not '`install`'.

Maybe copy-n-paste this into the command=line: 
- `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`

*Hope this helps,*
-**DennisLfromGA**
