### ISSUE TITLE
Unable to install distro to usb drive

### ISSUE THREAD

**Issue by GDJason12** [dnschneid/crouton#4245]
Hi, so i have been trying to install xenial on my usb drive. I've formatted my usb to ext4 as `/media/removable/USB Drive` and when i run 
`sudo crouton -r bionic -t gnome-desktop -p ``/media/removable/USB\ Drive`

 it gives me this error

`bash: /media/removable/USB Drive: Is a directory`
`No arg for -p option`

I have no other options except, if someone could compress a fresh install Ubuntu 18.04 with Gnome desktop into an image file, I would appreciate it

**Comment by DennisLfromGA** [comment]
@GDJason12,

Maybe it's just a quoting issue, try:
- `sudo crouton -r bionic -t gnome-desktop -p "/media/removable/USB Drive"`

Another option might be to install it on internal storage per default and them move or copy it once your done with `edit-chroot`, see below for the move & copy options:
```
    -m DEST     Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.
    -C DEST     Like -m, but copies instead of moves.
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by GDJason12** [comment]
> @GDJason12,
> 
> Maybe it's just a quoting issue, try:
> 
> * `sudo crouton -r bionic -t gnome-desktop -p "/media/removable/USB Drive"`
> 
> Another option might be to install it on internal storage per default and them move or copy it once your done with `edit-chroot`, see below for the move & copy options:
> 
> ```
>     -m DEST     Moves a chroot. Specify a new name to keep it in the same
>                 directory, or an absolute path to move it entirely.
>                 DEST can be a directory, in which case it must end in a slash.
>                 If multiple chroots are specified, DEST must be a directory.
>                 If you are moving a chroot to a SD card/USB drive, make sure the
>                 storage is formatted to ext2/3/4.
>     -C DEST     Like -m, but copies instead of moves.
> ```
> 
> _Hope this helps,_
> -**DennisLfromGA**

Thank you so much, that helped <3
