### ISSUE TITLE
Hang on Debian Bullseye w/ Libreoffice

### ISSUE THREAD

**Issue by cainy-a** [dnschneid/crouton#4247]
```
name: bullseye
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bullseye...
crouton: version 1-20200116214215~master:9017d640
release: bullseye
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,xorg,extension,audio,chrome,keyboard
host: version 12739.105.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.157-14175-g1706f38e9a13 #1 SMP PREEMPT Tue Mar 17 20:42:10 PDT 2020 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bullseye...
name: jessie
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/jessie...
crouton: version 1-20200116214215~master:9017d640
release: jessie
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi,xorg,extension,audio,chrome,keyboard
host: version 12739.105.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.157-14175-g1706f38e9a13 #1 SMP PREEMPT Tue Mar 17 20:42:10 PDT 2020 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/jessie...
```

#### Please describe your issue:

I got the full crouton environment to hang and be unresponsive on bullseye

#### If known, describe the steps to reproduce the issue:
EDIT: This seems unrelated to page breaks; this occurred out of the blue multiple times while using Libreoffice Draw.

**Comment by DennisLfromGA** [comment]
@cainy-a,

Is this happening with both 'xorg' and 'xiwi' ?

-**DennisLfromGA**

**Comment by cainy-a** [comment]
I have only tested and observed this on a chroot running
xorg,xiwi,extension as targets

**Comment by DennisLfromGA** [comment]
@cainy-a,

Since you have both xmethods installed I suggest you try launching your desktop in each one and see if you get the same results. You can do that with the following commands:
- sudo startxfce4 -n bullseye -X xorg (starts in fullscreen)

After testing that next try:
- sudo startxfce4 -n bullseye -X xiwi-fullscreen (starts in fullscreen)

See if the xmethod makes a difference, I believe it will.

*Hope this helps,*
-**DennisLfromGA**

**Comment by cainy-a** [comment]
Xorg seems to have fixed it, as before it was using xiwi, and Xorg runs way faster and smoother too

**Comment by DennisLfromGA** [comment]
@cainy-a,

Since you have both xmethods installed you can easily change the default back to 'xorg' by editing the file:
- `/etc/crouton/xmethod`

Then you won't have to specify the '`-X xorg`' option each time.

*Hope this helps,*
-**DennisLfromGA**
