### ISSUE TITLE
I'M CONFUSED FOR THE 3RD DARN TIME!

### ISSUE THREAD

**Issue by RedcatPhoenix2** [dnschneid/crouton#4249]
How do I get ubuntu with chromium too?

**Comment by saqikawaay** [comment]
I would simply add that if you want chromium after you've already installed, you have two options. 

One is from the ChromeOS shell: update your chroot. This is the second command DennisLfromGA added above `sudo crouton -n bionic -t chromium -u`. If you didn't get a bionic (ubuntu 18.04; it doesn't work for my device), your version might be xenial (16.04). You can type `sudo enter-chroot` to see the name of your chroot, and adjust the above command accordingly. 

The second option is from within a terminal inside your Ubuntu installation. Simply type `sudo apt install chromium` and follow the prompts and you're set. Firefox can be installed similarly.
