### ISSUE TITLE
sudo crouton -u won't update, broken packages.

### ISSUE THREAD

**Issue by kingliamb** [dnschneid/crouton#4250]
`$ sudo edit-chroot -all`
> `name: thistlehoney`
> `encrypted: no`
> `Entering /mnt/stateful_partition/crouton/chroots/thistlehoney...`
> `crouton: version 1-20200116214215~master:9017d640`
> `release: xenial`
> `architecture: amd64`
> `xmethod: xorg`
> `targets: unity,xorg,xiwi`
> `host: version 12739.111.0 (Official Build) stable-channel coral` 
> `kernel: Linux localhost 4.4.205-17074-gdc1f94d55924 #1 SMP PREEMPT Mon Mar 30 23:23:18 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux`
> `freon: yes`

#### Please describe your issue:
When I tried to update my chroot with `sudo crouton -un thistlehoney` like I do every so often, it spit out the weirdest error. Here are the last 25 lines of the log:
```
   750K .......... .......... .......... .......... .....      3.90M=0.2s

2020-04-04 05:02:49 (3.90 MB/s) - '/tmp/crouton-cras.oMHHWA/adhd.tar.gz' saved [814701]

Reading package lists... Done
Building dependency tree       
Reading state information... Done
alsa-utils is already the newest version (1.1.0-0ubuntu5).
libasound2:i386 is already the newest version (1.1.0-0ubuntu1).
libspeexdsp1:i386 is already the newest version (1.2~rc1.2-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gcc-multilib : Depends: gcc-5-multilib (>= 5.3.1-3~) but it is not going to be installed
 libc6-dev:i386 : Depends: libc6:i386 (= 2.23-0ubuntu3) but 2.23-0ubuntu11 is to be installed
E: Unable to correct problems, you have held broken packages.
Failed to complete chroot setup.
Not unmounting /mnt/stateful_partition/crouton/chroots/thistlehoney as another instance is using it.
```

I tried a little bit to fix the problem by installing the packages manually within the chroot with apt and aptitude, but the problem persisted. I don't know what's wrong. If anyone wants a list of my installed packages, [here it is.](https://drive.google.com/file/d/1-OS05KWlnavhl29DSqRw0QvijAjdttM1/view?usp=sharing "aptlist.txt")

#### If known, describe the steps to reproduce the issue:
¯\_(ツ)_/¯

**Comment by DennisLfromGA** [comment]
@kingliamb,

I just updated my xenial chroot with unity -  
- from: `version 1-20190902190258~master:9a594a66`
- to ...:     `version 1-20200116214215~master:9017d640`  (newest & same as yours)

I had no warnings or errors.

I have the following installed:

```
chroot name: xen.unity (2.0G)
crouton: version 1-20200116214215~master:9017d640
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xorg,cli-extra,keyboard,unity,chrome-beta
host: version 13015.0.0 (Official Build) dev-channel lulu 
kernel: Linux localhost 4.14.174-15082-ge77ca2dbd70c #1 SMP PREEMPT Tue Mar 31 12:31:52 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

I found these similar packages with the following versions installed on my chroot:
- `gcc-multilib/xenial,now 4:5.3.1-1ubuntu1 amd64 [installed]`  
- `libc6-dev-i386/xenial-updates,now 2.23-0ubuntu11 amd64 [installed,automatic]`  

Not sure why my versions are different from yours.  

I like to install and use '`aptitude`' instead of '`apt`' or '`apt-get`' for situations like this. It has better dependency resolution I think. You could install it and run: `sudo aptitude -f install` and see what it suggests.

*Hope this helps,*
-**DennisLfromGA**

**Comment by kingliamb** [comment]
Alright I used `aptitude` to fix attempt to fix the problem, and it just caused errors like this for a bunch of packages. After a few rounds of "fixing" with `aptitude`, I had hundreds of package errors. I just deleted and recreated my chroot. I don't know what caused this problem, but nobody else thus far has had this error so I'm optimistic that by closing this it's not going to cause a problem.
