### ISSUE TITLE
Kali-Rolling Sound Not Working

### ISSUE THREAD

**Issue by kadenbcampbell** [dnschneid/crouton#4251]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
WARNING: Unable to register core dump handler.
crouton: version 1-20200116214215~master:9017d640
release: kali-rolling
architecture: amd64
targets: audio,core
host: version 12739.111.0 (Official Build) stable-channel edgar 
kernel: Linux localhost 3.18.0-19937-g5da699e3897c #1 SMP PREEMPT Mon Mar 30 23:02:06 PDT 2020 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling as another instance is using it.
```

#### Please describe your issue:
I started pulseaudio with `pulseaudio --start` in terminal, but the only output device is a dummy output. For some reason, pulseaudio can't see any of the hardware sound cards.

I don't understand a lot about how operating systems work, and it's difficult for me to problem solve as I usually end up breaking things, and as a result, I have to entirely re-install the chroot. My point is, if there is a solution, please explain it to me as if I were five years old.

#### If known, describe the steps to reproduce the issue:
Install Kali Rolling. Open terminal and type `pulseaudio --start`.

**Comment by DennisLfromGA** [comment]
This may *still* be a lingering bug on kali releases.
Bottom line, as a crouton dev puts it: *pulseaudio on kali is indeed broken.*

Closing and duping this issue to: https://github.com/dnschneid/crouton/issues/2039

*Hope this helps,*
-**DennisLfromGA**
