### ISSUE TITLE
debian and kail there's no sound

### ISSUE THREAD

**Issue by toutheif** [dnschneid/crouton#4252]
My notebook model is spin13, crouton installed all the support system, found that except xenial sound everything is ok, debian and kali have no sound, how to solve? Get used to debian

**Comment by DennisLfromGA** [comment]
This may *still* be a lingering bug on kali releases.
Bottom line, as a crouton dev puts it: *pulseaudio on kali is indeed broken.*

Closing and duping this issue to: https://github.com/dnschneid/crouton/issues/2039

*Hope this helps,*
-**DennisLfromGA**
