### ISSUE TITLE
can't install newer nodejs

### ISSUE THREAD

**Issue by kongzheng1993** [dnschneid/crouton#4254]
i want use hexo to write blog. after installed trusty by crouton, i installed `nodejs` and `npm`. but they are too old to `npm install hexo`.
so i have to intall the newer version node, i download arm nodejs, but got these when i use it...

```console
(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ ll
total 39196
drwxr-xr-x. 2 kongzheng1993 kongzheng1993     4096 Apr  9 13:53 ./
drwxr-xr-x. 6 kongzheng1993 kongzheng1993     4096 Feb 18 12:38 ../
-rwxr-xr-x. 1 kongzheng1993 kongzheng1993 40105636 Feb 18 12:37 node*
lrwxrwxrwx. 1 kongzheng1993 kongzheng1993       42 Feb 18 12:38 npm -> ../lib/node_modules/npm/bin/npm-cli.js*
lrwxrwxrwx. 1 kongzheng1993 kongzheng1993       42 Feb 18 12:38 npx -> ../lib/node_modules/npm/bin/npx-cli.js*
(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ ll
total 39196
drwxr-xr-x. 2 kongzheng1993 kongzheng1993     4096 Apr  9 13:53 ./
drwxr-xr-x. 6 kongzheng1993 kongzheng1993     4096 Feb 18 12:38 ../
-rwxr-xr-x. 1 kongzheng1993 kongzheng1993 40105636 Feb 18 12:37 node*
lrwxrwxrwx. 1 kongzheng1993 kongzheng1993       42 Feb 18 12:38 npm -> ../lib/node_modules/npm/bin/npm-cli.js*
lrwxrwxrwx. 1 kongzheng1993 kongzheng1993       42 Feb 18 12:38 npx -> ../lib/node_modules/npm/bin/npx-cli.js*
(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ clear

(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ ll
total 39196
drwxr-xr-x. 2 kongzheng1993 kongzheng1993     4096 Apr  9 13:53 ./
drwxr-xr-x. 6 kongzheng1993 kongzheng1993     4096 Feb 18 12:38 ../
-rwxr-xr-x. 1 kongzheng1993 kongzheng1993 40105636 Feb 18 12:37 node*
lrwxrwxrwx. 1 kongzheng1993 kongzheng1993       42 Feb 18 12:38 npm -> ../lib/node_modules/npm/bin/npm-cli.js*
lrwxrwxrwx. 1 kongzheng1993 kongzheng1993       42 Feb 18 12:38 npx -> ../lib/node_modules/npm/bin/npx-cli.js*
(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ ./node
./node: relocation error: ./node: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ ./npm

/home/kongzheng1993/Downloads/node-v12.16.1-linux-armv7l/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ sudo ./node
[sudo] password for kongzheng1993: 
./node: relocation error: ./node: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
(trusty)kongzheng1993@localhost:~/Downloads/node-v12.16.1-linux-armv7l/bin$ sudo ./npm

/home/kongzheng1993/Downloads/node-v12.16.1-linux-armv7l/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```
i try to download `libstdc++6-armhf-cross_4.8.4-2ubuntu1_14.04.1cross0.11.2_all.deb` to install ,and some `libstdc++.so.6`, i am so tired...

please help me...

i am in china, network is a big trouble, if i can't fix it, i may sale is sell it ... i love my chromebook so much, even it's a arm machine...

**Comment by DennisLfromGA** [comment]
@kongzheng1993,

> ... so i have to intall the newer version node, i download arm nodejs,

I don't know what newer versions you need but maybe a newer distro like xenial (default) or bionic would have what you need. You can see what versions are in the distro repos, I've listed both xenial & bionic below:

> Ubuntu – Details of package nodejs in xenial
https://packages.ubuntu.com/xenial/nodejs

> Ubuntu – Details of package npm in xenial
https://packages.ubuntu.com/xenial/npm

> Ubuntu – Details of package nodejs in bionic
https://packages.ubuntu.com/bionic/nodejs

> Ubuntu – Details of package npm in bionic
https://packages.ubuntu.com/bionic/npm

*Hope this helps,*
-**DennisLfromGA**

**Comment by kongzheng1993** [comment]
thanks for your help



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： DennisL <notifications@github.com>
日期: 2020/4/12 02:48 (GMT+08:00)
收件人： dnschneid/crouton <crouton@noreply.github.com>
抄送： evilRat <kongzheng1993@hotmail.com>, Mention <mention@noreply.github.com>
主题： Re: [dnschneid/crouton] can't install newer nodejs (#4254)


@kongzheng1993<https://github.com/kongzheng1993>,

... so i have to intall the newer version node, i download arm nodejs,

I don't know what newer versions you need but maybe a newer distro like xenial (default) or bionic would have what you need. You can see what versions are in the distro repos, I've listed both xenial & bionic below:

Ubuntu C Details of package nodejs in xenial
https://packages.ubuntu.com/xenial/nodejs

Ubuntu C Details of package npm in xenial
https://packages.ubuntu.com/xenial/npm

Ubuntu C Details of package nodejs in bionic
https://packages.ubuntu.com/bionic/nodejs

Ubuntu C Details of package npm in bionic
https://packages.ubuntu.com/bionic/npm

Hope this helps,
-DennisLfromGA

―

**Comment by kongzheng1993** [comment]
1

**Comment by DennisLfromGA** [comment]
You're quite welcome.

Closing. Please re-open if this issue is still a concern.

**Comment by kongzheng1993** [comment]
@DennisLfromGA I mean nodejs version. you mean the reason is my os too old to install newer version nodejs?
