### ISSUE TITLE
Change distro?

### ISSUE THREAD

**Issue by chaseboy100** [dnschneid/crouton#4255]
From readme, "The -r parameter specifies which distro release you want to use."
How do I change it from xenial to something like buster?
(What cmds?)

**Comment by DennisLfromGA** [comment]
@chaseboy100,

You cannot *change* distros in the installed chroot like going from an Ubuntu xenial release to a Debian buster release.

You *can* upgrade a distro like going from Ubuntu trusty to Ubuntu xenial but it can be problematic. 

If you currently have an Ubuntu xenail chroot for example, to get a Debian buster chroot you'll have to do a new crouton installation. If you have the available storage space you can keep both chroots installed and use the '`-n [CHROOTNAME]`' option when launching them.

For more about installing buster, see the answer I gave you here: https://github.com/dnschneid/crouton/issues/4248#issuecomment-612491308

*Hope this helps,*
-**DennisLfromGA**
