### ISSUE TITLE
Crouton "permission denied" on arnoldthebat's Chromium build

### ISSUE THREAD

**Issue by TheLetterKaeh** [dnschneid/crouton#4261]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/var/run/drm': Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
As seen above, it fails to get control of the DRM, and leaves the chroot in an unusable state.

#### If known, describe the steps to reproduce the issue:
This occurs on both a typical install (no parameters, aside from `-t core`), and every attempt I've made to install to USB. When installing to the USB Drive, it reads as 
`cp: cannot create directory '/var/run/crouton/media/removable/USB Drive/chroots/xenial/var/run/drm': Permission denied`

I have already remounted it as exec, and the system itself has rootfs verification disabled.

**Comment by LeptonWu** [comment]
I hit this, strace shows that it tried to created directory while keeping some selinux attrib.

Running "setenforce 0" before running crouton  make it work for me.
