### ISSUE TITLE
(Sommelier error)Gdk-Message: 16:46:30.920: Error 71 (Protocol error) dispatching to Wayland display.

### ISSUE THREAD

**Issue by yutouyes** [dnschneid/crouton#4262]
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20200116214215~master:9017d640
release: bionic
architecture: amd64
targets: core,audio,cli-extra
host: version 12739.105.0 (Official Build) stable-channel rammus 
kernel: Linux localhost 4.19.87-brunch-sebanc #1 SMP PREEMPT Sat Apr 4 09:07:43 CEST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: no
```

Hi all, I followed this [wiki ](https://github.com/dnschneid/crouton/wiki/Sommelier-(A-more-native-alternative-to-xiwi)) to install sommelier in chroot. Installed successfully.
And I launched gedit. It displayed without error. But when I opened firefox, it reported:
```
Gdk-Message: 16:46:30.920: Error 71 (Protocol error) dispatching to Wayland display.
```
No firefox window displayed.

**Comment by DennisLfromGA** [comment]
@yutouyes 

I googled that error and found this:

[Bug 779764](https://bugzilla.gnome.org/show_bug.cgi?id=779764#c2) - Gdk-WARNING **: Error 71 (Protocol error) dispatching to Wayland display
> Firefox doesn't Wayland native, I am not sure about OpenOffice. But evolution does.
> Can you please capture the the logs produced with WAYLAND_DEBUG=1 while the issue occurs?
> That should tell what protocol error actually occurs...

So it appears to be an upstream bug.

*Hope this helps,*
-**DennisLfromGA**

**Comment by satmandu** [comment]
I didn't have to install sommelier to get Wayland apps working. I just did this:

```
export XDG_RUNTIME_DIR='/var/host/chrome'
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
                 ## if not found, launch a new one
                 eval `dbus-launch --sh-syntax`
                 ##echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi
export DBUS_SYSTEM_BUS_ADDRESS='unix:path=/var/host/dbus/system_bus_socket'
```
Then I was able to try to start firefox thus:
```MOZ_ENABLE_WAYLAND=1 WAYLAND_DEBUG=1 firefox```, but I get this error:
```[2880191.924] wl_display@1.error(wl_registry@20, 0, "invalid version for global wl_compositor (1): have 3, wanted 4")```

I think that is set here: https://chromium.googlesource.com/chromium/src/+/refs/heads/master/components/exo/wayland/wl_compositor.h

**Comment by satmandu** [comment]
As per https://hg.mozilla.org/mozilla-central/file/tip/widget/gtk/nsWaylandDisplay.cpp#l209
```// Requested wl_compositor version 4 as we need wl_surface_damage_buffer().```

But wl_surface_damage_buffer appears in https://chromium.googlesource.com/chromium/src/third_party/+/master/wayland/include/protocol/wayland-client-protocol-core.h

So maybe we need someone to submit a bug report to crbug.com to try to get the wl_compositor version revved in https://chromium.googlesource.com/chromium/src/+/refs/heads/master/components/exo/wayland/wl_compositor.h ?
