### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by AsianLad16** [dnschneid/crouton#4263]
I want to make steam library folder on external usb drive. how to get proper permission on external usb drive when mounted?

Link: https://www.reddit.com/user/New_Asian_Dude16/comments/g2j5vq/the_three_things_sorry_im_not_being_a_bit_more/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by DennisLfromGA** [comment]
@AsianLad16,

Your reddit post above seems to petain to Crostini, not crouton.

If your external drive is mounted noexec and/or without rw permissions then just remount it, for example:
- sudo mount -i -o remount,exec,rw /media/removable/[NameOfDeviceMountpoint]

*Hope this helps,*
-**DennisLfromGA**
