### ISSUE TITLE
Kali linux is not installing with crouton

### ISSUE THREAD

**Issue by KhushPatel365** [dnschneid/crouton#4267]
```
Please paste the output of the following command here: sudo sh -e ~/Downloads/crouton -r kali-rolling -t xfce
```
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

#### Please describe your issue:
I tried all the steps in the previous issue and none worked. I would appreciate any help

**Comment by DennisLfromGA** [comment]
Please refer to the answer in your other post here: https://github.com/dnschneid/crouton/issues/360#issuecomment-617269152
