### ISSUE TITLE
Unable to determine the release in /usr/local/chroots/mojave. Please specify it with -r. || focal does not belong to any supported distribution.

### ISSUE THREAD

**Issue by kingliamb** [dnschneid/crouton#4269]
name: mojave
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/mojave...
crouton: version 1-20200116214215~master:9017d640
release: bionic
architecture: amd64
targets: core,audio,cli-extra
host: version 12739.111.0 (Official Build) stable-channel coral 
kernel: Linux localhost 4.4.205-17074-gdc1f94d55924 #1 SMP PREEMPT Mon Mar 30 23:23:18 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
I'm not exactly sure what happened but I can't update my chroot.
Here are the commands and output:
```
chronos@localhost ~ $ sudo crouton -un mojave
Downloading latest crouton installer...
#################################################################################################################################################### 100.0%#################################################################################################################################################### 100.0%
/usr/local/chroots/mojave already exists; updating it...
Unable to determine the release in /usr/local/chroots/mojave. Please specify it with -r.
chronos@localhost ~ $ sudo crouton -un mojave -r focal
focal does not belong to any supported distribution.
```

I installed bionic and then upgraded with `update-manager-core`'s `do-release-upgrade` and it upgraded successfully. That's the only thing I can think of that might have caused this issue.

**Comment by DennisLfromGA** [comment]
@kingliamb 

If you run `sudo crouton -r list` you'll see 'focal' is not listed:
```
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty! utopic! vivid! wily! xenial yakkety! zesty! artful! bionic* cosmic!
    disco* eoan*  

Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```

So specifying '-r focal' will not work since 'focal does not belong to any supported distribution'.
You can still update & upgrade your chroot in the chroot but you can no longer update your version of crouton IIUC.

*Hope this helps,*
-**DennisLfromGA**

**Comment by dnschneid** [comment]
Added focal to the list of Ubuntu releases.  It should work\* now.



\* for certain totally-untested definitions of "work"
