### ISSUE TITLE
doesnt let me put in a password

### ISSUE THREAD

**Issue by Rhino149** [dnschneid/crouton#4270]
when im trying to set a password it doesnt let me do anything but press enter which fails it

**Comment by DennisLfromGA** [comment]
@Rhino149,

Are you sure it's not being accepted?

For security reasons, the password you enter is *not* displayed on the terminal but it *is* being recorded as input. Try it again by entering your password (twice) when prompted and if it doesn't work let us know and give us more details showing the command, errors, etc.

*Hope this helps,*
-**DennisLfromGA**
