### ISSUE TITLE
[Kali-rolling]E: Package 'kde-runtime' has no installation candidate

### ISSUE THREAD

**Issue by yutouyes** [dnschneid/crouton#4272]
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20200428114634~master:67dc8d77
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: chrome-dev,audio,extension,xorg,xfce,keyboard
host: version 12739.111.0 (Official Build) stable-channel nautilus 
kernel: Linux localhost 4.19.113-brunch-sebanc #1 SMP PREEMPT Sat May 2 11:57:06 CEST 2020 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
When I try to install kde for my kali:
```sudo crouton -t kde -n kali-rolling -u```
It reports the error ```E: Package 'kde-runtime' has no installation candidate```
And kde isn't be installed.

Thank you!

**Comment by DennisLfromGA** [comment]
I'm not sure if kali-rolling has changed and has new requirements for kde but maybe the link below will help get it fixed:
- https://gist.github.com/jayluxferro/5cb6ee45726bd30264918df2b0553b70#kde-desktop

*Hope this helps,*
-**DennisLfromGA**

**Comment by ergpopler** [comment]
can confirm this is happening on Debian sid aswell :(

**Comment by BonnieLeeRoot** [comment]
I have the same error with Debian Bullseye. I tried xfce4 and it runs fine w/xiwi. Using cli, I installed kde-plasma-desktop, but it is not connecting with crouton extension. I would like to use kde with Bullseye. Any ideas?
