### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by MrLbird** [dnschneid/crouton#4276]
When I try to run sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton it says I need a password but when I type in my password it says its wrong.

**Comment by Carl393** [comment]
Did you figure out the problem? Perhaps you need to set a password for the sudo command as you are running as chronos user (I am assuming you are running this command from chromebooks built in shell?) Thanks for clarifying

**Comment by DennisLfromGA** [comment]
@MrLbird,

Did you set a password for chronos using `chromeos-setdevpasswd` ?
If so, use that one.

Did you enable '[Debugging Features](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/debugging-features) at the initial sign-in (OOBE) screen ?
If so, you'll first have to login as root with the password you set before going any further.

*Hope this helps,*
-**DennisLfromGA**

**Comment by MrLbird** [comment]
This is weird... I never posted this...

**Comment by MrLbird** [comment]
but lol okay

**Comment by MrLbird** [comment]
Oh yeah thanks!
