### ISSUE TITLE
Broken link to Google Plus n the wiki

### ISSUE THREAD

**Issue by brannerchinese** [dnschneid/crouton#4277]
There is a [link](https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-%28xiwi%29) to `https://plus.google.com/u/0/+FrancoisBeaufort/posts/JDVkXALPcNq` in the wiki. The link is broken — Google Plus is defunct.

I have not edited the wiki page because I don't know what new link would be a suitable replacement.

**Comment by DennisLfromGA** [comment]
Removed reference & link to deprecated G+ discussion [here](https://plus.google.com/u/0/+FrancoisBeaufort/posts/JDVkXALPcNq).
