### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by MrLbird** [dnschneid/crouton#4279]
I'm trying to figure out how to use 18.04 or 20.04 but I don't know how can anyone help?

**Comment by MrLbird** [comment]
I figured it out, you have to type `sudo sh ~/Downloads/crouton -r VERSION -t DESKTOP -n CHROOTNAME` But replace the caps with your own stuff.

**Comment by DennisLfromGA** [comment]
> sudo sh ~/Downloads/crouton ...

^^ That method ^^ no longer valid with the noexec mounts, see the [README](https://github.com/dnschneid/crouton#but-first) for new info. on installing crouton.

Closing. Please re-open if this issue is still a concern.

**Comment by MrLbird** [comment]
Ok.

**Comment by MrLbird** [comment]
That doesn't help.

**Comment by MrLbird** [comment]
> > sudo sh ~/Downloads/crouton ...
> 
> ^^ That method ^^ no longer valid with the noexec mounts, see the [README](https://github.com/dnschneid/crouton#but-first) for new info. on installing crouton.
> 
> Closing. Please re-open if this issue is still a concern.

hmmm
