### ISSUE TITLE
Upgrade raring to saucy

### ISSUE THREAD

**Issue by schnie** [dnschneid/crouton#428]
Now that 13.10 is officially out, what is the best way (if any) to upgrade a chroot from 13.04?  The software updater is showing the upgrade as available, but I'm hesitant to let it upgrade.  Is there a better way to do this?  Any advice would be appreciated!

**Comment by zwhitchcox** [comment]
Where is this ubuntu upgrader? Is it a command line tool? Do I have to download it? Which distro is it in, or is it in all of them?
