### ISSUE TITLE
No Space Left Even Though I have space?

### ISSUE THREAD

**Issue by Andreilys** [dnschneid/crouton#4280]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
df -h /home/chronos/user
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1   11G  2.8G  7.0G  29% /home/chronos/user

#### Please describe your issue:
Trying to pip install tensorflow (516.2MB) but for some reason it says I'm out of space, even though it says I have 7GB of space available

**Comment by Andreilys** [comment]
I mounted on my external drive, (see df -h output below) and it still says i'm out of space on the device when I try to install pip install tensorflow,
![Screenshot 2020-05-17 at 9 32 28 AM](https://user-images.githubusercontent.com/8299248/82154249-6db2d280-9821-11ea-9f34-16845e7710f5.png)

**Comment by Carl393** [comment]
Hm, perhaps the install process makes use of another partition temporarily that is running out of room?...Ive had a similar problem in the past but I cannot exactly iron out the specifics that caused the issue. I'm by no means an expert, just trying to offer an idea.

**Comment by Andreilys** [comment]
@Carl393 any thoughts on how to diagnose the issue?

**Comment by Andreilys** [comment]
Solved this issue by creating a tmp directory:

```
mkdir -p /home/<user>/tmp
export TMPDIR=/home/<user>/tmp
```

Thanks for the tip @Carl393.
