### ISSUE TITLE
How do I change the name of the folder my linux is installed in?

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#4282]
Hello folks!

name: buster
encrypted: no
Entering /home/linux/chroots/buster...
crouton: version 1-20200428114634~master:67dc8d77
release: bullseye
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12871.48.0 (Official Build) beta-channel auron_yuna 
kernel: Linux localhost 4.14.167-14953-g10fef9ca764e #1 SMP PREEMPT Tue Mar 17 00:20:24 PDT 2020 x86_64 GNU/Linux
freon: yes
Unmounting **/home/linux/chroots/buster...**

#### Please describe your issue:
I would like to change the name of my chroot so that it is the same as what I am currently updated as (bullseye) is this possible?
also is it possible to change the name of the folder from /home/linux/chroots/buster to....
/home/linux/chroots/bullseye

? I'm not sure how to go about doing this.

Thank you for your time.

**Comment by DennisLfromGA** [comment]
@Carl393,

> I would like to change the name of my chroot so that it is the same as what I am currently updated as (bullseye) is this possible?

The 'name' of the chroot is stored in the chroot at: `/etc/crouton/name`
You can edit that file as root and change it.

> also is it possible to change the name of the folder from /home/linux/chroots/buster to....
/home/linux/chroots/bullseye

Yes, it can be done with the '`edit-chroot`' command, see below:

- sudo edit-chroot buster -m bullseye

-**DennisLfromGA**
*Hope this helps,*
