### ISSUE TITLE
Audio does not work in XFCE

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#4283]
(buster)carl@localhost:~$ croutonversion
crouton: version 1-20200428114634~master:67dc8d77
release: bullseye
architecture: amd64
xmethod: xorg
targets: xfce
host: version 12871.48.0 (Official Build) beta-channel auron_yuna 
kernel: Linux localhost 4.14.167-14953-g10fef9ca764e #1 SMP PREEMPT Tue Mar 17 00:20:24 PDT 2020 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
For some reason, my audio isn't working...
I'm pretty sure I have a Realtek ALC283 soundcard in my acer chromebook
However when i type:
**cat /proc/asound/cards**
all I get is the following
 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xe1118000 irq 45
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xe111c000 irq 46

I'm not sure what's going on here, Can anyone help out?
It seems that... for whatever reason CRAS always screws up at some point and my audio breaks...

**Comment by Carl393** [comment]
I ran this command and received the following response:

**cras_test_client --dump_server_info**

cras_test_client: cras_client: **Connect server failed: Connection timed out
Couldn't connect to server.**

Can anyone provide insight? I don't know what's going on here...

**Comment by Carl393** [comment]
Completely formatted the folder, reinstalled chroot, still no audio... running debian bullseye. Can anyone comment on why audio won't work? So strange.

**Comment by budp635** [comment]
I had the same issue and found a work around. Once in Linux, open the terminal and type   pulseaudio --start . That is only good for the session you are in, however you can avoid having to type that in each time you start Linux.

Under the applications menu, go to Settings, then Session and Startup. Click on the Application Autostart tab. You will a list of applications that start automatically. Click on the + Add button. Give it a name that remind you what it is, I choose start pulsaudio. Then in the Command box enter the same command that you typed in the terminal pulseaudio --start . Then click on ok. You can test it by restarting linux.

The same issue is in ubuntu focal.
