### ISSUE TITLE
root wont open or work at all 

### ISSUE THREAD

**Issue by king24806** [dnschneid/crouton#4286]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by DennisLfromGA** [comment]
@king24806,

You didn't show us the output of `sudo edit-chroot -all` so we don't have specifics about your chroot but I'll try to help if I can.

You said:
>  it has a big red x on the root file i try and it says kali-rolling my username then local host not root please fix this so i can actually use kali linux that

What are you doing when you see the big red X and what root file are you speaking of?

-**DennisLfromGA**
