### ISSUE TITLE
hardware acceleration problem

### ISSUE THREAD

**Issue by akabakass** [dnschneid/crouton#4287]
```
name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
crouton: version 1-20200428114634~master:67dc8d77
release: focal
architecture: amd64
xmethod: xorg
targets: audio,xorg,xiwi,x11,extension,keyboard,core,touch
host: version 13020.44.0 (Official Build) beta-channel coral 
kernel: Linux localhost 4.4.217-17430-g387e55c6a0e3 #1 SMP PREEMPT Mon May 11 02:09:50 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
hi all, I've recently upgraded my chroot to ubuntu focal (which is not supported yet) and after a few tweaks, manage to make everything working. I still have a little problem though:
whatever I try, my steam games are pretty laggy, which was not the case in bionic. i've tried several config in `/usr/share/X11/xorg.conf.d/xorg-intel-sna.conf` (I had to copy the file from `/etc/crouton` as it was not working from here)
It now look like this: 
```
Section "Device"
   Identifier "Intel Graphics SNA+TearFree"
   Driver     "intel"
#   Driver     "modesetting"
   Option     "AccelMethod" "uxa"
   Option     "TearFree"    "true"
EndSection
```
which is giving  me the right result from glxinfo:
```
glxinfo | grep vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: Intel
```
but glxgears and steam just wont run:
```
Abandon (core dumped)
```
if I try modesetting driver,  glxgears will run at ~160 fps, but steam is very laggy.
and i get `VMWare` in the vendor of `glxinfo`
I've also tried switching `Option "AccelMethod" "uxa"` to `Option "AccelMethod" "sna"` with similar kind of results
If you have any clue or resources to help me with that, I'll be glad.
thanks a lot

**Comment by akabaka74** [comment]
small up
nobody got any ideas on that? do I need to leave more infos?

**Comment by divx118** [comment]
Do you use your chroot in a chrome tab? Xiwi? https://github.com/dnschneid/crouton/blob/master/README.md#i-want-to-open-my-desktop-in-a-window-or-a-tab-but-i-dont-have-the-xiwi-targetxmethod

**Comment by akabaka74** [comment]
Hi,
Thanks for taking time to reply.
No I'm using it normally (using Ctrl+alt+shift+left/right arrow to switch back and forth)
Do you think it can make a difference?
I can try with xiwi if so.

**Comment by divx118** [comment]
@akabaka74 Then it is ok, you are using xorg. xiwi doesn't have hardware acceleration. It could be that you are missing some kernel module. Only kernel modules bundled with chromeos are available.
Problem also is you are sharing resources with chromeos.
IMHO if you want to do something resource heavy on a chromebook, best is to install a dual boot with for example gallium OS https://wiki.galliumos.org/Installing
Then you have access to all the kernel modules that are maybe needed and you won't have to share your resources with chromeos.
Just my 2 cents, maybe someone else has another better idea.

**Comment by akabaka74** [comment]
Thanks for the reply, but I don't think it's related to that as that issue
was not here in 14.04, appears in 16.04, then disappear in 18.04 and
reappeared in 20.04 so I'm pretty sure it's just related to some
driver/configuration/something else that is different between releases. I'm
not familiar enough with xorg stuff to find it yet.
I will check around kernel module to see if I can spot any differences
between the versions

**Comment by divx118** [comment]
@akabaka74 Ok, that wasn't clear to me if it works in ubuntu 18.04 then I guess it should be possible to let it work in 20.04. I would go and check changes in xorg config files between ubuntu 18.04 and 20.04 and or xorg/driver updates between the 2.
Sorry I can't help you much.

**Comment by k2arim99** [comment]
i had issues in bionic with my drivers in the same way and downgrading them mesa:dri to 18 kindaaa worked but fucked my wine
