### ISSUE TITLE
Unable to enter-chroot

### ISSUE THREAD

**Issue by Zoom1020** [dnschneid/crouton#4288]
`chronos@localhost /media/removable/SD Card $ sudo sh edit-chroot-all`
`sh: 0: Can't open edit-chroot-all`

#### Please describe your issue:
I cannot open executable files ie: `enter-chroot` `startunity` `edit-chroot-all`
I am currently on a Dell Chromebook 11 (CB1C13) and have installed Xenial on a 32gb SD Card. The pathway is `/media/removable/SD Card/` 

Also, 
```
chronos@localhost / $ sudo sh ~/Downloads/crouton -n xenial -u
sh: 0: /home/chronos/user/Downloads/crouton: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
/mnt/stateful_partition/crouton/chroots not found.
/usr/local/chroots/xenial does not exist; cannot update.
Valid chroots:
```
#### If known, describe the steps to reproduce the issue:
No clue.

**Comment by DennisLfromGA** [comment]
@Zoom1020,

If crouton was installed in the root directory on your external media then you should see something like this: 
```
/chroots/xenial/
/bin/
```
The crouton commands like `edit-chroot`, `startunity`, etc. will bein the `/bin/` directory.
So you'll need to launch them like below:
- `chronos@localhost /media/removable/SD Card $ sudo sh /bin/edit-chroot-all`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Zoom1020** [comment]
Yep, thank you sir. Just wasn't in the `/bin/` directory. It's all working now.
