### ISSUE TITLE
sudo sh ~/Downloads/crouton -t xiwi,xfce wont work. I'm trying to turn my Acer Computer Into a Ubuntu Linux Computer

### ISSUE THREAD

**Issue by damianeisold** [dnschneid/crouton#4289]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
```
#### Please describe your issue:
When running the command `sudo sh ~/Downloads/crouton -t xiwi,xfce` the crouton will not download. I got the crouton extension so it should work.

#### If known, describe the steps to reproduce the issue:
Type in `sudo sh ~/Downloads/crouton -t xiwi,xfce` and you'll likely download it.

**Comment by DennisLfromGA** [comment]
@damianeisold,

There are new instructions for installing crouton, the old way doesn't work on 'noexec 'mounts as you've discovered. See the [README](https://github.com/dnschneid/crouton) for more info. but here's an excerpt from it: 

> If you're just here to use crouton, you can grab the latest release from https://goo.gl/fd3zc. Download it to Downloads, pop open a shell (Ctrl+Alt+T, type shell and hit enter), make the installer executable with:
 `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton` 
Then launch it with sudo crouton to see the help text. See the "[examples](https://github.com/dnschneid/crouton#examples)" section for some usage examples.

*Hope this helps,*
-**DennisLfromGA**

**Comment by jmw2017** [comment]
I'm having the exact same issue:
![image](https://user-images.githubusercontent.com/29008293/87112804-c3609580-c23a-11ea-8d1d-7d1779bfa1d6.png)

**Comment by DennisLfromGA** [comment]
@jmw2017,

In the screenshot above it appears that the first time you attempted to install crouton it was successful, it doesn't report success.
But, in subsequent attempts, the same command seems to fail so please make sure when you download crouton you place it in your Downloads folder.

You can check to see if it's installed by entering the following command:
- `ls -l /usr/local/bin/crouton`

That should display the following if it's installed:
```
chronos@localhost ~ $ ls -l /usr/local/bin/crouton
-rwxr-xr-x. 1 root root 4.0K Jul 10 11:28 /usr/local/bin/crouton
```

The `edit-chroot` command failed because you first need to install a chroot using the `crouton` command.

*Hope this helps,*
-**DennisLfromGA**

**Comment by cas9san6o** [comment]
Hi, i start saying that i'm at beginning, i tried to use your instructions @DennisLfromGA 

`sudo install -Dt /user/local/bin -m 755 ~/Downloads/crouton`

but answer for me is 

install: cannot create directory '/user': Read-only file system

so i tried what is written in crouton .txt

Ensure the cache directory is marked as exec. For reasoning, see:
 https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
if ! mountpoint -q "$CACHEDIR"; then
    if ! mount --bind "$CACHEDIR" "$CACHEDIR" \
            || ! mount -o remount,exec "$CACHEDIR"; then
        echo "Unable to change permissions of the cache directory." >&2
    fi
fi

![Screenshot 2022-02-17 03 12 59](https://user-images.githubusercontent.com/99851694/154391437-8cdb9ffa-6ac0-4748-85fd-b62a8a15acce.png)

i'm on a chromebook with intel gemini lake (i only wanted to install ubuntu, i didn't thought i'll be here) thanks

**Comment by DennisLfromGA** [comment]
@cas9san6o,

You may not have noticed but this is a 'closed' issue.

You need to read the installation instructions carefully before typing in the commands.

The installation directory is /**usr**/local/bin NOT /**user**/local/bin

-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@cas9san6o,

Well, now you install a chroot.
See the https://github.com/dnschneid/crouton#examples for examples.

-**DennisLfromGA**
