### ISSUE TITLE
Display rotation issue...

### ISSUE THREAD

**Issue by Niels2468** [dnschneid/crouton#4290]
```
Please paste the output of the following command here: Sudo edit-chroot -all
```
name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20200428114634~master:67dc8d77
release: buster
architecture: arm64
xmethod: xorg
targets: xfce,xorg
host: version 13020.67.0 (Official Build) stable-channel kukui 
kernel: Linux localhost 4.19.113-08544-ge67503bc40df #1 SMP PREEMPT Tue Jun 2 00:44:47 PDT 2020 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...

#### Please describe your issue:
I have been messing around with crouton and so far I like it on my Chromebook duet!
But I do have a problem. Every time I try to change the display rotation in Xfce (I have tried other desktop environments but they all don't really work.) The mouse and keyboard start acting weird with delays. And severe UI glitches. The USB mouse/keyboards seem to work fine. The keyboard problem is only visible on the dot connector keyboard. But there are still severe UI lags which aren't in portrait mode. It would take a second before my mouse movement gets displayed on the screen. By default, the crouton rotation is in portrait mode and I want to put it in landscape mode but it doesn't like that. I needed to change the rotation by the xrandr command because the GUI would just crash my Chromebook. Any suggestions?
(I also have tried different versions like focal fossa and xenial but all  have the same problems.)

#### If known, describe the steps to reproduce the issue:
On a Lenovo Chromebook duet:
Install crouton: sudo crouton -r buster -t xfce
Launch it: Sudo startxfce4
Launch terminal and type: xrandr -o left

**Comment by sonictruth** [comment]
I can confirm this I also tried on the default release. It happens also if you change the rotation from xfce or gnome display settings.
Sometimes it also restarts.

**Comment by kry008** [comment]
This problem is problem with default software in Linux. I have the same problem on normal Linux tablet and I resolve this problem about ten days ago, when I do it again I will post how I do to resolve this issue.
