### ISSUE TITLE
crouton can no longer be run while mounted in /tmp/

### ISSUE THREAD

**Issue by Asternitix** [dnschneid/crouton#4291]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: delta
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/delta...
crouton: version 1-20200428114634~master:67dc8d77
release: buster/bullseye (distro upgrade work in progress.)
architecture: arm64
xmethod: xiwi
targets: audio,xfce,extension,xiwi
host: version 13020.67.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.217-17433-gafff2d852d1f #1 SMP PREEMPT Tue Jun 2 00:50:29 PDT 2020 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/delta...
#### Please describe your issue:
crouton -n delta -u fails because /tmp is no longer a directory scripts can be executed if they are mounted there.

sh: 0: Refusing to exec /tmp/crouton-installer-cache/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
#### If known, describe the steps to reproduce the issue:
run crouton -n $CHROOT_NAME -u on the latest version of ChromeOS, it will fail, enter-chroot will continue to work though.

**Comment by DennisLfromGA** [comment]
@Asternitix,

I just installed a bullseye chroot using the identical targets and then updated the chroot and could not repro this issue. I'm using an x86_64 CPU not ARM but I don't think that matters here.

Have you downloaded a fresh version of crouton and installed it using the new method?

*Hope this helps,*
-**DennisLfromGA**

**Comment by Asternitix** [comment]
Are you using the latest version of ChromeOS?

**Comment by Asternitix** [comment]
@DennisLfromGA Yes, I have. it now works, thank you

**Comment by geometerjr** [comment]
I had this same issue today. Downloading a fresh version of crouton fixed it for me too. Thank you both.
