### ISSUE TITLE
Two Suggestions/Issues

### ISSUE THREAD

**Issue by explodersname** [dnschneid/crouton#4292]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20200428114634~master:67dc8d77
release: bionic
architecture: amd64
xmethod: xorg
targets: x11,extension,keyboard,gnome,core,audio,cli-extra
host: version 13020.55.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 4.19.113-08544-ge67503bc40df #1 SMP PREEMPT Thu May 21 14:09:20 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...

#### Please describe your issue:
Issue/Suggestion 1:
I am trying to make host a server for minecraft and all goes well until port forwarding. Is it an issue on my end? IDK Is it not yet available? IDK Feedback is appreciated.
Issue/Suggestion 2:
After a while the screen goes black and i recieve a lock screen and some things dont work while the chromebook is in this state, for example if im in the queue for the mc server 2b2t it will work for about 5 minutes after it goes black but anytime much longer and i get kicked, whether its a disconnect for internet reasons or whatever im not sure but my point is that it would be appreciated if someone could tell me how to fix this or if its not a feature, then maybe the devs could make an option to keep the screen on or whatever to fix this.

**Comment by DennisLfromGA** [comment]
@explodersname,

- Issue 1 - Chrome OS uses '`iptable`' for the firewall and, by default, just about everything is denied. See this wiki article for opening them up: [Running servers in crouton](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton)

- Issue 2 - It sounds like you may have a screensaver running that is causing this issue.
I would check to see if that's so and disable it if possible.

*Hope this helps,*
-**DennisLfromGA**

**Comment by explodersname** [comment]
I have fixed issue 2, now I need help with issue 1.
I have installed iptables as shown on that wiki article, but now am confused because it says to add a line to /etc/rc.local and would love if someone could give a video tutorial on how to do this (i am a visual learner)
