### ISSUE TITLE
Can't add flatpak repos

### ISSUE THREAD

**Issue by cobalt2727** [dnschneid/crouton#4293]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: neon
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/neon...
crouton: version 1-20200428114634~master:67dc8d77
release: bionic
architecture: amd64
xmethod: xorg
targets: touch,xorg,xiwi,x11,cli-extra,extension,audio,core
host: version 13099.30.0 (Official Build) beta-channel nami 
kernel: Linux localhost 4.4.223-17586-ga94dece9d497 #1 SMP PREEMPT Mon Jun 8 02:48:59 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/neon...
#### Please describe your issue:
I can't add flathub as a flatpak remote to install anything - making flatpaks pretty useless...
Doing some basic research, it looks like some sort of policy kit issue, but I know absolutely nothing about how those work.

#### If known, describe the steps to reproduce the issue:
sudo apt update
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
error: Flatpak system operation ConfigureRemote not allowed for user

**Comment by DennisLfromGA** [comment]
If it doesn't prompt you for the administrator password perhaps you need to add '`--user`' to that command line. Just a guess tho since I don't use flatpaks.

*Hope this helps,*
-**DennisLfromGA**

**Comment by cobalt2727** [comment]
I have to add the user 'root' to the '_flatpak' group for that to work and run it as sudo for the command to execute at all - and even then flatpaks still won't open. Has anyone gotten flatpaks working properly on crouton?
