### ISSUE TITLE
reinstall with trusty, need a mirror? 

### ISSUE THREAD

**Issue by zuotian3619** [dnschneid/crouton#4294]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

no chroots

#### Please describe your issue:

was having trouble with my previous release (xenial). i wanted to install a new chroot with trusty but it says i need a mirror? not sure what this means tbh...

```
chronos@localhost / $ sudo crouton -r trusty -t xfce
WARNING: trusty has reached upstream end-of-life.
That means there will be no package updates available.
You also have to specify a mirror to crouton (-m) for installation to proceed.
```

**Comment by DennisLfromGA** [comment]
@zuotian3619,

It means that the trusty release has reached its end-of-life and normal distro channels are no longer available so trusty should be avoided.

If you still want to use it you can find mirrors here: https://launchpad.net/ubuntu/+archivemirrors

*Hope this helps,*
-**DennisLfromGA**
