### ISSUE TITLE
Password not working?

### ISSUE THREAD

**Issue by clownkitty** [dnschneid/crouton#4295]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
```

#### Please describe your issue:   
No matter what I do, it doesn't accept my password? The first time I didn't specify a password for the debugging, and test0000 was not being accepted. The second time I specified a password and that's not being accepted either.

**Comment by DennisLfromGA** [comment]
@clownkitty,

Yes, that's the correct behavior if you've enabled Debugging Features.
See if this helps: #2050 (comment)

*Hope this helps,*
-**DennisLfromGA**

**Comment by clownkitty** [comment]
so i should do it again and then not enable the debugging? :0

**Comment by DennisLfromGA** [comment]
@clownkitty,

If the comment I linked above doesn't help and you can't first login as root and supply a valid password then, yes, I suppose you may have to powerwash your device losing any files, folders, & chroots you haven't backed up and start over. Only this time do *not* enable Debugging Features at the OOBE screen.

FYI: You can enable any or all of the Debugging Features after you sign-in to your account profile by running the below debugd/helper scripts as root:
```
/usr/libexec/debugd/helpers/dev_features_chrome_remote_debugging
/usr/libexec/debugd/helpers/dev_features_password
/usr/libexec/debugd/helpers/dev_features_rootfs_verification
/usr/libexec/debugd/helpers/dev_features_ssh
/usr/libexec/debugd/helpers/dev_features_usb_boot
```
*Hope this helps,*
-**DennisLfromGA**
