### ISSUE TITLE
ubuntu 18.04 - 20.4

### ISSUE THREAD

**Issue by YuiFoxx** [dnschneid/crouton#4299]
hi i was just wondering is there a newer version of ubuntu such as 18.04 or 20.4 of which i can download to my chromebook

**Comment by DennisLfromGA** [comment]
@YuiFoxx,

Yes, there is.

Although xenial / 16.04 is the default release for crouton, other releases are available to download.
You can see them by entering: `sudo crouton -r list`, see below for the Ubuntu releases -
```
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty! utopic! vivid! wily! xenial yakkety! zesty! artful! bionic* cosmic!
    disco! eoan* focal*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```
You'll have to translate the release name to the number tho, see '[List of releases](https://wiki.ubuntu.com/Releases)'. But, bionic, eoan, & focal are newer releases that can be downloaded. The caveat, 'they are unsupported, but may work with some effort.'

*Hope this helps,*
-**DennisLfromGA**
