### ISSUE TITLE
Ubuntu problem

### ISSUE THREAD

**Issue by Okstate14** [dnschneid/crouton#4300]
When ever I try to download ubuntu I get this

 sudo sh ~/downloads/crouton -r trusty -t xfce
sh: 0: Can't open /home/samuelkosu/downloads/crouton

Please help me I am trying to get wine!!

**Comment by DennisLfromGA** [comment]
@Okstate14,

Couple of things I see wrong with that.
1. There's a new method for installing and using the crouton installer.
See this for details: https://github.com/dnschneid/crouton#usage
2. Linux is case sensitive so 'downloads' should be **D**ownloads.

*Hope this helps,*
-**DennisLfromGA**
