### ISSUE TITLE
i936 driver issue on bionic in a old 2013 pixel

### ISSUE THREAD

**Issue by k2arim99** [dnschneid/crouton#4303]
```
crouton: version 1-20200428114634~master:67dc8d77
release: bionic
architecture: amd64
xmethod: xorg
targets: x11,extension,keyboard,xorg,kodi,xiwi,gnome,xfce,unity,touch
host: version 10895.56.0 (Official Build) beta-channel link 
kernel: Linux localhost 3.8.11 #1 SMP Wed Sep 12 23:58:05 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
the i936 driver doesnt work even tho the drivers are installed and the card can be detected, mpv only lets me use the x11 legacy driver and all programs that can use acceleration  just print me 
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
my Xorg.crouton.log http://s000.tinyupload.com/index.php?file_id=00663924309126429776
a relevant bit
```

[   544.540] (II) intel(0): [DRI2] Setup complete
[   544.540] (II) intel(0): [DRI2]   DRI driver: i965
[   544.540] (II) intel(0): [DRI2]   VDPAU driver: va_gl
[   544.540] (II) intel(0): direct rendering: DRI2 enabled
[   544.540] (II) intel(0): hardware support for Present enabled
[   544.540] (--) RandR disabled
[   544.546] (II) SELinux: Disabled on system
[   544.566] (EE) AIGLX error: Calling driver entry point failed
[   544.567] (EE) AIGLX: reverting to software rendering
[   544.610] (II) IGLX: enabled GLX_MESA_copy_sub_buffer

```
any help would be apreciated

**Comment by abliss** [comment]
I had the same issue, and could not get hardware acceleration to work in bionic. In xenial it still works fine, though.

**Comment by k2arim99** [comment]
hello!
you downgraded?

**Comment by abliss** [comment]
Yeah, I abandoned my bionic chroot and went back to using xenial.

**Comment by k2arim99** [comment]
damn i should have tested before updating my main chroot to bionic

**Comment by k2arim99** [comment]
if someone has a hack to make it work i would apreciate it a lot (downgrading?) that im kinda unable to make a new chroot and pass everything, nevertheless this should be added to the wiki that bionic doesnt work

**Comment by k2arim99** [comment]
oh and kodi doesnt acelerate

**Comment by k2arim99** [comment]
i recommend to put a disclaimer about how not to update to bionic with a pixel 2013 in the faq or some place

**Comment by DennisLfromGA** [comment]
@k2arim99,

Since bionic is not a release supported in crouton and [will never be](https://github.com/dnschneid/crouton/issues/4265#issuecomment-620366138), I don't think a warning is warranted.

*Hope this helps,*
-**DennisLfromGA**

**Comment by k2arim99** [comment]
> @k2arim99,
> 
> Since bionic is not a release supported in crouton and [will never be](https://github.com/dnschneid/crouton/issues/4265#issuecomment-620366138), I don't think a warning is warranted.
> 
> _Hope this helps,_
> -**DennisLfromGA**

Oh im sorry didn't read that it would never be supported, I will close
Cheers

**Comment by abliss** [comment]
Good news @k2arim99 : on my chromebook pixel 2013 , hardware acceleration seems to work on Focal. (however, the i915 kernel driver seems to be quite buggy, so GPU-intensive workloads seem to qucikly cause GPU hangs.) (Also, watch out for #4338 if you try Focal right now.)

**Comment by k2arim99** [comment]
Thanks! I will have it into consideration when I once again migrate to a higher ubuntu version
