### ISSUE TITLE
Unable to switch back to Linux 

### ISSUE THREAD

**Issue by TheRealFanjin** [dnschneid/crouton#4309]
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xfcefocal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xfcefocal...
crouton: version 1-20200428114634~master:67dc8d77
release: focal
architecture: amd64
xmethod: xorg
targets: core,audio,keyboard,extension,touch,xfce,xorg
host: version 13099.62.0 (Official Build) beta-channel octopus 
kernel: Linux localhost 4.14.180-15210-gd513939c7dc9 #1 SMP PREEMPT Tue Jul 7 02:15:25 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xfcefocal...
```

#### Please describe your issue:
Sometimes when I switch back to ChromeOS from Linux, I am unable to switch back to Linux with Ctrl+Alt+>. It only happens about 1/4 of the time but it still gets annoying because I have to Ctrl+C it and lose my opened apps and stuff. It is similar to [https://github.com/dnschneid/crouton/issues/870](url) but when they switch it partially switches but when I try to switch nothing happens.

#### If known, describe the steps to reproduce the issue:
Just go back and forth between Linux and ChromeOS a few times?

**Comment by DennisLfromGA** [comment]
@TheRealFanjin,

The <kbd>***Shift***</kbd> was added to the key-combo *years* ago.

When you installed your chroot you may have missed this xorg 'tip' when it completed:
> You can flip through your running chroot desktops and Chromium OS by hitting
> <kbd>**Ctrl**</kbd>+<kbd>**Alt**</kbd>+<kbd>**Shift**</kbd>+<kbd>**Back**</kbd> 
> and   
> <kbd>**Ctrl**</kbd>+<kbd>**Alt**</kbd>+<kbd>**Shift**</kbd>+<kbd>**Forward**</kbd>

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheRealFanjin** [comment]
Oh, I'm sorry! I meant Ctrl+Alt+Shift+Back. Whenever I press that nothing happens

**Comment by killshot13** [comment]
Have you considered installing [xiwi](https://github.com/dnschneid/crouton/wiki/crouton-in-a-Chromium-OS-window-(xiwi)) with [extension](https://www.linuxuprising.com/2018/12/crouton-how-to-run-linux-applications.html)? When incorporated with the [crouton extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) available in the Chrome Web Store, it provides a much easier way to switch between Linux and Chrome without using those damn key combos.

**Comment by DennisLfromGA** [comment]
To add, you might be able to just add the 'extension' target along with the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension and use it to switch without actually installing the 'xiwi' method.   

In the chroot you can use this command in the terminal to switch to Chrome OS:  
- `croutoncycle cros`

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheRealFanjin** [comment]
@killshot13 Yeah I have used it before but I'm not a big fan of it because I mostly use the chroot in fullscreen and whenever I do that a big x always drops down when I hover my mouse at the top of the screen.
@DennisLfromGA What exactly do you mean? I have the extension but I thought it was only for copy/pasting in between the chroot and ChromeOS?

**Comment by DennisLfromGA** [comment]
@TheRealFanjin,

If you also install the 'crouton integration' extension, linked above, you can switch into active chroots with it from the browser toolbar, see below:

![Screenshot 2020-07-14 at 5 03 56 PM](https://user-images.githubusercontent.com/3418772/87476556-91618180-c5f4-11ea-859d-328b5948b1e6.png)


*Hope this helps,*
-**DennisLfromGA**

**Comment by TheRealFanjin** [comment]
@DennisLfromGA Wow, I didn't know that! Thank you so much!

**Comment by TheRealFanjin** [comment]
@DennisLfromGA It happened a few times again, I wasn't able to switch back to Linux with Ctrl+Alt+Shift+Forward, and this time I checked the extension and it didn't have the croot even though the croot is still running:
![Screenshot 2020-07-17 at 12 17 09 PM](https://user-images.githubusercontent.com/58857369/87813431-893d5800-c827-11ea-920d-23eac402b99e.png)
![Screenshot 2020-07-17 at 12 14 58 PM](https://user-images.githubusercontent.com/58857369/87813463-95291a00-c827-11ea-84d7-8e271d8aa092.png)

**Comment by DennisLfromGA** [comment]
@TheRealFanjin,

I'm not sure what to tell you since I can't repro it. 

Perhaps install the 'xiwi' method with a crouton update and the 'crouton integration' extension will then show your chroot. You can still use 'xorg' when you launch your desktop with:
- `sudo startxfce4 -n xfcefocal -X xorg`

*Hope this helps,*
-**DennisLfromGA**
