### ISSUE TITLE
crouton on chrome os canary 86

### ISSUE THREAD

**Issue by mjonsson1986** [dnschneid/crouton#4310]
is crouton realy usable on chrome os canary 86?
i can create a chroot like this:
crouton -r sid -t gnome-desktop -t audio -t xorg
and start it with startgnome
but seems i cant do anything with it
hmm?
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by TheRealFanjin** [comment]
You didn't paste the output of `sudo edit-chroot -all`. That's kind of necessary in order for us to help you.

**Comment by MrHallway0** [comment]
Are you running `startgnome` as `root`?
