### ISSUE TITLE
Unset passcode.

### ISSUE THREAD

**Issue by genevieve666** [dnschneid/crouton#4311]
I didn't set a passcode and now the xfce won't allow me to download anything due to the fact that I never set a passcode. Is there any way for me to set one now? Thanks.

**Comment by DennisLfromGA** [comment]
@genevieve666,

Sorry, I need more details.

You didn't set a passcode for what exactly -
- for the chroot user?
- for a chroot encryption key?
- for Chrome OS?

Can you get into your chroot?
If so, you can enter it as root and set a password for the user. 
Let us know if this is what you want and we'll try to help.

-**DennisLfromGA**
