### ISSUE TITLE
Ubuntu 20.04 support?

### ISSUE THREAD

**Issue by JakunGamer** [dnschneid/crouton#4313]
Will Ubuntu 20.04 focal support crouton?

**Comment by DennisLfromGA** [comment]
@JakunGamer,

Ubuntu 20.04 **eoan** is available to install in crouton, see below:
```
chronos@localhost ~ $ crouton -r list
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy! jessie stretch buster
    bullseye sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty! utopic! vivid! wily! xenial yakkety! zesty! artful! bionic* cosmic!
    disco! eoan* focal*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```
Notice though that eoan has an asterisk appended to it so it's currently unsupported.

This was brought up recently in issue #4265 and the crouton author [explained the situation](https://github.com/dnschneid/crouton/issues/4265#issuecomment-620366138), see below:

> We have pretty limited time to go through and repair all the compatibility issues that appear in each release, so we've been sticking to every-other LTS as the default crouton one and try to make that work as well as we can. Focal would be the next on the list, but it'll come down to when @drinkcat and I can allocate a week to hash it out. Rest assured it'll be sometime before April 2021 :)

In that same issue another user [stated this](https://github.com/dnschneid/crouton/issues/4265#issuecomment-620500414) about eoan:
> I just tried installing Focal, but I was met with a sed error. eoan works just fine.

So, it may work for you without too much effort, I hope so.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TheRealFanjin** [comment]
Isn't 20.04 called Focal Fossa

**Comment by DennisLfromGA** [comment]
@TheRealFanjin,

Thanx, I updated my reply above.

-**DennisLfromGA**

**Comment by JakunGamer** [comment]
> @TheRealFanjin,
> 
> Thanx, I corrected & updated my reply above.
> 
> -**DennisLfromGA**



> @JakunGamer,
> 
> Ubuntu 20.04 **focal** _**and**_ 19..10 **eoan** are available to install in crouton, see below:
> 
> ```
> chronos@localhost ~ $ crouton -r list
> Recognized debian releases:
>     potato! woody! sarge! etch! lenny! squeeze! wheezy! jessie stretch buster
>     bullseye sid
> Recognized kali releases:
>     moto! kali! sana! kali-rolling
> Recognized ubuntu releases:
>     warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
>     karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
>     trusty! utopic! vivid! wily! xenial yakkety! zesty! artful! bionic* cosmic!
>     disco! eoan* focal*
> Releases marked with ! are upstream end-of-life, and should be avoided.
> Releases marked with * are unsupported, but may work with some effort.
> ```
> 
> Notice though that eoan & focal have an asterisk appended to them so they're currently unsupported.
> 
> This was brought up recently in issue #4265 and the crouton author [explained the situation](https://github.com/dnschneid/crouton/issues/4265#issuecomment-620366138), see below:
> 
> > We have pretty limited time to go through and repair all the compatibility issues that appear in each release, so we've been sticking to every-other LTS as the default crouton one and try to make that work as well as we can. _**Focal would be the next on the list**_, but it'll come down to when @drinkcat and I can allocate a week to hash it out. Rest assured it'll be sometime before April 2021 :)
> 
> In that same issue another user [stated this](https://github.com/dnschneid/crouton/issues/4265#issuecomment-620500414) about **eoan**:
> 
> > I just tried installing Focal, but I was met with a sed error. **eoan** works just fine.
> 
> So, it may work for you without too much effort, I hope so.
> 
> _Hope this helps,_
> -**DennisLfromGA**

Thank you man
I have encountered an error (maybe) 
Tried Ubuntu 20.04
Needed to restart to update dbus
But in chroot, there's no restart
Any solution?

**Comment by TheRealFanjin** [comment]
@JakunGamer  Yeah, a lot of people have been talking about the restarts. I think I came across that once, but I don't remember how I solved it. I think I just restarted Chrome OS and installed it again. 
For example, if you do `sudo crouton -r focal` and it asks for a restart, restart your chromebook and do the same command again

**Comment by JakunGamer** [comment]
> @JakunGamer Yeah, a lot of people have been talking about the restarts. I think I came across that once, but I don't remember how I solved it. I think I just restarted Chrome OS and installed it again.
> For example, if you do `sudo crouton -r focal` and it asks for a restart, restart your chromebook and do the same command again

Thanks man
Will try

**Comment by JakunGamer** [comment]
Alright it worked

**Comment by JakunGamer** [comment]
Alright everything worked

**Comment by JakunGamer** [comment]
OK things worked. Will close this issues. Thank you for helping me
