### ISSUE TITLE
Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by qaqak** [dnschneid/crouton#4314]
#### Please describe your issue:

How do I get Ubuntu 20.04 LTS on my Chromebook?

**Comment by DennisLfromGA** [comment]
@qaqak,

One of the two pinned issues discusses Focal Foosa (  20.04 LTS ) -

![image](https://user-images.githubusercontent.com/3418772/87977863-6d42ec00-ca9d-11ea-8003-3f5e42201b3d.png)

It's available to install in crouton by using the '`-r focal`' option; it's currently unsupported but may work with some effort.

*Hope this helps,*
-**DennisLfromGA**

**Comment by qaqak** [comment]
It said UID 100 not found in focal

**Comment by DennisLfromGA** [comment]
@qaqak,

That means it's failing before it sets up a user account.
Please track and follow-up on this issue on the original Focal Foosa issue #4265.

*Hope this helps,*
-**DennisLfromGA**
