### ISSUE TITLE
Ubuntu 18.04 wake-suspend issue on Galaxy Chromebook (Kohaku)

### ISSUE THREAD

**Issue by pairwiserr** [dnschneid/crouton#4315]
#### Please describe your issue:
When laptop goes to sleep/suspend mode for the second time, I cannot get it to wake. The power LED remains ON even when it presumably went into sleep/suspend mode (i.e., screen turns off). I lose my entire session and have to force shutdown using power button.

This is on ChromeOS 80 (stable channel). I installed crouton via
```
sudo crouton -r bionic -t audio,chromium,cli-extra,core,gnome,gtk-extra,keyboard,touch,x11,xorg
```
Due to installation errors, I've followed this [solution](https://github.com/dnschneid/crouton/issues/3995#issuecomment-641595888).

Also installed `gdm3`: `sudo apt-get install gdm3` thinking that it was a display manager issue.

#### If known, describe the steps to reproduce the issue:

Let laptop go to sleep for ~ 20 minutes and wake it up. Let laptop go to sleep again for ~ 20 minutes and wake it up. The laptop can be plugged in to adapter or in battery mode.

**Comment by DennisLfromGA** [comment]
@pairwiserr,

Does it respond or awaken if you open the Developer Console using the key-combo <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Forward/F2</kbd> ?
If so, then just switch back to CrOS using the key-combo <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Back/F1</kbd>

As a workaround, you could also adjust the Power settings under 'Settings -> Power' to just turn off the display instead of going to sleep, see below:
![image](https://user-images.githubusercontent.com/3418772/88056324-5f897700-cb2e-11ea-8f80-dafa6d3bf200.png)

*Hope this helps,*
-**DennisLfromGA**

**Comment by pairwiserr** [comment]
Thanks for your reply, @DennisLfromGA .

> Does it respond or awaken if you open the Developer Console using the key-combo Ctrl+Alt+Forward/F2 ?

No. Neither does Alt+F3 for lock screen prompt. Thankfully, only turning off display when idle has fixed the issue. Still I hope I can get to the bottom of what was causing the issue. I found this [AskUbuntu post](https://askubuntu.com/questions/1029405/ubuntu-18-04-crashes-on-resuming-from-suspend?newreg=c68b8dedf5c9462ca5259cbff9e3aeab) describing a similar issue.

**Comment by DennisLfromGA** [comment]
@pairwiserr,

Glad the workaround helped.

The no awakening after the second sleep is strange and maybe device-specific, I don't think we've run into this issue before.
The AskUbuntu comments seem to point to an issue with the kernel that may be causing it.
At this point, I think it might be best to file a [crbug](http://crbug.com/new) and see if this issue can be rooted out & fixed.

I'm closing this for now.

-**DennisLfromGA**

**Comment by pairwiserr** [comment]
@DennisLfromGA , I realized that this is not a crouton issue. I face the same issue in ChromeOS. It may be that I have a defective unit.

**Comment by DennisLfromGA** [comment]
@pairwiserr,

Oh, I hope not.

I think filing a crbug is a good approach for this problem.
If you do decide to file one please let us know so we can track it.

-**DennisLfromGA**
