### ISSUE TITLE
Chroot in a chroot

### ISSUE THREAD

**Issue by qaqak** [dnschneid/crouton#4317]
Can I put a chroot inside a chroot?

**Comment by DennisLfromGA** [comment]
I suppose you can put a chroot in a chroot but not a crouton chroot.
It would probably depend on what folders and function you need in the sub-chroot.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
@qaqak,

> Are there any other chroot systems or is crouton the only one?

There are others, specifically, what do you want?

If you want to know the basics, Google is your friend:
- https://help.ubuntu.com/community/BasicChroot

*Hope this helps,*
-**DennisLfromGA**
