### ISSUE TITLE
where is the download link?

### ISSUE THREAD

**Issue by Acidic-x** [dnschneid/crouton#4322]
i literally just cant find the download link

**Comment by DennisLfromGA** [comment]
@Acidic-x 

At the right side of the [main page](https://github.com/dnschneid/crouton), see below:
![Screenshot 2020-07-30 at 1 18 18 PM](https://user-images.githubusercontent.com/3418772/88953803-6ff4cc80-d267-11ea-9e2b-a635f717ce39.png)

Here's the link: [https://goo.gl/fd3zc](https://goo.gl/fd3zc)
See [Usage](https://github.com/dnschneid/crouton#usage) for installations instructions.

*Hope this helps,*
-**DennisLfromGA**
