### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Acidic-x** [dnschneid/crouton#4323]
Is there a way to install manjaro instead of ubuntu on it? I can't find any decent tutorials on downloading manjaro through crouton for chrome OS

**Comment by DennisLfromGA** [comment]
@Acidic-x,

No, manjaro is not a supported or unsupported release.
The releases that you can install using crouton are listed below, some are supported, some are not -

```
chronos@localhost ~ $ crouton -r list
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy! jessie stretch buster
    bullseye sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty! utopic! vivid! wily! xenial yakkety! zesty! artful! bionic* cosmic!
    disco! eoan* focal*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```


The manjaro release has been equested before and a fork of it was started but no progress has been made on it in years.
See the below issues below for more details and please follow up with any questions on issue #4046 -

> Manjaro · Issue #4046 · dnschneid/crouton
> https://github.com/dnschneid/crouton/issues/4046

> manjaro installation instructions · Issue #2722 · dnschneid/crouton
> https://github.com/dnschneid/crouton/issues/2722

> Adding Manjaro as a release · Issue #688 · dnschneid/crouton
> https://github.com/dnschneid/crouton/issues/688

*Hope this helps,*
-**DennisLfromGA**
