### ISSUE TITLE
Gnome issues

### ISSUE THREAD

**Issue by explodersname** [dnschneid/crouton#4324]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
I have installed ubuntu 18.04 using this wiki: https://github.com/dnschneid/crouton/wiki/3-Steps-to-Install-Bionic-Beaver and installed gnome and xorg with it, I have done this several times before but only now is it giving me this response whilst typing the command sudo startgnome: No chroots with target 'gnome' found in /mnt/stateful_partition/crouton/chroots
Edit: I have tried renaming the chroot to gnome and it still doesnt work

**Comment by DennisLfromGA** [comment]
@explodersname ,

We ask that you please show us the output of the following command: `sudo edit-chroot -all`
That will tell us, among other things, what release and targets/desktops you installed and what device you have. 
With that info. we can may be able to tell why your `startgnome` command is failing.

*Hope this helps,*
-**DennisLfromGA**
