### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Acidic-x** [dnschneid/crouton#4325]
On how to switch versions of ubuntu is very vague, where do I put the version i want to boot and the -r, a base command would be good

**Comment by DennisLfromGA** [comment]
@Acidic-x,

You can't really *switch* versions, you may be able to upgrade a version, see:
- [To upgrade to a more recent version of Ubuntu](https://github.com/dnschneid/crouton/wiki/Upgrade-chroot-release#to-upgrade-to-a-more-recent-version-of-ubuntu)

Upgrading in place doesn't always turn out well tho.

You can install a new chroot with the release of your choice and it's probably the best way to get the release/verson that you want. The releases that you can install using crouton are listed below, some are supported, some are not -

```
chronos@localhost ~ $ crouton -r list
Recognized debian releases:
    potato! woody! sarge! etch! lenny! squeeze! wheezy! jessie stretch buster
    bullseye sid
Recognized kali releases:
    moto! kali! sana! kali-rolling
Recognized ubuntu releases:
    warty! hoary! breezy! dapper! edgy! feisty! gutsy! hardy! intrepid! jaunty!
    karmic! lucid! maverick! natty! oneiric! precise! quantal! raring! saucy!
    trusty! utopic! vivid! wily! xenial yakkety! zesty! artful! bionic* cosmic!
    disco! eoan* focal*
Releases marked with ! are upstream end-of-life, and should be avoided.
Releases marked with * are unsupported, but may work with some effort.
```

As you alluded to, you can use the '`-r`' option to install the release of your choice.
One example of that using the 'bionic' release is shown below:
- `sudo crouton -r bionic -t xiwi,cli-extra,keyboard,touch,lxde-desktop`

*Hope this helps,*
-**DennisLfromGA**
