### ISSUE TITLE
How to switch distros?

### ISSUE THREAD

**Issue by Acidic-x** [dnschneid/crouton#4326]
The command only showcases how to install ubuntu, and as someone pretty new to linux im just wondering how i could switch to something such as debian. (We don't talk about kali)

**Comment by DennisLfromGA** [comment]
Asked & answered here: HELP #4325

**Comment by Acidic-x** [comment]
Bruh

**Comment by DennisLfromGA** [comment]
Sorry, but what is not addressed in issue #4325 that you are still unsure about? 🤔
I've listed the recognized debian releases and told you how you can use the '-r' option to install the release of your choice.

-**DennisLfromGA**
