### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Acidic-x** [dnschneid/crouton#4327]
What command would I have to run if i wanted something besides ubuntu with xenial? Like what if I wanted something such as debian?

**Comment by DennisLfromGA** [comment]
Asked and answered in #4325 & #4326.

Please do not open multiple issues with the same or similar questions.
I asked what you were unsure about [here](https://github.com/dnschneid/crouton/issues/4326#issuecomment-669270309) and you did not respond.

-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
You might find the subreddit [r/crouton](https://www.reddit.com/r/Crouton/) of help too.
Here's [a thread](https://www.reddit.com/r/Crouton/comments/hlexgu/how_to_install_debian_9/fwzvs78?utm_source=share&utm_medium=web2x) asking about installing a Debian release in crouton:

> (1) How to install Debian 9? : Crouton
> https://www.reddit.com/r/Crouton/comments/hlexgu/how_to_install_debian_9/

*Hope this helps,*
-**DennisLfromGA**
