### ISSUE TITLE
open usb drive on crouton

### ISSUE THREAD

**Issue by Jonyk56** [dnschneid/crouton#4330]
#### Please describe your issue:
I am having troubles trying to open a usb in crouton ( which is on a usb aswell, idk if this affects anything ), the usb i'm trying to open is ext4, and is 128gb in terms of storage, is there a way for it to be even opened?

#### If known, describe the steps to reproduce the issue:
plug in any usb whilst crouton is open, and you can't access it

**Comment by DennisLfromGA** [comment]
I thought external media would show up under `/media/removable/` so check there.
On my system it didn't show up under `/media/removable/` but it did show up where CrOS mounted it and I'm able to access it there, see below:
```
(bionic)dennyl@localhost:~$ ll /media/removable
lrwxrwxrwx. 1 root root 25 Aug 13 14:58 /media/removable -> /var/host/media/removable/
(bionic)dennyl@localhost:~$ 
(bionic)dennyl@localhost:~$ mount|grep sda
/dev/sda on /var/host/media/removable/Pop_OS 20.04 amd64 type iso9660 (ro,nosuid,nodev,noexec,relatime,utf8,uid=1000,gid=1000)
(bionic)dennyl@localhost:~$ 
(bionic)dennyl@localhost:~$ ll /var/host/media/removable/
total 2.0K
dr-xr-xr-x. 1 dennyl dennyl 2.0K Jul  2 16:58 'Pop_OS 20.04 amd64'/
(bionic)dennyl@localhost:~$ 
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by Jonyk56** [comment]
ok, so, i have seen this aswell..... any time i try to access it, no matter what, i always get 'permission denied'
![Screenshot_2020-08-14_20-27-35](https://user-images.githubusercontent.com/44901605/90301234-a4be7180-de6c-11ea-862c-87d700f68fb9.png)

**Comment by DennisLfromGA** [comment]
@Jonyk56,

Check out the ownership and permissions of the root directory in the external media with:
- `ls  -ld  /var/host/media/dstorage` 
- or just if it works for you -
- `ls  -ld  /media/dstorage` 

You may have to change at least the ownership to 'jonyk5' with:
- `sudo  chown  jonyk5:root   /media/dstorage` 

You can use the '`-R`' option to `chown` to change the ownership on *all* subdirectories too.
If the permissions aren't set to executable in the directories you need then use `chmod` to change them too.

Also, if `/media/removable/dstorage` is mounted 'noexec' you may need to remount with exec permissions.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Jonyk56** [comment]
ok, also, one quick question, do i do the chown in crouton, or shell?

**Comment by Jonyk56** [comment]
the entirety of this is explained here:

https://github.com/dnschneid/crouton/wiki/Access-external-drive-from-crouton
