### ISSUE TITLE
Making the installer executable isn't working on a chromebook.

### ISSUE THREAD

**Issue by Ackoroth** [dnschneid/crouton#4334]
#4316 ## Please describe your issue: Hello! Currently I'm trying to install crouton for the first time on a chromebook, and the command `sudo install -Dt /usr/local/bin -m 755` isn't working. Whenever I enter it, it says 

> install: target '/usr/local/bin' is not a directory

I know nothing about computers, so I might be doing something wrong, but everything seems to be right. If anyone could help that would be great!

#### If known, describe the steps to reproduce the issue: 
![Screenshot 2020-08-23 at 11 21 08 AM](https://user-images.githubusercontent.com/70109083/90985748-c685bb80-e532-11ea-8a12-2ee2aa640bd7.png)

**Comment by DennisLfromGA** [comment]
@Ackoroth,

It appears from your screenshot that the command your using is not complete, the path to crouton was not entered.
Try this: 
- `sudo install -Dt /usr/local/bin -m 755`**`~/Downloads/crouton`**

You can copy-n-paste it if you like. 
It assumes that crouton was downloaded to the ~/Downloads folder, if you placed it somewhere else then use that path.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Ackoroth** [comment]
> @Ackoroth,
> 
> It appears from your screenshot that the command your using is not complete, the path to crouton was not entered.
> Try this:
> 
> * `sudo install -Dt /usr/local/bin -m 755`**`~/Downloads/crouton`**
> 
> You can copy-n-paste it if you like.
> It assumes that crouton was downloaded to the ~/Downloads folder, if you placed it somewhere else then use that path.
> 
> _Hope this helps,_
> -**DennisLfromGA**

Thanks for the reply! Sadly the problem is still happening even with the correct command. I'll try and figure it out with my limited code knowledge.

**Comment by DennisLfromGA** [comment]
@Ackoroth,

Hmmm, are you still getting that error message or a different one?
Are you sure you downloaded [crouton](https://goo.gl/fd3zc) and placed it in `~/Downloads`?
If you enter `ls -l /usr/local/bin/crouton` do you see what I show below?:
```
ls -l /usr/local/bin/crouton
-rwxr-xr-x. 1 root root 4.0K Jul 28 13:59 /usr/local/bin/crouton
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by Ackoroth** [comment]
@DennisLfromGA 

When I enter `ls -l /usr/local/bin/crouton` it says the same error as seen previously, that /usr/local/bin isn't a directory. I tried using mkdir to make it one, but it said that I can't make it because its an existing file. Thank you for your help though! I appreciate it!

**Comment by DennisLfromGA** [comment]
@Ackoroth,

Okay, that makes sense. Somehow it created a '`bin`' file instead of a directory.
Here's what I'd suggest -
1. `cd /usr/local/`
2. `sudo mv ./bin ./bin.bak`
3. `sudo mkdir -p /usr/local/bin/`
4. `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`
5. `ls -l /usr/local/bin/crouton`

That should now show that `crouton` is installed.
You can probably leave `bin.bak` file alone or remove it if you like.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Ackoroth** [comment]
YES! It worked! Thank you so, so much!
