### ISSUE TITLE
cant enter password after enter "sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton"

### ISSUE THREAD

**Issue by deathslayer1325** [dnschneid/crouton#4336]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
```
#### Please describe your issue:
after entering `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton` it wont let me type a password in

#### If known, describe the steps to reproduce the issue:
just enter the command again

**Comment by DennisLfromGA** [comment]
@deathslayer1325,

By default, there is no password for chronos or for your chroot unless you encrypt it.

Where are you prompted for a password, when you enter the shell, when you install the chroot, etc.?
What command are you using to install the chroot?

A screenshot and/or more details might help us troubleshoot this issue.

*Hope this helps,*
-**DennisLfromGA**

**Comment by WatsonHasAKnife** [comment]
is it not displaying what you type? if so, thats because thats how it works. instead of replacing the letters with an asterisk (*) it just doesnt display text. type your password then hit enter.

hope this helps!

**Comment by DennisLfromGA** [comment]
Closing. No response or follow-up (needed) at this time.

-**DennisLfromGA**
