### ISSUE TITLE
failed ubuntu download on acer chromebook.

### ISSUE THREAD

**Issue by BananaRama238** [dnschneid/crouton#4339]
#### Please paste the output of the following command here: sudo edit-chroot -all
```name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 11316.165.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.83-08247-g66ab05738a89 #1 SMP PREEMPT Sun Mar 3 23:08:03 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:   
hello there, im a total noob to all this stuff so forgive me for having a really silly problem. So I wanted to play steam games on my chromebook, but obviously i cannot do that without ubuntu or some other OS. So i followed the tutorial and felt like i was nearly done, then was told that the chroot setup failed, but wasnt given an issue number. i looked online and was showed some things to enter when facing this problem (sudo apt-get install -f for example) and i always get hit with command not found. I dont knowif im entering something wrong or whats up. any and every piece of help is appreciated. thank you all!_

**Comment by DennisLfromGA** [comment]
@BananaRama238,

> i looked online and was showed some things to enter when facing this problem (`sudo apt-get install -f` for example) and i always get hit with command not found.

Make sure you're in the chroot when you run that command, it doesn't work in the CrOS shell.

*Hope this helps,*
-**DennisLfromGA**
