### ISSUE TITLE
cant type unix password at end

### ISSUE THREAD

**Issue by kermitissad** [dnschneid/crouton#4340]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by kermitissad** [comment]
at the end it says type unix password only problem is i cant type there

**Comment by DennisLfromGA** [comment]
@kermitissad,

Are you sure you can't type there?

When it prompts you for the password (twice) the characters you type will not be displayed but will be entered & registered, that's for security.

*Hope this helps,*
-**DennisLfromGA**

**Comment by kermitissad** [comment]
then how do i enter it

**Comment by kermitissad** [comment]
@DennisLfromGA

**Comment by DennisLfromGA** [comment]
@kermitissad,

Please re-read the segment of the sentence where I mention:
> *the characters you type will not be displayed but* ***will be entered & registered***

Just enter a valid password (twice) and let it finish.

*Hope this helps,*
-**DennisLfromGA**

**Comment by bvcbvc** [comment]
i recommend adding the password thing to pins for clarification, some users will thing its not working

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
