### ISSUE TITLE
How to Mount USB/Micro SD on crouton?

### ISSUE THREAD

**Issue by JVGA8837** [dnschneid/crouton#4341]
I only have 32GB on my HP Chromebook 14 (AMD). I want to download games to play on the go without lugging around my huge laptop, but all "tutorials" never work. Any help would be great!

**Comment by Jonyk56** [comment]
https://github.com/dnschneid/crouton/wiki/Access-external-drive-from-crouton

**Comment by JVGA8837** [comment]
I have done that but It always says (drivename): is a read only partition. Even though the write protect is off.

**Comment by Jonyk56** [comment]
send an image/screenshot of what it says
