### ISSUE TITLE
UPDATED GUIDE FOR FOCAL FOSSA

### ISSUE THREAD

**Issue by explodersname** [dnschneid/crouton#4342]
If you'd like to install Ubuntu 20.04 (Focal Fossa) on crouton just use this guide:
[https://github.com/dnschneid/crouton/issues/4265#issuecomment-689346174](url)
It is a complete guide that walks you through setting up audio and everything for Crouton with ubuntu 20.04. If you make an article or guide on how to do this, please credit me somehow. That would be greatly appreciated.

**Comment by DennisLfromGA** [comment]
[ I took the liberty of correcting the url in your link above, it was pointing to nowhere. ]

-**DennisLfromGA**

**Comment by explodersname** [comment]
Thanks Dennis, your awesome. Keep it up!

**Comment by game174master** [comment]
hastebin.com can't work
