### ISSUE TITLE
External displays

### ISSUE THREAD

**Issue by explodersname** [dnschneid/crouton#4343]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
crouton: version 1-20200724165050~master:08dac970
release: focal
architecture: amd64
xmethod: xorg
targets: gnome,audio,core,xfce,x11,gtk-extra
host: version 13099.110.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 4.19.122-09121-gd58e3f311e19 #1 SMP PREEMPT Wed Aug 19 00:32:43 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

Is it possible to use external displays with crouton? I'd like to have a monitor to extend my screen onto, and I'd like to use a Capture Card to capture my screen. I don't know if this is possible though, so if it is could someone post a tutorial on how to do it. I don't want to go out and buy something that won't work.

**Comment by MrHallway0** [comment]
Check this out: [Crouton dual screen setup](https://www.reddit.com/r/Crouton/comments/bsbvty/crouton_dual_screen_setup/).
