### ISSUE TITLE
My issues with Focal Fossa Gnome and attempts to fix

### ISSUE THREAD

**Issue by kathelynn** [dnschneid/crouton#4345]
```
name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
crouton: version 1-20200724165050~master:08dac970
release: focal
architecture: amd64
xmethod: xorg
targets: audio,chrome,cli-extra,core,extension,gnome-desktop,x11,xorg
host: version 13421.23.0 (Official Build) beta-channel nami 
kernel: Linux localhost 4.4.232-19101-g619abfde5ea9 #1 SMP PREEMPT Mon Sep 7 01:24:35 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/focal...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: audio,chrome,cli-extra,core,extension,gnome-desktop,x11,xorg
host: version 13421.23.0 (Official Build) beta-channel nami 
kernel: Linux localhost 4.4.232-19101-g619abfde5ea9 #1 SMP PREEMPT Mon Sep 7 01:24:35 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
I'm going to list the issues I've encountered when using gnome in focal fossa release.

Display output issues consistent on any release (Xenial or Focal) because of Chrome OS 79+:
- Gnome (or any desktop env, really) is slow without SNA. #3988 
- Screen tearing and visual artifacts with SNA, certain apps don't work. I haven't tried other AccelMethod but so far it's not that promising. #4190

Those issues were never fixed for me. At this point, crouton seems very unusable and I have no lead on whether this was ever resolved or not.

Focal Fossa specific issues (ones that I have encountered):
- Focal does not work out of the box. The screen displays nothing (and gets stuck, can't go back to ChromeOS unless I go to Developer Console) until I apply [this workaround](https://github.com/dnschneid/crouton/issues/4265#issuecomment-664673069).
- Unable to read/write/execute any files in the Downloads folder. #3261
I haven't attempted any fixes yet found on the issue that I mentioned and will try to do so later and comment to see if it works fine or not.
- Audio does not work and refuses to work. #4265 solutions are mostly to start pulseaudio via terminal but this does not work for gnome apparently. [ALSA to hardware](https://github.com/dnschneid/crouton/wiki/Access-audio-hardware-directly-(ALSA,-JACK)) fixes this with very limited functionality:
  - Alsamixer sliders not doing anything; with no way to change the volume whatsoever and having to rely on app volume controls.
  - Pulseaudio had to be uninstalled and alsa-base only reinstalled. I'm not sure why, will need to test this further.
  - Gnome not recognizing any output (and dummy sound output does not even exist either), which causes browsers to misbehave when playing anything with sound such as YouTube giving the message "if playback doesn't start shortly, try restarting your device". The browser issue workaround I found is by muting and unmuting the tab.
- Focal Fossa is stubborn to start at times. There are chances it would start fine, and chances where it would not start.

I haven't tested if those issues are also on Xfce or not, to confirm that this is not an individual issue. I will comment on my findings later.

[Here's the console when Fossa crashes](https://pastebin.com/pPPFPqch) and when [Fossa decides to work, with me going back and forth from Chrome OS to Fossa twice](https://pastebin.com/7jXrDQjk). (Also notable that DBus error is caused when switching to Fossa, but this isn't a Fossa specific issue)

**Comment by mrwhistles** [comment]
I noticed that running alsamixer was only possible as root so adding my user to the pulse-access group, restarting my session and running "pulseaudio --start" got sound working for me both audio and microphone.
