### ISSUE TITLE
sh: Can't open /home/chronos/user/Downloads/crouton 

### ISSUE THREAD

**Issue by Armaan35** [dnschneid/crouton#4346]
```
sh: Can't open /home/chronos/user/Downloads/crouton 

```

#### If known, describe the steps to reproduce the issue: In shell, still on chrome OS, write 
sudo sh ~/Downloads/crouton -t unity
as that seems to be the problem. I have installed crouton and tried many things though none work. Thanks in advance!

**Comment by DennisLfromGA** [comment]
Please read or re-read the **[README](https://github.com/dnschneid/crouton#usage)** that explains the new installation method.  

> sh: Can't open /home/chronos/user/Downloads/crouton   
 
Also, make sure your fresh downloaded copy of crouton is in `~/Downloads` and not another folder for those instructions to work. 

*Hope this helps,*
-**DennisLfromGA**
