### ISSUE TITLE
Can't move mouse after a fresh Bionic Xfce install.

### ISSUE THREAD

**Issue by Kasperfma** [dnschneid/crouton#4347]
**Please paste the output of the following command here: sudo edit-chroot -all**
chronos@localhost / $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xorg
targets: xfce,xorg,xiwi,cli-extra,extension,audio,keyboard,touch,chrome-beta,chromium
host: version 13310.59.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.185-15955-gadad491c59bc #1 SMP PREEMPT Mon Aug 24 02:15:31 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...

**My Issue**
Today i installed a fresh version of crouton, bionic beaver, and im using xfce. I installed with this command, and by using these targets: `sudo crouton -r bionic -t xorg,xiwi,cli-extra,audio,extension,keyboard,touch,chrome-beta,chromium,xfce`

I waited for it to finish installing, and i got an error with xorg. I quickly fixed this, by using [this](https://github.com/dnschneid/crouton/issues/3995#issuecomment-641595888) thread as help. 
After finishing the steps, i tried to start xfce from the shell by using: `sudo startxfce4` .
It loads fine, but i quickly notice that i can't move my mouse, unless i do some weird kind of doubleclick, that has to be timed perfectly. Not ideal at all.

How do i fix this? I've tried a lot, but nothing works.

Maybe it's possible to reproduce by doing what i've already listed.

**Comment by MrHallway0** [comment]
Sorry for the late reply but do you have a touch screen device? If not reinstall it (remove: `sudo edit-chroot -d bionic` install `sudo crouton -t xfce -r sid`). It appears to be a problem with `touch`...

**Comment by sudo-power** [comment]
You should try using a focal install. I had a lot of sucess with focal and xfce! only problem is that i have to use command line to install deb files. (command for that is sudo gdebi) To get focal and xfce, type in `sudo crouton -r focal -t xfce,core` . NOTE: you can add whatever targets you want to that command (not a diffrent desktop)

Hope this helps!

![image](https://user-images.githubusercontent.com/79377279/111197321-94de4b80-857b-11eb-9104-8cba64b89e13.png)

Lucas Gaming_YT
