### ISSUE TITLE
All internet connections limited to Chromebook

### ISSUE THREAD

**Issue by LucAngevare** [dnschneid/crouton#4348]
Heya, I am having an issue with Crouton (Ubuntu Xenial XFCE on Acer Chromebook, ChromeOS version 85.0.4183.108). The issue is that any connection to the internet that I try to create, is limited to my Chromebook. 

This means that every SSH server I open, I can only access it on my Chromebook. The same goes for any/all other servers: minecraft, MPD, webserver, etc. The servers have all worked before but for some reason it crashed and won't work anymore (getting no errors and doing `sudo service [service name] status` shows that it is alive). 

I can for some reason connect to these servers using the shell or chroot on my Chromebook but on no other devices connected to the same internet as the Chromebook. I have concluded that this is not the fault of my WiFi as on other connections it hasn't worked either. 

I have tried power washing it again but that did nothing. My computer science teacher is baffled as well.

```
Please paste the output of the following command: sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13310.76.0 (Official Build) stable-channel relm 
kernel: Linux localhost 4.19.129-09609-gdb2c7bb8c121 #1 SMP PREEMPT Wed Sep 9 00:33:10 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...```


cat /etc/lsb-release
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6819528
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={3FC66B4B-1B63-94FA-BD6F-DB856B496918}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={3FC66B4B-1B63-94FA-BD6F-DB856B496918}
CHROMEOS_RELEASE_BOARD=relm-signed-mp-v8keys
CHROMEOS_RELEASE_BRANCH_NUMBER=76
CHROMEOS_RELEASE_BUILDER_PATH=relm-release/R85-13310.76.0
CHROMEOS_RELEASE_BUILD_NUMBER=13310
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=85
CHROMEOS_RELEASE_DESCRIPTION=13310.76.0 (Official Build) stable-channel relm 
CHROMEOS_RELEASE_KEYSET=mp-v8
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13310.76.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13310.76.0

**Comment by DennisLfromGA** [comment]
Maybe you need to open up the firewall.
Take a look t this wiki for pointers -
- https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton

*Hope this helps,*
-**DennisLfromGA**

**Comment by LucAngevare** [comment]
That was indeed the issue, something I overlooked when setting up the chroot the second time. Many apologies for this!

**Comment by LucAngevare** [comment]
Just to get back to this issue, for anyone who's experiencing the same issue and this hasn't helped, for me the problem was that the network reset and my IP address changed. This lead me to reset my chromebook and have the issue with the firewall, so for anyone having the same problem, just type `hostname -I` and see if your IP is the same as it was before.
