### ISSUE TITLE
sudo startxfce4 leads to blackscreen

### ISSUE THREAD

**Issue by axelahlqvist** [dnschneid/crouton#4351]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13310.91.0 (Official Build) stable-channel sarien 
kernel: Linux localhost 4.19.129-09609-gdb2c7bb8c121 #1 SMP PREEMPT Tue Sep 22 20:15:06 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I want to run linux on my chromebook and therefor installed crouton. I installed according to the following instruction https://github.com/dnschneid/crouton/blob/master/README.md (The easy way) but after running "sudo startxfce4" my screen turns black (with a mouse pointer). I can't get back to my chrome session since I have no "forward" button on my keyboard. I therefor reboot manually with the power button. I tried the solution given in the following thread https://github.com/dnschneid/crouton/issues/3016, specifically editing my xorg-intel-sna.conf and moving it to usr/share/X11/xorg.conf.d. Instead of getting stuck at the black screen I got the following error message:  

Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-115-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.19.129-09609-gdb2c7bb8c121 #1 SMP PREEMPT Tue Sep 22 20:15:06 PDT 2020 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4751360 verity payload=PARTUUID=843448cb-a69e-4103-9f7e-31d081319303/PARTNROFF=1 hashtree=PARTUUID=843448cb-a69e-4103-9f7e-31d081319303/PARTNROFF=1 hashstart=4751360 alg=sha256 root_hexdigest=29e54ea953a483d2c0681081f3e0b31196d3aa2efb654bb2392cb6370aec6aea salt=4f0d775344494cb5049efc92bbcf886bd335e8222d86ee958edafaf5771507e0" noinitrd vt.global_cursor_default=0 kern_guid=843448cb-a69e-4103-9f7e-31d081319303 add_efi_memmap boot=local noresume noswap i915.modeset=1 nmi_watchdog=panic,lapic ramoops.ecc=1 gsmi.s0ix_logging_enable=1 intel_pmc_core.warn_on_s0ix_failures=1 usbcore.quirks=2cb7:0007:k modprobe.blacklist=ucsi_acpi  
Build Date: 04 September 2020  03:38:30PM
xorg-server 2:1.18.4-0ubuntu0.10 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Sep 28 09:04:00 2020
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
(EE) 
Fatal server error:
(EE) failed to create screen resources(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### If known, describe the steps to reproduce the issue:
sudo startxfce4

I am using a dell latitude 5400

**Comment by MrHallway0** [comment]
I am experiencing something similar with the Cinnamon desktop (custom code).
I think running `sudo enter-chroot` followed by `sudo apt install gdm` will install a display manager, can you run that?
*if it doesn't help remove `gdm` so you have an almost blank XFCE state*

**Comment by axelahlqvist** [comment]
MrHallway0 your solution worked at first but the same problem returned after logging out from my crouton session. I installed gdm pressed ctrl-d to exit chroot and then ran "sudo enter-chroot startxfce4". I entered the crouton interface and could see the desktop. However, after I logged out of the session, and tried to enter with "sudo enter-chroot startxfce4" I got a black screen (with a mouse pointer) again. I have tried to remove gdm with apt-get purge. Still a blackscreen when I run startxfce4. I have tried to install gdm again after purging it. Sill a blackscreen. Something interesting is that if I wait a few minutes on the blackscreen, the screen goes to sleep and when I move the mouse I can see the crouton Desktop but not interact with it.

**Comment by MrHallway0** [comment]
Can you try `sudo startxfce4` without the `enter-chroot` before it?

**Comment by axelahlqvist** [comment]
Same results unfortunately.

**Comment by marauder316** [comment]
This may or may not work, but if you don't mind using Crouton in a window, update your chroot with `sudo crouton -n xenial -u -t xiwi` and then try `sudo startxfce4` again.

**Comment by MrHallway0** [comment]
@marauder316 
It looks to be a problem with the display manager.

@axelahlqvist 
Try reinstalling XFCE, if you don't have any important information. (remove XFCE: `sudo edit-chroot -d xenial`. Install `sudo crouton -t xfce -r sid`).

**Comment by rogervdf** [comment]
Am experiencing the same issue as OP.

@marauder316 's suggestion 2 posts above leads to a GUI, but with a non-functioning black screen in the middle that I guess is supposed to be a terminal.

@MrHallway0 's suggestion in the post above leads to a crash, with ´dbus-launch not found'

**Comment by axelahlqvist** [comment]
I also get the 'dbus-launch not found' with @MrHallway0's suggestion

**Comment by MrHallway0** [comment]
Witch one? Removing and reinstalling or `gdm`?

**Comment by axelahlqvist** [comment]
Removing and reinstalling.

**Comment by pjpreilly** [comment]
Same Black Screen on cloudread v86 and v87..... Any more suggestions?

chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 87.1.5 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 5.4.66+ #2 SMP Thu Nov 12 02:35:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

**Comment by MrHallway0** [comment]
Have you tried a different release (`-r <release name>` at install) other then `xenial`?

**Comment by pjpreilly** [comment]
> Have you tried a different release (`-r <release name>` at install) other then `xenial`?

I have not, it WAS working in previous cloudready versions but after upgrading the startxfce4 command leads to a black screen, I also had to comment these lines in /usr/local/bin/enter-chroot.....

Modify "enter-chroot" file with following command: sudo vi /usr/local/bin/enter-chroot
 
Search for the following statements:
# Allow X server running as normal user to set/drop DRM master
drm_relax_file="/sys/kernel/debug/dri/drm_master_relax"
if [ -f "$drm_relax_file" ]; then
    echo 'Y' > "$drm_relax_file"
fi
 
and comment them out:
# Allow X server running as normal user to set/drop DRM master
#drm_relax_file="/sys/kernel/debug/dri/drm_master_relax"
#if [ -f "$drm_relax_file" ]; then
#    echo 'Y' > "$drm_relax_file"
#fi

**Comment by pjpreilly** [comment]
Can/should I install a different version without deleting my xenial installation? Which one do you suggest?

**Comment by MrHallway0** [comment]
You can, as long as it has a different name. That will not matter because, by default, it's the release name. I suggest running this: `sudo crouton -t xfce -r sid`.

**Comment by pjpreilly** [comment]
Installed sid, I had to comment the "Allow X server" lines to continue the install. The results are the same, Black screen when startxfce4 is executed.

**Comment by marauder316** [comment]
Is this problem only with Ubuntu? Does XFCE work on Kali or Debian?

**Comment by pjpreilly** [comment]
> Is this problem only with Ubuntu? Does XFCE work on Kali or Debian?

sid is Debian

**Comment by pjpreilly** [comment]
Now that I both xenial & sid installed, how do I choose which one I want to launch? Currently startxfce4 starts sid by default so how do I attempt to start xenial?

**Comment by MrHallway0** [comment]
Try removing `sid`.

**Comment by pjpreilly** [comment]
...Can't have them both?

**Comment by pjpreilly** [comment]
Got it back to xenial ... not working.

**Comment by phummel** [comment]
I just did a fresh install of bullseye. I got the dbus-launch not found error using xiwi and xorg targets, but like others could enter-chroot to the command line without issue.

From enter-chroot I installed dbus-x11 (sudo apt-get install dbus-x11)
Now, I can run in xiwi and xorg without issue. Not sure why it wasn't installed initially?

**Comment by pjpreilly** [comment]
Not for me.... Still get black screen.....

chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/xenial...
(xenial)dad@localhost:~$ sudo apt-get install dbus-x11
[sudo] password for dad: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dbus-x11 is already the newest version (1.10.6-1ubuntu3.6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(xenial)dad@localhost:~$

**Comment by phummel** [comment]
> Not for me.... Still get black screen.....
> 

It looks like you are not getting the "dbus-launch not found" error that I was getting.

I don't remember my exact install, but I think it was:
sudo crouton -r bullseye -t xiwi,xorg,x11,gtk-extras,xfce,extension

Upon launching sudo startxfce4 I would get a screen with a popup that said dbus-launch not found. Clicking ok or cancel would drop me back into the shell.

**Comment by sat066** [comment]
same problem, except my release is kali-rolling and i get a window saying
"Unable to contact settings server
Failed to execute child process "dbus-launch" (No such file or directory)"
The xfce4 session then closes and the console returns with:
`dbus-launch not found, the desktop will not work properly!`

**Comment by sat066** [comment]
> same problem, except my release is kali-rolling and i get a window saying
> "Unable to contact settings server
> Failed to execute child process "dbus-launch" (No such file or directory)"
> The xfce4 session then closes and the console returns with:
> `dbus-launch not found, the desktop will not work properly!`

Fixed this problem by installing dbus-x11 via apt install:
`sudo enter-chroot`
`apt install dbus-x11`
`exit`
`sudo startxfce4`

**Comment by pjpreilly** [comment]
Apparently this cloudready update also fixed this crouton problem, enters crouton correctly with v87.3.28:

Fix for TTY shell: Switching to TTY via CTRL+ALT+F2 was not working. The issue has been resolved.
