### ISSUE TITLE
How do I boot chroot from usb?

### ISSUE THREAD

**Issue by jimmybungalo** [dnschneid/crouton#4352]
```
Please paste the output of the following command here: sudo edit-chroot -all (sudo edit-chroot -c /media/removable/USB\ Drive -all)
name: buster
encrypted: no
Entering /media/removable/USB Drive/chroots/buster...
crouton: version 1-20200724165050~master:08dac970
release: buster
architecture: amd64
xmethod: xorg
targets: lxde,x11,keyboard,core,cli-extra,chrome,audio
host: version 13310.76.0 (Official Build) stable-channel terra 
kernel: Linux localhost 4.19.129-09609-gdb2c7bb8c121 #1 SMP PREEMPT Wed Sep 9 00:25:08 PDT 2020 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/chroots/buster...
```

#### Please describe your issue:
I cannot open my chroot (Debian Buster LXDE) using startlxde, I installed it onto a USB Drive, and the startlxde file is in a folder called "bin" on the USB Drive, and there is also a "chroots" folder. How do I execute startlxde, and how do I make sure it executes buster from my USB Drive? 

#### If known, describe the steps to reproduce the issue:
No bugs, just inability to do what I intended.

**Comment by DennisLfromGA** [comment]
You can first `cd` into your external media device to the root directory in which you installed the bin and chroot subdirectories and data. Then launch your lxde desktop with: `sudo sh ./bin/startlxde`

*Hope this helps,*
-**DennisLfromGA**

**Comment by jimmybungalo** [comment]
It returned with ```sh: 0: Refusing to exec ./startlxde from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md```, does this mean it is non-executable?

**Comment by jimmybungalo** [comment]
> You can first `cd` into your external media device to the root directory in which you installed the bin and chroot subdirectories and data. Then launch your lxde desktop with: `sudo sh ./bin/startlxde`
> 
> _Hope this helps,_
> -**DennisLfromGA**

It returned with ```sh: 0: Refusing to exec ./startlxde from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md```, does this mean it is non-executable?

**Comment by DennisLfromGA** [comment]
Check where and how it's mounted with: 
- `mount | grep /media/removable`   

Take note of the name of the mount point.
Then if you see a 'noexec' in the mount options remount it with:  
- `sudo mount -o remount,exec /media/removable/USB \Drive` 

If the mount point is named something other than 'USB Drive' then use that name.

*Hope this helps,*
-**DennisLfromGA**

**Comment by jimmybungalo** [comment]
> Check where and how it's mounted with:
> 
> * `mount | grep /media/removable`
> 
> Take note of the name of the mount point.
> Then if you see a 'noexec' in the mount options remount it with:
> 
> * `sudo mount -o remount,exec /media/removable/USB \Drive`
> 
> If the mount point is named something other than 'USB Drive' then use that name.
> 
> _Hope this helps,_
> -**DennisLfromGA**

It didn't say anything about noexec, but your solution did just the trick! Now I just need to export the chroot to a tarball and I'll be set with a Debian VM. Thanks a lot.
