### ISSUE TITLE
.deb's won't install on 18.04 chroot

### ISSUE THREAD

**Issue by marauder316** [dnschneid/crouton#4353]
#### Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: arm64
xmethod: xiwi
targets: gnome-desktop,x11,core,touch,audio,keyboard,cli-extra,extension,xiwi,gtk-extra
host: version 13499.0.0 (Official Build) canary-channel kukui 
kernel: Linux localhost 4.19.147-10385-g11e2f8e1c066 #1 SMP PREEMPT Tue Sep 29 04:00:35 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.

name: eoan
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/eoan...
crouton: version 1-20200724165050~master:08dac970
release: eoan
architecture: arm64
xmethod: xiwi
targets: lxde,x11,core,touch,audio,keyboard,cli-extra,extension,xiwi,xorg,gtk-extra
host: version 13499.0.0 (Official Build) canary-channel kukui 
kernel: Linux localhost 4.19.147-10385-g11e2f8e1c066 #1 SMP PREEMPT Tue Sep 29 04:00:35 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/eoan...
```
#### Please describe your issue:
.deb packages won't install on my 18.04 chroot.

#### If known, describe the steps to reproduce the issue:
Ctrl+Alt+T to bring up the terminal.
```
(bionic)o_x@localhost:~$ sudo gdebi ~/Minecraft.deb
Reading package lists... Done
Building dependency tree
Reading start information... Done
Failed to open the software package
The package might be corrupted or you are not allowed to open this file. Check the permissions of the file.
(bionic)o_x@localhost:~$
```

Discord was an amd64 file, and I'm using the Lenovo Duet, so I had to add the architecture.
Any solutions? I'm not that good with Linux yet, but I'm willing to learn what I need to fix this.

**Comment by DennisLfromGA** [comment]
Have you tried anything other than '`gdebi`' ?

Maybe try: `cd; sudo apt install ./Minecraft.deb` -or- `sudo dpkg -i ~/Minecraft.deb`

If neither of those work and give you the same error then perhaps download the .deb file again and use a checksum if they offer one.

*Hope this helps,*
-**DennisLfromGA**

**Comment by marauder316** [comment]
I Will try, thanks!

Sorry for the late reply.

**Comment by marauder316** [comment]
It didn't work; here's the output:
`(bionic)o_x@localhost:~$ cd; sudo apt install ./Minecraft.deb
[sudo] password for o_x: 
Segmentation fault
(bionic)o_x@localhost:~$ sudo dpkg -i ~/Minecraft.deb
dpkg-deb: error: '/home/o_x/Minecraft.deb' is not a Debian format archive
dpkg: error processing archive /home/o_x/Minecraft.deb (--install):
dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /home/o_x/Minecraft.deb
(bionic)o_x@localhost:~$ `

I then did a checksum:
`(bionic)o_x@localhost:~$ sudo cksum Minecraft.deb
2498455001 96380 Minecraft.deb
(bionic)o_x@localhost:~$ 
`
I'm not the most experienced Linux user, so I don't really understand the `cksum` command.

**Comment by DennisLfromGA** [comment]
@marauder316,

Those errors seem to point to a corrupt or incomplete `Minecraft.deb` file.
Perhaps download a fresh copy or, maybe even better, try to find another source for it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by MrHallway0** [comment]
@marauder316 
Did a fresh copy work? If it didn't work then try something other then `Minecraft.deb`... Alternatively try another source as @DennisLfromGA  said (like [flatpak](https://www.flatpak.org/) or [snap](https://snapcraft.io/)).

Also I don't believe `arm64` devices running Linux can run Minecraft... although that being said if you are very advanced you might be able to build OpenJDK for ARM, Microsoft did it for the ARM version of Windows, check out [this](https://devblogs.microsoft.com/java/announcing-openjdk-windows-arm/) post.

**Comment by marauder316** [comment]
@MrHallway0 It didn't. Minecraft Java Edition isn't supported on arm64 devices.
I'm not smart enough yet to make a build. Maybe someday down the line :D

I'll close the issue. Thanks for your advice, guys.
