### ISSUE TITLE
LXDE Will not open display

### ISSUE THREAD

**Issue by Jonyk56** [dnschneid/crouton#4354]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: XA
encrypted: no
Entering /media/removable/USB Drive/chroots/XA...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,lxde,xiwi,xfce,unity,audio,gnome,kde
host: version 13421.39.0 (Official Build) beta-channel celes 
kernel: Linux localhost 4.19.139-09991-g2e051c3237b1 #1 SMP PREEMPT Mon Sep 21 20:55:40 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/chroots/XA...
name: ZAP
encrypted: no

#### Please describe your issue:
Lxde is not opening The display as it should

#### If known, describe the steps to reproduce the issue:
```
chronos@localhost /media/removable/USB Drive/bin $ sudo sh enter-chroot startlxde 
Entering /media/removable/USB Drive/chroots/XA...
Unknown username "geoclue" in message bus configuration file
Agent pid 19898
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE

(lxsession:19896): Gtk-WARNING **: cannot open display: 
Unmounting /media/removable/USB Drive/chroots/XA...
Sending SIGTERM to processes under /media/removable/USB Drive/chroots/XA...
```

**Comment by DennisLfromGA** [comment]
@Jonyk56,

According to [a post on Discord r/chromeos](https://discord.com/channels/253908290105376768/356483724075859969/761037965312000012) I believe you've discovered your solution now by installing/re-installing the lxde target.
If not, please let us know and we'll try to do further troubleshooting.

BTW, I like to use the lxde-desktop target for the full LUbuntu Desktop experience, it does have a bigger footprint tho.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Jonyk56** [comment]
Well, I did try it, and it is still broken...

**Comment by DennisLfromGA** [comment]
@Jonyk56 

Something must've happened during the install if the gtk-extra target was not pulled in since it's required when installing the lxde target:

```
lxde
        Installs the LXDE desktop environment. (Approx. 200MB)
        Requires: gtk-extra
```

If you don't have too much time & effort invested in it it might be best to start anew.

An alternate approach might be to install another chroot with just lxde and see if it works, maybe something like:
- `sudo crouton -r xenial -n XA1 -t xorg,xiwi,cli-extra,keyboard,touch,lxde`

*Hope this helps,*
-**DennisLfromGA**

**Comment by Jonyk56** [comment]
Ok, I found out that just running ``sudo sh startlxde`` does work, but when paired with enter-chroot, all heck breaks loose...

**Comment by Jonyk56** [comment]
![image](https://user-images.githubusercontent.com/44901605/94818671-5fc6ae00-03cc-11eb-94ba-6c9f348a9f52.png)

**Comment by Jonyk56** [comment]
Also, i'll be seein if it will work in a new environment once i am done with class

**Comment by DennisLfromGA** [comment]
@Jonyk56,

Makes sense since running the `startlxde` script in CrOS calls `enter-chroot` with other needed options so there's really no need to use it -
```
chronos@localhost ~ $ cat /usr/local/bin/startlxde
#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

APPLICATION="${0##*/}"

USAGE="$APPLICATION [options]

Wraps enter-chroot to start an LXDE session.
By default, it will log into the primary user on the first chroot found.

Options are directly passed to enter-chroot; run enter-chroot to list them."

exec sh -e "`dirname "\`readlink -f -- "$0"\`"`/enter-chroot" -t lxde "$@" "" \
    exec xinit /usr/bin/startlxde
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by Jonyk56** [comment]
*Well that makes sense* but, anyways, how to fix?

**Comment by DennisLfromGA** [comment]
@Jonyk56,

We seem to be going back & forth.

Your Discord comment seemed to make it sound like it was working, then you said it wasn't.

> Ok, I found out that just running sudo sh startlxde does work, but when paired with enter-chroot, all heck breaks loose...

The above comment also led me to believe it was working, then you said it isn't.

So, I'm a bit confused, maybe try my suggestion to install a fresh new chroot as I described above and see if & where it goes awry.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Jonyk56** [comment]
![image](https://user-images.githubusercontent.com/44901605/94821406-8cc89000-03cf-11eb-9f00-569be9e7ba0d.png)

**Comment by Jonyk56** [comment]
*i got it working*

**Comment by Jonyk56** [comment]
![Uploading image.png…]()

**Comment by Jonyk56** [comment]
![image](https://user-images.githubusercontent.com/44901605/94821690-ddd88400-03cf-11eb-9bbc-97ed4d09fb35.png)

**Comment by Jonyk56** [comment]
Yes, so, First off, You needa just enter chroot as normal, and once you do, run the following:
```sh
exec xinit /usr/bin/startlxde
```

**Comment by DennisLfromGA** [comment]
@Jonyk56,

Okay, thanx. 

> Ok, I found out that just running `sudo sh startlxde` **does work**, but when paired with enter-chroot, all heck breaks loose...

Not sure why `sudo sh startlxde` from CrOS doesn't work now when it did earlier but I guess stranger things have happened.

-**DennisLfromGA**

**Comment by Jonyk56** [comment]
*Indeed stranger things have happened*
