### ISSUE TITLE
Unable to install from any targets

### ISSUE THREAD

**Issue by tekstrand** [dnschneid/crouton#4355]
```
name: new
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/new...
chroot: failed to run command '/usr/local/bin/croutonversion': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/new...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
chroot: failed to run command '/usr/local/bin/croutonversion': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
1. After the above, run `sudo delete-chroot` for both
2. Run `sudo edit-chroot -all` results in `No chroots found in /mnt/stateful_partition/crouton/chroots`
3. Run `sudo crouton -t xfce`
```
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Chosen extractor for .deb packages: ar
Moving bootstrap files into the chroot...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/usr/src/crouton': No such file or directory
```
4. sudo crouton -u 
```
/usr/local/chroots/xenial already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/usr/src/crouton': No such file or directory
```
5. `sudo delete-chroot xenial`
```
Finished deleting /mnt/stateful_partition/crouton/chroots/xenial
```
6. `sudo edit-chroot -all`
```
No chroots found in /mnt/stateful_partition/crouton/chroots
```
7. `sudo crouton -u`
```
No chroots found in /mnt/stateful_partition/crouton/chroots
/usr/local/chroots/xenial does not exist; cannot update.
Valid chroots:
```

Not sure what is going on here. Even after deleting all chroots it still seems to think that `xenial` exists somewhere. Not sure where to find a file where this would be defined in.

#### If known, describe the steps to reproduce the issue:
This is a Chromebook that had xfce installed on it before. It hasn't been used ~2 years. I downloaded crouton again and ran the new command to add crouton to `bin` since Downloads no longer allows executables.

**Comment by DennisLfromGA** [comment]
@tekstrand,

The message:

> No chroots found in /mnt/stateful_partition/crouton/chroots
/usr/local/chroots/xenial does not exist; cannot update.
Valid chroots:

just means that the default chroot, xenial, is not installed nor are any other chroots.

I'm not sure why you are getting the error:

> cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/usr/src/crouton': No such file or directory

on a new installation.

it might be best to run: `sudo delete-chroot *`
Then reboot and try again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by tekstrand** [comment]
`sudo delete-chroot *` results in 
```
/mnt/stateful_partition/crouton/chroots/bin not found
```

I have searched around but found no directly related results. Any other ideas?

**Comment by DennisLfromGA** [comment]
@tekstrand,

That message may just indicate that there are no chroots installed any longer.

If `/usr/local/chroots/` has no chroots under it then your good to go.
If you find chroots in there then try to remove them manually with:
- `sudo rm -rf /usr/local/chroots/*`

> Any other ideas?

Yep, reboot and try again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by tekstrand** [comment]
@DennisLfromGA,

Same error after attempting the recommendations.
```
cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/usr/src/crouton': No such file or directory
```

Any log files I could look into?

**Comment by DennisLfromGA** [comment]
@tekstrand,

Sorry, I'm stumped.

What's listed in here when you enter:
- `sudo ls -l /mnt/stateful_partition/crouton/chroots/xenial/usr/src/`

> Any log files I could look into?

You might be able to get the complete output in a file with:
- `sudo sh -x /usr/local/bin/crouton -t xfce 2>&1 | tee ~/crouton.out`

Then examine `~/crouton.out` when it finishes or errors & exits.

*Hope this helps,*
-**DennisLfromGA**

**Comment by MrHallway0** [comment]
If you don't have any important **local** information. Then try a powerwash...

**Comment by tekstrand** [comment]
@MrHallway0 what is a "powerwash"? I've never heard that term.

**Comment by MrHallway0** [comment]
Where you reset the device to the default. Also known as factory reset. Here are instructions: [support.google.com/...](https://support.google.com/chromebook/answer/183084?hl=en).
