### ISSUE TITLE
I'm not exactly sure where to put this, but I need some help resuming the installation of a timed-out chroot install.

### ISSUE THREAD

**Issue by itstoast27** [dnschneid/crouton#4356]
```
No chroots found in /mnt/stateful_partition/crouton/chroots
```

#### Describe your issue here:
My internet connection is extremely spotty, and tends to cut out while I am in the middle of making a chroot. I'm not sure exactly how to resume it, as I have tried `sudo crouton -u -n bullseye` to try and restart it, but both times I tried this it left me with an unfinished chroot, and told me to "maybe run apt-get update or --fix-missing?". I don't know if I'm stupid but I have no clue where and how to use either of these. I've been deleting and attempting to recreate the chroot multiple times at this point, and I can see that this is getting me nowhere. If it helps, I had downloaded a .tar.gz for bullseye, and was applying the targets shown in [this pastebin](https://pastebin.com/WhhxvErQ). (Yes; I know my targets are overkill.) It's probably not helping that I am using the Samsung Chromebook 3 / CELES, but I've gotten crouton to work fine in the past on this very chromebook, so I don't see how it would affect something that is clearly not the one breaking chroots.
(To emphasize my suffering with my router, github had loaded to the point where I could write this issue, but never reconnected within the ~~twenty~~ ~~thirty~~ ~~fifty~~ ~~sixty~~ ninety minutes spent constantly attempting to reconnect, allowing me to write this bit down here as I wait in hope that my internet will come back.)

#### If known, describe the steps to reproduce the issue:
Just turn off your internet while attempting to make a chroot, and voila(!): You're also stuck going insane with an inane router.

**Comment by itstoast27** [comment]
decided to run it again, and preformed this after the fact
```chronos@localhost / $ sudo edit-chroot -all
name: painv2
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/painv2...
crouton: version 1-20200724165050~master:08dac970
release: bullseye
architecture: amd64
targets: xorg,xiwi,audio,extension,xfce,keyboard,chrome,core,cli-extra,x11
host: version 13502.0.0 (Official Build) dev-channel celes 
kernel: Linux localhost 4.19.148-10389-ged66ada73bf8 #1 SMP PREEMPT Wed Sep 30 17:37:18 PDT 2020 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/painv2...```

**Comment by DennisLfromGA** [comment]
@itstoast27,

You're decision and approach to first download the bootstrap file is a good one considering the connectivity issues you have.
Also, the targets you have chosen are okay, most of them are 'required' and get pulled in anyway.

The messages displayed about "maybe run apt-get update or --fix-missing?" pertain to commands you would run in the chroot, not from outside the chroot in CrOS. Try doing the following and see if it gets you any further:
```
sudo enter-chroot -n painv2
sudo apt update
sudo apt install -f
sudo apt upgrade
```

Hopefully, it'll find some missing dependencies or broken packages and fix them.

*Hope this helps,*
-**DennisLfromGA**

**Comment by itstoast27** [comment]
Thank you! Even though I had eventually gotten my internet functioning long enough to install it in one go, I will keep this in mind if I ever have to go through the installation process again.

___________
with gratitude,
sage
