### ISSUE TITLE
Ubuntu very slow on asus chromebook c436f

### ISSUE THREAD

**Issue by stajne** [dnschneid/crouton#4357]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13310.91.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.129-09609-gdb2c7bb8c121 #1 SMP PREEMPT Tue Sep 22 20:23:57 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

Linux is very slow, every click needs a couple of seconds to react. Does someone know the reason

**Comment by taolai** [comment]
I have the same setup and I noticed that the lagging is somekind of refresh problem that has something to do with mouse movement.
