### ISSUE TITLE
sudo: startxfce4: command not found from SD CARD HP 11A G6

### ISSUE THREAD

**Issue by kry008** [dnschneid/crouton#4358]
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: gnome
host: version 13310.93.0 (Official Build) stable-channel grunt 
kernel: Linux localhost 4.14.185-15957-g2b583f6bdd4f #1 SMP PREEMPT Thu Sep 24 20:50:09 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

``````

#### Please describe your issue:

I installed according to the instructions on the xfce4 wiki, I am trying to enable it also according to the wiki. And there is a mistake. Could someone explain to me why this error is displayed? Can it affect the fact that I already have the system installed on the system disk using this tool, if so, how to make it only on the SD card. There were no errors while installing. Sorry for my english, below is my language text.

Zainstalowałem według instrukcji na wiki xfce4, próbuję włączyć go też według wiki. I jest błąd. Mógłby ktoś mi wytłumaczyć dlaczego taki błąd się wyświetla? Czy może mieć wpływ na to, że na dysku systemowym już mam zainstalowany system za pomocą tego narzędzia, jeżeli tak, to jak zrobić aby był tylko na karcie SD. Przepraszam za mój angielski, poniżej jest tekst w moim języku.

#### If known, describe the steps to reproduce the issue:
![Screenshot 2020-10-07 at 20 10 35](https://user-images.githubusercontent.com/25504684/95371339-5b255c80-08da-11eb-92ef-49f01b883a8d.png)
![Screenshot 2020-10-07 at 20 10 05](https://user-images.githubusercontent.com/25504684/95371434-7db77580-08da-11eb-9561-3499e34b3008.png)

I also tried without sudo

**Comment by kry008** [comment]
I tried also without sudo.

**Comment by DennisLfromGA** [comment]
@kry008,

Now that you have installed your chroot on external media the command `sudo startxfce4` will not work since it is looking for the chroot on internal storage by default.

Here is the usage displayed for `startxfce4`:
```
chronos@localhost ~ $ startxfce4 -h
Illegal option -h
enter-chroot [options] [command [args...]]

Enters an installed Debian-based chroot for running alongside Chromium OS.

By default, it will log into the primary user on the first chroot found.
You can specify a command and parameters to run instead of an interactive shell.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /usr/local/chroots
    -l          Make the command part of a login. Parameters are passed directly
                to the chroot command, and a call to su is appended.
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -X XMETHOD  Override the auto-detected XMETHOD for this session.
    -x          Does not log in, but directly executes the command instead.
                Note that the environment will be empty (sans TERM).
                Specify -x a second time to run the /prepare.sh script.
```
Above you'll find a '`-p`' option to let the launcher know where your chroot is.
So, try the below commands to see if it launches, note that recent changes mount external media with the 'noexec' option so it's more difficult to launch them now but also more secure:
- `sudo startxfce4 -n xenial -c "/media/removable/SD Card/chroots"` -or-
- `sudo sh "/media/removable/SD Card/bin/startxfce4 -n xenial"` -or-
- `cd "/media/removable/SD Card"; sudo sh ./bin/startxfce4 -n xenial`

Hopefully, one or more of the above will work.

*Hope this helps,*
-**DennisLfromGA**

**Comment by kry008** [comment]
It doesn't work, shows that can not find file or can not run nonexec

**Comment by kry008** [comment]
`chronos@localhost /media/removable/SD Card $ sudo sh ./bin/starte17
sh: 0: Refusing to exec ./bin/starte17 from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
chronos@localhost /media/removable/SD Card $ sudo su
localhost /media/removable/SD Card # ls -l
total 24
drwxr-xr-x. 2 root root  4096 Oct 10 08:24 bin
drwxr-xr-x. 3 root root  4096 Oct 10 08:21 chroots
drwx------. 2 root root 16384 Oct 10 08:03 lost+found
localhost /media/removable/SD Card # cd bin
localhost /media/removable/SD Card/bin # ls -l
total 124
-rwxr-xr-x. 1 root root  7310 Oct 10 08:24 crash_reporter_wrapper
lrwxrwxrwx. 1 root root    11 Oct 10 08:24 delete-chroot -> edit-chroot
-rwxr-xr-x. 1 root root 32105 Oct 10 08:24 edit-chroot
-rwxr-xr-x. 1 root root 34899 Oct 10 08:24 enter-chroot
-rwxr-xr-x. 1 root root 21225 Oct 10 08:24 mount-chroot
-rwxr-xr-x. 1 root root   561 Oct 10 08:24 starte17
-rwxr-xr-x. 1 root root 18675 Oct 10 08:24 unmount-chroot
localhost /media/removable/SD Card/bin # `
What I must do to run from sd card? I format card and install again e17.

**Comment by DennisLfromGA** [comment]
@kry008,

You could remount the external media with the 'exec' option similar to below:
- `sudo mount -i -o remount,exec "/media/removable/SD Card"

*Hope this helps,*
-**DennisLfromGA**

**Comment by kry008** [comment]
ok, now is working.
working with this method
sudo startxfce4 -n xenial -c "/media/removable/SD Card/chroots"
