### ISSUE TITLE
Volume Control always show "Establishing Connection to PulseAudio" and No sound coming

### ISSUE THREAD

**Issue by imdigitalashish** [dnschneid/crouton#4359]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20200724165050~master:08dac970
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13577.0.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 4.19.153-10474-g58b82cb3fb6c #1 SMP PREEMPT Wed Nov 4 01:10:37 PST 2020 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling as another instance is using it.
```

#### Please describe your issue:

In my crouton linux which is Acer Chromebook R11 no Sound is coming and when I open pulseaudio it is always saying Establishing Connection to PulseAudio and no sound is coming from my linux please tell how can I fix that.

Thank You

**Comment by marauder316** [comment]
Please actually paste the output of the command.
If you haven't already, add the target `audio` to your chroot.

**Comment by imdigitalashish** [comment]
![image](https://user-images.githubusercontent.com/61198989/99044821-6133ea80-25b6-11eb-8873-20f290b65d35.png)
When I open Volume Control it always show this here

**Comment by imdigitalashish** [comment]
and I write pulseaudio -D

It shows dummy audio and dummy mic input and no sound is coming 

![image](https://user-images.githubusercontent.com/61198989/99044929-904a5c00-25b6-11eb-93c4-5d1ca7123eda.png)

**Comment by imdigitalashish** [comment]
this is my sudo edit-chroot

```name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20200724165050~master:08dac970
release: kali-rolling
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13577.0.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 4.19.153-10474-g58b82cb3fb6c #1 SMP PREEMPT Wed Nov 4 01:10:37 PST 2020 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling as another instance is using it.```

**Comment by marauder316** [comment]
If you have any backups where this problem _didn't_ exist, try restoring it.
Try updating your chroot with `sudo crouton -n kali-rolling -u`
I know mic input works with Crostini, so try there.
(I can't help you too much, sorry :(  )

**Comment by imdigitalashish** [comment]
I have first time installed this... and I have ran into this issue where mic is not support

**Comment by marauder316** [comment]
On Crostini (Linux Beta) or Crouton?
There's an option to enable mic input on Crostini, just find it and flip the switch.

**Comment by IntinteDAO** [comment]
I probably have this issue, I partially solved it. The problem was with privileges to soundcard device (/dev). The user can't open it, but root can. 

Simple "chmod -R 777 /dev" fixes that, but it's not a solution. I think there might be problem with udev or something like that.
