### ISSUE TITLE
Unable to move or install chroot on SD Card

### ISSUE THREAD

**Issue by duck955** [dnschneid/crouton#4360]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
chronos@localhost ~/Downloads $ sudo edit-chroot -all
No chroots found in /mnt/stateful_partition/crouton/chroots
```
#### Please describe your issue:
I moved my chroot from my internal drive to my SD Card and the task completed successfully.  When I run sudo startxfce4, I receive the same error as above "No chroots...."

When I attempt to update the chroot, I receive the error "Too many symbolic links".  See output below

Also, when I follow this guide, [How-To-Install-To-External-Drive](https://github.com/dnschneid/crouton/wiki/How-To-Install-To-External-Drive), I receive the same error during a fresh installation for "Too many symbolic links"
```
sudo crouton -n kali-rolling -p /media/removable/SD\ Card -u
/media/removable/SD Card/chroots/kali-rolling already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
cp: failed to access '/var/run/crouton/media/removable/SD Card/chroots/kali-rolling/usr/local/bin/startxfce4': Too many levels of symbolic links
```

**Comment by DennisLfromGA** [comment]
@duck955,

> I moved my chroot from my internal drive to my SD Card and the task completed successfully.

If you are just having trouble launching your desktop from external media them take a look at this comment, it may help with your issue:
- sudo: startxfce4: command not found from SD CARD HP 11A G6 · Issue #4358 · dnschneid/crouton

*Hope this helps,*
-**DennisLfromGA**

**Comment by duck955** [comment]
@DennisLfromGA  thank you for the reply

I ran the start command based on the issue you linked and with the help menu for startxfce4.  Below is my output.

```
chronos@localhost /media/removable/SD Card $ sudo startxfce4 -c /media/removable/SD\ Card/chroots
Entering /media/removable/SD Card/chroots/kali-rolling...
chroot: failed to run command 'su': Too many levels of symbolic `links`
WARNING: starting chroot system dbus daemon failed with code 126
chroot: failed to run command 'su': Too many levels of symbolic links
Unmounting /media/removable/SD Card/chroots/kali-rolling...
```

**Comment by duck955** [comment]
Additionally, when following the xfce4 wiki, the setup will not complete.  It also fails with too many symlinks.

![Screenshot 2020-10-22 at 1 51 49 PM](https://user-images.githubusercontent.com/73308348/96928849-09e6a280-146e-11eb-812d-d3fda649045e.png)
![Screenshot 2020-10-22 at 1 52 23 PM](https://user-images.githubusercontent.com/73308348/96928865-0f43ed00-146e-11eb-8bfd-d312fce25f47.png)

**Comment by ergpopler** [comment]
sudo enter-chroot /media/remove/sd card/chroot/chrootname?

**Comment by Ilazki** [comment]
I just ran into this same problem with a chroot on SD card.  Spent far too long troubleshooting, but it looks like the problem (at least for me) is that the SD card is being mounted with the `nosymfollow` option:

```
# mount|grep 'SD Card'
/dev/mmcblk1p1 on /media/removable/SD Card type ext4 (rw,nosuid,nodev,relatime,nosymfollow,dirsync,seclabel,data=ordered)
```

If I remove that with `mount -o remount,symfollow /media/removable/SD\ Card/` everything works again.  The `nosymfollow` option prevents following of symlinks, which triggers a confusing message with `chroot`.  I was already remounting the SD card to remove the `noexec` flag so I just added this to my first-run-after-reboot ritual.  Minor inconvenience now, but I wasted a lot of time hunting down the problem thanks to useless error messages. 

This seems to have started for me after a recent ChromeOS update, so I guess Google started mounting the SD cards differently and broke everything?  Not sure when this started but I'm currently on beta channel, running 88.0.

**Comment by JessicaMulein** [comment]
+1

**Comment by Visual-mov** [comment]
This solution worked for me, thanks!
