### ISSUE TITLE
crouton Failed to complete chroot setup cloudready

### ISSUE THREAD

**Issue by madhits** [dnschneid/crouton#4361]
```
Please paste the output of the following command here: 
sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
targets: xiwi,xfce
host: version 85.3.2 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 5.4.53+ #2 SMP Sat Oct 3 18:52:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xfce
host: version 85.3.2 (Developer Build - neverware) stable-channel chromeover64
kernel: Linux localhost 5.4.53+ #2 SMP Sat Oct 3 18:52:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Compiling CRAS (i386)...
tools/cras_test_client/cras_test_client.c: In function 'show_alog_tag':
tools/cras_test_client/cras_test_client.c:592:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   float f = *((float *)&data3);
   ^
tools/cras_test_client/cras_test_client.c: At top level:
cc1: error: unrecognized command line option '-Wno-int-in-bool-context' [-Werror]
cc1: all warnings being treated as errors
/usr/lib/gcc/x86_64-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: error: ld returned 1 exit status
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### If known, describe the steps to reproduce the issue:
failed during install.

**Comment by madhits** [comment]
Can't complete install, i did try with bionic and im trying again with a different distro to see how that goes, i assume the same error will occur.

**Comment by DennisLfromGA** [comment]
It may be another upstream change that crouton will have to accommodate, similar to this one:
- https://github.com/dnschneid/crouton/pull/4211

Cloudready is a bit different but maybe @drinkcat or another crouton devs will get a chance to look at this soon.

-**DennisLfromGA**
