### ISSUE TITLE
unable to download ubuntu

### ISSUE THREAD

**Issue by Blazingsoul6666** [dnschneid/crouton#4364]
```
chronos@localhost / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
chronos@localhost / $ sudo crouton -t unity
Downloading latest crouton installer...
############################################################################################################################################## 100.0%############################################################################################################################################## 100.0%
unity is unsupported on ARM for releases after precise.
Invalid target "unity".
```

I tried to get ubuntu but when i input `sudo crouton -t unity` it keeps saying that "unity is unsupported on ARM for releases after precise". what does this mean? and how can i fix this? Keep in mind i'm very new to this so i barely know whats going on.

**Comment by MrHallway0** [comment]
Unity is not supported on ARM Chromebooks. Try one of these: 
`sudo crouton -t xfce -r sid` (for the XFCE desktop) or another target in `sudo crouton -t list`.
I hope this helps!

**Comment by Blazingsoul6666** [comment]
I tried that it for some reason it didn't work so tried  `sudo crouton -t xfce -r sid` but that didn't work ether. It gave this`E: Sub-process /usr/bin/dpkg returned an error code (1)` I couldn't find the error code but thanks anyway.

**Comment by MrHallway0** [comment]
Do you mind running `sudo edit-chroot -a` for me?

**Comment by Blazingsoul6666** [comment]
I don't mind,it says:
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: sid
architecture: arm64
targets: gnome
host: version 13421.73.0 (Official Build) stable-channel hana 
kernel: Linux localhost 3.18.0-20561-g658cbb775e96 #1 SMP PREEMPT Tue Oct 20 09:26:55 PDT 2020 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

**Comment by MrHallway0** [comment]
So, it looks like you have GNOME (`sid`) installed...
As far as I know GNOME doesn't play well with newer Debian distros with Crouton. 
We should remove it with `sudo edit-chroot -d sid`. If you have stuff worth saving in the chroot we can remove just the desktop and install a new one but this is a bit more complicated. Let me know if we need to do this.

**Comment by DennisLfromGA** [comment]
Hmm, not sure why sid was suggested since an Ubuntu xenial release, the default, was attempted to begin with.
Since the unity target is no longer supported on arm devices and since you seem to like the gnome desktop try installing it with this:
- `sudo crouton -t gnome`

That will install the Ubuntu xenial release with the xorg xmethod and a gnome desktop.

*Hope this helps,*
-**DennisLfromGA**

**Comment by MrHallway0** [comment]
@Blazingsoul6666: 

>I don't mind,it says:
**name: sid**
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: sid
architecture: arm64
targets: gnome
host: version 13421.73.0 (Official Build) stable-channel hana
kernel: Linux localhost 3.18.0-20561-g658cbb775e96 #1 SMP PREEMPT Tue Oct 20 09:26:55 PDT 2020 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

**Comment by DennisLfromGA** [comment]
@MrHallway0,

Yes, indeed, but only *after* you told @Blazingsoul6666 was told to try it.
![image](https://user-images.githubusercontent.com/3418772/97507330-5bea6500-1953-11eb-8e13-422ccbd1e30a.png)

*Hope this helps,*
-**DennisLfromGA**

**Comment by MrHallway0** [comment]
@DennisLfromGA 

> A program that is run in such a modified environment cannot name (and therefore normally cannot access) files outside the designated directory tree.
- [Wikipedia](https://en.wikipedia.org/wiki/Chroot)

So, it couldn't be a problem with an almost blank chroot's files, right? Of course we should remove both of the chroot's files and try GNOME on more time... 

**Please note**: Gnome doesn't work correctly on Crouton with newer releases (I will probably need to create an issue for it)...

**Comment by DennisLfromGA** [comment]
@MrHallway0,

I believe I have the gnome desktop working on xenial and some newer releases but success may depend on the device.
If gnome doesn't work for you I suggest trying lxde or the full lxde-desktop, that's what I use most often.

*Hope this helps,*
-**DennisLfromGA**
