### ISSUE TITLE
Sleep mode vs crostini: Sommelier differences for non-crostini users?

### ISSUE THREAD

**Issue by satmandu** [dnschneid/crouton#4366]
I'm working on updating the version of sommelier in chromebrew to the current version in https://github.com/skycocker/chromebrew/pull/4450 and the remaining major problem I am seeing is that sommelier's connection to the ChromeOS wayland server drops when the machine goes to sleep.

Specifically this error: ```(EE) failed to read Wayland events: Broken pipe```

When using the crouton version of sommelier, have any of you figured out a workaround?

This obviously isn't a problem with crostini, but my guess is that sleep mode freezes the crosvm instance, which helps.

Short of taking a notification from powerd that it is about to sleep the machine and sending a suspend signal to sommelier, is there a better way to preserve the sommelier/wayland connection across sleep/suspend events?

**Comment by smibarber** [comment]
@zachreizner has dealt with the wayland socket before, but I don't recall the connection dropping across suspend/resume cycles. it does get broken when chrome restarts.

**Comment by satmandu** [comment]
I'm not shocked by chrome restarts breaking apps!  But I'd like the connection to the Wayland compositor not to drop since that kills any graphical apps being used.

**Comment by kapilhp** [comment]
Under crouton `sommelier` does not crash on suspend. The windows continue to be available after resume.

**Comment by satmandu** [comment]
Ok that's interesting. Let me replicate that.

**Comment by satmandu** [comment]
@kapilhp You're just talking about sommelier using the steps here, right?
https://github.com/dnschneid/crouton/wiki/Sommelier-%28A-more-native-alternative-to-xiwi%29

**Comment by satmandu** [comment]
@kapilhp I've done a test install of crouton, used the steps above to install sommelier, and then run xterm, and when I sleep this is what happens:

```
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Error:            Illegal keycode 569 (must be in the range 8-255 inclusive)
>                   Value of "maximum" not changed
> Error:            Illegal keycode 372 for name <I372>
>                   Must be in the range 8-255 inclusive
> Error:            Illegal keycode 382 for name <I382>
>                   Must be in the range 8-255 inclusive
> Error:            Illegal keycode 569 for name <I569>
>                   Must be in the range 8-255 inclusive
Errors from xkbcomp are not fatal to the X server
(EE) 
Fatal server error:
(EE) failed to dispatch Wayland events: Broken pipe
(EE) 
```

```
xterm: fatal IO error 11 (Resource temporarily unavailable) or KillClient on X server ":0"
```
(This is exactly the same error I am getting in chromebrew, or using the crostini version of sommelier.)

**Comment by kapilhp** [comment]
Mysterious!

I am using the instructions at https://github.com/dnschneid/crouton/issues/4363#issuecomment-719921817 to build and run `sommelier`. These are based on the chromebrew recipe for building it.

I did not create a fresh crouton but installed `xterm` and tested it. It did not crash.

**Comment by satmandu** [comment]
Huh. Could you run ```sudo powerd_dbus_suspend --delay=2``` from crosh after you have started the xterm?

If that doesn't work make sure that ```/usr/local/var/run/dbus``` is a symlink to ```/var/run/dbus``` as per:

```
chronos@localhost / $ ls -aFl /usr/local/var/run/dbus
lrwxrwxrwx. 1 root root 13 Nov 10 10:28 /usr/local/var/run/dbus -> /var/run/dbus/
chronos@localhost / $ 
```

That should put you into sleep, and then you can wake your device normally and see if the xterm is still there.

(I've noticed xterms surviving if I come out of sleep really fast.)

**Comment by kapilhp** [comment]
The xterm survived. I even made myself a tea in between!

There may be some difference in versions.

The above was done on ChromeOS version 88. However, I have not had issues with version 86 either.

Secondly, I am running `bullseye` not `buster`.

**Comment by satmandu** [comment]
hmmm...this is what I did on M87 Beta on nocturne:

```
cd Downloads
mkdir s
cd s
curl -OLf https://github.com/dnschneid/crouton/files/5468958/sommelier.gz
curl -OLf https://github.com/dnschneid/crouton/files/5468959/runsommelier.gz
curl -OLf https://github.com/dnschneid/crouton/files/5468960/sommelierrc.gz
curl -OLf https://github.com/dnschneid/crouton/files/5468961/startsommelier.gz
gunzip *
sudo crouton -n test -r bullseye -t core
cp sommelier /tmp/crouton-installer-cache/sommelier
sudo crouton -n test -u -T /tmp/crouton-installer-cache/sommelier 
sudo enter-chroot -n test
cd Downloads/s
sudo mkdir -p /usr/local/{bin,etc}
sudo cp sommelierrc /usr/local/etc
sudo cp runsommelier /usr/local/bin
sudo chmod +x /usr/local/bin/runsommelier
runsommelier xterm
tail -F /tmp/sommelier.log
```

In another crosh window I now run this:
```
sudo powerd_dbus_suspend --delay=2
```

And this is my output from /tmp/sommelier.log:
```
Errors from xkbcomp are not fatal to the X server
(EE) failed to read Wayland events: Connection reset by peer
xterm: fatal IO error 11 (Resource temporarily unavailable) or KillClient on X server ":0"
```

**Comment by satmandu** [comment]
Maybe this is a regression in M87?

**Comment by satmandu** [comment]
What hardware are you using?

**Comment by kapilhp** [comment]
Carried out (almost) exactly the same steps as outlined by @satmandu. (Had to vary a bit since crouton has had this problem of not keeping the "key" to read `Downloads`. So downloaded the files in a subdirectory of `/tmp/`.)

The `xterm` window did not crash.

This test was done on:

```
name: test
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/test...
crouton: version 1-20200724165050~master:08dac970
release: bullseye
architecture: amd64
targets: core
host: version 13421.89.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.193-16287-g11e511f19c3e #1 SMP PREEMPT Sun Nov 1 19:46:08 PST 2020 x86_64 GNU/Linux
freon: yes
```

**Comment by satmandu** [comment]
Ah you have a newer kernel too!
