### ISSUE TITLE
unable to see taskbar, display settings cant launch

### ISSUE THREAD

**Issue by kidney-bean** [dnschneid/crouton#4367]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: arm64
xmethod: xorg
targets: xfce
host: version 13421.73.0 (Official Build) stable-channel elm 
kernel: Linux localhost 3.18.0-20561-g658cbb775e96 #1 SMP PREEMPT Tue Oct 20 08:50:48 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
When i installed, i cannot see any taskbar. I figured the display settings might not be the right size. i get unable to start Xfce Display Settings.

system is an acer chromebook r13
#### If known, describe the steps to reproduce the issue:
do a fresh install

**Comment by MrHallway0** [comment]
Did a message pop up on your first boot?

**Comment by alec-j0217** [comment]
No

**Comment by MrHallway0** [comment]
try this... 

> `xfce4-panel --quit ; pkill xfconfd ; rm -rf ~/.config/xfce4/panel ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml ; xfce4-panel;`
- [Resetting Xfce Panels to default settings?](https://askubuntu.com/questions/224006/resetting-xfce-panels-to-default-settings)

**Comment by alec-j0217** [comment]
In crosh or terminal

**Comment by MrHallway0** [comment]
Terminal or `sudo enter-chroot` in crosh shell followed by the command...

**Comment by alec-j0217** [comment]
failed to quit the panel

**Comment by MrHallway0** [comment]
try exiting crouton (`ctrl+c` or close the tab) in the crosh shell that it's running in. Then running `sudo enter-chroot` like said in the other comment.

**Comment by alec-j0217** [comment]
![Uploading Screenshot 2020-10-28 at 8.38.07 PM.png…]()

**Comment by MrHallway0** [comment]
Do you mind sending me a text version. The photo is not loading for me.

**Comment by alec-j0217** [comment]
Entering /mnt/stateful_partition/crouton/chroots/xenial...
WARNING: Unable to register core dump handler.
xfce4-panel: Cannot open display: .
Type "xfce4-panel --help" for usage.
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
bash: xfce4-panel: command not found

**Comment by alec-j0217** [comment]
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in sid
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

**Comment by MrHallway0** [comment]
Try reinstall crouton: 
 1. [Download](https://goo.gl/fd3zc)
 2. `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`
That should work... tell me if it doesn't.

**Comment by alec-j0217** [comment]
failed to complete chroot setup
i even powerwashed and still get the error

**Comment by MrHallway0** [comment]
Did you install another chroot after the powerwash?

**Comment by alec-j0217** [comment]
yes

**Comment by MrHallway0** [comment]
can you do `sudo edit-chroot -all` for me?

**Comment by alec-j0217** [comment]
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: sid
architecture: arm64
targets: xfce
host: version 13421.73.0 (Official Build) stable-channel elm 
kernel: Linux localhost 3.18.0-20561-g658cbb775e96 #1 SMP PREEMPT Tue Oct 20 08:50:48 PDT 2020 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/sid...

**Comment by alec-j0217** [comment]
its like i have a curse whenever i mess with linux, whether it be this or a raspberry pi, things always seem to go wrong.

**Comment by MrHallway0** [comment]
Don't worry my attempts with the Raspberry Pi usually aren't fruitful like %80 of the time.
Let's try `sudo crouton -t lxde`.

**Comment by alec-j0217** [comment]
hey its working now!

**Comment by MrHallway0** [comment]
Do you have LXDE or XFCE desktop?

**Comment by alec-j0217** [comment]
Lxde

**Comment by MrHallway0** [comment]
Good!

**Comment by alec-j0217** [comment]
cant really get anything compatible with arm64 though

**Comment by MrHallway0** [comment]
Yes, I understand that. What do you plan to do? I might be able to help you...

**Comment by alec-j0217** [comment]
Discord, minecraft

**Comment by MrHallway0** [comment]
Okay so you can't install Minecraft on ARM, there is a way to get the pocket edition (see: [*HOW TO PLAY MINECRAFT BEDROCK ON YOUR CHROMEBOOK*](https://chromeunboxed.com/how-to-play-minecraft-bedrock-on-your-chromebook/)). Also because Linux doesn't seem to come with Discord's PPA you need to download it manually. Run the following commands:

```
cd /tmp
wget https://discord.com/api/download?platform=linux&format=deb
sudo apt-get install /tmp/discord-0.0.12.deb -y
```

That should work to install it...

**Comment by explodersname** [comment]
Simple fix I got working for xfce when I had the same problem is to go to xfce settings application then go to startup applications and create a new one and for the command make it "xfce4-panel" if pulseaudio isnt working as well just add one with the command "pulseaudio --start"
