### ISSUE TITLE
Crashes on modern releases with DBus error 

### ISSUE THREAD

**Issue by BetaPictoris** [dnschneid/crouton#4368]
```
name: sid
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sid...
crouton: version 1-20200724165050~master:08dac970
release: sid
architecture: amd64
xmethod: xorg
targets: gnome
host: version 13421.73.0 (Official Build) stable-channel auron_yuna 
kernel: Linux localhost 4.14.193-16287-g11e511f19c3e #1 SMP PREEMPT Tue Oct 20 09:02:41 PDT 2020 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
Getting an unknown error(s) with GNOME (`sid`).

Chrome OS developer Shell (crosh) does have errors as shown:
```
(EE) event4  - Elan Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.16.2/touchpad-jumping-cursors.html for details
(EE) event4  - Elan Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.16.2/touchpad-jumping-cursors.html for details
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
```

#### If known, describe the steps to reproduce the issue:
When running `sudo crouton -t gnome -r sid` GNOME installs fine.
When running `sudo startgnome` GNOME does not start right.

![IMG_20201028_175706](https://user-images.githubusercontent.com/65696362/97514014-fa25fd00-194a-11eb-9cc2-725b1e5d53bd.jpg)

**Comment by DennisLfromGA** [comment]
@MrHallway0 

Try it in an Ubuntu release like xenial for instance instead of a pure Debian release.

*Hope this helps,*
-**DennisLfromGA**

**Comment by MrHallway0** [comment]
Well... now it crashes when I open it.

errors in crosh shell:
```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1604005186.364025 sender=:1.18 -> destination=:1.292 serial=20001 reply_serial=2
   boolean true
```

**Comment by TheRealFanjin** [comment]
It's like that for me too. I just went with xfce

**Comment by Resurrection2981** [comment]
Same for me,too.Black screen.

**Comment by marauder316** [comment]
Did GNOME work with any _older_ Crouton release?

**Comment by TheRealFanjin** [comment]
> Did GNOME work with any _older_ Crouton release?

Yes, it worked for me but it was very laggy

**Comment by MrHallway0** [comment]
@marauder316 
GNOME works on older version *although* it lacks support for a large sum of software.

**Comment by marauder316** [comment]
Ah, ok.

**Comment by marauder316** [comment]
Is this problem only with GNOME?

**Comment by MrHallway0** [comment]
@marauder316 
I think so... I don't know about Ubuntu (`unity`), my Chromebook doesn't have a good chunk of storage to spare.

**Comment by cooldoglol** [comment]
i had the same issue with kali-rolling on my lenovo chromebook with an intel celeron N4000 and also on a cloudready hp all in one desktop (i later went back to windows 10)
i assume it might be an issue with xorg or graphical issues as i think some people fixed this issue by turning on 3D graphics. so this also happens in virtualbox... but VB is not crouton. so it may not...
focal with xfce works for me so it might be the desktops that are on steroids off gnome only (EG unity)

**Comment by cooldoglol** [comment]
someone got kali working using this method. https://www.youtube.com/watch?v=bvqk4wjkVyk&ab_channel=AlexaFeedTheKidsAlexaFeedTheKids
maybe try it for yourself and see if it works.

**Comment by MrHallway0** [comment]
@cooldoglol 
> someone got kali working using this method. https://www.youtube.com/watch?v=bvqk4wjkVyk&ab_channel=AlexaFeedTheKidsAlexaFeedTheKids
> maybe try it for yourself and see if it works. if it works. try reacting with a thumbs up to let me know and i will try it for myself.

Issue still seems to be effecting *all* modern releases seem to fail. I will do more investigation in a bit... maybe I will be able to find some logs.

**Comment by MrHallway0** [comment]
# Installation info
`XFCE FOCAL` - Fails CRAS 
`XFCE BULLSEYE` - Fails CRAS 
`GNOME SID` - Fails CRAS

It would seem that, due to the CRAS errors (#4450), no desktop can be installed and there for we can't get to the DBus errors, that occurred *after* the installation.

**Comment by Pedro36572** [comment]
same here

**Comment by 02tz** [comment]
`sudo nano /usr/share/gnome-session/sessions/gnome.session`
Go to last line and delete all apps listed until it is only the first one (Include the `;`)

**Comment by 02tz** [comment]
> `sudo nano /usr/share/gnome-session/sessions/gnome.session` Go to last line and delete all apps listed until it is only the first one (Include the `;`)

worked on debian bullseye idk bout you tho twizz

**Comment by ilteris** [comment]
yep above trick works by @02tz thank you sir
