### ISSUE TITLE
Chroot is laggy

### ISSUE THREAD

**Issue by KaidenYT** [dnschneid/crouton#4369]
Is there a way to assign more resources to the chroot idk

**Comment by benben233** [comment]
Same, using PixelbookGo, I feel every input has 0.5s lag. And many other problem, I think this project is deprecated

**Comment by marauder316** [comment]
Same on the Lenovo Duet :|
Too much lag, and freeing up things on ChromeOS does virtually nothing.

**Comment by MrHallway0** [comment]
please do `sudo edit-chroot -all`. I need to see something.
