### ISSUE TITLE
How do i get my USB Bluetooth adapter to work? Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by Mikroprocessor** [dnschneid/crouton#437]
I bought an USB bluetooth adapter and tried to plug it in, but Ubuntu 12.04 LTS does not start it up. Ubuntu recognize it but no more. My laptop is Acer C7 Chromebook.

If i write the command lsusb i got this message:

```
"Bus 002 Device 007: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)"
```

If i go the the system settings and then to Bluetooth it says with a locket grey text.

"No Bluetooth adapters found".

I have installed this:

```
"sudo apt-get install bluetooth blueman bluez-hcidump bluewho python-bluez bluez-tools"
```

If i then open "Bluetooth manager" i got this message:

   "Bluez daemon is not running, blueman-manager cannot continue. This probably means that there were no Bluetooth adapters detected or Bluetooth daemon was not started"

I have heard that the solution is that i need to update the kernel to a newer one. Is it possible to update kernel 3.4.0 to 3.11.0 on Ubuntu 12.04 LTS without any troubles?

**Comment by Rivas2016** [comment]
Anyone figure this out? I am experiencing similar problems.

**Comment by dminca** [comment]
1. `sudo apt-get install pulseaudio-module-bluetooth`
2. `pactl load-module module-bluetooth-discover`
3. Delete the device from bluetooth devices and pair it again.
