### ISSUE TITLE
Problem with my crouton

### ISSUE THREAD

**Issue by mateoblast** [dnschneid/crouton#4370]
Hello , i have that when i try to launch my linux ... Yesterday i delete my chroot and re install that , and today it's broke again

```
sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/bionic...
Creating input group with GID 222...
Moving #input GID from 222 to 223...
Usage: groupmod [options] GROUP

Options:
  -g, --gid GID                 change the group ID to GID
  -h, --help                    display this help message and exit
  -n, --new-name NEW_GROUP      change the name to NEW_GROUP
  -o, --non-unique              allow to use a duplicate (non-unique) GID
  -p, --password PASSWORD       change the password to this (encrypted)
                                PASSWORD
  -R, --root CHROOT_DIR         directory to chroot into

Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```

Thanks a lot for your help

**Comment by marauder316** [comment]
What exactly is wrong with your chroot?

**Comment by MrHallway0** [comment]
Is it displaying the text bellow when you run `sudo startxfce4`?
```
Entering /mnt/stateful_partition/crouton/chroots/bionic...
Creating input group with GID 222...
Moving #input GID from 222 to 223...
Usage: groupmod [options] GROUP

Options:
  -g, --gid GID                 change the group ID to GID
  -h, --help                    display this help message and exit
  -n, --new-name NEW_GROUP      change the name to NEW_GROUP
  -o, --non-unique              allow to use a duplicate (non-unique) GID
  -p, --password PASSWORD       change the password to this (encrypted)
                                PASSWORD
  -R, --root CHROOT_DIR         directory to chroot into

Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
```
Also please run `sudo edit-chroot -all` for us.

**Comment by mateoblast** [comment]
Hello i don't know , i can't launch my chroot .... i have this message again and again , i try anything , update crouton , update my chroot ... and nothing ...

**Comment by MrHallway0** [comment]
Yes, I understand. Although, I need to see more info on your chroot. Can you show us what `sudo edit-chroot -all` says?

**Comment by mateoblast** [comment]
Yeah sorry of course : 
sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xorg
targets: xfce,extension,keyboard,audio,cli-extra,core
host: version 13505.27.0 (Official Build) beta-channel octopus 
kernel: Linux localhost 4.14.199-16593-g5b8b8f424085 #1 SMP PREEMPT Tue Oct 27 20:56:26 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.

**Comment by MrHallway0** [comment]
@mateoblast 
Thank you. So, you upgraded from `cli-extra` to `xfce` is that right?

I think there is a problem with your user groups. Have you ever tried to create another user?

**Comment by mateoblast** [comment]
Hey guys I fix my problem when i create an another user :) thanks a lot and sorry to reply you just now
