### ISSUE TITLE
Display Rotation Crashes Chromebook

### ISSUE THREAD

**Issue by marauder316** [dnschneid/crouton#4371]
```
Please paste the output of the following command here: sudo edit-chroot -all
Password: 
name: cinnamon
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/cinnamon...
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: arm64
xmethod: xorg
targets: xiwi,x11,xorg,core,cli-extra,keyboard,touch,audio,extension,gtk-extra,gnome
host: version 13560.0.0 (Official Build) canary-channel kukui 
kernel: Linux localhost 4.19.152-10453-gdb6d2cd8e743 #1 SMP PREEMPT Wed Oct 28 00:52:55 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/cinnamon...
```

#### Please describe your issue:
Using the command `xrandr -o left` to rotate the screen crashes my Chromebook and restarts it. Display isn't fixed on startup.

#### If known, describe the steps to reproduce the issue:
`sudo startcinnamon` to enter the chroot
Once inside chroot, Ctrl+Alt+C to bring up the terminal
Inside the terminal, `xrandr -o left`, which leads to a restart.
Alternatively, going to display settings and manually rotating the display leads to a restart.

This is also a problem I occasionally have with chroots in general.
[Note: I used Tenn1518's repo [https://github.com/Tenn1518/crouton-cinnamon](url) to use the Cinnamon desktop environment]

**Comment by MrHallway0** [comment]
Have you tried other targets (not form other repos)? If so does this happen with them?

**Comment by marauder316** [comment]
I have. It occasionally happens with KDE, LXDE, and used to happen every time with Gnome and XFCE.

Cinnamon seems to be working now, so I'll close and reopen if necessary.

Thanks!
