### ISSUE TITLE
Intel graphic acceleration not working with xorg on Lenovo Yoga C630

### ISSUE THREAD

**Issue by mammique** [dnschneid/crouton#4374]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: x11,touch,extension,xiwi,xfce,xorg,keyboard,audio,core
host: version 11316.165.0 (Official Build) stable-channel nami
kernel: Linux localhost 4.4.164-15546-gd8c7defc947f #1 SMP PREEMPT Sun Mar 3 22:58:16 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Hi all. I have a problem with hardware acceleration. The Intel driver seems loaded by X11 (see log files), but I have very low performances (`glxgears` outputs 70 fps, while it'as 1500 fps on xiwi). I can't locate the issue. `xorg-intel-sna.conf` doesn't make any difference… Can anyone help in locating the issue?

Thank you,

Bests,

Camille.

[dmesg.txt](https://github.com/dnschneid/crouton/files/5561563/dmesg.txt)
[edit-chroot.txt](https://github.com/dnschneid/crouton/files/5561564/edit-chroot.txt)
[glxinfo.txt](https://github.com/dnschneid/crouton/files/5561565/glxinfo.txt)
[inxi_-GxxSM.txt](https://github.com/dnschneid/crouton/files/5561566/inxi_-GxxSM.txt)
[lspci.txt](https://github.com/dnschneid/crouton/files/5561567/lspci.txt)
[vainfo.txt](https://github.com/dnschneid/crouton/files/5561568/vainfo.txt)
[Xorg.0.log](https://github.com/dnschneid/crouton/files/5561569/Xorg.0.log)

**Comment by xxmNIe** [comment]
do you fix it？bro

**Comment by xxmNIe** [comment]
i installed ubuntu20.04 , and every thing is ok    0.O!
