### ISSUE TITLE
Gnome keeps crashing back to terminal in Focal

### ISSUE THREAD

**Issue by higgy999** [dnschneid/crouton#4377]
```
name: ilikegnomes
encrypted: no
Entering /media/removable/USB Drive/Gnome/chroots/ilikegnomes...
crouton: version 1-20200724165050~master:08dac970
release: focal
architecture: amd64
xmethod: xorg
targets: xorg,audio,core,gtk-extra,x11,gnome
host: version 13421.99.0 (Official Build) stable-channel gnawty 
kernel: Linux localhost 4.4.232-19106-g8255e54b7c36 #1 SMP PREEMPT Wed Nov 11 03:00:51 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/Gnome/chroots/ilikegnomes...
```

#### Please describe your issue:

I was this command to install Focal Foosa with Gnome on my Acer Chromebook 11 (CB3-111): sudo crouton -r focal -t xorg,audio,core,gtk-extra,x11,gnome -p '/media/removable/USB Drive/Gnome'
I am installing it on a external drive and I have properly made the drive an exec one, but when running startgnome the screen goes black a white cursor comes up which I can move and then after a minute brings me back to the terminal crashed. Here is the full log after running startgnome: [Pastebin](https://pastebin.com/SEN95ycF)
The thing is though is that this only happens with Gnome. I have made one also with xfce which runs and starts fine, but gnome just doesn't work. If someone could please help, thank you so much!

**Comment by MrHallway0** [comment]
Can you give me the terminal output when it crashes? 

Also check out #4368.

**Comment by higgy999** [comment]
> Can you give me the terminal output when it crashes?
https://pastebin.com/SEN95ycF

**Comment by MrHallway0** [comment]
I'm having the same problem.
> Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files

**Comment by higgy999** [comment]
Guess I'll use xfce

**Comment by Just-Randomly-Me** [comment]
Same with mine it only seems to work with xfce
