### ISSUE TITLE
Deleting Crouton

### ISSUE THREAD

**Issue by DMSUYT** [dnschneid/crouton#4378]
```
Please paste the output of the following command here: sudo crouton -t xfce
```

#### Please describe your issue: /usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.

**Comment by MrHallway0** [comment]
To view your chroots: `sudo edit-chroot -a`.
To delete one of your chroots: `sudo edit-chroot -d <chroot name>`.

**Hope this works!**

**Comment by DMSUYT** [comment]
> To view your chroots: `sudo edit-chroot -a`.
> To delete one of your chroots: `sudo edit-chroot -d <chroot name>`.
> 
> **Hope this works!**

It says sudo: edit-chroot: command not found

**Comment by MrHallway0** [comment]
I think there is another command to delete them... try `sudo delete-chroot xenial`.

**Comment by DMSUYT** [comment]
Still doesn't work

**Comment by MrHallway0** [comment]
try `sudo crouton -n xenial -u -t xfce`.

**Comment by DMSUYT** [comment]
It worked! Thank you!

**Comment by DennisLfromGA** [comment]
Of note: 
In the future if your scripts under `/usr/local/bin/` happen to get removed you can reinstall them using the '`-b`' option, like: 
- `sudo crouton -b`  

See below for usage:
```
-b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
```
*Hope this helps,*
-**DennisLfromGA**
