### ISSUE TITLE
Change default user

### ISSUE THREAD

**Issue by qaqak** [dnschneid/crouton#4379]
#### Please describe your issue:
How to I change what user is the default user?

#### What do I mean by that?
Right now, when I run ```sudo startmate```, it starts Ubuntu MATE as ```qaqak``` (My default user).
How do I change it so that when I run ```sudo startmate```, Ubuntu MATE starts as ```root```

**Comment by DennisLfromGA** [comment]
The `startmate` script & the mate desktop are not standard crouton built-in scripts or targets so I can't answer that without knowing more about your `startmate` script. But, all sanctioned crouton `start*` scripts support the `-u [USERNAME]` option, see below:
```
startlxde -h

enter-chroot [options] [command [args...]]

Enters an installed Debian-based chroot for running alongside Chromium OS.

By default, it will log into the primary user on the first chroot found.
You can specify a command and parameters to run instead of an interactive shell.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: /mnt/stateful_partition/crouton/chroots
    -l          Make the command part of a login. Parameters are passed directly
                to the chroot command, and a call to su is appended.
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -X XMETHOD  Override the auto-detected XMETHOD for this session.
    -x          Does not log in, but directly executes the command instead.
                Note that the environment will be empty (sans TERM).
                Specify -x a second time to run the /prepare.sh script.
```
So if your start script follows that scheme then just append `-u root` on the command-line when you launch your desktop.
**Big warning here though**: It is NOT a good idea to launch your desktop as root, bad things can happen with permissions that are not easily undone.

*Hope this helps,*
-**DennisLfromGA**

**Comment by qaqak** [comment]
[This is the article that I used](https://medium.com/power-user/ubuntu-mate-on-a-chromebook-with-crouton-2cebd167382)
I needed to login as `root` so I could update the system
How do I give user `qaqak` root permissions?
PS. The `startmate`script stopped working because of /bin/sh 0: Illegal operator: -`, so I am trying to use Ubuntu Eoan.
Thanks for the help!

**Comment by qaqak** [comment]
Eoan did not work. I am using the article again, but the error came again
Closing issue
