### ISSUE TITLE
launch-at-startup-script to be an option in regular crouton

### ISSUE THREAD

**Issue by croutongamer-coder** [dnschneid/crouton#4380]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce-desktop
host: version 12239.92.2 (Official Build) stable-channel panther 
kernel: Linux localhost 3.8.11 #1 SMP Thu Sep 12 09:43:10 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
It would be great if this script were to be default!
[6443733-master.zip](https://github.com/dnschneid/crouton/files/5613897/6443733-master.zip)

**Comment by DennisLfromGA** [comment]
@croutongamer-coder,

Yes, that would be great but for that to happen the devs would have to include that script in the default CrOS image/load, I don't think that will ever happen, especially now that an official Crostini container is now available.

It's a bit of a chore to copy that script into /etc/init after each update so I have a script that does it to make it a little easier.
Basically, it just removes rootfs write protection, reboots, and copies the script from a safe place to /etc/init.

**Comment by DennisLfromGA** [comment]
Closing. Please file a crbug feature request if this issue is still a concern.
