### ISSUE TITLE
Can't use KDE with Debian

### ISSUE THREAD

**Issue by qaqak** [dnschneid/crouton#4381]
#### Please describe your issue:
When I run `sudo crouton -t kde -r buster -n debian` to install Debian and then run it, the X server starts, but I get a dialog saying `Could not start kdeinit5. Check your installation`

#### If known, describe the steps to reproduce the issue:
Running `sudo crouton -t kde -r buster -n debian`  then `sudo startkde`

**Comment by YumeDragoon** [comment]
try using the target `kde-desktop` as that worked fine for me on buster. 
though my whole command was `sudo crouton -r buster -t xorg,extension,kde-desktop,core,keyboard,audio`
oh and also make sure you have the latest version of crouton too.

**Comment by qaqak** [comment]
OK Will do
