### ISSUE TITLE
Give root permissions to user

### ISSUE THREAD

**Issue by qaqak** [dnschneid/crouton#4382]
I followed [this article](https://medium.com/power-user/ubuntu-mate-on-a-chromebook-with-crouton-2cebd167382) to install Ubuntu Mate on my Chromebook
Now, I want to update the system from Xenial (16.04) to Bionic (18.04) to Focal (20.04)
Currently, I have to login as `root` to run `Software Updater`
How do I give my primary user permissions to use `Software Updater`?

**Comment by MrHallway0** [comment]
You are going to need to run it on the command line.
I do not know the `Software Updater` command, but, you can use `sudo apt update && sudo apt upgrade` to make sure everything is up to date! 

***Always remember that you don't want to login as `root` as you can easily break something!***

**Comment by qaqak** [comment]
I have to run `sudo gksudo software-manager`
Or...something like that...
