### ISSUE TITLE
Dear Mr. Author, goo.gl/fd3zc <- this link is not working anymore, I can't download the crouton installer anymore. I hope you could fix this soon. Thank you!

### ISSUE THREAD

**Issue by makebabynotwar** [dnschneid/crouton#4383]
Dear Mr. Author, goo.gl/fd3zc <- this link is not working anymore, I can't download the crouton installer anymore. I hope you could fix this soon. Thank you!

_Originally posted by @makebabynotwar in https://github.com/dnschneid/crouton/issues/4026#issuecomment-739509990_

**Comment by MrHallway0** [comment]
This link *should* still work. Check your internet settings along with your DNS to see if there is a problem with those. Further more admin can block sites, so check witch account you are using. Also at time the page just doesn't load at this time, try it in a couple of hours!

**Comment by makebabynotwar** [comment]
Thank you for responding! I don't know what happened but it kept telling me
that the page was temporarily unavailable or web page could be in another
address or something like that.. It's all good now though, it finally
loaded and I was able to download it. Again thank you so much for your help

**Comment by DennisLfromGA** [comment]
The [https://goo.gl/fd3zc](https://goo.gl/fd3zc) link is working.

Closing.
