### ISSUE TITLE
dowloading linux on chrome os

### ISSUE THREAD

**Issue by ColtonWright** [dnschneid/crouton#4385]
I dont know how to code or how computers work but i tried to follow step by step instructions on how to download linux on a chrome os computer and i went to crosh typed shell then i typed :
sudo sh -e ~/Downloads/crouton
and it said:
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
how do i fix this and download linux???
![Screenshot 2020-12-10 at 15 12 18](https://user-images.githubusercontent.com/75813723/101836214-3166fc80-3afa-11eb-98bb-026e508fe298.png)

**Comment by DennisLfromGA** [comment]
@ColtonWright,

Those step-by-step instructions are no longer correct.
Please read the [README](https://github.com/dnschneid/crouton/blob/master/README.md) for up-to-date instructions and examples.

*Hope this helps,*
-**DennisLfromGA**

**Comment by MrHallway0** [comment]
@ColtonWright 
Please follow the [README](https://github.com/dnschneid/crouton/blob/master/README.md#Examples), like @DennisLfromGA, said and close this issue.

**Comment by abe-csm** [comment]
I am having the same problem as Colton and I am using the "new" Readme.  I know nothing about this techie stuff and I may be a dolt, but I get the exact same error.  I have followed the document "explaining" noexec, but don't understand that either.  I am running a Samsung Chromebook Pro, am in developer mode, entered the shell, ran sudo crouton.  All of that works as expected.  Then I get the error when trying to run "sh ~/Downloads/**_anything_**.

**Comment by MrHallway0** [comment]
Try [this](https://medium.com/@MrHallway/installing-linux-on-a-chromebook-492ca390cc06) for instructions.

**Comment by abe-csm** [comment]
Thank you very much.  curiously enough, just after sending my post I
discovered another entry on the I-net that suggested a different syntax to
the command to in Linux using crouton.  Viola, it worked!  I installed
Debian with KDE.  I will go back an compare my cmd line to what you have to
ensure they are the same.

I did notice that something may be awry as Debian was running very, very
slowly.  I will have to fix that to have a real, productive installation.

Thank you very much,

Abe

**Comment by OBSmoove** [comment]
Can anyone help me? that code won't work for me. It just says 
install: cannot stat '/home/chronos/user/Downloads/crouton': No such file or directory.

**Comment by MrHallway0** [comment]
@OBSmoove can you please give me the command you are running?

**Comment by DennisLfromGA** [comment]
@OBSmoove,

You have to first download **[crouton](https://goo.gl/fd3zc)** and be sure to place it in **`~/Downloads`**.

*Hope this helps,*
-**DennisLfromGA**

**Comment by OBSmoove** [comment]
I downloaded the file and had it in downloads its the code i don't get why
it didn't work

**Comment by DennisLfromGA** [comment]
@OBSmoove,

Please show us what is displayed when you enter: `ls -l ~/Downloads/crouton`

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by hiddensea** [comment]
> Can anyone help me? that code won't work for me. It just says install: cannot stat '/home/chronos/user/Downloads/crouton': No such file or directory.

you left the full stop in there
