### ISSUE TITLE
How crouton X server start alongside Chrome OS display server?

### ISSUE THREAD

**Issue by supechicken666** [dnschneid/crouton#4387]
Hi there

Not an issue, more a little question for me
How can crouton start an X server alongside the Chrome OS display server?
(Is the `xinit` process based on Wayland?)

Thanks for any answer :)

**Comment by MrHallway0** [comment]
`xserverrc-xorg` (line 33): "# Freon necessitates the preload hack for X to coexist";

**Comment by dnschneid** [comment]
ChromeOS's display server has a dbus command to make it release ownership of the hardware.  We use the preload to override X11's attempts to grab the virtual terminal with some fake replies alongside calls to that dbus endpoint.

See https://github.com/dnschneid/crouton/blob/master/src/freon.c for the nitty-gritty.
