### ISSUE TITLE
Dbus-launch

### ISSUE THREAD

**Issue by kubaswieca** [dnschneid/crouton#4396]
I installed kali linux but everytime i type in
`sudo startxfce4`
It launches linux but on entrysays failed to execute dbus-launch

**Comment by GiddyLinux** [comment]
> I installed kali linux but everytime i type in
> `sudo startxfce4`
> It launches linux but on entrysays failed to execute dbus-launch

just do:

`sudo enter-chroot `

and then do:

`sudo apt install dbus-x11`
