### ISSUE TITLE
Upgrade to Ubuntu 18.04 LTS on Toshiba 2 Chromebook

### ISSUE THREAD

**Issue by froukehe0** [dnschneid/crouton#4397]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

I have a Toshiba 2 Chromebook where the hardware still works perfectly, but the Ubuntu version (16.04 LTS) will reach end of support in a few months. I have tried to upgrade to 18.04 LTS a few times, but always with issues. Would you know whether there will be support for a newer version of Ubuntu any time soon, so that I do not need to try and flash the bios to keep the laptop working?

**Comment by DennisLfromGA** [comment]
@froukehe0,

> I have tried to upgrade to 18.04 LTS a few times, but always with issues.

Yes, release upgrades are often problematic, it's best just to do a fresh install of Bionic Beaver / 18.04.
However, be aware it is not fully supported but has been reported to work pretty well, I can attest to that.

The next Ubuntu release that the crouton devs will support will be Focal Fossa / 20.04.
See this issue for more details about that and a timeline.
- FOCAL FOSSA! · Issue #4265 · dnschneid/crouton

Your '[Toshiba 2 Chromebook](https://support.google.com/chrome/a/answer/6220366?hl=en#zippy=%2Ctoshiba)' will hit it's Auto Update Expiration (AUE) date this year it appears:

| Toshiba     | AUE |
| ----------- | ----------- |
| Chromebook 2 | Sep 2021 |  
| Chromebook 2 (2015 Edition) | Jun 2021 |  

That does *not* mean it will not keep working, it just won't be guaranteed to receive updates after that time, in most cases Google will provide updates to these devices after the AUE date, often up to a year afterward.

*Hope this helps,*
-**DennisLfromGA**
