### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by OBSmoove** [dnschneid/crouton#4400]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by MrHallway0** [comment]
Can you find a file named `crouton` in your downloads folder? If not download it from https://goo.gl/fd3zc.

**Comment by OBSmoove** [comment]
I have the crouton file thingy and i opened it. Thats when i entered the
codes in to download linux and it didn't work

**Comment by OBSmoove** [comment]
OMG thanks man that file worked!!
