### ISSUE TITLE
two finger scrolling stopped working (after update...) 

### ISSUE THREAD

**Issue by westmj** [dnschneid/crouton#4409]
```
Please paste the output of the following command here: sudo edit-chroot -all
`` sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xiwi
targets: audio,chrome-beta,core,cli-extra,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,touch,kodi,gtk-extra,xfce,xfce-desktop
host: version 13729.8.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-20612-g40583ad71f80 #1 SMP PREEMPT Mon Jan 25 20:53:40 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/bionic as another instance is using it.`

#### Please describe your issue:

on my touchpad, two finger scrolling used to bing me up and down pages like the up arrow or down arrow.  Now has no effect. 

#### If known, describe the steps to reproduce the issue: use touchpad with 2 fingers

**Comment by phummel** [comment]
I have the same issue in bullseye. Installing libinput-tools and running the debug-gui the touchpad is detected as well as scroll events (both horizontally and vertically). Looking at the mouse/touchpad settings in xfce settings, no device is listed, the dropdown box is grayed out, and no options can be changed.

**Comment by westmj** [comment]
Works now after updating!   

chronos@localhost / $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xiwi
targets: audio,chrome-beta,core,cli-extra,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,touch,kodi,gtk-extra,xfce,xfce-desktop
host: version 13729.16.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-20614-gb2c1aeff485f #1 SMP PREEMPT Wed Feb 3 21:04:04 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.

**Comment by westmj** [comment]
Broken again, see https://github.com/dnschneid/crouton/issues/4413 ... but how do I open this one?

**Comment by DennisLfromGA** [comment]
@westmj, 

As the originator you *should* be able tore-open this issue however just follow up in https://github.com/dnschneid/crouton/issues/4413, no need to track two issues.

-**DennisLfromGA**
