### ISSUE TITLE
2 finger scrolling no longer works in ChromeOS v89

### ISSUE THREAD

**Issue by cvmiller** [dnschneid/crouton#4413]
```
Please paste the output of the following command here: sudo edit-chroot -all
$ sudo edit-chroot -all
name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20200724165050~master:08dac970
release: buster
architecture: arm64
xmethod: xiwi
targets: xfce,extension,audio,xiwi,xorg,x11
host: version 13729.16.0 (Official Build) beta-channel bob 
kernel: Linux localhost 4.4.250-19713-g86a113a4c077 #1 SMP PREEMPT Wed Feb 3 20:32:48 PST 2021 aarch64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/buster as another instance is using it.
```

#### Please describe your issue:
Using the Xiwi Target, 2 finger scrolling no longer works in Crouton chroot (debian buster).

#### If known, describe the steps to reproduce the issue:
Upgrade ChromeOS to v89, start Crouton, once inside the XFCE window, open any window with text (say a terminal which you do a `ls` with a lot of files. Use 2 finger scroll on the trackpad to scroll the terminal window up or down.

Running `xev` inside the chroot, I note that no scroll events are making it to the Xserver

**Comment by cvmiller** [comment]
Looks like this could be fixed by the new Wayland support in target `somm` See issue #4410

**Comment by westmj** [comment]
Also broken in bionic again, just updated my ChromeOS and crouton...

see also closed https://github.com/dnschneid/crouton/issues/4409 , this is in a state of flux...

Your Chromebook is up to date
Version 89.0.4389.48 (Official Build) beta (64-bit)

name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xiwi
targets: audio,chrome-beta,core,cli-extra,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,touch,kodi,gtk-extra,xfce,xfce-desktop
host: version 13729.22.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-20614-gb2c1aeff485f #1 SMP PREEMPT Tue Feb 9 20:23:05 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
chronos@localhost / $

**Comment by westmj** [comment]
Two finger scrolling is back for me now.  Thank you, thank you, thank you. 

Hey, I am just a local user, I shouldn't be saying how to do things when I don't understand how it all works, but would it be a good idea to add a test for two-finger scrolling in the test-driven-development I hear so much about? And, is there something I can do for myself as a result of talk about "a new target somm"?  Should I change how I do my update? Which is now with "sudo crouton -u -n bionic" ?  Thanks for any advice about working smarter not harder. 



Version 89.0.4389.48 (Official Build) beta (64-bit)

chronos@localhost / $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xiwi
targets: audio,chrome-beta,core,cli-extra,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,touch,kodi,gtk-extra,xfce,xfce-desktop
host: version 13729.22.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-20614-gb2c1aeff485f #1 SMP PREEMPT Tue Feb 9 20:23:05 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
chronos@localhost / $

**Comment by cvmiller** [comment]
>Two finger scrolling is back for me now. 

What did you do to get the scrolling back? I just updated my Debian Buster chroot, and still no 2 finger scrolling (using CrOS v89.0.4389.48)

**Comment by westmj** [comment]
I just did:

chronos@localhost / $ sudo crouton -u -n bionic

i just follow recipes, maybe it has to do with my targets? 

targets: audio,chrome-beta,core,cli-extra,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,touch,kodi,gtk-extra,xfce,xfce-desktop .

and recall my question about target "somm", above.  Plus, I use lxde 

chronos@localhost / $ sudo startlxde

and bionic.  Not sure what is important. That's why I post...

**Comment by cvmiller** [comment]
Thanks for the update. Unfortunately, many of those targets aren't available with Debian (or ARM). But I ran an update "-u" and 2 finger scrolling is still broken for me :(

**Comment by westmj** [comment]
Gosh darn it, it stopped working with no apparent changes on my part.  Restarting did not restore it, upgrading did not restore it.  It is like the laptop is haunted.

chronos@localhost / $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xiwi
targets: audio,chrome-beta,core,cli-extra,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,touch,kodi,gtk-extra,xfce,xfce-desktop
host: version 13729.22.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-20614-gb2c1aeff485f #1 SMP PREEMPT Tue Feb 9 20:23:05 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
chronos@localhost / $

**Comment by westmj** [comment]
It's back.  So, this seems really random.  Thoughts?

**Comment by westmj** [comment]
It's gone.  New  version 13729.29.0 (Official Build) beta-channel chell . Same crouton.  A clue? But may not be reproducible... time will tell.

chronos@localhost / $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xiwi
targets: audio,chrome-beta,core,cli-extra,extension,keyboard,lxde,lxde-desktop,x11,xiwi,xorg,touch,kodi,gtk-extra,xfce,xfce-desktop
host: version 13729.29.0 (Official Build) beta-channel chell 
kernel: Linux localhost 3.18.0-20615-g21024ba2ab1d #1 SMP PREEMPT Tue Feb 16 20:31:44 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
chronos@localhost / $

**Comment by cvmiller** [comment]
I have scrolling back as well in v89.0.4389.57 on ARM. Like you, not sure how long it will be, but I am happy to have it back.

**Comment by westmj** [comment]
In Version 89.0.4389.57 (Official Build) beta (64-bit) and crouton as noted above, I DO NOT HAVE TWO-FINGER SCROLLING.  Maybe it is a toggle switch between ARM and Intel?  Who knows?  Kind of talking to each other in the dark here... can you hear me now?

**Comment by westmj** [comment]
The workaround I am now using is going to xorg, there my two-finger scrolling works.  I lose the shared clipboard, sadly, but if I use my browser in crouton instead of in chromeOS, that works okay for now.  Love to have a better solution.  

To make xorg the default, I use (primitively)

sudo  crouton -t xorg,xiwi -u -n bionic

but I vaguely recall there are ways to initiate with the xiwi or xorg as options.  But, hey, this works for me now.  YMMV.  Ciao.

**Comment by cvmiller** [comment]
I agree, the problem is more subtle that what machine you are using. I powered down my ARM, and restarted, and now two finger scrolling no longer works in Xiwi (it was working _before_ the power down).

@westmj I tried your work-around (using -t xorg) but I lost trackpad "touch" (for mouse clicks) and I couldn't get back to ChromeOS!! So for now I am back to Xiwi and no 2 finger scrolling ;(

**Comment by cvmiller** [comment]
A bit more data. After getting my ARM machine (a Asus C101PA) back working on Xiwi, I had no 2 finger scroll.

Rather than power down, I rebooted the chromebook from the Crosh/Shell with the command 'sudo reboot now'. After reboot (but _not_ power down), and restarting Crouton in Xiwi, 2 finger scrolling is working. But this could just be a fluke. It seems like some kind of timing issue between boot up from power down and just a reboot.

**Comment by westmj** [comment]
Well, there goes one of my assumptions, and good riddance. When I am in xorg rather than xiwi, the clipboard IS shared between chromeOS and crouton.  So xorg is making me happy, though the "4 finger salute" is more challenging than clicking icons to switch from chomeOS to crouton and back.

**Comment by joseinestroza** [comment]
I had this issue since the first Version 89 on stable channel, for one or two weeks. Your report is from February. Version 89.0.4389.95 (Build oficial) (64 bits) fixed the issue immediately. No Crouton update needed, neither Debian.

My configuration is running on x86 using Xiwi on Debian Buster.

At last!!
