### ISSUE TITLE
Switch between Crouton & ChromeOS with hot keys on a macbook

### ISSUE THREAD

**Issue by pjpreilly** [dnschneid/crouton#4416]
I found this but I can't seem to make hot switching work on my macbook with cloudready... any suggestions?

[LINK](https://gist.github.com/tgirke/be26f29b0b52ee621ec02f2bcbca0b93#ii-switch-between-chroot-and-chrome-os)

**Comment by DennisLfromGA** [comment]
I don't know if the crouton keyboard target would help at all but it might be worth a try.

Also, crouton chroots have a `croutoncycle` command that can be used in a chroot terminal session that might benefit you.
I set some `croutoncycle` aliases since I'm usually in a terminal in the chroot anyway, this way you don't have to depend on key-combos to do the switching.
Here are some of the aliases I set:
```
alias 0='croutoncycle cros'
alias 1='croutoncycle 1'
alias 2='croutoncycle 2'
alias 3='croutoncycle 3'
alias 4='croutoncycle 4'
alias cros='croutoncycle cros'
alias list='croutoncycle list'
alias next='croutoncycle next'
alias prev='croutoncycle prev'
```
So, in a chroot terminal session to switch back to CrOS just run: `croutoncycle cros`

*Hope this helps,*
-**DennisLfromGA**

**Comment by pjpreilly** [comment]
switch back to CrOS just run: croutoncycle cros ............

... That works but how do I go BACK to my still running Crouton session?

**Comment by DennisLfromGA** [comment]
I install and use the '[crouton integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom)' extension, once installed just click on it and choose the chroot you want to switch to, see below -

![image](https://user-images.githubusercontent.com/3418772/107821258-1dce5100-6d4a-11eb-9d41-0045692e6138.png)

*Hope this helps,*
-**DennisLfromGA**

**Comment by pjpreilly** [comment]
I did that but I'm getting an error as pictured....
![Screenshot 2021-02-12 at 4 46 52 PM](https://user-images.githubusercontent.com/10430084/107825959-06936180-6d52-11eb-88f8-bca8a88ad5b8.png)

**Comment by pjpreilly** [comment]
After enabling collect errors for the extension I get this each 5 seconds.....
![Screenshot 2021-02-12 at 4 53 32 PM](https://user-images.githubusercontent.com/10430084/107826499-fcbe2e00-6d52-11eb-91dc-e9ae2d53e20a.png)

**Comment by pjpreilly** [comment]
... & this too. Restarted with the same results...
![Screenshot 2021-02-12 at 5 07 34 PM](https://user-images.githubusercontent.com/10430084/107827530-f0d36b80-6d54-11eb-9c27-3d38a7fc8b28.png)

**Comment by DennisLfromGA** [comment]
I don't have a Mac and I'm no longer running Cloudready on anything so I don't have any other suggestions, sorry.

Some Mac users I believe have had success with '[Brunch](https://github.com/sebanc/brunch)', I use it on an old Chromebook and it's pretty awesome.  
The [Brunch Discord site](https://discord.gg/x2EgK2M) has some helpful users on it too if you need more guidance.

*Hope this helps,*
-**DennisLfromGA**

**Comment by pjpreilly** [comment]
Thanks @DennisLfromGA ... maybe someone will see this & have some answers...

**Comment by sudo-power** [comment]
I have a suggestion! try using xiwi snd the crouton chrome extension! for a new chroot you would do this:
`sudo crouton -t xfce,xiwi`

**Comment by pjpreilly** [comment]
Actually was trying this and getting a xenial version could not be determined error use -r... but that's not working either.

Add 'xiwi' or any other target to an existing chroot with the -u option: sudo crouton -t xiwi -u -n xenial

**Comment by itstoast27** [comment]
you need to first delete the existing chroot, or rename the one youre installing
this can be acomplished via either
```
sudo delete-chroot xenial
```
or by adding the `-n _name_` flag to your crouton install.
