### ISSUE TITLE
No audio in Discord 

### ISSUE THREAD

**Issue by Carl393** [dnschneid/crouton#4418]
Dear friends,

CRAS seems to handle the audio for crouton and hence when I use XFCE4 the audio settings are adjustable only through Chrome OS correct? When I check pulseaudio volume from the settings window in XFCE it says starting pulseaudio interface....and then nothing happens...

Skype for linux works fine however discord for linux simply shows there is no audio input available...

Is there any way for pulseaudio to handle the audio preferences (inputs/outputs etc) once the linux end of the chromebook (crouton?) Is running?

Is there a workaround to get discord for linux to recognize CRAS handling of the audio? Study groups dont work very well if you cannot talk or hear anyone :'-D

**Comment by DennisLfromGA** [comment]
Discord for Linux is problematic, to begin with. It's best just to use the Discord web site.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Carl393** [comment]
Hi There, is it possible to contact discord and tell them this issue and hope they fix it?

**Comment by Carl393** [comment]
This is the only information they provided me with:

Who is the creator of that github website?Do they work for DISCORD? I installed all of those requirements listed here.

https://github.com/simoniz0r/Discord-Linux-Client-Issues
I cannot get my discord native linux app to work on chromebook... the Audio does not work.....does it not know how to interface with CRAS? (Chromium OS Audio Server)

Please have someone with expertise with chromebook devices and discord (a developer) write me back.

I will wait to hear back from Discord, would you be so kind as to provide any more insight? (is there an override for CRAS) so pulseaudio handles the audio? or is this not possible?

Thanks Dennis

**Comment by Carl393** [comment]
See photo (no option to select any soundcard)
![Screenshot_2021-02-16_23-55-10](https://user-images.githubusercontent.com/14049856/108158313-a8001780-70b2-11eb-9be9-ccf3657c1b76.png)

**Comment by TheRealFanjin** [comment]
First of all, can you post the output of `sudo edit-chroot -all` in shell? Also, what happens when you do `pulseaudio --start`?

**Comment by primas305** [comment]
> First of all, can you post the output of `sudo edit-chroot -all` in shell? Also, what happens when you do `pulseaudio --start`?

"pulseaudio --start" this seems to fix it just start pulseaudio and restart Discord and cras shows up in the voice settings and audio works. Thanks
