### ISSUE TITLE
Crouton installs, but doesn't install chroots; most commands fail

### ISSUE THREAD

**Issue by marauder316** [dnschneid/crouton#4422]
Please paste the output of the following command here: sudo edit-chroot -all
```CS
┌[chronos@localhost] [/dev/pts/0] 
└[~]> sudo edit-chroot -all                                                                
sudo: edit-chroot: command not found
┌[chronos@localhost] [/dev/pts/0] [1]
└[~]> 
```

#### Please describe your issue:
I can install crouton according to the wiki, but commands such as installing a chroot (see below) fail.

#### If known, describe the steps to reproduce the issue:
```CS
┌[chronos@localhost] [/dev/pts/0] [1]
└[~]> sudo crouton -r focal -t x11,cli-extra,touch,audio,keyboard,extension,core,xorg,xfce
/usr/local/chroots/focal already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.
┌[chronos@localhost] [/dev/pts/0] [1]
└[~]> sudo delete-chroot focal -y                                                         
sudo: delete-chroot: command not found
┌[chronos@localhost] [/dev/pts/0] [1]
└[~]>
```
Using `sudo crouton -r focal -t x11,`... gave an error like "this directory does not exsist" and installation stops.

I've flawlessly used crouton before, and I've never had an issue like this; I'm on a Lenovo Ideapad Duet (64GB/aarch64)

**Comment by MrHallway0** [comment]
Have you tried updating it?

**Comment by marauder316** [comment]
I did, yeah
To get rid of the failed chroots, I had to entirely remove the crouton file and all crouton directories, after which I re-installed crouton, only to get the same errors.

(I no longer have the Duet at all (it went to a cousin), but I'll leave it up for anyone else who may have the same problems.)
