### ISSUE TITLE
can't create a new chroot

### ISSUE THREAD

**Issue by HEYimHeroic** [dnschneid/crouton#4433]
```
chronos@localhost ~ $ sudo edit-chroot -all
name: mychroot
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/mychroot...
Creating hwaudio group with GID 18...
su: Critical error - immediate abort
Unmounting /mnt/stateful_partition/crouton/chroots/mychroot...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
i just can't install a chroot. i've followed the instructions but it just doesn't seem to work. i've never done this before, but i did successfully follow the steps to install crouton.

if you need any more info, let me know - i'm sure this isn't enough but i'm not sure where to start with that.

**Comment by DennisLfromGA** [comment]
It appears your chroot installation did not complete successfully.

Try these troubleshooting steps:
- https://github.com/dnschneid/crouton/wiki/Common-issues-and-reporting

If those steps do not fix your issue then it might be best to delete your chroot with:
- `sudo delete-chroot mychroot`

And then start over.

*Hope this helps,*
-**DennisLfromGA**

**Comment by HEYimHeroic** [comment]
right, i have been starting over. the mychroot for example was the fourth chroot i made.

**Comment by dnschneid** [comment]
Please try the latest release of crouton and re-open if it doesn't fix the failure.
