### ISSUE TITLE
No Scroll in XFCE after update to ChromeOS 89

### ISSUE THREAD

**Issue by jcv969** [dnschneid/crouton#4436]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenialb
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenialb...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xiwi
targets: xfce,unity,xiwi
host: version 13729.45.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-20615-g21024ba2ab1d #1 SMP PREEMPT Fri Mar 5 05:24:31 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenialb...

#### Please describe your issue:
Since the update to ChromeOS 89 stable two finger scroll on touchpad and mouse scroll no longer working

#### If known, describe the steps to reproduce the issue:
Open any window inside xfce and try scrolling with touchpad or with mouse and it fails to work

**Comment by rjhorniii** [comment]
It might not be related to ChromeOS update.  It could be related to an xfce update, or something else.  I just recently started seeing the same thing.  My edit-chroot output is

sudo edit-chroot -ll bionic
Password: 
name: bionic
Enter encryption passphrase for bionic: 
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/bionic...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce,xorg,x11,extension,keyboard,core,audio,cli-extra
host: version 13597.105.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-20591-gf51c8e8d99f21 #1 SMP PREEMPT Sun Feb 28 21:06:50 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...

**Comment by chitzinwin** [comment]
Same here after updating ChromeOS to Version 89.0.4389.82.
 I tried with both bionic and focal. I am aware focal is unsupported but tried to see any different. Problem persists.

name: ubuntu
encrypted: no
Entering /home/chronos/user/sd/chroot/chroots/ubuntu...
crouton: version 1-20200724165050~master:08dac970
release: focal
architecture: amd64
xmethod: xorg
targets: xorg,keyboard,xiwi,touch,xfce,x11,core,extension,cli-extra
host: version 13729.45.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.166-10982-g7b4adc7ea88e #1 SMP PREEMPT Fri Mar 5 05:35:32 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /home/chronos/user/sd/chroot/chroots/ubuntu as another instance is using it.

**Comment by gumgl** [comment]
Same here after updating to ChromeOS Version 89.0.4389.95 (Official Build) (64-bit).
Using the `xorg` target, scrolling still works. In `xiwi`, I see scroll events in `libinput-debug-events` but no scrolling happens. Tested with touchpad only. Same issue with xenial since the Chrome OS update.

```
name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
WARNING: Unable to register core dump handler.
crouton: version 1-20200724165050~master:08dac970
release: focal
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi,e17,gtk-extra,touch
host: version 13729.56.0 (Official Build) stable-channel cave 
kernel: Linux localhost 3.18.0-20616-g64ade1135b48e #1 SMP PREEMPT Mon Mar 15 21:11:18 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/focal...
```

**Comment by rjhorniii** [comment]
Looks like 89.0.4389.95 update has fixed the issue.  Two finger scroll is working after latest update.

**Comment by jcv969** [comment]
> Looks like 89.0.4389.95 update has fixed the issue. Two finger scroll is working after latest update.

Same here, the latest ChromeOS update has fixed the issue

**Comment by chitzinwin** [comment]
Confirmed Version 89.0.4389.95 has fixed the issue. thx

**Comment by scku208** [comment]
> Looks like 89.0.4389.95 update has fixed the issue. Two finger scroll is working after latest update.

Same here, thanks for the info. :)

**Comment by leonbollerup** [comment]
Seems its back in 90.. it seems

**Comment by jazzgroove** [comment]
Also can confirm 2-finger scrolling is broken in Version 91.0.4459.0

**Comment by chitzinwin** [comment]
still broke in Version 91.0.4472.147 (Official Build) (64-bit)

**Comment by rjhorniii** [comment]
Update:  This is xiwi related too.  If I start crouton using xorg, it works.  If I start using xiwi, the bug is still there.

**Comment by gumgl** [comment]
Broken again for me on 91.0.4472.167

**Comment by maxsalibe** [comment]
> Update: This is xiwi related too. If I start crouton using xorg, it works. If I start using xiwi, the bug is still there.

Hi! Could you please tell how to start crouton using xorg when it's already installed? I mean, the way I know to launch it is to write the following in the shell: `sudo startunity.` Should I pass something else to enable mouse scrolling?

**Comment by DennisLfromGA** [comment]
@maxsalibe,

If you have both 'xorg' & 'xiwi' xmethods installed you can specify which to use with your desktop on the command line with the '`-X`' option. See some examples below:
- `sudo startlxde -X xorg` (for xorg) 
- `sudo startlxde -X xiwi` (for xiwi in a window - default) 
- `sudo startlxde -X xiwi-fullscreen` (for xiwi fullscreen)
- `sudo startlxde -X xiwi-tab` (for xiwi in a tab)

Substitute `startlxde` with your desktop launcher, i.e `startxfce`, etc.

*Hope this helps,*
-**DennisLfromGA**

**Comment by maxsalibe** [comment]
X in uppercase?

**Comment by DennisLfromGA** [comment]
@maxsalibe,

Yes, Linux is case sensitive so the 'X' needs to be in uppercase.
Hint: enter `sudo startxfce4 -h` to see all the options available.

*Hope this helps,*
-**DennisLfromGA**

**Comment by maxsalibe** [comment]
Thanks! And is there a way to terminate the Linux desktop, as well as is
there a command to start it? I ask that because I use the Crouton
Integration extension and there are open desktops ... but I don't know how
to close them! And it worries me, because while they are open, I have some
problems in Chrome, such as bad mouse pointer behavior.

**Comment by maxsalibe** [comment]
xorg worked for me! I mean, it enabled mouse scrolling! Thank you! But, is
there any means to open xorg in a tab? I tried sudo startunity -X xorg-tab
but it opened on a separate desktop, not allowing to minimize nor opening
it in a tab...

**Comment by DennisLfromGA** [comment]
@maxsalibe,

> And is there a way to terminate the Linux desktop, as well as is
there a command to start it?

Most desktops have a 'logoff' / 'logout' option, look for it.
Unless you use the '`-b`' option when you launch the desktop it will b run in the foreground so you should be able to go back to the CrOS shell session where you launched it and press `Ctrl`+`C` to 'kill' the foreground process.
If you want to shutdown the entire chroot enter 'sudo halt` in the chroot.

> But, is there any means to open xorg in a tab?

Nope.
But, you can switch to CrOS using the key-combo <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F2/F3</kbd> or in a chroot command-line with: `croutoncycle cros`
And then you can switch back into the chroot with the above key-combo or use the 'crouton integration' extension to switch back into the chroot.

*Hope this helps,*
-**DennisLfromGA**
