### ISSUE TITLE
Installed crouton on SD card and hard-rebooted Chromebook

### ISSUE THREAD

**Issue by rohan-techie** [dnschneid/crouton#4438]
```
When I type 'sudo edit-chroot -all':
`sudo: edit-chroot: command not found`
```
I was running Ubuntu 16.04 Gnome 3.18 on a Lenovo N21 Chromebook, and my computer was becoming increasingly slow. I had not been running my chroot in the internal storage, but rather in an external SD card of 32GB, due to the limited storage on my Chromebook (16GB). After rebooting my computer, and then putting it back into dev mode, I can't startgnome (because it is not installed onto my system, but the chroot exists in my SD Card with all targets and files). What can I do to solve this?

**Comment by DennisLfromGA** [comment]
You can run the `edit-chroot` command giving it the full path to your external device's `PREFIX/bin/` folder or 
you can `cd` to your external device's `PREFIX/bin/` folder and run it from there or 
you can install the crouton scripts with croutons `-b` option, see below:
```
-b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
```
If you decide to install the scripts make sure you also use the `-p` option to specify your external device's PREFIX folder, see below:
```
-p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
```

*Hope this helps,*
-**DennisLfromGA**

**Comment by rohan-techie** [comment]
Thank you. It worked.
