### ISSUE TITLE
crouton won't delete

### ISSUE THREAD

**Issue by spityou** [dnschneid/crouton#4443]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
sudo: edit-chroot: command not found
```

#### Please describe your issue:
crouton won't delete i tried most of the delete commands and it just keeps saying: `sudo: delete-chroot: command not found`

#### If known, describe the steps to reproduce the issue:
what i was doing before this happed was i was trying to install vmware to boot windows and download on a copy on windows for my pc that i just built and i downloaded vmware but it needed some dependencies  but i need to plug in the computer so i went to go get the charger and the computer turned off while i was gone so when i turned on the computer while i was still booted into linux i put in the password and i was going to do the last command to install the dependencies and i switched back over to chrome because i was watching a youtube video on how to install vmware and when i tried to switch back over linux powered down so i just turned on linux again but reset everything too but when i opened terminal to put in the command i switched back over again and i tried to switch back over and it turned off again so i started it again then i opened terminal put in some on the command switched back over and it turned over again ect i did this for a minute until i wrote it down on a piece of paper and turned on linux again and put in the command and then when i put in the command the command didn't work for some reason and then i just switched over back and forth and it kept turning off and now i just want to reinstall it and now when i try to reinstall it i tried the delete command and it deleted it but it didn't delete all of it and now i can't start linux and i can't reinstall linux because i get this: 

```
/usr/local/chroots/xenial already has stuff in it!
Either delete it, specify a different name (-n), or specify -u to update it.    even though i put in the delete command please help
```

**Comment by DennisLfromGA** [comment]
The `delete-chroot` command should be under `/usr/local/bin/` *and* in your PATH but if not try:
> `sudo /usr/local/bin/delete-chroot xenial`

If *that* doesn't work then try the below method:
> `sudo /usr/local/bin/edit-chroot -d xenial`

Also, if 'xorg' is giving you problems when installing apps you can add both xorg & xiwi targets to your chroot and use xiwi to switch out of your chroot easier. You can also add a browser *in* your chroot and use it for searches & reference.

*Hope this helps,*
-**DennisLfromGA**

**Comment by spityou** [comment]
> The `delete-chroot` command should be under `/usr/local/bin/` _and_ in your PATH but if not try:
> 
> > `sudo /usr/local/bin/delete-chroot xenial`
> 
> If _that_ doesn't work then try the below method:
> 
> > `sudo /usr/local/bin/edit-chroot -d xenial`
> 
> Also, if 'xorg' is giving you problems when installing apps you can add both xorg & xiwi targets to your chroot and use xiwi to switch out of your chroot easier. You can also add a browser _in_ your chroot and use it for searches & reference.
> 
> _Hope this helps,_
> -**DennisLfromGA**

hello both of those commands did not work and i was not using xfce linux i was using unity linux and this is what i got from both of the commands: 

sudo: /usr/local/bin/delete-chroot: command not found

sudo: /usr/local/bin/edit-chroot: command not found

**Comment by riverbob9101** [comment]
I may be misunderstanding you (or fundamentally wrong since I'm new to linux), but it sounds like you're entering the edit-chroot command on the linux side?  For me I can't use commands like edit-chroot from within my chroot.  I get the same command not found response, but if you open a terminal and enter a shell in the chrome os side the chroot managment commands like edit-chroot work properly.

**Comment by spityou** [comment]
> I may be misunderstanding you (or fundamentally wrong since I'm new to linux), but it sounds like you're entering the edit-chroot command on the linux side? For me I can't use commands like edit-chroot from within my chroot. I get the same command not found response, but if you open a terminal and enter a shell in the chrome os side the chroot managment commands like edit-chroot work properly.

i have been entering the commands through crosh but before i enter the commands i type shell in crosh then enter the commmands

**Comment by spityou** [comment]
i may just have to wipe my chromebook because this have happened to me multiple times and what i did to fix it was just to wipe it i just want to know if there is a way to fix it without wiping everything

**Comment by riverbob9101** [comment]
Ah, in that case I don't know what the problem could be, sorry.

**Comment by DennisLfromGA** [comment]
@spityou 
> i just want to know if there is a way to fix it without wiping everything

If you are still getting 'command not found' errors even after entering the full path to the scripts then it appears that the scripts were somehow removed. You can reinstall the needed scripts for the chroot(s) you have installed (in the default location) with the command listed below:
- `sudo crouton -b`

Once they're reinstalled you should be able to delete your chroot with:
- `sudo delete-chroot xenial`

If you still get errors then, assuming you installed your chroot(s) in the PREFIX location (`/usr/local/chroots`) then this should remove them manually:

- `sudo rm -rf /usr/local/chroots/*`

Note that the above can be dangerous if you type in the wrong location so please be sure to enter it correctly.

If that should fail for any reason then you can always powerwash your device as a last resort.

*Hope this helps,*
-**DennisLfromGA**
