### ISSUE TITLE
Buster installing error UID 1000 not found in buster

### ISSUE THREAD

**Issue by JRIsP-dunno-much-about-coding** [dnschneid/crouton#4444]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20200724165050~master:08dac970
release: buster
architecture: i386
xmethod: xorg
targets: xfce
host: version 9334.72.0 (Official Build) stable-channel x86-alex_he 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 17 17:49:46 PDT 2017 i686 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...

```

#### Please describe your issue:

Hello everyone, I'm currently trying to mount buster in my Samsung Series 5 Notebook (a somewhat old model) using crouton and DE XFCE. Everything so far in the guide has been ok, but once I ran sudo crouton -t xfce -r buster, it began a long process of downloading and installing data... I guess (as my name suggests, I'm new in the programming world. A friend of mine was guiding me throughout the process), and eventually... it fails. It says "UID 1000 not found in buster"

![Screenshot 2021-03-20 at 7 34 44 PM](https://user-images.githubusercontent.com/81054333/111888494-eb60e500-89d4-11eb-83ab-b76b563e60d1.png)

Is there a way to fix this problem and continue with the install process? I've already invested time and money (via download sizes, my connection is paid per mb) in this and I don't want to lose all process.

I tried updating crouton with sudo crouton -u but this is what happens:

Downloading latest crouton installer...
######################################################################## 100.0%
/usr/local/chroots/xenial does not exist; cannot update.
Valid chroots:
buster

Please help me, guys.

**Comment by annoyedcat5971** [comment]
idk i am dealing with basicly the sam sh*t just with a few minor differeces

**Comment by annoyedcat5971** [comment]
differences

**Comment by annoyedcat5971** [comment]
if i knew how to help I would... :(
![Screenshot 2021-03-20 9 20 50 PM](https://user-images.githubusercontent.com/81060307/111891578-39202200-89c2-11eb-9765-718e9c11adc2.png)

**Comment by DennisLfromGA** [comment]
You might try getting into your chroot as root and then updating and/or fixing the package errors.
- Use: `sudo enter-chroot -u root -n [chrootname]`

*Hope this helps,*
-**DennisLfromGA**

**Comment by JRIsP-dunno-much-about-coding** [comment]
Okay, I did as you told and this happened:
![Screenshot 2021-03-21 at 10 27 56 AM](https://user-images.githubusercontent.com/81054333/111908579-ab8c1300-8a51-11eb-9299-c7ab1bd85384.png)

I tried apt-get update, but I don't really know if this worked or what to do now

**Comment by DennisLfromGA** [comment]
- How to Fix Broken Packages in Linux - Make Tech Easier
https://www.maketecheasier.com/fix-broken-packages-ubuntu/

**Comment by JRIsP-dunno-much-about-coding** [comment]
Ok I did that and some install process began. I THINK it worked, but I'll tell after if finished or something occurs.

**Comment by JRIsP-dunno-much-about-coding** [comment]
Hey guys, I THINK it worked so I'm closing BUT I have a very different kind of problem now: the debian downloads burned my network credit so I have to wait til next month to try finishing the installation.... IF something bad occurs then, I'll reopen the thread. Thank you a lot!!!

**Comment by JRIsP-dunno-much-about-coding** [comment]
New update: I could find a way to reload my credit early, and I followed the steps above but after I write "sudo crouton -n buster -u" I get the following error: "Assertion '(size_t) r < n' failed at ../src/basic/random-util.c:147, function genuine_random_bytes(). Aborting."

![Screenshot 2021-03-22 at 12 18 40 PM](https://user-images.githubusercontent.com/81054333/112022808-8919f880-8b2a-11eb-8289-2a2aa0acabda.png)

**Comment by JRIsP-dunno-much-about-coding** [comment]
So... I reopen the issue :c

**Comment by JRIsP-dunno-much-about-coding** [comment]
So... I reopen the issue :c

**Comment by JRIsP-dunno-much-about-coding** [comment]
Eh @DennisLfromGA
help?

**Comment by JRIsP-dunno-much-about-coding** [comment]
Ok, I decided it's going to be best for me (reading similar issues) to delete buster and start over. It'll save me time and headaches (I hope). This time I'll try xenial w/XFCE. Wish me luck, guys

**Comment by DennisLfromGA** [comment]
@JRIsP-dunno-much-about-coding 

If you have decided to move on with other distros you can close this again - or ask and I will.

**Comment by JRIsP-dunno-much-about-coding** [comment]
DONE, GUYS! Xenial works PERFECT. Closing now, definitely. Still thanks for your help!

**Comment by JRIsP-dunno-much-about-coding** [comment]
Okay, it doesn't close o.o
