### ISSUE TITLE
Bootstrap failure dpkg not found in chrome shell

### ISSUE THREAD

**Issue by axzxc99** [dnschneid/crouton#4446]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
Creating hwaudio group with GID 18...
su: Critical error - immediate abort
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
#### Please describe your issue:
I try to install any target and I keep getting the same error. 

W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.31-9_amd64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.31-9_amd64.deb is at fault)
Failed to complete chroot setup.

I've got no idea on what to do
#### If known, describe the steps to reproduce the issue:
sudo crouton -r kali-rolling -t xfce,extension,audio,chromium

**Comment by DennisLfromGA** [comment]
There is a duplicate issue and a relevantcomment linked below:
- https://github.com/dnschneid/crouton/discussions/4441#discussioncomment-505294

I'll close this issue so it can be tracked in one place, at the link above.
