### ISSUE TITLE
dpkg wraning... cant start crouton

### ISSUE THREAD

**Issue by lxlrip** [dnschneid/crouton#4451]
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: error: 1 expected program not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
Failed to complete chroot setup.

**Comment by DennisLfromGA** [comment]
For context, please show us the output of `sudo edit-chroot -all` and the command you are trying to run.
It's very hard to tell what might be causing the error without more detail.

*Hope this helps,*
-**DennisLfromGA**
