### ISSUE TITLE
Unable to install kde desktop in 

### ISSUE THREAD

**Issue by BruhDudeWew** [dnschneid/crouton#4453]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: bullseye
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bullseye...
crouton: version 1-20200724165050~master:08dac970
release: bullseye
architecture: amd64
xmethod: xorg
targets: kde-desktop,xorg,xiwi,x11,core,audio,cli-extra
host: version 13729.56.0 (Official Build) stable-channel nami 
kernel: Linux localhost 5.10.26-brunch-sebanc #1 SMP PREEMPT Sat Apr 3 07:47:44 CEST 2021 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bullseye...
#### Please describe your issue:
Cannot finalize kde-desktop installation process. It keep complaining kde-runtime not found despite it got removed from bullseye repo and kde no longer needed it.

#### If known, describe the steps to reproduce the issue:
Just "sudo crouton -r bullseye -t kde-desktop -u"

**Comment by DennisLfromGA** [comment]
Yes, it looks like kde-runtime package is installed as part of the [kde target](https://github.com/dnschneid/crouton/blob/master/targets/kde#L12).
I suppose it will need to be excluded for bullseye and possibly other distros.

A pull request will have to be submitted with this change I suppose.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Just-Randomly-Me** [comment]
yes kde doesnt work on mine either
