### ISSUE TITLE
Unity - Saucy - Taskbar not showing icons like battery status, login/out

### ISSUE THREAD

**Issue by fluxlife** [dnschneid/crouton#446]
Hardware: Acer C720
Unity
Saucy

I have tried to fresh installs and the task bar icons that usually shows the network status, email, battery, and login/logout are not there.  Furthermore the global App Menu doesn't seem to be working.  There is a bar at the top of the screen but it's not functioning the way it does in a native install.  Even after installing ubuntu-desktop via apt-get, I am still not getting the right setup.

**Comment by Fleepy** [comment]
It doesn't seem to me like this has been fixed. Im still having the same issue, and im on the same chromebook as the guy who created this post.
