### ISSUE TITLE
dbus-launch problem kali linux

### ISSUE THREAD

**Issue by PumadNeedsHelp** [dnschneid/crouton#4461]
```
dbus-launch not found, the desktop will not work properly!
```

####
 I tried running `sudo startxfce4` on crosh with crouton (kali linux), It launched and then a message came up to my screen saying "Failed to execute child process "dbus-launch" (No such file or directory) "
Is their a way to get dbus-launch, I'm new so I need help

####

**Comment by daboisadasd** [comment]
The solution that i have found to this issue is to enter the chroot and install dbus-launch

sudo enter-chroot

sudo apt install dbus-x11

startxfce4

This is my first time ever trying to solve a problem so sorry for anything I did wrong.

**Comment by PumadNeedsHelp** [comment]
Yup it works

**Comment by 526119512-10-1689189** [comment]
It has worked for me. Thanks!!

**Comment by om-73** [comment]
It is for rooted

**Comment by Ronin375** [comment]
worked perfectly for me. thank you!

**Comment by ermax775** [comment]
It really helps. Thanks, bruh ! 🙏🙏
