### ISSUE TITLE
failed to complete chroot setup

### ISSUE THREAD

**Issue by ryslen2** [dnschneid/crouton#4465]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
Im not sure what im doing besides trying to install linux on my chromebook, it's had this error almost 5 times and I've tried restarting
![Screenshot 2021-05-01 12 50 38 AM](https://user-images.githubusercontent.com/83489180/116772993-565ffb80-aa18-11eb-889e-f6474e219ab0.png)

**Comment by DennisLfromGA** [comment]
This is a known issue and currently unresolved, please see the below comment for more details -

#4441 (comment)   

I'll close this issue so we can track it at the link above.

Hope this helps,
DennisLfromGA
