### ISSUE TITLE
Can't install focal - libcras/cras_client.h:1924:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]

### ISSUE THREAD

**Issue by leonbollerup** [dnschneid/crouton#4466]
Hi,

Same issue as here : https://github.com/dnschneid/crouton/issues/4450

Anyone have a fix for it ?

**Comment by DennisLfromGA** [comment]
Yes & no.  

Yes, this is a dup of issue:
- Linux not installing saying something like CRAS ·
Issue #4450 · dnschneid/crouton   

No, it does not have a fix - yet.

No need to open another issue.
Closing, please track this issue at the link above.

-DennisLfromGA
