### ISSUE TITLE
Help with Crouton

### ISSUE THREAD

**Issue by jmp2140** [dnschneid/crouton#4467]
```
Please paste the output of the I following command here: sudo edit-chroot -all
```

chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 12105.100.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Jul 14 00:09:57 PDT 2019 armv7l armv7l armv7l GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I’m trying to use Crouton to get Linux on my 2015 Samsung Chromebook (model XE303C12-A01US). Entering developer mode goes fine, and it seems like installing crouton goes fine but when I get to running “sudo startfxce4” it doesn’t work. I’ve attached screenshots of what I’m seeing. 

If anyone could help I’d much appreciate it. 

![35FCE7DF-EB2B-4786-BD4D-532A96EFE882](https://user-images.githubusercontent.com/83596342/116892766-ce374d00-abf5-11eb-9981-7e673e186df0.png)
![21EA1AC3-5BAD-4431-8A7A-A49F5C799D9E](https://user-images.githubusercontent.com/83596342/116892771-cecfe380-abf5-11eb-92b0-0ad8d553be5c.png)

**Comment by BobUnderwoodSF** [comment]
Try installing Focal Fossa (Ubuntu 20.04 LTS) instead of Xenial (the default).
First, remove all existing chroots.

sudo delete-chroot *

Then install Focal Fossa.

sudo crouton -r focal -t xfce,audio

**Comment by MrHallway0** [comment]
If Focal Fossa fails I *always* suggest using `sid` with `xfce`.

**Comment by BobUnderwoodSF** [comment]
When I first tried to use Crouton on my Samsung XE503C32 both xenial and sid failed (with xfce) - focal succeeded and is working well.

    On Friday, May 7, 2021, 12:12:25 PM PDT, Mr. Hallway ***@***.***> wrote:  
 
 


If Focal Fossa fails I always suggest using sid with xfce.

**Comment by DennisLfromGA** [comment]
@jmp2140,

Please try the latest release of crouton and let us know if it doesn't fix the failure.
