### ISSUE TITLE
Can't install crouton

### ISSUE THREAD

**Issue by SlinkySausage** [dnschneid/crouton#4468]
```
Please paste the output of the following command here: sudo edit-chroot -all 
``` install: cannot stat '/usr/local/bin': No such file or directory

#### Please describe your issue:
Attempting to use (below) to install crouton, get above message please help, very new to this

sudo install -DT /usr/local/bin -m 755 ~/Downlaods/crouton -

#### If known, describe the steps to reproduce the issue:

**Comment by DennisLfromGA** [comment]
Linux is very picky about case sensitivity, you need to use a lowercase 't' with that `install` command.
```
       -t, --target-directory=DIRECTORY
              copy all SOURCE arguments into DIRECTORY

       -T, --no-target-directory
              treat DEST as a normal file
```
Also, you misspelled the Downloads directory so it cannot find the `crouton` file.

Copy-n-paste this command and see if it works better:
- `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`

For more details and examples see -
- https://github.com/dnschneid/crouton#usage

*Hope this helps,*
-**DennisLfromGA**

**Comment by afx8064** [comment]
similar issue, "install: cannot stat '/home/user/Downloads/crouton': No such file or directory"
my command seems to be perfectly fine
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
(new to linux)
