### ISSUE TITLE
Failed to complete chroot setup, failure trying to run dpkg

### ISSUE THREAD

**Issue by svioletg** [dnschneid/crouton#4469]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
I encountered a program I wanted to try but it was only available on Linux. Remembered I had an ubuntu chroot on my old chromebook, got it out and started up said chroot (it's been at least a year since I logged into said ubuntu instance, if that indicates any update might have been the problem or something...) only to find that I couldn't use barely any apt-get commands because of some dpkg error. After getting nowhere I decided to just reinstall a chroot from scratch, this time with unity since I just find it easier to use. Removed the old one entirely, seemed clean, ran the new steps to install it, and ran `sudo crouton -e -t unity` only to wait 5 minutes and be greeted with the following at the end:
```
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb is at fault)
Failed to complete chroot setup.
```
...before the command halted. That package is the same one I kept getting errors about in the xfce instance, is my chromebook just messed up somehow? I don't store any files on this chromebook so I'm fine having to powerwash it if necessary, but I'd really like to see if there's a less cumbersome way to deal with this.

#### If known, describe the steps to reproduce the issue:
I followed the README up until the `sudo crouton -t xfce` step. Here I ran `sudo crouton -e -t unity` since I wanted it encrypted, and because I wanted to install unity ubuntu.

Full output of `sudo crouton -e -t unity`: https://pastebin.com/hXw3rZFC

**Comment by DennisLfromGA** [comment]
This is a known issue and currently unresolved, please see the below comment for more details -

#4441 (comment)

I'll close this issue so we can track it at the link above.

*Hope this helps,*
-**DennisLfromGA**
