### ISSUE TITLE
Error when installing crouton 

### ISSUE THREAD

**Issue by Codeer12** [dnschneid/crouton#4470]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xiwi,extension
host: version 13904.16.0 (Official Build) beta-channel octopus 
kernel: Linux localhost 4.14.228-17533-gcb705c2f30e9 #1 SMP PREEMPT Mon Apr 26 22:01:05 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting  /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
Whenever I try to install crouton, it gives me this error:
libcras/cras_client.h:2000:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
I've tried resetting this computer at least 4 times. Each time I reset, I remember to try the crouton install again, and time and time again, it gives me the same issue

#### If known, describe the steps to reproduce the issue:
try installing crouton on the computer just doesn't work for me

**Comment by DennisLfromGA** [comment]
This is a known issue, please see the below issue and track it there -   
- Linux not installing saying something like CRAS #4450

*Hope this helps,*
-**DennisLfromGA**
