### ISSUE TITLE
Terrible glitches with XFCE windows.

### ISSUE THREAD

**Issue by synesthesium** [dnschneid/crouton#4471]
```
Please paste the output of the following command here: sudo edit-chroot -all

chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xiwi
targets: keyboard,xiwi,xorg,xfce-desktop,touch
host: version 13816.64.0 (Official Build) stable-channel coral 
kernel: Linux localhost 4.4.257-19938-g86d266acc51a #1 SMP PREEMPT Tue Apr 27 20:52:50 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue: Odd glitches on some programs when using XFCE on xorg. I'll be using Firefox as an example (the issue is, however, not limited to Firefox):

Expected results (using xiwi):
Not laggy, no glitches, a pretty good experience.
![expected](https://user-images.githubusercontent.com/26376886/117207660-70e7fb00-adb1-11eb-81bf-dc07c78a0806.png)

Actual results (using xorg):
Horribly laggy, a transparent line that moves around the window every half a second, unusable.
![actual](https://user-images.githubusercontent.com/26376886/117207938-c7edd000-adb1-11eb-8b35-dedacb45c363.png)

#### If known, describe the steps to reproduce the issue:
Install xenial with XFCE and try opening Firefox.

**Comment by pcwalden** [comment]
Just upgraded Firefox  to 88.0 on my existing xenial and have the same issue. Only seems to appear on Firefox though. I also use Seamonkey, but it shows no symptoms.

 Were you able to solve it?

It is very annoying and interferes with Firefox usability.
