### ISSUE TITLE
Unity will not work with Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by ChrisGamez10** [dnschneid/crouton#4478]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /media/removable/USB Drive/chroots/bionic...
crouton: version 1-20200724165050~master:08dac970
release: bionic
architecture: amd64
xmethod: xorg
targets: unity,keyboard,chrome,audio,x11,core,gtk-extra,cli-extra,extension
host: version 13729.84.0 (Official Build) stable-channel celes 
kernel: Linux localhost 4.19.166-10987-g59fad5daf7a8 #1 SMP PREEMPT Tue Apr 13 12:57:15 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/USB Drive/chroots/bionic...
#### Please describe your issue:
Launching Unity using sudo startunity does not start Unity, but starts GNOME instead. 

#### If known, describe the steps to reproduce the issue:
Make a Ubuntu 18.04 chroot with Unity and then sudo startunity

**Comment by DennisLfromGA** [comment]
@ChrisGamez10,

> Launching Unity using sudo startunity does not start Unity, but starts GNOME instead.

Are you sure there's an issue here?

The ['unity' target](https://github.com/dnschneid/crouton/blob/master/targets/unity#L24) includes 'gnome-session' and 'unity' is just a gnome shell, see below:
> Unity is a graphical shell for the GNOME desktop environment originally developed by Canonical

I don't use unity so I can't really repro your issue, sorry. Maybe others that use it will chime in.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. No response or follow-up (needed) at this time.

-**DennisLfromGA**
