### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by EthanTwu** [dnschneid/crouton#4484]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
sudo: edit-chroot: command not found

#### Please describe your issue:
I have been trying to download crouton for like 2 hours but I have no clue what I am doing. I try to follow the github usage and examples section but I keep getting issues like "Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount ERROR" and "mount: /home/chronos/user: mount point not mounted or bad option". I was getting really annoyed since nothing on the internet fixed my problem. I don't know what I did, but now the commands don't work(it is 12 a.m. and I am still trying to download crouton). Look at the screen shot I provided to have some understanding. If you have any questions and have no clue what I am saying, please leave a comment so I can clarify my question a little more.

![Screenshot 2021-05-16 12 15 48 AM](https://user-images.githubusercontent.com/30132410/118385321-e20e8600-b5db-11eb-84ca-085c0c8fa917.png)

#### If known, describe the steps to reproduce the issue:
I have no clue what I did.

**Comment by DennisLfromGA** [comment]
Try running this: 
- `sudo crouton -b`   

Then this and show us the output: 
- `sudo edit-chroot -all`   

*Hope this helps,*
-**DennisLfromGA**

**Comment by EthanTwu** [comment]
> Try running this:
> 
> * `sudo crouton -b`
> 
> Then this and show us the output:
> 
> * `sudo edit-chroot -all`
> 
> _Hope this helps,_
> -**DennisLfromGA**

Hi, I fixed it. I got out of developer mode and went back in(this powerwashes my computer). But now I am faced with another error. (Why is crouton so buggy lol) Check the recent issue I posted. I really want some help.

**Comment by EthanTwu** [comment]
> Try running this:
> 
> * `sudo crouton -b`
> 
> Then this and show us the output:
> 
> * `sudo edit-chroot -all`
> 
> _Hope this helps,_
> -**DennisLfromGA**

This is the new output:
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

Did it fix anything?

**Comment by DennisLfromGA** [comment]
The message:
> UID 1000 not found in xenial   

means that the chroot installation did not complete.

Try running this and see if it completes:
- `sudo crouton -n xenial -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by EthanTwu** [comment]
> The message:
> 
> > UID 1000 not found in xenial
> 
> means that the chroot installation did not complete.
> 
> Try running this and see if it completes:
> 
> * `sudo crouton -n xenial -u`
> 
> _Hope this helps,_
> -**DennisLfromGA**

Thanks for the continous help, but I am still receiving the same error message:

**chronos@localhost / $ sudo crouton -n xenial -u**
Downloading latest crouton installer...
###################################################################### 100.0%
/usr/local/chroots/xenial already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
**chronos@localhost / $ sudo startxfce4**
Entering /mnt/stateful_partition/crouton/chroots/xenial...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
Creating hwaudio group with GID 18...
su: pam_start: error 26
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
_UID 1000 not found in xenial_
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

Any other suggestions?

**Comment by DennisLfromGA** [comment]
Without the full output of `sudo edit-chroot -all` we can't tell much about your chroot, device, channel, version, etc., this makes helping you a challenge.

What channel are you using? 
This issue has been reported when using anything other than the stable channel so that may be your problem.

*Hope this helps,*
-**DennisLfromGA**

**Comment by EthanTwu** [comment]
> Without the full output of `sudo edit-chroot -all` we can't tell much about your chroot, device, channel, version, etc., this makes helping you a challenge.
> 
> What channel are you using?
> This issue has been reported when using anything other than the stable channel so that may be your problem.
> 
> _Hope this helps,_
> -**DennisLfromGA**

Sorry, I'll put the output to the command every time now. Here is the output of sudo edit-chroot -all:

**chronos@localhost / $ sudo edit-chroot -all**
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...


I am also on stable channel.

**Comment by DennisLfromGA** [comment]
Yep, sorry, I meant the full output wasn't displayed because the chroot didn't finish installing, nothing you could do about that.

If you are already in the stable channel, I'm not sure what the problem is, sorry.

Maybe someone else will be able to help out.

-**DennisLfromGA**

**Comment by EthanTwu** [comment]
> Yep, sorry, I meant the full output wasn't displayed because the chroot didn't finish installing, nothing you could do about that.
> 
> If you are already in the stable channel, I'm not sure what the problem is, sorry.
> 
> Maybe someone else will be able to help out.
> 
> -**DennisLfromGA**

Oh, ok. I am a little sad.. Any other way to get Linux(other than Linux beta)?

**Comment by DennisLfromGA** [comment]
You could try a different distro than xenial possibly.
Maybe try: 
- `sudo crouton -r bionic -t xfce`

You can substitute 'bionic' above with 'focal', etc. to see if any of them will install successfully.

*Hope this helps,*
-**DennisLfromGA**

**Comment by BobUnderwoodSF** [comment]
If you have a supported Chromebook you can try chrx.

https://github.com/reynhout/chrx

**Comment by BobUnderwoodSF** [comment]
An error is occurring at the same spot in the script each time - "Creating hwaudio group with GID 18...". Other users have reported the same problem recently.

You could wait to see if anyone fixes (hacks) the Crouton script; or,
revert your version of Chrome OS - https://www.reddit.com/r/chromeos/comments/emle5t/is_it_possible_to_roll_back_chrome_os_updates_on/    ; or,
enable Linux on your Chromebook (which gives you Debian Buster) then install a desktop environment like XFCE

**Comment by dnschneid** [comment]
Please try the latest release of crouton and re-open if it doesn't fix the failure.

**Comment by BobUnderwoodSF** [comment]
I'd be happy to test it but my only Chromebook is an old 32-bit ARM rig that stopped getting updates at v75.

    On Friday, July 9, 2021, 5:14:40 PM PDT, David Schneider ***@***.***> wrote:  
 
 


Please try the latest release of crouton and re-open if it doesn't fix the failure.
