### ISSUE TITLE
cant get past this bit

### ISSUE THREAD

**Issue by jordaaan21** [dnschneid/crouton#4490]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

If you want to customize the look/behavior, you can use the options page.
Load it by using the Ctrl-Shift-P keyboard shortcut.

crosh> shell
chronos@localhost / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
Password: 
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d] y
Preparing chroot environment...
Creating hwaudio group with GID 18...
su: pam_start: error 26
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost / $

**Comment by EthanTwu** [comment]
I have the same error as jordaaan21 that says, "su: pam_start: error 26. The chroot setup script may be broken. Your chroot is not fully configured." 

Anyone got any ideas?

**Comment by TeijoR** [comment]
I got a similar issue, this is now 4th time in a row, and clearly, I don't get figured out what is the matter of this error.  If there is someone who got a solution to this problem.  I would be happy to hear that! 
**su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...**

**Comment by dnschneid** [comment]
Please try the latest release of crouton and re-open if it doesn't fix the failure.
