### ISSUE TITLE
Really low fps on Minecraft

### ISSUE THREAD

**Issue by maybejadon** [dnschneid/crouton#4491]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13816.80.0 (Official Build) stable-channel banon 
kernel: Linux localhost 4.19.176-28773-g91924d8d61fa #1 SMP PREEMPT Mon May 10 21:14:15 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue: 
I have been able to get Minecraft to open and run but I get a maximum of 6 fps. I don't think that this is an issue with my computer because I've seen other people with chrombooks that have similar specs to mine be able to pull of 30-40 fps. 
Here are links tomimages of the F3 tab in Minecraft if it'll help: https://imgur.com/d1giGmU https://imgur.com/q2Rtmn3

#### If known, describe the steps to reproduce the issue: 
Open a world in Minecraft

**Comment by QwertzyIsCool** [comment]
Try to Disable hardware acceleration and use Fabric with Sodium, that fixes the problem

**Comment by MrHallway0** [comment]
Chromebooks aren't intended to be gaming machines. Even with the lowest settings on a pretty good 2018 Chromebook I was able to get about 10-20 FPS on the lowest settings. You could try off loading it to a server, I have a 1.12 one but I can set up a 1.8 server if you want, as they do help by off loading *some* work to the server instead of the device but I still wouldn't expect to get crazy good FPS on a Chromebook, and that goes for any game except temple run.

**Comment by QwertzyIsCool** [comment]
> Chromebooks aren't intended to be gaming machines. Even with the lowest settings on a pretty good 2018 Chromebook I was able to get about 10-20 FPS on the lowest settings. You could try off loading it to a server, I have a 1.12 one but I can set up a 1.8 server if you want, as they do help by off loading _some_ work to the server instead of the device but I still wouldn't expect to get crazy good FPS on a Chromebook, and that goes for any game except temple run.

My chromebook runs minecraft at around 100 FPS with Sodium and Lithium

**Comment by MrHallway0** [comment]
@QwertzyIsCool 
Yes, I understand that there are Chromebooks with decent hardware that can play games at high FPS. Although a user shouldn't expect that out of a device with [these](https://imgur.com/q2Rtmn3) specs, it just isn't reasonable.

**Comment by MrHallway0** [comment]
Possible duplicate of #4190.

**Comment by Dozer257** [comment]
I have an HP Chromebook 11a G6 EE and it handles Minecraft really well as long as something else like discord or chrome is not open, if you have other stuff open I suggest closing it, or try changing video settings.

If none of these work, then can you say what chromebook model you are using (the model is usually listed at the bottom of the chromebook)
