### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by X4X5** [dnschneid/crouton#4492]
```

```

**Comment by DennisLfromGA** [comment]
If you know the name of the chroot then use: 
- `sudo delete-chroot [chrootname]` <-- substitute [chrootname] with the name of your chroot.     

If you do not know the name of your chroot try this:
- `cd /usr/local/chroots && sudo delete-chroot *`

Then just follow the prompts.

*Hope this helps,*
-**DennisLfromGA**

**Comment by X4X5** [comment]
I ended up getting this printout 

Failed to unmount /mnt/stateful_partition/crouton/chroots/xenial. Kill processes? [a/k/y/p/N]

**Comment by MrHallway0** [comment]
Say `y`.

**Comment by X4X5** [comment]
Does it completely remove the crouton?

**Comment by DennisLfromGA** [comment]
Yes, it completely removes the chroot(s).

You got above the error because you were still using it, either answer 'a', 'k', or 'y' or just reboot and try to delete it again.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Closing. Please re-open if this issue is still a concern.
