### ISSUE TITLE
Error trying to install Ubuntu through Crouton

### ISSUE THREAD

**Issue by JimmyGitsErDone** [dnschneid/crouton#4493]
```
Please paste the output of the following command here: sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

####
So, I have though it would be cool to run Ubuntu on my Chromebook, while preserving my ChromeOS. I went into developer mode, and installed Crouton. Unfortunately, when I have tried to install Ubuntu in the ChromeOS developer shell (while following exactly what the instructions say) and when I get to the step with "sudo crouton -t xfce" everything looks fine, until the last few lines. They read:

I: Installing core packages...

W: Failure trying to run: dpkg --force-depends --install /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb

W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb is at fault)

Failed to complete chroot setup.

Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

I do not know why this is happening, and have tried powerwashing, reinstallling, and rebooting. Any tips or information will help! This is on a Chromebox G2
#### 
I download Crouton, do "sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton" and then "sudo crouton -t xfce" and that is where this issue takes place

**Comment by Csigley1** [comment]
I have the same problem

**Comment by Smalls2834** [comment]
I am having this same problem. 
Failure trying to run: dpkg --force-depends --install /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb
See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.23-0ubuntu3_amd64.deb is at fault)
Failed to complete chroot setup

**Comment by JimmyGitsErDone** [comment]
Well, someone on Reddit suggested that I revert back to ChromeOS 89, and I tried it and it worked. So, to fix this just download ChromeOS version 89 ( download from https://cros.tech/ ), use the Chrome Recovery Tool (which will wipe all the data, so make sure to backup and save everything) and then install Crouton. This worked for me, and I hope that it willl work for you.
