### ISSUE TITLE
Xiwi: characters are typed and commands are sent to both ChromeOS and Linux

### ISSUE THREAD

**Issue by Higashifukai** [dnschneid/crouton#4494]
```
chronos@localhost / $ sudo edit-chroot -all
name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20200724165050~master:08dac970
release: buster
architecture: arm64
xmethod: xiwi
targets: xiwi,xfce
host: version 13816.64.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.176-11263-g91924d8d61fa #1 SMP PREEMPT Tue Apr 27 20:19:33 PDT 2021 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...
chronos@localhost / $ 
```

#### Please describe your issue:
When I type something in ChromeOs, the characters are also typed in the opened App in Linux (Buster - XFCE).
(I tried to take a look at Crouton integration extension's Options, but they are greyed out.)

Any idea what can be causint this problem?

**Comment by DennisLfromGA** [comment]
@Higashifukai,

I'm not using the Debian buster release but Ubuntu xenial with the xfce4 desktop target and the xiwi xmethod, however, when I type characters in Chrome OS they do not appear in the xfce terminal or other apps I've tried in the chroot.

What apps are you using in both Chrome OS and the chroot that display the characters you type?

*Hope this helps,*
-**DennisLfromGA**
