### ISSUE TITLE
Error 26 when installing xenial

### ISSUE THREAD

**Issue by WhatIs-GitHub** [dnschneid/crouton#4495]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
Creating hwaudio group with GID 18...
su: pam_start: error 26
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I can't install xenial.

#### If known, describe the steps to reproduce the issue:
I went with the easy way in the read me section step by step.

**Comment by dnschneid** [comment]
Please try the latest release of crouton and re-open if it doesn't fix the failure.
