### ISSUE TITLE
failed to complete chroot setup

### ISSUE THREAD

**Issue by amelxss** [dnschneid/crouton#4498]
Hello I tried to install Crouton but it doesn't work.

[
![Screenshot 2021-05-25 21 09 43](https://user-images.githubusercontent.com/84808138/119555026-aa52cb80-bd9d-11eb-808d-30060d5bbb17.png)

I have an acer chromebook

**Comment by DennisLfromGA** [comment]
Dup of -
- crouton on x86_64 *and* arm, kernel version issue with libc updating in chroot · Issue #4429 · 
dnschneid/crouton https://github.com/dnschneid/crouton/issues/4429

*Please* search for the same or similar issues before posting.

Closing. Please track the above issue for further details.

-**DennisLfromGA**
