### ISSUE TITLE
Linux Mint Cinnamon???

### ISSUE THREAD

**Issue by Just-Randomly-Me** [dnschneid/crouton#4499]
Ummmmm  I'm not sure if this is the right place to put this but
Is it possible for Linux Mint 20.1 Cinnamon to be installed in a Chromebook using crouton?

**Comment by MrHallway0** [comment]
Cinnamon was once an option but was removed, [here](https://github.com/dnschneid/crouton/pull/832) is the pr.

**Comment by Just-Randomly-Me** [comment]
oh ok i'll probably use other distros
