### ISSUE TITLE
No audio device

### ISSUE THREAD

**Issue by mogenson** [dnschneid/crouton#45]
The Ubuntu chroot environment doesn't have any audio devices/can't see Chrome OS's audio device.

Result of "aplay -l" in Ubuntu:
aplay: device_list: 252: no soundcards found...

Result of "aplay -l" in Chrome OS:
***\* List of PLAYBACK Hardware Devices ****
card 0: DAISYI2S [DAISY-I2S], device 0: Playback HiFi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: DAISYI2S [DAISY-I2S], device 1: Capture HiFi-1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

It would be great to use VLC in Crouton to watch video files that Chrome OS doesn't support.. but not without sound!

**Comment by pljones** [comment]
Hi,

"Me too".  /dev/snd/* were hwaudio rather than audio and both aplay -l and arecord -l were not listing devices.  Also, audacity could not open "cras".

Changing group ownership to audio fixed all of that.

I guess a better long term fix is to add users to hwaudio?

-- Peter

**Comment by dnschneid** [comment]
Yeah, if you want to use the hardware audio devices directly, add your user to hwaudio.  By default we play nice with Chromium OS, though.

**Comment by pljones** [comment]
Even with hwaudio, I'd not been able to get recording working except through arecord.  But I have a horrible feeling this was down to pure dumb user error :) -- I hadn't enabled the "Capture" tab in the mixer application (why you have to enable it, I've no idea).  Once done and having enabled the Acer's mic, everything seems to work (though input level controls may be being ignored - still testing that).  I've not yet reverted adding my user to the hwadmin group, either.
