### ISSUE TITLE
Unable to write to `/lib/modules` : Read only filesystem

### ISSUE THREAD

**Issue by UmashankarTriforce** [dnschneid/crouton#4504]
```
name: ubuntu
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/ubuntu...
crouton: version 1-20200724165050~master:08dac970
release: focal
architecture: amd64
xmethod: xorg
targets: xfce-desktop
host: version 13816.82.0 (Official Build) stable-channel rammus 
kernel: Linux localhost 5.10.27-brunch-sebanc #1 SMP PREEMPT Sun May 16 18:29:35 CEST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```
I'm using Crouton using Brunch Framework on my Asus Vivobook S15 X510UN. My laptop comes with NVIDIA MX150 GPU, and I thought it would be really cool to use it on ChromeOS (I'm aware that cros does not have native support for NVIDIA GPUs).

So I installed crouton and got to installing the NVIDIA drivers using `sudo apt-get install nvidia-driver-460` and when the installation gets to the part of writing the NVIDIA kernel modules to `/lib/modules/5.10.27-brunch-sebanc/`, it throws an error saying `cannot perform mkdir: Read only filesystem`.

I can verify that my rootfs is mounted as r+w and I'm able to write to `/lib/modules/` from cros shell, so I'm assuming crostini is mounting the `/lib/modules/` into chroot as read only filesystem. Is there anyway to get around this problem?

**Comment by BobUnderwoodSF** [comment]
Does Focal open into XFCE?

**Comment by UmashankarTriforce** [comment]
Yes it does, infact only xfce4 works with focal for me. Other desktop environment just give a blank screen. 
Anyways, I was able to fix this issue. Just open `enter-chroot` script, and you'll find that `/lib/modules` is mounted as read-only, as I suspected. Just modify that from `ro` to `rw` and you'll be fine!
