### ISSUE TITLE
Failed to complete chroot setup.

### ISSUE THREAD

**Issue by idkwutsmyname** [dnschneid/crouton#4505]
I'm trying to install ubuntu on chrome book but I always get this message:
![image](https://user-images.githubusercontent.com/85312168/120696146-3342c480-c47a-11eb-8709-0e1e38d98e49.png)

I don't know much tech so please explain in a way I can understand.

**Comment by DennisLfromGA** [comment]
Dup of -

- crouton on x86_64 and arm, kernel version issue with libc updating in chroot · Issue #4429 ·
dnschneid/crouton #4429  

Please search for the same or similar issues before posting.

Closing. Please track the above issue for further details.

-DennisLfromGA
