### ISSUE TITLE
Unable to compile CRAS

### ISSUE THREAD

**Issue by UmashankarTriforce** [dnschneid/crouton#4506]
I have been trying to create a chroot with target `audio` and I get this error
```
Compiling CRAS (i386)...
In file included from libcras/cras_client.c:47:
libcras/cras_client.h:1439:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1454:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1475:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1491:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1506:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1530:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1550:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1570:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1592:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1608:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1623:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1638:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1653:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1668:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1683:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1732:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1753:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1767:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1784:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1799:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1815:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1831:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1847:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1878:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1893:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1908:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1924:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1940:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1955:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1970:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:1985:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
libcras/cras_client.h:2000:1: error: 'cfi-icall' attribute directive ignored [-Werror=attributes]
 {
 ^
cc1: all warnings being treated as errors
Failed to complete chroot setup.
```

I tried changing the releases to `xenial, bionic, focal, sid, stretch` and none of them worked. I even tried `gcc-7, gcc-9, gcc-10, gcc-11` and still the same error. If `-Wno-error=attributes` flag is added to the `make` target, this issue can be resolved.
Any help would be greatly appreciated!

**Comment by haberda** [comment]
Just want to say that I also have this issue. I can install anything I want as long as the only target is core. The problem seems to come from the audio target, which is a dependency of some of the other target (like xfce for example).

**Comment by haberda** [comment]
I managed a temporary workaround. Please note, there will be no audio working, but it seems everything else does:

1. If you haven't done so, install crouton according to the docs
2. In the console run `sudo crouton -x ~/mylocation` Where mylocation is a folder where you can extract crouton to
3. Navigate to the mylocation folder in the file browser, you will see a number of folders, open the `targets` folder and open the `audio` file with a text editor and delete everything below line 12, save.
4. Now in the console, assuming you are in the mylocation folder, you can run all the same crouton commands by: `sudo ./installer/main.sh`

Alternatively, you could probably just clone the repo to the local machine and just do the same thing without installing it, but I don't know what the implications of that are.

**Comment by UmashankarTriforce** [comment]
@haberda That's a great find! This issue arises because of `-Werror` in the Makefile of CRAS. It considers all the warnings as errors. So I developed a simple fix to overcome this. 
Just follow your steps of 1,2. In step 3, instead of deleting the contents after line 12, just add this command in line 119 - `sed -i 's/-Werror//g' Makefile.am`. This will remove any occurrence of `-Werror` in the Makefile. CRAS will then compile successfully. You can follow the remaining steps as it is.

**Comment by jeffzear** [comment]
Sorry -- relative noob question:

Upon sudo crouton -x ~/mydirectory, I get the directory structure (with chroot-bin, chroot-etc ... targets) in it, but there's nothing in any of the folders. A review of the help docs doesn't show -x as a flag.

Thanks in advance!

**Comment by haberda** [comment]
@jeffzear the `-x` parameter tells crouton to simply extract the source to that folder. If you extract with `sudo` it looks like the extracted folders have root ownership, hence why the folders look empty. Try the same command without `sudo`.

@UmashankarTriforce You should submit a PR to get this fixed for everyone!

**Comment by haberda** [comment]
I submitted PR #4507 to address this.

**Comment by UmashankarTriforce** [comment]
@haberda Great! I was caught up with something else, I was gonna work on submitting a PR in a couple of hours 😬

**Comment by dpilgrim** [comment]
I have run into this issue as well, and when I try haberda's workaround I get:
"sudo: unable to execute installer/main.sh: Permission denied"

**Comment by daboisadasd** [comment]
The solution to the cras error is to make sure your chromebook is in a stable build channel, open settings, go to About Chrome OS click additional details, click change channel and click stable. Then follow the onscreen instructions.

**Comment by haberda** [comment]
@dpilgrim I ran into this after the first chroot was created. I don't really understand it. However, there is another workaround. Install the chroot with crouton as normal. You will run into the CRAS error. In the terminal:

`sudo su`

Then as su navigate to the chroot install location.

Copy the `prepare.sh` file to an editable location such as `Downloads`. Run  `chmod 777 prepare.sh`.

Then you have to find the line to edit. `prepare.sh` is a roll up script and the exact line number you have to edit will vary, but apply the same fix outlined above.

Then copy the edited `prepare.sh` back to the original location. Run `chmod 510 prepare.sh` to reset the permissions (I think 510 is correct...). 

Then enter the chroot as if it finished setup correctly `enter-chroot foo`. It will say something like setup has not completed and ask if you want to continue, select yes. It should now complete.

**Comment by DennisLfromGA** [comment]
Also of import, see a crouton dev's comment here:
- https://github.com/dnschneid/crouton/issues/4450#issuecomment-826182681

Hope this helps,
-**DennisLfromGA**

**Comment by saltedcoffii** [comment]
I'm having this issue as well.

**Comment by dpilgrim** [comment]
Update: Thanks to DennisLfromGA for showing me where the fix was merged in. By switching from Stable to Beta I was able to hitch a ride on the fixed build, and now CRAS compiles.

**Comment by sandeep-gh** [comment]
I also get CRAS compile error ("no sanitize" -Werror). I am not able to understand what the final fix/workaround is? I tried @haberda  approach but got the same permission denied error. Is there a beta version of crouton that needs to be used? If so, where to find it.

**Comment by UmashankarTriforce** [comment]
> @haberda That's a great find! This issue arises because of `-Werror` in the Makefile of CRAS. It considers all the warnings as errors. So I developed a simple fix to overcome this. 
> Just follow your steps of 1,2. In step 3, instead of deleting the contents after line 12, just add this command in line 119 in `audio` target file - `sed -i 's/-Werror//g' Makefile.am`. This will remove any occurrence of `-Werror` in the Makefile. CRAS will then compile successfully. You can follow the remaining steps as it is. 
> This fix will allow you to have audio working in your chroot instead of completely removing it.

Please try this, it works for me.

**Comment by GrantCuster** [comment]
I was stuck on the same 'permission denied' error when trying to run installer.sh as @sandeep-gh and @dpilgrim. Found the solution in the readme:

> You also need to remember to place the unbundled scripts somewhere in /usr/local in order to be able to execute them.

I moved the unpacked crouton, including the modified audio target, into /usr/local and successfullly ran installer/main.sh from there.

**Comment by harrisonlingren** [comment]
Confirming the following worked for me:

1. Download `crouton` release as normal
2. `sudo crouton -x /usr/local/crouton-files && cd /usr/local/crouton-files`
3. `sudo chmod -R +rw .`
4. Patch the change from #4507 to `targets/audio` with `vi`
5. `sudo installers/main.sh -t <targets>`

**Comment by sandeep-gh** [comment]
Finally, did worked for me. I had to delete the chroot and start afresh instead of update the current install.

**Comment by dnschneid** [comment]
This should be fixed in the latest crouton release.
