### ISSUE TITLE
Increase in frames after switching between chrome and crouton repeatedly

### ISSUE THREAD

**Issue by LilJezza** [dnschneid/crouton#4510]
```
Please paste the output of the following command here: [Not Applicable]
```
name: xenial
encrypted: no
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13816.55.0 (Official Build) stable-channel setzer
kernel: Linux localhost 4.19.176-11262-ge5fd762f9648 #1 SMP PREEMPT Mon Apr 19 20:11:30 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:

I'm trying to run minecraft on crouton and usually have horrible frames. However, sometimes when switching between chrome and crouton, I get up to 60 frames consistently. I want to replicate this all the time. Also I've noticed that crouton is only using 60% of its cpu and not much in general even after considering I changed the niceness of java to -20. Anyone know how to also use 100% or close to that much cpu?

#### If known, describe the steps to reproduce the issue:
Switch back and forth between chrome os and crouton over and over

**Comment by Just-Randomly-Me** [comment]
Download a recent linux release like focal fossa. It should have updated drivers. Xenial is pretty old now. There's a whole disccusion about focal fossa in pinnied issues

**Comment by Just-Randomly-Me** [comment]
Download a recent linux release like focal fossa. It should have updated drivers. Xenial is pretty old now. There's a whole discussion about focal fossa in pinned issues
