### ISSUE TITLE
issues downloading 

### ISSUE THREAD

**Issue by mem0ryd0nk** [dnschneid/crouton#4512]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
whenever i try to install crouton using the command 'sudo sh ~/Downloads/crouton -e -t xfce,extension,keyboard,audio' it says 'sh: 0: Can't open /home/chronos/user/Downloads/crouton' even though i'm in developer mode. is anyone else having this problem or is it just me?

**Comment by DennisLfromGA** [comment]
Please read the new installation instructions in the [README](https://github.com/dnschneid/crouton/blob/master/README.md).
