### ISSUE TITLE
Tried downloading crouton, but...

### ISSUE THREAD

**Issue by Phe0nyx** [dnschneid/crouton#4513]
#### Please paste the output of the following command here: `sudo edit-chroot -all`
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xfce
host: version 13904.41.0 (Official Build) stable-channel cyan 
kernel: Linux localhost 4.19.185-29737-g391d4c3e561f #1 SMP PREEMPT Tue May 25 22:49:45 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
#### Please describe your issue:
I was trying to do as how the Github page said, but I got this error (I made a comment on another post, stating I had the same issue as the original poster): `Failed to complete chroot setup.` 

#### If known, describe the steps to reproduce the issue:
All I did was try to install chroot, then remove it (and failed).

**Comment by DennisLfromGA** [comment]
I replied to your comment in the other issue before I saw this one, see below:  
- https://github.com/dnschneid/crouton/issues/4432#issuecomment-860255325  

Please see it and follow up there if need be.
