### ISSUE TITLE
In the chroot, we cant install apps w/o using sudo command

### ISSUE THREAD

**Issue by ty1118** [dnschneid/crouton#4514]
when i try to install app from any chroot i get a no authorization. how do i fix this

**Comment by DennisLfromGA** [comment]
@ty1118,

By prefixing the command with `sudo`.
See this explanation as to why it's needed -

- APT
https://help.ubuntu.com/kubuntu/desktopguide/C/apt-get.html

- Root And Sudo
https://help.ubuntu.com/kubuntu/desktopguide/C/root-and-sudo.html

The above is for KUbuntu but it still applies.

*Hope this helps,*
-**DennisLfromGA**

**Comment by DennisLfromGA** [comment]
Follow up from OP in issue, now closed and tracking here:

> @ty1118 
> Allow me to explain deeper, why am i getting the message that I do not have authorization to install an app or change the config of my chroot? as in why dont i get prompeted to enter my password for doing things like changing my login screen or installing an in muon

**Comment by DennisLfromGA** [comment]
Closing. No response or follow-up (needed) at this time.

-**DennisLfromGA**
