### ISSUE TITLE
In the chroot, we cant install apps w/o using sudo command

### ISSUE THREAD

**Issue by ty1118** [dnschneid/crouton#4518]
Allow me to explain deeper, why am i getting the message that I do not have authorization to install an app or change the config of my chroot? as in why dont i get prompeted to enter my password for doing things like changing my login screen or installing an in muon

**Comment by DennisLfromGA** [comment]
Please don't open another issue for this question, I've reopened your first one so you and others can follow up there.   
- In the chroot, we cant install apps w/o using sudo command · Issue #4514 · dnschneid/crouton
https://github.com/dnschneid/crouton/issues/4514

Sorry my explanation didn't fully address your concern, maybe others will be able to help out.
