### ISSUE TITLE
Crouton VPN

### ISSUE THREAD

**Issue by LilJezza** [dnschneid/crouton#4519]
```
Please paste the output of the following command here: [Not Applicable]
```
name: xenial
encrypted: no
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13816.55.0 (Official Build) stable-channel setzer
kernel: Linux localhost 4.19.176-11262-ge5fd762f9648 #1 SMP PREEMPT Mon Apr 19 20:11:30 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:

I've been trying a few types of vpn's with crouton including windscribe and proton vpn but can never get one set up on the crouton environment. I'm just looking for a free vpn that works with crouton. I would even be okay with a vpn working through crouton from chrome.

#### If known, describe the steps to reproduce the issue:

Try to set up a vpn from crouton

**Comment by MrHallway0** [comment]
Do you have *any* debugging info or output that we could use to solve the issue? 
You could get some, normally, by running the apps from the terminal.

You can also take a look at #2916.

**Comment by DennisLfromGA** [comment]
Since crouton chroots uses the Chrome OS network and processes you can set up a VPN in Chrome OS and all crouton traffic will go through it. I use a PIA (Private Internet Access) VPN and it works great but there are many others.

**Comment by iptoux** [comment]
Bevor running OpenVPN
In Chrome OS:

- Strg+Alt+t

```
shell
sudo stop shill
sudo start shill BLACKLISTED_DEVICES=tun0
```

Source: [https://www.google.de/url?sa=t&source=web&cd=&ved=2ahUKEwit6b2z7PXzAhXO57sIHZmjBI8QFnoECAsQAQ&url=https%3A%2F%2Fgithub.com%2Fdnschneid%2Fcrouton%2Fissues%2F2916&usg=AOvVaw021Y5LNNIKebUyLt24piHp](GitHub)
