### ISSUE TITLE
use dev_boot_altfw :/ please i need help 

### ISSUE THREAD

**Issue by hpchromebook11g4** [dnschneid/crouton#4520]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Whenever i use sudo crouton -t xfce it says that and whenever it finished it says chroot failed to complete setup

**Comment by dnschneid** [comment]
Latest release of crouton won't say that anymore.  It might not fix your actual problem, though, so if it still fails please reopen with a more complete log.
