### ISSUE TITLE
Applications Not Opening

### ISSUE THREAD

**Issue by LilJezza** [dnschneid/crouton#4522]
```
Please paste the output of the following command here: 
```

#### Please describe your issue:
I've been trying to open apps. Namely Minecraft, however, it shows no error and just doesn't open. On the chrome terminal I get this:

https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
OK
https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
MessageBox(Minecraft Launcher): Couldn't load launcher core from /home/weemanjezza/.minecraft/launcher/liblauncher.so: LoadErrorNotPresent

My cousin who is also a Chromebook gamer is getting the same thing starting at the same time. Is anyone able to help? I've tried deleting the chroot and redownloading it, restarting my Chromebook, and uninstalling and installing minecraft.\

**Comment by MrHallway0** [comment]
@LilJezza what Chromebook do you have?

**Comment by LilJezza** [comment]
I'm using an Asus Chromebook C202SA
