### ISSUE TITLE
Cras is failing to compile

### ISSUE THREAD

**Issue by animeking9901** [dnschneid/crouton#4523]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: stretch
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/stretch...
crouton: version 1-20200724165050~master:08dac970
release: stretch
architecture: amd64
targets: xfce
host: version 13904.66.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.228-37743-g49d2c603c1a5 #1 SMP PREEMPT Wed Jun 16 23:49:27 PDT 2021 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/stretch...
#### Please describe your issue:

Cras refuses to compile when creating a fresh chroot,causing chroot setup to fail
#### If known, describe the steps to reproduce the issue:
try to create any chroot,and it will fail while compiling cras

logs at: https://del.dog/crouton-cras-failcompile

**Comment by DennisLfromGA** [comment]
This is a known issue, please track it here:  
- https://github.com/dnschneid/crouton/issues/4450#issuecomment-826182681
