### ISSUE TITLE
Debootstrap error: ar: error while loading shared libraries: libbfd-2.36.1.so

### ISSUE THREAD

**Issue by backslash-0001** [dnschneid/crouton#4531]
#### Please describe your issue:

Every time I try and install any distro I get the same error:
```
I: Retrieving ubuntu-minimal 1.361
I: Validating ubuntu-minimal 1.361
I: Retrieving ucf 3.0036
I: Validating ucf 3.0036
I: Retrieving udev 229-4ubuntu4
I: Validating udev 229-4ubuntu4
I: Retrieving ureadahead 0.100.0-19
I: Validating ureadahead 0.100.0-19
I: Retrieving util-linux 2.27.1-6ubuntu3
I: Validating util-linux 2.27.1-6ubuntu3
I: Retrieving vim-common 2:7.4.1689-3ubuntu1
I: Validating vim-common 2:7.4.1689-3ubuntu1
I: Retrieving vim-tiny 2:7.4.1689-3ubuntu1
I: Validating vim-tiny 2:7.4.1689-3ubuntu1
I: Retrieving whiptail 0.52.18-1ubuntu2
I: Validating whiptail 0.52.18-1ubuntu2
I: Retrieving xkb-data 2.16-1ubuntu1
I: Validating xkb-data 2.16-1ubuntu1
I: Retrieving zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Validating zlib1g 1:1.2.8.dfsg-2ubuntu4
I: Chosen extractor for .deb packages: ar
I: Extracting adduser...
debootstrap error log:


ar: error while loading shared libraries: libbfd-2.36.1.so: cannot open shared object file: No such file or directory
Failed to run debootstrap.
```

Using a Pixelbook on 91.0.4472.147.

**Comment by MrHallway0** [comment]
Are you using a [Pixelbook Go](https://www.google.com/intl/en_uk/chromebook/device/google-pixelbook-go/) or the [Pixelbook](https://www.amazon.co.uk/Google-Pixelbook-12-3-Inch-Laptop-Processor/dp/B077GGZTTR/ref=sr_1_3?dchild=1&keywords=:D&qid=1625153747&sr=8-3)?

**Comment by backslash-0001** [comment]
It's the original 2017 Pixelbook.

**Comment by MrHallway0** [comment]
Does it say *anything* about `libbfd-2.36.1.so` before this log?

**Comment by backslash-0001** [comment]
Nope, only in the error itself. Full log is [here](https://termbin.com/wdec).

**Comment by saltedcoffii** [comment]
Do you have chromebrew installed? If you do, the problem is likely chromebrew's version of `libbfd`. I uninstalled chromebrew and got it to work, but if you don't want to install chromebrew you can `unset LD_LIBRARY_PATH` and see if that works.

**Comment by MrHallway0** [comment]
@saltedcoffii Crouton works via chroots, so I wouldn't think that is the case, feel free to correct me if I am wrong though.

**Comment by backslash-0001** [comment]
Thanks. I did have chromebrew installed, uninstalled and now it works.

**Comment by MrHallway0** [comment]
> Thanks. I did have chromebrew installed, uninstalled and now it works.
I stand corrected... I didn't think that Chromebrew effected it.

**Comment by supechicken** [comment]
> @saltedcoffii Crouton works via chroots, so I wouldn't think that is the case, feel free to correct me if I am wrong though.

In the early stages of the chroot setup, `debootstrap` is used to create a basic rootfs for chroot (running outside of chroot), then take over by `apt` in chroot to complete the setup
