### ISSUE TITLE
Use Debian LTS Packages in Stretch (suggestion)

### ISSUE THREAD

**Issue by Anonymoustank** [dnschneid/crouton#4532]
Wouldn't it be best to automatically include the LTS repository for Debian Stretch ([found here](https://wiki.debian.org/LTS/Using)) in the /etc/apt/sources.list for the security updates?

**Comment by dnschneid** [comment]
Ooh yeah, looks like the logic for including the updates and security repos for debian hasn't been updated since jessie.
