### ISSUE TITLE
Getting the crouton file (not the installer)

### ISSUE THREAD

**Issue by RhyeBread** [dnschneid/crouton#4533]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xfce
host: version 13904.77.0 (Official Build) stable-channel celes 
kernel: Linux localhost 4.19.185-29738-gf8e4fd700b66 #1 SMP PREEMPT Sun Jun 27 22:51:41 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
#### Please describe your issue:
when I try to type 'sudo crouton -x /usr/local/crouton-file' it doesn't do anything, however, if it did something, I don't know where I'm supposed to look to see the file

#### If known, describe the steps to reproduce the issue:
I just did 'sudo crouton -x /usr/local/crouton-file'

**Comment by DennisLfromGA** [comment]
@RhyeBread,

If that command succeeds it will not display anything but will extract the crouton scripts in the directory:   
- `/usr/local/crouton-file/`

After the extraction you can modify crouton and then run installer/main.sh directly.

*Hope this helps,*
-**DennisLfromGA**
