### ISSUE TITLE
So does anyone know how to fix this

### ISSUE THREAD

**Issue by Babasrian** [dnschneid/crouton#4534]
```sudoedit-chroot all
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

Failure  to run:  dpkg --force-depends --install /var/cache/apt/archives/libc6_2.31-12_amd64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/libc6_2.31-12_amd64.deb is at fault) this is the error I get with every linux I try and download.

**Comment by DennisLfromGA** [comment]
It's a (well-)known issue, please track it here:   
- crouton on x86_64 *and* arm, kernel version issue with libc updating in chroot · Issue #4429 · dnschneid/crouton
https://github.com/dnschneid/crouton/issues/4429#issuecomment-842854754

**Comment by Babasrian** [comment]
thanks
