### ISSUE TITLE
Failed to complete chroot setup

### ISSUE THREAD

**Issue by overandoverifallforyou** [dnschneid/crouton#4541]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: amd64
targets: xfce
host: version 13904.66.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.228-37743-g49d2c603c1a5 #1 SMP PREEMPT Wed Jun 16 23:49:27 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
i'm pretty new to this, but i've looked up everything and i can't figure out how to fix cc1: error: unrecognized command line option '-Wno-int-in-bool-context' [-Werror]

#### If known, describe the steps to reproduce the issue:
when i type
sudo crouton -n xenial -u 
it always says 
cc1: error: unrecognized command line option '-Wno-int-in-bool-context' [-Werror]
cc1: all warnings being treated as errors
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in xenial
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

any help is appreciated

**Comment by dnschneid** [comment]
Please try the latest release of crouton and re-open if it doesn't fix the failure.
