### ISSUE TITLE
Can't open /home/chronos/user/Downloads/crouton

### ISSUE THREAD

**Issue by FrozenSalad** [dnschneid/crouton#4543]
No matter wtf I do I just can't seem to get ubuntu to install, yes I have crouton in my downloads folder, yes I have developer mode on, yes I literally followed 17 billion different guides all doing almost the exact same thing besides a few tweaks with the command I even tried following ubuntu.com. I'm getting really irritated cause literally all I did dev mode for was a better Linux operating system plus nonplay store apks. So please somebody just help me ive been at this for a solid hour or so
![Screenshot 2021-07-10 1 26 37 PM](https://user-images.githubusercontent.com/83255316/125175749-fe194880-e182-11eb-8534-ee460f67d0e4.png)
![Screenshot 2021-07-10 1 27 06 PM](https://user-images.githubusercontent.com/83255316/125175754-01accf80-e183-11eb-8fce-28b5fb6ecdcc.png)

**Comment by FrozenSalad** [comment]
wow for some reason it works when i follow the github intructions?

**Comment by DennisLfromGA** [comment]
@FrozenSalad,

> I literally followed 17 billion different guides all doing almost the exact same thing ...

Just follow the **[README](https://github.com/dnschneid/crouton#usage)** that shows the **new** installation method, many online guides are out of date.
It's basically the following steps -
1. grab the latest release from https://goo.gl/fd3zc and download it in ~/Downloads
2. pop open a shell (Ctrl+Alt+T, type shell and hit enter)
3. make the installer executable with `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`
4. install the release with the targets of your choice with `sudo crouton -t lxde` etc.

*Hope this helps,*
-**DennisLfromGA**
