### ISSUE TITLE
Oh Snap!(pun intended):)

### ISSUE THREAD

**Issue by yoiammaac** [dnschneid/crouton#4553]
I am running ubuntu 18.04 bionic, and whenever I try to install something with snap, I get this:

error: cannot communicate with server: Post http://localhost/v2/snaps/spotify: dial unix /run/snapd.socket: connect: no such file or directory
i also got this on xenial(and any other ubuntu release for that matter).
Found no solution though. Please help?

**Comment by Dozer257** [comment]
I can confirm that this problem also happens in Ubuntu 16.04 and 20.04 on Snap



I see that you're trying to install Spotify, but don't worry, I know how to install without using Snap.

1. Install curl if you haven't installed it yet `sudo apt install curl`

2. Import the public GPG key `curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add -`

3. Add Spotify's deb package to the system sources list `echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list`

4. Refresh the APT repo `sudo apt update`

5. And finally install Spotify `sudo apt install spotify-client`


I have tested this install method on both Ubuntu 16.04 and Ubuntu 20.04 so it should work on Ubuntu 18.04, let me know if it works.


Yes, I know this doesn't answer why Snaps don't work, but I just wanted to help you install Spotify.

**Comment by yoiammaac** [comment]
Thanks
But its just so much easier with snap & ubuntu software.
oh well.

**Comment by BetaPictoris** [comment]
> Snap has never really worked with crouton, as far as I can tell.

@ascent08 issue #4278 (this issue was closed, although had the same problem).
