### ISSUE TITLE
Xfce4 screen only updating in the background

### ISSUE THREAD

**Issue by alizeegagnon** [dnschneid/crouton#4554]
```
chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210709170820~master:14ca6bc7
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13904.97.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.185-29738-gf8e4fd700b66 #1 SMP PREEMPT Mon Jul 19 19:55:07 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`
```
#### Please describe your issue:

Freshly installed XFCE4 on a Lenovo Chromebook Flex. Whenever I am tabbed in to XFCE, I can move the mouse but the screen is not updating at all, i.e. no matter how much I click or the keyboard shortcuts I type nothing happens. The clock is not updating either. When I tab out into Chrome OS and then back in, the screen has updated with the actions I made. 

Probably related, when I closed the lid while tabbed in XFCE, upon reopening it my mouse is "stuck" in and around the focused window and I cannot tab back to ChromeOS anymore.  

#### If known, describe the steps to reproduce the issue:

1. Enter the shell on Chrome OS and type `sudo startxfce4`
2. The screen is black but the mouse can move. Tab out using ctrl+alt+shift+F2, then tab back in using the same key combination. 
3. The xfce desktop is now visible, but frozen. Type Alt+F2, then type "Hello". Nothing appears on the screen. Upon tabbing out and in, the Application Finder window is visible with "Hello" written in the box.
4. Close the lid, then open it back. Now the mouse is stuck in a box about 1cm larger than the App Finder window. It is no longer possible to tab out so the laptop is effectively soft-locked.

**Comment by MrHallway0** [comment]
I have a similar model to yours, just with an ARM processor, I will test Xenial XFCE soon...

**Comment by alizeegagnon** [comment]
Figured this log may be useful, these are the error messages I get when executing `sudo startxfce4`: 
`chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.19.185-29738-gf8e4fd700b66 #1 SMP PREEMPT Mon Jul 19 19:55:07 PDT 2021 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5324800 verity payload=PARTUUID=5d4dc93e-5d15-4221-87dd-d282f5a3f94b/PARTNROFF=1 hashtree=PARTUUID=5d4dc93e-5d15-4221-87dd-d282f5a3f94b/PARTNROFF=1 hashstart=5324800 alg=sha256 root_hexdigest=19613e7886c71da3f914dbc498d0114791554155a3e1a27d7d8364a862f2a7a0 salt=801ddb02f8ebe3932ff936b74480aa3b257b08ede187077f6430053b2af85ff2" noinitrd vt.global_cursor_default=0 kern_guid=5d4dc93e-5d15-4221-87dd-d282f5a3f94b add_efi_memmap boot=local noresume noswap i915.modeset=1 ramoops.ecc=1 gsmi.s0ix_logging_enable=1 intel_pmc_core.warn_on_s0ix_failures=1  
Build Date: 08 April 2021  01:52:21PM
xorg-server 2:1.18.4-0ubuntu0.12 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jul 23 16:11:45 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
i965_dri.so does not support the 0x9b21 PCI ID.
crouton: version 1-20210709170820~master:14ca6bc7
release: xenial
architecture: amd64
xmethod: xorg
targets: xfce
host: version 13904.97.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.185-29738-gf8e4fd700b66 #1 SMP PREEMPT Mon Jul 19 19:55:07 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
xrandr: Output eDP1 is not disconnected but has no modes
xrandr: Output DP1 is not disconnected but has no modes
xrandr: Output DP2 is not disconnected but has no modes
Kicking xrandr again
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
xfce4-session: No GPG agent found
xfce4-session: No SSH authentication agent found

(xfce4-session:4672): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /home/alizee/.cache/sessions/xfce4-session-localhost:1, Does it exist? Permissions issue?
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
`
