### ISSUE TITLE
what am i doing wrong here?

### ISSUE THREAD

**Issue by ezrastar** [dnschneid/crouton#4555]
Please paste the output of the following command here: `sudo edit-chroot -all`
```
crosh> shell
chronos@localhost / $ sudo sh ~/Download/crouton -m -t xfce
Password: 
sh: 0: Can't open /home/chronos/user/Download/crouton
chronos@localhost / $ 
```
#### Please describe your issue:
i've tried deleting crouton and redownloading it but that didnt work can someone who knows what there doing help please 

#### If known, describe the steps to reproduce the issue:download crouton and do the following commands
```
crosh> shell
chronos@localhost / $ sudo sh ~/Download/crouton -m -t xfce
Password: 
sh: 0: Can't open /home/chronos/user/Download/crouton
chronos@localhost / $"
```

**Comment by ezrastar** [comment]
figured that out but now it says Enter encryption passphrase for xenialEnter encryption passphrase for xenial

**Comment by MrHallway0** [comment]
The install steps have changed, please read the [README](https://github.com/dnschneid/crouton/blob/master/README.md) to get the most up to date info.

**Comment by DennisLfromGA** [comment]
@ezrastar,

What @MrHallway0 said ...

-------------  

Also, if it's asking you for an encryption password, at some point, you've requested encryption using the crouton's '`-e`' option.
If you don't want to enter an encryption passphrase, don't request encryption. If you can't get past that prompt then it's best to remove the chroot and start over.

In my experience, it's best to install your chroot first without encryption, once it's installed successfully and working the way you want then if you still want to add encryption do it with an update using: `sudo crouton -e -u [-n chrootname]`

*Hope this helps,*
-**DennisLfromGA**
