### ISSUE TITLE
How to Download ubuntu budgie on chromebook

### ISSUE THREAD

**Issue by yoiammaac** [dnschneid/crouton#4556]
How to Download ubuntu budgie on chromebook? 
is there such a target to do so?

**Comment by DennisLfromGA** [comment]
There doesn't appear to be a  'Budgie' desktop package available for any releases, only [complete Budgie distros for the focal and  hirsuit releases](https://ubuntubudgie.org/downloads/). So, you can't install a Budgie desktop package for it in crouton, or even Crostini.

Someone would have to create a budgie desktop package and then submit a crouton pull request to get it added.

*Hope this helps,*
-**DennisLfromGA**

**Comment by yoiammaac** [comment]
ohhhh..... 
I was hoping to download it in my bionic chroot.
Thanks anyway.

**Comment by MrHallway0** [comment]
> ohhhh.....
> I was hoping to download it in my bionic chroot.
> Thanks anyway.

You could *try* using the [`ubuntu-budgie-desktop`](https://packages.ubuntu.com/bionic/ubuntu-budgie-desktop) package, installing it in a chroot by your self and then somehow launching it from there ([this](https://askubuntu.com/questions/293575/switch-desktop-without-sign-out) looks promising).

**Comment by yoiammaac** [comment]
> > ohhhh.....
> > I was hoping to download it in my bionic chroot.
> > Thanks anyway.
> 
> You could _try_ using the [`ubuntu-budgie-desktop`](https://packages.ubuntu.com/bionic/ubuntu-budgie-desktop) package, installing it in a chroot by your self and then somehow launching it from there ([this](https://askubuntu.com/questions/293575/switch-desktop-without-sign-out) looks promising).

I tried, i thought i was good to go, but it ruined my chroot. I had to download it again.
