### ISSUE TITLE
How to execute executables in Debian

### ISSUE THREAD

**Issue by sanrobin** [dnschneid/crouton#4567]
Hello There!
I installed Debian 10 Buster KDE in my Chromebook to run Eclipse IDE (as Crostini frequently crashed) but after installing, I cant execute the executable. At first I thought it got corrupted somehow but I tried reinstalling(both Eclipse and the chroot) but to no avail. Can anyone know how to fix it?

Error Code:
(buster)sanjay@localhost:~/Desktop/Debian/eclipse$ ./eclipse                             ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-bash: ./eclipse: Permission denied

Sorry I don't know how to reproduce the error.

**EDIT:I FORGOT TO SAY THAT I EVEN CHANGED THE PERMISSIONS TOO**

(buster)sanjay@localhost:~/Desktop/Debian/eclipse$ chmod +rwx eclipse

(buster)sanjay@localhost:~/Desktop/Debian/eclipse$ ./eclipse

-bash: ./eclipse: Permission denied

**Comment by DennisLfromGA** [comment]
@sanrobin,

Do a long listing of your eclipse file and see who owns it & who can execute it with: 
- `ls -l ./eclipse`   

Also, is the file `./eclipse` in your $HOME directory or somewhere else?
If it's in your $HOME directory run the following command and make sure there is no 'noexec' in the mount options:  
- `mount | grep ~/`  

*Hope this helps,*
-**DennisLfromGA**

**Comment by sanrobin** [comment]
I found the culprit. It was ChromeOS itself ! I moved the executables to desktop and it worked. Sorry for late reply.
