### ISSUE TITLE
Error trying to update pip in Xenial (crouton)

### ISSUE THREAD

**Issue by JRIsP-dunno-much-about-coding** [dnschneid/crouton#4568]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20200724165050~master:08dac970
release: xenial
architecture: i386
xmethod: xorg
targets: xfce
host: version 9334.72.0 (Official Build) stable-channel x86-alex_he 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 17 17:49:46 PDT 2017 i686 i686 i686 GNU/Linux
freon: yes

#### Please describe your issue:

Hello to you all! I'm trying to upgrade pip so I can run things in Python (mostly for university math, numpy and scipy stuff) and I downloaded pip and python setuptools via apt and everything went great in both Python and Python3 (I ran simple codes perfectly).

However, when I try to install numpy and scipy I get an error saying something like "please ugrade pip" (You should consider upgrading via the 'pip install --upgrade pip' command.), and indeed: there's pip 21 out there and I only got pip 8 (!). So I try to upgrade pip with that very same code (with sudo) and I get this error:

```
Collecting pip
  Using cached https://files.pythonhosted.org/packages/52/e1/06c018197d8151383f66ebf6979d951995cf495629fc54149491f5d157d0/pip-21.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hJjmqm/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hJjmqm/pip/
You are using pip version 8.1.1, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Based on my research I think it's a path related issue. I have my packages right but pip can't find them... and I have reasons to think this is related to the mystic paths used by the chroot. Any ideas? Thank you!

**Comment by DennisLfromGA** [comment]
@JRIsP-dunno-much-about-coding,

You're using a *very* old Atom-PineTrail 32-bit CPU so that may be the biggest issue.
The later versions of pip may not b available on your platform, I don't know for sure though since I haven't researched it myself.

*Hope this helps,*
-**DennisLfromGA**
