### ISSUE TITLE
Software Updater "You are not allowed to perform this action"

### ISSUE THREAD

**Issue by vladikoff** [dnschneid/crouton#457]
`saucy` Ubuntu 13.10, fresh installation. Won't allow me to check for updates. 

![image](https://f.cloud.github.com/assets/128755/1417021/ee3b30a2-3f75-11e3-8a1e-990882e30b96.png)

Probably related to same issues as in https://github.com/dnschneid/crouton/issues/446

**Comment by ricprata** [comment]
I am observing this very issue on Xenial and Yakkety on Xfce. I'm on the Acer R13.

**Comment by JELaVallee** [comment]
Ditto for Xenial-Unity on a ASUS 302CA... No authentication prompt showing...

**Comment by Frank303** [comment]
Same on Acer C730 Gnawty. 
xenial -t x11,gtk-extra,unity,unity-desktop,core,cli-extra,extension,keyboard,chrome,audio,xiwi,xorg -e
I tried reinstalling but still the same.
Synaptic doesn't launch though it can be executed from terminal.
System log doesn't launch.
Software updater doesn't bring up authentication.

**Comment by mattsodes1031** [comment]
I have exact the same problems as Frank303. I have the samsung 3 and running xenial. Please tell if there s a fix to these problems

**Comment by ebdavison** [comment]
same problem here as well ...

**Comment by kupietools** [comment]
Same issue after upgrading to Ubuntu 17.10. Everything worked fine in 17.04, now I don't have privs to update anything.

**Comment by notstarboard** [comment]
I'm running into this as well on xenial. gksudo brings up the expected password prompt, but all updates still fail to install.

**Comment by cmdywrtr27** [comment]
been about a year since last comment but looks like problem still exists, i cant open synaptic unless using gksudo and trying to update through software center gives me: 

org.freedesktop.PolicyKit.Error.Failed: ('system-bus-name', {'name': ':1.83'}): org.debian.apt.update-cache

using gksudo to open software center and software updater doesn't work

**Comment by shoummashams** [comment]
@cmdywrtr27 I was having that same issue on 16.04 Xenial but I switched to 18.04 and using `sudo synaptic` (gnome-software too) works.

**Comment by squirreltasm** [comment]
> @cmdywrtr27 I was having that same issue on 16.04 Xenial but I switched to 18.04 and using `sudo synaptic` (gnome-software too) works.

Keep it simple, stupid. Thank you for this suggestion! I was finally able to easily dump a bunch of apps without hunting them down in the terminal. (running Xubuntu 18.04 on Ancient Chromebook 11)

**Comment by MeneerJansen** [comment]
I also still have this problem. Anybody know a solution? I'm on Debian 11 "Bullseye". Nothing works with `pkexec`!
