### ISSUE TITLE
replace httpredir.debian.org with deb.debian.org

### ISSUE THREAD

**Issue by pabs3** [dnschneid/crouton#4573]
The installer for Debian [references](https://github.com/dnschneid/crouton/blob/master/installer/debian/defaults) the httpredir.debian.org apt mirror redirector service, but this service no longer exists and has been replaced by the [deb.debian.org apt CDN service](https://deb.debian.org/). Please update the URL used to the new service. The new service also supports https.

**Comment by dnschneid** [comment]
Thanks for pointing that out!  Switching to https is mainly important for debootstrap (since it doesn't have gpg); otherwise, packages are validated using GPG and don't need https necessarily.

**Comment by pabs3** [comment]
At least debootstrap run from a Debian system and debootstrap as run in
the Debian installer verify OpenPGP signatures by default. So I think
crouton could also instruct debootstrap to verify OpenPGP signatures.

https://manpages.debian.org/buster/debootstrap/debootstrap.8.en.html#OPTIONS

The main advantage of https is that unsophisticated network attackers
will not be able to trivially know which packages/versions you install.
Of course it doesn't help with attackers who can do some statistics on
packages and requests sizes, but is better than nothing and there are
the Tor Onion services for those who want something better.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
