### ISSUE TITLE
Crouton/xiwi display stopped working properly

### ISSUE THREAD

**Issue by harmalkar** [dnschneid/crouton#4575]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210709170820~master:14ca6bc7
release: xenial
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 14092.28.0 (Official Build) beta-channel kip 
kernel: Linux localhost 4.4.254-20725-g094d7d3745aa #1 SMP PREEMPT Tue Aug 10 21:45:26 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```

#### Please describe your issue:
I'm using the crouton integration app with xiwi to display the desktop environment. It's been working perfectly for about a month, but today something broke and the text and icons no longer display properly:

![image](https://user-images.githubusercontent.com/12296732/129807573-d39a56d8-5c17-4b29-b91a-3ed9200d473b.png)

As you can see from the image above, the display environment has become slightly transparent, the background wallpaper is gone, and the text is hard to read. There are a few other issues which are hard to take a screenshot of as well, such as text disappearing when hovering over it or text not clearing when it normally would after the display refreshes. 

This is the output which appears in the terminal after I run sudo startxfce4:

```
Connected to extension, launched crouton in a window.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No GPG agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(xfwm4:23582): xfwm4-WARNING **: output size (683x640) and logical screen size (1366x736) do not match
xsel: realloc error: Resource temporarily unavailable
xsel: realloc error: Resource temporarily unavailable
xsel: realloc error: Resource temporarily unavailable
xsel: realloc error: Resource temporarily unavailable
xsel: realloc error: Resource temporarily unavailable
xsel: realloc error: Resource temporarily unavailable
xsel: realloc error: Resource temporarily unavailable
xsel: realloc error: Resource temporarily unavailable
```

This issue affects every app I try to run, not just the desktop environment. For example, when I run sudo enter-chroot xiwi xterm, the display is all white and doesn't refresh until I move the window. When I do move the window, the text refreshes but is light and hard to read against the white background.

**Comment by harmalkar** [comment]
Issue went away after restarting my chromebook a few times

**Comment by grde1988** [comment]
@dnschneid @harmalkar Hello, sorry to drag this out but I am running into this issue for the second time. It always seems to happen when I present my Crouton application while "sharing a window" in Google Meet. The problem has same visual symptoms as mentioned above and is persistent even though I restart my pixelbook and or remove and reinstall the Chrome Crouton Extension. Please advise. The very odd thing is the only way to properly view my display is by viewing it through a shared window on Google Meet. See below screenshot for reference. 


![Screenshot 2021-12-11 10 13 00 PM](https://user-images.githubusercontent.com/13649045/145691846-09111167-7915-4ec1-bd02-cd3d07f25551.png)

**Comment by grde1988** [comment]
Another update, I tired reinstalling xiwi via:

`sudo sh /usr/local/bin/crouton -t xiwi -u -n xenial`

but the visual issues persist. Any suggestions?

**Comment by grde1988** [comment]
Last update: I forced a ChromeOS by changing to dev channel. Now I'm stuck here because changing back to Sable or Beta will require a Powerwash >:-\

I will definitely avoid presenting with Google Meet from now on.

**Comment by DennisLfromGA** [comment]
@grde1988,

If you're avoiding a powerwash due to a crouton chroot be aware that  '`crouton`' has both backup & restore options.

*Hope this helps,*
-**DennisLfromGA*

**Comment by Apocalypse10110** [comment]
I have the same issue. Should I go into the dev channel or wait until a new Chromebook update? I know I am responding to 3 year old comment, but I hope you'll still be able to help me. Thanks.

**Comment by grde1988** [comment]
No, don't go dev. I still had the same problem even when using the dev
branch. When you say you are having the same issue, you mean graphic issues
on a google pixelbook or other chromebook. I still have the problem and it
made it impossible to work with crouton. I believe it has to do with the
chromebook updates, something needs to be updates for the newer versions
