### ISSUE TITLE
Is it possible to launch unity xorg in a chrome tab?

### ISSUE THREAD

**Issue by maxsalibe** [dnschneid/crouton#4576]
```
**Please paste the output of the following command here: sudo edit-chroot -all**
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210817115015~master:d607c558
release: xenial
architecture: amd64
xmethod: xiwi
targets: unity,xiwi,extension,xorg
host: version 13982.82.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.190-11780-g9abe9eac8155 #1 SMP PREEMPT Wed Aug 11 19:47:26 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**#### Please describe your issue:**
I tried entering this command `sudo startunity -X xorg-tab` and it opened in a brand new desktop instead of in a new chrome tab as I expected.

**Comment by DennisLfromGA** [comment]
Nope, see my response in your other post linked below -
- https://github.com/dnschneid/crouton/issues/4436#issuecomment-900748182

-**DennisLfromGA**
