### ISSUE TITLE
how to fix xiwi scrolling?

### ISSUE THREAD

**Issue by Arvin2A** [dnschneid/crouton#4578]
sudo edit-chroot -all 
kali

My Problem is in a xiwi server (i knew this before) that my scrolling is not working and also this error when i add touch command
"touch is not available in debian"
audio is working after all; and when i look at connected devices it show no mouse,touchpad

**Comment by dkni1029** [comment]
Me too have had problems with mouse & two-finger scrolling in xiwi and it has been months that I have to use xorg for crouton. I like xiwi and I really hope that I can continue to use it. It was reported that Chrome 89.0.4389.95 brought it back momentarily, but shortly after that, 90.0.4430.86 again made scrolling impossible in xiwi.

**Comment by dkni1029** [comment]
> sudo edit-chroot -all
> kali
> 
> My Problem is in a xiwi server (i knew this before) that my scrolling is not working and also this error when i add touch command
> "touch is not available in debian"
> audio is working after all; and when i look at connected devices it show no mouse,touchpad

A quick search told me that there has been a work-around for this. Just set AutoAddDevices to true in /etc/X11/xorg-dummy.conf

https://github.com/dnschneid/crouton/issues/4448#issuecomment-834069293
