### ISSUE TITLE
Update ubuntu 16.04 LTE on an HP Chromebook x360 14c

### ISSUE THREAD

**Issue by maxsalibe** [dnschneid/crouton#4579]
#### Please paste the output of the following command here: `sudo edit-chroot -all`   
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210817115015~master:d607c558
release: xenial
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,unity,extension
host: version 13982.82.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.190-11780-g9abe9eac8155 #1 SMP PREEMPT Wed Aug 11 19:47:26 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it.
```

#### Please describe your issue:
I need to update ubuntu, if possible, in order to have a better appearance performance while using Eclipse IDE.
I use crouton with xenial unity xiwi and xorg.

**Comment by DennisLfromGA** [comment]
@maxsalibe,

> I need to update ubuntu, if possible, in order to have a better appearance performance while using Eclipse IDE.

You can update your crouton chroot and all packages within with the command: 
- `sudo crouton -u -n [CHROOTNAME]`  

And you can update *just* the chroots's packages with the commands:   
1. `sudo enter-chroot`   
2. `sudo apt update && sudo apt upgrade`   

But if you mean upgrade the *release*, like from 'xenial' to 'focal' then it's usually *always* better to install a new chroot with the release you want instead of trying to do a release-upgrade since they are *very* problematic.

*Hope this helps,*
-**DennisLfromGA**

**Comment by maxsalibe** [comment]
I don't know exactly what it is better: I've just noticed that many people
have Ubuntu 20 and mine is 16. In addition to this, I see my Eclipse
interface more ugly than others'.

My current chroot is Xenial. And, when I get into the system settings of
the Linux desktop, it says Ubuntu 16.04 LTE.

**Comment by DennisLfromGA** [comment]
@maxsalibe,

You are using 'xenial (Ubuntu 16)' as evidenced by your `edit-chroot` display above.

'Ubuntu 16.04 LTE' (I think you mean **LTS**), as it denotes, has **L**ong **T**erm **S**upport and has an end-of-life of April 2024 so it's still good for a while. It could be that the Eclipse package for the 'xenial' release is not very appealing. It might be more so in a later release like 'bionic' or 'focal' but I don't know, that's just conjecture. 

I would suggest installing the Eclipse package on a crouton 'bionic (Ubuntu 18)' and/or 'focal (Ubuntu 20)' chroot to see if its appearance is improved.  

*Hope this helps,*
-**DennisLfromGA**

**Comment by maxsalibe** [comment]
I tried to install bionic with this command:
***@***.*** / $ sudo crouton -r bionic,focal -t extension,xiwi,xorg
Now, how do I launch it?

**Comment by maxsalibe** [comment]
I'm sorry, that didn't work, so I tried:
***@***.*** / $ sudo crouton -r bionic -t extension,xiwi,xorg
I think this worked, but now I don't know how to launch it.
Could you please tell me how?

**Comment by DennisLfromGA** [comment]
@maxsalibe,

You use crouton's '`-n [NAME]`' option to specify the chroot's name.

Since you didn't install any desktop targets you can only get a terminal session with: -  
- `sudo enter-chroot -n bionic`  

If you want to add desktop targets to it do so with crouton's '`-u`' update option, something like:  
- sudo crotuon -n bionic -t lxde-desktop -u`  

Of course, specify the desktop(s) of your preference.

*Hope this helps,*
-**DennisLfromGA**

**Comment by JasonYubini** [comment]
I always install first xenial, and then, update ubuntu. This is how I update from xenial to bionic.
Try to update with these commands:

sudo enter-chroot -n xenial
sudo apt-get install update-manager-core python-apt
sudo do-release-upgrade

After updating, rename the chroot with:

sudo edit-chroot xenial -m bionic

I always use this method and this always worked for me.

**Comment by maxsalibe** [comment]
> I always install first xenial, and then, update ubuntu. This is how I update from xenial to bionic.
> Try to update with these commands:
> 
> sudo enter-chroot -n xenial
> sudo apt-get install update-manager-core python-apt
> sudo do-release-upgrade
> 
> After updating, rename the chroot with:
> 
> sudo edit-chroot xenial -m bionic
> 
> I always use this method and this always worked for me.
> 
> But with unity desktop, I get graphical bugs. I always install xfce

Is that -m ok in sudo edit-chroot xenial -m bionic ?
And have you tried this configuration using Eclipse IDE?

**Comment by DennisLfromGA** [comment]
@maxsalibe,

> Is that -m ok in sudo edit-chroot xenial -m bionic ?

Yes, it's often good to look at the usage of the commands you're using before using them or asking questions.
Here's the `edit-chroot` '`-m`' option explained:
```
-m DEST         Moves a chroot. Specify a new name to keep it in the same
                directory, or an absolute path to move it entirely.
                DEST can be a directory, in which case it must end in a slash.
                If multiple chroots are specified, DEST must be a directory.
                If you are moving a chroot to a SD card/USB drive, make sure the
                storage is formatted to ext2/3/4.
```

*Hope this helps,*
-**DennisLfromGA**
