### ISSUE TITLE
Hi, I need help. I'm trying to install kodi with chroot.

### ISSUE THREAD

**Issue by ColeWebber06** [dnschneid/crouton#4584]
Hi, can someone give me a step by step exact tutorial on how to install kodi with a chroot. It keeps giving me this error:

"Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md"

I am following this tutorial that isn't working:
https://forum.kodi.tv/showthread.php?tid=320808

**Comment by BetaPictoris** [comment]
@ColeWebber06 make sure you are using an up-to-date guide, it would appear you haven't installed it yet with `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`.

**Comment by ColeWebber06** [comment]
I can't find any other good ones

**Comment by ColeWebber06** [comment]
> @ColeWebber06 make sure you are using an up-to-date guide, it would appear you haven't installed it yet with `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`.

I copied that script in but it didnt do anything

**Comment by BetaPictoris** [comment]
> > @ColeWebber06 make sure you are using an up-to-date guide, it would appear you haven't installed it yet with `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`.
> 
> I copied that script in but it didnt do anything

Can you do `sudo crouton` now?
