### ISSUE TITLE
Launching crouton takes me to an Ubuntu version I didn't specify, and there are several small and inaccessible volumes

### ISSUE THREAD

**Issue by TLG8263** [dnschneid/crouton#4587]
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210817115015~master:d607c558
release: xenial
architecture: amd64
xmethod: xorg
targets: unity
host: version 13816.82.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.254-36964-g86d266acc51a #1 SMP PREEMPT Thu May 13 22:06:58 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

```

I have successfully got crouton to run, but I did not get my preferred version, 20.04. I attempted to run crouton -r list, but the results in my eyes were just gibberish. There were a lot of random words under "Recognized Ubuntu releases," but they were all marked with either a ! or a *, so I didn't feel safe installing any of them. Even then, I don't know which one is right.

Additionally, launching Ubuntu just feels off. I have about 10 different partitions in the file browser, and I can't access most of them. Attempting to install Firefox results in nothing, as nothing actually starts to download using the normal method. It all just feels wrong in some way.

I do not know what led to this. I followed the tutorial as closely as possible, with these commands in order:

sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton

sudo crouton -t unity

sudo crouton

sudo startunity

What have I done wrong, and what needs to be done to make crouton run a standard Ubuntu 20.04 release?

**Comment by TLG8263** [comment]
> If you want a chroot with the 20.04 / focal release and the Unity desktop then enter:
> 
> * `sudo crouton -r focal -t unity`
> 
> Even though bionic, focal, and some other releases are not supported they may install and work for you.
> I've never had good luck with the Unity desktop, I prefer xfce4 or lxde but that's up to you.
> 
> _Hope this helps,_
> -**DennisLfromGA**

Attempting to run the chroot using 'sudo startunity' after 'sudo crouton -r focal -t unity' just takes me to a black screen, and then back to Chrome OS. I attempted to install 20.04 with that command, but I replaced 'unity' with 'xfce4' and 'lxde' on 2 separate occasions. I didn't get 'xfce4' to work, but I did get 'lxde' to work somewhat. I know very little about Linux, but it almost looks like 'sudo startlxde' runs some version of Debian. I can't identify the version, but the Start Menu equivalent is a logo I can't recognize, and clicking on it gives me a Debian option. Any idea what went wrong?

I read the README again, in more detail. I understood very little, mostly just that the extension provides clipboard syncing between the OSes and how to install the basic xfce4 Ubuntu 16.04 version.

**Comment by DennisLfromGA** [comment]
@TLG8263,

> Attempting to run the chroot using 'sudo startunity' after 'sudo crouton -r focal -t unity' just takes me to a black screen, and then back to Chrome OS

Try adding the 'xiwi' target to your chroot and using it. That may get you passed the black screen.

> I didn't get 'xfce4' to work, but I did get 'lxde' to work somewhat. I know very little about Linux, but it almost looks like 'sudo startlxde' runs some version of Debian.

Ubuntu *is* a version of Debian but it may just be that you're unfamiliar with the lxde desktop.
There are many other desktop targets to try like kde, gnome, etc. you can add and try as many as you like.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TLG8263** [comment]
@DennisLfromGA
 
> Try adding the 'xiwi' target to your chroot and using it. That may get you passed the black screen.

I did that with gnome first as it's my preferred GUI, and then unity. Neither worked, both of them had the same effect; a black screen. The only difference is the prompt about exiting fullscreen mode. I could not come up with anything that could remedy it.

**Comment by DennisLfromGA** [comment]
@TLG8263,

Concerning the 'black screen' issue, I just heard from another user with this issue and this method worked for them:

>  I just got the black screen. But then I started randomly moving the cursor around, and when it got to the top of the screen, there was an "X" there. i clicked it then bionic started.

Couldn't hurt to try that workaround.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TLG8263** [comment]
@DennisLfromGA

> > I just got the black screen. But then I started randomly moving the cursor around, and when it got to the top of the screen, there was an "X" there. i clicked it then bionic started.

Unfortunately, that doesn't work either. Not with unity or gnome. With gnome the X did appear, but the chroot closed shortly after I clicked it.

**Comment by trebante** [comment]
@TLG8263 That happened to me as well with Debian................
