### ISSUE TITLE
Bionic touchpad doesn't work within an X server

### ISSUE THREAD

**Issue by Arvin2A** [dnschneid/crouton#4588]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20210817115015~master:d607c558
release: bionic
architecture: amd64
xmethod: xorg
targets: xorg,lxde,core
host: version 13982.88.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.232-17774-gdfbdec1b1a0b #1 SMP PREEMPT Fri Aug 20 16:42:07 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
I just fixed the xorg within bionic install failure error but when i install bionic with xorg my cursor cant move unless if i just tap all the time is there any ideas?

#### If known, describe the steps to reproduce the issue:
sudo crouton -r bionic -t core

sudo crouton -r bionic -t xorg,lxde -u

**Comment by BetaPictoris** [comment]
Possible duplicate of #4546.
