### ISSUE TITLE
sh: 0: Can't open startxfce4

### ISSUE THREAD

**Issue by GiddyLinux** [dnschneid/crouton#4589]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost ~ $ sudo edit-chroot -all
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
/usr/local/bin/enter-chroot: 511: /usr/local/bin/enter-chroot: cannot create /var/run/crouton/mnt/stateful_partition/crouton/chroots/kali-rolling/etc/crouton/name: Directory nonexistent
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
chronos@localhost ~ $ 
#### Please describe your issue:
Yesterday I made a chroot on a micro sd

Upon going to the install location (/media/removable/SD Card) and running sudo sh startxfce4

it returns

sh: 0: Can't open startxfce4

help on this matter would be appreciated

**Comment by BetaPictoris** [comment]
Did you try `sudo startxfce4`, with no `sh`? Are you also 100% sure you specified the `xfce` target?

**Comment by DennisLfromGA** [comment]
@GiddyLinux,

It appears that the chroot is having trouble writing to the device:   
> /usr/local/bin/enter-chroot: cannot create

I find it easier to first install and setup the chroot on internal storage and when everything is up and running move it or copy it to external media.

*Hope this helps,*
-**DennisLfromGA**
