### ISSUE TITLE
Add a Debian -r bookworm 

### ISSUE THREAD

**Issue by pevsner** [dnschneid/crouton#4590]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
Any chance of adding Debian bookworm release.
Thank you.

#### If known, describe the steps to reproduce the issue:
# #

**Comment by BetaPictoris** [comment]
Is there even a build of bookworm out? I don't think you would want to build it on hardware that is as low powered as a Chromebook...

**Comment by pevsner** [comment]
Much appreciated.
