### ISSUE TITLE
Bullseye not installing on ARM64 chromebook

### ISSUE THREAD

**Issue by krome-3k** [dnschneid/crouton#4591]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue: Bullseye not installing on ARM64 chromebook

sudo crouton -r bullseye -t audio,extension,gnome,gtk-extra,keyboard,xorg ends in the screenshot.

![Screenshot 2021-09-06 3 35 55 AM](https://user-images.githubusercontent.com/89704836/132142695-484fa08c-ee27-47ab-981a-1d0ee523e4e9.png)

Please help.

**Comment by BetaPictoris** [comment]
Duplicate of #4389

**Comment by DennisLfromGA** [comment]
Closing. Please track the above issue for further details.

-**DennisLfromGA**

**Comment by krome-3k** [comment]
Okay
