### ISSUE TITLE
Sound Driver not working on Focal Fossa

### ISSUE THREAD

**Issue by Shreyas-PC** [dnschneid/crouton#4592]
```

#### Please describe your issue:
Sound is not working on focal 20.04

**Comment by BetaPictoris** [comment]
Do you have any of the following that you could give? 
 - Logs
 - Version numbers
 - Detailed description 
 - System information

It might be a long shot but you could try using PulseAudio like so:
```
sudo apt install pulseaudio
pulseaudio -k
pulseaudio -D
```

**Comment by Pekay-Tab** [comment]
Fixed the no driver issue but no audio actually comes out of the speakers
