### ISSUE TITLE
/tmp is not exec

### ISSUE THREAD

**Issue by octopusnz** [dnschneid/crouton#4594]
Running ChromeOS: 92.0.4515.162 
/tmp is no longer mounted as executable? Sad times.
I get: /usr/local/bin/crouton: 99: .: Refusing to exec /tmp/crouton.qMN/installer/main.sh from noexec mount;
After running sudo crouton -u -n chrootname

Such Steps:
Downloaded latest crouton (Sept 2021)
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
sudo crouton -u -n chrootname
Got error.

**Comment by DennisLfromGA** [comment]
@octopusnz,

Please make sure you have the [latest version of crouton](https://goo.gl/fd3zc) downloaded and installed.
The crouton devs have allowed for the noexec mounts in later versions of the [installer](https://github.com/dnschneid/crouton/blob/master/installer/crouton#L74):
```
CACHEDIR="/tmp/${0##*/}-installer-cache"
...
# Ensure the cache directory is marked as exec. For reasoning, see:
# https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
if ! mountpoint -q "$CACHEDIR"; then
    if ! mount --bind "$CACHEDIR" "$CACHEDIR" \
            || ! mount -o remount,exec "$CACHEDIR"; then
        echo "Unable to change permissions of the cache directory." >&2
    fi
fi
```
I just now installed a bionic chroot and didn't have *any* issues at all.

*Hope this helps,*
-**DennisLfromGA**

**Comment by octopusnz** [comment]
@DennisLfromGA Hmm, yes thanks for prompting me to check. I must have somehow grabbed an old version. The latest version does indeed remount tmp with exec. This seems all good - user error.
