### ISSUE TITLE
Lenovo Flex 5i opens ubuntu to black screen.

### ISSUE THREAD

**Issue by kwjorders** [dnschneid/crouton#4598]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210907212903~master:9b281df5
release: xenial
architecture: amd64
xmethod: xorg
targets: touch,kde
host: version 13904.77.0 (Official Build) stable-channel volteer 
kernel: Linux localhost 5.4.109-26094-g381754fbb430 #1 SMP PREEMPT Sun Jun 27 22:37:02 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I followed the tutorial once doing the xfce but got a black screen with a white cursor on it in the top left when I switched over to Ubuntu and none of the keys or buttons work,
I restarted over in developer mode and this time used KDE but ran into the same issue.
I also tried to uninstall using the evil chroot command but that did not work either.
I used command sudo startkde.
Not sure what else to try so posting here any help would be appreciated.
-Thanks

**Comment by kwjorders** [comment]
Forgot to add I ran though the troubleshooting steps and updated the crouton download but still have the same error.

**Comment by trebante** [comment]
For me KDE is not installing at all, and I get the same black screen with Debian bullseye. Just to be clear— Focal is the latest version of Ubuntu?
