### ISSUE TITLE
Starting GUI apps or xfce4 desktop breaks HDMI audio output for the entire Chrome OS until complete reboot.

### ISSUE THREAD

**Issue by ZZZXXX0110** [dnschneid/crouton#4605]
```
name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
crouton: version 1-20210907212903~master:9b281df5
release: focal
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi,extension,audio,core,gtk-extra,x11,gnome-desktop
host: version 13904.97.0 (Official Build) stable-channel rammus 
kernel: Linux localhost 4.19.190-brunch-sebanc #1 SMP PREEMPT Sat May 29 11:09:53 CEST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:

Launching VLC, Discord, or Firefox with Sommelier, or to start xfce4 desktop (without Sommelier) using "sudo startxfce4 -b" would completely break HDMI audio output for the entire Chrome OS (no HDMI audio in Android apps and Chrome OS native webapps at all) about 10 seconds after Crouton apps or desktop launches. Audio output through built in speaker or bluetooth headphones work fine. Only comeplete reboot would fix HDMI audio output, "chrome://restart" or log out and log back in do not fix it.

**Comment by BetaPictoris** [comment]
So considering the apps you listed all use audio, could you try launching another app that uses audio (ie. launching Chromium and playing a YouTube video)? It would also be helpful to know if it only happens with using Focal.
