### ISSUE TITLE
Is there a way to edit the install script to remove unwanted targets?

### ISSUE THREAD

**Issue by sanrobin** [dnschneid/crouton#4609]
```
name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
crouton: version 1-20210907212903~master:9b281df5
release: focal
architecture: amd64
xmethod: xorg
targets: xorg,audio,core,gtk-extra,x11,gnome-desktop,kde-desktop
host: version 14092.57.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.239-18064-g098890c16791 #1 SMP PREEMPT Mon Sep 13 22:44:36 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/focal...
```
#### Please describe your issue: 

Well,I wanted to install Focal but I used the same code I used for Xenial (sudo crouton -r focal -t xorg,audio,core,gtk-extra,x11,kde-desktop) just adding -r focal but KDE runtime was not found. I didnt wanted to reinstall from start and install another environment(i choose GNOME) but that kde runtime is a major roadblock to me. Is there a way to edit the install script to get rid of KDE?

#### If known, describe the steps to reproduce the issue:
1. Try to install Focal with this command:sudo crouton -r focal -t xorg,audio,core,gtk-extra,x11,kde-desktop .
2. After getting error, run sudo crouton -r focal -t xorg,audio,core,gtk-extra,x11,gnome-desktop -u
3. Thats it.

**Comment by sanrobin** [comment]
EDIT: I was able to get the prepare.sh but if i edit it crouto just deletes it and says it is invalid. But even though I am reinstalling, I just wanted to know that is there even another path.

**Comment by DennisLfromGA** [comment]
@sanrobin 

There are two files that contain the crouton targets:
```
ls -l /.crouton-targets /etc/crouton/targets 
-rw-------. 1 root root 143 Sep  1 14:43 /.crouton-targets
-rw-r--r--. 1 root root  75 Sep  1 14:43 /etc/crouton/targets
```
You can edit those two target files and remove the 'kde-desktop' target, once the 'kde-desktop' is removed you can do a crouton update and they won't be reinstalled.  Then remove or purge the kde packages from your chroot.

*Hope this helps,*
-**DennisLfromGA**
