### ISSUE TITLE
!¡!¡!¡!crosh dont want to open crouton, help please!!¡!¡!¡!

### ISSUE THREAD

**Issue by Prekestol** [dnschneid/crouton#4612]
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

**Comment by BetaPictoris** [comment]
You have provided nearly any information on your issue, although it seems that you didn't see [this](https://github.com/dnschneid/crouton#the-easy-way-assuming-you-want-an-ubuntu-lts-with-xfce) part of the readme.

Possible duplicate of: #4026,  #4385, and #4289.

**Comment by Prekestol** [comment]
i have crouton, and i can open it now, but i cant open anything besides home

**Comment by DutchCrafter09** [comment]
do ```sudo cp ~/Downloads/crouton /usr/local``` and then ```sudo sh /usr/local/crouton -t chrootname```

**Comment by DennisLfromGA** [comment]
@DutchCrafter09 

While that *may* work it is not the recommended way to install & run crouton.
See the link that @BetaPictoris posted in their reply above using the `install` command.

*Hope this helps,*
-**DennisLfromGA**
