### ISSUE TITLE
so close, yet so far.. <3

### ISSUE THREAD

**Issue by trollanomix** [dnschneid/crouton#4621]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
ERROR: Command not found.
#### Please describe your issue:
first post ever, so dont burn me too much.. 

hello, community. Trying to turn my dumpster fire of a chromebook into a linux distro. following this https://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook guide.. i have gotten ALL the way down to " mkdir root "

i get 
" mkdir: cannot create directory 'root': File exists "

their isnt any troubleshooting that i can find. so figured i would ask you super  humans.. 

much love,
Trollanomotry

#### If known, describe the steps to reproduce the issue:
![icon](https://user-images.githubusercontent.com/92754940/137796830-388d0c0a-5a83-421d-b432-6363f5475493.jpg)

![url](https://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook)

**Comment by BetaPictoris** [comment]
This guide doesn't use Crouton.
