### ISSUE TITLE
Running in chroot, ignoring command 

### ISSUE THREAD

**Issue by GiddyLinux** [dnschneid/crouton#4622]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Not relevant

#### Please describe your issue:
When I try to restart my nginx server I get this
Running in chroot, ignoring command 'restart'

#### If known, describe the steps to reproduce the issue:
Install and systemctl service and try to restart/start it

**Comment by BetaPictoris** [comment]
The `restart` command restarts the system. You are getting this message because a chroot can't be restarted.

**Comment by GiddyLinux** [comment]
> The `restart` command restarts the system. You are getting this message because a chroot can't be restarted.

Im trying to restart the service apache2 (not the actual system)

**Comment by BetaPictoris** [comment]
> > The `restart` command restarts the system. You are getting this message because a chroot can't be restarted.
> 
> Im trying to restart the service apache2 (not the actual system)

Then you need a command like `systemctl`.

**Comment by GiddyLinux** [comment]
> > > The `restart` command restarts the system. You are getting this message because a chroot can't be restarted.
> > 
> > 
> > Im trying to restart the service apache2 (not the actual system)
> 
> Then you need a command like `systemctl`.

any related commnd for example

sudo systemctl start apache2

returns

Running in chroot, ignoring command 'start'

**Comment by BetaPictoris** [comment]
You could try using the 'servicectl' tool by @smaknsk.

**Comment by MeneerJansen** [comment]
Can anybody explain why `systemctl` (from Systemd) will not work where the wrapper command `service` (from the package _init-system-helpers_) will? 

Many web pages with info/tutorials on how to configure and start/stop services in Linux requires a working `systemctl` command. It makes life very, very hard for us Crouton users. I don't understand why we can't use `systemctl`. There must be a good reason, isn't there?

**Comment by rahulonmars** [comment]
Facing the same issue.. any update on this ?

**Comment by MeneerJansen** [comment]
> Facing the same issue.. any update on this ?
Maybe something with SystemD versus Upstart (see Wikipedia). Upstart was in Ubuntu 16 which works fine in a chroot (which Croton is). Since then Ubuntu stopped using Upstart in favour of SystemD and that doesn't work well in a choot (something with rights). Crouton is dead to me. Unless they start supporting Devuan which doesn't use SytemD.

**Comment by saf1Hckr** [comment]
I am also facing the same error, anyone got any solution
