### ISSUE TITLE
I forgot the name of my chroot to enter

### ISSUE THREAD

**Issue by DutchCrafter09** [dnschneid/crouton#4623]
```
chronos@localhost / $ sudo enter-chroot debian
Entering /mnt/stateful_partition/crouton/chroots/buster...
-sh: 1: debian: not found
Unmounting /mnt/stateful_partition/crouton/chroots/buster...
```
I tried to enter my chroot like i always did, but i accidentally did ctrl + alt + forward.
I tried exiting the thing that had popped up doing ctrl + alt + backward but then i couldn't do ctrl alt shift forward to go into the chroot. 
But then it didn't work so I wanted to enter the chroot using terminal.
But then i forgor the name of the chroot.
I tried ```$sudo edit-chroot -a``` but that only brought up ```buster xenial```.
I tried both and they didnt work.

**Comment by DutchCrafter09** [comment]
I forgot to mention that I am on an ACER chromebook CB314 if that helps.

**Comment by supechicken** [comment]
I think you mean sudo enter-chroot **-c** debian

**Comment by DutchCrafter09** [comment]
```chronos@localhost / $ sudo enter-chroot -c buster
No chroots found in /buster```

**Comment by DutchCrafter09** [comment]
oh i found it
I went back to previously executed commands
it was startgnome
