### ISSUE TITLE
chroot: failed to run command '/prepare.sh': Exec format error

### ISSUE THREAD

**Issue by gitrubus** [dnschneid/crouton#4625]
```
Please paste the output of the following command here: 
name: hooi
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/hooi...
crouton: version 1-20210907212903~master:9b281df5
release: xenial
architecture: armhf
xmethod: xorg
targets: xfce
host: version 14318.0.0 (Official Build) dev-channel hana 
kernel: Linux localhost 4.19.214-12482-gdc2e95317dfe #1 SMP PREEMPT Mon Nov 1 04:01:03 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/hooi...
name: kali-rolling
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...
crouton: version 1-20210907212903~master:9b281df5
release: kali-rolling
architecture: arm64
targets: xfce
host: version 14318.0.0 (Official Build) dev-channel hana 
kernel: Linux localhost 4.19.214-12482-gdc2e95317dfe #1 SMP PREEMPT Mon Nov 1 04:01:03 PDT 2021 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...
name: ubuntuo
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/ubuntuo...
chroot: failed to run command '/usr/local/bin/croutonversion': Exec format error
Unmounting /mnt/stateful_partition/crouton/chroots/ubuntuo...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20210907212903~master:9b281df5
release: xenial
architecture: arm64
xmethod: xorg
targets: xfce
host: version 14318.0.0 (Official Build) dev-channel hana 
kernel: Linux localhost 4.19.214-12482-gdc2e95317dfe #1 SMP PREEMPT Mon Nov 1 04:01:03 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
name: xog
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xog...
chroot: failed to run command '/usr/local/bin/croutonversion': Exec format error
Unmounting /mnt/stateful_partition/crouton/chroots/xog...
chronos@localhost / $ ```

im having a hard Time getting the amd64 architecture on my Chromebook.  can you please help.

**Comment by BetaPictoris** [comment]
Your Chrome uses the `arm64` architecture, not the `x86_64` architecture.

**Comment by gitrubus** [comment]
But doesn't amd64 run on arm64

**Comment by gitrubus** [comment]
but also how do you fix  this error?

**Comment by BetaPictoris** [comment]
`Exec format error` means that the program you are trying to run doesn't support your computer, most of the time this has to do with architecture. 


> But doesn't amd64 run on arm64

No, the architecture can not be changed, without hardware changes (ie. new motherboard and CPU).

**Comment by DennisLfromGA** [comment]
@gitrubus,

You show 3 different crouton chroots above, namely 'and', 'hooi', and 'xenial'.
The 'Exec format error' you're getting on your 'amd' chroot I suspect is because it didn't install completely and/or successfully. 
I would try to update that chrroot to see if it can be fixed with:
- sudo crouton -n amd -u

*Hope this helps,*
-**DennisLfromGA**

**Comment by gitrubus** [comment]
i removed the AMD chroot it's replaced with ubuntuo

**Comment by gitrubus** [comment]
`/usr/local/chroots/ubuntuo already exists; updating it...
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
chroot: failed to run command '/prepare.sh': Exec format error
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/ubuntuo...`

it did not work :(

**Comment by gitrubus** [comment]
so im gonna buy a new chromebook
