### ISSUE TITLE
Cras error when installing bookworm?

### ISSUE THREAD

**Issue by mcdinosaur** [dnschneid/crouton#4626]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bookworm
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bookworm...
crouton: version 1-20210907212903~master:9b281df5
release: bookworm
architecture: amd64
targets: xfce
host: version 13597.105.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.204-16731-gb869cbdcd220 #1 SMP PREEMPT Sun Feb 28 21:01:03 PST 2021 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bookworm...
#### Please describe your issue:
When I try to install debian bookworm it comes up with [This](https://pastebin.com/clone/TCHCM8tT) cras error. I have tried install bookworm on chrome os 88 and 94 so I don't know what to do 

#### If known, describe the steps to reproduce the issue:
Install bookworm

Sudo crouton -r bookworm -t xfce

**Comment by pevsner** [comment]
I received  the same error output when updating `sudo crouton -u -n bookworm` after the latest chrome os update 
(94.0.4606.124).  Previously it had run smoothly and updated without errors..

Everything appears, however, to be still working fine, including audio (I use alsa, no pulseaudio) and sommelier.

 `name: bookworm
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bookworm...
crouton: version 1-20210907212903~master:9b281df5
release: bookworm
architecture: amd64
xmethod: xorg
targets: x11,extension,keyboard,core,audio,cli-extra
host: version 14150.87.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.243-18084-g7bc10658733d #1 SMP PREEMPT Tue Nov 9 14:20:16 PST 2021 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bookworm...`

**Comment by DennisLfromGA** [comment]
Refer to:
- #4450 
- #4618
