### ISSUE TITLE
Install Ubuntu in Samsung Chromebook Go

### ISSUE THREAD

**Issue by alessandriLuca** [dnschneid/crouton#4627]
```
chronos@localhost / $ sudo edit-chroot -all
name: linuxprova1
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/linuxprova1...
crouton: version 1-20210907212903~master:9b281df5
release: xenial
architecture: amd64
xmethod: xorg
targets: kde-desktop
host: version 14150.75.0 (Official Build) stable-channel dedede 
kernel: Linux localhost 5.4.139-16311-g330b3df0010b #1 SMP PREEMPT Thu Oct 28 21:20:05 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/linuxprova1...```

#### Please describe your issue:
Im able to install linux using crouton but i can start the GUI. I also tried with different -t version, gnome, unity and the result is always the same. Might be driver problem? 

#### If known, describe the steps to reproduce the issue:
Entering /mnt/stateful_partition/crouton/chroots/linuxprova1...
sudo startkde
X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
Current Operating System: Linux localhost 5.4.139-16311-g330b3df0010b #1 SMP PREEMPT Thu Oct 28 21:20:05 PDT 2021 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5836800 verity payload=PARTUUID=af790f93-60f0-4c95-96d8-b14d9d337873/PARTNROFF=1 hashtree=PARTUUID=af790f93-60f0-4c95-96d8-b14d9d337873/PARTNROFF=1 hashstart=5836800 alg=sha256 root_hexdigest=84c17cf2a215c89888adc22377a72d7e70b2f9d0bac6463a60836049910ab305 salt=3c3dce2021410e9951cae472322dee5578cdadd4b232f42dd3f8ec79fc46781e" noinitrd vt.global_cursor_default=0 kern_guid=af790f93-60f0-4c95-96d8-b14d9d337873 add_efi_memmap boot=local noresume noswap i915.modeset=1 i915.enable_guc=2 intel_pmc_core.warn_on_s0ix_failures=1  
Build Date: 08 April 2021  01:52:21PM
xorg-server 2:1.18.4-0ubuntu0.12 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/lucastormreig/.local/share/xorg/Xorg.1.log", Time: Sat Nov 13 09:43:20 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/lucastormreig/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/linuxprova1


Here is the complete log 

cat /home/lucastormreig/.local/share/xorg/Xorg.1.log
[ 10432.214] 
X.Org X Server 1.18.4
Release Date: 2016-07-19
[ 10432.214] X Protocol Version 11, Revision 0
[ 10432.214] Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
[ 10432.214] Current Operating System: Linux localhost 5.4.139-16311-g330b3df0010b #1 SMP PREEMPT Thu Oct 28 21:20:05 PDT 2021 x86_64
[ 10432.214] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5836800 verity payload=PARTUUID=af790f93-60f0-4c95-96d8-b14d9d337873/PARTNROFF=1 hashtree=PARTUUID=af790f93-60f0-4c95-96d8-b14d9d337873/PARTNROFF=1 hashstart=5836800 alg=sha256 root_hexdigest=84c17cf2a215c89888adc22377a72d7e70b2f9d0bac6463a60836049910ab305 salt=3c3dce2021410e9951cae472322dee5578cdadd4b232f42dd3f8ec79fc46781e" noinitrd vt.global_cursor_default=0 kern_guid=af790f93-60f0-4c95-96d8-b14d9d337873 add_efi_memmap boot=local noresume noswap i915.modeset=1 i915.enable_guc=2 intel_pmc_core.warn_on_s0ix_failures=1  
[ 10432.214] Build Date: 08 April 2021  01:52:21PM
[ 10432.214] xorg-server 2:1.18.4-0ubuntu0.12 (For technical support please see http://www.ubuntu.com/support) 
[ 10432.214] Current version of pixman: 0.33.6
[ 10432.214]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[ 10432.214] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 10432.214] (==) Log file: "/home/lucastormreig/.local/share/xorg/Xorg.1.log", Time: Sat Nov 13 09:43:20 2021
[ 10432.215] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 10432.218] (==) No Layout section.  Using the first Screen section.
[ 10432.218] (==) No screen section available. Using defaults.
[ 10432.218] (**) |-->Screen "Default Screen Section" (0)
[ 10432.218] (**) |   |-->Monitor "<default monitor>"
[ 10432.219] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[ 10432.219] (==) Automatically adding devices
[ 10432.219] (==) Automatically enabling devices
[ 10432.219] (==) Automatically adding GPU devices
[ 10432.219] (==) Max clients allowed: 256, resource mask: 0x1fffff
[ 10432.219] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[ 10432.220]    Entry deleted from font path.
[ 10432.220] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[ 10432.220]    Entry deleted from font path.
[ 10432.220] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[ 10432.220]    Entry deleted from font path.
[ 10432.220] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[ 10432.220]    Entry deleted from font path.
[ 10432.220] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[ 10432.220]    Entry deleted from font path.
[ 10432.220] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/Type1,
        built-ins
[ 10432.220] (==) ModulePath set to "/usr/lib/x86_64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[ 10432.220] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[ 10432.220] (II) Loader magic: 0x5ca51d15adc0
[ 10432.220] (II) Module ABI versions:
[ 10432.220]    X.Org ANSI C Emulation: 0.4
[ 10432.220]    X.Org Video Driver: 20.0
[ 10432.220]    X.Org XInput driver : 22.1
[ 10432.220]    X.Org Server Extension : 9.0
[ 10432.239] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[ 10432.240] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 10432.240] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 10432.240] (II) config/udev: Ignoring already known drm device (/dev/dri/card0)
[ 10432.243] (--) PCI:*(0:0:2:0) 8086:4e55:8086:2212 rev 1, Mem @ 0x90000000/16777216, 0x80000000/268435456, I/O @ 0x00001000/64, BIOS @ 0x????????/131072
[ 10432.243] (II) LoadModule: "glx"
[ 10432.246] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[ 10432.259] (II) Module glx: vendor="X.Org Foundation"
[ 10432.259]    compiled for 1.18.4, module version = 1.0.0
[ 10432.259]    ABI class: X.Org Server Extension, version 9.0
[ 10432.259] (==) AIGLX enabled
[ 10432.259] (==) Matched intel as autoconfigured driver 0
[ 10432.259] (==) Matched modesetting as autoconfigured driver 1
[ 10432.259] (==) Matched fbdev as autoconfigured driver 2
[ 10432.259] (==) Matched vesa as autoconfigured driver 3
[ 10432.259] (==) Assigned the driver to the xf86ConfigLayout
[ 10432.259] (II) LoadModule: "intel"
[ 10432.259] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[ 10432.264] (II) Module intel: vendor="X.Org Foundation"
[ 10432.264]    compiled for 1.18.4, module version = 2.99.917
[ 10432.264]    Module class: X.Org Video Driver
[ 10432.264]    ABI class: X.Org Video Driver, version 20.0
[ 10432.264] (II) LoadModule: "modesetting"
[ 10432.264] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[ 10432.265] (II) Module modesetting: vendor="X.Org Foundation"
[ 10432.265]    compiled for 1.18.4, module version = 1.18.4
[ 10432.265]    Module class: X.Org Video Driver
[ 10432.265]    ABI class: X.Org Video Driver, version 20.0
[ 10432.265] (II) LoadModule: "fbdev"
[ 10432.265] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[ 10432.266] (II) Module fbdev: vendor="X.Org Foundation"
[ 10432.266]    compiled for 1.18.1, module version = 0.4.4
[ 10432.266]    Module class: X.Org Video Driver
[ 10432.266]    ABI class: X.Org Video Driver, version 20.0
[ 10432.266] (II) LoadModule: "vesa"
[ 10432.266] (WW) Warning, couldn't open module vesa
[ 10432.266] (II) UnloadModule: "vesa"
[ 10432.266] (II) Unloading vesa
[ 10432.266] (EE) Failed to load module "vesa" (module does not exist, 0)
[ 10432.266] (==) Matched intel as autoconfigured driver 0
[ 10432.266] (==) Matched modesetting as autoconfigured driver 1
[ 10432.266] (==) Matched fbdev as autoconfigured driver 2
[ 10432.266] (==) Matched vesa as autoconfigured driver 3
[ 10432.266] (==) Assigned the driver to the xf86ConfigLayout
[ 10432.266] (II) LoadModule: "intel"
[ 10432.266] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[ 10432.266] (II) Module intel: vendor="X.Org Foundation"
[ 10432.266]    compiled for 1.18.4, module version = 2.99.917
[ 10432.266]    Module class: X.Org Video Driver
[ 10432.266]    ABI class: X.Org Video Driver, version 20.0
[ 10432.266] (II) UnloadModule: "intel"
[ 10432.266] (II) Unloading intel
[ 10432.267] (II) Failed to load module "intel" (already loaded, 23717)
[ 10432.267] (II) LoadModule: "modesetting"
[ 10432.267] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[ 10432.267] (II) Module modesetting: vendor="X.Org Foundation"
[ 10432.267]    compiled for 1.18.4, module version = 1.18.4
[ 10432.267]    Module class: X.Org Video Driver
[ 10432.267]    ABI class: X.Org Video Driver, version 20.0
[ 10432.267] (II) UnloadModule: "modesetting"
[ 10432.267] (II) Unloading modesetting
[ 10432.267] (II) Failed to load module "modesetting" (already loaded, 23717)
[ 10432.267] (II) LoadModule: "fbdev"
[ 10432.267] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[ 10432.267] (II) Module fbdev: vendor="X.Org Foundation"
[ 10432.267]    compiled for 1.18.1, module version = 0.4.4
[ 10432.267]    Module class: X.Org Video Driver
[ 10432.267]    ABI class: X.Org Video Driver, version 20.0
[ 10432.267] (II) UnloadModule: "fbdev"
[ 10432.267] (II) Unloading fbdev
[ 10432.267] (II) Failed to load module "fbdev" (already loaded, 23717)
[ 10432.267] (II) LoadModule: "vesa"
[ 10432.267] (WW) Warning, couldn't open module vesa
[ 10432.267] (II) UnloadModule: "vesa"
[ 10432.267] (II) Unloading vesa
[ 10432.267] (EE) Failed to load module "vesa" (module does not exist, 0)
[ 10432.267] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
        i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
        915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
        Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
        GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
[ 10432.267] (II) intel: Driver for Intel(R) HD Graphics: 2000-6000
[ 10432.267] (II) intel: Driver for Intel(R) Iris(TM) Graphics: 5100, 6100
[ 10432.267] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics: 5200, 6200, P6300
[ 10432.267] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[ 10432.267] (II) FBDEV: driver for framebuffer: fbdev
[ 10432.267] (EE) 
Fatal server error:
[ 10432.267] (EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
[ 10432.267] (EE) 
[ 10432.267] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[ 10432.267] (EE) Please also check the log file at "/home/lucastormreig/.local/share/xorg/Xorg.1.log" for additional information.
[ 10432.267] (EE)

**Comment by alessandriLuca** [comment]
Here are the results of lspci
lspci
00:00.0 Host bridge: Intel Corporation Device 4e22
00:02.0 VGA compatible controller: Intel Corporation Device 4e55 (rev 01)
00:04.0 Signal processing controller: Intel Corporation Device 4e03
00:08.0 System peripheral: Intel Corporation Device 4e11
00:14.0 USB controller: Intel Corporation Device 4ded (rev 01)
00:14.2 RAM memory: Intel Corporation Device 4def (rev 01)
00:14.3 Network controller: Intel Corporation Device 4df0 (rev 01)
00:14.5 SD Host controller: Intel Corporation Device 4df8 (rev 01)
00:15.0 Serial bus controller [0c80]: Intel Corporation Device 4de8 (rev 01)
00:15.1 Serial bus controller [0c80]: Intel Corporation Device 4de9 (rev 01)
00:15.2 Serial bus controller [0c80]: Intel Corporation Device 4dea (rev 01)
00:15.3 Serial bus controller [0c80]: Intel Corporation Device 4deb (rev 01)
00:19.0 Serial bus controller [0c80]: Intel Corporation Device 4dc5 (rev 01)
00:19.2 Communication controller: Intel Corporation Device 4dc7 (rev 01)
00:1a.0 SD Host controller: Intel Corporation Device 4dc4 (rev 01)
00:1e.0 Communication controller: Intel Corporation Device 4da8 (rev 01)
00:1e.2 Serial bus controller [0c80]: Intel Corporation Device 4daa (rev 01)
00:1f.0 ISA bridge: Intel Corporation Device 4d87 (rev 01)
00:1f.3 Multimedia audio controller: Intel Corporation Device 4dc8 (rev 01)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device 4da4 (rev 01)

**Comment by alessandriLuca** [comment]
UPDATE 
Apparently fixed but got another error. 
I used this code 
gpasswd -a lucastormreig tty 
and now the error is
Entering /mnt/stateful_partition/crouton/chroots/linuxprova1...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
Current Operating System: Linux localhost 5.4.139-16311-g330b3df0010b #1 SMP PREEMPT Tue Nov 9 13:32:09 PST 2021 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5836800 verity payload=PARTUUID=d9428973-b466-4eb2-b774-2b57b97df92f/PARTNROFF=1 hashtree=PARTUUID=d9428973-b466-4eb2-b774-2b57b97df92f/PARTNROFF=1 hashstart=5836800 alg=sha256 root_hexdigest=d7daa4f9ce742a188f84e1e69fac575655d178fb0466d98d8f4b460d9eb22748 salt=bd5765bea05140be28935eaa99cf7c4b696c5a2d73fcf082bad99be24b6570b5" noinitrd vt.global_cursor_default=0 kern_guid=d9428973-b466-4eb2-b774-2b57b97df92f add_efi_memmap boot=local noresume noswap i915.modeset=1 i915.enable_guc=2 intel_pmc_core.warn_on_s0ix_failures=1  
Build Date: 08 April 2021  01:52:21PM
xorg-server 2:1.18.4-0ubuntu0.12 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/lucastormreig/.local/share/xorg/Xorg.1.log", Time: Tue Nov 16 19:05:13 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open virtual console 2 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/lucastormreig/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/linuxprova1...

**Comment by alessandriLuca** [comment]
Here is the log from the previous try of sudo startkde

Entering /mnt/stateful_partition/crouton/chroots/linuxprova1...
(linuxprova1)lucastormreig@localhost:~$ cat /home/lucastormreig/.local/share/xorg/Xorg.1.log
[ 22401.229] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[ 22401.230] 
X.Org X Server 1.18.4
Release Date: 2016-07-19
[ 22401.230] X Protocol Version 11, Revision 0
[ 22401.230] Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
[ 22401.230] Current Operating System: Linux localhost 5.4.139-16311-g330b3df0010b #1 SMP PREEMPT Tue Nov 9 13:32:09 PST 2021 x86_64
[ 22401.230] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5836800 verity payload=PARTUUID=d9428973-b466-4eb2-b774-2b57b97df92f/PARTNROFF=1 hashtree=PARTUUID=d9428973-b466-4eb2-b774-2b57b97df92f/PARTNROFF=1 hashstart=5836800 alg=sha256 root_hexdigest=d7daa4f9ce742a188f84e1e69fac575655d178fb0466d98d8f4b460d9eb22748 salt=bd5765bea05140be28935eaa99cf7c4b696c5a2d73fcf082bad99be24b6570b5" noinitrd vt.global_cursor_default=0 kern_guid=d9428973-b466-4eb2-b774-2b57b97df92f add_efi_memmap boot=local noresume noswap i915.modeset=1 i915.enable_guc=2 intel_pmc_core.warn_on_s0ix_failures=1  
[ 22401.230] Build Date: 08 April 2021  01:52:21PM
[ 22401.230] xorg-server 2:1.18.4-0ubuntu0.12 (For technical support please see http://www.ubuntu.com/support) 
[ 22401.230] Current version of pixman: 0.33.6
[ 22401.230]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[ 22401.230] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 22401.230] (==) Log file: "/home/lucastormreig/.local/share/xorg/Xorg.1.log", Time: Tue Nov 16 19:05:13 2021
[ 22401.232] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 22401.235] (==) No Layout section.  Using the first Screen section.
[ 22401.235] (==) No screen section available. Using defaults.
[ 22401.235] (**) |-->Screen "Default Screen Section" (0)
[ 22401.235] (**) |   |-->Monitor "<default monitor>"
[ 22401.235] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[ 22401.235] (==) Automatically adding devices
[ 22401.235] (==) Automatically enabling devices
[ 22401.235] (==) Automatically adding GPU devices
[ 22401.235] (==) Max clients allowed: 256, resource mask: 0x1fffff
[ 22401.236] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[ 22401.236]    Entry deleted from font path.
[ 22401.236] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[ 22401.236]    Entry deleted from font path.
[ 22401.236] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[ 22401.236]    Entry deleted from font path.
[ 22401.236] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[ 22401.236]    Entry deleted from font path.
[ 22401.236] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[ 22401.236]    Entry deleted from font path.
[ 22401.236] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/Type1,
        built-ins
[ 22401.236] (==) ModulePath set to "/usr/lib/x86_64-linux-gnu/xorg/extra-modules,/usr/lib/xorg/extra-modules,/usr/lib/xorg/modules"
[ 22401.236] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[ 22401.236] (II) Loader magic: 0x57bdefff8dc0
[ 22401.236] (II) Module ABI versions:
[ 22401.236]    X.Org ANSI C Emulation: 0.4
[ 22401.236]    X.Org Video Driver: 20.0
[ 22401.236]    X.Org XInput driver : 22.1
[ 22401.236]    X.Org Server Extension : 9.0
[ 22401.237] (--) using VT number 2

[ 22401.237] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[ 22401.238] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 22401.238] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
[ 22401.238] (II) config/udev: Ignoring already known drm device (/dev/dri/card0)
[ 22401.241] (--) PCI:*(0:0:2:0) 8086:4e55:8086:2212 rev 1, Mem @ 0x90000000/16777216, 0x80000000/268435456, I/O @ 0x00001000/64, BIOS @ 0x????????/131072
[ 22401.241] (II) LoadModule: "glx"
[ 22401.246] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[ 22401.254] (II) Module glx: vendor="X.Org Foundation"
[ 22401.254]    compiled for 1.18.4, module version = 1.0.0
[ 22401.254]    ABI class: X.Org Server Extension, version 9.0
[ 22401.254] (==) AIGLX enabled
[ 22401.254] (==) Matched intel as autoconfigured driver 0
[ 22401.254] (==) Matched modesetting as autoconfigured driver 1
[ 22401.254] (==) Matched fbdev as autoconfigured driver 2
[ 22401.254] (==) Matched vesa as autoconfigured driver 3
[ 22401.254] (==) Assigned the driver to the xf86ConfigLayout
[ 22401.254] (II) LoadModule: "intel"
[ 22401.254] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[ 22401.256] (II) Module intel: vendor="X.Org Foundation"
[ 22401.256]    compiled for 1.18.4, module version = 2.99.917
[ 22401.256]    Module class: X.Org Video Driver
[ 22401.256]    ABI class: X.Org Video Driver, version 20.0
[ 22401.256] (II) LoadModule: "modesetting"
[ 22401.256] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[ 22401.256] (II) Module modesetting: vendor="X.Org Foundation"
[ 22401.256]    compiled for 1.18.4, module version = 1.18.4
[ 22401.256]    Module class: X.Org Video Driver
[ 22401.256]    ABI class: X.Org Video Driver, version 20.0
[ 22401.256] (II) LoadModule: "fbdev"
[ 22401.256] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[ 22401.257] (II) Module fbdev: vendor="X.Org Foundation"
[ 22401.257]    compiled for 1.18.1, module version = 0.4.4
[ 22401.257]    Module class: X.Org Video Driver
[ 22401.257]    ABI class: X.Org Video Driver, version 20.0
[ 22401.257] (II) LoadModule: "vesa"
[ 22401.257] (WW) Warning, couldn't open module vesa
[ 22401.257] (II) UnloadModule: "vesa"
[ 22401.257] (II) Unloading vesa
[ 22401.257] (EE) Failed to load module "vesa" (module does not exist, 0)
[ 22401.257] (==) Matched intel as autoconfigured driver 0
[ 22401.257] (==) Matched modesetting as autoconfigured driver 1
[ 22401.257] (==) Matched fbdev as autoconfigured driver 2
[ 22401.257] (==) Matched vesa as autoconfigured driver 3
[ 22401.257] (==) Assigned the driver to the xf86ConfigLayout
[ 22401.257] (II) LoadModule: "intel"
[ 22401.257] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[ 22401.257] (II) Module intel: vendor="X.Org Foundation"
[ 22401.257]    compiled for 1.18.4, module version = 2.99.917
[ 22401.257]    Module class: X.Org Video Driver
[ 22401.257]    ABI class: X.Org Video Driver, version 20.0
[ 22401.257] (II) UnloadModule: "intel"
[ 22401.257] (II) Unloading intel
[ 22401.257] (II) Failed to load module "intel" (already loaded, 22461)
[ 22401.257] (II) LoadModule: "modesetting"
[ 22401.258] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[ 22401.258] (II) Module modesetting: vendor="X.Org Foundation"
[ 22401.258]    compiled for 1.18.4, module version = 1.18.4
[ 22401.258]    Module class: X.Org Video Driver
[ 22401.258]    ABI class: X.Org Video Driver, version 20.0
[ 22401.258] (II) UnloadModule: "modesetting"
[ 22401.258] (II) Unloading modesetting
[ 22401.258] (II) Failed to load module "modesetting" (already loaded, 22461)
[ 22401.258] (II) LoadModule: "fbdev"
[ 22401.258] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[ 22401.258] (II) Module fbdev: vendor="X.Org Foundation"
[ 22401.258]    compiled for 1.18.1, module version = 0.4.4
[ 22401.258]    Module class: X.Org Video Driver
[ 22401.258]    ABI class: X.Org Video Driver, version 20.0
[ 22401.258] (II) UnloadModule: "fbdev"
[ 22401.258] (II) Unloading fbdev
[ 22401.258] (II) Failed to load module "fbdev" (already loaded, 22461)
[ 22401.258] (II) LoadModule: "vesa"
[ 22401.258] (WW) Warning, couldn't open module vesa
[ 22401.258] (II) UnloadModule: "vesa"
[ 22401.258] (II) Unloading vesa
[ 22401.258] (EE) Failed to load module "vesa" (module does not exist, 0)
[ 22401.258] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
        i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
        915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
        Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
        GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
[ 22401.258] (II) intel: Driver for Intel(R) HD Graphics: 2000-6000
[ 22401.258] (II) intel: Driver for Intel(R) Iris(TM) Graphics: 5100, 6100
[ 22401.258] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics: 5200, 6200, P6300
[ 22401.258] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[ 22401.258] (II) FBDEV: driver for framebuffer: fbdev
[ 22401.258] (EE) 
Fatal server error:
[ 22401.258] (EE) xf86OpenConsole: Cannot open virtual console 2 (Permission denied)
[ 22401.258] (EE) 
[ 22401.258] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[ 22401.259] (EE) Please also check the log file at "/home/lucastormreig/.local/share/xorg/Xorg.1.log" for additional information.
[ 22401.259] (EE) 
(linuxprova1)lucastorm

**Comment by gudhid71** [comment]
try sudo crouton -t xiwi,xfce worked for me
