### ISSUE TITLE
Cras compiler errors 

### ISSUE THREAD

**Issue by BROKENIST2** [dnschneid/crouton#4628]
```
I will post tommoroa
```

#### Please describe your issue:

Hello, I get an cras error about cras.client.5 write something with 2 and 1 and 3, I searched  the error and havent found anything that worked, please help me.

**Comment by BetaPictoris** [comment]
Please do not open multiple issues, it does not help solve the problem.

**Comment by DennisLfromGA** [comment]
Refer to:
- #4450 
- #4618
