### ISSUE TITLE
Failing to Complete Chroot Setup

### ISSUE THREAD

**Issue by marsacom** [dnschneid/crouton#4630]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
```
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version 1-20210907212903~master:9b281df5
release: kali-rolling
architecture: amd64
targets: core,xiwi,xfce,extension
host: version 14150.87.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.202-12118-g8ae2f2219bce #1 SMP PREEMPT Tue Nov 9 13:50:11 PST 2021 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
```

#### Please describe your issue:
I have been using crouton to use Kali Linux for a while. I recently decided to do a fresh install. I removed the crouton chrome extension, power washed my Chromebook, then with developer mode still enabled I tried to reinstall. The steps listed below in the last question show the EXACT steps I used. After step #6 and trying to install Kali, I am met with a ton of warnings and errors. I won't paste the entirety of it since it is a lot of text but there is a lot of this text repeated, with varieties in the files and errors.
```
In file included from libcras/cras_client.c:45:
/usr/include/unistd.h:367:16: note: in a call to function 'write' declared with attribute 'access (read_only, 2, 3)'
  367 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~"
All of the errors and warnings start after "Compiling CRAS (i386)..." when it starts to install Kali 
The last 3 lines of the window read
"cc1: all warnings being treated as errors
Failed to complete chroot setup
Unmounting /mnt/stateful_partition/crouton/chroots/kali..."
```

Then if I try to "sudo enter-chroot" I am met with...
```
Entering /mnt/stateful_partition/crouton/chroots/kali...
A chroot setup script still exists inside the chroot.
The chroot may not be fully set up.
Would you like to finish the setup? [Y/n/d]
```
If I use Y to update, I get more errors saying the setup script might be broken. I have tried all of those 6 steps I listed below at least 10 times. Reinstalling and making sure everything is up to date each time. And get the error ```UID 1000 not found in kali```

I have been looking and looking for days on this website and various other forums and websites trying to find a fix but cannot seem to find anything related to my exact issue.

#### If known, describe the steps to reproduce the issue:
1. Powerwashed my Chromebook
2. Enabled developer mode
3. Installed the crouton chrome extension and downloaded the file associated to be able to download crouton.
4. Inside the shell, I installed crouton via the following command "sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton"
5. Then launched the crouton with "sudo crouton"
6. Finally used this command to install Kali Linux, ```sudo crouton -n kali -r kali-rolling -t core,xiwi,xfce,extension```

**Comment by BetaPictoris** [comment]
See #4450.

**Comment by marsacom** [comment]
> See #4450.

I've been through that a hundred times. Even before writing my own topic. I just can't understand it. There's a hundred different things, all saying something different.

**Comment by marsacom** [comment]
> See #4450.

I have absolutely no idea how to get to that cras_client.h file. As well, when in prepare.sh those lines that the user esprout was talking about, specifically this one 
```sed -i -e 's/#define DISABLE_CFI_ICALL __attribute__((no_sanitize("cfi-icall")))/#define DISABLE_CFI_ICALL/' \
                libcras/cras_client.h```
is not there. I have absolutely no idea what to do.

**Comment by qubitter** [comment]
Do us a favor and paste the rest of the text here. The error you're getting should be identifiable, but we'll definitely need the rest of the text output to be sure. Don't worry about pasting too much - this is what GitHub is for! :)

**Comment by marsacom** [comment]
@qubitter I would but I finally figured it out! Had some help from someone in another topic # . Thank you though!
