### ISSUE TITLE
trying to put linux chroot on samsung chromebook to play Old School Runescape

### ISSUE THREAD

**Issue by MegLaRae** [dnschneid/crouton#4635]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found
chronos@localhost / $ sudo edit-chroot-all
sudo: edit-chroot-all: command not found
chronos@localhost / $ 

#### Please describe your issue:  I have been trying to be able to play Old School Runescape on my Samsung Chromebook using crouton. Every time I try to run the commands from this page https://platypusplatypus.com/chromebooks/play-runescape-chromebook/
I keep getting the output

 sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

#### If known, describe the steps to reproduce the issue: Here is the whole process that I went through...

Welcome to crosh, the Chrome OS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

If you want to customize the look/behavior, you can use the options page.
Load it by using the Ctrl-Shift-P keyboard shortcut.

crosh> shell
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
chronos@localhost / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
chronos@localhost / $ sudo edit -chroot -a
sudo: edit: command not found
chronos@localhost / $ sudo edit-chroot -a
sudo: edit-chroot: command not found
chronos@localhost / $ sudo ls /usr/local/chroots
ls: cannot access '/usr/local/chroots': No such file or directory
chronos@localhost / $ sudo crouton -n chrootname -u
Downloading latest crouton installer...
################################################################## 100.0%################################################################## 100.0%
/mnt/stateful_partition/crouton/chroots not found.
/usr/local/chroots/chrootname does not exist; cannot update.
Valid chroots:
chronos@localhost / $ sudo sh~/Downloads/crouton -r trusty -t xfce
sudo: sh~/Downloads/crouton: command not found
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
chronos@localhost / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton 
chronos@localhost / $ sudo ls /usr/local/chroots
/usr/local/chroots
chronos@localhost / $ sudo crouton -n chrootname -u
Downloading latest crouton installer...
################################################################## 100.0%################################################################## 100.0%
/mnt/stateful_partition/crouton/chroots not found.
/usr/local/chroots/chrootname does not exist; cannot update.
Valid chroots:
chronos@localhost / $ sudo edit-chroot -a
sudo: edit-chroot: command not found
chronos@localhost / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads.crouton
install: cannot stat '/home/chronos/user/Downloads.crouton': No such file or directory
chronos@localhost / $ sudo sh ~/Downloads/crouton -r trusty -t xfce
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found
chronos@localhost / $ sudo edit-chroot-all
sudo: edit-chroot-all: command not found

**Comment by DennisLfromGA** [comment]
That website and many others use the older method to install a crouton chroot.
It's always best to look at the source for changes before attempting to follow these online guides, especially one from 2016.

See below for the latest method to install a crouton chroot:
- https://github.com/dnschneid/crouton#usage

*Hope this helps,*
-**DennisLfromGA**
