### ISSUE TITLE
Possible to use crostini crossystem integrations on buster chroot?

### ISSUE THREAD

**Issue by TyTytheFurKit** [dnschneid/crouton#4640]
Crostini has that great ability to integrate GUI applications with Chrome OS as if it's running without the secure VM. If the repository for the integration packages were set up on a buster chroot, would it be possible to use the same integration features if all required packages were installed? Or is there another issue that prevents this from happening?

**Comment by supechicken** [comment]
There is a PR(#4410) that use `sommelier` (the integrated window manager used by crostini) as the window manager, which means you can run crouton apps seamlessly Chrome OS UI

However, stuff like launcher icons and notifications are not supported now (crostini is using a command called `garcon` to do it, but it only works with a verified crostini container ID)

**Comment by TyTytheFurKit** [comment]
I did some testing and, `sommelier` would not install using the `cros-guest-tools` metapackage. and then trying to install the `sommelier` package itself. I already deleted the chroot when it failed, I can try it again and give the terminal output if it'll help at all.

**Comment by TyTytheFurKit** [comment]
I'm using a just recently unsupported HP Chromebook `SETZER`.

**Comment by supechicken** [comment]
> I did some testing and, `sommelier` would not install using the `cros-guest-tools` metapackage. and then trying to install the `sommelier` package itself. I already deleted the chroot when it failed, I can try it again and give the terminal output if it'll help at all.

That package is just some symlinks linked to a place (bind-mounted from the termina VM to the Linux containers) that can only access by Crostini containers and the termina VM (/opt/google/containers/). That means those symlinks will point to invalid location when installing in crouton

**Comment by supechicken** [comment]
You need to build sommelier from source (don’t copy it from crostini, it won’t work as it use some VM related things (`/dev/wl0`) to communicate with the CrOS UI, which is unavailable on crouton)

AFAIK there is a tutorial on the wiki page about building sommelier (it works but the version of sommelier it used is outdated)

Maybe take a look of [this pull request I made in the chromebrew project](https://github.com/skycocker/chromebrew/pull/6405), it have the latest version of sommelier working with some patches
