### ISSUE TITLE
GPU acceleration broken after upgrading to focal

### ISSUE THREAD

**Issue by snowy-324** [dnschneid/crouton#4641]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
crouton: version 1-20210907212903~master:9b281df5
release: focal
architecture: amd64
xmethod: xorg
targets: keyboard,extension,xfce
host: version 14268.67.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.249-18369-g6e52abcfeab4 #1 SMP PREEMPT Sun Dec 12 20:01:44 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/focal...

#### Please describe your issue:
I have been using bionic for a while with perfectly working audio and gpu acceleration. After upgrading to focal, audio broke, but I found a fix for that. Now, the whole UI is very slow, and acceleration is no longer there. Here's the output of glxinfo -B:

name of display: :1.0
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 12.0.0, 128 bits) (0xffffffff)
    Version: 21.0.3
    Accelerated: no
    Video memory: 3806MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.0.3
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

I'm on a Samsung Chromebook 4 with Intel UHD 600 graphics btw. In the meantime I'll go back to bionic but i'd love to get acceleration on focal working

#### If known, describe the steps to reproduce the issue:
not really sure how to reproduce this. just start in a bionic chroot and upgrade to focal

**Comment by visor841** [comment]
I am having the same problem with a clean focal install. Nearly identical output from glxinfo -B

I'm on a lenovo yoga c630, with Intel UHD graphics 620.

**Comment by realsushi-official** [comment]
Thanks for pinpointing the issue, same issue display is completely laggy unusable. First install.


`name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: VMware, Inc. (0xffffffff)
    Device: llvmpipe (LLVM 6.0, 256 bits) (0xffffffff)
    Version: 18.0.5
    Accelerated: no
    Video memory: 7869MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 6.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
`
