### ISSUE TITLE
Shutting Down Chroot Problem

### ISSUE THREAD

**Issue by goodshibe20-cool** [dnschneid/crouton#4642]
I followed the easy way to run a chroot with xfce and like it a lot but a problem arose. every time now i shut down my chroot this message appears
Sending SIGKILL to processes under /mnt/stateful_partition/crouton/chroots/xenial...
and never stops
![image](https://user-images.githubusercontent.com/84594364/147103582-e422dce9-8321-43db-af0e-250bc0f45f4d.png)

**Comment by goodshibe20-cool** [comment]
update it still has not stopped
![image](https://user-images.githubusercontent.com/84594364/147134186-11f4c1df-e539-48db-97cd-a78157e3cd51.png)

**Comment by DennisLfromGA** [comment]
@goodshibe20-cool,

You may have to press <kbd>Ctrl</kbd>+<kbd>C</kbd> to break out of that process.   

You can tell what processes are running and preventing it from terminating by using the `unmount-chroot` command.
Here's the usage for it:   
```
unmount-chroot [options] name [...]

Unmounts one or more chroots, optionally killing any processes still running
inside them.

By default, it will run in interactive mode where it will ask to kill any
remaining processes if unable to unmount the chroot within 5 seconds.

Options:
    -a          Unmount all chroots in the CHROOTS directory.
    -c CHROOTS  Directory the chroots are in. Default: /usr/local/chroots
    -f          Forces a chroot to unmount, potentially breaking or killing
                other instances of the same chroot.
    -k KILL     Send the processes SIGKILL instead of SIGTERM.
    -p          Print to STDOUT the processes stopping a chroot from unmounting.
    -t TRIES    Number of seconds to try before signalling the processes.
                Use -t inf to be exceedingly patient. Default: 5
    -x          Keep the root directory of the chroot mounted.
    -y          Signal any remaining processes without confirmation.
                Automatically escalates from SIGTERM to SIGKILL.
```   
Try this to see what's running:   
- `sudo unmount-chroot -ap`   

And try this to force kill all of them:
- `sudo unmount-chroot -afpy`    

*Hope this helps,*
-**DennisLfromGA**

**Comment by goodshibe20-cool** [comment]
also my chromebook broke and just had to redo everything, so sad i lost my chroot :(
