### ISSUE TITLE
WIFI doesn't work?

### ISSUE THREAD

**Issue by TechFishe** [dnschneid/crouton#4643]
So I'm trying to install Visual Studio Code in xenial on the Unity Desktop and when I try, it exits saying that it can't download the files required because it's not connecting to the internet. Can someone help me with this? I tried to figure out how to use the Network App, but I couldn't make it work.

**Comment by DennisLfromGA** [comment]
@TechFishe,

crouton uses the Chrome OS networking processes, nothing to setup or do in the chroot.
If it downloads in Chrome OS it should also download in the chroot.

*Hope this helps,*
-**DennisLfromGA**

**Comment by TechFishe** [comment]
Huh, I didn't think that was the case. Thanks for the help and happy holidays!

**Comment by DennisLfromGA** [comment]
No problem, Happy Holidays.
