### ISSUE TITLE
Weird error while entering chroot.

### ISSUE THREAD

**Issue by yoiammaac** [dnschneid/crouton#4645]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20210907212903~master:9b281df5
release: bionic
architecture: amd64
xmethod: xorg
targets: gnome-desktop,audio,core,xorg,x11,extension,keyboard,chrome,cli-extra,gtk-extra
host: version 14268.67.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.254-21004-g90921f1f9a15 #1 SMP PREEMPT Sun Dec 12 20:07:25 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
#### Please describe your issue:
I get this when trying to enter my chroot-
crosh> shell
chronos@localhost / $ sudo startgnome
Entering /mnt/stateful_partition/crouton/chroots/bionic...

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-163-generic x86_64 Ubuntu
Current Operating System: Linux localhost 4.4.286-21004-g90921f1f9a15 #1 SMP PREEMPT Sun Dec 12 20:07:2
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4077568 verity payload=PARTUUID=f4892644-65b2-e241-a556-aecc0d1484dc/PARTNROFF=1 hashtree=PARTUUID=f4892644-65b2-e241-a556-aecc0d1484dc/PARTNROFF=1 hashstart=4077568 alg=sha256 root_hexdigest=2fa249926e403cd904e0aa5292b1b82" noinitrd vt.global_cursor_default=0 kern_guid=f4892644-65b2-e241-a556-aecc0d1484dc add_efi_memmap boot=local noresume noswap i915.modeset=1 disablevmx=off  
Build Date: 14 December 2021  04:11:54PM
xorg-server 2:1.19.6-1ubuntu4.10 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sun Dec 26 09:25:11 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1640490911.567979 sender=:1.41 -> destination=:1.286 serial=4178 reply_serial=2
   boolean true
WARNING: Kernel has no file descriptor comparison support: Function not implemented
crouton: version 1-20210907212903~master:9b281df5
release: bionic
architecture: amd64
xmethod: xorg
targets: gnome-desktop,audio,core,xorg,x11,extension,keyboard,chrome,cli-extra,gtk-extra
host: version 14268.67.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.254-21004-g90921f1f9a15 #1 SMP PREEMPT Sun Dec 12 20:07:25 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Cannot open /sys/class/tty/tty0/active: No such file or directory
Running exit commands...
/usr/bin/xinit: connection to X server lost
Hangup
Hangup

waiting for X server to shut down Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1640491009.953403 sender=:1.41 -> destination=:1.289 serial=4192 reply_serial=2
   boolean true
(II) Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bionic...

Please help, it has become a weekly issue with my bionic chroot(& xenial sucks, btw).
I have to delete my chroot each time this happens, and hope that it never happens again.

**Comment by yoiammaac** [comment]
Also enter-chroot works, but startgnome doesnt(thats the error).

**Comment by BetaPictoris** [comment]
Possible duplicate of #4368, #4638, #4611, #4577, #4500, #4482, #4435, #4402, #4398, #4335, and #4296.

**Comment by yoiammaac** [comment]
#4296 is an exact match.
