### ISSUE TITLE
nnjnj

### ISSUE THREAD

**Issue by DeviateBacon3** [dnschneid/crouton#4652]
It's asking for a password Even though I don't have a password

**Comment by BetaPictoris** [comment]
When is it asking you for a password? If it is after running the `crouton` command then you are being asked to *set* a password.

**Comment by TheTechRobo** [comment]
Is it sudo that's asking for the password? Please provide more information

**Comment by DeviateBacon3** [comment]
no i did not set a password on the  Ubuntu install it won't let me install app without a password

**Comment by DeviateBacon3** [comment]
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton

**Comment by supechicken** [comment]
A password should be asked when you install the chroot. (the install command could be like `sudo crouton -t xfce`) Just use that password you set on install.

**Comment by supechicken** [comment]
A password should be set by you when you install the chroot. (the install command could be like `sudo crouton -t xfce`) Just use that password you set on install.

**Comment by TheTechRobo** [comment]
they're having trouble installing crouton, not the chroot.

I can't remember what the default password for chronos is. Is it just chronos?

**Comment by supechicken** [comment]
> they're having trouble installing crouton, not the chroot.
> 
> 
> 
> I can't remember what the default password for chronos is. Is it just chronos?

Oh, sorry for misunderstanding.

AFAIK the default password would be `test0000` (most likely)

**Comment by DennisLfromGA** [comment]
@DeviateBacon3,

If you enabled Debugging Features and don't know the password then you'll have to perform a powerwash or full recovery to remove it.

Closing. Please re-open if this issue is still a concern.

-**DennisLfromGA**
