### ISSUE TITLE
Ctrl + Alt + t "type shell" ... It doesn't work

### ISSUE THREAD

**Issue by IdlePhoenix1645** [dnschneid/crouton#4666]
```
Please paste the output of the following command here: sudo edit-chroot -all
(couldn't get far enough into the process to run this command)

```

#### If known, describe the steps to reproduce the issue:

![Shell command don't work](https://user-images.githubusercontent.com/97568136/149055466-4dadbcc4-2261-4e38-a0ce-0dacb4a840dd.png)

Open crosh, type shell, get yelled at (see link above)

**Comment by supechicken** [comment]
Did you turned on the Chrome OS developer mode? (notice that it is different between dev update channel and dev mode)

**Comment by IdlePhoenix1645** [comment]
> Did you turn on the Chrome OS developer mode? (notice that it is different between dev update channel and dev mode)

I set it up to the point I can use all the Linux development stuff, did I miss an area for other development modes?

**Comment by TheTechRobo** [comment]
That's not the same. Developer mode turns on the shell - look up an article on how to do it. It will erase your Chromebook. It's not to be confused with the "Linux (beta)" functionality

**Comment by TheTechRobo** [comment]
Here's a tutorial: https://www.howtogeek.com/210817/how-to-enable-developer-mode-on-your-chromebook/

**Comment by IdlePhoenix1645** [comment]
> Here's a tutorial: https://www.howtogeek.com/210817/how-to-enable-developer-mode-on-your-chromebook/

That would be where I probably messed up, I am incredibly new to this XD thanks for the help

**Comment by TheTechRobo** [comment]
You're welcome, we all start somewhere!
