### ISSUE TITLE
i can install it

### ISSUE THREAD

**Issue by DeviateBacon3** [dnschneid/crouton#4673]
i get sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

**Comment by TheTechRobo** [comment]
You seem to be using an older tutorial. Use the README - remember, you need the `install` command else it won't work!

**Comment by SeSe008** [comment]
Do `sudo mount -o remount,exec,suid,dev,symfollow ~/` and install it again

**Comment by TheTechRobo** [comment]
you don't even have to do that - just follow the  instructions.
