### ISSUE TITLE
i cant setup

### ISSUE THREAD

**Issue by TwisstedToast** [dnschneid/crouton#4675]
i used sudo sh ~/Downloads/crouton -t xiwi -u -n xenial command

#### Please describe your issue: /mnt/stateful_partition/crouton/chroots not found.
/usr/local/chroots/xenial does not exist; cannot update.
Valid chroots:

**Comment by DennisLfromGA** [comment]
@TwisstedToast,

You're following old installation instructions, please follow the new guide linked below:
- https://github.com/dnschneid/crouton#usage  

-**DennisLfromGA**
