### ISSUE TITLE
unable to connect to X server: Connection refused

### ISSUE THREAD

**Issue by DeviateBacon3** [dnschneid/crouton#4686]
i put in sudo enter-chroot startxfce4 X.Org X Server 1.18.4 Release Date: 2016-07-19 X Protocol Version 11, Revision 0 Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu Current Operating System: Linux localhost 4.14.262-18676-g9987e27710db #1 SMP PREEMPT Thu Jan 13 18:06:38 PST 2022 x86_64 Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4710400 verity payload=PARTUUID=ae7ebf4a-6705-4f0d-81e8-be781d54ffb0/PARTNROFF=1 hashtree=PARTUUID=ae7ebf4a-6705-4f0d-81e8-be781d54ffb0/PARTNROFF=1 hashstart=4710400 alg=sha256 root_hexdigest=df2d10b3faa07a3a99217b6492233268328a117ba2aa8f66763590476f0e46af salt=40d23d04efbfdc9a4d12a1dbfddf514a6a3a0f550f0281c2d17a41f17e3bb545" noinitrd vt.global_cursor_default=0 kern_guid=ae7ebf4a-6705-4f0d-81e8-be781d54ffb0 add_efi_memmap boot=local noresume noswap i915.modeset=1 gsmi.s0ix_logging_enable=1 intel_idle.slp_s0_check=1   Build Date: 08 April 2021  01:52:21PM xorg-server 2:1.18.4-0ubuntu0.12 (For technical support please see http://www.ubuntu.com/support)  Current version of pixman: 0.33.6         Before reporting problems, check http://wiki.x.org         to make sure that you have the latest version. Markers: (--) probed, (**) from config file, (==) default setting,         (++) from command line, (!!) notice, (II) informational,         (WW) warning, (EE) error, (NI) not implemented, (??) unknown. (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Jan 29 11:13:38 2022 (==) Using system config directory "/usr/share/X11/xorg.conf.d" Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted) Error executing command as another user: Not authorized  This incident has been reported. The XKEYBOARD keymap compiler (xkbcomp) reports: > Error:            Cannot close "/var/lib/xkb/server-1.xkm" properly (not enough space?) >                   Output file "/var/lib/xkb/server-1.xkm" removed Errors from xkbcomp are not fatal to the X server The XKEYBOARD keymap compiler (xkbcomp) reports: > Error:            Cannot close "/var/lib/xkb/server-1.xkm" properly (not enough space?) >                   Output file "/var/lib/xkb/server-1.xkm" removed

**Comment by USMP-lancer** [comment]
~~forgot he still works on this thing~~
