### ISSUE TITLE
Installing Discord does not work (I've tried like 20 different ways)

### ISSUE THREAD

**Issue by mrhappyma** [dnschneid/crouton#4688]
I am running Debian Bookworm on xfce, and I am unable to install the Discord application.
I have tried

- Directly downloading the .deb from the Discord website - download fails
- Downloading it in Chrome OS and opening it in the installer in my chroot - Fails with a message saying it needs one more dependency (that i forget what it was), package not found with apt, downloading it and installing that way makes no difference.
- I have tried several guides on reddit and foss-related blogs to edit the dependencies list, no difference
- I have tried installing via flatpak - big long list of errors when trying to run, although install goes fine
- I attempted installing via snap - snap wont install, rip

**Comment by TheTechRobo** [comment]
Discord offers a Bookworm release? TIL

**Comment by DennisLfromGA** [comment]
The Linux Discord app is problematic, it's best to just use the [website](https://discord.com/channels/@me).

**Comment by USMP-lancer** [comment]
snapd needs systemd, so even if it installed, chroots do not have systemd(unless you can forceably start it in chroot somehow)
