### ISSUE TITLE
openSUSE with crouton

### ISSUE THREAD

**Issue by SeSe008** [dnschneid/crouton#4695]
#### Please describe your issue:
Is there any way to install openSUSE with crouton?
`sudo crouton -r tumbleweed -t xfce4`
gives the output:
`tumbleweed does not belong to any supported distribution.`

**Comment by DennisLfromGA** [comment]
openSUSE is not supported and since crouton is now 'maintenance-only it won't be added or supported, sorry.
See the link below for more details:  
- https://github.com/dnschneid/crouton/discussions/4654
