### ISSUE TITLE
cant think of what to call this

### ISSUE THREAD

**Issue by termonaitor2004** [dnschneid/crouton#4706]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: loveforgaming
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/loveforgaming...
crouton: version 1-20220111101058~master:a9eafaee
release: bionic
architecture: amd64
xmethod: xorg
targets: x11,xorg,extension,keyboard,gnome,gnome-desktop,core,audio,cli-extra
host: version 14526.16.0 (Official Build) beta-channel octopus 
kernel: Linux localhost 4.14.254-18726-g37ccbe819bb3 #1 SMP PREEMPT Sun Mar 6 19:49:02 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

#### Please describe your issue:
trying to use any app that requires root or even editing users in setting the AUTH prompt doesn't show up, so how would i make t so i can use them without having to launch from terminal using sudo like a regular ubuntu instillation

#### If known, describe the steps to reproduce the issue:
try installing apps with ubuntu software

**Comment by DennisLfromGA** [comment]
@termonaitor2004,

I can't tell what you are trying to do exactly but maybe this'll help:  
- You can enter your chroot as root with: `sudo enter-chroot -u root [-n CHROOTNAME]`
- You can become root in the chroot with: `sudo -i`
- You can run GUI apps as root by giving root access control first with: `xhost +si:localuser:root`

Be careful though, having root permissions can be dangerous and it's not needed for most things.

-**DennisLfromGA**

**Comment by termonaitor2004** [comment]
so when you install ubuntu with usb on a regular computer you can install software in the software center there is an Authentication dialog that pops up to put your password in same for gdebi, settings, and most other apps

**Comment by termonaitor2004** [comment]
fount the issue polkit doesnt start. pronlem is i cant start it. i get "request ignored, runnung in chroot" how would i bypass that to run polkit?

**Comment by termonaitor2004** [comment]
related to #3160 closing because it doesnt look like fix has been found
