### ISSUE TITLE
xubuntu is not booting up

### ISSUE THREAD

**Issue by gitrubus** [dnschneid/crouton#4709]
```
Please paste the output of the following command here: im to lazy
```

**Comment by gitrubus** [comment]
this is the command to start it if you installed it 
exec crouton-noroot xinit /usr/bin/xubuntu-session

**Comment by gitrubus** [comment]
wait how do you start xubuntu?

**Comment by DennisLfromGA** [comment]
@gitrubus,

> Please paste the output of the following command here: **im to lazy**

You *should* be able to start your Xubuntu desktop with:  
- `sudo startxfce4 [-n CHROOTNAME]`  

If that's not happening and you're too lazy to provide more details then we can't help you.

-**DennisLfromGA**
