### ISSUE TITLE
Kali linux as root

### ISSUE THREAD

**Issue by Apophis52** [dnschneid/crouton#4715]
How can I open Kali Linux rolling with crouton as root?

**Comment by supechicken** [comment]
`sudo`

**Comment by Apophis52** [comment]
I mean to login as root to access the root folder.

**Comment by DennisLfromGA** [comment]
- `sudo enter-chroot -u root [-n kali]`

**Comment by Apophis52** [comment]
sudo: enter-chroot: command not found

**Comment by Apophis52** [comment]
Oh wait it worked now but it's not the graphical display.
