### ISSUE TITLE
fs errors(fsck) edit-chroot -b fails, typical linux

### ISSUE THREAD

**Issue by TomTravis** [dnschneid/crouton#4740]
```
Please passd200: ***** FILE SYSTEM WAS MODIFIED *****
sd200: 1198631/12017664 files (0.2% non-contiguous), 18903874/48062976 blocks
chronos@localhost ~ $ sudo fsck /dev/sdb
fsck from util-linux 2.36.2
e2fsck 1.46.4 (18-Aug-2021)
sd200: clean, 1198631/12017664 files, 18903874/48062976 blocks
chronos@localhost ~ $ sudo mount /dev/sdb /media/removable/sd200
chronos@localhost ~ $ sudo edit-chroot -c/media/removable/sd200/deb/chroots -b -a -f /media/removable/sd200/
tar: bullseye/home/coco/.cache/keyring-DNUJM1/control: socket ignoredmovable/sd200/bullseye-20220518-2218.tar.gz...
tar: bullseye/home/coco/.cache/keyring-NSIHM1/control: socket ignored
tar: bullseye/home/coco/.cache/keyring-NSIHM1/ssh: socket ignored
tar: bullseye/home/coco/.cache/keyring-NSIHM1/pkcs11: socket ignored
tar: bullseye/home/coco/.cache/keyring-CRACM1/control: socket ignored
tar: bullseye/home/coco/.cache/keyring-CRACM1/ssh: socket ignored
tar: bullseye/home/coco/.cache/keyring-CRACM1/pkcs11: socket ignored
Finished backing up /media/removable/sd200/deb/chroots/bullseye to /media/removable/sd200/bullseye-20220518-2218.tar.gzte the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

backup fail on dirty file system
#### If known, describe the steps to reproduce the issue:
after running two days this are errors from chromium stuff (firefox and chromium crashes) fsck is need to clear on a regular basis, Cron does not work systemd?

**Comment by dnschneid** [comment]
sockets not being able to be backed up is normal; it doesn't really make sense to tar a socket.  It looks like the backup succeeded in your log.

I don't see an issue here; if your external media is being corrupted then it's probably not being unmounted correctly as part of suspend/resume; this has been a problem in the past, so try searching the issue tracker for tips.

**Comment by TomTravis** [comment]
firefox creates the bad bit on the disk chromium parts of firefox leave socket open and cause disk error always check before tar , the tar failed as the disk was not clean the log is lost
