### ISSUE TITLE
Seemingly unkillable chroot, loops delete-chroot to repeatedly sending SIGKILL

### ISSUE THREAD

**Issue by CorruptedPlazma** [dnschneid/crouton#4743]
```
chronos@localhost / $ sudo edit-chroot -all
name: bullseye
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bullseye...
crouton: version 1-20220111101058~master:a9eafaee
release: bullseye
architecture: amd64
targets: core
host: version 14588.98.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.254-18805-g12d6850827f5 #1 SMP PREEMPT Wed May 4 19:55:34 PDT 2022 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bullseye...
Failed to unmount /mnt/stateful_partition/crouton/chroots/bullseye. Kill processes? [a/k/y/p/N] y   
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bullseye...
Failed to unmount /mnt/stateful_partition/crouton/chroots/bullseye. Kill processes? [a/k/y/p/N] 
Skipping unmounting of /mnt/stateful_partition/crouton/chroots/bullseye
```

#### Please describe your issue:
Created a chroot for a quick thing, that failed, and so I wanted to get a fresh start. Exited the choot, the exit process couldn't kill it properly, sent a SIGTERM, then began to send SIGKILL infinitely. 

#### If known, describe the steps to reproduce the issue:
Based on my relatively little knowledge, it appears to possibly be something with what I've done within the choot while working with the Breath script.

**Comment by TomTravis** [comment]
yes the happens on new chroots init, very verbose error message, power cycle and it is gone for me New Kernel from Debian, I have started the init systemd grub chroot effort myself many new kernel are now out, The google board target fails when Flash Kernel(chromebook). New tools are happening, i have seen this panic attack this week on Bulleye arm64.

**Comment by CorruptedPlazma** [comment]
That appears to do it, and I honestly feel a bit dumb for not trying a reboot initially. Besides that, thanks for the help. Closing this issue.
