### ISSUE TITLE
i can't use any of crouton scripts

### ISSUE THREAD

**Issue by Arvin2A** [dnschneid/crouton#4759]
#### Please describe your issue:
In the folder where the crouton scripts run (scripts like enter-chroot, edit-chroot,startcli, etc)  i can't run any of those scripts instead i got these:
(*Note*) i can't use sudo (*script name*) directly it gives this error: sudo: edit-chroot: command not found
sudo sh ./edit-chroot -all
sh: 0: getcwd() failed: No such file or directory
sh: 0: Refusing to exec ./edit-chroot from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
It goes on with a similar result in the rest of the scripts 

By the way, I am running crouton from an external drive and the only way for me to access the chroot is the chroot command. I am using bionic as the release for the chroot

Reddit post here (that user that posted is me): https://www.reddit.com/r/Crouton/comments/v4h7kr/i_cant_run_a_crouton_script/?utm_source=share&utm_medium=web2x&context=3

**Comment by DennisLfromGA** [comment]
See my previous response here: https://github.com/dnschneid/crouton/issues/4748#issuecomment-1146432532

Also, you may need to install or reinstall the crouton scripts under `/usr/local/bin/`, you can do that using crouton's `-b` option, see below:

- `-b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.`

-**DennisLfromGA**

**Comment by Masong19hippows** [comment]
This guy is having issues because he install crouton wrong. He refused to fix it. He installed it with -p and on an external drive, so all the scripts are there and that drive is not in his path environment variable. 

He can't run enter-chroot because the script is on his drive with no-exec. I tried to exain all of this on his last post but he never listed. Here are the results. He deleted the post as well, because why not 

https://www.reddit.com/r/Crouton/comments/uyai9r/cannot_execute_binbash_permission_denied_need/?utm_medium=android_app&utm_source=share

**Comment by DennisLfromGA** [comment]
@Masong19hippows,

I understand.
If he installs the crouton scripts on his internal drive under `/usr/local/bin/` then he can launch them on external media by specifying the `-c` option with his 'start' scripts.

-**DennisLfromGA**

**Comment by Arvin2A** [comment]
how do I use -b, what I know about -b is that it runs in the background. If i try this: `sudo crouton -u -n bionic_two -b -p /media/removable/USB\ Drive` : 
Downloading latest crouton installer...
############################################################################################################################################## 100.0%
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: xenial,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.
...

**Comment by Masong19hippows** [comment]
@Arvin2A 

The -b option does not run it in the background. The guy above explained exactly what it does. 

Basically, whenever you installed crouton with -p, it installed everything on your external drive. It installed the scripts as well as the chroot all on that external drive. This is why you are having so many issues. The external drive is a non-exec mount and it is not in your path. This is what is preventing you from using the enter-chroot command. You can't use the normal commands including enter-chroot because your os has no way to find these commands and no way to execute them . This is what I tired to explain while you were being rude in the reddit post. 

The -b option fixes everything. I could be wrong, but all you should need to run is `sudo crouton -b` nothing after or before that. This will install the scripts under the right directory and fix the install that was broken using -p. After this, you should be able to execute `sudo enter-chroot`, and be able to enter your chroot normally.

**Comment by DennisLfromGA** [comment]
If *all*of your chroots on installed on external media you will have to use the '`-p`' option along with the '`-b`' option to let crouton know where your chroots are so it can then determine the targets, etc. and script to restore.

**Comment by Masong19hippows** [comment]
Ope, my bad

**Comment by Arvin2A** [comment]
i did sudo enter-chroot and then this happened: No chroots found in /mnt/stateful_partition/crouton/chroots

**Comment by Arvin2A** [comment]
Ok, i successfully entered the chroot but now i am getting an installation error
