### ISSUE TITLE
No /ect folder

### ISSUE THREAD

**Issue by asherman9000** [dnschneid/crouton#4764]
```
name: impish
encrypted: yes, unlocked
Entering /mnt/stateful_partition/crouton/chroots/impish...
crouton: version 1-20220111101058~master:a9eafaee
release: impish
architecture: amd64
xmethod: xorg
targets: xfce
host: version 14695.85.0 (Official Build) stable-channel octopus 
kernel: Linux localhost.localdomain 4.14.254-19064-g577a877aa35d #1 SMP PREEMPT Wed May 25 19:32:47 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
```

#### Please describe your issue:
I'm having some ubuntu issues and the advice has me doing commands such as
> ls /ect/init.d/

which returns 
> Cannot access /ect: no such file or directory

#### If known, describe the steps to reproduce the issue:
make a fresh impish, xfce install
try to access the /ect folder in a command

**Comment by supechicken** [comment]
It is `/etc` not `/ect`.
