### ISSUE TITLE
GNOME Terminal doesn't open on Debian Buster

### ISSUE THREAD

**Issue by Mwalters75** [dnschneid/crouton#4768]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: buster
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/buster...
crouton: version 1-20220111101058~master:a9eafaee
release: buster
architecture: amd64
xmethod: xorg
targets: gnome-desktop
host: version 14695.85.0 (Official Build) stable-channel snappy 
kernel: Linux localhost 4.4.254-21526-ga09c85531b92 #1 SMP PREEMPT Wed May 25 19:20:57 PDT 2022 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/buster...
```

#### Please describe your issue:
So, as always, I wanted to be a good Linux user, and update the packages, but I can't update the pacakges (none even installs on Gdebi either, and Xterm didn't install) because  

#### If known, describe the steps to reproduce the issue:
- Make a chroot with Debian Buster
- Enter into the chroot
- Launch the Terminal
Doesn't work.

**Comment by TomTravis** [comment]
the gnome package uses chromium libs so this may cause some problems for ARM64 chromebooks

correct xterm is not installed [gnome terminal](https://help.gnome.org/users/gnome-terminal/stable/) is

**Comment by Mwalters75** [comment]
> the gnome package uses chromium libs so this may cause some problems for ARM64 chromebooks
> 
> correct xterm is not installed [gnome terminal](https://help.gnome.org/users/gnome-terminal/stable/) is

Almost all of the Chromebooks I lay my hands on is ARM64, LOL.
