### ISSUE TITLE
Kali-Rolling not booting up

### ISSUE THREAD

**Issue by Astriumus** [dnschneid/crouton#4770]
name: kali-rolling
encrypted: yes, locked

When trying to start Gnome or XFCE4 with Kali-Rolling, I get this error: 
Entering /mnt/stateful_partition/crouton/chroots/kali-rolling...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
Current Operating System: Linux localhost 4.19.246-13481-g15fda228a70c #1 SMP PREEMPT Wed Jun 22 19:17:40 PDT 2022 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5324800 verity payload=PARTUUID=680a6027-cca1-f942-b1ea-cfa1c24ee51a/PARTNROFF=1 hashtree=PARTUUID=680a6027-cca1-f942-b1ea-cfa1c24ee51a/PARTNROFF=1 hashstart=5324800 alg=sha256 root_hexdigest=3247c0f2ac32c6d3062d800c25538ff37e8b9b3c3263ef0dcd678207df5f3fe6 salt=f6e7f9771e859cca0d04ad9564b2692a46860574552274756a2937fa76751b28" noinitrd vt.global_cursor_default=0 kern_guid=680a6027-cca1-f942-b1ea-cfa1c24ee51a add_efi_memmap boot=local noresume noswap i915.modeset=1 ramoops.ecc=1 gsmi.s0ix_logging_enable=1 intel_pmc_core.warn_on_s0ix_failures=1  
xorg-server 2:21.1.3-2+b1 (https://www.debian.org/support) 
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Jun 28 21:26:20 2022
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
error: Kernel is too old for Iris. Consider upgrading to kernel v4.16.

(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/kali-rolling...

**Comment by supechicken** [comment]
Could you provide the output of the following:
```shell
cat /tmp/Xorg.crouton.1.log
```

**Comment by Astriumus** [comment]
Output of cat /tmp/Xorg.crouton.1.log:

[  7746.053] _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[  7746.059] 
X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
[  7746.059] Current Operating System: Linux localhost 4.19.246-13481-g15fda228a70c #1 SMP PREEMPT Wed Jun 22 19:17:40 PDT 2022 x86_64
[  7746.059] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5324800 verity payload=PARTUUID=680a6027-cca1-f942-b1ea-cfa1c24ee51a/PARTNROFF=1 hashtree=PARTUUID=680a6027-cca1-f942-b1ea-cfa1c24ee51a/PARTNROFF=1 hashstart=5324800 alg=sha256 root_hexdigest=3247c0f2ac32c6d3062d800c25538ff37e8b9b3c3263ef0dcd678207df5f3fe6 salt=f6e7f9771e859cca0d04ad9564b2692a46860574552274756a2937fa76751b28" noinitrd vt.global_cursor_default=0 kern_guid=680a6027-cca1-f942-b1ea-cfa1c24ee51a add_efi_memmap boot=local noresume noswap i915.modeset=1 ramoops.ecc=1 gsmi.s0ix_logging_enable=1 intel_pmc_core.warn_on_s0ix_failures=1  
[  7746.059] xorg-server 2:21.1.3-2+b1 (https://www.debian.org/support) 
[  7746.059] Current version of pixman: 0.40.0
[  7746.060]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[  7746.060] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  7746.060] (++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Jun 29 22:42:51 2022
[  7746.061] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  7746.063] (==) No Layout section.  Using the first Screen section.
[  7746.063] (==) No screen section available. Using defaults.
[  7746.063] (**) |-->Screen "Default Screen Section" (0)
[  7746.063] (**) |   |-->Monitor "<default monitor>"
[  7746.065] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[  7746.065] (==) Automatically adding devices
[  7746.065] (==) Automatically enabling devices
[  7746.065] (==) Automatically adding GPU devices
[  7746.065] (==) Automatically binding GPU devices
[  7746.065] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  7746.066] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  7746.066]    Entry deleted from font path.
[  7746.068] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        /usr/share/fonts/X11/100dpi/:unscaled,
        /usr/share/fonts/X11/75dpi/:unscaled,
        /usr/share/fonts/X11/Type1,
        /usr/share/fonts/X11/100dpi,
        /usr/share/fonts/X11/75dpi,
        built-ins
[  7746.068] (==) ModulePath set to "/usr/lib/xorg/modules"
[  7746.068] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[  7746.068] (II) Loader magic: 0x60ec17c0
[  7746.068] (II) Module ABI versions:
[  7746.068]    X.Org ANSI C Emulation: 0.4
[  7746.068]    X.Org Video Driver: 25.2
[  7746.068]    X.Org XInput driver : 24.4
[  7746.068]    X.Org Server Extension : 10.0
[  7746.088] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[  7746.091] (II) xfree86: Adding drm device (/dev/dri/card0)
[  7746.091] (II) Platform probe for /sys/devices/pci0000:00/0000:00:02.0/drm/card0
[  7746.097] (--) PCI:*(0@0:2:0) 8086:9b41:8086:2212 rev 2, Mem @ 0xd0000000/16777216, 0xc0000000/268435456, I/O @ 0x00001c00/64, BIOS @ 0x????????/131072
[  7746.097] (II) LoadModule: "glx"
[  7746.102] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  7746.106] (II) Module glx: vendor="X.Org Foundation"
[  7746.106]    compiled for 1.21.1.3, module version = 1.0.0
[  7746.106]    ABI class: X.Org Server Extension, version 10.0
[  7746.106] (==) Matched modesetting as autoconfigured driver 0
[  7746.106] (==) Matched fbdev as autoconfigured driver 1
[  7746.106] (==) Matched vesa as autoconfigured driver 2
[  7746.106] (==) Assigned the driver to the xf86ConfigLayout
[  7746.106] (II) LoadModule: "modesetting"
[  7746.106] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  7746.107] (II) Module modesetting: vendor="X.Org Foundation"
[  7746.107]    compiled for 1.21.1.3, module version = 1.21.1
[  7746.107]    Module class: X.Org Video Driver
[  7746.107]    ABI class: X.Org Video Driver, version 25.2
[  7746.107] (II) LoadModule: "fbdev"
[  7746.107] (WW) Warning, couldn't open module fbdev
[  7746.107] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  7746.107] (II) LoadModule: "vesa"
[  7746.107] (WW) Warning, couldn't open module vesa
[  7746.107] (EE) Failed to load module "vesa" (module does not exist, 0)
[  7746.107] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  7746.107] (II) modeset(0): using drv /dev/dri/card0
[  7746.107] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[  7746.108] (II) modeset(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 24/32
[  7746.108] (==) modeset(0): Depth 24, (==) framebuffer bpp 32
[  7746.108] (==) modeset(0): RGB weight 888
[  7746.108] (==) modeset(0): Default visual is TrueColor
[  7746.108] (II) Loading sub module "glamoregl"
[  7746.108] (II) LoadModule: "glamoregl"
[  7746.108] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[  7746.117] (II) Module glamoregl: vendor="X.Org Foundation"
[  7746.117]    compiled for 1.21.1.3, module version = 1.0.1
[  7746.117]    ABI class: X.Org ANSI C Emulation, version 0.4
[  7746.167] (II) modeset(0): Refusing to try glamor on llvmpipe
[  7746.168] (II) modeset(0): glamor initialization failed
[  7746.168] (II) modeset(0): ShadowFB: preferred YES, enabled YES
[  7746.168] (II) modeset(0): Double-buffered shadow updates: off
[  7746.170] (II) modeset(0): Output eDP-1 has no monitor section
[  7746.170] (II) modeset(0): Output DP-1 has no monitor section
[  7746.170] (II) modeset(0): Output DP-2 has no monitor section
[  7746.172] (II) modeset(0): EDID for output eDP-1
[  7746.172] (II) modeset(0): Manufacturer: AUO  Model: 818b  Serial#: 0
[  7746.172] (II) modeset(0): Year: 2019  Week: 33
[  7746.172] (II) modeset(0): EDID Version: 1.4
[  7746.172] (II) modeset(0): Digital Display Input
[  7746.172] (II) modeset(0): 6 bits per channel
[  7746.172] (II) modeset(0): Digital interface is DisplayPort
[  7746.172] (II) modeset(0): Max Image Size [cm]: horiz.: 31  vert.: 17
[  7746.172] (II) modeset(0): Gamma: 2.20
[  7746.172] (II) modeset(0): No DPMS capabilities specified
[  7746.172] (II) modeset(0): Supported color encodings: RGB 4:4:4 
[  7746.172] (II) modeset(0): First detailed timing is preferred mode
[  7746.172] (II) modeset(0): Preferred mode is native pixel format and refresh rate
[  7746.172] (II) modeset(0): Display is continuous-frequency
[  7746.172] (II) modeset(0): redX: 0.572 redY: 0.337   greenX: 0.350 greenY: 0.565
[  7746.172] (II) modeset(0): blueX: 0.162 blueY: 0.125   whiteX: 0.313 whiteY: 0.329
[  7746.172] (II) modeset(0): Manufacturer's mask: 0
[  7746.172] (II) modeset(0): Supported detailed timing:
[  7746.172] (II) modeset(0): clock: 141.0 MHz   Image Size:  309 x 174 mm
[  7746.172] (II) modeset(0): h_active: 1920  h_sync: 1936  h_sync_end 1952 h_blank_end 2104 h_border: 0
[  7746.172] (II) modeset(0): v_active: 1080  v_sync: 1083  v_sync_end 1097 v_blanking: 1116 v_border: 0
[  7746.172] (II) modeset(0): Supported detailed timing:
[  7746.172] (II) modeset(0): clock: 94.0 MHz   Image Size:  309 x 174 mm
[  7746.172] (II) modeset(0): h_active: 1920  h_sync: 1936  h_sync_end 1952 h_blank_end 2104 h_border: 0
[  7746.172] (II) modeset(0): v_active: 1080  v_sync: 1083  v_sync_end 1097 v_blanking: 1116 v_border: 0
[  7746.172] (II) modeset(0): Unknown vendor-specific block 2
[  7746.172] (II) modeset(0): EDID (in hex):
[  7746.172] (II) modeset(0):   00ffffffffffff0006af8b8100000000
[  7746.172] (II) modeset(0):   211d0104951f1178039b859256599029
[  7746.172] (II) modeset(0):   20505400000001010101010101010101
[  7746.172] (II) modeset(0):   010101010101143780b8703824401010
[  7746.172] (II) modeset(0):   3e0035ae10000018b82480b870382440
[  7746.172] (II) modeset(0):   10103e0035ae10000018000000000000
[  7746.172] (II) modeset(0):   00000000000000000000000000000002
[  7746.172] (II) modeset(0):   001048ff0f3c7d490d1b7d20202000e4
[  7746.173] (II) modeset(0): Printing probed modes for output eDP-1
[  7746.173] (II) modeset(0): Modeline "1920x1080"x60.0  141.00  1920 1936 1952 2104  1080 1083 1097 1116 -hsync -vsync (67.0 kHz eP)
[  7746.173] (II) modeset(0): Modeline "1920x1080"x120.0  356.38  1920 2080 2288 2656  1080 1081 1084 1118 doublescan -hsync +vsync (134.2 kHz d)
[  7746.173] (II) modeset(0): Modeline "1920x1080"x119.9  266.50  1920 1944 1960 2000  1080 1081 1084 1111 doublescan +hsync -vsync (133.2 kHz d)
[  7746.173] (II) modeset(0): Modeline "1920x1080"x60.0  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync (67.2 kHz d)
[  7746.173] (II) modeset(0): Modeline "1920x1080"x59.9  138.50  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.6 kHz d)
[  7746.173] (II) modeset(0): Modeline "1920x1080"x40.0   94.00  1920 1936 1952 2104  1080 1083 1097 1116 -hsync -vsync (44.7 kHz e)
[  7746.173] (II) modeset(0): Modeline "1680x1050"x60.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "1680x1050"x59.9  119.00  1680 1728 1760 1840  1050 1053 1059 1080 +hsync -vsync (64.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "1600x1024"x60.2  103.12  1600 1600 1656 1664  1024 1024 1029 1030 +hsync +vsync (62.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "1400x1050"x60.0  122.00  1400 1488 1640 1880  1050 1052 1064 1082 +hsync +vsync (64.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "1600x900"x120.0  246.00  1600 1728 1900 2200  900 901 904 932 doublescan -hsync +vsync (111.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "1600x900"x119.9  186.50  1600 1624 1640 1680  900 901 904 926 doublescan +hsync -vsync (111.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "1600x900"x59.9  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync (56.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "1600x900"x59.8   97.50  1600 1648 1680 1760  900 903 908 926 +hsync -vsync (55.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x1024"x60.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "1440x900"x59.9  106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync (55.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "1400x900"x60.0  103.50  1400 1480 1624 1848  900 903 913 934 -hsync +vsync (56.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "1400x900"x59.9   86.50  1400 1448 1480 1560  900 903 913 926 +hsync -vsync (55.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x960"x60.0  108.00  1280 1376 1488 1800  960 961 964 1000 +hsync +vsync (60.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "1440x810"x120.0  198.12  1440 1548 1704 1968  810 811 814 839 doublescan -hsync +vsync (100.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "1440x810"x119.9  151.88  1440 1464 1480 1520  810 811 814 833 doublescan +hsync -vsync (99.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "1368x768"x59.9   85.25  1368 1440 1576 1784  768 771 781 798 -hsync +vsync (47.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "1368x768"x59.9   72.25  1368 1416 1448 1528  768 771 781 790 +hsync -vsync (47.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "1360x768"x59.8   84.75  1360 1432 1568 1776  768 771 781 798 -hsync +vsync (47.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "1360x768"x60.0   72.00  1360 1408 1440 1520  768 771 781 790 +hsync -vsync (47.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x800"x120.0  174.25  1280 1380 1516 1752  800 801 804 829 doublescan -hsync +vsync (99.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x800"x119.9  134.25  1280 1304 1320 1360  800 801 804 823 doublescan +hsync -vsync (98.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x800"x59.8   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync (49.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x800"x59.9   71.00  1280 1328 1360 1440  800 803 809 823 +hsync -vsync (49.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "1152x864"x60.0   81.62  1152 1216 1336 1520  864 865 868 895 -hsync +vsync (53.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x720"x120.0  156.12  1280 1376 1512 1744  720 721 724 746 doublescan -hsync +vsync (89.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x720"x120.0  120.75  1280 1304 1320 1360  720 721 724 740 doublescan +hsync -vsync (88.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x720"x59.9   74.50  1280 1344 1472 1664  720 723 728 748 -hsync +vsync (44.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "1280x720"x59.7   63.75  1280 1328 1360 1440  720 723 728 741 +hsync -vsync (44.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "1024x768"x120.1  133.47  1024 1100 1212 1400  768 768 770 794 doublescan -hsync +vsync (95.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "1024x768"x60.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "960x720"x120.0  117.00  960 1024 1128 1300  720 720 722 750 doublescan -hsync +vsync (90.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "928x696"x120.1  109.15  928 976 1088 1264  696 696 698 719 doublescan -hsync +vsync (86.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "896x672"x120.0  102.40  896 960 1060 1224  672 672 674 697 doublescan -hsync +vsync (83.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "1024x576"x119.9   98.50  1024 1092 1200 1376  576 577 580 597 doublescan -hsync +vsync (71.6 kHz d)
[  7746.173] (II) modeset(0): Modeline "1024x576"x119.9   78.38  1024 1048 1064 1104  576 577 580 592 doublescan +hsync -vsync (71.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "1024x576"x59.9   46.50  1024 1064 1160 1296  576 579 584 599 -hsync +vsync (35.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "1024x576"x59.8   42.00  1024 1072 1104 1184  576 579 584 593 +hsync -vsync (35.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "960x600"x119.9   96.62  960 1028 1128 1296  600 601 604 622 doublescan -hsync +vsync (74.6 kHz d)
[  7746.173] (II) modeset(0): Modeline "960x600"x120.0   77.00  960 984 1000 1040  600 601 604 617 doublescan +hsync -vsync (74.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "960x540"x119.9   86.50  960 1024 1124 1288  540 541 544 560 doublescan -hsync +vsync (67.2 kHz d)
[  7746.173] (II) modeset(0): Modeline "960x540"x120.0   69.25  960 984 1000 1040  540 541 544 555 doublescan +hsync -vsync (66.6 kHz d)
[  7746.173] (II) modeset(0): Modeline "960x540"x59.6   40.75  960 992 1088 1216  540 543 548 562 -hsync +vsync (33.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "960x540"x59.8   37.25  960 1008 1040 1120  540 543 548 556 +hsync -vsync (33.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "800x600"x120.0   81.00  800 832 928 1080  600 600 602 625 doublescan +hsync +vsync (75.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "800x600"x60.3   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "800x600"x56.2   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz d)
[  7746.173] (II) modeset(0): Modeline "840x525"x120.0   73.12  840 892 980 1120  525 526 529 544 doublescan -hsync +vsync (65.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "840x525"x119.8   59.50  840 864 880 920  525 526 529 540 doublescan +hsync -vsync (64.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "864x486"x59.9   32.50  864 888 968 1072  486 489 494 506 -hsync +vsync (30.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "864x486"x59.6   30.50  864 912 944 1024  486 489 494 500 +hsync -vsync (29.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "800x512"x120.3   51.56  800 800 828 832  512 512 514 515 doublescan +hsync +vsync (62.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "700x525"x120.0   61.00  700 744 820 940  525 526 532 541 doublescan +hsync +vsync (64.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "800x450"x119.9   59.12  800 848 928 1056  450 451 454 467 doublescan -hsync +vsync (56.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "800x450"x119.6   48.75  800 824 840 880  450 451 454 463 doublescan +hsync -vsync (55.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x512"x120.0   54.00  640 664 720 844  512 512 514 533 doublescan +hsync +vsync (64.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "720x450"x119.8   53.25  720 760 836 952  450 451 454 467 doublescan -hsync +vsync (55.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "700x450"x119.9   51.75  700 740 812 924  450 451 456 467 doublescan -hsync +vsync (56.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "700x450"x119.8   43.25  700 724 740 780  450 451 456 463 doublescan +hsync -vsync (55.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x480"x120.0   54.00  640 688 744 900  480 480 482 500 doublescan +hsync +vsync (60.0 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x480"x59.9   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "720x405"x59.5   22.50  720 744 808 896  405 408 413 422 -hsync +vsync (25.1 kHz d)
[  7746.173] (II) modeset(0): Modeline "720x405"x59.0   21.75  720 768 800 880  405 408 413 419 +hsync -vsync (24.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "684x384"x119.8   42.62  684 720 788 892  384 385 390 399 doublescan -hsync +vsync (47.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "684x384"x119.7   36.12  684 708 724 764  384 385 390 395 doublescan +hsync -vsync (47.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "680x384"x119.6   42.38  680 716 784 888  384 385 390 399 doublescan -hsync +vsync (47.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "680x384"x119.9   36.00  680 704 720 760  384 385 390 395 doublescan +hsync -vsync (47.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x400"x119.8   41.75  640 676 740 840  400 401 404 415 doublescan -hsync +vsync (49.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x400"x120.0   35.50  640 664 680 720  400 401 404 411 doublescan +hsync -vsync (49.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "576x432"x120.1   40.81  576 608 668 760  432 432 434 447 doublescan -hsync +vsync (53.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x360"x119.7   37.25  640 672 736 832  360 361 364 374 doublescan -hsync +vsync (44.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x360"x119.7   31.88  640 664 680 720  360 361 364 370 doublescan +hsync -vsync (44.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x360"x59.8   18.00  640 664 720 800  360 363 368 376 -hsync +vsync (22.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "640x360"x59.3   17.75  640 688 720 800  360 363 368 374 +hsync -vsync (22.2 kHz d)
[  7746.173] (II) modeset(0): Modeline "512x384"x120.0   32.50  512 524 592 672  384 385 388 403 doublescan -hsync -vsync (48.4 kHz d)
[  7746.173] (II) modeset(0): Modeline "512x288"x120.0   23.25  512 532 580 648  288 289 292 299 doublescan -hsync +vsync (35.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "512x288"x119.8   21.00  512 536 552 592  288 289 292 296 doublescan +hsync -vsync (35.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "480x270"x119.3   20.38  480 496 544 608  270 271 274 281 doublescan -hsync +vsync (33.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "480x270"x119.6   18.62  480 504 520 560  270 271 274 278 doublescan +hsync -vsync (33.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "400x300"x120.6   20.00  400 420 484 528  300 300 302 314 doublescan +hsync +vsync (37.9 kHz d)
[  7746.173] (II) modeset(0): Modeline "400x300"x112.7   18.00  400 412 448 512  300 300 301 312 doublescan +hsync +vsync (35.2 kHz d)
[  7746.173] (II) modeset(0): Modeline "432x243"x119.8   16.25  432 444 484 536  243 244 247 253 doublescan -hsync +vsync (30.3 kHz d)
[  7746.173] (II) modeset(0): Modeline "432x243"x119.1   15.25  432 456 472 512  243 244 247 250 doublescan +hsync -vsync (29.8 kHz d)
[  7746.173] (II) modeset(0): Modeline "320x240"x120.1   12.59  320 328 376 400  240 245 246 262 doublescan -hsync -vsync (31.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "360x202"x119.0   11.25  360 372 404 448  202 204 206 211 doublescan -hsync +vsync (25.1 kHz d)
[  7746.173] (II) modeset(0): Modeline "360x202"x118.3   10.88  360 384 400 440  202 204 206 209 doublescan +hsync -vsync (24.7 kHz d)
[  7746.173] (II) modeset(0): Modeline "320x180"x119.7    9.00  320 332 360 400  180 181 184 188 doublescan -hsync +vsync (22.5 kHz d)
[  7746.173] (II) modeset(0): Modeline "320x180"x118.6    8.88  320 344 360 400  180 181 184 187 doublescan +hsync -vsync (22.2 kHz d)
[  7746.173] (II) modeset(0): EDID for output DP-1
[  7746.173] (II) modeset(0): EDID for output DP-2
[  7746.173] (II) modeset(0): Output eDP-1 connected
[  7746.173] (II) modeset(0): Output DP-1 disconnected
[  7746.173] (II) modeset(0): Output DP-2 disconnected
[  7746.173] (II) modeset(0): Using exact sizes for initial modes
[  7746.173] (II) modeset(0): Output eDP-1 using initial mode 1920x1080 +0+0
[  7746.173] (==) modeset(0): Using gamma correction (1.0, 1.0, 1.0)
[  7746.173] (==) modeset(0): DPI set to (96, 96)
[  7746.173] (II) Loading sub module "fb"
[  7746.173] (II) LoadModule: "fb"
[  7746.173] (II) Module "fb" already built-in
[  7746.173] (II) Loading sub module "shadow"
[  7746.173] (II) LoadModule: "shadow"
[  7746.173] (II) Loading /usr/lib/xorg/modules/libshadow.so
[  7746.173] (II) Module shadow: vendor="X.Org Foundation"
[  7746.173]    compiled for 1.21.1.3, module version = 1.1.0
[  7746.173]    ABI class: X.Org ANSI C Emulation, version 0.4
[  7746.173] (EE) modeset(0): drmSetMaster failed: Permission denied
[  7746.173] (EE) 
Fatal server error:
[  7746.173] (EE) AddScreen/ScreenInit failed for driver 0
[  7746.173] (EE) 
[  7746.173] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
[  7746.173] (EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
[  7746.173] (EE) 
[  7746.173] (EE) Server terminated with error (1). Closing log file.

**Comment by TomTravis** [comment]
[ 7746.170] (II) modeset(0): Output eDP-1 has no monitor section
[ 7746.170] (II) modeset(0): Output DP-1 has no monitor section
[ 7746.170] (II) modeset(0): Output DP-2 has no monitor section
[ 7746.172] (II) modeset(0): EDID for output eDP-1

you have a configuration issue the correct eDP-1 is selected but no monitor via the crouton X driver SW

this is the problem the crouton install uses

[ 7746.088] (EE) systemd-logind: failed to get session: Launch helper exited with unknown return code 1
[ 7746.091] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 7746.107] (II) LoadModule: "fbdev"
[ 7746.107] (WW) Warning, couldn't open module fbdev
[ 7746.107] (EE) Failed to load module "fbdev" (module does not exist, 0)

**Comment by Astriumus** [comment]
What should I do then?
