### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by WebManageBotOFFICIAL** [dnschneid/crouton#4778]
```
sudo: edit-chroot: command not found
```

#### Please describe your issue:
I am installing on my external sdcard, and when it tries to run `prepare.sh`, it spits out this error:
```
chroot: failed to run command '/prepare.sh': Too many levels of symbolic links
Failed to complete chroot setup.
Unmounting /media/removable/chromebook/crouton/chroots/focal...
```

**Comment by WebManageBotOFFICIAL** [comment]
Closing because there is a similar post

**Comment by DennisLfromGA** [comment]
@WebManageBotOFFICIAL,

Check the permissions & mount options on your external media. 
By default I think they have the following mount options:
- `(rw,nosuid,nodev,noexec,relatime,nosymfollow,dirsync,seclabel)`

You'll have to remount it and allow both 'exec' & 'symfollow', at a minimum.
Similar to below, I'm showing `/dev/sda1` and  `/media/removable/STATE` as an example:
- `sudo mount -i -o remount,exec,symfollow /media/removable/STATE`

*Hope this helps,*
-**DennisLfromGA**
