### ISSUE TITLE
Error doing `sudo apt update`

### ISSUE THREAD

**Issue by VenomousSteam81** [dnschneid/crouton#4789]
`sudo edit-chroot -all` output:
```
name: focal
encrypted: no
Entering /media/removable/chromebook/crouton/chroots/focal...
crouton: version 1-20220111101058~master:a9eafaee
release: focal
architecture: arm64
xmethod: xorg
targets: xfce,audio,core,extension,gtk-extra,lxde,lxde-desktop,keyboard,kodi,xorg
host: version 14909.100.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.246-13496-g49abd66ff4ba #1 SMP PREEMPT Sat Jul 30 19:30:51 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Not unmounting /media/removable/chromebook/crouton/chroots/focal as another instance is using it.
```
(Yes, I know its running at the moment)

#### Please describe your issue:
```
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/main/binary-i386/Packages  404  Not Found [IP: 2620:2d:4000:1::19 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/main/binary-i386/Packages  404  Not Found [IP: 2620:2d:4000:1::19 80]
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/main/binary-i386/Packages  404  Not Found [IP: 2620:2d:4000:1::19 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

#### If known, describe the steps to reproduce the issue:
add wines apt repo and key

**Comment by darrell-k** [comment]
"binary-i386" should be "binary-arm64", given your reported architecture. check /etc/apt/sources.list and any files in /etc/apt/sources.list.d/

**Comment by VenomousSteam81** [comment]
I removed the wine apt key, still no dice
`cat /etc/apt/sources.list` output:
```
deb http://ports.ubuntu.com/ubuntu-ports/ focal main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ focal main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ focal-updates main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ focal-updates main restricted universe multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ focal-security main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ focal-security main restricted universe multiverse
```

`ls /etc/apt/sources.list.d/` output:
**nothing was in there. (cricket noise)**

**Comment by darrell-k** [comment]
So you're still getting the output from "apt update" showing that it's looking for "binary-i386"?

What commands did you run to set up the wine repo & key?

What is the output of
`dpkg --print-architecture`?

**Comment by VenomousSteam81** [comment]
Output of `dpkg --print-architecture` gets me `arm64`

**Comment by VenomousSteam81** [comment]
Now, I installed LXDE first, forgetting about the PID error (no I really don't wanna fix it). I uninstalled it, then reinstalled it using `apt`. Something weird to note is that there are at least 6 package managers in `whisker menu`. They are:
```
apply full upgrade
discover
packages
gdebi package manager
muon package manager
package updater
```
Are any of those going to mess stuff up?

**Comment by darrell-k** [comment]
I'm not familiar with LXDE, but I guess those utilities will all be using apt/dpkg under the covers, so I doubt they'd mess things up. 

With your dpkg architecture correct (arm64) and the sources.list contents as you have reported, I really can't see why apt is looking for the i386 packages. But I'm not an expert.

This is not specifically a Crouton issue, and because things are pretty quiet on here these days, I suggest you search/ask a question on the Ubuntu forums, or search for a wiki on apt - the Debian one is quite good.

Good luck.

**Comment by VenomousSteam81** [comment]
Alright, thank you. Have a good rest of your day/night.
Note: I'm actually using XFCE right now, and I deleted the lxde startup script.
