### ISSUE TITLE
THIS IS NOT A BUG, BUT A QUESTION

### ISSUE THREAD

**Issue by VenomousSteam81** [dnschneid/crouton#4791]
Is it possible to remove certain targets you specified with `-t`? I wanted to see if I had xiwi installed, and it reinstalled everything I had installed previously by using `-t`.

**Comment by DennisLfromGA** [comment]
No, unfortunately, there is no built-in method to remove targets from a crouton chroot.

You can remove the target(s) from both of these files in the chroot:  

> /.crouton-targets
> /etc/crouton/targets 

Then remove the target packages using `sudo apt remove [package name]`
Then update the chroot from outside the chroot with: `sudo crouton -n [chrootname] -u`

*Hope this helps,*
-**DennisLfromGA**

**Comment by VenomousSteam81** [comment]
Ok, thank you. I am really running low on space on my chroot.
