### ISSUE TITLE
Unable to download the crouton chrome extension. This makes it impossible to start Crouton. 

### ISSUE THREAD

**Issue by Martyn575** [dnschneid/crouton#4794]
In chromeos on on the arm samsung exynos 5 system...

navigating to:

https://goo.gl/OVQOEt

Gives me the chrome app page for "crouton integration". 

When i click "add to chrome" i then get a pop saying "add extension". 

When i click on this, it says:

"An error has occurred Download interrupted"

In the errors at the bottom right of chromeos, it says "0 B, Failed - the server could not find the file from clients2.google.com"

Weirdly i went through this process about a month or so ago on a different samsung arm 3 series chromebook and it worked flawlessly. 

Has google decided to be evil and pull the link, just to be as difficult as possible?

**Comment by Martyn575** [comment]
Fixed:

There was a critical update icon at the bottom right of chromeos that i needed to install. After a restart chrome app store then allowed me to download the file. 

Just leaving this here in case anyone else comes across this problem.

**Comment by dnschneid** [comment]
I don't recommend downloading and installing extensions from random sources; it's too easy to inject malicious code into them.
