### ISSUE TITLE
Crouton error download kali

### ISSUE THREAD

**Issue by james3212** [dnschneid/crouton#4795]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
When Crouton is retrieving packages to install kali-rolling it mentions cannot check release signature and then says links are not available anymore.

#### If known, describe the steps to reproduce the issue:
Run sudo crouton -n kali -r kali-rolling -t core,xiwi,xfce,extension

**Comment by TomTravis** [comment]
check this out you may need to fork and adjust the kali repo location
https://pkg.kali.org/pkg/debootstrap
crouton uses debootstrap to install distros the current crouton distro is not current for debootstrap this is maintenance activity

**Comment by james3212** [comment]
Thank you Tom

**Comment by dnschneid** [comment]
#4799
