### ISSUE TITLE
Pixel Ctl+Alt hotkey only works by going to and intermediate screen

### ISSUE THREAD

**Issue by gorzell** [dnschneid/crouton#48]
For some reason from ChromeOS if i hit ctl+alt+refresh nothing happens.  If I do ctl+alt+-> and then ctl+alt+refresh it works.

**Comment by gstrube** [comment]
I have experienced the same, using latest crouton (installed 13th july 2016), switching out to ChromeOS then back to Ubuntu with Ctrl + Alt + => shows CROS login screen (VT2). 

Using Ctrl + Alt + Refresh redraws Ubuntu X session and I can continue working...

My Chromebook is Acer CB5-311 (Arm Nvidia K1).

**Comment by DennisLfromGA** [comment]
@gstrube - The key combo 'Ctrl + Alt + => ' has been deprecated for years, use '<kbd>Ctrl + Alt + Shift + =>'</kbd>.
