### ISSUE TITLE
WHY DID YOUHAVE TO BREAK ^W 

### ISSUE THREAD

**Issue by teliten** [dnschneid/crouton#4801]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

**Comment by BetaPictoris** [comment]
Chrosh, and most terminals in general, don’t have the same key bindings as other applications. This is why <kbd>ctrl</kbd> + <kbd>w</kbd> doesn’t work the same way as someone might be used to, another example would be <kbd>ctrl</kbd> + <kbd>c</kbd>.

**Comment by dnschneid** [comment]
You can use the secure shell app to launch a local shell as a window.  Then if you make it full-screen, ^W should work.
