### ISSUE TITLE
sudo crouton -t xfce failing to run debootstrap when i try to run the installer

### ISSUE THREAD

**Issue by notgoodatlinux** [dnschneid/crouton#4805]
```
```chronos@localhost / $ sudo crouton -t xfce
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.46K/installer/ubuntu/bootstrap: /tmp/crouton.GEZ/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.GEZ/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.

Above is me trying to get crouton for the first time on my Chromebook (ASUS).
I followed the steps but when i try to run the installer with `sudo crouton -t xfce` it failed to run the debootstrap? 
If someone can tell me how to fix this that would be awesome :)

on a powerwashed chromebook download crouton, open a shell, run `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`. 
Then, put in `sudo crouton -t xfce` and the same error will occur hopefully. 
I think crouton is either outdated or chrome did something thats stopping crouton

**Comment by TomTravis** [comment]
try a different -r like bullseye -r bullseye -t  xfce

**Comment by iptoux** [comment]
> ```
> ```chronos@localhost / $ sudo crouton -t xfce
> Installing xenial-amd64 chroot to /usr/local/chroots/xenial
> Downloading bootstrap files...
> /tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.46K/installer/ubuntu/bootstrap: /tmp/crouton.GEZ/debootstrap: Permission denied
> debootstrap error log:
> tail: cannot open '/tmp/crouton.GEZ/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
> Failed to run debootstrap.
> 
> Above is me trying to get crouton for the first time on my Chromebook (ASUS).
> I followed the steps but when i try to run the installer with `sudo crouton -t xfce` it failed to run the debootstrap? 
> If someone can tell me how to fix this that would be awesome :)
> 
> on a powerwashed chromebook download crouton, open a shell, run `sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton`. 
> Then, put in `sudo crouton -t xfce` and the same error will occur hopefully. 
> I think crouton is either outdated or chrome did something thats stopping crouton

This is a dupe: https://github.com/dnschneid/crouton/issues/4803

**Comment by TomTravis** [comment]
so what is it the crouton shell need to set the /tmp files for RWX for the debootstrap process to run now this always was the case

sudo mount -i -o remount,exec /tmp/

**Comment by notgoodatlinux** [comment]
> 



> so what is it the crouton shell need to set the /tmp files for RWX for the debootstrap process to run now this always was the case
> 
>sudo mount -i -o remount,exec /tmp/
i already tried that didnt fix the problem

**Comment by notgoodatlinux** [comment]
nevermind, i powerwashed the chromebook and it workd sorry
