### ISSUE TITLE
Can't remove xenial

### ISSUE THREAD

**Issue by Chaotic276** [dnschneid/crouton#4806]
```
Not unmounting /mnt/stateful_partition/crouton/chroots/xenial as another instance is using it: sudo delete-chroot -a
```

#### Please describe your issue:
Trying to delete xenial because it's not wanted but I keep getting the same error.

**Comment by DennisLfromGA** [comment]
@Chaotic276,

Just reboot your Chromebook and try the command again.


-**DennisLfromGA**
