### ISSUE TITLE
Crouton not running

### ISSUE THREAD

**Issue by Icyfiremario** [dnschneid/crouton#4808]
```
Please paste the output of the following command here: 
Downloading latest crouton installer...
curl: error while loading shared libraries: /usr/local/lib64/libunistring.so.2: cannot open shared object file: No such file or directory
Failed to download crouton installer.
Check your internet connection or proxy settings (-P) and try again.

Chromebook model: BLOOGLET C2B-A4I-B2K-T4R-V2I-A3F
```

#### Please describe your issue:
every time I run crouton with or without flags or as root I get the error above

#### If known, describe the steps to reproduce the issue:
run crouton

**Comment by dnschneid** [comment]
It looks like you have something else installed in ChromeOS...maybe crew or something?

**Comment by Icyfiremario** [comment]
> 

I have crew installed if that is causing problems should I uninstall it?

**Comment by dnschneid** [comment]
Ideally it wouldn't cause problems, but it seems to be installing either an incomplete curl or some dependencies thereof that are taking precedence over ChromeOS's builtin ones.

It seems like Chromebrew is in active development, so you should file a bug there.

**Comment by Icyfiremario** [comment]
> Ideally it wouldn't cause problems, but it seems to be installing either an incomplete curl or some dependencies thereof that are taking precedence over ChromeOS's builtin ones.
> 
> It seems like Chromebrew is in active development, so you should file a bug there.

gotcha, I think I tried to install curl through crew because I didn't know if it came installed with ChromeOS and it set it to manually installed so maybe it has something to do with that

**Comment by dnschneid** [comment]
That would definitely do it probably

**Comment by Icyfiremario** [comment]
> That would definitely do it probably

gotcha I'll mess around with it see what works
