### ISSUE TITLE
Gnome Help ( Buster+gnome)

### ISSUE THREAD

**Issue by hiddensea** [dnschneid/crouton#4809]
```
Please paste the output of the following command here: sudo edit-chroot -all name: bullseye
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bullseye...
crouton: version 1-20220111101058~master:a9eafaee
release: bullseye
architecture: amd64
xmethod: xorg
targets: gnome
host: version 14989.107.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.254-19299-gc573ee6f5c5f #1 SMP PREEMPT Tue Sep 13 19:54:27 PDT 2022 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bullseye...
chronos@localhost / $ 
```

#### Please describe your issue: Whenever I launch the chroot/open an app, I get an error on my chroot and `Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1664869078.644439 sender=:1.37 -> destination=:1.232 serial=1317 reply_serial=2` in my crosh

**Comment by TomTravis** [comment]
it seems you install bullseye 
you may need Xdbus libs installed

**Comment by hiddensea** [comment]
Closed as I no longer work with Chrome OS. I will keep the issue up to help others
