### ISSUE TITLE
Xorg stops working after update

### ISSUE THREAD

**Issue by cdd100** [dnschneid/crouton#4811]
```
Please paste the output of the following command here: name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
crouton: version 1-20220111101058~master:a9eafaee
release: focal
architecture: arm64
xmethod: xorg
targets: gnome
host: version 14989.107.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.252-13620-gbce1a289c219 #1 SMP PREEMPT Tue Sep 13 19:34:03 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/focal...
```

#### Please describe your issue:
Xorg has stopped working after updating to ubuntu 22.04
output of sudo startgnome:
chronos@localhost / $ sudo startgnome
Entering /mnt/stateful_partition/crouton/chroots/focal...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
Current Operating System: Linux localhost 4.19.252-13620-gbce1a289c219 #1 SMP PREEMPT Tue Sep 13 19:34:03 PDT 2022 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4077568 verity payload=PARTUUID=58a1d3a8-899b-1c42-a04b-bffa473ab88b/PARTNROFF=1 hashtree=PARTUUID=58a1d3a8-899b-1c42-a04b-bffa473ab88b/PARTNROFF=1 hashstart=4077568 alg=sha256 root_hexdigest=9a1fdfd673bd9300b2d5e1c9513546972b7ca54570edebb0c294c8dc95771554 salt=c78916513cd2b4f4633435dce1a1c3cf837f60f8e16bd6ff1799593f6a3edfda" noinitrd vt.global_cursor_default=0 kern_guid=58a1d3a8-899b-1c42-a04b-bffa473ab88b  
xorg-server 2:21.1.3-2ubuntu2.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Oct 14 10:44:45 2022
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.

#### If known, describe the steps to reproduce the issue:
Lenovo c330 ARM
install ubuntu focal with gnome
update to jammy

**Comment by cdd100** [comment]
Edit: if at all possible i would not like to reinstall crouton.
Thanks!

**Comment by cdd100** [comment]
UPDATE: I settled for plasma on 20.04, but i was wondering if there was a way i could start KDE without having to start xfce and then kde. Thanks!

**Comment by dnschneid** [comment]
You should be able to install the kde target, and then you can run `startkde` instead of `startxfce4`.

**Comment by cdd100** [comment]
I have tried but ever since I tried to install unity, it gave me an error that it was unsupported. Now I cannot update since it gives me the same error every time I try to run sudo crouton -r focal -t kde -u .
