### ISSUE TITLE
can't run on chrome os flex, v105stable/108dev.

### ISSUE THREAD

**Issue by foss-dragon** [dnschneid/crouton#4813]
permission denied in /tmp/

**Comment by DennisLfromGA** [comment]
@foss-dragon 

See if adding 'symfollow' to the mount options helps, see the below reply for more details:  

- https://github.com/dnschneid/crouton/issues/4799#issuecomment-1264215295

*Hope this helps,*
-**DennisLfromGA**

**Comment by foss-dragon** [comment]
> @foss-dragon 
> 
> See if adding 'symfollow' to the mount options helps, see the below reply for more details:  
> 
> - https://github.com/dnschneid/crouton/issues/4799#issuecomment-1264215295
> 
> *Hope this helps,*
> -**DennisLfromGA**

this is not working

**Comment by myelin** [comment]
Can you see if https://github.com/myelin/crouton works for you?  I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.

Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal.

**Comment by foss-dragon** [comment]
> Can you see if https://github.com/myelin/crouton works for you?  I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.
> 
> Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal.

oh thanks, i try it tomorrow, can you please dm me in telegram @modesetting, i want ask some questions

**Comment by myelin** [comment]
> oh thanks, i try it tomorrow, can you please dm me in telegram @modesetting, i want ask some questions

Go ahead and ask questions here :)  That way everyone can benefit from the answers.

**Comment by foss-dragon** [comment]
> > oh thanks, i try it tomorrow, can you please dm me in telegram @modesetting, i want ask some questions
> 
> Go ahead and ask questions here :)  That way everyone can benefit from the answers.

is cursor capture working properly is fp games with sommelier?

**Comment by foss-dragon** [comment]
> Can you see if https://github.com/myelin/crouton works for you?  I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.
> 
> Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal.

cant enter chroot: cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/focal/var/run/drm' : permission denied

**Comment by foss-dragon** [comment]
> > Can you see if https://github.com/myelin/crouton works for you?  I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.
> > 
> > Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal.
> 
> cant enter chroot: cp: cannot create directory '/var/run/crouton/mnt/stateful_partition/crouton/chroots/focal/var/run/drm' : permission denied 

sorry, my bad, setenforce 0 fixed it

**Comment by foss-dragon** [comment]
> > > oh thanks, i try it tomorrow, can you please dm me in telegram @modesetting, i want ask some questions
> > 
> > Go ahead and ask questions here :)  That way everyone can benefit from the answers.
> 
> is cursor capture working properly is fp games with sommelier?

and, is there any ways to access crouton chroot apps via chrome os apps menu?

**Comment by veevyo** [comment]
> Can you see if https://github.com/myelin/crouton works for you? I spent some time on it today and it can create sid, focal, jammy, and kinetic chroots on my brya machine running a personal 108.0.5355.0 build.
> 
> Note that startxfce4 currently fails on sid, jammy, and kinetic, but works on focal.

when I try to run your crouton fork, I get `mktemp: failed to create directory via template '/usr/local/tmp/crouton.XXX': No such file or directory`

**Comment by myelin** [comment]
@foss-dragon @veevyo what device and chromeos version are you using? Can you go to chrome://version and paste the “Platform” line in here?

**Comment by veevyo** [comment]
1. Acer 315
2. chrome ver 106.0.6249.112
3. `Platform: 15054.98.0 (Official Build) stable-channel octopus`

**Comment by myelin** [comment]
> acer aspire 5750g v108

Can you paste the full platform line?
That doesn’t look like a Chromebook — are you running ChromeOS Flex?

**Comment by foss-dragon** [comment]
> 
> > acer aspire 5750g v108
> 
> Can you paste the full platform line?
> That doesn’t look like a Chromebook — are you running ChromeOS Flex?

yes

**Comment by foss-dragon** [comment]
> 
> > acer aspire 5750g v108
> 
> Can you paste the full platform line?
> That doesn’t look like a Chromebook — are you running ChromeOS Flex?

please help with sommelier pointer lock in crouton, i wanna some games..

**Comment by dnschneid** [comment]
#4799
