### ISSUE TITLE
Super weird dpkg error when trying to install bionic

### ISSUE THREAD

**Issue by veevyo** [dnschneid/crouton#4816]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: bionic
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bionic...
crouton: version 1-20220111101058~master:a9eafaee
release: bionic
architecture: amd64
targets: core
host: version 15054.98.0 (Official Build) stable-channel octopus 
kernel: Linux localhost 4.14.254-19334-gd1f3f46afcb0 #1 SMP PREEMPT Wed Oct 5 13:43:48 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...

#### Please describe your issue:
Unpacking libpam-modules-bin (1.1.8-3.6ubuntu2.18.04.3) over (1.1.8-3.6ubuntu2) ...
Setting up libpam-modules-bin (1.1.8-3.6ubuntu2.18.04.3) ...
(Reading database ... 11081 files and directories currently installed.)
Preparing to unpack .../libpam-modules_1.1.8-3.6ubuntu2.18.04.3_amd64.deb ...
Unpacking libpam-modules:amd64 (1.1.8-3.6ubuntu2.18.04.3) over (1.1.8-3.6ubuntu2) ...
Setting up libpam-modules:amd64 (1.1.8-3.6ubuntu2.18.04.3) ...
(Reading database ... 11085 files and directories currently installed.)
Preparing to unpack .../libpam-runtime_1.1.8-3.6ubuntu2.18.04.3_all.deb ...
Unpacking libpam-runtime (1.1.8-3.6ubuntu2.18.04.3) over (1.1.8-3.6ubuntu2) ...
Setting up libpam-runtime (1.1.8-3.6ubuntu2.18.04.3) ...
(Reading database ... 11085 files and directories currently installed.)
Preparing to unpack .../cron_3.0pl1-128.1ubuntu1.2_amd64.deb ...
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of stop.
Unpacking cron (3.0pl1-128.1ubuntu1.2) over (3.0pl1-128.1ubuntu1) ...
Preparing to unpack .../tar_1.29b-2ubuntu0.3_amd64.deb ...
Unpacking tar (1.29b-2ubuntu0.3) over (1.29b-2) ...
Setting up tar (1.29b-2ubuntu0.3) ...
(Reading database ... 11085 files and directories currently installed.)
Preparing to unpack .../dpkg_1.19.0.5ubuntu2.4_amd64.deb ...
Unpacking dpkg (1.19.0.5ubuntu2.4) over (1.19.0.5ubuntu2) ...
Setting up dpkg (1.19.0.5ubuntu2.4) ...
dpkg: error: cannot stat pathname '/tmp/apt-dpkg-install-FKQbmU/8-libext2fs2_1.44.1-1ubuntu1.4_amd64.deb': Too many levels of symbolic links
E: Sub-process /usr/bin/dpkg returned an error code (2)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bionic...

This weird "sub-process /usr/bin/dpkg returned an erorr code (2)" error pops up if I try to install bionic. I'm only installing bionic with the core target.

#### If known, describe the steps to reproduce the issue:
1. download crouton
2. put it in the right directory
3. `crouton -r bionic -t core`

**Comment by DennisLfromGA** [comment]
@veevyo,

> ... too many levels of symbolic links

See https://github.com/dnschneid/crouton/issues/4799#issuecomment-1265796905

*Hope this helps,*
-**DennisLfromGA**
