### ISSUE TITLE
sudo startxfce4 showing black screen after startup

### ISSUE THREAD

**Issue by SwiftSpev** [dnschneid/crouton#4817]
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20220111101058~master:a9eafaee
release: xenial
architecture: amd64
targets: touch,xfce
host: version 15054.98.0 (Official Build) stable-channel hatch 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Wed Oct 5 13:31:22 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

sudo startxfce4  showing black screen after pressing enter!

Log:

ibcras/cras_client.c: In function 'request_floop_ready':
libcras/cras_client.c:1827:14: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   if (req == (struct floop_request *)tag)
              ^
libcras/cras_client.c: In function 'request_floop':
libcras/cras_client.c:4209:40: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  cras_fill_request_floop(&msg, params, (uint64_t)&req);
                                        ^
libcras/cras_client.c: At top level:
cc1: warning: unrecognized command line option '-Wno-int-in-bool-context'
/usr/bin/ld: cannot find -lcras
collect2: error: ld returned 1 exit status
Failed to complete chroot setup.

**Comment by dnschneid** [comment]
Your update issues are #4804; hopefully once you're able to update, xorg will start working again (if not, please re-open)
