### ISSUE TITLE
Nothing is working, really! Nothing!!!

### ISSUE THREAD

**Issue by RAMBoykott** [dnschneid/crouton#4818]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found
#### Please describe your issue:
Hey! I tried thousands of tutorials but it seems that nothing is working. I get one error after error.... please help me...... I just want to install Kali Linux      : (

I got a chromebook (Chromebook Acer 514 Spin)

**Comment by RAMBoykott** [comment]
And a error that appears very often is:

chronos@localhost / $ sudo sh ~/Downloads/crouton ...
sh: 0: Refusing to exec /home/chronos/user/Downloads/crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

**Comment by RAMBoykott** [comment]
And that error:

chronos@localhost / $ sudo crouton
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: xenial,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.
chronos@localhost / $ sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
chronos@localhost / $ sudo crouton -t xfce
Downloading latest crouton installer...
################################################################################################################################### 100.0%
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.kOM/installer/ubuntu/bootstrap: /tmp/crouton.57u/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.57u/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
**Failed to run debootstrap.**
chronos@localhost / $

**Comment by DennisLfromGA** [comment]
@RAMBoykott,

You can no longer run crouton from Downloads, *please* refer to the [updated (4 years ago) installation instructions](https://github.com/dnschneid/crouton#but-first).

*Hope this helps,*
-**DennisLfromGA**

**Comment by RAMBoykott** [comment]
> @RAMBoykott,
> 
> You can no longer run crouton from Downloads, _please_ refer to the [updated (4 years ago) installation instructions](https://github.com/dnschneid/crouton#but-first).
> 
> _Hope this helps,_ -**DennisLfromGA**

Thanks.. I put the crouton file in my linux files now...... whats the command now?

**Comment by RAMBoykott** [comment]
@DennisLfromGA

**Comment by RAMBoykott** [comment]
> @DennisLfromGA

**Comment by DennisLfromGA** [comment]
What?

**Comment by RAMBoykott** [comment]
You said that i can not run it any longer from downloads what is the cammand that???

**Comment by RAMBoykott** [comment]
Before it was 
sudo sh ~/Downloads/crouton ...
but whats the right command now?

**Comment by DennisLfromGA** [comment]
I gave you a link to the updated instructions, please read them before you try anything else.

To quote the author:
> Please read the relevant sections of this README carefully, and reach out to your favorite weblogger/tutorialer/videotuber to update their guides if they're behind the times.

Look at the [Usage](https://github.com/dnschneid/crouton#usage) section and then the [Examples](https://github.com/dnschneid/crouton#examples).

If you have specific issues with anything after you have read and followed the README then search for answers in the [Issues](https://github.com/dnschneid/crouton/issues), most likely others have run into them before you.

-**DennisLfromGA**

**Comment by RAMBoykott** [comment]
Ok i will Try

**Comment by RAMBoykott** [comment]
I think that I need to do this tomorrow to fix it. I will let you know...

Downloading bootstrap files over and over again is a waste of time

Download crouton
Open a shell (Ctrl+Alt+T, type shell and hit enter)
Copy the installer to an executable location by running sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
Now that it's executable, use the installer to build a bootstrap tarball: sudo crouton -d -f ~/Downloads/mybootstrap.tar.bz2
Include the -r parameter if you want to specify for which release to prepare a bootstrap.
You can then create chroots using the tarball by running sudo crouton -f ~/Downloads/mybootstrap.tar.bz2. Make sure you also specify the target environment with -t.
This is the quickest way to create multiple chroots at once, since you won't have to determine and download the bootstrap files every time.

**Comment by RAMBoykott** [comment]
But it would be very helpful if you could tell me here directly which commands I need to use. Thanks

**Comment by RAMBoykott** [comment]
@DennisLfromGA 
I got a new error:

chronos@localhost / $ sudo crouton -d -f ~/Downloads/mybootstrap.tar.bz2
Downloading latest crouton installer...
############################################################################ 100.0%
Downloading xenial-amd64 bootstrap to /home/chronos/user/Downloads/mybootstrap.tar.bz2
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.SCF/installer/ubuntu/bootstrap: /tmp/crouton.sSd/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.sSd/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.
