### ISSUE TITLE
Failed to complete chroot setup?

### ISSUE THREAD

**Issue by NADA-png** [dnschneid/crouton#4821]
```
chronos@localhost / $ sudo edit-chroot -all
name: kali
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/kali...
crouton: version unknown
release: unknown
architecture: unknown
targets: core,xiwi,xfce,extension
host: version 14816.82.0 (Official Build) stable-channel celes 
kernel: Linux localhost 4.19.241-13212-ge9b0bab46475 #1 SMP PREEMPT Fri Jun 24 03:28:27 PDT 2022 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/kali...
```

#### Please describe your issue: 
I'm following a guide to install cybersecurity tools (through Kali) but when I run ```sudo crouton -u -n kali``` I get the error "Failed to complete chroot setup." I've downloaded the script/zip file and got the kali-rolling install command to work (produces the same error without stopping) but when I go to use ```sudo enter-chroot -n kali``` it asks me if I want to complete setup. No matter what I do it gives me the same error every time. I'm new to Linux and crosh so please don't get too complicated with your explanations if you can. Thanks!

**Comment by TomTravis** [comment]
yes this is correct some event in the install did not complete is keep asking to complete this
it is not a error

**Comment by TomTravis** [comment]
it could be crouton should update deboot strap
Adoption rate
Merged /usr has been the default since [debootstrap](https://packages.debian.org/debootstrap) 1.0.85, reverted in 1.0.87 and re-enabled in 1.0.102.

**Comment by dnschneid** [comment]
You are very likely hitting either #4804 or #4799; please reopen if those don't match

**Comment by dnschneid** [comment]
or #4792
