### ISSUE TITLE
Cannot get crouton to install a working version of linux

### ISSUE THREAD

**Issue by ChanceRhodes14** [dnschneid/crouton#4823]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
sudo: edit-shroot: command not found
#### Please describe your issue:
I am trying to install a working version of linux on my chromebook, and I personally have no clue what I am doing as I am entirely new to linux. I originally installed unity, but was roadblocked when i couldnt update out of 16.04 or even browse the internet. I tried using the apt get and apt install commands, but they didnt work. I also couldnt find the software updater in the OS. I then powerwashed my chromebook (just to make sure the previous installation wouldn't mess with a new one since it was already wiped anyways, and im stuck trying to install bionic.

All I really want is an up-to-date Linux operating system that can run alongside my chromeOS. If someone could explain to me how to get bionic 18.04 to install properly, or how to get 16.04 to update out of the stone age, that would be great.
#### If known, describe the steps to reproduce the issue:
Im going to put the output for my bionic installation here, but i cant seem to figure out the error it is giving me.

chronos@localhost / $ sudo crouton -n bionic -t x11,xorg,extension,keyboard,xfce -u
/usr/local/chroots/bionic already exists; updating it...
/bin/sh: 0: Can't open /tmp/crouton-installer-cache/crouton.1Dl/installer/debian/getrelease.sh
/bin/sh: 0: Can't open /tmp/crouton-installer-cache/crouton.1Dl/installer/kali/getrelease.sh
WARNING: bionic is an unsupported release.
You will likely run into issues, but things may work with some effort.
Press Ctrl-C to abort; update will continue in 5 seconds.
Preparing chroot environment...
Installing brightness into the chroot...
Installing croutonpowerd into the chroot...
Installing croutonversion into the chroot...
Installing host-dbus into the chroot...
Installing host-wayland into the chroot...
Installing volume into the chroot...
Installing pulseaudio-default.pa into the chroot...
Installing croutoncycle into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xorg-intel-sna.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xorg into the chroot...
Installing xserverrc-local.example into the chroot...
Installing croutonclip into the chroot...
Installing croutonnotify into the chroot...
Installing croutonurlhandler into the chroot...
Installing startxfce4 into the host...
Installing crouton-noroot into the chroot...
Installing startxfce4 into the chroot...
Installing startxiwi into the host...
Installing croutoncycle into the chroot...
Installing croutonfindnacl into the chroot...
Installing croutontriggerd into the chroot...
Installing croutonxinitrc-wrapper into the chroot...
Installing setres into the chroot...
Installing xinit into the chroot...
Installing xiwi into the chroot...
Installing xbindkeysrc.scm into the chroot...
Installing xiwi.conf into the chroot...
Installing xorg-dummy.conf into the chroot...
Installing xserverrc into the chroot...
Installing xserverrc-xiwi into the chroot...
Installing xserverrc-local.example into the chroot...
Installing startgnome into the host...
Installing crouton-noroot into the chroot...
Installing startgnome into the chroot...
Installing gnome-session-wrapper into the chroot...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing edit-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
Installing crash_reporter_wrapper into the host...
Setting up debconf-i18n (1.5.66ubuntu1) ...
Setting up cron (3.0pl1-128.1ubuntu1.2) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Installing target core...
Preparing environment...
Preparing software sources...
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Fetched 177 kB in 1s (237 kB/s)                              
Reading package lists... Done
Ensuring system is up-to-date...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  distro-info iso-codes libnetplan0 python-apt-common python3-apt python3-netifaces
  python3-pkg-resources
The following packages will be upgraded:
  apt apt-utils busybox-initramfs bzip2 ca-certificates console-setup console-setup-linux
  cpio dbus distro-info-data dmsetup e2fsprogs fdisk file gpgv grep gzip initramfs-tools
  initramfs-tools-bin initramfs-tools-core iproute2 iputils-ping isc-dhcp-client
  isc-dhcp-common keyboard-configuration klibc-utils kmod libapparmor1 libapt-inst2.0
  libapt-pkg5.0 libblkid1 libbsd0 libbz2-1.0 libc-bin libcom-err2 libcryptsetup12 libdb5.3
  libdbus-1-3 libdevmapper1.02.1 libdns-export1100 libelf1 libexpat1 libext2fs2 libfdisk1
  libfribidi0 libgcrypt20 libglib2.0-0 libglib2.0-data libgmp10 libgnutls30 libhogweed4
  libicu60 libidn11 libidn2-0 libisc-export169 libjson-c3 libklibc libkmod2 liblz4-1 liblzma5
  libmagic-mgc libmagic1 libmount1 libncurses5 libncursesw5 libnettle6 libnss-systemd
  libp11-kit0 libpam-systemd libpcre3 libprocps6 libpython3-stdlib libpython3.6-minimal
  libpython3.6-stdlib libseccomp2 libsepol1 libsmartcols1 libsqlite3-0 libss2 libssl1.1
  libsystemd0 libtinfo5 libudev1 libunistring2 libuuid1 libxml2 libzstd1 linux-base locales
  login mount ncurses-base ncurses-bin netcat-openbsd netplan.io networkd-dispatcher nplan
  openssl passwd procps python3 python3-gi python3-minimal python3.6 python3.6-minimal
  rsyslog sudo systemd systemd-sysv tzdata ubuntu-advantage-tools ubuntu-keyring
  ubuntu-minimal udev util-linux vim-common vim-tiny xkb-data xxd xz-utils zlib1g
121 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/46.6 MB of archives.
After this operation, 22.7 MB of additional disk space will be used.
Extracting templates from packages: 100%
Preconfiguring packages ...
dpkg: error: cannot stat pathname '/tmp/apt-dpkg-install-DNaw46/8-libext2fs2_1.44.1-1ubuntu1.4_amd64.deb': Too many levels of symbolic links
E: Sub-process /usr/bin/dpkg returned an error code (2)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/bionic...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/bionic...

If anyone can help me figure this out, I'll mail you a cookie :)

**Comment by dnschneid** [comment]
#4799
