### ISSUE TITLE
cannot find -lcras

### ISSUE THREAD

**Issue by eacelmar96** [dnschneid/crouton#4825]
I ran 
sudo CROUTON_BRANCH=slowpoke_fixes crouton -r xenial -t gnome

and got:

Get:1 http://ports.ubuntu.com/ubuntu-ports xenial/main arm64 libasound2-dev arm64 1.1.0-0ubuntu1 [114 kB]
Fetched 114 kB in 0s (289 kB/s)       
Selecting previously unselected package libasound2-dev:arm64.
(Reading database ... 16037 files and directories currently installed.)
Preparing to unpack .../libasound2-dev_1.1.0-0ubuntu1_arm64.deb ...
Unpacking libasound2-dev:arm64 (1.1.0-0ubuntu1) ...
Setting up libasound2-dev:arm64 (1.1.0-0ubuntu1) ...
libasound2-dev set to automatically installed.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
patch is already the newest version (2.7.5-1ubuntu0.16.04.2).
patch set to manually installed.
The following packages were automatically installed and are no longer required:
  libasound2-dev libglib2.0-0 libspeex-dev libspeex1 libspeexdsp-dev pkg-config
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Compiling CRAS (native)...
/usr/bin/ld: cannot find -lcras
collect2: error: ld returned 1 exit status
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### If known, describe the steps to reproduce the issue:
Also happens when running
sudo crouton -r xenial -t gnome

I am on ARM architecture (Lenovo IdeaPad Duet Chromebook)

**Comment by dnschneid** [comment]
Thanks for trying that branch.  cras compilation is definitely still not fixed... tracking in #4804
