### ISSUE TITLE
xiwi Frame Buffer is being changed somehow the video is horrible in most every chroot tried

### ISSUE THREAD

**Issue by TomTravis** [dnschneid/crouton#4826]
Something is not correct, the video look like the update rate are super slow and the frames overlap

It is likely ChromeOS has change the task privs and or time priority for the video socket

I have no idea i did not read the code or attempt to change it

**Comment by elkawai621** [comment]
dont use xiwi

**Comment by TomTravis** [comment]
you cannot use it , it does not work  the video is not good at all

**Comment by dnschneid** [comment]
I'm assuming this is the same as #4822; please reopen if it's a separate issue
