### ISSUE TITLE
Xenial or other releases fails to install

### ISSUE THREAD

**Issue by UnknownBinary009** [dnschneid/crouton#4831]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20220111101058~master:a9eafaee
release: xenial
architecture: amd64
targets: xfce,audio,core,x11,keyboard,chrome,xorg,xfce-desktop,gtk-extra
host: version 15054.114.0 (Official Build) stable-channel nami 
kernel: Linux localhost 5.4.210-19341-g58913344151b #1 SMP PREEMPT Thu Oct 13 19:09:18 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue: 
Compiling CRAS (i386)...
libcras/cras_client.c: In function 'request_floop_ready':
libcras/cras_client.c:1827:14: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   if (req == (struct floop_request *)tag)
              ^
libcras/cras_client.c: In function 'request_floop':
libcras/cras_client.c:4209:40: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  cras_fill_request_floop(&msg, params, (uint64_t)&req);
                                        ^
libcras/cras_client.c: At top level:
cc1: warning: unrecognized command line option '-Wno-int-in-bool-context'
/usr/bin/ld: cannot find -lcras
collect2: error: ld returned 1 exit status
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by UnknownBinary009** [comment]
on debian its the same it fails to install some own "crouton" issues happened after chromeOS update. I cant rollback not working somehow i powerwashed the device and tried to rollback once more but it also failed.

**Comment by MADOK1** [comment]
I just updated my device and I get this error now too.

**Comment by TomTravis** [comment]
my system bullseye and focal are working
![Screenshot at 2022-10-25 12-38-10](https://user-images.githubusercontent.com/46386261/197866687-8765ef46-3a87-4472-a960-7969336a660f.png)

**Comment by TomTravis** [comment]
Here's some tips:

Audio from the chroot will now be forwarded to CRAS (Chromium OS audio server),
through an ALSA plugin.

Future Chromium OS upgrades may break compatibility with the installed version
of CRAS. Should this happen, simply update your chroot.

You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.

Unmounting /media/removable/sd200/chroots/xenial...
Done! You can enter the chroot using enter-chroot.
chronos@localhost / $

**Comment by TomTravis** [comment]
I using my own fork of my setup
https://drive.google.com/file/d/1cZ6-bSSi2RYpPkb60YAK5tw9UZkdNpFT/view?usp=sharing
it is called testC 
sudo testC -r -t blah

**Comment by dnschneid** [comment]
#4804

**Comment by UnknownBinary009** [comment]
i indeed understand nothing

**Comment by UnknownBinary009** [comment]
on bullseye i get this: dpkg: error: cannot stat pathname '/tmp/apt-dpkg-install-HCJfbD/5-sudo_1.9.5p2-3_amd64.deb': Too many levels of symbolic links
E: Sub-process /usr/bin/dpkg returned an error code (2)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/bullseye...

**Comment by TomTravis** [comment]
https://github.com/dnschneid/crouton/issues/4420
