### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by MADOK1** [dnschneid/crouton#4837]
Please paste the output of the following command here: sudo edit-chroot -all
`chronos@localhost / $ sudo edit-chroot -all
name: bookworm
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/bookworm...
crouton: version 1-20221025213707~master:9eaac08b
release: bookworm
architecture: amd64
targets: gnome
host: version 15054.114.0 (Official Build) stable-channel volteer 
kernel: Linux localhost 5.4.210-19341-g58913344151b #1 SMP PREEMPT Thu Oct 13 19:15:48 PDT 2022 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/bookworm...
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20221025213707~master:9eaac08b
release: xenial
architecture: amd64
targets: xfce
host: version 15054.114.0 (Official Build) stable-channel volteer 
kernel: Linux localhost 5.4.210-19341-g58913344151b #1 SMP PREEMPT Thu Oct 13 19:15:48 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`

#### Please describe your issue:
when running `sudo crouton -r bookworm -t gnome`
the installation starts, but stops after giving throwing this error message:
`After this operation, 12.7 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 sudo amd64 1.9.11p3-2 [1818 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 openssl amd64 3.0.5-4 [1423 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 ca-certificates all 20211016 [156 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 libpsl5 amd64 0.21.0-1.2 [57.3 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 wget amd64 1.21.3-1+b2 [984 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 apt-transport-https all 2.5.3 [164 kB]
Fetched 4603 kB in 1s (8953 kB/s)            
Preconfiguring packages ...
dpkg: error: cannot stat pathname '/tmp/apt-dpkg-install-65j9Td/5-apt-transport-https_2.5.3_all.deb': Too many levels of symbolic links
E: Sub-process /usr/bin/dpkg returned an error code (2)
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/bookworm...`

**Comment by TomTravis** [comment]
sure it does you forget the -u and bookworn fails the install at usrmerge for me

Mount the mount point -o sysfollow , exec  the is for Too many levels of symbolic links

**Comment by dnschneid** [comment]
Could you please reboot and try `sudo CROUTON_BRANCH=symfollow crouton -u -n bookworm`

**Comment by TomTravis** [comment]
https://github.com/dnschneid/crouton/issues/4420

**Comment by TomTravis** [comment]
lhost / $ sudo testC -p  /media/removable/sd200/ -r bookworm -t core -n coreB
Installing bookworm-arm64 chroot to /media/removable/sd200/chroots/coreB
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://deb.debian.org/debian...
I: Retrieving libacl1 2.3.1-1
I: Validating libacl1 2.3.1-1
I: Retrieving adduser 3.129
I: Validating adduser 3.129
I: Retrieving libapparmor1 3.0.7-1+b1

I: Configuring usrmerge...
W: Failure while configuring required packages.
W: See //debootstrap/debootstrap.log for details (possibly the package usrmerge is at fault)
Failed to complete chroot setup.
Unmounting /media/removable/sd200/chroots/coreB...
chronos@localhost / $ ^C
chronos@localhost / $

**Comment by dnschneid** [comment]
@TomTravis that looks like a different bug; please file a separate issue for that

**Comment by TomTravis** [comment]
for to many sym links
sudo mount -o remount,symfollow -o exec /tmp
sudo mount -o remount,symfollow -o exec /media/removable/sd200
cause no problems for me

**Comment by TomTravis** [comment]
to many symlinks come after usrmerge you cannot install bookworm sid or kali

**Comment by MADOK1** [comment]
> Could you please reboot and try `sudo CROUTON_BRANCH=symfollow crouton -u -n bookworm`

I tried this, and it seemed to be installing, but the installation stopped after giving this error:
`Installing target gnome...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gnome-themes-standard is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gnome-themes-standard' has no installation candidate
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in bookworm
Unmounting /mnt/stateful_partition/crouton/chroots/bookworm...`

**Comment by TomTravis** [comment]
just try -t core to see in the chroot is good

**Comment by dnschneid** [comment]
OK, try the regular crouton that I just released; hopefully that fixes gnome as well.

**Comment by MADOK1** [comment]
thank you, this works!.

**Comment by TomTravis** [comment]
usrmerge is still strange

**Comment by TomTravis** [comment]
i pull you changes and try it

**Comment by jazzgroove** [comment]
> for to many sym links
> sudo mount -o remount,symfollow -o exec /tmp
> sudo mount -o remount,symfollow -o exec /media/removable/sd200
> cause no problems for me

Thanks for this! It fixed my issue!
