### ISSUE TITLE
usrmerge debootstrap failure

### ISSUE THREAD

**Issue by TomTravis** [dnschneid/crouton#4838]
lhost / $ sudo testC -p /media/removable/sd200/ -r bookworm -t core -n coreB
Installing bookworm-arm64 chroot to /media/removable/sd200/chroots/coreB
Downloading bootstrap files...
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving InRelease
I: Retrieving Packages
I: Validating Packages
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://deb.debian.org/debian...
I: Retrieving libacl1 2.3.1-1
I: Validating libacl1 2.3.1-1
I: Retrieving adduser 3.129
I: Validating adduser 3.129
I: Retrieving libapparmor1 3.0.7-1+b1

I: Configuring usrmerge...
W: Failure while configuring required packages.
W: See //debootstrap/debootstrap.log for details (possibly the package usrmerge is at fault)
Failed to complete chroot setup.
Unmounting /media/removable/sd200/chroots/coreB...
chronos@localhost / $ ^C
chronos@localhost / $

bookworm, sid , jammy all the same

**Comment by TomTravis** [comment]
sudo mount -o remount,symfollow -o exec /media/removable/sd200
sudo mount -o remount,symfollow -o exec /tmp
then the installs work for Xenial bullseye and focal , kali has usrmerge fails

**Comment by TomTravis** [comment]
hello

I merge the main with my fix-c branch and it works 
it appear you  mount and remount the chroot during the debootstrap for bookworm sid and jammy this was causing the usrnerge to fail
Installing target post-common...
Cleaning up...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Please specify a username for the primary user: z
New password: 
Retype new password: 
passwd: password updated successfully
/media/removable/sd200/chroots/bookworm not found.
Done! You can enter the chroot using enter-chroot.
chronos@localhost / $ ^C

**Comment by dnschneid** [comment]
Yeah, debootstrap messes with the mounts so crouton has to redo the mounts once second stage is complete.  Glad it's working for you now.
