### ISSUE TITLE
Xorg Fails Nvidia

### ISSUE THREAD

**Issue by TomTravis** [dnschneid/crouton#4839]
[chroot.txt](https://github.com/dnschneid/crouton/files/9875611/chroot.txt)

[newfile.txt](https://github.com/dnschneid/crouton/files/9875624/newfile.txt)
```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost /media/removable/sd200/chroots $  sudo edit-chroot -c /media/removable/sd200/chroots -all
name: bcore
encrypted: no
Entering /media/removable/sd200/chroots/bcore...
crouton: version 1-20220512214808
release: bookworm
architecture: arm64
xmethod: xiwi
targets: xiwi,x11,core
host: version 15054.114.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/sd200/chroots/bcore...
name: book
encrypted: no
Entering /media/removable/sd200/chroots/book...
crouton: version 1-20221026165811~new-fix:552076e5
release: bookworm
architecture: arm64
xmethod: xorg
targets: x11
host: version 15054.114.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/sd200/chroots/book...
name: bookworm
encrypted: no
Entering /media/removable/sd200/chroots/bookworm...
crouton: version 1-20221026165811~new-fix:552076e5
release: bookworm
architecture: arm64
targets: core
host: version 15054.114.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/sd200/chroots/bookworm...
name: bullseye
encrypted: no
Entering /media/removable/sd200/chroots/bullseye...
crouton: version 1-20220512214808
release: bullseye
architecture: arm64
xmethod: xorg
targets: xiwi,x11,core
host: version 15054.114.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64 GNU/Linux
freon: yes
Not unmounting /media/removable/sd200/chroots/bullseye as another instance is using it.
name: focal
encrypted: no
Entering /media/removable/sd200/chroots/focal...
crouton: version 1-20220512214808
release: focal
architecture: arm64
xmethod: xorg
targets: x11,xiwi
host: version 15054.114.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/sd200/chroots/focal...
name: kali-rolling
encrypted: no
Entering /media/removable/sd200/chroots/kali-rolling...
crouton: version unknown
release: unknown
architecture: unknown
targets: core
host: version 15054.114.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/sd200/chroots/kali-rolling...
name: xenial
encrypted: no
Entering /media/removable/sd200/chroots/xenial...
crouton: version 1-20220512214808
release: xenial
architecture: arm64
xmethod: xorg
targets: x11,core
host: version 15054.114.0 (Official Build) stable-channel hana 
kernel: Linux localhost 4.19.254-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /media/removable/sd200/chroots/xenial...
chronos@localhost /media/removable/sd200/chroots $ 

```

#### Please describe your issue:
X Protocol Version 11, Revision 0
[  8227.381] Build Operating System: linux Debian
[  8227.383] Current Operating System: Linux localhost 4.19.255-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64
[  8227.383] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4077568 verity payload=PARTUUID=1d128873-d1cb-5f47-960d-68e7a9818db0/PARTNROFF=1 hashtree=PARTUUID=1d128873-d1cb-5f47-960d-68e7a9818db0/PARTNROFF=1 hashstart=4077568 alg=sha256 root_hexdigest=e74cdb6a8b750cbf2b6dfc25ad8b7ea07cefc58b53ef98ee60834db4a684ba8d salt=4d7ed087a033cf5dfe4b11b8da0bcb302c1de1f7bdc44a92040f8aa7d59ddbdd" noinitrd vt.global_cursor_default=0 kern_guid=1d128873-d1cb-5f47-960d-68e7a9818db0 cpuidle.governor=teo  
[  8227.384] Build Date: 05 August 2022  08:00:36AM
works
[  8227.439] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[  8227.442] (II) xfree86: Adding drm device (/dev/dri/card2)
[  8227.443] (II) no primary bus or device found
[  8227.443] (II) LoadModule: "glx"
bullseye)z@localhost:/usr/share/X11$ ls -lar
total 88
drwxr-xr-x.   2 root root  4096 Oct 20 20:11 xorg.conf.d
-rw-r--r--.   1 root root  8305 Feb 28  2020 xman.help
drwxr-xr-x.   8 root root  4096 Oct 20 20:11 xkb
lrwxrwxrwx.   1 root root    16 Feb 15  2021 rgb.txt -> /etc/X11/rgb.txt
drwxr-xr-x.  64 root root  4096 Oct 20 20:08 locale
-rw-r--r--.   1 root root 42077 Jul 26  2021 XErrorDB
drwxr-xr-x. 440 root root 16384 Oct 25 19:47 ..
drwxr-xr-x.   5 root root  4096 Oct 20 20:11 .
(bullseye)z@localhost:/usr/share/X11$ cd  xorg.conf.d
(bullseye)z@localhost:/usr/share/X11/xorg.conf.d$ ls -la
total 20
drwxr-xr-x. 2 root root 4096 Oct 20 20:11 .
drwxr-xr-x. 5 root root 4096 Oct 20 20:11 ..
-rw-r--r--. 1 root root 1350 Aug  5 01:00 10-quirks.conf
-rw-r--r--. 1 root root 1429 Aug 17  2020 40-libinput.conf
-rw-r--r--. 1 root root 2747 Jun 26  2017 70-wacom.conf
(bullseye)z@localhost:/usr/share/X11/xorg.conf.d$ 

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
[  8227.381] Build Operating System: linux Debian
[  8227.383] Current Operating System: Linux localhost 4.19.255-13653-ga5ef616743fe #1 SMP PREEMPT Thu Oct 13 19:09:54 PDT 2022 aarch64
[  8227.383] Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro d
m_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4077568 verity payload=PARTUUID=1d128873-d1cb
-5f47-960d-68e7a9818db0/PARTNROFF=1 hashtree=PARTUUID=1d128873-d1cb-5f47-960d-68e7a9818db0/PARTNROFF=1 hashstart=4077568 alg=sha256 root_h
exdigest=e74cdb6a8b750cbf2b6dfc25ad8b7ea07cefc58b53ef98ee60834db4a684ba8d salt=4d7ed087a033cf5dfe4b11b8da0bcb302c1de1f7bdc44a92040f8aa7d59
ddbdd" noinitrd vt.global_cursor_default=0 kern_guid=1d128873-d1cb-5f47-960d-68e7a9818db0 cpuidle.governor=teo  

Fails

./xorg.conf.d:
total 20
drwxr-xr-x. 2 root root 4096 Oct 26 20:34 .
drwxr-xr-x. 5 root root 4096 Oct 26 17:56 ..
-rw-r--r--. 1 root root 1350 Sep 21 22:53 10-quirks.conf
-rw-r--r--. 1 root root 1429 Feb 12  2022 40-libinput.conf
-rw-r--r--. 1 root root 3458 Jul 14 07:19 70-wacom.conf
**lrwxrwxrwx. 1 root root   50 Jun 30 11:29 nvidia-drm-outputclass.conf -> /etc/alternatives/glx--nvidia-drm-outputclass.conf**

#### If known, describe the steps to reproduce the issue:

repair 
**glx--nvidia-drm-outputclass.conf**

**Comment by TomTravis** [comment]
https://download.nvidia.com/XFree86/Linux-x86_64/396.51/README/editxconfig.html

**Comment by TomTravis** [comment]
try to install the package debootstrap / crouton does not use this install
https://packages.debian.org/bookworm/nvidia-kernel-dkms
in work will add to my fork
this is my GPU integrated powervr gx6250 FOSS drivers should work

**Comment by TomTravis** [comment]
Building for 4.19.255-13653-ga5ef616743fe and 5.19.0-2-arm64
Module build for kernel 4.19.255-13653-ga5ef616743fe was skipped since the
kernel headers for this kernel do not seem to be installed.
Building initial module for 5.19.0-2-arm64
Done.

nvidia-current.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-2-arm64/updates/dkms/

nvidia-current-modeset.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-2-arm64/updates/dkms/

nvidia-current-drm.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-2-arm64/updates/dkms/

nvidia-current-uvm.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-2-arm64/updates/dkms/

nvidia-current-peermem.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.19.0-2-arm64/updates/dkms/
depmod...
Processing triggers for glx-alternative-nvidia (1.2.1) ...
Processing triggers for glx-alternative-mesa (1.2.1) ...
Processing triggers for update-glx (1.2.1) ...
Processing triggers for libc-bin (2.35-3) ...
Processing triggers for glx-alternative-nvidia (1.2.1) ...
Processing triggers for libc-bin (2.35-3) ...
Processing triggers for initramfs-tools (0.142) ...
(book)z@localhost:~$

**Comment by TomTravis** [comment]
well progress after nvidia akms and arm64 kernel update bookworm
 linux-headers-cloud-arm64
installed
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Oct 27 12:01:48 2022
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
there is no conf files installed

32460.480] (II) LoadModule: "fb"
[ 32460.480] (II) Module "fb" already built-in
[ 32460.480] (II) UnloadModule: "nvidia"
[ 32460.480] (II) Unloading nvidia
[ 32460.480] (EE) modeset(0): drmSetMaster failed: Invalid argument
still fail
[ 32460.480] (EE) 
Fatal server error:
[ 32460.480] (EE) AddScreen/ScreenInit failed for driver 0
[ 32460.480] (EE) 
[ 32460.480] (EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help.

**Comment by TomTravis** [comment]
i got the server to start via xorg.conf in /etc/X11 however the graphics will not connect
the crouton xinit in /usrlocal/bin is being used mate starts the server will not connect yet

**Comment by TomTravis** [comment]
i have to admit hacking now
the server starts via the crouton xorg.conf bit hangs and requires reboot xfce4... mate kde
I need to read up on Xorg video Nvidia is now the game it appears maybe not the kernel has been updated in bullseye for nvidia as is Ubuntu for free86 dummy  
the chromeOS I/F is still not connecting mouse and keyboard ,, this is why reboot

**Comment by TomTravis** [comment]
im getting very verbose message the console kit is not installed  apparently so ,, cros_secure console= loglevel=7 is not happening at server start it complains tty is not present

Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4077568 verity payload=PARTUUID=1d128873-d1cb-5f47-960d-68e7a9818db0/PARTNROFF=1 hashtree=PARTUUID=1d128873-d1cb-5f47-960d-68e7a9818db0/PARTNROFF=1 hashstart=4077568 alg=sha256 root_hexdigest=e74cdb6a8b750cbf2b6dfc25ad8b7ea07cefc58b53ef98ee60834db4a684ba8d salt=4d7ed087a033cf5dfe4b11b8da0bcb302c1de1f7bdc44a92040f8aa7d59ddbdd" noinitrd vt.global_cursor_default=0 kern_guid=1d128873-d1cb-5f47-960d-68e7a9818db0 cpuidle.governor=teo

**Comment by TomTravis** [comment]
My guess is to review the Intel Free86 video org install for crouton the chomeOS console works with this
xiwi uses the chomeoOS console and dummy Free86 drivers this also now has issues with res and clk

**Comment by dnschneid** [comment]
I can't pretend I've read all of that, but if you're trying to use the proprietary nvidia drivers, you have to build the kernel modules against the ChromeOS kernel and include them in the root partition (outside the chroot).  It's super messy and probably won't work.  You might want to look at some of the tutorials and issues floating around for running VirtualBox in crouton; it's kind of the same problem.

You also might have better luck with nouveau?

**Comment by TomTravis** [comment]
debian installed them also kali have them i did not choose the nvidia drivers debootstrap debian did

**Comment by TomTravis** [comment]
the xorg server starts no keyboard or pointer it hangs in wait state reboot is the only way to recover

**Comment by TomTravis** [comment]
[xorg.txt](https://github.com/dnschneid/crouton/files/9913640/xorg.txt)
it appears some edit and change in package install for crouton kms kernels
