### ISSUE TITLE
Automated shutdown

### ISSUE THREAD

**Issue by scorcioni** [dnschneid/crouton#484]
At random times I get a "the system will shutdown in 60 seconds". Most frequently it happens after the screen is been idle for some time or after the system is waking up from sleep. More rarely it happens as I am using the pixel. Does anybody else has this problem?

crouton: version 0-20131108001902~master:7170bf5b
release: precise
architecture: amd64
host: version 4920.6.0 (Official Build) dev-channel link

**Comment by UT99310** [comment]
I upgraded ram to 16GB and added a different external USB drive over the weekend. Since then I've seen two unexpected system shutdowns on this ASUS Chromebox (Trusty chroot). Both times it happened while the screens were blanked and I was away. There was some issue about whether or not this ram was actually compatible -- different stories from the vendor and manufacturer -- but CPU temp at least has not seemed scary high even when I was really pushing the system. I'm planning to change the logging config so I have something other than the dmesg ring to inspect. Any other suggestions appreciated. Thanks!

**Comment by divx118** [comment]
@UT99310 Normally a reboot/shutdown can be caused by a kernel panic. So you could take a look at `/dev/pstore/console-ramoops` to see if there is anything useful.

**Comment by UT99310** [comment]
These are complete shutdowns -- full power off. When I powered back on, I had the usual dev mode white screen sequence and a full boot sequence. Would /dev/pstore/console-ramoops be expected to survive a power cycle like that? My /dev/pstore is completely empty. Thanks!

**Comment by divx118** [comment]
Ah ok, a complete shutdown is normally not a kernel panic. If /dev/pstore is empty you didn't have one and yes they survive the reboot. You could take a look in /var/log , maybe something there could explain the shutdown.

**Comment by UT99310** [comment]
Yeah, I've been looking those logs over. They sure are full of:

DEBUG pulseaudio[25575]: Set nice to -10 Fail.

2015-05-06T21:05:33.831455-07:00 WARNING pulseaudio[25575]: setrlimit
10 failed: 1

I thought those settings were how I got PA performance way up and load
way down. Perhaps not!

No clue for the shutdowns yet, though. Thanks.

**Comment by UT99310** [comment]
Interesting. Logs suggest (see below) that the events are precipitated by
system-initiated timeout suspends (that apparently fail in some manner to
be recoverable, so I can't come out of those suspends and end up rebooting
instead). Oddly, while I do have the screens set to timeout, I thought I
had turned off automatic suspend everywhere in the CrOS and Trusty power
management system, but obviously they're still taking place. Hmm. Also, my
manually initiated suspends which I use at least once a day via:

sudo pm-suspend

have virtually never failed to be recoverable so far. Nor do I know what
has changed (other than my recent ram and disk upgrades) to cause this
altered behavior.

[0506/230542:INFO:state_controller.cc(89)] Dimming screen after 7m
[0506/230542:INFO:display_power_setter.cc(61)] Asking Chrome to dim
the display in software
[0506/230642:INFO:state_controller.cc(89)] Turning screen off after 8m
[0506/230642:INFO:display_power_setter.cc(72)] Asking Chrome to turn all
displays off
[0506/231719:INFO:daemon.cc(1440)] Update operation is
UPDATE_STATUS_CHECKING_FOR_UPDATE
[0506/231720:INFO:daemon.cc(1440)] Update operation is UPDATE_STATUS_IDLE
[0506/232857:INFO:state_controller.cc(872)] Ready to perform idle action
(suspend) after 30m
[0506/232857:INFO:suspender.cc(343)] Starting request 278069249
[0506/232857:INFO:suspend_delay_controller.cc(139)] Announcing suspend
request 278069249 with 2 pending delay(s) and 0 outstanding delay(s) from
previous request
[0506/232857:INFO:suspend_delay_controller.cc(88)] Got notification that
delay 278069249 (shill) is ready for suspend request 278069249 from :1.5
[0506/232857:INFO:suspend_delay_controller.cc(88)] Got notification that
delay 278069250 (chrome) is ready for suspend request 278069249 from :1.7
[0506/232857:INFO:suspend_delay_controller.cc(224)] Notifying observers
that suspend is ready
[0506/232857:INFO:suspender.cc(411)] Starting suspend
[0506/232857:INFO:util.cc(41)] Running "/usr/bin/powerd_setuid_helper
--action=suspend  --suspend_wakeup_count_valid --suspend_wakeup_count=0"
