### ISSUE TITLE
kali xorg nivdia

### ISSUE THREAD

**Issue by TomTravis** [dnschneid/crouton#4858]
![Screenshot from 2022-11-02 20-07-57](https://user-images.githubusercontent.com/46386261/199641307-5a701c2b-a8c6-4cd5-8642-82d48d70b79a.png)

image washing out 

kali needs
sudo apt-get install dbus-x11 for xiwi to start
using delete backports in xorg target
Installed property nvidia drivers and work with xiwi

**Comment by TomTravis** [comment]
![Screenshot 2022-11-02 8 27 56 PM](https://user-images.githubusercontent.com/46386261/199642350-28cc9fec-0eab-4a1c-b65d-ed3d03e8ae1a.png)

**Comment by dnschneid** [comment]
crouton doesn't support proprietary nvidia drivers.  Please either move this to your fork or keep the discussion in "discussions"
