### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by avaiv** [dnschneid/crouton#4878]
`chronos@localhost / $ sudo sh ~/Downloads/crouton -t unity
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.ZII/installer/ubuntu/bootstrap: /tmp/crouton.rFi/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.rFi/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory`

How do i fix the debootstrap

**Comment by TomTravis** [comment]
please post in chrome what is you processor ? 7c snapdragon? says amd64?
chrome://system
chrome://version

and your mount need to be exec
sudo mount -o remount,symfollow -o exec /tmp

**Comment by avaiv** [comment]
Intel(R) Celeron(R) CPU N3350 @ 1.10GHz (2 threads, 2.40GHz)

**Comment by TomTravis** [comment]
ok this work mount the /tmp dir exec time you restart the machine my script is mnt.sh in /usr/local/bin chmod 755

sudo mount -o remount,symfollow -o exec /media/removable/sd200  # i use a SD card for chroots
sudo mount -o remount,symfollow -o exec /tmp    

[mnt.txt](https://github.com/dnschneid/crouton/files/9993769/mnt.txt)

**Comment by TomTravis** [comment]
try this test2 like crouton was update to run in /usr/local/bin
https://drive.google.com/uc?export=download&id=1HFjX1OejjHAYbaHVL3l9krmBUkA1caZR

**Comment by avaiv** [comment]
@TomTravis I used the test2 but instead of 
`sudo mount -o remount,symfollow -o exec /tmp`
I used
`sudo mount -i -o remount,exec,dev /usr/local/ `
and it worked! 
Thank you!

**Comment by TomTravis** [comment]
wonderful
