### ISSUE TITLE
Cant install crouton

### ISSUE THREAD

**Issue by Timi25062010** [dnschneid/crouton#4881]
chronos@localhost / $ sudo crouton -t unity
WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
If this is a surprise to you, you should do a full system recovery via USB.
Installing xenial-amd64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.OoT/installer/ubuntu/bootstrap: /tmp/crouton.jmY/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.jmY/xenial-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.

**Comment by TomTravis** [comment]
please post in chrome what is you processor ? 7c snapdragon? says amd64?
chrome://system
chrome://version

and your mount need to be exec
sudo mount -o remount,symfollow -o exec /tmp

chrome://system
![Screenshot 2022-11-11 11 00 52 AM](https://user-images.githubusercontent.com/46386261/201485277-ac48cf05-45bc-4aa7-94b1-7ab232723e99.png)

**Comment by tanthon1** [comment]
I'm having this same issue. Opening up separate thread

**Comment by TomTravis** [comment]
well check /var /bin /mnt to be exec

**Comment by TomTravis** [comment]
https://github.com/dnschneid/crouton/issues/4884

**Comment by drinkcat** [comment]
#4901 should fix this. Please try again with the latest version of crouton.
