### ISSUE TITLE
Cannot Install ubuntu on Lenovo duet 5 chromebook (Model: 13QC76)

### ISSUE THREAD

**Issue by hungshe** [dnschneid/crouton#4882]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Output:
chronos@localhost / $ sudo edit-chroot -all
sudo: edit-chroot: command not found

#### Please describe your issue:
Following "The easy way (Assume you want an Ubuntu LTS with xfcce)": https://github.com/dnschneid/crouton#the-easy-way-assuming-you-want-an-ubuntu-lts-with-xfce
My duet 5 is already in developer mode, removed os verification, remount rootfs partition with read/write permission and exec mode.
However, the installation failed at step 4: 
4. Now that it's executable, run the installer itself: sudo crouton -t xfce
Output log:
chronos@localhost / $ sudo crouton -t xfce
Downloading latest crouton installer...
################################################################################################################################### 100.0%
WARNING: Your rootfs is writable. Signed boot verification cannot be enabled.
If this is a surprise to you, you should do a full system recovery via USB.
Installing xenial-arm64 chroot to /usr/local/chroots/xenial
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.YJI/installer/ubuntu/bootstrap: /tmp/crouton.Jwe/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.Jwe/xenial-arm64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.

System Info: 
![Screenshot 2022-11-12 12 36 10](https://user-images.githubusercontent.com/1335145/201493827-a9b481ee-af04-4245-a4c6-6f26d8163434.png)
My duet 5 chromebook is Qualcomm Arm64 version

#### If known, describe the steps to reproduce the issue:
1. Enter developer mode
2. set rootfs os verification off, reboot
3. remout root partition with rw, exec  configuration
4. sudo mount -o rw,remount,symfollow -o exec /tmp
5. follow the instruction:
https://github.com/dnschneid/crouton#the-easy-way-assuming-you-want-an-ubuntu-lts-with-xfce

**Comment by TomTravis** [comment]
yes it is to bad the 7c Qualcom arm64 is not supported by debootstrap with crouton it seems
you are not the only one,you can fork and play with debootstrap arm64 settings
or try to create a file in /tmp
and see if you get Permission denied

**Comment by hungshe** [comment]
> yes it is to bad the 7c Qualcom arm64 is not supported by debootstrap with crouton it seems tail: cannot open '/tmp/crouton.Jwe/xenial-arm64/debootstrap/debootstrap.log' for reading: No such file or directory Failed to run debootstrap. you are not the only one,you can fork and play with debootstrap arm64 settings or try to create a file in /tmp and see if you get Permission denied this may help you https://www.lenovo.com/us/en/faqs/operating-systems/install-linux-chromebook/?orgRef=https%253A%252F%252Fwww.google.com%252F

May I know the guide for "fork and play with debootstrap arm64 settings"?
Also, I tried create a file in /tmp with command echo "hello.txt" > hello.txt.  I don't see any permission issue.

**Comment by TomTravis** [comment]
yes the fork is easy just google search Github fork 
super easy , the issue maybe you need a development machine look for as low cost Chromebook maybe to choose from

once you have a fork you need to complie the code
![Screenshot 2022-11-13 12 39 10 AM](https://user-images.githubusercontent.com/46386261/201513470-ae81ab54-6c90-4edb-a455-c7a8c2e6136a.png)

if you wish you can join the chroot systemd team I will send you a invite you have a nice effort and the duet is a super chromebook
https://github.com/users/TomTravis/projects/3
![Screenshot 2022-11-13 12 44 50 AM](https://user-images.githubusercontent.com/46386261/201513460-864975d7-08e9-48d3-b734-a9abe46e086b.png)


Ok great news  I don't see any permission issue. this is super good news , then the error is no file is created there is no log file

**Comment by supechicken** [comment]
試一試將`sudo mount -o rw,remount,symfollow -o exec /tmp`中的兩個`-o`結合？ 像這樣：
```shell
sudo mount -o rw,remount,symfollow,exec /tmp
```

(I expect you understand Chinese since that's your system language)

順帶一提最好不要聽上面那個怪人的話，那人整天都在留廢話

**Comment by TomTravis** [comment]
> I tried create a file in /tmp with command echo "hello.txt" > hello.txt. I don't see any permission issue.



> 試一試將`sudo mount -o rw,remount,symfollow -o exec /tmp`中的兩個`-o`結合？ 像這樣：
> 
> ```shell
> sudo mount -o rw,remount,symfollow,exec /tmp
> ```
> 
> (I guess you understand Chinese since that's your system language)
> 
> 順帶一提最好不要聽上面那個怪人的話，那人不停的在這repo的issue裏留廢話
Ho provato a creare un file in /tmp con il comando echo "hello.txt" > hello.txt. Non vedo alcun problema di autorizzazione.

**Comment by TomTravis** [comment]
> 順帶一提最好不要聽上面那個怪人的話，那人不停的在這repo的issue裏留廢話

By the way, it's best not to listen to the weird guy above, who keeps leaving nonsense in the issue of this repo

wow this was not planned is nonsense , there is something else stopping the process, what are you worried about something might take place? super chicken is nonsense

**Comment by TomTravis** [comment]
you also check to see if /bin/sh is present and not a sym link to dash
https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

**Comment by hungshe** [comment]
> you also check to see if /bin/sh is present and not a sym link to dash https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
> 
> you may also make the /mnt /var /bin / as exec as google now check for cmd exec where the cmd came from /bin/sh

Do I need to delete crouton file before remount /mnt, /var, /bin, /  as exec?
I can remount /var, /bin as exec. However, I saw error message while mounting /mnt and / with the following output:

chronos@localhost / $ sudo mount / -o remount,exec
Password: 
mount: /: cannot remount /dev/mmcblk1p3 read-write, is write-protected. -> Should I disable write protection before running debootstrap? I don't see this requirement from any instruction or tutorial movies online before 
chronos@localhost / $ sudo mount /mnt -o remount,exec
mount: /mnt: mount point not mounted or bad option.

Regarding checking shell is running bash or dash, it's bash:

chronos@localhost / $ echo $0
/bin/bash


@supechicken  I tried combing both -o arguments together, it doesn't work.

**Comment by hungshe** [comment]
> yes the fork is easy just google search Github fork super easy , the issue maybe you need a development machine look for as low cost Chromebook maybe to choose from
> 
> once you have a fork you need to complie the code ![Screenshot 2022-11-13 12 39 10 AM](https://user-images.githubusercontent.com/46386261/201513470-ae81ab54-6c90-4edb-a455-c7a8c2e6136a.png)
> 
> if you wish you can join the chroot systemd team I will send you a invite you have a nice effort and the duet is a super chromebook https://github.com/users/TomTravis/projects/3 ![Screenshot 2022-11-13 12 44 50 AM](https://user-images.githubusercontent.com/46386261/201513460-864975d7-08e9-48d3-b734-a9abe46e086b.png)
> 
> Ok great news I don't see any permission issue. this is super good news , then the error is no file is created there is no log file
> 
> you have a invite ![Screenshot 2022-11-13 12 52 26 AM](https://user-images.githubusercontent.com/46386261/201513731-3bfc3196-b83f-4869-8ce0-66f53535dcdf.png)

Do I need to use same model of duet 5 chromebook or can I use any debian based device?

**Comment by TomTravis** [comment]
based on what i read the 7c snap dragon is a SOC (system on a chip) config not the normal , very low power draw and good performance
the new duet use a different CPU and not SOC 
so your duet is unique and create and image for this will be fun adventure

ARM64 chrome book should be fine

**Comment by hungshe** [comment]
> based on what i read the 7c snap dragon is a SOC (system on a chip) config not the normal , very low power draw and good performance this is why your having install problems the new duet use a different CPU and not SOC so your duet is unique and create and image for this will be fun adventure
> 
> ARM64 chrome book should be fine you need to test with you device many low cost arm64 chromebook for sale not SOC
> 
> for the cmd sudo mount -o rw,remount,symfollow -o exec /tmp
> 
> the target /FS mount has to be at the end of the cmd not in the middle $ sudo mount /mnt -o remount,exec is may not matter it is easy to read /tmp /var /bin /run /

I think maybe this is an issue before move into fork debootstrap test:

I just did the following experiment:

localhost# mount /var -o remount,exec
localhost# /bin/hostname
localhost
localhost# cp /bin/hostname /var/
localhost# /var/hostname
localhost
localhost# mount /tmp -o remount,exec
localhost# cp /bin/hostname /tmp/
localhost# /tmp/hostname
bash: /tmp/hostname: /usr/bin/coreutils: bad interpreter: Permission denied
localhost# chmod 777 /tmp/
localhost# /tmp/hostname
bash: /tmp/hostname: /usr/bin/coreutils: bad interpreter: Permission denied

I think that's the reason for permission isssue. How do I successfully remount /tmp as exec section?

This experiment is done after powerwash my device.

**Comment by TomTravis** [comment]
> > based on what i read the 7c snap dragon is a SOC (system on a chip) config not the normal , very low power draw and good performance this is why your having install problems the new duet use a different CPU and not SOC so your duet is unique and create and image for this will be fun adventure
> > ARM64 chrome book should be fine you need to test with you device many low cost arm64 chromebook for sale not SOC
> > for the cmd sudo mount -o rw,remount,symfollow -o exec /tmp
> > the target /FS mount has to be at the end of the cmd not in the middle $ sudo mount /mnt -o remount,exec is may not matter it is easy to read /tmp /var /bin /run /
> 
> I think maybe this is an issue before move into fork debootstrap test:
> 
> I just did the following experiment:
> 
> localhost# mount /var -o remount,exec localhost# /bin/hostname localhost localhost# cp /bin/hostname /var/ localhost# /var/hostname localhost localhost# mount /tmp -o remount,exec localhost# cp /bin/hostname /tmp/ localhost# /tmp/hostname bash: /tmp/hostname: /usr/bin/coreutils: bad interpreter: Permission denied localhost# chmod 777 /tmp/ localhost# /tmp/hostname bash: /tmp/hostname: /usr/bin/coreutils: bad interpreter: Permission denied
> 
> I think that's the reason for permission isssue. How do I successfully remount /tmp as exec section?
> 
> This experiment is done after powerwash my device.

Very Good my suggestion is read the google doc on noexec mount security has done this,, Goog write  they now track cmds issued from where and use what via bash sh dash just be aware of this 

Model:                           2
Model name:                      Cortex-A53
Stepping:                        r0p2
CPU max MHz:                     2106.0000
CPU min MHz:                     507.0000
BogoMIPS:                        26.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening, BHB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid

this what I use
chronos@localhost / $ cat /usr/local/bin/mnt.sh
sudo mount -o remount,symfollow -o exec /media/removable/sd200
sudo mount -o remount,symfollow -o exec /tmp

**Comment by TomTravis** [comment]
the systemd task is now a issue assign to the us
https://github.com/TomTravis/crouton_Penguin/issues/48#issuecomment-1315599763

**Comment by TomTravis** [comment]
i have looks and checked
this is not the issue
bash: /tmp/hostname: /usr/bin/coreutils: bad interpreter: Permission denied
coreutils is a lib of routes for task like chmod chown ...

the is a OS error  **bad interpreter:** Permission denied from the shell
has nothing to do with filesystems and exec paths

**Comment by TomTravis** [comment]
https://github.com/dnschneid/crouton/issues/4884
https://github.com/chromeos/chromeos.dev/issues/559

**Comment by TomTravis** [comment]
try this was change to run in /usr/local/bin
https://drive.google.com/uc?export=download&id=1HFjX1OejjHAYbaHVL3l9krmBUkA1caZR 
test2  same a crouton -r  -t 
this may fix the permission issue
seem to work for me

**Comment by DennisLfromGA** [comment]
https://github.com/dnschneid/crouton/pull/4901 should fix this. Please try again with the latest version of crouton.

**Comment by jason-edward-young** [comment]
hungshe, kind of random, but how did you disable OS verification? I also have a chromebook duet 5, but I'm still having trouble with that setp. I've gotten it into developer mode, but I still can't boot from a non-Chrome external disk.

**Comment by jason0505** [comment]
I have a development machine, codenamed Piglin, HWID is PIGLIN TEST 3600, as far as I know it is a snapdragon third generation processor, but I can't change the date, so I can't log in to my Google account. Is there a third-party BIOS that can install a LINUX operating system?
