### ISSUE TITLE
Cant install Debian on pixelbook. ChromeOS version 109

### ISSUE THREAD

**Issue by eComSt** [dnschneid/crouton#4883]
![Screenshot 2022-11-14 00 29 20](https://user-images.githubusercontent.com/66166134/201535621-a9fe7fbd-1da0-4396-b533-6e3a5afcab6d.png)
![Screenshot 2022-11-14 00 28 14](https://user-images.githubusercontent.com/66166134/201535623-c1632bbe-7a22-48ef-add8-66f7ec68ca75.png)
![Screenshot 2022-11-14 00 27 41](https://user-images.githubusercontent.com/66166134/201535625-5910ec56-e5a4-4bae-a089-df7b3cd6bba5.png)
![Screenshot 2022-11-14 00 26 41](https://user-images.githubusercontent.com/66166134/201535627-ecde9922-64ce-4ca3-86fc-9b994e116775.png)

**Comment by eComSt** [comment]
Please, help me. Troubles begin after chromos was updared on version 107...

**Comment by TomTravis** [comment]
Google Pixelbook (2017)
the permission message is crouton
the debootstrap is no file found 

the script is not creating a file for some reason

you can review the debootstrap 

the mount maybe modified via debootstap when the install happens
on the install 
crouton ...-r -t  |tee ~/Downloads/inst.txt this will create a install log called inst.txt in Download you can look at it via chromeOS

**Comment by TomTravis** [comment]
try this was change to run in /usr/local/bin
https://drive.google.com/uc?export=download&id=1HFjX1OejjHAYbaHVL3l9krmBUkA1caZR
test2 same a crouton -r -t
this may fix the permission issue
seem to work for me

**Comment by drinkcat** [comment]
#4901 should fix this. Please try again with the latest version of crouton.
