### ISSUE TITLE
Failed - Download error

### ISSUE THREAD

**Issue by ChaosUntamed** [dnschneid/crouton#4885]
While in the chroot, running Ubuntu Focal Fossa 20.04, any time I try to download a file from the internet using the browser the download immediately fails. No error message is given.

**Comment by TomTravis** [comment]
download to where the Downloads folder ?
The folder is protected by PAMd you need to edit a file or change you download folder in you browser

chronos@localhost /media/removable/sd200/chroots/kr/etc/pam.d $ ls
chfn            common-password                lightdm-autologin  other      sshd    xscreensaver
chpasswd        common-session                 lightdm-greeter    passwd     su
chsh            common-session-noninteractive  login              polkit-1   su-l
common-account  cron                           monit              runuser    sudo
common-auth     lightdm                        newusers           runuser-l  sudo-i
chronos@localhost /media/removable/sd200/chroots/kr/etc/pam.d $ cat su-l
#%PAM-1.0
auth            include         su
account         include         su
password        include         su
#session                optional        pam_keyinit.so force revoke
session         include         su
chronos@localhost /media/removable/sd200/chroots/kr/etc/pam.d $ 

comment this line out #session                optional        pam_keyinit.so force revoke
restart the chroot 

the Downloads folder is now writable

**Comment by ChaosUntamed** [comment]
Changing the folder worked perfect. I'll see if I can't file the directions to make the download folder work like intended as well. Thank you!

**Comment by TomTravis** [comment]
the Download folder is mapped to ChromeOS as a share it is useful the line comment out is simple to do
cd /etc/pam.d
sudo nano su-l
comment out line
^o to write the file
^x or exit nano
restart the chroot

see shared in /etc/crouton
