### ISSUE TITLE
Focal does not install on SD Card

### ISSUE THREAD

**Issue by ShipmasterKyle** [dnschneid/crouton#4887]
#### Please describe your issue:
focal does not install on SD Card

#### If known, describe the steps to reproduce the issue:
- Format SD Card
- sudo crouton -r focal -t xorg,audio,core,gtk-extra,x11,xfce -p /media/removable/SD\ Card/

Output:
```
WARNING: focal is an unsupported release.
You will likely run into issues, but things may work with some effort.
Press Ctrl-C to abort; installation will continue in 5 seconds.
Installing focal-amd64 chroot to /media/removable/SD Card/chroots/focal
Downloading bootstrap files...
/tmp/crouton-installer-cache/crouton: 95: /tmp/crouton-installer-cache/crouton.GLj/installer/ubuntu/bootstrap: /tmp/crouton.bvu/debootstrap: Permission denied
debootstrap error log:
tail: cannot open '/tmp/crouton.bvu/focal-amd64/debootstrap/debootstrap.log' for reading: No such file or directory
Failed to run debootstrap.
```

**Comment by TomTravis** [comment]
check to see if the mnt are exec
this is my mnt.sh
sudo mount -o remount,symfollow -o exec /media/removable/sd200
sudo mount -o remount,symfollow -o exec /tmp    
sudo mount -o remount,symfollow -o exec /var/run
sudo mount -o remount,symfollow -o exec /

also please post 
in chrome
chrome://system screen capture

**Comment by ShipmasterKyle** [comment]
none of the commands worked. 

https://vimeo.com/771420755/2fdb098c34

**Comment by TomTravis** [comment]
> none of the commands worked.
> 
> https://vimeo.com/771420755/2fdb098c34

i did not see any commands the mount exec commands the video show chrome://system

https://chromeos.guide/chromeosdevices/hpcareena

**Comment by ShipmasterKyle** [comment]
![image](https://user-images.githubusercontent.com/79712264/202173765-1a3b7179-97ac-47b4-a245-f37d4479feff.png)

**Comment by TomTravis** [comment]
howdy 
yep what happened is thank V107ChromeOS made some security changes and the install shell debootstrap fails for new install 
i make bootstrap images and put them in my repo release files
debian Kali and Ubuntu

you can also Powerwash your device using ctrl+alt+shift+R to revert back to v106 will it will work again

**Comment by TomTravis** [comment]
https://github.com/dnschneid/crouton/issues/4884
https://github.com/chromeos/chromeos.dev/issues/559

**Comment by ShipmasterKyle** [comment]
> howdy 
> yep what happened is thank V107ChromeOS made some security changes and the install shell debootstrap fails for new install i make bootstrap images and put them in my repo release files debian Kali and Ubuntu
> 
> you can also Powerwash your device using ctrl+alt+shift+R to revert back to v106 will it will work again

Dang. I figured it was the new updates. >v96 has been giving me issues anyways.

**Comment by TomTravis** [comment]
try this was change to run in /usr/local/bin
https://drive.google.com/uc?export=download&id=1HFjX1OejjHAYbaHVL3l9krmBUkA1caZR
test2 same a crouton -r -t
this may fix the permission issue
seem to work for me

**Comment by dnschneid** [comment]
Latest crouton should fix the error in the original issue, so please try again.
