### ISSUE TITLE
crouton install ubuntu -r jammy failed,what can I do next???

### ISSUE THREAD

**Issue by xiaomeixw** [dnschneid/crouton#4910]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:

E: Package 'ttf-ubuntu-font-family' has no installation candidate
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/jammy...

**Comment by xiaomeixw** [comment]
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-ubuntu-font-family' has no installation candidate
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in jammy
Unmounting /mnt/stateful_partition/crouton/chroots/jammy...

**Comment by shynababe** [comment]
i just use -r jammy -t xorg,xiwi,xfce
it works for me

**Comment by xiaomeixw** [comment]
Finally, I solved the problem by installing debian
Thanks...

**Comment by xiaomeixw** [comment]
sudo bash installer/main.sh -u -n buster -t lxde -P http://porxy_id:proxy_port
