### ISSUE TITLE
crouton command not running

### ISSUE THREAD

**Issue by sheeshdagamer** [dnschneid/crouton#4915]
when i run the command to copy it,it copys.but then, when i run it, no matter the arguments it always shows the help commands.i cant even install because iit wont work

chronos@localhost / $ sudo crouton -n sussypc -r xenial
crouton [options] -t targets
crouton [options] -f backup_tarball
crouton [options] -d -f bootstrap_tarball

Constructs a chroot for running a more standard userspace alongside Chromium OS.

If run with -f, where the tarball is a backup previously made using edit-chroot,
the chroot is restored and relevant scripts installed.

If run with -d, a bootstrap tarball is created to speed up chroot creation in
the future. You can use bootstrap tarballs generated this way by passing them
to -f the next time you create a chroot with the same architecture and release.

crouton must be run as root unless -d is specified AND fakeroot is
installed AND /tmp is mounted exec and dev.

It is highly recommended to run this from a crosh shell (Ctrl+Alt+T), not VT2.

Options:
    -a ARCH     The architecture to prepare a new chroot or bootstrap for.
                Default: autodetected for the current chroot or system.
    -b          Restore crouton scripts in PREFIX/bin, as required by the
                chroots currently installed in PREFIX/chroots.
    -d          Downloads the bootstrap tarball but does not prepare the chroot.
    -e          Encrypt the chroot with ecryptfs using a passphrase.
                If specified twice, prompt to change the encryption passphrase.
    -f TARBALL  The bootstrap or backup tarball to use, or to download to (-d).
                When using an existing tarball, -a and -r are ignored.
    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
                If unspecified, the keys will be stored in the chroot if doing a
                first encryption, or auto-detected on existing chroots.
    -m MIRROR   Mirror to use for bootstrapping and package installation.
                Default depends on the release chosen.
                Can only be specified during chroot creation and forced updates
                (-u -u). After installation, the mirror can be modified using
                the distribution's recommended way.
    -M MIRROR2  A secondary mirror, often used for security updates.
                Can only be specified alongside -m.
    -n NAME     Name of the chroot. Default is the release name.
                Cannot contain any slash (/).
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
    -P PROXY    Set an HTTP proxy for the chroot; effectively sets http_proxy.
                Specify an empty string to remove a proxy when updating.
    -r RELEASE  Name of the distribution release. Default: xenial,
                or auto-detected if upgrading a chroot and -n is specified.
                Specify 'help' or 'list' to print out recognized releases.
    -t TARGETS  Comma-separated list of environment targets to install.
                Specify 'help' or 'list' to print out potential targets.
    -T TARGETFILE  Path to a custom target definition file that gets applied to
                the chroot as if it were a target in the crouton bundle.
    -u          If the chroot exists, runs the preparation step again.
                You can use this to install new targets or update old ones.
                Passing this parameter twice will force an update even if the
                specified release does not match the one already installed.
    -V          Prints the version of the installer to stdout.

Be aware that dev mode is inherently insecure, even if you have a strong
password in your chroot! Anyone can simply switch VTs and gain root access
unless you've permanently assigned a Chromium OS root password. Encrypted
chroots require you to set a Chromium OS root password, but are still only as
secure as the passphrases you assign to them.

**Comment by DennisLfromGA** [comment]
@sheeshdagamer,

You need to specify some targets with the `-t` option.
Pick one or more of the below (found by running `crouton -t list`), as shown:
```
crouton -t list
Available targets:
audio
	Support audio playback via Chromium OS's audio system.
	Requires: core
chrome
	Google Chrome browser, stable channel.
	Requires: x11
chrome-beta
	Google Chrome browser, beta channel.
	Requires: x11
chrome-dev
	Google Chrome browser, dev channel.
	Requires: x11
chromium
	Chromium browser. Uses the distro's version, which may be old.
	Requires: x11
cli-extra
	Basic CLI tools such as ssh.
	Requires: core
core
	Performs core system configuration. Most users would want this.
e17
	Installs the enlightenment desktop environment. (Approx. 50MB)
	Requires: gtk-extra
extension
	Clipboard synchronization and URL handling with Chromium OS.
	Requires: x11
gnome
	Installs the GNOME desktop environment. (Approx. 400MB)
	Requires: gtk-extra
gnome-desktop
	Installs GNOME along with common applications. (Approx. 1100MB)
	Requires: gnome
gtk-extra
	GTK-based tools including gdebi and a simple browser.
	Requires: x11
kde
	Installs a minimal KDE desktop environment. (Approx. 600MB)
	Requires: x11
kde-desktop
	Installs KDE along with common applications. (Approx. 1000MB)
	Requires: kde
keyboard
	Adds support for Chromebook keyboard special keys.
	Requires: x11
kodi
	Installs the KODI media player. (Approx. 200MB)
	Requires: x11
lxde
	Installs the LXDE desktop environment. (Approx. 200MB)
	Requires: gtk-extra
lxde-desktop
	Installs LXDE along with common applications. (Approx. 800MB)
	Requires: lxde
touch
	Touchscreen and limited generic gesture support.
	Requires: x11
unity
	Installs the Unity desktop environment. (Approx. 700MB)
	Requires: gtk-extra
unity-desktop
	Installs Unity along with common applications. (Approx. 1100MB)
	Requires: unity
x11
	X11 via autodetected backend. Does not install any desktop environment.
xfce
	Installs the Xfce desktop environment. (Approx. 250MB)
	Requires: gtk-extra
xfce-desktop
	Installs Xfce along with common applications. (Approx. 1200MB)
	Requires: xfce
xiwi
	X.org X11 backend running unaccelerated in a Chromium OS window.
	Requires: audio extension
xorg
	X.Org X11 backend. Enables GPU acceleration on supported platforms.
	Requires: audio
```
I typically like to use the LXDE desktop target along with some other things like both xmethods, etc., see below for something similar to your use case:

`sudo crouton -n sussypc -r xenial -t xorg,xiwi,cli-extra,keyboard,touch,lxde-desktop,chrome-beta`

But you can choose your desktop preference and other targets of course.

*Hope this helps,*
-**DennisLfromGA**

**Comment by sheeshdagamer** [comment]
ill try the command you gave and see if it works.thanks for the help :)
