### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by englosh** [dnschneid/crouton#4917]
sudo: edit-chroot: command not found)

I am trying to get onto a TigerVNC server by typing "kex --win -s" but it won't let me. it just says this:
"Error connecting to the KeX server.
Please try "kex start" to start the service.
If the server fails to start, please try "kex kill" or restart your WSL2 session and try again."

So then I search online how to solve my problem and it says online to type:
"vncserver -localhost no"
but then kali just says(I'm replacing all my private info with "個人的":

"Killing Xtigervnc process ID 1038... success!

=================== tail /home/個人的/.vnc/個人的.:5901.log ===================
_XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
_XSERVTransSocketCreateListener: failed to bind listener
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix

Xvnc TigerVNC 1.12.0 - built 2022-12-17 19:13
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12101005, X.Org

Mon Jan  2 16:49:52 2023
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
[mi] mieq: warning: overriding existing handler (nil) with 0x56192eb85180 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x56192eb85180 for event 3

Mon Jan  2 16:50:22 2023
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
===============================================================================

vncserver: /usr/bin/Xtigervnc did not start up, please look into '/home/個人的/.vnc/個人的.:5901.log' to determine the reason! -1"

What do I do?

**Comment by DennisLfromGA** [comment]
@englosh,

This does not appear to be a  `crouton` issue, please seek help on a site that supports the vncserver.

-**DennisLfromGA**
