### ISSUE TITLE
Python is outdated, and pip doesn't work

### ISSUE THREAD

**Issue by RandomGamer368** [dnschneid/crouton#4919]
python is disturbingly old (3.5). please either update python and support pip (missing), or ask users what version(s) of python they want. I can not get a working python/pip otherwise

**Comment by dnschneid** [comment]
You probably want something newer than xenial, then.  See [the readme](https://github.com/dnschneid/crouton#hey-now-ubuntu-1604-is-pretty-old-im-young-and-hip) for instructions on how to install a different release.
