### ISSUE TITLE
Xorg failure    xf86OpenConsole: Cannot open virtual console 2 (Permission denied)

### ISSUE THREAD

**Issue by sheeshdagamer** [dnschneid/crouton#4920]
```
Please paste the output of the following command here: sudo edit-chroot -all
name: sussypc
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/sussypc...
/usr/local/bin/crash_reporter_wrapper: 119: exec: /var/run/crw/crw: Permission denied
WARNING: Unable to register core dump handler.
crouton: version 1-20221126232257~master:ae594340
release: bullseye
architecture: amd64
xmethod: xorg
targets: xorg,xiwi,cli-extra,extension,keyboard,lxde-desktop,chrome-beta
host: version 15183.59.0 (Official Build) stable-channel dedede 
kernel: Linux localhost 5.4.217-19684-g8dacb33c82e1 #1 SMP PREEMPT Mon Nov 28 21:46:19 PST 2022 x86_64 GNU/Linux
freon: no
Unmounting /mnt/stateful_partition/crouton/chroots/sussypc...
chronos@localhost / $ 
```

#### If known, describe the steps to reproduce the issue: using sudo startlxde in shell
chronos@localhost / $ sudo startlxde
Entering /mnt/stateful_partition/crouton/chroots/sussypc...
/usr/local/bin/crash_reporter_wrapper: 119: exec: /var/run/crw/crw: Permission denied
WARNING: Unable to register core dump handler.
X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux localhost 5.4.217-19684-g8dacb33c82e1 #1 SMP PREEMPT Mon Nov 28 21:46:19 PST 2022 x86
_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootw
ait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 6553600 verity p
ayload=PARTUUID=f7c461ed-33ef-5245-b72e-179a1bc6b986/PARTNROFF=1 hashtree=PARTUUID=f7c461ed-33ef-5245-b72e-179a1bc6b9
86/PARTNROFF=1 hashstart=6553600 alg=sha256 root_hexdigest=20a9632a451e89cbf9c3bb7af90e3d45ee51e133a787413dce10784209
bae16e salt=f2fe9273be2d583491fbed648e90f72068539f1f035d3b495988bf3048f69f2f" noinitrd vt.global_cursor_default=0 ker
n_guid=f7c461ed-33ef-5245-b72e-179a1bc6b986 add_efi_memmap boot=local noresume noswap i915.modeset=1 i915.enable_guc=
2 intel_pmc_core.warn_on_s0ix_failures=1  
Build Date: 11 November 2022  12:37:52PM
xorg-server 2:1.20.11-1+deb11u3 (https://www.debian.org/support) 
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/home/potato/.local/share/xorg/Xorg.1.log", Time: Thu Jan  5 07:55:56 2023
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/home/potato/.local/share/xorg/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/sussypc...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/sussypc...
chronos@localhost / $

**Comment by sheeshdagamer** [comment]
sudo enter-chroot startlxde also does not work

**Comment by sheeshdagamer** [comment]
now i get a different error

**Comment by sheeshdagamer** [comment]
xf86OpenConsole: Cannot open virtual console 1 (Permission denied)

**Comment by sheeshdagamer** [comment]
and when i run lxde from crosh now i get (EE) xf86OpenConsole: Cannot open virtual console 2 (Permission denied)

**Comment by sheeshdagamer** [comment]
no matter what i try i can not get x to run

**Comment by sheeshdagamer** [comment]
closing as i am reinstalling crouton

**Comment by bestplayer334** [comment]
okay
