### ISSUE TITLE
!Im trying to install Crouton but it it fails opening 

### ISSUE THREAD

**Issue by ViA8604** [dnschneid/crouton#4941]
I put the code:=>   Chronos@localhost / $ sudo sh /Downloads/crouton -e -t unity
And then it says:=> [ ](sh: 0: Can't open /Downloads/crouton)

I'm new at this, don't know what I'm doing wrong, I copied the files of crouton in Downloads.

**Comment by DennisLfromGA** [comment]
You need to read [the installation instructions](https://github.com/dnschneid/crouton#usage), it's changed from what you're using.

-**DennisLfromGA**

**Comment by ViA8604** [comment]
Ok, thanks, finally it worked.
