### ISSUE TITLE
help: edit chroot to target bionic, instead of unity

### ISSUE THREAD

**Issue by Essen73** [dnschneid/crouton#4963]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: xenial
encrypted: yes, locked
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

#### Please describe your issue:
I did do-release upgrade using the Ubuntu command line and upgraded to bionic from xenial
bionic was working but seemed a bit unstable, for example google maps kept crashing; so decided to logout and restart
while logging back in to Ubuntu using sudo startunity, realized that I needed to change 'startunity' to some other target specific to bionic
I am stuck at this step - how do I edit chroot to work with the bionic ubuntu

**Comment by Essen73** [comment]
@ducksosu That's awesome; it worked; with the xfce I can access all my previous files in libreoffice etc. Thanks.  The unity path does not work, but thats OK.  I now need to understand how chroot works; although I am creating a new chroot, how is it finding and connecting to my previous linux environment etc...

**Comment by ducksosu** [comment]
your welcome! (you should probably close the issue since its no longer an issue)
