### ISSUE TITLE
i can't install linux on chromOS version 112

### ISSUE THREAD

**Issue by gayaslimani** [dnschneid/crouton#4964]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
![1681603145985](https://user-images.githubusercontent.com/130874926/232259088-d6159da8-a61e-42e3-87ba-178949910806.jpg)
![Screenshot 2023-04-16 1 02 16 AM](https://user-images.githubusercontent.com/130874926/232259156-443036e5-44ce-46f7-b61b-4ef61c3fd895.png)
pls help i need ot so much

**Comment by Eaterminer** [comment]
This is a crostini issue, not a crouton one.

Yes, crostini and crouton can sound similar, but they are different
