### ISSUE TITLE
Critical graphics error in crouton!!!

### ISSUE THREAD

**Issue by Qwer-TeX** [dnschneid/crouton#4984]
I recently installed Jammy xfce using
`sudo CROUTON_BRANCH=silence crouton -r jammy -t core,cli-extra,x11,xorg,gtk-extra,extension,audio,xfce,xfce-desktop,xiwi,keyboard `and the graphics are messed up for some reason. I don't know if some graphics libraries are missing or if it is a hardware issue.

If I open GIMP, I see that there is a lag, almost of a glitch.
[Screen recording 2023-06-07 5.20.48 PM.webm](https://github.com/dnschneid/crouton/assets/128016252/22a905d3-1567-4d6e-87d1-1138066a9f6d)

Even if I try to play colobot gold edition, the graphics are messed up
[Screen recording 2023-06-07 10.11.26 PM.webm](https://github.com/dnschneid/crouton/assets/128016252/19c52341-bf9c-45f5-916f-dfe780585bc3)
Can anyone help me out. I don't know how to do bug hunting on this issue.

-edit: I also found that this also applies in the Netsurf browser but with the fonts messed up
I also see that all application menus have messed up and broken fonts. 
for example a **W** would look like **VV**

[Screen recording 2023-06-07 10.28.39 PM.webm](https://github.com/dnschneid/crouton/assets/128016252/51d66e7b-7a68-4f90-b086-0935b2879b25)
Don't you notice the difference, The font rendering is broken. I can't fix it :(
Please send help **:(**

**Comment by CroutonIsFun** [comment]
I cannot even get an xsession. I didn't install the xiwi target, however. This is the first time I've tried jammy. I've been using bullseye and focal.

**Comment by Qwer-TeX** [comment]
#1519 fixed it

**Comment by Qwer-TeX** [comment]
#1519 fixed it

**Comment by Qwer-TeX** [comment]
.
