### ISSUE TITLE
/prepare.sh: 726: /prepare.sh: ar: not found |  WHY is crouton broken like that???

### ISSUE THREAD

**Issue by Qwer-TeX** [dnschneid/crouton#4992]
I used `sudo CROUTON_BRANCH=silence crouton -t xfce`

at the end I get this
`prepare.sh: 726: /prepare.sh: ar: not found
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`

why are there so many errors in crouton?

**Comment by ducksosu** [comment]
#4959 try installing with CROUTON_BRANCH=silence crouton ...

**Comment by Qwer-TeX** [comment]
I did some time ago but I don't see this error anymore.
