### ISSUE TITLE
Can't add widget to panel or desktop under KDE 

### ISSUE THREAD

**Issue by rogue117** [dnschneid/crouton#500]
Plasma not working properly (for example with the ability to add plasmoids to the panel or desktop) in KDE. 

Several users have the same issue. All with samsung arm chromebook.

**Comment by Firestarthirty** [comment]
As a chromebook arm user I confirm this to still be a problem

**Comment by dnschneid** [comment]
It's possible there's an issue with their software rendering (since there's no GPU acceleration on ARM).  Did anyone search the KDE/Plasma bugtracker?

**Comment by Firestarthirty** [comment]
No wheres that? (Im not really a big linux guy)

**Comment by edrouin** [comment]
Any solution yet? I have the same problem on Asus arm chromebook.
