### ISSUE TITLE
Incorrect instruction

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [dnschneid/crouton#5017]
One can no longer simply use sudo inside of the crosh shell.
The only way currently possible Is to use VT-2 which tells you to use crosh but that is not possible. Please, do something about this. Thanks for working hard!

**Comment by CroutonIsFun** [comment]
> One can no longer simply use sudo inside of the crosh shell. The only way currently possible Is to use VT-2 which tells you to use crosh but that is not possible. Please, do something about this. Thanks for working hard!

[How to proceed](https://github.com/dnschneid/crouton/discussions/5013)

**Comment by Dae-Hang-Sook** [comment]
> > One can no longer simply use sudo inside of the crosh shell. The only way currently possible Is to use VT-2 which tells you to use crosh but that is not possible. Please, do something about this. Thanks for working hard!
> 
> [How to proceed](https://github.com/dnschneid/crouton/discussions/5013)

'apt' is not a command that is usable inside of crosh or VT-2

**Comment by CroutonIsFun** [comment]
Yes, apt can be used! In fact, you can run a crouton chroot inside VT-2. You just can't get a desktop.

The idea is to install crouton from VT-2, then ssh into it from the crosh shell.

**Comment by Dae-Hang-Sook** [comment]
> Yes, apt can be used! In fact, you can run a crouton chroot inside VT-2. You just can't get a desktop.
> 
> The idea is to install crouton from VT-2, then ssh into it from the crosh shell.

Then it must be device specific. I can't use it as chronos or root as it tells me every single time it's not a known command.

**Comment by DennisLfromGA** [comment]
@Dae-Hang-Sook,

> 'apt' is not a command that is usable inside of crosh or VT-2

That is correct, chromeOS does not use the 'apt' package manager.

Your chroot distro most likely can use 'apt' if it's Debian-based like Ubuntu, etc. so you'll need to enter your chroot first to use 'apt'.

-**DennisLfromGA**

**Comment by Dae-Hang-Sook** [comment]
> @Dae-Hang-Sook,
> 
> > 'apt' is not a command that is usable inside of crosh or VT-2
> 
> That is correct, chromeOS does not use the 'apt' package manager.
> 
> Your chroot distro most likely can use 'apt' if it's Debian-based like Ubuntu, etc. so you'll need to enter your chroot first to use 'apt'.
> 
> -**DennisLfromGA**

That's the point of the issue. I can't do exactly that because the only 'known' fix is an apt command which is unusable

**Comment by DennisLfromGA** [comment]
@Dae-Hang-Sook,

> That's the point of the issue. 

I thought the *point* of the issue was in your first remark:

> One can no longer simply use sudo inside of the crosh shell.
> The only way currently possible Is to use VT-2 which tells you to use crosh but that is not possible. 

The chromeOS team has removed 'sudo' from the crosh shell.
You can use 'sudo' as user 'chronos' in a Develeoper Console via VT-2.

> Please, do something about this.

We can't, you'll have to appeal to the chromeOS team by filing a feedback report and/or opening a crbug.

> I can't do exactly that because the only 'known' fix is an apt command which is unusable

Using 'apt' is *not* a *fix* for the above since 'apt' is not a viable command in chromeOS.
As I tried to explain above, your chroot distro most likely can use 'apt' if it's Debian-based like Ubuntu, etc. so you'll need to enter your chroot first to use 'apt'.

-DennisLfromGA

**Comment by Dae-Hang-Sook** [comment]
> @Dae-Hang-Sook,
> 
> > That's the point of the issue. 
> 
> I thought the *point* of the issue was in your first remark:
> 
> > One can no longer simply use sudo inside of the crosh shell.
> > The only way currently possible Is to use VT-2 which tells you to use crosh but that is not possible. 
> 
> The chromeOS team has removed 'sudo' from the crosh shell.
> You can use 'sudo' as user 'chronos' in a Develeoper Console via VT-2.
> 
> > Please, do something about this.
> 
> We can't, you'll have to appeal to the chromeOS team by filing a feedback report and/or opening a crbug.
> 
> > I can't do exactly that because the only 'known' fix is an apt command which is unusable
> 
> Using 'apt' is *not* a *fix* for the above since 'apt' is not a viable command in chromeOS.
> As I tried to explain above, your chroot distro most likely can use 'apt' if it's Debian-based like Ubuntu, etc. so you'll need to enter your chroot first to use 'apt'.
> 
> -DennisLfromGA
> 
> 
> 

Incapable of running the chroot. That's the issue.

**Comment by DennisLfromGA** [comment]
@Dae-Hang-Sook,

If you are incapable of running the chroot then you are doing it wrong.
Take a look at the Discussion below for tips on how to run a chroot using VT-2 and ssh in the crosh shell:

- Setting up a Crouton desktop under new conditions #5013

-**DennisLfromGA**

**Comment by Dae-Hang-Sook** [comment]
> @Dae-Hang-Sook,
> 
> If you are incapable of running the chroot then you are doing it wrong.
> Take a look at the Discussion below for tips on how to run a chroot using VT-2 and ssh in the crosh shell:
> 
> - Setting up a Crouton desktop under new conditions #5013
> 
> -**DennisLfromGA**
> 
> 

Followed this. Can't run it because all it does is tell me to run it from crosh. I'm incapable of doing just that because using sudo in crosh is no longer an option. I can't 'apt' anything because it doesn't allow it to be run from the VT-2

**Comment by DennisLfromGA** [comment]
@Dae-Hang-Sook,

Others have had success with those instructions, including yours truly.

Perhaps you should take another look at it and follow it step-by-step. 
If you get stuck then comment in that Discussion thread, not here.

-**DennisLfromGA**
