### ISSUE TITLE
every app I open that isn't in wine just kills the chromebook

### ISSUE THREAD

**Issue by ducksosu** [dnschneid/crouton#5028]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
cant paste from frecon but I don't think the hardware is relevant as it just started happening on update 118.0.5993.86 and it's never happened before this update 

#### Please describe your issue:
ever since I updated to the update above, I can't open native Linux apps in Ubuntu 18.03 xfce4 

#### If known, describe the steps to reproduce the issue:
open Linux try opening something like chrome then chromebook just restarts itself 

[this is a video of what's happening](https://drive.google.com/file/d/1Yg9G2ivxjYkU06eWScqZeLFxzZsHUMIs/view?usp=drivesdk)

**Comment by dodfsk** [comment]
#4790 it seems like a same issue

**Comment by dodfsk** [comment]
> @dodfsk so how do i fix this

I have given up crouton and use crostini. vscode in crostini is so slow, code-server + chromeos native browser will be better.
I'm also looking for a way to use crouton,but since v107,chromeos updates have broken too much about crouton.
Maybe it's time

**Comment by paul4334** [comment]
I do not know if this helps, but I found that this issue is occurring running any Electron-based app on an arm64 CB running v118 and v119.

**Comment by dodfsk** [comment]
> I do not know if this helps, but I found that this issue is occurring running any Electron-based app on an arm64 CB running v118 and v119.
> 
> The following ramoops attachment is from launching Chromium from a Debian bullseye crouton install - [dmesg-ramoops-0.txt](https://github.com/dnschneid/crouton/files/13443627/dmesg-ramoops-0.txt)
> 
> Crouton Install Info: [crouton_info.txt](https://github.com/dnschneid/crouton/files/13443691/crouton_info.txt)

it's also exists on x86 CB(pixel_slate),i think this issue occurs since upgrading to linux kernel 5.x

**Comment by ducksosu** [comment]
so I have just switched completely to ubuntu 22.04 using mrchromeboxes firmware util script so I won't be needing this anymore
