### ISSUE TITLE
Large Files download failing.

### ISSUE THREAD

**Issue by LegalDavidDaniel** [dnschneid/crouton#5029]
```
name: focal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/focal...
crouton: version 1-20221126232257~master:ae594340
release: focal
architecture: amd64
xmethod: xorg
targets: xfce
host: version 14092.77.0 (Official Build) stable-channel kip 
kernel: Linux localhost 4.4.254-20726-g204ae1828356 #1 SMP PREEMPT Sun Oct 3 21:32:56 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/focal...
```

#### Please describe your issue:
The browsers in my Linux environment are unable to download large files, it would not download any file larger than 10 MB,  it would fail without trying. downloading vs code extensions timeout or fails for reasons i don't know. The problem is not my internet connection because downloading works fine in the chromeOs desktop. 
Also trying to do `sudo sh -e ~/Downloads/crouton -u -t xiwi` results in `sh: 0: Refusing to exec crouton from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md`

#### If known, describe the steps to reproduce the issue:
I don't know what to do to improve the download problem, i have search on google.

**Comment by CroutonIsFun** [comment]
You're using the old instructions. Read the intro: you have to make crouton executable. Also, commands have to be executed in VT-2, not the crosh shell. Look at the various discussion posts recently for more info.

**Comment by LegalDavidDaniel** [comment]
> You're using the old instructions. Read the intro: you have to make crouton executable. Also, commands have to be executed in VT-2, not the crosh shell. Look at the various discussion posts recently for more info.

The readme still says I have to press ctrl + shit + t to run any commands. Which other intro am I missing?

**Comment by LegalDavidDaniel** [comment]
i was able to download files by changing the download folder settings in my browser to a folder i create in /Desktop. i guess the default download folder cannot be modified by the browsers.
