### ISSUE TITLE
Is there any way to install Arduino on chromebook?

### ISSUE THREAD

**Issue by Mikroprocessor** [dnschneid/crouton#503]
Is there any way to install Arduino on chromebook?

I have tried to unlock the write protection but i have not succeeded.
I have tried to create own programs for the chromebook but chromebook do not use programs, only apps. 

I just want to install Arduino on my Acer C7. After that i got everything i need.
If it possible to install Ardino on a SD-card and run it from there? 

BIOS is locked to the hardware and i cannot unlock the BIOS to install Windows 7.

**Comment by antoniscb** [comment]
Hello there. 

We are codebender, an online browser-based IDE for all Arduino users, makers and engineers out there.
We provide you the ability to write, save, access and if you wish share your code from everywhere. 
Just install our Chrome app or Firefox plug in and start programming!

But maybe you are aware of all these so why we bother you? What is going on?

You own a Chromebook and you always wanted to program your Arduino with it?
This is what we were working on for the last months!

codebender can now support Chromebooks!
Come "play" with your code on www.codebnder.cc and find out the potentials we can provide to you.
We preferred to keep silent but now it is time to say out loud : Your chromebook is supported!

Sorry for bothering and thank you for reading.
Antonis for the codebender team

**Comment by DGO143** [comment]
Do you mean the Arduino IDE or the actual firmware?

**Comment by antoniscb** [comment]
Hello there!

Actually nothing off these :-)..codebender provides you and online IDE and
you dont have to download/install anything..
You just open a web page and you write your code :-) of course if you need
to flash your sketch you still need a board..

And now codebender can run on chromebooks..so you can write code also from
a chromebook!

Best Regards
Antonis CC
