### ISSUE TITLE
unable to enter chroot

### ISSUE THREAD

**Issue by daniel020203** [dnschneid/crouton#5033]
```
Please paste the output of the following command here: sudo enter-chroot
```

#### Please describe your issue: 
Entering /mnt/stateful_partition/crouton/chroots/kali...
/usr/local/bin/crash_reporter_wrapper: 119: exec: /var/run/crw/crw: Permission denied
WARNING: Unable to register core dump handler.

**Comment by CroutonIsFun** [comment]
This is not a failure to enter chroot. I get this every time. I'm not sure what causes it, but you can ignore it for now. It has not prevented me from using crouton.
