### ISSUE TITLE
Xorg X11 servers cannot be launched from Frecon, return to Chromium OS and use Crosh to launch X

### ISSUE THREAD

**Issue by Whywontthisthingwork** [dnschneid/crouton#5037]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
Can't because of the error constantly terminating the connection to the chroot

#### Please describe your issue:
Sudo is disabled in the Crosh shell after about R119, fixed that by using the VT2 shell, auto tools has been removed, fixed that by using CROSH_BRANCH=silence, now the error described in the title shows up whenever I try sudo startgnome or sudo enter-chroot startgnome

#### If known, describe the steps to reproduce the issue:
Have a Lenovo IdeaPad Duet without the keyboard pack, with a USB-C dongle and a wired iMac keyboard and wireless mouse and the worst timing to try Crouton in the world.

**Comment by Whywontthisthingwork** [comment]
It also happens whenever I try anything with -chroot at the end (edit-chroot, enter-chroot, etc.) but not when I use delete-chroot.

Tried all desktop environments and I am not skilled enough for not using them. Unity and Unity-Desktop do not work because I am trying to use Xenial and the last arm-based build of Unity was for Precise.

**Comment by akang22** [comment]
See https://github.com/dnschneid/crouton/discussions/5013. You can't open x11 servers from the vt2 shell.
