### ISSUE TITLE
shell unknown command

### ISSUE THREAD

**Issue by burnsboyamazing** [dnschneid/crouton#5039]
```
Please paste the output of the following command here: shell
```

#### Please describe your issue: shell is an unknown command. Uploading the screenshot.
![Screenshot 2023-12-25 9 39 59 PM](https://github.com/dnschneid/crouton/assets/154830140/d4b6cef8-40dd-4b60-811a-5f5f781d63b6)

#### If known, describe the steps to reproduce the issue: shell is an unknown command. Uploading the screen recording.
[Screen recording 2023-12-25 9.39.20 PM.webm](https://github.com/dnschneid/crouton/assets/154830140/8da7f52e-d02f-4697-9ac3-fe1f51d5012f)

**Comment by CroutonIsFun** [comment]
it looks like you're not in developer mode
