### ISSUE TITLE
dnschneid.github.io 404 not found

### ISSUE THREAD

**Issue by burnsboyamazing** [dnschneid/crouton#5040]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue: dnschneid.github.io not found.
![Screenshot 2023-12-25 9 43 10 PM](https://github.com/dnschneid/crouton/assets/154830140/a3cd8b04-7547-4df4-bd48-f41dc7a7dd79)

**Comment by CroutonIsFun** [comment]
[croutonb](https://github.com/dnschneid/crouton)
