### ISSUE TITLE
When you try to google "shell" redirects to Google Search page

### ISSUE THREAD

**Issue by burnsboyamazing** [dnschneid/crouton#5042]
```
Please paste the output of the following command here: shell
```

#### Please describe your issue: Googling "shell" redirects to the Google Search page. Attaching the video here.
[Screen recording 2023-12-27 10.53.15 AM.webm](https://github.com/dnschneid/crouton/assets/154830140/0493f4f7-bffa-4430-8df4-9969f0c879fd)

#### If known, describe the steps to reproduce the issue:
1. Google "Shell".
2. It redirects to Google Search page.

#### Expected behaviour:
At https://github.com/dnschneid/crouton/issues/5039 without googling "shell", same issue appears. Attaching another video here.
[Screen recording 2023-12-27 10.55.50 AM.webm](https://github.com/dnschneid/crouton/assets/154830140/8276d107-e89c-4b86-84ed-d0c9448d1d90)

**Comment by DennisLfromGA** [comment]
Please **stop** opening *non-issues*, do more research before asking these types of questions.

You first need to enable Developer mode, see below:

- https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_mode.md

Then you need to use the , see below:

- https://github.com/dnschneid/crouton/discussions/5013

-**DennisLfromGA**

**Comment by burnsboyamazing** [comment]
Slideshow of two emails.

https://github.com/dnschneid/crouton/assets/154830140/d4803086-9ad7-480f-86e9-363a8f51ad9a
