### ISSUE TITLE
2 previous issues locked as off-topic and new issues have attachments

### ISSUE THREAD

**Issue by burnsboyamazing** [dnschneid/crouton#5045]
```
Please paste the output of the following command here: shell, sudo edit-chroot -all
```

#### Please describe your issue: Slideshow of two issues.

https://github.com/dnschneid/crouton/assets/154830140/8780ba80-40a2-4773-8bcb-f5f715975660

#### If known, describe the steps to reproduce the issue:
Accidental locked conversion as off-topic.

**Comment by DennisLfromGA** [comment]
@burnsboyamazing,

> Accidental locked conversion as off-topic.

It was **not** accidental, it is **NOT** an issue, it is a PEBCAK error, nothing more.

I gave you instructions in one of your previous posts, please read them:

- https://github.com/dnschneid/crouton/discussions/5043#discussioncomment-7958344

And please **stop** posting non-issues.

-**DennisLfromGA**
