### ISSUE TITLE
Previous issue locked as off-topic like sudo edit-chroot -all

### ISSUE THREAD

**Issue by burnsboyamazing** [dnschneid/crouton#5046]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue: Screenshot of one email.
![Screenshot 2023-12-27 12 17 43 PM](https://github.com/dnschneid/crouton/assets/154830140/bfda9150-622c-46b9-91c0-a2fa2efea41d)

#### If known, describe the steps to reproduce the issue:
No, but https://github.com/dnschneid/crouton/issues/5040 is better than off-topic.

**Comment by drinkcat** [comment]
@burnsboyamazing please stop opening new issues repeatedly. Dennis already provided some help on your original issue: https://github.com/dnschneid/crouton/discussions/5043#discussioncomment-7958344

**Comment by burnsboyamazing** [comment]
Screenshot of the email.
![Screenshot 2023-12-27 12 32 04 PM](https://github.com/dnschneid/crouton/assets/154830140/151071fc-2192-4683-8322-beaaaef79bd6)
