### ISSUE TITLE
shell command error (ChromeOS only)

### ISSUE THREAD

**Issue by burnsboyamazing** [dnschneid/crouton#5047]
```
Please paste the output of the following command here: shell
```

#### Please describe your issue: At https://github.com/dnschneid/crouton/issues/5039, still getting the "unknown command" error when I type shell.
[Screen recording 2023-12-29 5.10.40 PM.webm](https://github.com/dnschneid/crouton/assets/154830140/37197162-49c2-49ba-aa97-72695344fd57)

#### If known, describe the steps to reproduce the issue:
1. Press Ctrl+Alt+T.
2. Type "shell".
3. Press enter.

**Comment by dnschneid** [comment]
If the `shell` command doesn't work, it means your device isn't in developer mode (which is a different thing from dev channel).  There's plenty of tutorials on the internet for how to enter developer mode; [here's one of them](https://www.xda-developers.com/how-to-turn-on-chrome-os-developer-mode/).

If you follow the tutorial and the shell command still doesn't work, it probably means you accidentally exited developer mode by following the instructions at the boot screen.  Instead, you have to hit ctrl+D at the warning screen each time you boot your device.
