### ISSUE TITLE
"/sys/kernel/security/chromiumos/inode_security_policies/allow_fifo" is now read-only

### ISSUE THREAD

**Issue by powerCord154** [dnschneid/crouton#5056]
#### Please paste the output of the following command here: sudo edit-chroot -all
cant

#### Please describe your issue:
`/usr/local/bin/mount-chroot: 362: cannot create /sys/kernel/security/chromiumos/inode_security_policies/allow_fifo: Read-only file system` occurs after today's dev channel update (124.0.6340.0).
It's `/sys/kernel/security/` that's been made read-only

#### If known, describe the steps to reproduce the issue:
run crouton

**Comment by powerCord154** [comment]
actually, I found a fix:
`sudo mount -o remount,rw /sys/kernel/security/`

@dnschneid if this could be incorporated in crouton, that would help

**Comment by nethershaw** [comment]
"Maintenance mode" is code for "abandoned to a community that can't keep up with all the things Google does to make everyone else's lives harder, because asking someone to step up and wrangle the million forks was beyond us."

**Comment by dnschneid** [comment]
Actually, thanks for bumping this, since I somehow missed it in my inbox.

Give `BRANCH=rwsec` a try; I can't test it right now.  It's based on the silence branch since I assume you need that.

**Comment by Mar-Kali** [comment]
Many thanks to powerCord154,
In a VT (Virtual Terminal) I did the command:
$ sudo mount -o remount, rw /sys/kernel/security 
and after I was again able to do a "sudo enter-chroot".
;-)
