### ISSUE TITLE
Curl ssl certificate problem

### ISSUE THREAD

**Issue by xavimc** [dnschneid/crouton#5064]
Hello! I was happy using crouton until I decided to start clean, powerwash my deprecated samsung chromebox series 3 (2012)
I could not install crouton again for some certificate problem, details below.

Here some info: cat /etc/lsb-release
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={2EE05B2F-3769-43B9-B78C-792F4A027971}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={2EE05B2F-3769-43B9-B78C-792F4A027971}
CHROMEOS_RELEASE_BOARD=stumpy-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=62
CHROMEOS_RELEASE_BUILDER_PATH=stumpy-release/R65-10323.62.0
CHROMEOS_RELEASE_BUILD_NUMBER=10323
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=65
CHROMEOS_RELEASE_DESCRIPTION=10323.62.0 (Official Build) stable-channel stumpy 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10323.62.0
DEVICETYPE=CHROMEBOX
GOOGLE_RELEASE=10323.62.0

Followed steps for install:
sudo install -Dt /usr/local/bin -m 755 ~/Downloads/crouton
sudo crouton

Downloading latest crouton installer...
#=O#-   #     #                                                                                                                                     
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Failed to download crouton installer.
Check your internet connection or proxy settings (-P) and try again.

I tried adding certificates with pem file but it keeps saying all of them already exist.
Can I modify curl calls to use -k or insecure option?
Do you know how can I fix this...?
Thanks!

**Comment by dnschneid** [comment]
You can try downloading the latest release directly and running that instead: https://github.com/dnschneid/crouton/raw/releases/crouton

**Comment by xavimc** [comment]
Thank you for the quick response. 
I downloaded the last version from the short google link in the readme, I guess is the same but I'll try again with yours. And what about the opposite, maybe using an older crouton could help?

In the meantime I've tried using the chromebook extension tool to run a recovery from usb, disabled developer mode and enabled it again. I enabled debugging features at startup and set root password in case this could help, but still has the same certificate issue.

I've also seen that It's possible to directly install archlinux on some chrome devices... I may check that too https://wiki.archlinux.org/title/Chrome_OS_devices

**Comment by dnschneid** [comment]
The short link goes to an indirect downloader that curls and caches the above installer. This is so that people don't keep using old versions of crouton and running into stale bugs. 
Since the certs on your system are so old, curl isn't happy downloading the installer, so you can have Chrome download it instead. After that the usage is the same, and you can probably bootstrap your distro from a non-https server.

**Comment by xavimc** [comment]
Oh! Thank you very much, I could run the crouton from your link.
I'm back in the business! :)
