### ISSUE TITLE
Attempting Step 2 in Updated Installation Guide crashes my chromebook (Solved)

### ISSUE THREAD

**Issue by MMOEnthusiast** [dnschneid/crouton#5087]
```
Please paste the output of the following command here: sudo edit-chroot -all
```

#### Please describe your issue:
As stated above, I am able to make crouton executable (as the first step has me do), but the moment I attempt to install a distro as the second step suggests, my chromebook restarts. 
I own a HP Chromebook 14 inch 14a-ne0000.

#### If known, describe the steps to reproduce the issue:
Turn on developer mode and switch to VT-2.
After that, do step 1,
after that install a distro (sudo CROUTON_BRANCH=silence crouton -r focal -t xfce)

If there's any other info you need, I'll provide.
Thank you for your time.

**Comment by coderpro1234-2** [comment]
Same issue here, but with a Lenovo 100e Chromebook

**Comment by CroutonIsFun** [comment]
@MMOEnthusiast and @coderpro1234-2 

I'm not an expert, and this sounds really strange. When does your Chromebook reboot? Immediately, or after the install, or during the install?

**Comment by MMOEnthusiast** [comment]
@CroutonIsFun It happens immediately. The second I hit enter, my chromebook reboots. I tried it several times, just to make sure.

**Comment by CroutonIsFun** [comment]
I'm not getting these same results. I'm confused as to how running a script could cause a problem. What sorts of add-ons are you running in the browser?

**Comment by tista500** [comment]
Greetings,

This might be ChromiumOS 126.0.x specific.
I also experienced this issue after updated to 126 series (with some security enhanced?)

Anyway `crouton` and/or `enter-chroot` scripts would be blocked by OS-side, then it forces to reboot the machine without any core dumped. These behaviors look quite similar to the case that we've seen "Electron-based apps and wine apps on the crouton system are segfault-ed and rebooting machines". Long story short, there's no way to install crouton to ChromiumOS 126.0.xxxxx until some tricks are landed on the crouton scripts...

Cheers

**Comment by MMOEnthusiast** [comment]
Damn man.
Alright, that's fair enough.
Also, while I'm not sure if the add-ons were the issue, I did have several unneeded ones so I was able to reduce the memory. 
Thanks everyone :)
