### ISSUE TITLE
No sound after Chromium OS update.

### ISSUE THREAD

**Issue by bobmcbobbertson** [dnschneid/crouton#512]
So I'm completely inept when it comes to this sort of thing, and I have no idea what it is I should do, or ask, or what information to provide to solve my issue. All I know is that a few days ago, the sound worked just fine while running Ubuntu, and now it does not. Any help would be greatly appreciated! I'm running an Acer Chromebook, with the Unity interface for my Ubuntu.

**Comment by Alfriadox** [comment]
Is this still a current problem or can this be closed?

**Comment by eepgwde** [comment]
Yes, you can close it for me.
