### ISSUE TITLE
Unable to start xfce

### ISSUE THREAD

**Issue by Rafagars** [dnschneid/crouton#5120]
```
Please paste the output of the following command here: sudo edit-chroot -all
sudo edit-chroot -all
name: debian
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/debian...
crouton: version 1-20240722212955~master:d0780207
release: bookworm
architecture: amd64
xmethod: xorg
targets: xfce
host: version 14816.131.0 (Official Build) stable-channel terra 
kernel: Linux localhost 4.19.241-13212-ge9b0bab46475 #1 SMP PREEMPT Sun Jul 17 19:32:48 PDT 2022 x86_64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/debian..
```

I tried to install Crouton on my Asus C202s but I haven't been able to start xfce it gives me this error

sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/debian...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.21.1.7
X Protocol Version 11, Revision 0
Current Operating System: Linux localhost 4.19.241-13212-ge9b0bab46475 #1 SMP PREEMPT Sun Jul 17 19:32:48 PDT 2022 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 4077568 verity payload=PARTUUID=de011728-c0f6-4c4b-8f3e-e5196acfe711/PARTNROFF=1 hashtree=PARTUUID=de011728-c0f6-4c4b-8f3e-e5196acfe711/PARTNROFF=1 hashstart=4077568 alg=sha256 root_hexdigest=fd79aecb3022559be09cfa57c5e416d6fd9f1c273ec5cb59918dfc16da0334fb salt=1eb8f69ab9e6d7f944224ae464663a7902cabfc254cd802cf74afab4f05f7f9f" noinitrd vt.global_cursor_default=0 kern_guid=de011728-c0f6-4c4b-8f3e-e5196acfe711 add_efi_memmap boot=local noresume noswap i915.modeset=1 disablevmx=off tpm_tis.force=1 tpm_tis.interrupts=0  
xorg-server 2:21.1.7-3+deb12u8 (https://www.debian.org/support) 
Current version of pixman: 0.42.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Sat Nov 23 20:46:55 2024
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/debian...

**Comment by Rafagars** [comment]
Manage to make it work by using the Silence branch and installing bullseye instead of bookworm

**Comment by LanChrome** [comment]
I had the same issue. If you want bookworm, you have to install the default chroot (xenial), run it (it works every time, and you can immediately close it),  install bookworm, and run it. Be warned that you can only run bookworm once before it doesn't work again. You might be able to run xenial again, close it, and run bookworm again.
