### ISSUE TITLE
X Server Access Denied, Fails to enter Chroot

### ISSUE THREAD

**Issue by thewes** [dnschneid/crouton#524]
Upon upgrading the Pixel this morning on Dev channel and after entering sudo startunity I receive this:

Loading extension GLX
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error

Here's my version Info:

crouton: version 1-20131209181508~master:34ee7cf6
release: saucy
architecture: amd64
host: version 5062.1.0 (Official Build) dev-channel link

Chroot closes by itself and returns to command prompt.

**Comment by steveg19710** [comment]
You've been invited to join HelloFax by stevegause71@gmail.com. HelloFax lets you send and receive faxes from the browser. Join now and we'll both get 5 free fax pages.

Accept invitation: https://www.hellofax.com/?ref=9a57dc6f&amp%3Bs=F&utm_campaign=friend_invite&utm_source=default&utm_medium=email&utm_content=original


Thanks for going paperless!

The HelloFax Team

**Comment by bmoffitt** [comment]
Is anyone else having this problem again in their chroots? I am on an Acer C710-2856 (with 10 GB ram and an SSD). I am currently on stable; I updated ChromeOS on Monday:

Version 42.0.2311.153 (64-bit)
Platform 6812.88.0 (Official Build) stable-channel parrot_ivb
Firmware Google_Parrot.2685.54.0

and my chroot stopped working. Here's the output from chrootversion:

crouton: version 1-20150519153807~master:30cf02c9
release: trusty
architecture: amd64
xmethod: xorg
targets: x11,xfce-desktop
host: version 6812.88.0 (Official Build) stable-channel parrot_ivb 
kernel: Linux localhost 3.8.11 #1 SMP Fri May 8 13:50:13 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
freon: no

If I just run startxfce4, it fails (exactly as if Chromeos had updated requiring a crouton update - Fatal server errors: (EE)no screens found (EE)). If I then update crouton and run startxfce4, the machine reboots.

I haven't changed the x.org config or anything else... I'm not sure what to do.

**Comment by torsava** [comment]
If anyone is still interested: The issue still persists when using the debian-sid chroot base. Recommended solution: Switch to an ubuntu chroot.

**Comment by Yerffy** [comment]
Super disappointed, I've been trying to figure this thing out but I'm not too tech savvy, only reason I purchased the chromebook was for the fact that I could run Linux on it. Really hoping that this can get fixed.

**Comment by tedm** [comment]
Wow, isn't this a very old closed issue?

**Comment by Yerffy** [comment]
@tedm Was trying to find if there was someone with the same issues and ended up responding on the wrong forum and deleted it after accidentally sending it

**Comment by trusktr** [comment]
I'm getting this same error, no screens found for X11. I haven't used Crouton for a while (Chrome OS has since been updated), so something has changed. I was trying to run `sudo startgnome`, which leads to this error. `sudo enter-chroot` works though.

Is there a fix for this that doesn't involve wiping all my Crouton stuff? Maybe I just backup my home folder then re-install Crouton, reinstall apps, restore home folder? THe home folder has all the stuff I really care about. Other stuff outside of the home folder is installed only with apt-get or with package managers like `npm`.
