### ISSUE TITLE
jessie chroot does not have en_US.UTF-8

### ISSUE THREAD

**Issue by darcyparker** [dnschneid/crouton#534]
This may be similar to #85 ?

I installed a jessie debian chroot and struggled with term issues.  It turned out that `$LANG=C`.  `locale -a` showed that `C.UTF-8` was available but it wasn't the default... and `en_US.UTF-8` was not installed.  (Not having UTF-8 of course caused many problems with vim and especially things running inside tmux.

I worked around this by:
```
sudo apt-get debconf locales
dpkg-reconfigure locales
```
In the ncurses gui, I was able to install and set en_US.UTF-8 as my default.  This resolved my term issues.

**Comment by dnschneid** [comment]
Fixed in the latest crouton.

**Comment by thewtex** [comment]
Thanks!

**Comment by darcyparker-ptc** [comment]
Nice - looking forward to trying next time I build a new chroot.

**Comment by DennisLfromGA** [comment]
> sudo apt-get debconf locales
> dpkg-reconfigure locales

A little late to the party but I think it should be:
```
sudo apt-get *install* debconf locales
*sudo* dpkg-reconfigure locales
```

**Comment by sirosen** [comment]
I hate to raise an old issue from the dead, but has there been a regression?
I just had this issue with the latest crouton and a fresh jessie chroot.
The `locales` package was missing entirely.

Installing locales, running `dpkg-reconfigure locales`, and then restarting the debian chroot resolved it.


Some diagnostic info which may be of use:

```
chronos@localhost ~ $ sh Downloads/crouton -V
crouton: version 1-20151104200003~master:2a1fc9da
```

Running in a jessie chroot built with `xiwi`, `xfce`, and `keyboard` targets.

**Comment by darcyparker** [comment]
Yes, I think there was a regression. I am using Debian stretch and seeing the issue again... 

For me it hasn't been a big deal... Here's the script I use to automate most of my remaining setup after I build a new chroot *with the lines related to this issue's workaround marked):
https://gist.github.com/darcyparker/992a09589e51eb0f20d4#file-chrootpostinstall-sh-L398-L399

This issue should be looked at again though...

**Comment by leewc** [comment]
I ran the fix suggested by DennisLFromGA (install debconf locals then reconfigure), and restarted the chroot by exiting and entering the chroot, the issue still appears to be not fixed, as show below, I am unable to display Chinese characters. Will hunt around for a fix ASAP.

Here's some terminal output:
 ````
crosh> shell
chronos@localhost / $ ls
bin  debugd  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  postinst  proc  root  run  sbin  sys  tmp  usr  var
chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/theia...
(theia)wclee@localhost:~$ sudo apt-get install debconf locales
[sudo] password for wclee: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
debconf is already the newest version.
locales is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
(theia)wclee@localhost:~$ sudo dpkg-reconfigure locales
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
(theia)wclee@localhost:~$ cd ~/Downloads
(theia)wclee@localhost:~/Downloads$ ls
4061                            Screenshot 2016-01-06 at 5.57.15 PM.png
Eng???????????????[test]???????????????.txt

(theia)wclee@localhost:~/Downloads$ exit
logout
Unmounting /mnt/stateful_partition/crouton/chroots/theia...
Sending SIGTERM to processes under /mnt/stateful_partition/crouton/chroots/theia...
chronos@localhost / $ sudo enter-chroot
Entering /mnt/stateful_partition/crouton/chroots/theia...
(theia)wclee@localhost:~$ cd ~/Downloads/
(theia)wclee@localhost:~/Downloads$ ls
4061                                                                   Screenshot 2016-01-06 at 9.54.54 PM.png
???Eng???????????????[test]???????????????.txt
````

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.

**Comment by fizxmike** [comment]
Can confirm problem still exists in vanilla install using:
`sudo sh ~/Downloads/crouton -r jessie -t gnome-desktop,extension,audio`
Fix from DennisLFromGA worked:
```
sudo apt-get install debconf locales
sudo dpkg-reconfigure locales


```
Best,
Michael

**Comment by DennisLfromGA** [comment]
@fizxmike,

> Can confirm problem still exists in vanilla install using:

Are you getting error or warning messages and if so what are they?

I thought this had been addressed in the [core#L119](https://github.com/dnschneid/crouton/blob/master/targets/core#L119) target.

-**DennisL**

**Comment by leewc** [comment]
If you're interested I wrote a post about how to fix and install Unicode on
the vanilla install.

https://leewc.com/articles/unicode-crouton-how-to/

That's relevant to en_US.UTF8 as we're looking for UTF8 support.

The basic gist is

```
 sudo apt-get install language-selector-gnome
 gksu gnome-language-selector
 sudo locale-gen

```

The language selector will detect and fix the unicode issue. The remaining
steps are more for installing other languages.


leewc.com
PGP Public Key: 0xFAE812E11D152AAD
<http://pgp.mit.edu/pks/lookup?op=get&search=0xFAE812E11D152AAD>
