### ISSUE TITLE
Webserver commands

### ISSUE THREAD

**Issue by moocow1452** [dnschneid/crouton#558]
So, I remember we as a group were noodling over how to better integrate Crouton x-apps with the native Chrome Manager, either adding apps or bookmarklets to shunt Chrome OS over to your Linux target when you want to start a native app, then easily putting it back when you want to go home. I wonder, with the advent of a Crouton extension and a server within the Chroot that listens for copy/paste commands, could we have another server that the Chromebook proxies traffic through when it senses an active Chroot, that goes ding when it picks up a url or search query from crouton:// or a throwaway domain, and then starts an environment specifically to run that application full screen? It seemed like a good idea at three in the morning, so I'm bringing it to the board for a feasibility check before I start breaking things.

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
