### ISSUE TITLE
"mount: special device /var/run/shill does not exist"

### ISSUE THREAD

**Issue by ltrgoddard** [dnschneid/crouton#56]
Hi,

I'm having some problems getting crouton up and running on my Samsung Series 5 550. The install process stops abruptly after

```
Installing unmount-chroot into the host...
mount: special device /var/run/shill does not exist
Unmounting /usr/local/chroots/precise...
```

When I try to startxfce4 after this, I get the prompt described [here](https://github.com/dnschneid/crouton/issues/9) - "A chroot preparation script still exists inside the chroot", etc. I've tried deleting the chroot and re-running the script, but have the same problem - the process doesn't get to the prompt stage at all. I've pasted the full log below, cutting out the long list of retrieved/validated/extracted packages - any help would be much appreciated!

```
chronos@localhost /var/run $ sudo sh -e ~/Downloads/crouton -t xfce
Installing precise-amd64 chroot to /usr/local/chroots/precise
Remounting /tmp with dev+exec...
Downloading debootstrap...
Downloading bootstrap files...
I: Retrieving InRelease
I: Failed to retrieve InRelease
I: Retrieving Release
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/ubuntu-archive-keyring.gpg
I: Retrieving Packages
I: Validating Packages
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://archive.ubuntu.com/ubuntu...

[...]

Moving bootstrap files into the chroot...
Preparing chroot environment...
Installing brightness into the chroot...
Installing host-dbus into the chroot...
Installing croutonpowerd into the chroot...
Installing xinit into the chroot...
Installing startxfce4 into the host...
Installing enter-chroot into the host...
Installing delete-chroot into the host...
Installing mount-chroot into the host...
Installing unmount-chroot into the host...
mount: special device /var/run/shill does not exist
Unmounting /usr/local/chroots/precise...
```

**Comment by sbastable** [comment]
I realise that this is a very old thread, but I am having the same issue on my Pixelbook. I am definitely running the latest version of the OS (Version 63.0.3239.140 (Official Build) (64-bit))

I entered dev mode and then immediately downloaded Crouton from https://goo.gl/fd3zc  . I then ran the following from a terminal window

shell
sudo sh ~/Downloads/crouton -t xfce

Install whirred away for a minute or so, but I then received the message

mount: special device /var/run/shill does not exist
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

I have tried other targets with the same result. Any pointers or advice would be much appreciated. This conversation seems to be the only reference to the same issue that I can find.

**Comment by DennisLfromGA** [comment]
@sbastable,

That is strange, maybe something else is interfering with crouton. 
I'd suggest you reboot and try again, if you run into the same issue we'll try to gather more info. to troubleshoot with.

*Hope this helps,*
-**DennisLfromGA**
