### ISSUE TITLE
How to start the DE automatically?

### ISSUE THREAD

**Issue by ghost** [dnschneid/crouton#582]
First, I tried disable rootfs_verification with this command:

```
sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification
```

But I get this output:

```
ERROR: YOU ARE TRYING TO MODIFY THE LIVE SYSTEM IMAGE /dev/sda.

The system may become unusable after that change, especially when you have some auto updates in progress. To make it safer, we suggest you to only change the partition you have booted with. To do that, re-execute this command as:

sudo ./make_dev_ssh.sh --remove_rootfs_verification --partitions 2

If you are sure to modify other partition, please invoke the command again and explicitly assign only one target partition for each time (--partitions N)

ERROR: IMAGE /dev/sda IS NOT MODIFIED.
```

So I took the computer's advice and I ran:

```
sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 2
```

It seemed to work. I then did `cd etc` and then I did `vim rc.local`. I entered `startunity -b` into vim and then I tried to exit with `:wq` but it says that it doesn't have permissions to save. I tried `sudo` but same error.

When I try to run this command again:

```
sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification
```

The computer now suggests to run:

```
sudo ./make_dev_ssh.sh --remove_rootfs_verification --partitions 4
```

**Comment by UT99310** [comment]
Hi. I'd like verify the status of these instructions and the script. In the virtualbox integration writeup for Crouton, it involves copying the new vb udev rules to a directory on the CrOS root fs (at least, that's my interpretation). Of course that fs is ro. Before I start mucking with the partition flags and such to gain rw access, I'd like to minimize the chances of some of the problems noted above (this is on an Asus Chromebox, by the way). Any suggestions appreciated. Thanks!

**Comment by DennisLfromGA** [comment]
@UT99310 - Unfortunately, I don't have a Chromebox to test on but I think the problems stemmed from the `dev_boot_signed_only` flag being set (1). I mention this in the comments section of the `rw-rootfs` script here - https://gist.github.com/DennisLfromGA/6690677#comment-1418056.

I haven't heard from any Chromebox users since I modified the script to unset the flag so your on your own I guess - sorry.

-DennisL

**Comment by UT99310** [comment]
Understood. Guess I'll back up ye ol' chroot and give the script a try.
Thanks!

L

**Comment by UT99310** [comment]
Looks like it worked OK on my Asus Chromebox. The script did throw an error
about a misplaced or unrecognized -gt just before the reboot (around line
119 I think), but I didn't see any obvious negative effects so far. Thanks
again.

**Comment by DennisLfromGA** [comment]
That's *great* news.
I haven't tracked down that '-gt' error yet, I've been lazy...

**Comment by divx118** [comment]
@UT99310 For the udev rules you don't have to make the system rw. /var/run is writable, however you will need to redo it on a reboot.

**Comment by UT99310** [comment]
Having to manually do that on reboots isn't a viable option (to me, anyway). I used /etc/udev/rules.d which is at least stable through boots.

**Comment by divx118** [comment]
@UT99310 Well, I just thought I should mention. Also when other people come across this.

**Comment by UT99310** [comment]
Definitely. Thanks.

**Comment by DennisLfromGA** [comment]
Yes, that's good info. I think since probably *most* crouton users don't or won't remove rootfs.
It might be a good idea to add it to the https://github.com/dnschneid/crouton/wiki/VirtualBox-udev-integration pwiki age too. Maybe it's something that could users could add to their `.bashrc`.

**Comment by UT99310** [comment]
If the mount/script sequencing is such that .bashrc can routinely copy the
rules.d entries into /var/run/udev/rules.d at the correct time to be
effective, the procedure probably should be documented in place of the
existing specification to copy into a root dir.

**Comment by UT99310** [comment]
I may be missing something, but it appears that this isn't going to work for VirtualBox loading. You need to change the kernel flags to enable module loading, and I don't see any way to do that without taking the system rw first. Is there another way? Thanks.

**Comment by divx118** [comment]
@UT99310 You don't need to make the system rw to change kernel-flags. You can follow the [wiki instructions](https://github.com/dnschneid/crouton/wiki/Repack-kernel-to-Enable-VT_x-for-Virtualbox) or my script [change-kernel-flags](https://github.com/divx118/crouton-packages/blob/master/change-kernel-flags) See the first part of the [README.md](https://github.com/divx118/crouton-packages/blob/master/README.md) for the usage. The script will also let you revert the changes of the kernel flags by dd back an old backup kernel. Also it will handle automatically the crossystem variable settings.

**Comment by UT99310** [comment]
I should have been more explicit. The point I was trying to make is that
you can't get at the kernel flags without those various partition
operations (in my case, via your script) that must be made each time CrOS
updates and that some users may be uncomfortable doing. Thanks.

**Comment by divx118** [comment]
FYI if you make the system rw, you don't need to change kernel-flags. The sysfs path to disable module_locking should be visible again on a rw rootfs.

**Comment by UT99310** [comment]
Quick question: In the course of this testing, looks like I ended up with a
corrupt .bashrc (probably an extraneous chdir or exit on the end). Now when
I try to enter the shell I just revert immediately back to the crosh
prompt. Is there a suggested way to fix this? Thanks!

**Comment by DennisLfromGA** [comment]
@UT99310 - I think you can login to your Google account and then, without opening a shell in that session, open the Developer Console via \<Ctrl+Alt+Forward\>. Then log in as root and cd to the chronos home folder `# cd ~chronos`, then fix or remove the `.bashrc` file.

**Comment by UT99310** [comment]
Bingo! Thanks!

**Comment by DennisLfromGA** [comment]
Been there, done that... ;)

**Comment by UT99310** [comment]
Looks like there may be more damage of a sort. Even though the partitions
look right, I can no longer remount / rw -- keep getting write-protected
error. Rerunning the script claims that the correct partition is already
unlocked. Odd.

**Comment by DennisLfromGA** [comment]
Have you rebooted since running the script?

**Comment by UT99310** [comment]
Yeah. Still getting:

mount: cannot remount /dev/dm-0 read-write, is write-protected

**Comment by UT99310** [comment]
Got it rw now. Took a few more boots. Something must have been out of
sequence. Thanks again!

**Comment by DennisLfromGA** [comment]
@UT99310,

I had a similar issue, I think, a while back with my Acer C710, which has since bit the dust.
The problem was in the file `/usr/share/vboot/bin/make_dev_ssd.sh` where it was only looking at `dm-0` instead of `dm-[0-9]`. Look at line \# 65 or there abouts. I filed a bug report https://code.google.com/p/chromium/issues/detail?id=428041 and it was resolved.

Hopefully this hasn't reared it's ugly head again...

**Comment by DennisLfromGA** [comment]
Oh, cool, I should have *refreshed* the page, I didn't see your last reply.

**Comment by UT99310** [comment]
There clearly were changes that had unexpected (to me) effects in the last
CrOS update, there's now a conflict in the vb driver name paths that wasn't
there before. I'm working on it.

**Comment by UT99310** [comment]
For the record, this didn't end well. Something in the new CrOS update
really confused the modules, and ultimately I could not reboot. I do have a
crouton backup from a few days ago that will get me back to some known
state. Just got back into fresh dev mode -- takes quite a while with 128G
SSD.

**Comment by UT99310** [comment]
I got VB running on the previous CrOS version under Crouton w/o much difficulty, but when CrOS updated yesterday I ran into trouble. In fact, I ended up unbootable and had to restore from my most recent Crouton backup. Now I'm back to the point where VB starts but I'm getting the VT-x is Disabled error (which I did not see on my previous install of VB). I'd prefer not to blow away the system again if possible. Any suggestions? Thanks!

**Comment by UT99310** [comment]
Got VT-x working again. Even though the kernel flags were already changed appropriately, the partition was back in a locked state -- this prevented VT-x from functioning. Unlocked partition again using the script for making root writeable -- and VT-x popped back in.
