### ISSUE TITLE
Shared directory between chroots that is not volatile like Downloads?

### ISSUE THREAD

**Issue by pcm2a** [dnschneid/crouton#620]
It would be great to have a shared mount point between chroots that is not volatile like Downloads. ChromeOS will wipe out Downloads under conditions that are outside of the users control. I would like to store some development stuff there, like eclipse, that is shared between the chroots. 

Two huge benefits are:
1. The ability to use multiple desktop environments while not having to resetup productivity applications.
2. The ability to backup the chroot without backing up large amounts of space taken up by eclipse, SVN, whatever is in the shared area.

Is this already possible?

**Comment by dnschneid** [comment]
OK, this is now in the latest crouton.  Update your chroot and check out the /etc/crouton/shares file inside the chroot.  Let me know if anything seems amiss.
