### ISSUE TITLE
Kubuntu (running via crouton) needs to restart to complete updates..but how?

### ISSUE THREAD

**Issue by phoenix00a** [dnschneid/crouton#63]
So I'm using the awesome Crouton to run kubuntu-desktop alongside ChromeOS on my HP Pavilion Chromebook. I've updated some packages and now kubuntu-desktop is telling me a 'Restart is needed to complete the updates." (the orange icon with the circular arrow)

I've already done the obvious and restarted my machine but the restart message still appears once I'm back into my kubuntu-desktop. I've already tried logging-out and logging-in (essentially dropping into ChromeOS and then restarting ubuntu-desktop using sudo). Still the same result. 

How can I restart ONLY the ubuntu-desktop if there isn't an actual login screen (because using 'sudo startkde' from ChromeOS drops me directly into the kubuntu initializing screen)?

**Comment by VelocityDesign** [comment]
Oof, installing Eoan and this issue popped up again. Tried the method described above, and it is still not working. Please help :D

**Comment by DennisLfromGA** [comment]
@VelocityDesign,

Do you have the latest & greatest version of [crouton](https://goo.gl/fd3zc) downloaded and re-installed?

*Hope this helps,*
-**DennisLfromGA**

**Comment by VelocityDesign** [comment]
Yes, I have recently started using it.
