### ISSUE TITLE
Minecraft LAN Broken

### ISSUE THREAD

**Issue by Klikini** [dnschneid/crouton#667]
I can access the web (and Minecraft servers) just fine.

When I click Open to LAN in Minecraft, it shows up on other LAN computers (this is progress, after a bit of config file tweaking), but they can't connect with an unknown error.

I can't connect to other LAN worlds either.

Anyone else having this issue? Any advice? This is really annoying!

I have to use Ubuntu 12.04 with Unity instead of any newer version with XFCE because Minecraft won't run in anything but Unity on Crouton.

**Comment by KrawFish** [comment]
I believe I am having a similar problem. Using an Acer Chromebook 15, I can get Minecraft to run and Ubuntu 12.04 Xfce can access websites, however, when I try to join a Multiplayer game on the LAN, Minecraft cannot find the game that has been opened to LAN. Nor can other people on my LAN see the games I open for multiplayer.

I tried the IPTABLES command above, but I get a message that iptables is not installed.

**Comment by ScythianBeastie** [comment]
Potentially helpful note: I had to run `sudo iptables -P INPUT ACCEPT` in *ChromeOS*, not in the Linux session via Crouton.
