### ISSUE TITLE
Repacking kernel to enable VT-x extensions for virtualbox/virtualization

### ISSUE THREAD

**Issue by juancferrer** [dnschneid/crouton#675]
Following the steps here: https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)
We're able to have virtualbox installed on crouton.  Awesome!  One small issue is that by default the VT-x extensions are disabled by Chrome OS, meaning we can only emulate some OSes and only 32bit systems at that.

According to this: http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/running-virtual-machines-on-your-chromebook
It seems that by passing the 'vmxdisable=off' boot flag to the kernel will enable the VT-x extensions.

So how do we do that for the chromebook pixel??

Basically here: http://www.chromium.org/chromium-os/chromiumos-design-docs/disk-format#TOC-Changing-the-kernel-command-line
and here: https://codereview.chromium.org/3004001
Tells you how to change the kernel command line and repack the existing kernel.

Digesting the information above, we can do:
1. Copy the existing kernel into a file
   dd if=/dev/sda2 of=kernel2
   dd if=/dev/sda4 of=kernel4
2. Get the kernel configuration
   vbutil_kernel --verify kernel2 --verbose | tail -1 > vmxoff-config2.txt
   vbutil_kernel --verify kernel4 --verbose | tail -1 > vmxoff-config4.txt
3. Edit the config files and add 'vmxdisable=off' to the config line
4. Repack the kernels
   vbutil_kernel --repack repacked2 \ 
   --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk \ 
   --oldblob kernel2 \
   --config vmxoff-config2.txt 
   vbutil_kernel --repack repacked4 \ 
   --signprivate /usr/share/vboot/devkeys/kernel_data_key.vbprivk \ 
   --oldblob kernel4 \
   --config vmxoff-config4.txt
5. Verify the new kernels:
   vbutil_kernel --verify repacked2 --verbose
   vbutil_kernel --verify repacked4 --verbose
6. If verifying works, then it should just be a matter of:
   dd if=repacked2 of=/dev/sda2
   dd if=repacked4 of=/dev/sda4
   reboot, and enjoy VT-x extensions

I stopped at step 5 because the kernels never verified.  It says "Error verifying preamble".
Does anyone have any idea what I could be doing wrong?  It seems like I'm just one small step away from having VT-x enabled.  Also, why are there 2 partitions with a kernel on them?  I'm guessing one is a recovery kernel, if so, which one?  I'd love to leave the recovery kernel alone in case some terrible happens.

@divx118  Have you enabled VT-x extensions so that virtualbox works with 64bit VMs??

**Comment by duongkai** [comment]
I'm running crouton on chromebook pixel. Installing virtualbox works properly. I tried to enable VT-X as guide in wiki. But each time I boot my VMs, virtualbox said that VT-X is disabled in BIOS. So what happen to me?

**Comment by DennisLfromGA** [comment]
@rrolsbe - I never attempted the ```/usr/sbin/iotools ...``` command on my Acer C710, I just modified the kernel commandline to enable vmx support and that seemed to work just fine.

**Comment by rrolsbe** [comment]
@DennisLfromGA

I forgot to issue the following command:
crossystem dev_boot_signed_only=0  to disable verified boot.

I guess verified boot disables VT-x/vmx support during the boot process?  I assumed booting into developer mode would have disabled verified boot (guess I was wrong!).

Forum members please correct any incorrect statement in this post.

Thanks for the reply Dennis
Regards, Ron

**Comment by xx3nvyxx** [comment]
ChromeOS loads into a signed (by google) kernel by default. If verified boot is on, it will skip any unsigned kernel and load a signed one. If it can't find a signed kernel it will drop  you into recovery mode. By modifying the kernel to support VT-x, you invalidate the signature on the installed kernel and ChromeOS won't boot to it.

**Comment by DennisLfromGA** [comment]
@xx3nvyxx , It's possible I didn't fully understand your explanation above but I'm not so sure about the last statement -
> By modifying the kernel to support VT-x, you invalidate the signature on the installed kernel and ChromeOS won't boot to it.

Granted, I have turned off signed_only kernels:
```
chronos@localhost ~ $ sudo crossystem|grep dev_boot
dev_boot_usb           = 1                              # Enable developer mode boot from USB/SD (writable)
dev_boot_legacy        = 1                              # Enable developer mode boot Legacy OSes (writable)
dev_boot_signed_only   = 0                              # Enable developer mode boot only from official kernels (writable)
```
But, I have modified the kernel cmdline to 'enable vmx' and 'disable module_locking'
via this procedure '[Repack kernel to Enable VT_x for Virtualbox](https://github.com/dnschneid/crouton/wiki/Repack-kernel-to-Enable-VT_x-for-Virtualbox)':

`
chronos@localhost ~ $ cat /proc/cmdline 
cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=PARTUUID=cd9f7d97-84e4-2746-8c03-4ae431f7cdcb/PARTNROFF=1 rootwait rw dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=0 dm="1 vroot none ro 1,0 2506752 verity payload=ROOT_DEV hashtree=HASH_DEV hashstart=2506752 alg=sha1 root_hexdigest=8767c850c5de3c0da601c470dc5d489dcab5971d salt=a2152b7d609ae2d79defa512bb2288aee40f39ac2ea1c6207ff9aceb45cbc750" noinitrd vt.global_cursor_default=0 kern_guid=cd9f7d97-84e4-2746-8c03-4ae431f7cdcb add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  disablevmx=off lsm.module_locking=0
`

and am still booting the Google kernels - right now it's using KERNEL/ROOT-B:
```
Today is   : Wed Jan  7 14:44:06 EST 2015
Installed  : Thu Dec 25 11:58:39 EST 2014
Node name  : localhost
Machine    : x86_64
Rel. name  : Chrome OS
OS Track   : beta-channel
OS Release : Linux 3.8.11
CROS Root  : ROOT-B (/dev/sda5)
OS Board   : falco-signed-mp-v2keys
OS Coder   : Googler
OS Vers.   : 6457.36.0
Browser Ver: Google Chrome 40.0.2214.43
```

**Comment by xx3nvyxx** [comment]
They're still the same kernel, you just repacked it. Google signs the whole package, including the settings like VT-x disabled. By repacking it, you change the signature and it is no longer signed by google. Unless you had google's signing key you could not boot to that kernel with dev_boot_signed_only set to 1.

**Comment by DennisLfromGA** [comment]
Thanx @xx3nvyxx, I thought that might be the case. The 
`vbutil_kernel --repack repacked2 --signprivate ` 
portion would revoke Google's signed kernel and leave me out on a limb if I ever - or the system ever resets the `dev_boot_signed_only` to 1 - ouch!

**Comment by rrolsbe** [comment]
I modified the kernel using the enable-vmx.sh script and chromeos still
booted several times just fine with dev_boot_signed_only=1??  With it set
to 1, Virtualbox reported that VT-x was not enabled in the bios (when
trying to launch a 64Bit VM).  After setting it to 0 (no other changes),
the 64Bit VM runs fine.  I quess I am confused about how this all works?

Regards, Ron

**Comment by DennisLfromGA** [comment]
@rrolsbe - That's interesting. I'd be afraid to try it but I guess as long as the other pair is still signed it could boot it if the modded pair failed - I may try it myself.

**Comment by dsummersl** [comment]
I'd love to do this on my asus c200m, but when I try this script it complains that there is no `/dev/sda2` file. There aren't any `/dev/sda#`s!

I do notice that `futility verify` mentions `mmcblk0p2` as well as `sda2` as exmpale kernel partitions - I do have that. Is that what I should use instead?

**Comment by DennisLfromGA** [comment]
@dsummersl,

You're right - sorry about that ;)

I've since modified the script to accommodate root devices ending in a number like 'mmcblk0', etc. - thanx to @drinkcat ;)

You might want to grab the latest version of '[enable-vmx.sh](https://gist.github.com/DennisLfromGA/cd3455530cec2a5a1ef4)' and try it again.
*PLEASE* be forewarned though, I don't have any such device and I haven't tried it.

**Comment by dsummersl** [comment]
Awesome, thanks so much - worked!

**Comment by pfpmeijers** [comment]
I had it working once, but after a clean reinstall of chrome os, crouton, etc. it fails again. 

My kernel is adjusted. Running the enable-vmx.sh script says its ok already. disablevmx=off.

But when I start my virtual box I get the message that VT-x is not supported by the BIOS.

Do I need to redo something in the installation of Vbox itself?

Thanks in advance, Patrick

**Comment by rrolsbe** [comment]
Anyone try Virtualbox within Crouton on the ACER C710 with the 1007u processor?  After launching a 32/64 Bit VM the guest VM and Virtualbox proper become unresponsive.  This usually happen before the guest reaches the desktop but not always.  I also own a C710 with the 847 processor and (configured the same) Virtualbox under Crouton works great.  AFAIK, the only difference is the processor 847 versus 1007u and the kernel version 3.4.0 versus 3.8.11.  I would prefer to use the C710 with the 1007u processor because it has better CPU/GPU performance.

Thanks for any advice in advance!!
Regards, Ron

**Comment by UT99310** [comment]
I got VB running on the previous CrOS version under Crouton w/o much difficulty, but when CrOS updated yesterday I ran into trouble. In fact, I ended up unbootable and had to restore from my most recent Crouton backup. Now I'm back to the point where VB starts but I'm getting the VT-x is Disabled error (which I did not see on my previous install of VB). Reading through this thread, I'm unsure as to the best way to proceed. I'd prefer *not* to blow away the system again if possible. Any suggestions? Thanks!

**Comment by UT99310** [comment]
Got VT-x working again. Even though the kernel flags were already changed appropriately, the partition was back in a locked state -- this prevented VT-x from functioning. Unlocked partition again using the script for making root writeable -- and VT-x popped back in.

**Comment by Timvrakas** [comment]
@UT99310 I'm having the same problem, My /proc/cmdline has "disablevmx=off" but rdmsr -0 0x3a still returns "0000000000000001"
How exactly did you solve this, and why is it happening? I tried the rw-rootfs.sh script, but that did not help.

**Comment by pfpmeijers** [comment]
I did not solve it. Moved to a completely different approach for my
application, without virtualisation.
Grt, Patrick

**Comment by Timvrakas** [comment]
Well somehow I just got it to work by rebooting a few times and retrying
enable-vmx.sh and rw-rootfs.sh a few times.
And now viola it is enabled... although I would like to have more info on
how....

Thanks.

**Comment by mfbenson** [comment]
For some reason, I found shutting down and then starting up worked more
consistently after running enable-vmx.sh than just a reboot. I know, it
doesn't make sense...

**Comment by UT99310** [comment]
CrOS just updated, and suddenly I'm getting the VT-x error again also, leaving my 64-bit guest back in the mud. The previous CrOS updates up to this one seemed fine after I ran the scripts, but not this time.

**Comment by UT99310** [comment]
@mfbenson You're right. Shutting down and restarting fixed it where reboots did no good at all. Thanks.
