### ISSUE TITLE
Trusty not starting 

### ISSUE THREAD

**Issue by mgawin** [dnschneid/crouton#679]
First of all, I understand that Trusty is not officially supported. Still, maybe someone has any tips. The hidpi support looks very promising and I decided to give it a try.
After fresh install of Trusty, I get black screen at start, it seems that x is not starting at all. Console output below. Any help highly appreciated.

Entering /usr/local/chroots/trusty...

X.Org X Server 1.15.0
Release Date: 2013-12-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-58-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Fri Feb 28 03:44:29 PST 2014 x86_64
Kernel command line: cros_secure  console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2097152 verity payload=PARTUUID=02c62a69-6150-1e44-9cba-bfea71535727/PARTNROFF=1 hashtree=PARTUUID=02c62a69-6150-1e44-9cba-bfea71535727/PARTNROFF=1 hashstart=2097152 alg=sha1 root_hexdigest=a1a073de91c5cc712b16053e8f5185587291173f salt=3f2aa701e61bcf8073e253ea4ea1d113537d9c35b2810ecc144f43cd7cb435c5" noinitrd vt.global_cursor_default=0 kern_guid=02c62a69-6150-1e44-9cba-bfea71535727 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic gpt 
Build Date: 13 February 2014  03:27:21PM
xorg-server 2:1.15.0-1ubuntu6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Tue Mar  4 22:41:35 2014
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed: Permission denied
(II) AIGLX: Suspending AIGLX clients for VT switch

**Comment by qrkourier** [comment]
I have this issue with a Pixel 2 (2015) and the following instance:
  crouton: version 1-20150730171703~master:f8fdfb0c
  release: trusty
  architecture: amd64
  xmethod: xorg
  targets: touch,unity-desktop,audio,chromium,cli-extra,extension,keyboard,x11,xorg
  host: version 7077.95.0 (Official Build) stable-channel samus 
  kernel: Linux localhost 3.14.0 #1 SMP Tue Jul 14 21:42:56 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
  freon: yes
