### ISSUE TITLE
external screen

### ISSUE THREAD

**Issue by dimonf** [dnschneid/crouton#68]
First, thanks a lot for you work: I didn't even dream a week ago about such a perfect solution which turns chromebook into swiss knife linux box. Hat off.
Probably I put it to the limit, but work with external screen is not very practical. First, xfce works with, as far as I can see, virtual screen, which extends both physical screens. This is not very useful, since part of virtual screen is not accessible for the reason that two physical screens are of different dimensions. Second, switching between chromeos desktop and xfce with external screen connected turns the whole system unstable. I understand, that most probably my expectation is too high, so I post this just in case ... 
In this respect I'd like to ask, is it possible to avoid use of xfce desktop at all and fire up single window for specific application, say libreoffice, within chrome desktop environment?

**Comment by forresthopkinsa** [comment]
The secondary display (HDMI) works fine with Chrome, but if I try to enable it within Ubuntu, then ChromeOS goes haywire, and the secondary display simply doesn't work in Ubuntu. HP Chromebook 14 (2013)

Version 41.0.2272.89 (64-bit)
Platform 6680.64.0 (Official Build) stable-channel falco
Firmware Google_Falco.4389.92.0

**Comment by swt83** [comment]
I have a Pixel 2 and am wanting to buy a Dell 4k external monitor.  I have Ubuntu Unity.  Will this external display work?  It can use HDML or DisplayPort.

**Comment by forresthopkinsa** [comment]
If it helps, the secondary display has been working perfectly for me since the last update.

**Comment by Sodman** [comment]
@swt83 I've got a Pixel 2 working via HDMI with an Asus 1080p external monitor with Ubuntu Gnome - although I plug in the monitor while in chromeOS first. I can't speak for a 4k display specifically, but the marketing material for the chromebox says that the intel core i3 model supports 4k resolution output, so I'd assume your intel i5 (or i7) Pixel 2 should also be able to handle it.

**Comment by peepo** [comment]
I have 2x hdmi monitors that display in mirror using chromeOS,
however with vanilla install of crouton kde neither function at all in Ubuntu
