### ISSUE TITLE
Printing does not work on Ubuntu saucy

### ISSUE THREAD

**Issue by frederic-parrenin** [dnschneid/crouton#681]
I installed saucy with the gnome and keyboard targets.
Then I strictly followed the instructions here for printing support:
https://github.com/dnschneid/crouton/wiki/Printing
Yet, printing does not work.
The printing window in gnome does not say priting is not activated, but the buttons to add a new printer are desactivated.

**Comment by frederic-parrenin** [comment]
I confirm the two issues mentionned (no automatic detection and network printer and gnome-control-center print dialog disabled) still exist in utopic.

**Comment by frederic-parrenin** [comment]
For the gnome-control-center disabled problem, it might be an issue with PolicyKit but I don't have enough knowledge on it to propose a fix.

**Comment by DennisLfromGA** [comment]
The initial problem has been solved according to https://github.com/dnschneid/crouton/issues/681#issuecomment-37694133

The enhancement issue of creating a printer target is still open.

Please re-open if this issue is still a concern.
