### ISSUE TITLE
CTRL+ALT+FORWARD brings the developer console on C720

### ISSUE THREAD

**Issue by tbergeron** [dnschneid/crouton#687]
Hi,

I installed Crouton and everything, it works amazingly good until I do `CTRL+ALT+BACK` which brings back my Chrome OS desktop but then I do `CTRL+ALT+FORWARD` and it brings the Developer Console (black screen with white invite message) instead of bringing XFCE4 back. 

I can see in the `crosh` tab that XFCE4 is still opened. If I do `CTRL+C` to force quit it and run `sudo startxfce4` over again it starts fine.

I read somewhere to try `CTRL+ALT+REFRESH` but all it does is /sometimes/ freeze my Acer C720 for a while.

Any ideas of what I could be doing wrong here?

---

BONUS QUESTION:
Anything special about networking when using Crouton? I wanted to use Steam In-Home Streaming but for some reason when in crouton I cannot see my host computer anymore in Steam. Any idea?

Thanks!

**Comment by Shermanlion6** [comment]
Help i use unity for ununbu andi used ctrl alt and forward now im stuck idk the localname or password i tried to one i use but dont work help im on samsung chromebook

**Comment by divx118** [comment]
@Shermanlion6 Use ctr-alt-shift forward/back to switch between chroots. Note the shift. BTW ctr-alt-back should bring you back to chromeos out of the dev shell you landed in with chtr-alt-forward.

**Comment by Shermanlion6** [comment]
i know how to swtich back and forward it just how to mke it go way the login thing I just tried shift with it and its nt working how to make the thing go away it say at top  Developer Console how to restart it so i can login in with sudo startunity

**Comment by DennisLfromGA** [comment]
@Shermanlion6,

While at the Developer Console, press 'Ctrl+Alt+F1/LeftArrow' to get back to Chrome OS.

**Comment by Shermanlion6** [comment]
did it sends me back to the orginal screen my chromebook

**Comment by divx118** [comment]
@Shermanlion6 Yes, and when you are back in chromeos use "ctr-alt-shift forward/back" to swith between chromeos and chroots. Do not use "ctr-alt forward/back"

**Comment by Shermanlion6** [comment]
did it sends me back to the orginal screen my chromebook

**Comment by Shermanlion6** [comment]
did it sends me back to the orginal screen my chromebook

**Comment by Shermanlion6** [comment]
did it sends me back to the orginal screen my chromebook

**Comment by Shermanlion6** [comment]
did it sends me back to the orginal screen my chromebook

**Comment by Shermanlion6** [comment]
did it sends me back to the orginal screen my chromebook

**Comment by Shermanlion6** [comment]
is chrome os ur regular computer screen or something else cause im back to
my regular one i used the one with shift on regular screen but it not
working

**Comment by DennisLfromGA** [comment]
> did it sends me back to the orginal screen my chromebook

Once back in Chrome OS, (the original screen), open the original shell session or a new one via 'Ctrl+Alt+t', then enter `shell`, then `sudo startunity`.

**Comment by Jimzyboi** [comment]
I'm having the same issue as the original post, however the ctrl+alt+refresh when in the developer console does not work for me. I simply get a black screen and the mouse becomes unmoveable. Any help would be appreciated, Thanks.

**Comment by veraKorvo** [comment]
I'm using Hisense C11 ($149 walmart), and having the same issue. I installed debian jessie with target cli-extra. ctrl+alt+forward then ctrl+alt+refresh does the trick for me.

**Comment by williamjb18** [comment]
PLEASE HELP!!!!!! So i downloaded crouton xfce onto my acer c720 last night and it worked perfect. i shut my device off and went to bed. When i woke uo my computer was as it was before i did everything. So i did the key pad entry CTRL+ALT+FRWD and it sent me to a black screen. I remember it was CTRL+ALT+REFRESH instead. So that is what i did. Now it is asking me for my local host login. i put in what i thought it was pressed enter and it is now asking for my password. i typed in a possible password but it keeps saying login incorrect. i tried all possible passwords but it is not working. WHAT NOW?????? 
https://github.com/dnschneid please help

**Comment by DennisLfromGA** [comment]
@williamjb18 - Use CTRL+ALT**+SHIFT**+FRWD

**Comment by PayLeaves** [comment]
Leaving this comment for anyone searching for this now. The cause of this is that the chromebook in question, the C710, is Intel-based while most chromebooks are ARM-based. ARM chromebooks use the CTRL + ALT + SHIFT + F1/F2 (foreward/backward). Intel chromebooks use the CTRL+ALT+F1/F2 and require the CTRL+ALT+F3 (refresh) to show the desktop after. Hope this helps!

**Comment by dnschneid** [comment]
Actually, you should be using the shift version on both arm and intel.

**Comment by DamonD12** [comment]
An old thread, I know, but I am having the same problem William had, the ctrl+alt+fwd sends me to a screen titled Developer Console and requests a localhost login and password. The combination of ctrl+alt+shift+fwd does nothing at all.

**Comment by DennisLfromGA** [comment]
@DamonD12,

What *xmethod* are you using: 'xorg' or 'xiwi'?

-**DennisLfromGA**

**Comment by CertainCresula** [comment]
I have been having the same problem with this too, I found that you have to Start xfce4 first then use CTRL+ALT+SHIFT+BACKWRDS to go back and forth from Chome to xfce4

**Comment by DamonD12** [comment]
Fixed the original problem, now that I use the command 'sudo startxfce4' to
manually boot the Crouton Env. I get this message

ln: failed to access
'/var/run/crouton/mnt/stateful_partition/crouton/chroots/trusty/etc/resolv.conf':
Permission denied
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

**Comment by takseb** [comment]
I have the same problem that @williamjb18 had.
Downloaded chroot, installed ubuntu, xfce4, CTRL+ALT+f2 but it brought me to a developer console and it prompt me to login; i logged with the same credentials that it asked me on the chronos console after the istallation but nothing.
Pls help i'm totaly blocked

**Comment by DennisLfromGA** [comment]
@takseb, See https://github.com/dnschneid/crouton/issues/687#issuecomment-202518196

**Comment by takseb** [comment]
Oh thx, i think I'm mentaly ill for not reading that

**Comment by takseb** [comment]
@DennisLfromGA ok, that was helpfull but know every time i switch back my entire sceen is messed up:
negative, 100% contrast and so so, it was difficould even writing this msg, is there an easy solution sto stop it.
Note that before by doing CTRL+ALT+f2 brought me to the dev console and by adding SHIFT it brought me to Linux desktop I could null this screen effect by swaping to the dev console and swaping but then i restarted everything correctly by typeing sudo startxfce4 in the chronos console. Sorry if its not understandable but i can barely see what i am typeing.

**Comment by DennisLfromGA** [comment]
@takseb,

What xmethod are you using? 
Try installing and using 'xiwi' and see if your experience is better, it's the one I use exclusively now and I love it.

*Hope this helps,*
-**DennisLfromGA**

**Comment by Shermanlion6** [comment]
Hey,

I just signed the petition "PHS AND SPF: Let’s Get Our Pen Pal’s to Jersey
(before the end of the school year)" and wanted to see if you could help by
adding your name.

Our goal is to reach 200 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/snnJtzGd7y

Thanks!
Sherman

**Comment by zhmed** [comment]
you need to go crosh enter shell then enter sudo startxfce4 now!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MrHallway0** [comment]
This one is from 2014... The new ones are [here](https://github.com/dnschneid/crouton/issues)
