### ISSUE TITLE
No mouse cursor in Chrome after starting Unity

### ISSUE THREAD

**Issue by davidwallacejackson** [dnschneid/crouton#703]
I've got a chroot running saucy with Unity installed. As soon as I start Unity, if I switch back to Chrome, I can't find my cursor. The cursor works fine in Unity, and as soon as Unity shuts down, it returns to my Chrome desktop. I used to have this problem intermittently -- that is, the cursor would sometimes disappear upon returning to Chrome -- but now it happens consistently.

My machine is an Acer C720, and my croutonversion is:
crouton: version 1-20140304103726~master:6c512cef
release: saucy
architecture: amd64
targets: extension,keyboard,unity
host: version 5116.113.0 (Official Build) stable-channel peppy 

If there's other useful information I could provide, please let me know!

**Comment by dereckson** [comment]
I reopen this one.

Asus C200, powerwashed, last version of ChromeOS stable (40.0.2214.114 (64-bit) and crouton, chroot created with `sh crouton -e unity-desktop`, mouse cursor doesn't move.

**Comment by dnschneid** [comment]
Is that the same issue?  What do you mean by "doesn't move"?

**Comment by dereckson** [comment]
No, actually, it's not. After browsed another issue, I tested more strongly the touchpad, and it's the same than issue 214, a sensibility issue.

**Comment by dnschneid** [comment]
OK, please post in there your chromebook model and the sensitivity settings you arrived at.  Thanks!
