### ISSUE TITLE
Chroot password issue

### ISSUE THREAD

**Issue by Arancara** [dnschneid/crouton#705]
Having issues with chroot, I installed it, entered the usual, username, then it asks to set a password. Sadly the console allows me to enter nothing, regardless what key I press on the keyboard. The only key that functions is "enter".

I press enter, it says no password set, try again, so I try two more times and it then tells me that no password it set to use passwd user.

Installation completes, but when I use passwd or passwd user (user being alex in my case) it asks for current password, again same issue as before I cannot enter anything except the "enter key", the console then dishes me the following nonsense:
passwd: Authorisation failed
passwd: Password unchanged

I've tried the usual dish of default passwords such as root, pass, user, admin, but again it doesn't allow me to enter these passwords on the console, only on the login screen from the screensaver. And just pressing enter doesn't work either. So basically in short no password can be set nor is any password recognized. Any idea's on the solution?

I've tried removing chroot and reinstalling it again to see if it was a one off issue but sadly it's not and I have had the same issue again.

**Comment by alf11211** [comment]
Thank you , i appreciate you explaining this because i didn't see the asterisk and it really confused me .

I wish the developer will place a note when typing password but maybe they don't for security reasons.

**Comment by alf11211** [comment]
First time using chroot and a google pixel 2013 chromebook .
