### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by sjama** [dnschneid/crouton#707]
Currently I am running the cli version of crouton, no desktop environment.
This works well but I have been closely following the [Docker](https://github.com/dotcloud/docker) project and will love to just run [Docker](https://github.com/dotcloud/docker) on Chrome OS.

Is this a good idea? Is it even possible?

**PS:** I realize this issue/question is not directly related to crouton, but from the amount knowledge I have gleaned from other issues in this repo I think this is best place to get the best answer.

**Comment by apporc** [comment]
I am working on porting docker to chromiumos. Almost done.

**Comment by jpw1116** [comment]
Cool, @apporc . . . I'm still eager to see it happen on a Chromebook. Have you seen this other project (unrelated, but inspiring)? http://rancher.com/rancher-os/

**Comment by apporc** [comment]
@jpw1116 I don't have a chromebook at present, all the changes i made by now is only applied to amd64-generic architecture. I think upstream probably not agree to add docker support to the code, even dev image. So i don't know a proper way to make the changes public for whom interested in this. for the rancher-os, that's pretty cool, thank you for introducing it to me.

**Comment by kingdonb** [comment]
If you need any help with targeting armhf (like Samsung XE303C) I'm willing
to go over your burndown charts of todos, or what have you.  I didn't get
from your first message that you are actually trying to add docker support
to the upstream Chromium/ChromeOS, or fork it / create a patch set for it
for "system builders."  (For the record I think this is a great idea, even
if you don't care about ARM support at all.)


-- 

[image: https://content.metrixmatrix.com/images/logo.png]

*Kingdon Barrett*
IT Manager
785 Elmgrove Rd.
Rochester, NY 14624
585-231-1542 x 203


Philadelphia, PA – Lehighton, PA – Pottsville, PA – Rochester, NY – Sacramento,
CA

**Comment by apporc** [comment]
@kingdonb I am adding changes directly on the upstream, and keeping a local branch. There are so many repos in the project, i am not very clear about how to fork it.

**Comment by apporc** [comment]
@kingdonb it seems everything is got resolved. initctl start docker ok. docker info ok. But when i tried to start a docker container, there is an error: namespace creation reexec command failed. I only find a bug here: https://github.com/docker/docker/issues/14985, but that is because of apparmor profile. And i don't find anything about apparmor on chromeos.
Ron Minnich didn't say anything about this in https://docs.google.com/document/d/1WQnfloMbcR798Lk-iYPbvZt-wplW83IYyCf7SYyXTvs/edit  either, maybe he didn't have this error.
Have no idea at present. Time to ask for help from internet.

**Comment by perpen** [comment]
@apporc I don't know if you saw my comment on https://github.com/docker/docker/issues/15679
Your problem is due to the chromium os security module: Have function security/chromiumos/lsm.c:chromiumos_security_sb_mount return 0, this will allow reexec to work.

**Comment by apporc** [comment]
@perpen, Thanks ,i saw that.  I will try it later.

**Comment by christianbundy** [comment]
For anyone still looking to make this work, I've written up [a guide for how to get this working](https://gist.github.com/christianbundy/ba62890a7c2f8128bcbb) for the Chromebook Pixel 2.

**Comment by a1exus** [comment]
What about ASUS Chromebook Flip? Can I install Docker there?
```
chronos@localhost / $ uname -a
Linux localhost 3.14.0 #1 SMP PREEMPT Fri Jun 24 00:01:48 PDT 2016 armv7l ARMv7 Processor rev 1 (v7l) Rockchip (Device Tree) GNU/Linux
chronos@localhost / $ 
```

**Comment by christianbundy** [comment]
@a1exus Does `lsmod` return a kernel module for each item in [this list](https://github.com/docker/docker/blob/dd786eefbbf286ca57b52374a6905c1ac8b8bd60/docs/sources/installation/kernel.rst#details)?

**Comment by DennisLfromGA** [comment]
@a1exus - Why don't you try it and report back?

**Comment by christianbundy** [comment]
It looks like the RST file I linked to above is deprecated, there's now a [Bash script](https://github.com/docker/docker/blob/master/contrib/check-config.sh) that you can use to check whether you have the required kernel modules.

**Comment by a1exus** [comment]
@christianbundy:
`lsmod`:
```
chronos@localhost / $ lsmod
Module                  Size  Used by
ip6t_REJECT            12396  2 
xt_TCPMSS              12456  1 
ip6table_mangle        12455  1 
ip6table_raw           12446  1 
veth                   12870  0 
nls_iso8859_1          12386  1 
nls_cp437              12386  1 
vfat                   16850  1 
fat                    56034  1 vfat
rfcomm                 30254  4 
hci_uart               17905  1 
uinput                 16833  0 
i2c_dev                12691  0 
ipt_MASQUERADE         12495  1 
iptable_nat            12541  2 
nf_nat_ipv4            12759  1 iptable_nat
nf_nat                 17622  3 ipt_MASQUERADE,nf_nat_ipv4,iptable_nat
uvcvideo               64372  0 
bluetooth             308400  29 hci_uart,rfcomm
videobuf2_vmalloc      13118  1 uvcvideo
xt_mark                12384  5 
bridge                 78716  0 
zram                   16982  1 
stp                    12405  1 bridge
llc                    12624  2 stp,bridge
fuse                   79215  8 
nf_conntrack_ipv6      17316  10 
nf_defrag_ipv6         33178  1 nf_conntrack_ipv6
ip6table_filter        12455  2 
ip6_tables             16801  3 ip6table_filter,ip6table_mangle,ip6table_raw
brcmfmac              170614  0 
brcmutil               12941  1 brcmfmac
cfg80211              373027  1 brcmfmac
iio_trig_sysfs         12529  2 
joydev                 16757  0 
cros_ec_accel          12568  1 
kfifo_buf              12738  1 cros_ec_accel
snd_seq_midi           12668  0 
snd_seq_midi_event     13083  1 snd_seq_midi
snd_rawmidi            21698  1 snd_seq_midi
snd_seq                54620  2 snd_seq_midi_event,snd_seq_midi
snd_seq_device         12786  3 snd_seq,snd_rawmidi,snd_seq_midi
ppp_async              16845  0 
ppp_generic            25371  1 ppp_async
slhc                   12475  1 ppp_generic
tun                    25627  0 
chronos@localhost / $ 
```
not all kernel modules are in the list(
`check-config.sh`:
```
chronos@localhost ~/Downloads $ sh check-config.sh 
check-config.sh: 7: Syntax error: "(" unexpected
chronos@localhost ~/Downloads $ 
```
@DennisLfromGA - I'm not sure where to begin...

**Comment by christianbundy** [comment]
@a1exus It's a Bash script, so you'll need to run it with `bash` rather than `sh`. It looks like it probably won't work with your current kernel, so you'll have to compile a custom kernel if you'd like to. I've written a step-by-step [guide](https://gist.github.com/christianbundy/ba62890a7c2f8128bcbb) that some people have had success with, but compiling a custom kernel can be pretty obnoxious.

**Comment by hyena** [comment]
@christianbundy Do these instructions wipe one's chromebook? I notice that it's effectively building not just a new kernel but an entire new chromeos?

**Comment by iansltx** [comment]
Just got the "too many symlinks" error here. Guessing I'll have to do the whole Chromium OS with a custom kernel thing to get this working?

HP Chromebook 13 G1 FWIW.

**Comment by christianbundy** [comment]
@hyena
Yes, my guide is a complete wipe. There *may* be another way to do it, but it's so experimental that I'd just recommend wiping it.

@iansltx 
The default Chromium OS kernel doesn't have the necessary kernel modules to support Docker, so unfortunatley you'll have to use a custom kernel.
