### ISSUE TITLE
Logitech Ultrathin Touch Mouse T630 does not work

### ISSUE THREAD

**Issue by hubbamj** [dnschneid/crouton#713]
So, I have tried every version of ubuntu I can install with crouton, and none of them seem to allow the best mouse on the market, the Logitech T630 to work. The mouse works fine in chromium os but the second you transfer over to ubuntu, all you can get to register are clicks, not actual mouse movement. 

Other bluetooth mice work, such as Microsoft bluetooth mice, so I don't know if it is logitech bluetooth that does not work, or just this logitech mouse. Any ideas would be appreciated. I am new to linux, so please treat me like an idiot. 

I am using an HP Chromebook 14 and I have tried Ubuntu 12.04, 13.10 and Unity, gnome, and xfce desktops on each (yes, a lot of re installing)

**Comment by dnschneid** [comment]
It's worth trying the branch in #1302 to see if it fixes your problems.  It may be cmt taking over the mouse and not letting standard events through, which means we would need to either reactivate the standard events in crouton (probably the right short-term solution) or get cmt working better (the long-term solution).

**Comment by trisk** [comment]
I can confirm I've had the same issue with an older Logitech Wireless Touchpad for the past year. The Logitech touchpad devices default to mouse emulation, with firmware handling gestures, but cmt has special support for multitouch that probably puts the devices in a different mode.

The physical buttons work, but not touch gestures or movement. When starting Xorg, synaptics picks up the device by default due to the "touchpad" input class but synaptics is the wrong driver, anyway.

I've tried:
* Overriding the driver to evdev, which still doesn't produce events (probably because of the device state?)
* Installing Hugh Greenberg's cmt driver packages for trusty and using the same 40-touchpad-cmt.conf
The latter results in:
```
[    49.700] (II) Using input driver 'cmt' for 'Logitech Unifying Device. Wireless PID:4011'
[    49.700] (**) Logitech Unifying Device. Wireless PID:4011: always reports core events
[    49.700] (**) /dev/input/event15(**) Logitech Unifying Device. Wireless PID:4011: always reports core events
[    49.705] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:1d.0/usb4/4-1/4-1.8/4-1.8.1/4-1.8.1.3/4-1.8.1.3:1.2/0003:046D:C52B.0003/001D:046D:4011.0005/input/input16/event15"
[    49.705] (II) XINPUT: Adding extended input device "Logitech Unifying Device. Wireless PID:4011" (type: TOUCHPAD, id 9)
[    49.705] (EE) ERROR:^P:0:Couldn't recognize device class: -698162272
[    49.705] (**) Option "Two Finger Vertical Close Distance Thresh" "35.0"
[    49.705] (EE) ERROR:^P:0:Filters are not composed yet!
[    49.705] (**) Logitech Unifying Device. Wireless PID:4011: (accel) keeping acceleration scheme 1
[    49.705] (**) Option "AccelerationProfile" "-1"
[    49.705] (**) Logitech Unifying Device. Wireless PID:4011: (accel) acceleration profile -1
[    49.705] (**) Logitech Unifying Device. Wireless PID:4011: (accel) acceleration factor: 2.000
[    49.705] (**) Logitech Unifying Device. Wireless PID:4011: (accel) acceleration threshold: 4
[    49.705] (WW) ^X():405: Event_Sync_State: before 49.0 after 206158430232.140737201877088
```

I will try a rebased copy of the cmt hack branch next, though I suspect the results will be similar.

**Comment by trisk** [comment]
Wow, the cmt target works! (Though on trusty, I had to symlink ```/usr/lib/x86_64-linux-gnu/libstdc++.so.6``` -> ```/usr/local/lib/libstdc++.so``` to get ```GLIBCXX_3.4.20``` versioned symbols for ```/usr/lib/libgestures.so.0```. The external Chromium OS is dev channel)

**Comment by theblacklion** [comment]
I've a Logitech T620 (unified USB connector) which also isn't willing to move. I would be really happy if you guys (@jacklevy, @trisk) could push this matter a bit. Thanks! :)

@trisk Is your branch still working after merging the newest changes from dnschneid:master ?

**Comment by trisk** [comment]
@theblacklion I'm working on new code in croutonxi2event to handle scrolling direction changes, but I can try a merge of the existing script changes.

**Comment by rtorrero** [comment]
@trisk I'm getting here from Google, I own a T630 and i'm trying to get it play nice with Arch Linux. I'm currently using google cmt driver, but scrolling seems to be terrible (goes in huge steps, as opposed to windows, where it feels just like a regular touchpad)

If I understand correctly, did you get the T630 to have real scrolling using cmt? Any way I could replicate this?

**Comment by TriadX1** [comment]
Anyone found a solution to this?

**Comment by commiades** [comment]
I've got my T630 to work using xiwi, but that messes up the keyboard target, which works fine in xorg; all the function keys are google keys, even on an external keyboard, and I've not found any answer to this on the web.

**Comment by mark-hahn** [comment]
> but that messes up the keyboard target,

Are you on freon or on the old system?  If using freon then you will need
to use a hacked version of the chrome crouton extension.  Search this
repo's issues.  If you don't find them easily I'll find them for you.

**Comment by commiades** [comment]
Thanks. I'm on freon.

**Comment by mark-hahn** [comment]
I checked and that bug was fixed in June.
https://github.com/dnschneid/crouton/issues/1558

Sorry for the wrong info.

**Comment by commiades** [comment]
Thanks. I'm considering a powerwash and starting a new chroot to see if it has this problem.

**Comment by ericwithakay** [comment]
Just replying in case someone stumbles onto this thread while shopping for a mouse that works well with chromeOS+crouton. I purchased the logitech T630 mouse 1/22/17 and everything worked perfectly out of the box in both ChromeOS and my Xenial XFCE croot. Absolutely no configuration was required (besides pairing it in ChromeOS of course).
