### ISSUE TITLE
DE/target removal

### ISSUE THREAD

**Issue by DennisLfromGA** [dnschneid/crouton#717]
Question: Would it be feasible and not overly complicated to add an option to 'crouton' to remove a DE/target along with the update option? Maybe by specifying the target with a '-' sign in front something like: 

`sudo sh -e ~/Downloads/crouton -n saucy -t -cinnamon -u`

And then just reversing/uninstalling the target packages and dependencies?

**Comment by nakulbende** [comment]
Hey DennisL

Sorry to bother you, but I needed to remove a target which I recently installed (KDE - wishful thinking). I am not a pro at crouton/ linux. Can you please elaborate on the first step - "just grabbed the packages the targets used and applied them to the 'apt-mark auto ...' command line". I can help you in any way possible, but it seems like something useful to have on the forums. 

Thanks a lot in advance!

**Comment by DennisLfromGA** [comment]
@nakulbende,

This is part of the 'kde' target:
```
### Append to prepare.sh:
install --minimal kde-plasma-desktop -- network-manager
```
So I think you'll just need to do: 
1. `sudo apt-mark auto kde-plasma-desktop`
2. Then remove 'kde' from both `/.crouton-targets` and `/etc/crouton/targets`
3. Then `apt-get install -f`
4. Then exit your chroot and do a crouton update.

The 3rd step *may* not be necessary but it shouldn't hurt anything.

**Comment by DannyQuah** [comment]
Thank you for this very helpful thread. Can I check, @DennisLfromGA, when you say "grabbed the packages the targets used and applied them to the 'apt-mark auto ...' command line", where should I look to find the packages that, say, unity used?

**Comment by DennisLfromGA** [comment]
@DannyQuah,

All the crouton target files are here: [targets](https://github.com/dnschneid/crouton/tree/master/targets)
You can click on both [unity](https://github.com/dnschneid/crouton/blob/master/targets/unity) & [unity-desktop](https://github.com/dnschneid/crouton/blob/master/targets/unity-desktop) and find the `install ...` line(s) to determine what packages are included with each target.

@Dennis

**Comment by dennis** [comment]
FYI: When you @Dennis - you notify me. Please don't unless you wan't me attention

**Comment by DennisLfromGA** [comment]
@Dennis - My bad, sorry. 

I usually sign my posts with '**DennisL**' but I evidently left off the '**L**' previously.

I just now discovered that '**DennisL**' is also flagging the wrong account so I'll cease and desist that too. :/ 

I'll be sure to sign-off as '@DennisLfromGA' or just '**-DennisL**' in the future.

Thanx for post, I'm sure '**DennisL**' thanks you too. ;)

-**DennisL**

**Comment by dennis** [comment]
Don't worry about it. You're not the first, and probably not the last doing that :)

**Comment by shippy** [comment]
Data point: I tried to remove `xiwi` to slim down the install to `cli-extra,extension` on `xenial` -- because I do use CLI interaction (`croutonwebsocket, croutonnotify, croutonurlhandler`), but none of the graphics. I took a look at `targets/xiwi`, cross-checked what it installed with `apt-mark showmanual`, and ran `sudo apt-mark auto xserver-xorg-video-dummy x11-utils xautomation xbindkeys xorg xclip dmz-cursor-theme && sudo apt-get autoremove`. I then removed `x11, xorg, audio` from `/.crouton_targets` and `/etc/crouton/targets`. Unmounted, ran an update, and watched it fail:

```
The following packages have unmet dependencies:
 xserver-xorg-video-dummy : Depends: xorg-video-abi-15
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to complete chroot setup.
```

The failure is, of course, that I hadn't checked `targets/extension`, or I would have seen that `extension` installs `xorg` and `x11`, too.

**Takeaways**:

1. Look at *all* targets to determine what dependencies they keep before attempting to remove packages.
2. Run `autoremove` **last**. The order is:
    1. Remove targets you wish to remove from `/.crouton_targets` and `/etc/crouton/targets`,
    2. `apt-mark auto` the packages you imagine you'll get rid of without said targets,
    3. Update your chroot, which will mark the packages your remaining targets (and the dependent targets they install) back from `auto` to `manual`,
    4. After chroot is set up successfully, `sudo apt-get autoremove`.

**Comment by shippy** [comment]
I wonder if the info necessary for step (ii) could be reliably determined by doing a dry-run of target installations? The broad logic I imagine for `crouton -u -n chroot -t xfce4,-lxde`:

1. In a dry run that doesn't actually install anything, collect the list of packages that would be installed for:
    a. All old and all new targets,
    b. ^ without the targets intended for removal.
2. Get the set difference from the two lists. Those are the packages that can be safely marked `auto`, so mark them.
3. Either run `autoremove` or instruct the user to.

No idea if this is doable, or doable consistently across installers / releases. I'll try and see how much of this is wishful thinking; suggestions appreciated.

**Comment by jcao219** [comment]
This would be a really welcome change for me. Afterwards, I would finally be able to remove xfce from my encrypted chroot (is there a way to currently do it?).
