### ISSUE TITLE
HP Chromebook 14 - "Static-y" sound issue.

### ISSUE THREAD

**Issue by ChildOfDreams** [dnschneid/crouton#737]
Hello. Whenever I play sound through my Saucy installation, through notifications, applications, Youtube etc, the sound has static as it is played, but otherwise plays fine, as if the sound has awful compression. The sound quality is completely fine on Chrome OS, so I take it that it may be an issue with cras.

**Comment by tjstrunk** [comment]
I was having this problem on my Toshiba Chromebook and just tried restarting. Seemed to fix this issue. (I imagine you all tried that first, too, and then attempted more technical solutions.) Hopefully it doesn't come back and force me to learn more about the Chrome OS than I had really cared to know as a mindless consumer :P
