### ISSUE TITLE
crouton shell unicode

### ISSUE THREAD

**Issue by dimonf** [dnschneid/crouton#74]
This does not relates to crouton directly, as far as I understand:
am I right, that there is no support for unicode if I login via build-in chromium terminal? I just realized that I can read/write text in cyrilic in bash shell within crouton ... What a pity ...

**Comment by coderofsalvation** [comment]
@chee put 'set encoding=utf8' in your vimrc and you wont need ssh

**Comment by Jimsy2** [comment]
```
sh crouton -r stretch -t core   # ... is how I installed crouton
sudo enter-chroot               
sudo apt-get install locales    
sudo dpkg-reconfigure locales   # ... and selected de_DE.UTF-8
echo >>~/.bashrc export LANG=de_DE.UTF-8
```

This  fixed the missing UTF-8 for me.

**Comment by tangentsoft** [comment]
@Jimsy2 You shouldn't need to manually set `LANG`, `LC_*`, etc. During the "reconfigure" step, it asks what your default LANG type should be. All you need for that variable and the rest to be set is to exit the crouton chroot and re-enter it. In your case, you'll get what you expect if you selected `de_DE.UTF-8` when asked for your desired default on the second screen.

**Comment by Jimsy2** [comment]
@tangentsoft You are right regarding that `LANG` is set by `dpkg-reconfigure locales` and that I should have restarted Crouton to apply the changes. I used `source ~/.bashrc` to apply the changes made to `.bashrc` instead which is not so nice.

Therefore I added the missing variables to `/etc/default/locale` now:

```
(stretch)jimsy@localhost:~$ cat /etc/default/locale 
#  File generated by update-locale
LANG=de_DE.UTF-8
#  added manually
LC_ALL=de_DE.UTF-8
LANGUAGE=de_DE.UTF-8
```
