### ISSUE TITLE
Upgrade of crouton bricks Chromebook due to dev_boot_signed_only=1

### ISSUE THREAD

**Issue by wchao** [dnschneid/crouton#765]
I have an Acer C720 running ChromeOS 34.0.1847.118. I installed crouton on my Chromebook and it worked great. Because I wanted to use virtualization, I chose to add the disablevmx=off option to the kernel boot command line, which required that I set dev_boot_signed_only=0. All was well. Then I upgraded crouton, which set dev_boot_signed_only=1 again. When I rebooted, my Chromebook was unable to boot the active image, since it requires a kernel signed by Google.

I would like to suggest that when performing updates, crouton first check if the currently active image is signed by Google. If not, it should not set dev_boot_signed_only to 1. Otherwise people will run into the same problem as me. That should help for the future.

Does anyone know how I can either set dev_boot_signed_only=0 or boot using the previous boot image in /dev/sda2 or /dev/sda4? I believe the other boot partition has a boot image that IS signed by Google, so if I can get in, then I can run crossystem dev_boot_signed_only=0 and all should be well. It's just getting in that's the hard part. I'd prefer not to reformat the drive since I spent a couple of days getting the chroot Debian and the Windows VM under VirtualBox just so, and I'm not looking forward to repeating all that work.

**Comment by rrolsbe** [comment]
wchao commented on Apr 16, 2014

I managed to recover the data. I had another Chromebook and realized that if I took the SSD from the other Chromebook, I would be able to boot. Then I set dev_boot_signed_only=0, and installed the original SSD. Problem solved.

I am looking for some clarification on exactly what wchao did and why it worked.  I assume the drive from the other Chromebook must have also been in Developer Mode (or  the Developer Mode status is stored in the r/w firmware) and had the kernel boot bits stored on the drive were signed by Google, else the dev_boot_signed_only=0 command could not have been executed?  Also, The dev_boot_signed_only status must be stored in the r/w firmware area of Chromebooks, and NOT anywhere on the hard drive?

Thanks Much In Advance for any clarification!

Regards, Ron

PS - I had to perform a Recovery from USB after performing a crouton update. After the update and execution of the "sudo startxfce" command, it promptly crashed and rebooted thereafter.  The dev_boot_signed_only must of been set to 1 by the update.

**Comment by wchao** [comment]
The other Chromebook was in Developer mode. Anecdotally, I seem to recall that in the past few months, crouton seems to again set dev_boot_signed_only=1. It didn't brick my Chromebook because I was careful to check for it after my previous near-trauma, but I'm sure some people are caught up by it. I haven't played with it much recently, so I don't know if it's still doing that as of the last few weeks.

**Comment by drinkcat** [comment]
@rrolsbe : Sorry about that... There is a fix in #785, but it has not been merged yet: we had so few reports that we deviced to leave it aside. We will revisit it at some point...

In the mean time, unless you have strong security concerns, I'd suggest enabling USB booting (`crossystem dev_boot_usb=1`). That'll prevent crouton from flipping `dev_boot_signed_only`, and provide you with another way to recover your data (booting an image from USB).

**Comment by rrolsbe** [comment]
@drinkcat 

Thanks for the reply!  Since I own the two C710 Chromebooks, (the ones without the Seabios payload, thus not allowing traditional Legacy OS USB booting) what can I boot via USB  to access the internal hard/flash drive content?  Informational link would be greatly appreciated.

Thanks Again!!
Regards, Ron

**Comment by DennisLfromGA** [comment]
If you have or can build ChrUbuntu on an external usb stick and
'dev_boot_usb' is set to 1, then you can boot it via Ctrl-U at startup and
then get to your hard drive I believe.

On Wed, Jan 14, 2015 at 3:46 PM, rrolsbe <notifications@github.com> wrote:

> @drinkcat <https://github.com/drinkcat>
>
> Thanks for the reply! Since I own the two C710 Chromebooks, (the ones
> without the Seabios payload, thus not allowing traditional Legacy OS USB
> booting) what can I boot via USB to access the internal hard/flash drive
> content? Informational link would be greatly appreciated.
>
> Thanks Again!!
> Regards, Ron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnschneid/crouton/issues/765#issuecomment-69988388>.
>



-- 
*DennyL@GMail*

**Comment by dnschneid** [comment]
I noticed an interesting tidbit in [the verified dev mode wiki page](https://sites.google.com/site/chromeoswikisite/home/what-s-new-in-dev-and-beta/shell-acess-with-verified-boot):

> Or, from the shell, run crossystem without arguments as root.  You can also run crossystem kernkey_vfy.  If sig is returned, the kernel is a Google signed kernel.  Any other kernel partition returns hash, so you shouldn't see that value immediately following a verfied boot.

To those potentially affected by this (you know who you are, and @divx118 for good measure): could you run ``echo `crossystem kernkey_vfy` `` from the crosh shell and confirm that it returns `hash`?

**Comment by dnschneid** [comment]
Actually, the output of ``echo `crossystem mainfw_type` `` would also be useful.

**Comment by wchao** [comment]
I am running Chrome OS 42.0.2311.87 (64 bit) with a patched kernel partition (to add disablevmx=off lsm.module_locking=0 to the kernel command line). I get the following crossystem values:

crossystem kernkey_vfy: hash
crossystem mainfw_type: developer

**Comment by dnschneid** [comment]
Sweet.  One more thing: next time you (or anyone) get an update such that you have to re-patch your kernel, could you run both commands 3 times: before patching it, after patching it, and after rebooting?

**Comment by wchao** [comment]
Sure, happy to. I'm using the latest Chrome OS, so I don't know when the next time will be, but I would guess in 1 - 2 months it's likely.

**Comment by dnschneid** [comment]
If enough people say `kernkey_vfy` reflects reality, I might commit the check but keep this bug open until people can confirm that it changes immediately after kernel patch (i.e., not after next boot-up).  I'm not sure it does, so it may just be a nice extra safety measure.

If it DOES immediately change, then it may also be worth it to add checks to crouton enter_chroot to see if the status changed, and then alert/disable verified boot to prevent people from nuking themselves even outside the context of an install or update.

**Comment by divx118** [comment]
@dnschneid  If there is an update pending, the next reboot will boot another kernel. My script detects the on a reboot booted kernel and patches that. If I patch a kernel the crossystem flags will not change immediately, because the patched kernel will only be active after a reboot. This could be tricky, I need to think about it.

**Comment by dnschneid** [comment]
OK, it may be worth doing to avoid breaking an already-modified install, but it can't be used to save people about to nuke themselves.

**Comment by divx118** [comment]
I would rather prefer something like @drinkcat proposed in #785 to be really sure all kernels are signed correctly before enabling the flag. We now also have [the waiting time](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L558) when the flag is disabled. On my HP chromebook 14 the test takes about 5-6 seconds.
Sadly there doesn't seem to be a faster way to check the kernels.
Checking just `crossystem kernkey_vfy` and `crossystem mainfw_type` will still require that I set `crossystem dev_boot_usb=1 dev_boot_legacy=1`  in [my script](https://github.com/divx118/crouton-packages/blob/master/change-kernel-flags) to be sure they don't get a non bootable system.

That said keeping `crossystem dev_boot_usb=1 dev_boot_legacy=1` to prevent enabling `dev_boot_signed_only` is fine by me.

**Comment by wchao** [comment]
OK, I had the opportunity to perform an update. I ran the update, then rebooted. Then, before I patched, I ran:

echo `crossystem kernkey_vfy`
sig

echo `crossystem mainfw_type`
developer

After patching, I ran:

echo `crossystem kernkey_vfy`
sig

echo `crossystem mainfw_type`
developer

After reboot, I ran:

echo `crossystem kernkey_vfy`
sig

echo `crossystem mainfw_type`
developer

**Comment by dnschneid** [comment]
...oh well.

**Comment by 9291Sam** [comment]
Over 2 years later I just had this exact issue so it seems it is still not fixed

**Comment by DennisLfromGA** [comment]
@9291Sam,

crouton's [current logic](https://github.com/dnschneid/crouton/blob/master/installer/main.sh#L570) is to set 'dev_boot_signed_only=**1**' **_only_** when 'dev_boot_usb' **_and/or_** 'dev_boot_legacy' are **_not set / off_**. 

I have my options configured to boot both usb & legacy so crouton leaves the 'dev_boot_signed_only' bit unset, see below:
```
dev_boot_usb          = 1     # Enable developer mode boot from USB/SD (writable)
dev_boot_legacy       = 1     # Enable developer mode boot Legacy OSes (writable)
dev_boot_signed_only  = 0     # Enable developer mode boot only from official kernels (writable)
```

*Hope this helps,*
-**DennisL**

**Comment by tedm** [comment]
@DennisLfromGA a few weeks ago, there was a known issue where certain older Toshiba Chromebook 2's lost their video on all channels except stable. So I reverted to stable to get video back, and re-installed crouton, but the command for targets did not work: 

sh ~/Downloads/crouton -t list

I was fine installing cli-extra, but that should get fixed.

**Comment by DennisLfromGA** [comment]
@tedm,

It still works for me with or without `sudo`

```
chronos@localhost ~ $ sh ~/Downloads/crouton -t list
Available targets:
audio
        Support audio playback via Chromium OS's audio system.
        Requires: core
chrome
        Google Chrome browser, stable channel.
        Requires: x11
chrome-beta
        Google Chrome browser, beta channel.
        Requires: x11
chrome-dev
        Google Chrome browser, dev channel.
        Requires: x11
chromium
        Chromium browser. Uses the distro's version, which may be old.
        Requires: x11
cli-extra
        Basic CLI tools such as ssh.
        Requires: core
core
        Performs core system configuration. Most users would want this.
e17
        Installs the enlightenment desktop environment. (Approx. 50MB)
        Requires: gtk-extra
extension
        Clipboard synchronization and URL handling with Chromium OS.
        Requires: x11
gnome
        Installs the GNOME desktop environment. (Approx. 400MB)
        Requires: gtk-extra
gnome-desktop
        Installs GNOME along with common applications. (Approx. 1100MB)
        Requires: gnome
gtk-extra
        GTK-based tools including gdebi, gksu, and a simple browser.
        Requires: x11
kde
        Installs a minimal KDE desktop environment. (Approx. 600MB)
        Requires: x11
kde-desktop
        Installs KDE along with common applications. (Approx. 1000MB)
        Requires: kde
keyboard
        Adds support for Chromebook keyboard special keys.
        Requires: x11
lxde
        Installs the LXDE desktop environment. (Approx. 200MB)
        Requires: gtk-extra
lxde-desktop
        Installs LXDE along with common applications. (Approx. 800MB)
        Requires: lxde
touch
        Touchscreen and limited generic gesture support.
        Requires: x11
unity
        Installs the Unity desktop environment. (Approx. 700MB)
        Requires: gtk-extra
unity-desktop
        Installs Unity along with common applications. (Approx. 1100MB)
        Requires: unity
x11
        X11 via autodetected backend. Does not install any desktop environment.
xbmc
        Installs the XBMC media player. (Approx. 140MB)
        Requires: x11
xfce
        Installs the Xfce desktop environment. (Approx. 250MB)
        Requires: gtk-extra
xfce-desktop
        Installs Xfce along with common applications. (Approx. 1200MB)
        Requires: xfce
xiwi
        X.org X11 backend running unaccelerated in a Chromium OS window.
        Requires: audio extension
xorg
        X.Org X11 backend. Enables GPU acceleration on supported platforms.
        Requires: audio
chronos@localhost ~ $ 
```

*Hope this helps,*
-**DennisL**

**Comment by tedm** [comment]
Thanks, it works, I forgot the "sh"! A suggestion would be to make crouton executable (600 or 666) and not need the sh ?

**Comment by DennisLfromGA** [comment]
@tedm,

The stateful_partition where your `~/Downloads` folder resides is not mounted executable by default so making 'crouton' executable would not help, if I understand it correctly.

I re-mount it in my `.bashrc` script though to get past some of these limitations,

`sudo mount -i -o remount,exec /home/chronos/user`

*Hope this helps,*
-**DennisL**

**Comment by tedm** [comment]
@DennisLfromGA Thanks! I'll test it when I'm home. I'm pretty sure I've chmodded scripts and they've executed in ~/Downloads, and I don't recall having changed the mount flags.

These days, I'm hesitant to make many changes, since I seem to have to powerwash often. My first gen Toshiba Chromebook 2 is getting old, it still plays netflix fine, browses web, and runs crouton, but I don't think it's ever getting the ability to run android apps.

**Comment by tedm** [comment]
I have been playing with Windows bash dev edition lately, and it needs crouton badly. Perhaps the contributors should sell it to MS for $100 Billion and evenly split the proceeds ?? ;)

**Comment by 9291Sam** [comment]
That work nicely
