### ISSUE TITLE
Are kernel headers the same for different Chromebooks?

### ISSUE THREAD

**Issue by ShawnZhong** [dnschneid/crouton#772]
In that case I think we could share `linux-headers-3.8.11_3.8.11-10.00.Custom_amd64.deb` and `linux-image-3.8.11_3.8.11-10.00.Custom_amd64.deb` files.

See https://github.com/dnschneid/crouton/wiki/Build-kernel-headers-and-install-Virtualbox-(x86)

**Comment by Jackhford** [comment]
I hate to bother you about this.

I bought a new HP Chromebook 14 (2014), which I think is the best chromebook available. The screen may not have the highest resolution, but it's very good, good battery life, great keyboard, and upgradeable SSD - mine is 240gb.

Crouton and Ubuntu/Unity are installed. I tried to install Virtualbox again but have errors. I've tried and tried again, yet the errors persist. A screenshot is attached for your convenience.

I hope you can help me. I really appreciate you help.
![workspace 1_001](https://cloud.githubusercontent.com/assets/8303122/8767164/db962bea-2e08-11e5-8201-24c30b5d06ae.png)

**Comment by divx118** [comment]
@Jackhford Did you follow https://github.com/divx118/crouton-packages/blob/master/README.md before trying to install virtualbox and get it running.

**Comment by Jackhford** [comment]
I just completed you suggestion. All went well until I tried to install VirtualBox 5.0. Here's the gdebi error message:
Error: Breaks existing package 'virtualbox' that conflict: 'virtualbox'. But the '/home/jack/Downloads/virtualbox-5.0_5.0.0-101573-Ubuntu-trusty_amd64.deb' provides it via: 'virtualbox'
Any suggestions?

Thanks again

**Comment by Jackhford** [comment]
I think the linux headers need to be reinstalled in order for Virtualbox 5.0 to work. Do you agree?

**Comment by divx118** [comment]
I think you should uninstall virtualbox which you previously installed. `sudo apt-get remove virtualbox` then install your virtualbox deb package. At least according to the error `Error: Breaks existing package 'virtualbox' that conflict: 'virtualbox'.`

**Comment by Jackhford** [comment]
I've done that about 3 times. But I get the same error message each time I attempt to reinstall Virtualbox.

**Comment by Jackhford** [comment]
Hold on, Maurice. I tried again and I think it worked. Will post final results.

**Comment by Jackhford** [comment]
Ok, Maurice. Some progress (?) to report. I installed Virtualbox 5.0, rebooted to be sure everything was properly written. I ran VirtualBox, but I got exactly the same error I reported above with its attached screenshot. I'm sure you'll a very simple quick fix.
Thanks again

**Comment by divx118** [comment]
@Jackhford What is the output of `sudo /etc/init.d/vboxdrv setup` executed in the chroot on the command line?
Also can you give the output of `cat /proc/cmdline` and `uname -a`.

**Comment by Jackhford** [comment]
On Tue, Jul 21, 2015 at 10:22 AM, Maurice van Kruchten <
notifications@github.com> wrote:

> sudo /etc/init.d/vboxdrv


​Here you go:​

​(trusty)root@localhost:/home/jack# sudo /etc/init.d/vboxdrv
Usage: /etc/init.d/vboxdrv
{start|stop|stop_vms|restart|force-reload|status|setup}

​(trusty)root@localhost:/home/jack# cat /proc/cmdline
cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic
panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3
dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752
verity payload=PARTUUID=5a2fbf00-2067-da43-9ff9-c8c89f675c3a/PARTNROFF=1
hashtree=PARTUUID=5a2fbf00-2067-da43-9ff9-c8c89f675c3a/PARTNROFF=1
hashstart=2506752 alg=sha1
root_hexdigest=ac631d7057709155cc343dadbc4c436390cd7c5a
salt=ece2d11ed0bee603ed305a767fa0ff120ea11e3f08413850589e2a6d4860bd06"
noinitrd vt.global_cursor_default=0
kern_guid=5a2fbf00-2067-da43-9ff9-c8c89f675c3a add_efi_memmap boot=local
noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0
nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3
disablevmx=off  lsm.module_locking=0

(trusty)root@localhost:/home/jack# uname -a
Linux localhost 3.8.11 #1 SMP Tue Jul 14 00:18:51 PDT 2015 x86_64 x86_64
x86_64 GNU/Linux




================================


http://photonfunding.com

http://bit.ly/UYxJfv
Google+

Numerous Free Factoring Web Services - here are a few:
- 24/7 Online Invoice Creation System
- QuickBooks&reg; Factoring Integration
- Accounting Adjustments Displayed Online
- Electronic Timesheets for Staffing Firms
- SMS Funding Alerts
- Customer Check Images Displayed Online
*Jack Ford, Manager*
T: 213-973-CASH (2274) | F: 213.596.5787 | E: jford@photonfunding.com
<jford@21stcapital.com>

**Comment by divx118** [comment]
@Jackhford Don't forget "setup" `sudo /etc/init.d/vboxdrv setup` else it will only print you the usage.

**Comment by Jackhford** [comment]
Sorry. Oversight.

(trusty)root@localhost:/home/jack# sudo /etc/init.d/vboxdrv setup
Stopping VirtualBox kernel modules ...done.
Uninstalling old VirtualBox DKMS kernel modules ...done.
Trying to register the VirtualBox kernel modules using DKMS ...done.
Starting VirtualBox kernel modules ...done.



================================


http://photonfunding.com

http://bit.ly/UYxJfv
Google+

Numerous Free Factoring Web Services - here are a few:
- 24/7 Online Invoice Creation System
- QuickBooks&reg; Factoring Integration
- Accounting Adjustments Displayed Online
- Electronic Timesheets for Staffing Firms
- SMS Funding Alerts
- Customer Check Images Displayed Online
*Jack Ford, Manager*
T: 213-973-CASH (2274) | F: 213.596.5787 | E: jford@photonfunding.com
<jford@21stcapital.com>

**Comment by divx118** [comment]
Hmm looks good. Try starting virtual box again. If it gives you an error again then give the output of `cat /proc/modules`

**Comment by Jackhford** [comment]
I'm not sure I would call it an error. But the following happened and has
happened often. When I click start and it tries, in the case, to load my
Win8.1, it fails with the error "Fatal: No bootable medium found! System
halted." I then X out and "Power Off" the machine and try again. This time
I press search key + += key (F12) to the left of the backspace key and get
the following, instead:
Detected hard disks
ACHI Controller
   1) Hard disk
Other boot devices:
   f) Floppy
   c) CD-ROM
   l) Lan

   b) Continue booting

I think I'm supposed to select "Hard disk," but I don't know how to do so.
Have you seen this before and do you know how to get past this message?

But here's the output you requested:

(trusty)root@localhost:/home/jack# cat /proc/modules
vboxpci 19047 0 - Live 0xffffffffc029a000 (O)
vboxnetadp 25443 0 - Live 0xffffffffc0292000 (O)
vboxnetflt 23901 0 - Live 0xffffffffc02a9000 (O)
vboxdrv 335916 3 vboxpci,vboxnetadp,vboxnetflt, Live 0xffffffffc023e000 (O)
hidp 20761 1 - Live 0xffffffffc0237000
i2c_dev 12352 0 - Live 0xffffffffc0232000
uinput 16448 0 - Live 0xffffffffc022c000
rfcomm 25349 4 - Live 0xffffffffc0220000
snd_hda_codec_realtek 32832 1 - Live 0xffffffffc0216000
memconsole 12352 0 - Live 0xffffffffc01f0000
uvcvideo 67475 0 - Live 0xffffffffc0204000
videobuf2_vmalloc 12313 1 uvcvideo, Live 0xffffffffc01eb000
snd_hda_codec_hdmi 33201 1 - Live 0xffffffffc01e1000
zram 16620 1 - Live 0xffffffffc01db000 (C)
lzo_compress 12354 1 zram, Live 0xffffffffc01d6000
zsmalloc 12659 1 zram, Live 0xffffffffc01ae000 (C)
snd_hda_intel 36928 8 - Live 0xffffffffc01f9000
snd_hda_codec 118597 3
snd_hda_codec_realtek,snd_hda_codec_hdmi,snd_hda_intel, Live
0xffffffffc01b8000
snd_hwdep 12390 1 snd_hda_codec, Live 0xffffffffc01b3000
snd_pcm 69703 3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec, Live
0xffffffffc019b000
snd_page_alloc 12806 2 snd_hda_intel,snd_pcm, Live 0xffffffffc018e000
snd_timer 25190 1 snd_pcm, Live 0xffffffffc0193000
fuse 63981 2 - Live 0xffffffffc017d000
nf_conntrack_ipv6 12352 2 - Live 0xffffffffc0178000
nf_defrag_ipv6 12569 1 nf_conntrack_ipv6, Live 0xffffffffc0099000
ip6table_filter 12352 1 - Live 0xffffffffc0063000
ip6_tables 20721 1 ip6table_filter, Live 0xffffffffc0171000
ath9k_btcoex 122464 0 - Live 0xffffffffc0152000
ath9k_common_btcoex 12780 1 ath9k_btcoex, Live 0xffffffffc0068000
ath9k_hw_btcoex 353366 2 ath9k_btcoex,ath9k_common_btcoex, Live
0xffffffffc00fa000
ath 21105 3 ath9k_btcoex,ath9k_common_btcoex,ath9k_hw_btcoex, Live
0xffffffffc0092000
mac80211 330382 1 ath9k_btcoex, Live 0xffffffffc00a8000
cfg80211 141270 3 ath9k_btcoex,ath,mac80211, Live 0xffffffffc006e000
ath3k 12352 0 - Live 0xffffffffc005e000
btusb 20544 0 - Live 0xffffffffc00a1000
bluetooth 211859 27 hidp,rfcomm,ath3k,btusb, Live 0xffffffffc0029000
joydev 16448 0 - Live 0xffffffffc0023000
ppp_async 16448 0 - Live 0xffffffffc001d000
ppp_generic 21018 1 ppp_async, Live 0xffffffffc0012000
slhc 12531 1 ppp_generic, Live 0xffffffffc000b000
tun 20583 0 - Live 0xffffffffc0000000





================================


http://photonfunding.com

http://bit.ly/UYxJfv
Google+

Numerous Free Factoring Web Services - here are a few:
- 24/7 Online Invoice Creation System
- QuickBooks&reg; Factoring Integration
- Accounting Adjustments Displayed Online
- Electronic Timesheets for Staffing Firms
- SMS Funding Alerts
- Customer Check Images Displayed Online
*Jack Ford, Manager*
T: 213-973-CASH (2274) | F: 213.596.5787 | E: jford@photonfunding.com
<jford@21stcapital.com>

**Comment by divx118** [comment]
Well you need to provide an iso image of an install disk from windows 8.1 or any other windows version you want to run, but this is more related to how to use virtualbox. See for example http://betanews.com/2013/10/21/install-windows-8-1-on-oracle-virtualbox/. 
According to /proc/modules vbox modules are loaded so you should be good to go.

**Comment by Jackhford** [comment]
Thanks for checking back in, Maurice. Looks like I've got Win 8.1 running
with Guest Additions and the Extension Pack. I would love to see it
beautifully populating the entire display as it does on a PC. If you know,
please advise.

Thanks again for all your help



================================


http://photonfunding.com

http://bit.ly/UYxJfv
Google+

Numerous Free Factoring Web Services - here are a few:
- 24/7 Online Invoice Creation System
- QuickBooks&reg; Factoring Integration
- Accounting Adjustments Displayed Online
- Electronic Timesheets for Staffing Firms
- SMS Funding Alerts
- Customer Check Images Displayed Online
*Jack Ford, Manager*
T: 213-973-CASH (2274) | F: 213.596.5787 | E: jford@photonfunding.com
<jford@21stcapital.com>

**Comment by divx118** [comment]
Change the screen resolution of your virtualbox machine to the same as your chromebook display. Then run virtualbox in fullscreen mode.

**Comment by hongshiong** [comment]
Hi @divx118  I am working on acer c710, when i installed crouton in my Chromebook and also virtualbox, it show an error when i press start on virtualbox manager, 'The virtual machine 'Window 10' has terminated unexpectedly during startup with exit code 1 (0x01).' I would really appreciate if you could help me. Thanks!
 
![img_20150920_173520](https://cloud.githubusercontent.com/assets/14369108/9980089/1e6d9e9e-5fbe-11e5-8f43-ca67fa2b36af.jpg)

**Comment by skoocda** [comment]
Hi, after running your entire code to replace the 3.8.11 headers, I received this:

 Hmm. There is a symbolic link /lib/modules/3.8.11/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/3.8.11/build

 Hmm. The package shipped with a symbolic link /lib/modules/3.8.11/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/3.8.11/source

*Note:* Followed https://github.com/dnschneid/crouton/issues/772#issuecomment-40894248
to try to get a make command working with the following error:

    (trusty)skoocda@localhost:~/USBLAN/dm9601$ make -f Makefile      
    make -C /lib/modules/3.8.11/build M=/home/skoocda/USBLAN/dm9601  
    make: *** /lib/modules/3.8.11/build: No such file or directory.  Stop.
    make: *** [default] Error 2
