### ISSUE TITLE
Does Unity 8 Desktop Preview work with Crouton in 14.04?

### ISSUE THREAD

**Issue by vladashram** [dnschneid/crouton#778]
I have been using crouton since I got a chromebook and the other day I was experimenting trying to find a way to launch Unity8 desktop available as a preview in 14.04. I found instructions on how to install and launch on a normal Ubuntu install but trying to adapt them here has given me a bit of trouble. Does anybody have an idea if it could actually work since Unity8 relies on mir? And if it could do you know what would be the proper command to launch it?

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
