### ISSUE TITLE
xbmc on saucy produces “static” noise

### ISSUE THREAD

**Issue by drinkcat** [dnschneid/crouton#792]
Probably the same as the second part of #737 as reported by @divx118, but that issue was closed so I want to keep track of it. Maybe similar in symptoms to #791.

Steps to reproduce:
 - Install saucy chroot, xbmc target only
 - `sudo startxbmc`
 - Any audio sounds like white noise (including sound effect when switching between menu items)

Other notes:
 - After reducing volume to minimum (without muting): sound is ok
 - pulseaudio fixes the problem
 - `aplay -Dcras /usr/share/sounds/alsa/Front_Center.wav` works fine (I mean, “center” is cut, but that’s another problem)
 - Modifying the volume in XBMC does not change the level in `cras_test_client` or `alsamixer`.

```
$ croutonversion 
crouton: version git (that's 609fe46038)
release: saucy
architecture: amd64
targets: xbmc
host: version 5764.0.0 (Official Build) dev-channel peppy
```

Just a hunch, looking at XBMC log (`.xbmc/temp/xbmc.log`), I see: `Sample Format : AE_FMT_S24NE4`. What we test normally is 16-bit audio, not 24-bit… Wondering if the data is getting truncated (might explain why it works at low volume, since the volume is software-controlled in that case)...

**Comment by dnschneid** [comment]
Assuming obsolete.

**Comment by ironman5366** [comment]
I still have the problem on Trusty and the latest crouton
