### ISSUE TITLE
chroot backup fails when ~/Downloads is tmpfs-backed

### ISSUE THREAD

**Issue by rusvnc** [dnschneid/crouton#803]
I've never had this issue before, but I'm now getting this error consistently and am unable to back up my chroot:

$ sudo edit-chroot -b precise
Unmounting /usr/local/chroots/precise...
tar: precise-20140426-0036.tar: Wrote only 4095 of 10240 bytes36.tar...
tar: Error is not recoverable: exiting now
Unable to backup /usr/local/chroots/precise.
Deleting partial archive.

**Comment by dnschneid** [comment]
Fixed in the latest crouton.
