### ISSUE TITLE
Installing crouton on an external hard drive

### ISSUE THREAD

**Issue by devonpeak** [dnschneid/crouton#808]
I've tried installing crouton onto each of my 3 USB flash drives, but did not have sufficient permission (I don't remember the exact error) and that's what I expected. However, is it possible to install to and run it from an external hard drive? I know very little about hardware, so I don't know what, if any, difference there is between a flash drive and external hard drive although I'm thinking there is a huge difference. I've heard the terms FAT32 and NTFS and I think they're relevant, but not sure.

The reason I'd like to install to an external hard dive is the lack of space available on my Chromebook (16GB) and despite my chroot and software being fairly small, I'd like future downloads to be stored on something portable and am assuming the whole chroot needs to be.

**Comment by Anklebitter** [comment]
I have a question can I run a chroot on my flash drive and one on my chromebook at the same time?

**Comment by robinvd** [comment]
@Anklebitter You can run as many as you want from anywhere you want (with the ext2/3/4 limitation). So yea you can do that

**Comment by DennisLfromGA** [comment]
To add to @robinvd's reply, just be sure to specify where your chroots are located.

With `crouton` for installaitons and updates, you use the '**-p**' option:
```
    -p PREFIX   The root directory in which to install the bin and chroot
                subdirectories and data.
                Default: /usr/local, with /usr/local/chroots linked to
                /mnt/stateful_partition/crouton/chroots.
```
With `edit-chroot`, `enter-chroot`, and all of your `start*` scripts, you use the '**-c**' option:
```
    -c CHROOTS  Directory the chroots are in. 
                Default: /mnt/stateful_partition/crouton/chroots
```
*Hope this helps,*
-**DennisL**
