### ISSUE TITLE
Steam In-Home Streaming does not work

### ISSUE THREAD

**Issue by The-MAZZTer** [dnschneid/crouton#809]
This is just about the PCs being able to see each other; nothing about actual streaming video right now. :P

Few problems here:
1. On the host, you can see the Chromebook in the In-Home Streaming settings, but the name shows up as "localhost".  Whatever value Steam on crouton is pulling should be changed to match the chroot name if possible...
2. No PCs on the LAN show up in the Chromebook's In-Home Streaming settings.

Hooking up Wireshark on the host indicates that the host does seem to receive and dispatch UDP packets from the Chromebook on the In-Home Streaming discovery port (27036), which makes sense since it's showing up however when I run Wireshark on the Chromebook I get no traffic at all on the port and could not reproduce the traffic on the host... running iptables -P INPUT ACCEPT as recommended in other crouton bug had no effect on this.

The host has port 27036 open for listening but the client does not... but this could be intentional as Linux is not supported for In-Home Streaming hosting, so I dunno...

Reproduction: I created a trusty crouton and installed steam by downloading it from steampowered.com (I needed to do apt-get install -f to resolve some dependancy issues).  Then I ran Steam and opted into the Steam Beta from settings once I logged in (need to do this to get access to in-home streaming... host PC needs to be opted in too).

Check Steam Settings for the list of PCs.

**Comment by nickbailuc** [comment]
If people are still having problems, the following commands worked well for me:

sudo iptables -I INPUT -p udp --dport 27031 -j ACCEPT
sudo iptables -I INPUT -p udp --dport 27036 -j ACCEPT
sudo iptables -I INPUT -p tcp --dport 27036 -j ACCEPT
sudo iptables -I INPUT -p tcp --dport 27037 -j ACCEPT

as well as the later suggested

sudo iptables -I INPUT -p tcp --dport 37804 -j ACCEPT

I input all of them into the Chrome shell, and got both steam to recognize other computers on the lan, and game streaming to work. Tested video, and mouse keyboard input, all of which work without any problems. Did not test sound however, but I'm sure it works as well.

To find this I had to navigate through one post referring to the other, in the end it was on reddit:
 https://www.reddit.com/r/Crouton/comments/1xj9qz/has_anyone_been_able_to_use_steam_inhome_streaming/chi5m30/

I kind of wish I solved this problem after exams, not a week before :D

**Comment by DennisLfromGA** [comment]
This might be worthy of a 'Steam wiki' page since the only other mention of opening ports that I found pertains to '[Running servers in crouton](https://github.com/dnschneid/crouton/wiki/Running-servers-in-crouton)'.

-**DennisLfromGA**
