### ISSUE TITLE
How can I swap left control with search keys when using the Crouton 'keyboard' target?

### ISSUE THREAD

**Issue by darcyparker** [dnschneid/crouton#811]
On a typical modern keyboard (88/101/102 keys) I (like many others) like to map Capslock to CTRL.  (I normally don't swap the left CTRL and Capslock because I have no need for Capslock.)

In ChromeOS it is easy to swap the Ctrl and Search keys. And when I ssh into my crouton chroot, I get the desired experience.

But when I am using xfce, (jessie with the Crouton 'keyboard' target included), I am having difficulties figuring out how to swap the CTRL and Search keys.

I read https://github.com/dnschneid/crouton/wiki/Keyboard and `man xmodmap` and tried things like:
```bash
xmodmap -e "keycode 133 = Control_L"
xmodmap -e "keycode 37 = Overlay1_Enable"
```
but this hasn't work for me.

I'd like to have the 'keyboard' target provided by crouton because I like being able to enter F11 and F12 by pressing "Search" and "-", and "Search" and "+" respectively.  But I'd like to swap the Search and Ctrl keys.

I suspect there is something that is non obvious about how the mappings in the keyboard target are stacking up.

Has anyone else figured this out? And if so, can you please share how you did it? Thanks.

**Comment by morsedl** [comment]
Sure!  I can probably get to doing so by either mid-January or hopefully
by end of January (I'm in the throws of preparing a written and oral
defense for my dissertation proposal).  I've added a reminder to my
to-do system to ensure I get it done.

Are there particular things, over and above what I've already written
--- revised, better integrated, and re-contextualized for a more general
audience, of course --- that you or he are wanting me to include or cover?

**Comment by dnschneid** [comment]
Thanks!  Use your best judgement; you're far deeper into keyboard customization than I've ever gone.

**Comment by tonyxue** [comment]
@drinkcat 's solution, which is written in the wiki already:

> @darcyparker : Gave it a quick try, and I believe this is the way to go:
```
> xmodmap -e "keycode 133 = Control_L"
> xmodmap -e "keycode 37 = Overlay1_Enable"
> xmodmap -e "add control = Control_L"
> xmodmap -e "remove control = Overlay1_Enable"
```
caused an error in my ubuntu 14.04 w/ xfce chroot:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  118 (X_SetModifierMapping)
  Value in failed request:  0x17
  Serial number of failed request:  11
  Current serial number in output stream:  11
```
after running ```xmodmap -e "add control = Control_L" ```

##### After checking ``` xmodmap``` at every step, I discovered: #####
After running ```xmodmap -e 'keycode 133 = Control_L'``` the ```Control_L``` is somehow automatically mapped to ```mod4```, which is causing the error above. 
So here an extra ```xmodmap -e 'remove mod4 = Control_L'``` should be added to correct it.


*I intended to change the wiki but I am not sure what exactly the reason is and I am not 100% sure what I have done is the best or the most appropriate to solve the error. So posting it here for discussion.*

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
