### ISSUE TITLE
Installing SteamOS on Chromebook query.

### ISSUE THREAD

**Issue by gizmo683** [dnschneid/crouton#821]
To install SteamOS in Unity all you need to do is install SteamOS Compositor and SteamOS Modeswitch Inhibitor and you can then choose the SteamOS GUI from the Welcome screen. I've installed both of these.

Running "-l /usr/sahre/xsessions/" gives me:
"-rw-r--r-- 1 root root 134 oct 23 2013 steamos.desktop"
along with the other GUI info,

I've tried every way of being able to get to the Welcome screen that I can find online.

Is it possible to change to this GUI within the Crout?

**Comment by DennisLfromGA** [comment]
Please re-open if this issue is still a concern.
