### ISSUE TITLE
Backup chroot "File too large"

### ISSUE THREAD

**Issue by philspence** [dnschneid/crouton#823]
I just tried to backup my chroot (it is about 25GB in size) and it turns the following:

gzip: stdout: File too large
Unable to back up 
Deleting partial archive

The chroot runs of a USB3.0 drive and I'm backing up to an external HDD with 1TB storage and about 990GB free so space isn't an issue.

Is it possible to backup (and then later restore) with multiple smaller tars? or a way around this file size limit? Thanks!

**Comment by dnschneid** [comment]
This is now in the latest crouton.
