### ISSUE TITLE
qjackctl/alsa issues

### ISSUE THREAD

**Issue by mlittle5** [dnschneid/crouton#826]
So I am still having audio issues after trying a lot of different things I found on here. qjackctl will not start up a server and alsamixer is still only showing one channel so I'm assuming it is not  set up correctly. I just updated crouton today so it is the latest and greatest and even did the audio target. 

qjackctl output:

'''
12:23:33.295 Patchbay deactivated.
12:23:33.316 Statistics reset.
12:23:33.414 Could not open ALSA sequencer as a client. ALSA MIDI patchbay will be not available.
ALSA lib seq_hw.c:457:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied
(qjackctl:6485): Gtk-CRITICAL *_: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
(qjackctl:6485): Gtk-CRITICAL *_: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
12:23:35.909 D-BUS: Service is available (org.jackaudio.service aka jackdbus).
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
12:23:38.343 D-BUS: JACK server could not be started. Sorry
Sun May 18 12:23:37 2014: Starting jack server...
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
(qjackctl:6485): Gtk-CRITICAL *_: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
(qjackctl:6485): Gtk-CRITICAL *_: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
Sun May 18 12:23:38 2014: JACK server starting in realtime mode with priority 10
Sun May 18 12:23:38 2014: ERROR: Cannot lock down 82278944 byte memory area (Cannot allocate memory)
Sun May 18 12:23:38 2014: ERROR: control open "hw:0" (No such file or directory)
Sun May 18 12:23:38 2014: ERROR: control open "hw:0" (No such file or directory)
Sun May 18 12:23:38 2014: creating alsa driver ... hw:0|hw:0|1024|2|44100|0|0|nomon|swmeter|-|32bit
Sun May 18 12:23:38 2014: ERROR: control open "hw:0" (No such file or directory)
Sun May 18 12:23:38 2014: ERROR: ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
Sun May 18 12:23:38 2014: ERROR: Cannot initialize driver
Sun May 18 12:23:38 2014: ERROR: JackServer::Open failed with -1
Sun May 18 12:23:38 2014: ERROR: Failed to open server
Sun May 18 12:23:39 2014: Saving settings to "/home/morg/.config/jack/conf.xml" ...
12:23:41.640 Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
'''

I have tried changing the device output in the settings but it has not given me different results.

**Comment by freshdried** [comment]
@Slapp62 and anyone else, I've had success in implementing the aforementioned second method, namely accessing audio hardware directly with JACK. I've posted a [guide on the wiki](https://github.com/dnschneid/crouton/wiki/Access-audio-hardware-directly-(ALSA,-JACK)).

**Comment by jessaustin** [comment]
What should I do if the sound is very distorted and muffled with no treble frequencies? While I have jack running, even "native" chrome sounds this way (jack stuff does too), while after jackd is stopped native chrome stuff sounds normal again.

**Comment by eritain** [comment]
Same problem as jessaustin with using jack->cras, including bad sound on the Chrome side, fixed only by stopping Jack.

**Comment by niko** [comment]
@drinkcat: Is there a way to forward jack to cras from a chroot without x11?

**Comment by Allov** [comment]
I got an ARM asus C201 Chromebook and a Focusrite Scarlett 2i2 a week ago and I cannot get this to work. I tried all sorts of thing and I got it working only once (the first time). Then, I disconnected the 2i2 so I could use the laptop alone, plugged it back in and it was gone.

Audacity would only record loud noises, but playback seems fine (Recording worked fine the first time as well).

Now, I tried these steps, including the midi fix since qjackctl complained about it (I don't use midi). But, qjackctl won't fire up. I see the window come up for half a second and it just close. Nothing in the console, just a silent crash.

This is my fourth time redoing everything from scratch following the Crouton Audio Hardware access guide, the Full Blown ARM guide, and some ARM jackd2 patch. None of these worked so far with different results.

Anyone with some kind of tips is welcome, I'm losing hopes...

**Comment by mahasamoot** [comment]
The instructions above worked well.  However, jack is complaining that it cannot lock down the memory area.  I found other sites that talk about that problem, and have verified that the limits file and is correct and I'm in the audio group.  Given that this is correct, it seems to be related to crouton.  I'm running trusty, with lxde-desktop, on ARM (Nvidia tegra K1).  Please advise.

**Comment by coderofsalvation** [comment]
try increasing Frames/Periods to prevent distorted (sometimes even muted) sound. In some cases when hardware cannot be locked down properly, checking 'No memory-lock' and 'Soft-mode' and unchecking 'realtime' can fix it.

**Comment by coderofsalvation** [comment]
Ok I've officially bumped myself multiple times on this issue :)
Therefore, I've updated the 'JACK to CRAS'-instruction in the wiki, with the advice: for day-to-day JACK usage just start jackd like this:

```
usr/bin/jackd -r -s -v -d alsa -P cras &  # 'cras' does not show up in qjackctl..you're welcome :)
qjackctl &
```

> Just put it in /etc/X11/xinit/xinitrc etc. Don't start jackd using qjackctl: just do it before qjackctl.

I might be overreacting but the fact that 'cras' is not showing up in qjackctl is so counterintuitive: all your future debugging-sessions are basically doomed.
You have been warned :)
