### ISSUE TITLE
Switch to graphical chroot with a Chrome App

### ISSUE THREAD

**Issue by fbreitwieser** [dnschneid/crouton#847]
Hi, I'd like to have an icon in the Chrome taskbar to switch to the graphical crouton session, as I find the keyboard shortcut cumbersome. I found no Chrome App, which would do this.

I'll try to develop one, if there's none. What is the best way to switch the graphical chroot within an App? 

I can think of the command `sudo enter-chroot exec sh -c 'croutoncycle next'`, but for sure that's not the most direct way.

**Comment by Venryx** [comment]
You can modify the Secure Shell app source code, install your custom version over the original (using extensions page "Load unpacked extension"), then launch the "Crosh Window" app/icon to have your custom shell code run. As seen here: https://github.com/dnschneid/crouton/issues/369#issuecomment-349793600
