### ISSUE TITLE
Core installation should set proper locale for Unicode characters.

### ISSUE THREAD

**Issue by GirlBossRush** [dnschneid/crouton#85]
I battled with Unicode character issues for about a week and found the solution to my troubles. My chroot installation is the core package and I use Crosh Window to login. I use ZSH as my shell with Oh-My-ZSH and the default theme has a Unicode arrow next to the command line. Tab completion would duplicate the text on the screen until I found that the locale was not set. Running:

``` sh
sudo locale-gen en_US.UTF-8 UTF-8
sudo update-locale LANG="en_US.UTF-8"
```

Will fix the issue for good. I'm not sure if it's possible to include this fix in the installation or at least document the issue for other users.

**Comment by torsava** [comment]
The problem persists, and it's a bit different to solve it on Debian sid:

- Open file /etc/locale.gen in your favourite text editor.
- Uncomment line "# en_US.UTF-8 UTF-8" and save file.
- sudo locale-gen
- sudo update-locale LANG="en_US.UTF-8"
- sudo update-locale LC_ALL="en_US.UTF-8"

That should do it. Happy chrooting!

**Comment by 0xMF** [comment]
As there was no file /etc/locale.gen in the default install of Debian sid (xfce4), I solved this issue as follows:

1. Add locales to Debian sid and configure
- sudo apt install locales
- sudo dpkg-reconfigure locales
- In the dialog that appears: Select  "en_US.UTF-8 UTF-8" and click OK

2. Update xfce4-terminal settings to show Unicode (Edit->Preferences->Advanced->Encoding and select UTF-8).
