### ISSUE TITLE
Can't switch back to xfce4 after going from ChromeOS to xfce4 to ChromeOS

### ISSUE THREAD

**Issue by lolwatpear** [dnschneid/crouton#884]
I'm following this guide to install elementary os on my c720:

https://docs.google.com/document/d/1Mj7r8QzONMUHBSIMHWLgmRCS-EfefeYj-3-AO9wt_00/edit

My issue it that after going to the Ubuntu desktop and coming back to ChromeOS, I am unable to use crtl alt shit forward/back to go back to Ubuntu.  What happens if I try doing that hotkey a few times, its destkop will quickly flash, but I'll remain in ChromeOS.  If I restart the chromebook, it will switch once and do the same thing.  The weird thing is that one out of the many times I tried doing this (after a powerwash), it actually worked with no issue.  Then I had to powerwash the chromebook again, because I corrupted the hard drive, and it once again did this.  After switching back to chromeOS after being in ubuntu it gives me this:

(==) Log file: "/var/log/Xorg.1.log", Time: Fri Jun 13 14:57:07 2014
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
vesa: Ignoring device with a bound kernel driver
xfce4-session: No gpg or ssh authentication agent found

(xfce4-session:14690): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(Thunar:14706): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfce4-panel:14704): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(polkit-gnome-authentication-agent-1:14712): GLib-CRITICAL **: g_variant_new_string: assertion `string != NULL' failed

(polkit-gnome-authentication-agent-1:14712): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(xfwm4:14700): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfsettingsd:14721): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:14731): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(wrapper:14733): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(xfdesktop:14708): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:14708): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:14708): GLib-GIO-CRITICAL **: g_file_get_path: assertion `G_IS_FILE (file)' failed

(xfdesktop:14708): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

**Comment by gabrielhidasy** [comment]
"or CTL-ALT-Shift-F1/F2 if you're nasty." THANK YOU, this one is the only one that works for me (and inside the chroot I could use croutoncycle cros to go back to chromeOS)

**Comment by matsen** [comment]
Ditto the last comment. I suggest putting the F1/F2 key combos in the documentation.
