### ISSUE TITLE
Specific Questions Regarding WebEX Functionality in Chromebook/Crouton Install

### ISSUE THREAD

**Issue by henyates** [dnschneid/crouton#886]
David, others,

I now have a Intel "Haswell" based Chromebook (Dell Chromebook 11), and I'd like to try again to get WebEX up and running on it.

I have the following questions that I'd like someone on the forum to address, if possible:
1.  What linux version / desktop target would you recommend when running the crouton script?
2.  What version of Java (i.e. Oracle or OpenJDK, 6 or 7, 32 or 64 bit) do I need to install??  I have no plans to be a Java developer. . .I'm looking for the minimum install of Java that will allow me to use WebEX. . .i.e. will the runtime environment provide all that I need for WebEX?
3.  Do I need to install 32-bit libraries?
4.  What web-browser plugin??  IcedTea, other??
5. What browser works best for getting WebEX to run - FireFox, Chromium or Chrome?
6.  Please provide specific instructions for installing Java, getting the symbolic links in place for the browser-plugin to work, installing any missing libraries, etc. . .

I'm hoping that someone who's actually gotten WebEX to work on an Intel-based Chromebook can respond with detailed instructions. . .I've reviewed many "tutorials" on the web thus far on this topic, and they all leave out some elements. . .I've not had any success in getting WebEX to work by following them. . .

Thanks in advance for any help that you can provide. . .

**Comment by meltonryan** [comment]
@dnschneid Could you give the answer you stated previously, but for a 64 bit processor?  I am on an Asus C300 with crouton set-up on Ubuntu 12.04, Unity.

My specs are:
Version 44.0.2403.90 (64-bit)
Platform 7077.95.0 (Official Build) stable-channel quawks
Firmware Google_Quawks.5216.204.6

and could really use help getting WebEx to work for my setup.

**Comment by dnschneid** [comment]
Those instructions *are* for 64-bit chroots.  WebEX uses 32-bit binaries regardless of your architecture.

**Comment by meltonryan** [comment]
The reason I questioned that in the first place, was that several of the files listed, did not exist via apt-get with the i386 tag, and some did not exist as packages for 12.04.  

I may have gotten it to work regardless after installing many of the listed packages one at a time, then reinstalling oracle-java7-installer.  I suppose I'll find out for sure tomorrow when my class meets for the first time.

I may be back with questions.

**Comment by meltonryan** [comment]
Okay.  Now I have gotten web-ex to work partially.  I can view desktop sharing, but I get the message that "The Audio device is unaccessible now."  I can't seem to figure this out now.

I also updated to trusty tahr, and followed your directions above.
