### ISSUE TITLE
Nested mount points not being unmounted

### ISSUE THREAD

**Issue by thankyousam** [dnschneid/crouton#893]
I'm running my chroots from a SD Card partition located at /media/removable/crouton/chroots.  My /usr/local/chroots/ is a symlink to the chroots directory on the SD card.  (The /crouton/ part of the SD Card is the partition (ext4) label which usually gets picked up as /dev/sdb1)

When I enter my chroot it makes an additional mount point to /dev/sdb1 at the SD Card partition in the chroot's /var/host/media folder.  Mount (having exited the chroot) gives the following for the partition.

/dev/sdb1 on /media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)
/dev/sdb1 on /media/removable/crouton/chroots/trusty/var/host/media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)

Within the chroot it shows a single mount on /dev/sdb1, which makes sense given the above.

/dev/sdb1 on /var/host/media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)

When I exit the chroot that additional mount point is not removed, as shown above.  Things then start to get messy if I enter the chroot again another mount point is created at the next level down for both the above mounts, so mount shows the following having exited the 2nd chroot.  

/dev/sdb1 on /media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)
/dev/sdb1 on /media/removable/crouton/chroots/trusty/var/host/media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)
/dev/sdb1 on /media/removable/crouton/chroots/trusty/var/host/media/removable/crouton/chroots/trusty/var/host/media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)
/dev/sdb1 on /media/removable/crouton/chroots/trusty/var/host/media/removable/crouton/chroots/trusty/var/host/media/removable/crouton/chroots/trusty/var/host/media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)
/dev/sdb1 on /media/removable/crouton/chroots/trusty/var/host/media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)
/dev/sdb1 on /media/removable/crouton/chroots/trusty/var/host/media/removable/crouton/chroots/trusty/var/host/media/removable/crouton type ext4 (rw,nosuid,nodev,noexec,relatime,dirsync,data=ordered)

Doing this a 3rd time results in a total of 43 mounts on /dev/sdb1.

Sometimes this can be fixed by manually removing the SD Card, but other times I need to power down and restart the Chromebook.

**Comment by hansvb** [comment]
I still have this problem (or at least a **very** similar one) with an external USB disk on a Toshiba Chromebook 2 CB35.

**Comment by lukenowak** [comment]
I have this issue while using crouton on SD card. It does not matter if I used -p or symlink /usr/local/chroots - the problem appears.

```
$ crouton -V
crouton: version 1-20170901092920~master:0216f9d1
```
