### ISSUE TITLE
How to mount USB drive with exec

### ISSUE THREAD

**Issue by Epowerj** [dnschneid/crouton#928]
I want to mount a USB drive (/dev/sdb1) with exec so I can install steam games on it, but fstab doesn't seem to work. I've also learned that Chrome OS mounts with noexec by default. 

How do you mount a USB drive with exec?

**Comment by trusktr** [comment]
Can I do this with the home folder? How can I make the home folder have `exec` permanently? There's no `/etc/fstab` which I'm normally used to.

**Comment by trusktr** [comment]
Cool,

```sh
sudo mount -i -o remount,exec /home/chronos/user
```

works. (`-i` was required). I guess I can just put that in my bashrc or zshrc.

**Comment by trusktr** [comment]
Maybe also have bash check if the `noexec` option is currently enabled, and only run the above command when `noexec` is present, to avoid running it for every terminal you open.
