### ISSUE TITLE
Praise for Crouton, and a few questions regarding possible security improvements

### ISSUE THREAD

**Issue by engineergoff** [dnschneid/crouton#93]
If I am posting this in the wrong place, I apologize.  This really isn't an issue, but I was unsure where else to post it.  First, I want to thank the folks who are developing this technology.  It's pretty fantastic.  More to the point, it got me out of a pretty tight jam the other day; for which I am grateful.  By way of thanks, I'd like to make a suggestion, which I hope is helpful.  

To explain, I had been on the fence about installing Crouton on my Chromebook, since I heard of the project about a month ago.   I read the "read me" notes on the project page, and was a little wary of the possible security risks, but decided to take the plunge when my primary home machine, which ran Mint Linux, decided to lose its video card. Since I only ever used the thing for work, lets just say this put me in a bit of a bind.

So, I installed the XFCE target, then Ubuntu's Software Center, and away I went.  Frankly, I've been stunned by how well the "Guest OS" functions.  After a few days of using it, I have to say, I haven't really had any major issues. 

Here is the thing though, I'm still a little concerned about security.  I installed to my SD card, for the sake of additional storage, and if I loose that card, anyone who happens upon it would have total access to my files.  I realize I could have encrypted the Chroot, but the tutorial I was using didn't really explain how, and besides the encryption is really only as good as the password.  

Anyway I was thinking this over, when I had a few ideas I thought might enhance the security of your system.  If I am way off base here, I apologize.

The way I see it, the security issues for Crouton amount to three basic problems. First, the root file system on Chrome OS is exposed to attacks from the Guest OS side.  Second, the Guest OS can be corrupted, from either the Chrome OS, or Guest OS side, because the total guest file system is exposed, even if the Chroot is encrypted.  Third, if the device, or in the case of those who install to a SD, the memory card are stolen, then my data is much less secure than it would have been.  I like to suggest ways of addressing these issues; if I might, but since you folks know a heck of a lot more than me about this stuff, I'll phrase my suggestion in the form of a question.  
1. Could Crouton be made to encrypt the entire Guest OS file system, in such a way that these files would be "unpacked" and loaded when the guest OS was started, and further Guest OS was installed?  

**I realize that right now Crouton is not an "app" which runs every time the Guest OS is called; but I think it might be beneficial if it did.  I'm more asking is such a thing is possible.  I feel this would resolve the issues related to data security.**
1.  If this is possible, could these files be saved to a protected partition of my hard drive, or an SD card, in such a way that they could not be deleted or accessed; except via a call to run by the revised Crouton "app", which would logically speaking have to handle the Guest OS start up? I feel this would eliminate the issues with physical security of the device, unless it was stolen while I was logged in, in which case all my files are exposed anyway.
2. Lastly, could a target Guest OS be rewritten to ignore the Host OS root file system entirely?  By this I mean, could it be locked down in such a fashion that the Chrome OS file system would be usable by the Guest OS in as much as such a thing is necessary, but not accessible by any programs running on it, and not visible at all to the end user from the guest OS side?  I feel this would eliminate the threat of attacks on the Chrome OS files system, being directed from the Guest OS side.
3.  Could this modified version of Crouton be set up in such a way as to make installation of any target Guest OS without the modifications suggested above impossible?  Or maybe just throw some really scary warning at folks...whatever makes you smile.

Anyway, I drug this on way longer than I wanted to.  Sorry about that.  I really love Crouton, it's made me like my Chromebook a lot more.  Best of luck in your future development.

Yours,
Bruce Goff

**Comment by peterwilli** [comment]
@engineergoff I'm not sure if you're still working on this, but this has been on my mind as well. What I've tried besides Crouton (which I'm using at the moment) is the new Android-subsystem in ChromeOS, that allowed me to run this GnuRoot Debian (https://play.google.com/store/apps/details?id=com.gnuroot.debian).

It's a graphical Linux distro without emulation (so pretty fast) inside an Android app. It has a 'fake root' that gives you full access and allows you to run several applications.

Unfortunately I had to stop using it. The reason why is because the Android-subsystem on ChromeOS runs in a 32-bit architecture, even though my chrom
