### ISSUE TITLE
Aura freezes when X11 apps run on native chromebook display

### ISSUE THREAD

**Issue by sunaku** [dnschneid/crouton#931]
Hello,

When I connect my Acer C720 chromebook to an external monitor via HDMI and then close the lid (so that the only display available to the X server is the external monitor), I am able to run X11 apps successfully on the _same_ X server as the Aura window manager using the `host-x11` script provided by Crouton:

```sh
# treat Aura as a desktop so that "show desktop" works correctly in openbox
# and also so that Aura is not listed in the Alt-Tab window menu in openbox
# see https://github.com/chjj/compton/issues/118#issuecomment-19513709
host-x11 xprop -name aura_root_0 -f _NET_WM_WINDOW_TYPE 32a -set _NET_WM_WINDOW_TYPE _NET_WM_WINDOW_TYPE_DESKTOP
host-x11 openbox &
host-x11 xterm
```

However, when I open the lid on my chromebook (so that there are 2 displays available to the X server), the chromebook's native display keeps cycling between on/off states and the external monitor keeps cycling between blank/nonblank states. :cyclone:

At this point, when I disconnect the external monitor from my chromebook by unplugging the HDMI cable, my chromebook's native display settles down (stops cycling between on/off states) and shows me my current ChromeOS session.  However, everything is _frozen_:  Aura does not repaint itself anymore until I terminate all X11 apps (minimizing the X11 apps doesn't work; Aura wants them gone for good!) so I have to awkwardly fish around the screen for close buttons on existing X11 apps (while the screen remains "stuck") and hit them all. :bullettrain_front: 

Now, once all X11 apps are closed, Aura repaints itself and behaves normally. :sunglasses: 

Why does Aura play nice with X11 apps when there is only 1 external display but not when there are 2 simultaneous displays (1 external monitor + 1 chromebook native display) or when there is only the chromebook native display?  :cold_sweat:

Is there some kind of struggle for control between X11 apps and Aura in the latter 2 cases?  If so, what is the former case doing correctly to prevent this issue? :confused: 

Thanks for your consideration.

**Comment by dnschneid** [comment]
Freon and xiwi pretty much make this obsolete.
