### ISSUE TITLE
xmodmap modifications don't survive switching out of crouton

### ISSUE THREAD

**Issue by aspergerish** [dnschneid/crouton#953]
xmodmap modifications don't survive switching back to ChromeOS then back to Unity.

also, .Xmodmap doesnt seem to work, and I am using xmodmap ~/.Xmodmap to map the keys

ubuntu trusty using unity.

**Comment by Sunappnio** [comment]
Well, for any one who want to remap two keys, I have found a simple way
sudo vi /usr/share/X11/xkb/keycodes/evdev (you can make a bakup before doing this)
sudo rm /var/lib/xkb/*  (to clear cache)
and then restart the chroot.
