### ISSUE TITLE
Mounting (network)drives ext2/3/4 so they show up in chromeos Files App

### ISSUE THREAD

**Issue by divx118** [dnschneid/crouton#954]
I looked at the source of crosdisks and did some experimenting with dbus-send to mount a drive that will show up in the Files app.
First thanks to drinkcat for coming up with the idea of a loop device and testing it :)
Create a small fat32 loop device:

```
$ cd ~/Downloads; dd if=/dev/zero of=loop bs=1KB count=1024; sudo mkfs.vfat loop -n crouton_files; sudo losetup /dev/loop9 loop
```

Now we can mount the loop device with the following dbus-send command.
Note: 
- the empty string in the middle is for fs-type if leaving it empty it will try to auto  detect.
- the last array:string:"ro" are the mount options

```
$ dbus-send --print-reply --system --dest=org.chromium.CrosDisks /org/chromium/CrosDisks org.chromium.CrosDisks.Mount string:"/dev/loop9" string:"" array:string:"ro"
```

To monitor the dbus you can use the following:

```
dbus-monitor --system --monitor 'interface=org.chromium.CrosDisks'
```

Why: 
Support for ext2/3/4 will be dropped in the chromeos files app this is already active in dev channel see https://code.google.com/p/chromium/issues/detail?id=315401
Now we can use the small fat32 partition device to bindmount shared directory, ext2/3/4 formatted usb drives, network drives.
This would also solve https://github.com/dnschneid/crouton/issues/620 for a part.

Please feel free to discuss on how the approach should be to get this as a nice enhancement.

**Comment by nshaibu** [comment]
**_wow_**
