### ISSUE TITLE
Ctrl-Alt-Shift-Forward/Backward not working

### ISSUE THREAD

**Issue by evanlenz** [dnschneid/crouton#956]
I'm running crouton on a Chromebook 14. Starting it either as "sudo startxfce4" from the Chrome terminal, or "sudo enter-chroot" followed by "startxfce4".

When I had mistakenly run it as root, Ctrl-Alt-Shift-Forward/Backward worked perfectly. But now when running it as a non-root user, these no longer work. I can switch back to Chrome OS using Ctrl-Alt-Backward. But then Ctrl-Alt-Forward takes me to the "Developer Console" screen. Pressing Ctrl-Alt-Refresh then successfully gets me to the xfce desktop again. So it technically works (with the extra key press), but I'm hoping to simplify this as much as possible for my wife, whose computer this is.

From the terminal view (in Chrome OS), whenever I try to press Ctrl-Alt-Shift-Forward/Backward, the following is displayed:

/usr/local/bin/croutoncycle: 47: /usr/local/bin/croutoncycle: cannot create /tmp/crouton-lock/cycle: Permission denied

Does this indicate something is wrong? Or do we need to just live with the extra keypress?

Thanks!
Evan

**Comment by Dexterhill013** [comment]
says I need root to start
