### ISSUE TITLE
cannot get cron to work

### ISSUE THREAD

**Issue by city41** [dnschneid/crouton#957]
After setting up a crouton chroot, cron does not seem to work.

What I've done:
1. setup crouton following steps in README
2. `sudo enter-chroot`
3. `crontab -e`
- added `* * * * * echo "hi from cron" >> /home/matt/hiFromCron.txt"`
- after a few minutes, see no output at either `/home/matt` within the chroot or at the "real" /home/matt outside of the chroot (I went there and added a matt directory)

`ps -A | grep cron` returns nothing. It definitely looks like cron is not running.

But doing `sudo /etc/init.d/cron start` just produces "Rather than invoking init scripts through /etc/init.d, use the service(8) ..."

So I do `sudo service cron start` and get "Unknown job: cron"

And `sudo start cron` gives me "start: Unknown job: cron"

I'm not convinced this is a Crouton specific issue, but hoping I can get some pointers on what to try next.

**Comment by UT99310** [comment]
What is the best way to run scripts inside the chroot at shutdown or reboot, for cleanup, etc.? Thanks!

**Comment by dnschneid** [comment]
There's no official mechanism for it at the moment.  You may be able to make a script that gets run from rc.local that does nothing but wait for SIGTERM, and then performs your cleanup tasks.  `unmount-chroot` will SIGTERM all child processes if it can't unmount everything, and then SIGKILL five seconds later (so hopefully your cleanup takes less than five seconds :) ).

**Comment by UT99310** [comment]
Hmm. Thanks. Five seconds can be pretty tight for some stuff though.

**Comment by dnschneid** [comment]
You could modify unmount-chroot to change that timeout.  Otherwise, you'll probably have to try some other approach.  Also worth noting is that while there's a system dbus message that gets fired on shutdown, crouton doesn't actually respond to it, so even the SIGTERM approach may not work for the shutdown case...
