### ISSUE TITLE
moving chroot onto usb storage?

### ISSUE THREAD

**Issue by shadowkrazee** [dnschneid/crouton#960]
sudo edit-chroot -m ~/path/for/usb trusty

results in "failed to preserve ownership" errors for all of the following copy commands. what am i doing wrong?

**Comment by c0d3rm0nk3y** [comment]
impressive stuff.. thank you shadowkrazee and DennisLfromGA.  i put a 64GB chip in my c720 and found out i'm down to 1+ gigs of free space and thinking of moving it to a usb 3 external drive to let it grow some more.. 

lately though i have been using crouton in command line only.

a quick question i  have yet to find a definitive yes/no on.  using your examples from earlier i can move the crouton off local and onto a drive, am I correct in thinking it will expanded as needed their too?  or will i need to format my external drive?  (even though i've been using crouton for year i'm still a little fuzzy in a few areas).

i am thinking of doing the following.. move the current crouton to a big usb 3 drive so when i need to use a full gui experience it will be available to me. Next i'll power wash chromebook and create a fresh crouton but more focused on command line only (think i understand the how to do that from the github page).

**Comment by DennisLfromGA** [comment]
@c0d3rm0nk3y,

> ...am I correct in thinking it will expanded as needed their too? or will i need to format my external drive?

If you use -
 `sudo edit-chroot [chrootname] -m /path/to/external/drive/chroots/chrootname`, 
it will copy/move the entire chroot to the external drive.

If you use -
 `sudo sh ~/Downloads/crouton -f [path/to/tarball] -p /path/to/external/drive/` 
or
 `sudo edit-chroot -r -f [path/to/tarball] -c /path/to/external/drive/chroots -- [chrootname]` 
to restore a backed-up chroot, it will untar and uncompress it to the external drive.

*In either case, however, the script checks to ensure the external drive is of an ext2/3/4 format.*
There's a note listed under the `edit-chroot -m` option that says:
"If you are moving a chroot to a SD card/USB drive, make sure the storage is formatted to ext2/3/4."

**Comment by liamhetkoekie** [comment]
@DennisLfromGA i want to run 'sudo sh ~/Downloads/crouton -n sana -u' but i've installed sana to '/media/removable/USB/chroots' and i don't know how to change the default chroot path to do that, because crouton looks for chroots in the default folder, but there is nothing. Any help appreciated

**Comment by DennisLfromGA** [comment]
@liamhetkoekie - As mentioned a little earlier in this thread, just use crouton's '-p' option to specify the parent folder of where your chroot(s) reside. Something like this shouold work:

`sudo sh ~/Downloads/crouton -n sana -p /media/removable/USB -u`

**Comment by radumas** [comment]
In case anyone else starts reading this thread, please see https://github.com/dnschneid/crouton/issues/4026

**Comment by DennisLfromGA** [comment]
@radumas,

The method to install and run the `crouton` script has changed as mentioned in #4026, this doesn't break or affect how you run the chroot off of external media.

That has changed though with previous measures of tightening down security, see the following paragraph for more details about the new methods -

- [I want to install the chroot to another location](https://github.com/dnschneid/crouton#i-want-to-install-the-chroot-to-another-location)

*Hope this helps,*
-**DennisLfromGA**
