### ISSUE TITLE
New Mali Drivers support Hardware Acceleration?

### ISSUE THREAD

**Issue by xYuunaX** [dnschneid/crouton#964]
Hi David,

I was wondering if this would help in your development?

I stumbled across this:
http://krblogs.com/post/65347946766/mali-drivers-on-chromebook

Apparently the new drivers enables hardware-accelerated graphics rendering with X11.

If this has already been looked at and dismissed, please disregard.

Thanks!

**Comment by jman6495** [comment]
Did anyone get anywhere with running a second X server (sorry to "bump" this !) ?
More than anything, I'd love to be able to run gnome shell with reasonable performance on my ARM chromebook.
