### ISSUE TITLE
ChromeOS App to Launch a Chroot and an Android Chroot

### ISSUE THREAD

**Issue by nlvw** [dnschneid/crouton#972]
Not sure if this belongs here but I was wondering if 2 things are possible and if they might be incorporated in the future.
1.  is it possible to have a chromeos app that when you open it displays the available chroots and lets you click on one to launch it (basically a gui to launch chroots without having to open a terminal).  This would be just to launch chroots so you would still have to setup and use crouton to make the chroot before hand.
2.  Is there any plans to make android an available chroot that we can install.  So that we could chroot something like Android TV (when it comes out).

So these two basically come together to give you the best HTPC experience available all in one box.  For example you have a chromebox connected to your TV  you can use the gui app I mentioned to switch to android tv if you just want to consume Media (netflix, amazon instant video, hulu, google play) or you could switch to linux + steam big picture to game, locally or with in-home streaming.  You also still retain the chromeos  if you want to do basic web browsing or use streaming websites to watch videos.

Google has said they want to make android apps run on chromeos so question two may not be important.

**Comment by Venryx** [comment]
Number 1 is in fact possible, if you're fine with locally/manually installing a modified version of the Secure Shell app: https://github.com/dnschneid/crouton/issues/369#issuecomment-349793600
