### ISSUE TITLE
mounting over /usr/local isn't properly detected by the stateful_partition move script

### ISSUE THREAD

**Issue by millette** [dnschneid/crouton#976]
After installing crouton the first time, I soon realized I was going to run out of space. I was able to move the whole /usr/local subdirectory to a USB key and then I mounted /dev/sdb1 (or whatever) to /usr/local. Everything was working fine except for the sound, but that problem came up later.

Today, I tried to upgrade crouton -u -n wheezy but I got stuck on

    Migrating data from legacy chroots directory /usr/local/chroots to /mnt/stateful_partition/crouton/chroots...
    /mnt/stateful_partition/dev_image/chroots and /usr/local/chroots are not the same file as expected.

Perhaps it's due to the fact that I moved /usr/local after I first installed crouton? Any help would be appreciated.

P.S.: at one point, the upgrade almost seemed to work but it failed at the end compiling CRAS.

**Comment by dnschneid** [comment]
Fixed in the latest crouton.
