### ISSUE TITLE
Virtualbox on kernel 3.4.0 is very buggy

### ISSUE THREAD

**Issue by kevinkore3** [dnschneid/crouton#985]
When I start the chroot, I get a warning about error 127 about rc.local failing
It says "Operation not permitted" when I try to do sudo modprobe vboxdrv

I can manually fix this by manually disabling module_locking, then doing startxfce4 and installing my linux-image, then doing sudo modprobe vboxdrv, but that takes a long time.

There is also a bug when you open VirtualBox, the computer reboots, which seems to happen when I use bridged networking, which is unfortunately the fastest.

**Comment by rrolsbe** [comment]
I found out what was causing my Chromebook, C710 with 320GB drive, to reboot when launching VirtualBox VM's from crouton.  If the VM network settings is set to "Bridged Adapter", it will reboot.  All VM's work fine when the network settings are set to NAT the default.  I like to run my VM's bridged (all on same network) allowing me rdp, ssh rcp etc... between all nodes on my home network.

Regards, Ron
"
