### ISSUE TITLE
teamviewer - aka running deamons

### ISSUE THREAD

**Issue by retos** [dnschneid/crouton#99]
Has anyone accomplished to launch teamviewer?

**Comment by nashtag** [comment]
I can get teamviewer to work, but like you, I can't connect or sign in.

"I installed TeamViewer 8, and that has a "Ready to connect" message rather than the "check your connection" message. However, in the Computers and Contacts dialog, the Sign In box is still broken. If I click the Sign Up link, and select use an existing account, the Next button does not seem to do anything after I've entered my credentials."

**Comment by AlexanderKomarov** [comment]
@excel4 thank you for your advice! It's good point! Teamviewer7 works.

**Comment by forresthopkinsa** [comment]
Can confirm that initctl still shows `Unknown job: teamviewerd` when trying to install Teamviewer 10

**Comment by dnschneid** [comment]
Nothing has changed with upstart support; you still have to run the commands manually.

**Comment by forresthopkinsa** [comment]
Even then, doesn't work. I have yet to get Tv10 working on Crouton running Trusty.

**Comment by njatord** [comment]
went through the folders using a file manager and found the file, added a shortcut to the desktop and works like a charm.

**Comment by forresthopkinsa** [comment]
It's okay. We don't need to use Crouton for Teamviewing anymore. [Teamviewer 11 is now compatible directly with Chrome OS.](https://chrome.google.com/webstore/detail/teamviewer/oooiobdokpcfdlahlmcddobejikcmkfo)

**Comment by kajodowe** [comment]
forresthopkinsa -- Amen to that! Teamviewer 11 works wonderfully on the Chrome OS side to control a remote computer. I had the same issues as all users above and was not successful except to run it in Chrome.

**Comment by kajodowe** [comment]
Oh and one more comment! I am always using my Chromebook on the crouton side so having Teamviewer running on the Chrome OS side is great because keeps the remote system out of my hair (so to speak) except for when I want to control my desktop remotely.

**Comment by ikey4u** [comment]
Also I install teamview 11.0 on my ubuntu 14.04 x64, when i run  commmand `teamviewer --daemon start`,it gives me errors like:`
initctl start teamviewerd
initctl: Unknown job: teamviewerd
fail
`
,so i just run the command with sudo `sudo teamviewer --daemon start`,it works fine and is able to connect to the network.One reason causing this error is that you login in as root user,and if you do not run the command with sudo,teamviewer may think you are not ROOT,really weird things!
May this help someone.

**Comment by forresthopkinsa** [comment]
I'm not totally understanding what you're saying @ikey4u but have you tried using `sudo -h`?

**Comment by ikey4u** [comment]
@forresthopkinsa When you login in your system as root user,you may think you can run any commands  in root privileges by default,but its not true.In some cases,you should use `sudo` to  explicitly declare that you wanna to run the command in root privileges.For example ,you should run teamview with the command `sudo teamviewer --daemon start` but not the command `teamviewer --daemon start` even though you are root user.

**Comment by DennisLfromGA** [comment]
@ikey4u - You login into your system from crosh using `sudo` so 'root' can set things up, mounting directories, etc. *But*, you are logged into your *user account*, the one you specified when you installed your chroot. Therefore, you *don't* have root permissions and need to prefix commands/applicaitons that need root priveleges with `sudo`.

**Comment by ikey4u** [comment]
@DennisLfromGA  Wow! Excellent Explanation. Thank u  ~

**Comment by wallace11** [comment]
Just for future reference, I was able to run Team Viewer inside chroot by using the "Unofficially supported" tar.xz version (v12.0.76279) by simply dl, extract and run the teamviewer executable. No extra libs required for me, worked right away.
Hope this helps someone in the future ;)
